include::./index.adoc[]

[[v58-1-0]]
=== Hebreus, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v58-1-1]]

^<<v58-1-1,1>>^ Havendo Deus, outrora, falado, muitas vezes e de muitas maneiras, aos pais, pelos profetas,

[[v58-1-2]]

^<<v58-1-2,2>>^ nestes últimos dias, nos falou pelo Filho, a quem constituiu herdeiro de todas as coisas, pelo qual também fez o universo.

[[v58-1-3]]

^<<v58-1-3,3>>^ Ele, que é o resplendor da glória e a expressão exata do seu Ser, sustentando todas as coisas pela palavra do seu poder, depois de ter feito a purificação dos pecados, assentou-se à direita da Majestade, nas alturas,

[[v58-1-4]]

^<<v58-1-4,4>>^ tendo-se tornado tão superior aos anjos quanto herdou mais excelente nome do que eles.

[[v58-1-5]]

^<<v58-1-5,5>>^ Pois a qual dos anjos disse jamais: Tu és meu Filho, eu hoje te gerei? E outra vez: Eu lhe serei Pai, e ele me será Filho?

[[v58-1-6]]

^<<v58-1-6,6>>^ E, novamente, ao introduzir o Primogênito no mundo, diz: E todos os anjos de Deus o adorem.

[[v58-1-7]]

^<<v58-1-7,7>>^ Ainda, quanto aos anjos, diz: Aquele que a seus anjos faz ventos, e a seus ministros, labareda de fogo;

[[v58-1-8]]

^<<v58-1-8,8>>^ mas acerca do Filho: O teu trono, ó Deus, é para todo o sempre; e: Cetro de equidade é o cetro do seu reino.

[[v58-1-9]]

^<<v58-1-9,9>>^ Amaste a justiça e odiaste a iniquidade; por isso, Deus, o teu Deus, te ungiu com o óleo de alegria como a nenhum dos teus companheiros.

[[v58-1-10]]

^<<v58-1-10,10>>^ Ainda: No princípio, Senhor, lançaste os fundamentos da terra, e os céus são obra das tuas mãos;

[[v58-1-11]]

^<<v58-1-11,11>>^ eles perecerão; tu, porém, permaneces; sim, todos eles envelhecerão qual veste;

[[v58-1-12]]

^<<v58-1-12,12>>^ também, qual manto, os enrolarás, e, como vestes, serão igualmente mudados; tu, porém, és o mesmo, e os teus anos jamais terão fim.

[[v58-1-13]]

^<<v58-1-13,13>>^ Ora, a qual dos anjos jamais disse: Assenta-te à minha direita, até que eu ponha os teus inimigos por estrado dos teus pés?

[[v58-1-14]]

^<<v58-1-14,14>>^ Não são todos eles espíritos ministradores, enviados para serviço a favor dos que hão de herdar a salvação?

'''

xref:057-filemom/057-filemom-001.adoc#v57-1-0[&#60; Capítulo Anterior] | <<v58-1-0,Topo>> | xref:058-hebreus/058-hebreus-002.adoc#v58-2-0[Próximo Capítulo &#62;]