include::./index.adoc[]

[[v58-10-0]]
=== Hebreus, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v58-10-1]]

^<<v58-10-1,1>>^ Ora, visto que a lei tem sombra dos bens vindouros, não a imagem real das coisas, nunca jamais pode tornar perfeitos os ofertantes, com os mesmos sacrifícios que, ano após ano, perpetuamente, eles oferecem.

[[v58-10-2]]

^<<v58-10-2,2>>^ Doutra sorte, não teriam cessado de ser oferecidos, porquanto os que prestam culto, tendo sido purificados uma vez por todas, não mais teriam consciência de pecados?

[[v58-10-3]]

^<<v58-10-3,3>>^ Entretanto, nesses sacrifícios faz-se recordação de pecados todos os anos,

[[v58-10-4]]

^<<v58-10-4,4>>^ porque é impossível que o sangue de touros e de bodes remova pecados.

[[v58-10-5]]

^<<v58-10-5,5>>^ Por isso, ao entrar no mundo, diz: Sacrifício e oferta não quiseste; antes, um corpo me formaste;

[[v58-10-6]]

^<<v58-10-6,6>>^ não te deleitaste com holocaustos e ofertas pelo pecado.

[[v58-10-7]]

^<<v58-10-7,7>>^ Então, eu disse: Eis aqui estou (no rolo do livro está escrito a meu respeito), para fazer, ó Deus, a tua vontade.

[[v58-10-8]]

^<<v58-10-8,8>>^ Depois de dizer, como acima: Sacrifícios e ofertas não quiseste, nem holocaustos e oblações pelo pecado, nem com isto te deleitaste (coisas que se oferecem segundo a lei),

[[v58-10-9]]

^<<v58-10-9,9>>^ então, acrescentou: Eis aqui estou para fazer, ó Deus, a tua vontade. Remove o primeiro para estabelecer o segundo.

[[v58-10-10]]

^<<v58-10-10,10>>^ Nessa vontade é que temos sido santificados, mediante a oferta do corpo de Jesus Cristo, uma vez por todas.

[[v58-10-11]]

^<<v58-10-11,11>>^ Ora, todo sacerdote se apresenta, dia após dia, a exercer o serviço sagrado e a oferecer muitas vezes os mesmos sacrifícios, que nunca jamais podem remover pecados;

[[v58-10-12]]

^<<v58-10-12,12>>^ Jesus, porém, tendo oferecido, para sempre, um único sacrifício pelos pecados, assentou-se à destra de Deus,

[[v58-10-13]]

^<<v58-10-13,13>>^ aguardando, daí em diante, até que os seus inimigos sejam postos por estrado dos seus pés.

[[v58-10-14]]

^<<v58-10-14,14>>^ Porque, com uma única oferta, aperfeiçoou para sempre quantos estão sendo santificados.

[[v58-10-15]]

^<<v58-10-15,15>>^ E disto nos dá testemunho também o Espírito Santo; porquanto, após ter dito:

[[v58-10-16]]

^<<v58-10-16,16>>^ Esta é a aliança que farei com eles, depois daqueles dias, diz o Senhor: Porei no seu coração as minhas leis e sobre a sua mente as inscreverei,

[[v58-10-17]]

^<<v58-10-17,17>>^ acrescenta: Também de nenhum modo me lembrarei dos seus pecados e das suas iniquidades, para sempre.

[[v58-10-18]]

^<<v58-10-18,18>>^ Ora, onde há remissão destes, já não há oferta pelo pecado.

[[v58-10-19]]

^<<v58-10-19,19>>^ Tendo, pois, irmãos, intrepidez para entrar no Santo dos Santos, pelo sangue de Jesus,

[[v58-10-20]]

^<<v58-10-20,20>>^ pelo novo e vivo caminho que ele nos consagrou pelo véu, isto é, pela sua carne,

[[v58-10-21]]

^<<v58-10-21,21>>^ e tendo grande sacerdote sobre a casa de Deus,

[[v58-10-22]]

^<<v58-10-22,22>>^ aproximemo-nos, com sincero coração, em plena certeza de fé, tendo o coração purificado de má consciência e lavado o corpo com água pura.

[[v58-10-23]]

^<<v58-10-23,23>>^ Guardemos firme a confissão da esperança, sem vacilar, pois quem fez a promessa é fiel.

[[v58-10-24]]

^<<v58-10-24,24>>^ Consideremo-nos também uns aos outros, para nos estimularmos ao amor e às boas obras.

[[v58-10-25]]

^<<v58-10-25,25>>^ Não deixemos de congregar-nos, como é costume de alguns; antes, façamos admoestações e tanto mais quanto vedes que o Dia se aproxima.

[[v58-10-26]]

^<<v58-10-26,26>>^ Porque, se vivermos deliberadamente em pecado, depois de termos recebido o pleno conhecimento da verdade, já não resta sacrifício pelos pecados;

[[v58-10-27]]

^<<v58-10-27,27>>^ pelo contrário, certa expectação horrível de juízo e fogo vingador prestes a consumir os adversários.

[[v58-10-28]]

^<<v58-10-28,28>>^ Sem misericórdia morre pelo depoimento de duas ou três testemunhas quem tiver rejeitado a lei de Moisés.

[[v58-10-29]]

^<<v58-10-29,29>>^ De quanto mais severo castigo julgais vós será considerado digno aquele que calcou aos pés o Filho de Deus, e profanou o sangue da aliança com o qual foi santificado, e ultrajou o Espírito da graça?

[[v58-10-30]]

^<<v58-10-30,30>>^ Ora, nós conhecemos aquele que disse: A mim pertence a vingança; eu retribuirei. E outra vez: O Senhor julgará o seu povo.

[[v58-10-31]]

^<<v58-10-31,31>>^ Horrível coisa é cair nas mãos do Deus vivo.

[[v58-10-32]]

^<<v58-10-32,32>>^ Lembrai-vos, porém, dos dias anteriores, em que, depois de iluminados, sustentastes grande luta e sofrimentos;

[[v58-10-33]]

^<<v58-10-33,33>>^ ora expostos como em espetáculo, tanto de opróbrio quanto de tribulações, ora tornando-vos coparticipantes com aqueles que desse modo foram tratados.

[[v58-10-34]]

^<<v58-10-34,34>>^ Porque não somente vos compadecestes dos encarcerados, como também aceitastes com alegria o espólio dos vossos bens, tendo ciência de possuirdes vós mesmos patrimônio superior e durável.

[[v58-10-35]]

^<<v58-10-35,35>>^ Não abandoneis, portanto, a vossa confiança; ela tem grande galardão.

[[v58-10-36]]

^<<v58-10-36,36>>^ Com efeito, tendes necessidade de perseverança, para que, havendo feito a vontade de Deus, alcanceis a promessa.

[[v58-10-37]]

^<<v58-10-37,37>>^ Porque, ainda dentro de pouco tempo, aquele que vem virá e não tardará;

[[v58-10-38]]

^<<v58-10-38,38>>^ todavia, o meu justo viverá pela fé; e: Se retroceder, nele não se compraz a minha alma.

[[v58-10-39]]

^<<v58-10-39,39>>^ Nós, porém, não somos dos que retrocedem para a perdição; somos, entretanto, da fé, para a conservação da alma.

'''

xref:058-hebreus/058-hebreus-009.adoc#v58-9-0[&#60; Capítulo Anterior] | <<v58-10-0,Topo>> | xref:058-hebreus/058-hebreus-011.adoc#v58-11-0[Próximo Capítulo &#62;]