include::./index.adoc[]

[[v58-5-0]]
=== Hebreus, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v58-5-1]]

^<<v58-5-1,1>>^ Porque todo sumo sacerdote, sendo tomado dentre os homens, é constituído nas coisas concernentes a Deus, a favor dos homens, para oferecer tanto dons como sacrifícios pelos pecados,

[[v58-5-2]]

^<<v58-5-2,2>>^ e é capaz de condoer-se dos ignorantes e dos que erram, pois também ele mesmo está rodeado de fraquezas.

[[v58-5-3]]

^<<v58-5-3,3>>^ E, por esta razão, deve oferecer sacrifícios pelos pecados, tanto do povo como de si mesmo.

[[v58-5-4]]

^<<v58-5-4,4>>^ Ninguém, pois, toma esta honra para si mesmo, senão quando chamado por Deus, como aconteceu com Arão.

[[v58-5-5]]

^<<v58-5-5,5>>^ Assim, também Cristo a si mesmo não se glorificou para se tornar sumo sacerdote, mas o glorificou aquele que lhe disse: Tu és meu Filho, eu hoje te gerei;

[[v58-5-6]]

^<<v58-5-6,6>>^ como em outro lugar também diz: Tu és sacerdote para sempre, segundo a ordem de Melquisedeque.

[[v58-5-7]]

^<<v58-5-7,7>>^ Ele, Jesus, nos dias da sua carne, tendo oferecido, com forte clamor e lágrimas, orações e súplicas a quem o podia livrar da morte e tendo sido ouvido por causa da sua piedade,

[[v58-5-8]]

^<<v58-5-8,8>>^ embora sendo Filho, aprendeu a obediência pelas coisas que sofreu

[[v58-5-9]]

^<<v58-5-9,9>>^ e, tendo sido aperfeiçoado, tornou-se o Autor da salvação eterna para todos os que lhe obedecem,

[[v58-5-10]]

^<<v58-5-10,10>>^ tendo sido nomeado por Deus sumo sacerdote, segundo a ordem de Melquisedeque.

[[v58-5-11]]

^<<v58-5-11,11>>^ A esse respeito temos muitas coisas que dizer e difíceis de explicar, porquanto vos tendes tornado tardios em ouvir.

[[v58-5-12]]

^<<v58-5-12,12>>^ Pois, com efeito, quando devíeis ser mestres, atendendo ao tempo decorrido, tendes, novamente, necessidade de alguém que vos ensine, de novo, quais são os princípios elementares dos oráculos de Deus; assim, vos tornastes como necessitados de leite e não de alimento sólido.

[[v58-5-13]]

^<<v58-5-13,13>>^ Ora, todo aquele que se alimenta de leite é inexperiente na palavra da justiça, porque é criança.

[[v58-5-14]]

^<<v58-5-14,14>>^ Mas o alimento sólido é para os adultos, para aqueles que, pela prática, têm as suas faculdades exercitadas para discernir não somente o bem, mas também o mal.

'''

xref:058-hebreus/058-hebreus-004.adoc#v58-4-0[&#60; Capítulo Anterior] | <<v58-5-0,Topo>> | xref:058-hebreus/058-hebreus-006.adoc#v58-6-0[Próximo Capítulo &#62;]