include::./index.adoc[]

[[v58-2-0]]
=== Hebreus, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v58-2-1]]

^<<v58-2-1,1>>^ Por esta razão, importa que nos apeguemos, com mais firmeza, às verdades ouvidas, para que delas jamais nos desviemos.

[[v58-2-2]]

^<<v58-2-2,2>>^ Se, pois, se tornou firme a palavra falada por meio de anjos, e toda transgressão ou desobediência recebeu justo castigo,

[[v58-2-3]]

^<<v58-2-3,3>>^ como escaparemos nós, se negligenciarmos tão grande salvação? A qual, tendo sido anunciada inicialmente pelo Senhor, foi-nos depois confirmada pelos que a ouviram;

[[v58-2-4]]

^<<v58-2-4,4>>^ dando Deus testemunho juntamente com eles, por sinais, prodígios e vários milagres e por distribuições do Espírito Santo, segundo a sua vontade.

[[v58-2-5]]

^<<v58-2-5,5>>^ Pois não foi a anjos que sujeitou o mundo que há de vir, sobre o qual estamos falando;

[[v58-2-6]]

^<<v58-2-6,6>>^ antes, alguém, em certo lugar, deu pleno testemunho, dizendo: Que é o homem, que dele te lembres? Ou o filho do homem, que o visites?

[[v58-2-7]]

^<<v58-2-7,7>>^ Fizeste-o, por um pouco, menor que os anjos, de glória e de honra o coroaste [e o constituíste sobre as obras das tuas mãos].

[[v58-2-8]]

^<<v58-2-8,8>>^ Todas as coisas sujeitaste debaixo dos seus pés. Ora, desde que lhe sujeitou todas as coisas, nada deixou fora do seu domínio. Agora, porém, ainda não vemos todas as coisas a ele sujeitas;

[[v58-2-9]]

^<<v58-2-9,9>>^ vemos, todavia, aquele que, por um pouco, tendo sido feito menor que os anjos, Jesus, por causa do sofrimento da morte, foi coroado de glória e de honra, para que, pela graça de Deus, provasse a morte por todo homem.

[[v58-2-10]]

^<<v58-2-10,10>>^ Porque convinha que aquele, por cuja causa e por quem todas as coisas existem, conduzindo muitos filhos à glória, aperfeiçoasse, por meio de sofrimentos, o Autor da salvação deles.

[[v58-2-11]]

^<<v58-2-11,11>>^ Pois, tanto o que santifica como os que são santificados, todos vêm de um só. Por isso, é que ele não se envergonha de lhes chamar irmãos,

[[v58-2-12]]

^<<v58-2-12,12>>^ dizendo: A meus irmãos declararei o teu nome, cantar-te-ei louvores no meio da congregação.

[[v58-2-13]]

^<<v58-2-13,13>>^ E outra vez: Eu porei nele a minha confiança. E ainda: Eis aqui estou eu e os filhos que Deus me deu.

[[v58-2-14]]

^<<v58-2-14,14>>^ Visto, pois, que os filhos têm participação comum de carne e sangue, destes também ele, igualmente, participou, para que, por sua morte, destruísse aquele que tem o poder da morte, a saber, o diabo,

[[v58-2-15]]

^<<v58-2-15,15>>^ e livrasse todos que, pelo pavor da morte, estavam sujeitos à escravidão por toda a vida.

[[v58-2-16]]

^<<v58-2-16,16>>^ Pois ele, evidentemente, não socorre anjos, mas socorre a descendência de Abraão.

[[v58-2-17]]

^<<v58-2-17,17>>^ Por isso mesmo, convinha que, em todas as coisas, se tornasse semelhante aos irmãos, para ser misericordioso e fiel sumo sacerdote nas coisas referentes a Deus e para fazer propiciação pelos pecados do povo.

[[v58-2-18]]

^<<v58-2-18,18>>^ Pois, naquilo que ele mesmo sofreu, tendo sido tentado, é poderoso para socorrer os que são tentados.

'''

xref:058-hebreus/058-hebreus-001.adoc#v58-1-0[&#60; Capítulo Anterior] | <<v58-2-0,Topo>> | xref:058-hebreus/058-hebreus-003.adoc#v58-3-0[Próximo Capítulo &#62;]