include::./index.adoc[]

[[v58-12-0]]
=== Hebreus, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v58-12-1]]

^<<v58-12-1,1>>^ Portanto, também nós, visto que temos a rodear-nos tão grande nuvem de testemunhas, desembaraçando-nos de todo peso e do pecado que tenazmente nos assedia, corramos, com perseverança, a carreira que nos está proposta,

[[v58-12-2]]

^<<v58-12-2,2>>^ olhando firmemente para o Autor e Consumador da fé, Jesus, o qual, em troca da alegria que lhe estava proposta, suportou a cruz, não fazendo caso da ignomínia, e está assentado à destra do trono de Deus.

[[v58-12-3]]

^<<v58-12-3,3>>^ Considerai, pois, atentamente, aquele que suportou tamanha oposição dos pecadores contra si mesmo, para que não vos fatigueis, desmaiando em vossa alma.

[[v58-12-4]]

^<<v58-12-4,4>>^ Ora, na vossa luta contra o pecado, ainda não tendes resistido até ao sangue

[[v58-12-5]]

^<<v58-12-5,5>>^ e estais esquecidos da exortação que, como a filhos, discorre convosco: Filho meu, não menosprezes a correção que vem do Senhor, nem desmaies quando por ele és reprovado;

[[v58-12-6]]

^<<v58-12-6,6>>^ porque o Senhor corrige a quem ama e açoita a todo filho a quem recebe.

[[v58-12-7]]

^<<v58-12-7,7>>^ É para disciplina que perseverais (Deus vos trata como filhos); pois que filho há que o pai não corrige?

[[v58-12-8]]

^<<v58-12-8,8>>^ Mas, se estais sem correção, de que todos se têm tornado participantes, logo, sois bastardos e não filhos.

[[v58-12-9]]

^<<v58-12-9,9>>^ Além disso, tínhamos os nossos pais segundo a carne, que nos corrigiam, e os respeitávamos; não havemos de estar em muito maior submissão ao Pai espiritual e, então, viveremos?

[[v58-12-10]]

^<<v58-12-10,10>>^ Pois eles nos corrigiam por pouco tempo, segundo melhor lhes parecia; Deus, porém, nos disciplina para aproveitamento, a fim de sermos participantes da sua santidade.

[[v58-12-11]]

^<<v58-12-11,11>>^ Toda disciplina, com efeito, no momento não parece ser motivo de alegria, mas de tristeza; ao depois, entretanto, produz fruto pacífico aos que têm sido por ela exercitados, fruto de justiça.

[[v58-12-12]]

^<<v58-12-12,12>>^ Por isso, restabelecei as mãos descaídas e os joelhos trôpegos;

[[v58-12-13]]

^<<v58-12-13,13>>^ e fazei caminhos retos para os pés, para que não se extravie o que é manco; antes, seja curado.

[[v58-12-14]]

^<<v58-12-14,14>>^ Segui a paz com todos e a santificação, sem a qual ninguém verá o Senhor,

[[v58-12-15]]

^<<v58-12-15,15>>^ atentando, diligentemente, por que ninguém seja faltoso, separando-se da graça de Deus; nem haja alguma raiz de amargura que, brotando, vos perturbe, e, por meio dela, muitos sejam contaminados;

[[v58-12-16]]

^<<v58-12-16,16>>^ nem haja algum impuro ou profano, como foi Esaú, o qual, por um repasto, vendeu o seu direito de primogenitura.

[[v58-12-17]]

^<<v58-12-17,17>>^ Pois sabeis também que, posteriormente, querendo herdar a bênção, foi rejeitado, pois não achou lugar de arrependimento, embora, com lágrimas, o tivesse buscado.

[[v58-12-18]]

^<<v58-12-18,18>>^ Ora, não tendes chegado ao fogo palpável e ardente, e à escuridão, e às trevas, e à tempestade,

[[v58-12-19]]

^<<v58-12-19,19>>^ e ao clangor da trombeta, e ao som de palavras tais, que quantos o ouviram suplicaram que não se lhes falasse mais,

[[v58-12-20]]

^<<v58-12-20,20>>^ pois já não suportavam o que lhes era ordenado: Até um animal, se tocar o monte, será apedrejado.

[[v58-12-21]]

^<<v58-12-21,21>>^ Na verdade, de tal modo era horrível o espetáculo, que Moisés disse: Sinto-me aterrado e trêmulo!

[[v58-12-22]]

^<<v58-12-22,22>>^ Mas tendes chegado ao monte Sião e à cidade do Deus vivo, a Jerusalém celestial, e a incontáveis hostes de anjos, e à universal assembleia

[[v58-12-23]]

^<<v58-12-23,23>>^ e igreja dos primogênitos arrolados nos céus, e a Deus, o Juiz de todos, e aos espíritos dos justos aperfeiçoados,

[[v58-12-24]]

^<<v58-12-24,24>>^ e a Jesus, o Mediador da nova aliança, e ao sangue da aspersão que fala coisas superiores ao que fala o próprio Abel.

[[v58-12-25]]

^<<v58-12-25,25>>^ Tende cuidado, não recuseis ao que fala. Pois, se não escaparam aqueles que recusaram ouvir quem, divinamente, os advertia sobre a terra, muito menos nós, os que nos desviamos daquele que dos céus nos adverte,

[[v58-12-26]]

^<<v58-12-26,26>>^ aquele, cuja voz abalou, então, a terra; agora, porém, ele promete, dizendo: Ainda uma vez por todas, farei abalar não só a terra, mas também o céu.

[[v58-12-27]]

^<<v58-12-27,27>>^ Ora, esta palavra: Ainda uma vez por todas significa a remoção dessas coisas abaladas, como tinham sido feitas, para que as coisas que não são abaladas permaneçam.

[[v58-12-28]]

^<<v58-12-28,28>>^ Por isso, recebendo nós um reino inabalável, retenhamos a graça, pela qual sirvamos a Deus de modo agradável, com reverência e santo temor;

[[v58-12-29]]

^<<v58-12-29,29>>^ porque o nosso Deus é fogo consumidor.

'''

xref:058-hebreus/058-hebreus-011.adoc#v58-11-0[&#60; Capítulo Anterior] | <<v58-12-0,Topo>> | xref:058-hebreus/058-hebreus-013.adoc#v58-13-0[Próximo Capítulo &#62;]