include::./index.adoc[]

[[v58-13-0]]
=== Hebreus, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v58-13-1]]

^<<v58-13-1,1>>^ Seja constante o amor fraternal.

[[v58-13-2]]

^<<v58-13-2,2>>^ Não negligencieis a hospitalidade, pois alguns, praticando-a, sem o saber acolheram anjos.

[[v58-13-3]]

^<<v58-13-3,3>>^ Lembrai-vos dos encarcerados, como se presos com eles; dos que sofrem maus-tratos, como se, com efeito, vós mesmos em pessoa fôsseis os maltratados.

[[v58-13-4]]

^<<v58-13-4,4>>^ Digno de honra entre todos seja o matrimônio, bem como o leito sem mácula; porque Deus julgará os impuros e adúlteros.

[[v58-13-5]]

^<<v58-13-5,5>>^ Seja a vossa vida sem avareza. Contentai-vos com as coisas que tendes; porque ele tem dito: De maneira alguma te deixarei, nunca jamais te abandonarei.

[[v58-13-6]]

^<<v58-13-6,6>>^ Assim, afirmemos confiantemente: O Senhor é o meu auxílio, não temerei; que me poderá fazer o homem?

[[v58-13-7]]

^<<v58-13-7,7>>^ Lembrai-vos dos vossos guias, os quais vos pregaram a palavra de Deus; e, considerando atentamente o fim da sua vida, imitai a fé que tiveram.

[[v58-13-8]]

^<<v58-13-8,8>>^ Jesus Cristo, ontem e hoje, é o mesmo e o será para sempre.

[[v58-13-9]]

^<<v58-13-9,9>>^ Não vos deixeis envolver por doutrinas várias e estranhas, porquanto o que vale é estar o coração confirmado com graça e não com alimentos, pois nunca tiveram proveito os que com isto se preocuparam.

[[v58-13-10]]

^<<v58-13-10,10>>^ Possuímos um altar do qual não têm direito de comer os que ministram no tabernáculo.

[[v58-13-11]]

^<<v58-13-11,11>>^ Pois aqueles animais cujo sangue é trazido para dentro do Santo dos Santos, pelo sumo sacerdote, como oblação pelo pecado, têm o corpo queimado fora do acampamento.

[[v58-13-12]]

^<<v58-13-12,12>>^ Por isso, foi que também Jesus, para santificar o povo, pelo seu próprio sangue, sofreu fora da porta.

[[v58-13-13]]

^<<v58-13-13,13>>^ Saiamos, pois, a ele, fora do arraial, levando o seu vitupério.

[[v58-13-14]]

^<<v58-13-14,14>>^ Na verdade, não temos aqui cidade permanente, mas buscamos a que há de vir.

[[v58-13-15]]

^<<v58-13-15,15>>^ Por meio de Jesus, pois, ofereçamos a Deus, sempre, sacrifício de louvor, que é o fruto de lábios que confessam o seu nome.

[[v58-13-16]]

^<<v58-13-16,16>>^ Não negligencieis, igualmente, a prática do bem e a mútua cooperação; pois, com tais sacrifícios, Deus se compraz.

[[v58-13-17]]

^<<v58-13-17,17>>^ Obedecei aos vossos guias e sede submissos para com eles; pois velam por vossa alma, como quem deve prestar contas, para que façam isto com alegria e não gemendo; porque isto não aproveita a vós outros.

[[v58-13-18]]

^<<v58-13-18,18>>^ Orai por nós, pois estamos persuadidos de termos boa consciência, desejando em todas as coisas viver condignamente.

[[v58-13-19]]

^<<v58-13-19,19>>^ Rogo-vos, com muito empenho, que assim façais, a fim de que eu vos seja restituído mais depressa.

[[v58-13-20]]

^<<v58-13-20,20>>^ Ora, o Deus da paz, que tornou a trazer dentre os mortos a Jesus, nosso Senhor, o grande Pastor das ovelhas, pelo sangue da eterna aliança,

[[v58-13-21]]

^<<v58-13-21,21>>^ vos aperfeiçoe em todo o bem, para cumprirdes a sua vontade, operando em vós o que é agradável diante dele, por Jesus Cristo, a quem seja a glória para todo o sempre. Amém!

[[v58-13-22]]

^<<v58-13-22,22>>^ Rogo-vos ainda, irmãos, que suporteis a presente palavra de exortação; tanto mais quanto vos escrevi resumidamente.

[[v58-13-23]]

^<<v58-13-23,23>>^ Notifico-vos que o irmão Timóteo foi posto em liberdade; com ele, caso venha logo, vos verei.

[[v58-13-24]]

^<<v58-13-24,24>>^ Saudai todos os vossos guias, bem como todos os santos. Os da Itália vos saúdam.

[[v58-13-25]]

^<<v58-13-25,25>>^ A graça seja com todos vós.

'''

xref:058-hebreus/058-hebreus-012.adoc#v58-12-0[&#60; Capítulo Anterior] | <<v58-13-0,Topo>> | xref:059-tiago/059-tiago-001.adoc#v59-1-0[Próximo Capítulo &#62;]