include::./index.adoc[]

[[v58-7-0]]
=== Hebreus, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v58-7-1]]

^<<v58-7-1,1>>^ Porque este Melquisedeque, rei de Salém, sacerdote do Deus Altíssimo, que saiu ao encontro de Abraão, quando voltava da matança dos reis, e o abençoou,

[[v58-7-2]]

^<<v58-7-2,2>>^ para o qual também Abraão separou o dízimo de tudo (primeiramente se interpreta rei de justiça, depois também é rei de Salém, ou seja, rei de paz;

[[v58-7-3]]

^<<v58-7-3,3>>^ sem pai, sem mãe, sem genealogia; que não teve princípio de dias, nem fim de existência, entretanto, feito semelhante ao Filho de Deus), permanece sacerdote perpetuamente.

[[v58-7-4]]

^<<v58-7-4,4>>^ Considerai, pois, como era grande esse a quem Abraão, o patriarca, pagou o dízimo tirado dos melhores despojos.

[[v58-7-5]]

^<<v58-7-5,5>>^ Ora, os que dentre os filhos de Levi recebem o sacerdócio têm mandamento de recolher, de acordo com a lei, os dízimos do povo, ou seja, dos seus irmãos, embora tenham estes descendido de Abraão;

[[v58-7-6]]

^<<v58-7-6,6>>^ entretanto, aquele cuja genealogia não se inclui entre eles recebeu dízimos de Abraão e abençoou o que tinha as promessas.

[[v58-7-7]]

^<<v58-7-7,7>>^ Evidentemente, é fora de qualquer dúvida que o inferior é abençoado pelo superior.

[[v58-7-8]]

^<<v58-7-8,8>>^ Aliás, aqui são homens mortais os que recebem dízimos, porém ali, aquele de quem se testifica que vive.

[[v58-7-9]]

^<<v58-7-9,9>>^ E, por assim dizer, também Levi, que recebe dízimos, pagou-os na pessoa de Abraão.

[[v58-7-10]]

^<<v58-7-10,10>>^ Porque aquele ainda não tinha sido gerado por seu pai, quando Melquisedeque saiu ao encontro deste.

[[v58-7-11]]

^<<v58-7-11,11>>^ Se, portanto, a perfeição houvera sido mediante o sacerdócio levítico (pois nele baseado o povo recebeu a lei), que necessidade haveria ainda de que se levantasse outro sacerdote, segundo a ordem de Melquisedeque, e que não fosse contado segundo a ordem de Arão?

[[v58-7-12]]

^<<v58-7-12,12>>^ Pois, quando se muda o sacerdócio, necessariamente há também mudança de lei.

[[v58-7-13]]

^<<v58-7-13,13>>^ Porque aquele de quem são ditas estas coisas pertence a outra tribo, da qual ninguém prestou serviço ao altar;

[[v58-7-14]]

^<<v58-7-14,14>>^ pois é evidente que nosso Senhor procedeu de Judá, tribo à qual Moisés nunca atribuiu sacerdotes.

[[v58-7-15]]

^<<v58-7-15,15>>^ E isto é ainda muito mais evidente, quando, à semelhança de Melquisedeque, se levanta outro sacerdote,

[[v58-7-16]]

^<<v58-7-16,16>>^ constituído não conforme a lei de mandamento carnal, mas segundo o poder de vida indissolúvel.

[[v58-7-17]]

^<<v58-7-17,17>>^ Porquanto se testifica: Tu és sacerdote para sempre, segundo a ordem de Melquisedeque.

[[v58-7-18]]

^<<v58-7-18,18>>^ Portanto, por um lado, se revoga a anterior ordenança, por causa de sua fraqueza e inutilidade

[[v58-7-19]]

^<<v58-7-19,19>>^ (pois a lei nunca aperfeiçoou coisa alguma), e, por outro lado, se introduz esperança superior, pela qual nos chegamos a Deus.

[[v58-7-20]]

^<<v58-7-20,20>>^ E, visto que não é sem prestar juramento (porque aqueles, sem juramento, são feitos sacerdotes,

[[v58-7-21]]

^<<v58-7-21,21>>^ mas este, com juramento, por aquele que lhe disse: O Senhor jurou e não se arrependerá: Tu és sacerdote para sempre );

[[v58-7-22]]

^<<v58-7-22,22>>^ por isso mesmo, Jesus se tem tornado fiador de superior aliança.

[[v58-7-23]]

^<<v58-7-23,23>>^ Ora, aqueles são feitos sacerdotes em maior número, porque são impedidos pela morte de continuar;

[[v58-7-24]]

^<<v58-7-24,24>>^ este, no entanto, porque continua para sempre, tem o seu sacerdócio imutável.

[[v58-7-25]]

^<<v58-7-25,25>>^ Por isso, também pode salvar totalmente os que por ele se chegam a Deus, vivendo sempre para interceder por eles.

[[v58-7-26]]

^<<v58-7-26,26>>^ Com efeito, nos convinha um sumo sacerdote como este, santo, inculpável, sem mácula, separado dos pecadores e feito mais alto do que os céus,

[[v58-7-27]]

^<<v58-7-27,27>>^ que não tem necessidade, como os sumos sacerdotes, de oferecer todos os dias sacrifícios, primeiro, por seus próprios pecados, depois, pelos do povo; porque fez isto uma vez por todas, quando a si mesmo se ofereceu.

[[v58-7-28]]

^<<v58-7-28,28>>^ Porque a lei constitui sumos sacerdotes a homens sujeitos à fraqueza, mas a palavra do juramento, que foi posterior à lei, constitui o Filho, perfeito para sempre.

'''

xref:058-hebreus/058-hebreus-006.adoc#v58-6-0[&#60; Capítulo Anterior] | <<v58-7-0,Topo>> | xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[Próximo Capítulo &#62;]