include::./index.adoc[]

[[v58-8-0]]
=== Hebreus, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v58-8-1]]

^<<v58-8-1,1>>^ Ora, o essencial das coisas que temos dito é que possuímos tal sumo sacerdote, que se assentou à destra do trono da Majestade nos céus,

[[v58-8-2]]

^<<v58-8-2,2>>^ como ministro do santuário e do verdadeiro tabernáculo que o Senhor erigiu, não o homem.

[[v58-8-3]]

^<<v58-8-3,3>>^ Pois todo sumo sacerdote é constituído para oferecer tanto dons como sacrifícios; por isso, era necessário que também esse sumo sacerdote tivesse o que oferecer.

[[v58-8-4]]

^<<v58-8-4,4>>^ Ora, se ele estivesse na terra, nem mesmo sacerdote seria, visto existirem aqueles que oferecem os dons segundo a lei,

[[v58-8-5]]

^<<v58-8-5,5>>^ os quais ministram em figura e sombra das coisas celestes, assim como foi Moisés divinamente instruído, quando estava para construir o tabernáculo; pois diz ele: Vê que faças todas as coisas de acordo com o modelo que te foi mostrado no monte.

[[v58-8-6]]

^<<v58-8-6,6>>^ Agora, com efeito, obteve Jesus ministério tanto mais excelente, quanto é ele também Mediador de superior aliança instituída com base em superiores promessas.

[[v58-8-7]]

^<<v58-8-7,7>>^ Porque, se aquela primeira aliança tivesse sido sem defeito, de maneira alguma estaria sendo buscado lugar para uma segunda.

[[v58-8-8]]

^<<v58-8-8,8>>^ E, de fato, repreendendo-os, diz: Eis aí vêm dias, diz o Senhor, e firmarei nova aliança com a casa de Israel e com a casa de Judá,

[[v58-8-9]]

^<<v58-8-9,9>>^ não segundo a aliança que fiz com seus pais, no dia em que os tomei pela mão, para os conduzir até fora da terra do Egito; pois eles não continuaram na minha aliança, e eu não atentei para eles, diz o Senhor.

[[v58-8-10]]

^<<v58-8-10,10>>^ Porque esta é a aliança que firmarei com a casa de Israel, depois daqueles dias, diz o Senhor: na sua mente imprimirei as minhas leis, também sobre o seu coração as inscreverei; e eu serei o seu Deus, e eles serão o meu povo.

[[v58-8-11]]

^<<v58-8-11,11>>^ E não ensinará jamais cada um ao seu próximo, nem cada um ao seu irmão, dizendo: Conhece ao Senhor; porque todos me conhecerão, desde o menor deles até ao maior.

[[v58-8-12]]

^<<v58-8-12,12>>^ Pois, para com as suas iniquidades, usarei de misericórdia e dos seus pecados jamais me lembrarei.

[[v58-8-13]]

^<<v58-8-13,13>>^ Quando ele diz Nova, torna antiquada a primeira. Ora, aquilo que se torna antiquado e envelhecido está prestes a desaparecer.

'''

xref:058-hebreus/058-hebreus-007.adoc#v58-7-0[&#60; Capítulo Anterior] | <<v58-8-0,Topo>> | xref:058-hebreus/058-hebreus-009.adoc#v58-9-0[Próximo Capítulo &#62;]