include::./index.adoc[]

[[v58-9-0]]
=== Hebreus, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v58-9-1]]

^<<v58-9-1,1>>^ Ora, a primeira aliança também tinha preceitos de serviço sagrado e o seu santuário terrestre.

[[v58-9-2]]

^<<v58-9-2,2>>^ Com efeito, foi preparado o tabernáculo, cuja parte anterior, onde estavam o candeeiro, e a mesa, e a exposição dos pães, se chama o Santo Lugar;

[[v58-9-3]]

^<<v58-9-3,3>>^ por trás do segundo véu, se encontrava o tabernáculo que se chama o Santo dos Santos,

[[v58-9-4]]

^<<v58-9-4,4>>^ ao qual pertencia um altar de ouro para o incenso e a arca da aliança totalmente coberta de ouro, na qual estava uma urna de ouro contendo o maná, o bordão de Arão, que floresceu, e as tábuas da aliança;

[[v58-9-5]]

^<<v58-9-5,5>>^ e sobre ela, os querubins de glória, que, com a sua sombra, cobriam o propiciatório. Dessas coisas, todavia, não falaremos, agora, pormenorizadamente.

[[v58-9-6]]

^<<v58-9-6,6>>^ Ora, depois de tudo isto assim preparado, continuamente entram no primeiro tabernáculo os sacerdotes, para realizar os serviços sagrados;

[[v58-9-7]]

^<<v58-9-7,7>>^ mas, no segundo, o sumo sacerdote, ele sozinho, uma vez por ano, não sem sangue, que oferece por si e pelos pecados de ignorância do povo,

[[v58-9-8]]

^<<v58-9-8,8>>^ querendo com isto dar a entender o Espírito Santo que ainda o caminho do Santo Lugar não se manifestou, enquanto o primeiro tabernáculo continua erguido.

[[v58-9-9]]

^<<v58-9-9,9>>^ É isto uma parábola para a época presente; e, segundo esta, se oferecem tanto dons como sacrifícios, embora estes, no tocante à consciência, sejam ineficazes para aperfeiçoar aquele que presta culto,

[[v58-9-10]]

^<<v58-9-10,10>>^ os quais não passam de ordenanças da carne, baseadas somente em comidas, e bebidas, e diversas abluções, impostas até ao tempo oportuno de reforma.

[[v58-9-11]]

^<<v58-9-11,11>>^ Quando, porém, veio Cristo como sumo sacerdote dos bens já realizados, mediante o maior e mais perfeito tabernáculo, não feito por mãos, quer dizer, não desta criação,

[[v58-9-12]]

^<<v58-9-12,12>>^ não por meio de sangue de bodes e de bezerros, mas pelo seu próprio sangue, entrou no Santo dos Santos, uma vez por todas, tendo obtido eterna redenção.

[[v58-9-13]]

^<<v58-9-13,13>>^ Portanto, se o sangue de bodes e de touros e a cinza de uma novilha, aspergidos sobre os contaminados, os santificam, quanto à purificação da carne,

[[v58-9-14]]

^<<v58-9-14,14>>^ muito mais o sangue de Cristo, que, pelo Espírito eterno, a si mesmo se ofereceu sem mácula a Deus, purificará a nossa consciência de obras mortas, para servirmos ao Deus vivo!

[[v58-9-15]]

^<<v58-9-15,15>>^ Por isso mesmo, ele é o Mediador da nova aliança, a fim de que, intervindo a morte para remissão das transgressões que havia sob a primeira aliança, recebam a promessa da eterna herança aqueles que têm sido chamados.

[[v58-9-16]]

^<<v58-9-16,16>>^ Porque, onde há testamento, é necessário que intervenha a morte do testador;

[[v58-9-17]]

^<<v58-9-17,17>>^ pois um testamento só é confirmado no caso de mortos; visto que de maneira nenhuma tem força de lei enquanto vive o testador.

[[v58-9-18]]

^<<v58-9-18,18>>^ Pelo que nem a primeira aliança foi sancionada sem sangue;

[[v58-9-19]]

^<<v58-9-19,19>>^ porque, havendo Moisés proclamado todos os mandamentos segundo a lei a todo o povo, tomou o sangue dos bezerros e dos bodes, com água, e lã tinta de escarlate, e hissopo e aspergiu não só o próprio livro, como também sobre todo o povo,

[[v58-9-20]]

^<<v58-9-20,20>>^ dizendo: Este é o sangue da aliança, a qual Deus prescreveu para vós outros.

[[v58-9-21]]

^<<v58-9-21,21>>^ Igualmente também aspergiu com sangue o tabernáculo e todos os utensílios do serviço sagrado.

[[v58-9-22]]

^<<v58-9-22,22>>^ Com efeito, quase todas as coisas, segundo a lei, se purificam com sangue; e, sem derramamento de sangue, não há remissão.

[[v58-9-23]]

^<<v58-9-23,23>>^ Era necessário, portanto, que as figuras das coisas que se acham nos céus se purificassem com tais sacrifícios, mas as próprias coisas celestiais, com sacrifícios a eles superiores.

[[v58-9-24]]

^<<v58-9-24,24>>^ Porque Cristo não entrou em santuário feito por mãos, figura do verdadeiro, porém no mesmo céu, para comparecer, agora, por nós, diante de Deus;

[[v58-9-25]]

^<<v58-9-25,25>>^ nem ainda para se oferecer a si mesmo muitas vezes, como o sumo sacerdote cada ano entra no Santo dos Santos com sangue alheio.

[[v58-9-26]]

^<<v58-9-26,26>>^ Ora, neste caso, seria necessário que ele tivesse sofrido muitas vezes desde a fundação do mundo; agora, porém, ao se cumprirem os tempos, se manifestou uma vez por todas, para aniquilar, pelo sacrifício de si mesmo, o pecado.

[[v58-9-27]]

^<<v58-9-27,27>>^ E, assim como aos homens está ordenado morrerem uma só vez, vindo, depois disto, o juízo,

[[v58-9-28]]

^<<v58-9-28,28>>^ assim também Cristo, tendo-se oferecido uma vez para sempre para tirar os pecados de muitos, aparecerá segunda vez, sem pecado, aos que o aguardam para a salvação.

'''

xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[&#60; Capítulo Anterior] | <<v58-9-0,Topo>> | xref:058-hebreus/058-hebreus-010.adoc#v58-10-0[Próximo Capítulo &#62;]