include::./index.adoc[]

[[v58-4-0]]
=== Hebreus, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v58-4-1]]

^<<v58-4-1,1>>^ Temamos, portanto, que, sendo-nos deixada a promessa de entrar no descanso de Deus, suceda parecer que algum de vós tenha falhado.

[[v58-4-2]]

^<<v58-4-2,2>>^ Porque também a nós foram anunciadas as boas-novas, como se deu com eles; mas a palavra que ouviram não lhes aproveitou, visto não ter sido acompanhada pela fé naqueles que a ouviram.

[[v58-4-3]]

^<<v58-4-3,3>>^ Nós, porém, que cremos, entramos no descanso, conforme Deus tem dito: Assim, jurei na minha ira: Não entrarão no meu descanso. Embora, certamente, as obras estivessem concluídas desde a fundação do mundo.

[[v58-4-4]]

^<<v58-4-4,4>>^ Porque, em certo lugar, assim disse, no tocante ao sétimo dia: E descansou Deus, no sétimo dia, de todas as obras que fizera.

[[v58-4-5]]

^<<v58-4-5,5>>^ E novamente, no mesmo lugar: Não entrarão no meu descanso.

[[v58-4-6]]

^<<v58-4-6,6>>^ Visto, portanto, que resta entrarem alguns nele e que, por causa da desobediência, não entraram aqueles aos quais anteriormente foram anunciadas as boas-novas,

[[v58-4-7]]

^<<v58-4-7,7>>^ de novo, determina certo dia, Hoje, falando por Davi, muito tempo depois, segundo antes fora declarado: Hoje, se ouvirdes a sua voz, não endureçais o vosso coração.

[[v58-4-8]]

^<<v58-4-8,8>>^ Ora, se Josué lhes houvesse dado descanso, não falaria, posteriormente, a respeito de outro dia.

[[v58-4-9]]

^<<v58-4-9,9>>^ Portanto, resta um repouso para o povo de Deus.

[[v58-4-10]]

^<<v58-4-10,10>>^ Porque aquele que entrou no descanso de Deus, também ele mesmo descansou de suas obras, como Deus das suas.

[[v58-4-11]]

^<<v58-4-11,11>>^ Esforcemo-nos, pois, por entrar naquele descanso, a fim de que ninguém caia, segundo o mesmo exemplo de desobediência.

[[v58-4-12]]

^<<v58-4-12,12>>^ Porque a palavra de Deus é viva, e eficaz, e mais cortante do que qualquer espada de dois gumes, e penetra até ao ponto de dividir alma e espírito, juntas e medulas, e é apta para discernir os pensamentos e propósitos do coração.

[[v58-4-13]]

^<<v58-4-13,13>>^ E não há criatura que não seja manifesta na sua presença; pelo contrário, todas as coisas estão descobertas e patentes aos olhos daquele a quem temos de prestar contas.

[[v58-4-14]]

^<<v58-4-14,14>>^ Tendo, pois, a Jesus, o Filho de Deus, como grande sumo sacerdote que penetrou os céus, conservemos firmes a nossa confissão.

[[v58-4-15]]

^<<v58-4-15,15>>^ Porque não temos sumo sacerdote que não possa compadecer-se das nossas fraquezas; antes, foi ele tentado em todas as coisas, à nossa semelhança, mas sem pecado.

[[v58-4-16]]

^<<v58-4-16,16>>^ Acheguemo-nos, portanto, confiadamente, junto ao trono da graça, a fim de recebermos misericórdia e acharmos graça para socorro em ocasião oportuna.

'''

xref:058-hebreus/058-hebreus-003.adoc#v58-3-0[&#60; Capítulo Anterior] | <<v58-4-0,Topo>> | xref:058-hebreus/058-hebreus-005.adoc#v58-5-0[Próximo Capítulo &#62;]