include::./index.adoc[]

[[v58-3-0]]
=== Hebreus, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v58-3-1]]

^<<v58-3-1,1>>^ Por isso, santos irmãos, que participais da vocação celestial, considerai atentamente o Apóstolo e Sumo Sacerdote da nossa confissão, Jesus,

[[v58-3-2]]

^<<v58-3-2,2>>^ o qual é fiel àquele que o constituiu, como também o era Moisés em toda a casa de Deus.

[[v58-3-3]]

^<<v58-3-3,3>>^ Jesus, todavia, tem sido considerado digno de tanto maior glória do que Moisés, quanto maior honra do que a casa tem aquele que a estabeleceu.

[[v58-3-4]]

^<<v58-3-4,4>>^ Pois toda casa é estabelecida por alguém, mas aquele que estabeleceu todas as coisas é Deus.

[[v58-3-5]]

^<<v58-3-5,5>>^ E Moisés era fiel, em toda a casa de Deus, como servo, para testemunho das coisas que haviam de ser anunciadas;

[[v58-3-6]]

^<<v58-3-6,6>>^ Cristo, porém, como Filho, em sua casa; a qual casa somos nós, se guardarmos firme, até ao fim, a ousadia e a exultação da esperança.

[[v58-3-7]]

^<<v58-3-7,7>>^ Assim, pois, como diz o Espírito Santo: Hoje, se ouvirdes a sua voz,

[[v58-3-8]]

^<<v58-3-8,8>>^ não endureçais o vosso coração como foi na provocação, no dia da tentação no deserto,

[[v58-3-9]]

^<<v58-3-9,9>>^ onde os vossos pais me tentaram, pondo-me à prova, e viram as minhas obras por quarenta anos.

[[v58-3-10]]

^<<v58-3-10,10>>^ Por isso, me indignei contra essa geração e disse: Estes sempre erram no coração; eles também não conheceram os meus caminhos.

[[v58-3-11]]

^<<v58-3-11,11>>^ Assim, jurei na minha ira: Não entrarão no meu descanso.

[[v58-3-12]]

^<<v58-3-12,12>>^ Tende cuidado, irmãos, jamais aconteça haver em qualquer de vós perverso coração de incredulidade que vos afaste do Deus vivo;

[[v58-3-13]]

^<<v58-3-13,13>>^ pelo contrário, exortai-vos mutuamente cada dia, durante o tempo que se chama Hoje, a fim de que nenhum de vós seja endurecido pelo engano do pecado.

[[v58-3-14]]

^<<v58-3-14,14>>^ Porque nos temos tornado participantes de Cristo, se, de fato, guardarmos firme, até ao fim, a confiança que, desde o princípio, tivemos.

[[v58-3-15]]

^<<v58-3-15,15>>^ Enquanto se diz: Hoje, se ouvirdes a sua voz, não endureçais o vosso coração, como foi na provocação.

[[v58-3-16]]

^<<v58-3-16,16>>^ Ora, quais os que, tendo ouvido, se rebelaram? Não foram, de fato, todos os que saíram do Egito por intermédio de Moisés?

[[v58-3-17]]

^<<v58-3-17,17>>^ E contra quem se indignou por quarenta anos? Não foi contra os que pecaram, cujos cadáveres caíram no deserto?

[[v58-3-18]]

^<<v58-3-18,18>>^ E contra quem jurou que não entrariam no seu descanso, senão contra os que foram desobedientes?

[[v58-3-19]]

^<<v58-3-19,19>>^ Vemos, pois, que não puderam entrar por causa da incredulidade.

'''

xref:058-hebreus/058-hebreus-002.adoc#v58-2-0[&#60; Capítulo Anterior] | <<v58-3-0,Topo>> | xref:058-hebreus/058-hebreus-004.adoc#v58-4-0[Próximo Capítulo &#62;]