include::./index.adoc[]

[[v58-6-0]]
=== Hebreus, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v58-6-1]]

^<<v58-6-1,1>>^ Por isso, pondo de parte os princípios elementares da doutrina de Cristo, deixemo-nos levar para o que é perfeito, não lançando, de novo, a base do arrependimento de obras mortas e da fé em Deus,

[[v58-6-2]]

^<<v58-6-2,2>>^ o ensino de batismos e da imposição de mãos, da ressurreição dos mortos e do juízo eterno.

[[v58-6-3]]

^<<v58-6-3,3>>^ Isso faremos, se Deus permitir.

[[v58-6-4]]

^<<v58-6-4,4>>^ É impossível, pois, que aqueles que uma vez foram iluminados, e provaram o dom celestial, e se tornaram participantes do Espírito Santo,

[[v58-6-5]]

^<<v58-6-5,5>>^ e provaram a boa palavra de Deus e os poderes do mundo vindouro,

[[v58-6-6]]

^<<v58-6-6,6>>^ e caíram, sim, é impossível outra vez renová-los para arrependimento, visto que, de novo, estão crucificando para si mesmos o Filho de Deus e expondo-o à ignomínia.

[[v58-6-7]]

^<<v58-6-7,7>>^ Porque a terra que absorve a chuva que frequentemente cai sobre ela e produz erva útil para aqueles por quem é também cultivada recebe bênção da parte de Deus;

[[v58-6-8]]

^<<v58-6-8,8>>^ mas, se produz espinhos e abrolhos, é rejeitada e perto está da maldição; e o seu fim é ser queimada.

[[v58-6-9]]

^<<v58-6-9,9>>^ Quanto a vós outros, todavia, ó amados, estamos persuadidos das coisas que são melhores e pertencentes à salvação, ainda que falamos desta maneira.

[[v58-6-10]]

^<<v58-6-10,10>>^ Porque Deus não é injusto para ficar esquecido do vosso trabalho e do amor que evidenciastes para com o seu nome, pois servistes e ainda servis aos santos.

[[v58-6-11]]

^<<v58-6-11,11>>^ Desejamos, porém, continue cada um de vós mostrando, até ao fim, a mesma diligência para a plena certeza da esperança;

[[v58-6-12]]

^<<v58-6-12,12>>^ para que não vos torneis indolentes, mas imitadores daqueles que, pela fé e pela longanimidade, herdam as promessas.

[[v58-6-13]]

^<<v58-6-13,13>>^ Pois, quando Deus fez a promessa a Abraão, visto que não tinha ninguém superior por quem jurar, jurou por si mesmo,

[[v58-6-14]]

^<<v58-6-14,14>>^ dizendo: Certamente, te abençoarei e te multiplicarei.

[[v58-6-15]]

^<<v58-6-15,15>>^ E assim, depois de esperar com paciência, obteve Abraão a promessa.

[[v58-6-16]]

^<<v58-6-16,16>>^ Pois os homens juram pelo que lhes é superior, e o juramento, servindo de garantia, para eles, é o fim de toda contenda.

[[v58-6-17]]

^<<v58-6-17,17>>^ Por isso, Deus, quando quis mostrar mais firmemente aos herdeiros da promessa a imutabilidade do seu propósito, se interpôs com juramento,

[[v58-6-18]]

^<<v58-6-18,18>>^ para que, mediante duas coisas imutáveis, nas quais é impossível que Deus minta, forte alento tenhamos nós que já corremos para o refúgio, a fim de lançar mão da esperança proposta;

[[v58-6-19]]

^<<v58-6-19,19>>^ a qual temos por âncora da alma, segura e firme e que penetra além do véu,

[[v58-6-20]]

^<<v58-6-20,20>>^ onde Jesus, como precursor, entrou por nós, tendo-se tornado sumo sacerdote para sempre, segundo a ordem de Melquisedeque.

'''

xref:058-hebreus/058-hebreus-005.adoc#v58-5-0[&#60; Capítulo Anterior] | <<v58-6-0,Topo>> | xref:058-hebreus/058-hebreus-007.adoc#v58-7-0[Próximo Capítulo &#62;]