include::./index.adoc[]

[[v53-2-0]]
=== 2 Tessalonicenses, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v53-2-1]]

^<<v53-2-1,1>>^ Irmãos, no que diz respeito à vinda de nosso Senhor Jesus Cristo e à nossa reunião com ele, nós vos exortamos

[[v53-2-2]]

^<<v53-2-2,2>>^ a que não vos demovais da vossa mente, com facilidade, nem vos perturbeis, quer por espírito, quer por palavra, quer por epístola, como se procedesse de nós, supondo tenha chegado o Dia do Senhor.

[[v53-2-3]]

^<<v53-2-3,3>>^ Ninguém, de nenhum modo, vos engane, porque isto não acontecerá sem que primeiro venha a apostasia e seja revelado o homem da iniquidade, o filho da perdição,

[[v53-2-4]]

^<<v53-2-4,4>>^ o qual se opõe e se levanta contra tudo que se chama Deus ou é objeto de culto, a ponto de assentar-se no santuário de Deus, ostentando-se como se fosse o próprio Deus.

[[v53-2-5]]

^<<v53-2-5,5>>^ Não vos recordais de que, ainda convosco, eu costumava dizer-vos estas coisas?

[[v53-2-6]]

^<<v53-2-6,6>>^ E, agora, sabeis o que o detém, para que ele seja revelado somente em ocasião própria.

[[v53-2-7]]

^<<v53-2-7,7>>^ Com efeito, o mistério da iniquidade já opera e aguarda somente que seja afastado aquele que agora o detém;

[[v53-2-8]]

^<<v53-2-8,8>>^ então, será, de fato, revelado o iníquo, a quem o Senhor Jesus matará com o sopro de sua boca e o destruirá pela manifestação de sua vinda.

[[v53-2-9]]

^<<v53-2-9,9>>^ Ora, o aparecimento do iníquo é segundo a eficácia de Satanás, com todo poder, e sinais, e prodígios da mentira,

[[v53-2-10]]

^<<v53-2-10,10>>^ e com todo engano de injustiça aos que perecem, porque não acolheram o amor da verdade para serem salvos.

[[v53-2-11]]

^<<v53-2-11,11>>^ É por este motivo, pois, que Deus lhes manda a operação do erro, para darem crédito à mentira,

[[v53-2-12]]

^<<v53-2-12,12>>^ a fim de serem julgados todos quantos não deram crédito à verdade; antes, pelo contrário, deleitaram-se com a injustiça.

[[v53-2-13]]

^<<v53-2-13,13>>^ Entretanto, devemos sempre dar graças a Deus por vós, irmãos amados pelo Senhor, porque Deus vos escolheu desde o princípio para a salvação, pela santificação do Espírito e fé na verdade,

[[v53-2-14]]

^<<v53-2-14,14>>^ para o que também vos chamou mediante o nosso evangelho, para alcançardes a glória de nosso Senhor Jesus Cristo.

[[v53-2-15]]

^<<v53-2-15,15>>^ Assim, pois, irmãos, permanecei firmes e guardai as tradições que vos foram ensinadas, seja por palavra, seja por epístola nossa.

[[v53-2-16]]

^<<v53-2-16,16>>^ Ora, nosso Senhor Jesus Cristo mesmo e Deus, o nosso Pai, que nos amou e nos deu eterna consolação e boa esperança, pela graça,

[[v53-2-17]]

^<<v53-2-17,17>>^ consolem o vosso coração e vos confirmem em toda boa obra e boa palavra.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-001.adoc#v53-1-0[&#60; Capítulo Anterior] | <<v53-2-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-003.adoc#v53-3-0[Próximo Capítulo &#62;]