include::./index.adoc[]

[[v53-3-0]]
=== 2 Tessalonicenses, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v53-3-1]]

^<<v53-3-1,1>>^ Finalmente, irmãos, orai por nós, para que a palavra do Senhor se propague e seja glorificada, como também está acontecendo entre vós;

[[v53-3-2]]

^<<v53-3-2,2>>^ e para que sejamos livres dos homens perversos e maus; porque a fé não é de todos.

[[v53-3-3]]

^<<v53-3-3,3>>^ Todavia, o Senhor é fiel; ele vos confirmará e guardará do Maligno.

[[v53-3-4]]

^<<v53-3-4,4>>^ Nós também temos confiança em vós no Senhor, de que não só estais praticando as coisas que vos ordenamos, como também continuareis a fazê-las.

[[v53-3-5]]

^<<v53-3-5,5>>^ Ora, o Senhor conduza o vosso coração ao amor de Deus e à constância de Cristo.

[[v53-3-6]]

^<<v53-3-6,6>>^ Nós vos ordenamos, irmãos, em nome do Senhor Jesus Cristo, que vos aparteis de todo irmão que ande desordenadamente e não segundo a tradição que de nós recebestes;

[[v53-3-7]]

^<<v53-3-7,7>>^ pois vós mesmos estais cientes do modo por que vos convém imitar-nos, visto que nunca nos portamos desordenadamente entre vós,

[[v53-3-8]]

^<<v53-3-8,8>>^ nem jamais comemos pão à custa de outrem; pelo contrário, em labor e fadiga, de noite e de dia, trabalhamos, a fim de não sermos pesados a nenhum de vós;

[[v53-3-9]]

^<<v53-3-9,9>>^ não porque não tivéssemos esse direito, mas por termos em vista oferecer-vos exemplo em nós mesmos, para nos imitardes.

[[v53-3-10]]

^<<v53-3-10,10>>^ Porque, quando ainda convosco, vos ordenamos isto: se alguém não quer trabalhar, também não coma.

[[v53-3-11]]

^<<v53-3-11,11>>^ Pois, de fato, estamos informados de que, entre vós, há pessoas que andam desordenadamente, não trabalhando; antes, se intrometem na vida alheia.

[[v53-3-12]]

^<<v53-3-12,12>>^ A elas, porém, determinamos e exortamos, no Senhor Jesus Cristo, que, trabalhando tranquilamente, comam o seu próprio pão.

[[v53-3-13]]

^<<v53-3-13,13>>^ E vós, irmãos, não vos canseis de fazer o bem.

[[v53-3-14]]

^<<v53-3-14,14>>^ Caso alguém não preste obediência à nossa palavra dada por esta epístola, notai-o; nem vos associeis com ele, para que fique envergonhado.

[[v53-3-15]]

^<<v53-3-15,15>>^ Todavia, não o considereis por inimigo, mas adverti-o como irmão.

[[v53-3-16]]

^<<v53-3-16,16>>^ Ora, o Senhor da paz, ele mesmo, vos dê continuamente a paz em todas as circunstâncias. O Senhor seja com todos vós.

[[v53-3-17]]

^<<v53-3-17,17>>^ A saudação é de próprio punho: Paulo. Este é o sinal em cada epístola; assim é que eu assino.

[[v53-3-18]]

^<<v53-3-18,18>>^ A graça de nosso Senhor Jesus Cristo seja com todos vós.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-002.adoc#v53-2-0[&#60; Capítulo Anterior] | <<v53-3-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[Próximo Capítulo &#62;]