include::./index.adoc[]

[[v19-142-0]]
=== Salmos, 142
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-142-1]]

^<<v19-142-1,1>>^ Ao SENHOR ergo a minha voz e clamo, com a minha voz suplico ao SENHOR.

[[v19-142-2]]

^<<v19-142-2,2>>^ Derramo perante ele a minha queixa, à sua presença exponho a minha tribulação.

[[v19-142-3]]

^<<v19-142-3,3>>^ Quando dentro de mim me esmorece o espírito, conheces a minha vereda. No caminho em que ando, me ocultam armadilha.

[[v19-142-4]]

^<<v19-142-4,4>>^ Olha à minha direita e vê, pois não há quem me reconheça, nenhum lugar de refúgio, ninguém que por mim se interesse.

[[v19-142-5]]

^<<v19-142-5,5>>^ A ti clamo, SENHOR, e digo: tu és o meu refúgio, o meu quinhão na terra dos viventes.

[[v19-142-6]]

^<<v19-142-6,6>>^ Atende o meu clamor, pois me vejo muito fraco. Livra-me dos meus perseguidores, porque são mais fortes do que eu.

[[v19-142-7]]

^<<v19-142-7,7>>^ Tira a minha alma do cárcere, para que eu dê graças ao teu nome; os justos me rodearão, quando me fizeres esse bem.

'''

xref:019-salmos/019-salmos-141.adoc#v19-141-0[&#60; Capítulo Anterior] | <<v19-142-0,Topo>> | xref:019-salmos/019-salmos-143.adoc#v19-143-0[Próximo Capítulo &#62;]