include::./index.adoc[]

[[v19-112-0]]
=== Salmos, 112
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-112-1]]

^<<v19-112-1,1>>^ Aleluia! Bem-aventurado o homem que teme ao Senhor e se compraz nos seus mandamentos.

[[v19-112-2]]

^<<v19-112-2,2>>^ A sua descendência será poderosa na terra; será abençoada a geração dos justos.

[[v19-112-3]]

^<<v19-112-3,3>>^ Na sua casa há prosperidade e riqueza, e a sua justiça permanece para sempre.

[[v19-112-4]]

^<<v19-112-4,4>>^ Ao justo, nasce luz nas trevas; ele é benigno, misericordioso e justo.

[[v19-112-5]]

^<<v19-112-5,5>>^ Ditoso o homem que se compadece e empresta; ele defenderá a sua causa em juízo;

[[v19-112-6]]

^<<v19-112-6,6>>^ não será jamais abalado; será tido em memória eterna.

[[v19-112-7]]

^<<v19-112-7,7>>^ Não se atemoriza de más notícias; o seu coração é firme, confiante no SENHOR.

[[v19-112-8]]

^<<v19-112-8,8>>^ O seu coração, bem firmado, não teme, até ver cumprido, nos seus adversários, o seu desejo.

[[v19-112-9]]

^<<v19-112-9,9>>^ Distribui, dá aos pobres; a sua justiça permanece para sempre, e o seu poder se exaltará em glória.

[[v19-112-10]]

^<<v19-112-10,10>>^ O perverso vê isso e se enraivece; range os dentes e se consome; o desejo dos perversos perecerá.

'''

xref:019-salmos/019-salmos-111.adoc#v19-111-0[&#60; Capítulo Anterior] | <<v19-112-0,Topo>> | xref:019-salmos/019-salmos-113.adoc#v19-113-0[Próximo Capítulo &#62;]