include::./index.adoc[]

[[v19-35-0]]
=== Salmos, 35
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-35-1]]

^<<v19-35-1,1>>^ Contende, SENHOR, com os que contendem comigo; peleja contra os que contra mim pelejam.

[[v19-35-2]]

^<<v19-35-2,2>>^ Embraça o escudo e o broquel e ergue-te em meu auxílio.

[[v19-35-3]]

^<<v19-35-3,3>>^ Empunha a lança e reprime o passo aos meus perseguidores; dize à minha alma: Eu sou a tua salvação.

[[v19-35-4]]

^<<v19-35-4,4>>^ Sejam confundidos e cobertos de vexame os que buscam tirar-me a vida; retrocedam e sejam envergonhados os que tramam contra mim.

[[v19-35-5]]

^<<v19-35-5,5>>^ Sejam como a palha ao léu do vento, impelindo-os o anjo do SENHOR.

[[v19-35-6]]

^<<v19-35-6,6>>^ Torne-se-lhes o caminho tenebroso e escorregadio, e o anjo do SENHOR os persiga.

[[v19-35-7]]

^<<v19-35-7,7>>^ Pois sem causa me tramaram laços, sem causa abriram cova para a minha vida.

[[v19-35-8]]

^<<v19-35-8,8>>^ Venha sobre o inimigo a destruição, quando ele menos pensar; e prendam-no os laços que tramou ocultamente; caia neles para a sua própria ruína.

[[v19-35-9]]

^<<v19-35-9,9>>^ E minha alma se regozijará no Senhor e se deleitará na sua salvação.

[[v19-35-10]]

^<<v19-35-10,10>>^ Todos os meus ossos dirão: SENHOR, quem contigo se assemelha? Pois livras o aflito daquele que é demais forte para ele, o mísero e o necessitado, dos seus extorsionários.

[[v19-35-11]]

^<<v19-35-11,11>>^ Levantam-se iníquas testemunhas e me arguem de coisas que eu não sei.

[[v19-35-12]]

^<<v19-35-12,12>>^ Pagam-me o mal pelo bem, o que é desolação para a minha alma.

[[v19-35-13]]

^<<v19-35-13,13>>^ Quanto a mim, porém, estando eles enfermos, as minhas vestes eram pano de saco; eu afligia a minha alma com jejum e em oração me reclinava sobre o peito,

[[v19-35-14]]

^<<v19-35-14,14>>^ portava-me como se eles fossem meus amigos ou meus irmãos; andava curvado, de luto, como quem chora por sua mãe.

[[v19-35-15]]

^<<v19-35-15,15>>^ Quando, porém, tropecei, eles se alegraram e se reuniram; reuniram-se contra mim; os abjetos, que eu não conhecia, dilaceraram-me sem tréguas;

[[v19-35-16]]

^<<v19-35-16,16>>^ como vis bufões em festins, rangiam contra mim os dentes.

[[v19-35-17]]

^<<v19-35-17,17>>^ Até quando, Senhor, ficarás olhando? Livra-me a alma das violências deles; dos leões, a minha predileta.

[[v19-35-18]]

^<<v19-35-18,18>>^ Dar-te-ei graças na grande congregação, louvar-te-ei no meio da multidão poderosa.

[[v19-35-19]]

^<<v19-35-19,19>>^ Não se alegrem de mim os meus inimigos gratuitos; não pisquem os olhos os que sem causa me odeiam.

[[v19-35-20]]

^<<v19-35-20,20>>^ Não é de paz que eles falam; pelo contrário, tramam enganos contra os pacíficos da terra.

[[v19-35-21]]

^<<v19-35-21,21>>^ Escancaram contra mim a boca e dizem: Pegamos! Pegamos! Vimo-lo com os nossos próprios olhos.

[[v19-35-22]]

^<<v19-35-22,22>>^ Tu, SENHOR, os viste; não te cales; Senhor, não te ausentes de mim.

[[v19-35-23]]

^<<v19-35-23,23>>^ Acorda e desperta para me fazeres justiça, para a minha causa, Deus meu e Senhor meu.

[[v19-35-24]]

^<<v19-35-24,24>>^ Julga-me, SENHOR, Deus meu, segundo a tua justiça; não permitas que se regozijem contra mim.

[[v19-35-25]]

^<<v19-35-25,25>>^ Não digam eles lá no seu íntimo: Agora, sim! Cumpriu-se o nosso desejo! Não digam: Demos cabo dele!

[[v19-35-26]]

^<<v19-35-26,26>>^ Envergonhem-se e juntamente sejam cobertos de vexame os que se alegram com o meu mal; cubram-se de pejo e ignomínia os que se engrandecem contra mim.

[[v19-35-27]]

^<<v19-35-27,27>>^ Cantem de júbilo e se alegrem os que têm prazer na minha retidão; e digam sempre: Glorificado seja o SENHOR, que se compraz na prosperidade do seu servo!

[[v19-35-28]]

^<<v19-35-28,28>>^ E a minha língua celebrará a tua justiça e o teu louvor todo o dia.

'''

xref:019-salmos/019-salmos-034.adoc#v19-34-0[&#60; Capítulo Anterior] | <<v19-35-0,Topo>> | xref:019-salmos/019-salmos-036.adoc#v19-36-0[Próximo Capítulo &#62;]