include::./index.adoc[]

[[v19-143-0]]
=== Salmos, 143
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-143-1]]

^<<v19-143-1,1>>^ Atende, SENHOR, a minha oração, dá ouvidos às minhas súplicas. Responde-me, segundo a tua fidelidade, segundo a tua justiça.

[[v19-143-2]]

^<<v19-143-2,2>>^ Não entres em juízo com o teu servo, porque à tua vista não há justo nenhum vivente.

[[v19-143-3]]

^<<v19-143-3,3>>^ Pois o inimigo me tem perseguido a alma; tem arrojado por terra a minha vida; tem-me feito habitar na escuridão, como aqueles que morreram há muito.

[[v19-143-4]]

^<<v19-143-4,4>>^ Por isso, dentro de mim esmorece o meu espírito, e o coração se vê turbado.

[[v19-143-5]]

^<<v19-143-5,5>>^ Lembro-me dos dias de outrora, penso em todos os teus feitos e considero nas obras das tuas mãos.

[[v19-143-6]]

^<<v19-143-6,6>>^ A ti levanto as mãos; a minha alma anseia por ti, como terra sedenta.

[[v19-143-7]]

^<<v19-143-7,7>>^ Dá-te pressa, SENHOR, em responder-me; o espírito me desfalece; não me escondas a tua face, para que eu não me torne como os que baixam à cova.

[[v19-143-8]]

^<<v19-143-8,8>>^ Faze-me ouvir, pela manhã, da tua graça, pois em ti confio; mostra-me o caminho por onde devo andar, porque a ti elevo a minha alma.

[[v19-143-9]]

^<<v19-143-9,9>>^ Livra-me, SENHOR, dos meus inimigos; pois em ti é que me refugio.

[[v19-143-10]]

^<<v19-143-10,10>>^ Ensina-me a fazer a tua vontade, pois tu és o meu Deus; guie-me o teu bom Espírito por terreno plano.

[[v19-143-11]]

^<<v19-143-11,11>>^ Vivifica-me, SENHOR, por amor do teu nome; por amor da tua justiça, tira da tribulação a minha alma.

[[v19-143-12]]

^<<v19-143-12,12>>^ E, por tua misericórdia, dá cabo dos meus inimigos e destrói todos os que me atribulam a alma, pois eu sou teu servo.

'''

xref:019-salmos/019-salmos-142.adoc#v19-142-0[&#60; Capítulo Anterior] | <<v19-143-0,Topo>> | xref:019-salmos/019-salmos-144.adoc#v19-144-0[Próximo Capítulo &#62;]