include::./index.adoc[]

[[v19-20-0]]
=== Salmos, 20
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-20-1]]

^<<v19-20-1,1>>^ O SENHOR te responda no dia da tribulação; o nome do Deus de Jacó te eleve em segurança.

[[v19-20-2]]

^<<v19-20-2,2>>^ Do seu santuário te envie socorro e desde Sião te sustenha.

[[v19-20-3]]

^<<v19-20-3,3>>^ Lembre-se de todas as tuas ofertas de manjares e aceite os teus holocaustos.

[[v19-20-4]]

^<<v19-20-4,4>>^ Conceda-te segundo o teu coração e realize todos os teus desígnios.

[[v19-20-5]]

^<<v19-20-5,5>>^ Celebraremos com júbilo a tua vitória e em nome do nosso Deus hastearemos pendões; satisfaça o SENHOR a todos os teus votos.

[[v19-20-6]]

^<<v19-20-6,6>>^ Agora, sei que o SENHOR salva o seu ungido; ele lhe responderá do seu santo céu com a vitoriosa força de sua destra.

[[v19-20-7]]

^<<v19-20-7,7>>^ Uns confiam em carros, outros, em cavalos; nós, porém, nos gloriaremos em o nome do SENHOR, nosso Deus.

[[v19-20-8]]

^<<v19-20-8,8>>^ Eles se encurvam e caem; nós, porém, nos levantamos e nos mantemos de pé.

[[v19-20-9]]

^<<v19-20-9,9>>^ Ó SENHOR, dá vitória ao rei; responde-nos, quando clamarmos.

'''

xref:019-salmos/019-salmos-019.adoc#v19-19-0[&#60; Capítulo Anterior] | <<v19-20-0,Topo>> | xref:019-salmos/019-salmos-021.adoc#v19-21-0[Próximo Capítulo &#62;]