include::./index.adoc[]

[[v19-95-0]]
=== Salmos, 95
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-95-1]]

^<<v19-95-1,1>>^ Vinde, cantemos ao SENHOR, com júbilo, celebremos o Rochedo da nossa salvação.

[[v19-95-2]]

^<<v19-95-2,2>>^ Saiamos ao seu encontro, com ações de graças, vitoriemo-lo com salmos.

[[v19-95-3]]

^<<v19-95-3,3>>^ Porque o SENHOR é o Deus supremo e o grande Rei acima de todos os deuses.

[[v19-95-4]]

^<<v19-95-4,4>>^ Nas suas mãos estão as profundezas da terra, e as alturas dos montes lhe pertencem.

[[v19-95-5]]

^<<v19-95-5,5>>^ Dele é o mar, pois ele o fez; obra de suas mãos, os continentes.

[[v19-95-6]]

^<<v19-95-6,6>>^ Vinde, adoremos e prostremo-nos; ajoelhemos diante do SENHOR, que nos criou.

[[v19-95-7]]

^<<v19-95-7,7>>^ Ele é o nosso Deus, e nós, povo do seu pasto e ovelhas de sua mão. Hoje, se ouvirdes a sua voz,

[[v19-95-8]]

^<<v19-95-8,8>>^ não endureçais o coração, como em Meribá, como no dia de Massá, no deserto,

[[v19-95-9]]

^<<v19-95-9,9>>^ quando vossos pais me tentaram, pondo-me à prova, não obstante terem visto as minhas obras.

[[v19-95-10]]

^<<v19-95-10,10>>^ Durante quarenta anos, estive desgostado com essa geração e disse: é povo de coração transviado, não conhece os meus caminhos.

[[v19-95-11]]

^<<v19-95-11,11>>^ Por isso, jurei na minha ira: não entrarão no meu descanso.

'''

xref:019-salmos/019-salmos-094.adoc#v19-94-0[&#60; Capítulo Anterior] | <<v19-95-0,Topo>> | xref:019-salmos/019-salmos-096.adoc#v19-96-0[Próximo Capítulo &#62;]