include::./index.adoc[]

[[v19-49-0]]
=== Salmos, 49
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-49-1]]

^<<v19-49-1,1>>^ Povos todos, escutai isto; dai ouvidos, moradores todos da terra,

[[v19-49-2]]

^<<v19-49-2,2>>^ tanto plebeus como os de fina estirpe, todos juntamente, ricos e pobres.

[[v19-49-3]]

^<<v19-49-3,3>>^ Os meus lábios falarão sabedoria, e o meu coração terá pensamentos judiciosos.

[[v19-49-4]]

^<<v19-49-4,4>>^ Inclinarei os ouvidos a uma parábola, decifrarei o meu enigma ao som da harpa.

[[v19-49-5]]

^<<v19-49-5,5>>^ Por que hei de eu temer nos dias da tribulação, quando me salteia a iniquidade dos que me perseguem,

[[v19-49-6]]

^<<v19-49-6,6>>^ dos que confiam nos seus bens e na sua muita riqueza se gloriam?

[[v19-49-7]]

^<<v19-49-7,7>>^ Ao irmão, verdadeiramente, ninguém o pode remir, nem pagar por ele a Deus o seu resgate

[[v19-49-8]]

^<<v19-49-8,8>>^ (Pois a redenção da alma deles é caríssima, e cessará a tentativa para sempre.),

[[v19-49-9]]

^<<v19-49-9,9>>^ para que continue a viver perpetuamente e não veja a cova;

[[v19-49-10]]

^<<v19-49-10,10>>^ porquanto vê-se morrerem os sábios e perecerem tanto o estulto como o inepto, os quais deixam a outros as suas riquezas.

[[v19-49-11]]

^<<v19-49-11,11>>^ O seu pensamento íntimo é que as suas casas serão perpétuas e, as suas moradas, para todas as gerações; chegam a dar seu próprio nome às suas terras.

[[v19-49-12]]

^<<v19-49-12,12>>^ Todavia, o homem não permanece em sua ostentação; é, antes, como os animais, que perecem.

[[v19-49-13]]

^<<v19-49-13,13>>^ Tal proceder é estultícia deles; assim mesmo os seus seguidores aplaudem o que eles dizem.

[[v19-49-14]]

^<<v19-49-14,14>>^ Como ovelhas são postos na sepultura; a morte é o seu pastor; eles descem diretamente para a cova, onde a sua formosura se consome; a sepultura é o lugar em que habitam.

[[v19-49-15]]

^<<v19-49-15,15>>^ Mas Deus remirá a minha alma do poder da morte, pois ele me tomará para si.

[[v19-49-16]]

^<<v19-49-16,16>>^ Não temas, quando alguém se enriquecer, quando avultar a glória de sua casa;

[[v19-49-17]]

^<<v19-49-17,17>>^ pois, em morrendo, nada levará consigo, a sua glória não o acompanhará.

[[v19-49-18]]

^<<v19-49-18,18>>^ Ainda que durante a vida ele se tenha lisonjeado, e ainda que o louvem quando faz o bem a si mesmo,

[[v19-49-19]]

^<<v19-49-19,19>>^ irá ter com a geração de seus pais, os quais já não verão a luz.

[[v19-49-20]]

^<<v19-49-20,20>>^ O homem, revestido de honrarias, mas sem entendimento, é, antes, como os animais, que perecem.

'''

xref:019-salmos/019-salmos-048.adoc#v19-48-0[&#60; Capítulo Anterior] | <<v19-49-0,Topo>> | xref:019-salmos/019-salmos-050.adoc#v19-50-0[Próximo Capítulo &#62;]