include::./index.adoc[]

[[v19-32-0]]
=== Salmos, 32
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-32-1]]

^<<v19-32-1,1>>^ Bem-aventurado aquele cuja iniquidade é perdoada, cujo pecado é coberto.

[[v19-32-2]]

^<<v19-32-2,2>>^ Bem-aventurado o homem a quem o SENHOR não atribui iniquidade e em cujo espírito não há dolo.

[[v19-32-3]]

^<<v19-32-3,3>>^ Enquanto calei os meus pecados, envelheceram os meus ossos pelos meus constantes gemidos todo o dia.

[[v19-32-4]]

^<<v19-32-4,4>>^ Porque a tua mão pesava dia e noite sobre mim, e o meu vigor se tornou em sequidão de estio.

[[v19-32-5]]

^<<v19-32-5,5>>^ Confessei-te o meu pecado e a minha iniquidade não mais ocultei. Disse: confessarei ao SENHOR as minhas transgressões; e tu perdoaste a iniquidade do meu pecado.

[[v19-32-6]]

^<<v19-32-6,6>>^ Sendo assim, todo homem piedoso te fará súplicas em tempo de poder encontrar-te. Com efeito, quando transbordarem muitas águas, não o atingirão.

[[v19-32-7]]

^<<v19-32-7,7>>^ Tu és o meu esconderijo; tu me preservas da tribulação e me cercas de alegres cantos de livramento.

[[v19-32-8]]

^<<v19-32-8,8>>^ Instruir-te-ei e te ensinarei o caminho que deves seguir; e, sob as minhas vistas, te darei conselho.

[[v19-32-9]]

^<<v19-32-9,9>>^ Não sejais como o cavalo ou a mula, sem entendimento, os quais com freios e cabrestos são dominados; de outra sorte não te obedecem.

[[v19-32-10]]

^<<v19-32-10,10>>^ Muito sofrimento terá de curtir o ímpio, mas o que confia no SENHOR, a misericórdia o assistirá.

[[v19-32-11]]

^<<v19-32-11,11>>^ Alegrai-vos no SENHOR e regozijai-vos, ó justos; exultai, vós todos que sois retos de coração.

'''

xref:019-salmos/019-salmos-031.adoc#v19-31-0[&#60; Capítulo Anterior] | <<v19-32-0,Topo>> | xref:019-salmos/019-salmos-033.adoc#v19-33-0[Próximo Capítulo &#62;]