include::./index.adoc[]

[[v19-141-0]]
=== Salmos, 141
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-141-1]]

^<<v19-141-1,1>>^ SENHOR, a ti clamo, dá-te pressa em me acudir; inclina os ouvidos à minha voz, quando te invoco.

[[v19-141-2]]

^<<v19-141-2,2>>^ Suba à tua presença a minha oração, como incenso, e seja o erguer de minhas mãos como oferenda vespertina.

[[v19-141-3]]

^<<v19-141-3,3>>^ Põe guarda, SENHOR, à minha boca; vigia a porta dos meus lábios.

[[v19-141-4]]

^<<v19-141-4,4>>^ Não permitas que meu coração se incline para o mal, para a prática da perversidade na companhia de homens que são malfeitores; e não coma eu das suas iguarias.

[[v19-141-5]]

^<<v19-141-5,5>>^ Fira-me o justo, será isso mercê; repreenda-me, será como óleo sobre a minha cabeça, a qual não há de rejeitá-lo. Continuarei a orar enquanto os perversos praticam maldade.

[[v19-141-6]]

^<<v19-141-6,6>>^ Os seus juízes serão precipitados penha abaixo, mas ouvirão as minhas palavras, que são agradáveis,

[[v19-141-7]]

^<<v19-141-7,7>>^ ainda que sejam espalhados os meus ossos à boca da sepultura, quando se lavra e sulca a terra.

[[v19-141-8]]

^<<v19-141-8,8>>^ Pois em ti, SENHOR Deus, estão fitos os meus olhos: em ti confio; não desampares a minha alma.

[[v19-141-9]]

^<<v19-141-9,9>>^ Guarda-me dos laços que me armaram e das armadilhas dos que praticam iniquidade.

[[v19-141-10]]

^<<v19-141-10,10>>^ Caiam os ímpios nas suas próprias redes, enquanto eu, nesse meio tempo, me salvo incólume.

'''

xref:019-salmos/019-salmos-140.adoc#v19-140-0[&#60; Capítulo Anterior] | <<v19-141-0,Topo>> | xref:019-salmos/019-salmos-142.adoc#v19-142-0[Próximo Capítulo &#62;]