include::./index.adoc[]

[[v19-45-0]]
=== Salmos, 45
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-45-1]]

^<<v19-45-1,1>>^ De boas palavras transborda o meu coração. Ao Rei consagro o que compus; a minha língua é como a pena de habilidoso escritor.

[[v19-45-2]]

^<<v19-45-2,2>>^ Tu és o mais formoso dos filhos dos homens; nos teus lábios se extravasou a graça; por isso, Deus te abençoou para sempre.

[[v19-45-3]]

^<<v19-45-3,3>>^ Cinge a espada no teu flanco, herói; cinge a tua glória e a tua majestade!

[[v19-45-4]]

^<<v19-45-4,4>>^ E nessa majestade cavalga prosperamente, pela causa da verdade e da justiça; e a tua destra te ensinará proezas.

[[v19-45-5]]

^<<v19-45-5,5>>^ As tuas setas são agudas, penetram o coração dos inimigos do Rei; os povos caem submissos a ti.

[[v19-45-6]]

^<<v19-45-6,6>>^ O teu trono, ó Deus, é para todo o sempre; cetro de equidade é o cetro do teu reino.

[[v19-45-7]]

^<<v19-45-7,7>>^ Amas a justiça e odeias a iniquidade; por isso, Deus, o teu Deus, te ungiu com o óleo de alegria, como a nenhum dos teus companheiros.

[[v19-45-8]]

^<<v19-45-8,8>>^ Todas as tuas vestes recendem a mirra, aloés e cássia; de palácios de marfim ressoam instrumentos de cordas que te alegram.

[[v19-45-9]]

^<<v19-45-9,9>>^ Filhas de reis se encontram entre as tuas damas de honra; à tua direita está a rainha adornada de ouro finíssimo de Ofir.

[[v19-45-10]]

^<<v19-45-10,10>>^ Ouve, filha; vê, dá atenção; esquece o teu povo e a casa de teu pai.

[[v19-45-11]]

^<<v19-45-11,11>>^ Então, o Rei cobiçará a tua formosura; pois ele é o teu senhor; inclina-te perante ele.

[[v19-45-12]]

^<<v19-45-12,12>>^ A ti virá a filha de Tiro trazendo donativos; os mais ricos do povo te pedirão favores.

[[v19-45-13]]

^<<v19-45-13,13>>^ Toda formosura é a filha do Rei no interior do palácio; a sua vestidura é recamada de ouro.

[[v19-45-14]]

^<<v19-45-14,14>>^ Em roupagens bordadas conduzem-na perante o Rei; as virgens, suas companheiras que a seguem, serão trazidas à tua presença.

[[v19-45-15]]

^<<v19-45-15,15>>^ Serão dirigidas com alegria e regozijo; entrarão no palácio do Rei.

[[v19-45-16]]

^<<v19-45-16,16>>^ Em vez de teus pais, serão teus filhos, os quais farás príncipes por toda a terra.

[[v19-45-17]]

^<<v19-45-17,17>>^ O teu nome, eu o farei celebrado de geração a geração, e, assim, os povos te louvarão para todo o sempre.

'''

xref:019-salmos/019-salmos-044.adoc#v19-44-0[&#60; Capítulo Anterior] | <<v19-45-0,Topo>> | xref:019-salmos/019-salmos-046.adoc#v19-46-0[Próximo Capítulo &#62;]