include::./index.adoc[]

[[v19-115-0]]
=== Salmos, 115
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-115-1]]

^<<v19-115-1,1>>^ Não a nós, SENHOR, não a nós, mas ao teu nome dá glória, por amor da tua misericórdia e da tua fidelidade.

[[v19-115-2]]

^<<v19-115-2,2>>^ Por que diriam as nações: Onde está o Deus deles?

[[v19-115-3]]

^<<v19-115-3,3>>^ No céu está o nosso Deus e tudo faz como lhe agrada.

[[v19-115-4]]

^<<v19-115-4,4>>^ Prata e ouro são os ídolos deles, obra das mãos de homens.

[[v19-115-5]]

^<<v19-115-5,5>>^ Têm boca e não falam; têm olhos e não veem;

[[v19-115-6]]

^<<v19-115-6,6>>^ têm ouvidos e não ouvem; têm nariz e não cheiram.

[[v19-115-7]]

^<<v19-115-7,7>>^ Suas mãos não apalpam; seus pés não andam; som nenhum lhes sai da garganta.

[[v19-115-8]]

^<<v19-115-8,8>>^ Tornem-se semelhantes a eles os que os fazem e quantos neles confiam.

[[v19-115-9]]

^<<v19-115-9,9>>^ Israel confia no SENHOR; ele é o seu amparo e o seu escudo.

[[v19-115-10]]

^<<v19-115-10,10>>^ A casa de Arão confia no SENHOR; ele é o seu amparo e o seu escudo.

[[v19-115-11]]

^<<v19-115-11,11>>^ Confiam no SENHOR os que temem o SENHOR; ele é o seu amparo e o seu escudo.

[[v19-115-12]]

^<<v19-115-12,12>>^ De nós se tem lembrado o SENHOR; ele nos abençoará; abençoará a casa de Israel, abençoará a casa de Arão.

[[v19-115-13]]

^<<v19-115-13,13>>^ Ele abençoa os que temem o SENHOR, tanto pequenos como grandes.

[[v19-115-14]]

^<<v19-115-14,14>>^ O SENHOR vos aumente bênçãos mais e mais, sobre vós e sobre vossos filhos.

[[v19-115-15]]

^<<v19-115-15,15>>^ Sede benditos do SENHOR, que fez os céus e a terra.

[[v19-115-16]]

^<<v19-115-16,16>>^ Os céus são os céus do SENHOR, mas a terra, deu-a ele aos filhos dos homens.

[[v19-115-17]]

^<<v19-115-17,17>>^ Os mortos não louvam o SENHOR, nem os que descem à região do silêncio.

[[v19-115-18]]

^<<v19-115-18,18>>^ Nós, porém, bendiremos o SENHOR, desde agora e para sempre. Aleluia!

'''

xref:019-salmos/019-salmos-114.adoc#v19-114-0[&#60; Capítulo Anterior] | <<v19-115-0,Topo>> | xref:019-salmos/019-salmos-116.adoc#v19-116-0[Próximo Capítulo &#62;]