include::./index.adoc[]

[[v19-101-0]]
=== Salmos, 101
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-101-1]]

^<<v19-101-1,1>>^ Cantarei a bondade e a justiça; a ti, SENHOR, cantarei.

[[v19-101-2]]

^<<v19-101-2,2>>^ Atentarei sabiamente ao caminho da perfeição. Oh! Quando virás ter comigo? Portas a dentro, em minha casa, terei coração sincero.

[[v19-101-3]]

^<<v19-101-3,3>>^ Não porei coisa injusta diante dos meus olhos; aborreço o proceder dos que se desviam; nada disto se me pegará.

[[v19-101-4]]

^<<v19-101-4,4>>^ Longe de mim o coração perverso; não quero conhecer o mal.

[[v19-101-5]]

^<<v19-101-5,5>>^ Ao que às ocultas calunia o próximo, a esse destruirei; o que tem olhar altivo e coração soberbo, não o suportarei.

[[v19-101-6]]

^<<v19-101-6,6>>^ Os meus olhos procurarão os fiéis da terra, para que habitem comigo; o que anda em reto caminho, esse me servirá.

[[v19-101-7]]

^<<v19-101-7,7>>^ Não há de ficar em minha casa o que usa de fraude; o que profere mentiras não permanecerá ante os meus olhos.

[[v19-101-8]]

^<<v19-101-8,8>>^ Manhã após manhã, destruirei todos os ímpios da terra, para limpar a cidade do Senhor dos que praticam a iniquidade.

'''

xref:019-salmos/019-salmos-100.adoc#v19-100-0[&#60; Capítulo Anterior] | <<v19-101-0,Topo>> | xref:019-salmos/019-salmos-102.adoc#v19-102-0[Próximo Capítulo &#62;]