include::./index.adoc[]

[[v19-68-0]]
=== Salmos, 68
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-68-1]]

^<<v19-68-1,1>>^ Levanta-se Deus; dispersam-se os seus inimigos; de sua presença fogem os que o aborrecem.

[[v19-68-2]]

^<<v19-68-2,2>>^ Como se dissipa a fumaça, assim tu os dispersas; como se derrete a cera ante o fogo, assim à presença de Deus perecem os iníquos.

[[v19-68-3]]

^<<v19-68-3,3>>^ Os justos, porém, se regozijam, exultam na presença de Deus e folgam de alegria.

[[v19-68-4]]

^<<v19-68-4,4>>^ Cantai a Deus, salmodiai o seu nome; exaltai o que cavalga sobre as nuvens. SENHOR é o seu nome, exultai diante dele.

[[v19-68-5]]

^<<v19-68-5,5>>^ Pai dos órfãos e juiz das viúvas é Deus em sua santa morada.

[[v19-68-6]]

^<<v19-68-6,6>>^ Deus faz que o solitário more em família; tira os cativos para a prosperidade; só os rebeldes habitam em terra estéril.

[[v19-68-7]]

^<<v19-68-7,7>>^ Ao saíres, ó Deus, à frente do teu povo, ao avançares pelo deserto,

[[v19-68-8]]

^<<v19-68-8,8>>^ tremeu a terra; também os céus gotejaram à presença de Deus; o próprio Sinai se abalou na presença de Deus, do Deus de Israel.

[[v19-68-9]]

^<<v19-68-9,9>>^ Copiosa chuva derramaste, ó Deus, para a tua herança; quando já ela estava exausta, tu a restabeleceste.

[[v19-68-10]]

^<<v19-68-10,10>>^ Aí habitou a tua grei; em tua bondade, ó Deus, fizeste provisão para os necessitados.

[[v19-68-11]]

^<<v19-68-11,11>>^ O Senhor deu a palavra, grande é a falange das mensageiras das boas-novas.

[[v19-68-12]]

^<<v19-68-12,12>>^ Reis de exércitos fogem e fogem; a dona de casa reparte os despojos.

[[v19-68-13]]

^<<v19-68-13,13>>^ Por que repousais entre as cercas dos apriscos? As asas da pomba são cobertas de prata, cujas penas maiores têm o brilho flavo do ouro.

[[v19-68-14]]

^<<v19-68-14,14>>^ Quando o Todo-Poderoso ali dispersa os reis, cai neve sobre o monte Zalmom.

[[v19-68-15]]

^<<v19-68-15,15>>^ O monte de Deus é Basã, serra de elevações é o monte de Basã.

[[v19-68-16]]

^<<v19-68-16,16>>^ Por que olhais com inveja, ó montes elevados, o monte que Deus escolheu para sua habitação? O SENHOR habitará nele para sempre.

[[v19-68-17]]

^<<v19-68-17,17>>^ Os carros de Deus são vinte mil, sim, milhares de milhares. No meio deles, está o Senhor; o Sinai tornou-se em santuário.

[[v19-68-18]]

^<<v19-68-18,18>>^ Subiste às alturas, levaste cativo o cativeiro; recebeste homens por dádivas, até mesmo rebeldes, para que o SENHOR Deus habite no meio deles.

[[v19-68-19]]

^<<v19-68-19,19>>^ Bendito seja o Senhor que, dia a dia, leva o nosso fardo! Deus é a nossa salvação.

[[v19-68-20]]

^<<v19-68-20,20>>^ O nosso Deus é o Deus libertador; com Deus, o SENHOR, está o escaparmos da morte.

[[v19-68-21]]

^<<v19-68-21,21>>^ Sim, Deus parte a cabeça dos seus inimigos e o cabeludo crânio do que anda nos seus próprios delitos.

[[v19-68-22]]

^<<v19-68-22,22>>^ Disse o Senhor: De Basã os farei voltar, fá-los-ei tornar das profundezas do mar,

[[v19-68-23]]

^<<v19-68-23,23>>^ para que banhes o pé em sangue, e a língua dos teus cães tenha o seu quinhão dos inimigos.

[[v19-68-24]]

^<<v19-68-24,24>>^ Viu-se, ó Deus, o teu cortejo, o cortejo do meu Deus, do meu Rei, no santuário.

[[v19-68-25]]

^<<v19-68-25,25>>^ Os cantores iam adiante, atrás, os tocadores de instrumentos de cordas, em meio às donzelas com adufes.

[[v19-68-26]]

^<<v19-68-26,26>>^ Bendizei a Deus nas congregações, bendizei ao SENHOR, vós que sois da estirpe de Israel.

[[v19-68-27]]

^<<v19-68-27,27>>^ Ali, está o mais novo, Benjamim, que os precede, os príncipes de Judá, com o seu séquito, os príncipes de Zebulom e os príncipes de Naftali.

[[v19-68-28]]

^<<v19-68-28,28>>^ Reúne, ó Deus, a tua força, força divina que usaste a nosso favor,

[[v19-68-29]]

^<<v19-68-29,29>>^ oriunda do teu templo em Jerusalém. Os reis te oferecerão presentes.

[[v19-68-30]]

^<<v19-68-30,30>>^ Reprime a fera dos canaviais, a multidão dos fortes como touros e dos povos com novilhos; calcai aos pés os que cobiçam barras de prata. Dispersa os povos que se comprazem na guerra.

[[v19-68-31]]

^<<v19-68-31,31>>^ Príncipes vêm do Egito; a Etiópia corre a estender mãos cheias para Deus.

[[v19-68-32]]

^<<v19-68-32,32>>^ Reinos da terra, cantai a Deus, salmodiai ao Senhor,

[[v19-68-33]]

^<<v19-68-33,33>>^ àquele que encima os céus, os céus da antiguidade; eis que ele faz ouvir a sua voz, voz poderosa.

[[v19-68-34]]

^<<v19-68-34,34>>^ Tributai glória a Deus; a sua majestade está sobre Israel, e a sua fortaleza, nos espaços siderais.

[[v19-68-35]]

^<<v19-68-35,35>>^ Ó Deus, tu és tremendo nos teus santuários; o Deus de Israel, ele dá força e poder ao povo. Bendito seja Deus!

'''

xref:019-salmos/019-salmos-067.adoc#v19-67-0[&#60; Capítulo Anterior] | <<v19-68-0,Topo>> | xref:019-salmos/019-salmos-069.adoc#v19-69-0[Próximo Capítulo &#62;]