include::./index.adoc[]

[[v19-103-0]]
=== Salmos, 103
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-103-1]]

^<<v19-103-1,1>>^ Bendize, ó minha alma, ao SENHOR, e tudo o que há em mim bendiga ao seu santo nome.

[[v19-103-2]]

^<<v19-103-2,2>>^ Bendize, ó minha alma, ao SENHOR, e não te esqueças de nem um só de seus benefícios.

[[v19-103-3]]

^<<v19-103-3,3>>^ Ele é quem perdoa todas as tuas iniquidades; quem sara todas as tuas enfermidades;

[[v19-103-4]]

^<<v19-103-4,4>>^ quem da cova redime a tua vida e te coroa de graça e misericórdia;

[[v19-103-5]]

^<<v19-103-5,5>>^ quem farta de bens a tua velhice, de sorte que a tua mocidade se renova como a da águia.

[[v19-103-6]]

^<<v19-103-6,6>>^ O SENHOR faz justiça e julga a todos os oprimidos.

[[v19-103-7]]

^<<v19-103-7,7>>^ Manifestou os seus caminhos a Moisés e os seus feitos aos filhos de Israel.

[[v19-103-8]]

^<<v19-103-8,8>>^ O SENHOR é misericordioso e compassivo; longânimo e assaz benigno.

[[v19-103-9]]

^<<v19-103-9,9>>^ Não repreende perpetuamente, nem conserva para sempre a sua ira.

[[v19-103-10]]

^<<v19-103-10,10>>^ Não nos trata segundo os nossos pecados, nem nos retribui consoante as nossas iniquidades.

[[v19-103-11]]

^<<v19-103-11,11>>^ Pois quanto o céu se alteia acima da terra, assim é grande a sua misericórdia para com os que o temem.

[[v19-103-12]]

^<<v19-103-12,12>>^ Quanto dista o Oriente do Ocidente, assim afasta de nós as nossas transgressões.

[[v19-103-13]]

^<<v19-103-13,13>>^ Como um pai se compadece de seus filhos, assim o SENHOR se compadece dos que o temem.

[[v19-103-14]]

^<<v19-103-14,14>>^ Pois ele conhece a nossa estrutura e sabe que somos pó.

[[v19-103-15]]

^<<v19-103-15,15>>^ Quanto ao homem, os seus dias são como a relva; como a flor do campo, assim ele floresce;

[[v19-103-16]]

^<<v19-103-16,16>>^ pois, soprando nela o vento, desaparece; e não conhecerá, daí em diante, o seu lugar.

[[v19-103-17]]

^<<v19-103-17,17>>^ Mas a misericórdia do SENHOR é de eternidade a eternidade, sobre os que o temem, e a sua justiça, sobre os filhos dos filhos,

[[v19-103-18]]

^<<v19-103-18,18>>^ para com os que guardam a sua aliança e para com os que se lembram dos seus preceitos e os cumprem.

[[v19-103-19]]

^<<v19-103-19,19>>^ Nos céus, estabeleceu o SENHOR o seu trono, e o seu reino domina sobre tudo.

[[v19-103-20]]

^<<v19-103-20,20>>^ Bendizei ao SENHOR, todos os seus anjos, valorosos em poder, que executais as suas ordens e lhe obedeceis à palavra.

[[v19-103-21]]

^<<v19-103-21,21>>^ Bendizei ao SENHOR, todos os seus exércitos, vós, ministros seus, que fazeis a sua vontade.

[[v19-103-22]]

^<<v19-103-22,22>>^ Bendizei ao SENHOR, vós, todas as suas obras, em todos os lugares do seu domínio. Bendize, ó minha alma, ao SENHOR.

'''

xref:019-salmos/019-salmos-102.adoc#v19-102-0[&#60; Capítulo Anterior] | <<v19-103-0,Topo>> | xref:019-salmos/019-salmos-104.adoc#v19-104-0[Próximo Capítulo &#62;]