include::./index.adoc[]

[[v19-53-0]]
=== Salmos, 53
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-53-1]]

^<<v19-53-1,1>>^ Diz o insensato no seu coração: Não há Deus. Corrompem-se e praticam iniquidade; já não há quem faça o bem.

[[v19-53-2]]

^<<v19-53-2,2>>^ Do céu, olha Deus para os filhos dos homens, para ver se há quem entenda, se há quem busque a Deus.

[[v19-53-3]]

^<<v19-53-3,3>>^ Todos se extraviaram e juntamente se corromperam; não há quem faça o bem, não há nem sequer um.

[[v19-53-4]]

^<<v19-53-4,4>>^ Acaso, não entendem os obreiros da iniquidade? Esses, que devoram o meu povo como quem come pão? Eles não invocam a Deus.

[[v19-53-5]]

^<<v19-53-5,5>>^ Tomam-se de grande pavor, onde não há a quem temer; porque Deus dispersa os ossos daquele que te sitia; tu os envergonhas, porque Deus os rejeita.

[[v19-53-6]]

^<<v19-53-6,6>>^ Quem me dera que de Sião viesse já o livramento de Israel! Quando Deus restaurar a sorte do seu povo, então, exultará Jacó, e Israel se alegrará.

'''

xref:019-salmos/019-salmos-052.adoc#v19-52-0[&#60; Capítulo Anterior] | <<v19-53-0,Topo>> | xref:019-salmos/019-salmos-054.adoc#v19-54-0[Próximo Capítulo &#62;]