include::./index.adoc[]

[[v19-11-0]]
=== Salmos, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-11-1]]

^<<v19-11-1,1>>^ No SENHOR me refugio. Como dizeis, pois, à minha alma: Foge, como pássaro, para o teu monte?

[[v19-11-2]]

^<<v19-11-2,2>>^ Porque eis aí os ímpios, armam o arco, dispõem a sua flecha na corda, para, às ocultas, dispararem contra os retos de coração.

[[v19-11-3]]

^<<v19-11-3,3>>^ Ora, destruídos os fundamentos, que poderá fazer o justo?

[[v19-11-4]]

^<<v19-11-4,4>>^ O SENHOR está no seu santo templo; nos céus tem o SENHOR seu trono; os seus olhos estão atentos, as suas pálpebras sondam os filhos dos homens.

[[v19-11-5]]

^<<v19-11-5,5>>^ O SENHOR põe à prova ao justo e ao ímpio; mas, ao que ama a violência, a sua alma o abomina.

[[v19-11-6]]

^<<v19-11-6,6>>^ Fará chover sobre os perversos brasas de fogo e enxofre, e vento abrasador será a parte do seu cálice.

[[v19-11-7]]

^<<v19-11-7,7>>^ Porque o SENHOR é justo, ele ama a justiça; os retos lhe contemplarão a face.

'''

xref:019-salmos/019-salmos-010.adoc#v19-10-0[&#60; Capítulo Anterior] | <<v19-11-0,Topo>> | xref:019-salmos/019-salmos-012.adoc#v19-12-0[Próximo Capítulo &#62;]