include::./index.adoc[]

[[v19-148-0]]
=== Salmos, 148
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-148-1]]

^<<v19-148-1,1>>^ Aleluia! Louvai ao SENHOR do alto dos céus, louvai-o nas alturas.

[[v19-148-2]]

^<<v19-148-2,2>>^ Louvai-o, todos os seus anjos; louvai-o, todas as suas legiões celestes.

[[v19-148-3]]

^<<v19-148-3,3>>^ Louvai-o, sol e lua; louvai-o, todas as estrelas luzentes.

[[v19-148-4]]

^<<v19-148-4,4>>^ Louvai-o, céus dos céus e as águas que estão acima do firmamento.

[[v19-148-5]]

^<<v19-148-5,5>>^ Louvem o nome do SENHOR, pois mandou ele, e foram criados.

[[v19-148-6]]

^<<v19-148-6,6>>^ E os estabeleceu para todo o sempre; fixou-lhes uma ordem que não passará.

[[v19-148-7]]

^<<v19-148-7,7>>^ Louvai ao SENHOR da terra, monstros marinhos e abismos todos;

[[v19-148-8]]

^<<v19-148-8,8>>^ fogo e saraiva, neve e vapor e ventos procelosos que lhe executam a palavra;

[[v19-148-9]]

^<<v19-148-9,9>>^ montes e todos os outeiros, árvores frutíferas e todos os cedros;

[[v19-148-10]]

^<<v19-148-10,10>>^ feras e gados, répteis e voláteis;

[[v19-148-11]]

^<<v19-148-11,11>>^ reis da terra e todos os povos, príncipes e todos os juízes da terra;

[[v19-148-12]]

^<<v19-148-12,12>>^ rapazes e donzelas, velhos e crianças.

[[v19-148-13]]

^<<v19-148-13,13>>^ Louvem o nome do SENHOR, porque só o seu nome é excelso; a sua majestade é acima da terra e do céu.

[[v19-148-14]]

^<<v19-148-14,14>>^ Ele exalta o poder do seu povo, o louvor de todos os seus santos, dos filhos de Israel, povo que lhe é chegado. Aleluia!

'''

xref:019-salmos/019-salmos-147.adoc#v19-147-0[&#60; Capítulo Anterior] | <<v19-148-0,Topo>> | xref:019-salmos/019-salmos-149.adoc#v19-149-0[Próximo Capítulo &#62;]