include::./index.adoc[]

[[v19-57-0]]
=== Salmos, 57
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-57-1]]

^<<v19-57-1,1>>^ Tem misericórdia de mim, ó Deus, tem misericórdia, pois em ti a minha alma se refugia; à sombra das tuas asas me abrigo, até que passem as calamidades.

[[v19-57-2]]

^<<v19-57-2,2>>^ Clamarei ao Deus Altíssimo, ao Deus que por mim tudo executa.

[[v19-57-3]]

^<<v19-57-3,3>>^ Ele dos céus me envia o seu auxílio e me livra; cobre de vergonha os que me ferem. Envia a sua misericórdia e a sua fidelidade.

[[v19-57-4]]

^<<v19-57-4,4>>^ Acha-se a minha alma entre leões, ávidos de devorar os filhos dos homens; lanças e flechas são os seus dentes, espada afiada, a sua língua.

[[v19-57-5]]

^<<v19-57-5,5>>^ Sê exaltado, ó Deus, acima dos céus; e em toda a terra esplenda a tua glória.

[[v19-57-6]]

^<<v19-57-6,6>>^ Armaram rede aos meus passos, a minha alma está abatida; abriram cova diante de mim, mas eles mesmos caíram nela.

[[v19-57-7]]

^<<v19-57-7,7>>^ Firme está o meu coração, ó Deus, o meu coração está firme; cantarei e entoarei louvores.

[[v19-57-8]]

^<<v19-57-8,8>>^ Desperta, ó minha alma! Despertai, lira e harpa! Quero acordar a alva.

[[v19-57-9]]

^<<v19-57-9,9>>^ Render-te-ei graças entre os povos; cantar-te-ei louvores entre as nações.

[[v19-57-10]]

^<<v19-57-10,10>>^ Pois a tua misericórdia se eleva até aos céus, e a tua fidelidade, até às nuvens.

[[v19-57-11]]

^<<v19-57-11,11>>^ Sê exaltado, ó Deus, acima dos céus; e em toda a terra esplenda a tua glória.

'''

xref:019-salmos/019-salmos-056.adoc#v19-56-0[&#60; Capítulo Anterior] | <<v19-57-0,Topo>> | xref:019-salmos/019-salmos-058.adoc#v19-58-0[Próximo Capítulo &#62;]