include::./index.adoc[]

[[v19-94-0]]
=== Salmos, 94
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-94-1]]

^<<v19-94-1,1>>^ Ó SENHOR, Deus das vinganças, ó Deus das vinganças, resplandece.

[[v19-94-2]]

^<<v19-94-2,2>>^ Exalta-te, ó juiz da terra; dá o pago aos soberbos.

[[v19-94-3]]

^<<v19-94-3,3>>^ Até quando, SENHOR, os perversos, até quando exultarão os perversos?

[[v19-94-4]]

^<<v19-94-4,4>>^ Proferem impiedades e falam coisas duras; vangloriam-se os que praticam a iniquidade.

[[v19-94-5]]

^<<v19-94-5,5>>^ Esmagam o teu povo, SENHOR, e oprimem a tua herança.

[[v19-94-6]]

^<<v19-94-6,6>>^ Matam a viúva e o estrangeiro e aos órfãos assassinam.

[[v19-94-7]]

^<<v19-94-7,7>>^ E dizem: O SENHOR não o vê; nem disso faz caso o Deus de Jacó.

[[v19-94-8]]

^<<v19-94-8,8>>^ Atendei, ó estúpidos dentre o povo; e vós, insensatos, quando sereis prudentes?

[[v19-94-9]]

^<<v19-94-9,9>>^ O que fez o ouvido, acaso, não ouvirá? E o que formou os olhos será que não enxerga?

[[v19-94-10]]

^<<v19-94-10,10>>^ Porventura, quem repreende as nações não há de punir? Aquele que aos homens dá conhecimento não tem sabedoria?

[[v19-94-11]]

^<<v19-94-11,11>>^ O SENHOR conhece os pensamentos do homem, que são pensamentos vãos.

[[v19-94-12]]

^<<v19-94-12,12>>^ Bem-aventurado o homem, SENHOR, a quem tu repreendes, a quem ensinas a tua lei,

[[v19-94-13]]

^<<v19-94-13,13>>^ para lhe dares descanso dos dias maus, até que se abra a cova para o ímpio.

[[v19-94-14]]

^<<v19-94-14,14>>^ Pois o SENHOR não há de rejeitar o seu povo, nem desamparar a sua herança.

[[v19-94-15]]

^<<v19-94-15,15>>^ Mas o juízo se converterá em justiça, e segui-la-ão todos os de coração reto.

[[v19-94-16]]

^<<v19-94-16,16>>^ Quem se levantará a meu favor, contra os perversos? Quem estará comigo contra os que praticam a iniquidade?

[[v19-94-17]]

^<<v19-94-17,17>>^ Se não fora o auxílio do SENHOR, já a minha alma estaria na região do silêncio.

[[v19-94-18]]

^<<v19-94-18,18>>^ Quando eu digo: resvala-me o pé, a tua benignidade, SENHOR, me sustém.

[[v19-94-19]]

^<<v19-94-19,19>>^ Nos muitos cuidados que dentro de mim se multiplicam, as tuas consolações me alegram a alma.

[[v19-94-20]]

^<<v19-94-20,20>>^ Pode, acaso, associar-se contigo o trono da iniquidade, o qual forja o mal, tendo uma lei por pretexto?

[[v19-94-21]]

^<<v19-94-21,21>>^ Ajuntam-se contra a vida do justo e condenam o sangue inocente.

[[v19-94-22]]

^<<v19-94-22,22>>^ Mas o SENHOR é o meu baluarte e o meu Deus, o rochedo em que me abrigo.

[[v19-94-23]]

^<<v19-94-23,23>>^ Sobre eles faz recair a sua iniquidade e pela malícia deles próprios os destruirá; o SENHOR, nosso Deus, os exterminará.

'''

xref:019-salmos/019-salmos-093.adoc#v19-93-0[&#60; Capítulo Anterior] | <<v19-94-0,Topo>> | xref:019-salmos/019-salmos-095.adoc#v19-95-0[Próximo Capítulo &#62;]