include::./index.adoc[]

[[v19-55-0]]
=== Salmos, 55
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-55-1]]

^<<v19-55-1,1>>^ Dá ouvidos, ó Deus, à minha oração; não te escondas da minha súplica.

[[v19-55-2]]

^<<v19-55-2,2>>^ Atende-me e responde-me; sinto-me perplexo em minha queixa e ando perturbado,

[[v19-55-3]]

^<<v19-55-3,3>>^ por causa do clamor do inimigo e da opressão do ímpio; pois sobre mim lançam calamidade e furiosamente me hostilizam.

[[v19-55-4]]

^<<v19-55-4,4>>^ Estremece-me no peito o coração, terrores de morte me salteiam;

[[v19-55-5]]

^<<v19-55-5,5>>^ temor e tremor me sobrevêm, e o horror se apodera de mim.

[[v19-55-6]]

^<<v19-55-6,6>>^ Então, disse eu: quem me dera asas como de pomba! Voaria e acharia pouso.

[[v19-55-7]]

^<<v19-55-7,7>>^ Eis que fugiria para longe e ficaria no deserto.

[[v19-55-8]]

^<<v19-55-8,8>>^ Dar-me-ia pressa em abrigar-me do vendaval e da procela.

[[v19-55-9]]

^<<v19-55-9,9>>^ Destrói, Senhor, e confunde os seus conselhos, porque vejo violência e contenda na cidade.

[[v19-55-10]]

^<<v19-55-10,10>>^ Dia e noite giram nas suas muralhas, e, muros a dentro, campeia a perversidade e a malícia;

[[v19-55-11]]

^<<v19-55-11,11>>^ há destruição no meio dela; das suas praças não se apartam a opressão e o engano.

[[v19-55-12]]

^<<v19-55-12,12>>^ Com efeito, não é inimigo que me afronta; se o fosse, eu o suportaria; nem é o que me odeia quem se exalta contra mim, pois dele eu me esconderia;

[[v19-55-13]]

^<<v19-55-13,13>>^ mas és tu, homem meu igual, meu companheiro e meu íntimo amigo.

[[v19-55-14]]

^<<v19-55-14,14>>^ Juntos andávamos, juntos nos entretínhamos e íamos com a multidão à Casa de Deus.

[[v19-55-15]]

^<<v19-55-15,15>>^ A morte os assalte, e vivos desçam à cova! Porque há maldade nas suas moradas e no seu íntimo.

[[v19-55-16]]

^<<v19-55-16,16>>^ Eu, porém, invocarei a Deus, e o SENHOR me salvará.

[[v19-55-17]]

^<<v19-55-17,17>>^ À tarde, pela manhã e ao meio-dia, farei as minhas queixas e lamentarei; e ele ouvirá a minha voz.

[[v19-55-18]]

^<<v19-55-18,18>>^ Livra-me a alma, em paz, dos que me perseguem; pois são muitos contra mim.

[[v19-55-19]]

^<<v19-55-19,19>>^ Deus ouvirá e lhes responderá, ele, que preside desde a eternidade, porque não há neles mudança nenhuma, e não temem a Deus.

[[v19-55-20]]

^<<v19-55-20,20>>^ Tal homem estendeu as mãos contra os que tinham paz com ele; corrompeu a sua aliança.

[[v19-55-21]]

^<<v19-55-21,21>>^ A sua boca era mais macia que a manteiga, porém no coração havia guerra; as suas palavras eram mais brandas que o azeite; contudo, eram espadas desembainhadas.

[[v19-55-22]]

^<<v19-55-22,22>>^ Confia os teus cuidados ao SENHOR, e ele te susterá; jamais permitirá que o justo seja abalado.

[[v19-55-23]]

^<<v19-55-23,23>>^ Tu, porém, ó Deus, os precipitarás à cova profunda; homens sanguinários e fraudulentos não chegarão à metade dos seus dias; eu, todavia, confiarei em ti.

'''

xref:019-salmos/019-salmos-054.adoc#v19-54-0[&#60; Capítulo Anterior] | <<v19-55-0,Topo>> | xref:019-salmos/019-salmos-056.adoc#v19-56-0[Próximo Capítulo &#62;]