include::./index.adoc[]

[[v19-132-0]]
=== Salmos, 132
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-132-1]]

^<<v19-132-1,1>>^ Lembra-te, SENHOR, a favor de Davi, de todas as suas provações;

[[v19-132-2]]

^<<v19-132-2,2>>^ de como jurou ao Senhor e fez votos ao Poderoso de Jacó:

[[v19-132-3]]

^<<v19-132-3,3>>^ Não entrarei na tenda em que moro, nem subirei ao leito em que repouso,

[[v19-132-4]]

^<<v19-132-4,4>>^ não darei sono aos meus olhos, nem repouso às minhas pálpebras,

[[v19-132-5]]

^<<v19-132-5,5>>^ até que eu encontre lugar para o SENHOR, morada para o Poderoso de Jacó.

[[v19-132-6]]

^<<v19-132-6,6>>^ Ouvimos dizer que a arca se achava em Efrata e a encontramos no campo de Jaar.

[[v19-132-7]]

^<<v19-132-7,7>>^ Entremos na sua morada, adoremos ante o estrado de seus pés.

[[v19-132-8]]

^<<v19-132-8,8>>^ Levanta-te, SENHOR, entra no lugar do teu repouso, tu e a arca de tua fortaleza.

[[v19-132-9]]

^<<v19-132-9,9>>^ Vistam-se de justiça os teus sacerdotes, e exultem os teus fiéis.

[[v19-132-10]]

^<<v19-132-10,10>>^ Por amor de Davi, teu servo, não desprezes o rosto do teu ungido.

[[v19-132-11]]

^<<v19-132-11,11>>^ O SENHOR jurou a Davi com firme juramento e dele não se apartará: Um rebento da tua carne farei subir para o teu trono.

[[v19-132-12]]

^<<v19-132-12,12>>^ Se os teus filhos guardarem a minha aliança e o testemunho que eu lhes ensinar, também os seus filhos se assentarão para sempre no teu trono.

[[v19-132-13]]

^<<v19-132-13,13>>^ Pois o SENHOR escolheu a Sião, preferiu-a por sua morada:

[[v19-132-14]]

^<<v19-132-14,14>>^ Este é para sempre o lugar do meu repouso; aqui habitarei, pois o preferi.

[[v19-132-15]]

^<<v19-132-15,15>>^ Abençoarei com abundância o seu mantimento e de pão fartarei os seus pobres.

[[v19-132-16]]

^<<v19-132-16,16>>^ Vestirei de salvação os seus sacerdotes, e de júbilo exultarão os seus fiéis.

[[v19-132-17]]

^<<v19-132-17,17>>^ Ali, farei brotar a força de Davi; preparei uma lâmpada para o meu ungido.

[[v19-132-18]]

^<<v19-132-18,18>>^ Cobrirei de vexame os seus inimigos; mas sobre ele florescerá a sua coroa.

'''

xref:019-salmos/019-salmos-131.adoc#v19-131-0[&#60; Capítulo Anterior] | <<v19-132-0,Topo>> | xref:019-salmos/019-salmos-133.adoc#v19-133-0[Próximo Capítulo &#62;]