include::./index.adoc[]

[[v19-28-0]]
=== Salmos, 28
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-28-1]]

^<<v19-28-1,1>>^ A ti clamo, ó SENHOR; rocha minha, não sejas surdo para comigo; para que não suceda, se te calares acerca de mim, seja eu semelhante aos que descem à cova.

[[v19-28-2]]

^<<v19-28-2,2>>^ Ouve-me as vozes súplices, quando a ti clamar por socorro, quando erguer as mãos para o teu santuário.

[[v19-28-3]]

^<<v19-28-3,3>>^ Não me arrastes com os ímpios, com os que praticam a iniquidade; os quais falam de paz ao seu próximo, porém no coração têm perversidade.

[[v19-28-4]]

^<<v19-28-4,4>>^ Paga-lhes segundo as suas obras, segundo a malícia dos seus atos; dá-lhes conforme a obra de suas mãos, retribui-lhes o que merecem.

[[v19-28-5]]

^<<v19-28-5,5>>^ E, visto que não atentam para os feitos do SENHOR, nem para o que as suas mãos fazem, ele os derribará e não os reedificará.

[[v19-28-6]]

^<<v19-28-6,6>>^ Bendito seja o SENHOR, porque me ouviu as vozes súplices!

[[v19-28-7]]

^<<v19-28-7,7>>^ O SENHOR é a minha força e o meu escudo; nele o meu coração confia, nele fui socorrido; por isso, o meu coração exulta, e com o meu cântico o louvarei.

[[v19-28-8]]

^<<v19-28-8,8>>^ O SENHOR é a força do seu povo, o refúgio salvador do seu ungido.

[[v19-28-9]]

^<<v19-28-9,9>>^ Salva o teu povo e abençoa a tua herança; apascenta-o e exalta-o para sempre.

'''

xref:019-salmos/019-salmos-027.adoc#v19-27-0[&#60; Capítulo Anterior] | <<v19-28-0,Topo>> | xref:019-salmos/019-salmos-029.adoc#v19-29-0[Próximo Capítulo &#62;]