include::./index.adoc[]

[[v19-110-0]]
=== Salmos, 110
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-110-1]]

^<<v19-110-1,1>>^ Disse o SENHOR ao meu senhor: Assenta-te à minha direita, até que eu ponha os teus inimigos debaixo dos teus pés.

[[v19-110-2]]

^<<v19-110-2,2>>^ O SENHOR enviará de Sião o cetro do seu poder, dizendo: Domina entre os teus inimigos.

[[v19-110-3]]

^<<v19-110-3,3>>^ Apresentar-se-á voluntariamente o teu povo, no dia do teu poder; com santos ornamentos, como o orvalho emergindo da aurora, serão os teus jovens.

[[v19-110-4]]

^<<v19-110-4,4>>^ O SENHOR jurou e não se arrependerá: Tu és sacerdote para sempre, segundo a ordem de Melquisedeque.

[[v19-110-5]]

^<<v19-110-5,5>>^ O Senhor, à tua direita, no dia da sua ira, esmagará os reis.

[[v19-110-6]]

^<<v19-110-6,6>>^ Ele julga entre as nações; enche-as de cadáveres; esmagará cabeças por toda a terra.

[[v19-110-7]]

^<<v19-110-7,7>>^ De caminho, bebe na torrente e passa de cabeça erguida.

'''

xref:019-salmos/019-salmos-109.adoc#v19-109-0[&#60; Capítulo Anterior] | <<v19-110-0,Topo>> | xref:019-salmos/019-salmos-111.adoc#v19-111-0[Próximo Capítulo &#62;]