include::./index.adoc[]

[[v19-52-0]]
=== Salmos, 52
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-52-1]]

^<<v19-52-1,1>>^ Por que te glorias na maldade, ó homem poderoso? Pois a bondade de Deus dura para sempre.

[[v19-52-2]]

^<<v19-52-2,2>>^ A tua língua urde planos de destruição; é qual navalha afiada, ó praticadora de enganos!

[[v19-52-3]]

^<<v19-52-3,3>>^ Amas o mal antes que o bem; preferes mentir a falar retamente.

[[v19-52-4]]

^<<v19-52-4,4>>^ Amas todas as palavras devoradoras, ó língua fraudulenta!

[[v19-52-5]]

^<<v19-52-5,5>>^ Também Deus te destruirá para sempre; há de arrebatar-te e arrancar-te da tua tenda e te extirpará da terra dos viventes.

[[v19-52-6]]

^<<v19-52-6,6>>^ Os justos hão de ver tudo isso, temerão e se rirão dele, dizendo:

[[v19-52-7]]

^<<v19-52-7,7>>^ Eis o homem que não fazia de Deus a sua fortaleza; antes, confiava na abundância dos seus próprios bens e na sua perversidade se fortalecia.

[[v19-52-8]]

^<<v19-52-8,8>>^ Quanto a mim, porém, sou como a oliveira verdejante, na Casa de Deus; confio na misericórdia de Deus para todo o sempre.

[[v19-52-9]]

^<<v19-52-9,9>>^ Dar-te-ei graças para sempre, porque assim o fizeste; na presença dos teus fiéis, esperarei no teu nome, porque é bom.

'''

xref:019-salmos/019-salmos-051.adoc#v19-51-0[&#60; Capítulo Anterior] | <<v19-52-0,Topo>> | xref:019-salmos/019-salmos-053.adoc#v19-53-0[Próximo Capítulo &#62;]