include::./index.adoc[]

[[v19-88-0]]
=== Salmos, 88
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-88-1]]

^<<v19-88-1,1>>^ Ó SENHOR, Deus da minha salvação, dia e noite clamo diante de ti.

[[v19-88-2]]

^<<v19-88-2,2>>^ Chegue à tua presença a minha oração, inclina os ouvidos ao meu clamor.

[[v19-88-3]]

^<<v19-88-3,3>>^ Pois a minha alma está farta de males, e a minha vida já se abeira da morte.

[[v19-88-4]]

^<<v19-88-4,4>>^ Sou contado com os que baixam à cova; sou como um homem sem força,

[[v19-88-5]]

^<<v19-88-5,5>>^ atirado entre os mortos; como os feridos de morte que jazem na sepultura, dos quais já não te lembras; são desamparados de tuas mãos.

[[v19-88-6]]

^<<v19-88-6,6>>^ Puseste-me na mais profunda cova, nos lugares tenebrosos, nos abismos.

[[v19-88-7]]

^<<v19-88-7,7>>^ Sobre mim pesa a tua ira; tu me abates com todas as tuas ondas.

[[v19-88-8]]

^<<v19-88-8,8>>^ Apartaste de mim os meus conhecidos e me fizeste objeto de abominação para com eles; estou preso e não vejo como sair.

[[v19-88-9]]

^<<v19-88-9,9>>^ Os meus olhos desfalecem de aflição; dia após dia, venho clamando a ti, SENHOR, e te levanto as minhas mãos.

[[v19-88-10]]

^<<v19-88-10,10>>^ Mostrarás tu prodígios aos mortos ou os finados se levantarão para te louvar?

[[v19-88-11]]

^<<v19-88-11,11>>^ Será referida a tua bondade na sepultura? A tua fidelidade, nos abismos?

[[v19-88-12]]

^<<v19-88-12,12>>^ Acaso, nas trevas se manifestam as tuas maravilhas? E a tua justiça, na terra do esquecimento?

[[v19-88-13]]

^<<v19-88-13,13>>^ Mas eu, SENHOR, clamo a ti por socorro, e antemanhã já se antecipa diante de ti a minha oração.

[[v19-88-14]]

^<<v19-88-14,14>>^ Por que rejeitas, SENHOR, a minha alma e ocultas de mim o rosto?

[[v19-88-15]]

^<<v19-88-15,15>>^ Ando aflito e prestes a expirar desde moço; sob o peso dos teus terrores, estou desorientado.

[[v19-88-16]]

^<<v19-88-16,16>>^ Por sobre mim passaram as tuas iras, os teus terrores deram cabo de mim.

[[v19-88-17]]

^<<v19-88-17,17>>^ Eles me rodeiam como água, de contínuo; a um tempo me circundam.

[[v19-88-18]]

^<<v19-88-18,18>>^ Para longe de mim afastaste amigo e companheiro; os meus conhecidos são trevas.

'''

xref:019-salmos/019-salmos-087.adoc#v19-87-0[&#60; Capítulo Anterior] | <<v19-88-0,Topo>> | xref:019-salmos/019-salmos-089.adoc#v19-89-0[Próximo Capítulo &#62;]