include::./index.adoc[]

[[v19-14-0]]
=== Salmos, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-14-1]]

^<<v19-14-1,1>>^ Diz o insensato no seu coração: Não há Deus. Corrompem-se e praticam abominação; já não há quem faça o bem.

[[v19-14-2]]

^<<v19-14-2,2>>^ Do céu olha o SENHOR para os filhos dos homens, para ver se há quem entenda, se há quem busque a Deus.

[[v19-14-3]]

^<<v19-14-3,3>>^ Todos se extraviaram e juntamente se corromperam; não há quem faça o bem, não há nem um sequer.

[[v19-14-4]]

^<<v19-14-4,4>>^ Acaso, não entendem todos os obreiros da iniquidade, que devoram o meu povo, como quem come pão, que não invocam o SENHOR?

[[v19-14-5]]

^<<v19-14-5,5>>^ Tomar-se-ão de grande pavor, porque Deus está com a linhagem do justo.

[[v19-14-6]]

^<<v19-14-6,6>>^ Meteis a ridículo o conselho dos humildes, mas o SENHOR é o seu refúgio.

[[v19-14-7]]

^<<v19-14-7,7>>^ Tomara de Sião viesse já a salvação de Israel! Quando o SENHOR restaurar a sorte do seu povo, então, exultará Jacó, e Israel se alegrará.

'''

xref:019-salmos/019-salmos-013.adoc#v19-13-0[&#60; Capítulo Anterior] | <<v19-14-0,Topo>> | xref:019-salmos/019-salmos-015.adoc#v19-15-0[Próximo Capítulo &#62;]