include::./index.adoc[]

[[v19-138-0]]
=== Salmos, 138
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-138-1]]

^<<v19-138-1,1>>^ Render-te-ei graças, SENHOR, de todo o meu coração; na presença dos poderosos te cantarei louvores.

[[v19-138-2]]

^<<v19-138-2,2>>^ Prostrar-me-ei para o teu santo templo e louvarei o teu nome, por causa da tua misericórdia e da tua verdade, pois magnificaste acima de tudo o teu nome e a tua palavra.

[[v19-138-3]]

^<<v19-138-3,3>>^ No dia em que eu clamei, tu me acudiste e alentaste a força de minha alma.

[[v19-138-4]]

^<<v19-138-4,4>>^ Render-te-ão graças, ó SENHOR, todos os reis da terra, quando ouvirem as palavras da tua boca,

[[v19-138-5]]

^<<v19-138-5,5>>^ e cantarão os caminhos do SENHOR, pois grande é a glória do SENHOR.

[[v19-138-6]]

^<<v19-138-6,6>>^ O SENHOR é excelso, contudo, atenta para os humildes; os soberbos, ele os conhece de longe.

[[v19-138-7]]

^<<v19-138-7,7>>^ Se ando em meio à tribulação, tu me refazes a vida; estendes a mão contra a ira dos meus inimigos; a tua destra me salva.

[[v19-138-8]]

^<<v19-138-8,8>>^ O que a mim me concerne o SENHOR levará a bom termo; a tua misericórdia, ó SENHOR, dura para sempre; não desampares as obras das tuas mãos.

'''

xref:019-salmos/019-salmos-137.adoc#v19-137-0[&#60; Capítulo Anterior] | <<v19-138-0,Topo>> | xref:019-salmos/019-salmos-139.adoc#v19-139-0[Próximo Capítulo &#62;]