include::./index.adoc[]

[[v19-71-0]]
=== Salmos, 71
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-71-1]]

^<<v19-71-1,1>>^ Em ti, SENHOR, me refugio; não seja eu jamais envergonhado.

[[v19-71-2]]

^<<v19-71-2,2>>^ Livra-me por tua justiça e resgata-me; inclina-me os ouvidos e salva-me.

[[v19-71-3]]

^<<v19-71-3,3>>^ Sê tu para mim uma rocha habitável em que sempre me acolha; ordenaste que eu me salve, pois tu és a minha rocha e a minha fortaleza.

[[v19-71-4]]

^<<v19-71-4,4>>^ Livra-me, Deus meu, das mãos do ímpio, das garras do homem injusto e cruel.

[[v19-71-5]]

^<<v19-71-5,5>>^ Pois tu és a minha esperança, SENHOR Deus, a minha confiança desde a minha mocidade.

[[v19-71-6]]

^<<v19-71-6,6>>^ Em ti me tenho apoiado desde o meu nascimento; do ventre materno tu me tiraste, tu és motivo para os meus louvores constantemente.

[[v19-71-7]]

^<<v19-71-7,7>>^ Para muitos sou como um portento, mas tu és o meu forte refúgio.

[[v19-71-8]]

^<<v19-71-8,8>>^ Os meus lábios estão cheios do teu louvor e da tua glória continuamente.

[[v19-71-9]]

^<<v19-71-9,9>>^ Não me rejeites na minha velhice; quando me faltarem as forças, não me desampares.

[[v19-71-10]]

^<<v19-71-10,10>>^ Pois falam contra mim os meus inimigos; e os que me espreitam a alma consultam reunidos,

[[v19-71-11]]

^<<v19-71-11,11>>^ dizendo: Deus o desamparou; persegui-o e prendei-o, pois não há quem o livre.

[[v19-71-12]]

^<<v19-71-12,12>>^ Não te ausentes de mim, ó Deus; Deus meu, apressa-te em socorrer-me.

[[v19-71-13]]

^<<v19-71-13,13>>^ Sejam envergonhados e consumidos os que são adversários de minha alma; cubram-se de opróbrio e de vexame os que procuram o mal contra mim.

[[v19-71-14]]

^<<v19-71-14,14>>^ Quanto a mim, esperarei sempre e te louvarei mais e mais.

[[v19-71-15]]

^<<v19-71-15,15>>^ A minha boca relatará a tua justiça e de contínuo os feitos da tua salvação, ainda que eu não saiba o seu número.

[[v19-71-16]]

^<<v19-71-16,16>>^ Sinto-me na força do SENHOR Deus; e rememoro a tua justiça, a tua somente.

[[v19-71-17]]

^<<v19-71-17,17>>^ Tu me tens ensinado, ó Deus, desde a minha mocidade; e até agora tenho anunciado as tuas maravilhas.

[[v19-71-18]]

^<<v19-71-18,18>>^ Não me desampares, pois, ó Deus, até à minha velhice e às cãs; até que eu tenha declarado à presente geração a tua força e às vindouras o teu poder.

[[v19-71-19]]

^<<v19-71-19,19>>^ Ora, a tua justiça, ó Deus, se eleva até aos céus. Grandes coisas tens feito, ó Deus; quem é semelhante a ti?

[[v19-71-20]]

^<<v19-71-20,20>>^ Tu, que me tens feito ver muitas angústias e males, me restaurarás ainda a vida e de novo me tirarás dos abismos da terra.

[[v19-71-21]]

^<<v19-71-21,21>>^ Aumenta a minha grandeza, conforta-me novamente.

[[v19-71-22]]

^<<v19-71-22,22>>^ Eu também te louvo com a lira, celebro a tua verdade, ó meu Deus; cantar-te-ei salmos na harpa, ó Santo de Israel.

[[v19-71-23]]

^<<v19-71-23,23>>^ Os meus lábios exultarão quando eu te salmodiar; também exultará a minha alma, que remiste.

[[v19-71-24]]

^<<v19-71-24,24>>^ Igualmente a minha língua celebrará a tua justiça todo o dia; pois estão envergonhados e confundidos os que procuram o mal contra mim.

'''

xref:019-salmos/019-salmos-070.adoc#v19-70-0[&#60; Capítulo Anterior] | <<v19-71-0,Topo>> | xref:019-salmos/019-salmos-072.adoc#v19-72-0[Próximo Capítulo &#62;]