include::./index.adoc[]

[[v19-65-0]]
=== Salmos, 65
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-65-1]]

^<<v19-65-1,1>>^ A ti, ó Deus, confiança e louvor em Sião! E a ti se pagará o voto.

[[v19-65-2]]

^<<v19-65-2,2>>^ Ó tu que escutas a oração, a ti virão todos os homens,

[[v19-65-3]]

^<<v19-65-3,3>>^ por causa de suas iniquidades. Se prevalecem as nossas transgressões, tu no-las perdoas.

[[v19-65-4]]

^<<v19-65-4,4>>^ Bem-aventurado aquele a quem escolhes e aproximas de ti, para que assista nos teus átrios; ficaremos satisfeitos com a bondade de tua casa — o teu santo templo.

[[v19-65-5]]

^<<v19-65-5,5>>^ Com tremendos feitos nos respondes em tua justiça, ó Deus, Salvador nosso, esperança de todos os confins da terra e dos mares longínquos;

[[v19-65-6]]

^<<v19-65-6,6>>^ que por tua força consolidas os montes, cingido de poder;

[[v19-65-7]]

^<<v19-65-7,7>>^ que aplacas o rugir dos mares, o ruído das suas ondas e o tumulto das gentes.

[[v19-65-8]]

^<<v19-65-8,8>>^ Os que habitam nos confins da terra temem os teus sinais; os que vêm do Oriente e do Ocidente, tu os fazes exultar de júbilo.

[[v19-65-9]]

^<<v19-65-9,9>>^ Tu visitas a terra e a regas; tu a enriqueces copiosamente; os ribeiros de Deus são abundantes de água; preparas o cereal, porque para isso a dispões,

[[v19-65-10]]

^<<v19-65-10,10>>^ regando-lhe os sulcos, aplanando-lhe as leivas. Tu a amoleces com chuviscos e lhe abençoas a produção.

[[v19-65-11]]

^<<v19-65-11,11>>^ Coroas o ano da tua bondade; as tuas pegadas destilam fartura,

[[v19-65-12]]

^<<v19-65-12,12>>^ destilam sobre as pastagens do deserto, e de júbilo se revestem os outeiros.

[[v19-65-13]]

^<<v19-65-13,13>>^ Os campos cobrem-se de rebanhos, e os vales vestem-se de espigas; exultam de alegria e cantam.

'''

xref:019-salmos/019-salmos-064.adoc#v19-64-0[&#60; Capítulo Anterior] | <<v19-65-0,Topo>> | xref:019-salmos/019-salmos-066.adoc#v19-66-0[Próximo Capítulo &#62;]