include::./index.adoc[]

[[v19-82-0]]
=== Salmos, 82
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-82-1]]

^<<v19-82-1,1>>^ Deus assiste na congregação divina; no meio dos deuses, estabelece o seu julgamento.

[[v19-82-2]]

^<<v19-82-2,2>>^ Até quando julgareis injustamente e tomareis partido pela causa dos ímpios?

[[v19-82-3]]

^<<v19-82-3,3>>^ Fazei justiça ao fraco e ao órfão, procedei retamente para com o aflito e o desamparado.

[[v19-82-4]]

^<<v19-82-4,4>>^ Socorrei o fraco e o necessitado; tirai-os das mãos dos ímpios.

[[v19-82-5]]

^<<v19-82-5,5>>^ Eles nada sabem, nem entendem; vagueiam em trevas; vacilam todos os fundamentos da terra.

[[v19-82-6]]

^<<v19-82-6,6>>^ Eu disse: sois deuses, sois todos filhos do Altíssimo.

[[v19-82-7]]

^<<v19-82-7,7>>^ Todavia, como homens, morrereis e, como qualquer dos príncipes, haveis de sucumbir.

[[v19-82-8]]

^<<v19-82-8,8>>^ Levanta-te, ó Deus, julga a terra, pois a ti compete a herança de todas as nações.

'''

xref:019-salmos/019-salmos-081.adoc#v19-81-0[&#60; Capítulo Anterior] | <<v19-82-0,Topo>> | xref:019-salmos/019-salmos-083.adoc#v19-83-0[Próximo Capítulo &#62;]