include::./index.adoc[]

[[v19-29-0]]
=== Salmos, 29
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-29-1]]

^<<v19-29-1,1>>^ Tributai ao SENHOR, filhos de Deus, tributai ao SENHOR glória e força.

[[v19-29-2]]

^<<v19-29-2,2>>^ Tributai ao SENHOR a glória devida ao seu nome, adorai o SENHOR na beleza da santidade.

[[v19-29-3]]

^<<v19-29-3,3>>^ Ouve-se a voz do SENHOR sobre as águas; troveja o Deus da glória; o SENHOR está sobre as muitas águas.

[[v19-29-4]]

^<<v19-29-4,4>>^ A voz do SENHOR é poderosa; a voz do SENHOR é cheia de majestade.

[[v19-29-5]]

^<<v19-29-5,5>>^ A voz do SENHOR quebra os cedros; sim, o SENHOR despedaça os cedros do Líbano.

[[v19-29-6]]

^<<v19-29-6,6>>^ Ele os faz saltar como um bezerro; o Líbano e o Siriom, como bois selvagens.

[[v19-29-7]]

^<<v19-29-7,7>>^ A voz do SENHOR despede chamas de fogo.

[[v19-29-8]]

^<<v19-29-8,8>>^ A voz do SENHOR faz tremer o deserto; o SENHOR faz tremer o deserto de Cades.

[[v19-29-9]]

^<<v19-29-9,9>>^ A voz do SENHOR faz dar cria às corças e desnuda os bosques; e no seu templo tudo diz: Glória!

[[v19-29-10]]

^<<v19-29-10,10>>^ O SENHOR preside aos dilúvios; como rei, o SENHOR presidirá para sempre.

[[v19-29-11]]

^<<v19-29-11,11>>^ O SENHOR dá força ao seu povo, o SENHOR abençoa com paz ao seu povo.

'''

xref:019-salmos/019-salmos-028.adoc#v19-28-0[&#60; Capítulo Anterior] | <<v19-29-0,Topo>> | xref:019-salmos/019-salmos-030.adoc#v19-30-0[Próximo Capítulo &#62;]