include::./index.adoc[]

[[v19-64-0]]
=== Salmos, 64
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-64-1]]

^<<v19-64-1,1>>^ Ouve, ó Deus, a minha voz nas minhas perplexidades; preserva-me a vida do terror do inimigo.

[[v19-64-2]]

^<<v19-64-2,2>>^ Esconde-me da conspiração dos malfeitores e do tumulto dos que praticam a iniquidade,

[[v19-64-3]]

^<<v19-64-3,3>>^ os quais afiam a língua como espada e apontam, quais flechas, palavras amargas,

[[v19-64-4]]

^<<v19-64-4,4>>^ para, às ocultas, atingirem o íntegro; contra ele disparam repentinamente e não temem.

[[v19-64-5]]

^<<v19-64-5,5>>^ Teimam no mau propósito; falam em secretamente armar ciladas; dizem: Quem nos verá?

[[v19-64-6]]

^<<v19-64-6,6>>^ Projetam iniquidade, inquirem tudo o que se pode excogitar; é um abismo o pensamento e o coração de cada um deles.

[[v19-64-7]]

^<<v19-64-7,7>>^ Mas Deus desfere contra eles uma seta; de súbito, se acharão feridos.

[[v19-64-8]]

^<<v19-64-8,8>>^ Dessarte, serão levados a tropeçar; a própria língua se voltará contra eles; todos os que os veem meneiam a cabeça.

[[v19-64-9]]

^<<v19-64-9,9>>^ E todos os homens temerão, e anunciarão as obras de Deus, e entenderão o que ele faz.

[[v19-64-10]]

^<<v19-64-10,10>>^ O justo se alegra no SENHOR e nele confia; os de reto coração, todos se gloriam.

'''

xref:019-salmos/019-salmos-063.adoc#v19-63-0[&#60; Capítulo Anterior] | <<v19-64-0,Topo>> | xref:019-salmos/019-salmos-065.adoc#v19-65-0[Próximo Capítulo &#62;]