include::./index.adoc[]

[[v19-92-0]]
=== Salmos, 92
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-92-1]]

^<<v19-92-1,1>>^ Bom é render graças ao Senhor e cantar louvores ao teu nome, ó Altíssimo,

[[v19-92-2]]

^<<v19-92-2,2>>^ anunciar de manhã a tua misericórdia e, durante as noites, a tua fidelidade,

[[v19-92-3]]

^<<v19-92-3,3>>^ com instrumentos de dez cordas, com saltério e com a solenidade da harpa.

[[v19-92-4]]

^<<v19-92-4,4>>^ Pois me alegraste, SENHOR, com os teus feitos; exultarei nas obras das tuas mãos.

[[v19-92-5]]

^<<v19-92-5,5>>^ Quão grandes, SENHOR, são as tuas obras! Os teus pensamentos, que profundos!

[[v19-92-6]]

^<<v19-92-6,6>>^ O inepto não compreende, e o estulto não percebe isto:

[[v19-92-7]]

^<<v19-92-7,7>>^ ainda que os ímpios brotam como a erva, e florescem todos os que praticam a iniquidade, nada obstante, serão destruídos para sempre;

[[v19-92-8]]

^<<v19-92-8,8>>^ tu, porém, SENHOR, és o Altíssimo eternamente.

[[v19-92-9]]

^<<v19-92-9,9>>^ Eis que os teus inimigos, SENHOR, eis que os teus inimigos perecerão; serão dispersos todos os que praticam a iniquidade.

[[v19-92-10]]

^<<v19-92-10,10>>^ Porém tu exaltas o meu poder como o do boi selvagem; derramas sobre mim o óleo fresco.

[[v19-92-11]]

^<<v19-92-11,11>>^ Os meus olhos veem com alegria os inimigos que me espreitam, e os meus ouvidos se satisfazem em ouvir dos malfeitores que contra mim se levantam.

[[v19-92-12]]

^<<v19-92-12,12>>^ O justo florescerá como a palmeira, crescerá como o cedro no Líbano.

[[v19-92-13]]

^<<v19-92-13,13>>^ Plantados na Casa do SENHOR, florescerão nos átrios do nosso Deus.

[[v19-92-14]]

^<<v19-92-14,14>>^ Na velhice darão ainda frutos, serão cheios de seiva e de verdor,

[[v19-92-15]]

^<<v19-92-15,15>>^ para anunciar que o SENHOR é reto. Ele é a minha rocha, e nele não há injustiça.

'''

xref:019-salmos/019-salmos-091.adoc#v19-91-0[&#60; Capítulo Anterior] | <<v19-92-0,Topo>> | xref:019-salmos/019-salmos-093.adoc#v19-93-0[Próximo Capítulo &#62;]