include::./index.adoc[]

[[v19-108-0]]
=== Salmos, 108
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-108-1]]

^<<v19-108-1,1>>^ Firme está o meu coração, ó Deus! Cantarei e entoarei louvores de toda a minha alma.

[[v19-108-2]]

^<<v19-108-2,2>>^ Despertai, saltério e harpa! Quero acordar a alva.

[[v19-108-3]]

^<<v19-108-3,3>>^ Render-te-ei graças entre os povos, ó SENHOR! Cantar-te-ei louvores entre as nações.

[[v19-108-4]]

^<<v19-108-4,4>>^ Porque acima dos céus se eleva a tua misericórdia, e a tua fidelidade, para além das nuvens.

[[v19-108-5]]

^<<v19-108-5,5>>^ Sê exaltado, ó Deus, acima dos céus; e em toda a terra esplenda a tua glória,

[[v19-108-6]]

^<<v19-108-6,6>>^ para que os teus amados sejam livres; salva com a tua destra e responde-nos.

[[v19-108-7]]

^<<v19-108-7,7>>^ Disse Deus na sua santidade: Exultarei; dividirei Siquém e medirei o vale de Sucote.

[[v19-108-8]]

^<<v19-108-8,8>>^ Meu é Gileade, meu é Manassés; Efraim é a defesa de minha cabeça; Judá é o meu cetro.

[[v19-108-9]]

^<<v19-108-9,9>>^ Moabe, porém, é a minha bacia de lavar; sobre Edom atirarei a minha sandália; sobre a Filístia jubilarei.

[[v19-108-10]]

^<<v19-108-10,10>>^ Quem me conduzirá à cidade fortificada? Quem me guiará até Edom?

[[v19-108-11]]

^<<v19-108-11,11>>^ Não nos rejeitaste, ó Deus? Tu não sais, ó Deus, com os nossos exércitos!

[[v19-108-12]]

^<<v19-108-12,12>>^ Presta-nos auxílio na angústia, pois vão é o socorro do homem.

[[v19-108-13]]

^<<v19-108-13,13>>^ Em Deus faremos proezas, porque ele mesmo calca aos pés os nossos adversários.

'''

xref:019-salmos/019-salmos-107.adoc#v19-107-0[&#60; Capítulo Anterior] | <<v19-108-0,Topo>> | xref:019-salmos/019-salmos-109.adoc#v19-109-0[Próximo Capítulo &#62;]