include::./index.adoc[]

[[v19-30-0]]
=== Salmos, 30
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-30-1]]

^<<v19-30-1,1>>^ Eu te exaltarei, ó SENHOR, porque tu me livraste e não permitiste que os meus inimigos se regozijassem contra mim.

[[v19-30-2]]

^<<v19-30-2,2>>^ SENHOR, meu Deus, clamei a ti por socorro, e tu me saraste.

[[v19-30-3]]

^<<v19-30-3,3>>^ SENHOR, da cova fizeste subir a minha alma; preservaste-me a vida para que não descesse à sepultura.

[[v19-30-4]]

^<<v19-30-4,4>>^ Salmodiai ao SENHOR, vós que sois seus santos, e dai graças ao seu santo nome.

[[v19-30-5]]

^<<v19-30-5,5>>^ Porque não passa de um momento a sua ira; o seu favor dura a vida inteira. Ao anoitecer, pode vir o choro, mas a alegria vem pela manhã.

[[v19-30-6]]

^<<v19-30-6,6>>^ Quanto a mim, dizia eu na minha prosperidade: jamais serei abalado.

[[v19-30-7]]

^<<v19-30-7,7>>^ Tu, SENHOR, por teu favor fizeste permanecer forte a minha montanha; apenas voltaste o rosto, fiquei logo conturbado.

[[v19-30-8]]

^<<v19-30-8,8>>^ Por ti, SENHOR, clamei, ao Senhor implorei.

[[v19-30-9]]

^<<v19-30-9,9>>^ Que proveito obterás no meu sangue, quando baixo à cova? Louvar-te-á, porventura, o pó? Declarará ele a tua verdade?

[[v19-30-10]]

^<<v19-30-10,10>>^ Ouve, SENHOR, e tem compaixão de mim; sê tu, SENHOR, o meu auxílio.

[[v19-30-11]]

^<<v19-30-11,11>>^ Converteste o meu pranto em folguedos; tiraste o meu pano de saco e me cingiste de alegria,

[[v19-30-12]]

^<<v19-30-12,12>>^ para que o meu espírito te cante louvores e não se cale. SENHOR, Deus meu, graças te darei para sempre.

'''

xref:019-salmos/019-salmos-029.adoc#v19-29-0[&#60; Capítulo Anterior] | <<v19-30-0,Topo>> | xref:019-salmos/019-salmos-031.adoc#v19-31-0[Próximo Capítulo &#62;]