include::./index.adoc[]

[[v19-85-0]]
=== Salmos, 85
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-85-1]]

^<<v19-85-1,1>>^ Favoreceste, SENHOR, a tua terra; restauraste a prosperidade de Jacó.

[[v19-85-2]]

^<<v19-85-2,2>>^ Perdoaste a iniquidade de teu povo, encobriste os seus pecados todos.

[[v19-85-3]]

^<<v19-85-3,3>>^ A tua indignação, reprimiste-a toda, do furor da tua ira te desviaste.

[[v19-85-4]]

^<<v19-85-4,4>>^ Restabelece-nos, ó Deus da nossa salvação, e retira de sobre nós a tua ira.

[[v19-85-5]]

^<<v19-85-5,5>>^ Estarás para sempre irado contra nós? Prolongarás a tua ira por todas as gerações?

[[v19-85-6]]

^<<v19-85-6,6>>^ Porventura, não tornarás a vivificar-nos, para que em ti se regozije o teu povo?

[[v19-85-7]]

^<<v19-85-7,7>>^ Mostra-nos, SENHOR, a tua misericórdia e concede-nos a tua salvação.

[[v19-85-8]]

^<<v19-85-8,8>>^ Escutarei o que Deus, o SENHOR, disser, pois falará de paz ao seu povo e aos seus santos; e que jamais caiam em insensatez.

[[v19-85-9]]

^<<v19-85-9,9>>^ Próxima está a sua salvação dos que o temem, para que a glória assista em nossa terra.

[[v19-85-10]]

^<<v19-85-10,10>>^ Encontraram-se a graça e a verdade, a justiça e a paz se beijaram.

[[v19-85-11]]

^<<v19-85-11,11>>^ Da terra brota a verdade, dos céus a justiça baixa o seu olhar.

[[v19-85-12]]

^<<v19-85-12,12>>^ Também o SENHOR dará o que é bom, e a nossa terra produzirá o seu fruto.

[[v19-85-13]]

^<<v19-85-13,13>>^ A justiça irá adiante dele, cujas pegadas ela transforma em caminhos.

'''

xref:019-salmos/019-salmos-084.adoc#v19-84-0[&#60; Capítulo Anterior] | <<v19-85-0,Topo>> | xref:019-salmos/019-salmos-086.adoc#v19-86-0[Próximo Capítulo &#62;]