include::./index.adoc[]

[[v19-9-0]]
=== Salmos, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-9-1]]

^<<v19-9-1,1>>^ Louvar-te-ei, SENHOR, de todo o meu coração; contarei todas as tuas maravilhas.

[[v19-9-2]]

^<<v19-9-2,2>>^ Alegrar-me-ei e exultarei em ti; ao teu nome, ó Altíssimo, eu cantarei louvores.

[[v19-9-3]]

^<<v19-9-3,3>>^ Pois, ao retrocederem os meus inimigos, tropeçam e somem-se da tua presença;

[[v19-9-4]]

^<<v19-9-4,4>>^ porque sustentas o meu direito e a minha causa; no trono te assentas e julgas retamente.

[[v19-9-5]]

^<<v19-9-5,5>>^ Repreendes as nações, destróis o ímpio e para todo o sempre lhes apagas o nome.

[[v19-9-6]]

^<<v19-9-6,6>>^ Quanto aos inimigos, estão consumados, suas ruínas são perpétuas, arrasaste as suas cidades; até a sua memória pereceu.

[[v19-9-7]]

^<<v19-9-7,7>>^ Mas o SENHOR permanece no seu trono eternamente, trono que erigiu para julgar.

[[v19-9-8]]

^<<v19-9-8,8>>^ Ele mesmo julga o mundo com justiça; administra os povos com retidão.

[[v19-9-9]]

^<<v19-9-9,9>>^ O SENHOR é também alto refúgio para o oprimido, refúgio nas horas de tribulação.

[[v19-9-10]]

^<<v19-9-10,10>>^ Em ti, pois, confiam os que conhecem o teu nome, porque tu, SENHOR, não desamparas os que te buscam.

[[v19-9-11]]

^<<v19-9-11,11>>^ Cantai louvores ao SENHOR, que habita em Sião; proclamai entre os povos os seus feitos.

[[v19-9-12]]

^<<v19-9-12,12>>^ Pois aquele que requer o sangue lembra-se deles e não se esquece do clamor dos aflitos.

[[v19-9-13]]

^<<v19-9-13,13>>^ Compadece-te de mim, SENHOR; vê a que sofrimentos me reduziram os que me odeiam, tu que me levantas das portas da morte;

[[v19-9-14]]

^<<v19-9-14,14>>^ para que, às portas da filha de Sião, eu proclame todos os teus louvores e me regozije da tua salvação.

[[v19-9-15]]

^<<v19-9-15,15>>^ Afundam-se as nações na cova que fizeram, no laço que esconderam, prendeu-se-lhes o pé.

[[v19-9-16]]

^<<v19-9-16,16>>^ Faz-se conhecido o SENHOR, pelo juízo que executa; enlaçado está o ímpio nas obras de suas próprias mãos.

[[v19-9-17]]

^<<v19-9-17,17>>^ Os perversos serão lançados no inferno, e todas as nações que se esquecem de Deus.

[[v19-9-18]]

^<<v19-9-18,18>>^ Pois o necessitado não será para sempre esquecido, e a esperança dos aflitos não se há de frustrar perpetuamente.

[[v19-9-19]]

^<<v19-9-19,19>>^ Levanta-te, SENHOR; não prevaleça o mortal. Sejam as nações julgadas na tua presença.

[[v19-9-20]]

^<<v19-9-20,20>>^ Infunde-lhes, SENHOR, o medo; saibam as nações que não passam de mortais.

'''

xref:019-salmos/019-salmos-008.adoc#v19-8-0[&#60; Capítulo Anterior] | <<v19-9-0,Topo>> | xref:019-salmos/019-salmos-010.adoc#v19-10-0[Próximo Capítulo &#62;]