include::./index.adoc[]

[[v19-109-0]]
=== Salmos, 109
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-109-1]]

^<<v19-109-1,1>>^ Ó Deus do meu louvor, não te cales!

[[v19-109-2]]

^<<v19-109-2,2>>^ Pois contra mim se desataram lábios maldosos e fraudulentos; com mentirosa língua falam contra mim.

[[v19-109-3]]

^<<v19-109-3,3>>^ Cercam-me com palavras odiosas e sem causa me fazem guerra.

[[v19-109-4]]

^<<v19-109-4,4>>^ Em paga do meu amor, me hostilizam; eu, porém, oro.

[[v19-109-5]]

^<<v19-109-5,5>>^ Pagaram-me o bem com o mal; o amor, com ódio.

[[v19-109-6]]

^<<v19-109-6,6>>^ Suscita contra ele um ímpio, e à sua direita esteja um acusador.

[[v19-109-7]]

^<<v19-109-7,7>>^ Quando o julgarem, seja condenado; e, tida como pecado, a sua oração.

[[v19-109-8]]

^<<v19-109-8,8>>^ Os seus dias sejam poucos, e tome outro o seu encargo.

[[v19-109-9]]

^<<v19-109-9,9>>^ Fiquem órfãos os seus filhos, e viúva, a sua esposa.

[[v19-109-10]]

^<<v19-109-10,10>>^ Andem errantes os seus filhos e mendiguem; e sejam expulsos das ruínas de suas casas.

[[v19-109-11]]

^<<v19-109-11,11>>^ De tudo o que tem, lance mão o usurário; do fruto do seu trabalho, esbulhem-no os estranhos.

[[v19-109-12]]

^<<v19-109-12,12>>^ Ninguém tenha misericórdia dele, nem haja quem se compadeça dos seus órfãos.

[[v19-109-13]]

^<<v19-109-13,13>>^ Desapareça a sua posteridade, e na seguinte geração se extinga o seu nome.

[[v19-109-14]]

^<<v19-109-14,14>>^ Na lembrança do SENHOR, viva a iniquidade de seus pais, e não se apague o pecado de sua mãe.

[[v19-109-15]]

^<<v19-109-15,15>>^ Permaneçam ante os olhos do SENHOR, para que faça desaparecer da terra a memória deles.

[[v19-109-16]]

^<<v19-109-16,16>>^ Porquanto não se lembrou de usar de misericórdia, mas perseguiu o aflito e o necessitado, como também o quebrantado de coração, para os entregar à morte.

[[v19-109-17]]

^<<v19-109-17,17>>^ Amou a maldição; ela o apanhe; não quis a bênção; aparte-se dele.

[[v19-109-18]]

^<<v19-109-18,18>>^ Vestiu-se de maldição como de uma túnica: penetre, como água, no seu interior e nos seus ossos, como azeite.

[[v19-109-19]]

^<<v19-109-19,19>>^ Seja-lhe como a roupa que o cobre e como o cinto com que sempre se cinge.

[[v19-109-20]]

^<<v19-109-20,20>>^ Tal seja, da parte do SENHOR, o galardão dos meus contrários e dos que falam mal contra a minha alma.

[[v19-109-21]]

^<<v19-109-21,21>>^ Mas tu, SENHOR Deus, age por mim, por amor do teu nome; livra-me, porque é grande a tua misericórdia.

[[v19-109-22]]

^<<v19-109-22,22>>^ Porque estou aflito e necessitado e, dentro de mim, sinto ferido o coração.

[[v19-109-23]]

^<<v19-109-23,23>>^ Vou passando, como a sombra que declina; sou atirado para longe, como um gafanhoto.

[[v19-109-24]]

^<<v19-109-24,24>>^ De tanto jejuar, os joelhos me vacilam, e de magreza vai mirrando a minha carne.

[[v19-109-25]]

^<<v19-109-25,25>>^ Tornei-me para eles objeto de opróbrio; quando me veem, meneiam a cabeça.

[[v19-109-26]]

^<<v19-109-26,26>>^ Socorre, SENHOR, Deus meu! Salva-me segundo a tua misericórdia.

[[v19-109-27]]

^<<v19-109-27,27>>^ Para que saibam vir isso das tuas mãos; que tu, SENHOR, o fizeste.

[[v19-109-28]]

^<<v19-109-28,28>>^ Amaldiçoem eles, mas tu, abençoa; sejam confundidos os que contra mim se levantam; alegre-se, porém, o teu servo.

[[v19-109-29]]

^<<v19-109-29,29>>^ Cubram-se de ignomínia os meus adversários, e a sua própria confusão os envolva como uma túnica.

[[v19-109-30]]

^<<v19-109-30,30>>^ Muitas graças darei ao SENHOR com os meus lábios; louvá-lo-ei no meio da multidão;

[[v19-109-31]]

^<<v19-109-31,31>>^ porque ele se põe à direita do pobre, para o livrar dos que lhe julgam a alma.

'''

xref:019-salmos/019-salmos-108.adoc#v19-108-0[&#60; Capítulo Anterior] | <<v19-109-0,Topo>> | xref:019-salmos/019-salmos-110.adoc#v19-110-0[Próximo Capítulo &#62;]