include::./index.adoc[]

[[v19-26-0]]
=== Salmos, 26
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-26-1]]

^<<v19-26-1,1>>^ Faze-me justiça, SENHOR, pois tenho andado na minha integridade e confio no SENHOR, sem vacilar.

[[v19-26-2]]

^<<v19-26-2,2>>^ Examina-me, SENHOR, e prova-me; sonda-me o coração e os pensamentos.

[[v19-26-3]]

^<<v19-26-3,3>>^ Pois a tua benignidade, tenho-a perante os olhos e tenho andado na tua verdade.

[[v19-26-4]]

^<<v19-26-4,4>>^ Não me tenho assentado com homens falsos e com os dissimuladores não me associo.

[[v19-26-5]]

^<<v19-26-5,5>>^ Aborreço a súcia de malfeitores e com os ímpios não me assento.

[[v19-26-6]]

^<<v19-26-6,6>>^ Lavo as mãos na inocência e, assim, andarei, SENHOR, ao redor do teu altar,

[[v19-26-7]]

^<<v19-26-7,7>>^ para entoar, com voz alta, os louvores e proclamar as tuas maravilhas todas.

[[v19-26-8]]

^<<v19-26-8,8>>^ Eu amo, SENHOR, a habitação de tua casa e o lugar onde tua glória assiste.

[[v19-26-9]]

^<<v19-26-9,9>>^ Não colhas a minha alma com a dos pecadores, nem a minha vida com a dos homens sanguinários,

[[v19-26-10]]

^<<v19-26-10,10>>^ em cujas mãos há crimes e cuja destra está cheia de subornos.

[[v19-26-11]]

^<<v19-26-11,11>>^ Quanto a mim, porém, ando na minha integridade; livra-me e tem compaixão de mim.

[[v19-26-12]]

^<<v19-26-12,12>>^ O meu pé está firme em terreno plano; nas congregações, bendirei o SENHOR.

'''

xref:019-salmos/019-salmos-025.adoc#v19-25-0[&#60; Capítulo Anterior] | <<v19-26-0,Topo>> | xref:019-salmos/019-salmos-027.adoc#v19-27-0[Próximo Capítulo &#62;]