include::./index.adoc[]

[[v19-144-0]]
=== Salmos, 144
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-144-1]]

^<<v19-144-1,1>>^ Bendito seja o SENHOR, rocha minha, que me adestra as mãos para a batalha e os dedos, para a guerra;

[[v19-144-2]]

^<<v19-144-2,2>>^ minha misericórdia e fortaleza minha, meu alto refúgio e meu libertador, meu escudo, aquele em quem confio e quem me submete o meu povo.

[[v19-144-3]]

^<<v19-144-3,3>>^ SENHOR, que é o homem para que dele tomes conhecimento? E o filho do homem, para que o estimes?

[[v19-144-4]]

^<<v19-144-4,4>>^ O homem é como um sopro; os seus dias, como a sombra que passa.

[[v19-144-5]]

^<<v19-144-5,5>>^ Abaixa, SENHOR, os teus céus e desce; toca os montes, e fumegarão.

[[v19-144-6]]

^<<v19-144-6,6>>^ Despede relâmpagos e dispersa os meus inimigos; arremessa as tuas flechas e desbarata-os.

[[v19-144-7]]

^<<v19-144-7,7>>^ Estende a mão lá do alto; livra-me e arrebata-me das muitas águas e do poder de estranhos,

[[v19-144-8]]

^<<v19-144-8,8>>^ cuja boca profere mentiras, e cuja direita é direita de falsidade.

[[v19-144-9]]

^<<v19-144-9,9>>^ A ti, ó Deus, entoarei novo cântico; no saltério de dez cordas, te cantarei louvores.

[[v19-144-10]]

^<<v19-144-10,10>>^ É ele quem dá aos reis a vitória; quem livra da espada maligna a Davi, seu servo.

[[v19-144-11]]

^<<v19-144-11,11>>^ Livra-me e salva-me do poder de estranhos, cuja boca profere mentiras, e cuja direita é direita de falsidade.

[[v19-144-12]]

^<<v19-144-12,12>>^ Que nossos filhos sejam, na sua mocidade, como plantas viçosas, e nossas filhas, como pedras angulares, lavradas como colunas de palácio;

[[v19-144-13]]

^<<v19-144-13,13>>^ que transbordem os nossos celeiros, atulhados de toda sorte de provisões; que os nossos rebanhos produzam a milhares e a dezenas de milhares, em nossos campos;

[[v19-144-14]]

^<<v19-144-14,14>>^ que as nossas vacas andem pejadas, não lhes haja rotura, nem mau sucesso. Não haja gritos de lamento em nossas praças.

[[v19-144-15]]

^<<v19-144-15,15>>^ Bem-aventurado o povo a quem assim sucede! Sim, bem-aventurado é o povo cujo Deus é o SENHOR!

'''

xref:019-salmos/019-salmos-143.adoc#v19-143-0[&#60; Capítulo Anterior] | <<v19-144-0,Topo>> | xref:019-salmos/019-salmos-145.adoc#v19-145-0[Próximo Capítulo &#62;]