include::./index.adoc[]

[[v19-145-0]]
=== Salmos, 145
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-145-1]]

^<<v19-145-1,1>>^ Exaltar-te-ei, ó Deus meu e Rei; bendirei o teu nome para todo o sempre.

[[v19-145-2]]

^<<v19-145-2,2>>^ Todos os dias te bendirei e louvarei o teu nome para todo o sempre.

[[v19-145-3]]

^<<v19-145-3,3>>^ Grande é o SENHOR e mui digno de ser louvado; a sua grandeza é insondável.

[[v19-145-4]]

^<<v19-145-4,4>>^ Uma geração louvará a outra geração as tuas obras e anunciará os teus poderosos feitos.

[[v19-145-5]]

^<<v19-145-5,5>>^ Meditarei no glorioso esplendor da tua majestade e nas tuas maravilhas.

[[v19-145-6]]

^<<v19-145-6,6>>^ Falar-se-á do poder dos teus feitos tremendos, e contarei a tua grandeza.

[[v19-145-7]]

^<<v19-145-7,7>>^ Divulgarão a memória de tua muita bondade e com júbilo celebrarão a tua justiça.

[[v19-145-8]]

^<<v19-145-8,8>>^ Benigno e misericordioso é o SENHOR, tardio em irar-se e de grande clemência.

[[v19-145-9]]

^<<v19-145-9,9>>^ O SENHOR é bom para todos, e as suas ternas misericórdias permeiam todas as suas obras.

[[v19-145-10]]

^<<v19-145-10,10>>^ Todas as tuas obras te renderão graças, SENHOR; e os teus santos te bendirão.

[[v19-145-11]]

^<<v19-145-11,11>>^ Falarão da glória do teu reino e confessarão o teu poder,

[[v19-145-12]]

^<<v19-145-12,12>>^ para que aos filhos dos homens se façam notórios os teus poderosos feitos e a glória da majestade do teu reino.

[[v19-145-13]]

^<<v19-145-13,13>>^ O teu reino é o de todos os séculos, e o teu domínio subsiste por todas as gerações. O SENHOR é fiel em todas as suas palavras e santo em todas as suas obras.

[[v19-145-14]]

^<<v19-145-14,14>>^ O SENHOR sustém os que vacilam e apruma todos os prostrados.

[[v19-145-15]]

^<<v19-145-15,15>>^ Em ti esperam os olhos de todos, e tu, a seu tempo, lhes dás o alimento.

[[v19-145-16]]

^<<v19-145-16,16>>^ Abres a mão e satisfazes de benevolência a todo vivente.

[[v19-145-17]]

^<<v19-145-17,17>>^ Justo é o SENHOR em todos os seus caminhos, benigno em todas as suas obras.

[[v19-145-18]]

^<<v19-145-18,18>>^ Perto está o SENHOR de todos os que o invocam, de todos os que o invocam em verdade.

[[v19-145-19]]

^<<v19-145-19,19>>^ Ele acode à vontade dos que o temem; atende-lhes o clamor e os salva.

[[v19-145-20]]

^<<v19-145-20,20>>^ O SENHOR guarda a todos os que o amam; porém os ímpios serão exterminados.

[[v19-145-21]]

^<<v19-145-21,21>>^ Profira a minha boca louvores ao SENHOR, e toda carne louve o seu santo nome, para todo o sempre.

'''

xref:019-salmos/019-salmos-144.adoc#v19-144-0[&#60; Capítulo Anterior] | <<v19-145-0,Topo>> | xref:019-salmos/019-salmos-146.adoc#v19-146-0[Próximo Capítulo &#62;]