include::./index.adoc[]

[[v19-50-0]]
=== Salmos, 50
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-50-1]]

^<<v19-50-1,1>>^ Fala o Poderoso, o SENHOR Deus, e chama a terra desde o Levante até ao Poente.

[[v19-50-2]]

^<<v19-50-2,2>>^ Desde Sião, excelência de formosura, resplandece Deus.

[[v19-50-3]]

^<<v19-50-3,3>>^ Vem o nosso Deus e não guarda silêncio; perante ele arde um fogo devorador, ao seu redor esbraveja grande tormenta.

[[v19-50-4]]

^<<v19-50-4,4>>^ Intima os céus lá em cima e a terra, para julgar o seu povo.

[[v19-50-5]]

^<<v19-50-5,5>>^ Congregai os meus santos, os que comigo fizeram aliança por meio de sacrifícios.

[[v19-50-6]]

^<<v19-50-6,6>>^ Os céus anunciam a sua justiça, porque é o próprio Deus que julga.

[[v19-50-7]]

^<<v19-50-7,7>>^ Escuta, povo meu, e eu falarei; ó Israel, e eu testemunharei contra ti. Eu sou Deus, o teu Deus.

[[v19-50-8]]

^<<v19-50-8,8>>^ Não te repreendo pelos teus sacrifícios, nem pelos teus holocaustos continuamente perante mim.

[[v19-50-9]]

^<<v19-50-9,9>>^ De tua casa não aceitarei novilhos, nem bodes, dos teus apriscos.

[[v19-50-10]]

^<<v19-50-10,10>>^ Pois são meus todos os animais do bosque e as alimárias aos milhares sobre as montanhas.

[[v19-50-11]]

^<<v19-50-11,11>>^ Conheço todas as aves dos montes, e são meus todos os animais que pululam no campo.

[[v19-50-12]]

^<<v19-50-12,12>>^ Se eu tivesse fome, não to diria, pois o mundo é meu e quanto nele se contém.

[[v19-50-13]]

^<<v19-50-13,13>>^ Acaso, como eu carne de touros? Ou bebo sangue de cabritos?

[[v19-50-14]]

^<<v19-50-14,14>>^ Oferece a Deus sacrifício de ações de graças e cumpre os teus votos para com o Altíssimo;

[[v19-50-15]]

^<<v19-50-15,15>>^ invoca-me no dia da angústia; eu te livrarei, e tu me glorificarás.

[[v19-50-16]]

^<<v19-50-16,16>>^ Mas ao ímpio diz Deus: De que te serve repetires os meus preceitos e teres nos lábios a minha aliança,

[[v19-50-17]]

^<<v19-50-17,17>>^ uma vez que aborreces a disciplina e rejeitas as minhas palavras?

[[v19-50-18]]

^<<v19-50-18,18>>^ Se vês um ladrão, tu te comprazes nele e aos adúlteros te associas.

[[v19-50-19]]

^<<v19-50-19,19>>^ Soltas a boca para o mal, e a tua língua trama enganos.

[[v19-50-20]]

^<<v19-50-20,20>>^ Sentas-te para falar contra teu irmão e difamas o filho de tua mãe.

[[v19-50-21]]

^<<v19-50-21,21>>^ Tens feito estas coisas, e eu me calei; pensavas que eu era teu igual; mas eu te arguirei e porei tudo à tua vista.

[[v19-50-22]]

^<<v19-50-22,22>>^ Considerai, pois, nisto, vós que vos esqueceis de Deus, para que não vos despedace, sem haver quem vos livre.

[[v19-50-23]]

^<<v19-50-23,23>>^ O que me oferece sacrifício de ações de graças, esse me glorificará; e ao que prepara o seu caminho, dar-lhe-ei que veja a salvação de Deus.

'''

xref:019-salmos/019-salmos-049.adoc#v19-49-0[&#60; Capítulo Anterior] | <<v19-50-0,Topo>> | xref:019-salmos/019-salmos-051.adoc#v19-51-0[Próximo Capítulo &#62;]