include::./index.adoc[]

[[v19-76-0]]
=== Salmos, 76
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-76-1]]

^<<v19-76-1,1>>^ Conhecido é Deus em Judá; grande, o seu nome em Israel.

[[v19-76-2]]

^<<v19-76-2,2>>^ Em Salém, está o seu tabernáculo, e, em Sião, a sua morada.

[[v19-76-3]]

^<<v19-76-3,3>>^ Ali, despedaçou ele os relâmpagos do arco, o escudo, a espada e a batalha.

[[v19-76-4]]

^<<v19-76-4,4>>^ Tu és ilustre e mais glorioso do que os montes eternos.

[[v19-76-5]]

^<<v19-76-5,5>>^ Despojados foram os de ânimo forte; jazem a dormir o seu sono, e nenhum dos valentes pode valer-se das próprias mãos.

[[v19-76-6]]

^<<v19-76-6,6>>^ Ante a tua repreensão, ó Deus de Jacó, paralisaram carros e cavalos.

[[v19-76-7]]

^<<v19-76-7,7>>^ Tu, sim, tu és terrível; se te iras, quem pode subsistir à tua vista?

[[v19-76-8]]

^<<v19-76-8,8>>^ Desde os céus fizeste ouvir o teu juízo; tremeu a terra e se aquietou,

[[v19-76-9]]

^<<v19-76-9,9>>^ ao levantar-se Deus para julgar e salvar todos os humildes da terra.

[[v19-76-10]]

^<<v19-76-10,10>>^ Pois até a ira humana há de louvar-te; e do resíduo das iras te cinges.

[[v19-76-11]]

^<<v19-76-11,11>>^ Fazei votos e pagai-os ao SENHOR, vosso Deus; tragam presentes todos os que o rodeiam, àquele que deve ser temido.

[[v19-76-12]]

^<<v19-76-12,12>>^ Ele quebranta o orgulho dos príncipes; é tremendo aos reis da terra.

'''

xref:019-salmos/019-salmos-075.adoc#v19-75-0[&#60; Capítulo Anterior] | <<v19-76-0,Topo>> | xref:019-salmos/019-salmos-077.adoc#v19-77-0[Próximo Capítulo &#62;]