include::./index.adoc[]

[[v19-72-0]]
=== Salmos, 72
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-72-1]]

^<<v19-72-1,1>>^ Concede ao rei, ó Deus, os teus juízos e a tua justiça, ao filho do rei.

[[v19-72-2]]

^<<v19-72-2,2>>^ Julgue ele com justiça o teu povo e os teus aflitos, com equidade.

[[v19-72-3]]

^<<v19-72-3,3>>^ Os montes trarão paz ao povo, também as colinas a trarão, com justiça.

[[v19-72-4]]

^<<v19-72-4,4>>^ Julgue ele os aflitos do povo, salve os filhos dos necessitados e esmague ao opressor.

[[v19-72-5]]

^<<v19-72-5,5>>^ Ele permanecerá enquanto existir o sol e enquanto durar a lua, através das gerações.

[[v19-72-6]]

^<<v19-72-6,6>>^ Seja ele como chuva que desce sobre a campina ceifada, como aguaceiros que regam a terra.

[[v19-72-7]]

^<<v19-72-7,7>>^ Floresça em seus dias o justo, e haja abundância de paz até que cesse de haver lua.

[[v19-72-8]]

^<<v19-72-8,8>>^ Domine ele de mar a mar e desde o rio até aos confins da terra.

[[v19-72-9]]

^<<v19-72-9,9>>^ Curvem-se diante dele os habitantes do deserto, e os seus inimigos lambam o pó.

[[v19-72-10]]

^<<v19-72-10,10>>^ Paguem-lhe tributos os reis de Társis e das ilhas; os reis de Sabá e de Sebá lhe ofereçam presentes.

[[v19-72-11]]

^<<v19-72-11,11>>^ E todos os reis se prostrem perante ele; todas as nações o sirvam.

[[v19-72-12]]

^<<v19-72-12,12>>^ Porque ele acode ao necessitado que clama e também ao aflito e ao desvalido.

[[v19-72-13]]

^<<v19-72-13,13>>^ Ele tem piedade do fraco e do necessitado e salva a alma aos indigentes.

[[v19-72-14]]

^<<v19-72-14,14>>^ Redime a sua alma da opressão e da violência, e precioso lhe é o sangue deles.

[[v19-72-15]]

^<<v19-72-15,15>>^ Viverá, e se lhe dará do ouro de Sabá; e continuamente se fará por ele oração, e o bendirão todos os dias.

[[v19-72-16]]

^<<v19-72-16,16>>^ Haja na terra abundância de cereais, que ondulem até aos cimos dos montes; seja a sua messe como o Líbano, e das cidades floresçam os habitantes como a erva da terra.

[[v19-72-17]]

^<<v19-72-17,17>>^ Subsista para sempre o seu nome e prospere enquanto resplandecer o sol; nele sejam abençoados todos os homens, e as nações lhe chamem bem-aventurado.

[[v19-72-18]]

^<<v19-72-18,18>>^ Bendito seja o SENHOR Deus, o Deus de Israel, que só ele opera prodígios.

[[v19-72-19]]

^<<v19-72-19,19>>^ Bendito para sempre o seu glorioso nome, e da sua glória se encha toda a terra. Amém e amém!

[[v19-72-20]]

^<<v19-72-20,20>>^ Findam as orações de Davi, filho de Jessé.

'''

xref:019-salmos/019-salmos-071.adoc#v19-71-0[&#60; Capítulo Anterior] | <<v19-72-0,Topo>> | xref:019-salmos/019-salmos-073.adoc#v19-73-0[Próximo Capítulo &#62;]