include::./index.adoc[]

[[v19-10-0]]
=== Salmos, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-10-1]]

^<<v19-10-1,1>>^ Por que, SENHOR, te conservas longe? E te escondes nas horas de tribulação?

[[v19-10-2]]

^<<v19-10-2,2>>^ Com arrogância, os ímpios perseguem o pobre; sejam presas das tramas que urdiram.

[[v19-10-3]]

^<<v19-10-3,3>>^ Pois o perverso se gloria da cobiça de sua alma, o avarento maldiz o SENHOR e blasfema contra ele.

[[v19-10-4]]

^<<v19-10-4,4>>^ O perverso, na sua soberba, não investiga; que não há Deus são todas as suas cogitações.

[[v19-10-5]]

^<<v19-10-5,5>>^ São prósperos os seus caminhos em todo tempo; muito acima e longe dele estão os teus juízos; quanto aos seus adversários, ele a todos ridiculiza.

[[v19-10-6]]

^<<v19-10-6,6>>^ Pois diz lá no seu íntimo: Jamais serei abalado; de geração em geração, nenhum mal me sobrevirá.

[[v19-10-7]]

^<<v19-10-7,7>>^ A boca, ele a tem cheia de maldição, enganos e opressão; debaixo da língua, insulto e iniquidade.

[[v19-10-8]]

^<<v19-10-8,8>>^ Põe-se de tocaia nas vilas, trucida os inocentes nos lugares ocultos; seus olhos espreitam o desamparado.

[[v19-10-9]]

^<<v19-10-9,9>>^ Está ele de emboscada, como o leão na sua caverna; está de emboscada para enlaçar o pobre: apanha-o e, na sua rede, o enleia.

[[v19-10-10]]

^<<v19-10-10,10>>^ Abaixa-se, rasteja; em seu poder, lhe caem os necessitados.

[[v19-10-11]]

^<<v19-10-11,11>>^ Diz ele, no seu íntimo: Deus se esqueceu, virou o rosto e não verá isto nunca.

[[v19-10-12]]

^<<v19-10-12,12>>^ Levanta-te, SENHOR! Ó Deus, ergue a mão! Não te esqueças dos pobres.

[[v19-10-13]]

^<<v19-10-13,13>>^ Por que razão despreza o ímpio a Deus, dizendo no seu íntimo que Deus não se importa?

[[v19-10-14]]

^<<v19-10-14,14>>^ Tu, porém, o tens visto, porque atentas aos trabalhos e à dor, para que os possas tomar em tuas mãos. A ti se entrega o desamparado; tu tens sido o defensor do órfão.

[[v19-10-15]]

^<<v19-10-15,15>>^ Quebranta o braço do perverso e do malvado; esquadrinha-lhes a maldade, até nada mais achares.

[[v19-10-16]]

^<<v19-10-16,16>>^ O SENHOR é rei eterno: da sua terra somem-se as nações.

[[v19-10-17]]

^<<v19-10-17,17>>^ Tens ouvido, SENHOR, o desejo dos humildes; tu lhes fortalecerás o coração e lhes acudirás,

[[v19-10-18]]

^<<v19-10-18,18>>^ para fazeres justiça ao órfão e ao oprimido, a fim de que o homem, que é da terra, já não infunda terror.

'''

xref:019-salmos/019-salmos-009.adoc#v19-9-0[&#60; Capítulo Anterior] | <<v19-10-0,Topo>> | xref:019-salmos/019-salmos-011.adoc#v19-11-0[Próximo Capítulo &#62;]