include::./index.adoc[]

[[v19-69-0]]
=== Salmos, 69
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-69-1]]

^<<v19-69-1,1>>^ Salva-me, ó Deus, porque as águas me sobem até à alma.

[[v19-69-2]]

^<<v19-69-2,2>>^ Estou atolado em profundo lamaçal, que não dá pé; estou nas profundezas das águas, e a corrente me submerge.

[[v19-69-3]]

^<<v19-69-3,3>>^ Estou cansado de clamar, secou-se-me a garganta; os meus olhos desfalecem de tanto esperar por meu Deus.

[[v19-69-4]]

^<<v19-69-4,4>>^ São mais que os cabelos de minha cabeça os que, sem razão, me odeiam; são poderosos os meus destruidores, os que com falsos motivos são meus inimigos; por isso, tenho de restituir o que não furtei.

[[v19-69-5]]

^<<v19-69-5,5>>^ Tu, ó Deus, bem conheces a minha estultice, e as minhas culpas não te são ocultas.

[[v19-69-6]]

^<<v19-69-6,6>>^ Não sejam envergonhados por minha causa os que esperam em ti, ó SENHOR, Deus dos Exércitos; nem por minha causa sofram vexame os que te buscam, ó Deus de Israel.

[[v19-69-7]]

^<<v19-69-7,7>>^ Pois tenho suportado afrontas por amor de ti, e o rosto se me encobre de vexame.

[[v19-69-8]]

^<<v19-69-8,8>>^ Tornei-me estranho a meus irmãos e desconhecido aos filhos de minha mãe.

[[v19-69-9]]

^<<v19-69-9,9>>^ Pois o zelo da tua casa me consumiu, e as injúrias dos que te ultrajam caem sobre mim.

[[v19-69-10]]

^<<v19-69-10,10>>^ Chorei, em jejum está a minha alma, e isso mesmo se me tornou em afrontas.

[[v19-69-11]]

^<<v19-69-11,11>>^ Pus um pano de saco por veste e me tornei objeto de escárnio para eles.

[[v19-69-12]]

^<<v19-69-12,12>>^ Tagarelam sobre mim os que à porta se assentam, e sou motivo para cantigas de beberrões.

[[v19-69-13]]

^<<v19-69-13,13>>^ Quanto a mim, porém, SENHOR, faço a ti, em tempo favorável, a minha oração. Responde-me, ó Deus, pela riqueza da tua graça; pela tua fidelidade em socorrer,

[[v19-69-14]]

^<<v19-69-14,14>>^ livra-me do tremedal, para que não me afunde; seja eu salvo dos que me odeiam e das profundezas das águas.

[[v19-69-15]]

^<<v19-69-15,15>>^ Não me arraste a corrente das águas, nem me trague a voragem, nem se feche sobre mim a boca do poço.

[[v19-69-16]]

^<<v19-69-16,16>>^ Responde-me, SENHOR, pois compassiva é a tua graça; volta-te para mim segundo a riqueza das tuas misericórdias.

[[v19-69-17]]

^<<v19-69-17,17>>^ Não escondas o rosto ao teu servo, pois estou atribulado; responde-me depressa.

[[v19-69-18]]

^<<v19-69-18,18>>^ Aproxima-te de minha alma e redime-a; resgata-me por causa dos meus inimigos.

[[v19-69-19]]

^<<v19-69-19,19>>^ Tu conheces a minha afronta, a minha vergonha e o meu vexame; todos os meus adversários estão à tua vista.

[[v19-69-20]]

^<<v19-69-20,20>>^ O opróbrio partiu-me o coração, e desfaleci; esperei por piedade, mas debalde; por consoladores, e não os achei.

[[v19-69-21]]

^<<v19-69-21,21>>^ Por alimento me deram fel e na minha sede me deram a beber vinagre.

[[v19-69-22]]

^<<v19-69-22,22>>^ Sua mesa torne-se-lhes diante deles em laço, e a prosperidade, em armadilha.

[[v19-69-23]]

^<<v19-69-23,23>>^ Obscureçam-se-lhes os olhos, para que não vejam; e faze que sempre lhes vacile o dorso.

[[v19-69-24]]

^<<v19-69-24,24>>^ Derrama sobre eles a tua indignação, e que o ardor da tua ira os alcance.

[[v19-69-25]]

^<<v19-69-25,25>>^ Fique deserta a sua morada, e não haja quem habite as suas tendas.

[[v19-69-26]]

^<<v19-69-26,26>>^ Pois perseguem a quem tu feriste e acrescentam dores àquele a quem golpeaste.

[[v19-69-27]]

^<<v19-69-27,27>>^ Soma-lhes iniquidade à iniquidade, e não gozem da tua absolvição.

[[v19-69-28]]

^<<v19-69-28,28>>^ Sejam riscados do Livro dos Vivos e não tenham registro com os justos.

[[v19-69-29]]

^<<v19-69-29,29>>^ Quanto a mim, porém, amargurado e aflito, ponha-me o teu socorro, ó Deus, em alto refúgio.

[[v19-69-30]]

^<<v19-69-30,30>>^ Louvarei com cânticos o nome de Deus, exaltá-lo-ei com ações de graças.

[[v19-69-31]]

^<<v19-69-31,31>>^ Será isso muito mais agradável ao Senhor do que um boi ou um novilho com chifres e unhas.

[[v19-69-32]]

^<<v19-69-32,32>>^ Vejam isso os aflitos e se alegrem; quanto a vós outros que buscais a Deus, que o vosso coração reviva.

[[v19-69-33]]

^<<v19-69-33,33>>^ Porque o SENHOR responde aos necessitados e não despreza os seus prisioneiros.

[[v19-69-34]]

^<<v19-69-34,34>>^ Louvem-no os céus e a terra, os mares e tudo quanto neles se move.

[[v19-69-35]]

^<<v19-69-35,35>>^ Porque Deus salvará Sião e edificará as cidades de Judá, e ali habitarão e hão de possuí-la.

[[v19-69-36]]

^<<v19-69-36,36>>^ Também a descendência dos seus servos a herdará, e os que lhe amam o nome nela habitarão.

'''

xref:019-salmos/019-salmos-068.adoc#v19-68-0[&#60; Capítulo Anterior] | <<v19-69-0,Topo>> | xref:019-salmos/019-salmos-070.adoc#v19-70-0[Próximo Capítulo &#62;]