include::./index.adoc[]

[[v19-12-0]]
=== Salmos, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-12-1]]

^<<v19-12-1,1>>^ Socorro, SENHOR! Porque já não há homens piedosos; desaparecem os fiéis entre os filhos dos homens.

[[v19-12-2]]

^<<v19-12-2,2>>^ Falam com falsidade uns aos outros, falam com lábios bajuladores e coração fingido.

[[v19-12-3]]

^<<v19-12-3,3>>^ Corte o SENHOR todos os lábios bajuladores, a língua que fala soberbamente,

[[v19-12-4]]

^<<v19-12-4,4>>^ pois dizem: Com a língua prevaleceremos, os lábios são nossos; quem é senhor sobre nós?

[[v19-12-5]]

^<<v19-12-5,5>>^ Por causa da opressão dos pobres e do gemido dos necessitados, eu me levantarei agora, diz o SENHOR; e porei a salvo a quem por isso suspira.

[[v19-12-6]]

^<<v19-12-6,6>>^ As palavras do SENHOR são palavras puras, prata refinada em cadinho de barro, depurada sete vezes.

[[v19-12-7]]

^<<v19-12-7,7>>^ Sim, SENHOR, tu nos guardarás; desta geração nos livrarás para sempre.

[[v19-12-8]]

^<<v19-12-8,8>>^ Por todos os lugares andam os perversos, quando entre os filhos dos homens a vileza é exaltada.

'''

xref:019-salmos/019-salmos-011.adoc#v19-11-0[&#60; Capítulo Anterior] | <<v19-12-0,Topo>> | xref:019-salmos/019-salmos-013.adoc#v19-13-0[Próximo Capítulo &#62;]