include::./index.adoc[]

[[v19-119-0]]
=== Salmos, 119
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-119-1]]

^<<v19-119-1,1>>^ Bem-aventurados os irrepreensíveis no seu caminho, que andam na lei do SENHOR.

[[v19-119-2]]

^<<v19-119-2,2>>^ Bem-aventurados os que guardam as suas prescrições e o buscam de todo o coração;

[[v19-119-3]]

^<<v19-119-3,3>>^ não praticam iniquidade e andam nos seus caminhos.

[[v19-119-4]]

^<<v19-119-4,4>>^ Tu ordenaste os teus mandamentos, para que os cumpramos à risca.

[[v19-119-5]]

^<<v19-119-5,5>>^ Tomara sejam firmes os meus passos, para que eu observe os teus preceitos.

[[v19-119-6]]

^<<v19-119-6,6>>^ Então, não terei de que me envergonhar, quando considerar em todos os teus mandamentos.

[[v19-119-7]]

^<<v19-119-7,7>>^ Render-te-ei graças com integridade de coração, quando tiver aprendido os teus retos juízos.

[[v19-119-8]]

^<<v19-119-8,8>>^ Cumprirei os teus decretos; não me desampares jamais.

[[v19-119-9]]

^<<v19-119-9,9>>^ De que maneira poderá o jovem guardar puro o seu caminho? Observando-o segundo a tua palavra.

[[v19-119-10]]

^<<v19-119-10,10>>^ De todo o coração te busquei; não me deixes fugir aos teus mandamentos.

[[v19-119-11]]

^<<v19-119-11,11>>^ Guardo no coração as tuas palavras, para não pecar contra ti.

[[v19-119-12]]

^<<v19-119-12,12>>^ Bendito és tu, SENHOR; ensina-me os teus preceitos.

[[v19-119-13]]

^<<v19-119-13,13>>^ Com os lábios tenho narrado todos os juízos da tua boca.

[[v19-119-14]]

^<<v19-119-14,14>>^ Mais me regozijo com o caminho dos teus testemunhos do que com todas as riquezas.

[[v19-119-15]]

^<<v19-119-15,15>>^ Meditarei nos teus preceitos e às tuas veredas terei respeito.

[[v19-119-16]]

^<<v19-119-16,16>>^ Terei prazer nos teus decretos; não me esquecerei da tua palavra.

[[v19-119-17]]

^<<v19-119-17,17>>^ Sê generoso para com o teu servo, para que eu viva e observe a tua palavra.

[[v19-119-18]]

^<<v19-119-18,18>>^ Desvenda os meus olhos, para que eu contemple as maravilhas da tua lei.

[[v19-119-19]]

^<<v19-119-19,19>>^ Sou peregrino na terra; não escondas de mim os teus mandamentos.

[[v19-119-20]]

^<<v19-119-20,20>>^ Consumida está a minha alma por desejar, incessantemente, os teus juízos.

[[v19-119-21]]

^<<v19-119-21,21>>^ Increpaste os soberbos, os malditos, que se desviam dos teus mandamentos.

[[v19-119-22]]

^<<v19-119-22,22>>^ Tira de sobre mim o opróbrio e o desprezo, pois tenho guardado os teus testemunhos.

[[v19-119-23]]

^<<v19-119-23,23>>^ Assentaram-se príncipes e falaram contra mim, mas o teu servo considerou nos teus decretos.

[[v19-119-24]]

^<<v19-119-24,24>>^ Com efeito, os teus testemunhos são o meu prazer, são os meus conselheiros.

[[v19-119-25]]

^<<v19-119-25,25>>^ A minha alma está apegada ao pó; vivifica-me segundo a tua palavra.

[[v19-119-26]]

^<<v19-119-26,26>>^ Eu te expus os meus caminhos, e tu me valeste; ensina-me os teus decretos.

[[v19-119-27]]

^<<v19-119-27,27>>^ Faze-me atinar com o caminho dos teus preceitos, e meditarei nas tuas maravilhas.

[[v19-119-28]]

^<<v19-119-28,28>>^ A minha alma, de tristeza, verte lágrimas; fortalece-me segundo a tua palavra.

[[v19-119-29]]

^<<v19-119-29,29>>^ Afasta de mim o caminho da falsidade e favorece-me com a tua lei.

[[v19-119-30]]

^<<v19-119-30,30>>^ Escolhi o caminho da fidelidade e decidi-me pelos teus juízos.

[[v19-119-31]]

^<<v19-119-31,31>>^ Aos teus testemunhos me apego; não permitas, SENHOR, seja eu envergonhado.

[[v19-119-32]]

^<<v19-119-32,32>>^ Percorrerei o caminho dos teus mandamentos, quando me alegrares o coração.

[[v19-119-33]]

^<<v19-119-33,33>>^ Ensina-me, SENHOR, o caminho dos teus decretos, e os seguirei até ao fim.

[[v19-119-34]]

^<<v19-119-34,34>>^ Dá-me entendimento, e guardarei a tua lei; de todo o coração a cumprirei.

[[v19-119-35]]

^<<v19-119-35,35>>^ Guia-me pela vereda dos teus mandamentos, pois nela me comprazo.

[[v19-119-36]]

^<<v19-119-36,36>>^ Inclina-me o coração aos teus testemunhos e não à cobiça.

[[v19-119-37]]

^<<v19-119-37,37>>^ Desvia os meus olhos, para que não vejam a vaidade, e vivifica-me no teu caminho.

[[v19-119-38]]

^<<v19-119-38,38>>^ Confirma ao teu servo a tua promessa feita aos que te temem.

[[v19-119-39]]

^<<v19-119-39,39>>^ Afasta de mim o opróbrio, que temo, porque os teus juízos são bons.

[[v19-119-40]]

^<<v19-119-40,40>>^ Eis que tenho suspirado pelos teus preceitos; vivifica-me por tua justiça.

[[v19-119-41]]

^<<v19-119-41,41>>^ Venham também sobre mim as tuas misericórdias, SENHOR, e a tua salvação, segundo a tua promessa.

[[v19-119-42]]

^<<v19-119-42,42>>^ E saberei responder aos que me insultam, pois confio na tua palavra.

[[v19-119-43]]

^<<v19-119-43,43>>^ Não tires jamais de minha boca a palavra da verdade, pois tenho esperado nos teus juízos.

[[v19-119-44]]

^<<v19-119-44,44>>^ Assim, observarei de contínuo a tua lei, para todo o sempre.

[[v19-119-45]]

^<<v19-119-45,45>>^ E andarei com largueza, pois me empenho pelos teus preceitos.

[[v19-119-46]]

^<<v19-119-46,46>>^ Também falarei dos teus testemunhos na presença dos reis e não me envergonharei.

[[v19-119-47]]

^<<v19-119-47,47>>^ Terei prazer nos teus mandamentos, os quais eu amo.

[[v19-119-48]]

^<<v19-119-48,48>>^ Para os teus mandamentos, que amo, levantarei as mãos e meditarei nos teus decretos.

[[v19-119-49]]

^<<v19-119-49,49>>^ Lembra-te da promessa que fizeste ao teu servo, na qual me tens feito esperar.

[[v19-119-50]]

^<<v19-119-50,50>>^ O que me consola na minha angústia é isto: que a tua palavra me vivifica.

[[v19-119-51]]

^<<v19-119-51,51>>^ Os soberbos zombam continuamente de mim; todavia, não me afasto da tua lei.

[[v19-119-52]]

^<<v19-119-52,52>>^ Lembro-me dos teus juízos de outrora e me conforto, ó SENHOR.

[[v19-119-53]]

^<<v19-119-53,53>>^ De mim se apoderou a indignação, por causa dos pecadores que abandonaram a tua lei.

[[v19-119-54]]

^<<v19-119-54,54>>^ Os teus decretos são motivo dos meus cânticos, na casa da minha peregrinação.

[[v19-119-55]]

^<<v19-119-55,55>>^ Lembro-me, SENHOR, do teu nome, durante a noite, e observo a tua lei.

[[v19-119-56]]

^<<v19-119-56,56>>^ Tem-se dado assim comigo, porque guardo os teus preceitos.

[[v19-119-57]]

^<<v19-119-57,57>>^ O SENHOR é a minha porção; eu disse que guardaria as tuas palavras.

[[v19-119-58]]

^<<v19-119-58,58>>^ Imploro de todo o coração a tua graça; compadece-te de mim, segundo a tua palavra.

[[v19-119-59]]

^<<v19-119-59,59>>^ Considero os meus caminhos e volto os meus passos para os teus testemunhos.

[[v19-119-60]]

^<<v19-119-60,60>>^ Apresso-me, não me detenho em guardar os teus mandamentos.

[[v19-119-61]]

^<<v19-119-61,61>>^ Laços de perversos me enleiam; contudo, não me esqueço da tua lei.

[[v19-119-62]]

^<<v19-119-62,62>>^ Levanto-me à meia-noite para te dar graças, por causa dos teus retos juízos.

[[v19-119-63]]

^<<v19-119-63,63>>^ Companheiro sou de todos os que te temem e dos que guardam os teus preceitos.

[[v19-119-64]]

^<<v19-119-64,64>>^ A terra, SENHOR, está cheia da tua bondade; ensina-me os teus decretos.

[[v19-119-65]]

^<<v19-119-65,65>>^ Tens feito bem ao teu servo, SENHOR, segundo a tua palavra.

[[v19-119-66]]

^<<v19-119-66,66>>^ Ensina-me bom juízo e conhecimento, pois creio nos teus mandamentos.

[[v19-119-67]]

^<<v19-119-67,67>>^ Antes de ser afligido, andava errado, mas agora guardo a tua palavra.

[[v19-119-68]]

^<<v19-119-68,68>>^ Tu és bom e fazes o bem; ensina-me os teus decretos.

[[v19-119-69]]

^<<v19-119-69,69>>^ Os soberbos têm forjado mentiras contra mim; não obstante, eu guardo de todo o coração os teus preceitos.

[[v19-119-70]]

^<<v19-119-70,70>>^ Tornou-se-lhes o coração insensível, como se fosse de sebo; mas eu me comprazo na tua lei.

[[v19-119-71]]

^<<v19-119-71,71>>^ Foi-me bom ter eu passado pela aflição, para que aprendesse os teus decretos.

[[v19-119-72]]

^<<v19-119-72,72>>^ Para mim vale mais a lei que procede de tua boca do que milhares de ouro ou de prata.

[[v19-119-73]]

^<<v19-119-73,73>>^ As tuas mãos me fizeram e me afeiçoaram; ensina-me para que aprenda os teus mandamentos.

[[v19-119-74]]

^<<v19-119-74,74>>^ Alegraram-se os que te temem quando me viram, porque na tua palavra tenho esperado.

[[v19-119-75]]

^<<v19-119-75,75>>^ Bem sei, ó SENHOR, que os teus juízos são justos e que com fidelidade me afligiste.

[[v19-119-76]]

^<<v19-119-76,76>>^ Venha, pois, a tua bondade consolar-me, segundo a palavra que deste ao teu servo.

[[v19-119-77]]

^<<v19-119-77,77>>^ Baixem sobre mim as tuas misericórdias, para que eu viva; pois na tua lei está o meu prazer.

[[v19-119-78]]

^<<v19-119-78,78>>^ Envergonhados sejam os soberbos por me haverem oprimido injustamente; eu, porém, meditarei nos teus preceitos.

[[v19-119-79]]

^<<v19-119-79,79>>^ Voltem-se para mim os que te temem e os que conhecem os teus testemunhos.

[[v19-119-80]]

^<<v19-119-80,80>>^ Seja o meu coração irrepreensível nos teus decretos, para que eu não seja envergonhado.

[[v19-119-81]]

^<<v19-119-81,81>>^ Desfalece-me a alma, aguardando a tua salvação; porém espero na tua palavra.

[[v19-119-82]]

^<<v19-119-82,82>>^ Esmorecem os meus olhos de tanto esperar por tua promessa, enquanto digo: quando me haverás de consolar?

[[v19-119-83]]

^<<v19-119-83,83>>^ Já me assemelho a um odre na fumaça; contudo, não me esqueço dos teus decretos.

[[v19-119-84]]

^<<v19-119-84,84>>^ Quantos vêm a ser os dias do teu servo? Quando me farás justiça contra os que me perseguem?

[[v19-119-85]]

^<<v19-119-85,85>>^ Para mim abriram covas os soberbos, que não andam consoante a tua lei.

[[v19-119-86]]

^<<v19-119-86,86>>^ São verdadeiros todos os teus mandamentos; eles me perseguem injustamente; ajuda-me.

[[v19-119-87]]

^<<v19-119-87,87>>^ Quase deram cabo de mim, na terra; mas eu não deixo os teus preceitos.

[[v19-119-88]]

^<<v19-119-88,88>>^ Vivifica-me, segundo a tua misericórdia, e guardarei os testemunhos oriundos de tua boca.

[[v19-119-89]]

^<<v19-119-89,89>>^ Para sempre, ó SENHOR, está firmada a tua palavra no céu.

[[v19-119-90]]

^<<v19-119-90,90>>^ A tua fidelidade estende-se de geração em geração; fundaste a terra, e ela permanece.

[[v19-119-91]]

^<<v19-119-91,91>>^ Conforme os teus juízos, assim tudo se mantém até hoje; porque ao teu dispor estão todas as coisas.

[[v19-119-92]]

^<<v19-119-92,92>>^ Não fosse a tua lei ter sido o meu prazer, há muito já teria eu perecido na minha angústia.

[[v19-119-93]]

^<<v19-119-93,93>>^ Nunca me esquecerei dos teus preceitos, visto que por eles me tens dado vida.

[[v19-119-94]]

^<<v19-119-94,94>>^ Sou teu; salva-me, pois eu busco os teus preceitos.

[[v19-119-95]]

^<<v19-119-95,95>>^ Os ímpios me espreitam para perder-me; mas eu atento para os teus testemunhos.

[[v19-119-96]]

^<<v19-119-96,96>>^ Tenho visto que toda perfeição tem seu limite; mas o teu mandamento é ilimitado.

[[v19-119-97]]

^<<v19-119-97,97>>^ Quanto amo a tua lei! É a minha meditação, todo o dia!

[[v19-119-98]]

^<<v19-119-98,98>>^ Os teus mandamentos me fazem mais sábio que os meus inimigos; porque, aqueles, eu os tenho sempre comigo.

[[v19-119-99]]

^<<v19-119-99,99>>^ Compreendo mais do que todos os meus mestres, porque medito nos teus testemunhos.

[[v19-119-100]]

^<<v19-119-100,100>>^ Sou mais prudente que os idosos, porque guardo os teus preceitos.

[[v19-119-101]]

^<<v19-119-101,101>>^ De todo mau caminho desvio os pés, para observar a tua palavra.

[[v19-119-102]]

^<<v19-119-102,102>>^ Não me aparto dos teus juízos, pois tu me ensinas.

[[v19-119-103]]

^<<v19-119-103,103>>^ Quão doces são as tuas palavras ao meu paladar! Mais que o mel à minha boca.

[[v19-119-104]]

^<<v19-119-104,104>>^ Por meio dos teus preceitos, consigo entendimento; por isso, detesto todo caminho de falsidade.

[[v19-119-105]]

^<<v19-119-105,105>>^ Lâmpada para os meus pés é a tua palavra e, luz para os meus caminhos.

[[v19-119-106]]

^<<v19-119-106,106>>^ Jurei e confirmei o juramento de guardar os teus retos juízos.

[[v19-119-107]]

^<<v19-119-107,107>>^ Estou aflitíssimo; vivifica-me, SENHOR, segundo a tua palavra.

[[v19-119-108]]

^<<v19-119-108,108>>^ Aceita, SENHOR, a espontânea oferenda dos meus lábios e ensina-me os teus juízos.

[[v19-119-109]]

^<<v19-119-109,109>>^ Estou de contínuo em perigo de vida; todavia, não me esqueço da tua lei.

[[v19-119-110]]

^<<v19-119-110,110>>^ Armam ciladas contra mim os ímpios; contudo, não me desvio dos teus preceitos.

[[v19-119-111]]

^<<v19-119-111,111>>^ Os teus testemunhos, recebi-os por legado perpétuo, porque me constituem o prazer do coração.

[[v19-119-112]]

^<<v19-119-112,112>>^ Induzo o coração a guardar os teus decretos, para sempre, até ao fim.

[[v19-119-113]]

^<<v19-119-113,113>>^ Aborreço a duplicidade, porém amo a tua lei.

[[v19-119-114]]

^<<v19-119-114,114>>^ Tu és o meu refúgio e o meu escudo; na tua palavra, eu espero.

[[v19-119-115]]

^<<v19-119-115,115>>^ Apartai-vos de mim, malfeitores; quero guardar os mandamentos do meu Deus.

[[v19-119-116]]

^<<v19-119-116,116>>^ Ampara-me, segundo a tua promessa, para que eu viva; não permitas que a minha esperança me envergonhe.

[[v19-119-117]]

^<<v19-119-117,117>>^ Sustenta-me, e serei salvo e sempre atentarei para os teus decretos.

[[v19-119-118]]

^<<v19-119-118,118>>^ Desprezas os que se desviam dos teus decretos, porque falsidade é a astúcia deles.

[[v19-119-119]]

^<<v19-119-119,119>>^ Rejeitas, como escória, todos os ímpios da terra; por isso, amo os teus testemunhos.

[[v19-119-120]]

^<<v19-119-120,120>>^ Arrepia-se-me a carne com temor de ti, e temo os teus juízos.

[[v19-119-121]]

^<<v19-119-121,121>>^ Tenho praticado juízo e justiça; não me entregues aos meus opressores.

[[v19-119-122]]

^<<v19-119-122,122>>^ Sê fiador do teu servo para o bem; não permitas que os soberbos me oprimam.

[[v19-119-123]]

^<<v19-119-123,123>>^ Desfalecem-me os olhos à espera da tua salvação e da promessa da tua justiça.

[[v19-119-124]]

^<<v19-119-124,124>>^ Trata o teu servo segundo a tua misericórdia e ensina-me os teus decretos.

[[v19-119-125]]

^<<v19-119-125,125>>^ Sou teu servo; dá-me entendimento, para que eu conheça os teus testemunhos.

[[v19-119-126]]

^<<v19-119-126,126>>^ Já é tempo, SENHOR, para intervires, pois a tua lei está sendo violada.

[[v19-119-127]]

^<<v19-119-127,127>>^ Amo os teus mandamentos mais do que o ouro, mais do que o ouro refinado.

[[v19-119-128]]

^<<v19-119-128,128>>^ Por isso, tenho por, em tudo, retos os teus preceitos todos e aborreço todo caminho de falsidade.

[[v19-119-129]]

^<<v19-119-129,129>>^ Admiráveis são os teus testemunhos; por isso, a minha alma os observa.

[[v19-119-130]]

^<<v19-119-130,130>>^ A revelação das tuas palavras esclarece e dá entendimento aos simples.

[[v19-119-131]]

^<<v19-119-131,131>>^ Abro a boca e aspiro, porque anelo os teus mandamentos.

[[v19-119-132]]

^<<v19-119-132,132>>^ Volta-te para mim e tem piedade de mim, segundo costumas fazer aos que amam o teu nome.

[[v19-119-133]]

^<<v19-119-133,133>>^ Firma os meus passos na tua palavra, e não me domine iniquidade alguma.

[[v19-119-134]]

^<<v19-119-134,134>>^ Livra-me da opressão do homem, e guardarei os teus preceitos.

[[v19-119-135]]

^<<v19-119-135,135>>^ Faze resplandecer o rosto sobre o teu servo e ensina-me os teus decretos.

[[v19-119-136]]

^<<v19-119-136,136>>^ Torrentes de água nascem dos meus olhos, porque os homens não guardam a tua lei.

[[v19-119-137]]

^<<v19-119-137,137>>^ Justo és, SENHOR, e retos, os teus juízos.

[[v19-119-138]]

^<<v19-119-138,138>>^ Os teus testemunhos, tu os impuseste com retidão e com suma fidelidade.

[[v19-119-139]]

^<<v19-119-139,139>>^ O meu zelo me consome, porque os meus adversários se esquecem da tua palavra.

[[v19-119-140]]

^<<v19-119-140,140>>^ Puríssima é a tua palavra; por isso, o teu servo a estima.

[[v19-119-141]]

^<<v19-119-141,141>>^ Pequeno sou e desprezado; contudo, não me esqueço dos teus preceitos.

[[v19-119-142]]

^<<v19-119-142,142>>^ A tua justiça é justiça eterna, e a tua lei é a própria verdade.

[[v19-119-143]]

^<<v19-119-143,143>>^ Sobre mim vieram tribulação e angústia; todavia, os teus mandamentos são o meu prazer.

[[v19-119-144]]

^<<v19-119-144,144>>^ Eterna é a justiça dos teus testemunhos; dá-me a inteligência deles, e viverei.

[[v19-119-145]]

^<<v19-119-145,145>>^ De todo o coração eu te invoco; ouve-me, SENHOR; observo os teus decretos.

[[v19-119-146]]

^<<v19-119-146,146>>^ Clamo a ti; salva-me, e guardarei os teus testemunhos.

[[v19-119-147]]

^<<v19-119-147,147>>^ Antecipo-me ao alvorecer do dia e clamo; na tua palavra, espero confiante.

[[v19-119-148]]

^<<v19-119-148,148>>^ Os meus olhos antecipam-se às vigílias noturnas, para que eu medite nas tuas palavras.

[[v19-119-149]]

^<<v19-119-149,149>>^ Ouve, SENHOR, a minha voz, segundo a tua bondade; vivifica-me, segundo os teus juízos.

[[v19-119-150]]

^<<v19-119-150,150>>^ Aproximam-se de mim os que andam após a maldade; eles se afastam da tua lei.

[[v19-119-151]]

^<<v19-119-151,151>>^ Tu estás perto, SENHOR, e todos os teus mandamentos são verdade.

[[v19-119-152]]

^<<v19-119-152,152>>^ Quanto às tuas prescrições, há muito sei que as estabeleceste para sempre.

[[v19-119-153]]

^<<v19-119-153,153>>^ Atenta para a minha aflição e livra-me, pois não me esqueço da tua lei.

[[v19-119-154]]

^<<v19-119-154,154>>^ Defende a minha causa e liberta-me; vivifica-me, segundo a tua promessa.

[[v19-119-155]]

^<<v19-119-155,155>>^ A salvação está longe dos ímpios, pois não procuram os teus decretos.

[[v19-119-156]]

^<<v19-119-156,156>>^ Muitas, SENHOR, são as tuas misericórdias; vivifica-me, segundo os teus juízos.

[[v19-119-157]]

^<<v19-119-157,157>>^ São muitos os meus perseguidores e os meus adversários; não me desvio, porém, dos teus testemunhos.

[[v19-119-158]]

^<<v19-119-158,158>>^ Vi os infiéis e senti desgosto, porque não guardam a tua palavra.

[[v19-119-159]]

^<<v19-119-159,159>>^ Considera em como amo os teus preceitos; vivifica-me, ó SENHOR, segundo a tua bondade.

[[v19-119-160]]

^<<v19-119-160,160>>^ As tuas palavras são em tudo verdade desde o princípio, e cada um dos teus justos juízos dura para sempre.

[[v19-119-161]]

^<<v19-119-161,161>>^ Príncipes me perseguem sem causa, porém o que o meu coração teme é a tua palavra.

[[v19-119-162]]

^<<v19-119-162,162>>^ Alegro-me nas tuas promessas, como quem acha grandes despojos.

[[v19-119-163]]

^<<v19-119-163,163>>^ Abomino e detesto a mentira; porém amo a tua lei.

[[v19-119-164]]

^<<v19-119-164,164>>^ Sete vezes no dia, eu te louvo pela justiça dos teus juízos.

[[v19-119-165]]

^<<v19-119-165,165>>^ Grande paz têm os que amam a tua lei; para eles não há tropeço.

[[v19-119-166]]

^<<v19-119-166,166>>^ Espero, SENHOR, na tua salvação e cumpro os teus mandamentos.

[[v19-119-167]]

^<<v19-119-167,167>>^ A minha alma tem observado os teus testemunhos; eu os amo ardentemente.

[[v19-119-168]]

^<<v19-119-168,168>>^ Tenho observado os teus preceitos e os teus testemunhos, pois na tua presença estão todos os meus caminhos.

[[v19-119-169]]

^<<v19-119-169,169>>^ Chegue a ti, SENHOR, a minha súplica; dá-me entendimento, segundo a tua palavra.

[[v19-119-170]]

^<<v19-119-170,170>>^ Chegue a minha petição à tua presença; livra-me segundo a tua palavra.

[[v19-119-171]]

^<<v19-119-171,171>>^ Profiram louvor os meus lábios, pois me ensinas os teus decretos.

[[v19-119-172]]

^<<v19-119-172,172>>^ A minha língua celebre a tua lei, pois todos os teus mandamentos são justiça.

[[v19-119-173]]

^<<v19-119-173,173>>^ Venha a tua mão socorrer-me, pois escolhi os teus preceitos.

[[v19-119-174]]

^<<v19-119-174,174>>^ Suspiro, SENHOR, por tua salvação; a tua lei é todo o meu prazer.

[[v19-119-175]]

^<<v19-119-175,175>>^ Viva a minha alma para louvar-te; ajudem-me os teus juízos.

[[v19-119-176]]

^<<v19-119-176,176>>^ Ando errante como ovelha desgarrada; procura o teu servo, pois não me esqueço dos teus mandamentos.

'''

xref:019-salmos/019-salmos-118.adoc#v19-118-0[&#60; Capítulo Anterior] | <<v19-119-0,Topo>> | xref:019-salmos/019-salmos-120.adoc#v19-120-0[Próximo Capítulo &#62;]