include::./index.adoc[]

[[v19-39-0]]
=== Salmos, 39
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-39-1]]

^<<v19-39-1,1>>^ Disse comigo mesmo: guardarei os meus caminhos, para não pecar com a língua; porei mordaça à minha boca, enquanto estiver na minha presença o ímpio.

[[v19-39-2]]

^<<v19-39-2,2>>^ Emudeci em silêncio, calei acerca do bem, e a minha dor se agravou.

[[v19-39-3]]

^<<v19-39-3,3>>^ Esbraseou-se-me no peito o coração; enquanto eu meditava, ateou-se o fogo; então, disse eu com a própria língua:

[[v19-39-4]]

^<<v19-39-4,4>>^ Dá-me a conhecer, SENHOR, o meu fim e qual a soma dos meus dias, para que eu reconheça a minha fragilidade.

[[v19-39-5]]

^<<v19-39-5,5>>^ Deste aos meus dias o comprimento de alguns palmos; à tua presença, o prazo da minha vida é nada. Na verdade, todo homem, por mais firme que esteja, é pura vaidade.

[[v19-39-6]]

^<<v19-39-6,6>>^ Com efeito, passa o homem como uma sombra; em vão se inquieta; amontoa tesouros e não sabe quem os levará.

[[v19-39-7]]

^<<v19-39-7,7>>^ E eu, Senhor, que espero? Tu és a minha esperança.

[[v19-39-8]]

^<<v19-39-8,8>>^ Livra-me de todas as minhas iniquidades; não me faças o opróbrio do insensato.

[[v19-39-9]]

^<<v19-39-9,9>>^ Emudeço, não abro os lábios porque tu fizeste isso.

[[v19-39-10]]

^<<v19-39-10,10>>^ Tira de sobre mim o teu flagelo; pelo golpe de tua mão, estou consumido.

[[v19-39-11]]

^<<v19-39-11,11>>^ Quando castigas o homem com repreensões, por causa da iniquidade, destróis nele, como traça, o que tem de precioso. Com efeito, todo homem é pura vaidade.

[[v19-39-12]]

^<<v19-39-12,12>>^ Ouve, SENHOR, a minha oração, escuta-me quando grito por socorro; não te emudeças à vista de minhas lágrimas, porque sou forasteiro à tua presença, peregrino como todos os meus pais o foram.

[[v19-39-13]]

^<<v19-39-13,13>>^ Desvia de mim o olhar, para que eu tome alento, antes que eu passe e deixe de existir.

'''

xref:019-salmos/019-salmos-038.adoc#v19-38-0[&#60; Capítulo Anterior] | <<v19-39-0,Topo>> | xref:019-salmos/019-salmos-040.adoc#v19-40-0[Próximo Capítulo &#62;]