include::./index.adoc[]

[[v19-75-0]]
=== Salmos, 75
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-75-1]]

^<<v19-75-1,1>>^ Graças te rendemos, ó Deus; graças te rendemos, e invocamos o teu nome, e declaramos as tuas maravilhas.

[[v19-75-2]]

^<<v19-75-2,2>>^ Pois disseste: Hei de aproveitar o tempo determinado; hei de julgar retamente.

[[v19-75-3]]

^<<v19-75-3,3>>^ Vacilem a terra e todos os seus moradores, ainda assim eu firmarei as suas colunas.

[[v19-75-4]]

^<<v19-75-4,4>>^ Digo aos soberbos: não sejais arrogantes; e aos ímpios: não levanteis a vossa força.

[[v19-75-5]]

^<<v19-75-5,5>>^ Não levanteis altivamente a vossa força, nem faleis com insolência contra a Rocha.

[[v19-75-6]]

^<<v19-75-6,6>>^ Porque não é do Oriente, não é do Ocidente, nem do deserto que vem o auxílio.

[[v19-75-7]]

^<<v19-75-7,7>>^ Deus é o juiz; a um abate, a outro exalta.

[[v19-75-8]]

^<<v19-75-8,8>>^ Porque na mão do SENHOR há um cálice cujo vinho espuma, cheio de mistura; dele dá a beber; sorvem-no, até às escórias, todos os ímpios da terra.

[[v19-75-9]]

^<<v19-75-9,9>>^ Quanto a mim, exultarei para sempre; salmodiarei louvores ao Deus de Jacó.

[[v19-75-10]]

^<<v19-75-10,10>>^ Abaterei as forças dos ímpios; mas a força dos justos será exaltada.

'''

xref:019-salmos/019-salmos-074.adoc#v19-74-0[&#60; Capítulo Anterior] | <<v19-75-0,Topo>> | xref:019-salmos/019-salmos-076.adoc#v19-76-0[Próximo Capítulo &#62;]