include::./index.adoc[]

[[v19-8-0]]
=== Salmos, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-8-1]]

^<<v19-8-1,1>>^ Ó SENHOR, Senhor nosso, quão magnífico em toda a terra é o teu nome! Pois expuseste nos céus a tua majestade.

[[v19-8-2]]

^<<v19-8-2,2>>^ Da boca de pequeninos e crianças de peito suscitaste força, por causa dos teus adversários, para fazeres emudecer o inimigo e o vingador.

[[v19-8-3]]

^<<v19-8-3,3>>^ Quando contemplo os teus céus, obra dos teus dedos, e a lua e as estrelas que estabeleceste,

[[v19-8-4]]

^<<v19-8-4,4>>^ que é o homem, que dele te lembres? E o filho do homem, que o visites?

[[v19-8-5]]

^<<v19-8-5,5>>^ Fizeste-o, no entanto, por um pouco, menor do que Deus e de glória e de honra o coroaste.

[[v19-8-6]]

^<<v19-8-6,6>>^ Deste-lhe domínio sobre as obras da tua mão e sob seus pés tudo lhe puseste:

[[v19-8-7]]

^<<v19-8-7,7>>^ ovelhas e bois, todos, e também os animais do campo;

[[v19-8-8]]

^<<v19-8-8,8>>^ as aves do céu, e os peixes do mar, e tudo o que percorre as sendas dos mares.

[[v19-8-9]]

^<<v19-8-9,9>>^ Ó SENHOR, Senhor nosso, quão magnífico em toda a terra é o teu nome!

'''

xref:019-salmos/019-salmos-007.adoc#v19-7-0[&#60; Capítulo Anterior] | <<v19-8-0,Topo>> | xref:019-salmos/019-salmos-009.adoc#v19-9-0[Próximo Capítulo &#62;]