include::./index.adoc[]

[[v19-136-0]]
=== Salmos, 136
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-136-1]]

^<<v19-136-1,1>>^ Rendei graças ao SENHOR, porque ele é bom, porque a sua misericórdia dura para sempre.

[[v19-136-2]]

^<<v19-136-2,2>>^ Rendei graças ao Deus dos deuses, porque a sua misericórdia dura para sempre.

[[v19-136-3]]

^<<v19-136-3,3>>^ Rendei graças ao Senhor dos senhores, porque a sua misericórdia dura para sempre;

[[v19-136-4]]

^<<v19-136-4,4>>^ ao único que opera grandes maravilhas, porque a sua misericórdia dura para sempre;

[[v19-136-5]]

^<<v19-136-5,5>>^ àquele que com entendimento fez os céus, porque a sua misericórdia dura para sempre;

[[v19-136-6]]

^<<v19-136-6,6>>^ àquele que estendeu a terra sobre as águas, porque a sua misericórdia dura para sempre;

[[v19-136-7]]

^<<v19-136-7,7>>^ àquele que fez os grandes luminares, porque a sua misericórdia dura para sempre;

[[v19-136-8]]

^<<v19-136-8,8>>^ o sol para presidir o dia, porque a sua misericórdia dura para sempre;

[[v19-136-9]]

^<<v19-136-9,9>>^ a lua e as estrelas para presidirem a noite, porque a sua misericórdia dura para sempre;

[[v19-136-10]]

^<<v19-136-10,10>>^ àquele que feriu o Egito nos seus primogênitos, porque a sua misericórdia dura para sempre;

[[v19-136-11]]

^<<v19-136-11,11>>^ e tirou a Israel do meio deles, porque a sua misericórdia dura para sempre;

[[v19-136-12]]

^<<v19-136-12,12>>^ com mão poderosa e braço estendido, porque a sua misericórdia dura para sempre;

[[v19-136-13]]

^<<v19-136-13,13>>^ àquele que separou em duas partes o mar Vermelho, porque a sua misericórdia dura para sempre;

[[v19-136-14]]

^<<v19-136-14,14>>^ e por entre elas fez passar a Israel, porque a sua misericórdia dura para sempre;

[[v19-136-15]]

^<<v19-136-15,15>>^ mas precipitou no mar Vermelho a Faraó e ao seu exército, porque a sua misericórdia dura para sempre;

[[v19-136-16]]

^<<v19-136-16,16>>^ àquele que conduziu o seu povo pelo deserto, porque a sua misericórdia dura para sempre;

[[v19-136-17]]

^<<v19-136-17,17>>^ àquele que feriu grandes reis, porque a sua misericórdia dura para sempre;

[[v19-136-18]]

^<<v19-136-18,18>>^ e tirou a vida a famosos reis, porque a sua misericórdia dura para sempre;

[[v19-136-19]]

^<<v19-136-19,19>>^ a Seom, rei dos amorreus, porque a sua misericórdia dura para sempre;

[[v19-136-20]]

^<<v19-136-20,20>>^ e a Ogue, rei de Basã, porque a sua misericórdia dura para sempre;

[[v19-136-21]]

^<<v19-136-21,21>>^ cujas terras deu em herança, porque a sua misericórdia dura para sempre;

[[v19-136-22]]

^<<v19-136-22,22>>^ em herança a Israel, seu servo, porque a sua misericórdia dura para sempre;

[[v19-136-23]]

^<<v19-136-23,23>>^ a quem se lembrou de nós em nosso abatimento, porque a sua misericórdia dura para sempre;

[[v19-136-24]]

^<<v19-136-24,24>>^ e nos libertou dos nossos adversários, porque a sua misericórdia dura para sempre;

[[v19-136-25]]

^<<v19-136-25,25>>^ e dá alimento a toda carne, porque a sua misericórdia dura para sempre.

[[v19-136-26]]

^<<v19-136-26,26>>^ Oh! Tributai louvores ao Deus dos céus, porque a sua misericórdia dura para sempre.

'''

xref:019-salmos/019-salmos-135.adoc#v19-135-0[&#60; Capítulo Anterior] | <<v19-136-0,Topo>> | xref:019-salmos/019-salmos-137.adoc#v19-137-0[Próximo Capítulo &#62;]