include::./index.adoc[]

[[v19-106-0]]
=== Salmos, 106
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-106-1]]

^<<v19-106-1,1>>^ Aleluia! Rendei graças ao SENHOR, porque ele é bom; porque a sua misericórdia dura para sempre.

[[v19-106-2]]

^<<v19-106-2,2>>^ Quem saberá contar os poderosos feitos do Senhor ou anunciar os seus louvores?

[[v19-106-3]]

^<<v19-106-3,3>>^ Bem-aventurados os que guardam a retidão e o que pratica a justiça em todo tempo.

[[v19-106-4]]

^<<v19-106-4,4>>^ Lembra-te de mim, SENHOR, segundo a tua bondade para com o teu povo; visita-me com a tua salvação,

[[v19-106-5]]

^<<v19-106-5,5>>^ para que eu veja a prosperidade dos teus escolhidos, e me alegre com a alegria do teu povo, e me regozije com a tua herança.

[[v19-106-6]]

^<<v19-106-6,6>>^ Pecamos, como nossos pais; cometemos iniquidade, procedemos mal.

[[v19-106-7]]

^<<v19-106-7,7>>^ Nossos pais, no Egito, não atentaram às tuas maravilhas; não se lembraram da multidão das tuas misericórdias e foram rebeldes junto ao mar, o mar Vermelho.

[[v19-106-8]]

^<<v19-106-8,8>>^ Mas ele os salvou por amor do seu nome, para lhes fazer notório o seu poder.

[[v19-106-9]]

^<<v19-106-9,9>>^ Repreendeu o mar Vermelho, e ele secou; e fê-los passar pelos abismos, como por um deserto.

[[v19-106-10]]

^<<v19-106-10,10>>^ Salvou-os das mãos de quem os odiava e os remiu do poder do inimigo.

[[v19-106-11]]

^<<v19-106-11,11>>^ As águas cobriram os seus opressores; nem um deles escapou.

[[v19-106-12]]

^<<v19-106-12,12>>^ Então, creram nas suas palavras e lhe cantaram louvor.

[[v19-106-13]]

^<<v19-106-13,13>>^ Cedo, porém, se esqueceram das suas obras e não lhe aguardaram os desígnios;

[[v19-106-14]]

^<<v19-106-14,14>>^ entregaram-se à cobiça, no deserto; e tentaram a Deus na solidão.

[[v19-106-15]]

^<<v19-106-15,15>>^ Concedeu-lhes o que pediram, mas fez definhar-lhes a alma.

[[v19-106-16]]

^<<v19-106-16,16>>^ Tiveram inveja de Moisés, no acampamento, e de Arão, o santo do SENHOR.

[[v19-106-17]]

^<<v19-106-17,17>>^ Abriu-se a terra, e tragou a Datã, e cobriu o grupo de Abirão.

[[v19-106-18]]

^<<v19-106-18,18>>^ Ateou-se um fogo contra o seu grupo; a chama abrasou os ímpios.

[[v19-106-19]]

^<<v19-106-19,19>>^ Em Horebe, fizeram um bezerro e adoraram o ídolo fundido.

[[v19-106-20]]

^<<v19-106-20,20>>^ E, assim, trocaram a glória de Deus pelo simulacro de um novilho que come erva.

[[v19-106-21]]

^<<v19-106-21,21>>^ Esqueceram-se de Deus, seu Salvador, que, no Egito, fizera coisas portentosas,

[[v19-106-22]]

^<<v19-106-22,22>>^ maravilhas na terra de Cam, tremendos feitos no mar Vermelho.

[[v19-106-23]]

^<<v19-106-23,23>>^ Tê-los-ia exterminado, como dissera, se Moisés, seu escolhido, não se houvesse interposto, impedindo que sua cólera os destruísse.

[[v19-106-24]]

^<<v19-106-24,24>>^ Também desprezaram a terra aprazível e não deram crédito à sua palavra;

[[v19-106-25]]

^<<v19-106-25,25>>^ antes, murmuraram em suas tendas e não acudiram à voz do SENHOR.

[[v19-106-26]]

^<<v19-106-26,26>>^ Então, lhes jurou, de mão erguida, que os havia de arrasar no deserto;

[[v19-106-27]]

^<<v19-106-27,27>>^ e também derribaria entre as nações a sua descendência e os dispersaria por outras terras.

[[v19-106-28]]

^<<v19-106-28,28>>^ Também se juntaram a Baal-Peor e comeram os sacrifícios dos ídolos mortos.

[[v19-106-29]]

^<<v19-106-29,29>>^ Assim, com tais ações, o provocaram à ira; e grassou peste entre eles.

[[v19-106-30]]

^<<v19-106-30,30>>^ Então, se levantou Fineias e executou o juízo; e cessou a peste.

[[v19-106-31]]

^<<v19-106-31,31>>^ Isso lhe foi imputado por justiça, de geração em geração, para sempre.

[[v19-106-32]]

^<<v19-106-32,32>>^ Depois, o indignaram nas águas de Meribá, e, por causa deles, sucedeu mal a Moisés,

[[v19-106-33]]

^<<v19-106-33,33>>^ pois foram rebeldes ao Espírito de Deus, e Moisés falou irrefletidamente.

[[v19-106-34]]

^<<v19-106-34,34>>^ Não exterminaram os povos, como o SENHOR lhes ordenara.

[[v19-106-35]]

^<<v19-106-35,35>>^ Antes, se mesclaram com as nações e lhes aprenderam as obras;

[[v19-106-36]]

^<<v19-106-36,36>>^ deram culto a seus ídolos, os quais se lhes converteram em laço;

[[v19-106-37]]

^<<v19-106-37,37>>^ pois imolaram seus filhos e suas filhas aos demônios

[[v19-106-38]]

^<<v19-106-38,38>>^ e derramaram sangue inocente, o sangue de seus filhos e filhas, que sacrificaram aos ídolos de Canaã; e a terra foi contaminada com sangue.

[[v19-106-39]]

^<<v19-106-39,39>>^ Assim se contaminaram com as suas obras e se prostituíram nos seus feitos.

[[v19-106-40]]

^<<v19-106-40,40>>^ Acendeu-se, por isso, a ira do SENHOR contra o seu povo, e ele abominou a sua própria herança

[[v19-106-41]]

^<<v19-106-41,41>>^ e os entregou ao poder das nações; sobre eles dominaram os que os odiavam.

[[v19-106-42]]

^<<v19-106-42,42>>^ Também os oprimiram os seus inimigos, sob cujo poder foram subjugados.

[[v19-106-43]]

^<<v19-106-43,43>>^ Muitas vezes os libertou, mas eles o provocaram com os seus conselhos e, por sua iniquidade, foram abatidos.

[[v19-106-44]]

^<<v19-106-44,44>>^ Olhou-os, contudo, quando estavam angustiados e lhes ouviu o clamor;

[[v19-106-45]]

^<<v19-106-45,45>>^ lembrou-se, a favor deles, de sua aliança e se compadeceu, segundo a multidão de suas misericórdias.

[[v19-106-46]]

^<<v19-106-46,46>>^ Fez também que lograssem compaixão de todos os que os levaram cativos.

[[v19-106-47]]

^<<v19-106-47,47>>^ Salva-nos, SENHOR, nosso Deus, e congrega-nos de entre as nações, para que demos graças ao teu santo nome e nos gloriemos no teu louvor.

[[v19-106-48]]

^<<v19-106-48,48>>^ Bendito seja o SENHOR, Deus de Israel, de eternidade a eternidade; e todo o povo diga: Amém! Aleluia!

'''

xref:019-salmos/019-salmos-105.adoc#v19-105-0[&#60; Capítulo Anterior] | <<v19-106-0,Topo>> | xref:019-salmos/019-salmos-107.adoc#v19-107-0[Próximo Capítulo &#62;]