include::./index.adoc[]

[[v19-17-0]]
=== Salmos, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-17-1]]

^<<v19-17-1,1>>^ Ouve, SENHOR, a causa justa, atende ao meu clamor, dá ouvidos à minha oração, que procede de lábios não fraudulentos.

[[v19-17-2]]

^<<v19-17-2,2>>^ Baixe de tua presença o julgamento a meu respeito; os teus olhos veem com equidade.

[[v19-17-3]]

^<<v19-17-3,3>>^ Sondas-me o coração, de noite me visitas, provas-me no fogo e iniquidade nenhuma encontras em mim; a minha boca não transgride.

[[v19-17-4]]

^<<v19-17-4,4>>^ Quanto às ações dos homens, pela palavra dos teus lábios, eu me tenho guardado dos caminhos do violento.

[[v19-17-5]]

^<<v19-17-5,5>>^ Os meus passos se afizeram às tuas veredas, os meus pés não resvalaram.

[[v19-17-6]]

^<<v19-17-6,6>>^ Eu te invoco, ó Deus, pois tu me respondes; inclina-me os ouvidos e acode às minhas palavras.

[[v19-17-7]]

^<<v19-17-7,7>>^ Mostra as maravilhas da tua bondade, ó Salvador dos que à tua destra buscam refúgio dos que se levantam contra eles.

[[v19-17-8]]

^<<v19-17-8,8>>^ Guarda-me como a menina dos olhos, esconde-me à sombra das tuas asas,

[[v19-17-9]]

^<<v19-17-9,9>>^ dos perversos que me oprimem, inimigos que me assediam de morte.

[[v19-17-10]]

^<<v19-17-10,10>>^ Insensíveis, cerram o coração, falam com lábios insolentes;

[[v19-17-11]]

^<<v19-17-11,11>>^ andam agora cercando os nossos passos e fixam em nós os olhos para nos deitar por terra.

[[v19-17-12]]

^<<v19-17-12,12>>^ Parecem-se com o leão, ávido por sua presa, ou o leãozinho, que espreita de emboscada.

[[v19-17-13]]

^<<v19-17-13,13>>^ Levanta-te, SENHOR, defronta-os, arrasa-os; livra do ímpio a minha alma com a tua espada,

[[v19-17-14]]

^<<v19-17-14,14>>^ com a tua mão, SENHOR, dos homens mundanos, cujo quinhão é desta vida e cujo ventre tu enches dos teus tesouros; os quais se fartam de filhos e o que lhes sobra deixam aos seus pequeninos.

[[v19-17-15]]

^<<v19-17-15,15>>^ Eu, porém, na justiça contemplarei a tua face; quando acordar, eu me satisfarei com a tua semelhança.

'''

xref:019-salmos/019-salmos-016.adoc#v19-16-0[&#60; Capítulo Anterior] | <<v19-17-0,Topo>> | xref:019-salmos/019-salmos-018.adoc#v19-18-0[Próximo Capítulo &#62;]