include::./index.adoc[]

[[v19-3-0]]
=== Salmos, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-3-1]]

^<<v19-3-1,1>>^ SENHOR, como tem crescido o número dos meus adversários! São numerosos os que se levantam contra mim.

[[v19-3-2]]

^<<v19-3-2,2>>^ São muitos os que dizem de mim: Não há em Deus salvação para ele.

[[v19-3-3]]

^<<v19-3-3,3>>^ Porém tu, SENHOR, és o meu escudo, és a minha glória e o que exaltas a minha cabeça.

[[v19-3-4]]

^<<v19-3-4,4>>^ Com a minha voz clamo ao SENHOR, e ele do seu santo monte me responde.

[[v19-3-5]]

^<<v19-3-5,5>>^ Deito-me e pego no sono; acordo, porque o SENHOR me sustenta.

[[v19-3-6]]

^<<v19-3-6,6>>^ Não tenho medo de milhares do povo que tomam posição contra mim de todos os lados.

[[v19-3-7]]

^<<v19-3-7,7>>^ Levanta-te, SENHOR! Salva-me, Deus meu, pois feres nos queixos a todos os meus inimigos e aos ímpios quebras os dentes.

[[v19-3-8]]

^<<v19-3-8,8>>^ Do SENHOR é a salvação, e sobre o teu povo, a tua bênção.

'''

xref:019-salmos/019-salmos-002.adoc#v19-2-0[&#60; Capítulo Anterior] | <<v19-3-0,Topo>> | xref:019-salmos/019-salmos-004.adoc#v19-4-0[Próximo Capítulo &#62;]