include::./index.adoc[]

[[v19-89-0]]
=== Salmos, 89
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-89-1]]

^<<v19-89-1,1>>^ Cantarei para sempre as tuas misericórdias, ó SENHOR; os meus lábios proclamarão a todas as gerações a tua fidelidade.

[[v19-89-2]]

^<<v19-89-2,2>>^ Pois disse eu: a benignidade está fundada para sempre; a tua fidelidade, tu a confirmarás nos céus, dizendo:

[[v19-89-3]]

^<<v19-89-3,3>>^ Fiz aliança com o meu escolhido e jurei a Davi, meu servo:

[[v19-89-4]]

^<<v19-89-4,4>>^ Para sempre estabelecerei a tua posteridade e firmarei o teu trono de geração em geração.

[[v19-89-5]]

^<<v19-89-5,5>>^ Celebram os céus as tuas maravilhas, ó SENHOR, e, na assembleia dos santos, a tua fidelidade.

[[v19-89-6]]

^<<v19-89-6,6>>^ Pois quem nos céus é comparável ao SENHOR? Entre os seres celestiais, quem é semelhante ao SENHOR?

[[v19-89-7]]

^<<v19-89-7,7>>^ Deus é sobremodo tremendo na assembleia dos santos e temível sobre todos os que o rodeiam.

[[v19-89-8]]

^<<v19-89-8,8>>^ Ó SENHOR, Deus dos Exércitos, quem é poderoso como tu és, SENHOR, com a tua fidelidade ao redor de ti?!

[[v19-89-9]]

^<<v19-89-9,9>>^ Dominas a fúria do mar; quando as suas ondas se levantam, tu as amainas.

[[v19-89-10]]

^<<v19-89-10,10>>^ Calcaste a Raabe, como um ferido de morte; com o teu poderoso braço dispersaste os teus inimigos.

[[v19-89-11]]

^<<v19-89-11,11>>^ Teus são os céus, tua, a terra; o mundo e a sua plenitude, tu os fundaste.

[[v19-89-12]]

^<<v19-89-12,12>>^ O Norte e o Sul, tu os criaste; o Tabor e o Hermom exultam em teu nome.

[[v19-89-13]]

^<<v19-89-13,13>>^ O teu braço é armado de poder, forte é a tua mão, e elevada, a tua destra.

[[v19-89-14]]

^<<v19-89-14,14>>^ Justiça e direito são o fundamento do teu trono; graça e verdade te precedem.

[[v19-89-15]]

^<<v19-89-15,15>>^ Bem-aventurado o povo que conhece os vivas de júbilo, que anda, ó SENHOR, na luz da tua presença.

[[v19-89-16]]

^<<v19-89-16,16>>^ Em teu nome, de contínuo se alegra e na tua justiça se exalta,

[[v19-89-17]]

^<<v19-89-17,17>>^ porquanto tu és a glória de sua força; no teu favor avulta o nosso poder.

[[v19-89-18]]

^<<v19-89-18,18>>^ Pois ao SENHOR pertence o nosso escudo, e ao Santo de Israel, o nosso rei.

[[v19-89-19]]

^<<v19-89-19,19>>^ Outrora, falaste em visão aos teus santos e disseste: A um herói concedi o poder de socorrer; do meio do povo, exaltei um escolhido.

[[v19-89-20]]

^<<v19-89-20,20>>^ Encontrei Davi, meu servo; com o meu santo óleo o ungi.

[[v19-89-21]]

^<<v19-89-21,21>>^ A minha mão será firme com ele, o meu braço o fortalecerá.

[[v19-89-22]]

^<<v19-89-22,22>>^ O inimigo jamais o surpreenderá, nem o há de afligir o filho da perversidade.

[[v19-89-23]]

^<<v19-89-23,23>>^ Esmagarei diante dele os seus adversários e ferirei os que o odeiam.

[[v19-89-24]]

^<<v19-89-24,24>>^ A minha fidelidade e a minha bondade o hão de acompanhar, e em meu nome crescerá o seu poder.

[[v19-89-25]]

^<<v19-89-25,25>>^ Porei a sua mão sobre o mar e a sua direita, sobre os rios.

[[v19-89-26]]

^<<v19-89-26,26>>^ Ele me invocará, dizendo: Tu és meu pai, meu Deus e a rocha da minha salvação.

[[v19-89-27]]

^<<v19-89-27,27>>^ Fá-lo-ei, por isso, meu primogênito, o mais elevado entre os reis da terra.

[[v19-89-28]]

^<<v19-89-28,28>>^ Conservar-lhe-ei para sempre a minha graça e, firme com ele, a minha aliança.

[[v19-89-29]]

^<<v19-89-29,29>>^ Farei durar para sempre a sua descendência; e, o seu trono, como os dias do céu.

[[v19-89-30]]

^<<v19-89-30,30>>^ Se os seus filhos desprezarem a minha lei e não andarem nos meus juízos,

[[v19-89-31]]

^<<v19-89-31,31>>^ se violarem os meus preceitos e não guardarem os meus mandamentos,

[[v19-89-32]]

^<<v19-89-32,32>>^ então, punirei com vara as suas transgressões e com açoites, a sua iniquidade.

[[v19-89-33]]

^<<v19-89-33,33>>^ Mas jamais retirarei dele a minha bondade, nem desmentirei a minha fidelidade.

[[v19-89-34]]

^<<v19-89-34,34>>^ Não violarei a minha aliança, nem modificarei o que os meus lábios proferiram.

[[v19-89-35]]

^<<v19-89-35,35>>^ Uma vez jurei por minha santidade (e serei eu falso a Davi?):

[[v19-89-36]]

^<<v19-89-36,36>>^ A sua posteridade durará para sempre, e o seu trono, como o sol perante mim.

[[v19-89-37]]

^<<v19-89-37,37>>^ Ele será estabelecido para sempre como a lua e fiel como a testemunha no espaço.

[[v19-89-38]]

^<<v19-89-38,38>>^ Tu, porém, o repudiaste e o rejeitaste; e te indignaste com o teu ungido.

[[v19-89-39]]

^<<v19-89-39,39>>^ Aborreceste a aliança com o teu servo; profanaste-lhe a coroa, arrojando-a para a terra.

[[v19-89-40]]

^<<v19-89-40,40>>^ Arrasaste os seus muros todos; reduziste a ruínas as suas fortificações.

[[v19-89-41]]

^<<v19-89-41,41>>^ Despojam-no todos os que passam pelo caminho; e os vizinhos o escarnecem.

[[v19-89-42]]

^<<v19-89-42,42>>^ Exaltaste a destra dos seus adversários e deste regozijo a todos os seus inimigos.

[[v19-89-43]]

^<<v19-89-43,43>>^ Também viraste o fio da sua espada e não o sustentaste na batalha.

[[v19-89-44]]

^<<v19-89-44,44>>^ Fizeste cessar o seu esplendor e deitaste por terra o seu trono.

[[v19-89-45]]

^<<v19-89-45,45>>^ Abreviaste os dias da sua mocidade e o cobriste de ignomínia.

[[v19-89-46]]

^<<v19-89-46,46>>^ Até quando, SENHOR? Esconder-te-ás para sempre? Arderá a tua ira como fogo?

[[v19-89-47]]

^<<v19-89-47,47>>^ Lembra-te de como é breve a minha existência! Pois criarias em vão todos os filhos dos homens!

[[v19-89-48]]

^<<v19-89-48,48>>^ Que homem há, que viva e não veja a morte? Ou que livre a sua alma das garras do sepulcro?

[[v19-89-49]]

^<<v19-89-49,49>>^ Que é feito, Senhor, das tuas benignidades de outrora, juradas a Davi por tua fidelidade?

[[v19-89-50]]

^<<v19-89-50,50>>^ Lembra-te, Senhor, do opróbrio dos teus servos e de como trago no peito a injúria de muitos povos,

[[v19-89-51]]

^<<v19-89-51,51>>^ com que, SENHOR, os teus inimigos têm vilipendiado, sim, vilipendiado os passos do teu ungido.

[[v19-89-52]]

^<<v19-89-52,52>>^ Bendito seja o SENHOR para sempre! Amém e amém!

'''

xref:019-salmos/019-salmos-088.adoc#v19-88-0[&#60; Capítulo Anterior] | <<v19-89-0,Topo>> | xref:019-salmos/019-salmos-090.adoc#v19-90-0[Próximo Capítulo &#62;]