include::./index.adoc[]

[[v19-16-0]]
=== Salmos, 16
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-16-1]]

^<<v19-16-1,1>>^ Guarda-me, ó Deus, porque em ti me refugio.

[[v19-16-2]]

^<<v19-16-2,2>>^ Digo ao SENHOR: Tu és o meu Senhor; outro bem não possuo, senão a ti somente.

[[v19-16-3]]

^<<v19-16-3,3>>^ Quanto aos santos que há na terra, são eles os notáveis nos quais tenho todo o meu prazer.

[[v19-16-4]]

^<<v19-16-4,4>>^ Muitas serão as penas dos que trocam o SENHOR por outros deuses; não oferecerei as suas libações de sangue, e os meus lábios não pronunciarão o seu nome.

[[v19-16-5]]

^<<v19-16-5,5>>^ O SENHOR é a porção da minha herança e o meu cálice; tu és o arrimo da minha sorte.

[[v19-16-6]]

^<<v19-16-6,6>>^ Caem-me as divisas em lugares amenos, é mui linda a minha herança.

[[v19-16-7]]

^<<v19-16-7,7>>^ Bendigo o SENHOR, que me aconselha; pois até durante a noite o meu coração me ensina.

[[v19-16-8]]

^<<v19-16-8,8>>^ O SENHOR, tenho-o sempre à minha presença; estando ele à minha direita, não serei abalado.

[[v19-16-9]]

^<<v19-16-9,9>>^ Alegra-se, pois, o meu coração, e o meu espírito exulta; até o meu corpo repousará seguro.

[[v19-16-10]]

^<<v19-16-10,10>>^ Pois não deixarás a minha alma na morte, nem permitirás que o teu Santo veja corrupção.

[[v19-16-11]]

^<<v19-16-11,11>>^ Tu me farás ver os caminhos da vida; na tua presença há plenitude de alegria, na tua destra, delícias perpetuamente.

'''

xref:019-salmos/019-salmos-015.adoc#v19-15-0[&#60; Capítulo Anterior] | <<v19-16-0,Topo>> | xref:019-salmos/019-salmos-017.adoc#v19-17-0[Próximo Capítulo &#62;]