include::./index.adoc[]

[[v19-83-0]]
=== Salmos, 83
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-83-1]]

^<<v19-83-1,1>>^ Ó Deus, não te cales; não te emudeças, nem fiques inativo, ó Deus!

[[v19-83-2]]

^<<v19-83-2,2>>^ Os teus inimigos se alvoroçam, e os que te odeiam levantam a cabeça.

[[v19-83-3]]

^<<v19-83-3,3>>^ Tramam astutamente contra o teu povo e conspiram contra os teus protegidos.

[[v19-83-4]]

^<<v19-83-4,4>>^ Dizem: Vinde, risquemo-los de entre as nações; e não haja mais memória do nome de Israel.

[[v19-83-5]]

^<<v19-83-5,5>>^ Pois tramam concordemente e firmam aliança contra ti

[[v19-83-6]]

^<<v19-83-6,6>>^ as tendas de Edom e os ismaelitas, Moabe e os hagarenos,

[[v19-83-7]]

^<<v19-83-7,7>>^ Gebal, Amom e Amaleque, a Filístia como os habitantes de Tiro;

[[v19-83-8]]

^<<v19-83-8,8>>^ também a Assíria se alia com eles, e se constituem braço forte aos filhos de Ló.

[[v19-83-9]]

^<<v19-83-9,9>>^ Faze-lhes como fizeste a Midiã, como a Sísera, como a Jabim na ribeira de Quisom;

[[v19-83-10]]

^<<v19-83-10,10>>^ os quais pereceram em En-Dor; tornaram-se adubo para a terra.

[[v19-83-11]]

^<<v19-83-11,11>>^ Sejam os seus nobres como Orebe e como Zeebe, e os seus príncipes, como Zeba e como Zalmuna,

[[v19-83-12]]

^<<v19-83-12,12>>^ que disseram: Apoderemo-nos das habitações de Deus.

[[v19-83-13]]

^<<v19-83-13,13>>^ Deus meu, faze-os como folhas impelidas por um remoinho, como a palha ao léu do vento.

[[v19-83-14]]

^<<v19-83-14,14>>^ Como o fogo devora um bosque e a chama abrasa os montes,

[[v19-83-15]]

^<<v19-83-15,15>>^ assim, persegue-os com a tua tempestade e amedronta-os com o teu vendaval.

[[v19-83-16]]

^<<v19-83-16,16>>^ Enche-lhes o rosto de ignomínia, para que busquem o teu nome, SENHOR.

[[v19-83-17]]

^<<v19-83-17,17>>^ Sejam envergonhados e confundidos perpetuamente; perturbem-se e pereçam.

[[v19-83-18]]

^<<v19-83-18,18>>^ E reconhecerão que só tu, cujo nome é SENHOR, és o Altíssimo sobre toda a terra.

'''

xref:019-salmos/019-salmos-082.adoc#v19-82-0[&#60; Capítulo Anterior] | <<v19-83-0,Topo>> | xref:019-salmos/019-salmos-084.adoc#v19-84-0[Próximo Capítulo &#62;]