include::./index.adoc[]

[[v19-81-0]]
=== Salmos, 81
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-81-1]]

^<<v19-81-1,1>>^ Cantai de júbilo a Deus, força nossa; celebrai o Deus de Jacó.

[[v19-81-2]]

^<<v19-81-2,2>>^ Salmodiai e fazei soar o tamboril, a suave harpa com o saltério.

[[v19-81-3]]

^<<v19-81-3,3>>^ Tocai a trombeta na Festa da Lua Nova, na lua cheia, dia da nossa festa.

[[v19-81-4]]

^<<v19-81-4,4>>^ É preceito para Israel, é prescrição do Deus de Jacó.

[[v19-81-5]]

^<<v19-81-5,5>>^ Ele o ordenou, como lei, a José, ao sair contra a terra do Egito. Ouço uma linguagem que eu não conhecera.

[[v19-81-6]]

^<<v19-81-6,6>>^ Livrei os seus ombros do peso, e suas mãos foram livres dos cestos.

[[v19-81-7]]

^<<v19-81-7,7>>^ Clamaste na angústia, e te livrei; do recôndito do trovão eu te respondi e te experimentei junto às águas de Meribá.

[[v19-81-8]]

^<<v19-81-8,8>>^ Ouve, povo meu, quero exortar-te. Ó Israel, se me escutasses!

[[v19-81-9]]

^<<v19-81-9,9>>^ Não haja no meio de ti deus alheio, nem te prostres ante deus estranho.

[[v19-81-10]]

^<<v19-81-10,10>>^ Eu sou o SENHOR, teu Deus, que te tirei da terra do Egito. Abre bem a boca, e ta encherei.

[[v19-81-11]]

^<<v19-81-11,11>>^ Mas o meu povo não me quis escutar a voz, e Israel não me atendeu.

[[v19-81-12]]

^<<v19-81-12,12>>^ Assim, deixei-o andar na teimosia do seu coração; siga os seus próprios conselhos.

[[v19-81-13]]

^<<v19-81-13,13>>^ Ah! Se o meu povo me escutasse, se Israel andasse nos meus caminhos!

[[v19-81-14]]

^<<v19-81-14,14>>^ Eu, de pronto, lhe abateria o inimigo e deitaria mão contra os seus adversários.

[[v19-81-15]]

^<<v19-81-15,15>>^ Os que aborrecem ao SENHOR se lhe submeteriam, e isto duraria para sempre.

[[v19-81-16]]

^<<v19-81-16,16>>^ Eu o sustentaria com o trigo mais fino e o saciaria com o mel que escorre da rocha.

'''

xref:019-salmos/019-salmos-080.adoc#v19-80-0[&#60; Capítulo Anterior] | <<v19-81-0,Topo>> | xref:019-salmos/019-salmos-082.adoc#v19-82-0[Próximo Capítulo &#62;]