include::./index.adoc[]

[[v19-66-0]]
=== Salmos, 66
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-66-1]]

^<<v19-66-1,1>>^ Aclamai a Deus, toda a terra.

[[v19-66-2]]

^<<v19-66-2,2>>^ Salmodiai a glória do seu nome, dai glória ao seu louvor.

[[v19-66-3]]

^<<v19-66-3,3>>^ Dizei a Deus: Que tremendos são os teus feitos! Pela grandeza do teu poder, a ti se mostram submissos os teus inimigos.

[[v19-66-4]]

^<<v19-66-4,4>>^ Prostra-se toda a terra perante ti, canta salmos a ti; salmodia o teu nome.

[[v19-66-5]]

^<<v19-66-5,5>>^ Vinde e vede as obras de Deus: tremendos feitos para com os filhos dos homens!

[[v19-66-6]]

^<<v19-66-6,6>>^ Converteu o mar em terra seca; atravessaram o rio a pé; ali, nos alegramos nele.

[[v19-66-7]]

^<<v19-66-7,7>>^ Ele, em seu poder, governa eternamente; os seus olhos vigiam as nações; não se exaltem os rebeldes.

[[v19-66-8]]

^<<v19-66-8,8>>^ Bendizei, ó povos, o nosso Deus; fazei ouvir a voz do seu louvor;

[[v19-66-9]]

^<<v19-66-9,9>>^ o que preserva com vida a nossa alma e não permite que nos resvalem os pés.

[[v19-66-10]]

^<<v19-66-10,10>>^ Pois tu, ó Deus, nos provaste; acrisolaste-nos como se acrisola a prata.

[[v19-66-11]]

^<<v19-66-11,11>>^ Tu nos deixaste cair na armadilha; oprimiste as nossas costas;

[[v19-66-12]]

^<<v19-66-12,12>>^ fizeste que os homens cavalgassem sobre a nossa cabeça; passamos pelo fogo e pela água; porém, afinal, nos trouxeste para um lugar espaçoso.

[[v19-66-13]]

^<<v19-66-13,13>>^ Entrarei na tua casa com holocaustos; pagar-te-ei os meus votos,

[[v19-66-14]]

^<<v19-66-14,14>>^ que proferiram os meus lábios, e que, no dia da angústia, prometeu a minha boca.

[[v19-66-15]]

^<<v19-66-15,15>>^ Oferecer-te-ei holocaustos de vítimas cevadas, com aroma de carneiros; imolarei novilhos com cabritos.

[[v19-66-16]]

^<<v19-66-16,16>>^ Vinde, ouvi, todos vós que temeis a Deus, e vos contarei o que tem ele feito por minha alma.

[[v19-66-17]]

^<<v19-66-17,17>>^ A ele clamei com a boca, com a língua o exaltei.

[[v19-66-18]]

^<<v19-66-18,18>>^ Se eu no coração contemplara a vaidade, o Senhor não me teria ouvido.

[[v19-66-19]]

^<<v19-66-19,19>>^ Entretanto, Deus me tem ouvido e me tem atendido a voz da oração.

[[v19-66-20]]

^<<v19-66-20,20>>^ Bendito seja Deus, que não me rejeita a oração, nem aparta de mim a sua graça.

'''

xref:019-salmos/019-salmos-065.adoc#v19-65-0[&#60; Capítulo Anterior] | <<v19-66-0,Topo>> | xref:019-salmos/019-salmos-067.adoc#v19-67-0[Próximo Capítulo &#62;]