include::./index.adoc[]

[[v19-44-0]]
=== Salmos, 44
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-44-1]]

^<<v19-44-1,1>>^ Ouvimos, ó Deus, com os próprios ouvidos; nossos pais nos têm contado o que outrora fizeste, em seus dias.

[[v19-44-2]]

^<<v19-44-2,2>>^ Como por tuas próprias mãos desapossaste as nações e os estabeleceste; oprimiste os povos e aos pais deste largueza.

[[v19-44-3]]

^<<v19-44-3,3>>^ Pois não foi por sua espada que possuíram a terra, nem foi o seu braço que lhes deu vitória, e sim a tua destra, e o teu braço, e o fulgor do teu rosto, porque te agradaste deles.

[[v19-44-4]]

^<<v19-44-4,4>>^ Tu és o meu rei, ó Deus; ordena a vitória de Jacó.

[[v19-44-5]]

^<<v19-44-5,5>>^ Com o teu auxílio, vencemos os nossos inimigos; em teu nome, calcamos aos pés os que se levantam contra nós.

[[v19-44-6]]

^<<v19-44-6,6>>^ Não confio no meu arco, e não é a minha espada que me salva.

[[v19-44-7]]

^<<v19-44-7,7>>^ Pois tu nos salvaste dos nossos inimigos e cobriste de vergonha os que nos odeiam.

[[v19-44-8]]

^<<v19-44-8,8>>^ Em Deus, nos temos gloriado continuamente e para sempre louvaremos o teu nome.

[[v19-44-9]]

^<<v19-44-9,9>>^ Agora, porém, tu nos lançaste fora, e nos expuseste à vergonha, e já não sais com os nossos exércitos.

[[v19-44-10]]

^<<v19-44-10,10>>^ Tu nos fazes bater em retirada à vista dos nossos inimigos, e os que nos odeiam nos tomam por seu despojo.

[[v19-44-11]]

^<<v19-44-11,11>>^ Entregaste-nos como ovelhas para o corte e nos espalhaste entre as nações.

[[v19-44-12]]

^<<v19-44-12,12>>^ Vendes por um nada o teu povo e nada lucras com o seu preço.

[[v19-44-13]]

^<<v19-44-13,13>>^ Tu nos fazes opróbrio dos nossos vizinhos, escárnio e zombaria aos que nos rodeiam.

[[v19-44-14]]

^<<v19-44-14,14>>^ Pões-nos por ditado entre as nações, alvo de meneios de cabeça entre os povos.

[[v19-44-15]]

^<<v19-44-15,15>>^ A minha ignomínia está sempre diante de mim; cobre-se de vergonha o meu rosto,

[[v19-44-16]]

^<<v19-44-16,16>>^ ante os gritos do que afronta e blasfema, à vista do inimigo e do vingador.

[[v19-44-17]]

^<<v19-44-17,17>>^ Tudo isso nos sobreveio; entretanto, não nos esquecemos de ti, nem fomos infiéis à tua aliança.

[[v19-44-18]]

^<<v19-44-18,18>>^ Não tornou atrás o nosso coração, nem se desviaram os nossos passos dos teus caminhos,

[[v19-44-19]]

^<<v19-44-19,19>>^ para nos esmagares onde vivem os chacais e nos envolveres com as sombras da morte.

[[v19-44-20]]

^<<v19-44-20,20>>^ Se tivéssemos esquecido o nome do nosso Deus ou tivéssemos estendido as mãos a deus estranho,

[[v19-44-21]]

^<<v19-44-21,21>>^ porventura, não o teria atinado Deus, ele, que conhece os segredos dos corações?

[[v19-44-22]]

^<<v19-44-22,22>>^ Mas, por amor de ti, somos entregues à morte continuamente, somos considerados como ovelhas para o matadouro.

[[v19-44-23]]

^<<v19-44-23,23>>^ Desperta! Por que dormes, Senhor? Desperta! Não nos rejeites para sempre!

[[v19-44-24]]

^<<v19-44-24,24>>^ Por que escondes a face e te esqueces da nossa miséria e da nossa opressão?

[[v19-44-25]]

^<<v19-44-25,25>>^ Pois a nossa alma está abatida até ao pó, e o nosso corpo, como que pegado no chão.

[[v19-44-26]]

^<<v19-44-26,26>>^ Levanta-te para socorrer-nos e resgata-nos por amor da tua benignidade.

'''

xref:019-salmos/019-salmos-043.adoc#v19-43-0[&#60; Capítulo Anterior] | <<v19-44-0,Topo>> | xref:019-salmos/019-salmos-045.adoc#v19-45-0[Próximo Capítulo &#62;]