include::./index.adoc[]

[[v19-99-0]]
=== Salmos, 99
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-99-1]]

^<<v19-99-1,1>>^ Reina o SENHOR; tremam os povos. Ele está entronizado acima dos querubins; abale-se a terra.

[[v19-99-2]]

^<<v19-99-2,2>>^ O SENHOR é grande em Sião e sobremodo elevado acima de todos os povos.

[[v19-99-3]]

^<<v19-99-3,3>>^ Celebrem eles o teu nome grande e tremendo, porque é santo.

[[v19-99-4]]

^<<v19-99-4,4>>^ És rei poderoso que ama a justiça; tu firmas a equidade, executas o juízo e a justiça em Jacó.

[[v19-99-5]]

^<<v19-99-5,5>>^ Exaltai ao SENHOR, nosso Deus, e prostrai-vos ante o escabelo de seus pés, porque ele é santo.

[[v19-99-6]]

^<<v19-99-6,6>>^ Moisés e Arão, entre os seus sacerdotes, e, Samuel, entre os que lhe invocam o nome, clamavam ao SENHOR, e ele os ouvia.

[[v19-99-7]]

^<<v19-99-7,7>>^ Falava-lhes na coluna de nuvem; eles guardavam os seus mandamentos e a lei que lhes tinha dado.

[[v19-99-8]]

^<<v19-99-8,8>>^ Tu lhes respondeste, ó SENHOR, nosso Deus; foste para eles Deus perdoador, ainda que tomando vingança dos seus feitos.

[[v19-99-9]]

^<<v19-99-9,9>>^ Exaltai ao SENHOR, nosso Deus, e prostrai-vos ante o seu santo monte, porque santo é o SENHOR, nosso Deus.

'''

xref:019-salmos/019-salmos-098.adoc#v19-98-0[&#60; Capítulo Anterior] | <<v19-99-0,Topo>> | xref:019-salmos/019-salmos-100.adoc#v19-100-0[Próximo Capítulo &#62;]