include::./index.adoc[]

[[v19-91-0]]
=== Salmos, 91
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-91-1]]

^<<v19-91-1,1>>^ O que habita no esconderijo do Altíssimo e descansa à sombra do Onipotente

[[v19-91-2]]

^<<v19-91-2,2>>^ diz ao SENHOR: Meu refúgio e meu baluarte, Deus meu, em quem confio.

[[v19-91-3]]

^<<v19-91-3,3>>^ Pois ele te livrará do laço do passarinheiro e da peste perniciosa.

[[v19-91-4]]

^<<v19-91-4,4>>^ Cobrir-te-á com as suas penas, e, sob suas asas, estarás seguro; a sua verdade é pavês e escudo.

[[v19-91-5]]

^<<v19-91-5,5>>^ Não te assustarás do terror noturno, nem da seta que voa de dia,

[[v19-91-6]]

^<<v19-91-6,6>>^ nem da peste que se propaga nas trevas, nem da mortandade que assola ao meio-dia.

[[v19-91-7]]

^<<v19-91-7,7>>^ Caiam mil ao teu lado, e dez mil, à tua direita; tu não serás atingido.

[[v19-91-8]]

^<<v19-91-8,8>>^ Somente com os teus olhos contemplarás e verás o castigo dos ímpios.

[[v19-91-9]]

^<<v19-91-9,9>>^ Pois disseste: O SENHOR é o meu refúgio. Fizeste do Altíssimo a tua morada.

[[v19-91-10]]

^<<v19-91-10,10>>^ Nenhum mal te sucederá, praga nenhuma chegará à tua tenda.

[[v19-91-11]]

^<<v19-91-11,11>>^ Porque aos seus anjos dará ordens a teu respeito, para que te guardem em todos os teus caminhos.

[[v19-91-12]]

^<<v19-91-12,12>>^ Eles te sustentarão nas suas mãos, para não tropeçares nalguma pedra.

[[v19-91-13]]

^<<v19-91-13,13>>^ Pisarás o leão e a áspide, calcarás aos pés o leãozinho e a serpente.

[[v19-91-14]]

^<<v19-91-14,14>>^ Porque a mim se apegou com amor, eu o livrarei; pô-lo-ei a salvo, porque conhece o meu nome.

[[v19-91-15]]

^<<v19-91-15,15>>^ Ele me invocará, e eu lhe responderei; na sua angústia eu estarei com ele, livrá-lo-ei e o glorificarei.

[[v19-91-16]]

^<<v19-91-16,16>>^ Saciá-lo-ei com longevidade e lhe mostrarei a minha salvação.

'''

xref:019-salmos/019-salmos-090.adoc#v19-90-0[&#60; Capítulo Anterior] | <<v19-91-0,Topo>> | xref:019-salmos/019-salmos-092.adoc#v19-92-0[Próximo Capítulo &#62;]