include::./index.adoc[]

[[v19-37-0]]
=== Salmos, 37
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-37-1]]

^<<v19-37-1,1>>^ Não te indignes por causa dos malfeitores, nem tenhas inveja dos que praticam a iniquidade.

[[v19-37-2]]

^<<v19-37-2,2>>^ Pois eles dentro em breve definharão como a relva e murcharão como a erva verde.

[[v19-37-3]]

^<<v19-37-3,3>>^ Confia no SENHOR e faze o bem; habita na terra e alimenta-te da verdade.

[[v19-37-4]]

^<<v19-37-4,4>>^ Agrada-te do SENHOR, e ele satisfará os desejos do teu coração.

[[v19-37-5]]

^<<v19-37-5,5>>^ Entrega o teu caminho ao SENHOR, confia nele, e o mais ele fará.

[[v19-37-6]]

^<<v19-37-6,6>>^ Fará sobressair a tua justiça como a luz e o teu direito, como o sol ao meio-dia.

[[v19-37-7]]

^<<v19-37-7,7>>^ Descansa no SENHOR e espera nele, não te irrites por causa do homem que prospera em seu caminho, por causa do que leva a cabo os seus maus desígnios.

[[v19-37-8]]

^<<v19-37-8,8>>^ Deixa a ira, abandona o furor; não te impacientes; certamente, isso acabará mal.

[[v19-37-9]]

^<<v19-37-9,9>>^ Porque os malfeitores serão exterminados, mas os que esperam no SENHOR possuirão a terra.

[[v19-37-10]]

^<<v19-37-10,10>>^ Mais um pouco de tempo, e já não existirá o ímpio; procurarás o seu lugar e não o acharás.

[[v19-37-11]]

^<<v19-37-11,11>>^ Mas os mansos herdarão a terra e se deleitarão na abundância de paz.

[[v19-37-12]]

^<<v19-37-12,12>>^ Trama o ímpio contra o justo e contra ele ringe os dentes.

[[v19-37-13]]

^<<v19-37-13,13>>^ Rir-se-á dele o Senhor, pois vê estar-se aproximando o seu dia.

[[v19-37-14]]

^<<v19-37-14,14>>^ Os ímpios arrancam da espada e distendem o arco para abater o pobre e necessitado, para matar os que trilham o reto caminho.

[[v19-37-15]]

^<<v19-37-15,15>>^ A sua espada, porém, lhes traspassará o próprio coração, e os seus arcos serão espedaçados.

[[v19-37-16]]

^<<v19-37-16,16>>^ Mais vale o pouco do justo que a abundância de muitos ímpios.

[[v19-37-17]]

^<<v19-37-17,17>>^ Pois os braços dos ímpios serão quebrados, mas os justos, o SENHOR os sustém.

[[v19-37-18]]

^<<v19-37-18,18>>^ O SENHOR conhece os dias dos íntegros; a herança deles permanecerá para sempre.

[[v19-37-19]]

^<<v19-37-19,19>>^ Não serão envergonhados nos dias do mal e nos dias da fome se fartarão.

[[v19-37-20]]

^<<v19-37-20,20>>^ Os ímpios, no entanto, perecerão, e os inimigos do SENHOR serão como o viço das pastagens; serão aniquilados e se desfarão em fumaça.

[[v19-37-21]]

^<<v19-37-21,21>>^ O ímpio pede emprestado e não paga; o justo, porém, se compadece e dá.

[[v19-37-22]]

^<<v19-37-22,22>>^ Aqueles a quem o SENHOR abençoa possuirão a terra; e serão exterminados aqueles a quem amaldiçoa.

[[v19-37-23]]

^<<v19-37-23,23>>^ O SENHOR firma os passos do homem bom e no seu caminho se compraz;

[[v19-37-24]]

^<<v19-37-24,24>>^ se cair, não ficará prostrado, porque o SENHOR o segura pela mão.

[[v19-37-25]]

^<<v19-37-25,25>>^ Fui moço e já, agora, sou velho, porém jamais vi o justo desamparado, nem a sua descendência a mendigar o pão.

[[v19-37-26]]

^<<v19-37-26,26>>^ É sempre compassivo e empresta, e a sua descendência será uma bênção.

[[v19-37-27]]

^<<v19-37-27,27>>^ Aparta-te do mal e faze o bem, e será perpétua a tua morada.

[[v19-37-28]]

^<<v19-37-28,28>>^ Pois o SENHOR ama a justiça e não desampara os seus santos; serão preservados para sempre, mas a descendência dos ímpios será exterminada.

[[v19-37-29]]

^<<v19-37-29,29>>^ Os justos herdarão a terra e nela habitarão para sempre.

[[v19-37-30]]

^<<v19-37-30,30>>^ A boca do justo profere a sabedoria, e a sua língua fala o que é justo.

[[v19-37-31]]

^<<v19-37-31,31>>^ No coração, tem ele a lei do seu Deus; os seus passos não vacilarão.

[[v19-37-32]]

^<<v19-37-32,32>>^ O perverso espreita ao justo e procura tirar-lhe a vida.

[[v19-37-33]]

^<<v19-37-33,33>>^ Mas o SENHOR não o deixará nas suas mãos, nem o condenará quando for julgado.

[[v19-37-34]]

^<<v19-37-34,34>>^ Espera no SENHOR, segue o seu caminho, e ele te exaltará para possuíres a terra; presenciarás isso quando os ímpios forem exterminados.

[[v19-37-35]]

^<<v19-37-35,35>>^ Vi um ímpio prepotente a expandir-se qual cedro do Líbano.

[[v19-37-36]]

^<<v19-37-36,36>>^ Passei, e eis que desaparecera; procurei-o, e já não foi encontrado.

[[v19-37-37]]

^<<v19-37-37,37>>^ Observa o homem íntegro e atenta no que é reto; porquanto o homem de paz terá posteridade.

[[v19-37-38]]

^<<v19-37-38,38>>^ Quanto aos transgressores, serão, à uma, destruídos; a descendência dos ímpios será exterminada.

[[v19-37-39]]

^<<v19-37-39,39>>^ Vem do SENHOR a salvação dos justos; ele é a sua fortaleza no dia da tribulação.

[[v19-37-40]]

^<<v19-37-40,40>>^ O SENHOR os ajuda e os livra; livra-os dos ímpios e os salva, porque nele buscam refúgio.

'''

xref:019-salmos/019-salmos-036.adoc#v19-36-0[&#60; Capítulo Anterior] | <<v19-37-0,Topo>> | xref:019-salmos/019-salmos-038.adoc#v19-38-0[Próximo Capítulo &#62;]