include::./index.adoc[]

[[v19-41-0]]
=== Salmos, 41
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-41-1]]

^<<v19-41-1,1>>^ Bem-aventurado o que acode ao necessitado; o SENHOR o livra no dia do mal.

[[v19-41-2]]

^<<v19-41-2,2>>^ O SENHOR o protege, preserva-lhe a vida e o faz feliz na terra; não o entrega à discrição dos seus inimigos.

[[v19-41-3]]

^<<v19-41-3,3>>^ O SENHOR o assiste no leito da enfermidade; na doença, tu lhe afofas a cama.

[[v19-41-4]]

^<<v19-41-4,4>>^ Disse eu: compadece-te de mim, SENHOR; sara a minha alma, porque pequei contra ti.

[[v19-41-5]]

^<<v19-41-5,5>>^ Os meus inimigos falam mal de mim: Quando morrerá e lhe perecerá o nome?

[[v19-41-6]]

^<<v19-41-6,6>>^ Se algum deles me vem visitar, diz coisas vãs, amontoando no coração malícias; em saindo, é disso que fala.

[[v19-41-7]]

^<<v19-41-7,7>>^ De mim rosnam à uma todos os que me odeiam; engendram males contra mim, dizendo:

[[v19-41-8]]

^<<v19-41-8,8>>^ Peste maligna deu nele, e: Caiu de cama, já não há de levantar-se.

[[v19-41-9]]

^<<v19-41-9,9>>^ Até o meu amigo íntimo, em quem eu confiava, que comia do meu pão, levantou contra mim o calcanhar.

[[v19-41-10]]

^<<v19-41-10,10>>^ Tu, porém, SENHOR, compadece-te de mim e levanta-me, para que eu lhes pague segundo merecem.

[[v19-41-11]]

^<<v19-41-11,11>>^ Com isto conheço que tu te agradas de mim: em não triunfar contra mim o meu inimigo.

[[v19-41-12]]

^<<v19-41-12,12>>^ Quanto a mim, tu me susténs na minha integridade e me pões à tua presença para sempre.

[[v19-41-13]]

^<<v19-41-13,13>>^ Bendito seja o SENHOR, Deus de Israel, da eternidade para a eternidade! Amém e amém!

'''

xref:019-salmos/019-salmos-040.adoc#v19-40-0[&#60; Capítulo Anterior] | <<v19-41-0,Topo>> | xref:019-salmos/019-salmos-042.adoc#v19-42-0[Próximo Capítulo &#62;]