include::./index.adoc[]

[[v19-118-0]]
=== Salmos, 118
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-118-1]]

^<<v19-118-1,1>>^ Rendei graças ao SENHOR, porque ele é bom, porque a sua misericórdia dura para sempre.

[[v19-118-2]]

^<<v19-118-2,2>>^ Diga, pois, Israel: Sim, a sua misericórdia dura para sempre.

[[v19-118-3]]

^<<v19-118-3,3>>^ Diga, pois, a casa de Arão: Sim, a sua misericórdia dura para sempre.

[[v19-118-4]]

^<<v19-118-4,4>>^ Digam, pois, os que temem ao SENHOR: Sim, a sua misericórdia dura para sempre.

[[v19-118-5]]

^<<v19-118-5,5>>^ Em meio à tribulação, invoquei o SENHOR, e o SENHOR me ouviu e me deu folga.

[[v19-118-6]]

^<<v19-118-6,6>>^ O SENHOR está comigo; não temerei. Que me poderá fazer o homem?

[[v19-118-7]]

^<<v19-118-7,7>>^ O SENHOR está comigo entre os que me ajudam; por isso, verei cumprido o meu desejo nos que me odeiam.

[[v19-118-8]]

^<<v19-118-8,8>>^ Melhor é buscar refúgio no Senhor do que confiar no homem.

[[v19-118-9]]

^<<v19-118-9,9>>^ Melhor é buscar refúgio no Senhor do que confiar em príncipes.

[[v19-118-10]]

^<<v19-118-10,10>>^ Todas as nações me cercaram, mas em nome do SENHOR as destruí.

[[v19-118-11]]

^<<v19-118-11,11>>^ Cercaram-me, cercaram-me de todos os lados; mas em nome do SENHOR as destruí.

[[v19-118-12]]

^<<v19-118-12,12>>^ Como abelhas me cercaram, porém como fogo em espinhos foram queimadas; em nome do SENHOR as destruí.

[[v19-118-13]]

^<<v19-118-13,13>>^ Empurraram-me violentamente para me fazer cair, porém o SENHOR me amparou.

[[v19-118-14]]

^<<v19-118-14,14>>^ O SENHOR é a minha força e o meu cântico, porque ele me salvou.

[[v19-118-15]]

^<<v19-118-15,15>>^ Nas tendas dos justos há voz de júbilo e de salvação; a destra do SENHOR faz proezas.

[[v19-118-16]]

^<<v19-118-16,16>>^ A destra do SENHOR se eleva, a destra do SENHOR faz proezas.

[[v19-118-17]]

^<<v19-118-17,17>>^ Não morrerei; antes, viverei e contarei as obras do SENHOR.

[[v19-118-18]]

^<<v19-118-18,18>>^ O SENHOR me castigou severamente, mas não me entregou à morte.

[[v19-118-19]]

^<<v19-118-19,19>>^ Abri-me as portas da justiça; entrarei por elas e renderei graças ao SENHOR.

[[v19-118-20]]

^<<v19-118-20,20>>^ Esta é a porta do SENHOR; por ela entrarão os justos.

[[v19-118-21]]

^<<v19-118-21,21>>^ Render-te-ei graças porque me acudiste e foste a minha salvação.

[[v19-118-22]]

^<<v19-118-22,22>>^ A pedra que os construtores rejeitaram, essa veio a ser a principal pedra, angular;

[[v19-118-23]]

^<<v19-118-23,23>>^ isto procede do Senhor e é maravilhoso aos nossos olhos.

[[v19-118-24]]

^<<v19-118-24,24>>^ Este é o dia que o SENHOR fez; regozijemo-nos e alegremo-nos nele.

[[v19-118-25]]

^<<v19-118-25,25>>^ Oh! Salva-nos, SENHOR, nós te pedimos; oh! SENHOR, concede-nos prosperidade!

[[v19-118-26]]

^<<v19-118-26,26>>^ Bendito o que vem em nome do SENHOR. A vós outros da Casa do SENHOR, nós vos abençoamos.

[[v19-118-27]]

^<<v19-118-27,27>>^ O SENHOR é Deus, ele é a nossa luz; adornai a festa com ramos até às pontas do altar.

[[v19-118-28]]

^<<v19-118-28,28>>^ Tu és o meu Deus, render-te-ei graças; tu és o meu Deus, quero exaltar-te.

[[v19-118-29]]

^<<v19-118-29,29>>^ Rendei graças ao SENHOR, porque ele é bom, porque a sua misericórdia dura para sempre.

'''

xref:019-salmos/019-salmos-117.adoc#v19-117-0[&#60; Capítulo Anterior] | <<v19-118-0,Topo>> | xref:019-salmos/019-salmos-119.adoc#v19-119-0[Próximo Capítulo &#62;]