include::./index.adoc[]

[[v19-4-0]]
=== Salmos, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-4-1]]

^<<v19-4-1,1>>^ Responde-me quando clamo, ó Deus da minha justiça; na angústia, me tens aliviado; tem misericórdia de mim e ouve a minha oração.

[[v19-4-2]]

^<<v19-4-2,2>>^ Ó homens, até quando tornareis a minha glória em vexame, e amareis a vaidade, e buscareis a mentira?

[[v19-4-3]]

^<<v19-4-3,3>>^ Sabei, porém, que o SENHOR distingue para si o piedoso; o SENHOR me ouve quando eu clamo por ele.

[[v19-4-4]]

^<<v19-4-4,4>>^ Irai-vos e não pequeis; consultai no travesseiro o coração e sossegai.

[[v19-4-5]]

^<<v19-4-5,5>>^ Oferecei sacrifícios de justiça e confiai no SENHOR.

[[v19-4-6]]

^<<v19-4-6,6>>^ Há muitos que dizem: Quem nos dará a conhecer o bem? SENHOR, levanta sobre nós a luz do teu rosto.

[[v19-4-7]]

^<<v19-4-7,7>>^ Mais alegria me puseste no coração do que a alegria deles, quando lhes há fartura de cereal e de vinho.

[[v19-4-8]]

^<<v19-4-8,8>>^ Em paz me deito e logo pego no sono, porque, SENHOR, só tu me fazes repousar seguro.

'''

xref:019-salmos/019-salmos-003.adoc#v19-3-0[&#60; Capítulo Anterior] | <<v19-4-0,Topo>> | xref:019-salmos/019-salmos-005.adoc#v19-5-0[Próximo Capítulo &#62;]