include::./index.adoc[]

[[v19-116-0]]
=== Salmos, 116
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-116-1]]

^<<v19-116-1,1>>^ Amo o SENHOR, porque ele ouve a minha voz e as minhas súplicas.

[[v19-116-2]]

^<<v19-116-2,2>>^ Porque inclinou para mim os seus ouvidos, invocá-lo-ei enquanto eu viver.

[[v19-116-3]]

^<<v19-116-3,3>>^ Laços de morte me cercaram, e angústias do inferno se apoderaram de mim; caí em tribulação e tristeza.

[[v19-116-4]]

^<<v19-116-4,4>>^ Então, invoquei o nome do SENHOR: ó SENHOR, livra-me a alma.

[[v19-116-5]]

^<<v19-116-5,5>>^ Compassivo e justo é o SENHOR; o nosso Deus é misericordioso.

[[v19-116-6]]

^<<v19-116-6,6>>^ O SENHOR vela pelos simples; achava-me prostrado, e ele me salvou.

[[v19-116-7]]

^<<v19-116-7,7>>^ Volta, minha alma, ao teu sossego, pois o SENHOR tem sido generoso para contigo.

[[v19-116-8]]

^<<v19-116-8,8>>^ Pois livraste da morte a minha alma, das lágrimas, os meus olhos, da queda, os meus pés.

[[v19-116-9]]

^<<v19-116-9,9>>^ Andarei na presença do SENHOR, na terra dos viventes.

[[v19-116-10]]

^<<v19-116-10,10>>^ Eu cria, ainda que disse: estive sobremodo aflito.

[[v19-116-11]]

^<<v19-116-11,11>>^ Eu disse na minha perturbação: todo homem é mentiroso.

[[v19-116-12]]

^<<v19-116-12,12>>^ Que darei ao Senhor por todos os seus benefícios para comigo?

[[v19-116-13]]

^<<v19-116-13,13>>^ Tomarei o cálice da salvação e invocarei o nome do SENHOR.

[[v19-116-14]]

^<<v19-116-14,14>>^ Cumprirei os meus votos ao SENHOR, na presença de todo o seu povo.

[[v19-116-15]]

^<<v19-116-15,15>>^ Preciosa é aos olhos do Senhor a morte dos seus santos.

[[v19-116-16]]

^<<v19-116-16,16>>^ SENHOR, deveras sou teu servo, teu servo, filho da tua serva; quebraste as minhas cadeias.

[[v19-116-17]]

^<<v19-116-17,17>>^ Oferecer-te-ei sacrifícios de ações de graças e invocarei o nome do SENHOR.

[[v19-116-18]]

^<<v19-116-18,18>>^ Cumprirei os meus votos ao SENHOR, na presença de todo o seu povo,

[[v19-116-19]]

^<<v19-116-19,19>>^ nos átrios da Casa do SENHOR, no meio de ti, ó Jerusalém. Aleluia!

'''

xref:019-salmos/019-salmos-115.adoc#v19-115-0[&#60; Capítulo Anterior] | <<v19-116-0,Topo>> | xref:019-salmos/019-salmos-117.adoc#v19-117-0[Próximo Capítulo &#62;]