include::./index.adoc[]

[[v19-24-0]]
=== Salmos, 24
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-24-1]]

^<<v19-24-1,1>>^ Ao SENHOR pertence a terra e tudo o que nela se contém, o mundo e os que nele habitam.

[[v19-24-2]]

^<<v19-24-2,2>>^ Fundou-a ele sobre os mares e sobre as correntes a estabeleceu.

[[v19-24-3]]

^<<v19-24-3,3>>^ Quem subirá ao monte do SENHOR? Quem há de permanecer no seu santo lugar?

[[v19-24-4]]

^<<v19-24-4,4>>^ O que é limpo de mãos e puro de coração, que não entrega a sua alma à falsidade, nem jura dolosamente.

[[v19-24-5]]

^<<v19-24-5,5>>^ Este obterá do SENHOR a bênção e a justiça do Deus da sua salvação.

[[v19-24-6]]

^<<v19-24-6,6>>^ Tal é a geração dos que o buscam, dos que buscam a face do Deus de Jacó.

[[v19-24-7]]

^<<v19-24-7,7>>^ Levantai, ó portas, as vossas cabeças; levantai-vos, ó portais eternos, para que entre o Rei da Glória.

[[v19-24-8]]

^<<v19-24-8,8>>^ Quem é o Rei da Glória? O SENHOR, forte e poderoso, o SENHOR, poderoso nas batalhas.

[[v19-24-9]]

^<<v19-24-9,9>>^ Levantai, ó portas, as vossas cabeças; levantai-vos, ó portais eternos, para que entre o Rei da Glória.

[[v19-24-10]]

^<<v19-24-10,10>>^ Quem é esse Rei da Glória? O SENHOR dos Exércitos, ele é o Rei da Glória.

'''

xref:019-salmos/019-salmos-023.adoc#v19-23-0[&#60; Capítulo Anterior] | <<v19-24-0,Topo>> | xref:019-salmos/019-salmos-025.adoc#v19-25-0[Próximo Capítulo &#62;]