include::./index.adoc[]

[[v19-137-0]]
=== Salmos, 137
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-137-1]]

^<<v19-137-1,1>>^ Às margens dos rios da Babilônia, nós nos assentávamos e chorávamos, lembrando-nos de Sião.

[[v19-137-2]]

^<<v19-137-2,2>>^ Nos salgueiros que lá havia, pendurávamos as nossas harpas,

[[v19-137-3]]

^<<v19-137-3,3>>^ pois aqueles que nos levaram cativos nos pediam canções, e os nossos opressores, que fôssemos alegres, dizendo: Entoai-nos algum dos cânticos de Sião.

[[v19-137-4]]

^<<v19-137-4,4>>^ Como, porém, haveríamos de entoar o canto do Senhor em terra estranha?

[[v19-137-5]]

^<<v19-137-5,5>>^ Se eu de ti me esquecer, ó Jerusalém, que se resseque a minha mão direita.

[[v19-137-6]]

^<<v19-137-6,6>>^ Apegue-se-me a língua ao paladar, se me não lembrar de ti, se não preferir eu Jerusalém à minha maior alegria.

[[v19-137-7]]

^<<v19-137-7,7>>^ Contra os filhos de Edom, lembra-te, SENHOR, do dia de Jerusalém, pois diziam: Arrasai, arrasai-a, até aos fundamentos.

[[v19-137-8]]

^<<v19-137-8,8>>^ Filha da Babilônia, que hás de ser destruída, feliz aquele que te der o pago do mal que nos fizeste.

[[v19-137-9]]

^<<v19-137-9,9>>^ Feliz aquele que pegar teus filhos e esmagá-los contra a pedra.

'''

xref:019-salmos/019-salmos-136.adoc#v19-136-0[&#60; Capítulo Anterior] | <<v19-137-0,Topo>> | xref:019-salmos/019-salmos-138.adoc#v19-138-0[Próximo Capítulo &#62;]