include::./index.adoc[]

[[v19-5-0]]
=== Salmos, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-5-1]]

^<<v19-5-1,1>>^ Dá ouvidos, SENHOR, às minhas palavras e acode ao meu gemido.

[[v19-5-2]]

^<<v19-5-2,2>>^ Escuta, Rei meu e Deus meu, a minha voz que clama, pois a ti é que imploro.

[[v19-5-3]]

^<<v19-5-3,3>>^ De manhã, SENHOR, ouves a minha voz; de manhã te apresento a minha oração e fico esperando.

[[v19-5-4]]

^<<v19-5-4,4>>^ Pois tu não és Deus que se agrade com a iniquidade, e contigo não subsiste o mal.

[[v19-5-5]]

^<<v19-5-5,5>>^ Os arrogantes não permanecerão à tua vista; aborreces a todos os que praticam a iniquidade.

[[v19-5-6]]

^<<v19-5-6,6>>^ Tu destróis os que proferem mentira; o SENHOR abomina ao sanguinário e ao fraudulento;

[[v19-5-7]]

^<<v19-5-7,7>>^ porém eu, pela riqueza da tua misericórdia, entrarei na tua casa e me prostrarei diante do teu santo templo, no teu temor.

[[v19-5-8]]

^<<v19-5-8,8>>^ SENHOR, guia-me na tua justiça, por causa dos meus adversários; endireita diante de mim o teu caminho;

[[v19-5-9]]

^<<v19-5-9,9>>^ pois não têm eles sinceridade nos seus lábios; o seu íntimo é todo crimes; a sua garganta é sepulcro aberto, e com a língua lisonjeiam.

[[v19-5-10]]

^<<v19-5-10,10>>^ Declara-os culpados, ó Deus; caiam por seus próprios planos. Rejeita-os por causa de suas muitas transgressões, pois se rebelaram contra ti.

[[v19-5-11]]

^<<v19-5-11,11>>^ Mas regozijem-se todos os que confiam em ti; folguem de júbilo para sempre, porque tu os defendes; e em ti se gloriem os que amam o teu nome.

[[v19-5-12]]

^<<v19-5-12,12>>^ Pois tu, SENHOR, abençoas o justo e, como escudo, o cercas da tua benevolência.

'''

xref:019-salmos/019-salmos-004.adoc#v19-4-0[&#60; Capítulo Anterior] | <<v19-5-0,Topo>> | xref:019-salmos/019-salmos-006.adoc#v19-6-0[Próximo Capítulo &#62;]