include::./index.adoc[]

[[v19-62-0]]
=== Salmos, 62
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-62-1]]

^<<v19-62-1,1>>^ Somente em Deus, ó minha alma, espera silenciosa; dele vem a minha salvação.

[[v19-62-2]]

^<<v19-62-2,2>>^ Só ele é a minha rocha, e a minha salvação, e o meu alto refúgio; não serei muito abalado.

[[v19-62-3]]

^<<v19-62-3,3>>^ Até quando acometereis vós a um homem, todos vós, para o derribardes, como se fosse uma parede pendida ou um muro prestes a cair?

[[v19-62-4]]

^<<v19-62-4,4>>^ Só pensam em derribá-lo da sua dignidade; na mentira se comprazem; de boca bendizem, porém no interior maldizem.

[[v19-62-5]]

^<<v19-62-5,5>>^ Somente em Deus, ó minha alma, espera silenciosa, porque dele vem a minha esperança.

[[v19-62-6]]

^<<v19-62-6,6>>^ Só ele é a minha rocha, e a minha salvação, e o meu alto refúgio; não serei jamais abalado.

[[v19-62-7]]

^<<v19-62-7,7>>^ De Deus dependem a minha salvação e a minha glória; estão em Deus a minha forte rocha e o meu refúgio.

[[v19-62-8]]

^<<v19-62-8,8>>^ Confiai nele, ó povo, em todo tempo; derramai perante ele o vosso coração; Deus é o nosso refúgio.

[[v19-62-9]]

^<<v19-62-9,9>>^ Somente vaidade são os homens plebeus; falsidade, os de fina estirpe; pesados em balança, eles juntos são mais leves que a vaidade.

[[v19-62-10]]

^<<v19-62-10,10>>^ Não confieis naquilo que extorquis, nem vos vanglorieis na rapina; se as vossas riquezas prosperam, não ponhais nelas o coração.

[[v19-62-11]]

^<<v19-62-11,11>>^ Uma vez falou Deus, duas vezes ouvi isto: Que o poder pertence a Deus,

[[v19-62-12]]

^<<v19-62-12,12>>^ e a ti, Senhor, pertence a graça, pois a cada um retribuis segundo as suas obras.

'''

xref:019-salmos/019-salmos-061.adoc#v19-61-0[&#60; Capítulo Anterior] | <<v19-62-0,Topo>> | xref:019-salmos/019-salmos-063.adoc#v19-63-0[Próximo Capítulo &#62;]