include::./index.adoc[]

[[v19-73-0]]
=== Salmos, 73
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-73-1]]

^<<v19-73-1,1>>^ Com efeito, Deus é bom para com Israel, para com os de coração limpo.

[[v19-73-2]]

^<<v19-73-2,2>>^ Quanto a mim, porém, quase me resvalaram os pés; pouco faltou para que se desviassem os meus passos.

[[v19-73-3]]

^<<v19-73-3,3>>^ Pois eu invejava os arrogantes, ao ver a prosperidade dos perversos.

[[v19-73-4]]

^<<v19-73-4,4>>^ Para eles não há preocupações, o seu corpo é sadio e nédio.

[[v19-73-5]]

^<<v19-73-5,5>>^ Não partilham das canseiras dos mortais, nem são afligidos como os outros homens.

[[v19-73-6]]

^<<v19-73-6,6>>^ Daí, a soberba que os cinge como um colar, e a violência que os envolve como manto.

[[v19-73-7]]

^<<v19-73-7,7>>^ Os olhos saltam-lhes da gordura; do coração brotam-lhes fantasias.

[[v19-73-8]]

^<<v19-73-8,8>>^ Motejam e falam maliciosamente; da opressão falam com altivez.

[[v19-73-9]]

^<<v19-73-9,9>>^ Contra os céus desandam a boca, e a sua língua percorre a terra.

[[v19-73-10]]

^<<v19-73-10,10>>^ Por isso, o seu povo se volta para eles e os tem por fonte de que bebe a largos sorvos.

[[v19-73-11]]

^<<v19-73-11,11>>^ E diz: Como sabe Deus? Acaso, há conhecimento no Altíssimo?

[[v19-73-12]]

^<<v19-73-12,12>>^ Eis que são estes os ímpios; e, sempre tranquilos, aumentam suas riquezas.

[[v19-73-13]]

^<<v19-73-13,13>>^ Com efeito, inutilmente conservei puro o coração e lavei as mãos na inocência.

[[v19-73-14]]

^<<v19-73-14,14>>^ Pois de contínuo sou afligido e cada manhã, castigado.

[[v19-73-15]]

^<<v19-73-15,15>>^ Se eu pensara em falar tais palavras, já aí teria traído a geração de teus filhos.

[[v19-73-16]]

^<<v19-73-16,16>>^ Em só refletir para compreender isso, achei mui pesada tarefa para mim;

[[v19-73-17]]

^<<v19-73-17,17>>^ até que entrei no santuário de Deus e atinei com o fim deles.

[[v19-73-18]]

^<<v19-73-18,18>>^ Tu certamente os pões em lugares escorregadios e os fazes cair na destruição.

[[v19-73-19]]

^<<v19-73-19,19>>^ Como ficam de súbito assolados, totalmente aniquilados de terror!

[[v19-73-20]]

^<<v19-73-20,20>>^ Como ao sonho, quando se acorda, assim, ó Senhor, ao despertares, desprezarás a imagem deles.

[[v19-73-21]]

^<<v19-73-21,21>>^ Quando o coração se me amargou e as entranhas se me comoveram,

[[v19-73-22]]

^<<v19-73-22,22>>^ eu estava embrutecido e ignorante; era como um irracional à tua presença.

[[v19-73-23]]

^<<v19-73-23,23>>^ Todavia, estou sempre contigo, tu me seguras pela minha mão direita.

[[v19-73-24]]

^<<v19-73-24,24>>^ Tu me guias com o teu conselho e depois me recebes na glória.

[[v19-73-25]]

^<<v19-73-25,25>>^ Quem mais tenho eu no céu? Não há outro em quem eu me compraza na terra.

[[v19-73-26]]

^<<v19-73-26,26>>^ Ainda que a minha carne e o meu coração desfaleçam, Deus é a fortaleza do meu coração e a minha herança para sempre.

[[v19-73-27]]

^<<v19-73-27,27>>^ Os que se afastam de ti, eis que perecem; tu destróis todos os que são infiéis para contigo.

[[v19-73-28]]

^<<v19-73-28,28>>^ Quanto a mim, bom é estar junto a Deus; no SENHOR Deus ponho o meu refúgio, para proclamar todos os seus feitos.

'''

xref:019-salmos/019-salmos-072.adoc#v19-72-0[&#60; Capítulo Anterior] | <<v19-73-0,Topo>> | xref:019-salmos/019-salmos-074.adoc#v19-74-0[Próximo Capítulo &#62;]