include::./index.adoc[]

[[v19-58-0]]
=== Salmos, 58
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-58-1]]

^<<v19-58-1,1>>^ Falais verdadeiramente justiça, ó juízes? Julgais com retidão os filhos dos homens?

[[v19-58-2]]

^<<v19-58-2,2>>^ Longe disso; antes, no íntimo engendrais iniquidades e distribuís na terra a violência de vossas mãos.

[[v19-58-3]]

^<<v19-58-3,3>>^ Desviam-se os ímpios desde a sua concepção; nascem e já se desencaminham, proferindo mentiras.

[[v19-58-4]]

^<<v19-58-4,4>>^ Têm peçonha semelhante à peçonha da serpente; são como a víbora surda, que tapa os ouvidos,

[[v19-58-5]]

^<<v19-58-5,5>>^ para não ouvir a voz dos encantadores, do mais fascinante em encantamentos.

[[v19-58-6]]

^<<v19-58-6,6>>^ Ó Deus, quebra-lhes os dentes na boca; arranca, SENHOR, os queixais aos leõezinhos.

[[v19-58-7]]

^<<v19-58-7,7>>^ Desapareçam como águas que se escoam; ao dispararem flechas, fiquem elas embotadas.

[[v19-58-8]]

^<<v19-58-8,8>>^ Sejam como a lesma, que passa diluindo-se; como o aborto de mulher, não vejam nunca o sol.

[[v19-58-9]]

^<<v19-58-9,9>>^ Como espinheiros, antes que vossas panelas sintam deles o calor, tanto os verdes como os que estão em brasa serão arrebatados como por um redemoinho.

[[v19-58-10]]

^<<v19-58-10,10>>^ Alegrar-se-á o justo quando vir a vingança; banhará os pés no sangue do ímpio.

[[v19-58-11]]

^<<v19-58-11,11>>^ Então, se dirá: Na verdade, há recompensa para o justo; há um Deus, com efeito, que julga na terra.

'''

xref:019-salmos/019-salmos-057.adoc#v19-57-0[&#60; Capítulo Anterior] | <<v19-58-0,Topo>> | xref:019-salmos/019-salmos-059.adoc#v19-59-0[Próximo Capítulo &#62;]