include::./index.adoc[]

[[v19-79-0]]
=== Salmos, 79
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-79-1]]

^<<v19-79-1,1>>^ Ó Deus, as nações invadiram a tua herança, profanaram o teu santo templo, reduziram Jerusalém a um montão de ruínas.

[[v19-79-2]]

^<<v19-79-2,2>>^ Deram os cadáveres dos teus servos por cibo às aves dos céus e a carne dos teus santos, às feras da terra.

[[v19-79-3]]

^<<v19-79-3,3>>^ Derramaram como água o sangue deles ao redor de Jerusalém, e não houve quem lhes desse sepultura.

[[v19-79-4]]

^<<v19-79-4,4>>^ Tornamo-nos o opróbrio dos nossos vizinhos, o escárnio e a zombaria dos que nos rodeiam.

[[v19-79-5]]

^<<v19-79-5,5>>^ Até quando, SENHOR? Será para sempre a tua ira? Arderá como fogo o teu zelo?

[[v19-79-6]]

^<<v19-79-6,6>>^ Derrama o teu furor sobre as nações que te não conhecem e sobre os reinos que não invocam o teu nome.

[[v19-79-7]]

^<<v19-79-7,7>>^ Porque eles devoraram a Jacó e lhe assolaram as moradas.

[[v19-79-8]]

^<<v19-79-8,8>>^ Não recordes contra nós as iniquidades de nossos pais; apressem-se ao nosso encontro as tuas misericórdias, pois estamos sobremodo abatidos.

[[v19-79-9]]

^<<v19-79-9,9>>^ Assiste-nos, ó Deus e Salvador nosso, pela glória do teu nome; livra-nos e perdoa-nos os pecados, por amor do teu nome.

[[v19-79-10]]

^<<v19-79-10,10>>^ Por que diriam as nações: Onde está o seu Deus? Seja, à nossa vista, manifesta entre as nações a vingança do sangue que dos teus servos é derramado.

[[v19-79-11]]

^<<v19-79-11,11>>^ Chegue à tua presença o gemido do cativo; consoante a grandeza do teu poder, preserva os sentenciados à morte.

[[v19-79-12]]

^<<v19-79-12,12>>^ Retribui, Senhor, aos nossos vizinhos, sete vezes tanto, o opróbrio com que te vituperaram.

[[v19-79-13]]

^<<v19-79-13,13>>^ Quanto a nós, teu povo e ovelhas do teu pasto, para sempre te daremos graças; de geração em geração proclamaremos os teus louvores.

'''

xref:019-salmos/019-salmos-078.adoc#v19-78-0[&#60; Capítulo Anterior] | <<v19-79-0,Topo>> | xref:019-salmos/019-salmos-080.adoc#v19-80-0[Próximo Capítulo &#62;]