include::./index.adoc[]

[[v19-19-0]]
=== Salmos, 19
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-19-1]]

^<<v19-19-1,1>>^ Os céus proclamam a glória de Deus, e o firmamento anuncia as obras das suas mãos.

[[v19-19-2]]

^<<v19-19-2,2>>^ Um dia discursa a outro dia, e uma noite revela conhecimento a outra noite.

[[v19-19-3]]

^<<v19-19-3,3>>^ Não há linguagem, nem há palavras, e deles não se ouve nenhum som;

[[v19-19-4]]

^<<v19-19-4,4>>^ no entanto, por toda a terra se faz ouvir a sua voz, e as suas palavras, até aos confins do mundo. Aí, pôs uma tenda para o sol,

[[v19-19-5]]

^<<v19-19-5,5>>^ o qual, como noivo que sai dos seus aposentos, se regozija como herói, a percorrer o seu caminho.

[[v19-19-6]]

^<<v19-19-6,6>>^ Principia numa extremidade dos céus, e até à outra vai o seu percurso; e nada refoge ao seu calor.

[[v19-19-7]]

^<<v19-19-7,7>>^ A lei do SENHOR é perfeita e restaura a alma; o testemunho do SENHOR é fiel e dá sabedoria aos símplices.

[[v19-19-8]]

^<<v19-19-8,8>>^ Os preceitos do SENHOR são retos e alegram o coração; o mandamento do SENHOR é puro e ilumina os olhos.

[[v19-19-9]]

^<<v19-19-9,9>>^ O temor do SENHOR é límpido e permanece para sempre; os juízos do SENHOR são verdadeiros e todos igualmente, justos.

[[v19-19-10]]

^<<v19-19-10,10>>^ São mais desejáveis do que ouro, mais do que muito ouro depurado; e são mais doces do que o mel e o destilar dos favos.

[[v19-19-11]]

^<<v19-19-11,11>>^ Além disso, por eles se admoesta o teu servo; em os guardar, há grande recompensa.

[[v19-19-12]]

^<<v19-19-12,12>>^ Quem há que possa discernir as próprias faltas? Absolve-me das que me são ocultas.

[[v19-19-13]]

^<<v19-19-13,13>>^ Também da soberba guarda o teu servo, que ela não me domine; então, serei irrepreensível e ficarei livre de grande transgressão.

[[v19-19-14]]

^<<v19-19-14,14>>^ As palavras dos meus lábios e o meditar do meu coração sejam agradáveis na tua presença, SENHOR, rocha minha e redentor meu!

'''

xref:019-salmos/019-salmos-018.adoc#v19-18-0[&#60; Capítulo Anterior] | <<v19-19-0,Topo>> | xref:019-salmos/019-salmos-020.adoc#v19-20-0[Próximo Capítulo &#62;]