include::./index.adoc[]

[[v19-97-0]]
=== Salmos, 97
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-97-1]]

^<<v19-97-1,1>>^ Reina o SENHOR. Regozije-se a terra, alegrem-se as muitas ilhas.

[[v19-97-2]]

^<<v19-97-2,2>>^ Nuvens e escuridão o rodeiam, justiça e juízo são a base do seu trono.

[[v19-97-3]]

^<<v19-97-3,3>>^ Adiante dele vai um fogo que lhe consome os inimigos em redor.

[[v19-97-4]]

^<<v19-97-4,4>>^ Os seus relâmpagos alumiam o mundo; a terra os vê e estremece.

[[v19-97-5]]

^<<v19-97-5,5>>^ Derretem-se como cera os montes, na presença do SENHOR, na presença do Senhor de toda a terra.

[[v19-97-6]]

^<<v19-97-6,6>>^ Os céus anunciam a sua justiça, e todos os povos veem a sua glória.

[[v19-97-7]]

^<<v19-97-7,7>>^ Sejam confundidos todos os que servem a imagens de escultura, os que se gloriam de ídolos; prostrem-se diante dele todos os deuses.

[[v19-97-8]]

^<<v19-97-8,8>>^ Sião ouve e se alegra, as filhas de Judá se regozijam, por causa da tua justiça, ó SENHOR.

[[v19-97-9]]

^<<v19-97-9,9>>^ Pois tu, SENHOR, és o Altíssimo sobre toda a terra; tu és sobremodo elevado acima de todos os deuses.

[[v19-97-10]]

^<<v19-97-10,10>>^ Vós que amais o SENHOR, detestai o mal; ele guarda a alma dos seus santos, livra-os da mão dos ímpios.

[[v19-97-11]]

^<<v19-97-11,11>>^ A luz difunde-se para o justo, e a alegria, para os retos de coração.

[[v19-97-12]]

^<<v19-97-12,12>>^ Alegrai-vos no SENHOR, ó justos, e dai louvores ao seu santo nome.

'''

xref:019-salmos/019-salmos-096.adoc#v19-96-0[&#60; Capítulo Anterior] | <<v19-97-0,Topo>> | xref:019-salmos/019-salmos-098.adoc#v19-98-0[Próximo Capítulo &#62;]