include::./index.adoc[]

[[v19-33-0]]
=== Salmos, 33
// ara ?, ARA - Almeida Revista e Atualizada

[[v19-33-1]]

^<<v19-33-1,1>>^ Exultai, ó justos, no SENHOR! Aos retos fica bem louvá-lo.

[[v19-33-2]]

^<<v19-33-2,2>>^ Celebrai o SENHOR com harpa, louvai-o com cânticos no saltério de dez cordas.

[[v19-33-3]]

^<<v19-33-3,3>>^ Entoai-lhe novo cântico, tangei com arte e com júbilo.

[[v19-33-4]]

^<<v19-33-4,4>>^ Porque a palavra do SENHOR é reta, e todo o seu proceder é fiel.

[[v19-33-5]]

^<<v19-33-5,5>>^ Ele ama a justiça e o direito; a terra está cheia da bondade do SENHOR.

[[v19-33-6]]

^<<v19-33-6,6>>^ Os céus por sua palavra se fizeram, e, pelo sopro de sua boca, o exército deles.

[[v19-33-7]]

^<<v19-33-7,7>>^ Ele ajunta em montão as águas do mar; e em reservatório encerra as grandes vagas.

[[v19-33-8]]

^<<v19-33-8,8>>^ Tema ao SENHOR toda a terra, temam-no todos os habitantes do mundo.

[[v19-33-9]]

^<<v19-33-9,9>>^ Pois ele falou, e tudo se fez; ele ordenou, e tudo passou a existir.

[[v19-33-10]]

^<<v19-33-10,10>>^ O SENHOR frustra os desígnios das nações e anula os intentos dos povos.

[[v19-33-11]]

^<<v19-33-11,11>>^ O conselho do SENHOR dura para sempre; os desígnios do seu coração, por todas as gerações.

[[v19-33-12]]

^<<v19-33-12,12>>^ Feliz a nação cujo Deus é o SENHOR, e o povo que ele escolheu para sua herança.

[[v19-33-13]]

^<<v19-33-13,13>>^ O SENHOR olha dos céus; vê todos os filhos dos homens;

[[v19-33-14]]

^<<v19-33-14,14>>^ do lugar de sua morada, observa todos os moradores da terra,

[[v19-33-15]]

^<<v19-33-15,15>>^ ele, que forma o coração de todos eles, que contempla todas as suas obras.

[[v19-33-16]]

^<<v19-33-16,16>>^ Não há rei que se salve com o poder dos seus exércitos; nem por sua muita força se livra o valente.

[[v19-33-17]]

^<<v19-33-17,17>>^ O cavalo não garante vitória; a despeito de sua grande força, a ninguém pode livrar.

[[v19-33-18]]

^<<v19-33-18,18>>^ Eis que os olhos do SENHOR estão sobre os que o temem, sobre os que esperam na sua misericórdia,

[[v19-33-19]]

^<<v19-33-19,19>>^ para livrar-lhes a alma da morte, e, no tempo da fome, conservar-lhes a vida.

[[v19-33-20]]

^<<v19-33-20,20>>^ Nossa alma espera no SENHOR, nosso auxílio e escudo.

[[v19-33-21]]

^<<v19-33-21,21>>^ Nele, o nosso coração se alegra, pois confiamos no seu santo nome.

[[v19-33-22]]

^<<v19-33-22,22>>^ Seja sobre nós, SENHOR, a tua misericórdia, como de ti esperamos.

'''

xref:019-salmos/019-salmos-032.adoc#v19-32-0[&#60; Capítulo Anterior] | <<v19-33-0,Topo>> | xref:019-salmos/019-salmos-034.adoc#v19-34-0[Próximo Capítulo &#62;]