include::./index.adoc[]

[[v55-3-0]]
=== 2 Timóteo, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v55-3-1]]

^<<v55-3-1,1>>^ Sabe, porém, isto: nos últimos dias, sobrevirão tempos difíceis,

[[v55-3-2]]

^<<v55-3-2,2>>^ pois os homens serão egoístas, avarentos, jactanciosos, arrogantes, blasfemadores, desobedientes aos pais, ingratos, irreverentes,

[[v55-3-3]]

^<<v55-3-3,3>>^ desafeiçoados, implacáveis, caluniadores, sem domínio de si, cruéis, inimigos do bem,

[[v55-3-4]]

^<<v55-3-4,4>>^ traidores, atrevidos, enfatuados, mais amigos dos prazeres que amigos de Deus,

[[v55-3-5]]

^<<v55-3-5,5>>^ tendo forma de piedade, negando-lhe, entretanto, o poder. Foge também destes.

[[v55-3-6]]

^<<v55-3-6,6>>^ Pois entre estes se encontram os que penetram sorrateiramente nas casas e conseguem cativar mulherinhas sobrecarregadas de pecados, conduzidas de várias paixões,

[[v55-3-7]]

^<<v55-3-7,7>>^ que aprendem sempre e jamais podem chegar ao conhecimento da verdade.

[[v55-3-8]]

^<<v55-3-8,8>>^ E, do modo por que Janes e Jambres resistiram a Moisés, também estes resistem à verdade. São homens de todo corrompidos na mente, réprobos quanto à fé;

[[v55-3-9]]

^<<v55-3-9,9>>^ eles, todavia, não irão avante; porque a sua insensatez será a todos evidente, como também aconteceu com a daqueles.

[[v55-3-10]]

^<<v55-3-10,10>>^ Tu, porém, tens seguido, de perto, o meu ensino, procedimento, propósito, fé, longanimidade, amor, perseverança,

[[v55-3-11]]

^<<v55-3-11,11>>^ as minhas perseguições e os meus sofrimentos, quais me aconteceram em Antioquia, Icônio e Listra, — que variadas perseguições tenho suportado! De todas, entretanto, me livrou o Senhor.

[[v55-3-12]]

^<<v55-3-12,12>>^ Ora, todos quantos querem viver piedosamente em Cristo Jesus serão perseguidos.

[[v55-3-13]]

^<<v55-3-13,13>>^ Mas os homens perversos e impostores irão de mal a pior, enganando e sendo enganados.

[[v55-3-14]]

^<<v55-3-14,14>>^ Tu, porém, permanece naquilo que aprendeste e de que foste inteirado, sabendo de quem o aprendeste

[[v55-3-15]]

^<<v55-3-15,15>>^ e que, desde a infância, sabes as sagradas letras, que podem tornar-te sábio para a salvação pela fé em Cristo Jesus.

[[v55-3-16]]

^<<v55-3-16,16>>^ Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção, para a educação na justiça,

[[v55-3-17]]

^<<v55-3-17,17>>^ a fim de que o homem de Deus seja perfeito e perfeitamente habilitado para toda boa obra.

'''

xref:055-2-timoteo/055-2-timoteo-002.adoc#v55-2-0[&#60; Capítulo Anterior] | <<v55-3-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-004.adoc#v55-4-0[Próximo Capítulo &#62;]