include::./index.adoc[]

[[v55-4-0]]
=== 2 Timóteo, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v55-4-1]]

^<<v55-4-1,1>>^ Conjuro-te, perante Deus e Cristo Jesus, que há de julgar vivos e mortos, pela sua manifestação e pelo seu reino:

[[v55-4-2]]

^<<v55-4-2,2>>^ prega a palavra, insta, quer seja oportuno, quer não, corrige, repreende, exorta com toda a longanimidade e doutrina.

[[v55-4-3]]

^<<v55-4-3,3>>^ Pois haverá tempo em que não suportarão a sã doutrina; pelo contrário, cercar-se-ão de mestres segundo as suas próprias cobiças, como que sentindo coceira nos ouvidos;

[[v55-4-4]]

^<<v55-4-4,4>>^ e se recusarão a dar ouvidos à verdade, entregando-se às fábulas.

[[v55-4-5]]

^<<v55-4-5,5>>^ Tu, porém, sê sóbrio em todas as coisas, suporta as aflições, faze o trabalho de um evangelista, cumpre cabalmente o teu ministério.

[[v55-4-6]]

^<<v55-4-6,6>>^ Quanto a mim, estou sendo já oferecido por libação, e o tempo da minha partida é chegado.

[[v55-4-7]]

^<<v55-4-7,7>>^ Combati o bom combate, completei a carreira, guardei a fé.

[[v55-4-8]]

^<<v55-4-8,8>>^ Já agora a coroa da justiça me está guardada, a qual o Senhor, reto juiz, me dará naquele Dia; e não somente a mim, mas também a todos quantos amam a sua vinda.

[[v55-4-9]]

^<<v55-4-9,9>>^ Procura vir ter comigo depressa.

[[v55-4-10]]

^<<v55-4-10,10>>^ Porque Demas, tendo amado o presente século, me abandonou e se foi para Tessalônica; Crescente foi para a Galácia, Tito, para a Dalmácia.

[[v55-4-11]]

^<<v55-4-11,11>>^ Somente Lucas está comigo. Toma contigo Marcos e traze-o, pois me é útil para o ministério.

[[v55-4-12]]

^<<v55-4-12,12>>^ Quanto a Tíquico, mandei-o até Éfeso.

[[v55-4-13]]

^<<v55-4-13,13>>^ Quando vieres, traze a capa que deixei em Trôade, em casa de Carpo, bem como os livros, especialmente os pergaminhos.

[[v55-4-14]]

^<<v55-4-14,14>>^ Alexandre, o latoeiro, causou-me muitos males; o Senhor lhe dará a paga segundo as suas obras.

[[v55-4-15]]

^<<v55-4-15,15>>^ Tu, guarda-te também dele, porque resistiu fortemente às nossas palavras.

[[v55-4-16]]

^<<v55-4-16,16>>^ Na minha primeira defesa, ninguém foi a meu favor; antes, todos me abandonaram. Que isto não lhes seja posto em conta!

[[v55-4-17]]

^<<v55-4-17,17>>^ Mas o Senhor me assistiu e me revestiu de forças, para que, por meu intermédio, a pregação fosse plenamente cumprida, e todos os gentios a ouvissem; e fui libertado da boca do leão.

[[v55-4-18]]

^<<v55-4-18,18>>^ O Senhor me livrará também de toda obra maligna e me levará salvo para o seu reino celestial. A ele, glória pelos séculos dos séculos. Amém!

[[v55-4-19]]

^<<v55-4-19,19>>^ Saúda Prisca, e Áquila, e a casa de Onesíforo.

[[v55-4-20]]

^<<v55-4-20,20>>^ Erasto ficou em Corinto. Quanto a Trófimo, deixei-o doente em Mileto.

[[v55-4-21]]

^<<v55-4-21,21>>^ Apressa-te a vir antes do inverno. Êubulo te envia saudações; o mesmo fazem Prudente, Lino, Cláudia e os irmãos todos.

[[v55-4-22]]

^<<v55-4-22,22>>^ O Senhor seja com o teu espírito. A graça seja convosco.

'''

xref:055-2-timoteo/055-2-timoteo-003.adoc#v55-3-0[&#60; Capítulo Anterior] | <<v55-4-0,Topo>> | xref:056-tito/056-tito-001.adoc#v56-1-0[Próximo Capítulo &#62;]