include::./index.adoc[]

[[v55-2-0]]
=== 2 Timóteo, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v55-2-1]]

^<<v55-2-1,1>>^ Tu, pois, filho meu, fortifica-te na graça que está em Cristo Jesus.

[[v55-2-2]]

^<<v55-2-2,2>>^ E o que de minha parte ouviste através de muitas testemunhas, isso mesmo transmite a homens fiéis e também idôneos para instruir a outros.

[[v55-2-3]]

^<<v55-2-3,3>>^ Participa dos meus sofrimentos como bom soldado de Cristo Jesus.

[[v55-2-4]]

^<<v55-2-4,4>>^ Nenhum soldado em serviço se envolve em negócios desta vida, porque o seu objetivo é satisfazer àquele que o arregimentou.

[[v55-2-5]]

^<<v55-2-5,5>>^ Igualmente, o atleta não é coroado se não lutar segundo as normas.

[[v55-2-6]]

^<<v55-2-6,6>>^ O lavrador que trabalha deve ser o primeiro a participar dos frutos.

[[v55-2-7]]

^<<v55-2-7,7>>^ Pondera o que acabo de dizer, porque o Senhor te dará compreensão em todas as coisas.

[[v55-2-8]]

^<<v55-2-8,8>>^ Lembra-te de Jesus Cristo, ressuscitado de entre os mortos, descendente de Davi, segundo o meu evangelho;

[[v55-2-9]]

^<<v55-2-9,9>>^ pelo qual estou sofrendo até algemas, como malfeitor; contudo, a palavra de Deus não está algemada.

[[v55-2-10]]

^<<v55-2-10,10>>^ Por esta razão, tudo suporto por causa dos eleitos, para que também eles obtenham a salvação que está em Cristo Jesus, com eterna glória.

[[v55-2-11]]

^<<v55-2-11,11>>^ Fiel é esta palavra: Se já morremos com ele, também viveremos com ele;

[[v55-2-12]]

^<<v55-2-12,12>>^ se perseveramos, também com ele reinaremos; se o negamos, ele, por sua vez, nos negará;

[[v55-2-13]]

^<<v55-2-13,13>>^ se somos infiéis, ele permanece fiel, pois de maneira nenhuma pode negar-se a si mesmo.

[[v55-2-14]]

^<<v55-2-14,14>>^ Recomenda estas coisas. Dá testemunho solene a todos perante Deus, para que evitem contendas de palavras que para nada aproveitam, exceto para a subversão dos ouvintes.

[[v55-2-15]]

^<<v55-2-15,15>>^ Procura apresentar-te a Deus aprovado, como obreiro que não tem de que se envergonhar, que maneja bem a palavra da verdade.

[[v55-2-16]]

^<<v55-2-16,16>>^ Evita, igualmente, os falatórios inúteis e profanos, pois os que deles usam passarão a impiedade ainda maior.

[[v55-2-17]]

^<<v55-2-17,17>>^ Além disso, a linguagem deles corrói como câncer; entre os quais se incluem Himeneu e Fileto.

[[v55-2-18]]

^<<v55-2-18,18>>^ Estes se desviaram da verdade, asseverando que a ressurreição já se realizou, e estão pervertendo a fé a alguns.

[[v55-2-19]]

^<<v55-2-19,19>>^ Entretanto, o firme fundamento de Deus permanece, tendo este selo: O Senhor conhece os que lhe pertencem. E mais: Aparte-se da injustiça todo aquele que professa o nome do Senhor.

[[v55-2-20]]

^<<v55-2-20,20>>^ Ora, numa grande casa não há somente utensílios de ouro e de prata; há também de madeira e de barro. Alguns, para honra; outros, porém, para desonra.

[[v55-2-21]]

^<<v55-2-21,21>>^ Assim, pois, se alguém a si mesmo se purificar destes erros, será utensílio para honra, santificado e útil ao seu possuidor, estando preparado para toda boa obra.

[[v55-2-22]]

^<<v55-2-22,22>>^ Foge, outrossim, das paixões da mocidade. Segue a justiça, a fé, o amor e a paz com os que, de coração puro, invocam o Senhor.

[[v55-2-23]]

^<<v55-2-23,23>>^ E repele as questões insensatas e absurdas, pois sabes que só engendram contendas.

[[v55-2-24]]

^<<v55-2-24,24>>^ Ora, é necessário que o servo do Senhor não viva a contender, e sim deve ser brando para com todos, apto para instruir, paciente,

[[v55-2-25]]

^<<v55-2-25,25>>^ disciplinando com mansidão os que se opõem, na expectativa de que Deus lhes conceda não só o arrependimento para conhecerem plenamente a verdade,

[[v55-2-26]]

^<<v55-2-26,26>>^ mas também o retorno à sensatez, livrando-se eles dos laços do diabo, tendo sido feitos cativos por ele para cumprirem a sua vontade.

'''

xref:055-2-timoteo/055-2-timoteo-001.adoc#v55-1-0[&#60; Capítulo Anterior] | <<v55-2-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-003.adoc#v55-3-0[Próximo Capítulo &#62;]