include::./index.adoc[]

[[v55-1-0]]
=== 2 Timóteo, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v55-1-1]]

^<<v55-1-1,1>>^ Paulo, apóstolo de Cristo Jesus, pela vontade de Deus, de conformidade com a promessa da vida que está em Cristo Jesus,

[[v55-1-2]]

^<<v55-1-2,2>>^ ao amado filho Timóteo, graça, misericórdia e paz, da parte de Deus Pai e de Cristo Jesus, nosso Senhor.

[[v55-1-3]]

^<<v55-1-3,3>>^ Dou graças a Deus, a quem, desde os meus antepassados, sirvo com consciência pura, porque, sem cessar, me lembro de ti nas minhas orações, noite e dia.

[[v55-1-4]]

^<<v55-1-4,4>>^ Lembrado das tuas lágrimas, estou ansioso por ver-te, para que eu transborde de alegria

[[v55-1-5]]

^<<v55-1-5,5>>^ pela recordação que guardo de tua fé sem fingimento, a mesma que, primeiramente, habitou em tua avó Loide e em tua mãe Eunice, e estou certo de que também, em ti.

[[v55-1-6]]

^<<v55-1-6,6>>^ Por esta razão, pois, te admoesto que reavives o dom de Deus que há em ti pela imposição das minhas mãos.

[[v55-1-7]]

^<<v55-1-7,7>>^ Porque Deus não nos tem dado espírito de covardia, mas de poder, de amor e de moderação.

[[v55-1-8]]

^<<v55-1-8,8>>^ Não te envergonhes, portanto, do testemunho de nosso Senhor, nem do seu encarcerado, que sou eu; pelo contrário, participa comigo dos sofrimentos, a favor do evangelho, segundo o poder de Deus,

[[v55-1-9]]

^<<v55-1-9,9>>^ que nos salvou e nos chamou com santa vocação; não segundo as nossas obras, mas conforme a sua própria determinação e graça que nos foi dada em Cristo Jesus, antes dos tempos eternos,

[[v55-1-10]]

^<<v55-1-10,10>>^ e manifestada, agora, pelo aparecimento de nosso Salvador Cristo Jesus, o qual não só destruiu a morte, como trouxe à luz a vida e a imortalidade, mediante o evangelho,

[[v55-1-11]]

^<<v55-1-11,11>>^ para o qual eu fui designado pregador, apóstolo e mestre

[[v55-1-12]]

^<<v55-1-12,12>>^ e, por isso, estou sofrendo estas coisas; todavia, não me envergonho, porque sei em quem tenho crido e estou certo de que ele é poderoso para guardar o meu depósito até aquele Dia.

[[v55-1-13]]

^<<v55-1-13,13>>^ Mantém o padrão das sãs palavras que de mim ouviste com fé e com o amor que está em Cristo Jesus.

[[v55-1-14]]

^<<v55-1-14,14>>^ Guarda o bom depósito, mediante o Espírito Santo que habita em nós.

[[v55-1-15]]

^<<v55-1-15,15>>^ Estás ciente de que todos os da Ásia me abandonaram; dentre eles cito Fígelo e Hermógenes.

[[v55-1-16]]

^<<v55-1-16,16>>^ Conceda o Senhor misericórdia à casa de Onesíforo, porque, muitas vezes, me deu ânimo e nunca se envergonhou das minhas algemas;

[[v55-1-17]]

^<<v55-1-17,17>>^ antes, tendo ele chegado a Roma, me procurou solicitamente até me encontrar.

[[v55-1-18]]

^<<v55-1-18,18>>^ O Senhor lhe conceda, naquele Dia, achar misericórdia da parte do Senhor. E tu sabes, melhor do que eu, quantos serviços me prestou ele em Éfeso.

'''

xref:054-1-timoteo/054-1-timoteo-006.adoc#v54-6-0[&#60; Capítulo Anterior] | <<v55-1-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-002.adoc#v55-2-0[Próximo Capítulo &#62;]