include::./index.adoc[]

[[v15-4-0]]
=== Esdras, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v15-4-1]]

^<<v15-4-1,1>>^ Ouvindo os adversários de Judá e Benjamim que os que voltaram do cativeiro edificavam o templo ao SENHOR, Deus de Israel,

[[v15-4-2]]

^<<v15-4-2,2>>^ chegaram-se a Zorobabel e aos cabeças de famílias e lhes disseram: Deixai-nos edificar convosco, porque, como vós, buscaremos a vosso Deus; como também já lhe sacrificamos desde os dias de Esar-Hadom, rei da Assíria, que nos fez subir para aqui.

[[v15-4-3]]

^<<v15-4-3,3>>^ Porém Zorobabel, Jesua e os outros cabeças de famílias lhes responderam: Nada tendes conosco na edificação da casa a nosso Deus; nós mesmos, sozinhos, a edificaremos ao SENHOR, Deus de Israel, como nos ordenou Ciro, rei da Pérsia.

[[v15-4-4]]

^<<v15-4-4,4>>^ Então, as gentes da terra desanimaram o povo de Judá, inquietando-o no edificar;

[[v15-4-5]]

^<<v15-4-5,5>>^ alugaram contra eles conselheiros para frustrarem o seu plano, todos os dias de Ciro, rei da Pérsia, até ao reinado de Dario, rei da Pérsia.

[[v15-4-6]]

^<<v15-4-6,6>>^ No princípio do reinado de Assuero, escreveram uma acusação contra os habitantes de Judá e de Jerusalém.

[[v15-4-7]]

^<<v15-4-7,7>>^ E, nos dias de Artaxerxes, rei da Pérsia, Bislão, Mitredate, Tabeel e os outros seus companheiros lhe escreveram; a carta estava escrita em caracteres aramaicos e na língua siríaca.

[[v15-4-8]]

^<<v15-4-8,8>>^ Reum, o comandante, e Sinsai, o escrivão, escreveram contra Jerusalém uma carta ao rei Artaxerxes.

[[v15-4-9]]

^<<v15-4-9,9>>^ Escreveu Reum, o comandante, e Sinsai, o escrivão, os outros seus companheiros: dinaítas, afarsaquitas, tarpelitas, afarsitas, arquevitas, babilônios, susanquitas, deavitas, elamitas

[[v15-4-10]]

^<<v15-4-10,10>>^ e outros povos, que o grande e afamado Osnapar transportou e que fez habitar na cidade de Samaria, e os outros aquém do Eufrates.

[[v15-4-11]]

^<<v15-4-11,11>>^ Eis o teor da carta endereçada ao rei Artaxerxes:

[[v15-4-12]]

^<<v15-4-12,12>>^ Teus servos, os homens daquém do Eufrates e em tal tempo. Seja do conhecimento do rei que os judeus que subiram de ti vieram a nós a Jerusalém. Eles estão reedificando aquela rebelde e malvada cidade e vão restaurando os seus muros e reparando os seus fundamentos.

[[v15-4-13]]

^<<v15-4-13,13>>^ Saiba ainda o rei que, se aquela cidade se reedificar, e os muros se restaurarem, eles não pagarão os direitos, os impostos e os pedágios e assim causarão prejuízos ao rei.

[[v15-4-14]]

^<<v15-4-14,14>>^ Agora, pois, como somos assalariados do rei e não nos convém ver a desonra dele, por isso, mandamos dar-lhe aviso,

[[v15-4-15]]

^<<v15-4-15,15>>^ a fim de que se busque no Livro das Crônicas de seus pais, e nele achará o rei e saberá que aquela cidade foi rebelde e danosa aos reis e às províncias e que nela tem havido rebeliões, desde tempos antigos; pelo que foi a cidade destruída.

[[v15-4-16]]

^<<v15-4-16,16>>^ Nós, pois, fazemos notório ao rei que, se aquela cidade se reedificar, e os seus muros se restaurarem, sucederá que não terá a posse das terras deste lado do Eufrates.

[[v15-4-17]]

^<<v15-4-17,17>>^ Então, respondeu o rei: A Reum, o comandante, a Sinsai, o escrivão, e a seus companheiros que habitam em Samaria, como aos restantes que estão além do Eufrates: Paz!

[[v15-4-18]]

^<<v15-4-18,18>>^ A carta que nos enviastes foi distintamente lida na minha presença.

[[v15-4-19]]

^<<v15-4-19,19>>^ Ordenando-o eu, buscaram e acharam que, de tempos antigos, aquela cidade se levantou contra os reis, e nela se têm feito rebeliões e motins.

[[v15-4-20]]

^<<v15-4-20,20>>^ Também houve reis poderosos sobre Jerusalém, que dalém do Eufrates dominaram em todo lugar, e se lhes pagaram direitos, impostos e pedágios.

[[v15-4-21]]

^<<v15-4-21,21>>^ Agora, pois, dai ordem a fim de que aqueles homens parem o trabalho e não se edifique aquela cidade, a não ser com autorização minha.

[[v15-4-22]]

^<<v15-4-22,22>>^ Guardai-vos, não sejais remissos nestas coisas. Por que há de crescer o dano em prejuízo dos reis?

[[v15-4-23]]

^<<v15-4-23,23>>^ Depois de lida a cópia da carta do rei Artaxerxes perante Reum, Sinsai, o escrivão, e seus companheiros, foram eles apressadamente a Jerusalém, aos judeus, e, de mão armada, os forçaram a parar com a obra.

[[v15-4-24]]

^<<v15-4-24,24>>^ Cessou, pois, a obra da Casa de Deus, a qual estava em Jerusalém; e isso até ao segundo ano do reinado de Dario, rei da Pérsia.

'''

xref:015-esdras/015-esdras-003.adoc#v15-3-0[&#60; Capítulo Anterior] | <<v15-4-0,Topo>> | xref:015-esdras/015-esdras-005.adoc#v15-5-0[Próximo Capítulo &#62;]