include::./index.adoc[]

[[v15-8-0]]
=== Esdras, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v15-8-1]]

^<<v15-8-1,1>>^ São estes os cabeças de famílias, com as suas genealogias, os que subiram comigo da Babilônia, no reinado do rei Artaxerxes:

[[v15-8-2]]

^<<v15-8-2,2>>^ dos filhos de Fineias, Gérson; dos filhos de Itamar, Daniel; dos filhos de Davi, Hatus;

[[v15-8-3]]

^<<v15-8-3,3>>^ dos filhos de Secanias, dos filhos de Parós, Zacarias, e, com ele, foram registrados cento e cinquenta homens.

[[v15-8-4]]

^<<v15-8-4,4>>^ Dos filhos de Paate-Moabe, Elioenai, filho de Zeraías, e, com ele, duzentos homens.

[[v15-8-5]]

^<<v15-8-5,5>>^ Dos filhos de Secanias, o filho de Jaaziel, e, com ele, trezentos homens.

[[v15-8-6]]

^<<v15-8-6,6>>^ Dos filhos de Adim, Ebede, filho de Jônatas, e, com ele, cinquenta homens.

[[v15-8-7]]

^<<v15-8-7,7>>^ Dos filhos de Elão, Jesaías, filho de Atalias, e, com ele, setenta homens.

[[v15-8-8]]

^<<v15-8-8,8>>^ Dos filhos de Sefatias, Zebadias, filho de Micael, e, com ele, oitenta homens.

[[v15-8-9]]

^<<v15-8-9,9>>^ Dos filhos de Joabe, Obadias, filho de Jeiel, e, com ele, duzentos e dezoito homens.

[[v15-8-10]]

^<<v15-8-10,10>>^ Dos filhos de Bani, Selomite, filho de Josifias, e, com ele, cento e sessenta homens.

[[v15-8-11]]

^<<v15-8-11,11>>^ Dos filhos de Bebai, Zacarias, o filho de Bebai, e, com ele, vinte e oito homens.

[[v15-8-12]]

^<<v15-8-12,12>>^ Dos filhos de Azgade, Joanã, o filho de Hacatã, e, com ele, cento e dez homens.

[[v15-8-13]]

^<<v15-8-13,13>>^ Dos filhos de Adonicão, últimos a chegar, seus nomes eram estes: Elifelete, Jeiel e Semaías, e, com eles, sessenta homens.

[[v15-8-14]]

^<<v15-8-14,14>>^ Dos filhos de Bigvai, Utai e Zabude, e, com eles, setenta homens.

[[v15-8-15]]

^<<v15-8-15,15>>^ Ajuntei-os perto do rio que corre para Aava, onde ficamos acampados três dias. Passando revista ao povo e aos sacerdotes e não tendo achado nenhum dos filhos de Levi,

[[v15-8-16]]

^<<v15-8-16,16>>^ enviei Eliézer, Ariel, Semaías, Elnatã, Jaribe, Elnatã, Natã, Zacarias e Mesulão, os chefes, como também a Joiaribe e a Elnatã, que eram sábios.

[[v15-8-17]]

^<<v15-8-17,17>>^ Enviei-os a Ido, chefe em Casifia, e lhes dei expressamente as palavras que deveriam dizer a Ido e aos servidores do templo, seus irmãos, em Casifia, para nos trazerem ministros para a casa do nosso Deus.

[[v15-8-18]]

^<<v15-8-18,18>>^ Trouxeram-nos, segundo a boa mão de Deus sobre nós, um homem sábio, dos filhos de Mali, filho de Levi, filho de Israel, a saber, Serebias, com os seus filhos e irmãos, dezoito;

[[v15-8-19]]

^<<v15-8-19,19>>^ e a Hasabias e, com ele, Jesaías, dos filhos de Merari, com seus irmãos e os filhos deles, vinte;

[[v15-8-20]]

^<<v15-8-20,20>>^ e dos servidores do templo, que Davi e os príncipes deram para o ministério dos levitas, duzentos e vinte, todos eles mencionados nominalmente.

[[v15-8-21]]

^<<v15-8-21,21>>^ Então, apregoei ali um jejum junto ao rio Aava, para nos humilharmos perante o nosso Deus, para lhe pedirmos jornada feliz para nós, para nossos filhos e para tudo o que era nosso.

[[v15-8-22]]

^<<v15-8-22,22>>^ Porque tive vergonha de pedir ao rei exército e cavaleiros para nos defenderem do inimigo no caminho, porquanto já lhe havíamos dito: A boa mão do nosso Deus é sobre todos os que o buscam, para o bem deles; mas a sua força e a sua ira, contra todos os que o abandonam.

[[v15-8-23]]

^<<v15-8-23,23>>^ Nós, pois, jejuamos e pedimos isto ao nosso Deus, e ele nos atendeu.

[[v15-8-24]]

^<<v15-8-24,24>>^ Então, separei doze dos principais, isto é, Serebias, Hasabias e dez dos seus irmãos.

[[v15-8-25]]

^<<v15-8-25,25>>^ Pesei-lhes a prata, e o ouro, e os utensílios que eram a contribuição para a casa de nosso Deus, a qual ofereceram o rei, os seus conselheiros, os seus príncipes e todo o Israel que se achou ali.

[[v15-8-26]]

^<<v15-8-26,26>>^ Entreguei-lhes nas mãos seiscentos e cinquenta talentos de prata e, em objetos de prata, cem talentos, além de cem talentos de ouro;

[[v15-8-27]]

^<<v15-8-27,27>>^ e vinte taças de ouro de mil daricos e dois objetos de lustroso e fino bronze, tão precioso como ouro.

[[v15-8-28]]

^<<v15-8-28,28>>^ Disse-lhes: Vós sois santos ao SENHOR, e santos são estes objetos, como também esta prata e este ouro, oferta voluntária ao SENHOR, Deus de vossos pais.

[[v15-8-29]]

^<<v15-8-29,29>>^ Vigiai-os e guardai-os até que os peseis na presença dos principais sacerdotes, e dos levitas, e dos cabeças de famílias de Israel, em Jerusalém, nas câmaras da Casa do SENHOR.

[[v15-8-30]]

^<<v15-8-30,30>>^ Então, receberam os sacerdotes e os levitas o peso da prata, do ouro e dos objetos, para trazerem a Jerusalém, à casa de nosso Deus.

[[v15-8-31]]

^<<v15-8-31,31>>^ Partimos do rio Aava, no dia doze do primeiro mês, a fim de irmos para Jerusalém; e a boa mão do nosso Deus estava sobre nós e livrou-nos das mãos dos inimigos e dos que nos armavam ciladas pelo caminho.

[[v15-8-32]]

^<<v15-8-32,32>>^ Chegamos a Jerusalém e repousamos ali três dias.

[[v15-8-33]]

^<<v15-8-33,33>>^ No quarto dia, pesamos, na casa do nosso Deus, a prata, o ouro, os objetos e os entregamos a Meremote, filho do sacerdote Urias; com ele estava Eleazar, filho de Fineias, e, com eles, Jozabade, filho de Jesua, e Noadias, filho de Binui, levitas;

[[v15-8-34]]

^<<v15-8-34,34>>^ tudo foi contado e pesado, e o peso total, imediatamente registrado.

[[v15-8-35]]

^<<v15-8-35,35>>^ Os exilados que vieram do cativeiro ofereceram holocaustos ao Deus de Israel, doze novilhos por todo o Israel, noventa e seis carneiros, setenta e sete cordeiros e, como oferta pelo pecado, doze bodes; tudo em holocausto ao SENHOR.

[[v15-8-36]]

^<<v15-8-36,36>>^ Então, deram as ordens do rei aos seus sátrapas e aos governadores deste lado do Eufrates; e estes ajudaram o povo na reconstrução da Casa de Deus.

'''

xref:015-esdras/015-esdras-007.adoc#v15-7-0[&#60; Capítulo Anterior] | <<v15-8-0,Topo>> | xref:015-esdras/015-esdras-009.adoc#v15-9-0[Próximo Capítulo &#62;]