include::./index.adoc[]

[[v15-1-0]]
=== Esdras, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v15-1-1]]

^<<v15-1-1,1>>^ No primeiro ano de Ciro, rei da Pérsia, para que se cumprisse a palavra do SENHOR, por boca de Jeremias, despertou o SENHOR o espírito de Ciro, rei da Pérsia, o qual fez passar pregão por todo o seu reino, como também por escrito, dizendo:

[[v15-1-2]]

^<<v15-1-2,2>>^ Assim diz Ciro, rei da Pérsia: O SENHOR, Deus dos céus, me deu todos os reinos da terra e me encarregou de lhe edificar uma casa em Jerusalém de Judá.

[[v15-1-3]]

^<<v15-1-3,3>>^ Quem dentre vós é, de todo o seu povo, seja seu Deus com ele, e suba a Jerusalém de Judá e edifique a Casa do SENHOR, Deus de Israel; ele é o Deus que habita em Jerusalém.

[[v15-1-4]]

^<<v15-1-4,4>>^ Todo aquele que restar em alguns lugares em que habita, os homens desse lugar o ajudarão com prata, ouro, bens e gado, afora as dádivas voluntárias para a Casa de Deus, a qual está em Jerusalém.

[[v15-1-5]]

^<<v15-1-5,5>>^ Então, se levantaram os cabeças de famílias de Judá e de Benjamim, e os sacerdotes, e os levitas, com todos aqueles cujo espírito Deus despertou, para subirem a edificar a Casa do SENHOR, a qual está em Jerusalém.

[[v15-1-6]]

^<<v15-1-6,6>>^ Todos os que habitavam nos arredores os ajudaram com objetos de prata, com ouro, bens, gado e coisas preciosas, afora tudo o que, voluntariamente, se deu.

[[v15-1-7]]

^<<v15-1-7,7>>^ Também o rei Ciro tirou os utensílios da Casa do SENHOR, os quais Nabucodonosor tinha trazido de Jerusalém e que tinha posto na casa de seus deuses.

[[v15-1-8]]

^<<v15-1-8,8>>^ Tirou-os Ciro, rei da Pérsia, sob a direção do tesoureiro Mitredate, que os entregou contados a Sesbazar, príncipe de Judá.

[[v15-1-9]]

^<<v15-1-9,9>>^ Eis o número deles: trinta bacias de ouro, mil bacias de prata, vinte e nove facas,

[[v15-1-10]]

^<<v15-1-10,10>>^ trinta taças de ouro, quatrocentas e dez taças de prata de outra espécie e mil outros objetos.

[[v15-1-11]]

^<<v15-1-11,11>>^ Todos os utensílios de ouro e de prata foram cinco mil e quatrocentos; todos estes levou Sesbazar, quando os do exílio subiram da Babilônia para Jerusalém.

'''

xref:014-2-cronicas/014-2-cronicas-036.adoc#v14-36-0[&#60; Capítulo Anterior] | <<v15-1-0,Topo>> | xref:015-esdras/015-esdras-002.adoc#v15-2-0[Próximo Capítulo &#62;]