include::./index.adoc[]

[[v15-7-0]]
=== Esdras, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v15-7-1]]

^<<v15-7-1,1>>^ Passadas estas coisas, no reinado de Artaxerxes, rei da Pérsia, Esdras, filho de Seraías, filho de Azarias, filho de Hilquias,

[[v15-7-2]]

^<<v15-7-2,2>>^ filho de Salum, filho de Zadoque, filho de Aitube,

[[v15-7-3]]

^<<v15-7-3,3>>^ filho de Amarias, filho de Azarias, filho de Meraiote,

[[v15-7-4]]

^<<v15-7-4,4>>^ filho de Zeraías, filho de Uzi, filho de Buqui,

[[v15-7-5]]

^<<v15-7-5,5>>^ filho de Abisua, filho de Fineias, filho de Eleazar, filho de Arão, o sumo sacerdote, este Esdras subiu da Babilônia.

[[v15-7-6]]

^<<v15-7-6,6>>^ Ele era escriba versado na Lei de Moisés, dada pelo SENHOR, Deus de Israel; e, segundo a boa mão do SENHOR, seu Deus, que estava sobre ele, o rei lhe concedeu tudo quanto lhe pedira.

[[v15-7-7]]

^<<v15-7-7,7>>^ Também subiram a Jerusalém alguns dos filhos de Israel, dos sacerdotes, dos levitas, dos cantores, dos porteiros e dos servidores do templo, no sétimo ano do rei Artaxerxes.

[[v15-7-8]]

^<<v15-7-8,8>>^ Esdras chegou a Jerusalém no quinto mês, no sétimo ano deste rei;

[[v15-7-9]]

^<<v15-7-9,9>>^ pois, no primeiro dia do primeiro mês, partiu da Babilônia e, no primeiro dia do quinto mês, chegou a Jerusalém, segundo a boa mão do seu Deus sobre ele.

[[v15-7-10]]

^<<v15-7-10,10>>^ Porque Esdras tinha disposto o coração para buscar a Lei do SENHOR, e para a cumprir, e para ensinar em Israel os seus estatutos e os seus juízos.

[[v15-7-11]]

^<<v15-7-11,11>>^ Esta é a cópia da carta que o rei Artaxerxes deu ao sacerdote Esdras, o escriba das palavras, dos mandamentos e dos estatutos do SENHOR sobre Israel:

[[v15-7-12]]

^<<v15-7-12,12>>^ Artaxerxes, rei dos reis, ao sacerdote Esdras, escriba da Lei do Deus do céu: Paz perfeita!

[[v15-7-13]]

^<<v15-7-13,13>>^ Por mim se decreta que, no meu reino, todo aquele do povo de Israel e dos seus sacerdotes e levitas que quiser ir contigo a Jerusalém, vá.

[[v15-7-14]]

^<<v15-7-14,14>>^ Porquanto és mandado da parte do rei e dos seus sete conselheiros para fazeres inquirição a respeito de Judá e de Jerusalém, segundo a Lei do teu Deus, a qual está na tua mão;

[[v15-7-15]]

^<<v15-7-15,15>>^ e para levares a prata e o ouro que o rei e os seus conselheiros, espontaneamente, ofereceram ao Deus de Israel, cuja habitação está em Jerusalém,

[[v15-7-16]]

^<<v15-7-16,16>>^ bem assim a prata e o ouro que achares em toda a província da Babilônia, com as ofertas voluntárias do povo e dos sacerdotes, oferecidas, espontaneamente, para a casa de seu Deus, a qual está em Jerusalém.

[[v15-7-17]]

^<<v15-7-17,17>>^ Portanto, diligentemente comprarás com este dinheiro novilhos, e carneiros, e cordeiros, e as suas ofertas de manjares, e as suas libações e as oferecerás sobre o altar da casa de teu Deus, a qual está em Jerusalém.

[[v15-7-18]]

^<<v15-7-18,18>>^ Também o que a ti e a teus irmãos bem parecer fazerdes do resto da prata e do ouro, fazei-o, segundo a vontade do vosso Deus.

[[v15-7-19]]

^<<v15-7-19,19>>^ E os utensílios que te foram dados para o serviço da casa de teu Deus, restitui-os perante o Deus de Jerusalém.

[[v15-7-20]]

^<<v15-7-20,20>>^ E tudo mais que for necessário para a casa de teu Deus, que te convenha dar, dá-lo-ás da casa dos tesouros do rei.

[[v15-7-21]]

^<<v15-7-21,21>>^ Eu mesmo, o rei Artaxerxes, decreto a todos os tesoureiros que estão dalém do Eufrates: tudo quanto vos pedir o sacerdote Esdras, escriba da Lei do Deus do céu, pontualmente se lhe faça;

[[v15-7-22]]

^<<v15-7-22,22>>^ até cem talentos de prata, até cem coros de trigo, até cem batos de vinho, até cem batos de azeite e sal à vontade.

[[v15-7-23]]

^<<v15-7-23,23>>^ Tudo quanto se ordenar, segundo o mandado do Deus do céu, exatamente se faça para a casa do Deus do céu; pois para que haveria grande ira sobre o reino do rei e de seus filhos?

[[v15-7-24]]

^<<v15-7-24,24>>^ Também vos fazemos saber, acerca de todos os sacerdotes e levitas, cantores, porteiros, de todos os que servem nesta Casa de Deus, que não será lícito impor-lhes nem direitos, nem impostos, nem pedágios.

[[v15-7-25]]

^<<v15-7-25,25>>^ Tu, Esdras, segundo a sabedoria do teu Deus, que possuis, nomeia magistrados e juízes que julguem a todo o povo que está dalém do Eufrates, a todos os que sabem as leis de teu Deus, e ao que não as sabe, que lhas façam saber.

[[v15-7-26]]

^<<v15-7-26,26>>^ Todo aquele que não observar a lei do teu Deus e a lei do rei, seja condenado ou à morte, ou ao desterro, ou à confiscação de bens, ou à prisão.

[[v15-7-27]]

^<<v15-7-27,27>>^ Bendito seja o SENHOR, Deus de nossos pais, que deste modo moveu o coração do rei para ornar a Casa do SENHOR, a qual está em Jerusalém;

[[v15-7-28]]

^<<v15-7-28,28>>^ e que estendeu para mim a sua misericórdia perante o rei, os seus conselheiros e todos os seus príncipes poderosos. Assim, me animei, segundo a boa mão do SENHOR, meu Deus, sobre mim, e ajuntei de Israel alguns chefes para subirem comigo.

'''

xref:015-esdras/015-esdras-006.adoc#v15-6-0[&#60; Capítulo Anterior] | <<v15-7-0,Topo>> | xref:015-esdras/015-esdras-008.adoc#v15-8-0[Próximo Capítulo &#62;]