include::./index.adoc[]

[[v15-6-0]]
=== Esdras, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v15-6-1]]

^<<v15-6-1,1>>^ Então, o rei Dario deu ordem, e uma busca se fez nos arquivos reais da Babilônia, onde se guardavam os documentos.

[[v15-6-2]]

^<<v15-6-2,2>>^ Em Acmetá, na fortaleza que está na província da Média, se achou um rolo, e nele estava escrito um memorial que dizia assim:

[[v15-6-3]]

^<<v15-6-3,3>>^ O rei Ciro, no seu primeiro ano, baixou o seguinte decreto: Com respeito à Casa de Deus, em Jerusalém, deve ela edificar-se para ser um lugar em que se ofereçam sacrifícios; seus fundamentos serão firmes, a sua altura, de sessenta côvados, e a sua largura, de sessenta côvados, com três carreiras de grandes pedras e uma de madeira nova.

[[v15-6-4]]

^<<v15-6-4,4>>^ A despesa se fará da casa do rei.

[[v15-6-5]]

^<<v15-6-5,5>>^ Demais disto, os utensílios de ouro e de prata, da Casa de Deus, que Nabucodonosor tirara do templo que estava em Jerusalém, levando-os para a Babilônia, serão devolvidos para o templo que está em Jerusalém, cada utensílio para o seu lugar; serão recolocados na Casa de Deus.

[[v15-6-6]]

^<<v15-6-6,6>>^ Agora, pois, Tatenai, governador dalém do Eufrates, Setar-Bozenai e seus companheiros, os afarsaquitas, que estais para além do rio, retirai-vos para longe dali.

[[v15-6-7]]

^<<v15-6-7,7>>^ Não interrompais a obra desta Casa de Deus, para que o governador dos judeus e os seus anciãos reedifiquem a Casa de Deus no seu lugar.

[[v15-6-8]]

^<<v15-6-8,8>>^ Também por mim se decreta o que haveis de fazer a estes anciãos dos judeus, para que reedifiquem esta Casa de Deus, a saber, que da tesouraria real, isto é, dos tributos dalém do rio, se pague, pontualmente, a despesa a estes homens, para que não se interrompa a obra.

[[v15-6-9]]

^<<v15-6-9,9>>^ Também se lhes dê, dia após dia, sem falta, aquilo de que houverem mister: novilhos, carneiros e cordeiros, para holocausto ao Deus dos céus; trigo, sal, vinho e azeite, segundo a determinação dos sacerdotes que estão em Jerusalém;

[[v15-6-10]]

^<<v15-6-10,10>>^ para que ofereçam sacrifícios de aroma agradável ao Deus dos céus e orem pela vida do rei e de seus filhos.

[[v15-6-11]]

^<<v15-6-11,11>>^ Também por mim se decreta que todo homem que alterar este decreto, uma viga se arrancará da sua casa, e que seja ele levantado e pendurado nela; e que da sua casa se faça um monturo.

[[v15-6-12]]

^<<v15-6-12,12>>^ O Deus, pois, que fez habitar ali o seu nome derribe a todos os reis e povos que estenderem a mão para alterar o decreto e para destruir esta Casa de Deus, a qual está em Jerusalém. Eu, Dario, baixei o decreto; que se execute com toda a pontualidade.

[[v15-6-13]]

^<<v15-6-13,13>>^ Então, Tatenai, o governador daquém do Eufrates, Setar-Bozenai e os seus companheiros assim o fizeram pontualmente, segundo decretara o rei Dario.

[[v15-6-14]]

^<<v15-6-14,14>>^ Os anciãos dos judeus iam edificando e prosperando em virtude do que profetizaram os profetas Ageu e Zacarias, filho de Ido. Edificaram a casa e a terminaram segundo o mandado do Deus de Israel e segundo o decreto de Ciro, de Dario e de Artaxerxes, rei da Pérsia.

[[v15-6-15]]

^<<v15-6-15,15>>^ Acabou-se esta casa no dia terceiro do mês de adar, no sexto ano do reinado do rei Dario.

[[v15-6-16]]

^<<v15-6-16,16>>^ Os filhos de Israel, os sacerdotes, os levitas e o restante dos exilados celebraram com regozijo a dedicação desta Casa de Deus.

[[v15-6-17]]

^<<v15-6-17,17>>^ Para a dedicação desta Casa de Deus ofereceram cem novilhos, duzentos carneiros, quatrocentos cordeiros e doze cabritos, para oferta pelo pecado de todo o Israel, segundo o número das tribos de Israel.

[[v15-6-18]]

^<<v15-6-18,18>>^ Estabeleceram os sacerdotes nos seus turnos e os levitas nas suas divisões, para o serviço de Deus em Jerusalém, segundo está escrito no Livro de Moisés.

[[v15-6-19]]

^<<v15-6-19,19>>^ Os que vieram do cativeiro celebraram a Páscoa no dia catorze do primeiro mês;

[[v15-6-20]]

^<<v15-6-20,20>>^ porque os sacerdotes e os levitas se tinham purificado como se fossem um só homem, e todos estavam limpos; mataram o cordeiro da Páscoa para todos os que vieram do cativeiro, para os sacerdotes, seus irmãos, e para si mesmos.

[[v15-6-21]]

^<<v15-6-21,21>>^ Assim, comeram a Páscoa os filhos de Israel que tinham voltado do exílio e todos os que, unindo-se a eles, se haviam separado da imundícia dos gentios da terra, para buscarem o SENHOR, Deus de Israel.

[[v15-6-22]]

^<<v15-6-22,22>>^ Celebraram a Festa dos Pães Asmos por sete dias, com regozijo, porque o SENHOR os tinha alegrado, mudando o coração do rei da Assíria a favor deles, para lhes fortalecer as mãos na obra da Casa de Deus, o Deus de Israel.

'''

xref:015-esdras/015-esdras-005.adoc#v15-5-0[&#60; Capítulo Anterior] | <<v15-6-0,Topo>> | xref:015-esdras/015-esdras-007.adoc#v15-7-0[Próximo Capítulo &#62;]