include::./index.adoc[]

[[v15-10-0]]
=== Esdras, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v15-10-1]]

^<<v15-10-1,1>>^ Enquanto Esdras orava e fazia confissão, chorando prostrado diante da Casa de Deus, ajuntou-se a ele de Israel mui grande congregação de homens, de mulheres e de crianças; pois o povo chorava com grande choro.

[[v15-10-2]]

^<<v15-10-2,2>>^ Então, Secanias, filho de Jeiel, um dos filhos de Elão, tomou a palavra e disse a Esdras: Nós temos transgredido contra o nosso Deus, casando com mulheres estrangeiras, dos povos de outras terras, mas, no tocante a isto, ainda há esperança para Israel.

[[v15-10-3]]

^<<v15-10-3,3>>^ Agora, pois, façamos aliança com o nosso Deus, de que despediremos todas as mulheres e os seus filhos, segundo o conselho do Senhor e o dos que tremem ao mandado do nosso Deus; e faça-se segundo a Lei.

[[v15-10-4]]

^<<v15-10-4,4>>^ Levanta-te, pois esta coisa é de tua incumbência, e nós seremos contigo; sê forte e age.

[[v15-10-5]]

^<<v15-10-5,5>>^ Então, Esdras se levantou e ajuramentou os principais sacerdotes, os levitas e todo o Israel, de que fariam segundo esta palavra. E eles juraram.

[[v15-10-6]]

^<<v15-10-6,6>>^ Esdras se retirou de diante da Casa de Deus, e entrou na câmara de Joanã, filho de Eliasibe, e lá não comeu pão, nem bebeu água, porque pranteava por causa da transgressão dos que tinham voltado do exílio.

[[v15-10-7]]

^<<v15-10-7,7>>^ Fez-se passar pregão por Judá e Jerusalém a todos os que vieram do exílio, que deviam ajuntar-se em Jerusalém;

[[v15-10-8]]

^<<v15-10-8,8>>^ e que, se alguém, em três dias, não viesse, segundo o conselho dos príncipes e dos anciãos, todos os seus bens seriam totalmente destruídos, e ele mesmo separado da congregação dos que voltaram do exílio.

[[v15-10-9]]

^<<v15-10-9,9>>^ Então, todos os homens de Judá e Benjamim, em três dias, se ajuntaram em Jerusalém; no dia vinte do mês nono, todo o povo se assentou na praça da Casa de Deus, tremendo por causa desta coisa e por causa das grandes chuvas.

[[v15-10-10]]

^<<v15-10-10,10>>^ Então, se levantou Esdras, o sacerdote, e lhes disse: Vós transgredistes casando-vos com mulheres estrangeiras, aumentando a culpa de Israel.

[[v15-10-11]]

^<<v15-10-11,11>>^ Agora, pois, fazei confissão ao SENHOR, Deus de vossos pais, e fazei o que é do seu agrado; separai-vos dos povos de outras terras e das mulheres estrangeiras.

[[v15-10-12]]

^<<v15-10-12,12>>^ Respondeu toda a congregação e disse em altas vozes: Assim seja; segundo as tuas palavras, assim nos convém fazer.

[[v15-10-13]]

^<<v15-10-13,13>>^ Porém o povo é muito, e, sendo tempo de grandes chuvas, não podemos estar aqui de fora; e não é isto obra de um dia ou dois, pois somos muitos os que transgredimos nesta coisa.

[[v15-10-14]]

^<<v15-10-14,14>>^ Ora, que os nossos príncipes decidam por toda a congregação, e que venham a eles em tempos determinados todos os que em nossas cidades casaram com mulheres estrangeiras, e com estes os anciãos de cada cidade, e os seus juízes, até que desviemos de nós o brasume da ira do nosso Deus, por esta coisa.

[[v15-10-15]]

^<<v15-10-15,15>>^ No entanto, Jônatas, filho de Asael, e Jazeías, filho de Ticvá, se opuseram a esta coisa; e Mesulão e Sabetai, levita, os apoiaram.

[[v15-10-16]]

^<<v15-10-16,16>>^ Assim o fizeram os que voltaram do exílio; então, Esdras, o sacerdote, elegeu nominalmente os homens cabeças de famílias, segundo a casa de seus pais, que se assentaram no dia primeiro do décimo mês, para inquirir nesta coisa;

[[v15-10-17]]

^<<v15-10-17,17>>^ e o concluíram no dia primeiro do primeiro mês, a respeito de todos os homens que casaram com mulheres estrangeiras.

[[v15-10-18]]

^<<v15-10-18,18>>^ Acharam-se dentre os filhos dos sacerdotes estes, que casaram com mulheres estrangeiras: dos filhos de Jesua, filho de Jozadaque, e de seus irmãos: Maaseias, Eliézer, Jaribe e Gedalias.

[[v15-10-19]]

^<<v15-10-19,19>>^ Com um aperto de mão, prometeram despedir suas mulheres e, por serem culpados, ofereceram um carneiro do rebanho pela sua culpa.

[[v15-10-20]]

^<<v15-10-20,20>>^ Dos filhos de Imer: Hanani e Zebadias.

[[v15-10-21]]

^<<v15-10-21,21>>^ Dos filhos de Harim: Maaseias, Elias, Semaías, Jeiel e Uzias.

[[v15-10-22]]

^<<v15-10-22,22>>^ Dos filhos de Pasur: Elioenai, Maaseias, Ismael, Natanael, Jozabade e Elasa.

[[v15-10-23]]

^<<v15-10-23,23>>^ Dos levitas: Jozabade e Simei, Quelaías (este é Quelita), Petaías, Judá e Eliézer.

[[v15-10-24]]

^<<v15-10-24,24>>^ Dos cantores: Eliasibe; dos porteiros: Salum, Telém e Uri.

[[v15-10-25]]

^<<v15-10-25,25>>^ E de Israel: dos filhos de Parós: Ramias, Jezias, Malquias, Miamim, Eleazar, Malquias e Benaia.

[[v15-10-26]]

^<<v15-10-26,26>>^ Dos filhos de Elão: Matanias, Zacarias, Jeiel, Abdi, Jerimote e Elias.

[[v15-10-27]]

^<<v15-10-27,27>>^ Dos filhos de Zatu: Elioenai, Eliasibe, Matanias, Jerimote, Zabade e Aziza.

[[v15-10-28]]

^<<v15-10-28,28>>^ Dos filhos de Bebai: Joanã, Hananias, Zabai e Atlai.

[[v15-10-29]]

^<<v15-10-29,29>>^ Dos filhos de Bani: Mesulão, Maluque, Adaías, Jasube, Seal e Jerimote.

[[v15-10-30]]

^<<v15-10-30,30>>^ Dos filhos de Paate-Moabe: Adna, Quelal, Benaia, Maaseias, Matanias, Bezalel, Binui e Manassés.

[[v15-10-31]]

^<<v15-10-31,31>>^ Dos filhos de Harim: Eliézer, Issias, Malquias, Semaías, Simeão,

[[v15-10-32]]

^<<v15-10-32,32>>^ Benjamim, Maluque e Semarias.

[[v15-10-33]]

^<<v15-10-33,33>>^ Dos filhos de Hasum: Matenai, Matatá, Zabade, Elifelete, Jeremai, Manassés e Simei.

[[v15-10-34]]

^<<v15-10-34,34>>^ Dos filhos de Bani: Maadai, Anrão, Uel,

[[v15-10-35]]

^<<v15-10-35,35>>^ Benaia, Bedias, Queluí,

[[v15-10-36]]

^<<v15-10-36,36>>^ Vanias, Meremote, Eliasibe,

[[v15-10-37]]

^<<v15-10-37,37>>^ Matanias, Matenai, Jaasai,

[[v15-10-38]]

^<<v15-10-38,38>>^ Bani, Binui, Simei,

[[v15-10-39]]

^<<v15-10-39,39>>^ Selemias, Natã, Adaías,

[[v15-10-40]]

^<<v15-10-40,40>>^ Macnadbai, Sasai, Sarai,

[[v15-10-41]]

^<<v15-10-41,41>>^ Azarel, Selemias, Semarias,

[[v15-10-42]]

^<<v15-10-42,42>>^ Salum, Amarias e José.

[[v15-10-43]]

^<<v15-10-43,43>>^ Dos filhos de Nebo: Jeiel, Matitias, Zabade, Zebina, Jadai, Joel e Benaia.

[[v15-10-44]]

^<<v15-10-44,44>>^ Todos estes haviam tomado mulheres estrangeiras, alguns dos quais tinham filhos destas mulheres.

'''

xref:015-esdras/015-esdras-009.adoc#v15-9-0[&#60; Capítulo Anterior] | <<v15-10-0,Topo>> | xref:016-neemias/016-neemias-001.adoc#v16-1-0[Próximo Capítulo &#62;]