include::./index.adoc[]

[[v15-5-0]]
=== Esdras, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v15-5-1]]

^<<v15-5-1,1>>^ Ora, os profetas Ageu e Zacarias, filho de Ido, profetizaram aos judeus que estavam em Judá e em Jerusalém, em nome do Deus de Israel, cujo Espírito estava com eles.

[[v15-5-2]]

^<<v15-5-2,2>>^ Então, se dispuseram Zorobabel, filho de Sealtiel, e Jesua, filho de Jozadaque, e começaram a edificar a Casa de Deus, a qual está em Jerusalém; e, com eles, os referidos profetas de Deus, que os ajudavam.

[[v15-5-3]]

^<<v15-5-3,3>>^ Nesse tempo, veio a eles Tatenai, governador daquém do Eufrates, e Setar-Bozenai, e seus companheiros e assim lhes perguntaram: Quem vos deu ordem para reedificardes esta casa e restaurardes este muro?

[[v15-5-4]]

^<<v15-5-4,4>>^ Perguntaram-lhes mais: E quais são os nomes dos homens que constroem este edifício?

[[v15-5-5]]

^<<v15-5-5,5>>^ Porém os olhos de Deus estavam sobre os anciãos dos judeus, de maneira que não foram obrigados a parar, até que o assunto chegasse a Dario, e viesse resposta por carta sobre isso.

[[v15-5-6]]

^<<v15-5-6,6>>^ Eis a cópia da carta que Tatenai, o governador daquém do Eufrates, com Setar-Bozenai e os seus companheiros, os afarsaquitas, que estavam deste lado do rio, enviaram ao rei Dario,

[[v15-5-7]]

^<<v15-5-7,7>>^ na qual lhe deram uma relação escrita do modo seguinte: Ao rei Dario, toda a paz!

[[v15-5-8]]

^<<v15-5-8,8>>^ Seja notório ao rei que nós fomos à província de Judá, à casa do grande Deus, a qual se edifica com grandes pedras; a madeira se está pondo nas paredes, e a obra se vai fazendo com diligência e se adianta nas suas mãos.

[[v15-5-9]]

^<<v15-5-9,9>>^ Perguntamos aos anciãos e assim lhes dissemos: Quem vos deu ordem para reedificardes esta casa e restaurardes este muro?

[[v15-5-10]]

^<<v15-5-10,10>>^ Demais disto, lhes perguntamos também pelo seu nome, para tos declararmos, para que te pudéssemos escrever os nomes dos homens que são entre eles os chefes.

[[v15-5-11]]

^<<v15-5-11,11>>^ Esta foi a resposta que nos deram: Nós somos servos do Deus dos céus e da terra e reedificamos a casa que há muitos anos fora construída, a qual um grande rei de Israel edificou e a terminou.

[[v15-5-12]]

^<<v15-5-12,12>>^ Mas, depois que nossos pais provocaram à ira o Deus dos céus, ele os entregou nas mãos de Nabucodonosor, rei da Babilônia, o caldeu, o qual destruiu esta casa e transportou o povo para a Babilônia.

[[v15-5-13]]

^<<v15-5-13,13>>^ Porém Ciro, rei da Babilônia, no seu primeiro ano, deu ordem para que esta Casa de Deus se edificasse.

[[v15-5-14]]

^<<v15-5-14,14>>^ Também os utensílios de ouro e de prata, da Casa de Deus, que Nabucodonosor levara do templo que estava em Jerusalém e os meteu no templo de Babilônia, o rei Ciro os tirou de lá, e foram dados a um homem cujo nome era Sesbazar, a quem nomeara governador

[[v15-5-15]]

^<<v15-5-15,15>>^ e lhe disse: Toma estes utensílios, e vai, e leva-os ao templo de Jerusalém, e faze reedificar a Casa de Deus, no seu lugar.

[[v15-5-16]]

^<<v15-5-16,16>>^ Então, veio o dito Sesbazar e lançou os fundamentos da Casa de Deus, a qual está em Jerusalém; e, daí para cá, se está edificando e ainda não está acabada.

[[v15-5-17]]

^<<v15-5-17,17>>^ Agora, pois, se parece bem ao rei, que se busque nos arquivos reais, na Babilônia, se é verdade haver uma ordem do rei Ciro para edificar esta Casa de Deus, em Jerusalém; e sobre isto nos faça o rei saber a sua vontade.

'''

xref:015-esdras/015-esdras-004.adoc#v15-4-0[&#60; Capítulo Anterior] | <<v15-5-0,Topo>> | xref:015-esdras/015-esdras-006.adoc#v15-6-0[Próximo Capítulo &#62;]