include::./index.adoc[]

[[v15-3-0]]
=== Esdras, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v15-3-1]]

^<<v15-3-1,1>>^ Em chegando o sétimo mês, e estando os filhos de Israel já nas cidades, ajuntou-se o povo, como um só homem, em Jerusalém.

[[v15-3-2]]

^<<v15-3-2,2>>^ Levantou-se Jesua, filho de Jozadaque, e seus irmãos, sacerdotes, e Zorobabel, filho de Sealtiel, e seus irmãos e edificaram o altar do Deus de Israel, para sobre ele oferecerem holocaustos, como está escrito na Lei de Moisés, homem de Deus.

[[v15-3-3]]

^<<v15-3-3,3>>^ Firmaram o altar sobre as suas bases; e, ainda que estavam sob o terror dos povos de outras terras, ofereceram sobre ele holocaustos ao SENHOR, de manhã e à tarde.

[[v15-3-4]]

^<<v15-3-4,4>>^ Celebraram a Festa dos Tabernáculos, como está escrito, e ofereceram holocaustos diários, segundo o número ordenado para cada dia;

[[v15-3-5]]

^<<v15-3-5,5>>^ e, depois disto, o holocausto contínuo e os sacrifícios das Festas da Lua Nova e de todas as festas fixas do SENHOR, como também os dos que traziam ofertas voluntárias ao SENHOR.

[[v15-3-6]]

^<<v15-3-6,6>>^ Desde o primeiro dia do sétimo mês, começaram a oferecer holocaustos ao SENHOR; porém ainda não estavam postos os fundamentos do templo do SENHOR.

[[v15-3-7]]

^<<v15-3-7,7>>^ Deram, pois, o dinheiro aos pedreiros e aos carpinteiros, como também comida, bebida e azeite aos sidônios e tírios, para trazerem do Líbano madeira de cedro ao mar, para Jope, segundo a permissão que lhes tinha dado Ciro, rei da Pérsia.

[[v15-3-8]]

^<<v15-3-8,8>>^ No segundo ano da sua vinda à Casa de Deus, em Jerusalém, no segundo mês, Zorobabel, filho de Sealtiel, e Jesua, filho de Jozadaque, e os outros seus irmãos, sacerdotes e levitas, e todos os que vieram do cativeiro a Jerusalém começaram a obra da Casa do SENHOR e constituíram levitas da idade de vinte anos para cima, para a superintenderem.

[[v15-3-9]]

^<<v15-3-9,9>>^ Então, se apresentaram Jesua com seus filhos e seus irmãos, Cadmiel e seus filhos, os filhos de Judá, para juntamente vigiarem os que faziam a obra na Casa de Deus, bem como os filhos de Henadade, seus filhos e seus irmãos, os levitas.

[[v15-3-10]]

^<<v15-3-10,10>>^ Quando os edificadores lançaram os alicerces do templo do SENHOR, apresentaram-se os sacerdotes, paramentados e com trombetas, e os levitas, filhos de Asafe, com címbalos, para louvarem o SENHOR, segundo as determinações de Davi, rei de Israel.

[[v15-3-11]]

^<<v15-3-11,11>>^ Cantavam alternadamente, louvando e rendendo graças ao SENHOR, com estas palavras: Ele é bom, porque a sua misericórdia dura para sempre sobre Israel. E todo o povo jubilou com altas vozes, louvando ao SENHOR por se terem lançado os alicerces da sua casa.

[[v15-3-12]]

^<<v15-3-12,12>>^ Porém muitos dos sacerdotes, e levitas, e cabeças de famílias, já idosos, que viram a primeira casa, choraram em alta voz quando à sua vista foram lançados os alicerces desta casa; muitos, no entanto, levantaram as vozes com gritos de alegria.

[[v15-3-13]]

^<<v15-3-13,13>>^ De maneira que não se podiam discernir as vozes de alegria das vozes do choro do povo; pois o povo jubilava com tão grandes gritos, que as vozes se ouviam de mui longe.

'''

xref:015-esdras/015-esdras-002.adoc#v15-2-0[&#60; Capítulo Anterior] | <<v15-3-0,Topo>> | xref:015-esdras/015-esdras-004.adoc#v15-4-0[Próximo Capítulo &#62;]