include::./index.adoc[]

[[v57-1-0]]
=== Filemom, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v57-1-1]]

^<<v57-1-1,1>>^ Paulo, prisioneiro de Cristo Jesus, e o irmão Timóteo, ao amado Filemom, também nosso colaborador,

[[v57-1-2]]

^<<v57-1-2,2>>^ e à irmã Áfia, e a Arquipo, nosso companheiro de lutas, e à igreja que está em tua casa,

[[v57-1-3]]

^<<v57-1-3,3>>^ graça e paz a vós outros, da parte de Deus, nosso Pai, e do Senhor Jesus Cristo.

[[v57-1-4]]

^<<v57-1-4,4>>^ Dou graças ao meu Deus, lembrando-me, sempre, de ti nas minhas orações,

[[v57-1-5]]

^<<v57-1-5,5>>^ estando ciente do teu amor e da fé que tens para com o Senhor Jesus e todos os santos,

[[v57-1-6]]

^<<v57-1-6,6>>^ para que a comunhão da tua fé se torne eficiente no pleno conhecimento de todo bem que há em nós, para com Cristo.

[[v57-1-7]]

^<<v57-1-7,7>>^ Pois, irmão, tive grande alegria e conforto no teu amor, porquanto o coração dos santos tem sido reanimado por teu intermédio.

[[v57-1-8]]

^<<v57-1-8,8>>^ Pois bem, ainda que eu sinta plena liberdade em Cristo para te ordenar o que convém,

[[v57-1-9]]

^<<v57-1-9,9>>^ prefiro, todavia, solicitar em nome do amor, sendo o que sou, Paulo, o velho e, agora, até prisioneiro de Cristo Jesus;

[[v57-1-10]]

^<<v57-1-10,10>>^ sim, solicito-te em favor de meu filho Onésimo, que gerei entre algemas.

[[v57-1-11]]

^<<v57-1-11,11>>^ Ele, antes, te foi inútil; atualmente, porém, é útil, a ti e a mim.

[[v57-1-12]]

^<<v57-1-12,12>>^ Eu to envio de volta em pessoa, quero dizer, o meu próprio coração.

[[v57-1-13]]

^<<v57-1-13,13>>^ Eu queria conservá-lo comigo mesmo para, em teu lugar, me servir nas algemas que carrego por causa do evangelho;

[[v57-1-14]]

^<<v57-1-14,14>>^ nada, porém, quis fazer sem o teu consentimento, para que a tua bondade não venha a ser como que por obrigação, mas de livre vontade.

[[v57-1-15]]

^<<v57-1-15,15>>^ Pois acredito que ele veio a ser afastado de ti temporariamente, a fim de que o recebas para sempre,

[[v57-1-16]]

^<<v57-1-16,16>>^ não como escravo; antes, muito acima de escravo, como irmão caríssimo, especialmente de mim e, com maior razão, de ti, quer na carne, quer no Senhor.

[[v57-1-17]]

^<<v57-1-17,17>>^ Se, portanto, me consideras companheiro, recebe-o, como se fosse a mim mesmo.

[[v57-1-18]]

^<<v57-1-18,18>>^ E, se algum dano te fez ou se te deve alguma coisa, lança tudo em minha conta.

[[v57-1-19]]

^<<v57-1-19,19>>^ Eu, Paulo, de próprio punho, o escrevo: Eu pagarei — para não te alegar que também tu me deves até a ti mesmo.

[[v57-1-20]]

^<<v57-1-20,20>>^ Sim, irmão, que eu receba de ti, no Senhor, este benefício. Reanima-me o coração em Cristo.

[[v57-1-21]]

^<<v57-1-21,21>>^ Certo, como estou, da tua obediência, eu te escrevo, sabendo que farás mais do que estou pedindo.

[[v57-1-22]]

^<<v57-1-22,22>>^ E, ao mesmo tempo, prepara-me também pousada, pois espero que, por vossas orações, vos serei restituído.

[[v57-1-23]]

^<<v57-1-23,23>>^ Saúdam-te Epafras, prisioneiro comigo, em Cristo Jesus,

[[v57-1-24]]

^<<v57-1-24,24>>^ Marcos, Aristarco, Demas e Lucas, meus cooperadores.

[[v57-1-25]]

^<<v57-1-25,25>>^ A graça do Senhor Jesus Cristo seja com o vosso espírito.

'''

xref:056-tito/056-tito-003.adoc#v56-3-0[&#60; Capítulo Anterior] | <<v57-1-0,Topo>> | xref:058-hebreus/058-hebreus-001.adoc#v58-1-0[Próximo Capítulo &#62;]