include::./index.adoc[]

[[v39-4-0]]
=== Malaquias, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v39-4-1]]

^<<v39-4-1,1>>^ Pois eis que vem o dia e arde como fornalha; todos os soberbos e todos os que cometem perversidade serão como o restolho; o dia que vem os abrasará, diz o SENHOR dos Exércitos, de sorte que não lhes deixará nem raiz nem ramo.

[[v39-4-2]]

^<<v39-4-2,2>>^ Mas para vós outros que temeis o meu nome nascerá o sol da justiça, trazendo salvação nas suas asas; saireis e saltareis como bezerros soltos da estrebaria.

[[v39-4-3]]

^<<v39-4-3,3>>^ Pisareis os perversos, porque se farão cinzas debaixo das plantas de vossos pés, naquele dia que prepararei, diz o SENHOR dos Exércitos.

[[v39-4-4]]

^<<v39-4-4,4>>^ Lembrai-vos da Lei de Moisés, meu servo, a qual lhe prescrevi em Horebe para todo o Israel, a saber, estatutos e juízos.

[[v39-4-5]]

^<<v39-4-5,5>>^ Eis que eu vos enviarei o profeta Elias, antes que venha o grande e terrível Dia do SENHOR;

[[v39-4-6]]

^<<v39-4-6,6>>^ ele converterá o coração dos pais aos filhos e o coração dos filhos a seus pais, para que eu não venha e fira a terra com maldição.

'''

xref:039-malaquias/039-malaquias-003.adoc#v39-3-0[&#60; Capítulo Anterior] | <<v39-4-0,Topo>> | xref:040-mateus/040-mateus-001.adoc#v40-1-0[Próximo Capítulo &#62;]