include::./index.adoc[]

[[v39-1-0]]
=== Malaquias, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v39-1-1]]

^<<v39-1-1,1>>^ Sentença pronunciada pelo SENHOR contra Israel, por intermédio de Malaquias.

[[v39-1-2]]

^<<v39-1-2,2>>^ Eu vos tenho amado, diz o SENHOR; mas vós dizeis: Em que nos tens amado? Não foi Esaú irmão de Jacó? — disse o SENHOR; todavia, amei a Jacó,

[[v39-1-3]]

^<<v39-1-3,3>>^ porém aborreci a Esaú; e fiz dos seus montes uma assolação e dei a sua herança aos chacais do deserto.

[[v39-1-4]]

^<<v39-1-4,4>>^ Se Edom diz: Fomos destruídos, porém tornaremos a edificar as ruínas, então, diz o SENHOR dos Exércitos: Eles edificarão, mas eu destruirei; e Edom será chamado Terra-De-Perversidade e Povo-Contra-Quem-O- SENHOR-Está-Irado-Para-Sempre.

[[v39-1-5]]

^<<v39-1-5,5>>^ Os vossos olhos o verão, e vós direis: Grande é o SENHOR também fora dos limites de Israel.

[[v39-1-6]]

^<<v39-1-6,6>>^ O filho honra o pai, e o servo, ao seu senhor. Se eu sou pai, onde está a minha honra? E, se eu sou senhor, onde está o respeito para comigo? — diz o SENHOR dos Exércitos a vós outros, ó sacerdotes que desprezais o meu nome. Vós dizeis: Em que desprezamos nós o teu nome?

[[v39-1-7]]

^<<v39-1-7,7>>^ Ofereceis sobre o meu altar pão imundo e ainda perguntais: Em que te havemos profanado? Nisto, que pensais: A mesa do SENHOR é desprezível.

[[v39-1-8]]

^<<v39-1-8,8>>^ Quando trazeis animal cego para o sacrificardes, não é isso mal? E, quando trazeis o coxo ou o enfermo, não é isso mal? Ora, apresenta-o ao teu governador; acaso, terá ele agrado em ti e te será favorável? — diz o SENHOR dos Exércitos.

[[v39-1-9]]

^<<v39-1-9,9>>^ Agora, pois, suplicai o favor de Deus, que nos conceda a sua graça; mas, com tais ofertas nas vossas mãos, aceitará ele a vossa pessoa? — diz o SENHOR dos Exércitos.

[[v39-1-10]]

^<<v39-1-10,10>>^ Tomara houvesse entre vós quem feche as portas, para que não acendêsseis, debalde, o fogo do meu altar. Eu não tenho prazer em vós, diz o SENHOR dos Exércitos, nem aceitarei da vossa mão a oferta.

[[v39-1-11]]

^<<v39-1-11,11>>^ Mas, desde o nascente do sol até ao poente, é grande entre as nações o meu nome; e em todo lugar lhe é queimado incenso e trazidas ofertas puras, porque o meu nome é grande entre as nações, diz o SENHOR dos Exércitos.

[[v39-1-12]]

^<<v39-1-12,12>>^ Mas vós o profanais, quando dizeis: A mesa do SENHOR é imunda, e o que nela se oferece, isto é, a sua comida, é desprezível.

[[v39-1-13]]

^<<v39-1-13,13>>^ E dizeis ainda: Que canseira! E me desprezais, diz o SENHOR dos Exércitos; vós ofereceis o dilacerado, e o coxo, e o enfermo; assim fazeis a oferta. Aceitaria eu isso da vossa mão? — diz o SENHOR.

[[v39-1-14]]

^<<v39-1-14,14>>^ Pois maldito seja o enganador, que, tendo um animal sadio no seu rebanho, promete e oferece ao SENHOR um defeituoso; porque eu sou grande Rei, diz o SENHOR dos Exércitos, o meu nome é terrível entre as nações.

'''

xref:038-zacarias/038-zacarias-014.adoc#v38-14-0[&#60; Capítulo Anterior] | <<v39-1-0,Topo>> | xref:039-malaquias/039-malaquias-002.adoc#v39-2-0[Próximo Capítulo &#62;]