include::./index.adoc[]

[[v25-4-0]]
=== Lamentações, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v25-4-1]]

^<<v25-4-1,1>>^ Como se escureceu o ouro! Como se mudou o ouro refinado! Como estão espalhadas as pedras do santuário pelas esquinas de todas as ruas!

[[v25-4-2]]

^<<v25-4-2,2>>^ Os nobres filhos de Sião, comparáveis a puro ouro, como são agora reputados por objetos de barro, obra das mãos de oleiro!

[[v25-4-3]]

^<<v25-4-3,3>>^ Até os chacais dão o peito, dão de mamar a seus filhos; mas a filha do meu povo tornou-se cruel como os avestruzes no deserto.

[[v25-4-4]]

^<<v25-4-4,4>>^ A língua da criança que mama fica pegada, pela sede, ao céu da boca; os meninos pedem pão, e ninguém há que lho dê.

[[v25-4-5]]

^<<v25-4-5,5>>^ Os que se alimentavam de comidas finas desfalecem nas ruas; os que se criaram entre escarlata se apegam aos monturos.

[[v25-4-6]]

^<<v25-4-6,6>>^ Porque maior é a maldade da filha do meu povo do que o pecado de Sodoma, que foi subvertida como num momento, sem o emprego de mãos nenhumas.

[[v25-4-7]]

^<<v25-4-7,7>>^ Os seus príncipes eram mais alvos do que a neve, mais brancos do que o leite; eram mais ruivos de corpo do que os corais e tinham a formosura da safira.

[[v25-4-8]]

^<<v25-4-8,8>>^ Mas, agora, escureceu-se-lhes o aspecto mais do que a fuligem; não são conhecidos nas ruas; a sua pele se lhes pegou aos ossos, secou-se como uma madeira.

[[v25-4-9]]

^<<v25-4-9,9>>^ Mais felizes foram as vítimas da espada do que as vítimas da fome; porque estas se definham atingidas mortalmente pela falta do produto dos campos.

[[v25-4-10]]

^<<v25-4-10,10>>^ As mãos das mulheres outrora compassivas cozeram seus próprios filhos; estes lhes serviram de alimento na destruição da filha do meu povo.

[[v25-4-11]]

^<<v25-4-11,11>>^ Deu o SENHOR cumprimento à sua indignação, derramou o ardor da sua ira; acendeu fogo em Sião, que consumiu os seus fundamentos.

[[v25-4-12]]

^<<v25-4-12,12>>^ Não creram os reis da terra, nem todos os moradores do mundo, que entrasse o adversário e o inimigo pelas portas de Jerusalém.

[[v25-4-13]]

^<<v25-4-13,13>>^ Foi por causa dos pecados dos seus profetas, das maldades dos seus sacerdotes que se derramou no meio dela o sangue dos justos.

[[v25-4-14]]

^<<v25-4-14,14>>^ Erram como cegos nas ruas, andam contaminados de sangue, de tal sorte que ninguém lhes pode tocar nas roupas.

[[v25-4-15]]

^<<v25-4-15,15>>^ Apartai-vos, imundos! — gritavam-lhes; apartai-vos, apartai-vos, não toqueis! Quando fugiram errantes, dizia-se entre as nações: Jamais habitarão aqui.

[[v25-4-16]]

^<<v25-4-16,16>>^ A ira do SENHOR os espalhou; ele jamais atentará para eles; o inimigo não honra os sacerdotes, nem se compadece dos anciãos.

[[v25-4-17]]

^<<v25-4-17,17>>^ Os nossos olhos ainda desfalecem, esperando vão socorro; temos olhado das vigias para um povo que não pode livrar.

[[v25-4-18]]

^<<v25-4-18,18>>^ Espreitavam os nossos passos, de maneira que não podíamos andar pelas nossas praças; aproximava-se o nosso fim, os nossos dias se cumpriam, era chegado o nosso fim.

[[v25-4-19]]

^<<v25-4-19,19>>^ Os nossos perseguidores foram mais ligeiros do que as aves dos céus; sobre os montes nos perseguiram, no deserto nos armaram ciladas.

[[v25-4-20]]

^<<v25-4-20,20>>^ O fôlego da nossa vida, o ungido do SENHOR, foi preso nos forjes deles; dele dizíamos: debaixo da sua sombra, viveremos entre as nações.

[[v25-4-21]]

^<<v25-4-21,21>>^ Regozija-te e alegra-te, ó filha de Edom, que habitas na terra de Uz; o cálice se passará também a ti; embebedar-te-ás e te desnudarás.

[[v25-4-22]]

^<<v25-4-22,22>>^ O castigo da tua maldade está consumado, ó filha de Sião; o SENHOR nunca mais te levará para o exílio; a tua maldade, ó filha de Edom, descobrirá os teus pecados.

'''

xref:025-lamentacoes/025-lamentacoes-003.adoc#v25-3-0[&#60; Capítulo Anterior] | <<v25-4-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-005.adoc#v25-5-0[Próximo Capítulo &#62;]