include::./index.adoc[]

[[v5-15-0]]
=== Deuteronômio, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-15-1]]

^<<v5-15-1,1>>^ Ao fim de cada sete anos, farás remissão.

[[v5-15-2]]

^<<v5-15-2,2>>^ Este, pois, é o modo da remissão: todo credor que emprestou ao seu próximo alguma coisa remitirá o que havia emprestado; não o exigirá do seu próximo ou do seu irmão, pois a remissão do SENHOR é proclamada.

[[v5-15-3]]

^<<v5-15-3,3>>^ Do estranho podes exigi-lo, mas o que tiveres em poder de teu irmão, quitá-lo-ás;

[[v5-15-4]]

^<<v5-15-4,4>>^ para que entre ti não haja pobre; pois o SENHOR, teu Deus, te abençoará abundantemente na terra que te dá por herança, para a possuíres,

[[v5-15-5]]

^<<v5-15-5,5>>^ se apenas ouvires, atentamente, a voz do SENHOR, teu Deus, para cuidares em cumprir todos estes mandamentos que hoje te ordeno.

[[v5-15-6]]

^<<v5-15-6,6>>^ Pois o SENHOR, teu Deus, te abençoará, como te tem dito; assim, emprestarás a muitas nações, mas não tomarás empréstimos; e dominarás muitas nações, porém elas não te dominarão.

[[v5-15-7]]

^<<v5-15-7,7>>^ Quando entre ti houver algum pobre de teus irmãos, em alguma das tuas cidades, na tua terra que o SENHOR, teu Deus, te dá, não endurecerás o teu coração, nem fecharás as mãos a teu irmão pobre;

[[v5-15-8]]

^<<v5-15-8,8>>^ antes, lhe abrirás de todo a mão e lhe emprestarás o que lhe falta, quanto baste para a sua necessidade.

[[v5-15-9]]

^<<v5-15-9,9>>^ Guarda-te não haja pensamento vil no teu coração, nem digas: Está próximo o sétimo ano, o ano da remissão, de sorte que os teus olhos sejam malignos para com teu irmão pobre, e não lhe dês nada, e ele clame contra ti ao SENHOR, e haja em ti pecado.

[[v5-15-10]]

^<<v5-15-10,10>>^ Livremente, lhe darás, e não seja maligno o teu coração, quando lho deres; pois, por isso, te abençoará o SENHOR, teu Deus, em toda a tua obra e em tudo o que empreenderes.

[[v5-15-11]]

^<<v5-15-11,11>>^ Pois nunca deixará de haver pobres na terra; por isso, eu te ordeno: livremente, abrirás a mão para o teu irmão, para o necessitado, para o pobre na tua terra.

[[v5-15-12]]

^<<v5-15-12,12>>^ Quando um de teus irmãos, hebreu ou hebreia, te for vendido, seis anos servir-te-á, mas, no sétimo, o despedirás forro.

[[v5-15-13]]

^<<v5-15-13,13>>^ E, quando de ti o despedires forro, não o deixarás ir vazio.

[[v5-15-14]]

^<<v5-15-14,14>>^ Liberalmente, lhe fornecerás do teu rebanho, da tua eira e do teu lagar; daquilo com que o SENHOR, teu Deus, te houver abençoado, lhe darás.

[[v5-15-15]]

^<<v5-15-15,15>>^ Lembrar-te-ás de que foste servo na terra do Egito e de que o SENHOR, teu Deus, te remiu; pelo que, hoje, isso te ordeno.

[[v5-15-16]]

^<<v5-15-16,16>>^ Se, porém, ele te disser: Não sairei de ti; porquanto te ama, a ti e a tua casa, por estar bem contigo,

[[v5-15-17]]

^<<v5-15-17,17>>^ então, tomarás uma sovela e lhe furarás a orelha, na porta, e será para sempre teu servo; e também assim farás à tua serva.

[[v5-15-18]]

^<<v5-15-18,18>>^ Não pareça aos teus olhos duro o despedi-lo forro; pois seis anos te serviu por metade do salário do jornaleiro; assim, o SENHOR, teu Deus, te abençoará em tudo o que fizeres.

[[v5-15-19]]

^<<v5-15-19,19>>^ Todo primogênito que nascer do teu gado ou de tuas ovelhas, o macho consagrarás ao SENHOR, teu Deus; com o primogênito do teu gado não trabalharás, nem tosquiarás o primogênito das tuas ovelhas.

[[v5-15-20]]

^<<v5-15-20,20>>^ Comê-lo-ás perante o SENHOR, tu e a tua casa, de ano em ano, no lugar que o SENHOR escolher.

[[v5-15-21]]

^<<v5-15-21,21>>^ Porém, havendo nele algum defeito, se for coxo, ou cego, ou tiver outro defeito grave, não o sacrificarás ao SENHOR, teu Deus.

[[v5-15-22]]

^<<v5-15-22,22>>^ Na tua cidade, o comerás; o imundo e o limpo o comerão juntamente, como a carne do corço ou do veado.

[[v5-15-23]]

^<<v5-15-23,23>>^ Somente o seu sangue não comerás; sobre a terra o derramarás como água.

'''

xref:005-deuteronomio/005-deuteronomio-014.adoc#v5-14-0[&#60; Capítulo Anterior] | <<v5-15-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-016.adoc#v5-16-0[Próximo Capítulo &#62;]