include::./index.adoc[]

[[v5-7-0]]
=== Deuteronômio, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-7-1]]

^<<v5-7-1,1>>^ Quando o SENHOR, teu Deus, te introduzir na terra a qual passas a possuir, e tiver lançado muitas nações de diante de ti, os heteus, e os girgaseus, e os amorreus, e os cananeus, e os ferezeus, e os heveus, e os jebuseus, sete nações mais numerosas e mais poderosas do que tu;

[[v5-7-2]]

^<<v5-7-2,2>>^ e o SENHOR, teu Deus, as tiver dado diante de ti, para as ferir, totalmente as destruirás; não farás com elas aliança, nem terás piedade delas;

[[v5-7-3]]

^<<v5-7-3,3>>^ nem contrairás matrimônio com os filhos dessas nações; não darás tuas filhas a seus filhos, nem tomarás suas filhas para teus filhos;

[[v5-7-4]]

^<<v5-7-4,4>>^ pois elas fariam desviar teus filhos de mim, para que servissem a outros deuses; e a ira do SENHOR se acenderia contra vós outros e depressa vos destruiria.

[[v5-7-5]]

^<<v5-7-5,5>>^ Porém assim lhes fareis: derribareis os seus altares, quebrareis as suas colunas, cortareis os seus postes-ídolos e queimareis as suas imagens de escultura.

[[v5-7-6]]

^<<v5-7-6,6>>^ Porque tu és povo santo ao SENHOR, teu Deus; o SENHOR, teu Deus, te escolheu, para que lhe fosses o seu povo próprio, de todos os povos que há sobre a terra.

[[v5-7-7]]

^<<v5-7-7,7>>^ Não vos teve o SENHOR afeição, nem vos escolheu porque fôsseis mais numerosos do que qualquer povo, pois éreis o menor de todos os povos,

[[v5-7-8]]

^<<v5-7-8,8>>^ mas porque o SENHOR vos amava e, para guardar o juramento que fizera a vossos pais, o SENHOR vos tirou com mão poderosa e vos resgatou da casa da servidão, do poder de Faraó, rei do Egito.

[[v5-7-9]]

^<<v5-7-9,9>>^ Saberás, pois, que o SENHOR, teu Deus, é Deus, o Deus fiel, que guarda a aliança e a misericórdia até mil gerações aos que o amam e cumprem os seus mandamentos;

[[v5-7-10]]

^<<v5-7-10,10>>^ e dá o pago diretamente aos que o odeiam, fazendo-os perecer; não será demorado para com o que o odeia; prontamente, lho retribuirá.

[[v5-7-11]]

^<<v5-7-11,11>>^ Guarda, pois, os mandamentos, e os estatutos, e os juízos que hoje te mando cumprir.

[[v5-7-12]]

^<<v5-7-12,12>>^ Será, pois, que, se, ouvindo estes juízos, os guardares e cumprires, o SENHOR, teu Deus, te guardará a aliança e a misericórdia prometida sob juramento a teus pais;

[[v5-7-13]]

^<<v5-7-13,13>>^ ele te amará, e te abençoará, e te fará multiplicar; também abençoará os teus filhos, e o fruto da tua terra, e o teu cereal, e o teu vinho, e o teu azeite, e as crias das tuas vacas e das tuas ovelhas, na terra que, sob juramento a teus pais, prometeu dar-te.

[[v5-7-14]]

^<<v5-7-14,14>>^ Bendito serás mais do que todos os povos; não haverá entre ti nem homem, nem mulher estéril, nem entre os teus animais.

[[v5-7-15]]

^<<v5-7-15,15>>^ O SENHOR afastará de ti toda enfermidade; sobre ti não porá nenhuma das doenças malignas dos egípcios, que bem sabes; antes, as porá sobre todos os que te odeiam.

[[v5-7-16]]

^<<v5-7-16,16>>^ Consumirás todos os povos que te der o SENHOR, teu Deus; os teus olhos não terão piedade deles, nem servirás a seus deuses, pois isso te seria por ciladas.

[[v5-7-17]]

^<<v5-7-17,17>>^ Se disseres no teu coração: Estas nações são mais numerosas do que eu; como poderei desapossá-las?

[[v5-7-18]]

^<<v5-7-18,18>>^ Delas não tenhas temor; lembrar-te-ás do que o SENHOR, teu Deus, fez a Faraó e a todo o Egito;

[[v5-7-19]]

^<<v5-7-19,19>>^ das grandes provas que viram os teus olhos, e dos sinais, e maravilhas, e mão poderosa, e braço estendido, com que o SENHOR, teu Deus, te tirou; assim fará o SENHOR, teu Deus, com todos os povos, aos quais temes.

[[v5-7-20]]

^<<v5-7-20,20>>^ Além disso, o SENHOR, teu Deus, mandará entre eles vespões, até que pereçam os que ficarem e se esconderem de diante de ti.

[[v5-7-21]]

^<<v5-7-21,21>>^ Não te espantes diante deles, porque o SENHOR, teu Deus, está no meio de ti, Deus grande e temível.

[[v5-7-22]]

^<<v5-7-22,22>>^ O SENHOR, teu Deus, lançará fora estas nações, pouco a pouco, de diante de ti; não poderás destruí-las todas de pronto, para que as feras do campo se não multipliquem contra ti.

[[v5-7-23]]

^<<v5-7-23,23>>^ Mas o SENHOR, teu Deus, tas entregará e lhes infligirá grande confusão, até que sejam destruídas.

[[v5-7-24]]

^<<v5-7-24,24>>^ Entregar-te-á também nas mãos os seus reis, para que apagues o nome deles de debaixo dos céus; nenhum homem poderá resistir-te, até que os destruas.

[[v5-7-25]]

^<<v5-7-25,25>>^ As imagens de escultura de seus deuses queimarás; a prata e o ouro que estão sobre elas não cobiçarás, nem os tomarás para ti, para que te não enlaces neles; pois são abominação ao SENHOR, teu Deus.

[[v5-7-26]]

^<<v5-7-26,26>>^ Não meterás, pois, coisa abominável em tua casa, para que não sejas amaldiçoado, semelhante a ela; de todo, a detestarás e, de todo, a abominarás, pois é amaldiçoada.

'''

xref:005-deuteronomio/005-deuteronomio-006.adoc#v5-6-0[&#60; Capítulo Anterior] | <<v5-7-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-008.adoc#v5-8-0[Próximo Capítulo &#62;]