include::./index.adoc[]

[[v5-1-0]]
=== Deuteronômio, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-1-1]]

^<<v5-1-1,1>>^ São estas as palavras que Moisés falou a todo o Israel, dalém do Jordão, no deserto, na Arabá, defronte do mar de Sufe, entre Parã, Tofel, Labã, Hazerote e Di-Zaabe.

[[v5-1-2]]

^<<v5-1-2,2>>^ Jornada de onze dias há desde Horebe, pelo caminho da montanha de Seir, até Cades-Barneia.

[[v5-1-3]]

^<<v5-1-3,3>>^ Sucedeu que, no ano quadragésimo, no primeiro dia do undécimo mês, falou Moisés aos filhos de Israel, segundo tudo o que o SENHOR lhe mandara a respeito deles,

[[v5-1-4]]

^<<v5-1-4,4>>^ depois que feriu a Seom, rei dos amorreus, que habitava em Hesbom, e a Ogue, rei de Basã, que habitava em Astarote, em Edrei.

[[v5-1-5]]

^<<v5-1-5,5>>^ Além do Jordão, na terra de Moabe, encarregou-se Moisés de explicar esta lei, dizendo:

[[v5-1-6]]

^<<v5-1-6,6>>^ O SENHOR, nosso Deus, nos falou em Horebe, dizendo: Tempo bastante haveis estado neste monte.

[[v5-1-7]]

^<<v5-1-7,7>>^ Voltai-vos e parti; ide à região montanhosa dos amorreus, e a todos os seus vizinhos, na Arabá, e à região montanhosa, e à baixada, e ao Neguebe, e à costa marítima, terra dos cananeus, e ao Líbano, até ao grande rio Eufrates.

[[v5-1-8]]

^<<v5-1-8,8>>^ Eis aqui a terra que eu pus diante de vós; entrai e possuí a terra que o SENHOR, com juramento, deu a vossos pais, Abraão, Isaque e Jacó, a eles e à sua descendência depois deles.

[[v5-1-9]]

^<<v5-1-9,9>>^ Nesse mesmo tempo, eu vos disse: eu sozinho não poderei levar-vos.

[[v5-1-10]]

^<<v5-1-10,10>>^ O SENHOR, vosso Deus, vos tem multiplicado; e eis que, já hoje, sois multidão como as estrelas dos céus.

[[v5-1-11]]

^<<v5-1-11,11>>^ O SENHOR, Deus de vossos pais, vos faça mil vezes mais numerosos do que sois e vos abençoe, como vos prometeu.

[[v5-1-12]]

^<<v5-1-12,12>>^ Como suportaria eu sozinho o vosso peso, a vossa carga e a vossa contenda?

[[v5-1-13]]

^<<v5-1-13,13>>^ Tomai-vos homens sábios, inteligentes e experimentados, segundo as vossas tribos, para que os ponha por vossos cabeças.

[[v5-1-14]]

^<<v5-1-14,14>>^ Então, me respondestes e dissestes: É bom cumprir a palavra que tens falado.

[[v5-1-15]]

^<<v5-1-15,15>>^ Tomei, pois, os cabeças de vossas tribos, homens sábios e experimentados, e os fiz cabeças sobre vós, chefes de milhares, chefes de cem, chefes de cinquenta, chefes de dez e oficiais, segundo as vossas tribos.

[[v5-1-16]]

^<<v5-1-16,16>>^ Nesse mesmo tempo, ordenei a vossos juízes, dizendo: ouvi a causa entre vossos irmãos e julgai justamente entre o homem e seu irmão ou o estrangeiro que está com ele.

[[v5-1-17]]

^<<v5-1-17,17>>^ Não sereis parciais no juízo, ouvireis tanto o pequeno como o grande; não temereis a face de ninguém, porque o juízo é de Deus; porém a causa que vos for demasiadamente difícil fareis vir a mim, e eu a ouvirei.

[[v5-1-18]]

^<<v5-1-18,18>>^ Assim, naquele tempo, vos ordenei todas as coisas que havíeis de fazer.

[[v5-1-19]]

^<<v5-1-19,19>>^ Então, partimos de Horebe e caminhamos por todo aquele grande e terrível deserto que vistes, pelo caminho da região montanhosa dos amorreus, como o SENHOR, nosso Deus, nos ordenara; e chegamos a Cades-Barneia.

[[v5-1-20]]

^<<v5-1-20,20>>^ Então, eu vos disse: tendes chegado à região montanhosa dos amorreus, que o SENHOR, nosso Deus, nos dá.

[[v5-1-21]]

^<<v5-1-21,21>>^ Eis que o SENHOR, teu Deus, te colocou esta terra diante de ti. Sobe, possui-a, como te falou o SENHOR, Deus de teus pais: Não temas e não te assustes.

[[v5-1-22]]

^<<v5-1-22,22>>^ Então, todos vós vos chegastes a mim e dissestes: Mandemos homens adiante de nós, para que nos espiem a terra e nos digam por que caminho devemos subir e a que cidades devemos ir.

[[v5-1-23]]

^<<v5-1-23,23>>^ Isto me pareceu bem; de maneira que tomei, dentre vós, doze homens, de cada tribo um homem.

[[v5-1-24]]

^<<v5-1-24,24>>^ E foram-se, e subiram à região montanhosa, e, espiando a terra, vieram até o vale de Escol,

[[v5-1-25]]

^<<v5-1-25,25>>^ e tomaram do fruto da terra nas mãos, e no-lo trouxeram, e nos informaram, dizendo: É terra boa que nos dá o SENHOR, nosso Deus.

[[v5-1-26]]

^<<v5-1-26,26>>^ Porém vós não quisestes subir, mas fostes rebeldes à ordem do SENHOR, vosso Deus.

[[v5-1-27]]

^<<v5-1-27,27>>^ Murmurastes nas vossas tendas e dissestes: Tem o SENHOR contra nós ódio; por isso, nos tirou da terra do Egito para nos entregar nas mãos dos amorreus e destruir-nos.

[[v5-1-28]]

^<<v5-1-28,28>>^ Para onde subiremos? Nossos irmãos fizeram com que se derretesse o nosso coração, dizendo: Maior e mais alto do que nós é este povo; as cidades são grandes e fortificadas até aos céus. Também vimos ali os filhos dos anaquins.

[[v5-1-29]]

^<<v5-1-29,29>>^ Então, eu vos disse: não vos espanteis, nem os temais.

[[v5-1-30]]

^<<v5-1-30,30>>^ O SENHOR, vosso Deus, que vai adiante de vós, ele pelejará por vós, segundo tudo o que fez conosco, diante de vossos olhos, no Egito,

[[v5-1-31]]

^<<v5-1-31,31>>^ como também no deserto, onde vistes que o SENHOR, vosso Deus, nele vos levou, como um homem leva a seu filho, por todo o caminho pelo qual andastes, até chegardes a este lugar.

[[v5-1-32]]

^<<v5-1-32,32>>^ Mas nem por isso crestes no SENHOR, vosso Deus,

[[v5-1-33]]

^<<v5-1-33,33>>^ que foi adiante de vós por todo o caminho, para vos procurar o lugar onde deveríeis acampar; de noite, no fogo, para vos mostrar o caminho por onde havíeis de andar, e, de dia, na nuvem.

[[v5-1-34]]

^<<v5-1-34,34>>^ Tendo, pois, ouvido o SENHOR as vossas palavras, indignou-se e jurou, dizendo:

[[v5-1-35]]

^<<v5-1-35,35>>^ Certamente, nenhum dos homens desta maligna geração verá a boa terra que jurei dar a vossos pais,

[[v5-1-36]]

^<<v5-1-36,36>>^ salvo Calebe, filho de Jefoné; ele a verá, e a terra que pisou darei a ele e a seus filhos, porquanto perseverou em seguir ao SENHOR.

[[v5-1-37]]

^<<v5-1-37,37>>^ Também contra mim se indignou o SENHOR por causa de vós, dizendo: Também tu lá não entrarás.

[[v5-1-38]]

^<<v5-1-38,38>>^ Josué, filho de Num, que está diante de ti, ele ali entrará; anima-o, porque ele fará que Israel a receba por herança.

[[v5-1-39]]

^<<v5-1-39,39>>^ E vossos meninos, de quem dissestes: Por presa serão; e vossos filhos, que, hoje, nem sabem distinguir entre bem e mal, esses ali entrarão, e a eles darei a terra, e eles a possuirão.

[[v5-1-40]]

^<<v5-1-40,40>>^ Porém vós virai-vos e parti para o deserto, pelo caminho do mar Vermelho.

[[v5-1-41]]

^<<v5-1-41,41>>^ Então, respondestes e me dissestes: Pecamos contra o SENHOR; nós subiremos e pelejaremos, segundo tudo o que nos ordenou o SENHOR, nosso Deus. Vós vos armastes, cada um dos seus instrumentos de guerra, e vos mostrastes temerários em subindo à região montanhosa.

[[v5-1-42]]

^<<v5-1-42,42>>^ Disse-me o SENHOR: Dize-lhes: Não subais, nem pelejeis, pois não estou no meio de vós, para que não sejais derrotados diante dos vossos inimigos.

[[v5-1-43]]

^<<v5-1-43,43>>^ Assim vos falei, e não escutastes; antes, fostes rebeldes às ordens do SENHOR e, presunçosos, subistes às montanhas.

[[v5-1-44]]

^<<v5-1-44,44>>^ Os amorreus que habitavam naquela região montanhosa vos saíram ao encontro; e vos perseguiram como fazem as abelhas e vos derrotaram desde Seir até Horma.

[[v5-1-45]]

^<<v5-1-45,45>>^ Tornastes-vos, pois, e chorastes perante o SENHOR, porém o SENHOR não vos ouviu, não inclinou os ouvidos a vós outros.

[[v5-1-46]]

^<<v5-1-46,46>>^ Assim, permanecestes muitos dias em Cades.

'''

xref:004-numeros/004-numeros-036.adoc#v4-36-0[&#60; Capítulo Anterior] | <<v5-1-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-002.adoc#v5-2-0[Próximo Capítulo &#62;]