include::./index.adoc[]

[[v5-12-0]]
=== Deuteronômio, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-12-1]]

^<<v5-12-1,1>>^ São estes os estatutos e os juízos que cuidareis de cumprir na terra que vos deu o SENHOR, Deus de vossos pais, para a possuirdes todos os dias que viverdes sobre a terra.

[[v5-12-2]]

^<<v5-12-2,2>>^ Destruireis por completo todos os lugares onde as nações que ides desapossar serviram aos seus deuses, sobre as altas montanhas, sobre os outeiros e debaixo de toda árvore frondosa;

[[v5-12-3]]

^<<v5-12-3,3>>^ deitareis abaixo os seus altares, e despedaçareis as suas colunas, e os seus postes-ídolos queimareis, e despedaçareis as imagens esculpidas dos seus deuses, e apagareis o seu nome daquele lugar.

[[v5-12-4]]

^<<v5-12-4,4>>^ Não fareis assim para com o SENHOR, vosso Deus,

[[v5-12-5]]

^<<v5-12-5,5>>^ mas buscareis o lugar que o SENHOR, vosso Deus, escolher de todas as vossas tribos, para ali pôr o seu nome e sua habitação; e para lá ireis.

[[v5-12-6]]

^<<v5-12-6,6>>^ A esse lugar fareis chegar os vossos holocaustos, e os vossos sacrifícios, e os vossos dízimos, e a oferta das vossas mãos, e as ofertas votivas, e as ofertas voluntárias, e os primogênitos das vossas vacas e das vossas ovelhas.

[[v5-12-7]]

^<<v5-12-7,7>>^ Lá, comereis perante o SENHOR, vosso Deus, e vos alegrareis em tudo o que fizerdes, vós e as vossas casas, no que vos tiver abençoado o SENHOR, vosso Deus.

[[v5-12-8]]

^<<v5-12-8,8>>^ Não procedereis em nada segundo estamos fazendo aqui, cada qual tudo o que bem parece aos seus olhos,

[[v5-12-9]]

^<<v5-12-9,9>>^ porque, até agora, não entrastes no descanso e na herança que vos dá o SENHOR, vosso Deus.

[[v5-12-10]]

^<<v5-12-10,10>>^ Mas passareis o Jordão e habitareis na terra que vos fará herdar o SENHOR, vosso Deus; e vos dará descanso de todos os vossos inimigos em redor, e morareis seguros.

[[v5-12-11]]

^<<v5-12-11,11>>^ Então, haverá um lugar que escolherá o SENHOR, vosso Deus, para ali fazer habitar o seu nome; a esse lugar fareis chegar tudo o que vos ordeno: os vossos holocaustos, e os vossos sacrifícios, e os vossos dízimos, e a oferta das vossas mãos, e toda escolha dos vossos votos feitos ao SENHOR,

[[v5-12-12]]

^<<v5-12-12,12>>^ e vos alegrareis perante o SENHOR, vosso Deus, vós, os vossos filhos, as vossas filhas, os vossos servos, as vossas servas e o levita que mora dentro das vossas cidades e que não tem porção nem herança convosco.

[[v5-12-13]]

^<<v5-12-13,13>>^ Guarda-te, não ofereças os teus holocaustos em todo lugar que vires;

[[v5-12-14]]

^<<v5-12-14,14>>^ mas, no lugar que o SENHOR escolher numa das tuas tribos, ali oferecerás os teus holocaustos e ali farás tudo o que te ordeno.

[[v5-12-15]]

^<<v5-12-15,15>>^ Porém, consoante todo desejo da tua alma, poderás matar e comer carne nas tuas cidades, segundo a bênção do SENHOR, teu Deus; o imundo e o limpo dela comerão, assim como se come da carne do corço e do veado.

[[v5-12-16]]

^<<v5-12-16,16>>^ Tão somente o sangue não comerás; sobre a terra o derramarás como água.

[[v5-12-17]]

^<<v5-12-17,17>>^ Nas tuas cidades, não poderás comer o dízimo do teu cereal, nem do teu vinho, nem do teu azeite, nem os primogênitos das tuas vacas, nem das tuas ovelhas, nem nenhuma das tuas ofertas votivas, que houveres prometido, nem as tuas ofertas voluntárias, nem as ofertas das tuas mãos;

[[v5-12-18]]

^<<v5-12-18,18>>^ mas o comerás perante o SENHOR, teu Deus, no lugar que o SENHOR, teu Deus, escolher, tu, e teu filho, e tua filha, e teu servo, e tua serva, e o levita que mora na tua cidade; e perante o SENHOR, teu Deus, te alegrarás em tudo o que fizeres.

[[v5-12-19]]

^<<v5-12-19,19>>^ Guarda-te, não desampares o levita todos os teus dias na terra.

[[v5-12-20]]

^<<v5-12-20,20>>^ Quando o SENHOR, teu Deus, alargar o teu território, como te prometeu, e, por desejares comer carne, disseres: Comerei carne, então, segundo o teu desejo, comerás carne.

[[v5-12-21]]

^<<v5-12-21,21>>^ Se estiver longe de ti o lugar que o SENHOR, teu Deus, escolher para nele pôr o seu nome, então, matarás das tuas vacas e tuas ovelhas, que o SENHOR te houver dado, como te ordenei; e comerás dentro da tua cidade, segundo todo o teu desejo.

[[v5-12-22]]

^<<v5-12-22,22>>^ Porém, como se come da carne do corço e do veado, assim comerás destas carnes; destas comerá tanto o homem imundo como o limpo.

[[v5-12-23]]

^<<v5-12-23,23>>^ Somente empenha-te em não comeres o sangue, pois o sangue é a vida; pelo que não comerás a vida com a carne.

[[v5-12-24]]

^<<v5-12-24,24>>^ Não o comerás; na terra o derramarás como água.

[[v5-12-25]]

^<<v5-12-25,25>>^ Não o comerás, para que bem te suceda a ti e a teus filhos, depois de ti, quando fizeres o que é reto aos olhos do SENHOR.

[[v5-12-26]]

^<<v5-12-26,26>>^ Porém tomarás o que houveres consagrado daquilo que te pertence e as tuas ofertas votivas e virás ao lugar que o SENHOR escolher.

[[v5-12-27]]

^<<v5-12-27,27>>^ E oferecerás os teus holocaustos, a carne e o sangue sobre o altar do SENHOR, teu Deus; e o sangue dos teus sacrifícios se derramará sobre o altar do SENHOR, teu Deus; porém a carne comerás.

[[v5-12-28]]

^<<v5-12-28,28>>^ Guarda e cumpre todas estas palavras que te ordeno, para que bem te suceda a ti e a teus filhos, depois de ti, para sempre, quando fizeres o que é bom e reto aos olhos do SENHOR, teu Deus.

[[v5-12-29]]

^<<v5-12-29,29>>^ Quando o SENHOR, teu Deus, eliminar de diante de ti as nações, para as quais vais para possuí-las, e as desapossares e habitares na sua terra,

[[v5-12-30]]

^<<v5-12-30,30>>^ guarda-te, não te enlaces com imitá-las, após terem sido destruídas diante de ti; e que não indagues acerca dos seus deuses, dizendo: Assim como serviram estas nações aos seus deuses, do mesmo modo também farei eu.

[[v5-12-31]]

^<<v5-12-31,31>>^ Não farás assim ao SENHOR, teu Deus, porque tudo o que é abominável ao SENHOR e que ele odeia fizeram eles a seus deuses, pois até seus filhos e suas filhas queimaram aos seus deuses.

[[v5-12-32]]

^<<v5-12-32,32>>^ Tudo o que eu te ordeno observarás; nada lhe acrescentarás, nem diminuirás.

'''

xref:005-deuteronomio/005-deuteronomio-011.adoc#v5-11-0[&#60; Capítulo Anterior] | <<v5-12-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-013.adoc#v5-13-0[Próximo Capítulo &#62;]