include::./index.adoc[]

[[v5-10-0]]
=== Deuteronômio, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-10-1]]

^<<v5-10-1,1>>^ Naquele tempo, me disse o SENHOR: Lavra duas tábuas de pedra, como as primeiras, e sobe a mim ao monte, e faze uma arca de madeira.

[[v5-10-2]]

^<<v5-10-2,2>>^ Escreverei nas duas tábuas as palavras que estavam nas primeiras que quebraste, e as porás na arca.

[[v5-10-3]]

^<<v5-10-3,3>>^ Assim, fiz uma arca de madeira de acácia, lavrei duas tábuas de pedra, como as primeiras, e subi ao monte com as duas tábuas na mão.

[[v5-10-4]]

^<<v5-10-4,4>>^ Então, escreveu o SENHOR nas tábuas, segundo a primeira escritura, os dez mandamentos que ele vos falara no dia da congregação, no monte, no meio do fogo; e o SENHOR mas deu a mim.

[[v5-10-5]]

^<<v5-10-5,5>>^ Virei-me, e desci do monte, e pus as tábuas na arca que eu fizera; e ali estão, como o SENHOR me ordenou.

[[v5-10-6]]

^<<v5-10-6,6>>^ Partiram os filhos de Israel de Beerote-Benê-Jaacã para Mosera. Ali faleceu Arão e ali foi sepultado. Eleazar, seu filho, oficiou como sacerdote em seu lugar.

[[v5-10-7]]

^<<v5-10-7,7>>^ Dali partiram para Gudgoda e de Gudgoda para Jotbatá, terra de ribeiros de águas.

[[v5-10-8]]

^<<v5-10-8,8>>^ Por esse mesmo tempo, o SENHOR separou a tribo de Levi para levar a arca da Aliança do SENHOR, para estar diante do SENHOR, para o servir e para abençoar em seu nome até ao dia de hoje.

[[v5-10-9]]

^<<v5-10-9,9>>^ Pelo que Levi não tem parte nem herança com seus irmãos; o SENHOR é a sua herança, como o SENHOR, teu Deus, lhe tem prometido.

[[v5-10-10]]

^<<v5-10-10,10>>^ Permaneci no monte, como da primeira vez, quarenta dias e quarenta noites; o SENHOR me ouviu ainda por esta vez; não quis o SENHOR destruir-te.

[[v5-10-11]]

^<<v5-10-11,11>>^ Porém o SENHOR me disse: Levanta-te, põe-te a caminho diante do povo, para que entre e possua a terra que, sob juramento, prometi dar a seus pais.

[[v5-10-12]]

^<<v5-10-12,12>>^ Agora, pois, ó Israel, que é que o SENHOR requer de ti? Não é que temas o SENHOR, teu Deus, e andes em todos os seus caminhos, e o ames, e sirvas ao SENHOR, teu Deus, de todo o teu coração e de toda a tua alma,

[[v5-10-13]]

^<<v5-10-13,13>>^ para guardares os mandamentos do SENHOR e os seus estatutos que hoje te ordeno, para o teu bem?

[[v5-10-14]]

^<<v5-10-14,14>>^ Eis que os céus e os céus dos céus são do SENHOR, teu Deus, a terra e tudo o que nela há.

[[v5-10-15]]

^<<v5-10-15,15>>^ Tão somente o SENHOR se afeiçoou a teus pais para os amar; a vós outros, descendentes deles, escolheu de todos os povos, como hoje se vê.

[[v5-10-16]]

^<<v5-10-16,16>>^ Circuncidai, pois, o vosso coração e não mais endureçais a vossa cerviz.

[[v5-10-17]]

^<<v5-10-17,17>>^ Pois o SENHOR, vosso Deus, é o Deus dos deuses e o Senhor dos senhores, o Deus grande, poderoso e temível, que não faz acepção de pessoas, nem aceita suborno;

[[v5-10-18]]

^<<v5-10-18,18>>^ que faz justiça ao órfão e à viúva e ama o estrangeiro, dando-lhe pão e vestes.

[[v5-10-19]]

^<<v5-10-19,19>>^ Amai, pois, o estrangeiro, porque fostes estrangeiros na terra do Egito.

[[v5-10-20]]

^<<v5-10-20,20>>^ Ao SENHOR, teu Deus, temerás; a ele servirás, a ele te chegarás e, pelo seu nome, jurarás.

[[v5-10-21]]

^<<v5-10-21,21>>^ Ele é o teu louvor e o teu Deus, que te fez estas grandes e temíveis coisas que os teus olhos têm visto.

[[v5-10-22]]

^<<v5-10-22,22>>^ Com setenta almas, teus pais desceram ao Egito; e, agora, o SENHOR, teu Deus, te pôs como as estrelas dos céus em multidão.

'''

xref:005-deuteronomio/005-deuteronomio-009.adoc#v5-9-0[&#60; Capítulo Anterior] | <<v5-10-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-011.adoc#v5-11-0[Próximo Capítulo &#62;]