include::./index.adoc[]

[[v5-6-0]]
=== Deuteronômio, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-6-1]]

^<<v5-6-1,1>>^ Estes, pois, são os mandamentos, os estatutos e os juízos que mandou o SENHOR, teu Deus, se te ensinassem, para que os cumprisses na terra a que passas para a possuir;

[[v5-6-2]]

^<<v5-6-2,2>>^ para que temas ao SENHOR, teu Deus, e guardes todos os seus estatutos e mandamentos que eu te ordeno, tu, e teu filho, e o filho de teu filho, todos os dias da tua vida; e que teus dias sejam prolongados.

[[v5-6-3]]

^<<v5-6-3,3>>^ Ouve, pois, ó Israel, e atenta em os cumprires, para que bem te suceda, e muito te multipliques na terra que mana leite e mel, como te disse o SENHOR, Deus de teus pais.

[[v5-6-4]]

^<<v5-6-4,4>>^ Ouve, Israel, o SENHOR, nosso Deus, é o único SENHOR.

[[v5-6-5]]

^<<v5-6-5,5>>^ Amarás, pois, o SENHOR, teu Deus, de todo o teu coração, de toda a tua alma e de toda a tua força.

[[v5-6-6]]

^<<v5-6-6,6>>^ Estas palavras que, hoje, te ordeno estarão no teu coração;

[[v5-6-7]]

^<<v5-6-7,7>>^ tu as inculcarás a teus filhos, e delas falarás assentado em tua casa, e andando pelo caminho, e ao deitar-te, e ao levantar-te.

[[v5-6-8]]

^<<v5-6-8,8>>^ Também as atarás como sinal na tua mão, e te serão por frontal entre os olhos.

[[v5-6-9]]

^<<v5-6-9,9>>^ E as escreverás nos umbrais de tua casa e nas tuas portas.

[[v5-6-10]]

^<<v5-6-10,10>>^ Havendo-te, pois, o SENHOR, teu Deus, introduzido na terra que, sob juramento, prometeu a teus pais, Abraão, Isaque e Jacó, te daria, grandes e boas cidades, que tu não edificaste;

[[v5-6-11]]

^<<v5-6-11,11>>^ e casas cheias de tudo o que é bom, casas que não encheste; e poços abertos, que não abriste; vinhais e olivais, que não plantaste; e, quando comeres e te fartares,

[[v5-6-12]]

^<<v5-6-12,12>>^ guarda-te, para que não esqueças o SENHOR, que te tirou da terra do Egito, da casa da servidão.

[[v5-6-13]]

^<<v5-6-13,13>>^ O SENHOR, teu Deus, temerás, a ele servirás, e, pelo seu nome, jurarás.

[[v5-6-14]]

^<<v5-6-14,14>>^ Não seguirás outros deuses, nenhum dos deuses dos povos que houver à roda de ti,

[[v5-6-15]]

^<<v5-6-15,15>>^ porque o SENHOR, teu Deus, é Deus zeloso no meio de ti, para que a ira do SENHOR, teu Deus, se não acenda contra ti e te destrua de sobre a face da terra.

[[v5-6-16]]

^<<v5-6-16,16>>^ Não tentarás o SENHOR, teu Deus, como o tentaste em Massá.

[[v5-6-17]]

^<<v5-6-17,17>>^ Diligentemente, guardarás os mandamentos do SENHOR, teu Deus, e os seus testemunhos, e os seus estatutos que te ordenou.

[[v5-6-18]]

^<<v5-6-18,18>>^ Farás o que é reto e bom aos olhos do SENHOR, para que bem te suceda, e entres, e possuas a boa terra a qual o SENHOR, sob juramento, prometeu dar a teus pais,

[[v5-6-19]]

^<<v5-6-19,19>>^ lançando todos os teus inimigos de diante de ti, como o SENHOR tem dito.

[[v5-6-20]]

^<<v5-6-20,20>>^ Quando teu filho, no futuro, te perguntar, dizendo: Que significam os testemunhos, e estatutos, e juízos que o SENHOR, nosso Deus, vos ordenou?

[[v5-6-21]]

^<<v5-6-21,21>>^ Então, dirás a teu filho: Éramos servos de Faraó, no Egito; porém o SENHOR de lá nos tirou com poderosa mão.

[[v5-6-22]]

^<<v5-6-22,22>>^ Aos nossos olhos fez o SENHOR sinais e maravilhas, grandes e terríveis, contra o Egito e contra Faraó e toda a sua casa;

[[v5-6-23]]

^<<v5-6-23,23>>^ e dali nos tirou, para nos levar e nos dar a terra que sob juramento prometeu a nossos pais.

[[v5-6-24]]

^<<v5-6-24,24>>^ O SENHOR nos ordenou cumpríssemos todos estes estatutos e temêssemos o SENHOR, nosso Deus, para o nosso perpétuo bem, para nos guardar em vida, como tem feito até hoje.

[[v5-6-25]]

^<<v5-6-25,25>>^ Será por nós justiça, quando tivermos cuidado de cumprir todos estes mandamentos perante o SENHOR, nosso Deus, como nos tem ordenado.

'''

xref:005-deuteronomio/005-deuteronomio-005.adoc#v5-5-0[&#60; Capítulo Anterior] | <<v5-6-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-007.adoc#v5-7-0[Próximo Capítulo &#62;]