include::./index.adoc[]

[[v5-5-0]]
=== Deuteronômio, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-5-1]]

^<<v5-5-1,1>>^ Chamou Moisés a todo o Israel e disse-lhe: Ouvi, ó Israel, os estatutos e juízos que hoje vos falo aos ouvidos, para que os aprendais e cuideis em os cumprirdes.

[[v5-5-2]]

^<<v5-5-2,2>>^ O SENHOR, nosso Deus, fez aliança conosco em Horebe.

[[v5-5-3]]

^<<v5-5-3,3>>^ Não foi com nossos pais que fez o SENHOR esta aliança, e sim conosco, todos os que, hoje, aqui estamos vivos.

[[v5-5-4]]

^<<v5-5-4,4>>^ Face a face falou o SENHOR conosco, no monte, do meio do fogo

[[v5-5-5]]

^<<v5-5-5,5>>^ (Nesse tempo, eu estava em pé entre o SENHOR e vós, para vos notificar a palavra do SENHOR, porque temestes o fogo e não subistes ao monte.), dizendo:

[[v5-5-6]]

^<<v5-5-6,6>>^ Eu sou o SENHOR, teu Deus, que te tirei do Egito, da casa da servidão.

[[v5-5-7]]

^<<v5-5-7,7>>^ Não terás outros deuses diante de mim.

[[v5-5-8]]

^<<v5-5-8,8>>^ Não farás para ti imagem de escultura, nem semelhança alguma do que há em cima no céu, nem embaixo na terra, nem nas águas debaixo da terra;

[[v5-5-9]]

^<<v5-5-9,9>>^ não as adorarás, nem lhes darás culto; porque eu, o SENHOR, teu Deus, sou Deus zeloso, que visito a iniquidade dos pais nos filhos até a terceira e quarta geração daqueles que me aborrecem,

[[v5-5-10]]

^<<v5-5-10,10>>^ e faço misericórdia até mil gerações daqueles que me amam e guardam os meus mandamentos.

[[v5-5-11]]

^<<v5-5-11,11>>^ Não tomarás o nome do SENHOR, teu Deus, em vão, porque o SENHOR não terá por inocente o que tomar o seu nome em vão.

[[v5-5-12]]

^<<v5-5-12,12>>^ Guarda o dia de sábado, para o santificar, como te ordenou o SENHOR, teu Deus.

[[v5-5-13]]

^<<v5-5-13,13>>^ Seis dias trabalharás e farás toda a tua obra.

[[v5-5-14]]

^<<v5-5-14,14>>^ Mas o sétimo dia é o sábado do SENHOR, teu Deus; não farás nenhum trabalho, nem tu, nem o teu filho, nem a tua filha, nem o teu servo, nem a tua serva, nem o teu boi, nem o teu jumento, nem animal algum teu, nem o estrangeiro das tuas portas para dentro, para que o teu servo e a tua serva descansem como tu;

[[v5-5-15]]

^<<v5-5-15,15>>^ porque te lembrarás que foste servo na terra do Egito e que o SENHOR, teu Deus, te tirou dali com mão poderosa e braço estendido; pelo que o SENHOR, teu Deus, te ordenou que guardasses o dia de sábado.

[[v5-5-16]]

^<<v5-5-16,16>>^ Honra a teu pai e a tua mãe, como o SENHOR, teu Deus, te ordenou, para que se prolonguem os teus dias e para que te vá bem na terra que o SENHOR, teu Deus, te dá.

[[v5-5-17]]

^<<v5-5-17,17>>^ Não matarás.

[[v5-5-18]]

^<<v5-5-18,18>>^ Não adulterarás.

[[v5-5-19]]

^<<v5-5-19,19>>^ Não furtarás.

[[v5-5-20]]

^<<v5-5-20,20>>^ Não dirás falso testemunho contra o teu próximo.

[[v5-5-21]]

^<<v5-5-21,21>>^ Não cobiçarás a mulher do teu próximo. Não desejarás a casa do teu próximo, nem o seu campo, nem o seu servo, nem a sua serva, nem o seu boi, nem o seu jumento, nem coisa alguma do teu próximo.

[[v5-5-22]]

^<<v5-5-22,22>>^ Estas palavras falou o SENHOR a toda a vossa congregação no monte, do meio do fogo, da nuvem e da escuridade, com grande voz, e nada acrescentou. Tendo-as escrito em duas tábuas de pedra, deu-mas a mim.

[[v5-5-23]]

^<<v5-5-23,23>>^ Sucedeu que, ouvindo a voz do meio das trevas, enquanto ardia o monte em fogo, vos achegastes a mim, todos os cabeças das vossas tribos e vossos anciãos,

[[v5-5-24]]

^<<v5-5-24,24>>^ e dissestes: Eis aqui o SENHOR, nosso Deus, nos fez ver a sua glória e a sua grandeza, e ouvimos a sua voz do meio do fogo; hoje, vimos que Deus fala com o homem, e este permanece vivo.

[[v5-5-25]]

^<<v5-5-25,25>>^ Agora, pois, por que morreríamos? Pois este grande fogo nos consumiria; se ainda mais ouvíssemos a voz do SENHOR, nosso Deus, morreríamos.

[[v5-5-26]]

^<<v5-5-26,26>>^ Porque quem há, de toda carne, que tenha ouvido a voz do Deus vivo falar do meio do fogo, como nós ouvimos, e permanecido vivo?

[[v5-5-27]]

^<<v5-5-27,27>>^ Chega-te, e ouve tudo o que disser o SENHOR, nosso Deus; e tu nos dirás tudo o que te disser o SENHOR, nosso Deus, e o ouviremos, e o cumpriremos.

[[v5-5-28]]

^<<v5-5-28,28>>^ Ouvindo, pois, o SENHOR as vossas palavras, quando me faláveis a mim, o SENHOR me disse: Eu ouvi as palavras deste povo, as quais te disseram; em tudo falaram eles bem.

[[v5-5-29]]

^<<v5-5-29,29>>^ Quem dera que eles tivessem tal coração, que me temessem e guardassem em todo o tempo todos os meus mandamentos, para que bem lhes fosse a eles e a seus filhos, para sempre!

[[v5-5-30]]

^<<v5-5-30,30>>^ Vai, dize-lhes: Tornai-vos às vossas tendas.

[[v5-5-31]]

^<<v5-5-31,31>>^ Tu, porém, fica-te aqui comigo, e eu te direi todos os mandamentos, e estatutos, e juízos que tu lhes hás de ensinar que cumpram na terra que eu lhes darei para possuí-la.

[[v5-5-32]]

^<<v5-5-32,32>>^ Cuidareis em fazerdes como vos mandou o SENHOR, vosso Deus; não vos desviareis, nem para a direita, nem para a esquerda.

[[v5-5-33]]

^<<v5-5-33,33>>^ Andareis em todo o caminho que vos manda o SENHOR, vosso Deus, para que vivais, bem vos suceda, e prolongueis os dias na terra que haveis de possuir.

'''

xref:005-deuteronomio/005-deuteronomio-004.adoc#v5-4-0[&#60; Capítulo Anterior] | <<v5-5-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-006.adoc#v5-6-0[Próximo Capítulo &#62;]