include::./index.adoc[]

[[v5-14-0]]
=== Deuteronômio, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-14-1]]

^<<v5-14-1,1>>^ Filhos sois do SENHOR, vosso Deus; não vos dareis golpes, nem sobre a testa fareis calva por causa de algum morto.

[[v5-14-2]]

^<<v5-14-2,2>>^ Porque sois povo santo ao SENHOR, vosso Deus, e o SENHOR vos escolheu de todos os povos que há sobre a face da terra, para lhe serdes seu povo próprio.

[[v5-14-3]]

^<<v5-14-3,3>>^ Não comereis coisa alguma abominável.

[[v5-14-4]]

^<<v5-14-4,4>>^ São estes os animais que comereis: o boi, a ovelha, a cabra,

[[v5-14-5]]

^<<v5-14-5,5>>^ o veado, a gazela, a corça, a cabra montês, o antílope, a ovelha montês e o gamo.

[[v5-14-6]]

^<<v5-14-6,6>>^ Todo animal que tem unhas fendidas, e o casco se divide em dois, e rumina, entre os animais, isso comereis.

[[v5-14-7]]

^<<v5-14-7,7>>^ Porém estes não comereis, dos que somente ruminam ou que têm a unha fendida: o camelo, a lebre e o arganaz, porque ruminam, mas não têm a unha fendida; imundos vos serão.

[[v5-14-8]]

^<<v5-14-8,8>>^ Nem o porco, porque tem unha fendida, mas não rumina; imundo vos será. Destes não comereis a carne e não tocareis no seu cadáver.

[[v5-14-9]]

^<<v5-14-9,9>>^ Isto comereis de tudo o que há nas águas: tudo o que tem barbatanas e escamas.

[[v5-14-10]]

^<<v5-14-10,10>>^ Mas tudo o que não tiver barbatanas nem escamas não o comereis; imundo vos será.

[[v5-14-11]]

^<<v5-14-11,11>>^ Toda ave limpa comereis.

[[v5-14-12]]

^<<v5-14-12,12>>^ Estas, porém, são as que não comereis: a águia, o quebrantosso, a águia marinha,

[[v5-14-13]]

^<<v5-14-13,13>>^ o açor, o falcão e o milhano, segundo a sua espécie;

[[v5-14-14]]

^<<v5-14-14,14>>^ e todo corvo, segundo a sua espécie;

[[v5-14-15]]

^<<v5-14-15,15>>^ o avestruz, a coruja, a gaivota e o gavião, segundo a sua espécie;

[[v5-14-16]]

^<<v5-14-16,16>>^ o mocho, a íbis, a gralha,

[[v5-14-17]]

^<<v5-14-17,17>>^ o pelicano, o abutre, o corvo marinho,

[[v5-14-18]]

^<<v5-14-18,18>>^ a cegonha, e a garça, segundo a sua espécie, e a poupa, e o morcego.

[[v5-14-19]]

^<<v5-14-19,19>>^ Também todo inseto que voa vos será imundo; não se comerá.

[[v5-14-20]]

^<<v5-14-20,20>>^ Toda ave limpa comereis.

[[v5-14-21]]

^<<v5-14-21,21>>^ Não comereis nenhum animal que morreu por si. Podereis dá-lo ao estrangeiro que está dentro da tua cidade, para que o coma, ou vendê-lo ao estranho, porquanto sois povo santo ao SENHOR, vosso Deus. Não cozerás o cabrito no leite da sua própria mãe.

[[v5-14-22]]

^<<v5-14-22,22>>^ Certamente, darás os dízimos de todo o fruto das tuas sementes, que ano após ano se recolher do campo.

[[v5-14-23]]

^<<v5-14-23,23>>^ E, perante o SENHOR, teu Deus, no lugar que escolher para ali fazer habitar o seu nome, comerás os dízimos do teu cereal, do teu vinho, do teu azeite e os primogênitos das tuas vacas e das tuas ovelhas; para que aprendas a temer o SENHOR, teu Deus, todos os dias.

[[v5-14-24]]

^<<v5-14-24,24>>^ Quando o caminho te for comprido demais, que os não possas levar, por estar longe de ti o lugar que o SENHOR, teu Deus, escolher para ali pôr o seu nome, quando o SENHOR, teu Deus, te tiver abençoado,

[[v5-14-25]]

^<<v5-14-25,25>>^ então, vende-os, e leva o dinheiro na tua mão, e vai ao lugar que o SENHOR, teu Deus, escolher.

[[v5-14-26]]

^<<v5-14-26,26>>^ Esse dinheiro, dá-lo-ás por tudo o que deseja a tua alma, por vacas, ou ovelhas, ou vinho, ou bebida forte, ou qualquer coisa que te pedir a tua alma; come-o ali perante o SENHOR, teu Deus, e te alegrarás, tu e a tua casa;

[[v5-14-27]]

^<<v5-14-27,27>>^ porém não desampararás o levita que está dentro da tua cidade, pois não tem parte nem herança contigo.

[[v5-14-28]]

^<<v5-14-28,28>>^ Ao fim de cada três anos, tirarás todos os dízimos do fruto do terceiro ano e os recolherás na tua cidade.

[[v5-14-29]]

^<<v5-14-29,29>>^ Então, virão o levita (pois não tem parte nem herança contigo), o estrangeiro, o órfão e a viúva que estão dentro da tua cidade, e comerão, e se fartarão, para que o SENHOR, teu Deus, te abençoe em todas as obras que as tuas mãos fizerem.

'''

xref:005-deuteronomio/005-deuteronomio-013.adoc#v5-13-0[&#60; Capítulo Anterior] | <<v5-14-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-015.adoc#v5-15-0[Próximo Capítulo &#62;]