include::./index.adoc[]

[[v5-22-0]]
=== Deuteronômio, 22
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-22-1]]

^<<v5-22-1,1>>^ Vendo extraviado o boi ou a ovelha de teu irmão, não te furtarás a eles; restituí-los-ás, sem falta, a teu irmão.

[[v5-22-2]]

^<<v5-22-2,2>>^ Se teu irmão não for teu vizinho ou tu o não conheceres, recolhê-los-ás na tua casa, para que fiquem contigo até que teu irmão os busque, e tu lhos restituas.

[[v5-22-3]]

^<<v5-22-3,3>>^ Assim também farás com o seu jumento e assim farás com as suas vestes; o mesmo farás com toda coisa que se perder de teu irmão, e tu achares; não te poderás furtar a ela.

[[v5-22-4]]

^<<v5-22-4,4>>^ O jumento que é de teu irmão ou o seu boi não verás caído no caminho e a eles te furtarás; sem falta o ajudarás a levantá-lo.

[[v5-22-5]]

^<<v5-22-5,5>>^ A mulher não usará roupa de homem, nem o homem, veste peculiar à mulher; porque qualquer que faz tais coisas é abominável ao SENHOR, teu Deus.

[[v5-22-6]]

^<<v5-22-6,6>>^ Se de caminho encontrares algum ninho de ave, nalguma árvore ou no chão, com passarinhos, ou ovos, e a mãe sobre os passarinhos ou sobre os ovos, não tomarás a mãe com os filhotes;

[[v5-22-7]]

^<<v5-22-7,7>>^ deixarás ir, livremente, a mãe e os filhotes tomarás para ti, para que te vá bem, e prolongues os teus dias.

[[v5-22-8]]

^<<v5-22-8,8>>^ Quando edificares uma casa nova, far-lhe-ás, no terraço, um parapeito, para que nela não ponhas culpa de sangue, se alguém de algum modo cair dela.

[[v5-22-9]]

^<<v5-22-9,9>>^ Não semearás a tua vinha com duas espécies de semente, para que não degenere o fruto da semente que semeaste e a messe da vinha.

[[v5-22-10]]

^<<v5-22-10,10>>^ Não lavrarás com junta de boi e jumento.

[[v5-22-11]]

^<<v5-22-11,11>>^ Não te vestirás de estofos de lã e linho juntamente.

[[v5-22-12]]

^<<v5-22-12,12>>^ Farás borlas nos quatro cantos do manto com que te cobrires.

[[v5-22-13]]

^<<v5-22-13,13>>^ Se um homem casar com uma mulher, e, depois de coabitar com ela, a aborrecer,

[[v5-22-14]]

^<<v5-22-14,14>>^ e lhe atribuir atos vergonhosos, e contra ela divulgar má fama, dizendo: Casei com esta mulher e me cheguei a ela, porém não a achei virgem,

[[v5-22-15]]

^<<v5-22-15,15>>^ então, o pai da moça e sua mãe tomarão as provas da virgindade da moça e as levarão aos anciãos da cidade, à porta.

[[v5-22-16]]

^<<v5-22-16,16>>^ O pai da moça dirá aos anciãos: Dei minha filha por mulher a este homem; porém ele a aborreceu;

[[v5-22-17]]

^<<v5-22-17,17>>^ e eis que lhe atribuiu atos vergonhosos, dizendo: Não achei virgem a tua filha; todavia, eis aqui as provas da virgindade de minha filha. E estenderão a roupa dela diante dos anciãos da cidade,

[[v5-22-18]]

^<<v5-22-18,18>>^ os quais tomarão o homem, e o açoitarão,

[[v5-22-19]]

^<<v5-22-19,19>>^ e o condenarão a cem siclos de prata, e o darão ao pai da moça, porquanto divulgou má fama sobre uma virgem de Israel. Ela ficará sendo sua mulher, e ele não poderá mandá-la embora durante a sua vida.

[[v5-22-20]]

^<<v5-22-20,20>>^ Porém, se isto for verdade, que se não achou na moça a virgindade,

[[v5-22-21]]

^<<v5-22-21,21>>^ então, a levarão à porta da casa de seu pai, e os homens de sua cidade a apedrejarão até que morra, pois fez loucura em Israel, prostituindo-se na casa de seu pai; assim, eliminarás o mal do meio de ti.

[[v5-22-22]]

^<<v5-22-22,22>>^ Se um homem for achado deitado com uma mulher que tem marido, então, ambos morrerão, o homem que se deitou com a mulher e a mulher; assim, eliminarás o mal de Israel.

[[v5-22-23]]

^<<v5-22-23,23>>^ Se houver moça virgem, desposada, e um homem a achar na cidade e se deitar com ela,

[[v5-22-24]]

^<<v5-22-24,24>>^ então, trareis ambos à porta daquela cidade e os apedrejareis até que morram; a moça, porque não gritou na cidade, e o homem, porque humilhou a mulher do seu próximo; assim, eliminarás o mal do meio de ti.

[[v5-22-25]]

^<<v5-22-25,25>>^ Porém, se algum homem no campo achar moça desposada, e a forçar, e se deitar com ela, então, morrerá só o homem que se deitou com ela;

[[v5-22-26]]

^<<v5-22-26,26>>^ à moça não farás nada; ela não tem culpa de morte, porque, como o homem que se levanta contra o seu próximo e lhe tira a vida, assim também é este caso.

[[v5-22-27]]

^<<v5-22-27,27>>^ Pois a achou no campo; a moça desposada gritou, e não houve quem a livrasse.

[[v5-22-28]]

^<<v5-22-28,28>>^ Se um homem achar moça virgem, que não está desposada, e a pegar, e se deitar com ela, e forem apanhados,

[[v5-22-29]]

^<<v5-22-29,29>>^ então, o homem que se deitou com ela dará ao pai da moça cinquenta siclos de prata; e, uma vez que a humilhou, lhe será por mulher; não poderá mandá-la embora durante a sua vida.

[[v5-22-30]]

^<<v5-22-30,30>>^ Nenhum homem tomará sua madrasta e não profanará o leito de seu pai.

'''

xref:005-deuteronomio/005-deuteronomio-021.adoc#v5-21-0[&#60; Capítulo Anterior] | <<v5-22-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-023.adoc#v5-23-0[Próximo Capítulo &#62;]