include::./index.adoc[]

[[v5-25-0]]
=== Deuteronômio, 25
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-25-1]]

^<<v5-25-1,1>>^ Em havendo contenda entre alguns, e vierem a juízo, os juízes os julgarão, justificando ao justo e condenando ao culpado.

[[v5-25-2]]

^<<v5-25-2,2>>^ Se o culpado merecer açoites, o juiz o fará deitar-se e o fará açoitar, na sua presença, com o número de açoites segundo a sua culpa.

[[v5-25-3]]

^<<v5-25-3,3>>^ Quarenta açoites lhe fará dar, não mais; para que, porventura, se lhe fizer dar mais do que estes, teu irmão não fique aviltado aos teus olhos.

[[v5-25-4]]

^<<v5-25-4,4>>^ Não atarás a boca ao boi quando debulha.

[[v5-25-5]]

^<<v5-25-5,5>>^ Se irmãos morarem juntos, e um deles morrer sem filhos, então, a mulher do que morreu não se casará com outro estranho, fora da família; seu cunhado a tomará, e a receberá por mulher, e exercerá para com ela a obrigação de cunhado.

[[v5-25-6]]

^<<v5-25-6,6>>^ O primogênito que ela lhe der será sucessor do nome do seu irmão falecido, para que o nome deste não se apague em Israel.

[[v5-25-7]]

^<<v5-25-7,7>>^ Porém, se o homem não quiser tomar sua cunhada, subirá esta à porta, aos anciãos, e dirá: Meu cunhado recusa suscitar a seu irmão nome em Israel; não quer exercer para comigo a obrigação de cunhado.

[[v5-25-8]]

^<<v5-25-8,8>>^ Então, os anciãos da sua cidade devem chamá-lo e falar-lhe; e, se ele persistir e disser: Não quero tomá-la,

[[v5-25-9]]

^<<v5-25-9,9>>^ então, sua cunhada se chegará a ele na presença dos anciãos, e lhe descalçará a sandália do pé, e lhe cuspirá no rosto, e protestará, e dirá: Assim se fará ao homem que não quer edificar a casa de seu irmão;

[[v5-25-10]]

^<<v5-25-10,10>>^ e o nome de sua casa se chamará em Israel: A casa do descalçado.

[[v5-25-11]]

^<<v5-25-11,11>>^ Quando brigarem dois homens, um contra o outro, e a mulher de um chegar para livrar o marido da mão do que o fere, e ela estender a mão, e o pegar pelas suas vergonhas,

[[v5-25-12]]

^<<v5-25-12,12>>^ cortar-lhe-ás a mão; não a olharás com piedade.

[[v5-25-13]]

^<<v5-25-13,13>>^ Na tua bolsa, não terás pesos diversos, um grande e um pequeno.

[[v5-25-14]]

^<<v5-25-14,14>>^ Na tua casa, não terás duas sortes de efa, um grande e um pequeno.

[[v5-25-15]]

^<<v5-25-15,15>>^ Terás peso integral e justo, efa integral e justo; para que se prolonguem os teus dias na terra que te dá o SENHOR, teu Deus.

[[v5-25-16]]

^<<v5-25-16,16>>^ Porque é abominação ao SENHOR, teu Deus, todo aquele que pratica tal injustiça.

[[v5-25-17]]

^<<v5-25-17,17>>^ Lembra-te do que te fez Amaleque no caminho, quando saías do Egito;

[[v5-25-18]]

^<<v5-25-18,18>>^ como te veio ao encontro no caminho e te atacou na retaguarda todos os desfalecidos que iam após ti, quando estavas abatido e afadigado; e não temeu a Deus.

[[v5-25-19]]

^<<v5-25-19,19>>^ Quando, pois, o SENHOR, teu Deus, te houver dado sossego de todos os teus inimigos em redor, na terra que o SENHOR, teu Deus, te dá por herança, para a possuíres, apagarás a memória de Amaleque de debaixo do céu; não te esqueças.

'''

xref:005-deuteronomio/005-deuteronomio-024.adoc#v5-24-0[&#60; Capítulo Anterior] | <<v5-25-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-026.adoc#v5-26-0[Próximo Capítulo &#62;]