include::./index.adoc[]

[[v5-3-0]]
=== Deuteronômio, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-3-1]]

^<<v5-3-1,1>>^ Depois, nos viramos e subimos o caminho de Basã; e Ogue, rei de Basã, nos saiu ao encontro, ele e todo o seu povo, à peleja em Edrei.

[[v5-3-2]]

^<<v5-3-2,2>>^ Então, o SENHOR me disse: Não temas, porque a ele, e todo o seu povo, e sua terra dei na tua mão; e far-lhe-ás como fizeste a Seom, rei dos amorreus, que habitava em Hesbom.

[[v5-3-3]]

^<<v5-3-3,3>>^ Deu-nos o SENHOR, nosso Deus, em nossas mãos também a Ogue, rei de Basã, e a todo o seu povo; e ferimo-lo, até que lhe não ficou nenhum sobrevivente.

[[v5-3-4]]

^<<v5-3-4,4>>^ Nesse tempo, tomamos todas as suas cidades; nenhuma cidade houve que lhe não tomássemos: sessenta cidades, toda a região de Argobe, o reino de Ogue, em Basã.

[[v5-3-5]]

^<<v5-3-5,5>>^ Todas estas cidades eram fortificadas com altos muros, portas e ferrolhos; tomamos também outras muitas cidades, que eram sem muros.

[[v5-3-6]]

^<<v5-3-6,6>>^ Destruímo-las totalmente, como fizemos a Seom, rei de Hesbom, fazendo perecer, por completo, cada uma das cidades com os seus homens, suas mulheres e crianças.

[[v5-3-7]]

^<<v5-3-7,7>>^ Porém todo o gado e o despojo das cidades tomamos para nós, por presa.

[[v5-3-8]]

^<<v5-3-8,8>>^ Assim, nesse tempo, tomamos a terra da mão daqueles dois reis dos amorreus que estavam dalém do Jordão: desde o rio de Arnom até ao monte Hermom

[[v5-3-9]]

^<<v5-3-9,9>>^ (Os sidônios a Hermom chamam Siriom; porém os amorreus lhe chamam Senir.),

[[v5-3-10]]

^<<v5-3-10,10>>^ tomamos todas as cidades do planalto, e todo o Gileade, e todo o Basã, até Salca e Edrei, cidades do reino de Ogue, em Basã

[[v5-3-11]]

^<<v5-3-11,11>>^ (Porque só Ogue, rei de Basã, restou dos refains; eis que o seu leito, leito de ferro, não está, porventura, em Rabá dos filhos de Amom, sendo de nove côvados o seu comprimento, e de quatro, a sua largura, pelo côvado comum?).

[[v5-3-12]]

^<<v5-3-12,12>>^ Tomamos, pois, esta terra em possessão nesse tempo; desde Aroer, que está junto ao vale de Arnom, e a metade da região montanhosa de Gileade, com as suas cidades, dei aos rubenitas e gaditas.

[[v5-3-13]]

^<<v5-3-13,13>>^ O resto de Gileade, como também todo o Basã, o reino de Ogue, dei à meia tribo de Manassés; toda aquela região de Argobe, todo o Basã, se chamava a terra dos refains.

[[v5-3-14]]

^<<v5-3-14,14>>^ Jair, filho de Manassés, tomou toda a região de Argobe até ao limite dos gesuritas e maacatitas, isto é, Basã, e às aldeias chamou pelo seu nome: Havote-Jair, até o dia de hoje.

[[v5-3-15]]

^<<v5-3-15,15>>^ A Maquir dei Gileade.

[[v5-3-16]]

^<<v5-3-16,16>>^ Mas aos rubenitas e gaditas dei desde Gileade até ao vale de Arnom, cujo meio serve de limite; e até ao ribeiro de Jaboque, o limite dos filhos de Amom,

[[v5-3-17]]

^<<v5-3-17,17>>^ como também a Arabá e o Jordão por limite, desde Quinerete até ao mar da Arabá, o mar Salgado, pelas faldas de Pisga, para o oriente.

[[v5-3-18]]

^<<v5-3-18,18>>^ Nesse mesmo tempo, vos ordenei, dizendo: o SENHOR, vosso Deus, vos deu esta terra, para a possuirdes; passai, pois, armados, todos os homens valentes, adiante de vossos irmãos, os filhos de Israel.

[[v5-3-19]]

^<<v5-3-19,19>>^ Tão somente vossas mulheres, e vossas crianças, e vosso gado (porque sei que tendes muito gado) ficarão nas vossas cidades que já vos tenho dado,

[[v5-3-20]]

^<<v5-3-20,20>>^ até que o SENHOR dê descanso a vossos irmãos como a vós outros, para que eles também ocupem a terra que o SENHOR, vosso Deus, lhes dá dalém do Jordão; então, voltareis cada qual à sua possessão que vos dei.

[[v5-3-21]]

^<<v5-3-21,21>>^ Também, nesse tempo, dei ordem a Josué, dizendo: os teus olhos veem tudo o que o SENHOR, vosso Deus, tem feito a estes dois reis; assim fará o SENHOR a todos os reinos a que tu passarás.

[[v5-3-22]]

^<<v5-3-22,22>>^ Não os temais, porque o SENHOR, vosso Deus, é o que peleja por vós.

[[v5-3-23]]

^<<v5-3-23,23>>^ Também eu, nesse tempo, implorei graça ao SENHOR, dizendo:

[[v5-3-24]]

^<<v5-3-24,24>>^ Ó SENHOR Deus! Passaste a mostrar ao teu servo a tua grandeza e a tua poderosa mão; porque que deus há, nos céus ou na terra, que possa fazer segundo as tuas obras, segundo os teus poderosos feitos?

[[v5-3-25]]

^<<v5-3-25,25>>^ Rogo-te que me deixes passar, para que eu veja esta boa terra que está dalém do Jordão, esta boa região montanhosa e o Líbano.

[[v5-3-26]]

^<<v5-3-26,26>>^ Porém o SENHOR indignou-se muito contra mim, por vossa causa, e não me ouviu; antes, me disse: Basta! Não me fales mais nisto.

[[v5-3-27]]

^<<v5-3-27,27>>^ Sobe ao cimo de Pisga, levanta os olhos para o ocidente, e para o norte, e para o sul, e para o oriente e contempla com os próprios olhos, porque não passarás este Jordão.

[[v5-3-28]]

^<<v5-3-28,28>>^ Dá ordens a Josué, e anima-o, e fortalece-o; porque ele passará adiante deste povo e o fará possuir a terra que tu apenas verás.

[[v5-3-29]]

^<<v5-3-29,29>>^ Assim, ficamos no vale defronte de Bete-Peor.

'''

xref:005-deuteronomio/005-deuteronomio-002.adoc#v5-2-0[&#60; Capítulo Anterior] | <<v5-3-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-004.adoc#v5-4-0[Próximo Capítulo &#62;]