include::./index.adoc[]

[[v5-13-0]]
=== Deuteronômio, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-13-1]]

^<<v5-13-1,1>>^ Quando profeta ou sonhador se levantar no meio de ti e te anunciar um sinal ou prodígio,

[[v5-13-2]]

^<<v5-13-2,2>>^ e suceder o tal sinal ou prodígio de que te houver falado, e disser: Vamos após outros deuses, que não conheceste, e sirvamo-los,

[[v5-13-3]]

^<<v5-13-3,3>>^ não ouvirás as palavras desse profeta ou sonhador; porquanto o SENHOR, vosso Deus, vos prova, para saber se amais o SENHOR, vosso Deus, de todo o vosso coração e de toda a vossa alma.

[[v5-13-4]]

^<<v5-13-4,4>>^ Andareis após o SENHOR, vosso Deus, e a ele temereis; guardareis os seus mandamentos, ouvireis a sua voz, a ele servireis e a ele vos achegareis.

[[v5-13-5]]

^<<v5-13-5,5>>^ Esse profeta ou sonhador será morto, pois pregou rebeldia contra o SENHOR, vosso Deus, que vos tirou da terra do Egito e vos resgatou da casa da servidão, para vos apartar do caminho que vos ordenou o SENHOR, vosso Deus, para andardes nele. Assim, eliminarás o mal do meio de ti.

[[v5-13-6]]

^<<v5-13-6,6>>^ Se teu irmão, filho de tua mãe, ou teu filho, ou tua filha, ou a mulher do teu amor, ou teu amigo que amas como à tua alma te incitar em segredo, dizendo: Vamos e sirvamos a outros deuses, que não conheceste, nem tu, nem teus pais,

[[v5-13-7]]

^<<v5-13-7,7>>^ dentre os deuses dos povos que estão em redor de ti, perto ou longe de ti, desde uma até à outra extremidade da terra,

[[v5-13-8]]

^<<v5-13-8,8>>^ não concordarás com ele, nem o ouvirás; não olharás com piedade, não o pouparás, nem o esconderás,

[[v5-13-9]]

^<<v5-13-9,9>>^ mas, certamente, o matarás. A tua mão será a primeira contra ele, para o matar, e depois a mão de todo o povo.

[[v5-13-10]]

^<<v5-13-10,10>>^ Apedrejá-lo-ás até que morra, pois te procurou apartar do SENHOR, teu Deus, que te tirou da terra do Egito, da casa da servidão.

[[v5-13-11]]

^<<v5-13-11,11>>^ E todo o Israel ouvirá e temerá, e não se tornará a praticar maldade como esta no meio de ti.

[[v5-13-12]]

^<<v5-13-12,12>>^ Quando em alguma das tuas cidades que o SENHOR, teu Deus, te dá, para ali habitares, ouvires dizer

[[v5-13-13]]

^<<v5-13-13,13>>^ que homens malignos saíram do meio de ti e incitaram os moradores da sua cidade, dizendo: Vamos e sirvamos a outros deuses, que não conheceste,

[[v5-13-14]]

^<<v5-13-14,14>>^ então, inquirirás, investigarás e, com diligência, perguntarás; e eis que, se for verdade e certo que tal abominação se cometeu no meio de ti,

[[v5-13-15]]

^<<v5-13-15,15>>^ então, certamente, ferirás a fio de espada os moradores daquela cidade, destruindo-a completamente e tudo o que nela houver, até os animais.

[[v5-13-16]]

^<<v5-13-16,16>>^ Ajuntarás todo o seu despojo no meio da sua praça e a cidade e todo o seu despojo queimarás por oferta total ao SENHOR, teu Deus, e será montão perpétuo de ruínas; nunca mais se edificará.

[[v5-13-17]]

^<<v5-13-17,17>>^ Também nada do que for condenado deverá ficar em tua mão, para que o SENHOR se aparte do ardor da sua ira, e te faça misericórdia, e tenha piedade de ti, e te multiplique, como jurou a teus pais,

[[v5-13-18]]

^<<v5-13-18,18>>^ se ouvires a voz do SENHOR, teu Deus, e guardares todos os seus mandamentos que hoje te ordeno, para fazeres o que é reto aos olhos do SENHOR, teu Deus.

'''

xref:005-deuteronomio/005-deuteronomio-012.adoc#v5-12-0[&#60; Capítulo Anterior] | <<v5-13-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-014.adoc#v5-14-0[Próximo Capítulo &#62;]