include::./index.adoc[]

[[v5-30-0]]
=== Deuteronômio, 30
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-30-1]]

^<<v5-30-1,1>>^ Quando, pois, todas estas coisas vierem sobre ti, a bênção e a maldição que pus diante de ti, se te recordares delas entre todas as nações para onde te lançar o SENHOR, teu Deus;

[[v5-30-2]]

^<<v5-30-2,2>>^ e tornares ao SENHOR, teu Deus, tu e teus filhos, de todo o teu coração e de toda a tua alma, e deres ouvidos à sua voz, segundo tudo o que hoje te ordeno,

[[v5-30-3]]

^<<v5-30-3,3>>^ então, o SENHOR, teu Deus, mudará a tua sorte, e se compadecerá de ti, e te ajuntará, de novo, de todos os povos entre os quais te havia espalhado o SENHOR, teu Deus.

[[v5-30-4]]

^<<v5-30-4,4>>^ Ainda que os teus desterrados estejam para a extremidade dos céus, desde aí te ajuntará o SENHOR, teu Deus, e te tomará de lá.

[[v5-30-5]]

^<<v5-30-5,5>>^ O SENHOR, teu Deus, te introduzirá na terra que teus pais possuíram, e a possuirás; e te fará bem e te multiplicará mais do que a teus pais.

[[v5-30-6]]

^<<v5-30-6,6>>^ O SENHOR, teu Deus, circuncidará o teu coração e o coração de tua descendência, para amares o SENHOR, teu Deus, de todo o coração e de toda a tua alma, para que vivas.

[[v5-30-7]]

^<<v5-30-7,7>>^ O SENHOR, teu Deus, porá todas estas maldições sobre os teus inimigos e sobre os teus aborrecedores, que te perseguiram.

[[v5-30-8]]

^<<v5-30-8,8>>^ De novo, pois, darás ouvidos à voz do SENHOR; cumprirás todos os seus mandamentos que hoje te ordeno.

[[v5-30-9]]

^<<v5-30-9,9>>^ O SENHOR, teu Deus, te dará abundância em toda obra das tuas mãos, no fruto do teu ventre, no fruto dos teus animais e no fruto da tua terra e te beneficiará; porquanto o SENHOR tornará a exultar em ti, para te fazer bem, como exultou em teus pais;

[[v5-30-10]]

^<<v5-30-10,10>>^ se deres ouvidos à voz do SENHOR, teu Deus, guardando os seus mandamentos e os seus estatutos, escritos neste Livro da Lei, se te converteres ao SENHOR, teu Deus, de todo o teu coração e de toda a tua alma.

[[v5-30-11]]

^<<v5-30-11,11>>^ Porque este mandamento que, hoje, te ordeno não é demasiado difícil, nem está longe de ti.

[[v5-30-12]]

^<<v5-30-12,12>>^ Não está nos céus, para dizeres: Quem subirá por nós aos céus, que no-lo traga e no-lo faça ouvir, para que o cumpramos?

[[v5-30-13]]

^<<v5-30-13,13>>^ Nem está além do mar, para dizeres: Quem passará por nós além do mar que no-lo traga e no-lo faça ouvir, para que o cumpramos?

[[v5-30-14]]

^<<v5-30-14,14>>^ Pois esta palavra está mui perto de ti, na tua boca e no teu coração, para a cumprires.

[[v5-30-15]]

^<<v5-30-15,15>>^ Vê que proponho, hoje, a vida e o bem, a morte e o mal;

[[v5-30-16]]

^<<v5-30-16,16>>^ se guardares o mandamento que hoje te ordeno, que ames o SENHOR, teu Deus, andes nos seus caminhos, e guardes os seus mandamentos, e os seus estatutos, e os seus juízos, então, viverás e te multiplicarás, e o SENHOR, teu Deus, te abençoará na terra à qual passas para possuí-la.

[[v5-30-17]]

^<<v5-30-17,17>>^ Porém, se o teu coração se desviar, e não quiseres dar ouvidos, e fores seduzido, e te inclinares a outros deuses, e os servires,

[[v5-30-18]]

^<<v5-30-18,18>>^ então, hoje, te declaro que, certamente, perecerás; não permanecerás longo tempo na terra à qual vais, passando o Jordão, para a possuíres.

[[v5-30-19]]

^<<v5-30-19,19>>^ Os céus e a terra tomo, hoje, por testemunhas contra ti, que te propus a vida e a morte, a bênção e a maldição; escolhe, pois, a vida, para que vivas, tu e a tua descendência,

[[v5-30-20]]

^<<v5-30-20,20>>^ amando o SENHOR, teu Deus, dando ouvidos à sua voz e apegando-te a ele; pois disto depende a tua vida e a tua longevidade; para que habites na terra que o SENHOR, sob juramento, prometeu dar a teus pais, Abraão, Isaque e Jacó.

'''

xref:005-deuteronomio/005-deuteronomio-029.adoc#v5-29-0[&#60; Capítulo Anterior] | <<v5-30-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-031.adoc#v5-31-0[Próximo Capítulo &#62;]