include::./index.adoc[]

[[v5-11-0]]
=== Deuteronômio, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-11-1]]

^<<v5-11-1,1>>^ Amarás, pois, o SENHOR, teu Deus, e todos os dias guardarás os seus preceitos, os seus estatutos, os seus juízos e os seus mandamentos.

[[v5-11-2]]

^<<v5-11-2,2>>^ Considerai hoje (não falo com os vossos filhos que não conheceram, nem viram a disciplina do SENHOR, vosso Deus), considerai a grandeza do SENHOR, a sua poderosa mão e o seu braço estendido;

[[v5-11-3]]

^<<v5-11-3,3>>^ e também os seus sinais, as suas obras, que fez no meio do Egito a Faraó, rei do Egito, e a toda a sua terra;

[[v5-11-4]]

^<<v5-11-4,4>>^ e o que fez ao exército do Egito, aos seus cavalos e aos seus carros, fazendo passar sobre eles as águas do mar Vermelho, quando vos perseguiam, e como o SENHOR os destruiu até ao dia de hoje;

[[v5-11-5]]

^<<v5-11-5,5>>^ e o que fez no deserto, até que chegastes a este lugar;

[[v5-11-6]]

^<<v5-11-6,6>>^ e ainda o que fez a Datã e a Abirão, filhos de Eliabe, filho de Rúben; como a terra abriu a boca e os tragou e bem assim a sua família, suas tendas e tudo o que os seguia, no meio de todo o Israel;

[[v5-11-7]]

^<<v5-11-7,7>>^ porquanto os vossos olhos são os que viram todas as grandes obras que fez o SENHOR.

[[v5-11-8]]

^<<v5-11-8,8>>^ Guardai, pois, todos os mandamentos que hoje vos ordeno, para que sejais fortes, e entreis, e possuais a terra para onde vos dirigis;

[[v5-11-9]]

^<<v5-11-9,9>>^ para que prolongueis os dias na terra que o SENHOR, sob juramento, prometeu dar a vossos pais e à sua descendência, terra que mana leite e mel.

[[v5-11-10]]

^<<v5-11-10,10>>^ Porque a terra que passais a possuir não é como a terra do Egito, donde saístes, em que semeáveis a vossa semente e, com o pé, a regáveis como a uma horta;

[[v5-11-11]]

^<<v5-11-11,11>>^ mas a terra que passais a possuir é terra de montes e de vales; da chuva dos céus beberá as águas;

[[v5-11-12]]

^<<v5-11-12,12>>^ terra de que cuida o SENHOR, vosso Deus; os olhos do SENHOR, vosso Deus, estão sobre ela continuamente, desde o princípio até ao fim do ano.

[[v5-11-13]]

^<<v5-11-13,13>>^ Se diligentemente obedecerdes a meus mandamentos que hoje vos ordeno, de amar o SENHOR, vosso Deus, e de o servir de todo o vosso coração e de toda a vossa alma,

[[v5-11-14]]

^<<v5-11-14,14>>^ darei as chuvas da vossa terra a seu tempo, as primeiras e as últimas, para que recolhais o vosso cereal, e o vosso vinho, e o vosso azeite.

[[v5-11-15]]

^<<v5-11-15,15>>^ Darei erva no vosso campo aos vossos gados, e comereis e vos fartareis.

[[v5-11-16]]

^<<v5-11-16,16>>^ Guardai-vos não suceda que o vosso coração se engane, e vos desvieis, e sirvais a outros deuses, e vos prostreis perante eles;

[[v5-11-17]]

^<<v5-11-17,17>>^ que a ira do SENHOR se acenda contra vós outros, e feche ele os céus, e não haja chuva, e a terra não dê a sua messe, e cedo sejais eliminados da boa terra que o SENHOR vos dá.

[[v5-11-18]]

^<<v5-11-18,18>>^ Ponde, pois, estas minhas palavras no vosso coração e na vossa alma; atai-as por sinal na vossa mão, para que estejam por frontal entre os olhos.

[[v5-11-19]]

^<<v5-11-19,19>>^ Ensinai-as a vossos filhos, falando delas assentados em vossa casa, e andando pelo caminho, e deitando-vos, e levantando-vos.

[[v5-11-20]]

^<<v5-11-20,20>>^ Escrevei-as nos umbrais de vossa casa e nas vossas portas,

[[v5-11-21]]

^<<v5-11-21,21>>^ para que se multipliquem os vossos dias e os dias de vossos filhos na terra que o SENHOR, sob juramento, prometeu dar a vossos pais, e sejam tão numerosos como os dias do céu acima da terra.

[[v5-11-22]]

^<<v5-11-22,22>>^ Porque, se diligentemente guardardes todos estes mandamentos que vos ordeno para os guardardes, amando o SENHOR, vosso Deus, andando em todos os seus caminhos, e a ele vos achegardes,

[[v5-11-23]]

^<<v5-11-23,23>>^ o SENHOR desapossará todas estas nações, e possuireis nações maiores e mais poderosas do que vós.

[[v5-11-24]]

^<<v5-11-24,24>>^ Todo lugar que pisar a planta do vosso pé, desde o deserto, desde o Líbano, desde o rio, o rio Eufrates, até ao mar ocidental, será vosso.

[[v5-11-25]]

^<<v5-11-25,25>>^ Ninguém vos poderá resistir; o SENHOR, vosso Deus, porá sobre toda terra que pisardes o vosso terror e o vosso temor, como já vos tem dito.

[[v5-11-26]]

^<<v5-11-26,26>>^ Eis que, hoje, eu ponho diante de vós a bênção e a maldição:

[[v5-11-27]]

^<<v5-11-27,27>>^ a bênção, quando cumprirdes os mandamentos do SENHOR, vosso Deus, que hoje vos ordeno;

[[v5-11-28]]

^<<v5-11-28,28>>^ a maldição, se não cumprirdes os mandamentos do SENHOR, vosso Deus, mas vos desviardes do caminho que hoje vos ordeno, para seguirdes outros deuses que não conhecestes.

[[v5-11-29]]

^<<v5-11-29,29>>^ Quando, porém, o SENHOR, teu Deus, te introduzir na terra a que vais para possuí-la, então, pronunciarás a bênção sobre o monte Gerizim e a maldição sobre o monte Ebal.

[[v5-11-30]]

^<<v5-11-30,30>>^ Porventura, não estão eles além do Jordão, na direção do pôr do sol, na terra dos cananeus, que habitam na Arabá, defronte de Gilgal, junto aos carvalhais de Moré?

[[v5-11-31]]

^<<v5-11-31,31>>^ Pois ides passar o Jordão para entrardes e possuirdes a terra que vos dá o SENHOR, vosso Deus; possuí-la-eis e nela habitareis.

[[v5-11-32]]

^<<v5-11-32,32>>^ Tende, pois, cuidado em cumprir todos os estatutos e os juízos que eu, hoje, vos prescrevo.

'''

xref:005-deuteronomio/005-deuteronomio-010.adoc#v5-10-0[&#60; Capítulo Anterior] | <<v5-11-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-012.adoc#v5-12-0[Próximo Capítulo &#62;]