include::./index.adoc[]

[[v5-26-0]]
=== Deuteronômio, 26
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-26-1]]

^<<v5-26-1,1>>^ Ao entrares na terra que o SENHOR, teu Deus, te dá por herança, ao possuí-la e nela habitares,

[[v5-26-2]]

^<<v5-26-2,2>>^ tomarás das primícias de todos os frutos do solo que recolheres da terra que te dá o SENHOR, teu Deus, e as porás num cesto, e irás ao lugar que o SENHOR, teu Deus, escolher para ali fazer habitar o seu nome.

[[v5-26-3]]

^<<v5-26-3,3>>^ Virás ao que, naqueles dias, for sacerdote e lhe dirás: Hoje, declaro ao SENHOR, teu Deus, que entrei na terra que o SENHOR, sob juramento, prometeu dar a nossos pais.

[[v5-26-4]]

^<<v5-26-4,4>>^ O sacerdote tomará o cesto da tua mão e o porá diante do altar do SENHOR, teu Deus.

[[v5-26-5]]

^<<v5-26-5,5>>^ Então, testificarás perante o SENHOR, teu Deus, e dirás: Arameu prestes a perecer foi meu pai, e desceu para o Egito, e ali viveu como estrangeiro com pouca gente; e ali veio a ser nação grande, forte e numerosa.

[[v5-26-6]]

^<<v5-26-6,6>>^ Mas os egípcios nos maltrataram, e afligiram, e nos impuseram dura servidão.

[[v5-26-7]]

^<<v5-26-7,7>>^ Clamamos ao SENHOR, Deus de nossos pais; e o SENHOR ouviu a nossa voz e atentou para a nossa angústia, para o nosso trabalho e para a nossa opressão;

[[v5-26-8]]

^<<v5-26-8,8>>^ e o SENHOR nos tirou do Egito com poderosa mão, e com braço estendido, e com grande espanto, e com sinais, e com milagres;

[[v5-26-9]]

^<<v5-26-9,9>>^ e nos trouxe a este lugar e nos deu esta terra, terra que mana leite e mel.

[[v5-26-10]]

^<<v5-26-10,10>>^ Eis que, agora, trago as primícias dos frutos da terra que tu, ó SENHOR, me deste. Então, as porás perante o SENHOR, teu Deus, e te prostrarás perante ele.

[[v5-26-11]]

^<<v5-26-11,11>>^ Alegrar-te-ás por todo o bem que o SENHOR, teu Deus, te tem dado a ti e a tua casa, tu, e o levita, e o estrangeiro que está no meio de ti.

[[v5-26-12]]

^<<v5-26-12,12>>^ Quando acabares de separar todos os dízimos da tua messe no ano terceiro, que é o dos dízimos, então, os darás ao levita, ao estrangeiro, ao órfão e à viúva, para que comam dentro das tuas cidades e se fartem.

[[v5-26-13]]

^<<v5-26-13,13>>^ Dirás perante o SENHOR, teu Deus: Tirei de minha casa o que é consagrado e dei também ao levita, e ao estrangeiro, e ao órfão, e à viúva, segundo todos os teus mandamentos que me tens ordenado; nada transgredi dos teus mandamentos, nem deles me esqueci.

[[v5-26-14]]

^<<v5-26-14,14>>^ Dos dízimos não comi no meu luto e deles nada tirei estando imundo, nem deles dei para a casa de algum morto; obedeci à voz do SENHOR, meu Deus; segundo tudo o que me ordenaste, tenho feito.

[[v5-26-15]]

^<<v5-26-15,15>>^ Olha desde a tua santa habitação, desde o céu, e abençoa o teu povo, a Israel, e a terra que nos deste, como juraste a nossos pais, terra que mana leite e mel.

[[v5-26-16]]

^<<v5-26-16,16>>^ Hoje, o SENHOR, teu Deus, te manda cumprir estes estatutos e juízos; guarda-os, pois, e cumpre-os de todo o teu coração e de toda a tua alma.

[[v5-26-17]]

^<<v5-26-17,17>>^ Hoje, fizeste o SENHOR declarar que te será por Deus, e que andarás nos seus caminhos, e guardarás os seus estatutos, e os seus mandamentos, e os seus juízos, e darás ouvidos à sua voz.

[[v5-26-18]]

^<<v5-26-18,18>>^ E o SENHOR, hoje, te fez dizer que lhe serás por povo seu próprio, como te disse, e que guardarás todos os seus mandamentos.

[[v5-26-19]]

^<<v5-26-19,19>>^ Para, assim, te exaltar em louvor, renome e glória sobre todas as nações que fez e para que sejas povo santo ao SENHOR, teu Deus, como tem dito.

'''

xref:005-deuteronomio/005-deuteronomio-025.adoc#v5-25-0[&#60; Capítulo Anterior] | <<v5-26-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-027.adoc#v5-27-0[Próximo Capítulo &#62;]