include::./index.adoc[]

[[v5-4-0]]
=== Deuteronômio, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-4-1]]

^<<v5-4-1,1>>^ Agora, pois, ó Israel, ouve os estatutos e os juízos que eu vos ensino, para os cumprirdes, para que vivais, e entreis, e possuais a terra que o SENHOR, Deus de vossos pais, vos dá.

[[v5-4-2]]

^<<v5-4-2,2>>^ Nada acrescentareis à palavra que vos mando, nem diminuireis dela, para que guardeis os mandamentos do SENHOR, vosso Deus, que eu vos mando.

[[v5-4-3]]

^<<v5-4-3,3>>^ Os vossos olhos viram o que o SENHOR fez por causa de Baal-Peor; pois a todo homem que seguiu a Baal-Peor o SENHOR, vosso Deus, consumiu do vosso meio.

[[v5-4-4]]

^<<v5-4-4,4>>^ Porém vós que permanecestes fiéis ao SENHOR, vosso Deus, todos, hoje, estais vivos.

[[v5-4-5]]

^<<v5-4-5,5>>^ Eis que vos tenho ensinado estatutos e juízos, como me mandou o SENHOR, meu Deus, para que assim façais no meio da terra que passais a possuir.

[[v5-4-6]]

^<<v5-4-6,6>>^ Guardai-os, pois, e cumpri-os, porque isto será a vossa sabedoria e o vosso entendimento perante os olhos dos povos que, ouvindo todos estes estatutos, dirão: Certamente, este grande povo é gente sábia e inteligente.

[[v5-4-7]]

^<<v5-4-7,7>>^ Pois que grande nação há que tenha deuses tão chegados a si como o SENHOR, nosso Deus, todas as vezes que o invocamos?

[[v5-4-8]]

^<<v5-4-8,8>>^ E que grande nação há que tenha estatutos e juízos tão justos como toda esta lei que eu hoje vos proponho?

[[v5-4-9]]

^<<v5-4-9,9>>^ Tão somente guarda-te a ti mesmo e guarda bem a tua alma, que te não esqueças daquelas coisas que os teus olhos têm visto, e se não apartem do teu coração todos os dias da tua vida, e as farás saber a teus filhos e aos filhos de teus filhos.

[[v5-4-10]]

^<<v5-4-10,10>>^ Não te esqueças do dia em que estiveste perante o SENHOR, teu Deus, em Horebe, quando o SENHOR me disse: Reúne este povo, e os farei ouvir as minhas palavras, a fim de que aprenda a temer-me todos os dias que na terra viver e as ensinará a seus filhos.

[[v5-4-11]]

^<<v5-4-11,11>>^ Então, chegastes e vos pusestes ao pé do monte; e o monte ardia em fogo até ao meio dos céus, e havia trevas, e nuvens, e escuridão.

[[v5-4-12]]

^<<v5-4-12,12>>^ Então, o SENHOR vos falou do meio do fogo; a voz das palavras ouvistes; porém, além da voz, não vistes aparência nenhuma.

[[v5-4-13]]

^<<v5-4-13,13>>^ Então, vos anunciou ele a sua aliança, que vos prescreveu, os dez mandamentos, e os escreveu em duas tábuas de pedra.

[[v5-4-14]]

^<<v5-4-14,14>>^ Também o SENHOR me ordenou, ao mesmo tempo, que vos ensinasse estatutos e juízos, para que os cumprísseis na terra a qual passais a possuir.

[[v5-4-15]]

^<<v5-4-15,15>>^ Guardai, pois, cuidadosamente, a vossa alma, pois aparência nenhuma vistes no dia em que o SENHOR, vosso Deus, vos falou em Horebe, no meio do fogo;

[[v5-4-16]]

^<<v5-4-16,16>>^ para que não vos corrompais e vos façais alguma imagem esculpida na forma de ídolo, semelhança de homem ou de mulher,

[[v5-4-17]]

^<<v5-4-17,17>>^ semelhança de algum animal que há na terra, semelhança de algum volátil que voa pelos céus,

[[v5-4-18]]

^<<v5-4-18,18>>^ semelhança de algum animal que rasteja sobre a terra, semelhança de algum peixe que há nas águas debaixo da terra.

[[v5-4-19]]

^<<v5-4-19,19>>^ Guarda-te não levantes os olhos para os céus e, vendo o sol, a lua e as estrelas, a saber, todo o exército dos céus, sejas seduzido a inclinar-te perante eles e dês culto àqueles, coisas que o SENHOR, teu Deus, repartiu a todos os povos debaixo de todos os céus.

[[v5-4-20]]

^<<v5-4-20,20>>^ Mas o SENHOR vos tomou e vos tirou da fornalha de ferro do Egito, para que lhe sejais povo de herança, como hoje se vê.

[[v5-4-21]]

^<<v5-4-21,21>>^ Também o SENHOR se indignou contra mim, por vossa causa, e jurou que eu não passaria o Jordão e não entraria na boa terra que o SENHOR, teu Deus, te dá por herança.

[[v5-4-22]]

^<<v5-4-22,22>>^ Porque eu morrerei neste lugar, não passarei o Jordão; porém vós o passareis e possuireis aquela boa terra.

[[v5-4-23]]

^<<v5-4-23,23>>^ Guardai-vos não vos esqueçais da aliança do SENHOR, vosso Deus, feita convosco, e vos façais alguma imagem esculpida, semelhança de alguma coisa que o SENHOR, vosso Deus, vos proibiu.

[[v5-4-24]]

^<<v5-4-24,24>>^ Porque o SENHOR, teu Deus, é fogo que consome, é Deus zeloso.

[[v5-4-25]]

^<<v5-4-25,25>>^ Quando, pois, gerardes filhos e filhos de filhos, e vos envelhecerdes na terra, e vos corromperdes, e fizerdes alguma imagem esculpida, semelhança de alguma coisa, e fizerdes mal aos olhos do SENHOR, teu Deus, para o provocar à ira,

[[v5-4-26]]

^<<v5-4-26,26>>^ hoje, tomo por testemunhas contra vós outros o céu e a terra, que, com efeito, perecereis, imediatamente, da terra a qual, passado o Jordão, ides possuir; não prolongareis os vossos dias nela; antes, sereis de todo destruídos.

[[v5-4-27]]

^<<v5-4-27,27>>^ O SENHOR vos espalhará entre os povos, e restareis poucos em número entre as gentes aonde o SENHOR vos conduzirá.

[[v5-4-28]]

^<<v5-4-28,28>>^ Lá, servireis a deuses que são obra de mãos de homens, madeira e pedra, que não veem, nem ouvem, nem comem, nem cheiram.

[[v5-4-29]]

^<<v5-4-29,29>>^ De lá, buscarás ao SENHOR, teu Deus, e o acharás, quando o buscares de todo o teu coração e de toda a tua alma.

[[v5-4-30]]

^<<v5-4-30,30>>^ Quando estiveres em angústia, e todas estas coisas te sobrevierem nos últimos dias, e te voltares para o SENHOR, teu Deus, e lhe atenderes a voz,

[[v5-4-31]]

^<<v5-4-31,31>>^ então, o SENHOR, teu Deus, não te desamparará, porquanto é Deus misericordioso, nem te destruirá, nem se esquecerá da aliança que jurou a teus pais.

[[v5-4-32]]

^<<v5-4-32,32>>^ Agora, pois, pergunta aos tempos passados, que te precederam, desde o dia em que Deus criou o homem sobre a terra, desde uma extremidade do céu até à outra, se sucedeu jamais coisa tamanha como esta ou se se ouviu coisa como esta;

[[v5-4-33]]

^<<v5-4-33,33>>^ ou se algum povo ouviu falar a voz de algum deus do meio do fogo, como tu a ouviste, ficando vivo;

[[v5-4-34]]

^<<v5-4-34,34>>^ ou se um deus intentou ir tomar para si um povo do meio de outro povo, com provas, e com sinais, e com milagres, e com peleja, e com mão poderosa, e com braço estendido, e com grandes espantos, segundo tudo quanto o SENHOR, vosso Deus, vos fez no Egito, aos vossos olhos.

[[v5-4-35]]

^<<v5-4-35,35>>^ A ti te foi mostrado para que soubesses que o SENHOR é Deus; nenhum outro há, senão ele.

[[v5-4-36]]

^<<v5-4-36,36>>^ Dos céus te fez ouvir a sua voz, para te ensinar, e sobre a terra te mostrou o seu grande fogo, e do meio do fogo ouviste as suas palavras.

[[v5-4-37]]

^<<v5-4-37,37>>^ Porquanto amou teus pais, e escolheu a sua descendência depois deles, e te tirou do Egito, ele mesmo presente e com a sua grande força,

[[v5-4-38]]

^<<v5-4-38,38>>^ para lançar de diante de ti nações maiores e mais poderosas do que tu, para te introduzir na sua terra e ta dar por herança, como hoje se vê.

[[v5-4-39]]

^<<v5-4-39,39>>^ Por isso, hoje, saberás e refletirás no teu coração que só o SENHOR é Deus em cima no céu e embaixo na terra; nenhum outro há.

[[v5-4-40]]

^<<v5-4-40,40>>^ Guarda, pois, os seus estatutos e os seus mandamentos que te ordeno hoje, para que te vá bem a ti e a teus filhos depois de ti e para que prolongues os dias na terra que o SENHOR, teu Deus, te dá para todo o sempre.

[[v5-4-41]]

^<<v5-4-41,41>>^ Então, Moisés separou três cidades dalém do Jordão, do lado do nascimento do sol,

[[v5-4-42]]

^<<v5-4-42,42>>^ para que se acolhesse ali o homicida que matasse, involuntariamente, o seu próximo, a quem, dantes, não tivesse ódio algum, e se acolhesse a uma destas cidades e vivesse:

[[v5-4-43]]

^<<v5-4-43,43>>^ Bezer, no deserto, no planalto, para os rubenitas; Ramote, em Gileade, para os gaditas; e Golã, em Basã, para os manassitas.

[[v5-4-44]]

^<<v5-4-44,44>>^ Esta é a lei que Moisés propôs aos filhos de Israel.

[[v5-4-45]]

^<<v5-4-45,45>>^ São estes os testemunhos, e os estatutos, e os juízos que Moisés falou aos filhos de Israel, quando saíram do Egito,

[[v5-4-46]]

^<<v5-4-46,46>>^ além do Jordão, no vale defronte de Bete-Peor, na terra de Seom, rei dos amorreus, que habitava em Hesbom, a quem Moisés e os filhos de Israel feriram ao saírem do Egito,

[[v5-4-47]]

^<<v5-4-47,47>>^ e tomaram a sua terra em possessão, como também a terra de Ogue, rei de Basã, dois reis dos amorreus, que estavam além do Jordão, do lado do nascimento do sol;

[[v5-4-48]]

^<<v5-4-48,48>>^ desde Aroer, que está à borda do vale de Arnom, até ao monte Siom, que é Hermom,

[[v5-4-49]]

^<<v5-4-49,49>>^ e toda a Arabá, além do Jordão, do lado oriental, até ao mar da Arabá, pelas faldas de Pisga.

'''

xref:005-deuteronomio/005-deuteronomio-003.adoc#v5-3-0[&#60; Capítulo Anterior] | <<v5-4-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-005.adoc#v5-5-0[Próximo Capítulo &#62;]