include::./index.adoc[]

[[v5-19-0]]
=== Deuteronômio, 19
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-19-1]]

^<<v5-19-1,1>>^ Quando o SENHOR, teu Deus, eliminar as nações cuja terra te dará o SENHOR, teu Deus, e as desapossares e morares nas suas cidades e nas suas casas,

[[v5-19-2]]

^<<v5-19-2,2>>^ três cidades separarás no meio da tua terra que te dará o SENHOR, teu Deus, para a possuíres.

[[v5-19-3]]

^<<v5-19-3,3>>^ Preparar-te-ás o caminho e os limites da tua terra que te fará possuir o SENHOR, teu Deus, dividirás em três; e isto será para que nelas se acolha todo homicida.

[[v5-19-4]]

^<<v5-19-4,4>>^ Este é o caso tocante ao homicida que nelas se acolher, para que viva: aquele que, sem o querer, ferir o seu próximo, a quem não aborrecia dantes.

[[v5-19-5]]

^<<v5-19-5,5>>^ Assim, aquele que entrar com o seu próximo no bosque, para cortar lenha, e, manejando com impulso o machado para cortar a árvore, o ferro saltar do cabo e atingir o seu próximo, e este morrer, o tal se acolherá em uma destas cidades e viverá;

[[v5-19-6]]

^<<v5-19-6,6>>^ para que o vingador do sangue não persiga o homicida, quando se lhe enfurecer o coração, e o alcance, por ser comprido o caminho, e lhe tire a vida, porque não é culpado de morte, pois não o aborrecia dantes.

[[v5-19-7]]

^<<v5-19-7,7>>^ Portanto, te ordeno: três cidades separarás.

[[v5-19-8]]

^<<v5-19-8,8>>^ Se o SENHOR, teu Deus, dilatar os teus limites, como jurou a teus pais, e te der toda a terra que lhes prometeu,

[[v5-19-9]]

^<<v5-19-9,9>>^ desde que guardes todos estes mandamentos que hoje te ordeno, para cumpri-los, amando o SENHOR, teu Deus, e andando nos seus caminhos todos os dias, então, acrescentarás outras três cidades além destas três,

[[v5-19-10]]

^<<v5-19-10,10>>^ para que o sangue inocente se não derrame no meio da tua terra que o SENHOR, teu Deus, te dá por herança, pois haveria sangue sobre ti.

[[v5-19-11]]

^<<v5-19-11,11>>^ Mas, havendo alguém que aborrece a seu próximo, e lhe arma ciladas, e se levanta contra ele, e o fere de golpe mortal, e se acolhe em uma dessas cidades,

[[v5-19-12]]

^<<v5-19-12,12>>^ os anciãos da sua cidade enviarão a tirá-lo dali e a entregá-lo na mão do vingador do sangue, para que morra.

[[v5-19-13]]

^<<v5-19-13,13>>^ Não o olharás com piedade; antes, exterminarás de Israel a culpa do sangue inocente, para que te vá bem.

[[v5-19-14]]

^<<v5-19-14,14>>^ Não mudes os marcos do teu próximo, que os antigos fixaram na tua herança, na terra que o SENHOR, teu Deus, te dá para a possuíres.

[[v5-19-15]]

^<<v5-19-15,15>>^ Uma só testemunha não se levantará contra alguém por qualquer iniquidade ou por qualquer pecado, seja qual for que cometer; pelo depoimento de duas ou três testemunhas, se estabelecerá o fato.

[[v5-19-16]]

^<<v5-19-16,16>>^ Quando se levantar testemunha falsa contra alguém, para o acusar de algum transvio,

[[v5-19-17]]

^<<v5-19-17,17>>^ então, os dois homens que tiverem a demanda se apresentarão perante o SENHOR, diante dos sacerdotes e dos juízes que houver naqueles dias.

[[v5-19-18]]

^<<v5-19-18,18>>^ Os juízes indagarão bem; se a testemunha for falsa e tiver testemunhado falsamente contra seu irmão,

[[v5-19-19]]

^<<v5-19-19,19>>^ far-lhe-eis como cuidou fazer a seu irmão; e, assim, exterminarás o mal do meio de ti;

[[v5-19-20]]

^<<v5-19-20,20>>^ para que os que ficarem o ouçam, e temam, e nunca mais tornem a fazer semelhante mal no meio de ti.

[[v5-19-21]]

^<<v5-19-21,21>>^ Não o olharás com piedade: vida por vida, olho por olho, dente por dente, mão por mão, pé por pé.

'''

xref:005-deuteronomio/005-deuteronomio-018.adoc#v5-18-0[&#60; Capítulo Anterior] | <<v5-19-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-020.adoc#v5-20-0[Próximo Capítulo &#62;]