include::./index.adoc[]

[[v5-8-0]]
=== Deuteronômio, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-8-1]]

^<<v5-8-1,1>>^ Cuidareis de cumprir todos os mandamentos que hoje vos ordeno, para que vivais, e vos multipliqueis, e entreis, e possuais a terra que o SENHOR prometeu sob juramento a vossos pais.

[[v5-8-2]]

^<<v5-8-2,2>>^ Recordar-te-ás de todo o caminho pelo qual o SENHOR, teu Deus, te guiou no deserto estes quarenta anos, para te humilhar, para te provar, para saber o que estava no teu coração, se guardarias ou não os seus mandamentos.

[[v5-8-3]]

^<<v5-8-3,3>>^ Ele te humilhou, e te deixou ter fome, e te sustentou com o maná, que tu não conhecias, nem teus pais o conheciam, para te dar a entender que não só de pão viverá o homem, mas de tudo o que procede da boca do SENHOR viverá o homem.

[[v5-8-4]]

^<<v5-8-4,4>>^ Nunca envelheceu a tua veste sobre ti, nem se inchou o teu pé nestes quarenta anos.

[[v5-8-5]]

^<<v5-8-5,5>>^ Sabe, pois, no teu coração, que, como um homem disciplina a seu filho, assim te disciplina o SENHOR, teu Deus.

[[v5-8-6]]

^<<v5-8-6,6>>^ Guarda os mandamentos do SENHOR, teu Deus, para andares nos seus caminhos e o temeres;

[[v5-8-7]]

^<<v5-8-7,7>>^ porque o SENHOR, teu Deus, te faz entrar numa boa terra, terra de ribeiros de águas, de fontes, de mananciais profundos, que saem dos vales e das montanhas;

[[v5-8-8]]

^<<v5-8-8,8>>^ terra de trigo e cevada, de vides, figueiras e romeiras; terra de oliveiras, de azeite e mel;

[[v5-8-9]]

^<<v5-8-9,9>>^ terra em que comerás o pão sem escassez, e nada te faltará nela; terra cujas pedras são ferro e de cujos montes cavarás o cobre.

[[v5-8-10]]

^<<v5-8-10,10>>^ Comerás, e te fartarás, e louvarás o SENHOR, teu Deus, pela boa terra que te deu.

[[v5-8-11]]

^<<v5-8-11,11>>^ Guarda-te não te esqueças do SENHOR, teu Deus, não cumprindo os seus mandamentos, os seus juízos e os seus estatutos, que hoje te ordeno;

[[v5-8-12]]

^<<v5-8-12,12>>^ para não suceder que, depois de teres comido e estiveres farto, depois de haveres edificado boas casas e morado nelas;

[[v5-8-13]]

^<<v5-8-13,13>>^ depois de se multiplicarem os teus gados e os teus rebanhos, e se aumentar a tua prata e o teu ouro, e ser abundante tudo quanto tens,

[[v5-8-14]]

^<<v5-8-14,14>>^ se eleve o teu coração, e te esqueças do SENHOR, teu Deus, que te tirou da terra do Egito, da casa da servidão,

[[v5-8-15]]

^<<v5-8-15,15>>^ que te conduziu por aquele grande e terrível deserto de serpentes abrasadoras, de escorpiões e de secura, em que não havia água; e te fez sair água da pederneira;

[[v5-8-16]]

^<<v5-8-16,16>>^ que no deserto te sustentou com maná, que teus pais não conheciam; para te humilhar, e para te provar, e, afinal, te fazer bem.

[[v5-8-17]]

^<<v5-8-17,17>>^ Não digas, pois, no teu coração: A minha força e o poder do meu braço me adquiriram estas riquezas.

[[v5-8-18]]

^<<v5-8-18,18>>^ Antes, te lembrarás do SENHOR, teu Deus, porque é ele o que te dá força para adquirires riquezas; para confirmar a sua aliança, que, sob juramento, prometeu a teus pais, como hoje se vê.

[[v5-8-19]]

^<<v5-8-19,19>>^ Se te esqueceres do SENHOR, teu Deus, e andares após outros deuses, e os servires, e os adorares, protesto, hoje, contra vós outros que perecereis.

[[v5-8-20]]

^<<v5-8-20,20>>^ Como as nações que o SENHOR destruiu de diante de vós, assim perecereis; porquanto não quisestes obedecer à voz do SENHOR, vosso Deus.

'''

xref:005-deuteronomio/005-deuteronomio-007.adoc#v5-7-0[&#60; Capítulo Anterior] | <<v5-8-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-009.adoc#v5-9-0[Próximo Capítulo &#62;]