include::./index.adoc[]

[[v5-34-0]]
=== Deuteronômio, 34
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-34-1]]

^<<v5-34-1,1>>^ Então, subiu Moisés das campinas de Moabe ao monte Nebo, ao cimo de Pisga, que está defronte de Jericó; e o SENHOR lhe mostrou toda a terra de Gileade até Dã;

[[v5-34-2]]

^<<v5-34-2,2>>^ e todo o Naftali, e a terra de Efraim, e Manassés; e toda a terra de Judá até ao mar ocidental;

[[v5-34-3]]

^<<v5-34-3,3>>^ e o Neguebe e a campina do vale de Jericó, a cidade das Palmeiras, até Zoar.

[[v5-34-4]]

^<<v5-34-4,4>>^ Disse-lhe o SENHOR: Esta é a terra que, sob juramento, prometi a Abraão, a Isaque e a Jacó, dizendo: à tua descendência a darei; eu te faço vê-la com os próprios olhos; porém não irás para lá.

[[v5-34-5]]

^<<v5-34-5,5>>^ Assim, morreu ali Moisés, servo do SENHOR, na terra de Moabe, segundo a palavra do SENHOR.

[[v5-34-6]]

^<<v5-34-6,6>>^ Este o sepultou num vale, na terra de Moabe, defronte de Bete-Peor; e ninguém sabe, até hoje, o lugar da sua sepultura.

[[v5-34-7]]

^<<v5-34-7,7>>^ Tinha Moisés a idade de cento e vinte anos quando morreu; não se lhe escureceram os olhos, nem se lhe abateu o vigor.

[[v5-34-8]]

^<<v5-34-8,8>>^ Os filhos de Israel prantearam Moisés por trinta dias, nas campinas de Moabe; então, se cumpriram os dias do pranto no luto por Moisés.

[[v5-34-9]]

^<<v5-34-9,9>>^ Josué, filho de Num, estava cheio do espírito de sabedoria, porquanto Moisés impôs sobre ele as mãos; assim, os filhos de Israel lhe deram ouvidos e fizeram como o SENHOR ordenara a Moisés.

[[v5-34-10]]

^<<v5-34-10,10>>^ Nunca mais se levantou em Israel profeta algum como Moisés, com quem o SENHOR houvesse tratado face a face,

[[v5-34-11]]

^<<v5-34-11,11>>^ no tocante a todos os sinais e maravilhas que, por mando do SENHOR, fez na terra do Egito, a Faraó, a todos os seus oficiais e a toda a sua terra;

[[v5-34-12]]

^<<v5-34-12,12>>^ e no tocante a todas as obras de sua poderosa mão e aos grandes e terríveis feitos que operou Moisés à vista de todo o Israel.

'''

xref:005-deuteronomio/005-deuteronomio-033.adoc#v5-33-0[&#60; Capítulo Anterior] | <<v5-34-0,Topo>> | xref:006-josue/006-josue-001.adoc#v6-1-0[Próximo Capítulo &#62;]