include::./index.adoc[]

[[v5-32-0]]
=== Deuteronômio, 32
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-32-1]]

^<<v5-32-1,1>>^ Inclinai os ouvidos, ó céus, e falarei; e ouça a terra as palavras da minha boca.

[[v5-32-2]]

^<<v5-32-2,2>>^ Goteje a minha doutrina como a chuva, destile a minha palavra como o orvalho, como chuvisco sobre a relva e como gotas de água sobre a erva.

[[v5-32-3]]

^<<v5-32-3,3>>^ Porque proclamarei o nome do SENHOR. Engrandecei o nosso Deus.

[[v5-32-4]]

^<<v5-32-4,4>>^ Eis a Rocha! Suas obras são perfeitas, porque todos os seus caminhos são juízo; Deus é fidelidade, e não há nele injustiça; é justo e reto.

[[v5-32-5]]

^<<v5-32-5,5>>^ Procederam corruptamente contra ele, já não são seus filhos, e sim suas manchas; é geração perversa e deformada.

[[v5-32-6]]

^<<v5-32-6,6>>^ É assim que recompensas ao SENHOR, povo louco e ignorante? Não é ele teu pai, que te adquiriu, te fez e te estabeleceu?

[[v5-32-7]]

^<<v5-32-7,7>>^ Lembra-te dos dias da antiguidade, atenta para os anos de gerações e gerações; pergunta a teu pai, e ele te informará, aos teus anciãos, e eles to dirão.

[[v5-32-8]]

^<<v5-32-8,8>>^ Quando o Altíssimo distribuía as heranças às nações, quando separava os filhos dos homens uns dos outros, fixou os limites dos povos, segundo o número dos filhos de Israel.

[[v5-32-9]]

^<<v5-32-9,9>>^ Porque a porção do SENHOR é o seu povo; Jacó é a parte da sua herança.

[[v5-32-10]]

^<<v5-32-10,10>>^ Achou-o numa terra deserta e num ermo solitário povoado de uivos; rodeou-o e cuidou dele, guardou-o como a menina dos olhos.

[[v5-32-11]]

^<<v5-32-11,11>>^ Como a águia desperta a sua ninhada e voeja sobre os seus filhotes, estende as asas e, tomando-os, os leva sobre elas,

[[v5-32-12]]

^<<v5-32-12,12>>^ assim, só o SENHOR o guiou, e não havia com ele deus estranho.

[[v5-32-13]]

^<<v5-32-13,13>>^ Ele o fez cavalgar sobre os altos da terra, comer as messes do campo, chupar mel da rocha e azeite da dura pederneira,

[[v5-32-14]]

^<<v5-32-14,14>>^ coalhada de vacas e leite de ovelhas, com a gordura dos cordeiros, dos carneiros que pastam em Basã e dos bodes, com o mais escolhido trigo; e bebeste o sangue das uvas, o mosto.

[[v5-32-15]]

^<<v5-32-15,15>>^ Mas, engordando-se o meu amado, deu coices; engordou-se, engrossou-se, ficou nédio e abandonou a Deus, que o fez, desprezou a Rocha da sua salvação.

[[v5-32-16]]

^<<v5-32-16,16>>^ Com deuses estranhos o provocaram a zelos, com abominações o irritaram.

[[v5-32-17]]

^<<v5-32-17,17>>^ Sacrifícios ofereceram aos demônios, não a Deus; a deuses que não conheceram, novos deuses que vieram há pouco, dos quais não se estremeceram seus pais.

[[v5-32-18]]

^<<v5-32-18,18>>^ Olvidaste a Rocha que te gerou; e te esqueceste do Deus que te deu o ser.

[[v5-32-19]]

^<<v5-32-19,19>>^ Viu isto o SENHOR e os desprezou, por causa da provocação de seus filhos e suas filhas;

[[v5-32-20]]

^<<v5-32-20,20>>^ e disse: Esconderei deles o rosto, verei qual será o seu fim; porque são raça de perversidade, filhos em quem não há lealdade.

[[v5-32-21]]

^<<v5-32-21,21>>^ A zelos me provocaram com aquilo que não é Deus; com seus ídolos me provocaram à ira; portanto, eu os provocarei a zelos com aquele que não é povo; com louca nação os despertarei à ira.

[[v5-32-22]]

^<<v5-32-22,22>>^ Porque um fogo se acendeu no meu furor e arderá até ao mais profundo do inferno, consumirá a terra e suas messes e abrasará os fundamentos dos montes.

[[v5-32-23]]

^<<v5-32-23,23>>^ Amontoarei males sobre eles; as minhas setas esgotarei contra eles.

[[v5-32-24]]

^<<v5-32-24,24>>^ Consumidos serão pela fome, devorados pela febre e peste violenta; e contra eles enviarei dentes de feras e ardente peçonha de serpentes do pó.

[[v5-32-25]]

^<<v5-32-25,25>>^ Fora devastará a espada, em casa, o pavor, tanto ao jovem como à virgem, tanto à criança de peito como ao homem encanecido.

[[v5-32-26]]

^<<v5-32-26,26>>^ Eu teria dito: Por todos os cantos os espalharei e farei cessar a sua memória dentre os homens,

[[v5-32-27]]

^<<v5-32-27,27>>^ se eu não tivesse receado a provocação do inimigo, para que os seus adversários não se iludam, para que não digam: A nossa mão tem prevalecido, e não foi o SENHOR quem fez tudo isto.

[[v5-32-28]]

^<<v5-32-28,28>>^ Porque o meu povo é gente falta de conselhos, e neles não há entendimento.

[[v5-32-29]]

^<<v5-32-29,29>>^ Tomara fossem eles sábios! Então, entenderiam isto e atentariam para o seu fim.

[[v5-32-30]]

^<<v5-32-30,30>>^ Como poderia um só perseguir mil, e dois fazerem fugir dez mil, se a sua Rocha lhos não vendera, e o SENHOR lhos não entregara?

[[v5-32-31]]

^<<v5-32-31,31>>^ Porque a rocha deles não é como a nossa Rocha; e os próprios inimigos o atestam.

[[v5-32-32]]

^<<v5-32-32,32>>^ Porque a sua vinha é da vinha de Sodoma e dos campos de Gomorra; as suas uvas são uvas de veneno, seus cachos, amargos;

[[v5-32-33]]

^<<v5-32-33,33>>^ o seu vinho é ardente veneno de répteis e peçonha terrível de víboras.

[[v5-32-34]]

^<<v5-32-34,34>>^ Não está isto guardado comigo, selado nos meus tesouros?

[[v5-32-35]]

^<<v5-32-35,35>>^ A mim me pertence a vingança, a retribuição, a seu tempo, quando resvalar o seu pé; porque o dia da sua calamidade está próximo, e o seu destino se apressa em chegar.

[[v5-32-36]]

^<<v5-32-36,36>>^ Porque o SENHOR fará justiça ao seu povo e se compadecerá dos seus servos, quando vir que o seu poder se foi, e já não há nem escravo nem livre.

[[v5-32-37]]

^<<v5-32-37,37>>^ Então, dirá: Onde estão os seus deuses? E a rocha em quem confiavam?

[[v5-32-38]]

^<<v5-32-38,38>>^ Deuses que comiam a gordura de seus sacrifícios e bebiam o vinho de suas libações? Levantem-se eles e vos ajudem, para que haja esconderijo para vós outros!

[[v5-32-39]]

^<<v5-32-39,39>>^ Vede, agora, que Eu Sou, Eu somente, e mais nenhum deus além de mim; eu mato e eu faço viver; eu firo e eu saro; e não há quem possa livrar alguém da minha mão.

[[v5-32-40]]

^<<v5-32-40,40>>^ Levanto a mão aos céus e afirmo por minha vida eterna:

[[v5-32-41]]

^<<v5-32-41,41>>^ se eu afiar a minha espada reluzente, e a minha mão exercitar o juízo, tomarei vingança contra os meus adversários e retribuirei aos que me odeiam.

[[v5-32-42]]

^<<v5-32-42,42>>^ Embriagarei as minhas setas de sangue (a minha espada comerá carne), do sangue dos mortos e dos prisioneiros, das cabeças cabeludas do inimigo.

[[v5-32-43]]

^<<v5-32-43,43>>^ Louvai, ó nações, o seu povo, porque o SENHOR vingará o sangue dos seus servos, tomará vingança dos seus adversários e fará expiação pela terra do seu povo.

[[v5-32-44]]

^<<v5-32-44,44>>^ Veio Moisés e falou todas as palavras deste cântico aos ouvidos do povo, ele e Josué, filho de Num.

[[v5-32-45]]

^<<v5-32-45,45>>^ Tendo Moisés falado todas estas palavras a todo o Israel,

[[v5-32-46]]

^<<v5-32-46,46>>^ disse-lhes: Aplicai o coração a todas as palavras que, hoje, testifico entre vós, para que ordeneis a vossos filhos que cuidem de cumprir todas as palavras desta lei.

[[v5-32-47]]

^<<v5-32-47,47>>^ Porque esta palavra não é para vós outros coisa vã; antes, é a vossa vida; e, por esta mesma palavra, prolongareis os dias na terra à qual, passando o Jordão, ides para a possuir.

[[v5-32-48]]

^<<v5-32-48,48>>^ Naquele mesmo dia, falou o SENHOR a Moisés, dizendo:

[[v5-32-49]]

^<<v5-32-49,49>>^ Sobe a este monte de Abarim, ao monte Nebo, que está na terra de Moabe, defronte de Jericó, e vê a terra de Canaã, que aos filhos de Israel dou em possessão.

[[v5-32-50]]

^<<v5-32-50,50>>^ E morrerás no monte, ao qual terás subido, e te recolherás ao teu povo, como Arão, teu irmão, morreu no monte Hor e se recolheu ao seu povo,

[[v5-32-51]]

^<<v5-32-51,51>>^ porquanto prevaricastes contra mim no meio dos filhos de Israel, nas águas de Meribá de Cades, no deserto de Zim, pois me não santificastes no meio dos filhos de Israel.

[[v5-32-52]]

^<<v5-32-52,52>>^ Pelo que verás a terra defronte de ti, porém não entrarás nela, na terra que dou aos filhos de Israel.

'''

xref:005-deuteronomio/005-deuteronomio-031.adoc#v5-31-0[&#60; Capítulo Anterior] | <<v5-32-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-033.adoc#v5-33-0[Próximo Capítulo &#62;]