include::./index.adoc[]

[[v5-28-0]]
=== Deuteronômio, 28
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-28-1]]

^<<v5-28-1,1>>^ Se atentamente ouvires a voz do SENHOR, teu Deus, tendo cuidado de guardar todos os seus mandamentos que hoje te ordeno, o SENHOR, teu Deus, te exaltará sobre todas as nações da terra.

[[v5-28-2]]

^<<v5-28-2,2>>^ Se ouvires a voz do SENHOR, teu Deus, virão sobre ti e te alcançarão todas estas bênçãos:

[[v5-28-3]]

^<<v5-28-3,3>>^ Bendito serás tu na cidade e bendito serás no campo.

[[v5-28-4]]

^<<v5-28-4,4>>^ Bendito o fruto do teu ventre, e o fruto da tua terra, e o fruto dos teus animais, e as crias das tuas vacas e das tuas ovelhas.

[[v5-28-5]]

^<<v5-28-5,5>>^ Bendito o teu cesto e a tua amassadeira.

[[v5-28-6]]

^<<v5-28-6,6>>^ Bendito serás ao entrares e bendito, ao saíres.

[[v5-28-7]]

^<<v5-28-7,7>>^ O SENHOR fará que sejam derrotados na tua presença os inimigos que se levantarem contra ti; por um caminho, sairão contra ti, mas, por sete caminhos, fugirão da tua presença.

[[v5-28-8]]

^<<v5-28-8,8>>^ O SENHOR determinará que a bênção esteja nos teus celeiros e em tudo o que colocares a mão; e te abençoará na terra que te dá o SENHOR, teu Deus.

[[v5-28-9]]

^<<v5-28-9,9>>^ O SENHOR te constituirá para si em povo santo, como te tem jurado, quando guardares os mandamentos do SENHOR, teu Deus, e andares nos seus caminhos.

[[v5-28-10]]

^<<v5-28-10,10>>^ E todos os povos da terra verão que és chamado pelo nome do SENHOR e terão medo de ti.

[[v5-28-11]]

^<<v5-28-11,11>>^ O SENHOR te dará abundância de bens no fruto do teu ventre, no fruto dos teus animais e no fruto do teu solo, na terra que o SENHOR, sob juramento a teus pais, prometeu dar-te.

[[v5-28-12]]

^<<v5-28-12,12>>^ O SENHOR te abrirá o seu bom tesouro, o céu, para dar chuva à tua terra no seu tempo e para abençoar toda obra das tuas mãos; emprestarás a muitas gentes, porém tu não tomarás emprestado.

[[v5-28-13]]

^<<v5-28-13,13>>^ O SENHOR te porá por cabeça e não por cauda; e só estarás em cima e não debaixo, se obedeceres aos mandamentos do SENHOR, teu Deus, que hoje te ordeno, para os guardar e cumprir.

[[v5-28-14]]

^<<v5-28-14,14>>^ Não te desviarás de todas as palavras que hoje te ordeno, nem para a direita nem para a esquerda, seguindo outros deuses, para os servires.

[[v5-28-15]]

^<<v5-28-15,15>>^ Será, porém, que, se não deres ouvidos à voz do SENHOR, teu Deus, não cuidando em cumprir todos os seus mandamentos e os seus estatutos que, hoje, te ordeno, então, virão todas estas maldições sobre ti e te alcançarão:

[[v5-28-16]]

^<<v5-28-16,16>>^ Maldito serás tu na cidade e maldito serás no campo.

[[v5-28-17]]

^<<v5-28-17,17>>^ Maldito o teu cesto e a tua amassadeira.

[[v5-28-18]]

^<<v5-28-18,18>>^ Maldito o fruto do teu ventre, e o fruto da tua terra, e as crias das tuas vacas e das tuas ovelhas.

[[v5-28-19]]

^<<v5-28-19,19>>^ Maldito serás ao entrares e maldito, ao saíres.

[[v5-28-20]]

^<<v5-28-20,20>>^ O SENHOR mandará sobre ti a maldição, a confusão e a ameaça em tudo quanto empreenderes, até que sejas destruído e repentinamente pereças, por causa da maldade das tuas obras, com que me abandonaste.

[[v5-28-21]]

^<<v5-28-21,21>>^ O SENHOR fará que a pestilência te pegue a ti, até que te consuma a terra a que passas para possuí-la.

[[v5-28-22]]

^<<v5-28-22,22>>^ O SENHOR te ferirá com a tísica, e a febre, e a inflamação, e com o calor ardente, e a secura, e com o crestamento, e a ferrugem; e isto te perseguirá até que pereças.

[[v5-28-23]]

^<<v5-28-23,23>>^ Os teus céus sobre a tua cabeça serão de bronze; e a terra debaixo de ti será de ferro.

[[v5-28-24]]

^<<v5-28-24,24>>^ Por chuva da tua terra, o SENHOR te dará pó e cinza; dos céus, descerá sobre ti, até que sejas destruído.

[[v5-28-25]]

^<<v5-28-25,25>>^ O SENHOR te fará cair diante dos teus inimigos; por um caminho, sairás contra eles, e, por sete caminhos, fugirás diante deles, e serás motivo de horror para todos os reinos da terra.

[[v5-28-26]]

^<<v5-28-26,26>>^ O teu cadáver servirá de pasto a todas as aves dos céus e aos animais da terra; e ninguém haverá que os espante.

[[v5-28-27]]

^<<v5-28-27,27>>^ O SENHOR te ferirá com as úlceras do Egito, com tumores, com sarna e com prurido de que não possas curar-te.

[[v5-28-28]]

^<<v5-28-28,28>>^ O SENHOR te ferirá com loucura, com cegueira e com perturbação do espírito.

[[v5-28-29]]

^<<v5-28-29,29>>^ Apalparás ao meio-dia, como o cego apalpa nas trevas, e não prosperarás nos teus caminhos; porém somente serás oprimido e roubado todos os teus dias; e ninguém haverá que te salve.

[[v5-28-30]]

^<<v5-28-30,30>>^ Desposar-te-ás com uma mulher, porém outro homem dormirá com ela; edificarás casa, porém não morarás nela; plantarás vinha, porém não a desfrutarás.

[[v5-28-31]]

^<<v5-28-31,31>>^ O teu boi será morto aos teus olhos, porém dele não comerás; o teu jumento será roubado diante de ti e não voltará a ti; as tuas ovelhas serão dadas aos teus inimigos; e ninguém haverá que te salve.

[[v5-28-32]]

^<<v5-28-32,32>>^ Teus filhos e tuas filhas serão dados a outro povo; os teus olhos o verão e desfalecerão de saudades todo o dia; porém a tua mão nada poderá fazer.

[[v5-28-33]]

^<<v5-28-33,33>>^ O fruto da tua terra e todo o teu trabalho, comê-los-á um povo que nunca conheceste; e tu serás oprimido e quebrantado todos os dias;

[[v5-28-34]]

^<<v5-28-34,34>>^ e te enlouquecerás pelo que vires com os teus olhos.

[[v5-28-35]]

^<<v5-28-35,35>>^ O SENHOR te ferirá com úlceras malignas nos joelhos e nas pernas, das quais não te possas curar, desde a planta do pé até ao alto da cabeça.

[[v5-28-36]]

^<<v5-28-36,36>>^ O SENHOR te levará e o teu rei que tiveres constituído sobre ti a uma gente que não conheceste, nem tu, nem teus pais; e ali servirás a outros deuses, feitos de madeira e de pedra.

[[v5-28-37]]

^<<v5-28-37,37>>^ Virás a ser pasmo, provérbio e motejo entre todos os povos a que o SENHOR te levará.

[[v5-28-38]]

^<<v5-28-38,38>>^ Lançarás muita semente ao campo; porém colherás pouco, porque o gafanhoto a consumirá.

[[v5-28-39]]

^<<v5-28-39,39>>^ Plantarás e cultivarás muitas vinhas, porém do seu vinho não beberás, nem colherás as uvas, porque o verme as devorará.

[[v5-28-40]]

^<<v5-28-40,40>>^ Em todos os teus limites terás oliveiras; porém não te ungirás com azeite, porque as tuas azeitonas cairão.

[[v5-28-41]]

^<<v5-28-41,41>>^ Gerarás filhos e filhas, porém não ficarão contigo, porque serão levados ao cativeiro.

[[v5-28-42]]

^<<v5-28-42,42>>^ Todo o teu arvoredo e o fruto da tua terra o gafanhoto os consumirá.

[[v5-28-43]]

^<<v5-28-43,43>>^ O estrangeiro que está no meio de ti se elevará mais e mais, e tu mais e mais descerás.

[[v5-28-44]]

^<<v5-28-44,44>>^ Ele te emprestará a ti, porém tu não lhe emprestarás a ele; ele será por cabeça, e tu serás por cauda.

[[v5-28-45]]

^<<v5-28-45,45>>^ Todas estas maldições virão sobre ti, e te perseguirão, e te alcançarão, até que sejas destruído, porquanto não ouviste a voz do SENHOR, teu Deus, para guardares os mandamentos e os estatutos que te ordenou.

[[v5-28-46]]

^<<v5-28-46,46>>^ Serão, no teu meio, por sinal e por maravilha, como também entre a tua descendência, para sempre.

[[v5-28-47]]

^<<v5-28-47,47>>^ Porquanto não serviste ao SENHOR, teu Deus, com alegria e bondade de coração, não obstante a abundância de tudo.

[[v5-28-48]]

^<<v5-28-48,48>>^ Assim, com fome, com sede, com nudez e com falta de tudo, servirás aos inimigos que o SENHOR enviará contra ti; sobre o teu pescoço porá um jugo de ferro, até que te haja destruído.

[[v5-28-49]]

^<<v5-28-49,49>>^ O SENHOR levantará contra ti uma nação de longe, da extremidade da terra virá, como o voo impetuoso da águia, nação cuja língua não entenderás;

[[v5-28-50]]

^<<v5-28-50,50>>^ nação feroz de rosto, que não respeitará ao velho, nem se apiedará do moço.

[[v5-28-51]]

^<<v5-28-51,51>>^ Ela comerá o fruto dos teus animais e o fruto da tua terra, até que sejas destruído; e não te deixará cereal, mosto, nem azeite, nem as crias das tuas vacas e das tuas ovelhas, até que te haja consumido.

[[v5-28-52]]

^<<v5-28-52,52>>^ Sitiar-te-á em todas as tuas cidades, até que venham a cair, em toda a tua terra, os altos e fortes muros em que confiavas; e te sitiará em todas as tuas cidades, em toda a terra que o SENHOR, teu Deus, te deu.

[[v5-28-53]]

^<<v5-28-53,53>>^ Comerás o fruto do teu ventre, a carne de teus filhos e de tuas filhas, que te der o SENHOR, teu Deus, na angústia e no aperto com que os teus inimigos te apertarão.

[[v5-28-54]]

^<<v5-28-54,54>>^ O mais mimoso dos homens e o mais delicado do teu meio será mesquinho para com seu irmão, e para com a mulher do seu amor, e para com os demais de seus filhos que ainda lhe restarem;

[[v5-28-55]]

^<<v5-28-55,55>>^ de sorte que não dará a nenhum deles da carne de seus filhos, que ele comer; porquanto nada lhe ficou de resto na angústia e no aperto com que o teu inimigo te apertará em todas as tuas cidades.

[[v5-28-56]]

^<<v5-28-56,56>>^ A mais mimosa das mulheres e a mais delicada do teu meio, que de mimo e delicadeza não tentaria pôr a planta do pé sobre a terra, será mesquinha para com o marido de seu amor, e para com seu filho, e para com sua filha;

[[v5-28-57]]

^<<v5-28-57,57>>^ mesquinha da placenta que lhe saiu dentre os pés e dos filhos que tiver, porque os comerá às escondidas pela falta de tudo, na angústia e no aperto com que o teu inimigo te apertará nas tuas cidades.

[[v5-28-58]]

^<<v5-28-58,58>>^ Se não tiveres cuidado de guardar todas as palavras desta lei, escritas neste livro, para temeres este nome glorioso e terrível, o SENHOR, teu Deus,

[[v5-28-59]]

^<<v5-28-59,59>>^ então, o SENHOR fará terríveis as tuas pragas e as pragas de tua descendência, grandes e duradouras pragas, e enfermidades graves e duradouras;

[[v5-28-60]]

^<<v5-28-60,60>>^ fará voltar contra ti todas as moléstias do Egito, que temeste; e se apegarão a ti.

[[v5-28-61]]

^<<v5-28-61,61>>^ Também o SENHOR fará vir sobre ti toda enfermidade e toda praga que não estão escritas no livro desta Lei, até que sejas destruído.

[[v5-28-62]]

^<<v5-28-62,62>>^ Ficareis poucos em número, vós que éreis como as estrelas dos céus em multidão, porque não destes ouvidos à voz do SENHOR, vosso Deus.

[[v5-28-63]]

^<<v5-28-63,63>>^ Assim como o SENHOR se alegrava em vós outros, em fazer-vos bem e multiplicar-vos, da mesma sorte o SENHOR se alegrará em vos fazer perecer e vos destruir; sereis desarraigados da terra à qual passais para possuí-la.

[[v5-28-64]]

^<<v5-28-64,64>>^ O SENHOR vos espalhará entre todos os povos, de uma até à outra extremidade da terra. Servirás ali a outros deuses que não conheceste, nem tu, nem teus pais; servirás à madeira e à pedra.

[[v5-28-65]]

^<<v5-28-65,65>>^ Nem ainda entre estas nações descansarás, nem a planta de teu pé terá repouso, porquanto o SENHOR ali te dará coração tremente, olhos mortiços e desmaio de alma.

[[v5-28-66]]

^<<v5-28-66,66>>^ A tua vida estará suspensa como por um fio diante de ti; terás pavor de noite e de dia e não crerás na tua vida.

[[v5-28-67]]

^<<v5-28-67,67>>^ Pela manhã dirás: Ah! Quem me dera ver a noite! E, à noitinha, dirás: Ah! Quem me dera ver a manhã! Isso pelo pavor que sentirás no coração e pelo espetáculo que terás diante dos olhos.

[[v5-28-68]]

^<<v5-28-68,68>>^ O SENHOR te fará voltar ao Egito em navios, pelo caminho de que te disse: Nunca jamais o verás; sereis ali oferecidos para venda como escravos e escravas aos vossos inimigos, mas não haverá quem vos compre.

'''

xref:005-deuteronomio/005-deuteronomio-027.adoc#v5-27-0[&#60; Capítulo Anterior] | <<v5-28-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-029.adoc#v5-29-0[Próximo Capítulo &#62;]