include::./index.adoc[]

[[v5-27-0]]
=== Deuteronômio, 27
// ara ?, ARA - Almeida Revista e Atualizada

[[v5-27-1]]

^<<v5-27-1,1>>^ Moisés e os anciãos de Israel deram ordem ao povo, dizendo: Guarda todos estes mandamentos que, hoje, te ordeno.

[[v5-27-2]]

^<<v5-27-2,2>>^ No dia em que passares o Jordão à terra que te der o SENHOR, teu Deus, levantar-te-ás pedras grandes e as caiarás.

[[v5-27-3]]

^<<v5-27-3,3>>^ Havendo-o passado, escreverás, nelas, todas as palavras desta lei, para entrares na terra que te dá o SENHOR, teu Deus, terra que mana leite e mel, como te prometeu o SENHOR, Deus de teus pais.

[[v5-27-4]]

^<<v5-27-4,4>>^ Quando houveres passado o Jordão, levantarás estas pedras, que hoje te ordeno, no monte Ebal, e as caiarás.

[[v5-27-5]]

^<<v5-27-5,5>>^ Ali, edificarás um altar ao SENHOR, teu Deus, altar de pedras, sobre as quais não manejarás instrumento de ferro.

[[v5-27-6]]

^<<v5-27-6,6>>^ De pedras toscas edificarás o altar do SENHOR, teu Deus; e sobre ele lhe oferecerás holocaustos.

[[v5-27-7]]

^<<v5-27-7,7>>^ Também sacrificarás ofertas pacíficas; ali, comerás e te alegrarás perante o SENHOR, teu Deus.

[[v5-27-8]]

^<<v5-27-8,8>>^ Nestas pedras, escreverás, mui distintamente, as palavras todas desta lei.

[[v5-27-9]]

^<<v5-27-9,9>>^ Falou mais Moisés, juntamente com os sacerdotes levitas, a todo o Israel, dizendo: Guarda silêncio e ouve, ó Israel! Hoje, vieste a ser povo do SENHOR, teu Deus.

[[v5-27-10]]

^<<v5-27-10,10>>^ Portanto, obedecerás à voz do SENHOR, teu Deus, e lhe cumprirás os mandamentos e os estatutos que hoje te ordeno.

[[v5-27-11]]

^<<v5-27-11,11>>^ Moisés deu ordem, naquele dia, ao povo, dizendo:

[[v5-27-12]]

^<<v5-27-12,12>>^ Quando houveres passado o Jordão, estarão sobre o monte Gerizim, para abençoarem o povo, estes: Simeão, Levi, Judá, Issacar, José e Benjamim.

[[v5-27-13]]

^<<v5-27-13,13>>^ E estes, para amaldiçoar, estarão sobre o monte Ebal: Rúben, Gade, Aser, Zebulom, Dã e Naftali.

[[v5-27-14]]

^<<v5-27-14,14>>^ Os levitas testificarão a todo o povo de Israel em alta voz e dirão:

[[v5-27-15]]

^<<v5-27-15,15>>^ Maldito o homem que fizer imagem de escultura ou de fundição, abominável ao SENHOR, obra de artífice, e a puser em lugar oculto. E todo o povo responderá: Amém!

[[v5-27-16]]

^<<v5-27-16,16>>^ Maldito aquele que desprezar a seu pai ou a sua mãe. E todo o povo dirá: Amém!

[[v5-27-17]]

^<<v5-27-17,17>>^ Maldito aquele que mudar os marcos do seu próximo. E todo o povo dirá: Amém!

[[v5-27-18]]

^<<v5-27-18,18>>^ Maldito aquele que fizer o cego errar o caminho. E todo o povo dirá: Amém!

[[v5-27-19]]

^<<v5-27-19,19>>^ Maldito aquele que perverter o direito do estrangeiro, do órfão e da viúva. E todo o povo dirá: Amém!

[[v5-27-20]]

^<<v5-27-20,20>>^ Maldito aquele que se deitar com a madrasta, porquanto profanaria o leito de seu pai. E todo o povo dirá: Amém!

[[v5-27-21]]

^<<v5-27-21,21>>^ Maldito aquele que se ajuntar com animal. E todo o povo dirá: Amém!

[[v5-27-22]]

^<<v5-27-22,22>>^ Maldito aquele que se deitar com sua irmã, filha de seu pai ou filha de sua mãe. E todo o povo dirá: Amém!

[[v5-27-23]]

^<<v5-27-23,23>>^ Maldito aquele que se deitar com sua sogra. E todo o povo dirá: Amém!

[[v5-27-24]]

^<<v5-27-24,24>>^ Maldito aquele que ferir o seu próximo em oculto. E todo o povo dirá: Amém!

[[v5-27-25]]

^<<v5-27-25,25>>^ Maldito aquele que aceitar suborno para matar pessoa inocente. E todo o povo dirá: Amém!

[[v5-27-26]]

^<<v5-27-26,26>>^ Maldito aquele que não confirmar as palavras desta lei, não as cumprindo. E todo o povo dirá: Amém!

'''

xref:005-deuteronomio/005-deuteronomio-026.adoc#v5-26-0[&#60; Capítulo Anterior] | <<v5-27-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-028.adoc#v5-28-0[Próximo Capítulo &#62;]