include::./index.adoc[]

[[v34-1-0]]
=== Naum, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v34-1-1]]

^<<v34-1-1,1>>^ Sentença contra Nínive. Livro da visão de Naum, o elcosita.

[[v34-1-2]]

^<<v34-1-2,2>>^ O SENHOR é Deus zeloso e vingador, o SENHOR é vingador e cheio de ira; o SENHOR toma vingança contra os seus adversários e reserva indignação para os seus inimigos.

[[v34-1-3]]

^<<v34-1-3,3>>^ O SENHOR é tardio em irar-se, mas grande em poder e jamais inocenta o culpado; o SENHOR tem o seu caminho na tormenta e na tempestade, e as nuvens são o pó dos seus pés.

[[v34-1-4]]

^<<v34-1-4,4>>^ Ele repreende o mar, e o faz secar, e míngua todos os rios; desfalecem Basã e o Carmelo, e a flor do Líbano se murcha.

[[v34-1-5]]

^<<v34-1-5,5>>^ Os montes tremem perante ele, e os outeiros se derretem; e a terra se levanta diante dele, sim, o mundo e todos os que nele habitam.

[[v34-1-6]]

^<<v34-1-6,6>>^ Quem pode suportar a sua indignação? E quem subsistirá diante do furor da sua ira? A sua cólera se derrama como fogo, e as rochas são por ele demolidas.

[[v34-1-7]]

^<<v34-1-7,7>>^ O SENHOR é bom, é fortaleza no dia da angústia e conhece os que nele se refugiam.

[[v34-1-8]]

^<<v34-1-8,8>>^ Mas, com inundação transbordante, acabará de uma vez com o lugar desta cidade; com trevas, perseguirá o SENHOR os seus inimigos.

[[v34-1-9]]

^<<v34-1-9,9>>^ Que pensais vós contra o SENHOR? Ele mesmo vos consumirá de todo; não se levantará por duas vezes a angústia.

[[v34-1-10]]

^<<v34-1-10,10>>^ Porque, ainda que eles se entrelaçam como os espinhos e se saturam de vinho como bêbados, serão inteiramente consumidos como palha seca.

[[v34-1-11]]

^<<v34-1-11,11>>^ De ti, Nínive, saiu um que maquina o mal contra o SENHOR, um conselheiro vil.

[[v34-1-12]]

^<<v34-1-12,12>>^ Assim diz o SENHOR: Por mais seguros que estejam e por mais numerosos que sejam, ainda assim serão exterminados e passarão; eu te afligi, mas não te afligirei mais.

[[v34-1-13]]

^<<v34-1-13,13>>^ Mas de sobre ti, Judá, quebrarei o jugo deles e romperei os teus laços.

[[v34-1-14]]

^<<v34-1-14,14>>^ Porém contra ti, Assíria, o SENHOR deu ordem que não haja posteridade que leve o teu nome; da casa dos teus deuses exterminarei as imagens de escultura e de fundição; farei o teu sepulcro, porque és vil.

[[v34-1-15]]

^<<v34-1-15,15>>^ Eis sobre os montes os pés do que anuncia boas-novas, do que anuncia a paz! Celebra as tuas festas, ó Judá, cumpre os teus votos, porque o homem vil já não passará por ti; ele é inteiramente exterminado.

'''

xref:033-miqueias/033-miqueias-007.adoc#v33-7-0[&#60; Capítulo Anterior] | <<v34-1-0,Topo>> | xref:034-naum/034-naum-002.adoc#v34-2-0[Próximo Capítulo &#62;]