include::./index.adoc[]

[[v34-3-0]]
=== Naum, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v34-3-1]]

^<<v34-3-1,1>>^ Ai da cidade sanguinária, toda cheia de mentiras e de roubo e que não solta a sua presa!

[[v34-3-2]]

^<<v34-3-2,2>>^ Eis o estalo de açoites e o estrondo das rodas; o galope de cavalos e carros que vão saltando;

[[v34-3-3]]

^<<v34-3-3,3>>^ os cavaleiros que esporeiam, a espada flamejante, o relampejar da lança e multidão de traspassados, massa de cadáveres, mortos sem fim; tropeça gente sobre os mortos.

[[v34-3-4]]

^<<v34-3-4,4>>^ Tudo isso por causa da grande prostituição da bela e encantadora meretriz, da mestra de feitiçarias, que vendia os povos com a sua prostituição e as gentes, com as suas feitiçarias.

[[v34-3-5]]

^<<v34-3-5,5>>^ Eis que eu estou contra ti, diz o SENHOR dos Exércitos; levantarei as abas de tua saia sobre o teu rosto, e mostrarei às nações a tua nudez, e aos reinos, as tuas vergonhas.

[[v34-3-6]]

^<<v34-3-6,6>>^ Lançarei sobre ti imundícias, tratar-te-ei com desprezo e te porei por espetáculo.

[[v34-3-7]]

^<<v34-3-7,7>>^ Há de ser que todos os que te virem fugirão de ti e dirão: Nínive está destruída; quem terá compaixão dela? De onde buscarei os que te consolem?

[[v34-3-8]]

^<<v34-3-8,8>>^ És tu melhor do que Nô-Amom, que estava situada entre o Nilo e seus canais, cercada de águas, tendo por baluarte o mar e ainda o mar, por muralha?

[[v34-3-9]]

^<<v34-3-9,9>>^ Etiópia e Egito eram a sua força, e esta, sem limite; Pute e Líbia, o seu socorro.

[[v34-3-10]]

^<<v34-3-10,10>>^ Todavia, ela foi levada ao exílio, foi para o cativeiro; também os seus filhos foram despedaçados nas esquinas de todas as ruas; sobre os seus nobres lançaram sortes, e todos os seus grandes foram presos com grilhões.

[[v34-3-11]]

^<<v34-3-11,11>>^ Também tu, Nínive, serás embriagada e te esconderás; também procurarás refúgio contra o inimigo.

[[v34-3-12]]

^<<v34-3-12,12>>^ Todas as tuas fortalezas são como figueiras com figos temporãos; se os sacodem, caem na boca do que os há de comer.

[[v34-3-13]]

^<<v34-3-13,13>>^ Eis que as tuas tropas, no meio de ti, são como mulheres; as portas do teu país estão abertas de par em par aos teus inimigos; o fogo consome os teus ferrolhos.

[[v34-3-14]]

^<<v34-3-14,14>>^ Tira água para o tempo do cerco, fortifica as tuas fortalezas, entra no barro e pisa a massa, toma a forma para os ladrilhos.

[[v34-3-15]]

^<<v34-3-15,15>>^ No entanto, o fogo ali te consumirá, a espada te exterminará, consumir-te-á como o gafanhoto. Ainda que te multiplicas como o gafanhoto e te multiplicas como a locusta;

[[v34-3-16]]

^<<v34-3-16,16>>^ ainda que fizeste os teus negociantes mais numerosos do que as estrelas do céu, o gafanhoto devorador invade e sai voando.

[[v34-3-17]]

^<<v34-3-17,17>>^ Os teus príncipes são como os gafanhotos, e os teus chefes, como os gafanhotos grandes, que se acampam nas sebes nos dias de frio; em subindo o sol, voam embora, e não se conhece o lugar onde estão.

[[v34-3-18]]

^<<v34-3-18,18>>^ Os teus pastores dormem, ó rei da Assíria; os teus nobres dormitam; o teu povo se derrama pelos montes, e não há quem o ajunte.

[[v34-3-19]]

^<<v34-3-19,19>>^ Não há remédio para a tua ferida; a tua chaga é incurável; todos os que ouvirem a tua fama baterão palmas sobre ti; porque sobre quem não passou continuamente a tua maldade?

'''

xref:034-naum/034-naum-002.adoc#v34-2-0[&#60; Capítulo Anterior] | <<v34-3-0,Topo>> | xref:035-habacuque/035-habacuque-001.adoc#v35-1-0[Próximo Capítulo &#62;]