include::./index.adoc[]

[[v48-1-0]]
=== Gálatas, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v48-1-1]]

^<<v48-1-1,1>>^ Paulo, apóstolo, não da parte de homens, nem por intermédio de homem algum, mas por Jesus Cristo e por Deus Pai, que o ressuscitou dentre os mortos,

[[v48-1-2]]

^<<v48-1-2,2>>^ e todos os irmãos meus companheiros, às igrejas da Galácia,

[[v48-1-3]]

^<<v48-1-3,3>>^ graça a vós outros e paz, da parte de Deus, nosso Pai, e do [nosso] Senhor Jesus Cristo,

[[v48-1-4]]

^<<v48-1-4,4>>^ o qual se entregou a si mesmo pelos nossos pecados, para nos desarraigar deste mundo perverso, segundo a vontade de nosso Deus e Pai,

[[v48-1-5]]

^<<v48-1-5,5>>^ a quem seja a glória pelos séculos dos séculos. Amém!

[[v48-1-6]]

^<<v48-1-6,6>>^ Admira-me que estejais passando tão depressa daquele que vos chamou na graça de Cristo para outro evangelho,

[[v48-1-7]]

^<<v48-1-7,7>>^ o qual não é outro, senão que há alguns que vos perturbam e querem perverter o evangelho de Cristo.

[[v48-1-8]]

^<<v48-1-8,8>>^ Mas, ainda que nós ou mesmo um anjo vindo do céu vos pregue evangelho que vá além do que vos temos pregado, seja anátema.

[[v48-1-9]]

^<<v48-1-9,9>>^ Assim, como já dissemos, e agora repito, se alguém vos prega evangelho que vá além daquele que recebestes, seja anátema.

[[v48-1-10]]

^<<v48-1-10,10>>^ Porventura, procuro eu, agora, o favor dos homens ou o de Deus? Ou procuro agradar a homens? Se agradasse ainda a homens, não seria servo de Cristo.

[[v48-1-11]]

^<<v48-1-11,11>>^ Faço-vos, porém, saber, irmãos, que o evangelho por mim anunciado não é segundo o homem,

[[v48-1-12]]

^<<v48-1-12,12>>^ porque eu não o recebi, nem o aprendi de homem algum, mas mediante revelação de Jesus Cristo.

[[v48-1-13]]

^<<v48-1-13,13>>^ Porque ouvistes qual foi o meu proceder outrora no judaísmo, como sobremaneira perseguia eu a igreja de Deus e a devastava.

[[v48-1-14]]

^<<v48-1-14,14>>^ E, na minha nação, quanto ao judaísmo, avantajava-me a muitos da minha idade, sendo extremamente zeloso das tradições de meus pais.

[[v48-1-15]]

^<<v48-1-15,15>>^ Quando, porém, ao que me separou antes de eu nascer e me chamou pela sua graça, aprouve

[[v48-1-16]]

^<<v48-1-16,16>>^ revelar seu Filho em mim, para que eu o pregasse entre os gentios, sem detença, não consultei carne e sangue,

[[v48-1-17]]

^<<v48-1-17,17>>^ nem subi a Jerusalém para os que já eram apóstolos antes de mim, mas parti para as regiões da Arábia e voltei, outra vez, para Damasco.

[[v48-1-18]]

^<<v48-1-18,18>>^ Decorridos três anos, então, subi a Jerusalém para avistar-me com Cefas e permaneci com ele quinze dias;

[[v48-1-19]]

^<<v48-1-19,19>>^ e não vi outro dos apóstolos, senão Tiago, o irmão do Senhor.

[[v48-1-20]]

^<<v48-1-20,20>>^ Ora, acerca do que vos escrevo, eis que diante de Deus testifico que não minto.

[[v48-1-21]]

^<<v48-1-21,21>>^ Depois, fui para as regiões da Síria e da Cilícia.

[[v48-1-22]]

^<<v48-1-22,22>>^ E não era conhecido de vista das igrejas da Judeia, que estavam em Cristo.

[[v48-1-23]]

^<<v48-1-23,23>>^ Ouviam somente dizer: Aquele que, antes, nos perseguia, agora, prega a fé que, outrora, procurava destruir.

[[v48-1-24]]

^<<v48-1-24,24>>^ E glorificavam a Deus a meu respeito.

'''

xref:047-2-corintios/047-2-corintios-013.adoc#v47-13-0[&#60; Capítulo Anterior] | <<v48-1-0,Topo>> | xref:048-galatas/048-galatas-002.adoc#v48-2-0[Próximo Capítulo &#62;]