include::./index.adoc[]

[[v48-5-0]]
=== Gálatas, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v48-5-1]]

^<<v48-5-1,1>>^ Para a liberdade foi que Cristo nos libertou. Permanecei, pois, firmes e não vos submetais, de novo, a jugo de escravidão.

[[v48-5-2]]

^<<v48-5-2,2>>^ Eu, Paulo, vos digo que, se vos deixardes circuncidar, Cristo de nada vos aproveitará.

[[v48-5-3]]

^<<v48-5-3,3>>^ De novo, testifico a todo homem que se deixa circuncidar que está obrigado a guardar toda a lei.

[[v48-5-4]]

^<<v48-5-4,4>>^ De Cristo vos desligastes, vós que procurais justificar-vos na lei; da graça decaístes.

[[v48-5-5]]

^<<v48-5-5,5>>^ Porque nós, pelo Espírito, aguardamos a esperança da justiça que provém da fé.

[[v48-5-6]]

^<<v48-5-6,6>>^ Porque, em Cristo Jesus, nem a circuncisão, nem a incircuncisão têm valor algum, mas a fé que atua pelo amor.

[[v48-5-7]]

^<<v48-5-7,7>>^ Vós corríeis bem; quem vos impediu de continuardes a obedecer à verdade?

[[v48-5-8]]

^<<v48-5-8,8>>^ Esta persuasão não vem daquele que vos chama.

[[v48-5-9]]

^<<v48-5-9,9>>^ Um pouco de fermento leveda toda a massa.

[[v48-5-10]]

^<<v48-5-10,10>>^ Confio de vós, no Senhor, que não alimentareis nenhum outro sentimento; mas aquele que vos perturba, seja ele quem for, sofrerá a condenação.

[[v48-5-11]]

^<<v48-5-11,11>>^ Eu, porém, irmãos, se ainda prego a circuncisão, por que continuo sendo perseguido? Logo, está desfeito o escândalo da cruz.

[[v48-5-12]]

^<<v48-5-12,12>>^ Tomara até se mutilassem os que vos incitam à rebeldia.

[[v48-5-13]]

^<<v48-5-13,13>>^ Porque vós, irmãos, fostes chamados à liberdade; porém não useis da liberdade para dar ocasião à carne; sede, antes, servos uns dos outros, pelo amor.

[[v48-5-14]]

^<<v48-5-14,14>>^ Porque toda a lei se cumpre em um só preceito, a saber: Amarás o teu próximo como a ti mesmo.

[[v48-5-15]]

^<<v48-5-15,15>>^ Se vós, porém, vos mordeis e devorais uns aos outros, vede que não sejais mutuamente destruídos.

[[v48-5-16]]

^<<v48-5-16,16>>^ Digo, porém: andai no Espírito e jamais satisfareis à concupiscência da carne.

[[v48-5-17]]

^<<v48-5-17,17>>^ Porque a carne milita contra o Espírito, e o Espírito, contra a carne, porque são opostos entre si; para que não façais o que, porventura, seja do vosso querer.

[[v48-5-18]]

^<<v48-5-18,18>>^ Mas, se sois guiados pelo Espírito, não estais sob a lei.

[[v48-5-19]]

^<<v48-5-19,19>>^ Ora, as obras da carne são conhecidas e são: prostituição, impureza, lascívia,

[[v48-5-20]]

^<<v48-5-20,20>>^ idolatria, feitiçarias, inimizades, porfias, ciúmes, iras, discórdias, dissensões, facções,

[[v48-5-21]]

^<<v48-5-21,21>>^ invejas, bebedices, glutonarias e coisas semelhantes a estas, a respeito das quais eu vos declaro, como já, outrora, vos preveni, que não herdarão o reino de Deus os que tais coisas praticam.

[[v48-5-22]]

^<<v48-5-22,22>>^ Mas o fruto do Espírito é: amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade,

[[v48-5-23]]

^<<v48-5-23,23>>^ mansidão, domínio próprio. Contra estas coisas não há lei.

[[v48-5-24]]

^<<v48-5-24,24>>^ E os que são de Cristo Jesus crucificaram a carne, com as suas paixões e concupiscências.

[[v48-5-25]]

^<<v48-5-25,25>>^ Se vivemos no Espírito, andemos também no Espírito.

[[v48-5-26]]

^<<v48-5-26,26>>^ Não nos deixemos possuir de vanglória, provocando uns aos outros, tendo inveja uns dos outros.

'''

xref:048-galatas/048-galatas-004.adoc#v48-4-0[&#60; Capítulo Anterior] | <<v48-5-0,Topo>> | xref:048-galatas/048-galatas-006.adoc#v48-6-0[Próximo Capítulo &#62;]