include::./index.adoc[]

[[v48-6-0]]
=== Gálatas, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v48-6-1]]

^<<v48-6-1,1>>^ Irmãos, se alguém for surpreendido nalguma falta, vós, que sois espirituais, corrigi-o com espírito de brandura; e guarda-te para que não sejas também tentado.

[[v48-6-2]]

^<<v48-6-2,2>>^ Levai as cargas uns dos outros e, assim, cumprireis a lei de Cristo.

[[v48-6-3]]

^<<v48-6-3,3>>^ Porque, se alguém julga ser alguma coisa, não sendo nada, a si mesmo se engana.

[[v48-6-4]]

^<<v48-6-4,4>>^ Mas prove cada um o seu labor e, então, terá motivo de gloriar-se unicamente em si e não em outro.

[[v48-6-5]]

^<<v48-6-5,5>>^ Porque cada um levará o seu próprio fardo.

[[v48-6-6]]

^<<v48-6-6,6>>^ Mas aquele que está sendo instruído na palavra faça participante de todas as coisas boas aquele que o instrui.

[[v48-6-7]]

^<<v48-6-7,7>>^ Não vos enganeis: de Deus não se zomba; pois aquilo que o homem semear, isso também ceifará.

[[v48-6-8]]

^<<v48-6-8,8>>^ Porque o que semeia para a sua própria carne da carne colherá corrupção; mas o que semeia para o Espírito do Espírito colherá vida eterna.

[[v48-6-9]]

^<<v48-6-9,9>>^ E não nos cansemos de fazer o bem, porque a seu tempo ceifaremos, se não desfalecermos.

[[v48-6-10]]

^<<v48-6-10,10>>^ Por isso, enquanto tivermos oportunidade, façamos o bem a todos, mas principalmente aos da família da fé.

[[v48-6-11]]

^<<v48-6-11,11>>^ Vede com que letras grandes vos escrevi de meu próprio punho.

[[v48-6-12]]

^<<v48-6-12,12>>^ Todos os que querem ostentar-se na carne, esses vos constrangem a vos circuncidardes, somente para não serem perseguidos por causa da cruz de Cristo.

[[v48-6-13]]

^<<v48-6-13,13>>^ Pois nem mesmo aqueles que se deixam circuncidar guardam a lei; antes, querem que vos circuncideis, para se gloriarem na vossa carne.

[[v48-6-14]]

^<<v48-6-14,14>>^ Mas longe esteja de mim gloriar-me, senão na cruz de nosso Senhor Jesus Cristo, pela qual o mundo está crucificado para mim, e eu, para o mundo.

[[v48-6-15]]

^<<v48-6-15,15>>^ Pois nem a circuncisão é coisa alguma, nem a incircuncisão, mas o ser nova criatura.

[[v48-6-16]]

^<<v48-6-16,16>>^ E, a todos quantos andarem de conformidade com esta regra, paz e misericórdia sejam sobre eles e sobre o Israel de Deus.

[[v48-6-17]]

^<<v48-6-17,17>>^ Quanto ao mais, ninguém me moleste; porque eu trago no corpo as marcas de Jesus.

[[v48-6-18]]

^<<v48-6-18,18>>^ A graça de nosso Senhor Jesus Cristo seja, irmãos, com o vosso espírito. Amém!

'''

xref:048-galatas/048-galatas-005.adoc#v48-5-0[&#60; Capítulo Anterior] | <<v48-6-0,Topo>> | xref:049-efesios/049-efesios-001.adoc#v49-1-0[Próximo Capítulo &#62;]