include::./index.adoc[]

[[v48-2-0]]
=== Gálatas, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v48-2-1]]

^<<v48-2-1,1>>^ Catorze anos depois, subi outra vez a Jerusalém com Barnabé, levando também a Tito.

[[v48-2-2]]

^<<v48-2-2,2>>^ Subi em obediência a uma revelação; e lhes expus o evangelho que prego entre os gentios, mas em particular aos que pareciam de maior influência, para, de algum modo, não correr ou ter corrido em vão.

[[v48-2-3]]

^<<v48-2-3,3>>^ Contudo, nem mesmo Tito, que estava comigo, sendo grego, foi constrangido a circuncidar-se.

[[v48-2-4]]

^<<v48-2-4,4>>^ E isto por causa dos falsos irmãos que se entremeteram com o fim de espreitar a nossa liberdade que temos em Cristo Jesus e reduzir-nos à escravidão;

[[v48-2-5]]

^<<v48-2-5,5>>^ aos quais nem ainda por uma hora nos submetemos, para que a verdade do evangelho permanecesse entre vós.

[[v48-2-6]]

^<<v48-2-6,6>>^ E, quanto àqueles que pareciam ser de maior influência (quais tenham sido, outrora, não me interessa; Deus não aceita a aparência do homem), esses, digo, que me pareciam ser alguma coisa nada me acrescentaram;

[[v48-2-7]]

^<<v48-2-7,7>>^ antes, pelo contrário, quando viram que o evangelho da incircuncisão me fora confiado, como a Pedro o da circuncisão

[[v48-2-8]]

^<<v48-2-8,8>>^ (pois aquele que operou eficazmente em Pedro para o apostolado da circuncisão também operou eficazmente em mim para com os gentios)

[[v48-2-9]]

^<<v48-2-9,9>>^ e, quando conheceram a graça que me foi dada, Tiago, Cefas e João, que eram reputados colunas, me estenderam, a mim e a Barnabé, a destra de comunhão, a fim de que nós fôssemos para os gentios, e eles, para a circuncisão;

[[v48-2-10]]

^<<v48-2-10,10>>^ recomendando-nos somente que nos lembrássemos dos pobres, o que também me esforcei por fazer.

[[v48-2-11]]

^<<v48-2-11,11>>^ Quando, porém, Cefas veio a Antioquia, resisti-lhe face a face, porque se tornara repreensível.

[[v48-2-12]]

^<<v48-2-12,12>>^ Com efeito, antes de chegarem alguns da parte de Tiago, comia com os gentios; quando, porém, chegaram, afastou-se e, por fim, veio a apartar-se, temendo os da circuncisão.

[[v48-2-13]]

^<<v48-2-13,13>>^ E também os demais judeus dissimularam com ele, a ponto de o próprio Barnabé ter-se deixado levar pela dissimulação deles.

[[v48-2-14]]

^<<v48-2-14,14>>^ Quando, porém, vi que não procediam corretamente segundo a verdade do evangelho, disse a Cefas, na presença de todos: se, sendo tu judeu, vives como gentio e não como judeu, por que obrigas os gentios a viverem como judeus?

[[v48-2-15]]

^<<v48-2-15,15>>^ Nós, judeus por natureza e não pecadores dentre os gentios,

[[v48-2-16]]

^<<v48-2-16,16>>^ sabendo, contudo, que o homem não é justificado por obras da lei, e sim mediante a fé em Cristo Jesus, também temos crido em Cristo Jesus, para que fôssemos justificados pela fé em Cristo e não por obras da lei, pois, por obras da lei, ninguém será justificado.

[[v48-2-17]]

^<<v48-2-17,17>>^ Mas se, procurando ser justificados em Cristo, fomos nós mesmos também achados pecadores, dar-se-á o caso de ser Cristo ministro do pecado? Certo que não!

[[v48-2-18]]

^<<v48-2-18,18>>^ Porque, se torno a edificar aquilo que destruí, a mim mesmo me constituo transgressor.

[[v48-2-19]]

^<<v48-2-19,19>>^ Porque eu, mediante a própria lei, morri para a lei, a fim de viver para Deus. Estou crucificado com Cristo;

[[v48-2-20]]

^<<v48-2-20,20>>^ logo, já não sou eu quem vive, mas Cristo vive em mim; e esse viver que, agora, tenho na carne, vivo pela fé no Filho de Deus, que me amou e a si mesmo se entregou por mim.

[[v48-2-21]]

^<<v48-2-21,21>>^ Não anulo a graça de Deus; pois, se a justiça é mediante a lei, segue-se que morreu Cristo em vão.

'''

xref:048-galatas/048-galatas-001.adoc#v48-1-0[&#60; Capítulo Anterior] | <<v48-2-0,Topo>> | xref:048-galatas/048-galatas-003.adoc#v48-3-0[Próximo Capítulo &#62;]