include::./index.adoc[]

[[v48-3-0]]
=== Gálatas, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v48-3-1]]

^<<v48-3-1,1>>^ Ó gálatas insensatos! Quem vos fascinou a vós outros, ante cujos olhos foi Jesus Cristo exposto como crucificado?

[[v48-3-2]]

^<<v48-3-2,2>>^ Quero apenas saber isto de vós: recebestes o Espírito pelas obras da lei ou pela pregação da fé?

[[v48-3-3]]

^<<v48-3-3,3>>^ Sois assim insensatos que, tendo começado no Espírito, estejais, agora, vos aperfeiçoando na carne?

[[v48-3-4]]

^<<v48-3-4,4>>^ Terá sido em vão que tantas coisas sofrestes? Se, na verdade, foram em vão.

[[v48-3-5]]

^<<v48-3-5,5>>^ Aquele, pois, que vos concede o Espírito e que opera milagres entre vós, porventura, o faz pelas obras da lei ou pela pregação da fé?

[[v48-3-6]]

^<<v48-3-6,6>>^ É o caso de Abraão, que creu em Deus, e isso lhe foi imputado para justiça.

[[v48-3-7]]

^<<v48-3-7,7>>^ Sabei, pois, que os da fé é que são filhos de Abraão.

[[v48-3-8]]

^<<v48-3-8,8>>^ Ora, tendo a Escritura previsto que Deus justificaria pela fé os gentios, preanunciou o evangelho a Abraão: Em ti, serão abençoados todos os povos.

[[v48-3-9]]

^<<v48-3-9,9>>^ De modo que os da fé são abençoados com o crente Abraão.

[[v48-3-10]]

^<<v48-3-10,10>>^ Todos quantos, pois, são das obras da lei estão debaixo de maldição; porque está escrito: Maldito todo aquele que não permanece em todas as coisas escritas no Livro da lei, para praticá-las.

[[v48-3-11]]

^<<v48-3-11,11>>^ E é evidente que, pela lei, ninguém é justificado diante de Deus, porque o justo viverá pela fé.

[[v48-3-12]]

^<<v48-3-12,12>>^ Ora, a lei não procede de fé, mas: Aquele que observar os seus preceitos por eles viverá.

[[v48-3-13]]

^<<v48-3-13,13>>^ Cristo nos resgatou da maldição da lei, fazendo-se ele próprio maldição em nosso lugar (porque está escrito: Maldito todo aquele que for pendurado em madeiro ),

[[v48-3-14]]

^<<v48-3-14,14>>^ para que a bênção de Abraão chegasse aos gentios, em Jesus Cristo, a fim de que recebêssemos, pela fé, o Espírito prometido.

[[v48-3-15]]

^<<v48-3-15,15>>^ Irmãos, falo como homem. Ainda que uma aliança seja meramente humana, uma vez ratificada, ninguém a revoga ou lhe acrescenta alguma coisa.

[[v48-3-16]]

^<<v48-3-16,16>>^ Ora, as promessas foram feitas a Abraão e ao seu descendente. Não diz: E aos descendentes, como se falando de muitos, porém como de um só: E ao teu descendente, que é Cristo.

[[v48-3-17]]

^<<v48-3-17,17>>^ E digo isto: uma aliança já anteriormente confirmada por Deus, a lei, que veio quatrocentos e trinta anos depois, não a pode ab-rogar, de forma que venha a desfazer a promessa.

[[v48-3-18]]

^<<v48-3-18,18>>^ Porque, se a herança provém de lei, já não decorre de promessa; mas foi pela promessa que Deus a concedeu gratuitamente a Abraão.

[[v48-3-19]]

^<<v48-3-19,19>>^ Qual, pois, a razão de ser da lei? Foi adicionada por causa das transgressões, até que viesse o descendente a quem se fez a promessa, e foi promulgada por meio de anjos, pela mão de um mediador.

[[v48-3-20]]

^<<v48-3-20,20>>^ Ora, o mediador não é de um, mas Deus é um.

[[v48-3-21]]

^<<v48-3-21,21>>^ É, porventura, a lei contrária às promessas de Deus? De modo nenhum! Porque, se fosse promulgada uma lei que pudesse dar vida, a justiça, na verdade, seria procedente de lei.

[[v48-3-22]]

^<<v48-3-22,22>>^ Mas a Escritura encerrou tudo sob o pecado, para que, mediante a fé em Jesus Cristo, fosse a promessa concedida aos que creem.

[[v48-3-23]]

^<<v48-3-23,23>>^ Mas, antes que viesse a fé, estávamos sob a tutela da lei e nela encerrados, para essa fé que, de futuro, haveria de revelar-se.

[[v48-3-24]]

^<<v48-3-24,24>>^ De maneira que a lei nos serviu de aio para nos conduzir a Cristo, a fim de que fôssemos justificados por fé.

[[v48-3-25]]

^<<v48-3-25,25>>^ Mas, tendo vindo a fé, já não permanecemos subordinados ao aio.

[[v48-3-26]]

^<<v48-3-26,26>>^ Pois todos vós sois filhos de Deus mediante a fé em Cristo Jesus;

[[v48-3-27]]

^<<v48-3-27,27>>^ porque todos quantos fostes batizados em Cristo de Cristo vos revestistes.

[[v48-3-28]]

^<<v48-3-28,28>>^ Dessarte, não pode haver judeu nem grego; nem escravo nem liberto; nem homem nem mulher; porque todos vós sois um em Cristo Jesus.

[[v48-3-29]]

^<<v48-3-29,29>>^ E, se sois de Cristo, também sois descendentes de Abraão e herdeiros segundo a promessa.

'''

xref:048-galatas/048-galatas-002.adoc#v48-2-0[&#60; Capítulo Anterior] | <<v48-3-0,Topo>> | xref:048-galatas/048-galatas-004.adoc#v48-4-0[Próximo Capítulo &#62;]