include::./index.adoc[]

[[v21-3-0]]
=== Eclesiastes, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v21-3-1]]

^<<v21-3-1,1>>^ Tudo tem o seu tempo determinado, e há tempo para todo propósito debaixo do céu:

[[v21-3-2]]

^<<v21-3-2,2>>^ há tempo de nascer e tempo de morrer; tempo de plantar e tempo de arrancar o que se plantou;

[[v21-3-3]]

^<<v21-3-3,3>>^ tempo de matar e tempo de curar; tempo de derribar e tempo de edificar;

[[v21-3-4]]

^<<v21-3-4,4>>^ tempo de chorar e tempo de rir; tempo de prantear e tempo de saltar de alegria;

[[v21-3-5]]

^<<v21-3-5,5>>^ tempo de espalhar pedras e tempo de ajuntar pedras; tempo de abraçar e tempo de afastar-se de abraçar;

[[v21-3-6]]

^<<v21-3-6,6>>^ tempo de buscar e tempo de perder; tempo de guardar e tempo de deitar fora;

[[v21-3-7]]

^<<v21-3-7,7>>^ tempo de rasgar e tempo de coser; tempo de estar calado e tempo de falar;

[[v21-3-8]]

^<<v21-3-8,8>>^ tempo de amar e tempo de aborrecer; tempo de guerra e tempo de paz.

[[v21-3-9]]

^<<v21-3-9,9>>^ Que proveito tem o trabalhador naquilo com que se afadiga?

[[v21-3-10]]

^<<v21-3-10,10>>^ Vi o trabalho que Deus impôs aos filhos dos homens, para com ele os afligir.

[[v21-3-11]]

^<<v21-3-11,11>>^ Tudo fez Deus formoso no seu devido tempo; também pôs a eternidade no coração do homem, sem que este possa descobrir as obras que Deus fez desde o princípio até ao fim.

[[v21-3-12]]

^<<v21-3-12,12>>^ Sei que nada há melhor para o homem do que regozijar-se e levar vida regalada;

[[v21-3-13]]

^<<v21-3-13,13>>^ e também que é dom de Deus que possa o homem comer, beber e desfrutar o bem de todo o seu trabalho.

[[v21-3-14]]

^<<v21-3-14,14>>^ Sei que tudo quanto Deus faz durará eternamente; nada se lhe pode acrescentar e nada lhe tirar; e isto faz Deus para que os homens temam diante dele.

[[v21-3-15]]

^<<v21-3-15,15>>^ O que é já foi, e o que há de ser também já foi; Deus fará renovar-se o que se passou.

[[v21-3-16]]

^<<v21-3-16,16>>^ Vi ainda debaixo do sol que no lugar do juízo reinava a maldade e no lugar da justiça, maldade ainda.

[[v21-3-17]]

^<<v21-3-17,17>>^ Então, disse comigo: Deus julgará o justo e o perverso; pois há tempo para todo propósito e para toda obra.

[[v21-3-18]]

^<<v21-3-18,18>>^ Disse ainda comigo: é por causa dos filhos dos homens, para que Deus os prove, e eles vejam que são em si mesmos como os animais.

[[v21-3-19]]

^<<v21-3-19,19>>^ Porque o que sucede aos filhos dos homens sucede aos animais; o mesmo lhes sucede: como morre um, assim morre o outro, todos têm o mesmo fôlego de vida, e nenhuma vantagem tem o homem sobre os animais; porque tudo é vaidade.

[[v21-3-20]]

^<<v21-3-20,20>>^ Todos vão para o mesmo lugar; todos procedem do pó e ao pó tornarão.

[[v21-3-21]]

^<<v21-3-21,21>>^ Quem sabe se o fôlego de vida dos filhos dos homens se dirige para cima e o dos animais para baixo, para a terra?

[[v21-3-22]]

^<<v21-3-22,22>>^ Pelo que vi não haver coisa melhor do que alegrar-se o homem nas suas obras, porque essa é a sua recompensa; quem o fará voltar para ver o que será depois dele?

'''

xref:021-eclesiastes/021-eclesiastes-002.adoc#v21-2-0[&#60; Capítulo Anterior] | <<v21-3-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-004.adoc#v21-4-0[Próximo Capítulo &#62;]