include::./index.adoc[]

[[v21-7-0]]
=== Eclesiastes, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v21-7-1]]

^<<v21-7-1,1>>^ Melhor é a boa fama do que o unguento precioso, e o dia da morte, melhor do que o dia do nascimento.

[[v21-7-2]]

^<<v21-7-2,2>>^ Melhor é ir à casa onde há luto do que ir à casa onde há banquete, pois naquela se vê o fim de todos os homens; e os vivos que o tomem em consideração.

[[v21-7-3]]

^<<v21-7-3,3>>^ Melhor é a mágoa do que o riso, porque com a tristeza do rosto se faz melhor o coração.

[[v21-7-4]]

^<<v21-7-4,4>>^ O coração dos sábios está na casa do luto, mas o dos insensatos, na casa da alegria.

[[v21-7-5]]

^<<v21-7-5,5>>^ Melhor é ouvir a repreensão do sábio do que ouvir a canção do insensato.

[[v21-7-6]]

^<<v21-7-6,6>>^ Pois, qual o crepitar dos espinhos debaixo de uma panela, tal é a risada do insensato; também isto é vaidade.

[[v21-7-7]]

^<<v21-7-7,7>>^ Verdadeiramente, a opressão faz endoidecer até o sábio, e o suborno corrompe o coração.

[[v21-7-8]]

^<<v21-7-8,8>>^ Melhor é o fim das coisas do que o seu princípio; melhor é o paciente do que o arrogante.

[[v21-7-9]]

^<<v21-7-9,9>>^ Não te apresses em irar-te, porque a ira se abriga no íntimo dos insensatos.

[[v21-7-10]]

^<<v21-7-10,10>>^ Jamais digas: Por que foram os dias passados melhores do que estes? Pois não é sábio perguntar assim.

[[v21-7-11]]

^<<v21-7-11,11>>^ Boa é a sabedoria, havendo herança, e de proveito, para os que veem o sol.

[[v21-7-12]]

^<<v21-7-12,12>>^ A sabedoria protege como protege o dinheiro; mas o proveito da sabedoria é que ela dá vida ao seu possuidor.

[[v21-7-13]]

^<<v21-7-13,13>>^ Atenta para as obras de Deus, pois quem poderá endireitar o que ele torceu?

[[v21-7-14]]

^<<v21-7-14,14>>^ No dia da prosperidade, goza do bem; mas, no dia da adversidade, considera em que Deus fez tanto este como aquele, para que o homem nada descubra do que há de vir depois dele.

[[v21-7-15]]

^<<v21-7-15,15>>^ Tudo isto vi nos dias da minha vaidade: há justo que perece na sua justiça, e há perverso que prolonga os seus dias na sua perversidade.

[[v21-7-16]]

^<<v21-7-16,16>>^ Não sejas demasiadamente justo, nem exageradamente sábio; por que te destruirias a ti mesmo?

[[v21-7-17]]

^<<v21-7-17,17>>^ Não sejas demasiadamente perverso, nem sejas louco; por que morrerias fora do teu tempo?

[[v21-7-18]]

^<<v21-7-18,18>>^ Bom é que retenhas isto e também daquilo não retires a mão; pois quem teme a Deus de tudo isto sai ileso.

[[v21-7-19]]

^<<v21-7-19,19>>^ A sabedoria fortalece ao sábio, mais do que dez poderosos que haja na cidade.

[[v21-7-20]]

^<<v21-7-20,20>>^ Não há homem justo sobre a terra que faça o bem e que não peque.

[[v21-7-21]]

^<<v21-7-21,21>>^ Não apliques o coração a todas as palavras que se dizem, para que não venhas a ouvir o teu servo a amaldiçoar-te,

[[v21-7-22]]

^<<v21-7-22,22>>^ pois tu sabes que muitas vezes tu mesmo tens amaldiçoado a outros.

[[v21-7-23]]

^<<v21-7-23,23>>^ Tudo isto experimentei pela sabedoria; e disse: tornar-me-ei sábio, mas a sabedoria estava longe de mim.

[[v21-7-24]]

^<<v21-7-24,24>>^ O que está longe e mui profundo, quem o achará?

[[v21-7-25]]

^<<v21-7-25,25>>^ Apliquei-me a conhecer, e a investigar, e a buscar a sabedoria e meu juízo de tudo, e a conhecer que a perversidade é insensatez e a insensatez, loucura.

[[v21-7-26]]

^<<v21-7-26,26>>^ Achei coisa mais amarga do que a morte: a mulher cujo coração são redes e laços e cujas mãos são grilhões; quem for bom diante de Deus fugirá dela, mas o pecador virá a ser seu prisioneiro.

[[v21-7-27]]

^<<v21-7-27,27>>^ Eis o que achei, diz o Pregador, conferindo uma coisa com outra, para a respeito delas formar o meu juízo,

[[v21-7-28]]

^<<v21-7-28,28>>^ juízo que ainda procuro e não o achei: entre mil homens achei um como esperava, mas entre tantas mulheres não achei nem sequer uma.

[[v21-7-29]]

^<<v21-7-29,29>>^ Eis o que tão somente achei: que Deus fez o homem reto, mas ele se meteu em muitas astúcias.

'''

xref:021-eclesiastes/021-eclesiastes-006.adoc#v21-6-0[&#60; Capítulo Anterior] | <<v21-7-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-008.adoc#v21-8-0[Próximo Capítulo &#62;]