include::./index.adoc[]

[[v21-2-0]]
=== Eclesiastes, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v21-2-1]]

^<<v21-2-1,1>>^ Disse comigo: vamos! Eu te provarei com a alegria; goza, pois, a felicidade; mas também isso era vaidade.

[[v21-2-2]]

^<<v21-2-2,2>>^ Do riso disse: é loucura; e da alegria: de que serve?

[[v21-2-3]]

^<<v21-2-3,3>>^ Resolvi no meu coração dar-me ao vinho, regendo-me, contudo, pela sabedoria, e entregar-me à loucura, até ver o que melhor seria que fizessem os filhos dos homens debaixo do céu, durante os poucos dias da sua vida.

[[v21-2-4]]

^<<v21-2-4,4>>^ Empreendi grandes obras; edifiquei para mim casas; plantei para mim vinhas.

[[v21-2-5]]

^<<v21-2-5,5>>^ Fiz jardins e pomares para mim e nestes plantei árvores frutíferas de toda espécie.

[[v21-2-6]]

^<<v21-2-6,6>>^ Fiz para mim açudes, para regar com eles o bosque em que reverdeciam as árvores.

[[v21-2-7]]

^<<v21-2-7,7>>^ Comprei servos e servas e tive servos nascidos em casa; também possuí bois e ovelhas, mais do que possuíram todos os que antes de mim viveram em Jerusalém.

[[v21-2-8]]

^<<v21-2-8,8>>^ Amontoei também para mim prata e ouro e tesouros de reis e de províncias; provi-me de cantores e cantoras e das delícias dos filhos dos homens: mulheres e mulheres.

[[v21-2-9]]

^<<v21-2-9,9>>^ Engrandeci-me e sobrepujei a todos os que viveram antes de mim em Jerusalém; perseverou também comigo a minha sabedoria.

[[v21-2-10]]

^<<v21-2-10,10>>^ Tudo quanto desejaram os meus olhos não lhes neguei, nem privei o coração de alegria alguma, pois eu me alegrava com todas as minhas fadigas, e isso era a recompensa de todas elas.

[[v21-2-11]]

^<<v21-2-11,11>>^ Considerei todas as obras que fizeram as minhas mãos, como também o trabalho que eu, com fadigas, havia feito; e eis que tudo era vaidade e correr atrás do vento, e nenhum proveito havia debaixo do sol.

[[v21-2-12]]

^<<v21-2-12,12>>^ Então, passei a considerar a sabedoria, e a loucura, e a estultícia. Que fará o homem que seguir ao rei? O mesmo que outros já fizeram.

[[v21-2-13]]

^<<v21-2-13,13>>^ Então, vi que a sabedoria é mais proveitosa do que a estultícia, quanto a luz traz mais proveito do que as trevas.

[[v21-2-14]]

^<<v21-2-14,14>>^ Os olhos do sábio estão na sua cabeça, mas o estulto anda em trevas; contudo, entendi que o mesmo lhes sucede a ambos.

[[v21-2-15]]

^<<v21-2-15,15>>^ Pelo que disse eu comigo: como acontece ao estulto, assim me sucede a mim; por que, pois, busquei eu mais a sabedoria? Então, disse a mim mesmo que também isso era vaidade.

[[v21-2-16]]

^<<v21-2-16,16>>^ Pois, tanto do sábio como do estulto, a memória não durará para sempre; pois, passados alguns dias, tudo cai no esquecimento. Ah! Morre o sábio, e da mesma sorte, o estulto!

[[v21-2-17]]

^<<v21-2-17,17>>^ Pelo que aborreci a vida, pois me foi penosa a obra que se faz debaixo do sol; sim, tudo é vaidade e correr atrás do vento.

[[v21-2-18]]

^<<v21-2-18,18>>^ Também aborreci todo o meu trabalho, com que me afadiguei debaixo do sol, visto que o seu ganho eu havia de deixar a quem viesse depois de mim.

[[v21-2-19]]

^<<v21-2-19,19>>^ E quem pode dizer se será sábio ou estulto? Contudo, ele terá domínio sobre todo o ganho das minhas fadigas e sabedoria debaixo do sol; também isto é vaidade.

[[v21-2-20]]

^<<v21-2-20,20>>^ Então, me empenhei por que o coração se desesperasse de todo trabalho com que me afadigara debaixo do sol.

[[v21-2-21]]

^<<v21-2-21,21>>^ Porque há homem cujo trabalho é feito com sabedoria, ciência e destreza; contudo, deixará o seu ganho como porção a quem por ele não se esforçou; também isto é vaidade e grande mal.

[[v21-2-22]]

^<<v21-2-22,22>>^ Pois que tem o homem de todo o seu trabalho e da fadiga do seu coração, em que ele anda trabalhando debaixo do sol?

[[v21-2-23]]

^<<v21-2-23,23>>^ Porque todos os seus dias são dores, e o seu trabalho, desgosto; até de noite não descansa o seu coração; também isto é vaidade.

[[v21-2-24]]

^<<v21-2-24,24>>^ Nada há melhor para o homem do que comer, beber e fazer que a sua alma goze o bem do seu trabalho. No entanto, vi também que isto vem da mão de Deus,

[[v21-2-25]]

^<<v21-2-25,25>>^ pois, separado deste, quem pode comer ou quem pode alegrar-se?

[[v21-2-26]]

^<<v21-2-26,26>>^ Porque Deus dá sabedoria, conhecimento e prazer ao homem que lhe agrada; mas ao pecador dá trabalho, para que ele ajunte e amontoe, a fim de dar àquele que agrada a Deus. Também isto é vaidade e correr atrás do vento.

'''

xref:021-eclesiastes/021-eclesiastes-001.adoc#v21-1-0[&#60; Capítulo Anterior] | <<v21-2-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-003.adoc#v21-3-0[Próximo Capítulo &#62;]