include::./index.adoc[]

[[v21-5-0]]
=== Eclesiastes, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v21-5-1]]

^<<v21-5-1,1>>^ Guarda o pé, quando entrares na Casa de Deus; chegar-se para ouvir é melhor do que oferecer sacrifícios de tolos, pois não sabem que fazem mal.

[[v21-5-2]]

^<<v21-5-2,2>>^ Não te precipites com a tua boca, nem o teu coração se apresse a pronunciar palavra alguma diante de Deus; porque Deus está nos céus, e tu, na terra; portanto, sejam poucas as tuas palavras.

[[v21-5-3]]

^<<v21-5-3,3>>^ Porque dos muitos trabalhos vêm os sonhos, e do muito falar, palavras néscias.

[[v21-5-4]]

^<<v21-5-4,4>>^ Quando a Deus fizeres algum voto, não tardes em cumpri-lo; porque não se agrada de tolos. Cumpre o voto que fazes.

[[v21-5-5]]

^<<v21-5-5,5>>^ Melhor é que não votes do que votes e não cumpras.

[[v21-5-6]]

^<<v21-5-6,6>>^ Não consintas que a tua boca te faça culpado, nem digas diante do mensageiro de Deus que foi inadvertência; por que razão se iraria Deus por causa da tua palavra, a ponto de destruir as obras das tuas mãos?

[[v21-5-7]]

^<<v21-5-7,7>>^ Porque, como na multidão dos sonhos há vaidade, assim também, nas muitas palavras; tu, porém, teme a Deus.

[[v21-5-8]]

^<<v21-5-8,8>>^ Se vires em alguma província opressão de pobres e o roubo em lugar do direito e da justiça, não te maravilhes de semelhante caso; porque o que está alto tem acima de si outro mais alto que o explora, e sobre estes há ainda outros mais elevados que também exploram.

[[v21-5-9]]

^<<v21-5-9,9>>^ O proveito da terra é para todos; até o rei se serve do campo.

[[v21-5-10]]

^<<v21-5-10,10>>^ Quem ama o dinheiro jamais dele se farta; e quem ama a abundância nunca se farta da renda; também isto é vaidade.

[[v21-5-11]]

^<<v21-5-11,11>>^ Onde os bens se multiplicam, também se multiplicam os que deles comem; que mais proveito, pois, têm os seus donos do que os verem com seus olhos?

[[v21-5-12]]

^<<v21-5-12,12>>^ Doce é o sono do trabalhador, quer coma pouco, quer muito; mas a fartura do rico não o deixa dormir.

[[v21-5-13]]

^<<v21-5-13,13>>^ Grave mal vi debaixo do sol: as riquezas que seus donos guardam para o próprio dano.

[[v21-5-14]]

^<<v21-5-14,14>>^ E, se tais riquezas se perdem por qualquer má aventura, ao filho que gerou nada lhe fica na mão.

[[v21-5-15]]

^<<v21-5-15,15>>^ Como saiu do ventre de sua mãe, assim nu voltará, indo-se como veio; e do seu trabalho nada poderá levar consigo.

[[v21-5-16]]

^<<v21-5-16,16>>^ Também isto é grave mal: precisamente como veio, assim ele vai; e que proveito lhe vem de haver trabalhado para o vento?

[[v21-5-17]]

^<<v21-5-17,17>>^ Nas trevas, comeu em todos os seus dias, com muito enfado, com enfermidades e indignação.

[[v21-5-18]]

^<<v21-5-18,18>>^ Eis o que eu vi: boa e bela coisa é comer e beber e gozar cada um do bem de todo o seu trabalho, com que se afadigou debaixo do sol, durante os poucos dias da vida que Deus lhe deu; porque esta é a sua porção.

[[v21-5-19]]

^<<v21-5-19,19>>^ Quanto ao homem a quem Deus conferiu riquezas e bens e lhe deu poder para deles comer, e receber a sua porção, e gozar do seu trabalho, isto é dom de Deus.

[[v21-5-20]]

^<<v21-5-20,20>>^ Porque não se lembrará muito dos dias da sua vida, porquanto Deus lhe enche o coração de alegria.

'''

xref:021-eclesiastes/021-eclesiastes-004.adoc#v21-4-0[&#60; Capítulo Anterior] | <<v21-5-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-006.adoc#v21-6-0[Próximo Capítulo &#62;]