include::./index.adoc[]

[[v21-6-0]]
=== Eclesiastes, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v21-6-1]]

^<<v21-6-1,1>>^ Há um mal que vi debaixo do sol e que pesa sobre os homens:

[[v21-6-2]]

^<<v21-6-2,2>>^ o homem a quem Deus conferiu riquezas, bens e honra, e nada lhe falta de tudo quanto a sua alma deseja, mas Deus não lhe concede que disso coma; antes, o estranho o come; também isto é vaidade e grave aflição.

[[v21-6-3]]

^<<v21-6-3,3>>^ Se alguém gerar cem filhos e viver muitos anos, até avançada idade, e se a sua alma não se fartar do bem, e além disso não tiver sepultura, digo que um aborto é mais feliz do que ele;

[[v21-6-4]]

^<<v21-6-4,4>>^ pois debalde vem o aborto e em trevas se vai, e de trevas se cobre o seu nome;

[[v21-6-5]]

^<<v21-6-5,5>>^ não viu o sol, nada conhece. Todavia, tem mais descanso do que o outro,

[[v21-6-6]]

^<<v21-6-6,6>>^ ainda que aquele vivesse duas vezes mil anos, mas não gozasse o bem. Porventura, não vão todos para o mesmo lugar?

[[v21-6-7]]

^<<v21-6-7,7>>^ Todo trabalho do homem é para a sua boca; e, contudo, nunca se satisfaz o seu apetite.

[[v21-6-8]]

^<<v21-6-8,8>>^ Pois que vantagem tem o sábio sobre o tolo? Ou o pobre que sabe andar perante os vivos?

[[v21-6-9]]

^<<v21-6-9,9>>^ Melhor é a vista dos olhos do que o andar ocioso da cobiça; também isto é vaidade e correr atrás do vento.

[[v21-6-10]]

^<<v21-6-10,10>>^ A tudo quanto há de vir já se lhe deu o nome, e sabe-se o que é o homem, e que não pode contender com quem é mais forte do que ele.

[[v21-6-11]]

^<<v21-6-11,11>>^ É certo que há muitas coisas que só aumentam a vaidade, mas que aproveita isto ao homem?

[[v21-6-12]]

^<<v21-6-12,12>>^ Pois quem sabe o que é bom para o homem durante os poucos dias da sua vida de vaidade, os quais gasta como sombra? Quem pode declarar ao homem o que será depois dele debaixo do sol?

'''

xref:021-eclesiastes/021-eclesiastes-005.adoc#v21-5-0[&#60; Capítulo Anterior] | <<v21-6-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-007.adoc#v21-7-0[Próximo Capítulo &#62;]