include::./index.adoc[]

[[v21-10-0]]
=== Eclesiastes, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v21-10-1]]

^<<v21-10-1,1>>^ Qual a mosca morta faz o unguento do perfumador exalar mau cheiro, assim é para a sabedoria e a honra um pouco de estultícia.

[[v21-10-2]]

^<<v21-10-2,2>>^ O coração do sábio se inclina para o lado direito, mas o do estulto, para o da esquerda.

[[v21-10-3]]

^<<v21-10-3,3>>^ Quando o tolo vai pelo caminho, falta-lhe o entendimento; e, assim, a todos mostra que é estulto.

[[v21-10-4]]

^<<v21-10-4,4>>^ Levantando-se contra ti a indignação do governador, não deixes o teu lugar, porque o ânimo sereno acalma grandes ofensores.

[[v21-10-5]]

^<<v21-10-5,5>>^ Ainda há um mal que vi debaixo do sol, erro que procede do governador:

[[v21-10-6]]

^<<v21-10-6,6>>^ o tolo posto em grandes alturas, mas os ricos assentados em lugar baixo.

[[v21-10-7]]

^<<v21-10-7,7>>^ Vi servos a cavalo e príncipes andando a pé como servos sobre a terra.

[[v21-10-8]]

^<<v21-10-8,8>>^ Quem abre uma cova nela cairá, e quem rompe um muro, mordê-lo-á uma cobra.

[[v21-10-9]]

^<<v21-10-9,9>>^ Quem arranca pedras será maltratado por elas, e o que racha lenha expõe-se ao perigo.

[[v21-10-10]]

^<<v21-10-10,10>>^ Se o ferro está embotado, e não se lhe afia o corte, é preciso redobrar a força; mas a sabedoria resolve com bom êxito.

[[v21-10-11]]

^<<v21-10-11,11>>^ Se a cobra morder antes de estar encantada, não há vantagem no encantador.

[[v21-10-12]]

^<<v21-10-12,12>>^ Nas palavras do sábio há favor, mas ao tolo os seus lábios devoram.

[[v21-10-13]]

^<<v21-10-13,13>>^ As primeiras palavras da boca do tolo são estultícia, e as últimas, loucura perversa.

[[v21-10-14]]

^<<v21-10-14,14>>^ O estulto multiplica as palavras, ainda que o homem não sabe o que sucederá; e quem lhe manifestará o que será depois dele?

[[v21-10-15]]

^<<v21-10-15,15>>^ O trabalho do tolo o fatiga, pois nem sabe ir à cidade.

[[v21-10-16]]

^<<v21-10-16,16>>^ Ai de ti, ó terra cujo rei é criança e cujos príncipes se banqueteiam já de manhã.

[[v21-10-17]]

^<<v21-10-17,17>>^ Ditosa, tu, ó terra cujo rei é filho de nobres e cujos príncipes se sentam à mesa a seu tempo para refazerem as forças e não para bebedice.

[[v21-10-18]]

^<<v21-10-18,18>>^ Pela muita preguiça desaba o teto, e pela frouxidão das mãos goteja a casa.

[[v21-10-19]]

^<<v21-10-19,19>>^ O festim faz-se para rir, o vinho alegra a vida, e o dinheiro atende a tudo.

[[v21-10-20]]

^<<v21-10-20,20>>^ Nem no teu pensamento amaldiçoes o rei, nem tampouco no mais interior do teu quarto, o rico; porque as aves dos céus poderiam levar a tua voz, e o que tem asas daria notícia das tuas palavras.

'''

xref:021-eclesiastes/021-eclesiastes-009.adoc#v21-9-0[&#60; Capítulo Anterior] | <<v21-10-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-011.adoc#v21-11-0[Próximo Capítulo &#62;]