include::./index.adoc[]

[[v21-1-0]]
=== Eclesiastes, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v21-1-1]]

^<<v21-1-1,1>>^ Palavra do Pregador, filho de Davi, rei de Jerusalém:

[[v21-1-2]]

^<<v21-1-2,2>>^ Vaidade de vaidades, diz o Pregador; vaidade de vaidades, tudo é vaidade.

[[v21-1-3]]

^<<v21-1-3,3>>^ Que proveito tem o homem de todo o seu trabalho, com que se afadiga debaixo do sol?

[[v21-1-4]]

^<<v21-1-4,4>>^ Geração vai e geração vem; mas a terra permanece para sempre.

[[v21-1-5]]

^<<v21-1-5,5>>^ Levanta-se o sol, e põe-se o sol, e volta ao seu lugar, onde nasce de novo.

[[v21-1-6]]

^<<v21-1-6,6>>^ O vento vai para o sul e faz o seu giro para o norte; volve-se, e revolve-se, na sua carreira, e retorna aos seus circuitos.

[[v21-1-7]]

^<<v21-1-7,7>>^ Todos os rios correm para o mar, e o mar não se enche; ao lugar para onde correm os rios, para lá tornam eles a correr.

[[v21-1-8]]

^<<v21-1-8,8>>^ Todas as coisas são canseiras tais, que ninguém as pode exprimir; os olhos não se fartam de ver, nem se enchem os ouvidos de ouvir.

[[v21-1-9]]

^<<v21-1-9,9>>^ O que foi é o que há de ser; e o que se fez, isso se tornará a fazer; nada há, pois, novo debaixo do sol.

[[v21-1-10]]

^<<v21-1-10,10>>^ Há alguma coisa de que se possa dizer: Vê, isto é novo? Não! Já foi nos séculos que foram antes de nós.

[[v21-1-11]]

^<<v21-1-11,11>>^ Já não há lembrança das coisas que precederam; e das coisas posteriores também não haverá memória entre os que hão de vir depois delas.

[[v21-1-12]]

^<<v21-1-12,12>>^ Eu, o Pregador, venho sendo rei de Israel, em Jerusalém.

[[v21-1-13]]

^<<v21-1-13,13>>^ Apliquei o coração a esquadrinhar e a informar-me com sabedoria de tudo quanto sucede debaixo do céu; este enfadonho trabalho impôs Deus aos filhos dos homens, para nele os afligir.

[[v21-1-14]]

^<<v21-1-14,14>>^ Atentei para todas as obras que se fazem debaixo do sol, e eis que tudo era vaidade e correr atrás do vento.

[[v21-1-15]]

^<<v21-1-15,15>>^ Aquilo que é torto não se pode endireitar; e o que falta não se pode calcular.

[[v21-1-16]]

^<<v21-1-16,16>>^ Disse comigo: eis que me engrandeci e sobrepujei em sabedoria a todos os que antes de mim existiram em Jerusalém; com efeito, o meu coração tem tido larga experiência da sabedoria e do conhecimento.

[[v21-1-17]]

^<<v21-1-17,17>>^ Apliquei o coração a conhecer a sabedoria e a saber o que é loucura e o que é estultícia; e vim a saber que também isto é correr atrás do vento.

[[v21-1-18]]

^<<v21-1-18,18>>^ Porque na muita sabedoria há muito enfado; e quem aumenta ciência aumenta tristeza.

'''

xref:020-proverbios/020-proverbios-031.adoc#v20-31-0[&#60; Capítulo Anterior] | <<v21-1-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-002.adoc#v21-2-0[Próximo Capítulo &#62;]