include::./index.adoc[]

[[v6-18-0]]
=== Josué, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v6-18-1]]

^<<v6-18-1,1>>^ Reuniu-se toda a congregação dos filhos de Israel em Siló, e ali armaram a tenda da congregação; e a terra estava sujeita diante deles.

[[v6-18-2]]

^<<v6-18-2,2>>^ Dentre os filhos de Israel ficaram sete tribos que ainda não tinham repartido a sua herança.

[[v6-18-3]]

^<<v6-18-3,3>>^ Disse Josué aos filhos de Israel: Até quando sereis remissos em passardes para possuir a terra que o SENHOR, Deus de vossos pais, vos deu?

[[v6-18-4]]

^<<v6-18-4,4>>^ De cada tribo escolhei três homens, para que eu os envie, eles se disponham, e corram a terra, e façam dela um gráfico relativamente à herança das tribos, e se tornem a mim.

[[v6-18-5]]

^<<v6-18-5,5>>^ Dividirão a terra em sete partes: Judá ficará no seu território, ao sul, e a casa de José, no seu, ao norte.

[[v6-18-6]]

^<<v6-18-6,6>>^ Em sete partes fareis o gráfico da terra e mo trareis a mim, para que eu aqui vos lance as sortes perante o SENHOR, nosso Deus.

[[v6-18-7]]

^<<v6-18-7,7>>^ Porquanto os levitas não têm parte entre vós, pois o sacerdócio do SENHOR é a sua parte. Gade, e Rúben, e a meia tribo de Manassés já haviam recebido a sua herança dalém do Jordão, para o oriente, a qual lhes deu Moisés, servo do SENHOR.

[[v6-18-8]]

^<<v6-18-8,8>>^ Dispuseram-se, pois, aqueles homens e se foram, e Josué deu ordem aos que iam levantar o gráfico da terra, dizendo: Ide, correi a terra, levantai-lhe o gráfico e tornai a mim; aqui vos lançarei as sortes perante o SENHOR, em Siló.

[[v6-18-9]]

^<<v6-18-9,9>>^ Foram, pois, os homens, passaram pela terra, levantaram dela o gráfico, cidade por cidade, em sete partes, num livro, e voltaram a Josué, ao arraial em Siló.

[[v6-18-10]]

^<<v6-18-10,10>>^ Então, Josué lhes lançou as sortes em Siló, perante o SENHOR; e ali repartiu Josué a terra, segundo as suas divisões, aos filhos de Israel.

[[v6-18-11]]

^<<v6-18-11,11>>^ Saiu a sorte da tribo dos filhos de Benjamim, segundo as suas famílias; e o território da sua sorte caiu entre os filhos de Judá e os filhos de José.

[[v6-18-12]]

^<<v6-18-12,12>>^ O seu limite foi para o lado norte desde o Jordão; subia ao lado de Jericó, para o norte, e subia pela montanha, para o ocidente, para terminar no deserto de Bete-Áven.

[[v6-18-13]]

^<<v6-18-13,13>>^ E dali passava o limite a Luz, ao lado de Luz (que é Betel), para o sul; descia a Atarote-Adar, ao pé do monte que está do lado sul de Bete-Horom de baixo.

[[v6-18-14]]

^<<v6-18-14,14>>^ Seguia o limite, e tornava ao lado ocidental, para o sul do monte que está defronte de Bete-Horom, para o sul, e terminava em Quiriate-Baal (que é Quiriate-Jearim), cidade dos filhos de Judá; este era o lado ocidental.

[[v6-18-15]]

^<<v6-18-15,15>>^ O lado do sul começava na extremidade oriental de Quiriate-Jearim e seguia até à fonte das águas de Neftoa;

[[v6-18-16]]

^<<v6-18-16,16>>^ descia o limite até à extremidade do monte que está defronte do vale do Filho de Hinom, ao norte do vale dos Refains, e descia pelo vale de Hinom do lado dos jebuseus, para o sul; e baixava a En-Rogel;

[[v6-18-17]]

^<<v6-18-17,17>>^ volvia-se para o norte, chegava a En-Semes, de onde passava para Gelilote, que está defronte da subida de Adumim, e descia à pedra de Boã, filho de Rúben;

[[v6-18-18]]

^<<v6-18-18,18>>^ passava pela vertente norte, defronte da planície, e descia à planície.

[[v6-18-19]]

^<<v6-18-19,19>>^ Depois, passava o limite até ao lado de Bete-Hogla, para o norte, para terminar na baía do mar Salgado, na desembocadura do Jordão, ao sul; este era o limite do sul.

[[v6-18-20]]

^<<v6-18-20,20>>^ Do lado oriental, o Jordão era o seu limite; esta era a herança dos filhos de Benjamim nos seus limites em redor, segundo as suas famílias.

[[v6-18-21]]

^<<v6-18-21,21>>^ As cidades da tribo dos filhos de Benjamim, segundo as suas famílias, eram: Jericó, Bete-Hogla, Emeque-Quesis,

[[v6-18-22]]

^<<v6-18-22,22>>^ Bete-Arabá, Zemaraim, Betel,

[[v6-18-23]]

^<<v6-18-23,23>>^ Avim, Pará, Ofra,

[[v6-18-24]]

^<<v6-18-24,24>>^ Quefar-Amonai, Ofni e Gaba; ao todo, doze cidades com suas aldeias.

[[v6-18-25]]

^<<v6-18-25,25>>^ Gibeão, Ramá, Beerote,

[[v6-18-26]]

^<<v6-18-26,26>>^ Mispa, Cefira, Mosa,

[[v6-18-27]]

^<<v6-18-27,27>>^ Requém, Irpeel, Tarala,

[[v6-18-28]]

^<<v6-18-28,28>>^ Zela, Elefe, Jebus (esta é Jerusalém), Gibeá e Quiriate; ao todo, catorze cidades com suas aldeias; esta era a herança dos filhos de Benjamim, segundo as suas famílias.

'''

xref:006-josue/006-josue-017.adoc#v6-17-0[&#60; Capítulo Anterior] | <<v6-18-0,Topo>> | xref:006-josue/006-josue-019.adoc#v6-19-0[Próximo Capítulo &#62;]