include::./index.adoc[]

[[v6-17-0]]
=== Josué, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v6-17-1]]

^<<v6-17-1,1>>^ Também caiu a sorte à tribo de Manassés, o qual era o primogênito de José. Maquir, o primogênito de Manassés, pai de Gileade, porquanto era homem de guerra, teve Gileade e Basã.

[[v6-17-2]]

^<<v6-17-2,2>>^ Os mais filhos de Manassés também tiveram a sua parte, segundo as suas famílias, a saber, os filhos de Abiezer, e os filhos de Heleque, e os filhos de Asriel, e os filhos de Siquém, e os filhos de Héfer, e os filhos de Semida; são estes os filhos de Manassés, filho de José, segundo as suas famílias.

[[v6-17-3]]

^<<v6-17-3,3>>^ Zelofeade, porém, filho de Héfer, filho de Gileade, filho de Maquir, filho de Manassés, não teve filhos, mas só filhas, cujos nomes são estes: Macla, Noa, Hogla, Milca e Tirza.

[[v6-17-4]]

^<<v6-17-4,4>>^ Estas chegaram diante de Eleazar, o sacerdote, e diante de Josué, filho de Num, e diante dos príncipes, dizendo: O SENHOR ordenou a Moisés que se nos desse herança no meio de nossos irmãos. Pelo que, segundo o dito do SENHOR, Josué lhes deu herança no meio dos irmãos de seu pai.

[[v6-17-5]]

^<<v6-17-5,5>>^ Couberam a Manassés dez quinhões, afora a terra de Gileade e Basã, que está dalém do Jordão;

[[v6-17-6]]

^<<v6-17-6,6>>^ porque as filhas de Manassés, no meio de seus filhos, possuíram herança; os outros filhos de Manassés tiveram a terra de Gileade.

[[v6-17-7]]

^<<v6-17-7,7>>^ O limite de Manassés foi desde Aser até Micmetate, que está a leste de Siquém; e vai este limite, rumo sul, até aos moradores de En-Tapua.

[[v6-17-8]]

^<<v6-17-8,8>>^ Tinha Manassés a terra de Tapua; porém Tapua, ainda que situada no limite de Manassés, era dos filhos de Efraim.

[[v6-17-9]]

^<<v6-17-9,9>>^ Então, desce o limite ao ribeiro de Caná. As cidades, entre as de Manassés, ao sul do ribeiro, pertenciam a Efraim; então, o limite de Manassés vai ao norte do ribeiro, terminando no mar.

[[v6-17-10]]

^<<v6-17-10,10>>^ Efraim, ao sul, Manassés, ao norte, e o mar é seu limite; pelo norte, tocam em Aser e, pelo oriente, em Issacar.

[[v6-17-11]]

^<<v6-17-11,11>>^ Porque, em Issacar e em Aser, tinha Manassés a Bete-Seã e suas vilas, Ibleão e suas vilas, os habitantes de Dor e suas vilas, os habitantes de En-Dor e suas vilas, os habitantes de Taanaque e suas vilas e os habitantes de Megido e suas vilas, a região dos três outeiros.

[[v6-17-12]]

^<<v6-17-12,12>>^ E os filhos de Manassés não puderam expulsar os habitantes daquelas cidades, porquanto os cananeus persistiam em habitar nessa terra.

[[v6-17-13]]

^<<v6-17-13,13>>^ Sucedeu que, tornando-se fortes os filhos de Israel, sujeitaram aos cananeus a trabalhos forçados, porém não os expulsaram de todo.

[[v6-17-14]]

^<<v6-17-14,14>>^ Então, o povo dos filhos de José disse a Josué: Por que me deste por herança uma sorte apenas e um quinhão, sendo eu tão grande povo, visto que o SENHOR até aqui me tem abençoado?

[[v6-17-15]]

^<<v6-17-15,15>>^ Disse-lhe Josué: Se és grande povo, sobe ao bosque e abre ali clareira na terra dos ferezeus e dos refains, visto que a região montanhosa de Efraim te é estreita demais.

[[v6-17-16]]

^<<v6-17-16,16>>^ Então, disseram os filhos de José: A região montanhosa não nos basta; e todos os cananeus que habitam na terra do vale têm carros de ferro, tanto os que estão em Bete-Seã e suas vilas como os que estão no vale de Jezreel.

[[v6-17-17]]

^<<v6-17-17,17>>^ Falou Josué à casa de José, a Efraim e a Manassés, dizendo: Tu és povo numeroso e forte; não terás uma sorte apenas;

[[v6-17-18]]

^<<v6-17-18,18>>^ porém a região montanhosa será tua. Ainda que é bosque, cortá-lo-ás, e até às suas extremidades será todo teu; porque expulsarás os cananeus, ainda que possuem carros de ferro e são fortes.

'''

xref:006-josue/006-josue-016.adoc#v6-16-0[&#60; Capítulo Anterior] | <<v6-17-0,Topo>> | xref:006-josue/006-josue-018.adoc#v6-18-0[Próximo Capítulo &#62;]