include::./index.adoc[]

[[v6-14-0]]
=== Josué, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v6-14-1]]

^<<v6-14-1,1>>^ São estas as heranças que os filhos de Israel tiveram na terra de Canaã, o que Eleazar, o sacerdote, e Josué, filho de Num, e os cabeças dos pais das tribos dos filhos de Israel lhes fizeram repartir

[[v6-14-2]]

^<<v6-14-2,2>>^ por sorte da sua herança, como o SENHOR ordenara por intermédio de Moisés, acerca das nove tribos e meia.

[[v6-14-3]]

^<<v6-14-3,3>>^ Porquanto às duas tribos e meia já dera Moisés herança além do Jordão; mas aos levitas não tinha dado herança entre seus irmãos.

[[v6-14-4]]

^<<v6-14-4,4>>^ Os filhos de José foram duas tribos, Manassés e Efraim; aos levitas não deram herança na terra, senão cidades em que habitassem e os seus arredores para seu gado e para sua possessão.

[[v6-14-5]]

^<<v6-14-5,5>>^ Como o SENHOR ordenara a Moisés, assim fizeram os filhos de Israel e repartiram a terra.

[[v6-14-6]]

^<<v6-14-6,6>>^ Chegaram os filhos de Judá a Josué em Gilgal; e Calebe, filho de Jefoné, o quenezeu, lhe disse: Tu sabes o que o SENHOR falou a Moisés, homem de Deus, em Cades-Barneia, a respeito de mim e de ti.

[[v6-14-7]]

^<<v6-14-7,7>>^ Tinha eu quarenta anos quando Moisés, servo do SENHOR, me enviou de Cades-Barneia para espiar a terra; e eu lhe relatei como sentia no coração.

[[v6-14-8]]

^<<v6-14-8,8>>^ Mas meus irmãos que subiram comigo desesperaram o povo; eu, porém, perseverei em seguir o SENHOR, meu Deus.

[[v6-14-9]]

^<<v6-14-9,9>>^ Então, Moisés, naquele dia, jurou, dizendo: Certamente, a terra em que puseste o pé será tua e de teus filhos, em herança perpetuamente, pois perseveraste em seguir o SENHOR, meu Deus.

[[v6-14-10]]

^<<v6-14-10,10>>^ Eis, agora, o SENHOR me conservou em vida, como prometeu; quarenta e cinco anos há desde que o SENHOR falou esta palavra a Moisés, andando Israel ainda no deserto; e, já agora, sou de oitenta e cinco anos.

[[v6-14-11]]

^<<v6-14-11,11>>^ Estou forte ainda hoje como no dia em que Moisés me enviou; qual era a minha força naquele dia, tal ainda agora para o combate, tanto para sair a ele como para voltar.

[[v6-14-12]]

^<<v6-14-12,12>>^ Agora, pois, dá-me este monte de que o SENHOR falou naquele dia, pois, naquele dia, ouviste que lá estavam os anaquins e grandes e fortes cidades; o SENHOR, porventura, será comigo, para os desapossar, como prometeu.

[[v6-14-13]]

^<<v6-14-13,13>>^ Josué o abençoou e deu a Calebe, filho de Jefoné, Hebrom em herança.

[[v6-14-14]]

^<<v6-14-14,14>>^ Portanto, Hebrom passou a ser de Calebe, filho de Jefoné, o quenezeu, em herança até ao dia de hoje, visto que perseverara em seguir o SENHOR, Deus de Israel.

[[v6-14-15]]

^<<v6-14-15,15>>^ Dantes o nome de Hebrom era Quiriate-Arba; este Arba foi o maior homem entre os anaquins. E a terra repousou da guerra.

'''

xref:006-josue/006-josue-013.adoc#v6-13-0[&#60; Capítulo Anterior] | <<v6-14-0,Topo>> | xref:006-josue/006-josue-015.adoc#v6-15-0[Próximo Capítulo &#62;]