include::./index.adoc[]

[[v6-5-0]]
=== Josué, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v6-5-1]]

^<<v6-5-1,1>>^ Sucedeu que, ouvindo todos os reis dos amorreus que habitavam deste lado do Jordão, ao ocidente, e todos os reis dos cananeus que estavam ao pé do mar que o SENHOR tinha secado as águas do Jordão, de diante dos filhos de Israel, até que passamos, desmaiou-se-lhes o coração, e não houve mais alento neles, por causa dos filhos de Israel.

[[v6-5-2]]

^<<v6-5-2,2>>^ Naquele tempo, disse o SENHOR a Josué: Faze facas de pederneira e passa, de novo, a circuncidar os filhos de Israel.

[[v6-5-3]]

^<<v6-5-3,3>>^ Então, Josué fez para si facas de pederneira e circuncidou os filhos de Israel em Gibeate-Haralote.

[[v6-5-4]]

^<<v6-5-4,4>>^ Foi esta a razão por que Josué os circuncidou: todo o povo que tinha saído do Egito, os homens, todos os homens de guerra, eram já mortos no deserto, pelo caminho.

[[v6-5-5]]

^<<v6-5-5,5>>^ Porque todo o povo que saíra estava circuncidado, mas a nem um deles que nascera no deserto, pelo caminho, depois de terem saído do Egito, haviam circuncidado.

[[v6-5-6]]

^<<v6-5-6,6>>^ Porque quarenta anos andaram os filhos de Israel pelo deserto, até se acabar toda a gente dos homens de guerra que saíram do Egito, que não obedeceram à voz do SENHOR, aos quais o SENHOR tinha jurado que lhes não havia de deixar ver a terra que o SENHOR, sob juramento, prometeu dar a seus pais, terra que mana leite e mel.

[[v6-5-7]]

^<<v6-5-7,7>>^ Porém em seu lugar pôs a seus filhos; a estes Josué circuncidou, porquanto estavam incircuncisos, porque os não circuncidaram no caminho.

[[v6-5-8]]

^<<v6-5-8,8>>^ Tendo sido circuncidada toda a nação, ficaram no seu lugar no arraial, até que sararam.

[[v6-5-9]]

^<<v6-5-9,9>>^ Disse mais o SENHOR a Josué: Hoje, removi de vós o opróbrio do Egito; pelo que o nome daquele lugar se chamou Gilgal até o dia de hoje.

[[v6-5-10]]

^<<v6-5-10,10>>^ Estando, pois, os filhos de Israel acampados em Gilgal, celebraram a Páscoa no dia catorze do mês, à tarde, nas campinas de Jericó.

[[v6-5-11]]

^<<v6-5-11,11>>^ Comeram do fruto da terra, no dia seguinte à Páscoa; pães asmos e cereais tostados comeram nesse mesmo dia.

[[v6-5-12]]

^<<v6-5-12,12>>^ No dia imediato, depois que comeram do produto da terra, cessou o maná, e não o tiveram mais os filhos de Israel; mas, naquele ano, comeram das novidades da terra de Canaã.

[[v6-5-13]]

^<<v6-5-13,13>>^ Estando Josué ao pé de Jericó, levantou os olhos e olhou; eis que se achava em pé diante dele um homem que trazia na mão uma espada nua; chegou-se Josué a ele e disse-lhe: És tu dos nossos ou dos nossos adversários?

[[v6-5-14]]

^<<v6-5-14,14>>^ Respondeu ele: Não; sou príncipe do exército do SENHOR e acabo de chegar. Então, Josué se prostrou com o rosto em terra, e o adorou, e disse-lhe: Que diz meu senhor ao seu servo?

[[v6-5-15]]

^<<v6-5-15,15>>^ Respondeu o príncipe do exército do SENHOR a Josué: Descalça as sandálias dos pés, porque o lugar em que estás é santo. E fez Josué assim.

'''

xref:006-josue/006-josue-004.adoc#v6-4-0[&#60; Capítulo Anterior] | <<v6-5-0,Topo>> | xref:006-josue/006-josue-006.adoc#v6-6-0[Próximo Capítulo &#62;]