include::./index.adoc[]

[[v6-8-0]]
=== Josué, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v6-8-1]]

^<<v6-8-1,1>>^ Disse o SENHOR a Josué: Não temas, não te atemorizes; toma contigo toda a gente de guerra, e dispõe-te, e sobe a Ai; olha que entreguei nas tuas mãos o rei de Ai, e o seu povo, e a sua cidade, e a sua terra.

[[v6-8-2]]

^<<v6-8-2,2>>^ Farás a Ai e a seu rei como fizeste a Jericó e a seu rei; somente que para vós outros saqueareis os seus despojos e o seu gado; põe emboscadas à cidade, por detrás dela.

[[v6-8-3]]

^<<v6-8-3,3>>^ Então, Josué se levantou, e toda a gente de guerra, para subir contra Ai; escolheu Josué trinta mil homens valentes e os enviou de noite.

[[v6-8-4]]

^<<v6-8-4,4>>^ Deu-lhes ordem, dizendo: Eis que vos poreis de emboscada contra a cidade, por detrás dela; não vos distancieis muito da cidade; e todos estareis alertas.

[[v6-8-5]]

^<<v6-8-5,5>>^ Porém eu e todo o povo que está comigo nos aproximaremos da cidade; e será que, quando saírem, como dantes, contra nós, fugiremos diante deles.

[[v6-8-6]]

^<<v6-8-6,6>>^ Deixemo-los, pois, sair atrás de nós, até que os tiremos da cidade; porque dirão: Fogem diante de nós como dantes. Assim, fugiremos diante deles.

[[v6-8-7]]

^<<v6-8-7,7>>^ Então, saireis vós da emboscada e tomareis a cidade; porque o SENHOR, vosso Deus, vo-la entregará nas vossas mãos.

[[v6-8-8]]

^<<v6-8-8,8>>^ Havendo vós tomado a cidade, pôr-lhe-eis fogo; segundo a palavra do SENHOR, fareis; eis que vo-lo ordenei.

[[v6-8-9]]

^<<v6-8-9,9>>^ Assim, Josué os enviou, e eles se foram à emboscada; e ficaram entre Betel e Ai, ao ocidente de Ai; porém Josué passou aquela noite no meio do povo.

[[v6-8-10]]

^<<v6-8-10,10>>^ Levantou-se Josué de madrugada, passou revista ao povo, e subiram ele e os anciãos de Israel, diante do povo, contra Ai.

[[v6-8-11]]

^<<v6-8-11,11>>^ Subiram também todos os homens de guerra que estavam com ele, e chegaram-se, e vieram defronte da cidade; e alojaram-se do lado norte de Ai. Havia um vale entre eles e Ai.

[[v6-8-12]]

^<<v6-8-12,12>>^ Tomou também uns cinco mil homens e os pôs entre Betel e Ai, em emboscada, ao ocidente da cidade.

[[v6-8-13]]

^<<v6-8-13,13>>^ Assim foi posto o povo: todo o acampamento ao norte da cidade e a emboscada ao ocidente dela; e foi Josué aquela noite até ao meio do vale.

[[v6-8-14]]

^<<v6-8-14,14>>^ E sucedeu que, vendo-o o rei de Ai, ele e os homens da cidade apressaram-se e, levantando-se de madrugada, saíram de encontro a Israel, à batalha, defronte das campinas, porque ele não sabia achar-se contra ele uma emboscada atrás da cidade.

[[v6-8-15]]

^<<v6-8-15,15>>^ Josué, pois, e todo o Israel se houveram como feridos diante deles e fugiram pelo caminho do deserto.

[[v6-8-16]]

^<<v6-8-16,16>>^ Pelo que todo o povo que estava na cidade foi convocado para os perseguir; e perseguiram Josué e foram afastados da cidade.

[[v6-8-17]]

^<<v6-8-17,17>>^ Nem um só homem ficou em Ai, nem em Betel que não saísse após os israelitas; e deixaram a cidade aberta e perseguiram Israel.

[[v6-8-18]]

^<<v6-8-18,18>>^ Então, disse o SENHOR a Josué: Estende para Ai a lança que tens na mão; porque a esta darei na tua mão; e Josué estendeu para a cidade a lança que tinha na mão.

[[v6-8-19]]

^<<v6-8-19,19>>^ Então, a emboscada se levantou apressadamente do seu lugar, e, ao estender ele a mão, vieram à cidade e a tomaram; e apressaram-se e nela puseram fogo.

[[v6-8-20]]

^<<v6-8-20,20>>^ Virando-se os homens de Ai para trás, olharam, e eis que a fumaça da cidade subia ao céu, e não puderam fugir nem para um lado nem para outro; porque o povo que fugia para o deserto se tornou contra os que os perseguiam.

[[v6-8-21]]

^<<v6-8-21,21>>^ Vendo Josué e todo o Israel que a emboscada tomara a cidade e que a fumaça da cidade subia, voltaram e feriram os homens de Ai.

[[v6-8-22]]

^<<v6-8-22,22>>^ Da cidade saíram os outros ao encontro do inimigo, que, assim, ficou no meio de Israel, uns de uma parte, outros de outra; e feriram-nos de tal sorte, que nenhum deles sobreviveu, nem escapou.

[[v6-8-23]]

^<<v6-8-23,23>>^ Porém ao rei de Ai tomaram vivo e o trouxeram a Josué.

[[v6-8-24]]

^<<v6-8-24,24>>^ Tendo os israelitas acabado de matar todos os moradores de Ai no campo e no deserto onde os tinham perseguido, e havendo todos caído a fio de espada, e sendo já todos consumidos, todo o Israel voltou a Ai, e a passaram a fio de espada.

[[v6-8-25]]

^<<v6-8-25,25>>^ Os que caíram aquele dia, tanto homens como mulheres, foram doze mil, todos os moradores de Ai.

[[v6-8-26]]

^<<v6-8-26,26>>^ Porque Josué não retirou a mão que estendera com a lança até haver destruído totalmente os moradores de Ai.

[[v6-8-27]]

^<<v6-8-27,27>>^ Os israelitas saquearam, entretanto, para si o gado e os despojos daquela cidade, segundo a palavra do SENHOR, que ordenara a Josué.

[[v6-8-28]]

^<<v6-8-28,28>>^ Então, Josué pôs fogo a Ai e a reduziu, para sempre, a um montão, a ruínas até ao dia de hoje.

[[v6-8-29]]

^<<v6-8-29,29>>^ Ao rei de Ai, enforcou-o e o deixou no madeiro até à tarde; ao pôr do sol, por ordem de Josué, tiraram do madeiro o cadáver, e o lançaram à porta da cidade, e sobre ele levantaram um montão de pedras, que até hoje permanece.

[[v6-8-30]]

^<<v6-8-30,30>>^ Então, Josué edificou um altar ao SENHOR, Deus de Israel, no monte Ebal,

[[v6-8-31]]

^<<v6-8-31,31>>^ como Moisés, servo do SENHOR, ordenara aos filhos de Israel, segundo o que está escrito no Livro da Lei de Moisés, a saber, um altar de pedras toscas, sobre o qual se não manejara instrumento de ferro; sobre ele ofereceram holocaustos ao SENHOR e apresentaram ofertas pacíficas.

[[v6-8-32]]

^<<v6-8-32,32>>^ Escreveu, ali, em pedras, uma cópia da lei de Moisés, que já este havia escrito diante dos filhos de Israel.

[[v6-8-33]]

^<<v6-8-33,33>>^ Todo o Israel, com os seus anciãos, e os seus príncipes, e os seus juízes estavam de um e de outro lado da arca, perante os levitas sacerdotes que levavam a arca da Aliança do SENHOR, tanto estrangeiros como naturais; metade deles, em frente do monte Gerizim, e a outra metade, em frente do monte Ebal; como Moisés, servo do SENHOR, outrora, ordenara que fosse abençoado o povo de Israel.

[[v6-8-34]]

^<<v6-8-34,34>>^ Depois, leu todas as palavras da lei, a bênção e a maldição, segundo tudo o que está escrito no Livro da Lei.

[[v6-8-35]]

^<<v6-8-35,35>>^ Palavra nenhuma houve, de tudo o que Moisés ordenara, que Josué não lesse para toda a congregação de Israel, e para as mulheres, e os meninos, e os estrangeiros que andavam no meio deles.

'''

xref:006-josue/006-josue-007.adoc#v6-7-0[&#60; Capítulo Anterior] | <<v6-8-0,Topo>> | xref:006-josue/006-josue-009.adoc#v6-9-0[Próximo Capítulo &#62;]