include::./index.adoc[]

[[v6-22-0]]
=== Josué, 22
// ara ?, ARA - Almeida Revista e Atualizada

[[v6-22-1]]

^<<v6-22-1,1>>^ Então, Josué chamou os rubenitas, os gaditas e a meia tribo de Manassés

[[v6-22-2]]

^<<v6-22-2,2>>^ e lhes disse: Tendes guardado tudo quanto vos ordenou Moisés, servo do SENHOR, e também a mim me tendes obedecido em tudo quanto vos ordenei.

[[v6-22-3]]

^<<v6-22-3,3>>^ A vossos irmãos, durante longo tempo, até ao dia de hoje, não desamparastes; antes, tivestes o cuidado de guardar o mandamento do SENHOR, vosso Deus.

[[v6-22-4]]

^<<v6-22-4,4>>^ Tendo o SENHOR, vosso Deus, dado repouso a vossos irmãos, como lhes havia prometido, voltai-vos, pois, agora, e ide-vos para as vossas tendas, à terra da vossa possessão, que Moisés, servo do SENHOR, vos deu dalém do Jordão.

[[v6-22-5]]

^<<v6-22-5,5>>^ Tende cuidado, porém, de guardar com diligência o mandamento e a lei que Moisés, servo do SENHOR, vos ordenou: que ameis o SENHOR, vosso Deus, andeis em todos os seus caminhos, guardeis os seus mandamentos, e vos achegueis a ele, e o sirvais de todo o vosso coração e de toda a vossa alma.

[[v6-22-6]]

^<<v6-22-6,6>>^ Assim, Josué os abençoou e os despediu; e eles se foram para as suas tendas.

[[v6-22-7]]

^<<v6-22-7,7>>^ Ora, Moisés dera herança em Basã à meia tribo de Manassés; porém à outra metade deu Josué entre seus irmãos, daquém do Jordão, para o ocidente. E Josué, ao despedi-los para as suas tendas, os abençoou

[[v6-22-8]]

^<<v6-22-8,8>>^ e lhes disse: Voltais às vossas tendas com grandes riquezas, com muitíssimo gado, prata, ouro, bronze, ferro e muitíssima roupa; reparti com vossos irmãos o despojo dos vossos inimigos.

[[v6-22-9]]

^<<v6-22-9,9>>^ Assim, os filhos de Rúben, os filhos de Gade e a meia tribo de Manassés voltaram e se retiraram dos filhos de Israel em Siló, que está na terra de Canaã, para se irem à terra de Gileade, à terra da sua possessão, de que foram feitos possuidores, segundo o mandado do SENHOR, por intermédio de Moisés.

[[v6-22-10]]

^<<v6-22-10,10>>^ Vindo eles para os limites pegados ao Jordão, na terra de Canaã, ali os filhos de Rúben, os filhos de Gade e a meia tribo de Manassés edificaram um altar junto ao Jordão, altar grande e vistoso.

[[v6-22-11]]

^<<v6-22-11,11>>^ Os filhos de Israel ouviram dizer: Eis que os filhos de Rúben, os filhos de Gade e a meia tribo de Manassés edificaram um altar defronte da terra de Canaã, nos limites pegados ao Jordão, do lado dos filhos de Israel.

[[v6-22-12]]

^<<v6-22-12,12>>^ Ouvindo isto os filhos de Israel, ajuntou-se toda a congregação dos filhos de Israel em Siló, para saírem à peleja contra eles.

[[v6-22-13]]

^<<v6-22-13,13>>^ E aos filhos de Rúben, aos filhos de Gade e à meia tribo de Manassés enviaram os filhos de Israel, para a terra de Gileade, Fineias, filho de Eleazar, o sacerdote,

[[v6-22-14]]

^<<v6-22-14,14>>^ e dez príncipes com ele, de cada casa paterna um príncipe de todas as tribos de Israel; e cada um era cabeça da casa de seus pais entre os grupos de milhares de Israel.

[[v6-22-15]]

^<<v6-22-15,15>>^ Indo eles aos filhos de Rúben, aos filhos de Gade e à meia tribo de Manassés, à terra de Gileade, falaram-lhes, dizendo:

[[v6-22-16]]

^<<v6-22-16,16>>^ Assim diz toda a congregação do SENHOR: Que infidelidade é esta, que cometestes contra o Deus de Israel, deixando, hoje, de seguir o SENHOR, edificando-vos um altar, para vos rebelardes contra o SENHOR?

[[v6-22-17]]

^<<v6-22-17,17>>^ Acaso, não nos bastou a iniquidade de Peor, de que até hoje não estamos ainda purificados, posto que houve praga na congregação do SENHOR,

[[v6-22-18]]

^<<v6-22-18,18>>^ para que, hoje, abandoneis o SENHOR? Se, hoje, vos rebelais contra o SENHOR, amanhã, se irará contra toda a congregação de Israel.

[[v6-22-19]]

^<<v6-22-19,19>>^ Se a terra da vossa herança é imunda, passai-vos para a terra da possessão do SENHOR, onde habita o tabernáculo do SENHOR, e tomai possessão entre nós; não vos rebeleis, porém, contra o SENHOR, nem vos rebeleis contra nós, edificando-vos altar, afora o altar do SENHOR, nosso Deus.

[[v6-22-20]]

^<<v6-22-20,20>>^ Não cometeu Acã, filho de Zera, infidelidade no tocante às coisas condenadas? E não veio ira sobre toda a congregação de Israel? Pois aquele homem não morreu sozinho na sua iniquidade.

[[v6-22-21]]

^<<v6-22-21,21>>^ Então, responderam os filhos de Rúben, os filhos de Gade e a meia tribo de Manassés e disseram aos cabeças dos grupos de milhares de Israel:

[[v6-22-22]]

^<<v6-22-22,22>>^ O Poderoso, o Deus, o SENHOR, o Poderoso, o Deus, o SENHOR, ele o sabe, e Israel mesmo o saberá. Se foi em rebeldia ou por infidelidade contra o SENHOR, hoje, não nos preserveis.

[[v6-22-23]]

^<<v6-22-23,23>>^ Se edificamos altar para nos apartarmos do SENHOR, ou para, sobre ele, oferecermos holocausto e oferta de manjares, ou, sobre ele, fazermos oferta pacífica, o SENHOR mesmo de nós o demande.

[[v6-22-24]]

^<<v6-22-24,24>>^ Pelo contrário, fizemos por causa da seguinte preocupação: amanhã vossos filhos talvez dirão a nossos filhos: Que tendes vós com o SENHOR, Deus de Israel?

[[v6-22-25]]

^<<v6-22-25,25>>^ Pois o SENHOR pôs o Jordão por limite entre nós e vós, ó filhos de Rúben e filhos de Gade; não tendes parte no SENHOR; e, assim, bem poderiam os vossos filhos apartar os nossos do temor do SENHOR.

[[v6-22-26]]

^<<v6-22-26,26>>^ Pelo que dissemos: preparemo-nos, edifiquemos um altar, não para holocausto, nem para sacrifício,

[[v6-22-27]]

^<<v6-22-27,27>>^ mas, para que entre nós e vós e entre as nossas gerações depois de nós, nos seja testemunho, e possamos servir ao SENHOR diante dele com os nossos holocaustos, e os nossos sacrifícios, e as nossas ofertas pacíficas; e para que vossos filhos não digam amanhã a nossos filhos: Não tendes parte no SENHOR.

[[v6-22-28]]

^<<v6-22-28,28>>^ Pelo que dissemos: quando suceder que, amanhã, assim nos digam a nós e às nossas gerações, então, responderemos: vede o modelo do altar do SENHOR que fizeram nossos pais, não para holocausto, nem para sacrifício, mas para testemunho entre nós e vós.

[[v6-22-29]]

^<<v6-22-29,29>>^ Longe de nós o rebelarmo-nos contra o SENHOR e deixarmos, hoje, de seguir o SENHOR, edificando altar para holocausto, oferta de manjares ou sacrifício, afora o altar do SENHOR, nosso Deus, que está perante o seu tabernáculo.

[[v6-22-30]]

^<<v6-22-30,30>>^ Ouvindo, pois, Fineias, o sacerdote, e os príncipes da congregação, e os cabeças dos grupos de milhares de Israel que com ele estavam as palavras que disseram os filhos de Rúben, os filhos de Gade e os filhos de Manassés, deram-se por satisfeitos.

[[v6-22-31]]

^<<v6-22-31,31>>^ E disse Fineias, filho de Eleazar, o sacerdote, aos filhos de Rúben, aos filhos de Gade e aos filhos de Manassés: Hoje, sabemos que o SENHOR está no meio de nós, porquanto não cometestes infidelidade contra o SENHOR; agora, livrastes os filhos de Israel da mão do SENHOR.

[[v6-22-32]]

^<<v6-22-32,32>>^ Fineias, filho do sacerdote Eleazar, e os príncipes, deixando os filhos de Rúben e os filhos de Gade, voltaram da terra de Gileade para a terra de Canaã, aos filhos de Israel, e deram-lhes conta de tudo.

[[v6-22-33]]

^<<v6-22-33,33>>^ Com esta resposta deram-se por satisfeitos os filhos de Israel, os quais bendisseram a Deus; e não falaram mais de subir a pelejar contra eles, para destruírem a terra em que habitavam os filhos de Rúben e os filhos de Gade.

[[v6-22-34]]

^<<v6-22-34,34>>^ Os filhos de Rúben e os filhos de Gade chamaram o altar de Testemunho, porque disseram: É um testemunho entre nós de que o SENHOR é Deus.

'''

xref:006-josue/006-josue-021.adoc#v6-21-0[&#60; Capítulo Anterior] | <<v6-22-0,Topo>> | xref:006-josue/006-josue-023.adoc#v6-23-0[Próximo Capítulo &#62;]