include::./index.adoc[]

[[v6-2-0]]
=== Josué, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v6-2-1]]

^<<v6-2-1,1>>^ De Sitim enviou Josué, filho de Num, dois homens, secretamente, como espias, dizendo: Andai e observai a terra e Jericó. Foram, pois, e entraram na casa de uma mulher prostituta, cujo nome era Raabe, e pousaram ali.

[[v6-2-2]]

^<<v6-2-2,2>>^ Então, se deu notícia ao rei de Jericó, dizendo: Eis que, esta noite, vieram aqui uns homens dos filhos de Israel para espiar a terra.

[[v6-2-3]]

^<<v6-2-3,3>>^ Mandou, pois, o rei de Jericó dizer a Raabe: Faze sair os homens que vieram a ti e entraram na tua casa, porque vieram espiar toda a terra.

[[v6-2-4]]

^<<v6-2-4,4>>^ A mulher, porém, havia tomado e escondido os dois homens; e disse: É verdade que os dois homens vieram a mim, porém eu não sabia donde eram.

[[v6-2-5]]

^<<v6-2-5,5>>^ Havendo-se de fechar a porta, sendo já escuro, eles saíram; não sei para onde foram; ide após eles depressa, porque os alcançareis.

[[v6-2-6]]

^<<v6-2-6,6>>^ Ela, porém, os fizera subir ao eirado e os escondera entre as canas do linho que havia disposto em ordem no eirado.

[[v6-2-7]]

^<<v6-2-7,7>>^ Foram-se aqueles homens após os espias pelo caminho que dá aos vaus do Jordão; e, havendo saído os que iam após eles, fechou-se a porta.

[[v6-2-8]]

^<<v6-2-8,8>>^ Antes que os espias se deitassem, foi ela ter com eles ao eirado

[[v6-2-9]]

^<<v6-2-9,9>>^ e lhes disse: Bem sei que o SENHOR vos deu esta terra, e que o pavor que infundis caiu sobre nós, e que todos os moradores da terra estão desmaiados.

[[v6-2-10]]

^<<v6-2-10,10>>^ Porque temos ouvido que o SENHOR secou as águas do mar Vermelho diante de vós, quando saíeis do Egito; e também o que fizestes aos dois reis dos amorreus, Seom e Ogue, que estavam além do Jordão, os quais destruístes.

[[v6-2-11]]

^<<v6-2-11,11>>^ Ouvindo isto, desmaiou-nos o coração, e em ninguém mais há ânimo algum, por causa da vossa presença; porque o SENHOR, vosso Deus, é Deus em cima nos céus e embaixo na terra.

[[v6-2-12]]

^<<v6-2-12,12>>^ Agora, pois, jurai-me, vos peço, pelo SENHOR que, assim como usei de misericórdia para convosco, também dela usareis para com a casa de meu pai; e que me dareis um sinal certo

[[v6-2-13]]

^<<v6-2-13,13>>^ de que conservareis a vida a meu pai e a minha mãe, como também a meus irmãos e a minhas irmãs, com tudo o que têm, e de que livrareis a nossa vida da morte.

[[v6-2-14]]

^<<v6-2-14,14>>^ Então, lhe disseram os homens: A nossa vida responderá pela vossa se não denunciardes esta nossa missão; e será, pois, que, dando-nos o SENHOR esta terra, usaremos contigo de misericórdia e de fidelidade.

[[v6-2-15]]

^<<v6-2-15,15>>^ Ela, então, os fez descer por uma corda pela janela, porque a casa em que residia estava sobre o muro da cidade.

[[v6-2-16]]

^<<v6-2-16,16>>^ E disse-lhes: Ide-vos ao monte, para que, porventura, vos não encontrem os perseguidores; escondei-vos lá três dias, até que eles voltem; e, depois, tomareis o vosso caminho.

[[v6-2-17]]

^<<v6-2-17,17>>^ Disseram-lhe os homens: Desobrigados seremos deste teu juramento que nos fizeste jurar,

[[v6-2-18]]

^<<v6-2-18,18>>^ se, vindo nós à terra, não atares este cordão de fio de escarlata à janela por onde nos fizeste descer; e se não recolheres em casa contigo teu pai, e tua mãe, e teus irmãos, e a toda a família de teu pai.

[[v6-2-19]]

^<<v6-2-19,19>>^ Qualquer que sair para fora da porta da tua casa, o seu sangue lhe cairá sobre a cabeça, e nós seremos inocentes; mas o sangue de qualquer que estiver contigo em casa caia sobre a nossa cabeça, se alguém nele puser mão.

[[v6-2-20]]

^<<v6-2-20,20>>^ Também, se tu denunciares esta nossa missão, seremos desobrigados do juramento que nos fizeste jurar.

[[v6-2-21]]

^<<v6-2-21,21>>^ E ela disse: Segundo as vossas palavras, assim seja. Então, os despediu; e eles se foram; e ela atou o cordão de escarlata à janela.

[[v6-2-22]]

^<<v6-2-22,22>>^ Foram-se, pois, e chegaram ao monte, e ali ficaram três dias, até que voltaram os perseguidores; porque os perseguidores os procuraram por todo o caminho, porém não os acharam.

[[v6-2-23]]

^<<v6-2-23,23>>^ Assim, os dois homens voltaram, e desceram do monte, e passaram, e vieram a Josué, filho de Num, e lhe contaram tudo quanto lhes acontecera;

[[v6-2-24]]

^<<v6-2-24,24>>^ e disseram a Josué: Certamente, o SENHOR nos deu toda esta terra nas nossas mãos, e todos os seus moradores estão desmaiados diante de nós.

'''

xref:006-josue/006-josue-001.adoc#v6-1-0[&#60; Capítulo Anterior] | <<v6-2-0,Topo>> | xref:006-josue/006-josue-003.adoc#v6-3-0[Próximo Capítulo &#62;]