include::./index.adoc[]

[[v6-20-0]]
=== Josué, 20
// ara ?, ARA - Almeida Revista e Atualizada

[[v6-20-1]]

^<<v6-20-1,1>>^ Disse mais o SENHOR a Josué:

[[v6-20-2]]

^<<v6-20-2,2>>^ Fala aos filhos de Israel: Apartai para vós outros as cidades de refúgio de que vos falei por intermédio de Moisés;

[[v6-20-3]]

^<<v6-20-3,3>>^ para que fuja para ali o homicida que, por engano, matar alguma pessoa sem o querer; para que vos sirvam de refúgio contra o vingador do sangue.

[[v6-20-4]]

^<<v6-20-4,4>>^ E, fugindo para alguma dessas cidades, pôr-se-á à porta dela e exporá o seu caso perante os ouvidos dos anciãos da tal cidade; então, o tomarão consigo na cidade e lhe darão lugar, para que habite com eles.

[[v6-20-5]]

^<<v6-20-5,5>>^ Se o vingador do sangue o perseguir, não lhe entregarão nas mãos o homicida, porquanto feriu a seu próximo sem querer e não o aborrecia dantes.

[[v6-20-6]]

^<<v6-20-6,6>>^ Habitará, pois, na mesma cidade até que compareça em juízo perante a congregação, até que morra o sumo sacerdote que for naqueles dias; então, tornará o homicida e voltará à sua cidade e à sua casa, à cidade de onde fugiu.

[[v6-20-7]]

^<<v6-20-7,7>>^ Designaram, pois, solenemente, Quedes, na Galileia, na região montanhosa de Naftali, e Siquém, na região montanhosa de Efraim, e Quiriate-Arba, ou seja, Hebrom, na região montanhosa de Judá.

[[v6-20-8]]

^<<v6-20-8,8>>^ Dalém do Jordão, na altura de Jericó, para o oriente, designaram Bezer, no deserto, no planalto da tribo de Rúben; e Ramote, em Gileade, da tribo de Gade; e Golã, em Basã, da tribo de Manassés.

[[v6-20-9]]

^<<v6-20-9,9>>^ São estas as cidades que foram designadas para todos os filhos de Israel e para o estrangeiro que habitava entre eles; para que se refugiasse nelas todo aquele que, por engano, matasse alguma pessoa, para que não morresse às mãos do vingador do sangue, até comparecer perante a congregação.

'''

xref:006-josue/006-josue-019.adoc#v6-19-0[&#60; Capítulo Anterior] | <<v6-20-0,Topo>> | xref:006-josue/006-josue-021.adoc#v6-21-0[Próximo Capítulo &#62;]