include::./index.adoc[]

[[v6-21-0]]
=== Josué, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v6-21-1]]

^<<v6-21-1,1>>^ Então, se chegaram os cabeças dos pais dos levitas a Eleazar, o sacerdote, e a Josué, filho de Num, e aos cabeças dos pais das tribos dos filhos de Israel;

[[v6-21-2]]

^<<v6-21-2,2>>^ e falaram-lhes em Siló, na terra de Canaã, dizendo: O SENHOR ordenou, por intermédio de Moisés, que se nos dessem cidades para habitar e os seus arredores para os nossos animais.

[[v6-21-3]]

^<<v6-21-3,3>>^ E os filhos de Israel deram aos levitas, da sua herança, segundo o mandado do SENHOR, estas cidades e os seus arredores.

[[v6-21-4]]

^<<v6-21-4,4>>^ Caiu a sorte pelas famílias dos coatitas. Assim, os filhos de Arão, o sacerdote, que eram dos levitas, tiveram, por sorte, da tribo de Judá, da tribo de Simeão e da tribo de Benjamim treze cidades.

[[v6-21-5]]

^<<v6-21-5,5>>^ Os outros filhos de Coate tiveram, por sorte, das famílias da tribo de Efraim, da tribo de Dã e da meia tribo de Manassés dez cidades.

[[v6-21-6]]

^<<v6-21-6,6>>^ Os filhos de Gérson tiveram, por sorte, das famílias da tribo de Issacar, da tribo de Aser, da tribo de Naftali e da meia tribo de Manassés, em Basã, treze cidades.

[[v6-21-7]]

^<<v6-21-7,7>>^ Os filhos de Merari tiveram, por sorte, segundo as suas famílias, da tribo de Rúben, da tribo de Gade e da tribo de Zebulom doze cidades.

[[v6-21-8]]

^<<v6-21-8,8>>^ Deram os filhos de Israel aos levitas estas cidades e os seus arredores, por sorte, como o SENHOR ordenara por intermédio de Moisés.

[[v6-21-9]]

^<<v6-21-9,9>>^ Deram mais, da tribo dos filhos de Judá e da tribo dos filhos de Simeão, estas cidades que, nominalmente, foram designadas,

[[v6-21-10]]

^<<v6-21-10,10>>^ para que fossem dos filhos de Arão, das famílias dos coatitas, dos filhos de Levi, porquanto a primeira sorte foi deles.

[[v6-21-11]]

^<<v6-21-11,11>>^ Assim, lhes deram Quiriate-Arba (Arba era pai de Anaque), que é Hebrom, na região montanhosa de Judá, e, em torno dela, os seus arredores.

[[v6-21-12]]

^<<v6-21-12,12>>^ Porém o campo da cidade, com suas aldeias, deram a Calebe, filho de Jefoné, por sua possessão.

[[v6-21-13]]

^<<v6-21-13,13>>^ Assim, aos filhos de Arão, o sacerdote, deram Hebrom, cidade de refúgio do homicida, com seus arredores, Libna com seus arredores,

[[v6-21-14]]

^<<v6-21-14,14>>^ Jatir com seus arredores, Estemoa com seus arredores,

[[v6-21-15]]

^<<v6-21-15,15>>^ Holom com seus arredores, Debir com seus arredores,

[[v6-21-16]]

^<<v6-21-16,16>>^ Aim com seus arredores, Jutá com seus arredores e Bete-Semes com seus arredores; ao todo, nove cidades dessas duas tribos.

[[v6-21-17]]

^<<v6-21-17,17>>^ Da tribo de Benjamim, deram Gibeão com seus arredores, Gaba com seus arredores,

[[v6-21-18]]

^<<v6-21-18,18>>^ Anatote com seus arredores e Almom com seus arredores; ao todo, quatro cidades.

[[v6-21-19]]

^<<v6-21-19,19>>^ Total das cidades dos sacerdotes, filhos de Arão: treze cidades com seus arredores.

[[v6-21-20]]

^<<v6-21-20,20>>^ As mais famílias dos levitas de Coate tiveram as cidades da sua sorte da tribo de Efraim.

[[v6-21-21]]

^<<v6-21-21,21>>^ Deram-lhes Siquém, cidade de refúgio do homicida, com seus arredores, na região montanhosa de Efraim, Gezer com seus arredores,

[[v6-21-22]]

^<<v6-21-22,22>>^ Quibzaim com seus arredores e Bete-Horom com seus arredores; ao todo, quatro cidades.

[[v6-21-23]]

^<<v6-21-23,23>>^ Da tribo de Dã, deram Elteque com seus arredores, Gibetom com seus arredores,

[[v6-21-24]]

^<<v6-21-24,24>>^ Aijalom com seus arredores e Gate-Rimom com seus arredores; ao todo, quatro cidades.

[[v6-21-25]]

^<<v6-21-25,25>>^ Da meia tribo de Manassés, deram Taanaque com seus arredores e Gate-Rimom com seus arredores; ao todo, duas cidades.

[[v6-21-26]]

^<<v6-21-26,26>>^ Total: dez cidades com seus arredores, para as famílias dos demais filhos de Coate.

[[v6-21-27]]

^<<v6-21-27,27>>^ Aos filhos de Gérson, das famílias dos levitas, deram, em Basã, da tribo de Manassés, Golã, a cidade de refúgio para o homicida, com seus arredores, e Beesterá com seus arredores; ao todo, duas cidades.

[[v6-21-28]]

^<<v6-21-28,28>>^ Da tribo de Issacar, deram Quisião com seus arredores, Daberate com seus arredores,

[[v6-21-29]]

^<<v6-21-29,29>>^ Jarmute com seus arredores e En-Ganim com seus arredores; ao todo, quatro cidades.

[[v6-21-30]]

^<<v6-21-30,30>>^ Da tribo de Aser, deram Misal com seus arredores, Abdom com seus arredores,

[[v6-21-31]]

^<<v6-21-31,31>>^ Helcate com seus arredores e Reobe com seus arredores; ao todo, quatro cidades.

[[v6-21-32]]

^<<v6-21-32,32>>^ Da tribo de Naftali, deram, na Galileia, Quedes, cidade de refúgio para o homicida, com seus arredores, Hamote-Dor com seus arredores e Cartã com seus arredores; ao todo, três cidades.

[[v6-21-33]]

^<<v6-21-33,33>>^ Total das cidades dos gersonitas, segundo as suas famílias: treze cidades com seus arredores.

[[v6-21-34]]

^<<v6-21-34,34>>^ Às famílias dos demais levitas dos filhos de Merari deram, da tribo de Zebulom, Jocneão com seus arredores, Cartá com seus arredores,

[[v6-21-35]]

^<<v6-21-35,35>>^ Dimna com seus arredores e Naalal com seus arredores; ao todo, quatro cidades.

[[v6-21-36]]

^<<v6-21-36,36>>^ Da tribo de Rúben, deram Bezer com seus arredores, Jaza com seus arredores,

[[v6-21-37]]

^<<v6-21-37,37>>^ Quedemote com seus arredores e Mefaate com seus arredores; ao todo, quatro cidades.

[[v6-21-38]]

^<<v6-21-38,38>>^ Da tribo de Gade, deram, em Gileade, Ramote, cidade de refúgio para o homicida, com seus arredores, Maanaim com seus arredores,

[[v6-21-39]]

^<<v6-21-39,39>>^ Hesbom com seus arredores e Jazer com seus arredores; ao todo, quatro cidades.

[[v6-21-40]]

^<<v6-21-40,40>>^ Todas estas cidades tocaram por sorte aos filhos de Merari, segundo as suas famílias, que ainda restavam das famílias dos levitas: doze cidades.

[[v6-21-41]]

^<<v6-21-41,41>>^ As cidades, pois, dos levitas, no meio da herança dos filhos de Israel, foram, ao todo, quarenta e oito cidades com seus arredores;

[[v6-21-42]]

^<<v6-21-42,42>>^ cada uma das quais com seus arredores em torno de si; assim foi com todas estas cidades.

[[v6-21-43]]

^<<v6-21-43,43>>^ Desta maneira, deu o SENHOR a Israel toda a terra que jurara dar a seus pais; e a possuíram e habitaram nela.

[[v6-21-44]]

^<<v6-21-44,44>>^ O SENHOR lhes deu repouso em redor, segundo tudo quanto jurara a seus pais; nenhum de todos os seus inimigos resistiu diante deles; a todos eles o SENHOR lhes entregou nas mãos.

[[v6-21-45]]

^<<v6-21-45,45>>^ Nenhuma promessa falhou de todas as boas palavras que o SENHOR falara à casa de Israel; tudo se cumpriu.

'''

xref:006-josue/006-josue-020.adoc#v6-20-0[&#60; Capítulo Anterior] | <<v6-21-0,Topo>> | xref:006-josue/006-josue-022.adoc#v6-22-0[Próximo Capítulo &#62;]