include::./index.adoc[]

[[v6-24-0]]
=== Josué, 24
// ara ?, ARA - Almeida Revista e Atualizada

[[v6-24-1]]

^<<v6-24-1,1>>^ Depois, reuniu Josué todas as tribos de Israel em Siquém e chamou os anciãos de Israel, os seus cabeças, os seus juízes e os seus oficiais; e eles se apresentaram diante de Deus.

[[v6-24-2]]

^<<v6-24-2,2>>^ Então, Josué disse a todo o povo: Assim diz o SENHOR, Deus de Israel: Antigamente, vossos pais, Tera, pai de Abraão e de Naor, habitaram dalém do Eufrates e serviram a outros deuses.

[[v6-24-3]]

^<<v6-24-3,3>>^ Eu, porém, tomei Abraão, vosso pai, dalém do rio e o fiz percorrer toda a terra de Canaã; também lhe multipliquei a descendência e lhe dei Isaque.

[[v6-24-4]]

^<<v6-24-4,4>>^ A Isaque dei Jacó e Esaú e a Esaú dei em possessão as montanhas de Seir; porém Jacó e seus filhos desceram para o Egito.

[[v6-24-5]]

^<<v6-24-5,5>>^ Então, enviei Moisés e Arão e feri o Egito com o que fiz no meio dele; e, depois, vos tirei de lá.

[[v6-24-6]]

^<<v6-24-6,6>>^ Tirando eu vossos pais do Egito, viestes ao mar; os egípcios perseguiram vossos pais, com carros e com cavaleiros, até ao mar Vermelho.

[[v6-24-7]]

^<<v6-24-7,7>>^ E, clamando vossos pais, o SENHOR pôs escuridão entre vós e os egípcios, e trouxe o mar sobre estes, e o mar os cobriu; e os vossos olhos viram o que eu fiz no Egito. Então, habitastes no deserto por muito tempo.

[[v6-24-8]]

^<<v6-24-8,8>>^ Daí eu vos trouxe à terra dos amorreus, que habitavam dalém do Jordão, os quais pelejaram contra vós outros; porém os entreguei nas vossas mãos, e possuístes a sua terra; e os destruí diante de vós.

[[v6-24-9]]

^<<v6-24-9,9>>^ Levantou-se, também, o rei de Moabe, Balaque, filho de Zipor, e pelejou contra Israel; mandou chamar Balaão, filho de Beor, para que vos amaldiçoasse.

[[v6-24-10]]

^<<v6-24-10,10>>^ Porém eu não quis ouvir Balaão; e ele teve de vos abençoar; e, assim, vos livrei da sua mão.

[[v6-24-11]]

^<<v6-24-11,11>>^ Passando vós o Jordão e vindo a Jericó, os habitantes de Jericó pelejaram contra vós outros e também os amorreus, os ferezeus, os cananeus, os heteus, os girgaseus, os heveus e os jebuseus; porém os entreguei nas vossas mãos.

[[v6-24-12]]

^<<v6-24-12,12>>^ Enviei vespões adiante de vós, que os expulsaram da vossa presença, bem como os dois reis dos amorreus, e isso não com a tua espada, nem com o teu arco.

[[v6-24-13]]

^<<v6-24-13,13>>^ Dei-vos a terra em que não trabalhastes e cidades que não edificastes, e habitais nelas; comeis das vinhas e dos olivais que não plantastes.

[[v6-24-14]]

^<<v6-24-14,14>>^ Agora, pois, temei ao SENHOR e servi-o com integridade e com fidelidade; deitai fora os deuses aos quais serviram vossos pais dalém do Eufrates e no Egito e servi ao SENHOR.

[[v6-24-15]]

^<<v6-24-15,15>>^ Porém, se vos parece mal servir ao SENHOR, escolhei, hoje, a quem sirvais: se aos deuses a quem serviram vossos pais que estavam dalém do Eufrates ou aos deuses dos amorreus em cuja terra habitais. Eu e a minha casa serviremos ao SENHOR.

[[v6-24-16]]

^<<v6-24-16,16>>^ Então, respondeu o povo e disse: Longe de nós o abandonarmos o SENHOR para servirmos a outros deuses;

[[v6-24-17]]

^<<v6-24-17,17>>^ porque o SENHOR é o nosso Deus; ele é quem nos fez subir, a nós e a nossos pais, da terra do Egito, da casa da servidão, quem fez estes grandes sinais aos nossos olhos e nos guardou por todo o caminho em que andamos e entre todos os povos pelo meio dos quais passamos.

[[v6-24-18]]

^<<v6-24-18,18>>^ O SENHOR expulsou de diante de nós todas estas gentes, até o amorreu, morador da terra; portanto, nós também serviremos ao SENHOR, pois ele é o nosso Deus.

[[v6-24-19]]

^<<v6-24-19,19>>^ Então, Josué disse ao povo: Não podereis servir ao SENHOR, porquanto é Deus santo, Deus zeloso, que não perdoará a vossa transgressão nem os vossos pecados.

[[v6-24-20]]

^<<v6-24-20,20>>^ Se deixardes o SENHOR e servirdes a deuses estranhos, então, se voltará, e vos fará mal, e vos consumirá, depois de vos ter feito bem.

[[v6-24-21]]

^<<v6-24-21,21>>^ Então, disse o povo a Josué: Não; antes, serviremos ao SENHOR.

[[v6-24-22]]

^<<v6-24-22,22>>^ Josué disse ao povo: Sois testemunhas contra vós mesmos de que escolhestes o SENHOR para o servir. E disseram: Nós o somos.

[[v6-24-23]]

^<<v6-24-23,23>>^ Agora, pois, deitai fora os deuses estranhos que há no meio de vós e inclinai o coração ao SENHOR, Deus de Israel.

[[v6-24-24]]

^<<v6-24-24,24>>^ Disse o povo a Josué: Ao SENHOR, nosso Deus, serviremos e obedeceremos à sua voz.

[[v6-24-25]]

^<<v6-24-25,25>>^ Assim, naquele dia, fez Josué aliança com o povo e lha pôs por estatuto e direito em Siquém.

[[v6-24-26]]

^<<v6-24-26,26>>^ Josué escreveu estas palavras no Livro da Lei de Deus; tomou uma grande pedra e a erigiu ali debaixo do carvalho que estava em lugar santo do SENHOR.

[[v6-24-27]]

^<<v6-24-27,27>>^ Disse Josué a todo o povo: Eis que esta pedra nos será testemunha, pois ouviu todas as palavras que o SENHOR nos tem dito; portanto, será testemunha contra vós outros para que não mintais a vosso Deus.

[[v6-24-28]]

^<<v6-24-28,28>>^ Então, Josué despediu o povo, cada um para a sua herança.

[[v6-24-29]]

^<<v6-24-29,29>>^ Depois destas coisas, sucedeu que Josué, filho de Num, servo do SENHOR, faleceu com a idade de cento e dez anos.

[[v6-24-30]]

^<<v6-24-30,30>>^ Sepultaram-no na sua própria herança, em Timnate-Sera, que está na região montanhosa de Efraim, para o norte do monte Gaás.

[[v6-24-31]]

^<<v6-24-31,31>>^ Serviu, pois, Israel ao SENHOR todos os dias de Josué e todos os dias dos anciãos que ainda sobreviveram por muito tempo depois de Josué e que sabiam todas as obras feitas pelo SENHOR a Israel.

[[v6-24-32]]

^<<v6-24-32,32>>^ Os ossos de José, que os filhos de Israel trouxeram do Egito, enterraram-nos em Siquém, naquela parte do campo que Jacó comprara aos filhos de Hamor, pai de Siquém, por cem peças de prata, e que veio a ser a herança dos filhos de José.

[[v6-24-33]]

^<<v6-24-33,33>>^ Faleceu também Eleazar, filho de Arão, e o sepultaram em Gibeá, pertencente a Fineias, seu filho, a qual lhe fora dada na região montanhosa de Efraim.

'''

xref:006-josue/006-josue-023.adoc#v6-23-0[&#60; Capítulo Anterior] | <<v6-24-0,Topo>> | xref:007-juizes/007-juizes-001.adoc#v7-1-0[Próximo Capítulo &#62;]