include::./index.adoc[]

[[v6-4-0]]
=== Josué, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v6-4-1]]

^<<v6-4-1,1>>^ Tendo, pois, todo o povo passado o Jordão, falou o SENHOR a Josué, dizendo:

[[v6-4-2]]

^<<v6-4-2,2>>^ Tomai do povo doze homens, um de cada tribo,

[[v6-4-3]]

^<<v6-4-3,3>>^ e ordenai-lhes, dizendo: Daqui do meio do Jordão, do lugar onde, parados, pousaram os sacerdotes os pés, tomai doze pedras; e levai-as convosco e depositai-as no alojamento em que haveis de passar esta noite.

[[v6-4-4]]

^<<v6-4-4,4>>^ Chamou, pois, Josué os doze homens que escolhera dos filhos de Israel,

[[v6-4-5]]

^<<v6-4-5,5>>^ um de cada tribo, e disse-lhes: Passai adiante da arca do SENHOR, vosso Deus, ao meio do Jordão; e cada um levante sobre o ombro uma pedra, segundo o número das tribos dos filhos de Israel,

[[v6-4-6]]

^<<v6-4-6,6>>^ para que isto seja por sinal entre vós; e, quando vossos filhos, no futuro, perguntarem, dizendo: Que vos significam estas pedras?,

[[v6-4-7]]

^<<v6-4-7,7>>^ então, lhes direis que as águas do Jordão foram cortadas diante da arca da Aliança do SENHOR; em passando ela, foram as águas do Jordão cortadas. Estas pedras serão, para sempre, por memorial aos filhos de Israel.

[[v6-4-8]]

^<<v6-4-8,8>>^ Fizeram, pois, os filhos de Israel como Josué ordenara, e levantaram doze pedras do meio do Jordão, como o SENHOR tinha dito a Josué, segundo o número das tribos dos filhos de Israel, e levaram-nas consigo ao alojamento, e as depositaram ali.

[[v6-4-9]]

^<<v6-4-9,9>>^ Levantou Josué também doze pedras no meio do Jordão, no lugar em que, parados, pousaram os pés os sacerdotes que levavam a arca da Aliança; e ali estão até ao dia de hoje.

[[v6-4-10]]

^<<v6-4-10,10>>^ Porque os sacerdotes que levavam a arca haviam parado no meio do Jordão, em pé, até que se cumpriu tudo quanto o SENHOR, por intermédio de Moisés, ordenara a Josué falasse ao povo; e o povo se apressou e passou.

[[v6-4-11]]

^<<v6-4-11,11>>^ Tendo passado todo o povo, então, passou a arca do SENHOR, e os sacerdotes, à vista de todo o povo.

[[v6-4-12]]

^<<v6-4-12,12>>^ Passaram os filhos de Rúben, e os filhos de Gade, e a meia tribo de Manassés, armados, na frente dos filhos de Israel, como Moisés lhes tinha dito;

[[v6-4-13]]

^<<v6-4-13,13>>^ uns quarenta mil homens de guerra armados passaram diante do SENHOR para a batalha, às campinas de Jericó.

[[v6-4-14]]

^<<v6-4-14,14>>^ Naquele dia, o SENHOR engrandeceu a Josué na presença de todo o Israel; e respeitaram-no todos os dias da sua vida, como haviam respeitado a Moisés.

[[v6-4-15]]

^<<v6-4-15,15>>^ Disse, pois, o SENHOR a Josué:

[[v6-4-16]]

^<<v6-4-16,16>>^ Dá ordem aos sacerdotes que levam a arca do Testemunho que subam do Jordão.

[[v6-4-17]]

^<<v6-4-17,17>>^ Então, ordenou Josué aos sacerdotes, dizendo: Subi do Jordão.

[[v6-4-18]]

^<<v6-4-18,18>>^ Ao subirem do meio do Jordão os sacerdotes que levavam a arca da Aliança do SENHOR, e assim que as plantas dos seus pés se puseram na terra seca, as águas do Jordão se tornaram ao seu lugar e corriam, como dantes, sobre todas as suas ribanceiras.

[[v6-4-19]]

^<<v6-4-19,19>>^ Subiu, pois, do Jordão o povo no dia dez do primeiro mês; e acamparam-se em Gilgal, do lado oriental de Jericó.

[[v6-4-20]]

^<<v6-4-20,20>>^ As doze pedras que tiraram do Jordão, levantou-as Josué em coluna em Gilgal.

[[v6-4-21]]

^<<v6-4-21,21>>^ E disse aos filhos de Israel: Quando, no futuro, vossos filhos perguntarem a seus pais, dizendo: Que significam estas pedras?,

[[v6-4-22]]

^<<v6-4-22,22>>^ fareis saber a vossos filhos, dizendo: Israel passou em seco este Jordão.

[[v6-4-23]]

^<<v6-4-23,23>>^ Porque o SENHOR, vosso Deus, fez secar as águas do Jordão diante de vós, até que passásseis, como o SENHOR, vosso Deus, fez ao mar Vermelho, ao qual secou perante nós, até que passamos.

[[v6-4-24]]

^<<v6-4-24,24>>^ Para que todos os povos da terra conheçam que a mão do SENHOR é forte, a fim de que temais ao SENHOR, vosso Deus, todos os dias.

'''

xref:006-josue/006-josue-003.adoc#v6-3-0[&#60; Capítulo Anterior] | <<v6-4-0,Topo>> | xref:006-josue/006-josue-005.adoc#v6-5-0[Próximo Capítulo &#62;]