include::./index.adoc[]

[[v6-23-0]]
=== Josué, 23
// ara ?, ARA - Almeida Revista e Atualizada

[[v6-23-1]]

^<<v6-23-1,1>>^ Passado muito tempo depois que o SENHOR dera repouso a Israel de todos os seus inimigos em redor, e sendo Josué já velho e entrado em dias,

[[v6-23-2]]

^<<v6-23-2,2>>^ chamou Josué a todo o Israel, os seus anciãos, os seus cabeças, os seus juízes e os seus oficiais e disse-lhes: Já sou velho e entrado em dias,

[[v6-23-3]]

^<<v6-23-3,3>>^ e vós já tendes visto tudo quanto fez o SENHOR, vosso Deus, a todas estas nações por causa de vós, porque o SENHOR, vosso Deus, é o que pelejou por vós.

[[v6-23-4]]

^<<v6-23-4,4>>^ Vede aqui que vos fiz cair em sorte às vossas tribos estas nações que restam, juntamente com todas as nações que tenho eliminado, umas e outras, desde o Jordão até ao mar Grande, para o pôr do sol.

[[v6-23-5]]

^<<v6-23-5,5>>^ O SENHOR, vosso Deus, as afastará de vós e as expulsará de vossa presença; e vós possuireis a sua terra, como o SENHOR, vosso Deus, vos prometeu.

[[v6-23-6]]

^<<v6-23-6,6>>^ Esforçai-vos, pois, muito para guardardes e cumprirdes tudo quanto está escrito no Livro da Lei de Moisés, para que dela não vos aparteis, nem para a direita nem para a esquerda;

[[v6-23-7]]

^<<v6-23-7,7>>^ para que não vos mistureis com estas nações que restaram entre vós. Não façais menção dos nomes de seus deuses, nem por eles façais jurar, nem os sirvais, nem os adoreis.

[[v6-23-8]]

^<<v6-23-8,8>>^ Mas ao SENHOR, vosso Deus, vos apegareis, como fizestes até ao dia de hoje;

[[v6-23-9]]

^<<v6-23-9,9>>^ pois o SENHOR expulsou de diante de vós grandes e fortes nações; e, quanto a vós outros, ninguém vos resistiu até ao dia de hoje.

[[v6-23-10]]

^<<v6-23-10,10>>^ Um só homem dentre vós perseguirá mil, pois o SENHOR, vosso Deus, é quem peleja por vós, como já vos prometeu.

[[v6-23-11]]

^<<v6-23-11,11>>^ Portanto, empenhai-vos em guardar a vossa alma, para amardes o SENHOR, vosso Deus.

[[v6-23-12]]

^<<v6-23-12,12>>^ Porque, se dele vos desviardes e vos apegardes ao restante destas nações ainda em vosso meio, e com elas vos aparentardes, e com elas vos misturardes, e elas convosco,

[[v6-23-13]]

^<<v6-23-13,13>>^ sabei, certamente, que o SENHOR, vosso Deus, não expulsará mais estas nações de vossa presença, mas vos serão por laço e rede, e açoite às vossas ilhargas, e espinhos aos vossos olhos, até que pereçais nesta boa terra que vos deu o SENHOR, vosso Deus.

[[v6-23-14]]

^<<v6-23-14,14>>^ Eis que, já hoje, sigo pelo caminho de todos os da terra; e vós bem sabeis de todo o vosso coração e de toda a vossa alma que nem uma só promessa caiu de todas as boas palavras que falou de vós o SENHOR, vosso Deus; todas vos sobrevieram, nem uma delas falhou.

[[v6-23-15]]

^<<v6-23-15,15>>^ E sucederá que, assim como vieram sobre vós todas estas boas coisas que o SENHOR, vosso Deus, vos prometeu, assim cumprirá o SENHOR contra vós outros todas as ameaças até vos destruir de sobre a boa terra que vos deu o SENHOR, vosso Deus.

[[v6-23-16]]

^<<v6-23-16,16>>^ Quando violardes a aliança que o SENHOR, vosso Deus, vos ordenou, e fordes, e servirdes a outros deuses, e os adorardes, então, a ira do SENHOR se acenderá sobre vós, e logo perecereis na boa terra que vos deu.

'''

xref:006-josue/006-josue-022.adoc#v6-22-0[&#60; Capítulo Anterior] | <<v6-23-0,Topo>> | xref:006-josue/006-josue-024.adoc#v6-24-0[Próximo Capítulo &#62;]