include::./index.adoc[]

[[v6-12-0]]
=== Josué, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v6-12-1]]

^<<v6-12-1,1>>^ São estes os reis da terra, aos quais os filhos de Israel feriram, de cujas terras se apossaram dalém do Jordão para o nascente, desde o ribeiro de Arnom até ao monte Hermom e toda a planície do oriente:

[[v6-12-2]]

^<<v6-12-2,2>>^ Seom, rei dos amorreus, que habitava em Hesbom e dominava desde Aroer, que está à beira do vale de Arnom, e desde o meio do vale e a metade de Gileade até ao ribeiro de Jaboque, limite dos filhos de Amom;

[[v6-12-3]]

^<<v6-12-3,3>>^ desde a campina até ao mar de Quinerete, para o oriente, e até ao mar da Campina, o mar Salgado, para o oriente, pelo caminho de Bete-Jesimote; e desde o sul abaixo de Asdote-Pisga.

[[v6-12-4]]

^<<v6-12-4,4>>^ Como também o limite de Ogue, rei de Basã, que havia ficado dos refains e que habitava em Astarote e em Edrei;

[[v6-12-5]]

^<<v6-12-5,5>>^ e dominava no monte Hermom, e em Salca, e em toda a Basã, até ao limite dos gesuritas e dos maacatitas, e metade de Gileade, limite de Seom, rei de Hesbom.

[[v6-12-6]]

^<<v6-12-6,6>>^ Moisés, servo do SENHOR, e os filhos de Israel feriram a estes; e Moisés, servo do SENHOR, deu esta terra em possessão aos rubenitas, aos gaditas e à meia tribo de Manassés.

[[v6-12-7]]

^<<v6-12-7,7>>^ São estes os reis da terra aos quais Josué e os filhos de Israel feriram daquém do Jordão, para o ocidente, desde Baal-Gade, no vale do Líbano, até ao monte Halaque, que sobe a Seir, e cuja terra Josué deu em possessão às tribos de Israel, segundo as suas divisões,

[[v6-12-8]]

^<<v6-12-8,8>>^ a saber, o que havia na região montanhosa, nas planícies, na Arabá, nas descidas das águas, no deserto e no Neguebe, onde estava o heteu, o amorreu, o cananeu, o ferezeu, o heveu e o jebuseu:

[[v6-12-9]]

^<<v6-12-9,9>>^ o rei de Jericó, um; o de Ai, que está ao lado de Betel, outro;

[[v6-12-10]]

^<<v6-12-10,10>>^ o rei de Jerusalém, outro; o rei de Hebrom, outro;

[[v6-12-11]]

^<<v6-12-11,11>>^ o rei de Jarmute, outro; o de Laquis, outro;

[[v6-12-12]]

^<<v6-12-12,12>>^ o rei de Eglom, outro; o de Gezer, outro;

[[v6-12-13]]

^<<v6-12-13,13>>^ o rei de Debir, outro; o de Geder, outro;

[[v6-12-14]]

^<<v6-12-14,14>>^ o rei de Horma, outro; o de Arade, outro;

[[v6-12-15]]

^<<v6-12-15,15>>^ o rei de Libna, outro; o de Adulão, outro;

[[v6-12-16]]

^<<v6-12-16,16>>^ o rei de Maquedá, outro; o de Betel, outro;

[[v6-12-17]]

^<<v6-12-17,17>>^ o rei de Tapua, outro; o de Héfer, outro;

[[v6-12-18]]

^<<v6-12-18,18>>^ o rei de Afeca, outro; o de Lasarom, outro;

[[v6-12-19]]

^<<v6-12-19,19>>^ o rei de Madom, outro; o de Hazor, outro;

[[v6-12-20]]

^<<v6-12-20,20>>^ o rei de Sinrom-Merom, outro; o de Acsafe, outro;

[[v6-12-21]]

^<<v6-12-21,21>>^ o rei de Taanaque, outro; o de Megido, outro;

[[v6-12-22]]

^<<v6-12-22,22>>^ o rei de Quedes, outro; o de Jocneão do Carmelo, outro;

[[v6-12-23]]

^<<v6-12-23,23>>^ o rei de Dor, em Nafate-Dor, outro; o de Goim, em Gilgal, outro;

[[v6-12-24]]

^<<v6-12-24,24>>^ o rei de Tirza, outro; ao todo, trinta e um reis.

'''

xref:006-josue/006-josue-011.adoc#v6-11-0[&#60; Capítulo Anterior] | <<v6-12-0,Topo>> | xref:006-josue/006-josue-013.adoc#v6-13-0[Próximo Capítulo &#62;]