include::./index.adoc[]

[[v6-15-0]]
=== Josué, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v6-15-1]]

^<<v6-15-1,1>>^ A sorte da tribo dos filhos de Judá, segundo as suas famílias, caiu para o sul, até ao limite de Edom, até ao deserto de Zim, até à extremidade do lado sul.

[[v6-15-2]]

^<<v6-15-2,2>>^ Foi o seu limite ao sul, desde a extremidade do mar Salgado, desde a baía que olha para o sul;

[[v6-15-3]]

^<<v6-15-3,3>>^ e sai para o sul, até à subida de Acrabim, passa a Zim, sobe do sul a Cades-Barneia,

[[v6-15-4]]

^<<v6-15-4,4>>^ passa por Hezrom, sobe a Adar e rodeia Carca; passa por Azmom e sai ao ribeiro do Egito; as saídas deste limite vão até ao mar; este será o vosso limite do lado sul.

[[v6-15-5]]

^<<v6-15-5,5>>^ O limite, porém, para o oriente será o mar Salgado, até à foz do Jordão; e o limite para o norte será da baía do mar, começando com a embocadura do Jordão,

[[v6-15-6]]

^<<v6-15-6,6>>^ limite que sobe até Bete-Hogla e passa do norte a Bete-Arabá, subindo até à pedra de Boã, filho de Rúben,

[[v6-15-7]]

^<<v6-15-7,7>>^ subindo ainda este limite a Debir desde o vale de Acor, olhando para o norte, rumo a Gilgal, a qual está à subida de Adumim, que está para o sul do ribeiro; daí, o limite passa até às águas de En-Semes; e as suas saídas estarão do lado de En-Rogel.

[[v6-15-8]]

^<<v6-15-8,8>>^ Deste ponto sobe pelo vale do Filho de Hinom, do lado dos jebuseus do Sul, isto é, Jerusalém; e sobe este limite até ao cimo do monte que está diante do vale de Hinom, para o ocidente, que está no fim do vale dos Refains, do lado norte.

[[v6-15-9]]

^<<v6-15-9,9>>^ Então, vai o limite desde o cimo do monte até à fonte das águas de Neftoa; e sai até às cidades do monte Efrom; vai mais este limite até Baalá, isto é, Quiriate-Jearim.

[[v6-15-10]]

^<<v6-15-10,10>>^ Então, dá volta o limite desde Baalá, para o ocidente, até ao monte Seir, passa ao lado do monte de Jearim do lado norte, isto é, Quesalom, e, descendo a Bete-Semes, passa por Timna.

[[v6-15-11]]

^<<v6-15-11,11>>^ Segue mais ainda o limite ao lado de Ecrom, para o norte, e, indo a Siquerom, passa o monte de Baalá, saindo em Jabneel, para terminar no mar.

[[v6-15-12]]

^<<v6-15-12,12>>^ O limite, porém, do lado ocidental é o mar Grande e as suas imediações. São estes os limites dos filhos de Judá ao redor, segundo as suas famílias.

[[v6-15-13]]

^<<v6-15-13,13>>^ A Calebe, filho de Jefoné, porém, deu Josué uma parte no meio dos filhos de Judá, segundo lhe ordenara o SENHOR, a saber, Quiriate-Arba, isto é, Hebrom; este Arba era o pai de Anaque.

[[v6-15-14]]

^<<v6-15-14,14>>^ Dali expulsou Calebe os três filhos de Anaque: Sesai, Aimã e Talmai, gerados de Anaque.

[[v6-15-15]]

^<<v6-15-15,15>>^ Subiu aos habitantes de Debir, cujo nome, dantes, era Quiriate-Sefer.

[[v6-15-16]]

^<<v6-15-16,16>>^ Disse Calebe: A quem derrotar Quiriate-Sefer e a tomar, darei minha filha Acsa por mulher.

[[v6-15-17]]

^<<v6-15-17,17>>^ Tomou-a, pois, Otniel, filho de Quenaz, irmão de Calebe; este lhe deu a filha Acsa por mulher.

[[v6-15-18]]

^<<v6-15-18,18>>^ Esta, quando se foi a Otniel, insistiu com ele para que pedisse um campo ao pai dela; e ela apeou do jumento; então, Calebe lhe perguntou: Que desejas?

[[v6-15-19]]

^<<v6-15-19,19>>^ Respondeu ela: Dá-me um presente; deste-me terra seca, dá-me também fontes de água. Então, lhe deu as fontes superiores e as fontes inferiores.

[[v6-15-20]]

^<<v6-15-20,20>>^ Esta é a herança da tribo dos filhos de Judá, segundo as suas famílias.

[[v6-15-21]]

^<<v6-15-21,21>>^ São, pois, as cidades no extremo sul da tribo dos filhos de Judá, rumo do território de Edom: Cabzeel, Éder, Jagur,

[[v6-15-22]]

^<<v6-15-22,22>>^ Quiná, Dimona, Adada,

[[v6-15-23]]

^<<v6-15-23,23>>^ Quedes, Hazor, Itnã,

[[v6-15-24]]

^<<v6-15-24,24>>^ Zife, Telém, Bealote,

[[v6-15-25]]

^<<v6-15-25,25>>^ Hazor-Hadata, Queriote-Hezrom (que é Hazor),

[[v6-15-26]]

^<<v6-15-26,26>>^ Amã, Sema, Molada,

[[v6-15-27]]

^<<v6-15-27,27>>^ Hazar-Gada, Hesmom, Bete-Palete,

[[v6-15-28]]

^<<v6-15-28,28>>^ Hazar-Sual, Berseba, Biziotiá,

[[v6-15-29]]

^<<v6-15-29,29>>^ Baalá, Iim, Ezém,

[[v6-15-30]]

^<<v6-15-30,30>>^ Eltolade, Quesil, Horma,

[[v6-15-31]]

^<<v6-15-31,31>>^ Ziclague, Madmana, Sansana,

[[v6-15-32]]

^<<v6-15-32,32>>^ Lebaote, Silim, Aim e Rimom; ao todo, vinte e nove cidades com suas aldeias.

[[v6-15-33]]

^<<v6-15-33,33>>^ Nas planícies: Estaol, Zorá, Asná,

[[v6-15-34]]

^<<v6-15-34,34>>^ Zanoa, En-Ganim, Tapua, Enã,

[[v6-15-35]]

^<<v6-15-35,35>>^ Jarmute, Adulão, Socó, Azeca,

[[v6-15-36]]

^<<v6-15-36,36>>^ Saaraim, Aditaim, Gedera e Gederotaim; ao todo, catorze cidades com suas aldeias.

[[v6-15-37]]

^<<v6-15-37,37>>^ Zenã, Hadasa, Migdal-Gade,

[[v6-15-38]]

^<<v6-15-38,38>>^ Dileã, Mispa, Jocteel,

[[v6-15-39]]

^<<v6-15-39,39>>^ Laquis, Boscate, Eglom,

[[v6-15-40]]

^<<v6-15-40,40>>^ Cabom, Laamás, Quitlis,

[[v6-15-41]]

^<<v6-15-41,41>>^ Gederote, Bete-Dagom, Naamá e Maquedá; ao todo, dezesseis cidades com suas aldeias.

[[v6-15-42]]

^<<v6-15-42,42>>^ Libna, Eter, Asã,

[[v6-15-43]]

^<<v6-15-43,43>>^ Ifta, Asná, Nezibe,

[[v6-15-44]]

^<<v6-15-44,44>>^ Queila, Aczibe e Maressa; ao todo, nove cidades com suas aldeias.

[[v6-15-45]]

^<<v6-15-45,45>>^ Ecrom com suas vilas e aldeias;

[[v6-15-46]]

^<<v6-15-46,46>>^ desde Ecrom até ao mar, todas as que estão do lado de Asdode, com suas aldeias.

[[v6-15-47]]

^<<v6-15-47,47>>^ Asdode, suas vilas e aldeias; Gaza, suas vilas e aldeias, até ao rio do Egito e o mar Grande com as suas imediações.

[[v6-15-48]]

^<<v6-15-48,48>>^ Na região montanhosa: Samir, Jatir, Socó,

[[v6-15-49]]

^<<v6-15-49,49>>^ Daná, Quiriate-Sana, que é Debir,

[[v6-15-50]]

^<<v6-15-50,50>>^ Anabe, Estemoa, Anim,

[[v6-15-51]]

^<<v6-15-51,51>>^ Gósen, Holom e Gilo; ao todo, onze cidades com suas aldeias.

[[v6-15-52]]

^<<v6-15-52,52>>^ Arabe, Dumá, Esã,

[[v6-15-53]]

^<<v6-15-53,53>>^ Janim, Bete-Tapua, Afeca,

[[v6-15-54]]

^<<v6-15-54,54>>^ Hunta, Quiriate-Arba (que é Hebrom) e Zior; ao todo, nove cidades com suas aldeias.

[[v6-15-55]]

^<<v6-15-55,55>>^ Maom, Carmelo, Zife, Jutá,

[[v6-15-56]]

^<<v6-15-56,56>>^ Jezreel, Jocdeão, Zanoa,

[[v6-15-57]]

^<<v6-15-57,57>>^ Caim, Gibeá e Timna; ao todo, dez cidades com suas aldeias.

[[v6-15-58]]

^<<v6-15-58,58>>^ Halul, Bete-Zur, Gedor,

[[v6-15-59]]

^<<v6-15-59,59>>^ Maarate, Bete-Anote e Eltecom; ao todo, seis cidades com suas aldeias.

[[v6-15-60]]

^<<v6-15-60,60>>^ Quiriate-Baal (que é Quiriate-Jearim) e Rabá; ao todo, duas cidades com suas aldeias.

[[v6-15-61]]

^<<v6-15-61,61>>^ No deserto: Bete-Arabá, Midim, Secaca,

[[v6-15-62]]

^<<v6-15-62,62>>^ Nibsã, Cidade do Sal e En-Gedi; ao todo, seis cidades com suas aldeias.

[[v6-15-63]]

^<<v6-15-63,63>>^ Não puderam, porém, os filhos de Judá expulsar os jebuseus que habitavam em Jerusalém; assim, habitam os jebuseus com os filhos de Judá em Jerusalém até ao dia de hoje.

'''

xref:006-josue/006-josue-014.adoc#v6-14-0[&#60; Capítulo Anterior] | <<v6-15-0,Topo>> | xref:006-josue/006-josue-016.adoc#v6-16-0[Próximo Capítulo &#62;]