include::./index.adoc[]

[[v6-3-0]]
=== Josué, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v6-3-1]]

^<<v6-3-1,1>>^ Levantou-se, pois, Josué de madrugada, e, tendo ele e todos os filhos de Israel partido de Sitim, vieram até ao Jordão e pousaram ali antes que passassem.

[[v6-3-2]]

^<<v6-3-2,2>>^ Sucedeu, ao fim de três dias, que os oficiais passaram pelo meio do arraial

[[v6-3-3]]

^<<v6-3-3,3>>^ e ordenaram ao povo, dizendo: Quando virdes a arca da Aliança do SENHOR, vosso Deus, e que os levitas sacerdotes a levam, partireis vós também do vosso lugar e a seguireis.

[[v6-3-4]]

^<<v6-3-4,4>>^ Contudo, haja a distância de cerca de dois mil côvados entre vós e ela. Não vos chegueis a ela, para que conheçais o caminho pelo qual haveis de ir, visto que, por tal caminho, nunca passastes antes.

[[v6-3-5]]

^<<v6-3-5,5>>^ Disse Josué ao povo: Santificai-vos, porque amanhã o SENHOR fará maravilhas no meio de vós.

[[v6-3-6]]

^<<v6-3-6,6>>^ E também falou aos sacerdotes, dizendo: Levantai a arca da Aliança e passai adiante do povo. Levantaram, pois, a arca da Aliança e foram andando adiante do povo.

[[v6-3-7]]

^<<v6-3-7,7>>^ Então, disse o SENHOR a Josué: Hoje, começarei a engrandecer-te perante os olhos de todo o Israel, para que saibam que, como fui com Moisés, assim serei contigo.

[[v6-3-8]]

^<<v6-3-8,8>>^ Tu, pois, ordenarás aos sacerdotes que levam a arca da Aliança, dizendo: Ao chegardes à borda das águas do Jordão, parareis aí.

[[v6-3-9]]

^<<v6-3-9,9>>^ Então, disse Josué aos filhos de Israel: Chegai-vos para cá e ouvi as palavras do SENHOR, vosso Deus.

[[v6-3-10]]

^<<v6-3-10,10>>^ Disse mais Josué: Nisto conhecereis que o Deus vivo está no meio de vós e que de todo lançará de diante de vós os cananeus, os heteus, os heveus, os ferezeus, os girgaseus, os amorreus e os jebuseus.

[[v6-3-11]]

^<<v6-3-11,11>>^ Eis que a arca da Aliança do Senhor de toda a terra passa o Jordão diante de vós.

[[v6-3-12]]

^<<v6-3-12,12>>^ Tomai, pois, agora, doze homens das tribos de Israel, um de cada tribo;

[[v6-3-13]]

^<<v6-3-13,13>>^ porque há de acontecer que, assim que as plantas dos pés dos sacerdotes que levam a arca do SENHOR, o Senhor de toda a terra, pousem nas águas do Jordão, serão elas cortadas, a saber, as que vêm de cima, e se amontoarão.

[[v6-3-14]]

^<<v6-3-14,14>>^ Tendo partido o povo das suas tendas, para passar o Jordão, levando os sacerdotes a arca da Aliança diante do povo;

[[v6-3-15]]

^<<v6-3-15,15>>^ e, quando os que levavam a arca chegaram até ao Jordão, e os seus pés se molharam na borda das águas (porque o Jordão transbordava sobre todas as suas ribanceiras, todos os dias da sega),

[[v6-3-16]]

^<<v6-3-16,16>>^ pararam-se as águas que vinham de cima; levantaram-se num montão, mui longe da cidade de Adã, que fica ao lado de Sartã; e as que desciam ao mar da Arabá, que é o mar Salgado, foram de todo cortadas; então, passou o povo defronte de Jericó.

[[v6-3-17]]

^<<v6-3-17,17>>^ Porém os sacerdotes que levavam a arca da Aliança do SENHOR pararam firmes no meio do Jordão, e todo o Israel passou a pé enxuto, atravessando o Jordão.

'''

xref:006-josue/006-josue-002.adoc#v6-2-0[&#60; Capítulo Anterior] | <<v6-3-0,Topo>> | xref:006-josue/006-josue-004.adoc#v6-4-0[Próximo Capítulo &#62;]