include::./index.adoc[]

[[v6-9-0]]
=== Josué, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v6-9-1]]

^<<v6-9-1,1>>^ Sucedeu que, ouvindo isto todos os reis que estavam daquém do Jordão, nas montanhas, e nas campinas, em toda a costa do mar Grande, defronte do Líbano, os heteus, os amorreus, os cananeus, os ferezeus, os heveus e os jebuseus,

[[v6-9-2]]

^<<v6-9-2,2>>^ se ajuntaram eles de comum acordo, para pelejar contra Josué e contra Israel.

[[v6-9-3]]

^<<v6-9-3,3>>^ Os moradores de Gibeão, porém, ouvindo o que Josué fizera com Jericó e com Ai,

[[v6-9-4]]

^<<v6-9-4,4>>^ usaram de estratagema, e foram, e se fingiram embaixadores, e levaram sacos velhos sobre os seus jumentos e odres de vinho, velhos, rotos e consertados;

[[v6-9-5]]

^<<v6-9-5,5>>^ e, nos pés, sandálias velhas e remendadas e roupas velhas sobre si; e todo o pão que traziam para o caminho era seco e bolorento.

[[v6-9-6]]

^<<v6-9-6,6>>^ Foram ter com Josué, ao arraial, a Gilgal, e lhe disseram, a ele e aos homens de Israel: Chegamos de uma terra distante; fazei, pois, agora, aliança conosco.

[[v6-9-7]]

^<<v6-9-7,7>>^ E os homens de Israel responderam aos heveus: Porventura, habitais no meio de nós; como, pois, faremos aliança convosco?

[[v6-9-8]]

^<<v6-9-8,8>>^ Então, disseram a Josué: Somos teus servos. Então, lhes perguntou Josué: Quem sois vós? Donde vindes?

[[v6-9-9]]

^<<v6-9-9,9>>^ Responderam-lhe: Teus servos vieram de uma terra mui distante, por causa do nome do SENHOR, teu Deus; porquanto ouvimos a sua fama e tudo quanto fez no Egito;

[[v6-9-10]]

^<<v6-9-10,10>>^ e tudo quanto fez aos dois reis dos amorreus que estavam dalém do Jordão, Seom, rei de Hesbom, e Ogue, rei de Basã, que estava em Astarote.

[[v6-9-11]]

^<<v6-9-11,11>>^ Pelo que nossos anciãos e todos os moradores da nossa terra nos disseram: Tomai convosco provisão alimentar para o caminho, e ide ao encontro deles, e dizei-lhes: Somos vossos servos; fazei, pois, agora, aliança conosco.

[[v6-9-12]]

^<<v6-9-12,12>>^ Este nosso pão tomamos quente das nossas casas, no dia em que saímos para vir ter convosco; e ei-lo aqui, agora, já seco e bolorento;

[[v6-9-13]]

^<<v6-9-13,13>>^ e estes odres eram novos quando os enchemos de vinho; e ei-los aqui já rotos; e estas nossas vestes e estas nossas sandálias já envelheceram, por causa do mui longo caminho.

[[v6-9-14]]

^<<v6-9-14,14>>^ Então, os israelitas tomaram da provisão e não pediram conselho ao SENHOR.

[[v6-9-15]]

^<<v6-9-15,15>>^ Josué concedeu-lhes paz e fez com eles a aliança de lhes conservar a vida; e os príncipes da congregação lhes prestaram juramento.

[[v6-9-16]]

^<<v6-9-16,16>>^ Ao cabo de três dias, depois de terem feito a aliança com eles, ouviram que eram seus vizinhos e que moravam no meio deles.

[[v6-9-17]]

^<<v6-9-17,17>>^ Pois, partindo os filhos de Israel, chegaram às cidades deles ao terceiro dia; suas cidades eram Gibeão, Cefira, Beerote e Quiriate-Jearim.

[[v6-9-18]]

^<<v6-9-18,18>>^ Os filhos de Israel não os feriram, porquanto os príncipes da congregação lhes juraram pelo SENHOR, Deus de Israel; pelo que toda a congregação murmurou contra os príncipes.

[[v6-9-19]]

^<<v6-9-19,19>>^ Então, todos os príncipes disseram a toda a congregação: Nós lhes juramos pelo SENHOR, Deus de Israel; por isso, não podemos tocar-lhes.

[[v6-9-20]]

^<<v6-9-20,20>>^ Isto, porém, lhes faremos: Conservar-lhes-emos a vida, para que não haja grande ira sobre nós, por causa do juramento que já lhes fizemos.

[[v6-9-21]]

^<<v6-9-21,21>>^ Disseram-lhes, pois, os príncipes: Vivam. E se tornaram rachadores de lenha e tiradores de água para toda a congregação, como os príncipes lhes haviam dito.

[[v6-9-22]]

^<<v6-9-22,22>>^ Chamou-os Josué e disse-lhes: Por que nos enganastes, dizendo: Habitamos mui longe de vós, sendo que viveis em nosso meio?

[[v6-9-23]]

^<<v6-9-23,23>>^ Agora, pois, sois malditos; e dentre vós nunca deixará de haver escravos, rachadores de lenha e tiradores de água para a casa do meu Deus.

[[v6-9-24]]

^<<v6-9-24,24>>^ Então, responderam a Josué: É que se anunciou aos teus servos, como certo, que o SENHOR, teu Deus, ordenara a seu servo Moisés que vos desse toda esta terra e destruísse todos os moradores dela diante de vós. Por isso, tememos muito por nossa vida por causa de vós e fizemos assim.

[[v6-9-25]]

^<<v6-9-25,25>>^ Eis que estamos na tua mão; trata-nos segundo te parecer bom e reto.

[[v6-9-26]]

^<<v6-9-26,26>>^ Assim lhes fez e livrou-os das mãos dos filhos de Israel; e não os mataram.

[[v6-9-27]]

^<<v6-9-27,27>>^ Naquele dia, Josué os fez rachadores de lenha e tiradores de água para a congregação e para o altar do SENHOR, até ao dia de hoje, no lugar que Deus escolhesse.

'''

xref:006-josue/006-josue-008.adoc#v6-8-0[&#60; Capítulo Anterior] | <<v6-9-0,Topo>> | xref:006-josue/006-josue-010.adoc#v6-10-0[Próximo Capítulo &#62;]