include::./index.adoc[]

[[v50-1-0]]
=== Filipenses, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v50-1-1]]

^<<v50-1-1,1>>^ Paulo e Timóteo, servos de Cristo Jesus, a todos os santos em Cristo Jesus, inclusive bispos e diáconos que vivem em Filipos,

[[v50-1-2]]

^<<v50-1-2,2>>^ graça e paz a vós outros, da parte de Deus, nosso Pai, e do Senhor Jesus Cristo.

[[v50-1-3]]

^<<v50-1-3,3>>^ Dou graças ao meu Deus por tudo que recordo de vós,

[[v50-1-4]]

^<<v50-1-4,4>>^ fazendo sempre, com alegria, súplicas por todos vós, em todas as minhas orações,

[[v50-1-5]]

^<<v50-1-5,5>>^ pela vossa cooperação no evangelho, desde o primeiro dia até agora.

[[v50-1-6]]

^<<v50-1-6,6>>^ Estou plenamente certo de que aquele que começou boa obra em vós há de completá-la até ao Dia de Cristo Jesus.

[[v50-1-7]]

^<<v50-1-7,7>>^ Aliás, é justo que eu assim pense de todos vós, porque vos trago no coração, seja nas minhas algemas, seja na defesa e confirmação do evangelho, pois todos sois participantes da graça comigo.

[[v50-1-8]]

^<<v50-1-8,8>>^ Pois minha testemunha é Deus, da saudade que tenho de todos vós, na terna misericórdia de Cristo Jesus.

[[v50-1-9]]

^<<v50-1-9,9>>^ E também faço esta oração: que o vosso amor aumente mais e mais em pleno conhecimento e toda a percepção,

[[v50-1-10]]

^<<v50-1-10,10>>^ para aprovardes as coisas excelentes e serdes sinceros e inculpáveis para o Dia de Cristo,

[[v50-1-11]]

^<<v50-1-11,11>>^ cheios do fruto de justiça, o qual é mediante Jesus Cristo, para a glória e louvor de Deus.

[[v50-1-12]]

^<<v50-1-12,12>>^ Quero ainda, irmãos, cientificar-vos de que as coisas que me aconteceram têm, antes, contribuído para o progresso do evangelho;

[[v50-1-13]]

^<<v50-1-13,13>>^ de maneira que as minhas cadeias, em Cristo, se tornaram conhecidas de toda a guarda pretoriana e de todos os demais;

[[v50-1-14]]

^<<v50-1-14,14>>^ e a maioria dos irmãos, estimulados no Senhor por minhas algemas, ousam falar com mais desassombro a palavra de Deus.

[[v50-1-15]]

^<<v50-1-15,15>>^ Alguns, efetivamente, proclamam a Cristo por inveja e porfia; outros, porém, o fazem de boa vontade;

[[v50-1-16]]

^<<v50-1-16,16>>^ estes, por amor, sabendo que estou incumbido da defesa do evangelho;

[[v50-1-17]]

^<<v50-1-17,17>>^ aqueles, contudo, pregam a Cristo, por discórdia, insinceramente, julgando suscitar tribulação às minhas cadeias.

[[v50-1-18]]

^<<v50-1-18,18>>^ Todavia, que importa? Uma vez que Cristo, de qualquer modo, está sendo pregado, quer por pretexto, quer por verdade, também com isto me regozijo, sim, sempre me regozijarei.

[[v50-1-19]]

^<<v50-1-19,19>>^ Porque estou certo de que isto mesmo, pela vossa súplica e pela provisão do Espírito de Jesus Cristo, me redundará em libertação,

[[v50-1-20]]

^<<v50-1-20,20>>^ segundo a minha ardente expectativa e esperança de que em nada serei envergonhado; antes, com toda a ousadia, como sempre, também agora, será Cristo engrandecido no meu corpo, quer pela vida, quer pela morte.

[[v50-1-21]]

^<<v50-1-21,21>>^ Porquanto, para mim, o viver é Cristo, e o morrer é lucro.

[[v50-1-22]]

^<<v50-1-22,22>>^ Entretanto, se o viver na carne traz fruto para o meu trabalho, já não sei o que hei de escolher.

[[v50-1-23]]

^<<v50-1-23,23>>^ Ora, de um e outro lado, estou constrangido, tendo o desejo de partir e estar com Cristo, o que é incomparavelmente melhor.

[[v50-1-24]]

^<<v50-1-24,24>>^ Mas, por vossa causa, é mais necessário permanecer na carne.

[[v50-1-25]]

^<<v50-1-25,25>>^ E, convencido disto, estou certo de que ficarei e permanecerei com todos vós, para o vosso progresso e gozo da fé,

[[v50-1-26]]

^<<v50-1-26,26>>^ a fim de que aumente, quanto a mim, o motivo de vos gloriardes em Cristo Jesus, pela minha presença, de novo, convosco.

[[v50-1-27]]

^<<v50-1-27,27>>^ Vivei, acima de tudo, por modo digno do evangelho de Cristo, para que, ou indo ver-vos ou estando ausente, ouça, no tocante a vós outros, que estais firmes em um só espírito, como uma só alma, lutando juntos pela fé evangélica;

[[v50-1-28]]

^<<v50-1-28,28>>^ e que em nada estais intimidados pelos adversários. Pois o que é para eles prova evidente de perdição é, para vós outros, de salvação, e isto da parte de Deus.

[[v50-1-29]]

^<<v50-1-29,29>>^ Porque vos foi concedida a graça de padecerdes por Cristo e não somente de crerdes nele,

[[v50-1-30]]

^<<v50-1-30,30>>^ pois tendes o mesmo combate que vistes em mim e, ainda agora, ouvis que é o meu.

'''

xref:049-efesios/049-efesios-006.adoc#v49-6-0[&#60; Capítulo Anterior] | <<v50-1-0,Topo>> | xref:050-filipenses/050-filipenses-002.adoc#v50-2-0[Próximo Capítulo &#62;]