include::./index.adoc[]

[[v50-3-0]]
=== Filipenses, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v50-3-1]]

^<<v50-3-1,1>>^ Quanto ao mais, irmãos meus, alegrai-vos no Senhor. A mim, não me desgosta e é segurança para vós outros que eu escreva as mesmas coisas.

[[v50-3-2]]

^<<v50-3-2,2>>^ Acautelai-vos dos cães! Acautelai-vos dos maus obreiros! Acautelai-vos da falsa circuncisão!

[[v50-3-3]]

^<<v50-3-3,3>>^ Porque nós é que somos a circuncisão, nós que adoramos a Deus no Espírito, e nos gloriamos em Cristo Jesus, e não confiamos na carne.

[[v50-3-4]]

^<<v50-3-4,4>>^ Bem que eu poderia confiar também na carne. Se qualquer outro pensa que pode confiar na carne, eu ainda mais:

[[v50-3-5]]

^<<v50-3-5,5>>^ circuncidado ao oitavo dia, da linhagem de Israel, da tribo de Benjamim, hebreu de hebreus; quanto à lei, fariseu,

[[v50-3-6]]

^<<v50-3-6,6>>^ quanto ao zelo, perseguidor da igreja; quanto à justiça que há na lei, irrepreensível.

[[v50-3-7]]

^<<v50-3-7,7>>^ Mas o que, para mim, era lucro, isto considerei perda por causa de Cristo.

[[v50-3-8]]

^<<v50-3-8,8>>^ Sim, deveras considero tudo como perda, por causa da sublimidade do conhecimento de Cristo Jesus, meu Senhor; por amor do qual perdi todas as coisas e as considero como refugo, para ganhar a Cristo

[[v50-3-9]]

^<<v50-3-9,9>>^ e ser achado nele, não tendo justiça própria, que procede de lei, senão a que é mediante a fé em Cristo, a justiça que procede de Deus, baseada na fé;

[[v50-3-10]]

^<<v50-3-10,10>>^ para o conhecer, e o poder da sua ressurreição, e a comunhão dos seus sofrimentos, conformando-me com ele na sua morte;

[[v50-3-11]]

^<<v50-3-11,11>>^ para, de algum modo, alcançar a ressurreição dentre os mortos.

[[v50-3-12]]

^<<v50-3-12,12>>^ Não que eu o tenha já recebido ou tenha já obtido a perfeição; mas prossigo para conquistar aquilo para o que também fui conquistado por Cristo Jesus.

[[v50-3-13]]

^<<v50-3-13,13>>^ Irmãos, quanto a mim, não julgo havê-lo alcançado; mas uma coisa faço: esquecendo-me das coisas que para trás ficam e avançando para as que diante de mim estão,

[[v50-3-14]]

^<<v50-3-14,14>>^ prossigo para o alvo, para o prêmio da soberana vocação de Deus em Cristo Jesus.

[[v50-3-15]]

^<<v50-3-15,15>>^ Todos, pois, que somos perfeitos, tenhamos este sentimento; e, se, porventura, pensais doutro modo, também isto Deus vos esclarecerá.

[[v50-3-16]]

^<<v50-3-16,16>>^ Todavia, andemos de acordo com o que já alcançamos.

[[v50-3-17]]

^<<v50-3-17,17>>^ Irmãos, sede imitadores meus e observai os que andam segundo o modelo que tendes em nós.

[[v50-3-18]]

^<<v50-3-18,18>>^ Pois muitos andam entre nós, dos quais, repetidas vezes, eu vos dizia e, agora, vos digo, até chorando, que são inimigos da cruz de Cristo.

[[v50-3-19]]

^<<v50-3-19,19>>^ O destino deles é a perdição, o deus deles é o ventre, e a glória deles está na sua infâmia, visto que só se preocupam com as coisas terrenas.

[[v50-3-20]]

^<<v50-3-20,20>>^ Pois a nossa pátria está nos céus, de onde também aguardamos o Salvador, o Senhor Jesus Cristo,

[[v50-3-21]]

^<<v50-3-21,21>>^ o qual transformará o nosso corpo de humilhação, para ser igual ao corpo da sua glória, segundo a eficácia do poder que ele tem de até subordinar a si todas as coisas.

'''

xref:050-filipenses/050-filipenses-002.adoc#v50-2-0[&#60; Capítulo Anterior] | <<v50-3-0,Topo>> | xref:050-filipenses/050-filipenses-004.adoc#v50-4-0[Próximo Capítulo &#62;]