include::./index.adoc[]

[[v50-4-0]]
=== Filipenses, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v50-4-1]]

^<<v50-4-1,1>>^ Portanto, meus irmãos, amados e mui saudosos, minha alegria e coroa, sim, amados, permanecei, deste modo, firmes no Senhor.

[[v50-4-2]]

^<<v50-4-2,2>>^ Rogo a Evódia e rogo a Síntique pensem concordemente, no Senhor.

[[v50-4-3]]

^<<v50-4-3,3>>^ A ti, fiel companheiro de jugo, também peço que as auxilies, pois juntas se esforçaram comigo no evangelho, também com Clemente e com os demais cooperadores meus, cujos nomes se encontram no Livro da Vida.

[[v50-4-4]]

^<<v50-4-4,4>>^ Alegrai-vos sempre no Senhor; outra vez digo: alegrai-vos.

[[v50-4-5]]

^<<v50-4-5,5>>^ Seja a vossa moderação conhecida de todos os homens. Perto está o Senhor.

[[v50-4-6]]

^<<v50-4-6,6>>^ Não andeis ansiosos de coisa alguma; em tudo, porém, sejam conhecidas, diante de Deus, as vossas petições, pela oração e pela súplica, com ações de graças.

[[v50-4-7]]

^<<v50-4-7,7>>^ E a paz de Deus, que excede todo o entendimento, guardará o vosso coração e a vossa mente em Cristo Jesus.

[[v50-4-8]]

^<<v50-4-8,8>>^ Finalmente, irmãos, tudo o que é verdadeiro, tudo o que é respeitável, tudo o que é justo, tudo o que é puro, tudo o que é amável, tudo o que é de boa fama, se alguma virtude há e se algum louvor existe, seja isso o que ocupe o vosso pensamento.

[[v50-4-9]]

^<<v50-4-9,9>>^ O que também aprendestes, e recebestes, e ouvistes, e vistes em mim, isso praticai; e o Deus da paz será convosco.

[[v50-4-10]]

^<<v50-4-10,10>>^ Alegrei-me, sobremaneira, no Senhor porque, agora, uma vez mais, renovastes a meu favor o vosso cuidado; o qual também já tínheis antes, mas vos faltava oportunidade.

[[v50-4-11]]

^<<v50-4-11,11>>^ Digo isto, não por causa da pobreza, porque aprendi a viver contente em toda e qualquer situação.

[[v50-4-12]]

^<<v50-4-12,12>>^ Tanto sei estar humilhado como também ser honrado; de tudo e em todas as circunstâncias, já tenho experiência, tanto de fartura como de fome; assim de abundância como de escassez;

[[v50-4-13]]

^<<v50-4-13,13>>^ tudo posso naquele que me fortalece.

[[v50-4-14]]

^<<v50-4-14,14>>^ Todavia, fizestes bem, associando-vos na minha tribulação.

[[v50-4-15]]

^<<v50-4-15,15>>^ E sabeis também vós, ó filipenses, que, no início do evangelho, quando parti da Macedônia, nenhuma igreja se associou comigo no tocante a dar e receber, senão unicamente vós outros;

[[v50-4-16]]

^<<v50-4-16,16>>^ porque até para Tessalônica mandastes não somente uma vez, mas duas, o bastante para as minhas necessidades.

[[v50-4-17]]

^<<v50-4-17,17>>^ Não que eu procure o donativo, mas o que realmente me interessa é o fruto que aumente o vosso crédito.

[[v50-4-18]]

^<<v50-4-18,18>>^ Recebi tudo e tenho abundância; estou suprido, desde que Epafrodito me passou às mãos o que me veio de vossa parte como aroma suave, como sacrifício aceitável e aprazível a Deus.

[[v50-4-19]]

^<<v50-4-19,19>>^ E o meu Deus, segundo a sua riqueza em glória, há de suprir, em Cristo Jesus, cada uma de vossas necessidades.

[[v50-4-20]]

^<<v50-4-20,20>>^ Ora, a nosso Deus e Pai seja a glória pelos séculos dos séculos. Amém!

[[v50-4-21]]

^<<v50-4-21,21>>^ Saudai cada um dos santos em Cristo Jesus. Os irmãos que se acham comigo vos saúdam.

[[v50-4-22]]

^<<v50-4-22,22>>^ Todos os santos vos saúdam, especialmente os da casa de César.

[[v50-4-23]]

^<<v50-4-23,23>>^ A graça do Senhor Jesus Cristo seja com o vosso espírito.

'''

xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[&#60; Capítulo Anterior] | <<v50-4-0,Topo>> | xref:051-colossenses/051-colossenses-001.adoc#v51-1-0[Próximo Capítulo &#62;]