include::./index.adoc[]

[[v64-1-0]]
=== 3 João, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v64-1-1]]

^<<v64-1-1,1>>^ O presbítero ao amado Gaio, a quem eu amo na verdade.

[[v64-1-2]]

^<<v64-1-2,2>>^ Amado, acima de tudo, faço votos por tua prosperidade e saúde, assim como é próspera a tua alma.

[[v64-1-3]]

^<<v64-1-3,3>>^ Pois fiquei sobremodo alegre pela vinda de irmãos e pelo seu testemunho da tua verdade, como tu andas na verdade.

[[v64-1-4]]

^<<v64-1-4,4>>^ Não tenho maior alegria do que esta, a de ouvir que meus filhos andam na verdade.

[[v64-1-5]]

^<<v64-1-5,5>>^ Amado, procedes fielmente naquilo que praticas para com os irmãos, e isto fazes mesmo quando são estrangeiros,

[[v64-1-6]]

^<<v64-1-6,6>>^ os quais, perante a igreja, deram testemunho do teu amor. Bem farás encaminhando-os em sua jornada por modo digno de Deus;

[[v64-1-7]]

^<<v64-1-7,7>>^ pois por causa do Nome foi que saíram, nada recebendo dos gentios.

[[v64-1-8]]

^<<v64-1-8,8>>^ Portanto, devemos acolher esses irmãos, para nos tornarmos cooperadores da verdade.

[[v64-1-9]]

^<<v64-1-9,9>>^ Escrevi alguma coisa à igreja; mas Diótrefes, que gosta de exercer a primazia entre eles, não nos dá acolhida.

[[v64-1-10]]

^<<v64-1-10,10>>^ Por isso, se eu for aí, far-lhe-ei lembradas as obras que ele pratica, proferindo contra nós palavras maliciosas. E, não satisfeito com estas coisas, nem ele mesmo acolhe os irmãos, como impede os que querem recebê-los e os expulsa da igreja.

[[v64-1-11]]

^<<v64-1-11,11>>^ Amado, não imites o que é mau, senão o que é bom. Aquele que pratica o bem procede de Deus; aquele que pratica o mal jamais viu a Deus.

[[v64-1-12]]

^<<v64-1-12,12>>^ Quanto a Demétrio, todos lhe dão testemunho, até a própria verdade, e nós também damos testemunho; e sabes que o nosso testemunho é verdadeiro.

[[v64-1-13]]

^<<v64-1-13,13>>^ Muitas coisas tinha que te escrever; todavia, não quis fazê-lo com tinta e pena,

[[v64-1-14]]

^<<v64-1-14,14>>^ pois, em breve, espero ver-te. Então, conversaremos de viva voz.

[[v64-1-15]]

^<<v64-1-15,15>>^ A paz seja contigo. Os amigos te saúdam. Saúda os amigos, nome por nome.

'''

xref:063-2-joao/063-2-joao-001.adoc#v63-1-0[&#60; Capítulo Anterior] | <<v64-1-0,Topo>> | xref:065-judas/065-judas-001.adoc#v65-1-0[Próximo Capítulo &#62;]