include::./index.adoc[]

[[v26-4-0]]
=== Ezequiel, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-4-1]]

^<<v26-4-1,1>>^ Tu, pois, ó filho do homem, toma um tijolo, põe-no diante de ti e grava nele a cidade de Jerusalém.

[[v26-4-2]]

^<<v26-4-2,2>>^ Põe cerco contra ela, edifica contra ela fortificações, levanta contra ela tranqueiras e põe contra ela arraiais e aríetes em redor.

[[v26-4-3]]

^<<v26-4-3,3>>^ Toma também uma assadeira de ferro e põe-na por muro de ferro entre ti e a cidade; dirige para ela o rosto, e assim será cercada, e a cercarás; isto servirá de sinal para a casa de Israel.

[[v26-4-4]]

^<<v26-4-4,4>>^ Deita-te também sobre o teu lado esquerdo e põe a iniquidade da casa de Israel sobre ele; conforme o número dos dias que te deitares sobre ele, levarás sobre ti a iniquidade dela.

[[v26-4-5]]

^<<v26-4-5,5>>^ Porque eu te dei os anos da sua iniquidade, segundo o número dos dias, trezentos e noventa dias; e levarás sobre ti a iniquidade da casa de Israel.

[[v26-4-6]]

^<<v26-4-6,6>>^ Quando tiveres cumprido estes dias, deitar-te-ás sobre o teu lado direito e levarás sobre ti a iniquidade da casa de Judá.

[[v26-4-7]]

^<<v26-4-7,7>>^ Quarenta dias te dei, cada dia por um ano. Voltarás, pois, o rosto para o cerco de Jerusalém, com o teu braço descoberto, e profetizarás contra ela.

[[v26-4-8]]

^<<v26-4-8,8>>^ Eis que te prenderei com cordas; assim não te voltarás de um lado para o outro, até que cumpras os dias do teu cerco.

[[v26-4-9]]

^<<v26-4-9,9>>^ Toma trigo e cevada, favas e lentilhas, aveia e centeio, mete-os numa vasilha e faze deles pão; segundo o número dos dias que te deitares sobre o teu lado, trezentos e noventa dias, comerás dele.

[[v26-4-10]]

^<<v26-4-10,10>>^ A tua comida será por peso, vinte siclos por dia; de tempo em tempo, a comerás.

[[v26-4-11]]

^<<v26-4-11,11>>^ Também beberás a água por medida, a sexta parte de um him; de tempo em tempo, a beberás.

[[v26-4-12]]

^<<v26-4-12,12>>^ O que comeres será como bolos de cevada; cozê-lo-ás sobre esterco de homem, à vista do povo.

[[v26-4-13]]

^<<v26-4-13,13>>^ Disse o SENHOR: Assim comerão os filhos de Israel o seu pão imundo, entre as nações para onde os lançarei.

[[v26-4-14]]

^<<v26-4-14,14>>^ Então, disse eu: ah! SENHOR Deus! Eis que a minha alma não foi contaminada, pois, desde a minha mocidade até agora, nunca comi animal morto de si mesmo nem dilacerado por feras, nem carne abominável entrou na minha boca.

[[v26-4-15]]

^<<v26-4-15,15>>^ Então, ele me disse: Dei-te esterco de vacas, em lugar de esterco humano; sobre ele prepararás o teu pão.

[[v26-4-16]]

^<<v26-4-16,16>>^ Disse-me ainda: Filho do homem, eis que eu tirarei o sustento de pão em Jerusalém; comerão o pão por peso e, com ansiedade, beberão a água por medida e com espanto;

[[v26-4-17]]

^<<v26-4-17,17>>^ porque lhes faltará o pão e a água, espantar-se-ão uns com os outros e se consumirão nas suas iniquidades.

'''

xref:026-ezequiel/026-ezequiel-003.adoc#v26-3-0[&#60; Capítulo Anterior] | <<v26-4-0,Topo>> | xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[Próximo Capítulo &#62;]