include::./index.adoc[]

[[v26-34-0]]
=== Ezequiel, 34
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-34-1]]

^<<v26-34-1,1>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-34-2]]

^<<v26-34-2,2>>^ Filho do homem, profetiza contra os pastores de Israel; profetiza e dize-lhes: Assim diz o SENHOR Deus: Ai dos pastores de Israel que se apascentam a si mesmos! Não apascentarão os pastores as ovelhas?

[[v26-34-3]]

^<<v26-34-3,3>>^ Comeis a gordura, vestis-vos da lã e degolais o cevado; mas não apascentais as ovelhas.

[[v26-34-4]]

^<<v26-34-4,4>>^ A fraca não fortalecestes, a doente não curastes, a quebrada não ligastes, a desgarrada não tornastes a trazer e a perdida não buscastes; mas dominais sobre elas com rigor e dureza.

[[v26-34-5]]

^<<v26-34-5,5>>^ Assim, se espalharam, por não haver pastor, e se tornaram pasto para todas as feras do campo.

[[v26-34-6]]

^<<v26-34-6,6>>^ As minhas ovelhas andam desgarradas por todos os montes e por todo elevado outeiro; as minhas ovelhas andam espalhadas por toda a terra, sem haver quem as procure ou quem as busque.

[[v26-34-7]]

^<<v26-34-7,7>>^ Portanto, ó pastores, ouvi a palavra do SENHOR:

[[v26-34-8]]

^<<v26-34-8,8>>^ Tão certo como eu vivo, diz o SENHOR Deus, visto que as minhas ovelhas foram entregues à rapina e se tornaram pasto para todas as feras do campo, por não haver pastor, e que os meus pastores não procuram as minhas ovelhas, pois se apascentam a si mesmos e não apascentam as minhas ovelhas, —

[[v26-34-9]]

^<<v26-34-9,9>>^ portanto, ó pastores, ouvi a palavra do SENHOR:

[[v26-34-10]]

^<<v26-34-10,10>>^ Assim diz o SENHOR Deus: Eis que eu estou contra os pastores e deles demandarei as minhas ovelhas; porei termo no seu pastoreio, e não se apascentarão mais a si mesmos; livrarei as minhas ovelhas da sua boca, para que já não lhes sirvam de pasto.

[[v26-34-11]]

^<<v26-34-11,11>>^ Porque assim diz o SENHOR Deus: Eis que eu mesmo procurarei as minhas ovelhas e as buscarei.

[[v26-34-12]]

^<<v26-34-12,12>>^ Como o pastor busca o seu rebanho, no dia em que encontra ovelhas dispersas, assim buscarei as minhas ovelhas; livrá-las-ei de todos os lugares para onde foram espalhadas no dia de nuvens e de escuridão.

[[v26-34-13]]

^<<v26-34-13,13>>^ Tirá-las-ei dos povos, e as congregarei dos diversos países, e as introduzirei na sua terra; apascentá-las-ei nos montes de Israel, junto às correntes e em todos os lugares habitados da terra.

[[v26-34-14]]

^<<v26-34-14,14>>^ Apascentá-las-ei de bons pastos, e nos altos montes de Israel será a sua pastagem; deitar-se-ão ali em boa pastagem e terão pastos bons nos montes de Israel.

[[v26-34-15]]

^<<v26-34-15,15>>^ Eu mesmo apascentarei as minhas ovelhas e as farei repousar, diz o SENHOR Deus.

[[v26-34-16]]

^<<v26-34-16,16>>^ A perdida buscarei, a desgarrada tornarei a trazer, a quebrada ligarei e a enferma fortalecerei; mas a gorda e a forte destruirei; apascentá-las-ei com justiça.

[[v26-34-17]]

^<<v26-34-17,17>>^ Quanto a vós outras, ó ovelhas minhas, assim diz o SENHOR Deus: Eis que julgarei entre ovelhas e ovelhas, entre carneiros e bodes.

[[v26-34-18]]

^<<v26-34-18,18>>^ Acaso, não vos basta a boa pastagem? Haveis de pisar aos pés o resto do vosso pasto? E não vos basta o terdes bebido as águas claras? Haveis de turvar o resto com os pés?

[[v26-34-19]]

^<<v26-34-19,19>>^ Quanto às minhas ovelhas, elas pastam o que haveis pisado com os pés e bebem o que haveis turvado com os pés.

[[v26-34-20]]

^<<v26-34-20,20>>^ Por isso, assim lhes diz o SENHOR Deus: Eis que eu mesmo julgarei entre ovelhas gordas e ovelhas magras.

[[v26-34-21]]

^<<v26-34-21,21>>^ Visto que, com o lado e com o ombro, dais empurrões e, com os chifres, impelis as fracas até as espalhardes fora,

[[v26-34-22]]

^<<v26-34-22,22>>^ eu livrarei as minhas ovelhas, para que já não sirvam de rapina, e julgarei entre ovelhas e ovelhas.

[[v26-34-23]]

^<<v26-34-23,23>>^ Suscitarei para elas um só pastor, e ele as apascentará; o meu servo Davi é que as apascentará; ele lhes servirá de pastor.

[[v26-34-24]]

^<<v26-34-24,24>>^ Eu, o SENHOR, lhes serei por Deus, e o meu servo Davi será príncipe no meio delas; eu, o SENHOR, o disse.

[[v26-34-25]]

^<<v26-34-25,25>>^ Farei com elas aliança de paz e acabarei com as bestas-feras da terra; seguras habitarão no deserto e dormirão nos bosques.

[[v26-34-26]]

^<<v26-34-26,26>>^ Delas e dos lugares ao redor do meu outeiro, eu farei bênção; farei descer a chuva a seu tempo, serão chuvas de bênçãos.

[[v26-34-27]]

^<<v26-34-27,27>>^ As árvores do campo darão o seu fruto, e a terra dará a sua novidade, e estarão seguras na sua terra; e saberão que eu sou o SENHOR, quando eu quebrar as varas do seu jugo e as livrar das mãos dos que as escravizavam.

[[v26-34-28]]

^<<v26-34-28,28>>^ Já não servirão de rapina aos gentios, e as feras da terra nunca mais as comerão; e habitarão seguramente, e ninguém haverá que as espante.

[[v26-34-29]]

^<<v26-34-29,29>>^ Levantar-lhes-ei plantação memorável, e nunca mais serão consumidas pela fome na terra, nem mais levarão sobre si o opróbrio dos gentios.

[[v26-34-30]]

^<<v26-34-30,30>>^ Saberão, porém, que eu, o SENHOR, seu Deus, estou com elas e que elas são o meu povo, a casa de Israel, diz o SENHOR Deus.

[[v26-34-31]]

^<<v26-34-31,31>>^ Vós, pois, ó ovelhas minhas, ovelhas do meu pasto; homens sois, mas eu sou o vosso Deus, diz o SENHOR Deus.

'''

xref:026-ezequiel/026-ezequiel-033.adoc#v26-33-0[&#60; Capítulo Anterior] | <<v26-34-0,Topo>> | xref:026-ezequiel/026-ezequiel-035.adoc#v26-35-0[Próximo Capítulo &#62;]