include::./index.adoc[]

[[v26-33-0]]
=== Ezequiel, 33
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-33-1]]

^<<v26-33-1,1>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-33-2]]

^<<v26-33-2,2>>^ Filho do homem, fala aos filhos de teu povo e dize-lhes: Quando eu fizer vir a espada sobre a terra, e o povo da terra tomar um homem dos seus limites, e o constituir por seu atalaia;

[[v26-33-3]]

^<<v26-33-3,3>>^ e, vendo ele que a espada vem sobre a terra, tocar a trombeta e avisar o povo;

[[v26-33-4]]

^<<v26-33-4,4>>^ se aquele que ouvir o som da trombeta não se der por avisado, e vier a espada e o abater, o seu sangue será sobre a sua cabeça.

[[v26-33-5]]

^<<v26-33-5,5>>^ Ele ouviu o som da trombeta e não se deu por avisado; o seu sangue será sobre ele; mas o que se dá por avisado salvará a sua vida.

[[v26-33-6]]

^<<v26-33-6,6>>^ Mas, se o atalaia vir que vem a espada e não tocar a trombeta, e não for avisado o povo; se a espada vier e abater uma vida dentre eles, este foi abatido na sua iniquidade, mas o seu sangue demandarei do atalaia.

[[v26-33-7]]

^<<v26-33-7,7>>^ A ti, pois, ó filho do homem, te constituí por atalaia sobre a casa de Israel; tu, pois, ouvirás a palavra da minha boca e lhe darás aviso da minha parte.

[[v26-33-8]]

^<<v26-33-8,8>>^ Se eu disser ao perverso: Ó perverso, certamente, morrerás; e tu não falares, para avisar o perverso do seu caminho, morrerá esse perverso na sua iniquidade, mas o seu sangue eu o demandarei de ti.

[[v26-33-9]]

^<<v26-33-9,9>>^ Mas, se falares ao perverso, para o avisar do seu caminho, para que dele se converta, e ele não se converter do seu caminho, morrerá ele na sua iniquidade, mas tu livraste a tua alma.

[[v26-33-10]]

^<<v26-33-10,10>>^ Tu, pois, filho do homem, dize à casa de Israel: Assim falais vós: Visto que as nossas prevaricações e os nossos pecados estão sobre nós, e nós desfalecemos neles, como, pois, viveremos?

[[v26-33-11]]

^<<v26-33-11,11>>^ Dize-lhes: Tão certo como eu vivo, diz o SENHOR Deus, não tenho prazer na morte do perverso, mas em que o perverso se converta do seu caminho e viva. Convertei-vos, convertei-vos dos vossos maus caminhos; pois por que haveis de morrer, ó casa de Israel?

[[v26-33-12]]

^<<v26-33-12,12>>^ Tu, pois, filho do homem, dize aos filhos do teu povo: A justiça do justo não o livrará no dia da sua transgressão; quanto à perversidade do perverso, não cairá por ela, no dia em que se converter da sua perversidade; nem o justo pela justiça poderá viver no dia em que pecar.

[[v26-33-13]]

^<<v26-33-13,13>>^ Quando eu disser ao justo que, certamente, viverá, e ele, confiando na sua justiça, praticar iniquidade, não me virão à memória todas as suas justiças, mas na sua iniquidade, que pratica, ele morrerá.

[[v26-33-14]]

^<<v26-33-14,14>>^ Quando eu também disser ao perverso: Certamente, morrerás; se ele se converter do seu pecado, e fizer juízo e justiça,

[[v26-33-15]]

^<<v26-33-15,15>>^ e restituir esse perverso o penhor, e pagar o furtado, e andar nos estatutos da vida, e não praticar iniquidade, certamente, viverá; não morrerá.

[[v26-33-16]]

^<<v26-33-16,16>>^ De todos os seus pecados que cometeu não se fará memória contra ele; juízo e justiça fez; certamente, viverá.

[[v26-33-17]]

^<<v26-33-17,17>>^ Todavia, os filhos do teu povo dizem: Não é reto o caminho do Senhor; mas o próprio caminho deles é que não é reto.

[[v26-33-18]]

^<<v26-33-18,18>>^ Desviando-se o justo da sua justiça e praticando iniquidade, morrerá nela.

[[v26-33-19]]

^<<v26-33-19,19>>^ E, convertendo-se o perverso da sua perversidade e fazendo juízo e justiça, por isto mesmo viverá.

[[v26-33-20]]

^<<v26-33-20,20>>^ Todavia, vós dizeis: Não é reto o caminho do Senhor. Mas eu vos julgarei, cada um segundo os seus caminhos, ó casa de Israel.

[[v26-33-21]]

^<<v26-33-21,21>>^ No ano duodécimo do nosso exílio, aos cinco dias do décimo mês, veio a mim um que tinha escapado de Jerusalém, dizendo: Caiu a cidade.

[[v26-33-22]]

^<<v26-33-22,22>>^ Ora, a mão do SENHOR estivera sobre mim pela tarde, antes que viesse o que tinha escapado; abrira-se-me a boca antes de, pela manhã, vir ter comigo o tal homem; e, uma vez aberta, já não fiquei em silêncio.

[[v26-33-23]]

^<<v26-33-23,23>>^ Então, veio a mim a palavra do SENHOR, dizendo:

[[v26-33-24]]

^<<v26-33-24,24>>^ Filho do homem, os moradores destes lugares desertos da terra de Israel falam, dizendo: Abraão era um só; no entanto, possuiu esta terra; ora, sendo nós muitos, certamente, esta terra nos foi dada em possessão.

[[v26-33-25]]

^<<v26-33-25,25>>^ Dize-lhes, portanto: Assim diz o SENHOR Deus: Comeis a carne com sangue, levantais os olhos para os vossos ídolos e derramais sangue; porventura, haveis de possuir a terra?

[[v26-33-26]]

^<<v26-33-26,26>>^ Vós vos estribais sobre a vossa espada, cometeis abominações, e contamina cada um a mulher do seu próximo; e possuireis a terra?

[[v26-33-27]]

^<<v26-33-27,27>>^ Assim lhes dirás: Assim diz o SENHOR Deus: Tão certo como eu vivo, os que estiverem em lugares desertos cairão à espada, e o que estiver em campo aberto, o entregarei às feras, para que o devorem, e os que estiverem em fortalezas e em cavernas morrerão de peste.

[[v26-33-28]]

^<<v26-33-28,28>>^ Tornarei a terra em desolação e espanto, e será humilhado o orgulho do seu poder; os montes de Israel ficarão tão desolados, que ninguém passará por eles.

[[v26-33-29]]

^<<v26-33-29,29>>^ Então, saberão que eu sou o SENHOR, quando eu tornar a terra em desolação e espanto, por todas as abominações que cometeram.

[[v26-33-30]]

^<<v26-33-30,30>>^ Quanto a ti, ó filho do homem, os filhos do teu povo falam de ti junto aos muros e nas portas das casas; fala um com o outro, cada um a seu irmão, dizendo: Vinde, peço-vos, e ouvi qual é a palavra que procede do SENHOR.

[[v26-33-31]]

^<<v26-33-31,31>>^ Eles vêm a ti, como o povo costuma vir, e se assentam diante de ti como meu povo, e ouvem as tuas palavras, mas não as põem por obra; pois, com a boca, professam muito amor, mas o coração só ambiciona lucro.

[[v26-33-32]]

^<<v26-33-32,32>>^ Eis que tu és para eles como quem canta canções de amor, que tem voz suave e tange bem; porque ouvem as tuas palavras, mas não as põem por obra.

[[v26-33-33]]

^<<v26-33-33,33>>^ Mas, quando vier isto e aí vem, então, saberão que houve no meio deles um profeta.

'''

xref:026-ezequiel/026-ezequiel-032.adoc#v26-32-0[&#60; Capítulo Anterior] | <<v26-33-0,Topo>> | xref:026-ezequiel/026-ezequiel-034.adoc#v26-34-0[Próximo Capítulo &#62;]