include::./index.adoc[]

[[v26-31-0]]
=== Ezequiel, 31
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-31-1]]

^<<v26-31-1,1>>^ No undécimo ano, no terceiro mês, no primeiro dia do mês, veio a mim a palavra do SENHOR, dizendo:

[[v26-31-2]]

^<<v26-31-2,2>>^ Filho do homem, dize a Faraó, rei do Egito, e à multidão do seu povo: A quem és semelhante na tua grandeza?

[[v26-31-3]]

^<<v26-31-3,3>>^ Eis que a Assíria era um cedro no Líbano, de lindos ramos, de sombrosa folhagem, de grande estatura, cujo topo estava entre os ramos espessos.

[[v26-31-4]]

^<<v26-31-4,4>>^ As águas o fizeram crescer, as fontes das profundezas da terra o exalçaram e fizeram correr as torrentes no lugar em que estava plantado, enviando ribeiros para todas as árvores do campo.

[[v26-31-5]]

^<<v26-31-5,5>>^ Por isso, se elevou a sua estatura sobre todas as árvores do campo, e se multiplicaram os seus ramos, e se alongaram as suas varas, por causa das muitas águas durante o seu crescimento.

[[v26-31-6]]

^<<v26-31-6,6>>^ Todas as aves do céu se aninhavam nos seus ramos, todos os animais do campo geravam debaixo da sua fronde, e todos os grandes povos se assentavam à sua sombra.

[[v26-31-7]]

^<<v26-31-7,7>>^ Assim, era ele formoso na sua grandeza e na extensão dos seus ramos, porque a sua raiz estava junto às muitas águas.

[[v26-31-8]]

^<<v26-31-8,8>>^ Os cedros no jardim de Deus não lhe eram rivais; os ciprestes não igualavam os seus ramos, e os plátanos não tinham renovos como os seus; nenhuma árvore no jardim de Deus se assemelhava a ele na sua formosura.

[[v26-31-9]]

^<<v26-31-9,9>>^ Formoso o fiz com a multidão dos seus ramos; todas as árvores do Éden, que estavam no jardim de Deus, tiveram inveja dele.

[[v26-31-10]]

^<<v26-31-10,10>>^ Portanto, assim diz o SENHOR Deus: Como sobremaneira se elevou, e se levantou o seu topo no meio dos espessos ramos, e o seu coração se exalçou na sua altura,

[[v26-31-11]]

^<<v26-31-11,11>>^ eu o entregarei nas mãos da mais poderosa das nações, que lhe dará o tratamento segundo merece a sua perversidade; lançá-lo-ei fora.

[[v26-31-12]]

^<<v26-31-12,12>>^ Os mais terríveis estrangeiros das nações o cortaram e o deixaram; caíram os seus ramos sobre os montes e por todos os vales; os seus renovos foram quebrados por todas as correntes da terra; todos os povos da terra se retiraram da sua sombra e o deixaram.

[[v26-31-13]]

^<<v26-31-13,13>>^ Todas as aves do céu habitarão na sua ruína, e todos os animais do campo se acolherão sob os seus ramos,

[[v26-31-14]]

^<<v26-31-14,14>>^ para que todas as árvores junto às águas não se exaltem na sua estatura, nem levantem o seu topo no meio dos ramos espessos, nem as que bebem as águas venham a confiar em si, por causa da sua altura; porque todos os orgulhosos estão entregues à morte e se abismarão às profundezas da terra, no meio dos filhos dos homens, com os que descem à cova.

[[v26-31-15]]

^<<v26-31-15,15>>^ Assim diz o SENHOR Deus: No dia em que ele passou para o além, fiz eu que houvesse luto; por sua causa, cobri a profundeza da terra, retive as suas correntes, e as suas muitas águas se detiveram; cobri o Líbano de preto, por causa dele, e todas as árvores do campo desfaleceram por causa dele.

[[v26-31-16]]

^<<v26-31-16,16>>^ Ao som da sua queda, fiz tremer as nações, quando o fiz passar para o além com os que descem à cova; todas as árvores do Éden, a fina flor e o melhor do Líbano, todas as que foram regadas pelas águas se consolavam nas profundezas da terra.

[[v26-31-17]]

^<<v26-31-17,17>>^ Também estas, com ele, passarão para o além, a juntar-se aos que foram traspassados à espada; sim, aos que foram seu braço e que estavam assentados à sombra no meio das nações.

[[v26-31-18]]

^<<v26-31-18,18>>^ A quem, pois, és semelhante em glória e em grandeza entre as árvores do Éden? Todavia, descerás com as árvores do Éden às profundezas da terra; no meio dos incircuncisos, jazerás com os que foram traspassados à espada; este é Faraó e toda a sua pompa, diz o SENHOR Deus.

'''

xref:026-ezequiel/026-ezequiel-030.adoc#v26-30-0[&#60; Capítulo Anterior] | <<v26-31-0,Topo>> | xref:026-ezequiel/026-ezequiel-032.adoc#v26-32-0[Próximo Capítulo &#62;]