include::./index.adoc[]

[[v26-43-0]]
=== Ezequiel, 43
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-43-1]]

^<<v26-43-1,1>>^ Então, o homem me levou à porta, à porta que olha para o oriente.

[[v26-43-2]]

^<<v26-43-2,2>>^ E eis que, do caminho do oriente, vinha a glória do Deus de Israel; a sua voz era como o ruído de muitas águas, e a terra resplandeceu por causa da sua glória.

[[v26-43-3]]

^<<v26-43-3,3>>^ O aspecto da visão que tive era como o da visão que eu tivera, quando vim destruir a cidade; e eram as visões como a que tive junto ao rio Quebar; e me prostrei, rosto em terra.

[[v26-43-4]]

^<<v26-43-4,4>>^ A glória do SENHOR entrou no templo pela porta que olha para o oriente.

[[v26-43-5]]

^<<v26-43-5,5>>^ O Espírito me levantou e me levou ao átrio interior; e eis que a glória do SENHOR enchia o templo.

[[v26-43-6]]

^<<v26-43-6,6>>^ Então, ouvi uma voz que me foi dirigida do interior do templo, e o homem se pôs de pé junto a mim, e o SENHOR me disse:

[[v26-43-7]]

^<<v26-43-7,7>>^ Filho do homem, este é o lugar do meu trono, e o lugar das plantas dos meus pés, onde habitarei no meio dos filhos de Israel para sempre; os da casa de Israel não contaminarão mais o meu nome santo, nem eles nem os seus reis, com as suas prostituições e com o cadáver dos seus reis, nos seus monumentos,

[[v26-43-8]]

^<<v26-43-8,8>>^ pondo o seu limiar junto ao meu limiar e a sua ombreira, junto à minha ombreira, e havendo uma parede entre mim e eles. Contaminaram o meu santo nome com as suas abominações que faziam; por isso, eu os consumi na minha ira.

[[v26-43-9]]

^<<v26-43-9,9>>^ Agora, lancem eles para longe de mim a sua prostituição e o cadáver dos seus reis, e habitarei no meio deles para sempre.

[[v26-43-10]]

^<<v26-43-10,10>>^ Tu, pois, ó filho do homem, mostra à casa de Israel este templo, para que ela se envergonhe das suas iniquidades; e meça o modelo.

[[v26-43-11]]

^<<v26-43-11,11>>^ Envergonhando-se eles de tudo quanto praticaram, faze-lhes saber a planta desta casa e o seu arranjo, as suas saídas, as suas entradas e todas as suas formas; todos os seus estatutos, todos os seus dispositivos e todas as suas leis; escreve isto na sua presença para que observem todas as suas instituições e todos os seus estatutos e os cumpram.

[[v26-43-12]]

^<<v26-43-12,12>>^ Esta é a lei do templo; sobre o cimo do monte, todo o seu limite ao redor será santíssimo; eis que esta é a lei do templo.

[[v26-43-13]]

^<<v26-43-13,13>>^ São estas as medidas do altar, em côvados, sendo o côvado de côvado comum e quatro dedos; a base será de um côvado de altura e um côvado de largura, e a sua borda, em todo o seu contorno, de quatro dedos; esta é a base do altar.

[[v26-43-14]]

^<<v26-43-14,14>>^ Da base, na linha da terra, até à fiada do fundo, dois côvados, e de largura, um côvado; da fiada pequena até à fiada grande, quatro côvados, e a largura, um côvado.

[[v26-43-15]]

^<<v26-43-15,15>>^ A lareira, de quatro côvados de altura; da lareira para cima se projetarão quatro chifres.

[[v26-43-16]]

^<<v26-43-16,16>>^ A lareira terá doze côvados de comprimento e doze de largura, quadrada nos quatro lados.

[[v26-43-17]]

^<<v26-43-17,17>>^ A fiada terá catorze côvados de comprimento e catorze de largura, nos seus quatro lados; a borda ao redor dela, de meio côvado; e a base ao redor do altar se projetará um côvado; os seus degraus olharão para o oriente.

[[v26-43-18]]

^<<v26-43-18,18>>^ E o SENHOR me disse: Filho do homem, assim diz o SENHOR Deus: São estas as determinações do altar, no dia em que o farão, para oferecerem sobre ele holocausto e para sobre ele aspergirem sangue.

[[v26-43-19]]

^<<v26-43-19,19>>^ Aos sacerdotes levitas, que são da descendência de Zadoque, que se chegam a mim, diz o SENHOR Deus, para me servirem, darás um novilho para oferta pelo pecado.

[[v26-43-20]]

^<<v26-43-20,20>>^ Tomarás do seu sangue e o porás sobre os quatro chifres do altar, e nos quatro cantos da fiada, e na borda ao redor; assim, farás a purificação e a expiação.

[[v26-43-21]]

^<<v26-43-21,21>>^ Então, tomarás o novilho da oferta pelo pecado, o qual será queimado no lugar da casa para isso designado, fora do santuário.

[[v26-43-22]]

^<<v26-43-22,22>>^ No segundo dia, oferecerás um bode sem defeito, oferta pelo pecado; e purificarão o altar, como o purificaram com o novilho.

[[v26-43-23]]

^<<v26-43-23,23>>^ Acabando tu de o purificar, oferecerás um novilho sem defeito e, do rebanho, um carneiro sem defeito.

[[v26-43-24]]

^<<v26-43-24,24>>^ Oferecê-los-ás perante o SENHOR; os sacerdotes deitarão sal sobre eles e os oferecerão em holocausto ao SENHOR.

[[v26-43-25]]

^<<v26-43-25,25>>^ Durante sete dias, prepararás cada dia um bode para oferta pelo pecado; também prepararão um novilho e, do rebanho, um carneiro sem defeito.

[[v26-43-26]]

^<<v26-43-26,26>>^ Por sete dias, expiarão o altar e o purificarão; e, assim, o consagrarão.

[[v26-43-27]]

^<<v26-43-27,27>>^ Tendo eles cumprido estes dias, será que, ao oitavo dia, dali em diante, prepararão os sacerdotes sobre o altar os vossos holocaustos e as vossas ofertas pacíficas; e eu vos serei propício, diz o SENHOR Deus.

'''

xref:026-ezequiel/026-ezequiel-042.adoc#v26-42-0[&#60; Capítulo Anterior] | <<v26-43-0,Topo>> | xref:026-ezequiel/026-ezequiel-044.adoc#v26-44-0[Próximo Capítulo &#62;]