include::./index.adoc[]

[[v26-10-0]]
=== Ezequiel, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-10-1]]

^<<v26-10-1,1>>^ Olhei, e eis que, no firmamento que estava por cima da cabeça dos querubins, apareceu sobre eles uma como pedra de safira semelhando a forma de um trono.

[[v26-10-2]]

^<<v26-10-2,2>>^ E falou ao homem vestido de linho, dizendo: Vai por entre as rodas, até debaixo dos querubins, e enche as mãos de brasas acesas dentre os querubins, e espalha-as sobre a cidade. Ele entrou à minha vista.

[[v26-10-3]]

^<<v26-10-3,3>>^ Os querubins estavam ao lado direito da casa, quando entrou o homem; e a nuvem encheu o átrio interior.

[[v26-10-4]]

^<<v26-10-4,4>>^ Então, se levantou a glória do SENHOR de sobre o querubim, indo para a entrada da casa; a casa encheu-se da nuvem, e o átrio, da resplandecência da glória do SENHOR.

[[v26-10-5]]

^<<v26-10-5,5>>^ O tatalar das asas dos querubins se ouviu até ao átrio exterior, como a voz do Deus Todo-Poderoso, quando fala.

[[v26-10-6]]

^<<v26-10-6,6>>^ Tendo o SENHOR dado ordem ao homem vestido de linho, dizendo: Toma fogo dentre as rodas, dentre os querubins, ele entrou e se pôs junto às rodas.

[[v26-10-7]]

^<<v26-10-7,7>>^ Então, estendeu um querubim a mão de entre os querubins para o fogo que estava entre os querubins; tomou dele e o pôs nas mãos do homem que estava vestido de linho, o qual o tomou e saiu.

[[v26-10-8]]

^<<v26-10-8,8>>^ Tinham os querubins uma semelhança de mão de homem debaixo das suas asas.

[[v26-10-9]]

^<<v26-10-9,9>>^ Olhei, e eis quatro rodas junto aos querubins, uma roda junto a cada querubim; o aspecto das rodas era brilhante como pedra de berilo.

[[v26-10-10]]

^<<v26-10-10,10>>^ Quanto ao seu aspecto, tinham as quatro a mesma aparência; eram como se estivesse uma roda dentro da outra.

[[v26-10-11]]

^<<v26-10-11,11>>^ Andando elas, podiam ir em quatro direções e não se viravam quando iam; para onde ia a primeira, seguiam as outras e não se viravam quando iam.

[[v26-10-12]]

^<<v26-10-12,12>>^ Todo o corpo dos querubins, suas costas, as mãos, as asas e também as rodas que os quatro tinham estavam cheias de olhos ao redor.

[[v26-10-13]]

^<<v26-10-13,13>>^ Quanto às rodas, foram elas chamadas girantes, ouvindo-o eu.

[[v26-10-14]]

^<<v26-10-14,14>>^ Cada um dos seres viventes tinha quatro rostos: o rosto do primeiro era rosto de querubim, o do segundo, rosto de homem, o do terceiro, rosto de leão, e o do quarto, rosto de águia.

[[v26-10-15]]

^<<v26-10-15,15>>^ Os querubins se elevaram. São estes os mesmos seres viventes que vi junto ao rio Quebar.

[[v26-10-16]]

^<<v26-10-16,16>>^ Andando os querubins, andavam as rodas juntamente com eles; e, levantando os querubins as suas asas, para se elevarem de sobre a terra, as rodas não se separavam deles.

[[v26-10-17]]

^<<v26-10-17,17>>^ Parando eles, paravam elas; e, elevando-se eles, elevavam-se elas, porque o espírito dos seres viventes estava nelas.

[[v26-10-18]]

^<<v26-10-18,18>>^ Então, saiu a glória do SENHOR da entrada da casa e parou sobre os querubins.

[[v26-10-19]]

^<<v26-10-19,19>>^ Os querubins levantaram as suas asas e se elevaram da terra à minha vista, quando saíram acompanhados pelas rodas; pararam à entrada da porta oriental da Casa do SENHOR, e a glória do Deus de Israel estava no alto, sobre eles.

[[v26-10-20]]

^<<v26-10-20,20>>^ São estes os seres viventes que vi debaixo do Deus de Israel, junto ao rio Quebar, e fiquei sabendo que eram querubins.

[[v26-10-21]]

^<<v26-10-21,21>>^ Cada um tinha quatro rostos e quatro asas e a semelhança de mãos de homem debaixo das asas.

[[v26-10-22]]

^<<v26-10-22,22>>^ A aparência dos seus rostos era como a dos rostos que eu vira junto ao rio Quebar; tinham o mesmo aspecto, eram os mesmos seres. Cada qual andava para a sua frente.

'''

xref:026-ezequiel/026-ezequiel-009.adoc#v26-9-0[&#60; Capítulo Anterior] | <<v26-10-0,Topo>> | xref:026-ezequiel/026-ezequiel-011.adoc#v26-11-0[Próximo Capítulo &#62;]