include::./index.adoc[]

[[v26-27-0]]
=== Ezequiel, 27
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-27-1]]

^<<v26-27-1,1>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-27-2]]

^<<v26-27-2,2>>^ Tu, pois, ó filho do homem, levanta lamentação sobre Tiro;

[[v26-27-3]]

^<<v26-27-3,3>>^ dize a Tiro, que habita nas entradas do mar e negocia com os povos em muitas terras do mar: Assim diz o SENHOR Deus: Ó Tiro, tu dizes: Eu sou perfeita em formosura.

[[v26-27-4]]

^<<v26-27-4,4>>^ No coração dos mares, estão os teus limites; os que te edificaram aperfeiçoaram a tua formosura.

[[v26-27-5]]

^<<v26-27-5,5>>^ Fabricaram todos os teus conveses de ciprestes de Senir; trouxeram cedros do Líbano, para te fazerem mastros.

[[v26-27-6]]

^<<v26-27-6,6>>^ Fizeram os teus remos de carvalhos de Basã; os teus bancos, fizeram-nos de marfim engastado em pinho das ilhas dos quiteus.

[[v26-27-7]]

^<<v26-27-7,7>>^ De linho fino bordado do Egito era a tua vela, para servir de estandarte; azul e púrpura das ilhas de Elisá eram o teu toldo.

[[v26-27-8]]

^<<v26-27-8,8>>^ Os moradores de Sidom e de Arvade foram os teus remeiros; os teus sábios, ó Tiro, que se achavam em ti, esses foram os teus pilotos.

[[v26-27-9]]

^<<v26-27-9,9>>^ Os anciãos de Gebal e os seus sábios foram em ti os teus calafates; todos os navios do mar e os marinheiros se acharam em ti, para trocar as tuas mercadorias.

[[v26-27-10]]

^<<v26-27-10,10>>^ Os persas, os lídios e os de Pute se acharam em teu exército e eram teus homens de guerra; escudos e capacetes penduraram em ti; manifestaram a tua glória.

[[v26-27-11]]

^<<v26-27-11,11>>^ Os filhos de Arvade e o teu exército estavam sobre os teus muros em redor, e os gamaditas, nas torres; penduravam os seus escudos nos teus muros em redor; aperfeiçoavam a tua formosura.

[[v26-27-12]]

^<<v26-27-12,12>>^ Társis negociava contigo, por causa da abundância de toda sorte de riquezas; trocavam por tuas mercadorias prata, ferro, estanho e chumbo.

[[v26-27-13]]

^<<v26-27-13,13>>^ Javã, Tubal e Meseque eram os teus mercadores; em troca das tuas mercadorias, davam escravos e objetos de bronze.

[[v26-27-14]]

^<<v26-27-14,14>>^ Os da casa de Togarma, em troca das tuas mercadorias, davam cavalos, ginetes e mulos.

[[v26-27-15]]

^<<v26-27-15,15>>^ Os filhos de Dedã eram os teus mercadores; muitas terras do mar eram o mercado das tuas manufaturas; em troca, traziam dentes de marfim e madeira de ébano.

[[v26-27-16]]

^<<v26-27-16,16>>^ A Síria negociava contigo por causa da multidão das tuas manufaturas; por tuas mercadorias, eles davam esmeralda, púrpura, obras bordadas, linho fino, coral e pedras preciosas.

[[v26-27-17]]

^<<v26-27-17,17>>^ Judá e a terra de Israel eram os teus mercadores; pelas tuas mercadorias, trocavam o trigo de Minite, confeitos, mel, azeite e bálsamo.

[[v26-27-18]]

^<<v26-27-18,18>>^ Damasco negociava contigo, por causa da multidão das tuas manufaturas, por causa da abundância de toda sorte de riquezas, dando em troca vinho de Helbom e lã de Saar.

[[v26-27-19]]

^<<v26-27-19,19>>^ Também Dã e Javã, de Uzal, pelas tuas mercadorias, davam em troca ferro trabalhado, cássia e cálamo, que assim entravam no teu comércio.

[[v26-27-20]]

^<<v26-27-20,20>>^ Dedã negociava contigo com baixeiros para cavalgaduras.

[[v26-27-21]]

^<<v26-27-21,21>>^ A Arábia e todos os príncipes de Quedar eram mercadores ao teu serviço; negociavam contigo com cordeiros, carneiros e bodes; nisto, negociavam contigo.

[[v26-27-22]]

^<<v26-27-22,22>>^ Os mercadores de Sabá e Raamá eram os teus mercadores; pelas tuas mercadorias, davam em troca os mais finos aromas, pedras preciosas e ouro.

[[v26-27-23]]

^<<v26-27-23,23>>^ Harã, Cane e Éden, mercadores de Sabá, Assíria e Quilmade negociavam contigo.

[[v26-27-24]]

^<<v26-27-24,24>>^ Estes eram teus mercadores em toda sorte de mercadorias, em pano de púrpura e bordados, tapetes de várias cores e cordas trançadas e fortes.

[[v26-27-25]]

^<<v26-27-25,25>>^ Os navios de Társis eram as tuas caravanas para as tuas mercadorias; e te enriqueceste e ficaste mui famosa no coração dos mares.

[[v26-27-26]]

^<<v26-27-26,26>>^ Os teus remeiros te conduziram sobre grandes águas; o vento oriental te quebrou no coração dos mares.

[[v26-27-27]]

^<<v26-27-27,27>>^ As tuas riquezas, as tuas mercadorias, os teus bens, os teus marinheiros, os teus pilotos, os calafates, os que faziam os teus negócios e todos os teus soldados que estão em ti, juntamente com toda a multidão do povo que está no meio de ti, se afundarão no coração dos mares no dia da tua ruína.

[[v26-27-28]]

^<<v26-27-28,28>>^ Ao estrondo da gritaria dos teus pilotos, tremerão as praias.

[[v26-27-29]]

^<<v26-27-29,29>>^ Todos os que pegam no remo, os marinheiros, e todos os pilotos do mar descerão de seus navios e pararão em terra;

[[v26-27-30]]

^<<v26-27-30,30>>^ farão ouvir a sua voz sobre ti e gritarão amargamente; lançarão pó sobre a cabeça e na cinza se revolverão;

[[v26-27-31]]

^<<v26-27-31,31>>^ far-se-ão calvos por tua causa, cingir-se-ão de pano de saco e chorarão sobre ti, com amargura de alma, com amargura e lamentação.

[[v26-27-32]]

^<<v26-27-32,32>>^ Levantarão lamentações sobre ti no seu pranto, lamentarão sobre ti, dizendo: Quem foi como Tiro, como a que está reduzida ao silêncio no meio do mar?

[[v26-27-33]]

^<<v26-27-33,33>>^ Quando as tuas mercadorias eram exportadas pelos mares, fartaste a muitos povos; com a multidão da tua riqueza e do teu negócio, enriqueceste os reis da terra.

[[v26-27-34]]

^<<v26-27-34,34>>^ No tempo em que foste quebrada nos mares, nas profundezas das águas se afundaram os teus negócios e toda a tua multidão, no meio de ti.

[[v26-27-35]]

^<<v26-27-35,35>>^ Todos os moradores das terras dos mares se espantam por tua causa; os seus reis tremem sobremaneira e estão de rosto perturbado.

[[v26-27-36]]

^<<v26-27-36,36>>^ Os mercadores dentre os povos assobiam contra ti; vens a ser objeto de espanto e jamais subsistirás.

'''

xref:026-ezequiel/026-ezequiel-026.adoc#v26-26-0[&#60; Capítulo Anterior] | <<v26-27-0,Topo>> | xref:026-ezequiel/026-ezequiel-028.adoc#v26-28-0[Próximo Capítulo &#62;]