include::./index.adoc[]

[[v26-18-0]]
=== Ezequiel, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-18-1]]

^<<v26-18-1,1>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-18-2]]

^<<v26-18-2,2>>^ Que tendes vós, vós que, acerca da terra de Israel, proferis este provérbio, dizendo: Os pais comeram uvas verdes, e os dentes dos filhos é que se embotaram?

[[v26-18-3]]

^<<v26-18-3,3>>^ Tão certo como eu vivo, diz o SENHOR Deus, jamais direis este provérbio em Israel.

[[v26-18-4]]

^<<v26-18-4,4>>^ Eis que todas as almas são minhas; como a alma do pai, também a alma do filho é minha; a alma que pecar, essa morrerá.

[[v26-18-5]]

^<<v26-18-5,5>>^ Sendo, pois, o homem justo e fazendo juízo e justiça,

[[v26-18-6]]

^<<v26-18-6,6>>^ não comendo carne sacrificada nos altos, nem levantando os olhos para os ídolos da casa de Israel, nem contaminando a mulher do seu próximo, nem se chegando à mulher na sua menstruação;

[[v26-18-7]]

^<<v26-18-7,7>>^ não oprimindo a ninguém, tornando ao devedor a coisa penhorada, não roubando, dando o seu pão ao faminto e cobrindo ao nu com vestes;

[[v26-18-8]]

^<<v26-18-8,8>>^ não dando o seu dinheiro à usura, não recebendo juros, desviando a sua mão da injustiça e fazendo verdadeiro juízo entre homem e homem;

[[v26-18-9]]

^<<v26-18-9,9>>^ andando nos meus estatutos, guardando os meus juízos e procedendo retamente, o tal justo, certamente, viverá, diz o SENHOR Deus.

[[v26-18-10]]

^<<v26-18-10,10>>^ Se ele gerar um filho ladrão, derramador de sangue, que fizer a seu irmão qualquer destas coisas

[[v26-18-11]]

^<<v26-18-11,11>>^ e não cumprir todos aqueles deveres, mas, antes, comer carne sacrificada nos altos, contaminar a mulher de seu próximo,

[[v26-18-12]]

^<<v26-18-12,12>>^ oprimir ao pobre e necessitado, praticar roubos, não tornar o penhor, levantar os olhos para os ídolos, cometer abominação,

[[v26-18-13]]

^<<v26-18-13,13>>^ emprestar com usura e receber juros, porventura, viverá? Não viverá. Todas estas abominações ele fez e será morto; o seu sangue será sobre ele.

[[v26-18-14]]

^<<v26-18-14,14>>^ Eis que, se ele gerar um filho que veja todos os pecados que seu pai fez, e, vendo-os, não cometer coisas semelhantes,

[[v26-18-15]]

^<<v26-18-15,15>>^ não comer carne sacrificada nos altos, não levantar os olhos para os ídolos da casa de Israel e não contaminar a mulher de seu próximo;

[[v26-18-16]]

^<<v26-18-16,16>>^ não oprimir a ninguém, não retiver o penhor, não roubar, der o seu pão ao faminto, cobrir ao nu com vestes;

[[v26-18-17]]

^<<v26-18-17,17>>^ desviar do pobre a mão, não receber usura e juros, fizer os meus juízos e andar nos meus estatutos, o tal não morrerá pela iniquidade de seu pai; certamente, viverá.

[[v26-18-18]]

^<<v26-18-18,18>>^ Quanto a seu pai, porque praticou extorsão, roubou os bens do próximo e fez o que não era bom no meio de seu povo, eis que ele morrerá por causa de sua iniquidade.

[[v26-18-19]]

^<<v26-18-19,19>>^ Mas dizeis: Por que não leva o filho a iniquidade do pai? Porque o filho fez o que era reto e justo, e guardou todos os meus estatutos, e os praticou, por isso, certamente, viverá.

[[v26-18-20]]

^<<v26-18-20,20>>^ A alma que pecar, essa morrerá; o filho não levará a iniquidade do pai, nem o pai, a iniquidade do filho; a justiça do justo ficará sobre ele, e a perversidade do perverso cairá sobre este.

[[v26-18-21]]

^<<v26-18-21,21>>^ Mas, se o perverso se converter de todos os pecados que cometeu, e guardar todos os meus estatutos, e fizer o que é reto e justo, certamente, viverá; não será morto.

[[v26-18-22]]

^<<v26-18-22,22>>^ De todas as transgressões que cometeu não haverá lembrança contra ele; pela justiça que praticou, viverá.

[[v26-18-23]]

^<<v26-18-23,23>>^ Acaso, tenho eu prazer na morte do perverso? — diz o SENHOR Deus; não desejo eu, antes, que ele se converta dos seus caminhos e viva?

[[v26-18-24]]

^<<v26-18-24,24>>^ Mas, desviando-se o justo da sua justiça e cometendo iniquidade, fazendo segundo todas as abominações que faz o perverso, acaso, viverá? De todos os atos de justiça que tiver praticado não se fará memória; na sua transgressão com que transgrediu e no seu pecado que cometeu, neles morrerá.

[[v26-18-25]]

^<<v26-18-25,25>>^ No entanto, dizeis: O caminho do Senhor não é direito. Ouvi, agora, ó casa de Israel: Não é o meu caminho direito? Não são os vossos caminhos tortuosos?

[[v26-18-26]]

^<<v26-18-26,26>>^ Desviando-se o justo da sua justiça e cometendo iniquidade, morrerá por causa dela; na iniquidade que cometeu, morrerá.

[[v26-18-27]]

^<<v26-18-27,27>>^ Mas, convertendo-se o perverso da perversidade que cometeu e praticando o que é reto e justo, conservará ele a sua alma em vida.

[[v26-18-28]]

^<<v26-18-28,28>>^ Pois se considera e se converte de todas as transgressões que cometeu, certamente, viverá; não será morto.

[[v26-18-29]]

^<<v26-18-29,29>>^ No entanto, diz a casa de Israel: O caminho do Senhor não é direito. Não são os meus caminhos direitos, ó casa de Israel? E não são os vossos caminhos tortuosos?

[[v26-18-30]]

^<<v26-18-30,30>>^ Portanto, eu vos julgarei, a cada um segundo os seus caminhos, ó casa de Israel, diz o SENHOR Deus. Convertei-vos e desviai-vos de todas as vossas transgressões; e a iniquidade não vos servirá de tropeço.

[[v26-18-31]]

^<<v26-18-31,31>>^ Lançai de vós todas as vossas transgressões com que transgredistes e criai em vós coração novo e espírito novo; pois, por que morreríeis, ó casa de Israel?

[[v26-18-32]]

^<<v26-18-32,32>>^ Porque não tenho prazer na morte de ninguém, diz o SENHOR Deus. Portanto, convertei-vos e vivei.

'''

xref:026-ezequiel/026-ezequiel-017.adoc#v26-17-0[&#60; Capítulo Anterior] | <<v26-18-0,Topo>> | xref:026-ezequiel/026-ezequiel-019.adoc#v26-19-0[Próximo Capítulo &#62;]