include::./index.adoc[]

[[v26-22-0]]
=== Ezequiel, 22
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-22-1]]

^<<v26-22-1,1>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-22-2]]

^<<v26-22-2,2>>^ Tu, pois, ó filho do homem, acaso, julgarás, julgarás a cidade sanguinária? Faze-lhe conhecer, pois, todas as suas abominações

[[v26-22-3]]

^<<v26-22-3,3>>^ e dize: Assim diz o SENHOR Deus: Ai da cidade que derrama sangue no meio de si, para que venha o seu tempo, e que faz ídolos contra si mesma, para se contaminar!

[[v26-22-4]]

^<<v26-22-4,4>>^ Pelo teu sangue, por ti mesma derramado, tu te fizeste culpada e pelos teus ídolos, por ti mesma fabricados, tu te contaminaste e fizeste chegar o dia do teu julgamento e o término de teus anos; por isso, eu te fiz objeto de opróbrio das nações e de escárnio de todas as terras.

[[v26-22-5]]

^<<v26-22-5,5>>^ As que estão perto de ti e as que estão longe escarnecerão de ti, ó infamada, cheia de inquietação.

[[v26-22-6]]

^<<v26-22-6,6>>^ Eis que os príncipes de Israel, cada um segundo o seu poder, nada mais intentam, senão derramar sangue.

[[v26-22-7]]

^<<v26-22-7,7>>^ No meio de ti, desprezam o pai e a mãe, praticam extorsões contra o estrangeiro e são injustos para com o órfão e a viúva.

[[v26-22-8]]

^<<v26-22-8,8>>^ Desprezaste as minhas coisas santas e profanaste os meus sábados.

[[v26-22-9]]

^<<v26-22-9,9>>^ Homens caluniadores se acham no meio de ti, para derramarem sangue; no meio de ti, comem carne sacrificada nos montes e cometem perversidade.

[[v26-22-10]]

^<<v26-22-10,10>>^ No teu meio, descobrem a vergonha de seu pai e abusam da mulher no prazo da sua menstruação.

[[v26-22-11]]

^<<v26-22-11,11>>^ Um comete abominação com a mulher do seu próximo, outro contamina torpemente a sua nora, e outro humilha no meio de ti a sua irmã, filha de seu pai.

[[v26-22-12]]

^<<v26-22-12,12>>^ No meio de ti, aceitam subornos para se derramar sangue; usura e lucros tomaste, extorquindo-o; exploraste o teu próximo com extorsão; mas de mim te esqueceste, diz o SENHOR Deus.

[[v26-22-13]]

^<<v26-22-13,13>>^ Eis que bato as minhas palmas com furor contra a exploração que praticaste e por causa da tua culpa de sangue, que há no meio de ti. Estará firme o teu coração?

[[v26-22-14]]

^<<v26-22-14,14>>^ Estarão fortes as tuas mãos, nos dias em que eu vier a tratar contigo? Eu, o SENHOR, o disse e o farei.

[[v26-22-15]]

^<<v26-22-15,15>>^ Espalhar-te-ei entre as nações, e te dispersarei em outras terras, e porei termo à tua imundícia.

[[v26-22-16]]

^<<v26-22-16,16>>^ Serás profanada em ti mesma, à vista das nações, e saberás que eu sou o SENHOR.

[[v26-22-17]]

^<<v26-22-17,17>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-22-18]]

^<<v26-22-18,18>>^ Filho do homem, a casa de Israel se tornou para mim em escória; todos eles são cobre, estanho, ferro e chumbo no meio do forno; em escória de prata se tornaram.

[[v26-22-19]]

^<<v26-22-19,19>>^ Portanto, assim diz o SENHOR Deus: Pois que todos vós vos tornastes em escória, eis que vos ajuntarei no meio de Jerusalém.

[[v26-22-20]]

^<<v26-22-20,20>>^ Como se ajuntam a prata, e o cobre, e o ferro, e o chumbo, e o estanho no meio do forno, para assoprar o fogo sobre eles, a fim de se fundirem, assim vos ajuntarei na minha ira e no meu furor, e ali vos deixarei, e fundirei.

[[v26-22-21]]

^<<v26-22-21,21>>^ Congregar-vos-ei e assoprarei sobre vós o fogo do meu furor; e sereis fundidos no meio de Jerusalém.

[[v26-22-22]]

^<<v26-22-22,22>>^ Como se funde a prata no meio do forno, assim sereis fundidos no meio dela; e sabereis que eu, o SENHOR, derramei o meu furor sobre vós.

[[v26-22-23]]

^<<v26-22-23,23>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-22-24]]

^<<v26-22-24,24>>^ Filho do homem, dize-lhe: Tu és terra que não está purificada e que não tem chuva no dia da indignação.

[[v26-22-25]]

^<<v26-22-25,25>>^ Conspiração dos seus profetas há no meio dela; como um leão que ruge, que arrebata a presa, assim eles devoram as almas; tesouros e coisas preciosas tomam, multiplicam as suas viúvas no meio dela.

[[v26-22-26]]

^<<v26-22-26,26>>^ Os seus sacerdotes transgridem a minha lei e profanam as minhas coisas santas; entre o santo e o profano, não fazem diferença, nem discernem o imundo do limpo e dos meus sábados escondem os olhos; e, assim, sou profanado no meio deles.

[[v26-22-27]]

^<<v26-22-27,27>>^ Os seus príncipes no meio dela são como lobos que arrebatam a presa para derramarem o sangue, para destruírem as almas e ganharem lucro desonesto.

[[v26-22-28]]

^<<v26-22-28,28>>^ Os seus profetas lhes encobrem isto com cal por visões falsas, predizendo mentiras e dizendo: Assim diz o SENHOR Deus, sem que o SENHOR tenha falado.

[[v26-22-29]]

^<<v26-22-29,29>>^ Contra o povo da terra praticam extorsão, andam roubando, fazem violência ao aflito e ao necessitado e ao estrangeiro oprimem sem razão.

[[v26-22-30]]

^<<v26-22-30,30>>^ Busquei entre eles um homem que tapasse o muro e se colocasse na brecha perante mim, a favor desta terra, para que eu não a destruísse; mas a ninguém achei.

[[v26-22-31]]

^<<v26-22-31,31>>^ Por isso, eu derramei sobre eles a minha indignação, com o fogo do meu furor os consumi; fiz cair-lhes sobre a cabeça o castigo do seu procedimento, diz o SENHOR Deus.

'''

xref:026-ezequiel/026-ezequiel-021.adoc#v26-21-0[&#60; Capítulo Anterior] | <<v26-22-0,Topo>> | xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[Próximo Capítulo &#62;]