include::./index.adoc[]

[[v26-39-0]]
=== Ezequiel, 39
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-39-1]]

^<<v26-39-1,1>>^ Tu, pois, ó filho do homem, profetiza ainda contra Gogue e dize: Assim diz o SENHOR Deus: Eis que eu sou contra ti, ó Gogue, príncipe de Rôs, de Meseque e Tubal.

[[v26-39-2]]

^<<v26-39-2,2>>^ Far-te-ei que te volvas e te conduzirei, far-te-ei subir dos lados do Norte e te trarei aos montes de Israel.

[[v26-39-3]]

^<<v26-39-3,3>>^ Tirarei o teu arco da tua mão esquerda e farei cair as tuas flechas da tua mão direita.

[[v26-39-4]]

^<<v26-39-4,4>>^ Nos montes de Israel, cairás, tu, e todas as tuas tropas, e os povos que estão contigo; a toda espécie de aves de rapina e aos animais do campo eu te darei, para que te devorem.

[[v26-39-5]]

^<<v26-39-5,5>>^ Cairás em campo aberto, porque eu falei, diz o SENHOR Deus.

[[v26-39-6]]

^<<v26-39-6,6>>^ Meterei fogo em Magogue e nos que habitam seguros nas terras do mar; e saberão que eu sou o SENHOR.

[[v26-39-7]]

^<<v26-39-7,7>>^ Farei conhecido o meu santo nome no meio do meu povo de Israel e nunca mais deixarei profanar o meu santo nome; e as nações saberão que eu sou o SENHOR, o Santo em Israel.

[[v26-39-8]]

^<<v26-39-8,8>>^ Eis que vem e se cumprirá, diz o SENHOR Deus; este é o dia de que tenho falado.

[[v26-39-9]]

^<<v26-39-9,9>>^ Os habitantes das cidades de Israel sairão e queimarão, de todo, as armas, os escudos, os paveses, os arcos, as flechas, os bastões de mão e as lanças; farão fogo com tudo isto por sete anos.

[[v26-39-10]]

^<<v26-39-10,10>>^ Não trarão lenha do campo, nem a cortarão dos bosques, mas com as armas acenderão fogo; saquearão aos que os saquearam e despojarão aos que os despojaram, diz o SENHOR Deus.

[[v26-39-11]]

^<<v26-39-11,11>>^ Naquele dia, darei ali a Gogue um lugar de sepultura em Israel, o vale dos Viajantes, ao oriente do mar; espantar-se-ão os que por ele passarem. Nele, sepultarão a Gogue e a todas as suas forças e lhe chamarão o vale das Forças de Gogue.

[[v26-39-12]]

^<<v26-39-12,12>>^ Durante sete meses, estará a casa de Israel a sepultá-los, para limpar a terra.

[[v26-39-13]]

^<<v26-39-13,13>>^ Sim, todo o povo da terra os sepultará; ser-lhes-á memorável o dia em que eu for glorificado, diz o SENHOR Deus.

[[v26-39-14]]

^<<v26-39-14,14>>^ Serão separados homens que, sem cessar, percorrerão a terra para sepultar os que entre os transeuntes tenham ficado nela, para a limpar; depois de sete meses, iniciarão a busca.

[[v26-39-15]]

^<<v26-39-15,15>>^ Ao percorrerem eles a terra, a qual atravessarão, em vendo algum deles o osso de algum homem, porá ao lado um sinal, até que os enterradores o sepultem no vale das Forças de Gogue.

[[v26-39-16]]

^<<v26-39-16,16>>^ Também o nome da cidade será o das Forças. Assim, limparão a terra.

[[v26-39-17]]

^<<v26-39-17,17>>^ Tu, pois, ó filho do homem, assim diz o SENHOR Deus: Dize às aves de toda espécie e a todos os animais do campo: Ajuntai-vos e vinde, ajuntai-vos de toda parte para o meu sacrifício, que eu oferecerei por vós, sacrifício grande nos montes de Israel; e comereis carne e bebereis sangue.

[[v26-39-18]]

^<<v26-39-18,18>>^ Comereis a carne dos poderosos e bebereis o sangue dos príncipes da terra, dos carneiros, dos cordeiros, dos bodes e dos novilhos, todos engordados em Basã.

[[v26-39-19]]

^<<v26-39-19,19>>^ Do meu sacrifício, que oferecerei por vós, comereis a gordura até vos fartardes e bebereis o sangue até vos embriagardes.

[[v26-39-20]]

^<<v26-39-20,20>>^ À minha mesa, vós vos fartareis de cavalos e de cavaleiros, de valentes e de todos os homens de guerra, diz o SENHOR Deus.

[[v26-39-21]]

^<<v26-39-21,21>>^ Manifestarei a minha glória entre as nações, e todas as nações verão o meu juízo, que eu tiver executado, e a minha mão, que sobre elas tiver descarregado.

[[v26-39-22]]

^<<v26-39-22,22>>^ Desse dia em diante, os da casa de Israel saberão que eu sou o SENHOR, seu Deus.

[[v26-39-23]]

^<<v26-39-23,23>>^ Saberão as nações que os da casa de Israel, por causa da sua iniquidade, foram levados para o exílio, porque agiram perfidamente contra mim, e eu escondi deles o rosto, e os entreguei nas mãos de seus adversários, e todos eles caíram à espada.

[[v26-39-24]]

^<<v26-39-24,24>>^ Segundo a sua imundícia e as suas transgressões, assim me houve com eles e escondi deles o rosto.

[[v26-39-25]]

^<<v26-39-25,25>>^ Portanto, assim diz o SENHOR Deus: Agora, tornarei a mudar a sorte de Jacó e me compadecerei de toda a casa de Israel; terei zelo pelo meu santo nome.

[[v26-39-26]]

^<<v26-39-26,26>>^ Esquecerão a sua vergonha e toda a perfídia com que se rebelaram contra mim, quando eles habitarem seguros na sua terra, sem haver quem os espante,

[[v26-39-27]]

^<<v26-39-27,27>>^ quando eu tornar a trazê-los de entre os povos, e os houver ajuntado das terras de seus inimigos, e tiver vindicado neles a minha santidade perante muitas nações.

[[v26-39-28]]

^<<v26-39-28,28>>^ Saberão que eu sou o SENHOR, seu Deus, quando virem que eu os fiz ir para o cativeiro entre as nações, e os tornei a ajuntar para voltarem à sua terra, e que lá não deixarei a nenhum deles.

[[v26-39-29]]

^<<v26-39-29,29>>^ Já não esconderei deles o rosto, pois derramarei o meu Espírito sobre a casa de Israel, diz o SENHOR Deus.

'''

xref:026-ezequiel/026-ezequiel-038.adoc#v26-38-0[&#60; Capítulo Anterior] | <<v26-39-0,Topo>> | xref:026-ezequiel/026-ezequiel-040.adoc#v26-40-0[Próximo Capítulo &#62;]