include::./index.adoc[]

[[v26-14-0]]
=== Ezequiel, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-14-1]]

^<<v26-14-1,1>>^ Então, vieram ter comigo alguns dos anciãos de Israel e se assentaram diante de mim.

[[v26-14-2]]

^<<v26-14-2,2>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-14-3]]

^<<v26-14-3,3>>^ Filho do homem, estes homens levantaram os seus ídolos dentro do seu coração, tropeço para a iniquidade que sempre têm eles diante de si; acaso, permitirei que eles me interroguem?

[[v26-14-4]]

^<<v26-14-4,4>>^ Portanto, fala com eles e dize-lhes: Assim diz o SENHOR Deus: Qualquer homem da casa de Israel que levantar os seus ídolos dentro do seu coração, e tem tal tropeço para a sua iniquidade, e vier ao profeta, eu, o SENHOR, vindo ele, lhe responderei segundo a multidão dos seus ídolos;

[[v26-14-5]]

^<<v26-14-5,5>>^ para que eu possa apanhar a casa de Israel no seu próprio coração, porquanto todos se apartaram de mim para seguirem os seus ídolos.

[[v26-14-6]]

^<<v26-14-6,6>>^ Portanto, dize à casa de Israel: Assim diz o SENHOR Deus: Convertei-vos, e apartai-vos dos vossos ídolos, e dai as costas a todas as vossas abominações,

[[v26-14-7]]

^<<v26-14-7,7>>^ porque qualquer homem da casa de Israel ou dos estrangeiros que moram em Israel que se alienar de mim, e levantar os seus ídolos dentro do seu coração, e tiver tal tropeço para a iniquidade, e vier ao profeta, para me consultar por meio dele, a esse, eu, o SENHOR, responderei por mim mesmo.

[[v26-14-8]]

^<<v26-14-8,8>>^ Voltarei o rosto contra o tal homem, e o farei sinal e provérbio, e eliminá-lo-ei do meio do meu povo; e sabereis que eu sou o SENHOR.

[[v26-14-9]]

^<<v26-14-9,9>>^ Se o profeta for enganado e falar alguma coisa, fui eu, o SENHOR, que enganei esse profeta; estenderei a mão contra ele e o eliminarei do meio do meu povo de Israel.

[[v26-14-10]]

^<<v26-14-10,10>>^ Ambos levarão sobre si a sua iniquidade; a iniquidade daquele que consulta será como a do profeta;

[[v26-14-11]]

^<<v26-14-11,11>>^ para que a casa de Israel não se desvie mais de mim, nem mais se contamine com todas as suas transgressões. Então, diz o SENHOR Deus: Eles serão o meu povo, e eu serei o seu Deus.

[[v26-14-12]]

^<<v26-14-12,12>>^ Veio ainda a mim a palavra do SENHOR, dizendo:

[[v26-14-13]]

^<<v26-14-13,13>>^ Filho do homem, quando uma terra pecar contra mim, cometendo graves transgressões, estenderei a mão contra ela, e tornarei instável o sustento do pão, e enviarei contra ela fome, e eliminarei dela homens e animais;

[[v26-14-14]]

^<<v26-14-14,14>>^ ainda que estivessem no meio dela estes três homens, Noé, Daniel e Jó, eles, pela sua justiça, salvariam apenas a sua própria vida, diz o SENHOR Deus.

[[v26-14-15]]

^<<v26-14-15,15>>^ Se eu fizer passar pela terra bestas-feras, e elas a assolarem, que fique assolada, e ninguém possa passar por ela por causa das feras;

[[v26-14-16]]

^<<v26-14-16,16>>^ tão certo como eu vivo, diz o SENHOR Deus, ainda que esses três homens estivessem no meio dela, não salvariam nem a seus filhos nem a suas filhas; só eles seriam salvos, e a terra seria assolada.

[[v26-14-17]]

^<<v26-14-17,17>>^ Ou se eu fizer vir a espada sobre essa terra e disser: Espada, passa pela terra; e eu eliminar dela homens e animais,

[[v26-14-18]]

^<<v26-14-18,18>>^ tão certo como eu vivo, diz o SENHOR Deus, ainda que esses três homens estivessem no meio dela, não salvariam nem a seus filhos nem a suas filhas; só eles seriam salvos.

[[v26-14-19]]

^<<v26-14-19,19>>^ Ou se eu enviar a peste sobre essa terra e derramar o meu furor sobre ela com sangue, para eliminar dela homens e animais,

[[v26-14-20]]

^<<v26-14-20,20>>^ tão certo como eu vivo, diz o SENHOR Deus, ainda que Noé, Daniel e Jó estivessem no meio dela, não salvariam nem a seu filho nem a sua filha; pela sua justiça salvariam apenas a sua própria vida.

[[v26-14-21]]

^<<v26-14-21,21>>^ Porque assim diz o SENHOR Deus: Quanto mais, se eu enviar os meus quatro maus juízos, a espada, a fome, as bestas-feras e a peste, contra Jerusalém, para eliminar dela homens e animais?

[[v26-14-22]]

^<<v26-14-22,22>>^ Mas eis que alguns restarão nela, que levarão fora tanto filhos como filhas; eis que eles virão a vós outros, e vereis o seu caminho e os seus feitos; e ficareis consolados do mal que eu fiz vir sobre Jerusalém, sim, de tudo o que fiz vir sobre ela.

[[v26-14-23]]

^<<v26-14-23,23>>^ Eles vos consolarão quando virdes o seu caminho e os seus feitos; e sabereis que não foi sem motivo tudo quanto fiz nela, diz o SENHOR Deus.

'''

xref:026-ezequiel/026-ezequiel-013.adoc#v26-13-0[&#60; Capítulo Anterior] | <<v26-14-0,Topo>> | xref:026-ezequiel/026-ezequiel-015.adoc#v26-15-0[Próximo Capítulo &#62;]