include::./index.adoc[]

[[v26-28-0]]
=== Ezequiel, 28
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-28-1]]

^<<v26-28-1,1>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-28-2]]

^<<v26-28-2,2>>^ Filho do homem, dize ao príncipe de Tiro: Assim diz o SENHOR Deus: Visto que se eleva o teu coração, e dizes: Eu sou Deus, sobre a cadeira de Deus me assento no coração dos mares, e não passas de homem e não és Deus, ainda que estimas o teu coração como se fora o coração de Deus —

[[v26-28-3]]

^<<v26-28-3,3>>^ sim, és mais sábio que Daniel, não há segredo algum que se possa esconder de ti;

[[v26-28-4]]

^<<v26-28-4,4>>^ pela tua sabedoria e pelo teu entendimento, alcançaste o teu poder e adquiriste ouro e prata nos teus tesouros;

[[v26-28-5]]

^<<v26-28-5,5>>^ pela extensão da tua sabedoria no teu comércio, aumentaste as tuas riquezas; e, por causa delas, se eleva o teu coração —,

[[v26-28-6]]

^<<v26-28-6,6>>^ assim diz o SENHOR Deus: Visto que estimas o teu coração como se fora o coração de Deus,

[[v26-28-7]]

^<<v26-28-7,7>>^ eis que eu trarei sobre ti os mais terríveis estrangeiros dentre as nações, os quais desembainharão a espada contra a formosura da tua sabedoria e mancharão o teu resplendor.

[[v26-28-8]]

^<<v26-28-8,8>>^ Eles te farão descer à cova, e morrerás da morte dos traspassados no coração dos mares.

[[v26-28-9]]

^<<v26-28-9,9>>^ Dirás ainda diante daquele que te matar: Eu sou Deus? Pois não passas de homem e não és Deus, no poder do que te traspassa.

[[v26-28-10]]

^<<v26-28-10,10>>^ Da morte de incircuncisos morrerás, por intermédio de estrangeiros, porque eu o falei, diz o SENHOR Deus.

[[v26-28-11]]

^<<v26-28-11,11>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-28-12]]

^<<v26-28-12,12>>^ Filho do homem, levanta uma lamentação contra o rei de Tiro e dize-lhe: Assim diz o SENHOR Deus: Tu és o sinete da perfeição, cheio de sabedoria e formosura.

[[v26-28-13]]

^<<v26-28-13,13>>^ Estavas no Éden, jardim de Deus; de todas as pedras preciosas te cobrias: o sárdio, o topázio, o diamante, o berilo, o ônix, o jaspe, a safira, o carbúnculo e a esmeralda; de ouro se te fizeram os engastes e os ornamentos; no dia em que foste criado, foram eles preparados.

[[v26-28-14]]

^<<v26-28-14,14>>^ Tu eras querubim da guarda ungido, e te estabeleci; permanecias no monte santo de Deus, no brilho das pedras andavas.

[[v26-28-15]]

^<<v26-28-15,15>>^ Perfeito eras nos teus caminhos, desde o dia em que foste criado até que se achou iniquidade em ti.

[[v26-28-16]]

^<<v26-28-16,16>>^ Na multiplicação do teu comércio, se encheu o teu interior de violência, e pecaste; pelo que te lançarei, profanado, fora do monte de Deus e te farei perecer, ó querubim da guarda, em meio ao brilho das pedras.

[[v26-28-17]]

^<<v26-28-17,17>>^ Elevou-se o teu coração por causa da tua formosura, corrompeste a tua sabedoria por causa do teu resplendor; lancei-te por terra, diante dos reis te pus, para que te contemplem.

[[v26-28-18]]

^<<v26-28-18,18>>^ Pela multidão das tuas iniquidades, pela injustiça do teu comércio, profanaste os teus santuários; eu, pois, fiz sair do meio de ti um fogo, que te consumiu, e te reduzi a cinzas sobre a terra, aos olhos de todos os que te contemplam.

[[v26-28-19]]

^<<v26-28-19,19>>^ Todos os que te conhecem entre os povos estão espantados de ti; vens a ser objeto de espanto e jamais subsistirás.

[[v26-28-20]]

^<<v26-28-20,20>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-28-21]]

^<<v26-28-21,21>>^ Filho do homem, volve o rosto contra Sidom, profetiza contra ela

[[v26-28-22]]

^<<v26-28-22,22>>^ e dize: Assim diz o SENHOR Deus: Eis-me contra ti, ó Sidom, e serei glorificado no meio de ti; saberão que eu sou o SENHOR, quando nela executar juízos e nela me santificar.

[[v26-28-23]]

^<<v26-28-23,23>>^ Pois enviarei contra ela a peste e o sangue nas suas ruas, e os traspassados cairão no meio dela, pela espada contra ela, por todos os lados; e saberão que eu sou o SENHOR.

[[v26-28-24]]

^<<v26-28-24,24>>^ Para a casa de Israel já não haverá espinho que a pique, nem abrolho que cause dor, entre todos os vizinhos que a tratam com desprezo; e saberão que eu sou o SENHOR Deus.

[[v26-28-25]]

^<<v26-28-25,25>>^ Assim diz o SENHOR Deus: Quando eu congregar a casa de Israel dentre os povos entre os quais estão espalhados e eu me santificar entre eles, perante as nações, então, habitarão na terra que dei a meu servo, a Jacó.

[[v26-28-26]]

^<<v26-28-26,26>>^ Habitarão nela seguros, edificarão casas e plantarão vinhas; sim, habitarão seguros, quando eu executar juízos contra todos os que os tratam com desprezo ao redor deles; e saberão que eu sou o SENHOR, seu Deus.

'''

xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[&#60; Capítulo Anterior] | <<v26-28-0,Topo>> | xref:026-ezequiel/026-ezequiel-029.adoc#v26-29-0[Próximo Capítulo &#62;]