include::./index.adoc[]

[[v26-5-0]]
=== Ezequiel, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-5-1]]

^<<v26-5-1,1>>^ Tu, ó filho do homem, toma uma espada afiada; como navalha de barbeiro a tomarás e a farás passar pela tua cabeça e pela tua barba; tomarás uma balança de peso e repartirás os cabelos.

[[v26-5-2]]

^<<v26-5-2,2>>^ Uma terça parte queimarás, no meio da cidade, quando se cumprirem os dias do cerco; tomarás outra terça parte e a ferirás com uma espada ao redor da cidade; e a outra terça parte espalharás ao vento; desembainharei a espada atrás deles.

[[v26-5-3]]

^<<v26-5-3,3>>^ Desta terça parte tomarás uns poucos e os atarás nas abas da tua veste.

[[v26-5-4]]

^<<v26-5-4,4>>^ Destes ainda tomarás alguns, e os lançarás no meio do fogo, e os queimarás; dali sairá um fogo contra toda a casa de Israel.

[[v26-5-5]]

^<<v26-5-5,5>>^ Assim diz o SENHOR Deus: Esta é Jerusalém; pu-la no meio das nações e terras que estão ao redor dela.

[[v26-5-6]]

^<<v26-5-6,6>>^ Ela, porém, se rebelou contra os meus juízos, praticando o mal mais do que as nações e transgredindo os meus estatutos mais do que as terras que estão ao redor dela; porque rejeitaram os meus juízos e não andaram nos meus estatutos.

[[v26-5-7]]

^<<v26-5-7,7>>^ Portanto, assim diz o SENHOR Deus: Porque sois mais rebeldes do que as nações que estão ao vosso redor e não tendes andado nos meus estatutos, nem cumprido os meus juízos, nem procedido segundo os direitos das nações ao redor de vós,

[[v26-5-8]]

^<<v26-5-8,8>>^ por isso, assim diz o SENHOR Deus: Eis que eu, eu mesmo, estou contra ti; e executarei juízos no meio de ti, à vista das nações.

[[v26-5-9]]

^<<v26-5-9,9>>^ Farei contigo o que nunca fiz e o que jamais farei, por causa de todas as tuas abominações.

[[v26-5-10]]

^<<v26-5-10,10>>^ Portanto, os pais devorarão a seus filhos no meio de ti, e os filhos devorarão a seus pais; executarei em ti juízos e tudo o que restar de ti espalharei a todos os ventos.

[[v26-5-11]]

^<<v26-5-11,11>>^ Portanto, tão certo como eu vivo, diz o SENHOR Deus, pois que profanaste o meu santuário com todas as tuas coisas detestáveis e com todas as tuas abominações, eu retirarei, sem piedade, os olhos de ti e não te pouparei.

[[v26-5-12]]

^<<v26-5-12,12>>^ Uma terça parte de ti morrerá de peste e será consumida de fome no meio de ti; outra terça parte cairá à espada em redor de ti; e a outra terça parte espalharei a todos os ventos e desembainharei a espada atrás dela.

[[v26-5-13]]

^<<v26-5-13,13>>^ Assim, se cumprirá a minha ira, e satisfarei neles o meu furor e me consolarei; saberão que eu, o SENHOR, falei no meu zelo, quando cumprir neles o meu furor.

[[v26-5-14]]

^<<v26-5-14,14>>^ Pôr-te-ei em desolação e por objeto de opróbrio entre as nações que estão ao redor de ti, à vista de todos os que passarem.

[[v26-5-15]]

^<<v26-5-15,15>>^ Assim, serás objeto de opróbrio e ludíbrio, de escarmento e espanto às nações que estão ao redor de ti, quando eu executar em ti juízos com ira e indignação, em furiosos castigos. Eu, o SENHOR, falei.

[[v26-5-16]]

^<<v26-5-16,16>>^ Quando eu despedir as malignas flechas da fome contra eles, flechas destruidoras, que eu enviarei para vos destruir, então, aumentarei a fome sobre vós e vos tirarei o sustento de pão.

[[v26-5-17]]

^<<v26-5-17,17>>^ Enviarei sobre vós a fome e bestas-feras que te desfilharão; a peste e o sangue passarão por ti, e trarei a espada sobre ti. Eu, o SENHOR, falei.

'''

xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[&#60; Capítulo Anterior] | <<v26-5-0,Topo>> | xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[Próximo Capítulo &#62;]