include::./index.adoc[]

[[v26-3-0]]
=== Ezequiel, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-3-1]]

^<<v26-3-1,1>>^ Ainda me disse: Filho do homem, come o que achares; come este rolo, vai e fala à casa de Israel.

[[v26-3-2]]

^<<v26-3-2,2>>^ Então, abri a boca, e ele me deu a comer o rolo.

[[v26-3-3]]

^<<v26-3-3,3>>^ E me disse: Filho do homem, dá de comer ao teu ventre e enche as tuas entranhas deste rolo que eu te dou. Eu o comi, e na boca me era doce como o mel.

[[v26-3-4]]

^<<v26-3-4,4>>^ Disse-me ainda: Filho do homem, vai, entra na casa de Israel e dize-lhe as minhas palavras.

[[v26-3-5]]

^<<v26-3-5,5>>^ Porque tu não és enviado a um povo de estranho falar nem de língua difícil, mas à casa de Israel;

[[v26-3-6]]

^<<v26-3-6,6>>^ nem a muitos povos de estranho falar e de língua difícil, cujas palavras não possas entender; se eu aos tais te enviasse, certamente, te dariam ouvidos.

[[v26-3-7]]

^<<v26-3-7,7>>^ Mas a casa de Israel não te dará ouvidos, porque não me quer dar ouvidos a mim; pois toda a casa de Israel é de fronte obstinada e dura de coração.

[[v26-3-8]]

^<<v26-3-8,8>>^ Eis que fiz duro o teu rosto contra o rosto deles e dura a tua fronte, contra a sua fronte.

[[v26-3-9]]

^<<v26-3-9,9>>^ Fiz a tua fronte como o diamante, mais dura do que a pederneira; não os temas, pois, nem te assustes com o seu rosto, porque são casa rebelde.

[[v26-3-10]]

^<<v26-3-10,10>>^ Ainda me disse mais: Filho do homem, mete no coração todas as minhas palavras que te hei de falar e ouve-as com os teus ouvidos.

[[v26-3-11]]

^<<v26-3-11,11>>^ Eia, pois, vai aos do cativeiro, aos filhos do teu povo, e, quer ouçam quer deixem de ouvir, fala com eles, e dize-lhes: Assim diz o SENHOR Deus.

[[v26-3-12]]

^<<v26-3-12,12>>^ Levantou-me o Espírito, e ouvi por detrás de mim uma voz de grande estrondo, que, levantando-se do seu lugar, dizia: Bendita seja a glória do SENHOR.

[[v26-3-13]]

^<<v26-3-13,13>>^ Ouvi o tatalar das asas dos seres viventes, que tocavam umas nas outras, e o barulho das rodas juntamente com eles e o sonido de um grande estrondo.

[[v26-3-14]]

^<<v26-3-14,14>>^ Então, o Espírito me levantou e me levou; eu fui amargurado na excitação do meu espírito; mas a mão do SENHOR se fez muito forte sobre mim.

[[v26-3-15]]

^<<v26-3-15,15>>^ Então, fui a Tel-Abibe, aos do exílio, que habitavam junto ao rio Quebar, e passei a morar onde eles habitavam; e, por sete dias, assentei-me ali, atônito, no meio deles.

[[v26-3-16]]

^<<v26-3-16,16>>^ Findos os sete dias, veio a mim a palavra do SENHOR, dizendo:

[[v26-3-17]]

^<<v26-3-17,17>>^ Filho do homem, eu te dei por atalaia sobre a casa de Israel; da minha boca ouvirás a palavra e os avisarás da minha parte.

[[v26-3-18]]

^<<v26-3-18,18>>^ Quando eu disser ao perverso: Certamente, morrerás, e tu não o avisares e nada disseres para o advertir do seu mau caminho, para lhe salvar a vida, esse perverso morrerá na sua iniquidade, mas o seu sangue da tua mão o requererei.

[[v26-3-19]]

^<<v26-3-19,19>>^ Mas, se avisares o perverso, e ele não se converter da sua maldade e do seu caminho perverso, ele morrerá na sua iniquidade, mas tu salvaste a tua alma.

[[v26-3-20]]

^<<v26-3-20,20>>^ Também quando o justo se desviar da sua justiça e fizer maldade, e eu puser diante dele um tropeço, ele morrerá; visto que não o avisaste, no seu pecado morrerá, e suas justiças que praticara não serão lembradas, mas o seu sangue da tua mão o requererei.

[[v26-3-21]]

^<<v26-3-21,21>>^ No entanto, se tu avisares o justo, para que não peque, e ele não pecar, certamente, viverá, porque foi avisado; e tu salvaste a tua alma.

[[v26-3-22]]

^<<v26-3-22,22>>^ A mão do SENHOR veio sobre mim, e ele me disse: Levanta-te e sai para o vale, onde falarei contigo.

[[v26-3-23]]

^<<v26-3-23,23>>^ Levantei-me e saí para o vale, e eis que a glória do SENHOR estava ali, como a glória que eu vira junto ao rio Quebar; e caí com o rosto em terra.

[[v26-3-24]]

^<<v26-3-24,24>>^ Então, entrou em mim o Espírito, e me pôs em pé, e falou comigo, e me disse: Vai e encerra-te dentro da tua casa.

[[v26-3-25]]

^<<v26-3-25,25>>^ Porque, ó filho do homem, eis que porão cordas sobre ti e te ligarão com elas; e não sairás ao meio deles.

[[v26-3-26]]

^<<v26-3-26,26>>^ Farei que a tua língua se pegue ao teu paladar, ficarás mudo e incapaz de os repreender; porque são casa rebelde.

[[v26-3-27]]

^<<v26-3-27,27>>^ Mas, quando eu falar contigo, darei que fale a tua boca, e lhes dirás: Assim diz o SENHOR Deus: Quem ouvir ouça, e quem deixar de ouvir deixe; porque são casa rebelde.

'''

xref:026-ezequiel/026-ezequiel-002.adoc#v26-2-0[&#60; Capítulo Anterior] | <<v26-3-0,Topo>> | xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[Próximo Capítulo &#62;]