include::./index.adoc[]

[[v26-42-0]]
=== Ezequiel, 42
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-42-1]]

^<<v26-42-1,1>>^ Depois disto, me fez sair para o átrio exterior, para o norte; e me levou às celas que estavam para o norte, opostas ao edifício na área separada, edifício que olha para o norte,

[[v26-42-2]]

^<<v26-42-2,2>>^ do comprimento de cem côvados, com portas que davam para o norte; e a largura era de cinquenta côvados.

[[v26-42-3]]

^<<v26-42-3,3>>^ Em frente dos vinte côvados que pertenciam ao átrio interior, defronte do pavimento que pertencia ao átrio exterior, havia galeria contra galeria em três andares.

[[v26-42-4]]

^<<v26-42-4,4>>^ Diante das câmaras havia um passeio de dez côvados de largura, do lado de dentro, e cem de comprimento; e as suas entradas eram para o lado norte.

[[v26-42-5]]

^<<v26-42-5,5>>^ As câmaras superiores eram mais estreitas; porque as galerias tiravam mais espaço destas do que das de baixo e das do meio do edifício.

[[v26-42-6]]

^<<v26-42-6,6>>^ Porque elas eram de três andares e não tinham colunas como as colunas dos átrios; por isso, as superiores eram mais estreitas do que as de baixo e as do meio.

[[v26-42-7]]

^<<v26-42-7,7>>^ O muro que estava por fora, defronte das câmaras, no caminho do átrio exterior, diante das câmaras, tinha cinquenta côvados de comprimento.

[[v26-42-8]]

^<<v26-42-8,8>>^ Pois o comprimento das câmaras, que estavam no átrio exterior, era de cinquenta côvados; e eis que defronte do templo havia cem côvados.

[[v26-42-9]]

^<<v26-42-9,9>>^ Da parte de baixo destas câmaras, estava a entrada do lado do oriente, quando se entra nelas pelo átrio exterior.

[[v26-42-10]]

^<<v26-42-10,10>>^ Do muro do átrio para o oriente, diante do edifício na área separada, havia também celas

[[v26-42-11]]

^<<v26-42-11,11>>^ e um passeio; tinham a feição das celas que olhavam para o norte, e o mesmo comprimento, e a mesma largura, e ainda as mesmas saídas, e o mesmo arranjo; como eram as suas entradas,

[[v26-42-12]]

^<<v26-42-12,12>>^ assim eram as das celas que olhavam para o sul, no princípio do caminho, a saber, o caminho bem defronte do muro para o oriente, para quem por elas entra.

[[v26-42-13]]

^<<v26-42-13,13>>^ Então, o homem me disse: As câmaras do norte e as câmaras do sul, que estão diante da área separada, são câmaras santas, em que os sacerdotes, que se chegam ao SENHOR, comerão e onde depositarão as coisas santíssimas, isto é, as ofertas de manjares e as pelo pecado e pela culpa; porque o lugar é santo.

[[v26-42-14]]

^<<v26-42-14,14>>^ Quando os sacerdotes entrarem, não sairão do santuário para o átrio exterior, mas porão ali as vestiduras com que ministraram, porque elas são santas; usarão outras vestiduras e assim se aproximarão do lugar destinado ao povo.

[[v26-42-15]]

^<<v26-42-15,15>>^ Acabando ele de medir o templo interior, ele me fez sair pela porta que olha para o oriente; e mediu em redor.

[[v26-42-16]]

^<<v26-42-16,16>>^ Mediu o lado oriental com a cana de medir: quinhentas canas ao redor.

[[v26-42-17]]

^<<v26-42-17,17>>^ Mediu o lado norte: quinhentas canas ao redor.

[[v26-42-18]]

^<<v26-42-18,18>>^ Mediu também o lado sul: quinhentas canas.

[[v26-42-19]]

^<<v26-42-19,19>>^ Voltou-se para o lado ocidental e mediu quinhentas canas.

[[v26-42-20]]

^<<v26-42-20,20>>^ Mediu pelos quatro lados; havia um muro em redor, de quinhentas canas de comprimento e quinhentas de largura, para fazer separação entre o santo e o profano.

'''

xref:026-ezequiel/026-ezequiel-041.adoc#v26-41-0[&#60; Capítulo Anterior] | <<v26-42-0,Topo>> | xref:026-ezequiel/026-ezequiel-043.adoc#v26-43-0[Próximo Capítulo &#62;]