include::./index.adoc[]

[[v26-12-0]]
=== Ezequiel, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-12-1]]

^<<v26-12-1,1>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-12-2]]

^<<v26-12-2,2>>^ Filho do homem, tu habitas no meio da casa rebelde, que tem olhos para ver e não vê, tem ouvidos para ouvir e não ouve, porque é casa rebelde.

[[v26-12-3]]

^<<v26-12-3,3>>^ Tu, pois, ó filho do homem, prepara a bagagem de exílio e de dia sai, à vista deles, para o exílio; e, do lugar onde estás, parte para outro lugar, à vista deles. Bem pode ser que o entendam, ainda que eles são casa rebelde.

[[v26-12-4]]

^<<v26-12-4,4>>^ À vista deles, pois, traze para a rua, de dia, a tua bagagem de exílio; depois, à tarde, sairás, à vista deles, como quem vai para o exílio.

[[v26-12-5]]

^<<v26-12-5,5>>^ Abre um buraco na parede, à vista deles, e sai por ali.

[[v26-12-6]]

^<<v26-12-6,6>>^ À vista deles, aos ombros a levarás; às escuras, a transportarás; cobre o rosto para que não vejas a terra; porque por sinal te pus à casa de Israel.

[[v26-12-7]]

^<<v26-12-7,7>>^ Como se me ordenou, assim eu fiz: de dia, levei para fora a minha bagagem de exílio; então, à tarde, com as mãos abri para mim um buraco na parede; às escuras, eu saí e, aos ombros, transportei a bagagem, à vista deles.

[[v26-12-8]]

^<<v26-12-8,8>>^ Pela manhã, veio a mim a palavra do SENHOR, dizendo:

[[v26-12-9]]

^<<v26-12-9,9>>^ Filho do homem, não te perguntou a casa de Israel, aquela casa rebelde: Que fazes tu?

[[v26-12-10]]

^<<v26-12-10,10>>^ Dize-lhes: Assim diz o SENHOR Deus: Esta sentença refere-se ao príncipe em Jerusalém e a toda a casa de Israel, que está no meio dela.

[[v26-12-11]]

^<<v26-12-11,11>>^ Dize: Eu sou o vosso sinal. Como eu fiz, assim se lhes fará a eles; irão para o exílio, para o cativeiro.

[[v26-12-12]]

^<<v26-12-12,12>>^ O príncipe que está no meio deles levará aos ombros a bagagem e, às escuras, sairá; abrirá um buraco na parede para sair por ele; cobrirá o rosto para que seus olhos não vejam a terra.

[[v26-12-13]]

^<<v26-12-13,13>>^ Também estenderei a minha rede sobre ele, e será apanhado nas minhas malhas; levá-lo-ei a Babilônia, à terra dos caldeus, mas não a verá, ainda que venha a morrer ali.

[[v26-12-14]]

^<<v26-12-14,14>>^ A todos os ventos espalharei todos os que, para o ajudarem, estão ao redor dele, e todas as suas tropas; desembainharei a espada após eles.

[[v26-12-15]]

^<<v26-12-15,15>>^ Saberão que eu sou o SENHOR, quando eu os dispersar entre as nações e os espalhar pelas terras.

[[v26-12-16]]

^<<v26-12-16,16>>^ Deles deixarei ficar alguns poucos, escapos da espada, da fome e da peste, para que publiquem todas as suas coisas abomináveis entre as nações para onde forem; e saberão que eu sou o SENHOR.

[[v26-12-17]]

^<<v26-12-17,17>>^ Então, veio a mim a palavra do SENHOR, dizendo:

[[v26-12-18]]

^<<v26-12-18,18>>^ Filho do homem, o teu pão comerás com tremor e a tua água beberás com estremecimento e ansiedade;

[[v26-12-19]]

^<<v26-12-19,19>>^ e dirás ao povo da terra: Assim diz o SENHOR Deus acerca dos habitantes de Jerusalém, na terra de Israel: O seu pão comerão com ansiedade e a sua água beberão com espanto, pois que a sua terra será despojada de tudo quanto contém, por causa da violência de todos os que nela habitam.

[[v26-12-20]]

^<<v26-12-20,20>>^ As cidades habitadas cairão em ruínas, e a terra se tornará em desolação; e sabereis que eu sou o SENHOR.

[[v26-12-21]]

^<<v26-12-21,21>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-12-22]]

^<<v26-12-22,22>>^ Filho do homem, que provérbio é esse que vós tendes na terra de Israel: Prolongue-se o tempo, e não se cumpra a profecia?

[[v26-12-23]]

^<<v26-12-23,23>>^ Portanto, dize-lhes: Assim diz o SENHOR Deus: Farei cessar esse provérbio, e já não se servirão dele em Israel; mas dize-lhes: Os dias estão próximos e o cumprimento de toda profecia.

[[v26-12-24]]

^<<v26-12-24,24>>^ Porque já não haverá visão falsa nenhuma, nem adivinhação lisonjeira, no meio da casa de Israel.

[[v26-12-25]]

^<<v26-12-25,25>>^ Porque eu, o SENHOR, falarei, e a palavra que eu falar se cumprirá e não será retardada; porque, em vossos dias, ó casa rebelde, falarei a palavra e a cumprirei, diz o SENHOR Deus.

[[v26-12-26]]

^<<v26-12-26,26>>^ Veio-me ainda a palavra do SENHOR, dizendo:

[[v26-12-27]]

^<<v26-12-27,27>>^ Filho do homem, eis que os da casa de Israel dizem: A visão que tem este é para muitos dias, e ele profetiza de tempos que estão mui longe.

[[v26-12-28]]

^<<v26-12-28,28>>^ Portanto, dize-lhes: Assim diz o SENHOR Deus: Não será retardada nenhuma das minhas palavras; e a palavra que falei se cumprirá, diz o SENHOR Deus.

'''

xref:026-ezequiel/026-ezequiel-011.adoc#v26-11-0[&#60; Capítulo Anterior] | <<v26-12-0,Topo>> | xref:026-ezequiel/026-ezequiel-013.adoc#v26-13-0[Próximo Capítulo &#62;]