include::./index.adoc[]

[[v26-24-0]]
=== Ezequiel, 24
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-24-1]]

^<<v26-24-1,1>>^ Veio a mim a palavra do SENHOR, em o nono ano, no décimo mês, aos dez dias do mês, dizendo:

[[v26-24-2]]

^<<v26-24-2,2>>^ Filho do homem, escreve o nome deste dia, deste mesmo dia; porque o rei da Babilônia se atira contra Jerusalém neste dia.

[[v26-24-3]]

^<<v26-24-3,3>>^ Propõe uma parábola à casa rebelde e dize-lhe: Assim diz o SENHOR Deus: Põe ao lume a panela, põe-na, deita-lhe água dentro,

[[v26-24-4]]

^<<v26-24-4,4>>^ ajunta nela pedaços de carne, todos os bons pedaços, as coxas e as espáduas; enche-a de ossos escolhidos.

[[v26-24-5]]

^<<v26-24-5,5>>^ Pega do melhor do rebanho e empilha lenha debaixo dela; faze-a ferver bem, e cozam-se dentro dela os ossos.

[[v26-24-6]]

^<<v26-24-6,6>>^ Portanto, assim diz o SENHOR Deus: Ai da cidade sanguinária, da panela cheia de ferrugem, ferrugem que não foi tirada dela! Tira de dentro a carne, pedaço por pedaço, sem escolha.

[[v26-24-7]]

^<<v26-24-7,7>>^ Porque a culpa de sangue está no meio dela; derramou-o sobre penha descalvada e não sobre a terra, para o cobrir com o pó;

[[v26-24-8]]

^<<v26-24-8,8>>^ para fazer subir a indignação, para tomar vingança, eu pus o seu sangue numa penha descalvada, para que não fosse coberto.

[[v26-24-9]]

^<<v26-24-9,9>>^ Portanto, assim diz o SENHOR Deus: Ai da cidade sanguinária! Também eu farei pilha grande.

[[v26-24-10]]

^<<v26-24-10,10>>^ Amontoa muita lenha, acende o fogo, cozinha a carne, engrossa o caldo, e ardam os ossos.

[[v26-24-11]]

^<<v26-24-11,11>>^ Então, porás a panela vazia sobre as brasas, para que ela aqueça, o seu cobre se torne candente, funda-se a sua imundícia dentro dela, e se consuma a sua ferrugem.

[[v26-24-12]]

^<<v26-24-12,12>>^ Trabalho inútil! Não sai dela a sua muita ferrugem, nem pelo fogo.

[[v26-24-13]]

^<<v26-24-13,13>>^ Na tua imundícia está a luxúria; porque eu quis purificar-te, e não te purificaste, não serás nunca purificada da tua imundícia, até que eu tenha satisfeito o meu furor contra ti.

[[v26-24-14]]

^<<v26-24-14,14>>^ Eu, o SENHOR, o disse: será assim, e eu o farei; não tornarei atrás, não pouparei, nem me arrependerei; segundo os teus caminhos e segundo os teus feitos, serás julgada, diz o SENHOR Deus.

[[v26-24-15]]

^<<v26-24-15,15>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-24-16]]

^<<v26-24-16,16>>^ Filho do homem, eis que, às súbitas, tirarei a delícia dos teus olhos, mas não lamentarás, nem chorarás, nem te correrão as lágrimas.

[[v26-24-17]]

^<<v26-24-17,17>>^ Geme em silêncio, não faças lamentação pelos mortos, prende o teu turbante, mete as tuas sandálias nos pés, não cubras os bigodes e não comas o pão que te mandam.

[[v26-24-18]]

^<<v26-24-18,18>>^ Falei ao povo pela manhã, e, à tarde, morreu minha mulher; na manhã seguinte, fiz segundo me havia sido mandado.

[[v26-24-19]]

^<<v26-24-19,19>>^ Então, me disse o povo: Não nos farás saber o que significam estas coisas que estás fazendo?

[[v26-24-20]]

^<<v26-24-20,20>>^ Eu lhes disse: Veio a mim a palavra do SENHOR, dizendo:

[[v26-24-21]]

^<<v26-24-21,21>>^ Dize à casa de Israel: Assim diz o SENHOR Deus: Eis que eu profanarei o meu santuário, objeto do vosso mais alto orgulho, delícia dos vossos olhos e anelo de vossa alma; vossos filhos e vossas filhas, que deixastes, cairão à espada.

[[v26-24-22]]

^<<v26-24-22,22>>^ Fareis como eu fiz: não cobrireis os bigodes, nem comereis o pão que vos mandam.

[[v26-24-23]]

^<<v26-24-23,23>>^ Trareis à cabeça os vossos turbantes e as vossas sandálias, nos pés; não lamentareis, nem chorareis, mas definhar-vos-eis nas vossas iniquidades e gemereis uns com os outros.

[[v26-24-24]]

^<<v26-24-24,24>>^ Assim vos servirá Ezequiel de sinal; segundo tudo o que ele fez, assim fareis. Quando isso acontecer, sabereis que eu sou o SENHOR Deus.

[[v26-24-25]]

^<<v26-24-25,25>>^ Filho do homem, não sucederá que, no dia em que eu lhes tirar o objeto do seu orgulho, o seu júbilo, a sua glória, a delícia dos seus olhos e o anelo de sua alma e a seus filhos e suas filhas,

[[v26-24-26]]

^<<v26-24-26,26>>^ nesse dia, virá ter contigo algum que escapar, para te dar a notícia pessoalmente?

[[v26-24-27]]

^<<v26-24-27,27>>^ Nesse dia, abrir-se-á a tua boca para com aquele que escapar; falarás e já não ficarás mudo. Assim, lhes servirás de sinal, e saberão que eu sou o SENHOR.

'''

xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[&#60; Capítulo Anterior] | <<v26-24-0,Topo>> | xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[Próximo Capítulo &#62;]