include::./index.adoc[]

[[v26-8-0]]
=== Ezequiel, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-8-1]]

^<<v26-8-1,1>>^ No sexto ano, no sexto mês, aos cinco dias do mês, estando eu sentado em minha casa, e os anciãos de Judá, assentados diante de mim, sucedeu que ali a mão do SENHOR Deus caiu sobre mim.

[[v26-8-2]]

^<<v26-8-2,2>>^ Olhei, e eis uma figura como de fogo; desde os seus lombos e daí para baixo, era fogo e, dos seus lombos para cima, como o resplendor de metal brilhante.

[[v26-8-3]]

^<<v26-8-3,3>>^ Estendeu ela dali uma semelhança de mão e me tomou pelos cachos da cabeça; o Espírito me levantou entre a terra e o céu e me levou a Jerusalém em visões de Deus, até à entrada da porta do pátio de dentro, que olha para o norte, onde estava colocada a imagem dos ciúmes, que provoca o ciúme de Deus.

[[v26-8-4]]

^<<v26-8-4,4>>^ Eis que a glória do Deus de Israel estava ali, como a glória que eu vira no vale.

[[v26-8-5]]

^<<v26-8-5,5>>^ Ele me disse: Filho do homem, levanta agora os olhos para o norte. Levantei os olhos para lá, e eis que do lado norte, à porta do altar, estava esta imagem dos ciúmes, à entrada.

[[v26-8-6]]

^<<v26-8-6,6>>^ Disse-me ainda: Filho do homem, vês o que eles estão fazendo? As grandes abominações que a casa de Israel faz aqui, para que me afaste do meu santuário? Pois verás ainda maiores abominações.

[[v26-8-7]]

^<<v26-8-7,7>>^ Ele me levou à porta do átrio; olhei, e eis que havia um buraco na parede. Então, me disse: Filho do homem, cava naquela parede.

[[v26-8-8]]

^<<v26-8-8,8>>^ Cavei na parede, e eis que havia uma porta.

[[v26-8-9]]

^<<v26-8-9,9>>^ Disse-me: Entra e vê as terríveis abominações que eles fazem aqui.

[[v26-8-10]]

^<<v26-8-10,10>>^ Entrei e vi; eis toda forma de répteis e de animais abomináveis e de todos os ídolos da casa de Israel, pintados na parede em todo o redor.

[[v26-8-11]]

^<<v26-8-11,11>>^ Setenta homens dos anciãos da casa de Israel, com Jazanias, filho de Safã, que se achava no meio deles, estavam em pé diante das pinturas, tendo cada um na mão o seu incensário; e subia o aroma da nuvem de incenso.

[[v26-8-12]]

^<<v26-8-12,12>>^ Então, me disse: Viste, filho do homem, o que os anciãos da casa de Israel fazem nas trevas, cada um nas suas câmaras pintadas de imagens? Pois dizem: O SENHOR não nos vê, o SENHOR abandonou a terra.

[[v26-8-13]]

^<<v26-8-13,13>>^ Disse-me ainda: Tornarás a ver maiores abominações que eles estão fazendo.

[[v26-8-14]]

^<<v26-8-14,14>>^ Levou-me à entrada da porta da Casa do SENHOR, que está no lado norte, e eis que estavam ali mulheres assentadas chorando a Tamuz.

[[v26-8-15]]

^<<v26-8-15,15>>^ Disse-me: Vês isto, filho do homem? Verás ainda abominações maiores do que estas.

[[v26-8-16]]

^<<v26-8-16,16>>^ Levou-me para o átrio de dentro da Casa do SENHOR, e eis que estavam à entrada do templo do SENHOR, entre o pórtico e o altar, cerca de vinte e cinco homens, de costas para o templo do SENHOR e com o rosto para o oriente; adoravam o sol, virados para o oriente.

[[v26-8-17]]

^<<v26-8-17,17>>^ Então, me disse: Vês, filho do homem? Acaso, é coisa de pouca monta para a casa de Judá o fazerem eles as abominações que fazem aqui, para que ainda encham de violência a terra e tornem a irritar-me? Ei-los a chegar o ramo ao seu nariz.

[[v26-8-18]]

^<<v26-8-18,18>>^ Pelo que também eu os tratarei com furor; os meus olhos não pouparão, nem terei piedade. Ainda que me gritem aos ouvidos em alta voz, nem assim os ouvirei.

'''

xref:026-ezequiel/026-ezequiel-007.adoc#v26-7-0[&#60; Capítulo Anterior] | <<v26-8-0,Topo>> | xref:026-ezequiel/026-ezequiel-009.adoc#v26-9-0[Próximo Capítulo &#62;]