include::./index.adoc[]

[[v26-1-0]]
=== Ezequiel, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-1-1]]

^<<v26-1-1,1>>^ Aconteceu no trigésimo ano, no quinto dia do quarto mês, que, estando eu no meio dos exilados, junto ao rio Quebar, se abriram os céus, e eu tive visões de Deus.

[[v26-1-2]]

^<<v26-1-2,2>>^ No quinto dia do referido mês, no quinto ano de cativeiro do rei Joaquim,

[[v26-1-3]]

^<<v26-1-3,3>>^ veio expressamente a palavra do SENHOR a Ezequiel, filho de Buzi, o sacerdote, na terra dos caldeus, junto ao rio Quebar, e ali esteve sobre ele a mão do SENHOR.

[[v26-1-4]]

^<<v26-1-4,4>>^ Olhei, e eis que um vento tempestuoso vinha do Norte, e uma grande nuvem, com fogo a revolver-se, e resplendor ao redor dela, e no meio disto, uma coisa como metal brilhante, que saía do meio do fogo.

[[v26-1-5]]

^<<v26-1-5,5>>^ Do meio dessa nuvem saía a semelhança de quatro seres viventes, cuja aparência era esta: tinham a semelhança de homem.

[[v26-1-6]]

^<<v26-1-6,6>>^ Cada um tinha quatro rostos, como também quatro asas.

[[v26-1-7]]

^<<v26-1-7,7>>^ As suas pernas eram direitas, a planta de cujos pés era como a de um bezerro e luzia como o brilho de bronze polido.

[[v26-1-8]]

^<<v26-1-8,8>>^ Debaixo das asas tinham mãos de homem, aos quatro lados; assim todos os quatro tinham rostos e asas.

[[v26-1-9]]

^<<v26-1-9,9>>^ Estas se uniam uma à outra; não se viravam quando iam; cada qual andava para a sua frente.

[[v26-1-10]]

^<<v26-1-10,10>>^ A forma de seus rostos era como o de homem; à direita, os quatro tinham rosto de leão; à esquerda, rosto de boi; e também rosto de águia, todos os quatro.

[[v26-1-11]]

^<<v26-1-11,11>>^ Assim eram os seus rostos. Suas asas se abriam em cima; cada ser tinha duas asas, unidas cada uma à do outro; outras duas cobriam o corpo deles.

[[v26-1-12]]

^<<v26-1-12,12>>^ Cada qual andava para a sua frente; para onde o espírito havia de ir, iam; não se viravam quando iam.

[[v26-1-13]]

^<<v26-1-13,13>>^ O aspecto dos seres viventes era como carvão em brasa, à semelhança de tochas; o fogo corria resplendente por entre os seres, e dele saíam relâmpagos,

[[v26-1-14]]

^<<v26-1-14,14>>^ os seres viventes ziguezagueavam à semelhança de relâmpagos.

[[v26-1-15]]

^<<v26-1-15,15>>^ Vi os seres viventes; e eis que havia uma roda na terra, ao lado de cada um deles.

[[v26-1-16]]

^<<v26-1-16,16>>^ O aspecto das rodas e a sua estrutura eram brilhantes como o berilo; tinham as quatro a mesma aparência, cujo aspecto e estrutura eram como se estivera uma roda dentro da outra.

[[v26-1-17]]

^<<v26-1-17,17>>^ Andando elas, podiam ir em quatro direções; e não se viravam quando iam.

[[v26-1-18]]

^<<v26-1-18,18>>^ As suas cambotas eram altas, e metiam medo; e, nas quatro rodas, as mesmas eram cheias de olhos ao redor.

[[v26-1-19]]

^<<v26-1-19,19>>^ Andando os seres viventes, andavam as rodas ao lado deles; elevando-se eles, também elas se elevavam.

[[v26-1-20]]

^<<v26-1-20,20>>^ Para onde o espírito queria ir, iam, pois o espírito os impelia; e as rodas se elevavam juntamente com eles, porque nelas havia o espírito dos seres viventes.

[[v26-1-21]]

^<<v26-1-21,21>>^ Andando eles, andavam elas e, parando eles, paravam elas, e, elevando-se eles da terra, elevavam-se também as rodas juntamente com eles; porque o espírito dos seres viventes estava nas rodas.

[[v26-1-22]]

^<<v26-1-22,22>>^ Sobre a cabeça dos seres viventes havia algo semelhante ao firmamento, como cristal brilhante que metia medo, estendido por sobre a sua cabeça.

[[v26-1-23]]

^<<v26-1-23,23>>^ Por debaixo do firmamento, estavam estendidas as suas asas, a de um em direção à de outro; cada um tinha outras duas asas com que cobria o corpo de um e de outro lado.

[[v26-1-24]]

^<<v26-1-24,24>>^ Andando eles, ouvi o tatalar das suas asas, como o rugido de muitas águas, como a voz do Onipotente; ouvi o estrondo tumultuoso, como o tropel de um exército. Parando eles, abaixavam as asas.

[[v26-1-25]]

^<<v26-1-25,25>>^ Veio uma voz de cima do firmamento que estava sobre a sua cabeça. Parando eles, abaixavam as asas.

[[v26-1-26]]

^<<v26-1-26,26>>^ Por cima do firmamento que estava sobre a sua cabeça, havia algo semelhante a um trono, como uma safira; sobre esta espécie de trono, estava sentada uma figura semelhante a um homem.

[[v26-1-27]]

^<<v26-1-27,27>>^ Vi-a como metal brilhante, como fogo ao redor dela, desde os seus lombos e daí para cima; e desde os seus lombos e daí para baixo, vi-a como fogo e um resplendor ao redor dela.

[[v26-1-28]]

^<<v26-1-28,28>>^ Como o aspecto do arco que aparece na nuvem em dia de chuva, assim era o resplendor em redor. Esta era a aparência da glória do SENHOR; vendo isto, caí com o rosto em terra e ouvi a voz de quem falava.

'''

xref:025-lamentacoes/025-lamentacoes-005.adoc#v25-5-0[&#60; Capítulo Anterior] | <<v26-1-0,Topo>> | xref:026-ezequiel/026-ezequiel-002.adoc#v26-2-0[Próximo Capítulo &#62;]