include::./index.adoc[]

[[v26-20-0]]
=== Ezequiel, 20
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-20-1]]

^<<v26-20-1,1>>^ No quinto mês do sétimo ano, aos dez dias do mês, vieram alguns dos anciãos de Israel para consultar ao SENHOR; e assentaram-se diante de mim.

[[v26-20-2]]

^<<v26-20-2,2>>^ Então, veio a mim a palavra do SENHOR, dizendo:

[[v26-20-3]]

^<<v26-20-3,3>>^ Filho do homem, fala aos anciãos de Israel e dize-lhes: Assim diz o SENHOR Deus: Acaso, viestes consultar-me? Tão certo como eu vivo, diz o SENHOR Deus, vós não me consultareis.

[[v26-20-4]]

^<<v26-20-4,4>>^ Julgá-los-ias tu, ó filho do homem, julgá-los-ias? Faze-lhes saber as abominações de seus pais

[[v26-20-5]]

^<<v26-20-5,5>>^ e dize-lhes: Assim diz o SENHOR Deus: No dia em que escolhi a Israel, levantando a mão, jurei à descendência da casa de Jacó e me dei a conhecer a eles na terra do Egito; levantei-lhes a mão e jurei: Eu sou o SENHOR, vosso Deus.

[[v26-20-6]]

^<<v26-20-6,6>>^ Naquele dia, levantei-lhes a mão e jurei tirá-los da terra do Egito para uma terra que lhes tinha previsto, a qual mana leite e mel, coroa de todas as terras.

[[v26-20-7]]

^<<v26-20-7,7>>^ Então, lhes disse: Cada um lance de si as abominações de que se agradam os seus olhos, e não vos contamineis com os ídolos do Egito; eu sou o SENHOR, vosso Deus.

[[v26-20-8]]

^<<v26-20-8,8>>^ Mas rebelaram-se contra mim e não me quiseram ouvir; ninguém lançava de si as abominações de que se agradavam os seus olhos, nem abandonava os ídolos do Egito. Então, eu disse que derramaria sobre eles o meu furor, para cumprir a minha ira contra eles, no meio da terra do Egito.

[[v26-20-9]]

^<<v26-20-9,9>>^ O que fiz, porém, foi por amor do meu nome, para que não fosse profanado diante das nações no meio das quais eles estavam, diante das quais eu me dei a conhecer a eles, para os tirar da terra do Egito.

[[v26-20-10]]

^<<v26-20-10,10>>^ Tirei-os da terra do Egito e os levei para o deserto.

[[v26-20-11]]

^<<v26-20-11,11>>^ Dei-lhes os meus estatutos e lhes fiz conhecer os meus juízos, os quais, cumprindo-os o homem, viverá por eles.

[[v26-20-12]]

^<<v26-20-12,12>>^ Também lhes dei os meus sábados, para servirem de sinal entre mim e eles, para que soubessem que eu sou o SENHOR que os santifica.

[[v26-20-13]]

^<<v26-20-13,13>>^ Mas a casa de Israel se rebelou contra mim no deserto, não andando nos meus estatutos e rejeitando os meus juízos, os quais, cumprindo-os o homem, viverá por eles; e profanaram grandemente os meus sábados. Então, eu disse que derramaria sobre eles o meu furor no deserto, para os consumir.

[[v26-20-14]]

^<<v26-20-14,14>>^ O que fiz, porém, foi por amor do meu nome, para que não fosse profanado diante das nações perante as quais os fiz sair.

[[v26-20-15]]

^<<v26-20-15,15>>^ Demais, levantei-lhes no deserto a mão e jurei não deixá-los entrar na terra que lhes tinha dado, a qual mana leite e mel, coroa de todas as terras.

[[v26-20-16]]

^<<v26-20-16,16>>^ Porque rejeitaram os meus juízos, e não andaram nos meus estatutos, e profanaram os meus sábados, pois o seu coração andava após os seus ídolos.

[[v26-20-17]]

^<<v26-20-17,17>>^ Não obstante, os meus olhos lhes perdoaram, e eu não os destruí, nem os consumi de todo no deserto.

[[v26-20-18]]

^<<v26-20-18,18>>^ Mas disse eu a seus filhos no deserto: Não andeis nos estatutos de vossos pais, nem guardeis os seus juízos, nem vos contamineis com os seus ídolos.

[[v26-20-19]]

^<<v26-20-19,19>>^ Eu sou o SENHOR, vosso Deus; andai nos meus estatutos, e guardai os meus juízos, e praticai-os;

[[v26-20-20]]

^<<v26-20-20,20>>^ santificai os meus sábados, pois servirão de sinal entre mim e vós, para que saibais que eu sou o SENHOR, vosso Deus.

[[v26-20-21]]

^<<v26-20-21,21>>^ Mas também os filhos se rebelaram contra mim e não andaram nos meus estatutos, nem guardaram os meus juízos, os quais, cumprindo-os o homem, viverá por eles; antes, profanaram os meus sábados. Então, eu disse que derramaria sobre eles o meu furor, para cumprir contra eles a minha ira no deserto.

[[v26-20-22]]

^<<v26-20-22,22>>^ Mas detive a mão e o fiz por amor do meu nome, para que não fosse profanado diante das nações perante as quais os fiz sair.

[[v26-20-23]]

^<<v26-20-23,23>>^ Também levantei-lhes no deserto a mão e jurei espalhá-los entre as nações e derramá-los pelas terras;

[[v26-20-24]]

^<<v26-20-24,24>>^ porque não executaram os meus juízos, rejeitaram os meus estatutos, profanaram os meus sábados, e os seus olhos se iam após os ídolos de seus pais;

[[v26-20-25]]

^<<v26-20-25,25>>^ pelo que também lhes dei estatutos que não eram bons e juízos pelos quais não haviam de viver;

[[v26-20-26]]

^<<v26-20-26,26>>^ e permiti que eles se contaminassem com seus dons sacrificiais, como quando queimavam tudo o que abre a madre, para horrorizá-los, a fim de que soubessem que eu sou o SENHOR.

[[v26-20-27]]

^<<v26-20-27,27>>^ Portanto, fala à casa de Israel, ó filho do homem, e dize-lhes: Assim diz o SENHOR Deus: Ainda nisto me blasfemaram vossos pais e transgrediram contra mim.

[[v26-20-28]]

^<<v26-20-28,28>>^ Porque, havendo-os eu introduzido na terra sobre a qual eu, levantando a mão, jurara dar-lha, onde quer que viam um outeiro alto e uma árvore frondosa, aí ofereciam os seus sacrifícios, apresentavam suas ofertas provocantes, punham os seus suaves aromas e derramavam as suas libações.

[[v26-20-29]]

^<<v26-20-29,29>>^ Eu lhes disse: Que alto é este, aonde vós ides? O seu nome tem sido Lugar Alto, até ao dia de hoje.

[[v26-20-30]]

^<<v26-20-30,30>>^ Portanto, dize à casa de Israel: Assim diz o SENHOR Deus: Vós vos contaminais a vós mesmos, à maneira de vossos pais, e vos prostituís com as suas abominações?

[[v26-20-31]]

^<<v26-20-31,31>>^ Ao oferecerdes os vossos dons sacrificiais, como quando queimais os vossos filhos, vós vos contaminais com todos os vossos ídolos, até ao dia de hoje. Porventura, me consultaríeis, ó casa de Israel? Tão certo como eu vivo, diz o SENHOR Deus, vós não me consultareis.

[[v26-20-32]]

^<<v26-20-32,32>>^ O que vos ocorre à mente de maneira nenhuma sucederá; isto que dizeis: Seremos como as nações, como as outras gerações da terra, servindo às árvores e às pedras.

[[v26-20-33]]

^<<v26-20-33,33>>^ Tão certo como eu vivo, diz o SENHOR Deus, com mão poderosa, com braço estendido e derramado furor, hei de reinar sobre vós;

[[v26-20-34]]

^<<v26-20-34,34>>^ tirar-vos-ei dentre os povos e vos congregarei das terras nas quais andais espalhados, com mão forte, com braço estendido e derramado furor.

[[v26-20-35]]

^<<v26-20-35,35>>^ Levar-vos-ei ao deserto dos povos e ali entrarei em juízo convosco, face a face.

[[v26-20-36]]

^<<v26-20-36,36>>^ Como entrei em juízo com vossos pais, no deserto da terra do Egito, assim entrarei em juízo convosco, diz o SENHOR Deus.

[[v26-20-37]]

^<<v26-20-37,37>>^ Far-vos-ei passar debaixo do meu cajado e vos sujeitarei à disciplina da aliança;

[[v26-20-38]]

^<<v26-20-38,38>>^ separarei dentre vós os rebeldes e os que transgrediram contra mim; da terra das suas moradas eu os farei sair, mas não entrarão na terra de Israel; e sabereis que eu sou o SENHOR.

[[v26-20-39]]

^<<v26-20-39,39>>^ Quanto a vós outros, vós, ó casa de Israel, assim diz o SENHOR Deus: Ide; cada um sirva aos seus ídolos, agora e mais tarde, pois que a mim não me quereis ouvir; mas não profaneis mais o meu santo nome com as vossas dádivas e com os vossos ídolos.

[[v26-20-40]]

^<<v26-20-40,40>>^ Porque no meu santo monte, no monte alto de Israel, diz o SENHOR Deus, ali toda a casa de Israel me servirá, toda, naquela terra; ali me agradarei deles, ali requererei as vossas ofertas e as primícias das vossas dádivas, com todas as vossas coisas santas.

[[v26-20-41]]

^<<v26-20-41,41>>^ Agradar-me-ei de vós como de aroma suave, quando eu vos tirar dentre os povos e vos congregar das terras em que andais espalhados; e serei santificado em vós perante as nações.

[[v26-20-42]]

^<<v26-20-42,42>>^ Sabereis que eu sou o SENHOR, quando eu vos der entrada na terra de Israel, na terra que, levantando a mão, jurei dar a vossos pais.

[[v26-20-43]]

^<<v26-20-43,43>>^ Ali, vos lembrareis dos vossos caminhos e de todos os vossos feitos com que vos contaminastes e tereis nojo de vós mesmos, por todas as vossas iniquidades que tendes cometido.

[[v26-20-44]]

^<<v26-20-44,44>>^ Sabereis que eu sou o SENHOR, quando eu proceder para convosco por amor do meu nome, não segundo os vossos maus caminhos, nem segundo os vossos feitos corruptos, ó casa de Israel, diz o SENHOR Deus.

[[v26-20-45]]

^<<v26-20-45,45>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-20-46]]

^<<v26-20-46,46>>^ Filho do homem, volve o rosto para o Sul e derrama as tuas palavras contra ele; profetiza contra o bosque do campo do Sul

[[v26-20-47]]

^<<v26-20-47,47>>^ e dize ao bosque do Sul: Ouve a palavra do SENHOR: Assim diz o SENHOR Deus: Eis que acenderei em ti um fogo que consumirá em ti toda árvore verde e toda árvore seca; não se apagará a chama flamejante; antes, com ela se queimarão todos os rostos, desde o Sul até ao Norte.

[[v26-20-48]]

^<<v26-20-48,48>>^ E todos os homens verão que eu, o SENHOR, o acendi; não se apagará.

[[v26-20-49]]

^<<v26-20-49,49>>^ Então, disse eu: ah! SENHOR Deus! Eles dizem de mim: Não é ele proferidor de parábolas?

'''

xref:026-ezequiel/026-ezequiel-019.adoc#v26-19-0[&#60; Capítulo Anterior] | <<v26-20-0,Topo>> | xref:026-ezequiel/026-ezequiel-021.adoc#v26-21-0[Próximo Capítulo &#62;]