include::./index.adoc[]

[[v26-21-0]]
=== Ezequiel, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-21-1]]

^<<v26-21-1,1>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-21-2]]

^<<v26-21-2,2>>^ Filho do homem, volve o rosto contra Jerusalém, derrama as tuas palavras contra os santuários e profetiza contra a terra de Israel.

[[v26-21-3]]

^<<v26-21-3,3>>^ Dize à terra de Israel: Assim diz o SENHOR: Eis que sou contra ti, e tirarei a minha espada da bainha, e eliminarei do meio de ti tanto o justo como o perverso.

[[v26-21-4]]

^<<v26-21-4,4>>^ Porque hei de eliminar do meio de ti o justo e o perverso, a minha espada sairá da bainha contra todo vivente, desde o Sul até ao Norte.

[[v26-21-5]]

^<<v26-21-5,5>>^ Saberão todos os homens que eu, o SENHOR, tirei da bainha a minha espada; jamais voltará a ela.

[[v26-21-6]]

^<<v26-21-6,6>>^ Tu, porém, ó filho do homem, suspira; à vista deles, suspira de coração quebrantado e com amargura.

[[v26-21-7]]

^<<v26-21-7,7>>^ Quando te perguntarem: Por que suspiras tu? Então, dirás: Por causa das novas. Quando elas vêm, todo coração desmaia, todas as mãos se afrouxam, todo espírito se angustia, e todos os joelhos se desfazem em água; eis que elas vêm e se cumprirão, diz o SENHOR Deus.

[[v26-21-8]]

^<<v26-21-8,8>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-21-9]]

^<<v26-21-9,9>>^ Filho do homem, profetiza e dize: Assim diz o Senhor: A espada, a espada está afiada e polida;

[[v26-21-10]]

^<<v26-21-10,10>>^ afiada para matança, polida para reluzir como relâmpago. Israel diz: Alegremo-nos! O cetro do meu filho despreza qualquer outra madeira.

[[v26-21-11]]

^<<v26-21-11,11>>^ Mas Deus responde: Deu-se a espada a polir, para ser manejada; ela está afiada e polida, para ser posta na mão do matador.

[[v26-21-12]]

^<<v26-21-12,12>>^ Grita e geme, ó filho do homem, porque ela será contra o meu povo, contra todos os príncipes de Israel. Estes, juntamente com o meu povo, estão entregues à espada; dá, pois, pancadas na tua coxa.

[[v26-21-13]]

^<<v26-21-13,13>>^ Pois haverá uma prova; e que haverá, se o próprio cetro que desprezou a todos não vier a subsistir? — diz o SENHOR Deus.

[[v26-21-14]]

^<<v26-21-14,14>>^ Tu, pois, ó filho do homem, profetiza e bate com as palmas uma na outra; duplique a espada o seu golpe, triplique-o a espada da matança, da grande matança, que os rodeia;

[[v26-21-15]]

^<<v26-21-15,15>>^ para que desmaie o seu coração, e se multiplique o seu tropeçar junto a todas as portas. Faço reluzir a espada. Ah! Ela foi feita para ser raio e está afiada para matar.

[[v26-21-16]]

^<<v26-21-16,16>>^ Ó espada, vira-te, com toda a força, para a direita, vira-te para a esquerda, para onde quer que o teu rosto se dirigir.

[[v26-21-17]]

^<<v26-21-17,17>>^ Também eu baterei as minhas palmas uma na outra e desafogarei o meu furor; eu, o SENHOR, é que falei.

[[v26-21-18]]

^<<v26-21-18,18>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-21-19]]

^<<v26-21-19,19>>^ Tu, pois, ó filho do homem, propõe dois caminhos por onde venha a espada do rei da Babilônia; ambos procederão da mesma terra; põe neles marcos indicadores, põe-nos na entrada do caminho para a cidade.

[[v26-21-20]]

^<<v26-21-20,20>>^ Indica o caminho para que a espada chegue à Rabá dos filhos de Amom, a Judá e a Jerusalém, a fortificada.

[[v26-21-21]]

^<<v26-21-21,21>>^ Porque o rei da Babilônia para na encruzilhada, na entrada dos dois caminhos, para consultar os oráculos: sacode as flechas, interroga os ídolos do lar, examina o fígado.

[[v26-21-22]]

^<<v26-21-22,22>>^ Caiu-lhe o oráculo para a direita, sobre Jerusalém, para dispor os aríetes, para abrir a boca com ordens de matar, para lançar gritos de guerra, para colocar os aríetes contra as portas, para levantar terraplenos, para edificar baluartes.

[[v26-21-23]]

^<<v26-21-23,23>>^ Aos judeus, lhes parecerá isto oráculo enganador, pois têm em seu favor juramentos solenes; mas Deus se lembrará da iniquidade deles, para que sejam apreendidos.

[[v26-21-24]]

^<<v26-21-24,24>>^ Portanto, assim diz o SENHOR Deus: Visto que me fazeis lembrar da vossa iniquidade, descobrindo-se as vossas transgressões, aparecendo os vossos pecados em todos os vossos atos, e visto que me viestes à memória, sereis apreendidos por causa disso.

[[v26-21-25]]

^<<v26-21-25,25>>^ E tu, ó profano e perverso, príncipe de Israel, cujo dia virá no tempo do seu castigo final;

[[v26-21-26]]

^<<v26-21-26,26>>^ assim diz o SENHOR Deus: Tira o diadema e remove a coroa; o que é já não será o mesmo; será exaltado o humilde e abatido o soberbo.

[[v26-21-27]]

^<<v26-21-27,27>>^ Ruína! Ruína! A ruínas a reduzirei, e ela já não será, até que venha aquele a quem ela pertence de direito; a ele a darei.

[[v26-21-28]]

^<<v26-21-28,28>>^ E tu, ó filho do homem, profetiza e dize: Assim diz o SENHOR Deus acerca dos filhos de Amom e acerca dos seus insultos; dize, pois: A espada, a espada está desembainhada, polida para a matança, para consumir, para reluzir como relâmpago;

[[v26-21-29]]

^<<v26-21-29,29>>^ para ser posta no pescoço dos profanos, dos perversos, cujo dia virá no tempo do castigo final, ao passo que te pregam visões falsas e te adivinham mentiras.

[[v26-21-30]]

^<<v26-21-30,30>>^ Torna a tua espada à sua bainha. No lugar em que foste formado, na terra do teu nascimento, te julgarei.

[[v26-21-31]]

^<<v26-21-31,31>>^ Derramarei sobre ti a minha indignação, assoprarei contra ti o fogo do meu furor e te entregarei nas mãos de homens brutais, mestres de destruição.

[[v26-21-32]]

^<<v26-21-32,32>>^ Servirás de pasto ao fogo, o teu sangue será derramado no meio da terra, já não serás lembrado; pois eu, o SENHOR, é que falei.

'''

xref:026-ezequiel/026-ezequiel-020.adoc#v26-20-0[&#60; Capítulo Anterior] | <<v26-21-0,Topo>> | xref:026-ezequiel/026-ezequiel-022.adoc#v26-22-0[Próximo Capítulo &#62;]