include::./index.adoc[]

[[v26-41-0]]
=== Ezequiel, 41
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-41-1]]

^<<v26-41-1,1>>^ Então, me levou ao templo e mediu os pilares, seis côvados de largura de um lado e seis de largura do outro, que era a largura do tabernáculo.

[[v26-41-2]]

^<<v26-41-2,2>>^ A largura da entrada: dez côvados; os lados da entrada: cinco côvados de um lado e cinco do outro; também mediu a profundidade da entrada: quarenta côvados, e a largura: vinte côvados.

[[v26-41-3]]

^<<v26-41-3,3>>^ Penetrou e mediu o pilar da entrada: dois côvados, a altura da entrada: seis côvados, e a largura da entrada: sete côvados.

[[v26-41-4]]

^<<v26-41-4,4>>^ Também mediu o seu comprimento: vinte côvados, e a largura: vinte côvados, diante do templo, e me disse: Este é o Santo dos Santos.

[[v26-41-5]]

^<<v26-41-5,5>>^ Então, mediu a parede do templo: seis côvados, e a largura de cada câmara lateral: quatro côvados, por todo o redor do templo.

[[v26-41-6]]

^<<v26-41-6,6>>^ As câmaras laterais estavam em três andares, câmara sobre câmara, trinta em cada andar; e havia reentrâncias na parede do templo ao redor, para as câmaras laterais, para que as vigas se apoiassem nelas e não fossem introduzidas na parede do templo.

[[v26-41-7]]

^<<v26-41-7,7>>^ As câmaras laterais aumentavam em largura de andar para andar, correspondendo às reentrâncias do templo de andar em andar ao redor; daí ter o templo mais largura em cima. Assim, se subia do andar inferior para o superior pelo intermediário.

[[v26-41-8]]

^<<v26-41-8,8>>^ E vi um pavimento elevado ao redor do templo; eram os fundamentos das câmaras laterais de uma cana inteira, isto é, de seis côvados de altura.

[[v26-41-9]]

^<<v26-41-9,9>>^ A grossura da parede das câmaras laterais de fora era de cinco côvados; e a área aberta entre as câmaras laterais, que estavam junto ao templo

[[v26-41-10]]

^<<v26-41-10,10>>^ e às células, tinha a largura de vinte côvados por todo o redor do templo.

[[v26-41-11]]

^<<v26-41-11,11>>^ As entradas das câmaras laterais estavam voltadas para a área aberta: uma entrada para o norte e outra para o sul; a largura da área aberta era de cinco côvados em redor.

[[v26-41-12]]

^<<v26-41-12,12>>^ O edifício que estava numa área separada, do lado ocidental, tinha a largura de setenta côvados; a parede do edifício era de cinco côvados de largura em redor, e o seu comprimento, de noventa côvados.

[[v26-41-13]]

^<<v26-41-13,13>>^ Assim, mediu o templo: cem côvados de comprimento, como também a área separada, o edifício e as suas paredes: cem côvados de comprimento.

[[v26-41-14]]

^<<v26-41-14,14>>^ A largura da frente oriental do templo e da área separada, de uma e de outra parte: cem côvados.

[[v26-41-15]]

^<<v26-41-15,15>>^ Também mediu o comprimento do edifício, que estava na área separada e por detrás do templo, e as suas galerias de uma e de outra parte: cem côvados. O templo propriamente dito, o Santíssimo e o vestíbulo do átrio eram apainelados.

[[v26-41-16]]

^<<v26-41-16,16>>^ As janelas, de fasquias fixas superpostas, estavam ao redor dos três lugares. Dentro, as paredes estavam cobertas de madeira em redor, e isto desde o chão até às janelas, que estavam cobertas.

[[v26-41-17]]

^<<v26-41-17,17>>^ No espaço em cima da porta, e até ao templo de dentro e de fora, e em toda a parede em redor, por dentro e por fora, havia obras de escultura,

[[v26-41-18]]

^<<v26-41-18,18>>^ querubins e palmeiras, de sorte que cada palmeira estava entre querubim e querubim, e cada querubim tinha dois rostos,

[[v26-41-19]]

^<<v26-41-19,19>>^ a saber, um rosto de homem olhava para a palmeira de um lado, e um rosto de leãozinho, para a palmeira do outro lado; assim se fez pela casa toda ao redor.

[[v26-41-20]]

^<<v26-41-20,20>>^ Desde o chão até acima da entrada estavam feitos os querubins e as palmeiras, como também pela parede do templo.

[[v26-41-21]]

^<<v26-41-21,21>>^ As ombreiras do templo eram quadradas, e, no tocante à entrada do Santo dos Santos, era esta da mesma aparência.

[[v26-41-22]]

^<<v26-41-22,22>>^ O altar de madeira era de três côvados de altura, e o seu comprimento, de dois côvados; os seus cantos, a sua base e as suas paredes eram de madeira; e o homem me disse: Esta é a mesa que está perante o SENHOR.

[[v26-41-23]]

^<<v26-41-23,23>>^ O templo e o Santíssimo, ambos tinham duas portas.

[[v26-41-24]]

^<<v26-41-24,24>>^ Havia duas folhas para as portas, duas folhas dobráveis; duas para cada porta.

[[v26-41-25]]

^<<v26-41-25,25>>^ Nelas, isto é, nas portas do templo, foram feitos querubins e palmeiras, como estavam feitos nas paredes, e havia um baldaquino de madeira na frontaria do vestíbulo por fora.

[[v26-41-26]]

^<<v26-41-26,26>>^ E havia janelas de fasquias fixas superpostas e palmeiras, em ambos os lados do vestíbulo, como também nas câmaras laterais do templo e no baldaquino.

'''

xref:026-ezequiel/026-ezequiel-040.adoc#v26-40-0[&#60; Capítulo Anterior] | <<v26-41-0,Topo>> | xref:026-ezequiel/026-ezequiel-042.adoc#v26-42-0[Próximo Capítulo &#62;]