include::./index.adoc[]

[[v26-37-0]]
=== Ezequiel, 37
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-37-1]]

^<<v26-37-1,1>>^ Veio sobre mim a mão do SENHOR; ele me levou pelo Espírito do SENHOR e me deixou no meio de um vale que estava cheio de ossos,

[[v26-37-2]]

^<<v26-37-2,2>>^ e me fez andar ao redor deles; eram mui numerosos na superfície do vale e estavam sequíssimos.

[[v26-37-3]]

^<<v26-37-3,3>>^ Então, me perguntou: Filho do homem, acaso, poderão reviver estes ossos? Respondi: SENHOR Deus, tu o sabes.

[[v26-37-4]]

^<<v26-37-4,4>>^ Disse-me ele: Profetiza a estes ossos e dize-lhes: Ossos secos, ouvi a palavra do SENHOR.

[[v26-37-5]]

^<<v26-37-5,5>>^ Assim diz o SENHOR Deus a estes ossos: Eis que farei entrar o espírito em vós, e vivereis.

[[v26-37-6]]

^<<v26-37-6,6>>^ Porei tendões sobre vós, farei crescer carne sobre vós, sobre vós estenderei pele e porei em vós o espírito, e vivereis. E sabereis que eu sou o SENHOR.

[[v26-37-7]]

^<<v26-37-7,7>>^ Então, profetizei segundo me fora ordenado; enquanto eu profetizava, houve um ruído, um barulho de ossos que batiam contra ossos e se ajuntavam, cada osso ao seu osso.

[[v26-37-8]]

^<<v26-37-8,8>>^ Olhei, e eis que havia tendões sobre eles, e cresceram as carnes, e se estendeu a pele sobre eles; mas não havia neles o espírito.

[[v26-37-9]]

^<<v26-37-9,9>>^ Então, ele me disse: Profetiza ao espírito, profetiza, ó filho do homem, e dize-lhe: Assim diz o SENHOR Deus: Vem dos quatro ventos, ó espírito, e assopra sobre estes mortos, para que vivam.

[[v26-37-10]]

^<<v26-37-10,10>>^ Profetizei como ele me ordenara, e o espírito entrou neles, e viveram e se puseram em pé, um exército sobremodo numeroso.

[[v26-37-11]]

^<<v26-37-11,11>>^ Então, me disse: Filho do homem, estes ossos são toda a casa de Israel. Eis que dizem: Os nossos ossos se secaram, e pereceu a nossa esperança; estamos de todo exterminados.

[[v26-37-12]]

^<<v26-37-12,12>>^ Portanto, profetiza e dize-lhes: Assim diz o SENHOR Deus: Eis que abrirei a vossa sepultura, e vos farei sair dela, ó povo meu, e vos trarei à terra de Israel.

[[v26-37-13]]

^<<v26-37-13,13>>^ Sabereis que eu sou o SENHOR, quando eu abrir a vossa sepultura e vos fizer sair dela, ó povo meu.

[[v26-37-14]]

^<<v26-37-14,14>>^ Porei em vós o meu Espírito, e vivereis, e vos estabelecerei na vossa própria terra. Então, sabereis que eu, o SENHOR, disse isto e o fiz, diz o SENHOR.

[[v26-37-15]]

^<<v26-37-15,15>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-37-16]]

^<<v26-37-16,16>>^ Tu, pois, ó filho do homem, toma um pedaço de madeira e escreve nele: Para Judá e para os filhos de Israel, seus companheiros; depois, toma outro pedaço de madeira e escreve nele: Para José, pedaço de madeira de Efraim, e para toda a casa de Israel, seus companheiros.

[[v26-37-17]]

^<<v26-37-17,17>>^ Ajunta-os um ao outro, faze deles um só pedaço, para que se tornem apenas um na tua mão.

[[v26-37-18]]

^<<v26-37-18,18>>^ Quando te falarem os filhos do teu povo, dizendo: Não nos revelarás o que significam estas coisas?

[[v26-37-19]]

^<<v26-37-19,19>>^ Tu lhes dirás: Assim diz o SENHOR Deus: Eis que tomarei o pedaço de madeira de José, que esteve na mão de Efraim, e das tribos de Israel, suas companheiras, e o ajuntarei ao pedaço de Judá, e farei deles um só pedaço, e se tornarão apenas um na minha mão.

[[v26-37-20]]

^<<v26-37-20,20>>^ Os pedaços de madeira em que houveres escrito estarão na tua mão, perante eles.

[[v26-37-21]]

^<<v26-37-21,21>>^ Dize-lhes, pois: Assim diz o SENHOR Deus: Eis que eu tomarei os filhos de Israel de entre as nações para onde eles foram, e os congregarei de todas as partes, e os levarei para a sua própria terra.

[[v26-37-22]]

^<<v26-37-22,22>>^ Farei deles uma só nação na terra, nos montes de Israel, e um só rei será rei de todos eles. Nunca mais serão duas nações; nunca mais para o futuro se dividirão em dois reinos.

[[v26-37-23]]

^<<v26-37-23,23>>^ Nunca mais se contaminarão com os seus ídolos, nem com as suas abominações, nem com qualquer das suas transgressões; livrá-los-ei de todas as suas apostasias em que pecaram e os purificarei. Assim, eles serão o meu povo, e eu serei o seu Deus.

[[v26-37-24]]

^<<v26-37-24,24>>^ O meu servo Davi reinará sobre eles; todos eles terão um só pastor, andarão nos meus juízos, guardarão os meus estatutos e os observarão.

[[v26-37-25]]

^<<v26-37-25,25>>^ Habitarão na terra que dei a meu servo Jacó, na qual vossos pais habitaram; habitarão nela, eles e seus filhos e os filhos de seus filhos, para sempre; e Davi, meu servo, será seu príncipe eternamente.

[[v26-37-26]]

^<<v26-37-26,26>>^ Farei com eles aliança de paz; será aliança perpétua. Estabelecê-los-ei, e os multiplicarei, e porei o meu santuário no meio deles, para sempre.

[[v26-37-27]]

^<<v26-37-27,27>>^ O meu tabernáculo estará com eles; eu serei o seu Deus, e eles serão o meu povo.

[[v26-37-28]]

^<<v26-37-28,28>>^ As nações saberão que eu sou o SENHOR que santifico a Israel, quando o meu santuário estiver para sempre no meio deles.

'''

xref:026-ezequiel/026-ezequiel-036.adoc#v26-36-0[&#60; Capítulo Anterior] | <<v26-37-0,Topo>> | xref:026-ezequiel/026-ezequiel-038.adoc#v26-38-0[Próximo Capítulo &#62;]