include::./index.adoc[]

[[v26-11-0]]
=== Ezequiel, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-11-1]]

^<<v26-11-1,1>>^ Então, o Espírito me levantou e me levou à porta oriental da Casa do SENHOR, a qual olha para o oriente. À entrada da porta, estavam vinte e cinco homens; no meio deles, vi a Jazanias, filho de Azur, e a Pelatias, filho de Benaías, príncipes do povo.

[[v26-11-2]]

^<<v26-11-2,2>>^ E disse-me: Filho do homem, são estes os homens que maquinam vilezas e aconselham perversamente nesta cidade,

[[v26-11-3]]

^<<v26-11-3,3>>^ os quais dizem: Não está próximo o tempo de construir casas; esta cidade é a panela, e nós, a carne.

[[v26-11-4]]

^<<v26-11-4,4>>^ Portanto, profetiza contra eles, profetiza, ó filho do homem.

[[v26-11-5]]

^<<v26-11-5,5>>^ Caiu, pois, sobre mim o Espírito do SENHOR e disse-me: Fala: Assim diz o SENHOR: Assim tendes dito, ó casa de Israel; porque, quanto às coisas que vos surgem à mente, eu as conheço.

[[v26-11-6]]

^<<v26-11-6,6>>^ Multiplicastes os vossos mortos nesta cidade e deles enchestes as suas ruas.

[[v26-11-7]]

^<<v26-11-7,7>>^ Portanto, assim diz o SENHOR Deus: Os que vós matastes e largastes no meio dela são a carne, e ela, a panela; a vós outros, porém, vos tirarei do meio dela.

[[v26-11-8]]

^<<v26-11-8,8>>^ Temestes a espada, mas a espada trarei sobre vós, diz o SENHOR Deus.

[[v26-11-9]]

^<<v26-11-9,9>>^ Tirar-vos-ei do meio dela, e vos entregarei nas mãos de estrangeiros, e executarei juízos entre vós.

[[v26-11-10]]

^<<v26-11-10,10>>^ Caireis à espada; nos confins de Israel, vos julgarei, e sabereis que eu sou o SENHOR.

[[v26-11-11]]

^<<v26-11-11,11>>^ Esta cidade não vos servirá de panela, nem vós servireis de carne no seu meio; nos confins de Israel, vos julgarei,

[[v26-11-12]]

^<<v26-11-12,12>>^ e sabereis que eu sou o SENHOR. Pois não andastes nos meus estatutos, nem executastes os meus juízos; antes, fizestes segundo os juízos das nações que estão em redor de vós.

[[v26-11-13]]

^<<v26-11-13,13>>^ Ao tempo em que eu profetizava, morreu Pelatias, filho de Benaías. Então, caí com o rosto em terra, clamei em alta voz e disse: ah! SENHOR Deus! Darás fim ao resto de Israel?

[[v26-11-14]]

^<<v26-11-14,14>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-11-15]]

^<<v26-11-15,15>>^ Filho do homem, teus irmãos, os teus próprios irmãos, os homens do teu parentesco e toda a casa de Israel, todos eles são aqueles a quem os habitantes de Jerusalém disseram: Apartai-vos para longe do SENHOR; esta terra se nos deu em possessão.

[[v26-11-16]]

^<<v26-11-16,16>>^ Portanto, dize: Assim diz o SENHOR Deus: Ainda que os lancei para longe entre as nações e ainda que os espalhei pelas terras, todavia, lhes servirei de santuário, por um pouco de tempo, nas terras para onde foram.

[[v26-11-17]]

^<<v26-11-17,17>>^ Dize ainda: Assim diz o SENHOR Deus: Hei de ajuntá-los do meio dos povos, e os recolherei das terras para onde foram lançados, e lhes darei a terra de Israel.

[[v26-11-18]]

^<<v26-11-18,18>>^ Voltarão para ali e tirarão dela todos os seus ídolos detestáveis e todas as suas abominações.

[[v26-11-19]]

^<<v26-11-19,19>>^ Dar-lhes-ei um só coração, espírito novo porei dentro deles; tirarei da sua carne o coração de pedra e lhes darei coração de carne;

[[v26-11-20]]

^<<v26-11-20,20>>^ para que andem nos meus estatutos, e guardem os meus juízos, e os executem; eles serão o meu povo, e eu serei o seu Deus.

[[v26-11-21]]

^<<v26-11-21,21>>^ Mas, quanto àqueles cujo coração se compraz em seus ídolos detestáveis e abominações, eu farei recair sobre sua cabeça as suas obras, diz o SENHOR Deus.

[[v26-11-22]]

^<<v26-11-22,22>>^ Então, os querubins elevaram as suas asas, e as rodas os acompanhavam; e a glória do Deus de Israel estava no alto, sobre eles.

[[v26-11-23]]

^<<v26-11-23,23>>^ A glória do SENHOR subiu do meio da cidade e se pôs sobre o monte que está ao oriente da cidade.

[[v26-11-24]]

^<<v26-11-24,24>>^ Depois, o Espírito de Deus me levantou e me levou na sua visão à Caldeia, para os do cativeiro; e de mim se foi a visão que eu tivera.

[[v26-11-25]]

^<<v26-11-25,25>>^ Então, falei aos do cativeiro todas as coisas que o SENHOR me havia mostrado.

'''

xref:026-ezequiel/026-ezequiel-010.adoc#v26-10-0[&#60; Capítulo Anterior] | <<v26-11-0,Topo>> | xref:026-ezequiel/026-ezequiel-012.adoc#v26-12-0[Próximo Capítulo &#62;]