include::./index.adoc[]

[[v26-46-0]]
=== Ezequiel, 46
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-46-1]]

^<<v26-46-1,1>>^ Assim diz o SENHOR Deus: A porta do átrio interior, que olha para o oriente, estará fechada durante os seis dias que são de trabalho; mas no sábado ela se abrirá e também no dia da Festa da Lua Nova.

[[v26-46-2]]

^<<v26-46-2,2>>^ O príncipe entrará de fora pelo vestíbulo da porta e permanecerá junto da ombreira da porta; os sacerdotes prepararão o holocausto dele e os seus sacrifícios pacíficos, e ele adorará no limiar da porta e sairá; mas a porta não se fechará até à tarde.

[[v26-46-3]]

^<<v26-46-3,3>>^ O povo da terra adorará na entrada da mesma porta, nos sábados e nas Festas da Lua Nova, diante do SENHOR.

[[v26-46-4]]

^<<v26-46-4,4>>^ O holocausto que o príncipe oferecer ao SENHOR serão, no dia de sábado, seis cordeiros sem defeito e um carneiro sem defeito.

[[v26-46-5]]

^<<v26-46-5,5>>^ A oferta de manjares será um efa para cada carneiro; para cada cordeiro, a oferta de manjares será o que puder dar; e de azeite, um him para cada efa.

[[v26-46-6]]

^<<v26-46-6,6>>^ Mas, no dia da Festa da Lua Nova, será um novilho sem defeito e seis cordeiros e um carneiro; eles serão sem defeito.

[[v26-46-7]]

^<<v26-46-7,7>>^ Preparará por oferta de manjares um efa para cada novilho e um efa para cada carneiro, mas, pelos cordeiros, segundo puder; e um him de azeite para cada efa.

[[v26-46-8]]

^<<v26-46-8,8>>^ Quando entrar o príncipe, entrará pelo vestíbulo da porta e sairá pelo mesmo caminho.

[[v26-46-9]]

^<<v26-46-9,9>>^ Mas, quando vier o povo da terra perante o SENHOR, nas festas fixas, aquele que entrar pela porta do norte, para adorar, sairá pela porta do sul; e aquele que entrar pela porta do sul sairá pela porta do norte; não tornará pela porta por onde entrou, mas sairá pela porta oposta.

[[v26-46-10]]

^<<v26-46-10,10>>^ O príncipe entrará no meio deles, quando eles entrarem; em saindo eles, ele sairá.

[[v26-46-11]]

^<<v26-46-11,11>>^ Nas solenidades e nas festas fixas, a oferta de manjares será um efa para cada novilho e um para cada carneiro; mas, pelos cordeiros, o que puder dar; e de azeite, um him para cada efa.

[[v26-46-12]]

^<<v26-46-12,12>>^ Quando o príncipe preparar holocausto ou sacrifícios pacíficos como oferta voluntária ao SENHOR, então, lhe abrirão a porta que olha para o oriente, e fará ele o seu holocausto e os seus sacrifícios pacíficos, como costuma fazer no dia de sábado; e sairá, e se fechará a porta depois de ele sair.

[[v26-46-13]]

^<<v26-46-13,13>>^ Prepararás um cordeiro de um ano, sem defeito, em holocausto ao SENHOR, cada dia; manhã após manhã, o prepararás.

[[v26-46-14]]

^<<v26-46-14,14>>^ Juntamente com ele, prepararás, manhã após manhã, uma oferta de manjares para o SENHOR, a sexta parte de um efa e, de azeite, a terça parte de um him, para misturar com a flor de farinha. Isto é estatuto perpétuo e contínuo.

[[v26-46-15]]

^<<v26-46-15,15>>^ Assim prepararão o cordeiro, e a oferta de manjares, e o azeite, manhã após manhã, em holocausto contínuo.

[[v26-46-16]]

^<<v26-46-16,16>>^ Assim diz o SENHOR Deus: Quando o príncipe der um presente de sua herança a alguns de seus filhos, pertencerá a estes; será possessão deles por herança.

[[v26-46-17]]

^<<v26-46-17,17>>^ Mas, dando ele um presente da sua herança a algum dos seus servos, será deste até ao ano da liberdade; então, tornará para o príncipe, porque a seus filhos, somente a eles, pertencerá a herança.

[[v26-46-18]]

^<<v26-46-18,18>>^ O príncipe não tomará nada da herança do povo, não os esbulhará da sua possessão; da sua própria possessão deixará herança a seus filhos, para que o meu povo não seja retirado, cada um da sua possessão.

[[v26-46-19]]

^<<v26-46-19,19>>^ Depois disto, o homem me trouxe, pela entrada que estava ao lado da porta, às câmaras santas dos sacerdotes, as quais olhavam para o norte; e eis que ali havia um lugar nos fundos extremos que olham para o ocidente.

[[v26-46-20]]

^<<v26-46-20,20>>^ Ele me disse: Este é o lugar onde os sacerdotes cozerão a oferta pela culpa e a oferta pelo pecado e onde cozerão a oferta de manjares, para que não a tragam ao átrio exterior e assim santifiquem o povo.

[[v26-46-21]]

^<<v26-46-21,21>>^ Então, me levou para fora, para o átrio exterior, e me fez passar aos quatro cantos do átrio; e eis que em cada canto do átrio havia outro átrio.

[[v26-46-22]]

^<<v26-46-22,22>>^ Nos quatro cantos do átrio havia átrios pequenos, menores, de quarenta côvados de comprimento e trinta de largura; estes quatro cantos tinham a mesma dimensão.

[[v26-46-23]]

^<<v26-46-23,23>>^ Havia um muro ao redor dos átrios, ao redor dos quatro, e havia lugares para cozer ao pé dos muros ao redor.

[[v26-46-24]]

^<<v26-46-24,24>>^ E me disse: São estas as cozinhas, onde os ministros do templo cozerão o sacrifício do povo.

'''

xref:026-ezequiel/026-ezequiel-045.adoc#v26-45-0[&#60; Capítulo Anterior] | <<v26-46-0,Topo>> | xref:026-ezequiel/026-ezequiel-047.adoc#v26-47-0[Próximo Capítulo &#62;]