include::./index.adoc[]

[[v26-30-0]]
=== Ezequiel, 30
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-30-1]]

^<<v26-30-1,1>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-30-2]]

^<<v26-30-2,2>>^ Filho do homem, profetiza e dize: Assim diz o SENHOR Deus: Gemei: Ah! Aquele dia!

[[v26-30-3]]

^<<v26-30-3,3>>^ Porque está perto o dia, sim, está perto o Dia do SENHOR, dia nublado; será o tempo dos gentios.

[[v26-30-4]]

^<<v26-30-4,4>>^ A espada virá contra o Egito, e haverá grande dor na Etiópia, quando caírem os traspassados no Egito; o seu povo será levado para o cativeiro, e serão destruídos os seus fundamentos.

[[v26-30-5]]

^<<v26-30-5,5>>^ A Etiópia, Pute e Lude e toda a Arábia, os de Cube e os outros aliados do Egito cairão juntamente com ele à espada.

[[v26-30-6]]

^<<v26-30-6,6>>^ Assim diz o SENHOR: Também cairão os que sustêm o Egito, e será humilhado o orgulho do seu poder; desde Migdol até Sevene, cairão à espada, diz o SENHOR Deus.

[[v26-30-7]]

^<<v26-30-7,7>>^ Serão desolados no meio das terras desertas; e as suas cidades estarão no meio das cidades devastadas.

[[v26-30-8]]

^<<v26-30-8,8>>^ Saberão que eu sou o SENHOR, quando eu tiver posto fogo no Egito e se acharem destruídos todos os que lhe prestavam auxílio.

[[v26-30-9]]

^<<v26-30-9,9>>^ Naquele dia, sairão mensageiros de diante de mim em navios, para espantarem a Etiópia descuidada; e sobre ela haverá angústia, como no dia do Egito; pois eis que já vem.

[[v26-30-10]]

^<<v26-30-10,10>>^ Assim diz o SENHOR Deus: Eu, pois, farei cessar a pompa do Egito, por intermédio de Nabucodonosor, rei da Babilônia.

[[v26-30-11]]

^<<v26-30-11,11>>^ Ele e o seu povo com ele, os mais terríveis das nações, serão levados para destruírem a terra; desembainharão a espada contra o Egito e encherão de traspassados a terra.

[[v26-30-12]]

^<<v26-30-12,12>>^ Secarei os rios e venderei a terra, entregando-a nas mãos dos maus; por meio de estrangeiros, farei desolada a terra e tudo o que nela houver; eu, o SENHOR, é que falei.

[[v26-30-13]]

^<<v26-30-13,13>>^ Assim diz o SENHOR Deus: Também destruirei os ídolos e darei cabo das imagens em Mênfis; já não haverá príncipe na terra do Egito, onde implantarei o terror.

[[v26-30-14]]

^<<v26-30-14,14>>^ Farei desolada a Patros, porei fogo em Zoã e executarei juízo em Nô.

[[v26-30-15]]

^<<v26-30-15,15>>^ Derramarei o meu furor sobre Sim, fortaleza do Egito, e exterminarei a multidão de Nô.

[[v26-30-16]]

^<<v26-30-16,16>>^ Atearei fogo no Egito; Sim terá grande angústia, Nô será destruída, e Mênfis terá adversários em pleno dia.

[[v26-30-17]]

^<<v26-30-17,17>>^ Os jovens de Áven e de Pi-Besete cairão à espada, e estas cidades cairão em cativeiro.

[[v26-30-18]]

^<<v26-30-18,18>>^ Em Tafnes, se escurecerá o dia, quando eu quebrar ali os jugos do Egito e nela cessar o orgulho do seu poder; uma nuvem a cobrirá, e suas filhas cairão em cativeiro.

[[v26-30-19]]

^<<v26-30-19,19>>^ Assim, executarei juízo no Egito, e saberão que eu sou o SENHOR.

[[v26-30-20]]

^<<v26-30-20,20>>^ No undécimo ano, no mês primeiro, aos sete dias do mês, veio a mim a palavra do SENHOR, dizendo:

[[v26-30-21]]

^<<v26-30-21,21>>^ Filho do homem, eu quebrei o braço de Faraó, rei do Egito, e eis que não foi atado, nem tratado com remédios, nem lhe porão ligaduras, para tornar-se forte e pegar da espada.

[[v26-30-22]]

^<<v26-30-22,22>>^ Portanto, assim diz o SENHOR Deus: Eis que eu estou contra Faraó, rei do Egito; quebrar-lhe-ei os braços, tanto o forte como o que já está quebrado, e lhe farei cair da mão a espada.

[[v26-30-23]]

^<<v26-30-23,23>>^ Espalharei os egípcios entre as nações e os derramarei pelas terras.

[[v26-30-24]]

^<<v26-30-24,24>>^ Fortalecerei os braços do rei da Babilônia e lhe porei na mão a minha espada; mas quebrarei os braços de Faraó, que, diante dele, gemerá como geme o traspassado.

[[v26-30-25]]

^<<v26-30-25,25>>^ Levantarei os braços do rei da Babilônia, mas os braços de Faraó cairão; e saberão que eu sou o SENHOR, quando eu puser a minha espada na mão do rei da Babilônia e ele a estender contra a terra do Egito.

[[v26-30-26]]

^<<v26-30-26,26>>^ Espalharei os egípcios entre as nações e os derramarei pelas terras; assim, saberão que eu sou o SENHOR.

'''

xref:026-ezequiel/026-ezequiel-029.adoc#v26-29-0[&#60; Capítulo Anterior] | <<v26-30-0,Topo>> | xref:026-ezequiel/026-ezequiel-031.adoc#v26-31-0[Próximo Capítulo &#62;]