include::./index.adoc[]

[[v26-48-0]]
=== Ezequiel, 48
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-48-1]]

^<<v26-48-1,1>>^ São estes os nomes das tribos: desde a parte extrema do norte, via Hetlom, até à entrada de Hamate, até Hazar-Enom, o limite norte de Damasco até junto de Hamate e desde o lado oriental até ao ocidente, Dã terá uma porção.

[[v26-48-2]]

^<<v26-48-2,2>>^ Limitando-se com Dã, desde o lado oriental até ao ocidental, Aser, uma porção.

[[v26-48-3]]

^<<v26-48-3,3>>^ Limitando-se com Aser, desde o lado oriental até ao ocidental, Naftali, uma porção.

[[v26-48-4]]

^<<v26-48-4,4>>^ Limitando-se com Naftali, desde o lado oriental até ao ocidental, Manassés, uma porção.

[[v26-48-5]]

^<<v26-48-5,5>>^ Limitando-se com Manassés, desde o lado oriental até ao ocidental, Efraim, uma porção.

[[v26-48-6]]

^<<v26-48-6,6>>^ Limitando-se com Efraim, desde o lado oriental até ao ocidental, Rúben, uma porção.

[[v26-48-7]]

^<<v26-48-7,7>>^ Limitando-se com Rúben, desde o lado oriental até ao ocidental, Judá, uma porção.

[[v26-48-8]]

^<<v26-48-8,8>>^ Limitando-se com Judá, desde o lado oriental até ao ocidental, será a região sagrada que haveis de separar, de vinte e cinco mil côvados de largura e de comprimento, o mesmo que o das porções, desde o lado oriental até ao ocidental; o santuário estará no meio dela.

[[v26-48-9]]

^<<v26-48-9,9>>^ A região que haveis de separar ao SENHOR será do comprimento de vinte e cinco mil côvados e da largura de dez mil.

[[v26-48-10]]

^<<v26-48-10,10>>^ Esta região santa dos sacerdotes terá, ao norte, vinte e cinco mil côvados, ao ocidente, dez mil de largura, ao oriente, dez mil de largura e ao sul, vinte e cinco mil de comprimento; o santuário do SENHOR estará no meio dela.

[[v26-48-11]]

^<<v26-48-11,11>>^ Será para os sacerdotes santificados, para os filhos de Zadoque, que cumpriram o seu dever e não andaram errados, quando os filhos de Israel se extraviaram, como fizeram os levitas.

[[v26-48-12]]

^<<v26-48-12,12>>^ Será região especial dentro da região sagrada, lugar santíssimo, fazendo limites com a porção dos levitas.

[[v26-48-13]]

^<<v26-48-13,13>>^ Os levitas, segundo o limite dos sacerdotes, terão vinte e cinco mil côvados de comprimento e dez mil de largura; todo o comprimento será vinte e cinco mil, e a largura, dez mil.

[[v26-48-14]]

^<<v26-48-14,14>>^ Não venderão nada disto, nem trocarão, nem transferirão a outrem o melhor da terra, porque é santo ao SENHOR.

[[v26-48-15]]

^<<v26-48-15,15>>^ Mas os cinco mil côvados que ficaram da largura diante dos vinte e cinco mil serão para o uso civil da cidade, para habitação e para arredores; a cidade estará no meio.

[[v26-48-16]]

^<<v26-48-16,16>>^ Serão estas as suas medidas: o lado norte, de quatro mil e quinhentos côvados, o lado sul, de quatro mil e quinhentos, o lado oriental, de quatro mil e quinhentos, e o lado ocidental, de quatro mil e quinhentos.

[[v26-48-17]]

^<<v26-48-17,17>>^ Os arredores da cidade serão, ao norte, de duzentos e cinquenta côvados, ao sul, de duzentos e cinquenta côvados, ao oriente, de duzentos e cinquenta e, ao ocidente, de duzentos e cinquenta.

[[v26-48-18]]

^<<v26-48-18,18>>^ Quanto ao que ficou do resto do comprimento, paralelo à região sagrada, será de dez mil para o oriente e de dez mil para o ocidente e corresponderá à região sagrada; e o seu produto será para o sustento daqueles que trabalham na cidade.

[[v26-48-19]]

^<<v26-48-19,19>>^ Lavrá-lo-ão os trabalhadores da cidade, provindos de todas as tribos de Israel.

[[v26-48-20]]

^<<v26-48-20,20>>^ A região toda será de vinte e cinco mil côvados em quadrado, isto é, a região sagrada juntamente com a possessão da cidade.

[[v26-48-21]]

^<<v26-48-21,21>>^ O que restar será para o príncipe, deste e do outro lado da região sagrada e da possessão da cidade. Por isso, aquilo que se estende dos vinte e cinco mil côvados em direção do oriente e também dos vinte e cinco mil côvados em direção do ocidente, paralelamente com as porções, será do príncipe; a região sagrada e o santuário do templo estarão no meio.

[[v26-48-22]]

^<<v26-48-22,22>>^ Excetuando o que pertence aos levitas e a cidade que está no meio daquilo que pertence ao príncipe, entre o território de Judá e o de Benjamim, será isso para o príncipe.

[[v26-48-23]]

^<<v26-48-23,23>>^ Quanto ao resto das tribos, desde o lado oriental até ao ocidental, Benjamim terá uma porção.

[[v26-48-24]]

^<<v26-48-24,24>>^ Limitando-se com Benjamim, desde o lado oriental até ao ocidental, Simeão, uma porção.

[[v26-48-25]]

^<<v26-48-25,25>>^ Limitando-se com Simeão, desde o lado oriental até ao ocidental, Issacar, uma porção.

[[v26-48-26]]

^<<v26-48-26,26>>^ Limitando-se com Issacar, desde o lado oriental até ao ocidental, Zebulom, uma porção.

[[v26-48-27]]

^<<v26-48-27,27>>^ Limitando-se com Zebulom, desde o lado oriental até ao ocidental, Gade, uma porção.

[[v26-48-28]]

^<<v26-48-28,28>>^ Limitando-se com o território de Gade, ao sul, o limite será desde Tamar até às águas de Meribá-Cades, ao longo do ribeiro do Egito até ao mar Grande.

[[v26-48-29]]

^<<v26-48-29,29>>^ Esta é a terra que sorteareis em herança às tribos de Israel; e estas, as suas porções, diz o SENHOR Deus.

[[v26-48-30]]

^<<v26-48-30,30>>^ São estas as saídas da cidade: do lado norte, que mede quatro mil e quinhentos côvados,

[[v26-48-31]]

^<<v26-48-31,31>>^ três portas: a porta de Rúben, a de Judá e a de Levi, tomando as portas da cidade os nomes das tribos de Israel;

[[v26-48-32]]

^<<v26-48-32,32>>^ do lado oriental, quatro mil e quinhentos côvados e três portas, a saber: a porta de José, a de Benjamim e a de Dã;

[[v26-48-33]]

^<<v26-48-33,33>>^ do lado sul, quatro mil e quinhentos côvados e três portas: a porta de Simeão, a de Issacar e a de Zebulom;

[[v26-48-34]]

^<<v26-48-34,34>>^ do lado ocidental, quatro mil e quinhentos côvados e as suas três portas: a porta de Gade, a de Aser e a de Naftali.

[[v26-48-35]]

^<<v26-48-35,35>>^ Dezoito mil côvados em redor; e o nome da cidade desde aquele dia será: O SENHOR Está Ali.

'''

xref:026-ezequiel/026-ezequiel-047.adoc#v26-47-0[&#60; Capítulo Anterior] | <<v26-48-0,Topo>> | xref:027-daniel/027-daniel-001.adoc#v27-1-0[Próximo Capítulo &#62;]