include::./index.adoc[]

[[v26-6-0]]
=== Ezequiel, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-6-1]]

^<<v26-6-1,1>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-6-2]]

^<<v26-6-2,2>>^ Filho do homem, vira o rosto para os montes de Israel e profetiza contra eles, dizendo:

[[v26-6-3]]

^<<v26-6-3,3>>^ Montes de Israel, ouvi a palavra do SENHOR Deus: Assim diz o SENHOR Deus aos montes, aos outeiros, aos ribeiros e aos vales: Eis que eu, eu mesmo, trarei a espada sobre vós e destruirei os vossos altos.

[[v26-6-4]]

^<<v26-6-4,4>>^ Ficarão desolados os vossos altares, e quebrados, os vossos altares de incenso; arrojarei os vossos mortos à espada, diante dos vossos ídolos.

[[v26-6-5]]

^<<v26-6-5,5>>^ Porei os cadáveres dos filhos de Israel diante dos seus ídolos e espalharei os vossos ossos ao redor dos vossos altares.

[[v26-6-6]]

^<<v26-6-6,6>>^ Em todos os vossos lugares habitáveis, as cidades serão destruídas, e os altos ficarão desolados, para que os vossos altares sejam destruídos e arruinados, e os vossos ídolos, quebrados e extintos, e os vossos altares do incenso sejam eliminados, e desfeitas as vossas obras.

[[v26-6-7]]

^<<v26-6-7,7>>^ Os mortos à espada cairão no meio de vós, para que saibais que eu sou o SENHOR.

[[v26-6-8]]

^<<v26-6-8,8>>^ Mas deixarei um resto, porquanto alguns de vós escapareis da espada entre as nações, quando fordes espalhados pelas terras.

[[v26-6-9]]

^<<v26-6-9,9>>^ Então, se lembrarão de mim os que dentre vós escaparem entre as nações para onde foram levados em cativeiro; pois me quebrantei por causa do seu coração dissoluto, que se desviou de mim, e por causa dos seus olhos, que se prostituíram após os seus ídolos. Eles terão nojo de si mesmos, por causa dos males que fizeram em todas as suas abominações.

[[v26-6-10]]

^<<v26-6-10,10>>^ Saberão que eu sou o SENHOR e não disse debalde que lhes faria este mal.

[[v26-6-11]]

^<<v26-6-11,11>>^ Assim diz o SENHOR Deus: Bate as palmas, bate com o pé e dize: Ah! Por todas as terríveis abominações da casa de Israel! Pois cairão à espada, e de fome, e de peste.

[[v26-6-12]]

^<<v26-6-12,12>>^ O que estiver longe morrerá de peste; o que estiver perto cairá à espada; e o que ficar de resto e cercado morrerá de fome. Assim, neles cumprirei o meu furor.

[[v26-6-13]]

^<<v26-6-13,13>>^ Então, sabereis que eu sou o SENHOR, quando os seus mortos à espada jazerem no meio dos seus ídolos, em redor dos seus altares, em todo outeiro alto, em todos os cimos dos montes e debaixo de toda árvore frondosa, debaixo de todo carvalho espesso, lugares onde ofereciam suave perfume a todos os seus ídolos.

[[v26-6-14]]

^<<v26-6-14,14>>^ Estenderei a mão sobre eles e farei a terra tornar-se desolada, desolada desde o deserto até Ribla, em todas as suas habitações; e saberão que eu sou o SENHOR.

'''

xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[&#60; Capítulo Anterior] | <<v26-6-0,Topo>> | xref:026-ezequiel/026-ezequiel-007.adoc#v26-7-0[Próximo Capítulo &#62;]