include::./index.adoc[]

[[v26-36-0]]
=== Ezequiel, 36
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-36-1]]

^<<v26-36-1,1>>^ Tu, ó filho do homem, profetiza aos montes de Israel e dize: Montes de Israel, ouvi a palavra do SENHOR.

[[v26-36-2]]

^<<v26-36-2,2>>^ Assim diz o SENHOR Deus: Visto que diz o inimigo contra vós outros: Bem feito!, e também: Os eternos lugares altos são nossa herança,

[[v26-36-3]]

^<<v26-36-3,3>>^ portanto, profetiza e dize: Assim diz o SENHOR Deus: Visto que vos assolaram e procuraram abocar-vos de todos os lados, para que fôsseis possessão do resto das nações e andais em lábios paroleiros e na infâmia do povo,

[[v26-36-4]]

^<<v26-36-4,4>>^ portanto, ouvi, ó montes de Israel, a palavra do SENHOR Deus: Assim diz o SENHOR Deus aos montes e aos outeiros, às correntes e aos vales, aos lugares desertos e desolados e às cidades desamparadas, que se tornaram rapina e escárnio para o resto das nações circunvizinhas.

[[v26-36-5]]

^<<v26-36-5,5>>^ Portanto, assim diz o SENHOR Deus: Certamente, no fogo do meu zelo, falei contra o resto das nações e contra todo o Edom. Eles se apropriaram da minha terra, com alegria de todo o coração e com menosprezo de alma, para despovoá-la e saqueá-la.

[[v26-36-6]]

^<<v26-36-6,6>>^ Portanto, profetiza sobre a terra de Israel e dize aos montes e aos outeiros, às correntes e aos vales: Assim diz o SENHOR Deus: Eis que falei no meu zelo e no meu furor, porque levastes sobre vós o opróbrio das nações.

[[v26-36-7]]

^<<v26-36-7,7>>^ Portanto, assim diz o SENHOR Deus: Levantando eu a mão, jurei que as nações que estão ao redor de vós levem o seu opróbrio sobre si mesmas.

[[v26-36-8]]

^<<v26-36-8,8>>^ Mas vós, ó montes de Israel, vós produzireis os vossos ramos e dareis o vosso fruto para o meu povo de Israel, o qual está prestes a vir.

[[v26-36-9]]

^<<v26-36-9,9>>^ Porque eis que eu estou convosco; voltar-me-ei para vós outros, e sereis lavrados e semeados.

[[v26-36-10]]

^<<v26-36-10,10>>^ Multiplicarei homens sobre vós, a toda a casa de Israel, sim, toda; as cidades serão habitadas, e os lugares devastados serão edificados.

[[v26-36-11]]

^<<v26-36-11,11>>^ Multiplicarei homens e animais sobre vós; eles se multiplicarão e serão fecundos; fá-los-ei habitar-vos como dantes e vos tratarei melhor do que outrora; e sabereis que eu sou o SENHOR.

[[v26-36-12]]

^<<v26-36-12,12>>^ Farei andar sobre vós homens, o meu povo de Israel; eles vos possuirão, e sereis a sua herança e jamais os desfilhareis.

[[v26-36-13]]

^<<v26-36-13,13>>^ Assim diz o SENHOR Deus: Visto que te dizem: Tu és terra que devora os homens e és terra que desfilha o seu povo,

[[v26-36-14]]

^<<v26-36-14,14>>^ por isso, tu não devorarás mais os homens, nem desfilharás mais o teu povo, diz o SENHOR Deus.

[[v26-36-15]]

^<<v26-36-15,15>>^ Não te permitirei jamais que ouças a ignomínia dos gentios; não mais levarás sobre ti o opróbrio dos povos, nem mais farás tropeçar o teu povo, diz o SENHOR Deus.

[[v26-36-16]]

^<<v26-36-16,16>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-36-17]]

^<<v26-36-17,17>>^ Filho do homem, quando os da casa de Israel habitavam na sua terra, eles a contaminaram com os seus caminhos e as suas ações; como a imundícia de uma mulher em sua menstruação, tal era o seu caminho perante mim.

[[v26-36-18]]

^<<v26-36-18,18>>^ Derramei, pois, o meu furor sobre eles, por causa do sangue que derramaram sobre a terra e por causa dos seus ídolos com que a contaminaram.

[[v26-36-19]]

^<<v26-36-19,19>>^ Espalhei-os entre as nações, e foram derramados pelas terras; segundo os seus caminhos e segundo os seus feitos, eu os julguei.

[[v26-36-20]]

^<<v26-36-20,20>>^ Em chegando às nações para onde foram, profanaram o meu santo nome, pois deles se dizia: São estes o povo do SENHOR, porém tiveram de sair da terra dele.

[[v26-36-21]]

^<<v26-36-21,21>>^ Mas tive compaixão do meu santo nome, que a casa de Israel profanou entre as nações para onde foi.

[[v26-36-22]]

^<<v26-36-22,22>>^ Dize, portanto, à casa de Israel: Assim diz o SENHOR Deus: Não é por amor de vós que eu faço isto, ó casa de Israel, mas pelo meu santo nome, que profanastes entre as nações para onde fostes.

[[v26-36-23]]

^<<v26-36-23,23>>^ Vindicarei a santidade do meu grande nome, que foi profanado entre as nações, o qual profanastes no meio delas; as nações saberão que eu sou o SENHOR, diz o SENHOR Deus, quando eu vindicar a minha santidade perante elas.

[[v26-36-24]]

^<<v26-36-24,24>>^ Tomar-vos-ei de entre as nações, e vos congregarei de todos os países, e vos trarei para a vossa terra.

[[v26-36-25]]

^<<v26-36-25,25>>^ Então, aspergirei água pura sobre vós, e ficareis purificados; de todas as vossas imundícias e de todos os vossos ídolos vos purificarei.

[[v26-36-26]]

^<<v26-36-26,26>>^ Dar-vos-ei coração novo e porei dentro de vós espírito novo; tirarei de vós o coração de pedra e vos darei coração de carne.

[[v26-36-27]]

^<<v26-36-27,27>>^ Porei dentro de vós o meu Espírito e farei que andeis nos meus estatutos, guardeis os meus juízos e os observeis.

[[v26-36-28]]

^<<v26-36-28,28>>^ Habitareis na terra que eu dei a vossos pais; vós sereis o meu povo, e eu serei o vosso Deus.

[[v26-36-29]]

^<<v26-36-29,29>>^ Livrar-vos-ei de todas as vossas imundícias; farei vir o trigo, e o multiplicarei, e não trarei fome sobre vós.

[[v26-36-30]]

^<<v26-36-30,30>>^ Multiplicarei o fruto das árvores e a novidade do campo, para que jamais recebais o opróbrio da fome entre as nações.

[[v26-36-31]]

^<<v26-36-31,31>>^ Então, vos lembrareis dos vossos maus caminhos e dos vossos feitos que não foram bons; tereis nojo de vós mesmos por causa das vossas iniquidades e das vossas abominações.

[[v26-36-32]]

^<<v26-36-32,32>>^ Não é por amor de vós, fique bem-entendido, que eu faço isto, diz o SENHOR Deus. Envergonhai-vos e confundi-vos por causa dos vossos caminhos, ó casa de Israel.

[[v26-36-33]]

^<<v26-36-33,33>>^ Assim diz o SENHOR Deus: No dia em que eu vos purificar de todas as vossas iniquidades, então, farei que sejam habitadas as cidades e sejam edificados os lugares desertos.

[[v26-36-34]]

^<<v26-36-34,34>>^ Lavrar-se-á a terra deserta, em vez de estar desolada aos olhos de todos os que passam.

[[v26-36-35]]

^<<v26-36-35,35>>^ Dir-se-á: Esta terra desolada ficou como o jardim do Éden; as cidades desertas, desoladas e em ruínas estão fortificadas e habitadas.

[[v26-36-36]]

^<<v26-36-36,36>>^ Então, as nações que tiverem restado ao redor de vós saberão que eu, o SENHOR, reedifiquei as cidades destruídas e replantei o que estava abandonado. Eu, o SENHOR, o disse e o farei.

[[v26-36-37]]

^<<v26-36-37,37>>^ Assim diz o SENHOR Deus: Ainda nisto permitirei que seja eu solicitado pela casa de Israel: que lhe multiplique eu os homens como um rebanho.

[[v26-36-38]]

^<<v26-36-38,38>>^ Como um rebanho de santos, o rebanho de Jerusalém nas suas festas fixas, assim as cidades desertas se encherão de rebanhos de homens; e saberão que eu sou o SENHOR.

'''

xref:026-ezequiel/026-ezequiel-035.adoc#v26-35-0[&#60; Capítulo Anterior] | <<v26-36-0,Topo>> | xref:026-ezequiel/026-ezequiel-037.adoc#v26-37-0[Próximo Capítulo &#62;]