include::./index.adoc[]

[[v26-35-0]]
=== Ezequiel, 35
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-35-1]]

^<<v26-35-1,1>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-35-2]]

^<<v26-35-2,2>>^ Filho do homem, volve o rosto contra o monte Seir e profetiza contra ele.

[[v26-35-3]]

^<<v26-35-3,3>>^ Dize-lhe: Assim diz o SENHOR Deus: Eis que eu estou contra ti, ó monte Seir, e estenderei a mão contra ti, e te farei desolação e espanto.

[[v26-35-4]]

^<<v26-35-4,4>>^ Farei desertas as tuas cidades, e tu serás desolado; e saberás que eu sou o SENHOR.

[[v26-35-5]]

^<<v26-35-5,5>>^ Pois guardaste inimizade perpétua e abandonaste os filhos de Israel à violência da espada, no tempo da calamidade e do castigo final.

[[v26-35-6]]

^<<v26-35-6,6>>^ Por isso, diz o SENHOR Deus, tão certo como eu vivo, eu te fiz sangrar, e sangue te perseguirá; visto que não aborreceste o sangue, o sangue te perseguirá.

[[v26-35-7]]

^<<v26-35-7,7>>^ Farei do monte Seir extrema desolação e eliminarei dele o que por ele passa e o que por ele volta.

[[v26-35-8]]

^<<v26-35-8,8>>^ Encherei os seus montes dos seus traspassados; nos teus outeiros, nos teus vales e em todas as tuas correntes, cairão os traspassados à espada.

[[v26-35-9]]

^<<v26-35-9,9>>^ Em perpétuas desolações, te porei, e as tuas cidades jamais serão habitadas; assim sabereis que eu sou o SENHOR.

[[v26-35-10]]

^<<v26-35-10,10>>^ Visto que dizes: Os dois povos e as duas terras serão meus, e os possuirei, ainda que o SENHOR se achava ali,

[[v26-35-11]]

^<<v26-35-11,11>>^ por isso, tão certo como eu vivo, diz o SENHOR Deus, procederei segundo a tua ira e segundo a tua inveja, com que, no teu ódio, os trataste; e serei conhecido deles, quando te julgar.

[[v26-35-12]]

^<<v26-35-12,12>>^ Saberás que eu, o SENHOR, ouvi todas as blasfêmias que proferiste contra os montes de Israel, dizendo: Já estão desolados, a nós nos são entregues por pasto.

[[v26-35-13]]

^<<v26-35-13,13>>^ Vós vos engrandecestes contra mim com a vossa boca e multiplicastes as vossas palavras contra mim; eu o ouvi.

[[v26-35-14]]

^<<v26-35-14,14>>^ Assim diz o SENHOR Deus: Ao alegrar-se toda a terra, eu te reduzirei à desolação.

[[v26-35-15]]

^<<v26-35-15,15>>^ Como te alegraste com a sorte da casa de Israel, porque foi desolada, assim também farei a ti; desolado serás, ó monte Seir e todo o Edom, sim, todo; e saberão que eu sou o SENHOR.

'''

xref:026-ezequiel/026-ezequiel-034.adoc#v26-34-0[&#60; Capítulo Anterior] | <<v26-35-0,Topo>> | xref:026-ezequiel/026-ezequiel-036.adoc#v26-36-0[Próximo Capítulo &#62;]