include::./index.adoc[]

[[v26-19-0]]
=== Ezequiel, 19
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-19-1]]

^<<v26-19-1,1>>^ E tu levanta uma lamentação sobre os príncipes de Israel

[[v26-19-2]]

^<<v26-19-2,2>>^ e dize: Quem é tua mãe? Uma leoa entre leões, a qual, deitada entre os leõezinhos, criou os seus filhotes.

[[v26-19-3]]

^<<v26-19-3,3>>^ Criou um dos seus filhotinhos, o qual veio a ser leãozinho, e aprendeu a apanhar a presa, e devorou homens.

[[v26-19-4]]

^<<v26-19-4,4>>^ As nações ouviram falar dele, e foi ele apanhado na cova que elas fizeram e levado com ganchos para a terra do Egito.

[[v26-19-5]]

^<<v26-19-5,5>>^ Vendo a leoa frustrada e perdida a sua esperança, tomou outro dos seus filhotes e o fez leãozinho.

[[v26-19-6]]

^<<v26-19-6,6>>^ Este, andando entre os leões, veio a ser um leãozinho, e aprendeu a apanhar a presa, e devorou homens.

[[v26-19-7]]

^<<v26-19-7,7>>^ Aprendeu a fazer viúvas e a tornar desertas as cidades deles; ficaram estupefatos a terra e seus habitantes, ao ouvirem o seu rugido.

[[v26-19-8]]

^<<v26-19-8,8>>^ Então, se ajuntaram contra ele as gentes das províncias em roda, estenderam sobre ele a rede, e foi apanhado na cova que elas fizeram.

[[v26-19-9]]

^<<v26-19-9,9>>^ Com gancho, meteram-no em jaula, e o levaram ao rei da Babilônia, e fizeram-no entrar nos lugares fortes, para que se não ouvisse mais a sua voz nos montes de Israel.

[[v26-19-10]]

^<<v26-19-10,10>>^ Tua mãe, de sua natureza, era qual videira plantada junto às águas; plantada à borda, ela frutificou e se encheu de ramos, por causa das muitas águas.

[[v26-19-11]]

^<<v26-19-11,11>>^ Tinha galhos fortes para cetros de dominadores; elevou-se a sua estatura entre os espessos ramos, e foi vista na sua altura com a multidão deles.

[[v26-19-12]]

^<<v26-19-12,12>>^ Mas foi arrancada com furor e lançada por terra, e o vento oriental secou-lhe o fruto; quebraram-se e secaram os seus fortes galhos, e o fogo os consumiu.

[[v26-19-13]]

^<<v26-19-13,13>>^ Agora, está plantada no deserto, numa terra seca e sedenta.

[[v26-19-14]]

^<<v26-19-14,14>>^ Dos galhos dos seus ramos saiu fogo que consumiu o seu fruto, de maneira que já não há nela galho forte que sirva de cetro para dominar. Esta é uma lamentação e ficará servindo de lamentação.

'''

xref:026-ezequiel/026-ezequiel-018.adoc#v26-18-0[&#60; Capítulo Anterior] | <<v26-19-0,Topo>> | xref:026-ezequiel/026-ezequiel-020.adoc#v26-20-0[Próximo Capítulo &#62;]