include::./index.adoc[]

[[v26-23-0]]
=== Ezequiel, 23
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-23-1]]

^<<v26-23-1,1>>^ Veio a mim a palavra do SENHOR, dizendo:

[[v26-23-2]]

^<<v26-23-2,2>>^ Filho do homem, houve duas mulheres, filhas de uma só mãe.

[[v26-23-3]]

^<<v26-23-3,3>>^ Estas se prostituíram no Egito; prostituíram-se na sua mocidade; ali foram apertados os seus peitos e apalpados os seios da sua virgindade.

[[v26-23-4]]

^<<v26-23-4,4>>^ Os seus nomes eram: Oolá, a mais velha, e Oolibá, sua irmã; e foram minhas e tiveram filhos e filhas; e, quanto ao seu nome, Samaria é Oolá, e Jerusalém é Oolibá.

[[v26-23-5]]

^<<v26-23-5,5>>^ Prostituiu-se Oolá, quando era minha; inflamou-se pelos seus amantes, pelos assírios, seus vizinhos,

[[v26-23-6]]

^<<v26-23-6,6>>^ que se vestiam de azul, governadores e sátrapas, todos jovens de cobiçar, cavaleiros montados a cavalo.

[[v26-23-7]]

^<<v26-23-7,7>>^ Assim, cometeu ela as suas devassidões com eles, que eram todos a fina flor dos filhos da Assíria, e com todos aqueles pelos quais se inflamava; com todos os seus ídolos se contaminou.

[[v26-23-8]]

^<<v26-23-8,8>>^ As suas impudicícias, que trouxe do Egito, não as deixou; porque com ela se deitaram na sua mocidade, e eles apalparam os seios da sua virgindade e derramaram sobre ela a sua impudicícia.

[[v26-23-9]]

^<<v26-23-9,9>>^ Por isso, a entreguei nas mãos dos seus amantes, nas mãos dos filhos da Assíria, pelos quais se inflamara.

[[v26-23-10]]

^<<v26-23-10,10>>^ Estes descobriram as vergonhas dela, levaram seus filhos e suas filhas; porém a ela mataram à espada; e ela se tornou falada entre as mulheres, e sobre ela executaram juízos.

[[v26-23-11]]

^<<v26-23-11,11>>^ Vendo isto sua irmã Oolibá, corrompeu a sua paixão mais do que ela, e as suas devassidões foram maiores do que as de sua irmã.

[[v26-23-12]]

^<<v26-23-12,12>>^ Inflamou-se pelos filhos da Assíria, governadores e sátrapas, seus vizinhos, vestidos com primor, cavaleiros montados a cavalo, todos jovens de cobiçar.

[[v26-23-13]]

^<<v26-23-13,13>>^ Vi que se tinha contaminado; o caminho de ambas era o mesmo.

[[v26-23-14]]

^<<v26-23-14,14>>^ Aumentou as suas impudicícias, porque viu homens pintados na parede, imagens dos caldeus, pintados de vermelho:

[[v26-23-15]]

^<<v26-23-15,15>>^ de lombos cingidos e turbantes pendentes da cabeça, todos com aparência de oficiais, semelhantes aos filhos da Babilônia, na Caldeia, em terra do seu nascimento.

[[v26-23-16]]

^<<v26-23-16,16>>^ Vendo-os, inflamou-se por eles e lhes mandou mensageiros à Caldeia.

[[v26-23-17]]

^<<v26-23-17,17>>^ Então, vieram ter com ela os filhos da Babilônia, para o leito dos amores, e a contaminaram com as suas impudicícias; ela, após contaminar-se com eles, enojada, os deixou.

[[v26-23-18]]

^<<v26-23-18,18>>^ Assim, tendo ela posto a descoberto as suas devassidões e sua nudez, a minha alma se alienou dela, como já se dera com respeito à sua irmã.

[[v26-23-19]]

^<<v26-23-19,19>>^ Ela, todavia, multiplicou as suas impudicícias, lembrando-se dos dias da sua mocidade, em que se prostituíra na terra do Egito.

[[v26-23-20]]

^<<v26-23-20,20>>^ Inflamou-se pelos seus amantes, cujos membros eram como o de jumento e cujo fluxo é como o fluxo de cavalos.

[[v26-23-21]]

^<<v26-23-21,21>>^ Assim, trouxeste à memória a luxúria da tua mocidade, quando os do Egito apalpavam os teus seios, os peitos da tua mocidade.

[[v26-23-22]]

^<<v26-23-22,22>>^ Por isso, ó Oolibá, assim diz o SENHOR Deus: Eis que eu suscitarei contra ti os teus amantes, os quais, enojada, tu os deixaras, e os trarei contra ti de todos os lados:

[[v26-23-23]]

^<<v26-23-23,23>>^ os filhos da Babilônia e todos os caldeus de Pecode, de Soa, de Coa e todos os filhos da Assíria com eles, jovens de cobiçar, governadores e sátrapas, príncipes e homens de renome, todos montados a cavalo.

[[v26-23-24]]

^<<v26-23-24,24>>^ Virão contra ti do Norte, com carros e carretas e com multidão de povos; pôr-se-ão contra ti em redor, com paveses, e escudos, e capacetes; e porei diante deles o juízo, e julgar-te-ão segundo os seus direitos.

[[v26-23-25]]

^<<v26-23-25,25>>^ Porei contra ti o meu zelo, e eles te tratarão com furor; cortar-te-ão o nariz e as orelhas, e o que restar cairá à espada; levarão teus filhos e tuas filhas, e quem ainda te restar será consumido pelo fogo.

[[v26-23-26]]

^<<v26-23-26,26>>^ Despojar-te-ão dos teus vestidos e tomarão as tuas joias de adorno.

[[v26-23-27]]

^<<v26-23-27,27>>^ Assim, farei cessar em ti a tua luxúria e a tua prostituição, provenientes da terra do Egito; não levantarás os olhos para eles e já não te lembrarás do Egito.

[[v26-23-28]]

^<<v26-23-28,28>>^ Porque assim diz o SENHOR Deus: Eis que eu te entregarei nas mãos daqueles a quem aborreces, nas mãos daqueles que, enojada, tu deixaste.

[[v26-23-29]]

^<<v26-23-29,29>>^ Eles te tratarão com ódio, e levarão todo o fruto do teu trabalho, e te deixarão nua e despida; descobrir-se-á a vergonha da tua prostituição, a tua luxúria e as tuas devassidões.

[[v26-23-30]]

^<<v26-23-30,30>>^ Estas coisas se te farão, porque te prostituíste com os gentios e te contaminaste com os seus ídolos.

[[v26-23-31]]

^<<v26-23-31,31>>^ Andaste no caminho de tua irmã; por isso, entregarei o seu copo na tua mão.

[[v26-23-32]]

^<<v26-23-32,32>>^ Assim diz o SENHOR Deus: Beberás o copo de tua irmã, fundo e largo; servirás de riso e escárnio; pois nele cabe muito.

[[v26-23-33]]

^<<v26-23-33,33>>^ Encher-te-ás de embriaguez e de dor; o copo de tua irmã Samaria é copo de espanto e de desolação.

[[v26-23-34]]

^<<v26-23-34,34>>^ Tu o beberás, e esgotá-lo-ás, e lhe roerás os cacos, e te rasgarás os peitos, pois eu o falei, diz o SENHOR Deus.

[[v26-23-35]]

^<<v26-23-35,35>>^ Portanto, assim diz o SENHOR Deus: Como te esqueceste de mim e me viraste as costas, também carregarás com a tua luxúria e as tuas devassidões.

[[v26-23-36]]

^<<v26-23-36,36>>^ Disse-me ainda o SENHOR: Filho do homem, julgarás tu a Oolá e a Oolibá? Declara-lhes, pois, as suas abominações.

[[v26-23-37]]

^<<v26-23-37,37>>^ Porque adulteraram, e nas suas mãos há culpa de sangue; com seus ídolos adulteraram, e até os seus filhos, que me geraram, ofereceram a eles para serem consumidos pelo fogo.

[[v26-23-38]]

^<<v26-23-38,38>>^ Ainda isto me fizeram: no mesmo dia contaminaram o meu santuário e profanaram os meus sábados.

[[v26-23-39]]

^<<v26-23-39,39>>^ Pois, havendo sacrificado seus filhos aos ídolos, vieram, no mesmo dia, ao meu santuário para o profanarem; e assim o fizeram no meio da minha casa.

[[v26-23-40]]

^<<v26-23-40,40>>^ E mais ainda: mandaram vir uns homens de longe; fora-lhes enviado um mensageiro, e eis que vieram; por amor deles, te banhaste, coloriste os olhos e te ornaste de enfeites;

[[v26-23-41]]

^<<v26-23-41,41>>^ e te assentaste num suntuoso leito, diante do qual se achava mesa preparada, sobre que puseste o meu incenso e o meu óleo.

[[v26-23-42]]

^<<v26-23-42,42>>^ Com ela se ouvia a voz de muita gente que folgava; com homens de classe baixa foram trazidos do deserto uns bêbados, que puseram braceletes nas mãos delas e, na cabeça, coroas formosas.

[[v26-23-43]]

^<<v26-23-43,43>>^ Então, disse eu da envelhecida em adultérios: continuará ela em suas prostituições?

[[v26-23-44]]

^<<v26-23-44,44>>^ E passaram a estar com ela, como quem frequenta a uma prostituta; assim, passaram a frequentar a Oolá e a Oolibá, mulheres depravadas,

[[v26-23-45]]

^<<v26-23-45,45>>^ de maneira que homens justos as julgarão como se julgam as adúlteras e as sanguinárias; porque são adúlteras, e, nas suas mãos, há culpa de sangue.

[[v26-23-46]]

^<<v26-23-46,46>>^ Pois assim diz o SENHOR Deus: Farei subir contra elas grande multidão e as entregarei ao tumulto e ao saque.

[[v26-23-47]]

^<<v26-23-47,47>>^ A multidão as apedrejará e as golpeará com as suas espadas; a seus filhos e suas filhas matarão e as suas casas queimarão.

[[v26-23-48]]

^<<v26-23-48,48>>^ Assim, farei cessar a luxúria da terra, para que se escarmentem todas as mulheres e não façam segundo a luxúria delas.

[[v26-23-49]]

^<<v26-23-49,49>>^ O castigo da vossa luxúria recairá sobre vós, e levareis os pecados dos vossos ídolos; e sabereis que eu sou o SENHOR Deus.

'''

xref:026-ezequiel/026-ezequiel-022.adoc#v26-22-0[&#60; Capítulo Anterior] | <<v26-23-0,Topo>> | xref:026-ezequiel/026-ezequiel-024.adoc#v26-24-0[Próximo Capítulo &#62;]