include::./index.adoc[]

[[v26-40-0]]
=== Ezequiel, 40
// ara ?, ARA - Almeida Revista e Atualizada

[[v26-40-1]]

^<<v26-40-1,1>>^ No ano vigésimo quinto do nosso exílio, no princípio do ano, no décimo dia do mês, catorze anos após ter caído a cidade, nesse mesmo dia, veio sobre mim a mão do SENHOR, e ele me levou para lá.

[[v26-40-2]]

^<<v26-40-2,2>>^ Em visões, Deus me levou à terra de Israel e me pôs sobre um monte muito alto; sobre este havia um como edifício de cidade, para o lado sul.

[[v26-40-3]]

^<<v26-40-3,3>>^ Ele me levou para lá, e eis um homem cuja aparência era como a do bronze; estava de pé na porta e tinha na mão um cordel de linho e uma cana de medir.

[[v26-40-4]]

^<<v26-40-4,4>>^ Disse-me o homem: Filho do homem, vê com os próprios olhos, ouve com os próprios ouvidos; e põe no coração tudo quanto eu te mostrar, porque para isso foste trazido para aqui; anuncia, pois, à casa de Israel tudo quanto estás vendo.

[[v26-40-5]]

^<<v26-40-5,5>>^ Vi um muro exterior que rodeava toda a casa e, na mão do homem, uma cana de medir, de seis côvados, cada um dos quais media um côvado e quatro dedos. Ele mediu a largura do edifício, uma cana; e a altura, uma cana.

[[v26-40-6]]

^<<v26-40-6,6>>^ Então, veio à porta que olhava para o oriente e subiu pelos seus degraus; mediu o limiar da porta: uma cana de largura, e o outro limiar: uma cana de largura.

[[v26-40-7]]

^<<v26-40-7,7>>^ Cada câmara tinha uma cana de comprido e uma cana de largura; o espaço entre uma e outra câmara era de cinco côvados; o limiar da porta, junto ao vestíbulo da porta interior, tinha uma cana.

[[v26-40-8]]

^<<v26-40-8,8>>^ Também mediu o vestíbulo da porta interior: uma cana.

[[v26-40-9]]

^<<v26-40-9,9>>^ Então, mediu o vestíbulo da porta, que tinha oito côvados; e os seus pilares: dois côvados; o vestíbulo olha do interior da casa para a porta.

[[v26-40-10]]

^<<v26-40-10,10>>^ A porta para o lado oriental possuía três câmaras de cada lado, cuja medida era a mesma para cada uma; também os pilares deste lado e do outro mediam o mesmo.

[[v26-40-11]]

^<<v26-40-11,11>>^ Mediu mais a largura da entrada da porta, que era de dez côvados; a profundidade da entrada: treze côvados.

[[v26-40-12]]

^<<v26-40-12,12>>^ O espaço em frente das câmaras era de um côvado, e de um côvado, o espaço do outro lado; cada câmara tinha seis côvados em quadrado.

[[v26-40-13]]

^<<v26-40-13,13>>^ Então, mediu a porta desde a extremidade do teto de uma câmara até à da outra: vinte e cinco côvados de largura; e uma porta defronte da outra.

[[v26-40-14]]

^<<v26-40-14,14>>^ Mediu a distância até aos pilares, sessenta côvados, e o átrio se estendia até aos pilares em redor da porta.

[[v26-40-15]]

^<<v26-40-15,15>>^ Desde a dianteira da porta da entrada até à dianteira do vestíbulo da porta interior, havia cinquenta côvados.

[[v26-40-16]]

^<<v26-40-16,16>>^ Havia também janelas com fasquias fixas superpostas para as câmaras e para os pilares, e da mesma sorte, para os vestíbulos; as janelas estavam à roda pela parte de dentro, e nos pilares havia palmeiras esculpidas.

[[v26-40-17]]

^<<v26-40-17,17>>^ Ele me levou ao átrio exterior; e eis que havia nele câmaras e um pavimento feito no átrio em redor; defronte deste pavimento havia trinta câmaras.

[[v26-40-18]]

^<<v26-40-18,18>>^ O pavimento ao lado das portas era a par do comprimento das portas; era o pavimento inferior.

[[v26-40-19]]

^<<v26-40-19,19>>^ Então, mediu a largura desde a dianteira da porta inferior até à dianteira do átrio interior, por fora: cem côvados do lado leste e do norte.

[[v26-40-20]]

^<<v26-40-20,20>>^ Quanto à porta que olhava para o norte, no átrio exterior, ele mediu o seu comprimento e a sua largura.

[[v26-40-21]]

^<<v26-40-21,21>>^ As suas câmaras, três de um lado e três do outro, e os seus pilares, e os seus vestíbulos eram da medida do primeiro vestíbulo; de cinquenta côvados era o seu comprimento, e a largura, de vinte e cinco côvados.

[[v26-40-22]]

^<<v26-40-22,22>>^ As suas janelas, e os seus vestíbulos, e as suas palmeiras eram da medida da porta que olhava para o oriente; subia-se para ela por sete degraus, e o seu vestíbulo estava diante dela.

[[v26-40-23]]

^<<v26-40-23,23>>^ Essa porta do átrio interior estava defronte tanto da porta do norte como da do oriente; e mediu, de porta a porta, cem côvados.

[[v26-40-24]]

^<<v26-40-24,24>>^ Então, ele me levou para o lado sul, e eis que havia ali uma porta que olhava para o sul; e mediu os seus pilares e os seus vestíbulos, que tinham as mesmas dimensões.

[[v26-40-25]]

^<<v26-40-25,25>>^ Havia também janelas em redor dos seus vestíbulos, como as outras janelas; cinquenta côvados, o comprimento do vestíbulo, e a largura, vinte e cinco côvados.

[[v26-40-26]]

^<<v26-40-26,26>>^ De sete degraus eram as suas subidas, e os seus vestíbulos estavam diante deles; e tinha palmeiras esculpidas, uma de um lado e outra do outro, nos seus pilares.

[[v26-40-27]]

^<<v26-40-27,27>>^ Também havia uma porta no átrio interior para o sul; e mediu, de porta a porta, para o sul, cem côvados.

[[v26-40-28]]

^<<v26-40-28,28>>^ Então, me levou ao átrio interior pela porta do sul; e mediu a porta do sul, que tinha as mesmas dimensões.

[[v26-40-29]]

^<<v26-40-29,29>>^ As suas câmaras, e os seus pilares, e os seus vestíbulos eram segundo estas medidas; e tinham também janelas ao redor dos seus vestíbulos; o comprimento do vestíbulo era de cinquenta côvados, e a largura, de vinte e cinco côvados.

[[v26-40-30]]

^<<v26-40-30,30>>^ Havia vestíbulos em redor; o comprimento era de vinte e cinco côvados, e a largura, de cinco côvados.

[[v26-40-31]]

^<<v26-40-31,31>>^ Os seus vestíbulos olhavam para o átrio exterior, e havia palmeiras nos seus pilares; e de oito degraus eram as suas subidas.

[[v26-40-32]]

^<<v26-40-32,32>>^ Depois, me levou ao átrio interior, para o oriente, e mediu a porta, que tinha as mesmas dimensões.

[[v26-40-33]]

^<<v26-40-33,33>>^ Também as suas câmaras, e os seus pilares, e os seus vestíbulos, segundo estas medidas; havia também janelas em redor dos seus vestíbulos; o comprimento do vestíbulo era de cinquenta côvados, e a largura, de vinte e cinco côvados.

[[v26-40-34]]

^<<v26-40-34,34>>^ Os seus vestíbulos olhavam para o átrio exterior; também havia palmeiras nos seus pilares, de um e de outro lado; e eram as suas subidas de oito degraus.

[[v26-40-35]]

^<<v26-40-35,35>>^ Então, me levou à porta do norte e a mediu; tinha as mesmas dimensões.

[[v26-40-36]]

^<<v26-40-36,36>>^ Também as suas câmaras, e os seus pilares, e os seus vestíbulos, e as suas janelas em redor; o comprimento do vestíbulo era de cinquenta côvados, e a largura, de vinte e cinco côvados.

[[v26-40-37]]

^<<v26-40-37,37>>^ Os seus pilares olhavam para o átrio exterior; também havia palmeiras nos seus pilares, de um e de outro lado; e eram as suas subidas de oito degraus.

[[v26-40-38]]

^<<v26-40-38,38>>^ A sua câmara e a sua entrada estavam junto aos pilares dos vestíbulos onde lavavam o holocausto.

[[v26-40-39]]

^<<v26-40-39,39>>^ No vestíbulo da porta havia duas mesas de um lado e duas do outro, para nelas se degolar o holocausto e a oferta pelo pecado e pela culpa.

[[v26-40-40]]

^<<v26-40-40,40>>^ Também do lado de fora da subida para a entrada da porta do norte havia duas mesas; e, no outro lado do vestíbulo da porta, havia duas mesas.

[[v26-40-41]]

^<<v26-40-41,41>>^ Quatro mesas de um lado, e quatro do outro lado; junto à porta, oito mesas, sobre as quais imolavam.

[[v26-40-42]]

^<<v26-40-42,42>>^ As quatro mesas para o holocausto eram de pedras lavradas; o comprimento era de um côvado e meio, a largura, de um côvado e meio, e a altura, de um côvado; sobre elas se punham os instrumentos com que imolavam o holocausto e os sacrifícios.

[[v26-40-43]]

^<<v26-40-43,43>>^ Os ganchos, de quatro dedos de comprimento, estavam fixados por dentro ao redor, e sobre as mesas estava a carne da oblação.

[[v26-40-44]]

^<<v26-40-44,44>>^ Fora da porta interior estavam duas câmaras dos cantores, no átrio de dentro; uma, do lado da porta do norte, e olhava para o sul; outra, do lado da porta do sul, e olhava para o norte.

[[v26-40-45]]

^<<v26-40-45,45>>^ Ele me disse: Esta câmara que olha para o sul é para os sacerdotes que têm a guarda do templo.

[[v26-40-46]]

^<<v26-40-46,46>>^ Mas a câmara que olha para o norte é para os sacerdotes que têm a guarda do altar; são estes os filhos de Zadoque, os quais, dentre os filhos de Levi, se chegam ao SENHOR para o servirem.

[[v26-40-47]]

^<<v26-40-47,47>>^ Ele mediu o átrio: comprimento, cem côvados, largura, cem côvados, um quadrado; o altar estava diante do templo.

[[v26-40-48]]

^<<v26-40-48,48>>^ Então, me levou ao vestíbulo do templo e mediu cada pilar do vestíbulo, cinco côvados de um lado e cinco do outro; e a largura da porta, três côvados de um lado e três do outro.

[[v26-40-49]]

^<<v26-40-49,49>>^ O comprimento do vestíbulo era de vinte côvados, e a largura, de onze; e era por degraus que se subia. Havia colunas junto aos pilares, uma de um lado e outra do outro.

'''

xref:026-ezequiel/026-ezequiel-039.adoc#v26-39-0[&#60; Capítulo Anterior] | <<v26-40-0,Topo>> | xref:026-ezequiel/026-ezequiel-041.adoc#v26-41-0[Próximo Capítulo &#62;]