include::./index.adoc[]

[[v61-1-0]]
=== 2 Pedro, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v61-1-1]]

^<<v61-1-1,1>>^ Simão Pedro, servo e apóstolo de Jesus Cristo, aos que conosco obtiveram fé igualmente preciosa na justiça do nosso Deus e Salvador Jesus Cristo,

[[v61-1-2]]

^<<v61-1-2,2>>^ graça e paz vos sejam multiplicadas, no pleno conhecimento de Deus e de Jesus, nosso Senhor.

[[v61-1-3]]

^<<v61-1-3,3>>^ Visto como, pelo seu divino poder, nos têm sido doadas todas as coisas que conduzem à vida e à piedade, pelo conhecimento completo daquele que nos chamou para a sua própria glória e virtude,

[[v61-1-4]]

^<<v61-1-4,4>>^ pelas quais nos têm sido doadas as suas preciosas e mui grandes promessas, para que por elas vos torneis coparticipantes da natureza divina, livrando-vos da corrupção das paixões que há no mundo,

[[v61-1-5]]

^<<v61-1-5,5>>^ por isso mesmo, vós, reunindo toda a vossa diligência, associai com a vossa fé a virtude; com a virtude, o conhecimento;

[[v61-1-6]]

^<<v61-1-6,6>>^ com o conhecimento, o domínio próprio; com o domínio próprio, a perseverança; com a perseverança, a piedade;

[[v61-1-7]]

^<<v61-1-7,7>>^ com a piedade, a fraternidade; com a fraternidade, o amor.

[[v61-1-8]]

^<<v61-1-8,8>>^ Porque estas coisas, existindo em vós e em vós aumentando, fazem com que não sejais nem inativos, nem infrutuosos no pleno conhecimento de nosso Senhor Jesus Cristo.

[[v61-1-9]]

^<<v61-1-9,9>>^ Pois aquele a quem estas coisas não estão presentes é cego, vendo só o que está perto, esquecido da purificação dos seus pecados de outrora.

[[v61-1-10]]

^<<v61-1-10,10>>^ Por isso, irmãos, procurai, com diligência cada vez maior, confirmar a vossa vocação e eleição; porquanto, procedendo assim, não tropeçareis em tempo algum.

[[v61-1-11]]

^<<v61-1-11,11>>^ Pois desta maneira é que vos será amplamente suprida a entrada no reino eterno de nosso Senhor e Salvador Jesus Cristo.

[[v61-1-12]]

^<<v61-1-12,12>>^ Por esta razão, sempre estarei pronto para trazer-vos lembrados acerca destas coisas, embora estejais certos da verdade já presente convosco e nela confirmados.

[[v61-1-13]]

^<<v61-1-13,13>>^ Também considero justo, enquanto estou neste tabernáculo, despertar-vos com essas lembranças,

[[v61-1-14]]

^<<v61-1-14,14>>^ certo de que estou prestes a deixar o meu tabernáculo, como efetivamente nosso Senhor Jesus Cristo me revelou.

[[v61-1-15]]

^<<v61-1-15,15>>^ Mas, de minha parte, esforçar-me-ei, diligentemente, por fazer que, a todo tempo, mesmo depois da minha partida, conserveis lembrança de tudo.

[[v61-1-16]]

^<<v61-1-16,16>>^ Porque não vos demos a conhecer o poder e a vinda de nosso Senhor Jesus Cristo seguindo fábulas engenhosamente inventadas, mas nós mesmos fomos testemunhas oculares da sua majestade,

[[v61-1-17]]

^<<v61-1-17,17>>^ pois ele recebeu, da parte de Deus Pai, honra e glória, quando pela Glória Excelsa lhe foi enviada a seguinte voz: Este é o meu Filho amado, em quem me comprazo.

[[v61-1-18]]

^<<v61-1-18,18>>^ Ora, esta voz, vinda do céu, nós a ouvimos quando estávamos com ele no monte santo.

[[v61-1-19]]

^<<v61-1-19,19>>^ Temos, assim, tanto mais confirmada a palavra profética, e fazeis bem em atendê-la, como a uma candeia que brilha em lugar tenebroso, até que o dia clareie e a estrela da alva nasça em vosso coração,

[[v61-1-20]]

^<<v61-1-20,20>>^ sabendo, primeiramente, isto: que nenhuma profecia da Escritura provém de particular elucidação;

[[v61-1-21]]

^<<v61-1-21,21>>^ porque nunca jamais qualquer profecia foi dada por vontade humana; entretanto, homens [santos] falaram da parte de Deus, movidos pelo Espírito Santo.

'''

xref:060-1-pedro/060-1-pedro-005.adoc#v60-5-0[&#60; Capítulo Anterior] | <<v61-1-0,Topo>> | xref:061-2-pedro/061-2-pedro-002.adoc#v61-2-0[Próximo Capítulo &#62;]