include::./index.adoc[]

[[v61-2-0]]
=== 2 Pedro, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v61-2-1]]

^<<v61-2-1,1>>^ Assim como, no meio do povo, surgiram falsos profetas, assim também haverá entre vós falsos mestres, os quais introduzirão, dissimuladamente, heresias destruidoras, até ao ponto de renegarem o Soberano Senhor que os resgatou, trazendo sobre si mesmos repentina destruição.

[[v61-2-2]]

^<<v61-2-2,2>>^ E muitos seguirão as suas práticas libertinas, e, por causa deles, será infamado o caminho da verdade;

[[v61-2-3]]

^<<v61-2-3,3>>^ também, movidos por avareza, farão comércio de vós, com palavras fictícias; para eles o juízo lavrado há longo tempo não tarda, e a sua destruição não dorme.

[[v61-2-4]]

^<<v61-2-4,4>>^ Ora, se Deus não poupou anjos quando pecaram, antes, precipitando-os no inferno, os entregou a abismos de trevas, reservando-os para juízo;

[[v61-2-5]]

^<<v61-2-5,5>>^ e não poupou o mundo antigo, mas preservou a Noé, pregador da justiça, e mais sete pessoas, quando fez vir o dilúvio sobre o mundo de ímpios;

[[v61-2-6]]

^<<v61-2-6,6>>^ e, reduzindo a cinzas as cidades de Sodoma e Gomorra, ordenou-as à ruína completa, tendo-as posto como exemplo a quantos venham a viver impiamente;

[[v61-2-7]]

^<<v61-2-7,7>>^ e livrou o justo Ló, afligido pelo procedimento libertino daqueles insubordinados

[[v61-2-8]]

^<<v61-2-8,8>>^ (porque este justo, pelo que via e ouvia quando habitava entre eles, atormentava a sua alma justa, cada dia, por causa das obras iníquas daqueles),

[[v61-2-9]]

^<<v61-2-9,9>>^ é porque o Senhor sabe livrar da provação os piedosos e reservar, sob castigo, os injustos para o Dia de Juízo,

[[v61-2-10]]

^<<v61-2-10,10>>^ especialmente aqueles que, seguindo a carne, andam em imundas paixões e menosprezam qualquer governo. Atrevidos, arrogantes, não temem difamar autoridades superiores,

[[v61-2-11]]

^<<v61-2-11,11>>^ ao passo que anjos, embora maiores em força e poder, não proferem contra elas juízo infamante na presença do Senhor.

[[v61-2-12]]

^<<v61-2-12,12>>^ Esses, todavia, como brutos irracionais, naturalmente feitos para presa e destruição, falando mal daquilo em que são ignorantes, na sua destruição também hão de ser destruídos,

[[v61-2-13]]

^<<v61-2-13,13>>^ recebendo injustiça por salário da injustiça que praticam. Considerando como prazer a sua luxúria carnal em pleno dia, quais nódoas e deformidades, eles se regalam nas suas próprias mistificações, enquanto banqueteiam junto convosco;

[[v61-2-14]]

^<<v61-2-14,14>>^ tendo os olhos cheios de adultério e insaciáveis no pecado, engodando almas inconstantes, tendo coração exercitado na avareza, filhos malditos;

[[v61-2-15]]

^<<v61-2-15,15>>^ abandonando o reto caminho, se extraviaram, seguindo pelo caminho de Balaão, filho de Beor, que amou o prêmio da injustiça

[[v61-2-16]]

^<<v61-2-16,16>>^ (recebeu, porém, castigo da sua transgressão, a saber, um mudo animal de carga, falando com voz humana, refreou a insensatez do profeta).

[[v61-2-17]]

^<<v61-2-17,17>>^ Esses tais são como fonte sem água, como névoas impelidas por temporal. Para eles está reservada a negridão das trevas;

[[v61-2-18]]

^<<v61-2-18,18>>^ porquanto, proferindo palavras jactanciosas de vaidade, engodam com paixões carnais, por suas libertinagens, aqueles que estavam prestes a fugir dos que andam no erro,

[[v61-2-19]]

^<<v61-2-19,19>>^ prometendo-lhes liberdade, quando eles mesmos são escravos da corrupção, pois aquele que é vencido fica escravo do vencedor.

[[v61-2-20]]

^<<v61-2-20,20>>^ Portanto, se, depois de terem escapado das contaminações do mundo mediante o conhecimento do Senhor e Salvador Jesus Cristo, se deixam enredar de novo e são vencidos, tornou-se o seu último estado pior que o primeiro.

[[v61-2-21]]

^<<v61-2-21,21>>^ Pois melhor lhes fora nunca tivessem conhecido o caminho da justiça do que, após conhecê-lo, volverem para trás, apartando-se do santo mandamento que lhes fora dado.

[[v61-2-22]]

^<<v61-2-22,22>>^ Com eles aconteceu o que diz certo adágio verdadeiro: O cão voltou ao seu próprio vômito; e: A porca lavada voltou a revolver-se no lamaçal.

'''

xref:061-2-pedro/061-2-pedro-001.adoc#v61-1-0[&#60; Capítulo Anterior] | <<v61-2-0,Topo>> | xref:061-2-pedro/061-2-pedro-003.adoc#v61-3-0[Próximo Capítulo &#62;]