include::./index.adoc[]

[[v38-4-0]]
=== Zacarias, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v38-4-1]]

^<<v38-4-1,1>>^ Tornou o anjo que falava comigo e me despertou, como a um homem que é despertado do seu sono,

[[v38-4-2]]

^<<v38-4-2,2>>^ e me perguntou: Que vês? Respondi: olho, e eis um candelabro todo de ouro e um vaso de azeite em cima com as suas sete lâmpadas e sete tubos, um para cada uma das lâmpadas que estão em cima do candelabro.

[[v38-4-3]]

^<<v38-4-3,3>>^ Junto a este, duas oliveiras, uma à direita do vaso de azeite, e a outra à sua esquerda.

[[v38-4-4]]

^<<v38-4-4,4>>^ Então, perguntei ao anjo que falava comigo: meu senhor, que é isto?

[[v38-4-5]]

^<<v38-4-5,5>>^ Respondeu-me o anjo que falava comigo: Não sabes tu que é isto? Respondi: não, meu senhor.

[[v38-4-6]]

^<<v38-4-6,6>>^ Prosseguiu ele e me disse: Esta é a palavra do SENHOR a Zorobabel: Não por força nem por poder, mas pelo meu Espírito, diz o SENHOR dos Exércitos.

[[v38-4-7]]

^<<v38-4-7,7>>^ Quem és tu, ó grande monte? Diante de Zorobabel serás uma campina; porque ele colocará a pedra de remate, em meio a aclamações: Haja graça e graça para ela!

[[v38-4-8]]

^<<v38-4-8,8>>^ Novamente, me veio a palavra do SENHOR, dizendo:

[[v38-4-9]]

^<<v38-4-9,9>>^ As mãos de Zorobabel lançaram os fundamentos desta casa, elas mesmas a acabarão, para que saibais que o SENHOR dos Exércitos é quem me enviou a vós outros.

[[v38-4-10]]

^<<v38-4-10,10>>^ Pois quem despreza o dia dos humildes começos, esse alegrar-se-á vendo o prumo na mão de Zorobabel. Aqueles sete olhos são os olhos do SENHOR, que percorrem toda a terra.

[[v38-4-11]]

^<<v38-4-11,11>>^ Prossegui e lhe perguntei: que são as duas oliveiras à direita e à esquerda do candelabro?

[[v38-4-12]]

^<<v38-4-12,12>>^ Tornando a falar-lhe, perguntei: que são aqueles dois raminhos de oliveira que estão junto aos dois tubos de ouro, que vertem de si azeite dourado?

[[v38-4-13]]

^<<v38-4-13,13>>^ Ele me respondeu: Não sabes que é isto? Eu disse: não, meu senhor.

[[v38-4-14]]

^<<v38-4-14,14>>^ Então, ele disse: São os dois ungidos, que assistem junto ao Senhor de toda a terra.

'''

xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[&#60; Capítulo Anterior] | <<v38-4-0,Topo>> | xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[Próximo Capítulo &#62;]