include::./index.adoc[]

[[v38-11-0]]
=== Zacarias, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v38-11-1]]

^<<v38-11-1,1>>^ Abre, ó Líbano, as tuas portas, para que o fogo consuma os teus cedros.

[[v38-11-2]]

^<<v38-11-2,2>>^ Geme, ó cipreste, porque os cedros caíram, porque as mais excelentes árvores são destruídas; gemei, ó carvalhos de Basã, porque o denso bosque foi derribado.

[[v38-11-3]]

^<<v38-11-3,3>>^ Eis o uivo dos pastores, porque a sua glória é destruída! Eis o bramido dos filhos de leões, porque foi destruída a soberba do Jordão!

[[v38-11-4]]

^<<v38-11-4,4>>^ Assim diz o SENHOR, meu Deus: Apascenta as ovelhas destinadas para a matança.

[[v38-11-5]]

^<<v38-11-5,5>>^ Aqueles que as compram matam-nas e não são punidos; os que as vendem dizem: Louvado seja o SENHOR, porque me tornei rico; e os seus pastores não se compadecem delas.

[[v38-11-6]]

^<<v38-11-6,6>>^ Certamente, já não terei piedade dos moradores desta terra, diz o SENHOR; eis, porém, que entregarei os homens, cada um nas mãos do seu próximo e nas mãos do seu rei; eles ferirão a terra, e eu não os livrarei das mãos deles.

[[v38-11-7]]

^<<v38-11-7,7>>^ Apascentai, pois, as ovelhas destinadas para a matança, as pobres ovelhas do rebanho. Tomei para mim duas varas: a uma chamei Graça, e à outra, União; e apascentei as ovelhas.

[[v38-11-8]]

^<<v38-11-8,8>>^ Dei cabo dos três pastores num mês. Então, perdi a paciência com as ovelhas, e também elas estavam cansadas de mim.

[[v38-11-9]]

^<<v38-11-9,9>>^ Então, disse eu: não vos apascentarei; o que quer morrer, morra, o que quer ser destruído, seja, e os que restarem, coma cada um a carne do seu próximo.

[[v38-11-10]]

^<<v38-11-10,10>>^ Tomei a vara chamada Graça e a quebrei, para anular a minha aliança, que eu fizera com todos os povos.

[[v38-11-11]]

^<<v38-11-11,11>>^ Foi, pois, anulada naquele dia; e as pobres do rebanho, que fizeram caso de mim, reconheceram que isto era palavra do SENHOR.

[[v38-11-12]]

^<<v38-11-12,12>>^ Eu lhes disse: se vos parece bem, dai-me o meu salário; e, se não, deixai-o. Pesaram, pois, por meu salário trinta moedas de prata.

[[v38-11-13]]

^<<v38-11-13,13>>^ Então, o SENHOR me disse: Arroja isso ao oleiro, esse magnífico preço em que fui avaliado por eles. Tomei as trinta moedas de prata e as arrojei ao oleiro, na Casa do SENHOR.

[[v38-11-14]]

^<<v38-11-14,14>>^ Então, quebrei a segunda vara, chamada União, para romper a irmandade entre Judá e Israel.

[[v38-11-15]]

^<<v38-11-15,15>>^ O SENHOR me disse: Toma ainda os petrechos de um pastor insensato,

[[v38-11-16]]

^<<v38-11-16,16>>^ porque eis que suscitarei um pastor na terra, o qual não cuidará das que estão perecendo, não buscará a desgarrada, não curará a que foi ferida, nem apascentará a sã; mas comerá a carne das gordas e lhes arrancará até as unhas.

[[v38-11-17]]

^<<v38-11-17,17>>^ Ai do pastor inútil, que abandona o rebanho! A espada lhe cairá sobre o braço e sobre o olho direito; o braço, completamente, se lhe secará, e o olho direito, de todo, se escurecerá.

'''

xref:038-zacarias/038-zacarias-010.adoc#v38-10-0[&#60; Capítulo Anterior] | <<v38-11-0,Topo>> | xref:038-zacarias/038-zacarias-012.adoc#v38-12-0[Próximo Capítulo &#62;]