include::./index.adoc[]

[[v38-8-0]]
=== Zacarias, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v38-8-1]]

^<<v38-8-1,1>>^ Veio a mim a palavra do SENHOR dos Exércitos, dizendo:

[[v38-8-2]]

^<<v38-8-2,2>>^ Assim diz o SENHOR dos Exércitos: Tenho grandes zelos de Sião e com grande indignação tenho zelos dela.

[[v38-8-3]]

^<<v38-8-3,3>>^ Assim diz o SENHOR: Voltarei para Sião e habitarei no meio de Jerusalém; Jerusalém chamar-se-á a cidade fiel, e o monte do SENHOR dos Exércitos, monte santo.

[[v38-8-4]]

^<<v38-8-4,4>>^ Assim diz o SENHOR dos Exércitos: Ainda nas praças de Jerusalém sentar-se-ão velhos e velhas, levando cada um na mão o seu arrimo, por causa da sua muita idade.

[[v38-8-5]]

^<<v38-8-5,5>>^ As praças da cidade se encherão de meninos e meninas, que nelas brincarão.

[[v38-8-6]]

^<<v38-8-6,6>>^ Assim diz o SENHOR dos Exércitos: Se isto for maravilhoso aos olhos do restante deste povo naqueles dias, será também maravilhoso aos meus olhos? — diz o SENHOR dos Exércitos.

[[v38-8-7]]

^<<v38-8-7,7>>^ Assim diz o SENHOR dos Exércitos: Eis que salvarei o meu povo, tirando-o da terra do Oriente e da terra do Ocidente;

[[v38-8-8]]

^<<v38-8-8,8>>^ eu os trarei, e habitarão em Jerusalém; eles serão o meu povo, e eu serei o seu Deus, em verdade e em justiça.

[[v38-8-9]]

^<<v38-8-9,9>>^ Assim diz o SENHOR dos Exércitos: Sejam fortes as mãos de todos vós que nestes dias ouvis estas palavras da boca dos profetas, a saber, nos dias em que foram postos os fundamentos da Casa do SENHOR dos Exércitos, para que o templo fosse edificado.

[[v38-8-10]]

^<<v38-8-10,10>>^ Porque, antes daqueles dias, não havia salário para homens, nem os animais lhes davam ganho, não havia paz para o que entrava, nem para o que saía, por causa do inimigo, porque eu incitei todos os homens, cada um contra o seu próximo.

[[v38-8-11]]

^<<v38-8-11,11>>^ Mas, agora, não serei para com o restante deste povo como nos primeiros dias, diz o SENHOR dos Exércitos.

[[v38-8-12]]

^<<v38-8-12,12>>^ Porque haverá sementeira de paz; a vide dará o seu fruto, a terra, a sua novidade, e os céus, o seu orvalho; e farei que o resto deste povo herde tudo isto.

[[v38-8-13]]

^<<v38-8-13,13>>^ E há de acontecer, ó casa de Judá, ó casa de Israel, que, assim como fostes maldição entre as nações, assim vos salvarei, e sereis bênção; não temais, e sejam fortes as vossas mãos.

[[v38-8-14]]

^<<v38-8-14,14>>^ Porque assim diz o SENHOR dos Exércitos: Como pensei fazer-vos mal, quando vossos pais me provocaram à ira, diz o SENHOR dos Exércitos, e não me arrependi,

[[v38-8-15]]

^<<v38-8-15,15>>^ assim pensei de novo em fazer bem a Jerusalém e à casa de Judá nestes dias; não temais.

[[v38-8-16]]

^<<v38-8-16,16>>^ Eis as coisas que deveis fazer: Falai a verdade cada um com o seu próximo, executai juízo nas vossas portas, segundo a verdade, em favor da paz;

[[v38-8-17]]

^<<v38-8-17,17>>^ nenhum de vós pense mal no seu coração contra o seu próximo, nem ame o juramento falso, porque a todas estas coisas eu aborreço, diz o SENHOR.

[[v38-8-18]]

^<<v38-8-18,18>>^ A palavra do SENHOR dos Exércitos veio a mim, dizendo:

[[v38-8-19]]

^<<v38-8-19,19>>^ Assim diz o SENHOR dos Exércitos: O jejum do quarto mês, e o do quinto, e o do sétimo, e o do décimo serão para a casa de Judá regozijo, alegria e festividades solenes; amai, pois, a verdade e a paz.

[[v38-8-20]]

^<<v38-8-20,20>>^ Assim diz o SENHOR dos Exércitos: Ainda sucederá que virão povos e habitantes de muitas cidades;

[[v38-8-21]]

^<<v38-8-21,21>>^ e os habitantes de uma cidade irão à outra, dizendo: Vamos depressa suplicar o favor do SENHOR e buscar ao SENHOR dos Exércitos; eu também irei.

[[v38-8-22]]

^<<v38-8-22,22>>^ Virão muitos povos e poderosas nações buscar em Jerusalém ao SENHOR dos Exércitos e suplicar o favor do SENHOR.

[[v38-8-23]]

^<<v38-8-23,23>>^ Assim diz o SENHOR dos Exércitos: Naquele dia, sucederá que pegarão dez homens, de todas as línguas das nações, pegarão, sim, na orla da veste de um judeu e lhe dirão: Iremos convosco, porque temos ouvido que Deus está convosco.

'''

xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[&#60; Capítulo Anterior] | <<v38-8-0,Topo>> | xref:038-zacarias/038-zacarias-009.adoc#v38-9-0[Próximo Capítulo &#62;]