include::./index.adoc[]

[[v38-1-0]]
=== Zacarias, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v38-1-1]]

^<<v38-1-1,1>>^ No oitavo mês do segundo ano de Dario, veio a palavra do SENHOR ao profeta Zacarias, filho de Baraquias, filho de Ido, dizendo:

[[v38-1-2]]

^<<v38-1-2,2>>^ O SENHOR se irou em extremo contra vossos pais.

[[v38-1-3]]

^<<v38-1-3,3>>^ Portanto, dize-lhes: Assim diz o SENHOR dos Exércitos: Tornai-vos para mim, diz o SENHOR dos Exércitos, e eu me tornarei para vós outros, diz o SENHOR dos Exércitos.

[[v38-1-4]]

^<<v38-1-4,4>>^ Não sejais como vossos pais, a quem clamavam os primeiros profetas, dizendo: Assim diz o SENHOR dos Exércitos: Convertei-vos, agora, dos vossos maus caminhos e das vossas más obras; mas não ouviram, nem me atenderam, diz o SENHOR.

[[v38-1-5]]

^<<v38-1-5,5>>^ Vossos pais, onde estão eles? E os profetas, acaso, vivem para sempre?

[[v38-1-6]]

^<<v38-1-6,6>>^ Contudo, as minhas palavras e os meus estatutos, que eu prescrevi aos profetas, meus servos, não alcançaram a vossos pais? Sim, estes se arrependeram e disseram: Como o SENHOR dos Exércitos fez tenção de nos tratar, segundo os nossos caminhos e segundo as nossas obras, assim ele nos fez.

[[v38-1-7]]

^<<v38-1-7,7>>^ No vigésimo quarto dia do mês undécimo, que é o mês de sebate, no segundo ano de Dario, veio a palavra do SENHOR ao profeta Zacarias, filho de Baraquias, filho de Ido.

[[v38-1-8]]

^<<v38-1-8,8>>^ Tive de noite uma visão, e eis um homem montado num cavalo vermelho; estava parado entre as murteiras que havia num vale profundo; atrás dele se achavam cavalos vermelhos, baios e brancos.

[[v38-1-9]]

^<<v38-1-9,9>>^ Então, perguntei: meu senhor, quem são estes? Respondeu-me o anjo que falava comigo: Eu te mostrarei quem são eles.

[[v38-1-10]]

^<<v38-1-10,10>>^ Então, respondeu o homem que estava entre as murteiras e disse: São os que o SENHOR tem enviado para percorrerem a terra.

[[v38-1-11]]

^<<v38-1-11,11>>^ Eles responderam ao anjo do SENHOR, que estava entre as murteiras, e disseram: Nós já percorremos a terra, e eis que toda a terra está, agora, repousada e tranquila.

[[v38-1-12]]

^<<v38-1-12,12>>^ Então, o anjo do SENHOR respondeu: Ó SENHOR dos Exércitos, até quando não terás compaixão de Jerusalém e das cidades de Judá, contra as quais estás indignado faz já setenta anos?

[[v38-1-13]]

^<<v38-1-13,13>>^ Respondeu o SENHOR com palavras boas, palavras consoladoras, ao anjo que falava comigo.

[[v38-1-14]]

^<<v38-1-14,14>>^ E este me disse: Clama: Assim diz o SENHOR dos Exércitos: Com grande empenho, estou zelando por Jerusalém e por Sião.

[[v38-1-15]]

^<<v38-1-15,15>>^ E, com grande indignação, estou irado contra as nações que vivem confiantes; porque eu estava um pouco indignado, e elas agravaram o mal.

[[v38-1-16]]

^<<v38-1-16,16>>^ Portanto, assim diz o SENHOR: Voltei-me para Jerusalém com misericórdia; a minha casa nela será edificada, diz o SENHOR dos Exércitos, e o cordel será estendido sobre Jerusalém.

[[v38-1-17]]

^<<v38-1-17,17>>^ Clama outra vez, dizendo: Assim diz o SENHOR dos Exércitos: As minhas cidades ainda transbordarão de bens; o SENHOR ainda consolará a Sião e ainda escolherá a Jerusalém.

[[v38-1-18]]

^<<v38-1-18,18>>^ Levantei os olhos e vi, e eis quatro chifres.

[[v38-1-19]]

^<<v38-1-19,19>>^ Perguntei ao anjo que falava comigo: que é isto? Ele me respondeu: São os chifres que dispersaram a Judá, a Israel e a Jerusalém.

[[v38-1-20]]

^<<v38-1-20,20>>^ O SENHOR me mostrou quatro ferreiros.

[[v38-1-21]]

^<<v38-1-21,21>>^ Então, perguntei: que vêm fazer estes? Ele respondeu: Aqueles são os chifres que dispersaram a Judá, de maneira que ninguém pode levantar a cabeça; estes ferreiros, pois, vieram para os amedrontar, para derribar os chifres das nações que levantaram o seu poder contra a terra de Judá, para a espalhar.

'''

xref:037-ageu/037-ageu-002.adoc#v37-2-0[&#60; Capítulo Anterior] | <<v38-1-0,Topo>> | xref:038-zacarias/038-zacarias-002.adoc#v38-2-0[Próximo Capítulo &#62;]