include::./index.adoc[]

[[v38-5-0]]
=== Zacarias, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v38-5-1]]

^<<v38-5-1,1>>^ Tornei a levantar os olhos e vi, e eis um rolo voante.

[[v38-5-2]]

^<<v38-5-2,2>>^ Perguntou-me o anjo: Que vês? Eu respondi: vejo um rolo voante, que tem vinte côvados de comprimento e dez de largura.

[[v38-5-3]]

^<<v38-5-3,3>>^ Então, me disse: Esta é a maldição que sai pela face de toda a terra, porque qualquer que furtar será expulso segundo a maldição, e qualquer que jurar falsamente será expulso também segundo a mesma.

[[v38-5-4]]

^<<v38-5-4,4>>^ Fá-la-ei sair, diz o SENHOR dos Exércitos, e a farei entrar na casa do ladrão e na casa do que jurar falsamente pelo meu nome; nela, pernoitará e consumirá a sua madeira e as suas pedras.

[[v38-5-5]]

^<<v38-5-5,5>>^ Saiu o anjo que falava comigo e me disse: Levanta, agora, os olhos e vê que é isto que sai.

[[v38-5-6]]

^<<v38-5-6,6>>^ Eu perguntei: que é isto? Ele me respondeu: É um efa que sai. Disse ainda: Isto é a iniquidade em toda a terra.

[[v38-5-7]]

^<<v38-5-7,7>>^ Eis que foi levantada a tampa de chumbo, e uma mulher estava sentada dentro do efa.

[[v38-5-8]]

^<<v38-5-8,8>>^ Prosseguiu o anjo: Isto é a impiedade. E a lançou para o fundo do efa, sobre cuja boca pôs o peso de chumbo.

[[v38-5-9]]

^<<v38-5-9,9>>^ Levantei os olhos e vi, e eis que saíram duas mulheres; havia vento em suas asas, que eram como de cegonha; e levantaram o efa entre a terra e o céu.

[[v38-5-10]]

^<<v38-5-10,10>>^ Então, perguntei ao anjo que falava comigo: para onde levam elas o efa?

[[v38-5-11]]

^<<v38-5-11,11>>^ Respondeu-me: Para edificarem àquela mulher uma casa na terra de Sinar, e, estando esta acabada, ela será posta ali em seu próprio lugar.

'''

xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[&#60; Capítulo Anterior] | <<v38-5-0,Topo>> | xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[Próximo Capítulo &#62;]