include::./index.adoc[]

[[v38-3-0]]
=== Zacarias, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v38-3-1]]

^<<v38-3-1,1>>^ Deus me mostrou o sumo sacerdote Josué, o qual estava diante do Anjo do SENHOR, e Satanás estava à mão direita dele, para se lhe opor.

[[v38-3-2]]

^<<v38-3-2,2>>^ Mas o SENHOR disse a Satanás: O SENHOR te repreende, ó Satanás; sim, o SENHOR, que escolheu a Jerusalém, te repreende; não é este um tição tirado do fogo?

[[v38-3-3]]

^<<v38-3-3,3>>^ Ora, Josué, trajado de vestes sujas, estava diante do Anjo.

[[v38-3-4]]

^<<v38-3-4,4>>^ Tomou este a palavra e disse aos que estavam diante dele: Tirai-lhe as vestes sujas. A Josué disse: Eis que tenho feito que passe de ti a tua iniquidade e te vestirei de finos trajes.

[[v38-3-5]]

^<<v38-3-5,5>>^ E disse eu: ponham-lhe um turbante limpo sobre a cabeça. Puseram-lhe, pois, sobre a cabeça um turbante limpo e o vestiram com trajes próprios; e o Anjo do SENHOR estava ali,

[[v38-3-6]]

^<<v38-3-6,6>>^ protestou a Josué e disse:

[[v38-3-7]]

^<<v38-3-7,7>>^ Assim diz o SENHOR dos Exércitos: Se andares nos meus caminhos e observares os meus preceitos, também tu julgarás a minha casa e guardarás os meus átrios, e te darei livre acesso entre estes que aqui se encontram.

[[v38-3-8]]

^<<v38-3-8,8>>^ Ouve, pois, Josué, sumo sacerdote, tu e os teus companheiros que se assentam diante de ti, porque são homens de presságio; eis que eu farei vir o meu servo, o Renovo.

[[v38-3-9]]

^<<v38-3-9,9>>^ Porque eis aqui a pedra que pus diante de Josué; sobre esta pedra única estão sete olhos; eis que eu lavrarei a sua escultura, diz o SENHOR dos Exércitos, e tirarei a iniquidade desta terra, num só dia.

[[v38-3-10]]

^<<v38-3-10,10>>^ Naquele dia, diz o SENHOR dos Exércitos, cada um de vós convidará ao seu próximo para debaixo da vide e para debaixo da figueira.

'''

xref:038-zacarias/038-zacarias-002.adoc#v38-2-0[&#60; Capítulo Anterior] | <<v38-3-0,Topo>> | xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[Próximo Capítulo &#62;]