include::./index.adoc[]

[[v38-2-0]]
=== Zacarias, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v38-2-1]]

^<<v38-2-1,1>>^ Tornei a levantar os olhos e vi, e eis um homem que tinha na mão um cordel de medir.

[[v38-2-2]]

^<<v38-2-2,2>>^ Então, perguntei: para onde vais tu? Ele me respondeu: Medir Jerusalém, para ver qual é a sua largura e qual o seu comprimento.

[[v38-2-3]]

^<<v38-2-3,3>>^ Eis que saiu o anjo que falava comigo, e outro anjo lhe saiu ao encontro.

[[v38-2-4]]

^<<v38-2-4,4>>^ E lhe disse: Corre, fala a este jovem: Jerusalém será habitada como as aldeias sem muros, por causa da multidão de homens e animais que haverá nela.

[[v38-2-5]]

^<<v38-2-5,5>>^ Pois eu lhe serei, diz o SENHOR, um muro de fogo em redor e eu mesmo serei, no meio dela, a sua glória.

[[v38-2-6]]

^<<v38-2-6,6>>^ Eh! Eh! Fugi, agora, da terra do Norte, diz o SENHOR, porque vos espalhei como os quatro ventos do céu, diz o SENHOR.

[[v38-2-7]]

^<<v38-2-7,7>>^ Eh! Salva-te, ó Sião, tu que habitas com a filha da Babilônia.

[[v38-2-8]]

^<<v38-2-8,8>>^ Pois assim diz o SENHOR dos Exércitos: Para obter ele a glória, enviou-me às nações que vos despojaram; porque aquele que tocar em vós toca na menina do seu olho.

[[v38-2-9]]

^<<v38-2-9,9>>^ Porque eis aí agitarei a mão contra eles, e eles virão a ser a presa daqueles que os serviram; assim, sabereis vós que o SENHOR dos Exércitos é quem me enviou.

[[v38-2-10]]

^<<v38-2-10,10>>^ Canta e exulta, ó filha de Sião, porque eis que venho e habitarei no meio de ti, diz o SENHOR.

[[v38-2-11]]

^<<v38-2-11,11>>^ Naquele dia, muitas nações se ajuntarão ao SENHOR e serão o meu povo; habitarei no meio de ti, e saberás que o SENHOR dos Exércitos é quem me enviou a ti.

[[v38-2-12]]

^<<v38-2-12,12>>^ Então, o SENHOR herdará a Judá como sua porção na terra santa e, de novo, escolherá a Jerusalém.

[[v38-2-13]]

^<<v38-2-13,13>>^ Cale-se toda carne diante do SENHOR, porque ele se levantou da sua santa morada.

'''

xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[&#60; Capítulo Anterior] | <<v38-2-0,Topo>> | xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[Próximo Capítulo &#62;]