include::./index.adoc[]

[[v38-13-0]]
=== Zacarias, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v38-13-1]]

^<<v38-13-1,1>>^ Naquele dia, haverá uma fonte aberta para a casa de Davi e para os habitantes de Jerusalém, para remover o pecado e a impureza.

[[v38-13-2]]

^<<v38-13-2,2>>^ Acontecerá, naquele dia, diz o SENHOR dos Exércitos, que eliminarei da terra os nomes dos ídolos, e deles não haverá mais memória; e também removerei da terra os profetas e o espírito imundo.

[[v38-13-3]]

^<<v38-13-3,3>>^ Quando alguém ainda profetizar, seu pai e sua mãe, que o geraram, lhe dirão: Não viverás, porque tens falado mentiras em nome do SENHOR; seu pai e sua mãe, que o geraram, o traspassarão quando profetizar.

[[v38-13-4]]

^<<v38-13-4,4>>^ Naquele dia, se sentirão envergonhados os profetas, cada um da sua visão quando profetiza; nem mais se vestirão de manto de pelos, para enganarem.

[[v38-13-5]]

^<<v38-13-5,5>>^ Cada um, porém, dirá: Não sou profeta, sou lavrador da terra, porque fui comprado desde a minha mocidade.

[[v38-13-6]]

^<<v38-13-6,6>>^ Se alguém lhe disser: Que feridas são essas nas tuas mãos?, responderá ele: São as feridas com que fui ferido na casa dos meus amigos.

[[v38-13-7]]

^<<v38-13-7,7>>^ Desperta, ó espada, contra o meu pastor e contra o homem que é o meu companheiro, diz o SENHOR dos Exércitos; fere o pastor, e as ovelhas ficarão dispersas; mas volverei a mão para os pequeninos.

[[v38-13-8]]

^<<v38-13-8,8>>^ Em toda a terra, diz o SENHOR, dois terços dela serão eliminados e perecerão; mas a terceira parte restará nela.

[[v38-13-9]]

^<<v38-13-9,9>>^ Farei passar a terceira parte pelo fogo, e a purificarei como se purifica a prata, e a provarei como se prova o ouro; ela invocará o meu nome, e eu a ouvirei; direi: é meu povo, e ela dirá: O SENHOR é meu Deus.

'''

xref:038-zacarias/038-zacarias-012.adoc#v38-12-0[&#60; Capítulo Anterior] | <<v38-13-0,Topo>> | xref:038-zacarias/038-zacarias-014.adoc#v38-14-0[Próximo Capítulo &#62;]