include::./index.adoc[]

[[v38-7-0]]
=== Zacarias, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v38-7-1]]

^<<v38-7-1,1>>^ No quarto ano do rei Dario, veio a palavra do SENHOR a Zacarias, no dia quarto do nono mês, que é quisleu.

[[v38-7-2]]

^<<v38-7-2,2>>^ Quando de Betel foram enviados Sarezer, e Regém-Meleque, e seus homens, para suplicarem o favor do SENHOR,

[[v38-7-3]]

^<<v38-7-3,3>>^ perguntaram aos sacerdotes, que estavam na Casa do SENHOR dos Exércitos, e aos profetas: Continuaremos nós a chorar, com jejum, no quinto mês, como temos feito por tantos anos?

[[v38-7-4]]

^<<v38-7-4,4>>^ Então, a palavra do SENHOR dos Exércitos me veio a mim, dizendo:

[[v38-7-5]]

^<<v38-7-5,5>>^ Fala a todo o povo desta terra e aos sacerdotes: Quando jejuastes e pranteastes, no quinto e no sétimo mês, durante estes setenta anos, acaso, foi para mim que jejuastes, com efeito, para mim?

[[v38-7-6]]

^<<v38-7-6,6>>^ Quando comeis e bebeis, não é para vós mesmos que comeis e bebeis?

[[v38-7-7]]

^<<v38-7-7,7>>^ Não ouvistes vós as palavras que o SENHOR pregou pelo ministério dos profetas que nos precederam, quando Jerusalém estava habitada e em paz com as suas cidades ao redor dela, e o Sul e a campina eram habitados?

[[v38-7-8]]

^<<v38-7-8,8>>^ A palavra do SENHOR veio a Zacarias, dizendo:

[[v38-7-9]]

^<<v38-7-9,9>>^ Assim falara o SENHOR dos Exércitos: Executai juízo verdadeiro, mostrai bondade e misericórdia, cada um a seu irmão;

[[v38-7-10]]

^<<v38-7-10,10>>^ não oprimais a viúva, nem o órfão, nem o estrangeiro, nem o pobre, nem intente cada um, em seu coração, o mal contra o seu próximo.

[[v38-7-11]]

^<<v38-7-11,11>>^ Eles, porém, não quiseram atender e, rebeldes, me deram as costas e ensurdeceram os ouvidos, para que não ouvissem.

[[v38-7-12]]

^<<v38-7-12,12>>^ Sim, fizeram o seu coração duro como diamante, para que não ouvissem a lei, nem as palavras que o SENHOR dos Exércitos enviara pelo seu Espírito, mediante os profetas que nos precederam; daí veio a grande ira do SENHOR dos Exércitos.

[[v38-7-13]]

^<<v38-7-13,13>>^ Visto que eu clamei, e eles não me ouviram, eles também clamaram, e eu não os ouvi, diz o SENHOR dos Exércitos.

[[v38-7-14]]

^<<v38-7-14,14>>^ Espalhei-os com um turbilhão por entre todas as nações que eles não conheceram; e a terra foi assolada atrás deles, de sorte que ninguém passava por ela, nem voltava; porque da terra desejável fizeram uma desolação.

'''

xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[&#60; Capítulo Anterior] | <<v38-7-0,Topo>> | xref:038-zacarias/038-zacarias-008.adoc#v38-8-0[Próximo Capítulo &#62;]