include::./index.adoc[]

[[v38-6-0]]
=== Zacarias, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v38-6-1]]

^<<v38-6-1,1>>^ Outra vez, levantei os olhos e vi, e eis que quatro carros saíam dentre dois montes, e estes montes eram de bronze.

[[v38-6-2]]

^<<v38-6-2,2>>^ No primeiro carro, os cavalos eram vermelhos, no segundo, pretos,

[[v38-6-3]]

^<<v38-6-3,3>>^ no terceiro, brancos e no quarto, baios; todos eram fortes.

[[v38-6-4]]

^<<v38-6-4,4>>^ Então, perguntei ao anjo que falava comigo: que é isto, meu senhor?

[[v38-6-5]]

^<<v38-6-5,5>>^ Respondeu-me o anjo: São os quatro ventos do céu, que saem donde estavam perante o Senhor de toda a terra.

[[v38-6-6]]

^<<v38-6-6,6>>^ O carro em que estão os cavalos pretos sai para a terra do Norte; o dos brancos, após eles; o dos baios, para a terra do Sul.

[[v38-6-7]]

^<<v38-6-7,7>>^ Saem, assim, os cavalos fortes, forcejando por andar avante, para percorrerem a terra. O SENHOR lhes disse: Ide, percorrei a terra. E percorriam a terra.

[[v38-6-8]]

^<<v38-6-8,8>>^ E me chamou e me disse: Eis que aqueles que saíram para a terra do Norte fazem repousar o meu Espírito na terra do Norte.

[[v38-6-9]]

^<<v38-6-9,9>>^ A palavra do SENHOR veio a mim, dizendo:

[[v38-6-10]]

^<<v38-6-10,10>>^ Recebe dos que foram levados cativos, a saber, de Heldai, de Tobias e de Jedaías, e vem tu no mesmo dia e entra na casa de Josias, filho de Sofonias, para a qual vieram da Babilônia.

[[v38-6-11]]

^<<v38-6-11,11>>^ Recebe, digo, prata e ouro, e faze coroas, e põe-nas na cabeça de Josué, filho de Jozadaque, o sumo sacerdote.

[[v38-6-12]]

^<<v38-6-12,12>>^ E dize-lhe: Assim diz o SENHOR dos Exércitos: Eis aqui o homem cujo nome é Renovo; ele brotará do seu lugar e edificará o templo do SENHOR.

[[v38-6-13]]

^<<v38-6-13,13>>^ Ele mesmo edificará o templo do SENHOR e será revestido de glória; assentar-se-á no seu trono, e dominará, e será sacerdote no seu trono; e reinará perfeita união entre ambos os ofícios.

[[v38-6-14]]

^<<v38-6-14,14>>^ As coroas serão para Helém, para Tobias, para Jedaías e para Hem, filho de Sofonias, como memorial no templo do SENHOR.

[[v38-6-15]]

^<<v38-6-15,15>>^ Aqueles que estão longe virão e ajudarão no edificar o templo do SENHOR, e sabereis que o SENHOR dos Exércitos me enviou a vós outros. Isto sucederá se diligentemente ouvirdes a voz do SENHOR, vosso Deus.

'''

xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[&#60; Capítulo Anterior] | <<v38-6-0,Topo>> | xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[Próximo Capítulo &#62;]