include::./index.adoc[]

[[v38-12-0]]
=== Zacarias, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v38-12-1]]

^<<v38-12-1,1>>^ Sentença pronunciada pelo SENHOR contra Israel. Fala o SENHOR, o que estendeu o céu, fundou a terra e formou o espírito do homem dentro dele.

[[v38-12-2]]

^<<v38-12-2,2>>^ Eis que eu farei de Jerusalém um cálice de tontear para todos os povos em redor e também para Judá, durante o sítio contra Jerusalém.

[[v38-12-3]]

^<<v38-12-3,3>>^ Naquele dia, farei de Jerusalém uma pedra pesada para todos os povos; todos os que a erguerem se ferirão gravemente; e, contra ela, se ajuntarão todas as nações da terra.

[[v38-12-4]]

^<<v38-12-4,4>>^ Naquele dia, diz o SENHOR, ferirei de espanto a todos os cavalos e de loucura os que os montam; sobre a casa de Judá abrirei os olhos e ferirei de cegueira a todos os cavalos dos povos.

[[v38-12-5]]

^<<v38-12-5,5>>^ Então, os chefes de Judá pensarão assim: Os habitantes de Jerusalém têm a força do SENHOR dos Exércitos, seu Deus.

[[v38-12-6]]

^<<v38-12-6,6>>^ Naquele dia, porei os chefes de Judá como um braseiro ardente debaixo da lenha e como uma tocha entre a palha; eles devorarão, à direita e à esquerda, a todos os povos em redor, e Jerusalém será habitada outra vez no seu próprio lugar, em Jerusalém mesma.

[[v38-12-7]]

^<<v38-12-7,7>>^ O SENHOR salvará primeiramente as tendas de Judá, para que a glória da casa de Davi e a glória dos habitantes de Jerusalém não sejam exaltadas acima de Judá.

[[v38-12-8]]

^<<v38-12-8,8>>^ Naquele dia, o SENHOR protegerá os habitantes de Jerusalém; e o mais fraco dentre eles, naquele dia, será como Davi, e a casa de Davi será como Deus, como o Anjo do SENHOR diante deles.

[[v38-12-9]]

^<<v38-12-9,9>>^ Naquele dia, procurarei destruir todas as nações que vierem contra Jerusalém.

[[v38-12-10]]

^<<v38-12-10,10>>^ E sobre a casa de Davi e sobre os habitantes de Jerusalém derramarei o espírito da graça e de súplicas; olharão para aquele a quem traspassaram; pranteá-lo-ão como quem pranteia por um unigênito e chorarão por ele como se chora amargamente pelo primogênito.

[[v38-12-11]]

^<<v38-12-11,11>>^ Naquele dia, será grande o pranto em Jerusalém, como o pranto de Hadade-Rimom, no vale de Megido.

[[v38-12-12]]

^<<v38-12-12,12>>^ A terra pranteará, cada família à parte; a família da casa de Davi à parte, e suas mulheres à parte; a família da casa de Natã à parte, e suas mulheres à parte;

[[v38-12-13]]

^<<v38-12-13,13>>^ a família da casa de Levi à parte, e suas mulheres à parte; a família dos simeítas à parte, e suas mulheres à parte.

[[v38-12-14]]

^<<v38-12-14,14>>^ Todas as mais famílias, cada família à parte, e suas mulheres à parte.

'''

xref:038-zacarias/038-zacarias-011.adoc#v38-11-0[&#60; Capítulo Anterior] | <<v38-12-0,Topo>> | xref:038-zacarias/038-zacarias-013.adoc#v38-13-0[Próximo Capítulo &#62;]