include::./index.adoc[]

[[v27-8-0]]
=== Daniel, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v27-8-1]]

^<<v27-8-1,1>>^ No ano terceiro do reinado do rei Belsazar, eu, Daniel, tive uma visão depois daquela que eu tivera a princípio.

[[v27-8-2]]

^<<v27-8-2,2>>^ Quando a visão me veio, pareceu-me estar eu na cidadela de Susã, que é província de Elão, e vi que estava junto ao rio Ulai.

[[v27-8-3]]

^<<v27-8-3,3>>^ Então, levantei os olhos e vi, e eis que, diante do rio, estava um carneiro, o qual tinha dois chifres, e os dois chifres eram altos, mas um, mais alto do que o outro; e o mais alto subiu por último.

[[v27-8-4]]

^<<v27-8-4,4>>^ Vi que o carneiro dava marradas para o ocidente, e para o norte, e para o sul; e nenhum dos animais lhe podia resistir, nem havia quem pudesse livrar-se do seu poder; ele, porém, fazia segundo a sua vontade e, assim, se engrandecia.

[[v27-8-5]]

^<<v27-8-5,5>>^ Estando eu observando, eis que um bode vinha do ocidente sobre toda a terra, mas sem tocar no chão; este bode tinha um chifre notável entre os olhos;

[[v27-8-6]]

^<<v27-8-6,6>>^ dirigiu-se ao carneiro que tinha os dois chifres, o qual eu tinha visto diante do rio; e correu contra ele com todo o seu furioso poder.

[[v27-8-7]]

^<<v27-8-7,7>>^ Vi-o chegar perto do carneiro, e, enfurecido contra ele, o feriu e lhe quebrou os dois chifres, pois não havia força no carneiro para lhe resistir; e o bode o lançou por terra e o pisou aos pés, e não houve quem pudesse livrar o carneiro do poder dele.

[[v27-8-8]]

^<<v27-8-8,8>>^ O bode se engrandeceu sobremaneira; e, na sua força, quebrou-se-lhe o grande chifre, e em seu lugar saíram quatro chifres notáveis, para os quatro ventos do céu.

[[v27-8-9]]

^<<v27-8-9,9>>^ De um dos chifres saiu um chifre pequeno e se tornou muito forte para o sul, para o oriente e para a terra gloriosa.

[[v27-8-10]]

^<<v27-8-10,10>>^ Cresceu até atingir o exército dos céus; a alguns do exército e das estrelas lançou por terra e os pisou.

[[v27-8-11]]

^<<v27-8-11,11>>^ Sim, engrandeceu-se até ao príncipe do exército; dele tirou o sacrifício diário e o lugar do seu santuário foi deitado abaixo.

[[v27-8-12]]

^<<v27-8-12,12>>^ O exército lhe foi entregue, com o sacrifício diário, por causa das transgressões; e deitou por terra a verdade; e o que fez prosperou.

[[v27-8-13]]

^<<v27-8-13,13>>^ Depois, ouvi um santo que falava; e disse outro santo àquele que falava: Até quando durará a visão do sacrifício diário e da transgressão assoladora, visão na qual é entregue o santuário e o exército, a fim de serem pisados?

[[v27-8-14]]

^<<v27-8-14,14>>^ Ele me disse: Até duas mil e trezentas tardes e manhãs; e o santuário será purificado.

[[v27-8-15]]

^<<v27-8-15,15>>^ Havendo eu, Daniel, tido a visão, procurei entendê-la, e eis que se me apresentou diante uma como aparência de homem.

[[v27-8-16]]

^<<v27-8-16,16>>^ E ouvi uma voz de homem de entre as margens do Ulai, a qual gritou e disse: Gabriel, dá a entender a este a visão.

[[v27-8-17]]

^<<v27-8-17,17>>^ Veio, pois, para perto donde eu estava; ao chegar ele, fiquei amedrontado e prostrei-me com o rosto em terra; mas ele me disse: Entende, filho do homem, pois esta visão se refere ao tempo do fim.

[[v27-8-18]]

^<<v27-8-18,18>>^ Falava ele comigo quando caí sem sentidos, rosto em terra; ele, porém, me tocou e me pôs em pé no lugar onde eu me achava;

[[v27-8-19]]

^<<v27-8-19,19>>^ e disse: Eis que te farei saber o que há de acontecer no último tempo da ira, porque esta visão se refere ao tempo determinado do fim.

[[v27-8-20]]

^<<v27-8-20,20>>^ Aquele carneiro com dois chifres, que viste, são os reis da Média e da Pérsia;

[[v27-8-21]]

^<<v27-8-21,21>>^ mas o bode peludo é o rei da Grécia; o chifre grande entre os olhos é o primeiro rei;

[[v27-8-22]]

^<<v27-8-22,22>>^ o ter sido quebrado, levantando-se quatro em lugar dele, significa que quatro reinos se levantarão deste povo, mas não com força igual à que ele tinha.

[[v27-8-23]]

^<<v27-8-23,23>>^ Mas, no fim do seu reinado, quando os prevaricadores acabarem, levantar-se-á um rei de feroz catadura e especialista em intrigas.

[[v27-8-24]]

^<<v27-8-24,24>>^ Grande é o seu poder, mas não por sua própria força; causará estupendas destruições, prosperará e fará o que lhe aprouver; destruirá os poderosos e o povo santo.

[[v27-8-25]]

^<<v27-8-25,25>>^ Por sua astúcia nos seus empreendimentos, fará prosperar o engano, no seu coração se engrandecerá e destruirá a muitos que vivem despreocupadamente; levantar-se-á contra o Príncipe dos príncipes, mas será quebrado sem esforço de mãos humanas.

[[v27-8-26]]

^<<v27-8-26,26>>^ A visão da tarde e da manhã, que foi dita, é verdadeira; tu, porém, preserva a visão, porque se refere a dias ainda mui distantes.

[[v27-8-27]]

^<<v27-8-27,27>>^ Eu, Daniel, enfraqueci e estive enfermo alguns dias; então, me levantei e tratei dos negócios do rei. Espantava-me com a visão, e não havia quem a entendesse.

'''

xref:027-daniel/027-daniel-007.adoc#v27-7-0[&#60; Capítulo Anterior] | <<v27-8-0,Topo>> | xref:027-daniel/027-daniel-009.adoc#v27-9-0[Próximo Capítulo &#62;]