include::./index.adoc[]

[[v27-5-0]]
=== Daniel, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v27-5-1]]

^<<v27-5-1,1>>^ O rei Belsazar deu um grande banquete a mil dos seus grandes e bebeu vinho na presença dos mil.

[[v27-5-2]]

^<<v27-5-2,2>>^ Enquanto Belsazar bebia e apreciava o vinho, mandou trazer os utensílios de ouro e de prata que Nabucodonosor, seu pai, tirara do templo, que estava em Jerusalém, para que neles bebessem o rei e os seus grandes, as suas mulheres e concubinas.

[[v27-5-3]]

^<<v27-5-3,3>>^ Então, trouxeram os utensílios de ouro, que foram tirados do templo da Casa de Deus que estava em Jerusalém, e beberam neles o rei, os seus grandes e as suas mulheres e concubinas.

[[v27-5-4]]

^<<v27-5-4,4>>^ Beberam o vinho e deram louvores aos deuses de ouro, de prata, de bronze, de ferro, de madeira e de pedra.

[[v27-5-5]]

^<<v27-5-5,5>>^ No mesmo instante, apareceram uns dedos de mão de homem e escreviam, defronte do candeeiro, na caiadura da parede do palácio real; e o rei via os dedos que estavam escrevendo.

[[v27-5-6]]

^<<v27-5-6,6>>^ Então, se mudou o semblante do rei, e os seus pensamentos o turbaram; as juntas dos seus lombos se relaxaram, e os seus joelhos batiam um no outro.

[[v27-5-7]]

^<<v27-5-7,7>>^ O rei ordenou, em voz alta, que se introduzissem os encantadores, os caldeus e os feiticeiros; falou o rei e disse aos sábios da Babilônia: Qualquer que ler esta escritura e me declarar a sua interpretação será vestido de púrpura, trará uma cadeia de ouro ao pescoço e será o terceiro no meu reino.

[[v27-5-8]]

^<<v27-5-8,8>>^ Então, entraram todos os sábios do rei; mas não puderam ler a escritura, nem fazer saber ao rei a sua interpretação.

[[v27-5-9]]

^<<v27-5-9,9>>^ Com isto, se perturbou muito o rei Belsazar, e mudou-se-lhe o semblante; e os seus grandes estavam sobressaltados.

[[v27-5-10]]

^<<v27-5-10,10>>^ A rainha-mãe, por causa do que havia acontecido ao rei e aos seus grandes, entrou na casa do banquete e disse: Ó rei, vive eternamente! Não te turbem os teus pensamentos, nem se mude o teu semblante.

[[v27-5-11]]

^<<v27-5-11,11>>^ Há no teu reino um homem que tem o espírito dos deuses santos; nos dias de teu pai, se achou nele luz, e inteligência, e sabedoria como a sabedoria dos deuses; teu pai, o rei Nabucodonosor, sim, teu pai, ó rei, o constituiu chefe dos magos, dos encantadores, dos caldeus e dos feiticeiros,

[[v27-5-12]]

^<<v27-5-12,12>>^ porquanto espírito excelente, conhecimento e inteligência, interpretação de sonhos, declaração de enigmas e solução de casos difíceis se acharam neste Daniel, a quem o rei pusera o nome de Beltessazar; chame-se, pois, a Daniel, e ele dará a interpretação.

[[v27-5-13]]

^<<v27-5-13,13>>^ Então, Daniel foi introduzido à presença do rei. Falou o rei e disse a Daniel: És tu aquele Daniel, dos cativos de Judá, que o rei, meu pai, trouxe de Judá?

[[v27-5-14]]

^<<v27-5-14,14>>^ Tenho ouvido dizer a teu respeito que o espírito dos deuses está em ti, e que em ti se acham luz, inteligência e excelente sabedoria.

[[v27-5-15]]

^<<v27-5-15,15>>^ Acabam de ser introduzidos à minha presença os sábios e os encantadores, para lerem esta escritura e me fazerem saber a sua interpretação; mas não puderam dar a interpretação destas palavras.

[[v27-5-16]]

^<<v27-5-16,16>>^ Eu, porém, tenho ouvido dizer de ti que podes dar interpretações e solucionar casos difíceis; agora, se puderes ler esta escritura e fazer-me saber a sua interpretação, serás vestido de púrpura, terás cadeia de ouro ao pescoço e serás o terceiro no meu reino.

[[v27-5-17]]

^<<v27-5-17,17>>^ Então, respondeu Daniel e disse na presença do rei: Os teus presentes fiquem contigo, e dá os teus prêmios a outrem; todavia, lerei ao rei a escritura e lhe farei saber a interpretação.

[[v27-5-18]]

^<<v27-5-18,18>>^ Ó rei! Deus, o Altíssimo, deu a Nabucodonosor, teu pai, o reino e grandeza, glória e majestade.

[[v27-5-19]]

^<<v27-5-19,19>>^ Por causa da grandeza que lhe deu, povos, nações e homens de todas as línguas tremiam e temiam diante dele; matava a quem queria e a quem queria deixava com vida; a quem queria exaltava e a quem queria abatia.

[[v27-5-20]]

^<<v27-5-20,20>>^ Quando, porém, o seu coração se elevou, e o seu espírito se tornou soberbo e arrogante, foi derribado do seu trono real, e passou dele a sua glória.

[[v27-5-21]]

^<<v27-5-21,21>>^ Foi expulso dentre os filhos dos homens, o seu coração foi feito semelhante ao dos animais, e a sua morada foi com os jumentos monteses; deram-lhe a comer erva como aos bois, e do orvalho do céu foi molhado o seu corpo, até que conheceu que Deus, o Altíssimo, tem domínio sobre o reino dos homens e a quem quer constitui sobre ele.

[[v27-5-22]]

^<<v27-5-22,22>>^ Tu, Belsazar, que és seu filho, não humilhaste o teu coração, ainda que sabias tudo isto.

[[v27-5-23]]

^<<v27-5-23,23>>^ E te levantaste contra o Senhor do céu, pois foram trazidos os utensílios da casa dele perante ti, e tu, e os teus grandes, e as tuas mulheres, e as tuas concubinas bebestes vinho neles; além disso, deste louvores aos deuses de prata, de ouro, de bronze, de ferro, de madeira e de pedra, que não veem, não ouvem, nem sabem; mas a Deus, em cuja mão está a tua vida e todos os teus caminhos, a ele não glorificaste.

[[v27-5-24]]

^<<v27-5-24,24>>^ Então, da parte dele foi enviada aquela mão que traçou esta escritura.

[[v27-5-25]]

^<<v27-5-25,25>>^ Esta, pois, é a escritura que se traçou: Mene , Mene , Tequel  e Parsim .

[[v27-5-26]]

^<<v27-5-26,26>>^ Esta é a interpretação daquilo: Mene : Contou Deus o teu reino e deu cabo dele.

[[v27-5-27]]

^<<v27-5-27,27>>^ Tequel : Pesado foste na balança e achado em falta.

[[v27-5-28]]

^<<v27-5-28,28>>^ Peres : Dividido foi o teu reino e dado aos medos e aos persas.

[[v27-5-29]]

^<<v27-5-29,29>>^ Então, mandou Belsazar que vestissem Daniel de púrpura, e lhe pusessem cadeia de ouro ao pescoço, e proclamassem que passaria a ser o terceiro no governo do seu reino.

[[v27-5-30]]

^<<v27-5-30,30>>^ Naquela mesma noite, foi morto Belsazar, rei dos caldeus.

[[v27-5-31]]

^<<v27-5-31,31>>^ E Dario, o medo, com cerca de sessenta e dois anos, se apoderou do reino.

'''

xref:027-daniel/027-daniel-004.adoc#v27-4-0[&#60; Capítulo Anterior] | <<v27-5-0,Topo>> | xref:027-daniel/027-daniel-006.adoc#v27-6-0[Próximo Capítulo &#62;]