include::./index.adoc[]

[[v27-1-0]]
=== Daniel, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v27-1-1]]

^<<v27-1-1,1>>^ No ano terceiro do reinado de Jeoaquim, rei de Judá, veio Nabucodonosor, rei da Babilônia, a Jerusalém e a sitiou.

[[v27-1-2]]

^<<v27-1-2,2>>^ O Senhor lhe entregou nas mãos a Jeoaquim, rei de Judá, e alguns dos utensílios da Casa de Deus; a estes, levou-os para a terra de Sinar, para a casa do seu deus, e os pôs na casa do tesouro do seu deus.

[[v27-1-3]]

^<<v27-1-3,3>>^ Disse o rei a Aspenaz, chefe dos seus eunucos, que trouxesse alguns dos filhos de Israel, tanto da linhagem real como dos nobres,

[[v27-1-4]]

^<<v27-1-4,4>>^ jovens sem nenhum defeito, de boa aparência, instruídos em toda a sabedoria, doutos em ciência, versados no conhecimento e que fossem competentes para assistirem no palácio do rei e lhes ensinasse a cultura e a língua dos caldeus.

[[v27-1-5]]

^<<v27-1-5,5>>^ Determinou-lhes o rei a ração diária, das finas iguarias da mesa real e do vinho que ele bebia, e que assim fossem mantidos por três anos, ao cabo dos quais assistiriam diante do rei.

[[v27-1-6]]

^<<v27-1-6,6>>^ Entre eles, se achavam, dos filhos de Judá, Daniel, Hananias, Misael e Azarias.

[[v27-1-7]]

^<<v27-1-7,7>>^ O chefe dos eunucos lhes pôs outros nomes, a saber: a Daniel, o de Beltessazar; a Hananias, o de Sadraque; a Misael, o de Mesaque; e a Azarias, o de Abede-Nego.

[[v27-1-8]]

^<<v27-1-8,8>>^ Resolveu Daniel, firmemente, não contaminar-se com as finas iguarias do rei, nem com o vinho que ele bebia; então, pediu ao chefe dos eunucos que lhe permitisse não contaminar-se.

[[v27-1-9]]

^<<v27-1-9,9>>^ Ora, Deus concedeu a Daniel misericórdia e compreensão da parte do chefe dos eunucos.

[[v27-1-10]]

^<<v27-1-10,10>>^ Disse o chefe dos eunucos a Daniel: Tenho medo do meu senhor, o rei, que determinou a vossa comida e a vossa bebida; por que, pois, veria ele o vosso rosto mais abatido do que o dos outros jovens da vossa idade? Assim, poríeis em perigo a minha cabeça para com o rei.

[[v27-1-11]]

^<<v27-1-11,11>>^ Então, disse Daniel ao cozinheiro-chefe, a quem o chefe dos eunucos havia encarregado de cuidar de Daniel, Hananias, Misael e Azarias:

[[v27-1-12]]

^<<v27-1-12,12>>^ Experimenta, peço-te, os teus servos dez dias; e que se nos deem legumes a comer e água a beber.

[[v27-1-13]]

^<<v27-1-13,13>>^ Então, se veja diante de ti a nossa aparência e a dos jovens que comem das finas iguarias do rei; e, segundo vires, age com os teus servos.

[[v27-1-14]]

^<<v27-1-14,14>>^ Ele atendeu e os experimentou dez dias.

[[v27-1-15]]

^<<v27-1-15,15>>^ No fim dos dez dias, a sua aparência era melhor; estavam eles mais robustos do que todos os jovens que comiam das finas iguarias do rei.

[[v27-1-16]]

^<<v27-1-16,16>>^ Com isto, o cozinheiro-chefe tirou deles as finas iguarias e o vinho que deviam beber e lhes dava legumes.

[[v27-1-17]]

^<<v27-1-17,17>>^ Ora, a estes quatro jovens Deus deu o conhecimento e a inteligência em toda cultura e sabedoria; mas a Daniel deu inteligência de todas as visões e sonhos.

[[v27-1-18]]

^<<v27-1-18,18>>^ Vencido o tempo determinado pelo rei para que os trouxessem, o chefe dos eunucos os trouxe à presença de Nabucodonosor.

[[v27-1-19]]

^<<v27-1-19,19>>^ Então, o rei falou com eles; e, entre todos, não foram achados outros como Daniel, Hananias, Misael e Azarias; por isso, passaram a assistir diante do rei.

[[v27-1-20]]

^<<v27-1-20,20>>^ Em toda matéria de sabedoria e de inteligência sobre que o rei lhes fez perguntas, os achou dez vezes mais doutos do que todos os magos e encantadores que havia em todo o seu reino.

[[v27-1-21]]

^<<v27-1-21,21>>^ Daniel continuou até ao primeiro ano do rei Ciro.

'''

xref:026-ezequiel/026-ezequiel-048.adoc#v26-48-0[&#60; Capítulo Anterior] | <<v27-1-0,Topo>> | xref:027-daniel/027-daniel-002.adoc#v27-2-0[Próximo Capítulo &#62;]