include::./index.adoc[]

[[v27-9-0]]
=== Daniel, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v27-9-1]]

^<<v27-9-1,1>>^ No primeiro ano de Dario, filho de Assuero, da linhagem dos medos, o qual foi constituído rei sobre o reino dos caldeus,

[[v27-9-2]]

^<<v27-9-2,2>>^ no primeiro ano do seu reinado, eu, Daniel, entendi, pelos livros, que o número de anos, de que falara o SENHOR ao profeta Jeremias, que haviam de durar as assolações de Jerusalém, era de setenta anos.

[[v27-9-3]]

^<<v27-9-3,3>>^ Voltei o rosto ao Senhor Deus, para o buscar com oração e súplicas, com jejum, pano de saco e cinza.

[[v27-9-4]]

^<<v27-9-4,4>>^ Orei ao SENHOR, meu Deus, confessei e disse: ah! Senhor! Deus grande e temível, que guardas a aliança e a misericórdia para com os que te amam e guardam os teus mandamentos;

[[v27-9-5]]

^<<v27-9-5,5>>^ temos pecado e cometido iniquidades, procedemos perversamente e fomos rebeldes, apartando-nos dos teus mandamentos e dos teus juízos;

[[v27-9-6]]

^<<v27-9-6,6>>^ e não demos ouvidos aos teus servos, os profetas, que em teu nome falaram aos nossos reis, nossos príncipes e nossos pais, como também a todo o povo da terra.

[[v27-9-7]]

^<<v27-9-7,7>>^ A ti, ó Senhor, pertence a justiça, mas a nós, o corar de vergonha, como hoje se vê; aos homens de Judá, os moradores de Jerusalém, todo o Israel, quer os de perto, quer os de longe, em todas as terras por onde os tens lançado, por causa das suas transgressões que cometeram contra ti.

[[v27-9-8]]

^<<v27-9-8,8>>^ Ó SENHOR, a nós pertence o corar de vergonha, aos nossos reis, aos nossos príncipes e aos nossos pais, porque temos pecado contra ti.

[[v27-9-9]]

^<<v27-9-9,9>>^ Ao Senhor, nosso Deus, pertence a misericórdia e o perdão, pois nos temos rebelado contra ele

[[v27-9-10]]

^<<v27-9-10,10>>^ e não obedecemos à voz do SENHOR, nosso Deus, para andarmos nas suas leis, que nos deu por intermédio de seus servos, os profetas.

[[v27-9-11]]

^<<v27-9-11,11>>^ Sim, todo o Israel transgrediu a tua lei, desviando-se, para não obedecer à tua voz; por isso, a maldição e as imprecações que estão escritas na Lei de Moisés, servo de Deus, se derramaram sobre nós, porque temos pecado contra ti.

[[v27-9-12]]

^<<v27-9-12,12>>^ Ele confirmou a sua palavra, que falou contra nós e contra os nossos juízes que nos julgavam, e fez vir sobre nós grande mal, porquanto nunca, debaixo de todo o céu, aconteceu o que se deu em Jerusalém.

[[v27-9-13]]

^<<v27-9-13,13>>^ Como está escrito na Lei de Moisés, todo este mal nos sobreveio; apesar disso, não temos implorado o favor do SENHOR, nosso Deus, para nos convertermos das nossas iniquidades e nos aplicarmos à tua verdade.

[[v27-9-14]]

^<<v27-9-14,14>>^ Por isso, o SENHOR cuidou em trazer sobre nós o mal e o fez vir sobre nós; pois justo é o SENHOR, nosso Deus, em todas as suas obras que faz, pois não obedecemos à sua voz.

[[v27-9-15]]

^<<v27-9-15,15>>^ Na verdade, ó Senhor, nosso Deus, que tiraste o teu povo da terra do Egito com mão poderosa, e a ti mesmo adquiriste renome, como hoje se vê, temos pecado e procedido perversamente.

[[v27-9-16]]

^<<v27-9-16,16>>^ Ó Senhor, segundo todas as tuas justiças, aparte-se a tua ira e o teu furor da tua cidade de Jerusalém, do teu santo monte, porquanto, por causa dos nossos pecados e por causa das iniquidades de nossos pais, se tornaram Jerusalém e o teu povo opróbrio para todos os que estão em redor de nós.

[[v27-9-17]]

^<<v27-9-17,17>>^ Agora, pois, ó Deus nosso, ouve a oração do teu servo e as suas súplicas e sobre o teu santuário assolado faze resplandecer o rosto, por amor do Senhor.

[[v27-9-18]]

^<<v27-9-18,18>>^ Inclina, ó Deus meu, os ouvidos e ouve; abre os olhos e olha para a nossa desolação e para a cidade que é chamada pelo teu nome, porque não lançamos as nossas súplicas perante a tua face fiados em nossas justiças, mas em tuas muitas misericórdias.

[[v27-9-19]]

^<<v27-9-19,19>>^ Ó Senhor, ouve; ó Senhor, perdoa; ó Senhor, atende-nos e age; não te retardes, por amor de ti mesmo, ó Deus meu; porque a tua cidade e o teu povo são chamados pelo teu nome.

[[v27-9-20]]

^<<v27-9-20,20>>^ Falava eu ainda, e orava, e confessava o meu pecado e o pecado do meu povo de Israel, e lançava a minha súplica perante a face do SENHOR, meu Deus, pelo monte santo do meu Deus.

[[v27-9-21]]

^<<v27-9-21,21>>^ Falava eu, digo, falava ainda na oração, quando o homem Gabriel, que eu tinha observado na minha visão ao princípio, veio rapidamente, voando, e me tocou à hora do sacrifício da tarde.

[[v27-9-22]]

^<<v27-9-22,22>>^ Ele queria instruir-me, falou comigo e disse: Daniel, agora, saí para fazer-te entender o sentido.

[[v27-9-23]]

^<<v27-9-23,23>>^ No princípio das tuas súplicas, saiu a ordem, e eu vim, para to declarar, porque és mui amado; considera, pois, a coisa e entende a visão.

[[v27-9-24]]

^<<v27-9-24,24>>^ Setenta semanas estão determinadas sobre o teu povo e sobre a tua santa cidade, para fazer cessar a transgressão, para dar fim aos pecados, para expiar a iniquidade, para trazer a justiça eterna, para selar a visão e a profecia e para ungir o Santo dos Santos.

[[v27-9-25]]

^<<v27-9-25,25>>^ Sabe e entende: desde a saída da ordem para restaurar e para edificar Jerusalém, até ao Ungido, ao Príncipe, sete semanas e sessenta e duas semanas; as praças e as circunvalações se reedificarão, mas em tempos angustiosos.

[[v27-9-26]]

^<<v27-9-26,26>>^ Depois das sessenta e duas semanas, será morto o Ungido e já não estará; e o povo de um príncipe que há de vir destruirá a cidade e o santuário, e o seu fim será num dilúvio, e até ao fim haverá guerra; desolações são determinadas.

[[v27-9-27]]

^<<v27-9-27,27>>^ Ele fará firme aliança com muitos, por uma semana; na metade da semana, fará cessar o sacrifício e a oferta de manjares; sobre a asa das abominações virá o assolador, até que a destruição, que está determinada, se derrame sobre ele.

'''

xref:027-daniel/027-daniel-008.adoc#v27-8-0[&#60; Capítulo Anterior] | <<v27-9-0,Topo>> | xref:027-daniel/027-daniel-010.adoc#v27-10-0[Próximo Capítulo &#62;]