include::./index.adoc[]

[[v13-29-0]]
=== 1 Crônicas, 29
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-29-1]]

^<<v13-29-1,1>>^ Disse mais o rei Davi a toda a congregação: Salomão, meu filho, o único a quem Deus escolheu, é ainda moço e inexperiente, e esta obra é grande; porque o palácio não é para homens, mas para o SENHOR Deus.

[[v13-29-2]]

^<<v13-29-2,2>>^ Eu, pois, com todas as minhas forças já preparei para a casa de meu Deus ouro para as obras de ouro, prata para as de prata, bronze para as de bronze, ferro para as de ferro e madeira para as de madeira; pedras de ônix, pedras de engaste, pedras de várias cores, de mosaicos e toda sorte de pedras preciosas, e mármore, e tudo em abundância.

[[v13-29-3]]

^<<v13-29-3,3>>^ E ainda, porque amo a casa de meu Deus, o ouro e a prata particulares que tenho dou para a casa de meu Deus, afora tudo quanto preparei para o santuário:

[[v13-29-4]]

^<<v13-29-4,4>>^ três mil talentos de ouro, do ouro de Ofir, e sete mil talentos de prata purificada, para cobrir as paredes das casas;

[[v13-29-5]]

^<<v13-29-5,5>>^ ouro para os objetos de ouro e prata para os de prata, e para toda obra de mão dos artífices. Quem, pois, está disposto, hoje, a trazer ofertas liberalmente ao SENHOR?

[[v13-29-6]]

^<<v13-29-6,6>>^ Então, os chefes das famílias, os príncipes das tribos de Israel, os capitães de mil e os de cem e até os intendentes sobre as empresas do rei voluntariamente contribuíram

[[v13-29-7]]

^<<v13-29-7,7>>^ e deram para o serviço da Casa de Deus cinco mil talentos de ouro, dez mil daricos, dez mil talentos de prata, dezoito mil talentos de bronze e cem mil talentos de ferro.

[[v13-29-8]]

^<<v13-29-8,8>>^ Os que possuíam pedras preciosas as trouxeram para o tesouro da Casa do SENHOR, a cargo de Jeiel, o gersonita.

[[v13-29-9]]

^<<v13-29-9,9>>^ O povo se alegrou com tudo o que se fez voluntariamente; porque de coração íntegro deram eles liberalmente ao SENHOR; também o rei Davi se alegrou com grande júbilo.

[[v13-29-10]]

^<<v13-29-10,10>>^ Pelo que Davi louvou ao SENHOR perante a congregação toda e disse: Bendito és tu, SENHOR, Deus de Israel, nosso pai, de eternidade em eternidade.

[[v13-29-11]]

^<<v13-29-11,11>>^ Teu, SENHOR, é o poder, a grandeza, a honra, a vitória e a majestade; porque teu é tudo quanto há nos céus e na terra; teu, SENHOR, é o reino, e tu te exaltaste por chefe sobre todos.

[[v13-29-12]]

^<<v13-29-12,12>>^ Riquezas e glória vêm de ti, tu dominas sobre tudo, na tua mão há força e poder; contigo está o engrandecer e a tudo dar força.

[[v13-29-13]]

^<<v13-29-13,13>>^ Agora, pois, ó nosso Deus, graças te damos e louvamos o teu glorioso nome.

[[v13-29-14]]

^<<v13-29-14,14>>^ Porque quem sou eu, e quem é o meu povo para que pudéssemos dar voluntariamente estas coisas? Porque tudo vem de ti, e das tuas mãos to damos.

[[v13-29-15]]

^<<v13-29-15,15>>^ Porque somos estranhos diante de ti e peregrinos como todos os nossos pais; como a sombra são os nossos dias sobre a terra, e não temos permanência.

[[v13-29-16]]

^<<v13-29-16,16>>^ SENHOR, nosso Deus, toda esta abundância que preparamos para te edificar uma casa ao teu santo nome vem da tua mão e é toda tua.

[[v13-29-17]]

^<<v13-29-17,17>>^ Bem sei, meu Deus, que tu provas os corações e que da sinceridade te agradas; eu também, na sinceridade de meu coração, dei voluntariamente todas estas coisas; acabo de ver com alegria que o teu povo, que se acha aqui, te faz ofertas voluntariamente.

[[v13-29-18]]

^<<v13-29-18,18>>^ SENHOR, Deus de nossos pais Abraão, Isaque e Israel, conserva para sempre no coração do teu povo estas disposições e pensamentos, inclina-lhe o coração para contigo;

[[v13-29-19]]

^<<v13-29-19,19>>^ e a Salomão, meu filho, dá coração íntegro para guardar os teus mandamentos, os teus testemunhos e os teus estatutos, fazendo tudo para edificar este palácio para o qual providenciei.

[[v13-29-20]]

^<<v13-29-20,20>>^ Então, disse Davi a toda a congregação: Agora, louvai o SENHOR, vosso Deus. Então, toda a congregação louvou ao SENHOR, Deus de seus pais; todos inclinaram a cabeça, adoraram o SENHOR e se prostraram perante o rei.

[[v13-29-21]]

^<<v13-29-21,21>>^ Ao outro dia, trouxeram sacrifícios ao SENHOR e lhe ofereceram holocaustos de mil bezerros, mil carneiros, mil cordeiros, com as suas libações; sacrifícios em abundância por todo o Israel.

[[v13-29-22]]

^<<v13-29-22,22>>^ Comeram e beberam, naquele dia, perante o SENHOR, com grande regozijo. Pela segunda vez, fizeram rei a Salomão, filho de Davi, e o ungiram ao SENHOR por príncipe e a Zadoque, por sacerdote.

[[v13-29-23]]

^<<v13-29-23,23>>^ Salomão assentou-se no trono do SENHOR, rei, em lugar de Davi, seu pai, e prosperou; e todo o Israel lhe obedecia.

[[v13-29-24]]

^<<v13-29-24,24>>^ Todos os príncipes, os grandes e até todos os filhos do rei Davi prestaram homenagens ao rei Salomão.

[[v13-29-25]]

^<<v13-29-25,25>>^ O SENHOR engrandeceu sobremaneira a Salomão perante todo o Israel; deu-lhe majestade real, qual antes dele não teve nenhum rei em Israel.

[[v13-29-26]]

^<<v13-29-26,26>>^ Ora, Davi, filho de Jessé, reinou sobre todo o Israel.

[[v13-29-27]]

^<<v13-29-27,27>>^ O tempo que reinou sobre Israel foi de quarenta anos: em Hebrom, sete; em Jerusalém, trinta e três.

[[v13-29-28]]

^<<v13-29-28,28>>^ Morreu em ditosa velhice, cheio de dias, riquezas e glória; e Salomão, seu filho, reinou em seu lugar.

[[v13-29-29]]

^<<v13-29-29,29>>^ Os atos, pois, do rei Davi, tanto os primeiros como os últimos, eis que estão escritos nas crônicas, registrados por Samuel, o vidente, nas crônicas do profeta Natã e nas crônicas de Gade, o vidente,

[[v13-29-30]]

^<<v13-29-30,30>>^ juntamente com o que se passou no seu reinado e a respeito do seu poder e todos os acontecimentos que se deram com ele, com Israel e com todos os reinos daquelas terras.

'''

xref:013-1-cronicas/013-1-cronicas-028.adoc#v13-28-0[&#60; Capítulo Anterior] | <<v13-29-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-001.adoc#v14-1-0[Próximo Capítulo &#62;]