include::./index.adoc[]

[[v13-14-0]]
=== 1 Crônicas, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-14-1]]

^<<v13-14-1,1>>^ Então, Hirão, rei de Tiro, mandou mensageiros a Davi, e madeira de cedro, e pedreiros, e carpinteiros, para lhe edificarem uma casa.

[[v13-14-2]]

^<<v13-14-2,2>>^ Reconheceu Davi que o SENHOR o confirmara rei sobre Israel; porque, por amor do seu povo de Israel, o seu reino se tinha exaltado muito.

[[v13-14-3]]

^<<v13-14-3,3>>^ Davi tomou ainda mais mulheres em Jerusalém; e gerou ainda mais filhos e filhas.

[[v13-14-4]]

^<<v13-14-4,4>>^ São estes os nomes dos filhos que teve em Jerusalém: Samua, Sobabe, Natã, Salomão,

[[v13-14-5]]

^<<v13-14-5,5>>^ Ibar, Elisua, Elpelete,

[[v13-14-6]]

^<<v13-14-6,6>>^ Nogá, Nefegue, Jafia,

[[v13-14-7]]

^<<v13-14-7,7>>^ Elisama, Beeliada e Elifelete.

[[v13-14-8]]

^<<v13-14-8,8>>^ Ouvindo, pois, os filisteus que Davi fora ungido rei sobre todo o Israel, subiram todos para prender Davi; ouvindo-o Davi, saiu contra eles.

[[v13-14-9]]

^<<v13-14-9,9>>^ Mas vieram os filisteus e investiram contra ele no vale dos Refains.

[[v13-14-10]]

^<<v13-14-10,10>>^ Então, Davi consultou a Deus, dizendo: Subirei contra os filisteus? Entregar-mos-ás nas mãos? Respondeu-lhe o SENHOR: Sobe, porque os entregarei nas tuas mãos.

[[v13-14-11]]

^<<v13-14-11,11>>^ Subindo Davi a Baal-Perazim, ali os derrotou; e disse: Deus, por meu intermédio, rompeu as fileiras inimigas diante de mim, como quem rompe águas. Por isso, chamaram o nome daquele lugar Baal-Perazim.

[[v13-14-12]]

^<<v13-14-12,12>>^ Ali, deixaram os seus deuses; e ordenou Davi que se queimassem.

[[v13-14-13]]

^<<v13-14-13,13>>^ Porém os filisteus tornaram e fizeram uma investida no vale.

[[v13-14-14]]

^<<v13-14-14,14>>^ De novo, Davi consultou a Deus, e este lhe respondeu: Não subirás após eles; mas rodeia por detrás deles e ataca-os por defronte das amoreiras;

[[v13-14-15]]

^<<v13-14-15,15>>^ e há de ser que, ouvindo tu um estrondo de marcha pelas copas das amoreiras, então, sai à peleja; porque Deus saiu adiante de ti a ferir o exército dos filisteus.

[[v13-14-16]]

^<<v13-14-16,16>>^ Fez Davi como Deus lhe ordenara; e feriu o exército dos filisteus desde Gibeão até Gezer.

[[v13-14-17]]

^<<v13-14-17,17>>^ Assim se espalhou o renome de Davi por todas aquelas terras; pois o SENHOR o fez temível a todas aquelas gentes.

'''

xref:013-1-cronicas/013-1-cronicas-013.adoc#v13-13-0[&#60; Capítulo Anterior] | <<v13-14-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-015.adoc#v13-15-0[Próximo Capítulo &#62;]