include::./index.adoc[]

[[v13-19-0]]
=== 1 Crônicas, 19
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-19-1]]

^<<v13-19-1,1>>^ Depois disto, morreu Naás, rei dos filhos de Amom; e seu filho reinou em seu lugar.

[[v13-19-2]]

^<<v13-19-2,2>>^ Então, disse Davi: Usarei de bondade para com Hanum, filho de Naás, porque seu pai usou de bondade para comigo. Pelo que Davi enviou mensageiros para o consolar acerca de seu pai; e vieram os servos de Davi à terra dos filhos de Amom, a Hanum, para o consolarem.

[[v13-19-3]]

^<<v13-19-3,3>>^ Disseram os príncipes dos filhos de Amom a Hanum: Pensas que, por te haver Davi mandado consoladores, está honrando a teu pai? Não vieram seus servos a ti para reconhecerem, destruírem e espiarem a terra?

[[v13-19-4]]

^<<v13-19-4,4>>^ Tomou, então, Hanum os servos de Davi, e rapou-os, e lhes cortou metade das vestes até às nádegas, e os despediu.

[[v13-19-5]]

^<<v13-19-5,5>>^ Foram-se alguns e avisaram a Davi acerca destes homens; então, enviou mensageiros a encontrá-los, porque estavam sobremaneira envergonhados. Mandou o rei dizer-lhes: Deixai-vos estar em Jericó, até que vos torne a crescer a barba; e, então, vinde.

[[v13-19-6]]

^<<v13-19-6,6>>^ Vendo, pois, os filhos de Amom que se haviam tornado odiosos a Davi, então, Hanum e os filhos de Amom tomaram mil talentos de prata, para alugarem para si carros e cavaleiros da Mesopotâmia, e dos siros de Maaca, e de Zoba.

[[v13-19-7]]

^<<v13-19-7,7>>^ Alugaram para si trinta e dois mil carros, o rei de Maaca e a sua gente, e eles vieram e se acamparam diante de Medeba; também os filhos de Amom se ajuntaram das suas cidades e vieram para a guerra.

[[v13-19-8]]

^<<v13-19-8,8>>^ O que ouvindo Davi, enviou contra eles a Joabe com todo o exército dos valentes.

[[v13-19-9]]

^<<v13-19-9,9>>^ Saíram os filhos de Amom e ordenaram a batalha à entrada da porta da cidade; porém os reis que vieram estavam à parte, no campo.

[[v13-19-10]]

^<<v13-19-10,10>>^ Vendo, pois, Joabe que estava preparada contra ele a batalha, tanto pela frente como pela retaguarda, escolheu dentre todos o que havia de melhor em Israel e os formou em linha contra os siros;

[[v13-19-11]]

^<<v13-19-11,11>>^ e o resto do povo entregou a Abisai, seu irmão, e puseram-se em linha contra os filhos de Amom.

[[v13-19-12]]

^<<v13-19-12,12>>^ Disse Joabe: Se os siros forem mais fortes do que eu, tu me virás em socorro; e, se os filhos de Amom forem mais fortes do que tu, eu irei ao teu socorro.

[[v13-19-13]]

^<<v13-19-13,13>>^ Sê forte, pois; pelejemos varonilmente pelo nosso povo e pelas cidades de nosso Deus; e faça o SENHOR o que bem lhe parecer.

[[v13-19-14]]

^<<v13-19-14,14>>^ Então, avançou Joabe com o povo que estava com ele, e travaram peleja contra os siros; e estes fugiram de diante dele.

[[v13-19-15]]

^<<v13-19-15,15>>^ Vendo os filhos de Amom que os siros fugiam, também eles fugiram de diante de Abisai, irmão de Joabe, e entraram na cidade; voltou Joabe dos filhos de Amom e tornou a Jerusalém.

[[v13-19-16]]

^<<v13-19-16,16>>^ Vendo, pois, os siros que tinham sido desbaratados diante de Israel, enviaram mensageiros e fizeram sair os siros que habitavam do lado dalém do rio; Sofaque, capitão do exército de Hadadezer, marchava adiante deles.

[[v13-19-17]]

^<<v13-19-17,17>>^ Informado Davi, ajuntou a todo o Israel, passou o Jordão, veio ter com eles e ordenou contra eles a batalha; e, tendo Davi ordenado a batalha contra os siros, pelejaram estes contra ele.

[[v13-19-18]]

^<<v13-19-18,18>>^ Porém os siros fugiram de diante de Israel, e Davi matou dentre os siros os homens de sete mil carros e quarenta mil homens de pé; a Sofaque, chefe do exército, matou.

[[v13-19-19]]

^<<v13-19-19,19>>^ Vendo, pois, os servos de Hadadezer que foram feridos diante de Israel, fizeram paz com Davi e o serviram; e os siros nunca mais quiseram socorrer aos filhos de Amom.

'''

xref:013-1-cronicas/013-1-cronicas-018.adoc#v13-18-0[&#60; Capítulo Anterior] | <<v13-19-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-020.adoc#v13-20-0[Próximo Capítulo &#62;]