include::./index.adoc[]

[[v13-15-0]]
=== 1 Crônicas, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-15-1]]

^<<v13-15-1,1>>^ Fez também Davi casas para si mesmo, na Cidade de Davi; e preparou um lugar para a arca de Deus e lhe armou uma tenda.

[[v13-15-2]]

^<<v13-15-2,2>>^ Então, disse Davi: Ninguém pode levar a arca de Deus, senão os levitas; porque o SENHOR os elegeu, para levarem a arca de Deus e o servirem para sempre.

[[v13-15-3]]

^<<v13-15-3,3>>^ Davi reuniu a todo o Israel em Jerusalém, para fazerem subir a arca do SENHOR ao seu lugar, que lhe tinha preparado.

[[v13-15-4]]

^<<v13-15-4,4>>^ Reuniu Davi os filhos de Arão e os levitas:

[[v13-15-5]]

^<<v13-15-5,5>>^ dos filhos de Coate: Uriel, o chefe, e seus irmãos, cento e vinte;

[[v13-15-6]]

^<<v13-15-6,6>>^ dos filhos de Merari: Asaías, o chefe, e seus irmãos, duzentos e vinte;

[[v13-15-7]]

^<<v13-15-7,7>>^ dos filhos de Gérson: Joel, o chefe, e seus irmãos, cento e trinta;

[[v13-15-8]]

^<<v13-15-8,8>>^ dos filhos de Elisafã: Semaías, o chefe, e seus irmãos, duzentos;

[[v13-15-9]]

^<<v13-15-9,9>>^ dos filhos de Hebrom: Eliel, o chefe, e seus irmãos, oitenta;

[[v13-15-10]]

^<<v13-15-10,10>>^ dos filhos de Uziel: Aminadabe, o chefe, e seus irmãos, cento e doze.

[[v13-15-11]]

^<<v13-15-11,11>>^ Chamou Davi os sacerdotes Zadoque e Abiatar e os levitas Uriel, Asaías, Joel, Semaías, Eliel e Aminadabe

[[v13-15-12]]

^<<v13-15-12,12>>^ e lhes disse: Vós sois os cabeças das famílias dos levitas; santificai-vos, vós e vossos irmãos, para que façais subir a arca do SENHOR, Deus de Israel, ao lugar que lhe preparei.

[[v13-15-13]]

^<<v13-15-13,13>>^ Pois, visto que não a levastes na primeira vez, o SENHOR, nosso Deus, irrompeu contra nós, porque, então, não o buscamos, segundo nos fora ordenado.

[[v13-15-14]]

^<<v13-15-14,14>>^ Santificaram-se, pois, os sacerdotes e levitas, para fazerem subir a arca do SENHOR, Deus de Israel.

[[v13-15-15]]

^<<v13-15-15,15>>^ Os filhos dos levitas trouxeram a arca de Deus aos ombros pelas varas que nela estavam, como Moisés tinha ordenado, segundo a palavra do SENHOR.

[[v13-15-16]]

^<<v13-15-16,16>>^ Disse Davi aos chefes dos levitas que constituíssem a seus irmãos, os cantores, para que, com instrumentos músicos, com alaúdes, harpas e címbalos se fizessem ouvir e levantassem a voz com alegria.

[[v13-15-17]]

^<<v13-15-17,17>>^ Designaram, pois, os levitas Hemã, filho de Joel; e dos irmãos dele, Asafe, filho de Berequias; e dos filhos de Merari, irmãos deles, Etã, filho de Cusaías.

[[v13-15-18]]

^<<v13-15-18,18>>^ E com eles a seus irmãos da segunda ordem: Zacarias, Bene, Jaaziel, Semiramote, Jeiel, Uni, Eliabe, Benaia, Maaseias, Matitias, Elifeleu e Micneias e os porteiros Obede-Edom e Jeiel.

[[v13-15-19]]

^<<v13-15-19,19>>^ Assim, os cantores Hemã, Asafe e Etã se faziam ouvir com címbalos de bronze;

[[v13-15-20]]

^<<v13-15-20,20>>^ Zacarias, Aziel, Semiramote, Jeiel, Uni, Eliabe, Maaseias e Benaia, com alaúdes, em voz de soprano;

[[v13-15-21]]

^<<v13-15-21,21>>^ Matitias, Elifeleu, Micneias, Obede-Edom, Jeiel e Azazias, com harpas, em voz de baixo, para conduzir o canto.

[[v13-15-22]]

^<<v13-15-22,22>>^ Quenanias, chefe dos levitas músicos, tinha o encargo de dirigir o canto, porque era perito nisso.

[[v13-15-23]]

^<<v13-15-23,23>>^ Berequias e Elcana eram porteiros da arca.

[[v13-15-24]]

^<<v13-15-24,24>>^ Sebanias, Josafá, Natanael, Amasai, Zacarias, Benaia e Eliézer, os sacerdotes, tocavam as trombetas perante a arca de Deus; Obede-Edom e Jeías eram porteiros da arca.

[[v13-15-25]]

^<<v13-15-25,25>>^ Foram Davi, e os anciãos de Israel, e os capitães de milhares, para fazerem subir, com alegria, a arca da Aliança do SENHOR, da casa de Obede-Edom.

[[v13-15-26]]

^<<v13-15-26,26>>^ Tendo Deus ajudado os levitas que levavam a arca da Aliança do SENHOR, ofereceram em sacrifício sete novilhos e sete carneiros.

[[v13-15-27]]

^<<v13-15-27,27>>^ Davi ia vestido de um manto de linho fino, como também todos os levitas que levavam a arca, e os cantores, e Quenanias, chefe dos que levavam a arca e dos cantores; Davi vestia também uma estola sacerdotal de linho.

[[v13-15-28]]

^<<v13-15-28,28>>^ Assim, todo o Israel fez subir com júbilo a arca da Aliança do SENHOR, ao som de clarins, de trombetas e de címbalos, fazendo ressoar alaúdes e harpas.

[[v13-15-29]]

^<<v13-15-29,29>>^ Ao entrar a arca da Aliança do SENHOR na Cidade de Davi, Mical, filha de Saul, estava olhando pela janela e, vendo ao rei Davi dançando e folgando, o desprezou no seu coração.

'''

xref:013-1-cronicas/013-1-cronicas-014.adoc#v13-14-0[&#60; Capítulo Anterior] | <<v13-15-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-016.adoc#v13-16-0[Próximo Capítulo &#62;]