include::./index.adoc[]

[[v13-20-0]]
=== 1 Crônicas, 20
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-20-1]]

^<<v13-20-1,1>>^ Decorrido um ano, no tempo em que os reis costumam sair para a guerra, Joabe levou o exército, destruiu a terra dos filhos de Amom, veio e sitiou a Rabá; porém Davi ficou em Jerusalém; e Joabe feriu a Rabá e a destruiu.

[[v13-20-2]]

^<<v13-20-2,2>>^ Tirou Davi a coroa da cabeça do seu rei e verificou que tinha o peso de um talento de ouro e que havia nela pedras preciosas; e foi posta na cabeça de Davi; e da cidade levou mui grande despojo.

[[v13-20-3]]

^<<v13-20-3,3>>^ Também levou o povo que estava nela e o fez passar à serra, e a picaretas de ferro, e a machados; assim fez Davi a todas as cidades dos filhos de Amom. Voltou Davi, com todo o povo, para Jerusalém.

[[v13-20-4]]

^<<v13-20-4,4>>^ Depois disto, houve guerra em Gezer contra os filisteus; então, Sibecai, o husatita, feriu a Sipai, que era descendente dos gigantes; e os filisteus foram subjugados.

[[v13-20-5]]

^<<v13-20-5,5>>^ Houve ainda outra guerra contra os filisteus; e Elanã, filho de Jair, feriu a Lami, irmão de Golias, o geteu, cuja lança tinha a haste como eixo de tecelão.

[[v13-20-6]]

^<<v13-20-6,6>>^ Houve ainda outra guerra em Gate; havia ali um homem de grande estatura, tinha vinte e quatro dedos, seis em cada mão e seis em cada pé; também este descendia dos gigantes.

[[v13-20-7]]

^<<v13-20-7,7>>^ Quando ele injuriava a Israel, Jônatas, filho de Simeia, irmão de Davi, o feriu.

[[v13-20-8]]

^<<v13-20-8,8>>^ Estes nasceram dos gigantes em Gate; e caíram pela mão de Davi e pela mão de seus homens.

'''

xref:013-1-cronicas/013-1-cronicas-019.adoc#v13-19-0[&#60; Capítulo Anterior] | <<v13-20-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-021.adoc#v13-21-0[Próximo Capítulo &#62;]