include::./index.adoc[]

[[v13-11-0]]
=== 1 Crônicas, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-11-1]]

^<<v13-11-1,1>>^ Então, todo o Israel se ajuntou a Davi, em Hebrom, dizendo: Somos do mesmo povo de que tu és.

[[v13-11-2]]

^<<v13-11-2,2>>^ Outrora, sendo Saul ainda rei, eras tu que fazias saídas e entradas militares com Israel; também o SENHOR, teu Deus, te disse: Tu apascentarás o meu povo de Israel, serás chefe sobre o meu povo de Israel.

[[v13-11-3]]

^<<v13-11-3,3>>^ Assim, pois, todos os anciãos de Israel vieram ter com o rei em Hebrom; e Davi fez com eles aliança em Hebrom, perante o SENHOR. Ungiram Davi rei sobre Israel, segundo a palavra do SENHOR por intermédio de Samuel.

[[v13-11-4]]

^<<v13-11-4,4>>^ Partiu Davi e todo o Israel para Jerusalém, que é Jebus, porque ali estavam os jebuseus que habitavam naquela terra.

[[v13-11-5]]

^<<v13-11-5,5>>^ Disseram os moradores de Jebus a Davi: Tu não entrarás aqui. Porém Davi tomou a fortaleza de Sião; esta é a Cidade de Davi.

[[v13-11-6]]

^<<v13-11-6,6>>^ Porque disse Davi: Qualquer que primeiro ferir os jebuseus será chefe e comandante. Então, Joabe, filho de Zeruia, subiu primeiro e foi feito chefe.

[[v13-11-7]]

^<<v13-11-7,7>>^ Assim, habitou Davi na fortaleza, pelo que se chamou a Cidade de Davi.

[[v13-11-8]]

^<<v13-11-8,8>>^ E foi edificando a cidade em redor, desde Milo, completando o circuito; e Joabe renovou o resto da cidade.

[[v13-11-9]]

^<<v13-11-9,9>>^ Ia Davi crescendo em poder cada vez mais, porque o SENHOR dos Exércitos era com ele.

[[v13-11-10]]

^<<v13-11-10,10>>^ São estes os principais valentes de Davi, que o apoiaram valorosamente no seu reino, com todo o Israel, para o fazerem rei, segundo a palavra do SENHOR, no tocante a esse povo.

[[v13-11-11]]

^<<v13-11-11,11>>^ Eis a lista dos valentes de Davi: Jasobeão, hacmonita, o principal dos trinta, o qual, brandindo a sua lança contra trezentos, de uma vez os feriu.

[[v13-11-12]]

^<<v13-11-12,12>>^ Depois dele, Eleazar, filho de Dodô, o aoíta; ele estava entre os três valentes.

[[v13-11-13]]

^<<v13-11-13,13>>^ Este se achou com Davi em Pas-Damim, quando se ajuntaram ali os filisteus à peleja, onde havia um pedaço de terra cheio de cevada; e o povo fugiu de diante dos filisteus.

[[v13-11-14]]

^<<v13-11-14,14>>^ Puseram-se no meio daquele terreno, e o defenderam, e feriram os filisteus; e o SENHOR efetuou grande livramento.

[[v13-11-15]]

^<<v13-11-15,15>>^ Três dos trinta cabeças desceram à penha, indo ter com Davi à caverna de Adulão; e o exército dos filisteus se acampara no vale dos Refains.

[[v13-11-16]]

^<<v13-11-16,16>>^ Davi estava na fortaleza, e a guarnição dos filisteus, em Belém.

[[v13-11-17]]

^<<v13-11-17,17>>^ Suspirou Davi e disse: Quem me dera beber água do poço que está junto à porta de Belém!

[[v13-11-18]]

^<<v13-11-18,18>>^ Então, aqueles três romperam pelo acampamento dos filisteus, e tiraram água do poço junto à porta de Belém, e tomaram-na, e a levaram a Davi; ele não a quis beber, mas a derramou como libação ao SENHOR.

[[v13-11-19]]

^<<v13-11-19,19>>^ E disse: Longe de mim, ó meu Deus, fazer tal coisa; beberia eu o sangue dos homens que lá foram com perigo de sua vida? Pois, com perigo de sua vida, a trouxeram. De maneira que não a quis beber. São essas as coisas que fizeram os três valentes.

[[v13-11-20]]

^<<v13-11-20,20>>^ Também Abisai, irmão de Joabe, era cabeça dos trinta, o qual, brandindo a sua lança contra trezentos, os feriu; e tinha nome entre os primeiros três.

[[v13-11-21]]

^<<v13-11-21,21>>^ Era ele mais nobre do que os trinta e era o cabeça deles; contudo, aos primeiros três não chegou.

[[v13-11-22]]

^<<v13-11-22,22>>^ Também Benaia, filho de Joiada, era homem valente de Cabzeel e grande em obras; feriu ele dois heróis de Moabe. Desceu numa cova e nela matou um leão no tempo da neve.

[[v13-11-23]]

^<<v13-11-23,23>>^ Matou também um egípcio, homem da estatura de cinco côvados; o egípcio trazia na mão uma lança como o eixo do tecelão, mas Benaia o atacou com um cajado, arrancou-lhe da mão a lança e com ela o matou.

[[v13-11-24]]

^<<v13-11-24,24>>^ Estas coisas fez Benaia, filho de Joiada, pelo que teve nome entre os primeiros três valentes.

[[v13-11-25]]

^<<v13-11-25,25>>^ Era mais nobre do que os trinta, porém aos três primeiros não chegou, e Davi o pôs sobre a sua guarda.

[[v13-11-26]]

^<<v13-11-26,26>>^ Foram os heróis dos exércitos: Asael, irmão de Joabe, Elanã, filho de Dodô, de Belém;

[[v13-11-27]]

^<<v13-11-27,27>>^ Samote, harorita; Heles, pelonita;

[[v13-11-28]]

^<<v13-11-28,28>>^ Ira, filho de Iques, tecoíta; Abiezer, anatotita;

[[v13-11-29]]

^<<v13-11-29,29>>^ Sibecai, husatita; Ilai, aoíta;

[[v13-11-30]]

^<<v13-11-30,30>>^ Maarai, netofatita; Helede, filho de Baaná, netofatita;

[[v13-11-31]]

^<<v13-11-31,31>>^ Itai, filho de Ribai, de Gibeá, dos filhos de Benjamim; Benaia, piratonita;

[[v13-11-32]]

^<<v13-11-32,32>>^ Hurai, do ribeiro de Gaás; Abiel, arbatita;

[[v13-11-33]]

^<<v13-11-33,33>>^ Azmavete, baarumita; Eliaba, saalbonita;

[[v13-11-34]]

^<<v13-11-34,34>>^ Benê-Hasém, gizonita; Jônatas, filho de Sage, hararita;

[[v13-11-35]]

^<<v13-11-35,35>>^ Aião, filho de Sacar, hararita; Elifal, filho de Ur;

[[v13-11-36]]

^<<v13-11-36,36>>^ Héfer, mequeratita; Aías, pelonita;

[[v13-11-37]]

^<<v13-11-37,37>>^ Hezro, carmelita; Naarai, filho de Ezbai;

[[v13-11-38]]

^<<v13-11-38,38>>^ Joel, irmão de Natã; Mibar, filho de Hagri;

[[v13-11-39]]

^<<v13-11-39,39>>^ Zeleque, amonita; Naarai, beerotita, o que trazia as armas de Joabe, filho de Zeruia;

[[v13-11-40]]

^<<v13-11-40,40>>^ Ira, o itrita; Garebe, itrita;

[[v13-11-41]]

^<<v13-11-41,41>>^ Urias, heteu; Zabade, filho de Alai;

[[v13-11-42]]

^<<v13-11-42,42>>^ Adina, filho de Siza, rubenita, chefe dos rubenitas, e com ele trinta;

[[v13-11-43]]

^<<v13-11-43,43>>^ Hanã, filho de Maaca; Josafá, mitenita;

[[v13-11-44]]

^<<v13-11-44,44>>^ Uzias, asteratita, Sama e Jeiel, filhos de Hotão, aroerita;

[[v13-11-45]]

^<<v13-11-45,45>>^ Jediael, filho de Sinri, e Joá, seu irmão, tizita;

[[v13-11-46]]

^<<v13-11-46,46>>^ Eliel, maavita, Jeribai e Josavias, filhos de Elnaão; Itma, moabita;

[[v13-11-47]]

^<<v13-11-47,47>>^ Eliel, Obede e Jaasiel, de Zoba.

'''

xref:013-1-cronicas/013-1-cronicas-010.adoc#v13-10-0[&#60; Capítulo Anterior] | <<v13-11-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-012.adoc#v13-12-0[Próximo Capítulo &#62;]