include::./index.adoc[]

[[v13-27-0]]
=== 1 Crônicas, 27
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-27-1]]

^<<v13-27-1,1>>^ São estes os filhos de Israel segundo o seu número, os chefes das famílias e os capitães de milhares e de centenas com os seus oficiais, que serviam ao rei em todos os negócios dos turnos que entravam e saíam de mês em mês durante o ano, cada turno de vinte e quatro mil.

[[v13-27-2]]

^<<v13-27-2,2>>^ Sobre o primeiro turno do primeiro mês estava Jasobeão, filho de Zabdiel; em seu turno havia vinte e quatro mil.

[[v13-27-3]]

^<<v13-27-3,3>>^ Era este dos filhos de Perez, chefe de todos os capitães dos exércitos para o primeiro mês.

[[v13-27-4]]

^<<v13-27-4,4>>^ Sobre o turno do segundo mês estava Dodai, o aoíta, a cujo lado estava Miclote; também em seu turno havia vinte e quatro mil.

[[v13-27-5]]

^<<v13-27-5,5>>^ O terceiro capitão do exército e o designado para o terceiro mês era Benaia, chefe, filho do sacerdote Joiada; também em seu turno havia vinte e quatro mil.

[[v13-27-6]]

^<<v13-27-6,6>>^ Era este Benaia homem poderoso entre os trinta e cabeça deles; o seu turno estava ao encargo do seu filho Amizabade.

[[v13-27-7]]

^<<v13-27-7,7>>^ O quarto, para o quarto mês, Asael, irmão de Joabe, e depois dele Zebadias, seu filho; também em seu turno havia vinte e quatro mil.

[[v13-27-8]]

^<<v13-27-8,8>>^ O quinto capitão, para o quinto mês, Samute, o izraíta; também em seu turno havia vinte e quatro mil.

[[v13-27-9]]

^<<v13-27-9,9>>^ O sexto, para o sexto mês, Ira, filho de Iques, o tecoíta; também em seu turno havia vinte e quatro mil.

[[v13-27-10]]

^<<v13-27-10,10>>^ O sétimo, para o sétimo mês, Heles, o pelonita, dos filhos de Efraim; também em seu turno havia vinte e quatro mil.

[[v13-27-11]]

^<<v13-27-11,11>>^ O oitavo, para o oitavo mês, Sibecai, o husatita, dos zeraítas; também em seu turno havia vinte e quatro mil.

[[v13-27-12]]

^<<v13-27-12,12>>^ O nono, para o nono mês, Abiezer, o anatotita, dos benjamitas; também em seu turno havia vinte e quatro mil.

[[v13-27-13]]

^<<v13-27-13,13>>^ O décimo, para o décimo mês, Maarai, o netofatita, dos zeraítas; também em seu turno havia vinte e quatro mil.

[[v13-27-14]]

^<<v13-27-14,14>>^ O undécimo, para o undécimo mês, Benaia, o piratonita, dos filhos de Efraim; também em seu turno havia vinte e quatro mil.

[[v13-27-15]]

^<<v13-27-15,15>>^ O duodécimo, para o duodécimo mês, Heldai, o netofatita, de Otniel; também em seu turno havia vinte e quatro mil.

[[v13-27-16]]

^<<v13-27-16,16>>^ Sobre as tribos de Israel eram estes: sobre os rubenitas era chefe Eliézer, filho de Zicri; sobre os simeonitas, Sefatias, filho de Maaca;

[[v13-27-17]]

^<<v13-27-17,17>>^ sobre os levitas, Hasabias, filho de Quemuel; sobre os aronitas, Zadoque;

[[v13-27-18]]

^<<v13-27-18,18>>^ sobre Judá, Eliú, dos irmãos de Davi; sobre Issacar, Onri, filho de Micael;

[[v13-27-19]]

^<<v13-27-19,19>>^ sobre Zebulom, Ismaías, filho de Obadias; sobre Naftali, Jerimote, filho de Azriel;

[[v13-27-20]]

^<<v13-27-20,20>>^ sobre os filhos de Efraim, Oseias, filho de Azazias; sobre a meia tribo de Manassés, Joel, filho de Pedaías;

[[v13-27-21]]

^<<v13-27-21,21>>^ sobre a outra meia tribo de Manassés em Gileade, Ido, filho de Zacarias; sobre Benjamim, Jaasiel, filho de Abner;

[[v13-27-22]]

^<<v13-27-22,22>>^ sobre Dã, Azarel, filho de Jeroão; estes eram os chefes das tribos de Israel.

[[v13-27-23]]

^<<v13-27-23,23>>^ Davi não contou os que eram de vinte anos para baixo, porque o SENHOR tinha dito que multiplicaria a Israel como as estrelas do céu.

[[v13-27-24]]

^<<v13-27-24,24>>^ Joabe, filho de Zeruia, tinha começado a contar o povo, porém não acabou, porquanto viera por isso grande ira sobre Israel; pelo que o número não se registrou na história do rei Davi.

[[v13-27-25]]

^<<v13-27-25,25>>^ Azmavete, filho de Adiel, estava sobre os tesouros do rei; sobre o que este possuía nos campos, nas cidades, nas aldeias e nos castelos, Jônatas, filho de Uzias.

[[v13-27-26]]

^<<v13-27-26,26>>^ Sobre os lavradores do campo, que cultivavam a terra, Ezri, filho de Quelube.

[[v13-27-27]]

^<<v13-27-27,27>>^ Sobre as vinhas, Simei, o ramatita; porém sobre o que das vides entrava para as adegas, Zabdi, o sifmita.

[[v13-27-28]]

^<<v13-27-28,28>>^ Sobre os olivais e sicômoros que havia nas campinas, Baal-Hanã, o gederita; porém Joás, sobre os depósitos do azeite.

[[v13-27-29]]

^<<v13-27-29,29>>^ Sobre os gados que pasciam em Sarom, Sitrai, o saronita; porém sobre os gados dos vales, Safate, filho de Adlai.

[[v13-27-30]]

^<<v13-27-30,30>>^ Sobre os camelos, Obil, o ismaelita; sobre as jumentas, Jedias, o meronotita.

[[v13-27-31]]

^<<v13-27-31,31>>^ Sobre o gado miúdo, Jaziz, o hagareno; todos estes eram administradores da fazenda do rei Davi.

[[v13-27-32]]

^<<v13-27-32,32>>^ Jônatas, tio de Davi, era do conselho, homem sábio e escriba; Jeiel, filho de Hacmoni, atendia os filhos do rei.

[[v13-27-33]]

^<<v13-27-33,33>>^ Aitofel era do conselho do rei; Husai, o arquita, amigo do rei.

[[v13-27-34]]

^<<v13-27-34,34>>^ A Aitofel sucederam Joiada, filho de Benaia, e Abiatar; Joabe era comandante do exército do rei.

'''

xref:013-1-cronicas/013-1-cronicas-026.adoc#v13-26-0[&#60; Capítulo Anterior] | <<v13-27-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-028.adoc#v13-28-0[Próximo Capítulo &#62;]