include::./index.adoc[]

[[v13-1-0]]
=== 1 Crônicas, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-1-1]]

^<<v13-1-1,1>>^ Adão, Sete, Enos,

[[v13-1-2]]

^<<v13-1-2,2>>^ Cainã, Maalalel, Jarede,

[[v13-1-3]]

^<<v13-1-3,3>>^ Enoque, Metusalém, Lameque,

[[v13-1-4]]

^<<v13-1-4,4>>^ Noé, Sem, Cam e Jafé.

[[v13-1-5]]

^<<v13-1-5,5>>^ Os filhos de Jafé foram: Gomer, Magogue, Madai, Javã, Tubal, Meseque e Tiras.

[[v13-1-6]]

^<<v13-1-6,6>>^ Os filhos de Gomer: Asquenaz, Rifate e Togarma.

[[v13-1-7]]

^<<v13-1-7,7>>^ Os filhos de Javã: Elisá, Társis, Quitim e Rodanim.

[[v13-1-8]]

^<<v13-1-8,8>>^ Os filhos de Cam: Cuxe, Mizraim, Pute e Canaã.

[[v13-1-9]]

^<<v13-1-9,9>>^ Os filhos de Cuxe: Sebá, Havilá, Sabtá, Raamá e Sabtecá; os filhos de Raamá: Sabá e Dedã.

[[v13-1-10]]

^<<v13-1-10,10>>^ Cuxe gerou a Ninrode, que começou a ser poderoso na terra.

[[v13-1-11]]

^<<v13-1-11,11>>^ Mizraim gerou a Ludim, a Anamim, a Leabim, a Naftuim,

[[v13-1-12]]

^<<v13-1-12,12>>^ a Patrusim, a Casluim (de quem descendem os filisteus) e a Caftorim.

[[v13-1-13]]

^<<v13-1-13,13>>^ Canaã gerou a Sidom, seu primogênito, a Hete,

[[v13-1-14]]

^<<v13-1-14,14>>^ aos jebuseus, aos amorreus, aos girgaseus,

[[v13-1-15]]

^<<v13-1-15,15>>^ aos heveus, aos arqueus, aos sineus,

[[v13-1-16]]

^<<v13-1-16,16>>^ aos arvadeus, aos zemareus e aos hamateus.

[[v13-1-17]]

^<<v13-1-17,17>>^ Os filhos de Sem: Elão, Assur, Arfaxade, Lude, Arã, Uz, Hul, Geter e Meseque.

[[v13-1-18]]

^<<v13-1-18,18>>^ Arfaxade gerou a Selá, e Selá gerou a Héber.

[[v13-1-19]]

^<<v13-1-19,19>>^ A Héber nasceram dois filhos: o nome de um foi Pelegue, porquanto, nos seus dias, se repartiu a terra; e o nome de seu irmão era Joctã.

[[v13-1-20]]

^<<v13-1-20,20>>^ Joctã gerou a Almodá, a Salefe, a Hazar-Mavé, a Jerá,

[[v13-1-21]]

^<<v13-1-21,21>>^ a Hadorão, a Uzal, a Dicla,

[[v13-1-22]]

^<<v13-1-22,22>>^ a Ebal, a Abimael, a Sabá,

[[v13-1-23]]

^<<v13-1-23,23>>^ a Ofir, a Havilá e a Jobabe; todos estes eram filhos de Joctã.

[[v13-1-24]]

^<<v13-1-24,24>>^ Sem, Arfaxade, Selá,

[[v13-1-25]]

^<<v13-1-25,25>>^ Héber, Pelegue, Reú,

[[v13-1-26]]

^<<v13-1-26,26>>^ Serugue, Naor, Tera

[[v13-1-27]]

^<<v13-1-27,27>>^ e Abrão, que é Abraão.

[[v13-1-28]]

^<<v13-1-28,28>>^ Os filhos de Abraão: Isaque e Ismael.

[[v13-1-29]]

^<<v13-1-29,29>>^ São estas as suas gerações: o primogênito de Ismael foi Nebaiote, depois Quedar, Adbeel, Mibsão,

[[v13-1-30]]

^<<v13-1-30,30>>^ Misma, Dumá, Massá, Hadade, Temá,

[[v13-1-31]]

^<<v13-1-31,31>>^ Jetur, Nafis e Quedemá; estes foram os filhos de Ismael.

[[v13-1-32]]

^<<v13-1-32,32>>^ Quanto aos filhos de Quetura, concubina de Abraão, esta deu à luz a Zinrã, a Jocsã, a Medã, a Midiã, a Isbaque e a Sua. Os filhos de Jocsã: Sabá e Dedã.

[[v13-1-33]]

^<<v13-1-33,33>>^ Os filhos de Midiã: Efa, Éfer, Enoque, Abida e Elda; todos estes foram filhos de Quetura.

[[v13-1-34]]

^<<v13-1-34,34>>^ Abraão, pois, gerou a Isaque. Os filhos de Isaque: Esaú e Israel.

[[v13-1-35]]

^<<v13-1-35,35>>^ Os filhos de Esaú: Elifaz, Reuel, Jeús, Jalão e Coré.

[[v13-1-36]]

^<<v13-1-36,36>>^ Os filhos de Elifaz: Temã, Omar, Zefi, Gaetã, Quenaz, Timna e Amaleque.

[[v13-1-37]]

^<<v13-1-37,37>>^ Os filhos de Reuel: Naate, Zerá, Samá e Mizá.

[[v13-1-38]]

^<<v13-1-38,38>>^ Os filhos de Seir: Lotã, Sobal, Zibeão, Aná, Diso, Eser e Disã.

[[v13-1-39]]

^<<v13-1-39,39>>^ Os filhos de Lotã: Hori e Homã; e a irmã de Lotã foi Timna.

[[v13-1-40]]

^<<v13-1-40,40>>^ Os filhos de Sobal eram Aliã, Manaate, Ebal, Sefô e Onã. Os filhos de Zibeão: Aías e Aná.

[[v13-1-41]]

^<<v13-1-41,41>>^ O filho de Aná: Disom. Os filhos de Disom: Hanrão, Esbã, Itrã e Querã.

[[v13-1-42]]

^<<v13-1-42,42>>^ Os filhos de Eser: Bilã, Zaavã e Jaacã. Os filhos de Disã: Uz e Arã.

[[v13-1-43]]

^<<v13-1-43,43>>^ São estes os reis que reinaram na terra de Edom, antes que houvesse rei sobre os filhos de Israel: Bela, filho de Beor, e o nome da sua cidade era Dinabá.

[[v13-1-44]]

^<<v13-1-44,44>>^ Morreu Bela, e em seu lugar reinou Jobabe, filho de Zera, de Bozra.

[[v13-1-45]]

^<<v13-1-45,45>>^ Morreu Jobabe, e em seu lugar reinou Husão, da terra dos temanitas.

[[v13-1-46]]

^<<v13-1-46,46>>^ Morreu Husão, e em seu lugar reinou Hadade, filho de Bedade; este feriu a Midiã no campo de Moabe; o nome da sua cidade era Avite.

[[v13-1-47]]

^<<v13-1-47,47>>^ Morreu Hadade, e em seu lugar reinou Samlá, de Masreca.

[[v13-1-48]]

^<<v13-1-48,48>>^ Morreu Samlá, e em seu lugar reinou Saul, de Reobote, junto ao Eufrates.

[[v13-1-49]]

^<<v13-1-49,49>>^ Morreu Saul, e em seu lugar reinou Baal-Hanã, filho de Acbor.

[[v13-1-50]]

^<<v13-1-50,50>>^ Morreu Baal-Hanã, e em seu lugar reinou Hadade; o nome da sua cidade era Paú, e o de sua mulher era Meetabel, filha de Matrede, filha de Me-Zaabe.

[[v13-1-51]]

^<<v13-1-51,51>>^ Morreu Hadade. São estes os nomes dos príncipes de Edom: o príncipe Timna, o príncipe Alva, o príncipe Jetete,

[[v13-1-52]]

^<<v13-1-52,52>>^ o príncipe Oolibama, o príncipe Elá, o príncipe Pinom,

[[v13-1-53]]

^<<v13-1-53,53>>^ o príncipe Quenaz, o príncipe Temã, o príncipe Mibzar,

[[v13-1-54]]

^<<v13-1-54,54>>^ o príncipe Magdiel, o príncipe Irão; são estes os príncipes de Edom.

'''

xref:012-2-reis/012-2-reis-025.adoc#v12-25-0[&#60; Capítulo Anterior] | <<v13-1-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-002.adoc#v13-2-0[Próximo Capítulo &#62;]