include::./index.adoc[]

[[v13-17-0]]
=== 1 Crônicas, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-17-1]]

^<<v13-17-1,1>>^ Sucedeu que, habitando Davi em sua própria casa, disse ao profeta Natã: Eis que moro em casa de cedros, mas a arca da Aliança do SENHOR se acha numa tenda.

[[v13-17-2]]

^<<v13-17-2,2>>^ Então, Natã disse a Davi: Faze tudo quanto está no teu coração, porque Deus é contigo.

[[v13-17-3]]

^<<v13-17-3,3>>^ Porém, naquela mesma noite, veio a palavra do SENHOR a Natã, dizendo:

[[v13-17-4]]

^<<v13-17-4,4>>^ Vai e dize a meu servo Davi: Assim diz o SENHOR: Tu não edificarás casa para minha habitação;

[[v13-17-5]]

^<<v13-17-5,5>>^ porque em casa nenhuma habitei, desde o dia que fiz subir a Israel até ao dia de hoje; mas tenho andado de tenda em tenda, de tabernáculo em tabernáculo.

[[v13-17-6]]

^<<v13-17-6,6>>^ Em todo lugar em que andei com todo o Israel, falei, acaso, alguma palavra com algum dos seus juízes, a quem mandei apascentar o meu povo, dizendo: Por que não me edificais uma casa de cedro?

[[v13-17-7]]

^<<v13-17-7,7>>^ Agora, pois, assim dirás ao meu servo Davi: Assim diz o SENHOR dos Exércitos: Tomei-te da malhada e de detrás das ovelhas, para que fosses príncipe sobre o meu povo de Israel.

[[v13-17-8]]

^<<v13-17-8,8>>^ E fui contigo, por onde quer que andaste, eliminei os teus inimigos de diante de ti e fiz grande o teu nome, como só os grandes têm na terra.

[[v13-17-9]]

^<<v13-17-9,9>>^ Prepararei lugar para o meu povo de Israel e o plantarei para que habite no seu lugar e não mais seja perturbado; e jamais os filhos da perversidade o oprimam, como dantes,

[[v13-17-10]]

^<<v13-17-10,10>>^ desde o dia em que mandei houvesse juízes sobre o meu povo de Israel; porém abati todos os teus inimigos e também te fiz saber que o SENHOR te edificaria uma casa.

[[v13-17-11]]

^<<v13-17-11,11>>^ Há de ser que, quando teus dias se cumprirem, e tiveres de ir para junto de teus pais, então, farei levantar depois de ti o teu descendente, que será dos teus filhos, e estabelecerei o seu reino.

[[v13-17-12]]

^<<v13-17-12,12>>^ Esse me edificará casa; e eu estabelecerei o seu trono para sempre.

[[v13-17-13]]

^<<v13-17-13,13>>^ Eu lhe serei por pai, e ele me será por filho; a minha misericórdia não apartarei dele, como a retirei daquele que foi antes de ti.

[[v13-17-14]]

^<<v13-17-14,14>>^ Mas o confirmarei na minha casa e no meu reino para sempre, e o seu trono será estabelecido para sempre.

[[v13-17-15]]

^<<v13-17-15,15>>^ Segundo todas estas palavras e conforme toda esta visão, assim falou Natã a Davi.

[[v13-17-16]]

^<<v13-17-16,16>>^ Então, entrou o rei Davi na Casa do SENHOR, ficou perante ele e disse: Quem sou eu, SENHOR Deus, e qual é a minha casa, para que me tenhas trazido até aqui?

[[v13-17-17]]

^<<v13-17-17,17>>^ Foi isso ainda pouco aos teus olhos, ó Deus, de maneira que também falaste a respeito da casa de teu servo para tempos distantes; e me trataste como se eu fosse homem ilustre, ó SENHOR Deus.

[[v13-17-18]]

^<<v13-17-18,18>>^ Que mais ainda te poderá dizer Davi acerca das honras feitas a teu servo? Pois tu conheces bem teu servo.

[[v13-17-19]]

^<<v13-17-19,19>>^ Ó SENHOR, por amor de teu servo e segundo o teu coração, fizeste toda esta grandeza, para tornar notórias todas estas grandes coisas!

[[v13-17-20]]

^<<v13-17-20,20>>^ SENHOR, ninguém há semelhante a ti, e não há outro Deus além de ti, segundo tudo o que nós mesmos temos ouvido.

[[v13-17-21]]

^<<v13-17-21,21>>^ Quem há como o teu povo de Israel, gente única na terra, a quem tu, ó Deus, foste resgatar para ser teu povo e fazer a ti mesmo um nome, com estas grandes e tremendas coisas, desterrando as nações de diante do teu povo, que remiste do Egito?

[[v13-17-22]]

^<<v13-17-22,22>>^ Estabeleceste a teu povo de Israel por teu povo, para sempre, e tu, ó SENHOR, te fizeste o seu Deus.

[[v13-17-23]]

^<<v13-17-23,23>>^ Agora, pois, ó SENHOR, a palavra que disseste acerca de teu servo e acerca da sua casa, seja estabelecida para sempre; e faze como falaste.

[[v13-17-24]]

^<<v13-17-24,24>>^ Estabeleça-se, e seja para sempre engrandecido o teu nome, e diga-se: O SENHOR dos Exércitos é o Deus de Israel, é Deus para Israel; e a casa de Davi, teu servo, será estabelecida diante de ti.

[[v13-17-25]]

^<<v13-17-25,25>>^ Pois tu, Deus meu, fizeste ao teu servo a revelação de que lhe edificarias casa. Por isso, o teu servo se animou para fazer-te esta oração.

[[v13-17-26]]

^<<v13-17-26,26>>^ Agora, pois, ó SENHOR, tu mesmo és Deus e prometeste a teu servo este bem.

[[v13-17-27]]

^<<v13-17-27,27>>^ Sê, pois, agora, servido de abençoar a casa de teu servo, a fim de permanecer para sempre diante de ti, pois tu, ó SENHOR, a abençoaste, e abençoada será para sempre.

'''

xref:013-1-cronicas/013-1-cronicas-016.adoc#v13-16-0[&#60; Capítulo Anterior] | <<v13-17-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-018.adoc#v13-18-0[Próximo Capítulo &#62;]