include::./index.adoc[]

[[v13-23-0]]
=== 1 Crônicas, 23
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-23-1]]

^<<v13-23-1,1>>^ Sendo, pois, Davi já velho e farto de dias, constituiu a seu filho Salomão rei sobre Israel.

[[v13-23-2]]

^<<v13-23-2,2>>^ Ajuntou todos os príncipes de Israel, como também os sacerdotes e levitas.

[[v13-23-3]]

^<<v13-23-3,3>>^ Foram contados os levitas de trinta anos para cima; seu número, contados um por um, foi de trinta e oito mil homens.

[[v13-23-4]]

^<<v13-23-4,4>>^ Destes, havia vinte e quatro mil para superintenderem a obra da Casa do SENHOR, seis mil oficiais e juízes,

[[v13-23-5]]

^<<v13-23-5,5>>^ quatro mil porteiros e quatro mil para louvarem o SENHOR com os instrumentos que Davi fez para esse mister.

[[v13-23-6]]

^<<v13-23-6,6>>^ Davi os repartiu por turnos, segundo os filhos de Levi: Gérson, Coate e Merari.

[[v13-23-7]]

^<<v13-23-7,7>>^ Filhos de Gérson: Ladã e Simei.

[[v13-23-8]]

^<<v13-23-8,8>>^ Filhos de Ladã: Jeiel, o chefe, Zetã e Joel, três.

[[v13-23-9]]

^<<v13-23-9,9>>^ Filhos de Simei: Selomite, Haziel e Harã, três; estes foram os chefes das famílias de Ladã.

[[v13-23-10]]

^<<v13-23-10,10>>^ Filhos de Simei: Jaate, Ziza, Jeús e Berias; estes foram os filhos de Simei, quatro.

[[v13-23-11]]

^<<v13-23-11,11>>^ Jaate era o chefe, Ziza, o segundo; mas Jeús e Berias não tiveram muitos filhos; pelo que estes dois foram contados por uma só família.

[[v13-23-12]]

^<<v13-23-12,12>>^ Filhos de Coate: Anrão, Isar, Hebrom e Uziel, quatro.

[[v13-23-13]]

^<<v13-23-13,13>>^ Filhos de Anrão: Arão e Moisés; Arão foi separado para servir no Santo dos Santos, ele e seus filhos, perpetuamente, e para queimar incenso diante do SENHOR, para o servir e para dar a bênção em seu nome, eternamente.

[[v13-23-14]]

^<<v13-23-14,14>>^ Quanto a Moisés, homem de Deus, seus filhos foram contados entre a tribo de Levi.

[[v13-23-15]]

^<<v13-23-15,15>>^ Os filhos de Moisés: Gérson e Eliézer.

[[v13-23-16]]

^<<v13-23-16,16>>^ Filho de Gérson: Sebuel, o chefe.

[[v13-23-17]]

^<<v13-23-17,17>>^ Filho de Eliézer: Reabias, o chefe; e não teve outros; porém os filhos de Reabias se multiplicaram grandemente.

[[v13-23-18]]

^<<v13-23-18,18>>^ Filhos de Isar: Selomite, o chefe.

[[v13-23-19]]

^<<v13-23-19,19>>^ Filhos de Hebrom: Jerias, o chefe, Amarias, o segundo, Jaaziel, o terceiro, e Jecameão, o quarto.

[[v13-23-20]]

^<<v13-23-20,20>>^ Filhos de Uziel: Mica, o chefe, e Issias, o segundo.

[[v13-23-21]]

^<<v13-23-21,21>>^ Filhos de Merari: Mali e Musi; filhos de Mali: Eleazar e Quis.

[[v13-23-22]]

^<<v13-23-22,22>>^ Morreu Eleazar e não teve filhos, porém filhas; e os filhos de Quis, seus irmãos, as desposaram.

[[v13-23-23]]

^<<v13-23-23,23>>^ Os filhos de Musi: Mali, Éder e Jerimote, três.

[[v13-23-24]]

^<<v13-23-24,24>>^ São estes os filhos de Levi, segundo as suas famílias e chefes delas, segundo foram contados nominalmente, um por um, encarregados do ministério da Casa do SENHOR, de vinte anos para cima.

[[v13-23-25]]

^<<v13-23-25,25>>^ Porque disse Davi: O SENHOR, Deus de Israel, deu paz ao seu povo e habitará em Jerusalém para sempre.

[[v13-23-26]]

^<<v13-23-26,26>>^ Assim, os levitas já não precisarão levar o tabernáculo e nenhum dos utensílios para o seu ministério.

[[v13-23-27]]

^<<v13-23-27,27>>^ Porque, segundo as últimas palavras de Davi, foram contados os filhos de Levi de vinte anos para cima.

[[v13-23-28]]

^<<v13-23-28,28>>^ O cargo deles era assistir os filhos de Arão no ministério da Casa do SENHOR, nos átrios e nas câmaras, na purificação de todas as coisas sagradas e na obra do ministério da Casa de Deus,

[[v13-23-29]]

^<<v13-23-29,29>>^ a saber, os pães da proposição, a flor de farinha para a oferta de manjares, os coscorões asmos, as assadeiras, o tostado e toda sorte de peso e medida.

[[v13-23-30]]

^<<v13-23-30,30>>^ Deviam estar presentes todas as manhãs para renderem graças ao SENHOR e o louvarem; e da mesma sorte, à tarde;

[[v13-23-31]]

^<<v13-23-31,31>>^ e para cada oferecimento dos holocaustos do SENHOR, nos sábados, nas Festas da Lua Nova e nas festas fixas, perante o SENHOR, segundo o número determinado;

[[v13-23-32]]

^<<v13-23-32,32>>^ e para que tivessem a seu cargo a tenda da congregação e o santuário e atendessem aos filhos de Arão, seus irmãos, no ministério da Casa do SENHOR.

'''

xref:013-1-cronicas/013-1-cronicas-022.adoc#v13-22-0[&#60; Capítulo Anterior] | <<v13-23-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-024.adoc#v13-24-0[Próximo Capítulo &#62;]