include::./index.adoc[]

[[v13-12-0]]
=== 1 Crônicas, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-12-1]]

^<<v13-12-1,1>>^ São estes os que vieram a Davi, a Ziclague, quando fugitivo de Saul, filho de Quis; e eram dos valentes que o ajudavam na guerra.

[[v13-12-2]]

^<<v13-12-2,2>>^ Tinham por arma o arco e usavam tanto da mão direita como da esquerda em arremessar pedras com fundas e em atirar flechas com o arco. Eram dos irmãos de Saul, da tribo de Benjamim:

[[v13-12-3]]

^<<v13-12-3,3>>^ Aiezer, o chefe, e Joás, filhos de Semaá, o gibeatita; Jeziel e Pelete, filhos de Azmavete; Beraca e Jeú, o anatotita;

[[v13-12-4]]

^<<v13-12-4,4>>^ Ismaías, o gibeonita, valente entre os trinta e cabeça deles; Jeremias, Jaaziel, Joanã e Jozabade, o gederatita;

[[v13-12-5]]

^<<v13-12-5,5>>^ Eluzai, Jerimote, Bealias, Semarias e Sefatias, o harufita;

[[v13-12-6]]

^<<v13-12-6,6>>^ Elcana, Issias, Azarel, Joezer e Jasobeão, os coreítas;

[[v13-12-7]]

^<<v13-12-7,7>>^ Joela, Zebadias, filhos de Jeroão, de Gedor.

[[v13-12-8]]

^<<v13-12-8,8>>^ Dos gaditas passaram-se para Davi à fortaleza no deserto, homens valentes, homens de guerra para pelejar, armados de escudo e lança; seu rosto era como de leões, e eram eles ligeiros como gazelas sobre os montes:

[[v13-12-9]]

^<<v13-12-9,9>>^ Ézer, o cabeça, Obadias, o segundo, Eliabe, o terceiro,

[[v13-12-10]]

^<<v13-12-10,10>>^ Mismana, o quarto, Jeremias, o quinto,

[[v13-12-11]]

^<<v13-12-11,11>>^ Atai, o sexto, Eliel, o sétimo,

[[v13-12-12]]

^<<v13-12-12,12>>^ Joanã, o oitavo, Elzabade, o nono,

[[v13-12-13]]

^<<v13-12-13,13>>^ Jeremias, o décimo, Macbanai, o undécimo;

[[v13-12-14]]

^<<v13-12-14,14>>^ estes, dos filhos de Gade, foram capitães do exército; o menor valia por cem homens, e o maior, por mil.

[[v13-12-15]]

^<<v13-12-15,15>>^ São estes os que passaram o Jordão no primeiro mês, quando ele transbordava por todas as suas ribanceiras, e puseram em fuga a todos os que habitavam nos vales, tanto no oriente como no ocidente.

[[v13-12-16]]

^<<v13-12-16,16>>^ Também vieram alguns dos filhos de Benjamim e de Judá a Davi, à fortaleza.

[[v13-12-17]]

^<<v13-12-17,17>>^ Davi lhes saiu ao encontro e lhes falou, dizendo: Se vós vindes a mim pacificamente e para me ajudar, o meu coração se unirá convosco; porém, se é para me entregardes aos meus adversários, não havendo maldade em mim, o Deus de nossos pais o veja e o repreenda.

[[v13-12-18]]

^<<v13-12-18,18>>^ Então, entrou o Espírito em Amasai, cabeça de trinta, e disse: Nós somos teus, ó Davi, e contigo estamos, ó filho de Jessé! Paz, paz seja contigo! E paz com os que te ajudam! Porque o teu Deus te ajuda. Davi os recebeu e os fez capitães de tropas.

[[v13-12-19]]

^<<v13-12-19,19>>^ Também de Manassés alguns se passaram para Davi, quando veio com os filisteus para a batalha contra Saul, mas não ajudou os filisteus, porque os príncipes destes, depois de se aconselharem, o despediram; pois diziam: À custa de nossa cabeça, passará a Saul, seu senhor.

[[v13-12-20]]

^<<v13-12-20,20>>^ Voltando ele, pois, a Ziclague, passaram-se para ele, de Manassés, Adna, Jozabade, Jediael, Micael, Jozabade, Eliú e Ziletai, chefes de milhares dos de Manassés.

[[v13-12-21]]

^<<v13-12-21,21>>^ Estes ajudaram Davi contra aquela tropa, porque todos eles eram homens valentes e capitães no exército.

[[v13-12-22]]

^<<v13-12-22,22>>^ Porque, naquele tempo, dia após dia, vinham a Davi para o ajudar, até que se fez um grande exército, como exército de Deus.

[[v13-12-23]]

^<<v13-12-23,23>>^ Ora, este é o número dos homens armados para a peleja, que vieram a Davi, em Hebrom, para lhe transferirem o reino de Saul, segundo a palavra do SENHOR:

[[v13-12-24]]

^<<v13-12-24,24>>^ dos filhos de Judá, que traziam escudo e lança, seis mil e oitocentos, armados para a peleja;

[[v13-12-25]]

^<<v13-12-25,25>>^ dos filhos de Simeão, homens valentes para a peleja, sete mil e cem;

[[v13-12-26]]

^<<v13-12-26,26>>^ dos filhos de Levi, quatro mil e seiscentos;

[[v13-12-27]]

^<<v13-12-27,27>>^ Joiada era o chefe da casa de Arão, e com ele vieram três mil e setecentos;

[[v13-12-28]]

^<<v13-12-28,28>>^ Zadoque, sendo ainda jovem, homem valente, trouxe vinte e dois príncipes de sua casa paterna;

[[v13-12-29]]

^<<v13-12-29,29>>^ dos filhos de Benjamim, irmãos de Saul, vieram três mil; porque até então havia ainda muitos deles que eram pela casa de Saul;

[[v13-12-30]]

^<<v13-12-30,30>>^ dos filhos de Efraim, vinte mil e oitocentos homens valentes e de renome em casa de seus pais;

[[v13-12-31]]

^<<v13-12-31,31>>^ da meia tribo de Manassés, dezoito mil, que foram apontados nominalmente para vir a fazer rei a Davi;

[[v13-12-32]]

^<<v13-12-32,32>>^ dos filhos de Issacar, conhecedores da época, para saberem o que Israel devia fazer, duzentos chefes e todos os seus irmãos sob suas ordens;

[[v13-12-33]]

^<<v13-12-33,33>>^ de Zebulom, dos capazes para sair à guerra, providos com todas as armas de guerra, cinquenta mil, destros para ordenar uma batalha com ânimo resoluto;

[[v13-12-34]]

^<<v13-12-34,34>>^ de Naftali, mil capitães, e, com eles, trinta e sete mil com escudo e lança;

[[v13-12-35]]

^<<v13-12-35,35>>^ dos danitas, providos para a peleja, vinte e oito mil e seiscentos;

[[v13-12-36]]

^<<v13-12-36,36>>^ de Aser, dos capazes para sair à guerra e prontos para a batalha, quarenta mil;

[[v13-12-37]]

^<<v13-12-37,37>>^ do lado dalém do Jordão, dos rubenitas e gaditas e da meia tribo de Manassés, providos de toda sorte de instrumentos de guerra, cento e vinte mil.

[[v13-12-38]]

^<<v13-12-38,38>>^ Todos estes homens de guerra, postos em ordem de batalha, vieram a Hebrom, resolvidos a fazer Davi rei sobre todo o Israel; também todo o resto de Israel era unânime no propósito de fazer a Davi rei.

[[v13-12-39]]

^<<v13-12-39,39>>^ Estiveram ali com Davi três dias, comendo e bebendo; porque seus irmãos lhes tinham feito provisões.

[[v13-12-40]]

^<<v13-12-40,40>>^ E também seus vizinhos de mais perto, até Issacar, Zebulom e Naftali, trouxeram pão sobre jumentos, sobre camelos, sobre mulos e sobre bois, provisões de farinha, e pastas de figos, e cachos de passas, e vinho, e azeite, e bois, e gado miúdo em abundância; porque havia regozijo em Israel.

'''

xref:013-1-cronicas/013-1-cronicas-011.adoc#v13-11-0[&#60; Capítulo Anterior] | <<v13-12-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-013.adoc#v13-13-0[Próximo Capítulo &#62;]