include::./index.adoc[]

[[v13-7-0]]
=== 1 Crônicas, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-7-1]]

^<<v13-7-1,1>>^ Os filhos de Issacar foram: Tola, Puá, Jasube e Sinrom; quatro ao todo.

[[v13-7-2]]

^<<v13-7-2,2>>^ Os filhos de Tola: Uzi, Refaías, Jeriel, Jamai, Ibsão e Samuel, chefes das suas famílias, descendentes de Tola; homens valentes nas suas gerações, cujo número, nos dias de Davi, foi de vinte e dois mil e setecentos.

[[v13-7-3]]

^<<v13-7-3,3>>^ O filho de Uzi: Izraías; e os filhos de Izraías: Micael, Obadias, Joel e Issias; cinco ao todo; todos eles chefes.

[[v13-7-4]]

^<<v13-7-4,4>>^ Tinham, nas suas gerações, segundo as suas famílias, em tropas de guerra, trinta e seis mil homens; pois tinham muitas mulheres e filhos.

[[v13-7-5]]

^<<v13-7-5,5>>^ Seus irmãos, em todas as famílias de Issacar, homens valentes, foram oitenta e sete mil, todos registrados pelas suas genealogias.

[[v13-7-6]]

^<<v13-7-6,6>>^ Os filhos de Benjamim: Bela, Bequer e Jediael; três ao todo.

[[v13-7-7]]

^<<v13-7-7,7>>^ Os filhos de Bela: Esbom, Uzi, Uziel, Jerimote e Iri; cinco ao todo; chefes das suas famílias, homens valentes, foram vinte e dois mil e trinta e quatro, registrados pelas suas genealogias.

[[v13-7-8]]

^<<v13-7-8,8>>^ Os filhos de Bequer: Zemira, Joás, Eliézer, Elioenai, Onri, Jerimote, Abias, Anatote e Alemete; todos filhos de Bequer.

[[v13-7-9]]

^<<v13-7-9,9>>^ O número deles, registrados pelas suas genealogias, segundo as suas gerações, chefes das suas famílias, homens valentes, vinte mil e duzentos.

[[v13-7-10]]

^<<v13-7-10,10>>^ O filho de Jediael: Bilã; os filhos de Bilã: Jeús, Benjamim, Eúde, Quenaana, Zetã, Társis e Aisaar.

[[v13-7-11]]

^<<v13-7-11,11>>^ Todos estes, filhos de Jediael, foram chefes das suas famílias, homens valentes, dezessete mil e duzentos, capazes de sair à guerra.

[[v13-7-12]]

^<<v13-7-12,12>>^ Supim e Hupim eram filhos de Ir; e Husim, filho de Aer.

[[v13-7-13]]

^<<v13-7-13,13>>^ Os filhos de Naftali: Jaziel, Guni, Jezer e Salum, filhos de Bila.

[[v13-7-14]]

^<<v13-7-14,14>>^ O filho de Manassés: Asriel, de sua concubina síria, que também deu à luz a Maquir, pai de Gileade.

[[v13-7-15]]

^<<v13-7-15,15>>^ Maquir tomou a irmã de Hupim e Supim por mulher. O nome dela era Maaca; o nome do irmão de Maquir era Zelofeade, o qual teve só filhas.

[[v13-7-16]]

^<<v13-7-16,16>>^ Maaca, mulher de Maquir, teve um filho, a quem chamou Perez; irmão deste foi Seres. Os filhos de Perez foram Ulão e Requém.

[[v13-7-17]]

^<<v13-7-17,17>>^ O filho de Ulão: Bedã. Tais foram os filhos de Gileade, filho de Maquir, filho de Manassés.

[[v13-7-18]]

^<<v13-7-18,18>>^ Sua irmã Hamolequete deu à luz a Isode, a Abiezer e a Macla.

[[v13-7-19]]

^<<v13-7-19,19>>^ Foram os filhos de Semida: Aiã, Siquém, Liqui e Anião.

[[v13-7-20]]

^<<v13-7-20,20>>^ Era filho de Efraim Sutela, de quem foi filho Berede, de quem foi filho Taate, de quem foi filho Eleada, de quem foi filho Taate,

[[v13-7-21]]

^<<v13-7-21,21>>^ de quem foi filho Zabade, de quem foi filho Sutela; e ainda Ézer e Eleade, mortos pelos homens de Gate, naturais da terra, pois eles desceram para roubar o gado destes.

[[v13-7-22]]

^<<v13-7-22,22>>^ Pelo que por muitos dias os chorou Efraim, seu pai, cujos irmãos vieram para o consolar.

[[v13-7-23]]

^<<v13-7-23,23>>^ Depois, coabitou com sua mulher, e ela concebeu e teve um filho, a quem ele chamou Berias, porque as coisas iam mal na sua casa.

[[v13-7-24]]

^<<v13-7-24,24>>^ Sua filha foi Seerá, que edificou a Bete-Horom, a de baixo e a de cima, como também a Uzém-Seerá.

[[v13-7-25]]

^<<v13-7-25,25>>^ O filho de Berias foi Refa, de quem foi filho Resefe, de quem foi filho Tela, de quem foi filho Taã,

[[v13-7-26]]

^<<v13-7-26,26>>^ de quem foi filho Ladã, de quem foi filho Amiúde, de quem foi filho Elisama,

[[v13-7-27]]

^<<v13-7-27,27>>^ de quem foi filho Num, de quem foi filho Josué.

[[v13-7-28]]

^<<v13-7-28,28>>^ A possessão e habitação deles foram: Betel e as suas aldeias; ao oriente, Naarã; e, ao ocidente, Gezer e suas aldeias, Siquém e suas aldeias, até Aia e suas aldeias;

[[v13-7-29]]

^<<v13-7-29,29>>^ do lado dos filhos de Manassés, Bete-Seã e suas aldeias, Taanaque e suas aldeias, Megido e suas aldeias, Dor e suas aldeias; nestas, habitaram os filhos de José, filho de Israel.

[[v13-7-30]]

^<<v13-7-30,30>>^ Os filhos de Aser: Imna, Isvá, Isvi e Berias e Sera, irmã deles.

[[v13-7-31]]

^<<v13-7-31,31>>^ Os filhos de Berias: Héber e Malquiel; este foi o pai de Birzavite.

[[v13-7-32]]

^<<v13-7-32,32>>^ Héber gerou a Jaflete, a Somer, a Hotão e a Suá, irmã deles.

[[v13-7-33]]

^<<v13-7-33,33>>^ Os filhos de Jaflete: Pasaque, Bimal e Asvate; estes foram os filhos de Jaflete.

[[v13-7-34]]

^<<v13-7-34,34>>^ Os filhos de Semer: Aí, Roga, Jeubá e Arã.

[[v13-7-35]]

^<<v13-7-35,35>>^ Os filhos de seu irmão Helém: Zofa, Imna, Seles e Amal.

[[v13-7-36]]

^<<v13-7-36,36>>^ Os filhos de Zofa: Sua, Harnefer, Sual, Beri, Inra,

[[v13-7-37]]

^<<v13-7-37,37>>^ Bezer, Hode, Sama, Silsa, Itrã e Beera.

[[v13-7-38]]

^<<v13-7-38,38>>^ Os filhos de Jéter: Jefoné, Pispa e Ara.

[[v13-7-39]]

^<<v13-7-39,39>>^ Os filhos de Ula: Ara, Haniel e Rizia.

[[v13-7-40]]

^<<v13-7-40,40>>^ Todos estes foram filhos de Aser, chefes das famílias, escolhidos, homens valentes, chefes de príncipes, registrados nas suas genealogias para o serviço na guerra; seu número foi de vinte e seis mil homens.

'''

xref:013-1-cronicas/013-1-cronicas-006.adoc#v13-6-0[&#60; Capítulo Anterior] | <<v13-7-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-008.adoc#v13-8-0[Próximo Capítulo &#62;]