include::./index.adoc[]

[[v13-28-0]]
=== 1 Crônicas, 28
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-28-1]]

^<<v13-28-1,1>>^ Então, Davi convocou para Jerusalém todos os príncipes de Israel, os príncipes das tribos, os capitães dos turnos que serviam o rei, os capitães de mil e os de cem, os administradores de toda a fazenda e possessões do rei e de seus filhos, como também os oficiais, os poderosos e todo homem valente.

[[v13-28-2]]

^<<v13-28-2,2>>^ Pôs-se o rei Davi em pé e disse: Ouvi-me, irmãos meus e povo meu: Era meu propósito de coração edificar uma casa de repouso para a arca da Aliança do SENHOR e para o estrado dos pés do nosso Deus, e eu tinha feito o preparo para a edificar.

[[v13-28-3]]

^<<v13-28-3,3>>^ Porém Deus me disse: Não edificarás casa ao meu nome, porque és homem de guerra e derramaste muito sangue.

[[v13-28-4]]

^<<v13-28-4,4>>^ O SENHOR, Deus de Israel, me escolheu de toda a casa de meu pai, para que eternamente fosse eu rei sobre Israel; porque a Judá escolheu por príncipe e a casa de meu pai, na casa de Judá; e entre os filhos de meu pai se agradou de mim, para me fazer rei sobre todo o Israel.

[[v13-28-5]]

^<<v13-28-5,5>>^ E, de todos os meus filhos, porque muitos filhos me deu o SENHOR, escolheu ele a Salomão para se assentar no trono do reino do SENHOR, sobre Israel.

[[v13-28-6]]

^<<v13-28-6,6>>^ E me disse: Teu filho Salomão é quem edificará a minha casa e os meus átrios, porque o escolhi para filho e eu lhe serei por pai.

[[v13-28-7]]

^<<v13-28-7,7>>^ Estabelecerei o seu reino para sempre, se perseverar ele em cumprir os meus mandamentos e os meus juízos, como até ao dia de hoje.

[[v13-28-8]]

^<<v13-28-8,8>>^ Agora, pois, perante todo o Israel, a congregação do SENHOR, e perante o nosso Deus, que me ouve, eu vos digo: guardai todos os mandamentos do SENHOR, vosso Deus, e empenhai-vos por eles, para que possuais esta boa terra e a deixeis como herança a vossos filhos, para sempre.

[[v13-28-9]]

^<<v13-28-9,9>>^ Tu, meu filho Salomão, conhece o Deus de teu pai e serve-o de coração íntegro e alma voluntária; porque o SENHOR esquadrinha todos os corações e penetra todos os desígnios do pensamento. Se o buscares, ele deixará achar-se por ti; se o deixares, ele te rejeitará para sempre.

[[v13-28-10]]

^<<v13-28-10,10>>^ Agora, pois, atende a tudo, porque o SENHOR te escolheu para edificares casa para o santuário; sê forte e faze a obra.

[[v13-28-11]]

^<<v13-28-11,11>>^ Deu Davi a Salomão, seu filho, a planta do pórtico com as suas casas, as suas tesourarias, os seus cenáculos e as suas câmaras interiores, como também da casa do propiciatório.

[[v13-28-12]]

^<<v13-28-12,12>>^ Também a planta de tudo quanto tinha em mente, com referência aos átrios da Casa do SENHOR, e a todas as câmaras em redor, para os tesouros da Casa de Deus e para os tesouros das coisas consagradas;

[[v13-28-13]]

^<<v13-28-13,13>>^ e para os turnos dos sacerdotes e dos levitas, e para toda obra do ministério da Casa do SENHOR, e para todos os utensílios para o serviço da Casa do SENHOR,

[[v13-28-14]]

^<<v13-28-14,14>>^ especificando o peso do ouro para todos os utensílios de ouro de cada serviço; também o peso da prata para todos os utensílios de prata de cada serviço;

[[v13-28-15]]

^<<v13-28-15,15>>^ o peso para os candeeiros de ouro e suas lâmpadas de ouro, para cada candeeiro e suas lâmpadas, segundo o uso de cada um;

[[v13-28-16]]

^<<v13-28-16,16>>^ também o peso do ouro para as mesas da proposição, para cada uma de per si; como também a prata para as mesas de prata;

[[v13-28-17]]

^<<v13-28-17,17>>^ ouro puro para os garfos, para as bacias e para os copos; para as taças de ouro o devido peso a cada uma, como também para as taças de prata, a cada uma o seu peso;

[[v13-28-18]]

^<<v13-28-18,18>>^ o peso do ouro refinado para o altar do incenso, como também, segundo a planta, o ouro para o carro dos querubins, que haviam de estender as asas e cobrir a arca da Aliança do SENHOR.

[[v13-28-19]]

^<<v13-28-19,19>>^ Tudo isto, disse Davi, me foi dado por escrito por mandado do SENHOR, a saber, todas as obras desta planta.

[[v13-28-20]]

^<<v13-28-20,20>>^ Disse Davi a Salomão, seu filho: Sê forte e corajoso e faze a obra; não temas, nem te desanimes, porque o SENHOR Deus, meu Deus, há de ser contigo; não te deixará, nem te desamparará, até que acabes todas as obras para o serviço da Casa do SENHOR.

[[v13-28-21]]

^<<v13-28-21,21>>^ Eis aí os turnos dos sacerdotes e dos levitas para todo serviço da Casa de Deus; também se acham contigo, para toda obra, voluntários com sabedoria de toda espécie para cada serviço; como também os príncipes e todo o povo estarão inteiramente às tuas ordens.

'''

xref:013-1-cronicas/013-1-cronicas-027.adoc#v13-27-0[&#60; Capítulo Anterior] | <<v13-28-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-029.adoc#v13-29-0[Próximo Capítulo &#62;]