include::./index.adoc[]

[[v13-10-0]]
=== 1 Crônicas, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-10-1]]

^<<v13-10-1,1>>^ Os filisteus pelejaram contra Israel; e, tendo os homens de Israel fugido de diante dos filisteus, caíram mortos no monte Gilboa.

[[v13-10-2]]

^<<v13-10-2,2>>^ Os filisteus perseguiram Saul e seus filhos e mataram Jônatas, Abinadabe e Malquisua, filhos de Saul.

[[v13-10-3]]

^<<v13-10-3,3>>^ Agravou-se muito a peleja contra Saul, os flecheiros o avistaram, e ele muito os temeu.

[[v13-10-4]]

^<<v13-10-4,4>>^ Então, disse Saul ao seu escudeiro: Arranca a tua espada e atravessa-me com ela, para que, porventura, não venham estes incircuncisos e escarneçam de mim. Porém o seu escudeiro não o quis, porque temia muito; então, Saul tomou a espada e se lançou sobre ela.

[[v13-10-5]]

^<<v13-10-5,5>>^ Vendo, pois, o seu escudeiro que Saul já era morto, também ele se lançou sobre a espada e morreu com ele.

[[v13-10-6]]

^<<v13-10-6,6>>^ Assim, morreram Saul e seus três filhos; e toda a sua casa pereceu juntamente com ele.

[[v13-10-7]]

^<<v13-10-7,7>>^ Vendo os homens de Israel que estavam no vale que os homens de Israel fugiram e que Saul e seus filhos estavam mortos, desampararam as cidades e fugiram; e vieram os filisteus e habitaram nelas.

[[v13-10-8]]

^<<v13-10-8,8>>^ Sucedeu, pois, que, vindo os filisteus ao outro dia a despojar os mortos, acharam Saul e os seus filhos caídos no monte Gilboa.

[[v13-10-9]]

^<<v13-10-9,9>>^ E os despojaram, tomaram a sua cabeça e as suas armas e enviaram mensageiros pela terra dos filisteus, em redor, a levar as boas-novas a seus ídolos e entre o povo.

[[v13-10-10]]

^<<v13-10-10,10>>^ Puseram as armas de Saul no templo de seu deus, e a sua cabeça afixaram na casa de Dagom.

[[v13-10-11]]

^<<v13-10-11,11>>^ Ouvindo, pois, toda a Jabes de Gileade tudo quanto os filisteus fizeram a Saul,

[[v13-10-12]]

^<<v13-10-12,12>>^ então, todos os homens valentes se levantaram, e tomaram o corpo de Saul e os corpos dos filhos, e os trouxeram a Jabes; e sepultaram os seus ossos debaixo de um arvoredo, em Jabes, e jejuaram sete dias.

[[v13-10-13]]

^<<v13-10-13,13>>^ Assim, morreu Saul por causa da sua transgressão cometida contra o SENHOR, por causa da palavra do SENHOR, que ele não guardara; e também porque interrogara e consultara uma necromante

[[v13-10-14]]

^<<v13-10-14,14>>^ e não ao SENHOR, que, por isso, o matou e transferiu o reino a Davi, filho de Jessé.

'''

xref:013-1-cronicas/013-1-cronicas-009.adoc#v13-9-0[&#60; Capítulo Anterior] | <<v13-10-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-011.adoc#v13-11-0[Próximo Capítulo &#62;]