include::./index.adoc[]

[[v13-16-0]]
=== 1 Crônicas, 16
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-16-1]]

^<<v13-16-1,1>>^ Introduziram, pois, a arca de Deus e a puseram no meio da tenda que lhe armara Davi; e trouxeram holocaustos e ofertas pacíficas perante Deus.

[[v13-16-2]]

^<<v13-16-2,2>>^ Tendo Davi acabado de trazer os holocaustos e ofertas pacíficas, abençoou o povo em nome do SENHOR.

[[v13-16-3]]

^<<v13-16-3,3>>^ E repartiu a todos em Israel, tanto os homens como as mulheres, a cada um, um bolo de pão, um bom pedaço de carne e passas.

[[v13-16-4]]

^<<v13-16-4,4>>^ Designou dentre os levitas os que haviam de ministrar diante da arca do SENHOR, e celebrar, e louvar, e exaltar o SENHOR, Deus de Israel, a saber,

[[v13-16-5]]

^<<v13-16-5,5>>^ Asafe, o chefe, Zacarias, o segundo, e depois Jeiel, Semiramote, Jeiel, Matitias, Eliabe, Benaia, Obede-Edom e Jeiel, com alaúdes e harpas; e Asafe fazia ressoar os címbalos.

[[v13-16-6]]

^<<v13-16-6,6>>^ Os sacerdotes Benaia e Jaaziel estavam continuamente com trombetas, perante a arca da Aliança de Deus.

[[v13-16-7]]

^<<v13-16-7,7>>^ Naquele dia, foi que Davi encarregou, pela primeira vez, a Asafe e a seus irmãos de celebrarem com hinos o SENHOR.

[[v13-16-8]]

^<<v13-16-8,8>>^ Rendei graças ao SENHOR, invocai o seu nome, fazei conhecidos, entre os povos, os seus feitos.

[[v13-16-9]]

^<<v13-16-9,9>>^ Cantai-lhe, cantai-lhe salmos; narrai todas as suas maravilhas.

[[v13-16-10]]

^<<v13-16-10,10>>^ Gloriai-vos no seu santo nome; alegre-se o coração dos que buscam o SENHOR.

[[v13-16-11]]

^<<v13-16-11,11>>^ Buscai o SENHOR e o seu poder, buscai perpetuamente a sua presença.

[[v13-16-12]]

^<<v13-16-12,12>>^ Lembrai-vos das maravilhas que fez, dos seus prodígios e dos juízos dos seus lábios,

[[v13-16-13]]

^<<v13-16-13,13>>^ vós, descendentes de Israel, seu servo, vós, filhos de Jacó, seus escolhidos.

[[v13-16-14]]

^<<v13-16-14,14>>^ Ele é o SENHOR, nosso Deus; os seus juízos permeiam toda a terra.

[[v13-16-15]]

^<<v13-16-15,15>>^ Lembra-se perpetuamente da sua aliança, da palavra que empenhou para mil gerações;

[[v13-16-16]]

^<<v13-16-16,16>>^ da aliança que fez com Abraão e do juramento que fez a Isaque;

[[v13-16-17]]

^<<v13-16-17,17>>^ o qual confirmou a Jacó por decreto e a Israel, por aliança perpétua,

[[v13-16-18]]

^<<v13-16-18,18>>^ dizendo: Dar-vos-ei a terra de Canaã como quinhão da vossa herança.

[[v13-16-19]]

^<<v13-16-19,19>>^ Então, eram eles em pequeno número, pouquíssimos e forasteiros nela;

[[v13-16-20]]

^<<v13-16-20,20>>^ andavam de nação em nação, de um reino para um povo.

[[v13-16-21]]

^<<v13-16-21,21>>^ A ninguém permitiu que os oprimisse; antes, por amor deles, repreendeu a reis,

[[v13-16-22]]

^<<v13-16-22,22>>^ dizendo: Não toqueis nos meus ungidos, nem maltrateis os meus profetas.

[[v13-16-23]]

^<<v13-16-23,23>>^ Cantai ao SENHOR, todas as terras; proclamai a sua salvação, dia após dia.

[[v13-16-24]]

^<<v13-16-24,24>>^ Anunciai entre as nações a sua glória, entre todos os povos, as suas maravilhas,

[[v13-16-25]]

^<<v13-16-25,25>>^ porque grande é o SENHOR e mui digno de ser louvado, temível mais do que todos os deuses.

[[v13-16-26]]

^<<v13-16-26,26>>^ Porque todos os deuses dos povos são ídolos; o SENHOR, porém, fez os céus.

[[v13-16-27]]

^<<v13-16-27,27>>^ Glória e majestade estão diante dele, força e formosura, no seu santuário.

[[v13-16-28]]

^<<v13-16-28,28>>^ Tributai ao SENHOR, ó famílias dos povos, tributai ao SENHOR glória e força.

[[v13-16-29]]

^<<v13-16-29,29>>^ Tributai ao SENHOR a glória devida ao seu nome; trazei oferendas e entrai nos seus átrios; adorai o SENHOR na beleza da sua santidade.

[[v13-16-30]]

^<<v13-16-30,30>>^ Tremei diante dele, todas as terras, pois ele firmou o mundo para que não se abale.

[[v13-16-31]]

^<<v13-16-31,31>>^ Alegrem-se os céus, e a terra exulte; diga-se entre as nações: Reina o SENHOR.

[[v13-16-32]]

^<<v13-16-32,32>>^ Ruja o mar e a sua plenitude; folgue o campo e tudo o que nele há.

[[v13-16-33]]

^<<v13-16-33,33>>^ Regozijem-se as árvores do bosque na presença do SENHOR, porque vem a julgar a terra.

[[v13-16-34]]

^<<v13-16-34,34>>^ Rendei graças ao SENHOR, porque ele é bom; porque a sua misericórdia dura para sempre.

[[v13-16-35]]

^<<v13-16-35,35>>^ E dizei: Salva-nos, ó Deus da nossa salvação, ajunta-nos e livra-nos das nações, para que rendamos graças ao teu santo nome e nos gloriemos no teu louvor.

[[v13-16-36]]

^<<v13-16-36,36>>^ Bendito seja o SENHOR, Deus de Israel, desde a eternidade até a eternidade. E todo o povo disse: Amém! E louvou ao SENHOR.

[[v13-16-37]]

^<<v13-16-37,37>>^ Então, Davi deixou ali diante da arca da Aliança do SENHOR a Asafe e a seus irmãos, para ministrarem continuamente perante ela, segundo se ordenara para cada dia;

[[v13-16-38]]

^<<v13-16-38,38>>^ também deixou a Obede-Edom com seus irmãos, em número de sessenta e oito; a Obede-Edom, filho de Jedutum, e a Hosa, para serem porteiros;

[[v13-16-39]]

^<<v13-16-39,39>>^ e deixou a Zadoque, o sacerdote, e aos sacerdotes, seus irmãos, diante do tabernáculo do SENHOR, num lugar alto de Gibeão,

[[v13-16-40]]

^<<v13-16-40,40>>^ para oferecerem continuamente ao SENHOR os holocaustos sobre o altar dos holocaustos, pela manhã e à tarde; e isto segundo tudo o que está escrito na Lei que o SENHOR ordenara a Israel.

[[v13-16-41]]

^<<v13-16-41,41>>^ E com eles deixou a Hemã, a Jedutum e os mais escolhidos, que foram nominalmente designados para louvarem o SENHOR, porque a sua misericórdia dura para sempre.

[[v13-16-42]]

^<<v13-16-42,42>>^ Com eles, pois, estavam Hemã e Jedutum, que faziam ressoar trombetas, e címbalos, e instrumentos de música de Deus; os filhos de Jedutum eram porteiros.

[[v13-16-43]]

^<<v13-16-43,43>>^ Então, se retirou todo o povo, cada um para sua casa; e tornou Davi, para abençoar a sua casa.

'''

xref:013-1-cronicas/013-1-cronicas-015.adoc#v13-15-0[&#60; Capítulo Anterior] | <<v13-16-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-017.adoc#v13-17-0[Próximo Capítulo &#62;]