include::./index.adoc[]

[[v13-21-0]]
=== 1 Crônicas, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-21-1]]

^<<v13-21-1,1>>^ Então, Satanás se levantou contra Israel e incitou a Davi a levantar o censo de Israel.

[[v13-21-2]]

^<<v13-21-2,2>>^ Disse Davi a Joabe e aos chefes do povo: Ide, levantai o censo de Israel, desde Berseba até Dã; e trazei-me a apuração para que eu saiba o seu número.

[[v13-21-3]]

^<<v13-21-3,3>>^ Então, disse Joabe: Multiplique o SENHOR, teu Deus, a este povo cem vezes mais; porventura, ó rei, meu senhor, não são todos servos de meu senhor? Por que requer isso o meu senhor? Por que trazer, assim, culpa sobre Israel?

[[v13-21-4]]

^<<v13-21-4,4>>^ Porém a palavra do rei prevaleceu contra Joabe; pelo que saiu Joabe e percorreu todo o Israel; então, voltou para Jerusalém.

[[v13-21-5]]

^<<v13-21-5,5>>^ Deu Joabe a Davi o recenseamento do povo; havia em Israel um milhão e cem mil homens que puxavam da espada; e em Judá eram quatrocentos e setenta mil homens que puxavam da espada.

[[v13-21-6]]

^<<v13-21-6,6>>^ Porém os de Levi e Benjamim não foram contados entre eles, porque a ordem do rei foi abominável a Joabe.

[[v13-21-7]]

^<<v13-21-7,7>>^ Tudo isto desagradou a Deus, pelo que feriu a Israel.

[[v13-21-8]]

^<<v13-21-8,8>>^ Então, disse Davi a Deus: Muito pequei em fazer tal coisa; porém, agora, peço-te que perdoes a iniquidade de teu servo, porque procedi mui loucamente.

[[v13-21-9]]

^<<v13-21-9,9>>^ Falou, pois, o SENHOR a Gade, o vidente de Davi, dizendo:

[[v13-21-10]]

^<<v13-21-10,10>>^ Vai e dize a Davi: Assim diz o SENHOR: Três coisas te ofereço; escolhe uma delas, para que ta faça.

[[v13-21-11]]

^<<v13-21-11,11>>^ Veio, pois, Gade a Davi e lhe disse: Assim diz o SENHOR: Escolhe o que queres:

[[v13-21-12]]

^<<v13-21-12,12>>^ ou três anos de fome, ou que por três meses sejas consumido diante dos teus adversários, e a espada de teus inimigos te alcance, ou que por três dias a espada do SENHOR, isto é, a peste na terra, e o Anjo do SENHOR causem destruição em todos os territórios de Israel; vê, pois, agora, que resposta hei de dar ao que me enviou.

[[v13-21-13]]

^<<v13-21-13,13>>^ Então, disse Davi a Gade: Estou em grande angústia; caia eu, pois, nas mãos do SENHOR, porque são muitíssimas as suas misericórdias, mas nas mãos dos homens não caia eu.

[[v13-21-14]]

^<<v13-21-14,14>>^ Então, enviou o SENHOR a peste a Israel; e caíram de Israel setenta mil homens.

[[v13-21-15]]

^<<v13-21-15,15>>^ Enviou Deus um anjo a Jerusalém, para a destruir; ao destruí-la, olhou o SENHOR, e se arrependeu do mal, e disse ao anjo destruidor: Basta, retira, agora, a mão. O Anjo do SENHOR estava junto à eira de Ornã, o jebuseu.

[[v13-21-16]]

^<<v13-21-16,16>>^ Levantando Davi os olhos, viu o Anjo do SENHOR, que estava entre a terra e o céu, com a espada desembainhada na mão estendida contra Jerusalém; então, Davi e os anciãos, cobertos de panos de saco, se prostraram com o rosto em terra.

[[v13-21-17]]

^<<v13-21-17,17>>^ Disse Davi a Deus: Não sou eu o que disse que se contasse o povo? Eu é que pequei, eu é que fiz muito mal; porém estas ovelhas que fizeram? Ah! SENHOR, meu Deus, seja, pois, a tua mão contra mim e contra a casa de meu pai e não para castigo do teu povo.

[[v13-21-18]]

^<<v13-21-18,18>>^ Então, o Anjo do SENHOR disse a Gade que mandasse Davi subir para levantar um altar ao SENHOR, na eira de Ornã, o jebuseu.

[[v13-21-19]]

^<<v13-21-19,19>>^ Subiu, pois, Davi, segundo a palavra de Gade, que falara em nome do SENHOR.

[[v13-21-20]]

^<<v13-21-20,20>>^ Virando-se Ornã, viu o Anjo; e esconderam-se seus quatro filhos que estavam com ele. Ora, Ornã estava debulhando trigo.

[[v13-21-21]]

^<<v13-21-21,21>>^ Quando Davi vinha chegando a Ornã, este olhou, e o viu e, saindo da eira, se inclinou diante de Davi, com o rosto em terra.

[[v13-21-22]]

^<<v13-21-22,22>>^ Disse Davi a Ornã: Dá-me este lugar da eira a fim de edificar nele um altar ao SENHOR, para que cesse a praga de sobre o povo; dá-mo pelo seu devido valor.

[[v13-21-23]]

^<<v13-21-23,23>>^ Então, disse Ornã a Davi: Tome-a o rei, meu senhor, para si e faça dela o que bem lhe parecer; eis que dou os bois para o holocausto, e os trilhos, para a lenha, e o trigo, para oferta de manjares; dou tudo.

[[v13-21-24]]

^<<v13-21-24,24>>^ Tornou o rei Davi a Ornã: Não; antes, pelo seu inteiro valor a quero comprar; porque não tomarei o que é teu para o SENHOR, nem oferecerei holocausto que não me custe nada.

[[v13-21-25]]

^<<v13-21-25,25>>^ Davi deu a Ornã por aquele lugar a soma de seiscentos siclos de ouro.

[[v13-21-26]]

^<<v13-21-26,26>>^ Edificou ali um altar ao SENHOR, ofereceu nele holocaustos e sacrifícios pacíficos e invocou o SENHOR, o qual lhe respondeu com fogo do céu sobre o altar do holocausto.

[[v13-21-27]]

^<<v13-21-27,27>>^ O SENHOR deu ordem ao Anjo, e ele meteu a sua espada na bainha.

[[v13-21-28]]

^<<v13-21-28,28>>^ Vendo Davi, naquele mesmo tempo, que o SENHOR lhe respondera na eira de Ornã, o jebuseu, sacrificou ali.

[[v13-21-29]]

^<<v13-21-29,29>>^ Porque o tabernáculo do SENHOR, que Moisés fizera no deserto, e o altar do holocausto estavam, naquele tempo, no alto de Gibeão.

[[v13-21-30]]

^<<v13-21-30,30>>^ Davi não podia ir até lá para consultar a Deus, porque estava atemorizado por causa da espada do Anjo do SENHOR.

'''

xref:013-1-cronicas/013-1-cronicas-020.adoc#v13-20-0[&#60; Capítulo Anterior] | <<v13-21-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-022.adoc#v13-22-0[Próximo Capítulo &#62;]