include::./index.adoc[]

[[v13-5-0]]
=== 1 Crônicas, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v13-5-1]]

^<<v13-5-1,1>>^ Quanto aos filhos de Rúben, o primogênito de Israel (pois era o primogênito, mas, por ter profanado o leito de seu pai, deu-se a sua primogenitura aos filhos de José, filho de Israel; de modo que, na genealogia, não foi contado como primogênito.

[[v13-5-2]]

^<<v13-5-2,2>>^ Judá, na verdade, foi poderoso entre seus irmãos, e dele veio o príncipe; porém o direito da primogenitura foi de José.),

[[v13-5-3]]

^<<v13-5-3,3>>^ foram estes: Enoque, Palu, Hezrom e Carmi.

[[v13-5-4]]

^<<v13-5-4,4>>^ O filho de Joel: Semaías, de quem foi filho Gogue, de quem foi filho Simei,

[[v13-5-5]]

^<<v13-5-5,5>>^ de quem foi filho Mica, de quem foi filho Reaías, de quem foi filho Baal,

[[v13-5-6]]

^<<v13-5-6,6>>^ de quem foi filho Beera, o qual Tiglate-Pileser, rei da Assíria, levou cativo; ele foi príncipe dos rubenitas.

[[v13-5-7]]

^<<v13-5-7,7>>^ Quanto a seus irmãos, pelas suas famílias, quando foram inscritos nas genealogias segundo as suas descendências, tinham por cabeças Jeiel, Zacarias,

[[v13-5-8]]

^<<v13-5-8,8>>^ Bela, filho de Azaz, filho de Sema, filho de Joel, que habitaram em Aroer, até Nebo e Baal-Meom;

[[v13-5-9]]

^<<v13-5-9,9>>^ também habitaram do lado oriental, até à entrada do deserto, o qual se estende até ao rio Eufrates, porque o seu gado se tinha multiplicado na terra de Gileade.

[[v13-5-10]]

^<<v13-5-10,10>>^ Nos dias de Saul, fizeram guerra aos hagarenos, que caíram pelo poder de sua mão, e habitaram nas tendas deles, em toda a terra fronteira de Gileade, do lado oriental.

[[v13-5-11]]

^<<v13-5-11,11>>^ Os filhos de Gade habitaram defronte deles, na terra de Basã, até Salca.

[[v13-5-12]]

^<<v13-5-12,12>>^ Joel foi o cabeça, e Safã, o segundo; também Janai e Safate estavam em Basã.

[[v13-5-13]]

^<<v13-5-13,13>>^ Seus irmãos, segundo as suas casas paternas, foram: Micael, Mesulão, Seba, Jorai, Jacã, Zia e Héber; ao todo, sete;

[[v13-5-14]]

^<<v13-5-14,14>>^ estes foram os filhos de Abiail, filho de Huri, filho de Jaroa, filho de Gileade, filho de Micael, filho de Jesisai, filho de Jado, filho de Buz.

[[v13-5-15]]

^<<v13-5-15,15>>^ Aí, filho de Abdiel, filho de Guni, foi o cabeça da sua família.

[[v13-5-16]]

^<<v13-5-16,16>>^ Habitaram em Gileade, em Basã e suas aldeias, bem como até aos limites de todos os arredores de Sarom.

[[v13-5-17]]

^<<v13-5-17,17>>^ Todos estes foram inscritos na genealogia, nos dias de Jotão, rei de Judá, e nos dias de Jeroboão, rei de Israel.

[[v13-5-18]]

^<<v13-5-18,18>>^ Dos filhos de Rúben, dos gaditas e da meia tribo de Manassés, homens valentes, que traziam escudo e espada, entesavam o arco e eram destros na guerra, houve quarenta e quatro mil setecentos e sessenta, capazes de sair a combate.

[[v13-5-19]]

^<<v13-5-19,19>>^ Fizeram guerra aos hagarenos, como a Jetur, a Nafis e a Nodabe.

[[v13-5-20]]

^<<v13-5-20,20>>^ Foram ajudados contra eles, e os hagarenos e todos quantos estavam com eles foram entregues nas suas mãos; porque, na peleja, clamaram a Deus, que lhes deu ouvidos, porquanto confiaram nele.

[[v13-5-21]]

^<<v13-5-21,21>>^ Levaram o gado deles: cinquenta mil camelos, duzentas e cinquenta mil ovelhas, dois mil jumentos; e cem mil pessoas.

[[v13-5-22]]

^<<v13-5-22,22>>^ Porque muitos caíram feridos à espada, pois de Deus era a peleja; e habitaram no lugar deles até ao exílio.

[[v13-5-23]]

^<<v13-5-23,23>>^ Os filhos da meia tribo de Manassés habitaram naquela terra de Basã até Baal-Hermom, e Senir, e o monte Hermom; e eram numerosos.

[[v13-5-24]]

^<<v13-5-24,24>>^ Estes foram cabeças de suas famílias, a saber: Éfer, Isi, Eliel, Azriel, Jeremias, Hodavias e Jadiel, guerreiros valentes, homens famosos, cabeças de suas famílias.

[[v13-5-25]]

^<<v13-5-25,25>>^ Porém cometeram transgressões contra o Deus de seus pais e se prostituíram, seguindo os deuses dos povos da terra, os quais Deus destruíra de diante deles.

[[v13-5-26]]

^<<v13-5-26,26>>^ Pelo que o Deus de Israel suscitou o espírito de Pul, rei da Assíria, e o espírito de Tiglate-Pileser, rei da Assíria, que os levou cativos, a saber: os rubenitas, os gaditas e a meia tribo de Manassés, e os trouxe para Hala, Habor e Hara e para o rio Gozã, onde permanecem até ao dia de hoje.

'''

xref:013-1-cronicas/013-1-cronicas-004.adoc#v13-4-0[&#60; Capítulo Anterior] | <<v13-5-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-006.adoc#v13-6-0[Próximo Capítulo &#62;]