include::./index.adoc[]

[[v59-4-0]]
=== Tiago, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v59-4-1]]

^<<v59-4-1,1>>^ De onde procedem guerras e contendas que há entre vós? De onde, senão dos prazeres que militam na vossa carne?

[[v59-4-2]]

^<<v59-4-2,2>>^ Cobiçais e nada tendes; matais, e invejais, e nada podeis obter; viveis a lutar e a fazer guerras. Nada tendes, porque não pedis;

[[v59-4-3]]

^<<v59-4-3,3>>^ pedis e não recebeis, porque pedis mal, para esbanjardes em vossos prazeres.

[[v59-4-4]]

^<<v59-4-4,4>>^ Infiéis, não compreendeis que a amizade do mundo é inimiga de Deus? Aquele, pois, que quiser ser amigo do mundo constitui-se inimigo de Deus.

[[v59-4-5]]

^<<v59-4-5,5>>^ Ou supondes que em vão afirma a Escritura: É com ciúme que por nós anseia o Espírito, que ele fez habitar em nós?

[[v59-4-6]]

^<<v59-4-6,6>>^ Antes, ele dá maior graça; pelo que diz: Deus resiste aos soberbos, mas dá graça aos humildes.

[[v59-4-7]]

^<<v59-4-7,7>>^ Sujeitai-vos, portanto, a Deus; mas resisti ao diabo, e ele fugirá de vós.

[[v59-4-8]]

^<<v59-4-8,8>>^ Chegai-vos a Deus, e ele se chegará a vós outros. Purificai as mãos, pecadores; e vós que sois de ânimo dobre, limpai o coração.

[[v59-4-9]]

^<<v59-4-9,9>>^ Afligi-vos, lamentai e chorai. Converta-se o vosso riso em pranto, e a vossa alegria, em tristeza.

[[v59-4-10]]

^<<v59-4-10,10>>^ Humilhai-vos na presença do Senhor, e ele vos exaltará.

[[v59-4-11]]

^<<v59-4-11,11>>^ Irmãos, não faleis mal uns dos outros. Aquele que fala mal do irmão ou julga a seu irmão fala mal da lei e julga a lei; ora, se julgas a lei, não és observador da lei, mas juiz.

[[v59-4-12]]

^<<v59-4-12,12>>^ Um só é Legislador e Juiz, aquele que pode salvar e fazer perecer; tu, porém, quem és, que julgas o próximo?

[[v59-4-13]]

^<<v59-4-13,13>>^ Atendei, agora, vós que dizeis: Hoje ou amanhã, iremos para a cidade tal, e lá passaremos um ano, e negociaremos, e teremos lucros.

[[v59-4-14]]

^<<v59-4-14,14>>^ Vós não sabeis o que sucederá amanhã. Que é a vossa vida? Sois, apenas, como neblina que aparece por instante e logo se dissipa.

[[v59-4-15]]

^<<v59-4-15,15>>^ Em vez disso, devíeis dizer: Se o Senhor quiser, não só viveremos, como também faremos isto ou aquilo.

[[v59-4-16]]

^<<v59-4-16,16>>^ Agora, entretanto, vos jactais das vossas arrogantes pretensões. Toda jactância semelhante a essa é maligna.

[[v59-4-17]]

^<<v59-4-17,17>>^ Portanto, aquele que sabe que deve fazer o bem e não o faz nisso está pecando.

'''

xref:059-tiago/059-tiago-003.adoc#v59-3-0[&#60; Capítulo Anterior] | <<v59-4-0,Topo>> | xref:059-tiago/059-tiago-005.adoc#v59-5-0[Próximo Capítulo &#62;]