include::./index.adoc[]

[[v59-1-0]]
=== Tiago, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v59-1-1]]

^<<v59-1-1,1>>^ Tiago, servo de Deus e do Senhor Jesus Cristo, às doze tribos que se encontram na Dispersão, saudações.

[[v59-1-2]]

^<<v59-1-2,2>>^ Meus irmãos, tende por motivo de toda alegria o passardes por várias provações,

[[v59-1-3]]

^<<v59-1-3,3>>^ sabendo que a provação da vossa fé, uma vez confirmada, produz perseverança.

[[v59-1-4]]

^<<v59-1-4,4>>^ Ora, a perseverança deve ter ação completa, para que sejais perfeitos e íntegros, em nada deficientes.

[[v59-1-5]]

^<<v59-1-5,5>>^ Se, porém, algum de vós necessita de sabedoria, peça-a a Deus, que a todos dá liberalmente e nada lhes impropera; e ser-lhe-á concedida.

[[v59-1-6]]

^<<v59-1-6,6>>^ Peça-a, porém, com fé, em nada duvidando; pois o que duvida é semelhante à onda do mar, impelida e agitada pelo vento.

[[v59-1-7]]

^<<v59-1-7,7>>^ Não suponha esse homem que alcançará do Senhor alguma coisa;

[[v59-1-8]]

^<<v59-1-8,8>>^ homem de ânimo dobre, inconstante em todos os seus caminhos.

[[v59-1-9]]

^<<v59-1-9,9>>^ O irmão, porém, de condição humilde glorie-se na sua dignidade,

[[v59-1-10]]

^<<v59-1-10,10>>^ e o rico, na sua insignificância, porque ele passará como a flor da erva.

[[v59-1-11]]

^<<v59-1-11,11>>^ Porque o sol se levanta com seu ardente calor, e a erva seca, e a sua flor cai, e desaparece a formosura do seu aspecto; assim também se murchará o rico em seus caminhos.

[[v59-1-12]]

^<<v59-1-12,12>>^ Bem-aventurado o homem que suporta, com perseverança, a provação; porque, depois de ter sido aprovado, receberá a coroa da vida, a qual o Senhor prometeu aos que o amam.

[[v59-1-13]]

^<<v59-1-13,13>>^ Ninguém, ao ser tentado, diga: Sou tentado por Deus; porque Deus não pode ser tentado pelo mal e ele mesmo a ninguém tenta.

[[v59-1-14]]

^<<v59-1-14,14>>^ Ao contrário, cada um é tentado pela sua própria cobiça, quando esta o atrai e seduz.

[[v59-1-15]]

^<<v59-1-15,15>>^ Então, a cobiça, depois de haver concebido, dá à luz o pecado; e o pecado, uma vez consumado, gera a morte.

[[v59-1-16]]

^<<v59-1-16,16>>^ Não vos enganeis, meus amados irmãos.

[[v59-1-17]]

^<<v59-1-17,17>>^ Toda boa dádiva e todo dom perfeito são lá do alto, descendo do Pai das luzes, em quem não pode existir variação ou sombra de mudança.

[[v59-1-18]]

^<<v59-1-18,18>>^ Pois, segundo o seu querer, ele nos gerou pela palavra da verdade, para que fôssemos como que primícias das suas criaturas.

[[v59-1-19]]

^<<v59-1-19,19>>^ Sabeis estas coisas, meus amados irmãos. Todo homem, pois, seja pronto para ouvir, tardio para falar, tardio para se irar.

[[v59-1-20]]

^<<v59-1-20,20>>^ Porque a ira do homem não produz a justiça de Deus.

[[v59-1-21]]

^<<v59-1-21,21>>^ Portanto, despojando-vos de toda impureza e acúmulo de maldade, acolhei, com mansidão, a palavra em vós implantada, a qual é poderosa para salvar a vossa alma.

[[v59-1-22]]

^<<v59-1-22,22>>^ Tornai-vos, pois, praticantes da palavra e não somente ouvintes, enganando-vos a vós mesmos.

[[v59-1-23]]

^<<v59-1-23,23>>^ Porque, se alguém é ouvinte da palavra e não praticante, assemelha-se ao homem que contempla, num espelho, o seu rosto natural;

[[v59-1-24]]

^<<v59-1-24,24>>^ pois a si mesmo se contempla, e se retira, e para logo se esquece de como era a sua aparência.

[[v59-1-25]]

^<<v59-1-25,25>>^ Mas aquele que considera, atentamente, na lei perfeita, lei da liberdade, e nela persevera, não sendo ouvinte negligente, mas operoso praticante, esse será bem-aventurado no que realizar.

[[v59-1-26]]

^<<v59-1-26,26>>^ Se alguém supõe ser religioso, deixando de refrear a língua, antes, enganando o próprio coração, a sua religião é vã.

[[v59-1-27]]

^<<v59-1-27,27>>^ A religião pura e sem mácula, para com o nosso Deus e Pai, é esta: visitar os órfãos e as viúvas nas suas tribulações e a si mesmo guardar-se incontaminado do mundo.

'''

xref:058-hebreus/058-hebreus-013.adoc#v58-13-0[&#60; Capítulo Anterior] | <<v59-1-0,Topo>> | xref:059-tiago/059-tiago-002.adoc#v59-2-0[Próximo Capítulo &#62;]