include::./index.adoc[]

[[v59-2-0]]
=== Tiago, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v59-2-1]]

^<<v59-2-1,1>>^ Meus irmãos, não tenhais a fé em nosso Senhor Jesus Cristo, Senhor da glória, em acepção de pessoas.

[[v59-2-2]]

^<<v59-2-2,2>>^ Se, portanto, entrar na vossa sinagoga algum homem com anéis de ouro nos dedos, em trajos de luxo, e entrar também algum pobre andrajoso,

[[v59-2-3]]

^<<v59-2-3,3>>^ e tratardes com deferência o que tem os trajos de luxo e lhe disserdes: Tu, assenta-te aqui em lugar de honra; e disserdes ao pobre: Tu, fica ali em pé ou assenta-te aqui abaixo do estrado dos meus pés,

[[v59-2-4]]

^<<v59-2-4,4>>^ não fizestes distinção entre vós mesmos e não vos tornastes juízes tomados de perversos pensamentos?

[[v59-2-5]]

^<<v59-2-5,5>>^ Ouvi, meus amados irmãos. Não escolheu Deus os que para o mundo são pobres, para serem ricos em fé e herdeiros do reino que ele prometeu aos que o amam?

[[v59-2-6]]

^<<v59-2-6,6>>^ Entretanto, vós outros menosprezastes o pobre. Não são os ricos que vos oprimem e não são eles que vos arrastam para tribunais?

[[v59-2-7]]

^<<v59-2-7,7>>^ Não são eles os que blasfemam o bom nome que sobre vós foi invocado?

[[v59-2-8]]

^<<v59-2-8,8>>^ Se vós, contudo, observais a lei régia segundo a Escritura: Amarás o teu próximo como a ti mesmo, fazeis bem;

[[v59-2-9]]

^<<v59-2-9,9>>^ se, todavia, fazeis acepção de pessoas, cometeis pecado, sendo arguidos pela lei como transgressores.

[[v59-2-10]]

^<<v59-2-10,10>>^ Pois qualquer que guarda toda a lei, mas tropeça em um só ponto, se torna culpado de todos.

[[v59-2-11]]

^<<v59-2-11,11>>^ Porquanto, aquele que disse: Não adulterarás também ordenou: Não matarás. Ora, se não adulteras, porém matas, vens a ser transgressor da lei.

[[v59-2-12]]

^<<v59-2-12,12>>^ Falai de tal maneira e de tal maneira procedei como aqueles que hão de ser julgados pela lei da liberdade.

[[v59-2-13]]

^<<v59-2-13,13>>^ Porque o juízo é sem misericórdia para com aquele que não usou de misericórdia. A misericórdia triunfa sobre o juízo.

[[v59-2-14]]

^<<v59-2-14,14>>^ Meus irmãos, qual é o proveito, se alguém disser que tem fé, mas não tiver obras? Pode, acaso, semelhante fé salvá-lo?

[[v59-2-15]]

^<<v59-2-15,15>>^ Se um irmão ou uma irmã estiverem carecidos de roupa e necessitados do alimento cotidiano,

[[v59-2-16]]

^<<v59-2-16,16>>^ e qualquer dentre vós lhes disser: Ide em paz, aquecei-vos e fartai-vos, sem, contudo, lhes dar o necessário para o corpo, qual é o proveito disso?

[[v59-2-17]]

^<<v59-2-17,17>>^ Assim, também a fé, se não tiver obras, por si só está morta.

[[v59-2-18]]

^<<v59-2-18,18>>^ Mas alguém dirá: Tu tens fé, e eu tenho obras; mostra-me essa tua fé sem as obras, e eu, com as obras, te mostrarei a minha fé.

[[v59-2-19]]

^<<v59-2-19,19>>^ Crês, tu, que Deus é um só? Fazes bem. Até os demônios creem e tremem.

[[v59-2-20]]

^<<v59-2-20,20>>^ Queres, pois, ficar certo, ó homem insensato, de que a fé sem as obras é inoperante?

[[v59-2-21]]

^<<v59-2-21,21>>^ Não foi por obras que Abraão, o nosso pai, foi justificado, quando ofereceu sobre o altar o próprio filho, Isaque?

[[v59-2-22]]

^<<v59-2-22,22>>^ Vês como a fé operava juntamente com as suas obras; com efeito, foi pelas obras que a fé se consumou,

[[v59-2-23]]

^<<v59-2-23,23>>^ e se cumpriu a Escritura, a qual diz: Ora, Abraão creu em Deus, e isso lhe foi imputado para justiça; e: Foi chamado amigo de Deus.

[[v59-2-24]]

^<<v59-2-24,24>>^ Verificais que uma pessoa é justificada por obras e não por fé somente.

[[v59-2-25]]

^<<v59-2-25,25>>^ De igual modo, não foi também justificada por obras a meretriz Raabe, quando acolheu os emissários e os fez partir por outro caminho?

[[v59-2-26]]

^<<v59-2-26,26>>^ Porque, assim como o corpo sem espírito é morto, assim também a fé sem obras é morta.

'''

xref:059-tiago/059-tiago-001.adoc#v59-1-0[&#60; Capítulo Anterior] | <<v59-2-0,Topo>> | xref:059-tiago/059-tiago-003.adoc#v59-3-0[Próximo Capítulo &#62;]