include::./index.adoc[]

[[v59-3-0]]
=== Tiago, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v59-3-1]]

^<<v59-3-1,1>>^ Meus irmãos, não vos torneis, muitos de vós, mestres, sabendo que havemos de receber maior juízo.

[[v59-3-2]]

^<<v59-3-2,2>>^ Porque todos tropeçamos em muitas coisas. Se alguém não tropeça no falar, é perfeito varão, capaz de refrear também todo o corpo.

[[v59-3-3]]

^<<v59-3-3,3>>^ Ora, se pomos freio na boca dos cavalos, para nos obedecerem, também lhes dirigimos o corpo inteiro.

[[v59-3-4]]

^<<v59-3-4,4>>^ Observai, igualmente, os navios que, sendo tão grandes e batidos de rijos ventos, por um pequeníssimo leme são dirigidos para onde queira o impulso do timoneiro.

[[v59-3-5]]

^<<v59-3-5,5>>^ Assim, também a língua, pequeno órgão, se gaba de grandes coisas. Vede como uma fagulha põe em brasas tão grande selva!

[[v59-3-6]]

^<<v59-3-6,6>>^ Ora, a língua é fogo; é mundo de iniquidade; a língua está situada entre os membros de nosso corpo, e contamina o corpo inteiro, e não só põe em chamas toda a carreira da existência humana, como também é posta ela mesma em chamas pelo inferno.

[[v59-3-7]]

^<<v59-3-7,7>>^ Pois toda espécie de feras, de aves, de répteis e de seres marinhos se doma e tem sido domada pelo gênero humano;

[[v59-3-8]]

^<<v59-3-8,8>>^ a língua, porém, nenhum dos homens é capaz de domar; é mal incontido, carregado de veneno mortífero.

[[v59-3-9]]

^<<v59-3-9,9>>^ Com ela, bendizemos ao Senhor e Pai; também, com ela, amaldiçoamos os homens, feitos à semelhança de Deus.

[[v59-3-10]]

^<<v59-3-10,10>>^ De uma só boca procede bênção e maldição. Meus irmãos, não é conveniente que estas coisas sejam assim.

[[v59-3-11]]

^<<v59-3-11,11>>^ Acaso, pode a fonte jorrar do mesmo lugar o que é doce e o que é amargoso?

[[v59-3-12]]

^<<v59-3-12,12>>^ Acaso, meus irmãos, pode a figueira produzir azeitonas ou a videira, figos? Tampouco fonte de água salgada pode dar água doce.

[[v59-3-13]]

^<<v59-3-13,13>>^ Quem entre vós é sábio e inteligente? Mostre em mansidão de sabedoria, mediante condigno proceder, as suas obras.

[[v59-3-14]]

^<<v59-3-14,14>>^ Se, pelo contrário, tendes em vosso coração inveja amargurada e sentimento faccioso, nem vos glorieis disso, nem mintais contra a verdade.

[[v59-3-15]]

^<<v59-3-15,15>>^ Esta não é a sabedoria que desce lá do alto; antes, é terrena, animal e demoníaca.

[[v59-3-16]]

^<<v59-3-16,16>>^ Pois, onde há inveja e sentimento faccioso, aí há confusão e toda espécie de coisas ruins.

[[v59-3-17]]

^<<v59-3-17,17>>^ A sabedoria, porém, lá do alto é, primeiramente, pura; depois, pacífica, indulgente, tratável, plena de misericórdia e de bons frutos, imparcial, sem fingimento.

[[v59-3-18]]

^<<v59-3-18,18>>^ Ora, é em paz que se semeia o fruto da justiça, para os que promovem a paz.

'''

xref:059-tiago/059-tiago-002.adoc#v59-2-0[&#60; Capítulo Anterior] | <<v59-3-0,Topo>> | xref:059-tiago/059-tiago-004.adoc#v59-4-0[Próximo Capítulo &#62;]