include::./index.adoc[]

[[v56-1-0]]
=== Tito, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v56-1-1]]

^<<v56-1-1,1>>^ Paulo, servo de Deus e apóstolo de Jesus Cristo, para promover a fé que é dos eleitos de Deus e o pleno conhecimento da verdade segundo a piedade,

[[v56-1-2]]

^<<v56-1-2,2>>^ na esperança da vida eterna que o Deus que não pode mentir prometeu antes dos tempos eternos

[[v56-1-3]]

^<<v56-1-3,3>>^ e, em tempos devidos, manifestou a sua palavra mediante a pregação que me foi confiada por mandato de Deus, nosso Salvador,

[[v56-1-4]]

^<<v56-1-4,4>>^ a Tito, verdadeiro filho, segundo a fé comum, graça e paz, da parte de Deus Pai e de Cristo Jesus, nosso Salvador.

[[v56-1-5]]

^<<v56-1-5,5>>^ Por esta causa, te deixei em Creta, para que pusesses em ordem as coisas restantes, bem como, em cada cidade, constituísses presbíteros, conforme te prescrevi:

[[v56-1-6]]

^<<v56-1-6,6>>^ alguém que seja irrepreensível, marido de uma só mulher, que tenha filhos crentes que não são acusados de dissolução, nem são insubordinados.

[[v56-1-7]]

^<<v56-1-7,7>>^ Porque é indispensável que o bispo seja irrepreensível como despenseiro de Deus, não arrogante, não irascível, não dado ao vinho, nem violento, nem cobiçoso de torpe ganância;

[[v56-1-8]]

^<<v56-1-8,8>>^ antes, hospitaleiro, amigo do bem, sóbrio, justo, piedoso, que tenha domínio de si,

[[v56-1-9]]

^<<v56-1-9,9>>^ apegado à palavra fiel, que é segundo a doutrina, de modo que tenha poder tanto para exortar pelo reto ensino como para convencer os que o contradizem.

[[v56-1-10]]

^<<v56-1-10,10>>^ Porque existem muitos insubordinados, palradores frívolos e enganadores, especialmente os da circuncisão.

[[v56-1-11]]

^<<v56-1-11,11>>^ É preciso fazê-los calar, porque andam pervertendo casas inteiras, ensinando o que não devem, por torpe ganância.

[[v56-1-12]]

^<<v56-1-12,12>>^ Foi mesmo, dentre eles, um seu profeta, que disse: Cretenses, sempre mentirosos, feras terríveis, ventres preguiçosos.

[[v56-1-13]]

^<<v56-1-13,13>>^ Tal testemunho é exato. Portanto, repreende-os severamente, para que sejam sadios na fé

[[v56-1-14]]

^<<v56-1-14,14>>^ e não se ocupem com fábulas judaicas, nem com mandamentos de homens desviados da verdade.

[[v56-1-15]]

^<<v56-1-15,15>>^ Todas as coisas são puras para os puros; todavia, para os impuros e descrentes, nada é puro. Porque tanto a mente como a consciência deles estão corrompidas.

[[v56-1-16]]

^<<v56-1-16,16>>^ No tocante a Deus, professam conhecê-lo; entretanto, o negam por suas obras; é por isso que são abomináveis, desobedientes e reprovados para toda boa obra.

'''

xref:055-2-timoteo/055-2-timoteo-004.adoc#v55-4-0[&#60; Capítulo Anterior] | <<v56-1-0,Topo>> | xref:056-tito/056-tito-002.adoc#v56-2-0[Próximo Capítulo &#62;]