include::./index.adoc[]

[[v62-4-0]]
=== 1 João, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v62-4-1]]

^<<v62-4-1,1>>^ Amados, não deis crédito a qualquer espírito; antes, provai os espíritos se procedem de Deus, porque muitos falsos profetas têm saído pelo mundo fora.

[[v62-4-2]]

^<<v62-4-2,2>>^ Nisto reconheceis o Espírito de Deus: todo espírito que confessa que Jesus Cristo veio em carne é de Deus;

[[v62-4-3]]

^<<v62-4-3,3>>^ e todo espírito que não confessa a Jesus não procede de Deus; pelo contrário, este é o espírito do anticristo, a respeito do qual tendes ouvido que vem e, presentemente, já está no mundo.

[[v62-4-4]]

^<<v62-4-4,4>>^ Filhinhos, vós sois de Deus e tendes vencido os falsos profetas, porque maior é aquele que está em vós do que aquele que está no mundo.

[[v62-4-5]]

^<<v62-4-5,5>>^ Eles procedem do mundo; por essa razão, falam da parte do mundo, e o mundo os ouve.

[[v62-4-6]]

^<<v62-4-6,6>>^ Nós somos de Deus; aquele que conhece a Deus nos ouve; aquele que não é da parte de Deus não nos ouve. Nisto reconhecemos o espírito da verdade e o espírito do erro.

[[v62-4-7]]

^<<v62-4-7,7>>^ Amados, amemo-nos uns aos outros, porque o amor procede de Deus; e todo aquele que ama é nascido de Deus e conhece a Deus.

[[v62-4-8]]

^<<v62-4-8,8>>^ Aquele que não ama não conhece a Deus, pois Deus é amor.

[[v62-4-9]]

^<<v62-4-9,9>>^ Nisto se manifestou o amor de Deus em nós: em haver Deus enviado o seu Filho unigênito ao mundo, para vivermos por meio dele.

[[v62-4-10]]

^<<v62-4-10,10>>^ Nisto consiste o amor: não em que nós tenhamos amado a Deus, mas em que ele nos amou e enviou o seu Filho como propiciação pelos nossos pecados.

[[v62-4-11]]

^<<v62-4-11,11>>^ Amados, se Deus de tal maneira nos amou, devemos nós também amar uns aos outros.

[[v62-4-12]]

^<<v62-4-12,12>>^ Ninguém jamais viu a Deus; se amarmos uns aos outros, Deus permanece em nós, e o seu amor é, em nós, aperfeiçoado.

[[v62-4-13]]

^<<v62-4-13,13>>^ Nisto conhecemos que permanecemos nele, e ele, em nós: em que nos deu do seu Espírito.

[[v62-4-14]]

^<<v62-4-14,14>>^ E nós temos visto e testemunhamos que o Pai enviou o seu Filho como Salvador do mundo.

[[v62-4-15]]

^<<v62-4-15,15>>^ Aquele que confessar que Jesus é o Filho de Deus, Deus permanece nele, e ele, em Deus.

[[v62-4-16]]

^<<v62-4-16,16>>^ E nós conhecemos e cremos no amor que Deus tem por nós. Deus é amor, e aquele que permanece no amor permanece em Deus, e Deus, nele.

[[v62-4-17]]

^<<v62-4-17,17>>^ Nisto é em nós aperfeiçoado o amor, para que, no Dia do Juízo, mantenhamos confiança; pois, segundo ele é, também nós somos neste mundo.

[[v62-4-18]]

^<<v62-4-18,18>>^ No amor não existe medo; antes, o perfeito amor lança fora o medo. Ora, o medo produz tormento; logo, aquele que teme não é aperfeiçoado no amor.

[[v62-4-19]]

^<<v62-4-19,19>>^ Nós amamos porque ele nos amou primeiro.

[[v62-4-20]]

^<<v62-4-20,20>>^ Se alguém disser: Amo a Deus, e odiar a seu irmão, é mentiroso; pois aquele que não ama a seu irmão, a quem vê, não pode amar a Deus, a quem não vê.

[[v62-4-21]]

^<<v62-4-21,21>>^ Ora, temos, da parte dele, este mandamento: que aquele que ama a Deus ame também a seu irmão.

'''

xref:062-1-joao/062-1-joao-003.adoc#v62-3-0[&#60; Capítulo Anterior] | <<v62-4-0,Topo>> | xref:062-1-joao/062-1-joao-005.adoc#v62-5-0[Próximo Capítulo &#62;]