include::./index.adoc[]

[[v62-2-0]]
=== 1 João, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v62-2-1]]

^<<v62-2-1,1>>^ Filhinhos meus, estas coisas vos escrevo para que não pequeis. Se, todavia, alguém pecar, temos Advogado junto ao Pai, Jesus Cristo, o Justo;

[[v62-2-2]]

^<<v62-2-2,2>>^ e ele é a propiciação pelos nossos pecados e não somente pelos nossos próprios, mas ainda pelos do mundo inteiro.

[[v62-2-3]]

^<<v62-2-3,3>>^ Ora, sabemos que o temos conhecido por isto: se guardamos os seus mandamentos.

[[v62-2-4]]

^<<v62-2-4,4>>^ Aquele que diz: Eu o conheço e não guarda os seus mandamentos é mentiroso, e nele não está a verdade.

[[v62-2-5]]

^<<v62-2-5,5>>^ Aquele, entretanto, que guarda a sua palavra, nele, verdadeiramente, tem sido aperfeiçoado o amor de Deus. Nisto sabemos que estamos nele:

[[v62-2-6]]

^<<v62-2-6,6>>^ aquele que diz que permanece nele, esse deve também andar assim como ele andou.

[[v62-2-7]]

^<<v62-2-7,7>>^ Amados, não vos escrevo mandamento novo, senão mandamento antigo, o qual, desde o princípio, tivestes. Esse mandamento antigo é a palavra que ouvistes.

[[v62-2-8]]

^<<v62-2-8,8>>^ Todavia, vos escrevo novo mandamento, aquilo que é verdadeiro nele e em vós, porque as trevas se vão dissipando, e a verdadeira luz já brilha.

[[v62-2-9]]

^<<v62-2-9,9>>^ Aquele que diz estar na luz e odeia a seu irmão, até agora, está nas trevas.

[[v62-2-10]]

^<<v62-2-10,10>>^ Aquele que ama a seu irmão permanece na luz, e nele não há nenhum tropeço.

[[v62-2-11]]

^<<v62-2-11,11>>^ Aquele, porém, que odeia a seu irmão está nas trevas, e anda nas trevas, e não sabe para onde vai, porque as trevas lhe cegaram os olhos.

[[v62-2-12]]

^<<v62-2-12,12>>^ Filhinhos, eu vos escrevo, porque os vossos pecados são perdoados, por causa do seu nome.

[[v62-2-13]]

^<<v62-2-13,13>>^ Pais, eu vos escrevo, porque conheceis aquele que existe desde o princípio. Jovens, eu vos escrevo, porque tendes vencido o Maligno.

[[v62-2-14]]

^<<v62-2-14,14>>^ Filhinhos, eu vos escrevi, porque conheceis o Pai. Pais, eu vos escrevi, porque conheceis aquele que existe desde o princípio. Jovens, eu vos escrevi, porque sois fortes, e a palavra de Deus permanece em vós, e tendes vencido o Maligno.

[[v62-2-15]]

^<<v62-2-15,15>>^ Não ameis o mundo nem as coisas que há no mundo. Se alguém amar o mundo, o amor do Pai não está nele;

[[v62-2-16]]

^<<v62-2-16,16>>^ porque tudo que há no mundo, a concupiscência da carne, a concupiscência dos olhos e a soberba da vida, não procede do Pai, mas procede do mundo.

[[v62-2-17]]

^<<v62-2-17,17>>^ Ora, o mundo passa, bem como a sua concupiscência; aquele, porém, que faz a vontade de Deus permanece eternamente.

[[v62-2-18]]

^<<v62-2-18,18>>^ Filhinhos, já é a última hora; e, como ouvistes que vem o anticristo, também, agora, muitos anticristos têm surgido; pelo que conhecemos que é a última hora.

[[v62-2-19]]

^<<v62-2-19,19>>^ Eles saíram de nosso meio; entretanto, não eram dos nossos; porque, se tivessem sido dos nossos, teriam permanecido conosco; todavia, eles se foram para que ficasse manifesto que nenhum deles é dos nossos.

[[v62-2-20]]

^<<v62-2-20,20>>^ E vós possuís unção que vem do Santo e todos tendes conhecimento.

[[v62-2-21]]

^<<v62-2-21,21>>^ Não vos escrevi porque não saibais a verdade; antes, porque a sabeis, e porque mentira alguma jamais procede da verdade.

[[v62-2-22]]

^<<v62-2-22,22>>^ Quem é o mentiroso, senão aquele que nega que Jesus é o Cristo? Este é o anticristo, o que nega o Pai e o Filho.

[[v62-2-23]]

^<<v62-2-23,23>>^ Todo aquele que nega o Filho, esse não tem o Pai; aquele que confessa o Filho tem igualmente o Pai.

[[v62-2-24]]

^<<v62-2-24,24>>^ Permaneça em vós o que ouvistes desde o princípio. Se em vós permanecer o que desde o princípio ouvistes, também permanecereis vós no Filho e no Pai.

[[v62-2-25]]

^<<v62-2-25,25>>^ E esta é a promessa que ele mesmo nos fez, a vida eterna.

[[v62-2-26]]

^<<v62-2-26,26>>^ Isto que vos acabo de escrever é acerca dos que vos procuram enganar.

[[v62-2-27]]

^<<v62-2-27,27>>^ Quanto a vós outros, a unção que dele recebestes permanece em vós, e não tendes necessidade de que alguém vos ensine; mas, como a sua unção vos ensina a respeito de todas as coisas, e é verdadeira, e não é falsa, permanecei nele, como também ela vos ensinou.

[[v62-2-28]]

^<<v62-2-28,28>>^ Filhinhos, agora, pois, permanecei nele, para que, quando ele se manifestar, tenhamos confiança e dele não nos afastemos envergonhados na sua vinda.

[[v62-2-29]]

^<<v62-2-29,29>>^ Se sabeis que ele é justo, reconhecei também que todo aquele que pratica a justiça é nascido dele.

'''

xref:062-1-joao/062-1-joao-001.adoc#v62-1-0[&#60; Capítulo Anterior] | <<v62-2-0,Topo>> | xref:062-1-joao/062-1-joao-003.adoc#v62-3-0[Próximo Capítulo &#62;]