include::./index.adoc[]

[[v62-1-0]]
=== 1 João, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v62-1-1]]

^<<v62-1-1,1>>^ O que era desde o princípio, o que temos ouvido, o que temos visto com os nossos próprios olhos, o que contemplamos, e as nossas mãos apalparam, com respeito ao Verbo da vida

[[v62-1-2]]

^<<v62-1-2,2>>^ (e a vida se manifestou, e nós a temos visto, e dela damos testemunho, e vo-la anunciamos, a vida eterna, a qual estava com o Pai e nos foi manifestada),

[[v62-1-3]]

^<<v62-1-3,3>>^ o que temos visto e ouvido anunciamos também a vós outros, para que vós, igualmente, mantenhais comunhão conosco. Ora, a nossa comunhão é com o Pai e com seu Filho, Jesus Cristo.

[[v62-1-4]]

^<<v62-1-4,4>>^ Estas coisas, pois, vos escrevemos para que a nossa alegria seja completa.

[[v62-1-5]]

^<<v62-1-5,5>>^ Ora, a mensagem que, da parte dele, temos ouvido e vos anunciamos é esta: que Deus é luz, e não há nele treva nenhuma.

[[v62-1-6]]

^<<v62-1-6,6>>^ Se dissermos que mantemos comunhão com ele e andarmos nas trevas, mentimos e não praticamos a verdade.

[[v62-1-7]]

^<<v62-1-7,7>>^ Se, porém, andarmos na luz, como ele está na luz, mantemos comunhão uns com os outros, e o sangue de Jesus, seu Filho, nos purifica de todo pecado.

[[v62-1-8]]

^<<v62-1-8,8>>^ Se dissermos que não temos pecado nenhum, a nós mesmos nos enganamos, e a verdade não está em nós.

[[v62-1-9]]

^<<v62-1-9,9>>^ Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça.

[[v62-1-10]]

^<<v62-1-10,10>>^ Se dissermos que não temos cometido pecado, fazemo-lo mentiroso, e a sua palavra não está em nós.

'''

xref:061-2-pedro/061-2-pedro-003.adoc#v61-3-0[&#60; Capítulo Anterior] | <<v62-1-0,Topo>> | xref:062-1-joao/062-1-joao-002.adoc#v62-2-0[Próximo Capítulo &#62;]