include::./index.adoc[]

[[v16-5-0]]
=== Neemias, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v16-5-1]]

^<<v16-5-1,1>>^ Foi grande, porém, o clamor do povo e de suas mulheres contra os judeus, seus irmãos.

[[v16-5-2]]

^<<v16-5-2,2>>^ Porque havia os que diziam: Somos muitos, nós, nossos filhos e nossas filhas; que se nos dê trigo, para que comamos e vivamos.

[[v16-5-3]]

^<<v16-5-3,3>>^ Também houve os que diziam: As nossas terras, as nossas vinhas e as nossas casas hipotecamos para tomarmos trigo nesta fome.

[[v16-5-4]]

^<<v16-5-4,4>>^ Houve ainda os que diziam: Tomamos dinheiro emprestado até para o tributo do rei, sobre as nossas terras e as nossas vinhas.

[[v16-5-5]]

^<<v16-5-5,5>>^ No entanto, nós somos da mesma carne como eles, e nossos filhos são tão bons como os deles; e eis que sujeitamos nossos filhos e nossas filhas para serem escravos, algumas de nossas filhas já estão reduzidas à escravidão. Não está em nosso poder evitá-lo; pois os nossos campos e as nossas vinhas já são de outros.

[[v16-5-6]]

^<<v16-5-6,6>>^ Ouvindo eu, pois, o seu clamor e estas palavras, muito me aborreci.

[[v16-5-7]]

^<<v16-5-7,7>>^ Depois de ter considerado comigo mesmo, repreendi os nobres e magistrados e lhes disse: Sois usurários, cada um para com seu irmão; e convoquei contra eles um grande ajuntamento.

[[v16-5-8]]

^<<v16-5-8,8>>^ Disse-lhes: nós resgatamos os judeus, nossos irmãos, que foram vendidos às gentes, segundo nossas posses; e vós outra vez negociaríeis vossos irmãos, para que sejam vendidos a nós?

[[v16-5-9]]

^<<v16-5-9,9>>^ Então, se calaram e não acharam o que responder. Disse mais: não é bom o que fazeis; porventura não devíeis andar no temor do nosso Deus, por causa do opróbrio dos gentios, os nossos inimigos?

[[v16-5-10]]

^<<v16-5-10,10>>^ Também eu, meus irmãos e meus moços lhes demos dinheiro emprestado e trigo. Demos de mão a esse empréstimo.

[[v16-5-11]]

^<<v16-5-11,11>>^ Restituí-lhes hoje, vos peço, as suas terras, as suas vinhas, os seus olivais e as suas casas, como também o centésimo do dinheiro, do trigo, do vinho e do azeite, que exigistes deles.

[[v16-5-12]]

^<<v16-5-12,12>>^ Então, responderam: Restituir-lhes-emos e nada lhes pediremos; faremos assim como dizes. Então, chamei os sacerdotes e os fiz jurar que fariam segundo prometeram.

[[v16-5-13]]

^<<v16-5-13,13>>^ Também sacudi o meu regaço e disse: Assim o faça Deus, sacuda de sua casa e de seu trabalho a todo homem que não cumprir esta promessa; seja sacudido e despojado. E toda a congregação respondeu: Amém! E louvaram o SENHOR; e o povo fez segundo a sua promessa.

[[v16-5-14]]

^<<v16-5-14,14>>^ Também desde o dia em que fui nomeado seu governador na terra de Judá, desde o vigésimo ano até ao trigésimo segundo ano do rei Artaxerxes, doze anos, nem eu nem meus irmãos comemos o pão devido ao governador.

[[v16-5-15]]

^<<v16-5-15,15>>^ Mas os primeiros governadores, que foram antes de mim, oprimiram o povo e lhe tomaram pão e vinho, além de quarenta siclos de prata; até os seus moços dominavam sobre o povo, porém eu assim não fiz, por causa do temor de Deus.

[[v16-5-16]]

^<<v16-5-16,16>>^ Antes, também na obra deste muro fiz reparação, e terra nenhuma compramos; e todos os meus moços se ajuntaram ali para a obra.

[[v16-5-17]]

^<<v16-5-17,17>>^ Também cento e cinquenta homens dos judeus e dos magistrados e os que vinham a nós, dentre as gentes que estavam ao nosso redor, eram meus hóspedes.

[[v16-5-18]]

^<<v16-5-18,18>>^ O que se preparava para cada dia era um boi e seis ovelhas escolhidas; também à minha custa eram preparadas aves e, de dez em dez dias, muito vinho de todas as espécies; nem por isso exigi o pão devido ao governador, porquanto a servidão deste povo era grande.

[[v16-5-19]]

^<<v16-5-19,19>>^ Lembra-te de mim para meu bem, ó meu Deus, e de tudo quanto fiz a este povo.

'''

xref:016-neemias/016-neemias-004.adoc#v16-4-0[&#60; Capítulo Anterior] | <<v16-5-0,Topo>> | xref:016-neemias/016-neemias-006.adoc#v16-6-0[Próximo Capítulo &#62;]