include::./index.adoc[]

[[v16-8-0]]
=== Neemias, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v16-8-1]]

^<<v16-8-1,1>>^ Em chegando o sétimo mês, e estando os filhos de Israel nas suas cidades, todo o povo se ajuntou como um só homem, na praça, diante da Porta das Águas; e disseram a Esdras, o escriba, que trouxesse o Livro da Lei de Moisés, que o SENHOR tinha prescrito a Israel.

[[v16-8-2]]

^<<v16-8-2,2>>^ Esdras, o sacerdote, trouxe a Lei perante a congregação, tanto de homens como de mulheres e de todos os que eram capazes de entender o que ouviam. Era o primeiro dia do sétimo mês.

[[v16-8-3]]

^<<v16-8-3,3>>^ E leu no livro, diante da praça, que está fronteira à Porta das Águas, desde a alva até ao meio-dia, perante homens e mulheres e os que podiam entender; e todo o povo tinha os ouvidos atentos ao Livro da Lei.

[[v16-8-4]]

^<<v16-8-4,4>>^ Esdras, o escriba, estava num púlpito de madeira, que fizeram para aquele fim; estavam em pé junto a ele, à sua direita, Matitias, Sema, Anaías, Urias, Hilquias e Maaseias; e à sua esquerda, Pedaías, Misael, Malquias, Hasum, Hasbadana, Zacarias e Mesulão.

[[v16-8-5]]

^<<v16-8-5,5>>^ Esdras abriu o livro à vista de todo o povo, porque estava acima dele; abrindo-o ele, todo o povo se pôs em pé.

[[v16-8-6]]

^<<v16-8-6,6>>^ Esdras bendisse ao SENHOR, o grande Deus; e todo o povo respondeu: Amém! Amém! E, levantando as mãos; inclinaram-se e adoraram o SENHOR, com o rosto em terra.

[[v16-8-7]]

^<<v16-8-7,7>>^ E Jesua, Bani, Serebias, Jamim, Acube, Sabetai, Hodias, Maaseias, Quelita, Azarias, Jozabade, Hanã, Pelaías e os levitas ensinavam o povo na Lei; e o povo estava no seu lugar.

[[v16-8-8]]

^<<v16-8-8,8>>^ Leram no livro, na Lei de Deus, claramente, dando explicações, de maneira que entendessem o que se lia.

[[v16-8-9]]

^<<v16-8-9,9>>^ Neemias, que era o governador, e Esdras, sacerdote e escriba, e os levitas que ensinavam todo o povo lhe disseram: Este dia é consagrado ao SENHOR, vosso Deus, pelo que não pranteeis, nem choreis. Porque todo o povo chorava, ouvindo as palavras da Lei.

[[v16-8-10]]

^<<v16-8-10,10>>^ Disse-lhes mais: ide, comei carnes gordas, tomai bebidas doces e enviai porções aos que não têm nada preparado para si; porque este dia é consagrado ao nosso Senhor; portanto, não vos entristeçais, porque a alegria do SENHOR é a vossa força.

[[v16-8-11]]

^<<v16-8-11,11>>^ Os levitas fizeram calar todo o povo, dizendo: Calai-vos, porque este dia é santo; e não estejais contristados.

[[v16-8-12]]

^<<v16-8-12,12>>^ Então, todo o povo se foi a comer, a beber, a enviar porções e a regozijar-se grandemente, porque tinham entendido as palavras que lhes foram explicadas.

[[v16-8-13]]

^<<v16-8-13,13>>^ No dia seguinte, ajuntaram-se a Esdras, o escriba, os cabeças das famílias de todo o povo, os sacerdotes e os levitas, e isto para atentarem nas palavras da Lei.

[[v16-8-14]]

^<<v16-8-14,14>>^ Acharam escrito na Lei que o SENHOR ordenara por intermédio de Moisés que os filhos de Israel habitassem em cabanas, durante a festa do sétimo mês;

[[v16-8-15]]

^<<v16-8-15,15>>^ que publicassem e fizessem passar pregão por todas as suas cidades e em Jerusalém, dizendo: Saí ao monte e trazei ramos de oliveiras, ramos de zambujeiros, ramos de murtas, ramos de palmeiras e ramos de árvores frondosas, para fazer cabanas, como está escrito.

[[v16-8-16]]

^<<v16-8-16,16>>^ Saiu, pois, o povo, trouxeram os ramos e fizeram para si cabanas, cada um no seu terraço, e nos seus pátios, e nos átrios da Casa de Deus, e na praça da Porta das Águas, e na praça da Porta de Efraim.

[[v16-8-17]]

^<<v16-8-17,17>>^ Toda a congregação dos que tinham voltado do cativeiro fez cabanas e nelas habitou; porque nunca fizeram assim os filhos de Israel, desde os dias de Josué, filho de Num, até àquele dia; e houve mui grande alegria.

[[v16-8-18]]

^<<v16-8-18,18>>^ Dia após dia, leu Esdras no Livro da Lei de Deus, desde o primeiro dia até ao último; e celebraram a festa por sete dias; no oitavo dia, houve uma assembleia solene, segundo o prescrito.

'''

xref:016-neemias/016-neemias-007.adoc#v16-7-0[&#60; Capítulo Anterior] | <<v16-8-0,Topo>> | xref:016-neemias/016-neemias-009.adoc#v16-9-0[Próximo Capítulo &#62;]