include::./index.adoc[]

[[v16-6-0]]
=== Neemias, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v16-6-1]]

^<<v16-6-1,1>>^ Tendo ouvido Sambalate, Tobias, Gesém, o arábio, e o resto dos nossos inimigos que eu tinha edificado o muro e que nele já não havia brecha nenhuma, ainda que até este tempo não tinha posto as portas nos portais,

[[v16-6-2]]

^<<v16-6-2,2>>^ Sambalate e Gesém mandaram dizer-me: Vem, encontremo-nos, nas aldeias, no vale de Ono. Porém intentavam fazer-me mal.

[[v16-6-3]]

^<<v16-6-3,3>>^ Enviei-lhes mensageiros a dizer: Estou fazendo grande obra, de modo que não poderei descer; por que cessaria a obra, enquanto eu a deixasse e fosse ter convosco?

[[v16-6-4]]

^<<v16-6-4,4>>^ Quatro vezes me enviaram o mesmo pedido; eu, porém, lhes dei sempre a mesma resposta.

[[v16-6-5]]

^<<v16-6-5,5>>^ Então, Sambalate me enviou pela quinta vez o seu moço, o qual trazia na mão uma carta aberta,

[[v16-6-6]]

^<<v16-6-6,6>>^ do teor seguinte: Entre as gentes se ouviu, e Gesém diz que tu e os judeus intentais revoltar-vos; por isso, reedificas o muro, e, segundo se diz, queres ser o rei deles,

[[v16-6-7]]

^<<v16-6-7,7>>^ e puseste profetas para falarem a teu respeito em Jerusalém, dizendo: Este é rei em Judá. Ora, o rei ouvirá isso, segundo essas palavras. Vem, pois, agora, e consultemos juntamente.

[[v16-6-8]]

^<<v16-6-8,8>>^ Mandei dizer-lhe: De tudo o que dizes coisa nenhuma sucedeu; tu, do teu coração, é que o inventas.

[[v16-6-9]]

^<<v16-6-9,9>>^ Porque todos eles procuravam atemorizar-nos, dizendo: As suas mãos largarão a obra, e não se efetuará. Agora, pois, ó Deus, fortalece as minhas mãos.

[[v16-6-10]]

^<<v16-6-10,10>>^ Tendo eu ido à casa de Semaías, filho de Delaías, filho de Meetabel (que estava encerrado), disse ele: Vamos juntamente à Casa de Deus, ao meio do templo, e fechemos as portas do templo; porque virão matar-te; aliás, de noite virão matar-te.

[[v16-6-11]]

^<<v16-6-11,11>>^ Porém eu disse: homem como eu fugiria? E quem há, como eu, que entre no templo para que viva? De maneira nenhuma entrarei.

[[v16-6-12]]

^<<v16-6-12,12>>^ Então, percebi que não era Deus quem o enviara; tal profecia falou ele contra mim, porque Tobias e Sambalate o subornaram.

[[v16-6-13]]

^<<v16-6-13,13>>^ Para isto o subornaram, para me atemorizar, e para que eu, assim, viesse a proceder e a pecar, para que tivessem motivo de me infamar e me vituperassem.

[[v16-6-14]]

^<<v16-6-14,14>>^ Lembra-te, meu Deus, de Tobias e de Sambalate, no tocante a estas suas obras, e também da profetisa Noadia e dos mais profetas que procuraram atemorizar-me.

[[v16-6-15]]

^<<v16-6-15,15>>^ Acabou-se, pois, o muro aos vinte e cinco dias do mês de elul, em cinquenta e dois dias.

[[v16-6-16]]

^<<v16-6-16,16>>^ Sucedeu que, ouvindo-o todos os nossos inimigos, temeram todos os gentios nossos circunvizinhos e decaíram muito no seu próprio conceito; porque reconheceram que por intervenção de nosso Deus é que fizemos esta obra.

[[v16-6-17]]

^<<v16-6-17,17>>^ Também naqueles dias alguns nobres de Judá escreveram muitas cartas, que iam para Tobias, e cartas de Tobias vinham para eles.

[[v16-6-18]]

^<<v16-6-18,18>>^ Pois muitos em Judá lhe eram ajuramentados porque era genro de Secanias, filho de Ará; e seu filho Joanã se casara com a filha de Mesulão, filho de Berequias.

[[v16-6-19]]

^<<v16-6-19,19>>^ Também das suas boas ações falavam na minha presença, e as minhas palavras lhe levavam a ele; Tobias escrevia cartas para me atemorizar.

'''

xref:016-neemias/016-neemias-005.adoc#v16-5-0[&#60; Capítulo Anterior] | <<v16-6-0,Topo>> | xref:016-neemias/016-neemias-007.adoc#v16-7-0[Próximo Capítulo &#62;]