include::./index.adoc[]

[[v16-4-0]]
=== Neemias, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v16-4-1]]

^<<v16-4-1,1>>^ Tendo Sambalate ouvido que edificávamos o muro, ardeu em ira, e se indignou muito, e escarneceu dos judeus.

[[v16-4-2]]

^<<v16-4-2,2>>^ Então, falou na presença de seus irmãos e do exército de Samaria e disse: Que fazem estes fracos judeus? Permitir-se-lhes-á isso? Sacrificarão? Darão cabo da obra num só dia? Renascerão, acaso, dos montões de pó as pedras que foram queimadas?

[[v16-4-3]]

^<<v16-4-3,3>>^ Estava com ele Tobias, o amonita, e disse: Ainda que edifiquem, vindo uma raposa, derribará o seu muro de pedra.

[[v16-4-4]]

^<<v16-4-4,4>>^ Ouve, ó nosso Deus, pois estamos sendo desprezados; caia o seu opróbrio sobre a cabeça deles, e faze que sejam despojo numa terra de cativeiro.

[[v16-4-5]]

^<<v16-4-5,5>>^ Não lhes encubras a iniquidade, e não se risque de diante de ti o seu pecado, pois te provocaram à ira, na presença dos que edificavam.

[[v16-4-6]]

^<<v16-4-6,6>>^ Assim, edificamos o muro, e todo o muro se fechou até a metade de sua altura; porque o povo tinha ânimo para trabalhar.

[[v16-4-7]]

^<<v16-4-7,7>>^ Mas, ouvindo Sambalate e Tobias, os arábios, os amonitas e os asdoditas que a reparação dos muros de Jerusalém ia avante e que já se começavam a fechar-lhe as brechas, ficaram sobremodo irados.

[[v16-4-8]]

^<<v16-4-8,8>>^ Ajuntaram-se todos de comum acordo para virem atacar Jerusalém e suscitar confusão ali.

[[v16-4-9]]

^<<v16-4-9,9>>^ Porém nós oramos ao nosso Deus e, como proteção, pusemos guarda contra eles, de dia e de noite.

[[v16-4-10]]

^<<v16-4-10,10>>^ Então, disse Judá: Já desfaleceram as forças dos carregadores, e os escombros são muitos; de maneira que não podemos edificar o muro.

[[v16-4-11]]

^<<v16-4-11,11>>^ Disseram, porém, os nossos inimigos: Nada saberão disto, nem verão, até que entremos no meio deles e os matemos; assim, faremos cessar a obra.

[[v16-4-12]]

^<<v16-4-12,12>>^ Quando os judeus que habitavam na vizinhança deles, dez vezes, nos disseram: De todos os lugares onde moram, subirão contra nós,

[[v16-4-13]]

^<<v16-4-13,13>>^ então, pus o povo, por famílias, nos lugares baixos e abertos, por detrás do muro, com as suas espadas, e as suas lanças, e os seus arcos;

[[v16-4-14]]

^<<v16-4-14,14>>^ inspecionei, dispus-me e disse aos nobres, aos magistrados e ao resto do povo: não os temais; lembrai-vos do Senhor, grande e temível, e pelejai pelos vossos irmãos, vossos filhos, vossas filhas, vossa mulher e vossa casa.

[[v16-4-15]]

^<<v16-4-15,15>>^ E sucedeu que, ouvindo os nossos inimigos que já o sabíamos e que Deus tinha frustrado o desígnio deles, voltamos todos nós ao muro, cada um à sua obra.

[[v16-4-16]]

^<<v16-4-16,16>>^ Daquele dia em diante, metade dos meus moços trabalhava na obra, e a outra metade empunhava lanças, escudos, arcos e couraças; e os chefes estavam por detrás de toda a casa de Judá;

[[v16-4-17]]

^<<v16-4-17,17>>^ os carregadores, que por si mesmos tomavam as cargas, cada um com uma das mãos fazia a obra e com a outra segurava a arma.

[[v16-4-18]]

^<<v16-4-18,18>>^ Os edificadores, cada um trazia a sua espada à cinta, e assim edificavam; o que tocava a trombeta estava junto de mim.

[[v16-4-19]]

^<<v16-4-19,19>>^ Disse eu aos nobres, aos magistrados e ao resto do povo: Grande e extensa é a obra, e nós estamos no muro mui separados, longe uns dos outros.

[[v16-4-20]]

^<<v16-4-20,20>>^ No lugar em que ouvirdes o som da trombeta, para ali acorrei a ter conosco; o nosso Deus pelejará por nós.

[[v16-4-21]]

^<<v16-4-21,21>>^ Assim trabalhávamos na obra; e metade empunhava as lanças desde o raiar do dia até ao sair das estrelas.

[[v16-4-22]]

^<<v16-4-22,22>>^ Também nesse mesmo tempo disse eu ao povo: Cada um com o seu moço fique em Jerusalém, para que de noite nos sirvam de guarda e de dia trabalhem.

[[v16-4-23]]

^<<v16-4-23,23>>^ Nem eu, nem meus irmãos, nem meus moços, nem os homens da guarda que me seguiam largávamos as nossas vestes; cada um se deitava com as armas à sua direita.

'''

xref:016-neemias/016-neemias-003.adoc#v16-3-0[&#60; Capítulo Anterior] | <<v16-4-0,Topo>> | xref:016-neemias/016-neemias-005.adoc#v16-5-0[Próximo Capítulo &#62;]