include::./index.adoc[]

[[v16-3-0]]
=== Neemias, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v16-3-1]]

^<<v16-3-1,1>>^ Então, se dispôs Eliasibe, o sumo sacerdote, com os sacerdotes, seus irmãos, e reedificaram a Porta das Ovelhas; consagraram-na, assentaram-lhe as portas e continuaram a reconstrução até à Torre dos Cem e à Torre de Hananel.

[[v16-3-2]]

^<<v16-3-2,2>>^ Junto a ele edificaram os homens de Jericó; também, ao seu lado, edificou Zacur, filho de Inri.

[[v16-3-3]]

^<<v16-3-3,3>>^ Os filhos de Hassenaá edificaram a Porta do Peixe; colocaram-lhe as vigas e lhe assentaram as portas com seus ferrolhos e trancas.

[[v16-3-4]]

^<<v16-3-4,4>>^ Ao seu lado, reparou Meremote, filho de Urias, filho de Coz; junto deste reparou Mesulão, filho de Berequias, filho de Mesezabel, a cujo lado reparou Zadoque, filho de Baaná.

[[v16-3-5]]

^<<v16-3-5,5>>^ Ao lado destes, repararam os tecoítas; os seus nobres, porém, não se sujeitaram ao serviço do seu senhor.

[[v16-3-6]]

^<<v16-3-6,6>>^ Joiada, filho de Paseia, e Mesulão, filho de Besodias, repararam a Porta Velha; colocaram-lhe as vigas e lhe assentaram as portas com seus ferrolhos e trancas.

[[v16-3-7]]

^<<v16-3-7,7>>^ Junto deles, trabalharam Melatias, gibeonita, e Jadom, meronotita, homens de Gibeão e de Mispa, que pertenciam ao domínio do governador de além do Eufrates.

[[v16-3-8]]

^<<v16-3-8,8>>^ Ao seu lado, reparou Uziel, filho de Haraías, um dos ourives; junto dele, Hananias, um dos perfumistas; e restauraram Jerusalém até ao Muro Largo.

[[v16-3-9]]

^<<v16-3-9,9>>^ Junto a estes, trabalhou Refaías, filho de Hur, maioral da metade de Jerusalém.

[[v16-3-10]]

^<<v16-3-10,10>>^ Ao seu lado, reparou Jedaías, filho de Harumafe, defronte da sua casa; e, ao seu lado, reparou Hatus, filho de Hasabneias.

[[v16-3-11]]

^<<v16-3-11,11>>^ A outra parte reparou Malquias, filho de Harim, e Hassube, filho de Paate-Moabe, como também a Torre dos Fornos.

[[v16-3-12]]

^<<v16-3-12,12>>^ Ao lado dele, reparou Salum, filho de Haloés, maioral da outra meia parte de Jerusalém, ele e suas filhas.

[[v16-3-13]]

^<<v16-3-13,13>>^ A Porta do Vale, reparou-a Hanum e os moradores de Zanoa; edificaram-na e lhe assentaram as portas com seus ferrolhos e trancas e ainda mil côvados da muralha, até à Porta do Monturo.

[[v16-3-14]]

^<<v16-3-14,14>>^ A Porta do Monturo, reparou-a Malquias, filho de Recabe, maioral do distrito de Bete-Haquerém; ele a edificou e lhe assentou as portas com seus ferrolhos e trancas.

[[v16-3-15]]

^<<v16-3-15,15>>^ A Porta da Fonte, reparou-a Salum, filho de Col-Hozé, maioral do distrito de Mispa; ele a edificou, e a cobriu, e lhe assentou as portas com seus ferrolhos e trancas, e ainda o muro do açude de Selá, junto ao jardim do rei, até aos degraus que descem da Cidade de Davi.

[[v16-3-16]]

^<<v16-3-16,16>>^ Depois dele, reparou Neemias, filho de Azbuque, maioral da metade do distrito de Bete-Zur, até defronte dos sepulcros de Davi, até ao açude artificial e até à casa dos heróis.

[[v16-3-17]]

^<<v16-3-17,17>>^ Depois dele, repararam os levitas, Reum, filho de Bani, e, ao seu lado, Hasabias, maioral da metade do distrito de Queila.

[[v16-3-18]]

^<<v16-3-18,18>>^ Depois dele, repararam seus irmãos: Bavai, filho de Henadade, maioral da metade do distrito de Queila;

[[v16-3-19]]

^<<v16-3-19,19>>^ ao seu lado, reparou Ezer, filho de Jesua, maioral de Mispa, outra parte defronte da subida para a casa das armas, no ângulo do muro.

[[v16-3-20]]

^<<v16-3-20,20>>^ Depois dele, reparou com grande ardor Baruque, filho de Zabai, outra porção, desde o ângulo do muro até à porta da casa de Eliasibe, o sumo sacerdote.

[[v16-3-21]]

^<<v16-3-21,21>>^ Depois dele, reparou Meremote, filho de Urias, filho de Coz, outra porção, desde a porta da casa de Eliasibe até à extremidade da casa de Eliasibe.

[[v16-3-22]]

^<<v16-3-22,22>>^ Depois dele, repararam os sacerdotes que habitavam na campina.

[[v16-3-23]]

^<<v16-3-23,23>>^ Depois, repararam Benjamim e Hassube, defronte da sua casa; depois deles, reparou Azarias, filho de Maaseias, filho de Ananias, junto à sua casa.

[[v16-3-24]]

^<<v16-3-24,24>>^ Depois dele, reparou Binui, filho de Henadade, outra porção, desde a casa de Azarias até ao ângulo e até à esquina.

[[v16-3-25]]

^<<v16-3-25,25>>^ Palal, filho de Uzai, reparou defronte do ângulo e da torre que sai da casa real superior, que está junto ao pátio do cárcere; depois dele, reparou Pedaías, filho de Parós,

[[v16-3-26]]

^<<v16-3-26,26>>^ e os servos do templo que habitavam em Ofel, até defronte da Porta das Águas, para o oriente, e até à torre alta.

[[v16-3-27]]

^<<v16-3-27,27>>^ Depois, repararam os tecoítas outra porção, defronte da torre grande e alta, e até ao Muro de Ofel.

[[v16-3-28]]

^<<v16-3-28,28>>^ Para cima da Porta dos Cavalos, repararam os sacerdotes, cada um defronte da sua casa.

[[v16-3-29]]

^<<v16-3-29,29>>^ Depois deles, reparou Zadoque, filho de Imer, defronte de sua casa; e, depois dele, Semaías, filho de Secanias, guarda da Porta Oriental.

[[v16-3-30]]

^<<v16-3-30,30>>^ Depois dele, reparou Hananias, filho de Selemias, e Hanum, o sexto filho de Zalafe, outra porção; depois deles, reparou Mesulão, filho de Berequias, defronte da sua morada.

[[v16-3-31]]

^<<v16-3-31,31>>^ Depois dele, reparou Malquias, filho de um ourives, até à casa dos servos do templo e dos mercadores, defronte da Porta da Guarda, até ao eirado da esquina.

[[v16-3-32]]

^<<v16-3-32,32>>^ Entre o eirado da esquina e a Porta das Ovelhas, repararam os ourives e os mercadores.

'''

xref:016-neemias/016-neemias-002.adoc#v16-2-0[&#60; Capítulo Anterior] | <<v16-3-0,Topo>> | xref:016-neemias/016-neemias-004.adoc#v16-4-0[Próximo Capítulo &#62;]