include::./index.adoc[]

[[v16-2-0]]
=== Neemias, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v16-2-1]]

^<<v16-2-1,1>>^ No mês de nisã, no ano vigésimo do rei Artaxerxes, uma vez posto o vinho diante dele, eu o tomei para oferecer e lho dei; ora, eu nunca antes estivera triste diante dele.

[[v16-2-2]]

^<<v16-2-2,2>>^ O rei me disse: Por que está triste o teu rosto, se não estás doente? Tem de ser tristeza do coração. Então, temi sobremaneira

[[v16-2-3]]

^<<v16-2-3,3>>^ e lhe respondi: viva o rei para sempre! Como não me estaria triste o rosto se a cidade, onde estão os sepulcros de meus pais, está assolada e tem as portas consumidas pelo fogo?

[[v16-2-4]]

^<<v16-2-4,4>>^ Disse-me o rei: Que me pedes agora? Então, orei ao Deus dos céus

[[v16-2-5]]

^<<v16-2-5,5>>^ e disse ao rei: se é do agrado do rei, e se o teu servo acha mercê em tua presença, peço-te que me envies a Judá, à cidade dos sepulcros de meus pais, para que eu a reedifique.

[[v16-2-6]]

^<<v16-2-6,6>>^ Então, o rei, estando a rainha assentada junto dele, me disse: Quanto durará a tua ausência? Quando voltarás? Aprouve ao rei enviar-me, e marquei certo prazo.

[[v16-2-7]]

^<<v16-2-7,7>>^ E ainda disse ao rei: Se ao rei parece bem, deem-se-me cartas para os governadores dalém do Eufrates, para que me permitam passar e entrar em Judá,

[[v16-2-8]]

^<<v16-2-8,8>>^ como também carta para Asafe, guarda das matas do rei, para que me dê madeira para as vigas das portas da cidadela do templo, para os muros da cidade e para a casa em que deverei alojar-me. E o rei mas deu, porque a boa mão do meu Deus era comigo.

[[v16-2-9]]

^<<v16-2-9,9>>^ Então, fui aos governadores dalém do Eufrates e lhes entreguei as cartas do rei; ora, o rei tinha enviado comigo oficiais do exército e cavaleiros.

[[v16-2-10]]

^<<v16-2-10,10>>^ Disto ficaram sabendo Sambalate, o horonita, e Tobias, o servo amonita; e muito lhes desagradou que alguém viesse a procurar o bem dos filhos de Israel.

[[v16-2-11]]

^<<v16-2-11,11>>^ Cheguei a Jerusalém, onde estive três dias.

[[v16-2-12]]

^<<v16-2-12,12>>^ Então, à noite me levantei, e uns poucos homens, comigo; não declarei a ninguém o que o meu Deus me pusera no coração para eu fazer em Jerusalém. Não havia comigo animal algum, senão o que eu montava.

[[v16-2-13]]

^<<v16-2-13,13>>^ De noite, saí pela Porta do Vale, para o lado da Fonte do Dragão e para a Porta do Monturo e contemplei os muros de Jerusalém, que estavam assolados, cujas portas tinham sido consumidas pelo fogo.

[[v16-2-14]]

^<<v16-2-14,14>>^ Passei à Porta da Fonte e ao açude do rei; mas não havia lugar por onde passasse o animal que eu montava.

[[v16-2-15]]

^<<v16-2-15,15>>^ Subi à noite pelo ribeiro e contemplei ainda os muros; voltei, entrei pela Porta do Vale e tornei para casa.

[[v16-2-16]]

^<<v16-2-16,16>>^ Não sabiam os magistrados aonde eu fora nem o que fazia, pois até aqui não havia eu declarado coisa alguma, nem aos judeus, nem aos sacerdotes, nem aos nobres, nem aos magistrados, nem aos mais que faziam a obra.

[[v16-2-17]]

^<<v16-2-17,17>>^ Então, lhes disse: Estais vendo a miséria em que estamos, Jerusalém assolada, e as suas portas, queimadas; vinde, pois, reedifiquemos os muros de Jerusalém e deixemos de ser opróbrio.

[[v16-2-18]]

^<<v16-2-18,18>>^ E lhes declarei como a boa mão do meu Deus estivera comigo e também as palavras que o rei me falara. Então, disseram: Disponhamo-nos e edifiquemos. E fortaleceram as mãos para a boa obra.

[[v16-2-19]]

^<<v16-2-19,19>>^ Porém Sambalate, o horonita, e Tobias, o servo amonita, e Gesém, o arábio, quando o souberam, zombaram de nós, e nos desprezaram, e disseram: Que é isso que fazeis? Quereis rebelar-vos contra o rei?

[[v16-2-20]]

^<<v16-2-20,20>>^ Então, lhes respondi: o Deus dos céus é quem nos dará bom êxito; nós, seus servos, nos disporemos e reedificaremos; vós, todavia, não tendes parte, nem direito, nem memorial em Jerusalém.

'''

xref:016-neemias/016-neemias-001.adoc#v16-1-0[&#60; Capítulo Anterior] | <<v16-2-0,Topo>> | xref:016-neemias/016-neemias-003.adoc#v16-3-0[Próximo Capítulo &#62;]