include::./index.adoc[]

[[v16-1-0]]
=== Neemias, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v16-1-1]]

^<<v16-1-1,1>>^ As palavras de Neemias, filho de Hacalias. No mês de quisleu, no ano vigésimo, estando eu na cidadela de Susã,

[[v16-1-2]]

^<<v16-1-2,2>>^ veio Hanani, um de meus irmãos, com alguns de Judá; então, lhes perguntei pelos judeus que escaparam e que não foram levados para o exílio e acerca de Jerusalém.

[[v16-1-3]]

^<<v16-1-3,3>>^ Disseram-me: Os restantes, que não foram levados para o exílio e se acham lá na província, estão em grande miséria e desprezo; os muros de Jerusalém estão derribados, e as suas portas, queimadas.

[[v16-1-4]]

^<<v16-1-4,4>>^ Tendo eu ouvido estas palavras, assentei-me, e chorei, e lamentei por alguns dias; e estive jejuando e orando perante o Deus dos céus.

[[v16-1-5]]

^<<v16-1-5,5>>^ E disse: ah! SENHOR, Deus dos céus, Deus grande e temível, que guardas a aliança e a misericórdia para com aqueles que te amam e guardam os teus mandamentos!

[[v16-1-6]]

^<<v16-1-6,6>>^ Estejam, pois, atentos os teus ouvidos, e os teus olhos, abertos, para acudires à oração do teu servo, que hoje faço à tua presença, dia e noite, pelos filhos de Israel, teus servos; e faço confissão pelos pecados dos filhos de Israel, os quais temos cometido contra ti; pois eu e a casa de meu pai temos pecado.

[[v16-1-7]]

^<<v16-1-7,7>>^ Temos procedido de todo corruptamente contra ti, não temos guardado os mandamentos, nem os estatutos, nem os juízos que ordenaste a Moisés, teu servo.

[[v16-1-8]]

^<<v16-1-8,8>>^ Lembra-te da palavra que ordenaste a Moisés, teu servo, dizendo: Se transgredirdes, eu vos espalharei por entre os povos;

[[v16-1-9]]

^<<v16-1-9,9>>^ mas, se vos converterdes a mim, e guardardes os meus mandamentos, e os cumprirdes, então, ainda que os vossos rejeitados estejam pelas extremidades do céu, de lá os ajuntarei e os trarei para o lugar que tenho escolhido para ali fazer habitar o meu nome.

[[v16-1-10]]

^<<v16-1-10,10>>^ Estes ainda são teus servos e o teu povo que resgataste com teu grande poder e com tua mão poderosa.

[[v16-1-11]]

^<<v16-1-11,11>>^ Ah! Senhor, estejam, pois, atentos os teus ouvidos à oração do teu servo e à dos teus servos que se agradam de temer o teu nome; concede que seja bem-sucedido hoje o teu servo e dá-lhe mercê perante este homem. Nesse tempo eu era copeiro do rei.

'''

xref:015-esdras/015-esdras-010.adoc#v15-10-0[&#60; Capítulo Anterior] | <<v16-1-0,Topo>> | xref:016-neemias/016-neemias-002.adoc#v16-2-0[Próximo Capítulo &#62;]