include::./index.adoc[]

[[v4-20-0]]
=== Números, 20
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-20-1]]

^<<v4-20-1,1>>^ Chegando os filhos de Israel, toda a congregação, ao deserto de Zim, no mês primeiro, o povo ficou em Cades. Ali, morreu Miriã e, ali, foi sepultada.

[[v4-20-2]]

^<<v4-20-2,2>>^ Não havia água para o povo; então, se ajuntaram contra Moisés e contra Arão.

[[v4-20-3]]

^<<v4-20-3,3>>^ E o povo contendeu com Moisés, e disseram: Antes tivéssemos perecido quando expiraram nossos irmãos perante o SENHOR!

[[v4-20-4]]

^<<v4-20-4,4>>^ Por que trouxestes a congregação do SENHOR a este deserto, para morrermos aí, nós e os nossos animais?

[[v4-20-5]]

^<<v4-20-5,5>>^ E por que nos fizestes subir do Egito, para nos trazer a este mau lugar, que não é de cereais, nem de figos, nem de vides, nem de romãs, nem de água para beber?

[[v4-20-6]]

^<<v4-20-6,6>>^ Então, Moisés e Arão se foram de diante do povo para a porta da tenda da congregação e se lançaram sobre o seu rosto; e a glória do SENHOR lhes apareceu.

[[v4-20-7]]

^<<v4-20-7,7>>^ Disse o SENHOR a Moisés:

[[v4-20-8]]

^<<v4-20-8,8>>^ Toma o bordão, ajunta o povo, tu e Arão, teu irmão, e, diante dele, falai à rocha, e dará a sua água; assim lhe tirareis água da rocha e dareis a beber à congregação e aos seus animais.

[[v4-20-9]]

^<<v4-20-9,9>>^ Então, Moisés tomou o bordão de diante do SENHOR, como lhe tinha ordenado.

[[v4-20-10]]

^<<v4-20-10,10>>^ Moisés e Arão reuniram o povo diante da rocha, e Moisés lhe disse: Ouvi, agora, rebeldes: porventura, faremos sair água desta rocha para vós outros?

[[v4-20-11]]

^<<v4-20-11,11>>^ Moisés levantou a mão e feriu a rocha duas vezes com o seu bordão, e saíram muitas águas; e bebeu a congregação e os seus animais.

[[v4-20-12]]

^<<v4-20-12,12>>^ Mas o SENHOR disse a Moisés e a Arão: Visto que não crestes em mim, para me santificardes diante dos filhos de Israel, por isso, não fareis entrar este povo na terra que lhe dei.

[[v4-20-13]]

^<<v4-20-13,13>>^ São estas as águas de Meribá, porque os filhos de Israel contenderam com o SENHOR; e o SENHOR se santificou neles.

[[v4-20-14]]

^<<v4-20-14,14>>^ Enviou Moisés, de Cades, mensageiros ao rei de Edom, a dizer-lhe: Assim diz teu irmão Israel: Bem sabes todo o trabalho que nos tem sobrevindo;

[[v4-20-15]]

^<<v4-20-15,15>>^ como nossos pais desceram ao Egito, e nós no Egito habitamos muito tempo, e como os egípcios nos maltrataram, a nós e a nossos pais;

[[v4-20-16]]

^<<v4-20-16,16>>^ e clamamos ao SENHOR, e ele ouviu a nossa voz, e mandou o Anjo, e nos tirou do Egito. E eis que estamos em Cades, cidade nos confins do teu país.

[[v4-20-17]]

^<<v4-20-17,17>>^ Deixa-nos passar pela tua terra; não o faremos pelo campo, nem pelas vinhas, nem beberemos a água dos poços; iremos pela estrada real; não nos desviaremos para a direita nem para a esquerda, até que passemos pelo teu país.

[[v4-20-18]]

^<<v4-20-18,18>>^ Porém Edom lhe disse: Não passarás por mim, para que não saia eu de espada ao teu encontro.

[[v4-20-19]]

^<<v4-20-19,19>>^ Então, os filhos de Israel lhe disseram: Subiremos pelo caminho trilhado, e, se eu e o meu gado bebermos das tuas águas, pagarei o preço delas; outra coisa não desejo senão passar a pé.

[[v4-20-20]]

^<<v4-20-20,20>>^ Porém ele disse: Não passarás. E saiu-lhe Edom ao encontro, com muita gente e com mão forte.

[[v4-20-21]]

^<<v4-20-21,21>>^ Assim recusou Edom deixar passar a Israel pelo seu país; pelo que Israel se desviou dele.

[[v4-20-22]]

^<<v4-20-22,22>>^ Então, partiram de Cades; e os filhos de Israel, toda a congregação, foram ao monte Hor.

[[v4-20-23]]

^<<v4-20-23,23>>^ Disse o SENHOR a Moisés e a Arão no monte Hor, nos confins da terra de Edom:

[[v4-20-24]]

^<<v4-20-24,24>>^ Arão será recolhido a seu povo, porque não entrará na terra que dei aos filhos de Israel, pois fostes rebeldes à minha palavra, nas águas de Meribá.

[[v4-20-25]]

^<<v4-20-25,25>>^ Toma Arão e Eleazar, seu filho, e faze-os subir ao monte Hor;

[[v4-20-26]]

^<<v4-20-26,26>>^ depois, despe Arão das suas vestes e veste com elas a Eleazar, seu filho; porque Arão será recolhido a seu povo e aí morrerá.

[[v4-20-27]]

^<<v4-20-27,27>>^ Fez Moisés como o SENHOR lhe ordenara; subiram ao monte Hor, perante os olhos de toda a congregação.

[[v4-20-28]]

^<<v4-20-28,28>>^ Moisés, pois, despiu a Arão de suas vestes e vestiu com elas a Eleazar, seu filho; morreu Arão ali sobre o cimo do monte; e dali desceram Moisés e Eleazar.

[[v4-20-29]]

^<<v4-20-29,29>>^ Vendo, pois, toda a congregação que Arão era morto, choraram por Arão trinta dias, isto é, toda a casa de Israel.

'''

xref:004-numeros/004-numeros-019.adoc#v4-19-0[&#60; Capítulo Anterior] | <<v4-20-0,Topo>> | xref:004-numeros/004-numeros-021.adoc#v4-21-0[Próximo Capítulo &#62;]