include::./index.adoc[]

[[v4-14-0]]
=== Números, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-14-1]]

^<<v4-14-1,1>>^ Levantou-se, pois, toda a congregação e gritou em voz alta; e o povo chorou aquela noite.

[[v4-14-2]]

^<<v4-14-2,2>>^ Todos os filhos de Israel murmuraram contra Moisés e contra Arão; e toda a congregação lhes disse: Tomara tivéssemos morrido na terra do Egito ou mesmo neste deserto!

[[v4-14-3]]

^<<v4-14-3,3>>^ E por que nos traz o SENHOR a esta terra, para cairmos à espada e para que nossas mulheres e nossas crianças sejam por presa? Não nos seria melhor voltarmos para o Egito?

[[v4-14-4]]

^<<v4-14-4,4>>^ E diziam uns aos outros: Levantemos um capitão e voltemos para o Egito.

[[v4-14-5]]

^<<v4-14-5,5>>^ Então, Moisés e Arão caíram sobre o seu rosto perante a congregação dos filhos de Israel.

[[v4-14-6]]

^<<v4-14-6,6>>^ E Josué, filho de Num, e Calebe, filho de Jefoné, dentre os que espiaram a terra, rasgaram as suas vestes

[[v4-14-7]]

^<<v4-14-7,7>>^ e falaram a toda a congregação dos filhos de Israel, dizendo: A terra pelo meio da qual passamos a espiar é terra muitíssimo boa.

[[v4-14-8]]

^<<v4-14-8,8>>^ Se o SENHOR se agradar de nós, então, nos fará entrar nessa terra e no-la dará, terra que mana leite e mel.

[[v4-14-9]]

^<<v4-14-9,9>>^ Tão somente não sejais rebeldes contra o SENHOR e não temais o povo dessa terra, porquanto, como pão, os podemos devorar; retirou-se deles o seu amparo; o SENHOR é conosco; não os temais.

[[v4-14-10]]

^<<v4-14-10,10>>^ Apesar disso, toda a congregação disse que os apedrejassem; porém a glória do SENHOR apareceu na tenda da congregação a todos os filhos de Israel.

[[v4-14-11]]

^<<v4-14-11,11>>^ Disse o SENHOR a Moisés: Até quando me provocará este povo e até quando não crerá em mim, a despeito de todos os sinais que fiz no meio dele?

[[v4-14-12]]

^<<v4-14-12,12>>^ Com pestilência o ferirei e o deserdarei; e farei de ti povo maior e mais forte do que este.

[[v4-14-13]]

^<<v4-14-13,13>>^ Respondeu Moisés ao SENHOR: Os egípcios não somente ouviram que, com a tua força, fizeste subir este povo do meio deles,

[[v4-14-14]]

^<<v4-14-14,14>>^ mas também o disseram aos moradores desta terra; ouviram que tu, ó SENHOR, estás no meio deste povo, que face a face, ó SENHOR, lhes apareces, tua nuvem está sobre eles, e vais adiante deles numa coluna de nuvem, de dia, e, numa coluna de fogo, de noite.

[[v4-14-15]]

^<<v4-14-15,15>>^ Se matares este povo como a um só homem, as gentes, pois, que, antes, ouviram a tua fama, dirão:

[[v4-14-16]]

^<<v4-14-16,16>>^ Não podendo o SENHOR fazer entrar este povo na terra que lhe prometeu com juramento, os matou no deserto.

[[v4-14-17]]

^<<v4-14-17,17>>^ Agora, pois, rogo-te que a força do meu Senhor se engrandeça, como tens falado, dizendo:

[[v4-14-18]]

^<<v4-14-18,18>>^ O SENHOR é longânimo e grande em misericórdia, que perdoa a iniquidade e a transgressão, ainda que não inocenta o culpado, e visita a iniquidade dos pais nos filhos até à terceira e quarta gerações.

[[v4-14-19]]

^<<v4-14-19,19>>^ Perdoa, pois, a iniquidade deste povo, segundo a grandeza da tua misericórdia e como também tens perdoado a este povo desde a terra do Egito até aqui.

[[v4-14-20]]

^<<v4-14-20,20>>^ Tornou-lhe o SENHOR: Segundo a tua palavra, eu lhe perdoei.

[[v4-14-21]]

^<<v4-14-21,21>>^ Porém, tão certo como eu vivo, e como toda a terra se encherá da glória do SENHOR,

[[v4-14-22]]

^<<v4-14-22,22>>^ nenhum dos homens que, tendo visto a minha glória e os prodígios que fiz no Egito e no deserto, todavia, me puseram à prova já dez vezes e não obedeceram à minha voz,

[[v4-14-23]]

^<<v4-14-23,23>>^ nenhum deles verá a terra que, com juramento, prometi a seus pais, sim, nenhum daqueles que me desprezaram a verá.

[[v4-14-24]]

^<<v4-14-24,24>>^ Porém o meu servo Calebe, visto que nele houve outro espírito, e perseverou em seguir-me, eu o farei entrar a terra que espiou, e a sua descendência a possuirá.

[[v4-14-25]]

^<<v4-14-25,25>>^ Ora, os amalequitas e os cananeus habitam no vale; mudai, amanhã, de rumo e caminhai para o deserto, pelo caminho do mar Vermelho.

[[v4-14-26]]

^<<v4-14-26,26>>^ Depois, disse o SENHOR a Moisés e a Arão:

[[v4-14-27]]

^<<v4-14-27,27>>^ Até quando sofrerei esta má congregação que murmura contra mim? Tenho ouvido as murmurações que os filhos de Israel proferem contra mim.

[[v4-14-28]]

^<<v4-14-28,28>>^ Dize-lhes: Por minha vida, diz o SENHOR, que, como falastes aos meus ouvidos, assim farei a vós outros.

[[v4-14-29]]

^<<v4-14-29,29>>^ Neste deserto, cairá o vosso cadáver, como também todos os que de vós foram contados segundo o censo, de vinte anos para cima, os que dentre vós contra mim murmurastes;

[[v4-14-30]]

^<<v4-14-30,30>>^ não entrareis na terra a respeito da qual jurei que vos faria habitar nela, salvo Calebe, filho de Jefoné, e Josué, filho de Num.

[[v4-14-31]]

^<<v4-14-31,31>>^ Mas os vossos filhos, de que dizeis: Por presa serão, farei entrar nela; e eles conhecerão a terra que vós desprezastes.

[[v4-14-32]]

^<<v4-14-32,32>>^ Porém, quanto a vós outros, o vosso cadáver cairá neste deserto.

[[v4-14-33]]

^<<v4-14-33,33>>^ Vossos filhos serão pastores neste deserto quarenta anos e levarão sobre si as vossas infidelidades, até que o vosso cadáver se consuma neste deserto.

[[v4-14-34]]

^<<v4-14-34,34>>^ Segundo o número dos dias em que espiastes a terra, quarenta dias, cada dia representando um ano, levareis sobre vós as vossas iniquidades quarenta anos e tereis experiência do meu desagrado.

[[v4-14-35]]

^<<v4-14-35,35>>^ Eu, o SENHOR, falei; assim farei a toda esta má congregação, que se levantou contra mim; neste deserto, se consumirão e aí falecerão.

[[v4-14-36]]

^<<v4-14-36,36>>^ Os homens que Moisés mandara a espiar a terra e que, voltando, fizeram murmurar toda a congregação contra ele, infamando a terra,

[[v4-14-37]]

^<<v4-14-37,37>>^ esses mesmos homens que infamaram a terra morreram de praga perante o SENHOR.

[[v4-14-38]]

^<<v4-14-38,38>>^ Mas Josué, filho de Num, e Calebe, filho de Jefoné, que eram dos homens que foram espiar a terra, sobreviveram.

[[v4-14-39]]

^<<v4-14-39,39>>^ Falou Moisés estas palavras a todos os filhos de Israel, e o povo se contristou muito.

[[v4-14-40]]

^<<v4-14-40,40>>^ Levantaram-se pela manhã de madrugada e subiram ao cimo do monte, dizendo: Eis-nos aqui e subiremos ao lugar que o SENHOR tem prometido, porquanto havemos pecado.

[[v4-14-41]]

^<<v4-14-41,41>>^ Porém Moisés respondeu: Por que transgredis o mandado do SENHOR? Pois isso não prosperará.

[[v4-14-42]]

^<<v4-14-42,42>>^ Não subais, pois o SENHOR não estará no meio de vós, para que não sejais feridos diante dos vossos inimigos.

[[v4-14-43]]

^<<v4-14-43,43>>^ Porque os amalequitas e os cananeus ali estão diante de vós, e caireis à espada; pois, uma vez que vos desviastes do SENHOR, o SENHOR não será convosco.

[[v4-14-44]]

^<<v4-14-44,44>>^ Contudo, temerariamente, tentaram subir ao cimo do monte, mas a arca da Aliança do SENHOR e Moisés não se apartaram do meio do arraial.

[[v4-14-45]]

^<<v4-14-45,45>>^ Então, desceram os amalequitas e os cananeus que habitavam na montanha e os feriram, derrotando-os até Horma.

'''

xref:004-numeros/004-numeros-013.adoc#v4-13-0[&#60; Capítulo Anterior] | <<v4-14-0,Topo>> | xref:004-numeros/004-numeros-015.adoc#v4-15-0[Próximo Capítulo &#62;]