include::./index.adoc[]

[[v4-17-0]]
=== Números, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-17-1]]

^<<v4-17-1,1>>^ Disse o SENHOR a Moisés:

[[v4-17-2]]

^<<v4-17-2,2>>^ Fala aos filhos de Israel e recebe deles bordões, um pela casa de cada pai de todos os seus príncipes, segundo as casas de seus pais, isto é, doze bordões; escreve o nome de cada um sobre o seu bordão.

[[v4-17-3]]

^<<v4-17-3,3>>^ Porém o nome de Arão escreverás sobre o bordão de Levi; porque cada cabeça da casa de seus pais terá um bordão.

[[v4-17-4]]

^<<v4-17-4,4>>^ E os porás na tenda da congregação, perante o Testemunho, onde eu vos encontrarei.

[[v4-17-5]]

^<<v4-17-5,5>>^ O bordão do homem que eu escolher, esse florescerá; assim, farei cessar de sobre mim as murmurações que os filhos de Israel proferem contra vós.

[[v4-17-6]]

^<<v4-17-6,6>>^ Falou, pois, Moisés aos filhos de Israel, e todos os seus príncipes lhe deram bordões; cada um lhe deu um, segundo as casas de seus pais: doze bordões; e, entre eles, o bordão de Arão.

[[v4-17-7]]

^<<v4-17-7,7>>^ Moisés pôs estes bordões perante o SENHOR, na tenda do Testemunho.

[[v4-17-8]]

^<<v4-17-8,8>>^ No dia seguinte, Moisés entrou na tenda do Testemunho, e eis que o bordão de Arão, pela casa de Levi, brotara, e, tendo inchado os gomos, produzira flores, e dava amêndoas.

[[v4-17-9]]

^<<v4-17-9,9>>^ Então, Moisés trouxe todos os bordões de diante do SENHOR a todos os filhos de Israel; e eles o viram, e tomou cada um o seu bordão.

[[v4-17-10]]

^<<v4-17-10,10>>^ Disse o SENHOR a Moisés: Torna a pôr o bordão de Arão perante o Testemunho, para que se guarde por sinal para filhos rebeldes; assim farás acabar as suas murmurações contra mim, para que não morram.

[[v4-17-11]]

^<<v4-17-11,11>>^ E Moisés fez assim; como lhe ordenara o SENHOR, assim fez.

[[v4-17-12]]

^<<v4-17-12,12>>^ Então, falaram os filhos de Israel a Moisés, dizendo: Eis que expiramos, perecemos, perecemos todos.

[[v4-17-13]]

^<<v4-17-13,13>>^ Todo aquele que se aproximar do tabernáculo do SENHOR morrerá; acaso, expiraremos todos?

'''

xref:004-numeros/004-numeros-016.adoc#v4-16-0[&#60; Capítulo Anterior] | <<v4-17-0,Topo>> | xref:004-numeros/004-numeros-018.adoc#v4-18-0[Próximo Capítulo &#62;]