include::./index.adoc[]

[[v4-18-0]]
=== Números, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-18-1]]

^<<v4-18-1,1>>^ Disse o SENHOR a Arão: Tu, e teus filhos, e a casa de teu pai contigo levareis sobre vós a iniquidade relativamente ao santuário; tu e teus filhos contigo levareis sobre vós a iniquidade relativamente ao vosso sacerdócio.

[[v4-18-2]]

^<<v4-18-2,2>>^ Também farás chegar contigo a teus irmãos, a tribo de Levi, a tribo de teu pai, para que se ajuntem a ti e te sirvam, quando tu e teus filhos contigo estiverdes perante a tenda do Testemunho.

[[v4-18-3]]

^<<v4-18-3,3>>^ Farão o serviço que lhes é devido para contigo e para com a tenda; porém não se aproximarão dos utensílios do santuário, nem do altar, para que não morram, nem eles, nem vós.

[[v4-18-4]]

^<<v4-18-4,4>>^ Ajuntar-se-ão a ti e farão todo o serviço da tenda da congregação; o estranho, porém, não se chegará a vós outros.

[[v4-18-5]]

^<<v4-18-5,5>>^ Vós, pois, fareis o serviço do santuário e o do altar, para que não haja outra vez ira contra os filhos de Israel.

[[v4-18-6]]

^<<v4-18-6,6>>^ Eu, eis que tomei vossos irmãos, os levitas, do meio dos filhos de Israel; são dados a vós outros para o SENHOR, para servir na tenda da congregação.

[[v4-18-7]]

^<<v4-18-7,7>>^ Mas tu e teus filhos contigo atendereis ao vosso sacerdócio em tudo concernente ao altar, e ao que estiver para dentro do véu, isto é vosso serviço; eu vos tenho entregue o vosso sacerdócio por ofício como dádiva; porém o estranho que se aproximar morrerá.

[[v4-18-8]]

^<<v4-18-8,8>>^ Disse mais o SENHOR a Arão: Eis que eu te dei o que foi separado das minhas ofertas, com todas as coisas consagradas dos filhos de Israel; dei-as por direito perpétuo como porção a ti e a teus filhos.

[[v4-18-9]]

^<<v4-18-9,9>>^ Isto terás das coisas santíssimas, não dadas ao fogo: todas as suas ofertas, com todas as suas ofertas de manjares, e com todas as suas ofertas pelo pecado, e com todas as suas ofertas pela culpa, que me apresentarem, serão coisas santíssimas para ti e para teus filhos.

[[v4-18-10]]

^<<v4-18-10,10>>^ No lugar santíssimo, o comerás; todo homem o comerá; ser-te-á santo.

[[v4-18-11]]

^<<v4-18-11,11>>^ Também isto será teu: a oferta das suas dádivas com todas as ofertas movidas dos filhos de Israel; a ti, a teus filhos e a tuas filhas contigo, dei-as por direito perpétuo; todo o que estiver limpo na tua casa as comerá.

[[v4-18-12]]

^<<v4-18-12,12>>^ Todo o melhor do azeite, do mosto e dos cereais, as suas primícias que derem ao SENHOR, dei-as a ti.

[[v4-18-13]]

^<<v4-18-13,13>>^ Os primeiros frutos de tudo que houver na terra, que trouxerem ao SENHOR, serão teus; todo o que estiver limpo na tua casa os comerá.

[[v4-18-14]]

^<<v4-18-14,14>>^ Toda coisa consagrada irremissivelmente em Israel será tua.

[[v4-18-15]]

^<<v4-18-15,15>>^ Todo o que abrir a madre, de todo ser vivente, que trouxerem ao SENHOR, tanto de homens como de animais, será teu; porém os primogênitos dos homens resgatarás; também os primogênitos dos animais imundos resgatarás.

[[v4-18-16]]

^<<v4-18-16,16>>^ O resgate, pois (desde a idade de um mês os resgatarás), será segundo a tua avaliação, por cinco siclos de dinheiro, segundo o siclo do santuário, que é de vinte geras.

[[v4-18-17]]

^<<v4-18-17,17>>^ Mas o primogênito do gado, ou primogênito de ovelhas, ou primogênito de cabra não resgatarás; são santos; o seu sangue aspergirás sobre o altar e a sua gordura queimarás em oferta queimada de aroma agradável ao SENHOR.

[[v4-18-18]]

^<<v4-18-18,18>>^ A carne deles será tua, assim como será teu o peito movido e a coxa direita.

[[v4-18-19]]

^<<v4-18-19,19>>^ Todas as ofertas sagradas, que os filhos de Israel oferecerem ao SENHOR, dei-as a ti, e a teus filhos, e a tuas filhas contigo, por direito perpétuo; aliança perpétua de sal perante o SENHOR é esta, para ti e para tua descendência contigo.

[[v4-18-20]]

^<<v4-18-20,20>>^ Disse também o SENHOR a Arão: Na sua terra, herança nenhuma terás e, no meio deles, nenhuma porção terás. Eu sou a tua porção e a tua herança no meio dos filhos de Israel.

[[v4-18-21]]

^<<v4-18-21,21>>^ Aos filhos de Levi dei todos os dízimos em Israel por herança, pelo serviço que prestam, serviço da tenda da congregação.

[[v4-18-22]]

^<<v4-18-22,22>>^ E nunca mais os filhos de Israel se chegarão à tenda da congregação, para que não levem sobre si o pecado e morram.

[[v4-18-23]]

^<<v4-18-23,23>>^ Mas os levitas farão o serviço da tenda da congregação e responderão por suas faltas; estatuto perpétuo é este para todas as vossas gerações. E não terão eles nenhuma herança no meio dos filhos de Israel.

[[v4-18-24]]

^<<v4-18-24,24>>^ Porque os dízimos dos filhos de Israel, que apresentam ao SENHOR em oferta, dei-os por herança aos levitas; porquanto eu lhes disse: No meio dos filhos de Israel, nenhuma herança tereis.

[[v4-18-25]]

^<<v4-18-25,25>>^ Disse o SENHOR a Moisés:

[[v4-18-26]]

^<<v4-18-26,26>>^ Também falarás aos levitas e lhes dirás: Quando receberdes os dízimos da parte dos filhos de Israel, que vos dei por vossa herança, deles apresentareis uma oferta ao SENHOR: o dízimo dos dízimos.

[[v4-18-27]]

^<<v4-18-27,27>>^ Atribuir-se-vos-á a vossa oferta como se fosse cereal da eira e plenitude do lagar.

[[v4-18-28]]

^<<v4-18-28,28>>^ Assim, também apresentareis ao SENHOR uma oferta de todos os vossos dízimos que receberdes dos filhos de Israel e deles dareis a oferta do SENHOR a Arão, o sacerdote.

[[v4-18-29]]

^<<v4-18-29,29>>^ De todas as vossas dádivas apresentareis toda oferta do SENHOR: do melhor delas, a parte que lhe é sagrada.

[[v4-18-30]]

^<<v4-18-30,30>>^ Portanto, lhes dirás: Quando oferecerdes o melhor que há nos dízimos, o restante destes, como se fosse produto da eira e produto do lagar, se contará aos levitas.

[[v4-18-31]]

^<<v4-18-31,31>>^ Comê-lo-eis em todo lugar, vós e a vossa casa, porque é vossa recompensa pelo vosso serviço na tenda da congregação.

[[v4-18-32]]

^<<v4-18-32,32>>^ Pelo que não levareis sobre vós o pecado, quando deles oferecerdes o melhor; e não profanareis as coisas sagradas dos filhos de Israel, para que não morrais.

'''

xref:004-numeros/004-numeros-017.adoc#v4-17-0[&#60; Capítulo Anterior] | <<v4-18-0,Topo>> | xref:004-numeros/004-numeros-019.adoc#v4-19-0[Próximo Capítulo &#62;]