include::./index.adoc[]

[[v4-33-0]]
=== Números, 33
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-33-1]]

^<<v4-33-1,1>>^ São estas as caminhadas dos filhos de Israel que saíram da terra do Egito, segundo os seus exércitos, sob as ordens de Moisés e Arão.

[[v4-33-2]]

^<<v4-33-2,2>>^ Escreveu Moisés as suas saídas, caminhada após caminhada, conforme o mandado do SENHOR; e são estas as suas caminhadas, segundo as suas saídas:

[[v4-33-3]]

^<<v4-33-3,3>>^ partiram, pois, de Ramessés no décimo quinto dia do primeiro mês; no dia seguinte ao da Páscoa, saíram os filhos de Israel, corajosamente, aos olhos de todos os egípcios,

[[v4-33-4]]

^<<v4-33-4,4>>^ enquanto estes sepultavam todos os seus primogênitos, a quem o SENHOR havia ferido entre eles; também contra os deuses executou o SENHOR juízos.

[[v4-33-5]]

^<<v4-33-5,5>>^ Partidos, pois, os filhos de Israel de Ramessés, acamparam-se em Sucote.

[[v4-33-6]]

^<<v4-33-6,6>>^ E partiram de Sucote e acamparam-se em Etã, que está no fim do deserto.

[[v4-33-7]]

^<<v4-33-7,7>>^ E partiram de Etã, e voltaram a Pi-Hairote, que está defronte de Baal-Zefom, e acamparam-se diante de Migdol.

[[v4-33-8]]

^<<v4-33-8,8>>^ E partiram de Pi-Hairote, passaram pelo meio do mar ao deserto e, depois de terem andado caminho de três dias no deserto de Etã, acamparam-se em Mara.

[[v4-33-9]]

^<<v4-33-9,9>>^ E partiram de Mara e vieram a Elim. Em Elim, havia doze fontes de águas e setenta palmeiras; e acamparam-se ali.

[[v4-33-10]]

^<<v4-33-10,10>>^ E partiram de Elim e acamparam-se junto ao mar Vermelho;

[[v4-33-11]]

^<<v4-33-11,11>>^ partiram do mar Vermelho e acamparam-se no deserto de Sim;

[[v4-33-12]]

^<<v4-33-12,12>>^ partiram do deserto de Sim e acamparam-se em Dofca;

[[v4-33-13]]

^<<v4-33-13,13>>^ partiram de Dofca e acamparam-se em Alus;

[[v4-33-14]]

^<<v4-33-14,14>>^ partiram de Alus e acamparam-se em Refidim, porém não havia ali água, para que o povo bebesse;

[[v4-33-15]]

^<<v4-33-15,15>>^ partiram de Refidim e acamparam-se no deserto do Sinai;

[[v4-33-16]]

^<<v4-33-16,16>>^ partiram do deserto do Sinai e acamparam-se em Quibrote-Hataavá;

[[v4-33-17]]

^<<v4-33-17,17>>^ partiram de Quibrote-Hataavá e acamparam-se em Hazerote;

[[v4-33-18]]

^<<v4-33-18,18>>^ partiram de Hazerote e acamparam-se em Ritma;

[[v4-33-19]]

^<<v4-33-19,19>>^ partiram de Ritma e acamparam-se em Rimom-Perez;

[[v4-33-20]]

^<<v4-33-20,20>>^ partiram de Rimom-Perez e acamparam-se em Libna;

[[v4-33-21]]

^<<v4-33-21,21>>^ partiram de Libna e acamparam-se em Rissa;

[[v4-33-22]]

^<<v4-33-22,22>>^ partiram de Rissa e acamparam-se em Queelata;

[[v4-33-23]]

^<<v4-33-23,23>>^ partiram de Queelata e acamparam-se no monte Sefer;

[[v4-33-24]]

^<<v4-33-24,24>>^ partiram do monte Sefer e acamparam-se em Harada;

[[v4-33-25]]

^<<v4-33-25,25>>^ partiram de Harada e acamparam-se em Maquelote;

[[v4-33-26]]

^<<v4-33-26,26>>^ partiram de Maquelote e acamparam-se em Taate;

[[v4-33-27]]

^<<v4-33-27,27>>^ partiram de Taate e acamparam-se em Tera;

[[v4-33-28]]

^<<v4-33-28,28>>^ partiram de Tera e acamparam-se em Mitca;

[[v4-33-29]]

^<<v4-33-29,29>>^ partiram de Mitca e acamparam-se em Hasmona;

[[v4-33-30]]

^<<v4-33-30,30>>^ partiram de Hasmona e acamparam-se em Moserote;

[[v4-33-31]]

^<<v4-33-31,31>>^ partiram de Moserote e acamparam-se em Benê-Jaacã;

[[v4-33-32]]

^<<v4-33-32,32>>^ partiram de Benê-Jaacã e acamparam-se em Hor-Hagidgade;

[[v4-33-33]]

^<<v4-33-33,33>>^ partiram de Hor-Hagidgade e acamparam-se em Jotbatá;

[[v4-33-34]]

^<<v4-33-34,34>>^ partiram de Jotbatá e acamparam-se em Abrona;

[[v4-33-35]]

^<<v4-33-35,35>>^ partiram de Abrona e acamparam-se em Eziom-Geber;

[[v4-33-36]]

^<<v4-33-36,36>>^ partiram de Eziom-Geber e acamparam-se no deserto de Zim, que é Cades;

[[v4-33-37]]

^<<v4-33-37,37>>^ partiram de Cades e acamparam-se no monte Hor, na fronteira da terra de Edom.

[[v4-33-38]]

^<<v4-33-38,38>>^ Então, Arão, o sacerdote, subiu ao monte Hor, segundo o mandado do SENHOR; e morreu ali, no quinto mês do ano quadragésimo da saída dos filhos de Israel da terra do Egito, no primeiro dia do mês.

[[v4-33-39]]

^<<v4-33-39,39>>^ Era Arão da idade de cento e vinte e três anos, quando morreu no monte Hor.

[[v4-33-40]]

^<<v4-33-40,40>>^ Então, ouviu o cananeu, rei de Arade, que habitava o Sul da terra de Canaã, que chegavam os filhos de Israel.

[[v4-33-41]]

^<<v4-33-41,41>>^ E partiram do monte Hor e acamparam-se em Zalmona;

[[v4-33-42]]

^<<v4-33-42,42>>^ partiram de Zalmona e acamparam-se em Punom;

[[v4-33-43]]

^<<v4-33-43,43>>^ partiram de Punom e acamparam-se em Obote;

[[v4-33-44]]

^<<v4-33-44,44>>^ partiram de Obote e acamparam-se em Ijé-Abarim, no limite de Moabe;

[[v4-33-45]]

^<<v4-33-45,45>>^ partiram de Ijé-Abarim e acamparam-se em Dibom-Gade;

[[v4-33-46]]

^<<v4-33-46,46>>^ partiram de Dibom-Gade e acamparam-se em Almom-Diblataim;

[[v4-33-47]]

^<<v4-33-47,47>>^ partiram de Almom-Diblataim e acamparam-se nos montes de Abarim, defronte de Nebo;

[[v4-33-48]]

^<<v4-33-48,48>>^ partiram dos montes de Abarim e acamparam-se nas campinas de Moabe, junto ao Jordão, na altura de Jericó.

[[v4-33-49]]

^<<v4-33-49,49>>^ E acamparam-se junto ao Jordão, desde Bete-Jesimote até Abel-Sitim, nas campinas de Moabe.

[[v4-33-50]]

^<<v4-33-50,50>>^ Disse o SENHOR a Moisés, nas campinas de Moabe, junto ao Jordão, na altura de Jericó:

[[v4-33-51]]

^<<v4-33-51,51>>^ Fala aos filhos de Israel e dize-lhes: Quando houverdes passado o Jordão para a terra de Canaã,

[[v4-33-52]]

^<<v4-33-52,52>>^ desapossareis de diante de vós todos os moradores da terra, destruireis todas as pedras com figura e também todas as suas imagens fundidas e deitareis abaixo todos os seus ídolos;

[[v4-33-53]]

^<<v4-33-53,53>>^ tomareis a terra em possessão e nela habitareis, porque esta terra, eu vo-la dei para a possuirdes;

[[v4-33-54]]

^<<v4-33-54,54>>^ herdareis a terra por sortes, segundo as vossas famílias; à tribo mais numerosa dareis herança maior; à pequena, herança menor. Onde lhe cair a sorte, esse lugar lhe pertencerá; herdareis segundo as tribos de vossos pais.

[[v4-33-55]]

^<<v4-33-55,55>>^ Porém, se não desapossardes de diante de vós os moradores da terra, então, os que deixardes ficar ser-vos-ão como espinhos nos vossos olhos e como aguilhões nas vossas ilhargas e vos perturbarão na terra em que habitardes.

[[v4-33-56]]

^<<v4-33-56,56>>^ E será que farei a vós outros como pensei fazer-lhes a eles.

'''

xref:004-numeros/004-numeros-032.adoc#v4-32-0[&#60; Capítulo Anterior] | <<v4-33-0,Topo>> | xref:004-numeros/004-numeros-034.adoc#v4-34-0[Próximo Capítulo &#62;]