include::./index.adoc[]

[[v4-30-0]]
=== Números, 30
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-30-1]]

^<<v4-30-1,1>>^ Falou Moisés aos cabeças das tribos dos filhos de Israel, dizendo: Esta é a palavra que o SENHOR ordenou:

[[v4-30-2]]

^<<v4-30-2,2>>^ Quando um homem fizer voto ao SENHOR ou juramento para obrigar-se a alguma abstinência, não violará a sua palavra; segundo tudo o que prometeu, fará.

[[v4-30-3]]

^<<v4-30-3,3>>^ Quando, porém, uma mulher fizer voto ao SENHOR ou se obrigar a alguma abstinência, estando em casa de seu pai, na sua mocidade,

[[v4-30-4]]

^<<v4-30-4,4>>^ e seu pai, sabendo do voto e da abstinência a que ela se obrigou, calar-se para com ela, todos os seus votos serão válidos; terá de observar toda a abstinência a que se obrigou.

[[v4-30-5]]

^<<v4-30-5,5>>^ Mas, se o pai, no dia em que tal souber, o desaprovar, não será válido nenhum dos votos dela, nem lhe será preciso observar a abstinência a que se obrigou; o SENHOR lhe perdoará, porque o pai dela a isso se opôs.

[[v4-30-6]]

^<<v4-30-6,6>>^ Porém, se ela se casar, ainda sob seus votos ou dito irrefletido dos seus lábios, com que a si mesma se obrigou,

[[v4-30-7]]

^<<v4-30-7,7>>^ e seu marido, ouvindo-o, calar-se para com ela no dia em que o ouvir, serão válidos os votos dela, e lhe será preciso observar a abstinência a que se obrigou.

[[v4-30-8]]

^<<v4-30-8,8>>^ Mas, se seu marido o desaprovar no dia em que o ouvir e anular o voto que estava sobre ela, como também o dito irrefletido dos seus lábios, com que a si mesma se obrigou, o SENHOR lho perdoará.

[[v4-30-9]]

^<<v4-30-9,9>>^ No tocante ao voto da viúva ou da divorciada, tudo com que se obrigar lhe será válido.

[[v4-30-10]]

^<<v4-30-10,10>>^ Porém, se fez voto na casa de seu marido ou com juramento se obrigou a alguma abstinência,

[[v4-30-11]]

^<<v4-30-11,11>>^ e seu marido o soube, e se calou para com ela, e lho não desaprovou, todos os votos dela serão válidos; e lhe será preciso observar toda a abstinência a que a si mesma se obrigou.

[[v4-30-12]]

^<<v4-30-12,12>>^ Porém, se seu marido lhos anulou no dia em que o soube, tudo quanto saiu dos lábios dela, quer dos seus votos, quer da abstinência a que a si mesma se obrigou, não será válido; seu marido lhos anulou, e o SENHOR perdoará a ela.

[[v4-30-13]]

^<<v4-30-13,13>>^ Todo voto e todo juramento com que ela se obrigou, para afligir a sua alma, seu marido pode confirmar ou anular.

[[v4-30-14]]

^<<v4-30-14,14>>^ Porém, se seu marido, dia após dia, se calar para com ela, então, confirma todos os votos dela e tudo aquilo a que ela se obrigou, porquanto se calou para com ela no dia em que o soube.

[[v4-30-15]]

^<<v4-30-15,15>>^ Porém, se lhos anular depois de os ter ouvido, responderá pela obrigação dela.

[[v4-30-16]]

^<<v4-30-16,16>>^ São estes os estatutos que o SENHOR ordenou a Moisés, entre o marido e sua mulher, entre o pai e sua filha moça se ela estiver em casa de seu pai.

'''

xref:004-numeros/004-numeros-029.adoc#v4-29-0[&#60; Capítulo Anterior] | <<v4-30-0,Topo>> | xref:004-numeros/004-numeros-031.adoc#v4-31-0[Próximo Capítulo &#62;]