include::./index.adoc[]

[[v4-36-0]]
=== Números, 36
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-36-1]]

^<<v4-36-1,1>>^ Chegaram os cabeças das casas paternas da família dos filhos de Gileade, filho de Maquir, filho de Manassés, das famílias dos filhos de José, e falaram diante de Moisés e diante dos príncipes, cabeças das casas paternas dos filhos de Israel,

[[v4-36-2]]

^<<v4-36-2,2>>^ e disseram: O SENHOR ordenou a meu senhor que dê esta terra por sorte em herança aos filhos de Israel; e a meu senhor foi ordenado pelo SENHOR que a herança do nosso irmão Zelofeade se desse a suas filhas.

[[v4-36-3]]

^<<v4-36-3,3>>^ Porém, casando-se elas com algum dos filhos das outras tribos dos filhos de Israel, então, a sua herança seria diminuída da herança de nossos pais e acrescentada à herança da tribo a que vierem pertencer; assim, se tiraria da nossa herança que nos tocou em sorte.

[[v4-36-4]]

^<<v4-36-4,4>>^ Vindo também o Ano do Jubileu dos filhos de Israel, a herança delas se acrescentaria à herança da tribo daqueles a que vierem pertencer; assim, a sua herança será tirada da tribo de nossos pais.

[[v4-36-5]]

^<<v4-36-5,5>>^ Então, Moisés deu ordem aos filhos de Israel, segundo o mandado do SENHOR, dizendo: A tribo dos filhos de José fala o que é justo.

[[v4-36-6]]

^<<v4-36-6,6>>^ Esta é a palavra que o SENHOR mandou acerca das filhas de Zelofeade, dizendo: Sejam por mulheres a quem bem parecer aos seus olhos, contanto que se casem na família da tribo de seu pai.

[[v4-36-7]]

^<<v4-36-7,7>>^ Assim, a herança dos filhos de Israel não passará de tribo em tribo; pois os filhos de Israel se hão de vincular cada um à herança da tribo de seus pais.

[[v4-36-8]]

^<<v4-36-8,8>>^ Qualquer filha que possuir alguma herança das tribos dos filhos de Israel se casará com alguém da família da tribo de seu pai, para que os filhos de Israel possuam cada um a herança de seus pais.

[[v4-36-9]]

^<<v4-36-9,9>>^ Assim, a herança não passará de uma tribo a outra; pois as tribos dos filhos de Israel se hão de vincular cada uma à sua herança.

[[v4-36-10]]

^<<v4-36-10,10>>^ Como o SENHOR ordenara a Moisés, assim fizeram as filhas de Zelofeade,

[[v4-36-11]]

^<<v4-36-11,11>>^ pois Macla, Tirza, Hogla, Milca e Noa, filhas de Zelofeade, se casaram com os filhos de seus tios paternos.

[[v4-36-12]]

^<<v4-36-12,12>>^ Casaram-se nas famílias dos filhos de Manassés, filho de José, e a herança delas permaneceu na tribo da família de seu pai.

[[v4-36-13]]

^<<v4-36-13,13>>^ São estes os mandamentos e os juízos que ordenou o SENHOR, por intermédio de Moisés, aos filhos de Israel nas campinas de Moabe, junto ao Jordão, na altura de Jericó.

'''

xref:004-numeros/004-numeros-035.adoc#v4-35-0[&#60; Capítulo Anterior] | <<v4-36-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-001.adoc#v5-1-0[Próximo Capítulo &#62;]