include::./index.adoc[]

[[v4-32-0]]
=== Números, 32
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-32-1]]

^<<v4-32-1,1>>^ Os filhos de Rúben e os filhos de Gade tinham gado em muitíssima quantidade; e viram a terra de Jazer e a terra de Gileade, e eis que o lugar era lugar de gado.

[[v4-32-2]]

^<<v4-32-2,2>>^ Vieram, pois, os filhos de Gade e os filhos de Rúben e falaram a Moisés, e ao sacerdote Eleazar, e aos príncipes da congregação, dizendo:

[[v4-32-3]]

^<<v4-32-3,3>>^ Atarote, Dibom, Jazer, Ninra, Hesbom, Eleale, Sebã, Nebo e Beom,

[[v4-32-4]]

^<<v4-32-4,4>>^ a terra que o SENHOR feriu diante da congregação de Israel é terra de gado; e os teus servos têm gado.

[[v4-32-5]]

^<<v4-32-5,5>>^ Disseram mais: Se achamos mercê aos teus olhos, dê-se esta terra em possessão aos teus servos; e não nos faças passar o Jordão.

[[v4-32-6]]

^<<v4-32-6,6>>^ Porém Moisés disse aos filhos de Gade e aos filhos de Rúben: Irão vossos irmãos à guerra, e ficareis vós aqui?

[[v4-32-7]]

^<<v4-32-7,7>>^ Por que, pois, desanimais o coração dos filhos de Israel, para que não passem à terra que o SENHOR lhes deu?

[[v4-32-8]]

^<<v4-32-8,8>>^ Assim fizeram vossos pais, quando os enviei de Cades-Barneia a ver esta terra.

[[v4-32-9]]

^<<v4-32-9,9>>^ Chegando eles até ao vale de Escol e vendo a terra, descorajaram o coração dos filhos de Israel, para que não viessem à terra que o SENHOR lhes tinha dado.

[[v4-32-10]]

^<<v4-32-10,10>>^ Então, a ira do SENHOR se acendeu naquele mesmo dia, e jurou, dizendo:

[[v4-32-11]]

^<<v4-32-11,11>>^ Certamente, os varões que subiram do Egito, de vinte anos para cima, não verão a terra que prometi com juramento a Abraão, a Isaque e a Jacó, porquanto não perseveraram em seguir-me,

[[v4-32-12]]

^<<v4-32-12,12>>^ exceto Calebe, filho de Jefoné, o quenezeu, e Josué, filho de Num, porque perseveraram em seguir ao SENHOR.

[[v4-32-13]]

^<<v4-32-13,13>>^ Pelo que se acendeu a ira do SENHOR contra Israel, e fê-los andar errantes pelo deserto quarenta anos, até que se consumiu toda a geração que procedera mal perante o SENHOR.

[[v4-32-14]]

^<<v4-32-14,14>>^ Eis que vós, raça de homens pecadores, vos levantastes em lugar de vossos pais, para aumentardes ainda o furor da ira do SENHOR contra Israel.

[[v4-32-15]]

^<<v4-32-15,15>>^ Se não quiserdes segui-lo, também ele deixará todo o povo, novamente, no deserto, e sereis a sua ruína.

[[v4-32-16]]

^<<v4-32-16,16>>^ Então, se chegaram a ele e disseram: Edificaremos currais aqui para o nosso gado e cidades para as nossas crianças;

[[v4-32-17]]

^<<v4-32-17,17>>^ porém nós nos armaremos, apressando-nos adiante dos filhos de Israel, até que os levemos ao seu lugar; e ficarão as nossas crianças nas cidades fortes, por causa dos moradores da terra.

[[v4-32-18]]

^<<v4-32-18,18>>^ Não voltaremos para nossa casa até que os filhos de Israel estejam de posse, cada um, da sua herança.

[[v4-32-19]]

^<<v4-32-19,19>>^ Porque não herdaremos com eles do outro lado do Jordão, nem mais adiante, porquanto já temos a nossa herança deste lado do Jordão, ao oriente.

[[v4-32-20]]

^<<v4-32-20,20>>^ Então, Moisés lhes disse: Se isto fizerdes assim, se vos armardes para a guerra perante o SENHOR,

[[v4-32-21]]

^<<v4-32-21,21>>^ e cada um de vós, armado, passar o Jordão perante o SENHOR, até que haja lançado fora os seus inimigos de diante dele,

[[v4-32-22]]

^<<v4-32-22,22>>^ e a terra estiver subjugada perante o SENHOR, então, voltareis e sereis desobrigados perante o SENHOR e perante Israel; e a terra vos será por possessão perante o SENHOR.

[[v4-32-23]]

^<<v4-32-23,23>>^ Porém, se não fizerdes assim, eis que pecastes contra o SENHOR; e sabei que o vosso pecado vos há de achar.

[[v4-32-24]]

^<<v4-32-24,24>>^ Edificai vós cidades para as vossas crianças e currais para as vossas ovelhas; e cumpri o que haveis prometido.

[[v4-32-25]]

^<<v4-32-25,25>>^ Então, os filhos de Gade e os filhos de Rúben falaram a Moisés, dizendo: Como ordena meu senhor, assim farão teus servos.

[[v4-32-26]]

^<<v4-32-26,26>>^ Nossas crianças, nossas mulheres, nossos rebanhos e todos os nossos animais estarão aí nas cidades de Gileade,

[[v4-32-27]]

^<<v4-32-27,27>>^ mas os teus servos passarão, cada um armado para a guerra, perante o SENHOR, como diz meu senhor.

[[v4-32-28]]

^<<v4-32-28,28>>^ Então, Moisés deu ordem a respeito deles a Eleazar, o sacerdote, e a Josué, filho de Num, e aos cabeças das casas dos pais das tribos dos filhos de Israel;

[[v4-32-29]]

^<<v4-32-29,29>>^ e disse-lhes: Se os filhos de Gade e os filhos de Rúben passarem convosco o Jordão, armado cada um para a guerra, perante o SENHOR, e a terra estiver subjugada diante de vós, então, lhes dareis em possessão a terra de Gileade;

[[v4-32-30]]

^<<v4-32-30,30>>^ porém, se não passarem, armados, convosco, terão possessões entre vós na terra de Canaã.

[[v4-32-31]]

^<<v4-32-31,31>>^ Responderam os filhos de Gade e os filhos de Rúben, dizendo: O que o SENHOR disse a teus servos, isso faremos.

[[v4-32-32]]

^<<v4-32-32,32>>^ Passaremos, armados, perante o SENHOR à terra de Canaã e teremos a possessão de nossa herança deste lado do Jordão.

[[v4-32-33]]

^<<v4-32-33,33>>^ Deu Moisés aos filhos de Gade, e aos filhos de Rúben, e à meia tribo de Manassés, filho de José, o reino de Seom, rei dos amorreus, e o reino de Ogue, rei de Basã: a terra com as cidades e seus distritos, as cidades em toda a extensão do país.

[[v4-32-34]]

^<<v4-32-34,34>>^ Os filhos de Gade edificaram Dibom, Atarote e Aroer;

[[v4-32-35]]

^<<v4-32-35,35>>^ Atarote-Sofã, Jazer e Jogbeá;

[[v4-32-36]]

^<<v4-32-36,36>>^ Bete-Ninra e Bete-Harã, cidades fortificadas, e currais de ovelhas.

[[v4-32-37]]

^<<v4-32-37,37>>^ Os filhos de Rúben edificaram Hesbom, Eleale e Quiriataim;

[[v4-32-38]]

^<<v4-32-38,38>>^ Nebo e Baal-Meom, mudando-lhes o nome, e Sibma; e deram outros nomes às cidades que edificaram.

[[v4-32-39]]

^<<v4-32-39,39>>^ Os filhos de Maquir, filho de Manassés, foram-se para Gileade, e a tomaram, e desapossaram os amorreus que estavam nela.

[[v4-32-40]]

^<<v4-32-40,40>>^ Deu, pois, Moisés Gileade a Maquir, filho de Manassés, o qual habitou nela.

[[v4-32-41]]

^<<v4-32-41,41>>^ Foi Jair, filho de Manassés, e tomou as suas aldeias; e chamou-lhes Havote-Jair.

[[v4-32-42]]

^<<v4-32-42,42>>^ Foi Noba e tomou a Quenate com as suas aldeias; e chamou-lhe Noba, segundo o seu nome.

'''

xref:004-numeros/004-numeros-031.adoc#v4-31-0[&#60; Capítulo Anterior] | <<v4-32-0,Topo>> | xref:004-numeros/004-numeros-033.adoc#v4-33-0[Próximo Capítulo &#62;]