include::./index.adoc[]

[[v4-31-0]]
=== Números, 31
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-31-1]]

^<<v4-31-1,1>>^ Disse o SENHOR a Moisés:

[[v4-31-2]]

^<<v4-31-2,2>>^ Vinga os filhos de Israel dos midianitas; depois, serás recolhido ao teu povo.

[[v4-31-3]]

^<<v4-31-3,3>>^ Falou, pois, Moisés ao povo, dizendo: Armai alguns de vós para a guerra, e que saiam contra os midianitas, para fazerem a vingança do SENHOR contra eles.

[[v4-31-4]]

^<<v4-31-4,4>>^ Mil homens de cada tribo entre todas as tribos de Israel enviareis à guerra.

[[v4-31-5]]

^<<v4-31-5,5>>^ Assim, dos milhares de Israel foram dados mil de cada tribo: doze mil ao todo, armados para a guerra.

[[v4-31-6]]

^<<v4-31-6,6>>^ Mandou-os Moisés à guerra, de cada tribo mil, a estes e a Fineias, filho do sacerdote Eleazar, o qual levava consigo os utensílios sagrados, a saber, as trombetas para o toque de rebate.

[[v4-31-7]]

^<<v4-31-7,7>>^ Pelejaram contra os midianitas, como o SENHOR ordenara a Moisés,

[[v4-31-8]]

^<<v4-31-8,8>>^ e mataram todo homem feito. Mataram, além dos que já haviam sido mortos, os reis dos midianitas, Evi, Requém, Zur, Hur e Reba, cinco reis dos midianitas; também Balaão, filho de Beor, mataram à espada.

[[v4-31-9]]

^<<v4-31-9,9>>^ Porém os filhos de Israel levaram presas as mulheres dos midianitas e as suas crianças; também levaram todos os seus animais, e todo o seu gado, e todos os seus bens.

[[v4-31-10]]

^<<v4-31-10,10>>^ Queimaram-lhes todas as cidades em que habitavam e todos os seus acampamentos.

[[v4-31-11]]

^<<v4-31-11,11>>^ Tomaram todo o despojo e toda a presa, tanto de homens como de animais.

[[v4-31-12]]

^<<v4-31-12,12>>^ Trouxeram a Moisés, e ao sacerdote Eleazar, e à congregação dos filhos de Israel os cativos, e a presa, e o despojo, para o arraial, nas campinas de Moabe, junto do Jordão, na altura de Jericó.

[[v4-31-13]]

^<<v4-31-13,13>>^ Moisés, e Eleazar, o sacerdote, e todos os príncipes da congregação saíram a recebê-los fora do arraial.

[[v4-31-14]]

^<<v4-31-14,14>>^ Indignou-se Moisés contra os oficiais do exército, capitães dos milhares e capitães das centenas, que vinham do serviço da guerra.

[[v4-31-15]]

^<<v4-31-15,15>>^ Disse-lhes Moisés: Deixastes viver todas as mulheres?

[[v4-31-16]]

^<<v4-31-16,16>>^ Eis que estas, por conselho de Balaão, fizeram prevaricar os filhos de Israel contra o SENHOR, no caso de Peor, pelo que houve a praga entre a congregação do SENHOR.

[[v4-31-17]]

^<<v4-31-17,17>>^ Agora, pois, matai, dentre as crianças, todas as do sexo masculino; e matai toda mulher que coabitou com algum homem, deitando-se com ele.

[[v4-31-18]]

^<<v4-31-18,18>>^ Porém todas as meninas, e as jovens que não coabitaram com algum homem, deitando-se com ele, deixai-as viver para vós outros.

[[v4-31-19]]

^<<v4-31-19,19>>^ Acampai-vos sete dias fora do arraial; qualquer de vós que tiver matado alguma pessoa e qualquer que tiver tocado em algum morto, ao terceiro dia e ao sétimo dia, vos purificareis, tanto vós como os vossos cativos.

[[v4-31-20]]

^<<v4-31-20,20>>^ Também purificareis toda veste, e toda obra de peles, e toda obra de pelos de cabra, e todo artigo de madeira.

[[v4-31-21]]

^<<v4-31-21,21>>^ Então, disse o sacerdote Eleazar aos homens do exército que partiram à guerra: Este é o estatuto da lei que o SENHOR ordenou a Moisés.

[[v4-31-22]]

^<<v4-31-22,22>>^ Contudo, o ouro, a prata, o bronze, o ferro, o estanho e o chumbo,

[[v4-31-23]]

^<<v4-31-23,23>>^ tudo o que pode suportar o fogo fareis passar pelo fogo, para que fique limpo; todavia, se purificará com a água purificadora; mas tudo o que não pode suportar o fogo fareis passar pela água.

[[v4-31-24]]

^<<v4-31-24,24>>^ Também lavareis as vossas vestes ao sétimo dia, para que fiqueis limpos; e, depois, entrareis no arraial.

[[v4-31-25]]

^<<v4-31-25,25>>^ Disse mais o SENHOR a Moisés:

[[v4-31-26]]

^<<v4-31-26,26>>^ Faze a contagem da presa que foi tomada, tanto de homens como de animais, tu, e Eleazar, o sacerdote, e os cabeças das casas dos pais da congregação;

[[v4-31-27]]

^<<v4-31-27,27>>^ divide a presa em duas partes iguais, uma para os que, hábeis na peleja, saíram à guerra, e a outra para toda a congregação.

[[v4-31-28]]

^<<v4-31-28,28>>^ Então, para o SENHOR tomarás tributo dos homens do exército que saíram a esta guerra, de cada quinhentas cabeças, uma, tanto dos homens como dos bois, dos jumentos e das ovelhas.

[[v4-31-29]]

^<<v4-31-29,29>>^ Da metade que lhes toca o tomareis e o dareis ao sacerdote Eleazar, para a oferta do SENHOR.

[[v4-31-30]]

^<<v4-31-30,30>>^ Mas, da metade que toca aos filhos de Israel, tomarás, de cada cinquenta, um, tanto dos homens como dos bois, dos jumentos e das ovelhas, de todos os animais; e os darás aos levitas que têm a seu cargo o serviço do tabernáculo do SENHOR.

[[v4-31-31]]

^<<v4-31-31,31>>^ Moisés e o sacerdote Eleazar fizeram como o SENHOR ordenara a Moisés.

[[v4-31-32]]

^<<v4-31-32,32>>^ Foi a presa, restante do despojo que tomaram os homens de guerra, seiscentas e setenta e cinco mil ovelhas,

[[v4-31-33]]

^<<v4-31-33,33>>^ setenta e dois mil bois,

[[v4-31-34]]

^<<v4-31-34,34>>^ sessenta e um mil jumentos

[[v4-31-35]]

^<<v4-31-35,35>>^ e trinta e duas mil pessoas, as mulheres que não coabitaram com homem algum, deitando-se com ele.

[[v4-31-36]]

^<<v4-31-36,36>>^ E a metade, parte que toca aos que saíram à guerra, foi em número de trezentas e trinta e sete mil e quinhentas ovelhas.

[[v4-31-37]]

^<<v4-31-37,37>>^ O tributo em ovelhas para o SENHOR foram seiscentas e setenta e cinco.

[[v4-31-38]]

^<<v4-31-38,38>>^ E foram os bois trinta e seis mil; e o seu tributo para o SENHOR, setenta e dois.

[[v4-31-39]]

^<<v4-31-39,39>>^ E foram os jumentos trinta mil e quinhentos; e o seu tributo para o SENHOR, sessenta e um.

[[v4-31-40]]

^<<v4-31-40,40>>^ As pessoas foram dezesseis mil; e o seu tributo para o SENHOR, trinta e duas.

[[v4-31-41]]

^<<v4-31-41,41>>^ Então, Moisés deu a Eleazar, o sacerdote, o tributo da oferta do SENHOR, como este ordenara a Moisés.

[[v4-31-42]]

^<<v4-31-42,42>>^ E, da metade que toca aos filhos de Israel, que Moisés separara da dos homens que pelejaram

[[v4-31-43]]

^<<v4-31-43,43>>^ (a metade para a congregação foram, em ovelhas, trezentas e trinta e sete mil e quinhentas;

[[v4-31-44]]

^<<v4-31-44,44>>^ em bois, trinta e seis mil;

[[v4-31-45]]

^<<v4-31-45,45>>^ em jumentos, trinta mil e quinhentos;

[[v4-31-46]]

^<<v4-31-46,46>>^ e, em pessoas, dezesseis mil),

[[v4-31-47]]

^<<v4-31-47,47>>^ desta metade que toca aos filhos de Israel, Moisés tomou um de cada cinquenta, tanto de homens como de animais, e os deu aos levitas que tinham a seu cargo o serviço do tabernáculo do SENHOR, como o SENHOR ordenara a Moisés.

[[v4-31-48]]

^<<v4-31-48,48>>^ Então, se chegaram a Moisés os oficiais sobre os milhares do exército, capitães sobre mil e capitães sobre cem,

[[v4-31-49]]

^<<v4-31-49,49>>^ e lhe disseram: Teus servos fizeram a conta dos homens de guerra que estiveram sob as nossas ordens, e nenhum falta dentre eles e nós.

[[v4-31-50]]

^<<v4-31-50,50>>^ Pelo que trouxemos uma oferta ao SENHOR, cada um o que achou: objetos de ouro, ornamentos para o braço, pulseiras, sinetes, arrecadas e colares, para fazer expiação por nós mesmos perante o SENHOR.

[[v4-31-51]]

^<<v4-31-51,51>>^ Assim, Moisés e o sacerdote Eleazar receberam deles o ouro, sendo todos os objetos bem-trabalhados.

[[v4-31-52]]

^<<v4-31-52,52>>^ Foi todo o ouro da oferta que os capitães de mil e os capitães de cem trouxeram ao SENHOR dezesseis mil setecentos e cinquenta siclos.

[[v4-31-53]]

^<<v4-31-53,53>>^ Pois cada um dos homens de guerra havia tomado despojo para si.

[[v4-31-54]]

^<<v4-31-54,54>>^ Moisés e o sacerdote Eleazar receberam o ouro dos capitães de mil e dos capitães de cem e o trouxeram à tenda da congregação, como memorial para os filhos de Israel perante o SENHOR.

'''

xref:004-numeros/004-numeros-030.adoc#v4-30-0[&#60; Capítulo Anterior] | <<v4-31-0,Topo>> | xref:004-numeros/004-numeros-032.adoc#v4-32-0[Próximo Capítulo &#62;]