include::./index.adoc[]

[[v4-24-0]]
=== Números, 24
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-24-1]]

^<<v4-24-1,1>>^ Vendo Balaão que bem parecia aos olhos do SENHOR que abençoasse a Israel, não foi esta vez, como antes, ao encontro de agouros, mas voltou o rosto para o deserto.

[[v4-24-2]]

^<<v4-24-2,2>>^ Levantando Balaão os olhos e vendo Israel acampado segundo as suas tribos, veio sobre ele o Espírito de Deus.

[[v4-24-3]]

^<<v4-24-3,3>>^ Proferiu a sua palavra e disse: Palavra de Balaão, filho de Beor, palavra do homem de olhos abertos;

[[v4-24-4]]

^<<v4-24-4,4>>^ palavra daquele que ouve os ditos de Deus, o que tem a visão do Todo-Poderoso e prostra-se, porém de olhos abertos:

[[v4-24-5]]

^<<v4-24-5,5>>^ Que boas são as tuas tendas, ó Jacó! Que boas são as tuas moradas, ó Israel!

[[v4-24-6]]

^<<v4-24-6,6>>^ Como vales que se estendem, como jardins à beira dos rios, como árvores de sândalo que o SENHOR plantou, como cedros junto às águas.

[[v4-24-7]]

^<<v4-24-7,7>>^ Águas manarão de seus baldes, e as suas sementeiras terão águas abundantes; o seu rei se levantará mais do que Agague, e o seu reino será exaltado.

[[v4-24-8]]

^<<v4-24-8,8>>^ Deus tirou do Egito a Israel, cujas forças são como as do boi selvagem; consumirá as nações, seus inimigos, e quebrará seus ossos, e, com as suas setas, os atravessará.

[[v4-24-9]]

^<<v4-24-9,9>>^ Este abaixou-se, deitou-se como leão e como leoa; quem o despertará? Benditos os que te abençoarem, e malditos os que te amaldiçoarem.

[[v4-24-10]]

^<<v4-24-10,10>>^ Então, a ira de Balaque se acendeu contra Balaão, e bateu ele as suas palmas. Disse Balaque a Balaão: Chamei-te para amaldiçoares os meus inimigos; porém, agora, já três vezes, somente os abençoaste.

[[v4-24-11]]

^<<v4-24-11,11>>^ Agora, pois, vai-te embora para tua casa; eu dissera que te cumularia de honras; mas eis que o SENHOR te privou delas.

[[v4-24-12]]

^<<v4-24-12,12>>^ Então, Balaão disse a Balaque: Não falei eu também aos teus mensageiros, que me enviaste, dizendo:

[[v4-24-13]]

^<<v4-24-13,13>>^ ainda que Balaque me desse a sua casa cheia de prata e ouro, não poderia traspassar o mandado do SENHOR, fazendo de mim mesmo bem ou mal; o que o SENHOR falar, isso falarei?

[[v4-24-14]]

^<<v4-24-14,14>>^ Agora, eis que vou ao meu povo; vem, avisar-te-ei do que fará este povo ao teu, nos últimos dias.

[[v4-24-15]]

^<<v4-24-15,15>>^ Então, proferiu a sua palavra e disse: Palavra de Balaão, filho de Beor, palavra do homem de olhos abertos,

[[v4-24-16]]

^<<v4-24-16,16>>^ palavra daquele que ouve os ditos de Deus e sabe a ciência do Altíssimo; daquele que tem a visão do Todo-Poderoso e prostra-se, porém de olhos abertos:

[[v4-24-17]]

^<<v4-24-17,17>>^ Vê-lo-ei, mas não agora; contemplá-lo-ei, mas não de perto; uma estrela procederá de Jacó, de Israel subirá um cetro que ferirá as têmporas de Moabe e destruirá todos os filhos de Sete.

[[v4-24-18]]

^<<v4-24-18,18>>^ Edom será uma possessão; Seir, seus inimigos, também será uma possessão; mas Israel fará proezas.

[[v4-24-19]]

^<<v4-24-19,19>>^ De Jacó sairá o dominador e exterminará os que restam das cidades.

[[v4-24-20]]

^<<v4-24-20,20>>^ Viu Balaão a Amaleque, proferiu a sua palavra e disse: Amaleque é o primeiro das nações; porém o seu fim será destruição.

[[v4-24-21]]

^<<v4-24-21,21>>^ Viu os queneus, proferiu a sua palavra e disse: Segura está a tua habitação, e puseste o teu ninho na penha.

[[v4-24-22]]

^<<v4-24-22,22>>^ Todavia, o queneu será consumido. Até quando? Assur te levará cativo.

[[v4-24-23]]

^<<v4-24-23,23>>^ Proferiu ainda a sua palavra e disse: Ai! Quem viverá, quando Deus fizer isto?

[[v4-24-24]]

^<<v4-24-24,24>>^ Homens virão das costas de Quitim em suas naus; afligirão a Assur e a Héber; e também eles mesmos perecerão.

[[v4-24-25]]

^<<v4-24-25,25>>^ Então, Balaão se levantou, e se foi, e voltou para a sua terra; e também Balaque se foi pelo seu caminho.

'''

xref:004-numeros/004-numeros-023.adoc#v4-23-0[&#60; Capítulo Anterior] | <<v4-24-0,Topo>> | xref:004-numeros/004-numeros-025.adoc#v4-25-0[Próximo Capítulo &#62;]