include::./index.adoc[]

[[v4-3-0]]
=== Números, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-3-1]]

^<<v4-3-1,1>>^ São estas, pois, as gerações de Arão e de Moisés, no dia em que o SENHOR falou com Moisés no monte Sinai.

[[v4-3-2]]

^<<v4-3-2,2>>^ E são estes os nomes dos filhos de Arão: o primogênito, Nadabe; depois, Abiú, Eleazar e Itamar.

[[v4-3-3]]

^<<v4-3-3,3>>^ Estes são os nomes dos filhos de Arão, os sacerdotes ungidos, consagrados para oficiar como sacerdotes.

[[v4-3-4]]

^<<v4-3-4,4>>^ Mas Nadabe e Abiú morreram perante o SENHOR, quando ofereciam fogo estranho perante o SENHOR, no deserto do Sinai, e não tiveram filhos; porém Eleazar e Itamar oficiaram como sacerdotes diante de Arão, seu pai.

[[v4-3-5]]

^<<v4-3-5,5>>^ Disse o SENHOR a Moisés:

[[v4-3-6]]

^<<v4-3-6,6>>^ Faze chegar a tribo de Levi e põe-na diante de Arão, o sacerdote, para que o sirvam

[[v4-3-7]]

^<<v4-3-7,7>>^ e cumpram seus deveres para com ele e para com todo o povo, diante da tenda da congregação, para ministrarem no tabernáculo.

[[v4-3-8]]

^<<v4-3-8,8>>^ Terão cuidado de todos os utensílios da tenda da congregação e cumprirão o seu dever para com os filhos de Israel, no ministrar no tabernáculo.

[[v4-3-9]]

^<<v4-3-9,9>>^ Darás, pois, os levitas a Arão e a seus filhos; dentre os filhos de Israel lhe são dados.

[[v4-3-10]]

^<<v4-3-10,10>>^ Mas a Arão e a seus filhos ordenarás que se dediquem só ao seu sacerdócio, e o estranho que se aproximar morrerá.

[[v4-3-11]]

^<<v4-3-11,11>>^ Disse o SENHOR a Moisés:

[[v4-3-12]]

^<<v4-3-12,12>>^ Eis que tenho eu tomado os levitas do meio dos filhos de Israel, em lugar de todo primogênito que abre a madre, entre os filhos de Israel; e os levitas serão meus.

[[v4-3-13]]

^<<v4-3-13,13>>^ Porque todo primogênito é meu; desde o dia em que feri a todo primogênito na terra do Egito, consagrei para mim todo primogênito em Israel, desde o homem até ao animal; serão meus. Eu sou o SENHOR.

[[v4-3-14]]

^<<v4-3-14,14>>^ Falou o SENHOR a Moisés no deserto do Sinai, dizendo:

[[v4-3-15]]

^<<v4-3-15,15>>^ Conta os filhos de Levi, segundo a casa de seus pais, pelas suas famílias; contarás todo homem da idade de um mês para cima.

[[v4-3-16]]

^<<v4-3-16,16>>^ E Moisés os contou segundo o mandado do SENHOR, como lhe fora ordenado.

[[v4-3-17]]

^<<v4-3-17,17>>^ São estes os filhos de Levi pelos seus nomes: Gérson, Coate e Merari.

[[v4-3-18]]

^<<v4-3-18,18>>^ E estes são os nomes dos filhos de Gérson pelas suas famílias: Libni e Simei.

[[v4-3-19]]

^<<v4-3-19,19>>^ E os filhos de Coate pelas suas famílias: Anrão, Izar, Hebrom e Uziel.

[[v4-3-20]]

^<<v4-3-20,20>>^ E os filhos de Merari pelas suas famílias: Mali e Musi; são estas as famílias dos levitas, segundo a casa de seus pais.

[[v4-3-21]]

^<<v4-3-21,21>>^ De Gérson é a família dos libnitas e a dos simeítas; são estas as famílias dos gersonitas.

[[v4-3-22]]

^<<v4-3-22,22>>^ Todos os homens que deles foram contados, cada um nominalmente, de um mês para cima, foram sete mil e quinhentos.

[[v4-3-23]]

^<<v4-3-23,23>>^ As famílias dos gersonitas se acamparão atrás do tabernáculo, ao ocidente.

[[v4-3-24]]

^<<v4-3-24,24>>^ O príncipe da casa paterna dos gersonitas será Eliasafe, filho de Lael.

[[v4-3-25]]

^<<v4-3-25,25>>^ Os filhos de Gérson terão a seu cargo, na tenda da congregação, o tabernáculo, a tenda e sua coberta, o reposteiro para a porta da tenda da congregação,

[[v4-3-26]]

^<<v4-3-26,26>>^ as cortinas do pátio, o reposteiro da porta do pátio, que rodeia o tabernáculo e o altar, as suas cordas e todo o serviço a eles devido.

[[v4-3-27]]

^<<v4-3-27,27>>^ De Coate é a família dos anramitas, e a dos izaritas, e a dos hebronitas, e a dos uzielitas; são estas as famílias dos coatitas.

[[v4-3-28]]

^<<v4-3-28,28>>^ Contados todos os homens, da idade de um mês para cima, foram oito mil e seiscentos, que tinham a seu cargo o santuário.

[[v4-3-29]]

^<<v4-3-29,29>>^ As famílias dos filhos de Coate se acamparão ao lado do tabernáculo, do lado sul.

[[v4-3-30]]

^<<v4-3-30,30>>^ O príncipe da casa paterna das famílias dos coatitas será Elisafã, filho de Uziel.

[[v4-3-31]]

^<<v4-3-31,31>>^ Terão eles a seu cargo a arca, a mesa, o candelabro, os altares, os utensílios do santuário com que ministram, o reposteiro e todo o serviço a eles devido.

[[v4-3-32]]

^<<v4-3-32,32>>^ O príncipe dos príncipes de Levi será Eleazar, filho de Arão, o sacerdote; terá a superintendência dos que têm a seu cargo o santuário.

[[v4-3-33]]

^<<v4-3-33,33>>^ De Merari é a família dos malitas e a dos musitas; são estas as famílias de Merari.

[[v4-3-34]]

^<<v4-3-34,34>>^ Todos os homens que deles foram contados, de um mês para cima, foram seis mil e duzentos.

[[v4-3-35]]

^<<v4-3-35,35>>^ O príncipe da casa paterna das famílias de Merari será Zuriel, filho de Abiail; acampar-se-ão ao lado do tabernáculo, do lado norte.

[[v4-3-36]]

^<<v4-3-36,36>>^ Os filhos de Merari, por designação, terão a seu cargo as tábuas do tabernáculo, as suas travessas, as suas colunas, as suas bases, todos os seus utensílios e todo o serviço a eles devido;

[[v4-3-37]]

^<<v4-3-37,37>>^ também as colunas do pátio em redor, as suas bases, as suas estacas e as suas cordas.

[[v4-3-38]]

^<<v4-3-38,38>>^ Os que se acamparão diante do tabernáculo, ao oriente, diante da tenda da congregação, para o lado do nascente, serão Moisés e Arão, com seus filhos, tendo a seu cargo os ritos do santuário, para cumprirem seus deveres prescritos, em prol dos filhos de Israel; o estranho que se aproximar morrerá.

[[v4-3-39]]

^<<v4-3-39,39>>^ Todos os que foram contados dos levitas, contados por Moisés e Arão, por mandado do SENHOR, segundo as suas famílias, todo homem de um mês para cima, foram vinte e dois mil.

[[v4-3-40]]

^<<v4-3-40,40>>^ Disse o SENHOR a Moisés: Conta todo primogênito varão dos filhos de Israel, cada um nominalmente, de um mês para cima,

[[v4-3-41]]

^<<v4-3-41,41>>^ e para mim tomarás os levitas (eu sou o SENHOR) em lugar de todo primogênito dos filhos de Israel e os animais dos levitas em lugar de todo primogênito entre os animais dos filhos de Israel.

[[v4-3-42]]

^<<v4-3-42,42>>^ Contou Moisés, como o SENHOR lhe ordenara, todo primogênito entre os filhos de Israel.

[[v4-3-43]]

^<<v4-3-43,43>>^ Todos os primogênitos varões, contados nominalmente, de um mês para cima, segundo o censo, foram vinte e dois mil duzentos e setenta e três.

[[v4-3-44]]

^<<v4-3-44,44>>^ Disse o SENHOR a Moisés:

[[v4-3-45]]

^<<v4-3-45,45>>^ Toma os levitas em lugar de todo primogênito entre os filhos de Israel e os animais dos levitas em lugar dos animais dos filhos de Israel, porquanto os levitas serão meus. Eu sou o SENHOR.

[[v4-3-46]]

^<<v4-3-46,46>>^ Pelo resgate dos duzentos e setenta e três dos primogênitos dos filhos de Israel, que excedem o número dos levitas,

[[v4-3-47]]

^<<v4-3-47,47>>^ tomarás por cabeça cinco siclos; segundo o siclo do santuário, os tomarás, a vinte geras o siclo.

[[v4-3-48]]

^<<v4-3-48,48>>^ E darás a Arão e a seus filhos o dinheiro com o qual são resgatados os que são demais entre eles.

[[v4-3-49]]

^<<v4-3-49,49>>^ Então, Moisés tomou o dinheiro do resgate dos que excederam os que foram resgatados pelos levitas.

[[v4-3-50]]

^<<v4-3-50,50>>^ Dos primogênitos dos filhos de Israel tomou o dinheiro, mil trezentos e sessenta e cinco siclos, segundo o siclo do santuário.

[[v4-3-51]]

^<<v4-3-51,51>>^ E deu Moisés o dinheiro dos resgatados a Arão e a seus filhos, segundo o mandado do SENHOR, como o SENHOR ordenara a Moisés.

'''

xref:004-numeros/004-numeros-002.adoc#v4-2-0[&#60; Capítulo Anterior] | <<v4-3-0,Topo>> | xref:004-numeros/004-numeros-004.adoc#v4-4-0[Próximo Capítulo &#62;]