include::./index.adoc[]

[[v4-29-0]]
=== Números, 29
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-29-1]]

^<<v4-29-1,1>>^ No primeiro dia do sétimo mês, tereis santa convocação; nenhuma obra servil fareis; ser-vos-á dia do sonido de trombetas.

[[v4-29-2]]

^<<v4-29-2,2>>^ Então, por holocausto, de aroma agradável ao SENHOR, oferecereis um novilho, um carneiro e sete cordeiros de um ano, sem defeito;

[[v4-29-3]]

^<<v4-29-3,3>>^ e, pela sua oferta de manjares de flor de farinha, amassada com azeite, três décimas de um efa para o novilho, duas décimas para o carneiro

[[v4-29-4]]

^<<v4-29-4,4>>^ e uma décima para cada um dos sete cordeiros;

[[v4-29-5]]

^<<v4-29-5,5>>^ e um bode, para oferta pelo pecado, para fazer expiação por vós,

[[v4-29-6]]

^<<v4-29-6,6>>^ além do holocausto do mês e a sua oferta de manjares, do holocausto contínuo e a sua oferta de manjares, com as suas libações, segundo o seu estatuto, em aroma agradável, oferta queimada ao SENHOR.

[[v4-29-7]]

^<<v4-29-7,7>>^ No dia dez deste sétimo mês, tereis santa convocação e afligireis a vossa alma; nenhuma obra fareis.

[[v4-29-8]]

^<<v4-29-8,8>>^ Mas, por holocausto, em aroma agradável ao SENHOR, oferecereis um novilho, um carneiro e sete cordeiros de um ano; ser-vos-ão eles sem defeito.

[[v4-29-9]]

^<<v4-29-9,9>>^ Pela sua oferta de manjares de flor de farinha, amassada com azeite, oferecereis três décimas de um efa para o novilho, duas décimas para o carneiro

[[v4-29-10]]

^<<v4-29-10,10>>^ e uma décima para cada um dos sete cordeiros;

[[v4-29-11]]

^<<v4-29-11,11>>^ um bode, para oferta pelo pecado, além da oferta pelo pecado, para fazer expiação, e do holocausto contínuo, e da sua oferta de manjares com as suas libações.

[[v4-29-12]]

^<<v4-29-12,12>>^ Aos quinze dias do sétimo mês, tereis santa convocação; nenhuma obra servil fareis; mas sete dias celebrareis festa ao SENHOR.

[[v4-29-13]]

^<<v4-29-13,13>>^ Por holocausto em oferta queimada, de aroma agradável ao SENHOR, oferecereis treze novilhos, dois carneiros e catorze cordeiros de um ano; serão eles sem defeito.

[[v4-29-14]]

^<<v4-29-14,14>>^ Pela oferta de manjares de flor de farinha, amassada com azeite, três décimas de um efa para cada um dos treze novilhos, duas décimas para cada um dos dois carneiros

[[v4-29-15]]

^<<v4-29-15,15>>^ e uma décima para cada um dos catorze cordeiros;

[[v4-29-16]]

^<<v4-29-16,16>>^ e um bode, para oferta pelo pecado, além do holocausto contínuo, a sua oferta de manjares e a sua libação.

[[v4-29-17]]

^<<v4-29-17,17>>^ No segundo dia, oferecereis doze novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito,

[[v4-29-18]]

^<<v4-29-18,18>>^ com a oferta de manjares e as libações para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo o estatuto,

[[v4-29-19]]

^<<v4-29-19,19>>^ e um bode, para oferta pelo pecado, além do holocausto contínuo, a sua oferta de manjares e a sua libação.

[[v4-29-20]]

^<<v4-29-20,20>>^ No terceiro dia, oferecereis onze novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito,

[[v4-29-21]]

^<<v4-29-21,21>>^ com a oferta de manjares e as libações para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo o estatuto,

[[v4-29-22]]

^<<v4-29-22,22>>^ e um bode, para oferta pelo pecado, além do holocausto contínuo, a sua oferta de manjares e a sua libação.

[[v4-29-23]]

^<<v4-29-23,23>>^ No quarto dia, dez novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito,

[[v4-29-24]]

^<<v4-29-24,24>>^ com a oferta de manjares e as libações para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo o estatuto,

[[v4-29-25]]

^<<v4-29-25,25>>^ e um bode, para oferta pelo pecado, além do holocausto contínuo, a sua oferta de manjares e a sua libação.

[[v4-29-26]]

^<<v4-29-26,26>>^ No quinto dia, nove novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito,

[[v4-29-27]]

^<<v4-29-27,27>>^ com a oferta de manjares e as libações para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo o estatuto,

[[v4-29-28]]

^<<v4-29-28,28>>^ e um bode, para oferta pelo pecado, além do holocausto contínuo, a sua oferta de manjares e a sua libação.

[[v4-29-29]]

^<<v4-29-29,29>>^ No sexto dia, oito novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito,

[[v4-29-30]]

^<<v4-29-30,30>>^ com a oferta de manjares e as libações para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo o estatuto,

[[v4-29-31]]

^<<v4-29-31,31>>^ e um bode, para oferta pelo pecado, além do holocausto contínuo, a sua oferta de manjares e a sua libação.

[[v4-29-32]]

^<<v4-29-32,32>>^ No sétimo dia, sete novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito,

[[v4-29-33]]

^<<v4-29-33,33>>^ com a oferta de manjares e as libações para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo o estatuto,

[[v4-29-34]]

^<<v4-29-34,34>>^ e um bode, para oferta pelo pecado, além do holocausto contínuo, a sua oferta de manjares e a sua libação.

[[v4-29-35]]

^<<v4-29-35,35>>^ No oitavo dia, tereis reunião solene; nenhuma obra servil fareis;

[[v4-29-36]]

^<<v4-29-36,36>>^ e, por holocausto, em oferta queimada de aroma agradável ao SENHOR, oferecereis um novilho, um carneiro, sete cordeiros de um ano, sem defeito,

[[v4-29-37]]

^<<v4-29-37,37>>^ com a oferta de manjares e as libações para o novilho, para o carneiro e para os cordeiros, conforme o seu número, segundo o estatuto,

[[v4-29-38]]

^<<v4-29-38,38>>^ e um bode, para oferta pelo pecado, além do holocausto contínuo, a sua oferta de manjares e a sua libação.

[[v4-29-39]]

^<<v4-29-39,39>>^ Estas coisas oferecereis ao SENHOR nas vossas festas fixas, além dos vossos votos e das vossas ofertas voluntárias, para os vossos holocaustos, as vossas ofertas de manjares, as vossas libações e as vossas ofertas pacíficas.

[[v4-29-40]]

^<<v4-29-40,40>>^ E falou Moisés aos filhos de Israel, conforme tudo o que o SENHOR lhe ordenara.

'''

xref:004-numeros/004-numeros-028.adoc#v4-28-0[&#60; Capítulo Anterior] | <<v4-29-0,Topo>> | xref:004-numeros/004-numeros-030.adoc#v4-30-0[Próximo Capítulo &#62;]