include::./index.adoc[]

[[v4-5-0]]
=== Números, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-5-1]]

^<<v4-5-1,1>>^ Disse o SENHOR a Moisés:

[[v4-5-2]]

^<<v4-5-2,2>>^ Ordena aos filhos de Israel que lancem para fora do arraial todo leproso, todo o que padece fluxo e todo imundo por ter tocado em algum morto;

[[v4-5-3]]

^<<v4-5-3,3>>^ tanto homem como mulher os lançareis; para fora do arraial os lançareis, para que não contaminem o arraial, no meio do qual eu habito.

[[v4-5-4]]

^<<v4-5-4,4>>^ Os filhos de Israel fizeram assim e os lançaram para fora do arraial; como o SENHOR falara a Moisés, assim fizeram os filhos de Israel.

[[v4-5-5]]

^<<v4-5-5,5>>^ Disse mais o SENHOR a Moisés:

[[v4-5-6]]

^<<v4-5-6,6>>^ Dize aos filhos de Israel: Quando homem ou mulher cometer algum dos pecados em que caem os homens, ofendendo ao SENHOR, tal pessoa é culpada.

[[v4-5-7]]

^<<v4-5-7,7>>^ Confessará o pecado que cometer; e, pela culpa, fará plena restituição, e lhe acrescentará a sua quinta parte, e dará tudo àquele contra quem se fez culpado.

[[v4-5-8]]

^<<v4-5-8,8>>^ Mas, se esse homem não tiver parente chegado, a quem possa fazer restituição pela culpa, então, o que se restitui ao SENHOR pela culpa será do sacerdote, além do carneiro expiatório com que se fizer expiação pelo culpado.

[[v4-5-9]]

^<<v4-5-9,9>>^ Toda oferta de todas as coisas santas dos filhos de Israel, que trouxerem ao sacerdote, será deste

[[v4-5-10]]

^<<v4-5-10,10>>^ e também as coisas sagradas de cada um; o que alguém der ao sacerdote será deste.

[[v4-5-11]]

^<<v4-5-11,11>>^ Disse mais o SENHOR a Moisés:

[[v4-5-12]]

^<<v4-5-12,12>>^ Fala aos filhos de Israel e dize-lhes: Se a mulher de alguém se desviar e lhe for infiel,

[[v4-5-13]]

^<<v4-5-13,13>>^ de maneira que algum homem se tenha deitado com ela, e for oculto aos olhos de seu marido, e ela o tiver ocultado, havendo-se ela contaminado, e contra ela não houver testemunha, e não for surpreendida em flagrante,

[[v4-5-14]]

^<<v4-5-14,14>>^ e o espírito de ciúmes vier sobre ele, e de sua mulher tiver ciúmes, por ela se haver contaminado, ou o tiver, não se havendo ela contaminado,

[[v4-5-15]]

^<<v4-5-15,15>>^ então, esse homem trará a sua mulher perante o sacerdote e juntamente trará a sua oferta por ela: uma décima de efa de farinha de cevada, sobre a qual não deitará azeite, nem sobre ela porá incenso, porquanto é oferta de manjares de ciúmes, oferta memorativa, que traz a iniquidade à memória.

[[v4-5-16]]

^<<v4-5-16,16>>^ O sacerdote a fará chegar e a colocará perante o SENHOR.

[[v4-5-17]]

^<<v4-5-17,17>>^ O sacerdote tomará água santa num vaso de barro; também tomará do pó que houver no chão do tabernáculo e o deitará na água.

[[v4-5-18]]

^<<v4-5-18,18>>^ Apresentará a mulher perante o SENHOR e soltará a cabeleira dela; e lhe porá nas mãos a oferta memorativa de manjares, que é a oferta de manjares dos ciúmes. A água amarga, que traz consigo a maldição, estará na mão do sacerdote.

[[v4-5-19]]

^<<v4-5-19,19>>^ O sacerdote a conjurará e lhe dirá: Se ninguém contigo se deitou, e se não te desviaste para a imundícia, estando sob o domínio de teu marido, destas águas amargas, amaldiçoantes, serás livre.

[[v4-5-20]]

^<<v4-5-20,20>>^ Mas, se te desviaste, quando sob o domínio de teu marido, e te contaminaste, e algum homem, que não é o teu marido, se deitou contigo

[[v4-5-21]]

^<<v4-5-21,21>>^ (então, o sacerdote fará que a mulher tome o juramento de maldição e lhe dirá), o SENHOR te ponha por maldição e por praga no meio do teu povo, fazendo-te o SENHOR descair a coxa e inchar o ventre;

[[v4-5-22]]

^<<v4-5-22,22>>^ e esta água amaldiçoante penetre nas tuas entranhas, para te fazer inchar o ventre e te fazer descair a coxa. Então, a mulher dirá: Amém! Amém!

[[v4-5-23]]

^<<v4-5-23,23>>^ O sacerdote escreverá estas maldições num livro e, com a água amarga, as apagará.

[[v4-5-24]]

^<<v4-5-24,24>>^ E fará que a mulher beba a água amarga, que traz consigo a maldição; e, sendo bebida, lhe causará amargura.

[[v4-5-25]]

^<<v4-5-25,25>>^ Da mão da mulher tomará o sacerdote a oferta de manjares de ciúmes e a moverá perante o SENHOR; e a trará ao altar.

[[v4-5-26]]

^<<v4-5-26,26>>^ Tomará um punhado da oferta de manjares, da oferta memorativa, e sobre o altar o queimará; e, depois, dará a beber a água à mulher.

[[v4-5-27]]

^<<v4-5-27,27>>^ E, havendo-lhe dado a beber a água, será que, se ela se tiver contaminado, e a seu marido tenha sido infiel, a água amaldiçoante entrará nela para amargura, e o seu ventre se inchará, e a sua coxa descairá; a mulher será por maldição no meio do seu povo.

[[v4-5-28]]

^<<v4-5-28,28>>^ Se a mulher se não tiver contaminado, mas estiver limpa, então, será livre e conceberá.

[[v4-5-29]]

^<<v4-5-29,29>>^ Esta é a lei para o caso de ciúmes, quando a mulher, sob o domínio de seu marido, se desviar e for contaminada;

[[v4-5-30]]

^<<v4-5-30,30>>^ ou quando sobre o homem vier o espírito de ciúmes, e tiver ciúmes de sua mulher, apresente a mulher perante o SENHOR, e o sacerdote nela execute toda esta lei.

[[v4-5-31]]

^<<v4-5-31,31>>^ O homem será livre da iniquidade, porém a mulher levará a sua iniquidade.

'''

xref:004-numeros/004-numeros-004.adoc#v4-4-0[&#60; Capítulo Anterior] | <<v4-5-0,Topo>> | xref:004-numeros/004-numeros-006.adoc#v4-6-0[Próximo Capítulo &#62;]