include::./index.adoc[]

[[v4-21-0]]
=== Números, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-21-1]]

^<<v4-21-1,1>>^ Ouvindo o cananeu, rei de Arade, que habitava no Neguebe, que Israel vinha pelo caminho de Atarim, pelejou contra Israel e levou alguns deles cativos.

[[v4-21-2]]

^<<v4-21-2,2>>^ Então, Israel fez voto ao SENHOR, dizendo: Se, de fato, entregares este povo nas minhas mãos, destruirei totalmente as suas cidades.

[[v4-21-3]]

^<<v4-21-3,3>>^ Ouviu, pois, o SENHOR a voz de Israel e lhe entregou os cananeus. Os israelitas os destruíram totalmente, a eles e a suas cidades; e aquele lugar se chamou Horma.

[[v4-21-4]]

^<<v4-21-4,4>>^ Então, partiram do monte Hor, pelo caminho do mar Vermelho, a rodear a terra de Edom, porém o povo se tornou impaciente no caminho.

[[v4-21-5]]

^<<v4-21-5,5>>^ E o povo falou contra Deus e contra Moisés: Por que nos fizestes subir do Egito, para que morramos neste deserto, onde não há pão nem água? E a nossa alma tem fastio deste pão vil.

[[v4-21-6]]

^<<v4-21-6,6>>^ Então, o SENHOR mandou entre o povo serpentes abrasadoras, que mordiam o povo; e morreram muitos do povo de Israel.

[[v4-21-7]]

^<<v4-21-7,7>>^ Veio o povo a Moisés e disse: Havemos pecado, porque temos falado contra o SENHOR e contra ti; ora ao SENHOR que tire de nós as serpentes. Então, Moisés orou pelo povo.

[[v4-21-8]]

^<<v4-21-8,8>>^ Disse o SENHOR a Moisés: Faze uma serpente abrasadora, põe-na sobre uma haste, e será que todo mordido que a mirar viverá.

[[v4-21-9]]

^<<v4-21-9,9>>^ Fez Moisés uma serpente de bronze e a pôs sobre uma haste; sendo alguém mordido por alguma serpente, se olhava para a de bronze, sarava.

[[v4-21-10]]

^<<v4-21-10,10>>^ Então, partiram os filhos de Israel e se acamparam em Obote.

[[v4-21-11]]

^<<v4-21-11,11>>^ Depois, partiram de Obote e se acamparam em Ijé-Abarim, no deserto que está defronte de Moabe, para o nascente.

[[v4-21-12]]

^<<v4-21-12,12>>^ Dali, partiram e se acamparam no vale de Zerede.

[[v4-21-13]]

^<<v4-21-13,13>>^ E, dali, partiram e se acamparam na outra margem do Arnom, que está no deserto que se estende do território dos amorreus; porque o Arnom é o limite de Moabe, entre Moabe e os amorreus.

[[v4-21-14]]

^<<v4-21-14,14>>^ Pelo que se diz no Livro das Guerras do SENHOR: Vaebe em Sufa, e os vales do Arnom,

[[v4-21-15]]

^<<v4-21-15,15>>^ e o declive dos vales que se inclina para a sede de Ar e se encosta aos limites de Moabe.

[[v4-21-16]]

^<<v4-21-16,16>>^ Dali partiram para Beer; este é o poço do qual disse o SENHOR a Moisés: Ajunta o povo, e lhe darei água.

[[v4-21-17]]

^<<v4-21-17,17>>^ Então, cantou Israel este cântico: Brota, ó poço! Entoai-lhe cânticos!

[[v4-21-18]]

^<<v4-21-18,18>>^ Poço que os príncipes cavaram, que os nobres do povo abriram, com o cetro, com os seus bordões. Do deserto, partiram para Matana.

[[v4-21-19]]

^<<v4-21-19,19>>^ E, de Matana, para Naaliel e, de Naaliel, para Bamote.

[[v4-21-20]]

^<<v4-21-20,20>>^ De Bamote, ao vale que está no campo de Moabe, no cimo de Pisga, que olha para o deserto.

[[v4-21-21]]

^<<v4-21-21,21>>^ Então, Israel mandou mensageiros a Seom, rei dos amorreus, dizendo:

[[v4-21-22]]

^<<v4-21-22,22>>^ Deixa-me passar pela tua terra; não nos desviaremos pelos campos nem pelas vinhas; as águas dos poços não beberemos; iremos pela estrada real até que passemos o teu país.

[[v4-21-23]]

^<<v4-21-23,23>>^ Porém Seom não deixou passar a Israel pelo seu país; antes, reuniu todo o seu povo, e saiu ao encontro de Israel ao deserto, e veio a Jasa, e pelejou contra Israel.

[[v4-21-24]]

^<<v4-21-24,24>>^ Mas Israel o feriu a fio de espada e tomou posse de sua terra, desde o Arnom até ao Jaboque, até aos filhos de Amom, cuja fronteira era fortificada.

[[v4-21-25]]

^<<v4-21-25,25>>^ Assim, Israel tomou todas estas cidades dos amorreus e habitou em todas elas, em Hesbom e em todas as suas aldeias.

[[v4-21-26]]

^<<v4-21-26,26>>^ Porque Hesbom era cidade de Seom, rei dos amorreus, que tinha pelejado contra o precedente rei dos moabitas, de cuja mão tomara toda a sua terra até ao Arnom.

[[v4-21-27]]

^<<v4-21-27,27>>^ Pelo que dizem os poetas: Vinde a Hesbom! Edifique-se, estabeleça-se a cidade de Seom!

[[v4-21-28]]

^<<v4-21-28,28>>^ Porque fogo saiu de Hesbom, e chama, da cidade de Seom, e consumiu a Ar, de Moabe, e os senhores dos altos do Arnom.

[[v4-21-29]]

^<<v4-21-29,29>>^ Ai de ti, Moabe! Perdido estás, povo de Quemos; entregou seus filhos como fugitivos e suas filhas, como cativas a Seom, rei dos amorreus.

[[v4-21-30]]

^<<v4-21-30,30>>^ Nós os asseteamos; estão destruídos desde Hesbom até Dibom; e os assolamos até Nofa e com fogo, até Medeba.

[[v4-21-31]]

^<<v4-21-31,31>>^ Assim, Israel habitou na terra dos amorreus.

[[v4-21-32]]

^<<v4-21-32,32>>^ Depois, mandou Moisés espiar a Jazer, tomaram as suas aldeias e desapossaram os amorreus que se achavam ali.

[[v4-21-33]]

^<<v4-21-33,33>>^ Então, voltaram e subiram o caminho de Basã; e Ogue, rei de Basã, saiu contra eles, ele e todo o seu povo, à peleja em Edrei.

[[v4-21-34]]

^<<v4-21-34,34>>^ Disse o SENHOR a Moisés: Não o temas, porque eu o dei na tua mão, a ele, e a todo o seu povo, e a sua terra; e far-lhe-ás como fizeste a Seom, rei dos amorreus, que habitava em Hesbom.

[[v4-21-35]]

^<<v4-21-35,35>>^ De tal maneira o feriram, a ele, e a seus filhos, e a todo o seu povo, que nenhum deles escapou; e lhe tomaram posse da terra.

'''

xref:004-numeros/004-numeros-020.adoc#v4-20-0[&#60; Capítulo Anterior] | <<v4-21-0,Topo>> | xref:004-numeros/004-numeros-022.adoc#v4-22-0[Próximo Capítulo &#62;]