include::./index.adoc[]

[[v4-23-0]]
=== Números, 23
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-23-1]]

^<<v4-23-1,1>>^ Então, Balaão disse a Balaque: Edifica-me, aqui, sete altares e prepara-me sete novilhos e sete carneiros.

[[v4-23-2]]

^<<v4-23-2,2>>^ Fez, pois, Balaque como Balaão dissera; e Balaque e Balaão ofereceram um novilho e um carneiro sobre cada altar.

[[v4-23-3]]

^<<v4-23-3,3>>^ Disse mais Balaão a Balaque: Fica-te junto do teu holocausto, e eu irei; porventura, o SENHOR me sairá ao encontro, e o que me mostrar to notificarei. Então, subiu a um morro desnudo.

[[v4-23-4]]

^<<v4-23-4,4>>^ Encontrando-se Deus com Balaão, este lhe disse: Preparei sete altares e sobre cada um ofereci um novilho e um carneiro.

[[v4-23-5]]

^<<v4-23-5,5>>^ Então, o SENHOR pôs a palavra na boca de Balaão e disse: Torna para Balaque e falarás assim.

[[v4-23-6]]

^<<v4-23-6,6>>^ E, tornando para ele, eis que estava junto do seu holocausto, ele e todos os príncipes dos moabitas.

[[v4-23-7]]

^<<v4-23-7,7>>^ Então, proferiu a sua palavra e disse: Balaque me fez vir de Arã, o rei de Moabe, dos montes do Oriente; vem, amaldiçoa-me a Jacó, e vem, denuncia a Israel.

[[v4-23-8]]

^<<v4-23-8,8>>^ Como posso amaldiçoar a quem Deus não amaldiçoou? Como posso denunciar a quem o SENHOR não denunciou?

[[v4-23-9]]

^<<v4-23-9,9>>^ Pois do cimo das penhas vejo Israel e dos outeiros o contemplo: eis que é povo que habita só e não será reputado entre as nações.

[[v4-23-10]]

^<<v4-23-10,10>>^ Quem contou o pó de Jacó ou enumerou a quarta parte de Israel? Que eu morra a morte dos justos, e o meu fim seja como o dele.

[[v4-23-11]]

^<<v4-23-11,11>>^ Então, disse Balaque a Balaão: Que me fizeste? Chamei-te para amaldiçoar os meus inimigos, mas eis que somente os abençoaste.

[[v4-23-12]]

^<<v4-23-12,12>>^ Mas ele respondeu: Porventura, não terei cuidado de falar o que o SENHOR pôs na minha boca?

[[v4-23-13]]

^<<v4-23-13,13>>^ Então, Balaque lhe disse: Rogo-te que venhas comigo a outro lugar, donde verás o povo; verás somente a parte mais próxima dele e não o verás todo; e amaldiçoa-mo dali.

[[v4-23-14]]

^<<v4-23-14,14>>^ Levou-o consigo ao campo de Zofim, ao cimo de Pisga; e edificou sete altares e sobre cada um ofereceu um novilho e um carneiro.

[[v4-23-15]]

^<<v4-23-15,15>>^ Então, disse Balaão a Balaque: Fica, aqui, junto do teu holocausto, e eu irei ali ao encontro do SENHOR.

[[v4-23-16]]

^<<v4-23-16,16>>^ Encontrando-se o SENHOR com Balaão, pôs-lhe na boca a palavra e disse: Torna para Balaque e assim falarás.

[[v4-23-17]]

^<<v4-23-17,17>>^ Vindo a ele, eis que estava junto do holocausto, e os príncipes dos moabitas, com ele. Perguntou-lhe, pois, Balaque: Que falou o SENHOR?

[[v4-23-18]]

^<<v4-23-18,18>>^ Então, proferiu a sua palavra e disse: Levanta-te, Balaque, e ouve; escuta-me, filho de Zipor:

[[v4-23-19]]

^<<v4-23-19,19>>^ Deus não é homem, para que minta; nem filho de homem, para que se arrependa. Porventura, tendo ele prometido, não o fará? Ou, tendo falado, não o cumprirá?

[[v4-23-20]]

^<<v4-23-20,20>>^ Eis que para abençoar recebi ordem; ele abençoou, não o posso revogar.

[[v4-23-21]]

^<<v4-23-21,21>>^ Não viu iniquidade em Jacó, nem contemplou desventura em Israel; o SENHOR, seu Deus, está com ele, no meio dele se ouvem aclamações ao seu Rei.

[[v4-23-22]]

^<<v4-23-22,22>>^ Deus os tirou do Egito; as forças deles são como as do boi selvagem.

[[v4-23-23]]

^<<v4-23-23,23>>^ Pois contra Jacó não vale encantamento, nem adivinhação contra Israel; agora, se poderá dizer de Jacó e de Israel: Que coisas tem feito Deus!

[[v4-23-24]]

^<<v4-23-24,24>>^ Eis que o povo se levanta como leoa e se ergue como leão; não se deita até que devore a presa e beba o sangue dos que forem mortos.

[[v4-23-25]]

^<<v4-23-25,25>>^ Então, disse Balaque a Balaão: Nem o amaldiçoarás, nem o abençoarás.

[[v4-23-26]]

^<<v4-23-26,26>>^ Porém Balaão respondeu e disse a Balaque: Não te disse eu: tudo o que o SENHOR falar, isso farei?

[[v4-23-27]]

^<<v4-23-27,27>>^ Disse mais Balaque a Balaão: Ora, vem, e te levarei a outro lugar; porventura, parecerá bem aos olhos de Deus que dali mo amaldiçoes.

[[v4-23-28]]

^<<v4-23-28,28>>^ Então, Balaque levou Balaão consigo ao cimo de Peor, que olha para o lado do deserto.

[[v4-23-29]]

^<<v4-23-29,29>>^ Balaão disse a Balaque: Edifica-me, aqui, sete altares e prepara-me sete novilhos e sete carneiros.

[[v4-23-30]]

^<<v4-23-30,30>>^ Balaque, pois, fez como dissera Balaão e ofereceu sobre cada altar um novilho e um carneiro.

'''

xref:004-numeros/004-numeros-022.adoc#v4-22-0[&#60; Capítulo Anterior] | <<v4-23-0,Topo>> | xref:004-numeros/004-numeros-024.adoc#v4-24-0[Próximo Capítulo &#62;]