include::./index.adoc[]

[[v4-25-0]]
=== Números, 25
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-25-1]]

^<<v4-25-1,1>>^ Habitando Israel em Sitim, começou o povo a prostituir-se com as filhas dos moabitas.

[[v4-25-2]]

^<<v4-25-2,2>>^ Estas convidaram o povo aos sacrifícios dos seus deuses; e o povo comeu e inclinou-se aos deuses delas.

[[v4-25-3]]

^<<v4-25-3,3>>^ Juntando-se Israel a Baal-Peor, a ira do SENHOR se acendeu contra Israel.

[[v4-25-4]]

^<<v4-25-4,4>>^ Disse o SENHOR a Moisés: Toma todos os cabeças do povo e enforca-os ao SENHOR ao ar livre, e a ardente ira do SENHOR se retirará de Israel.

[[v4-25-5]]

^<<v4-25-5,5>>^ Então, Moisés disse aos juízes de Israel: Cada um mate os homens da sua tribo que se juntaram a Baal-Peor.

[[v4-25-6]]

^<<v4-25-6,6>>^ Eis que um homem dos filhos de Israel veio e trouxe a seus irmãos uma midianita perante os olhos de Moisés e de toda a congregação dos filhos de Israel, enquanto eles choravam diante da tenda da congregação.

[[v4-25-7]]

^<<v4-25-7,7>>^ Vendo isso Fineias, filho de Eleazar, o filho de Arão, o sacerdote, levantou-se do meio da congregação, e, pegando uma lança,

[[v4-25-8]]

^<<v4-25-8,8>>^ foi após o homem israelita até ao interior da tenda, e os atravessou, ao homem israelita e à mulher, a ambos pelo ventre; então, a praga cessou de sobre os filhos de Israel.

[[v4-25-9]]

^<<v4-25-9,9>>^ Os que morreram da praga foram vinte e quatro mil.

[[v4-25-10]]

^<<v4-25-10,10>>^ Então, disse o SENHOR a Moisés:

[[v4-25-11]]

^<<v4-25-11,11>>^ Fineias, filho de Eleazar, filho de Arão, o sacerdote, desviou a minha ira de sobre os filhos de Israel, pois estava animado com o meu zelo entre eles; de sorte que, no meu zelo, não consumi os filhos de Israel.

[[v4-25-12]]

^<<v4-25-12,12>>^ Portanto, dize: Eis que lhe dou a minha aliança de paz.

[[v4-25-13]]

^<<v4-25-13,13>>^ E ele e a sua descendência depois dele terão a aliança do sacerdócio perpétuo; porquanto teve zelo pelo seu Deus e fez expiação pelos filhos de Israel.

[[v4-25-14]]

^<<v4-25-14,14>>^ O nome do israelita que foi morto (morto com a midianita) era Zinri, filho de Salu, príncipe da casa paterna dos simeonitas.

[[v4-25-15]]

^<<v4-25-15,15>>^ O nome da mulher midianita que foi morta era Cosbi, filha de Zur, cabeça do povo da casa paterna entre os midianitas.

[[v4-25-16]]

^<<v4-25-16,16>>^ Disse mais o SENHOR a Moisés:

[[v4-25-17]]

^<<v4-25-17,17>>^ Afligireis os midianitas e os ferireis,

[[v4-25-18]]

^<<v4-25-18,18>>^ porque eles vos afligiram a vós outros quando vos enganaram no caso de Peor e no caso de Cosbi, filha do príncipe dos midianitas, irmã deles, que foi morta no dia da praga no caso de Peor.

'''

xref:004-numeros/004-numeros-024.adoc#v4-24-0[&#60; Capítulo Anterior] | <<v4-25-0,Topo>> | xref:004-numeros/004-numeros-026.adoc#v4-26-0[Próximo Capítulo &#62;]