include::./index.adoc[]

[[v4-8-0]]
=== Números, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-8-1]]

^<<v4-8-1,1>>^ Disse o SENHOR a Moisés:

[[v4-8-2]]

^<<v4-8-2,2>>^ Fala a Arão e dize-lhe: Quando colocares as lâmpadas, seja de tal maneira que venham as sete a alumiar defronte do candelabro.

[[v4-8-3]]

^<<v4-8-3,3>>^ E Arão fez assim; colocou as lâmpadas para que alumiassem defronte do candelabro, como o SENHOR ordenara a Moisés.

[[v4-8-4]]

^<<v4-8-4,4>>^ O candelabro era feito de ouro batido desde o seu pedestal até às suas flores; segundo o modelo que o SENHOR mostrara a Moisés, assim ele fez o candelabro.

[[v4-8-5]]

^<<v4-8-5,5>>^ Disse mais o SENHOR a Moisés:

[[v4-8-6]]

^<<v4-8-6,6>>^ Toma os levitas do meio dos filhos de Israel e purifica-os;

[[v4-8-7]]

^<<v4-8-7,7>>^ assim lhes farás, para os purificar: asperge sobre eles a água da expiação; e sobre todo o seu corpo farão passar a navalha, lavarão as suas vestes e se purificarão;

[[v4-8-8]]

^<<v4-8-8,8>>^ e tomarão um novilho, com a sua oferta de manjares de flor de farinha, amassada com azeite; tu, porém, tomarás outro novilho para oferta pelo pecado.

[[v4-8-9]]

^<<v4-8-9,9>>^ Farás chegar os levitas perante a tenda da congregação; e ajuntarás toda a congregação dos filhos de Israel.

[[v4-8-10]]

^<<v4-8-10,10>>^ Quando, pois, fizerem chegar os levitas perante o SENHOR, os filhos de Israel porão as mãos sobre eles.

[[v4-8-11]]

^<<v4-8-11,11>>^ Arão apresentará os levitas como oferta movida perante o SENHOR, da parte dos filhos de Israel; e serão para o serviço do SENHOR.

[[v4-8-12]]

^<<v4-8-12,12>>^ Os levitas porão as mãos sobre a cabeça dos novilhos; e tu sacrificarás um para oferta pelo pecado e o outro para holocausto ao SENHOR, para fazer expiação pelos levitas.

[[v4-8-13]]

^<<v4-8-13,13>>^ Porás os levitas perante Arão e perante os seus filhos e os apresentarás por oferta movida ao SENHOR.

[[v4-8-14]]

^<<v4-8-14,14>>^ E separarás os levitas do meio dos filhos de Israel; os levitas serão meus.

[[v4-8-15]]

^<<v4-8-15,15>>^ Depois disso, entrarão os levitas para fazerem o serviço da tenda da congregação; e tu os purificarás e, por oferta movida, os apresentarás,

[[v4-8-16]]

^<<v4-8-16,16>>^ porquanto eles dentre os filhos de Israel me são dados; em lugar de todo aquele que abre a madre, do primogênito de cada um dos filhos de Israel, para mim os tomei.

[[v4-8-17]]

^<<v4-8-17,17>>^ Porque meu é todo primogênito entre os filhos de Israel, tanto de homens como de animais; no dia em que, na terra do Egito, feri todo primogênito, os consagrei para mim.

[[v4-8-18]]

^<<v4-8-18,18>>^ Tomei os levitas em lugar de todo primogênito entre os filhos de Israel.

[[v4-8-19]]

^<<v4-8-19,19>>^ E os levitas, dados a Arão e a seus filhos, dentre os filhos de Israel, entreguei-os para fazerem o serviço dos filhos de Israel na tenda da congregação e para fazerem expiação por eles, para que não haja praga entre o povo de Israel, chegando-se os filhos de Israel ao santuário.

[[v4-8-20]]

^<<v4-8-20,20>>^ E assim fez Moisés, e Arão, e toda a congregação dos filhos de Israel com os levitas; segundo tudo o que o SENHOR ordenara a Moisés acerca dos levitas, assim lhes fizeram os filhos de Israel.

[[v4-8-21]]

^<<v4-8-21,21>>^ Os levitas se purificaram e lavaram as suas vestes, e Arão os apresentou por oferta movida perante o SENHOR e fez expiação por eles, para purificá-los.

[[v4-8-22]]

^<<v4-8-22,22>>^ Depois disso, chegaram os levitas, para fazerem o seu serviço na tenda da congregação, perante Arão e seus filhos; como o SENHOR ordenara a Moisés acerca dos levitas, assim lhes fizeram.

[[v4-8-23]]

^<<v4-8-23,23>>^ Disse mais o SENHOR a Moisés:

[[v4-8-24]]

^<<v4-8-24,24>>^ Isto é o que toca aos levitas: da idade de vinte e cinco anos para cima entrarão, para fazerem o seu serviço na tenda da congregação;

[[v4-8-25]]

^<<v4-8-25,25>>^ mas desde a idade de cinquenta anos desobrigar-se-ão do serviço e nunca mais servirão;

[[v4-8-26]]

^<<v4-8-26,26>>^ porém ajudarão aos seus irmãos na tenda da congregação, no tocante ao cargo deles; não terão mais serviço. Assim farás com os levitas quanto aos seus deveres.

'''

xref:004-numeros/004-numeros-007.adoc#v4-7-0[&#60; Capítulo Anterior] | <<v4-8-0,Topo>> | xref:004-numeros/004-numeros-009.adoc#v4-9-0[Próximo Capítulo &#62;]