include::./index.adoc[]

[[v4-15-0]]
=== Números, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-15-1]]

^<<v4-15-1,1>>^ Disse o SENHOR a Moisés:

[[v4-15-2]]

^<<v4-15-2,2>>^ Fala aos filhos de Israel e dize-lhes: Quando entrardes na terra das vossas habitações, que eu vos hei de dar,

[[v4-15-3]]

^<<v4-15-3,3>>^ e ao SENHOR fizerdes oferta queimada, holocausto ou sacrifício, em cumprimento de um voto ou em oferta voluntária, ou, nas vossas festas fixas, apresentardes ao SENHOR aroma agradável com o sacrifício de gado e ovelhas,

[[v4-15-4]]

^<<v4-15-4,4>>^ então, aquele que apresentar a sua oferta ao SENHOR, por oferta de manjares, trará a décima parte de um efa de flor de farinha, misturada com a quarta parte de um him de azeite.

[[v4-15-5]]

^<<v4-15-5,5>>^ E de vinho para libação prepararás a quarta parte de um him para cada cordeiro, além do holocausto ou do sacrifício.

[[v4-15-6]]

^<<v4-15-6,6>>^ Para cada carneiro prepararás uma oferta de manjares de duas décimas de um efa de flor de farinha, misturada com a terça parte de um him de azeite;

[[v4-15-7]]

^<<v4-15-7,7>>^ e de vinho para a libação oferecerás a terça parte de um him ao SENHOR, em aroma agradável.

[[v4-15-8]]

^<<v4-15-8,8>>^ Quando preparares novilho para holocausto ou sacrifício, em cumprimento de um voto ou um sacrifício pacífico ao SENHOR,

[[v4-15-9]]

^<<v4-15-9,9>>^ com o novilho, trarás uma oferta de manjares de três décimas de um efa de flor de farinha, misturada com a metade de um him de azeite,

[[v4-15-10]]

^<<v4-15-10,10>>^ e de vinho para a libação trarás a metade de um him, oferta queimada de aroma agradável ao SENHOR.

[[v4-15-11]]

^<<v4-15-11,11>>^ Assim se fará com todos os novilhos, carneiros, cordeiros e bodes.

[[v4-15-12]]

^<<v4-15-12,12>>^ Segundo o número que oferecerdes, assim o fareis para cada um.

[[v4-15-13]]

^<<v4-15-13,13>>^ Todos os naturais assim farão estas coisas, trazendo oferta queimada de aroma agradável ao SENHOR.

[[v4-15-14]]

^<<v4-15-14,14>>^ Se também morar convosco algum estrangeiro ou quem quer que estiver entre vós durante as vossas gerações, e trouxer uma oferta queimada de aroma agradável ao SENHOR, como vós fizerdes, assim fará ele.

[[v4-15-15]]

^<<v4-15-15,15>>^ Quanto à congregação, haja apenas um estatuto, tanto para vós outros como para o estrangeiro que morar entre vós, por estatuto perpétuo nas vossas gerações; como vós sois, assim será o estrangeiro perante o SENHOR.

[[v4-15-16]]

^<<v4-15-16,16>>^ A mesma lei e o mesmo rito haverá para vós outros e para o estrangeiro que mora convosco.

[[v4-15-17]]

^<<v4-15-17,17>>^ Disse mais o SENHOR a Moisés:

[[v4-15-18]]

^<<v4-15-18,18>>^ Fala aos filhos de Israel e dize-lhes: Quando chegardes à terra em que vos farei entrar,

[[v4-15-19]]

^<<v4-15-19,19>>^ ao comerdes do pão da terra, apresentareis oferta ao SENHOR.

[[v4-15-20]]

^<<v4-15-20,20>>^ Das primícias da vossa farinha grossa apresentareis um bolo como oferta; como oferta da eira, assim o apresentareis.

[[v4-15-21]]

^<<v4-15-21,21>>^ Das primícias da vossa farinha grossa apresentareis ao SENHOR oferta nas vossas gerações.

[[v4-15-22]]

^<<v4-15-22,22>>^ Quando errardes e não cumprirdes todos estes mandamentos que o SENHOR falou a Moisés,

[[v4-15-23]]

^<<v4-15-23,23>>^ sim, tudo quanto o SENHOR vos tem mandado por Moisés, desde o dia em que o SENHOR ordenou e daí em diante, nas vossas gerações,

[[v4-15-24]]

^<<v4-15-24,24>>^ será que, quando se fizer alguma coisa por ignorância e for encoberta aos olhos da congregação, toda a congregação oferecerá um novilho, para holocausto de aroma agradável ao SENHOR, com a sua oferta de manjares e libação, segundo o rito, e um bode, para oferta pelo pecado.

[[v4-15-25]]

^<<v4-15-25,25>>^ O sacerdote fará expiação por toda a congregação dos filhos de Israel, e lhes será perdoado, porquanto foi erro, e trouxeram a sua oferta, oferta queimada ao SENHOR, e a sua oferta pelo pecado perante o SENHOR, por causa do seu erro.

[[v4-15-26]]

^<<v4-15-26,26>>^ Será, pois, perdoado a toda a congregação dos filhos de Israel e mais ao estrangeiro que habita no meio deles, pois no erro foi envolvido todo o povo.

[[v4-15-27]]

^<<v4-15-27,27>>^ Se alguma pessoa pecar por ignorância, apresentará uma cabra de um ano como oferta pelo pecado.

[[v4-15-28]]

^<<v4-15-28,28>>^ O sacerdote fará expiação pela pessoa que errou, quando pecar por ignorância perante o SENHOR, fazendo expiação por ela, e lhe será perdoado.

[[v4-15-29]]

^<<v4-15-29,29>>^ Para o natural dos filhos de Israel e para o estrangeiro que no meio deles habita, tereis a mesma lei para aquele que isso fizer por ignorância.

[[v4-15-30]]

^<<v4-15-30,30>>^ Mas a pessoa que fizer alguma coisa atrevidamente, quer seja dos naturais quer dos estrangeiros, injuria ao SENHOR; tal pessoa será eliminada do meio do seu povo,

[[v4-15-31]]

^<<v4-15-31,31>>^ pois desprezou a palavra do SENHOR e violou o seu mandamento; será eliminada essa pessoa, e a sua iniquidade será sobre ela.

[[v4-15-32]]

^<<v4-15-32,32>>^ Estando, pois, os filhos de Israel no deserto, acharam um homem apanhando lenha no dia de sábado.

[[v4-15-33]]

^<<v4-15-33,33>>^ Os que o acharam apanhando lenha o trouxeram a Moisés, e a Arão, e a toda a congregação.

[[v4-15-34]]

^<<v4-15-34,34>>^ Meteram-no em guarda, porquanto ainda não estava declarado o que se lhe devia fazer.

[[v4-15-35]]

^<<v4-15-35,35>>^ Então, disse o SENHOR a Moisés: Tal homem será morto; toda a congregação o apedrejará fora do arraial.

[[v4-15-36]]

^<<v4-15-36,36>>^ Levou-o, pois, toda a congregação para fora do arraial, e o apedrejaram; e ele morreu, como o SENHOR ordenara a Moisés.

[[v4-15-37]]

^<<v4-15-37,37>>^ Disse o SENHOR a Moisés:

[[v4-15-38]]

^<<v4-15-38,38>>^ Fala aos filhos de Israel e dize-lhes que nos cantos das suas vestes façam borlas pelas suas gerações; e as borlas em cada canto, presas por um cordão azul.

[[v4-15-39]]

^<<v4-15-39,39>>^ E as borlas estarão ali para que, vendo-as, vos lembreis de todos os mandamentos do SENHOR e os cumprais; não seguireis os desejos do vosso coração, nem os dos vossos olhos, após os quais andais adulterando,

[[v4-15-40]]

^<<v4-15-40,40>>^ para que vos lembreis de todos os meus mandamentos, e os cumprais, e santos sereis a vosso Deus.

[[v4-15-41]]

^<<v4-15-41,41>>^ Eu sou o SENHOR, vosso Deus, que vos tirei da terra do Egito, para vos ser por Deus. Eu sou o SENHOR, vosso Deus.

'''

xref:004-numeros/004-numeros-014.adoc#v4-14-0[&#60; Capítulo Anterior] | <<v4-15-0,Topo>> | xref:004-numeros/004-numeros-016.adoc#v4-16-0[Próximo Capítulo &#62;]