include::./index.adoc[]

[[v4-9-0]]
=== Números, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-9-1]]

^<<v4-9-1,1>>^ Falou o SENHOR a Moisés no deserto do Sinai, no ano segundo da sua saída da terra do Egito, no mês primeiro, dizendo:

[[v4-9-2]]

^<<v4-9-2,2>>^ Celebrem os filhos de Israel a Páscoa a seu tempo.

[[v4-9-3]]

^<<v4-9-3,3>>^ No dia catorze deste mês, ao crepúsculo da tarde, a seu tempo a celebrareis; segundo todos os seus estatutos e segundo todos os seus ritos, a celebrareis.

[[v4-9-4]]

^<<v4-9-4,4>>^ Disse, pois, Moisés aos filhos de Israel que celebrassem a Páscoa.

[[v4-9-5]]

^<<v4-9-5,5>>^ Então, celebraram a Páscoa no dia catorze do mês primeiro, ao crepúsculo da tarde, no deserto do Sinai; segundo tudo o que o SENHOR ordenara a Moisés, assim fizeram os filhos de Israel.

[[v4-9-6]]

^<<v4-9-6,6>>^ Houve alguns que se acharam imundos por terem tocado o cadáver de um homem, de maneira que não puderam celebrar a Páscoa naquele dia; por isso, chegando-se perante Moisés e Arão,

[[v4-9-7]]

^<<v4-9-7,7>>^ disseram-lhes: Estamos imundos por termos tocado o cadáver de um homem; por que havemos de ser privados de apresentar a oferta do SENHOR, a seu tempo, no meio dos filhos de Israel?

[[v4-9-8]]

^<<v4-9-8,8>>^ Respondeu-lhes Moisés: Esperai, e ouvirei o que o SENHOR vos ordenará.

[[v4-9-9]]

^<<v4-9-9,9>>^ Então, disse o SENHOR a Moisés:

[[v4-9-10]]

^<<v4-9-10,10>>^ Fala aos filhos de Israel, dizendo: Quando alguém entre vós ou entre as vossas gerações achar-se imundo por causa de um morto ou se achar em jornada longe de vós, contudo, ainda celebrará a Páscoa ao SENHOR.

[[v4-9-11]]

^<<v4-9-11,11>>^ No mês segundo, no dia catorze, no crepúsculo da tarde, a celebrarão; com pães asmos e ervas amargas a comerão.

[[v4-9-12]]

^<<v4-9-12,12>>^ Dela nada deixarão até à manhã e dela não quebrarão osso algum; segundo todo o estatuto da Páscoa, a celebrarão.

[[v4-9-13]]

^<<v4-9-13,13>>^ Porém, se um homem achar-se limpo, e não estiver de caminho, e deixar de celebrar a Páscoa, essa alma será eliminada do seu povo, porquanto não apresentou a oferta do SENHOR, a seu tempo; tal homem levará sobre si o seu pecado.

[[v4-9-14]]

^<<v4-9-14,14>>^ Se um estrangeiro habitar entre vós e também celebrar a Páscoa ao SENHOR, segundo o estatuto da Páscoa e segundo o seu rito, assim a celebrará; um só estatuto haverá para vós outros, tanto para o estrangeiro como para o natural da terra.

[[v4-9-15]]

^<<v4-9-15,15>>^ No dia em que foi erigido o tabernáculo, a nuvem o cobriu, a saber, a tenda do Testemunho; e, à tarde, estava sobre o tabernáculo uma aparência de fogo até à manhã.

[[v4-9-16]]

^<<v4-9-16,16>>^ Assim era de contínuo: a nuvem o cobria, e, de noite, havia aparência de fogo.

[[v4-9-17]]

^<<v4-9-17,17>>^ Quando a nuvem se erguia de sobre a tenda, os filhos de Israel se punham em marcha; e, no lugar onde a nuvem parava, aí os filhos de Israel se acampavam.

[[v4-9-18]]

^<<v4-9-18,18>>^ Segundo o mandado do SENHOR, os filhos de Israel partiam e, segundo o mandado do SENHOR, se acampavam; por todo o tempo em que a nuvem pairava sobre o tabernáculo, permaneciam acampados.

[[v4-9-19]]

^<<v4-9-19,19>>^ Quando a nuvem se detinha muitos dias sobre o tabernáculo, então, os filhos de Israel cumpriam a ordem do SENHOR e não partiam.

[[v4-9-20]]

^<<v4-9-20,20>>^ Às vezes, a nuvem ficava poucos dias sobre o tabernáculo; então, segundo o mandado do SENHOR, permaneciam e, segundo a ordem do SENHOR, partiam.

[[v4-9-21]]

^<<v4-9-21,21>>^ Às vezes, a nuvem ficava desde a tarde até à manhã; quando, pela manhã, a nuvem se erguia, punham-se em marcha; quer de dia, quer de noite, erguendo-se a nuvem, partiam.

[[v4-9-22]]

^<<v4-9-22,22>>^ Se a nuvem se detinha sobre o tabernáculo por dois dias, ou um mês, ou por mais tempo, enquanto pairava sobre ele, os filhos de Israel permaneciam acampados e não se punham em marcha; mas, erguendo-se ela, partiam.

[[v4-9-23]]

^<<v4-9-23,23>>^ Segundo o mandado do SENHOR, se acampavam e, segundo o mandado do SENHOR, se punham em marcha; cumpriam o seu dever para com o SENHOR, segundo a ordem do SENHOR por intermédio de Moisés.

'''

xref:004-numeros/004-numeros-008.adoc#v4-8-0[&#60; Capítulo Anterior] | <<v4-9-0,Topo>> | xref:004-numeros/004-numeros-010.adoc#v4-10-0[Próximo Capítulo &#62;]