include::./index.adoc[]

[[v4-13-0]]
=== Números, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-13-1]]

^<<v4-13-1,1>>^ Disse o SENHOR a Moisés:

[[v4-13-2]]

^<<v4-13-2,2>>^ Envia homens que espiem a terra de Canaã, que eu hei de dar aos filhos de Israel; de cada tribo de seus pais enviareis um homem, sendo cada qual príncipe entre eles.

[[v4-13-3]]

^<<v4-13-3,3>>^ Enviou-os Moisés do deserto de Parã, segundo o mandado do SENHOR; todos aqueles homens eram cabeças dos filhos de Israel.

[[v4-13-4]]

^<<v4-13-4,4>>^ São estes os seus nomes: da tribo de Rúben, Samua, filho de Zacur;

[[v4-13-5]]

^<<v4-13-5,5>>^ da tribo de Simeão, Safate, filho de Hori;

[[v4-13-6]]

^<<v4-13-6,6>>^ da tribo de Judá, Calebe, filho de Jefoné;

[[v4-13-7]]

^<<v4-13-7,7>>^ da tribo de Issacar, Jigeal, filho de José;

[[v4-13-8]]

^<<v4-13-8,8>>^ da tribo de Efraim, Oseias, filho de Num;

[[v4-13-9]]

^<<v4-13-9,9>>^ da tribo de Benjamim, Palti, filho de Rafu;

[[v4-13-10]]

^<<v4-13-10,10>>^ da tribo de Zebulom, Gadiel, filho de Sodi;

[[v4-13-11]]

^<<v4-13-11,11>>^ da tribo de José, pela tribo de Manassés, Gadi, filho de Susi;

[[v4-13-12]]

^<<v4-13-12,12>>^ da tribo de Dã, Amiel, filho de Gemali;

[[v4-13-13]]

^<<v4-13-13,13>>^ da tribo de Aser, Setur, filho de Micael;

[[v4-13-14]]

^<<v4-13-14,14>>^ da tribo de Naftali, Nabi, filho de Vofsi;

[[v4-13-15]]

^<<v4-13-15,15>>^ da tribo de Gade, Geuel, filho de Maqui.

[[v4-13-16]]

^<<v4-13-16,16>>^ São estes os nomes dos homens que Moisés enviou a espiar aquela terra; e a Oseias, filho de Num, Moisés chamou Josué.

[[v4-13-17]]

^<<v4-13-17,17>>^ Enviou-os, pois, Moisés a espiar a terra de Canaã; e disse-lhes: Subi ao Neguebe e penetrai nas montanhas.

[[v4-13-18]]

^<<v4-13-18,18>>^ Vede a terra, que tal é, e o povo que nela habita, se é forte ou fraco, se poucos ou muitos.

[[v4-13-19]]

^<<v4-13-19,19>>^ E qual é a terra em que habita, se boa ou má; e que tais são as cidades em que habita, se em arraiais, se em fortalezas.

[[v4-13-20]]

^<<v4-13-20,20>>^ Também qual é a terra, se fértil ou estéril, se nela há matas ou não. Tende ânimo e trazei do fruto da terra. Eram aqueles dias os dias das primícias das uvas.

[[v4-13-21]]

^<<v4-13-21,21>>^ Assim, subiram e espiaram a terra desde o deserto de Zim até Reobe, à entrada de Hamate.

[[v4-13-22]]

^<<v4-13-22,22>>^ E subiram pelo Neguebe e vieram até Hebrom; estavam ali Aimã, Sesai e Talmai, filhos de Anaque (Hebrom foi edificada sete anos antes de Zoã, no Egito).

[[v4-13-23]]

^<<v4-13-23,23>>^ Depois, vieram até ao vale de Escol e dali cortaram um ramo de vide com um cacho de uvas, o qual trouxeram dois homens numa vara, como também romãs e figos.

[[v4-13-24]]

^<<v4-13-24,24>>^ Esse lugar se chamou o vale de Escol, por causa do cacho que ali cortaram os filhos de Israel.

[[v4-13-25]]

^<<v4-13-25,25>>^ Ao cabo de quarenta dias, voltaram de espiar a terra,

[[v4-13-26]]

^<<v4-13-26,26>>^ caminharam e vieram a Moisés, e a Arão, e a toda a congregação dos filhos de Israel no deserto de Parã, a Cades; deram-lhes conta, a eles e a toda a congregação, e mostraram-lhes o fruto da terra.

[[v4-13-27]]

^<<v4-13-27,27>>^ Relataram a Moisés e disseram: Fomos à terra a que nos enviaste; e, verdadeiramente, mana leite e mel; este é o fruto dela.

[[v4-13-28]]

^<<v4-13-28,28>>^ O povo, porém, que habita nessa terra é poderoso, e as cidades, mui grandes e fortificadas; também vimos ali os filhos de Anaque.

[[v4-13-29]]

^<<v4-13-29,29>>^ Os amalequitas habitam na terra do Neguebe; os heteus, os jebuseus e os amorreus habitam na montanha; os cananeus habitam ao pé do mar e pela ribeira do Jordão.

[[v4-13-30]]

^<<v4-13-30,30>>^ Então, Calebe fez calar o povo perante Moisés e disse: Eia! Subamos e possuamos a terra, porque, certamente, prevaleceremos contra ela.

[[v4-13-31]]

^<<v4-13-31,31>>^ Porém os homens que com ele tinham subido disseram: Não poderemos subir contra aquele povo, porque é mais forte do que nós.

[[v4-13-32]]

^<<v4-13-32,32>>^ E, diante dos filhos de Israel, infamaram a terra que haviam espiado, dizendo: A terra pelo meio da qual passamos a espiar é terra que devora os seus moradores; e todo o povo que vimos nela são homens de grande estatura.

[[v4-13-33]]

^<<v4-13-33,33>>^ Também vimos ali gigantes (os filhos de Anaque são descendentes de gigantes), e éramos, aos nossos próprios olhos, como gafanhotos e assim também o éramos aos seus olhos.

'''

xref:004-numeros/004-numeros-012.adoc#v4-12-0[&#60; Capítulo Anterior] | <<v4-13-0,Topo>> | xref:004-numeros/004-numeros-014.adoc#v4-14-0[Próximo Capítulo &#62;]