include::./index.adoc[]

[[v4-16-0]]
=== Números, 16
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-16-1]]

^<<v4-16-1,1>>^ Corá, filho de Isar, filho de Coate, filho de Levi, tomou consigo a Datã e a Abirão, filhos de Eliabe, e a Om, filho de Pelete, filhos de Rúben.

[[v4-16-2]]

^<<v4-16-2,2>>^ Levantaram-se perante Moisés com duzentos e cinquenta homens dos filhos de Israel, príncipes da congregação, eleitos por ela, varões de renome,

[[v4-16-3]]

^<<v4-16-3,3>>^ e se ajuntaram contra Moisés e contra Arão e lhes disseram: Basta! Pois que toda a congregação é santa, cada um deles é santo, e o SENHOR está no meio deles; por que, pois, vos exaltais sobre a congregação do SENHOR?

[[v4-16-4]]

^<<v4-16-4,4>>^ Tendo ouvido isto, Moisés caiu sobre o seu rosto.

[[v4-16-5]]

^<<v4-16-5,5>>^ E falou a Corá e a todo o seu grupo, dizendo: Amanhã pela manhã, o SENHOR fará saber quem é dele e quem é o santo que ele fará chegar a si; aquele a quem escolher fará chegar a si.

[[v4-16-6]]

^<<v4-16-6,6>>^ Fazei isto: tomai vós incensários, Corá e todo o seu grupo;

[[v4-16-7]]

^<<v4-16-7,7>>^ e, pondo fogo neles amanhã, sobre eles deitai incenso perante o SENHOR; e será que o homem a quem o SENHOR escolher, este será o santo; basta-vos, filhos de Levi.

[[v4-16-8]]

^<<v4-16-8,8>>^ Disse mais Moisés a Corá: Ouvi agora, filhos de Levi:

[[v4-16-9]]

^<<v4-16-9,9>>^ acaso, é para vós outros coisa de somenos que o Deus de Israel vos separou da congregação de Israel, para vos fazer chegar a si, a fim de cumprirdes o serviço do tabernáculo do SENHOR e estardes perante a congregação para ministrar-lhe;

[[v4-16-10]]

^<<v4-16-10,10>>^ e te fez chegar, Corá, e todos os teus irmãos, os filhos de Levi, contigo? Ainda também procurais o sacerdócio?

[[v4-16-11]]

^<<v4-16-11,11>>^ Pelo que tu e todo o teu grupo juntos estais contra o SENHOR; e Arão, que é ele para que murmureis contra ele?

[[v4-16-12]]

^<<v4-16-12,12>>^ Mandou Moisés chamar a Datã e a Abirão, filhos de Eliabe; porém eles disseram: Não subiremos;

[[v4-16-13]]

^<<v4-16-13,13>>^ porventura, é coisa de somenos que nos fizeste subir de uma terra que mana leite e mel, para fazer-nos morrer neste deserto, senão que também queres fazer-te príncipe sobre nós?

[[v4-16-14]]

^<<v4-16-14,14>>^ Nem tampouco nos trouxeste a uma terra que mana leite e mel, nem nos deste campos e vinhas em herança; pensas que lançarás pó aos olhos destes homens? Pois não subiremos.

[[v4-16-15]]

^<<v4-16-15,15>>^ Então, Moisés irou-se muito e disse ao SENHOR: Não atentes para a sua oferta; nem um só jumento levei deles e a nenhum deles fiz mal.

[[v4-16-16]]

^<<v4-16-16,16>>^ Disse mais Moisés a Corá: Tu e todo o teu grupo, ponde-vos perante o SENHOR, tu, e eles, e Arão, amanhã.

[[v4-16-17]]

^<<v4-16-17,17>>^ Tomai cada um o seu incensário e neles ponde incenso; trazei-o, cada um o seu, perante o SENHOR, duzentos e cinquenta incensários; também tu e Arão, cada qual o seu.

[[v4-16-18]]

^<<v4-16-18,18>>^ Tomaram, pois, cada qual o seu incensário, neles puseram fogo, sobre eles deitaram incenso e se puseram perante a porta da tenda da congregação com Moisés e Arão.

[[v4-16-19]]

^<<v4-16-19,19>>^ Corá fez ajuntar contra eles todo o povo à porta da tenda da congregação; então, a glória do SENHOR apareceu a toda a congregação.

[[v4-16-20]]

^<<v4-16-20,20>>^ Disse o SENHOR a Moisés e a Arão:

[[v4-16-21]]

^<<v4-16-21,21>>^ Apartai-vos do meio desta congregação, e os consumirei num momento.

[[v4-16-22]]

^<<v4-16-22,22>>^ Mas eles se prostraram sobre o seu rosto e disseram: Ó Deus, Autor e Conservador de toda a vida, acaso, por pecar um só homem, indignar-te-ás contra toda esta congregação?

[[v4-16-23]]

^<<v4-16-23,23>>^ Respondeu o SENHOR a Moisés:

[[v4-16-24]]

^<<v4-16-24,24>>^ Fala a toda esta congregação, dizendo: Levantai-vos do redor da habitação de Corá, Datã e Abirão.

[[v4-16-25]]

^<<v4-16-25,25>>^ Então, se levantou Moisés e foi a Datã e a Abirão; e após ele foram os anciãos de Israel.

[[v4-16-26]]

^<<v4-16-26,26>>^ E disse à congregação: Desviai-vos, peço-vos, das tendas destes homens perversos e não toqueis nada do que é seu, para que não sejais arrebatados em todos os seus pecados.

[[v4-16-27]]

^<<v4-16-27,27>>^ Levantaram-se, pois, do redor da habitação de Corá, Datã e Abirão; e Datã e Abirão saíram e se puseram à porta da sua tenda, juntamente com suas mulheres, seus filhos e suas crianças.

[[v4-16-28]]

^<<v4-16-28,28>>^ Então, disse Moisés: Nisto conhecereis que o SENHOR me enviou a realizar todas estas obras, que não procedem de mim mesmo:

[[v4-16-29]]

^<<v4-16-29,29>>^ se morrerem estes como todos os homens morrem e se forem visitados por qualquer castigo como se dá com todos os homens, então, não sou enviado do SENHOR.

[[v4-16-30]]

^<<v4-16-30,30>>^ Mas, se o SENHOR criar alguma coisa inaudita, e a terra abrir a sua boca e os tragar com tudo o que é seu, e vivos descerem ao abismo, então, conhecereis que estes homens desprezaram o SENHOR.

[[v4-16-31]]

^<<v4-16-31,31>>^ E aconteceu que, acabando ele de falar todas estas palavras, a terra debaixo deles se fendeu,

[[v4-16-32]]

^<<v4-16-32,32>>^ abriu a sua boca e os tragou com as suas casas, como também todos os homens que pertenciam a Corá e todos os seus bens.

[[v4-16-33]]

^<<v4-16-33,33>>^ Eles e todos os que lhes pertenciam desceram vivos ao abismo; a terra os cobriu, e pereceram do meio da congregação.

[[v4-16-34]]

^<<v4-16-34,34>>^ Todo o Israel que estava ao redor deles fugiu do seu grito, porque diziam: Não suceda que a terra nos trague a nós também.

[[v4-16-35]]

^<<v4-16-35,35>>^ Procedente do SENHOR saiu fogo e consumiu os duzentos e cinquenta homens que ofereciam o incenso.

[[v4-16-36]]

^<<v4-16-36,36>>^ Disse o SENHOR a Moisés:

[[v4-16-37]]

^<<v4-16-37,37>>^ Dize a Eleazar, filho de Arão, o sacerdote, que tome os incensários do meio do incêndio e espalhe o fogo longe, porque santos são;

[[v4-16-38]]

^<<v4-16-38,38>>^ quanto aos incensários daqueles que pecaram contra a sua própria vida, deles se façam lâminas para cobertura do altar; porquanto os trouxeram perante o SENHOR; pelo que santos são e serão por sinal aos filhos de Israel.

[[v4-16-39]]

^<<v4-16-39,39>>^ Eleazar, o sacerdote, tomou os incensários de metal, que tinham trazido aqueles que foram queimados, e os converteram em lâminas para cobertura do altar,

[[v4-16-40]]

^<<v4-16-40,40>>^ por memorial para os filhos de Israel, para que nenhum estranho, que não for da descendência de Arão, se chegue para acender incenso perante o SENHOR; para que não seja como Corá e o seu grupo, como o SENHOR lhe tinha dito por Moisés.

[[v4-16-41]]

^<<v4-16-41,41>>^ Mas, no dia seguinte, toda a congregação dos filhos de Israel murmurou contra Moisés e contra Arão, dizendo: Vós matastes o povo do SENHOR.

[[v4-16-42]]

^<<v4-16-42,42>>^ Ajuntando-se o povo contra Moisés e Arão e virando-se para a tenda da congregação, eis que a nuvem a cobriu, e a glória do SENHOR apareceu.

[[v4-16-43]]

^<<v4-16-43,43>>^ Vieram, pois, Moisés e Arão perante a tenda da congregação.

[[v4-16-44]]

^<<v4-16-44,44>>^ Então, falou o SENHOR a Moisés, dizendo:

[[v4-16-45]]

^<<v4-16-45,45>>^ Levantai-vos do meio desta congregação, e a consumirei num momento; então, se prostraram sobre o seu rosto.

[[v4-16-46]]

^<<v4-16-46,46>>^ Disse Moisés a Arão: Toma o teu incensário, põe nele fogo do altar, deita incenso sobre ele, vai depressa à congregação e faze expiação por eles; porque grande indignação saiu de diante do SENHOR; já começou a praga.

[[v4-16-47]]

^<<v4-16-47,47>>^ Tomou-o Arão, como Moisés lhe falara, correu ao meio da congregação (eis que já a praga havia começado entre o povo), deitou incenso nele e fez expiação pelo povo.

[[v4-16-48]]

^<<v4-16-48,48>>^ Pôs-se em pé entre os mortos e os vivos; e cessou a praga.

[[v4-16-49]]

^<<v4-16-49,49>>^ Ora, os que morreram daquela praga foram catorze mil e setecentos, fora os que morreram por causa de Corá.

[[v4-16-50]]

^<<v4-16-50,50>>^ Voltou Arão a Moisés, à porta da tenda da congregação; e cessou a praga.

'''

xref:004-numeros/004-numeros-015.adoc#v4-15-0[&#60; Capítulo Anterior] | <<v4-16-0,Topo>> | xref:004-numeros/004-numeros-017.adoc#v4-17-0[Próximo Capítulo &#62;]