include::./index.adoc[]

[[v4-28-0]]
=== Números, 28
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-28-1]]

^<<v4-28-1,1>>^ Disse mais o SENHOR a Moisés:

[[v4-28-2]]

^<<v4-28-2,2>>^ Dá ordem aos filhos de Israel e dize-lhes: Da minha oferta, do meu manjar para as minhas ofertas queimadas, do aroma agradável, tereis cuidado, para mas trazer a seu tempo determinado.

[[v4-28-3]]

^<<v4-28-3,3>>^ Dir-lhes-ás: Esta é a oferta queimada que oferecereis ao SENHOR, dia após dia: dois cordeiros de um ano, sem defeito, em contínuo holocausto;

[[v4-28-4]]

^<<v4-28-4,4>>^ um cordeiro oferecerás pela manhã, e o outro, ao crepúsculo da tarde;

[[v4-28-5]]

^<<v4-28-5,5>>^ e a décima parte de um efa de flor de farinha, em oferta de manjares, amassada com a quarta parte de um him de azeite batido.

[[v4-28-6]]

^<<v4-28-6,6>>^ É holocausto contínuo, instituído no monte Sinai, de aroma agradável, oferta queimada ao SENHOR.

[[v4-28-7]]

^<<v4-28-7,7>>^ A sua libação será a quarta parte de um him para o cordeiro; no santuário, oferecerás a libação de bebida forte ao SENHOR.

[[v4-28-8]]

^<<v4-28-8,8>>^ E o outro cordeiro oferecerás no crepúsculo da tarde; como a oferta de manjares da manhã e como a sua libação, o trarás em oferta queimada de aroma agradável ao SENHOR.

[[v4-28-9]]

^<<v4-28-9,9>>^ No dia de sábado, oferecerás dois cordeiros de um ano, sem defeito, e duas décimas de um efa de flor de farinha, amassada com azeite, em oferta de manjares, e a sua libação;

[[v4-28-10]]

^<<v4-28-10,10>>^ é holocausto de cada sábado, além do holocausto contínuo e a sua libação.

[[v4-28-11]]

^<<v4-28-11,11>>^ Nos princípios dos vossos meses, oferecereis, em holocausto ao SENHOR, dois novilhos e um carneiro, sete cordeiros de um ano, sem defeito,

[[v4-28-12]]

^<<v4-28-12,12>>^ e três décimas de um efa de flor de farinha, amassada com azeite, em oferta de manjares, para um novilho; duas décimas de flor de farinha, amassada com azeite, em oferta de manjares, para um carneiro;

[[v4-28-13]]

^<<v4-28-13,13>>^ e uma décima de um efa de flor de farinha, amassada com azeite, em oferta de manjares, para um cordeiro; é holocausto de aroma agradável, oferta queimada ao SENHOR.

[[v4-28-14]]

^<<v4-28-14,14>>^ As suas libações serão a metade de um him de vinho para um novilho, e a terça parte de um him para um carneiro, e a quarta parte de um him para um cordeiro; este é o holocausto da lua nova de cada mês, por todos os meses do ano.

[[v4-28-15]]

^<<v4-28-15,15>>^ Também se trará um bode como oferta pelo pecado, ao SENHOR, além do holocausto contínuo, com a sua libação.

[[v4-28-16]]

^<<v4-28-16,16>>^ No primeiro mês, aos catorze dias do mês, é a Páscoa do SENHOR.

[[v4-28-17]]

^<<v4-28-17,17>>^ Aos quinze dias do mesmo mês, haverá festa; sete dias se comerão pães asmos.

[[v4-28-18]]

^<<v4-28-18,18>>^ No primeiro dia, haverá santa convocação; nenhuma obra servil fareis;

[[v4-28-19]]

^<<v4-28-19,19>>^ mas apresentareis oferta queimada em holocausto ao SENHOR, dois novilhos, um carneiro e sete cordeiros de um ano; ser-vos-ão eles sem defeito.

[[v4-28-20]]

^<<v4-28-20,20>>^ A sua oferta de manjares será flor de farinha, amassada com azeite; oferecereis três décimas para um novilho e duas décimas para um carneiro.

[[v4-28-21]]

^<<v4-28-21,21>>^ Para cada um dos sete cordeiros oferecereis uma décima;

[[v4-28-22]]

^<<v4-28-22,22>>^ e um bode, para oferta pelo pecado, para fazer expiação por vós.

[[v4-28-23]]

^<<v4-28-23,23>>^ Estas coisas oferecereis, além do holocausto da manhã, que é o holocausto contínuo.

[[v4-28-24]]

^<<v4-28-24,24>>^ Assim, oferecereis cada dia, por sete dias, o manjar da oferta queimada em aroma agradável ao SENHOR; além do holocausto contínuo, se oferecerá isto com a sua libação.

[[v4-28-25]]

^<<v4-28-25,25>>^ No sétimo dia, tereis santa convocação; nenhuma obra servil fareis.

[[v4-28-26]]

^<<v4-28-26,26>>^ Também tereis santa convocação no dia das primícias, quando trouxerdes oferta nova de manjares ao SENHOR, segundo a vossa Festa das Semanas; nenhuma obra servil fareis.

[[v4-28-27]]

^<<v4-28-27,27>>^ Então, oferecereis ao SENHOR por holocausto, em aroma agradável: dois novilhos, um carneiro e sete cordeiros de um ano;

[[v4-28-28]]

^<<v4-28-28,28>>^ a sua oferta de manjares de flor de farinha, amassada com azeite: três décimas de um efa para um novilho, duas décimas para um carneiro,

[[v4-28-29]]

^<<v4-28-29,29>>^ uma décima para cada um dos sete cordeiros;

[[v4-28-30]]

^<<v4-28-30,30>>^ e um bode, para fazer expiação por vós.

[[v4-28-31]]

^<<v4-28-31,31>>^ Oferecê-los-eis, além do holocausto contínuo, e da sua oferta de manjares, e das suas libações. Ser-vos-ão eles sem defeito.

'''

xref:004-numeros/004-numeros-027.adoc#v4-27-0[&#60; Capítulo Anterior] | <<v4-28-0,Topo>> | xref:004-numeros/004-numeros-029.adoc#v4-29-0[Próximo Capítulo &#62;]