include::./index.adoc[]

[[v4-11-0]]
=== Números, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v4-11-1]]

^<<v4-11-1,1>>^ Queixou-se o povo de sua sorte aos ouvidos do SENHOR; ouvindo-o o SENHOR, acendeu-se-lhe a ira, e fogo do SENHOR ardeu entre eles e consumiu extremidades do arraial.

[[v4-11-2]]

^<<v4-11-2,2>>^ Então, o povo clamou a Moisés, e, orando este ao SENHOR, o fogo se apagou.

[[v4-11-3]]

^<<v4-11-3,3>>^ Pelo que chamou aquele lugar Taberá, porque o fogo do SENHOR se acendera entre eles.

[[v4-11-4]]

^<<v4-11-4,4>>^ E o populacho que estava no meio deles veio a ter grande desejo das comidas dos egípcios; pelo que os filhos de Israel tornaram a chorar e também disseram: Quem nos dará carne a comer?

[[v4-11-5]]

^<<v4-11-5,5>>^ Lembramo-nos dos peixes que, no Egito, comíamos de graça; dos pepinos, dos melões, dos alhos silvestres, das cebolas e dos alhos.

[[v4-11-6]]

^<<v4-11-6,6>>^ Agora, porém, seca-se a nossa alma, e nenhuma coisa vemos senão este maná.

[[v4-11-7]]

^<<v4-11-7,7>>^ Era o maná como semente de coentro, e a sua aparência, semelhante à de bdélio.

[[v4-11-8]]

^<<v4-11-8,8>>^ Espalhava-se o povo, e o colhia, e em moinhos o moía ou num gral o pisava, e em panelas o cozia, e dele fazia bolos; o seu sabor era como o de bolos amassados com azeite.

[[v4-11-9]]

^<<v4-11-9,9>>^ Quando, de noite, descia o orvalho sobre o arraial, sobre este também caía o maná.

[[v4-11-10]]

^<<v4-11-10,10>>^ Então, Moisés ouviu chorar o povo por famílias, cada um à porta de sua tenda; e a ira do SENHOR grandemente se acendeu, e pareceu mal aos olhos de Moisés.

[[v4-11-11]]

^<<v4-11-11,11>>^ Disse Moisés ao SENHOR: Por que fizeste mal a teu servo, e por que não achei favor aos teus olhos, visto que puseste sobre mim a carga de todo este povo?

[[v4-11-12]]

^<<v4-11-12,12>>^ Concebi eu, porventura, todo este povo? Dei-o eu à luz, para que me digas: Leva-o ao teu colo, como a ama leva a criança que mama, à terra que, sob juramento, prometeste a seus pais?

[[v4-11-13]]

^<<v4-11-13,13>>^ Donde teria eu carne para dar a todo este povo? Pois chora diante de mim, dizendo: Dá-nos carne que possamos comer.

[[v4-11-14]]

^<<v4-11-14,14>>^ Eu sozinho não posso levar todo este povo, pois me é pesado demais.

[[v4-11-15]]

^<<v4-11-15,15>>^ Se assim me tratas, mata-me de uma vez, eu te peço, se tenho achado favor aos teus olhos; e não me deixes ver a minha miséria.

[[v4-11-16]]

^<<v4-11-16,16>>^ Disse o SENHOR a Moisés: Ajunta-me setenta homens dos anciãos de Israel, que sabes serem anciãos e superintendentes do povo; e os trarás perante a tenda da congregação, para que assistam ali contigo.

[[v4-11-17]]

^<<v4-11-17,17>>^ Então, descerei e ali falarei contigo; tirarei do Espírito que está sobre ti e o porei sobre eles; e contigo levarão a carga do povo, para que não a leves tu somente.

[[v4-11-18]]

^<<v4-11-18,18>>^ Dize ao povo: Santificai-vos para amanhã e comereis carne; porquanto chorastes aos ouvidos do SENHOR, dizendo: Quem nos dará carne a comer? Íamos bem no Egito. Pelo que o SENHOR vos dará carne, e comereis.

[[v4-11-19]]

^<<v4-11-19,19>>^ Não comereis um dia, nem dois dias, nem cinco, nem dez, nem ainda vinte;

[[v4-11-20]]

^<<v4-11-20,20>>^ mas um mês inteiro, até vos sair pelos narizes, até que vos enfastieis dela, porquanto rejeitastes o SENHOR, que está no meio de vós, e chorastes diante dele, dizendo: Por que saímos do Egito?

[[v4-11-21]]

^<<v4-11-21,21>>^ Respondeu Moisés: Seiscentos mil homens de pé é este povo no meio do qual estou; e tu disseste: Dar-lhes-ei carne, e a comerão um mês inteiro.

[[v4-11-22]]

^<<v4-11-22,22>>^ Matar-se-ão para eles rebanhos de ovelhas e de gado que lhes bastem? Ou se ajuntarão para eles todos os peixes do mar que lhes bastem?

[[v4-11-23]]

^<<v4-11-23,23>>^ Porém o SENHOR respondeu a Moisés: Ter-se-ia encurtado a mão do SENHOR? Agora mesmo, verás se se cumprirá ou não a minha palavra!

[[v4-11-24]]

^<<v4-11-24,24>>^ Saiu, pois, Moisés, e referiu ao povo as palavras do SENHOR, e ajuntou setenta homens dos anciãos do povo, e os pôs ao redor da tenda.

[[v4-11-25]]

^<<v4-11-25,25>>^ Então, o SENHOR desceu na nuvem e lhe falou; e, tirando do Espírito que estava sobre ele, o pôs sobre aqueles setenta anciãos; quando o Espírito repousou sobre eles, profetizaram; mas, depois, nunca mais.

[[v4-11-26]]

^<<v4-11-26,26>>^ Porém, no arraial, ficaram dois homens; um se chamava Eldade, e o outro, Medade. Repousou sobre eles o Espírito, porquanto estavam entre os inscritos, ainda que não saíram à tenda; e profetizavam no arraial.

[[v4-11-27]]

^<<v4-11-27,27>>^ Então, correu um moço, e o anunciou a Moisés, e disse: Eldade e Medade profetizam no arraial.

[[v4-11-28]]

^<<v4-11-28,28>>^ Josué, filho de Num, servidor de Moisés, um dos seus escolhidos, respondeu e disse: Moisés, meu senhor, proíbe-lho.

[[v4-11-29]]

^<<v4-11-29,29>>^ Porém Moisés lhe disse: Tens tu ciúmes por mim? Tomara todo o povo do SENHOR fosse profeta, que o SENHOR lhes desse o seu Espírito!

[[v4-11-30]]

^<<v4-11-30,30>>^ Depois, Moisés se recolheu ao arraial, ele e os anciãos de Israel.

[[v4-11-31]]

^<<v4-11-31,31>>^ Então, soprou um vento do SENHOR, e trouxe codornizes do mar, e as espalhou pelo arraial quase caminho de um dia, ao seu redor, cerca de dois côvados sobre a terra.

[[v4-11-32]]

^<<v4-11-32,32>>^ Levantou-se o povo todo aquele dia, e a noite, e o outro dia e recolheu as codornizes; o que menos colheu teve dez ômeres; e as estenderam para si ao redor do arraial.

[[v4-11-33]]

^<<v4-11-33,33>>^ Estava ainda a carne entre os seus dentes, antes que fosse mastigada, quando se acendeu a ira do SENHOR contra o povo, e o feriu com praga mui grande.

[[v4-11-34]]

^<<v4-11-34,34>>^ Pelo que o nome daquele lugar se chamou Quibrote-Hataavá, porquanto ali enterraram o povo que teve o desejo das comidas dos egípcios.

[[v4-11-35]]

^<<v4-11-35,35>>^ De Quibrote-Hataavá partiu o povo para Hazerote e ali ficou.

'''

xref:004-numeros/004-numeros-010.adoc#v4-10-0[&#60; Capítulo Anterior] | <<v4-11-0,Topo>> | xref:004-numeros/004-numeros-012.adoc#v4-12-0[Próximo Capítulo &#62;]