include::./index.adoc[]

[[v11-1-0]]
=== 1 Reis, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v11-1-1]]

^<<v11-1-1,1>>^ Sendo o rei Davi já velho e entrado em dias, envolviam-no com roupas, porém não se aquecia.

[[v11-1-2]]

^<<v11-1-2,2>>^ Então, lhe disseram os seus servos: Procure-se para o rei, nosso senhor, uma jovem donzela, que esteja perante o rei, e tenha cuidado dele, e durma nos seus braços, para que o rei, nosso senhor, se aqueça.

[[v11-1-3]]

^<<v11-1-3,3>>^ Procuraram, pois, por todos os limites de Israel uma jovem formosa; acharam Abisague, sunamita, e a trouxeram ao rei.

[[v11-1-4]]

^<<v11-1-4,4>>^ A jovem era sobremaneira formosa; cuidava do rei e o servia, porém o rei não a possuiu.

[[v11-1-5]]

^<<v11-1-5,5>>^ Então, Adonias, filho de Hagite, se exaltou e disse: Eu reinarei. Providenciou carros, e cavaleiros, e cinquenta homens que corressem adiante dele.

[[v11-1-6]]

^<<v11-1-6,6>>^ Jamais seu pai o contrariou, dizendo: Por que procedes assim? Além disso, era ele de aparência mui formosa e nascera depois de Absalão.

[[v11-1-7]]

^<<v11-1-7,7>>^ Entendia-se ele com Joabe, filho de Zeruia, e com Abiatar, o sacerdote, que, seguindo-o, o ajudavam.

[[v11-1-8]]

^<<v11-1-8,8>>^ Porém Zadoque, o sacerdote, e Benaia, filho de Joiada, e Natã, o profeta, e Simei, e Reí, e os valentes que Davi tinha não apoiavam Adonias.

[[v11-1-9]]

^<<v11-1-9,9>>^ Imolou Adonias ovelhas, e bois, e animais cevados, junto à pedra de Zoelete, que está perto da fonte de Rogel, e convidou todos os seus irmãos, os filhos do rei, e todos os homens de Judá, servos do rei,

[[v11-1-10]]

^<<v11-1-10,10>>^ porém a Natã, profeta, e a Benaia, e os valentes, e a Salomão, seu irmão, não convidou.

[[v11-1-11]]

^<<v11-1-11,11>>^ Então, disse Natã a Bate-Seba, mãe de Salomão: Não ouviste que Adonias, filho de Hagite, reina e que nosso senhor, Davi, não o sabe?

[[v11-1-12]]

^<<v11-1-12,12>>^ Vem, pois, e permite que eu te dê um conselho, para que salves a tua vida e a de Salomão, teu filho.

[[v11-1-13]]

^<<v11-1-13,13>>^ Vai, apresenta-te ao rei Davi e dize-lhe: Não juraste, ó rei, senhor meu, à tua serva, dizendo: Teu filho Salomão reinará depois de mim e se assentará no meu trono? Por que, pois, reina Adonias?

[[v11-1-14]]

^<<v11-1-14,14>>^ Eis que, estando tu ainda a falar com o rei, eu também entrarei depois de ti e confirmarei as tuas palavras.

[[v11-1-15]]

^<<v11-1-15,15>>^ Apresentou-se, pois, Bate-Seba ao rei na recâmara; era já o rei mui velho, e Abisague, a sunamita, o servia.

[[v11-1-16]]

^<<v11-1-16,16>>^ Bate-Seba inclinou a cabeça e prostrou-se perante o rei, que perguntou: Que desejas?

[[v11-1-17]]

^<<v11-1-17,17>>^ Respondeu-lhe ela: Senhor meu, juraste à tua serva pelo SENHOR, teu Deus, dizendo: Salomão, teu filho, reinará depois de mim e ele se assentará no meu trono.

[[v11-1-18]]

^<<v11-1-18,18>>^ Agora, eis que Adonias reina, e tu, ó rei, meu senhor, não o sabes.

[[v11-1-19]]

^<<v11-1-19,19>>^ Imolou bois, e animais cevados, e ovelhas em abundância. Convidou todos os filhos do rei, a Abiatar, o sacerdote, e a Joabe, comandante do exército, mas a teu servo Salomão não convidou.

[[v11-1-20]]

^<<v11-1-20,20>>^ Porém, ó rei, meu senhor, todo o Israel tem os olhos em ti, para que lhe declares quem será o teu sucessor que se assentará no teu trono.

[[v11-1-21]]

^<<v11-1-21,21>>^ Do contrário, sucederá que, quando o rei, meu senhor, jazer com seus pais, eu e Salomão, meu filho, seremos tidos por culpados.

[[v11-1-22]]

^<<v11-1-22,22>>^ Estando ela ainda a falar com o rei, eis que entra o profeta Natã.

[[v11-1-23]]

^<<v11-1-23,23>>^ E o fizeram saber ao rei, dizendo: Aí está o profeta Natã. Apresentou-se ele ao rei, prostrou-se com o rosto em terra perante ele

[[v11-1-24]]

^<<v11-1-24,24>>^ e disse: Ó rei, meu senhor, acaso disseste: Adonias reinará depois de mim e ele é quem se assentará no meu trono?

[[v11-1-25]]

^<<v11-1-25,25>>^ Porque, hoje, desceu, imolou bois, e animais cevados, e ovelhas em abundância e convidou todos os filhos do rei, e os chefes do exército, e a Abiatar, o sacerdote, e eis que estão comendo e bebendo perante ele; e dizem: Viva o rei Adonias!

[[v11-1-26]]

^<<v11-1-26,26>>^ Porém a mim, sendo eu teu servo, e a Zadoque, o sacerdote, e a Benaia, filho de Joiada, e a Salomão, teu servo, não convidou.

[[v11-1-27]]

^<<v11-1-27,27>>^ Foi isto feito da parte do rei, meu senhor? E não fizeste saber a teu servo quem se assentaria no teu trono, depois de ti?

[[v11-1-28]]

^<<v11-1-28,28>>^ Respondeu o rei Davi e disse: Chamai-me a Bate-Seba. Ela se apresentou ao rei e se pôs diante dele.

[[v11-1-29]]

^<<v11-1-29,29>>^ Então, jurou o rei e disse: Tão certo como vive o SENHOR, que remiu a minha alma de toda a angústia,

[[v11-1-30]]

^<<v11-1-30,30>>^ farei no dia de hoje, como te jurei pelo SENHOR, Deus de Israel, dizendo: Teu filho Salomão reinará depois de mim e se assentará no meu trono, em meu lugar.

[[v11-1-31]]

^<<v11-1-31,31>>^ Então, Bate-Seba se inclinou, e se prostrou com o rosto em terra diante do rei, e disse: Viva o rei Davi, meu senhor, para sempre!

[[v11-1-32]]

^<<v11-1-32,32>>^ Disse o rei Davi: Chamai-me Zadoque, o sacerdote, e Natã, o profeta, e Benaia, filho de Joiada. E eles se apresentaram ao rei.

[[v11-1-33]]

^<<v11-1-33,33>>^ Disse-lhes o rei: Tomai convosco os servos de vosso senhor, e fazei montar meu filho Salomão na minha mula, e levai-o a Giom.

[[v11-1-34]]

^<<v11-1-34,34>>^ Zadoque, o sacerdote, com Natã, o profeta, ali o ungirão rei sobre Israel; então, tocareis a trombeta e direis: Viva o rei Salomão!

[[v11-1-35]]

^<<v11-1-35,35>>^ Subireis após ele, e virá e se assentará no meu trono, pois é ele quem reinará em meu lugar; porque ordenei seja ele príncipe sobre Israel e sobre Judá.

[[v11-1-36]]

^<<v11-1-36,36>>^ Então, Benaia, filho de Joiada, respondeu ao rei e disse: Amém! Assim o diga o SENHOR, Deus do rei, meu senhor.

[[v11-1-37]]

^<<v11-1-37,37>>^ Como o SENHOR foi com o rei, meu senhor, assim seja com Salomão e faça que o trono deste seja maior do que o trono do rei Davi, meu senhor.

[[v11-1-38]]

^<<v11-1-38,38>>^ Então, desceu Zadoque, o sacerdote, e Natã, o profeta, e Benaia, filho de Joiada, e a guarda real, fizeram montar Salomão a mula que era do rei Davi e o levaram a Giom.

[[v11-1-39]]

^<<v11-1-39,39>>^ Zadoque, o sacerdote, tomou do tabernáculo o chifre do azeite e ungiu a Salomão; tocaram a trombeta, e todo o povo exclamou: Viva o rei Salomão!

[[v11-1-40]]

^<<v11-1-40,40>>^ Após ele, subiu todo o povo, tocando gaitas e alegrando-se com grande alegria, de maneira que, com o seu clamor, parecia fender-se a terra.

[[v11-1-41]]

^<<v11-1-41,41>>^ Adonias e todos os convidados que com ele estavam o ouviram, quando acabavam de comer; também Joabe ouviu o sonido das trombetas e disse: Que significa esse ruído de cidade alvoroçada?

[[v11-1-42]]

^<<v11-1-42,42>>^ Estando ele ainda a falar, eis que vem Jônatas, filho de Abiatar, o sacerdote; disse Adonias: Entra, porque és homem valente e trazes boas-novas.

[[v11-1-43]]

^<<v11-1-43,43>>^ Respondeu Jônatas e disse a Adonias: Pelo contrário, nosso senhor, o rei Davi, constituiu rei a Salomão.

[[v11-1-44]]

^<<v11-1-44,44>>^ E Davi enviou com ele a Zadoque, o sacerdote, e a Natã, o profeta, e a Benaia, filho de Joiada, e aos da guarda real; e o fizeram montar a mula que era do rei.

[[v11-1-45]]

^<<v11-1-45,45>>^ Zadoque, o sacerdote, e Natã, o profeta, o ungiram rei em Giom e dali subiram alegres, e a cidade se alvoroçou; esse é o clamor que ouviste.

[[v11-1-46]]

^<<v11-1-46,46>>^ Também Salomão já está assentado no trono do reino.

[[v11-1-47]]

^<<v11-1-47,47>>^ Ademais, os oficiais do rei Davi vieram congratular-se com ele e disseram: Faça teu Deus que o nome de Salomão seja mais célebre do que o teu nome; e faça que o seu trono seja maior do que o teu trono. E o rei se inclinou sobre o leito.

[[v11-1-48]]

^<<v11-1-48,48>>^ Também disse o rei assim: Bendito o SENHOR, Deus de Israel, que deu, hoje, quem se assente no meu trono, vendo-o os meus próprios olhos.

[[v11-1-49]]

^<<v11-1-49,49>>^ Então, estremeceram e se levantaram todos os convidados que estavam com Adonias, e todos se foram, tomando cada um seu caminho.

[[v11-1-50]]

^<<v11-1-50,50>>^ Porém Adonias, temendo a Salomão, levantou-se, foi e pegou nas pontas do altar.

[[v11-1-51]]

^<<v11-1-51,51>>^ Foi dito a Salomão: Eis que Adonias tem medo de ti, porque pega nas pontas do altar, dizendo: Jure-me, hoje, o rei Salomão que não matará a seu servo à espada.

[[v11-1-52]]

^<<v11-1-52,52>>^ Respondeu Salomão: Se for homem de bem, nem um de seus cabelos cairá em terra; porém, se se achar nele maldade, morrerá.

[[v11-1-53]]

^<<v11-1-53,53>>^ Enviou o rei Salomão mensageiros, e o fizeram descer do altar; então, veio ele e se prostrou perante o rei Salomão, e este lhe disse: Vai para tua casa.

'''

xref:010-2-samuel/010-2-samuel-024.adoc#v10-24-0[&#60; Capítulo Anterior] | <<v11-1-0,Topo>> | xref:011-1-reis/011-1-reis-002.adoc#v11-2-0[Próximo Capítulo &#62;]