include::./index.adoc[]

[[v11-7-0]]
=== 1 Reis, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v11-7-1]]

^<<v11-7-1,1>>^ Edificou Salomão os seus palácios, levando treze anos para os concluir.

[[v11-7-2]]

^<<v11-7-2,2>>^ Edificou a Casa do Bosque do Líbano, de cem côvados de comprimento, cinquenta de largura e trinta de altura, sobre quatro ordens de colunas de cedro e vigas de cedro sobre as colunas.

[[v11-7-3]]

^<<v11-7-3,3>>^ A cobertura era de cedro, abrangendo as câmaras laterais em número de quarenta e cinco, quinze em cada andar, as quais repousavam sobre colunas.

[[v11-7-4]]

^<<v11-7-4,4>>^ Havia janelas em três ordens e janela oposta a janela em três fileiras.

[[v11-7-5]]

^<<v11-7-5,5>>^ Todas as portas e janelas eram quadradas; e janela oposta a janela em três fileiras.

[[v11-7-6]]

^<<v11-7-6,6>>^ Depois, fez o Salão das Colunas, de cinquenta côvados de comprimento e trinta de largura; e havia um pórtico de colunas defronte dele, um baldaquino.

[[v11-7-7]]

^<<v11-7-7,7>>^ Também fez a Sala do Trono, onde julgava, a saber, a Sala do Julgamento, coberta de cedro desde o soalho até ao teto.

[[v11-7-8]]

^<<v11-7-8,8>>^ A sua casa, em que moraria, fê-la noutro pátio atrás da Sala do Trono, de obra semelhante a esta; também para a filha de Faraó, que tomara por mulher, fez Salomão uma casa semelhante à Sala do Trono.

[[v11-7-9]]

^<<v11-7-9,9>>^ Todas estas construções eram de pedras de valor, cortadas à medida, serradas para o lado de dentro e para o de fora; e isto desde o fundamento até às beiras do teto, e por fora até ao átrio maior.

[[v11-7-10]]

^<<v11-7-10,10>>^ O fundamento era de pedras de valor, pedras grandes; pedras de dez côvados e pedras de oito côvados;

[[v11-7-11]]

^<<v11-7-11,11>>^ por cima delas, pedras de valor, cortadas segundo as medidas, e cedros.

[[v11-7-12]]

^<<v11-7-12,12>>^ Ao redor do grande átrio, havia três ordens de pedras cortadas e uma ordem de vigas de cedro; assim era também o átrio interior da Casa do SENHOR e o pórtico daquela casa.

[[v11-7-13]]

^<<v11-7-13,13>>^ Enviou o rei Salomão mensageiros que de Tiro trouxessem Hirão.

[[v11-7-14]]

^<<v11-7-14,14>>^ Era este filho de uma mulher viúva, da tribo de Naftali, e fora seu pai um homem de Tiro que trabalhava em bronze; Hirão era cheio de sabedoria, e de entendimento, e de ciência para fazer toda obra de bronze. Veio ter com o rei Salomão e fez toda a sua obra.

[[v11-7-15]]

^<<v11-7-15,15>>^ Formou duas colunas de bronze; a altura de cada uma era de dezoito côvados, e um fio de doze côvados era a medida de sua circunferência.

[[v11-7-16]]

^<<v11-7-16,16>>^ Também fez dois capitéis de fundição de bronze para pôr sobre o alto das colunas; de cinco côvados era a altura de cada um deles.

[[v11-7-17]]

^<<v11-7-17,17>>^ Havia obra de rede e ornamentos torcidos em forma de cadeia, para os capitéis que estavam sobre o alto das colunas; sete para um capitel e sete para o outro.

[[v11-7-18]]

^<<v11-7-18,18>>^ Fez também romãs em duas fileiras por cima de uma das obras de rede, para cobrir o capitel no alto da coluna; o mesmo fez com o outro capitel.

[[v11-7-19]]

^<<v11-7-19,19>>^ Os capitéis que estavam no alto das colunas eram de obra de lírios, como na Sala do Trono, e de quatro côvados.

[[v11-7-20]]

^<<v11-7-20,20>>^ Perto do bojo, próximo à obra de rede, os capitéis que estavam no alto das duas colunas tinham duzentas romãs, dispostas em fileiras em redor, sobre um e outro capitel.

[[v11-7-21]]

^<<v11-7-21,21>>^ Depois, levantou as colunas no pórtico do templo; tendo levantado a coluna direita, chamou-lhe Jaquim; e, tendo levantado a coluna esquerda, chamou-lhe Boaz.

[[v11-7-22]]

^<<v11-7-22,22>>^ No alto das colunas, estava a obra de lírios. E, assim, se acabou a obra das colunas.

[[v11-7-23]]

^<<v11-7-23,23>>^ Fez também o mar de fundição, redondo, de dez côvados de uma borda até à outra borda, e de cinco de altura; e um fio de trinta côvados era a medida de sua circunferência.

[[v11-7-24]]

^<<v11-7-24,24>>^ Por baixo da sua borda em redor, havia colocíntidas, dez em cada côvado; estavam em duas fileiras, fundidas quando se fundiu o mar.

[[v11-7-25]]

^<<v11-7-25,25>>^ Assentava-se o mar sobre doze bois; três olhavam para o norte, três, para o ocidente, três, para o sul, e três, para o oriente; o mar apoiava-se sobre eles, cujas partes posteriores convergiam para dentro.

[[v11-7-26]]

^<<v11-7-26,26>>^ A grossura dele era de quatro dedos, e a sua borda, como borda de copo, como flor de lírios; comportava dois mil batos.

[[v11-7-27]]

^<<v11-7-27,27>>^ Fez também de bronze dez suportes; cada um media quatro côvados de comprimento, quatro de largura e três de altura;

[[v11-7-28]]

^<<v11-7-28,28>>^ e eram do seguinte modo: tinham painéis, que estavam entre molduras,

[[v11-7-29]]

^<<v11-7-29,29>>^ nos quais havia leões, bois e querubins; nas molduras de cima e de baixo dos leões e dos bois, havia festões pendentes.

[[v11-7-30]]

^<<v11-7-30,30>>^ Tinha cada suporte quatro rodas de bronze e eixos de bronze; os seus quatro pés tinham apoios debaixo da pia, apoios fundidos, e ao lado de cada um havia festões.

[[v11-7-31]]

^<<v11-7-31,31>>^ A boca dos suportes estava dentro de uma guarnição que media um côvado de altura; a boca era redonda como a obra de um pedestal e tinha o diâmetro de um côvado e meio. Também nela havia entalhes, e os seus painéis eram quadrados, não redondos.

[[v11-7-32]]

^<<v11-7-32,32>>^ As quatro rodas estavam debaixo dos painéis, e os eixos das rodas formavam uma peça com o suporte; cada roda era de um côvado e meio de altura.

[[v11-7-33]]

^<<v11-7-33,33>>^ As rodas eram como as de um carro: seus eixos, suas cambas, seus raios e seus cubos, todos eram fundidos.

[[v11-7-34]]

^<<v11-7-34,34>>^ Havia quatro apoios aos quatro cantos de cada suporte, que com este formavam uma peça.

[[v11-7-35]]

^<<v11-7-35,35>>^ No alto de cada suporte, havia um cilindro de meio côvado de altura; também, no alto de cada suporte, os apoios e painéis formavam uma peça só com ele.

[[v11-7-36]]

^<<v11-7-36,36>>^ Na superfície dos seus apoios e dos seus painéis, gravou querubins, leões e palmeiras, segundo o espaço de cada um, com festões ao redor.

[[v11-7-37]]

^<<v11-7-37,37>>^ Deste modo, fez os dez suportes; todos tinham a mesma fundição, o mesmo tamanho e o mesmo entalhe.

[[v11-7-38]]

^<<v11-7-38,38>>^ Também fez dez pias de bronze; em cada uma cabiam quarenta batos, e cada uma era de quatro côvados; sobre cada um dos dez suportes estava uma pia.

[[v11-7-39]]

^<<v11-7-39,39>>^ Pôs cinco suportes à direita da casa e cinco, à esquerda; porém o mar pôs ao lado direito da casa, para o lado sudeste.

[[v11-7-40]]

^<<v11-7-40,40>>^ Depois, fez Hirão os caldeirões, e as pás, e as bacias. Assim, terminou ele de fazer toda a obra para o rei Salomão, para a Casa do SENHOR:

[[v11-7-41]]

^<<v11-7-41,41>>^ as duas colunas, os dois globos dos capitéis que estavam no alto das duas colunas; as duas redes, para cobrir os dois globos dos capitéis que estavam ao alto das colunas;

[[v11-7-42]]

^<<v11-7-42,42>>^ as quatrocentas romãs para as duas redes, isto é, duas fileiras de romãs para cada rede, para cobrirem os dois globos dos capitéis que estavam no alto das colunas;

[[v11-7-43]]

^<<v11-7-43,43>>^ os dez suportes e as dez pias sobre eles;

[[v11-7-44]]

^<<v11-7-44,44>>^ o mar com os doze bois por baixo;

[[v11-7-45]]

^<<v11-7-45,45>>^ os caldeirões, as pás, as bacias e todos estes utensílios que fez Hirão para o rei Salomão, para a Casa do SENHOR, todos eram de bronze polido.

[[v11-7-46]]

^<<v11-7-46,46>>^ Na planície do Jordão, o rei os fez fundir em terra barrenta, entre Sucote e Zaretã.

[[v11-7-47]]

^<<v11-7-47,47>>^ Deixou Salomão de pesar todos os utensílios pelo seu excessivo número, não se verificando, pois, o peso do seu bronze.

[[v11-7-48]]

^<<v11-7-48,48>>^ Também fez Salomão todos os utensílios do Santo Lugar do SENHOR: o altar de ouro e a mesa de ouro, sobre a qual estavam os pães da proposição;

[[v11-7-49]]

^<<v11-7-49,49>>^ os castiçais de ouro finíssimo, cinco à direita e cinco à esquerda, diante do Santo dos Santos; as flores, as lâmpadas e as espevitadeiras, também de ouro;

[[v11-7-50]]

^<<v11-7-50,50>>^ também as taças, as espevitadeiras, as bacias, os recipientes para incenso e os braseiros, de ouro finíssimo; as dobradiças para as portas da casa interior para o Santo dos Santos e as das portas do Santo Lugar do templo, também de ouro.

[[v11-7-51]]

^<<v11-7-51,51>>^ Assim, se acabou toda a obra que fez o rei Salomão para a Casa do SENHOR; então, trouxe Salomão as coisas que Davi, seu pai, havia dedicado; a prata, o ouro e os utensílios, ele os pôs entre os tesouros da Casa do SENHOR.

'''

xref:011-1-reis/011-1-reis-006.adoc#v11-6-0[&#60; Capítulo Anterior] | <<v11-7-0,Topo>> | xref:011-1-reis/011-1-reis-008.adoc#v11-8-0[Próximo Capítulo &#62;]