include::./index.adoc[]

[[v11-3-0]]
=== 1 Reis, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v11-3-1]]

^<<v11-3-1,1>>^ Salomão aparentou-se com Faraó, rei do Egito, pois tomou por mulher a filha de Faraó e a trouxe à Cidade de Davi, até que acabasse de edificar a sua casa, e a Casa do SENHOR, e a muralha à roda de Jerusalém.

[[v11-3-2]]

^<<v11-3-2,2>>^ Entretanto, o povo oferecia sacrifícios sobre os altos, porque até àqueles dias ainda não se tinha edificado casa ao nome do SENHOR.

[[v11-3-3]]

^<<v11-3-3,3>>^ Salomão amava ao SENHOR, andando nos preceitos de Davi, seu pai; porém sacrificava ainda nos altos e queimava incenso.

[[v11-3-4]]

^<<v11-3-4,4>>^ Foi o rei a Gibeão para lá sacrificar, porque era o alto maior; ofereceu mil holocaustos Salomão naquele altar.

[[v11-3-5]]

^<<v11-3-5,5>>^ Em Gibeão, apareceu o SENHOR a Salomão, de noite, em sonhos. Disse-lhe Deus: Pede-me o que queres que eu te dê.

[[v11-3-6]]

^<<v11-3-6,6>>^ Respondeu Salomão: De grande benevolência usaste para com teu servo Davi, meu pai, porque ele andou contigo em fidelidade, e em justiça, e em retidão de coração, perante a tua face; mantiveste-lhe esta grande benevolência e lhe deste um filho que se assentasse no seu trono, como hoje se vê.

[[v11-3-7]]

^<<v11-3-7,7>>^ Agora, pois, ó SENHOR, meu Deus, tu fizeste reinar teu servo em lugar de Davi, meu pai; não passo de uma criança, não sei como conduzir-me.

[[v11-3-8]]

^<<v11-3-8,8>>^ Teu servo está no meio do teu povo que elegeste, povo grande, tão numeroso, que se não pode contar.

[[v11-3-9]]

^<<v11-3-9,9>>^ Dá, pois, ao teu servo coração compreensivo para julgar a teu povo, para que prudentemente discirna entre o bem e o mal; pois quem poderia julgar a este grande povo?

[[v11-3-10]]

^<<v11-3-10,10>>^ Estas palavras agradaram ao Senhor, por haver Salomão pedido tal coisa.

[[v11-3-11]]

^<<v11-3-11,11>>^ Disse-lhe Deus: Já que pediste esta coisa e não pediste longevidade, nem riquezas, nem a morte de teus inimigos; mas pediste entendimento, para discernires o que é justo;

[[v11-3-12]]

^<<v11-3-12,12>>^ eis que faço segundo as tuas palavras: dou-te coração sábio e inteligente, de maneira que antes de ti não houve teu igual, nem depois de ti o haverá.

[[v11-3-13]]

^<<v11-3-13,13>>^ Também até o que me não pediste eu te dou, tanto riquezas como glória; que não haja teu igual entre os reis, por todos os teus dias.

[[v11-3-14]]

^<<v11-3-14,14>>^ Se andares nos meus caminhos e guardares os meus estatutos e os meus mandamentos, como andou Davi, teu pai, prolongarei os teus dias.

[[v11-3-15]]

^<<v11-3-15,15>>^ Despertou Salomão; e eis que era sonho. Veio a Jerusalém, pôs-se perante a arca da Aliança do SENHOR, ofereceu holocaustos, apresentou ofertas pacíficas e deu um banquete a todos os seus oficiais.

[[v11-3-16]]

^<<v11-3-16,16>>^ Então, vieram duas prostitutas ao rei e se puseram perante ele.

[[v11-3-17]]

^<<v11-3-17,17>>^ Disse-lhe uma das mulheres: Ah! Senhor meu, eu e esta mulher moramos na mesma casa, onde dei à luz um filho.

[[v11-3-18]]

^<<v11-3-18,18>>^ No terceiro dia, depois do meu parto, também esta mulher teve um filho. Estávamos juntas; nenhuma outra pessoa se achava conosco na casa; somente nós ambas estávamos ali.

[[v11-3-19]]

^<<v11-3-19,19>>^ De noite, morreu o filho desta mulher, porquanto se deitara sobre ele.

[[v11-3-20]]

^<<v11-3-20,20>>^ Levantou-se à meia-noite, e, enquanto dormia a tua serva, tirou-me a meu filho do meu lado, e o deitou nos seus braços; e a seu filho morto deitou-o nos meus.

[[v11-3-21]]

^<<v11-3-21,21>>^ Levantando-me de madrugada para dar de mamar a meu filho, eis que estava morto; mas, reparando nele pela manhã, eis que não era o filho que eu dera à luz.

[[v11-3-22]]

^<<v11-3-22,22>>^ Então, disse a outra mulher: Não, mas o vivo é meu filho; o teu é o morto. Porém esta disse: Não, o morto é teu filho; o meu é o vivo. Assim falaram perante o rei.

[[v11-3-23]]

^<<v11-3-23,23>>^ Então, disse o rei: Esta diz: Este que vive é meu filho, e teu filho é o morto; e esta outra diz: Não, o morto é teu filho, e o meu filho é o vivo.

[[v11-3-24]]

^<<v11-3-24,24>>^ Disse mais o rei: Trazei-me uma espada. Trouxeram uma espada diante do rei.

[[v11-3-25]]

^<<v11-3-25,25>>^ Disse o rei: Dividi em duas partes o menino vivo e dai metade a uma e metade a outra.

[[v11-3-26]]

^<<v11-3-26,26>>^ Então, a mulher cujo filho era o vivo falou ao rei (porque o amor materno se aguçou por seu filho) e disse: Ah! Senhor meu, dai-lhe o menino vivo e por modo nenhum o mateis. Porém a outra dizia: Nem meu nem teu; seja dividido.

[[v11-3-27]]

^<<v11-3-27,27>>^ Então, respondeu o rei: Dai à primeira o menino vivo; não o mateis, porque esta é sua mãe.

[[v11-3-28]]

^<<v11-3-28,28>>^ Todo o Israel ouviu a sentença que o rei havia proferido; e todos tiveram profundo respeito ao rei, porque viram que havia nele a sabedoria de Deus, para fazer justiça.

'''

xref:011-1-reis/011-1-reis-002.adoc#v11-2-0[&#60; Capítulo Anterior] | <<v11-3-0,Topo>> | xref:011-1-reis/011-1-reis-004.adoc#v11-4-0[Próximo Capítulo &#62;]