include::./index.adoc[]

[[v11-20-0]]
=== 1 Reis, 20
// ara ?, ARA - Almeida Revista e Atualizada

[[v11-20-1]]

^<<v11-20-1,1>>^ Ben-Hadade, rei da Síria, ajuntou todo o seu exército; havia com ele trinta e dois reis, e cavalos, e carros. Subiu, cercou a Samaria e pelejou contra ela.

[[v11-20-2]]

^<<v11-20-2,2>>^ Enviou mensageiros à cidade, a Acabe, rei de Israel,

[[v11-20-3]]

^<<v11-20-3,3>>^ que lhe disseram: Assim diz Ben-Hadade: A tua prata e o teu ouro são meus; tuas mulheres e os melhores de teus filhos são meus.

[[v11-20-4]]

^<<v11-20-4,4>>^ Respondeu o rei de Israel e disse: Seja conforme a tua palavra, ó rei, meu senhor; eu sou teu, e tudo o que tenho.

[[v11-20-5]]

^<<v11-20-5,5>>^ Tornaram a vir os mensageiros e disseram: Assim diz Ben-Hadade: Enviei-te, na verdade, mensageiros que dissessem: Tens de entregar-me a tua prata, o teu ouro, as tuas mulheres e os teus filhos.

[[v11-20-6]]

^<<v11-20-6,6>>^ Todavia, amanhã a estas horas enviar-te-ei os meus servos, que esquadrinharão a tua casa e as casas dos teus oficiais, meterão as mãos em tudo o que for aprazível aos teus olhos e o levarão.

[[v11-20-7]]

^<<v11-20-7,7>>^ Então, o rei de Israel chamou todos os anciãos da sua terra e lhes disse: Notai e vede como este homem procura o mal; pois me mandou exigir minhas mulheres, meus filhos, minha prata e meu ouro, e não lho neguei.

[[v11-20-8]]

^<<v11-20-8,8>>^ Todos os anciãos e todo o povo lhe disseram: Não lhe dês ouvidos, nem o consintas.

[[v11-20-9]]

^<<v11-20-9,9>>^ Pelo que disse aos mensageiros de Ben-Hadade: Dizei ao rei, meu senhor: Tudo o que primeiro demandaste do teu servo farei, porém isto, agora, não posso consentir. E se foram os mensageiros e deram esta resposta.

[[v11-20-10]]

^<<v11-20-10,10>>^ Ben-Hadade tornou a enviar mensageiros, dizendo: Façam-me os deuses como lhes aprouver, se o pó de Samaria bastar para encher as mãos de todo o povo que me segue.

[[v11-20-11]]

^<<v11-20-11,11>>^ Porém o rei de Israel respondeu e disse: Dizei-lhe: Não se gabe quem se cinge como aquele que vitorioso se descinge.

[[v11-20-12]]

^<<v11-20-12,12>>^ Tendo Ben-Hadade ouvido esta resposta, quando bebiam ele e os reis nas tendas, disse aos seus servos: Ponde-vos de prontidão. E eles se puseram de prontidão contra a cidade.

[[v11-20-13]]

^<<v11-20-13,13>>^ Eis que um profeta se chegou a Acabe, rei de Israel, e lhe disse: Assim diz o SENHOR: Viste toda esta grande multidão? Pois, hoje, a entregarei nas tuas mãos, e saberás que eu sou o SENHOR.

[[v11-20-14]]

^<<v11-20-14,14>>^ Perguntou Acabe: Por quem? Ele respondeu: Assim diz o SENHOR: Pelos moços dos chefes das províncias. E disse: Quem começará a peleja? Tu! — respondeu ele.

[[v11-20-15]]

^<<v11-20-15,15>>^ Então, contou os moços dos chefes das províncias, e eram duzentos e trinta e dois; depois, contou todo o povo, todos os filhos de Israel, sete mil.

[[v11-20-16]]

^<<v11-20-16,16>>^ Saíram ao meio-dia. Ben-Hadade, porém, estava bebendo e embriagando-se nas tendas, ele e os reis, os trinta e dois reis que o ajudavam.

[[v11-20-17]]

^<<v11-20-17,17>>^ Saíram primeiro os moços dos chefes das províncias; Ben-Hadade mandou observadores que lhe deram avisos, dizendo: Saíram de Samaria uns homens.

[[v11-20-18]]

^<<v11-20-18,18>>^ Ele disse: Quer venham tratar de paz, tomai-os vivos; quer venham pelejar, tomai-os vivos.

[[v11-20-19]]

^<<v11-20-19,19>>^ Saíram, pois, da cidade os moços dos chefes das províncias e o exército que os seguia.

[[v11-20-20]]

^<<v11-20-20,20>>^ Eles feriram, cada um ao homem que se lhe opunha; os siros fugiram, e Israel os perseguiu; porém Ben-Hadade, rei da Síria, escapou a cavalo, com alguns cavaleiros.

[[v11-20-21]]

^<<v11-20-21,21>>^ Saiu o rei de Israel e destroçou os cavalos e os carros; e feriu os siros com grande estrago.

[[v11-20-22]]

^<<v11-20-22,22>>^ Então, o profeta se chegou ao rei de Israel e lhe disse: Vai, sê forte, considera e vê o que hás de fazer; porque daqui a um ano subirá o rei da Síria contra ti.

[[v11-20-23]]

^<<v11-20-23,23>>^ Os servos do rei da Síria lhe disseram: Seus deuses são deuses dos montes; por isso, foram mais fortes do que nós; mas pelejemos contra eles em planície, e, por certo, seremos mais fortes do que eles.

[[v11-20-24]]

^<<v11-20-24,24>>^ Faze, pois, isto: tira os reis, cada um do seu lugar, e substitui-os por capitães,

[[v11-20-25]]

^<<v11-20-25,25>>^ e forma outro exército igual em número ao que perdeste, com outros tantos cavalos e outros tantos carros, e pelejemos contra eles em planície e, por certo, seremos mais fortes do que eles. Ele deu ouvidos ao que disseram e assim o fez.

[[v11-20-26]]

^<<v11-20-26,26>>^ Decorrido um ano, Ben-Hadade passou revista aos siros e subiu a Afeca para pelejar contra Israel.

[[v11-20-27]]

^<<v11-20-27,27>>^ Também aos filhos de Israel se passou revista, foram providos de víveres e marcharam contra eles. Os filhos de Israel acamparam-se defronte deles, como dois pequenos rebanhos de cabras; mas os siros enchiam a terra.

[[v11-20-28]]

^<<v11-20-28,28>>^ Chegou um homem de Deus, e falou ao rei de Israel, e disse: Assim diz o SENHOR: Porquanto os siros disseram: O SENHOR é deus dos montes e não dos vales, toda esta grande multidão entregarei nas tuas mãos, e assim sabereis que eu sou o SENHOR.

[[v11-20-29]]

^<<v11-20-29,29>>^ Sete dias estiveram acampados uns defronte dos outros. Ao sétimo dia, travou-se a batalha, e os filhos de Israel, num só dia, feriram dos siros cem mil homens de pé.

[[v11-20-30]]

^<<v11-20-30,30>>^ Os restantes fugiram para Afeca e entraram na cidade; e caiu o muro sobre os vinte e sete mil homens que restaram. Ben-Hadade fugiu, veio à cidade e se escondia de câmara em câmara.

[[v11-20-31]]

^<<v11-20-31,31>>^ Então, lhe disseram os seus servos: Eis que temos ouvido que os reis da casa de Israel são reis clementes; ponhamos, pois, panos de saco sobre os lombos e cordas à roda da cabeça e saiamos ao rei de Israel; pode ser que ele te poupe a vida.

[[v11-20-32]]

^<<v11-20-32,32>>^ Então, se cingiram com pano de saco pelos lombos, puseram cordas à roda da cabeça, vieram ao rei de Israel e disseram: Diz o teu servo Ben-Hadade: Poupa-me a vida. Disse Acabe: Pois ainda vive? É meu irmão.

[[v11-20-33]]

^<<v11-20-33,33>>^ Aqueles homens tomaram isto por presságio, valeram-se logo dessa palavra; e disseram: Teu irmão Ben-Hadade! Ele disse: Vinde, trazei-mo. Então, Ben-Hadade saiu a ter com ele, e ele o fez subir ao carro.

[[v11-20-34]]

^<<v11-20-34,34>>^ Ben-Hadade disse-lhe: As cidades que meu pai tomou a teu pai, eu tas restituirei; monta os teus bazares em Damasco, como meu pai o fez em Samaria. E eu, disse Acabe, com esta aliança, te deixarei livre. Fez com ele aliança e o despediu.

[[v11-20-35]]

^<<v11-20-35,35>>^ Então, um dos discípulos dos profetas disse ao seu companheiro por ordem do SENHOR: Esmurra-me; mas o homem recusou fazê-lo.

[[v11-20-36]]

^<<v11-20-36,36>>^ Ele lhe disse: Visto que não obedeceste à voz do SENHOR, eis que, em te apartando de mim, um leão te matará. Tendo ele se apartado, um leão o encontrou e o matou.

[[v11-20-37]]

^<<v11-20-37,37>>^ Encontrando o profeta outro homem, lhe disse: Esmurra-me. Ele o esmurrou e o feriu.

[[v11-20-38]]

^<<v11-20-38,38>>^ Então, se foi o profeta e se pôs no caminho do rei, disfarçado com uma venda sobre os olhos.

[[v11-20-39]]

^<<v11-20-39,39>>^ Ao passar o rei, gritou e disse: Teu servo estava no meio da peleja, quando, voltando-se-me um companheiro, me trouxe um homem e me disse: Vigia este homem; se vier a faltar, a tua vida responderá pela vida dele ou pagarás um talento de prata.

[[v11-20-40]]

^<<v11-20-40,40>>^ Estando o teu servo ocupado daqui e dali, ele se foi. Respondeu-lhe o rei de Israel: Esta é a tua sentença; tu mesmo a pronunciaste.

[[v11-20-41]]

^<<v11-20-41,41>>^ Então, ele se apressou e tirou a venda de sobre os seus olhos; e o rei de Israel reconheceu que era um dos profetas.

[[v11-20-42]]

^<<v11-20-42,42>>^ E disse-lhe: Assim diz o SENHOR: Porquanto soltaste da mão o homem que eu havia condenado, a tua vida será em lugar da sua vida, e o teu povo, em lugar do seu povo.

[[v11-20-43]]

^<<v11-20-43,43>>^ Foi-se o rei de Israel para sua casa, desgostoso e indignado, e chegou a Samaria.

'''

xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[&#60; Capítulo Anterior] | <<v11-20-0,Topo>> | xref:011-1-reis/011-1-reis-021.adoc#v11-21-0[Próximo Capítulo &#62;]