include::./index.adoc[]

[[v11-9-0]]
=== 1 Reis, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v11-9-1]]

^<<v11-9-1,1>>^ Sucedeu, pois, que, tendo acabado Salomão de edificar a Casa do SENHOR, e a casa do rei, e tudo o que tinha desejado e designara fazer,

[[v11-9-2]]

^<<v11-9-2,2>>^ o SENHOR tornou a aparecer-lhe, como lhe tinha aparecido em Gibeão,

[[v11-9-3]]

^<<v11-9-3,3>>^ e o SENHOR lhe disse: Ouvi a tua oração e a tua súplica que fizeste perante mim; santifiquei a casa que edificaste, a fim de pôr ali o meu nome para sempre; os meus olhos e o meu coração estarão ali todos os dias.

[[v11-9-4]]

^<<v11-9-4,4>>^ Se andares perante mim como andou Davi, teu pai, com integridade de coração e com sinceridade, para fazeres segundo tudo o que te mandei e guardares os meus estatutos e os meus juízos,

[[v11-9-5]]

^<<v11-9-5,5>>^ então, confirmarei o trono de teu reino sobre Israel para sempre, como falei acerca de Davi, teu pai, dizendo: Não te faltará sucessor sobre o trono de Israel.

[[v11-9-6]]

^<<v11-9-6,6>>^ Porém, se vós e vossos filhos, de qualquer maneira, vos apartardes de mim e não guardardes os meus mandamentos e os meus estatutos, que vos prescrevi, mas fordes, e servirdes a outros deuses, e os adorardes,

[[v11-9-7]]

^<<v11-9-7,7>>^ então, eliminarei Israel da terra que lhe dei, e a esta casa, que santifiquei a meu nome, lançarei longe da minha presença; e Israel virá a ser provérbio e motejo entre todos os povos.

[[v11-9-8]]

^<<v11-9-8,8>>^ E desta casa, agora tão exaltada, todo aquele que por ela passar pasmará, e assobiará, e dirá: Por que procedeu o SENHOR assim para com esta terra e esta casa?

[[v11-9-9]]

^<<v11-9-9,9>>^ Responder-se-lhe-á: Porque deixaram o SENHOR, seu Deus, que tirou da terra do Egito os seus pais, e se apegaram a outros deuses, e os adoraram, e os serviram. Por isso, trouxe o SENHOR sobre eles todo este mal.

[[v11-9-10]]

^<<v11-9-10,10>>^ Ao fim de vinte anos, terminara Salomão as duas casas, a Casa do SENHOR e a casa do rei.

[[v11-9-11]]

^<<v11-9-11,11>>^ Ora, como Hirão, rei de Tiro, trouxera a Salomão madeira de cedro e de cipreste e ouro, segundo todo o seu desejo, este lhe deu vinte cidades na terra da Galileia.

[[v11-9-12]]

^<<v11-9-12,12>>^ Saiu Hirão de Tiro a ver as cidades que Salomão lhe dera, porém não lhe agradaram.

[[v11-9-13]]

^<<v11-9-13,13>>^ Pelo que disse: Que cidades são estas que me deste, irmão meu? E lhes chamaram Terra de Cabul, até hoje.

[[v11-9-14]]

^<<v11-9-14,14>>^ Hirão tinha enviado ao rei cento e vinte talentos de ouro.

[[v11-9-15]]

^<<v11-9-15,15>>^ A razão por que Salomão impôs o trabalho forçado é esta: edificar a Casa do SENHOR, e a sua própria casa, e Milo, e o muro de Jerusalém, como também Hazor, e Megido, e Gezer;

[[v11-9-16]]

^<<v11-9-16,16>>^ porque Faraó, rei do Egito, subira, e tomara a Gezer, e a queimara, e matara os cananeus que moravam nela, e com ela dotara a sua filha, mulher de Salomão.

[[v11-9-17]]

^<<v11-9-17,17>>^ Assim, edificou Salomão Gezer, Bete-Horom, a baixa,

[[v11-9-18]]

^<<v11-9-18,18>>^ Baalate, Tadmor, no deserto daquela terra,

[[v11-9-19]]

^<<v11-9-19,19>>^ todas as cidades-armazéns que Salomão tinha, as cidades para os carros, as cidades para os cavaleiros e o que desejou enfim edificar em Jerusalém, no Líbano e em toda a terra do seu domínio.

[[v11-9-20]]

^<<v11-9-20,20>>^ Quanto a todo o povo que restou dos amorreus, heteus, ferezeus, heveus e jebuseus, e que não eram dos filhos de Israel,

[[v11-9-21]]

^<<v11-9-21,21>>^ a seus filhos, que restaram depois deles na terra, os quais os filhos de Israel não puderam destruir totalmente, a esses fez Salomão trabalhadores forçados, até hoje.

[[v11-9-22]]

^<<v11-9-22,22>>^ Porém dos filhos de Israel não fez Salomão escravo algum; eram homens de guerra, e seus oficiais, e seus príncipes, e seus capitães, e chefes dos seus carros e dos seus cavalarianos.

[[v11-9-23]]

^<<v11-9-23,23>>^ Os principais oficiais que estavam sobre a obra de Salomão eram quinhentos e cinquenta; tinham estes a seu cargo o povo que trabalhava na obra.

[[v11-9-24]]

^<<v11-9-24,24>>^ Subiu, porém, a filha de Faraó da Cidade de Davi à sua casa, que Salomão lhe edificara; então, edificou a Milo.

[[v11-9-25]]

^<<v11-9-25,25>>^ Oferecia Salomão, três vezes por ano, holocaustos e sacrifícios pacíficos sobre o altar que edificara ao SENHOR e queimava incenso sobre o altar perante o SENHOR. Assim, acabou ele a casa.

[[v11-9-26]]

^<<v11-9-26,26>>^ Fez o rei Salomão também naus em Eziom-Geber, que está junto a Elate, na praia do mar Vermelho, na terra de Edom.

[[v11-9-27]]

^<<v11-9-27,27>>^ Mandou Hirão, com aquelas naus, os seus servos, marinheiros, conhecedores do mar, com os servos de Salomão.

[[v11-9-28]]

^<<v11-9-28,28>>^ Chegaram a Ofir e tomaram de lá quatrocentos e vinte talentos de ouro, que trouxeram ao rei Salomão.

'''

xref:011-1-reis/011-1-reis-008.adoc#v11-8-0[&#60; Capítulo Anterior] | <<v11-9-0,Topo>> | xref:011-1-reis/011-1-reis-010.adoc#v11-10-0[Próximo Capítulo &#62;]