include::./index.adoc[]

[[v11-19-0]]
=== 1 Reis, 19
// ara ?, ARA - Almeida Revista e Atualizada

[[v11-19-1]]

^<<v11-19-1,1>>^ Acabe fez saber a Jezabel tudo quanto Elias havia feito e como matara todos os profetas à espada.

[[v11-19-2]]

^<<v11-19-2,2>>^ Então, Jezabel mandou um mensageiro a Elias a dizer-lhe: Façam-me os deuses como lhes aprouver se amanhã a estas horas não fizer eu à tua vida como fizeste a cada um deles.

[[v11-19-3]]

^<<v11-19-3,3>>^ Temendo, pois, Elias, levantou-se, e, para salvar sua vida, se foi, e chegou a Berseba, que pertence a Judá; e ali deixou o seu moço.

[[v11-19-4]]

^<<v11-19-4,4>>^ Ele mesmo, porém, se foi ao deserto, caminho de um dia, e veio, e se assentou debaixo de um zimbro; e pediu para si a morte e disse: Basta; toma agora, ó SENHOR, a minha alma, pois não sou melhor do que meus pais.

[[v11-19-5]]

^<<v11-19-5,5>>^ Deitou-se e dormiu debaixo do zimbro; eis que um anjo o tocou e lhe disse: Levanta-te e come.

[[v11-19-6]]

^<<v11-19-6,6>>^ Olhou ele e viu, junto à cabeceira, um pão cozido sobre pedras em brasa e uma botija de água. Comeu, bebeu e tornou a dormir.

[[v11-19-7]]

^<<v11-19-7,7>>^ Voltou segunda vez o anjo do SENHOR, tocou-o e lhe disse: Levanta-te e come, porque o caminho te será sobremodo longo.

[[v11-19-8]]

^<<v11-19-8,8>>^ Levantou-se, pois, comeu e bebeu; e, com a força daquela comida, caminhou quarenta dias e quarenta noites até Horebe, o monte de Deus.

[[v11-19-9]]

^<<v11-19-9,9>>^ Ali, entrou numa caverna, onde passou a noite; e eis que lhe veio a palavra do SENHOR e lhe disse: Que fazes aqui, Elias?

[[v11-19-10]]

^<<v11-19-10,10>>^ Ele respondeu: Tenho sido zeloso pelo SENHOR, Deus dos Exércitos, porque os filhos de Israel deixaram a tua aliança, derribaram os teus altares e mataram os teus profetas à espada; e eu fiquei só, e procuram tirar-me a vida.

[[v11-19-11]]

^<<v11-19-11,11>>^ Disse-lhe Deus: Sai e põe-te neste monte perante o SENHOR. Eis que passava o SENHOR; e um grande e forte vento fendia os montes e despedaçava as penhas diante do SENHOR, porém o SENHOR não estava no vento; depois do vento, um terremoto, mas o SENHOR não estava no terremoto;

[[v11-19-12]]

^<<v11-19-12,12>>^ depois do terremoto, um fogo, mas o SENHOR não estava no fogo; e, depois do fogo, um cicio tranquilo e suave.

[[v11-19-13]]

^<<v11-19-13,13>>^ Ouvindo-o Elias, envolveu o rosto no seu manto e, saindo, pôs-se à entrada da caverna. Eis que lhe veio uma voz e lhe disse: Que fazes aqui, Elias?

[[v11-19-14]]

^<<v11-19-14,14>>^ Ele respondeu: Tenho sido em extremo zeloso pelo SENHOR, Deus dos Exércitos, porque os filhos de Israel deixaram a tua aliança, derribaram os teus altares e mataram os teus profetas à espada; e eu fiquei só, e procuram tirar-me a vida.

[[v11-19-15]]

^<<v11-19-15,15>>^ Disse-lhe o SENHOR: Vai, volta ao teu caminho para o deserto de Damasco e, em chegando lá, unge a Hazael rei sobre a Síria.

[[v11-19-16]]

^<<v11-19-16,16>>^ A Jeú, filho de Ninsi, ungirás rei sobre Israel e também Eliseu, filho de Safate, de Abel-Meolá, ungirás profeta em teu lugar.

[[v11-19-17]]

^<<v11-19-17,17>>^ Quem escapar à espada de Hazael, Jeú o matará; quem escapar à espada de Jeú, Eliseu o matará.

[[v11-19-18]]

^<<v11-19-18,18>>^ Também conservei em Israel sete mil, todos os joelhos que não se dobraram a Baal, e toda boca que o não beijou.

[[v11-19-19]]

^<<v11-19-19,19>>^ Partiu, pois, Elias dali e achou a Eliseu, filho de Safate, que andava lavrando com doze juntas de bois adiante dele; ele estava com a duodécima. Elias passou por ele e lançou o seu manto sobre ele.

[[v11-19-20]]

^<<v11-19-20,20>>^ Então, deixou este os bois, correu após Elias e disse: Deixa-me beijar a meu pai e a minha mãe e, então, te seguirei. Elias respondeu-lhe: Vai e volta; pois já sabes o que fiz contigo.

[[v11-19-21]]

^<<v11-19-21,21>>^ Voltou Eliseu de seguir a Elias, tomou a junta de bois, e os imolou, e, com os aparelhos dos bois, cozeu as carnes, e as deu ao povo, e comeram. Então, se dispôs, e seguiu a Elias, e o servia.

'''

xref:011-1-reis/011-1-reis-018.adoc#v11-18-0[&#60; Capítulo Anterior] | <<v11-19-0,Topo>> | xref:011-1-reis/011-1-reis-020.adoc#v11-20-0[Próximo Capítulo &#62;]