include::./index.adoc[]

[[v11-5-0]]
=== 1 Reis, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v11-5-1]]

^<<v11-5-1,1>>^ Enviou também Hirão, rei de Tiro, os seus servos a Salomão (porque ouvira que ungiram a Salomão rei em lugar de seu pai), pois Hirão sempre fora amigo de Davi.

[[v11-5-2]]

^<<v11-5-2,2>>^ Então, Salomão enviou mensageiros a Hirão, dizendo:

[[v11-5-3]]

^<<v11-5-3,3>>^ Bem sabes que Davi, meu pai, não pôde edificar uma casa ao nome do SENHOR, seu Deus, por causa das guerras com que o envolveram os seus inimigos, até que o SENHOR lhos pôs debaixo dos pés.

[[v11-5-4]]

^<<v11-5-4,4>>^ Porém a mim o SENHOR, meu Deus, me tem dado descanso de todos os lados; não há nem inimigo, nem adversidade alguma.

[[v11-5-5]]

^<<v11-5-5,5>>^ Pelo que intento edificar uma casa ao nome do SENHOR, meu Deus, como falou o SENHOR a Davi, meu pai, dizendo: Teu filho, que porei em teu lugar no teu trono, esse edificará uma casa ao meu nome.

[[v11-5-6]]

^<<v11-5-6,6>>^ Dá ordem, pois, que do Líbano me cortem cedros; os meus servos estarão com os teus servos, e eu te pagarei o salário destes segundo determinares; porque bem sabes que entre o meu povo não há quem saiba cortar a madeira como os sidônios.

[[v11-5-7]]

^<<v11-5-7,7>>^ Ouvindo Hirão as palavras de Salomão, muito se alegrou e disse: Bendito seja, hoje, o SENHOR, que deu a Davi um filho sábio sobre este grande povo.

[[v11-5-8]]

^<<v11-5-8,8>>^ Enviou Hirão mensageiros a Salomão, dizendo: Ouvi o que mandaste dizer. Farei toda a tua vontade acerca das madeiras de cedro e de cipreste.

[[v11-5-9]]

^<<v11-5-9,9>>^ Os meus servos as levarão desde o Líbano até ao mar, e eu as farei conduzir em jangadas pelo mar até ao lugar que me designares e ali as desamarrarei; e tu as receberás. Tu também farás a minha vontade, dando provisões à minha casa.

[[v11-5-10]]

^<<v11-5-10,10>>^ Assim, deu Hirão a Salomão madeira de cedro e madeira de cipreste, segundo este queria.

[[v11-5-11]]

^<<v11-5-11,11>>^ Salomão deu a Hirão vinte mil coros de trigo, para sustento da sua casa, e vinte coros de azeite batido; e o fazia de ano em ano.

[[v11-5-12]]

^<<v11-5-12,12>>^ Deu o SENHOR sabedoria a Salomão, como lhe havia prometido. Havia paz entre Hirão e Salomão; e fizeram ambos entre si aliança.

[[v11-5-13]]

^<<v11-5-13,13>>^ Formou o rei Salomão uma leva de trabalhadores dentre todo o Israel, e se compunha de trinta mil homens.

[[v11-5-14]]

^<<v11-5-14,14>>^ E os enviava ao Líbano alternadamente, dez mil por mês; um mês estavam no Líbano, e dois meses, cada um em sua casa; e Adonirão dirigia a leva.

[[v11-5-15]]

^<<v11-5-15,15>>^ Tinha também Salomão setenta mil que levavam as cargas e oitenta mil que talhavam pedra nas montanhas,

[[v11-5-16]]

^<<v11-5-16,16>>^ afora os chefes-oficiais de Salomão, em número de três mil e trezentos, que dirigiam a obra e davam ordens ao povo que a executava.

[[v11-5-17]]

^<<v11-5-17,17>>^ Mandou o rei que trouxessem pedras grandes, e pedras preciosas, e pedras lavradas para fundarem a casa.

[[v11-5-18]]

^<<v11-5-18,18>>^ Lavravam-nas os edificadores de Salomão, e os de Hirão, e os giblitas; e preparavam a madeira e as pedras para se edificar a casa.

'''

xref:011-1-reis/011-1-reis-004.adoc#v11-4-0[&#60; Capítulo Anterior] | <<v11-5-0,Topo>> | xref:011-1-reis/011-1-reis-006.adoc#v11-6-0[Próximo Capítulo &#62;]