include::./index.adoc[]

[[v11-10-0]]
=== 1 Reis, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v11-10-1]]

^<<v11-10-1,1>>^ Tendo a rainha de Sabá ouvido a fama de Salomão, com respeito ao nome do SENHOR, veio prová-lo com perguntas difíceis.

[[v11-10-2]]

^<<v11-10-2,2>>^ Chegou a Jerusalém com mui grande comitiva; com camelos carregados de especiarias, e muitíssimo ouro, e pedras preciosas; compareceu perante Salomão e lhe expôs tudo quanto trazia em sua mente.

[[v11-10-3]]

^<<v11-10-3,3>>^ Salomão lhe deu resposta a todas as perguntas, e nada lhe houve profundo demais que não pudesse explicar.

[[v11-10-4]]

^<<v11-10-4,4>>^ Vendo, pois, a rainha de Sabá toda a sabedoria de Salomão, e a casa que edificara,

[[v11-10-5]]

^<<v11-10-5,5>>^ e a comida da sua mesa, e o lugar dos seus oficiais, e o serviço dos seus criados, e os trajes deles, e seus copeiros, e o holocausto que oferecia na Casa do SENHOR, ficou como fora de si

[[v11-10-6]]

^<<v11-10-6,6>>^ e disse ao rei: Foi verdade a palavra que a teu respeito ouvi na minha terra e a respeito da tua sabedoria.

[[v11-10-7]]

^<<v11-10-7,7>>^ Eu, contudo, não cria naquelas palavras, até que vim e vi com os meus próprios olhos. Eis que não me contaram a metade: sobrepujas em sabedoria e prosperidade a fama que ouvi.

[[v11-10-8]]

^<<v11-10-8,8>>^ Felizes os teus homens, felizes estes teus servos, que estão sempre diante de ti e que ouvem a tua sabedoria!

[[v11-10-9]]

^<<v11-10-9,9>>^ Bendito seja o SENHOR, teu Deus, que se agradou de ti para te colocar no trono de Israel; é porque o SENHOR ama a Israel para sempre, que te constituiu rei, para executares juízo e justiça.

[[v11-10-10]]

^<<v11-10-10,10>>^ Deu ela ao rei cento e vinte talentos de ouro, e muitíssimas especiarias, e pedras preciosas; nunca mais veio especiaria em tanta abundância, como a que a rainha de Sabá ofereceu ao rei Salomão.

[[v11-10-11]]

^<<v11-10-11,11>>^ Também as naus de Hirão, que de Ofir transportavam ouro, traziam de lá grande quantidade de madeira de sândalo e pedras preciosas.

[[v11-10-12]]

^<<v11-10-12,12>>^ Desta madeira de sândalo, fez o rei balaústres para a Casa do SENHOR e para a casa real, como também harpas e alaúdes para os cantores; tal madeira nunca se havia trazido para ali, nem se viu mais semelhante madeira até ao dia de hoje.

[[v11-10-13]]

^<<v11-10-13,13>>^ O rei Salomão deu à rainha de Sabá tudo quanto ela desejou e pediu, afora tudo o que lhe deu por sua generosidade real. Assim, voltou e se foi para a sua terra, com os seus servos.

[[v11-10-14]]

^<<v11-10-14,14>>^ O peso do ouro que se trazia a Salomão cada ano era de seiscentos e sessenta e seis talentos de ouro,

[[v11-10-15]]

^<<v11-10-15,15>>^ além do que entrava dos vendedores, e do tráfico dos negociantes, e de todos os reis da Arábia, e dos governadores da terra.

[[v11-10-16]]

^<<v11-10-16,16>>^ Fez o rei Salomão duzentos paveses de ouro batido; seiscentos siclos de ouro mandou pesar para cada pavês;

[[v11-10-17]]

^<<v11-10-17,17>>^ fez também trezentos escudos de ouro batido; três arráteis de ouro mandou pesar para cada escudo. E o rei os pôs na Casa do Bosque do Líbano.

[[v11-10-18]]

^<<v11-10-18,18>>^ Fez mais o rei um grande trono de marfim e o cobriu de ouro puríssimo.

[[v11-10-19]]

^<<v11-10-19,19>>^ O trono tinha seis degraus; o espaldar do trono, ao alto, era redondo; de ambos os lados tinha braços junto ao assento e dois leões junto aos braços.

[[v11-10-20]]

^<<v11-10-20,20>>^ Também doze leões estavam ali sobre os seis degraus, um em cada extremo destes. Nunca se fizera obra semelhante em nenhum dos reinos.

[[v11-10-21]]

^<<v11-10-21,21>>^ Todas as taças de que se servia o rei Salomão para beber eram de ouro, e também de ouro puro todas as da Casa do Bosque do Líbano; não havia nelas prata, porque nos dias de Salomão não se dava a ela estimação nenhuma.

[[v11-10-22]]

^<<v11-10-22,22>>^ Porque o rei tinha no mar uma frota de Társis, com as naus de Hirão; de três em três anos, voltava a frota de Társis, trazendo ouro, prata, marfim, bugios e pavões.

[[v11-10-23]]

^<<v11-10-23,23>>^ Assim, o rei Salomão excedeu a todos os reis do mundo, tanto em riqueza como em sabedoria.

[[v11-10-24]]

^<<v11-10-24,24>>^ Todo o mundo procurava ir ter com ele para ouvir a sabedoria que Deus lhe pusera no coração.

[[v11-10-25]]

^<<v11-10-25,25>>^ Cada um trazia o seu presente: objetos de prata e de ouro, roupas, armaduras, especiarias, cavalos e mulas; assim, ano após ano.

[[v11-10-26]]

^<<v11-10-26,26>>^ Também ajuntou Salomão carros e cavaleiros, tinha mil e quatrocentos carros e doze mil cavalarianos, que distribuiu às cidades para os carros e junto ao rei, em Jerusalém.

[[v11-10-27]]

^<<v11-10-27,27>>^ Fez o rei que, em Jerusalém, houvesse prata como pedras e cedros em abundância como os sicômoros que estão nas planícies.

[[v11-10-28]]

^<<v11-10-28,28>>^ Os cavalos de Salomão vinham do Egito e da Cilícia; e comerciantes do rei os recebiam da Cilícia por certo preço.

[[v11-10-29]]

^<<v11-10-29,29>>^ Importava-se, do Egito, um carro por seiscentos siclos de prata e um cavalo por cento e cinquenta; nas mesmas condições, as caravanas os traziam e os exportavam para todos os reis dos heteus e para os reis da Síria.

'''

xref:011-1-reis/011-1-reis-009.adoc#v11-9-0[&#60; Capítulo Anterior] | <<v11-10-0,Topo>> | xref:011-1-reis/011-1-reis-011.adoc#v11-11-0[Próximo Capítulo &#62;]