include::./index.adoc[]

[[v11-22-0]]
=== 1 Reis, 22
// ara ?, ARA - Almeida Revista e Atualizada

[[v11-22-1]]

^<<v11-22-1,1>>^ Três anos se passaram sem haver guerra entre a Síria e Israel.

[[v11-22-2]]

^<<v11-22-2,2>>^ Porém, no terceiro ano, desceu Josafá, rei de Judá, para avistar-se com o rei de Israel.

[[v11-22-3]]

^<<v11-22-3,3>>^ Disse o rei de Israel aos seus servos: Não sabeis vós que Ramote-Gileade é nossa, e nós hesitamos em tomá-la das mãos do rei da Síria?

[[v11-22-4]]

^<<v11-22-4,4>>^ Então, perguntou a Josafá: Irás tu comigo à peleja, a Ramote-Gileade? Respondeu Josafá ao rei de Israel: Serei como tu és, o meu povo, como o teu povo, os meus cavalos, como os teus cavalos.

[[v11-22-5]]

^<<v11-22-5,5>>^ Disse mais Josafá ao rei de Israel: Consulta primeiro a palavra do SENHOR.

[[v11-22-6]]

^<<v11-22-6,6>>^ Então, o rei de Israel ajuntou os profetas, cerca de quatrocentos homens, e lhes disse: Irei à peleja contra Ramote-Gileade ou deixarei de ir? Eles disseram: Sobe, porque o Senhor a entregará nas mãos do rei.

[[v11-22-7]]

^<<v11-22-7,7>>^ Disse, porém, Josafá: Não há aqui ainda algum profeta do SENHOR para o consultarmos?

[[v11-22-8]]

^<<v11-22-8,8>>^ Respondeu o rei de Israel a Josafá: Há um ainda, pelo qual se pode consultar o SENHOR, porém eu o aborreço, porque nunca profetiza de mim o que é bom, mas somente o que é mau. Este é Micaías, filho de Inlá. Disse Josafá: Não fale o rei assim.

[[v11-22-9]]

^<<v11-22-9,9>>^ Então, o rei de Israel chamou um oficial e disse: Traze-me depressa Micaías, filho de Inlá.

[[v11-22-10]]

^<<v11-22-10,10>>^ O rei de Israel e Josafá, rei de Judá, estavam assentados, cada um no seu trono, vestidos de trajes reais, numa eira à entrada da porta de Samaria; e todos os profetas profetizavam diante deles.

[[v11-22-11]]

^<<v11-22-11,11>>^ Zedequias, filho de Quenaana, fez para si uns chifres de ferro e disse: Assim diz o SENHOR: Com este escornearás os siros até de todo os consumir.

[[v11-22-12]]

^<<v11-22-12,12>>^ Todos os profetas profetizaram assim, dizendo: Sobe a Ramote-Gileade e triunfarás, porque o SENHOR a entregará nas mãos do rei.

[[v11-22-13]]

^<<v11-22-13,13>>^ O mensageiro que fora chamar a Micaías falou-lhe, dizendo: Eis que as palavras dos profetas a uma voz predizem coisas boas para o rei; seja, pois, a tua palavra como a palavra de um deles e fala o que é bom.

[[v11-22-14]]

^<<v11-22-14,14>>^ Respondeu Micaías: Tão certo como vive o SENHOR, o que o SENHOR me disser, isso falarei.

[[v11-22-15]]

^<<v11-22-15,15>>^ E, vindo ele ao rei, este lhe perguntou: Micaías, iremos a Ramote-Gileade à peleja ou deixaremos de ir? Ele lhe respondeu: Sobe e triunfarás, porque o SENHOR a entregará nas mãos do rei.

[[v11-22-16]]

^<<v11-22-16,16>>^ O rei lhe disse: Quantas vezes te conjurarei, que não me fales senão a verdade em nome do SENHOR?

[[v11-22-17]]

^<<v11-22-17,17>>^ Então, disse ele: Vi todo o Israel disperso pelos montes, como ovelhas que não têm pastor; e disse o SENHOR: Estes não têm dono; torne cada um em paz para a sua casa.

[[v11-22-18]]

^<<v11-22-18,18>>^ Então, o rei de Israel disse a Josafá: Não te disse eu que ele não profetiza a meu respeito o que é bom, mas somente o que é mau?

[[v11-22-19]]

^<<v11-22-19,19>>^ Micaías prosseguiu: Ouve, pois, a palavra do SENHOR: Vi o SENHOR assentado no seu trono, e todo o exército do céu estava junto a ele, à sua direita e à sua esquerda.

[[v11-22-20]]

^<<v11-22-20,20>>^ Perguntou o SENHOR: Quem enganará a Acabe, para que suba e caia em Ramote-Gileade? Um dizia desta maneira, e outro, de outra.

[[v11-22-21]]

^<<v11-22-21,21>>^ Então, saiu um espírito, e se apresentou diante do SENHOR, e disse: Eu o enganarei. Perguntou-lhe o SENHOR: Com quê?

[[v11-22-22]]

^<<v11-22-22,22>>^ Respondeu ele: Sairei e serei espírito mentiroso na boca de todos os seus profetas. Disse o SENHOR: Tu o enganarás e ainda prevalecerás; sai e faze-o assim.

[[v11-22-23]]

^<<v11-22-23,23>>^ Eis que o SENHOR pôs o espírito mentiroso na boca de todos estes teus profetas e o SENHOR falou o que é mau contra ti.

[[v11-22-24]]

^<<v11-22-24,24>>^ Então, Zedequias, filho de Quenaana, chegou, deu uma bofetada em Micaías e disse: Por onde saiu de mim o Espírito do SENHOR para falar a ti?

[[v11-22-25]]

^<<v11-22-25,25>>^ Disse Micaías: Eis que o verás naquele mesmo dia, quando entrares de câmara em câmara, para te esconderes.

[[v11-22-26]]

^<<v11-22-26,26>>^ Então, disse o rei de Israel: Tomai Micaías e devolvei-o a Amom, governador da cidade, e a Joás, filho do rei;

[[v11-22-27]]

^<<v11-22-27,27>>^ e direis: Assim diz o rei: Metei este homem na casa do cárcere e angustiai-o, com escassez de pão e de água, até que eu volte em paz.

[[v11-22-28]]

^<<v11-22-28,28>>^ Disse Micaías: Se voltares em paz, não falou o SENHOR, na verdade, por mim. Disse mais: Ouvi isto, vós, todos os povos!

[[v11-22-29]]

^<<v11-22-29,29>>^ Subiram o rei de Israel e Josafá, rei de Judá, a Ramote-Gileade.

[[v11-22-30]]

^<<v11-22-30,30>>^ Disse o rei de Israel a Josafá: Eu me disfarçarei e entrarei na peleja; tu, porém, traja as tuas vestes. Disfarçou-se, pois, o rei de Israel e entrou na peleja.

[[v11-22-31]]

^<<v11-22-31,31>>^ Ora, o rei da Síria dera ordem aos trinta e dois capitães dos seus carros, dizendo: Não pelejareis nem contra pequeno nem contra grande, mas somente contra o rei de Israel.

[[v11-22-32]]

^<<v11-22-32,32>>^ Vendo os capitães dos carros Josafá, disseram: Certamente, este é o rei de Israel. E a ele se dirigiram para o atacar. Porém Josafá gritou.

[[v11-22-33]]

^<<v11-22-33,33>>^ Vendo os capitães dos carros que não era o rei de Israel, deixaram de o perseguir.

[[v11-22-34]]

^<<v11-22-34,34>>^ Então, um homem entesou o arco e, atirando ao acaso, feriu o rei de Israel por entre as juntas da sua armadura; então, disse este ao seu cocheiro: Vira e leva-me para fora do combate, porque estou gravemente ferido.

[[v11-22-35]]

^<<v11-22-35,35>>^ A peleja tornou-se renhida naquele dia; quanto ao rei, seguraram-no de pé no carro defronte dos siros, mas à tarde morreu. O sangue corria da ferida para o fundo do carro.

[[v11-22-36]]

^<<v11-22-36,36>>^ Ao pôr do sol, fez-se ouvir um pregão pelo exército, que dizia: Cada um para a sua cidade, e cada um para a sua terra!

[[v11-22-37]]

^<<v11-22-37,37>>^ Morto o rei, levaram-no a Samaria, onde o sepultaram.

[[v11-22-38]]

^<<v11-22-38,38>>^ Quando lavaram o carro junto ao açude de Samaria, os cães lamberam o sangue do rei, segundo a palavra que o SENHOR tinha dito; as prostitutas banharam-se nestas águas.

[[v11-22-39]]

^<<v11-22-39,39>>^ Quanto aos mais atos de Acabe, e a tudo quanto fez, e à casa de marfim que construiu, e a todas as cidades que edificou, porventura, não estão escritos no Livro da História dos Reis de Israel?

[[v11-22-40]]

^<<v11-22-40,40>>^ Assim, descansou Acabe com seus pais; e Acazias, seu filho, reinou em seu lugar.

[[v11-22-41]]

^<<v11-22-41,41>>^ E Josafá, filho de Asa, começou a reinar sobre Judá no quarto ano de Acabe, rei de Israel.

[[v11-22-42]]

^<<v11-22-42,42>>^ Era Josafá da idade de trinta e cinco anos quando começou a reinar; e vinte e cinco anos reinou em Jerusalém. Sua mãe se chamava Azuba, filha de Sili.

[[v11-22-43]]

^<<v11-22-43,43>>^ Ele andou em todos os caminhos de Asa, seu pai; não se desviou deles e fez o que era reto perante o SENHOR.

[[v11-22-44]]

^<<v11-22-44,44>>^ Todavia, os altos não se tiraram; neles, o povo ainda sacrificava e queimava incenso.

[[v11-22-45]]

^<<v11-22-45,45>>^ Josafá viveu em paz com o rei de Israel.

[[v11-22-46]]

^<<v11-22-46,46>>^ Quanto aos mais atos de Josafá, e ao poder que mostrou, e como guerreou, porventura, não estão escritos no Livro da História dos Reis de Judá?

[[v11-22-47]]

^<<v11-22-47,47>>^ Também exterminou da terra os restantes dos prostitutos cultuais que ficaram nos dias de Asa, seu pai.

[[v11-22-48]]

^<<v11-22-48,48>>^ Então, não havia rei em Edom, porém reinava um governador.

[[v11-22-49]]

^<<v11-22-49,49>>^ Fez Josafá navios de Társis, para irem a Ofir em busca de ouro; porém não foram, porque os navios se quebraram em Eziom-Geber.

[[v11-22-50]]

^<<v11-22-50,50>>^ Então, Acazias, filho de Acabe, disse a Josafá: Vão os meus servos embarcados com os teus. Porém Josafá não quis.

[[v11-22-51]]

^<<v11-22-51,51>>^ Josafá descansou com seus pais e foi sepultado na Cidade de Davi, seu pai; e Jeorão, seu filho, reinou em seu lugar.

[[v11-22-52]]

^<<v11-22-52,52>>^ Acazias, filho de Acabe, começou a reinar sobre Israel em Samaria, no décimo sétimo ano de Josafá, rei de Judá; e reinou dois anos sobre Israel.

[[v11-22-53]]

^<<v11-22-53,53>>^ Fez o que era mau perante o SENHOR; porque andou nos caminhos de seu pai, como também nos caminhos de sua mãe e nos caminhos de Jeroboão, filho de Nebate, que fez pecar a Israel.

[[v11-22-54]]

^<<v11-22-54,54>>^ Ele serviu a Baal, e o adorou, e provocou à ira ao SENHOR, Deus de Israel, segundo tudo quanto fizera seu pai.

'''

xref:011-1-reis/011-1-reis-021.adoc#v11-21-0[&#60; Capítulo Anterior] | <<v11-22-0,Topo>> | xref:012-2-reis/012-2-reis-001.adoc#v12-1-0[Próximo Capítulo &#62;]