include::./index.adoc[]

[[v11-18-0]]
=== 1 Reis, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v11-18-1]]

^<<v11-18-1,1>>^ Muito tempo depois, veio a palavra do SENHOR a Elias, no terceiro ano, dizendo: Vai, apresenta-te a Acabe, porque darei chuva sobre a terra.

[[v11-18-2]]

^<<v11-18-2,2>>^ Partiu, pois, Elias a apresentar-se a Acabe; e a fome era extrema em Samaria.

[[v11-18-3]]

^<<v11-18-3,3>>^ Acabe chamou a Obadias, o mordomo. (Obadias temia muito ao SENHOR,

[[v11-18-4]]

^<<v11-18-4,4>>^ porque, quando Jezabel exterminava os profetas do SENHOR, Obadias tomou cem profetas, e de cinquenta em cinquenta os escondeu numa cova, e os sustentou com pão e água.)

[[v11-18-5]]

^<<v11-18-5,5>>^ Disse Acabe a Obadias: Vai pela terra a todas as fontes de água e a todos os vales; pode ser que achemos erva, para que salvemos a vida aos cavalos e mulos e não percamos todos os animais.

[[v11-18-6]]

^<<v11-18-6,6>>^ Repartiram entre si a terra, para a percorrerem; Acabe foi à parte por um caminho, e Obadias foi sozinho por outro.

[[v11-18-7]]

^<<v11-18-7,7>>^ Estando Obadias já de caminho, eis que Elias se encontrou com ele. Obadias, reconhecendo-o, prostrou-se com o rosto em terra e disse: És tu meu senhor Elias?

[[v11-18-8]]

^<<v11-18-8,8>>^ Respondeu-lhe ele: Sou eu; vai e dize a teu senhor: Eis que aí está Elias.

[[v11-18-9]]

^<<v11-18-9,9>>^ Porém ele disse: Em que pequei, para que entregues teu servo na mão de Acabe, e ele me mate?

[[v11-18-10]]

^<<v11-18-10,10>>^ Tão certo como vive o SENHOR, teu Deus, não houve nação nem reino aonde o meu senhor não mandasse homens à tua procura; e, dizendo eles: Aqui não está; fazia jurar aquele reino e aquela nação que te não haviam achado.

[[v11-18-11]]

^<<v11-18-11,11>>^ Agora, tu dizes: Vai, dize a teu senhor: Eis que aí está Elias.

[[v11-18-12]]

^<<v11-18-12,12>>^ Poderá ser que, apartando-me eu de ti, o Espírito do SENHOR te leve não sei para onde, e, vindo eu a dar as novas a Acabe, e não te achando ele, me matará; eu, contudo, teu servo, temo ao SENHOR desde a minha mocidade.

[[v11-18-13]]

^<<v11-18-13,13>>^ Acaso, não disseram a meu senhor o que fiz, quando Jezabel matava os profetas do SENHOR, como escondi cem homens dos profetas do SENHOR, de cinquenta em cinquenta, numas covas, e os sustentei com pão e água?

[[v11-18-14]]

^<<v11-18-14,14>>^ E, agora, tu dizes: Vai, dize a teu senhor: Eis que aí está Elias. Ele me matará.

[[v11-18-15]]

^<<v11-18-15,15>>^ Disse Elias: Tão certo como vive o SENHOR dos Exércitos, perante cuja face estou, deveras, hoje, me apresentarei a ele.

[[v11-18-16]]

^<<v11-18-16,16>>^ Então, foi Obadias encontrar-se com Acabe e lho anunciou; e foi Acabe ter com Elias.

[[v11-18-17]]

^<<v11-18-17,17>>^ Vendo-o, disse-lhe: És tu, ó perturbador de Israel?

[[v11-18-18]]

^<<v11-18-18,18>>^ Respondeu Elias: Eu não tenho perturbado a Israel, mas tu e a casa de teu pai, porque deixastes os mandamentos do SENHOR e seguistes os baalins.

[[v11-18-19]]

^<<v11-18-19,19>>^ Agora, pois, manda ajuntar a mim todo o Israel no monte Carmelo, como também os quatrocentos e cinquenta profetas de Baal e os quatrocentos profetas do poste-ídolo que comem da mesa de Jezabel.

[[v11-18-20]]

^<<v11-18-20,20>>^ Então, enviou Acabe mensageiros a todos os filhos de Israel e ajuntou os profetas no monte Carmelo.

[[v11-18-21]]

^<<v11-18-21,21>>^ Então, Elias se chegou a todo o povo e disse: Até quando coxeareis entre dois pensamentos? Se o SENHOR é Deus, segui-o; se é Baal, segui-o. Porém o povo nada lhe respondeu.

[[v11-18-22]]

^<<v11-18-22,22>>^ Então, disse Elias ao povo: Só eu fiquei dos profetas do SENHOR, e os profetas de Baal são quatrocentos e cinquenta homens.

[[v11-18-23]]

^<<v11-18-23,23>>^ Deem-se-nos, pois, dois novilhos; escolham eles para si um dos novilhos e, dividindo-o em pedaços, o ponham sobre a lenha, porém não lhe metam fogo; eu prepararei o outro novilho, e o porei sobre a lenha, e não lhe meterei fogo.

[[v11-18-24]]

^<<v11-18-24,24>>^ Então, invocai o nome de vosso deus, e eu invocarei o nome do SENHOR; e há de ser que o deus que responder por fogo esse é que é Deus. E todo o povo respondeu e disse: É boa esta palavra.

[[v11-18-25]]

^<<v11-18-25,25>>^ Disse Elias aos profetas de Baal: Escolhei para vós outros um dos novilhos, e preparai-o primeiro, porque sois muitos, e invocai o nome de vosso deus; e não lhe metais fogo.

[[v11-18-26]]

^<<v11-18-26,26>>^ Tomaram o novilho que lhes fora dado, prepararam-no e invocaram o nome de Baal, desde a manhã até ao meio-dia, dizendo: Ah! Baal, responde-nos! Porém não havia uma voz que respondesse; e, manquejando, se movimentavam ao redor do altar que tinham feito.

[[v11-18-27]]

^<<v11-18-27,27>>^ Ao meio-dia, Elias zombava deles, dizendo: Clamai em altas vozes, porque ele é deus; pode ser que esteja meditando, ou atendendo a necessidades, ou de viagem, ou a dormir e despertará.

[[v11-18-28]]

^<<v11-18-28,28>>^ E eles clamavam em altas vozes e se retalhavam com facas e com lancetas, segundo o seu costume, até derramarem sangue.

[[v11-18-29]]

^<<v11-18-29,29>>^ Passado o meio-dia, profetizaram eles, até que a oferta de manjares se oferecesse; porém não houve voz, nem resposta, nem atenção alguma.

[[v11-18-30]]

^<<v11-18-30,30>>^ Então, Elias disse a todo o povo: Chegai-vos a mim. E todo o povo se chegou a ele; Elias restaurou o altar do SENHOR, que estava em ruínas.

[[v11-18-31]]

^<<v11-18-31,31>>^ Tomou doze pedras, segundo o número das tribos dos filhos de Jacó, ao qual viera a palavra do SENHOR, dizendo: Israel será o teu nome.

[[v11-18-32]]

^<<v11-18-32,32>>^ Com aquelas pedras edificou o altar em nome do SENHOR; depois, fez um rego em redor do altar tão grande como para semear duas medidas de sementes.

[[v11-18-33]]

^<<v11-18-33,33>>^ Então, armou a lenha, dividiu o novilho em pedaços, pô-lo sobre a lenha

[[v11-18-34]]

^<<v11-18-34,34>>^ e disse: Enchei de água quatro cântaros e derramai-a sobre o holocausto e sobre a lenha. Disse ainda: Fazei-o segunda vez; e o fizeram. Disse mais: Fazei-o terceira vez; e o fizeram terceira vez.

[[v11-18-35]]

^<<v11-18-35,35>>^ De maneira que a água corria ao redor do altar; ele encheu também de água o rego.

[[v11-18-36]]

^<<v11-18-36,36>>^ No devido tempo, para se apresentar a oferta de manjares, aproximou-se o profeta Elias e disse: Ó SENHOR, Deus de Abraão, de Isaque e de Israel, fique, hoje, sabido que tu és Deus em Israel, e que eu sou teu servo e que, segundo a tua palavra, fiz todas estas coisas.

[[v11-18-37]]

^<<v11-18-37,37>>^ Responde-me, SENHOR, responde-me, para que este povo saiba que tu, SENHOR, és Deus e que a ti fizeste retroceder o coração deles.

[[v11-18-38]]

^<<v11-18-38,38>>^ Então, caiu fogo do SENHOR, e consumiu o holocausto, e a lenha, e as pedras, e a terra, e ainda lambeu a água que estava no rego.

[[v11-18-39]]

^<<v11-18-39,39>>^ O que vendo todo o povo, caiu de rosto em terra e disse: O SENHOR é Deus! O SENHOR é Deus!

[[v11-18-40]]

^<<v11-18-40,40>>^ Disse-lhes Elias: Lançai mão dos profetas de Baal, que nem um deles escape. Lançaram mão deles; e Elias os fez descer ao ribeiro de Quisom e ali os matou.

[[v11-18-41]]

^<<v11-18-41,41>>^ Então, disse Elias a Acabe: Sobe, come e bebe, porque já se ouve ruído de abundante chuva.

[[v11-18-42]]

^<<v11-18-42,42>>^ Subiu Acabe a comer e a beber; Elias, porém, subiu ao cimo do Carmelo, e, encurvado para a terra, meteu o rosto entre os joelhos,

[[v11-18-43]]

^<<v11-18-43,43>>^ e disse ao seu moço: Sobe e olha para o lado do mar. Ele subiu, olhou e disse: Não há nada. Então, lhe disse Elias: Volta. E assim por sete vezes.

[[v11-18-44]]

^<<v11-18-44,44>>^ À sétima vez disse: Eis que se levanta do mar uma nuvem pequena como a palma da mão do homem. Então, disse ele: Sobe e dize a Acabe: Aparelha o teu carro e desce, para que a chuva não te detenha.

[[v11-18-45]]

^<<v11-18-45,45>>^ Dentro em pouco, os céus se enegreceram, com nuvens e vento, e caiu grande chuva. Acabe subiu ao carro e foi para Jezreel.

[[v11-18-46]]

^<<v11-18-46,46>>^ A mão do SENHOR veio sobre Elias, o qual cingiu os lombos e correu adiante de Acabe, até à entrada de Jezreel.

'''

xref:011-1-reis/011-1-reis-017.adoc#v11-17-0[&#60; Capítulo Anterior] | <<v11-18-0,Topo>> | xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[Próximo Capítulo &#62;]