include::./index.adoc[]

[[v11-11-0]]
=== 1 Reis, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v11-11-1]]

^<<v11-11-1,1>>^ Ora, além da filha de Faraó, amou Salomão muitas mulheres estrangeiras: moabitas, amonitas, edomitas, sidônias e heteias,

[[v11-11-2]]

^<<v11-11-2,2>>^ mulheres das nações de que havia o SENHOR dito aos filhos de Israel: Não caseis com elas, nem casem elas convosco, pois vos perverteriam o coração, para seguirdes os seus deuses. A estas se apegou Salomão pelo amor.

[[v11-11-3]]

^<<v11-11-3,3>>^ Tinha setecentas mulheres, princesas e trezentas concubinas; e suas mulheres lhe perverteram o coração.

[[v11-11-4]]

^<<v11-11-4,4>>^ Sendo já velho, suas mulheres lhe perverteram o coração para seguir outros deuses; e o seu coração não era de todo fiel para com o SENHOR, seu Deus, como fora o de Davi, seu pai.

[[v11-11-5]]

^<<v11-11-5,5>>^ Salomão seguiu a Astarote, deusa dos sidônios, e a Milcom, abominação dos amonitas.

[[v11-11-6]]

^<<v11-11-6,6>>^ Assim, fez Salomão o que era mau perante o SENHOR e não perseverou em seguir ao SENHOR, como Davi, seu pai.

[[v11-11-7]]

^<<v11-11-7,7>>^ Nesse tempo, edificou Salomão um santuário a Quemos, abominação de Moabe, sobre o monte fronteiro a Jerusalém, e a Moloque, abominação dos filhos de Amom.

[[v11-11-8]]

^<<v11-11-8,8>>^ Assim fez para com todas as suas mulheres estrangeiras, as quais queimavam incenso e sacrificavam a seus deuses.

[[v11-11-9]]

^<<v11-11-9,9>>^ Pelo que o SENHOR se indignou contra Salomão, pois desviara o seu coração do SENHOR, Deus de Israel, que duas vezes lhe aparecera.

[[v11-11-10]]

^<<v11-11-10,10>>^ E acerca disso lhe tinha ordenado que não seguisse a outros deuses. Ele, porém, não guardou o que o SENHOR lhe ordenara.

[[v11-11-11]]

^<<v11-11-11,11>>^ Por isso, disse o SENHOR a Salomão: Visto que assim procedeste e não guardaste a minha aliança, nem os meus estatutos que te mandei, tirarei de ti este reino e o darei a teu servo.

[[v11-11-12]]

^<<v11-11-12,12>>^ Contudo, não o farei nos teus dias, por amor de Davi, teu pai; da mão de teu filho o tirarei.

[[v11-11-13]]

^<<v11-11-13,13>>^ Todavia, não tirarei o reino todo; darei uma tribo a teu filho, por amor de Davi, meu servo, e por amor de Jerusalém, que escolhi.

[[v11-11-14]]

^<<v11-11-14,14>>^ Levantou o SENHOR contra Salomão um adversário, Hadade, o edomita; este era da linhagem real de Edom.

[[v11-11-15]]

^<<v11-11-15,15>>^ Porque, estando Davi em Edom e tendo subido Joabe, comandante do exército, a sepultar os mortos, feriu todos os varões em Edom.

[[v11-11-16]]

^<<v11-11-16,16>>^ (Porque Joabe ficou ali seis meses com todo o Israel, até que eliminou todos os varões em Edom.)

[[v11-11-17]]

^<<v11-11-17,17>>^ Hadade, porém, fugiu, e, com ele, alguns homens edomitas, dos servos de seu pai, para ir ao Egito; era Hadade ainda muito jovem.

[[v11-11-18]]

^<<v11-11-18,18>>^ Partiram de Midiã e seguiram a Parã, de onde tomaram consigo homens e chegaram ao Egito, a Faraó, rei do Egito, o qual deu a Hadade uma casa, e lhe prometeu sustento, e lhe deu terras.

[[v11-11-19]]

^<<v11-11-19,19>>^ Achou Hadade grande mercê por parte de Faraó, tanta que este lhe deu por mulher a irmã de sua própria mulher,

[[v11-11-20]]

^<<v11-11-20,20>>^ a irmã de Tafnes, a rainha. A irmã de Tafnes deu-lhe à luz seu filho Genubate, o qual Tafnes criou na casa de Faraó, onde Genubate ficou entre os filhos de Faraó.

[[v11-11-21]]

^<<v11-11-21,21>>^ Tendo, pois, Hadade ouvido no Egito que Davi descansara com seus pais e que Joabe, comandante do exército, era morto, disse a Faraó: Deixa-me voltar para a minha terra.

[[v11-11-22]]

^<<v11-11-22,22>>^ Então, Faraó lhe disse: Pois que te falta comigo, que procuras partir para a tua terra? Respondeu ele: Nada; porém deixa-me ir.

[[v11-11-23]]

^<<v11-11-23,23>>^ Também Deus levantou a Salomão outro adversário, Rezom, filho de Eliada, que havia fugido de seu senhor Hadadezer, rei de Zobá.

[[v11-11-24]]

^<<v11-11-24,24>>^ Ele ajuntou homens e se fez capitão de um bando; depois do morticínio feito por Davi, eles se foram para Damasco, onde habitaram e onde constituíram rei a Rezom.

[[v11-11-25]]

^<<v11-11-25,25>>^ Este foi adversário de Israel por todos os dias de Salomão, fez-lhe mal como Hadade, detestava a Israel e reinava sobre a Síria.

[[v11-11-26]]

^<<v11-11-26,26>>^ Jeroboão, filho de Nebate, efraimita de Zereda, servo de Salomão, e cuja mãe era mulher viúva, por nome Zerua, levantou a mão contra o rei.

[[v11-11-27]]

^<<v11-11-27,27>>^ Esta foi a causa por que levantou a mão contra o rei: Salomão estava edificando a Milo e terraplenando depressões da Cidade de Davi, seu pai.

[[v11-11-28]]

^<<v11-11-28,28>>^ Ora, vendo Salomão que Jeroboão era homem valente e capaz, moço laborioso, ele o pôs sobre todo o trabalho forçado da casa de José.

[[v11-11-29]]

^<<v11-11-29,29>>^ Sucedeu, nesse tempo, que, saindo Jeroboão de Jerusalém, o encontrou o profeta Aías, o silonita, no caminho; este se tinha vestido de uma capa nova, e estavam sós os dois no campo.

[[v11-11-30]]

^<<v11-11-30,30>>^ Aías pegou na capa nova que tinha sobre si, rasgou-a em doze pedaços

[[v11-11-31]]

^<<v11-11-31,31>>^ e disse a Jeroboão: Toma dez pedaços, porque assim diz o SENHOR, Deus de Israel: Eis que rasgarei o reino da mão de Salomão, e a ti darei dez tribos.

[[v11-11-32]]

^<<v11-11-32,32>>^ Porém ele terá uma tribo, por amor de Davi, meu servo, e por amor de Jerusalém, a cidade que escolhi de todas as tribos de Israel.

[[v11-11-33]]

^<<v11-11-33,33>>^ Porque Salomão me deixou e se encurvou a Astarote, deusa dos sidônios, a Quemos, deus de Moabe, e a Milcom, deus dos filhos de Amom; e não andou nos meus caminhos para fazer o que é reto perante mim, a saber, os meus estatutos e os meus juízos, como fez Davi, seu pai.

[[v11-11-34]]

^<<v11-11-34,34>>^ Porém não tomarei da sua mão o reino todo; pelo contrário, fá-lo-ei príncipe todos os dias da sua vida, por amor de Davi, meu servo, a quem elegi, porque guardou os meus mandamentos e os meus estatutos.

[[v11-11-35]]

^<<v11-11-35,35>>^ Mas da mão de seu filho tomarei o reino, a saber, as dez tribos, e tas darei a ti.

[[v11-11-36]]

^<<v11-11-36,36>>^ E a seu filho darei uma tribo; para que Davi, meu servo, tenha sempre uma lâmpada diante de mim em Jerusalém, a cidade que escolhi para pôr ali o meu nome.

[[v11-11-37]]

^<<v11-11-37,37>>^ Tomar-te-ei, e reinarás sobre tudo o que desejar a tua alma; e serás rei sobre Israel.

[[v11-11-38]]

^<<v11-11-38,38>>^ Se ouvires tudo o que eu te ordenar, e andares nos meus caminhos, e fizeres o que é reto perante mim, guardando os meus estatutos e os meus mandamentos, como fez Davi, meu servo, eu serei contigo, e te edificarei uma casa estável, como edifiquei a Davi, e te darei Israel.

[[v11-11-39]]

^<<v11-11-39,39>>^ Por isso, afligirei a descendência de Davi; todavia, não para sempre.

[[v11-11-40]]

^<<v11-11-40,40>>^ Pelo que Salomão procurou matar a Jeroboão; este, porém, se dispôs e fugiu para o Egito, a ter com Sisaque, rei do Egito; e ali permaneceu até à morte de Salomão.

[[v11-11-41]]

^<<v11-11-41,41>>^ Quanto aos mais atos de Salomão, a tudo quanto fez, e à sua sabedoria, porventura, não estão escritos no Livro da História de Salomão?

[[v11-11-42]]

^<<v11-11-42,42>>^ Foi de quarenta anos o tempo que reinou Salomão em Jerusalém sobre todo o Israel.

[[v11-11-43]]

^<<v11-11-43,43>>^ Descansou com seus pais e foi sepultado na Cidade de Davi, seu pai; e Roboão, seu filho, reinou em seu lugar.

'''

xref:011-1-reis/011-1-reis-010.adoc#v11-10-0[&#60; Capítulo Anterior] | <<v11-11-0,Topo>> | xref:011-1-reis/011-1-reis-012.adoc#v11-12-0[Próximo Capítulo &#62;]