include::./index.adoc[]

[[v11-14-0]]
=== 1 Reis, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v11-14-1]]

^<<v11-14-1,1>>^ Naquele tempo, adoeceu Abias, filho de Jeroboão.

[[v11-14-2]]

^<<v11-14-2,2>>^ Disse este a sua mulher: Dispõe-te, agora, e disfarça-te, para que não conheçam que és mulher de Jeroboão; e vai a Siló. Eis que lá está o profeta Aías, o qual a meu respeito disse que eu seria rei sobre este povo.

[[v11-14-3]]

^<<v11-14-3,3>>^ Leva contigo dez pães, bolos e uma botija de mel e vai ter com ele; ele te dirá o que há de suceder a este menino.

[[v11-14-4]]

^<<v11-14-4,4>>^ A mulher de Jeroboão assim o fez; levantou-se, foi a Siló e entrou na casa de Aías; Aías já não podia ver, porque os seus olhos já se tinham escurecido, por causa da sua velhice.

[[v11-14-5]]

^<<v11-14-5,5>>^ Porém o SENHOR disse a Aías: Eis que a mulher de Jeroboão vem consultar-te sobre seu filho, que está doente. Assim e assim lhe falarás, porque, ao entrar, fingirá ser outra.

[[v11-14-6]]

^<<v11-14-6,6>>^ Ouvindo Aías o ruído de seus pés, quando ela entrava pela porta, disse: Entra, mulher de Jeroboão; por que finges assim? Pois estou encarregado de te dizer duras novas.

[[v11-14-7]]

^<<v11-14-7,7>>^ Vai e dize a Jeroboão: Assim diz o SENHOR, Deus de Israel: Porquanto te levantei do meio do povo, e te fiz príncipe sobre o meu povo de Israel,

[[v11-14-8]]

^<<v11-14-8,8>>^ e tirei o reino da casa de Davi, e to entreguei, e tu não foste como Davi, meu servo, que guardou os meus mandamentos e andou após mim de todo o seu coração, para fazer somente o que parecia reto aos meus olhos;

[[v11-14-9]]

^<<v11-14-9,9>>^ antes, fizeste o mal, pior do que todos os que foram antes de ti, e fizeste outros deuses e imagens de fundição, para provocar-me à ira, e me viraste as costas;

[[v11-14-10]]

^<<v11-14-10,10>>^ portanto, eis que trarei o mal sobre a casa de Jeroboão, e eliminarei de Jeroboão todo e qualquer do sexo masculino, tanto o escravo como o livre, e lançarei fora os descendentes da casa de Jeroboão, como se lança fora o esterco, até que, de todo, ela se acabe.

[[v11-14-11]]

^<<v11-14-11,11>>^ Quem morrer a Jeroboão na cidade, os cães o comerão, e o que morrer no campo aberto, as aves do céu o comerão, porque o SENHOR o disse.

[[v11-14-12]]

^<<v11-14-12,12>>^ Tu, pois, dispõe-te e vai para tua casa; quando puseres os pés na cidade, o menino morrerá.

[[v11-14-13]]

^<<v11-14-13,13>>^ Todo o Israel o pranteará e o sepultará; porque de Jeroboão só este dará entrada em sepultura, porquanto se achou nele coisa boa para com o SENHOR, Deus de Israel, em casa de Jeroboão.

[[v11-14-14]]

^<<v11-14-14,14>>^ O SENHOR, porém, suscitará para si um rei sobre Israel, que eliminará, no seu dia, a casa de Jeroboão. Que digo eu? Há de ser já.

[[v11-14-15]]

^<<v11-14-15,15>>^ Também o SENHOR ferirá a Israel para que se agite como a cana se agita nas águas; arrancará a Israel desta boa terra que dera a seus pais e o espalhará para além do Eufrates, porquanto fez os seus postes-ídolos, provocando o SENHOR à ira.

[[v11-14-16]]

^<<v11-14-16,16>>^ Abandonará a Israel por causa dos pecados que Jeroboão cometeu e pelos que fez Israel cometer.

[[v11-14-17]]

^<<v11-14-17,17>>^ Então, a mulher de Jeroboão se levantou, foi e chegou a Tirza; chegando ela ao limiar da casa, morreu o menino.

[[v11-14-18]]

^<<v11-14-18,18>>^ Sepultaram-no, e todo o Israel o pranteou, segundo a palavra do SENHOR, por intermédio do profeta Aías, seu servo.

[[v11-14-19]]

^<<v11-14-19,19>>^ Quanto aos mais atos de Jeroboão, como guerreou e como reinou, eis que estão escritos no Livro da História dos Reis de Israel.

[[v11-14-20]]

^<<v11-14-20,20>>^ Foi de vinte e dois anos o tempo que reinou Jeroboão; e descansou com seus pais; e Nadabe, seu filho, reinou em seu lugar.

[[v11-14-21]]

^<<v11-14-21,21>>^ Roboão, filho de Salomão, reinou em Judá; de quarenta e um anos de idade era Roboão quando começou a reinar e reinou dezessete anos em Jerusalém, na cidade que o SENHOR escolhera de todas as tribos de Israel, para estabelecer ali o seu nome. Naamá era o nome de sua mãe, amonita.

[[v11-14-22]]

^<<v11-14-22,22>>^ Fez Judá o que era mau perante o SENHOR; e, com os pecados que cometeu, o provocou a zelo, mais do que fizeram os seus pais.

[[v11-14-23]]

^<<v11-14-23,23>>^ Porque também os de Judá edificaram altos, estátuas, colunas e postes-ídolos no alto de todos os elevados outeiros e debaixo de todas as árvores verdes.

[[v11-14-24]]

^<<v11-14-24,24>>^ Havia também na terra prostitutos cultuais; fizeram segundo todas as coisas abomináveis das nações que o SENHOR expulsara de diante dos filhos de Israel.

[[v11-14-25]]

^<<v11-14-25,25>>^ No quinto ano do rei Roboão, Sisaque, rei do Egito, subiu contra Jerusalém

[[v11-14-26]]

^<<v11-14-26,26>>^ e tomou os tesouros da Casa do SENHOR e os tesouros da casa do rei; tomou tudo. Também levou todos os escudos de ouro que Salomão tinha feito.

[[v11-14-27]]

^<<v11-14-27,27>>^ Em lugar destes, fez o rei Roboão escudos de bronze e os entregou nas mãos dos capitães da guarda, que guardavam a porta da casa do rei.

[[v11-14-28]]

^<<v11-14-28,28>>^ Toda vez que o rei entrava na Casa do SENHOR, os da guarda usavam os escudos e tornavam a trazê-los para a câmara da guarda.

[[v11-14-29]]

^<<v11-14-29,29>>^ Quanto aos mais dos atos de Roboão e a tudo quanto fez, porventura, não estão escritos no Livro da História dos Reis de Judá?

[[v11-14-30]]

^<<v11-14-30,30>>^ Houve guerra entre Roboão e Jeroboão todos os seus dias.

[[v11-14-31]]

^<<v11-14-31,31>>^ Roboão descansou com seus pais e com eles foi sepultado na Cidade de Davi. Naamá era o nome de sua mãe, amonita; e Abias, filho de Roboão, reinou em seu lugar.

'''

xref:011-1-reis/011-1-reis-013.adoc#v11-13-0[&#60; Capítulo Anterior] | <<v11-14-0,Topo>> | xref:011-1-reis/011-1-reis-015.adoc#v11-15-0[Próximo Capítulo &#62;]