include::./index.adoc[]

[[v11-13-0]]
=== 1 Reis, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v11-13-1]]

^<<v11-13-1,1>>^ Eis que, por ordem do SENHOR, veio de Judá a Betel um homem de Deus; e Jeroboão estava junto ao altar, para queimar incenso.

[[v11-13-2]]

^<<v11-13-2,2>>^ Clamou o profeta contra o altar, por ordem do SENHOR, e disse: Altar, altar! Assim diz o SENHOR: Eis que um filho nascerá à casa de Davi, cujo nome será Josias, o qual sacrificará sobre ti os sacerdotes dos altos que queimam sobre ti incenso, e ossos humanos se queimarão sobre ti.

[[v11-13-3]]

^<<v11-13-3,3>>^ Deu, naquele mesmo dia, um sinal, dizendo: Este é o sinal de que o SENHOR falou: Eis que o altar se fenderá, e se derramará a cinza que há sobre ele.

[[v11-13-4]]

^<<v11-13-4,4>>^ Tendo o rei ouvido as palavras do homem de Deus, que clamara contra o altar de Betel, Jeroboão estendeu a mão de sobre o altar, dizendo: Prendei-o! Mas a mão que estendera contra o homem de Deus secou, e não a podia recolher.

[[v11-13-5]]

^<<v11-13-5,5>>^ O altar se fendeu, e a cinza se derramou do altar, segundo o sinal que o homem de Deus apontara por ordem do SENHOR.

[[v11-13-6]]

^<<v11-13-6,6>>^ Então, disse o rei ao homem de Deus: Implora o favor do SENHOR, teu Deus, e ora por mim, para que eu possa recolher a mão. Então, o homem de Deus implorou o favor do SENHOR, e a mão do rei se lhe recolheu e ficou como dantes.

[[v11-13-7]]

^<<v11-13-7,7>>^ Disse o rei ao homem de Deus: Vem comigo a casa e fortalece-te; e eu te recompensarei.

[[v11-13-8]]

^<<v11-13-8,8>>^ Porém o homem de Deus disse ao rei: Ainda que me desses metade da tua casa, não iria contigo, nem comeria pão, nem beberia água neste lugar.

[[v11-13-9]]

^<<v11-13-9,9>>^ Porque assim me ordenou o SENHOR pela sua palavra, dizendo: Não comerás pão, nem beberás água; e não voltarás pelo caminho por onde foste.

[[v11-13-10]]

^<<v11-13-10,10>>^ E se foi por outro caminho; e não voltou pelo caminho por onde viera a Betel.

[[v11-13-11]]

^<<v11-13-11,11>>^ Morava em Betel um profeta velho; vieram seus filhos e lhe contaram tudo o que o homem de Deus fizera aquele dia em Betel; as palavras que dissera ao rei, contaram-nas a seu pai.

[[v11-13-12]]

^<<v11-13-12,12>>^ Perguntou-lhes o pai: Por que caminho se foi? Mostraram seus filhos o caminho por onde fora o homem de Deus que viera de Judá.

[[v11-13-13]]

^<<v11-13-13,13>>^ Então, disse a seus filhos: Albardai-me um jumento. Albardaram-lhe o jumento, e ele montou.

[[v11-13-14]]

^<<v11-13-14,14>>^ E foi após o homem de Deus e, achando-o sentado debaixo de um carvalho, lhe disse: És tu o homem de Deus que vieste de Judá? Ele respondeu: Eu mesmo.

[[v11-13-15]]

^<<v11-13-15,15>>^ Então, lhe disse: Vem comigo a casa e come pão.

[[v11-13-16]]

^<<v11-13-16,16>>^ Porém ele disse: Não posso voltar contigo, nem entrarei contigo; não comerei pão, nem beberei água contigo neste lugar.

[[v11-13-17]]

^<<v11-13-17,17>>^ Porque me foi dito pela palavra do SENHOR: Ali, não comerás pão, nem beberás água, nem voltarás pelo caminho por que foste.

[[v11-13-18]]

^<<v11-13-18,18>>^ Tornou-lhe ele: Também eu sou profeta como tu, e um anjo me falou por ordem do SENHOR, dizendo: Faze-o voltar contigo a tua casa, para que coma pão e beba água. (Porém mentiu-lhe.)

[[v11-13-19]]

^<<v11-13-19,19>>^ Então, voltou ele, e comeu pão em sua casa, e bebeu água.

[[v11-13-20]]

^<<v11-13-20,20>>^ Estando eles à mesa, veio a palavra do SENHOR ao profeta que o tinha feito voltar;

[[v11-13-21]]

^<<v11-13-21,21>>^ e clamou ao homem de Deus, que viera de Judá, dizendo: Assim diz o SENHOR: Porquanto foste rebelde à palavra do SENHOR e não guardaste o mandamento que o SENHOR, teu Deus, te mandara,

[[v11-13-22]]

^<<v11-13-22,22>>^ antes, voltaste, e comeste pão, e bebeste água no lugar de que te dissera: Não comerás pão, nem beberás água, o teu cadáver não entrará no sepulcro de teus pais.

[[v11-13-23]]

^<<v11-13-23,23>>^ Depois de o profeta a quem fizera voltar haver comido pão e bebido água, albardou para ele o jumento.

[[v11-13-24]]

^<<v11-13-24,24>>^ Foi-se, pois, e um leão o encontrou no caminho e o matou; o seu cadáver estava atirado no caminho, e o jumento e o leão, parados junto ao cadáver.

[[v11-13-25]]

^<<v11-13-25,25>>^ Eis que os homens passaram e viram o corpo lançado no caminho, como também o leão parado junto ao corpo; e vieram e o disseram na cidade onde o profeta velho habitava.

[[v11-13-26]]

^<<v11-13-26,26>>^ Ouvindo-o o profeta que o fizera voltar do caminho, disse: É o homem de Deus, que foi rebelde à palavra do SENHOR; por isso, o SENHOR o entregou ao leão, que o despedaçou e matou, segundo a palavra que o SENHOR lhe tinha dito.

[[v11-13-27]]

^<<v11-13-27,27>>^ Então, disse a seus filhos: Albardai-me o jumento. Eles o albardaram.

[[v11-13-28]]

^<<v11-13-28,28>>^ Ele se foi e achou o cadáver atirado no caminho e o jumento e o leão, parados junto ao cadáver; o leão não tinha devorado o corpo, nem despedaçado o jumento.

[[v11-13-29]]

^<<v11-13-29,29>>^ Então, o profeta levantou o cadáver do homem de Deus, e o pôs sobre o jumento, e o tornou a levar; assim, veio o profeta velho à cidade, para o chorar e enterrar.

[[v11-13-30]]

^<<v11-13-30,30>>^ Depositou o cadáver no seu próprio sepulcro; e o prantearam, dizendo: Ah! Irmão meu!

[[v11-13-31]]

^<<v11-13-31,31>>^ Depois de o haver sepultado, disse a seus filhos: Quando eu morrer, enterrai-me no sepulcro em que o homem de Deus está sepultado; ponde os meus ossos junto aos ossos dele.

[[v11-13-32]]

^<<v11-13-32,32>>^ Porque certamente se cumprirá o que por ordem do SENHOR clamou contra o altar que está em Betel e contra todas as casas dos altos que estão nas cidades de Samaria.

[[v11-13-33]]

^<<v11-13-33,33>>^ Depois destas coisas, Jeroboão ainda não deixou o seu mau caminho; antes, de entre o povo tornou a constituir sacerdotes para lugares altos; a quem queria, consagrava para sacerdote dos lugares altos.

[[v11-13-34]]

^<<v11-13-34,34>>^ Isso se tornou em pecado à casa de Jeroboão, para destruí-la e extingui-la da terra.

'''

xref:011-1-reis/011-1-reis-012.adoc#v11-12-0[&#60; Capítulo Anterior] | <<v11-13-0,Topo>> | xref:011-1-reis/011-1-reis-014.adoc#v11-14-0[Próximo Capítulo &#62;]