include::./index.adoc[]

[[v11-6-0]]
=== 1 Reis, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v11-6-1]]

^<<v11-6-1,1>>^ No ano quatrocentos e oitenta, depois de saírem os filhos de Israel do Egito, Salomão, no ano quarto do seu reinado sobre Israel, no mês de zive (este é o mês segundo), começou a edificar a Casa do SENHOR.

[[v11-6-2]]

^<<v11-6-2,2>>^ A casa que o rei Salomão edificou ao SENHOR era de sessenta côvados de comprimento, vinte de largura e trinta de altura.

[[v11-6-3]]

^<<v11-6-3,3>>^ O pórtico diante do templo da casa media vinte côvados no sentido da largura do Lugar Santo, contra dez de fundo.

[[v11-6-4]]

^<<v11-6-4,4>>^ Para a casa, fez janelas de fasquias fixas superpostas.

[[v11-6-5]]

^<<v11-6-5,5>>^ Contra a parede da casa, tanto do santuário como do Santo dos Santos, edificou andares ao redor e fez câmaras laterais ao redor.

[[v11-6-6]]

^<<v11-6-6,6>>^ O andar de baixo tinha cinco côvados de largura, o do meio, seis, e o terceiro, sete; porque, pela parte de fora da casa em redor, fizera reentrâncias para que as vigas não fossem introduzidas nas paredes.

[[v11-6-7]]

^<<v11-6-7,7>>^ Edificava-se a casa com pedras já preparadas nas pedreiras, de maneira que nem martelo, nem machado, nem instrumento algum de ferro se ouviu na casa quando a edificavam.

[[v11-6-8]]

^<<v11-6-8,8>>^ A porta da câmara do meio do andar térreo estava ao lado sul da casa, e por caracóis se subia ao segundo e, deste, ao terceiro.

[[v11-6-9]]

^<<v11-6-9,9>>^ Assim, edificou a casa e a rematou, cobrindo-a com um tabuado de cedro.

[[v11-6-10]]

^<<v11-6-10,10>>^ Os andares que edificou contra a casa toda eram de cinco côvados de altura, e os ligou com a casa com madeira de cedro.

[[v11-6-11]]

^<<v11-6-11,11>>^ Então, veio a palavra do SENHOR a Salomão, dizendo:

[[v11-6-12]]

^<<v11-6-12,12>>^ Quanto a esta casa que tu edificas, se andares nos meus estatutos, e executares os meus juízos, e guardares todos os meus mandamentos, andando neles, cumprirei para contigo a minha palavra, a qual falei a Davi, teu pai.

[[v11-6-13]]

^<<v11-6-13,13>>^ E habitarei no meio dos filhos de Israel e não desampararei o meu povo.

[[v11-6-14]]

^<<v11-6-14,14>>^ Assim, edificou Salomão a casa e a rematou.

[[v11-6-15]]

^<<v11-6-15,15>>^ Também revestiu as paredes da casa por dentro com tábuas de cedro; desde o soalho da casa até ao teto, cobriu com madeira por dentro; e cobriu o piso da casa com tábuas de cipreste.

[[v11-6-16]]

^<<v11-6-16,16>>^ Da mesma sorte, revestiu também os vinte côvados dos fundos da casa com tábuas de cedro, desde o soalho até ao teto; e esse interior ele constituiu em santuário, a saber, o Santo dos Santos.

[[v11-6-17]]

^<<v11-6-17,17>>^ Era, pois, o Santo Lugar do templo de quarenta côvados.

[[v11-6-18]]

^<<v11-6-18,18>>^ O cedro da casa por dentro era lavrado de colocíntidas e flores abertas; tudo era cedro, pedra nenhuma se via.

[[v11-6-19]]

^<<v11-6-19,19>>^ No mais interior da casa, preparou o Santo dos Santos para nele colocar a arca da Aliança do SENHOR.

[[v11-6-20]]

^<<v11-6-20,20>>^ Era o Santo dos Santos de vinte côvados de comprimento, vinte de largura e vinte de altura; cobriu-o de ouro puro. Cobriu também de ouro o altar de cedro.

[[v11-6-21]]

^<<v11-6-21,21>>^ Por dentro, Salomão revestiu a casa de ouro puro; e fez passar cadeias de ouro por dentro do Santo dos Santos, que também cobrira de ouro.

[[v11-6-22]]

^<<v11-6-22,22>>^ Assim, cobriu de ouro toda a casa, inteiramente, e também todo o altar que estava diante do Santo dos Santos.

[[v11-6-23]]

^<<v11-6-23,23>>^ No Santo dos Santos, fez dois querubins de madeira de oliveira, cada um da altura de dez côvados.

[[v11-6-24]]

^<<v11-6-24,24>>^ Cada asa de um querubim era de cinco côvados; dez côvados havia, pois, de uma a outra extremidade de suas asas.

[[v11-6-25]]

^<<v11-6-25,25>>^ Assim, também era de dez côvados o outro querubim; ambos mediam o mesmo e eram da mesma forma.

[[v11-6-26]]

^<<v11-6-26,26>>^ A altura de um querubim era de dez côvados; e assim a do outro.

[[v11-6-27]]

^<<v11-6-27,27>>^ Pôs os querubins no mais interior da casa; os querubins estavam de asas estendidas, de maneira que a asa de um tocava numa parede, e a asa do outro tocava na outra parede; e as suas asas no meio da casa tocavam uma na outra.

[[v11-6-28]]

^<<v11-6-28,28>>^ E cobriu de ouro os querubins.

[[v11-6-29]]

^<<v11-6-29,29>>^ Nas paredes todas, tanto no mais interior da casa como no seu exterior, lavrou, ao redor, entalhes de querubins, palmeiras e flores abertas.

[[v11-6-30]]

^<<v11-6-30,30>>^ Também cobriu de ouro o soalho, tanto no mais interior da casa como no seu exterior.

[[v11-6-31]]

^<<v11-6-31,31>>^ Para entrada do Santo dos Santos, fez folhas de madeira de oliveira; a verga com as ombreiras formavam uma porta pentagonal.

[[v11-6-32]]

^<<v11-6-32,32>>^ Assim, fabricou de madeira de oliveira duas folhas e lavrou nelas entalhes de querubins, de palmeiras e de flores abertas; a estas, como as palmeiras e os querubins, cobriu de ouro.

[[v11-6-33]]

^<<v11-6-33,33>>^ Fez, para entrada do Santo Lugar, ombreiras de madeira de oliveira; entrada quadrilateral,

[[v11-6-34]]

^<<v11-6-34,34>>^ cujas duas folhas eram de madeira de cipreste; e as duas tábuas de cada folha eram dobradiças.

[[v11-6-35]]

^<<v11-6-35,35>>^ E as lavrou de querubins, de palmeiras e de flores abertas e as cobriu de ouro acomodado ao lavor.

[[v11-6-36]]

^<<v11-6-36,36>>^ Também edificou o átrio interior de três ordens de pedras cortadas e de uma ordem de vigas de cedro.

[[v11-6-37]]

^<<v11-6-37,37>>^ No ano quarto, se pôs o fundamento da Casa do SENHOR, no mês de zive.

[[v11-6-38]]

^<<v11-6-38,38>>^ E, no ano undécimo, no mês de bul, que é o oitavo, se acabou esta casa com todas as suas dependências, tal como devia ser. Levou Salomão sete anos para edificá-la.

'''

xref:011-1-reis/011-1-reis-005.adoc#v11-5-0[&#60; Capítulo Anterior] | <<v11-6-0,Topo>> | xref:011-1-reis/011-1-reis-007.adoc#v11-7-0[Próximo Capítulo &#62;]