include::./index.adoc[]

[[v11-15-0]]
=== 1 Reis, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v11-15-1]]

^<<v11-15-1,1>>^ No décimo oitavo ano do rei Jeroboão, filho de Nebate, Abias começou a reinar sobre Judá.

[[v11-15-2]]

^<<v11-15-2,2>>^ Três anos reinou em Jerusalém. Era o nome de sua mãe Maaca, filha de Absalão.

[[v11-15-3]]

^<<v11-15-3,3>>^ Andou em todos os pecados que seu pai havia cometido antes dele; e seu coração não foi perfeito para com o SENHOR, seu Deus, como o coração de Davi, seu pai.

[[v11-15-4]]

^<<v11-15-4,4>>^ Mas, por amor de Davi, o SENHOR, seu Deus, lhe deu uma lâmpada em Jerusalém, levantando a seu filho depois dele e dando estabilidade a Jerusalém.

[[v11-15-5]]

^<<v11-15-5,5>>^ Porquanto Davi fez o que era reto perante o SENHOR e não se desviou de tudo quanto lhe ordenara, em todos os dias da sua vida, senão no caso de Urias, o heteu.

[[v11-15-6]]

^<<v11-15-6,6>>^ Houve guerra entre Roboão e Jeroboão todos os dias da sua vida.

[[v11-15-7]]

^<<v11-15-7,7>>^ Quanto aos mais atos de Abias e a tudo quanto fez, porventura, não estão escritos no Livro da História dos Reis de Judá? Também houve guerra entre Abias e Jeroboão.

[[v11-15-8]]

^<<v11-15-8,8>>^ Abias descansou com seus pais, e o sepultaram na Cidade de Davi; e Asa, seu filho, reinou em seu lugar.

[[v11-15-9]]

^<<v11-15-9,9>>^ No vigésimo ano de Jeroboão, rei de Israel, começou Asa a reinar sobre Judá.

[[v11-15-10]]

^<<v11-15-10,10>>^ Quarenta e um anos reinou em Jerusalém. Era o nome de sua mãe Maaca, filha de Absalão.

[[v11-15-11]]

^<<v11-15-11,11>>^ Asa fez o que era reto perante o SENHOR, como Davi, seu pai.

[[v11-15-12]]

^<<v11-15-12,12>>^ Porque tirou da terra os prostitutos cultuais e removeu todos os ídolos que seus pais fizeram;

[[v11-15-13]]

^<<v11-15-13,13>>^ e até a Maaca, sua mãe, depôs da dignidade de rainha-mãe, porquanto ela havia feito ao poste-ídolo uma abominável imagem; pois Asa destruiu essa imagem e a queimou no vale de Cedrom;

[[v11-15-14]]

^<<v11-15-14,14>>^ os altos, porém, não foram tirados; todavia, o coração de Asa foi, todos os seus dias, totalmente do SENHOR.

[[v11-15-15]]

^<<v11-15-15,15>>^ Trouxe à Casa do SENHOR as coisas consagradas por seu pai e as coisas que ele mesmo consagrara: prata, ouro e objetos de utilidade.

[[v11-15-16]]

^<<v11-15-16,16>>^ Houve guerra entre Asa e Baasa, rei de Israel, todos os seus dias.

[[v11-15-17]]

^<<v11-15-17,17>>^ Porque Baasa, rei de Israel, subiu contra Judá e edificou a Ramá, para que a ninguém fosse permitido sair de junto de Asa, rei de Judá, nem chegar a ele.

[[v11-15-18]]

^<<v11-15-18,18>>^ Então, Asa tomou toda a prata e ouro restantes nos tesouros da Casa do SENHOR e os tesouros da casa do rei e os entregou nas mãos de seus servos; e o rei Asa os enviou a Ben-Hadade, filho de Tabrimom, filho de Heziom, rei da Síria, e que habitava em Damasco, dizendo:

[[v11-15-19]]

^<<v11-15-19,19>>^ Haja aliança entre mim e ti, como houve entre meu pai e teu pai. Eis que te mando um presente, prata e ouro; vai e anula a tua aliança com Baasa, rei de Israel, para que se retire de mim.

[[v11-15-20]]

^<<v11-15-20,20>>^ Ben-Hadade deu ouvidos ao rei Asa e enviou os capitães dos seus exércitos contra as cidades de Israel; e feriu a Ijom, a Dã, a Abel-Bete-Maaca e todo o distrito de Quinerete, com toda a terra de Naftali.

[[v11-15-21]]

^<<v11-15-21,21>>^ Ouvindo isso, Baasa deixou de edificar a Ramá e ficou em Tirza.

[[v11-15-22]]

^<<v11-15-22,22>>^ Então, o rei Asa fez apregoar por toda a região de Judá que todos, sem exceção, trouxessem as pedras de Ramá e a sua madeira, com que Baasa a edificara; com elas edificou o rei Asa a Geba de Benjamim e a Mispa.

[[v11-15-23]]

^<<v11-15-23,23>>^ Quanto aos mais atos de Asa, e a todo o seu poder, e a tudo quanto fez, e às cidades que edificou, porventura, não estão escritos no Livro da História dos Reis de Judá? Porém, no tempo da sua velhice, padeceu dos pés.

[[v11-15-24]]

^<<v11-15-24,24>>^ Descansou Asa com seus pais e com eles foi sepultado na Cidade de Davi, seu pai; e Josafá, seu filho, reinou em seu lugar.

[[v11-15-25]]

^<<v11-15-25,25>>^ Nadabe, filho de Jeroboão, começou a reinar sobre Israel no ano segundo de Asa, rei de Judá; e reinou sobre Israel dois anos.

[[v11-15-26]]

^<<v11-15-26,26>>^ Fez o que era mau perante o SENHOR e andou nos caminhos de seu pai e no pecado com que seu pai fizera pecar a Israel.

[[v11-15-27]]

^<<v11-15-27,27>>^ Conspirou contra ele Baasa, filho de Aías, da casa de Issacar, e o feriu em Gibetom, que era dos filisteus, quando Nadabe e todo o Israel cercavam Gibetom.

[[v11-15-28]]

^<<v11-15-28,28>>^ Baasa, no ano terceiro de Asa, rei de Judá, matou a Nadabe e passou a reinar em seu lugar.

[[v11-15-29]]

^<<v11-15-29,29>>^ Logo que começou a reinar, matou toda a descendência de Jeroboão; não lhe deixou ninguém com vida, a todos exterminou, segundo a palavra do SENHOR, por intermédio do seu servo Aías, o silonita,

[[v11-15-30]]

^<<v11-15-30,30>>^ por causa dos pecados que Jeroboão cometera e pelos que fizera Israel cometer, por causa da provocação com que irritara ao SENHOR, Deus de Israel.

[[v11-15-31]]

^<<v11-15-31,31>>^ Quanto aos mais atos de Nadabe e a tudo quanto fez, porventura, não estão escritos no Livro da História dos Reis de Israel?

[[v11-15-32]]

^<<v11-15-32,32>>^ Houve guerra entre Asa e Baasa, rei de Israel, todos os seus dias.

[[v11-15-33]]

^<<v11-15-33,33>>^ No ano terceiro de Asa, rei de Judá, Baasa, filho de Aías, começou a reinar sobre todo o Israel, em Tirza, e reinou vinte e quatro anos.

[[v11-15-34]]

^<<v11-15-34,34>>^ Fez o que era mau perante o SENHOR e andou no caminho de Jeroboão e no seu pecado, o qual fizera Israel cometer.

'''

xref:011-1-reis/011-1-reis-014.adoc#v11-14-0[&#60; Capítulo Anterior] | <<v11-15-0,Topo>> | xref:011-1-reis/011-1-reis-016.adoc#v11-16-0[Próximo Capítulo &#62;]