include::./index.adoc[]

[[v11-21-0]]
=== 1 Reis, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v11-21-1]]

^<<v11-21-1,1>>^ Sucedeu, depois disto, o seguinte: Nabote, o jezreelita, possuía uma vinha ao lado do palácio que Acabe, rei de Samaria, tinha em Jezreel.

[[v11-21-2]]

^<<v11-21-2,2>>^ Disse Acabe a Nabote: Dá-me a tua vinha, para que me sirva de horta, pois está perto, ao lado da minha casa. Dar-te-ei por ela outra, melhor; ou, se for do teu agrado, dar-te-ei em dinheiro o que ela vale.

[[v11-21-3]]

^<<v11-21-3,3>>^ Porém Nabote disse a Acabe: Guarde-me o SENHOR de que eu dê a herança de meus pais.

[[v11-21-4]]

^<<v11-21-4,4>>^ Então, Acabe veio desgostoso e indignado para sua casa, por causa da palavra que Nabote, o jezreelita, lhe falara, quando disse: Não te darei a herança de meus pais. E deitou-se na sua cama, voltou o rosto e não comeu pão.

[[v11-21-5]]

^<<v11-21-5,5>>^ Porém, vindo Jezabel, sua mulher, ter com ele, lhe disse: Que é isso que tens assim desgostoso o teu espírito e não comes pão?

[[v11-21-6]]

^<<v11-21-6,6>>^ Ele lhe respondeu: Porque falei a Nabote, o jezreelita, e lhe disse: Dá-me a tua vinha por dinheiro; ou, se te apraz, dar-te-ei outra em seu lugar. Porém ele disse: Não te darei a minha vinha.

[[v11-21-7]]

^<<v11-21-7,7>>^ Então, Jezabel, sua mulher, lhe disse: Governas tu, com efeito, sobre Israel? Levanta-te, come, e alegre-se o teu coração; eu te darei a vinha de Nabote, o jezreelita.

[[v11-21-8]]

^<<v11-21-8,8>>^ Então, escreveu cartas em nome de Acabe, selou-as com o sinete dele e as enviou aos anciãos e aos nobres que havia na sua cidade e habitavam com Nabote.

[[v11-21-9]]

^<<v11-21-9,9>>^ E escreveu nas cartas, dizendo: Apregoai um jejum e trazei Nabote para a frente do povo.

[[v11-21-10]]

^<<v11-21-10,10>>^ Fazei sentar defronte dele dois homens malignos, que testemunhem contra ele, dizendo: Blasfemaste contra Deus e contra o rei. Depois, levai-o para fora e apedrejai-o, para que morra.

[[v11-21-11]]

^<<v11-21-11,11>>^ Os homens da sua cidade, os anciãos e os nobres que nela habitavam fizeram como Jezabel lhes ordenara, segundo estava escrito nas cartas que lhes havia mandado.

[[v11-21-12]]

^<<v11-21-12,12>>^ Apregoaram um jejum e trouxeram Nabote para a frente do povo.

[[v11-21-13]]

^<<v11-21-13,13>>^ Então, vieram dois homens malignos, sentaram-se defronte dele e testemunharam contra ele, contra Nabote, perante o povo, dizendo: Nabote blasfemou contra Deus e contra o rei. E o levaram para fora da cidade e o apedrejaram, e morreu.

[[v11-21-14]]

^<<v11-21-14,14>>^ Então, mandaram dizer a Jezabel: Nabote foi apedrejado e morreu.

[[v11-21-15]]

^<<v11-21-15,15>>^ Tendo Jezabel ouvido que Nabote fora apedrejado e morrera, disse a Acabe: Levanta-te e toma posse da vinha que Nabote, o jezreelita, recusou dar-te por dinheiro; pois Nabote já não vive, mas é morto.

[[v11-21-16]]

^<<v11-21-16,16>>^ Tendo Acabe ouvido que Nabote era morto, levantou-se para descer para a vinha de Nabote, o jezreelita, para tomar posse dela.

[[v11-21-17]]

^<<v11-21-17,17>>^ Então, veio a palavra do SENHOR a Elias, o tesbita, dizendo:

[[v11-21-18]]

^<<v11-21-18,18>>^ Dispõe-te, desce para encontrar-te com Acabe, rei de Israel, que habita em Samaria; eis que está na vinha de Nabote, aonde desceu para tomar posse dela.

[[v11-21-19]]

^<<v11-21-19,19>>^ Falar-lhe-ás, dizendo: Assim diz o SENHOR: Mataste e, ainda por cima, tomaste a herança? Dir-lhe-ás mais: Assim diz o SENHOR: No lugar em que os cães lamberam o sangue de Nabote, cães lamberão o teu sangue, o teu mesmo.

[[v11-21-20]]

^<<v11-21-20,20>>^ Perguntou Acabe a Elias: Já me achaste, inimigo meu? Respondeu ele: Achei-te, porquanto já te vendeste para fazeres o que é mau perante o SENHOR.

[[v11-21-21]]

^<<v11-21-21,21>>^ Eis que trarei o mal sobre ti, arrancarei a tua posteridade e exterminarei de Acabe a todo do sexo masculino, quer escravo quer livre, em Israel.

[[v11-21-22]]

^<<v11-21-22,22>>^ Farei a tua casa como a casa de Jeroboão, filho de Nebate, e como a casa de Baasa, filho de Aías, por causa da provocação com que me irritaste e fizeste pecar a Israel.

[[v11-21-23]]

^<<v11-21-23,23>>^ Também de Jezabel falou o SENHOR: Os cães devorarão Jezabel dentro dos muros de Jezreel.

[[v11-21-24]]

^<<v11-21-24,24>>^ Quem morrer de Acabe na cidade, os cães o comerão, e quem morrer no campo, as aves do céu o comerão.

[[v11-21-25]]

^<<v11-21-25,25>>^ Ninguém houve, pois, como Acabe, que se vendeu para fazer o que era mau perante o SENHOR, porque Jezabel, sua mulher, o instigava;

[[v11-21-26]]

^<<v11-21-26,26>>^ que fez grandes abominações, seguindo os ídolos, segundo tudo o que fizeram os amorreus, os quais o SENHOR lançou de diante dos filhos de Israel.

[[v11-21-27]]

^<<v11-21-27,27>>^ Tendo Acabe ouvido estas palavras, rasgou as suas vestes, cobriu de pano de saco o seu corpo e jejuou; dormia em panos de saco e andava cabisbaixo.

[[v11-21-28]]

^<<v11-21-28,28>>^ Então, veio a palavra do SENHOR a Elias, o tesbita, dizendo:

[[v11-21-29]]

^<<v11-21-29,29>>^ Não viste que Acabe se humilha perante mim? Portanto, visto que se humilha perante mim, não trarei este mal nos seus dias, mas nos dias de seu filho o trarei sobre a sua casa.

'''

xref:011-1-reis/011-1-reis-020.adoc#v11-20-0[&#60; Capítulo Anterior] | <<v11-21-0,Topo>> | xref:011-1-reis/011-1-reis-022.adoc#v11-22-0[Próximo Capítulo &#62;]