include::./index.adoc[]

[[v42-3-0]]
=== Lucas, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-3-1]]

^<<v42-3-1,1>>^ No décimo quinto ano do reinado de Tibério César, sendo Pôncio Pilatos governador da Judeia, Herodes, tetrarca da Galileia, seu irmão Filipe, tetrarca da região da Itureia e Traconites, e Lisânias, tetrarca de Abilene,

[[v42-3-2]]

^<<v42-3-2,2>>^ sendo sumos sacerdotes Anás e Caifás, veio a palavra de Deus a João, filho de Zacarias, no deserto.

[[v42-3-3]]

^<<v42-3-3,3>>^ Ele percorreu toda a circunvizinhança do Jordão, pregando batismo de arrependimento para remissão de pecados,

[[v42-3-4]]

^<<v42-3-4,4>>^ conforme está escrito no livro das palavras do profeta Isaías: Voz do que clama no deserto: Preparai o caminho do Senhor, endireitai as suas veredas.

[[v42-3-5]]

^<<v42-3-5,5>>^ Todo vale será aterrado, e nivelados todos os montes e outeiros; os caminhos tortuosos serão retificados, e os escabrosos, aplanados;

[[v42-3-6]]

^<<v42-3-6,6>>^ e toda carne verá a salvação de Deus.

[[v42-3-7]]

^<<v42-3-7,7>>^ Dizia ele, pois, às multidões que saíam para serem batizadas: Raça de víboras, quem vos induziu a fugir da ira vindoura?

[[v42-3-8]]

^<<v42-3-8,8>>^ Produzi, pois, frutos dignos de arrependimento e não comeceis a dizer entre vós mesmos: Temos por pai a Abraão; porque eu vos afirmo que destas pedras Deus pode suscitar filhos a Abraão.

[[v42-3-9]]

^<<v42-3-9,9>>^ E também já está posto o machado à raiz das árvores; toda árvore, pois, que não produz bom fruto é cortada e lançada ao fogo.

[[v42-3-10]]

^<<v42-3-10,10>>^ Então, as multidões o interrogavam, dizendo: Que havemos, pois, de fazer?

[[v42-3-11]]

^<<v42-3-11,11>>^ Respondeu-lhes: Quem tiver duas túnicas, reparta com quem não tem; e quem tiver comida, faça o mesmo.

[[v42-3-12]]

^<<v42-3-12,12>>^ Foram também publicanos para serem batizados e perguntaram-lhe: Mestre, que havemos de fazer?

[[v42-3-13]]

^<<v42-3-13,13>>^ Respondeu-lhes: Não cobreis mais do que o estipulado.

[[v42-3-14]]

^<<v42-3-14,14>>^ Também soldados lhe perguntaram: E nós, que faremos? E ele lhes disse: A ninguém maltrateis, não deis denúncia falsa e contentai-vos com o vosso soldo.

[[v42-3-15]]

^<<v42-3-15,15>>^ Estando o povo na expectativa, e discorrendo todos no seu íntimo a respeito de João, se não seria ele, porventura, o próprio Cristo,

[[v42-3-16]]

^<<v42-3-16,16>>^ disse João a todos: Eu, na verdade, vos batizo com água, mas vem o que é mais poderoso do que eu, do qual não sou digno de desatar-lhe as correias das sandálias; ele vos batizará com o Espírito Santo e com fogo.

[[v42-3-17]]

^<<v42-3-17,17>>^ A sua pá, ele a tem na mão, para limpar completamente a sua eira e recolher o trigo no seu celeiro; porém queimará a palha em fogo inextinguível.

[[v42-3-18]]

^<<v42-3-18,18>>^ Assim, pois, com muitas outras exortações anunciava o evangelho ao povo;

[[v42-3-19]]

^<<v42-3-19,19>>^ mas Herodes, o tetrarca, sendo repreendido por ele, por causa de Herodias, mulher de seu irmão, e por todas as maldades que o mesmo Herodes havia feito,

[[v42-3-20]]

^<<v42-3-20,20>>^ acrescentou ainda sobre todas a de lançar João no cárcere.

[[v42-3-21]]

^<<v42-3-21,21>>^ E aconteceu que, ao ser todo o povo batizado, também o foi Jesus; e, estando ele a orar, o céu se abriu,

[[v42-3-22]]

^<<v42-3-22,22>>^ e o Espírito Santo desceu sobre ele em forma corpórea como pomba; e ouviu-se uma voz do céu: Tu és o meu Filho amado, em ti me comprazo.

[[v42-3-23]]

^<<v42-3-23,23>>^ Ora, tinha Jesus cerca de trinta anos ao começar o seu ministério. Era, como se cuidava, filho de José, filho de Eli;

[[v42-3-24]]

^<<v42-3-24,24>>^ Eli, filho de Matate, Matate, filho de Levi, Levi, filho de Melqui, este, filho de Janai, filho de José;

[[v42-3-25]]

^<<v42-3-25,25>>^ José, filho de Matatias, Matatias, filho de Amós, Amós, filho de Naum, este, filho de Esli, filho de Nagai;

[[v42-3-26]]

^<<v42-3-26,26>>^ Nagai, filho de Maate, Maate, filho de Matatias, Matatias, filho de Semei, este, filho de José, filho de Jodá;

[[v42-3-27]]

^<<v42-3-27,27>>^ Jodá, filho de Joanã, Joanã, filho de Resa, Resa, filho de Zorobabel, este, de Salatiel, filho de Neri;

[[v42-3-28]]

^<<v42-3-28,28>>^ Neri, filho de Melqui, Melqui, filho de Adi, Adi, filho de Cosã, este, de Elmadã, filho de Er;

[[v42-3-29]]

^<<v42-3-29,29>>^ Er, filho de Josué, Josué, filho de Eliézer, Eliézer, filho de Jorim, este, de Matate, filho de Levi;

[[v42-3-30]]

^<<v42-3-30,30>>^ Levi, filho de Simeão, Simeão, filho de Judá, Judá, filho de José, este, filho de Jonã, filho de Eliaquim;

[[v42-3-31]]

^<<v42-3-31,31>>^ Eliaquim, filho de Meleá, Meleá, filho de Mená, Mená, filho de Matatá, este, filho de Natã, filho de Davi;

[[v42-3-32]]

^<<v42-3-32,32>>^ Davi, filho de Jessé, Jessé, filho de Obede, Obede, filho de Boaz, este, filho de Salá, filho de Naassom;

[[v42-3-33]]

^<<v42-3-33,33>>^ Naassom, filho de Aminadabe, Aminadabe, filho de Admim, Admim, filho de Arni, Arni, filho de Esrom, este, filho de Perez, filho de Judá;

[[v42-3-34]]

^<<v42-3-34,34>>^ Judá, filho de Jacó, Jacó, filho de Isaque, Isaque, filho de Abraão, este, filho de Tera, filho de Naor;

[[v42-3-35]]

^<<v42-3-35,35>>^ Naor, filho de Serugue, Serugue, filho de Ragaú, Ragaú, filho de Faleque, este, filho de Éber, filho de Salá;

[[v42-3-36]]

^<<v42-3-36,36>>^ Salá, filho de Cainã, Cainã, filho de Arfaxade, Arfaxade, filho de Sem, este, filho de Noé, filho de Lameque;

[[v42-3-37]]

^<<v42-3-37,37>>^ Lameque, filho de Metusalém, Metusalém, filho de Enoque, Enoque, filho de Jarede, este, filho de Maalalel, filho de Cainã;

[[v42-3-38]]

^<<v42-3-38,38>>^ Cainã, filho de Enos, Enos, filho de Sete, e este, filho de Adão, filho de Deus.

'''

xref:042-lucas/042-lucas-002.adoc#v42-2-0[&#60; Capítulo Anterior] | <<v42-3-0,Topo>> | xref:042-lucas/042-lucas-004.adoc#v42-4-0[Próximo Capítulo &#62;]