include::./index.adoc[]

[[v42-21-0]]
=== Lucas, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-21-1]]

^<<v42-21-1,1>>^ Estando Jesus a observar, viu os ricos lançarem suas ofertas no gazofilácio.

[[v42-21-2]]

^<<v42-21-2,2>>^ Viu também certa viúva pobre lançar ali duas pequenas moedas;

[[v42-21-3]]

^<<v42-21-3,3>>^ e disse: Verdadeiramente, vos digo que esta viúva pobre deu mais do que todos.

[[v42-21-4]]

^<<v42-21-4,4>>^ Porque todos estes deram como oferta daquilo que lhes sobrava; esta, porém, da sua pobreza deu tudo o que possuía, todo o seu sustento.

[[v42-21-5]]

^<<v42-21-5,5>>^ Falavam alguns a respeito do templo, como estava ornado de belas pedras e de dádivas;

[[v42-21-6]]

^<<v42-21-6,6>>^ então, disse Jesus: Vedes estas coisas? Dias virão em que não ficará pedra sobre pedra que não seja derribada.

[[v42-21-7]]

^<<v42-21-7,7>>^ Perguntaram-lhe: Mestre, quando sucederá isto? E que sinal haverá de quando estas coisas estiverem para se cumprir?

[[v42-21-8]]

^<<v42-21-8,8>>^ Respondeu ele: Vede que não sejais enganados; porque muitos virão em meu nome, dizendo: Sou eu! E também: Chegou a hora! Não os sigais.

[[v42-21-9]]

^<<v42-21-9,9>>^ Quando ouvirdes falar de guerras e revoluções, não vos assusteis; pois é necessário que primeiro aconteçam estas coisas, mas o fim não será logo.

[[v42-21-10]]

^<<v42-21-10,10>>^ Então, lhes disse: Levantar-se-á nação contra nação, e reino, contra reino;

[[v42-21-11]]

^<<v42-21-11,11>>^ haverá grandes terremotos, epidemias e fome em vários lugares, coisas espantosas e também grandes sinais do céu.

[[v42-21-12]]

^<<v42-21-12,12>>^ Antes, porém, de todas estas coisas, lançarão mão de vós e vos perseguirão, entregando-vos às sinagogas e aos cárceres, levando-vos à presença de reis e governadores, por causa do meu nome;

[[v42-21-13]]

^<<v42-21-13,13>>^ e isto vos acontecerá para que deis testemunho.

[[v42-21-14]]

^<<v42-21-14,14>>^ Assentai, pois, em vosso coração de não vos preocupardes com o que haveis de responder;

[[v42-21-15]]

^<<v42-21-15,15>>^ porque eu vos darei boca e sabedoria a que não poderão resistir, nem contradizer todos quantos se vos opuserem.

[[v42-21-16]]

^<<v42-21-16,16>>^ E sereis entregues até por vossos pais, irmãos, parentes e amigos; e matarão alguns dentre vós.

[[v42-21-17]]

^<<v42-21-17,17>>^ De todos sereis odiados por causa do meu nome.

[[v42-21-18]]

^<<v42-21-18,18>>^ Contudo, não se perderá um só fio de cabelo da vossa cabeça.

[[v42-21-19]]

^<<v42-21-19,19>>^ É na vossa perseverança que ganhareis a vossa alma.

[[v42-21-20]]

^<<v42-21-20,20>>^ Quando, porém, virdes Jerusalém sitiada de exércitos, sabei que está próxima a sua devastação.

[[v42-21-21]]

^<<v42-21-21,21>>^ Então, os que estiverem na Judeia, fujam para os montes; os que se encontrarem dentro da cidade, retirem-se; e os que estiverem nos campos, não entrem nela.

[[v42-21-22]]

^<<v42-21-22,22>>^ Porque estes dias são de vingança, para se cumprir tudo o que está escrito.

[[v42-21-23]]

^<<v42-21-23,23>>^ Ai das que estiverem grávidas e das que amamentarem naqueles dias! Porque haverá grande aflição na terra e ira contra este povo.

[[v42-21-24]]

^<<v42-21-24,24>>^ Cairão a fio de espada e serão levados cativos para todas as nações; e, até que os tempos dos gentios se completem, Jerusalém será pisada por eles.

[[v42-21-25]]

^<<v42-21-25,25>>^ Haverá sinais no sol, na lua e nas estrelas; sobre a terra, angústia entre as nações em perplexidade por causa do bramido do mar e das ondas;

[[v42-21-26]]

^<<v42-21-26,26>>^ haverá homens que desmaiarão de terror e pela expectativa das coisas que sobrevirão ao mundo; pois os poderes dos céus serão abalados.

[[v42-21-27]]

^<<v42-21-27,27>>^ Então, se verá o Filho do Homem vindo numa nuvem, com poder e grande glória.

[[v42-21-28]]

^<<v42-21-28,28>>^ Ora, ao começarem estas coisas a suceder, exultai e erguei a vossa cabeça; porque a vossa redenção se aproxima.

[[v42-21-29]]

^<<v42-21-29,29>>^ Ainda lhes propôs uma parábola, dizendo: Vede a figueira e todas as árvores.

[[v42-21-30]]

^<<v42-21-30,30>>^ Quando começam a brotar, vendo-o, sabeis, por vós mesmos, que o verão está próximo.

[[v42-21-31]]

^<<v42-21-31,31>>^ Assim também, quando virdes acontecerem estas coisas, sabei que está próximo o reino de Deus.

[[v42-21-32]]

^<<v42-21-32,32>>^ Em verdade vos digo que não passará esta geração, sem que tudo isto aconteça.

[[v42-21-33]]

^<<v42-21-33,33>>^ Passará o céu e a terra, porém as minhas palavras não passarão.

[[v42-21-34]]

^<<v42-21-34,34>>^ Acautelai-vos por vós mesmos, para que nunca vos suceda que o vosso coração fique sobrecarregado com as consequências da orgia, da embriaguez e das preocupações deste mundo, e para que aquele dia não venha sobre vós repentinamente, como um laço.

[[v42-21-35]]

^<<v42-21-35,35>>^ Pois há de sobrevir a todos os que vivem sobre a face de toda a terra.

[[v42-21-36]]

^<<v42-21-36,36>>^ Vigiai, pois, a todo tempo, orando, para que possais escapar de todas estas coisas que têm de suceder e estar em pé na presença do Filho do Homem.

[[v42-21-37]]

^<<v42-21-37,37>>^ Jesus ensinava todos os dias no templo, mas à noite, saindo, ia pousar no monte chamado das Oliveiras.

[[v42-21-38]]

^<<v42-21-38,38>>^ E todo o povo madrugava para ir ter com ele no templo, a fim de ouvi-lo.

'''

xref:042-lucas/042-lucas-020.adoc#v42-20-0[&#60; Capítulo Anterior] | <<v42-21-0,Topo>> | xref:042-lucas/042-lucas-022.adoc#v42-22-0[Próximo Capítulo &#62;]