include::./index.adoc[]

[[v42-24-0]]
=== Lucas, 24
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-24-1]]

^<<v42-24-1,1>>^ Mas, no primeiro dia da semana, alta madrugada, foram elas ao túmulo, levando os aromas que haviam preparado.

[[v42-24-2]]

^<<v42-24-2,2>>^ E encontraram a pedra removida do sepulcro;

[[v42-24-3]]

^<<v42-24-3,3>>^ mas, ao entrarem, não acharam o corpo do Senhor Jesus.

[[v42-24-4]]

^<<v42-24-4,4>>^ Aconteceu que, perplexas a esse respeito, apareceram-lhes dois varões com vestes resplandecentes.

[[v42-24-5]]

^<<v42-24-5,5>>^ Estando elas possuídas de temor, baixando os olhos para o chão, eles lhes falaram: Por que buscais entre os mortos ao que vive?

[[v42-24-6]]

^<<v42-24-6,6>>^ Ele não está aqui, mas ressuscitou. Lembrai-vos de como vos preveniu, estando ainda na Galileia,

[[v42-24-7]]

^<<v42-24-7,7>>^ quando disse: Importa que o Filho do Homem seja entregue nas mãos de pecadores, e seja crucificado, e ressuscite no terceiro dia.

[[v42-24-8]]

^<<v42-24-8,8>>^ Então, se lembraram das suas palavras.

[[v42-24-9]]

^<<v42-24-9,9>>^ E, voltando do túmulo, anunciaram todas estas coisas aos onze e a todos os mais que com eles estavam.

[[v42-24-10]]

^<<v42-24-10,10>>^ Eram Maria Madalena, Joana e Maria, mãe de Tiago; também as demais que estavam com elas confirmaram estas coisas aos apóstolos.

[[v42-24-11]]

^<<v42-24-11,11>>^ Tais palavras lhes pareciam um como delírio, e não acreditaram nelas.

[[v42-24-12]]

^<<v42-24-12,12>>^ Pedro, porém, levantando-se, correu ao sepulcro. E, abaixando-se, nada mais viu, senão os lençóis de linho; e retirou-se para casa, maravilhado do que havia acontecido.

[[v42-24-13]]

^<<v42-24-13,13>>^ Naquele mesmo dia, dois deles estavam de caminho para uma aldeia chamada Emaús, distante de Jerusalém sessenta estádios.

[[v42-24-14]]

^<<v42-24-14,14>>^ E iam conversando a respeito de todas as coisas sucedidas.

[[v42-24-15]]

^<<v42-24-15,15>>^ Aconteceu que, enquanto conversavam e discutiam, o próprio Jesus se aproximou e ia com eles.

[[v42-24-16]]

^<<v42-24-16,16>>^ Os seus olhos, porém, estavam como que impedidos de o reconhecer.

[[v42-24-17]]

^<<v42-24-17,17>>^ Então, lhes perguntou Jesus: Que é isso que vos preocupa e de que ides tratando à medida que caminhais?  E eles pararam entristecidos.

[[v42-24-18]]

^<<v42-24-18,18>>^ Um, porém, chamado Cleopas, respondeu, dizendo: És o único, porventura, que, tendo estado em Jerusalém, ignoras as ocorrências destes últimos dias?

[[v42-24-19]]

^<<v42-24-19,19>>^ Ele lhes perguntou: Quais?  E explicaram: O que aconteceu a Jesus, o Nazareno, que era varão profeta, poderoso em obras e palavras, diante de Deus e de todo o povo,

[[v42-24-20]]

^<<v42-24-20,20>>^ e como os principais sacerdotes e as nossas autoridades o entregaram para ser condenado à morte e o crucificaram.

[[v42-24-21]]

^<<v42-24-21,21>>^ Ora, nós esperávamos que fosse ele quem havia de redimir a Israel; mas, depois de tudo isto, é já este o terceiro dia desde que tais coisas sucederam.

[[v42-24-22]]

^<<v42-24-22,22>>^ É verdade também que algumas mulheres, das que conosco estavam, nos surpreenderam, tendo ido de madrugada ao túmulo;

[[v42-24-23]]

^<<v42-24-23,23>>^ e, não achando o corpo de Jesus, voltaram dizendo terem tido uma visão de anjos, os quais afirmam que ele vive.

[[v42-24-24]]

^<<v42-24-24,24>>^ De fato, alguns dos nossos foram ao sepulcro e verificaram a exatidão do que disseram as mulheres; mas não o viram.

[[v42-24-25]]

^<<v42-24-25,25>>^ Então, lhes disse Jesus: Ó néscios e tardos de coração para crer tudo o que os profetas disseram!

[[v42-24-26]]

^<<v42-24-26,26>>^ Porventura, não convinha que o Cristo padecesse e entrasse na sua glória?

[[v42-24-27]]

^<<v42-24-27,27>>^ E, começando por Moisés, discorrendo por todos os Profetas, expunha-lhes o que a seu respeito constava em todas as Escrituras.

[[v42-24-28]]

^<<v42-24-28,28>>^ Quando se aproximavam da aldeia para onde iam, fez ele menção de passar adiante.

[[v42-24-29]]

^<<v42-24-29,29>>^ Mas eles o constrangeram, dizendo: Fica conosco, porque é tarde, e o dia já declina. E entrou para ficar com eles.

[[v42-24-30]]

^<<v42-24-30,30>>^ E aconteceu que, quando estavam à mesa, tomando ele o pão, abençoou-o e, tendo-o partido, lhes deu;

[[v42-24-31]]

^<<v42-24-31,31>>^ então, se lhes abriram os olhos, e o reconheceram; mas ele desapareceu da presença deles.

[[v42-24-32]]

^<<v42-24-32,32>>^ E disseram um ao outro: Porventura, não nos ardia o coração, quando ele, pelo caminho, nos falava, quando nos expunha as Escrituras?

[[v42-24-33]]

^<<v42-24-33,33>>^ E, na mesma hora, levantando-se, voltaram para Jerusalém, onde acharam reunidos os onze e outros com eles,

[[v42-24-34]]

^<<v42-24-34,34>>^ os quais diziam: O Senhor ressuscitou e já apareceu a Simão!

[[v42-24-35]]

^<<v42-24-35,35>>^ Então, os dois contaram o que lhes acontecera no caminho e como fora por eles reconhecido no partir do pão.

[[v42-24-36]]

^<<v42-24-36,36>>^ Falavam ainda estas coisas quando Jesus apareceu no meio deles e lhes disse: Paz seja convosco!

[[v42-24-37]]

^<<v42-24-37,37>>^ Eles, porém, surpresos e atemorizados, acreditavam estarem vendo um espírito.

[[v42-24-38]]

^<<v42-24-38,38>>^ Mas ele lhes disse: Por que estais perturbados? E por que sobem dúvidas ao vosso coração?

[[v42-24-39]]

^<<v42-24-39,39>>^ Vede as minhas mãos e os meus pés, que sou eu mesmo; apalpai-me e verificai, porque um espírito não tem carne nem ossos, como vedes que eu tenho.

[[v42-24-40]]

^<<v42-24-40,40>>^ Dizendo isto, mostrou-lhes as mãos e os pés.

[[v42-24-41]]

^<<v42-24-41,41>>^ E, por não acreditarem eles ainda, por causa da alegria, e estando admirados, Jesus lhes disse: Tendes aqui alguma coisa que comer?

[[v42-24-42]]

^<<v42-24-42,42>>^ Então, lhe apresentaram um pedaço de peixe assado [e um favo de mel].

[[v42-24-43]]

^<<v42-24-43,43>>^ E ele comeu na presença deles.

[[v42-24-44]]

^<<v42-24-44,44>>^ A seguir, Jesus lhes disse: São estas as palavras que eu vos falei, estando ainda convosco: importava se cumprisse tudo o que de mim está escrito na Lei de Moisés, nos Profetas e nos Salmos.

[[v42-24-45]]

^<<v42-24-45,45>>^ Então, lhes abriu o entendimento para compreenderem as Escrituras;

[[v42-24-46]]

^<<v42-24-46,46>>^ e lhes disse: Assim está escrito que o Cristo havia de padecer e ressuscitar dentre os mortos no terceiro dia

[[v42-24-47]]

^<<v42-24-47,47>>^ e que em seu nome se pregasse arrependimento para remissão de pecados a todas as nações, começando de Jerusalém.

[[v42-24-48]]

^<<v42-24-48,48>>^ Vós sois testemunhas destas coisas.

[[v42-24-49]]

^<<v42-24-49,49>>^ Eis que envio sobre vós a promessa de meu Pai; permanecei, pois, na cidade, até que do alto sejais revestidos de poder.

[[v42-24-50]]

^<<v42-24-50,50>>^ Então, os levou para Betânia e, erguendo as mãos, os abençoou.

[[v42-24-51]]

^<<v42-24-51,51>>^ Aconteceu que, enquanto os abençoava, ia-se retirando deles, sendo elevado para o céu.

[[v42-24-52]]

^<<v42-24-52,52>>^ Então, eles, adorando-o, voltaram para Jerusalém, tomados de grande júbilo;

[[v42-24-53]]

^<<v42-24-53,53>>^ e estavam sempre no templo, louvando a Deus.

'''

xref:042-lucas/042-lucas-023.adoc#v42-23-0[&#60; Capítulo Anterior] | <<v42-24-0,Topo>> | xref:043-joao/043-joao-001.adoc#v43-1-0[Próximo Capítulo &#62;]