include::./index.adoc[]

[[v42-5-0]]
=== Lucas, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-5-1]]

^<<v42-5-1,1>>^ Aconteceu que, ao apertá-lo a multidão para ouvir a palavra de Deus, estava ele junto ao lago de Genesaré;

[[v42-5-2]]

^<<v42-5-2,2>>^ e viu dois barcos junto à praia do lago; mas os pescadores, havendo desembarcado, lavavam as redes.

[[v42-5-3]]

^<<v42-5-3,3>>^ Entrando em um dos barcos, que era o de Simão, pediu-lhe que o afastasse um pouco da praia; e, assentando-se, ensinava do barco as multidões.

[[v42-5-4]]

^<<v42-5-4,4>>^ Quando acabou de falar, disse a Simão: Faze-te ao largo, e lançai as vossas redes para pescar.

[[v42-5-5]]

^<<v42-5-5,5>>^ Respondeu-lhe Simão: Mestre, havendo trabalhado toda a noite, nada apanhamos, mas sob a tua palavra lançarei as redes.

[[v42-5-6]]

^<<v42-5-6,6>>^ Isto fazendo, apanharam grande quantidade de peixes; e rompiam-se-lhes as redes.

[[v42-5-7]]

^<<v42-5-7,7>>^ Então, fizeram sinais aos companheiros do outro barco, para que fossem ajudá-los. E foram e encheram ambos os barcos, a ponto de quase irem a pique.

[[v42-5-8]]

^<<v42-5-8,8>>^ Vendo isto, Simão Pedro prostrou-se aos pés de Jesus, dizendo: Senhor, retira-te de mim, porque sou pecador.

[[v42-5-9]]

^<<v42-5-9,9>>^ Pois, à vista da pesca que fizeram, a admiração se apoderou dele e de todos os seus companheiros,

[[v42-5-10]]

^<<v42-5-10,10>>^ bem como de Tiago e João, filhos de Zebedeu, que eram seus sócios. Disse Jesus a Simão: Não temas; doravante serás pescador de homens.

[[v42-5-11]]

^<<v42-5-11,11>>^ E, arrastando eles os barcos sobre a praia, deixando tudo, o seguiram.

[[v42-5-12]]

^<<v42-5-12,12>>^ Aconteceu que, estando ele numa das cidades, veio à sua presença um homem coberto de lepra; ao ver a Jesus, prostrando-se com o rosto em terra, suplicou-lhe: Senhor, se quiseres, podes purificar-me.

[[v42-5-13]]

^<<v42-5-13,13>>^ E ele, estendendo a mão, tocou-lhe, dizendo: Quero, fica limpo!  E, no mesmo instante, lhe desapareceu a lepra.

[[v42-5-14]]

^<<v42-5-14,14>>^ Ordenou-lhe Jesus que a ninguém o dissesse, mas vai,  disse, mostra-te ao sacerdote e oferece, pela tua purificação, o sacrifício que Moisés determinou, para servir de testemunho ao povo.

[[v42-5-15]]

^<<v42-5-15,15>>^ Porém o que se dizia a seu respeito cada vez mais se divulgava, e grandes multidões afluíam para o ouvirem e serem curadas de suas enfermidades.

[[v42-5-16]]

^<<v42-5-16,16>>^ Ele, porém, se retirava para lugares solitários e orava.

[[v42-5-17]]

^<<v42-5-17,17>>^ Ora, aconteceu que, num daqueles dias, estava ele ensinando, e achavam-se ali assentados fariseus e mestres da Lei, vindos de todas as aldeias da Galileia, da Judeia e de Jerusalém. E o poder do Senhor estava com ele para curar.

[[v42-5-18]]

^<<v42-5-18,18>>^ Vieram, então, uns homens trazendo em um leito um paralítico; e procuravam introduzi-lo e pô-lo diante de Jesus.

[[v42-5-19]]

^<<v42-5-19,19>>^ E, não achando por onde introduzi-lo por causa da multidão, subindo ao eirado, o desceram no leito, por entre os ladrilhos, para o meio, diante de Jesus.

[[v42-5-20]]

^<<v42-5-20,20>>^ Vendo-lhes a fé, Jesus disse ao paralítico: Homem, estão perdoados os teus pecados.

[[v42-5-21]]

^<<v42-5-21,21>>^ E os escribas e fariseus arrazoavam, dizendo: Quem é este que diz blasfêmias? Quem pode perdoar pecados, senão Deus?

[[v42-5-22]]

^<<v42-5-22,22>>^ Jesus, porém, conhecendo-lhes os pensamentos, disse-lhes: Que arrazoais em vosso coração?

[[v42-5-23]]

^<<v42-5-23,23>>^ Qual é mais fácil, dizer: Estão perdoados os teus pecados ou: Levanta-te e anda?

[[v42-5-24]]

^<<v42-5-24,24>>^ Mas, para que saibais que o Filho do Homem tem sobre a terra autoridade para perdoar pecados  — disse ao paralítico: Eu te ordeno: Levanta-te, toma o teu leito e vai para casa.

[[v42-5-25]]

^<<v42-5-25,25>>^ Imediatamente, se levantou diante deles e, tomando o leito em que permanecera deitado, voltou para casa, glorificando a Deus.

[[v42-5-26]]

^<<v42-5-26,26>>^ Todos ficaram atônitos, davam glória a Deus e, possuídos de temor, diziam: Hoje, vimos prodígios.

[[v42-5-27]]

^<<v42-5-27,27>>^ Passadas estas coisas, saindo, viu um publicano, chamado Levi, assentado na coletoria, e disse-lhe: Segue-me!

[[v42-5-28]]

^<<v42-5-28,28>>^ Ele se levantou e, deixando tudo, o seguiu.

[[v42-5-29]]

^<<v42-5-29,29>>^ Então, lhe ofereceu Levi um grande banquete em sua casa; e numerosos publicanos e outros estavam com eles à mesa.

[[v42-5-30]]

^<<v42-5-30,30>>^ Os fariseus e seus escribas murmuravam contra os discípulos de Jesus, perguntando: Por que comeis e bebeis com os publicanos e pecadores?

[[v42-5-31]]

^<<v42-5-31,31>>^ Respondeu-lhes Jesus: Os sãos não precisam de médico, e sim os doentes.

[[v42-5-32]]

^<<v42-5-32,32>>^ Não vim chamar justos, e sim pecadores, ao arrependimento.

[[v42-5-33]]

^<<v42-5-33,33>>^ Disseram-lhe eles: Os discípulos de João e bem assim os dos fariseus frequentemente jejuam e fazem orações; os teus, entretanto, comem e bebem.

[[v42-5-34]]

^<<v42-5-34,34>>^ Jesus, porém, lhes disse: Podeis fazer jejuar os convidados para o casamento, enquanto está com eles o noivo?

[[v42-5-35]]

^<<v42-5-35,35>>^ Dias virão, contudo, em que lhes será tirado o noivo; naqueles dias, sim, jejuarão.

[[v42-5-36]]

^<<v42-5-36,36>>^ Também lhes disse uma parábola: Ninguém tira um pedaço de veste nova e o põe em veste velha; pois rasgará a nova, e o remendo da nova não se ajustará à velha.

[[v42-5-37]]

^<<v42-5-37,37>>^ E ninguém põe vinho novo em odres velhos, pois o vinho novo romperá os odres; entornar-se-á o vinho, e os odres se estragarão.

[[v42-5-38]]

^<<v42-5-38,38>>^ Pelo contrário, vinho novo deve ser posto em odres novos [e ambos se conservam].

[[v42-5-39]]

^<<v42-5-39,39>>^ E ninguém, tendo bebido o vinho velho, prefere o novo; porque diz: O velho é excelente.

'''

xref:042-lucas/042-lucas-004.adoc#v42-4-0[&#60; Capítulo Anterior] | <<v42-5-0,Topo>> | xref:042-lucas/042-lucas-006.adoc#v42-6-0[Próximo Capítulo &#62;]