include::./index.adoc[]

[[v42-7-0]]
=== Lucas, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-7-1]]

^<<v42-7-1,1>>^ Tendo Jesus concluído todas as suas palavras dirigidas ao povo, entrou em Cafarnaum.

[[v42-7-2]]

^<<v42-7-2,2>>^ E o servo de um centurião, a quem este muito estimava, estava doente, quase à morte.

[[v42-7-3]]

^<<v42-7-3,3>>^ Tendo ouvido falar a respeito de Jesus, enviou-lhe alguns anciãos dos judeus, pedindo-lhe que viesse curar o seu servo.

[[v42-7-4]]

^<<v42-7-4,4>>^ Estes, chegando-se a Jesus, com instância lhe suplicaram, dizendo: Ele é digno de que lhe faças isto;

[[v42-7-5]]

^<<v42-7-5,5>>^ porque é amigo do nosso povo, e ele mesmo nos edificou a sinagoga.

[[v42-7-6]]

^<<v42-7-6,6>>^ Então, Jesus foi com eles. E, já perto da casa, o centurião enviou-lhe amigos para lhe dizer: Senhor, não te incomodes, porque não sou digno de que entres em minha casa.

[[v42-7-7]]

^<<v42-7-7,7>>^ Por isso, eu mesmo não me julguei digno de ir ter contigo; porém manda com uma palavra, e o meu rapaz será curado.

[[v42-7-8]]

^<<v42-7-8,8>>^ Porque também eu sou homem sujeito à autoridade, e tenho soldados às minhas ordens, e digo a este: vai, e ele vai; e a outro: vem, e ele vem; e ao meu servo: faze isto, e ele o faz.

[[v42-7-9]]

^<<v42-7-9,9>>^ Ouvidas estas palavras, admirou-se Jesus dele e, voltando-se para o povo que o acompanhava, disse: Afirmo-vos que nem mesmo em Israel achei fé como esta.

[[v42-7-10]]

^<<v42-7-10,10>>^ E, voltando para casa os que foram enviados, encontraram curado o servo.

[[v42-7-11]]

^<<v42-7-11,11>>^ Em dia subsequente, dirigia-se Jesus a uma cidade chamada Naim, e iam com ele os seus discípulos e numerosa multidão.

[[v42-7-12]]

^<<v42-7-12,12>>^ Como se aproximasse da porta da cidade, eis que saía o enterro do filho único de uma viúva; e grande multidão da cidade ia com ela.

[[v42-7-13]]

^<<v42-7-13,13>>^ Vendo-a, o Senhor se compadeceu dela e lhe disse: Não chores!

[[v42-7-14]]

^<<v42-7-14,14>>^ Chegando-se, tocou o esquife e, parando os que o conduziam, disse: Jovem, eu te mando: levanta-te!

[[v42-7-15]]

^<<v42-7-15,15>>^ Sentou-se o que estivera morto e passou a falar; e Jesus o restituiu a sua mãe.

[[v42-7-16]]

^<<v42-7-16,16>>^ Todos ficaram possuídos de temor e glorificavam a Deus, dizendo: Grande profeta se levantou entre nós; e: Deus visitou o seu povo.

[[v42-7-17]]

^<<v42-7-17,17>>^ Esta notícia a respeito dele divulgou-se por toda a Judeia e por toda a circunvizinhança.

[[v42-7-18]]

^<<v42-7-18,18>>^ Todas estas coisas foram referidas a João pelos seus discípulos. E João, chamando dois deles,

[[v42-7-19]]

^<<v42-7-19,19>>^ enviou-os ao Senhor para perguntar: És tu aquele que estava para vir ou havemos de esperar outro?

[[v42-7-20]]

^<<v42-7-20,20>>^ Quando os homens chegaram junto dele, disseram: João Batista enviou-nos para te perguntar: És tu aquele que estava para vir ou esperaremos outro?

[[v42-7-21]]

^<<v42-7-21,21>>^ Naquela mesma hora, curou Jesus muitos de moléstias, e de flagelos, e de espíritos malignos; e deu vista a muitos cegos.

[[v42-7-22]]

^<<v42-7-22,22>>^ Então, Jesus lhes respondeu: Ide e anunciai a João o que vistes e ouvistes: os cegos veem, os coxos andam, os leprosos são purificados, os surdos ouvem, os mortos são ressuscitados, e aos pobres, anuncia-se-lhes o evangelho.

[[v42-7-23]]

^<<v42-7-23,23>>^ E bem-aventurado é aquele que não achar em mim motivo de tropeço.

[[v42-7-24]]

^<<v42-7-24,24>>^ Tendo-se retirado os mensageiros, passou Jesus a dizer ao povo a respeito de João: Que saístes a ver no deserto? Um caniço agitado pelo vento?

[[v42-7-25]]

^<<v42-7-25,25>>^ Que saístes a ver? Um homem vestido de roupas finas? Os que se vestem bem e vivem no luxo assistem nos palácios dos reis.

[[v42-7-26]]

^<<v42-7-26,26>>^ Sim, que saístes a ver? Um profeta? Sim, eu vos digo, e muito mais que profeta.

[[v42-7-27]]

^<<v42-7-27,27>>^ Este é aquele de quem está escrito: Eis aí envio diante da tua face o meu mensageiro, o qual preparará o teu caminho diante de ti.

[[v42-7-28]]

^<<v42-7-28,28>>^ E eu vos digo: entre os nascidos de mulher, ninguém é maior do que João; mas o menor no reino de Deus é maior do que ele.

[[v42-7-29]]

^<<v42-7-29,29>>^ Todo o povo que o ouviu e até os publicanos reconheceram a justiça de Deus, tendo sido batizados com o batismo de João;

[[v42-7-30]]

^<<v42-7-30,30>>^ mas os fariseus e os intérpretes da Lei rejeitaram, quanto a si mesmos, o desígnio de Deus, não tendo sido batizados por ele.

[[v42-7-31]]

^<<v42-7-31,31>>^ A que, pois, compararei os homens da presente geração, e a que são eles semelhantes?

[[v42-7-32]]

^<<v42-7-32,32>>^ São semelhantes a meninos que, sentados na praça, gritam uns para os outros: Nós vos tocamos flauta, e não dançastes; entoamos lamentações, e não chorastes.

[[v42-7-33]]

^<<v42-7-33,33>>^ Pois veio João Batista, não comendo pão, nem bebendo vinho, e dizeis: Tem demônio!

[[v42-7-34]]

^<<v42-7-34,34>>^ Veio o Filho do Homem, comendo e bebendo, e dizeis: Eis aí um glutão e bebedor de vinho, amigo de publicanos e pecadores!

[[v42-7-35]]

^<<v42-7-35,35>>^ Mas a sabedoria é justificada por todos os seus filhos.

[[v42-7-36]]

^<<v42-7-36,36>>^ Convidou-o um dos fariseus para que fosse jantar com ele. Jesus, entrando na casa do fariseu, tomou lugar à mesa.

[[v42-7-37]]

^<<v42-7-37,37>>^ E eis que uma mulher da cidade, pecadora, sabendo que ele estava à mesa na casa do fariseu, levou um vaso de alabastro com unguento;

[[v42-7-38]]

^<<v42-7-38,38>>^ e, estando por detrás, aos seus pés, chorando, regava-os com suas lágrimas e os enxugava com os próprios cabelos; e beijava-lhe os pés e os ungia com o unguento.

[[v42-7-39]]

^<<v42-7-39,39>>^ Ao ver isto, o fariseu que o convidara disse consigo mesmo: Se este fora profeta, bem saberia quem e qual é a mulher que lhe tocou, porque é pecadora.

[[v42-7-40]]

^<<v42-7-40,40>>^ Dirigiu-se Jesus ao fariseu e lhe disse: Simão, uma coisa tenho a dizer-te.  Ele respondeu: Dize-a, Mestre.

[[v42-7-41]]

^<<v42-7-41,41>>^ Certo credor tinha dois devedores: um lhe devia quinhentos denários, e o outro, cinquenta.

[[v42-7-42]]

^<<v42-7-42,42>>^ Não tendo nenhum dos dois com que pagar, perdoou-lhes a ambos. Qual deles, portanto, o amará mais?

[[v42-7-43]]

^<<v42-7-43,43>>^ Respondeu-lhe Simão: Suponho que aquele a quem mais perdoou. Replicou-lhe: Julgaste bem.

[[v42-7-44]]

^<<v42-7-44,44>>^ E, voltando-se para a mulher, disse a Simão: Vês esta mulher? Entrei em tua casa, e não me deste água para os pés; esta, porém, regou os meus pés com lágrimas e os enxugou com os seus cabelos.

[[v42-7-45]]

^<<v42-7-45,45>>^ Não me deste ósculo; ela, entretanto, desde que entrei não cessa de me beijar os pés.

[[v42-7-46]]

^<<v42-7-46,46>>^ Não me ungiste a cabeça com óleo, mas esta, com bálsamo, ungiu os meus pés.

[[v42-7-47]]

^<<v42-7-47,47>>^ Por isso, te digo: perdoados lhe são os seus muitos pecados, porque ela muito amou; mas aquele a quem pouco se perdoa, pouco ama.

[[v42-7-48]]

^<<v42-7-48,48>>^ Então, disse à mulher: Perdoados são os teus pecados.

[[v42-7-49]]

^<<v42-7-49,49>>^ Os que estavam com ele à mesa começaram a dizer entre si: Quem é este que até perdoa pecados?

[[v42-7-50]]

^<<v42-7-50,50>>^ Mas Jesus disse à mulher: A tua fé te salvou; vai-te em paz.

'''

xref:042-lucas/042-lucas-006.adoc#v42-6-0[&#60; Capítulo Anterior] | <<v42-7-0,Topo>> | xref:042-lucas/042-lucas-008.adoc#v42-8-0[Próximo Capítulo &#62;]