include::./index.adoc[]

[[v42-18-0]]
=== Lucas, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-18-1]]

^<<v42-18-1,1>>^ Disse-lhes Jesus uma parábola sobre o dever de orar sempre e nunca esmorecer:

[[v42-18-2]]

^<<v42-18-2,2>>^ Havia em certa cidade um juiz que não temia a Deus, nem respeitava homem algum.

[[v42-18-3]]

^<<v42-18-3,3>>^ Havia também, naquela mesma cidade, uma viúva que vinha ter com ele, dizendo: Julga a minha causa contra o meu adversário.

[[v42-18-4]]

^<<v42-18-4,4>>^ Ele, por algum tempo, não a quis atender; mas, depois, disse consigo: Bem que eu não temo a Deus, nem respeito a homem algum;

[[v42-18-5]]

^<<v42-18-5,5>>^ todavia, como esta viúva me importuna, julgarei a sua causa, para não suceder que, por fim, venha a molestar-me.

[[v42-18-6]]

^<<v42-18-6,6>>^ Então, disse o Senhor: Considerai no que diz este juiz iníquo.

[[v42-18-7]]

^<<v42-18-7,7>>^ Não fará Deus justiça aos seus escolhidos, que a ele clamam dia e noite, embora pareça demorado em defendê-los?

[[v42-18-8]]

^<<v42-18-8,8>>^ Digo-vos que, depressa, lhes fará justiça. Contudo, quando vier o Filho do Homem, achará, porventura, fé na terra?

[[v42-18-9]]

^<<v42-18-9,9>>^ Propôs também esta parábola a alguns que confiavam em si mesmos, por se considerarem justos, e desprezavam os outros:

[[v42-18-10]]

^<<v42-18-10,10>>^ Dois homens subiram ao templo com o propósito de orar: um, fariseu, e o outro, publicano.

[[v42-18-11]]

^<<v42-18-11,11>>^ O fariseu, posto em pé, orava de si para si mesmo, desta forma: Ó Deus, graças te dou porque não sou como os demais homens, roubadores, injustos e adúlteros, nem ainda como este publicano;

[[v42-18-12]]

^<<v42-18-12,12>>^ jejuo duas vezes por semana e dou o dízimo de tudo quanto ganho.

[[v42-18-13]]

^<<v42-18-13,13>>^ O publicano, estando em pé, longe, não ousava nem ainda levantar os olhos ao céu, mas batia no peito, dizendo: Ó Deus, sê propício a mim, pecador!

[[v42-18-14]]

^<<v42-18-14,14>>^ Digo-vos que este desceu justificado para sua casa, e não aquele; porque todo o que se exalta será humilhado; mas o que se humilha será exaltado.

[[v42-18-15]]

^<<v42-18-15,15>>^ Traziam-lhe também as crianças, para que as tocasse; e os discípulos, vendo, os repreendiam.

[[v42-18-16]]

^<<v42-18-16,16>>^ Jesus, porém, chamando-as para junto de si, ordenou: Deixai vir a mim os pequeninos e não os embaraceis, porque dos tais é o reino de Deus.

[[v42-18-17]]

^<<v42-18-17,17>>^ Em verdade vos digo: Quem não receber o reino de Deus como uma criança de maneira alguma entrará nele.

[[v42-18-18]]

^<<v42-18-18,18>>^ Certo homem de posição perguntou-lhe: Bom Mestre, que farei para herdar a vida eterna?

[[v42-18-19]]

^<<v42-18-19,19>>^ Respondeu-lhe Jesus: Por que me chamas bom? Ninguém é bom, senão um, que é Deus.

[[v42-18-20]]

^<<v42-18-20,20>>^ Sabes os mandamentos: Não adulterarás , não matarás , não furtarás , não dirás falso testemunho , honra a teu pai e a tua mãe.

[[v42-18-21]]

^<<v42-18-21,21>>^ Replicou ele: Tudo isso tenho observado desde a minha juventude.

[[v42-18-22]]

^<<v42-18-22,22>>^ Ouvindo-o Jesus, disse-lhe: Uma coisa ainda te falta: vende tudo o que tens, dá-o aos pobres e terás um tesouro nos céus; depois, vem e segue-me.

[[v42-18-23]]

^<<v42-18-23,23>>^ Mas, ouvindo ele estas palavras, ficou muito triste, porque era riquíssimo.

[[v42-18-24]]

^<<v42-18-24,24>>^ E Jesus, vendo-o assim triste, disse: Quão dificilmente entrarão no reino de Deus os que têm riquezas!

[[v42-18-25]]

^<<v42-18-25,25>>^ Porque é mais fácil passar um camelo pelo fundo de uma agulha do que entrar um rico no reino de Deus.

[[v42-18-26]]

^<<v42-18-26,26>>^ E os que ouviram disseram: Sendo assim, quem pode ser salvo?

[[v42-18-27]]

^<<v42-18-27,27>>^ Mas ele respondeu: Os impossíveis dos homens são possíveis para Deus.

[[v42-18-28]]

^<<v42-18-28,28>>^ E disse Pedro: Eis que nós deixamos nossa casa e te seguimos.

[[v42-18-29]]

^<<v42-18-29,29>>^ Respondeu-lhes Jesus: Em verdade vos digo que ninguém há que tenha deixado casa, ou mulher, ou irmãos, ou pais, ou filhos, por causa do reino de Deus,

[[v42-18-30]]

^<<v42-18-30,30>>^ que não receba, no presente, muitas vezes mais e, no mundo por vir, a vida eterna.

[[v42-18-31]]

^<<v42-18-31,31>>^ Tomando consigo os doze, disse-lhes Jesus: Eis que subimos para Jerusalém, e vai cumprir-se ali tudo quanto está escrito por intermédio dos profetas, no tocante ao Filho do Homem;

[[v42-18-32]]

^<<v42-18-32,32>>^ pois será ele entregue aos gentios, escarnecido, ultrajado e cuspido;

[[v42-18-33]]

^<<v42-18-33,33>>^ e, depois de o açoitarem, tirar-lhe-ão a vida; mas, ao terceiro dia, ressuscitará.

[[v42-18-34]]

^<<v42-18-34,34>>^ Eles, porém, nada compreenderam acerca destas coisas; e o sentido destas palavras era-lhes encoberto, de sorte que não percebiam o que ele dizia.

[[v42-18-35]]

^<<v42-18-35,35>>^ Aconteceu que, ao aproximar-se ele de Jericó, estava um cego assentado à beira do caminho, pedindo esmolas.

[[v42-18-36]]

^<<v42-18-36,36>>^ E, ouvindo o tropel da multidão que passava, perguntou o que era aquilo.

[[v42-18-37]]

^<<v42-18-37,37>>^ Anunciaram-lhe que passava Jesus, o Nazareno.

[[v42-18-38]]

^<<v42-18-38,38>>^ Então, ele clamou: Jesus, Filho de Davi, tem compaixão de mim!

[[v42-18-39]]

^<<v42-18-39,39>>^ E os que iam na frente o repreendiam para que se calasse; ele, porém, cada vez gritava mais: Filho de Davi, tem misericórdia de mim!

[[v42-18-40]]

^<<v42-18-40,40>>^ Então, parou Jesus e mandou que lho trouxessem. E, tendo ele chegado, perguntou-lhe:

[[v42-18-41]]

^<<v42-18-41,41>>^ Que queres que eu te faça?  Respondeu ele: Senhor, que eu torne a ver.

[[v42-18-42]]

^<<v42-18-42,42>>^ Então, Jesus lhe disse: Recupera a tua vista; a tua fé te salvou.

[[v42-18-43]]

^<<v42-18-43,43>>^ Imediatamente, tornou a ver e seguia-o glorificando a Deus. Também todo o povo, vendo isto, dava louvores a Deus.

'''

xref:042-lucas/042-lucas-017.adoc#v42-17-0[&#60; Capítulo Anterior] | <<v42-18-0,Topo>> | xref:042-lucas/042-lucas-019.adoc#v42-19-0[Próximo Capítulo &#62;]