include::./index.adoc[]

[[v42-10-0]]
=== Lucas, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-10-1]]

^<<v42-10-1,1>>^ Depois disto, o Senhor designou outros setenta; e os enviou de dois em dois, para que o precedessem em cada cidade e lugar aonde ele estava para ir.

[[v42-10-2]]

^<<v42-10-2,2>>^ E lhes fez a seguinte advertência: A seara é grande, mas os trabalhadores são poucos. Rogai, pois, ao Senhor da seara que mande trabalhadores para a sua seara.

[[v42-10-3]]

^<<v42-10-3,3>>^ Ide! Eis que eu vos envio como cordeiros para o meio de lobos.

[[v42-10-4]]

^<<v42-10-4,4>>^ Não leveis bolsa, nem alforje, nem sandálias; e a ninguém saudeis pelo caminho.

[[v42-10-5]]

^<<v42-10-5,5>>^ Ao entrardes numa casa, dizei antes de tudo: Paz seja nesta casa!

[[v42-10-6]]

^<<v42-10-6,6>>^ Se houver ali um filho da paz, repousará sobre ele a vossa paz; se não houver, ela voltará sobre vós.

[[v42-10-7]]

^<<v42-10-7,7>>^ Permanecei na mesma casa, comendo e bebendo do que eles tiverem; porque digno é o trabalhador do seu salário. Não andeis a mudar de casa em casa.

[[v42-10-8]]

^<<v42-10-8,8>>^ Quando entrardes numa cidade e ali vos receberem, comei do que vos for oferecido.

[[v42-10-9]]

^<<v42-10-9,9>>^ Curai os enfermos que nela houver e anunciai-lhes: A vós outros está próximo o reino de Deus.

[[v42-10-10]]

^<<v42-10-10,10>>^ Quando, porém, entrardes numa cidade e não vos receberem, saí pelas ruas e clamai:

[[v42-10-11]]

^<<v42-10-11,11>>^ Até o pó da vossa cidade, que se nos pegou aos pés, sacudimos contra vós outros. Não obstante, sabei que está próximo o reino de Deus.

[[v42-10-12]]

^<<v42-10-12,12>>^ Digo-vos que, naquele dia, haverá menos rigor para Sodoma do que para aquela cidade.

[[v42-10-13]]

^<<v42-10-13,13>>^ Ai de ti, Corazim! Ai de ti, Betsaida! Porque, se em Tiro e em Sidom, se tivessem operado os milagres que em vós se fizeram, há muito que elas se teriam arrependido, assentadas em pano de saco e cinza.

[[v42-10-14]]

^<<v42-10-14,14>>^ Contudo, no Juízo, haverá menos rigor para Tiro e Sidom do que para vós outras.

[[v42-10-15]]

^<<v42-10-15,15>>^ Tu, Cafarnaum, elevar-te-ás, porventura, até ao céu? Descerás até ao inferno.

[[v42-10-16]]

^<<v42-10-16,16>>^ Quem vos der ouvidos ouve-me a mim; e quem vos rejeitar a mim me rejeita; quem, porém, me rejeitar rejeita aquele que me enviou.

[[v42-10-17]]

^<<v42-10-17,17>>^ Então, regressaram os setenta, possuídos de alegria, dizendo: Senhor, os próprios demônios se nos submetem pelo teu nome!

[[v42-10-18]]

^<<v42-10-18,18>>^ Mas ele lhes disse: Eu via Satanás caindo do céu como um relâmpago.

[[v42-10-19]]

^<<v42-10-19,19>>^ Eis aí vos dei autoridade para pisardes serpentes e escorpiões e sobre todo o poder do inimigo, e nada, absolutamente, vos causará dano.

[[v42-10-20]]

^<<v42-10-20,20>>^ Não obstante, alegrai-vos, não porque os espíritos se vos submetem, e sim porque o vosso nome está arrolado nos céus.

[[v42-10-21]]

^<<v42-10-21,21>>^ Naquela hora, exultou Jesus no Espírito Santo e exclamou: Graças te dou, ó Pai, Senhor do céu e da terra, porque ocultaste estas coisas aos sábios e instruídos e as revelaste aos pequeninos. Sim, ó Pai, porque assim foi do teu agrado.

[[v42-10-22]]

^<<v42-10-22,22>>^ Tudo me foi entregue por meu Pai. Ninguém sabe quem é o Filho, senão o Pai; e também ninguém sabe quem é o Pai, senão o Filho, e aquele a quem o Filho o quiser revelar.

[[v42-10-23]]

^<<v42-10-23,23>>^ E, voltando-se para os seus discípulos, disse-lhes particularmente: Bem-aventurados os olhos que veem as coisas que vós vedes.

[[v42-10-24]]

^<<v42-10-24,24>>^ Pois eu vos afirmo que muitos profetas e reis quiseram ver o que vedes e não viram; e ouvir o que ouvis e não o ouviram.

[[v42-10-25]]

^<<v42-10-25,25>>^ E eis que certo homem, intérprete da Lei, se levantou com o intuito de pôr Jesus à prova e disse-lhe: Mestre, que farei para herdar a vida eterna?

[[v42-10-26]]

^<<v42-10-26,26>>^ Então, Jesus lhe perguntou: Que está escrito na Lei? Como interpretas?

[[v42-10-27]]

^<<v42-10-27,27>>^ A isto ele respondeu: Amarás o Senhor, teu Deus, de todo o teu coração, de toda a tua alma, de todas as tuas forças e de todo o teu entendimento; e: Amarás o teu próximo como a ti mesmo.

[[v42-10-28]]

^<<v42-10-28,28>>^ Então, Jesus lhe disse: Respondeste corretamente; faze isto e viverás.

[[v42-10-29]]

^<<v42-10-29,29>>^ Ele, porém, querendo justificar-se, perguntou a Jesus: Quem é o meu próximo?

[[v42-10-30]]

^<<v42-10-30,30>>^ Jesus prosseguiu, dizendo: Certo homem descia de Jerusalém para Jericó e veio a cair em mãos de salteadores, os quais, depois de tudo lhe roubarem e lhe causarem muitos ferimentos, retiraram-se, deixando-o semimorto.

[[v42-10-31]]

^<<v42-10-31,31>>^ Casualmente, descia um sacerdote por aquele mesmo caminho e, vendo-o, passou de largo.

[[v42-10-32]]

^<<v42-10-32,32>>^ Semelhantemente, um levita descia por aquele lugar e, vendo-o, também passou de largo.

[[v42-10-33]]

^<<v42-10-33,33>>^ Certo samaritano, que seguia o seu caminho, passou-lhe perto e, vendo-o, compadeceu-se dele.

[[v42-10-34]]

^<<v42-10-34,34>>^ E, chegando-se, pensou-lhe os ferimentos, aplicando-lhes óleo e vinho; e, colocando-o sobre o seu próprio animal, levou-o para uma hospedaria e tratou dele.

[[v42-10-35]]

^<<v42-10-35,35>>^ No dia seguinte, tirou dois denários e os entregou ao hospedeiro, dizendo: Cuida deste homem, e, se alguma coisa gastares a mais, eu to indenizarei quando voltar.

[[v42-10-36]]

^<<v42-10-36,36>>^ Qual destes três te parece ter sido o próximo do homem que caiu nas mãos dos salteadores?

[[v42-10-37]]

^<<v42-10-37,37>>^ Respondeu-lhe o intérprete da Lei: O que usou de misericórdia para com ele. Então, lhe disse: Vai e procede tu de igual modo.

[[v42-10-38]]

^<<v42-10-38,38>>^ Indo eles de caminho, entrou Jesus num povoado. E certa mulher, chamada Marta, hospedou-o na sua casa.

[[v42-10-39]]

^<<v42-10-39,39>>^ Tinha ela uma irmã, chamada Maria, e esta quedava-se assentada aos pés do Senhor a ouvir-lhe os ensinamentos.

[[v42-10-40]]

^<<v42-10-40,40>>^ Marta agitava-se de um lado para outro, ocupada em muitos serviços. Então, se aproximou de Jesus e disse: Senhor, não te importas de que minha irmã tenha deixado que eu fique a servir sozinha? Ordena-lhe, pois, que venha ajudar-me.

[[v42-10-41]]

^<<v42-10-41,41>>^ Respondeu-lhe o Senhor: Marta! Marta! Andas inquieta e te preocupas com muitas coisas.

[[v42-10-42]]

^<<v42-10-42,42>>^ Entretanto, pouco é necessário ou mesmo uma só coisa; Maria, pois, escolheu a boa parte, e esta não lhe será tirada.

'''

xref:042-lucas/042-lucas-009.adoc#v42-9-0[&#60; Capítulo Anterior] | <<v42-10-0,Topo>> | xref:042-lucas/042-lucas-011.adoc#v42-11-0[Próximo Capítulo &#62;]