include::./index.adoc[]

[[v42-22-0]]
=== Lucas, 22
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-22-1]]

^<<v42-22-1,1>>^ Estava próxima a Festa dos Pães Asmos, chamada Páscoa.

[[v42-22-2]]

^<<v42-22-2,2>>^ Preocupavam-se os principais sacerdotes e os escribas em como tirar a vida a Jesus; porque temiam o povo.

[[v42-22-3]]

^<<v42-22-3,3>>^ Ora, Satanás entrou em Judas, chamado Iscariotes, que era um dos doze.

[[v42-22-4]]

^<<v42-22-4,4>>^ Este foi entender-se com os principais sacerdotes e os capitães sobre como lhes entregaria a Jesus;

[[v42-22-5]]

^<<v42-22-5,5>>^ então, eles se alegraram e combinaram em lhe dar dinheiro.

[[v42-22-6]]

^<<v42-22-6,6>>^ Judas concordou e buscava uma boa ocasião de lho entregar sem tumulto.

[[v42-22-7]]

^<<v42-22-7,7>>^ Chegou o dia da Festa dos Pães Asmos, em que importava comemorar a Páscoa.

[[v42-22-8]]

^<<v42-22-8,8>>^ Jesus, pois, enviou Pedro e João, dizendo: Ide preparar-nos a Páscoa para que a comamos.

[[v42-22-9]]

^<<v42-22-9,9>>^ Eles lhe perguntaram: Onde queres que a preparemos?

[[v42-22-10]]

^<<v42-22-10,10>>^ Então, lhes explicou Jesus: Ao entrardes na cidade, encontrareis um homem com um cântaro de água; segui-o até à casa em que ele entrar

[[v42-22-11]]

^<<v42-22-11,11>>^ e dizei ao dono da casa: O Mestre manda perguntar-te: Onde é o aposento no qual hei de comer a Páscoa com os meus discípulos?

[[v42-22-12]]

^<<v42-22-12,12>>^ Ele vos mostrará um espaçoso cenáculo mobilado; ali fazei os preparativos.

[[v42-22-13]]

^<<v42-22-13,13>>^ E, indo, tudo encontraram como Jesus lhes dissera e prepararam a Páscoa.

[[v42-22-14]]

^<<v42-22-14,14>>^ Chegada a hora, pôs-se Jesus à mesa, e com ele os apóstolos.

[[v42-22-15]]

^<<v42-22-15,15>>^ E disse-lhes: Tenho desejado ansiosamente comer convosco esta Páscoa, antes do meu sofrimento.

[[v42-22-16]]

^<<v42-22-16,16>>^ Pois vos digo que nunca mais a comerei, até que ela se cumpra no reino de Deus.

[[v42-22-17]]

^<<v42-22-17,17>>^ E, tomando um cálice, havendo dado graças, disse: Recebei e reparti entre vós;

[[v42-22-18]]

^<<v42-22-18,18>>^ pois vos digo que, de agora em diante, não mais beberei do fruto da videira, até que venha o reino de Deus.

[[v42-22-19]]

^<<v42-22-19,19>>^ E, tomando um pão, tendo dado graças, o partiu e lhes deu, dizendo: Isto é o meu corpo oferecido por vós; fazei isto em memória de mim.

[[v42-22-20]]

^<<v42-22-20,20>>^ Semelhantemente, depois de cear, tomou o cálice, dizendo: Este é o cálice da nova aliança no meu sangue derramado em favor de vós.

[[v42-22-21]]

^<<v42-22-21,21>>^ Todavia, a mão do traidor está comigo à mesa.

[[v42-22-22]]

^<<v42-22-22,22>>^ Porque o Filho do Homem, na verdade, vai segundo o que está determinado, mas ai daquele por intermédio de quem ele está sendo traído!

[[v42-22-23]]

^<<v42-22-23,23>>^ Então, começaram a indagar entre si quem seria, dentre eles, o que estava para fazer isto.

[[v42-22-24]]

^<<v42-22-24,24>>^ Suscitaram também entre si uma discussão sobre qual deles parecia ser o maior.

[[v42-22-25]]

^<<v42-22-25,25>>^ Mas Jesus lhes disse: Os reis dos povos dominam sobre eles, e os que exercem autoridade são chamados benfeitores.

[[v42-22-26]]

^<<v42-22-26,26>>^ Mas vós não sois assim; pelo contrário, o maior entre vós seja como o menor; e aquele que dirige seja como o que serve.

[[v42-22-27]]

^<<v42-22-27,27>>^ Pois qual é maior: quem está à mesa ou quem serve? Porventura, não é quem está à mesa? Pois, no meio de vós, eu sou como quem serve.

[[v42-22-28]]

^<<v42-22-28,28>>^ Vós sois os que tendes permanecido comigo nas minhas tentações.

[[v42-22-29]]

^<<v42-22-29,29>>^ Assim como meu Pai me confiou um reino, eu vo-lo confio,

[[v42-22-30]]

^<<v42-22-30,30>>^ para que comais e bebais à minha mesa no meu reino; e vos assentareis em tronos para julgar as doze tribos de Israel.

[[v42-22-31]]

^<<v42-22-31,31>>^ Simão, Simão, eis que Satanás vos reclamou para vos peneirar como trigo!

[[v42-22-32]]

^<<v42-22-32,32>>^ Eu, porém, roguei por ti, para que a tua fé não desfaleça; tu, pois, quando te converteres, fortalece os teus irmãos.

[[v42-22-33]]

^<<v42-22-33,33>>^ Ele, porém, respondeu: Senhor, estou pronto a ir contigo, tanto para a prisão como para a morte.

[[v42-22-34]]

^<<v42-22-34,34>>^ Mas Jesus lhe disse: Afirmo-te, Pedro, que, hoje, três vezes negarás que me conheces, antes que o galo cante.

[[v42-22-35]]

^<<v42-22-35,35>>^ A seguir, Jesus lhes perguntou: Quando vos mandei sem bolsa, sem alforje e sem sandálias, faltou-vos, porventura, alguma coisa? Nada, disseram eles.

[[v42-22-36]]

^<<v42-22-36,36>>^ Então, lhes disse: Agora, porém, quem tem bolsa, tome-a, como também o alforje; e o que não tem espada, venda a sua capa e compre uma.

[[v42-22-37]]

^<<v42-22-37,37>>^ Pois vos digo que importa que se cumpra em mim o que está escrito: Ele foi contado com os malfeitores. Porque o que a mim se refere está sendo cumprido.

[[v42-22-38]]

^<<v42-22-38,38>>^ Então, lhe disseram: Senhor, eis aqui duas espadas! Respondeu-lhes: Basta!

[[v42-22-39]]

^<<v42-22-39,39>>^ E, saindo, foi, como de costume, para o monte das Oliveiras; e os discípulos o acompanharam.

[[v42-22-40]]

^<<v42-22-40,40>>^ Chegando ao lugar escolhido, Jesus lhes disse: Orai, para que não entreis em tentação.

[[v42-22-41]]

^<<v42-22-41,41>>^ Ele, por sua vez, se afastou, cerca de um tiro de pedra, e, de joelhos, orava,

[[v42-22-42]]

^<<v42-22-42,42>>^ dizendo: Pai, se queres, passa de mim este cálice; contudo, não se faça a minha vontade, e sim a tua.

[[v42-22-43]]

^<<v42-22-43,43>>^ [Então, lhe apareceu um anjo do céu que o confortava.

[[v42-22-44]]

^<<v42-22-44,44>>^ E, estando em agonia, orava mais intensamente. E aconteceu que o seu suor se tornou como gotas de sangue caindo sobre a terra.]

[[v42-22-45]]

^<<v42-22-45,45>>^ Levantando-se da oração, foi ter com os discípulos, e os achou dormindo de tristeza,

[[v42-22-46]]

^<<v42-22-46,46>>^ e disse-lhes: Por que estais dormindo? Levantai-vos e orai, para que não entreis em tentação.

[[v42-22-47]]

^<<v42-22-47,47>>^ Falava ele ainda, quando chegou uma multidão; e um dos doze, o chamado Judas, que vinha à frente deles, aproximou-se de Jesus para o beijar.

[[v42-22-48]]

^<<v42-22-48,48>>^ Jesus, porém, lhe disse: Judas, com um beijo trais o Filho do Homem?

[[v42-22-49]]

^<<v42-22-49,49>>^ Os que estavam ao redor dele, vendo o que ia suceder, perguntaram: Senhor, feriremos à espada?

[[v42-22-50]]

^<<v42-22-50,50>>^ Um deles feriu o servo do sumo sacerdote e cortou-lhe a orelha direita.

[[v42-22-51]]

^<<v42-22-51,51>>^ Mas Jesus acudiu, dizendo: Deixai, basta.  E, tocando-lhe a orelha, o curou.

[[v42-22-52]]

^<<v42-22-52,52>>^ Então, dirigindo-se Jesus aos principais sacerdotes, capitães do templo e anciãos que vieram prendê-lo, disse: Saístes com espadas e porretes como para deter um salteador?

[[v42-22-53]]

^<<v42-22-53,53>>^ Diariamente, estando eu convosco no templo, não pusestes as mãos sobre mim. Esta, porém, é a vossa hora e o poder das trevas.

[[v42-22-54]]

^<<v42-22-54,54>>^ Então, prendendo-o, o levaram e o introduziram na casa do sumo sacerdote. Pedro seguia de longe.

[[v42-22-55]]

^<<v42-22-55,55>>^ E, quando acenderam fogo no meio do pátio e juntos se assentaram, Pedro tomou lugar entre eles.

[[v42-22-56]]

^<<v42-22-56,56>>^ Entrementes, uma criada, vendo-o assentado perto do fogo, fitando-o, disse: Este também estava com ele.

[[v42-22-57]]

^<<v42-22-57,57>>^ Mas Pedro negava, dizendo: Mulher, não o conheço.

[[v42-22-58]]

^<<v42-22-58,58>>^ Pouco depois, vendo-o outro, disse: Também tu és dos tais. Pedro, porém, protestava: Homem, não sou.

[[v42-22-59]]

^<<v42-22-59,59>>^ E, tendo passado cerca de uma hora, outro afirmava, dizendo: Também este, verdadeiramente, estava com ele, porque também é galileu.

[[v42-22-60]]

^<<v42-22-60,60>>^ Mas Pedro insistia: Homem, não compreendo o que dizes. E logo, estando ele ainda a falar, cantou o galo.

[[v42-22-61]]

^<<v42-22-61,61>>^ Então, voltando-se o Senhor, fixou os olhos em Pedro, e Pedro se lembrou da palavra do Senhor, como lhe dissera: Hoje, três vezes me negarás, antes de cantar o galo.

[[v42-22-62]]

^<<v42-22-62,62>>^ Então, Pedro, saindo dali, chorou amargamente.

[[v42-22-63]]

^<<v42-22-63,63>>^ Os que detinham Jesus zombavam dele, davam-lhe pancadas e,

[[v42-22-64]]

^<<v42-22-64,64>>^ vendando-lhe os olhos, diziam: Profetiza-nos: quem é que te bateu?

[[v42-22-65]]

^<<v42-22-65,65>>^ E muitas outras coisas diziam contra ele, blasfemando.

[[v42-22-66]]

^<<v42-22-66,66>>^ Logo que amanheceu, reuniu-se a assembleia dos anciãos do povo, tanto os principais sacerdotes como os escribas, e o conduziram ao Sinédrio, onde lhe disseram:

[[v42-22-67]]

^<<v42-22-67,67>>^ Se tu és o Cristo, dize-nos. Então, Jesus lhes respondeu: Se vo-lo disser, não o acreditareis;

[[v42-22-68]]

^<<v42-22-68,68>>^ também, se vos perguntar, de nenhum modo me respondereis.

[[v42-22-69]]

^<<v42-22-69,69>>^ Desde agora, estará sentado o Filho do Homem à direita do Todo-Poderoso Deus.

[[v42-22-70]]

^<<v42-22-70,70>>^ Então, disseram todos: Logo, tu és o Filho de Deus? E ele lhes respondeu: Vós dizeis que eu sou.

[[v42-22-71]]

^<<v42-22-71,71>>^ Clamaram, pois: Que necessidade mais temos de testemunho? Porque nós mesmos o ouvimos da sua própria boca.

'''

xref:042-lucas/042-lucas-021.adoc#v42-21-0[&#60; Capítulo Anterior] | <<v42-22-0,Topo>> | xref:042-lucas/042-lucas-023.adoc#v42-23-0[Próximo Capítulo &#62;]