include::./index.adoc[]

[[v42-1-0]]
=== Lucas, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-1-1]]

^<<v42-1-1,1>>^ Visto que muitos houve que empreenderam uma narração coordenada dos fatos que entre nós se realizaram,

[[v42-1-2]]

^<<v42-1-2,2>>^ conforme nos transmitiram os que desde o princípio foram deles testemunhas oculares e ministros da palavra,

[[v42-1-3]]

^<<v42-1-3,3>>^ igualmente a mim me pareceu bem, depois de acurada investigação de tudo desde sua origem, dar-te por escrito, excelentíssimo Teófilo, uma exposição em ordem,

[[v42-1-4]]

^<<v42-1-4,4>>^ para que tenhas plena certeza das verdades em que foste instruído.

[[v42-1-5]]

^<<v42-1-5,5>>^ Nos dias de Herodes, rei da Judeia, houve um sacerdote chamado Zacarias, do turno de Abias. Sua mulher era das filhas de Arão e se chamava Isabel.

[[v42-1-6]]

^<<v42-1-6,6>>^ Ambos eram justos diante de Deus, vivendo irrepreensivelmente em todos os preceitos e mandamentos do Senhor.

[[v42-1-7]]

^<<v42-1-7,7>>^ E não tinham filhos, porque Isabel era estéril, sendo eles avançados em dias.

[[v42-1-8]]

^<<v42-1-8,8>>^ Ora, aconteceu que, exercendo ele diante de Deus o sacerdócio na ordem do seu turno, coube-lhe por sorte,

[[v42-1-9]]

^<<v42-1-9,9>>^ segundo o costume sacerdotal, entrar no santuário do Senhor para queimar o incenso;

[[v42-1-10]]

^<<v42-1-10,10>>^ e, durante esse tempo, toda a multidão do povo permanecia da parte de fora, orando.

[[v42-1-11]]

^<<v42-1-11,11>>^ E eis que lhe apareceu um anjo do Senhor, em pé, à direita do altar do incenso.

[[v42-1-12]]

^<<v42-1-12,12>>^ Vendo-o, Zacarias turbou-se, e apoderou-se dele o temor.

[[v42-1-13]]

^<<v42-1-13,13>>^ Disse-lhe, porém, o anjo: Zacarias, não temas, porque a tua oração foi ouvida; e Isabel, tua mulher, te dará à luz um filho, a quem darás o nome de João.

[[v42-1-14]]

^<<v42-1-14,14>>^ Em ti haverá prazer e alegria, e muitos se regozijarão com o seu nascimento.

[[v42-1-15]]

^<<v42-1-15,15>>^ Pois ele será grande diante do Senhor, não beberá vinho nem bebida forte e será cheio do Espírito Santo, já do ventre materno.

[[v42-1-16]]

^<<v42-1-16,16>>^ E converterá muitos dos filhos de Israel ao Senhor, seu Deus.

[[v42-1-17]]

^<<v42-1-17,17>>^ E irá adiante do Senhor no espírito e poder de Elias, para converter o coração dos pais aos filhos, converter os desobedientes à prudência dos justos e habilitar para o Senhor um povo preparado.

[[v42-1-18]]

^<<v42-1-18,18>>^ Então, perguntou Zacarias ao anjo: Como saberei isto? Pois eu sou velho, e minha mulher, avançada em dias.

[[v42-1-19]]

^<<v42-1-19,19>>^ Respondeu-lhe o anjo: Eu sou Gabriel, que assisto diante de Deus, e fui enviado para falar-te e trazer-te estas boas-novas.

[[v42-1-20]]

^<<v42-1-20,20>>^ Todavia, ficarás mudo e não poderás falar até ao dia em que estas coisas venham a realizar-se; porquanto não acreditaste nas minhas palavras, as quais, a seu tempo, se cumprirão.

[[v42-1-21]]

^<<v42-1-21,21>>^ O povo estava esperando a Zacarias e admirava-se de que tanto se demorasse no santuário.

[[v42-1-22]]

^<<v42-1-22,22>>^ Mas, saindo ele, não lhes podia falar; então, entenderam que tivera uma visão no santuário. E expressava-se por acenos e permanecia mudo.

[[v42-1-23]]

^<<v42-1-23,23>>^ Sucedeu que, terminados os dias de seu ministério, voltou para casa.

[[v42-1-24]]

^<<v42-1-24,24>>^ Passados esses dias, Isabel, sua mulher, concebeu e ocultou-se por cinco meses, dizendo:

[[v42-1-25]]

^<<v42-1-25,25>>^ Assim me fez o Senhor, contemplando-me, para anular o meu opróbrio perante os homens.

[[v42-1-26]]

^<<v42-1-26,26>>^ No sexto mês, foi o anjo Gabriel enviado, da parte de Deus, para uma cidade da Galileia, chamada Nazaré,

[[v42-1-27]]

^<<v42-1-27,27>>^ a uma virgem desposada com certo homem da casa de Davi, cujo nome era José; a virgem chamava-se Maria.

[[v42-1-28]]

^<<v42-1-28,28>>^ E, entrando o anjo aonde ela estava, disse: Alegra-te, muito favorecida! O Senhor é contigo.

[[v42-1-29]]

^<<v42-1-29,29>>^ Ela, porém, ao ouvir esta palavra, perturbou-se muito e pôs-se a pensar no que significaria esta saudação.

[[v42-1-30]]

^<<v42-1-30,30>>^ Mas o anjo lhe disse: Maria, não temas; porque achaste graça diante de Deus.

[[v42-1-31]]

^<<v42-1-31,31>>^ Eis que conceberás e darás à luz um filho, a quem chamarás pelo nome de Jesus.

[[v42-1-32]]

^<<v42-1-32,32>>^ Este será grande e será chamado Filho do Altíssimo; Deus, o Senhor, lhe dará o trono de Davi, seu pai;

[[v42-1-33]]

^<<v42-1-33,33>>^ ele reinará para sempre sobre a casa de Jacó, e o seu reinado não terá fim.

[[v42-1-34]]

^<<v42-1-34,34>>^ Então, disse Maria ao anjo: Como será isto, pois não tenho relação com homem algum?

[[v42-1-35]]

^<<v42-1-35,35>>^ Respondeu-lhe o anjo: Descerá sobre ti o Espírito Santo, e o poder do Altíssimo te envolverá com a sua sombra; por isso, também o ente santo que há de nascer será chamado Filho de Deus.

[[v42-1-36]]

^<<v42-1-36,36>>^ E Isabel, tua parenta, igualmente concebeu um filho na sua velhice, sendo este já o sexto mês para aquela que diziam ser estéril.

[[v42-1-37]]

^<<v42-1-37,37>>^ Porque para Deus não haverá impossíveis em todas as suas promessas.

[[v42-1-38]]

^<<v42-1-38,38>>^ Então, disse Maria: Aqui está a serva do Senhor; que se cumpra em mim conforme a tua palavra. E o anjo se ausentou dela.

[[v42-1-39]]

^<<v42-1-39,39>>^ Naqueles dias, dispondo-se Maria, foi apressadamente à região montanhosa, a uma cidade de Judá,

[[v42-1-40]]

^<<v42-1-40,40>>^ entrou na casa de Zacarias e saudou Isabel.

[[v42-1-41]]

^<<v42-1-41,41>>^ Ouvindo esta a saudação de Maria, a criança lhe estremeceu no ventre; então, Isabel ficou possuída do Espírito Santo.

[[v42-1-42]]

^<<v42-1-42,42>>^ E exclamou em alta voz: Bendita és tu entre as mulheres, e bendito o fruto do teu ventre!

[[v42-1-43]]

^<<v42-1-43,43>>^ E de onde me provém que me venha visitar a mãe do meu Senhor?

[[v42-1-44]]

^<<v42-1-44,44>>^ Pois, logo que me chegou aos ouvidos a voz da tua saudação, a criança estremeceu de alegria dentro de mim.

[[v42-1-45]]

^<<v42-1-45,45>>^ Bem-aventurada a que creu, porque serão cumpridas as palavras que lhe foram ditas da parte do Senhor.

[[v42-1-46]]

^<<v42-1-46,46>>^ Então, disse Maria: A minha alma engrandece ao Senhor,

[[v42-1-47]]

^<<v42-1-47,47>>^ e o meu espírito se alegrou em Deus, meu Salvador,

[[v42-1-48]]

^<<v42-1-48,48>>^ porque contemplou na humildade da sua serva. Pois, desde agora, todas as gerações me considerarão bem-aventurada,

[[v42-1-49]]

^<<v42-1-49,49>>^ porque o Poderoso me fez grandes coisas. Santo é o seu nome.

[[v42-1-50]]

^<<v42-1-50,50>>^ A sua misericórdia vai de geração em geração sobre os que o temem.

[[v42-1-51]]

^<<v42-1-51,51>>^ Agiu com o seu braço valorosamente; dispersou os que, no coração, alimentavam pensamentos soberbos.

[[v42-1-52]]

^<<v42-1-52,52>>^ Derribou do seu trono os poderosos e exaltou os humildes.

[[v42-1-53]]

^<<v42-1-53,53>>^ Encheu de bens os famintos e despediu vazios os ricos.

[[v42-1-54]]

^<<v42-1-54,54>>^ Amparou a Israel, seu servo, a fim de lembrar-se da sua misericórdia

[[v42-1-55]]

^<<v42-1-55,55>>^ a favor de Abraão e de sua descendência, para sempre, como prometera aos nossos pais.

[[v42-1-56]]

^<<v42-1-56,56>>^ Maria permaneceu cerca de três meses com Isabel e voltou para casa.

[[v42-1-57]]

^<<v42-1-57,57>>^ A Isabel cumpriu-se o tempo de dar à luz, e teve um filho.

[[v42-1-58]]

^<<v42-1-58,58>>^ Ouviram os seus vizinhos e parentes que o Senhor usara de grande misericórdia para com ela e participaram do seu regozijo.

[[v42-1-59]]

^<<v42-1-59,59>>^ Sucedeu que, no oitavo dia, foram circuncidar o menino e queriam dar-lhe o nome de seu pai, Zacarias.

[[v42-1-60]]

^<<v42-1-60,60>>^ De modo nenhum! Respondeu sua mãe. Pelo contrário, ele deve ser chamado João.

[[v42-1-61]]

^<<v42-1-61,61>>^ Disseram-lhe: Ninguém há na tua parentela que tenha este nome.

[[v42-1-62]]

^<<v42-1-62,62>>^ E perguntaram, por acenos, ao pai do menino que nome queria que lhe dessem.

[[v42-1-63]]

^<<v42-1-63,63>>^ Então, pedindo ele uma tabuinha, escreveu: João é o seu nome. E todos se admiraram.

[[v42-1-64]]

^<<v42-1-64,64>>^ Imediatamente, a boca se lhe abriu, e, desimpedida a língua, falava louvando a Deus.

[[v42-1-65]]

^<<v42-1-65,65>>^ Sucedeu que todos os seus vizinhos ficaram possuídos de temor, e por toda a região montanhosa da Judeia foram divulgadas estas coisas.

[[v42-1-66]]

^<<v42-1-66,66>>^ Todos os que as ouviram guardavam-nas no coração, dizendo: Que virá a ser, pois, este menino? E a mão do Senhor estava com ele.

[[v42-1-67]]

^<<v42-1-67,67>>^ Zacarias, seu pai, cheio do Espírito Santo, profetizou, dizendo:

[[v42-1-68]]

^<<v42-1-68,68>>^ Bendito seja o Senhor, Deus de Israel, porque visitou e redimiu o seu povo,

[[v42-1-69]]

^<<v42-1-69,69>>^ e nos suscitou plena e poderosa salvação na casa de Davi, seu servo,

[[v42-1-70]]

^<<v42-1-70,70>>^ como prometera, desde a antiguidade, por boca dos seus santos profetas,

[[v42-1-71]]

^<<v42-1-71,71>>^ para nos libertar dos nossos inimigos e das mãos de todos os que nos odeiam;

[[v42-1-72]]

^<<v42-1-72,72>>^ para usar de misericórdia com os nossos pais e lembrar-se da sua santa aliança

[[v42-1-73]]

^<<v42-1-73,73>>^ e do juramento que fez a Abraão, o nosso pai,

[[v42-1-74]]

^<<v42-1-74,74>>^ de conceder-nos que, livres das mãos de inimigos, o adorássemos sem temor,

[[v42-1-75]]

^<<v42-1-75,75>>^ em santidade e justiça perante ele, todos os nossos dias.

[[v42-1-76]]

^<<v42-1-76,76>>^ Tu, menino, serás chamado profeta do Altíssimo, porque precederás o Senhor, preparando-lhe os caminhos,

[[v42-1-77]]

^<<v42-1-77,77>>^ para dar ao seu povo conhecimento da salvação, no redimi-lo dos seus pecados,

[[v42-1-78]]

^<<v42-1-78,78>>^ graças à entranhável misericórdia de nosso Deus, pela qual nos visitará o sol nascente das alturas,

[[v42-1-79]]

^<<v42-1-79,79>>^ para alumiar os que jazem nas trevas e na sombra da morte, e dirigir os nossos pés pelo caminho da paz.

[[v42-1-80]]

^<<v42-1-80,80>>^ O menino crescia e se fortalecia em espírito. E viveu nos desertos até ao dia em que havia de manifestar-se a Israel.

'''

xref:041-marcos/041-marcos-016.adoc#v41-16-0[&#60; Capítulo Anterior] | <<v42-1-0,Topo>> | xref:042-lucas/042-lucas-002.adoc#v42-2-0[Próximo Capítulo &#62;]