include::./index.adoc[]

[[v42-11-0]]
=== Lucas, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-11-1]]

^<<v42-11-1,1>>^ De uma feita, estava Jesus orando em certo lugar; quando terminou, um dos seus discípulos lhe pediu: Senhor, ensina-nos a orar como também João ensinou aos seus discípulos.

[[v42-11-2]]

^<<v42-11-2,2>>^ Então, ele os ensinou: Quando orardes, dizei: Pai, santificado seja o teu nome; venha o teu reino;

[[v42-11-3]]

^<<v42-11-3,3>>^ o pão nosso cotidiano dá-nos de dia em dia;

[[v42-11-4]]

^<<v42-11-4,4>>^ perdoa-nos os nossos pecados, pois também nós perdoamos a todo o que nos deve; e não nos deixes cair em tentação.

[[v42-11-5]]

^<<v42-11-5,5>>^ Disse-lhes ainda Jesus: Qual dentre vós, tendo um amigo, e este for procurá-lo à meia-noite e lhe disser: Amigo, empresta-me três pães,

[[v42-11-6]]

^<<v42-11-6,6>>^ pois um meu amigo, chegando de viagem, procurou-me, e eu nada tenho que lhe oferecer.

[[v42-11-7]]

^<<v42-11-7,7>>^ E o outro lhe responda lá de dentro, dizendo: Não me importunes; a porta já está fechada, e os meus filhos comigo também já estão deitados. Não posso levantar-me para tos dar;

[[v42-11-8]]

^<<v42-11-8,8>>^ digo-vos que, se não se levantar para dar-lhos por ser seu amigo, todavia, o fará por causa da importunação e lhe dará tudo o de que tiver necessidade.

[[v42-11-9]]

^<<v42-11-9,9>>^ Por isso, vos digo: Pedi, e dar-se-vos-á; buscai, e achareis; batei, e abrir-se-vos-á.

[[v42-11-10]]

^<<v42-11-10,10>>^ Pois todo o que pede recebe; o que busca encontra; e a quem bate, abrir-se-lhe-á.

[[v42-11-11]]

^<<v42-11-11,11>>^ Qual dentre vós é o pai que, se o filho lhe pedir [pão, lhe dará uma pedra? Ou se pedir] um peixe, lhe dará em lugar de peixe uma cobra?

[[v42-11-12]]

^<<v42-11-12,12>>^ Ou, se lhe pedir um ovo lhe dará um escorpião?

[[v42-11-13]]

^<<v42-11-13,13>>^ Ora, se vós, que sois maus, sabeis dar boas dádivas aos vossos filhos, quanto mais o Pai celestial dará o Espírito Santo àqueles que lho pedirem?

[[v42-11-14]]

^<<v42-11-14,14>>^ De outra feita, estava Jesus expelindo um demônio que era mudo. E aconteceu que, ao sair o demônio, o mudo passou a falar; e as multidões se admiravam.

[[v42-11-15]]

^<<v42-11-15,15>>^ Mas alguns dentre eles diziam: Ora, ele expele os demônios pelo poder de Belzebu, o maioral dos demônios.

[[v42-11-16]]

^<<v42-11-16,16>>^ E outros, tentando-o, pediam dele um sinal do céu.

[[v42-11-17]]

^<<v42-11-17,17>>^ E, sabendo ele o que se lhes passava pelo espírito, disse-lhes: Todo reino dividido contra si mesmo ficará deserto, e casa sobre casa cairá.

[[v42-11-18]]

^<<v42-11-18,18>>^ Se também Satanás estiver dividido contra si mesmo, como subsistirá o seu reino? Isto, porque dizeis que eu expulso os demônios por Belzebu.

[[v42-11-19]]

^<<v42-11-19,19>>^ E, se eu expulso os demônios por Belzebu, por quem os expulsam vossos filhos? Por isso, eles mesmos serão os vossos juízes.

[[v42-11-20]]

^<<v42-11-20,20>>^ Se, porém, eu expulso os demônios pelo dedo de Deus, certamente, é chegado o reino de Deus sobre vós.

[[v42-11-21]]

^<<v42-11-21,21>>^ Quando o valente, bem-armado, guarda a sua própria casa, ficam em segurança todos os seus bens.

[[v42-11-22]]

^<<v42-11-22,22>>^ Sobrevindo, porém, um mais valente do que ele, vence-o, tira-lhe a armadura em que confiava e lhe divide os despojos.

[[v42-11-23]]

^<<v42-11-23,23>>^ Quem não é por mim é contra mim; e quem comigo não ajunta espalha.

[[v42-11-24]]

^<<v42-11-24,24>>^ Quando o espírito imundo sai do homem, anda por lugares áridos, procurando repouso; e, não o achando, diz: Voltarei para minha casa, donde saí.

[[v42-11-25]]

^<<v42-11-25,25>>^ E, tendo voltado, a encontra varrida e ornamentada.

[[v42-11-26]]

^<<v42-11-26,26>>^ Então, vai e leva consigo outros sete espíritos, piores do que ele, e, entrando, habitam ali; e o último estado daquele homem se torna pior do que o primeiro.

[[v42-11-27]]

^<<v42-11-27,27>>^ Ora, aconteceu que, ao dizer Jesus estas palavras, uma mulher, que estava entre a multidão, exclamou e disse-lhe: Bem-aventurada aquela que te concebeu, e os seios que te amamentaram!

[[v42-11-28]]

^<<v42-11-28,28>>^ Ele, porém, respondeu: Antes, bem-aventurados são os que ouvem a palavra de Deus e a guardam!

[[v42-11-29]]

^<<v42-11-29,29>>^ Como afluíssem as multidões, passou Jesus a dizer: Esta é geração perversa! Pede sinal; mas nenhum sinal lhe será dado, senão o de Jonas.

[[v42-11-30]]

^<<v42-11-30,30>>^ Porque, assim como Jonas foi sinal para os ninivitas, o Filho do Homem o será para esta geração.

[[v42-11-31]]

^<<v42-11-31,31>>^ A rainha do Sul se levantará, no Juízo, com os homens desta geração e os condenará; porque veio dos confins da terra para ouvir a sabedoria de Salomão. E eis aqui está quem é maior do que Salomão.

[[v42-11-32]]

^<<v42-11-32,32>>^ Ninivitas se levantarão, no Juízo, com esta geração e a condenarão; porque se arrependeram com a pregação de Jonas. E eis aqui está quem é maior do que Jonas.

[[v42-11-33]]

^<<v42-11-33,33>>^ Ninguém, depois de acender uma candeia, a põe em lugar escondido, nem debaixo do alqueire, mas no velador, a fim de que os que entram vejam a luz.

[[v42-11-34]]

^<<v42-11-34,34>>^ São os teus olhos a lâmpada do teu corpo; se os teus olhos forem bons, todo o teu corpo será luminoso; mas, se forem maus, o teu corpo ficará em trevas.

[[v42-11-35]]

^<<v42-11-35,35>>^ Repara, pois, que a luz que há em ti não sejam trevas.

[[v42-11-36]]

^<<v42-11-36,36>>^ Se, portanto, todo o teu corpo for luminoso, sem ter qualquer parte em trevas, será todo resplandecente como a candeia quando te ilumina em plena luz.

[[v42-11-37]]

^<<v42-11-37,37>>^ Ao falar Jesus estas palavras, um fariseu o convidou para ir comer com ele; então, entrando, tomou lugar à mesa.

[[v42-11-38]]

^<<v42-11-38,38>>^ O fariseu, porém, admirou-se ao ver que Jesus não se lavara primeiro, antes de comer.

[[v42-11-39]]

^<<v42-11-39,39>>^ O Senhor, porém, lhe disse: Vós, fariseus, limpais o exterior do copo e do prato; mas o vosso interior está cheio de rapina e perversidade.

[[v42-11-40]]

^<<v42-11-40,40>>^ Insensatos! Quem fez o exterior não é o mesmo que fez o interior?

[[v42-11-41]]

^<<v42-11-41,41>>^ Antes, dai esmola do que tiverdes, e tudo vos será limpo.

[[v42-11-42]]

^<<v42-11-42,42>>^ Mas ai de vós, fariseus! Porque dais o dízimo da hortelã, da arruda e de todas as hortaliças e desprezais a justiça e o amor de Deus; devíeis, porém, fazer estas coisas, sem omitir aquelas.

[[v42-11-43]]

^<<v42-11-43,43>>^ Ai de vós, fariseus! Porque gostais da primeira cadeira nas sinagogas e das saudações nas praças.

[[v42-11-44]]

^<<v42-11-44,44>>^ Ai de vós que sois como as sepulturas invisíveis, sobre as quais os homens passam sem o saber!

[[v42-11-45]]

^<<v42-11-45,45>>^ Então, respondendo um dos intérpretes da Lei, disse a Jesus: Mestre, dizendo estas coisas, também nos ofendes a nós outros!

[[v42-11-46]]

^<<v42-11-46,46>>^ Mas ele respondeu: Ai de vós também, intérpretes da Lei! Porque sobrecarregais os homens com fardos superiores às suas forças, mas vós mesmos nem com um dedo os tocais.

[[v42-11-47]]

^<<v42-11-47,47>>^ Ai de vós! Porque edificais os túmulos dos profetas que vossos pais assassinaram.

[[v42-11-48]]

^<<v42-11-48,48>>^ Assim, sois testemunhas e aprovais com cumplicidade as obras dos vossos pais; porque eles mataram os profetas, e vós lhes edificais os túmulos.

[[v42-11-49]]

^<<v42-11-49,49>>^ Por isso, também disse a sabedoria de Deus: Enviar-lhes-ei profetas e apóstolos, e a alguns deles matarão e a outros perseguirão,

[[v42-11-50]]

^<<v42-11-50,50>>^ para que desta geração se peçam contas do sangue dos profetas, derramado desde a fundação do mundo;

[[v42-11-51]]

^<<v42-11-51,51>>^ desde o sangue de Abel até ao de Zacarias, que foi assassinado entre o altar e a casa de Deus. Sim, eu vos afirmo, contas serão pedidas a esta geração.

[[v42-11-52]]

^<<v42-11-52,52>>^ Ai de vós, intérpretes da Lei! Porque tomastes a chave da ciência; contudo, vós mesmos não entrastes e impedistes os que estavam entrando.

[[v42-11-53]]

^<<v42-11-53,53>>^ Saindo Jesus dali, passaram os escribas e fariseus a argui-lo com veemência, procurando confundi-lo a respeito de muitos assuntos,

[[v42-11-54]]

^<<v42-11-54,54>>^ com o intuito de tirar das suas próprias palavras motivos para o acusar.

'''

xref:042-lucas/042-lucas-010.adoc#v42-10-0[&#60; Capítulo Anterior] | <<v42-11-0,Topo>> | xref:042-lucas/042-lucas-012.adoc#v42-12-0[Próximo Capítulo &#62;]