include::./index.adoc[]

[[v42-12-0]]
=== Lucas, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-12-1]]

^<<v42-12-1,1>>^ Posto que miríades de pessoas se aglomeraram, a ponto de uns aos outros se atropelarem, passou Jesus a dizer, antes de tudo, aos seus discípulos: Acautelai-vos do fermento dos fariseus, que é a hipocrisia.

[[v42-12-2]]

^<<v42-12-2,2>>^ Nada há encoberto que não venha a ser revelado; e oculto que não venha a ser conhecido.

[[v42-12-3]]

^<<v42-12-3,3>>^ Porque tudo o que dissestes às escuras será ouvido em plena luz; e o que dissestes aos ouvidos no interior da casa será proclamado dos eirados.

[[v42-12-4]]

^<<v42-12-4,4>>^ Digo-vos, pois, amigos meus: não temais os que matam o corpo e, depois disso, nada mais podem fazer.

[[v42-12-5]]

^<<v42-12-5,5>>^ Eu, porém, vos mostrarei a quem deveis temer: temei aquele que, depois de matar, tem poder para lançar no inferno. Sim, digo-vos, a esse deveis temer.

[[v42-12-6]]

^<<v42-12-6,6>>^ Não se vendem cinco pardais por dois asses? Entretanto, nenhum deles está em esquecimento diante de Deus.

[[v42-12-7]]

^<<v42-12-7,7>>^ Até os cabelos da vossa cabeça estão todos contados. Não temais! Bem mais valeis do que muitos pardais.

[[v42-12-8]]

^<<v42-12-8,8>>^ Digo-vos ainda: todo aquele que me confessar diante dos homens, também o Filho do Homem o confessará diante dos anjos de Deus;

[[v42-12-9]]

^<<v42-12-9,9>>^ mas o que me negar diante dos homens será negado diante dos anjos de Deus.

[[v42-12-10]]

^<<v42-12-10,10>>^ Todo aquele que proferir uma palavra contra o Filho do Homem, isso lhe será perdoado; mas, para o que blasfemar contra o Espírito Santo, não haverá perdão.

[[v42-12-11]]

^<<v42-12-11,11>>^ Quando vos levarem às sinagogas e perante os governadores e as autoridades, não vos preocupeis quanto ao modo por que respondereis, nem quanto às coisas que tiverdes de falar.

[[v42-12-12]]

^<<v42-12-12,12>>^ Porque o Espírito Santo vos ensinará, naquela mesma hora, as coisas que deveis dizer.

[[v42-12-13]]

^<<v42-12-13,13>>^ Nesse ponto, um homem que estava no meio da multidão lhe falou: Mestre, ordena a meu irmão que reparta comigo a herança.

[[v42-12-14]]

^<<v42-12-14,14>>^ Mas Jesus lhe respondeu: Homem, quem me constituiu juiz ou partidor entre vós?

[[v42-12-15]]

^<<v42-12-15,15>>^ Então, lhes recomendou: Tende cuidado e guardai-vos de toda e qualquer avareza; porque a vida de um homem não consiste na abundância dos bens que ele possui.

[[v42-12-16]]

^<<v42-12-16,16>>^ E lhes proferiu ainda uma parábola, dizendo: O campo de um homem rico produziu com abundância.

[[v42-12-17]]

^<<v42-12-17,17>>^ E arrazoava consigo mesmo, dizendo: Que farei, pois não tenho onde recolher os meus frutos?

[[v42-12-18]]

^<<v42-12-18,18>>^ E disse: Farei isto: destruirei os meus celeiros, reconstruí-los-ei maiores e aí recolherei todo o meu produto e todos os meus bens.

[[v42-12-19]]

^<<v42-12-19,19>>^ Então, direi à minha alma: tens em depósito muitos bens para muitos anos; descansa, come, bebe e regala-te.

[[v42-12-20]]

^<<v42-12-20,20>>^ Mas Deus lhe disse: Louco, esta noite te pedirão a tua alma; e o que tens preparado, para quem será?

[[v42-12-21]]

^<<v42-12-21,21>>^ Assim é o que entesoura para si mesmo e não é rico para com Deus.

[[v42-12-22]]

^<<v42-12-22,22>>^ A seguir, dirigiu-se Jesus a seus discípulos, dizendo: Por isso, eu vos advirto: não andeis ansiosos pela vossa vida, quanto ao que haveis de comer, nem pelo vosso corpo, quanto ao que haveis de vestir.

[[v42-12-23]]

^<<v42-12-23,23>>^ Porque a vida é mais do que o alimento, e o corpo, mais do que as vestes.

[[v42-12-24]]

^<<v42-12-24,24>>^ Observai os corvos, os quais não semeiam, nem ceifam, não têm despensa nem celeiros; todavia, Deus os sustenta. Quanto mais valeis do que as aves!

[[v42-12-25]]

^<<v42-12-25,25>>^ Qual de vós, por ansioso que esteja, pode acrescentar um côvado ao curso da sua vida?

[[v42-12-26]]

^<<v42-12-26,26>>^ Se, portanto, nada podeis fazer quanto às coisas mínimas, por que andais ansiosos pelas outras?

[[v42-12-27]]

^<<v42-12-27,27>>^ Observai os lírios; eles não fiam, nem tecem. Eu, contudo, vos afirmo que nem Salomão, em toda a sua glória, se vestiu como qualquer deles.

[[v42-12-28]]

^<<v42-12-28,28>>^ Ora, se Deus veste assim a erva que hoje está no campo e amanhã é lançada no forno, quanto mais tratando-se de vós, homens de pequena fé!

[[v42-12-29]]

^<<v42-12-29,29>>^ Não andeis, pois, a indagar o que haveis de comer ou beber e não vos entregueis a inquietações.

[[v42-12-30]]

^<<v42-12-30,30>>^ Porque os gentios de todo o mundo é que procuram estas coisas; mas vosso Pai sabe que necessitais delas.

[[v42-12-31]]

^<<v42-12-31,31>>^ Buscai, antes de tudo, o seu reino, e estas coisas vos serão acrescentadas.

[[v42-12-32]]

^<<v42-12-32,32>>^ Não temais, ó pequenino rebanho; porque vosso Pai se agradou em dar-vos o seu reino.

[[v42-12-33]]

^<<v42-12-33,33>>^ Vendei os vossos bens e dai esmola; fazei para vós outros bolsas que não desgastem, tesouro inextinguível nos céus, onde não chega o ladrão, nem a traça consome,

[[v42-12-34]]

^<<v42-12-34,34>>^ porque, onde está o vosso tesouro, aí estará também o vosso coração.

[[v42-12-35]]

^<<v42-12-35,35>>^ Cingido esteja o vosso corpo, e acesas, as vossas candeias.

[[v42-12-36]]

^<<v42-12-36,36>>^ Sede vós semelhantes a homens que esperam pelo seu senhor, ao voltar ele das festas de casamento; para que, quando vier e bater à porta, logo lha abram.

[[v42-12-37]]

^<<v42-12-37,37>>^ Bem-aventurados aqueles servos a quem o senhor, quando vier, os encontre vigilantes; em verdade vos afirmo que ele há de cingir-se, dar-lhes lugar à mesa e, aproximando-se, os servirá.

[[v42-12-38]]

^<<v42-12-38,38>>^ Quer ele venha na segunda vigília, quer na terceira, bem-aventurados serão eles, se assim os achar.

[[v42-12-39]]

^<<v42-12-39,39>>^ Sabei, porém, isto: se o pai de família soubesse a que hora havia de vir o ladrão, [vigiaria e] não deixaria arrombar a sua casa.

[[v42-12-40]]

^<<v42-12-40,40>>^ Ficai também vós apercebidos, porque, à hora em que não cuidais, o Filho do Homem virá.

[[v42-12-41]]

^<<v42-12-41,41>>^ Então, Pedro perguntou: Senhor, proferes esta parábola para nós ou também para todos?

[[v42-12-42]]

^<<v42-12-42,42>>^ Disse o Senhor: Quem é, pois, o mordomo fiel e prudente, a quem o senhor confiará os seus conservos para dar-lhes o sustento a seu tempo?

[[v42-12-43]]

^<<v42-12-43,43>>^ Bem-aventurado aquele servo a quem seu senhor, quando vier, achar fazendo assim.

[[v42-12-44]]

^<<v42-12-44,44>>^ Verdadeiramente, vos digo que lhe confiará todos os seus bens.

[[v42-12-45]]

^<<v42-12-45,45>>^ Mas, se aquele servo disser consigo mesmo: Meu senhor tarda em vir, e passar a espancar os criados e as criadas, a comer, a beber e a embriagar-se,

[[v42-12-46]]

^<<v42-12-46,46>>^ virá o senhor daquele servo, em dia em que não o espera e em hora que não sabe, e castigá-lo-á, lançando-lhe a sorte com os infiéis.

[[v42-12-47]]

^<<v42-12-47,47>>^ Aquele servo, porém, que conheceu a vontade de seu senhor e não se aprontou, nem fez segundo a sua vontade será punido com muitos açoites.

[[v42-12-48]]

^<<v42-12-48,48>>^ Aquele, porém, que não soube a vontade do seu senhor e fez coisas dignas de reprovação levará poucos açoites. Mas àquele a quem muito foi dado, muito lhe será exigido; e àquele a quem muito se confia, muito mais lhe pedirão.

[[v42-12-49]]

^<<v42-12-49,49>>^ Eu vim para lançar fogo sobre a terra e bem quisera que já estivesse a arder.

[[v42-12-50]]

^<<v42-12-50,50>>^ Tenho, porém, um batismo com o qual hei de ser batizado; e quanto me angustio até que o mesmo se realize!

[[v42-12-51]]

^<<v42-12-51,51>>^ Supondes que vim para dar paz à terra? Não, eu vo-lo afirmo; antes, divisão.

[[v42-12-52]]

^<<v42-12-52,52>>^ Porque, daqui em diante, estarão cinco divididos numa casa: três contra dois, e dois contra três.

[[v42-12-53]]

^<<v42-12-53,53>>^ Estarão divididos: pai contra filho, filho contra pai; mãe contra filha, filha contra mãe; sogra contra nora, e nora contra sogra.

[[v42-12-54]]

^<<v42-12-54,54>>^ Disse também às multidões: Quando vedes aparecer uma nuvem no poente, logo dizeis que vem chuva, e assim acontece;

[[v42-12-55]]

^<<v42-12-55,55>>^ e, quando vedes soprar o vento sul, dizeis que haverá calor, e assim acontece.

[[v42-12-56]]

^<<v42-12-56,56>>^ Hipócritas, sabeis interpretar o aspecto da terra e do céu e, entretanto, não sabeis discernir esta época?

[[v42-12-57]]

^<<v42-12-57,57>>^ E por que não julgais também por vós mesmos o que é justo?

[[v42-12-58]]

^<<v42-12-58,58>>^ Quando fores com o teu adversário ao magistrado, esforça-te para te livrares desse adversário no caminho; para que não suceda que ele te arraste ao juiz, o juiz te entregue ao meirinho e o meirinho te recolha à prisão.

[[v42-12-59]]

^<<v42-12-59,59>>^ Digo-te que não sairás dali enquanto não pagares o último centavo.

'''

xref:042-lucas/042-lucas-011.adoc#v42-11-0[&#60; Capítulo Anterior] | <<v42-12-0,Topo>> | xref:042-lucas/042-lucas-013.adoc#v42-13-0[Próximo Capítulo &#62;]