include::./index.adoc[]

[[v42-14-0]]
=== Lucas, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-14-1]]

^<<v42-14-1,1>>^ Aconteceu que, ao entrar ele num sábado na casa de um dos principais fariseus para comer pão, eis que o estavam observando.

[[v42-14-2]]

^<<v42-14-2,2>>^ Ora, diante dele se achava um homem hidrópico.

[[v42-14-3]]

^<<v42-14-3,3>>^ Então, Jesus, dirigindo-se aos intérpretes da Lei e aos fariseus, perguntou-lhes: É ou não é lícito curar no sábado?

[[v42-14-4]]

^<<v42-14-4,4>>^ Eles, porém, nada disseram. E, tomando-o, o curou e o despediu.

[[v42-14-5]]

^<<v42-14-5,5>>^ A seguir, lhes perguntou: Qual de vós, se o filho ou o boi cair num poço, não o tirará logo, mesmo em dia de sábado?

[[v42-14-6]]

^<<v42-14-6,6>>^ A isto nada puderam responder.

[[v42-14-7]]

^<<v42-14-7,7>>^ Reparando como os convidados escolhiam os primeiros lugares, propôs-lhes uma parábola:

[[v42-14-8]]

^<<v42-14-8,8>>^ Quando por alguém fores convidado para um casamento, não procures o primeiro lugar; para não suceder que, havendo um convidado mais digno do que tu,

[[v42-14-9]]

^<<v42-14-9,9>>^ vindo aquele que te convidou e também a ele, te diga: Dá o lugar a este. Então, irás, envergonhado, ocupar o último lugar.

[[v42-14-10]]

^<<v42-14-10,10>>^ Pelo contrário, quando fores convidado, vai tomar o último lugar; para que, quando vier o que te convidou, te diga: Amigo, senta-te mais para cima. Ser-te-á isto uma honra diante de todos os mais convivas.

[[v42-14-11]]

^<<v42-14-11,11>>^ Pois todo o que se exalta será humilhado; e o que se humilha será exaltado.

[[v42-14-12]]

^<<v42-14-12,12>>^ Disse também ao que o havia convidado: Quando deres um jantar ou uma ceia, não convides os teus amigos, nem teus irmãos, nem teus parentes, nem vizinhos ricos; para não suceder que eles, por sua vez, te convidem e sejas recompensado.

[[v42-14-13]]

^<<v42-14-13,13>>^ Antes, ao dares um banquete, convida os pobres, os aleijados, os coxos e os cegos;

[[v42-14-14]]

^<<v42-14-14,14>>^ e serás bem-aventurado, pelo fato de não terem eles com que recompensar-te; a tua recompensa, porém, tu a receberás na ressurreição dos justos.

[[v42-14-15]]

^<<v42-14-15,15>>^ Ora, ouvindo tais palavras, um dos que estavam com ele à mesa, disse-lhe: Bem-aventurado aquele que comer pão no reino de Deus.

[[v42-14-16]]

^<<v42-14-16,16>>^ Ele, porém, respondeu: Certo homem deu uma grande ceia e convidou muitos.

[[v42-14-17]]

^<<v42-14-17,17>>^ À hora da ceia, enviou o seu servo para avisar aos convidados: Vinde, porque tudo já está preparado.

[[v42-14-18]]

^<<v42-14-18,18>>^ Não obstante, todos, à uma, começaram a escusar-se. Disse o primeiro: Comprei um campo e preciso ir vê-lo; rogo-te que me tenhas por escusado.

[[v42-14-19]]

^<<v42-14-19,19>>^ Outro disse: Comprei cinco juntas de bois e vou experimentá-las; rogo-te que me tenhas por escusado.

[[v42-14-20]]

^<<v42-14-20,20>>^ E outro disse: Casei-me e, por isso, não posso ir.

[[v42-14-21]]

^<<v42-14-21,21>>^ Voltando o servo, tudo contou ao seu senhor. Então, irado, o dono da casa disse ao seu servo: Sai depressa para as ruas e becos da cidade e traze para aqui os pobres, os aleijados, os cegos e os coxos.

[[v42-14-22]]

^<<v42-14-22,22>>^ Depois, lhe disse o servo: Senhor, feito está como mandaste, e ainda há lugar.

[[v42-14-23]]

^<<v42-14-23,23>>^ Respondeu-lhe o senhor: Sai pelos caminhos e atalhos e obriga a todos a entrar, para que fique cheia a minha casa.

[[v42-14-24]]

^<<v42-14-24,24>>^ Porque vos declaro que nenhum daqueles homens que foram convidados provará a minha ceia.

[[v42-14-25]]

^<<v42-14-25,25>>^ Grandes multidões o acompanhavam, e ele, voltando-se, lhes disse:

[[v42-14-26]]

^<<v42-14-26,26>>^ Se alguém vem a mim e não aborrece a seu pai, e mãe, e mulher, e filhos, e irmãos, e irmãs e ainda a sua própria vida, não pode ser meu discípulo.

[[v42-14-27]]

^<<v42-14-27,27>>^ E qualquer que não tomar a sua cruz e vier após mim não pode ser meu discípulo.

[[v42-14-28]]

^<<v42-14-28,28>>^ Pois qual de vós, pretendendo construir uma torre, não se assenta primeiro para calcular a despesa e verificar se tem os meios para a concluir?

[[v42-14-29]]

^<<v42-14-29,29>>^ Para não suceder que, tendo lançado os alicerces e não a podendo acabar, todos os que a virem zombem dele,

[[v42-14-30]]

^<<v42-14-30,30>>^ dizendo: Este homem começou a construir e não pôde acabar.

[[v42-14-31]]

^<<v42-14-31,31>>^ Ou qual é o rei que, indo para combater outro rei, não se assenta primeiro para calcular se com dez mil homens poderá enfrentar o que vem contra ele com vinte mil?

[[v42-14-32]]

^<<v42-14-32,32>>^ Caso contrário, estando o outro ainda longe, envia-lhe uma embaixada, pedindo condições de paz.

[[v42-14-33]]

^<<v42-14-33,33>>^ Assim, pois, todo aquele que dentre vós não renuncia a tudo quanto tem não pode ser meu discípulo.

[[v42-14-34]]

^<<v42-14-34,34>>^ O sal é certamente bom; caso, porém, se torne insípido, como restaurar-lhe o sabor?

[[v42-14-35]]

^<<v42-14-35,35>>^ Nem presta para a terra, nem mesmo para o monturo; lançam-no fora. Quem tem ouvidos para ouvir, ouça.

'''

xref:042-lucas/042-lucas-013.adoc#v42-13-0[&#60; Capítulo Anterior] | <<v42-14-0,Topo>> | xref:042-lucas/042-lucas-015.adoc#v42-15-0[Próximo Capítulo &#62;]