include::./index.adoc[]

[[v42-8-0]]
=== Lucas, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-8-1]]

^<<v42-8-1,1>>^ Aconteceu, depois disto, que andava Jesus de cidade em cidade e de aldeia em aldeia, pregando e anunciando o evangelho do reino de Deus, e os doze iam com ele,

[[v42-8-2]]

^<<v42-8-2,2>>^ e também algumas mulheres que haviam sido curadas de espíritos malignos e de enfermidades: Maria, chamada Madalena, da qual saíram sete demônios;

[[v42-8-3]]

^<<v42-8-3,3>>^ e Joana, mulher de Cuza, procurador de Herodes, Suzana e muitas outras, as quais lhe prestavam assistência com os seus bens.

[[v42-8-4]]

^<<v42-8-4,4>>^ Afluindo uma grande multidão e vindo ter com ele gente de todas as cidades, disse Jesus por parábola:

[[v42-8-5]]

^<<v42-8-5,5>>^ Eis que o semeador saiu a semear. E, ao semear, uma parte caiu à beira do caminho; foi pisada, e as aves do céu a comeram.

[[v42-8-6]]

^<<v42-8-6,6>>^ Outra caiu sobre a pedra; e, tendo crescido, secou por falta de umidade.

[[v42-8-7]]

^<<v42-8-7,7>>^ Outra caiu no meio dos espinhos; e estes, ao crescerem com ela, a sufocaram.

[[v42-8-8]]

^<<v42-8-8,8>>^ Outra, afinal, caiu em boa terra; cresceu e produziu a cento por um.  Dizendo isto, clamou: Quem tem ouvidos para ouvir, ouça.

[[v42-8-9]]

^<<v42-8-9,9>>^ E os seus discípulos o interrogaram, dizendo: Que parábola é esta?

[[v42-8-10]]

^<<v42-8-10,10>>^ Respondeu-lhes Jesus: A vós outros é dado conhecer os mistérios do reino de Deus; aos demais, fala-se por parábolas, para que, vendo, não vejam; e, ouvindo, não entendam.

[[v42-8-11]]

^<<v42-8-11,11>>^ Este é o sentido da parábola: a semente é a palavra de Deus.

[[v42-8-12]]

^<<v42-8-12,12>>^ A que caiu à beira do caminho são os que a ouviram; vem, a seguir, o diabo e arrebata-lhes do coração a palavra, para não suceder que, crendo, sejam salvos.

[[v42-8-13]]

^<<v42-8-13,13>>^ A que caiu sobre a pedra são os que, ouvindo a palavra, a recebem com alegria; estes não têm raiz, creem apenas por algum tempo e, na hora da provação, se desviam.

[[v42-8-14]]

^<<v42-8-14,14>>^ A que caiu entre espinhos são os que ouviram e, no decorrer dos dias, foram sufocados com os cuidados, riquezas e deleites da vida; os seus frutos não chegam a amadurecer.

[[v42-8-15]]

^<<v42-8-15,15>>^ A que caiu na boa terra são os que, tendo ouvido de bom e reto coração, retêm a palavra; estes frutificam com perseverança.

[[v42-8-16]]

^<<v42-8-16,16>>^ Ninguém, depois de acender uma candeia, a cobre com um vaso ou a põe debaixo de uma cama; pelo contrário, coloca-a sobre um velador, a fim de que os que entram vejam a luz.

[[v42-8-17]]

^<<v42-8-17,17>>^ Nada há oculto, que não haja de manifestar-se, nem escondido, que não venha a ser conhecido e revelado.

[[v42-8-18]]

^<<v42-8-18,18>>^ Vede, pois, como ouvis; porque ao que tiver, se lhe dará; e ao que não tiver, até aquilo que julga ter lhe será tirado.

[[v42-8-19]]

^<<v42-8-19,19>>^ Vieram ter com ele sua mãe e seus irmãos e não podiam aproximar-se por causa da concorrência de povo.

[[v42-8-20]]

^<<v42-8-20,20>>^ E lhe comunicaram: Tua mãe e teus irmãos estão lá fora e querem ver-te.

[[v42-8-21]]

^<<v42-8-21,21>>^ Ele, porém, lhes respondeu: Minha mãe e meus irmãos são aqueles que ouvem a palavra de Deus e a praticam.

[[v42-8-22]]

^<<v42-8-22,22>>^ Aconteceu que, num daqueles dias, entrou ele num barco em companhia dos seus discípulos e disse-lhes: Passemos para a outra margem do lago;  e partiram.

[[v42-8-23]]

^<<v42-8-23,23>>^ Enquanto navegavam, ele adormeceu. E sobreveio uma tempestade de vento no lago, correndo eles o perigo de soçobrar.

[[v42-8-24]]

^<<v42-8-24,24>>^ Chegando-se a ele, despertaram-no dizendo: Mestre, Mestre, estamos perecendo! Despertando-se Jesus, repreendeu o vento e a fúria da água. Tudo cessou, e veio a bonança.

[[v42-8-25]]

^<<v42-8-25,25>>^ Então, lhes disse: Onde está a vossa fé?  Eles, possuídos de temor e admiração, diziam uns aos outros: Quem é este que até aos ventos e às ondas repreende, e lhe obedecem?

[[v42-8-26]]

^<<v42-8-26,26>>^ Então, rumaram para a terra dos gerasenos, fronteira da Galileia.

[[v42-8-27]]

^<<v42-8-27,27>>^ Logo ao desembarcar, veio da cidade ao seu encontro um homem possesso de demônios que, havia muito, não se vestia, nem habitava em casa alguma, porém vivia nos sepulcros.

[[v42-8-28]]

^<<v42-8-28,28>>^ E, quando viu a Jesus, prostrou-se diante dele, exclamando e dizendo em alta voz: Que tenho eu contigo, Jesus, Filho do Deus Altíssimo? Rogo-te que não me atormentes.

[[v42-8-29]]

^<<v42-8-29,29>>^ Porque Jesus ordenara ao espírito imundo que saísse do homem, pois muitas vezes se apoderara dele. E, embora procurassem conservá-lo preso com cadeias e grilhões, tudo despedaçava e era impelido pelo demônio para o deserto.

[[v42-8-30]]

^<<v42-8-30,30>>^ Perguntou-lhe Jesus: Qual é o teu nome?  Respondeu ele: Legião, porque tinham entrado nele muitos demônios.

[[v42-8-31]]

^<<v42-8-31,31>>^ Rogavam-lhe que não os mandasse sair para o abismo.

[[v42-8-32]]

^<<v42-8-32,32>>^ Ora, andava ali, pastando no monte, uma grande manada de porcos; rogaram-lhe que lhes permitisse entrar naqueles porcos. E Jesus o permitiu.

[[v42-8-33]]

^<<v42-8-33,33>>^ Tendo os demônios saído do homem, entraram nos porcos, e a manada precipitou-se despenhadeiro abaixo, para dentro do lago, e se afogou.

[[v42-8-34]]

^<<v42-8-34,34>>^ Os porqueiros, vendo o que acontecera, fugiram e foram anunciá-lo na cidade e pelos campos.

[[v42-8-35]]

^<<v42-8-35,35>>^ Então, saiu o povo para ver o que se passara, e foram ter com Jesus. De fato, acharam o homem de quem saíram os demônios, vestido, em perfeito juízo, assentado aos pés de Jesus; e ficaram dominados de terror.

[[v42-8-36]]

^<<v42-8-36,36>>^ E algumas pessoas que tinham presenciado os fatos contaram-lhes também como fora salvo o endemoninhado.

[[v42-8-37]]

^<<v42-8-37,37>>^ Todo o povo da circunvizinhança dos gerasenos rogou-lhe que se retirasse deles, pois estavam possuídos de grande medo. E Jesus, tomando de novo o barco, voltou.

[[v42-8-38]]

^<<v42-8-38,38>>^ O homem de quem tinham saído os demônios rogou-lhe que o deixasse estar com ele; Jesus, porém, o despediu, dizendo:

[[v42-8-39]]

^<<v42-8-39,39>>^ Volta para casa e conta aos teus tudo o que Deus fez por ti.  Então, foi ele anunciando por toda a cidade todas as coisas que Jesus lhe tinha feito.

[[v42-8-40]]

^<<v42-8-40,40>>^ Ao regressar Jesus, a multidão o recebeu com alegria, porque todos o estavam esperando.

[[v42-8-41]]

^<<v42-8-41,41>>^ Eis que veio um homem chamado Jairo, que era chefe da sinagoga, e, prostrando-se aos pés de Jesus, lhe suplicou que chegasse até a sua casa.

[[v42-8-42]]

^<<v42-8-42,42>>^ Pois tinha uma filha única de uns doze anos, que estava à morte. Enquanto ele ia, as multidões o apertavam.

[[v42-8-43]]

^<<v42-8-43,43>>^ Certa mulher que, havia doze anos, vinha sofrendo de uma hemorragia, e a quem ninguém tinha podido curar [e que gastara com os médicos todos os seus haveres],

[[v42-8-44]]

^<<v42-8-44,44>>^ veio por trás dele e lhe tocou na orla da veste, e logo se lhe estancou a hemorragia.

[[v42-8-45]]

^<<v42-8-45,45>>^ Mas Jesus disse: Quem me tocou?  Como todos negassem, Pedro [com seus companheiros] disse: Mestre, as multidões te apertam e te oprimem [e dizes: Quem me tocou?].

[[v42-8-46]]

^<<v42-8-46,46>>^ Contudo, Jesus insistiu: Alguém me tocou, porque senti que de mim saiu poder.

[[v42-8-47]]

^<<v42-8-47,47>>^ Vendo a mulher que não podia ocultar-se, aproximou-se trêmula e, prostrando-se diante dele, declarou, à vista de todo o povo, a causa por que lhe havia tocado e como imediatamente fora curada.

[[v42-8-48]]

^<<v42-8-48,48>>^ Então, lhe disse: Filha, a tua fé te salvou; vai-te em paz.

[[v42-8-49]]

^<<v42-8-49,49>>^ Falava ele ainda, quando veio uma pessoa da casa do chefe da sinagoga, dizendo: Tua filha já está morta, não incomodes mais o Mestre.

[[v42-8-50]]

^<<v42-8-50,50>>^ Mas Jesus, ouvindo isto, lhe disse: Não temas, crê somente, e ela será salva.

[[v42-8-51]]

^<<v42-8-51,51>>^ Tendo chegado à casa, a ninguém permitiu que entrasse com ele, senão Pedro, João, Tiago e bem assim o pai e a mãe da menina.

[[v42-8-52]]

^<<v42-8-52,52>>^ E todos choravam e a pranteavam. Mas ele disse: Não choreis; ela não está morta, mas dorme.

[[v42-8-53]]

^<<v42-8-53,53>>^ E riam-se dele, porque sabiam que ela estava morta.

[[v42-8-54]]

^<<v42-8-54,54>>^ Entretanto, ele, tomando-a pela mão, disse-lhe, em voz alta: Menina, levanta-te!

[[v42-8-55]]

^<<v42-8-55,55>>^ Voltou-lhe o espírito, ela imediatamente se levantou, e ele mandou que lhe dessem de comer.

[[v42-8-56]]

^<<v42-8-56,56>>^ Seus pais ficaram maravilhados, mas ele lhes advertiu que a ninguém contassem o que havia acontecido.

'''

xref:042-lucas/042-lucas-007.adoc#v42-7-0[&#60; Capítulo Anterior] | <<v42-8-0,Topo>> | xref:042-lucas/042-lucas-009.adoc#v42-9-0[Próximo Capítulo &#62;]