include::./index.adoc[]

[[v42-9-0]]
=== Lucas, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-9-1]]

^<<v42-9-1,1>>^ Tendo Jesus convocado os doze, deu-lhes poder e autoridade sobre todos os demônios, e para efetuarem curas.

[[v42-9-2]]

^<<v42-9-2,2>>^ Também os enviou a pregar o reino de Deus e a curar os enfermos.

[[v42-9-3]]

^<<v42-9-3,3>>^ E disse-lhes: Nada leveis para o caminho: nem bordão, nem alforje, nem pão, nem dinheiro; nem deveis ter duas túnicas.

[[v42-9-4]]

^<<v42-9-4,4>>^ Na casa em que entrardes, ali permanecei e dali saireis.

[[v42-9-5]]

^<<v42-9-5,5>>^ E onde quer que não vos receberem, ao sairdes daquela cidade, sacudi o pó dos vossos pés em testemunho contra eles.

[[v42-9-6]]

^<<v42-9-6,6>>^ Então, saindo, percorriam todas as aldeias, anunciando o evangelho e efetuando curas por toda parte.

[[v42-9-7]]

^<<v42-9-7,7>>^ Ora, o tetrarca Herodes soube de tudo o que se passava e ficou perplexo, porque alguns diziam: João ressuscitou dentre os mortos;

[[v42-9-8]]

^<<v42-9-8,8>>^ outros: Elias apareceu; e outros: Ressurgiu um dos antigos profetas.

[[v42-9-9]]

^<<v42-9-9,9>>^ Herodes, porém, disse: Eu mandei decapitar a João; quem é, pois, este a respeito do qual tenho ouvido tais coisas? E se esforçava por vê-lo.

[[v42-9-10]]

^<<v42-9-10,10>>^ Ao regressarem, os apóstolos relataram a Jesus tudo o que tinham feito. E, levando-os consigo, retirou-se à parte para uma cidade chamada Betsaida.

[[v42-9-11]]

^<<v42-9-11,11>>^ Mas as multidões, ao saberem, seguiram-no. Acolhendo-as, falava-lhes a respeito do reino de Deus e socorria os que tinham necessidade de cura.

[[v42-9-12]]

^<<v42-9-12,12>>^ Mas o dia começava a declinar. Então, se aproximaram os doze e lhe disseram: Despede a multidão, para que, indo às aldeias e campos circunvizinhos, se hospedem e achem alimento; pois estamos aqui em lugar deserto.

[[v42-9-13]]

^<<v42-9-13,13>>^ Ele, porém, lhes disse: Dai-lhes vós mesmos de comer.  Responderam eles: Não temos mais que cinco pães e dois peixes, salvo se nós mesmos formos comprar comida para todo este povo.

[[v42-9-14]]

^<<v42-9-14,14>>^ Porque estavam ali cerca de cinco mil homens. Então, disse aos seus discípulos: Fazei-os sentar-se em grupos de cinquenta.

[[v42-9-15]]

^<<v42-9-15,15>>^ Eles atenderam, acomodando a todos.

[[v42-9-16]]

^<<v42-9-16,16>>^ E, tomando os cinco pães e os dois peixes, erguendo os olhos para o céu, os abençoou, partiu e deu aos discípulos para que os distribuíssem entre o povo.

[[v42-9-17]]

^<<v42-9-17,17>>^ Todos comeram e se fartaram; e dos pedaços que ainda sobejaram foram recolhidos doze cestos.

[[v42-9-18]]

^<<v42-9-18,18>>^ Estando ele orando à parte, achavam-se presentes os discípulos, a quem perguntou: Quem dizem as multidões que sou eu?

[[v42-9-19]]

^<<v42-9-19,19>>^ Responderam eles: João Batista, mas outros, Elias; e ainda outros dizem que ressurgiu um dos antigos profetas.

[[v42-9-20]]

^<<v42-9-20,20>>^ Mas vós,  perguntou ele, quem dizeis que eu sou?  Então, falou Pedro e disse: És o Cristo de Deus.

[[v42-9-21]]

^<<v42-9-21,21>>^ Ele, porém, advertindo-os, mandou que a ninguém declarassem tal coisa,

[[v42-9-22]]

^<<v42-9-22,22>>^ dizendo: É necessário que o Filho do Homem sofra muitas coisas, seja rejeitado pelos anciãos, pelos principais sacerdotes e pelos escribas; seja morto e, no terceiro dia, ressuscite.

[[v42-9-23]]

^<<v42-9-23,23>>^ Dizia a todos: Se alguém quer vir após mim, a si mesmo se negue, dia a dia tome a sua cruz e siga-me.

[[v42-9-24]]

^<<v42-9-24,24>>^ Pois quem quiser salvar a sua vida perdê-la-á; quem perder a vida por minha causa, esse a salvará.

[[v42-9-25]]

^<<v42-9-25,25>>^ Que aproveita ao homem ganhar o mundo inteiro, se vier a perder-se ou a causar dano a si mesmo?

[[v42-9-26]]

^<<v42-9-26,26>>^ Porque qualquer que de mim e das minhas palavras se envergonhar, dele se envergonhará o Filho do Homem, quando vier na sua glória e na do Pai e dos santos anjos.

[[v42-9-27]]

^<<v42-9-27,27>>^ Verdadeiramente, vos digo: alguns há dos que aqui se encontram que, de maneira nenhuma, passarão pela morte até que vejam o reino de Deus.

[[v42-9-28]]

^<<v42-9-28,28>>^ Cerca de oito dias depois de proferidas estas palavras, tomando consigo a Pedro, João e Tiago, subiu ao monte com o propósito de orar.

[[v42-9-29]]

^<<v42-9-29,29>>^ E aconteceu que, enquanto ele orava, a aparência do seu rosto se transfigurou e suas vestes resplandeceram de brancura.

[[v42-9-30]]

^<<v42-9-30,30>>^ Eis que dois varões falavam com ele: Moisés e Elias,

[[v42-9-31]]

^<<v42-9-31,31>>^ os quais apareceram em glória e falavam da sua partida, que ele estava para cumprir em Jerusalém.

[[v42-9-32]]

^<<v42-9-32,32>>^ Pedro e seus companheiros achavam-se premidos de sono; mas, conservando-se acordados, viram a sua glória e os dois varões que com ele estavam.

[[v42-9-33]]

^<<v42-9-33,33>>^ Ao se retirarem estes de Jesus, disse-lhe Pedro: Mestre, bom é estarmos aqui; então, façamos três tendas: uma será tua, outra, de Moisés, e outra, de Elias, não sabendo, porém, o que dizia.

[[v42-9-34]]

^<<v42-9-34,34>>^ Enquanto assim falava, veio uma nuvem e os envolveu; e encheram-se de medo ao entrarem na nuvem.

[[v42-9-35]]

^<<v42-9-35,35>>^ E dela veio uma voz, dizendo: Este é o meu Filho, o meu eleito; a ele ouvi.

[[v42-9-36]]

^<<v42-9-36,36>>^ Depois daquela voz, achou-se Jesus sozinho. Eles calaram-se e, naqueles dias, a ninguém contaram coisa alguma do que tinham visto.

[[v42-9-37]]

^<<v42-9-37,37>>^ No dia seguinte, ao descerem eles do monte, veio ao encontro de Jesus grande multidão.

[[v42-9-38]]

^<<v42-9-38,38>>^ E eis que, dentre a multidão, surgiu um homem, dizendo em alta voz: Mestre, suplico-te que vejas meu filho, porque é o único;

[[v42-9-39]]

^<<v42-9-39,39>>^ um espírito se apodera dele, e, de repente, o menino grita, e o espírito o atira por terra, convulsiona-o até espumar; e dificilmente o deixa, depois de o ter quebrantado.

[[v42-9-40]]

^<<v42-9-40,40>>^ Roguei aos teus discípulos que o expelissem, mas eles não puderam.

[[v42-9-41]]

^<<v42-9-41,41>>^ Respondeu Jesus: Ó geração incrédula e perversa! Até quando estarei convosco e vos sofrerei? Traze o teu filho.

[[v42-9-42]]

^<<v42-9-42,42>>^ Quando se ia aproximando, o demônio o atirou no chão e o convulsionou; mas Jesus repreendeu o espírito imundo, curou o menino e o entregou a seu pai.

[[v42-9-43]]

^<<v42-9-43,43>>^ E todos ficaram maravilhados ante a majestade de Deus. Como todos se maravilhassem de quanto Jesus fazia, disse aos seus discípulos:

[[v42-9-44]]

^<<v42-9-44,44>>^ Fixai nos vossos ouvidos as seguintes palavras: o Filho do Homem está para ser entregue nas mãos dos homens.

[[v42-9-45]]

^<<v42-9-45,45>>^ Eles, porém, não entendiam isto, e foi-lhes encoberto para que o não compreendessem; e temiam interrogá-lo a este respeito.

[[v42-9-46]]

^<<v42-9-46,46>>^ Levantou-se entre eles uma discussão sobre qual deles seria o maior.

[[v42-9-47]]

^<<v42-9-47,47>>^ Mas Jesus, sabendo o que se lhes passava no coração, tomou uma criança, colocou-a junto a si

[[v42-9-48]]

^<<v42-9-48,48>>^ e lhes disse: Quem receber esta criança em meu nome a mim me recebe; e quem receber a mim recebe aquele que me enviou; porque aquele que entre vós for o menor de todos, esse é que é grande.

[[v42-9-49]]

^<<v42-9-49,49>>^ Falou João e disse: Mestre, vimos certo homem que, em teu nome, expelia demônios e lho proibimos, porque não segue conosco.

[[v42-9-50]]

^<<v42-9-50,50>>^ Mas Jesus lhe disse: Não proibais; pois quem não é contra vós outros é por vós.

[[v42-9-51]]

^<<v42-9-51,51>>^ E aconteceu que, ao se completarem os dias em que devia ele ser assunto ao céu, manifestou, no semblante, a intrépida resolução de ir para Jerusalém

[[v42-9-52]]

^<<v42-9-52,52>>^ e enviou mensageiros que o antecedessem. Indo eles, entraram numa aldeia de samaritanos para lhe preparar pousada.

[[v42-9-53]]

^<<v42-9-53,53>>^ Mas não o receberam, porque o aspecto dele era de quem, decisivamente, ia para Jerusalém.

[[v42-9-54]]

^<<v42-9-54,54>>^ Vendo isto, os discípulos Tiago e João perguntaram: Senhor, queres que mandemos descer fogo do céu para os consumir?

[[v42-9-55]]

^<<v42-9-55,55>>^ Jesus, porém, voltando-se os repreendeu [e disse: Vós não sabeis de que espírito sois].

[[v42-9-56]]

^<<v42-9-56,56>>^ [Pois o Filho do Homem não veio para destruir as almas dos homens, mas para salvá-las.]  E seguiram para outra aldeia.

[[v42-9-57]]

^<<v42-9-57,57>>^ Indo eles caminho fora, alguém lhe disse: Seguir-te-ei para onde quer que fores.

[[v42-9-58]]

^<<v42-9-58,58>>^ Mas Jesus lhe respondeu: As raposas têm seus covis, e as aves do céu, ninhos; mas o Filho do Homem não tem onde reclinar a cabeça.

[[v42-9-59]]

^<<v42-9-59,59>>^ A outro disse Jesus: Segue-me!  Ele, porém, respondeu: Permite-me ir primeiro sepultar meu pai.

[[v42-9-60]]

^<<v42-9-60,60>>^ Mas Jesus insistiu: Deixa aos mortos o sepultar os seus próprios mortos. Tu, porém, vai e prega o reino de Deus.

[[v42-9-61]]

^<<v42-9-61,61>>^ Outro lhe disse: Seguir-te-ei, Senhor; mas deixa-me primeiro despedir-me dos de casa.

[[v42-9-62]]

^<<v42-9-62,62>>^ Mas Jesus lhe replicou: Ninguém que, tendo posto a mão no arado, olha para trás é apto para o reino de Deus.

'''

xref:042-lucas/042-lucas-008.adoc#v42-8-0[&#60; Capítulo Anterior] | <<v42-9-0,Topo>> | xref:042-lucas/042-lucas-010.adoc#v42-10-0[Próximo Capítulo &#62;]