include::./index.adoc[]

[[v42-15-0]]
=== Lucas, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-15-1]]

^<<v42-15-1,1>>^ Aproximavam-se de Jesus todos os publicanos e pecadores para o ouvir.

[[v42-15-2]]

^<<v42-15-2,2>>^ E murmuravam os fariseus e os escribas, dizendo: Este recebe pecadores e come com eles.

[[v42-15-3]]

^<<v42-15-3,3>>^ Então, lhes propôs Jesus esta parábola:

[[v42-15-4]]

^<<v42-15-4,4>>^ Qual, dentre vós, é o homem que, possuindo cem ovelhas e perdendo uma delas, não deixa no deserto as noventa e nove e vai em busca da que se perdeu, até encontrá-la?

[[v42-15-5]]

^<<v42-15-5,5>>^ Achando-a, põe-na sobre os ombros, cheio de júbilo.

[[v42-15-6]]

^<<v42-15-6,6>>^ E, indo para casa, reúne os amigos e vizinhos, dizendo-lhes: Alegrai-vos comigo, porque já achei a minha ovelha perdida.

[[v42-15-7]]

^<<v42-15-7,7>>^ Digo-vos que, assim, haverá maior júbilo no céu por um pecador que se arrepende do que por noventa e nove justos que não necessitam de arrependimento.

[[v42-15-8]]

^<<v42-15-8,8>>^ Ou qual é a mulher que, tendo dez dracmas, se perder uma, não acende a candeia, varre a casa e a procura diligentemente até encontrá-la?

[[v42-15-9]]

^<<v42-15-9,9>>^ E, tendo-a achado, reúne as amigas e vizinhas, dizendo: Alegrai-vos comigo, porque achei a dracma que eu tinha perdido.

[[v42-15-10]]

^<<v42-15-10,10>>^ Eu vos afirmo que, de igual modo, há júbilo diante dos anjos de Deus por um pecador que se arrepende.

[[v42-15-11]]

^<<v42-15-11,11>>^ Continuou: Certo homem tinha dois filhos;

[[v42-15-12]]

^<<v42-15-12,12>>^ o mais moço deles disse ao pai: Pai, dá-me a parte dos bens que me cabe. E ele lhes repartiu os haveres.

[[v42-15-13]]

^<<v42-15-13,13>>^ Passados não muitos dias, o filho mais moço, ajuntando tudo o que era seu, partiu para uma terra distante e lá dissipou todos os seus bens, vivendo dissolutamente.

[[v42-15-14]]

^<<v42-15-14,14>>^ Depois de ter consumido tudo, sobreveio àquele país uma grande fome, e ele começou a passar necessidade.

[[v42-15-15]]

^<<v42-15-15,15>>^ Então, ele foi e se agregou a um dos cidadãos daquela terra, e este o mandou para os seus campos a guardar porcos.

[[v42-15-16]]

^<<v42-15-16,16>>^ Ali, desejava ele fartar-se das alfarrobas que os porcos comiam; mas ninguém lhe dava nada.

[[v42-15-17]]

^<<v42-15-17,17>>^ Então, caindo em si, disse: Quantos trabalhadores de meu pai têm pão com fartura, e eu aqui morro de fome!

[[v42-15-18]]

^<<v42-15-18,18>>^ Levantar-me-ei, e irei ter com o meu pai, e lhe direi: Pai, pequei contra o céu e diante de ti;

[[v42-15-19]]

^<<v42-15-19,19>>^ já não sou digno de ser chamado teu filho; trata-me como um dos teus trabalhadores.

[[v42-15-20]]

^<<v42-15-20,20>>^ E, levantando-se, foi para seu pai. Vinha ele ainda longe, quando seu pai o avistou, e, compadecido dele, correndo, o abraçou, e beijou.

[[v42-15-21]]

^<<v42-15-21,21>>^ E o filho lhe disse: Pai, pequei contra o céu e diante de ti; já não sou digno de ser chamado teu filho.

[[v42-15-22]]

^<<v42-15-22,22>>^ O pai, porém, disse aos seus servos: Trazei depressa a melhor roupa, vesti-o, ponde-lhe um anel no dedo e sandálias nos pés;

[[v42-15-23]]

^<<v42-15-23,23>>^ trazei também e matai o novilho cevado. Comamos e regozijemo-nos,

[[v42-15-24]]

^<<v42-15-24,24>>^ porque este meu filho estava morto e reviveu, estava perdido e foi achado. E começaram a regozijar-se.

[[v42-15-25]]

^<<v42-15-25,25>>^ Ora, o filho mais velho estivera no campo; e, quando voltava, ao aproximar-se da casa, ouviu a música e as danças.

[[v42-15-26]]

^<<v42-15-26,26>>^ Chamou um dos criados e perguntou-lhe que era aquilo.

[[v42-15-27]]

^<<v42-15-27,27>>^ E ele informou: Veio teu irmão, e teu pai mandou matar o novilho cevado, porque o recuperou com saúde.

[[v42-15-28]]

^<<v42-15-28,28>>^ Ele se indignou e não queria entrar; saindo, porém, o pai, procurava conciliá-lo.

[[v42-15-29]]

^<<v42-15-29,29>>^ Mas ele respondeu a seu pai: Há tantos anos que te sirvo sem jamais transgredir uma ordem tua, e nunca me deste um cabrito sequer para alegrar-me com os meus amigos;

[[v42-15-30]]

^<<v42-15-30,30>>^ vindo, porém, esse teu filho, que desperdiçou os teus bens com meretrizes, tu mandaste matar para ele o novilho cevado.

[[v42-15-31]]

^<<v42-15-31,31>>^ Então, lhe respondeu o pai: Meu filho, tu sempre estás comigo; tudo o que é meu é teu.

[[v42-15-32]]

^<<v42-15-32,32>>^ Entretanto, era preciso que nos regozijássemos e nos alegrássemos, porque esse teu irmão estava morto e reviveu, estava perdido e foi achado.

'''

xref:042-lucas/042-lucas-014.adoc#v42-14-0[&#60; Capítulo Anterior] | <<v42-15-0,Topo>> | xref:042-lucas/042-lucas-016.adoc#v42-16-0[Próximo Capítulo &#62;]