include::./index.adoc[]

[[v42-4-0]]
=== Lucas, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-4-1]]

^<<v42-4-1,1>>^ Jesus, cheio do Espírito Santo, voltou do Jordão e foi guiado pelo mesmo Espírito, no deserto,

[[v42-4-2]]

^<<v42-4-2,2>>^ durante quarenta dias, sendo tentado pelo diabo. Nada comeu naqueles dias, ao fim dos quais teve fome.

[[v42-4-3]]

^<<v42-4-3,3>>^ Disse-lhe, então, o diabo: Se és o Filho de Deus, manda que esta pedra se transforme em pão.

[[v42-4-4]]

^<<v42-4-4,4>>^ Mas Jesus lhe respondeu: Está escrito: Não só de pão viverá o homem.

[[v42-4-5]]

^<<v42-4-5,5>>^ E, elevando-o, mostrou-lhe, num momento, todos os reinos do mundo.

[[v42-4-6]]

^<<v42-4-6,6>>^ Disse-lhe o diabo: Dar-te-ei toda esta autoridade e a glória destes reinos, porque ela me foi entregue, e a dou a quem eu quiser.

[[v42-4-7]]

^<<v42-4-7,7>>^ Portanto, se prostrado me adorares, toda será tua.

[[v42-4-8]]

^<<v42-4-8,8>>^ Mas Jesus lhe respondeu: Está escrito: Ao Senhor, teu Deus, adorarás e só a ele darás culto.

[[v42-4-9]]

^<<v42-4-9,9>>^ Então, o levou a Jerusalém, e o colocou sobre o pináculo do templo, e disse: Se és o Filho de Deus, atira-te daqui abaixo;

[[v42-4-10]]

^<<v42-4-10,10>>^ porque está escrito: Aos seus anjos ordenará a teu respeito que te guardem;

[[v42-4-11]]

^<<v42-4-11,11>>^ e: Eles te susterão nas suas mãos, para não tropeçares nalguma pedra.

[[v42-4-12]]

^<<v42-4-12,12>>^ Respondeu-lhe Jesus: Dito está: Não tentarás o Senhor, teu Deus.

[[v42-4-13]]

^<<v42-4-13,13>>^ Passadas que foram as tentações de toda sorte, apartou-se dele o diabo, até momento oportuno.

[[v42-4-14]]

^<<v42-4-14,14>>^ Então, Jesus, no poder do Espírito, regressou para a Galileia, e a sua fama correu por toda a circunvizinhança.

[[v42-4-15]]

^<<v42-4-15,15>>^ E ensinava nas sinagogas, sendo glorificado por todos.

[[v42-4-16]]

^<<v42-4-16,16>>^ Indo para Nazaré, onde fora criado, entrou, num sábado, na sinagoga, segundo o seu costume, e levantou-se para ler.

[[v42-4-17]]

^<<v42-4-17,17>>^ Então, lhe deram o livro do profeta Isaías, e, abrindo o livro, achou o lugar onde estava escrito:

[[v42-4-18]]

^<<v42-4-18,18>>^ O Espírito do Senhor está sobre mim, pelo que me ungiu para evangelizar os pobres; enviou-me para proclamar libertação aos cativos e restauração da vista aos cegos, para pôr em liberdade os oprimidos,

[[v42-4-19]]

^<<v42-4-19,19>>^ e apregoar o ano aceitável do Senhor.

[[v42-4-20]]

^<<v42-4-20,20>>^ Tendo fechado o livro, devolveu-o ao assistente e sentou-se; e todos na sinagoga tinham os olhos fitos nele.

[[v42-4-21]]

^<<v42-4-21,21>>^ Então, passou Jesus a dizer-lhes: Hoje, se cumpriu a Escritura que acabais de ouvir.

[[v42-4-22]]

^<<v42-4-22,22>>^ Todos lhe davam testemunho, e se maravilhavam das palavras de graça que lhe saíam dos lábios, e perguntavam: Não é este o filho de José?

[[v42-4-23]]

^<<v42-4-23,23>>^ Disse-lhes Jesus: Sem dúvida, citar-me-eis este provérbio: Médico, cura-te a ti mesmo; tudo o que ouvimos ter-se dado em Cafarnaum, faze-o também aqui na tua terra.

[[v42-4-24]]

^<<v42-4-24,24>>^ E prosseguiu: De fato, vos afirmo que nenhum profeta é bem-recebido na sua própria terra.

[[v42-4-25]]

^<<v42-4-25,25>>^ Na verdade vos digo que muitas viúvas havia em Israel no tempo de Elias, quando o céu se fechou por três anos e seis meses, reinando grande fome em toda a terra;

[[v42-4-26]]

^<<v42-4-26,26>>^ e a nenhuma delas foi Elias enviado, senão a uma viúva de Sarepta de Sidom.

[[v42-4-27]]

^<<v42-4-27,27>>^ Havia também muitos leprosos em Israel nos dias do profeta Eliseu, e nenhum deles foi purificado, senão Naamã, o siro.

[[v42-4-28]]

^<<v42-4-28,28>>^ Todos na sinagoga, ouvindo estas coisas, se encheram de ira.

[[v42-4-29]]

^<<v42-4-29,29>>^ E, levantando-se, expulsaram-no da cidade e o levaram até ao cimo do monte sobre o qual estava edificada, para, de lá, o precipitarem abaixo.

[[v42-4-30]]

^<<v42-4-30,30>>^ Jesus, porém, passando por entre eles, retirou-se.

[[v42-4-31]]

^<<v42-4-31,31>>^ E desceu a Cafarnaum, cidade da Galileia, e os ensinava no sábado.

[[v42-4-32]]

^<<v42-4-32,32>>^ E muito se maravilhavam da sua doutrina, porque a sua palavra era com autoridade.

[[v42-4-33]]

^<<v42-4-33,33>>^ Achava-se na sinagoga um homem possesso de um espírito de demônio imundo, e bradou em alta voz:

[[v42-4-34]]

^<<v42-4-34,34>>^ Ah! Que temos nós contigo, Jesus Nazareno? Vieste para perder-nos? Bem sei quem és: o Santo de Deus!

[[v42-4-35]]

^<<v42-4-35,35>>^ Mas Jesus o repreendeu, dizendo: Cala-te e sai deste homem.  O demônio, depois de o ter lançado por terra no meio de todos, saiu dele sem lhe fazer mal.

[[v42-4-36]]

^<<v42-4-36,36>>^ Todos ficaram grandemente admirados e comentavam entre si, dizendo: Que palavra é esta, pois, com autoridade e poder, ordena aos espíritos imundos, e eles saem?

[[v42-4-37]]

^<<v42-4-37,37>>^ E a sua fama corria por todos os lugares da circunvizinhança.

[[v42-4-38]]

^<<v42-4-38,38>>^ Deixando ele a sinagoga, foi para a casa de Simão. Ora, a sogra de Simão achava-se enferma, com febre muito alta; e rogaram-lhe por ela.

[[v42-4-39]]

^<<v42-4-39,39>>^ Inclinando-se ele para ela, repreendeu a febre, e esta a deixou; e logo se levantou, passando a servi-los.

[[v42-4-40]]

^<<v42-4-40,40>>^ Ao pôr do sol, todos os que tinham enfermos de diferentes moléstias lhos traziam; e ele os curava, impondo as mãos sobre cada um.

[[v42-4-41]]

^<<v42-4-41,41>>^ Também de muitos saíam demônios, gritando e dizendo: Tu és o Filho de Deus! Ele, porém, os repreendia para que não falassem, pois sabiam ser ele o Cristo.

[[v42-4-42]]

^<<v42-4-42,42>>^ Sendo dia, saiu e foi para um lugar deserto; as multidões o procuravam, e foram até junto dele, e instavam para que não os deixasse.

[[v42-4-43]]

^<<v42-4-43,43>>^ Ele, porém, lhes disse: É necessário que eu anuncie o evangelho do reino de Deus também às outras cidades, pois para isso é que fui enviado.

[[v42-4-44]]

^<<v42-4-44,44>>^ E pregava nas sinagogas da Judeia.

'''

xref:042-lucas/042-lucas-003.adoc#v42-3-0[&#60; Capítulo Anterior] | <<v42-4-0,Topo>> | xref:042-lucas/042-lucas-005.adoc#v42-5-0[Próximo Capítulo &#62;]