include::./index.adoc[]

[[v42-19-0]]
=== Lucas, 19
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-19-1]]

^<<v42-19-1,1>>^ Entrando em Jericó, atravessava Jesus a cidade.

[[v42-19-2]]

^<<v42-19-2,2>>^ Eis que um homem, chamado Zaqueu, maioral dos publicanos e rico,

[[v42-19-3]]

^<<v42-19-3,3>>^ procurava ver quem era Jesus, mas não podia, por causa da multidão, por ser ele de pequena estatura.

[[v42-19-4]]

^<<v42-19-4,4>>^ Então, correndo adiante, subiu a um sicômoro a fim de vê-lo, porque por ali havia de passar.

[[v42-19-5]]

^<<v42-19-5,5>>^ Quando Jesus chegou àquele lugar, olhando para cima, disse-lhe: Zaqueu, desce depressa, pois me convém ficar hoje em tua casa.

[[v42-19-6]]

^<<v42-19-6,6>>^ Ele desceu a toda a pressa e o recebeu com alegria.

[[v42-19-7]]

^<<v42-19-7,7>>^ Todos os que viram isto murmuravam, dizendo que ele se hospedara com homem pecador.

[[v42-19-8]]

^<<v42-19-8,8>>^ Entrementes, Zaqueu se levantou e disse ao Senhor: Senhor, resolvo dar aos pobres a metade dos meus bens; e, se nalguma coisa tenho defraudado alguém, restituo quatro vezes mais.

[[v42-19-9]]

^<<v42-19-9,9>>^ Então, Jesus lhe disse: Hoje, houve salvação nesta casa, pois que também este é filho de Abraão.

[[v42-19-10]]

^<<v42-19-10,10>>^ Porque o Filho do Homem veio buscar e salvar o perdido.

[[v42-19-11]]

^<<v42-19-11,11>>^ Ouvindo eles estas coisas, Jesus propôs uma parábola, visto estar perto de Jerusalém e lhes parecer que o reino de Deus havia de manifestar-se imediatamente.

[[v42-19-12]]

^<<v42-19-12,12>>^ Então, disse: Certo homem nobre partiu para uma terra distante, com o fim de tomar posse de um reino e voltar.

[[v42-19-13]]

^<<v42-19-13,13>>^ Chamou dez servos seus, confiou-lhes dez minas e disse-lhes: Negociai até que eu volte.

[[v42-19-14]]

^<<v42-19-14,14>>^ Mas os seus concidadãos o odiavam e enviaram após ele uma embaixada, dizendo: Não queremos que este reine sobre nós.

[[v42-19-15]]

^<<v42-19-15,15>>^ Quando ele voltou, depois de haver tomado posse do reino, mandou chamar os servos a quem dera o dinheiro, a fim de saber que negócio cada um teria conseguido.

[[v42-19-16]]

^<<v42-19-16,16>>^ Compareceu o primeiro e disse: Senhor, a tua mina rendeu dez.

[[v42-19-17]]

^<<v42-19-17,17>>^ Respondeu-lhe o senhor: Muito bem, servo bom; porque foste fiel no pouco, terás autoridade sobre dez cidades.

[[v42-19-18]]

^<<v42-19-18,18>>^ Veio o segundo, dizendo: Senhor, a tua mina rendeu cinco.

[[v42-19-19]]

^<<v42-19-19,19>>^ A este disse: Terás autoridade sobre cinco cidades.

[[v42-19-20]]

^<<v42-19-20,20>>^ Veio, então, outro, dizendo: Eis aqui, senhor, a tua mina, que eu guardei embrulhada num lenço.

[[v42-19-21]]

^<<v42-19-21,21>>^ Pois tive medo de ti, que és homem rigoroso; tiras o que não puseste e ceifas o que não semeaste.

[[v42-19-22]]

^<<v42-19-22,22>>^ Respondeu-lhe: Servo mau, por tua própria boca te condenarei. Sabias que eu sou homem rigoroso, que tiro o que não pus e ceifo o que não semeei;

[[v42-19-23]]

^<<v42-19-23,23>>^ por que não puseste o meu dinheiro no banco? E, então, na minha vinda, o receberia com juros.

[[v42-19-24]]

^<<v42-19-24,24>>^ E disse aos que o assistiam: Tirai-lhe a mina e dai-a ao que tem as dez.

[[v42-19-25]]

^<<v42-19-25,25>>^ Eles ponderaram: Senhor, ele já tem dez.

[[v42-19-26]]

^<<v42-19-26,26>>^ Pois eu vos declaro: a todo o que tem dar-se-lhe-á; mas ao que não tem, o que tem lhe será tirado.

[[v42-19-27]]

^<<v42-19-27,27>>^ Quanto, porém, a esses meus inimigos, que não quiseram que eu reinasse sobre eles, trazei-os aqui e executai-os na minha presença.

[[v42-19-28]]

^<<v42-19-28,28>>^ E, dito isto, prosseguia Jesus subindo para Jerusalém.

[[v42-19-29]]

^<<v42-19-29,29>>^ Ora, aconteceu que, ao aproximar-se de Betfagé e de Betânia, junto ao monte das Oliveiras, enviou dois de seus discípulos,

[[v42-19-30]]

^<<v42-19-30,30>>^ dizendo-lhes: Ide à aldeia fronteira e ali, ao entrardes, achareis preso um jumentinho que jamais homem algum montou; soltai-o e trazei-o.

[[v42-19-31]]

^<<v42-19-31,31>>^ Se alguém vos perguntar: Por que o soltais? Respondereis assim: Porque o Senhor precisa dele.

[[v42-19-32]]

^<<v42-19-32,32>>^ E, indo os que foram mandados, acharam segundo lhes dissera Jesus.

[[v42-19-33]]

^<<v42-19-33,33>>^ Quando eles estavam soltando o jumentinho, seus donos lhes disseram: Por que o soltais?

[[v42-19-34]]

^<<v42-19-34,34>>^ Responderam: Porque o Senhor precisa dele.

[[v42-19-35]]

^<<v42-19-35,35>>^ Então, o trouxeram e, pondo as suas vestes sobre ele, ajudaram Jesus a montar.

[[v42-19-36]]

^<<v42-19-36,36>>^ Indo ele, estendiam no caminho as suas vestes.

[[v42-19-37]]

^<<v42-19-37,37>>^ E, quando se aproximava da descida do monte das Oliveiras, toda a multidão dos discípulos passou, jubilosa, a louvar a Deus em alta voz, por todos os milagres que tinham visto,

[[v42-19-38]]

^<<v42-19-38,38>>^ dizendo: Bendito é o Rei que vem em nome do Senhor! Paz no céu e glória nas maiores alturas!

[[v42-19-39]]

^<<v42-19-39,39>>^ Ora, alguns dos fariseus lhe disseram em meio à multidão: Mestre, repreende os teus discípulos!

[[v42-19-40]]

^<<v42-19-40,40>>^ Mas ele lhes respondeu: Asseguro-vos que, se eles se calarem, as próprias pedras clamarão.

[[v42-19-41]]

^<<v42-19-41,41>>^ Quando ia chegando, vendo a cidade, chorou

[[v42-19-42]]

^<<v42-19-42,42>>^ e dizia: Ah! Se conheceras por ti mesma, ainda hoje, o que é devido à paz! Mas isto está agora oculto aos teus olhos.

[[v42-19-43]]

^<<v42-19-43,43>>^ Pois sobre ti virão dias em que os teus inimigos te cercarão de trincheiras e, por todos os lados, te apertarão o cerco;

[[v42-19-44]]

^<<v42-19-44,44>>^ e te arrasarão e aos teus filhos dentro de ti; não deixarão em ti pedra sobre pedra, porque não reconheceste a oportunidade da tua visitação.

[[v42-19-45]]

^<<v42-19-45,45>>^ Depois, entrando no templo, expulsou os que ali vendiam,

[[v42-19-46]]

^<<v42-19-46,46>>^ dizendo-lhes: Está escrito: A minha casa será casa de oração. Mas vós a transformastes em covil de salteadores.

[[v42-19-47]]

^<<v42-19-47,47>>^ Diariamente, Jesus ensinava no templo; mas os principais sacerdotes, os escribas e os maiorais do povo procuravam eliminá-lo;

[[v42-19-48]]

^<<v42-19-48,48>>^ contudo, não atinavam em como fazê-lo, porque todo o povo, ao ouvi-lo, ficava dominado por ele.

'''

xref:042-lucas/042-lucas-018.adoc#v42-18-0[&#60; Capítulo Anterior] | <<v42-19-0,Topo>> | xref:042-lucas/042-lucas-020.adoc#v42-20-0[Próximo Capítulo &#62;]