include::./index.adoc[]

[[v42-16-0]]
=== Lucas, 16
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-16-1]]

^<<v42-16-1,1>>^ Disse Jesus também aos discípulos: Havia um homem rico que tinha um administrador; e este lhe foi denunciado como quem estava a defraudar os seus bens.

[[v42-16-2]]

^<<v42-16-2,2>>^ Então, mandando-o chamar, lhe disse: Que é isto que ouço a teu respeito? Presta contas da tua administração, porque já não podes mais continuar nela.

[[v42-16-3]]

^<<v42-16-3,3>>^ Disse o administrador consigo mesmo: Que farei, pois o meu senhor me tira a administração? Trabalhar na terra não posso; também de mendigar tenho vergonha.

[[v42-16-4]]

^<<v42-16-4,4>>^ Eu sei o que farei, para que, quando for demitido da administração, me recebam em suas casas.

[[v42-16-5]]

^<<v42-16-5,5>>^ Tendo chamado cada um dos devedores do seu senhor, disse ao primeiro: Quanto deves ao meu patrão?

[[v42-16-6]]

^<<v42-16-6,6>>^ Respondeu ele: Cem cados de azeite. Então, disse: Toma a tua conta, assenta-te depressa e escreve cinquenta.

[[v42-16-7]]

^<<v42-16-7,7>>^ Depois, perguntou a outro: Tu, quanto deves? Respondeu ele: Cem coros de trigo. Disse-lhe: Toma a tua conta e escreve oitenta.

[[v42-16-8]]

^<<v42-16-8,8>>^ E elogiou o senhor o administrador infiel porque se houvera atiladamente, porque os filhos do mundo são mais hábeis na sua própria geração do que os filhos da luz.

[[v42-16-9]]

^<<v42-16-9,9>>^ E eu vos recomendo: das riquezas de origem iníqua fazei amigos; para que, quando aquelas vos faltarem, esses amigos vos recebam nos tabernáculos eternos.

[[v42-16-10]]

^<<v42-16-10,10>>^ Quem é fiel no pouco também é fiel no muito; e quem é injusto no pouco também é injusto no muito.

[[v42-16-11]]

^<<v42-16-11,11>>^ Se, pois, não vos tornastes fiéis na aplicação das riquezas de origem injusta, quem vos confiará a verdadeira riqueza?

[[v42-16-12]]

^<<v42-16-12,12>>^ Se não vos tornastes fiéis na aplicação do alheio, quem vos dará o que é vosso?

[[v42-16-13]]

^<<v42-16-13,13>>^ Ninguém pode servir a dois senhores; porque ou há de aborrecer-se de um e amar ao outro ou se devotará a um e desprezará ao outro. Não podeis servir a Deus e às riquezas.

[[v42-16-14]]

^<<v42-16-14,14>>^ Os fariseus, que eram avarentos, ouviam tudo isto e o ridiculizavam.

[[v42-16-15]]

^<<v42-16-15,15>>^ Mas Jesus lhes disse: Vós sois os que vos justificais a vós mesmos diante dos homens, mas Deus conhece o vosso coração; pois aquilo que é elevado entre homens é abominação diante de Deus.

[[v42-16-16]]

^<<v42-16-16,16>>^ A Lei e os Profetas vigoraram até João; desde esse tempo, vem sendo anunciado o evangelho do reino de Deus, e todo homem se esforça por entrar nele.

[[v42-16-17]]

^<<v42-16-17,17>>^ E é mais fácil passar o céu e a terra do que cair um til sequer da Lei.

[[v42-16-18]]

^<<v42-16-18,18>>^ Quem repudiar sua mulher e casar com outra comete adultério; e aquele que casa com a mulher repudiada pelo marido também comete adultério.

[[v42-16-19]]

^<<v42-16-19,19>>^ Ora, havia certo homem rico que se vestia de púrpura e de linho finíssimo e que, todos os dias, se regalava esplendidamente.

[[v42-16-20]]

^<<v42-16-20,20>>^ Havia também certo mendigo, chamado Lázaro, coberto de chagas, que jazia à porta daquele;

[[v42-16-21]]

^<<v42-16-21,21>>^ e desejava alimentar-se das migalhas que caíam da mesa do rico; e até os cães vinham lamber-lhe as úlceras.

[[v42-16-22]]

^<<v42-16-22,22>>^ Aconteceu morrer o mendigo e ser levado pelos anjos para o seio de Abraão; morreu também o rico e foi sepultado.

[[v42-16-23]]

^<<v42-16-23,23>>^ No inferno, estando em tormentos, levantou os olhos e viu ao longe a Abraão e Lázaro no seu seio.

[[v42-16-24]]

^<<v42-16-24,24>>^ Então, clamando, disse: Pai Abraão, tem misericórdia de mim! E manda a Lázaro que molhe em água a ponta do dedo e me refresque a língua, porque estou atormentado nesta chama.

[[v42-16-25]]

^<<v42-16-25,25>>^ Disse, porém, Abraão: Filho, lembra-te de que recebeste os teus bens em tua vida, e Lázaro igualmente, os males; agora, porém, aqui, ele está consolado; tu, em tormentos.

[[v42-16-26]]

^<<v42-16-26,26>>^ E, além de tudo, está posto um grande abismo entre nós e vós, de sorte que os que querem passar daqui para vós outros não podem, nem os de lá passar para nós.

[[v42-16-27]]

^<<v42-16-27,27>>^ Então, replicou: Pai, eu te imploro que o mandes à minha casa paterna,

[[v42-16-28]]

^<<v42-16-28,28>>^ porque tenho cinco irmãos; para que lhes dê testemunho, a fim de não virem também para este lugar de tormento.

[[v42-16-29]]

^<<v42-16-29,29>>^ Respondeu Abraão: Eles têm Moisés e os Profetas; ouçam-nos.

[[v42-16-30]]

^<<v42-16-30,30>>^ Mas ele insistiu: Não, pai Abraão; se alguém dentre os mortos for ter com eles, arrepender-se-ão.

[[v42-16-31]]

^<<v42-16-31,31>>^ Abraão, porém, lhe respondeu: Se não ouvem a Moisés e aos Profetas, tampouco se deixarão persuadir, ainda que ressuscite alguém dentre os mortos.

'''

xref:042-lucas/042-lucas-015.adoc#v42-15-0[&#60; Capítulo Anterior] | <<v42-16-0,Topo>> | xref:042-lucas/042-lucas-017.adoc#v42-17-0[Próximo Capítulo &#62;]