include::./index.adoc[]

[[v42-2-0]]
=== Lucas, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v42-2-1]]

^<<v42-2-1,1>>^ Naqueles dias, foi publicado um decreto de César Augusto, convocando toda a população do império para recensear-se.

[[v42-2-2]]

^<<v42-2-2,2>>^ Este, o primeiro recenseamento, foi feito quando Quirino era governador da Síria.

[[v42-2-3]]

^<<v42-2-3,3>>^ Todos iam alistar-se, cada um à sua própria cidade.

[[v42-2-4]]

^<<v42-2-4,4>>^ José também subiu da Galileia, da cidade de Nazaré, para a Judeia, à cidade de Davi, chamada Belém, por ser ele da casa e família de Davi,

[[v42-2-5]]

^<<v42-2-5,5>>^ a fim de alistar-se com Maria, sua esposa, que estava grávida.

[[v42-2-6]]

^<<v42-2-6,6>>^ Estando eles ali, aconteceu completarem-se-lhe os dias,

[[v42-2-7]]

^<<v42-2-7,7>>^ e ela deu à luz o seu filho primogênito, enfaixou-o e o deitou numa manjedoura, porque não havia lugar para eles na hospedaria.

[[v42-2-8]]

^<<v42-2-8,8>>^ Havia, naquela mesma região, pastores que viviam nos campos e guardavam o seu rebanho durante as vigílias da noite.

[[v42-2-9]]

^<<v42-2-9,9>>^ E um anjo do Senhor desceu aonde eles estavam, e a glória do Senhor brilhou ao redor deles; e ficaram tomados de grande temor.

[[v42-2-10]]

^<<v42-2-10,10>>^ O anjo, porém, lhes disse: Não temais; eis aqui vos trago boa-nova de grande alegria, que o será para todo o povo:

[[v42-2-11]]

^<<v42-2-11,11>>^ é que hoje vos nasceu, na cidade de Davi, o Salvador, que é Cristo, o Senhor.

[[v42-2-12]]

^<<v42-2-12,12>>^ E isto vos servirá de sinal: encontrareis uma criança envolta em faixas e deitada em manjedoura.

[[v42-2-13]]

^<<v42-2-13,13>>^ E, subitamente, apareceu com o anjo uma multidão da milícia celestial, louvando a Deus e dizendo:

[[v42-2-14]]

^<<v42-2-14,14>>^ Glória a Deus nas maiores alturas, e paz na terra entre os homens, a quem ele quer bem.

[[v42-2-15]]

^<<v42-2-15,15>>^ E, ausentando-se deles os anjos para o céu, diziam os pastores uns aos outros: Vamos até Belém e vejamos os acontecimentos que o Senhor nos deu a conhecer.

[[v42-2-16]]

^<<v42-2-16,16>>^ Foram apressadamente e acharam Maria e José e a criança deitada na manjedoura.

[[v42-2-17]]

^<<v42-2-17,17>>^ E, vendo-o, divulgaram o que lhes tinha sido dito a respeito deste menino.

[[v42-2-18]]

^<<v42-2-18,18>>^ Todos os que ouviram se admiraram das coisas referidas pelos pastores.

[[v42-2-19]]

^<<v42-2-19,19>>^ Maria, porém, guardava todas estas palavras, meditando-as no coração.

[[v42-2-20]]

^<<v42-2-20,20>>^ Voltaram, então, os pastores glorificando e louvando a Deus por tudo o que tinham ouvido e visto, como lhes fora anunciado.

[[v42-2-21]]

^<<v42-2-21,21>>^ Completados oito dias para ser circuncidado o menino, deram-lhe o nome de Jesus , como lhe chamara o anjo, antes de ser concebido.

[[v42-2-22]]

^<<v42-2-22,22>>^ Passados os dias da purificação deles segundo a Lei de Moisés, levaram-no a Jerusalém para o apresentarem ao Senhor,

[[v42-2-23]]

^<<v42-2-23,23>>^ conforme o que está escrito na Lei do Senhor: Todo primogênito ao Senhor será consagrado;

[[v42-2-24]]

^<<v42-2-24,24>>^ e para oferecer um sacrifício, segundo o que está escrito na referida Lei: Um par de rolas ou dois pombinhos.

[[v42-2-25]]

^<<v42-2-25,25>>^ Havia em Jerusalém um homem chamado Simeão; homem este justo e piedoso que esperava a consolação de Israel; e o Espírito Santo estava sobre ele.

[[v42-2-26]]

^<<v42-2-26,26>>^ Revelara-lhe o Espírito Santo que não passaria pela morte antes de ver o Cristo do Senhor.

[[v42-2-27]]

^<<v42-2-27,27>>^ Movido pelo Espírito, foi ao templo; e, quando os pais trouxeram o menino Jesus para fazerem com ele o que a Lei ordenava,

[[v42-2-28]]

^<<v42-2-28,28>>^ Simeão o tomou nos braços e louvou a Deus, dizendo:

[[v42-2-29]]

^<<v42-2-29,29>>^ Agora, Senhor, podes despedir em paz o teu servo, segundo a tua palavra;

[[v42-2-30]]

^<<v42-2-30,30>>^ porque os meus olhos já viram a tua salvação,

[[v42-2-31]]

^<<v42-2-31,31>>^ a qual preparaste diante de todos os povos:

[[v42-2-32]]

^<<v42-2-32,32>>^ luz para revelação aos gentios, e para glória do teu povo de Israel.

[[v42-2-33]]

^<<v42-2-33,33>>^ E estavam o pai e a mãe do menino admirados do que dele se dizia.

[[v42-2-34]]

^<<v42-2-34,34>>^ Simeão os abençoou e disse a Maria, mãe do menino: Eis que este menino está destinado tanto para ruína como para levantamento de muitos em Israel e para ser alvo de contradição

[[v42-2-35]]

^<<v42-2-35,35>>^ (também uma espada traspassará a tua própria alma), para que se manifestem os pensamentos de muitos corações.

[[v42-2-36]]

^<<v42-2-36,36>>^ Havia uma profetisa, chamada Ana, filha de Fanuel, da tribo de Aser, avançada em dias, que vivera com seu marido sete anos desde que se casara

[[v42-2-37]]

^<<v42-2-37,37>>^ e que era viúva de oitenta e quatro anos. Esta não deixava o templo, mas adorava noite e dia em jejuns e orações.

[[v42-2-38]]

^<<v42-2-38,38>>^ E, chegando naquela hora, dava graças a Deus e falava a respeito do menino a todos os que esperavam a redenção de Jerusalém.

[[v42-2-39]]

^<<v42-2-39,39>>^ Cumpridas todas as ordenanças segundo a Lei do Senhor, voltaram para a Galileia, para a sua cidade de Nazaré.

[[v42-2-40]]

^<<v42-2-40,40>>^ Crescia o menino e se fortalecia, enchendo-se de sabedoria; e a graça de Deus estava sobre ele.

[[v42-2-41]]

^<<v42-2-41,41>>^ Ora, anualmente iam seus pais a Jerusalém, para a Festa da Páscoa.

[[v42-2-42]]

^<<v42-2-42,42>>^ Quando ele atingiu os doze anos, subiram a Jerusalém, segundo o costume da festa.

[[v42-2-43]]

^<<v42-2-43,43>>^ Terminados os dias da festa, ao regressarem, permaneceu o menino Jesus em Jerusalém, sem que seus pais o soubessem.

[[v42-2-44]]

^<<v42-2-44,44>>^ Pensando, porém, estar ele entre os companheiros de viagem, foram caminho de um dia e, então, passaram a procurá-lo entre os parentes e os conhecidos;

[[v42-2-45]]

^<<v42-2-45,45>>^ e, não o tendo encontrado, voltaram a Jerusalém à sua procura.

[[v42-2-46]]

^<<v42-2-46,46>>^ Três dias depois, o acharam no templo, assentado no meio dos doutores, ouvindo-os e interrogando-os.

[[v42-2-47]]

^<<v42-2-47,47>>^ E todos os que o ouviam muito se admiravam da sua inteligência e das suas respostas.

[[v42-2-48]]

^<<v42-2-48,48>>^ Logo que seus pais o viram, ficaram maravilhados; e sua mãe lhe disse: Filho, por que fizeste assim conosco? Teu pai e eu, aflitos, estamos à tua procura.

[[v42-2-49]]

^<<v42-2-49,49>>^ Ele lhes respondeu: Por que me procuráveis? Não sabíeis que me cumpria estar na casa de meu Pai?

[[v42-2-50]]

^<<v42-2-50,50>>^ Não compreenderam, porém, as palavras que lhes dissera.

[[v42-2-51]]

^<<v42-2-51,51>>^ E desceu com eles para Nazaré; e era-lhes submisso. Sua mãe, porém, guardava todas estas coisas no coração.

[[v42-2-52]]

^<<v42-2-52,52>>^ E crescia Jesus em sabedoria, estatura e graça, diante de Deus e dos homens.

'''

xref:042-lucas/042-lucas-001.adoc#v42-1-0[&#60; Capítulo Anterior] | <<v42-2-0,Topo>> | xref:042-lucas/042-lucas-003.adoc#v42-3-0[Próximo Capítulo &#62;]