include::./index.adoc[]

[[v20-16-0]]
=== Provérbios, 16
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-16-1]]

^<<v20-16-1,1>>^ O coração do homem pode fazer planos, mas a resposta certa dos lábios vem do SENHOR.

[[v20-16-2]]

^<<v20-16-2,2>>^ Todos os caminhos do homem são puros aos seus olhos, mas o SENHOR pesa o espírito.

[[v20-16-3]]

^<<v20-16-3,3>>^ Confia ao SENHOR as tuas obras, e os teus desígnios serão estabelecidos.

[[v20-16-4]]

^<<v20-16-4,4>>^ O SENHOR fez todas as coisas para determinados fins e até o perverso, para o dia da calamidade.

[[v20-16-5]]

^<<v20-16-5,5>>^ Abominável é ao SENHOR todo arrogante de coração; é evidente que não ficará impune.

[[v20-16-6]]

^<<v20-16-6,6>>^ Pela misericórdia e pela verdade, se expia a culpa; e pelo temor do SENHOR os homens evitam o mal.

[[v20-16-7]]

^<<v20-16-7,7>>^ Sendo o caminho dos homens agradável ao SENHOR, este reconcilia com eles os seus inimigos.

[[v20-16-8]]

^<<v20-16-8,8>>^ Melhor é o pouco, havendo justiça, do que grandes rendimentos com injustiça.

[[v20-16-9]]

^<<v20-16-9,9>>^ O coração do homem traça o seu caminho, mas o SENHOR lhe dirige os passos.

[[v20-16-10]]

^<<v20-16-10,10>>^ Nos lábios do rei se acham decisões autorizadas; no julgar não transgrida, pois, a sua boca.

[[v20-16-11]]

^<<v20-16-11,11>>^ Peso e balança justos pertencem ao SENHOR; obra sua são todos os pesos da bolsa.

[[v20-16-12]]

^<<v20-16-12,12>>^ A prática da impiedade é abominável para os reis, porque com justiça se estabelece o trono.

[[v20-16-13]]

^<<v20-16-13,13>>^ Os lábios justos são o contentamento do rei, e ele ama o que fala coisas retas.

[[v20-16-14]]

^<<v20-16-14,14>>^ O furor do rei são uns mensageiros de morte, mas o homem sábio o apazigua.

[[v20-16-15]]

^<<v20-16-15,15>>^ O semblante alegre do rei significa vida, e a sua benevolência é como a nuvem que traz chuva serôdia.

[[v20-16-16]]

^<<v20-16-16,16>>^ Quanto melhor é adquirir a sabedoria do que o ouro! E mais excelente, adquirir a prudência do que a prata!

[[v20-16-17]]

^<<v20-16-17,17>>^ O caminho dos retos é desviar-se do mal; o que guarda o seu caminho preserva a sua alma.

[[v20-16-18]]

^<<v20-16-18,18>>^ A soberba precede a ruína, e a altivez do espírito, a queda.

[[v20-16-19]]

^<<v20-16-19,19>>^ Melhor é ser humilde de espírito com os humildes do que repartir o despojo com os soberbos.

[[v20-16-20]]

^<<v20-16-20,20>>^ O que atenta para o ensino acha o bem, e o que confia no SENHOR, esse é feliz.

[[v20-16-21]]

^<<v20-16-21,21>>^ O sábio de coração é chamado prudente, e a doçura no falar aumenta o saber.

[[v20-16-22]]

^<<v20-16-22,22>>^ O entendimento, para aqueles que o possuem, é fonte de vida; mas, para o insensato, a sua estultícia lhe é castigo.

[[v20-16-23]]

^<<v20-16-23,23>>^ O coração do sábio é mestre de sua boca e aumenta a persuasão nos seus lábios.

[[v20-16-24]]

^<<v20-16-24,24>>^ Palavras agradáveis são como favo de mel: doces para a alma e medicina para o corpo.

[[v20-16-25]]

^<<v20-16-25,25>>^ Há caminho que parece direito ao homem, mas afinal são caminhos de morte.

[[v20-16-26]]

^<<v20-16-26,26>>^ A fome do trabalhador o faz trabalhar, porque a sua boca a isso o incita.

[[v20-16-27]]

^<<v20-16-27,27>>^ O homem depravado cava o mal, e nos seus lábios há como que fogo ardente.

[[v20-16-28]]

^<<v20-16-28,28>>^ O homem perverso espalha contendas, e o difamador separa os maiores amigos.

[[v20-16-29]]

^<<v20-16-29,29>>^ O homem violento alicia o seu companheiro e guia-o por um caminho que não é bom.

[[v20-16-30]]

^<<v20-16-30,30>>^ Quem fecha os olhos imagina o mal, e, quando morde os lábios, o executa.

[[v20-16-31]]

^<<v20-16-31,31>>^ Coroa de honra são as cãs, quando se acham no caminho da justiça.

[[v20-16-32]]

^<<v20-16-32,32>>^ Melhor é o longânimo do que o herói da guerra, e o que domina o seu espírito, do que o que toma uma cidade.

[[v20-16-33]]

^<<v20-16-33,33>>^ A sorte se lança no regaço, mas do SENHOR procede toda decisão.

'''

xref:020-proverbios/020-proverbios-015.adoc#v20-15-0[&#60; Capítulo Anterior] | <<v20-16-0,Topo>> | xref:020-proverbios/020-proverbios-017.adoc#v20-17-0[Próximo Capítulo &#62;]