include::./index.adoc[]

[[v20-2-0]]
=== Provérbios, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-2-1]]

^<<v20-2-1,1>>^ Filho meu, se aceitares as minhas palavras e esconderes contigo os meus mandamentos,

[[v20-2-2]]

^<<v20-2-2,2>>^ para fazeres atento à sabedoria o teu ouvido e para inclinares o coração ao entendimento,

[[v20-2-3]]

^<<v20-2-3,3>>^ e, se clamares por inteligência, e por entendimento alçares a voz,

[[v20-2-4]]

^<<v20-2-4,4>>^ se buscares a sabedoria como a prata e como a tesouros escondidos a procurares,

[[v20-2-5]]

^<<v20-2-5,5>>^ então, entenderás o temor do Senhor e acharás o conhecimento de Deus.

[[v20-2-6]]

^<<v20-2-6,6>>^ Porque o SENHOR dá a sabedoria, e da sua boca vem a inteligência e o entendimento.

[[v20-2-7]]

^<<v20-2-7,7>>^ Ele reserva a verdadeira sabedoria para os retos; é escudo para os que caminham na sinceridade,

[[v20-2-8]]

^<<v20-2-8,8>>^ guarda as veredas do juízo e conserva o caminho dos seus santos.

[[v20-2-9]]

^<<v20-2-9,9>>^ Então, entenderás justiça, juízo e equidade, todas as boas veredas.

[[v20-2-10]]

^<<v20-2-10,10>>^ Porquanto a sabedoria entrará no teu coração, e o conhecimento será agradável à tua alma.

[[v20-2-11]]

^<<v20-2-11,11>>^ O bom siso te guardará, e a inteligência te conservará;

[[v20-2-12]]

^<<v20-2-12,12>>^ para te livrar do caminho do mal e do homem que diz coisas perversas;

[[v20-2-13]]

^<<v20-2-13,13>>^ dos que deixam as veredas da retidão, para andarem pelos caminhos das trevas;

[[v20-2-14]]

^<<v20-2-14,14>>^ que se alegram de fazer o mal, folgam com as perversidades dos maus,

[[v20-2-15]]

^<<v20-2-15,15>>^ seguem veredas tortuosas e se desviam nos seus caminhos;

[[v20-2-16]]

^<<v20-2-16,16>>^ para te livrar da mulher adúltera, da estrangeira, que lisonjeia com palavras,

[[v20-2-17]]

^<<v20-2-17,17>>^ a qual deixa o amigo da sua mocidade e se esquece da aliança do seu Deus;

[[v20-2-18]]

^<<v20-2-18,18>>^ porque a sua casa se inclina para a morte, e as suas veredas, para o reino das sombras da morte;

[[v20-2-19]]

^<<v20-2-19,19>>^ todos os que se dirigem a essa mulher não voltarão e não atinarão com as veredas da vida.

[[v20-2-20]]

^<<v20-2-20,20>>^ Assim, andarás pelo caminho dos homens de bem e guardarás as veredas dos justos.

[[v20-2-21]]

^<<v20-2-21,21>>^ Porque os retos habitarão a terra, e os íntegros permanecerão nela.

[[v20-2-22]]

^<<v20-2-22,22>>^ Mas os perversos serão eliminados da terra, e os aleivosos serão dela desarraigados.

'''

xref:020-proverbios/020-proverbios-001.adoc#v20-1-0[&#60; Capítulo Anterior] | <<v20-2-0,Topo>> | xref:020-proverbios/020-proverbios-003.adoc#v20-3-0[Próximo Capítulo &#62;]