include::./index.adoc[]

[[v20-24-0]]
=== Provérbios, 24
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-24-1]]

^<<v20-24-1,1>>^ Não tenhas inveja dos homens malignos, nem queiras estar com eles,

[[v20-24-2]]

^<<v20-24-2,2>>^ porque o seu coração maquina violência, e os seus lábios falam para o mal.

[[v20-24-3]]

^<<v20-24-3,3>>^ Com a sabedoria edifica-se a casa, e com a inteligência ela se firma;

[[v20-24-4]]

^<<v20-24-4,4>>^ pelo conhecimento se encherão as câmaras de toda sorte de bens, preciosos e deleitáveis.

[[v20-24-5]]

^<<v20-24-5,5>>^ Mais poder tem o sábio do que o forte, e o homem de conhecimento, mais do que o robusto.

[[v20-24-6]]

^<<v20-24-6,6>>^ Com medidas de prudência farás a guerra; na multidão de conselheiros está a vitória.

[[v20-24-7]]

^<<v20-24-7,7>>^ A sabedoria é alta demais para o insensato; no juízo, a sua boca não terá palavra.

[[v20-24-8]]

^<<v20-24-8,8>>^ Ao que cuida em fazer o mal, mestre de intrigas lhe chamarão.

[[v20-24-9]]

^<<v20-24-9,9>>^ Os desígnios do insensato são pecado, e o escarnecedor é abominável aos homens.

[[v20-24-10]]

^<<v20-24-10,10>>^ Se te mostras fraco no dia da angústia, a tua força é pequena.

[[v20-24-11]]

^<<v20-24-11,11>>^ Livra os que estão sendo levados para a morte e salva os que cambaleiam indo para serem mortos.

[[v20-24-12]]

^<<v20-24-12,12>>^ Se disseres: Não o soubemos, não o perceberá aquele que pesa os corações? Não o saberá aquele que atenta para a tua alma? E não pagará ele ao homem segundo as suas obras?

[[v20-24-13]]

^<<v20-24-13,13>>^ Filho meu, saboreia o mel, porque é saudável, e o favo, porque é doce ao teu paladar.

[[v20-24-14]]

^<<v20-24-14,14>>^ Então, sabe que assim é a sabedoria para a tua alma; se a achares, haverá bom futuro, e não será frustrada a tua esperança.

[[v20-24-15]]

^<<v20-24-15,15>>^ Não te ponhas de emboscada, ó perverso, contra a habitação do justo, nem assoles o lugar do seu repouso,

[[v20-24-16]]

^<<v20-24-16,16>>^ porque sete vezes cairá o justo e se levantará; mas os perversos são derribados pela calamidade.

[[v20-24-17]]

^<<v20-24-17,17>>^ Quando cair o teu inimigo, não te alegres, e não se regozije o teu coração quando ele tropeçar;

[[v20-24-18]]

^<<v20-24-18,18>>^ para que o SENHOR não veja isso, e lhe desagrade, e desvie dele a sua ira.

[[v20-24-19]]

^<<v20-24-19,19>>^ Não te aflijas por causa dos malfeitores, nem tenhas inveja dos perversos,

[[v20-24-20]]

^<<v20-24-20,20>>^ porque o maligno não terá bom futuro, e a lâmpada dos perversos se apagará.

[[v20-24-21]]

^<<v20-24-21,21>>^ Teme ao SENHOR, filho meu, e ao rei e não te associes com os revoltosos.

[[v20-24-22]]

^<<v20-24-22,22>>^ Porque de repente levantará a sua perdição, e a ruína que virá daqueles dois, quem a conhecerá?

[[v20-24-23]]

^<<v20-24-23,23>>^ São também estes provérbios dos sábios. Parcialidade no julgar não é bom.

[[v20-24-24]]

^<<v20-24-24,24>>^ O que disser ao perverso: Tu és justo; pelo povo será maldito e detestado pelas nações.

[[v20-24-25]]

^<<v20-24-25,25>>^ Mas os que o repreenderem se acharão bem, e sobre eles virão grandes bênçãos.

[[v20-24-26]]

^<<v20-24-26,26>>^ Como beijo nos lábios, é a resposta com palavras retas.

[[v20-24-27]]

^<<v20-24-27,27>>^ Cuida dos teus negócios lá fora, apronta a lavoura no campo e, depois, edifica a tua casa.

[[v20-24-28]]

^<<v20-24-28,28>>^ Não sejas testemunha sem causa contra o teu próximo, nem o enganes com os teus lábios.

[[v20-24-29]]

^<<v20-24-29,29>>^ Não digas: Como ele me fez a mim, assim lhe farei a ele; pagarei a cada um segundo a sua obra.

[[v20-24-30]]

^<<v20-24-30,30>>^ Passei pelo campo do preguiçoso e junto à vinha do homem falto de entendimento;

[[v20-24-31]]

^<<v20-24-31,31>>^ eis que tudo estava cheio de espinhos, a sua superfície, coberta de urtigas, e o seu muro de pedra, em ruínas.

[[v20-24-32]]

^<<v20-24-32,32>>^ Tendo-o visto, considerei; vi e recebi a instrução.

[[v20-24-33]]

^<<v20-24-33,33>>^ Um pouco para dormir, um pouco para tosquenejar, um pouco para encruzar os braços em repouso,

[[v20-24-34]]

^<<v20-24-34,34>>^ assim sobrevirá a tua pobreza como um ladrão, e a tua necessidade, como um homem armado.

'''

xref:020-proverbios/020-proverbios-023.adoc#v20-23-0[&#60; Capítulo Anterior] | <<v20-24-0,Topo>> | xref:020-proverbios/020-proverbios-025.adoc#v20-25-0[Próximo Capítulo &#62;]