include::./index.adoc[]

[[v20-10-0]]
=== Provérbios, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-10-1]]

^<<v20-10-1,1>>^ Provérbios de Salomão. O filho sábio alegra a seu pai, mas o filho insensato é a tristeza de sua mãe.

[[v20-10-2]]

^<<v20-10-2,2>>^ Os tesouros da impiedade de nada aproveitam, mas a justiça livra da morte.

[[v20-10-3]]

^<<v20-10-3,3>>^ O SENHOR não deixa ter fome o justo, mas rechaça a avidez dos perversos.

[[v20-10-4]]

^<<v20-10-4,4>>^ O que trabalha com mão remissa empobrece, mas a mão dos diligentes vem a enriquecer-se.

[[v20-10-5]]

^<<v20-10-5,5>>^ O que ajunta no verão é filho sábio, mas o que dorme na sega é filho que envergonha.

[[v20-10-6]]

^<<v20-10-6,6>>^ Sobre a cabeça do justo há bênçãos, mas na boca dos perversos mora a violência.

[[v20-10-7]]

^<<v20-10-7,7>>^ A memória do justo é abençoada, mas o nome dos perversos cai em podridão.

[[v20-10-8]]

^<<v20-10-8,8>>^ O sábio de coração aceita os mandamentos, mas o insensato de lábios vem a arruinar-se.

[[v20-10-9]]

^<<v20-10-9,9>>^ Quem anda em integridade anda seguro, mas o que perverte os seus caminhos será conhecido.

[[v20-10-10]]

^<<v20-10-10,10>>^ O que acena com os olhos traz desgosto, e o insensato de lábios vem a arruinar-se.

[[v20-10-11]]

^<<v20-10-11,11>>^ A boca do justo é manancial de vida, mas na boca dos perversos mora a violência.

[[v20-10-12]]

^<<v20-10-12,12>>^ O ódio excita contendas, mas o amor cobre todas as transgressões.

[[v20-10-13]]

^<<v20-10-13,13>>^ Nos lábios do prudente, se acha sabedoria, mas a vara é para as costas do falto de senso.

[[v20-10-14]]

^<<v20-10-14,14>>^ Os sábios entesouram o conhecimento, mas a boca do néscio é uma ruína iminente.

[[v20-10-15]]

^<<v20-10-15,15>>^ Os bens do rico são a sua cidade forte; a pobreza dos pobres é a sua ruína.

[[v20-10-16]]

^<<v20-10-16,16>>^ A obra do justo conduz à vida, e o rendimento do perverso, ao pecado.

[[v20-10-17]]

^<<v20-10-17,17>>^ O caminho para a vida é de quem guarda o ensino, mas o que abandona a repreensão anda errado.

[[v20-10-18]]

^<<v20-10-18,18>>^ O que retém o ódio é de lábios falsos, e o que difama é insensato.

[[v20-10-19]]

^<<v20-10-19,19>>^ No muito falar não falta transgressão, mas o que modera os lábios é prudente.

[[v20-10-20]]

^<<v20-10-20,20>>^ Prata escolhida é a língua do justo, mas o coração dos perversos vale mui pouco.

[[v20-10-21]]

^<<v20-10-21,21>>^ Os lábios do justo apascentam a muitos, mas, por falta de senso, morrem os tolos.

[[v20-10-22]]

^<<v20-10-22,22>>^ A bênção do SENHOR enriquece, e, com ela, ele não traz desgosto.

[[v20-10-23]]

^<<v20-10-23,23>>^ Para o insensato, praticar a maldade é divertimento; para o homem inteligente, o ser sábio.

[[v20-10-24]]

^<<v20-10-24,24>>^ Aquilo que teme o perverso, isso lhe sobrevém, mas o anelo dos justos Deus o cumpre.

[[v20-10-25]]

^<<v20-10-25,25>>^ Como passa a tempestade, assim desaparece o perverso, mas o justo tem perpétuo fundamento.

[[v20-10-26]]

^<<v20-10-26,26>>^ Como vinagre para os dentes e fumaça para os olhos, assim é o preguiçoso para aqueles que o mandam.

[[v20-10-27]]

^<<v20-10-27,27>>^ O temor do SENHOR prolonga os dias da vida, mas os anos dos perversos serão abreviados.

[[v20-10-28]]

^<<v20-10-28,28>>^ A esperança dos justos é alegria, mas a expectação dos perversos perecerá.

[[v20-10-29]]

^<<v20-10-29,29>>^ O caminho do SENHOR é fortaleza para os íntegros, mas ruína aos que praticam a iniquidade.

[[v20-10-30]]

^<<v20-10-30,30>>^ O justo jamais será abalado, mas os perversos não habitarão a terra.

[[v20-10-31]]

^<<v20-10-31,31>>^ A boca do justo produz sabedoria, mas a língua da perversidade será desarraigada.

[[v20-10-32]]

^<<v20-10-32,32>>^ Os lábios do justo sabem o que agrada, mas a boca dos perversos, somente o mal.

'''

xref:020-proverbios/020-proverbios-009.adoc#v20-9-0[&#60; Capítulo Anterior] | <<v20-10-0,Topo>> | xref:020-proverbios/020-proverbios-011.adoc#v20-11-0[Próximo Capítulo &#62;]