include::./index.adoc[]

[[v20-22-0]]
=== Provérbios, 22
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-22-1]]

^<<v20-22-1,1>>^ Mais vale o bom nome do que as muitas riquezas; e o ser estimado é melhor do que a prata e o ouro.

[[v20-22-2]]

^<<v20-22-2,2>>^ O rico e o pobre se encontram; a um e a outro faz o SENHOR.

[[v20-22-3]]

^<<v20-22-3,3>>^ O prudente vê o mal e esconde-se; mas os simples passam adiante e sofrem a pena.

[[v20-22-4]]

^<<v20-22-4,4>>^ O galardão da humildade e o temor do Senhor são riquezas, e honra, e vida.

[[v20-22-5]]

^<<v20-22-5,5>>^ Espinhos e laços há no caminho do perverso; o que guarda a sua alma retira-se para longe deles.

[[v20-22-6]]

^<<v20-22-6,6>>^ Ensina a criança no caminho em que deve andar, e, ainda quando for velho, não se desviará dele.

[[v20-22-7]]

^<<v20-22-7,7>>^ O rico domina sobre o pobre, e o que toma emprestado é servo do que empresta.

[[v20-22-8]]

^<<v20-22-8,8>>^ O que semeia a injustiça segará males; e a vara da sua indignação falhará.

[[v20-22-9]]

^<<v20-22-9,9>>^ O generoso será abençoado, porque dá do seu pão ao pobre.

[[v20-22-10]]

^<<v20-22-10,10>>^ Lança fora o escarnecedor, e com ele se irá a contenda; cessarão as demandas e a ignomínia.

[[v20-22-11]]

^<<v20-22-11,11>>^ O que ama a pureza do coração e é grácil no falar terá por amigo o rei.

[[v20-22-12]]

^<<v20-22-12,12>>^ Os olhos do SENHOR conservam aquele que tem conhecimento, mas as palavras do iníquo ele transtornará.

[[v20-22-13]]

^<<v20-22-13,13>>^ Diz o preguiçoso: Um leão está lá fora; serei morto no meio das ruas.

[[v20-22-14]]

^<<v20-22-14,14>>^ Cova profunda é a boca da mulher estranha; aquele contra quem o SENHOR se irar cairá nela.

[[v20-22-15]]

^<<v20-22-15,15>>^ A estultícia está ligada ao coração da criança, mas a vara da disciplina a afastará dela.

[[v20-22-16]]

^<<v20-22-16,16>>^ O que oprime ao pobre para enriquecer a si ou o que dá ao rico certamente empobrecerá.

[[v20-22-17]]

^<<v20-22-17,17>>^ Inclina o ouvido, e ouve as palavras dos sábios, e aplica o coração ao meu conhecimento.

[[v20-22-18]]

^<<v20-22-18,18>>^ Porque é coisa agradável os guardares no teu coração e os aplicares todos aos teus lábios.

[[v20-22-19]]

^<<v20-22-19,19>>^ Para que a tua confiança esteja no SENHOR, quero dar-te hoje a instrução, a ti mesmo.

[[v20-22-20]]

^<<v20-22-20,20>>^ Porventura, não te escrevi excelentes coisas acerca de conselhos e conhecimentos,

[[v20-22-21]]

^<<v20-22-21,21>>^ para mostrar-te a certeza das palavras da verdade, a fim de que possas responder claramente aos que te enviarem?

[[v20-22-22]]

^<<v20-22-22,22>>^ Não roubes ao pobre, porque é pobre, nem oprimas em juízo ao aflito,

[[v20-22-23]]

^<<v20-22-23,23>>^ porque o SENHOR defenderá a causa deles e tirará a vida aos que os despojam.

[[v20-22-24]]

^<<v20-22-24,24>>^ Não te associes com o iracundo, nem andes com o homem colérico,

[[v20-22-25]]

^<<v20-22-25,25>>^ para que não aprendas as suas veredas e, assim, enlaces a tua alma.

[[v20-22-26]]

^<<v20-22-26,26>>^ Não estejas entre os que se comprometem e ficam por fiadores de dívidas,

[[v20-22-27]]

^<<v20-22-27,27>>^ pois, se não tens com que pagar, por que arriscas perder a cama de debaixo de ti?

[[v20-22-28]]

^<<v20-22-28,28>>^ Não removas os marcos antigos que puseram teus pais.

[[v20-22-29]]

^<<v20-22-29,29>>^ Vês a um homem perito na sua obra? Perante reis será posto; não entre a plebe.

'''

xref:020-proverbios/020-proverbios-021.adoc#v20-21-0[&#60; Capítulo Anterior] | <<v20-22-0,Topo>> | xref:020-proverbios/020-proverbios-023.adoc#v20-23-0[Próximo Capítulo &#62;]