include::./index.adoc[]

[[v20-14-0]]
=== Provérbios, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-14-1]]

^<<v20-14-1,1>>^ A mulher sábia edifica a sua casa, mas a insensata, com as próprias mãos, a derriba.

[[v20-14-2]]

^<<v20-14-2,2>>^ O que anda na retidão teme ao SENHOR, mas o que anda em caminhos tortuosos, esse o despreza.

[[v20-14-3]]

^<<v20-14-3,3>>^ Está na boca do insensato a vara para a sua própria soberba, mas os lábios do prudente o preservarão.

[[v20-14-4]]

^<<v20-14-4,4>>^ Não havendo bois, o celeiro fica limpo, mas pela força do boi há abundância de colheitas.

[[v20-14-5]]

^<<v20-14-5,5>>^ A testemunha verdadeira não mente, mas a falsa se desboca em mentiras.

[[v20-14-6]]

^<<v20-14-6,6>>^ O escarnecedor procura a sabedoria e não a encontra, mas para o prudente o conhecimento é fácil.

[[v20-14-7]]

^<<v20-14-7,7>>^ Foge da presença do homem insensato, porque nele não divisarás lábios de conhecimento.

[[v20-14-8]]

^<<v20-14-8,8>>^ A sabedoria do prudente é entender o seu próprio caminho, mas a estultícia dos insensatos é enganadora.

[[v20-14-9]]

^<<v20-14-9,9>>^ Os loucos zombam do pecado, mas entre os retos há boa vontade.

[[v20-14-10]]

^<<v20-14-10,10>>^ O coração conhece a sua própria amargura, e da sua alegria não participará o estranho.

[[v20-14-11]]

^<<v20-14-11,11>>^ A casa dos perversos será destruída, mas a tenda dos retos florescerá.

[[v20-14-12]]

^<<v20-14-12,12>>^ Há caminho que ao homem parece direito, mas ao cabo dá em caminhos de morte.

[[v20-14-13]]

^<<v20-14-13,13>>^ Até no riso tem dor o coração, e o fim da alegria é tristeza.

[[v20-14-14]]

^<<v20-14-14,14>>^ O infiel de coração dos seus próprios caminhos se farta, como do seu próprio proceder, o homem de bem.

[[v20-14-15]]

^<<v20-14-15,15>>^ O simples dá crédito a toda palavra, mas o prudente atenta para os seus passos.

[[v20-14-16]]

^<<v20-14-16,16>>^ O sábio é cauteloso e desvia-se do mal, mas o insensato encoleriza-se e dá-se por seguro.

[[v20-14-17]]

^<<v20-14-17,17>>^ O que presto se ira faz loucuras, e o homem de maus desígnios é odiado.

[[v20-14-18]]

^<<v20-14-18,18>>^ Os simples herdam a estultícia, mas os prudentes se coroam de conhecimento.

[[v20-14-19]]

^<<v20-14-19,19>>^ Os maus inclinam-se perante a face dos bons, e os perversos, junto às portas do justo.

[[v20-14-20]]

^<<v20-14-20,20>>^ O pobre é odiado até do vizinho, mas o rico tem muitos amigos.

[[v20-14-21]]

^<<v20-14-21,21>>^ O que despreza ao seu vizinho peca, mas o que se compadece dos pobres é feliz.

[[v20-14-22]]

^<<v20-14-22,22>>^ Acaso, não erram os que maquinam o mal? Mas amor e fidelidade haverá para os que planejam o bem.

[[v20-14-23]]

^<<v20-14-23,23>>^ Em todo trabalho há proveito; meras palavras, porém, levam à penúria.

[[v20-14-24]]

^<<v20-14-24,24>>^ Aos sábios a riqueza é coroa, mas a estultícia dos insensatos não passa de estultícia.

[[v20-14-25]]

^<<v20-14-25,25>>^ A testemunha verdadeira livra almas, mas o que se desboca em mentiras é enganador.

[[v20-14-26]]

^<<v20-14-26,26>>^ No temor do SENHOR, tem o homem forte amparo, e isso é refúgio para os seus filhos.

[[v20-14-27]]

^<<v20-14-27,27>>^ O temor do SENHOR é fonte de vida para evitar os laços da morte.

[[v20-14-28]]

^<<v20-14-28,28>>^ Na multidão do povo, está a glória do rei, mas, na falta de povo, a ruína do príncipe.

[[v20-14-29]]

^<<v20-14-29,29>>^ O longânimo é grande em entendimento, mas o de ânimo precipitado exalta a loucura.

[[v20-14-30]]

^<<v20-14-30,30>>^ O ânimo sereno é a vida do corpo, mas a inveja é a podridão dos ossos.

[[v20-14-31]]

^<<v20-14-31,31>>^ O que oprime ao pobre insulta aquele que o criou, mas a este honra o que se compadece do necessitado.

[[v20-14-32]]

^<<v20-14-32,32>>^ Pela sua malícia é derribado o perverso, mas o justo, ainda morrendo, tem esperança.

[[v20-14-33]]

^<<v20-14-33,33>>^ No coração do prudente, repousa a sabedoria, mas o que há no interior dos insensatos vem a lume.

[[v20-14-34]]

^<<v20-14-34,34>>^ A justiça exalta as nações, mas o pecado é o opróbrio dos povos.

[[v20-14-35]]

^<<v20-14-35,35>>^ O servo prudente goza do favor do rei, mas o que procede indignamente é objeto do seu furor.

'''

xref:020-proverbios/020-proverbios-013.adoc#v20-13-0[&#60; Capítulo Anterior] | <<v20-14-0,Topo>> | xref:020-proverbios/020-proverbios-015.adoc#v20-15-0[Próximo Capítulo &#62;]