include::./index.adoc[]

[[v20-12-0]]
=== Provérbios, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-12-1]]

^<<v20-12-1,1>>^ Quem ama a disciplina ama o conhecimento, mas o que aborrece a repreensão é estúpido.

[[v20-12-2]]

^<<v20-12-2,2>>^ O homem de bem alcança o favor do SENHOR, mas ao homem de perversos desígnios, ele o condena.

[[v20-12-3]]

^<<v20-12-3,3>>^ O homem não se estabelece pela perversidade, mas a raiz dos justos não será removida.

[[v20-12-4]]

^<<v20-12-4,4>>^ A mulher virtuosa é a coroa do seu marido, mas a que procede vergonhosamente é como podridão nos seus ossos.

[[v20-12-5]]

^<<v20-12-5,5>>^ Os pensamentos do justo são retos, mas os conselhos do perverso, engano.

[[v20-12-6]]

^<<v20-12-6,6>>^ As palavras dos perversos são emboscadas para derramar sangue, mas a boca dos retos livra homens.

[[v20-12-7]]

^<<v20-12-7,7>>^ Os perversos serão derribados e já não são, mas a casa dos justos permanecerá.

[[v20-12-8]]

^<<v20-12-8,8>>^ Segundo o seu entendimento, será louvado o homem, mas o perverso de coração será desprezado.

[[v20-12-9]]

^<<v20-12-9,9>>^ Melhor é o que se estima em pouco e faz o seu trabalho do que o vanglorioso que tem falta de pão.

[[v20-12-10]]

^<<v20-12-10,10>>^ O justo atenta para a vida dos seus animais, mas o coração dos perversos é cruel.

[[v20-12-11]]

^<<v20-12-11,11>>^ O que lavra a sua terra será farto de pão, mas o que corre atrás de coisas vãs é falto de senso.

[[v20-12-12]]

^<<v20-12-12,12>>^ O perverso quer viver do que caçam os maus, mas a raiz dos justos produz o seu fruto.

[[v20-12-13]]

^<<v20-12-13,13>>^ Pela transgressão dos lábios o mau se enlaça, mas o justo sairá da angústia.

[[v20-12-14]]

^<<v20-12-14,14>>^ Cada um se farta de bem pelo fruto da sua boca, e o que as mãos do homem fizerem ser-lhe-á retribuído.

[[v20-12-15]]

^<<v20-12-15,15>>^ O caminho do insensato aos seus próprios olhos parece reto, mas o sábio dá ouvidos aos conselhos.

[[v20-12-16]]

^<<v20-12-16,16>>^ A ira do insensato num instante se conhece, mas o prudente oculta a afronta.

[[v20-12-17]]

^<<v20-12-17,17>>^ O que diz a verdade manifesta a justiça, mas a testemunha falsa, a fraude.

[[v20-12-18]]

^<<v20-12-18,18>>^ Alguém há cuja tagarelice é como pontas de espada, mas a língua dos sábios é medicina.

[[v20-12-19]]

^<<v20-12-19,19>>^ O lábio veraz permanece para sempre, mas a língua mentirosa, apenas um momento.

[[v20-12-20]]

^<<v20-12-20,20>>^ Há fraude no coração dos que maquinam mal, mas alegria têm os que aconselham a paz.

[[v20-12-21]]

^<<v20-12-21,21>>^ Nenhum agravo sobrevirá ao justo, mas os perversos, o mal os apanhará em cheio.

[[v20-12-22]]

^<<v20-12-22,22>>^ Os lábios mentirosos são abomináveis ao SENHOR, mas os que agem fielmente são o seu prazer.

[[v20-12-23]]

^<<v20-12-23,23>>^ O homem prudente oculta o conhecimento, mas o coração dos insensatos proclama a estultícia.

[[v20-12-24]]

^<<v20-12-24,24>>^ A mão diligente dominará, mas a remissa será sujeita a trabalhos forçados.

[[v20-12-25]]

^<<v20-12-25,25>>^ A ansiedade no coração do homem o abate, mas a boa palavra o alegra.

[[v20-12-26]]

^<<v20-12-26,26>>^ O justo serve de guia para o seu companheiro, mas o caminho dos perversos os faz errar.

[[v20-12-27]]

^<<v20-12-27,27>>^ O preguiçoso não assará a sua caça, mas o bem precioso do homem é ser ele diligente.

[[v20-12-28]]

^<<v20-12-28,28>>^ Na vereda da justiça, está a vida, e no caminho da sua carreira não há morte.

'''

xref:020-proverbios/020-proverbios-011.adoc#v20-11-0[&#60; Capítulo Anterior] | <<v20-12-0,Topo>> | xref:020-proverbios/020-proverbios-013.adoc#v20-13-0[Próximo Capítulo &#62;]