include::./index.adoc[]

[[v20-8-0]]
=== Provérbios, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-8-1]]

^<<v20-8-1,1>>^ Não clama, porventura, a Sabedoria, e o Entendimento não faz ouvir a sua voz?

[[v20-8-2]]

^<<v20-8-2,2>>^ No cimo das alturas, junto ao caminho, nas encruzilhadas das veredas ela se coloca;

[[v20-8-3]]

^<<v20-8-3,3>>^ junto às portas, à entrada da cidade, à entrada das portas está gritando:

[[v20-8-4]]

^<<v20-8-4,4>>^ A vós outros, ó homens, clamo; e a minha voz se dirige aos filhos dos homens.

[[v20-8-5]]

^<<v20-8-5,5>>^ Entendei, ó simples, a prudência; e vós, néscios, entendei a sabedoria.

[[v20-8-6]]

^<<v20-8-6,6>>^ Ouvi, pois falarei coisas excelentes; os meus lábios proferirão coisas retas.

[[v20-8-7]]

^<<v20-8-7,7>>^ Porque a minha boca proclamará a verdade; os meus lábios abominam a impiedade.

[[v20-8-8]]

^<<v20-8-8,8>>^ São justas todas as palavras da minha boca; não há nelas nenhuma coisa torta, nem perversa.

[[v20-8-9]]

^<<v20-8-9,9>>^ Todas são retas para quem as entende e justas, para os que acham o conhecimento.

[[v20-8-10]]

^<<v20-8-10,10>>^ Aceitai o meu ensino, e não a prata, e o conhecimento, antes do que o ouro escolhido.

[[v20-8-11]]

^<<v20-8-11,11>>^ Porque melhor é a sabedoria do que joias, e de tudo o que se deseja nada se pode comparar com ela.

[[v20-8-12]]

^<<v20-8-12,12>>^ Eu, a Sabedoria, habito com a prudência e disponho de conhecimentos e de conselhos.

[[v20-8-13]]

^<<v20-8-13,13>>^ O temor do SENHOR consiste em aborrecer o mal; a soberba, a arrogância, o mau caminho e a boca perversa, eu os aborreço.

[[v20-8-14]]

^<<v20-8-14,14>>^ Meu é o conselho e a verdadeira sabedoria, eu sou o Entendimento, minha é a fortaleza.

[[v20-8-15]]

^<<v20-8-15,15>>^ Por meu intermédio, reinam os reis, e os príncipes decretam justiça.

[[v20-8-16]]

^<<v20-8-16,16>>^ Por meu intermédio, governam os príncipes, os nobres e todos os juízes da terra.

[[v20-8-17]]

^<<v20-8-17,17>>^ Eu amo os que me amam; os que me procuram me acham.

[[v20-8-18]]

^<<v20-8-18,18>>^ Riquezas e honra estão comigo, bens duráveis e justiça.

[[v20-8-19]]

^<<v20-8-19,19>>^ Melhor é o meu fruto do que o ouro, do que o ouro refinado; e o meu rendimento, melhor do que a prata escolhida.

[[v20-8-20]]

^<<v20-8-20,20>>^ Ando pelo caminho da justiça, no meio das veredas do juízo,

[[v20-8-21]]

^<<v20-8-21,21>>^ para dotar de bens os que me amam e lhes encher os tesouros.

[[v20-8-22]]

^<<v20-8-22,22>>^ O SENHOR me possuía no início de sua obra, antes de suas obras mais antigas.

[[v20-8-23]]

^<<v20-8-23,23>>^ Desde a eternidade fui estabelecida, desde o princípio, antes do começo da terra.

[[v20-8-24]]

^<<v20-8-24,24>>^ Antes de haver abismos, eu nasci, e antes ainda de haver fontes carregadas de águas.

[[v20-8-25]]

^<<v20-8-25,25>>^ Antes que os montes fossem firmados, antes de haver outeiros, eu nasci.

[[v20-8-26]]

^<<v20-8-26,26>>^ Ainda ele não tinha feito a terra, nem as amplidões, nem sequer o princípio do pó do mundo.

[[v20-8-27]]

^<<v20-8-27,27>>^ Quando ele preparava os céus, aí estava eu; quando traçava o horizonte sobre a face do abismo;

[[v20-8-28]]

^<<v20-8-28,28>>^ quando firmava as nuvens de cima; quando estabelecia as fontes do abismo;

[[v20-8-29]]

^<<v20-8-29,29>>^ quando fixava ao mar o seu limite, para que as águas não traspassassem os seus limites; quando compunha os fundamentos da terra;

[[v20-8-30]]

^<<v20-8-30,30>>^ então, eu estava com ele e era seu arquiteto, dia após dia, eu era as suas delícias, folgando perante ele em todo o tempo;

[[v20-8-31]]

^<<v20-8-31,31>>^ regozijando-me no seu mundo habitável e achando as minhas delícias com os filhos dos homens.

[[v20-8-32]]

^<<v20-8-32,32>>^ Agora, pois, filhos, ouvi-me, porque felizes serão os que guardarem os meus caminhos.

[[v20-8-33]]

^<<v20-8-33,33>>^ Ouvi o ensino, sede sábios e não o rejeiteis.

[[v20-8-34]]

^<<v20-8-34,34>>^ Feliz o homem que me dá ouvidos, velando dia a dia às minhas portas, esperando às ombreiras da minha entrada.

[[v20-8-35]]

^<<v20-8-35,35>>^ Porque o que me acha acha a vida e alcança favor do SENHOR.

[[v20-8-36]]

^<<v20-8-36,36>>^ Mas o que peca contra mim violenta a própria alma. Todos os que me aborrecem amam a morte.

'''

xref:020-proverbios/020-proverbios-007.adoc#v20-7-0[&#60; Capítulo Anterior] | <<v20-8-0,Topo>> | xref:020-proverbios/020-proverbios-009.adoc#v20-9-0[Próximo Capítulo &#62;]