include::./index.adoc[]

[[v20-15-0]]
=== Provérbios, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-15-1]]

^<<v20-15-1,1>>^ A resposta branda desvia o furor, mas a palavra dura suscita a ira.

[[v20-15-2]]

^<<v20-15-2,2>>^ A língua dos sábios adorna o conhecimento, mas a boca dos insensatos derrama a estultícia.

[[v20-15-3]]

^<<v20-15-3,3>>^ Os olhos do SENHOR estão em todo lugar, contemplando os maus e os bons.

[[v20-15-4]]

^<<v20-15-4,4>>^ A língua serena é árvore de vida, mas a perversa quebranta o espírito.

[[v20-15-5]]

^<<v20-15-5,5>>^ O insensato despreza a instrução de seu pai, mas o que atende à repreensão consegue a prudência.

[[v20-15-6]]

^<<v20-15-6,6>>^ Na casa do justo há grande tesouro, mas na renda dos perversos há perturbação.

[[v20-15-7]]

^<<v20-15-7,7>>^ A língua dos sábios derrama o conhecimento, mas o coração dos insensatos não procede assim.

[[v20-15-8]]

^<<v20-15-8,8>>^ O sacrifício dos perversos é abominável ao SENHOR, mas a oração dos retos é o seu contentamento.

[[v20-15-9]]

^<<v20-15-9,9>>^ O caminho do perverso é abominação ao SENHOR, mas este ama o que segue a justiça.

[[v20-15-10]]

^<<v20-15-10,10>>^ Disciplina rigorosa há para o que deixa a vereda, e o que odeia a repreensão morrerá.

[[v20-15-11]]

^<<v20-15-11,11>>^ O além e o abismo estão descobertos perante o SENHOR; quanto mais o coração dos filhos dos homens!

[[v20-15-12]]

^<<v20-15-12,12>>^ O escarnecedor não ama àquele que o repreende, nem se chegará para os sábios.

[[v20-15-13]]

^<<v20-15-13,13>>^ O coração alegre aformoseia o rosto, mas com a tristeza do coração o espírito se abate.

[[v20-15-14]]

^<<v20-15-14,14>>^ O coração sábio procura o conhecimento, mas a boca dos insensatos se apascenta de estultícia.

[[v20-15-15]]

^<<v20-15-15,15>>^ Todos os dias do aflito são maus, mas a alegria do coração é banquete contínuo.

[[v20-15-16]]

^<<v20-15-16,16>>^ Melhor é o pouco, havendo o temor do SENHOR, do que grande tesouro onde há inquietação.

[[v20-15-17]]

^<<v20-15-17,17>>^ Melhor é um prato de hortaliças onde há amor do que o boi cevado e, com ele, o ódio.

[[v20-15-18]]

^<<v20-15-18,18>>^ O homem iracundo suscita contendas, mas o longânimo apazigua a luta.

[[v20-15-19]]

^<<v20-15-19,19>>^ O caminho do preguiçoso é como que cercado de espinhos, mas a vereda dos retos é plana.

[[v20-15-20]]

^<<v20-15-20,20>>^ O filho sábio alegra a seu pai, mas o homem insensato despreza a sua mãe.

[[v20-15-21]]

^<<v20-15-21,21>>^ A estultícia é alegria para o que carece de entendimento, mas o homem sábio anda retamente.

[[v20-15-22]]

^<<v20-15-22,22>>^ Onde não há conselho fracassam os projetos, mas com os muitos conselheiros há bom êxito.

[[v20-15-23]]

^<<v20-15-23,23>>^ O homem se alegra em dar resposta adequada, e a palavra, a seu tempo, quão boa é!

[[v20-15-24]]

^<<v20-15-24,24>>^ Para o sábio há o caminho da vida que o leva para cima, a fim de evitar o inferno, embaixo.

[[v20-15-25]]

^<<v20-15-25,25>>^ O SENHOR deita por terra a casa dos soberbos; contudo, mantém a herança da viúva.

[[v20-15-26]]

^<<v20-15-26,26>>^ Abomináveis são para o SENHOR os desígnios do mau, mas as palavras bondosas lhe são aprazíveis.

[[v20-15-27]]

^<<v20-15-27,27>>^ O que é ávido por lucro desonesto transtorna a sua casa, mas o que odeia o suborno, esse viverá.

[[v20-15-28]]

^<<v20-15-28,28>>^ O coração do justo medita o que há de responder, mas a boca dos perversos transborda maldades.

[[v20-15-29]]

^<<v20-15-29,29>>^ O SENHOR está longe dos perversos, mas atende à oração dos justos.

[[v20-15-30]]

^<<v20-15-30,30>>^ O olhar de amigo alegra ao coração; as boas-novas fortalecem até os ossos.

[[v20-15-31]]

^<<v20-15-31,31>>^ Os ouvidos que atendem à repreensão salutar no meio dos sábios têm a sua morada.

[[v20-15-32]]

^<<v20-15-32,32>>^ O que rejeita a disciplina menospreza a sua alma, porém o que atende à repreensão adquire entendimento.

[[v20-15-33]]

^<<v20-15-33,33>>^ O temor do SENHOR é a instrução da sabedoria, e a humildade precede a honra.

'''

xref:020-proverbios/020-proverbios-014.adoc#v20-14-0[&#60; Capítulo Anterior] | <<v20-15-0,Topo>> | xref:020-proverbios/020-proverbios-016.adoc#v20-16-0[Próximo Capítulo &#62;]