include::./index.adoc[]

[[v20-28-0]]
=== Provérbios, 28
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-28-1]]

^<<v20-28-1,1>>^ Fogem os perversos, sem que ninguém os persiga; mas o justo é intrépido como o leão.

[[v20-28-2]]

^<<v20-28-2,2>>^ Por causa da transgressão da terra, mudam-se frequentemente os príncipes, mas por um, sábio e prudente, se faz estável a sua ordem.

[[v20-28-3]]

^<<v20-28-3,3>>^ O homem pobre que oprime os pobres é como chuva que a tudo arrasta e não deixa trigo.

[[v20-28-4]]

^<<v20-28-4,4>>^ Os que desamparam a lei louvam o perverso, mas os que guardam a lei se indignam contra ele.

[[v20-28-5]]

^<<v20-28-5,5>>^ Os homens maus não entendem o que é justo, mas os que buscam o SENHOR entendem tudo.

[[v20-28-6]]

^<<v20-28-6,6>>^ Melhor é o pobre que anda na sua integridade do que o perverso, nos seus caminhos, ainda que seja rico.

[[v20-28-7]]

^<<v20-28-7,7>>^ O que guarda a lei é filho prudente, mas o companheiro de libertinos envergonha a seu pai.

[[v20-28-8]]

^<<v20-28-8,8>>^ O que aumenta os seus bens com juros e ganância ajunta-os para o que se compadece do pobre.

[[v20-28-9]]

^<<v20-28-9,9>>^ O que desvia os ouvidos de ouvir a lei, até a sua oração será abominável.

[[v20-28-10]]

^<<v20-28-10,10>>^ O que desvia os retos para o mau caminho, ele mesmo cairá na cova que fez, mas os íntegros herdarão o bem.

[[v20-28-11]]

^<<v20-28-11,11>>^ O homem rico é sábio aos seus próprios olhos; mas o pobre que é sábio sabe sondá-lo.

[[v20-28-12]]

^<<v20-28-12,12>>^ Quando triunfam os justos, há grande festividade; quando, porém, sobem os perversos, os homens se escondem.

[[v20-28-13]]

^<<v20-28-13,13>>^ O que encobre as suas transgressões jamais prosperará; mas o que as confessa e deixa alcançará misericórdia.

[[v20-28-14]]

^<<v20-28-14,14>>^ Feliz o homem constante no temor de Deus; mas o que endurece o coração cairá no mal.

[[v20-28-15]]

^<<v20-28-15,15>>^ Como leão que ruge e urso que ataca, assim é o perverso que domina sobre um povo pobre.

[[v20-28-16]]

^<<v20-28-16,16>>^ O príncipe falto de inteligência multiplica as opressões, mas o que aborrece a avareza viverá muitos anos.

[[v20-28-17]]

^<<v20-28-17,17>>^ O homem carregado do sangue de outrem fugirá até à cova; ninguém o detenha.

[[v20-28-18]]

^<<v20-28-18,18>>^ O que anda em integridade será salvo, mas o perverso em seus caminhos cairá logo.

[[v20-28-19]]

^<<v20-28-19,19>>^ O que lavra a sua terra virá a fartar-se de pão, mas o que se ajunta a vadios se fartará de pobreza.

[[v20-28-20]]

^<<v20-28-20,20>>^ O homem fiel será cumulado de bênçãos, mas o que se apressa a enriquecer não passará sem castigo.

[[v20-28-21]]

^<<v20-28-21,21>>^ Parcialidade não é bom, porque até por um bocado de pão o homem prevaricará.

[[v20-28-22]]

^<<v20-28-22,22>>^ Aquele que tem olhos invejosos corre atrás das riquezas, mas não sabe que há de vir sobre ele a penúria.

[[v20-28-23]]

^<<v20-28-23,23>>^ O que repreende ao homem achará, depois, mais favor do que aquele que lisonjeia com a língua.

[[v20-28-24]]

^<<v20-28-24,24>>^ O que rouba a seu pai ou a sua mãe e diz: Não é pecado, companheiro é do destruidor.

[[v20-28-25]]

^<<v20-28-25,25>>^ O cobiçoso levanta contendas, mas o que confia no SENHOR prosperará.

[[v20-28-26]]

^<<v20-28-26,26>>^ O que confia no seu próprio coração é insensato, mas o que anda em sabedoria será salvo.

[[v20-28-27]]

^<<v20-28-27,27>>^ O que dá ao pobre não terá falta, mas o que dele esconde os olhos será cumulado de maldições.

[[v20-28-28]]

^<<v20-28-28,28>>^ Quando sobem os perversos, os homens se escondem, mas, quando eles perecem, os justos se multiplicam.

'''

xref:020-proverbios/020-proverbios-027.adoc#v20-27-0[&#60; Capítulo Anterior] | <<v20-28-0,Topo>> | xref:020-proverbios/020-proverbios-029.adoc#v20-29-0[Próximo Capítulo &#62;]