include::./index.adoc[]

[[v20-11-0]]
=== Provérbios, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-11-1]]

^<<v20-11-1,1>>^ Balança enganosa é abominação para o SENHOR, mas o peso justo é o seu prazer.

[[v20-11-2]]

^<<v20-11-2,2>>^ Em vindo a soberba, sobrevém a desonra, mas com os humildes está a sabedoria.

[[v20-11-3]]

^<<v20-11-3,3>>^ A integridade dos retos os guia; mas, aos pérfidos, a sua mesma falsidade os destrói.

[[v20-11-4]]

^<<v20-11-4,4>>^ As riquezas de nada aproveitam no dia da ira, mas a justiça livra da morte.

[[v20-11-5]]

^<<v20-11-5,5>>^ A justiça do íntegro endireita o seu caminho, mas pela sua impiedade cai o perverso.

[[v20-11-6]]

^<<v20-11-6,6>>^ A justiça dos retos os livrará, mas na sua maldade os pérfidos serão apanhados.

[[v20-11-7]]

^<<v20-11-7,7>>^ Morrendo o homem perverso, morre a sua esperança, e a expectação da iniquidade se desvanece.

[[v20-11-8]]

^<<v20-11-8,8>>^ O justo é libertado da angústia, e o perverso a recebe em seu lugar.

[[v20-11-9]]

^<<v20-11-9,9>>^ O ímpio, com a boca, destrói o próximo, mas os justos são libertados pelo conhecimento.

[[v20-11-10]]

^<<v20-11-10,10>>^ No bem-estar dos justos exulta a cidade, e, perecendo os perversos, há júbilo.

[[v20-11-11]]

^<<v20-11-11,11>>^ Pela bênção que os retos suscitam, a cidade se exalta, mas pela boca dos perversos é derribada.

[[v20-11-12]]

^<<v20-11-12,12>>^ O que despreza o próximo é falto de senso, mas o homem prudente, este se cala.

[[v20-11-13]]

^<<v20-11-13,13>>^ O mexeriqueiro descobre o segredo, mas o fiel de espírito o encobre.

[[v20-11-14]]

^<<v20-11-14,14>>^ Não havendo sábia direção, cai o povo, mas na multidão de conselheiros há segurança.

[[v20-11-15]]

^<<v20-11-15,15>>^ Quem fica por fiador de outrem sofrerá males, mas o que foge de o ser estará seguro.

[[v20-11-16]]

^<<v20-11-16,16>>^ A mulher graciosa alcança honra, como os poderosos adquirem riqueza.

[[v20-11-17]]

^<<v20-11-17,17>>^ O homem bondoso faz bem a si mesmo, mas o cruel a si mesmo se fere.

[[v20-11-18]]

^<<v20-11-18,18>>^ O perverso recebe um salário ilusório, mas o que semeia justiça terá recompensa verdadeira.

[[v20-11-19]]

^<<v20-11-19,19>>^ Tão certo como a justiça conduz para a vida, assim o que segue o mal, para a sua morte o faz.

[[v20-11-20]]

^<<v20-11-20,20>>^ Abomináveis para o SENHOR são os perversos de coração, mas os que andam em integridade são o seu prazer.

[[v20-11-21]]

^<<v20-11-21,21>>^ O mau, é evidente, não ficará sem castigo, mas a geração dos justos é livre.

[[v20-11-22]]

^<<v20-11-22,22>>^ Como joia de ouro em focinho de porco, assim é a mulher formosa que não tem discrição.

[[v20-11-23]]

^<<v20-11-23,23>>^ O desejo dos justos tende somente para o bem, mas a expectação dos perversos redunda em ira.

[[v20-11-24]]

^<<v20-11-24,24>>^ A quem dá liberalmente, ainda se lhe acrescenta mais e mais; ao que retém mais do que é justo, ser-lhe-á em pura perda.

[[v20-11-25]]

^<<v20-11-25,25>>^ A alma generosa prosperará, e quem dá a beber será dessedentado.

[[v20-11-26]]

^<<v20-11-26,26>>^ Ao que retém o trigo, o povo o amaldiçoa, mas bênção haverá sobre a cabeça do seu vendedor.

[[v20-11-27]]

^<<v20-11-27,27>>^ Quem procura o bem alcança favor, mas ao que corre atrás do mal, este lhe sobrevirá.

[[v20-11-28]]

^<<v20-11-28,28>>^ Quem confia nas suas riquezas cairá, mas os justos reverdecerão como a folhagem.

[[v20-11-29]]

^<<v20-11-29,29>>^ O que perturba a sua casa herda o vento, e o insensato é servo do sábio de coração.

[[v20-11-30]]

^<<v20-11-30,30>>^ O fruto do justo é árvore de vida, e o que ganha almas é sábio.

[[v20-11-31]]

^<<v20-11-31,31>>^ Se o justo é punido na terra, quanto mais o perverso e o pecador!

'''

xref:020-proverbios/020-proverbios-010.adoc#v20-10-0[&#60; Capítulo Anterior] | <<v20-11-0,Topo>> | xref:020-proverbios/020-proverbios-012.adoc#v20-12-0[Próximo Capítulo &#62;]