include::./index.adoc[]

[[v20-18-0]]
=== Provérbios, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-18-1]]

^<<v20-18-1,1>>^ O solitário busca o seu próprio interesse e insurge-se contra a verdadeira sabedoria.

[[v20-18-2]]

^<<v20-18-2,2>>^ O insensato não tem prazer no entendimento, senão em externar o seu interior.

[[v20-18-3]]

^<<v20-18-3,3>>^ Vindo a perversidade, vem também o desprezo; e, com a ignomínia, a vergonha.

[[v20-18-4]]

^<<v20-18-4,4>>^ Águas profundas são as palavras da boca do homem, e a fonte da sabedoria, ribeiros transbordantes.

[[v20-18-5]]

^<<v20-18-5,5>>^ Não é bom ser parcial com o perverso, para torcer o direito contra os justos.

[[v20-18-6]]

^<<v20-18-6,6>>^ Os lábios do insensato entram na contenda, e por açoites brada a sua boca.

[[v20-18-7]]

^<<v20-18-7,7>>^ A boca do insensato é a sua própria destruição, e os seus lábios, um laço para a sua alma.

[[v20-18-8]]

^<<v20-18-8,8>>^ As palavras do maldizente são doces bocados que descem para o mais interior do ventre.

[[v20-18-9]]

^<<v20-18-9,9>>^ Quem é negligente na sua obra já é irmão do desperdiçador.

[[v20-18-10]]

^<<v20-18-10,10>>^ Torre forte é o nome do SENHOR, à qual o justo se acolhe e está seguro.

[[v20-18-11]]

^<<v20-18-11,11>>^ Os bens do rico lhe são cidade forte e, segundo imagina, uma alta muralha.

[[v20-18-12]]

^<<v20-18-12,12>>^ Antes da ruína, gaba-se o coração do homem, e diante da honra vai a humildade.

[[v20-18-13]]

^<<v20-18-13,13>>^ Responder antes de ouvir é estultícia e vergonha.

[[v20-18-14]]

^<<v20-18-14,14>>^ O espírito firme sustém o homem na sua doença, mas o espírito abatido, quem o pode suportar?

[[v20-18-15]]

^<<v20-18-15,15>>^ O coração do sábio adquire o conhecimento, e o ouvido dos sábios procura o saber.

[[v20-18-16]]

^<<v20-18-16,16>>^ O presente que o homem faz alarga-lhe o caminho e leva-o perante os grandes.

[[v20-18-17]]

^<<v20-18-17,17>>^ O que começa o pleito parece justo, até que vem o outro e o examina.

[[v20-18-18]]

^<<v20-18-18,18>>^ Pelo lançar da sorte, cessam os pleitos, e se decide a causa entre os poderosos.

[[v20-18-19]]

^<<v20-18-19,19>>^ O irmão ofendido resiste mais que uma fortaleza; suas contendas são ferrolhos de um castelo.

[[v20-18-20]]

^<<v20-18-20,20>>^ Do fruto da boca o coração se farta, do que produzem os lábios se satisfaz.

[[v20-18-21]]

^<<v20-18-21,21>>^ A morte e a vida estão no poder da língua; o que bem a utiliza come do seu fruto.

[[v20-18-22]]

^<<v20-18-22,22>>^ O que acha uma esposa acha o bem e alcançou a benevolência do SENHOR.

[[v20-18-23]]

^<<v20-18-23,23>>^ O pobre fala com súplicas, porém o rico responde com durezas.

[[v20-18-24]]

^<<v20-18-24,24>>^ O homem que tem muitos amigos sai perdendo; mas há amigo mais chegado do que um irmão.

'''

xref:020-proverbios/020-proverbios-017.adoc#v20-17-0[&#60; Capítulo Anterior] | <<v20-18-0,Topo>> | xref:020-proverbios/020-proverbios-019.adoc#v20-19-0[Próximo Capítulo &#62;]