include::./index.adoc[]

[[v20-5-0]]
=== Provérbios, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-5-1]]

^<<v20-5-1,1>>^ Filho meu, atende a minha sabedoria; à minha inteligência inclina os ouvidos

[[v20-5-2]]

^<<v20-5-2,2>>^ para que conserves a discrição, e os teus lábios guardem o conhecimento;

[[v20-5-3]]

^<<v20-5-3,3>>^ porque os lábios da mulher adúltera destilam favos de mel, e as suas palavras são mais suaves do que o azeite;

[[v20-5-4]]

^<<v20-5-4,4>>^ mas o fim dela é amargoso como o absinto, agudo, como a espada de dois gumes.

[[v20-5-5]]

^<<v20-5-5,5>>^ Os seus pés descem à morte; os seus passos conduzem-na ao inferno.

[[v20-5-6]]

^<<v20-5-6,6>>^ Ela não pondera a vereda da vida; anda errante nos seus caminhos e não o sabe.

[[v20-5-7]]

^<<v20-5-7,7>>^ Agora, pois, filho, dá-me ouvidos e não te desvies das palavras da minha boca.

[[v20-5-8]]

^<<v20-5-8,8>>^ Afasta o teu caminho da mulher adúltera e não te aproximes da porta da sua casa;

[[v20-5-9]]

^<<v20-5-9,9>>^ para que não dês a outrem a tua honra, nem os teus anos, a cruéis;

[[v20-5-10]]

^<<v20-5-10,10>>^ para que dos teus bens não se fartem os estranhos, e o fruto do teu trabalho não entre em casa alheia;

[[v20-5-11]]

^<<v20-5-11,11>>^ e gemas no fim de tua vida, quando se consumirem a tua carne e o teu corpo,

[[v20-5-12]]

^<<v20-5-12,12>>^ e digas: Como aborreci o ensino! E desprezou o meu coração a disciplina!

[[v20-5-13]]

^<<v20-5-13,13>>^ E não escutei a voz dos que me ensinavam, nem a meus mestres inclinei os ouvidos!

[[v20-5-14]]

^<<v20-5-14,14>>^ Quase que me achei em todo mal que sucedeu no meio da assembleia e da congregação.

[[v20-5-15]]

^<<v20-5-15,15>>^ Bebe a água da tua própria cisterna e das correntes do teu poço.

[[v20-5-16]]

^<<v20-5-16,16>>^ Derramar-se-iam por fora as tuas fontes, e, pelas praças, os ribeiros de águas?

[[v20-5-17]]

^<<v20-5-17,17>>^ Sejam para ti somente e não para os estranhos contigo.

[[v20-5-18]]

^<<v20-5-18,18>>^ Seja bendito o teu manancial, e alegra-te com a mulher da tua mocidade,

[[v20-5-19]]

^<<v20-5-19,19>>^ corça de amores e gazela graciosa. Saciem-te os seus seios em todo o tempo; e embriaga-te sempre com as suas carícias.

[[v20-5-20]]

^<<v20-5-20,20>>^ Por que, filho meu, andarias cego pela estranha e abraçarias o peito de outra?

[[v20-5-21]]

^<<v20-5-21,21>>^ Porque os caminhos do homem estão perante os olhos do SENHOR, e ele considera todas as suas veredas.

[[v20-5-22]]

^<<v20-5-22,22>>^ Quanto ao perverso, as suas iniquidades o prenderão, e com as cordas do seu pecado será detido.

[[v20-5-23]]

^<<v20-5-23,23>>^ Ele morrerá pela falta de disciplina, e, pela sua muita loucura, perdido, cambaleia.

'''

xref:020-proverbios/020-proverbios-004.adoc#v20-4-0[&#60; Capítulo Anterior] | <<v20-5-0,Topo>> | xref:020-proverbios/020-proverbios-006.adoc#v20-6-0[Próximo Capítulo &#62;]