include::./index.adoc[]

[[v20-27-0]]
=== Provérbios, 27
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-27-1]]

^<<v20-27-1,1>>^ Não te glories do dia de amanhã, porque não sabes o que trará à luz.

[[v20-27-2]]

^<<v20-27-2,2>>^ Seja outro o que te louve, e não a tua boca; o estrangeiro, e não os teus lábios.

[[v20-27-3]]

^<<v20-27-3,3>>^ Pesada é a pedra, e a areia é uma carga; mas a ira do insensato é mais pesada do que uma e outra.

[[v20-27-4]]

^<<v20-27-4,4>>^ Cruel é o furor, e impetuosa, a ira, mas quem pode resistir à inveja?

[[v20-27-5]]

^<<v20-27-5,5>>^ Melhor é a repreensão franca do que o amor encoberto.

[[v20-27-6]]

^<<v20-27-6,6>>^ Leais são as feridas feitas pelo que ama, porém os beijos de quem odeia são enganosos.

[[v20-27-7]]

^<<v20-27-7,7>>^ A alma farta pisa o favo de mel, mas à alma faminta todo amargo é doce.

[[v20-27-8]]

^<<v20-27-8,8>>^ Qual ave que vagueia longe do seu ninho, tal é o homem que anda vagueando longe do seu lar.

[[v20-27-9]]

^<<v20-27-9,9>>^ Como o óleo e o perfume alegram o coração, assim, o amigo encontra doçura no conselho cordial.

[[v20-27-10]]

^<<v20-27-10,10>>^ Não abandones o teu amigo, nem o amigo de teu pai, nem entres na casa de teu irmão no dia da tua adversidade. Mais vale o vizinho perto do que o irmão longe.

[[v20-27-11]]

^<<v20-27-11,11>>^ Sê sábio, filho meu, e alegra o meu coração, para que eu saiba responder àqueles que me afrontam.

[[v20-27-12]]

^<<v20-27-12,12>>^ O prudente vê o mal e esconde-se; mas os simples passam adiante e sofrem a pena.

[[v20-27-13]]

^<<v20-27-13,13>>^ Tome-se a roupa àquele que fica fiador por outrem; e, por penhor, àquele que se obriga por mulher estranha.

[[v20-27-14]]

^<<v20-27-14,14>>^ O que bendiz ao seu vizinho em alta voz, logo de manhã, por maldição lhe atribuem o que faz.

[[v20-27-15]]

^<<v20-27-15,15>>^ O gotejar contínuo no dia de grande chuva e a mulher rixosa são semelhantes;

[[v20-27-16]]

^<<v20-27-16,16>>^ contê-la seria conter o vento, seria pegar o óleo na mão.

[[v20-27-17]]

^<<v20-27-17,17>>^ Como o ferro com o ferro se afia, assim, o homem, ao seu amigo.

[[v20-27-18]]

^<<v20-27-18,18>>^ O que trata da figueira comerá do seu fruto; e o que cuida do seu senhor será honrado.

[[v20-27-19]]

^<<v20-27-19,19>>^ Como na água o rosto corresponde ao rosto, assim, o coração do homem, ao homem.

[[v20-27-20]]

^<<v20-27-20,20>>^ O inferno e o abismo nunca se fartam, e os olhos do homem nunca se satisfazem.

[[v20-27-21]]

^<<v20-27-21,21>>^ Como o crisol prova a prata, e o forno, o ouro, assim, o homem é provado pelos louvores que recebe.

[[v20-27-22]]

^<<v20-27-22,22>>^ Ainda que pises o insensato com mão de gral entre grãos pilados de cevada, não se vai dele a sua estultícia.

[[v20-27-23]]

^<<v20-27-23,23>>^ Procura conhecer o estado das tuas ovelhas e cuida dos teus rebanhos,

[[v20-27-24]]

^<<v20-27-24,24>>^ porque as riquezas não duram para sempre, nem a coroa, de geração em geração.

[[v20-27-25]]

^<<v20-27-25,25>>^ Quando, removido o feno, aparecerem os renovos e se recolherem as ervas dos montes,

[[v20-27-26]]

^<<v20-27-26,26>>^ então, os cordeiros te darão as vestes, os bodes, o preço do campo,

[[v20-27-27]]

^<<v20-27-27,27>>^ e as cabras, leite em abundância para teu alimento, para alimento da tua casa e para sustento das tuas servas.

'''

xref:020-proverbios/020-proverbios-026.adoc#v20-26-0[&#60; Capítulo Anterior] | <<v20-27-0,Topo>> | xref:020-proverbios/020-proverbios-028.adoc#v20-28-0[Próximo Capítulo &#62;]