include::./index.adoc[]

[[v20-19-0]]
=== Provérbios, 19
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-19-1]]

^<<v20-19-1,1>>^ Melhor é o pobre que anda na sua integridade do que o perverso de lábios e tolo.

[[v20-19-2]]

^<<v20-19-2,2>>^ Não é bom proceder sem refletir, e peca quem é precipitado.

[[v20-19-3]]

^<<v20-19-3,3>>^ A estultícia do homem perverte o seu caminho, mas é contra o SENHOR que o seu coração se ira.

[[v20-19-4]]

^<<v20-19-4,4>>^ As riquezas multiplicam os amigos; mas, ao pobre, o seu próprio amigo o deixa.

[[v20-19-5]]

^<<v20-19-5,5>>^ A falsa testemunha não fica impune, e o que profere mentiras não escapa.

[[v20-19-6]]

^<<v20-19-6,6>>^ Ao generoso, muitos o adulam, e todos são amigos do que dá presentes.

[[v20-19-7]]

^<<v20-19-7,7>>^ Se os irmãos do pobre o aborrecem, quanto mais se afastarão dele os seus amigos! Corre após eles com súplicas, mas não os alcança.

[[v20-19-8]]

^<<v20-19-8,8>>^ O que adquire entendimento ama a sua alma; o que conserva a inteligência acha o bem.

[[v20-19-9]]

^<<v20-19-9,9>>^ A falsa testemunha não fica impune, e o que profere mentiras perece.

[[v20-19-10]]

^<<v20-19-10,10>>^ Ao insensato não convém a vida regalada, quanto menos ao escravo dominar os príncipes!

[[v20-19-11]]

^<<v20-19-11,11>>^ A discrição do homem o torna longânimo, e sua glória é perdoar as injúrias.

[[v20-19-12]]

^<<v20-19-12,12>>^ Como o bramido do leão, assim é a indignação do rei; mas seu favor é como o orvalho sobre a erva.

[[v20-19-13]]

^<<v20-19-13,13>>^ O filho insensato é a desgraça do pai, e um gotejar contínuo, as contenções da esposa.

[[v20-19-14]]

^<<v20-19-14,14>>^ A casa e os bens vêm como herança dos pais; mas do SENHOR, a esposa prudente.

[[v20-19-15]]

^<<v20-19-15,15>>^ A preguiça faz cair em profundo sono, e o ocioso vem a padecer fome.

[[v20-19-16]]

^<<v20-19-16,16>>^ O que guarda o mandamento guarda a sua alma; mas o que despreza os seus caminhos, esse morre.

[[v20-19-17]]

^<<v20-19-17,17>>^ Quem se compadece do pobre ao SENHOR empresta, e este lhe paga o seu benefício.

[[v20-19-18]]

^<<v20-19-18,18>>^ Castiga a teu filho, enquanto há esperança, mas não te excedas a ponto de matá-lo.

[[v20-19-19]]

^<<v20-19-19,19>>^ Homem de grande ira tem de sofrer o dano; porque, se tu o livrares, virás ainda a fazê-lo de novo.

[[v20-19-20]]

^<<v20-19-20,20>>^ Ouve o conselho e recebe a instrução, para que sejas sábio nos teus dias por vir.

[[v20-19-21]]

^<<v20-19-21,21>>^ Muitos propósitos há no coração do homem, mas o desígnio do SENHOR permanecerá.

[[v20-19-22]]

^<<v20-19-22,22>>^ O que torna agradável o homem é a sua misericórdia; o pobre é preferível ao mentiroso.

[[v20-19-23]]

^<<v20-19-23,23>>^ O temor do SENHOR conduz à vida; aquele que o tem ficará satisfeito, e mal nenhum o visitará.

[[v20-19-24]]

^<<v20-19-24,24>>^ O preguiçoso mete a mão no prato e não quer ter o trabalho de a levar à boca.

[[v20-19-25]]

^<<v20-19-25,25>>^ Quando ferires ao escarnecedor, o simples aprenderá a prudência; repreende ao sábio, e crescerá em conhecimento.

[[v20-19-26]]

^<<v20-19-26,26>>^ O que maltrata a seu pai ou manda embora a sua mãe filho é que envergonha e desonra.

[[v20-19-27]]

^<<v20-19-27,27>>^ Filho meu, se deixas de ouvir a instrução, desviar-te-ás das palavras do conhecimento.

[[v20-19-28]]

^<<v20-19-28,28>>^ A testemunha de Belial escarnece da justiça, e a boca dos perversos devora a iniquidade.

[[v20-19-29]]

^<<v20-19-29,29>>^ Preparados estão os juízos para os escarnecedores e os açoites, para as costas dos insensatos.

'''

xref:020-proverbios/020-proverbios-018.adoc#v20-18-0[&#60; Capítulo Anterior] | <<v20-19-0,Topo>> | xref:020-proverbios/020-proverbios-020.adoc#v20-20-0[Próximo Capítulo &#62;]