include::./index.adoc[]

[[v20-9-0]]
=== Provérbios, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-9-1]]

^<<v20-9-1,1>>^ A Sabedoria edificou a sua casa, lavrou as suas sete colunas.

[[v20-9-2]]

^<<v20-9-2,2>>^ Carneou os seus animais, misturou o seu vinho e arrumou a sua mesa.

[[v20-9-3]]

^<<v20-9-3,3>>^ Já deu ordens às suas criadas e, assim, convida desde as alturas da cidade:

[[v20-9-4]]

^<<v20-9-4,4>>^ Quem é simples, volte-se para aqui. Aos faltos de senso diz:

[[v20-9-5]]

^<<v20-9-5,5>>^ Vinde, comei do meu pão e bebei do vinho que misturei.

[[v20-9-6]]

^<<v20-9-6,6>>^ Deixai os insensatos e vivei; andai pelo caminho do entendimento.

[[v20-9-7]]

^<<v20-9-7,7>>^ O que repreende o escarnecedor traz afronta sobre si; e o que censura o perverso a si mesmo se injuria.

[[v20-9-8]]

^<<v20-9-8,8>>^ Não repreendas o escarnecedor, para que te não aborreça; repreende o sábio, e ele te amará.

[[v20-9-9]]

^<<v20-9-9,9>>^ Dá instrução ao sábio, e ele se fará mais sábio ainda; ensina ao justo, e ele crescerá em prudência.

[[v20-9-10]]

^<<v20-9-10,10>>^ O temor do SENHOR é o princípio da sabedoria, e o conhecimento do Santo é prudência.

[[v20-9-11]]

^<<v20-9-11,11>>^ Porque por mim se multiplicam os teus dias, e anos de vida se te acrescentarão.

[[v20-9-12]]

^<<v20-9-12,12>>^ Se és sábio, para ti mesmo o és; se és escarnecedor, tu só o suportarás.

[[v20-9-13]]

^<<v20-9-13,13>>^ A loucura é mulher apaixonada, é ignorante e não sabe coisa alguma.

[[v20-9-14]]

^<<v20-9-14,14>>^ Assenta-se à porta de sua casa, nas alturas da cidade, toma uma cadeira,

[[v20-9-15]]

^<<v20-9-15,15>>^ para dizer aos que passam e seguem direito o seu caminho:

[[v20-9-16]]

^<<v20-9-16,16>>^ Quem é simples, volte-se para aqui. E aos faltos de senso diz:

[[v20-9-17]]

^<<v20-9-17,17>>^ As águas roubadas são doces, e o pão comido às ocultas é agradável.

[[v20-9-18]]

^<<v20-9-18,18>>^ Eles, porém, não sabem que ali estão os mortos, que os seus convidados estão nas profundezas do inferno.

'''

xref:020-proverbios/020-proverbios-008.adoc#v20-8-0[&#60; Capítulo Anterior] | <<v20-9-0,Topo>> | xref:020-proverbios/020-proverbios-010.adoc#v20-10-0[Próximo Capítulo &#62;]