include::./index.adoc[]

[[v20-30-0]]
=== Provérbios, 30
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-30-1]]

^<<v20-30-1,1>>^ Palavras de Agur, filho de Jaque, de Massá. Disse o homem: Fatiguei-me, ó Deus; fatiguei-me, ó Deus, e estou exausto

[[v20-30-2]]

^<<v20-30-2,2>>^ porque sou demasiadamente estúpido para ser homem; não tenho inteligência de homem,

[[v20-30-3]]

^<<v20-30-3,3>>^ não aprendi a sabedoria, nem tenho o conhecimento do Santo.

[[v20-30-4]]

^<<v20-30-4,4>>^ Quem subiu ao céu e desceu? Quem encerrou os ventos nos seus punhos? Quem amarrou as águas na sua roupa? Quem estabeleceu todas as extremidades da terra? Qual é o seu nome, e qual é o nome de seu filho, se é que o sabes?

[[v20-30-5]]

^<<v20-30-5,5>>^ Toda palavra de Deus é pura; ele é escudo para os que nele confiam.

[[v20-30-6]]

^<<v20-30-6,6>>^ Nada acrescentes às suas palavras, para que não te repreenda, e sejas achado mentiroso.

[[v20-30-7]]

^<<v20-30-7,7>>^ Duas coisas te peço; não mas negues, antes que eu morra:

[[v20-30-8]]

^<<v20-30-8,8>>^ afasta de mim a falsidade e a mentira; não me dês nem a pobreza nem a riqueza; dá-me o pão que me for necessário;

[[v20-30-9]]

^<<v20-30-9,9>>^ para não suceder que, estando eu farto, te negue e diga: Quem é o SENHOR? Ou que, empobrecido, venha a furtar e profane o nome de Deus.

[[v20-30-10]]

^<<v20-30-10,10>>^ Não calunies o servo diante de seu senhor, para que aquele te não amaldiçoe e fiques culpado.

[[v20-30-11]]

^<<v20-30-11,11>>^ Há daqueles que amaldiçoam a seu pai e que não bendizem a sua mãe.

[[v20-30-12]]

^<<v20-30-12,12>>^ Há daqueles que são puros aos próprios olhos e que jamais foram lavados da sua imundícia.

[[v20-30-13]]

^<<v20-30-13,13>>^ Há daqueles — quão altivos são os seus olhos e levantadas as suas pálpebras!

[[v20-30-14]]

^<<v20-30-14,14>>^ Há daqueles cujos dentes são espadas, e cujos queixais são facas, para consumirem na terra os aflitos e os necessitados entre os homens.

[[v20-30-15]]

^<<v20-30-15,15>>^ A sanguessuga tem duas filhas, a saber: Dá, Dá. Há três coisas que nunca se fartam, sim, quatro que não dizem: Basta!

[[v20-30-16]]

^<<v20-30-16,16>>^ Elas são a sepultura, a madre estéril, a terra, que se não farta de água, e o fogo, que nunca diz: Basta!

[[v20-30-17]]

^<<v20-30-17,17>>^ Os olhos de quem zomba do pai ou de quem despreza a obediência à sua mãe, corvos no ribeiro os arrancarão e pelos pintãos da águia serão comidos.

[[v20-30-18]]

^<<v20-30-18,18>>^ Há três coisas que são maravilhosas demais para mim, sim, há quatro que não entendo:

[[v20-30-19]]

^<<v20-30-19,19>>^ o caminho da águia no céu, o caminho da cobra na penha, o caminho do navio no meio do mar e o caminho do homem com uma donzela.

[[v20-30-20]]

^<<v20-30-20,20>>^ Tal é o caminho da mulher adúltera: come, e limpa a boca, e diz: Não cometi maldade.

[[v20-30-21]]

^<<v20-30-21,21>>^ Sob três coisas estremece a terra, sim, sob quatro não pode subsistir:

[[v20-30-22]]

^<<v20-30-22,22>>^ sob o servo quando se torna rei; sob o insensato quando anda farto de pão;

[[v20-30-23]]

^<<v20-30-23,23>>^ sob a mulher desdenhada quando se casa; sob a serva quando se torna herdeira da sua senhora.

[[v20-30-24]]

^<<v20-30-24,24>>^ Há quatro coisas mui pequenas na terra que, porém, são mais sábias que os sábios:

[[v20-30-25]]

^<<v20-30-25,25>>^ as formigas, povo sem força; todavia, no verão preparam a sua comida;

[[v20-30-26]]

^<<v20-30-26,26>>^ os arganazes, povo não poderoso; contudo, fazem a sua casa nas rochas;

[[v20-30-27]]

^<<v20-30-27,27>>^ os gafanhotos não têm rei; contudo, marcham todos em bandos;

[[v20-30-28]]

^<<v20-30-28,28>>^ o geco, que se apanha com as mãos; contudo, está nos palácios dos reis.

[[v20-30-29]]

^<<v20-30-29,29>>^ Há três que têm passo elegante, sim, quatro que andam airosamente:

[[v20-30-30]]

^<<v20-30-30,30>>^ O leão, o mais forte entre os animais, que por ninguém torna atrás;

[[v20-30-31]]

^<<v20-30-31,31>>^ o galo, que anda ereto, o bode e o rei, a quem não se pode resistir.

[[v20-30-32]]

^<<v20-30-32,32>>^ Se procedeste insensatamente em te exaltares ou se maquinaste o mal, põe a mão na boca.

[[v20-30-33]]

^<<v20-30-33,33>>^ Porque o bater do leite produz manteiga, e o torcer do nariz produz sangue, e o açular a ira produz contendas.

'''

xref:020-proverbios/020-proverbios-029.adoc#v20-29-0[&#60; Capítulo Anterior] | <<v20-30-0,Topo>> | xref:020-proverbios/020-proverbios-031.adoc#v20-31-0[Próximo Capítulo &#62;]