include::./index.adoc[]

[[v20-3-0]]
=== Provérbios, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-3-1]]

^<<v20-3-1,1>>^ Filho meu, não te esqueças dos meus ensinos, e o teu coração guarde os meus mandamentos;

[[v20-3-2]]

^<<v20-3-2,2>>^ porque eles aumentarão os teus dias e te acrescentarão anos de vida e paz.

[[v20-3-3]]

^<<v20-3-3,3>>^ Não te desamparem a benignidade e a fidelidade; ata-as ao pescoço; escreve-as na tábua do teu coração

[[v20-3-4]]

^<<v20-3-4,4>>^ e acharás graça e boa compreensão diante de Deus e dos homens.

[[v20-3-5]]

^<<v20-3-5,5>>^ Confia no SENHOR de todo o teu coração e não te estribes no teu próprio entendimento.

[[v20-3-6]]

^<<v20-3-6,6>>^ Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.

[[v20-3-7]]

^<<v20-3-7,7>>^ Não sejas sábio aos teus próprios olhos; teme ao SENHOR e aparta-te do mal;

[[v20-3-8]]

^<<v20-3-8,8>>^ será isto saúde para o teu corpo e refrigério, para os teus ossos.

[[v20-3-9]]

^<<v20-3-9,9>>^ Honra ao SENHOR com os teus bens e com as primícias de toda a tua renda;

[[v20-3-10]]

^<<v20-3-10,10>>^ e se encherão fartamente os teus celeiros, e transbordarão de vinho os teus lagares.

[[v20-3-11]]

^<<v20-3-11,11>>^ Filho meu, não rejeites a disciplina do SENHOR, nem te enfades da sua repreensão.

[[v20-3-12]]

^<<v20-3-12,12>>^ Porque o SENHOR repreende a quem ama, assim como o pai, ao filho a quem quer bem.

[[v20-3-13]]

^<<v20-3-13,13>>^ Feliz o homem que acha sabedoria, e o homem que adquire conhecimento;

[[v20-3-14]]

^<<v20-3-14,14>>^ porque melhor é o lucro que ela dá do que o da prata, e melhor a sua renda do que o ouro mais fino.

[[v20-3-15]]

^<<v20-3-15,15>>^ Mais preciosa é do que pérolas, e tudo o que podes desejar não é comparável a ela.

[[v20-3-16]]

^<<v20-3-16,16>>^ O alongar-se da vida está na sua mão direita, na sua esquerda, riquezas e honra.

[[v20-3-17]]

^<<v20-3-17,17>>^ Os seus caminhos são caminhos deliciosos, e todas as suas veredas, paz.

[[v20-3-18]]

^<<v20-3-18,18>>^ É árvore de vida para os que a alcançam, e felizes são todos os que a retêm.

[[v20-3-19]]

^<<v20-3-19,19>>^ O SENHOR com sabedoria fundou a terra, com inteligência estabeleceu os céus.

[[v20-3-20]]

^<<v20-3-20,20>>^ Pelo seu conhecimento os abismos se rompem, e as nuvens destilam orvalho.

[[v20-3-21]]

^<<v20-3-21,21>>^ Filho meu, não se apartem estas coisas dos teus olhos; guarda a verdadeira sabedoria e o bom siso;

[[v20-3-22]]

^<<v20-3-22,22>>^ porque serão vida para a tua alma e adorno ao teu pescoço.

[[v20-3-23]]

^<<v20-3-23,23>>^ Então, andarás seguro no teu caminho, e não tropeçará o teu pé.

[[v20-3-24]]

^<<v20-3-24,24>>^ Quando te deitares, não temerás; deitar-te-ás, e o teu sono será suave.

[[v20-3-25]]

^<<v20-3-25,25>>^ Não temas o pavor repentino, nem a arremetida dos perversos, quando vier.

[[v20-3-26]]

^<<v20-3-26,26>>^ Porque o SENHOR será a tua segurança e guardará os teus pés de serem presos.

[[v20-3-27]]

^<<v20-3-27,27>>^ Não te furtes a fazer o bem a quem de direito, estando na tua mão o poder de fazê-lo.

[[v20-3-28]]

^<<v20-3-28,28>>^ Não digas ao teu próximo: Vai e volta amanhã; então, to darei, se o tens agora contigo.

[[v20-3-29]]

^<<v20-3-29,29>>^ Não maquines o mal contra o teu próximo, pois habita junto de ti confiadamente.

[[v20-3-30]]

^<<v20-3-30,30>>^ Jamais pleiteies com alguém sem razão, se te não houver feito mal.

[[v20-3-31]]

^<<v20-3-31,31>>^ Não tenhas inveja do homem violento, nem sigas nenhum de seus caminhos;

[[v20-3-32]]

^<<v20-3-32,32>>^ porque o SENHOR abomina o perverso, mas aos retos trata com intimidade.

[[v20-3-33]]

^<<v20-3-33,33>>^ A maldição do SENHOR habita na casa do perverso, porém a morada dos justos ele abençoa.

[[v20-3-34]]

^<<v20-3-34,34>>^ Certamente, ele escarnece dos escarnecedores, mas dá graça aos humildes.

[[v20-3-35]]

^<<v20-3-35,35>>^ Os sábios herdarão honra, mas os loucos tomam sobre si a ignomínia.

'''

xref:020-proverbios/020-proverbios-002.adoc#v20-2-0[&#60; Capítulo Anterior] | <<v20-3-0,Topo>> | xref:020-proverbios/020-proverbios-004.adoc#v20-4-0[Próximo Capítulo &#62;]