include::./index.adoc[]

[[v20-7-0]]
=== Provérbios, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-7-1]]

^<<v20-7-1,1>>^ Filho meu, guarda as minhas palavras e conserva dentro de ti os meus mandamentos.

[[v20-7-2]]

^<<v20-7-2,2>>^ Guarda os meus mandamentos e vive; e a minha lei, como a menina dos teus olhos.

[[v20-7-3]]

^<<v20-7-3,3>>^ Ata-os aos dedos, escreve-os na tábua do teu coração.

[[v20-7-4]]

^<<v20-7-4,4>>^ Dize à Sabedoria: Tu és minha irmã; e ao Entendimento chama teu parente;

[[v20-7-5]]

^<<v20-7-5,5>>^ para te guardarem da mulher alheia, da estranha que lisonjeia com palavras.

[[v20-7-6]]

^<<v20-7-6,6>>^ Porque da janela da minha casa, por minhas grades, olhando eu,

[[v20-7-7]]

^<<v20-7-7,7>>^ vi entre os simples, descobri entre os jovens um que era carecente de juízo,

[[v20-7-8]]

^<<v20-7-8,8>>^ que ia e vinha pela rua junto à esquina da mulher estranha e seguia o caminho da sua casa,

[[v20-7-9]]

^<<v20-7-9,9>>^ à tarde do dia, no crepúsculo, na escuridão da noite, nas trevas.

[[v20-7-10]]

^<<v20-7-10,10>>^ Eis que a mulher lhe sai ao encontro, com vestes de prostituta e astuta de coração.

[[v20-7-11]]

^<<v20-7-11,11>>^ É apaixonada e inquieta, cujos pés não param em casa;

[[v20-7-12]]

^<<v20-7-12,12>>^ ora está nas ruas, ora, nas praças, espreitando por todos os cantos.

[[v20-7-13]]

^<<v20-7-13,13>>^ Aproximou-se dele, e o beijou, e de cara impudente lhe diz:

[[v20-7-14]]

^<<v20-7-14,14>>^ Sacrifícios pacíficos tinha eu de oferecer; paguei hoje os meus votos.

[[v20-7-15]]

^<<v20-7-15,15>>^ Por isso, saí ao teu encontro, a buscar-te, e te achei.

[[v20-7-16]]

^<<v20-7-16,16>>^ Já cobri de colchas a minha cama, de linho fino do Egito, de várias cores;

[[v20-7-17]]

^<<v20-7-17,17>>^ já perfumei o meu leito com mirra, aloés e cinamomo.

[[v20-7-18]]

^<<v20-7-18,18>>^ Vem, embriaguemo-nos com as delícias do amor, até pela manhã; gozemos amores.

[[v20-7-19]]

^<<v20-7-19,19>>^ Porque o meu marido não está em casa, saiu de viagem para longe.

[[v20-7-20]]

^<<v20-7-20,20>>^ Levou consigo um saquitel de dinheiro; só por volta da lua cheia ele tornará para casa.

[[v20-7-21]]

^<<v20-7-21,21>>^ Seduziu-o com as suas muitas palavras, com as lisonjas dos seus lábios o arrastou.

[[v20-7-22]]

^<<v20-7-22,22>>^ E ele num instante a segue, como o boi que vai ao matadouro; como o cervo que corre para a rede,

[[v20-7-23]]

^<<v20-7-23,23>>^ até que a flecha lhe atravesse o coração; como a ave que se apressa para o laço, sem saber que isto lhe custará a vida.

[[v20-7-24]]

^<<v20-7-24,24>>^ Agora, pois, filho, dá-me ouvidos e sê atento às palavras da minha boca;

[[v20-7-25]]

^<<v20-7-25,25>>^ não se desvie o teu coração para os caminhos dela, e não andes perdido nas suas veredas;

[[v20-7-26]]

^<<v20-7-26,26>>^ porque a muitos feriu e derribou; e são muitos os que por ela foram mortos.

[[v20-7-27]]

^<<v20-7-27,27>>^ A sua casa é caminho para a sepultura e desce para as câmaras da morte.

'''

xref:020-proverbios/020-proverbios-006.adoc#v20-6-0[&#60; Capítulo Anterior] | <<v20-7-0,Topo>> | xref:020-proverbios/020-proverbios-008.adoc#v20-8-0[Próximo Capítulo &#62;]