include::./index.adoc[]

[[v20-29-0]]
=== Provérbios, 29
// ara ?, ARA - Almeida Revista e Atualizada

[[v20-29-1]]

^<<v20-29-1,1>>^ O homem que muitas vezes repreendido endurece a cerviz será quebrantado de repente sem que haja cura.

[[v20-29-2]]

^<<v20-29-2,2>>^ Quando se multiplicam os justos, o povo se alegra, quando, porém, domina o perverso, o povo suspira.

[[v20-29-3]]

^<<v20-29-3,3>>^ O homem que ama a sabedoria alegra a seu pai, mas o companheiro de prostitutas desperdiça os bens.

[[v20-29-4]]

^<<v20-29-4,4>>^ O rei justo sustém a terra, mas o amigo de impostos a transtorna.

[[v20-29-5]]

^<<v20-29-5,5>>^ O homem que lisonjeia a seu próximo arma-lhe uma rede aos passos.

[[v20-29-6]]

^<<v20-29-6,6>>^ Na transgressão do homem mau, há laço, mas o justo canta e se regozija.

[[v20-29-7]]

^<<v20-29-7,7>>^ Informa-se o justo da causa dos pobres, mas o perverso de nada disso quer saber.

[[v20-29-8]]

^<<v20-29-8,8>>^ Os homens escarnecedores alvoroçam a cidade, mas os sábios desviam a ira.

[[v20-29-9]]

^<<v20-29-9,9>>^ Se o homem sábio discute com o insensato, quer este se encolerize, quer se ria, não haverá fim.

[[v20-29-10]]

^<<v20-29-10,10>>^ Os sanguinários aborrecem o íntegro, ao passo que, quanto aos retos, procuram tirar-lhes a vida.

[[v20-29-11]]

^<<v20-29-11,11>>^ O insensato expande toda a sua ira, mas o sábio afinal lha reprime.

[[v20-29-12]]

^<<v20-29-12,12>>^ Se o governador dá atenção a palavras mentirosas, virão a ser perversos todos os seus servos.

[[v20-29-13]]

^<<v20-29-13,13>>^ O pobre e o seu opressor se encontram, mas é o SENHOR quem dá luz aos olhos de ambos.

[[v20-29-14]]

^<<v20-29-14,14>>^ O rei que julga os pobres com equidade firmará o seu trono para sempre.

[[v20-29-15]]

^<<v20-29-15,15>>^ A vara e a disciplina dão sabedoria, mas a criança entregue a si mesma vem a envergonhar a sua mãe.

[[v20-29-16]]

^<<v20-29-16,16>>^ Quando os perversos se multiplicam, multiplicam-se as transgressões, mas os justos verão a ruína deles.

[[v20-29-17]]

^<<v20-29-17,17>>^ Corrige o teu filho, e te dará descanso, dará delícias à tua alma.

[[v20-29-18]]

^<<v20-29-18,18>>^ Não havendo profecia, o povo se corrompe; mas o que guarda a lei, esse é feliz.

[[v20-29-19]]

^<<v20-29-19,19>>^ O servo não se emendará com palavras, porque, ainda que entenda, não obedecerá.

[[v20-29-20]]

^<<v20-29-20,20>>^ Tens visto um homem precipitado nas suas palavras? Maior esperança há para o insensato do que para ele.

[[v20-29-21]]

^<<v20-29-21,21>>^ Se alguém amimar o escravo desde a infância, por fim ele quererá ser filho.

[[v20-29-22]]

^<<v20-29-22,22>>^ O iracundo levanta contendas, e o furioso multiplica as transgressões.

[[v20-29-23]]

^<<v20-29-23,23>>^ A soberba do homem o abaterá, mas o humilde de espírito obterá honra.

[[v20-29-24]]

^<<v20-29-24,24>>^ O que tem parte com o ladrão aborrece a própria alma; ouve as maldições e nada denuncia.

[[v20-29-25]]

^<<v20-29-25,25>>^ Quem teme ao homem arma ciladas, mas o que confia no SENHOR está seguro.

[[v20-29-26]]

^<<v20-29-26,26>>^ Muitos buscam o favor daquele que governa, mas para o homem a justiça vem do SENHOR.

[[v20-29-27]]

^<<v20-29-27,27>>^ Para o justo, o iníquo é abominação, e o reto no seu caminho é abominação ao perverso.

'''

xref:020-proverbios/020-proverbios-028.adoc#v20-28-0[&#60; Capítulo Anterior] | <<v20-29-0,Topo>> | xref:020-proverbios/020-proverbios-030.adoc#v20-30-0[Próximo Capítulo &#62;]