include::./index.adoc[]

[[v40-11-0]]
=== Mateus, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v40-11-1]]

^<<v40-11-1,1>>^ Ora, tendo acabado Jesus de dar estas instruções a seus doze discípulos, partiu dali a ensinar e a pregar nas cidades deles.

[[v40-11-2]]

^<<v40-11-2,2>>^ Quando João ouviu, no cárcere, falar das obras de Cristo, mandou por seus discípulos perguntar-lhe:

[[v40-11-3]]

^<<v40-11-3,3>>^ És tu aquele que estava para vir ou havemos de esperar outro?

[[v40-11-4]]

^<<v40-11-4,4>>^ E Jesus, respondendo, disse-lhes: Ide e anunciai a João o que estais ouvindo e vendo:

[[v40-11-5]]

^<<v40-11-5,5>>^ os cegos veem, os coxos andam, os leprosos são purificados, os surdos ouvem, os mortos são ressuscitados, e aos pobres está sendo pregado o evangelho.

[[v40-11-6]]

^<<v40-11-6,6>>^ E bem-aventurado é aquele que não achar em mim motivo de tropeço.

[[v40-11-7]]

^<<v40-11-7,7>>^ Então, em partindo eles, passou Jesus a dizer ao povo a respeito de João: Que saístes a ver no deserto? Um caniço agitado pelo vento?

[[v40-11-8]]

^<<v40-11-8,8>>^ Sim, que saístes a ver? Um homem vestido de roupas finas? Ora, os que vestem roupas finas assistem nos palácios reais.

[[v40-11-9]]

^<<v40-11-9,9>>^ Mas para que saístes? Para ver um profeta? Sim, eu vos digo, e muito mais que profeta.

[[v40-11-10]]

^<<v40-11-10,10>>^ Este é de quem está escrito: Eis aí eu envio diante da tua face o meu mensageiro, o qual preparará o teu caminho diante de ti.

[[v40-11-11]]

^<<v40-11-11,11>>^ Em verdade vos digo: entre os nascidos de mulher, ninguém apareceu maior do que João Batista; mas o menor no reino dos céus é maior do que ele.

[[v40-11-12]]

^<<v40-11-12,12>>^ Desde os dias de João Batista até agora, o reino dos céus é tomado por esforço, e os que se esforçam se apoderam dele.

[[v40-11-13]]

^<<v40-11-13,13>>^ Porque todos os Profetas e a Lei profetizaram até João.

[[v40-11-14]]

^<<v40-11-14,14>>^ E, se o quereis reconhecer, ele mesmo é Elias, que estava para vir.

[[v40-11-15]]

^<<v40-11-15,15>>^ Quem tem ouvidos [para ouvir], ouça.

[[v40-11-16]]

^<<v40-11-16,16>>^ Mas a quem hei de comparar esta geração? É semelhante a meninos que, sentados nas praças, gritam aos companheiros:

[[v40-11-17]]

^<<v40-11-17,17>>^ Nós vos tocamos flauta, e não dançastes; entoamos lamentações, e não pranteastes.

[[v40-11-18]]

^<<v40-11-18,18>>^ Pois veio João, que não comia nem bebia, e dizem: Tem demônio!

[[v40-11-19]]

^<<v40-11-19,19>>^ Veio o Filho do Homem, que come e bebe, e dizem: Eis aí um glutão e bebedor de vinho, amigo de publicanos e pecadores! Mas a sabedoria é justificada por suas obras.

[[v40-11-20]]

^<<v40-11-20,20>>^ Passou, então, Jesus a increpar as cidades nas quais ele operara numerosos milagres, pelo fato de não se terem arrependido:

[[v40-11-21]]

^<<v40-11-21,21>>^ Ai de ti, Corazim! Ai de ti, Betsaida! Porque, se em Tiro e em Sidom se tivessem operado os milagres que em vós se fizeram, há muito que elas se teriam arrependido com pano de saco e cinza.

[[v40-11-22]]

^<<v40-11-22,22>>^ E, contudo, vos digo: no Dia do Juízo, haverá menos rigor para Tiro e Sidom do que para vós outras.

[[v40-11-23]]

^<<v40-11-23,23>>^ Tu, Cafarnaum, elevar-te-ás, porventura, até ao céu? Descerás até ao inferno; porque, se em Sodoma se tivessem operado os milagres que em ti se fizeram, teria ela permanecido até ao dia de hoje.

[[v40-11-24]]

^<<v40-11-24,24>>^ Digo-vos, porém, que menos rigor haverá, no Dia do Juízo, para com a terra de Sodoma do que para contigo.

[[v40-11-25]]

^<<v40-11-25,25>>^ Por aquele tempo, exclamou Jesus: Graças te dou, ó Pai, Senhor do céu e da terra, porque ocultaste estas coisas aos sábios e instruídos e as revelaste aos pequeninos.

[[v40-11-26]]

^<<v40-11-26,26>>^ Sim, ó Pai, porque assim foi do teu agrado.

[[v40-11-27]]

^<<v40-11-27,27>>^ Tudo me foi entregue por meu Pai. Ninguém conhece o Filho, senão o Pai; e ninguém conhece o Pai, senão o Filho e aquele a quem o Filho o quiser revelar.

[[v40-11-28]]

^<<v40-11-28,28>>^ Vinde a mim, todos os que estais cansados e sobrecarregados, e eu vos aliviarei.

[[v40-11-29]]

^<<v40-11-29,29>>^ Tomai sobre vós o meu jugo e aprendei de mim, porque sou manso e humilde de coração; e achareis descanso para a vossa alma.

[[v40-11-30]]

^<<v40-11-30,30>>^ Porque o meu jugo é suave, e o meu fardo é leve.

'''

xref:040-mateus/040-mateus-010.adoc#v40-10-0[&#60; Capítulo Anterior] | <<v40-11-0,Topo>> | xref:040-mateus/040-mateus-012.adoc#v40-12-0[Próximo Capítulo &#62;]