include::./index.adoc[]

[[v40-5-0]]
=== Mateus, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v40-5-1]]

^<<v40-5-1,1>>^ Vendo Jesus as multidões, subiu ao monte, e, como se assentasse, aproximaram-se os seus discípulos;

[[v40-5-2]]

^<<v40-5-2,2>>^ e ele passou a ensiná-los, dizendo:

[[v40-5-3]]

^<<v40-5-3,3>>^ Bem-aventurados os humildes de espírito, porque deles é o reino dos céus.

[[v40-5-4]]

^<<v40-5-4,4>>^ Bem-aventurados os que choram, porque serão consolados.

[[v40-5-5]]

^<<v40-5-5,5>>^ Bem-aventurados os mansos, porque herdarão a terra.

[[v40-5-6]]

^<<v40-5-6,6>>^ Bem-aventurados os que têm fome e sede de justiça, porque serão fartos.

[[v40-5-7]]

^<<v40-5-7,7>>^ Bem-aventurados os misericordiosos, porque alcançarão misericórdia.

[[v40-5-8]]

^<<v40-5-8,8>>^ Bem-aventurados os limpos de coração, porque verão a Deus.

[[v40-5-9]]

^<<v40-5-9,9>>^ Bem-aventurados os pacificadores, porque serão chamados filhos de Deus.

[[v40-5-10]]

^<<v40-5-10,10>>^ Bem-aventurados os perseguidos por causa da justiça, porque deles é o reino dos céus.

[[v40-5-11]]

^<<v40-5-11,11>>^ Bem-aventurados sois quando, por minha causa, vos injuriarem, e vos perseguirem, e, mentindo, disserem todo mal contra vós.

[[v40-5-12]]

^<<v40-5-12,12>>^ Regozijai-vos e exultai, porque é grande o vosso galardão nos céus; pois assim perseguiram aos profetas que viveram antes de vós.

[[v40-5-13]]

^<<v40-5-13,13>>^ Vós sois o sal da terra; ora, se o sal vier a ser insípido, como lhe restaurar o sabor? Para nada mais presta senão para, lançado fora, ser pisado pelos homens.

[[v40-5-14]]

^<<v40-5-14,14>>^ Vós sois a luz do mundo. Não se pode esconder a cidade edificada sobre um monte;

[[v40-5-15]]

^<<v40-5-15,15>>^ nem se acende uma candeia para colocá-la debaixo do alqueire, mas no velador, e alumia a todos os que se encontram na casa.

[[v40-5-16]]

^<<v40-5-16,16>>^ Assim brilhe também a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem a vosso Pai que está nos céus.

[[v40-5-17]]

^<<v40-5-17,17>>^ Não penseis que vim revogar a Lei ou os Profetas; não vim para revogar, vim para cumprir.

[[v40-5-18]]

^<<v40-5-18,18>>^ Porque em verdade vos digo: até que o céu e a terra passem, nem um i ou um til jamais passará da Lei, até que tudo se cumpra.

[[v40-5-19]]

^<<v40-5-19,19>>^ Aquele, pois, que violar um destes mandamentos, posto que dos menores, e assim ensinar aos homens, será considerado mínimo no reino dos céus; aquele, porém, que os observar e ensinar, esse será considerado grande no reino dos céus.

[[v40-5-20]]

^<<v40-5-20,20>>^ Porque vos digo que, se a vossa justiça não exceder em muito a dos escribas e fariseus, jamais entrareis no reino dos céus.

[[v40-5-21]]

^<<v40-5-21,21>>^ Ouvistes que foi dito aos antigos: Não matarás; e: Quem matar estará sujeito a julgamento.

[[v40-5-22]]

^<<v40-5-22,22>>^ Eu, porém, vos digo que todo aquele que [sem motivo] se irar contra seu irmão estará sujeito a julgamento; e quem proferir um insulto a seu irmão estará sujeito a julgamento do tribunal; e quem lhe chamar: Tolo, estará sujeito ao inferno de fogo.

[[v40-5-23]]

^<<v40-5-23,23>>^ Se, pois, ao trazeres ao altar a tua oferta, ali te lembrares de que teu irmão tem alguma coisa contra ti,

[[v40-5-24]]

^<<v40-5-24,24>>^ deixa perante o altar a tua oferta, vai primeiro reconciliar-te com teu irmão; e, então, voltando, faze a tua oferta.

[[v40-5-25]]

^<<v40-5-25,25>>^ Entra em acordo sem demora com o teu adversário, enquanto estás com ele a caminho, para que o adversário não te entregue ao juiz, o juiz, ao oficial de justiça, e sejas recolhido à prisão.

[[v40-5-26]]

^<<v40-5-26,26>>^ Em verdade te digo que não sairás dali, enquanto não pagares o último centavo.

[[v40-5-27]]

^<<v40-5-27,27>>^ Ouvistes que foi dito: Não adulterarás.

[[v40-5-28]]

^<<v40-5-28,28>>^ Eu, porém, vos digo: qualquer que olhar para uma mulher com intenção impura, no coração, já adulterou com ela.

[[v40-5-29]]

^<<v40-5-29,29>>^ Se o teu olho direito te faz tropeçar, arranca-o e lança-o de ti; pois te convém que se perca um dos teus membros, e não seja todo o teu corpo lançado no inferno.

[[v40-5-30]]

^<<v40-5-30,30>>^ E, se a tua mão direita te faz tropeçar, corta-a e lança-a de ti; pois te convém que se perca um dos teus membros, e não vá todo o teu corpo para o inferno.

[[v40-5-31]]

^<<v40-5-31,31>>^ Também foi dito: Aquele que repudiar sua mulher, dê-lhe carta de divórcio.

[[v40-5-32]]

^<<v40-5-32,32>>^ Eu, porém, vos digo: qualquer que repudiar sua mulher, exceto em caso de relações sexuais ilícitas, a expõe a tornar-se adúltera; e aquele que casar com a repudiada comete adultério.

[[v40-5-33]]

^<<v40-5-33,33>>^ Também ouvistes que foi dito aos antigos: Não jurarás falso, mas cumprirás rigorosamente para com o Senhor os teus juramentos.

[[v40-5-34]]

^<<v40-5-34,34>>^ Eu, porém, vos digo: de modo algum jureis; nem pelo céu, por ser o trono de Deus;

[[v40-5-35]]

^<<v40-5-35,35>>^ nem pela terra, por ser estrado de seus pés; nem por Jerusalém, por ser cidade do grande Rei;

[[v40-5-36]]

^<<v40-5-36,36>>^ nem jures pela tua cabeça, porque não podes tornar um cabelo branco ou preto.

[[v40-5-37]]

^<<v40-5-37,37>>^ Seja, porém, a tua palavra: Sim, sim; não, não. O que disto passar vem do maligno.

[[v40-5-38]]

^<<v40-5-38,38>>^ Ouvistes que foi dito: Olho por olho, dente por dente.

[[v40-5-39]]

^<<v40-5-39,39>>^ Eu, porém, vos digo: não resistais ao perverso; mas, a qualquer que te ferir na face direita, volta-lhe também a outra;

[[v40-5-40]]

^<<v40-5-40,40>>^ e, ao que quer demandar contigo e tirar-te a túnica, deixa-lhe também a capa.

[[v40-5-41]]

^<<v40-5-41,41>>^ Se alguém te obrigar a andar uma milha, vai com ele duas.

[[v40-5-42]]

^<<v40-5-42,42>>^ Dá a quem te pede e não voltes as costas ao que deseja que lhe emprestes.

[[v40-5-43]]

^<<v40-5-43,43>>^ Ouvistes que foi dito: Amarás o teu próximo e odiarás o teu inimigo.

[[v40-5-44]]

^<<v40-5-44,44>>^ Eu, porém, vos digo: amai os vossos inimigos e orai pelos que vos perseguem;

[[v40-5-45]]

^<<v40-5-45,45>>^ para que vos torneis filhos do vosso Pai celeste, porque ele faz nascer o seu sol sobre maus e bons e vir chuvas sobre justos e injustos.

[[v40-5-46]]

^<<v40-5-46,46>>^ Porque, se amardes os que vos amam, que recompensa tendes? Não fazem os publicanos também o mesmo?

[[v40-5-47]]

^<<v40-5-47,47>>^ E, se saudardes somente os vossos irmãos, que fazeis de mais? Não fazem os gentios também o mesmo?

[[v40-5-48]]

^<<v40-5-48,48>>^ Portanto, sede vós perfeitos como perfeito é o vosso Pai celeste.

'''

xref:040-mateus/040-mateus-004.adoc#v40-4-0[&#60; Capítulo Anterior] | <<v40-5-0,Topo>> | xref:040-mateus/040-mateus-006.adoc#v40-6-0[Próximo Capítulo &#62;]