include::./index.adoc[]

[[v40-16-0]]
=== Mateus, 16
// ara ?, ARA - Almeida Revista e Atualizada

[[v40-16-1]]

^<<v40-16-1,1>>^ Aproximando-se os fariseus e os saduceus, tentando-o, pediram-lhe que lhes mostrasse um sinal vindo do céu.

[[v40-16-2]]

^<<v40-16-2,2>>^ Ele, porém, lhes respondeu: Chegada a tarde, dizeis: Haverá bom tempo, porque o céu está avermelhado;

[[v40-16-3]]

^<<v40-16-3,3>>^ e, pela manhã: Hoje, haverá tempestade, porque o céu está de um vermelho sombrio. Sabeis, na verdade, discernir o aspecto do céu e não podeis discernir os sinais dos tempos?

[[v40-16-4]]

^<<v40-16-4,4>>^ Uma geração má e adúltera pede um sinal; e nenhum sinal lhe será dado, senão o de Jonas.  E, deixando-os, retirou-se.

[[v40-16-5]]

^<<v40-16-5,5>>^ Ora, tendo os discípulos passado para o outro lado, esqueceram-se de levar pão.

[[v40-16-6]]

^<<v40-16-6,6>>^ E Jesus lhes disse: Vede e acautelai-vos do fermento dos fariseus e dos saduceus.

[[v40-16-7]]

^<<v40-16-7,7>>^ Eles, porém, discorriam entre si, dizendo: É porque não trouxemos pão.

[[v40-16-8]]

^<<v40-16-8,8>>^ Percebendo-o Jesus, disse: Por que discorreis entre vós, homens de pequena fé, sobre o não terdes pão?

[[v40-16-9]]

^<<v40-16-9,9>>^ Não compreendeis ainda, nem vos lembrais dos cinco pães para cinco mil homens e de quantos cestos tomastes?

[[v40-16-10]]

^<<v40-16-10,10>>^ Nem dos sete pães para os quatro mil e de quantos cestos tomastes?

[[v40-16-11]]

^<<v40-16-11,11>>^ Como não compreendeis que não vos falei a respeito de pães? E sim: acautelai-vos do fermento dos fariseus e dos saduceus.

[[v40-16-12]]

^<<v40-16-12,12>>^ Então, entenderam que não lhes dissera que se acautelassem do fermento de pães, mas da doutrina dos fariseus e dos saduceus.

[[v40-16-13]]

^<<v40-16-13,13>>^ Indo Jesus para os lados de Cesareia de Filipe, perguntou a seus discípulos: Quem diz o povo ser o Filho do Homem?

[[v40-16-14]]

^<<v40-16-14,14>>^ E eles responderam: Uns dizem: João Batista; outros: Elias; e outros: Jeremias ou algum dos profetas.

[[v40-16-15]]

^<<v40-16-15,15>>^ Mas vós,  continuou ele, quem dizeis que eu sou?

[[v40-16-16]]

^<<v40-16-16,16>>^ Respondendo Simão Pedro, disse: Tu és o Cristo, o Filho do Deus vivo.

[[v40-16-17]]

^<<v40-16-17,17>>^ Então, Jesus lhe afirmou: Bem-aventurado és, Simão Barjonas, porque não foi carne e sangue que to revelaram, mas meu Pai, que está nos céus.

[[v40-16-18]]

^<<v40-16-18,18>>^ Também eu te digo que tu és Pedro, e sobre esta pedra edificarei a minha igreja, e as portas do inferno não prevalecerão contra ela.

[[v40-16-19]]

^<<v40-16-19,19>>^ Dar-te-ei as chaves do reino dos céus; o que ligares na terra terá sido ligado nos céus; e o que desligares na terra terá sido desligado nos céus.

[[v40-16-20]]

^<<v40-16-20,20>>^ Então, advertiu os discípulos de que a ninguém dissessem ser ele o Cristo.

[[v40-16-21]]

^<<v40-16-21,21>>^ Desde esse tempo, começou Jesus Cristo a mostrar a seus discípulos que lhe era necessário seguir para Jerusalém e sofrer muitas coisas dos anciãos, dos principais sacerdotes e dos escribas, ser morto e ressuscitado no terceiro dia.

[[v40-16-22]]

^<<v40-16-22,22>>^ E Pedro, chamando-o à parte, começou a reprová-lo, dizendo: Tem compaixão de ti, Senhor; isso de modo algum te acontecerá.

[[v40-16-23]]

^<<v40-16-23,23>>^ Mas Jesus, voltando-se, disse a Pedro: Arreda, Satanás! Tu és para mim pedra de tropeço, porque não cogitas das coisas de Deus, e sim das dos homens.

[[v40-16-24]]

^<<v40-16-24,24>>^ Então, disse Jesus a seus discípulos: Se alguém quer vir após mim, a si mesmo se negue, tome a sua cruz e siga-me.

[[v40-16-25]]

^<<v40-16-25,25>>^ Porquanto, quem quiser salvar a sua vida perdê-la-á; e quem perder a vida por minha causa achá-la-á.

[[v40-16-26]]

^<<v40-16-26,26>>^ Pois que aproveitará o homem se ganhar o mundo inteiro e perder a sua alma? Ou que dará o homem em troca da sua alma?

[[v40-16-27]]

^<<v40-16-27,27>>^ Porque o Filho do Homem há de vir na glória de seu Pai, com os seus anjos, e, então, retribuirá a cada um conforme as suas obras.

[[v40-16-28]]

^<<v40-16-28,28>>^ Em verdade vos digo que alguns há, dos que aqui se encontram, que de maneira nenhuma passarão pela morte até que vejam vir o Filho do Homem no seu reino.

'''

xref:040-mateus/040-mateus-015.adoc#v40-15-0[&#60; Capítulo Anterior] | <<v40-16-0,Topo>> | xref:040-mateus/040-mateus-017.adoc#v40-17-0[Próximo Capítulo &#62;]