include::./index.adoc[]

[[v40-15-0]]
=== Mateus, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v40-15-1]]

^<<v40-15-1,1>>^ Então, vieram de Jerusalém a Jesus alguns fariseus e escribas e perguntaram:

[[v40-15-2]]

^<<v40-15-2,2>>^ Por que transgridem os teus discípulos a tradição dos anciãos? Pois não lavam as mãos, quando comem.

[[v40-15-3]]

^<<v40-15-3,3>>^ Ele, porém, lhes respondeu: Por que transgredis vós também o mandamento de Deus, por causa da vossa tradição?

[[v40-15-4]]

^<<v40-15-4,4>>^ Porque Deus ordenou: Honra a teu pai e a tua mãe; e: Quem maldisser a seu pai ou a sua mãe seja punido de morte.

[[v40-15-5]]

^<<v40-15-5,5>>^ Mas vós dizeis: Se alguém disser a seu pai ou a sua mãe: É oferta ao Senhor aquilo que poderias aproveitar de mim;

[[v40-15-6]]

^<<v40-15-6,6>>^ esse jamais honrará a seu pai ou a sua mãe. E, assim, invalidastes a palavra de Deus, por causa da vossa tradição.

[[v40-15-7]]

^<<v40-15-7,7>>^ Hipócritas! Bem profetizou Isaías a vosso respeito, dizendo:

[[v40-15-8]]

^<<v40-15-8,8>>^ Este povo honra-me com os lábios, mas o seu coração está longe de mim.

[[v40-15-9]]

^<<v40-15-9,9>>^ E em vão me adoram, ensinando doutrinas que são preceitos de homens.

[[v40-15-10]]

^<<v40-15-10,10>>^ E, tendo convocado a multidão, lhes disse: Ouvi e entendei:

[[v40-15-11]]

^<<v40-15-11,11>>^ não é o que entra pela boca o que contamina o homem, mas o que sai da boca, isto, sim, contamina o homem.

[[v40-15-12]]

^<<v40-15-12,12>>^ Então, aproximando-se dele os discípulos, disseram: Sabes que os fariseus, ouvindo a tua palavra, se escandalizaram?

[[v40-15-13]]

^<<v40-15-13,13>>^ Ele, porém, respondeu: Toda planta que meu Pai celestial não plantou será arrancada.

[[v40-15-14]]

^<<v40-15-14,14>>^ Deixai-os; são cegos, guias de cegos. Ora, se um cego guiar outro cego, cairão ambos no barranco.

[[v40-15-15]]

^<<v40-15-15,15>>^ Então, lhe disse Pedro: Explica-nos a parábola.

[[v40-15-16]]

^<<v40-15-16,16>>^ Jesus, porém, disse: Também vós não entendeis ainda?

[[v40-15-17]]

^<<v40-15-17,17>>^ Não compreendeis que tudo o que entra pela boca desce para o ventre e, depois, é lançado em lugar escuso?

[[v40-15-18]]

^<<v40-15-18,18>>^ Mas o que sai da boca vem do coração, e é isso que contamina o homem.

[[v40-15-19]]

^<<v40-15-19,19>>^ Porque do coração procedem maus desígnios, homicídios, adultérios, prostituição, furtos, falsos testemunhos, blasfêmias.

[[v40-15-20]]

^<<v40-15-20,20>>^ São estas as coisas que contaminam o homem; mas o comer sem lavar as mãos não o contamina.

[[v40-15-21]]

^<<v40-15-21,21>>^ Partindo Jesus dali, retirou-se para os lados de Tiro e Sidom.

[[v40-15-22]]

^<<v40-15-22,22>>^ E eis que uma mulher cananeia, que viera daquelas regiões, clamava: Senhor, Filho de Davi, tem compaixão de mim! Minha filha está horrivelmente endemoninhada.

[[v40-15-23]]

^<<v40-15-23,23>>^ Ele, porém, não lhe respondeu palavra. E os seus discípulos, aproximando-se, rogaram-lhe: Despede-a, pois vem clamando atrás de nós.

[[v40-15-24]]

^<<v40-15-24,24>>^ Mas Jesus respondeu: Não fui enviado senão às ovelhas perdidas da casa de Israel.

[[v40-15-25]]

^<<v40-15-25,25>>^ Ela, porém, veio e o adorou, dizendo: Senhor, socorre-me!

[[v40-15-26]]

^<<v40-15-26,26>>^ Então, ele, respondendo, disse: Não é bom tomar o pão dos filhos e lançá-lo aos cachorrinhos.

[[v40-15-27]]

^<<v40-15-27,27>>^ Ela, contudo, replicou: Sim, Senhor, porém os cachorrinhos comem das migalhas que caem da mesa dos seus donos.

[[v40-15-28]]

^<<v40-15-28,28>>^ Então, lhe disse Jesus: Ó mulher, grande é a tua fé! Faça-se contigo como queres.  E, desde aquele momento, sua filha ficou sã.

[[v40-15-29]]

^<<v40-15-29,29>>^ Partindo Jesus dali, foi para junto do mar da Galileia; e, subindo ao monte, assentou-se ali.

[[v40-15-30]]

^<<v40-15-30,30>>^ E vieram a ele muitas multidões trazendo consigo coxos, aleijados, cegos, mudos e outros muitos e os largaram junto aos pés de Jesus; e ele os curou.

[[v40-15-31]]

^<<v40-15-31,31>>^ De modo que o povo se maravilhou ao ver que os mudos falavam, os aleijados recobravam saúde, os coxos andavam e os cegos viam. Então, glorificavam ao Deus de Israel.

[[v40-15-32]]

^<<v40-15-32,32>>^ E, chamando Jesus os seus discípulos, disse: Tenho compaixão desta gente, porque há três dias que permanece comigo e não tem o que comer; e não quero despedi-la em jejum, para que não desfaleça pelo caminho.

[[v40-15-33]]

^<<v40-15-33,33>>^ Mas os discípulos lhe disseram: Onde haverá neste deserto tantos pães para fartar tão grande multidão?

[[v40-15-34]]

^<<v40-15-34,34>>^ Perguntou-lhes Jesus: Quantos pães tendes?  Responderam: Sete e alguns peixinhos.

[[v40-15-35]]

^<<v40-15-35,35>>^ Então, tendo mandado o povo assentar-se no chão,

[[v40-15-36]]

^<<v40-15-36,36>>^ tomou os sete pães e os peixes, e, dando graças, partiu, e deu aos discípulos, e estes, ao povo.

[[v40-15-37]]

^<<v40-15-37,37>>^ Todos comeram e se fartaram; e, do que sobejou, recolheram sete cestos cheios.

[[v40-15-38]]

^<<v40-15-38,38>>^ Ora, os que comeram eram quatro mil homens, além de mulheres e crianças.

[[v40-15-39]]

^<<v40-15-39,39>>^ E, tendo despedido as multidões, entrou Jesus no barco e foi para o território de Magadã.

'''

xref:040-mateus/040-mateus-014.adoc#v40-14-0[&#60; Capítulo Anterior] | <<v40-15-0,Topo>> | xref:040-mateus/040-mateus-016.adoc#v40-16-0[Próximo Capítulo &#62;]