include::./index.adoc[]

[[v40-12-0]]
=== Mateus, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v40-12-1]]

^<<v40-12-1,1>>^ Por aquele tempo, em dia de sábado, passou Jesus pelas searas. Ora, estando os seus discípulos com fome, entraram a colher espigas e a comer.

[[v40-12-2]]

^<<v40-12-2,2>>^ Os fariseus, porém, vendo isso, disseram-lhe: Eis que os teus discípulos fazem o que não é lícito fazer em dia de sábado.

[[v40-12-3]]

^<<v40-12-3,3>>^ Mas Jesus lhes disse: Não lestes o que fez Davi quando ele e seus companheiros tiveram fome?

[[v40-12-4]]

^<<v40-12-4,4>>^ Como entrou na Casa de Deus, e comeram os pães da proposição, os quais não lhes era lícito comer, nem a ele nem aos que com ele estavam, mas exclusivamente aos sacerdotes?

[[v40-12-5]]

^<<v40-12-5,5>>^ Ou não lestes na Lei que, aos sábados, os sacerdotes no templo violam o sábado e ficam sem culpa? Pois eu vos digo:

[[v40-12-6]]

^<<v40-12-6,6>>^ aqui está quem é maior que o templo.

[[v40-12-7]]

^<<v40-12-7,7>>^ Mas, se vós soubésseis o que significa: Misericórdia quero e não holocaustos, não teríeis condenado inocentes.

[[v40-12-8]]

^<<v40-12-8,8>>^ Porque o Filho do Homem é senhor do sábado.

[[v40-12-9]]

^<<v40-12-9,9>>^ Tendo Jesus partido dali, entrou na sinagoga deles.

[[v40-12-10]]

^<<v40-12-10,10>>^ Achava-se ali um homem que tinha uma das mãos ressequida; e eles, então, com o intuito de acusá-lo, perguntaram a Jesus: É lícito curar no sábado?

[[v40-12-11]]

^<<v40-12-11,11>>^ Ao que lhes respondeu: Qual dentre vós será o homem que, tendo uma ovelha, e, num sábado, esta cair numa cova, não fará todo o esforço, tirando-a dali?

[[v40-12-12]]

^<<v40-12-12,12>>^ Ora, quanto mais vale um homem que uma ovelha? Logo, é lícito, nos sábados, fazer o bem.

[[v40-12-13]]

^<<v40-12-13,13>>^ Então, disse ao homem: Estende a mão.  Estendeu-a, e ela ficou sã como a outra.

[[v40-12-14]]

^<<v40-12-14,14>>^ Retirando-se, porém, os fariseus, conspiravam contra ele, sobre como lhe tirariam a vida.

[[v40-12-15]]

^<<v40-12-15,15>>^ Mas Jesus, sabendo disto, afastou-se dali. Muitos o seguiram, e a todos ele curou,

[[v40-12-16]]

^<<v40-12-16,16>>^ advertindo-lhes, porém, que o não expusessem à publicidade,

[[v40-12-17]]

^<<v40-12-17,17>>^ para se cumprir o que foi dito por intermédio do profeta Isaías:

[[v40-12-18]]

^<<v40-12-18,18>>^ Eis aqui o meu servo, que escolhi, o meu amado, em quem a minha alma se compraz. Farei repousar sobre ele o meu Espírito, e ele anunciará juízo aos gentios.

[[v40-12-19]]

^<<v40-12-19,19>>^ Não contenderá, nem gritará, nem alguém ouvirá nas praças a sua voz.

[[v40-12-20]]

^<<v40-12-20,20>>^ Não esmagará a cana quebrada, nem apagará a torcida que fumega, até que faça vencedor o juízo.

[[v40-12-21]]

^<<v40-12-21,21>>^ E, no seu nome, esperarão os gentios.

[[v40-12-22]]

^<<v40-12-22,22>>^ Então, lhe trouxeram um endemoninhado, cego e mudo; e ele o curou, passando o mudo a falar e a ver.

[[v40-12-23]]

^<<v40-12-23,23>>^ E toda a multidão se admirava e dizia: É este, porventura, o Filho de Davi?

[[v40-12-24]]

^<<v40-12-24,24>>^ Mas os fariseus, ouvindo isto, murmuravam: Este não expele demônios senão pelo poder de Belzebu, maioral dos demônios.

[[v40-12-25]]

^<<v40-12-25,25>>^ Jesus, porém, conhecendo-lhes os pensamentos, disse: Todo reino dividido contra si mesmo ficará deserto, e toda cidade ou casa dividida contra si mesma não subsistirá.

[[v40-12-26]]

^<<v40-12-26,26>>^ Se Satanás expele a Satanás, dividido está contra si mesmo; como, pois, subsistirá o seu reino?

[[v40-12-27]]

^<<v40-12-27,27>>^ E, se eu expulso demônios por Belzebu, por quem os expulsam vossos filhos? Por isso, eles mesmos serão os vossos juízes.

[[v40-12-28]]

^<<v40-12-28,28>>^ Se, porém, eu expulso demônios pelo Espírito de Deus, certamente é chegado o reino de Deus sobre vós.

[[v40-12-29]]

^<<v40-12-29,29>>^ Ou como pode alguém entrar na casa do valente e roubar-lhe os bens sem primeiro amarrá-lo? E, então, lhe saqueará a casa.

[[v40-12-30]]

^<<v40-12-30,30>>^ Quem não é por mim é contra mim; e quem comigo não ajunta espalha.

[[v40-12-31]]

^<<v40-12-31,31>>^ Por isso, vos declaro: todo pecado e blasfêmia serão perdoados aos homens; mas a blasfêmia contra o Espírito não será perdoada.

[[v40-12-32]]

^<<v40-12-32,32>>^ Se alguém proferir alguma palavra contra o Filho do Homem, ser-lhe-á isso perdoado; mas, se alguém falar contra o Espírito Santo, não lhe será isso perdoado, nem neste mundo nem no porvir.

[[v40-12-33]]

^<<v40-12-33,33>>^ Ou fazei a árvore boa e o seu fruto bom ou a árvore má e o seu fruto mau; porque pelo fruto se conhece a árvore.

[[v40-12-34]]

^<<v40-12-34,34>>^ Raça de víboras, como podeis falar coisas boas, sendo maus? Porque a boca fala do que está cheio o coração.

[[v40-12-35]]

^<<v40-12-35,35>>^ O homem bom tira do tesouro bom coisas boas; mas o homem mau do mau tesouro tira coisas más.

[[v40-12-36]]

^<<v40-12-36,36>>^ Digo-vos que de toda palavra frívola que proferirem os homens, dela darão conta no Dia do Juízo;

[[v40-12-37]]

^<<v40-12-37,37>>^ porque, pelas tuas palavras, serás justificado e, pelas tuas palavras, serás condenado.

[[v40-12-38]]

^<<v40-12-38,38>>^ Então, alguns escribas e fariseus replicaram: Mestre, queremos ver de tua parte algum sinal.

[[v40-12-39]]

^<<v40-12-39,39>>^ Ele, porém, respondeu: Uma geração má e adúltera pede um sinal; mas nenhum sinal lhe será dado, senão o do profeta Jonas.

[[v40-12-40]]

^<<v40-12-40,40>>^ Porque assim como esteve Jonas três dias e três noites no ventre do grande peixe, assim o Filho do Homem estará três dias e três noites no coração da terra.

[[v40-12-41]]

^<<v40-12-41,41>>^ Ninivitas se levantarão, no Juízo, com esta geração e a condenarão; porque se arrependeram com a pregação de Jonas. E eis aqui está quem é maior do que Jonas.

[[v40-12-42]]

^<<v40-12-42,42>>^ A rainha do Sul se levantará, no Juízo, com esta geração e a condenará; porque veio dos confins da terra para ouvir a sabedoria de Salomão. E eis aqui está quem é maior do que Salomão.

[[v40-12-43]]

^<<v40-12-43,43>>^ Quando o espírito imundo sai do homem, anda por lugares áridos procurando repouso, porém não encontra.

[[v40-12-44]]

^<<v40-12-44,44>>^ Por isso, diz: Voltarei para minha casa donde saí. E, tendo voltado, a encontra vazia, varrida e ornamentada.

[[v40-12-45]]

^<<v40-12-45,45>>^ Então, vai e leva consigo outros sete espíritos, piores do que ele, e, entrando, habitam ali; e o último estado daquele homem torna-se pior do que o primeiro. Assim também acontecerá a esta geração perversa.

[[v40-12-46]]

^<<v40-12-46,46>>^ Falava ainda Jesus ao povo, e eis que sua mãe e seus irmãos estavam do lado de fora, procurando falar-lhe.

[[v40-12-47]]

^<<v40-12-47,47>>^ E alguém lhe disse: Tua mãe e teus irmãos estão lá fora e querem falar-te.

[[v40-12-48]]

^<<v40-12-48,48>>^ Porém ele respondeu ao que lhe trouxera o aviso: Quem é minha mãe e quem são meus irmãos?

[[v40-12-49]]

^<<v40-12-49,49>>^ E, estendendo a mão para os discípulos, disse: Eis minha mãe e meus irmãos.

[[v40-12-50]]

^<<v40-12-50,50>>^ Porque qualquer que fizer a vontade de meu Pai celeste, esse é meu irmão, irmã e mãe.

'''

xref:040-mateus/040-mateus-011.adoc#v40-11-0[&#60; Capítulo Anterior] | <<v40-12-0,Topo>> | xref:040-mateus/040-mateus-013.adoc#v40-13-0[Próximo Capítulo &#62;]