include::./index.adoc[]

[[v40-18-0]]
=== Mateus, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v40-18-1]]

^<<v40-18-1,1>>^ Naquela hora, aproximaram-se de Jesus os discípulos, perguntando: Quem é, porventura, o maior no reino dos céus?

[[v40-18-2]]

^<<v40-18-2,2>>^ E Jesus, chamando uma criança, colocou-a no meio deles.

[[v40-18-3]]

^<<v40-18-3,3>>^ E disse: Em verdade vos digo que, se não vos converterdes e não vos tornardes como crianças, de modo algum entrareis no reino dos céus.

[[v40-18-4]]

^<<v40-18-4,4>>^ Portanto, aquele que se humilhar como esta criança, esse é o maior no reino dos céus.

[[v40-18-5]]

^<<v40-18-5,5>>^ E quem receber uma criança, tal como esta, em meu nome, a mim me recebe.

[[v40-18-6]]

^<<v40-18-6,6>>^ Qualquer, porém, que fizer tropeçar a um destes pequeninos que creem em mim, melhor lhe fora que se lhe pendurasse ao pescoço uma grande pedra de moinho, e fosse afogado na profundeza do mar.

[[v40-18-7]]

^<<v40-18-7,7>>^ Ai do mundo, por causa dos escândalos; porque é inevitável que venham escândalos, mas ai do homem pelo qual vem o escândalo!

[[v40-18-8]]

^<<v40-18-8,8>>^ Portanto, se a tua mão ou o teu pé te faz tropeçar, corta-o e lança-o fora de ti; melhor é entrares na vida manco ou aleijado do que, tendo duas mãos ou dois pés, seres lançado no fogo eterno.

[[v40-18-9]]

^<<v40-18-9,9>>^ Se um dos teus olhos te faz tropeçar, arranca-o e lança-o fora de ti; melhor é entrares na vida com um só dos teus olhos do que, tendo dois, seres lançado no inferno de fogo.

[[v40-18-10]]

^<<v40-18-10,10>>^ Vede, não desprezeis a qualquer destes pequeninos; porque eu vos afirmo que os seus anjos nos céus veem incessantemente a face de meu Pai celeste.

[[v40-18-11]]

^<<v40-18-11,11>>^ [Porque o Filho do Homem veio salvar o que estava perdido.]

[[v40-18-12]]

^<<v40-18-12,12>>^ Que vos parece? Se um homem tiver cem ovelhas, e uma delas se extraviar, não deixará ele nos montes as noventa e nove, indo procurar a que se extraviou?

[[v40-18-13]]

^<<v40-18-13,13>>^ E, se porventura a encontra, em verdade vos digo que maior prazer sentirá por causa desta do que pelas noventa e nove que não se extraviaram.

[[v40-18-14]]

^<<v40-18-14,14>>^ Assim, pois, não é da vontade de vosso Pai celeste que pereça um só destes pequeninos.

[[v40-18-15]]

^<<v40-18-15,15>>^ Se teu irmão pecar [contra ti], vai argui-lo entre ti e ele só. Se ele te ouvir, ganhaste a teu irmão.

[[v40-18-16]]

^<<v40-18-16,16>>^ Se, porém, não te ouvir, toma ainda contigo uma ou duas pessoas, para que, pelo depoimento de duas ou três testemunhas, toda palavra se estabeleça.

[[v40-18-17]]

^<<v40-18-17,17>>^ E, se ele não os atender, dize-o à igreja; e, se recusar ouvir também a igreja, considera-o como gentio e publicano.

[[v40-18-18]]

^<<v40-18-18,18>>^ Em verdade vos digo que tudo o que ligardes na terra terá sido ligado nos céus, e tudo o que desligardes na terra terá sido desligado nos céus.

[[v40-18-19]]

^<<v40-18-19,19>>^ Em verdade também vos digo que, se dois dentre vós, sobre a terra, concordarem a respeito de qualquer coisa que, porventura, pedirem, ser-lhes-á concedida por meu Pai, que está nos céus.

[[v40-18-20]]

^<<v40-18-20,20>>^ Porque, onde estiverem dois ou três reunidos em meu nome, ali estou no meio deles.

[[v40-18-21]]

^<<v40-18-21,21>>^ Então, Pedro, aproximando-se, lhe perguntou: Senhor, até quantas vezes meu irmão pecará contra mim, que eu lhe perdoe? Até sete vezes?

[[v40-18-22]]

^<<v40-18-22,22>>^ Respondeu-lhe Jesus: Não te digo que até sete vezes, mas até setenta vezes sete.

[[v40-18-23]]

^<<v40-18-23,23>>^ Por isso, o reino dos céus é semelhante a um rei que resolveu ajustar contas com os seus servos.

[[v40-18-24]]

^<<v40-18-24,24>>^ E, passando a fazê-lo, trouxeram-lhe um que lhe devia dez mil talentos.

[[v40-18-25]]

^<<v40-18-25,25>>^ Não tendo ele, porém, com que pagar, ordenou o senhor que fosse vendido ele, a mulher, os filhos e tudo quanto possuía e que a dívida fosse paga.

[[v40-18-26]]

^<<v40-18-26,26>>^ Então, o servo, prostrando-se reverente, rogou: Sê paciente comigo, e tudo te pagarei.

[[v40-18-27]]

^<<v40-18-27,27>>^ E o senhor daquele servo, compadecendo-se, mandou-o embora e perdoou-lhe a dívida.

[[v40-18-28]]

^<<v40-18-28,28>>^ Saindo, porém, aquele servo, encontrou um dos seus conservos que lhe devia cem denários; e, agarrando-o, o sufocava, dizendo: Paga-me o que me deves.

[[v40-18-29]]

^<<v40-18-29,29>>^ Então, o seu conservo, caindo-lhe aos pés, lhe implorava: Sê paciente comigo, e te pagarei.

[[v40-18-30]]

^<<v40-18-30,30>>^ Ele, entretanto, não quis; antes, indo-se, o lançou na prisão, até que saldasse a dívida.

[[v40-18-31]]

^<<v40-18-31,31>>^ Vendo os seus companheiros o que se havia passado, entristeceram-se muito e foram relatar ao seu senhor tudo que acontecera.

[[v40-18-32]]

^<<v40-18-32,32>>^ Então, o seu senhor, chamando-o, lhe disse: Servo malvado, perdoei-te aquela dívida toda porque me suplicaste;

[[v40-18-33]]

^<<v40-18-33,33>>^ não devias tu, igualmente, compadecer-te do teu conservo, como também eu me compadeci de ti?

[[v40-18-34]]

^<<v40-18-34,34>>^ E, indignando-se, o seu senhor o entregou aos verdugos, até que lhe pagasse toda a dívida.

[[v40-18-35]]

^<<v40-18-35,35>>^ Assim também meu Pai celeste vos fará, se do íntimo não perdoardes cada um a seu irmão.

'''

xref:040-mateus/040-mateus-017.adoc#v40-17-0[&#60; Capítulo Anterior] | <<v40-18-0,Topo>> | xref:040-mateus/040-mateus-019.adoc#v40-19-0[Próximo Capítulo &#62;]