include::./index.adoc[]

[[v40-6-0]]
=== Mateus, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v40-6-1]]

^<<v40-6-1,1>>^ Guardai-vos de exercer a vossa justiça diante dos homens, com o fim de serdes vistos por eles; doutra sorte, não tereis galardão junto de vosso Pai celeste.

[[v40-6-2]]

^<<v40-6-2,2>>^ Quando, pois, deres esmola, não toques trombeta diante de ti, como fazem os hipócritas, nas sinagogas e nas ruas, para serem glorificados pelos homens. Em verdade vos digo que eles já receberam a recompensa.

[[v40-6-3]]

^<<v40-6-3,3>>^ Tu, porém, ao dares a esmola, ignore a tua mão esquerda o que faz a tua mão direita;

[[v40-6-4]]

^<<v40-6-4,4>>^ para que a tua esmola fique em secreto; e teu Pai, que vê em secreto, te recompensará.

[[v40-6-5]]

^<<v40-6-5,5>>^ E, quando orardes, não sereis como os hipócritas; porque gostam de orar em pé nas sinagogas e nos cantos das praças, para serem vistos dos homens. Em verdade vos digo que eles já receberam a recompensa.

[[v40-6-6]]

^<<v40-6-6,6>>^ Tu, porém, quando orares, entra no teu quarto e, fechada a porta, orarás a teu Pai, que está em secreto; e teu Pai, que vê em secreto, te recompensará.

[[v40-6-7]]

^<<v40-6-7,7>>^ E, orando, não useis de vãs repetições, como os gentios; porque presumem que pelo seu muito falar serão ouvidos.

[[v40-6-8]]

^<<v40-6-8,8>>^ Não vos assemelheis, pois, a eles; porque Deus, o vosso Pai, sabe o de que tendes necessidade, antes que lho peçais.

[[v40-6-9]]

^<<v40-6-9,9>>^ Portanto, vós orareis assim: Pai nosso, que estás nos céus, santificado seja o teu nome;

[[v40-6-10]]

^<<v40-6-10,10>>^ venha o teu reino; faça-se a tua vontade, assim na terra como no céu;

[[v40-6-11]]

^<<v40-6-11,11>>^ o pão nosso de cada dia dá-nos hoje;

[[v40-6-12]]

^<<v40-6-12,12>>^ e perdoa-nos as nossas dívidas, assim como nós temos perdoado aos nossos devedores;

[[v40-6-13]]

^<<v40-6-13,13>>^ e não nos deixes cair em tentação; mas livra-nos do mal [pois teu é o reino, o poder e a glória para sempre. Amém]!

[[v40-6-14]]

^<<v40-6-14,14>>^ Porque, se perdoardes aos homens as suas ofensas, também vosso Pai celeste vos perdoará;

[[v40-6-15]]

^<<v40-6-15,15>>^ se, porém, não perdoardes aos homens [as suas ofensas], tampouco vosso Pai vos perdoará as vossas ofensas.

[[v40-6-16]]

^<<v40-6-16,16>>^ Quando jejuardes, não vos mostreis contristados como os hipócritas; porque desfiguram o rosto com o fim de parecer aos homens que jejuam. Em verdade vos digo que eles já receberam a recompensa.

[[v40-6-17]]

^<<v40-6-17,17>>^ Tu, porém, quando jejuares, unge a cabeça e lava o rosto,

[[v40-6-18]]

^<<v40-6-18,18>>^ com o fim de não parecer aos homens que jejuas, e sim ao teu Pai, em secreto; e teu Pai, que vê em secreto, te recompensará.

[[v40-6-19]]

^<<v40-6-19,19>>^ Não acumuleis para vós outros tesouros sobre a terra, onde a traça e a ferrugem corroem e onde ladrões escavam e roubam;

[[v40-6-20]]

^<<v40-6-20,20>>^ mas ajuntai para vós outros tesouros no céu, onde traça nem ferrugem corrói, e onde ladrões não escavam, nem roubam;

[[v40-6-21]]

^<<v40-6-21,21>>^ porque, onde está o teu tesouro, aí estará também o teu coração.

[[v40-6-22]]

^<<v40-6-22,22>>^ São os olhos a lâmpada do corpo. Se os teus olhos forem bons, todo o teu corpo será luminoso;

[[v40-6-23]]

^<<v40-6-23,23>>^ se, porém, os teus olhos forem maus, todo o teu corpo estará em trevas. Portanto, caso a luz que em ti há sejam trevas, que grandes trevas serão!

[[v40-6-24]]

^<<v40-6-24,24>>^ Ninguém pode servir a dois senhores; porque ou há de aborrecer-se de um e amar ao outro, ou se devotará a um e desprezará ao outro. Não podeis servir a Deus e às riquezas.

[[v40-6-25]]

^<<v40-6-25,25>>^ Por isso, vos digo: não andeis ansiosos pela vossa vida, quanto ao que haveis de comer ou beber; nem pelo vosso corpo, quanto ao que haveis de vestir. Não é a vida mais do que o alimento, e o corpo, mais do que as vestes?

[[v40-6-26]]

^<<v40-6-26,26>>^ Observai as aves do céu: não semeiam, não colhem, nem ajuntam em celeiros; contudo, vosso Pai celeste as sustenta. Porventura, não valeis vós muito mais do que as aves?

[[v40-6-27]]

^<<v40-6-27,27>>^ Qual de vós, por ansioso que esteja, pode acrescentar um côvado ao curso da sua vida?

[[v40-6-28]]

^<<v40-6-28,28>>^ E por que andais ansiosos quanto ao vestuário? Considerai como crescem os lírios do campo: eles não trabalham, nem fiam.

[[v40-6-29]]

^<<v40-6-29,29>>^ Eu, contudo, vos afirmo que nem Salomão, em toda a sua glória, se vestiu como qualquer deles.

[[v40-6-30]]

^<<v40-6-30,30>>^ Ora, se Deus veste assim a erva do campo, que hoje existe e amanhã é lançada no forno, quanto mais a vós outros, homens de pequena fé?

[[v40-6-31]]

^<<v40-6-31,31>>^ Portanto, não vos inquieteis, dizendo: Que comeremos? Que beberemos? Ou: Com que nos vestiremos?

[[v40-6-32]]

^<<v40-6-32,32>>^ Porque os gentios é que procuram todas estas coisas; pois vosso Pai celeste sabe que necessitais de todas elas;

[[v40-6-33]]

^<<v40-6-33,33>>^ buscai, pois, em primeiro lugar, o seu reino e a sua justiça, e todas estas coisas vos serão acrescentadas.

[[v40-6-34]]

^<<v40-6-34,34>>^ Portanto, não vos inquieteis com o dia de amanhã, pois o amanhã trará os seus cuidados; basta ao dia o seu próprio mal.

'''

xref:040-mateus/040-mateus-005.adoc#v40-5-0[&#60; Capítulo Anterior] | <<v40-6-0,Topo>> | xref:040-mateus/040-mateus-007.adoc#v40-7-0[Próximo Capítulo &#62;]