include::./index.adoc[]

[[v40-2-0]]
=== Mateus, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v40-2-1]]

^<<v40-2-1,1>>^ Tendo Jesus nascido em Belém da Judeia, em dias do rei Herodes, eis que vieram uns magos do Oriente a Jerusalém.

[[v40-2-2]]

^<<v40-2-2,2>>^ E perguntavam: Onde está o recém-nascido Rei dos judeus? Porque vimos a sua estrela no Oriente e viemos para adorá-lo.

[[v40-2-3]]

^<<v40-2-3,3>>^ Tendo ouvido isso, alarmou-se o rei Herodes, e, com ele, toda a Jerusalém;

[[v40-2-4]]

^<<v40-2-4,4>>^ então, convocando todos os principais sacerdotes e escribas do povo, indagava deles onde o Cristo deveria nascer.

[[v40-2-5]]

^<<v40-2-5,5>>^ Em Belém da Judeia, responderam eles, porque assim está escrito por intermédio do profeta:

[[v40-2-6]]

^<<v40-2-6,6>>^ E tu, Belém, terra de Judá, não és de modo algum a menor entre as principais de Judá; porque de ti sairá o Guia que há de apascentar a meu povo, Israel.

[[v40-2-7]]

^<<v40-2-7,7>>^ Com isto, Herodes, tendo chamado secretamente os magos, inquiriu deles com precisão quanto ao tempo em que a estrela aparecera.

[[v40-2-8]]

^<<v40-2-8,8>>^ E, enviando-os a Belém, disse-lhes: Ide informar-vos cuidadosamente a respeito do menino; e, quando o tiverdes encontrado, avisai-me, para eu também ir adorá-lo.

[[v40-2-9]]

^<<v40-2-9,9>>^ Depois de ouvirem o rei, partiram; e eis que a estrela que viram no Oriente os precedia, até que, chegando, parou sobre onde estava o menino.

[[v40-2-10]]

^<<v40-2-10,10>>^ E, vendo eles a estrela, alegraram-se com grande e intenso júbilo.

[[v40-2-11]]

^<<v40-2-11,11>>^ Entrando na casa, viram o menino com Maria, sua mãe. Prostrando-se, o adoraram; e, abrindo os seus tesouros, entregaram-lhe suas ofertas: ouro, incenso e mirra.

[[v40-2-12]]

^<<v40-2-12,12>>^ Sendo por divina advertência prevenidos em sonho para não voltarem à presença de Herodes, regressaram por outro caminho a sua terra.

[[v40-2-13]]

^<<v40-2-13,13>>^ Tendo eles partido, eis que apareceu um anjo do Senhor a José, em sonho, e disse: Dispõe-te, toma o menino e sua mãe, foge para o Egito e permanece lá até que eu te avise; porque Herodes há de procurar o menino para o matar.

[[v40-2-14]]

^<<v40-2-14,14>>^ Dispondo-se ele, tomou de noite o menino e sua mãe e partiu para o Egito;

[[v40-2-15]]

^<<v40-2-15,15>>^ e lá ficou até à morte de Herodes, para que se cumprisse o que fora dito pelo Senhor, por intermédio do profeta: Do Egito chamei o meu Filho.

[[v40-2-16]]

^<<v40-2-16,16>>^ Vendo-se iludido pelos magos, enfureceu-se Herodes grandemente e mandou matar todos os meninos de Belém e de todos os seus arredores, de dois anos para baixo, conforme o tempo do qual com precisão se informara dos magos.

[[v40-2-17]]

^<<v40-2-17,17>>^ Então, se cumpriu o que fora dito por intermédio do profeta Jeremias:

[[v40-2-18]]

^<<v40-2-18,18>>^ Ouviu-se um clamor em Ramá, pranto, [choro] e grande lamento; era Raquel chorando por seus filhos e inconsolável porque não mais existem.

[[v40-2-19]]

^<<v40-2-19,19>>^ Tendo Herodes morrido, eis que um anjo do Senhor apareceu em sonho a José, no Egito, e disse-lhe:

[[v40-2-20]]

^<<v40-2-20,20>>^ Dispõe-te, toma o menino e sua mãe e vai para a terra de Israel; porque já morreram os que atentavam contra a vida do menino.

[[v40-2-21]]

^<<v40-2-21,21>>^ Dispôs-se ele, tomou o menino e sua mãe e regressou para a terra de Israel.

[[v40-2-22]]

^<<v40-2-22,22>>^ Tendo, porém, ouvido que Arquelau reinava na Judeia em lugar de seu pai Herodes, temeu ir para lá; e, por divina advertência prevenido em sonho, retirou-se para as regiões da Galileia.

[[v40-2-23]]

^<<v40-2-23,23>>^ E foi habitar numa cidade chamada Nazaré, para que se cumprisse o que fora dito por intermédio dos profetas: Ele será chamado Nazareno.

'''

xref:040-mateus/040-mateus-001.adoc#v40-1-0[&#60; Capítulo Anterior] | <<v40-2-0,Topo>> | xref:040-mateus/040-mateus-003.adoc#v40-3-0[Próximo Capítulo &#62;]