include::./index.adoc[]

[[v40-9-0]]
=== Mateus, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v40-9-1]]

^<<v40-9-1,1>>^ Entrando Jesus num barco, passou para o outro lado e foi para a sua própria cidade.

[[v40-9-2]]

^<<v40-9-2,2>>^ E eis que lhe trouxeram um paralítico deitado num leito. Vendo-lhes a fé, Jesus disse ao paralítico: Tem bom ânimo, filho; estão perdoados os teus pecados.

[[v40-9-3]]

^<<v40-9-3,3>>^ Mas alguns escribas diziam consigo: Este blasfema.

[[v40-9-4]]

^<<v40-9-4,4>>^ Jesus, porém, conhecendo-lhes os pensamentos, disse: Por que cogitais o mal no vosso coração?

[[v40-9-5]]

^<<v40-9-5,5>>^ Pois qual é mais fácil? Dizer: Estão perdoados os teus pecados, ou dizer: Levanta-te e anda?

[[v40-9-6]]

^<<v40-9-6,6>>^ Ora, para que saibais que o Filho do Homem tem sobre a terra autoridade para perdoar pecados  — disse, então, ao paralítico: Levanta-te, toma o teu leito e vai para tua casa.

[[v40-9-7]]

^<<v40-9-7,7>>^ E, levantando-se, partiu para sua casa.

[[v40-9-8]]

^<<v40-9-8,8>>^ Vendo isto, as multidões, possuídas de temor, glorificaram a Deus, que dera tal autoridade aos homens.

[[v40-9-9]]

^<<v40-9-9,9>>^ Partindo Jesus dali, viu um homem chamado Mateus sentado na coletoria e disse-lhe: Segue-me!  Ele se levantou e o seguiu.

[[v40-9-10]]

^<<v40-9-10,10>>^ E sucedeu que, estando ele em casa, à mesa, muitos publicanos e pecadores vieram e tomaram lugares com Jesus e seus discípulos.

[[v40-9-11]]

^<<v40-9-11,11>>^ Ora, vendo isto, os fariseus perguntavam aos discípulos: Por que come o vosso Mestre com os publicanos e pecadores?

[[v40-9-12]]

^<<v40-9-12,12>>^ Mas Jesus, ouvindo, disse: Os sãos não precisam de médico, e sim os doentes.

[[v40-9-13]]

^<<v40-9-13,13>>^ Ide, porém, e aprendei o que significa: Misericórdia quero e não holocaustos; pois não vim chamar justos, e sim pecadores [ao arrependimento].

[[v40-9-14]]

^<<v40-9-14,14>>^ Vieram, depois, os discípulos de João e lhe perguntaram: Por que jejuamos nós, e os fariseus [muitas vezes], e teus discípulos não jejuam?

[[v40-9-15]]

^<<v40-9-15,15>>^ Respondeu-lhes Jesus: Podem, acaso, estar tristes os convidados para o casamento, enquanto o noivo está com eles? Dias virão, contudo, em que lhes será tirado o noivo, e nesses dias hão de jejuar.

[[v40-9-16]]

^<<v40-9-16,16>>^ Ninguém põe remendo de pano novo em veste velha; porque o remendo tira parte da veste, e fica maior a rotura.

[[v40-9-17]]

^<<v40-9-17,17>>^ Nem se põe vinho novo em odres velhos; do contrário, rompem-se os odres, derrama-se o vinho, e os odres se perdem. Mas põe-se vinho novo em odres novos, e ambos se conservam.

[[v40-9-18]]

^<<v40-9-18,18>>^ Enquanto estas coisas lhes dizia, eis que um chefe, aproximando-se, o adorou e disse: Minha filha faleceu agora mesmo; mas vem, impõe a mão sobre ela, e viverá.

[[v40-9-19]]

^<<v40-9-19,19>>^ E Jesus, levantando-se, o seguia, e também os seus discípulos.

[[v40-9-20]]

^<<v40-9-20,20>>^ E eis que uma mulher, que durante doze anos vinha padecendo de uma hemorragia, veio por trás dele e lhe tocou na orla da veste;

[[v40-9-21]]

^<<v40-9-21,21>>^ porque dizia consigo mesma: Se eu apenas lhe tocar a veste, ficarei curada.

[[v40-9-22]]

^<<v40-9-22,22>>^ E Jesus, voltando-se e vendo-a, disse: Tem bom ânimo, filha, a tua fé te salvou.  E, desde aquele instante, a mulher ficou sã.

[[v40-9-23]]

^<<v40-9-23,23>>^ Tendo Jesus chegado à casa do chefe e vendo os tocadores de flauta e o povo em alvoroço, disse:

[[v40-9-24]]

^<<v40-9-24,24>>^ Retirai-vos, porque não está morta a menina, mas dorme.  E riam-se dele.

[[v40-9-25]]

^<<v40-9-25,25>>^ Mas, afastado o povo, entrou Jesus, tomou a menina pela mão, e ela se levantou.

[[v40-9-26]]

^<<v40-9-26,26>>^ E a fama deste acontecimento correu por toda aquela terra.

[[v40-9-27]]

^<<v40-9-27,27>>^ Partindo Jesus dali, seguiram-no dois cegos, clamando: Tem compaixão de nós, Filho de Davi!

[[v40-9-28]]

^<<v40-9-28,28>>^ Tendo ele entrado em casa, aproximaram-se os cegos, e Jesus lhes perguntou: Credes que eu posso fazer isso?  Responderam-lhe: Sim, Senhor!

[[v40-9-29]]

^<<v40-9-29,29>>^ Então, lhes tocou os olhos, dizendo: Faça-se-vos conforme a vossa fé.

[[v40-9-30]]

^<<v40-9-30,30>>^ E abriram-se-lhes os olhos. Jesus, porém, os advertiu severamente, dizendo: Acautelai-vos de que ninguém o saiba.

[[v40-9-31]]

^<<v40-9-31,31>>^ Saindo eles, porém, divulgaram-lhe a fama por toda aquela terra.

[[v40-9-32]]

^<<v40-9-32,32>>^ Ao retirarem-se eles, foi-lhe trazido um mudo endemoninhado.

[[v40-9-33]]

^<<v40-9-33,33>>^ E, expelido o demônio, falou o mudo; e as multidões se admiravam, dizendo: Jamais se viu tal coisa em Israel!

[[v40-9-34]]

^<<v40-9-34,34>>^ Mas os fariseus murmuravam: Pelo maioral dos demônios é que expele os demônios.

[[v40-9-35]]

^<<v40-9-35,35>>^ E percorria Jesus todas as cidades e povoados, ensinando nas sinagogas, pregando o evangelho do reino e curando toda sorte de doenças e enfermidades.

[[v40-9-36]]

^<<v40-9-36,36>>^ Vendo ele as multidões, compadeceu-se delas, porque estavam aflitas e exaustas como ovelhas que não têm pastor.

[[v40-9-37]]

^<<v40-9-37,37>>^ E, então, se dirigiu a seus discípulos: A seara, na verdade, é grande, mas os trabalhadores são poucos.

[[v40-9-38]]

^<<v40-9-38,38>>^ Rogai, pois, ao Senhor da seara que mande trabalhadores para a sua seara.

'''

xref:040-mateus/040-mateus-008.adoc#v40-8-0[&#60; Capítulo Anterior] | <<v40-9-0,Topo>> | xref:040-mateus/040-mateus-010.adoc#v40-10-0[Próximo Capítulo &#62;]