include::./index.adoc[]

[[v40-10-0]]
=== Mateus, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v40-10-1]]

^<<v40-10-1,1>>^ Tendo chamado os seus doze discípulos, deu-lhes Jesus autoridade sobre espíritos imundos para os expelir e para curar toda sorte de doenças e enfermidades.

[[v40-10-2]]

^<<v40-10-2,2>>^ Ora, os nomes dos doze apóstolos são estes: primeiro, Simão, por sobrenome Pedro, e André, seu irmão; Tiago, filho de Zebedeu, e João, seu irmão;

[[v40-10-3]]

^<<v40-10-3,3>>^ Filipe e Bartolomeu; Tomé e Mateus, o publicano; Tiago, filho de Alfeu, e Tadeu;

[[v40-10-4]]

^<<v40-10-4,4>>^ Simão, o Zelote, e Judas Iscariotes, que foi quem o traiu.

[[v40-10-5]]

^<<v40-10-5,5>>^ A estes doze enviou Jesus, dando-lhes as seguintes instruções: Não tomeis rumo aos gentios, nem entreis em cidade de samaritanos;

[[v40-10-6]]

^<<v40-10-6,6>>^ mas, de preferência, procurai as ovelhas perdidas da casa de Israel;

[[v40-10-7]]

^<<v40-10-7,7>>^ e, à medida que seguirdes, pregai que está próximo o reino dos céus.

[[v40-10-8]]

^<<v40-10-8,8>>^ Curai enfermos, ressuscitai mortos, purificai leprosos, expeli demônios; de graça recebestes, de graça dai.

[[v40-10-9]]

^<<v40-10-9,9>>^ Não vos provereis de ouro, nem de prata, nem de cobre nos vossos cintos;

[[v40-10-10]]

^<<v40-10-10,10>>^ nem de alforje para o caminho, nem de duas túnicas, nem de sandálias, nem de bordão; porque digno é o trabalhador do seu alimento.

[[v40-10-11]]

^<<v40-10-11,11>>^ E, em qualquer cidade ou povoado em que entrardes, indagai quem neles é digno; e aí ficai até vos retirardes.

[[v40-10-12]]

^<<v40-10-12,12>>^ Ao entrardes na casa, saudai-a;

[[v40-10-13]]

^<<v40-10-13,13>>^ se, com efeito, a casa for digna, venha sobre ela a vossa paz; se, porém, não o for, torne para vós outros a vossa paz.

[[v40-10-14]]

^<<v40-10-14,14>>^ Se alguém não vos receber, nem ouvir as vossas palavras, ao sairdes daquela casa ou daquela cidade, sacudi o pó dos vossos pés.

[[v40-10-15]]

^<<v40-10-15,15>>^ Em verdade vos digo que menos rigor haverá para Sodoma e Gomorra, no Dia do Juízo, do que para aquela cidade.

[[v40-10-16]]

^<<v40-10-16,16>>^ Eis que eu vos envio como ovelhas para o meio de lobos; sede, portanto, prudentes como as serpentes e símplices como as pombas.

[[v40-10-17]]

^<<v40-10-17,17>>^ E acautelai-vos dos homens; porque vos entregarão aos tribunais e vos açoitarão nas suas sinagogas;

[[v40-10-18]]

^<<v40-10-18,18>>^ por minha causa sereis levados à presença de governadores e de reis, para lhes servir de testemunho, a eles e aos gentios.

[[v40-10-19]]

^<<v40-10-19,19>>^ E, quando vos entregarem, não cuideis em como ou o que haveis de falar, porque, naquela hora, vos será concedido o que haveis de dizer,

[[v40-10-20]]

^<<v40-10-20,20>>^ visto que não sois vós os que falais, mas o Espírito de vosso Pai é quem fala em vós.

[[v40-10-21]]

^<<v40-10-21,21>>^ Um irmão entregará à morte outro irmão, e o pai, ao filho; filhos haverá que se levantarão contra os progenitores e os matarão.

[[v40-10-22]]

^<<v40-10-22,22>>^ Sereis odiados de todos por causa do meu nome; aquele, porém, que perseverar até ao fim, esse será salvo.

[[v40-10-23]]

^<<v40-10-23,23>>^ Quando, porém, vos perseguirem numa cidade, fugi para outra; porque em verdade vos digo que não acabareis de percorrer as cidades de Israel, até que venha o Filho do Homem.

[[v40-10-24]]

^<<v40-10-24,24>>^ O discípulo não está acima do seu mestre, nem o servo, acima do seu senhor.

[[v40-10-25]]

^<<v40-10-25,25>>^ Basta ao discípulo ser como o seu mestre, e ao servo, como o seu senhor. Se chamaram Belzebu ao dono da casa, quanto mais aos seus domésticos?

[[v40-10-26]]

^<<v40-10-26,26>>^ Portanto, não os temais; pois nada há encoberto, que não venha a ser revelado; nem oculto, que não venha a ser conhecido.

[[v40-10-27]]

^<<v40-10-27,27>>^ O que vos digo às escuras, dizei-o a plena luz; e o que se vos diz ao ouvido, proclamai-o dos eirados.

[[v40-10-28]]

^<<v40-10-28,28>>^ Não temais os que matam o corpo e não podem matar a alma; temei, antes, aquele que pode fazer perecer no inferno tanto a alma como o corpo.

[[v40-10-29]]

^<<v40-10-29,29>>^ Não se vendem dois pardais por um asse? E nenhum deles cairá em terra sem o consentimento de vosso Pai.

[[v40-10-30]]

^<<v40-10-30,30>>^ E, quanto a vós outros, até os cabelos todos da cabeça estão contados.

[[v40-10-31]]

^<<v40-10-31,31>>^ Não temais, pois! Bem mais valeis vós do que muitos pardais.

[[v40-10-32]]

^<<v40-10-32,32>>^ Portanto, todo aquele que me confessar diante dos homens, também eu o confessarei diante de meu Pai, que está nos céus;

[[v40-10-33]]

^<<v40-10-33,33>>^ mas aquele que me negar diante dos homens, também eu o negarei diante de meu Pai, que está nos céus.

[[v40-10-34]]

^<<v40-10-34,34>>^ Não penseis que vim trazer paz à terra; não vim trazer paz, mas espada.

[[v40-10-35]]

^<<v40-10-35,35>>^ Pois vim causar divisão entre o homem e seu pai; entre a filha e sua mãe e entre a nora e sua sogra.

[[v40-10-36]]

^<<v40-10-36,36>>^ Assim, os inimigos do homem serão os da sua própria casa.

[[v40-10-37]]

^<<v40-10-37,37>>^ Quem ama seu pai ou sua mãe mais do que a mim não é digno de mim; quem ama seu filho ou sua filha mais do que a mim não é digno de mim;

[[v40-10-38]]

^<<v40-10-38,38>>^ e quem não toma a sua cruz e vem após mim não é digno de mim.

[[v40-10-39]]

^<<v40-10-39,39>>^ Quem acha a sua vida perdê-la-á; quem, todavia, perde a vida por minha causa achá-la-á.

[[v40-10-40]]

^<<v40-10-40,40>>^ Quem vos recebe a mim me recebe; e quem me recebe recebe aquele que me enviou.

[[v40-10-41]]

^<<v40-10-41,41>>^ Quem recebe um profeta, no caráter de profeta, receberá o galardão de profeta; quem recebe um justo, no caráter de justo, receberá o galardão de justo.

[[v40-10-42]]

^<<v40-10-42,42>>^ E quem der a beber, ainda que seja um copo de água fria, a um destes pequeninos, por ser este meu discípulo, em verdade vos digo que de modo algum perderá o seu galardão.

'''

xref:040-mateus/040-mateus-009.adoc#v40-9-0[&#60; Capítulo Anterior] | <<v40-10-0,Topo>> | xref:040-mateus/040-mateus-011.adoc#v40-11-0[Próximo Capítulo &#62;]