include::./index.adoc[]

[[v40-27-0]]
=== Mateus, 27
// ara ?, ARA - Almeida Revista e Atualizada

[[v40-27-1]]

^<<v40-27-1,1>>^ Ao romper o dia, todos os principais sacerdotes e os anciãos do povo entraram em conselho contra Jesus, para o matarem;

[[v40-27-2]]

^<<v40-27-2,2>>^ e, amarrando-o, levaram-no e o entregaram ao governador Pilatos.

[[v40-27-3]]

^<<v40-27-3,3>>^ Então, Judas, o que o traiu, vendo que Jesus fora condenado, tocado de remorso, devolveu as trinta moedas de prata aos principais sacerdotes e aos anciãos, dizendo:

[[v40-27-4]]

^<<v40-27-4,4>>^ Pequei, traindo sangue inocente. Eles, porém, responderam: Que nos importa? Isso é contigo.

[[v40-27-5]]

^<<v40-27-5,5>>^ Então, Judas, atirando para o santuário as moedas de prata, retirou-se e foi enforcar-se.

[[v40-27-6]]

^<<v40-27-6,6>>^ E os principais sacerdotes, tomando as moedas, disseram: Não é lícito deitá-las no cofre das ofertas, porque é preço de sangue.

[[v40-27-7]]

^<<v40-27-7,7>>^ E, tendo deliberado, compraram com elas o campo do oleiro, para cemitério de forasteiros.

[[v40-27-8]]

^<<v40-27-8,8>>^ Por isso, aquele campo tem sido chamado, até ao dia de hoje, Campo de Sangue.

[[v40-27-9]]

^<<v40-27-9,9>>^ Então, se cumpriu o que foi dito por intermédio do profeta Jeremias: Tomaram as trinta moedas de prata, preço em que foi estimado aquele a quem alguns dos filhos de Israel avaliaram;

[[v40-27-10]]

^<<v40-27-10,10>>^ e as deram pelo campo do oleiro, assim como me ordenou o Senhor.

[[v40-27-11]]

^<<v40-27-11,11>>^ Jesus estava em pé ante o governador; e este o interrogou, dizendo: És tu o rei dos judeus? Respondeu-lhe Jesus: Tu o dizes.

[[v40-27-12]]

^<<v40-27-12,12>>^ E, sendo acusado pelos principais sacerdotes e pelos anciãos, nada respondeu.

[[v40-27-13]]

^<<v40-27-13,13>>^ Então, lhe perguntou Pilatos: Não ouves quantas acusações te fazem?

[[v40-27-14]]

^<<v40-27-14,14>>^ Jesus não respondeu nem uma palavra, vindo com isto a admirar-se grandemente o governador.

[[v40-27-15]]

^<<v40-27-15,15>>^ Ora, por ocasião da festa, costumava o governador soltar ao povo um dos presos, conforme eles quisessem.

[[v40-27-16]]

^<<v40-27-16,16>>^ Naquela ocasião, tinham eles um preso muito conhecido, chamado Barrabás.

[[v40-27-17]]

^<<v40-27-17,17>>^ Estando, pois, o povo reunido, perguntou-lhes Pilatos: A quem quereis que eu vos solte, a Barrabás ou a Jesus, chamado Cristo?

[[v40-27-18]]

^<<v40-27-18,18>>^ Porque sabia que, por inveja, o tinham entregado.

[[v40-27-19]]

^<<v40-27-19,19>>^ E, estando ele no tribunal, sua mulher mandou dizer-lhe: Não te envolvas com esse justo; porque hoje, em sonho, muito sofri por seu respeito.

[[v40-27-20]]

^<<v40-27-20,20>>^ Mas os principais sacerdotes e os anciãos persuadiram o povo a que pedisse Barrabás e fizesse morrer Jesus.

[[v40-27-21]]

^<<v40-27-21,21>>^ De novo, perguntou-lhes o governador: Qual dos dois quereis que eu vos solte? Responderam eles: Barrabás!

[[v40-27-22]]

^<<v40-27-22,22>>^ Replicou-lhes Pilatos: Que farei, então, de Jesus, chamado Cristo? Seja crucificado! Responderam todos.

[[v40-27-23]]

^<<v40-27-23,23>>^ Que mal fez ele? Perguntou Pilatos. Porém cada vez clamavam mais: Seja crucificado!

[[v40-27-24]]

^<<v40-27-24,24>>^ Vendo Pilatos que nada conseguia, antes, pelo contrário, aumentava o tumulto, mandando vir água, lavou as mãos perante o povo, dizendo: Estou inocente do sangue deste [justo]; fique o caso convosco!

[[v40-27-25]]

^<<v40-27-25,25>>^ E o povo todo respondeu: Caia sobre nós o seu sangue e sobre nossos filhos!

[[v40-27-26]]

^<<v40-27-26,26>>^ Então, Pilatos lhes soltou Barrabás; e, após haver açoitado a Jesus, entregou-o para ser crucificado.

[[v40-27-27]]

^<<v40-27-27,27>>^ Logo a seguir, os soldados do governador, levando Jesus para o pretório, reuniram em torno dele toda a coorte.

[[v40-27-28]]

^<<v40-27-28,28>>^ Despojando-o das vestes, cobriram-no com um manto escarlate;

[[v40-27-29]]

^<<v40-27-29,29>>^ tecendo uma coroa de espinhos, puseram-lha na cabeça e, na mão direita, um caniço; e, ajoelhando-se diante dele, o escarneciam, dizendo: Salve, rei dos judeus!

[[v40-27-30]]

^<<v40-27-30,30>>^ E, cuspindo nele, tomaram o caniço e davam-lhe com ele na cabeça.

[[v40-27-31]]

^<<v40-27-31,31>>^ Depois de o terem escarnecido, despiram-lhe o manto e o vestiram com as suas próprias vestes. Em seguida, o levaram para ser crucificado.

[[v40-27-32]]

^<<v40-27-32,32>>^ Ao saírem, encontraram um cireneu, chamado Simão, a quem obrigaram a carregar-lhe a cruz.

[[v40-27-33]]

^<<v40-27-33,33>>^ E, chegando a um lugar chamado Gólgota, que significa Lugar da Caveira,

[[v40-27-34]]

^<<v40-27-34,34>>^ deram-lhe a beber vinho com fel; mas ele, provando-o, não o quis beber.

[[v40-27-35]]

^<<v40-27-35,35>>^ Depois de o crucificarem, repartiram entre si as suas vestes, tirando a sorte.

[[v40-27-36]]

^<<v40-27-36,36>>^ E, assentados ali, o guardavam.

[[v40-27-37]]

^<<v40-27-37,37>>^ Por cima da sua cabeça puseram escrita a sua acusação: Este é Jesus, o Rei dos Judeus .

[[v40-27-38]]

^<<v40-27-38,38>>^ E foram crucificados com ele dois ladrões, um à sua direita, e outro à sua esquerda.

[[v40-27-39]]

^<<v40-27-39,39>>^ Os que iam passando blasfemavam dele, meneando a cabeça e dizendo:

[[v40-27-40]]

^<<v40-27-40,40>>^ Ó tu que destróis o santuário e em três dias o reedificas! Salva-te a ti mesmo, se és Filho de Deus, e desce da cruz!

[[v40-27-41]]

^<<v40-27-41,41>>^ De igual modo, os principais sacerdotes, com os escribas e anciãos, escarnecendo, diziam:

[[v40-27-42]]

^<<v40-27-42,42>>^ Salvou os outros, a si mesmo não pode salvar-se. É rei de Israel! Desça da cruz, e creremos nele.

[[v40-27-43]]

^<<v40-27-43,43>>^ Confiou em Deus; pois venha livrá-lo agora, se, de fato, lhe quer bem; porque disse: Sou Filho de Deus.

[[v40-27-44]]

^<<v40-27-44,44>>^ E os mesmos impropérios lhe diziam também os ladrões que haviam sido crucificados com ele.

[[v40-27-45]]

^<<v40-27-45,45>>^ Desde a hora sexta até à hora nona, houve trevas sobre toda a terra.

[[v40-27-46]]

^<<v40-27-46,46>>^ Por volta da hora nona, clamou Jesus em alta voz, dizendo: Eli, Eli, lamá sabactâni?  O que quer dizer: Deus meu, Deus meu, por que me desamparaste?

[[v40-27-47]]

^<<v40-27-47,47>>^ E alguns dos que ali estavam, ouvindo isto, diziam: Ele chama por Elias.

[[v40-27-48]]

^<<v40-27-48,48>>^ E, logo, um deles correu a buscar uma esponja e, tendo-a embebido de vinagre e colocado na ponta de um caniço, deu-lhe a beber.

[[v40-27-49]]

^<<v40-27-49,49>>^ Os outros, porém, diziam: Deixa, vejamos se Elias vem salvá-lo.

[[v40-27-50]]

^<<v40-27-50,50>>^ E Jesus, clamando outra vez com grande voz, entregou o espírito.

[[v40-27-51]]

^<<v40-27-51,51>>^ Eis que o véu do santuário se rasgou em duas partes de alto a baixo; tremeu a terra, fenderam-se as rochas;

[[v40-27-52]]

^<<v40-27-52,52>>^ abriram-se os sepulcros, e muitos corpos de santos, que dormiam, ressuscitaram;

[[v40-27-53]]

^<<v40-27-53,53>>^ e, saindo dos sepulcros depois da ressurreição de Jesus, entraram na cidade santa e apareceram a muitos.

[[v40-27-54]]

^<<v40-27-54,54>>^ O centurião e os que com ele guardavam a Jesus, vendo o terremoto e tudo o que se passava, ficaram possuídos de grande temor e disseram: Verdadeiramente este era Filho de Deus.

[[v40-27-55]]

^<<v40-27-55,55>>^ Estavam ali muitas mulheres, observando de longe; eram as que vinham seguindo a Jesus desde a Galileia, para o servirem;

[[v40-27-56]]

^<<v40-27-56,56>>^ entre elas estavam Maria Madalena, Maria, mãe de Tiago e de José, e a mulher de Zebedeu.

[[v40-27-57]]

^<<v40-27-57,57>>^ Caindo a tarde, veio um homem rico de Arimateia, chamado José, que era também discípulo de Jesus.

[[v40-27-58]]

^<<v40-27-58,58>>^ Este foi ter com Pilatos e lhe pediu o corpo de Jesus. Então, Pilatos mandou que lho fosse entregue.

[[v40-27-59]]

^<<v40-27-59,59>>^ E José, tomando o corpo, envolveu-o num pano limpo de linho

[[v40-27-60]]

^<<v40-27-60,60>>^ e o depositou no seu túmulo novo, que fizera abrir na rocha; e, rolando uma grande pedra para a entrada do sepulcro, se retirou.

[[v40-27-61]]

^<<v40-27-61,61>>^ Achavam-se ali, sentadas em frente da sepultura, Maria Madalena e a outra Maria.

[[v40-27-62]]

^<<v40-27-62,62>>^ No dia seguinte, que é o dia depois da preparação, reuniram-se os principais sacerdotes e os fariseus e, dirigindo-se a Pilatos,

[[v40-27-63]]

^<<v40-27-63,63>>^ disseram-lhe: Senhor, lembramo-nos de que aquele embusteiro, enquanto vivia, disse: Depois de três dias ressuscitarei.

[[v40-27-64]]

^<<v40-27-64,64>>^ Ordena, pois, que o sepulcro seja guardado com segurança até ao terceiro dia, para não suceder que, vindo os discípulos, o roubem e depois digam ao povo: Ressuscitou dos mortos; e será o último embuste pior que o primeiro.

[[v40-27-65]]

^<<v40-27-65,65>>^ Disse-lhes Pilatos: Aí tendes uma escolta; ide e guardai o sepulcro como bem vos parecer.

[[v40-27-66]]

^<<v40-27-66,66>>^ Indo eles, montaram guarda ao sepulcro, selando a pedra e deixando ali a escolta.

'''

xref:040-mateus/040-mateus-026.adoc#v40-26-0[&#60; Capítulo Anterior] | <<v40-27-0,Topo>> | xref:040-mateus/040-mateus-028.adoc#v40-28-0[Próximo Capítulo &#62;]