include::./index.adoc[]

[[v40-23-0]]
=== Mateus, 23
// ara ?, ARA - Almeida Revista e Atualizada

[[v40-23-1]]

^<<v40-23-1,1>>^ Então, falou Jesus às multidões e aos seus discípulos:

[[v40-23-2]]

^<<v40-23-2,2>>^ Na cadeira de Moisés, se assentaram os escribas e os fariseus.

[[v40-23-3]]

^<<v40-23-3,3>>^ Fazei e guardai, pois, tudo quanto eles vos disserem, porém não os imiteis nas suas obras; porque dizem e não fazem.

[[v40-23-4]]

^<<v40-23-4,4>>^ Atam fardos pesados [e difíceis de carregar] e os põem sobre os ombros dos homens; entretanto, eles mesmos nem com o dedo querem movê-los.

[[v40-23-5]]

^<<v40-23-5,5>>^ Praticam, porém, todas as suas obras com o fim de serem vistos dos homens; pois alargam os seus filactérios e alongam as suas franjas.

[[v40-23-6]]

^<<v40-23-6,6>>^ Amam o primeiro lugar nos banquetes e as primeiras cadeiras nas sinagogas,

[[v40-23-7]]

^<<v40-23-7,7>>^ as saudações nas praças e o serem chamados mestres pelos homens.

[[v40-23-8]]

^<<v40-23-8,8>>^ Vós, porém, não sereis chamados mestres, porque um só é vosso Mestre, e vós todos sois irmãos.

[[v40-23-9]]

^<<v40-23-9,9>>^ A ninguém sobre a terra chameis vosso pai; porque só um é vosso Pai, aquele que está nos céus.

[[v40-23-10]]

^<<v40-23-10,10>>^ Nem sereis chamados guias, porque um só é vosso Guia, o Cristo.

[[v40-23-11]]

^<<v40-23-11,11>>^ Mas o maior dentre vós será vosso servo.

[[v40-23-12]]

^<<v40-23-12,12>>^ Quem a si mesmo se exaltar será humilhado; e quem a si mesmo se humilhar será exaltado.

[[v40-23-13]]

^<<v40-23-13,13>>^ Ai de vós, escribas e fariseus, hipócritas, porque fechais o reino dos céus diante dos homens; pois vós não entrais, nem deixais entrar os que estão entrando!

[[v40-23-14]]

^<<v40-23-14,14>>^ [Ai de vós, escribas e fariseus, hipócritas, porque devorais as casas das viúvas e, para o justificar, fazeis longas orações; por isso, sofrereis juízo muito mais severo!]

[[v40-23-15]]

^<<v40-23-15,15>>^ Ai de vós, escribas e fariseus, hipócritas, porque rodeais o mar e a terra para fazer um prosélito; e, uma vez feito, o tornais filho do inferno duas vezes mais do que vós!

[[v40-23-16]]

^<<v40-23-16,16>>^ Ai de vós, guias cegos, que dizeis: Quem jurar pelo santuário, isso é nada; mas, se alguém jurar pelo ouro do santuário, fica obrigado pelo que jurou!

[[v40-23-17]]

^<<v40-23-17,17>>^ Insensatos e cegos! Pois qual é maior: o ouro ou o santuário que santifica o ouro?

[[v40-23-18]]

^<<v40-23-18,18>>^ E dizeis: Quem jurar pelo altar, isso é nada; quem, porém, jurar pela oferta que está sobre o altar fica obrigado pelo que jurou.

[[v40-23-19]]

^<<v40-23-19,19>>^ Cegos! Pois qual é maior: a oferta ou o altar que santifica a oferta?

[[v40-23-20]]

^<<v40-23-20,20>>^ Portanto, quem jurar pelo altar jura por ele e por tudo o que sobre ele está.

[[v40-23-21]]

^<<v40-23-21,21>>^ Quem jurar pelo santuário jura por ele e por aquele que nele habita;

[[v40-23-22]]

^<<v40-23-22,22>>^ e quem jurar pelo céu jura pelo trono de Deus e por aquele que no trono está sentado.

[[v40-23-23]]

^<<v40-23-23,23>>^ Ai de vós, escribas e fariseus, hipócritas, porque dais o dízimo da hortelã, do endro e do cominho e tendes negligenciado os preceitos mais importantes da Lei: a justiça, a misericórdia e a fé; devíeis, porém, fazer estas coisas, sem omitir aquelas!

[[v40-23-24]]

^<<v40-23-24,24>>^ Guias cegos, que coais o mosquito e engolis o camelo!

[[v40-23-25]]

^<<v40-23-25,25>>^ Ai de vós, escribas e fariseus, hipócritas, porque limpais o exterior do copo e do prato, mas estes, por dentro, estão cheios de rapina e intemperança!

[[v40-23-26]]

^<<v40-23-26,26>>^ Fariseu cego, limpa primeiro o interior do copo, para que também o seu exterior fique limpo!

[[v40-23-27]]

^<<v40-23-27,27>>^ Ai de vós, escribas e fariseus, hipócritas, porque sois semelhantes aos sepulcros caiados, que, por fora, se mostram belos, mas interiormente estão cheios de ossos de mortos e de toda imundícia!

[[v40-23-28]]

^<<v40-23-28,28>>^ Assim também vós exteriormente pareceis justos aos homens, mas, por dentro, estais cheios de hipocrisia e de iniquidade.

[[v40-23-29]]

^<<v40-23-29,29>>^ Ai de vós, escribas e fariseus, hipócritas, porque edificais os sepulcros dos profetas, adornais os túmulos dos justos

[[v40-23-30]]

^<<v40-23-30,30>>^ e dizeis: Se tivéssemos vivido nos dias de nossos pais, não teríamos sido seus cúmplices no sangue dos profetas!

[[v40-23-31]]

^<<v40-23-31,31>>^ Assim, contra vós mesmos, testificais que sois filhos dos que mataram os profetas.

[[v40-23-32]]

^<<v40-23-32,32>>^ Enchei vós, pois, a medida de vossos pais.

[[v40-23-33]]

^<<v40-23-33,33>>^ Serpentes, raça de víboras! Como escapareis da condenação do inferno?

[[v40-23-34]]

^<<v40-23-34,34>>^ Por isso, eis que eu vos envio profetas, sábios e escribas. A uns matareis e crucificareis; a outros açoitareis nas vossas sinagogas e perseguireis de cidade em cidade;

[[v40-23-35]]

^<<v40-23-35,35>>^ para que sobre vós recaia todo o sangue justo derramado sobre a terra, desde o sangue do justo Abel até ao sangue de Zacarias, filho de Baraquias, a quem matastes entre o santuário e o altar.

[[v40-23-36]]

^<<v40-23-36,36>>^ Em verdade vos digo que todas estas coisas hão de vir sobre a presente geração.

[[v40-23-37]]

^<<v40-23-37,37>>^ Jerusalém, Jerusalém, que matas os profetas e apedrejas os que te foram enviados! Quantas vezes quis eu reunir os teus filhos, como a galinha ajunta os seus pintinhos debaixo das asas, e vós não o quisestes!

[[v40-23-38]]

^<<v40-23-38,38>>^ Eis que a vossa casa vos ficará deserta.

[[v40-23-39]]

^<<v40-23-39,39>>^ Declaro-vos, pois, que, desde agora, já não me vereis, até que venhais a dizer: Bendito o que vem em nome do Senhor!

'''

xref:040-mateus/040-mateus-022.adoc#v40-22-0[&#60; Capítulo Anterior] | <<v40-23-0,Topo>> | xref:040-mateus/040-mateus-024.adoc#v40-24-0[Próximo Capítulo &#62;]