include::./index.adoc[]

[[v40-17-0]]
=== Mateus, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v40-17-1]]

^<<v40-17-1,1>>^ Seis dias depois, tomou Jesus consigo a Pedro e aos irmãos Tiago e João e os levou, em particular, a um alto monte.

[[v40-17-2]]

^<<v40-17-2,2>>^ E foi transfigurado diante deles; o seu rosto resplandecia como o sol, e as suas vestes tornaram-se brancas como a luz.

[[v40-17-3]]

^<<v40-17-3,3>>^ E eis que lhes apareceram Moisés e Elias, falando com ele.

[[v40-17-4]]

^<<v40-17-4,4>>^ Então, disse Pedro a Jesus: Senhor, bom é estarmos aqui; se queres, farei aqui três tendas; uma será tua, outra para Moisés, outra para Elias.

[[v40-17-5]]

^<<v40-17-5,5>>^ Falava ele ainda, quando uma nuvem luminosa os envolveu; e eis, vindo da nuvem, uma voz que dizia: Este é o meu Filho amado, em quem me comprazo; a ele ouvi.

[[v40-17-6]]

^<<v40-17-6,6>>^ Ouvindo-a os discípulos, caíram de bruços, tomados de grande medo.

[[v40-17-7]]

^<<v40-17-7,7>>^ Aproximando-se deles, tocou-lhes Jesus, dizendo: Erguei-vos e não temais!

[[v40-17-8]]

^<<v40-17-8,8>>^ Então, eles, levantando os olhos, a ninguém viram, senão Jesus.

[[v40-17-9]]

^<<v40-17-9,9>>^ E, descendo eles do monte, ordenou-lhes Jesus: A ninguém conteis a visão, até que o Filho do Homem ressuscite dentre os mortos.

[[v40-17-10]]

^<<v40-17-10,10>>^ Mas os discípulos o interrogaram: Por que dizem, pois, os escribas ser necessário que Elias venha primeiro?

[[v40-17-11]]

^<<v40-17-11,11>>^ Então, Jesus respondeu: De fato, Elias virá e restaurará todas as coisas.

[[v40-17-12]]

^<<v40-17-12,12>>^ Eu, porém, vos declaro que Elias já veio, e não o reconheceram; antes, fizeram com ele tudo quanto quiseram. Assim também o Filho do Homem há de padecer nas mãos deles.

[[v40-17-13]]

^<<v40-17-13,13>>^ Então, os discípulos entenderam que lhes falara a respeito de João Batista.

[[v40-17-14]]

^<<v40-17-14,14>>^ E, quando chegaram para junto da multidão, aproximou-se dele um homem, que se ajoelhou e disse:

[[v40-17-15]]

^<<v40-17-15,15>>^ Senhor, compadece-te de meu filho, porque é lunático e sofre muito; pois muitas vezes cai no fogo e outras muitas, na água.

[[v40-17-16]]

^<<v40-17-16,16>>^ Apresentei-o a teus discípulos, mas eles não puderam curá-lo.

[[v40-17-17]]

^<<v40-17-17,17>>^ Jesus exclamou: Ó geração incrédula e perversa! Até quando estarei convosco? Até quando vos sofrerei? Trazei-me aqui o menino.

[[v40-17-18]]

^<<v40-17-18,18>>^ E Jesus repreendeu o demônio, e este saiu do menino; e, desde aquela hora, ficou o menino curado.

[[v40-17-19]]

^<<v40-17-19,19>>^ Então, os discípulos, aproximando-se de Jesus, perguntaram em particular: Por que motivo não pudemos nós expulsá-lo?

[[v40-17-20]]

^<<v40-17-20,20>>^ E ele lhes respondeu: Por causa da pequenez da vossa fé. Pois em verdade vos digo que, se tiverdes fé como um grão de mostarda, direis a este monte: Passa daqui para acolá, e ele passará. Nada vos será impossível.

[[v40-17-21]]

^<<v40-17-21,21>>^ [Mas esta casta não se expele senão por meio de oração e jejum.]

[[v40-17-22]]

^<<v40-17-22,22>>^ Reunidos eles na Galileia, disse-lhes Jesus: O Filho do Homem está para ser entregue nas mãos dos homens;

[[v40-17-23]]

^<<v40-17-23,23>>^ e estes o matarão; mas, ao terceiro dia, ressuscitará.  Então, os discípulos se entristeceram grandemente.

[[v40-17-24]]

^<<v40-17-24,24>>^ Tendo eles chegado a Cafarnaum, dirigiram-se a Pedro os que cobravam o imposto das duas dracmas e perguntaram: Não paga o vosso Mestre as duas dracmas?

[[v40-17-25]]

^<<v40-17-25,25>>^ Sim, respondeu ele. Ao entrar Pedro em casa, Jesus se lhe antecipou, dizendo: Simão, que te parece? De quem cobram os reis da terra impostos ou tributo: dos seus filhos ou dos estranhos?

[[v40-17-26]]

^<<v40-17-26,26>>^ Respondendo Pedro: Dos estranhos, Jesus lhe disse: Logo, estão isentos os filhos.

[[v40-17-27]]

^<<v40-17-27,27>>^ Mas, para que não os escandalizemos, vai ao mar, lança o anzol, e o primeiro peixe que fisgar, tira-o; e, abrindo-lhe a boca, acharás um estáter. Toma-o e entrega-lhes por mim e por ti.

'''

xref:040-mateus/040-mateus-016.adoc#v40-16-0[&#60; Capítulo Anterior] | <<v40-17-0,Topo>> | xref:040-mateus/040-mateus-018.adoc#v40-18-0[Próximo Capítulo &#62;]