include::./index.adoc[]

[[v40-21-0]]
=== Mateus, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v40-21-1]]

^<<v40-21-1,1>>^ Quando se aproximaram de Jerusalém e chegaram a Betfagé, ao monte das Oliveiras, enviou Jesus dois discípulos, dizendo-lhes:

[[v40-21-2]]

^<<v40-21-2,2>>^ Ide à aldeia que aí está diante de vós e logo achareis presa uma jumenta e, com ela, um jumentinho. Desprendei-a e trazei-mos.

[[v40-21-3]]

^<<v40-21-3,3>>^ E, se alguém vos disser alguma coisa, respondei-lhe que o Senhor precisa deles. E logo os enviará.

[[v40-21-4]]

^<<v40-21-4,4>>^ Ora, isto aconteceu para se cumprir o que foi dito por intermédio do profeta:

[[v40-21-5]]

^<<v40-21-5,5>>^ Dizei à filha de Sião: Eis aí te vem o teu Rei, humilde, montado em jumento, num jumentinho, cria de animal de carga.

[[v40-21-6]]

^<<v40-21-6,6>>^ Indo os discípulos e tendo feito como Jesus lhes ordenara,

[[v40-21-7]]

^<<v40-21-7,7>>^ trouxeram a jumenta e o jumentinho. Então, puseram em cima deles as suas vestes, e sobre elas Jesus montou.

[[v40-21-8]]

^<<v40-21-8,8>>^ E a maior parte da multidão estendeu as suas vestes pelo caminho, e outros cortavam ramos de árvores, espalhando-os pela estrada.

[[v40-21-9]]

^<<v40-21-9,9>>^ E as multidões, tanto as que o precediam como as que o seguiam, clamavam: Hosana ao Filho de Davi! Bendito o que vem em nome do Senhor! Hosana nas maiores alturas!

[[v40-21-10]]

^<<v40-21-10,10>>^ E, entrando ele em Jerusalém, toda a cidade se alvoroçou, e perguntavam: Quem é este?

[[v40-21-11]]

^<<v40-21-11,11>>^ E as multidões clamavam: Este é o profeta Jesus, de Nazaré da Galileia!

[[v40-21-12]]

^<<v40-21-12,12>>^ Tendo Jesus entrado no templo, expulsou todos os que ali vendiam e compravam; também derribou as mesas dos cambistas e as cadeiras dos que vendiam pombas.

[[v40-21-13]]

^<<v40-21-13,13>>^ E disse-lhes: Está escrito: A minha casa será chamada casa de oração; vós, porém, a transformais em covil de salteadores.

[[v40-21-14]]

^<<v40-21-14,14>>^ Vieram a ele, no templo, cegos e coxos, e ele os curou.

[[v40-21-15]]

^<<v40-21-15,15>>^ Mas, vendo os principais sacerdotes e os escribas as maravilhas que Jesus fazia e os meninos clamando: Hosana ao Filho de Davi!, indignaram-se e perguntaram-lhe:

[[v40-21-16]]

^<<v40-21-16,16>>^ Ouves o que estes estão dizendo? Respondeu-lhes Jesus: Sim; nunca lestes: Da boca de pequeninos e crianças de peito tiraste perfeito louvor?

[[v40-21-17]]

^<<v40-21-17,17>>^ E, deixando-os, saiu da cidade para Betânia, onde pernoitou.

[[v40-21-18]]

^<<v40-21-18,18>>^ Cedo de manhã, ao voltar para a cidade, teve fome;

[[v40-21-19]]

^<<v40-21-19,19>>^ e, vendo uma figueira à beira do caminho, aproximou-se dela; e, não tendo achado senão folhas, disse-lhe: Nunca mais nasça fruto de ti!  E a figueira secou imediatamente.

[[v40-21-20]]

^<<v40-21-20,20>>^ Vendo isto os discípulos, admiraram-se e exclamaram: Como secou depressa a figueira!

[[v40-21-21]]

^<<v40-21-21,21>>^ Jesus, porém, lhes respondeu: Em verdade vos digo que, se tiverdes fé e não duvidardes, não somente fareis o que foi feito à figueira, mas até mesmo, se a este monte disserdes: Ergue-te e lança-te no mar, tal sucederá;

[[v40-21-22]]

^<<v40-21-22,22>>^ e tudo quanto pedirdes em oração, crendo, recebereis.

[[v40-21-23]]

^<<v40-21-23,23>>^ Tendo Jesus chegado ao templo, estando já ensinando, acercaram-se dele os principais sacerdotes e os anciãos do povo, perguntando: Com que autoridade fazes estas coisas? E quem te deu essa autoridade?

[[v40-21-24]]

^<<v40-21-24,24>>^ E Jesus lhes respondeu: Eu também vos farei uma pergunta; se me responderdes, também eu vos direi com que autoridade faço estas coisas.

[[v40-21-25]]

^<<v40-21-25,25>>^ Donde era o batismo de João, do céu ou dos homens?  E discorriam entre si: Se dissermos: do céu, ele nos dirá: Então, por que não acreditastes nele?

[[v40-21-26]]

^<<v40-21-26,26>>^ E, se dissermos: dos homens, é para temer o povo, porque todos consideram João como profeta.

[[v40-21-27]]

^<<v40-21-27,27>>^ Então, responderam a Jesus: Não sabemos. E ele, por sua vez: Nem eu vos digo com que autoridade faço estas coisas.

[[v40-21-28]]

^<<v40-21-28,28>>^ E que vos parece? Um homem tinha dois filhos. Chegando-se ao primeiro, disse: Filho, vai hoje trabalhar na vinha.

[[v40-21-29]]

^<<v40-21-29,29>>^ Ele respondeu: Sim, senhor; porém não foi.

[[v40-21-30]]

^<<v40-21-30,30>>^ Dirigindo-se ao segundo, disse-lhe a mesma coisa. Mas este respondeu: Não quero; depois, arrependido, foi.

[[v40-21-31]]

^<<v40-21-31,31>>^ Qual dos dois fez a vontade do pai?  Disseram: O segundo. Declarou-lhes Jesus: Em verdade vos digo que publicanos e meretrizes vos precedem no reino de Deus.

[[v40-21-32]]

^<<v40-21-32,32>>^ Porque João veio a vós outros no caminho da justiça, e não acreditastes nele; ao passo que publicanos e meretrizes creram. Vós, porém, mesmo vendo isto, não vos arrependestes, afinal, para acreditardes nele.

[[v40-21-33]]

^<<v40-21-33,33>>^ Atentai noutra parábola. Havia um homem, dono de casa, que plantou uma vinha. Cercou-a de uma sebe, construiu nela um lagar, edificou-lhe uma torre e arrendou-a a uns lavradores. Depois, se ausentou do país.

[[v40-21-34]]

^<<v40-21-34,34>>^ Ao tempo da colheita, enviou os seus servos aos lavradores, para receber os frutos que lhe tocavam.

[[v40-21-35]]

^<<v40-21-35,35>>^ E os lavradores, agarrando os servos, espancaram a um, mataram a outro e a outro apedrejaram.

[[v40-21-36]]

^<<v40-21-36,36>>^ Enviou ainda outros servos em maior número; e trataram-nos da mesma sorte.

[[v40-21-37]]

^<<v40-21-37,37>>^ E, por último, enviou-lhes o seu próprio filho, dizendo: A meu filho respeitarão.

[[v40-21-38]]

^<<v40-21-38,38>>^ Mas os lavradores, vendo o filho, disseram entre si: Este é o herdeiro; ora, vamos, matemo-lo e apoderemo-nos da sua herança.

[[v40-21-39]]

^<<v40-21-39,39>>^ E, agarrando-o, lançaram-no fora da vinha e o mataram.

[[v40-21-40]]

^<<v40-21-40,40>>^ Quando, pois, vier o senhor da vinha, que fará àqueles lavradores?

[[v40-21-41]]

^<<v40-21-41,41>>^ Responderam-lhe: Fará perecer horrivelmente a estes malvados e arrendará a vinha a outros lavradores que lhe remetam os frutos nos seus devidos tempos.

[[v40-21-42]]

^<<v40-21-42,42>>^ Perguntou-lhes Jesus: Nunca lestes nas Escrituras: A pedra que os construtores rejeitaram, essa veio a ser a principal pedra, angular; isto procede do Senhor e é maravilhoso aos nossos olhos?

[[v40-21-43]]

^<<v40-21-43,43>>^ Portanto, vos digo que o reino de Deus vos será tirado e será entregue a um povo que lhe produza os respectivos frutos.

[[v40-21-44]]

^<<v40-21-44,44>>^ Todo o que cair sobre esta pedra ficará em pedaços; e aquele sobre quem ela cair ficará reduzido a pó.

[[v40-21-45]]

^<<v40-21-45,45>>^ Os principais sacerdotes e os fariseus, ouvindo estas parábolas, entenderam que era a respeito deles que Jesus falava;

[[v40-21-46]]

^<<v40-21-46,46>>^ e, conquanto buscassem prendê-lo, temeram as multidões, porque estas o consideravam como profeta.

'''

xref:040-mateus/040-mateus-020.adoc#v40-20-0[&#60; Capítulo Anterior] | <<v40-21-0,Topo>> | xref:040-mateus/040-mateus-022.adoc#v40-22-0[Próximo Capítulo &#62;]