include::./index.adoc[]

[[v40-4-0]]
=== Mateus, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v40-4-1]]

^<<v40-4-1,1>>^ A seguir, foi Jesus levado pelo Espírito ao deserto, para ser tentado pelo diabo.

[[v40-4-2]]

^<<v40-4-2,2>>^ E, depois de jejuar quarenta dias e quarenta noites, teve fome.

[[v40-4-3]]

^<<v40-4-3,3>>^ Então, o tentador, aproximando-se, lhe disse: Se és Filho de Deus, manda que estas pedras se transformem em pães.

[[v40-4-4]]

^<<v40-4-4,4>>^ Jesus, porém, respondeu: Está escrito: Não só de pão viverá o homem, mas de toda palavra que procede da boca de Deus.

[[v40-4-5]]

^<<v40-4-5,5>>^ Então, o diabo o levou à Cidade Santa, colocou-o sobre o pináculo do templo

[[v40-4-6]]

^<<v40-4-6,6>>^ e lhe disse: Se és Filho de Deus, atira-te abaixo, porque está escrito: Aos seus anjos ordenará a teu respeito que te guardem; e: Eles te susterão nas suas mãos, para não tropeçares nalguma pedra.

[[v40-4-7]]

^<<v40-4-7,7>>^ Respondeu-lhe Jesus: Também está escrito: Não tentarás o Senhor, teu Deus.

[[v40-4-8]]

^<<v40-4-8,8>>^ Levou-o ainda o diabo a um monte muito alto, mostrou-lhe todos os reinos do mundo e a glória deles

[[v40-4-9]]

^<<v40-4-9,9>>^ e lhe disse: Tudo isto te darei se, prostrado, me adorares.

[[v40-4-10]]

^<<v40-4-10,10>>^ Então, Jesus lhe ordenou: Retira-te, Satanás, porque está escrito: Ao Senhor, teu Deus, adorarás, e só a ele darás culto.

[[v40-4-11]]

^<<v40-4-11,11>>^ Com isto, o deixou o diabo, e eis que vieram anjos e o serviram.

[[v40-4-12]]

^<<v40-4-12,12>>^ Ouvindo, porém, Jesus que João fora preso, retirou-se para a Galileia;

[[v40-4-13]]

^<<v40-4-13,13>>^ e, deixando Nazaré, foi morar em Cafarnaum, situada à beira-mar, nos confins de Zebulom e Naftali;

[[v40-4-14]]

^<<v40-4-14,14>>^ para que se cumprisse o que fora dito por intermédio do profeta Isaías:

[[v40-4-15]]

^<<v40-4-15,15>>^ Terra de Zebulom, terra de Naftali, caminho do mar, além do Jordão, Galileia dos gentios!

[[v40-4-16]]

^<<v40-4-16,16>>^ O povo que jazia em trevas viu grande luz, e aos que viviam na região e sombra da morte resplandeceu-lhes a luz.

[[v40-4-17]]

^<<v40-4-17,17>>^ Daí por diante, passou Jesus a pregar e a dizer: Arrependei-vos, porque está próximo o reino dos céus.

[[v40-4-18]]

^<<v40-4-18,18>>^ Caminhando junto ao mar da Galileia, viu dois irmãos, Simão, chamado Pedro, e André, que lançavam as redes ao mar, porque eram pescadores.

[[v40-4-19]]

^<<v40-4-19,19>>^ E disse-lhes: Vinde após mim, e eu vos farei pescadores de homens.

[[v40-4-20]]

^<<v40-4-20,20>>^ Então, eles deixaram imediatamente as redes e o seguiram.

[[v40-4-21]]

^<<v40-4-21,21>>^ Passando adiante, viu outros dois irmãos, Tiago, filho de Zebedeu, e João, seu irmão, que estavam no barco em companhia de seu pai, consertando as redes; e chamou-os.

[[v40-4-22]]

^<<v40-4-22,22>>^ Então, eles, no mesmo instante, deixando o barco e seu pai, o seguiram.

[[v40-4-23]]

^<<v40-4-23,23>>^ Percorria Jesus toda a Galileia, ensinando nas sinagogas, pregando o evangelho do reino e curando toda sorte de doenças e enfermidades entre o povo.

[[v40-4-24]]

^<<v40-4-24,24>>^ E a sua fama correu por toda a Síria; trouxeram-lhe, então, todos os doentes, acometidos de várias enfermidades e tormentos: endemoninhados, lunáticos e paralíticos. E ele os curou.

[[v40-4-25]]

^<<v40-4-25,25>>^ E da Galileia, Decápolis, Jerusalém, Judeia e dalém do Jordão numerosas multidões o seguiam.

'''

xref:040-mateus/040-mateus-003.adoc#v40-3-0[&#60; Capítulo Anterior] | <<v40-4-0,Topo>> | xref:040-mateus/040-mateus-005.adoc#v40-5-0[Próximo Capítulo &#62;]