include::./index.adoc[]

[[v22-7-0]]
=== Cânticos, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v22-7-1]]

^<<v22-7-1,1>>^ Que formosos são os teus passos dados de sandálias, ó filha do príncipe! Os meneios dos teus quadris são como colares trabalhados por mãos de artista.

[[v22-7-2]]

^<<v22-7-2,2>>^ O teu umbigo é taça redonda, a que não falta bebida; o teu ventre é monte de trigo, cercado de lírios.

[[v22-7-3]]

^<<v22-7-3,3>>^ Os teus dois seios, como duas crias, gêmeas de uma gazela.

[[v22-7-4]]

^<<v22-7-4,4>>^ O teu pescoço, como torre de marfim; os teus olhos são as piscinas de Hesbom, junto à porta de Bate-Rabim; o teu nariz, como a torre do Líbano, que olha para Damasco.

[[v22-7-5]]

^<<v22-7-5,5>>^ A tua cabeça é como o monte Carmelo, a tua cabeleira, como a púrpura; um rei está preso nas tuas tranças.

[[v22-7-6]]

^<<v22-7-6,6>>^ Quão formosa e quão aprazível és, ó amor em delícias!

[[v22-7-7]]

^<<v22-7-7,7>>^ Esse teu porte é semelhante à palmeira, e os teus seios, a seus cachos.

[[v22-7-8]]

^<<v22-7-8,8>>^ Dizia eu: subirei à palmeira, pegarei em seus ramos. Sejam os teus seios como os cachos da vide, e o aroma da tua respiração, como o das maçãs.

[[v22-7-9]]

^<<v22-7-9,9>>^ Os teus beijos são como o bom vinho, vinho que se escoa suavemente para o meu amado, deslizando entre seus lábios e dentes.

[[v22-7-10]]

^<<v22-7-10,10>>^ Eu sou do meu amado, e ele tem saudades de mim.

[[v22-7-11]]

^<<v22-7-11,11>>^ Vem, ó meu amado, saiamos ao campo, passemos as noites nas aldeias.

[[v22-7-12]]

^<<v22-7-12,12>>^ Levantemo-nos cedo de manhã para ir às vinhas; vejamos se florescem as vides, se se abre a flor, se já brotam as romeiras; dar-te-ei ali o meu amor.

[[v22-7-13]]

^<<v22-7-13,13>>^ As mandrágoras exalam o seu perfume, e às nossas portas há toda sorte de excelentes frutos, novos e velhos; eu tos reservei, ó meu amado.

'''

xref:022-canticos/022-canticos-006.adoc#v22-6-0[&#60; Capítulo Anterior] | <<v22-7-0,Topo>> | xref:022-canticos/022-canticos-008.adoc#v22-8-0[Próximo Capítulo &#62;]