include::./index.adoc[]

[[v22-4-0]]
=== Cânticos, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v22-4-1]]

^<<v22-4-1,1>>^ Como és formosa, querida minha, como és formosa! Os teus olhos são como os das pombas e brilham através do teu véu. Os teus cabelos são como o rebanho de cabras que descem ondeantes do monte de Gileade.

[[v22-4-2]]

^<<v22-4-2,2>>^ São os teus dentes como o rebanho das ovelhas recém-tosquiadas, que sobem do lavadouro, e das quais todas produzem gêmeos, e nenhuma delas há sem crias.

[[v22-4-3]]

^<<v22-4-3,3>>^ Os teus lábios são como um fio de escarlata, e tua boca é formosa; as tuas faces, como romã partida, brilham através do véu.

[[v22-4-4]]

^<<v22-4-4,4>>^ O teu pescoço é como a torre de Davi, edificada para arsenal; mil escudos pendem dela, todos broquéis de soldados valorosos.

[[v22-4-5]]

^<<v22-4-5,5>>^ Os teus dois seios são como duas crias, gêmeas de uma gazela, que se apascentam entre os lírios.

[[v22-4-6]]

^<<v22-4-6,6>>^ Antes que refresque o dia, e fujam as sombras, irei ao monte da mirra e ao outeiro do incenso.

[[v22-4-7]]

^<<v22-4-7,7>>^ Tu és toda formosa, querida minha, e em ti não há defeito.

[[v22-4-8]]

^<<v22-4-8,8>>^ Vem comigo do Líbano, noiva minha, vem comigo do Líbano; olha do cimo do Amana, do cimo do Senir e do Hermom, dos covis dos leões, dos montes dos leopardos.

[[v22-4-9]]

^<<v22-4-9,9>>^ Arrebataste-me o coração, minha irmã, noiva minha; arrebataste-me o coração com um só dos teus olhares, com uma só pérola do teu colar.

[[v22-4-10]]

^<<v22-4-10,10>>^ Que belo é o teu amor, ó minha irmã, noiva minha! Quanto melhor é o teu amor do que o vinho, e o aroma dos teus unguentos do que toda sorte de especiarias!

[[v22-4-11]]

^<<v22-4-11,11>>^ Os teus lábios, noiva minha, destilam mel. Mel e leite se acham debaixo da tua língua, e a fragrância dos teus vestidos é como a do Líbano.

[[v22-4-12]]

^<<v22-4-12,12>>^ Jardim fechado és tu, minha irmã, noiva minha, manancial recluso, fonte selada.

[[v22-4-13]]

^<<v22-4-13,13>>^ Os teus renovos são um pomar de romãs, com frutos excelentes: a hena e o nardo;

[[v22-4-14]]

^<<v22-4-14,14>>^ o nardo e o açafrão, o cálamo e o cinamomo, com toda a sorte de árvores de incenso, a mirra e o aloés, com todas as principais especiarias.

[[v22-4-15]]

^<<v22-4-15,15>>^ És fonte dos jardins, poço das águas vivas, torrentes que correm do Líbano!

[[v22-4-16]]

^<<v22-4-16,16>>^ Levanta-te, vento norte, e vem tu, vento sul; assopra no meu jardim, para que se derramem os seus aromas. Ah! Venha o meu amado para o seu jardim e coma os seus frutos excelentes!

'''

xref:022-canticos/022-canticos-003.adoc#v22-3-0[&#60; Capítulo Anterior] | <<v22-4-0,Topo>> | xref:022-canticos/022-canticos-005.adoc#v22-5-0[Próximo Capítulo &#62;]