include::./index.adoc[]

[[v22-3-0]]
=== Cânticos, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v22-3-1]]

^<<v22-3-1,1>>^ De noite, no meu leito, busquei o amado de minha alma, busquei-o e não o achei.

[[v22-3-2]]

^<<v22-3-2,2>>^ Levantar-me-ei, pois, e rodearei a cidade, pelas ruas e pelas praças; buscarei o amado da minha alma. Busquei-o e não o achei.

[[v22-3-3]]

^<<v22-3-3,3>>^ Encontraram-me os guardas, que rondavam pela cidade. Então, lhes perguntei: vistes o amado da minha alma?

[[v22-3-4]]

^<<v22-3-4,4>>^ Mal os deixei, encontrei logo o amado da minha alma; agarrei-me a ele e não o deixei ir embora, até que o fiz entrar em casa de minha mãe e na recâmara daquela que me concebeu.

[[v22-3-5]]

^<<v22-3-5,5>>^ Conjuro-vos, ó filhas de Jerusalém, pelas gazelas e cervas do campo, que não acordeis, nem desperteis o amor, até que este o queira.

[[v22-3-6]]

^<<v22-3-6,6>>^ Que é isso que sobe do deserto, como colunas de fumaça, perfumado de mirra, e de incenso, e de toda sorte de pós aromáticos do mercador?

[[v22-3-7]]

^<<v22-3-7,7>>^ É a liteira de Salomão; sessenta valentes estão ao redor dela, dos valentes de Israel.

[[v22-3-8]]

^<<v22-3-8,8>>^ Todos sabem manejar a espada e são destros na guerra; cada um leva a espada à cinta, por causa dos temores noturnos.

[[v22-3-9]]

^<<v22-3-9,9>>^ O rei Salomão fez para si um palanquim de madeira do Líbano.

[[v22-3-10]]

^<<v22-3-10,10>>^ Fez-lhe as colunas de prata, a espalda de ouro, o assento de púrpura, e tudo interiormente ornado com amor pelas filhas de Jerusalém.

[[v22-3-11]]

^<<v22-3-11,11>>^ Saí, ó filhas de Sião, e contemplai ao rei Salomão com a coroa com que sua mãe o coroou no dia do seu desposório, no dia do júbilo do seu coração.

'''

xref:022-canticos/022-canticos-002.adoc#v22-2-0[&#60; Capítulo Anterior] | <<v22-3-0,Topo>> | xref:022-canticos/022-canticos-004.adoc#v22-4-0[Próximo Capítulo &#62;]