include::./index.adoc[]

[[v22-8-0]]
=== Cânticos, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v22-8-1]]

^<<v22-8-1,1>>^ Tomara fosses como meu irmão, que mamou os seios de minha mãe! Quando te encontrasse na rua, beijar-te-ia, e não me desprezariam!

[[v22-8-2]]

^<<v22-8-2,2>>^ Levar-te-ia e te introduziria na casa de minha mãe, e tu me ensinarias; eu te daria a beber vinho aromático e mosto das minhas romãs.

[[v22-8-3]]

^<<v22-8-3,3>>^ A sua mão esquerda estaria debaixo da minha cabeça, e a sua direita me abraçaria.

[[v22-8-4]]

^<<v22-8-4,4>>^ Conjuro-vos, ó filhas de Jerusalém, que não acordeis, nem desperteis o amor, até que este o queira.

[[v22-8-5]]

^<<v22-8-5,5>>^ Quem é esta que sobe do deserto e vem encostada ao seu amado? Debaixo da macieira te despertei, ali esteve tua mãe com dores; ali esteve com dores aquela que te deu à luz.

[[v22-8-6]]

^<<v22-8-6,6>>^ Põe-me como selo sobre o teu coração, como selo sobre o teu braço, porque o amor é forte como a morte, e duro como a sepultura, o ciúme; as suas brasas são brasas de fogo, são veementes labaredas.

[[v22-8-7]]

^<<v22-8-7,7>>^ As muitas águas não poderiam apagar o amor, nem os rios, afogá-lo; ainda que alguém desse todos os bens da sua casa pelo amor, seria de todo desprezado.

[[v22-8-8]]

^<<v22-8-8,8>>^ Temos uma irmãzinha que ainda não tem seios; que faremos a esta nossa irmã, no dia em que for pedida?

[[v22-8-9]]

^<<v22-8-9,9>>^ Se ela for um muro, edificaremos sobre ele uma torre de prata; se for uma porta, cercá-la-emos com tábuas de cedro.

[[v22-8-10]]

^<<v22-8-10,10>>^ Eu sou um muro, e os meus seios, como as suas torres; sendo eu assim, fui tida por digna da confiança do meu amado.

[[v22-8-11]]

^<<v22-8-11,11>>^ Teve Salomão uma vinha em Baal-Hamom; entregou-a a uns guardas, e cada um lhe trazia pelo seu fruto mil peças de prata.

[[v22-8-12]]

^<<v22-8-12,12>>^ A vinha que me pertence está ao meu dispor; tu, ó Salomão, terás os mil siclos, e os que guardam o fruto dela, duzentos.

[[v22-8-13]]

^<<v22-8-13,13>>^ Ó tu que habitas nos jardins, os companheiros estão atentos para ouvir a tua voz; faze-me, pois, também ouvi-la.

[[v22-8-14]]

^<<v22-8-14,14>>^ Vem depressa, amado meu, faze-te semelhante ao gamo ou ao filho da gazela, que saltam sobre os montes aromáticos.

'''

xref:022-canticos/022-canticos-007.adoc#v22-7-0[&#60; Capítulo Anterior] | <<v22-8-0,Topo>> | xref:023-isaias/023-isaias-001.adoc#v23-1-0[Próximo Capítulo &#62;]