include::./index.adoc[]

[[v22-2-0]]
=== Cânticos, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v22-2-1]]

^<<v22-2-1,1>>^ Eu sou a rosa de Sarom, o lírio dos vales.

[[v22-2-2]]

^<<v22-2-2,2>>^ Qual o lírio entre os espinhos, tal é a minha querida entre as donzelas.

[[v22-2-3]]

^<<v22-2-3,3>>^ Qual a macieira entre as árvores do bosque, tal é o meu amado entre os jovens; desejo muito a sua sombra e debaixo dela me assento, e o seu fruto é doce ao meu paladar.

[[v22-2-4]]

^<<v22-2-4,4>>^ Leva-me à sala do banquete, e o seu estandarte sobre mim é o amor.

[[v22-2-5]]

^<<v22-2-5,5>>^ Sustentai-me com passas, confortai-me com maçãs, pois desfaleço de amor.

[[v22-2-6]]

^<<v22-2-6,6>>^ A sua mão esquerda esteja debaixo da minha cabeça, e a direita me abrace.

[[v22-2-7]]

^<<v22-2-7,7>>^ Conjuro-vos, ó filhas de Jerusalém, pelas gazelas e cervas do campo, que não acordeis, nem desperteis o amor, até que este o queira.

[[v22-2-8]]

^<<v22-2-8,8>>^ Ouço a voz do meu amado; ei-lo aí galgando os montes, pulando sobre os outeiros.

[[v22-2-9]]

^<<v22-2-9,9>>^ O meu amado é semelhante ao gamo ou ao filho da gazela; eis que está detrás da nossa parede, olhando pelas janelas, espreitando pelas grades.

[[v22-2-10]]

^<<v22-2-10,10>>^ O meu amado fala e me diz: Levanta-te, querida minha, formosa minha, e vem.

[[v22-2-11]]

^<<v22-2-11,11>>^ Porque eis que passou o inverno, cessou a chuva e se foi;

[[v22-2-12]]

^<<v22-2-12,12>>^ aparecem as flores na terra, chegou o tempo de cantarem as aves, e a voz da rola ouve-se em nossa terra.

[[v22-2-13]]

^<<v22-2-13,13>>^ A figueira começou a dar seus figos, e as vides em flor exalam o seu aroma; levanta-te, querida minha, formosa minha, e vem.

[[v22-2-14]]

^<<v22-2-14,14>>^ Pomba minha, que andas pelas fendas dos penhascos, no esconderijo das rochas escarpadas, mostra-me o rosto, faze-me ouvir a tua voz, porque a tua voz é doce, e o teu rosto, amável.

[[v22-2-15]]

^<<v22-2-15,15>>^ Apanhai-me as raposas, as raposinhas, que devastam os vinhedos, porque as nossas vinhas estão em flor.

[[v22-2-16]]

^<<v22-2-16,16>>^ O meu amado é meu, e eu sou dele; ele apascenta o seu rebanho entre os lírios.

[[v22-2-17]]

^<<v22-2-17,17>>^ Antes que refresque o dia e fujam as sombras, volta, amado meu; faze-te semelhante ao gamo ou ao filho das gazelas sobre os montes escabrosos.

'''

xref:022-canticos/022-canticos-001.adoc#v22-1-0[&#60; Capítulo Anterior] | <<v22-2-0,Topo>> | xref:022-canticos/022-canticos-003.adoc#v22-3-0[Próximo Capítulo &#62;]