include::./index.adoc[]

[[v22-5-0]]
=== Cânticos, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v22-5-1]]

^<<v22-5-1,1>>^ Já entrei no meu jardim, minha irmã, noiva minha; colhi a minha mirra com a especiaria, comi o meu favo com o mel, bebi o meu vinho com o leite. Comei e bebei, amigos; bebei fartamente, ó amados.

[[v22-5-2]]

^<<v22-5-2,2>>^ Eu dormia, mas o meu coração velava; eis a voz do meu amado, que está batendo: Abre-me, minha irmã, querida minha, pomba minha, imaculada minha, porque a minha cabeça está cheia de orvalho, os meus cabelos, das gotas da noite.

[[v22-5-3]]

^<<v22-5-3,3>>^ Já despi a minha túnica, hei de vesti-la outra vez? Já lavei os pés, tornarei a sujá-los?

[[v22-5-4]]

^<<v22-5-4,4>>^ O meu amado meteu a mão por uma fresta, e o meu coração se comoveu por amor dele.

[[v22-5-5]]

^<<v22-5-5,5>>^ Levantei-me para abrir ao meu amado; as minhas mãos destilavam mirra, e os meus dedos mirra preciosa sobre a maçaneta do ferrolho.

[[v22-5-6]]

^<<v22-5-6,6>>^ Abri ao meu amado, mas já ele se retirara e tinha ido embora; a minha alma se derreteu quando, antes, ele me falou; busquei-o e não o achei; chamei-o, e não me respondeu.

[[v22-5-7]]

^<<v22-5-7,7>>^ Encontraram-me os guardas que rondavam pela cidade; espancaram-me e feriram-me; tiraram-me o manto os guardas dos muros.

[[v22-5-8]]

^<<v22-5-8,8>>^ Conjuro-vos, ó filhas de Jerusalém, se encontrardes o meu amado, que lhe direis? Que desfaleço de amor.

[[v22-5-9]]

^<<v22-5-9,9>>^ Que é o teu amado mais do que outro amado, ó tu, a mais formosa entre as mulheres? Que é o teu amado mais do que outro amado, que tanto nos conjuras?

[[v22-5-10]]

^<<v22-5-10,10>>^ O meu amado é alvo e rosado, o mais distinguido entre dez mil.

[[v22-5-11]]

^<<v22-5-11,11>>^ A sua cabeça é como o ouro mais apurado, os seus cabelos, cachos de palmeira, são pretos como o corvo.

[[v22-5-12]]

^<<v22-5-12,12>>^ Os seus olhos são como os das pombas junto às correntes das águas, lavados em leite, postos em engaste.

[[v22-5-13]]

^<<v22-5-13,13>>^ As suas faces são como um canteiro de bálsamo, como colinas de ervas aromáticas; os seus lábios são lírios que gotejam mirra preciosa;

[[v22-5-14]]

^<<v22-5-14,14>>^ as suas mãos, cilindros de ouro, embutidos de jacintos; o seu ventre, como alvo marfim, coberto de safiras.

[[v22-5-15]]

^<<v22-5-15,15>>^ As suas pernas, colunas de mármore, assentadas em bases de ouro puro; o seu aspecto, como o Líbano, esbelto como os cedros.

[[v22-5-16]]

^<<v22-5-16,16>>^ O seu falar é muitíssimo doce; sim, ele é totalmente desejável. Tal é o meu amado, tal, o meu esposo, ó filhas de Jerusalém.

'''

xref:022-canticos/022-canticos-004.adoc#v22-4-0[&#60; Capítulo Anterior] | <<v22-5-0,Topo>> | xref:022-canticos/022-canticos-006.adoc#v22-6-0[Próximo Capítulo &#62;]