include::./index.adoc[]

[[v22-1-0]]
=== Cânticos, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v22-1-1]]

^<<v22-1-1,1>>^ Cântico dos cânticos de Salomão.

[[v22-1-2]]

^<<v22-1-2,2>>^ Beija-me com os beijos de tua boca; porque melhor é o teu amor do que o vinho.

[[v22-1-3]]

^<<v22-1-3,3>>^ Suave é o aroma dos teus unguentos, como unguento derramado é o teu nome; por isso, as donzelas te amam.

[[v22-1-4]]

^<<v22-1-4,4>>^ Leva-me após ti, apressemo-nos. O rei me introduziu nas suas recâmaras. Em ti nos regozijaremos e nos alegraremos; do teu amor nos lembraremos, mais do que do vinho; não é sem razão que te amam.

[[v22-1-5]]

^<<v22-1-5,5>>^ Eu estou morena e formosa, ó filhas de Jerusalém, como as tendas de Quedar, como as cortinas de Salomão.

[[v22-1-6]]

^<<v22-1-6,6>>^ Não olheis para o eu estar morena, porque o sol me queimou. Os filhos de minha mãe se indignaram contra mim e me puseram por guarda de vinhas; a vinha, porém, que me pertence, não a guardei.

[[v22-1-7]]

^<<v22-1-7,7>>^ Dize-me, ó amado de minha alma: onde apascentas o teu rebanho, onde o fazes repousar pelo meio-dia, para que não ande eu vagando junto ao rebanho dos teus companheiros?

[[v22-1-8]]

^<<v22-1-8,8>>^ Se tu não o sabes, ó mais formosa entre as mulheres, sai-te pelas pisadas dos rebanhos e apascenta os teus cabritos junto às tendas dos pastores.

[[v22-1-9]]

^<<v22-1-9,9>>^ Às éguas dos carros de Faraó te comparo, ó querida minha.

[[v22-1-10]]

^<<v22-1-10,10>>^ Formosas são as tuas faces entre os teus enfeites, o teu pescoço, com os colares.

[[v22-1-11]]

^<<v22-1-11,11>>^ Enfeites de ouro te faremos, com incrustações de prata.

[[v22-1-12]]

^<<v22-1-12,12>>^ Enquanto o rei está assentado à sua mesa, o meu nardo exala o seu perfume.

[[v22-1-13]]

^<<v22-1-13,13>>^ O meu amado é para mim um saquitel de mirra, posto entre os meus seios.

[[v22-1-14]]

^<<v22-1-14,14>>^ Como um racimo de flores de hena nas vinhas de En-Gedi, é para mim o meu amado.

[[v22-1-15]]

^<<v22-1-15,15>>^ Eis que és formosa, ó querida minha, eis que és formosa; os teus olhos são como os das pombas.

[[v22-1-16]]

^<<v22-1-16,16>>^ Como és formoso, amado meu, como és amável! O nosso leito é de viçosas folhas,

[[v22-1-17]]

^<<v22-1-17,17>>^ as traves da nossa casa são de cedro, e os seus caibros, de cipreste.

'''

xref:021-eclesiastes/021-eclesiastes-012.adoc#v21-12-0[&#60; Capítulo Anterior] | <<v22-1-0,Topo>> | xref:022-canticos/022-canticos-002.adoc#v22-2-0[Próximo Capítulo &#62;]