include::./index.adoc[]

[[v22-6-0]]
=== Cânticos, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v22-6-1]]

^<<v22-6-1,1>>^ Para onde foi o teu amado, ó mais formosa entre as mulheres? Que rumo tomou o teu amado? E o buscaremos contigo.

[[v22-6-2]]

^<<v22-6-2,2>>^ O meu amado desceu ao seu jardim, aos canteiros de bálsamo, para pastorear nos jardins e para colher os lírios.

[[v22-6-3]]

^<<v22-6-3,3>>^ Eu sou do meu amado, e o meu amado é meu; ele pastoreia entre os lírios.

[[v22-6-4]]

^<<v22-6-4,4>>^ Formosa és, querida minha, como Tirza, aprazível como Jerusalém, formidável como um exército com bandeiras.

[[v22-6-5]]

^<<v22-6-5,5>>^ Desvia de mim os olhos, porque eles me perturbam. Os teus cabelos descem ondeantes como o rebanho das cabras de Gileade.

[[v22-6-6]]

^<<v22-6-6,6>>^ São os teus dentes como o rebanho de ovelhas que sobem do lavadouro, e das quais todas produzem gêmeos, e nenhuma delas há sem crias.

[[v22-6-7]]

^<<v22-6-7,7>>^ As tuas faces, como romã partida, brilham através do véu.

[[v22-6-8]]

^<<v22-6-8,8>>^ Sessenta são as rainhas, oitenta, as concubinas, e as virgens, sem número.

[[v22-6-9]]

^<<v22-6-9,9>>^ Mas uma só é a minha pomba, a minha imaculada, de sua mãe, a única, a predileta daquela que a deu à luz; viram-na as donzelas e lhe chamaram ditosa; viram-na as rainhas e as concubinas e a louvaram.

[[v22-6-10]]

^<<v22-6-10,10>>^ Quem é esta que aparece como a alva do dia, formosa como a lua, pura como o sol, formidável como um exército com bandeiras?

[[v22-6-11]]

^<<v22-6-11,11>>^ Desci ao jardim das nogueiras, para mirar os renovos do vale, para ver se brotavam as vides, se floresciam as romeiras.

[[v22-6-12]]

^<<v22-6-12,12>>^ Não sei como, imaginei-me no carro do meu nobre povo!

[[v22-6-13]]

^<<v22-6-13,13>>^ Volta, volta, ó sulamita, volta, volta, para que nós te contemplemos. Por que quereis contemplar a sulamita na dança de Maanaim?

'''

xref:022-canticos/022-canticos-005.adoc#v22-5-0[&#60; Capítulo Anterior] | <<v22-6-0,Topo>> | xref:022-canticos/022-canticos-007.adoc#v22-7-0[Próximo Capítulo &#62;]