include::./index.adoc[]

[[v17-4-0]]
=== Ester, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v17-4-1]]

^<<v17-4-1,1>>^ Quando soube Mordecai tudo quanto se havia passado, rasgou as suas vestes, e se cobriu de pano de saco e de cinza, e, saindo pela cidade, clamou com grande e amargo clamor;

[[v17-4-2]]

^<<v17-4-2,2>>^ e chegou até à porta do rei; porque ninguém vestido de pano de saco podia entrar pelas portas do rei.

[[v17-4-3]]

^<<v17-4-3,3>>^ Em todas as províncias aonde chegava a palavra do rei e a sua lei, havia entre os judeus grande luto, com jejum, e choro, e lamentação; e muitos se deitavam em pano de saco e em cinza.

[[v17-4-4]]

^<<v17-4-4,4>>^ Então, vieram as servas de Ester e os eunucos e fizeram-na saber, com o que a rainha muito se doeu; e mandou roupas para vestir a Mordecai e tirar-lhe o pano de saco; porém ele não as aceitou.

[[v17-4-5]]

^<<v17-4-5,5>>^ Então, Ester chamou a Hataque, um dos eunucos do rei, que este lhe dera para a servir, e lhe ordenou que fosse a Mordecai para saber que era aquilo e o seu motivo.

[[v17-4-6]]

^<<v17-4-6,6>>^ Saiu, pois, Hataque à praça da cidade para encontrar-se com Mordecai à porta do rei.

[[v17-4-7]]

^<<v17-4-7,7>>^ Mordecai lhe fez saber tudo quanto lhe tinha sucedido; como também a quantia certa da prata que Hamã prometera pagar aos tesouros do rei pelo aniquilamento dos judeus.

[[v17-4-8]]

^<<v17-4-8,8>>^ Também lhe deu o traslado do decreto escrito que se publicara em Susã para os destruir, para que o mostrasse a Ester e a fizesse saber, a fim de que fosse ter com o rei, e lhe pedisse misericórdia, e, na sua presença, lhe suplicasse pelo povo dela.

[[v17-4-9]]

^<<v17-4-9,9>>^ Tornou, pois, Hataque e fez saber a Ester as palavras de Mordecai.

[[v17-4-10]]

^<<v17-4-10,10>>^ Então, respondeu Ester a Hataque e mandou-lhe dizer a Mordecai:

[[v17-4-11]]

^<<v17-4-11,11>>^ Todos os servos do rei e o povo das províncias do rei sabem que, para qualquer homem ou mulher que, sem ser chamado, entrar no pátio interior para avistar-se com o rei, não há senão uma sentença, a de morte, salvo se o rei estender para ele o cetro de ouro, para que viva; e eu, nestes trinta dias, não fui chamada para entrar ao rei.

[[v17-4-12]]

^<<v17-4-12,12>>^ Fizeram saber a Mordecai as palavras de Ester.

[[v17-4-13]]

^<<v17-4-13,13>>^ Então, lhes disse Mordecai que respondessem a Ester: Não imagines que, por estares na casa do rei, só tu escaparás entre todos os judeus.

[[v17-4-14]]

^<<v17-4-14,14>>^ Porque, se de todo te calares agora, de outra parte se levantará para os judeus socorro e livramento, mas tu e a casa de teu pai perecereis; e quem sabe se para conjuntura como esta é que foste elevada a rainha?

[[v17-4-15]]

^<<v17-4-15,15>>^ Então, disse Ester que respondessem a Mordecai:

[[v17-4-16]]

^<<v17-4-16,16>>^ Vai, ajunta a todos os judeus que se acharem em Susã, e jejuai por mim, e não comais, nem bebais por três dias, nem de noite nem de dia; eu e as minhas servas também jejuaremos. Depois, irei ter com o rei, ainda que é contra a lei; se perecer, pereci.

[[v17-4-17]]

^<<v17-4-17,17>>^ Então, se foi Mordecai e tudo fez segundo Ester lhe havia ordenado.

'''

xref:017-ester/017-ester-003.adoc#v17-3-0[&#60; Capítulo Anterior] | <<v17-4-0,Topo>> | xref:017-ester/017-ester-005.adoc#v17-5-0[Próximo Capítulo &#62;]