include::./index.adoc[]

[[v17-9-0]]
=== Ester, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v17-9-1]]

^<<v17-9-1,1>>^ No dia treze do duodécimo mês, que é o mês de adar, quando chegou a palavra do rei e a sua ordem para se executar, no dia em que os inimigos dos judeus contavam assenhorear-se deles, sucedeu o contrário, pois os judeus é que se assenhorearam dos que os odiavam;

[[v17-9-2]]

^<<v17-9-2,2>>^ porque os judeus, nas suas cidades, em todas as províncias do rei Assuero, se ajuntaram para dar cabo daqueles que lhes procuravam o mal; e ninguém podia resistir-lhes, porque o terror que inspiravam caiu sobre todos aqueles povos.

[[v17-9-3]]

^<<v17-9-3,3>>^ Todos os príncipes das províncias, e os sátrapas, e os governadores, e os oficiais do rei auxiliavam os judeus, porque tinha caído sobre eles o temor de Mordecai.

[[v17-9-4]]

^<<v17-9-4,4>>^ Porque Mordecai era grande na casa do rei, e a sua fama crescia por todas as províncias; pois ele se ia tornando mais e mais poderoso.

[[v17-9-5]]

^<<v17-9-5,5>>^ Feriram, pois, os judeus a todos os seus inimigos, a golpes de espada, com matança e destruição; e fizeram dos seus inimigos o que bem quiseram.

[[v17-9-6]]

^<<v17-9-6,6>>^ Na cidadela de Susã, os judeus mataram e destruíram a quinhentos homens,

[[v17-9-7]]

^<<v17-9-7,7>>^ como também a Parsandata, a Dalfom, a Aspata,

[[v17-9-8]]

^<<v17-9-8,8>>^ a Porata, a Adalia, a Aridata,

[[v17-9-9]]

^<<v17-9-9,9>>^ a Farmasta, a Arisai, a Aridai e a Vaizata,

[[v17-9-10]]

^<<v17-9-10,10>>^ que eram os dez filhos de Hamã, filho de Hamedata, o inimigo dos judeus; porém no despojo não tocaram.

[[v17-9-11]]

^<<v17-9-11,11>>^ No mesmo dia, foi comunicado ao rei o número dos mortos na cidadela de Susã.

[[v17-9-12]]

^<<v17-9-12,12>>^ Disse o rei à rainha Ester: Na cidadela de Susã, mataram e destruíram os judeus a quinhentos homens e os dez filhos de Hamã; nas mais províncias do rei, que terão eles feito? Qual é, pois, a tua petição? E se te dará. Ou que é que desejas ainda? E se cumprirá.

[[v17-9-13]]

^<<v17-9-13,13>>^ Então, disse Ester: Se bem parecer ao rei, conceda-se aos judeus que se acham em Susã que também façam, amanhã, segundo o edito de hoje e dependurem em forca os cadáveres dos dez filhos de Hamã.

[[v17-9-14]]

^<<v17-9-14,14>>^ Então, disse o rei que assim se fizesse; publicou-se o edito em Susã, e dependuraram os cadáveres dos dez filhos de Hamã.

[[v17-9-15]]

^<<v17-9-15,15>>^ Reuniram-se os judeus que se achavam em Susã também no dia catorze do mês de adar, e mataram, em Susã, a trezentos homens; porém no despojo não tocaram.

[[v17-9-16]]

^<<v17-9-16,16>>^ Também os demais judeus que se achavam nas províncias do rei se reuniram, e se dispuseram para defender a vida, e tiveram sossego dos seus inimigos; e mataram a setenta e cinco mil dos que os odiavam; porém no despojo não tocaram.

[[v17-9-17]]

^<<v17-9-17,17>>^ Sucedeu isto no dia treze do mês de adar; no dia catorze, descansaram e o fizeram dia de banquetes e de alegria.

[[v17-9-18]]

^<<v17-9-18,18>>^ Os judeus, porém, que se achavam em Susã se ajuntaram nos dias treze e catorze do mesmo; e descansaram no dia quinze e o fizeram dia de banquetes e de alegria.

[[v17-9-19]]

^<<v17-9-19,19>>^ Também os judeus das vilas que habitavam nas aldeias abertas fizeram do dia catorze do mês de adar dia de alegria e de banquetes e dia de festa e de mandarem porções dos banquetes uns aos outros.

[[v17-9-20]]

^<<v17-9-20,20>>^ Mordecai escreveu estas coisas e enviou cartas a todos os judeus que se achavam em todas as províncias do rei Assuero, aos de perto e aos de longe,

[[v17-9-21]]

^<<v17-9-21,21>>^ ordenando-lhes que comemorassem o dia catorze do mês de adar e o dia quinze do mesmo, todos os anos,

[[v17-9-22]]

^<<v17-9-22,22>>^ como os dias em que os judeus tiveram sossego dos seus inimigos, e o mês que se lhes mudou de tristeza em alegria, e de luto em dia de festa; para que os fizessem dias de banquetes e de alegria, e de mandarem porções dos banquetes uns aos outros, e dádivas aos pobres.

[[v17-9-23]]

^<<v17-9-23,23>>^ Assim, os judeus aceitaram como costume o que, naquele tempo, haviam feito pela primeira vez, segundo Mordecai lhes prescrevera;

[[v17-9-24]]

^<<v17-9-24,24>>^ porque Hamã, filho de Hamedata, o agagita, inimigo de todos os judeus, tinha intentado destruir os judeus; e tinha lançado o Pur, isto é, sortes, para os assolar e destruir.

[[v17-9-25]]

^<<v17-9-25,25>>^ Mas, tendo Ester ido perante o rei, ordenou ele por cartas que o seu mau intento, que assentara contra os judeus, recaísse contra a própria cabeça dele, pelo que enforcaram a ele e a seus filhos.

[[v17-9-26]]

^<<v17-9-26,26>>^ Por isso, àqueles dias chamam Purim, do nome Pur. Daí, por causa de todas as palavras daquela carta, e do que testemunharam, e do que lhes havia sucedido,

[[v17-9-27]]

^<<v17-9-27,27>>^ determinaram os judeus e tomaram sobre si, sobre a sua descendência e sobre todos os que se chegassem a eles que não se deixaria de comemorar estes dois dias segundo o que se escrevera deles e segundo o seu tempo marcado, todos os anos;

[[v17-9-28]]

^<<v17-9-28,28>>^ e que estes dias seriam lembrados e comemorados geração após geração, por todas as famílias, em todas as províncias e em todas as cidades, e que estes dias de Purim jamais caducariam entre os judeus, e que a memória deles jamais se extinguiria entre os seus descendentes.

[[v17-9-29]]

^<<v17-9-29,29>>^ Então, a rainha Ester, filha de Abiail, e o judeu Mordecai escreveram, com toda a autoridade, segunda vez, para confirmar a carta de Purim.

[[v17-9-30]]

^<<v17-9-30,30>>^ Expediram cartas a todos os judeus, às cento e vinte e sete províncias do reino de Assuero, com palavras amigáveis e sinceras,

[[v17-9-31]]

^<<v17-9-31,31>>^ para confirmar estes dias de Purim nos seus tempos determinados, como o judeu Mordecai e a rainha Ester lhes tinham estabelecido, e como eles mesmos já o tinham estabelecido sobre si e sobre a sua descendência, acerca do jejum e do seu lamento.

[[v17-9-32]]

^<<v17-9-32,32>>^ E o mandado de Ester estabeleceu estas particularidades de Purim; e se escreveu no livro.

'''

xref:017-ester/017-ester-008.adoc#v17-8-0[&#60; Capítulo Anterior] | <<v17-9-0,Topo>> | xref:017-ester/017-ester-010.adoc#v17-10-0[Próximo Capítulo &#62;]