include::./index.adoc[]

[[v17-8-0]]
=== Ester, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v17-8-1]]

^<<v17-8-1,1>>^ Naquele mesmo dia, deu o rei Assuero à rainha Ester a casa de Hamã, inimigo dos judeus; e Mordecai veio perante o rei, porque Ester lhe fez saber que era seu parente.

[[v17-8-2]]

^<<v17-8-2,2>>^ Tirou o rei o seu anel, que tinha tomado a Hamã, e o deu a Mordecai. E Ester pôs a Mordecai por superintendente da casa de Hamã.

[[v17-8-3]]

^<<v17-8-3,3>>^ Falou mais Ester perante o rei e se lhe lançou aos pés; e, com lágrimas, lhe implorou que revogasse a maldade de Hamã, o agagita, e a trama que havia empreendido contra os judeus.

[[v17-8-4]]

^<<v17-8-4,4>>^ Estendeu o rei para Ester o cetro de ouro. Então, ela se levantou, pôs-se de pé diante do rei

[[v17-8-5]]

^<<v17-8-5,5>>^ e lhe disse: Se bem parecer ao rei, se eu achei favor perante ele, se esta coisa é reta diante do rei, e se nisto lhe agrado, escreva-se que se revoguem os decretos concebidos por Hamã, filho de Hamedata, o agagita, os quais ele escreveu para aniquilar os judeus que há em todas as províncias do rei.

[[v17-8-6]]

^<<v17-8-6,6>>^ Pois como poderei ver o mal que sobrevirá ao meu povo? E como poderei ver a destruição da minha parentela?

[[v17-8-7]]

^<<v17-8-7,7>>^ Então, disse o rei Assuero à rainha Ester e ao judeu Mordecai: Eis que dei a Ester a casa de Hamã, e a ele penduraram numa forca, porquanto intentara matar os judeus.

[[v17-8-8]]

^<<v17-8-8,8>>^ Escrevei, pois, aos judeus, como bem vos parecer, em nome do rei, e selai-o com o anel do rei; porque os decretos feitos em nome do rei e que com o seu anel se selam não se podem revogar.

[[v17-8-9]]

^<<v17-8-9,9>>^ Então, foram chamados, sem detença, os secretários do rei, aos vinte e três dias do mês de sivã, que é o terceiro mês. E, segundo tudo quanto ordenou Mordecai, se escreveu um edito para os judeus, para os sátrapas, para os governadores e para os príncipes das províncias que se estendem da Índia à Etiópia, cento e vinte e sete províncias, a cada uma no seu próprio modo de escrever, e a cada povo na sua própria língua; e também aos judeus segundo o seu próprio modo de escrever e a sua própria língua.

[[v17-8-10]]

^<<v17-8-10,10>>^ Escreveu-se em nome do rei Assuero, e se selou com o anel do rei; as cartas foram enviadas por intermédio de correios montados em ginetes criados na coudelaria do rei.

[[v17-8-11]]

^<<v17-8-11,11>>^ Nelas, o rei concedia aos judeus de cada cidade que se reunissem e se dispusessem para defender a sua vida, para destruir, matar e aniquilar de vez toda e qualquer força armada do povo da província que viessem contra eles, crianças e mulheres, e que se saqueassem os seus bens,

[[v17-8-12]]

^<<v17-8-12,12>>^ num mesmo dia, em todas as províncias do rei Assuero, no dia treze do duodécimo mês, que é o mês de adar.

[[v17-8-13]]

^<<v17-8-13,13>>^ A carta, que determinava a proclamação do edito em todas as províncias, foi enviada a todos os povos, para que os judeus se preparassem para aquele dia, para se vingarem dos seus inimigos.

[[v17-8-14]]

^<<v17-8-14,14>>^ Os correios, montados em ginetes que se usavam no serviço do rei, saíram incontinenti, impelidos pela ordem do rei; e o edito foi publicado na cidadela de Susã.

[[v17-8-15]]

^<<v17-8-15,15>>^ Então, Mordecai saiu da presença do rei com veste real azul-celeste e branco, como também com grande coroa de ouro e manto de linho fino e púrpura; e a cidade de Susã exultou e se alegrou.

[[v17-8-16]]

^<<v17-8-16,16>>^ Para os judeus houve felicidade, alegria, regozijo e honra.

[[v17-8-17]]

^<<v17-8-17,17>>^ Também em toda província e em toda cidade aonde chegava a palavra do rei e a sua ordem, havia entre os judeus alegria e regozijo, banquetes e festas; e muitos, dos povos da terra, se fizeram judeus, porque o temor dos judeus tinha caído sobre eles.

'''

xref:017-ester/017-ester-007.adoc#v17-7-0[&#60; Capítulo Anterior] | <<v17-8-0,Topo>> | xref:017-ester/017-ester-009.adoc#v17-9-0[Próximo Capítulo &#62;]