include::./index.adoc[]

[[v17-6-0]]
=== Ester, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v17-6-1]]

^<<v17-6-1,1>>^ Naquela noite, o rei não pôde dormir; então, mandou trazer o Livro dos Feitos Memoráveis, e nele se leu diante do rei.

[[v17-6-2]]

^<<v17-6-2,2>>^ Achou-se escrito que Mordecai é quem havia denunciado a Bigtã e a Teres, os dois eunucos do rei, guardas da porta, que tinham procurado matar o rei Assuero.

[[v17-6-3]]

^<<v17-6-3,3>>^ Então, disse o rei: Que honras e distinções se deram a Mordecai por isso? Nada lhe foi conferido, responderam os servos do rei que o serviam.

[[v17-6-4]]

^<<v17-6-4,4>>^ Perguntou o rei: Quem está no pátio? Ora, Hamã tinha entrado no pátio exterior da casa do rei, para dizer ao rei que se enforcasse a Mordecai na forca que ele, Hamã, lhe tinha preparado.

[[v17-6-5]]

^<<v17-6-5,5>>^ Os servos do rei lhe disseram: Hamã está no pátio. Disse o rei que entrasse.

[[v17-6-6]]

^<<v17-6-6,6>>^ Entrou Hamã. O rei lhe disse: Que se fará ao homem a quem o rei deseja honrar? Então, Hamã disse consigo mesmo: De quem se agradaria o rei mais do que de mim para honrá-lo?

[[v17-6-7]]

^<<v17-6-7,7>>^ E respondeu ao rei: Quanto ao homem a quem agrada ao rei honrá-lo,

[[v17-6-8]]

^<<v17-6-8,8>>^ tragam-se as vestes reais, que o rei costuma usar, e o cavalo em que o rei costuma andar montado, e tenha na cabeça a coroa real;

[[v17-6-9]]

^<<v17-6-9,9>>^ entreguem-se as vestes e o cavalo às mãos dos mais nobres príncipes do rei, e vistam delas aquele a quem o rei deseja honrar; levem-no a cavalo pela praça da cidade e diante dele apregoem: Assim se faz ao homem a quem o rei deseja honrar.

[[v17-6-10]]

^<<v17-6-10,10>>^ Então, disse o rei a Hamã: Apressa-te, toma as vestes e o cavalo, como disseste, e faze assim para com o judeu Mordecai, que está assentado à porta do rei; e não omitas coisa nenhuma de tudo quanto disseste.

[[v17-6-11]]

^<<v17-6-11,11>>^ Hamã tomou as vestes e o cavalo, vestiu a Mordecai, e o levou a cavalo pela praça da cidade, e apregoou diante dele: Assim se faz ao homem a quem o rei deseja honrar.

[[v17-6-12]]

^<<v17-6-12,12>>^ Depois disto, Mordecai voltou para a porta do rei; porém Hamã se retirou correndo para casa, angustiado e de cabeça coberta.

[[v17-6-13]]

^<<v17-6-13,13>>^ Contou Hamã a Zeres, sua mulher, e a todos os seus amigos tudo quanto lhe tinha sucedido. Então, os seus sábios e Zeres, sua mulher, lhe disseram: Se Mordecai, perante o qual já começaste a cair, é da descendência dos judeus, não prevalecerás contra ele; antes, certamente, cairás diante dele.

[[v17-6-14]]

^<<v17-6-14,14>>^ Falavam estes ainda com ele quando chegaram os eunucos do rei e apressadamente levaram Hamã ao banquete que Ester preparara.

'''

xref:017-ester/017-ester-005.adoc#v17-5-0[&#60; Capítulo Anterior] | <<v17-6-0,Topo>> | xref:017-ester/017-ester-007.adoc#v17-7-0[Próximo Capítulo &#62;]