include::./index.adoc[]

[[v17-1-0]]
=== Ester, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v17-1-1]]

^<<v17-1-1,1>>^ Nos dias de Assuero, o Assuero que reinou, desde a Índia até à Etiópia, sobre cento e vinte e sete províncias,

[[v17-1-2]]

^<<v17-1-2,2>>^ naqueles dias, assentando-se o rei Assuero no trono do seu reino, que está na cidadela de Susã,

[[v17-1-3]]

^<<v17-1-3,3>>^ no terceiro ano de seu reinado, deu um banquete a todos os seus príncipes e seus servos, no qual se representou o escol da Pérsia e Média, e os nobres e príncipes das províncias estavam perante ele.

[[v17-1-4]]

^<<v17-1-4,4>>^ Então, mostrou as riquezas da glória do seu reino e o esplendor da sua excelente grandeza, por muitos dias, por cento e oitenta dias.

[[v17-1-5]]

^<<v17-1-5,5>>^ Passados esses dias, deu o rei um banquete a todo o povo que se achava na cidadela de Susã, tanto para os maiores como para os menores, por sete dias, no pátio do jardim do palácio real.

[[v17-1-6]]

^<<v17-1-6,6>>^ Havia tecido branco, linho fino e estofas de púrpura atados com cordões de linho e de púrpura a argolas de prata e a colunas de alabastro. A armação dos leitos era de ouro e de prata, sobre um pavimento de pórfiro, de mármore, de alabastro e de pedras preciosas.

[[v17-1-7]]

^<<v17-1-7,7>>^ Dava-se-lhes de beber em vasos de ouro, vasos de várias espécies, e havia muito vinho real, graças à generosidade do rei.

[[v17-1-8]]

^<<v17-1-8,8>>^ Bebiam sem constrangimento, como estava prescrito, pois o rei havia ordenado a todos os oficiais da sua casa que fizessem segundo a vontade de cada um.

[[v17-1-9]]

^<<v17-1-9,9>>^ Também a rainha Vasti deu um banquete às mulheres na casa real do rei Assuero.

[[v17-1-10]]

^<<v17-1-10,10>>^ Ao sétimo dia, estando já o coração do rei alegre do vinho, mandou a Meumã, Bizta, Harbona, Bigtá, Abagta, Zetar e Carcas, os sete eunucos que serviam na presença do rei Assuero,

[[v17-1-11]]

^<<v17-1-11,11>>^ que introduzissem à presença do rei a rainha Vasti, com a coroa real, para mostrar aos povos e aos príncipes a formosura dela, pois era em extremo formosa.

[[v17-1-12]]

^<<v17-1-12,12>>^ Porém a rainha Vasti recusou vir por intermédio dos eunucos, segundo a palavra do rei; pelo que o rei muito se enfureceu e se inflamou de ira.

[[v17-1-13]]

^<<v17-1-13,13>>^ Então, o rei consultou os sábios que entendiam dos tempos (porque assim se tratavam os interesses do rei na presença de todos os que sabiam a lei e o direito;

[[v17-1-14]]

^<<v17-1-14,14>>^ e os mais chegados a ele eram: Carsena, Setar, Admata, Társis, Meres, Marsena e Memucã, os sete príncipes dos persas e dos medos, que se avistavam pessoalmente com o rei e se assentavam como principais no reino)

[[v17-1-15]]

^<<v17-1-15,15>>^ sobre o que se devia fazer, segundo a lei, à rainha Vasti, por não haver ela cumprido o mandado do rei Assuero, por intermédio dos eunucos.

[[v17-1-16]]

^<<v17-1-16,16>>^ Então, disse Memucã na presença do rei e dos príncipes: A rainha Vasti não somente ofendeu ao rei, mas também a todos os príncipes e a todos os povos que há em todas as províncias do rei Assuero.

[[v17-1-17]]

^<<v17-1-17,17>>^ Porque a notícia do que fez a rainha chegará a todas as mulheres, de modo que desprezarão a seu marido, quando ouvirem dizer: Mandou o rei Assuero que introduzissem à sua presença a rainha Vasti, porém ela não foi.

[[v17-1-18]]

^<<v17-1-18,18>>^ Hoje mesmo, as princesas da Pérsia e da Média, ao ouvirem o que fez a rainha, dirão o mesmo a todos os príncipes do rei; e haverá daí muito desprezo e indignação.

[[v17-1-19]]

^<<v17-1-19,19>>^ Se bem parecer ao rei, promulgue de sua parte um edito real, e que se inscreva nas leis dos persas e dos medos e não se revogue, que Vasti não entre jamais na presença do rei Assuero; e o rei dê o reino dela a outra que seja melhor do que ela.

[[v17-1-20]]

^<<v17-1-20,20>>^ Quando for ouvido o mandado, que o rei decretar em todo o seu reino, vasto que é, todas as mulheres darão honra a seu marido, tanto ao mais importante como ao menos importante.

[[v17-1-21]]

^<<v17-1-21,21>>^ O conselho pareceu bem tanto ao rei como aos príncipes; e fez o rei segundo a palavra de Memucã.

[[v17-1-22]]

^<<v17-1-22,22>>^ Então, enviou cartas a todas as províncias do rei, a cada província segundo o seu modo de escrever e a cada povo segundo a sua língua: que cada homem fosse senhor em sua casa, e que se falasse a língua do seu povo.

'''

xref:016-neemias/016-neemias-013.adoc#v16-13-0[&#60; Capítulo Anterior] | <<v17-1-0,Topo>> | xref:017-ester/017-ester-002.adoc#v17-2-0[Próximo Capítulo &#62;]