include::./index.adoc[]

[[v17-2-0]]
=== Ester, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v17-2-1]]

^<<v17-2-1,1>>^ Passadas estas coisas, e apaziguado já o furor do rei Assuero, lembrou-se de Vasti, e do que ela fizera, e do que se tinha decretado contra ela.

[[v17-2-2]]

^<<v17-2-2,2>>^ Então, disseram os jovens do rei, que lhe serviam: Tragam-se moças para o rei, virgens de boa aparência e formosura.

[[v17-2-3]]

^<<v17-2-3,3>>^ Ponha o rei comissários em todas as províncias do seu reino, que reúnam todas as moças virgens, de boa aparência e formosura, na cidadela de Susã, na casa das mulheres, sob as vistas de Hegai, eunuco do rei, guarda das mulheres, e deem-se-lhes os seus unguentos.

[[v17-2-4]]

^<<v17-2-4,4>>^ A moça que cair no agrado do rei, essa reine em lugar de Vasti. Com isto concordou o rei, e assim se fez.

[[v17-2-5]]

^<<v17-2-5,5>>^ Ora, na cidadela de Susã havia certo homem judeu, benjamita, chamado Mordecai, filho de Jair, filho de Simei, filho de Quis,

[[v17-2-6]]

^<<v17-2-6,6>>^ que fora transportado de Jerusalém com os exilados que foram deportados com Jeconias, rei de Judá, a quem Nabucodonosor, rei da Babilônia, havia transportado.

[[v17-2-7]]

^<<v17-2-7,7>>^ Ele criara a Hadassa, que é Ester, filha de seu tio, a qual não tinha pai nem mãe; e era jovem bela, de boa aparência e formosura. Tendo-lhe morrido o pai e a mãe, Mordecai a tomara por filha.

[[v17-2-8]]

^<<v17-2-8,8>>^ Em se divulgando, pois, o mandado do rei e a sua lei, ao serem ajuntadas muitas moças na cidadela de Susã, sob as vistas de Hegai, levaram também Ester à casa do rei, sob os cuidados de Hegai, guarda das mulheres.

[[v17-2-9]]

^<<v17-2-9,9>>^ A moça lhe pareceu formosa e alcançou favor perante ele; pelo que se apressou em dar-lhe os unguentos e os devidos alimentos, como também sete jovens escolhidas da casa do rei; e a fez passar com as suas jovens para os melhores aposentos da casa das mulheres.

[[v17-2-10]]

^<<v17-2-10,10>>^ Ester não havia declarado o seu povo nem a sua linhagem, pois Mordecai lhe ordenara que o não declarasse.

[[v17-2-11]]

^<<v17-2-11,11>>^ Passeava Mordecai todos os dias diante do átrio da casa das mulheres, para se informar de como passava Ester e do que lhe sucederia.

[[v17-2-12]]

^<<v17-2-12,12>>^ Em chegando o prazo de cada moça vir ao rei Assuero, depois de tratada segundo as prescrições para as mulheres, por doze meses (porque assim se cumpriam os dias de seu embelezamento, seis meses com óleo de mirra e seis meses com especiarias e com os perfumes e unguentos em uso entre as mulheres),

[[v17-2-13]]

^<<v17-2-13,13>>^ então, é que vinha a jovem ao rei; a ela se dava o que desejasse para levar consigo da casa das mulheres para a casa do rei.

[[v17-2-14]]

^<<v17-2-14,14>>^ À tarde, entrava e, pela manhã, tornava à segunda casa das mulheres, sob as vistas de Saasgaz, eunuco do rei, guarda das concubinas; não tornava mais ao rei, salvo se o rei a desejasse, e ela fosse chamada pelo nome.

[[v17-2-15]]

^<<v17-2-15,15>>^ Ester, filha de Abiail, tio de Mordecai, que a tomara por filha, quando lhe chegou a vez de ir ao rei, nada pediu além do que disse Hegai, eunuco do rei, guarda das mulheres. E Ester alcançou favor de todos quantos a viam.

[[v17-2-16]]

^<<v17-2-16,16>>^ Assim, foi levada Ester ao rei Assuero, à casa real, no décimo mês, que é o mês de tebete, no sétimo ano do seu reinado.

[[v17-2-17]]

^<<v17-2-17,17>>^ O rei amou a Ester mais do que a todas as mulheres, e ela alcançou perante ele favor e benevolência mais do que todas as virgens; o rei pôs-lhe na cabeça a coroa real e a fez rainha em lugar de Vasti.

[[v17-2-18]]

^<<v17-2-18,18>>^ Então, o rei deu um grande banquete a todos os seus príncipes e aos seus servos; era o banquete de Ester; concedeu alívio às províncias e fez presentes segundo a generosidade real.

[[v17-2-19]]

^<<v17-2-19,19>>^ Quando, pela segunda vez, se reuniram as virgens, Mordecai estava assentado à porta do rei.

[[v17-2-20]]

^<<v17-2-20,20>>^ Ester não havia declarado ainda a sua linhagem e o seu povo, como Mordecai lhe ordenara; porque Ester cumpria o mandado de Mordecai como quando a criava.

[[v17-2-21]]

^<<v17-2-21,21>>^ Naqueles dias, estando Mordecai sentado à porta do rei, dois eunucos do rei, dos guardas da porta, Bigtã e Teres, sobremodo se indignaram e tramaram atentar contra o rei Assuero.

[[v17-2-22]]

^<<v17-2-22,22>>^ Veio isso ao conhecimento de Mordecai, que o revelou à rainha Ester, e Ester o disse ao rei, em nome de Mordecai.

[[v17-2-23]]

^<<v17-2-23,23>>^ Investigou-se o caso, e era fato; e ambos foram pendurados numa forca. Isso foi escrito no Livro das Crônicas, perante o rei.

'''

xref:017-ester/017-ester-001.adoc#v17-1-0[&#60; Capítulo Anterior] | <<v17-2-0,Topo>> | xref:017-ester/017-ester-003.adoc#v17-3-0[Próximo Capítulo &#62;]