include::./index.adoc[]

[[v17-5-0]]
=== Ester, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v17-5-1]]

^<<v17-5-1,1>>^ Ao terceiro dia, Ester se aprontou com seus trajes reais e se pôs no pátio interior da casa do rei, defronte da residência do rei; o rei estava assentado no seu trono real fronteiro à porta da residência.

[[v17-5-2]]

^<<v17-5-2,2>>^ Quando o rei viu a rainha Ester parada no pátio, alcançou ela favor perante ele; estendeu o rei para Ester o cetro de ouro que tinha na mão; Ester se chegou e tocou a ponta do cetro.

[[v17-5-3]]

^<<v17-5-3,3>>^ Então, lhe disse o rei: Que é o que tens, rainha Ester, ou qual é a tua petição? Até metade do reino se te dará.

[[v17-5-4]]

^<<v17-5-4,4>>^ Respondeu Ester: Se bem te parecer, venha o rei e Hamã, hoje, ao banquete que eu preparei ao rei.

[[v17-5-5]]

^<<v17-5-5,5>>^ Então, disse o rei: Fazei apressar a Hamã, para que atendamos ao que Ester deseja. Vindo, pois, o rei e Hamã ao banquete que Ester havia preparado,

[[v17-5-6]]

^<<v17-5-6,6>>^ disse o rei a Ester, no banquete do vinho: Qual é a tua petição? E se te dará. Que desejas? Cumprir-se-á, ainda que seja metade do reino.

[[v17-5-7]]

^<<v17-5-7,7>>^ Então, respondeu Ester e disse: Minha petição e desejo são o seguinte:

[[v17-5-8]]

^<<v17-5-8,8>>^ se achei favor perante o rei, e se bem parecer ao rei conceder-me a petição e cumprir o meu desejo, venha o rei com Hamã ao banquete que lhes hei de preparar amanhã, e, então, farei segundo o rei me concede.

[[v17-5-9]]

^<<v17-5-9,9>>^ Então, saiu Hamã, naquele dia, alegre e de bom ânimo; quando viu, porém, Mordecai à porta do rei e que não se levantara, nem se movera diante dele, então, se encheu de furor contra Mordecai.

[[v17-5-10]]

^<<v17-5-10,10>>^ Hamã, porém, se conteve e foi para casa; e mandou vir os seus amigos e a Zeres, sua mulher.

[[v17-5-11]]

^<<v17-5-11,11>>^ Contou-lhes Hamã a glória das suas riquezas e a multidão de seus filhos, e tudo em que o rei o tinha engrandecido, e como o tinha exaltado sobre os príncipes e servos do rei.

[[v17-5-12]]

^<<v17-5-12,12>>^ Disse mais Hamã: A própria rainha Ester a ninguém fez vir com o rei ao banquete que tinha preparado, senão a mim; e também para amanhã estou convidado por ela, juntamente com o rei.

[[v17-5-13]]

^<<v17-5-13,13>>^ Porém tudo isto não me satisfaz, enquanto vir o judeu Mordecai assentado à porta do rei.

[[v17-5-14]]

^<<v17-5-14,14>>^ Então, lhe disse Zeres, sua mulher, e todos os seus amigos: Faça-se uma forca de cinquenta côvados de altura, e, pela manhã, dize ao rei que nela enforquem Mordecai; então, entra alegre com o rei ao banquete. A sugestão foi bem-aceita por Hamã, que mandou levantar a forca.

'''

xref:017-ester/017-ester-004.adoc#v17-4-0[&#60; Capítulo Anterior] | <<v17-5-0,Topo>> | xref:017-ester/017-ester-006.adoc#v17-6-0[Próximo Capítulo &#62;]