include::./index.adoc[]

[[v17-3-0]]
=== Ester, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v17-3-1]]

^<<v17-3-1,1>>^ Depois destas coisas, o rei Assuero engrandeceu a Hamã, filho de Hamedata, agagita, e o exaltou, e lhe pôs o trono acima de todos os príncipes que estavam com ele.

[[v17-3-2]]

^<<v17-3-2,2>>^ Todos os servos do rei, que estavam à porta do rei, se inclinavam e se prostravam perante Hamã; porque assim tinha ordenado o rei a respeito dele. Mordecai, porém, não se inclinava, nem se prostrava.

[[v17-3-3]]

^<<v17-3-3,3>>^ Então, os servos do rei, que estavam à porta do rei, disseram a Mordecai: Por que transgrides as ordens do rei?

[[v17-3-4]]

^<<v17-3-4,4>>^ Sucedeu, pois, que, dizendo-lhe eles isto, dia após dia, e não lhes dando ele ouvidos, o fizeram saber a Hamã, para ver se as palavras de Mordecai se manteriam de pé, porque ele lhes tinha declarado que era judeu.

[[v17-3-5]]

^<<v17-3-5,5>>^ Vendo, pois, Hamã que Mordecai não se inclinava, nem se prostrava diante dele, encheu-se de furor.

[[v17-3-6]]

^<<v17-3-6,6>>^ Porém teve como pouco, nos seus propósitos, o atentar apenas contra Mordecai, porque lhe haviam declarado de que povo era Mordecai; por isso, procurou Hamã destruir todos os judeus, povo de Mordecai, que havia em todo o reino de Assuero.

[[v17-3-7]]

^<<v17-3-7,7>>^ No primeiro mês, que é o mês de nisã, no ano duodécimo do rei Assuero, se lançou o Pur, isto é, sortes, perante Hamã, dia a dia, mês a mês, até ao duodécimo, que é o mês de adar.

[[v17-3-8]]

^<<v17-3-8,8>>^ Então, disse Hamã ao rei Assuero: Existe espalhado, disperso entre os povos em todas as províncias do teu reino, um povo cujas leis são diferentes das leis de todos os povos e que não cumpre as do rei; pelo que não convém ao rei tolerá-lo.

[[v17-3-9]]

^<<v17-3-9,9>>^ Se bem parecer ao rei, decrete-se que sejam mortos, e, nas próprias mãos dos que executarem a obra, eu pesarei dez mil talentos de prata para que entrem nos tesouros do rei.

[[v17-3-10]]

^<<v17-3-10,10>>^ Então, o rei tirou da mão o seu anel, deu-o a Hamã, filho de Hamedata, agagita, adversário dos judeus,

[[v17-3-11]]

^<<v17-3-11,11>>^ e lhe disse: Essa prata seja tua, como também esse povo, para fazeres dele o que melhor for de teu agrado.

[[v17-3-12]]

^<<v17-3-12,12>>^ Chamaram, pois, os secretários do rei, no dia treze do primeiro mês, e, segundo ordenou Hamã, tudo se escreveu aos sátrapas do rei, aos governadores de todas as províncias e aos príncipes de cada povo; a cada província no seu próprio modo de escrever e a cada povo na sua própria língua. Em nome do rei Assuero se escreveu, e com o anel do rei se selou.

[[v17-3-13]]

^<<v17-3-13,13>>^ Enviaram-se as cartas, por intermédio dos correios, a todas as províncias do rei, para que se destruíssem, matassem e aniquilassem de vez a todos os judeus, moços e velhos, crianças e mulheres, em um só dia, no dia treze do duodécimo mês, que é o mês de adar, e que lhes saqueassem os bens.

[[v17-3-14]]

^<<v17-3-14,14>>^ Tais cartas encerravam o traslado do decreto para que se proclamasse a lei em cada província; esse traslado foi enviado a todos os povos para que se preparassem para aquele dia.

[[v17-3-15]]

^<<v17-3-15,15>>^ Os correios, pois, impelidos pela ordem do rei, partiram incontinenti, e a lei se proclamou na cidadela de Susã; o rei e Hamã se assentaram a beber, mas a cidade de Susã estava perplexa.

'''

xref:017-ester/017-ester-002.adoc#v17-2-0[&#60; Capítulo Anterior] | <<v17-3-0,Topo>> | xref:017-ester/017-ester-004.adoc#v17-4-0[Próximo Capítulo &#62;]