include::./index.adoc[]

[[v3-4-0]]
=== Levítico, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-4-1]]

^<<v3-4-1,1>>^ Disse mais o SENHOR a Moisés:

[[v3-4-2]]

^<<v3-4-2,2>>^ Fala aos filhos de Israel, dizendo: Quando alguém pecar por ignorância contra qualquer dos mandamentos do SENHOR, por fazer contra algum deles o que não se deve fazer,

[[v3-4-3]]

^<<v3-4-3,3>>^ se o sacerdote ungido pecar para escândalo do povo, oferecerá pelo seu pecado um novilho sem defeito ao SENHOR, como oferta pelo pecado.

[[v3-4-4]]

^<<v3-4-4,4>>^ Trará o novilho à porta da tenda da congregação, perante o SENHOR; porá a mão sobre a cabeça do novilho e o imolará perante o SENHOR.

[[v3-4-5]]

^<<v3-4-5,5>>^ Então, o sacerdote ungido tomará do sangue do novilho e o trará à tenda da congregação;

[[v3-4-6]]

^<<v3-4-6,6>>^ e, molhando o dedo no sangue, aspergirá dele sete vezes perante o SENHOR, diante do véu do santuário.

[[v3-4-7]]

^<<v3-4-7,7>>^ Também daquele sangue porá o sacerdote sobre os chifres do altar do incenso aromático, perante o SENHOR, altar que está na tenda da congregação; e todo o restante do sangue do novilho derramará à base do altar do holocausto, que está à porta da tenda da congregação.

[[v3-4-8]]

^<<v3-4-8,8>>^ Toda a gordura do novilho da expiação tirará dele: a gordura que cobre as entranhas e toda a gordura que está sobre as entranhas,

[[v3-4-9]]

^<<v3-4-9,9>>^ como também os dois rins, a gordura que está sobre eles e junto aos lombos; e o redenho sobre o fígado com os rins, tirá-los-á

[[v3-4-10]]

^<<v3-4-10,10>>^ como se tiram os do novilho do sacrifício pacífico; e o sacerdote os queimará sobre o altar do holocausto.

[[v3-4-11]]

^<<v3-4-11,11>>^ Mas o couro do novilho, toda a sua carne, a cabeça, as pernas, as entranhas e o excremento,

[[v3-4-12]]

^<<v3-4-12,12>>^ a saber, o novilho todo, levá-lo-á fora do arraial, a um lugar limpo, onde se lança a cinza, e o queimará sobre a lenha; será queimado onde se lança a cinza.

[[v3-4-13]]

^<<v3-4-13,13>>^ Mas, se toda a congregação de Israel pecar por ignorância, e isso for oculto aos olhos da coletividade, e se fizerem, contra algum dos mandamentos do SENHOR, aquilo que se não deve fazer, e forem culpados,

[[v3-4-14]]

^<<v3-4-14,14>>^ e o pecado que cometeram for notório, então, a coletividade trará um novilho como oferta pelo pecado e o apresentará diante da tenda da congregação.

[[v3-4-15]]

^<<v3-4-15,15>>^ Os anciãos da congregação porão as mãos sobre a cabeça do novilho perante o SENHOR; e será imolado o novilho perante o SENHOR.

[[v3-4-16]]

^<<v3-4-16,16>>^ Então, o sacerdote ungido trará do sangue do novilho à tenda da congregação;

[[v3-4-17]]

^<<v3-4-17,17>>^ molhará o dedo no sangue e o aspergirá sete vezes perante o SENHOR, diante do véu.

[[v3-4-18]]

^<<v3-4-18,18>>^ E daquele sangue porá sobre os chifres do altar que está perante o SENHOR, na tenda da congregação; e todo o restante do sangue derramará à base do altar do holocausto, que está à porta da tenda da congregação.

[[v3-4-19]]

^<<v3-4-19,19>>^ Tirará do novilho toda a gordura e a queimará sobre o altar;

[[v3-4-20]]

^<<v3-4-20,20>>^ e fará a este novilho como fez ao novilho da oferta pelo pecado; assim lhe fará, e o sacerdote por eles fará expiação, e eles serão perdoados.

[[v3-4-21]]

^<<v3-4-21,21>>^ Depois, levará o novilho fora do arraial e o queimará como queimou o primeiro novilho; é oferta pelo pecado da coletividade.

[[v3-4-22]]

^<<v3-4-22,22>>^ Quando um príncipe pecar, e por ignorância fizer alguma de todas as coisas que o SENHOR, seu Deus, ordenou se não fizessem, e se tornar culpado;

[[v3-4-23]]

^<<v3-4-23,23>>^ ou se o pecado em que ele caiu lhe for notificado, trará por sua oferta um bode sem defeito.

[[v3-4-24]]

^<<v3-4-24,24>>^ E porá a mão sobre a cabeça do bode e o imolará no lugar onde se imola o holocausto, perante o SENHOR; é oferta pelo pecado.

[[v3-4-25]]

^<<v3-4-25,25>>^ Então, o sacerdote, com o dedo, tomará do sangue da oferta pelo pecado e o porá sobre os chifres do altar do holocausto; e todo o restante do sangue derramará à base do altar do holocausto.

[[v3-4-26]]

^<<v3-4-26,26>>^ Toda a gordura da oferta, queimá-la-á sobre o altar, como a gordura do sacrifício pacífico; assim, o sacerdote fará expiação por ele, no tocante ao seu pecado, e este lhe será perdoado.

[[v3-4-27]]

^<<v3-4-27,27>>^ Se qualquer pessoa do povo da terra pecar por ignorância, por fazer alguma das coisas que o SENHOR ordenou se não fizessem, e se tornar culpada;

[[v3-4-28]]

^<<v3-4-28,28>>^ ou se o pecado em que ela caiu lhe for notificado, trará por sua oferta uma cabra sem defeito, pelo pecado que cometeu.

[[v3-4-29]]

^<<v3-4-29,29>>^ E porá a mão sobre a cabeça da oferta pelo pecado e a imolará no lugar do holocausto.

[[v3-4-30]]

^<<v3-4-30,30>>^ Então, o sacerdote, com o dedo, tomará do sangue da oferta e o porá sobre os chifres do altar do holocausto; e todo o restante do sangue derramará à base do altar.

[[v3-4-31]]

^<<v3-4-31,31>>^ Tirará toda a gordura, como se tira a gordura do sacrifício pacífico; o sacerdote a queimará sobre o altar como aroma agradável ao SENHOR; e o sacerdote fará expiação pela pessoa, e lhe será perdoado.

[[v3-4-32]]

^<<v3-4-32,32>>^ Mas, se pela sua oferta trouxer uma cordeira como oferta pelo pecado, fêmea sem defeito a trará.

[[v3-4-33]]

^<<v3-4-33,33>>^ E porá a mão sobre a cabeça da oferta pelo pecado e a imolará por oferta pelo pecado, no lugar onde se imola o holocausto.

[[v3-4-34]]

^<<v3-4-34,34>>^ Então, o sacerdote, com o dedo, tomará do sangue da oferta pelo pecado e o porá sobre os chifres do altar do holocausto; e todo o restante do sangue derramará à base do altar.

[[v3-4-35]]

^<<v3-4-35,35>>^ Tirará toda a gordura, como se tira a gordura do cordeiro do sacrifício pacífico; o sacerdote a queimará sobre o altar, em cima das ofertas queimadas do SENHOR; assim, o sacerdote, por essa pessoa, fará expiação do seu pecado que cometeu, e lhe será perdoado.

'''

xref:003-levitico/003-levitico-003.adoc#v3-3-0[&#60; Capítulo Anterior] | <<v3-4-0,Topo>> | xref:003-levitico/003-levitico-005.adoc#v3-5-0[Próximo Capítulo &#62;]