include::./index.adoc[]

[[v3-18-0]]
=== Levítico, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-18-1]]

^<<v3-18-1,1>>^ Disse mais o SENHOR a Moisés:

[[v3-18-2]]

^<<v3-18-2,2>>^ Fala aos filhos de Israel e dize-lhes: Eu sou o SENHOR, vosso Deus.

[[v3-18-3]]

^<<v3-18-3,3>>^ Não fareis segundo as obras da terra do Egito, em que habitastes, nem fareis segundo as obras da terra de Canaã, para a qual eu vos levo, nem andareis nos seus estatutos.

[[v3-18-4]]

^<<v3-18-4,4>>^ Fareis segundo os meus juízos e os meus estatutos guardareis, para andardes neles. Eu sou o SENHOR, vosso Deus.

[[v3-18-5]]

^<<v3-18-5,5>>^ Portanto, os meus estatutos e os meus juízos guardareis; cumprindo-os, o homem viverá por eles. Eu sou o SENHOR.

[[v3-18-6]]

^<<v3-18-6,6>>^ Nenhum homem se chegará a qualquer parenta da sua carne, para lhe descobrir a nudez. Eu sou o SENHOR.

[[v3-18-7]]

^<<v3-18-7,7>>^ Não descobrirás a nudez de teu pai e de tua mãe; ela é tua mãe; não lhe descobrirás a nudez.

[[v3-18-8]]

^<<v3-18-8,8>>^ Não descobrirás a nudez da mulher de teu pai; é nudez de teu pai.

[[v3-18-9]]

^<<v3-18-9,9>>^ A nudez da tua irmã, filha de teu pai ou filha de tua mãe, nascida em casa ou fora de casa, a sua nudez não descobrirás.

[[v3-18-10]]

^<<v3-18-10,10>>^ A nudez da filha do teu filho ou da filha de tua filha, a sua nudez não descobrirás, porque é tua nudez.

[[v3-18-11]]

^<<v3-18-11,11>>^ Não descobrirás a nudez da filha da mulher de teu pai, gerada de teu pai; ela é tua irmã.

[[v3-18-12]]

^<<v3-18-12,12>>^ A nudez da irmã do teu pai não descobrirás; ela é parenta de teu pai.

[[v3-18-13]]

^<<v3-18-13,13>>^ A nudez da irmã de tua mãe não descobrirás; pois ela é parenta de tua mãe.

[[v3-18-14]]

^<<v3-18-14,14>>^ A nudez do irmão de teu pai não descobrirás; não te chegarás à sua mulher; ela é tua tia.

[[v3-18-15]]

^<<v3-18-15,15>>^ A nudez de tua nora não descobrirás; ela é mulher de teu filho; não lhe descobrirás a nudez.

[[v3-18-16]]

^<<v3-18-16,16>>^ A nudez da mulher de teu irmão não descobrirás; é a nudez de teu irmão.

[[v3-18-17]]

^<<v3-18-17,17>>^ A nudez de uma mulher e de sua filha não descobrirás; não tomarás a filha de seu filho, nem a filha de sua filha, para lhe descobrir a nudez; parentes são; maldade é.

[[v3-18-18]]

^<<v3-18-18,18>>^ E não tomarás com tua mulher outra, de sorte que lhe seja rival, descobrindo a sua nudez com ela durante sua vida.

[[v3-18-19]]

^<<v3-18-19,19>>^ Não te chegarás à mulher, para lhe descobrir a nudez, durante a sua menstruação.

[[v3-18-20]]

^<<v3-18-20,20>>^ Nem te deitarás com a mulher de teu próximo, para te contaminares com ela.

[[v3-18-21]]

^<<v3-18-21,21>>^ E da tua descendência não darás nenhum para dedicar-se a Moloque, nem profanarás o nome de teu Deus. Eu sou o SENHOR.

[[v3-18-22]]

^<<v3-18-22,22>>^ Com homem não te deitarás, como se fosse mulher; é abominação.

[[v3-18-23]]

^<<v3-18-23,23>>^ Nem te deitarás com animal, para te contaminares com ele, nem a mulher se porá perante um animal, para ajuntar-se com ele; é confusão.

[[v3-18-24]]

^<<v3-18-24,24>>^ Com nenhuma destas coisas vos contaminareis, porque com todas estas coisas se contaminaram as nações que eu lanço de diante de vós.

[[v3-18-25]]

^<<v3-18-25,25>>^ E a terra se contaminou; e eu visitei nela a sua iniquidade, e ela vomitou os seus moradores.

[[v3-18-26]]

^<<v3-18-26,26>>^ Porém vós guardareis os meus estatutos e os meus juízos, e nenhuma destas abominações fareis, nem o natural, nem o estrangeiro que peregrina entre vós;

[[v3-18-27]]

^<<v3-18-27,27>>^ porque todas estas abominações fizeram os homens desta terra que nela estavam antes de vós; e a terra se contaminou.

[[v3-18-28]]

^<<v3-18-28,28>>^ Não suceda que a terra vos vomite, havendo-a vós contaminado, como vomitou o povo que nela estava antes de vós.

[[v3-18-29]]

^<<v3-18-29,29>>^ Todo que fizer alguma destas abominações, sim, aqueles que as cometerem serão eliminados do seu povo.

[[v3-18-30]]

^<<v3-18-30,30>>^ Portanto, guardareis a obrigação que tendes para comigo, não praticando nenhum dos costumes abomináveis que se praticaram antes de vós, e não vos contaminareis com eles. Eu sou o SENHOR, vosso Deus.

'''

xref:003-levitico/003-levitico-017.adoc#v3-17-0[&#60; Capítulo Anterior] | <<v3-18-0,Topo>> | xref:003-levitico/003-levitico-019.adoc#v3-19-0[Próximo Capítulo &#62;]