include::./index.adoc[]

[[v3-26-0]]
=== Levítico, 26
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-26-1]]

^<<v3-26-1,1>>^ Não fareis para vós outros ídolos, nem vos levantareis imagem de escultura nem coluna, nem poreis pedra com figuras na vossa terra, para vos inclinardes a ela; porque eu sou o SENHOR, vosso Deus.

[[v3-26-2]]

^<<v3-26-2,2>>^ Guardareis os meus sábados e reverenciareis o meu santuário. Eu sou o SENHOR.

[[v3-26-3]]

^<<v3-26-3,3>>^ Se andardes nos meus estatutos, guardardes os meus mandamentos e os cumprirdes,

[[v3-26-4]]

^<<v3-26-4,4>>^ então, eu vos darei as vossas chuvas a seu tempo; e a terra dará a sua messe, e a árvore do campo, o seu fruto.

[[v3-26-5]]

^<<v3-26-5,5>>^ A debulha se estenderá até à vindima, e a vindima, até à sementeira; comereis o vosso pão a fartar e habitareis seguros na vossa terra.

[[v3-26-6]]

^<<v3-26-6,6>>^ Estabelecerei paz na terra; deitar-vos-eis, e não haverá quem vos espante; farei cessar os animais nocivos da terra, e pela vossa terra não passará espada.

[[v3-26-7]]

^<<v3-26-7,7>>^ Perseguireis os vossos inimigos, e cairão à espada diante de vós.

[[v3-26-8]]

^<<v3-26-8,8>>^ Cinco de vós perseguirão a cem, e cem dentre vós perseguirão a dez mil; e os vossos inimigos cairão à espada diante de vós.

[[v3-26-9]]

^<<v3-26-9,9>>^ Para vós outros olharei, e vos farei fecundos, e vos multiplicarei, e confirmarei a minha aliança convosco.

[[v3-26-10]]

^<<v3-26-10,10>>^ Comereis o velho da colheita anterior e, para dar lugar ao novo, tirareis fora o velho.

[[v3-26-11]]

^<<v3-26-11,11>>^ Porei o meu tabernáculo no meio de vós, e a minha alma não vos aborrecerá.

[[v3-26-12]]

^<<v3-26-12,12>>^ Andarei entre vós e serei o vosso Deus, e vós sereis o meu povo.

[[v3-26-13]]

^<<v3-26-13,13>>^ Eu sou o SENHOR, vosso Deus, que vos tirei da terra do Egito, para que não fôsseis seus escravos; quebrei os timões do vosso jugo e vos fiz andar eretos.

[[v3-26-14]]

^<<v3-26-14,14>>^ Mas, se me não ouvirdes e não cumprirdes todos estes mandamentos;

[[v3-26-15]]

^<<v3-26-15,15>>^ se rejeitardes os meus estatutos, e a vossa alma se aborrecer dos meus juízos, a ponto de não cumprir todos os meus mandamentos, e violardes a minha aliança,

[[v3-26-16]]

^<<v3-26-16,16>>^ então, eu vos farei isto: porei sobre vós terror, a tísica e a febre ardente, que fazem desaparecer o lustre dos olhos e definhar a vida; e semeareis debalde a vossa semente, porque os vossos inimigos a comerão.

[[v3-26-17]]

^<<v3-26-17,17>>^ Voltar-me-ei contra vós outros, e sereis feridos diante de vossos inimigos; os que vos aborrecerem assenhorear-se-ão de vós e fugireis, sem ninguém vos perseguir.

[[v3-26-18]]

^<<v3-26-18,18>>^ Se ainda assim com isto não me ouvirdes, tornarei a castigar-vos sete vezes mais por causa dos vossos pecados.

[[v3-26-19]]

^<<v3-26-19,19>>^ Quebrantarei a soberba da vossa força e vos farei que os céus sejam como ferro e a vossa terra, como bronze.

[[v3-26-20]]

^<<v3-26-20,20>>^ Debalde se gastará a vossa força; a vossa terra não dará a sua messe, e as árvores da terra não darão o seu fruto.

[[v3-26-21]]

^<<v3-26-21,21>>^ E, se andardes contrariamente para comigo e não me quiserdes ouvir, trarei sobre vós pragas sete vezes mais, segundo os vossos pecados.

[[v3-26-22]]

^<<v3-26-22,22>>^ Porque enviarei para o meio de vós as feras do campo, as quais vos desfilharão, e acabarão com o vosso gado, e vos reduzirão a poucos; e os vossos caminhos se tornarão desertos.

[[v3-26-23]]

^<<v3-26-23,23>>^ Se ainda com isto não vos corrigirdes para volverdes a mim, porém andardes contrariamente comigo,

[[v3-26-24]]

^<<v3-26-24,24>>^ eu também serei contrário a vós outros e eu mesmo vos ferirei sete vezes mais por causa dos vossos pecados.

[[v3-26-25]]

^<<v3-26-25,25>>^ Trarei sobre vós a espada vingadora da minha aliança; e, então, quando vos ajuntardes nas vossas cidades, enviarei a peste para o meio de vós, e sereis entregues na mão do inimigo.

[[v3-26-26]]

^<<v3-26-26,26>>^ Quando eu vos tirar o sustento do pão, dez mulheres cozerão o vosso pão num só forno e vo-lo entregarão por peso; comereis, porém não vos fartareis.

[[v3-26-27]]

^<<v3-26-27,27>>^ Se ainda com isto me não ouvirdes e andardes contrariamente comigo,

[[v3-26-28]]

^<<v3-26-28,28>>^ eu também, com furor, serei contrário a vós outros e vos castigarei sete vezes mais por causa dos vossos pecados.

[[v3-26-29]]

^<<v3-26-29,29>>^ Comereis a carne de vossos filhos e de vossas filhas.

[[v3-26-30]]

^<<v3-26-30,30>>^ Destruirei os vossos altos, e desfarei as vossas imagens do sol, e lançarei o vosso cadáver sobre o cadáver dos vossos deuses; a minha alma se aborrecerá de vós.

[[v3-26-31]]

^<<v3-26-31,31>>^ Reduzirei as vossas cidades a deserto, e assolarei os vossos santuários, e não aspirarei o vosso aroma agradável.

[[v3-26-32]]

^<<v3-26-32,32>>^ Assolarei a terra, e se espantarão disso os vossos inimigos que nela morarem.

[[v3-26-33]]

^<<v3-26-33,33>>^ Espalhar-vos-ei por entre as nações e desembainharei a espada atrás de vós; a vossa terra será assolada, e as vossas cidades serão desertas.

[[v3-26-34]]

^<<v3-26-34,34>>^ Então, a terra folgará nos seus sábados, todos os dias da sua assolação, e vós estareis na terra dos vossos inimigos; nesse tempo, a terra descansará e folgará nos seus sábados.

[[v3-26-35]]

^<<v3-26-35,35>>^ Todos os dias da assolação descansará, porque não descansou nos vossos sábados, quando habitáveis nela.

[[v3-26-36]]

^<<v3-26-36,36>>^ Quanto aos que de vós ficarem, eu lhes meterei no coração tal ansiedade, nas terras dos seus inimigos, que o ruído de uma folha movida os perseguirá; fugirão como quem foge da espada; e cairão sem ninguém os perseguir.

[[v3-26-37]]

^<<v3-26-37,37>>^ Cairão uns sobre os outros como diante da espada, sem ninguém os perseguir; não podereis levantar-vos diante dos vossos inimigos.

[[v3-26-38]]

^<<v3-26-38,38>>^ Perecereis entre as nações, e a terra dos vossos inimigos vos consumirá.

[[v3-26-39]]

^<<v3-26-39,39>>^ Aqueles que dentre vós ficarem serão consumidos pela sua iniquidade nas terras dos vossos inimigos e pela iniquidade de seus pais com eles serão consumidos.

[[v3-26-40]]

^<<v3-26-40,40>>^ Mas, se confessarem a sua iniquidade e a iniquidade de seus pais, na infidelidade que cometeram contra mim, como também confessarem que andaram contrariamente para comigo,

[[v3-26-41]]

^<<v3-26-41,41>>^ pelo que também fui contrário a eles e os fiz entrar na terra dos seus inimigos; se o seu coração incircunciso se humilhar, e tomarem eles por bem o castigo da sua iniquidade,

[[v3-26-42]]

^<<v3-26-42,42>>^ então, me lembrarei da minha aliança com Jacó, e também da minha aliança com Isaque, e também da minha aliança com Abraão, e da terra me lembrarei.

[[v3-26-43]]

^<<v3-26-43,43>>^ Mas a terra na sua assolação, deixada por eles, folgará nos seus sábados; e tomarão eles por bem o castigo da sua iniquidade, visto que rejeitaram os meus juízos e a sua alma se aborreceu dos meus estatutos.

[[v3-26-44]]

^<<v3-26-44,44>>^ Mesmo assim, estando eles na terra dos seus inimigos, não os rejeitarei, nem me aborrecerei deles, para consumi-los e invalidar a minha aliança com eles, porque eu sou o SENHOR, seu Deus.

[[v3-26-45]]

^<<v3-26-45,45>>^ Antes, por amor deles, me lembrarei da aliança com os seus antepassados, que tirei da terra do Egito à vista das nações, para lhes ser por Deus. Eu sou o SENHOR.

[[v3-26-46]]

^<<v3-26-46,46>>^ São estes os estatutos, juízos e leis que deu o SENHOR entre si e os filhos de Israel, no monte Sinai, pela mão de Moisés.

'''

xref:003-levitico/003-levitico-025.adoc#v3-25-0[&#60; Capítulo Anterior] | <<v3-26-0,Topo>> | xref:003-levitico/003-levitico-027.adoc#v3-27-0[Próximo Capítulo &#62;]