include::./index.adoc[]

[[v3-17-0]]
=== Levítico, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-17-1]]

^<<v3-17-1,1>>^ Disse o SENHOR a Moisés:

[[v3-17-2]]

^<<v3-17-2,2>>^ Fala a Arão, e a seus filhos, e a todos os filhos de Israel e dize-lhes: Isto é o que o SENHOR ordenou, dizendo:

[[v3-17-3]]

^<<v3-17-3,3>>^ Qualquer homem da casa de Israel que imolar boi, ou cordeiro, ou cabra, no arraial ou fora dele,

[[v3-17-4]]

^<<v3-17-4,4>>^ e os não trouxer à porta da tenda da congregação, como oferta ao SENHOR diante do seu tabernáculo, a tal homem será imputada a culpa do sangue; derramou sangue, pelo que esse homem será eliminado do seu povo;

[[v3-17-5]]

^<<v3-17-5,5>>^ para que os filhos de Israel, trazendo os seus sacrifícios, que imolam em campo aberto, os apresentem ao SENHOR, à porta da tenda da congregação, ao sacerdote, e os ofereçam por sacrifícios pacíficos ao SENHOR.

[[v3-17-6]]

^<<v3-17-6,6>>^ O sacerdote aspergirá o sangue sobre o altar do SENHOR, à porta da tenda da congregação, e queimará a gordura de aroma agradável ao SENHOR.

[[v3-17-7]]

^<<v3-17-7,7>>^ Nunca mais oferecerão os seus sacrifícios aos demônios, com os quais eles se prostituem; isso lhes será por estatuto perpétuo nas suas gerações.

[[v3-17-8]]

^<<v3-17-8,8>>^ Dize-lhes, pois: Qualquer homem da casa de Israel ou dos estrangeiros que peregrinam entre vós que oferecer holocausto ou sacrifício

[[v3-17-9]]

^<<v3-17-9,9>>^ e não o trouxer à porta da tenda da congregação, para oferecê-lo ao SENHOR, esse homem será eliminado do seu povo.

[[v3-17-10]]

^<<v3-17-10,10>>^ Qualquer homem da casa de Israel ou dos estrangeiros que peregrinam entre vós que comer algum sangue, contra ele me voltarei e o eliminarei do seu povo.

[[v3-17-11]]

^<<v3-17-11,11>>^ Porque a vida da carne está no sangue. Eu vo-lo tenho dado sobre o altar, para fazer expiação pela vossa alma, porquanto é o sangue que fará expiação em virtude da vida.

[[v3-17-12]]

^<<v3-17-12,12>>^ Portanto, tenho dito aos filhos de Israel: nenhuma alma de entre vós comerá sangue, nem o estrangeiro que peregrina entre vós o comerá.

[[v3-17-13]]

^<<v3-17-13,13>>^ Qualquer homem dos filhos de Israel ou dos estrangeiros que peregrinam entre vós que caçar animal ou ave que se come derramará o seu sangue e o cobrirá com pó.

[[v3-17-14]]

^<<v3-17-14,14>>^ Portanto, a vida de toda carne é o seu sangue; por isso, tenho dito aos filhos de Israel: não comereis o sangue de nenhuma carne, porque a vida de toda carne é o seu sangue; qualquer que o comer será eliminado.

[[v3-17-15]]

^<<v3-17-15,15>>^ Todo homem, quer natural, quer estrangeiro, que comer o que morre por si ou dilacerado lavará as suas vestes, banhar-se-á em água e será imundo até à tarde; depois, será limpo.

[[v3-17-16]]

^<<v3-17-16,16>>^ Mas, se não as lavar, nem banhar o corpo, levará sobre si a sua iniquidade.

'''

xref:003-levitico/003-levitico-016.adoc#v3-16-0[&#60; Capítulo Anterior] | <<v3-17-0,Topo>> | xref:003-levitico/003-levitico-018.adoc#v3-18-0[Próximo Capítulo &#62;]