include::./index.adoc[]

[[v3-11-0]]
=== Levítico, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-11-1]]

^<<v3-11-1,1>>^ Falou o SENHOR a Moisés e a Arão, dizendo-lhes:

[[v3-11-2]]

^<<v3-11-2,2>>^ Dizei aos filhos de Israel: São estes os animais que comereis de todos os quadrúpedes que há sobre a terra:

[[v3-11-3]]

^<<v3-11-3,3>>^ todo o que tem unhas fendidas, e o casco se divide em dois, e rumina, entre os animais, esse comereis.

[[v3-11-4]]

^<<v3-11-4,4>>^ Destes, porém, não comereis: dos que ruminam ou dos que têm unhas fendidas: o camelo, que rumina, mas não tem unhas fendidas; este vos será imundo;

[[v3-11-5]]

^<<v3-11-5,5>>^ o arganaz, porque rumina, mas não tem as unhas fendidas; este vos será imundo;

[[v3-11-6]]

^<<v3-11-6,6>>^ a lebre, porque rumina, mas não tem as unhas fendidas; esta vos será imunda.

[[v3-11-7]]

^<<v3-11-7,7>>^ Também o porco, porque tem unhas fendidas e o casco dividido, mas não rumina; este vos será imundo;

[[v3-11-8]]

^<<v3-11-8,8>>^ da sua carne não comereis, nem tocareis no seu cadáver. Estes vos serão imundos.

[[v3-11-9]]

^<<v3-11-9,9>>^ De todos os animais que há nas águas comereis os seguintes: todo o que tem barbatanas e escamas, nos mares e nos rios; esses comereis.

[[v3-11-10]]

^<<v3-11-10,10>>^ Porém todo o que não tem barbatanas nem escamas, nos mares e nos rios, todos os que enxameiam as águas e todo ser vivente que há nas águas, estes serão para vós outros abominação.

[[v3-11-11]]

^<<v3-11-11,11>>^ Ser-vos-ão, pois, por abominação; da sua carne não comereis e abominareis o seu cadáver.

[[v3-11-12]]

^<<v3-11-12,12>>^ Todo o que nas águas não tem barbatanas ou escamas será para vós outros abominação.

[[v3-11-13]]

^<<v3-11-13,13>>^ Das aves, estas abominareis; não se comerão, serão abominação: a águia, o quebrantosso e a águia marinha;

[[v3-11-14]]

^<<v3-11-14,14>>^ o milhano e o falcão, segundo a sua espécie,

[[v3-11-15]]

^<<v3-11-15,15>>^ todo corvo, segundo a sua espécie,

[[v3-11-16]]

^<<v3-11-16,16>>^ o avestruz, a coruja, a gaivota, o gavião, segundo a sua espécie,

[[v3-11-17]]

^<<v3-11-17,17>>^ o mocho, o corvo marinho, a íbis,

[[v3-11-18]]

^<<v3-11-18,18>>^ a gralha, o pelicano, o abutre,

[[v3-11-19]]

^<<v3-11-19,19>>^ a cegonha, a garça, segundo a sua espécie, a poupa e o morcego.

[[v3-11-20]]

^<<v3-11-20,20>>^ Todo inseto que voa, que anda sobre quatro pés será para vós outros abominação.

[[v3-11-21]]

^<<v3-11-21,21>>^ Mas de todo inseto que voa, que anda sobre quatro pés, cujas pernas traseiras são mais compridas, para saltar com elas sobre a terra, estes comereis.

[[v3-11-22]]

^<<v3-11-22,22>>^ Deles, comereis estes: a locusta, segundo a sua espécie, o gafanhoto devorador, segundo a sua espécie, o grilo, segundo a sua espécie, e o gafanhoto, segundo a sua espécie.

[[v3-11-23]]

^<<v3-11-23,23>>^ Mas todos os outros insetos que voam, que têm quatro pés serão para vós outros abominação.

[[v3-11-24]]

^<<v3-11-24,24>>^ E por estes vos tornareis imundos; qualquer que tocar o seu cadáver imundo será até à tarde.

[[v3-11-25]]

^<<v3-11-25,25>>^ Qualquer que levar o seu cadáver lavará as suas vestes e será imundo até à tarde.

[[v3-11-26]]

^<<v3-11-26,26>>^ Todo animal que tem unhas fendidas, mas o casco não dividido em dois e não rumina vos será por imundo; qualquer que tocar neles será imundo.

[[v3-11-27]]

^<<v3-11-27,27>>^ Todo animal quadrúpede que anda na planta dos pés vos será por imundo; qualquer que tocar o seu cadáver será imundo até à tarde.

[[v3-11-28]]

^<<v3-11-28,28>>^ E o que levar o seu cadáver lavará as suas vestes e será imundo até à tarde; eles vos serão por imundos.

[[v3-11-29]]

^<<v3-11-29,29>>^ Estes vos serão imundos entre o enxame de criaturas que povoam a terra: a doninha, o rato, o lagarto, segundo a sua espécie,

[[v3-11-30]]

^<<v3-11-30,30>>^ o geco, o crocodilo da terra, a lagartixa, o lagarto da areia e o camaleão;

[[v3-11-31]]

^<<v3-11-31,31>>^ estes vos serão por imundos entre todo o enxame de criaturas; qualquer que os tocar, estando eles mortos, será imundo até à tarde.

[[v3-11-32]]

^<<v3-11-32,32>>^ E tudo aquilo sobre que cair qualquer deles, estando eles mortos, será imundo, seja vaso de madeira, ou veste, ou pele, ou pano de saco, ou qualquer instrumento com que se faz alguma obra, será metido em água e será imundo até à tarde; então, será limpo.

[[v3-11-33]]

^<<v3-11-33,33>>^ E todo vaso de barro, dentro do qual cair alguma coisa deles, tudo o que houver nele será imundo; o vaso quebrareis.

[[v3-11-34]]

^<<v3-11-34,34>>^ Todo alimento que se come, preparado com água, será imundo; e todo líquido que se bebe, em todo vaso, será imundo.

[[v3-11-35]]

^<<v3-11-35,35>>^ E aquilo sobre o que cair alguma coisa do seu corpo morto será imundo; se for um forno ou um fogareiro de barro, serão quebrados; imundos são; portanto, vos serão por imundos.

[[v3-11-36]]

^<<v3-11-36,36>>^ Porém a fonte ou cisterna, em que se recolhem águas, será limpa; mas quem tocar no cadáver desses animais será imundo.

[[v3-11-37]]

^<<v3-11-37,37>>^ Se do seu cadáver cair alguma coisa sobre alguma semente de semear, esta será limpa;

[[v3-11-38]]

^<<v3-11-38,38>>^ mas, se alguém deitar água sobre a semente, e, se do cadáver cair alguma coisa sobre ela, vos será imunda.

[[v3-11-39]]

^<<v3-11-39,39>>^ Se morrer algum dos animais de que vos é lícito comer, quem tocar no seu cadáver será imundo até à tarde;

[[v3-11-40]]

^<<v3-11-40,40>>^ quem do seu cadáver comer lavará as suas vestes e será imundo até à tarde; e quem levar o seu corpo morto lavará as suas vestes e será imundo até à tarde.

[[v3-11-41]]

^<<v3-11-41,41>>^ Também todo enxame de criaturas que povoam a terra será abominação; não se comerá.

[[v3-11-42]]

^<<v3-11-42,42>>^ Tudo o que anda sobre o ventre, e tudo o que anda sobre quatro pés ou que tem muitos pés, entre todo enxame de criaturas que povoam a terra, não comereis, porquanto são abominação.

[[v3-11-43]]

^<<v3-11-43,43>>^ Não vos façais abomináveis por nenhum enxame de criaturas, nem por elas vos contaminareis, para não serdes imundos.

[[v3-11-44]]

^<<v3-11-44,44>>^ Eu sou o SENHOR, vosso Deus; portanto, vós vos consagrareis e sereis santos, porque eu sou santo; e não vos contaminareis por nenhum enxame de criaturas que se arrastam sobre a terra.

[[v3-11-45]]

^<<v3-11-45,45>>^ Eu sou o SENHOR, que vos faço subir da terra do Egito, para que eu seja vosso Deus; portanto, vós sereis santos, porque eu sou santo.

[[v3-11-46]]

^<<v3-11-46,46>>^ Esta é a lei dos animais, e das aves, e de toda alma vivente que se move nas águas, e de toda criatura que povoa a terra,

[[v3-11-47]]

^<<v3-11-47,47>>^ para fazer diferença entre o imundo e o limpo e entre os animais que se podem comer e os animais que se não podem comer.

'''

xref:003-levitico/003-levitico-010.adoc#v3-10-0[&#60; Capítulo Anterior] | <<v3-11-0,Topo>> | xref:003-levitico/003-levitico-012.adoc#v3-12-0[Próximo Capítulo &#62;]