include::./index.adoc[]

[[v3-2-0]]
=== Levítico, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-2-1]]

^<<v3-2-1,1>>^ Quando alguma pessoa fizer oferta de manjares ao SENHOR, a sua oferta será de flor de farinha; nela, deitará azeite e, sobre ela, porá incenso.

[[v3-2-2]]

^<<v3-2-2,2>>^ Levá-la-á aos filhos de Arão, os sacerdotes, um dos quais tomará dela um punhado da flor de farinha e do seu azeite com todo o seu incenso e os queimará como porção memorial sobre o altar; é oferta queimada, de aroma agradável ao SENHOR.

[[v3-2-3]]

^<<v3-2-3,3>>^ O que ficar da oferta de manjares será de Arão e de seus filhos; é coisa santíssima das ofertas queimadas ao SENHOR.

[[v3-2-4]]

^<<v3-2-4,4>>^ Quando trouxeres oferta de manjares, cozida no forno, será de bolos asmos de flor de farinha amassados com azeite e obreias asmas untadas com azeite.

[[v3-2-5]]

^<<v3-2-5,5>>^ Se a tua oferta for de manjares cozida na assadeira, será de flor de farinha sem fermento amassada com azeite.

[[v3-2-6]]

^<<v3-2-6,6>>^ Em pedaços a partirás e, sobre ela, deitarás azeite; é oferta de manjares.

[[v3-2-7]]

^<<v3-2-7,7>>^ Se a tua oferta for de manjares de frigideira, far-se-á de flor de farinha com azeite.

[[v3-2-8]]

^<<v3-2-8,8>>^ E a oferta de manjares, que daquilo se fará, trarás ao SENHOR; será apresentada ao sacerdote, o qual a levará ao altar.

[[v3-2-9]]

^<<v3-2-9,9>>^ Da oferta de manjares tomará o sacerdote a porção memorial e a queimará sobre o altar; é oferta queimada, de aroma agradável ao SENHOR.

[[v3-2-10]]

^<<v3-2-10,10>>^ O que ficar da oferta de manjares será de Arão e de seus filhos; é coisa santíssima das ofertas queimadas ao SENHOR.

[[v3-2-11]]

^<<v3-2-11,11>>^ Nenhuma oferta de manjares, que fizerdes ao SENHOR, se fará com fermento; porque de nenhum fermento e de mel nenhum queimareis por oferta ao SENHOR.

[[v3-2-12]]

^<<v3-2-12,12>>^ Deles, trareis ao SENHOR por oferta das primícias; todavia, não se porão sobre o altar como aroma agradável.

[[v3-2-13]]

^<<v3-2-13,13>>^ Toda oferta dos teus manjares temperarás com sal; à tua oferta de manjares não deixarás faltar o sal da aliança do teu Deus; em todas as tuas ofertas aplicarás sal.

[[v3-2-14]]

^<<v3-2-14,14>>^ Se trouxeres ao SENHOR oferta de manjares das primícias, farás a oferta de manjares das tuas primícias de espigas verdes, tostadas ao fogo, isto é, os grãos esmagados de espigas verdes.

[[v3-2-15]]

^<<v3-2-15,15>>^ Deitarás azeite sobre ela e, por cima, lhe porás incenso; é oferta de manjares.

[[v3-2-16]]

^<<v3-2-16,16>>^ Assim, o sacerdote queimará a porção memorial dos grãos de espigas esmagados e do azeite, com todo o incenso; é oferta queimada ao SENHOR.

'''

xref:003-levitico/003-levitico-001.adoc#v3-1-0[&#60; Capítulo Anterior] | <<v3-2-0,Topo>> | xref:003-levitico/003-levitico-003.adoc#v3-3-0[Próximo Capítulo &#62;]