include::./index.adoc[]

[[v3-22-0]]
=== Levítico, 22
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-22-1]]

^<<v3-22-1,1>>^ Disse o SENHOR a Moisés:

[[v3-22-2]]

^<<v3-22-2,2>>^ Dize a Arão e aos seus filhos que se abstenham das coisas sagradas, dedicadas a mim pelos filhos de Israel, para que não profanem o meu santo nome. Eu sou o SENHOR.

[[v3-22-3]]

^<<v3-22-3,3>>^ Dize-lhes: Todo homem, que entre as vossas gerações, de toda a vossa descendência, se chegar às coisas sagradas que os filhos de Israel dedicam ao SENHOR, tendo sobre si a sua imundícia, aquela alma será eliminada de diante de mim. Eu sou o SENHOR.

[[v3-22-4]]

^<<v3-22-4,4>>^ Ninguém da descendência de Arão que for leproso ou tiver fluxo comerá das coisas sagradas, até que seja limpo; como também o que tocar alguma coisa imunda por causa de um morto ou aquele com quem se der a emissão do sêmen;

[[v3-22-5]]

^<<v3-22-5,5>>^ ou qualquer que tocar algum réptil, com o que se faz imundo, ou a algum homem, com o que se faz imundo, seja qual for a sua imundícia.

[[v3-22-6]]

^<<v3-22-6,6>>^ O homem que o tocar será imundo até à tarde e não comerá das coisas sagradas sem primeiro banhar o seu corpo em água.

[[v3-22-7]]

^<<v3-22-7,7>>^ Posto o sol, então, será limpo e, depois, comerá das coisas sagradas, porque isto é o seu pão.

[[v3-22-8]]

^<<v3-22-8,8>>^ Do animal que morre por si mesmo ou é dilacerado não comerá, para, com isso, não contaminar-se. Eu sou o SENHOR.

[[v3-22-9]]

^<<v3-22-9,9>>^ Guardarão, pois, a obrigação que têm para comigo, para que, por isso, não levem sobre si pecado e morram, havendo-o profanado. Eu sou o SENHOR, que os santifico.

[[v3-22-10]]

^<<v3-22-10,10>>^ Nenhum estrangeiro comerá das coisas sagradas; o hóspede do sacerdote nem o seu jornaleiro comerão das coisas sagradas.

[[v3-22-11]]

^<<v3-22-11,11>>^ Mas, se o sacerdote comprar algum escravo com o seu dinheiro, este comerá delas; os que nascerem na sua casa, estes comerão do seu pão.

[[v3-22-12]]

^<<v3-22-12,12>>^ Quando a filha do sacerdote se casar com estrangeiro, ela não comerá da oferta das coisas sagradas.

[[v3-22-13]]

^<<v3-22-13,13>>^ Mas, se a filha do sacerdote for viúva ou repudiada, e não tiver filhos, e se houver tornado à casa de seu pai, como na sua mocidade, do pão de seu pai comerá; mas nenhum estrangeiro comerá dele.

[[v3-22-14]]

^<<v3-22-14,14>>^ Se alguém, por ignorância, comer a coisa sagrada, ajuntar-se-lhe-á a sua quinta parte e a dará ao sacerdote com a coisa sagrada.

[[v3-22-15]]

^<<v3-22-15,15>>^ Não profanarão as coisas sagradas que os filhos de Israel oferecem ao SENHOR,

[[v3-22-16]]

^<<v3-22-16,16>>^ pois assim os fariam levar sobre si a culpa da iniquidade, comendo as coisas sagradas; porque eu sou o SENHOR, que os santifico.

[[v3-22-17]]

^<<v3-22-17,17>>^ Disse mais o SENHOR a Moisés:

[[v3-22-18]]

^<<v3-22-18,18>>^ Fala a Arão, e a seus filhos, e a todos os filhos de Israel e dize-lhes: Qualquer que, da casa de Israel ou dos estrangeiros em Israel, apresentar a sua oferta, quer em cumprimento de seus votos ou como ofertas voluntárias, que apresentar ao SENHOR em holocausto,

[[v3-22-19]]

^<<v3-22-19,19>>^ para que seja aceitável, oferecerá macho sem defeito, ou do gado, ou do rebanho de ovelhas, ou de cabras.

[[v3-22-20]]

^<<v3-22-20,20>>^ Porém todo o que tiver defeito, esse não oferecereis; porque não seria aceito a vosso favor.

[[v3-22-21]]

^<<v3-22-21,21>>^ Quando alguém oferecer sacrifício pacífico ao SENHOR, quer em cumprimento de voto ou como oferta voluntária, do gado ou do rebanho, o animal deve ser sem defeito para ser aceitável; nele, não haverá defeito nenhum.

[[v3-22-22]]

^<<v3-22-22,22>>^ O cego, ou aleijado, ou mutilado, ou ulceroso, ou sarnoso, ou cheio de impigens, não os oferecereis ao SENHOR e deles não poreis oferta queimada ao SENHOR sobre o altar.

[[v3-22-23]]

^<<v3-22-23,23>>^ Porém novilho ou cordeiro desproporcionados poderás oferecer por oferta voluntária, mas, por voto, não será aceito.

[[v3-22-24]]

^<<v3-22-24,24>>^ Não oferecereis ao SENHOR animal que tiver os testículos machucados, ou moídos, ou arrancados, ou cortados; nem fareis isso na vossa terra.

[[v3-22-25]]

^<<v3-22-25,25>>^ Também da mão do estrangeiro nenhum desses animais oferecereis como pão do vosso Deus, porque são corrompidos pelo defeito que há neles; não serão aceitos a vosso favor.

[[v3-22-26]]

^<<v3-22-26,26>>^ Disse mais o SENHOR a Moisés:

[[v3-22-27]]

^<<v3-22-27,27>>^ Quando nascer o boi, ou cordeiro, ou cabra, sete dias estará com a mãe; do oitavo dia em diante, será aceito por oferta queimada ao SENHOR.

[[v3-22-28]]

^<<v3-22-28,28>>^ Ou seja vaca, ou seja ovelha, não imolarás a ela e seu filho, ambos no mesmo dia.

[[v3-22-29]]

^<<v3-22-29,29>>^ Quando oferecerdes sacrifício de louvores ao SENHOR, fá-lo-eis para que sejais aceitos.

[[v3-22-30]]

^<<v3-22-30,30>>^ No mesmo dia, será comido; e, dele, nada deixareis ficar até pela manhã. Eu sou o SENHOR.

[[v3-22-31]]

^<<v3-22-31,31>>^ Pelo que guardareis os meus mandamentos e os cumprireis. Eu sou o SENHOR.

[[v3-22-32]]

^<<v3-22-32,32>>^ Não profanareis o meu santo nome, mas serei santificado no meio dos filhos de Israel. Eu sou o SENHOR, que vos santifico,

[[v3-22-33]]

^<<v3-22-33,33>>^ que vos tirei da terra do Egito, para ser o vosso Deus. Eu sou o SENHOR.

'''

xref:003-levitico/003-levitico-021.adoc#v3-21-0[&#60; Capítulo Anterior] | <<v3-22-0,Topo>> | xref:003-levitico/003-levitico-023.adoc#v3-23-0[Próximo Capítulo &#62;]