include::./index.adoc[]

[[v3-3-0]]
=== Levítico, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-3-1]]

^<<v3-3-1,1>>^ Se a oferta de alguém for sacrifício pacífico, se a fizer de gado, seja macho ou fêmea, oferecê-la-á sem defeito diante do SENHOR.

[[v3-3-2]]

^<<v3-3-2,2>>^ E porá a mão sobre a cabeça da sua oferta e a imolará diante da porta da tenda da congregação; e os filhos de Arão, os sacerdotes, aspergirão o sangue sobre o altar, ao redor.

[[v3-3-3]]

^<<v3-3-3,3>>^ Do sacrifício pacífico fará oferta queimada ao SENHOR: a gordura que cobre as entranhas e toda a gordura que está sobre as entranhas,

[[v3-3-4]]

^<<v3-3-4,4>>^ como também os dois rins, a gordura que está sobre eles e junto aos lombos; e o redenho sobre o fígado com os rins, tirá-los-á.

[[v3-3-5]]

^<<v3-3-5,5>>^ E os filhos de Arão queimarão tudo isso sobre o altar, em cima do holocausto, que estará sobre a lenha no fogo; é oferta queimada, de aroma agradável ao SENHOR.

[[v3-3-6]]

^<<v3-3-6,6>>^ Se a sua oferta por sacrifício pacífico ao SENHOR for de gado miúdo, seja macho ou fêmea, sem defeito a oferecerá.

[[v3-3-7]]

^<<v3-3-7,7>>^ Se trouxer um cordeiro por sua oferta, oferecê-lo-á perante o SENHOR.

[[v3-3-8]]

^<<v3-3-8,8>>^ E porá a mão sobre a cabeça da sua oferta e a imolará diante da tenda da congregação; e os filhos de Arão aspergirão o sangue sobre o altar, em redor.

[[v3-3-9]]

^<<v3-3-9,9>>^ Então, do sacrifício pacífico trará ao SENHOR por oferta queimada a sua gordura: a cauda toda, a qual tirará rente ao espinhaço, e a gordura que cobre as entranhas, e toda a gordura que está sobre as entranhas,

[[v3-3-10]]

^<<v3-3-10,10>>^ como também os dois rins, a gordura que está sobre eles e junto aos lombos; e o redenho sobre o fígado com os rins, tirá-los-á.

[[v3-3-11]]

^<<v3-3-11,11>>^ E o sacerdote queimará tudo isso sobre o altar; é manjar da oferta queimada ao SENHOR.

[[v3-3-12]]

^<<v3-3-12,12>>^ Mas, se a sua oferta for uma cabra, perante o SENHOR a trará.

[[v3-3-13]]

^<<v3-3-13,13>>^ E porá a mão sobre a sua cabeça e a imolará diante da tenda da congregação; e os filhos de Arão aspergirão o sangue sobre o altar, em redor.

[[v3-3-14]]

^<<v3-3-14,14>>^ Depois, trará dela a sua oferta, por oferta queimada ao SENHOR: a gordura que cobre as entranhas e toda a gordura que está sobre as entranhas,

[[v3-3-15]]

^<<v3-3-15,15>>^ como também os dois rins, a gordura que está sobre eles e junto aos lombos; e o redenho sobre o fígado com os rins, tirá-los-á.

[[v3-3-16]]

^<<v3-3-16,16>>^ E o sacerdote queimará tudo isso sobre o altar; é manjar da oferta queimada, de aroma agradável. Toda a gordura será do SENHOR.

[[v3-3-17]]

^<<v3-3-17,17>>^ Estatuto perpétuo será durante as vossas gerações, em todas as vossas moradas; gordura nenhuma nem sangue jamais comereis.

'''

xref:003-levitico/003-levitico-002.adoc#v3-2-0[&#60; Capítulo Anterior] | <<v3-3-0,Topo>> | xref:003-levitico/003-levitico-004.adoc#v3-4-0[Próximo Capítulo &#62;]