include::./index.adoc[]

[[v3-1-0]]
=== Levítico, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-1-1]]

^<<v3-1-1,1>>^ Chamou o SENHOR a Moisés e, da tenda da congregação, lhe disse:

[[v3-1-2]]

^<<v3-1-2,2>>^ Fala aos filhos de Israel e dize-lhes: Quando algum de vós trouxer oferta ao SENHOR, trareis a vossa oferta de gado, de rebanho ou de gado miúdo.

[[v3-1-3]]

^<<v3-1-3,3>>^ Se a sua oferta for holocausto de gado, trará macho sem defeito; à porta da tenda da congregação o trará, para que o homem seja aceito perante o SENHOR.

[[v3-1-4]]

^<<v3-1-4,4>>^ E porá a mão sobre a cabeça do holocausto, para que seja aceito a favor dele, para a sua expiação.

[[v3-1-5]]

^<<v3-1-5,5>>^ Depois, imolará o novilho perante o SENHOR; e os filhos de Arão, os sacerdotes, apresentarão o sangue e o aspergirão ao redor sobre o altar que está diante da porta da tenda da congregação.

[[v3-1-6]]

^<<v3-1-6,6>>^ Então, ele esfolará o holocausto e o cortará em seus pedaços.

[[v3-1-7]]

^<<v3-1-7,7>>^ E os filhos de Arão, o sacerdote, porão fogo sobre o altar e porão em ordem lenha sobre o fogo.

[[v3-1-8]]

^<<v3-1-8,8>>^ Também os filhos de Arão, os sacerdotes, colocarão em ordem os pedaços, a saber, a cabeça e o redenho, sobre a lenha que está no fogo sobre o altar.

[[v3-1-9]]

^<<v3-1-9,9>>^ Porém as entranhas e as pernas, o sacerdote as lavará com água; e queimará tudo isso sobre o altar; é holocausto, oferta queimada, de aroma agradável ao SENHOR.

[[v3-1-10]]

^<<v3-1-10,10>>^ Se a sua oferta for de gado miúdo, de carneiros ou de cabritos, para holocausto, trará macho sem defeito.

[[v3-1-11]]

^<<v3-1-11,11>>^ E o imolará ao lado do altar, para o lado norte, perante o SENHOR; e os filhos de Arão, os sacerdotes, aspergirão o seu sangue em redor sobre o altar.

[[v3-1-12]]

^<<v3-1-12,12>>^ Depois, ele o cortará em seus pedaços, como também a sua cabeça e o seu redenho; e o sacerdote os porá em ordem sobre a lenha que está no fogo sobre o altar;

[[v3-1-13]]

^<<v3-1-13,13>>^ porém as entranhas e as pernas serão lavadas com água; e o sacerdote oferecerá tudo isso e o queimará sobre o altar; é holocausto, oferta queimada, de aroma agradável ao SENHOR.

[[v3-1-14]]

^<<v3-1-14,14>>^ Se a sua oferta ao SENHOR for holocausto de aves, trará a sua oferta de rolas ou de pombinhos.

[[v3-1-15]]

^<<v3-1-15,15>>^ O sacerdote a trará ao altar, e, com a unha, lhe destroncará a cabeça, sem a separar do pescoço, e a queimará sobre o altar; o seu sangue, ele o fará correr na parede do altar;

[[v3-1-16]]

^<<v3-1-16,16>>^ tirará o papo com suas penas e o lançará junto ao altar, para o lado oriental, no lugar da cinza;

[[v3-1-17]]

^<<v3-1-17,17>>^ rasgá-la-á pelas asas, porém não a partirá; o sacerdote a queimará sobre o altar, em cima da lenha que está no fogo; é holocausto, oferta queimada, de aroma agradável ao SENHOR.

'''

xref:002-exodo/002-exodo-040.adoc#v2-40-0[&#60; Capítulo Anterior] | <<v3-1-0,Topo>> | xref:003-levitico/003-levitico-002.adoc#v3-2-0[Próximo Capítulo &#62;]