include::./index.adoc[]

[[v3-6-0]]
=== Levítico, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-6-1]]

^<<v3-6-1,1>>^ Falou mais o SENHOR a Moisés, dizendo:

[[v3-6-2]]

^<<v3-6-2,2>>^ Quando alguma pessoa pecar, e cometer ofensa contra o SENHOR, e negar ao seu próximo o que este lhe deu em depósito, ou penhor, ou roubar, ou tiver usado de extorsão para com o seu próximo;

[[v3-6-3]]

^<<v3-6-3,3>>^ ou que, tendo achado o perdido, o negar com falso juramento, ou fizer alguma outra coisa de todas em que o homem costuma pecar,

[[v3-6-4]]

^<<v3-6-4,4>>^ será, pois, que, tendo pecado e ficado culpada, restituirá aquilo que roubou, ou que extorquiu, ou o depósito que lhe foi dado, ou o perdido que achou,

[[v3-6-5]]

^<<v3-6-5,5>>^ ou tudo aquilo sobre que jurou falsamente; e o restituirá por inteiro e ainda a isso acrescentará a quinta parte; àquele a quem pertence, lho dará no dia da sua oferta pela culpa.

[[v3-6-6]]

^<<v3-6-6,6>>^ E, por sua oferta pela culpa, trará, do rebanho, ao SENHOR um carneiro sem defeito, conforme a tua avaliação, para a oferta pela culpa; trá-lo-á ao sacerdote.

[[v3-6-7]]

^<<v3-6-7,7>>^ E o sacerdote fará expiação por ela diante do SENHOR, e será perdoada de qualquer de todas as coisas que fez, tornando-se, por isso, culpada.

[[v3-6-8]]

^<<v3-6-8,8>>^ Disse mais o SENHOR a Moisés:

[[v3-6-9]]

^<<v3-6-9,9>>^ Dá ordem a Arão e a seus filhos, dizendo: Esta é a lei do holocausto: o holocausto ficará na lareira do altar toda a noite até pela manhã, e nela se manterá aceso o fogo do altar.

[[v3-6-10]]

^<<v3-6-10,10>>^ O sacerdote vestirá a sua túnica de linho e os calções de linho sobre a pele nua, e levantará a cinza, quando o fogo houver consumido o holocausto sobre o altar, e a porá junto a este.

[[v3-6-11]]

^<<v3-6-11,11>>^ Depois, despirá as suas vestes e porá outras; e levará a cinza para fora do arraial a um lugar limpo.

[[v3-6-12]]

^<<v3-6-12,12>>^ O fogo, pois, sempre arderá sobre o altar; não se apagará; mas o sacerdote acenderá lenha nele cada manhã, e sobre ele porá em ordem o holocausto, e sobre ele queimará a gordura das ofertas pacíficas.

[[v3-6-13]]

^<<v3-6-13,13>>^ O fogo arderá continuamente sobre o altar; não se apagará.

[[v3-6-14]]

^<<v3-6-14,14>>^ Esta é a lei da oferta de manjares: os filhos de Arão a oferecerão perante o SENHOR, diante do altar.

[[v3-6-15]]

^<<v3-6-15,15>>^ Um deles tomará dela um punhado de flor de farinha da oferta de manjares com seu azeite e todo o incenso que está sobre a oferta de manjares; então, o queimará sobre o altar, como porção memorial de aroma agradável ao SENHOR.

[[v3-6-16]]

^<<v3-6-16,16>>^ O restante dela comerão Arão e seus filhos; asmo se comerá no lugar santo; no pátio da tenda da congregação, o comerão.

[[v3-6-17]]

^<<v3-6-17,17>>^ Levedado não se cozerá; sua porção dei-lhes das minhas ofertas queimadas; coisa santíssima é, como a oferta pelo pecado e a oferta pela culpa.

[[v3-6-18]]

^<<v3-6-18,18>>^ Todo varão entre os filhos de Arão comerá da oferta de manjares; estatuto perpétuo será para as vossas gerações dentre as ofertas queimadas do SENHOR; tudo o que tocar nelas será santo.

[[v3-6-19]]

^<<v3-6-19,19>>^ Disse mais o SENHOR a Moisés:

[[v3-6-20]]

^<<v3-6-20,20>>^ Esta é a oferta de Arão e de seus filhos, que oferecerão ao SENHOR no dia em que aquele for ungido: a décima parte de um efa de flor de farinha pela oferta de manjares contínua; metade dela será oferecida pela manhã, e a outra metade, à tarde.

[[v3-6-21]]

^<<v3-6-21,21>>^ Numa assadeira, se fará com azeite; bem amassada a trarás; em pedaços cozidos trarás a oferta de manjares de aroma agradável ao SENHOR.

[[v3-6-22]]

^<<v3-6-22,22>>^ Também o sacerdote, que dentre os filhos de Arão for ungido em seu lugar, fará o mesmo; por estatuto perpétuo será de todo queimada ao SENHOR.

[[v3-6-23]]

^<<v3-6-23,23>>^ Assim, toda a oferta de manjares do sacerdote será totalmente queimada; não se comerá.

[[v3-6-24]]

^<<v3-6-24,24>>^ Disse mais o SENHOR a Moisés:

[[v3-6-25]]

^<<v3-6-25,25>>^ Fala a Arão e a seus filhos, dizendo: Esta é a lei da oferta pelo pecado: no lugar onde se imola o holocausto, se imolará a oferta pelo pecado, perante o SENHOR; coisa santíssima é.

[[v3-6-26]]

^<<v3-6-26,26>>^ O sacerdote que a oferecer pelo pecado a comerá; no lugar santo, se comerá, no pátio da tenda da congregação.

[[v3-6-27]]

^<<v3-6-27,27>>^ Tudo o que tocar a carne da oferta será santo; se aspergir alguém do seu sangue sobre a sua veste, lavarás aquilo sobre que caiu, no lugar santo.

[[v3-6-28]]

^<<v3-6-28,28>>^ E o vaso de barro em que for cozida será quebrado; porém, se for cozida num vaso de bronze, esfregar-se-á e lavar-se-á na água.

[[v3-6-29]]

^<<v3-6-29,29>>^ Todo varão entre os sacerdotes a comerá; coisa santíssima é.

[[v3-6-30]]

^<<v3-6-30,30>>^ Porém não se comerá nenhuma oferta pelo pecado, cujo sangue se traz à tenda da congregação, para fazer expiação no santuário; no fogo será queimada.

'''

xref:003-levitico/003-levitico-005.adoc#v3-5-0[&#60; Capítulo Anterior] | <<v3-6-0,Topo>> | xref:003-levitico/003-levitico-007.adoc#v3-7-0[Próximo Capítulo &#62;]