include::./index.adoc[]

[[v3-5-0]]
=== Levítico, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-5-1]]

^<<v3-5-1,1>>^ Quando alguém pecar nisto: tendo ouvido a voz da imprecação, sendo testemunha de um fato, por ter visto ou sabido e, contudo, não o revelar, levará a sua iniquidade;

[[v3-5-2]]

^<<v3-5-2,2>>^ ou quando alguém tocar em alguma coisa imunda, seja corpo morto de besta-fera imunda, seja corpo morto de animal imundo, seja corpo morto de réptil imundo, ainda que lhe fosse oculto, e tornar-se imundo, então, será culpado;

[[v3-5-3]]

^<<v3-5-3,3>>^ ou quando tocar a imundícia de um homem, seja qual for a imundícia com que se faça imundo, e lhe for oculto, e o souber depois, será culpado;

[[v3-5-4]]

^<<v3-5-4,4>>^ ou quando alguém jurar temerariamente com seus lábios fazer mal ou fazer bem, seja o que for que o homem pronuncie temerariamente com juramento, e lhe for oculto, e o souber depois, culpado será numa destas coisas.

[[v3-5-5]]

^<<v3-5-5,5>>^ Será, pois, que, sendo culpado numa destas coisas, confessará aquilo em que pecou.

[[v3-5-6]]

^<<v3-5-6,6>>^ Como sua oferta pela culpa, pelo pecado que cometeu, trará ele ao SENHOR, do gado miúdo, uma cordeira ou uma cabrita como oferta pelo pecado; assim, o sacerdote, por ele, fará expiação do seu pecado.

[[v3-5-7]]

^<<v3-5-7,7>>^ Se as suas posses não lhe permitirem trazer uma cordeira, trará ao SENHOR, como oferta pela culpa, pelo pecado que cometeu, duas rolas ou dois pombinhos: um como oferta pelo pecado, e o outro como holocausto.

[[v3-5-8]]

^<<v3-5-8,8>>^ Entregá-los-á ao sacerdote, o qual primeiro oferecerá aquele que é como oferta pelo pecado e lhe destroncará, com a unha, a cabeça, sem a separar do pescoço.

[[v3-5-9]]

^<<v3-5-9,9>>^ Do sangue da oferta pelo pecado aspergirá sobre a parede do altar e o restante do sangue, fá-lo-á correr à base do altar; é oferta pelo pecado.

[[v3-5-10]]

^<<v3-5-10,10>>^ E do outro fará holocausto, conforme o estabelecido; assim, o sacerdote, por ele, fará oferta pelo pecado que cometeu, e lhe será perdoado.

[[v3-5-11]]

^<<v3-5-11,11>>^ Porém, se as suas posses não lhe permitirem trazer duas rolas ou dois pombinhos, então, aquele que pecou trará, por sua oferta, a décima parte de um efa de flor de farinha como oferta pelo pecado; não lhe deitará azeite, nem lhe porá em cima incenso, pois é oferta pelo pecado.

[[v3-5-12]]

^<<v3-5-12,12>>^ Entregá-la-á ao sacerdote, e o sacerdote dela tomará um punhado como porção memorial e a queimará sobre o altar, em cima das ofertas queimadas ao SENHOR; é oferta pelo pecado.

[[v3-5-13]]

^<<v3-5-13,13>>^ Assim, o sacerdote, por ele, fará oferta pelo pecado que cometeu em alguma destas coisas, e lhe será perdoado; o restante será do sacerdote, como a oferta de manjares.

[[v3-5-14]]

^<<v3-5-14,14>>^ Disse mais o SENHOR a Moisés:

[[v3-5-15]]

^<<v3-5-15,15>>^ Quando alguém cometer ofensa e pecar por ignorância nas coisas sagradas do SENHOR, então, trará ao SENHOR, por oferta, do rebanho, um carneiro sem defeito, conforme a tua avaliação em siclos de prata, segundo o siclo do santuário, como oferta pela culpa.

[[v3-5-16]]

^<<v3-5-16,16>>^ Assim, restituirá o que ele tirou das coisas sagradas, e ainda acrescentará o seu quinto, e o dará ao sacerdote; assim, o sacerdote, com o carneiro da oferta pela culpa, fará expiação por ele, e lhe será perdoado.

[[v3-5-17]]

^<<v3-5-17,17>>^ E, se alguma pessoa pecar e fizer contra algum de todos os mandamentos do SENHOR aquilo que se não deve fazer, ainda que o não soubesse, contudo, será culpada e levará a sua iniquidade.

[[v3-5-18]]

^<<v3-5-18,18>>^ E do rebanho trará ao sacerdote um carneiro sem defeito, conforme a tua avaliação, para oferta pela culpa, e o sacerdote, por ela, fará expiação no tocante ao erro que, por ignorância, cometeu, e lhe será perdoado.

[[v3-5-19]]

^<<v3-5-19,19>>^ Oferta pela culpa é; certamente, se tornou culpada ao SENHOR.

'''

xref:003-levitico/003-levitico-004.adoc#v3-4-0[&#60; Capítulo Anterior] | <<v3-5-0,Topo>> | xref:003-levitico/003-levitico-006.adoc#v3-6-0[Próximo Capítulo &#62;]