include::./index.adoc[]

[[v3-10-0]]
=== Levítico, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-10-1]]

^<<v3-10-1,1>>^ Nadabe e Abiú, filhos de Arão, tomaram cada um o seu incensário, e puseram neles fogo, e sobre este, incenso, e trouxeram fogo estranho perante a face do SENHOR, o que lhes não ordenara.

[[v3-10-2]]

^<<v3-10-2,2>>^ Então, saiu fogo de diante do SENHOR e os consumiu; e morreram perante o SENHOR.

[[v3-10-3]]

^<<v3-10-3,3>>^ E falou Moisés a Arão: Isto é o que o SENHOR disse: Mostrarei a minha santidade naqueles que se cheguem a mim e serei glorificado diante de todo o povo. Porém Arão se calou.

[[v3-10-4]]

^<<v3-10-4,4>>^ Então, Moisés chamou a Misael e a Elzafã, filhos de Uziel, tio de Arão, e disse-lhes: Chegai, tirai vossos irmãos de diante do santuário, para fora do arraial.

[[v3-10-5]]

^<<v3-10-5,5>>^ Chegaram-se, pois, e os levaram nas suas túnicas para fora do arraial, como Moisés tinha dito.

[[v3-10-6]]

^<<v3-10-6,6>>^ Moisés disse a Arão e a seus filhos Eleazar e Itamar: Não desgrenheis os cabelos, nem rasgueis as vossas vestes, para que não morrais, nem venha grande ira sobre toda a congregação; mas vossos irmãos, toda a casa de Israel, lamentem o incêndio que o SENHOR suscitou.

[[v3-10-7]]

^<<v3-10-7,7>>^ Não saireis da porta da tenda da congregação, para que não morrais; porque está sobre vós o óleo da unção do SENHOR. E fizeram conforme a palavra de Moisés.

[[v3-10-8]]

^<<v3-10-8,8>>^ Falou também o SENHOR a Arão, dizendo:

[[v3-10-9]]

^<<v3-10-9,9>>^ Vinho ou bebida forte tu e teus filhos não bebereis quando entrardes na tenda da congregação, para que não morrais; estatuto perpétuo será isso entre as vossas gerações,

[[v3-10-10]]

^<<v3-10-10,10>>^ para fazerdes diferença entre o santo e o profano e entre o imundo e o limpo

[[v3-10-11]]

^<<v3-10-11,11>>^ e para ensinardes aos filhos de Israel todos os estatutos que o SENHOR lhes tem falado por intermédio de Moisés.

[[v3-10-12]]

^<<v3-10-12,12>>^ Disse Moisés a Arão e aos filhos deste, Eleazar e Itamar, que lhe ficaram: Tomai a oferta de manjares, restante das ofertas queimadas ao SENHOR, e comei-a, sem fermento, junto ao altar, porquanto coisa santíssima é.

[[v3-10-13]]

^<<v3-10-13,13>>^ Comê-la-eis em lugar santo, porque isto é a tua porção e a porção de teus filhos, das ofertas queimadas do SENHOR; porque assim me foi ordenado.

[[v3-10-14]]

^<<v3-10-14,14>>^ Também o peito da oferta movida e a coxa da oferta comereis em lugar limpo, tu, e teus filhos, e tuas filhas, porque foram dados por tua porção e por porção de teus filhos, dos sacrifícios pacíficos dos filhos de Israel.

[[v3-10-15]]

^<<v3-10-15,15>>^ A coxa da oferta e o peito da oferta movida trarão com as ofertas queimadas de gordura, para mover por oferta movida perante o SENHOR, o que será por estatuto perpétuo, para ti e para teus filhos, como o SENHOR tem ordenado.

[[v3-10-16]]

^<<v3-10-16,16>>^ Moisés diligentemente buscou o bode da oferta pelo pecado, e eis que já era queimado; portanto, indignando-se grandemente contra Eleazar e contra Itamar, os filhos que de Arão ficaram, disse:

[[v3-10-17]]

^<<v3-10-17,17>>^ Por que não comestes a oferta pelo pecado no lugar santo? Pois coisa santíssima é; e o SENHOR a deu a vós outros, para levardes a iniquidade da congregação, para fazerdes expiação por eles diante do SENHOR.

[[v3-10-18]]

^<<v3-10-18,18>>^ Eis que desta oferta não foi trazido o seu sangue para dentro do santuário; certamente, devíeis tê-la comido no santuário, como eu tinha ordenado.

[[v3-10-19]]

^<<v3-10-19,19>>^ Respondeu Arão a Moisés: Eis que, hoje, meus filhos ofereceram a sua oferta pelo pecado e o seu holocausto perante o SENHOR; e tais coisas me sucederam; se eu, hoje, tivesse comido a oferta pelo pecado, seria isso, porventura, aceito aos olhos do SENHOR?

[[v3-10-20]]

^<<v3-10-20,20>>^ O que ouvindo Moisés, deu-se por satisfeito.

'''

xref:003-levitico/003-levitico-009.adoc#v3-9-0[&#60; Capítulo Anterior] | <<v3-10-0,Topo>> | xref:003-levitico/003-levitico-011.adoc#v3-11-0[Próximo Capítulo &#62;]