include::./index.adoc[]

[[v3-13-0]]
=== Levítico, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-13-1]]

^<<v3-13-1,1>>^ Disse o SENHOR a Moisés e a Arão:

[[v3-13-2]]

^<<v3-13-2,2>>^ O homem que tiver na sua pele inchação, ou pústula, ou mancha lustrosa, e isto nela se tornar como praga de lepra, será levado a Arão, o sacerdote, ou a um de seus filhos, sacerdotes.

[[v3-13-3]]

^<<v3-13-3,3>>^ O sacerdote lhe examinará a praga na pele; se o pelo na praga se tornou branco, e a praga parecer mais profunda do que a pele da sua carne, é praga de lepra; o sacerdote o examinará e o declarará imundo.

[[v3-13-4]]

^<<v3-13-4,4>>^ Se a mancha lustrosa na pele for branca e não parecer mais profunda do que a pele, e o pelo não se tornou branco, então, o sacerdote encerrará por sete dias o que tem a praga.

[[v3-13-5]]

^<<v3-13-5,5>>^ Ao sétimo dia, o sacerdote o examinará; se, na sua opinião, a praga tiver parado e não se estendeu na sua pele, então, o sacerdote o encerrará por outros sete dias.

[[v3-13-6]]

^<<v3-13-6,6>>^ O sacerdote, ao sétimo dia, o examinará outra vez; se a lepra se tornou baça e na pele se não estendeu, então, o sacerdote o declarará limpo; é pústula; o homem lavará as suas vestes e será limpo.

[[v3-13-7]]

^<<v3-13-7,7>>^ Mas, se a pústula se estende muito na pele, depois de se ter mostrado ao sacerdote para a sua purificação, outra vez se mostrará ao sacerdote.

[[v3-13-8]]

^<<v3-13-8,8>>^ Este o examinará, e se a pústula se tiver estendido na pele, o sacerdote o declarará imundo; é lepra.

[[v3-13-9]]

^<<v3-13-9,9>>^ Quando no homem houver praga de lepra, será levado ao sacerdote.

[[v3-13-10]]

^<<v3-13-10,10>>^ E o sacerdote o examinará; se há inchação branca na pele, a qual tornou o pelo branco, e houver carne viva na inchação,

[[v3-13-11]]

^<<v3-13-11,11>>^ é lepra inveterada na pele; portanto, o sacerdote o declarará imundo; não o encerrará, porque é imundo.

[[v3-13-12]]

^<<v3-13-12,12>>^ Se a lepra se espalhar de todo na pele e cobrir a pele do que tem a lepra, desde a cabeça até aos pés, quanto podem ver os olhos do sacerdote,

[[v3-13-13]]

^<<v3-13-13,13>>^ então, este o examinará. Se a lepra cobriu toda a sua carne, declarará limpo o que tem a mancha; a lepra tornou-se branca; o homem está limpo.

[[v3-13-14]]

^<<v3-13-14,14>>^ Mas, no dia em que aparecer nele carne viva, será imundo.

[[v3-13-15]]

^<<v3-13-15,15>>^ Vendo, pois, o sacerdote a carne viva, declará-lo-á imundo; a carne viva é imunda; é lepra.

[[v3-13-16]]

^<<v3-13-16,16>>^ Se a carne viva mudar e ficar de novo branca, então, virá ao sacerdote,

[[v3-13-17]]

^<<v3-13-17,17>>^ e este o examinará. Se a lepra se tornou branca, então, o sacerdote declarará limpo o que tem a praga; está limpo.

[[v3-13-18]]

^<<v3-13-18,18>>^ Quando sarar a carne em cuja pele houver uma úlcera,

[[v3-13-19]]

^<<v3-13-19,19>>^ e no lugar da úlcera aparecer uma inchação branca ou mancha lustrosa, branca que tira a vermelho, mostrar-se-á ao sacerdote.

[[v3-13-20]]

^<<v3-13-20,20>>^ O sacerdote a examinará; se ela parece mais funda do que a pele, e o seu pelo se tornou branco, o sacerdote o declarará imundo; praga de lepra é, que brotou da úlcera.

[[v3-13-21]]

^<<v3-13-21,21>>^ Porém, se o sacerdote a examinar, e nela não houver pelo branco, e não estiver ela mais funda do que a pele, porém baça, então, o sacerdote o encerrará por sete dias.

[[v3-13-22]]

^<<v3-13-22,22>>^ Se ela se estender na pele, o sacerdote declarará imundo o homem; é lepra.

[[v3-13-23]]

^<<v3-13-23,23>>^ Mas, se a mancha lustrosa parar no seu lugar, não se estendendo, é cicatriz da úlcera; o sacerdote, pois, o declarará limpo.

[[v3-13-24]]

^<<v3-13-24,24>>^ Quando, na pele, houver queimadura de fogo, e a carne viva da queimadura se tornar em mancha lustrosa, branca que tira a vermelho ou branco,

[[v3-13-25]]

^<<v3-13-25,25>>^ o sacerdote a examinará. Se o pelo da mancha lustrosa se tornou branco, e ela parece mais funda do que a pele, é lepra que brotou na queimadura. O sacerdote declarará imundo o homem; é a praga de lepra.

[[v3-13-26]]

^<<v3-13-26,26>>^ Porém, se o sacerdote a examinar, e não houver pelo branco na mancha lustrosa, e ela não estiver mais funda que a pele, mas for de cor baça, o sacerdote encerrará por sete dias o homem.

[[v3-13-27]]

^<<v3-13-27,27>>^ Depois, o sacerdote o examinará ao sétimo dia; se ela se tiver estendido na pele, o sacerdote o declarará imundo; é praga de lepra.

[[v3-13-28]]

^<<v3-13-28,28>>^ Mas, se a mancha lustrosa parar no seu lugar e na pele não se estender, mas se tornou baça, é inchação da queimadura; portanto, o sacerdote o declarará limpo, porque é cicatriz da queimadura.

[[v3-13-29]]

^<<v3-13-29,29>>^ Quando o homem (ou a mulher) tiver praga na cabeça ou na barba,

[[v3-13-30]]

^<<v3-13-30,30>>^ o sacerdote examinará a praga; se ela parece mais funda do que a pele, e pelo amarelo fino nela houver, o sacerdote o declarará imundo; é tinha, é lepra da cabeça ou da barba.

[[v3-13-31]]

^<<v3-13-31,31>>^ Mas, se o sacerdote, havendo examinado a praga da tinha, achar que ela não parece mais funda do que a pele, e, se nela não houver pelo preto, então, o sacerdote encerrará o que tem a praga da tinha por sete dias.

[[v3-13-32]]

^<<v3-13-32,32>>^ Ao sétimo dia, o sacerdote examinará a praga; se a tinha não se tiver espalhado, e nela não houver pelo amarelo, e a tinha não parecer mais funda do que a pele,

[[v3-13-33]]

^<<v3-13-33,33>>^ então, o homem será rapado; mas não se rapará a tinha. O sacerdote, por mais sete dias, encerrará o que tem a tinha.

[[v3-13-34]]

^<<v3-13-34,34>>^ Ao sétimo dia, o sacerdote examinará a tinha; se ela não se houver estendido na pele e não parecer mais funda do que a pele, o sacerdote declarará limpo o homem; este lavará as suas vestes e será limpo.

[[v3-13-35]]

^<<v3-13-35,35>>^ Mas, se a tinha, depois da sua purificação, se tiver espalhado muito na pele,

[[v3-13-36]]

^<<v3-13-36,36>>^ então, o sacerdote o examinará; se a tinha se tiver espalhado na pele, o sacerdote não procurará pelo amarelo; está imundo.

[[v3-13-37]]

^<<v3-13-37,37>>^ Mas, se a tinha, a seu ver, parou, e pelo preto cresceu nela, a tinha está sarada; ele está limpo, e o sacerdote o declarará limpo.

[[v3-13-38]]

^<<v3-13-38,38>>^ E, quando o homem (ou a mulher) tiver manchas lustrosas na pele,

[[v3-13-39]]

^<<v3-13-39,39>>^ então, o sacerdote o examinará; se na pele aparecerem manchas baças, brancas, é impigem branca que brotou na pele; está limpo.

[[v3-13-40]]

^<<v3-13-40,40>>^ Quando os cabelos do homem lhe caírem da cabeça, é calva; contudo, está limpo.

[[v3-13-41]]

^<<v3-13-41,41>>^ Se lhe caírem na frente da cabeça, é antecalva; contudo, está limpo.

[[v3-13-42]]

^<<v3-13-42,42>>^ Porém, se, na calva ou na antecalva, houver praga branca, que tira a vermelho, é lepra, brotando na calva ou na antecalva.

[[v3-13-43]]

^<<v3-13-43,43>>^ Havendo, pois, o sacerdote examinado, se a inchação da praga, na sua calva ou antecalva, está branca, que tira a vermelho, como parece a lepra na pele,

[[v3-13-44]]

^<<v3-13-44,44>>^ é leproso aquele homem, está imundo; o sacerdote o declarará imundo; a sua praga está na cabeça.

[[v3-13-45]]

^<<v3-13-45,45>>^ As vestes do leproso, em quem está a praga, serão rasgadas, e os seus cabelos serão desgrenhados; cobrirá o bigode e clamará: Imundo! Imundo!

[[v3-13-46]]

^<<v3-13-46,46>>^ Será imundo durante os dias em que a praga estiver nele; é imundo, habitará só; a sua habitação será fora do arraial.

[[v3-13-47]]

^<<v3-13-47,47>>^ Quando também em alguma veste houver praga de lepra, veste de lã ou de linho,

[[v3-13-48]]

^<<v3-13-48,48>>^ seja na urdidura, seja na trama, de linho ou de lã, em pele ou em qualquer obra de peles,

[[v3-13-49]]

^<<v3-13-49,49>>^ se a praga for esverdinhada ou avermelhada na veste, ou na pele, ou na urdidura, ou na trama, em qualquer coisa feita de pele, é a praga de lepra, e mostrar-se-á ao sacerdote.

[[v3-13-50]]

^<<v3-13-50,50>>^ O sacerdote examinará a praga e encerrará, por sete dias, aquilo que tem a praga.

[[v3-13-51]]

^<<v3-13-51,51>>^ Então, examinará a praga ao sétimo dia; se ela se houver estendido na veste, na urdidura ou na trama, seja na pele, seja qual for a obra em que se empregue, é lepra maligna; isso é imundo.

[[v3-13-52]]

^<<v3-13-52,52>>^ Pelo que se queimará aquela veste, seja a urdidura, seja a trama, de lã, ou de linho, ou qualquer coisa feita de pele, em que se acha a praga, pois é lepra maligna; tudo se queimará.

[[v3-13-53]]

^<<v3-13-53,53>>^ Mas, examinando o sacerdote, se a praga não se tiver espalhado na veste, nem na urdidura, nem na trama, nem em qualquer coisa feita de pele,

[[v3-13-54]]

^<<v3-13-54,54>>^ então, o sacerdote ordenará que se lave aquilo em que havia a praga e o encerrará por mais sete dias;

[[v3-13-55]]

^<<v3-13-55,55>>^ o sacerdote, examinando a coisa em que havia praga, depois de lavada aquela, se a praga não mudou a sua cor, nem se espalhou, está imunda; com fogo a queimarás; é lepra roedora, seja no avesso ou no direito.

[[v3-13-56]]

^<<v3-13-56,56>>^ Mas, se o sacerdote examinar a mancha, e esta se tornou baça depois de lavada, então, a rasgará da veste, ou da pele, ou da urdidura, ou da trama.

[[v3-13-57]]

^<<v3-13-57,57>>^ Se a praga ainda aparecer na veste, quer na urdidura, quer na trama, ou em qualquer coisa feita de pele, é lepra que se espalha; com fogo queimarás aquilo em que está a praga.

[[v3-13-58]]

^<<v3-13-58,58>>^ Mas a veste, quer na urdidura, quer na trama, ou qualquer coisa de peles, que lavares e de que a praga se retirar, se lavará segunda vez e será limpa.

[[v3-13-59]]

^<<v3-13-59,59>>^ Esta é a lei da praga da lepra da veste de lã ou de linho, quer na urdidura, quer na trama; ou de qualquer coisa de peles, para se poder declará-las limpas ou imundas.

'''

xref:003-levitico/003-levitico-012.adoc#v3-12-0[&#60; Capítulo Anterior] | <<v3-13-0,Topo>> | xref:003-levitico/003-levitico-014.adoc#v3-14-0[Próximo Capítulo &#62;]