include::./index.adoc[]

[[v3-9-0]]
=== Levítico, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-9-1]]

^<<v3-9-1,1>>^ Ao oitavo dia, chamou Moisés a Arão, e a seus filhos, e aos anciãos de Israel

[[v3-9-2]]

^<<v3-9-2,2>>^ e disse a Arão: Toma um bezerro, para oferta pelo pecado, e um carneiro, para holocausto, ambos sem defeito, e traze-os perante o SENHOR.

[[v3-9-3]]

^<<v3-9-3,3>>^ Depois, dirás aos filhos de Israel: Tomai um bode, para oferta pelo pecado, um bezerro e um cordeiro, ambos de um ano e sem defeito, como holocausto;

[[v3-9-4]]

^<<v3-9-4,4>>^ e um boi e um carneiro, por oferta pacífica, para sacrificar perante o SENHOR, e oferta de manjares amassada com azeite; porquanto, hoje, o SENHOR vos aparecerá.

[[v3-9-5]]

^<<v3-9-5,5>>^ Então, trouxeram o que ordenara Moisés, diante da tenda da congregação, e chegou-se toda a congregação e se pôs perante o SENHOR.

[[v3-9-6]]

^<<v3-9-6,6>>^ Disse Moisés: Esta coisa que o SENHOR ordenou fareis; e a glória do SENHOR vos aparecerá.

[[v3-9-7]]

^<<v3-9-7,7>>^ Depois, disse Moisés a Arão: Chega-te ao altar, faze a tua oferta pelo pecado e o teu holocausto; e faze expiação por ti e pelo povo; depois, faze a oferta do povo e a expiação por ele, como ordenou o SENHOR.

[[v3-9-8]]

^<<v3-9-8,8>>^ Chegou-se, pois, Arão ao altar e imolou o bezerro da oferta pelo pecado que era por si mesmo.

[[v3-9-9]]

^<<v3-9-9,9>>^ Os filhos de Arão trouxeram-lhe o sangue; ele molhou o dedo no sangue e o pôs sobre os chifres do altar; e o resto do sangue derramou à base do altar.

[[v3-9-10]]

^<<v3-9-10,10>>^ Mas a gordura, e os rins, e o redenho do fígado da oferta pelo pecado queimou sobre o altar, como o SENHOR ordenara a Moisés.

[[v3-9-11]]

^<<v3-9-11,11>>^ Porém a carne e o couro queimou fora do arraial.

[[v3-9-12]]

^<<v3-9-12,12>>^ Depois, imolou o holocausto, e os filhos de Arão lhe entregaram o sangue, e ele o aspergiu sobre o altar, em redor.

[[v3-9-13]]

^<<v3-9-13,13>>^ Também lhe entregaram o holocausto nos seus pedaços, com a cabeça; e queimou-o sobre o altar.

[[v3-9-14]]

^<<v3-9-14,14>>^ E lavou as entranhas e as pernas e as queimou sobre o holocausto, no altar.

[[v3-9-15]]

^<<v3-9-15,15>>^ Depois, fez chegar a oferta do povo, e, tomando o bode da oferta pelo pecado, que era pelo povo, o imolou, e o preparou por oferta pelo pecado, como fizera com o primeiro.

[[v3-9-16]]

^<<v3-9-16,16>>^ Também fez chegar o holocausto e o ofereceu segundo o rito.

[[v3-9-17]]

^<<v3-9-17,17>>^ Fez chegar a oferta de manjares, e dela tomou um punhado, e queimou sobre o altar, além do holocausto da manhã.

[[v3-9-18]]

^<<v3-9-18,18>>^ Depois, imolou o boi e o carneiro em sacrifício pacífico, que era pelo povo; e os filhos de Arão entregaram-lhe o sangue, que aspergiu sobre o altar, em redor,

[[v3-9-19]]

^<<v3-9-19,19>>^ como também a gordura do boi e do carneiro, e a cauda, e o que cobre as entranhas, e os rins, e o redenho do fígado.

[[v3-9-20]]

^<<v3-9-20,20>>^ E puseram a gordura sobre o peito, e ele a queimou sobre o altar;

[[v3-9-21]]

^<<v3-9-21,21>>^ mas o peito e a coxa direita Arão moveu por oferta movida perante o SENHOR, como Moisés tinha ordenado.

[[v3-9-22]]

^<<v3-9-22,22>>^ Depois, Arão levantou as mãos para o povo e o abençoou; e desceu, havendo feito a oferta pelo pecado, e o holocausto, e a oferta pacífica.

[[v3-9-23]]

^<<v3-9-23,23>>^ Então, entraram Moisés e Arão na tenda da congregação; e, saindo, abençoaram o povo; e a glória do SENHOR apareceu a todo o povo.

[[v3-9-24]]

^<<v3-9-24,24>>^ E eis que, saindo fogo de diante do SENHOR, consumiu o holocausto e a gordura sobre o altar; o que vendo o povo, jubilou e prostrou-se sobre o rosto.

'''

xref:003-levitico/003-levitico-008.adoc#v3-8-0[&#60; Capítulo Anterior] | <<v3-9-0,Topo>> | xref:003-levitico/003-levitico-010.adoc#v3-10-0[Próximo Capítulo &#62;]