include::./index.adoc[]

[[v3-8-0]]
=== Levítico, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-8-1]]

^<<v3-8-1,1>>^ Disse mais o SENHOR a Moisés:

[[v3-8-2]]

^<<v3-8-2,2>>^ Toma Arão, e seus filhos, e as vestes, e o óleo da unção, como também o novilho da oferta pelo pecado, e os dois carneiros, e o cesto dos pães asmos

[[v3-8-3]]

^<<v3-8-3,3>>^ e ajunta toda a congregação à porta da tenda da congregação.

[[v3-8-4]]

^<<v3-8-4,4>>^ Fez, pois, Moisés como o SENHOR lhe ordenara, e a congregação se ajuntou à porta da tenda da congregação.

[[v3-8-5]]

^<<v3-8-5,5>>^ Então, disse Moisés à congregação: Isto é o que o SENHOR ordenou que se fizesse.

[[v3-8-6]]

^<<v3-8-6,6>>^ E fez chegar a Arão e a seus filhos e os lavou com água.

[[v3-8-7]]

^<<v3-8-7,7>>^ Vestiu a Arão da túnica, cingiu-o com o cinto e pôs sobre ele a sobrepeliz; também pôs sobre ele a estola sacerdotal, e o cingiu com o cinto de obra esmerada da estola sacerdotal, e o ajustou com ele.

[[v3-8-8]]

^<<v3-8-8,8>>^ Depois, lhe colocou o peitoral, pondo no peitoral o Urim e o Tumim;

[[v3-8-9]]

^<<v3-8-9,9>>^ e lhe pôs a mitra na cabeça e na mitra, na sua parte dianteira, pôs a lâmina de ouro, a coroa sagrada, como o SENHOR ordenara a Moisés.

[[v3-8-10]]

^<<v3-8-10,10>>^ Então, Moisés tomou o óleo da unção, e ungiu o tabernáculo e tudo o que havia nele, e o consagrou;

[[v3-8-11]]

^<<v3-8-11,11>>^ e dele aspergiu sete vezes sobre o altar e ungiu o altar e todos os seus utensílios, como também a bacia e o seu suporte, para os consagrar.

[[v3-8-12]]

^<<v3-8-12,12>>^ Depois, derramou do óleo da unção sobre a cabeça de Arão e ungiu-o, para consagrá-lo.

[[v3-8-13]]

^<<v3-8-13,13>>^ Também Moisés fez chegar os filhos de Arão, e vestiu-lhes as túnicas, e cingiu-os com o cinto, e atou-lhes as tiaras, como o SENHOR lhe ordenara.

[[v3-8-14]]

^<<v3-8-14,14>>^ Então, fez chegar o novilho da oferta pelo pecado; e Arão e seus filhos puseram as mãos sobre a cabeça do novilho da oferta pelo pecado;

[[v3-8-15]]

^<<v3-8-15,15>>^ e Moisés o imolou, e tomou o sangue, e dele pôs, com o dedo, sobre os chifres do altar em redor, e purificou o altar; depois, derramou o resto do sangue à base do altar e o consagrou, para fazer expiação por ele.

[[v3-8-16]]

^<<v3-8-16,16>>^ Depois, tomou toda a gordura que está sobre as entranhas, e o redenho do fígado, e os dois rins, e sua gordura; e Moisés os queimou sobre o altar.

[[v3-8-17]]

^<<v3-8-17,17>>^ Mas o novilho com o seu couro, e a sua carne, e o seu excremento queimou fora do arraial, como o SENHOR ordenara a Moisés.

[[v3-8-18]]

^<<v3-8-18,18>>^ Depois, fez chegar o carneiro do holocausto; e Arão e seus filhos puseram as mãos sobre a cabeça do carneiro.

[[v3-8-19]]

^<<v3-8-19,19>>^ E Moisés o imolou e aspergiu o sangue sobre o altar, em redor.

[[v3-8-20]]

^<<v3-8-20,20>>^ Partiu também o carneiro nos seus pedaços; Moisés queimou a cabeça, os pedaços e a gordura.

[[v3-8-21]]

^<<v3-8-21,21>>^ Porém as entranhas e as pernas lavou com água; e Moisés queimou todo o carneiro sobre o altar; holocausto de aroma agradável, oferta queimada era ao SENHOR, como o SENHOR ordenara a Moisés.

[[v3-8-22]]

^<<v3-8-22,22>>^ Então, fez chegar o outro carneiro, o carneiro da consagração; e Arão e seus filhos puseram as mãos sobre a cabeça do carneiro.

[[v3-8-23]]

^<<v3-8-23,23>>^ E Moisés o imolou, e tomou do seu sangue, e o pôs sobre a ponta da orelha direita de Arão, e sobre o polegar da sua mão direita, e sobre o polegar do seu pé direito.

[[v3-8-24]]

^<<v3-8-24,24>>^ Também fez chegar os filhos de Arão; pôs daquele sangue sobre a ponta da orelha direita deles, e sobre o polegar da mão direita, e sobre o polegar do pé direito; e aspergiu Moisés o resto do sangue sobre o altar, em redor.

[[v3-8-25]]

^<<v3-8-25,25>>^ Tomou a gordura, e a cauda, e toda a gordura que está nas entranhas, e o redenho do fígado, e ambos os rins, e a sua gordura, e a coxa direita.

[[v3-8-26]]

^<<v3-8-26,26>>^ Também do cesto dos pães asmos, que estava diante do SENHOR, tomou um bolo asmo, um bolo de pão azeitado e uma obreia e os pôs sobre a gordura e sobre a coxa direita.

[[v3-8-27]]

^<<v3-8-27,27>>^ E tudo isso pôs nas mãos de Arão e de seus filhos e o moveu por oferta movida perante o SENHOR.

[[v3-8-28]]

^<<v3-8-28,28>>^ Depois, Moisés o tomou das suas mãos e o queimou no altar sobre o holocausto; era uma oferta da consagração, por aroma agradável, oferta queimada ao SENHOR.

[[v3-8-29]]

^<<v3-8-29,29>>^ Tomou Moisés o peito e moveu-o por oferta movida perante o SENHOR; era a porção que tocava a Moisés, do carneiro da consagração, como o SENHOR lhe ordenara.

[[v3-8-30]]

^<<v3-8-30,30>>^ Tomou Moisés também do óleo da unção e do sangue que estava sobre o altar e o aspergiu sobre Arão e as suas vestes, bem como sobre os filhos de Arão e as suas vestes; e consagrou a Arão, e as suas vestes, e a seus filhos, e as vestes de seus filhos.

[[v3-8-31]]

^<<v3-8-31,31>>^ Disse Moisés a Arão e a seus filhos: Cozei a carne diante da porta da tenda da congregação e ali a comereis com o pão que está no cesto da consagração, como tenho ordenado, dizendo: Arão e seus filhos a comerão.

[[v3-8-32]]

^<<v3-8-32,32>>^ Mas o que restar da carne e do pão queimareis.

[[v3-8-33]]

^<<v3-8-33,33>>^ Também da porta da tenda da congregação não saireis por sete dias, até ao dia em que se cumprirem os dias da vossa consagração; porquanto por sete dias o SENHOR vos consagrará.

[[v3-8-34]]

^<<v3-8-34,34>>^ Como se fez neste dia, assim o SENHOR ordenou se fizesse, em expiação por vós.

[[v3-8-35]]

^<<v3-8-35,35>>^ Ficareis, pois, à porta da tenda da congregação dia e noite, por sete dias, e observareis as prescrições do SENHOR, para que não morrais; porque assim me foi ordenado.

[[v3-8-36]]

^<<v3-8-36,36>>^ E Arão e seus filhos fizeram todas as coisas que o SENHOR ordenara por intermédio de Moisés.

'''

xref:003-levitico/003-levitico-007.adoc#v3-7-0[&#60; Capítulo Anterior] | <<v3-8-0,Topo>> | xref:003-levitico/003-levitico-009.adoc#v3-9-0[Próximo Capítulo &#62;]