include::./index.adoc[]

[[v3-27-0]]
=== Levítico, 27
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-27-1]]

^<<v3-27-1,1>>^ Disse mais o SENHOR a Moisés:

[[v3-27-2]]

^<<v3-27-2,2>>^ Fala aos filhos de Israel e dize-lhes: Quando alguém fizer voto com respeito a pessoas, estas serão do SENHOR, segundo a tua avaliação.

[[v3-27-3]]

^<<v3-27-3,3>>^ Se o objeto da tua avaliação for homem, da idade de vinte anos até à de sessenta, será a tua avaliação de cinquenta siclos de prata, segundo o siclo do santuário.

[[v3-27-4]]

^<<v3-27-4,4>>^ Porém, se for mulher, a tua avaliação será de trinta siclos.

[[v3-27-5]]

^<<v3-27-5,5>>^ Se a idade for de cinco anos até vinte, a tua avaliação do homem será de vinte siclos, e a da mulher, de dez siclos.

[[v3-27-6]]

^<<v3-27-6,6>>^ Se a idade for de um mês até cinco anos, a tua avaliação do homem será de cinco siclos de prata, e a tua avaliação pela mulher será de três siclos de prata.

[[v3-27-7]]

^<<v3-27-7,7>>^ De sessenta anos para cima, se for homem, a tua avaliação será de quinze siclos; se mulher, dez siclos.

[[v3-27-8]]

^<<v3-27-8,8>>^ Mas, se for mais pobre do que a tua avaliação, então, apresentar-se-á diante do sacerdote, para que este o avalie; segundo o que permitem as posses do que fez o voto, o avaliará o sacerdote.

[[v3-27-9]]

^<<v3-27-9,9>>^ Se for animal dos que se oferecem ao SENHOR, tudo quanto dele se der ao SENHOR será santo.

[[v3-27-10]]

^<<v3-27-10,10>>^ Não o mudará, nem o trocará bom por mau ou mau por bom; porém, se dalgum modo se trocar animal por animal, um e outro serão santos.

[[v3-27-11]]

^<<v3-27-11,11>>^ Se for animal imundo dos que se não oferecem ao SENHOR, então, apresentará o animal diante do sacerdote.

[[v3-27-12]]

^<<v3-27-12,12>>^ O sacerdote o avaliará, seja bom ou mau; segundo a avaliação do sacerdote, assim será.

[[v3-27-13]]

^<<v3-27-13,13>>^ Porém, se dalgum modo o resgatar, então, acrescentará a quinta parte à tua avaliação.

[[v3-27-14]]

^<<v3-27-14,14>>^ Quando alguém dedicar a sua casa para ser santa ao SENHOR, o sacerdote a avaliará, seja boa ou seja má; como o sacerdote a avaliar, assim será.

[[v3-27-15]]

^<<v3-27-15,15>>^ Mas, se aquele que a dedicou quiser resgatar a casa, então, acrescentará a quinta parte do dinheiro à tua avaliação, e será sua.

[[v3-27-16]]

^<<v3-27-16,16>>^ Se alguém dedicar ao SENHOR parte do campo da sua herança, então, a tua avaliação será segundo a semente necessária para o semear: um gômer pleno de cevada será avaliado por cinquenta siclos de prata.

[[v3-27-17]]

^<<v3-27-17,17>>^ Se dedicar o seu campo desde o Ano do Jubileu, segundo a tua plena avaliação, ficará.

[[v3-27-18]]

^<<v3-27-18,18>>^ Mas, se dedicar o seu campo depois do Ano do Jubileu, então, o sacerdote lhe contará o dinheiro segundo os anos restantes até ao Ano do Jubileu, e isto se abaterá da tua avaliação.

[[v3-27-19]]

^<<v3-27-19,19>>^ Se aquele que dedicou o campo dalgum modo o quiser resgatar, então, acrescentará a quinta parte do dinheiro à tua avaliação, e ficará seu.

[[v3-27-20]]

^<<v3-27-20,20>>^ Se não quiser resgatar o campo ou se o vender a outro homem, nunca mais se resgatará.

[[v3-27-21]]

^<<v3-27-21,21>>^ Porém, havendo o campo saído livre no Ano do Jubileu, será santo ao SENHOR, como campo consagrado; a posse dele será do sacerdote.

[[v3-27-22]]

^<<v3-27-22,22>>^ Se alguém dedicar ao SENHOR o campo que comprou, e não for parte da sua herança,

[[v3-27-23]]

^<<v3-27-23,23>>^ então, o sacerdote lhe contará o preço da avaliação até ao Ano do Jubileu; e, no mesmo dia, dará o importe da avaliação como coisa santa ao SENHOR.

[[v3-27-24]]

^<<v3-27-24,24>>^ No Ano do Jubileu, o campo tornará àquele que o vendeu, àquele de quem era a posse do campo por herança.

[[v3-27-25]]

^<<v3-27-25,25>>^ Toda a tua avaliação se fará segundo o siclo do santuário; o siclo será de vinte geras.

[[v3-27-26]]

^<<v3-27-26,26>>^ Mas o primogênito de um animal, por já pertencer ao SENHOR, ninguém o dedicará; seja boi ou gado miúdo, é do SENHOR.

[[v3-27-27]]

^<<v3-27-27,27>>^ Mas, se for de um animal imundo, resgatar-se-á, segundo a tua avaliação, e sobre ele acrescentará a quinta parte; se não for resgatado, vender-se-á, segundo a tua avaliação.

[[v3-27-28]]

^<<v3-27-28,28>>^ No entanto, nada do que alguém dedicar irremissivelmente ao SENHOR, de tudo o que tem, seja homem, ou animal, ou campo da sua herança, se poderá vender, nem resgatar; toda coisa assim consagrada será santíssima ao SENHOR.

[[v3-27-29]]

^<<v3-27-29,29>>^ Ninguém que dentre os homens for dedicado irremissivelmente ao SENHOR se poderá resgatar; será morto.

[[v3-27-30]]

^<<v3-27-30,30>>^ Também todas as dízimas da terra, tanto dos cereais do campo como dos frutos das árvores, são do SENHOR; santas são ao SENHOR.

[[v3-27-31]]

^<<v3-27-31,31>>^ Se alguém, das suas dízimas, quiser resgatar alguma coisa, acrescentará a sua quinta parte sobre ela.

[[v3-27-32]]

^<<v3-27-32,32>>^ No tocante às dízimas do gado e do rebanho, de tudo o que passar debaixo do bordão do pastor, o dízimo será santo ao SENHOR.

[[v3-27-33]]

^<<v3-27-33,33>>^ Não se investigará se é bom ou mau, nem o trocará; mas, se dalgum modo o trocar, um e outro serão santos; não serão resgatados.

[[v3-27-34]]

^<<v3-27-34,34>>^ São estes os mandamentos que o SENHOR ordenou a Moisés, para os filhos de Israel, no monte Sinai.

'''

xref:003-levitico/003-levitico-026.adoc#v3-26-0[&#60; Capítulo Anterior] | <<v3-27-0,Topo>> | xref:004-numeros/004-numeros-001.adoc#v4-1-0[Próximo Capítulo &#62;]