include::./index.adoc[]

[[v3-15-0]]
=== Levítico, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-15-1]]

^<<v3-15-1,1>>^ Disse mais o SENHOR a Moisés e a Arão:

[[v3-15-2]]

^<<v3-15-2,2>>^ Falai aos filhos de Israel e dizei-lhes: Qualquer homem que tiver fluxo seminal do seu corpo será imundo por causa do fluxo.

[[v3-15-3]]

^<<v3-15-3,3>>^ Esta, pois, será a sua imundícia por causa do seu fluxo: se o seu corpo vaza o fluxo ou se o seu corpo o estanca, esta é a sua imundícia.

[[v3-15-4]]

^<<v3-15-4,4>>^ Toda cama em que se deitar o que tiver fluxo será imunda; e tudo sobre que se assentar será imundo.

[[v3-15-5]]

^<<v3-15-5,5>>^ Qualquer que lhe tocar a cama lavará as suas vestes, banhar-se-á em água e será imundo até à tarde.

[[v3-15-6]]

^<<v3-15-6,6>>^ Aquele que se assentar sobre aquilo em que se assentara o que tem o fluxo lavará as suas vestes, banhar-se-á em água e será imundo até à tarde.

[[v3-15-7]]

^<<v3-15-7,7>>^ Quem tocar o corpo do que tem o fluxo lavará as suas vestes, banhar-se-á em água e será imundo até à tarde.

[[v3-15-8]]

^<<v3-15-8,8>>^ Se o homem que tem o fluxo cuspir sobre uma pessoa limpa, então, esta lavará as suas vestes, banhar-se-á em água e será imunda até à tarde.

[[v3-15-9]]

^<<v3-15-9,9>>^ Também toda sela em que cavalgar o que tem o fluxo será imunda.

[[v3-15-10]]

^<<v3-15-10,10>>^ Qualquer que tocar alguma coisa que esteve debaixo dele será imundo até à tarde; e aquele que a levar lavará as suas vestes, banhar-se-á em água e será imundo até à tarde.

[[v3-15-11]]

^<<v3-15-11,11>>^ Também todo aquele em quem tocar o que tiver o fluxo, sem haver lavado as suas mãos com água, lavará as suas vestes, banhar-se-á em água e será imundo até à tarde.

[[v3-15-12]]

^<<v3-15-12,12>>^ O vaso de barro em que tocar o que tem o fluxo será quebrado; porém todo vaso de madeira será lavado em água.

[[v3-15-13]]

^<<v3-15-13,13>>^ Quando, pois, o que tem o fluxo dele estiver limpo, contar-se-ão sete dias para a sua purificação; lavará as suas vestes, banhará o corpo em águas correntes e será limpo.

[[v3-15-14]]

^<<v3-15-14,14>>^ Ao oitavo dia, tomará duas rolas ou dois pombinhos, e virá perante o SENHOR, à porta da tenda da congregação, e os dará ao sacerdote;

[[v3-15-15]]

^<<v3-15-15,15>>^ este os oferecerá, um, para oferta pelo pecado, e o outro, para holocausto; e, assim, o sacerdote fará, por ele, expiação do seu fluxo perante o SENHOR.

[[v3-15-16]]

^<<v3-15-16,16>>^ Também o homem, quando se der com ele emissão do sêmen, banhará todo o seu corpo em água e será imundo até à tarde.

[[v3-15-17]]

^<<v3-15-17,17>>^ Toda veste e toda pele em que houver sêmen se lavarão em água e serão imundas até à tarde.

[[v3-15-18]]

^<<v3-15-18,18>>^ Se um homem coabitar com mulher e tiver emissão do sêmen, ambos se banharão em água e serão imundos até à tarde.

[[v3-15-19]]

^<<v3-15-19,19>>^ A mulher, quando tiver o fluxo de sangue, se este for o fluxo costumado do seu corpo, estará sete dias na sua menstruação, e qualquer que a tocar será imundo até à tarde.

[[v3-15-20]]

^<<v3-15-20,20>>^ Tudo sobre que ela se deitar durante a menstruação será imundo; e tudo sobre que se assentar será imundo.

[[v3-15-21]]

^<<v3-15-21,21>>^ Quem tocar no leito dela lavará as suas vestes, banhar-se-á em água e será imundo até à tarde.

[[v3-15-22]]

^<<v3-15-22,22>>^ Quem tocar alguma coisa sobre que ela se tiver assentado lavará as suas vestes, banhar-se-á em água e será imundo até à tarde.

[[v3-15-23]]

^<<v3-15-23,23>>^ Também quem tocar alguma coisa que estiver sobre a cama ou sobre aquilo em que ela se assentou, esse será imundo até à tarde.

[[v3-15-24]]

^<<v3-15-24,24>>^ Se um homem coabitar com ela, e a sua menstruação estiver sobre ele, será imundo por sete dias; e toda cama sobre que ele se deitar será imunda.

[[v3-15-25]]

^<<v3-15-25,25>>^ Também a mulher, quando manar fluxo do seu sangue, por muitos dias fora do tempo da sua menstruação ou quando tiver fluxo do sangue por mais tempo do que o costumado, todos os dias do fluxo será imunda, como nos dias da sua menstruação.

[[v3-15-26]]

^<<v3-15-26,26>>^ Toda cama sobre que se deitar durante os dias do seu fluxo ser-lhe-á como a cama da sua menstruação; e toda coisa sobre que se assentar será imunda, conforme a impureza da sua menstruação.

[[v3-15-27]]

^<<v3-15-27,27>>^ Quem tocar estas será imundo; portanto, lavará as suas vestes, banhar-se-á em água e será imundo até à tarde.

[[v3-15-28]]

^<<v3-15-28,28>>^ Porém, quando lhe cessar o fluxo, então, se contarão sete dias, e depois será limpa.

[[v3-15-29]]

^<<v3-15-29,29>>^ Ao oitavo dia, tomará duas rolas ou dois pombinhos e os trará ao sacerdote à porta da tenda da congregação.

[[v3-15-30]]

^<<v3-15-30,30>>^ Então, o sacerdote oferecerá um, para oferta pelo pecado, e o outro, para holocausto; o sacerdote fará, por ela, expiação do fluxo da sua impureza perante o SENHOR.

[[v3-15-31]]

^<<v3-15-31,31>>^ Assim, separareis os filhos de Israel das suas impurezas, para que não morram nelas, ao contaminarem o meu tabernáculo, que está no meio deles.

[[v3-15-32]]

^<<v3-15-32,32>>^ Esta é a lei daquele que tem o fluxo, e daquele com quem se dá emissão do sêmen e que fica por ela imundo,

[[v3-15-33]]

^<<v3-15-33,33>>^ e também da mulher passível da sua menstruação, e daquele que tem o fluxo, seja homem ou mulher, e do homem que se deita com mulher imunda.

'''

xref:003-levitico/003-levitico-014.adoc#v3-14-0[&#60; Capítulo Anterior] | <<v3-15-0,Topo>> | xref:003-levitico/003-levitico-016.adoc#v3-16-0[Próximo Capítulo &#62;]