include::./index.adoc[]

[[v3-21-0]]
=== Levítico, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-21-1]]

^<<v3-21-1,1>>^ Disse o SENHOR a Moisés: Fala aos sacerdotes, filhos de Arão, e dize-lhes: O sacerdote não se contaminará por causa de um morto entre o seu povo,

[[v3-21-2]]

^<<v3-21-2,2>>^ salvo por seu parente mais chegado: por sua mãe, e por seu pai, e por seu filho, e por sua filha, e por seu irmão;

[[v3-21-3]]

^<<v3-21-3,3>>^ e também por sua irmã virgem, chegada a ele, que ainda não teve marido, pode contaminar-se.

[[v3-21-4]]

^<<v3-21-4,4>>^ Ele, sendo homem principal entre o seu povo, não se contaminará, pois que se profanaria.

[[v3-21-5]]

^<<v3-21-5,5>>^ Não farão calva na sua cabeça e não cortarão as extremidades da barba, nem ferirão a sua carne.

[[v3-21-6]]

^<<v3-21-6,6>>^ Santos serão a seu Deus e não profanarão o nome do seu Deus, porque oferecem as ofertas queimadas do SENHOR, o pão de seu Deus; portanto, serão santos.

[[v3-21-7]]

^<<v3-21-7,7>>^ Não tomarão mulher prostituta ou desonrada, nem tomarão mulher repudiada de seu marido, pois o sacerdote é santo a seu Deus.

[[v3-21-8]]

^<<v3-21-8,8>>^ Portanto, o consagrarás, porque oferece o pão do teu Deus. Ele vos será santo, pois eu, o SENHOR que vos santifico, sou santo.

[[v3-21-9]]

^<<v3-21-9,9>>^ Se a filha de um sacerdote se desonra, prostituindo-se, profana a seu pai; será queimada.

[[v3-21-10]]

^<<v3-21-10,10>>^ O sumo sacerdote entre seus irmãos, sobre cuja cabeça foi derramado o óleo da unção, e que for consagrado para vestir as vestes sagradas, não desgrenhará os cabelos, nem rasgará as suas vestes.

[[v3-21-11]]

^<<v3-21-11,11>>^ Não se chegará a cadáver algum, nem se contaminará por causa de seu pai ou de sua mãe.

[[v3-21-12]]

^<<v3-21-12,12>>^ Não sairá do santuário, nem profanará o santuário do seu Deus, pois a consagração do óleo da unção do seu Deus está sobre ele. Eu sou o SENHOR.

[[v3-21-13]]

^<<v3-21-13,13>>^ Ele tomará por mulher uma virgem.

[[v3-21-14]]

^<<v3-21-14,14>>^ Viúva, ou repudiada, ou desonrada, ou prostituta, estas não tomará, mas virgem do seu povo tomará por mulher.

[[v3-21-15]]

^<<v3-21-15,15>>^ E não profanará a sua descendência entre o seu povo, porque eu sou o SENHOR, que o santifico.

[[v3-21-16]]

^<<v3-21-16,16>>^ Disse mais o SENHOR a Moisés:

[[v3-21-17]]

^<<v3-21-17,17>>^ Fala a Arão, dizendo: Ninguém dos teus descendentes, nas suas gerações, em quem houver algum defeito se chegará para oferecer o pão do seu Deus.

[[v3-21-18]]

^<<v3-21-18,18>>^ Pois nenhum homem em quem houver defeito se chegará: como homem cego, ou coxo, ou de rosto mutilado, ou desproporcionado,

[[v3-21-19]]

^<<v3-21-19,19>>^ ou homem que tiver o pé quebrado ou mão quebrada,

[[v3-21-20]]

^<<v3-21-20,20>>^ ou corcovado, ou anão, ou que tiver belida no olho, ou sarna, ou impigens, ou que tiver testículo quebrado.

[[v3-21-21]]

^<<v3-21-21,21>>^ Nenhum homem da descendência de Arão, o sacerdote, em quem houver algum defeito se chegará para oferecer as ofertas queimadas do SENHOR; ele tem defeito; não se chegará para oferecer o pão do seu Deus.

[[v3-21-22]]

^<<v3-21-22,22>>^ Comerá o pão do seu Deus, tanto do santíssimo como do santo.

[[v3-21-23]]

^<<v3-21-23,23>>^ Porém até ao véu não entrará, nem se chegará ao altar, porque tem defeito, para que não profane os meus santuários, porque eu sou o SENHOR, que os santifico.

[[v3-21-24]]

^<<v3-21-24,24>>^ Assim falou Moisés a Arão, aos filhos deste e a todos os filhos de Israel.

'''

xref:003-levitico/003-levitico-020.adoc#v3-20-0[&#60; Capítulo Anterior] | <<v3-21-0,Topo>> | xref:003-levitico/003-levitico-022.adoc#v3-22-0[Próximo Capítulo &#62;]