include::./index.adoc[]

[[v3-12-0]]
=== Levítico, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-12-1]]

^<<v3-12-1,1>>^ Disse mais o SENHOR a Moisés:

[[v3-12-2]]

^<<v3-12-2,2>>^ Fala aos filhos de Israel: Se uma mulher conceber e tiver um menino, será imunda sete dias; como nos dias da sua menstruação, será imunda.

[[v3-12-3]]

^<<v3-12-3,3>>^ E, no oitavo dia, se circuncidará ao menino a carne do seu prepúcio.

[[v3-12-4]]

^<<v3-12-4,4>>^ Depois, ficará ela trinta e três dias a purificar-se do seu sangue; nenhuma coisa santa tocará, nem entrará no santuário até que se cumpram os dias da sua purificação.

[[v3-12-5]]

^<<v3-12-5,5>>^ Mas, se tiver uma menina, será imunda duas semanas, como na sua menstruação; depois, ficará sessenta e seis dias a purificar-se do seu sangue.

[[v3-12-6]]

^<<v3-12-6,6>>^ E, cumpridos os dias da sua purificação por filho ou filha, trará ao sacerdote um cordeiro de um ano, por holocausto, e um pombinho ou uma rola, por oferta pelo pecado, à porta da tenda da congregação;

[[v3-12-7]]

^<<v3-12-7,7>>^ o sacerdote o oferecerá perante o SENHOR e, pela mulher, fará expiação; e ela será purificada do fluxo do seu sangue; esta é a lei da que der à luz menino ou menina.

[[v3-12-8]]

^<<v3-12-8,8>>^ Mas, se as suas posses não lhe permitirem trazer um cordeiro, tomará, então, duas rolas ou dois pombinhos, um para o holocausto e o outro para a oferta pelo pecado; assim, o sacerdote fará expiação pela mulher, e será limpa.

'''

xref:003-levitico/003-levitico-011.adoc#v3-11-0[&#60; Capítulo Anterior] | <<v3-12-0,Topo>> | xref:003-levitico/003-levitico-013.adoc#v3-13-0[Próximo Capítulo &#62;]