include::./index.adoc[]

[[v3-19-0]]
=== Levítico, 19
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-19-1]]

^<<v3-19-1,1>>^ Disse o SENHOR a Moisés:

[[v3-19-2]]

^<<v3-19-2,2>>^ Fala a toda a congregação dos filhos de Israel e dize-lhes: Santos sereis, porque eu, o SENHOR, vosso Deus, sou santo.

[[v3-19-3]]

^<<v3-19-3,3>>^ Cada um respeitará a sua mãe e o seu pai e guardará os meus sábados. Eu sou o SENHOR, vosso Deus.

[[v3-19-4]]

^<<v3-19-4,4>>^ Não vos virareis para os ídolos, nem vos fareis deuses de fundição. Eu sou o SENHOR, vosso Deus.

[[v3-19-5]]

^<<v3-19-5,5>>^ Quando oferecerdes sacrifício pacífico ao SENHOR, oferecê-lo-eis para que sejais aceitos.

[[v3-19-6]]

^<<v3-19-6,6>>^ No dia em que o oferecerdes e no dia seguinte, se comerá; mas o que sobejar, ao terceiro dia, será queimado.

[[v3-19-7]]

^<<v3-19-7,7>>^ Se alguma coisa dele for comida ao terceiro dia, é abominação; não será aceita.

[[v3-19-8]]

^<<v3-19-8,8>>^ Qualquer que o comer levará a sua iniquidade, porquanto profanou coisa santa do SENHOR; por isso, será eliminado do seu povo.

[[v3-19-9]]

^<<v3-19-9,9>>^ Quando também segares a messe da tua terra, o canto do teu campo não segarás totalmente, nem as espigas caídas colherás da tua messe.

[[v3-19-10]]

^<<v3-19-10,10>>^ Não rebuscarás a tua vinha, nem colherás os bagos caídos da tua vinha; deixá-los-ás ao pobre e ao estrangeiro. Eu sou o SENHOR, vosso Deus.

[[v3-19-11]]

^<<v3-19-11,11>>^ Não furtareis, nem mentireis, nem usareis de falsidade cada um com o seu próximo;

[[v3-19-12]]

^<<v3-19-12,12>>^ nem jurareis falso pelo meu nome, pois profanaríeis o nome do vosso Deus. Eu sou o SENHOR.

[[v3-19-13]]

^<<v3-19-13,13>>^ Não oprimirás o teu próximo, nem o roubarás; a paga do jornaleiro não ficará contigo até pela manhã.

[[v3-19-14]]

^<<v3-19-14,14>>^ Não amaldiçoarás o surdo, nem porás tropeço diante do cego; mas temerás o teu Deus. Eu sou o SENHOR.

[[v3-19-15]]

^<<v3-19-15,15>>^ Não farás injustiça no juízo, nem favorecendo o pobre, nem comprazendo ao grande; com justiça julgarás o teu próximo.

[[v3-19-16]]

^<<v3-19-16,16>>^ Não andarás como mexeriqueiro entre o teu povo; não atentarás contra a vida do teu próximo. Eu sou o SENHOR.

[[v3-19-17]]

^<<v3-19-17,17>>^ Não aborrecerás teu irmão no teu íntimo; mas repreenderás o teu próximo e, por causa dele, não levarás sobre ti pecado.

[[v3-19-18]]

^<<v3-19-18,18>>^ Não te vingarás, nem guardarás ira contra os filhos do teu povo; mas amarás o teu próximo como a ti mesmo. Eu sou o SENHOR.

[[v3-19-19]]

^<<v3-19-19,19>>^ Guardarás os meus estatutos; não permitirás que os teus animais se ajuntem com os de espécie diversa; no teu campo, não semearás semente de duas espécies; nem usarás roupa de dois estofos misturados.

[[v3-19-20]]

^<<v3-19-20,20>>^ Se alguém se deitar com uma mulher, se for escrava desposada com outro homem e não for resgatada, nem se lhe houver dado liberdade, então, serão açoitados; não serão mortos, pois não foi libertada.

[[v3-19-21]]

^<<v3-19-21,21>>^ O homem, como oferta pela sua culpa, trará um carneiro ao SENHOR, à porta da tenda da congregação.

[[v3-19-22]]

^<<v3-19-22,22>>^ Com o carneiro da oferta pela culpa, o sacerdote fará expiação, por ele, perante o SENHOR, pelo pecado que cometeu, e ser-lhe-á perdoado o pecado que cometeu.

[[v3-19-23]]

^<<v3-19-23,23>>^ Quando entrardes na terra e plantardes toda sorte de árvore de comer, ser-vos-á vedado o seu fruto; três anos vos será vedado; dele não se comerá.

[[v3-19-24]]

^<<v3-19-24,24>>^ Porém, no quarto ano, todo o seu fruto será santo, será oferta de louvores ao SENHOR.

[[v3-19-25]]

^<<v3-19-25,25>>^ No quinto ano, comereis fruto dela para que vos faça aumentar a sua produção. Eu sou o SENHOR, vosso Deus.

[[v3-19-26]]

^<<v3-19-26,26>>^ Não comereis coisa alguma com sangue; não agourareis, nem adivinhareis.

[[v3-19-27]]

^<<v3-19-27,27>>^ Não cortareis o cabelo em redondo, nem danificareis as extremidades da barba.

[[v3-19-28]]

^<<v3-19-28,28>>^ Pelos mortos não ferireis a vossa carne; nem fareis marca nenhuma sobre vós. Eu sou o SENHOR.

[[v3-19-29]]

^<<v3-19-29,29>>^ Não contaminarás a tua filha, fazendo-a prostituir-se; para que a terra não se prostitua, nem se encha de maldade.

[[v3-19-30]]

^<<v3-19-30,30>>^ Guardareis os meus sábados e reverenciareis o meu santuário. Eu sou o SENHOR.

[[v3-19-31]]

^<<v3-19-31,31>>^ Não vos voltareis para os necromantes, nem para os adivinhos; não os procureis para serdes contaminados por eles. Eu sou o SENHOR, vosso Deus.

[[v3-19-32]]

^<<v3-19-32,32>>^ Diante das cãs te levantarás, e honrarás a presença do ancião, e temerás o teu Deus. Eu sou o SENHOR.

[[v3-19-33]]

^<<v3-19-33,33>>^ Se o estrangeiro peregrinar na vossa terra, não o oprimireis.

[[v3-19-34]]

^<<v3-19-34,34>>^ Como o natural, será entre vós o estrangeiro que peregrina convosco; amá-lo-eis como a vós mesmos, pois estrangeiros fostes na terra do Egito. Eu sou o SENHOR, vosso Deus.

[[v3-19-35]]

^<<v3-19-35,35>>^ Não cometereis injustiça no juízo, nem na vara, nem no peso, nem na medida.

[[v3-19-36]]

^<<v3-19-36,36>>^ Balanças justas, pesos justos, efa justo e justo him tereis. Eu sou o SENHOR, vosso Deus, que vos tirei da terra do Egito.

[[v3-19-37]]

^<<v3-19-37,37>>^ Guardareis todos os meus estatutos e todos os meus juízos e os cumprireis. Eu sou o SENHOR.

'''

xref:003-levitico/003-levitico-018.adoc#v3-18-0[&#60; Capítulo Anterior] | <<v3-19-0,Topo>> | xref:003-levitico/003-levitico-020.adoc#v3-20-0[Próximo Capítulo &#62;]