include::./index.adoc[]

[[v3-24-0]]
=== Levítico, 24
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-24-1]]

^<<v3-24-1,1>>^ Disse o SENHOR a Moisés:

[[v3-24-2]]

^<<v3-24-2,2>>^ Ordena aos filhos de Israel que te tragam azeite puro de oliveira, batido, para o candelabro, para que haja lâmpada acesa continuamente.

[[v3-24-3]]

^<<v3-24-3,3>>^ Na tenda da congregação fora do véu, que está diante do Testemunho, Arão a conservará em ordem, desde a tarde até pela manhã, de contínuo, perante o SENHOR; estatuto perpétuo será este pelas suas gerações.

[[v3-24-4]]

^<<v3-24-4,4>>^ Sobre o candeeiro de ouro puro conservará em ordem as lâmpadas perante o SENHOR, continuamente.

[[v3-24-5]]

^<<v3-24-5,5>>^ Também tomarás da flor de farinha e dela cozerás doze pães, cada um dos quais será de duas dízimas de um efa.

[[v3-24-6]]

^<<v3-24-6,6>>^ E os porás em duas fileiras, seis em cada fileira, sobre a mesa de ouro puro, perante o SENHOR.

[[v3-24-7]]

^<<v3-24-7,7>>^ Sobre cada fileira porás incenso puro, que será, para o pão, como porção memorial; é oferta queimada ao SENHOR.

[[v3-24-8]]

^<<v3-24-8,8>>^ Em cada sábado, Arão os porá em ordem perante o SENHOR, continuamente, da parte dos filhos de Israel, por aliança perpétua.

[[v3-24-9]]

^<<v3-24-9,9>>^ E serão de Arão e de seus filhos, os quais os comerão no lugar santo, porque são coisa santíssima para eles, das ofertas queimadas ao SENHOR, como estatuto perpétuo.

[[v3-24-10]]

^<<v3-24-10,10>>^ Apareceu entre os filhos de Israel o filho de uma israelita, o qual era filho de um egípcio; o filho da israelita e certo homem israelita contenderam no arraial.

[[v3-24-11]]

^<<v3-24-11,11>>^ Então, o filho da mulher israelita blasfemou o nome do SENHOR e o amaldiçoou, pelo que o trouxeram a Moisés. O nome de sua mãe era Selomite, filha de Dibri, da tribo de Dã.

[[v3-24-12]]

^<<v3-24-12,12>>^ E o levaram à prisão, até que se lhes fizesse declaração pela boca do SENHOR.

[[v3-24-13]]

^<<v3-24-13,13>>^ Disse o SENHOR a Moisés:

[[v3-24-14]]

^<<v3-24-14,14>>^ Tira o que blasfemou para fora do arraial; e todos os que o ouviram porão as mãos sobre a cabeça dele, e toda a congregação o apedrejará.

[[v3-24-15]]

^<<v3-24-15,15>>^ Dirás aos filhos de Israel: Qualquer que amaldiçoar o seu Deus levará sobre si o seu pecado.

[[v3-24-16]]

^<<v3-24-16,16>>^ Aquele que blasfemar o nome do SENHOR será morto; toda a congregação o apedrejará; tanto o estrangeiro como o natural, blasfemando o nome do SENHOR, será morto.

[[v3-24-17]]

^<<v3-24-17,17>>^ Quem matar alguém será morto.

[[v3-24-18]]

^<<v3-24-18,18>>^ Mas quem matar um animal o restituirá: igual por igual.

[[v3-24-19]]

^<<v3-24-19,19>>^ Se alguém causar defeito em seu próximo, como ele fez, assim lhe será feito:

[[v3-24-20]]

^<<v3-24-20,20>>^ fratura por fratura, olho por olho, dente por dente; como ele tiver desfigurado a algum homem, assim se lhe fará.

[[v3-24-21]]

^<<v3-24-21,21>>^ Quem matar um animal restituirá outro; quem matar um homem será morto.

[[v3-24-22]]

^<<v3-24-22,22>>^ Uma e a mesma lei havereis, tanto para o estrangeiro como para o natural; pois eu sou o SENHOR, vosso Deus.

[[v3-24-23]]

^<<v3-24-23,23>>^ Então, falou Moisés aos filhos de Israel que levassem o que tinha blasfemado para fora do arraial e o apedrejassem; e os filhos de Israel fizeram como o SENHOR ordenara a Moisés.

'''

xref:003-levitico/003-levitico-023.adoc#v3-23-0[&#60; Capítulo Anterior] | <<v3-24-0,Topo>> | xref:003-levitico/003-levitico-025.adoc#v3-25-0[Próximo Capítulo &#62;]