include::./index.adoc[]

[[v3-7-0]]
=== Levítico, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v3-7-1]]

^<<v3-7-1,1>>^ Esta é a lei da oferta pela culpa; coisa santíssima é.

[[v3-7-2]]

^<<v3-7-2,2>>^ No lugar onde imolam o holocausto, imolarão a oferta pela culpa, e o seu sangue se aspergirá sobre o altar, em redor.

[[v3-7-3]]

^<<v3-7-3,3>>^ Dela se oferecerá toda a gordura, a cauda e a gordura que cobre as entranhas;

[[v3-7-4]]

^<<v3-7-4,4>>^ também ambos os rins e a gordura que neles há, junto aos lombos; e o redenho sobre o fígado com os rins se tirará.

[[v3-7-5]]

^<<v3-7-5,5>>^ O sacerdote o queimará sobre o altar em oferta queimada ao SENHOR; é oferta pela culpa.

[[v3-7-6]]

^<<v3-7-6,6>>^ Todo varão entre os sacerdotes a comerá; no lugar santo, se comerá; coisa santíssima é.

[[v3-7-7]]

^<<v3-7-7,7>>^ Como a oferta pelo pecado, assim será a oferta pela culpa; uma única lei haverá para elas: será do sacerdote que, com ela, fizer expiação.

[[v3-7-8]]

^<<v3-7-8,8>>^ O sacerdote que oferecer o holocausto de alguém terá o couro do holocausto que oferece,

[[v3-7-9]]

^<<v3-7-9,9>>^ como também toda oferta de manjares que se cozer no forno, com tudo que se preparar na frigideira e na assadeira, será do sacerdote que a oferece.

[[v3-7-10]]

^<<v3-7-10,10>>^ Toda oferta de manjares amassada com azeite ou seca será de todos os filhos de Arão, tanto de um como do outro.

[[v3-7-11]]

^<<v3-7-11,11>>^ Esta é a lei das ofertas pacíficas que alguém pode oferecer ao SENHOR.

[[v3-7-12]]

^<<v3-7-12,12>>^ Se fizer por ação de graças, com a oferta de ação de graças trará bolos asmos amassados com azeite, obreias asmas untadas com azeite e bolos de flor de farinha bem amassados com azeite.

[[v3-7-13]]

^<<v3-7-13,13>>^ Com os bolos trará, por sua oferta, pão levedado, com o sacrifício de sua oferta pacífica por ação de graças.

[[v3-7-14]]

^<<v3-7-14,14>>^ E, de toda oferta, trará um bolo por oferta ao SENHOR, que será do sacerdote que aspergir o sangue da oferta pacífica.

[[v3-7-15]]

^<<v3-7-15,15>>^ Mas a carne do sacrifício de ação de graças da sua oferta pacífica se comerá no dia do seu oferecimento; nada se deixará dela até à manhã.

[[v3-7-16]]

^<<v3-7-16,16>>^ E, se o sacrifício da sua oferta for voto ou oferta voluntária, no dia em que oferecer o seu sacrifício, se comerá; e o que dele ficar também se comerá no dia seguinte.

[[v3-7-17]]

^<<v3-7-17,17>>^ Porém o que ainda restar da carne do sacrifício, ao terceiro dia, será queimado.

[[v3-7-18]]

^<<v3-7-18,18>>^ Se da carne do seu sacrifício pacífico se comer ao terceiro dia, aquele que a ofereceu não será aceito, nem lhe será atribuído o sacrifício; coisa abominável será, e a pessoa que dela comer levará a sua iniquidade.

[[v3-7-19]]

^<<v3-7-19,19>>^ A carne que tocar alguma coisa imunda não se comerá; será queimada. Qualquer que estiver limpo comerá a carne do sacrifício.

[[v3-7-20]]

^<<v3-7-20,20>>^ Porém, se alguma pessoa, tendo sobre si imundícia, comer a carne do sacrifício pacífico, que é do SENHOR, será eliminada do seu povo.

[[v3-7-21]]

^<<v3-7-21,21>>^ Se uma pessoa tocar alguma coisa imunda, como imundícia de homem, ou de gado imundo, ou de qualquer réptil imundo e da carne do sacrifício pacífico, que é do SENHOR, ela comer, será eliminada do seu povo.

[[v3-7-22]]

^<<v3-7-22,22>>^ Disse mais o SENHOR a Moisés:

[[v3-7-23]]

^<<v3-7-23,23>>^ Fala aos filhos de Israel, dizendo: Não comereis gordura de boi, nem de carneiro, nem de cabra.

[[v3-7-24]]

^<<v3-7-24,24>>^ A gordura do animal que morre por si mesmo e a do dilacerado por feras podem servir para qualquer outro uso, mas de maneira nenhuma as comereis;

[[v3-7-25]]

^<<v3-7-25,25>>^ porque qualquer que comer a gordura do animal, do qual se trouxer ao SENHOR oferta queimada, será eliminado do seu povo.

[[v3-7-26]]

^<<v3-7-26,26>>^ Não comereis sangue em qualquer das vossas habitações, quer de aves, quer de gado.

[[v3-7-27]]

^<<v3-7-27,27>>^ Toda pessoa que comer algum sangue será eliminada do seu povo.

[[v3-7-28]]

^<<v3-7-28,28>>^ Disse mais o SENHOR a Moisés:

[[v3-7-29]]

^<<v3-7-29,29>>^ Fala aos filhos de Israel, dizendo: Quem oferecer ao SENHOR o seu sacrifício pacífico trará a sua oferta ao SENHOR; do seu sacrifício pacífico

[[v3-7-30]]

^<<v3-7-30,30>>^ trará com suas próprias mãos as ofertas queimadas do SENHOR; a gordura do peito com o peito trará para movê-lo por oferta movida perante o SENHOR.

[[v3-7-31]]

^<<v3-7-31,31>>^ O sacerdote queimará a gordura sobre o altar, porém o peito será de Arão e de seus filhos.

[[v3-7-32]]

^<<v3-7-32,32>>^ Também a coxa direita dareis ao sacerdote por oferta dos vossos sacrifícios pacíficos.

[[v3-7-33]]

^<<v3-7-33,33>>^ Aquele dos filhos de Arão que oferecer o sangue do sacrifício pacífico e a gordura, esse terá a coxa direita por sua porção;

[[v3-7-34]]

^<<v3-7-34,34>>^ porque o peito movido e a coxa da oferta tomei dos filhos de Israel, dos seus sacrifícios pacíficos, e os dei a Arão, o sacerdote, e a seus filhos, por direito perpétuo dos filhos de Israel.

[[v3-7-35]]

^<<v3-7-35,35>>^ Esta é a porção de Arão e a porção de seus filhos, das ofertas queimadas do SENHOR, no dia em que os apresentou para oficiarem como sacerdotes ao SENHOR;

[[v3-7-36]]

^<<v3-7-36,36>>^ a qual o SENHOR ordenou que se lhes desse dentre os filhos de Israel no dia em que os ungiu; estatuto perpétuo é pelas suas gerações.

[[v3-7-37]]

^<<v3-7-37,37>>^ Esta é a lei do holocausto, da oferta de manjares, da oferta pelo pecado, da oferta pela culpa, da consagração e do sacrifício pacífico,

[[v3-7-38]]

^<<v3-7-38,38>>^ que o SENHOR ordenou a Moisés no monte Sinai, no dia em que ordenou aos filhos de Israel que oferecessem as suas ofertas ao SENHOR, no deserto do Sinai.

'''

xref:003-levitico/003-levitico-006.adoc#v3-6-0[&#60; Capítulo Anterior] | <<v3-7-0,Topo>> | xref:003-levitico/003-levitico-008.adoc#v3-8-0[Próximo Capítulo &#62;]