include::./index.adoc[]

[[v28-4-0]]
=== Oséias, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v28-4-1]]

^<<v28-4-1,1>>^ Ouvi a palavra do SENHOR, vós, filhos de Israel, porque o SENHOR tem uma contenda com os habitantes da terra, porque nela não há verdade, nem amor, nem conhecimento de Deus.

[[v28-4-2]]

^<<v28-4-2,2>>^ O que só prevalece é perjurar, mentir, matar, furtar e adulterar, e há arrombamentos e homicídios sobre homicídios.

[[v28-4-3]]

^<<v28-4-3,3>>^ Por isso, a terra está de luto, e todo o que mora nela desfalece, com os animais do campo e com as aves do céu; e até os peixes do mar perecem.

[[v28-4-4]]

^<<v28-4-4,4>>^ Todavia, ninguém contenda, ninguém repreenda; porque o teu povo é como os sacerdotes aos quais acusa.

[[v28-4-5]]

^<<v28-4-5,5>>^ Por isso, tropeçarás de dia, e o profeta contigo tropeçará de noite; e destruirei a tua mãe.

[[v28-4-6]]

^<<v28-4-6,6>>^ O meu povo está sendo destruído, porque lhe falta o conhecimento. Porque tu, sacerdote, rejeitaste o conhecimento, também eu te rejeitarei, para que não sejas sacerdote diante de mim; visto que te esqueceste da lei do teu Deus, também eu me esquecerei de teus filhos.

[[v28-4-7]]

^<<v28-4-7,7>>^ Quanto mais estes se multiplicaram, tanto mais contra mim pecaram; eu mudarei a sua honra em vergonha.

[[v28-4-8]]

^<<v28-4-8,8>>^ Alimentam-se do pecado do meu povo e da maldade dele têm desejo ardente.

[[v28-4-9]]

^<<v28-4-9,9>>^ Por isso, como é o povo, assim é o sacerdote; castigá-lo-ei pelo seu procedimento e lhe darei o pago das suas obras.

[[v28-4-10]]

^<<v28-4-10,10>>^ Comerão, mas não se fartarão; entregar-se-ão à sensualidade, mas não se multiplicarão, porque ao SENHOR deixaram de adorar.

[[v28-4-11]]

^<<v28-4-11,11>>^ A sensualidade, o vinho e o mosto tiram o entendimento.

[[v28-4-12]]

^<<v28-4-12,12>>^ O meu povo consulta o seu pedaço de madeira, e a sua vara lhe dá resposta; porque um espírito de prostituição os enganou, eles, prostituindo-se, abandonaram o seu Deus.

[[v28-4-13]]

^<<v28-4-13,13>>^ Sacrificam sobre o cimo dos montes e queimam incenso sobre os outeiros, debaixo do carvalho, dos choupos e dos terebintos, porque é boa a sua sombra; por isso, vossas filhas se prostituem, e as vossas noras adulteram.

[[v28-4-14]]

^<<v28-4-14,14>>^ Não castigarei vossas filhas, que se prostituem, nem vossas noras, quando adulteram, porque os homens mesmos se retiram com as meretrizes e com as prostitutas cultuais sacrificam, pois o povo que não tem entendimento corre para a sua perdição.

[[v28-4-15]]

^<<v28-4-15,15>>^ Ainda que tu, ó Israel, queres prostituir-te, contudo, não se faça culpado Judá; nem venhais a Gilgal e não subais a Bete-Áven, nem jureis, dizendo: Vive o SENHOR.

[[v28-4-16]]

^<<v28-4-16,16>>^ Como vaca rebelde, se rebelou Israel; será que o SENHOR o apascenta como a um cordeiro em vasta campina?

[[v28-4-17]]

^<<v28-4-17,17>>^ Efraim está entregue aos ídolos; é deixá-lo.

[[v28-4-18]]

^<<v28-4-18,18>>^ Tendo acabado de beber, eles se entregam à prostituição; os seus príncipes amam apaixonadamente a desonra.

[[v28-4-19]]

^<<v28-4-19,19>>^ O vento os envolveu nas suas asas; e envergonhar-se-ão por causa dos seus sacrifícios.

'''

xref:028-oseias/028-oseias-003.adoc#v28-3-0[&#60; Capítulo Anterior] | <<v28-4-0,Topo>> | xref:028-oseias/028-oseias-005.adoc#v28-5-0[Próximo Capítulo &#62;]