include::./index.adoc[]

[[v28-6-0]]
=== Oséias, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v28-6-1]]

^<<v28-6-1,1>>^ Vinde, e tornemos para o SENHOR, porque ele nos despedaçou e nos sarará; fez a ferida e a ligará.

[[v28-6-2]]

^<<v28-6-2,2>>^ Depois de dois dias, nos revigorará; ao terceiro dia, nos levantará, e viveremos diante dele.

[[v28-6-3]]

^<<v28-6-3,3>>^ Conheçamos e prossigamos em conhecer ao SENHOR; como a alva, a sua vinda é certa; e ele descerá sobre nós como a chuva, como chuva serôdia que rega a terra.

[[v28-6-4]]

^<<v28-6-4,4>>^ Que te farei, ó Efraim? Que te farei, ó Judá? Porque o vosso amor é como a nuvem da manhã e como o orvalho da madrugada, que cedo passa.

[[v28-6-5]]

^<<v28-6-5,5>>^ Por isso, os abati por meio dos profetas; pela palavra da minha boca, os matei; e os meus juízos sairão como a luz.

[[v28-6-6]]

^<<v28-6-6,6>>^ Pois misericórdia quero, e não sacrifício, e o conhecimento de Deus, mais do que holocaustos.

[[v28-6-7]]

^<<v28-6-7,7>>^ Mas eles transgrediram a aliança, como Adão; eles se portaram aleivosamente contra mim.

[[v28-6-8]]

^<<v28-6-8,8>>^ Gileade é a cidade dos que praticam a injustiça, manchada de sangue.

[[v28-6-9]]

^<<v28-6-9,9>>^ Como hordas de salteadores que espreitam alguém, assim é a companhia dos sacerdotes, pois matam no caminho para Siquém; praticam abominações.

[[v28-6-10]]

^<<v28-6-10,10>>^ Vejo uma coisa horrenda na casa de Israel: ali está a prostituição de Efraim; Israel está contaminado.

[[v28-6-11]]

^<<v28-6-11,11>>^ Também tu, ó Judá, serás ceifado.

'''

xref:028-oseias/028-oseias-005.adoc#v28-5-0[&#60; Capítulo Anterior] | <<v28-6-0,Topo>> | xref:028-oseias/028-oseias-007.adoc#v28-7-0[Próximo Capítulo &#62;]