include::./index.adoc[]

[[v28-1-0]]
=== Oséias, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v28-1-1]]

^<<v28-1-1,1>>^ Palavra do SENHOR, que foi dirigida a Oseias, filho de Beeri, nos dias de Uzias, Jotão, Acaz e Ezequias, reis de Judá, e nos dias de Jeroboão, filho de Joás, rei de Israel.

[[v28-1-2]]

^<<v28-1-2,2>>^ Quando, pela primeira vez, falou o SENHOR por intermédio de Oseias, então, o SENHOR lhe disse: Vai, toma uma mulher de prostituições e terás filhos de prostituição, porque a terra se prostituiu, desviando-se do SENHOR.

[[v28-1-3]]

^<<v28-1-3,3>>^ Foi-se, pois, e tomou a Gômer, filha de Diblaim, e ela concebeu e lhe deu um filho.

[[v28-1-4]]

^<<v28-1-4,4>>^ Disse-lhe o SENHOR: Põe-lhe o nome de Jezreel, porque, daqui a pouco, castigarei, pelo sangue de Jezreel, a casa de Jeú e farei cessar o reino da casa de Israel.

[[v28-1-5]]

^<<v28-1-5,5>>^ Naquele dia, quebrarei o arco de Israel no vale de Jezreel.

[[v28-1-6]]

^<<v28-1-6,6>>^ Tornou ela a conceber e deu à luz uma filha. Disse o SENHOR a Oseias: Põe-lhe o nome de Desfavorecida, porque eu não mais tornarei a favorecer a casa de Israel, para lhe perdoar.

[[v28-1-7]]

^<<v28-1-7,7>>^ Porém da casa de Judá me compadecerei e os salvarei pelo SENHOR, seu Deus, pois não os salvarei pelo arco, nem pela espada, nem pela guerra, nem pelos cavalos, nem pelos cavaleiros.

[[v28-1-8]]

^<<v28-1-8,8>>^ Depois de haver desmamado a Desfavorecida, concebeu e deu à luz um filho.

[[v28-1-9]]

^<<v28-1-9,9>>^ Disse o SENHOR a Oseias: Põe-lhe o nome de Não-Meu-Povo, porque vós não sois meu povo, nem eu serei vosso Deus.

[[v28-1-10]]

^<<v28-1-10,10>>^ Todavia, o número dos filhos de Israel será como a areia do mar, que se não pode medir, nem contar; e acontecerá que, no lugar onde se lhes dizia: Vós não sois meu povo, se lhes dirá: Vós sois filhos do Deus vivo.

[[v28-1-11]]

^<<v28-1-11,11>>^ Os filhos de Judá e os filhos de Israel se congregarão, e constituirão sobre si uma só cabeça, e subirão da terra, porque grande será o dia de Jezreel.

'''

xref:027-daniel/027-daniel-012.adoc#v27-12-0[&#60; Capítulo Anterior] | <<v28-1-0,Topo>> | xref:028-oseias/028-oseias-002.adoc#v28-2-0[Próximo Capítulo &#62;]