include::./index.adoc[]

[[v28-8-0]]
=== Oséias, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v28-8-1]]

^<<v28-8-1,1>>^ Emboca a trombeta! Ele vem como a águia contra a casa do SENHOR, porque transgrediram a minha aliança e se rebelaram contra a minha lei.

[[v28-8-2]]

^<<v28-8-2,2>>^ A mim, me invocam: Nosso Deus! Nós, Israel, te conhecemos.

[[v28-8-3]]

^<<v28-8-3,3>>^ Israel rejeitou o bem; o inimigo o perseguirá.

[[v28-8-4]]

^<<v28-8-4,4>>^ Eles estabeleceram reis, mas não da minha parte; constituíram príncipes, mas eu não o soube; da sua prata e do seu ouro fizeram ídolos para si, para serem destruídos.

[[v28-8-5]]

^<<v28-8-5,5>>^ O teu bezerro, ó Samaria, é rejeitado; a minha ira se acende contra eles; até quando serão eles incapazes da inocência?

[[v28-8-6]]

^<<v28-8-6,6>>^ Porque vem de Israel, é obra de artífice, não é Deus; mas em pedaços será desfeito o bezerro de Samaria.

[[v28-8-7]]

^<<v28-8-7,7>>^ Porque semeiam ventos e segarão tormentas; não haverá seara; a erva não dará farinha; e, se a der, comê-la-ão os estrangeiros.

[[v28-8-8]]

^<<v28-8-8,8>>^ Israel foi devorado; agora, está entre as nações como coisa de que ninguém se agrada,

[[v28-8-9]]

^<<v28-8-9,9>>^ porque subiram à Assíria; o jumento montês anda solitário, mas Efraim mercou amores.

[[v28-8-10]]

^<<v28-8-10,10>>^ Todavia, ainda que eles merquem socorros entre as nações, eu os congregarei; já começaram a ser diminuídos por causa da opressão do rei e dos príncipes.

[[v28-8-11]]

^<<v28-8-11,11>>^ Porquanto Efraim multiplicou altares para pecar, estes lhe foram para pecar.

[[v28-8-12]]

^<<v28-8-12,12>>^ Embora eu lhe escreva a minha lei em dez mil preceitos, estes seriam tidos como coisa estranha.

[[v28-8-13]]

^<<v28-8-13,13>>^ Amam o sacrifício; por isso, sacrificam, pois gostam de carne e a comem, mas o SENHOR não os aceita; agora, se lembrará da sua iniquidade e lhes castigará o pecado; eles voltarão para o Egito.

[[v28-8-14]]

^<<v28-8-14,14>>^ Porque Israel se esqueceu do seu Criador e edificou palácios, e Judá multiplicou cidades fortes; mas eu enviarei fogo contra as suas cidades, fogo que consumirá os seus palácios.

'''

xref:028-oseias/028-oseias-007.adoc#v28-7-0[&#60; Capítulo Anterior] | <<v28-8-0,Topo>> | xref:028-oseias/028-oseias-009.adoc#v28-9-0[Próximo Capítulo &#62;]