include::./index.adoc[]

[[v28-5-0]]
=== Oséias, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v28-5-1]]

^<<v28-5-1,1>>^ Ouvi isto, ó sacerdotes; escutai, ó casa de Israel; e dai ouvidos, ó casa do rei, porque este juízo é contra vós outros, visto que fostes um laço em Mispa e rede estendida sobre o Tabor.

[[v28-5-2]]

^<<v28-5-2,2>>^ Na prática de excessos, vos aprofundastes; mas eu castigarei a todos eles.

[[v28-5-3]]

^<<v28-5-3,3>>^ Conheço a Efraim, e Israel não me está oculto; porque, agora, te tens prostituído, ó Efraim, e Israel está contaminado.

[[v28-5-4]]

^<<v28-5-4,4>>^ O seu proceder não lhes permite voltar para o seu Deus, porque um espírito de prostituição está no meio deles, e não conhecem ao SENHOR.

[[v28-5-5]]

^<<v28-5-5,5>>^ A soberba de Israel, abertamente, o acusa; Israel e Efraim cairão por causa da sua iniquidade, e Judá cairá juntamente com eles.

[[v28-5-6]]

^<<v28-5-6,6>>^ Estes irão com os seus rebanhos e o seu gado à procura do SENHOR, porém não o acharão; ele se retirou deles.

[[v28-5-7]]

^<<v28-5-7,7>>^ Aleivosamente se houveram contra o SENHOR, porque geraram filhos bastardos; agora, a Festa da Lua Nova os consumirá com as suas porções.

[[v28-5-8]]

^<<v28-5-8,8>>^ Tocai a trombeta em Gibeá e em Ramá tocai a rebate! Levantai gritos em Bete-Áven! Cuidado, Benjamim!

[[v28-5-9]]

^<<v28-5-9,9>>^ Efraim tornar-se-á assolação no dia do castigo; entre as tribos de Israel, tornei conhecido o que se cumprirá.

[[v28-5-10]]

^<<v28-5-10,10>>^ Os príncipes de Judá são como os que mudam os marcos; derramarei, pois, o meu furor sobre eles como água.

[[v28-5-11]]

^<<v28-5-11,11>>^ Efraim está oprimido e quebrantado pelo castigo, porque foi do seu agrado andar após a vaidade.

[[v28-5-12]]

^<<v28-5-12,12>>^ Portanto, para Efraim serei como a traça e para a casa de Judá, como a podridão.

[[v28-5-13]]

^<<v28-5-13,13>>^ Quando Efraim viu a sua enfermidade, e Judá, a sua chaga, subiu Efraim à Assíria e se dirigiu ao rei principal, que o acudisse; mas ele não poderá curá-los, nem sarar a sua chaga.

[[v28-5-14]]

^<<v28-5-14,14>>^ Porque para Efraim serei como um leão e como um leãozinho, para a casa de Judá; eu, eu mesmo, os despedaçarei e ir-me-ei embora; arrebatá-los-ei, e não haverá quem os livre.

[[v28-5-15]]

^<<v28-5-15,15>>^ Irei e voltarei para o meu lugar, até que se reconheçam culpados e busquem a minha face; estando eles angustiados, cedo me buscarão, dizendo:

'''

xref:028-oseias/028-oseias-004.adoc#v28-4-0[&#60; Capítulo Anterior] | <<v28-5-0,Topo>> | xref:028-oseias/028-oseias-006.adoc#v28-6-0[Próximo Capítulo &#62;]