include::./index.adoc[]

[[v28-7-0]]
=== Oséias, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v28-7-1]]

^<<v28-7-1,1>>^ Quando me disponho a mudar a sorte do meu povo e a sarar a Israel, se descobre a iniquidade de Efraim, como também a maldade de Samaria, porque praticam a falsidade; por dentro há ladrões, e por fora rouba a horda de salteadores.

[[v28-7-2]]

^<<v28-7-2,2>>^ Não dizem no seu coração que eu me lembro de toda a sua maldade; agora, pois, os seus próprios feitos os cercam; acham-se diante da minha face.

[[v28-7-3]]

^<<v28-7-3,3>>^ Com a sua malícia, alegram ao rei e com as suas mentiras, aos príncipes.

[[v28-7-4]]

^<<v28-7-4,4>>^ Todos eles são adúlteros: semelhantes ao forno aceso pelo padeiro, que somente cessa de atiçar o fogo desde que sovou a massa até que seja levedada.

[[v28-7-5]]

^<<v28-7-5,5>>^ No dia da festa do nosso rei, os príncipes se tornaram doentes com o excitamento do vinho, e ele deu a mão aos escarnecedores.

[[v28-7-6]]

^<<v28-7-6,6>>^ Porque prepararam o coração como um forno, enquanto estão de espreita; toda a noite, dorme o seu furor, mas, pela manhã, arde como labaredas de fogo.

[[v28-7-7]]

^<<v28-7-7,7>>^ Todos eles são quentes como um forno e consomem os seus juízes; todos os seus reis caem; ninguém há, entre eles, que me invoque.

[[v28-7-8]]

^<<v28-7-8,8>>^ Efraim se mistura com os povos e é um pão que não foi virado.

[[v28-7-9]]

^<<v28-7-9,9>>^ Estrangeiros lhe comem a força, e ele não o sabe; também as cãs já se espalham sobre ele, e ele não o sabe.

[[v28-7-10]]

^<<v28-7-10,10>>^ A soberba de Israel, abertamente, o acusa; todavia, não voltam para o SENHOR, seu Deus, nem o buscam em tudo isto.

[[v28-7-11]]

^<<v28-7-11,11>>^ Porque Efraim é como uma pomba enganada, sem entendimento; chamam o Egito e vão para a Assíria.

[[v28-7-12]]

^<<v28-7-12,12>>^ Quando forem, sobre eles estenderei a minha rede e como aves do céu os farei descer; castigá-los-ei, segundo o que eles têm ouvido na sua congregação.

[[v28-7-13]]

^<<v28-7-13,13>>^ Ai deles! Porque fugiram de mim; destruição sobre eles, porque se rebelaram contra mim! Eu os remiria, mas eles falam mentiras contra mim.

[[v28-7-14]]

^<<v28-7-14,14>>^ Não clamam a mim de coração, mas dão uivos nas suas camas; para o trigo e para o vinho se ajuntam, mas contra mim se rebelam.

[[v28-7-15]]

^<<v28-7-15,15>>^ Adestrei e fortaleci os seus braços; no entanto, maquinam contra mim.

[[v28-7-16]]

^<<v28-7-16,16>>^ Eles voltam, mas não para o Altíssimo. Fizeram-se como um arco enganoso; caem à espada os seus príncipes, por causa da insolência da sua língua; este será o seu escárnio na terra do Egito.

'''

xref:028-oseias/028-oseias-006.adoc#v28-6-0[&#60; Capítulo Anterior] | <<v28-7-0,Topo>> | xref:028-oseias/028-oseias-008.adoc#v28-8-0[Próximo Capítulo &#62;]