include::./index.adoc[]

[[v28-10-0]]
=== Oséias, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v28-10-1]]

^<<v28-10-1,1>>^ Israel é vide luxuriante, que dá o fruto; segundo a abundância do seu fruto, assim multiplicou os altares; quanto melhor a terra, tanto mais belas colunas fizeram.

[[v28-10-2]]

^<<v28-10-2,2>>^ O seu coração é falso; por isso, serão culpados; o SENHOR quebrará os seus altares e deitará abaixo as colunas.

[[v28-10-3]]

^<<v28-10-3,3>>^ Agora, pois, dirão eles: Não temos rei, porque não tememos ao SENHOR. E o rei, que faria por nós?

[[v28-10-4]]

^<<v28-10-4,4>>^ Falam palavras vãs, jurando falsamente, fazendo aliança; por isso, brota o juízo como erva venenosa nos sulcos dos campos.

[[v28-10-5]]

^<<v28-10-5,5>>^ Os moradores de Samaria serão atemorizados por causa do bezerro de Bete-Áven; o seu povo se lamentará por causa dele, e os sacerdotes idólatras tremerão por causa da sua glória, que já se foi.

[[v28-10-6]]

^<<v28-10-6,6>>^ Também o bezerro será levado à Assíria como presente ao rei principal; Efraim se cobrirá de vexame, e Israel se envergonhará por causa de seu próprio capricho.

[[v28-10-7]]

^<<v28-10-7,7>>^ O rei de Samaria será como lasca de madeira na superfície da água.

[[v28-10-8]]

^<<v28-10-8,8>>^ E os altos de Áven, pecado de Israel, serão destruídos; espinheiros e abrolhos crescerão sobre os seus altares; e aos montes se dirá: Cobri-nos! E aos outeiros: Caí sobre nós!

[[v28-10-9]]

^<<v28-10-9,9>>^ Desde os dias de Gibeá, pecaste, ó Israel, e nisto permaneceste. A peleja contra os filhos da perversidade não há de alcançar-te em Gibeá?

[[v28-10-10]]

^<<v28-10-10,10>>^ Castigarei o povo na medida do meu desejo; e congregar-se-ão contra eles os povos, quando eu o punir por causa de sua dupla transgressão.

[[v28-10-11]]

^<<v28-10-11,11>>^ Porque Efraim era uma bezerra domada, que gostava de trilhar; coloquei o jugo sobre a formosura do seu pescoço; atrelei Efraim ao carro. Judá lavrará, Jacó lhe desfará os torrões.

[[v28-10-12]]

^<<v28-10-12,12>>^ Então, eu disse: semeai para vós outros em justiça, ceifai segundo a misericórdia; arai o campo de pousio; porque é tempo de buscar ao SENHOR, até que ele venha, e chova a justiça sobre vós.

[[v28-10-13]]

^<<v28-10-13,13>>^ Arastes a malícia, colhestes a perversidade; comestes o fruto da mentira, porque confiastes nos vossos carros e na multidão dos vossos valentes.

[[v28-10-14]]

^<<v28-10-14,14>>^ Portanto, entre o teu povo se levantará tumulto de guerra, e todas as tuas fortalezas serão destruídas, como Salmã destruiu a Bete-Arbel no dia da guerra; as mães ali foram despedaçadas com seus filhos.

[[v28-10-15]]

^<<v28-10-15,15>>^ Assim vos fará Betel, por causa da vossa grande malícia; como passa a alva, assim será o rei de Israel totalmente destruído.

'''

xref:028-oseias/028-oseias-009.adoc#v28-9-0[&#60; Capítulo Anterior] | <<v28-10-0,Topo>> | xref:028-oseias/028-oseias-011.adoc#v28-11-0[Próximo Capítulo &#62;]