include::./index.adoc[]

[[v28-3-0]]
=== Oséias, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v28-3-1]]

^<<v28-3-1,1>>^ Disse-me o SENHOR: Vai outra vez, ama uma mulher, amada de seu amigo e adúltera, como o SENHOR ama os filhos de Israel, embora eles olhem para outros deuses e amem bolos de passas.

[[v28-3-2]]

^<<v28-3-2,2>>^ Comprei-a, pois, para mim por quinze peças de prata e um ômer e meio de cevada;

[[v28-3-3]]

^<<v28-3-3,3>>^ e lhe disse: tu esperarás por mim muitos dias; não te prostituirás, nem serás de outro homem; assim também eu esperarei por ti.

[[v28-3-4]]

^<<v28-3-4,4>>^ Porque os filhos de Israel ficarão por muitos dias sem rei, sem príncipe, sem sacrifício, sem coluna, sem estola sacerdotal ou ídolos do lar.

[[v28-3-5]]

^<<v28-3-5,5>>^ Depois, tornarão os filhos de Israel, e buscarão ao SENHOR, seu Deus, e a Davi, seu rei; e, nos últimos dias, tremendo, se aproximarão do SENHOR e da sua bondade.

'''

xref:028-oseias/028-oseias-002.adoc#v28-2-0[&#60; Capítulo Anterior] | <<v28-3-0,Topo>> | xref:028-oseias/028-oseias-004.adoc#v28-4-0[Próximo Capítulo &#62;]