include::./index.adoc[]

[[v28-9-0]]
=== Oséias, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v28-9-1]]

^<<v28-9-1,1>>^ Não te alegres, ó Israel, não exultes, como os povos; porque, com prostituir-te, abandonaste o teu Deus, amaste a paga de prostituição em todas as eiras de cereais.

[[v28-9-2]]

^<<v28-9-2,2>>^ A eira e o lagar não os manterão; e o vinho novo lhes faltará.

[[v28-9-3]]

^<<v28-9-3,3>>^ Na terra do SENHOR, não permanecerão; mas Efraim tornará ao Egito e na Assíria comerá coisa imunda.

[[v28-9-4]]

^<<v28-9-4,4>>^ Não derramarão libações de vinho ao SENHOR, nem os seus sacrifícios lhe serão agradáveis; seu pão será como pão de pranteadores, todos os que dele comerem serão imundos; porque o seu pão será exclusivamente para eles e não entrará na Casa do SENHOR.

[[v28-9-5]]

^<<v28-9-5,5>>^ Que fareis vós no dia da solenidade e no dia da festa do SENHOR?

[[v28-9-6]]

^<<v28-9-6,6>>^ Porque eis que eles se foram por causa da destruição, mas o Egito os ceifará, Mênfis os sepultará; as preciosidades da sua prata, as urtigas as possuirão; espinhos crescerão nas suas moradas.

[[v28-9-7]]

^<<v28-9-7,7>>^ Chegaram os dias do castigo, chegaram os dias da retribuição; Israel o saberá; o seu profeta é um insensato, o homem de espírito é um louco, por causa da abundância da tua iniquidade, ó Israel, e o muito do teu ódio.

[[v28-9-8]]

^<<v28-9-8,8>>^ O profeta é sentinela contra Efraim, ao lado de meu Deus, laço do passarinheiro em todos os seus caminhos e inimizade na casa do seu Deus.

[[v28-9-9]]

^<<v28-9-9,9>>^ Mui profundamente se corromperam, como nos dias de Gibeá. O SENHOR se lembrará das suas injustiças e castigará os pecados deles.

[[v28-9-10]]

^<<v28-9-10,10>>^ Achei a Israel como uvas no deserto, vi a vossos pais como as primícias da figueira nova; mas eles foram para Baal-Peor, e se consagraram à vergonhosa idolatria, e se tornaram abomináveis como aquilo que amaram.

[[v28-9-11]]

^<<v28-9-11,11>>^ Quanto a Efraim, a sua glória voará como ave; não haverá nascimento, nem gravidez, nem concepção.

[[v28-9-12]]

^<<v28-9-12,12>>^ Ainda que venham a criar seus filhos, eu os privarei deles, para que não fique nenhum homem. Ai deles, quando deles me apartar!

[[v28-9-13]]

^<<v28-9-13,13>>^ Efraim, como planejei, seria como Tiro, plantado num lugar aprazível; mas Efraim levará seus filhos ao matador.

[[v28-9-14]]

^<<v28-9-14,14>>^ Dá-lhes, ó SENHOR; que lhes darás? Dá-lhes um ventre estéril e seios secos.

[[v28-9-15]]

^<<v28-9-15,15>>^ Toda a sua malícia se acha em Gilgal, porque ali passei a aborrecê-los; por causa da maldade das suas obras, os lançarei fora de minha casa; já não os amarei; todos os seus príncipes são rebeldes.

[[v28-9-16]]

^<<v28-9-16,16>>^ Ferido está Efraim, secaram-se as suas raízes; não dará fruto; ainda que gere filhos, eu matarei os mais queridos do seu ventre.

[[v28-9-17]]

^<<v28-9-17,17>>^ O meu Deus os rejeitará, porque não o ouvem; e andarão errantes entre as nações.

'''

xref:028-oseias/028-oseias-008.adoc#v28-8-0[&#60; Capítulo Anterior] | <<v28-9-0,Topo>> | xref:028-oseias/028-oseias-010.adoc#v28-10-0[Próximo Capítulo &#62;]