include::./index.adoc[]

[[v28-2-0]]
=== Oséias, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v28-2-1]]

^<<v28-2-1,1>>^ Chamai a vosso irmão Meu-Povo e a vossa irmã, Favor.

[[v28-2-2]]

^<<v28-2-2,2>>^ Repreendei vossa mãe, repreendei-a, porque ela não é minha mulher, e eu não sou seu marido, para que ela afaste as suas prostituições de sua presença e os seus adultérios de entre os seus seios;

[[v28-2-3]]

^<<v28-2-3,3>>^ para que eu não a deixe despida, e a ponha como no dia em que nasceu, e a torne semelhante a um deserto, e a faça como terra seca, e a mate à sede,

[[v28-2-4]]

^<<v28-2-4,4>>^ e não me compadeça de seus filhos, porque são filhos de prostituições.

[[v28-2-5]]

^<<v28-2-5,5>>^ Pois sua mãe se prostituiu; aquela que os concebeu houve-se torpemente, porque diz: Irei atrás de meus amantes, que me dão o meu pão e a minha água, a minha lã e o meu linho, o meu óleo e as minhas bebidas.

[[v28-2-6]]

^<<v28-2-6,6>>^ Portanto, eis que cercarei o seu caminho com espinhos; e levantarei um muro contra ela, para que ela não ache as suas veredas.

[[v28-2-7]]

^<<v28-2-7,7>>^ Ela irá em seguimento de seus amantes, porém não os alcançará; buscá-los-á, sem, contudo, os achar; então, dirá: Irei e tornarei para o meu primeiro marido, porque melhor me ia então do que agora.

[[v28-2-8]]

^<<v28-2-8,8>>^ Ela, pois, não soube que eu é que lhe dei o trigo, e o vinho, e o óleo, e lhe multipliquei a prata e o ouro, que eles usaram para Baal.

[[v28-2-9]]

^<<v28-2-9,9>>^ Portanto, tornar-me-ei, e reterei, a seu tempo, o meu trigo e o meu vinho, e arrebatarei a minha lã e o meu linho, que lhe deviam cobrir a nudez.

[[v28-2-10]]

^<<v28-2-10,10>>^ Agora, descobrirei as suas vergonhas aos olhos dos seus amantes, e ninguém a livrará da minha mão.

[[v28-2-11]]

^<<v28-2-11,11>>^ Farei cessar todo o seu gozo, as suas Festas de Lua Nova, os seus sábados e todas as suas solenidades.

[[v28-2-12]]

^<<v28-2-12,12>>^ Devastarei a sua vide e a sua figueira, de que ela diz: Esta é a paga que me deram os meus amantes; eu, pois, farei delas um bosque, e as bestas-feras do campo as devorarão.

[[v28-2-13]]

^<<v28-2-13,13>>^ Castigá-la-ei pelos dias dos baalins, nos quais lhes queimou incenso, e se adornou com as suas arrecadas e com as suas joias, e andou atrás de seus amantes, mas de mim se esqueceu, diz o SENHOR.

[[v28-2-14]]

^<<v28-2-14,14>>^ Portanto, eis que eu a atrairei, e a levarei para o deserto, e lhe falarei ao coração.

[[v28-2-15]]

^<<v28-2-15,15>>^ E lhe darei, dali, as suas vinhas e o vale de Acor por porta de esperança; será ela obsequiosa como nos dias da sua mocidade e como no dia em que subiu da terra do Egito.

[[v28-2-16]]

^<<v28-2-16,16>>^ Naquele dia, diz o SENHOR, ela me chamará: Meu marido e já não me chamará: Meu Baal.

[[v28-2-17]]

^<<v28-2-17,17>>^ Da sua boca tirarei os nomes dos baalins, e não mais se lembrará desses nomes.

[[v28-2-18]]

^<<v28-2-18,18>>^ Naquele dia, farei a favor dela aliança com as bestas-feras do campo, e com as aves do céu, e com os répteis da terra; e tirarei desta o arco, e a espada, e a guerra e farei o meu povo repousar em segurança.

[[v28-2-19]]

^<<v28-2-19,19>>^ Desposar-te-ei comigo para sempre; desposar-te-ei comigo em justiça, e em juízo, e em benignidade, e em misericórdias;

[[v28-2-20]]

^<<v28-2-20,20>>^ desposar-te-ei comigo em fidelidade, e conhecerás ao SENHOR.

[[v28-2-21]]

^<<v28-2-21,21>>^ Naquele dia, eu serei obsequioso, diz o SENHOR, obsequioso aos céus, e estes, à terra;

[[v28-2-22]]

^<<v28-2-22,22>>^ a terra, obsequiosa ao trigo, e ao vinho, e ao óleo; e estes, a Jezreel.

[[v28-2-23]]

^<<v28-2-23,23>>^ Semearei Israel para mim na terra e compadecer-me-ei da Desfavorecida; e a Não-Meu-Povo direi: Tu és o meu povo! Ele dirá: Tu és o meu Deus!

'''

xref:028-oseias/028-oseias-001.adoc#v28-1-0[&#60; Capítulo Anterior] | <<v28-2-0,Topo>> | xref:028-oseias/028-oseias-003.adoc#v28-3-0[Próximo Capítulo &#62;]