include::./index.adoc[]

[[v41-14-0]]
=== Marcos, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v41-14-1]]

^<<v41-14-1,1>>^ Dali a dois dias, era a Páscoa e a Festa dos Pães Asmos; e os principais sacerdotes e os escribas procuravam como o prenderiam, à traição, e o matariam.

[[v41-14-2]]

^<<v41-14-2,2>>^ Pois diziam: Não durante a festa, para que não haja tumulto entre o povo.

[[v41-14-3]]

^<<v41-14-3,3>>^ Estando ele em Betânia, reclinado à mesa, em casa de Simão, o leproso, veio uma mulher trazendo um vaso de alabastro com preciosíssimo perfume de nardo puro; e, quebrando o alabastro, derramou o bálsamo sobre a cabeça de Jesus.

[[v41-14-4]]

^<<v41-14-4,4>>^ Indignaram-se alguns entre si e diziam: Para que este desperdício de bálsamo?

[[v41-14-5]]

^<<v41-14-5,5>>^ Porque este perfume poderia ser vendido por mais de trezentos denários e dar-se aos pobres. E murmuravam contra ela.

[[v41-14-6]]

^<<v41-14-6,6>>^ Mas Jesus disse: Deixai-a; por que a molestais? Ela praticou boa ação para comigo.

[[v41-14-7]]

^<<v41-14-7,7>>^ Porque os pobres, sempre os tendes convosco e, quando quiserdes, podeis fazer-lhes bem, mas a mim nem sempre me tendes.

[[v41-14-8]]

^<<v41-14-8,8>>^ Ela fez o que pôde: antecipou-se a ungir-me para a sepultura.

[[v41-14-9]]

^<<v41-14-9,9>>^ Em verdade vos digo: onde for pregado em todo o mundo o evangelho, será também contado o que ela fez, para memória sua.

[[v41-14-10]]

^<<v41-14-10,10>>^ E Judas Iscariotes, um dos doze, foi ter com os principais sacerdotes, para lhes entregar Jesus.

[[v41-14-11]]

^<<v41-14-11,11>>^ Eles, ouvindo-o, alegraram-se e lhe prometeram dinheiro; nesse meio tempo, buscava ele uma boa ocasião para o entregar.

[[v41-14-12]]

^<<v41-14-12,12>>^ E, no primeiro dia da Festa dos Pães Asmos, quando se fazia o sacrifício do cordeiro pascal, disseram-lhe seus discípulos: Onde queres que vamos fazer os preparativos para comeres a Páscoa?

[[v41-14-13]]

^<<v41-14-13,13>>^ Então, enviou dois dos seus discípulos, dizendo-lhes: Ide à cidade, e vos sairá ao encontro um homem trazendo um cântaro de água;

[[v41-14-14]]

^<<v41-14-14,14>>^ segui-o e dizei ao dono da casa onde ele entrar que o Mestre pergunta: Onde é o meu aposento no qual hei de comer a Páscoa com os meus discípulos?

[[v41-14-15]]

^<<v41-14-15,15>>^ E ele vos mostrará um espaçoso cenáculo mobilado e pronto; ali fazei os preparativos.

[[v41-14-16]]

^<<v41-14-16,16>>^ Saíram, pois, os discípulos, foram à cidade e, achando tudo como Jesus lhes tinha dito, prepararam a Páscoa.

[[v41-14-17]]

^<<v41-14-17,17>>^ Ao cair da tarde, foi com os doze.

[[v41-14-18]]

^<<v41-14-18,18>>^ Quando estavam à mesa e comiam, disse Jesus: Em verdade vos digo que um dentre vós, o que come comigo, me trairá.

[[v41-14-19]]

^<<v41-14-19,19>>^ E eles começaram a entristecer-se e a dizer-lhe, um após outro: Porventura, sou eu?

[[v41-14-20]]

^<<v41-14-20,20>>^ Respondeu-lhes: É um dos doze, o que mete comigo a mão no prato.

[[v41-14-21]]

^<<v41-14-21,21>>^ Pois o Filho do Homem vai, como está escrito a seu respeito; mas ai daquele por intermédio de quem o Filho do Homem está sendo traído! Melhor lhe fora não haver nascido!

[[v41-14-22]]

^<<v41-14-22,22>>^ E, enquanto comiam, tomou Jesus um pão e, abençoando-o, o partiu e lhes deu, dizendo: Tomai, isto é o meu corpo.

[[v41-14-23]]

^<<v41-14-23,23>>^ A seguir, tomou Jesus um cálice e, tendo dado graças, o deu aos seus discípulos; e todos beberam dele.

[[v41-14-24]]

^<<v41-14-24,24>>^ Então, lhes disse: Isto é o meu sangue, o sangue da [nova] aliança, derramado em favor de muitos.

[[v41-14-25]]

^<<v41-14-25,25>>^ Em verdade vos digo que jamais beberei do fruto da videira, até àquele dia em que o hei de beber, novo, no reino de Deus.

[[v41-14-26]]

^<<v41-14-26,26>>^ Tendo cantado um hino, saíram para o monte das Oliveiras.

[[v41-14-27]]

^<<v41-14-27,27>>^ Então, lhes disse Jesus: Todos vós vos escandalizareis, porque está escrito: Ferirei o pastor, e as ovelhas ficarão dispersas.

[[v41-14-28]]

^<<v41-14-28,28>>^ Mas, depois da minha ressurreição, irei adiante de vós para a Galileia.

[[v41-14-29]]

^<<v41-14-29,29>>^ Disse-lhe Pedro: Ainda que todos se escandalizem, eu, jamais!

[[v41-14-30]]

^<<v41-14-30,30>>^ Respondeu-lhe Jesus: Em verdade te digo que hoje, nesta noite, antes que duas vezes cante o galo, tu me negarás três vezes.

[[v41-14-31]]

^<<v41-14-31,31>>^ Mas ele insistia com mais veemência: Ainda que me seja necessário morrer contigo, de nenhum modo te negarei. Assim disseram todos.

[[v41-14-32]]

^<<v41-14-32,32>>^ Então, foram a um lugar chamado Getsêmani; ali chegados, disse Jesus a seus discípulos: Assentai-vos aqui, enquanto eu vou orar.

[[v41-14-33]]

^<<v41-14-33,33>>^ E, levando consigo a Pedro, Tiago e João, começou a sentir-se tomado de pavor e de angústia.

[[v41-14-34]]

^<<v41-14-34,34>>^ E lhes disse: A minha alma está profundamente triste até à morte; ficai aqui e vigiai.

[[v41-14-35]]

^<<v41-14-35,35>>^ E, adiantando-se um pouco, prostrou-se em terra; e orava para que, se possível, lhe fosse poupada aquela hora.

[[v41-14-36]]

^<<v41-14-36,36>>^ E dizia: Aba, Pai, tudo te é possível; passa de mim este cálice; contudo, não seja o que eu quero, e sim o que tu queres.

[[v41-14-37]]

^<<v41-14-37,37>>^ Voltando, achou-os dormindo; e disse a Pedro: Simão, tu dormes? Não pudeste vigiar nem uma hora?

[[v41-14-38]]

^<<v41-14-38,38>>^ Vigiai e orai, para que não entreis em tentação; o espírito, na verdade, está pronto, mas a carne é fraca.

[[v41-14-39]]

^<<v41-14-39,39>>^ Retirando-se de novo, orou repetindo as mesmas palavras.

[[v41-14-40]]

^<<v41-14-40,40>>^ Voltando, achou-os outra vez dormindo, porque os seus olhos estavam pesados; e não sabiam o que lhe responder.

[[v41-14-41]]

^<<v41-14-41,41>>^ E veio pela terceira vez e disse-lhes: Ainda dormis e repousais! Basta! Chegou a hora; o Filho do Homem está sendo entregue nas mãos dos pecadores.

[[v41-14-42]]

^<<v41-14-42,42>>^ Levantai-vos, vamos! Eis que o traidor se aproxima.

[[v41-14-43]]

^<<v41-14-43,43>>^ E logo, falava ele ainda, quando chegou Judas, um dos doze, e com ele, vinda da parte dos principais sacerdotes, escribas e anciãos, uma turba com espadas e porretes.

[[v41-14-44]]

^<<v41-14-44,44>>^ Ora, o traidor tinha-lhes dado esta senha: Aquele a quem eu beijar, é esse; prendei-o e levai-o com segurança.

[[v41-14-45]]

^<<v41-14-45,45>>^ E, logo que chegou, aproximando-se, disse-lhe: Mestre! E o beijou.

[[v41-14-46]]

^<<v41-14-46,46>>^ Então, lhe deitaram as mãos e o prenderam.

[[v41-14-47]]

^<<v41-14-47,47>>^ Nisto, um dos circunstantes, sacando da espada, feriu o servo do sumo sacerdote e cortou-lhe a orelha.

[[v41-14-48]]

^<<v41-14-48,48>>^ Disse-lhes Jesus: Saístes com espadas e porretes para prender-me, como a um salteador?

[[v41-14-49]]

^<<v41-14-49,49>>^ Todos os dias eu estava convosco no templo, ensinando, e não me prendestes; contudo, é para que se cumpram as Escrituras.

[[v41-14-50]]

^<<v41-14-50,50>>^ Então, deixando-o, todos fugiram.

[[v41-14-51]]

^<<v41-14-51,51>>^ Seguia-o um jovem, coberto unicamente com um lençol, e lançaram-lhe a mão.

[[v41-14-52]]

^<<v41-14-52,52>>^ Mas ele, largando o lençol, fugiu desnudo.

[[v41-14-53]]

^<<v41-14-53,53>>^ E levaram Jesus ao sumo sacerdote, e reuniram-se todos os principais sacerdotes, os anciãos e os escribas.

[[v41-14-54]]

^<<v41-14-54,54>>^ Pedro seguira-o de longe até ao interior do pátio do sumo sacerdote e estava assentado entre os serventuários, aquentando-se ao fogo.

[[v41-14-55]]

^<<v41-14-55,55>>^ E os principais sacerdotes e todo o Sinédrio procuravam algum testemunho contra Jesus para o condenar à morte e não achavam.

[[v41-14-56]]

^<<v41-14-56,56>>^ Pois muitos testemunhavam falsamente contra Jesus, mas os depoimentos não eram coerentes.

[[v41-14-57]]

^<<v41-14-57,57>>^ E, levantando-se alguns, testificavam falsamente, dizendo:

[[v41-14-58]]

^<<v41-14-58,58>>^ Nós o ouvimos declarar: Eu destruirei este santuário edificado por mãos humanas e, em três dias, construirei outro, não por mãos humanas.

[[v41-14-59]]

^<<v41-14-59,59>>^ Nem assim o testemunho deles era coerente.

[[v41-14-60]]

^<<v41-14-60,60>>^ Levantando-se o sumo sacerdote, no meio, perguntou a Jesus: Nada respondes ao que estes depõem contra ti?

[[v41-14-61]]

^<<v41-14-61,61>>^ Ele, porém, guardou silêncio e nada respondeu. Tornou a interrogá-lo o sumo sacerdote e lhe disse: És tu o Cristo, o Filho do Deus Bendito?

[[v41-14-62]]

^<<v41-14-62,62>>^ Jesus respondeu: Eu sou, e vereis o Filho do Homem assentado à direita do Todo-Poderoso e vindo com as nuvens do céu.

[[v41-14-63]]

^<<v41-14-63,63>>^ Então, o sumo sacerdote rasgou as suas vestes e disse: Que mais necessidade temos de testemunhas?

[[v41-14-64]]

^<<v41-14-64,64>>^ Ouvistes a blasfêmia; que vos parece? E todos o julgaram réu de morte.

[[v41-14-65]]

^<<v41-14-65,65>>^ Puseram-se alguns a cuspir nele, a cobrir-lhe o rosto, a dar-lhe murros e a dizer-lhe: Profetiza! E os guardas o tomaram a bofetadas.

[[v41-14-66]]

^<<v41-14-66,66>>^ Estando Pedro embaixo no pátio, veio uma das criadas do sumo sacerdote

[[v41-14-67]]

^<<v41-14-67,67>>^ e, vendo a Pedro, que se aquentava, fixou-o e disse: Tu também estavas com Jesus, o Nazareno.

[[v41-14-68]]

^<<v41-14-68,68>>^ Mas ele o negou, dizendo: Não o conheço, nem compreendo o que dizes. E saiu para o alpendre. [E o galo cantou.]

[[v41-14-69]]

^<<v41-14-69,69>>^ E a criada, vendo-o, tornou a dizer aos circunstantes: Este é um deles.

[[v41-14-70]]

^<<v41-14-70,70>>^ Mas ele outra vez o negou. E, pouco depois, os que ali estavam disseram a Pedro: Verdadeiramente, és um deles, porque também tu és galileu.

[[v41-14-71]]

^<<v41-14-71,71>>^ Ele, porém, começou a praguejar e a jurar: Não conheço esse homem de quem falais!

[[v41-14-72]]

^<<v41-14-72,72>>^ E logo cantou o galo pela segunda vez. Então, Pedro se lembrou da palavra que Jesus lhe dissera: Antes que duas vezes cante o galo, tu me negarás três vezes.  E, caindo em si, desatou a chorar.

'''

xref:041-marcos/041-marcos-013.adoc#v41-13-0[&#60; Capítulo Anterior] | <<v41-14-0,Topo>> | xref:041-marcos/041-marcos-015.adoc#v41-15-0[Próximo Capítulo &#62;]