include::./index.adoc[]

[[v41-12-0]]
=== Marcos, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v41-12-1]]

^<<v41-12-1,1>>^ Depois, entrou Jesus a falar-lhes por parábola: Um homem plantou uma vinha, cercou-a de uma sebe, construiu um lagar, edificou uma torre, arrendou-a a uns lavradores e ausentou-se do país.

[[v41-12-2]]

^<<v41-12-2,2>>^ No tempo da colheita, enviou um servo aos lavradores para que recebesse deles dos frutos da vinha;

[[v41-12-3]]

^<<v41-12-3,3>>^ eles, porém, o agarraram, espancaram e o despacharam vazio.

[[v41-12-4]]

^<<v41-12-4,4>>^ De novo, lhes enviou outro servo, e eles o esbordoaram na cabeça e o insultaram.

[[v41-12-5]]

^<<v41-12-5,5>>^ Ainda outro lhes mandou, e a este mataram. Muitos outros lhes enviou, dos quais espancaram uns e mataram outros.

[[v41-12-6]]

^<<v41-12-6,6>>^ Restava-lhe ainda um, seu filho amado; a este lhes enviou, por fim, dizendo: Respeitarão a meu filho.

[[v41-12-7]]

^<<v41-12-7,7>>^ Mas os tais lavradores disseram entre si: Este é o herdeiro; ora, vamos, matemo-lo, e a herança será nossa.

[[v41-12-8]]

^<<v41-12-8,8>>^ E, agarrando-o, mataram-no e o atiraram para fora da vinha.

[[v41-12-9]]

^<<v41-12-9,9>>^ Que fará, pois, o dono da vinha? Virá, exterminará aqueles lavradores e passará a vinha a outros.

[[v41-12-10]]

^<<v41-12-10,10>>^ Ainda não lestes esta Escritura: A pedra que os construtores rejeitaram, essa veio a ser a principal pedra, angular;

[[v41-12-11]]

^<<v41-12-11,11>>^ isto procede do Senhor, e é maravilhoso aos nossos olhos?

[[v41-12-12]]

^<<v41-12-12,12>>^ E procuravam prendê-lo, mas temiam o povo; porque compreenderam que contra eles proferira esta parábola. Então, desistindo, retiraram-se.

[[v41-12-13]]

^<<v41-12-13,13>>^ E enviaram-lhe alguns dos fariseus e dos herodianos, para que o apanhassem em alguma palavra.

[[v41-12-14]]

^<<v41-12-14,14>>^ Chegando, disseram-lhe: Mestre, sabemos que és verdadeiro e não te importas com quem quer que seja, porque não olhas a aparência dos homens; antes, segundo a verdade, ensinas o caminho de Deus; é lícito pagar tributo a César ou não? Devemos ou não devemos pagar?

[[v41-12-15]]

^<<v41-12-15,15>>^ Mas Jesus, percebendo-lhes a hipocrisia, respondeu: Por que me experimentais? Trazei-me um denário para que eu o veja.

[[v41-12-16]]

^<<v41-12-16,16>>^ E eles lho trouxeram. Perguntou-lhes: De quem é esta efígie e inscrição?  Responderam: De César.

[[v41-12-17]]

^<<v41-12-17,17>>^ Disse-lhes, então, Jesus: Dai a César o que é de César e a Deus o que é de Deus.  E muito se admiraram dele.

[[v41-12-18]]

^<<v41-12-18,18>>^ Então, os saduceus, que dizem não haver ressurreição, aproximaram-se dele e lhe perguntaram, dizendo:

[[v41-12-19]]

^<<v41-12-19,19>>^ Mestre, Moisés nos deixou escrito que, se morrer o irmão de alguém e deixar mulher sem filhos, seu irmão a tome como esposa e suscite descendência a seu irmão.

[[v41-12-20]]

^<<v41-12-20,20>>^ Ora, havia sete irmãos; o primeiro casou e morreu sem deixar descendência;

[[v41-12-21]]

^<<v41-12-21,21>>^ o segundo desposou a viúva e morreu, também sem deixar descendência; e o terceiro, da mesma forma.

[[v41-12-22]]

^<<v41-12-22,22>>^ E, assim, os sete não deixaram descendência. Por fim, depois de todos, morreu também a mulher.

[[v41-12-23]]

^<<v41-12-23,23>>^ Na ressurreição, quando eles ressuscitarem, de qual deles será ela a esposa? Porque os sete a desposaram.

[[v41-12-24]]

^<<v41-12-24,24>>^ Respondeu-lhes Jesus: Não provém o vosso erro de não conhecerdes as Escrituras, nem o poder de Deus?

[[v41-12-25]]

^<<v41-12-25,25>>^ Pois, quando ressuscitarem de entre os mortos, nem casarão, nem se darão em casamento; porém, são como os anjos nos céus.

[[v41-12-26]]

^<<v41-12-26,26>>^ Quanto à ressurreição dos mortos, não tendes lido no Livro de Moisés, no trecho referente à sarça, como Deus lhe falou: Eu sou o Deus de Abraão, o Deus de Isaque e o Deus de Jacó?

[[v41-12-27]]

^<<v41-12-27,27>>^ Ora, ele não é Deus de mortos, e sim de vivos. Laborais em grande erro.

[[v41-12-28]]

^<<v41-12-28,28>>^ Chegando um dos escribas, tendo ouvido a discussão entre eles, vendo como Jesus lhes houvera respondido bem, perguntou-lhe: Qual é o principal de todos os mandamentos?

[[v41-12-29]]

^<<v41-12-29,29>>^ Respondeu Jesus: O principal é: Ouve, ó Israel, o Senhor, nosso Deus, é o único Senhor!

[[v41-12-30]]

^<<v41-12-30,30>>^ Amarás, pois, o Senhor, teu Deus, de todo o teu coração, de toda a tua alma, de todo o teu entendimento e de toda a tua força.

[[v41-12-31]]

^<<v41-12-31,31>>^ O segundo é: Amarás o teu próximo como a ti mesmo. Não há outro mandamento maior do que estes.

[[v41-12-32]]

^<<v41-12-32,32>>^ Disse-lhe o escriba: Muito bem, Mestre, e com verdade disseste que ele é o único, e não há outro senão ele,

[[v41-12-33]]

^<<v41-12-33,33>>^ e que amar a Deus de todo o coração e de todo o entendimento e de toda a força, e amar ao próximo como a si mesmo excede a todos os holocaustos e sacrifícios.

[[v41-12-34]]

^<<v41-12-34,34>>^ Vendo Jesus que ele havia respondido sabiamente, declarou-lhe: Não estás longe do reino de Deus.  E já ninguém mais ousava interrogá-lo.

[[v41-12-35]]

^<<v41-12-35,35>>^ Jesus, ensinando no templo, perguntou: Como dizem os escribas que o Cristo é filho de Davi?

[[v41-12-36]]

^<<v41-12-36,36>>^ O próprio Davi falou, pelo Espírito Santo: Disse o Senhor ao meu Senhor: Assenta-te à minha direita, até que eu ponha os teus inimigos debaixo dos teus pés.

[[v41-12-37]]

^<<v41-12-37,37>>^ O mesmo Davi chama-lhe Senhor; como, pois, é ele seu filho?  E a grande multidão o ouvia com prazer.

[[v41-12-38]]

^<<v41-12-38,38>>^ E, ao ensinar, dizia ele: Guardai-vos dos escribas, que gostam de andar com vestes talares e das saudações nas praças;

[[v41-12-39]]

^<<v41-12-39,39>>^ e das primeiras cadeiras nas sinagogas e dos primeiros lugares nos banquetes;

[[v41-12-40]]

^<<v41-12-40,40>>^ os quais devoram as casas das viúvas e, para o justificar, fazem longas orações; estes sofrerão juízo muito mais severo.

[[v41-12-41]]

^<<v41-12-41,41>>^ Assentado diante do gazofilácio, observava Jesus como o povo lançava ali o dinheiro. Ora, muitos ricos depositavam grandes quantias.

[[v41-12-42]]

^<<v41-12-42,42>>^ Vindo, porém, uma viúva pobre, depositou duas pequenas moedas correspondentes a um quadrante.

[[v41-12-43]]

^<<v41-12-43,43>>^ E, chamando os seus discípulos, disse-lhes: Em verdade vos digo que esta viúva pobre depositou no gazofilácio mais do que o fizeram todos os ofertantes.

[[v41-12-44]]

^<<v41-12-44,44>>^ Porque todos eles ofertaram do que lhes sobrava; ela, porém, da sua pobreza deu tudo quanto possuía, todo o seu sustento.

'''

xref:041-marcos/041-marcos-011.adoc#v41-11-0[&#60; Capítulo Anterior] | <<v41-12-0,Topo>> | xref:041-marcos/041-marcos-013.adoc#v41-13-0[Próximo Capítulo &#62;]