include::./index.adoc[]

[[v41-11-0]]
=== Marcos, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v41-11-1]]

^<<v41-11-1,1>>^ Quando se aproximavam de Jerusalém, de Betfagé e Betânia, junto ao monte das Oliveiras, enviou Jesus dois dos seus discípulos

[[v41-11-2]]

^<<v41-11-2,2>>^ e disse-lhes: Ide à aldeia que aí está diante de vós e, logo ao entrar, achareis preso um jumentinho, o qual ainda ninguém montou; desprendei-o e trazei-o.

[[v41-11-3]]

^<<v41-11-3,3>>^ Se alguém vos perguntar: Por que fazeis isso? Respondei: O Senhor precisa dele e logo o mandará de volta para aqui.

[[v41-11-4]]

^<<v41-11-4,4>>^ Então, foram e acharam o jumentinho preso, junto ao portão, do lado de fora, na rua, e o desprenderam.

[[v41-11-5]]

^<<v41-11-5,5>>^ Alguns dos que ali estavam reclamaram: Que fazeis, soltando o jumentinho?

[[v41-11-6]]

^<<v41-11-6,6>>^ Eles, porém, responderam conforme as instruções de Jesus; então, os deixaram ir.

[[v41-11-7]]

^<<v41-11-7,7>>^ Levaram o jumentinho, sobre o qual puseram as suas vestes, e Jesus o montou.

[[v41-11-8]]

^<<v41-11-8,8>>^ E muitos estendiam as suas vestes no caminho, e outros, ramos que haviam cortado dos campos.

[[v41-11-9]]

^<<v41-11-9,9>>^ Tanto os que iam adiante dele como os que vinham depois clamavam: Hosana! Bendito o que vem em nome do Senhor!

[[v41-11-10]]

^<<v41-11-10,10>>^ Bendito o reino que vem, o reino de Davi, nosso pai! Hosana, nas maiores alturas!

[[v41-11-11]]

^<<v41-11-11,11>>^ E, quando entrou em Jerusalém, no templo, tendo observado tudo, como fosse já tarde, saiu para Betânia com os doze.

[[v41-11-12]]

^<<v41-11-12,12>>^ No dia seguinte, quando saíram de Betânia, teve fome.

[[v41-11-13]]

^<<v41-11-13,13>>^ E, vendo de longe uma figueira com folhas, foi ver se nela, porventura, acharia alguma coisa. Aproximando-se dela, nada achou, senão folhas; porque não era tempo de figos.

[[v41-11-14]]

^<<v41-11-14,14>>^ Então, lhe disse Jesus: Nunca jamais coma alguém fruto de ti!  E seus discípulos ouviram isto.

[[v41-11-15]]

^<<v41-11-15,15>>^ E foram para Jerusalém. Entrando ele no templo, passou a expulsar os que ali vendiam e compravam; derribou as mesas dos cambistas e as cadeiras dos que vendiam pombas.

[[v41-11-16]]

^<<v41-11-16,16>>^ Não permitia que alguém conduzisse qualquer utensílio pelo templo;

[[v41-11-17]]

^<<v41-11-17,17>>^ também os ensinava e dizia: Não está escrito: A minha casa será chamada casa de oração para todas as nações? Vós, porém, a tendes transformado em covil de salteadores.

[[v41-11-18]]

^<<v41-11-18,18>>^ E os principais sacerdotes e escribas ouviam estas coisas e procuravam um modo de lhe tirar a vida; pois o temiam, porque toda a multidão se maravilhava de sua doutrina.

[[v41-11-19]]

^<<v41-11-19,19>>^ Em vindo a tarde, saíram da cidade.

[[v41-11-20]]

^<<v41-11-20,20>>^ E, passando eles pela manhã, viram que a figueira secara desde a raiz.

[[v41-11-21]]

^<<v41-11-21,21>>^ Então, Pedro, lembrando-se, falou: Mestre, eis que a figueira que amaldiçoaste secou.

[[v41-11-22]]

^<<v41-11-22,22>>^ Ao que Jesus lhes disse: Tende fé em Deus;

[[v41-11-23]]

^<<v41-11-23,23>>^ porque em verdade vos afirmo que, se alguém disser a este monte: Ergue-te e lança-te no mar, e não duvidar no seu coração, mas crer que se fará o que diz, assim será com ele.

[[v41-11-24]]

^<<v41-11-24,24>>^ Por isso, vos digo que tudo quanto em oração pedirdes, crede que recebestes, e será assim convosco.

[[v41-11-25]]

^<<v41-11-25,25>>^ E, quando estiverdes orando, se tendes alguma coisa contra alguém, perdoai, para que vosso Pai celestial vos perdoe as vossas ofensas.

[[v41-11-26]]

^<<v41-11-26,26>>^ [Mas, se não perdoardes, também vosso Pai celestial não vos perdoará as vossas ofensas.]

[[v41-11-27]]

^<<v41-11-27,27>>^ Então, regressaram para Jerusalém. E, andando ele pelo templo, vieram ao seu encontro os principais sacerdotes, os escribas e os anciãos

[[v41-11-28]]

^<<v41-11-28,28>>^ e lhe perguntaram: Com que autoridade fazes estas coisas? Ou quem te deu tal autoridade para as fazeres?

[[v41-11-29]]

^<<v41-11-29,29>>^ Jesus lhes respondeu: Eu vos farei uma pergunta; respondei-me, e eu vos direi com que autoridade faço estas coisas.

[[v41-11-30]]

^<<v41-11-30,30>>^ O batismo de João era do céu ou dos homens? Respondei!

[[v41-11-31]]

^<<v41-11-31,31>>^ E eles discorriam entre si: Se dissermos: Do céu, dirá: Então, por que não acreditastes nele?

[[v41-11-32]]

^<<v41-11-32,32>>^ Se, porém, dissermos: dos homens, é de temer o povo. Porque todos consideravam a João como profeta.

[[v41-11-33]]

^<<v41-11-33,33>>^ Então, responderam a Jesus: Não sabemos. E Jesus, por sua vez, lhes disse: Nem eu tampouco vos digo com que autoridade faço estas coisas.

'''

xref:041-marcos/041-marcos-010.adoc#v41-10-0[&#60; Capítulo Anterior] | <<v41-11-0,Topo>> | xref:041-marcos/041-marcos-012.adoc#v41-12-0[Próximo Capítulo &#62;]