include::./index.adoc[]

[[v41-2-0]]
=== Marcos, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v41-2-1]]

^<<v41-2-1,1>>^ Dias depois, entrou Jesus de novo em Cafarnaum, e logo correu que ele estava em casa.

[[v41-2-2]]

^<<v41-2-2,2>>^ Muitos afluíram para ali, tantos que nem mesmo junto à porta eles achavam lugar; e anunciava-lhes a palavra.

[[v41-2-3]]

^<<v41-2-3,3>>^ Alguns foram ter com ele, conduzindo um paralítico, levado por quatro homens.

[[v41-2-4]]

^<<v41-2-4,4>>^ E, não podendo aproximar-se dele, por causa da multidão, descobriram o eirado no ponto correspondente ao em que ele estava e, fazendo uma abertura, baixaram o leito em que jazia o doente.

[[v41-2-5]]

^<<v41-2-5,5>>^ Vendo-lhes a fé, Jesus disse ao paralítico: Filho, os teus pecados estão perdoados.

[[v41-2-6]]

^<<v41-2-6,6>>^ Mas alguns dos escribas estavam assentados ali e arrazoavam em seu coração:

[[v41-2-7]]

^<<v41-2-7,7>>^ Por que fala ele deste modo? Isto é blasfêmia! Quem pode perdoar pecados, senão um, que é Deus?

[[v41-2-8]]

^<<v41-2-8,8>>^ E Jesus, percebendo logo por seu espírito que eles assim arrazoavam, disse-lhes: Por que arrazoais sobre estas coisas em vosso coração?

[[v41-2-9]]

^<<v41-2-9,9>>^ Qual é mais fácil? Dizer ao paralítico: Estão perdoados os teus pecados, ou dizer: Levanta-te, toma o teu leito e anda?

[[v41-2-10]]

^<<v41-2-10,10>>^ Ora, para que saibais que o Filho do Homem tem sobre a terra autoridade para perdoar pecados  — disse ao paralítico:

[[v41-2-11]]

^<<v41-2-11,11>>^ Eu te mando: Levanta-te, toma o teu leito e vai para tua casa.

[[v41-2-12]]

^<<v41-2-12,12>>^ Então, ele se levantou e, no mesmo instante, tomando o leito, retirou-se à vista de todos, a ponto de se admirarem todos e darem glória a Deus, dizendo: Jamais vimos coisa assim!

[[v41-2-13]]

^<<v41-2-13,13>>^ De novo, saiu Jesus para junto do mar, e toda a multidão vinha ao seu encontro, e ele os ensinava.

[[v41-2-14]]

^<<v41-2-14,14>>^ Quando ia passando, viu a Levi, filho de Alfeu, sentado na coletoria e disse-lhe: Segue-me!  Ele se levantou e o seguiu.

[[v41-2-15]]

^<<v41-2-15,15>>^ Achando-se Jesus à mesa na casa de Levi, estavam juntamente com ele e com seus discípulos muitos publicanos e pecadores; porque estes eram em grande número e também o seguiam.

[[v41-2-16]]

^<<v41-2-16,16>>^ Os escribas dos fariseus, vendo-o comer em companhia dos pecadores e publicanos, perguntavam aos discípulos dele: Por que come [e bebe] ele com os publicanos e pecadores?

[[v41-2-17]]

^<<v41-2-17,17>>^ Tendo Jesus ouvido isto, respondeu-lhes: Os sãos não precisam de médico, e sim os doentes; não vim chamar justos, e sim pecadores.

[[v41-2-18]]

^<<v41-2-18,18>>^ Ora, os discípulos de João e os fariseus estavam jejuando. Vieram alguns e lhe perguntaram: Por que motivo jejuam os discípulos de João e os dos fariseus, mas os teus discípulos não jejuam?

[[v41-2-19]]

^<<v41-2-19,19>>^ Respondeu-lhes Jesus: Podem, porventura, jejuar os convidados para o casamento, enquanto o noivo está com eles? Durante o tempo em que estiver presente o noivo, não podem jejuar.

[[v41-2-20]]

^<<v41-2-20,20>>^ Dias virão, contudo, em que lhes será tirado o noivo; e, nesse tempo, jejuarão.

[[v41-2-21]]

^<<v41-2-21,21>>^ Ninguém costura remendo de pano novo em veste velha; porque o remendo novo tira parte da veste velha, e fica maior a rotura.

[[v41-2-22]]

^<<v41-2-22,22>>^ Ninguém põe vinho novo em odres velhos; do contrário, o vinho romperá os odres; e tanto se perde o vinho como os odres. Mas põe-se vinho novo em odres novos.

[[v41-2-23]]

^<<v41-2-23,23>>^ Ora, aconteceu atravessar Jesus, em dia de sábado, as searas, e os discípulos, ao passarem, colhiam espigas.

[[v41-2-24]]

^<<v41-2-24,24>>^ Advertiram-no os fariseus: Vê! Por que fazem o que não é lícito aos sábados?

[[v41-2-25]]

^<<v41-2-25,25>>^ Mas ele lhes respondeu: Nunca lestes o que fez Davi, quando se viu em necessidade e teve fome, ele e os seus companheiros?

[[v41-2-26]]

^<<v41-2-26,26>>^ Como entrou na Casa de Deus, no tempo do sumo sacerdote Abiatar, e comeu os pães da proposição, os quais não é lícito comer, senão aos sacerdotes, e deu também aos que estavam com ele?

[[v41-2-27]]

^<<v41-2-27,27>>^ E acrescentou: O sábado foi estabelecido por causa do homem, e não o homem por causa do sábado;

[[v41-2-28]]

^<<v41-2-28,28>>^ de sorte que o Filho do Homem é senhor também do sábado.

'''

xref:041-marcos/041-marcos-001.adoc#v41-1-0[&#60; Capítulo Anterior] | <<v41-2-0,Topo>> | xref:041-marcos/041-marcos-003.adoc#v41-3-0[Próximo Capítulo &#62;]