include::./index.adoc[]

[[v41-1-0]]
=== Marcos, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v41-1-1]]

^<<v41-1-1,1>>^ Princípio do evangelho de Jesus Cristo, Filho de Deus.

[[v41-1-2]]

^<<v41-1-2,2>>^ Conforme está escrito na profecia de Isaías: Eis aí envio diante da tua face o meu mensageiro, o qual preparará o teu caminho;

[[v41-1-3]]

^<<v41-1-3,3>>^ voz do que clama no deserto: Preparai o caminho do Senhor, endireitai as suas veredas;

[[v41-1-4]]

^<<v41-1-4,4>>^ apareceu João Batista no deserto, pregando batismo de arrependimento para remissão de pecados.

[[v41-1-5]]

^<<v41-1-5,5>>^ Saíam a ter com ele toda a província da Judeia e todos os habitantes de Jerusalém; e, confessando os seus pecados, eram batizados por ele no rio Jordão.

[[v41-1-6]]

^<<v41-1-6,6>>^ As vestes de João eram feitas de pelos de camelo; ele trazia um cinto de couro e se alimentava de gafanhotos e mel silvestre.

[[v41-1-7]]

^<<v41-1-7,7>>^ E pregava, dizendo: Após mim vem aquele que é mais poderoso do que eu, do qual não sou digno de, curvando-me, desatar-lhe as correias das sandálias.

[[v41-1-8]]

^<<v41-1-8,8>>^ Eu vos tenho batizado com água; ele, porém, vos batizará com o Espírito Santo.

[[v41-1-9]]

^<<v41-1-9,9>>^ Naqueles dias, veio Jesus de Nazaré da Galileia e por João foi batizado no rio Jordão.

[[v41-1-10]]

^<<v41-1-10,10>>^ Logo ao sair da água, viu os céus rasgarem-se e o Espírito descendo como pomba sobre ele.

[[v41-1-11]]

^<<v41-1-11,11>>^ Então, foi ouvida uma voz dos céus: Tu és o meu Filho amado, em ti me comprazo.

[[v41-1-12]]

^<<v41-1-12,12>>^ E logo o Espírito o impeliu para o deserto,

[[v41-1-13]]

^<<v41-1-13,13>>^ onde permaneceu quarenta dias, sendo tentado por Satanás; estava com as feras, mas os anjos o serviam.

[[v41-1-14]]

^<<v41-1-14,14>>^ Depois de João ter sido preso, foi Jesus para a Galileia, pregando o evangelho de Deus,

[[v41-1-15]]

^<<v41-1-15,15>>^ dizendo: O tempo está cumprido, e o reino de Deus está próximo; arrependei-vos e crede no evangelho.

[[v41-1-16]]

^<<v41-1-16,16>>^ Caminhando junto ao mar da Galileia, viu os irmãos Simão e André, que lançavam a rede ao mar, porque eram pescadores.

[[v41-1-17]]

^<<v41-1-17,17>>^ Disse-lhes Jesus: Vinde após mim, e eu vos farei pescadores de homens.

[[v41-1-18]]

^<<v41-1-18,18>>^ Então, eles deixaram imediatamente as redes e o seguiram.

[[v41-1-19]]

^<<v41-1-19,19>>^ Pouco mais adiante, viu Tiago, filho de Zebedeu, e João, seu irmão, que estavam no barco consertando as redes.

[[v41-1-20]]

^<<v41-1-20,20>>^ E logo os chamou. Deixando eles no barco a seu pai Zebedeu com os empregados, seguiram após Jesus.

[[v41-1-21]]

^<<v41-1-21,21>>^ Depois, entraram em Cafarnaum, e, logo no sábado, foi ele ensinar na sinagoga.

[[v41-1-22]]

^<<v41-1-22,22>>^ Maravilhavam-se da sua doutrina, porque os ensinava como quem tem autoridade e não como os escribas.

[[v41-1-23]]

^<<v41-1-23,23>>^ Não tardou que aparecesse na sinagoga um homem possesso de espírito imundo, o qual bradou:

[[v41-1-24]]

^<<v41-1-24,24>>^ Que temos nós contigo, Jesus Nazareno? Vieste para perder-nos? Bem sei quem és: o Santo de Deus!

[[v41-1-25]]

^<<v41-1-25,25>>^ Mas Jesus o repreendeu, dizendo: Cala-te e sai desse homem.

[[v41-1-26]]

^<<v41-1-26,26>>^ Então, o espírito imundo, agitando-o violentamente e bradando em alta voz, saiu dele.

[[v41-1-27]]

^<<v41-1-27,27>>^ Todos se admiraram, a ponto de perguntarem entre si: Que vem a ser isto? Uma nova doutrina! Com autoridade ele ordena aos espíritos imundos, e eles lhe obedecem!

[[v41-1-28]]

^<<v41-1-28,28>>^ Então, correu célere a fama de Jesus em todas as direções, por toda a circunvizinhança da Galileia.

[[v41-1-29]]

^<<v41-1-29,29>>^ E, saindo eles da sinagoga, foram, com Tiago e João, diretamente para a casa de Simão e André.

[[v41-1-30]]

^<<v41-1-30,30>>^ A sogra de Simão achava-se acamada, com febre; e logo lhe falaram a respeito dela.

[[v41-1-31]]

^<<v41-1-31,31>>^ Então, aproximando-se, tomou-a pela mão; e a febre a deixou, passando ela a servi-los.

[[v41-1-32]]

^<<v41-1-32,32>>^ À tarde, ao cair do sol, trouxeram a Jesus todos os enfermos e endemoninhados.

[[v41-1-33]]

^<<v41-1-33,33>>^ Toda a cidade estava reunida à porta.

[[v41-1-34]]

^<<v41-1-34,34>>^ E ele curou muitos doentes de toda sorte de enfermidades; também expeliu muitos demônios, não lhes permitindo que falassem, porque sabiam quem ele era.

[[v41-1-35]]

^<<v41-1-35,35>>^ Tendo-se levantado alta madrugada, saiu, foi para um lugar deserto e ali orava.

[[v41-1-36]]

^<<v41-1-36,36>>^ Procuravam-no diligentemente Simão e os que com ele estavam.

[[v41-1-37]]

^<<v41-1-37,37>>^ Tendo-o encontrado, lhe disseram: Todos te buscam.

[[v41-1-38]]

^<<v41-1-38,38>>^ Jesus, porém, lhes disse: Vamos a outros lugares, às povoações vizinhas, a fim de que eu pregue também ali, pois para isso é que eu vim.

[[v41-1-39]]

^<<v41-1-39,39>>^ Então, foi por toda a Galileia, pregando nas sinagogas deles e expelindo os demônios.

[[v41-1-40]]

^<<v41-1-40,40>>^ Aproximou-se dele um leproso rogando-lhe, de joelhos: Se quiseres, podes purificar-me.

[[v41-1-41]]

^<<v41-1-41,41>>^ Jesus, profundamente compadecido, estendeu a mão, tocou-o e disse-lhe: Quero, fica limpo!

[[v41-1-42]]

^<<v41-1-42,42>>^ No mesmo instante, lhe desapareceu a lepra, e ficou limpo.

[[v41-1-43]]

^<<v41-1-43,43>>^ Fazendo-lhe, então, veemente advertência, logo o despediu

[[v41-1-44]]

^<<v41-1-44,44>>^ e lhe disse: Olha, não digas nada a ninguém; mas vai, mostra-te ao sacerdote e oferece pela tua purificação o que Moisés determinou, para servir de testemunho ao povo.

[[v41-1-45]]

^<<v41-1-45,45>>^ Mas, tendo ele saído, entrou a propalar muitas coisas e a divulgar a notícia, a ponto de não mais poder Jesus entrar publicamente em qualquer cidade, mas permanecia fora, em lugares ermos; e de toda parte vinham ter com ele.

'''

xref:040-mateus/040-mateus-028.adoc#v40-28-0[&#60; Capítulo Anterior] | <<v41-1-0,Topo>> | xref:041-marcos/041-marcos-002.adoc#v41-2-0[Próximo Capítulo &#62;]