include::./index.adoc[]

[[v41-4-0]]
=== Marcos, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v41-4-1]]

^<<v41-4-1,1>>^ Voltou Jesus a ensinar à beira-mar. E reuniu-se numerosa multidão a ele, de modo que entrou num barco, onde se assentou, afastando-se da praia. E todo o povo estava à beira-mar, na praia.

[[v41-4-2]]

^<<v41-4-2,2>>^ Assim, lhes ensinava muitas coisas por parábolas, no decorrer do seu doutrinamento.

[[v41-4-3]]

^<<v41-4-3,3>>^ Ouvi: Eis que saiu o semeador a semear.

[[v41-4-4]]

^<<v41-4-4,4>>^ E, ao semear, uma parte caiu à beira do caminho, e vieram as aves e a comeram.

[[v41-4-5]]

^<<v41-4-5,5>>^ Outra caiu em solo rochoso, onde a terra era pouca, e logo nasceu, visto não ser profunda a terra.

[[v41-4-6]]

^<<v41-4-6,6>>^ Saindo, porém, o sol, a queimou; e, porque não tinha raiz, secou-se.

[[v41-4-7]]

^<<v41-4-7,7>>^ Outra parte caiu entre os espinhos; e os espinhos cresceram e a sufocaram, e não deu fruto.

[[v41-4-8]]

^<<v41-4-8,8>>^ Outra, enfim, caiu em boa terra e deu fruto, que vingou e cresceu, produzindo a trinta, a sessenta e a cem por um.

[[v41-4-9]]

^<<v41-4-9,9>>^ E acrescentou: Quem tem ouvidos para ouvir, ouça.

[[v41-4-10]]

^<<v41-4-10,10>>^ Quando Jesus ficou só, os que estavam junto dele com os doze o interrogaram a respeito das parábolas.

[[v41-4-11]]

^<<v41-4-11,11>>^ Ele lhes respondeu: A vós outros vos é dado conhecer o mistério do reino de Deus; mas, aos de fora, tudo se ensina por meio de parábolas,

[[v41-4-12]]

^<<v41-4-12,12>>^ para que, vendo, vejam e não percebam; e, ouvindo, ouçam e não entendam; para que não venham a converter-se, e haja perdão para eles.

[[v41-4-13]]

^<<v41-4-13,13>>^ Então, lhes perguntou: Não entendeis esta parábola e como compreendereis todas as parábolas?

[[v41-4-14]]

^<<v41-4-14,14>>^ O semeador semeia a palavra.

[[v41-4-15]]

^<<v41-4-15,15>>^ São estes os da beira do caminho, onde a palavra é semeada; e, enquanto a ouvem, logo vem Satanás e tira a palavra semeada neles.

[[v41-4-16]]

^<<v41-4-16,16>>^ Semelhantemente, são estes os semeados em solo rochoso, os quais, ouvindo a palavra, logo a recebem com alegria.

[[v41-4-17]]

^<<v41-4-17,17>>^ Mas eles não têm raiz em si mesmos, sendo, antes, de pouca duração; em lhes chegando a angústia ou a perseguição por causa da palavra, logo se escandalizam.

[[v41-4-18]]

^<<v41-4-18,18>>^ Os outros, os semeados entre os espinhos, são os que ouvem a palavra,

[[v41-4-19]]

^<<v41-4-19,19>>^ mas os cuidados do mundo, a fascinação da riqueza e as demais ambições, concorrendo, sufocam a palavra, ficando ela infrutífera.

[[v41-4-20]]

^<<v41-4-20,20>>^ Os que foram semeados em boa terra são aqueles que ouvem a palavra e a recebem, frutificando a trinta, a sessenta e a cem por um.

[[v41-4-21]]

^<<v41-4-21,21>>^ Também lhes disse: Vem, porventura, a candeia para ser posta debaixo do alqueire ou da cama? Não vem, antes, para ser colocada no velador?

[[v41-4-22]]

^<<v41-4-22,22>>^ Pois nada está oculto, senão para ser manifesto; e nada se faz escondido, senão para ser revelado.

[[v41-4-23]]

^<<v41-4-23,23>>^ Se alguém tem ouvidos para ouvir, ouça.

[[v41-4-24]]

^<<v41-4-24,24>>^ Então, lhes disse: Atentai no que ouvis. Com a medida com que tiverdes medido vos medirão também, e ainda se vos acrescentará.

[[v41-4-25]]

^<<v41-4-25,25>>^ Pois ao que tem se lhe dará; e, ao que não tem, até o que tem lhe será tirado.

[[v41-4-26]]

^<<v41-4-26,26>>^ Disse ainda: O reino de Deus é assim como se um homem lançasse a semente à terra;

[[v41-4-27]]

^<<v41-4-27,27>>^ depois, dormisse e se levantasse, de noite e de dia, e a semente germinasse e crescesse, não sabendo ele como.

[[v41-4-28]]

^<<v41-4-28,28>>^ A terra por si mesma frutifica: primeiro a erva, depois, a espiga, e, por fim, o grão cheio na espiga.

[[v41-4-29]]

^<<v41-4-29,29>>^ E, quando o fruto já está maduro, logo se lhe mete a foice, porque é chegada a ceifa.

[[v41-4-30]]

^<<v41-4-30,30>>^ Disse mais: A que assemelharemos o reino de Deus? Ou com que parábola o apresentaremos?

[[v41-4-31]]

^<<v41-4-31,31>>^ É como um grão de mostarda, que, quando semeado, é a menor de todas as sementes sobre a terra;

[[v41-4-32]]

^<<v41-4-32,32>>^ mas, uma vez semeada, cresce e se torna maior do que todas as hortaliças e deita grandes ramos, a ponto de as aves do céu poderem aninhar-se à sua sombra.

[[v41-4-33]]

^<<v41-4-33,33>>^ E com muitas parábolas semelhantes lhes expunha a palavra, conforme o permitia a capacidade dos ouvintes.

[[v41-4-34]]

^<<v41-4-34,34>>^ E sem parábolas não lhes falava; tudo, porém, explicava em particular aos seus próprios discípulos.

[[v41-4-35]]

^<<v41-4-35,35>>^ Naquele dia, sendo já tarde, disse-lhes Jesus: Passemos para a outra margem.

[[v41-4-36]]

^<<v41-4-36,36>>^ E eles, despedindo a multidão, o levaram assim como estava, no barco; e outros barcos o seguiam.

[[v41-4-37]]

^<<v41-4-37,37>>^ Ora, levantou-se grande temporal de vento, e as ondas se arremessavam contra o barco, de modo que o mesmo já estava a encher-se de água.

[[v41-4-38]]

^<<v41-4-38,38>>^ E Jesus estava na popa, dormindo sobre o travesseiro; eles o despertaram e lhe disseram: Mestre, não te importa que pereçamos?

[[v41-4-39]]

^<<v41-4-39,39>>^ E ele, despertando, repreendeu o vento e disse ao mar: Acalma-te, emudece!  O vento se aquietou, e fez-se grande bonança.

[[v41-4-40]]

^<<v41-4-40,40>>^ Então, lhes disse: Por que sois assim tímidos?! Como é que não tendes fé?

[[v41-4-41]]

^<<v41-4-41,41>>^ E eles, possuídos de grande temor, diziam uns aos outros: Quem é este que até o vento e o mar lhe obedecem?

'''

xref:041-marcos/041-marcos-003.adoc#v41-3-0[&#60; Capítulo Anterior] | <<v41-4-0,Topo>> | xref:041-marcos/041-marcos-005.adoc#v41-5-0[Próximo Capítulo &#62;]