include::./index.adoc[]

[[v41-8-0]]
=== Marcos, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v41-8-1]]

^<<v41-8-1,1>>^ Naqueles dias, quando outra vez se reuniu grande multidão, e não tendo eles o que comer, chamou Jesus os discípulos e lhes disse:

[[v41-8-2]]

^<<v41-8-2,2>>^ Tenho compaixão desta gente, porque há três dias que permanecem comigo e não têm o que comer.

[[v41-8-3]]

^<<v41-8-3,3>>^ Se eu os despedir para suas casas, em jejum, desfalecerão pelo caminho; e alguns deles vieram de longe.

[[v41-8-4]]

^<<v41-8-4,4>>^ Mas os seus discípulos lhe responderam: Donde poderá alguém fartá-los de pão neste deserto?

[[v41-8-5]]

^<<v41-8-5,5>>^ E Jesus lhes perguntou: Quantos pães tendes?  Responderam eles: Sete.

[[v41-8-6]]

^<<v41-8-6,6>>^ Ordenou ao povo que se assentasse no chão. E, tomando os sete pães, partiu-os, após ter dado graças, e os deu a seus discípulos, para que estes os distribuíssem, repartindo entre o povo.

[[v41-8-7]]

^<<v41-8-7,7>>^ Tinham também alguns peixinhos; e, abençoando-os, mandou que estes igualmente fossem distribuídos.

[[v41-8-8]]

^<<v41-8-8,8>>^ Comeram e se fartaram; e dos pedaços restantes recolheram sete cestos.

[[v41-8-9]]

^<<v41-8-9,9>>^ Eram cerca de quatro mil homens. Então, Jesus os despediu.

[[v41-8-10]]

^<<v41-8-10,10>>^ Logo a seguir, tendo embarcado juntamente com seus discípulos, partiu para as regiões de Dalmanuta.

[[v41-8-11]]

^<<v41-8-11,11>>^ E, saindo os fariseus, puseram-se a discutir com ele; e, tentando-o, pediram-lhe um sinal do céu.

[[v41-8-12]]

^<<v41-8-12,12>>^ Jesus, porém, arrancou do íntimo do seu espírito um gemido e disse: Por que pede esta geração um sinal? Em verdade vos digo que a esta geração não se lhe dará sinal algum.

[[v41-8-13]]

^<<v41-8-13,13>>^ E, deixando-os, tornou a embarcar e foi para o outro lado.

[[v41-8-14]]

^<<v41-8-14,14>>^ Ora, aconteceu que eles se esqueceram de levar pães e, no barco, não tinham consigo senão um só.

[[v41-8-15]]

^<<v41-8-15,15>>^ Preveniu-os Jesus, dizendo: Vede, guardai-vos do fermento dos fariseus e do fermento de Herodes.

[[v41-8-16]]

^<<v41-8-16,16>>^ E eles discorriam entre si: É que não temos pão.

[[v41-8-17]]

^<<v41-8-17,17>>^ Jesus, percebendo-o, lhes perguntou: Por que discorreis sobre o não terdes pão? Ainda não considerastes, nem compreendestes? Tendes o coração endurecido?

[[v41-8-18]]

^<<v41-8-18,18>>^ Tendo olhos, não vedes? E, tendo ouvidos, não ouvis? Não vos lembrais

[[v41-8-19]]

^<<v41-8-19,19>>^ de quando parti os cinco pães para os cinco mil, quantos cestos cheios de pedaços recolhestes?  Responderam eles: Doze!

[[v41-8-20]]

^<<v41-8-20,20>>^ E de quando parti os sete pães para os quatro mil, quantos cestos cheios de pedaços recolhestes?  Responderam: Sete!

[[v41-8-21]]

^<<v41-8-21,21>>^ Ao que lhes disse Jesus: Não compreendeis ainda?

[[v41-8-22]]

^<<v41-8-22,22>>^ Então, chegaram a Betsaida; e lhe trouxeram um cego, rogando-lhe que o tocasse.

[[v41-8-23]]

^<<v41-8-23,23>>^ Jesus, tomando o cego pela mão, levou-o para fora da aldeia e, aplicando-lhe saliva aos olhos e impondo-lhe as mãos, perguntou-lhe: Vês alguma coisa?

[[v41-8-24]]

^<<v41-8-24,24>>^ Este, recobrando a vista, respondeu: Vejo os homens, porque como árvores os vejo, andando.

[[v41-8-25]]

^<<v41-8-25,25>>^ Então, novamente lhe pôs as mãos nos olhos, e ele, passando a ver claramente, ficou restabelecido; e tudo distinguia de modo perfeito.

[[v41-8-26]]

^<<v41-8-26,26>>^ E mandou-o Jesus embora para casa, recomendando-lhe: Não entres na aldeia.

[[v41-8-27]]

^<<v41-8-27,27>>^ Então, Jesus e os seus discípulos partiram para as aldeias de Cesareia de Filipe; e, no caminho, perguntou-lhes: Quem dizem os homens que sou eu?

[[v41-8-28]]

^<<v41-8-28,28>>^ E responderam: João Batista; outros: Elias; mas outros: Algum dos profetas.

[[v41-8-29]]

^<<v41-8-29,29>>^ Então, lhes perguntou: Mas vós, quem dizeis que eu sou?  Respondendo, Pedro lhe disse: Tu és o Cristo.

[[v41-8-30]]

^<<v41-8-30,30>>^ Advertiu-os Jesus de que a ninguém dissessem tal coisa a seu respeito.

[[v41-8-31]]

^<<v41-8-31,31>>^ Então, começou ele a ensinar-lhes que era necessário que o Filho do Homem sofresse muitas coisas, fosse rejeitado pelos anciãos, pelos principais sacerdotes e pelos escribas, fosse morto e que, depois de três dias, ressuscitasse.

[[v41-8-32]]

^<<v41-8-32,32>>^ E isto ele expunha claramente. Mas Pedro, chamando-o à parte, começou a reprová-lo.

[[v41-8-33]]

^<<v41-8-33,33>>^ Jesus, porém, voltou-se e, fitando os seus discípulos, repreendeu a Pedro e disse: Arreda, Satanás! Porque não cogitas das coisas de Deus, e sim das dos homens.

[[v41-8-34]]

^<<v41-8-34,34>>^ Então, convocando a multidão e juntamente os seus discípulos, disse-lhes: Se alguém quer vir após mim, a si mesmo se negue, tome a sua cruz e siga-me.

[[v41-8-35]]

^<<v41-8-35,35>>^ Quem quiser, pois, salvar a sua vida perdê-la-á; e quem perder a vida por causa de mim e do evangelho salvá-la-á.

[[v41-8-36]]

^<<v41-8-36,36>>^ Que aproveita ao homem ganhar o mundo inteiro e perder a sua alma?

[[v41-8-37]]

^<<v41-8-37,37>>^ Que daria um homem em troca de sua alma?

[[v41-8-38]]

^<<v41-8-38,38>>^ Porque qualquer que, nesta geração adúltera e pecadora, se envergonhar de mim e das minhas palavras, também o Filho do Homem se envergonhará dele, quando vier na glória de seu Pai com os santos anjos.

'''

xref:041-marcos/041-marcos-007.adoc#v41-7-0[&#60; Capítulo Anterior] | <<v41-8-0,Topo>> | xref:041-marcos/041-marcos-009.adoc#v41-9-0[Próximo Capítulo &#62;]