include::./index.adoc[]

[[v41-15-0]]
=== Marcos, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v41-15-1]]

^<<v41-15-1,1>>^ Logo pela manhã, entraram em conselho os principais sacerdotes com os anciãos, os escribas e todo o Sinédrio; e, amarrando a Jesus, levaram-no e o entregaram a Pilatos.

[[v41-15-2]]

^<<v41-15-2,2>>^ Pilatos o interrogou: És tu o rei dos judeus? Respondeu Jesus: Tu o dizes.

[[v41-15-3]]

^<<v41-15-3,3>>^ Então, os principais sacerdotes o acusavam de muitas coisas.

[[v41-15-4]]

^<<v41-15-4,4>>^ Tornou Pilatos a interrogá-lo: Nada respondes? Vê quantas acusações te fazem!

[[v41-15-5]]

^<<v41-15-5,5>>^ Jesus, porém, não respondeu palavra, a ponto de Pilatos muito se admirar.

[[v41-15-6]]

^<<v41-15-6,6>>^ Ora, por ocasião da festa, era costume soltar ao povo um dos presos, qualquer que eles pedissem.

[[v41-15-7]]

^<<v41-15-7,7>>^ Havia um, chamado Barrabás, preso com amotinadores, os quais em um tumulto haviam cometido homicídio.

[[v41-15-8]]

^<<v41-15-8,8>>^ Vindo a multidão, começou a pedir que lhes fizesse como de costume.

[[v41-15-9]]

^<<v41-15-9,9>>^ E Pilatos lhes respondeu, dizendo: Quereis que eu vos solte o rei dos judeus?

[[v41-15-10]]

^<<v41-15-10,10>>^ Pois ele bem percebia que por inveja os principais sacerdotes lho haviam entregado.

[[v41-15-11]]

^<<v41-15-11,11>>^ Mas estes incitaram a multidão no sentido de que lhes soltasse, de preferência, Barrabás.

[[v41-15-12]]

^<<v41-15-12,12>>^ Mas Pilatos lhes perguntou: Que farei, então, deste a quem chamais o rei dos judeus?

[[v41-15-13]]

^<<v41-15-13,13>>^ Eles, porém, clamavam: Crucifica-o!

[[v41-15-14]]

^<<v41-15-14,14>>^ Mas Pilatos lhes disse: Que mal fez ele? E eles gritavam cada vez mais: Crucifica-o!

[[v41-15-15]]

^<<v41-15-15,15>>^ Então, Pilatos, querendo contentar a multidão, soltou-lhes Barrabás; e, após mandar açoitar a Jesus, entregou-o para ser crucificado.

[[v41-15-16]]

^<<v41-15-16,16>>^ Então, os soldados o levaram para dentro do palácio, que é o pretório, e reuniram todo o destacamento.

[[v41-15-17]]

^<<v41-15-17,17>>^ Vestiram-no de púrpura e, tecendo uma coroa de espinhos, lha puseram na cabeça.

[[v41-15-18]]

^<<v41-15-18,18>>^ E o saudavam, dizendo: Salve, rei dos judeus!

[[v41-15-19]]

^<<v41-15-19,19>>^ Davam-lhe na cabeça com um caniço, cuspiam nele e, pondo-se de joelhos, o adoravam.

[[v41-15-20]]

^<<v41-15-20,20>>^ Depois de o terem escarnecido, despiram-lhe a púrpura e o vestiram com as suas próprias vestes. Então, conduziram Jesus para fora, com o fim de o crucificarem.

[[v41-15-21]]

^<<v41-15-21,21>>^ E obrigaram a Simão Cireneu, que passava, vindo do campo, pai de Alexandre e de Rufo, a carregar-lhe a cruz.

[[v41-15-22]]

^<<v41-15-22,22>>^ E levaram Jesus para o Gólgota, que quer dizer Lugar da Caveira.

[[v41-15-23]]

^<<v41-15-23,23>>^ Deram-lhe a beber vinho com mirra; ele, porém, não tomou.

[[v41-15-24]]

^<<v41-15-24,24>>^ Então, o crucificaram e repartiram entre si as vestes dele, lançando-lhes sorte, para ver o que levaria cada um.

[[v41-15-25]]

^<<v41-15-25,25>>^ Era a hora terceira quando o crucificaram.

[[v41-15-26]]

^<<v41-15-26,26>>^ E, por cima, estava, em epígrafe, a sua acusação: O Rei dos Judeus .

[[v41-15-27]]

^<<v41-15-27,27>>^ Com ele crucificaram dois ladrões, um à sua direita, e outro à sua esquerda.

[[v41-15-28]]

^<<v41-15-28,28>>^ [E cumpriu-se a Escritura que diz: Com malfeitores foi contado. ]

[[v41-15-29]]

^<<v41-15-29,29>>^ Os que iam passando, blasfemavam dele, meneando a cabeça e dizendo: Ah! Tu que destróis o santuário e, em três dias, o reedificas!

[[v41-15-30]]

^<<v41-15-30,30>>^ Salva-te a ti mesmo, descendo da cruz!

[[v41-15-31]]

^<<v41-15-31,31>>^ De igual modo, os principais sacerdotes com os escribas, escarnecendo, entre si diziam: Salvou os outros, a si mesmo não pode salvar-se;

[[v41-15-32]]

^<<v41-15-32,32>>^ desça agora da cruz o Cristo, o rei de Israel, para que vejamos e creiamos. Também os que com ele foram crucificados o insultavam.

[[v41-15-33]]

^<<v41-15-33,33>>^ Chegada a hora sexta, houve trevas sobre toda a terra até a hora nona.

[[v41-15-34]]

^<<v41-15-34,34>>^ À hora nona, clamou Jesus em alta voz: Eloí, Eloí, lamá sabactâni?  Que quer dizer: Deus meu, Deus meu, por que me desamparaste?

[[v41-15-35]]

^<<v41-15-35,35>>^ Alguns dos que ali estavam, ouvindo isto, diziam: Vede, chama por Elias!

[[v41-15-36]]

^<<v41-15-36,36>>^ E um deles correu a embeber uma esponja em vinagre e, pondo-a na ponta de um caniço, deu-lhe de beber, dizendo: Deixai, vejamos se Elias vem tirá-lo!

[[v41-15-37]]

^<<v41-15-37,37>>^ Mas Jesus, dando um grande brado, expirou.

[[v41-15-38]]

^<<v41-15-38,38>>^ E o véu do santuário rasgou-se em duas partes, de alto a baixo.

[[v41-15-39]]

^<<v41-15-39,39>>^ O centurião que estava em frente dele, vendo que assim expirara, disse: Verdadeiramente, este homem era o Filho de Deus.

[[v41-15-40]]

^<<v41-15-40,40>>^ Estavam também ali algumas mulheres, observando de longe; entre elas, Maria Madalena, Maria, mãe de Tiago, o menor, e de José, e Salomé;

[[v41-15-41]]

^<<v41-15-41,41>>^ as quais, quando Jesus estava na Galileia, o acompanhavam e serviam; e, além destas, muitas outras que haviam subido com ele para Jerusalém.

[[v41-15-42]]

^<<v41-15-42,42>>^ Ao cair da tarde, por ser o dia da preparação, isto é, a véspera do sábado,

[[v41-15-43]]

^<<v41-15-43,43>>^ vindo José de Arimateia, ilustre membro do Sinédrio, que também esperava o reino de Deus, dirigiu-se resolutamente a Pilatos e pediu o corpo de Jesus.

[[v41-15-44]]

^<<v41-15-44,44>>^ Mas Pilatos admirou-se de que ele já tivesse morrido. E, tendo chamado o centurião, perguntou-lhe se havia muito que morrera.

[[v41-15-45]]

^<<v41-15-45,45>>^ Após certificar-se, pela informação do comandante, cedeu o corpo a José.

[[v41-15-46]]

^<<v41-15-46,46>>^ Este, baixando o corpo da cruz, envolveu-o em um lençol que comprara e o depositou em um túmulo que tinha sido aberto numa rocha; e rolou uma pedra para a entrada do túmulo.

[[v41-15-47]]

^<<v41-15-47,47>>^ Ora, Maria Madalena e Maria, mãe de José, observaram onde ele foi posto.

'''

xref:041-marcos/041-marcos-014.adoc#v41-14-0[&#60; Capítulo Anterior] | <<v41-15-0,Topo>> | xref:041-marcos/041-marcos-016.adoc#v41-16-0[Próximo Capítulo &#62;]