include::./index.adoc[]

[[v41-16-0]]
=== Marcos, 16
// ara ?, ARA - Almeida Revista e Atualizada

[[v41-16-1]]

^<<v41-16-1,1>>^ Passado o sábado, Maria Madalena, Maria, mãe de Tiago, e Salomé, compraram aromas para irem embalsamá-lo.

[[v41-16-2]]

^<<v41-16-2,2>>^ E, muito cedo, no primeiro dia da semana, ao despontar do sol, foram ao túmulo.

[[v41-16-3]]

^<<v41-16-3,3>>^ Diziam umas às outras: Quem nos removerá a pedra da entrada do túmulo?

[[v41-16-4]]

^<<v41-16-4,4>>^ E, olhando, viram que a pedra já estava removida; pois era muito grande.

[[v41-16-5]]

^<<v41-16-5,5>>^ Entrando no túmulo, viram um jovem assentado ao lado direito, vestido de branco, e ficaram surpreendidas e atemorizadas.

[[v41-16-6]]

^<<v41-16-6,6>>^ Ele, porém, lhes disse: Não vos atemorizeis; buscais a Jesus, o Nazareno, que foi crucificado; ele ressuscitou, não está mais aqui; vede o lugar onde o tinham posto.

[[v41-16-7]]

^<<v41-16-7,7>>^ Mas ide, dizei a seus discípulos e a Pedro que ele vai adiante de vós para a Galileia; lá o vereis, como ele vos disse.

[[v41-16-8]]

^<<v41-16-8,8>>^ E, saindo elas, fugiram do sepulcro, porque estavam possuídas de temor e de assombro; e, de medo, nada disseram a ninguém.

[[v41-16-9]]

^<<v41-16-9,9>>^ Havendo ele ressuscitado de manhã cedo no primeiro dia da semana, apareceu primeiro a Maria Madalena, da qual expelira sete demônios.

[[v41-16-10]]

^<<v41-16-10,10>>^ E, partindo ela, foi anunciá-lo àqueles que, tendo sido companheiros de Jesus, se achavam tristes e choravam.

[[v41-16-11]]

^<<v41-16-11,11>>^ Estes, ouvindo que ele vivia e que fora visto por ela, não acreditaram.

[[v41-16-12]]

^<<v41-16-12,12>>^ Depois disto, manifestou-se em outra forma a dois deles que estavam de caminho para o campo.

[[v41-16-13]]

^<<v41-16-13,13>>^ E, indo, eles o anunciaram aos demais, mas também a estes dois eles não deram crédito.

[[v41-16-14]]

^<<v41-16-14,14>>^ Finalmente, apareceu Jesus aos onze, quando estavam à mesa, e censurou-lhes a incredulidade e dureza de coração, porque não deram crédito aos que o tinham visto já ressuscitado.

[[v41-16-15]]

^<<v41-16-15,15>>^ E disse-lhes: Ide por todo o mundo e pregai o evangelho a toda criatura.

[[v41-16-16]]

^<<v41-16-16,16>>^ Quem crer e for batizado será salvo; quem, porém, não crer será condenado.

[[v41-16-17]]

^<<v41-16-17,17>>^ Estes sinais hão de acompanhar aqueles que creem: em meu nome, expelirão demônios; falarão novas línguas;

[[v41-16-18]]

^<<v41-16-18,18>>^ pegarão em serpentes; e, se alguma coisa mortífera beberem, não lhes fará mal; se impuserem as mãos sobre enfermos, eles ficarão curados.

[[v41-16-19]]

^<<v41-16-19,19>>^ De fato, o Senhor Jesus, depois de lhes ter falado, foi recebido no céu e assentou-se à destra de Deus.

[[v41-16-20]]

^<<v41-16-20,20>>^ E eles, tendo partido, pregaram em toda parte, cooperando com eles o Senhor e confirmando a palavra por meio de sinais, que se seguiam.

'''

xref:041-marcos/041-marcos-015.adoc#v41-15-0[&#60; Capítulo Anterior] | <<v41-16-0,Topo>> | xref:042-lucas/042-lucas-001.adoc#v42-1-0[Próximo Capítulo &#62;]