include::./index.adoc[]

[[v41-7-0]]
=== Marcos, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v41-7-1]]

^<<v41-7-1,1>>^ Ora, reuniram-se a Jesus os fariseus e alguns escribas, vindos de Jerusalém.

[[v41-7-2]]

^<<v41-7-2,2>>^ E, vendo que alguns dos discípulos dele comiam pão com as mãos impuras, isto é, por lavar

[[v41-7-3]]

^<<v41-7-3,3>>^ (pois os fariseus e todos os judeus, observando a tradição dos anciãos, não comem sem lavar cuidadosamente as mãos;

[[v41-7-4]]

^<<v41-7-4,4>>^ quando voltam da praça, não comem sem se aspergirem; e há muitas outras coisas que receberam para observar, como a lavagem de copos, jarros e vasos de metal [e camas]),

[[v41-7-5]]

^<<v41-7-5,5>>^ interpelaram-no os fariseus e os escribas: Por que não andam os teus discípulos de conformidade com a tradição dos anciãos, mas comem com as mãos por lavar?

[[v41-7-6]]

^<<v41-7-6,6>>^ Respondeu-lhes: Bem profetizou Isaías a respeito de vós, hipócritas, como está escrito: Este povo honra-me com os lábios, mas o seu coração está longe de mim.

[[v41-7-7]]

^<<v41-7-7,7>>^ E em vão me adoram, ensinando doutrinas que são preceitos de homens.

[[v41-7-8]]

^<<v41-7-8,8>>^ Negligenciando o mandamento de Deus, guardais a tradição dos homens.

[[v41-7-9]]

^<<v41-7-9,9>>^ E disse-lhes ainda: Jeitosamente rejeitais o preceito de Deus para guardardes a vossa própria tradição.

[[v41-7-10]]

^<<v41-7-10,10>>^ Pois Moisés disse: Honra a teu pai e a tua mãe; e: Quem maldisser a seu pai ou a sua mãe seja punido de morte.

[[v41-7-11]]

^<<v41-7-11,11>>^ Vós, porém, dizeis: Se um homem disser a seu pai ou a sua mãe: Aquilo que poderias aproveitar de mim é Corbã, isto é, oferta para o Senhor,

[[v41-7-12]]

^<<v41-7-12,12>>^ então, o dispensais de fazer qualquer coisa em favor de seu pai ou de sua mãe,

[[v41-7-13]]

^<<v41-7-13,13>>^ invalidando a palavra de Deus pela vossa própria tradição, que vós mesmos transmitistes; e fazeis muitas outras coisas semelhantes.

[[v41-7-14]]

^<<v41-7-14,14>>^ Convocando ele, de novo, a multidão, disse-lhes: Ouvi-me, todos, e entendei.

[[v41-7-15]]

^<<v41-7-15,15>>^ Nada há fora do homem que, entrando nele, o possa contaminar; mas o que sai do homem é o que o contamina.

[[v41-7-16]]

^<<v41-7-16,16>>^ [Se alguém tem ouvidos para ouvir, ouça.]

[[v41-7-17]]

^<<v41-7-17,17>>^ Quando entrou em casa, deixando a multidão, os seus discípulos o interrogaram acerca da parábola.

[[v41-7-18]]

^<<v41-7-18,18>>^ Então, lhes disse: Assim vós também não entendeis? Não compreendeis que tudo o que de fora entra no homem não o pode contaminar,

[[v41-7-19]]

^<<v41-7-19,19>>^ porque não lhe entra no coração, mas no ventre, e sai para lugar escuso? E, assim, considerou ele puros todos os alimentos.

[[v41-7-20]]

^<<v41-7-20,20>>^ E dizia: O que sai do homem, isso é o que o contamina.

[[v41-7-21]]

^<<v41-7-21,21>>^ Porque de dentro, do coração dos homens, é que procedem os maus desígnios, a prostituição, os furtos, os homicídios, os adultérios,

[[v41-7-22]]

^<<v41-7-22,22>>^ a avareza, as malícias, o dolo, a lascívia, a inveja, a blasfêmia, a soberba, a loucura.

[[v41-7-23]]

^<<v41-7-23,23>>^ Ora, todos estes males vêm de dentro e contaminam o homem.

[[v41-7-24]]

^<<v41-7-24,24>>^ Levantando-se, partiu dali para as terras de Tiro [e Sidom]. Tendo entrado numa casa, queria que ninguém o soubesse; no entanto, não pôde ocultar-se,

[[v41-7-25]]

^<<v41-7-25,25>>^ porque uma mulher, cuja filhinha estava possessa de espírito imundo, tendo ouvido a respeito dele, veio e prostrou-se-lhe aos pés.

[[v41-7-26]]

^<<v41-7-26,26>>^ Esta mulher era grega, de origem siro-fenícia, e rogava-lhe que expelisse de sua filha o demônio.

[[v41-7-27]]

^<<v41-7-27,27>>^ Mas Jesus lhe disse: Deixa primeiro que se fartem os filhos, porque não é bom tomar o pão dos filhos e lançá-lo aos cachorrinhos.

[[v41-7-28]]

^<<v41-7-28,28>>^ Ela, porém, lhe respondeu: Sim, Senhor; mas os cachorrinhos, debaixo da mesa, comem das migalhas das crianças.

[[v41-7-29]]

^<<v41-7-29,29>>^ Então, lhe disse: Por causa desta palavra, podes ir; o demônio já saiu de tua filha.

[[v41-7-30]]

^<<v41-7-30,30>>^ Voltando ela para casa, achou a menina sobre a cama, pois o demônio a deixara.

[[v41-7-31]]

^<<v41-7-31,31>>^ De novo, se retirou das terras de Tiro e foi por Sidom até ao mar da Galileia, através do território de Decápolis.

[[v41-7-32]]

^<<v41-7-32,32>>^ Então, lhe trouxeram um surdo e gago e lhe suplicaram que impusesse as mãos sobre ele.

[[v41-7-33]]

^<<v41-7-33,33>>^ Jesus, tirando-o da multidão, à parte, pôs-lhe os dedos nos ouvidos e lhe tocou a língua com saliva;

[[v41-7-34]]

^<<v41-7-34,34>>^ depois, erguendo os olhos ao céu, suspirou e disse: Efatá!,  que quer dizer: Abre-te!

[[v41-7-35]]

^<<v41-7-35,35>>^ Abriram-se-lhe os ouvidos, e logo se lhe soltou o empecilho da língua, e falava desembaraçadamente.

[[v41-7-36]]

^<<v41-7-36,36>>^ Mas lhes ordenou que a ninguém o dissessem; contudo, quanto mais recomendava, tanto mais eles o divulgavam.

[[v41-7-37]]

^<<v41-7-37,37>>^ Maravilhavam-se sobremaneira, dizendo: Tudo ele tem feito esplendidamente bem; não somente faz ouvir os surdos, como falar os mudos.

'''

xref:041-marcos/041-marcos-006.adoc#v41-6-0[&#60; Capítulo Anterior] | <<v41-7-0,Topo>> | xref:041-marcos/041-marcos-008.adoc#v41-8-0[Próximo Capítulo &#62;]