include::./index.adoc[]

[[v41-5-0]]
=== Marcos, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v41-5-1]]

^<<v41-5-1,1>>^ Entrementes, chegaram à outra margem do mar, à terra dos gerasenos.

[[v41-5-2]]

^<<v41-5-2,2>>^ Ao desembarcar, logo veio dos sepulcros, ao seu encontro, um homem possesso de espírito imundo,

[[v41-5-3]]

^<<v41-5-3,3>>^ o qual vivia nos sepulcros, e nem mesmo com cadeias alguém podia prendê-lo;

[[v41-5-4]]

^<<v41-5-4,4>>^ porque, tendo sido muitas vezes preso com grilhões e cadeias, as cadeias foram quebradas por ele, e os grilhões, despedaçados. E ninguém podia subjugá-lo.

[[v41-5-5]]

^<<v41-5-5,5>>^ Andava sempre, de noite e de dia, clamando por entre os sepulcros e pelos montes, ferindo-se com pedras.

[[v41-5-6]]

^<<v41-5-6,6>>^ Quando, de longe, viu Jesus, correu e o adorou,

[[v41-5-7]]

^<<v41-5-7,7>>^ exclamando com alta voz: Que tenho eu contigo, Jesus, Filho do Deus Altíssimo? Conjuro-te por Deus que não me atormentes!

[[v41-5-8]]

^<<v41-5-8,8>>^ Porque Jesus lhe dissera: Espírito imundo, sai desse homem!

[[v41-5-9]]

^<<v41-5-9,9>>^ E perguntou-lhe: Qual é o teu nome?  Respondeu ele: Legião é o meu nome, porque somos muitos.

[[v41-5-10]]

^<<v41-5-10,10>>^ E rogou-lhe encarecidamente que os não mandasse para fora do país.

[[v41-5-11]]

^<<v41-5-11,11>>^ Ora, pastava ali pelo monte uma grande manada de porcos.

[[v41-5-12]]

^<<v41-5-12,12>>^ E os espíritos imundos rogaram a Jesus, dizendo: Manda-nos para os porcos, para que entremos neles.

[[v41-5-13]]

^<<v41-5-13,13>>^ Jesus o permitiu. Então, saindo os espíritos imundos, entraram nos porcos; e a manada, que era cerca de dois mil, precipitou-se despenhadeiro abaixo, para dentro do mar, onde se afogaram.

[[v41-5-14]]

^<<v41-5-14,14>>^ Os porqueiros fugiram e o anunciaram na cidade e pelos campos. Então, saiu o povo para ver o que sucedera.

[[v41-5-15]]

^<<v41-5-15,15>>^ Indo ter com Jesus, viram o endemoninhado, o que tivera a legião, assentado, vestido, em perfeito juízo; e temeram.

[[v41-5-16]]

^<<v41-5-16,16>>^ Os que haviam presenciado os fatos contaram-lhes o que acontecera ao endemoninhado e acerca dos porcos.

[[v41-5-17]]

^<<v41-5-17,17>>^ E entraram a rogar-lhe que se retirasse da terra deles.

[[v41-5-18]]

^<<v41-5-18,18>>^ Ao entrar Jesus no barco, suplicava-lhe o que fora endemoninhado que o deixasse estar com ele.

[[v41-5-19]]

^<<v41-5-19,19>>^ Jesus, porém, não lho permitiu, mas ordenou-lhe: Vai para tua casa, para os teus. Anuncia-lhes tudo o que o Senhor te fez e como teve compaixão de ti.

[[v41-5-20]]

^<<v41-5-20,20>>^ Então, ele foi e começou a proclamar em Decápolis tudo o que Jesus lhe fizera; e todos se admiravam.

[[v41-5-21]]

^<<v41-5-21,21>>^ Tendo Jesus voltado no barco, para o outro lado, afluiu para ele grande multidão; e ele estava junto do mar.

[[v41-5-22]]

^<<v41-5-22,22>>^ Eis que se chegou a ele um dos principais da sinagoga, chamado Jairo, e, vendo-o, prostrou-se a seus pés

[[v41-5-23]]

^<<v41-5-23,23>>^ e insistentemente lhe suplicou: Minha filhinha está à morte; vem, impõe as mãos sobre ela, para que seja salva, e viverá.

[[v41-5-24]]

^<<v41-5-24,24>>^ Jesus foi com ele. Grande multidão o seguia, comprimindo-o.

[[v41-5-25]]

^<<v41-5-25,25>>^ Aconteceu que certa mulher, que, havia doze anos, vinha sofrendo de uma hemorragia

[[v41-5-26]]

^<<v41-5-26,26>>^ e muito padecera à mão de vários médicos, tendo despendido tudo quanto possuía, sem, contudo, nada aproveitar, antes, pelo contrário, indo a pior,

[[v41-5-27]]

^<<v41-5-27,27>>^ tendo ouvido a fama de Jesus, vindo por trás dele, por entre a multidão, tocou-lhe a veste.

[[v41-5-28]]

^<<v41-5-28,28>>^ Porque, dizia: Se eu apenas lhe tocar as vestes, ficarei curada.

[[v41-5-29]]

^<<v41-5-29,29>>^ E logo se lhe estancou a hemorragia, e sentiu no corpo estar curada do seu flagelo.

[[v41-5-30]]

^<<v41-5-30,30>>^ Jesus, reconhecendo imediatamente que dele saíra poder, virando-se no meio da multidão, perguntou: Quem me tocou nas vestes?

[[v41-5-31]]

^<<v41-5-31,31>>^ Responderam-lhe seus discípulos: Vês que a multidão te aperta e dizes: Quem me tocou?

[[v41-5-32]]

^<<v41-5-32,32>>^ Ele, porém, olhava ao redor para ver quem fizera isto.

[[v41-5-33]]

^<<v41-5-33,33>>^ Então, a mulher, atemorizada e tremendo, cônscia do que nela se operara, veio, prostrou-se diante dele e declarou-lhe toda a verdade.

[[v41-5-34]]

^<<v41-5-34,34>>^ E ele lhe disse: Filha, a tua fé te salvou; vai-te em paz e fica livre do teu mal.

[[v41-5-35]]

^<<v41-5-35,35>>^ Falava ele ainda, quando chegaram alguns da casa do chefe da sinagoga, a quem disseram: Tua filha já morreu; por que ainda incomodas o Mestre?

[[v41-5-36]]

^<<v41-5-36,36>>^ Mas Jesus, sem acudir a tais palavras, disse ao chefe da sinagoga: Não temas, crê somente.

[[v41-5-37]]

^<<v41-5-37,37>>^ Contudo, não permitiu que alguém o acompanhasse, senão Pedro e os irmãos Tiago e João.

[[v41-5-38]]

^<<v41-5-38,38>>^ Chegando à casa do chefe da sinagoga, viu Jesus o alvoroço, os que choravam e os que pranteavam muito.

[[v41-5-39]]

^<<v41-5-39,39>>^ Ao entrar, lhes disse: Por que estais em alvoroço e chorais? A criança não está morta, mas dorme.

[[v41-5-40]]

^<<v41-5-40,40>>^ E riam-se dele. Tendo ele, porém, mandado sair a todos, tomou o pai e a mãe da criança e os que vieram com ele e entrou onde ela estava.

[[v41-5-41]]

^<<v41-5-41,41>>^ Tomando-a pela mão, disse: Talitá cumi!,  que quer dizer: Menina, eu te mando, levanta-te!

[[v41-5-42]]

^<<v41-5-42,42>>^ Imediatamente, a menina se levantou e pôs-se a andar; pois tinha doze anos. Então, ficaram todos sobremaneira admirados.

[[v41-5-43]]

^<<v41-5-43,43>>^ Mas Jesus ordenou-lhes expressamente que ninguém o soubesse; e mandou que dessem de comer à menina.

'''

xref:041-marcos/041-marcos-004.adoc#v41-4-0[&#60; Capítulo Anterior] | <<v41-5-0,Topo>> | xref:041-marcos/041-marcos-006.adoc#v41-6-0[Próximo Capítulo &#62;]