include::./index.adoc[]

[[v41-10-0]]
=== Marcos, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v41-10-1]]

^<<v41-10-1,1>>^ Levantando-se Jesus, foi dali para o território da Judeia, além do Jordão. E outra vez as multidões se reuniram junto a ele, e, de novo, ele as ensinava, segundo o seu costume.

[[v41-10-2]]

^<<v41-10-2,2>>^ E, aproximando-se alguns fariseus, o experimentaram, perguntando-lhe: É lícito ao marido repudiar sua mulher?

[[v41-10-3]]

^<<v41-10-3,3>>^ Ele lhes respondeu: Que vos ordenou Moisés?

[[v41-10-4]]

^<<v41-10-4,4>>^ Tornaram eles: Moisés permitiu lavrar carta de divórcio e repudiar.

[[v41-10-5]]

^<<v41-10-5,5>>^ Mas Jesus lhes disse: Por causa da dureza do vosso coração, ele vos deixou escrito esse mandamento;

[[v41-10-6]]

^<<v41-10-6,6>>^ porém, desde o princípio da criação, Deus os fez homem e mulher.

[[v41-10-7]]

^<<v41-10-7,7>>^ Por isso, deixará o homem a seu pai e mãe [e unir-se-á a sua mulher],

[[v41-10-8]]

^<<v41-10-8,8>>^ e, com sua mulher, serão os dois uma só carne. De modo que já não são dois, mas uma só carne.

[[v41-10-9]]

^<<v41-10-9,9>>^ Portanto, o que Deus ajuntou não separe o homem.

[[v41-10-10]]

^<<v41-10-10,10>>^ Em casa, voltaram os discípulos a interrogá-lo sobre este assunto.

[[v41-10-11]]

^<<v41-10-11,11>>^ E ele lhes disse: Quem repudiar sua mulher e casar com outra comete adultério contra aquela.

[[v41-10-12]]

^<<v41-10-12,12>>^ E, se ela repudiar seu marido e casar com outro, comete adultério.

[[v41-10-13]]

^<<v41-10-13,13>>^ Então, lhe trouxeram algumas crianças para que as tocasse, mas os discípulos os repreendiam.

[[v41-10-14]]

^<<v41-10-14,14>>^ Jesus, porém, vendo isto, indignou-se e disse-lhes: Deixai vir a mim os pequeninos, não os embaraceis, porque dos tais é o reino de Deus.

[[v41-10-15]]

^<<v41-10-15,15>>^ Em verdade vos digo: Quem não receber o reino de Deus como uma criança de maneira nenhuma entrará nele.

[[v41-10-16]]

^<<v41-10-16,16>>^ Então, tomando-as nos braços e impondo-lhes as mãos, as abençoava.

[[v41-10-17]]

^<<v41-10-17,17>>^ E, pondo-se Jesus a caminho, correu um homem ao seu encontro e, ajoelhando-se, perguntou-lhe: Bom Mestre, que farei para herdar a vida eterna?

[[v41-10-18]]

^<<v41-10-18,18>>^ Respondeu-lhe Jesus: Por que me chamas bom? Ninguém é bom senão um, que é Deus.

[[v41-10-19]]

^<<v41-10-19,19>>^ Sabes os mandamentos: Não matarás, não adulterarás, não furtarás, não dirás falso testemunho, não defraudarás ninguém, honra a teu pai e tua mãe.

[[v41-10-20]]

^<<v41-10-20,20>>^ Então, ele respondeu: Mestre, tudo isso tenho observado desde a minha juventude.

[[v41-10-21]]

^<<v41-10-21,21>>^ E Jesus, fitando-o, o amou e disse: Só uma coisa te falta: Vai, vende tudo o que tens, dá-o aos pobres e terás um tesouro no céu; então, vem e segue-me.

[[v41-10-22]]

^<<v41-10-22,22>>^ Ele, porém, contrariado com esta palavra, retirou-se triste, porque era dono de muitas propriedades.

[[v41-10-23]]

^<<v41-10-23,23>>^ Então, Jesus, olhando ao redor, disse aos seus discípulos: Quão dificilmente entrarão no reino de Deus os que têm riquezas!

[[v41-10-24]]

^<<v41-10-24,24>>^ Os discípulos estranharam estas palavras; mas Jesus insistiu em dizer-lhes: Filhos, quão difícil é [para os que confiam nas riquezas] entrar no reino de Deus!

[[v41-10-25]]

^<<v41-10-25,25>>^ É mais fácil passar um camelo pelo fundo de uma agulha do que entrar um rico no reino de Deus.

[[v41-10-26]]

^<<v41-10-26,26>>^ Eles ficaram sobremodo maravilhados, dizendo entre si: Então, quem pode ser salvo?

[[v41-10-27]]

^<<v41-10-27,27>>^ Jesus, porém, fitando neles o olhar, disse: Para os homens é impossível; contudo, não para Deus, porque para Deus tudo é possível.

[[v41-10-28]]

^<<v41-10-28,28>>^ Então, Pedro começou a dizer-lhe: Eis que nós tudo deixamos e te seguimos.

[[v41-10-29]]

^<<v41-10-29,29>>^ Tornou Jesus: Em verdade vos digo que ninguém há que tenha deixado casa, ou irmãos, ou irmãs, ou mãe, ou pai, ou filhos, ou campos por amor de mim e por amor do evangelho,

[[v41-10-30]]

^<<v41-10-30,30>>^ que não receba, já no presente, o cêntuplo de casas, irmãos, irmãs, mães, filhos e campos, com perseguições; e, no mundo por vir, a vida eterna.

[[v41-10-31]]

^<<v41-10-31,31>>^ Porém muitos primeiros serão últimos; e os últimos, primeiros.

[[v41-10-32]]

^<<v41-10-32,32>>^ Estavam de caminho, subindo para Jerusalém, e Jesus ia adiante dos seus discípulos. Estes se admiravam e o seguiam tomados de apreensões. E Jesus, tornando a levar à parte os doze, passou a revelar-lhes as coisas que lhe deviam sobrevir, dizendo:

[[v41-10-33]]

^<<v41-10-33,33>>^ Eis que subimos para Jerusalém, e o Filho do Homem será entregue aos principais sacerdotes e aos escribas; condená-lo-ão à morte e o entregarão aos gentios;

[[v41-10-34]]

^<<v41-10-34,34>>^ hão de escarnecê-lo, cuspir nele, açoitá-lo e matá-lo; mas, depois de três dias, ressuscitará.

[[v41-10-35]]

^<<v41-10-35,35>>^ Então, se aproximaram dele Tiago e João, filhos de Zebedeu, dizendo-lhe: Mestre, queremos que nos concedas o que te vamos pedir.

[[v41-10-36]]

^<<v41-10-36,36>>^ E ele lhes perguntou: Que quereis que vos faça?

[[v41-10-37]]

^<<v41-10-37,37>>^ Responderam-lhe: Permite-nos que, na tua glória, nos assentemos um à tua direita e o outro à tua esquerda.

[[v41-10-38]]

^<<v41-10-38,38>>^ Mas Jesus lhes disse: Não sabeis o que pedis. Podeis vós beber o cálice que eu bebo ou receber o batismo com que eu sou batizado?

[[v41-10-39]]

^<<v41-10-39,39>>^ Disseram-lhe: Podemos. Tornou-lhes Jesus: Bebereis o cálice que eu bebo e recebereis o batismo com que eu sou batizado;

[[v41-10-40]]

^<<v41-10-40,40>>^ quanto, porém, ao assentar-se à minha direita ou à minha esquerda, não me compete concedê-lo; porque é para aqueles a quem está preparado.

[[v41-10-41]]

^<<v41-10-41,41>>^ Ouvindo isto, indignaram-se os dez contra Tiago e João.

[[v41-10-42]]

^<<v41-10-42,42>>^ Mas Jesus, chamando-os para junto de si, disse-lhes: Sabeis que os que são considerados governadores dos povos têm-nos sob seu domínio, e sobre eles os seus maiorais exercem autoridade.

[[v41-10-43]]

^<<v41-10-43,43>>^ Mas entre vós não é assim; pelo contrário, quem quiser tornar-se grande entre vós, será esse o que vos sirva;

[[v41-10-44]]

^<<v41-10-44,44>>^ e quem quiser ser o primeiro entre vós será servo de todos.

[[v41-10-45]]

^<<v41-10-45,45>>^ Pois o próprio Filho do Homem não veio para ser servido, mas para servir e dar a sua vida em resgate por muitos.

[[v41-10-46]]

^<<v41-10-46,46>>^ E foram para Jericó. Quando ele saía de Jericó, juntamente com os discípulos e numerosa multidão, Bartimeu, cego mendigo, filho de Timeu, estava assentado à beira do caminho

[[v41-10-47]]

^<<v41-10-47,47>>^ e, ouvindo que era Jesus, o Nazareno, pôs-se a clamar: Jesus, Filho de Davi, tem compaixão de mim!

[[v41-10-48]]

^<<v41-10-48,48>>^ E muitos o repreendiam, para que se calasse; mas ele cada vez gritava mais: Filho de Davi, tem misericórdia de mim!

[[v41-10-49]]

^<<v41-10-49,49>>^ Parou Jesus e disse: Chamai-o.  Chamaram, então, o cego, dizendo-lhe: Tem bom ânimo; levanta-te, ele te chama.

[[v41-10-50]]

^<<v41-10-50,50>>^ Lançando de si a capa, levantou-se de um salto e foi ter com Jesus.

[[v41-10-51]]

^<<v41-10-51,51>>^ Perguntou-lhe Jesus: Que queres que eu te faça?  Respondeu o cego: Mestre, que eu torne a ver.

[[v41-10-52]]

^<<v41-10-52,52>>^ Então, Jesus lhe disse: Vai, a tua fé te salvou.  E imediatamente tornou a ver e seguia a Jesus estrada fora.

'''

xref:041-marcos/041-marcos-009.adoc#v41-9-0[&#60; Capítulo Anterior] | <<v41-10-0,Topo>> | xref:041-marcos/041-marcos-011.adoc#v41-11-0[Próximo Capítulo &#62;]