include::./index.adoc[]

[[v41-9-0]]
=== Marcos, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v41-9-1]]

^<<v41-9-1,1>>^ Dizia-lhes ainda: Em verdade vos afirmo que, dos que aqui se encontram, alguns há que, de maneira nenhuma, passarão pela morte até que vejam ter chegado com poder o reino de Deus.

[[v41-9-2]]

^<<v41-9-2,2>>^ Seis dias depois, tomou Jesus consigo a Pedro, Tiago e João e levou-os sós, à parte, a um alto monte. Foi transfigurado diante deles;

[[v41-9-3]]

^<<v41-9-3,3>>^ as suas vestes tornaram-se resplandecentes e sobremodo brancas, como nenhum lavandeiro na terra as poderia alvejar.

[[v41-9-4]]

^<<v41-9-4,4>>^ Apareceu-lhes Elias com Moisés, e estavam falando com Jesus.

[[v41-9-5]]

^<<v41-9-5,5>>^ Então, Pedro, tomando a palavra, disse: Mestre, bom é estarmos aqui e que façamos três tendas: uma será tua, outra, para Moisés, e outra, para Elias.

[[v41-9-6]]

^<<v41-9-6,6>>^ Pois não sabia o que dizer, por estarem eles aterrados.

[[v41-9-7]]

^<<v41-9-7,7>>^ A seguir, veio uma nuvem que os envolveu; e dela uma voz dizia: Este é o meu Filho amado; a ele ouvi.

[[v41-9-8]]

^<<v41-9-8,8>>^ E, de relance, olhando ao redor, a ninguém mais viram com eles, senão Jesus.

[[v41-9-9]]

^<<v41-9-9,9>>^ Ao descerem do monte, ordenou-lhes Jesus que não divulgassem as coisas que tinham visto, até o dia em que o Filho do Homem ressuscitasse dentre os mortos.

[[v41-9-10]]

^<<v41-9-10,10>>^ Eles guardaram a recomendação, perguntando uns aos outros que seria o ressuscitar dentre os mortos.

[[v41-9-11]]

^<<v41-9-11,11>>^ E interrogaram-no, dizendo: Por que dizem os escribas ser necessário que Elias venha primeiro?

[[v41-9-12]]

^<<v41-9-12,12>>^ Então, ele lhes disse: Elias, vindo primeiro, restaurará todas as coisas; como, pois, está escrito sobre o Filho do Homem que sofrerá muito e será aviltado?

[[v41-9-13]]

^<<v41-9-13,13>>^ Eu, porém, vos digo que Elias já veio, e fizeram com ele tudo o que quiseram, como a seu respeito está escrito.

[[v41-9-14]]

^<<v41-9-14,14>>^ Quando eles se aproximaram dos discípulos, viram numerosa multidão ao redor e que os escribas discutiam com eles.

[[v41-9-15]]

^<<v41-9-15,15>>^ E logo toda a multidão, ao ver Jesus, tomada de surpresa, correu para ele e o saudava.

[[v41-9-16]]

^<<v41-9-16,16>>^ Então, ele interpelou os escribas: Que é que discutíeis com eles?

[[v41-9-17]]

^<<v41-9-17,17>>^ E um, dentre a multidão, respondeu: Mestre, trouxe-te o meu filho, possesso de um espírito mudo;

[[v41-9-18]]

^<<v41-9-18,18>>^ e este, onde quer que o apanha, lança-o por terra, e ele espuma, rilha os dentes e vai definhando. Roguei a teus discípulos que o expelissem, e eles não puderam.

[[v41-9-19]]

^<<v41-9-19,19>>^ Então, Jesus lhes disse: Ó geração incrédula, até quando estarei convosco? Até quando vos sofrerei? Trazei-mo.

[[v41-9-20]]

^<<v41-9-20,20>>^ E trouxeram-lho; quando ele viu a Jesus, o espírito imediatamente o agitou com violência, e, caindo ele por terra, revolvia-se espumando.

[[v41-9-21]]

^<<v41-9-21,21>>^ Perguntou Jesus ao pai do menino: Há quanto tempo isto lhe sucede?  Desde a infância, respondeu;

[[v41-9-22]]

^<<v41-9-22,22>>^ e muitas vezes o tem lançado no fogo e na água, para o matar; mas, se tu podes alguma coisa, tem compaixão de nós e ajuda-nos.

[[v41-9-23]]

^<<v41-9-23,23>>^ Ao que lhe respondeu Jesus: Se podes! Tudo é possível ao que crê.

[[v41-9-24]]

^<<v41-9-24,24>>^ E imediatamente o pai do menino exclamou [com lágrimas]: Eu creio! Ajuda-me na minha falta de fé!

[[v41-9-25]]

^<<v41-9-25,25>>^ Vendo Jesus que a multidão concorria, repreendeu o espírito imundo, dizendo-lhe: Espírito mudo e surdo, eu te ordeno: Sai deste jovem e nunca mais tornes a ele.

[[v41-9-26]]

^<<v41-9-26,26>>^ E ele, clamando e agitando-o muito, saiu, deixando-o como se estivesse morto, a ponto de muitos dizerem: Morreu.

[[v41-9-27]]

^<<v41-9-27,27>>^ Mas Jesus, tomando-o pela mão, o ergueu, e ele se levantou.

[[v41-9-28]]

^<<v41-9-28,28>>^ Quando entrou em casa, os seus discípulos lhe perguntaram em particular: Por que não pudemos nós expulsá-lo?

[[v41-9-29]]

^<<v41-9-29,29>>^ Respondeu-lhes: Esta casta não pode sair senão por meio de oração [e jejum].

[[v41-9-30]]

^<<v41-9-30,30>>^ E, tendo partido dali, passavam pela Galileia, e não queria que ninguém o soubesse;

[[v41-9-31]]

^<<v41-9-31,31>>^ porque ensinava os seus discípulos e lhes dizia: O Filho do Homem será entregue nas mãos dos homens, e o matarão; mas, três dias depois da sua morte, ressuscitará.

[[v41-9-32]]

^<<v41-9-32,32>>^ Eles, contudo, não compreendiam isto e temiam interrogá-lo.

[[v41-9-33]]

^<<v41-9-33,33>>^ Tendo eles partido para Cafarnaum, estando ele em casa, interrogou os discípulos: De que é que discorríeis pelo caminho?

[[v41-9-34]]

^<<v41-9-34,34>>^ Mas eles guardaram silêncio; porque, pelo caminho, haviam discutido entre si sobre quem era o maior.

[[v41-9-35]]

^<<v41-9-35,35>>^ E ele, assentando-se, chamou os doze e lhes disse: Se alguém quer ser o primeiro, será o último e servo de todos.

[[v41-9-36]]

^<<v41-9-36,36>>^ Trazendo uma criança, colocou-a no meio deles e, tomando-a nos braços, disse-lhes:

[[v41-9-37]]

^<<v41-9-37,37>>^ Qualquer que receber uma criança, tal como esta, em meu nome, a mim me recebe; e qualquer que a mim me receber, não recebe a mim, mas ao que me enviou.

[[v41-9-38]]

^<<v41-9-38,38>>^ Disse-lhe João: Mestre, vimos um homem que, em teu nome, expelia demônios, o qual não nos segue; e nós lho proibimos, porque não seguia conosco.

[[v41-9-39]]

^<<v41-9-39,39>>^ Mas Jesus respondeu: Não lho proibais; porque ninguém há que faça milagre em meu nome e, logo a seguir, possa falar mal de mim.

[[v41-9-40]]

^<<v41-9-40,40>>^ Pois quem não é contra nós é por nós.

[[v41-9-41]]

^<<v41-9-41,41>>^ Porquanto, aquele que vos der de beber um copo de água, em meu nome, porque sois de Cristo, em verdade vos digo que de modo algum perderá o seu galardão.

[[v41-9-42]]

^<<v41-9-42,42>>^ E quem fizer tropeçar a um destes pequeninos crentes, melhor lhe fora que se lhe pendurasse ao pescoço uma grande pedra de moinho, e fosse lançado no mar.

[[v41-9-43]]

^<<v41-9-43,43>>^ E, se tua mão te faz tropeçar, corta-a; pois é melhor entrares maneta na vida do que, tendo as duas mãos, ires para o inferno, para o fogo inextinguível

[[v41-9-44]]

^<<v41-9-44,44>>^ [onde não lhes morre o verme, nem o fogo se apaga].

[[v41-9-45]]

^<<v41-9-45,45>>^ E, se teu pé te faz tropeçar, corta-o; é melhor entrares na vida aleijado do que, tendo os dois pés, seres lançado no inferno

[[v41-9-46]]

^<<v41-9-46,46>>^ [onde não lhes morre o verme, nem o fogo se apaga].

[[v41-9-47]]

^<<v41-9-47,47>>^ E, se um dos teus olhos te faz tropeçar, arranca-o; é melhor entrares no reino de Deus com um só dos teus olhos do que, tendo os dois seres lançado no inferno,

[[v41-9-48]]

^<<v41-9-48,48>>^ onde não lhes morre o verme, nem o fogo se apaga.

[[v41-9-49]]

^<<v41-9-49,49>>^ Porque cada um será salgado com fogo.

[[v41-9-50]]

^<<v41-9-50,50>>^ Bom é o sal; mas, se o sal vier a tornar-se insípido, como lhe restaurar o sabor? Tende sal em vós mesmos e paz uns com os outros.

'''

xref:041-marcos/041-marcos-008.adoc#v41-8-0[&#60; Capítulo Anterior] | <<v41-9-0,Topo>> | xref:041-marcos/041-marcos-010.adoc#v41-10-0[Próximo Capítulo &#62;]