include::./index.adoc[]

[[v43-9-0]]
=== João, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-9-1]]

^<<v43-9-1,1>>^ Caminhando Jesus, viu um homem cego de nascença.

[[v43-9-2]]

^<<v43-9-2,2>>^ E os seus discípulos perguntaram: Mestre, quem pecou, este ou seus pais, para que nascesse cego?

[[v43-9-3]]

^<<v43-9-3,3>>^ Respondeu Jesus: Nem ele pecou, nem seus pais; mas foi para que se manifestem nele as obras de Deus.

[[v43-9-4]]

^<<v43-9-4,4>>^ É necessário que façamos as obras daquele que me enviou, enquanto é dia; a noite vem, quando ninguém pode trabalhar.

[[v43-9-5]]

^<<v43-9-5,5>>^ Enquanto estou no mundo, sou a luz do mundo.

[[v43-9-6]]

^<<v43-9-6,6>>^ Dito isso, cuspiu na terra e, tendo feito lodo com a saliva, aplicou-o aos olhos do cego,

[[v43-9-7]]

^<<v43-9-7,7>>^ dizendo-lhe: Vai, lava-te no tanque de Siloé  (que quer dizer Enviado). Ele foi, lavou-se e voltou vendo.

[[v43-9-8]]

^<<v43-9-8,8>>^ Então, os vizinhos e os que dantes o conheciam de vista, como mendigo, perguntavam: Não é este o que estava assentado pedindo esmolas?

[[v43-9-9]]

^<<v43-9-9,9>>^ Uns diziam: É ele. Outros: Não, mas se parece com ele. Ele mesmo, porém, dizia: Sou eu.

[[v43-9-10]]

^<<v43-9-10,10>>^ Perguntaram-lhe, pois: Como te foram abertos os olhos?

[[v43-9-11]]

^<<v43-9-11,11>>^ Respondeu ele: O homem chamado Jesus fez lodo, untou-me os olhos e disse-me: Vai ao tanque de Siloé e lava-te. Então, fui, lavei-me e estou vendo.

[[v43-9-12]]

^<<v43-9-12,12>>^ Disseram-lhe, pois: Onde está ele? Respondeu: Não sei.

[[v43-9-13]]

^<<v43-9-13,13>>^ Levaram, pois, aos fariseus o que dantes fora cego.

[[v43-9-14]]

^<<v43-9-14,14>>^ E era sábado o dia em que Jesus fez o lodo e lhe abriu os olhos.

[[v43-9-15]]

^<<v43-9-15,15>>^ Então, os fariseus, por sua vez, lhe perguntaram como chegara a ver; ao que lhes respondeu: Aplicou lodo aos meus olhos, lavei-me e estou vendo.

[[v43-9-16]]

^<<v43-9-16,16>>^ Por isso, alguns dos fariseus diziam: Esse homem não é de Deus, porque não guarda o sábado. Diziam outros: Como pode um homem pecador fazer tamanhos sinais? E houve dissensão entre eles.

[[v43-9-17]]

^<<v43-9-17,17>>^ De novo, perguntaram ao cego: Que dizes tu a respeito dele, visto que te abriu os olhos? Que é profeta, respondeu ele.

[[v43-9-18]]

^<<v43-9-18,18>>^ Não acreditaram os judeus que ele fora cego e que agora via, enquanto não lhe chamaram os pais

[[v43-9-19]]

^<<v43-9-19,19>>^ e os interrogaram: É este o vosso filho, de quem dizeis que nasceu cego? Como, pois, vê agora?

[[v43-9-20]]

^<<v43-9-20,20>>^ Então, os pais responderam: Sabemos que este é nosso filho e que nasceu cego;

[[v43-9-21]]

^<<v43-9-21,21>>^ mas não sabemos como vê agora; ou quem lhe abriu os olhos também não sabemos. Perguntai a ele, idade tem; falará de si mesmo.

[[v43-9-22]]

^<<v43-9-22,22>>^ Isto disseram seus pais porque estavam com medo dos judeus; pois estes já haviam assentado que, se alguém confessasse ser Jesus o Cristo, fosse expulso da sinagoga.

[[v43-9-23]]

^<<v43-9-23,23>>^ Por isso, é que disseram os pais: Ele idade tem, interrogai-o.

[[v43-9-24]]

^<<v43-9-24,24>>^ Então, chamaram, pela segunda vez, o homem que fora cego e lhe disseram: Dá glória a Deus; nós sabemos que esse homem é pecador.

[[v43-9-25]]

^<<v43-9-25,25>>^ Ele retrucou: Se é pecador, não sei; uma coisa sei: eu era cego e agora vejo.

[[v43-9-26]]

^<<v43-9-26,26>>^ Perguntaram-lhe, pois: Que te fez ele? como te abriu os olhos?

[[v43-9-27]]

^<<v43-9-27,27>>^ Ele lhes respondeu: Já vo-lo disse, e não atendestes; por que quereis ouvir outra vez? Porventura, quereis vós também tornar-vos seus discípulos?

[[v43-9-28]]

^<<v43-9-28,28>>^ Então, o injuriaram e lhe disseram: Discípulo dele és tu; mas nós somos discípulos de Moisés.

[[v43-9-29]]

^<<v43-9-29,29>>^ Sabemos que Deus falou a Moisés; mas este nem sabemos donde é.

[[v43-9-30]]

^<<v43-9-30,30>>^ Respondeu-lhes o homem: Nisto é de estranhar que vós não saibais donde ele é, e, contudo, me abriu os olhos.

[[v43-9-31]]

^<<v43-9-31,31>>^ Sabemos que Deus não atende a pecadores; mas, pelo contrário, se alguém teme a Deus e pratica a sua vontade, a este atende.

[[v43-9-32]]

^<<v43-9-32,32>>^ Desde que há mundo, jamais se ouviu que alguém tenha aberto os olhos a um cego de nascença.

[[v43-9-33]]

^<<v43-9-33,33>>^ Se este homem não fosse de Deus, nada poderia ter feito.

[[v43-9-34]]

^<<v43-9-34,34>>^ Mas eles retrucaram: Tu és nascido todo em pecado e nos ensinas a nós? E o expulsaram.

[[v43-9-35]]

^<<v43-9-35,35>>^ Ouvindo Jesus que o tinham expulsado, encontrando-o, lhe perguntou: Crês tu no Filho do Homem?

[[v43-9-36]]

^<<v43-9-36,36>>^ Ele respondeu e disse: Quem é, Senhor, para que eu nele creia?

[[v43-9-37]]

^<<v43-9-37,37>>^ E Jesus lhe disse: Já o tens visto, e é o que fala contigo.

[[v43-9-38]]

^<<v43-9-38,38>>^ Então, afirmou ele: Creio, Senhor; e o adorou.

[[v43-9-39]]

^<<v43-9-39,39>>^ Prosseguiu Jesus: Eu vim a este mundo para juízo, a fim de que os que não veem vejam, e os que veem se tornem cegos.

[[v43-9-40]]

^<<v43-9-40,40>>^ Alguns dentre os fariseus que estavam perto dele perguntaram-lhe: Acaso, também nós somos cegos?

[[v43-9-41]]

^<<v43-9-41,41>>^ Respondeu-lhes Jesus: Se fôsseis cegos, não teríeis pecado algum; mas, porque agora dizeis: Nós vemos, subsiste o vosso pecado.

'''

xref:043-joao/043-joao-008.adoc#v43-8-0[&#60; Capítulo Anterior] | <<v43-9-0,Topo>> | xref:043-joao/043-joao-010.adoc#v43-10-0[Próximo Capítulo &#62;]