include::./index.adoc[]

[[v43-10-0]]
=== João, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-10-1]]

^<<v43-10-1,1>>^ Em verdade, em verdade vos digo: o que não entra pela porta no aprisco das ovelhas, mas sobe por outra parte, esse é ladrão e salteador.

[[v43-10-2]]

^<<v43-10-2,2>>^ Aquele, porém, que entra pela porta, esse é o pastor das ovelhas.

[[v43-10-3]]

^<<v43-10-3,3>>^ Para este o porteiro abre, as ovelhas ouvem a sua voz, ele chama pelo nome as suas próprias ovelhas e as conduz para fora.

[[v43-10-4]]

^<<v43-10-4,4>>^ Depois de fazer sair todas as que lhe pertencem, vai adiante delas, e elas o seguem, porque lhe reconhecem a voz;

[[v43-10-5]]

^<<v43-10-5,5>>^ mas de modo nenhum seguirão o estranho; antes, fugirão dele, porque não conhecem a voz dos estranhos.

[[v43-10-6]]

^<<v43-10-6,6>>^ Jesus lhes propôs esta parábola, mas eles não compreenderam o sentido daquilo que lhes falava.

[[v43-10-7]]

^<<v43-10-7,7>>^ Jesus, pois, lhes afirmou de novo: Em verdade, em verdade vos digo: eu sou a porta das ovelhas.

[[v43-10-8]]

^<<v43-10-8,8>>^ Todos quantos vieram antes de mim são ladrões e salteadores; mas as ovelhas não lhes deram ouvido.

[[v43-10-9]]

^<<v43-10-9,9>>^ Eu sou a porta. Se alguém entrar por mim, será salvo; entrará, e sairá, e achará pastagem.

[[v43-10-10]]

^<<v43-10-10,10>>^ O ladrão vem somente para roubar, matar e destruir; eu vim para que tenham vida e a tenham em abundância.

[[v43-10-11]]

^<<v43-10-11,11>>^ Eu sou o bom pastor. O bom pastor dá a vida pelas ovelhas.

[[v43-10-12]]

^<<v43-10-12,12>>^ O mercenário, que não é pastor, a quem não pertencem as ovelhas, vê vir o lobo, abandona as ovelhas e foge; então, o lobo as arrebata e dispersa.

[[v43-10-13]]

^<<v43-10-13,13>>^ O mercenário foge, porque é mercenário e não tem cuidado com as ovelhas.

[[v43-10-14]]

^<<v43-10-14,14>>^ Eu sou o bom pastor; conheço as minhas ovelhas, e elas me conhecem a mim,

[[v43-10-15]]

^<<v43-10-15,15>>^ assim como o Pai me conhece a mim, e eu conheço o Pai; e dou a minha vida pelas ovelhas.

[[v43-10-16]]

^<<v43-10-16,16>>^ Ainda tenho outras ovelhas, não deste aprisco; a mim me convém conduzi-las; elas ouvirão a minha voz; então, haverá um rebanho e um pastor.

[[v43-10-17]]

^<<v43-10-17,17>>^ Por isso, o Pai me ama, porque eu dou a minha vida para a reassumir.

[[v43-10-18]]

^<<v43-10-18,18>>^ Ninguém a tira de mim; pelo contrário, eu espontaneamente a dou. Tenho autoridade para a entregar e também para reavê-la. Este mandato recebi de meu Pai.

[[v43-10-19]]

^<<v43-10-19,19>>^ Por causa dessas palavras, rompeu nova dissensão entre os judeus.

[[v43-10-20]]

^<<v43-10-20,20>>^ Muitos deles diziam: Ele tem demônio e enlouqueceu; por que o ouvis?

[[v43-10-21]]

^<<v43-10-21,21>>^ Outros diziam: Este modo de falar não é de endemoninhado; pode, porventura, um demônio abrir os olhos aos cegos?

[[v43-10-22]]

^<<v43-10-22,22>>^ Celebrava-se em Jerusalém a Festa da Dedicação. Era inverno.

[[v43-10-23]]

^<<v43-10-23,23>>^ Jesus passeava no templo, no Pórtico de Salomão.

[[v43-10-24]]

^<<v43-10-24,24>>^ Rodearam-no, pois, os judeus e o interpelaram: Até quando nos deixarás a mente em suspenso? Se tu és o Cristo, dize-o francamente.

[[v43-10-25]]

^<<v43-10-25,25>>^ Respondeu-lhes Jesus: Já vo-lo disse, e não credes. As obras que eu faço em nome de meu Pai testificam a meu respeito.

[[v43-10-26]]

^<<v43-10-26,26>>^ Mas vós não credes, porque não sois das minhas ovelhas.

[[v43-10-27]]

^<<v43-10-27,27>>^ As minhas ovelhas ouvem a minha voz; eu as conheço, e elas me seguem.

[[v43-10-28]]

^<<v43-10-28,28>>^ Eu lhes dou a vida eterna; jamais perecerão, e ninguém as arrebatará da minha mão.

[[v43-10-29]]

^<<v43-10-29,29>>^ Aquilo que meu Pai me deu é maior do que tudo; e da mão do Pai ninguém pode arrebatar.

[[v43-10-30]]

^<<v43-10-30,30>>^ Eu e o Pai somos um.

[[v43-10-31]]

^<<v43-10-31,31>>^ Novamente, pegaram os judeus em pedras para lhe atirar.

[[v43-10-32]]

^<<v43-10-32,32>>^ Disse-lhes Jesus: Tenho-vos mostrado muitas obras boas da parte do Pai; por qual delas me apedrejais?

[[v43-10-33]]

^<<v43-10-33,33>>^ Responderam-lhe os judeus: Não é por obra boa que te apedrejamos, e sim por causa da blasfêmia, pois, sendo tu homem, te fazes Deus a ti mesmo.

[[v43-10-34]]

^<<v43-10-34,34>>^ Replicou-lhes Jesus: Não está escrito na vossa lei: Eu disse: sois deuses?

[[v43-10-35]]

^<<v43-10-35,35>>^ Se ele chamou deuses àqueles a quem foi dirigida a palavra de Deus, e a Escritura não pode falhar,

[[v43-10-36]]

^<<v43-10-36,36>>^ então, daquele a quem o Pai santificou e enviou ao mundo, dizeis: Tu blasfemas; porque declarei: sou Filho de Deus?

[[v43-10-37]]

^<<v43-10-37,37>>^ Se não faço as obras de meu Pai, não me acrediteis;

[[v43-10-38]]

^<<v43-10-38,38>>^ mas, se faço, e não me credes, crede nas obras; para que possais saber e compreender que o Pai está em mim, e eu estou no Pai.

[[v43-10-39]]

^<<v43-10-39,39>>^ Nesse ponto, procuravam, outra vez, prendê-lo; mas ele se livrou das suas mãos.

[[v43-10-40]]

^<<v43-10-40,40>>^ Novamente, se retirou para além do Jordão, para o lugar onde João batizava no princípio; e ali permaneceu.

[[v43-10-41]]

^<<v43-10-41,41>>^ E iam muitos ter com ele e diziam: Realmente, João não fez nenhum sinal, porém tudo quanto disse a respeito deste era verdade.

[[v43-10-42]]

^<<v43-10-42,42>>^ E muitos ali creram nele.

'''

xref:043-joao/043-joao-009.adoc#v43-9-0[&#60; Capítulo Anterior] | <<v43-10-0,Topo>> | xref:043-joao/043-joao-011.adoc#v43-11-0[Próximo Capítulo &#62;]