include::./index.adoc[]

[[v43-1-0]]
=== João, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-1-1]]

^<<v43-1-1,1>>^ No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus.

[[v43-1-2]]

^<<v43-1-2,2>>^ Ele estava no princípio com Deus.

[[v43-1-3]]

^<<v43-1-3,3>>^ Todas as coisas foram feitas por intermédio dele, e, sem ele, nada do que foi feito se fez.

[[v43-1-4]]

^<<v43-1-4,4>>^ A vida estava nele e a vida era a luz dos homens.

[[v43-1-5]]

^<<v43-1-5,5>>^ A luz resplandece nas trevas, e as trevas não prevaleceram contra ela.

[[v43-1-6]]

^<<v43-1-6,6>>^ Houve um homem enviado por Deus cujo nome era João.

[[v43-1-7]]

^<<v43-1-7,7>>^ Este veio como testemunha para que testificasse a respeito da luz, a fim de todos virem a crer por intermédio dele.

[[v43-1-8]]

^<<v43-1-8,8>>^ Ele não era a luz, mas veio para que testificasse da luz,

[[v43-1-9]]

^<<v43-1-9,9>>^ a saber, a verdadeira luz, que, vinda ao mundo, ilumina a todo homem.

[[v43-1-10]]

^<<v43-1-10,10>>^ O Verbo estava no mundo, o mundo foi feito por intermédio dele, mas o mundo não o conheceu.

[[v43-1-11]]

^<<v43-1-11,11>>^ Veio para o que era seu, e os seus não o receberam.

[[v43-1-12]]

^<<v43-1-12,12>>^ Mas, a todos quantos o receberam, deu-lhes o poder de serem feitos filhos de Deus, a saber, aos que creem no seu nome;

[[v43-1-13]]

^<<v43-1-13,13>>^ os quais não nasceram do sangue, nem da vontade da carne, nem da vontade do homem, mas de Deus.

[[v43-1-14]]

^<<v43-1-14,14>>^ E o Verbo se fez carne e habitou entre nós, cheio de graça e de verdade, e vimos a sua glória, glória como do unigênito do Pai.

[[v43-1-15]]

^<<v43-1-15,15>>^ João testemunha a respeito dele e exclama: Este é o de quem eu disse: o que vem depois de mim tem, contudo, a primazia, porquanto já existia antes de mim.

[[v43-1-16]]

^<<v43-1-16,16>>^ Porque todos nós temos recebido da sua plenitude e graça sobre graça.

[[v43-1-17]]

^<<v43-1-17,17>>^ Porque a lei foi dada por intermédio de Moisés; a graça e a verdade vieram por meio de Jesus Cristo.

[[v43-1-18]]

^<<v43-1-18,18>>^ Ninguém jamais viu a Deus; o Deus unigênito, que está no seio do Pai, é quem o revelou.

[[v43-1-19]]

^<<v43-1-19,19>>^ Este foi o testemunho de João, quando os judeus lhe enviaram de Jerusalém sacerdotes e levitas para lhe perguntarem: Quem és tu?

[[v43-1-20]]

^<<v43-1-20,20>>^ Ele confessou e não negou; confessou: Eu não sou o Cristo.

[[v43-1-21]]

^<<v43-1-21,21>>^ Então, lhe perguntaram: Quem és, pois? És tu Elias? Ele disse: Não sou. És tu o profeta? Respondeu: Não.

[[v43-1-22]]

^<<v43-1-22,22>>^ Disseram-lhe, pois: Declara-nos quem és, para que demos resposta àqueles que nos enviaram; que dizes a respeito de ti mesmo?

[[v43-1-23]]

^<<v43-1-23,23>>^ Então, ele respondeu: Eu sou a voz do que clama no deserto: Endireitai o caminho do Senhor, como disse o profeta Isaías.

[[v43-1-24]]

^<<v43-1-24,24>>^ Ora, os que haviam sido enviados eram de entre os fariseus.

[[v43-1-25]]

^<<v43-1-25,25>>^ E perguntaram-lhe: Então, por que batizas, se não és o Cristo, nem Elias, nem o profeta?

[[v43-1-26]]

^<<v43-1-26,26>>^ Respondeu-lhes João: Eu batizo com água; mas, no meio de vós, está quem vós não conheceis,

[[v43-1-27]]

^<<v43-1-27,27>>^ o qual vem após mim, do qual não sou digno de desatar-lhe as correias das sandálias.

[[v43-1-28]]

^<<v43-1-28,28>>^ Estas coisas se passaram em Betânia, do outro lado do Jordão, onde João estava batizando.

[[v43-1-29]]

^<<v43-1-29,29>>^ No dia seguinte, viu João a Jesus, que vinha para ele, e disse: Eis o Cordeiro de Deus, que tira o pecado do mundo!

[[v43-1-30]]

^<<v43-1-30,30>>^ É este a favor de quem eu disse: após mim vem um varão que tem a primazia, porque já existia antes de mim.

[[v43-1-31]]

^<<v43-1-31,31>>^ Eu mesmo não o conhecia, mas, a fim de que ele fosse manifestado a Israel, vim, por isso, batizando com água.

[[v43-1-32]]

^<<v43-1-32,32>>^ E João testemunhou, dizendo: Vi o Espírito descer do céu como pomba e pousar sobre ele.

[[v43-1-33]]

^<<v43-1-33,33>>^ Eu não o conhecia; aquele, porém, que me enviou a batizar com água me disse: Aquele sobre quem vires descer e pousar o Espírito, esse é o que batiza com o Espírito Santo.

[[v43-1-34]]

^<<v43-1-34,34>>^ Pois eu, de fato, vi e tenho testificado que ele é o Filho de Deus.

[[v43-1-35]]

^<<v43-1-35,35>>^ No dia seguinte, estava João outra vez na companhia de dois dos seus discípulos

[[v43-1-36]]

^<<v43-1-36,36>>^ e, vendo Jesus passar, disse: Eis o Cordeiro de Deus!

[[v43-1-37]]

^<<v43-1-37,37>>^ Os dois discípulos, ouvindo-o dizer isto, seguiram Jesus.

[[v43-1-38]]

^<<v43-1-38,38>>^ E Jesus, voltando-se e vendo que o seguiam, disse-lhes: Que buscais?  Disseram-lhe: Rabi (que quer dizer Mestre), onde assistes?

[[v43-1-39]]

^<<v43-1-39,39>>^ Respondeu-lhes: Vinde e vede.  Foram, pois, e viram onde Jesus estava morando; e ficaram com ele aquele dia, sendo mais ou menos a hora décima.

[[v43-1-40]]

^<<v43-1-40,40>>^ Era André, o irmão de Simão Pedro, um dos dois que tinham ouvido o testemunho de João e seguido Jesus.

[[v43-1-41]]

^<<v43-1-41,41>>^ Ele achou primeiro o seu próprio irmão, Simão, a quem disse: Achamos o Messias (que quer dizer Cristo),

[[v43-1-42]]

^<<v43-1-42,42>>^ e o levou a Jesus. Olhando Jesus para ele, disse: Tu és Simão, o filho de João; tu serás chamado Cefas  (que quer dizer Pedro).

[[v43-1-43]]

^<<v43-1-43,43>>^ No dia imediato, resolveu Jesus partir para a Galileia e encontrou a Filipe, a quem disse: Segue-me.

[[v43-1-44]]

^<<v43-1-44,44>>^ Ora, Filipe era de Betsaida, cidade de André e de Pedro.

[[v43-1-45]]

^<<v43-1-45,45>>^ Filipe encontrou a Natanael e disse-lhe: Achamos aquele de quem Moisés escreveu na lei, e a quem se referiram os profetas: Jesus, o Nazareno, filho de José.

[[v43-1-46]]

^<<v43-1-46,46>>^ Perguntou-lhe Natanael: De Nazaré pode sair alguma coisa boa? Respondeu-lhe Filipe: Vem e vê.

[[v43-1-47]]

^<<v43-1-47,47>>^ Jesus viu Natanael aproximar-se e disse a seu respeito: Eis um verdadeiro israelita, em quem não há dolo!

[[v43-1-48]]

^<<v43-1-48,48>>^ Perguntou-lhe Natanael: Donde me conheces? Respondeu-lhe Jesus: Antes de Filipe te chamar, eu te vi, quando estavas debaixo da figueira.

[[v43-1-49]]

^<<v43-1-49,49>>^ Então, exclamou Natanael: Mestre, tu és o Filho de Deus, tu és o Rei de Israel!

[[v43-1-50]]

^<<v43-1-50,50>>^ Ao que Jesus lhe respondeu: Porque te disse que te vi debaixo da figueira, crês? Pois maiores coisas do que estas verás.

[[v43-1-51]]

^<<v43-1-51,51>>^ E acrescentou: Em verdade, em verdade vos digo que vereis o céu aberto e os anjos de Deus subindo e descendo sobre o Filho do Homem.

'''

xref:042-lucas/042-lucas-024.adoc#v42-24-0[&#60; Capítulo Anterior] | <<v43-1-0,Topo>> | xref:043-joao/043-joao-002.adoc#v43-2-0[Próximo Capítulo &#62;]