include::./index.adoc[]

[[v43-13-0]]
=== João, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-13-1]]

^<<v43-13-1,1>>^ Ora, antes da Festa da Páscoa, sabendo Jesus que era chegada a sua hora de passar deste mundo para o Pai, tendo amado os seus que estavam no mundo, amou-os até ao fim.

[[v43-13-2]]

^<<v43-13-2,2>>^ Durante a ceia, tendo já o diabo posto no coração de Judas Iscariotes, filho de Simão, que traísse a Jesus,

[[v43-13-3]]

^<<v43-13-3,3>>^ sabendo este que o Pai tudo confiara às suas mãos, e que ele viera de Deus, e voltava para Deus,

[[v43-13-4]]

^<<v43-13-4,4>>^ levantou-se da ceia, tirou a vestimenta de cima e, tomando uma toalha, cingiu-se com ela.

[[v43-13-5]]

^<<v43-13-5,5>>^ Depois, deitou água na bacia e passou a lavar os pés aos discípulos e a enxugar-lhos com a toalha com que estava cingido.

[[v43-13-6]]

^<<v43-13-6,6>>^ Aproximou-se, pois, de Simão Pedro, e este lhe disse: Senhor, tu me lavas os pés a mim?

[[v43-13-7]]

^<<v43-13-7,7>>^ Respondeu-lhe Jesus: O que eu faço não o sabes agora; compreendê-lo-ás depois.

[[v43-13-8]]

^<<v43-13-8,8>>^ Disse-lhe Pedro: Nunca me lavarás os pés. Respondeu-lhe Jesus: Se eu não te lavar, não tens parte comigo.

[[v43-13-9]]

^<<v43-13-9,9>>^ Então, Pedro lhe pediu: Senhor, não somente os pés, mas também as mãos e a cabeça.

[[v43-13-10]]

^<<v43-13-10,10>>^ Declarou-lhe Jesus: Quem já se banhou não necessita de lavar senão os pés; quanto ao mais, está todo limpo. Ora, vós estais limpos, mas não todos.

[[v43-13-11]]

^<<v43-13-11,11>>^ Pois ele sabia quem era o traidor. Foi por isso que disse: Nem todos estais limpos.

[[v43-13-12]]

^<<v43-13-12,12>>^ Depois de lhes ter lavado os pés, tomou as vestes e, voltando à mesa, perguntou-lhes: Compreendeis o que vos fiz?

[[v43-13-13]]

^<<v43-13-13,13>>^ Vós me chamais o Mestre e o Senhor e dizeis bem; porque eu o sou.

[[v43-13-14]]

^<<v43-13-14,14>>^ Ora, se eu, sendo o Senhor e o Mestre, vos lavei os pés, também vós deveis lavar os pés uns dos outros.

[[v43-13-15]]

^<<v43-13-15,15>>^ Porque eu vos dei o exemplo, para que, como eu vos fiz, façais vós também.

[[v43-13-16]]

^<<v43-13-16,16>>^ Em verdade, em verdade vos digo que o servo não é maior do que seu senhor, nem o enviado, maior do que aquele que o enviou.

[[v43-13-17]]

^<<v43-13-17,17>>^ Ora, se sabeis estas coisas, bem-aventurados sois se as praticardes.

[[v43-13-18]]

^<<v43-13-18,18>>^ Não falo a respeito de todos vós, pois eu conheço aqueles que escolhi; é, antes, para que se cumpra a Escritura: Aquele que come do meu pão levantou contra mim seu calcanhar.

[[v43-13-19]]

^<<v43-13-19,19>>^ Desde já vos digo, antes que aconteça, para que, quando acontecer, creiais que Eu Sou .

[[v43-13-20]]

^<<v43-13-20,20>>^ Em verdade, em verdade vos digo: quem recebe aquele que eu enviar, a mim me recebe; e quem me recebe recebe aquele que me enviou.

[[v43-13-21]]

^<<v43-13-21,21>>^ Ditas estas coisas, angustiou-se Jesus em espírito e afirmou: Em verdade, em verdade vos digo que um dentre vós me trairá.

[[v43-13-22]]

^<<v43-13-22,22>>^ Então, os discípulos olharam uns para os outros, sem saber a quem ele se referia.

[[v43-13-23]]

^<<v43-13-23,23>>^ Ora, ali estava conchegado a Jesus um dos seus discípulos, aquele a quem ele amava;

[[v43-13-24]]

^<<v43-13-24,24>>^ a esse fez Simão Pedro sinal, dizendo-lhe: Pergunta a quem ele se refere.

[[v43-13-25]]

^<<v43-13-25,25>>^ Então, aquele discípulo, reclinando-se sobre o peito de Jesus, perguntou-lhe: Senhor, quem é?

[[v43-13-26]]

^<<v43-13-26,26>>^ Respondeu Jesus: É aquele a quem eu der o pedaço de pão molhado.  Tomou, pois, um pedaço de pão e, tendo-o molhado, deu-o a Judas, filho de Simão Iscariotes.

[[v43-13-27]]

^<<v43-13-27,27>>^ E, após o bocado, imediatamente, entrou nele Satanás. Então, disse Jesus: O que pretendes fazer, faze-o depressa.

[[v43-13-28]]

^<<v43-13-28,28>>^ Nenhum, porém, dos que estavam à mesa percebeu a que fim lhe dissera isto.

[[v43-13-29]]

^<<v43-13-29,29>>^ Pois, como Judas era quem trazia a bolsa, pensaram alguns que Jesus lhe dissera: Compra o que precisamos para a festa ou lhe ordenara que desse alguma coisa aos pobres.

[[v43-13-30]]

^<<v43-13-30,30>>^ Ele, tendo recebido o bocado, saiu logo. E era noite.

[[v43-13-31]]

^<<v43-13-31,31>>^ Quando ele saiu, disse Jesus: Agora, foi glorificado o Filho do Homem, e Deus foi glorificado nele;

[[v43-13-32]]

^<<v43-13-32,32>>^ se Deus foi glorificado nele, também Deus o glorificará nele mesmo; e glorificá-lo-á imediatamente.

[[v43-13-33]]

^<<v43-13-33,33>>^ Filhinhos, ainda por um pouco estou convosco; buscar-me-eis, e o que eu disse aos judeus também agora vos digo a vós outros: para onde eu vou, vós não podeis ir.

[[v43-13-34]]

^<<v43-13-34,34>>^ Novo mandamento vos dou: que vos ameis uns aos outros; assim como eu vos amei, que também vos ameis uns aos outros.

[[v43-13-35]]

^<<v43-13-35,35>>^ Nisto conhecerão todos que sois meus discípulos: se tiverdes amor uns aos outros.

[[v43-13-36]]

^<<v43-13-36,36>>^ Perguntou-lhe Simão Pedro: Senhor, para onde vais? Respondeu Jesus: Para onde vou, não me podes seguir agora; mais tarde, porém, me seguirás.

[[v43-13-37]]

^<<v43-13-37,37>>^ Replicou Pedro: Senhor, por que não posso seguir-te agora? Por ti darei a própria vida.

[[v43-13-38]]

^<<v43-13-38,38>>^ Respondeu Jesus: Darás a vida por mim? Em verdade, em verdade te digo que jamais cantará o galo antes que me negues três vezes.

'''

xref:043-joao/043-joao-012.adoc#v43-12-0[&#60; Capítulo Anterior] | <<v43-13-0,Topo>> | xref:043-joao/043-joao-014.adoc#v43-14-0[Próximo Capítulo &#62;]