include::./index.adoc[]

[[v43-18-0]]
=== João, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-18-1]]

^<<v43-18-1,1>>^ Tendo Jesus dito estas palavras, saiu juntamente com seus discípulos para o outro lado do ribeiro Cedrom, onde havia um jardim; e aí entrou com eles.

[[v43-18-2]]

^<<v43-18-2,2>>^ E Judas, o traidor, também conhecia aquele lugar, porque Jesus ali estivera muitas vezes com seus discípulos.

[[v43-18-3]]

^<<v43-18-3,3>>^ Tendo, pois, Judas recebido a escolta e, dos principais sacerdotes e dos fariseus, alguns guardas, chegou a este lugar com lanternas, tochas e armas.

[[v43-18-4]]

^<<v43-18-4,4>>^ Sabendo, pois, Jesus todas as coisas que sobre ele haviam de vir, adiantou-se e perguntou-lhes: A quem buscais?

[[v43-18-5]]

^<<v43-18-5,5>>^ Responderam-lhe: A Jesus, o Nazareno. Então, Jesus lhes disse: Sou eu.  Ora, Judas, o traidor, estava também com eles.

[[v43-18-6]]

^<<v43-18-6,6>>^ Quando, pois, Jesus lhes disse: Sou eu, recuaram e caíram por terra.

[[v43-18-7]]

^<<v43-18-7,7>>^ Jesus, de novo, lhes perguntou: A quem buscais?  Responderam: A Jesus, o Nazareno.

[[v43-18-8]]

^<<v43-18-8,8>>^ Então, lhes disse Jesus: Já vos declarei que sou eu; se é a mim, pois, que buscais, deixai ir estes;

[[v43-18-9]]

^<<v43-18-9,9>>^ para se cumprir a palavra que dissera: Não perdi nenhum dos que me deste.

[[v43-18-10]]

^<<v43-18-10,10>>^ Então, Simão Pedro puxou da espada que trazia e feriu o servo do sumo sacerdote, cortando-lhe a orelha direita; e o nome do servo era Malco.

[[v43-18-11]]

^<<v43-18-11,11>>^ Mas Jesus disse a Pedro: Mete a espada na bainha; não beberei, porventura, o cálice que o Pai me deu?

[[v43-18-12]]

^<<v43-18-12,12>>^ Assim, a escolta, o comandante e os guardas dos judeus prenderam Jesus, manietaram-no

[[v43-18-13]]

^<<v43-18-13,13>>^ e o conduziram primeiramente a Anás; pois era sogro de Caifás, sumo sacerdote naquele ano.

[[v43-18-14]]

^<<v43-18-14,14>>^ Ora, Caifás era quem havia declarado aos judeus ser conveniente morrer um homem pelo povo.

[[v43-18-15]]

^<<v43-18-15,15>>^ Simão Pedro e outro discípulo seguiam a Jesus. Sendo este discípulo conhecido do sumo sacerdote, entrou para o pátio deste com Jesus.

[[v43-18-16]]

^<<v43-18-16,16>>^ Pedro, porém, ficou de fora, junto à porta. Saindo, pois, o outro discípulo, que era conhecido do sumo sacerdote, falou com a encarregada da porta e levou a Pedro para dentro.

[[v43-18-17]]

^<<v43-18-17,17>>^ Então, a criada, encarregada da porta, perguntou a Pedro: Não és tu também um dos discípulos deste homem? Não sou, respondeu ele.

[[v43-18-18]]

^<<v43-18-18,18>>^ Ora, os servos e os guardas estavam ali, tendo acendido um braseiro, por causa do frio, e aquentavam-se. Pedro estava no meio deles, aquentando-se também.

[[v43-18-19]]

^<<v43-18-19,19>>^ Então, o sumo sacerdote interrogou a Jesus acerca dos seus discípulos e da sua doutrina.

[[v43-18-20]]

^<<v43-18-20,20>>^ Declarou-lhe Jesus: Eu tenho falado francamente ao mundo; ensinei continuamente tanto nas sinagogas como no templo, onde todos os judeus se reúnem, e nada disse em oculto.

[[v43-18-21]]

^<<v43-18-21,21>>^ Por que me interrogas? Pergunta aos que ouviram o que lhes falei; bem sabem eles o que eu disse.

[[v43-18-22]]

^<<v43-18-22,22>>^ Dizendo ele isto, um dos guardas que ali estavam deu uma bofetada em Jesus, dizendo: É assim que falas ao sumo sacerdote?

[[v43-18-23]]

^<<v43-18-23,23>>^ Replicou-lhe Jesus: Se falei mal, dá testemunho do mal; mas, se falei bem, por que me feres?

[[v43-18-24]]

^<<v43-18-24,24>>^ Então, Anás o enviou, manietado, à presença de Caifás, o sumo sacerdote.

[[v43-18-25]]

^<<v43-18-25,25>>^ Lá estava Simão Pedro, aquentando-se. Perguntaram-lhe, pois: És tu, porventura, um dos discípulos dele? Ele negou e disse: Não sou.

[[v43-18-26]]

^<<v43-18-26,26>>^ Um dos servos do sumo sacerdote, parente daquele a quem Pedro tinha decepado a orelha, perguntou: Não te vi eu no jardim com ele?

[[v43-18-27]]

^<<v43-18-27,27>>^ De novo, Pedro o negou, e, no mesmo instante, cantou o galo.

[[v43-18-28]]

^<<v43-18-28,28>>^ Depois, levaram Jesus da casa de Caifás para o pretório. Era cedo de manhã. Eles não entraram no pretório para não se contaminarem, mas poderem comer a Páscoa.

[[v43-18-29]]

^<<v43-18-29,29>>^ Então, Pilatos saiu para lhes falar e lhes disse: Que acusação trazeis contra este homem?

[[v43-18-30]]

^<<v43-18-30,30>>^ Responderam-lhe: Se este não fosse malfeitor, não to entregaríamos.

[[v43-18-31]]

^<<v43-18-31,31>>^ Replicou-lhes, pois, Pilatos: Tomai-o vós outros e julgai-o segundo a vossa lei. Responderam-lhe os judeus: A nós não nos é lícito matar ninguém;

[[v43-18-32]]

^<<v43-18-32,32>>^ para que se cumprisse a palavra de Jesus, significando o modo por que havia de morrer.

[[v43-18-33]]

^<<v43-18-33,33>>^ Tornou Pilatos a entrar no pretório, chamou Jesus e perguntou-lhe: És tu o rei dos judeus?

[[v43-18-34]]

^<<v43-18-34,34>>^ Respondeu Jesus: Vem de ti mesmo esta pergunta ou to disseram outros a meu respeito?

[[v43-18-35]]

^<<v43-18-35,35>>^ Replicou Pilatos: Porventura, sou judeu? A tua própria gente e os principais sacerdotes é que te entregaram a mim. Que fizeste?

[[v43-18-36]]

^<<v43-18-36,36>>^ Respondeu Jesus: O meu reino não é deste mundo. Se o meu reino fosse deste mundo, os meus ministros se empenhariam por mim, para que não fosse eu entregue aos judeus; mas agora o meu reino não é daqui.

[[v43-18-37]]

^<<v43-18-37,37>>^ Então, lhe disse Pilatos: Logo, tu és rei? Respondeu Jesus: Tu dizes que sou rei. Eu para isso nasci e para isso vim ao mundo, a fim de dar testemunho da verdade. Todo aquele que é da verdade ouve a minha voz.

[[v43-18-38]]

^<<v43-18-38,38>>^ Perguntou-lhe Pilatos: Que é a verdade? Tendo dito isto, voltou aos judeus e lhes disse: Eu não acho nele crime algum.

[[v43-18-39]]

^<<v43-18-39,39>>^ É costume entre vós que eu vos solte alguém por ocasião da Páscoa; quereis, pois, que vos solte o rei dos judeus?

[[v43-18-40]]

^<<v43-18-40,40>>^ Então, gritaram todos, novamente: Não este, mas Barrabás! Ora, Barrabás era salteador.

'''

xref:043-joao/043-joao-017.adoc#v43-17-0[&#60; Capítulo Anterior] | <<v43-18-0,Topo>> | xref:043-joao/043-joao-019.adoc#v43-19-0[Próximo Capítulo &#62;]