include::./index.adoc[]

[[v43-7-0]]
=== João, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-7-1]]

^<<v43-7-1,1>>^ Passadas estas coisas, Jesus andava pela Galileia, porque não desejava percorrer a Judeia, visto que os judeus procuravam matá-lo.

[[v43-7-2]]

^<<v43-7-2,2>>^ Ora, a festa dos judeus, chamada de Festa dos Tabernáculos, estava próxima.

[[v43-7-3]]

^<<v43-7-3,3>>^ Dirigiram-se, pois, a ele os seus irmãos e lhe disseram: Deixa este lugar e vai para a Judeia, para que também os teus discípulos vejam as obras que fazes.

[[v43-7-4]]

^<<v43-7-4,4>>^ Porque ninguém há que procure ser conhecido em público e, contudo, realize os seus feitos em oculto. Se fazes estas coisas, manifesta-te ao mundo.

[[v43-7-5]]

^<<v43-7-5,5>>^ Pois nem mesmo os seus irmãos criam nele.

[[v43-7-6]]

^<<v43-7-6,6>>^ Disse-lhes, pois, Jesus: O meu tempo ainda não chegou, mas o vosso sempre está presente.

[[v43-7-7]]

^<<v43-7-7,7>>^ Não pode o mundo odiar-vos, mas a mim me odeia, porque eu dou testemunho a seu respeito de que as suas obras são más.

[[v43-7-8]]

^<<v43-7-8,8>>^ Subi vós outros à festa; eu, por enquanto, não subo, porque o meu tempo ainda não está cumprido.

[[v43-7-9]]

^<<v43-7-9,9>>^ Disse-lhes Jesus estas coisas e continuou na Galileia.

[[v43-7-10]]

^<<v43-7-10,10>>^ Mas, depois que seus irmãos subiram para a festa, então, subiu ele também, não publicamente, mas em oculto.

[[v43-7-11]]

^<<v43-7-11,11>>^ Ora, os judeus o procuravam na festa e perguntavam: Onde estará ele?

[[v43-7-12]]

^<<v43-7-12,12>>^ E havia grande murmuração a seu respeito entre as multidões. Uns diziam: Ele é bom. E outros: Não, antes, engana o povo.

[[v43-7-13]]

^<<v43-7-13,13>>^ Entretanto, ninguém falava dele abertamente, por ter medo dos judeus.

[[v43-7-14]]

^<<v43-7-14,14>>^ Corria já em meio a festa, e Jesus subiu ao templo e ensinava.

[[v43-7-15]]

^<<v43-7-15,15>>^ Então, os judeus se maravilhavam e diziam: Como sabe este letras, sem ter estudado?

[[v43-7-16]]

^<<v43-7-16,16>>^ Respondeu-lhes Jesus: O meu ensino não é meu, e sim daquele que me enviou.

[[v43-7-17]]

^<<v43-7-17,17>>^ Se alguém quiser fazer a vontade dele, conhecerá a respeito da doutrina, se ela é de Deus ou se eu falo por mim mesmo.

[[v43-7-18]]

^<<v43-7-18,18>>^ Quem fala por si mesmo está procurando a sua própria glória; mas o que procura a glória de quem o enviou, esse é verdadeiro, e nele não há injustiça.

[[v43-7-19]]

^<<v43-7-19,19>>^ Não vos deu Moisés a lei? Contudo, ninguém dentre vós a observa. Por que procurais matar-me?

[[v43-7-20]]

^<<v43-7-20,20>>^ Respondeu a multidão: Tens demônio. Quem é que procura matar-te?

[[v43-7-21]]

^<<v43-7-21,21>>^ Replicou-lhes Jesus: Um só feito realizei, e todos vos admirais.

[[v43-7-22]]

^<<v43-7-22,22>>^ Pelo motivo de que Moisés vos deu a circuncisão (se bem que ela não vem dele, mas dos patriarcas ), no sábado circuncidais um homem.

[[v43-7-23]]

^<<v43-7-23,23>>^ E, se o homem pode ser circuncidado em dia de sábado, para que a lei de Moisés não seja violada, por que vos indignais contra mim, pelo fato de eu ter curado, num sábado, ao todo, um homem?

[[v43-7-24]]

^<<v43-7-24,24>>^ Não julgueis segundo a aparência, e sim pela reta justiça.

[[v43-7-25]]

^<<v43-7-25,25>>^ Diziam alguns de Jerusalém: Não é este aquele a quem procuram matar?

[[v43-7-26]]

^<<v43-7-26,26>>^ Eis que ele fala abertamente, e nada lhe dizem. Porventura, reconhecem verdadeiramente as autoridades que este é, de fato, o Cristo?

[[v43-7-27]]

^<<v43-7-27,27>>^ Nós, todavia, sabemos donde este é; quando, porém, vier o Cristo, ninguém saberá donde ele é.

[[v43-7-28]]

^<<v43-7-28,28>>^ Jesus, pois, enquanto ensinava no templo, clamou, dizendo: Vós não somente me conheceis, mas também sabeis donde eu sou; e não vim porque eu, de mim mesmo, o quisesse, mas aquele que me enviou é verdadeiro, aquele a quem vós não conheceis.

[[v43-7-29]]

^<<v43-7-29,29>>^ Eu o conheço, porque venho da parte dele e fui por ele enviado.

[[v43-7-30]]

^<<v43-7-30,30>>^ Então, procuravam prendê-lo; mas ninguém lhe pôs a mão, porque ainda não era chegada a sua hora.

[[v43-7-31]]

^<<v43-7-31,31>>^ E, contudo, muitos de entre a multidão creram nele e diziam: Quando vier o Cristo, fará, porventura, maiores sinais do que este homem tem feito?

[[v43-7-32]]

^<<v43-7-32,32>>^ Os fariseus, ouvindo a multidão murmurar estas coisas a respeito dele, juntamente com os principais sacerdotes enviaram guardas para o prenderem.

[[v43-7-33]]

^<<v43-7-33,33>>^ Disse-lhes Jesus: Ainda por um pouco de tempo estou convosco e depois irei para junto daquele que me enviou.

[[v43-7-34]]

^<<v43-7-34,34>>^ Haveis de procurar-me e não me achareis; também aonde eu estou, vós não podeis ir.

[[v43-7-35]]

^<<v43-7-35,35>>^ Disseram, pois, os judeus uns aos outros: Para onde irá este que não o possamos achar? Irá, porventura, para a Dispersão entre os gregos, com o fim de os ensinar?

[[v43-7-36]]

^<<v43-7-36,36>>^ Que significa, de fato, o que ele diz: Haveis de procurar-me e não me achareis; também aonde eu estou, vós não podeis ir?

[[v43-7-37]]

^<<v43-7-37,37>>^ No último dia, o grande dia da festa, levantou-se Jesus e exclamou: Se alguém tem sede, venha a mim e beba.

[[v43-7-38]]

^<<v43-7-38,38>>^ Quem crer em mim, como diz a Escritura, do seu interior fluirão rios de água viva.

[[v43-7-39]]

^<<v43-7-39,39>>^ Isto ele disse com respeito ao Espírito que haviam de receber os que nele cressem; pois o Espírito até aquele momento não fora dado, porque Jesus não havia sido ainda glorificado.

[[v43-7-40]]

^<<v43-7-40,40>>^ Então, os que dentre o povo tinham ouvido estas palavras diziam: Este é verdadeiramente o profeta;

[[v43-7-41]]

^<<v43-7-41,41>>^ outros diziam: Ele é o Cristo; outros, porém, perguntavam: Porventura, o Cristo virá da Galileia?

[[v43-7-42]]

^<<v43-7-42,42>>^ Não diz a Escritura que o Cristo vem da descendência de Davi e da aldeia de Belém, donde era Davi?

[[v43-7-43]]

^<<v43-7-43,43>>^ Assim, houve uma dissensão entre o povo por causa dele;

[[v43-7-44]]

^<<v43-7-44,44>>^ alguns dentre eles queriam prendê-lo, mas ninguém lhe pôs as mãos.

[[v43-7-45]]

^<<v43-7-45,45>>^ Voltaram, pois, os guardas à presença dos principais sacerdotes e fariseus, e estes lhes perguntaram: Por que não o trouxestes?

[[v43-7-46]]

^<<v43-7-46,46>>^ Responderam eles: Jamais alguém falou como este homem.

[[v43-7-47]]

^<<v43-7-47,47>>^ Replicaram-lhes, pois, os fariseus: Será que também vós fostes enganados?

[[v43-7-48]]

^<<v43-7-48,48>>^ Porventura, creu nele alguém dentre as autoridades ou algum dos fariseus?

[[v43-7-49]]

^<<v43-7-49,49>>^ Quanto a esta plebe que nada sabe da lei, é maldita.

[[v43-7-50]]

^<<v43-7-50,50>>^ Nicodemos, um deles, que antes fora ter com Jesus, perguntou-lhes:

[[v43-7-51]]

^<<v43-7-51,51>>^ Acaso, a nossa lei julga um homem, sem primeiro ouvi-lo e saber o que ele fez?

[[v43-7-52]]

^<<v43-7-52,52>>^ Responderam eles: Dar-se-á o caso de que também tu és da Galileia? Examina e verás que da Galileia não se levanta profeta.

[[v43-7-53]]

^<<v43-7-53,53>>^ [E cada um foi para sua casa.

'''

xref:043-joao/043-joao-006.adoc#v43-6-0[&#60; Capítulo Anterior] | <<v43-7-0,Topo>> | xref:043-joao/043-joao-008.adoc#v43-8-0[Próximo Capítulo &#62;]