include::./index.adoc[]

[[v43-21-0]]
=== João, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-21-1]]

^<<v43-21-1,1>>^ Depois disto, tornou Jesus a manifestar-se aos discípulos junto do mar de Tiberíades; e foi assim que ele se manifestou:

[[v43-21-2]]

^<<v43-21-2,2>>^ estavam juntos Simão Pedro, Tomé, chamado Dídimo, Natanael, que era de Caná da Galileia, os filhos de Zebedeu e mais dois dos seus discípulos.

[[v43-21-3]]

^<<v43-21-3,3>>^ Disse-lhes Simão Pedro: Vou pescar. Disseram-lhe os outros: Também nós vamos contigo. Saíram, e entraram no barco, e, naquela noite, nada apanharam.

[[v43-21-4]]

^<<v43-21-4,4>>^ Mas, ao clarear da madrugada, estava Jesus na praia; todavia, os discípulos não reconheceram que era ele.

[[v43-21-5]]

^<<v43-21-5,5>>^ Perguntou-lhes Jesus: Filhos, tendes aí alguma coisa de comer?  Responderam-lhe: Não.

[[v43-21-6]]

^<<v43-21-6,6>>^ Então, lhes disse: Lançai a rede à direita do barco e achareis.  Assim fizeram e já não podiam puxar a rede, tão grande era a quantidade de peixes.

[[v43-21-7]]

^<<v43-21-7,7>>^ Aquele discípulo a quem Jesus amava disse a Pedro: É o Senhor! Simão Pedro, ouvindo que era o Senhor, cingiu-se com sua veste, porque se havia despido, e lançou-se ao mar;

[[v43-21-8]]

^<<v43-21-8,8>>^ mas os outros discípulos vieram no barquinho puxando a rede com os peixes; porque não estavam distantes da terra senão quase duzentos côvados.

[[v43-21-9]]

^<<v43-21-9,9>>^ Ao saltarem em terra, viram ali umas brasas e, em cima, peixes; e havia também pão.

[[v43-21-10]]

^<<v43-21-10,10>>^ Disse-lhes Jesus: Trazei alguns dos peixes que acabastes de apanhar.

[[v43-21-11]]

^<<v43-21-11,11>>^ Simão Pedro entrou no barco e arrastou a rede para a terra, cheia de cento e cinquenta e três grandes peixes; e, não obstante serem tantos, a rede não se rompeu.

[[v43-21-12]]

^<<v43-21-12,12>>^ Disse-lhes Jesus: Vinde, comei.  Nenhum dos discípulos ousava perguntar-lhe: Quem és tu? Porque sabiam que era o Senhor.

[[v43-21-13]]

^<<v43-21-13,13>>^ Veio Jesus, tomou o pão, e lhes deu, e, de igual modo, o peixe.

[[v43-21-14]]

^<<v43-21-14,14>>^ E já era esta a terceira vez que Jesus se manifestava aos discípulos, depois de ressuscitado dentre os mortos.

[[v43-21-15]]

^<<v43-21-15,15>>^ Depois de terem comido, perguntou Jesus a Simão Pedro: Simão, filho de João, amas-me mais do que estes outros?  Ele respondeu: Sim, Senhor, tu sabes que te amo. Ele lhe disse: Apascenta os meus cordeiros.

[[v43-21-16]]

^<<v43-21-16,16>>^ Tornou a perguntar-lhe pela segunda vez: Simão, filho de João, tu me amas?  Ele lhe respondeu: Sim, Senhor, tu sabes que te amo. Disse-lhe Jesus: Pastoreia as minhas ovelhas.

[[v43-21-17]]

^<<v43-21-17,17>>^ Pela terceira vez Jesus lhe perguntou: Simão, filho de João, tu me amas?  Pedro entristeceu-se por ele lhe ter dito, pela terceira vez: Tu me amas? E respondeu-lhe: Senhor, tu sabes todas as coisas, tu sabes que eu te amo. Jesus lhe disse: Apascenta as minhas ovelhas.

[[v43-21-18]]

^<<v43-21-18,18>>^ Em verdade, em verdade te digo que, quando eras mais moço, tu te cingias a ti mesmo e andavas por onde querias; quando, porém, fores velho, estenderás as mãos, e outro te cingirá e te levará para onde não queres.

[[v43-21-19]]

^<<v43-21-19,19>>^ Disse isto para significar com que gênero de morte Pedro havia de glorificar a Deus. Depois de assim falar, acrescentou-lhe: Segue-me.

[[v43-21-20]]

^<<v43-21-20,20>>^ Então, Pedro, voltando-se, viu que também o ia seguindo o discípulo a quem Jesus amava, o qual na ceia se reclinara sobre o peito de Jesus e perguntara: Senhor, quem é o traidor?

[[v43-21-21]]

^<<v43-21-21,21>>^ Vendo-o, pois, Pedro perguntou a Jesus: E quanto a este?

[[v43-21-22]]

^<<v43-21-22,22>>^ Respondeu-lhe Jesus: Se eu quero que ele permaneça até que eu venha, que te importa? Quanto a ti, segue-me.

[[v43-21-23]]

^<<v43-21-23,23>>^ Então, se tornou corrente entre os irmãos o dito de que aquele discípulo não morreria. Ora, Jesus não dissera que tal discípulo não morreria, mas: Se eu quero que ele permaneça até que eu venha, que te importa?

[[v43-21-24]]

^<<v43-21-24,24>>^ Este é o discípulo que dá testemunho a respeito destas coisas e que as escreveu; e sabemos que o seu testemunho é verdadeiro.

[[v43-21-25]]

^<<v43-21-25,25>>^ Há, porém, ainda muitas outras coisas que Jesus fez. Se todas elas fossem relatadas uma por uma, creio eu que nem no mundo inteiro caberiam os livros que seriam escritos.

'''

xref:043-joao/043-joao-020.adoc#v43-20-0[&#60; Capítulo Anterior] | <<v43-21-0,Topo>> | xref:044-atos/044-atos-001.adoc#v44-1-0[Próximo Capítulo &#62;]