include::./index.adoc[]

[[v43-8-0]]
=== João, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-8-1]]

^<<v43-8-1,1>>^ Jesus, entretanto, foi para o monte das Oliveiras.

[[v43-8-2]]

^<<v43-8-2,2>>^ De madrugada, voltou novamente para o templo, e todo o povo ia ter com ele; e, assentado, os ensinava.

[[v43-8-3]]

^<<v43-8-3,3>>^ Os escribas e fariseus trouxeram à sua presença uma mulher surpreendida em adultério e, fazendo-a ficar de pé no meio de todos,

[[v43-8-4]]

^<<v43-8-4,4>>^ disseram a Jesus: Mestre, esta mulher foi apanhada em flagrante adultério.

[[v43-8-5]]

^<<v43-8-5,5>>^ E na lei nos mandou Moisés que tais mulheres sejam apedrejadas; tu, pois, que dizes?

[[v43-8-6]]

^<<v43-8-6,6>>^ Isto diziam eles tentando-o, para terem de que o acusar. Mas Jesus, inclinando-se, escrevia na terra com o dedo.

[[v43-8-7]]

^<<v43-8-7,7>>^ Como insistissem na pergunta, Jesus se levantou e lhes disse: Aquele que dentre vós estiver sem pecado seja o primeiro que lhe atire pedra.

[[v43-8-8]]

^<<v43-8-8,8>>^ E, tornando a inclinar-se, continuou a escrever no chão.

[[v43-8-9]]

^<<v43-8-9,9>>^ Mas, ouvindo eles esta resposta e acusados pela própria consciência, foram-se retirando um por um, a começar pelos mais velhos até aos últimos, ficando só Jesus e a mulher no meio onde estava.

[[v43-8-10]]

^<<v43-8-10,10>>^ Erguendo-se Jesus e não vendo a ninguém mais além da mulher, perguntou-lhe: Mulher, onde estão aqueles teus acusadores? Ninguém te condenou?

[[v43-8-11]]

^<<v43-8-11,11>>^ Respondeu ela: Ninguém, Senhor! Então, lhe disse Jesus: Nem eu tampouco te condeno; vai e não peques mais.]

[[v43-8-12]]

^<<v43-8-12,12>>^ De novo, lhes falava Jesus, dizendo: Eu sou a luz do mundo; quem me segue não andará nas trevas; pelo contrário, terá a luz da vida.

[[v43-8-13]]

^<<v43-8-13,13>>^ Então, lhe objetaram os fariseus: Tu dás testemunho de ti mesmo; logo, o teu testemunho não é verdadeiro.

[[v43-8-14]]

^<<v43-8-14,14>>^ Respondeu Jesus e disse-lhes: Posto que eu testifico de mim mesmo, o meu testemunho é verdadeiro, porque sei donde vim e para onde vou; mas vós não sabeis donde venho, nem para onde vou.

[[v43-8-15]]

^<<v43-8-15,15>>^ Vós julgais segundo a carne, eu a ninguém julgo.

[[v43-8-16]]

^<<v43-8-16,16>>^ Se eu julgo, o meu juízo é verdadeiro, porque não sou eu só, porém eu e aquele que me enviou.

[[v43-8-17]]

^<<v43-8-17,17>>^ Também na vossa lei está escrito que o testemunho de duas pessoas é verdadeiro.

[[v43-8-18]]

^<<v43-8-18,18>>^ Eu testifico de mim mesmo, e o Pai, que me enviou, também testifica de mim.

[[v43-8-19]]

^<<v43-8-19,19>>^ Então, eles lhe perguntaram: Onde está teu Pai? Respondeu Jesus: Não me conheceis a mim nem a meu Pai; se conhecêsseis a mim, também conheceríeis a meu Pai.

[[v43-8-20]]

^<<v43-8-20,20>>^ Proferiu ele estas palavras no lugar do gazofilácio, quando ensinava no templo; e ninguém o prendeu, porque não era ainda chegada a sua hora.

[[v43-8-21]]

^<<v43-8-21,21>>^ De outra feita, lhes falou, dizendo: Vou retirar-me, e vós me procurareis, mas perecereis no vosso pecado; para onde eu vou vós não podeis ir.

[[v43-8-22]]

^<<v43-8-22,22>>^ Então, diziam os judeus: Terá ele, acaso, a intenção de suicidar-se? Porque diz: Para onde eu vou vós não podeis ir.

[[v43-8-23]]

^<<v43-8-23,23>>^ E prosseguiu: Vós sois cá de baixo, eu sou lá de cima; vós sois deste mundo, eu deste mundo não sou.

[[v43-8-24]]

^<<v43-8-24,24>>^ Por isso, eu vos disse que morrereis nos vossos pecados; porque, se não crerdes que Eu Sou , morrereis nos vossos pecados.

[[v43-8-25]]

^<<v43-8-25,25>>^ Então, lhe perguntaram: Quem és tu? Respondeu-lhes Jesus: Que é que desde o princípio vos tenho dito?

[[v43-8-26]]

^<<v43-8-26,26>>^ Muitas coisas tenho para dizer a vosso respeito e vos julgar; porém aquele que me enviou é verdadeiro, de modo que as coisas que dele tenho ouvido, essas digo ao mundo.

[[v43-8-27]]

^<<v43-8-27,27>>^ Eles, porém, não atinaram que lhes falava do Pai.

[[v43-8-28]]

^<<v43-8-28,28>>^ Disse-lhes, pois, Jesus: Quando levantardes o Filho do Homem, então, sabereis que Eu Sou  e que nada faço por mim mesmo; mas falo como o Pai me ensinou.

[[v43-8-29]]

^<<v43-8-29,29>>^ E aquele que me enviou está comigo, não me deixou só, porque eu faço sempre o que lhe agrada.

[[v43-8-30]]

^<<v43-8-30,30>>^ Ditas estas coisas, muitos creram nele.

[[v43-8-31]]

^<<v43-8-31,31>>^ Disse, pois, Jesus aos judeus que haviam crido nele: Se vós permanecerdes na minha palavra, sois verdadeiramente meus discípulos;

[[v43-8-32]]

^<<v43-8-32,32>>^ e conhecereis a verdade, e a verdade vos libertará.

[[v43-8-33]]

^<<v43-8-33,33>>^ Responderam-lhe: Somos descendência de Abraão e jamais fomos escravos de alguém; como dizes tu: Sereis livres?

[[v43-8-34]]

^<<v43-8-34,34>>^ Replicou-lhes Jesus: Em verdade, em verdade vos digo: todo o que comete pecado é escravo do pecado.

[[v43-8-35]]

^<<v43-8-35,35>>^ O escravo não fica sempre na casa; o filho, sim, para sempre.

[[v43-8-36]]

^<<v43-8-36,36>>^ Se, pois, o Filho vos libertar, verdadeiramente sereis livres.

[[v43-8-37]]

^<<v43-8-37,37>>^ Bem sei que sois descendência de Abraão; contudo, procurais matar-me, porque a minha palavra não está em vós.

[[v43-8-38]]

^<<v43-8-38,38>>^ Eu falo das coisas que vi junto de meu Pai; vós, porém, fazeis o que vistes em vosso pai.

[[v43-8-39]]

^<<v43-8-39,39>>^ Então, lhe responderam: Nosso pai é Abraão. Disse-lhes Jesus: Se sois filhos de Abraão, praticai as obras de Abraão.

[[v43-8-40]]

^<<v43-8-40,40>>^ Mas agora procurais matar-me, a mim que vos tenho falado a verdade que ouvi de Deus; assim não procedeu Abraão.

[[v43-8-41]]

^<<v43-8-41,41>>^ Vós fazeis as obras de vosso pai.  Disseram-lhe eles: Nós não somos bastardos; temos um pai, que é Deus.

[[v43-8-42]]

^<<v43-8-42,42>>^ Replicou-lhes Jesus: Se Deus fosse, de fato, vosso pai, certamente, me havíeis de amar; porque eu vim de Deus e aqui estou; pois não vim de mim mesmo, mas ele me enviou.

[[v43-8-43]]

^<<v43-8-43,43>>^ Qual a razão por que não compreendeis a minha linguagem? É porque sois incapazes de ouvir a minha palavra.

[[v43-8-44]]

^<<v43-8-44,44>>^ Vós sois do diabo, que é vosso pai, e quereis satisfazer-lhe os desejos. Ele foi homicida desde o princípio e jamais se firmou na verdade, porque nele não há verdade. Quando ele profere mentira, fala do que lhe é próprio, porque é mentiroso e pai da mentira.

[[v43-8-45]]

^<<v43-8-45,45>>^ Mas, porque eu digo a verdade, não me credes.

[[v43-8-46]]

^<<v43-8-46,46>>^ Quem dentre vós me convence de pecado? Se vos digo a verdade, por que razão não me credes?

[[v43-8-47]]

^<<v43-8-47,47>>^ Quem é de Deus ouve as palavras de Deus; por isso, não me dais ouvidos, porque não sois de Deus.

[[v43-8-48]]

^<<v43-8-48,48>>^ Responderam, pois, os judeus e lhe disseram: Porventura, não temos razão em dizer que és samaritano e tens demônio?

[[v43-8-49]]

^<<v43-8-49,49>>^ Replicou Jesus: Eu não tenho demônio; pelo contrário, honro a meu Pai, e vós me desonrais.

[[v43-8-50]]

^<<v43-8-50,50>>^ Eu não procuro a minha própria glória; há quem a busque e julgue.

[[v43-8-51]]

^<<v43-8-51,51>>^ Em verdade, em verdade vos digo: se alguém guardar a minha palavra, não verá a morte, eternamente.

[[v43-8-52]]

^<<v43-8-52,52>>^ Disseram-lhe os judeus: Agora, estamos certos de que tens demônio. Abraão morreu, e também os profetas, e tu dizes: Se alguém guardar a minha palavra, não provará a morte, eternamente.

[[v43-8-53]]

^<<v43-8-53,53>>^ És maior do que Abraão, o nosso pai, que morreu? Também os profetas morreram. Quem, pois, te fazes ser?

[[v43-8-54]]

^<<v43-8-54,54>>^ Respondeu Jesus: Se eu me glorifico a mim mesmo, a minha glória nada é; quem me glorifica é meu Pai, o qual vós dizeis que é vosso Deus.

[[v43-8-55]]

^<<v43-8-55,55>>^ Entretanto, vós não o tendes conhecido; eu, porém, o conheço. Se eu disser que não o conheço, serei como vós: mentiroso; mas eu o conheço e guardo a sua palavra.

[[v43-8-56]]

^<<v43-8-56,56>>^ Abraão, vosso pai, alegrou-se por ver o meu dia, viu-o e regozijou-se.

[[v43-8-57]]

^<<v43-8-57,57>>^ Perguntaram-lhe, pois, os judeus: Ainda não tens cinquenta anos e viste Abraão?

[[v43-8-58]]

^<<v43-8-58,58>>^ Respondeu-lhes Jesus: Em verdade, em verdade eu vos digo: antes que Abraão existisse, Eu Sou .

[[v43-8-59]]

^<<v43-8-59,59>>^ Então, pegaram em pedras para atirarem nele; mas Jesus se ocultou e saiu do templo.

'''

xref:043-joao/043-joao-007.adoc#v43-7-0[&#60; Capítulo Anterior] | <<v43-8-0,Topo>> | xref:043-joao/043-joao-009.adoc#v43-9-0[Próximo Capítulo &#62;]