include::./index.adoc[]

[[v43-16-0]]
=== João, 16
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-16-1]]

^<<v43-16-1,1>>^ Tenho-vos dito estas coisas para que não vos escandalizeis.

[[v43-16-2]]

^<<v43-16-2,2>>^ Eles vos expulsarão das sinagogas; mas vem a hora em que todo o que vos matar julgará com isso tributar culto a Deus.

[[v43-16-3]]

^<<v43-16-3,3>>^ Isto farão porque não conhecem o Pai, nem a mim.

[[v43-16-4]]

^<<v43-16-4,4>>^ Ora, estas coisas vos tenho dito para que, quando a hora chegar, vos recordeis de que eu vo-las disse. Não vo-las disse desde o princípio, porque eu estava convosco.

[[v43-16-5]]

^<<v43-16-5,5>>^ Mas, agora, vou para junto daquele que me enviou, e nenhum de vós me pergunta: Para onde vais?

[[v43-16-6]]

^<<v43-16-6,6>>^ Pelo contrário, porque vos tenho dito estas coisas, a tristeza encheu o vosso coração.

[[v43-16-7]]

^<<v43-16-7,7>>^ Mas eu vos digo a verdade: convém-vos que eu vá, porque, se eu não for, o Consolador não virá para vós outros; se, porém, eu for, eu vo-lo enviarei.

[[v43-16-8]]

^<<v43-16-8,8>>^ Quando ele vier, convencerá o mundo do pecado, da justiça e do juízo:

[[v43-16-9]]

^<<v43-16-9,9>>^ do pecado, porque não creem em mim;

[[v43-16-10]]

^<<v43-16-10,10>>^ da justiça, porque vou para o Pai, e não me vereis mais;

[[v43-16-11]]

^<<v43-16-11,11>>^ do juízo, porque o príncipe deste mundo já está julgado.

[[v43-16-12]]

^<<v43-16-12,12>>^ Tenho ainda muito que vos dizer, mas vós não o podeis suportar agora;

[[v43-16-13]]

^<<v43-16-13,13>>^ quando vier, porém, o Espírito da verdade, ele vos guiará a toda a verdade; porque não falará por si mesmo, mas dirá tudo o que tiver ouvido e vos anunciará as coisas que hão de vir.

[[v43-16-14]]

^<<v43-16-14,14>>^ Ele me glorificará, porque há de receber do que é meu e vo-lo há de anunciar.

[[v43-16-15]]

^<<v43-16-15,15>>^ Tudo quanto o Pai tem é meu; por isso é que vos disse que há de receber do que é meu e vo-lo há de anunciar.

[[v43-16-16]]

^<<v43-16-16,16>>^ Um pouco, e não mais me vereis; outra vez um pouco, e ver-me-eis.

[[v43-16-17]]

^<<v43-16-17,17>>^ Então, alguns dos seus discípulos disseram uns aos outros: Que vem a ser isto que nos diz: Um pouco, e não mais me vereis, e outra vez um pouco, e ver-me-eis; e: Vou para o Pai?

[[v43-16-18]]

^<<v43-16-18,18>>^ Diziam, pois: Que vem a ser esse — um pouco? Não compreendemos o que quer dizer.

[[v43-16-19]]

^<<v43-16-19,19>>^ Percebendo Jesus que desejavam interrogá-lo, perguntou-lhes: Indagais entre vós a respeito disto que vos disse: Um pouco, e não me vereis, e outra vez um pouco, e ver-me-eis?

[[v43-16-20]]

^<<v43-16-20,20>>^ Em verdade, em verdade eu vos digo que chorareis e vos lamentareis, e o mundo se alegrará; vós ficareis tristes, mas a vossa tristeza se converterá em alegria.

[[v43-16-21]]

^<<v43-16-21,21>>^ A mulher, quando está para dar à luz, tem tristeza, porque a sua hora é chegada; mas, depois de nascido o menino, já não se lembra da aflição, pelo prazer que tem de ter nascido ao mundo um homem.

[[v43-16-22]]

^<<v43-16-22,22>>^ Assim também agora vós tendes tristeza; mas outra vez vos verei; o vosso coração se alegrará, e a vossa alegria ninguém poderá tirar.

[[v43-16-23]]

^<<v43-16-23,23>>^ Naquele dia, nada me perguntareis. Em verdade, em verdade vos digo: se pedirdes alguma coisa ao Pai, ele vo-la concederá em meu nome.

[[v43-16-24]]

^<<v43-16-24,24>>^ Até agora nada tendes pedido em meu nome; pedi e recebereis, para que a vossa alegria seja completa.

[[v43-16-25]]

^<<v43-16-25,25>>^ Estas coisas vos tenho dito por meio de figuras; vem a hora em que não vos falarei por meio de comparações, mas vos falarei claramente a respeito do Pai.

[[v43-16-26]]

^<<v43-16-26,26>>^ Naquele dia, pedireis em meu nome; e não vos digo que rogarei ao Pai por vós.

[[v43-16-27]]

^<<v43-16-27,27>>^ Porque o próprio Pai vos ama, visto que me tendes amado e tendes crido que eu vim da parte de Deus.

[[v43-16-28]]

^<<v43-16-28,28>>^ Vim do Pai e entrei no mundo; todavia, deixo o mundo e vou para o Pai.

[[v43-16-29]]

^<<v43-16-29,29>>^ Disseram os seus discípulos: Agora é que falas claramente e não empregas nenhuma figura.

[[v43-16-30]]

^<<v43-16-30,30>>^ Agora, vemos que sabes todas as coisas e não precisas de que alguém te pergunte; por isso, cremos que, de fato, vieste de Deus.

[[v43-16-31]]

^<<v43-16-31,31>>^ Respondeu-lhes Jesus: Credes agora?

[[v43-16-32]]

^<<v43-16-32,32>>^ Eis que vem a hora e já é chegada, em que sereis dispersos, cada um para sua casa, e me deixareis só; contudo, não estou só, porque o Pai está comigo.

[[v43-16-33]]

^<<v43-16-33,33>>^ Estas coisas vos tenho dito para que tenhais paz em mim. No mundo, passais por aflições; mas tende bom ânimo; eu venci o mundo.

'''

xref:043-joao/043-joao-015.adoc#v43-15-0[&#60; Capítulo Anterior] | <<v43-16-0,Topo>> | xref:043-joao/043-joao-017.adoc#v43-17-0[Próximo Capítulo &#62;]