include::./index.adoc[]

[[v43-5-0]]
=== João, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-5-1]]

^<<v43-5-1,1>>^ Passadas estas coisas, havia uma festa dos judeus, e Jesus subiu para Jerusalém.

[[v43-5-2]]

^<<v43-5-2,2>>^ Ora, existe ali, junto à Porta das Ovelhas, um tanque, chamado em hebraico Betesda, o qual tem cinco pavilhões.

[[v43-5-3]]

^<<v43-5-3,3>>^ Nestes, jazia uma multidão de enfermos, cegos, coxos, paralíticos

[[v43-5-4]]

^<<v43-5-4,4>>^ [esperando que se movesse a água. Porquanto um anjo descia em certo tempo, agitando-a; e o primeiro que entrava no tanque, uma vez agitada a água, sarava de qualquer doença que tivesse].

[[v43-5-5]]

^<<v43-5-5,5>>^ Estava ali um homem enfermo havia trinta e oito anos.

[[v43-5-6]]

^<<v43-5-6,6>>^ Jesus, vendo-o deitado e sabendo que estava assim há muito tempo, perguntou-lhe: Queres ser curado?

[[v43-5-7]]

^<<v43-5-7,7>>^ Respondeu-lhe o enfermo: Senhor, não tenho ninguém que me ponha no tanque, quando a água é agitada; pois, enquanto eu vou, desce outro antes de mim.

[[v43-5-8]]

^<<v43-5-8,8>>^ Então, lhe disse Jesus: Levanta-te, toma o teu leito e anda.

[[v43-5-9]]

^<<v43-5-9,9>>^ Imediatamente, o homem se viu curado e, tomando o leito, pôs-se a andar. E aquele dia era sábado.

[[v43-5-10]]

^<<v43-5-10,10>>^ Por isso, disseram os judeus ao que fora curado: Hoje é sábado, e não te é lícito carregar o leito.

[[v43-5-11]]

^<<v43-5-11,11>>^ Ao que ele lhes respondeu: O mesmo que me curou me disse: Toma o teu leito e anda.

[[v43-5-12]]

^<<v43-5-12,12>>^ Perguntaram-lhe eles: Quem é o homem que te disse: Toma o teu leito e anda?

[[v43-5-13]]

^<<v43-5-13,13>>^ Mas o que fora curado não sabia quem era; porque Jesus se havia retirado, por haver muita gente naquele lugar.

[[v43-5-14]]

^<<v43-5-14,14>>^ Mais tarde, Jesus o encontrou no templo e lhe disse: Olha que já estás curado; não peques mais, para que não te suceda coisa pior.

[[v43-5-15]]

^<<v43-5-15,15>>^ O homem retirou-se e disse aos judeus que fora Jesus quem o havia curado.

[[v43-5-16]]

^<<v43-5-16,16>>^ E os judeus perseguiam Jesus, porque fazia estas coisas no sábado.

[[v43-5-17]]

^<<v43-5-17,17>>^ Mas ele lhes disse: Meu Pai trabalha até agora, e eu trabalho também.

[[v43-5-18]]

^<<v43-5-18,18>>^ Por isso, pois, os judeus ainda mais procuravam matá-lo, porque não somente violava o sábado, mas também dizia que Deus era seu próprio Pai, fazendo-se igual a Deus.

[[v43-5-19]]

^<<v43-5-19,19>>^ Então, lhes falou Jesus: Em verdade, em verdade vos digo que o Filho nada pode fazer de si mesmo, senão somente aquilo que vir fazer o Pai; porque tudo o que este fizer, o Filho também semelhantemente o faz.

[[v43-5-20]]

^<<v43-5-20,20>>^ Porque o Pai ama ao Filho, e lhe mostra tudo o que faz, e maiores obras do que estas lhe mostrará, para que vos maravilheis.

[[v43-5-21]]

^<<v43-5-21,21>>^ Pois assim como o Pai ressuscita e vivifica os mortos, assim também o Filho vivifica aqueles a quem quer.

[[v43-5-22]]

^<<v43-5-22,22>>^ E o Pai a ninguém julga, mas ao Filho confiou todo julgamento,

[[v43-5-23]]

^<<v43-5-23,23>>^ a fim de que todos honrem o Filho do modo por que honram o Pai. Quem não honra o Filho não honra o Pai que o enviou.

[[v43-5-24]]

^<<v43-5-24,24>>^ Em verdade, em verdade vos digo: quem ouve a minha palavra e crê naquele que me enviou tem a vida eterna, não entra em juízo, mas passou da morte para a vida.

[[v43-5-25]]

^<<v43-5-25,25>>^ Em verdade, em verdade vos digo que vem a hora e já chegou, em que os mortos ouvirão a voz do Filho de Deus; e os que a ouvirem viverão.

[[v43-5-26]]

^<<v43-5-26,26>>^ Porque assim como o Pai tem vida em si mesmo, também concedeu ao Filho ter vida em si mesmo.

[[v43-5-27]]

^<<v43-5-27,27>>^ E lhe deu autoridade para julgar, porque é o Filho do Homem.

[[v43-5-28]]

^<<v43-5-28,28>>^ Não vos maravilheis disto, porque vem a hora em que todos os que se acham nos túmulos ouvirão a sua voz e sairão:

[[v43-5-29]]

^<<v43-5-29,29>>^ os que tiverem feito o bem, para a ressurreição da vida; e os que tiverem praticado o mal, para a ressurreição do juízo.

[[v43-5-30]]

^<<v43-5-30,30>>^ Eu nada posso fazer de mim mesmo; na forma por que ouço, julgo. O meu juízo é justo, porque não procuro a minha própria vontade, e sim a daquele que me enviou.

[[v43-5-31]]

^<<v43-5-31,31>>^ Se eu testifico a respeito de mim mesmo, o meu testemunho não é verdadeiro.

[[v43-5-32]]

^<<v43-5-32,32>>^ Outro é o que testifica a meu respeito, e sei que é verdadeiro o testemunho que ele dá de mim.

[[v43-5-33]]

^<<v43-5-33,33>>^ Mandastes mensageiros a João, e ele deu testemunho da verdade.

[[v43-5-34]]

^<<v43-5-34,34>>^ Eu, porém, não aceito humano testemunho; digo-vos, entretanto, estas coisas para que sejais salvos.

[[v43-5-35]]

^<<v43-5-35,35>>^ Ele era a lâmpada que ardia e alumiava, e vós quisestes, por algum tempo, alegrar-vos com a sua luz.

[[v43-5-36]]

^<<v43-5-36,36>>^ Mas eu tenho maior testemunho do que o de João; porque as obras que o Pai me confiou para que eu as realizasse, essas que eu faço testemunham a meu respeito de que o Pai me enviou.

[[v43-5-37]]

^<<v43-5-37,37>>^ O Pai, que me enviou, esse mesmo é que tem dado testemunho de mim. Jamais tendes ouvido a sua voz, nem visto a sua forma.

[[v43-5-38]]

^<<v43-5-38,38>>^ Também não tendes a sua palavra permanente em vós, porque não credes naquele a quem ele enviou.

[[v43-5-39]]

^<<v43-5-39,39>>^ Examinais as Escrituras, porque julgais ter nelas a vida eterna, e são elas mesmas que testificam de mim.

[[v43-5-40]]

^<<v43-5-40,40>>^ Contudo, não quereis vir a mim para terdes vida.

[[v43-5-41]]

^<<v43-5-41,41>>^ Eu não aceito glória que vem dos homens;

[[v43-5-42]]

^<<v43-5-42,42>>^ sei, entretanto, que não tendes em vós o amor de Deus.

[[v43-5-43]]

^<<v43-5-43,43>>^ Eu vim em nome de meu Pai, e não me recebeis; se outro vier em seu próprio nome, certamente, o recebereis.

[[v43-5-44]]

^<<v43-5-44,44>>^ Como podeis crer, vós os que aceitais glória uns dos outros e, contudo, não procurais a glória que vem do Deus único?

[[v43-5-45]]

^<<v43-5-45,45>>^ Não penseis que eu vos acusarei perante o Pai; quem vos acusa é Moisés, em quem tendes firmado a vossa confiança.

[[v43-5-46]]

^<<v43-5-46,46>>^ Porque, se, de fato, crêsseis em Moisés, também creríeis em mim; porquanto ele escreveu a meu respeito.

[[v43-5-47]]

^<<v43-5-47,47>>^ Se, porém, não credes nos seus escritos, como crereis nas minhas palavras?

'''

xref:043-joao/043-joao-004.adoc#v43-4-0[&#60; Capítulo Anterior] | <<v43-5-0,Topo>> | xref:043-joao/043-joao-006.adoc#v43-6-0[Próximo Capítulo &#62;]