include::./index.adoc[]

[[v43-12-0]]
=== João, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-12-1]]

^<<v43-12-1,1>>^ Seis dias antes da Páscoa, foi Jesus para Betânia, onde estava Lázaro, a quem ele ressuscitara dentre os mortos.

[[v43-12-2]]

^<<v43-12-2,2>>^ Deram-lhe, pois, ali, uma ceia; Marta servia, sendo Lázaro um dos que estavam com ele à mesa.

[[v43-12-3]]

^<<v43-12-3,3>>^ Então, Maria, tomando uma libra de bálsamo de nardo puro, mui precioso, ungiu os pés de Jesus e os enxugou com os seus cabelos; e encheu-se toda a casa com o perfume do bálsamo.

[[v43-12-4]]

^<<v43-12-4,4>>^ Mas Judas Iscariotes, um dos seus discípulos, o que estava para traí-lo, disse:

[[v43-12-5]]

^<<v43-12-5,5>>^ Por que não se vendeu este perfume por trezentos denários e não se deu aos pobres?

[[v43-12-6]]

^<<v43-12-6,6>>^ Isto disse ele, não porque tivesse cuidado dos pobres; mas porque era ladrão e, tendo a bolsa, tirava o que nela se lançava.

[[v43-12-7]]

^<<v43-12-7,7>>^ Jesus, entretanto, disse: Deixa-a! Que ela guarde isto para o dia em que me embalsamarem;

[[v43-12-8]]

^<<v43-12-8,8>>^ porque os pobres, sempre os tendes convosco, mas a mim nem sempre me tendes.

[[v43-12-9]]

^<<v43-12-9,9>>^ Soube numerosa multidão dos judeus que Jesus estava ali, e lá foram não só por causa dele, mas também para verem Lázaro, a quem ele ressuscitara dentre os mortos.

[[v43-12-10]]

^<<v43-12-10,10>>^ Mas os principais sacerdotes resolveram matar também Lázaro;

[[v43-12-11]]

^<<v43-12-11,11>>^ porque muitos dos judeus, por causa dele, voltavam crendo em Jesus.

[[v43-12-12]]

^<<v43-12-12,12>>^ No dia seguinte, a numerosa multidão que viera à festa, tendo ouvido que Jesus estava de caminho para Jerusalém,

[[v43-12-13]]

^<<v43-12-13,13>>^ tomou ramos de palmeiras e saiu ao seu encontro, clamando: Hosana! Bendito o que vem em nome do Senhor e que é Rei de Israel!

[[v43-12-14]]

^<<v43-12-14,14>>^ E Jesus, tendo conseguido um jumentinho, montou-o, segundo está escrito:

[[v43-12-15]]

^<<v43-12-15,15>>^ Não temas, filha de Sião, eis que o teu Rei aí vem, montado em um filho de jumenta.

[[v43-12-16]]

^<<v43-12-16,16>>^ Seus discípulos a princípio não compreenderam isto; quando, porém, Jesus foi glorificado, então, eles se lembraram de que estas coisas estavam escritas a respeito dele e também de que isso lhe fizeram.

[[v43-12-17]]

^<<v43-12-17,17>>^ Dava, pois, testemunho disto a multidão que estivera com ele, quando chamara a Lázaro do túmulo e o levantara dentre os mortos.

[[v43-12-18]]

^<<v43-12-18,18>>^ Por causa disso, também, a multidão lhe saiu ao encontro, pois ouviu que ele fizera este sinal.

[[v43-12-19]]

^<<v43-12-19,19>>^ De sorte que os fariseus disseram entre si: Vede que nada aproveitais! Eis aí vai o mundo após ele.

[[v43-12-20]]

^<<v43-12-20,20>>^ Ora, entre os que subiram para adorar durante a festa, havia alguns gregos;

[[v43-12-21]]

^<<v43-12-21,21>>^ estes, pois, se dirigiram a Filipe, que era de Betsaida da Galileia, e lhe rogaram: Senhor, queremos ver Jesus.

[[v43-12-22]]

^<<v43-12-22,22>>^ Filipe foi dizê-lo a André, e André e Filipe o comunicaram a Jesus.

[[v43-12-23]]

^<<v43-12-23,23>>^ Respondeu-lhes Jesus: É chegada a hora de ser glorificado o Filho do Homem.

[[v43-12-24]]

^<<v43-12-24,24>>^ Em verdade, em verdade vos digo: se o grão de trigo, caindo na terra, não morrer, fica ele só; mas, se morrer, produz muito fruto.

[[v43-12-25]]

^<<v43-12-25,25>>^ Quem ama a sua vida perde-a; mas aquele que odeia a sua vida neste mundo preservá-la-á para a vida eterna.

[[v43-12-26]]

^<<v43-12-26,26>>^ Se alguém me serve, siga-me, e, onde eu estou, ali estará também o meu servo. E, se alguém me servir, o Pai o honrará.

[[v43-12-27]]

^<<v43-12-27,27>>^ Agora, está angustiada a minha alma, e que direi eu? Pai, salva-me desta hora? Mas precisamente com este propósito vim para esta hora.

[[v43-12-28]]

^<<v43-12-28,28>>^ Pai, glorifica o teu nome.  Então, veio uma voz do céu: Eu já o glorifiquei e ainda o glorificarei.

[[v43-12-29]]

^<<v43-12-29,29>>^ A multidão, pois, que ali estava, tendo ouvido a voz, dizia ter havido um trovão. Outros diziam: Foi um anjo que lhe falou.

[[v43-12-30]]

^<<v43-12-30,30>>^ Então, explicou Jesus: Não foi por mim que veio esta voz, e sim por vossa causa.

[[v43-12-31]]

^<<v43-12-31,31>>^ Chegou o momento de ser julgado este mundo, e agora o seu príncipe será expulso.

[[v43-12-32]]

^<<v43-12-32,32>>^ E eu, quando for levantado da terra, atrairei todos a mim mesmo.

[[v43-12-33]]

^<<v43-12-33,33>>^ Isto dizia, significando de que gênero de morte estava para morrer.

[[v43-12-34]]

^<<v43-12-34,34>>^ Replicou-lhe, pois, a multidão: Nós temos ouvido da lei que o Cristo permanece para sempre, e como dizes tu ser necessário que o Filho do Homem seja levantado? Quem é esse Filho do Homem?

[[v43-12-35]]

^<<v43-12-35,35>>^ Respondeu-lhes Jesus: Ainda por um pouco a luz está convosco. Andai enquanto tendes a luz, para que as trevas não vos apanhem; e quem anda nas trevas não sabe para onde vai.

[[v43-12-36]]

^<<v43-12-36,36>>^ Enquanto tendes a luz, crede na luz, para que vos torneis filhos da luz.  Jesus disse estas coisas e, retirando-se, ocultou-se deles.

[[v43-12-37]]

^<<v43-12-37,37>>^ E, embora tivesse feito tantos sinais na sua presença, não creram nele,

[[v43-12-38]]

^<<v43-12-38,38>>^ para se cumprir a palavra do profeta Isaías, que diz: Senhor, quem creu em nossa pregação? E a quem foi revelado o braço do Senhor?

[[v43-12-39]]

^<<v43-12-39,39>>^ Por isso, não podiam crer, porque Isaías disse ainda:

[[v43-12-40]]

^<<v43-12-40,40>>^ Cegou-lhes os olhos e endureceu-lhes o coração, para que não vejam com os olhos, nem entendam com o coração, e se convertam, e sejam por mim curados.

[[v43-12-41]]

^<<v43-12-41,41>>^ Isto disse Isaías porque viu a glória dele e falou a seu respeito.

[[v43-12-42]]

^<<v43-12-42,42>>^ Contudo, muitos dentre as próprias autoridades creram nele, mas, por causa dos fariseus, não o confessavam, para não serem expulsos da sinagoga;

[[v43-12-43]]

^<<v43-12-43,43>>^ porque amaram mais a glória dos homens do que a glória de Deus.

[[v43-12-44]]

^<<v43-12-44,44>>^ E Jesus clamou, dizendo: Quem crê em mim crê, não em mim, mas naquele que me enviou.

[[v43-12-45]]

^<<v43-12-45,45>>^ E quem me vê a mim vê aquele que me enviou.

[[v43-12-46]]

^<<v43-12-46,46>>^ Eu vim como luz para o mundo, a fim de que todo aquele que crê em mim não permaneça nas trevas.

[[v43-12-47]]

^<<v43-12-47,47>>^ Se alguém ouvir as minhas palavras e não as guardar, eu não o julgo; porque eu não vim para julgar o mundo, e sim para salvá-lo.

[[v43-12-48]]

^<<v43-12-48,48>>^ Quem me rejeita e não recebe as minhas palavras tem quem o julgue; a própria palavra que tenho proferido, essa o julgará no último dia.

[[v43-12-49]]

^<<v43-12-49,49>>^ Porque eu não tenho falado por mim mesmo, mas o Pai, que me enviou, esse me tem prescrito o que dizer e o que anunciar.

[[v43-12-50]]

^<<v43-12-50,50>>^ E sei que o seu mandamento é a vida eterna. As coisas, pois, que eu falo, como o Pai mo tem dito, assim falo.

'''

xref:043-joao/043-joao-011.adoc#v43-11-0[&#60; Capítulo Anterior] | <<v43-12-0,Topo>> | xref:043-joao/043-joao-013.adoc#v43-13-0[Próximo Capítulo &#62;]