include::./index.adoc[]

[[v43-4-0]]
=== João, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-4-1]]

^<<v43-4-1,1>>^ Quando, pois, o Senhor veio a saber que os fariseus tinham ouvido dizer que ele, Jesus, fazia e batizava mais discípulos que João

[[v43-4-2]]

^<<v43-4-2,2>>^ (se bem que Jesus mesmo não batizava, e sim os seus discípulos),

[[v43-4-3]]

^<<v43-4-3,3>>^ deixou a Judeia, retirando-se outra vez para a Galileia.

[[v43-4-4]]

^<<v43-4-4,4>>^ E era-lhe necessário atravessar a província de Samaria.

[[v43-4-5]]

^<<v43-4-5,5>>^ Chegou, pois, a uma cidade samaritana, chamada Sicar, perto das terras que Jacó dera a seu filho José.

[[v43-4-6]]

^<<v43-4-6,6>>^ Estava ali a fonte de Jacó. Cansado da viagem, assentara-se Jesus junto à fonte, por volta da hora sexta.

[[v43-4-7]]

^<<v43-4-7,7>>^ Nisto, veio uma mulher samaritana tirar água. Disse-lhe Jesus: Dá-me de beber.

[[v43-4-8]]

^<<v43-4-8,8>>^ Pois seus discípulos tinham ido à cidade para comprar alimentos.

[[v43-4-9]]

^<<v43-4-9,9>>^ Então, lhe disse a mulher samaritana: Como, sendo tu judeu, pedes de beber a mim, que sou mulher samaritana (porque os judeus não se dão com os samaritanos )?

[[v43-4-10]]

^<<v43-4-10,10>>^ Replicou-lhe Jesus: Se conheceras o dom de Deus e quem é o que te pede: dá-me de beber, tu lhe pedirias, e ele te daria água viva.

[[v43-4-11]]

^<<v43-4-11,11>>^ Respondeu-lhe ela: Senhor, tu não tens com que a tirar, e o poço é fundo; onde, pois, tens a água viva?

[[v43-4-12]]

^<<v43-4-12,12>>^ És tu, porventura, maior do que Jacó, o nosso pai, que nos deu o poço, do qual ele mesmo bebeu, e, bem assim, seus filhos, e seu gado?

[[v43-4-13]]

^<<v43-4-13,13>>^ Afirmou-lhe Jesus: Quem beber desta água tornará a ter sede;

[[v43-4-14]]

^<<v43-4-14,14>>^ aquele, porém, que beber da água que eu lhe der nunca mais terá sede; pelo contrário, a água que eu lhe der será nele uma fonte a jorrar para a vida eterna.

[[v43-4-15]]

^<<v43-4-15,15>>^ Disse-lhe a mulher: Senhor, dá-me dessa água para que eu não mais tenha sede, nem precise vir aqui buscá-la.

[[v43-4-16]]

^<<v43-4-16,16>>^ Disse-lhe Jesus: Vai, chama teu marido e vem cá;

[[v43-4-17]]

^<<v43-4-17,17>>^ ao que lhe respondeu a mulher: Não tenho marido. Replicou-lhe Jesus: Bem disseste, não tenho marido;

[[v43-4-18]]

^<<v43-4-18,18>>^ porque cinco maridos já tiveste, e esse que agora tens não é teu marido; isto disseste com verdade.

[[v43-4-19]]

^<<v43-4-19,19>>^ Senhor, disse-lhe a mulher, vejo que tu és profeta.

[[v43-4-20]]

^<<v43-4-20,20>>^ Nossos pais adoravam neste monte; vós, entretanto, dizeis que em Jerusalém é o lugar onde se deve adorar.

[[v43-4-21]]

^<<v43-4-21,21>>^ Disse-lhe Jesus: Mulher, podes crer-me que a hora vem, quando nem neste monte, nem em Jerusalém adorareis o Pai.

[[v43-4-22]]

^<<v43-4-22,22>>^ Vós adorais o que não conheceis; nós adoramos o que conhecemos, porque a salvação vem dos judeus.

[[v43-4-23]]

^<<v43-4-23,23>>^ Mas vem a hora e já chegou, em que os verdadeiros adoradores adorarão o Pai em espírito e em verdade; porque são estes que o Pai procura para seus adoradores.

[[v43-4-24]]

^<<v43-4-24,24>>^ Deus é espírito; e importa que os seus adoradores o adorem em espírito e em verdade.

[[v43-4-25]]

^<<v43-4-25,25>>^ Eu sei, respondeu a mulher, que há de vir o Messias, chamado Cristo; quando ele vier, nos anunciará todas as coisas.

[[v43-4-26]]

^<<v43-4-26,26>>^ Disse-lhe Jesus: Eu o sou, eu que falo contigo.

[[v43-4-27]]

^<<v43-4-27,27>>^ Neste ponto, chegaram os seus discípulos e se admiraram de que estivesse falando com uma mulher; todavia, nenhum lhe disse: Que perguntas? Ou: Por que falas com ela?

[[v43-4-28]]

^<<v43-4-28,28>>^ Quanto à mulher, deixou o seu cântaro, foi à cidade e disse àqueles homens:

[[v43-4-29]]

^<<v43-4-29,29>>^ Vinde comigo e vede um homem que me disse tudo quanto tenho feito. Será este, porventura, o Cristo?!

[[v43-4-30]]

^<<v43-4-30,30>>^ Saíram, pois, da cidade e vieram ter com ele.

[[v43-4-31]]

^<<v43-4-31,31>>^ Nesse ínterim, os discípulos lhe rogavam, dizendo: Mestre, come!

[[v43-4-32]]

^<<v43-4-32,32>>^ Mas ele lhes disse: Uma comida tenho para comer, que vós não conheceis.

[[v43-4-33]]

^<<v43-4-33,33>>^ Diziam, então, os discípulos uns aos outros: Ter-lhe-ia, porventura, alguém trazido o que comer?

[[v43-4-34]]

^<<v43-4-34,34>>^ Disse-lhes Jesus: A minha comida consiste em fazer a vontade daquele que me enviou e realizar a sua obra.

[[v43-4-35]]

^<<v43-4-35,35>>^ Não dizeis vós que ainda há quatro meses até à ceifa? Eu, porém, vos digo: erguei os olhos e vede os campos, pois já branquejam para a ceifa.

[[v43-4-36]]

^<<v43-4-36,36>>^ O ceifeiro recebe desde já a recompensa e entesoura o seu fruto para a vida eterna; e, dessarte, se alegram tanto o semeador como o ceifeiro.

[[v43-4-37]]

^<<v43-4-37,37>>^ Pois, no caso, é verdadeiro o ditado: Um é o semeador, e outro é o ceifeiro.

[[v43-4-38]]

^<<v43-4-38,38>>^ Eu vos enviei para ceifar o que não semeastes; outros trabalharam, e vós entrastes no seu trabalho.

[[v43-4-39]]

^<<v43-4-39,39>>^ Muitos samaritanos daquela cidade creram nele, em virtude do testemunho da mulher, que anunciara: Ele me disse tudo quanto tenho feito.

[[v43-4-40]]

^<<v43-4-40,40>>^ Vindo, pois, os samaritanos ter com Jesus, pediam-lhe que permanecesse com eles; e ficou ali dois dias.

[[v43-4-41]]

^<<v43-4-41,41>>^ Muitos outros creram nele, por causa da sua palavra,

[[v43-4-42]]

^<<v43-4-42,42>>^ e diziam à mulher: Já agora não é pelo que disseste que nós cremos; mas porque nós mesmos temos ouvido e sabemos que este é verdadeiramente o Salvador do mundo.

[[v43-4-43]]

^<<v43-4-43,43>>^ Passados dois dias, partiu dali para a Galileia.

[[v43-4-44]]

^<<v43-4-44,44>>^ Porque o mesmo Jesus testemunhou que um profeta não tem honras na sua própria terra.

[[v43-4-45]]

^<<v43-4-45,45>>^ Assim, quando chegou à Galileia, os galileus o receberam, porque viram todas as coisas que ele fizera em Jerusalém, por ocasião da festa, à qual eles também tinham comparecido.

[[v43-4-46]]

^<<v43-4-46,46>>^ Dirigiu-se, de novo, a Caná da Galileia, onde da água fizera vinho. Ora, havia um oficial do rei, cujo filho estava doente em Cafarnaum.

[[v43-4-47]]

^<<v43-4-47,47>>^ Tendo ouvido dizer que Jesus viera da Judeia para a Galileia, foi ter com ele e lhe rogou que descesse para curar seu filho, que estava à morte.

[[v43-4-48]]

^<<v43-4-48,48>>^ Então, Jesus lhe disse: Se, porventura, não virdes sinais e prodígios, de modo nenhum crereis.

[[v43-4-49]]

^<<v43-4-49,49>>^ Rogou-lhe o oficial: Senhor, desce, antes que meu filho morra.

[[v43-4-50]]

^<<v43-4-50,50>>^ Vai,  disse-lhe Jesus; teu filho vive.  O homem creu na palavra de Jesus e partiu.

[[v43-4-51]]

^<<v43-4-51,51>>^ Já ele descia, quando os seus servos lhe vieram ao encontro, anunciando-lhe que o seu filho vivia.

[[v43-4-52]]

^<<v43-4-52,52>>^ Então, indagou deles a que hora o seu filho se sentira melhor. Informaram: Ontem, à hora sétima a febre o deixou.

[[v43-4-53]]

^<<v43-4-53,53>>^ Com isto, reconheceu o pai ser aquela precisamente a hora em que Jesus lhe dissera: Teu filho vive; e creu ele e toda a sua casa.

[[v43-4-54]]

^<<v43-4-54,54>>^ Foi este o segundo sinal que fez Jesus, depois de vir da Judeia para a Galileia.

'''

xref:043-joao/043-joao-003.adoc#v43-3-0[&#60; Capítulo Anterior] | <<v43-4-0,Topo>> | xref:043-joao/043-joao-005.adoc#v43-5-0[Próximo Capítulo &#62;]