include::./index.adoc[]

[[v43-15-0]]
=== João, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-15-1]]

^<<v43-15-1,1>>^ Eu sou a videira verdadeira, e meu Pai é o agricultor.

[[v43-15-2]]

^<<v43-15-2,2>>^ Todo ramo que, estando em mim, não der fruto, ele o corta; e todo o que dá fruto limpa, para que produza mais fruto ainda.

[[v43-15-3]]

^<<v43-15-3,3>>^ Vós já estais limpos pela palavra que vos tenho falado;

[[v43-15-4]]

^<<v43-15-4,4>>^ permanecei em mim, e eu permanecerei em vós. Como não pode o ramo produzir fruto de si mesmo, se não permanecer na videira, assim, nem vós o podeis dar, se não permanecerdes em mim.

[[v43-15-5]]

^<<v43-15-5,5>>^ Eu sou a videira, vós, os ramos. Quem permanece em mim, e eu, nele, esse dá muito fruto; porque sem mim nada podeis fazer.

[[v43-15-6]]

^<<v43-15-6,6>>^ Se alguém não permanecer em mim, será lançado fora, à semelhança do ramo, e secará; e o apanham, lançam no fogo e o queimam.

[[v43-15-7]]

^<<v43-15-7,7>>^ Se permanecerdes em mim, e as minhas palavras permanecerem em vós, pedireis o que quiserdes, e vos será feito.

[[v43-15-8]]

^<<v43-15-8,8>>^ Nisto é glorificado meu Pai, em que deis muito fruto; e assim vos tornareis meus discípulos.

[[v43-15-9]]

^<<v43-15-9,9>>^ Como o Pai me amou, também eu vos amei; permanecei no meu amor.

[[v43-15-10]]

^<<v43-15-10,10>>^ Se guardardes os meus mandamentos, permanecereis no meu amor; assim como também eu tenho guardado os mandamentos de meu Pai e no seu amor permaneço.

[[v43-15-11]]

^<<v43-15-11,11>>^ Tenho-vos dito estas coisas para que o meu gozo esteja em vós, e o vosso gozo seja completo.

[[v43-15-12]]

^<<v43-15-12,12>>^ O meu mandamento é este: que vos ameis uns aos outros, assim como eu vos amei.

[[v43-15-13]]

^<<v43-15-13,13>>^ Ninguém tem maior amor do que este: de dar alguém a própria vida em favor dos seus amigos.

[[v43-15-14]]

^<<v43-15-14,14>>^ Vós sois meus amigos, se fazeis o que eu vos mando.

[[v43-15-15]]

^<<v43-15-15,15>>^ Já não vos chamo servos, porque o servo não sabe o que faz o seu senhor; mas tenho-vos chamado amigos, porque tudo quanto ouvi de meu Pai vos tenho dado a conhecer.

[[v43-15-16]]

^<<v43-15-16,16>>^ Não fostes vós que me escolhestes a mim; pelo contrário, eu vos escolhi a vós outros e vos designei para que vades e deis fruto, e o vosso fruto permaneça; a fim de que tudo quanto pedirdes ao Pai em meu nome, ele vo-lo conceda.

[[v43-15-17]]

^<<v43-15-17,17>>^ Isto vos mando: que vos ameis uns aos outros.

[[v43-15-18]]

^<<v43-15-18,18>>^ Se o mundo vos odeia, sabei que, primeiro do que a vós outros, me odiou a mim.

[[v43-15-19]]

^<<v43-15-19,19>>^ Se vós fôsseis do mundo, o mundo amaria o que era seu; como, todavia, não sois do mundo, pelo contrário, dele vos escolhi, por isso, o mundo vos odeia.

[[v43-15-20]]

^<<v43-15-20,20>>^ Lembrai-vos da palavra que eu vos disse: não é o servo maior do que seu senhor. Se me perseguiram a mim, também perseguirão a vós outros; se guardaram a minha palavra, também guardarão a vossa.

[[v43-15-21]]

^<<v43-15-21,21>>^ Tudo isto, porém, vos farão por causa do meu nome, porquanto não conhecem aquele que me enviou.

[[v43-15-22]]

^<<v43-15-22,22>>^ Se eu não viera, nem lhes houvera falado, pecado não teriam; mas, agora, não têm desculpa do seu pecado.

[[v43-15-23]]

^<<v43-15-23,23>>^ Quem me odeia odeia também a meu Pai.

[[v43-15-24]]

^<<v43-15-24,24>>^ Se eu não tivesse feito entre eles tais obras, quais nenhum outro fez, pecado não teriam; mas, agora, não somente têm eles visto, mas também odiado, tanto a mim como a meu Pai.

[[v43-15-25]]

^<<v43-15-25,25>>^ Isto, porém, é para que se cumpra a palavra escrita na sua lei: Odiaram-me sem motivo.

[[v43-15-26]]

^<<v43-15-26,26>>^ Quando, porém, vier o Consolador, que eu vos enviarei da parte do Pai, o Espírito da verdade, que dele procede, esse dará testemunho de mim;

[[v43-15-27]]

^<<v43-15-27,27>>^ e vós também testemunhareis, porque estais comigo desde o princípio.

'''

xref:043-joao/043-joao-014.adoc#v43-14-0[&#60; Capítulo Anterior] | <<v43-15-0,Topo>> | xref:043-joao/043-joao-016.adoc#v43-16-0[Próximo Capítulo &#62;]