include::./index.adoc[]

[[v43-20-0]]
=== João, 20
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-20-1]]

^<<v43-20-1,1>>^ No primeiro dia da semana, Maria Madalena foi ao sepulcro de madrugada, sendo ainda escuro, e viu que a pedra estava revolvida.

[[v43-20-2]]

^<<v43-20-2,2>>^ Então, correu e foi ter com Simão Pedro e com o outro discípulo, a quem Jesus amava, e disse-lhes: Tiraram do sepulcro o Senhor, e não sabemos onde o puseram.

[[v43-20-3]]

^<<v43-20-3,3>>^ Saiu, pois, Pedro e o outro discípulo e foram ao sepulcro.

[[v43-20-4]]

^<<v43-20-4,4>>^ Ambos corriam juntos, mas o outro discípulo correu mais depressa do que Pedro e chegou primeiro ao sepulcro;

[[v43-20-5]]

^<<v43-20-5,5>>^ e, abaixando-se, viu os lençóis de linho; todavia, não entrou.

[[v43-20-6]]

^<<v43-20-6,6>>^ Então, Simão Pedro, seguindo-o, chegou e entrou no sepulcro. Ele também viu os lençóis,

[[v43-20-7]]

^<<v43-20-7,7>>^ e o lenço que estivera sobre a cabeça de Jesus, e que não estava com os lençóis, mas deixado num lugar à parte.

[[v43-20-8]]

^<<v43-20-8,8>>^ Então, entrou também o outro discípulo, que chegara primeiro ao sepulcro, e viu, e creu.

[[v43-20-9]]

^<<v43-20-9,9>>^ Pois ainda não tinham compreendido a Escritura, que era necessário ressuscitar ele dentre os mortos.

[[v43-20-10]]

^<<v43-20-10,10>>^ E voltaram os discípulos outra vez para casa.

[[v43-20-11]]

^<<v43-20-11,11>>^ Maria, entretanto, permanecia junto à entrada do túmulo, chorando. Enquanto chorava, abaixou-se, e olhou para dentro do túmulo,

[[v43-20-12]]

^<<v43-20-12,12>>^ e viu dois anjos vestidos de branco, sentados onde o corpo de Jesus fora posto, um à cabeceira e outro aos pés.

[[v43-20-13]]

^<<v43-20-13,13>>^ Então, eles lhe perguntaram: Mulher, por que choras? Ela lhes respondeu: Porque levaram o meu Senhor, e não sei onde o puseram.

[[v43-20-14]]

^<<v43-20-14,14>>^ Tendo dito isto, voltou-se para trás e viu Jesus em pé, mas não reconheceu que era Jesus.

[[v43-20-15]]

^<<v43-20-15,15>>^ Perguntou-lhe Jesus: Mulher, por que choras? A quem procuras?  Ela, supondo ser ele o jardineiro, respondeu: Senhor, se tu o tiraste, dize-me onde o puseste, e eu o levarei.

[[v43-20-16]]

^<<v43-20-16,16>>^ Disse-lhe Jesus: Maria!  Ela, voltando-se, lhe disse, em hebraico: Raboni (que quer dizer Mestre)!

[[v43-20-17]]

^<<v43-20-17,17>>^ Recomendou-lhe Jesus: Não me detenhas; porque ainda não subi para meu Pai, mas vai ter com os meus irmãos e dize-lhes: Subo para meu Pai e vosso Pai, para meu Deus e vosso Deus.

[[v43-20-18]]

^<<v43-20-18,18>>^ Então, saiu Maria Madalena anunciando aos discípulos: Vi o Senhor! E contava que ele lhe dissera estas coisas.

[[v43-20-19]]

^<<v43-20-19,19>>^ Ao cair da tarde daquele dia, o primeiro da semana, trancadas as portas da casa onde estavam os discípulos com medo dos judeus, veio Jesus, pôs-se no meio e disse-lhes: Paz seja convosco!

[[v43-20-20]]

^<<v43-20-20,20>>^ E, dizendo isto, lhes mostrou as mãos e o lado. Alegraram-se, portanto, os discípulos ao verem o Senhor.

[[v43-20-21]]

^<<v43-20-21,21>>^ Disse-lhes, pois, Jesus outra vez: Paz seja convosco! Assim como o Pai me enviou, eu também vos envio.

[[v43-20-22]]

^<<v43-20-22,22>>^ E, havendo dito isto, soprou sobre eles e disse-lhes: Recebei o Espírito Santo.

[[v43-20-23]]

^<<v43-20-23,23>>^ Se de alguns perdoardes os pecados, são-lhes perdoados; se lhos retiverdes, são retidos.

[[v43-20-24]]

^<<v43-20-24,24>>^ Ora, Tomé, um dos doze, chamado Dídimo, não estava com eles quando veio Jesus.

[[v43-20-25]]

^<<v43-20-25,25>>^ Disseram-lhe, então, os outros discípulos: Vimos o Senhor. Mas ele respondeu: Se eu não vir nas suas mãos o sinal dos cravos, e ali não puser o dedo, e não puser a mão no seu lado, de modo algum acreditarei.

[[v43-20-26]]

^<<v43-20-26,26>>^ Passados oito dias, estavam outra vez ali reunidos os seus discípulos, e Tomé, com eles. Estando as portas trancadas, veio Jesus, pôs-se no meio e disse-lhes: Paz seja convosco!

[[v43-20-27]]

^<<v43-20-27,27>>^ E logo disse a Tomé: Põe aqui o dedo e vê as minhas mãos; chega também a mão e põe-na no meu lado; não sejas incrédulo, mas crente.

[[v43-20-28]]

^<<v43-20-28,28>>^ Respondeu-lhe Tomé: Senhor meu e Deus meu!

[[v43-20-29]]

^<<v43-20-29,29>>^ Disse-lhe Jesus: Porque me viste, creste? Bem-aventurados os que não viram e creram.

[[v43-20-30]]

^<<v43-20-30,30>>^ Na verdade, fez Jesus diante dos discípulos muitos outros sinais que não estão escritos neste livro.

[[v43-20-31]]

^<<v43-20-31,31>>^ Estes, porém, foram registrados para que creiais que Jesus é o Cristo, o Filho de Deus, e para que, crendo, tenhais vida em seu nome.

'''

xref:043-joao/043-joao-019.adoc#v43-19-0[&#60; Capítulo Anterior] | <<v43-20-0,Topo>> | xref:043-joao/043-joao-021.adoc#v43-21-0[Próximo Capítulo &#62;]