include::./index.adoc[]

[[v43-19-0]]
=== João, 19
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-19-1]]

^<<v43-19-1,1>>^ Então, por isso, Pilatos tomou a Jesus e mandou açoitá-lo.

[[v43-19-2]]

^<<v43-19-2,2>>^ Os soldados, tendo tecido uma coroa de espinhos, puseram-lha na cabeça e vestiram-no com um manto de púrpura.

[[v43-19-3]]

^<<v43-19-3,3>>^ Chegavam-se a ele e diziam: Salve, rei dos judeus! E davam-lhe bofetadas.

[[v43-19-4]]

^<<v43-19-4,4>>^ Outra vez saiu Pilatos e lhes disse: Eis que eu vo-lo apresento, para que saibais que eu não acho nele crime algum.

[[v43-19-5]]

^<<v43-19-5,5>>^ Saiu, pois, Jesus trazendo a coroa de espinhos e o manto de púrpura. Disse-lhes Pilatos: Eis o homem!

[[v43-19-6]]

^<<v43-19-6,6>>^ Ao verem-no, os principais sacerdotes e os seus guardas gritaram: Crucifica-o! Crucifica-o! Disse-lhes Pilatos: Tomai-o vós outros e crucificai-o; porque eu não acho nele crime algum.

[[v43-19-7]]

^<<v43-19-7,7>>^ Responderam-lhe os judeus: Temos uma lei, e, de conformidade com a lei, ele deve morrer, porque a si mesmo se fez Filho de Deus.

[[v43-19-8]]

^<<v43-19-8,8>>^ Pilatos, ouvindo tal declaração, ainda mais atemorizado ficou,

[[v43-19-9]]

^<<v43-19-9,9>>^ e, tornando a entrar no pretório, perguntou a Jesus: Donde és tu? Mas Jesus não lhe deu resposta.

[[v43-19-10]]

^<<v43-19-10,10>>^ Então, Pilatos o advertiu: Não me respondes? Não sabes que tenho autoridade para te soltar e autoridade para te crucificar?

[[v43-19-11]]

^<<v43-19-11,11>>^ Respondeu Jesus: Nenhuma autoridade terias sobre mim, se de cima não te fosse dada; por isso, quem me entregou a ti maior pecado tem.

[[v43-19-12]]

^<<v43-19-12,12>>^ A partir deste momento, Pilatos procurava soltá-lo, mas os judeus clamavam: Se soltas a este, não és amigo de César! Todo aquele que se faz rei é contra César!

[[v43-19-13]]

^<<v43-19-13,13>>^ Ouvindo Pilatos estas palavras, trouxe Jesus para fora e sentou-se no tribunal, no lugar chamado Pavimento, no hebraico Gabatá.

[[v43-19-14]]

^<<v43-19-14,14>>^ E era a parasceve pascal, cerca da hora sexta; e disse aos judeus: Eis aqui o vosso rei.

[[v43-19-15]]

^<<v43-19-15,15>>^ Eles, porém, clamavam: Fora! Fora! Crucifica-o! Disse-lhes Pilatos: Hei de crucificar o vosso rei? Responderam os principais sacerdotes: Não temos rei, senão César!

[[v43-19-16]]

^<<v43-19-16,16>>^ Então, Pilatos o entregou para ser crucificado.

[[v43-19-17]]

^<<v43-19-17,17>>^ Tomaram eles, pois, a Jesus; e ele próprio, carregando a sua cruz, saiu para o lugar chamado Calvário, Gólgota em hebraico,

[[v43-19-18]]

^<<v43-19-18,18>>^ onde o crucificaram e com ele outros dois, um de cada lado, e Jesus no meio.

[[v43-19-19]]

^<<v43-19-19,19>>^ Pilatos escreveu também um título e o colocou no cimo da cruz; o que estava escrito era: Jesus Nazareno, o Rei dos Judeus .

[[v43-19-20]]

^<<v43-19-20,20>>^ Muitos judeus leram este título, porque o lugar em que Jesus fora crucificado era perto da cidade; e estava escrito em hebraico, latim e grego.

[[v43-19-21]]

^<<v43-19-21,21>>^ Os principais sacerdotes diziam a Pilatos: Não escrevas: Rei dos judeus, e sim que ele disse: Sou o rei dos judeus.

[[v43-19-22]]

^<<v43-19-22,22>>^ Respondeu Pilatos: O que escrevi escrevi.

[[v43-19-23]]

^<<v43-19-23,23>>^ Os soldados, pois, quando crucificaram Jesus, tomaram-lhe as vestes e fizeram quatro partes, para cada soldado uma parte; e pegaram também a túnica. A túnica, porém, era sem costura, toda tecida de alto a baixo.

[[v43-19-24]]

^<<v43-19-24,24>>^ Disseram, pois, uns aos outros: Não a rasguemos, mas lancemos sortes sobre ela para ver a quem caberá — para se cumprir a Escritura: Repartiram entre si as minhas vestes e sobre a minha túnica lançaram sortes. Assim, pois, o fizeram os soldados.

[[v43-19-25]]

^<<v43-19-25,25>>^ E junto à cruz estavam a mãe de Jesus, e a irmã dela, e Maria, mulher de Clopas, e Maria Madalena.

[[v43-19-26]]

^<<v43-19-26,26>>^ Vendo Jesus sua mãe e junto a ela o discípulo amado, disse: Mulher, eis aí teu filho.

[[v43-19-27]]

^<<v43-19-27,27>>^ Depois, disse ao discípulo: Eis aí tua mãe.  Dessa hora em diante, o discípulo a tomou para casa.

[[v43-19-28]]

^<<v43-19-28,28>>^ Depois, vendo Jesus que tudo já estava consumado, para se cumprir a Escritura, disse: Tenho sede!

[[v43-19-29]]

^<<v43-19-29,29>>^ Estava ali um vaso cheio de vinagre. Embeberam de vinagre uma esponja e, fixando-a num caniço de hissopo, lha chegaram à boca.

[[v43-19-30]]

^<<v43-19-30,30>>^ Quando, pois, Jesus tomou o vinagre, disse: Está consumado!  E, inclinando a cabeça, rendeu o espírito.

[[v43-19-31]]

^<<v43-19-31,31>>^ Então, os judeus, para que no sábado não ficassem os corpos na cruz, visto como era a preparação, pois era grande o dia daquele sábado, rogaram a Pilatos que se lhes quebrassem as pernas, e fossem tirados.

[[v43-19-32]]

^<<v43-19-32,32>>^ Os soldados foram e quebraram as pernas ao primeiro e ao outro que com ele tinham sido crucificados;

[[v43-19-33]]

^<<v43-19-33,33>>^ chegando-se, porém, a Jesus, como vissem que já estava morto, não lhe quebraram as pernas.

[[v43-19-34]]

^<<v43-19-34,34>>^ Mas um dos soldados lhe abriu o lado com uma lança, e logo saiu sangue e água.

[[v43-19-35]]

^<<v43-19-35,35>>^ Aquele que isto viu testificou, sendo verdadeiro o seu testemunho; e ele sabe que diz a verdade, para que também vós creiais.

[[v43-19-36]]

^<<v43-19-36,36>>^ E isto aconteceu para se cumprir a Escritura: Nenhum dos seus ossos será quebrado.

[[v43-19-37]]

^<<v43-19-37,37>>^ E outra vez diz a Escritura: Eles verão aquele a quem traspassaram.

[[v43-19-38]]

^<<v43-19-38,38>>^ Depois disto, José de Arimateia, que era discípulo de Jesus, ainda que ocultamente pelo receio que tinha dos judeus, rogou a Pilatos lhe permitisse tirar o corpo de Jesus. Pilatos lho permitiu. Então, foi José de Arimateia e retirou o corpo de Jesus.

[[v43-19-39]]

^<<v43-19-39,39>>^ E também Nicodemos, aquele que anteriormente viera ter com Jesus à noite, foi, levando cerca de cem libras de um composto de mirra e aloés.

[[v43-19-40]]

^<<v43-19-40,40>>^ Tomaram, pois, o corpo de Jesus e o envolveram em lençóis com os aromas, como é de uso entre os judeus na preparação para o sepulcro.

[[v43-19-41]]

^<<v43-19-41,41>>^ No lugar onde Jesus fora crucificado, havia um jardim, e neste, um sepulcro novo, no qual ninguém tinha sido ainda posto.

[[v43-19-42]]

^<<v43-19-42,42>>^ Ali, pois, por causa da preparação dos judeus e por estar perto o túmulo, depositaram o corpo de Jesus.

'''

xref:043-joao/043-joao-018.adoc#v43-18-0[&#60; Capítulo Anterior] | <<v43-19-0,Topo>> | xref:043-joao/043-joao-020.adoc#v43-20-0[Próximo Capítulo &#62;]