include::./index.adoc[]

[[v43-6-0]]
=== João, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-6-1]]

^<<v43-6-1,1>>^ Depois destas coisas, atravessou Jesus o mar da Galileia, que é o de Tiberíades.

[[v43-6-2]]

^<<v43-6-2,2>>^ Seguia-o numerosa multidão, porque tinham visto os sinais que ele fazia na cura dos enfermos.

[[v43-6-3]]

^<<v43-6-3,3>>^ Então, subiu Jesus ao monte e assentou-se ali com os seus discípulos.

[[v43-6-4]]

^<<v43-6-4,4>>^ Ora, a Páscoa, festa dos judeus, estava próxima.

[[v43-6-5]]

^<<v43-6-5,5>>^ Então, Jesus, erguendo os olhos e vendo que grande multidão vinha ter com ele, disse a Filipe: Onde compraremos pães para lhes dar a comer?

[[v43-6-6]]

^<<v43-6-6,6>>^ Mas dizia isto para o experimentar; porque ele bem sabia o que estava para fazer.

[[v43-6-7]]

^<<v43-6-7,7>>^ Respondeu-lhe Filipe: Não lhes bastariam duzentos denários de pão, para receber cada um o seu pedaço.

[[v43-6-8]]

^<<v43-6-8,8>>^ Um de seus discípulos, chamado André, irmão de Simão Pedro, informou a Jesus:

[[v43-6-9]]

^<<v43-6-9,9>>^ Está aí um rapaz que tem cinco pães de cevada e dois peixinhos; mas isto que é para tanta gente?

[[v43-6-10]]

^<<v43-6-10,10>>^ Disse Jesus: Fazei o povo assentar-se;  pois havia naquele lugar muita relva. Assentaram-se, pois, os homens em número de quase cinco mil.

[[v43-6-11]]

^<<v43-6-11,11>>^ Então, Jesus tomou os pães e, tendo dado graças, distribuiu-os entre eles; e também igualmente os peixes, quanto queriam.

[[v43-6-12]]

^<<v43-6-12,12>>^ E, quando já estavam fartos, disse Jesus aos seus discípulos: Recolhei os pedaços que sobraram, para que nada se perca.

[[v43-6-13]]

^<<v43-6-13,13>>^ Assim, pois, o fizeram e encheram doze cestos de pedaços dos cinco pães de cevada, que sobraram aos que haviam comido.

[[v43-6-14]]

^<<v43-6-14,14>>^ Vendo, pois, os homens o sinal que Jesus fizera, disseram: Este é, verdadeiramente, o profeta que devia vir ao mundo.

[[v43-6-15]]

^<<v43-6-15,15>>^ Sabendo, pois, Jesus que estavam para vir com o intuito de arrebatá-lo para o proclamarem rei, retirou-se novamente, sozinho, para o monte.

[[v43-6-16]]

^<<v43-6-16,16>>^ Ao descambar o dia, os seus discípulos desceram para o mar.

[[v43-6-17]]

^<<v43-6-17,17>>^ E, tomando um barco, passaram para o outro lado, rumo a Cafarnaum. Já se fazia escuro, e Jesus ainda não viera ter com eles.

[[v43-6-18]]

^<<v43-6-18,18>>^ E o mar começava a empolar-se, agitado por vento rijo que soprava.

[[v43-6-19]]

^<<v43-6-19,19>>^ Tendo navegado uns vinte e cinco a trinta estádios, eis que viram Jesus andando por sobre o mar, aproximando-se do barco; e ficaram possuídos de temor.

[[v43-6-20]]

^<<v43-6-20,20>>^ Mas Jesus lhes disse: Sou eu. Não temais!

[[v43-6-21]]

^<<v43-6-21,21>>^ Então, eles, de bom grado, o receberam, e logo o barco chegou ao seu destino.

[[v43-6-22]]

^<<v43-6-22,22>>^ No dia seguinte, a multidão que ficara do outro lado do mar notou que ali não havia senão um pequeno barco e que Jesus não embarcara nele com seus discípulos, tendo estes partido sós.

[[v43-6-23]]

^<<v43-6-23,23>>^ Entretanto, outros barquinhos chegaram de Tiberíades, perto do lugar onde comeram o pão, tendo o Senhor dado graças.

[[v43-6-24]]

^<<v43-6-24,24>>^ Quando, pois, viu a multidão que Jesus não estava ali nem os seus discípulos, tomaram os barcos e partiram para Cafarnaum à sua procura.

[[v43-6-25]]

^<<v43-6-25,25>>^ E, tendo-o encontrado no outro lado do mar, lhe perguntaram: Mestre, quando chegaste aqui?

[[v43-6-26]]

^<<v43-6-26,26>>^ Respondeu-lhes Jesus: Em verdade, em verdade vos digo: vós me procurais, não porque vistes sinais, mas porque comestes dos pães e vos fartastes.

[[v43-6-27]]

^<<v43-6-27,27>>^ Trabalhai, não pela comida que perece, mas pela que subsiste para a vida eterna, a qual o Filho do Homem vos dará; porque Deus, o Pai, o confirmou com o seu selo.

[[v43-6-28]]

^<<v43-6-28,28>>^ Dirigiram-se, pois, a ele, perguntando: Que faremos para realizar as obras de Deus?

[[v43-6-29]]

^<<v43-6-29,29>>^ Respondeu-lhes Jesus: A obra de Deus é esta: que creiais naquele que por ele foi enviado.

[[v43-6-30]]

^<<v43-6-30,30>>^ Então, lhe disseram eles: Que sinal fazes para que o vejamos e creiamos em ti? Quais são os teus feitos?

[[v43-6-31]]

^<<v43-6-31,31>>^ Nossos pais comeram o maná no deserto, como está escrito: Deu-lhes a comer pão do céu.

[[v43-6-32]]

^<<v43-6-32,32>>^ Replicou-lhes Jesus: Em verdade, em verdade vos digo: não foi Moisés quem vos deu o pão do céu; o verdadeiro pão do céu é meu Pai quem vos dá.

[[v43-6-33]]

^<<v43-6-33,33>>^ Porque o pão de Deus é o que desce do céu e dá vida ao mundo.

[[v43-6-34]]

^<<v43-6-34,34>>^ Então, lhe disseram: Senhor, dá-nos sempre desse pão.

[[v43-6-35]]

^<<v43-6-35,35>>^ Declarou-lhes, pois, Jesus: Eu sou o pão da vida; o que vem a mim jamais terá fome; e o que crê em mim jamais terá sede.

[[v43-6-36]]

^<<v43-6-36,36>>^ Porém eu já vos disse que, embora me tenhais visto, não credes.

[[v43-6-37]]

^<<v43-6-37,37>>^ Todo aquele que o Pai me dá, esse virá a mim; e o que vem a mim, de modo nenhum o lançarei fora.

[[v43-6-38]]

^<<v43-6-38,38>>^ Porque eu desci do céu, não para fazer a minha própria vontade, e sim a vontade daquele que me enviou.

[[v43-6-39]]

^<<v43-6-39,39>>^ E a vontade de quem me enviou é esta: que nenhum eu perca de todos os que me deu; pelo contrário, eu o ressuscitarei no último dia.

[[v43-6-40]]

^<<v43-6-40,40>>^ De fato, a vontade de meu Pai é que todo homem que vir o Filho e nele crer tenha a vida eterna; e eu o ressuscitarei no último dia.

[[v43-6-41]]

^<<v43-6-41,41>>^ Murmuravam, pois, dele os judeus, porque dissera: Eu sou o pão que desceu do céu.

[[v43-6-42]]

^<<v43-6-42,42>>^ E diziam: Não é este Jesus, o filho de José? Acaso, não lhe conhecemos o pai e a mãe? Como, pois, agora diz: Desci do céu?

[[v43-6-43]]

^<<v43-6-43,43>>^ Respondeu-lhes Jesus: Não murmureis entre vós.

[[v43-6-44]]

^<<v43-6-44,44>>^ Ninguém pode vir a mim se o Pai, que me enviou, não o trouxer; e eu o ressuscitarei no último dia.

[[v43-6-45]]

^<<v43-6-45,45>>^ Está escrito nos profetas: E serão todos ensinados por Deus. Portanto, todo aquele que da parte do Pai tem ouvido e aprendido, esse vem a mim.

[[v43-6-46]]

^<<v43-6-46,46>>^ Não que alguém tenha visto o Pai, salvo aquele que vem de Deus; este o tem visto.

[[v43-6-47]]

^<<v43-6-47,47>>^ Em verdade, em verdade vos digo: quem crê em mim tem a vida eterna.

[[v43-6-48]]

^<<v43-6-48,48>>^ Eu sou o pão da vida.

[[v43-6-49]]

^<<v43-6-49,49>>^ Vossos pais comeram o maná no deserto e morreram.

[[v43-6-50]]

^<<v43-6-50,50>>^ Este é o pão que desce do céu, para que todo o que dele comer não pereça.

[[v43-6-51]]

^<<v43-6-51,51>>^ Eu sou o pão vivo que desceu do céu; se alguém dele comer, viverá eternamente; e o pão que eu darei pela vida do mundo é a minha carne.

[[v43-6-52]]

^<<v43-6-52,52>>^ Disputavam, pois, os judeus entre si, dizendo: Como pode este dar-nos a comer a sua própria carne?

[[v43-6-53]]

^<<v43-6-53,53>>^ Respondeu-lhes Jesus: Em verdade, em verdade vos digo: se não comerdes a carne do Filho do Homem e não beberdes o seu sangue, não tendes vida em vós mesmos.

[[v43-6-54]]

^<<v43-6-54,54>>^ Quem comer a minha carne e beber o meu sangue tem a vida eterna, e eu o ressuscitarei no último dia.

[[v43-6-55]]

^<<v43-6-55,55>>^ Pois a minha carne é verdadeira comida, e o meu sangue é verdadeira bebida.

[[v43-6-56]]

^<<v43-6-56,56>>^ Quem comer a minha carne e beber o meu sangue permanece em mim, e eu, nele.

[[v43-6-57]]

^<<v43-6-57,57>>^ Assim como o Pai, que vive, me enviou, e igualmente eu vivo pelo Pai, também quem de mim se alimenta por mim viverá.

[[v43-6-58]]

^<<v43-6-58,58>>^ Este é o pão que desceu do céu, em nada semelhante àquele que os vossos pais comeram e, contudo, morreram; quem comer este pão viverá eternamente.

[[v43-6-59]]

^<<v43-6-59,59>>^ Estas coisas disse Jesus, quando ensinava na sinagoga de Cafarnaum.

[[v43-6-60]]

^<<v43-6-60,60>>^ Muitos dos seus discípulos, tendo ouvido tais palavras, disseram: Duro é este discurso; quem o pode ouvir?

[[v43-6-61]]

^<<v43-6-61,61>>^ Mas Jesus, sabendo por si mesmo que eles murmuravam a respeito de suas palavras, interpelou-os: Isto vos escandaliza?

[[v43-6-62]]

^<<v43-6-62,62>>^ Que será, pois, se virdes o Filho do Homem subir para o lugar onde primeiro estava?

[[v43-6-63]]

^<<v43-6-63,63>>^ O espírito é o que vivifica; a carne para nada aproveita; as palavras que eu vos tenho dito são espírito e são vida.

[[v43-6-64]]

^<<v43-6-64,64>>^ Contudo, há descrentes entre vós.  Pois Jesus sabia, desde o princípio, quais eram os que não criam e quem o havia de trair.

[[v43-6-65]]

^<<v43-6-65,65>>^ E prosseguiu: Por causa disto, é que vos tenho dito: ninguém poderá vir a mim, se, pelo Pai, não lhe for concedido.

[[v43-6-66]]

^<<v43-6-66,66>>^ À vista disso, muitos dos seus discípulos o abandonaram e já não andavam com ele.

[[v43-6-67]]

^<<v43-6-67,67>>^ Então, perguntou Jesus aos doze: Porventura, quereis também vós outros retirar-vos?

[[v43-6-68]]

^<<v43-6-68,68>>^ Respondeu-lhe Simão Pedro: Senhor, para quem iremos? Tu tens as palavras da vida eterna;

[[v43-6-69]]

^<<v43-6-69,69>>^ e nós temos crido e conhecido que tu és o Santo de Deus.

[[v43-6-70]]

^<<v43-6-70,70>>^ Replicou-lhes Jesus: Não vos escolhi eu em número de doze? Contudo, um de vós é diabo.

[[v43-6-71]]

^<<v43-6-71,71>>^ Referia-se ele a Judas, filho de Simão Iscariotes; porque era quem estava para traí-lo, sendo um dos doze.

'''

xref:043-joao/043-joao-005.adoc#v43-5-0[&#60; Capítulo Anterior] | <<v43-6-0,Topo>> | xref:043-joao/043-joao-007.adoc#v43-7-0[Próximo Capítulo &#62;]