include::./index.adoc[]

[[v43-2-0]]
=== João, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-2-1]]

^<<v43-2-1,1>>^ Três dias depois, houve um casamento em Caná da Galileia, achando-se ali a mãe de Jesus.

[[v43-2-2]]

^<<v43-2-2,2>>^ Jesus também foi convidado, com os seus discípulos, para o casamento.

[[v43-2-3]]

^<<v43-2-3,3>>^ Tendo acabado o vinho, a mãe de Jesus lhe disse: Eles não têm mais vinho.

[[v43-2-4]]

^<<v43-2-4,4>>^ Mas Jesus lhe disse: Mulher, que tenho eu contigo? Ainda não é chegada a minha hora.

[[v43-2-5]]

^<<v43-2-5,5>>^ Então, ela falou aos serventes: Fazei tudo o que ele vos disser.

[[v43-2-6]]

^<<v43-2-6,6>>^ Estavam ali seis talhas de pedra, que os judeus usavam para as purificações, e cada uma levava duas ou três metretas.

[[v43-2-7]]

^<<v43-2-7,7>>^ Jesus lhes disse: Enchei de água as talhas.  E eles as encheram totalmente.

[[v43-2-8]]

^<<v43-2-8,8>>^ Então, lhes determinou: Tirai agora e levai ao mestre-sala.  Eles o fizeram.

[[v43-2-9]]

^<<v43-2-9,9>>^ Tendo o mestre-sala provado a água transformada em vinho (não sabendo donde viera, se bem que o sabiam os serventes que haviam tirado a água), chamou o noivo

[[v43-2-10]]

^<<v43-2-10,10>>^ e lhe disse: Todos costumam pôr primeiro o bom vinho e, quando já beberam fartamente, servem o inferior; tu, porém, guardaste o bom vinho até agora.

[[v43-2-11]]

^<<v43-2-11,11>>^ Com este, deu Jesus princípio a seus sinais em Caná da Galileia; manifestou a sua glória, e os seus discípulos creram nele.

[[v43-2-12]]

^<<v43-2-12,12>>^ Depois disto, desceu ele para Cafarnaum, com sua mãe, seus irmãos e seus discípulos; e ficaram ali não muitos dias.

[[v43-2-13]]

^<<v43-2-13,13>>^ Estando próxima a Páscoa dos judeus, subiu Jesus para Jerusalém.

[[v43-2-14]]

^<<v43-2-14,14>>^ E encontrou no templo os que vendiam bois, ovelhas e pombas e também os cambistas assentados;

[[v43-2-15]]

^<<v43-2-15,15>>^ tendo feito um azorrague de cordas, expulsou todos do templo, bem como as ovelhas e os bois, derramou pelo chão o dinheiro dos cambistas, virou as mesas

[[v43-2-16]]

^<<v43-2-16,16>>^ e disse aos que vendiam as pombas: Tirai daqui estas coisas; não façais da casa de meu Pai casa de negócio.

[[v43-2-17]]

^<<v43-2-17,17>>^ Lembraram-se os seus discípulos de que está escrito: O zelo da tua casa me consumirá.

[[v43-2-18]]

^<<v43-2-18,18>>^ Perguntaram-lhe, pois, os judeus: Que sinal nos mostras, para fazeres estas coisas?

[[v43-2-19]]

^<<v43-2-19,19>>^ Jesus lhes respondeu: Destruí este santuário, e em três dias o reconstruirei.

[[v43-2-20]]

^<<v43-2-20,20>>^ Replicaram os judeus: Em quarenta e seis anos foi edificado este santuário, e tu, em três dias, o levantarás?

[[v43-2-21]]

^<<v43-2-21,21>>^ Ele, porém, se referia ao santuário do seu corpo.

[[v43-2-22]]

^<<v43-2-22,22>>^ Quando, pois, Jesus ressuscitou dentre os mortos, lembraram-se os seus discípulos de que ele dissera isto; e creram na Escritura e na palavra de Jesus.

[[v43-2-23]]

^<<v43-2-23,23>>^ Estando ele em Jerusalém, durante a Festa da Páscoa, muitos, vendo os sinais que ele fazia, creram no seu nome;

[[v43-2-24]]

^<<v43-2-24,24>>^ mas o próprio Jesus não se confiava a eles, porque os conhecia a todos.

[[v43-2-25]]

^<<v43-2-25,25>>^ E não precisava de que alguém lhe desse testemunho a respeito do homem, porque ele mesmo sabia o que era a natureza humana.

'''

xref:043-joao/043-joao-001.adoc#v43-1-0[&#60; Capítulo Anterior] | <<v43-2-0,Topo>> | xref:043-joao/043-joao-003.adoc#v43-3-0[Próximo Capítulo &#62;]