include::./index.adoc[]

[[v43-11-0]]
=== João, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v43-11-1]]

^<<v43-11-1,1>>^ Estava enfermo Lázaro, de Betânia, da aldeia de Maria e de sua irmã Marta.

[[v43-11-2]]

^<<v43-11-2,2>>^ Esta Maria, cujo irmão Lázaro estava enfermo, era a mesma que ungiu com bálsamo o Senhor e lhe enxugou os pés com os seus cabelos.

[[v43-11-3]]

^<<v43-11-3,3>>^ Mandaram, pois, as irmãs de Lázaro dizer a Jesus: Senhor, está enfermo aquele a quem amas.

[[v43-11-4]]

^<<v43-11-4,4>>^ Ao receber a notícia, disse Jesus: Esta enfermidade não é para morte, e sim para a glória de Deus, a fim de que o Filho de Deus seja por ela glorificado.

[[v43-11-5]]

^<<v43-11-5,5>>^ Ora, amava Jesus a Marta, e a sua irmã, e a Lázaro.

[[v43-11-6]]

^<<v43-11-6,6>>^ Quando, pois, soube que Lázaro estava doente, ainda se demorou dois dias no lugar onde estava.

[[v43-11-7]]

^<<v43-11-7,7>>^ Depois, disse aos seus discípulos: Vamos outra vez para a Judeia.

[[v43-11-8]]

^<<v43-11-8,8>>^ Disseram-lhe os discípulos: Mestre, ainda agora os judeus procuravam apedrejar-te, e voltas para lá?

[[v43-11-9]]

^<<v43-11-9,9>>^ Respondeu Jesus: Não são doze as horas do dia? Se alguém andar de dia, não tropeça, porque vê a luz deste mundo;

[[v43-11-10]]

^<<v43-11-10,10>>^ mas, se andar de noite, tropeça, porque nele não há luz.

[[v43-11-11]]

^<<v43-11-11,11>>^ Isto dizia e depois lhes acrescentou: Nosso amigo Lázaro adormeceu, mas vou para despertá-lo.

[[v43-11-12]]

^<<v43-11-12,12>>^ Disseram-lhe, pois, os discípulos: Senhor, se dorme, estará salvo.

[[v43-11-13]]

^<<v43-11-13,13>>^ Jesus, porém, falara com respeito à morte de Lázaro; mas eles supunham que tivesse falado do repouso do sono.

[[v43-11-14]]

^<<v43-11-14,14>>^ Então, Jesus lhes disse claramente: Lázaro morreu;

[[v43-11-15]]

^<<v43-11-15,15>>^ e por vossa causa me alegro de que lá não estivesse, para que possais crer; mas vamos ter com ele.

[[v43-11-16]]

^<<v43-11-16,16>>^ Então, Tomé, chamado Dídimo, disse aos condiscípulos: Vamos também nós para morrermos com ele.

[[v43-11-17]]

^<<v43-11-17,17>>^ Chegando Jesus, encontrou Lázaro já sepultado, havia quatro dias.

[[v43-11-18]]

^<<v43-11-18,18>>^ Ora, Betânia estava cerca de quinze estádios perto de Jerusalém.

[[v43-11-19]]

^<<v43-11-19,19>>^ Muitos dentre os judeus tinham vindo ter com Marta e Maria, para as consolar a respeito de seu irmão.

[[v43-11-20]]

^<<v43-11-20,20>>^ Marta, quando soube que vinha Jesus, saiu ao seu encontro; Maria, porém, ficou sentada em casa.

[[v43-11-21]]

^<<v43-11-21,21>>^ Disse, pois, Marta a Jesus: Senhor, se estiveras aqui, não teria morrido meu irmão.

[[v43-11-22]]

^<<v43-11-22,22>>^ Mas também sei que, mesmo agora, tudo quanto pedires a Deus, Deus to concederá.

[[v43-11-23]]

^<<v43-11-23,23>>^ Declarou-lhe Jesus: Teu irmão há de ressurgir.

[[v43-11-24]]

^<<v43-11-24,24>>^ Eu sei, replicou Marta, que ele há de ressurgir na ressurreição, no último dia.

[[v43-11-25]]

^<<v43-11-25,25>>^ Disse-lhe Jesus: Eu sou a ressurreição e a vida. Quem crê em mim, ainda que morra, viverá;

[[v43-11-26]]

^<<v43-11-26,26>>^ e todo o que vive e crê em mim não morrerá, eternamente. Crês isto?

[[v43-11-27]]

^<<v43-11-27,27>>^ Sim, Senhor, respondeu ela, eu tenho crido que tu és o Cristo, o Filho de Deus que devia vir ao mundo.

[[v43-11-28]]

^<<v43-11-28,28>>^ Tendo dito isto, retirou-se e chamou Maria, sua irmã, e lhe disse em particular: O Mestre chegou e te chama.

[[v43-11-29]]

^<<v43-11-29,29>>^ Ela, ouvindo isto, levantou-se depressa e foi ter com ele,

[[v43-11-30]]

^<<v43-11-30,30>>^ pois Jesus ainda não tinha entrado na aldeia, mas permanecia onde Marta se avistara com ele.

[[v43-11-31]]

^<<v43-11-31,31>>^ Os judeus que estavam com Maria em casa e a consolavam, vendo-a levantar-se depressa e sair, seguiram-na, supondo que ela ia ao túmulo para chorar.

[[v43-11-32]]

^<<v43-11-32,32>>^ Quando Maria chegou ao lugar onde estava Jesus, ao vê-lo, lançou-se-lhe aos pés, dizendo: Senhor, se estiveras aqui, meu irmão não teria morrido.

[[v43-11-33]]

^<<v43-11-33,33>>^ Jesus, vendo-a chorar, e bem assim os judeus que a acompanhavam, agitou-se no espírito e comoveu-se.

[[v43-11-34]]

^<<v43-11-34,34>>^ E perguntou: Onde o sepultastes?  Eles lhe responderam: Senhor, vem e vê!

[[v43-11-35]]

^<<v43-11-35,35>>^ Jesus chorou.

[[v43-11-36]]

^<<v43-11-36,36>>^ Então, disseram os judeus: Vede quanto o amava.

[[v43-11-37]]

^<<v43-11-37,37>>^ Mas alguns objetaram: Não podia ele, que abriu os olhos ao cego, fazer que este não morresse?

[[v43-11-38]]

^<<v43-11-38,38>>^ Jesus, agitando-se novamente em si mesmo, encaminhou-se para o túmulo; era este uma gruta a cuja entrada tinham posto uma pedra.

[[v43-11-39]]

^<<v43-11-39,39>>^ Então, ordenou Jesus: Tirai a pedra.  Disse-lhe Marta, irmã do morto: Senhor, já cheira mal, porque já é de quatro dias.

[[v43-11-40]]

^<<v43-11-40,40>>^ Respondeu-lhe Jesus: Não te disse eu que, se creres, verás a glória de Deus?

[[v43-11-41]]

^<<v43-11-41,41>>^ Tiraram, então, a pedra. E Jesus, levantando os olhos para o céu, disse: Pai, graças te dou porque me ouviste.

[[v43-11-42]]

^<<v43-11-42,42>>^ Aliás, eu sabia que sempre me ouves, mas assim falei por causa da multidão presente, para que creiam que tu me enviaste.

[[v43-11-43]]

^<<v43-11-43,43>>^ E, tendo dito isto, clamou em alta voz: Lázaro, vem para fora!

[[v43-11-44]]

^<<v43-11-44,44>>^ Saiu aquele que estivera morto, tendo os pés e as mãos ligados com ataduras e o rosto envolto num lenço. Então, lhes ordenou Jesus: Desatai-o e deixai-o ir.

[[v43-11-45]]

^<<v43-11-45,45>>^ Muitos, pois, dentre os judeus que tinham vindo visitar Maria, vendo o que fizera Jesus, creram nele.

[[v43-11-46]]

^<<v43-11-46,46>>^ Outros, porém, foram ter com os fariseus e lhes contaram dos feitos que Jesus realizara.

[[v43-11-47]]

^<<v43-11-47,47>>^ Então, os principais sacerdotes e os fariseus convocaram o Sinédrio; e disseram: Que estamos fazendo, uma vez que este homem opera muitos sinais?

[[v43-11-48]]

^<<v43-11-48,48>>^ Se o deixarmos assim, todos crerão nele; depois, virão os romanos e tomarão não só o nosso lugar, mas a própria nação.

[[v43-11-49]]

^<<v43-11-49,49>>^ Caifás, porém, um dentre eles, sumo sacerdote naquele ano, advertiu-os, dizendo: Vós nada sabeis,

[[v43-11-50]]

^<<v43-11-50,50>>^ nem considerais que vos convém que morra um só homem pelo povo e que não venha a perecer toda a nação.

[[v43-11-51]]

^<<v43-11-51,51>>^ Ora, ele não disse isto de si mesmo; mas, sendo sumo sacerdote naquele ano, profetizou que Jesus estava para morrer pela nação

[[v43-11-52]]

^<<v43-11-52,52>>^ e não somente pela nação, mas também para reunir em um só corpo os filhos de Deus, que andam dispersos.

[[v43-11-53]]

^<<v43-11-53,53>>^ Desde aquele dia, resolveram matá-lo.

[[v43-11-54]]

^<<v43-11-54,54>>^ De sorte que Jesus já não andava publicamente entre os judeus, mas retirou-se para uma região vizinha ao deserto, para uma cidade chamada Efraim; e ali permaneceu com os discípulos.

[[v43-11-55]]

^<<v43-11-55,55>>^ Estava próxima a Páscoa dos judeus; e muitos daquela região subiram para Jerusalém antes da Páscoa, para se purificarem.

[[v43-11-56]]

^<<v43-11-56,56>>^ Lá, procuravam Jesus e, estando eles no templo, diziam uns aos outros: Que vos parece? Não virá ele à festa?

[[v43-11-57]]

^<<v43-11-57,57>>^ Ora, os principais sacerdotes e os fariseus tinham dado ordem para, se alguém soubesse onde ele estava, denunciá-lo, a fim de o prenderem.

'''

xref:043-joao/043-joao-010.adoc#v43-10-0[&#60; Capítulo Anterior] | <<v43-11-0,Topo>> | xref:043-joao/043-joao-012.adoc#v43-12-0[Próximo Capítulo &#62;]