include::./index.adoc[]

[[v36-1-0]]
=== Sofonias, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v36-1-1]]

^<<v36-1-1,1>>^ Palavra do SENHOR que veio a Sofonias, filho de Cusi, filho de Gedalias, filho de Amarias, filho de Ezequias, nos dias de Josias, filho de Amom, rei de Judá.

[[v36-1-2]]

^<<v36-1-2,2>>^ De fato, consumirei todas as coisas sobre a face da terra, diz o SENHOR.

[[v36-1-3]]

^<<v36-1-3,3>>^ Consumirei os homens e os animais, consumirei as aves do céu, e os peixes do mar, e as ofensas com os perversos; e exterminarei os homens de sobre a face da terra, diz o SENHOR.

[[v36-1-4]]

^<<v36-1-4,4>>^ Estenderei a mão contra Judá e contra todos os habitantes de Jerusalém; exterminarei deste lugar o resto de Baal, o nome dos ministrantes dos ídolos e seus sacerdotes;

[[v36-1-5]]

^<<v36-1-5,5>>^ os que sobre os eirados adoram o exército do céu e os que adoram ao SENHOR e juram por ele e também por Milcom;

[[v36-1-6]]

^<<v36-1-6,6>>^ os que deixam de seguir ao SENHOR e os que não buscam o SENHOR, nem perguntam por ele.

[[v36-1-7]]

^<<v36-1-7,7>>^ Cala-te diante do SENHOR Deus, porque o Dia do SENHOR está perto, pois o SENHOR preparou o sacrifício e santificou os seus convidados.

[[v36-1-8]]

^<<v36-1-8,8>>^ No dia do sacrifício do SENHOR, hei de castigar os oficiais, e os filhos do rei, e todos os que trajam vestiduras estrangeiras.

[[v36-1-9]]

^<<v36-1-9,9>>^ Castigarei também, naquele dia, todos aqueles que sobem o pedestal dos ídolos e enchem de violência e engano a casa dos seus senhores.

[[v36-1-10]]

^<<v36-1-10,10>>^ Naquele dia, diz o SENHOR, far-se-á ouvir um grito desde a Porta do Peixe, e um uivo desde a Cidade Baixa, e grande lamento desde os outeiros.

[[v36-1-11]]

^<<v36-1-11,11>>^ Uivai vós, moradores de Mactés, porque todo o povo de Canaã está arruinado, todos os que pesam prata são destruídos.

[[v36-1-12]]

^<<v36-1-12,12>>^ Naquele tempo, esquadrinharei a Jerusalém com lanternas e castigarei os homens que estão apegados à borra do vinho e dizem no seu coração: O SENHOR não faz bem, nem faz mal.

[[v36-1-13]]

^<<v36-1-13,13>>^ Por isso, serão saqueados os seus bens e assoladas as suas casas; e edificarão casas, mas não habitarão nelas, plantarão vinhas, porém não lhes beberão o vinho.

[[v36-1-14]]

^<<v36-1-14,14>>^ Está perto o grande Dia do SENHOR; está perto e muito se apressa. Atenção! O Dia do SENHOR é amargo, e nele clama até o homem poderoso.

[[v36-1-15]]

^<<v36-1-15,15>>^ Aquele dia é dia de indignação, dia de angústia e dia de alvoroço e desolação, dia de escuridade e negrume, dia de nuvens e densas trevas,

[[v36-1-16]]

^<<v36-1-16,16>>^ dia de trombeta e de rebate contra as cidades fortes e contra as torres altas.

[[v36-1-17]]

^<<v36-1-17,17>>^ Trarei angústia sobre os homens, e eles andarão como cegos, porque pecaram contra o SENHOR; e o sangue deles se derramará como pó, e a sua carne será atirada como esterco.

[[v36-1-18]]

^<<v36-1-18,18>>^ Nem a sua prata nem o seu ouro os poderão livrar no dia da indignação do SENHOR, mas, pelo fogo do seu zelo, a terra será consumida, porque, certamente, fará destruição total e repentina de todos os moradores da terra.

'''

xref:035-habacuque/035-habacuque-003.adoc#v35-3-0[&#60; Capítulo Anterior] | <<v36-1-0,Topo>> | xref:036-sofonias/036-sofonias-002.adoc#v36-2-0[Próximo Capítulo &#62;]