include::./index.adoc[]

[[v36-2-0]]
=== Sofonias, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v36-2-1]]

^<<v36-2-1,1>>^ Concentra-te e examina-te, ó nação que não tens pudor,

[[v36-2-2]]

^<<v36-2-2,2>>^ antes que saia o decreto, pois o dia se vai como a palha; antes que venha sobre ti o furor da ira do SENHOR, sim, antes que venha sobre ti o dia da ira do SENHOR.

[[v36-2-3]]

^<<v36-2-3,3>>^ Buscai o SENHOR, vós todos os mansos da terra, que cumpris o seu juízo; buscai a justiça, buscai a mansidão; porventura, lograreis esconder-vos no dia da ira do SENHOR.

[[v36-2-4]]

^<<v36-2-4,4>>^ Porque Gaza será desamparada, e Asquelom ficará deserta; Asdode, ao meio-dia, será expulsa, e Ecrom, desarraigada.

[[v36-2-5]]

^<<v36-2-5,5>>^ Ai dos que habitam no litoral, do povo dos quereítas! A palavra do SENHOR será contra vós outros, ó Canaã, terra dos filisteus, e eu vos farei destruir, até que não haja um morador sequer.

[[v36-2-6]]

^<<v36-2-6,6>>^ O litoral será de pastagens, com refúgios para os pastores e currais para os rebanhos.

[[v36-2-7]]

^<<v36-2-7,7>>^ O litoral pertencerá aos restantes da casa de Judá; nele, apascentarão os seus rebanhos e, à tarde, se deitarão nas casas de Asquelom; porque o SENHOR, seu Deus, atentará para eles e lhes mudará a sorte.

[[v36-2-8]]

^<<v36-2-8,8>>^ Ouvi o escárnio de Moabe e as injuriosas palavras dos filhos de Amom, com que escarneceram do meu povo e se gabaram contra o seu território.

[[v36-2-9]]

^<<v36-2-9,9>>^ Portanto, tão certo como eu vivo, diz o SENHOR dos Exércitos, o Deus de Israel, Moabe será como Sodoma, e os filhos de Amom, como Gomorra, campo de urtigas, poços de sal e assolação perpétua; o restante do meu povo os saqueará, e os sobreviventes da minha nação os possuirão.

[[v36-2-10]]

^<<v36-2-10,10>>^ Isso lhes sobrevirá por causa da sua soberba, porque escarneceram e se gabaram contra o povo do SENHOR dos Exércitos.

[[v36-2-11]]

^<<v36-2-11,11>>^ O SENHOR será terrível contra eles, porque aniquilará todos os deuses da terra; todas as ilhas das nações, cada uma do seu lugar, o adorarão.

[[v36-2-12]]

^<<v36-2-12,12>>^ Também vós, ó etíopes, sereis mortos pela espada do SENHOR.

[[v36-2-13]]

^<<v36-2-13,13>>^ Ele estenderá também a mão contra o Norte e destruirá a Assíria; e fará de Nínive uma desolação e terra seca como o deserto.

[[v36-2-14]]

^<<v36-2-14,14>>^ No meio desta cidade, repousarão os rebanhos e todos os animais em bandos; alojar-se-ão nos seus capitéis tanto o pelicano como o ouriço; a voz das aves retinirá nas janelas, o monturo estará nos limiares, porque já lhe arrancaram o madeiramento de cedro.

[[v36-2-15]]

^<<v36-2-15,15>>^ Esta é a cidade alegre e confiante, que dizia consigo mesma: Eu sou a única, e não há outra além de mim. Como se tornou em desolação, em pousada de animais! Qualquer que passar por ela assobiará com desprezo e agitará a mão.

'''

xref:036-sofonias/036-sofonias-001.adoc#v36-1-0[&#60; Capítulo Anterior] | <<v36-2-0,Topo>> | xref:036-sofonias/036-sofonias-003.adoc#v36-3-0[Próximo Capítulo &#62;]