include::./index.adoc[]

[[v32-1-0]]
=== Jonas, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v32-1-1]]

^<<v32-1-1,1>>^ Veio a palavra do SENHOR a Jonas, filho de Amitai, dizendo:

[[v32-1-2]]

^<<v32-1-2,2>>^ Dispõe-te, vai à grande cidade de Nínive e clama contra ela, porque a sua malícia subiu até mim.

[[v32-1-3]]

^<<v32-1-3,3>>^ Jonas se dispôs, mas para fugir da presença do SENHOR, para Társis; e, tendo descido a Jope, achou um navio que ia para Társis; pagou, pois, a sua passagem e embarcou nele, para ir com eles para Társis, para longe da presença do SENHOR.

[[v32-1-4]]

^<<v32-1-4,4>>^ Mas o SENHOR lançou sobre o mar um forte vento, e fez-se no mar uma grande tempestade, e o navio estava a ponto de se despedaçar.

[[v32-1-5]]

^<<v32-1-5,5>>^ Então, os marinheiros, cheios de medo, clamavam cada um ao seu deus e lançavam ao mar a carga que estava no navio, para o aliviarem do peso dela. Jonas, porém, havia descido ao porão e se deitado; e dormia profundamente.

[[v32-1-6]]

^<<v32-1-6,6>>^ Chegou-se a ele o mestre do navio e lhe disse: Que se passa contigo? Agarrado no sono? Levanta-te, invoca o teu deus; talvez, assim, esse deus se lembre de nós, para que não pereçamos.

[[v32-1-7]]

^<<v32-1-7,7>>^ E diziam uns aos outros: Vinde, e lancemos sortes, para que saibamos por causa de quem nos sobreveio este mal. E lançaram sortes, e a sorte caiu sobre Jonas.

[[v32-1-8]]

^<<v32-1-8,8>>^ Então, lhe disseram: Declara-nos, agora, por causa de quem nos sobreveio este mal. Que ocupação é a tua? Donde vens? Qual a tua terra? E de que povo és tu?

[[v32-1-9]]

^<<v32-1-9,9>>^ Ele lhes respondeu: Sou hebreu e temo ao SENHOR, o Deus do céu, que fez o mar e a terra.

[[v32-1-10]]

^<<v32-1-10,10>>^ Então, os homens ficaram possuídos de grande temor e lhe disseram: Que é isto que fizeste! Pois sabiam os homens que ele fugia da presença do SENHOR, porque lho havia declarado.

[[v32-1-11]]

^<<v32-1-11,11>>^ Disseram-lhe: Que te faremos, para que o mar se nos acalme? Porque o mar se ia tornando cada vez mais tempestuoso.

[[v32-1-12]]

^<<v32-1-12,12>>^ Respondeu-lhes: Tomai-me e lançai-me ao mar, e o mar se aquietará, porque eu sei que, por minha causa, vos sobreveio esta grande tempestade.

[[v32-1-13]]

^<<v32-1-13,13>>^ Entretanto, os homens remavam, esforçando-se por alcançar a terra, mas não podiam, porquanto o mar se ia tornando cada vez mais tempestuoso contra eles.

[[v32-1-14]]

^<<v32-1-14,14>>^ Então, clamaram ao SENHOR e disseram: Ah! SENHOR! Rogamos-te que não pereçamos por causa da vida deste homem, e não faças cair sobre nós este sangue, quanto a nós, inocente; porque tu, SENHOR, fizeste como te aprouve.

[[v32-1-15]]

^<<v32-1-15,15>>^ E levantaram a Jonas e o lançaram ao mar; e cessou o mar da sua fúria.

[[v32-1-16]]

^<<v32-1-16,16>>^ Temeram, pois, estes homens em extremo ao SENHOR; e ofereceram sacrifícios ao SENHOR e fizeram votos.

[[v32-1-17]]

^<<v32-1-17,17>>^ Deparou o SENHOR um grande peixe, para que tragasse a Jonas; e esteve Jonas três dias e três noites no ventre do peixe.

'''

xref:031-obadias/031-obadias-001.adoc#v31-1-0[&#60; Capítulo Anterior] | <<v32-1-0,Topo>> | xref:032-jonas/032-jonas-002.adoc#v32-2-0[Próximo Capítulo &#62;]