include::./index.adoc[]

[[v32-3-0]]
=== Jonas, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v32-3-1]]

^<<v32-3-1,1>>^ Veio a palavra do SENHOR, segunda vez, a Jonas, dizendo:

[[v32-3-2]]

^<<v32-3-2,2>>^ Dispõe-te, vai à grande cidade de Nínive e proclama contra ela a mensagem que eu te digo.

[[v32-3-3]]

^<<v32-3-3,3>>^ Levantou-se, pois, Jonas e foi a Nínive, segundo a palavra do SENHOR. Ora, Nínive era cidade mui importante diante de Deus e de três dias para percorrê-la.

[[v32-3-4]]

^<<v32-3-4,4>>^ Começou Jonas a percorrer a cidade caminho de um dia, e pregava, e dizia: Ainda quarenta dias, e Nínive será subvertida.

[[v32-3-5]]

^<<v32-3-5,5>>^ Os ninivitas creram em Deus, e proclamaram um jejum, e vestiram-se de panos de saco, desde o maior até o menor.

[[v32-3-6]]

^<<v32-3-6,6>>^ Chegou esta notícia ao rei de Nínive; ele levantou-se do seu trono, tirou de si as vestes reais, cobriu-se de pano de saco e assentou-se sobre cinza.

[[v32-3-7]]

^<<v32-3-7,7>>^ E fez-se proclamar e divulgar em Nínive: Por mandado do rei e seus grandes, nem homens, nem animais, nem bois, nem ovelhas provem coisa alguma, nem os levem ao pasto, nem bebam água;

[[v32-3-8]]

^<<v32-3-8,8>>^ mas sejam cobertos de pano de saco, tanto os homens como os animais, e clamarão fortemente a Deus; e se converterão, cada um do seu mau caminho e da violência que há nas suas mãos.

[[v32-3-9]]

^<<v32-3-9,9>>^ Quem sabe se voltará Deus, e se arrependerá, e se apartará do furor da sua ira, de sorte que não pereçamos?

[[v32-3-10]]

^<<v32-3-10,10>>^ Viu Deus o que fizeram, como se converteram do seu mau caminho; e Deus se arrependeu do mal que tinha dito lhes faria e não o fez.

'''

xref:032-jonas/032-jonas-002.adoc#v32-2-0[&#60; Capítulo Anterior] | <<v32-3-0,Topo>> | xref:032-jonas/032-jonas-004.adoc#v32-4-0[Próximo Capítulo &#62;]