include::./index.adoc[]

[[v47-1-0]]
=== 2 Coríntios, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v47-1-1]]

^<<v47-1-1,1>>^ Paulo, apóstolo de Cristo Jesus pela vontade de Deus, e o irmão Timóteo, à igreja de Deus que está em Corinto e a todos os santos em toda a Acaia,

[[v47-1-2]]

^<<v47-1-2,2>>^ graça a vós outros e paz, da parte de Deus, nosso Pai, e do Senhor Jesus Cristo.

[[v47-1-3]]

^<<v47-1-3,3>>^ Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o Pai de misericórdias e Deus de toda consolação!

[[v47-1-4]]

^<<v47-1-4,4>>^ É ele que nos conforta em toda a nossa tribulação, para podermos consolar os que estiverem em qualquer angústia, com a consolação com que nós mesmos somos contemplados por Deus.

[[v47-1-5]]

^<<v47-1-5,5>>^ Porque, assim como os sofrimentos de Cristo se manifestam em grande medida a nosso favor, assim também a nossa consolação transborda por meio de Cristo.

[[v47-1-6]]

^<<v47-1-6,6>>^ Mas, se somos atribulados, é para o vosso conforto e salvação; se somos confortados, é também para o vosso conforto, o qual se torna eficaz, suportando vós com paciência os mesmos sofrimentos que nós também padecemos.

[[v47-1-7]]

^<<v47-1-7,7>>^ A nossa esperança a respeito de vós está firme, sabendo que, como sois participantes dos sofrimentos, assim o sereis da consolação.

[[v47-1-8]]

^<<v47-1-8,8>>^ Porque não queremos, irmãos, que ignoreis a natureza da tribulação que nos sobreveio na Ásia, porquanto foi acima das nossas forças, a ponto de desesperarmos até da própria vida.

[[v47-1-9]]

^<<v47-1-9,9>>^ Contudo, já em nós mesmos, tivemos a sentença de morte, para que não confiemos em nós, e sim no Deus que ressuscita os mortos;

[[v47-1-10]]

^<<v47-1-10,10>>^ o qual nos livrou e livrará de tão grande morte; em quem temos esperado que ainda continuará a livrar-nos,

[[v47-1-11]]

^<<v47-1-11,11>>^ ajudando-nos também vós, com as vossas orações a nosso favor, para que, por muitos, sejam dadas graças a nosso respeito, pelo benefício que nos foi concedido por meio de muitos.

[[v47-1-12]]

^<<v47-1-12,12>>^ Porque a nossa glória é esta: o testemunho da nossa consciência, de que, com santidade e sinceridade de Deus, não com sabedoria humana, mas, na graça divina, temos vivido no mundo e mais especialmente para convosco.

[[v47-1-13]]

^<<v47-1-13,13>>^ Porque nenhuma outra coisa vos escrevemos, além das que ledes e bem compreendeis; e espero que o compreendereis de todo,

[[v47-1-14]]

^<<v47-1-14,14>>^ como também já em parte nos compreendestes, que somos a vossa glória, como igualmente sois a nossa no Dia de Jesus, nosso Senhor.

[[v47-1-15]]

^<<v47-1-15,15>>^ Com esta confiança, resolvi ir, primeiro, encontrar-me convosco, para que tivésseis um segundo benefício;

[[v47-1-16]]

^<<v47-1-16,16>>^ e, por vosso intermédio, passar à Macedônia, e da Macedônia voltar a encontrar-me convosco, e ser encaminhado por vós para a Judeia.

[[v47-1-17]]

^<<v47-1-17,17>>^ Ora, determinando isto, terei, porventura, agido com leviandade? Ou, ao deliberar, acaso delibero segundo a carne, de sorte que haja em mim, simultaneamente, o sim e o não?

[[v47-1-18]]

^<<v47-1-18,18>>^ Antes, como Deus é fiel, a nossa palavra para convosco não é sim e não.

[[v47-1-19]]

^<<v47-1-19,19>>^ Porque o Filho de Deus, Cristo Jesus, que foi, por nosso intermédio, anunciado entre vós, isto é, por mim, e Silvano, e Timóteo, não foi sim e não; mas sempre nele houve o sim.

[[v47-1-20]]

^<<v47-1-20,20>>^ Porque quantas são as promessas de Deus, tantas têm nele o sim; porquanto também por ele é o amém para glória de Deus, por nosso intermédio.

[[v47-1-21]]

^<<v47-1-21,21>>^ Mas aquele que nos confirma convosco em Cristo e nos ungiu é Deus,

[[v47-1-22]]

^<<v47-1-22,22>>^ que também nos selou e nos deu o penhor do Espírito em nosso coração.

[[v47-1-23]]

^<<v47-1-23,23>>^ Eu, porém, por minha vida, tomo a Deus por testemunha de que, para vos poupar, não tornei ainda a Corinto;

[[v47-1-24]]

^<<v47-1-24,24>>^ não que tenhamos domínio sobre a vossa fé, mas porque somos cooperadores de vossa alegria; porquanto, pela fé, já estais firmados.

'''

xref:046-1-corintios/046-1-corintios-016.adoc#v46-16-0[&#60; Capítulo Anterior] | <<v47-1-0,Topo>> | xref:047-2-corintios/047-2-corintios-002.adoc#v47-2-0[Próximo Capítulo &#62;]