include::./index.adoc[]

[[v47-10-0]]
=== 2 Coríntios, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v47-10-1]]

^<<v47-10-1,1>>^ E eu mesmo, Paulo, vos rogo, pela mansidão e benignidade de Cristo, eu que, na verdade, quando presente entre vós, sou humilde; mas, quando ausente, ousado para convosco,

[[v47-10-2]]

^<<v47-10-2,2>>^ sim, eu vos rogo que não tenha de ser ousado, quando presente, servindo-me daquela firmeza com que penso devo tratar alguns que nos julgam como se andássemos em disposições de mundano proceder.

[[v47-10-3]]

^<<v47-10-3,3>>^ Porque, embora andando na carne, não militamos segundo a carne.

[[v47-10-4]]

^<<v47-10-4,4>>^ Porque as armas da nossa milícia não são carnais, e sim poderosas em Deus, para destruir fortalezas, anulando nós sofismas

[[v47-10-5]]

^<<v47-10-5,5>>^ e toda altivez que se levante contra o conhecimento de Deus, e levando cativo todo pensamento à obediência de Cristo,

[[v47-10-6]]

^<<v47-10-6,6>>^ e estando prontos para punir toda desobediência, uma vez completa a vossa submissão.

[[v47-10-7]]

^<<v47-10-7,7>>^ Observai o que está evidente. Se alguém confia em si que é de Cristo, pense outra vez consigo mesmo que, assim como ele é de Cristo, também nós o somos.

[[v47-10-8]]

^<<v47-10-8,8>>^ Porque, se eu me gloriar um pouco mais a respeito da nossa autoridade, a qual o Senhor nos conferiu para edificação e não para destruição vossa, não me envergonharei,

[[v47-10-9]]

^<<v47-10-9,9>>^ para que não pareça ser meu intuito intimidar-vos por meio de cartas.

[[v47-10-10]]

^<<v47-10-10,10>>^ As cartas, com efeito, dizem, são graves e fortes; mas a presença pessoal dele é fraca, e a palavra, desprezível.

[[v47-10-11]]

^<<v47-10-11,11>>^ Considere o tal isto: que o que somos na palavra por cartas, estando ausentes, tal seremos em atos, quando presentes.

[[v47-10-12]]

^<<v47-10-12,12>>^ Porque não ousamos classificar-nos ou comparar-nos com alguns que se louvam a si mesmos; mas eles, medindo-se consigo mesmos e comparando-se consigo mesmos, revelam insensatez.

[[v47-10-13]]

^<<v47-10-13,13>>^ Nós, porém, não nos gloriaremos sem medida, mas respeitamos o limite da esfera de ação que Deus nos demarcou e que se estende até vós.

[[v47-10-14]]

^<<v47-10-14,14>>^ Porque não ultrapassamos os nossos limites como se não devêssemos chegar até vós, posto que já chegamos até vós com o evangelho de Cristo;

[[v47-10-15]]

^<<v47-10-15,15>>^ não nos gloriando fora de medida nos trabalhos alheios e tendo esperança de que, crescendo a vossa fé, seremos sobremaneira engrandecidos entre vós, dentro da nossa esfera de ação,

[[v47-10-16]]

^<<v47-10-16,16>>^ a fim de anunciar o evangelho para além das vossas fronteiras, sem com isto nos gloriarmos de coisas já realizadas em campo alheio.

[[v47-10-17]]

^<<v47-10-17,17>>^ Aquele, porém, que se gloria, glorie-se no Senhor.

[[v47-10-18]]

^<<v47-10-18,18>>^ Porque não é aprovado quem a si mesmo se louva, e sim aquele a quem o Senhor louva.

'''

xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[&#60; Capítulo Anterior] | <<v47-10-0,Topo>> | xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[Próximo Capítulo &#62;]