include::./index.adoc[]

[[v47-3-0]]
=== 2 Coríntios, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v47-3-1]]

^<<v47-3-1,1>>^ Começamos, porventura, outra vez a recomendar-nos a nós mesmos? Ou temos necessidade, como alguns, de cartas de recomendação para vós outros ou de vós?

[[v47-3-2]]

^<<v47-3-2,2>>^ Vós sois a nossa carta, escrita em nosso coração, conhecida e lida por todos os homens,

[[v47-3-3]]

^<<v47-3-3,3>>^ estando já manifestos como carta de Cristo, produzida pelo nosso ministério, escrita não com tinta, mas pelo Espírito do Deus vivente, não em tábuas de pedra, mas em tábuas de carne, isto é, nos corações.

[[v47-3-4]]

^<<v47-3-4,4>>^ E é por intermédio de Cristo que temos tal confiança em Deus;

[[v47-3-5]]

^<<v47-3-5,5>>^ não que, por nós mesmos, sejamos capazes de pensar alguma coisa, como se partisse de nós; pelo contrário, a nossa suficiência vem de Deus,

[[v47-3-6]]

^<<v47-3-6,6>>^ o qual nos habilitou para sermos ministros de uma nova aliança, não da letra, mas do espírito; porque a letra mata, mas o espírito vivifica.

[[v47-3-7]]

^<<v47-3-7,7>>^ E, se o ministério da morte, gravado com letras em pedras, se revestiu de glória, a ponto de os filhos de Israel não poderem fitar a face de Moisés, por causa da glória do seu rosto, ainda que desvanecente,

[[v47-3-8]]

^<<v47-3-8,8>>^ como não será de maior glória o ministério do Espírito!

[[v47-3-9]]

^<<v47-3-9,9>>^ Porque, se o ministério da condenação foi glória, em muito maior proporção será glorioso o ministério da justiça.

[[v47-3-10]]

^<<v47-3-10,10>>^ Porquanto, na verdade, o que, outrora, foi glorificado, neste respeito, já não resplandece, diante da atual sobre-excelente glória.

[[v47-3-11]]

^<<v47-3-11,11>>^ Porque, se o que se desvanecia teve sua glória, muito mais glória tem o que é permanente.

[[v47-3-12]]

^<<v47-3-12,12>>^ Tendo, pois, tal esperança, servimo-nos de muita ousadia no falar.

[[v47-3-13]]

^<<v47-3-13,13>>^ E não somos como Moisés, que punha véu sobre a face, para que os filhos de Israel não atentassem na terminação do que se desvanecia.

[[v47-3-14]]

^<<v47-3-14,14>>^ Mas os sentidos deles se embotaram. Pois até ao dia de hoje, quando fazem a leitura da antiga aliança, o mesmo véu permanece, não lhes sendo revelado que, em Cristo, é removido.

[[v47-3-15]]

^<<v47-3-15,15>>^ Mas até hoje, quando é lido Moisés, o véu está posto sobre o coração deles.

[[v47-3-16]]

^<<v47-3-16,16>>^ Quando, porém, algum deles se converte ao Senhor, o véu lhe é retirado.

[[v47-3-17]]

^<<v47-3-17,17>>^ Ora, o Senhor é o Espírito; e, onde está o Espírito do Senhor, aí há liberdade.

[[v47-3-18]]

^<<v47-3-18,18>>^ E todos nós, com o rosto desvendado, contemplando, como por espelho, a glória do Senhor, somos transformados, de glória em glória, na sua própria imagem, como pelo Senhor, o Espírito.

'''

xref:047-2-corintios/047-2-corintios-002.adoc#v47-2-0[&#60; Capítulo Anterior] | <<v47-3-0,Topo>> | xref:047-2-corintios/047-2-corintios-004.adoc#v47-4-0[Próximo Capítulo &#62;]