include::./index.adoc[]

[[v47-7-0]]
=== 2 Coríntios, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v47-7-1]]

^<<v47-7-1,1>>^ Tendo, pois, ó amados, tais promessas, purifiquemo-nos de toda impureza, tanto da carne como do espírito, aperfeiçoando a nossa santidade no temor de Deus.

[[v47-7-2]]

^<<v47-7-2,2>>^ Acolhei-nos em vosso coração; a ninguém tratamos com injustiça, a ninguém corrompemos, a ninguém exploramos.

[[v47-7-3]]

^<<v47-7-3,3>>^ Não falo para vos condenar; porque já vos tenho dito que estais em nosso coração para, juntos, morrermos e vivermos.

[[v47-7-4]]

^<<v47-7-4,4>>^ Mui grande é a minha franqueza para convosco, e muito me glorio por vossa causa; sinto-me grandemente confortado e transbordante de júbilo em toda a nossa tribulação.

[[v47-7-5]]

^<<v47-7-5,5>>^ Porque, chegando nós à Macedônia, nenhum alívio tivemos; pelo contrário, em tudo fomos atribulados: lutas por fora, temores por dentro.

[[v47-7-6]]

^<<v47-7-6,6>>^ Porém Deus, que conforta os abatidos, nos consolou com a chegada de Tito;

[[v47-7-7]]

^<<v47-7-7,7>>^ e não somente com a sua chegada, mas também pelo conforto que recebeu de vós, referindo-nos a vossa saudade, o vosso pranto, o vosso zelo por mim, aumentando, assim, meu regozijo.

[[v47-7-8]]

^<<v47-7-8,8>>^ Porquanto, ainda que vos tenha contristado com a carta, não me arrependo; embora já me tenha arrependido (vejo que aquela carta vos contristou por breve tempo),

[[v47-7-9]]

^<<v47-7-9,9>>^ agora, me alegro não porque fostes contristados, mas porque fostes contristados para arrependimento; pois fostes contristados segundo Deus, para que, de nossa parte, nenhum dano sofrêsseis.

[[v47-7-10]]

^<<v47-7-10,10>>^ Porque a tristeza segundo Deus produz arrependimento para a salvação, que a ninguém traz pesar; mas a tristeza do mundo produz morte.

[[v47-7-11]]

^<<v47-7-11,11>>^ Porque quanto cuidado não produziu isto mesmo em vós que, segundo Deus, fostes contristados! Que defesa, que indignação, que temor, que saudades, que zelo, que vindita! Em tudo destes prova de estardes inocentes neste assunto.

[[v47-7-12]]

^<<v47-7-12,12>>^ Portanto, embora vos tenha escrito, não foi por causa do que fez o mal, nem por causa do que sofreu o agravo, mas para que a vossa solicitude a nosso favor fosse manifesta entre vós, diante de Deus.

[[v47-7-13]]

^<<v47-7-13,13>>^ Foi por isso que nos sentimos confortados. E, acima desta nossa consolação, muito mais nos alegramos pelo contentamento de Tito, cujo espírito foi recreado por todos vós.

[[v47-7-14]]

^<<v47-7-14,14>>^ Porque, se nalguma coisa me gloriei de vós para com ele, não fiquei envergonhado; pelo contrário, como, em tudo, vos falamos com verdade, também a nossa exaltação na presença de Tito se verificou ser verdadeira.

[[v47-7-15]]

^<<v47-7-15,15>>^ E o seu entranhável afeto cresce mais e mais para convosco, lembrando-se da obediência de todos vós, de como o recebestes com temor e tremor.

[[v47-7-16]]

^<<v47-7-16,16>>^ Alegro-me porque, em tudo, posso confiar em vós.

'''

xref:047-2-corintios/047-2-corintios-006.adoc#v47-6-0[&#60; Capítulo Anterior] | <<v47-7-0,Topo>> | xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[Próximo Capítulo &#62;]