include::./index.adoc[]

[[v47-2-0]]
=== 2 Coríntios, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v47-2-1]]

^<<v47-2-1,1>>^ Isto deliberei por mim mesmo: não voltar a encontrar-me convosco em tristeza.

[[v47-2-2]]

^<<v47-2-2,2>>^ Porque, se eu vos entristeço, quem me alegrará, senão aquele que está entristecido por mim mesmo?

[[v47-2-3]]

^<<v47-2-3,3>>^ E isto escrevi para que, quando for, não tenha tristeza da parte daqueles que deveriam alegrar-me, confiando em todos vós de que a minha alegria é também a vossa.

[[v47-2-4]]

^<<v47-2-4,4>>^ Porque, no meio de muitos sofrimentos e angústias de coração, vos escrevi, com muitas lágrimas, não para que ficásseis entristecidos, mas para que conhecêsseis o amor que vos consagro em grande medida.

[[v47-2-5]]

^<<v47-2-5,5>>^ Ora, se alguém causou tristeza, não o fez apenas a mim, mas, para que eu não seja demasiadamente áspero, digo que em parte a todos vós;

[[v47-2-6]]

^<<v47-2-6,6>>^ basta-lhe a punição pela maioria.

[[v47-2-7]]

^<<v47-2-7,7>>^ De modo que deveis, pelo contrário, perdoar-lhe e confortá-lo, para que não seja o mesmo consumido por excessiva tristeza.

[[v47-2-8]]

^<<v47-2-8,8>>^ Pelo que vos rogo que confirmeis para com ele o vosso amor.

[[v47-2-9]]

^<<v47-2-9,9>>^ E foi por isso também que vos escrevi, para ter prova de que, em tudo, sois obedientes.

[[v47-2-10]]

^<<v47-2-10,10>>^ A quem perdoais alguma coisa, também eu perdoo; porque, de fato, o que tenho perdoado (se alguma coisa tenho perdoado), por causa de vós o fiz na presença de Cristo;

[[v47-2-11]]

^<<v47-2-11,11>>^ para que Satanás não alcance vantagem sobre nós, pois não lhe ignoramos os desígnios.

[[v47-2-12]]

^<<v47-2-12,12>>^ Ora, quando cheguei a Trôade para pregar o evangelho de Cristo, e uma porta se me abriu no Senhor,

[[v47-2-13]]

^<<v47-2-13,13>>^ não tive, contudo, tranquilidade no meu espírito, porque não encontrei o meu irmão Tito; por isso, despedindo-me deles, parti para a Macedônia.

[[v47-2-14]]

^<<v47-2-14,14>>^ Graças, porém, a Deus, que, em Cristo, sempre nos conduz em triunfo e, por meio de nós, manifesta em todo lugar a fragrância do seu conhecimento.

[[v47-2-15]]

^<<v47-2-15,15>>^ Porque nós somos para com Deus o bom perfume de Cristo, tanto nos que são salvos como nos que se perdem.

[[v47-2-16]]

^<<v47-2-16,16>>^ Para com estes, cheiro de morte para morte; para com aqueles, aroma de vida para vida. Quem, porém, é suficiente para estas coisas?

[[v47-2-17]]

^<<v47-2-17,17>>^ Porque nós não estamos, como tantos outros, mercadejando a palavra de Deus; antes, em Cristo é que falamos na presença de Deus, com sinceridade e da parte do próprio Deus.

'''

xref:047-2-corintios/047-2-corintios-001.adoc#v47-1-0[&#60; Capítulo Anterior] | <<v47-2-0,Topo>> | xref:047-2-corintios/047-2-corintios-003.adoc#v47-3-0[Próximo Capítulo &#62;]