include::./index.adoc[]

[[v47-13-0]]
=== 2 Coríntios, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v47-13-1]]

^<<v47-13-1,1>>^ Esta é a terceira vez que vou ter convosco. Por boca de duas ou três testemunhas, toda questão será decidida.

[[v47-13-2]]

^<<v47-13-2,2>>^ Já o disse anteriormente e torno a dizer, como fiz quando estive presente pela segunda vez; mas, agora, estando ausente, o digo aos que, outrora, pecaram e a todos os mais que, se outra vez for, não os pouparei,

[[v47-13-3]]

^<<v47-13-3,3>>^ posto que buscais prova de que, em mim, Cristo fala, o qual não é fraco para convosco; antes, é poderoso em vós.

[[v47-13-4]]

^<<v47-13-4,4>>^ Porque, de fato, foi crucificado em fraqueza; contudo, vive pelo poder de Deus. Porque nós também somos fracos nele, mas viveremos, com ele, para vós outros pelo poder de Deus.

[[v47-13-5]]

^<<v47-13-5,5>>^ Examinai-vos a vós mesmos se realmente estais na fé; provai-vos a vós mesmos. Ou não reconheceis que Jesus Cristo está em vós? Se não é que já estais reprovados.

[[v47-13-6]]

^<<v47-13-6,6>>^ Mas espero reconheçais que não somos reprovados.

[[v47-13-7]]

^<<v47-13-7,7>>^ Estamos orando a Deus para que não façais mal algum, não para que, simplesmente, pareçamos aprovados, mas para que façais o bem, embora sejamos tidos como reprovados.

[[v47-13-8]]

^<<v47-13-8,8>>^ Porque nada podemos contra a verdade, senão em favor da própria verdade.

[[v47-13-9]]

^<<v47-13-9,9>>^ Porque nos regozijamos quando nós estamos fracos e vós, fortes; e isto é o que pedimos: o vosso aperfeiçoamento.

[[v47-13-10]]

^<<v47-13-10,10>>^ Portanto, escrevo estas coisas, estando ausente, para que, estando presente, não venha a usar de rigor segundo a autoridade que o Senhor me conferiu para edificação e não para destruir.

[[v47-13-11]]

^<<v47-13-11,11>>^ Quanto ao mais, irmãos, adeus! Aperfeiçoai-vos, consolai-vos, sede do mesmo parecer, vivei em paz; e o Deus de amor e de paz estará convosco.

[[v47-13-12]]

^<<v47-13-12,12>>^ Saudai-vos uns aos outros com ósculo santo. Todos os santos vos saúdam.

[[v47-13-13]]

^<<v47-13-13,13>>^ A graça do Senhor Jesus Cristo, e o amor de Deus, e a comunhão do Espírito Santo sejam com todos vós.

'''

xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[&#60; Capítulo Anterior] | <<v47-13-0,Topo>> | xref:048-galatas/048-galatas-001.adoc#v48-1-0[Próximo Capítulo &#62;]