include::./index.adoc[]

[[v47-8-0]]
=== 2 Coríntios, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v47-8-1]]

^<<v47-8-1,1>>^ Também, irmãos, vos fazemos conhecer a graça de Deus concedida às igrejas da Macedônia;

[[v47-8-2]]

^<<v47-8-2,2>>^ porque, no meio de muita prova de tribulação, manifestaram abundância de alegria, e a profunda pobreza deles superabundou em grande riqueza da sua generosidade.

[[v47-8-3]]

^<<v47-8-3,3>>^ Porque eles, testemunho eu, na medida de suas posses e mesmo acima delas, se mostraram voluntários,

[[v47-8-4]]

^<<v47-8-4,4>>^ pedindo-nos, com muitos rogos, a graça de participarem da assistência aos santos.

[[v47-8-5]]

^<<v47-8-5,5>>^ E não somente fizeram como nós esperávamos, mas também deram-se a si mesmos primeiro ao Senhor, depois a nós, pela vontade de Deus;

[[v47-8-6]]

^<<v47-8-6,6>>^ o que nos levou a recomendar a Tito que, como começou, assim também complete esta graça entre vós.

[[v47-8-7]]

^<<v47-8-7,7>>^ Como, porém, em tudo, manifestais superabundância, tanto na fé e na palavra como no saber, e em todo cuidado, e em nosso amor para convosco, assim também abundeis nesta graça.

[[v47-8-8]]

^<<v47-8-8,8>>^ Não vos falo na forma de mandamento, mas para provar, pela diligência de outros, a sinceridade do vosso amor;

[[v47-8-9]]

^<<v47-8-9,9>>^ pois conheceis a graça de nosso Senhor Jesus Cristo, que, sendo rico, se fez pobre por amor de vós, para que, pela sua pobreza, vos tornásseis ricos.

[[v47-8-10]]

^<<v47-8-10,10>>^ E nisto dou minha opinião; pois a vós outros, que, desde o ano passado, principiastes não só a prática, mas também o querer, convém isto.

[[v47-8-11]]

^<<v47-8-11,11>>^ Completai, agora, a obra começada, para que, assim como revelastes prontidão no querer, assim a leveis a termo, segundo as vossas posses.

[[v47-8-12]]

^<<v47-8-12,12>>^ Porque, se há boa vontade, será aceita conforme o que o homem tem e não segundo o que ele não tem.

[[v47-8-13]]

^<<v47-8-13,13>>^ Porque não é para que os outros tenham alívio, e vós, sobrecarga; mas para que haja igualdade,

[[v47-8-14]]

^<<v47-8-14,14>>^ suprindo a vossa abundância, no presente, a falta daqueles, de modo que a abundância daqueles venha a suprir a vossa falta, e, assim, haja igualdade,

[[v47-8-15]]

^<<v47-8-15,15>>^ como está escrito: O que muito colheu não teve demais; e o que pouco, não teve falta.

[[v47-8-16]]

^<<v47-8-16,16>>^ Mas graças a Deus, que pôs no coração de Tito a mesma solicitude por amor de vós;

[[v47-8-17]]

^<<v47-8-17,17>>^ porque atendeu ao nosso apelo e, mostrando-se mais cuidadoso, partiu voluntariamente para vós outros.

[[v47-8-18]]

^<<v47-8-18,18>>^ E, com ele, enviamos o irmão cujo louvor no evangelho está espalhado por todas as igrejas.

[[v47-8-19]]

^<<v47-8-19,19>>^ E não só isto, mas foi também eleito pelas igrejas para ser nosso companheiro no desempenho desta graça ministrada por nós, para a glória do próprio Senhor e para mostrar a nossa boa vontade;

[[v47-8-20]]

^<<v47-8-20,20>>^ evitando, assim, que alguém nos acuse em face desta generosa dádiva administrada por nós;

[[v47-8-21]]

^<<v47-8-21,21>>^ pois o que nos preocupa é procedermos honestamente, não só perante o Senhor, como também diante dos homens.

[[v47-8-22]]

^<<v47-8-22,22>>^ Com eles, enviamos nosso irmão cujo zelo, em muitas ocasiões e de muitos modos, temos experimentado; agora, porém, se mostra ainda mais zeloso pela muita confiança em vós.

[[v47-8-23]]

^<<v47-8-23,23>>^ Quanto a Tito, é meu companheiro e cooperador convosco; quanto a nossos irmãos, são mensageiros das igrejas e glória de Cristo.

[[v47-8-24]]

^<<v47-8-24,24>>^ Manifestai, pois, perante as igrejas, a prova do vosso amor e da nossa exultação a vosso respeito na presença destes homens.

'''

xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[&#60; Capítulo Anterior] | <<v47-8-0,Topo>> | xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[Próximo Capítulo &#62;]