include::./index.adoc[]

[[v47-11-0]]
=== 2 Coríntios, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v47-11-1]]

^<<v47-11-1,1>>^ Quisera eu me suportásseis um pouco mais na minha loucura. Suportai-me, pois.

[[v47-11-2]]

^<<v47-11-2,2>>^ Porque zelo por vós com zelo de Deus; visto que vos tenho preparado para vos apresentar como virgem pura a um só esposo, que é Cristo.

[[v47-11-3]]

^<<v47-11-3,3>>^ Mas receio que, assim como a serpente enganou a Eva com a sua astúcia, assim também seja corrompida a vossa mente e se aparte da simplicidade e pureza devidas a Cristo.

[[v47-11-4]]

^<<v47-11-4,4>>^ Se, na verdade, vindo alguém, prega outro Jesus que não temos pregado, ou se aceitais espírito diferente que não tendes recebido, ou evangelho diferente que não tendes abraçado, a esse, de boa mente, o tolerais.

[[v47-11-5]]

^<<v47-11-5,5>>^ Porque suponho em nada ter sido inferior a esses tais apóstolos.

[[v47-11-6]]

^<<v47-11-6,6>>^ E, embora seja falto no falar, não o sou no conhecimento; mas, em tudo e por todos os modos, vos temos feito conhecer isto.

[[v47-11-7]]

^<<v47-11-7,7>>^ Cometi eu, porventura, algum pecado pelo fato de viver humildemente, para que fôsseis vós exaltados, visto que gratuitamente vos anunciei o evangelho de Deus?

[[v47-11-8]]

^<<v47-11-8,8>>^ Despojei outras igrejas, recebendo salário, para vos poder servir,

[[v47-11-9]]

^<<v47-11-9,9>>^ e, estando entre vós, ao passar privações, não me fiz pesado a ninguém; pois os irmãos, quando vieram da Macedônia, supriram o que me faltava; e, em tudo, me guardei e me guardarei de vos ser pesado.

[[v47-11-10]]

^<<v47-11-10,10>>^ A verdade de Cristo está em mim; por isso, não me será tirada esta glória nas regiões da Acaia.

[[v47-11-11]]

^<<v47-11-11,11>>^ Por que razão? É porque não vos amo? Deus o sabe.

[[v47-11-12]]

^<<v47-11-12,12>>^ Mas o que faço e farei é para cortar ocasião àqueles que a buscam com o intuito de serem considerados iguais a nós, naquilo em que se gloriam.

[[v47-11-13]]

^<<v47-11-13,13>>^ Porque os tais são falsos apóstolos, obreiros fraudulentos, transformando-se em apóstolos de Cristo.

[[v47-11-14]]

^<<v47-11-14,14>>^ E não é de admirar, porque o próprio Satanás se transforma em anjo de luz.

[[v47-11-15]]

^<<v47-11-15,15>>^ Não é muito, pois, que os seus próprios ministros se transformem em ministros de justiça; e o fim deles será conforme as suas obras.

[[v47-11-16]]

^<<v47-11-16,16>>^ Outra vez digo: ninguém me considere insensato; todavia, se o pensais, recebei-me como insensato, para que também me glorie um pouco.

[[v47-11-17]]

^<<v47-11-17,17>>^ O que falo, não o falo segundo o Senhor, e sim como por loucura, nesta confiança de gloriar-me.

[[v47-11-18]]

^<<v47-11-18,18>>^ E, posto que muitos se gloriam segundo a carne, também eu me gloriarei.

[[v47-11-19]]

^<<v47-11-19,19>>^ Porque, sendo vós sensatos, de boa mente tolerais os insensatos.

[[v47-11-20]]

^<<v47-11-20,20>>^ Tolerais quem vos escravize, quem vos devore, quem vos detenha, quem se exalte, quem vos esbofeteie no rosto.

[[v47-11-21]]

^<<v47-11-21,21>>^ Ingloriamente o confesso, como se fôramos fracos. Mas, naquilo em que qualquer tem ousadia (com insensatez o afirmo), também eu a tenho.

[[v47-11-22]]

^<<v47-11-22,22>>^ São hebreus? Também eu. São israelitas? Também eu. São da descendência de Abraão? Também eu.

[[v47-11-23]]

^<<v47-11-23,23>>^ São ministros de Cristo? (Falo como fora de mim.) Eu ainda mais: em trabalhos, muito mais; muito mais em prisões; em açoites, sem medida; em perigos de morte, muitas vezes.

[[v47-11-24]]

^<<v47-11-24,24>>^ Cinco vezes recebi dos judeus uma quarentena de açoites menos um;

[[v47-11-25]]

^<<v47-11-25,25>>^ fui três vezes fustigado com varas; uma vez, apedrejado; em naufrágio, três vezes; uma noite e um dia passei na voragem do mar;

[[v47-11-26]]

^<<v47-11-26,26>>^ em jornadas, muitas vezes; em perigos de rios, em perigos de salteadores, em perigos entre patrícios, em perigos entre gentios, em perigos na cidade, em perigos no deserto, em perigos no mar, em perigos entre falsos irmãos;

[[v47-11-27]]

^<<v47-11-27,27>>^ em trabalhos e fadigas, em vigílias, muitas vezes; em fome e sede, em jejuns, muitas vezes; em frio e nudez.

[[v47-11-28]]

^<<v47-11-28,28>>^ Além das coisas exteriores, há o que pesa sobre mim diariamente, a preocupação com todas as igrejas.

[[v47-11-29]]

^<<v47-11-29,29>>^ Quem enfraquece, que também eu não enfraqueça? Quem se escandaliza, que eu não me inflame?

[[v47-11-30]]

^<<v47-11-30,30>>^ Se tenho de gloriar-me, gloriar-me-ei no que diz respeito à minha fraqueza.

[[v47-11-31]]

^<<v47-11-31,31>>^ O Deus e Pai do Senhor Jesus, que é eternamente bendito, sabe que não minto.

[[v47-11-32]]

^<<v47-11-32,32>>^ Em Damasco, o governador preposto do rei Aretas montou guarda na cidade dos damascenos, para me prender;

[[v47-11-33]]

^<<v47-11-33,33>>^ mas, num grande cesto, me desceram por uma janela da muralha abaixo, e assim me livrei das suas mãos.

'''

xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[&#60; Capítulo Anterior] | <<v47-11-0,Topo>> | xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[Próximo Capítulo &#62;]