include::./index.adoc[]

[[v47-12-0]]
=== 2 Coríntios, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v47-12-1]]

^<<v47-12-1,1>>^ Se é necessário que me glorie, ainda que não convém, passarei às visões e revelações do Senhor.

[[v47-12-2]]

^<<v47-12-2,2>>^ Conheço um homem em Cristo que, há catorze anos, foi arrebatado até ao terceiro céu (se no corpo ou fora do corpo, não sei, Deus o sabe)

[[v47-12-3]]

^<<v47-12-3,3>>^ e sei que o tal homem (se no corpo ou fora do corpo, não sei, Deus o sabe)

[[v47-12-4]]

^<<v47-12-4,4>>^ foi arrebatado ao paraíso e ouviu palavras inefáveis, as quais não é lícito ao homem referir.

[[v47-12-5]]

^<<v47-12-5,5>>^ De tal coisa me gloriarei; não, porém, de mim mesmo, salvo nas minhas fraquezas.

[[v47-12-6]]

^<<v47-12-6,6>>^ Pois, se eu vier a gloriar-me, não serei néscio, porque direi a verdade; mas abstenho-me para que ninguém se preocupe comigo mais do que em mim vê ou de mim ouve.

[[v47-12-7]]

^<<v47-12-7,7>>^ E, para que não me ensoberbecesse com a grandeza das revelações, foi-me posto um espinho na carne, mensageiro de Satanás, para me esbofetear, a fim de que não me exalte.

[[v47-12-8]]

^<<v47-12-8,8>>^ Por causa disto, três vezes pedi ao Senhor que o afastasse de mim.

[[v47-12-9]]

^<<v47-12-9,9>>^ Então, ele me disse: A minha graça te basta, porque o poder se aperfeiçoa na fraqueza.  De boa vontade, pois, mais me gloriarei nas fraquezas, para que sobre mim repouse o poder de Cristo.

[[v47-12-10]]

^<<v47-12-10,10>>^ Pelo que sinto prazer nas fraquezas, nas injúrias, nas necessidades, nas perseguições, nas angústias, por amor de Cristo. Porque, quando sou fraco, então, é que sou forte.

[[v47-12-11]]

^<<v47-12-11,11>>^ Tenho-me tornado insensato; a isto me constrangestes. Eu devia ter sido louvado por vós; porquanto em nada fui inferior a esses tais apóstolos, ainda que nada sou.

[[v47-12-12]]

^<<v47-12-12,12>>^ Pois as credenciais do apostolado foram apresentadas no meio de vós, com toda a persistência, por sinais, prodígios e poderes miraculosos.

[[v47-12-13]]

^<<v47-12-13,13>>^ Porque, em que tendes vós sido inferiores às demais igrejas, senão neste fato de não vos ter sido pesado? Perdoai-me esta injustiça.

[[v47-12-14]]

^<<v47-12-14,14>>^ Eis que, pela terceira vez, estou pronto a ir ter convosco e não vos serei pesado; pois não vou atrás dos vossos bens, mas procuro a vós outros. Não devem os filhos entesourar para os pais, mas os pais, para os filhos.

[[v47-12-15]]

^<<v47-12-15,15>>^ Eu de boa vontade me gastarei e ainda me deixarei gastar em prol da vossa alma. Se mais vos amo, serei menos amado?

[[v47-12-16]]

^<<v47-12-16,16>>^ Pois seja assim, eu não vos fui pesado; porém, sendo astuto, vos prendi com dolo.

[[v47-12-17]]

^<<v47-12-17,17>>^ Porventura, vos explorei por intermédio de algum daqueles que vos enviei?

[[v47-12-18]]

^<<v47-12-18,18>>^ Roguei a Tito e enviei com ele outro irmão; porventura, Tito vos explorou? Acaso, não temos andado no mesmo espírito? Não seguimos nas mesmas pisadas?

[[v47-12-19]]

^<<v47-12-19,19>>^ Há muito, pensais que nos estamos desculpando convosco. Falamos em Cristo perante Deus, e tudo, ó amados, para vossa edificação.

[[v47-12-20]]

^<<v47-12-20,20>>^ Temo, pois, que, indo ter convosco, não vos encontre na forma em que vos quero, e que também vós me acheis diferente do que esperáveis, e que haja entre vós contendas, invejas, iras, porfias, detrações, intrigas, orgulho e tumultos.

[[v47-12-21]]

^<<v47-12-21,21>>^ Receio que, indo outra vez, o meu Deus me humilhe no meio de vós, e eu venha a chorar por muitos que, outrora, pecaram e não se arrependeram da impureza, prostituição e lascívia que cometeram.

'''

xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[&#60; Capítulo Anterior] | <<v47-12-0,Topo>> | xref:047-2-corintios/047-2-corintios-013.adoc#v47-13-0[Próximo Capítulo &#62;]