include::./index.adoc[]

[[v47-6-0]]
=== 2 Coríntios, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v47-6-1]]

^<<v47-6-1,1>>^ E nós, na qualidade de cooperadores com ele, também vos exortamos a que não recebais em vão a graça de Deus

[[v47-6-2]]

^<<v47-6-2,2>>^ (porque ele diz: Eu te ouvi no tempo da oportunidade e te socorri no dia da salvação; eis, agora, o tempo sobremodo oportuno, eis, agora, o dia da salvação);

[[v47-6-3]]

^<<v47-6-3,3>>^ não dando nós nenhum motivo de escândalo em coisa alguma, para que o ministério não seja censurado.

[[v47-6-4]]

^<<v47-6-4,4>>^ Pelo contrário, em tudo recomendando-nos a nós mesmos como ministros de Deus: na muita paciência, nas aflições, nas privações, nas angústias,

[[v47-6-5]]

^<<v47-6-5,5>>^ nos açoites, nas prisões, nos tumultos, nos trabalhos, nas vigílias, nos jejuns,

[[v47-6-6]]

^<<v47-6-6,6>>^ na pureza, no saber, na longanimidade, na bondade, no Espírito Santo, no amor não fingido,

[[v47-6-7]]

^<<v47-6-7,7>>^ na palavra da verdade, no poder de Deus, pelas armas da justiça, quer ofensivas, quer defensivas;

[[v47-6-8]]

^<<v47-6-8,8>>^ por honra e por desonra, por infâmia e por boa fama, como enganadores e sendo verdadeiros;

[[v47-6-9]]

^<<v47-6-9,9>>^ como desconhecidos e, entretanto, bem-conhecidos; como se estivéssemos morrendo e, contudo, eis que vivemos; como castigados, porém não mortos;

[[v47-6-10]]

^<<v47-6-10,10>>^ entristecidos, mas sempre alegres; pobres, mas enriquecendo a muitos; nada tendo, mas possuindo tudo.

[[v47-6-11]]

^<<v47-6-11,11>>^ Para vós outros, ó coríntios, abrem-se os nossos lábios, e alarga-se o nosso coração.

[[v47-6-12]]

^<<v47-6-12,12>>^ Não tendes limites em nós; mas estais limitados em vossos próprios afetos.

[[v47-6-13]]

^<<v47-6-13,13>>^ Ora, como justa retribuição (falo-vos como a filhos), dilatai-vos também vós.

[[v47-6-14]]

^<<v47-6-14,14>>^ Não vos ponhais em jugo desigual com os incrédulos; porquanto que sociedade pode haver entre a justiça e a iniquidade? Ou que comunhão, da luz com as trevas?

[[v47-6-15]]

^<<v47-6-15,15>>^ Que harmonia, entre Cristo e o Maligno? Ou que união, do crente com o incrédulo?

[[v47-6-16]]

^<<v47-6-16,16>>^ Que ligação há entre o santuário de Deus e os ídolos? Porque nós somos santuário do Deus vivente, como ele próprio disse: Habitarei e andarei entre eles; serei o seu Deus, e eles serão o meu povo.

[[v47-6-17]]

^<<v47-6-17,17>>^ Por isso, retirai-vos do meio deles, separai-vos, diz o Senhor; não toqueis em coisas impuras; e eu vos receberei,

[[v47-6-18]]

^<<v47-6-18,18>>^ serei vosso Pai, e vós sereis para mim filhos e filhas, diz o Senhor Todo-Poderoso.

'''

xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[&#60; Capítulo Anterior] | <<v47-6-0,Topo>> | xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[Próximo Capítulo &#62;]