include::./index.adoc[]

[[v47-4-0]]
=== 2 Coríntios, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v47-4-1]]

^<<v47-4-1,1>>^ Pelo que, tendo este ministério, segundo a misericórdia que nos foi feita, não desfalecemos;

[[v47-4-2]]

^<<v47-4-2,2>>^ pelo contrário, rejeitamos as coisas que, por vergonhosas, se ocultam, não andando com astúcia, nem adulterando a palavra de Deus; antes, nos recomendamos à consciência de todo homem, na presença de Deus, pela manifestação da verdade.

[[v47-4-3]]

^<<v47-4-3,3>>^ Mas, se o nosso evangelho ainda está encoberto, é para os que se perdem que está encoberto,

[[v47-4-4]]

^<<v47-4-4,4>>^ nos quais o deus deste século cegou o entendimento dos incrédulos, para que lhes não resplandeça a luz do evangelho da glória de Cristo, o qual é a imagem de Deus.

[[v47-4-5]]

^<<v47-4-5,5>>^ Porque não nos pregamos a nós mesmos, mas a Cristo Jesus como Senhor e a nós mesmos como vossos servos, por amor de Jesus.

[[v47-4-6]]

^<<v47-4-6,6>>^ Porque Deus, que disse: Das trevas resplandecerá a luz, ele mesmo resplandeceu em nosso coração, para iluminação do conhecimento da glória de Deus, na face de Cristo.

[[v47-4-7]]

^<<v47-4-7,7>>^ Temos, porém, este tesouro em vasos de barro, para que a excelência do poder seja de Deus e não de nós.

[[v47-4-8]]

^<<v47-4-8,8>>^ Em tudo somos atribulados, porém não angustiados; perplexos, porém não desanimados;

[[v47-4-9]]

^<<v47-4-9,9>>^ perseguidos, porém não desamparados; abatidos, porém não destruídos;

[[v47-4-10]]

^<<v47-4-10,10>>^ levando sempre no corpo o morrer de Jesus, para que também a sua vida se manifeste em nosso corpo.

[[v47-4-11]]

^<<v47-4-11,11>>^ Porque nós, que vivemos, somos sempre entregues à morte por causa de Jesus, para que também a vida de Jesus se manifeste em nossa carne mortal.

[[v47-4-12]]

^<<v47-4-12,12>>^ De modo que, em nós, opera a morte, mas, em vós, a vida.

[[v47-4-13]]

^<<v47-4-13,13>>^ Tendo, porém, o mesmo espírito da fé, como está escrito: Eu cri; por isso, é que falei. Também nós cremos; por isso, também falamos,

[[v47-4-14]]

^<<v47-4-14,14>>^ sabendo que aquele que ressuscitou o Senhor Jesus também nos ressuscitará com Jesus e nos apresentará convosco.

[[v47-4-15]]

^<<v47-4-15,15>>^ Porque todas as coisas existem por amor de vós, para que a graça, multiplicando-se, torne abundantes as ações de graças por meio de muitos, para glória de Deus.

[[v47-4-16]]

^<<v47-4-16,16>>^ Por isso, não desanimamos; pelo contrário, mesmo que o nosso homem exterior se corrompa, contudo, o nosso homem interior se renova de dia em dia.

[[v47-4-17]]

^<<v47-4-17,17>>^ Porque a nossa leve e momentânea tribulação produz para nós eterno peso de glória, acima de toda comparação,

[[v47-4-18]]

^<<v47-4-18,18>>^ não atentando nós nas coisas que se veem, mas nas que se não veem; porque as que se veem são temporais, e as que se não veem são eternas.

'''

xref:047-2-corintios/047-2-corintios-003.adoc#v47-3-0[&#60; Capítulo Anterior] | <<v47-4-0,Topo>> | xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[Próximo Capítulo &#62;]