include::./index.adoc[]

[[v47-9-0]]
=== 2 Coríntios, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v47-9-1]]

^<<v47-9-1,1>>^ Ora, quanto à assistência a favor dos santos, é desnecessário escrever-vos,

[[v47-9-2]]

^<<v47-9-2,2>>^ porque bem reconheço a vossa presteza, da qual me glorio junto aos macedônios, dizendo que a Acaia está preparada desde o ano passado; e o vosso zelo tem estimulado a muitíssimos.

[[v47-9-3]]

^<<v47-9-3,3>>^ Contudo, enviei os irmãos, para que o nosso louvor a vosso respeito, neste particular, não se desminta, a fim de que, como venho dizendo, estivésseis preparados,

[[v47-9-4]]

^<<v47-9-4,4>>^ para que, caso alguns macedônios forem comigo e vos encontrem desapercebidos, não fiquemos nós envergonhados (para não dizer, vós) quanto a esta confiança.

[[v47-9-5]]

^<<v47-9-5,5>>^ Portanto, julguei conveniente recomendar aos irmãos que me precedessem entre vós e preparassem de antemão a vossa dádiva já anunciada, para que esteja pronta como expressão de generosidade e não de avareza.

[[v47-9-6]]

^<<v47-9-6,6>>^ E isto afirmo: aquele que semeia pouco pouco também ceifará; e o que semeia com fartura com abundância também ceifará.

[[v47-9-7]]

^<<v47-9-7,7>>^ Cada um contribua segundo tiver proposto no coração, não com tristeza ou por necessidade; porque Deus ama a quem dá com alegria.

[[v47-9-8]]

^<<v47-9-8,8>>^ Deus pode fazer-vos abundar em toda graça, a fim de que, tendo sempre, em tudo, ampla suficiência, superabundeis em toda boa obra,

[[v47-9-9]]

^<<v47-9-9,9>>^ como está escrito: Distribuiu, deu aos pobres, a sua justiça permanece para sempre.

[[v47-9-10]]

^<<v47-9-10,10>>^ Ora, aquele que dá semente ao que semeia e pão para alimento também suprirá e aumentará a vossa sementeira e multiplicará os frutos da vossa justiça,

[[v47-9-11]]

^<<v47-9-11,11>>^ enriquecendo-vos, em tudo, para toda generosidade, a qual faz que, por nosso intermédio, sejam tributadas graças a Deus.

[[v47-9-12]]

^<<v47-9-12,12>>^ Porque o serviço desta assistência não só supre a necessidade dos santos, mas também redunda em muitas graças a Deus,

[[v47-9-13]]

^<<v47-9-13,13>>^ visto como, na prova desta ministração, glorificam a Deus pela obediência da vossa confissão quanto ao evangelho de Cristo e pela liberalidade com que contribuís para eles e para todos,

[[v47-9-14]]

^<<v47-9-14,14>>^ enquanto oram eles a vosso favor, com grande afeto, em virtude da superabundante graça de Deus que há em vós.

[[v47-9-15]]

^<<v47-9-15,15>>^ Graças a Deus pelo seu dom inefável!

'''

xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[&#60; Capítulo Anterior] | <<v47-9-0,Topo>> | xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[Próximo Capítulo &#62;]