include::./index.adoc[]

[[v10-14-0]]
=== 2 Samuel, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-14-1]]

^<<v10-14-1,1>>^ Percebendo, pois, Joabe, filho de Zeruia, que o coração do rei começava a inclinar-se para Absalão,

[[v10-14-2]]

^<<v10-14-2,2>>^ mandou trazer de Tecoa uma mulher sábia e lhe disse: Finge que estás profundamente triste, põe vestidos de luto, não te unjas com óleo e sê como mulher que há já muitos dias está de luto por algum morto.

[[v10-14-3]]

^<<v10-14-3,3>>^ Apresenta-te ao rei e fala-lhe tais e tais palavras. E Joabe lhe pôs as palavras na boca.

[[v10-14-4]]

^<<v10-14-4,4>>^ A mulher tecoíta apresentou-se ao rei, e, inclinando-se, prostrou-se com o rosto em terra, e disse: Salva-me, ó rei!

[[v10-14-5]]

^<<v10-14-5,5>>^ Perguntou-lhe o rei: Que tens? Ela respondeu: Ah! Sou mulher viúva; morreu meu marido.

[[v10-14-6]]

^<<v10-14-6,6>>^ Tinha a tua serva dois filhos, os quais brigaram entre si no campo, e não houve quem os apartasse; um feriu ao outro e o matou.

[[v10-14-7]]

^<<v10-14-7,7>>^ Eis que toda a parentela se levantou contra a tua serva, e disseram: Dá-nos aquele que feriu a seu irmão, para que o matemos, em vingança da vida de quem ele matou e para que destruamos também o herdeiro. Assim, apagarão a última brasa que me ficou, de sorte que não deixam a meu marido nome, nem sobrevivente na terra.

[[v10-14-8]]

^<<v10-14-8,8>>^ Disse o rei à mulher: Vai para tua casa, e eu darei ordens a teu respeito.

[[v10-14-9]]

^<<v10-14-9,9>>^ Disse a mulher tecoíta ao rei: A culpa, ó rei, meu senhor, caia sobre mim e sobre a casa de meu pai; o rei, porém, e o seu trono sejam inocentes.

[[v10-14-10]]

^<<v10-14-10,10>>^ Disse o rei: Quem falar contra ti, traze-mo a mim; e nunca mais te tocará.

[[v10-14-11]]

^<<v10-14-11,11>>^ Disse ela: Ora, lembra-te, ó rei, do SENHOR, teu Deus, para que os vingadores do sangue não se multipliquem a matar e exterminem meu filho. Respondeu ele: Tão certo como vive o SENHOR, não há de cair no chão nem um só dos cabelos de teu filho.

[[v10-14-12]]

^<<v10-14-12,12>>^ Então, disse a mulher: Permite que a tua serva fale uma palavra contigo, ó rei, meu senhor. Disse ele: Fala.

[[v10-14-13]]

^<<v10-14-13,13>>^ Prosseguiu a mulher: Por que pensas tu doutro modo contra o povo de Deus? Pois, em pronunciando o rei esse juízo, condena-se a si mesmo, visto que não quer fazer voltar o seu desterrado.

[[v10-14-14]]

^<<v10-14-14,14>>^ Porque temos de morrer e somos como águas derramadas na terra que já não se podem juntar; pois Deus não tira a vida, mas cogita meios para que o banido não permaneça arrojado de sua presença.

[[v10-14-15]]

^<<v10-14-15,15>>^ Se vim, agora, falar esta palavra ao rei, meu senhor, é porque o povo me atemorizou; pois dizia a tua serva: Falarei ao rei; porventura, ele fará segundo a palavra da sua serva.

[[v10-14-16]]

^<<v10-14-16,16>>^ Porque o rei atenderá, para livrar a sua serva da mão do homem que intenta destruir tanto a mim como a meu filho da herança de Deus.

[[v10-14-17]]

^<<v10-14-17,17>>^ Dizia mais a tua serva: Seja, agora, a palavra do rei, meu senhor, para a minha tranquilidade; porque, como um anjo de Deus, assim é o rei, meu senhor, para discernir entre o bem e o mal. O SENHOR, teu Deus, será contigo.

[[v10-14-18]]

^<<v10-14-18,18>>^ Então, respondeu o rei e disse à mulher: Peço-te que não me encubras o que eu te perguntar. Respondeu a mulher: Pois fale o rei, meu senhor.

[[v10-14-19]]

^<<v10-14-19,19>>^ Disse o rei: Não é certo que a mão de Joabe anda contigo em tudo isto? Respondeu ela: Tão certo como vive a tua alma, ó rei, meu senhor, ninguém se poderá desviar, nem para a direita nem para a esquerda, de tudo quanto o rei, meu senhor, tem dito; porque Joabe, teu servo, é quem me deu ordem e foi ele quem ditou à tua serva todas estas palavras.

[[v10-14-20]]

^<<v10-14-20,20>>^ Para mudar o aspecto deste caso foi que o teu servo Joabe fez isto. Porém sábio é meu senhor, segundo a sabedoria de um anjo de Deus, para entender tudo o que se passa na terra.

[[v10-14-21]]

^<<v10-14-21,21>>^ Então, o rei disse a Joabe: Atendi ao teu pedido; vai, pois, e traze o jovem Absalão.

[[v10-14-22]]

^<<v10-14-22,22>>^ Inclinando-se Joabe, prostrou-se em terra, abençoou o rei e disse: Hoje, reconheço que achei mercê diante de ti, ó rei, meu senhor; porque o rei fez segundo a palavra do seu servo.

[[v10-14-23]]

^<<v10-14-23,23>>^ Levantou-se Joabe, foi a Gesur e trouxe Absalão a Jerusalém.

[[v10-14-24]]

^<<v10-14-24,24>>^ Disse o rei: Torne para a sua casa e não veja a minha face. Tornou, pois, Absalão para sua casa e não viu a face do rei.

[[v10-14-25]]

^<<v10-14-25,25>>^ Não havia, porém, em todo o Israel homem tão celebrado por sua beleza como Absalão; da planta do pé ao alto da cabeça, não havia nele defeito algum.

[[v10-14-26]]

^<<v10-14-26,26>>^ Quando cortava o cabelo (e isto se fazia no fim de cada ano, porquanto muito lhe pesava), seu peso era de duzentos siclos, segundo o peso real.

[[v10-14-27]]

^<<v10-14-27,27>>^ Também nasceram a Absalão três filhos e uma filha, cujo nome era Tamar; esta era mulher formosa à vista.

[[v10-14-28]]

^<<v10-14-28,28>>^ Tendo ficado Absalão dois anos em Jerusalém e sem ver a face do rei,

[[v10-14-29]]

^<<v10-14-29,29>>^ mandou ele chamar a Joabe, para o enviar ao rei; porém ele não quis vir. Mandou chamá-lo segunda vez, mas ainda não quis ele vir.

[[v10-14-30]]

^<<v10-14-30,30>>^ Então, disse aos seus servos: Vede ali o pedaço de campo de Joabe pegado ao meu, e tem cevada nele; ide e metei-lhe fogo. E os servos de Absalão meteram fogo nesse pedaço de campo.

[[v10-14-31]]

^<<v10-14-31,31>>^ Então, Joabe se levantou, e foi à casa de Absalão, e lhe disse: Por que meteram fogo os teus servos no pedaço de campo que é meu?

[[v10-14-32]]

^<<v10-14-32,32>>^ Respondeu Absalão a Joabe: Mandei chamar-te, dizendo: Vem cá, para que te envie ao rei, a dizer-lhe: Para que vim de Gesur? Melhor me fora estar ainda lá. Agora, pois, quero ver a face do rei; se há em mim alguma culpa, que me mate.

[[v10-14-33]]

^<<v10-14-33,33>>^ Então, Joabe foi ao rei e lho disse. Chamou o rei a Absalão, e este se lhe apresentou e inclinou-se sobre o rosto em terra, diante do rei. O rei beijou a Absalão.

'''

xref:010-2-samuel/010-2-samuel-013.adoc#v10-13-0[&#60; Capítulo Anterior] | <<v10-14-0,Topo>> | xref:010-2-samuel/010-2-samuel-015.adoc#v10-15-0[Próximo Capítulo &#62;]