include::./index.adoc[]

[[v10-15-0]]
=== 2 Samuel, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-15-1]]

^<<v10-15-1,1>>^ Depois disto, Absalão fez aparelhar para si um carro e cavalos e cinquenta homens que corressem adiante dele.

[[v10-15-2]]

^<<v10-15-2,2>>^ Levantando-se Absalão pela manhã, parava à entrada da porta; e a todo homem que tinha alguma demanda para vir ao rei a juízo, o chamava Absalão a si e lhe dizia: De que cidade és tu? Ele respondia: De tal tribo de Israel é teu servo.

[[v10-15-3]]

^<<v10-15-3,3>>^ Então, Absalão lhe dizia: Olha, a tua causa é boa e reta, porém não tens quem te ouça da parte do rei.

[[v10-15-4]]

^<<v10-15-4,4>>^ Dizia mais Absalão: Ah! Quem me dera ser juiz na terra, para que viesse a mim todo homem que tivesse demanda ou questão, para que lhe fizesse justiça!

[[v10-15-5]]

^<<v10-15-5,5>>^ Também, quando alguém se chegava para inclinar-se diante dele, ele estendia a mão, pegava-o e o beijava.

[[v10-15-6]]

^<<v10-15-6,6>>^ Desta maneira fazia Absalão a todo o Israel que vinha ao rei para juízo e, assim, ele furtava o coração dos homens de Israel.

[[v10-15-7]]

^<<v10-15-7,7>>^ Ao cabo de quatro anos, disse Absalão ao rei: Deixa-me ir a Hebrom cumprir o voto que fiz ao SENHOR.

[[v10-15-8]]

^<<v10-15-8,8>>^ Porque, morando em Gesur, na Síria, fez o teu servo um voto, dizendo: Se o SENHOR me fizer tornar a Jerusalém, prestarei culto ao SENHOR.

[[v10-15-9]]

^<<v10-15-9,9>>^ Então, lhe disse o rei: Vai-te em paz. Levantou-se, pois, e foi para Hebrom.

[[v10-15-10]]

^<<v10-15-10,10>>^ Enviou Absalão emissários secretos por todas as tribos de Israel, dizendo: Quando ouvirdes o som das trombetas, direis: Absalão é rei em Hebrom!

[[v10-15-11]]

^<<v10-15-11,11>>^ De Jerusalém foram com Absalão duzentos homens convidados, porém iam na sua simplicidade, porque nada sabiam daquele negócio.

[[v10-15-12]]

^<<v10-15-12,12>>^ Também Absalão mandou vir Aitofel, o gilonita, do conselho de Davi, da sua cidade de Gilo; enquanto ele oferecia os seus sacrifícios, tornou-se poderosa a conspirata, e crescia em número o povo que tomava o partido de Absalão.

[[v10-15-13]]

^<<v10-15-13,13>>^ Então, veio um mensageiro a Davi, dizendo: Todo o povo de Israel segue decididamente a Absalão.

[[v10-15-14]]

^<<v10-15-14,14>>^ Disse, pois, Davi a todos os seus homens que estavam com ele em Jerusalém: Levantai-vos, e fujamos, porque não poderemos salvar-nos de Absalão. Dai-vos pressa a sair, para que não nos alcance de súbito, lance sobre nós algum mal e fira a cidade a fio de espada.

[[v10-15-15]]

^<<v10-15-15,15>>^ Então, os homens do rei lhe disseram: Eis aqui os teus servos, para tudo quanto determinar o rei, nosso senhor.

[[v10-15-16]]

^<<v10-15-16,16>>^ Saiu o rei, e todos os de sua casa o seguiram; deixou, porém, o rei dez concubinas, para cuidarem da casa.

[[v10-15-17]]

^<<v10-15-17,17>>^ Tendo, pois, saído o rei com todo o povo após ele, pararam na última casa.

[[v10-15-18]]

^<<v10-15-18,18>>^ Todos os seus homens passaram ao pé dele; também toda a guarda real e todos os geteus, seiscentos homens que o seguiram de Gate, passaram adiante do rei.

[[v10-15-19]]

^<<v10-15-19,19>>^ Disse, pois, o rei a Itai, o geteu: Por que irias também tu conosco? Volta e fica-te com quem vier a ser o rei, porque és estrangeiro e desterrado de tua pátria.

[[v10-15-20]]

^<<v10-15-20,20>>^ Chegaste ontem, e já te levaria eu, hoje, conosco a vaguear, quando eu mesmo não sei para onde vou? Volta, pois, e faze voltar a teus irmãos contigo. E contigo sejam misericórdia e fidelidade.

[[v10-15-21]]

^<<v10-15-21,21>>^ Respondeu, porém, Itai ao rei: Tão certo como vive o SENHOR, e como vive o rei, meu senhor, no lugar em que estiver o rei, meu senhor, seja para morte seja para vida, lá estará também o teu servo.

[[v10-15-22]]

^<<v10-15-22,22>>^ Então, disse Davi a Itai: Vai e passa adiante. Assim, passou Itai, o geteu, e todos os seus homens, e todas as crianças que estavam com ele.

[[v10-15-23]]

^<<v10-15-23,23>>^ Toda a terra chorava em alta voz; e todo o povo e também o rei passaram o ribeiro de Cedrom, seguindo o caminho do deserto.

[[v10-15-24]]

^<<v10-15-24,24>>^ Eis que Abiatar subiu, e também Zadoque, e com este todos os levitas que levavam a arca da Aliança de Deus; puseram ali a arca de Deus, até que todo o povo acabou de sair da cidade.

[[v10-15-25]]

^<<v10-15-25,25>>^ Então, disse o rei a Zadoque: Torna a levar a arca de Deus à cidade. Se achar eu graça aos olhos do SENHOR, ele me fará voltar para lá e me deixará ver assim a arca como a sua habitação.

[[v10-15-26]]

^<<v10-15-26,26>>^ Se ele, porém, disser: Não tenho prazer em ti, eis-me aqui; faça de mim como melhor lhe parecer.

[[v10-15-27]]

^<<v10-15-27,27>>^ Disse mais o rei a Zadoque, o sacerdote: Ó vidente, tu e Abiatar, voltai em paz para a cidade, e convosco também vossos dois filhos, Aimaás, teu filho, e Jônatas, filho de Abiatar.

[[v10-15-28]]

^<<v10-15-28,28>>^ Olhai que me demorarei nos vaus do deserto até que me venham informações vossas.

[[v10-15-29]]

^<<v10-15-29,29>>^ Zadoque, pois, e Abiatar levaram a arca de Deus para Jerusalém e lá ficaram.

[[v10-15-30]]

^<<v10-15-30,30>>^ Seguiu Davi pela encosta das Oliveiras, subindo e chorando; tinha a cabeça coberta e caminhava descalço; todo o povo que ia com ele, de cabeça coberta, subiu chorando.

[[v10-15-31]]

^<<v10-15-31,31>>^ Então, fizeram saber a Davi, dizendo: Aitofel está entre os que conspiram com Absalão. Pelo que disse Davi: Ó SENHOR, peço-te que transtornes em loucura o conselho de Aitofel.

[[v10-15-32]]

^<<v10-15-32,32>>^ Ao chegar Davi ao cimo, onde se costuma adorar a Deus, eis que Husai, o arquita, veio encontrar-se com ele, de manto rasgado e terra sobre a cabeça.

[[v10-15-33]]

^<<v10-15-33,33>>^ Disse-lhe Davi: Se fores comigo, ser-me-ás pesado.

[[v10-15-34]]

^<<v10-15-34,34>>^ Porém, se voltares para a cidade e disseres a Absalão: Eu serei, ó rei, teu servo, como fui, dantes, servo de teu pai, assim, agora, serei teu servo, dissipar-me-ás, então, o conselho de Aitofel.

[[v10-15-35]]

^<<v10-15-35,35>>^ Tens lá contigo Zadoque e Abiatar, sacerdotes. Todas as coisas, pois, que ouvires da casa do rei farás saber a esses sacerdotes.

[[v10-15-36]]

^<<v10-15-36,36>>^ Lá estão com eles seus dois filhos, Aimaás, filho de Zadoque, e Jônatas, filho de Abiatar; por meio deles, me mandareis notícias de todas as coisas que ouvirdes.

[[v10-15-37]]

^<<v10-15-37,37>>^ Husai, pois, amigo de Davi, veio para a cidade, e Absalão entrou em Jerusalém.

'''

xref:010-2-samuel/010-2-samuel-014.adoc#v10-14-0[&#60; Capítulo Anterior] | <<v10-15-0,Topo>> | xref:010-2-samuel/010-2-samuel-016.adoc#v10-16-0[Próximo Capítulo &#62;]