include::./index.adoc[]

[[v10-3-0]]
=== 2 Samuel, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-3-1]]

^<<v10-3-1,1>>^ Durou muito tempo a guerra entre a casa de Saul e a casa de Davi; Davi se ia fortalecendo, porém os da casa de Saul se iam enfraquecendo.

[[v10-3-2]]

^<<v10-3-2,2>>^ Em Hebrom, nasceram filhos a Davi; o primogênito foi Amnom, de Ainoã, a jezreelita;

[[v10-3-3]]

^<<v10-3-3,3>>^ o segundo, Quileabe, de Abigail, viúva de Nabal, o carmelita; o terceiro, Absalão, filho de Maaca, filha de Talmai, rei de Gesur;

[[v10-3-4]]

^<<v10-3-4,4>>^ o quarto, Adonias, filho de Hagite; o quinto, Sefatias, filho de Abital;

[[v10-3-5]]

^<<v10-3-5,5>>^ o sexto, Itreão, de Eglá, mulher de Davi; estes nasceram a Davi em Hebrom.

[[v10-3-6]]

^<<v10-3-6,6>>^ Havendo guerra entre a casa de Saul e a casa de Davi, Abner se fez poderoso na casa de Saul.

[[v10-3-7]]

^<<v10-3-7,7>>^ Teve Saul uma concubina, cujo nome era Rispa, filha de Aiá. Perguntou Isbosete a Abner: Por que coabitaste com a concubina de meu pai?

[[v10-3-8]]

^<<v10-3-8,8>>^ Então, se irou muito Abner por causa das palavras de Isbosete e disse: Sou eu cabeça de cão para Judá? Ainda hoje faço beneficência à casa de Saul, teu pai, a seus irmãos e a seus amigos e te não entreguei nas mãos de Davi? Contudo, me queres, hoje, culpar por causa desta mulher.

[[v10-3-9]]

^<<v10-3-9,9>>^ Assim faça Deus segundo lhe parecer a Abner, se, como jurou o SENHOR a Davi, não fizer eu,

[[v10-3-10]]

^<<v10-3-10,10>>^ transferindo o reino da casa de Saul e estabelecendo o trono de Davi sobre Israel e sobre Judá, desde Dã até Berseba.

[[v10-3-11]]

^<<v10-3-11,11>>^ E nenhuma palavra pôde Isbosete responder a Abner, porque o temia.

[[v10-3-12]]

^<<v10-3-12,12>>^ Então, de sua parte ordenou Abner mensageiros a Davi, dizendo: De quem é a terra? Faze comigo aliança, e eu te ajudarei em fazer passar-te a ti todo o Israel.

[[v10-3-13]]

^<<v10-3-13,13>>^ Respondeu Davi: Bem, eu farei aliança contigo, porém uma coisa exijo: quando vieres a mim, não verás a minha face, se primeiro me não trouxeres a Mical, filha de Saul.

[[v10-3-14]]

^<<v10-3-14,14>>^ Também enviou Davi mensageiros a Isbosete, filho de Saul, dizendo: Dá-me de volta minha mulher Mical, que eu desposei por cem prepúcios de filisteus.

[[v10-3-15]]

^<<v10-3-15,15>>^ Então, Isbosete mandou tirá-la a seu marido, a Paltiel, filho de Laís.

[[v10-3-16]]

^<<v10-3-16,16>>^ Seu marido a acompanhou, caminhando e chorando após ela, até Baurim. Disse Abner: Vai-te, volta. E ele voltou.

[[v10-3-17]]

^<<v10-3-17,17>>^ Falou Abner com os anciãos de Israel, dizendo: Outrora, procuráveis que Davi reinasse sobre vós.

[[v10-3-18]]

^<<v10-3-18,18>>^ Fazei-o, pois, agora, porque o SENHOR falou a Davi, dizendo: Por intermédio de Davi, meu servo, livrarei o meu povo das mãos dos filisteus e das mãos de todos os seus inimigos.

[[v10-3-19]]

^<<v10-3-19,19>>^ Da mesma sorte falou também Abner aos ouvidos de Benjamim; e foi ainda dizer a Davi, em Hebrom, tudo o que agradava a Israel e a toda a casa de Benjamim.

[[v10-3-20]]

^<<v10-3-20,20>>^ Veio Abner ter com Davi, em Hebrom, e vinte homens, com ele; Davi ofereceu um banquete a Abner e aos homens que com ele vieram.

[[v10-3-21]]

^<<v10-3-21,21>>^ Então, disse Abner a Davi: Levantar-me-ei e irei para ajuntar todo o Israel ao rei, meu senhor, para fazerem aliança contigo; tu reinarás sobre tudo que desejar a tua alma. Assim, despediu Davi a Abner, e ele se foi em paz.

[[v10-3-22]]

^<<v10-3-22,22>>^ Eis que os servos de Davi e Joabe vieram de uma investida e traziam consigo grande despojo; Abner, porém, já não estava com Davi, em Hebrom, porque este o havia despedido, e ele se fora em paz.

[[v10-3-23]]

^<<v10-3-23,23>>^ Chegando, pois, Joabe e toda a tropa que vinha com ele, disseram-lhe: Abner, filho de Ner, veio ter com o rei, o qual o despediu, e ele se foi em paz.

[[v10-3-24]]

^<<v10-3-24,24>>^ Então, Joabe foi ao rei e disse: Que fizeste? Eis que Abner veio ter contigo; como, pois, o despediste, indo-se ele livremente?

[[v10-3-25]]

^<<v10-3-25,25>>^ Bem conheces Abner, filho de Ner. Veio para enganar-te, tomar conhecimento de tuas empresas e sondar todos os teus planos.

[[v10-3-26]]

^<<v10-3-26,26>>^ Retirando-se Joabe de Davi, enviou mensageiros após Abner, e o fizeram voltar desde o poço de Sirá, sem que Davi o soubesse.

[[v10-3-27]]

^<<v10-3-27,27>>^ Tornando, pois, Abner a Hebrom, Joabe o tomou à parte, no interior da porta, para lhe falar em segredo, e ali o feriu no abdômen, e ele morreu, agindo assim Joabe em vingança do sangue de seu irmão Asael.

[[v10-3-28]]

^<<v10-3-28,28>>^ Sabendo-o depois Davi, disse: Inocentes somos eu e o meu reino, para com o SENHOR, para sempre, do sangue de Abner, filho de Ner.

[[v10-3-29]]

^<<v10-3-29,29>>^ Caia este sangue sobre a cabeça de Joabe e sobre toda a casa de seu pai! Jamais falte da casa de Joabe quem tenha fluxo, quem seja leproso, quem se apoie em muleta, quem caia à espada, quem necessite de pão.

[[v10-3-30]]

^<<v10-3-30,30>>^ Joabe, pois, e seu irmão Abisai mataram Abner, por ter morto seu irmão Asael na peleja, em Gibeão.

[[v10-3-31]]

^<<v10-3-31,31>>^ Disse, pois, Davi a Joabe e a todo o povo que com ele estava: Rasgai as vossas vestes, cingi-vos de panos de saco e ide pranteando diante de Abner. E o rei Davi ia seguindo o féretro.

[[v10-3-32]]

^<<v10-3-32,32>>^ Sepultaram Abner em Hebrom; o rei levantou a voz e chorou junto da sepultura de Abner; chorou também todo o povo.

[[v10-3-33]]

^<<v10-3-33,33>>^ E o rei, pranteando a Abner, disse: Teria de morrer Abner como se fora um perverso?

[[v10-3-34]]

^<<v10-3-34,34>>^ As tuas mãos não estavam atadas, nem os teus pés, carregados de grilhões; caíste como os que caem diante dos filhos da maldade! E todo o povo chorou muito mais por ele.

[[v10-3-35]]

^<<v10-3-35,35>>^ Então, veio todo o povo fazer que Davi comesse pão, sendo ainda dia; porém Davi jurou, dizendo: Assim me faça Deus o que lhe aprouver, se eu provar pão ou alguma coisa antes do sol posto.

[[v10-3-36]]

^<<v10-3-36,36>>^ Todo o povo notou isso e lhe pareceu bem, assim como lhe pareceu bem tudo quanto o rei fez.

[[v10-3-37]]

^<<v10-3-37,37>>^ Todo o povo e todo o Israel, naquele mesmo dia, ficaram sabendo que não procedera do rei que matassem a Abner, filho de Ner.

[[v10-3-38]]

^<<v10-3-38,38>>^ Então, disse o rei aos seus homens: Não sabeis que, hoje, caiu em Israel um príncipe e um grande homem?

[[v10-3-39]]

^<<v10-3-39,39>>^ No presente, sou fraco, embora ungido rei; estes homens, filhos de Zeruia, são mais fortes do que eu. Retribua o SENHOR ao que fez mal segundo a sua maldade.

'''

xref:010-2-samuel/010-2-samuel-002.adoc#v10-2-0[&#60; Capítulo Anterior] | <<v10-3-0,Topo>> | xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[Próximo Capítulo &#62;]