include::./index.adoc[]

[[v10-20-0]]
=== 2 Samuel, 20
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-20-1]]

^<<v10-20-1,1>>^ Então, se achou ali, por acaso, um homem de Belial, cujo nome era Seba, filho de Bicri, homem de Benjamim, o qual tocou a trombeta e disse: Não fazemos parte de Davi, nem temos herança no filho de Jessé; cada um para as suas tendas, ó Israel.

[[v10-20-2]]

^<<v10-20-2,2>>^ Então, todos os homens de Israel se separaram de Davi e seguiram Seba, filho de Bicri; porém os homens de Judá se apegaram ao seu rei, conduzindo-o desde o Jordão até Jerusalém.

[[v10-20-3]]

^<<v10-20-3,3>>^ Vindo, pois, Davi para sua casa, a Jerusalém, tomou o rei as suas dez concubinas, que deixara para cuidar da casa, e as pôs em custódia, e as sustentou, porém não coabitou com elas; e estiveram encerradas até ao dia em que morreram, vivendo como viúvas.

[[v10-20-4]]

^<<v10-20-4,4>>^ Disse o rei a Amasa: Convoca-me, para dentro de três dias, os homens de Judá e apresenta-te aqui.

[[v10-20-5]]

^<<v10-20-5,5>>^ Partiu Amasa para convocar os homens de Judá; porém demorou-se além do tempo que lhe fora aprazado.

[[v10-20-6]]

^<<v10-20-6,6>>^ Então, disse Davi a Abisai: Mais mal, agora, nos fará Seba, o filho de Bicri, do que Absalão; pelo que toma tu os servos de teu senhor e persegue-o, para que não ache para si cidades fortificadas e nos escape.

[[v10-20-7]]

^<<v10-20-7,7>>^ Então, o perseguiram os homens de Joabe, a guarda real e todos os valentes; estes saíram de Jerusalém para perseguirem Seba, filho de Bicri.

[[v10-20-8]]

^<<v10-20-8,8>>^ Chegando eles, pois, à pedra grande que está junto a Gibeão, Amasa veio perante eles; trazia Joabe vestes militares e sobre elas um cinto, no qual, presa aos seus lombos, estava uma espada dentro da bainha; adiantando-se ele, fez cair a espada.

[[v10-20-9]]

^<<v10-20-9,9>>^ Disse Joabe a Amasa: Vais bem, meu irmão? E, com a mão direita, lhe pegou a barba, para o beijar.

[[v10-20-10]]

^<<v10-20-10,10>>^ Amasa não se importou com a espada que estava na mão de Joabe, de sorte que este o feriu com ela no abdômen e lhe derramou por terra as entranhas; não o feriu segunda vez, e morreu. Então, Joabe e Abisai, seu irmão, perseguiram a Seba, filho de Bicri.

[[v10-20-11]]

^<<v10-20-11,11>>^ Mas um, dentre os moços de Joabe, parou junto de Amasa e disse: Quem está do lado de Joabe e é por Davi, siga a Joabe.

[[v10-20-12]]

^<<v10-20-12,12>>^ Amasa se revolvia no seu sangue no meio do caminho; vendo o moço que todo o povo parava, desviou a Amasa do caminho para o campo e lançou sobre ele um manto; porque via que todo aquele que chegava a ele parava.

[[v10-20-13]]

^<<v10-20-13,13>>^ Uma vez afastado do caminho, todos os homens seguiram Joabe, para perseguirem Seba, filho de Bicri.

[[v10-20-14]]

^<<v10-20-14,14>>^ Seba passou por todas as tribos de Israel até Abel-Bete-Maaca; e apenas os beritas se ajuntaram todos e o seguiram.

[[v10-20-15]]

^<<v10-20-15,15>>^ Vieram Joabe e os homens, e o cercaram em Abel-Bete-Maaca, e levantaram contra a cidade um montão da altura do muro; e todo o povo que estava com Joabe trabalhava no muro para o derribar.

[[v10-20-16]]

^<<v10-20-16,16>>^ Então, uma mulher sábia gritou de dentro da cidade: Ouvi, ouvi; dizei a Joabe: Chega-te cá, para que eu fale contigo.

[[v10-20-17]]

^<<v10-20-17,17>>^ Chegando-se ele, perguntou-lhe a mulher: És tu Joabe? Respondeu: Eu sou. Ela lhe disse: Ouve as palavras de tua serva. Disse ele: Ouço.

[[v10-20-18]]

^<<v10-20-18,18>>^ Então, disse ela: Antigamente, se costumava dizer: Peça-se conselho em Abel; e assim davam cabo das questões.

[[v10-20-19]]

^<<v10-20-19,19>>^ Eu sou uma das pacíficas e das fiéis em Israel; e tu procuras destruir uma cidade e uma mãe em Israel; por que, pois, devorarias a herança do SENHOR?

[[v10-20-20]]

^<<v10-20-20,20>>^ Respondeu Joabe e disse: Longe, longe de mim que eu devore e destrua!

[[v10-20-21]]

^<<v10-20-21,21>>^ A coisa não é assim; porém um homem da região montanhosa de Efraim, cujo nome é Seba, filho de Bicri, levantou a mão contra o rei, contra Davi; entregai-me só este, e retirar-me-ei da cidade. Então, disse a mulher a Joabe: Eis que te será lançada a sua cabeça pelo muro.

[[v10-20-22]]

^<<v10-20-22,22>>^ E a mulher, na sua sabedoria, foi ter com todo o povo, e cortaram a cabeça de Seba, filho de Bicri, e a lançaram a Joabe. Então, tocou este a trombeta, e se retiraram da cidade, cada um para sua casa. E Joabe voltou a Jerusalém, a ter com o rei.

[[v10-20-23]]

^<<v10-20-23,23>>^ Joabe era comandante de todo o exército de Israel; e Benaia, filho de Joiada, da guarda real;

[[v10-20-24]]

^<<v10-20-24,24>>^ Adorão, dos que estavam sujeitos a trabalhos forçados; Josafá, filho de Ailude, era o cronista.

[[v10-20-25]]

^<<v10-20-25,25>>^ Seva, o escrivão; Zadoque e Abiatar, os sacerdotes;

[[v10-20-26]]

^<<v10-20-26,26>>^ e também Ira, o jairita, era ministro de Davi.

'''

xref:010-2-samuel/010-2-samuel-019.adoc#v10-19-0[&#60; Capítulo Anterior] | <<v10-20-0,Topo>> | xref:010-2-samuel/010-2-samuel-021.adoc#v10-21-0[Próximo Capítulo &#62;]