include::./index.adoc[]

[[v10-21-0]]
=== 2 Samuel, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-21-1]]

^<<v10-21-1,1>>^ Houve, em dias de Davi, uma fome de três anos consecutivos. Davi consultou ao SENHOR, e o SENHOR lhe disse: Há culpa de sangue sobre Saul e sobre a sua casa, porque ele matou os gibeonitas.

[[v10-21-2]]

^<<v10-21-2,2>>^ Então, chamou o rei os gibeonitas e lhes falou. Os gibeonitas não eram dos filhos de Israel, mas do resto dos amorreus; e os filhos de Israel lhes tinham jurado poupá-los, porém Saul procurou destruí-los no seu zelo pelos filhos de Israel e de Judá.

[[v10-21-3]]

^<<v10-21-3,3>>^ Perguntou Davi aos gibeonitas: Que quereis que eu vos faça? E que resgate vos darei, para que abençoeis a herança do SENHOR?

[[v10-21-4]]

^<<v10-21-4,4>>^ Então, os gibeonitas lhe disseram: Não é por prata nem ouro que temos questão com Saul e com sua casa; nem tampouco pretendemos matar pessoa alguma em Israel. Disse Davi: Que é, pois, que quereis que vos faça?

[[v10-21-5]]

^<<v10-21-5,5>>^ Responderam ao rei: Quanto ao homem que nos destruiu e procurou que fôssemos assolados, sem que pudéssemos subsistir em limite algum de Israel,

[[v10-21-6]]

^<<v10-21-6,6>>^ de seus filhos se nos deem sete homens, para que os enforquemos ao SENHOR, em Gibeá de Saul, o eleito do SENHOR. Disse o rei: Eu os darei.

[[v10-21-7]]

^<<v10-21-7,7>>^ Porém o rei poupou a Mefibosete, filho de Jônatas, filho de Saul, por causa do juramento ao SENHOR, que entre eles houvera, entre Davi e Jônatas, filho de Saul.

[[v10-21-8]]

^<<v10-21-8,8>>^ Porém tomou o rei os dois filhos de Rispa, filha de Aiá, que tinha tido de Saul, a saber, a Armoni e a Mefibosete, como também os cinco filhos de Merabe, filha de Saul, que tivera de Adriel, filho de Barzilai, meolatita;

[[v10-21-9]]

^<<v10-21-9,9>>^ e os entregou nas mãos dos gibeonitas, os quais os enforcaram no monte, perante o SENHOR; caíram os sete juntamente. Foram mortos nos dias da ceifa, nos primeiros dias, no princípio da ceifa da cevada.

[[v10-21-10]]

^<<v10-21-10,10>>^ Então, Rispa, filha de Aiá, tomou um pano de saco e o estendeu para si sobre uma penha, desde o princípio da ceifa até que sobre eles caiu água do céu; e não deixou que as aves do céu se aproximassem deles de dia, nem os animais do campo, de noite.

[[v10-21-11]]

^<<v10-21-11,11>>^ Foi dito a Davi o que fizera Rispa, filha de Aiá e concubina de Saul.

[[v10-21-12]]

^<<v10-21-12,12>>^ Então, foi Davi e tomou os ossos de Saul e os ossos de Jônatas, seu filho, dos moradores de Jabes-Gileade, os quais os furtaram da praça de Bete-Seã, onde os filisteus os tinham pendurado, no dia em que feriram Saul em Gilboa.

[[v10-21-13]]

^<<v10-21-13,13>>^ Dali, transportou os ossos de Saul e os ossos de Jônatas, seu filho; e ajuntaram também os ossos dos enforcados.

[[v10-21-14]]

^<<v10-21-14,14>>^ Enterraram os ossos de Saul e de Jônatas, seu filho, na terra de Benjamim, em Zela, na sepultura de Quis, seu pai. Fizeram tudo o que o rei ordenara. Depois disto, Deus se tornou favorável para com a terra.

[[v10-21-15]]

^<<v10-21-15,15>>^ De novo, fizeram os filisteus guerra contra Israel. Desceu Davi com os seus homens, e pelejaram contra os filisteus, ficando Davi mui fatigado.

[[v10-21-16]]

^<<v10-21-16,16>>^ Isbi-Benobe descendia dos gigantes; o peso do bronze de sua lança era de trezentos siclos, e estava cingido de uma armadura nova; este intentou matar a Davi.

[[v10-21-17]]

^<<v10-21-17,17>>^ Porém Abisai, filho de Zeruia, socorreu-o, feriu o filisteu e o matou; então, os homens de Davi lhe juraram, dizendo: Nunca mais sairás conosco à peleja, para que não apagues a lâmpada de Israel.

[[v10-21-18]]

^<<v10-21-18,18>>^ Depois disto, houve ainda, em Gobe, outra peleja contra os filisteus; então, Sibecai, o husatita, feriu a Safe, que era descendente dos gigantes.

[[v10-21-19]]

^<<v10-21-19,19>>^ Houve ainda, em Gobe, outra peleja contra os filisteus; e Elanã, filho de Jaaré-Oregim, o belemita, feriu a Golias, o geteu, cuja lança tinha a haste como eixo de tecelão.

[[v10-21-20]]

^<<v10-21-20,20>>^ Houve ainda outra peleja; esta foi em Gate, onde estava um homem de grande estatura, que tinha em cada mão e em cada pé seis dedos, vinte e quatro ao todo; também este descendia dos gigantes.

[[v10-21-21]]

^<<v10-21-21,21>>^ Quando ele injuriava a Israel, Jônatas, filho de Simeia, irmão de Davi, o feriu.

[[v10-21-22]]

^<<v10-21-22,22>>^ Estes quatro nasceram dos gigantes em Gate; e caíram pela mão de Davi e pela mão de seus homens.

'''

xref:010-2-samuel/010-2-samuel-020.adoc#v10-20-0[&#60; Capítulo Anterior] | <<v10-21-0,Topo>> | xref:010-2-samuel/010-2-samuel-022.adoc#v10-22-0[Próximo Capítulo &#62;]