include::./index.adoc[]

[[v10-22-0]]
=== 2 Samuel, 22
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-22-1]]

^<<v10-22-1,1>>^ Falou Davi ao SENHOR as palavras deste cântico, no dia em que o SENHOR o livrou das mãos de todos os seus inimigos e das mãos de Saul.

[[v10-22-2]]

^<<v10-22-2,2>>^ E disse: O SENHOR é a minha rocha, a minha cidadela, o meu libertador;

[[v10-22-3]]

^<<v10-22-3,3>>^ o meu Deus, o meu rochedo em que me refugio; o meu escudo, a força da minha salvação, o meu baluarte e o meu refúgio. Ó Deus, da violência tu me salvas.

[[v10-22-4]]

^<<v10-22-4,4>>^ Invoco o SENHOR, digno de ser louvado, e serei salvo dos meus inimigos.

[[v10-22-5]]

^<<v10-22-5,5>>^ Porque ondas de morte me cercaram, torrentes de impiedade me impuseram terror;

[[v10-22-6]]

^<<v10-22-6,6>>^ cadeias infernais me cingiram, e tramas de morte me surpreenderam.

[[v10-22-7]]

^<<v10-22-7,7>>^ Na minha angústia, invoquei o SENHOR, clamei a meu Deus; ele, do seu templo, ouviu a minha voz, e o meu clamor chegou aos seus ouvidos.

[[v10-22-8]]

^<<v10-22-8,8>>^ Então, a terra se abalou e tremeu, vacilaram também os fundamentos dos céus e se estremeceram, porque ele se indignou.

[[v10-22-9]]

^<<v10-22-9,9>>^ Das suas narinas, subiu fumaça, e, da sua boca, fogo devorador; dele saíram carvões, em chama.

[[v10-22-10]]

^<<v10-22-10,10>>^ Baixou ele os céus, e desceu, e teve sob os pés densa escuridão.

[[v10-22-11]]

^<<v10-22-11,11>>^ Cavalgava um querubim e voou; e foi visto sobre as asas do vento.

[[v10-22-12]]

^<<v10-22-12,12>>^ Por pavilhão pôs, ao redor de si, trevas, ajuntamento de águas, nuvens dos céus.

[[v10-22-13]]

^<<v10-22-13,13>>^ Do resplendor que diante dele havia, brasas de fogo se acenderam.

[[v10-22-14]]

^<<v10-22-14,14>>^ Trovejou o SENHOR desde os céus; o Altíssimo levantou a sua voz.

[[v10-22-15]]

^<<v10-22-15,15>>^ Despediu setas, e espalhou os meus inimigos, e raios, e os desbaratou.

[[v10-22-16]]

^<<v10-22-16,16>>^ Então, se viu o leito das águas, e se descobriram os fundamentos do mundo, pela repreensão do SENHOR, pelo iroso resfolgar das suas narinas.

[[v10-22-17]]

^<<v10-22-17,17>>^ Do alto, me estendeu ele a mão e me tomou; tirou-me das muitas águas.

[[v10-22-18]]

^<<v10-22-18,18>>^ Livrou-me do forte inimigo, dos que me aborreciam, porque eram mais poderosos do que eu.

[[v10-22-19]]

^<<v10-22-19,19>>^ Assaltaram-me no dia da minha calamidade, mas o SENHOR me serviu de amparo.

[[v10-22-20]]

^<<v10-22-20,20>>^ Trouxe-me para um lugar espaçoso; livrou-me, porque ele se agradou de mim.

[[v10-22-21]]

^<<v10-22-21,21>>^ Retribuiu-me o SENHOR segundo a minha justiça, recompensou-me conforme a pureza das minhas mãos.

[[v10-22-22]]

^<<v10-22-22,22>>^ Pois tenho guardado os caminhos do Senhor e não me apartei perversamente do meu Deus.

[[v10-22-23]]

^<<v10-22-23,23>>^ Porque todos os seus juízos me estão presentes, e dos seus estatutos não me desviei.

[[v10-22-24]]

^<<v10-22-24,24>>^ Também fui inculpável para com ele e me guardei da iniquidade.

[[v10-22-25]]

^<<v10-22-25,25>>^ Daí, retribuir-me o SENHOR segundo a minha justiça, segundo a minha pureza diante dos seus olhos.

[[v10-22-26]]

^<<v10-22-26,26>>^ Para com o benigno, benigno te mostras; com o íntegro, também íntegro.

[[v10-22-27]]

^<<v10-22-27,27>>^ Com o puro, puro te mostras; com o perverso, inflexível.

[[v10-22-28]]

^<<v10-22-28,28>>^ Tu salvas o povo humilde, mas, com um lance de vista, abates os altivos.

[[v10-22-29]]

^<<v10-22-29,29>>^ Tu, SENHOR, és a minha lâmpada; o SENHOR derrama luz nas minhas trevas.

[[v10-22-30]]

^<<v10-22-30,30>>^ Pois contigo desbarato exércitos, com o meu Deus, salto muralhas.

[[v10-22-31]]

^<<v10-22-31,31>>^ O caminho de Deus é perfeito; a palavra do SENHOR é provada; ele é escudo para todos os que nele se refugiam.

[[v10-22-32]]

^<<v10-22-32,32>>^ Pois quem é Deus, senão o SENHOR? E quem é rochedo, senão o nosso Deus?

[[v10-22-33]]

^<<v10-22-33,33>>^ Deus é a minha fortaleza e a minha força e ele perfeitamente desembaraça o meu caminho.

[[v10-22-34]]

^<<v10-22-34,34>>^ Ele deu a meus pés a ligeireza das corças e me firmou nas minhas alturas.

[[v10-22-35]]

^<<v10-22-35,35>>^ Ele adestrou as minhas mãos para o combate, de sorte que os meus braços vergaram um arco de bronze.

[[v10-22-36]]

^<<v10-22-36,36>>^ Também me deste o escudo do teu salvamento, e a tua clemência me engrandeceu.

[[v10-22-37]]

^<<v10-22-37,37>>^ Alongaste sob meus passos o caminho, e os meus pés não vacilaram.

[[v10-22-38]]

^<<v10-22-38,38>>^ Persegui os meus inimigos, e os derrotei, e só voltei depois de haver dado cabo deles.

[[v10-22-39]]

^<<v10-22-39,39>>^ Acabei com eles, esmagando-os a tal ponto, que não puderam levantar-se; caíram sob meus pés.

[[v10-22-40]]

^<<v10-22-40,40>>^ Pois de força me cingiste para o combate e me submeteste os que se levantaram contra mim.

[[v10-22-41]]

^<<v10-22-41,41>>^ Também puseste em fuga os meus inimigos, e os que me odiaram, eu os exterminei.

[[v10-22-42]]

^<<v10-22-42,42>>^ Olharam, mas ninguém lhes acudiu, sim, para o SENHOR, mas ele não respondeu.

[[v10-22-43]]

^<<v10-22-43,43>>^ Então, os moí como o pó da terra; esmaguei-os e, como a lama das ruas, os amassei.

[[v10-22-44]]

^<<v10-22-44,44>>^ Das contendas do meu povo me livraste e me fizeste cabeça das nações; povo que não conheci me serviu.

[[v10-22-45]]

^<<v10-22-45,45>>^ Os estrangeiros se me sujeitaram; ouvindo a minha voz, me obedeceram.

[[v10-22-46]]

^<<v10-22-46,46>>^ Sumiram-se os estrangeiros e das suas fortificações saíram espavoridos.

[[v10-22-47]]

^<<v10-22-47,47>>^ Vive o SENHOR, e bendita seja a minha Rocha! Exaltado seja o meu Deus, a Rocha da minha salvação!

[[v10-22-48]]

^<<v10-22-48,48>>^ O Deus que por mim tomou vingança e me submeteu povos;

[[v10-22-49]]

^<<v10-22-49,49>>^ o Deus que me tirou dentre os meus inimigos; sim, tu que me exaltaste acima dos meus adversários e me livraste do homem violento.

[[v10-22-50]]

^<<v10-22-50,50>>^ Celebrar-te-ei, pois, entre as nações, ó SENHOR, e cantarei louvores ao teu nome.

[[v10-22-51]]

^<<v10-22-51,51>>^ É ele quem dá grandes vitórias ao seu rei e usa de benignidade para com o seu ungido, com Davi e sua posteridade, para sempre.

'''

xref:010-2-samuel/010-2-samuel-021.adoc#v10-21-0[&#60; Capítulo Anterior] | <<v10-22-0,Topo>> | xref:010-2-samuel/010-2-samuel-023.adoc#v10-23-0[Próximo Capítulo &#62;]