include::./index.adoc[]

[[v10-24-0]]
=== 2 Samuel, 24
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-24-1]]

^<<v10-24-1,1>>^ Tornou a ira do SENHOR a acender-se contra os israelitas, e ele incitou a Davi contra eles, dizendo: Vai, levanta o censo de Israel e de Judá.

[[v10-24-2]]

^<<v10-24-2,2>>^ Disse, pois, o rei a Joabe, comandante do seu exército: Percorre todas as tribos de Israel, de Dã até Berseba, e levanta o censo do povo, para que eu saiba o seu número.

[[v10-24-3]]

^<<v10-24-3,3>>^ Então, disse Joabe ao rei: Ora, multiplique o SENHOR, teu Deus, a este povo cem vezes mais, e o rei, meu senhor, o veja; mas por que tem prazer nisto o rei, meu senhor?

[[v10-24-4]]

^<<v10-24-4,4>>^ Porém a palavra do rei prevaleceu contra Joabe e contra os chefes do exército; saiu, pois, Joabe com os chefes do exército da presença do rei, a levantar o censo do povo de Israel.

[[v10-24-5]]

^<<v10-24-5,5>>^ Tendo eles passado o Jordão, acamparam-se em Aroer, à direita da cidade que está no meio do vale de Gade, e foram a Jazer.

[[v10-24-6]]

^<<v10-24-6,6>>^ Daqui foram a Gileade e chegaram até Cades, na terra dos heteus; seguiram a Dã-Jaã e viraram-se para Sidom;

[[v10-24-7]]

^<<v10-24-7,7>>^ chegaram à fortaleza de Tiro e a todas as cidades dos heveus e dos cananeus, donde saíram para o Neguebe de Judá, a Berseba.

[[v10-24-8]]

^<<v10-24-8,8>>^ Assim, percorreram toda a terra e, ao cabo de nove meses e vinte dias, chegaram a Jerusalém.

[[v10-24-9]]

^<<v10-24-9,9>>^ Deu Joabe ao rei o recenseamento do povo: havia em Israel oitocentos mil homens de guerra, que puxavam da espada; e em Judá eram quinhentos mil.

[[v10-24-10]]

^<<v10-24-10,10>>^ Sentiu Davi bater-lhe o coração, depois de haver recenseado o povo, e disse ao SENHOR: Muito pequei no que fiz; porém, agora, ó SENHOR, peço-te que perdoes a iniquidade do teu servo; porque procedi mui loucamente.

[[v10-24-11]]

^<<v10-24-11,11>>^ Ao levantar-se Davi pela manhã, veio a palavra do SENHOR ao profeta Gade, vidente de Davi, dizendo:

[[v10-24-12]]

^<<v10-24-12,12>>^ Vai e dize a Davi: Assim diz o SENHOR: Três coisas te ofereço; escolhe uma delas, para que ta faça.

[[v10-24-13]]

^<<v10-24-13,13>>^ Veio, pois, Gade a Davi e lho fez saber, dizendo: Queres que sete anos de fome te venham à tua terra? Ou que, por três meses, fujas diante de teus inimigos, e eles te persigam? Ou que, por três dias, haja peste na tua terra? Delibera, agora, e vê que resposta hei de dar ao que me enviou.

[[v10-24-14]]

^<<v10-24-14,14>>^ Então, disse Davi a Gade: Estou em grande angústia; porém caiamos nas mãos do SENHOR, porque muitas são as suas misericórdias; mas, nas mãos dos homens, não caia eu.

[[v10-24-15]]

^<<v10-24-15,15>>^ Então, enviou o SENHOR a peste a Israel, desde a manhã até ao tempo que determinou; e, de Dã até Berseba, morreram setenta mil homens do povo.

[[v10-24-16]]

^<<v10-24-16,16>>^ Estendendo, pois, o Anjo do SENHOR a mão sobre Jerusalém, para a destruir, arrependeu-se o SENHOR do mal e disse ao Anjo que fazia a destruição entre o povo: Basta, retira a mão. O Anjo estava junto à eira de Araúna, o jebuseu.

[[v10-24-17]]

^<<v10-24-17,17>>^ Vendo Davi ao Anjo que feria o povo, falou ao SENHOR e disse: Eu é que pequei, eu é que procedi perversamente; porém estas ovelhas que fizeram? Seja, pois, a tua mão contra mim e contra a casa de meu pai.

[[v10-24-18]]

^<<v10-24-18,18>>^ Naquele mesmo dia, veio Gade ter com Davi e lhe disse: Sobe, levanta ao SENHOR um altar na eira de Araúna, o jebuseu.

[[v10-24-19]]

^<<v10-24-19,19>>^ Davi subiu segundo a palavra de Gade, como o SENHOR lhe havia ordenado.

[[v10-24-20]]

^<<v10-24-20,20>>^ Olhou Araúna do alto e, vendo que vinham para ele o rei e os seus homens, saiu e se inclinou diante do rei, com o rosto em terra.

[[v10-24-21]]

^<<v10-24-21,21>>^ E perguntou: Por que vem o rei, meu senhor, ao seu servo? Respondeu Davi: Para comprar de ti esta eira, a fim de edificar nela um altar ao SENHOR, para que cesse a praga de sobre o povo.

[[v10-24-22]]

^<<v10-24-22,22>>^ Então, disse Araúna a Davi: Tome e ofereça o rei, meu senhor, o que bem lhe parecer; eis aí os bois para o holocausto, e os trilhos, e a apeiragem dos bois para a lenha.

[[v10-24-23]]

^<<v10-24-23,23>>^ Tudo isto, ó rei, Araúna oferece ao rei; e ajuntou: Que o SENHOR, teu Deus, te seja propício.

[[v10-24-24]]

^<<v10-24-24,24>>^ Porém o rei disse a Araúna: Não, mas eu to comprarei pelo devido preço, porque não oferecerei ao SENHOR, meu Deus, holocaustos que não me custem nada. Assim, Davi comprou a eira e pelos bois pagou cinquenta siclos de prata.

[[v10-24-25]]

^<<v10-24-25,25>>^ Edificou ali Davi ao SENHOR um altar e apresentou holocaustos e ofertas pacíficas. Assim, o SENHOR se tornou favorável para com a terra, e a praga cessou de sobre Israel.

'''

xref:010-2-samuel/010-2-samuel-023.adoc#v10-23-0[&#60; Capítulo Anterior] | <<v10-24-0,Topo>> | xref:011-1-reis/011-1-reis-001.adoc#v11-1-0[Próximo Capítulo &#62;]