include::./index.adoc[]

[[v10-18-0]]
=== 2 Samuel, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-18-1]]

^<<v10-18-1,1>>^ Contou Davi o povo que tinha consigo e pôs sobre eles capitães de mil e capitães de cem.

[[v10-18-2]]

^<<v10-18-2,2>>^ Davi enviou o povo: um terço sob o comando de Joabe, outro terço sob o de Abisai, filho de Zeruia e irmão de Joabe, e o outro terço sob o de Itai, o geteu. Disse o rei ao povo: Eu também sairei convosco.

[[v10-18-3]]

^<<v10-18-3,3>>^ Respondeu, porém, o povo: Não sairás, porque, se formos obrigados a fugir, não se importarão conosco, nem ainda que metade de nós morra, pois tu vales por dez mil de nós. Melhor será que da cidade nos prestes socorro.

[[v10-18-4]]

^<<v10-18-4,4>>^ Tornou-lhes Davi: O que vos agradar, isso farei. Pôs-se o rei ao lado da porta, e todo o povo saiu a centenas e a milhares.

[[v10-18-5]]

^<<v10-18-5,5>>^ Deu ordem o rei a Joabe, a Abisai e a Itai, dizendo: Tratai com brandura o jovem Absalão, por amor de mim. Todo o povo ouviu quando o rei dava a ordem a todos os capitães acerca de Absalão.

[[v10-18-6]]

^<<v10-18-6,6>>^ Saiu, pois, o povo ao campo, a encontrar-se com Israel, e deu-se a batalha no bosque de Efraim.

[[v10-18-7]]

^<<v10-18-7,7>>^ Ali, foi o povo de Israel batido diante dos servos de Davi; e, naquele mesmo dia, houve ali grande derrota, com a perda de vinte mil homens.

[[v10-18-8]]

^<<v10-18-8,8>>^ Porque aí se estendeu a batalha por toda aquela região; e o bosque, naquele dia, consumiu mais gente do que a espada.

[[v10-18-9]]

^<<v10-18-9,9>>^ Indo Absalão montado no seu mulo, encontrou-se com os homens de Davi; entrando o mulo debaixo dos ramos espessos de um carvalho, Absalão, preso nele pela cabeça, ficou pendurado entre o céu e a terra; e o mulo, que ele montava, passou adiante.

[[v10-18-10]]

^<<v10-18-10,10>>^ Vendo isto um homem, fez saber a Joabe e disse: Vi Absalão pendurado num carvalho.

[[v10-18-11]]

^<<v10-18-11,11>>^ Então, disse Joabe ao homem que lho fizera saber: Viste-o! Por que logo não o feriste ali, derrubando-o por terra? E forçoso me seria dar-te dez moedas de prata e um cinto.

[[v10-18-12]]

^<<v10-18-12,12>>^ Disse, porém, o homem a Joabe: Ainda que me pesassem nas mãos mil moedas de prata, não estenderia a mão contra o filho do rei, pois bem ouvimos que o rei te deu ordem a ti, a Abisai e a Itai, dizendo: Guardai-me o jovem Absalão.

[[v10-18-13]]

^<<v10-18-13,13>>^ Se eu tivesse procedido traiçoeiramente contra a vida dele, nada disso se esconderia ao rei, e tu mesmo te oporias.

[[v10-18-14]]

^<<v10-18-14,14>>^ Então, disse Joabe: Não devo perder tempo, assim, contigo. Tomou três dardos e traspassou com eles o coração de Absalão, estando ele ainda vivo no meio do carvalho.

[[v10-18-15]]

^<<v10-18-15,15>>^ Cercaram-no dez jovens, que levavam as armas de Joabe, e feriram a Absalão, e o mataram.

[[v10-18-16]]

^<<v10-18-16,16>>^ Então, tocou Joabe a trombeta, e o povo voltou de perseguir a Israel, porque Joabe deteve o povo.

[[v10-18-17]]

^<<v10-18-17,17>>^ Levaram Absalão, e o lançaram no bosque, numa grande cova, e levantaram sobre ele mui grande montão de pedras; todo o Israel fugiu, cada um para a sua casa.

[[v10-18-18]]

^<<v10-18-18,18>>^ Ora, Absalão, quando ainda vivia, levantara para si uma coluna, que está no vale do Rei, porque dizia: Filho nenhum tenho para conservar a memória do meu nome; e deu o seu próprio nome à coluna; pelo que até hoje se chama o Monumento de Absalão.

[[v10-18-19]]

^<<v10-18-19,19>>^ Então, disse Aimaás, filho de Zadoque: Deixa-me correr e dar notícia ao rei de que já o SENHOR o vingou do poder de seus inimigos.

[[v10-18-20]]

^<<v10-18-20,20>>^ Mas Joabe lhe disse: Tu não serás, hoje, o portador de novas, porém outro dia o serás; hoje, não darás a nova, porque é morto o filho do rei.

[[v10-18-21]]

^<<v10-18-21,21>>^ Disse Joabe ao etíope: Vai tu e dize ao rei o que viste. Inclinou-se a Joabe e correu.

[[v10-18-22]]

^<<v10-18-22,22>>^ Prosseguiu Aimaás, filho de Zadoque, e disse a Joabe: Seja o que for, deixa-me também correr após o etíope. Disse Joabe: Para que, agora, correrias tu, meu filho, pois não terás recompensa das novas?

[[v10-18-23]]

^<<v10-18-23,23>>^ Seja o que for, tornou Aimaás, correrei. Então, Joabe lhe disse: Corre. Aimaás correu pelo caminho da planície e passou o etíope.

[[v10-18-24]]

^<<v10-18-24,24>>^ Davi estava assentado entre as duas portas da entrada; subiu a sentinela ao terraço da porta sobre o muro e, levantando os olhos, viu que um homem chegava correndo só.

[[v10-18-25]]

^<<v10-18-25,25>>^ Gritou, pois, a sentinela e o disse ao rei. O rei respondeu: Se vem só, traz boas notícias. E vinha andando e chegando.

[[v10-18-26]]

^<<v10-18-26,26>>^ Viu a sentinela outro homem que corria; então, gritou para a porta e disse: Eis que vem outro homem correndo só. Então, disse o rei: Também este traz boas-novas.

[[v10-18-27]]

^<<v10-18-27,27>>^ Disse mais a sentinela: Vejo o correr do primeiro; parece ser o correr de Aimaás, filho de Zadoque. Então, disse o rei: Este homem é de bem e trará boas-novas.

[[v10-18-28]]

^<<v10-18-28,28>>^ Gritou Aimaás e disse ao rei: Paz! Inclinou-se ao rei, com o rosto em terra, e disse: Bendito seja o SENHOR, teu Deus, que nos entregou os homens que levantaram a mão contra o rei, meu senhor.

[[v10-18-29]]

^<<v10-18-29,29>>^ Então, perguntou o rei: Vai bem o jovem Absalão? Respondeu Aimaás: Vi um grande alvoroço, quando Joabe mandou o teu servo, ó rei, porém não sei o que era.

[[v10-18-30]]

^<<v10-18-30,30>>^ Disse o rei: Põe-te ao lado e espera aqui. Ele se pôs e esperou.

[[v10-18-31]]

^<<v10-18-31,31>>^ Chegou o etíope e disse: Boas-novas ao rei, meu senhor. Hoje, o SENHOR te vingou do poder de todos os que se levantaram contra ti.

[[v10-18-32]]

^<<v10-18-32,32>>^ Então, disse o rei ao etíope: Vai bem o jovem Absalão? Respondeu o etíope: Sejam como aquele os inimigos do rei, meu senhor, e todos os que se levantam contra ti para o mal.

[[v10-18-33]]

^<<v10-18-33,33>>^ Então, o rei, profundamente comovido, subiu à sala que estava por cima da porta e chorou; e, andando, dizia: Meu filho Absalão, meu filho, meu filho Absalão! Quem me dera que eu morrera por ti, Absalão, meu filho, meu filho!

'''

xref:010-2-samuel/010-2-samuel-017.adoc#v10-17-0[&#60; Capítulo Anterior] | <<v10-18-0,Topo>> | xref:010-2-samuel/010-2-samuel-019.adoc#v10-19-0[Próximo Capítulo &#62;]