include::./index.adoc[]

[[v10-19-0]]
=== 2 Samuel, 19
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-19-1]]

^<<v10-19-1,1>>^ Disseram a Joabe: Eis que o rei anda chorando e lastima-se por Absalão.

[[v10-19-2]]

^<<v10-19-2,2>>^ Então, a vitória se tornou, naquele mesmo dia, em luto para todo o povo; porque, naquele dia, o povo ouvira dizer: O rei está de luto por causa de seu filho.

[[v10-19-3]]

^<<v10-19-3,3>>^ Naquele mesmo dia, entrou o povo às furtadelas na cidade, como o faz quando foge envergonhado da batalha.

[[v10-19-4]]

^<<v10-19-4,4>>^ Tendo o rei coberto o rosto, exclamava em alta voz: Meu filho Absalão, Absalão, meu filho, meu filho!

[[v10-19-5]]

^<<v10-19-5,5>>^ Então, Joabe entrou na casa do rei e lhe disse: Hoje, envergonhaste a face de todos os teus servos, que livraram, hoje, a tua vida, e a vida de teus filhos, e de tuas filhas, e a vida de tuas mulheres, e de tuas concubinas,

[[v10-19-6]]

^<<v10-19-6,6>>^ amando tu os que te aborrecem e aborrecendo aos que te amam; porque, hoje, dás a entender que nada valem para contigo príncipes e servos; porque entendo, agora, que, se Absalão vivesse e todos nós, hoje, fôssemos mortos, então, estarias contente.

[[v10-19-7]]

^<<v10-19-7,7>>^ Levanta-te, agora, sai e fala segundo o coração de teus servos. Juro pelo SENHOR que, se não saíres, nem um só homem ficará contigo esta noite; e maior mal te será isto do que todo o mal que tem vindo sobre ti desde a tua mocidade até agora.

[[v10-19-8]]

^<<v10-19-8,8>>^ Então, o rei se levantou e se assentou à porta, e o fizeram saber a todo o povo, dizendo: Eis que o rei está assentado à porta. Veio, pois, todo o povo apresentar-se diante do rei. Ora, Israel havia fugido, cada um para a sua tenda.

[[v10-19-9]]

^<<v10-19-9,9>>^ Todo o povo, em todas as tribos de Israel, andava altercando entre si, dizendo: O rei nos tirou das mãos de nossos inimigos, livrou-nos das mãos dos filisteus e, agora, fugiu da terra por causa de Absalão.

[[v10-19-10]]

^<<v10-19-10,10>>^ Absalão, a quem ungimos sobre nós, já morreu na peleja; agora, pois, por que vos calais e não fazeis voltar o rei?

[[v10-19-11]]

^<<v10-19-11,11>>^ Então, o rei Davi mandou dizer a Zadoque e a Abiatar, sacerdotes: Falai aos anciãos de Judá: Por que seríeis vós os últimos em tornar a trazer o rei para a sua casa, visto que aquilo que todo o Israel dizia já chegou ao rei, até à sua casa?

[[v10-19-12]]

^<<v10-19-12,12>>^ Vós sois meus irmãos, sois meu osso e minha carne; por que, pois, seríeis os últimos em tornar a trazer o rei?

[[v10-19-13]]

^<<v10-19-13,13>>^ Dizei a Amasa: Não és tu meu osso e minha carne? Deus me faça o que lhe aprouver, se não vieres a ser para sempre comandante do meu exército, em lugar de Joabe.

[[v10-19-14]]

^<<v10-19-14,14>>^ Com isto moveu o rei o coração de todos os homens de Judá, como se fora um só homem, e mandaram dizer-lhe: Volta, ó rei, tu e todos os teus servos.

[[v10-19-15]]

^<<v10-19-15,15>>^ Então, o rei voltou e chegou ao Jordão; Judá foi a Gilgal, para encontrar-se com o rei, a fim de fazê-lo passar o Jordão.

[[v10-19-16]]

^<<v10-19-16,16>>^ Apressou-se Simei, filho de Gera, benjamita, que era de Baurim, e desceu com os homens de Judá a encontrar-se com o rei Davi.

[[v10-19-17]]

^<<v10-19-17,17>>^ E, com ele, mil homens de Benjamim, como também Ziba, servo da casa de Saul, acompanhado de seus quinze filhos e seus vinte servos, e meteram-se pelo Jordão à vista do rei

[[v10-19-18]]

^<<v10-19-18,18>>^ e o atravessaram, para fazerem passar a casa real e para fazerem o que lhe era agradável. Então, Simei, filho de Gera, prostrou-se diante do rei, quando este ia passar o Jordão,

[[v10-19-19]]

^<<v10-19-19,19>>^ e lhe disse: Não me imputes, senhor, a minha culpa e não te lembres do que tão perversamente fez teu servo, no dia em que o rei, meu senhor, saiu de Jerusalém; não o conserves, ó rei, em teu coração.

[[v10-19-20]]

^<<v10-19-20,20>>^ Porque eu, teu servo, deveras confesso que pequei; por isso, sou o primeiro que, de toda a casa de José, desci a encontrar-me com o rei, meu senhor.

[[v10-19-21]]

^<<v10-19-21,21>>^ Então, respondeu Abisai, filho de Zeruia, e disse: Não morreria, pois, Simei por isto, havendo amaldiçoado ao ungido do SENHOR?

[[v10-19-22]]

^<<v10-19-22,22>>^ Porém Davi disse: Que tenho eu convosco, filhos de Zeruia, para que, hoje, me sejais adversários? Morreria alguém, hoje, em Israel? Pois não sei eu que, hoje, novamente sou rei sobre Israel?

[[v10-19-23]]

^<<v10-19-23,23>>^ Então, disse o rei a Simei: Não morrerás. E lho jurou.

[[v10-19-24]]

^<<v10-19-24,24>>^ Também Mefibosete, filho de Saul, desceu a encontrar-se com o rei; não tinha tratado dos pés, nem espontado a barba, nem lavado as vestes, desde o dia em que o rei saíra até ao dia em que voltou em paz.

[[v10-19-25]]

^<<v10-19-25,25>>^ Tendo ele chegado a Jerusalém a encontrar-se com o rei, este lhe disse: Por que não foste comigo, Mefibosete?

[[v10-19-26]]

^<<v10-19-26,26>>^ Ele respondeu: Ó rei, meu senhor, o meu servo me enganou; porque eu, teu servo, dizia: albardarei um jumento e montarei para ir com o rei; pois o teu servo é coxo.

[[v10-19-27]]

^<<v10-19-27,27>>^ Demais disto, ele falsamente me acusou a mim, teu servo, diante do rei, meu senhor; porém o rei, meu senhor, é como um anjo de Deus; faze, pois, o que melhor te parecer.

[[v10-19-28]]

^<<v10-19-28,28>>^ Porque toda a casa de meu pai não era senão de homens dignos de morte diante do rei, meu senhor; contudo, puseste teu servo entre os que comem à tua mesa; que direito, pois, tenho eu de clamar ao rei?

[[v10-19-29]]

^<<v10-19-29,29>>^ Respondeu-lhe o rei: Por que ainda falas dos teus negócios? Resolvo que repartas com Ziba as terras.

[[v10-19-30]]

^<<v10-19-30,30>>^ Disse Mefibosete ao rei: Fique ele, muito embora, com tudo, pois já voltou o rei, meu senhor, em paz à sua casa.

[[v10-19-31]]

^<<v10-19-31,31>>^ Também Barzilai, o gileadita, desceu de Rogelim e passou com o rei o Jordão, para o acompanhar até ao outro lado.

[[v10-19-32]]

^<<v10-19-32,32>>^ Era Barzilai mui velho, da idade de oitenta anos; ele sustentara o rei quando este estava em Maanaim, porque era homem mui rico.

[[v10-19-33]]

^<<v10-19-33,33>>^ Disse o rei a Barzilai: Vem tu comigo, e te sustentarei em Jerusalém.

[[v10-19-34]]

^<<v10-19-34,34>>^ Respondeu Barzilai ao rei: Quantos serão ainda os dias dos anos da minha vida? Não vale a pena subir com o rei a Jerusalém.

[[v10-19-35]]

^<<v10-19-35,35>>^ Oitenta anos tenho hoje; poderia eu discernir entre o bom e o mau? Poderia o teu servo ter gosto no que come e no que bebe? Poderia eu mais ouvir a voz dos cantores e cantoras? E por que há de ser o teu servo ainda pesado ao rei, meu senhor?

[[v10-19-36]]

^<<v10-19-36,36>>^ Com o rei irá o teu servo ainda um pouco além do Jordão; por que há de me retribuir o rei com tal recompensa?

[[v10-19-37]]

^<<v10-19-37,37>>^ Deixa voltar o teu servo, e morrerei na minha cidade e serei sepultado junto de meu pai e de minha mãe; mas eis aí o teu servo Quimã; passe ele com o rei, meu senhor, e faze-lhe o que bem te parecer.

[[v10-19-38]]

^<<v10-19-38,38>>^ Respondeu o rei: Quimã passará comigo, e eu lhe farei como for do teu agrado e tudo quanto desejares de mim eu te farei.

[[v10-19-39]]

^<<v10-19-39,39>>^ Havendo, pois, todo o povo passado o Jordão e passado também o rei, este beijou a Barzilai e o abençoou; e ele voltou para sua casa.

[[v10-19-40]]

^<<v10-19-40,40>>^ Dali, passou o rei a Gilgal, e Quimã passou com ele; todo o povo de Judá e metade do povo de Israel acompanharam o rei.

[[v10-19-41]]

^<<v10-19-41,41>>^ Eis que todos os homens de Israel vieram ter com o rei e lhe disseram: Por que te furtaram nossos irmãos, os homens de Judá, e conduziram o rei, e a sua casa através do Jordão, e todos os homens de Davi com eles?

[[v10-19-42]]

^<<v10-19-42,42>>^ Então, responderam todos os homens de Judá aos homens de Israel: Porque o rei é nosso parente; por que, pois, vos irais por isso? Porventura, comemos à custa do rei ou nos deu algum presente?

[[v10-19-43]]

^<<v10-19-43,43>>^ Responderam os homens de Israel aos homens de Judá e disseram: Dez tantos temos no rei, e mais a nós nos toca Davi do que a vós outros; por que, pois, fizestes pouco caso de nós? Não foi a nossa palavra a primeira para fazer voltar o nosso rei? Porém a palavra dos homens de Judá foi mais dura do que a palavra dos homens de Israel.

'''

xref:010-2-samuel/010-2-samuel-018.adoc#v10-18-0[&#60; Capítulo Anterior] | <<v10-19-0,Topo>> | xref:010-2-samuel/010-2-samuel-020.adoc#v10-20-0[Próximo Capítulo &#62;]