include::./index.adoc[]

[[v10-6-0]]
=== 2 Samuel, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-6-1]]

^<<v10-6-1,1>>^ Tornou Davi a ajuntar todos os escolhidos de Israel, em número de trinta mil.

[[v10-6-2]]

^<<v10-6-2,2>>^ Dispôs-se e, com todo o povo que tinha consigo, partiu para Baalá de Judá, para levarem de lá para cima a arca de Deus, sobre a qual se invoca o Nome, o nome do SENHOR dos Exércitos, que se assenta acima dos querubins.

[[v10-6-3]]

^<<v10-6-3,3>>^ Puseram a arca de Deus num carro novo e a levaram da casa de Abinadabe, que estava no outeiro; e Uzá e Aiô, filhos de Abinadabe, guiavam o carro novo.

[[v10-6-4]]

^<<v10-6-4,4>>^ Levaram-no com a arca de Deus, da casa de Abinadabe, que estava no outeiro; e Aiô ia adiante da arca.

[[v10-6-5]]

^<<v10-6-5,5>>^ Davi e toda a casa de Israel alegravam-se perante o SENHOR, com toda sorte de instrumentos de pau de faia, com harpas, com saltérios, com tamboris, com pandeiros e com címbalos.

[[v10-6-6]]

^<<v10-6-6,6>>^ Quando chegaram à eira de Nacom, estendeu Uzá a mão à arca de Deus e a segurou, porque os bois tropeçaram.

[[v10-6-7]]

^<<v10-6-7,7>>^ Então, a ira do SENHOR se acendeu contra Uzá, e Deus o feriu ali por esta irreverência; e morreu ali junto à arca de Deus.

[[v10-6-8]]

^<<v10-6-8,8>>^ Desgostou-se Davi, porque o SENHOR irrompera contra Uzá; e chamou aquele lugar Perez-Uzá, até ao dia de hoje.

[[v10-6-9]]

^<<v10-6-9,9>>^ Temeu Davi ao SENHOR, naquele dia, e disse: Como virá a mim a arca do SENHOR?

[[v10-6-10]]

^<<v10-6-10,10>>^ Não quis Davi retirar para junto de si a arca do SENHOR, para a Cidade de Davi; mas a fez levar à casa de Obede-Edom, o geteu.

[[v10-6-11]]

^<<v10-6-11,11>>^ Ficou a arca do SENHOR em casa de Obede-Edom, o geteu, três meses; e o SENHOR o abençoou e a toda a sua casa.

[[v10-6-12]]

^<<v10-6-12,12>>^ Então, avisaram a Davi, dizendo: O SENHOR abençoou a casa de Obede-Edom e tudo quanto tem, por amor da arca de Deus; foi, pois, Davi e, com alegria, fez subir a arca de Deus da casa de Obede-Edom, à Cidade de Davi.

[[v10-6-13]]

^<<v10-6-13,13>>^ Sucedeu que, quando os que levavam a arca do SENHOR tinham dado seis passos, sacrificava ele bois e carneiros cevados.

[[v10-6-14]]

^<<v10-6-14,14>>^ Davi dançava com todas as suas forças diante do SENHOR; e estava cingido de uma estola sacerdotal de linho.

[[v10-6-15]]

^<<v10-6-15,15>>^ Assim, Davi, com todo o Israel, fez subir a arca do SENHOR, com júbilo e ao som de trombetas.

[[v10-6-16]]

^<<v10-6-16,16>>^ Ao entrar a arca do SENHOR na Cidade de Davi, Mical, filha de Saul, estava olhando pela janela e, vendo ao rei Davi, que ia saltando e dançando diante do SENHOR, o desprezou no seu coração.

[[v10-6-17]]

^<<v10-6-17,17>>^ Introduziram a arca do SENHOR e puseram-na no seu lugar, na tenda que lhe armara Davi; e este trouxe holocaustos e ofertas pacíficas perante o SENHOR.

[[v10-6-18]]

^<<v10-6-18,18>>^ Tendo Davi trazido holocaustos e ofertas pacíficas, abençoou o povo em nome do SENHOR dos Exércitos.

[[v10-6-19]]

^<<v10-6-19,19>>^ E repartiu a todo o povo e a toda a multidão de Israel, tanto homens como mulheres, a cada um, um bolo de pão, um bom pedaço de carne e passas. Então, se retirou todo o povo, cada um para sua casa.

[[v10-6-20]]

^<<v10-6-20,20>>^ Voltando Davi para abençoar a sua casa, Mical, filha de Saul, saiu a encontrar-se com ele e lhe disse: Que bela figura fez o rei de Israel, descobrindo-se, hoje, aos olhos das servas de seus servos, como, sem pejo, se descobre um vadio qualquer!

[[v10-6-21]]

^<<v10-6-21,21>>^ Disse, porém, Davi a Mical: Perante o SENHOR, que me escolheu a mim antes do que a teu pai e a toda a sua casa, mandando-me que fosse chefe sobre o povo do SENHOR, sobre Israel, perante o SENHOR me tenho alegrado.

[[v10-6-22]]

^<<v10-6-22,22>>^ Ainda mais desprezível me farei e me humilharei aos meus olhos; quanto às servas, de quem falaste, delas serei honrado.

[[v10-6-23]]

^<<v10-6-23,23>>^ Mical, filha de Saul, não teve filhos, até ao dia da sua morte.

'''

xref:010-2-samuel/010-2-samuel-005.adoc#v10-5-0[&#60; Capítulo Anterior] | <<v10-6-0,Topo>> | xref:010-2-samuel/010-2-samuel-007.adoc#v10-7-0[Próximo Capítulo &#62;]