include::./index.adoc[]

[[v10-9-0]]
=== 2 Samuel, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-9-1]]

^<<v10-9-1,1>>^ Disse Davi: Resta ainda, porventura, alguém da casa de Saul, para que use eu de bondade para com ele, por amor de Jônatas?

[[v10-9-2]]

^<<v10-9-2,2>>^ Havia um servo na casa de Saul cujo nome era Ziba; chamaram-no que viesse a Davi. Perguntou-lhe o rei: És tu Ziba? Respondeu: Eu mesmo, teu servo.

[[v10-9-3]]

^<<v10-9-3,3>>^ Disse-lhe o rei: Não há ainda alguém da casa de Saul para que use eu da bondade de Deus para com ele? Então, Ziba respondeu ao rei: Ainda há um filho de Jônatas, aleijado de ambos os pés.

[[v10-9-4]]

^<<v10-9-4,4>>^ E onde está? Perguntou-lhe o rei. Ziba lhe respondeu: Está na casa de Maquir, filho de Amiel, em Lo-Debar.

[[v10-9-5]]

^<<v10-9-5,5>>^ Então, mandou o rei Davi trazê-lo de Lo-Debar, da casa de Maquir, filho de Amiel.

[[v10-9-6]]

^<<v10-9-6,6>>^ Vindo Mefibosete, filho de Jônatas, filho de Saul, a Davi, inclinou-se, prostrando-se com o rosto em terra. Disse-lhe Davi: Mefibosete! Ele disse: Eis aqui teu servo!

[[v10-9-7]]

^<<v10-9-7,7>>^ Então, lhe disse Davi: Não temas, porque usarei de bondade para contigo, por amor de Jônatas, teu pai, e te restituirei todas as terras de Saul, teu pai, e tu comerás pão sempre à minha mesa.

[[v10-9-8]]

^<<v10-9-8,8>>^ Então, se inclinou e disse: Quem é teu servo, para teres olhado para um cão morto tal como eu?

[[v10-9-9]]

^<<v10-9-9,9>>^ Chamou Davi a Ziba, servo de Saul, e lhe disse: Tudo o que pertencia a Saul e toda a sua casa dei ao filho de teu senhor.

[[v10-9-10]]

^<<v10-9-10,10>>^ Trabalhar-lhe-ás, pois, a terra, tu, e teus filhos, e teus servos, e recolherás os frutos, para que a casa de teu senhor tenha pão que coma; porém Mefibosete, filho de teu senhor, comerá pão sempre à minha mesa. Tinha Ziba quinze filhos e vinte servos.

[[v10-9-11]]

^<<v10-9-11,11>>^ Disse Ziba ao rei: Segundo tudo quanto meu senhor, o rei, manda a seu servo, assim o fará. Comeu, pois, Mefibosete à mesa de Davi, como um dos filhos do rei.

[[v10-9-12]]

^<<v10-9-12,12>>^ Tinha Mefibosete um filho pequeno, cujo nome era Mica. Todos quantos moravam em casa de Ziba eram servos de Mefibosete.

[[v10-9-13]]

^<<v10-9-13,13>>^ Morava Mefibosete em Jerusalém, porquanto comia sempre à mesa do rei. Ele era coxo de ambos os pés.

'''

xref:010-2-samuel/010-2-samuel-008.adoc#v10-8-0[&#60; Capítulo Anterior] | <<v10-9-0,Topo>> | xref:010-2-samuel/010-2-samuel-010.adoc#v10-10-0[Próximo Capítulo &#62;]