include::./index.adoc[]

[[v10-11-0]]
=== 2 Samuel, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-11-1]]

^<<v10-11-1,1>>^ Decorrido um ano, no tempo em que os reis costumam sair para a guerra, enviou Davi a Joabe, e seus servos, com ele, e a todo o Israel, que destruíram os filhos de Amom e sitiaram Rabá; porém Davi ficou em Jerusalém.

[[v10-11-2]]

^<<v10-11-2,2>>^ Uma tarde, levantou-se Davi do seu leito e andava passeando no terraço da casa real; daí viu uma mulher que estava tomando banho; era ela mui formosa.

[[v10-11-3]]

^<<v10-11-3,3>>^ Davi mandou perguntar quem era. Disseram-lhe: É Bate-Seba, filha de Eliã e mulher de Urias, o heteu.

[[v10-11-4]]

^<<v10-11-4,4>>^ Então, enviou Davi mensageiros que a trouxessem; ela veio, e ele se deitou com ela. Tendo-se ela purificado da sua imundícia, voltou para sua casa.

[[v10-11-5]]

^<<v10-11-5,5>>^ A mulher concebeu e mandou dizer a Davi: Estou grávida.

[[v10-11-6]]

^<<v10-11-6,6>>^ Então, enviou Davi mensageiros a Joabe, dizendo: Manda-me Urias, o heteu. Joabe enviou Urias a Davi.

[[v10-11-7]]

^<<v10-11-7,7>>^ Vindo, pois, Urias a Davi, perguntou este como passava Joabe, como se achava o povo e como ia a guerra.

[[v10-11-8]]

^<<v10-11-8,8>>^ Depois, disse Davi a Urias: Desce a tua casa e lava os pés. Saindo Urias da casa real, logo se lhe seguiu um presente do rei.

[[v10-11-9]]

^<<v10-11-9,9>>^ Porém Urias se deitou à porta da casa real, com todos os servos do seu senhor, e não desceu para sua casa.

[[v10-11-10]]

^<<v10-11-10,10>>^ Fizeram-no saber a Davi, dizendo: Urias não desceu a sua casa. Então, disse Davi a Urias: Não vens tu de uma jornada? Por que não desceste a tua casa?

[[v10-11-11]]

^<<v10-11-11,11>>^ Respondeu Urias a Davi: A arca, Israel e Judá ficam em tendas; Joabe, meu senhor, e os servos de meu senhor estão acampados ao ar livre; e hei de eu entrar na minha casa, para comer e beber e para me deitar com minha mulher? Tão certo como tu vives e como vive a tua alma, não farei tal coisa.

[[v10-11-12]]

^<<v10-11-12,12>>^ Então, disse Davi a Urias: Demora-te aqui ainda hoje, e amanhã te despedirei. Urias, pois, ficou em Jerusalém aquele dia e o seguinte.

[[v10-11-13]]

^<<v10-11-13,13>>^ Davi o convidou, e comeu e bebeu diante dele, e o embebedou; à tarde, saiu Urias a deitar-se na sua cama, com os servos de seu senhor; porém não desceu a sua casa.

[[v10-11-14]]

^<<v10-11-14,14>>^ Pela manhã, Davi escreveu uma carta a Joabe e lha mandou por mão de Urias.

[[v10-11-15]]

^<<v10-11-15,15>>^ Escreveu na carta, dizendo: Ponde Urias na frente da maior força da peleja; e deixai-o sozinho, para que seja ferido e morra.

[[v10-11-16]]

^<<v10-11-16,16>>^ Tendo, pois, Joabe sitiado a cidade, pôs a Urias no lugar onde sabia que estavam homens valentes.

[[v10-11-17]]

^<<v10-11-17,17>>^ Saindo os homens da cidade e pelejando com Joabe, caíram alguns do povo, dos servos de Davi; e morreu também Urias, o heteu.

[[v10-11-18]]

^<<v10-11-18,18>>^ Então, Joabe enviou notícias e fez saber a Davi tudo o que se dera na batalha.

[[v10-11-19]]

^<<v10-11-19,19>>^ Deu ordem ao mensageiro, dizendo: Se, ao terminares de contar ao rei os acontecimentos desta peleja,

[[v10-11-20]]

^<<v10-11-20,20>>^ suceder que ele se encolerize e te diga: Por que vos chegastes assim perto da cidade a pelejar? Não sabíeis vós que haviam de atirar do muro?

[[v10-11-21]]

^<<v10-11-21,21>>^ Quem feriu a Abimeleque, filho de Jerubesete? Não lançou uma mulher sobre ele, do muro, um pedaço de mó corredora, de que morreu em Tebes? Por que vos chegastes ao muro? Então, dirás: Também morreu teu servo Urias, o heteu.

[[v10-11-22]]

^<<v10-11-22,22>>^ Partiu o mensageiro e, chegando, fez saber a Davi tudo o que Joabe lhe havia mandado dizer.

[[v10-11-23]]

^<<v10-11-23,23>>^ Disse o mensageiro a Davi: Na verdade, aqueles homens foram mais poderosos do que nós e saíram contra nós ao campo; porém nós fomos contra eles, até à entrada da porta.

[[v10-11-24]]

^<<v10-11-24,24>>^ Então, os flecheiros, do alto do muro, atiraram contra os teus servos, e morreram alguns dos servos do rei; e também morreu o teu servo Urias, o heteu.

[[v10-11-25]]

^<<v10-11-25,25>>^ Disse Davi ao mensageiro: Assim dirás a Joabe: Não pareça isto mal aos teus olhos, pois a espada devora tanto este como aquele; intensifica a tua peleja contra a cidade e derrota-a; e, tu, anima a Joabe.

[[v10-11-26]]

^<<v10-11-26,26>>^ Ouvindo, pois, a mulher de Urias que seu marido era morto, ela o pranteou.

[[v10-11-27]]

^<<v10-11-27,27>>^ Passado o luto, Davi mandou buscá-la e a trouxe para o palácio; tornou-se ela sua mulher e lhe deu à luz um filho. Porém isto que Davi fizera foi mau aos olhos do SENHOR.

'''

xref:010-2-samuel/010-2-samuel-010.adoc#v10-10-0[&#60; Capítulo Anterior] | <<v10-11-0,Topo>> | xref:010-2-samuel/010-2-samuel-012.adoc#v10-12-0[Próximo Capítulo &#62;]