include::./index.adoc[]

[[v10-10-0]]
=== 2 Samuel, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-10-1]]

^<<v10-10-1,1>>^ Depois disto, morreu o rei dos filhos de Amom, e seu filho Hanum reinou em seu lugar.

[[v10-10-2]]

^<<v10-10-2,2>>^ Então, disse Davi: Usarei de bondade para com Hanum, filho de Naás, como seu pai usou de bondade para comigo. E enviou Davi servos seus para o consolar acerca de seu pai; e vieram os servos de Davi à terra dos filhos de Amom.

[[v10-10-3]]

^<<v10-10-3,3>>^ Mas os príncipes dos filhos de Amom disseram a seu senhor, Hanum: Pensas que, por Davi te haver mandado consoladores, está honrando a teu pai? Porventura, não te enviou ele os seus servos para reconhecerem a cidade, espiá-la e destruí-la?

[[v10-10-4]]

^<<v10-10-4,4>>^ Tomou, então, Hanum os servos de Davi, e lhes rapou metade da barba, e lhes cortou metade das vestes até às nádegas, e os despediu.

[[v10-10-5]]

^<<v10-10-5,5>>^ Sabedor disso, enviou Davi mensageiros a encontrá-los, porque estavam sobremaneira envergonhados. Mandou o rei dizer-lhes: Deixai-vos estar em Jericó, até que vos torne a crescer a barba; e, então, vinde.

[[v10-10-6]]

^<<v10-10-6,6>>^ Vendo, pois, os filhos de Amom que se haviam tornado odiosos a Davi, mandaram mensageiros tomar a soldo vinte mil homens de pé dos siros de Bete-Reobe e dos siros de Zobá, mil homens do rei de Maaca e doze mil de Tobe.

[[v10-10-7]]

^<<v10-10-7,7>>^ O que ouvindo Davi, enviou contra eles a Joabe com todo o exército dos valentes.

[[v10-10-8]]

^<<v10-10-8,8>>^ Saíram os filhos de Amom e ordenaram a batalha à entrada da porta, e os siros de Zobá e Reobe e os homens de Tobe e Maaca estavam à parte no campo.

[[v10-10-9]]

^<<v10-10-9,9>>^ Vendo, pois, Joabe que estava preparada contra ele a batalha, tanto pela frente como pela retaguarda, escolheu dentre todos o que havia de melhor em Israel e os formou em linha contra os siros;

[[v10-10-10]]

^<<v10-10-10,10>>^ e o resto do povo, entregou-o a Abisai, seu irmão, o qual o formou em linha contra os filhos de Amom.

[[v10-10-11]]

^<<v10-10-11,11>>^ Disse Joabe: Se os siros forem mais fortes do que eu, tu me virás em socorro; e, se os filhos de Amom forem mais fortes do que tu, eu irei ao teu socorro.

[[v10-10-12]]

^<<v10-10-12,12>>^ Sê forte, pois; pelejemos varonilmente pelo nosso povo e pelas cidades de nosso Deus; e faça o SENHOR o que bem lhe parecer.

[[v10-10-13]]

^<<v10-10-13,13>>^ Então, avançou Joabe com o povo que estava com ele, e travaram peleja contra os siros; e estes fugiram de diante deles.

[[v10-10-14]]

^<<v10-10-14,14>>^ Vendo os filhos de Amom que os siros fugiam, também eles fugiram de diante de Abisai e entraram na cidade; voltou Joabe dos filhos de Amom e tornou a Jerusalém.

[[v10-10-15]]

^<<v10-10-15,15>>^ Vendo, pois, os siros que tinham sido desbaratados diante de Israel, tornaram a refazer-se.

[[v10-10-16]]

^<<v10-10-16,16>>^ E Hadadezer fez sair os siros que estavam do outro lado do rio, e vieram a Helã; Sobaque, chefe do exército de Hadadezer, marchava adiante deles.

[[v10-10-17]]

^<<v10-10-17,17>>^ Informado Davi, ajuntou a todo o Israel, passou o Jordão e foi a Helã; os siros se puseram em ordem de batalha contra Davi e pelejaram contra ele.

[[v10-10-18]]

^<<v10-10-18,18>>^ Porém os siros fugiram de diante de Israel, e Davi matou dentre os siros os homens de setecentos carros e quarenta mil homens de cavalo; também feriu a Sobaque, chefe do exército, de tal sorte que morreu ali.

[[v10-10-19]]

^<<v10-10-19,19>>^ Vendo, pois, todos os reis, servos de Hadadezer, que foram vencidos, fizeram paz com Israel e o serviram; e temeram os siros de ainda socorrer aos filhos de Amom.

'''

xref:010-2-samuel/010-2-samuel-009.adoc#v10-9-0[&#60; Capítulo Anterior] | <<v10-10-0,Topo>> | xref:010-2-samuel/010-2-samuel-011.adoc#v10-11-0[Próximo Capítulo &#62;]