include::./index.adoc[]

[[v10-7-0]]
=== 2 Samuel, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-7-1]]

^<<v10-7-1,1>>^ Sucedeu que, habitando o rei Davi em sua própria casa, tendo-lhe o SENHOR dado descanso de todos os seus inimigos em redor,

[[v10-7-2]]

^<<v10-7-2,2>>^ disse o rei ao profeta Natã: Olha, eu moro em casa de cedros, e a arca de Deus se acha numa tenda.

[[v10-7-3]]

^<<v10-7-3,3>>^ Disse Natã ao rei: Vai, faze tudo quanto está no teu coração, porque o SENHOR é contigo.

[[v10-7-4]]

^<<v10-7-4,4>>^ Porém, naquela mesma noite, veio a palavra do SENHOR a Natã, dizendo:

[[v10-7-5]]

^<<v10-7-5,5>>^ Vai e dize a meu servo Davi: Assim diz o SENHOR: Edificar-me-ás tu casa para minha habitação?

[[v10-7-6]]

^<<v10-7-6,6>>^ Porque em casa nenhuma habitei desde o dia em que fiz subir os filhos de Israel do Egito até ao dia de hoje; mas tenho andado em tenda, em tabernáculo.

[[v10-7-7]]

^<<v10-7-7,7>>^ Em todo lugar em que andei com todos os filhos de Israel, falei, acaso, alguma palavra com qualquer das suas tribos, a quem mandei apascentar o meu povo de Israel, dizendo: Por que não me edificais uma casa de cedro?

[[v10-7-8]]

^<<v10-7-8,8>>^ Agora, pois, assim dirás ao meu servo Davi: Assim diz o SENHOR dos Exércitos: Tomei-te da malhada, de detrás das ovelhas, para que fosses príncipe sobre o meu povo, sobre Israel.

[[v10-7-9]]

^<<v10-7-9,9>>^ E fui contigo, por onde quer que andaste, eliminei os teus inimigos diante de ti e fiz grande o teu nome, como só os grandes têm na terra.

[[v10-7-10]]

^<<v10-7-10,10>>^ Prepararei lugar para o meu povo, para Israel, e o plantarei, para que habite no seu lugar e não mais seja perturbado, e jamais os filhos da perversidade o aflijam, como dantes,

[[v10-7-11]]

^<<v10-7-11,11>>^ desde o dia em que mandei houvesse juízes sobre o meu povo de Israel. Dar-te-ei, porém, descanso de todos os teus inimigos; também o SENHOR te faz saber que ele, o SENHOR, te fará casa.

[[v10-7-12]]

^<<v10-7-12,12>>^ Quando teus dias se cumprirem e descansares com teus pais, então, farei levantar depois de ti o teu descendente, que procederá de ti, e estabelecerei o seu reino.

[[v10-7-13]]

^<<v10-7-13,13>>^ Este edificará uma casa ao meu nome, e eu estabelecerei para sempre o trono do seu reino.

[[v10-7-14]]

^<<v10-7-14,14>>^ Eu lhe serei por pai, e ele me será por filho; se vier a transgredir, castigá-lo-ei com varas de homens e com açoites de filhos de homens.

[[v10-7-15]]

^<<v10-7-15,15>>^ Mas a minha misericórdia se não apartará dele, como a retirei de Saul, a quem tirei de diante de ti.

[[v10-7-16]]

^<<v10-7-16,16>>^ Porém a tua casa e o teu reino serão firmados para sempre diante de ti; teu trono será estabelecido para sempre.

[[v10-7-17]]

^<<v10-7-17,17>>^ Segundo todas estas palavras e conforme toda esta visão, assim falou Natã a Davi.

[[v10-7-18]]

^<<v10-7-18,18>>^ Então, entrou o rei Davi na Casa do SENHOR, ficou perante ele e disse: Quem sou eu, SENHOR Deus, e qual é a minha casa, para que me tenhas trazido até aqui?

[[v10-7-19]]

^<<v10-7-19,19>>^ Foi isso ainda pouco aos teus olhos, SENHOR Deus, de maneira que também falaste a respeito da casa de teu servo para tempos distantes; e isto é instrução para todos os homens, ó SENHOR Deus.

[[v10-7-20]]

^<<v10-7-20,20>>^ Que mais ainda te poderá dizer Davi? Pois tu conheces bem a teu servo, ó SENHOR Deus.

[[v10-7-21]]

^<<v10-7-21,21>>^ Por causa da tua palavra e segundo o teu coração, fizeste toda esta grandeza, dando-a a conhecer a teu servo.

[[v10-7-22]]

^<<v10-7-22,22>>^ Portanto, grandíssimo és, ó SENHOR Deus, porque não há semelhante a ti, e não há outro Deus além de ti, segundo tudo o que nós mesmos temos ouvido.

[[v10-7-23]]

^<<v10-7-23,23>>^ Quem há como o teu povo, como Israel, gente única na terra, a quem tu, ó Deus, foste resgatar para ser teu povo? E para fazer a ti mesmo um nome e fazer a teu povo estas grandes e tremendas coisas, para a tua terra, diante do teu povo, que tu resgataste do Egito, desterrando as nações e seus deuses?

[[v10-7-24]]

^<<v10-7-24,24>>^ Estabeleceste teu povo Israel por teu povo para sempre e tu, ó SENHOR, te fizeste o seu Deus.

[[v10-7-25]]

^<<v10-7-25,25>>^ Agora, pois, ó SENHOR Deus, quanto a esta palavra que disseste acerca de teu servo e acerca da sua casa, confirma-a para sempre e faze como falaste.

[[v10-7-26]]

^<<v10-7-26,26>>^ Seja para sempre engrandecido o teu nome, e diga-se: O SENHOR dos Exércitos é Deus sobre Israel; e a casa de Davi, teu servo, será estabelecida diante de ti.

[[v10-7-27]]

^<<v10-7-27,27>>^ Pois tu, ó SENHOR dos Exércitos, Deus de Israel, fizeste ao teu servo esta revelação, dizendo: Edificar-te-ei casa. Por isso, o teu servo se animou para fazer-te esta oração.

[[v10-7-28]]

^<<v10-7-28,28>>^ Agora, pois, ó SENHOR Deus, tu mesmo és Deus, e as tuas palavras são verdade, e tens prometido a teu servo este bem.

[[v10-7-29]]

^<<v10-7-29,29>>^ Sê, pois, agora, servido de abençoar a casa do teu servo, a fim de permanecer para sempre diante de ti, pois tu, ó SENHOR Deus, o disseste; e, com a tua bênção, será, para sempre, bendita a casa do teu servo.

'''

xref:010-2-samuel/010-2-samuel-006.adoc#v10-6-0[&#60; Capítulo Anterior] | <<v10-7-0,Topo>> | xref:010-2-samuel/010-2-samuel-008.adoc#v10-8-0[Próximo Capítulo &#62;]