include::./index.adoc[]

[[v10-17-0]]
=== 2 Samuel, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-17-1]]

^<<v10-17-1,1>>^ Disse ainda Aitofel a Absalão: Deixa-me escolher doze mil homens, e me disporei, e perseguirei Davi esta noite.

[[v10-17-2]]

^<<v10-17-2,2>>^ Assaltá-lo-ei, enquanto está cansado e frouxo de mãos; espantá-lo-ei; fugirá todo o povo que está com ele; então, matarei apenas o rei.

[[v10-17-3]]

^<<v10-17-3,3>>^ Farei voltar a ti todo o povo; pois a volta de todos depende daquele a quem procuras matar; assim, todo o povo estará em paz.

[[v10-17-4]]

^<<v10-17-4,4>>^ O parecer agradou a Absalão e a todos os anciãos de Israel.

[[v10-17-5]]

^<<v10-17-5,5>>^ Disse, porém, Absalão: Chamai, agora, a Husai, o arquita, e ouçamos também o que ele dirá.

[[v10-17-6]]

^<<v10-17-6,6>>^ Tendo Husai chegado a Absalão, este lhe falou, dizendo: Desta maneira falou Aitofel; faremos segundo a sua palavra? Se não, fala tu.

[[v10-17-7]]

^<<v10-17-7,7>>^ Então, disse Husai a Absalão: O conselho que deu Aitofel desta vez não é bom.

[[v10-17-8]]

^<<v10-17-8,8>>^ Continuou Husai: Bem conheces teu pai e seus homens e sabes que são valentes e estão enfurecidos como a ursa no campo, roubada dos seus cachorros; também teu pai é homem de guerra e não passará a noite com o povo.

[[v10-17-9]]

^<<v10-17-9,9>>^ Eis que, agora, estará de espreita nalguma cova ou em qualquer outro lugar; e será que, caindo no primeiro ataque alguns dos teus, cada um que o ouvir dirá: Houve derrota no povo que segue a Absalão.

[[v10-17-10]]

^<<v10-17-10,10>>^ Então, até o homem valente, cujo coração é como o de leões, sem dúvida desmaiará; porque todo o Israel sabe que teu pai é herói e que homens valentes são os que estão com ele.

[[v10-17-11]]

^<<v10-17-11,11>>^ Eu, porém, aconselho que a toda pressa se reúna a ti todo o Israel, desde Dã até Berseba, em multidão como a areia do mar; e que tu em pessoa vás no meio deles.

[[v10-17-12]]

^<<v10-17-12,12>>^ Então, iremos a ele em qualquer lugar em que se achar e facilmente cairemos sobre ele, como o orvalho cai sobre a terra; ele não ficará, e nenhum dos homens que com ele estão, nem um só.

[[v10-17-13]]

^<<v10-17-13,13>>^ Se ele se retirar para alguma cidade, todo o Israel levará cordas àquela cidade; e arrastá-la-emos até ao ribeiro, até que lá não se ache nem uma só pedrinha.

[[v10-17-14]]

^<<v10-17-14,14>>^ Então, disseram Absalão e todos os homens de Israel: Melhor é o conselho de Husai, o arquita, do que o de Aitofel. Pois ordenara o SENHOR que fosse dissipado o bom conselho de Aitofel, para que o mal sobreviesse contra Absalão.

[[v10-17-15]]

^<<v10-17-15,15>>^ Disse Husai a Zadoque e a Abiatar, sacerdotes: Assim e assim aconselhou Aitofel a Absalão e aos anciãos de Israel; porém assim e assim aconselhei eu.

[[v10-17-16]]

^<<v10-17-16,16>>^ Agora, pois, mandai avisar depressa a Davi, dizendo: Não passes esta noite nos vaus do deserto, mas passa, sem demora, ao outro lado, para que não seja destruído o rei e todo o povo que com ele está.

[[v10-17-17]]

^<<v10-17-17,17>>^ Estavam Jônatas e Aimaás junto a En-Rogel; e uma criada lhes dava aviso, e eles iam e diziam ao rei Davi, porque não podiam ser vistos entrar na cidade.

[[v10-17-18]]

^<<v10-17-18,18>>^ Viu-os, porém, um moço e avisou a Absalão; porém ambos partiram logo, apressadamente, e entraram em casa de um homem, em Baurim, que tinha um poço no seu pátio, ao qual desceram.

[[v10-17-19]]

^<<v10-17-19,19>>^ A mulher desse homem tomou uma coberta, e a estendeu sobre a boca do poço, e espalhou grãos pilados de cereais sobre ela; assim, nada se soube.

[[v10-17-20]]

^<<v10-17-20,20>>^ Chegando, pois, os servos de Absalão à mulher, àquela casa, disseram: Onde estão Aimaás e Jônatas? Respondeu-lhes a mulher: Já passaram o vau das águas. Havendo-os procurado, sem os achar, voltaram para Jerusalém.

[[v10-17-21]]

^<<v10-17-21,21>>^ Mal se retiraram, saíram logo os dois do poço, e foram dar aviso a Davi, e lhe disseram: Levantai-vos e passai depressa as águas, porque assim e assim aconselhou Aitofel contra vós outros.

[[v10-17-22]]

^<<v10-17-22,22>>^ Então, Davi e todo o povo que com ele estava se levantaram e passaram o Jordão; quando amanheceu, já nem um só havia que não tivesse passado o Jordão.

[[v10-17-23]]

^<<v10-17-23,23>>^ Vendo, pois, Aitofel que não fora seguido o seu conselho, albardou o jumento, dispôs-se e foi para casa e para a sua cidade; pôs em ordem os seus negócios e se enforcou; morreu e foi sepultado na sepultura do seu pai.

[[v10-17-24]]

^<<v10-17-24,24>>^ Davi chegou a Maanaim. Absalão, tendo passado o Jordão com todos os homens de Israel,

[[v10-17-25]]

^<<v10-17-25,25>>^ constituiu a Amasa em lugar de Joabe sobre o exército. Era Amasa filho de certo homem chamado Itra, o ismaelita, o qual se deitara com Abigail, filha de Naás, e irmã de Zeruia, mãe de Joabe.

[[v10-17-26]]

^<<v10-17-26,26>>^ Israel, pois, e Absalão acamparam-se na terra de Gileade.

[[v10-17-27]]

^<<v10-17-27,27>>^ Tendo Davi chegado a Maanaim, Sobi, filho de Naás, de Rabá, dos filhos de Amom, e Maquir, filho de Amiel, de Lo-Debar, e Barzilai, o gileadita, de Rogelim,

[[v10-17-28]]

^<<v10-17-28,28>>^ tomaram camas, bacias e vasilhas de barro, trigo, cevada, farinha, grãos torrados, favas e lentilhas;

[[v10-17-29]]

^<<v10-17-29,29>>^ também mel, coalhada, ovelhas e queijos de gado e os trouxeram a Davi e ao povo que com ele estava, para comerem, porque disseram: Este povo no deserto está faminto, cansado e sedento.

'''

xref:010-2-samuel/010-2-samuel-016.adoc#v10-16-0[&#60; Capítulo Anterior] | <<v10-17-0,Topo>> | xref:010-2-samuel/010-2-samuel-018.adoc#v10-18-0[Próximo Capítulo &#62;]