include::./index.adoc[]

[[v10-5-0]]
=== 2 Samuel, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-5-1]]

^<<v10-5-1,1>>^ Então, todas as tribos de Israel vieram a Davi, a Hebrom, e falaram, dizendo: Somos do mesmo povo de que tu és.

[[v10-5-2]]

^<<v10-5-2,2>>^ Outrora, sendo Saul ainda rei sobre nós, eras tu que fazias entradas e saídas militares com Israel; também o SENHOR te disse: Tu apascentarás o meu povo de Israel e serás chefe sobre Israel.

[[v10-5-3]]

^<<v10-5-3,3>>^ Assim, pois, todos os anciãos de Israel vieram ter com o rei, em Hebrom; e o rei Davi fez com eles aliança em Hebrom, perante o SENHOR. Ungiram Davi rei sobre Israel.

[[v10-5-4]]

^<<v10-5-4,4>>^ Da idade de trinta anos era Davi quando começou a reinar; e reinou quarenta anos.

[[v10-5-5]]

^<<v10-5-5,5>>^ Em Hebrom, reinou sobre Judá sete anos e seis meses; em Jerusalém, reinou trinta e três anos sobre todo o Israel e Judá.

[[v10-5-6]]

^<<v10-5-6,6>>^ Partiu o rei com os seus homens para Jerusalém, contra os jebuseus que habitavam naquela terra e que disseram a Davi: Não entrarás aqui, porque os cegos e os coxos te repelirão, como quem diz: Davi não entrará neste lugar.

[[v10-5-7]]

^<<v10-5-7,7>>^ Porém Davi tomou a fortaleza de Sião; esta é a Cidade de Davi.

[[v10-5-8]]

^<<v10-5-8,8>>^ Davi, naquele dia, mandou dizer: Todo o que está disposto a ferir os jebuseus suba pelo canal subterrâneo e fira os cegos e os coxos, a quem a alma de Davi aborrece. (Por isso, se diz: Nem cego nem coxo entrará na casa.)

[[v10-5-9]]

^<<v10-5-9,9>>^ Assim, habitou Davi na fortaleza e lhe chamou a Cidade de Davi; foi edificando em redor, desde Milo e para dentro.

[[v10-5-10]]

^<<v10-5-10,10>>^ Ia Davi crescendo em poder cada vez mais, porque o SENHOR, Deus dos Exércitos, era com ele.

[[v10-5-11]]

^<<v10-5-11,11>>^ Hirão, rei de Tiro, enviou mensageiros a Davi, e madeira de cedro, e carpinteiros, e pedreiros, que edificaram uma casa a Davi.

[[v10-5-12]]

^<<v10-5-12,12>>^ Reconheceu Davi que o SENHOR o confirmara rei sobre Israel e que exaltara o seu reino por amor do seu povo.

[[v10-5-13]]

^<<v10-5-13,13>>^ Tomou Davi mais concubinas e mulheres de Jerusalém, depois que viera de Hebrom, e nasceram-lhe mais filhos e filhas.

[[v10-5-14]]

^<<v10-5-14,14>>^ São estes os nomes dos que lhe nasceram em Jerusalém: Samua, Sobabe, Natã, Salomão,

[[v10-5-15]]

^<<v10-5-15,15>>^ Ibar, Elisua, Nefegue, Jafia,

[[v10-5-16]]

^<<v10-5-16,16>>^ Elisama, Eliada e Elifelete.

[[v10-5-17]]

^<<v10-5-17,17>>^ Ouvindo, pois, os filisteus que Davi fora ungido rei sobre Israel, subiram todos para prender a Davi; ouvindo-o, desceu Davi à fortaleza.

[[v10-5-18]]

^<<v10-5-18,18>>^ Mas vieram os filisteus e se estenderam pelo vale dos Refains.

[[v10-5-19]]

^<<v10-5-19,19>>^ Davi consultou ao SENHOR, dizendo: Subirei contra os filisteus? Entregar-mos-ás nas mãos? Respondeu-lhe o SENHOR: Sobe, porque, certamente, entregarei os filisteus nas tuas mãos.

[[v10-5-20]]

^<<v10-5-20,20>>^ Então, veio Davi a Baal-Perazim e os derrotou ali; e disse: Rompeu o SENHOR as fileiras inimigas diante de mim, como quem rompe águas. Por isso, chamou o nome daquele lugar Baal-Perazim.

[[v10-5-21]]

^<<v10-5-21,21>>^ Os filisteus deixaram lá os seus ídolos; e Davi e os seus homens os levaram.

[[v10-5-22]]

^<<v10-5-22,22>>^ Os filisteus tornaram a subir e se estenderam pelo vale dos Refains.

[[v10-5-23]]

^<<v10-5-23,23>>^ Davi consultou ao SENHOR, e este lhe respondeu: Não subirás; rodeia por detrás deles e ataca-os por defronte das amoreiras.

[[v10-5-24]]

^<<v10-5-24,24>>^ E há de ser que, ouvindo tu um estrondo de marcha pelas copas das amoreiras, então, te apressarás: é o SENHOR que saiu diante de ti, a ferir o arraial dos filisteus.

[[v10-5-25]]

^<<v10-5-25,25>>^ Fez Davi como o SENHOR lhe ordenara; e feriu os filisteus desde Geba até chegar a Gezer.

'''

xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[&#60; Capítulo Anterior] | <<v10-5-0,Topo>> | xref:010-2-samuel/010-2-samuel-006.adoc#v10-6-0[Próximo Capítulo &#62;]