include::./index.adoc[]

[[v10-2-0]]
=== 2 Samuel, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-2-1]]

^<<v10-2-1,1>>^ Depois disto, consultou Davi ao SENHOR, dizendo: Subirei a alguma das cidades de Judá? Respondeu-lhe o SENHOR: Sobe. Perguntou Davi: Para onde subirei? Respondeu o SENHOR: Para Hebrom.

[[v10-2-2]]

^<<v10-2-2,2>>^ Subiu Davi para lá, e também as suas duas mulheres, Ainoã, a jezreelita, e Abigail, a viúva de Nabal, o carmelita.

[[v10-2-3]]

^<<v10-2-3,3>>^ Fez Davi subir os homens que estavam com ele, cada um com sua família; e habitaram nas aldeias de Hebrom.

[[v10-2-4]]

^<<v10-2-4,4>>^ Então, vieram os homens de Judá e ungiram ali Davi rei sobre a casa de Judá. E informaram Davi de que os homens de Jabes-Gileade foram os que sepultaram Saul.

[[v10-2-5]]

^<<v10-2-5,5>>^ Então, enviou Davi mensageiros aos homens de Jabes-Gileade para dizer-lhes: Benditos do SENHOR sejais vós, por esta humanidade para com vosso senhor, para com Saul, pois o sepultastes!

[[v10-2-6]]

^<<v10-2-6,6>>^ Agora, pois, o SENHOR use convosco de misericórdia e fidelidade; eu vos recompensarei este bem que fizestes.

[[v10-2-7]]

^<<v10-2-7,7>>^ Agora, pois, sejam fortes as vossas mãos, e sede valentes, pois Saul, vosso senhor, é morto, e os da casa de Judá me ungiram rei sobre si.

[[v10-2-8]]

^<<v10-2-8,8>>^ Abner, filho de Ner, capitão do exército de Saul, tomou a Isbosete, filho de Saul, e o fez passar a Maanaim,

[[v10-2-9]]

^<<v10-2-9,9>>^ e o constituiu rei sobre Gileade, sobre os assuritas, sobre Jezreel, Efraim, Benjamim e sobre todo o Israel.

[[v10-2-10]]

^<<v10-2-10,10>>^ Da idade de quarenta anos era Isbosete, filho de Saul, quando começou a reinar sobre Israel, e reinou dois anos; somente a casa de Judá seguia a Davi.

[[v10-2-11]]

^<<v10-2-11,11>>^ O tempo que Davi reinou em Hebrom sobre a casa de Judá foram sete anos e seis meses.

[[v10-2-12]]

^<<v10-2-12,12>>^ Saiu Abner, filho de Ner, com os homens de Isbosete, filho de Saul, de Maanaim a Gibeão.

[[v10-2-13]]

^<<v10-2-13,13>>^ Saíram também Joabe, filho de Zeruia, e os homens de Davi e se encontraram uns com os outros perto do açude de Gibeão; pararam estes do lado de cá do açude, e aqueles, do lado de lá.

[[v10-2-14]]

^<<v10-2-14,14>>^ Disse Abner a Joabe: Levantem-se os moços e batam-se diante de nós. Respondeu Joabe: Levantem-se.

[[v10-2-15]]

^<<v10-2-15,15>>^ Então, se levantaram e avançaram em igual número: doze de Benjamim, da parte de Isbosete, filho de Saul, e doze dos homens de Davi.

[[v10-2-16]]

^<<v10-2-16,16>>^ Cada um lançou mão da cabeça do outro, meteu-lhe a espada no lado, e caíram juntamente; donde se chamou àquele lugar Campo das Espadas, que está junto a Gibeão.

[[v10-2-17]]

^<<v10-2-17,17>>^ Seguiu-se crua peleja naquele dia; porém Abner e os homens de Israel foram derrotados diante dos homens de Davi.

[[v10-2-18]]

^<<v10-2-18,18>>^ Estavam ali os três filhos de Zeruia: Joabe, Abisai e Asael; Asael era ligeiro de pés, como gazela selvagem.

[[v10-2-19]]

^<<v10-2-19,19>>^ Asael perseguiu a Abner e, na sua perseguição, não se desviou nem para a direita, nem para a esquerda.

[[v10-2-20]]

^<<v10-2-20,20>>^ Então, olhou Abner para trás e perguntou: És tu Asael? Ele respondeu: Eu mesmo.

[[v10-2-21]]

^<<v10-2-21,21>>^ Então, lhe disse Abner: Desvia-te para a direita ou para a esquerda, lança mão de um dos moços e toma-lhe a armadura. Porém Asael não quis apartar-se dele.

[[v10-2-22]]

^<<v10-2-22,22>>^ Então, Abner tornou a dizer-lhe: Desvia-te de detrás de mim; por que hei de eu ferir-te e dar contigo em terra? E como me avistaria rosto a rosto com Joabe, teu irmão?

[[v10-2-23]]

^<<v10-2-23,23>>^ Porém, recusando ele desviar-se, Abner o feriu no abdômen com a extremidade inferior da lança, que lhe saiu por detrás. Asael caiu e morreu no mesmo lugar; todos quantos chegavam no lugar em que Asael caíra e morrera paravam.

[[v10-2-24]]

^<<v10-2-24,24>>^ Porém Joabe e Abisai perseguiram Abner; e pôs-se o sol, quando chegaram eles ao outeiro de Amá, que está diante de Giá, junto ao caminho do deserto de Gibeão.

[[v10-2-25]]

^<<v10-2-25,25>>^ Os filhos de Benjamim se ajuntaram atrás de Abner e, cerrados numa tropa, puseram-se no cimo de um outeiro.

[[v10-2-26]]

^<<v10-2-26,26>>^ Então, Abner gritou a Joabe e disse: Consumirá a espada para sempre? Não sabes que serão amargas as suas consequências? Até quando te demorarás em ordenar ao povo que deixe de perseguir a seus irmãos?

[[v10-2-27]]

^<<v10-2-27,27>>^ Respondeu Joabe: Tão certo como vive Deus, se não tivesses falado, só amanhã cedo o povo cessaria de perseguir cada um a seu irmão.

[[v10-2-28]]

^<<v10-2-28,28>>^ Então, Joabe tocou a trombeta, e todo o povo parou, e eles não perseguiram mais a Israel e já não pelejaram.

[[v10-2-29]]

^<<v10-2-29,29>>^ Abner e seus homens marcharam toda aquela noite pela planície; passaram o Jordão e, caminhando toda a manhã, chegaram a Maanaim.

[[v10-2-30]]

^<<v10-2-30,30>>^ Joabe deixou de perseguir a Abner; e, tendo ele ajuntado todo o povo, faltavam dezenove dos homens de Davi, além de Asael.

[[v10-2-31]]

^<<v10-2-31,31>>^ Porém os servos de Davi tinham ferido, dentre os de Benjamim e dentre os homens de Abner, a trezentos e sessenta homens, que ali ficaram mortos.

[[v10-2-32]]

^<<v10-2-32,32>>^ Levaram Asael e o enterraram na sepultura de seu pai, a qual estava em Belém. Joabe e seus homens caminharam toda aquela noite, e amanheceu-lhes o dia em Hebrom.

'''

xref:010-2-samuel/010-2-samuel-001.adoc#v10-1-0[&#60; Capítulo Anterior] | <<v10-2-0,Topo>> | xref:010-2-samuel/010-2-samuel-003.adoc#v10-3-0[Próximo Capítulo &#62;]