include::./index.adoc[]

[[v10-16-0]]
=== 2 Samuel, 16
// ara ?, ARA - Almeida Revista e Atualizada

[[v10-16-1]]

^<<v10-16-1,1>>^ Tendo Davi passado um pouco além, dobrando o cimo, eis que lhe saiu ao encontro Ziba, servo de Mefibosete, com dois jumentos albardados e sobre eles duzentos pães, cem cachos de passas, cem frutas de verão e um odre de vinho.

[[v10-16-2]]

^<<v10-16-2,2>>^ Perguntou o rei a Ziba: Que pretendes com isto? Respondeu Ziba: Os jumentos são para a casa do rei, para serem montados; o pão e as frutas de verão, para os moços comerem; o vinho, para beberem os cansados no deserto.

[[v10-16-3]]

^<<v10-16-3,3>>^ Então, disse o rei: Onde está, pois, o filho de teu senhor? Respondeu Ziba ao rei: Eis que ficou em Jerusalém, pois disse: Hoje, a casa de Israel me restituirá o reino de meu pai.

[[v10-16-4]]

^<<v10-16-4,4>>^ Então, disse o rei a Ziba: Teu é tudo que pertence a Mefibosete. Disse Ziba: Eu me inclino e ache eu mercê diante de ti, ó rei, meu senhor.

[[v10-16-5]]

^<<v10-16-5,5>>^ Tendo chegado o rei Davi a Baurim, eis que dali saiu um homem da família da casa de Saul, cujo nome era Simei, filho de Gera; saiu e ia amaldiçoando.

[[v10-16-6]]

^<<v10-16-6,6>>^ Atirava pedras contra Davi e contra todos os seus servos, ainda que todo o povo e todos os valentes estavam à direita e à esquerda do rei.

[[v10-16-7]]

^<<v10-16-7,7>>^ Amaldiçoando-o, dizia Simei: Fora daqui, fora, homem de sangue, homem de Belial;

[[v10-16-8]]

^<<v10-16-8,8>>^ o SENHOR te deu, agora, a paga de todo o sangue da casa de Saul, cujo reino usurpaste; o SENHOR já o entregou nas mãos de teu filho Absalão; eis-te, agora, na tua desgraça, porque és homem de sangue.

[[v10-16-9]]

^<<v10-16-9,9>>^ Então, Abisai, filho de Zeruia, disse ao rei: Por que amaldiçoaria este cão morto ao rei, meu senhor? Deixa-me passar e lhe tirarei a cabeça.

[[v10-16-10]]

^<<v10-16-10,10>>^ Respondeu o rei: Que tenho eu convosco, filhos de Zeruia? Ora, deixai-o amaldiçoar; pois, se o SENHOR lhe disse: Amaldiçoa a Davi, quem diria: Por que assim fizeste?

[[v10-16-11]]

^<<v10-16-11,11>>^ Disse mais Davi a Abisai e a todos os seus servos: Eis que meu próprio filho procura tirar-me a vida, quanto mais ainda este benjamita? Deixai-o; que amaldiçoe, pois o SENHOR lhe ordenou.

[[v10-16-12]]

^<<v10-16-12,12>>^ Talvez o SENHOR olhará para a minha aflição e o SENHOR me pagará com bem a sua maldição deste dia.

[[v10-16-13]]

^<<v10-16-13,13>>^ Prosseguiam, pois, o seu caminho, Davi e os seus homens; também Simei ia ao longo do monte, ao lado dele, caminhando e amaldiçoando, e atirava pedras e terra contra ele.

[[v10-16-14]]

^<<v10-16-14,14>>^ O rei e todo o povo que ia com ele chegaram exaustos ao Jordão e ali descansaram.

[[v10-16-15]]

^<<v10-16-15,15>>^ Absalão, pois, e todo o povo, homens de Israel, vieram a Jerusalém; e, com ele, Aitofel.

[[v10-16-16]]

^<<v10-16-16,16>>^ Tendo-se apresentado Husai, o arquita, amigo de Davi, a Absalão, disse-lhe: Viva o rei, viva o rei!

[[v10-16-17]]

^<<v10-16-17,17>>^ Porém Absalão disse a Husai: É assim a tua fidelidade para com o teu amigo Davi? Por que não foste com o teu amigo?

[[v10-16-18]]

^<<v10-16-18,18>>^ Respondeu Husai a Absalão: Não, mas àquele a quem o SENHOR elegeu, e todo este povo, e todos os homens de Israel, a ele pertencerei e com ele ficarei.

[[v10-16-19]]

^<<v10-16-19,19>>^ Ainda mais, a quem serviria eu? Porventura, não seria diante de seu filho? Como servi diante de teu pai, assim serei diante de ti.

[[v10-16-20]]

^<<v10-16-20,20>>^ Então, disse Absalão a Aitofel: Dai o vosso conselho sobre o que devemos fazer.

[[v10-16-21]]

^<<v10-16-21,21>>^ Disse Aitofel a Absalão: Coabita com as concubinas de teu pai, que deixou para cuidar da casa; e, em ouvindo todo o Israel que te fizeste odioso para com teu pai, animar-se-ão todos os que estão contigo.

[[v10-16-22]]

^<<v10-16-22,22>>^ Armaram, pois, para Absalão uma tenda no eirado, e ali, à vista de todo o Israel, ele coabitou com as concubinas de seu pai.

[[v10-16-23]]

^<<v10-16-23,23>>^ O conselho que Aitofel dava, naqueles dias, era como resposta de Deus a uma consulta; tal era o conselho de Aitofel, tanto para Davi como para Absalão.

'''

xref:010-2-samuel/010-2-samuel-015.adoc#v10-15-0[&#60; Capítulo Anterior] | <<v10-16-0,Topo>> | xref:010-2-samuel/010-2-samuel-017.adoc#v10-17-0[Próximo Capítulo &#62;]