include::./index.adoc[]

[[v30-5-0]]
=== Amós, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v30-5-1]]

^<<v30-5-1,1>>^ Ouvi esta palavra que levanto como lamentação sobre vós, ó casa de Israel:

[[v30-5-2]]

^<<v30-5-2,2>>^ Caiu a virgem de Israel, nunca mais tornará a levantar-se; estendida está na sua terra, e não há quem a levante.

[[v30-5-3]]

^<<v30-5-3,3>>^ Porque assim diz o SENHOR Deus: A cidade da qual saem mil conservará cem, e aquela da qual saem cem conservará dez à casa de Israel.

[[v30-5-4]]

^<<v30-5-4,4>>^ Pois assim diz o SENHOR à casa de Israel: Buscai-me e vivei.

[[v30-5-5]]

^<<v30-5-5,5>>^ Porém não busqueis a Betel, nem venhais a Gilgal, nem passeis a Berseba, porque Gilgal, certamente, será levada cativa, e Betel será desfeita em nada.

[[v30-5-6]]

^<<v30-5-6,6>>^ Buscai ao SENHOR e vivei, para que não irrompa na casa de José como um fogo que a consuma, e não haja em Betel quem o apague.

[[v30-5-7]]

^<<v30-5-7,7>>^ Vós que converteis o juízo em alosna e deitais por terra a justiça,

[[v30-5-8]]

^<<v30-5-8,8>>^ procurai o que faz o Sete-estrelo e o Órion, e torna a densa treva em manhã, e muda o dia em noite; o que chama as águas do mar e as derrama sobre a terra; SENHOR é o seu nome.

[[v30-5-9]]

^<<v30-5-9,9>>^ É ele que faz vir súbita destruição sobre o forte e ruína contra a fortaleza.

[[v30-5-10]]

^<<v30-5-10,10>>^ Aborreceis na porta ao que vos repreende e abominais o que fala sinceramente.

[[v30-5-11]]

^<<v30-5-11,11>>^ Portanto, visto que pisais o pobre e dele exigis tributo de trigo, não habitareis nas casas de pedras lavradas que tendes edificado; nem bebereis do vinho das vides desejáveis que tendes plantado.

[[v30-5-12]]

^<<v30-5-12,12>>^ Porque sei serem muitas as vossas transgressões e graves os vossos pecados; afligis o justo, tomais suborno e rejeitais os necessitados na porta.

[[v30-5-13]]

^<<v30-5-13,13>>^ Portanto, o que for prudente guardará, então, silêncio, porque é tempo mau.

[[v30-5-14]]

^<<v30-5-14,14>>^ Buscai o bem e não o mal, para que vivais; e, assim, o SENHOR, o Deus dos Exércitos, estará convosco, como dizeis.

[[v30-5-15]]

^<<v30-5-15,15>>^ Aborrecei o mal, e amai o bem, e estabelecei na porta o juízo; talvez o SENHOR, o Deus dos Exércitos, se compadeça do restante de José.

[[v30-5-16]]

^<<v30-5-16,16>>^ Portanto, assim diz o Senhor, o SENHOR, Deus dos Exércitos: Em todas as praças haverá pranto; e em todas as ruas dirão: Ai! Ai! E ao lavrador chamarão para o pranto e, para o choro, os que sabem prantear.

[[v30-5-17]]

^<<v30-5-17,17>>^ Em todas as vinhas haverá pranto, porque passarei pelo meio de ti, diz o SENHOR.

[[v30-5-18]]

^<<v30-5-18,18>>^ Ai de vós que desejais o Dia do SENHOR! Para que desejais vós o Dia do SENHOR? É dia de trevas e não de luz.

[[v30-5-19]]

^<<v30-5-19,19>>^ Como se um homem fugisse de diante do leão, e se encontrasse com ele o urso; ou como se, entrando em casa, encostando a mão à parede, fosse mordido de uma cobra.

[[v30-5-20]]

^<<v30-5-20,20>>^ Não será, pois, o Dia do SENHOR trevas e não luz? Não será completa escuridão, sem nenhuma claridade?

[[v30-5-21]]

^<<v30-5-21,21>>^ Aborreço, desprezo as vossas festas e com as vossas assembleias solenes não tenho nenhum prazer.

[[v30-5-22]]

^<<v30-5-22,22>>^ E, ainda que me ofereçais holocaustos e vossas ofertas de manjares, não me agradarei deles, nem atentarei para as ofertas pacíficas de vossos animais cevados.

[[v30-5-23]]

^<<v30-5-23,23>>^ Afasta de mim o estrépito dos teus cânticos, porque não ouvirei as melodias das tuas liras.

[[v30-5-24]]

^<<v30-5-24,24>>^ Antes, corra o juízo como as águas; e a justiça, como ribeiro perene.

[[v30-5-25]]

^<<v30-5-25,25>>^ Apresentastes-me, vós, sacrifícios e ofertas de manjares no deserto por quarenta anos, ó casa de Israel?

[[v30-5-26]]

^<<v30-5-26,26>>^ Sim, levastes Sicute, vosso rei, Quium, vossa imagem, e o vosso deus-estrela, que fizestes para vós mesmos.

[[v30-5-27]]

^<<v30-5-27,27>>^ Por isso, vos desterrarei para além de Damasco, diz o SENHOR, cujo nome é Deus dos Exércitos.

'''

xref:030-amos/030-amos-004.adoc#v30-4-0[&#60; Capítulo Anterior] | <<v30-5-0,Topo>> | xref:030-amos/030-amos-006.adoc#v30-6-0[Próximo Capítulo &#62;]