include::./index.adoc[]

[[v30-9-0]]
=== Amós, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v30-9-1]]

^<<v30-9-1,1>>^ Vi o Senhor, que estava em pé junto ao altar; e me disse: Fere os capitéis, e estremecerão os umbrais, e faze tudo em pedaços sobre a cabeça de todos eles; matarei à espada até ao último deles; nenhum deles fugirá, e nenhum escapará.

[[v30-9-2]]

^<<v30-9-2,2>>^ Ainda que desçam ao mais profundo abismo, a minha mão os tirará de lá; se subirem ao céu, de lá os farei descer.

[[v30-9-3]]

^<<v30-9-3,3>>^ Se se esconderem no cimo do Carmelo, de lá buscá-los-ei e de lá os tirarei; e, se dos meus olhos se ocultarem no fundo do mar, de lá darei ordem à serpente, e ela os morderá.

[[v30-9-4]]

^<<v30-9-4,4>>^ Se forem para o cativeiro diante de seus inimigos, ali darei ordem à espada, e ela os matará; porei os olhos sobre eles, para o mal e não para o bem.

[[v30-9-5]]

^<<v30-9-5,5>>^ Porque o Senhor, o SENHOR dos Exércitos, é o que toca a terra, e ela se derrete, e todos os que habitam nela se enlutarão; ela subirá toda como o Nilo e abaixará como o rio do Egito.

[[v30-9-6]]

^<<v30-9-6,6>>^ Deus é o que edifica as suas câmaras no céu e a sua abóbada fundou na terra; é o que chama as águas do mar e as derrama sobre a terra; SENHOR é o seu nome.

[[v30-9-7]]

^<<v30-9-7,7>>^ Não sois vós para mim, ó filhos de Israel, como os filhos dos etíopes? — diz o SENHOR. Não fiz eu subir a Israel da terra do Egito, e de Caftor, os filisteus, e de Quir, os siros?

[[v30-9-8]]

^<<v30-9-8,8>>^ Eis que os olhos do SENHOR Deus estão contra este reino pecador, e eu o destruirei de sobre a face da terra; mas não destruirei de todo a casa de Jacó, diz o SENHOR.

[[v30-9-9]]

^<<v30-9-9,9>>^ Porque eis que darei ordens e sacudirei a casa de Israel entre todas as nações, assim como se sacode trigo no crivo, sem que caia na terra um só grão.

[[v30-9-10]]

^<<v30-9-10,10>>^ Todos os pecadores do meu povo morrerão à espada, os quais dizem: O mal não nos alcançará, nem nos encontrará.

[[v30-9-11]]

^<<v30-9-11,11>>^ Naquele dia, levantarei o tabernáculo caído de Davi, repararei as suas brechas; e, levantando-o das suas ruínas, restaurá-lo-ei como fora nos dias da antiguidade;

[[v30-9-12]]

^<<v30-9-12,12>>^ para que possuam o restante de Edom e todas as nações que são chamadas pelo meu nome, diz o SENHOR, que faz estas coisas.

[[v30-9-13]]

^<<v30-9-13,13>>^ Eis que vêm dias, diz o SENHOR, em que o que lavra segue logo ao que ceifa, e o que pisa as uvas, ao que lança a semente; os montes destilarão mosto, e todos os outeiros se derreterão.

[[v30-9-14]]

^<<v30-9-14,14>>^ Mudarei a sorte do meu povo de Israel; reedificarão as cidades assoladas e nelas habitarão, plantarão vinhas e beberão o seu vinho, farão pomares e lhes comerão o fruto.

[[v30-9-15]]

^<<v30-9-15,15>>^ Plantá-los-ei na sua terra, e, dessa terra que lhes dei, já não serão arrancados, diz o SENHOR, teu Deus.

'''

xref:030-amos/030-amos-008.adoc#v30-8-0[&#60; Capítulo Anterior] | <<v30-9-0,Topo>> | xref:031-obadias/031-obadias-001.adoc#v31-1-0[Próximo Capítulo &#62;]