include::./index.adoc[]

[[v30-3-0]]
=== Amós, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v30-3-1]]

^<<v30-3-1,1>>^ Ouvi a palavra que o SENHOR fala contra vós outros, filhos de Israel, contra toda a família que ele fez subir da terra do Egito, dizendo:

[[v30-3-2]]

^<<v30-3-2,2>>^ De todas as famílias da terra, somente a vós outros vos escolhi; portanto, eu vos punirei por todas as vossas iniquidades.

[[v30-3-3]]

^<<v30-3-3,3>>^ Andarão dois juntos, se não houver entre eles acordo?

[[v30-3-4]]

^<<v30-3-4,4>>^ Rugirá o leão no bosque, sem que tenha presa? Levantará o leãozinho no covil a sua voz, se nada tiver apanhado?

[[v30-3-5]]

^<<v30-3-5,5>>^ Cairá a ave no laço em terra, se não houver armadilha para ela? Levantar-se-á o laço da terra, sem que tenha apanhado alguma coisa?

[[v30-3-6]]

^<<v30-3-6,6>>^ Tocar-se-á a trombeta na cidade, sem que o povo se estremeça? Sucederá algum mal à cidade, sem que o SENHOR o tenha feito?

[[v30-3-7]]

^<<v30-3-7,7>>^ Certamente, o SENHOR Deus não fará coisa alguma, sem primeiro revelar o seu segredo aos seus servos, os profetas.

[[v30-3-8]]

^<<v30-3-8,8>>^ Rugiu o leão, quem não temerá? Falou o SENHOR Deus, quem não profetizará?

[[v30-3-9]]

^<<v30-3-9,9>>^ Fazei ouvir isto nos castelos de Asdode e nos castelos da terra do Egito e dizei: Ajuntai-vos sobre os montes de Samaria e vede que grandes tumultos há nela e que opressões há no meio dela.

[[v30-3-10]]

^<<v30-3-10,10>>^ Porque Israel não sabe fazer o que é reto, diz o SENHOR, e entesoura nos seus castelos a violência e a devastação.

[[v30-3-11]]

^<<v30-3-11,11>>^ Portanto, assim diz o SENHOR Deus: Um inimigo cercará a tua terra, derribará a tua fortaleza, e os teus castelos serão saqueados.

[[v30-3-12]]

^<<v30-3-12,12>>^ Assim diz o SENHOR: Como o pastor livra da boca do leão as duas pernas ou um pedacinho da orelha, assim serão salvos os filhos de Israel que habitam em Samaria com apenas o canto da cama e parte do leito.

[[v30-3-13]]

^<<v30-3-13,13>>^ Ouvi e protestai contra a casa de Jacó, diz o SENHOR Deus, o Deus dos Exércitos:

[[v30-3-14]]

^<<v30-3-14,14>>^ No dia em que eu punir Israel, por causa das suas transgressões, visitarei também os altares de Betel; e as pontas do altar serão cortadas e cairão por terra.

[[v30-3-15]]

^<<v30-3-15,15>>^ Derribarei a casa de inverno com a casa de verão; as casas de marfim perecerão, e as grandes casas serão destruídas, diz o SENHOR.

'''

xref:030-amos/030-amos-002.adoc#v30-2-0[&#60; Capítulo Anterior] | <<v30-3-0,Topo>> | xref:030-amos/030-amos-004.adoc#v30-4-0[Próximo Capítulo &#62;]