include::./index.adoc[]

[[v30-7-0]]
=== Amós, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v30-7-1]]

^<<v30-7-1,1>>^ Isto me fez ver o SENHOR Deus: eis que ele formava gafanhotos ao surgir o rebento da erva serôdia; e era a erva serôdia depois de findas as ceifas do rei.

[[v30-7-2]]

^<<v30-7-2,2>>^ Tendo eles comido de todo a erva da terra, disse eu: SENHOR Deus, perdoa, rogo-te; como subsistirá Jacó? Pois ele é pequeno.

[[v30-7-3]]

^<<v30-7-3,3>>^ Então, o SENHOR se arrependeu disso. Não acontecerá, disse o SENHOR.

[[v30-7-4]]

^<<v30-7-4,4>>^ Isto me mostrou o SENHOR Deus: eis que o SENHOR Deus chamou o fogo para exercer a sua justiça; este consumiu o grande abismo e devorava a herança do SENHOR.

[[v30-7-5]]

^<<v30-7-5,5>>^ Então, disse eu: SENHOR Deus, cessa agora; como subsistirá Jacó? Pois ele é pequeno.

[[v30-7-6]]

^<<v30-7-6,6>>^ E o SENHOR se arrependeu disso. Também não acontecerá, disse o SENHOR Deus.

[[v30-7-7]]

^<<v30-7-7,7>>^ Mostrou-me também isto: eis que o Senhor estava sobre um muro levantado a prumo; e tinha um prumo na mão.

[[v30-7-8]]

^<<v30-7-8,8>>^ O SENHOR me disse: Que vês tu, Amós? Respondi: Um prumo. Então, me disse o Senhor: Eis que eu porei o prumo no meio do meu povo de Israel; e jamais passarei por ele.

[[v30-7-9]]

^<<v30-7-9,9>>^ Mas os altos de Isaque serão assolados, e destruídos, os santuários de Israel; e levantar-me-ei com a espada contra a casa de Jeroboão.

[[v30-7-10]]

^<<v30-7-10,10>>^ Então, Amazias, o sacerdote de Betel, mandou dizer a Jeroboão, rei de Israel: Amós tem conspirado contra ti, no meio da casa de Israel; a terra não pode sofrer todas as suas palavras.

[[v30-7-11]]

^<<v30-7-11,11>>^ Porque assim diz Amós: Jeroboão morrerá à espada, e Israel, certamente, será levado para fora de sua terra, em cativeiro.

[[v30-7-12]]

^<<v30-7-12,12>>^ Então, Amazias disse a Amós: Vai-te, ó vidente, foge para a terra de Judá, e ali come o teu pão, e ali profetiza;

[[v30-7-13]]

^<<v30-7-13,13>>^ mas em Betel, daqui por diante, já não profetizarás, porque é o santuário do rei e o templo do reino.

[[v30-7-14]]

^<<v30-7-14,14>>^ Respondeu Amós e disse a Amazias: Eu não sou profeta, nem discípulo de profeta, mas boieiro e colhedor de sicômoros.

[[v30-7-15]]

^<<v30-7-15,15>>^ Mas o SENHOR me tirou de após o gado e o SENHOR me disse: Vai e profetiza ao meu povo de Israel.

[[v30-7-16]]

^<<v30-7-16,16>>^ Ora, pois, ouve a palavra do SENHOR. Tu dizes: Não profetizarás contra Israel, nem falarás contra a casa de Isaque.

[[v30-7-17]]

^<<v30-7-17,17>>^ Portanto, assim diz o SENHOR: Tua mulher se prostituirá na cidade, e teus filhos e tuas filhas cairão à espada, e a tua terra será repartida a cordel, e tu morrerás na terra imunda, e Israel, certamente, será levado cativo para fora da sua terra.

'''

xref:030-amos/030-amos-006.adoc#v30-6-0[&#60; Capítulo Anterior] | <<v30-7-0,Topo>> | xref:030-amos/030-amos-008.adoc#v30-8-0[Próximo Capítulo &#62;]