include::./index.adoc[]

[[v30-4-0]]
=== Amós, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v30-4-1]]

^<<v30-4-1,1>>^ Ouvi esta palavra, vacas de Basã, que estais no monte de Samaria, oprimis os pobres, esmagais os necessitados e dizeis a vosso marido: Dá cá, e bebamos.

[[v30-4-2]]

^<<v30-4-2,2>>^ Jurou o SENHOR Deus, pela sua santidade, que dias estão para vir sobre vós, em que vos levarão com anzóis e as vossas restantes com fisga de pesca.

[[v30-4-3]]

^<<v30-4-3,3>>^ Saireis cada uma em frente de si pelas brechas e vos lançareis para Hermom, disse o SENHOR.

[[v30-4-4]]

^<<v30-4-4,4>>^ Vinde a Betel e transgredi, a Gilgal, e multiplicai as transgressões; e, cada manhã, trazei os vossos sacrifícios e, de três em três dias, os vossos dízimos;

[[v30-4-5]]

^<<v30-4-5,5>>^ e oferecei sacrifício de louvores do que é levedado, e apregoai ofertas voluntárias, e publicai-as, porque disso gostais, ó filhos de Israel, disse o SENHOR Deus.

[[v30-4-6]]

^<<v30-4-6,6>>^ Também vos deixei de dentes limpos em todas as vossas cidades e com falta de pão em todos os vossos lugares; contudo, não vos convertestes a mim, disse o SENHOR.

[[v30-4-7]]

^<<v30-4-7,7>>^ Além disso, retive de vós a chuva, três meses ainda antes da ceifa; e fiz chover sobre uma cidade e sobre a outra, não; um campo teve chuva, mas o outro, que ficou sem chuva, se secou.

[[v30-4-8]]

^<<v30-4-8,8>>^ Andaram duas ou três cidades, indo a outra cidade para beberem água, mas não se saciaram; contudo, não vos convertestes a mim, disse o SENHOR.

[[v30-4-9]]

^<<v30-4-9,9>>^ Feri-vos com o crestamento e a ferrugem; a multidão das vossas hortas, e das vossas vinhas, e das vossas figueiras, e das vossas oliveiras, devorou-a o gafanhoto; contudo, não vos convertestes a mim, disse o SENHOR.

[[v30-4-10]]

^<<v30-4-10,10>>^ Enviei a peste contra vós outros à maneira do Egito; os vossos jovens, matei-os à espada, e os vossos cavalos, deixei-os levar presos, e o mau cheiro dos vossos arraiais fiz subir aos vossos narizes; contudo, não vos convertestes a mim, disse o SENHOR.

[[v30-4-11]]

^<<v30-4-11,11>>^ Subverti alguns dentre vós, como Deus subverteu a Sodoma e Gomorra, e vós fostes como um tição arrebatado da fogueira; contudo, não vos convertestes a mim, disse o SENHOR.

[[v30-4-12]]

^<<v30-4-12,12>>^ Portanto, assim te farei, ó Israel! E, porque isso te farei, prepara-te, ó Israel, para te encontrares com o teu Deus.

[[v30-4-13]]

^<<v30-4-13,13>>^ Porque é ele quem forma os montes, e cria o vento, e declara ao homem qual é o seu pensamento; e faz da manhã trevas e pisa os altos da terra; SENHOR, Deus dos Exércitos, é o seu nome.

'''

xref:030-amos/030-amos-003.adoc#v30-3-0[&#60; Capítulo Anterior] | <<v30-4-0,Topo>> | xref:030-amos/030-amos-005.adoc#v30-5-0[Próximo Capítulo &#62;]