include::./index.adoc[]

[[v30-8-0]]
=== Amós, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v30-8-1]]

^<<v30-8-1,1>>^ O SENHOR Deus me fez ver isto: eis aqui um cesto de frutos de verão.

[[v30-8-2]]

^<<v30-8-2,2>>^ E perguntou: Que vês, Amós? E eu respondi: Um cesto de frutos de verão. Então, o SENHOR me disse: Chegou o fim para o meu povo de Israel; e jamais passarei por ele.

[[v30-8-3]]

^<<v30-8-3,3>>^ Mas os cânticos do templo, naquele dia, serão uivos, diz o SENHOR Deus; multiplicar-se-ão os cadáveres; em todos os lugares, serão lançados fora. Silêncio!

[[v30-8-4]]

^<<v30-8-4,4>>^ Ouvi isto, vós que tendes gana contra o necessitado e destruís os miseráveis da terra,

[[v30-8-5]]

^<<v30-8-5,5>>^ dizendo: Quando passará a Festa da Lua Nova, para vendermos os cereais? E o sábado, para abrirmos os celeiros de trigo, diminuindo o efa, e aumentando o siclo, e procedendo dolosamente com balanças enganadoras,

[[v30-8-6]]

^<<v30-8-6,6>>^ para comprarmos os pobres por dinheiro e os necessitados por um par de sandálias e vendermos o refugo do trigo?

[[v30-8-7]]

^<<v30-8-7,7>>^ Jurou o SENHOR pela glória de Jacó: Eu não me esquecerei de todas as suas obras, para sempre!

[[v30-8-8]]

^<<v30-8-8,8>>^ Por causa disto, não estremecerá a terra? E não se enlutará todo aquele que habita nela? Certamente, levantar-se-á toda como o Nilo, será agitada e abaixará como o rio do Egito.

[[v30-8-9]]

^<<v30-8-9,9>>^ Sucederá que, naquele dia, diz o SENHOR Deus, farei que o sol se ponha ao meio-dia e entenebrecerei a terra em dia claro.

[[v30-8-10]]

^<<v30-8-10,10>>^ Converterei as vossas festas em luto e todos os vossos cânticos em lamentações; porei pano de saco sobre todos os lombos e calva sobre toda cabeça; e farei que isso seja como luto por filho único, luto cujo fim será como dia de amarguras.

[[v30-8-11]]

^<<v30-8-11,11>>^ Eis que vêm dias, diz o SENHOR Deus, em que enviarei fome sobre a terra, não de pão, nem sede de água, mas de ouvir as palavras do SENHOR.

[[v30-8-12]]

^<<v30-8-12,12>>^ Andarão de mar a mar e do Norte até ao Oriente; correrão por toda parte, procurando a palavra do SENHOR, e não a acharão.

[[v30-8-13]]

^<<v30-8-13,13>>^ Naquele dia, as virgens formosas e os jovens desmaiarão de sede,

[[v30-8-14]]

^<<v30-8-14,14>>^ os que, agora, juram pelo ídolo de Samaria e dizem: Como é certo viver o teu deus, ó Dã! E: Como é certo viver o culto de Berseba! Esses mesmos cairão e não se levantarão jamais.

'''

xref:030-amos/030-amos-007.adoc#v30-7-0[&#60; Capítulo Anterior] | <<v30-8-0,Topo>> | xref:030-amos/030-amos-009.adoc#v30-9-0[Próximo Capítulo &#62;]