include::./index.adoc[]

[[v66-18-0]]
=== Apocalipse, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-18-1]]

^<<v66-18-1,1>>^ Depois destas coisas, vi descer do céu outro anjo, que tinha grande autoridade, e a terra se iluminou com a sua glória.

[[v66-18-2]]

^<<v66-18-2,2>>^ Então, exclamou com potente voz, dizendo: Caiu! Caiu a grande Babilônia e se tornou morada de demônios, covil de toda espécie de espírito imundo e esconderijo de todo gênero de ave imunda e detestável,

[[v66-18-3]]

^<<v66-18-3,3>>^ pois todas as nações têm bebido do vinho do furor da sua prostituição. Com ela se prostituíram os reis da terra. Também os mercadores da terra se enriqueceram à custa da sua luxúria.

[[v66-18-4]]

^<<v66-18-4,4>>^ Ouvi outra voz do céu, dizendo: Retirai-vos dela, povo meu, para não serdes cúmplices em seus pecados e para não participardes dos seus flagelos;

[[v66-18-5]]

^<<v66-18-5,5>>^ porque os seus pecados se acumularam até ao céu, e Deus se lembrou dos atos iníquos que ela praticou.

[[v66-18-6]]

^<<v66-18-6,6>>^ Dai-lhe em retribuição como também ela retribuiu, pagai-lhe em dobro segundo as suas obras e, no cálice em que ela misturou bebidas, misturai dobrado para ela.

[[v66-18-7]]

^<<v66-18-7,7>>^ O quanto a si mesma se glorificou e viveu em luxúria, dai-lhe em igual medida tormento e pranto, porque diz consigo mesma: Estou sentada como rainha. Viúva, não sou. Pranto, nunca hei de ver!

[[v66-18-8]]

^<<v66-18-8,8>>^ Por isso, em um só dia, sobrevirão os seus flagelos: morte, pranto e fome; e será consumida no fogo, porque poderoso é o Senhor Deus, que a julgou.

[[v66-18-9]]

^<<v66-18-9,9>>^ Ora, chorarão e se lamentarão sobre ela os reis da terra, que com ela se prostituíram e viveram em luxúria, quando virem a fumaceira do seu incêndio,

[[v66-18-10]]

^<<v66-18-10,10>>^ e, conservando-se de longe, pelo medo do seu tormento, dizem: Ai! Ai! Tu, grande cidade, Babilônia, tu, poderosa cidade! Pois, em uma só hora, chegou o teu juízo.

[[v66-18-11]]

^<<v66-18-11,11>>^ E, sobre ela, choram e pranteiam os mercadores da terra, porque já ninguém compra a sua mercadoria,

[[v66-18-12]]

^<<v66-18-12,12>>^ mercadoria de ouro, de prata, de pedras preciosas, de pérolas, de linho finíssimo, de púrpura, de seda, de escarlata; e toda espécie de madeira odorífera, todo gênero de objeto de marfim, toda qualidade de móvel de madeira preciosíssima, de bronze, de ferro e de mármore;

[[v66-18-13]]

^<<v66-18-13,13>>^ e canela de cheiro, especiarias, incenso, unguento, bálsamo, vinho, azeite, flor de farinha, trigo, gado e ovelhas; e de cavalos, de carros, de escravos e até almas humanas.

[[v66-18-14]]

^<<v66-18-14,14>>^ O fruto sazonado, que a tua alma tanto apeteceu, se apartou de ti, e para ti se extinguiu tudo o que é delicado e esplêndido, e nunca jamais serão achados.

[[v66-18-15]]

^<<v66-18-15,15>>^ Os mercadores destas coisas, que, por meio dela, se enriqueceram, conservar-se-ão de longe, pelo medo do seu tormento, chorando e pranteando,

[[v66-18-16]]

^<<v66-18-16,16>>^ dizendo: Ai! Ai da grande cidade, que estava vestida de linho finíssimo, de púrpura, e de escarlata, adornada de ouro, e de pedras preciosas, e de pérolas,

[[v66-18-17]]

^<<v66-18-17,17>>^ porque, em uma só hora, ficou devastada tamanha riqueza! E todo piloto, e todo aquele que navega livremente, e marinheiros, e quantos labutam no mar conservaram-se de longe.

[[v66-18-18]]

^<<v66-18-18,18>>^ Então, vendo a fumaceira do seu incêndio, gritavam: Que cidade se compara à grande cidade?

[[v66-18-19]]

^<<v66-18-19,19>>^ Lançaram pó sobre a cabeça e, chorando e pranteando, gritavam: Ai! Ai da grande cidade, na qual se enriqueceram todos os que possuíam navios no mar, à custa da sua opulência, porque, em uma só hora, foi devastada!

[[v66-18-20]]

^<<v66-18-20,20>>^ Exultai sobre ela, ó céus, e vós, santos, apóstolos e profetas, porque Deus contra ela julgou a vossa causa.

[[v66-18-21]]

^<<v66-18-21,21>>^ Então, um anjo forte levantou uma pedra como grande pedra de moinho e arrojou-a para dentro do mar, dizendo: Assim, com ímpeto, será arrojada Babilônia, a grande cidade, e nunca jamais será achada.

[[v66-18-22]]

^<<v66-18-22,22>>^ E voz de harpistas, de músicos, de tocadores de flautas e de clarins jamais em ti se ouvirá, nem artífice algum de qualquer arte jamais em ti se achará, e nunca jamais em ti se ouvirá o ruído de pedra de moinho.

[[v66-18-23]]

^<<v66-18-23,23>>^ Também jamais em ti brilhará luz de candeia; nem voz de noivo ou de noiva jamais em ti se ouvirá, pois os teus mercadores foram os grandes da terra, porque todas as nações foram seduzidas pela tua feitiçaria.

[[v66-18-24]]

^<<v66-18-24,24>>^ E nela se achou sangue de profetas, de santos e de todos os que foram mortos sobre a terra.

'''

xref:066-apocalipse/066-apocalipse-017.adoc#v66-17-0[&#60; Capítulo Anterior] | <<v66-18-0,Topo>> | xref:066-apocalipse/066-apocalipse-019.adoc#v66-19-0[Próximo Capítulo &#62;]