include::./index.adoc[]

[[v66-6-0]]
=== Apocalipse, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-6-1]]

^<<v66-6-1,1>>^ Vi quando o Cordeiro abriu um dos sete selos e ouvi um dos quatro seres viventes dizendo, como se fosse voz de trovão: Vem!

[[v66-6-2]]

^<<v66-6-2,2>>^ Vi, então, e eis um cavalo branco e o seu cavaleiro com um arco; e foi-lhe dada uma coroa; e ele saiu vencendo e para vencer.

[[v66-6-3]]

^<<v66-6-3,3>>^ Quando abriu o segundo selo, ouvi o segundo ser vivente dizendo: Vem!

[[v66-6-4]]

^<<v66-6-4,4>>^ E saiu outro cavalo, vermelho; e ao seu cavaleiro, foi-lhe dado tirar a paz da terra para que os homens se matassem uns aos outros; também lhe foi dada uma grande espada.

[[v66-6-5]]

^<<v66-6-5,5>>^ Quando abriu o terceiro selo, ouvi o terceiro ser vivente dizendo: Vem! Então, vi, e eis um cavalo preto e o seu cavaleiro com uma balança na mão.

[[v66-6-6]]

^<<v66-6-6,6>>^ E ouvi uma como que voz no meio dos quatro seres viventes dizendo: Uma medida de trigo por um denário; três medidas de cevada por um denário; e não danifiques o azeite e o vinho.

[[v66-6-7]]

^<<v66-6-7,7>>^ Quando o Cordeiro abriu o quarto selo, ouvi a voz do quarto ser vivente dizendo: Vem!

[[v66-6-8]]

^<<v66-6-8,8>>^ E olhei, e eis um cavalo amarelo e o seu cavaleiro, sendo este chamado Morte; e o Inferno o estava seguindo, e foi-lhes dada autoridade sobre a quarta parte da terra para matar à espada, pela fome, com a mortandade e por meio das feras da terra.

[[v66-6-9]]

^<<v66-6-9,9>>^ Quando ele abriu o quinto selo, vi, debaixo do altar, as almas daqueles que tinham sido mortos por causa da palavra de Deus e por causa do testemunho que sustentavam.

[[v66-6-10]]

^<<v66-6-10,10>>^ Clamaram em grande voz, dizendo: Até quando, ó Soberano Senhor, santo e verdadeiro, não julgas, nem vingas o nosso sangue dos que habitam sobre a terra?

[[v66-6-11]]

^<<v66-6-11,11>>^ Então, a cada um deles foi dada uma vestidura branca, e lhes disseram que repousassem ainda por pouco tempo, até que também se completasse o número dos seus conservos e seus irmãos que iam ser mortos como igualmente eles foram.

[[v66-6-12]]

^<<v66-6-12,12>>^ Vi quando o Cordeiro abriu o sexto selo, e sobreveio grande terremoto. O sol se tornou negro como saco de crina, a lua toda, como sangue,

[[v66-6-13]]

^<<v66-6-13,13>>^ as estrelas do céu caíram pela terra, como a figueira, quando abalada por vento forte, deixa cair os seus figos verdes,

[[v66-6-14]]

^<<v66-6-14,14>>^ e o céu recolheu-se como um pergaminho quando se enrola. Então, todos os montes e ilhas foram movidos do seu lugar.

[[v66-6-15]]

^<<v66-6-15,15>>^ Os reis da terra, os grandes, os comandantes, os ricos, os poderosos e todo escravo e todo livre se esconderam nas cavernas e nos penhascos dos montes

[[v66-6-16]]

^<<v66-6-16,16>>^ e disseram aos montes e aos rochedos: Caí sobre nós e escondei-nos da face daquele que se assenta no trono e da ira do Cordeiro,

[[v66-6-17]]

^<<v66-6-17,17>>^ porque chegou o grande Dia da ira deles; e quem é que pode suster-se?

'''

xref:066-apocalipse/066-apocalipse-005.adoc#v66-5-0[&#60; Capítulo Anterior] | <<v66-6-0,Topo>> | xref:066-apocalipse/066-apocalipse-007.adoc#v66-7-0[Próximo Capítulo &#62;]