include::./index.adoc[]

[[v66-7-0]]
=== Apocalipse, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-7-1]]

^<<v66-7-1,1>>^ Depois disto, vi quatro anjos em pé nos quatro cantos da terra, conservando seguros os quatro ventos da terra, para que nenhum vento soprasse sobre a terra, nem sobre o mar, nem sobre árvore alguma.

[[v66-7-2]]

^<<v66-7-2,2>>^ Vi outro anjo que subia do nascente do sol, tendo o selo do Deus vivo, e clamou em grande voz aos quatro anjos, aqueles aos quais fora dado fazer dano à terra e ao mar,

[[v66-7-3]]

^<<v66-7-3,3>>^ dizendo: Não danifiqueis nem a terra, nem o mar, nem as árvores, até selarmos na fronte os servos do nosso Deus.

[[v66-7-4]]

^<<v66-7-4,4>>^ Então, ouvi o número dos que foram selados, que era cento e quarenta e quatro mil, de todas as tribos dos filhos de Israel:

[[v66-7-5]]

^<<v66-7-5,5>>^ da tribo de Judá foram selados doze mil; da tribo de Rúben, doze mil; da tribo de Gade, doze mil;

[[v66-7-6]]

^<<v66-7-6,6>>^ da tribo de Aser, doze mil; da tribo de Naftali, doze mil; da tribo de Manassés, doze mil;

[[v66-7-7]]

^<<v66-7-7,7>>^ da tribo de Simeão, doze mil; da tribo de Levi, doze mil; da tribo de Issacar, doze mil;

[[v66-7-8]]

^<<v66-7-8,8>>^ da tribo de Zebulom, doze mil; da tribo de José, doze mil; da tribo de Benjamim foram selados doze mil.

[[v66-7-9]]

^<<v66-7-9,9>>^ Depois destas coisas, vi, e eis grande multidão que ninguém podia enumerar, de todas as nações, tribos, povos e línguas, em pé diante do trono e diante do Cordeiro, vestidos de vestiduras brancas, com palmas nas mãos;

[[v66-7-10]]

^<<v66-7-10,10>>^ e clamavam em grande voz, dizendo: Ao nosso Deus, que se assenta no trono, e ao Cordeiro, pertence a salvação.

[[v66-7-11]]

^<<v66-7-11,11>>^ Todos os anjos estavam de pé rodeando o trono, os anciãos e os quatro seres viventes, e ante o trono se prostraram sobre o seu rosto, e adoraram a Deus,

[[v66-7-12]]

^<<v66-7-12,12>>^ dizendo: Amém! O louvor, e a glória, e a sabedoria, e as ações de graças, e a honra, e o poder, e a força sejam ao nosso Deus, pelos séculos dos séculos. Amém!

[[v66-7-13]]

^<<v66-7-13,13>>^ Um dos anciãos tomou a palavra, dizendo: Estes, que se vestem de vestiduras brancas, quem são e donde vieram?

[[v66-7-14]]

^<<v66-7-14,14>>^ Respondi-lhe: meu Senhor, tu o sabes. Ele, então, me disse: São estes os que vêm da grande tribulação, lavaram suas vestiduras e as alvejaram no sangue do Cordeiro,

[[v66-7-15]]

^<<v66-7-15,15>>^ razão por que se acham diante do trono de Deus e o servem de dia e de noite no seu santuário; e aquele que se assenta no trono estenderá sobre eles o seu tabernáculo.

[[v66-7-16]]

^<<v66-7-16,16>>^ Jamais terão fome, nunca mais terão sede, não cairá sobre eles o sol, nem ardor algum,

[[v66-7-17]]

^<<v66-7-17,17>>^ pois o Cordeiro que se encontra no meio do trono os apascentará e os guiará para as fontes da água da vida. E Deus lhes enxugará dos olhos toda lágrima.

'''

xref:066-apocalipse/066-apocalipse-006.adoc#v66-6-0[&#60; Capítulo Anterior] | <<v66-7-0,Topo>> | xref:066-apocalipse/066-apocalipse-008.adoc#v66-8-0[Próximo Capítulo &#62;]