include::./index.adoc[]

[[v66-10-0]]
=== Apocalipse, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-10-1]]

^<<v66-10-1,1>>^ Vi outro anjo forte descendo do céu, envolto em nuvem, com o arco-íris por cima de sua cabeça; o rosto era como o sol, e as pernas, como colunas de fogo;

[[v66-10-2]]

^<<v66-10-2,2>>^ e tinha na mão um livrinho aberto. Pôs o pé direito sobre o mar e o esquerdo, sobre a terra,

[[v66-10-3]]

^<<v66-10-3,3>>^ e bradou em grande voz, como ruge um leão, e, quando bradou, desferiram os sete trovões as suas próprias vozes.

[[v66-10-4]]

^<<v66-10-4,4>>^ Logo que falaram os sete trovões, eu ia escrever, mas ouvi uma voz do céu, dizendo: Guarda em segredo as coisas que os sete trovões falaram e não as escrevas.

[[v66-10-5]]

^<<v66-10-5,5>>^ Então, o anjo que vi em pé sobre o mar e sobre a terra levantou a mão direita para o céu

[[v66-10-6]]

^<<v66-10-6,6>>^ e jurou por aquele que vive pelos séculos dos séculos, o mesmo que criou o céu, a terra, o mar e tudo quanto neles existe: Já não haverá demora,

[[v66-10-7]]

^<<v66-10-7,7>>^ mas, nos dias da voz do sétimo anjo, quando ele estiver para tocar a trombeta, cumprir-se-á, então, o mistério de Deus, segundo ele anunciou aos seus servos, os profetas.

[[v66-10-8]]

^<<v66-10-8,8>>^ A voz que ouvi, vinda do céu, estava de novo falando comigo e dizendo: Vai e toma o livro que se acha aberto na mão do anjo em pé sobre o mar e sobre a terra.

[[v66-10-9]]

^<<v66-10-9,9>>^ Fui, pois, ao anjo, dizendo-lhe que me desse o livrinho. Ele, então, me falou: Toma-o e devora-o; certamente, ele será amargo ao teu estômago, mas, na tua boca, doce como mel.

[[v66-10-10]]

^<<v66-10-10,10>>^ Tomei o livrinho da mão do anjo e o devorei, e, na minha boca, era doce como mel; quando, porém, o comi, o meu estômago ficou amargo.

[[v66-10-11]]

^<<v66-10-11,11>>^ Então, me disseram: É necessário que ainda profetizes a respeito de muitos povos, nações, línguas e reis.

'''

xref:066-apocalipse/066-apocalipse-009.adoc#v66-9-0[&#60; Capítulo Anterior] | <<v66-10-0,Topo>> | xref:066-apocalipse/066-apocalipse-011.adoc#v66-11-0[Próximo Capítulo &#62;]