include::./index.adoc[]

[[v66-22-0]]
=== Apocalipse, 22
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-22-1]]

^<<v66-22-1,1>>^ Então, me mostrou o rio da água da vida, brilhante como cristal, que sai do trono de Deus e do Cordeiro.

[[v66-22-2]]

^<<v66-22-2,2>>^ No meio da sua praça, de uma e outra margem do rio, está a árvore da vida, que produz doze frutos, dando o seu fruto de mês em mês, e as folhas da árvore são para a cura dos povos.

[[v66-22-3]]

^<<v66-22-3,3>>^ Nunca mais haverá qualquer maldição. Nela, estará o trono de Deus e do Cordeiro. Os seus servos o servirão,

[[v66-22-4]]

^<<v66-22-4,4>>^ contemplarão a sua face, e na sua fronte está o nome dele.

[[v66-22-5]]

^<<v66-22-5,5>>^ Então, já não haverá noite, nem precisam eles de luz de candeia, nem da luz do sol, porque o Senhor Deus brilhará sobre eles, e reinarão pelos séculos dos séculos.

[[v66-22-6]]

^<<v66-22-6,6>>^ Disse-me ainda: Estas palavras são fiéis e verdadeiras. O Senhor, o Deus dos espíritos dos profetas, enviou seu anjo para mostrar aos seus servos as coisas que em breve devem acontecer.

[[v66-22-7]]

^<<v66-22-7,7>>^ Eis que venho sem demora. Bem-aventurado aquele que guarda as palavras da profecia deste livro.

[[v66-22-8]]

^<<v66-22-8,8>>^ Eu, João, sou quem ouviu e viu estas coisas. E, quando as ouvi e vi, prostrei-me ante os pés do anjo que me mostrou essas coisas, para adorá-lo.

[[v66-22-9]]

^<<v66-22-9,9>>^ Então, ele me disse: Vê, não faças isso; eu sou conservo teu, dos teus irmãos, os profetas, e dos que guardam as palavras deste livro. Adora a Deus.

[[v66-22-10]]

^<<v66-22-10,10>>^ Disse-me ainda: Não seles as palavras da profecia deste livro, porque o tempo está próximo.

[[v66-22-11]]

^<<v66-22-11,11>>^ Continue o injusto fazendo injustiça, continue o imundo ainda sendo imundo; o justo continue na prática da justiça, e o santo continue a santificar-se.

[[v66-22-12]]

^<<v66-22-12,12>>^ E eis que venho sem demora, e comigo está o galardão que tenho para retribuir a cada um segundo as suas obras.

[[v66-22-13]]

^<<v66-22-13,13>>^ Eu sou o Alfa e o Ômega, o Primeiro e o Último, o Princípio e o Fim.

[[v66-22-14]]

^<<v66-22-14,14>>^ Bem-aventurados aqueles que lavam as suas vestiduras [no sangue do Cordeiro], para que lhes assista o direito à árvore da vida, e entrem na cidade pelas portas.

[[v66-22-15]]

^<<v66-22-15,15>>^ Fora ficam os cães, os feiticeiros, os impuros, os assassinos, os idólatras e todo aquele que ama e pratica a mentira.

[[v66-22-16]]

^<<v66-22-16,16>>^ Eu, Jesus, enviei o meu anjo para vos testificar estas coisas às igrejas. Eu sou a Raiz e a Geração de Davi, a brilhante Estrela da manhã.

[[v66-22-17]]

^<<v66-22-17,17>>^ O Espírito e a noiva dizem: Vem! Aquele que ouve, diga: Vem! Aquele que tem sede venha, e quem quiser receba de graça a água da vida.

[[v66-22-18]]

^<<v66-22-18,18>>^ Eu, a todo aquele que ouve as palavras da profecia deste livro, testifico: Se alguém lhes fizer qualquer acréscimo, Deus lhe acrescentará os flagelos escritos neste livro;

[[v66-22-19]]

^<<v66-22-19,19>>^ e, se alguém tirar qualquer coisa das palavras do livro desta profecia, Deus tirará a sua parte da árvore da vida, da cidade santa e das coisas que se acham escritas neste livro.

[[v66-22-20]]

^<<v66-22-20,20>>^ Aquele que dá testemunho destas coisas diz: Certamente, venho sem demora.  Amém! Vem, Senhor Jesus!

[[v66-22-21]]

^<<v66-22-21,21>>^ A graça do Senhor Jesus seja com todos.

'''

xref:066-apocalipse/066-apocalipse-021.adoc#v66-21-0[&#60; Capítulo Anterior] | <<v66-22-0,Topo>> | **Próximo Capítulo &#62;**