include::./index.adoc[]

[[v66-12-0]]
=== Apocalipse, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-12-1]]

^<<v66-12-1,1>>^ Viu-se grande sinal no céu, a saber, uma mulher vestida do sol com a lua debaixo dos pés e uma coroa de doze estrelas na cabeça,

[[v66-12-2]]

^<<v66-12-2,2>>^ que, achando-se grávida, grita com as dores de parto, sofrendo tormentos para dar à luz.

[[v66-12-3]]

^<<v66-12-3,3>>^ Viu-se, também, outro sinal no céu, e eis um dragão, grande, vermelho, com sete cabeças, dez chifres e, nas cabeças, sete diademas.

[[v66-12-4]]

^<<v66-12-4,4>>^ A sua cauda arrastava a terça parte das estrelas do céu, as quais lançou para a terra; e o dragão se deteve em frente da mulher que estava para dar à luz, a fim de lhe devorar o filho quando nascesse.

[[v66-12-5]]

^<<v66-12-5,5>>^ Nasceu-lhe, pois, um filho varão, que há de reger todas as nações com cetro de ferro. E o seu filho foi arrebatado para Deus até ao seu trono.

[[v66-12-6]]

^<<v66-12-6,6>>^ A mulher, porém, fugiu para o deserto, onde lhe havia Deus preparado lugar para que nele a sustentem durante mil duzentos e sessenta dias.

[[v66-12-7]]

^<<v66-12-7,7>>^ Houve peleja no céu. Miguel e os seus anjos pelejaram contra o dragão. Também pelejaram o dragão e seus anjos;

[[v66-12-8]]

^<<v66-12-8,8>>^ todavia, não prevaleceram; nem mais se achou no céu o lugar deles.

[[v66-12-9]]

^<<v66-12-9,9>>^ E foi expulso o grande dragão, a antiga serpente, que se chama diabo e Satanás, o sedutor de todo o mundo, sim, foi atirado para a terra, e, com ele, os seus anjos.

[[v66-12-10]]

^<<v66-12-10,10>>^ Então, ouvi grande voz do céu, proclamando: Agora, veio a salvação, o poder, o reino do nosso Deus e a autoridade do seu Cristo, pois foi expulso o acusador de nossos irmãos, o mesmo que os acusa de dia e de noite, diante do nosso Deus.

[[v66-12-11]]

^<<v66-12-11,11>>^ Eles, pois, o venceram por causa do sangue do Cordeiro e por causa da palavra do testemunho que deram e, mesmo em face da morte, não amaram a própria vida.

[[v66-12-12]]

^<<v66-12-12,12>>^ Por isso, festejai, ó céus, e vós, os que neles habitais. Ai da terra e do mar, pois o diabo desceu até vós, cheio de grande cólera, sabendo que pouco tempo lhe resta.

[[v66-12-13]]

^<<v66-12-13,13>>^ Quando, pois, o dragão se viu atirado para a terra, perseguiu a mulher que dera à luz o filho varão;

[[v66-12-14]]

^<<v66-12-14,14>>^ e foram dadas à mulher as duas asas da grande águia, para que voasse até ao deserto, ao seu lugar, aí onde é sustentada durante um tempo, tempos e metade de um tempo, fora da vista da serpente.

[[v66-12-15]]

^<<v66-12-15,15>>^ Então, a serpente arrojou da sua boca, atrás da mulher, água como um rio, a fim de fazer com que ela fosse arrebatada pelo rio.

[[v66-12-16]]

^<<v66-12-16,16>>^ A terra, porém, socorreu a mulher; e a terra abriu a boca e engoliu o rio que o dragão tinha arrojado de sua boca.

[[v66-12-17]]

^<<v66-12-17,17>>^ Irou-se o dragão contra a mulher e foi pelejar com os restantes da sua descendência, os que guardam os mandamentos de Deus e têm o testemunho de Jesus; e se pôs em pé sobre a areia do mar.

'''

xref:066-apocalipse/066-apocalipse-011.adoc#v66-11-0[&#60; Capítulo Anterior] | <<v66-12-0,Topo>> | xref:066-apocalipse/066-apocalipse-013.adoc#v66-13-0[Próximo Capítulo &#62;]