include::./index.adoc[]

[[v66-4-0]]
=== Apocalipse, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-4-1]]

^<<v66-4-1,1>>^ Depois destas coisas, olhei, e eis não somente uma porta aberta no céu, como também a primeira voz que ouvi, como de trombeta ao falar comigo, dizendo: Sobe para aqui, e te mostrarei o que deve acontecer depois destas coisas.

[[v66-4-2]]

^<<v66-4-2,2>>^ Imediatamente, eu me achei em espírito, e eis armado no céu um trono, e, no trono, alguém sentado;

[[v66-4-3]]

^<<v66-4-3,3>>^ e esse que se acha assentado é semelhante, no aspecto, a pedra de jaspe e de sardônio, e, ao redor do trono, há um arco-íris semelhante, no aspecto, a esmeralda.

[[v66-4-4]]

^<<v66-4-4,4>>^ Ao redor do trono, há também vinte e quatro tronos, e assentados neles, vinte e quatro anciãos vestidos de branco, em cujas cabeças estão coroas de ouro.

[[v66-4-5]]

^<<v66-4-5,5>>^ Do trono saem relâmpagos, vozes e trovões, e, diante do trono, ardem sete tochas de fogo, que são os sete Espíritos de Deus.

[[v66-4-6]]

^<<v66-4-6,6>>^ Há diante do trono um como que mar de vidro, semelhante ao cristal, e também, no meio do trono e à volta do trono, quatro seres viventes cheios de olhos por diante e por detrás.

[[v66-4-7]]

^<<v66-4-7,7>>^ O primeiro ser vivente é semelhante a leão, o segundo, semelhante a novilho, o terceiro tem o rosto como de homem, e o quarto ser vivente é semelhante à águia quando está voando.

[[v66-4-8]]

^<<v66-4-8,8>>^ E os quatro seres viventes, tendo cada um deles, respectivamente, seis asas, estão cheios de olhos, ao redor e por dentro; não têm descanso, nem de dia nem de noite, proclamando: Santo, Santo, Santo é o Senhor Deus, o Todo-Poderoso, aquele que era, que é e que há de vir.

[[v66-4-9]]

^<<v66-4-9,9>>^ Quando esses seres viventes derem glória, honra e ações de graças ao que se encontra sentado no trono, ao que vive pelos séculos dos séculos,

[[v66-4-10]]

^<<v66-4-10,10>>^ os vinte e quatro anciãos prostrar-se-ão diante daquele que se encontra sentado no trono, adorarão o que vive pelos séculos dos séculos e depositarão as suas coroas diante do trono, proclamando:

[[v66-4-11]]

^<<v66-4-11,11>>^ Tu és digno, Senhor e Deus nosso, de receber a glória, a honra e o poder, porque todas as coisas tu criaste, sim, por causa da tua vontade vieram a existir e foram criadas.

'''

xref:066-apocalipse/066-apocalipse-003.adoc#v66-3-0[&#60; Capítulo Anterior] | <<v66-4-0,Topo>> | xref:066-apocalipse/066-apocalipse-005.adoc#v66-5-0[Próximo Capítulo &#62;]