include::./index.adoc[]

[[v66-13-0]]
=== Apocalipse, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-13-1]]

^<<v66-13-1,1>>^ Vi emergir do mar uma besta que tinha dez chifres e sete cabeças e, sobre os chifres, dez diademas e, sobre as cabeças, nomes de blasfêmia.

[[v66-13-2]]

^<<v66-13-2,2>>^ A besta que vi era semelhante a leopardo, com pés como de urso e boca como de leão. E deu-lhe o dragão o seu poder, o seu trono e grande autoridade.

[[v66-13-3]]

^<<v66-13-3,3>>^ Então, vi uma de suas cabeças como golpeada de morte, mas essa ferida mortal foi curada; e toda a terra se maravilhou, seguindo a besta;

[[v66-13-4]]

^<<v66-13-4,4>>^ e adoraram o dragão porque deu a sua autoridade à besta; também adoraram a besta, dizendo: Quem é semelhante à besta? Quem pode pelejar contra ela?

[[v66-13-5]]

^<<v66-13-5,5>>^ Foi-lhe dada uma boca que proferia arrogâncias e blasfêmias e autoridade para agir quarenta e dois meses;

[[v66-13-6]]

^<<v66-13-6,6>>^ e abriu a boca em blasfêmias contra Deus, para lhe difamar o nome e difamar o tabernáculo, a saber, os que habitam no céu.

[[v66-13-7]]

^<<v66-13-7,7>>^ Foi-lhe dado, também, que pelejasse contra os santos e os vencesse. Deu-se-lhe ainda autoridade sobre cada tribo, povo, língua e nação;

[[v66-13-8]]

^<<v66-13-8,8>>^ e adorá-la-ão todos os que habitam sobre a terra, aqueles cujos nomes não foram escritos no Livro da Vida do Cordeiro que foi morto desde a fundação do mundo.

[[v66-13-9]]

^<<v66-13-9,9>>^ Se alguém tem ouvidos, ouça.

[[v66-13-10]]

^<<v66-13-10,10>>^ Se alguém leva para cativeiro, para cativeiro vai. Se alguém matar à espada, necessário é que seja morto à espada. Aqui está a perseverança e a fidelidade dos santos.

[[v66-13-11]]

^<<v66-13-11,11>>^ Vi ainda outra besta emergir da terra; possuía dois chifres, parecendo cordeiro, mas falava como dragão.

[[v66-13-12]]

^<<v66-13-12,12>>^ Exerce toda a autoridade da primeira besta na sua presença. Faz com que a terra e os seus habitantes adorem a primeira besta, cuja ferida mortal fora curada.

[[v66-13-13]]

^<<v66-13-13,13>>^ Também opera grandes sinais, de maneira que até fogo do céu faz descer à terra, diante dos homens.

[[v66-13-14]]

^<<v66-13-14,14>>^ Seduz os que habitam sobre a terra por causa dos sinais que lhe foi dado executar diante da besta, dizendo aos que habitam sobre a terra que façam uma imagem à besta, àquela que, ferida à espada, sobreviveu;

[[v66-13-15]]

^<<v66-13-15,15>>^ e lhe foi dado comunicar fôlego à imagem da besta, para que não só a imagem falasse, como ainda fizesse morrer quantos não adorassem a imagem da besta.

[[v66-13-16]]

^<<v66-13-16,16>>^ A todos, os pequenos e os grandes, os ricos e os pobres, os livres e os escravos, faz que lhes seja dada certa marca sobre a mão direita ou sobre a fronte,

[[v66-13-17]]

^<<v66-13-17,17>>^ para que ninguém possa comprar ou vender, senão aquele que tem a marca, o nome da besta ou o número do seu nome.

[[v66-13-18]]

^<<v66-13-18,18>>^ Aqui está a sabedoria. Aquele que tem entendimento calcule o número da besta, pois é número de homem. Ora, esse número é seiscentos e sessenta e seis.

'''

xref:066-apocalipse/066-apocalipse-012.adoc#v66-12-0[&#60; Capítulo Anterior] | <<v66-13-0,Topo>> | xref:066-apocalipse/066-apocalipse-014.adoc#v66-14-0[Próximo Capítulo &#62;]