include::./index.adoc[]

[[v66-5-0]]
=== Apocalipse, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-5-1]]

^<<v66-5-1,1>>^ Vi, na mão direita daquele que estava sentado no trono, um livro escrito por dentro e por fora, de todo selado com sete selos.

[[v66-5-2]]

^<<v66-5-2,2>>^ Vi, também, um anjo forte, que proclamava em grande voz: Quem é digno de abrir o livro e de lhe desatar os selos?

[[v66-5-3]]

^<<v66-5-3,3>>^ Ora, nem no céu, nem sobre a terra, nem debaixo da terra, ninguém podia abrir o livro, nem mesmo olhar para ele;

[[v66-5-4]]

^<<v66-5-4,4>>^ e eu chorava muito, porque ninguém foi achado digno de abrir o livro, nem mesmo de olhar para ele.

[[v66-5-5]]

^<<v66-5-5,5>>^ Todavia, um dos anciãos me disse: Não chores; eis que o Leão da tribo de Judá, a Raiz de Davi, venceu para abrir o livro e os seus sete selos.

[[v66-5-6]]

^<<v66-5-6,6>>^ Então, vi, no meio do trono e dos quatro seres viventes e entre os anciãos, de pé, um Cordeiro como tendo sido morto. Ele tinha sete chifres, bem como sete olhos, que são os sete Espíritos de Deus enviados por toda a terra.

[[v66-5-7]]

^<<v66-5-7,7>>^ Veio, pois, e tomou o livro da mão direita daquele que estava sentado no trono;

[[v66-5-8]]

^<<v66-5-8,8>>^ e, quando tomou o livro, os quatro seres viventes e os vinte e quatro anciãos prostraram-se diante do Cordeiro, tendo cada um deles uma harpa e taças de ouro cheias de incenso, que são as orações dos santos,

[[v66-5-9]]

^<<v66-5-9,9>>^ e entoavam novo cântico, dizendo: Digno és de tomar o livro e de abrir-lhe os selos, porque foste morto e com o teu sangue compraste para Deus os que procedem de toda tribo, língua, povo e nação

[[v66-5-10]]

^<<v66-5-10,10>>^ e para o nosso Deus os constituíste reino e sacerdotes; e reinarão sobre a terra.

[[v66-5-11]]

^<<v66-5-11,11>>^ Vi e ouvi uma voz de muitos anjos ao redor do trono, dos seres viventes e dos anciãos, cujo número era de milhões de milhões e milhares de milhares,

[[v66-5-12]]

^<<v66-5-12,12>>^ proclamando em grande voz: Digno é o Cordeiro que foi morto de receber o poder, e riqueza, e sabedoria, e força, e honra, e glória, e louvor.

[[v66-5-13]]

^<<v66-5-13,13>>^ Então, ouvi que toda criatura que há no céu e sobre a terra, debaixo da terra e sobre o mar, e tudo o que neles há, estava dizendo: Àquele que está sentado no trono e ao Cordeiro, seja o louvor, e a honra, e a glória, e o domínio pelos séculos dos séculos.

[[v66-5-14]]

^<<v66-5-14,14>>^ E os quatro seres viventes respondiam: Amém! Também os anciãos prostraram-se e adoraram.

'''

xref:066-apocalipse/066-apocalipse-004.adoc#v66-4-0[&#60; Capítulo Anterior] | <<v66-5-0,Topo>> | xref:066-apocalipse/066-apocalipse-006.adoc#v66-6-0[Próximo Capítulo &#62;]