include::./index.adoc[]

[[v66-17-0]]
=== Apocalipse, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-17-1]]

^<<v66-17-1,1>>^ Veio um dos sete anjos que têm as sete taças e falou comigo, dizendo: Vem, mostrar-te-ei o julgamento da grande meretriz que se acha sentada sobre muitas águas,

[[v66-17-2]]

^<<v66-17-2,2>>^ com quem se prostituíram os reis da terra; e, com o vinho de sua devassidão, foi que se embebedaram os que habitam na terra.

[[v66-17-3]]

^<<v66-17-3,3>>^ Transportou-me o anjo, em espírito, a um deserto e vi uma mulher montada numa besta escarlate, besta repleta de nomes de blasfêmia, com sete cabeças e dez chifres.

[[v66-17-4]]

^<<v66-17-4,4>>^ Achava-se a mulher vestida de púrpura e de escarlata, adornada de ouro, de pedras preciosas e de pérolas, tendo na mão um cálice de ouro transbordante de abominações e com as imundícias da sua prostituição.

[[v66-17-5]]

^<<v66-17-5,5>>^ Na sua fronte, achava-se escrito um nome, um mistério: Babilônia, a Grande, a Mãe das Meretrizes e das Abominações da Terra .

[[v66-17-6]]

^<<v66-17-6,6>>^ Então, vi a mulher embriagada com o sangue dos santos e com o sangue das testemunhas de Jesus; e, quando a vi, admirei-me com grande espanto.

[[v66-17-7]]

^<<v66-17-7,7>>^ O anjo, porém, me disse: Por que te admiraste? Dir-te-ei o mistério da mulher e da besta que tem as sete cabeças e os dez chifres e que leva a mulher:

[[v66-17-8]]

^<<v66-17-8,8>>^ a besta que viste, era e não é, está para emergir do abismo e caminha para a destruição. E aqueles que habitam sobre a terra, cujos nomes não foram escritos no Livro da Vida desde a fundação do mundo, se admirarão, vendo a besta que era e não é, mas aparecerá.

[[v66-17-9]]

^<<v66-17-9,9>>^ Aqui está o sentido, que tem sabedoria: as sete cabeças são sete montes, nos quais a mulher está sentada. São também sete reis,

[[v66-17-10]]

^<<v66-17-10,10>>^ dos quais caíram cinco, um existe, e o outro ainda não chegou; e, quando chegar, tem de durar pouco.

[[v66-17-11]]

^<<v66-17-11,11>>^ E a besta, que era e não é, também é ele, o oitavo rei, e procede dos sete, e caminha para a destruição.

[[v66-17-12]]

^<<v66-17-12,12>>^ Os dez chifres que viste são dez reis, os quais ainda não receberam reino, mas recebem autoridade como reis, com a besta, durante uma hora.

[[v66-17-13]]

^<<v66-17-13,13>>^ Têm estes um só pensamento e oferecem à besta o poder e a autoridade que possuem.

[[v66-17-14]]

^<<v66-17-14,14>>^ Pelejarão eles contra o Cordeiro, e o Cordeiro os vencerá, pois é o Senhor dos senhores e o Rei dos reis; vencerão também os chamados, eleitos e fiéis que se acham com ele.

[[v66-17-15]]

^<<v66-17-15,15>>^ Falou-me ainda: As águas que viste, onde a meretriz está assentada, são povos, multidões, nações e línguas.

[[v66-17-16]]

^<<v66-17-16,16>>^ Os dez chifres que viste e a besta, esses odiarão a meretriz, e a farão devastada e despojada, e lhe comerão as carnes, e a consumirão no fogo.

[[v66-17-17]]

^<<v66-17-17,17>>^ Porque em seu coração incutiu Deus que realizem o seu pensamento, o executem à uma e deem à besta o reino que possuem, até que se cumpram as palavras de Deus.

[[v66-17-18]]

^<<v66-17-18,18>>^ A mulher que viste é a grande cidade que domina sobre os reis da terra.

'''

xref:066-apocalipse/066-apocalipse-016.adoc#v66-16-0[&#60; Capítulo Anterior] | <<v66-17-0,Topo>> | xref:066-apocalipse/066-apocalipse-018.adoc#v66-18-0[Próximo Capítulo &#62;]