include::./index.adoc[]

[[v66-21-0]]
=== Apocalipse, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-21-1]]

^<<v66-21-1,1>>^ Vi novo céu e nova terra, pois o primeiro céu e a primeira terra passaram, e o mar já não existe.

[[v66-21-2]]

^<<v66-21-2,2>>^ Vi também a cidade santa, a nova Jerusalém, que descia do céu, da parte de Deus, ataviada como noiva adornada para o seu esposo.

[[v66-21-3]]

^<<v66-21-3,3>>^ Então, ouvi grande voz vinda do trono, dizendo: Eis o tabernáculo de Deus com os homens. Deus habitará com eles. Eles serão povos de Deus, e Deus mesmo estará com eles.

[[v66-21-4]]

^<<v66-21-4,4>>^ E lhes enxugará dos olhos toda lágrima, e a morte já não existirá, já não haverá luto, nem pranto, nem dor, porque as primeiras coisas passaram.

[[v66-21-5]]

^<<v66-21-5,5>>^ E aquele que está assentado no trono disse: Eis que faço novas todas as coisas. E acrescentou: Escreve, porque estas palavras são fiéis e verdadeiras.

[[v66-21-6]]

^<<v66-21-6,6>>^ Disse-me ainda: Tudo está feito. Eu sou o Alfa e o Ômega, o Princípio e o Fim. Eu, a quem tem sede, darei de graça da fonte da água da vida.

[[v66-21-7]]

^<<v66-21-7,7>>^ O vencedor herdará estas coisas, e eu lhe serei Deus, e ele me será filho.

[[v66-21-8]]

^<<v66-21-8,8>>^ Quanto, porém, aos covardes, aos incrédulos, aos abomináveis, aos assassinos, aos impuros, aos feiticeiros, aos idólatras e a todos os mentirosos, a parte que lhes cabe será no lago que arde com fogo e enxofre, a saber, a segunda morte.

[[v66-21-9]]

^<<v66-21-9,9>>^ Então, veio um dos sete anjos que têm as sete taças cheias dos últimos sete flagelos e falou comigo, dizendo: Vem, mostrar-te-ei a noiva, a esposa do Cordeiro;

[[v66-21-10]]

^<<v66-21-10,10>>^ e me transportou, em espírito, até a uma grande e elevada montanha e me mostrou a santa cidade, Jerusalém, que descia do céu, da parte de Deus,

[[v66-21-11]]

^<<v66-21-11,11>>^ a qual tem a glória de Deus. O seu fulgor era semelhante a uma pedra preciosíssima, como pedra de jaspe cristalina.

[[v66-21-12]]

^<<v66-21-12,12>>^ Tinha grande e alta muralha, doze portas, e, junto às portas, doze anjos, e, sobre elas, nomes inscritos, que são os nomes das doze tribos dos filhos de Israel.

[[v66-21-13]]

^<<v66-21-13,13>>^ Três portas se achavam a leste, três, ao norte, três, ao sul, e três, a oeste.

[[v66-21-14]]

^<<v66-21-14,14>>^ A muralha da cidade tinha doze fundamentos, e estavam sobre estes os doze nomes dos doze apóstolos do Cordeiro.

[[v66-21-15]]

^<<v66-21-15,15>>^ Aquele que falava comigo tinha por medida uma vara de ouro para medir a cidade, as suas portas e a sua muralha.

[[v66-21-16]]

^<<v66-21-16,16>>^ A cidade é quadrangular, de comprimento e largura iguais. E mediu a cidade com a vara até doze mil estádios. O seu comprimento, largura e altura são iguais.

[[v66-21-17]]

^<<v66-21-17,17>>^ Mediu também a sua muralha, cento e quarenta e quatro côvados, medida de homem, isto é, de anjo.

[[v66-21-18]]

^<<v66-21-18,18>>^ A estrutura da muralha é de jaspe; também a cidade é de ouro puro, semelhante a vidro límpido.

[[v66-21-19]]

^<<v66-21-19,19>>^ Os fundamentos da muralha da cidade estão adornados de toda espécie de pedras preciosas. O primeiro fundamento é de jaspe; o segundo, de safira; o terceiro, de calcedônia; o quarto, de esmeralda;

[[v66-21-20]]

^<<v66-21-20,20>>^ o quinto, de sardônio; o sexto, de sárdio; o sétimo, de crisólito; o oitavo, de berilo; o nono, de topázio; o décimo, de crisópraso; o undécimo, de jacinto; e o duodécimo, de ametista.

[[v66-21-21]]

^<<v66-21-21,21>>^ As doze portas são doze pérolas, e cada uma dessas portas, de uma só pérola. A praça da cidade é de ouro puro, como vidro transparente.

[[v66-21-22]]

^<<v66-21-22,22>>^ Nela, não vi santuário, porque o seu santuário é o Senhor, o Deus Todo-Poderoso, e o Cordeiro.

[[v66-21-23]]

^<<v66-21-23,23>>^ A cidade não precisa nem do sol, nem da lua, para lhe darem claridade, pois a glória de Deus a iluminou, e o Cordeiro é a sua lâmpada.

[[v66-21-24]]

^<<v66-21-24,24>>^ As nações andarão mediante a sua luz, e os reis da terra lhe trazem a sua glória.

[[v66-21-25]]

^<<v66-21-25,25>>^ As suas portas nunca jamais se fecharão de dia, porque, nela, não haverá noite.

[[v66-21-26]]

^<<v66-21-26,26>>^ E lhe trarão a glória e a honra das nações.

[[v66-21-27]]

^<<v66-21-27,27>>^ Nela, nunca jamais penetrará coisa alguma contaminada, nem o que pratica abominação e mentira, mas somente os inscritos no Livro da Vida do Cordeiro.

'''

xref:066-apocalipse/066-apocalipse-020.adoc#v66-20-0[&#60; Capítulo Anterior] | <<v66-21-0,Topo>> | xref:066-apocalipse/066-apocalipse-022.adoc#v66-22-0[Próximo Capítulo &#62;]