include::./index.adoc[]

[[v66-3-0]]
=== Apocalipse, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-3-1]]

^<<v66-3-1,1>>^ Ao anjo da igreja em Sardes escreve: Estas coisas diz aquele que tem os sete Espíritos de Deus e as sete estrelas: Conheço as tuas obras, que tens nome de que vives e estás morto.

[[v66-3-2]]

^<<v66-3-2,2>>^ Sê vigilante e consolida o resto que estava para morrer, porque não tenho achado íntegras as tuas obras na presença do meu Deus.

[[v66-3-3]]

^<<v66-3-3,3>>^ Lembra-te, pois, do que tens recebido e ouvido, guarda-o e arrepende-te. Porquanto, se não vigiares, virei como ladrão, e não conhecerás de modo algum em que hora virei contra ti.

[[v66-3-4]]

^<<v66-3-4,4>>^ Tens, contudo, em Sardes, umas poucas pessoas que não contaminaram as suas vestiduras e andarão de branco junto comigo, pois são dignas.

[[v66-3-5]]

^<<v66-3-5,5>>^ O vencedor será assim vestido de vestiduras brancas, e de modo nenhum apagarei o seu nome do Livro da Vida; pelo contrário, confessarei o seu nome diante de meu Pai e diante dos seus anjos.

[[v66-3-6]]

^<<v66-3-6,6>>^ Quem tem ouvidos, ouça o que o Espírito diz às igrejas.

[[v66-3-7]]

^<<v66-3-7,7>>^ Ao anjo da igreja em Filadélfia escreve: Estas coisas diz o santo, o verdadeiro, aquele que tem a chave de Davi, que abre, e ninguém fechará, e que fecha, e ninguém abrirá:

[[v66-3-8]]

^<<v66-3-8,8>>^ Conheço as tuas obras — eis que tenho posto diante de ti uma porta aberta, a qual ninguém pode fechar — que tens pouca força, entretanto, guardaste a minha palavra e não negaste o meu nome.

[[v66-3-9]]

^<<v66-3-9,9>>^ Eis farei que alguns dos que são da sinagoga de Satanás, desses que a si mesmos se declaram judeus e não são, mas mentem, eis que os farei vir e prostrar-se aos teus pés e conhecer que eu te amei.

[[v66-3-10]]

^<<v66-3-10,10>>^ Porque guardaste a palavra da minha perseverança, também eu te guardarei da hora da provação que há de vir sobre o mundo inteiro, para experimentar os que habitam sobre a terra.

[[v66-3-11]]

^<<v66-3-11,11>>^ Venho sem demora. Conserva o que tens, para que ninguém tome a tua coroa.

[[v66-3-12]]

^<<v66-3-12,12>>^ Ao vencedor, fá-lo-ei coluna no santuário do meu Deus, e daí jamais sairá; gravarei também sobre ele o nome do meu Deus, o nome da cidade do meu Deus, a nova Jerusalém que desce do céu, vinda da parte do meu Deus, e o meu novo nome.

[[v66-3-13]]

^<<v66-3-13,13>>^ Quem tem ouvidos, ouça o que o Espírito diz às igrejas.

[[v66-3-14]]

^<<v66-3-14,14>>^ Ao anjo da igreja em Laodiceia escreve: Estas coisas diz o Amém, a testemunha fiel e verdadeira, o princípio da criação de Deus:

[[v66-3-15]]

^<<v66-3-15,15>>^ Conheço as tuas obras, que nem és frio nem quente. Quem dera fosses frio ou quente!

[[v66-3-16]]

^<<v66-3-16,16>>^ Assim, porque és morno e nem és quente nem frio, estou a ponto de vomitar-te da minha boca;

[[v66-3-17]]

^<<v66-3-17,17>>^ pois dizes: Estou rico e abastado e não preciso de coisa alguma, e nem sabes que tu és infeliz, sim, miserável, pobre, cego e nu.

[[v66-3-18]]

^<<v66-3-18,18>>^ Aconselho-te que de mim compres ouro refinado pelo fogo para te enriqueceres, vestiduras brancas para te vestires, a fim de que não seja manifesta a vergonha da tua nudez, e colírio para ungires os olhos, a fim de que vejas.

[[v66-3-19]]

^<<v66-3-19,19>>^ Eu repreendo e disciplino a quantos amo. Sê, pois, zeloso e arrepende-te.

[[v66-3-20]]

^<<v66-3-20,20>>^ Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei em sua casa e cearei com ele, e ele, comigo.

[[v66-3-21]]

^<<v66-3-21,21>>^ Ao vencedor, dar-lhe-ei sentar-se comigo no meu trono, assim como também eu venci e me sentei com meu Pai no seu trono.

[[v66-3-22]]

^<<v66-3-22,22>>^ Quem tem ouvidos, ouça o que o Espírito diz às igrejas.

'''

xref:066-apocalipse/066-apocalipse-002.adoc#v66-2-0[&#60; Capítulo Anterior] | <<v66-3-0,Topo>> | xref:066-apocalipse/066-apocalipse-004.adoc#v66-4-0[Próximo Capítulo &#62;]