include::./index.adoc[]

[[v66-1-0]]
=== Apocalipse, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-1-1]]

^<<v66-1-1,1>>^ Revelação de Jesus Cristo, que Deus lhe deu para mostrar aos seus servos as coisas que em breve devem acontecer e que ele, enviando por intermédio do seu anjo, notificou ao seu servo João,

[[v66-1-2]]

^<<v66-1-2,2>>^ o qual atestou a palavra de Deus e o testemunho de Jesus Cristo, quanto a tudo o que viu.

[[v66-1-3]]

^<<v66-1-3,3>>^ Bem-aventurados aqueles que leem e aqueles que ouvem as palavras da profecia e guardam as coisas nela escritas, pois o tempo está próximo.

[[v66-1-4]]

^<<v66-1-4,4>>^ João, às sete igrejas que se encontram na Ásia, graça e paz a vós outros, da parte daquele que é, que era e que há de vir, da parte dos sete Espíritos que se acham diante do seu trono

[[v66-1-5]]

^<<v66-1-5,5>>^ e da parte de Jesus Cristo, a Fiel Testemunha, o Primogênito dos mortos e o Soberano dos reis da terra. Àquele que nos ama, e, pelo seu sangue, nos libertou dos nossos pecados,

[[v66-1-6]]

^<<v66-1-6,6>>^ e nos constituiu reino, sacerdotes para o seu Deus e Pai, a ele a glória e o domínio pelos séculos dos séculos. Amém!

[[v66-1-7]]

^<<v66-1-7,7>>^ Eis que vem com as nuvens, e todo olho o verá, até quantos o traspassaram. E todas as tribos da terra se lamentarão sobre ele. Certamente. Amém!

[[v66-1-8]]

^<<v66-1-8,8>>^ Eu sou o Alfa e Ômega,  diz o Senhor Deus, aquele que é, que era e que há de vir, o Todo-Poderoso.

[[v66-1-9]]

^<<v66-1-9,9>>^ Eu, João, irmão vosso e companheiro na tribulação, no reino e na perseverança, em Jesus, achei-me na ilha chamada Patmos, por causa da palavra de Deus e do testemunho de Jesus.

[[v66-1-10]]

^<<v66-1-10,10>>^ Achei-me em espírito, no dia do Senhor, e ouvi, por detrás de mim, grande voz, como de trombeta,

[[v66-1-11]]

^<<v66-1-11,11>>^ dizendo: O que vês escreve em livro e manda às sete igrejas: Éfeso, Esmirna, Pérgamo, Tiatira, Sardes, Filadélfia e Laodiceia.

[[v66-1-12]]

^<<v66-1-12,12>>^ Voltei-me para ver quem falava comigo e, voltado, vi sete candeeiros de ouro

[[v66-1-13]]

^<<v66-1-13,13>>^ e, no meio dos candeeiros, um semelhante a filho de homem, com vestes talares e cingido, à altura do peito, com uma cinta de ouro.

[[v66-1-14]]

^<<v66-1-14,14>>^ A sua cabeça e cabelos eram brancos como alva lã, como neve; os olhos, como chama de fogo;

[[v66-1-15]]

^<<v66-1-15,15>>^ os pés, semelhantes ao bronze polido, como que refinado numa fornalha; a voz, como voz de muitas águas.

[[v66-1-16]]

^<<v66-1-16,16>>^ Tinha na mão direita sete estrelas, e da boca saía-lhe uma afiada espada de dois gumes. O seu rosto brilhava como o sol na sua força.

[[v66-1-17]]

^<<v66-1-17,17>>^ Quando o vi, caí a seus pés como morto. Porém ele pôs sobre mim a mão direita, dizendo: Não temas; eu sou o primeiro e o último

[[v66-1-18]]

^<<v66-1-18,18>>^ e aquele que vive; estive morto, mas eis que estou vivo pelos séculos dos séculos e tenho as chaves da morte e do inferno.

[[v66-1-19]]

^<<v66-1-19,19>>^ Escreve, pois, as coisas que viste, e as que são, e as que hão de acontecer depois destas.

[[v66-1-20]]

^<<v66-1-20,20>>^ Quanto ao mistério das sete estrelas que viste na minha mão direita e aos sete candeeiros de ouro, as sete estrelas são os anjos das sete igrejas, e os sete candeeiros são as sete igrejas.

'''

xref:065-judas/065-judas-001.adoc#v65-1-0[&#60; Capítulo Anterior] | <<v66-1-0,Topo>> | xref:066-apocalipse/066-apocalipse-002.adoc#v66-2-0[Próximo Capítulo &#62;]