include::./index.adoc[]

[[v66-15-0]]
=== Apocalipse, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-15-1]]

^<<v66-15-1,1>>^ Vi no céu outro sinal grande e admirável: sete anjos tendo os sete últimos flagelos, pois com estes se consumou a cólera de Deus.

[[v66-15-2]]

^<<v66-15-2,2>>^ Vi como que um mar de vidro, mesclado de fogo, e os vencedores da besta, da sua imagem e do número do seu nome, que se achavam em pé no mar de vidro, tendo harpas de Deus;

[[v66-15-3]]

^<<v66-15-3,3>>^ e entoavam o cântico de Moisés, servo de Deus, e o cântico do Cordeiro, dizendo: Grandes e admiráveis são as tuas obras, Senhor Deus, Todo-Poderoso! Justos e verdadeiros são os teus caminhos, ó Rei das nações!

[[v66-15-4]]

^<<v66-15-4,4>>^ Quem não temerá e não glorificará o teu nome, ó Senhor? Pois só tu és santo; por isso, todas as nações virão e adorarão diante de ti, porque os teus atos de justiça se fizeram manifestos.

[[v66-15-5]]

^<<v66-15-5,5>>^ Depois destas coisas, olhei, e abriu-se no céu o santuário do tabernáculo do Testemunho,

[[v66-15-6]]

^<<v66-15-6,6>>^ e os sete anjos que tinham os sete flagelos saíram do santuário, vestidos de linho puro e resplandecente e cingidos ao peito com cintas de ouro.

[[v66-15-7]]

^<<v66-15-7,7>>^ Então, um dos quatro seres viventes deu aos sete anjos sete taças de ouro, cheias da cólera de Deus, que vive pelos séculos dos séculos.

[[v66-15-8]]

^<<v66-15-8,8>>^ O santuário se encheu de fumaça procedente da glória de Deus e do seu poder, e ninguém podia penetrar no santuário, enquanto não se cumprissem os sete flagelos dos sete anjos.

'''

xref:066-apocalipse/066-apocalipse-014.adoc#v66-14-0[&#60; Capítulo Anterior] | <<v66-15-0,Topo>> | xref:066-apocalipse/066-apocalipse-016.adoc#v66-16-0[Próximo Capítulo &#62;]