include::./index.adoc[]

[[v66-14-0]]
=== Apocalipse, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-14-1]]

^<<v66-14-1,1>>^ Olhei, e eis o Cordeiro em pé sobre o monte Sião, e com ele cento e quarenta e quatro mil, tendo na fronte escrito o seu nome e o nome de seu Pai.

[[v66-14-2]]

^<<v66-14-2,2>>^ Ouvi uma voz do céu como voz de muitas águas, como voz de grande trovão; também a voz que ouvi era como de harpistas quando tangem a sua harpa.

[[v66-14-3]]

^<<v66-14-3,3>>^ Entoavam novo cântico diante do trono, diante dos quatro seres viventes e dos anciãos. E ninguém pôde aprender o cântico, senão os cento e quarenta e quatro mil que foram comprados da terra.

[[v66-14-4]]

^<<v66-14-4,4>>^ São estes os que não se macularam com mulheres, porque são castos. São eles os seguidores do Cordeiro por onde quer que vá. São os que foram redimidos dentre os homens, primícias para Deus e para o Cordeiro;

[[v66-14-5]]

^<<v66-14-5,5>>^ e não se achou mentira na sua boca; não têm mácula.

[[v66-14-6]]

^<<v66-14-6,6>>^ Vi outro anjo voando pelo meio do céu, tendo um evangelho eterno para pregar aos que se assentam sobre a terra, e a cada nação, e tribo, e língua, e povo,

[[v66-14-7]]

^<<v66-14-7,7>>^ dizendo, em grande voz: Temei a Deus e dai-lhe glória, pois é chegada a hora do seu juízo; e adorai aquele que fez o céu, e a terra, e o mar, e as fontes das águas.

[[v66-14-8]]

^<<v66-14-8,8>>^ Seguiu-se outro anjo, o segundo, dizendo: Caiu, caiu a grande Babilônia que tem dado a beber a todas as nações do vinho da fúria da sua prostituição.

[[v66-14-9]]

^<<v66-14-9,9>>^ Seguiu-se a estes outro anjo, o terceiro, dizendo, em grande voz: Se alguém adora a besta e a sua imagem e recebe a sua marca na fronte ou sobre a mão,

[[v66-14-10]]

^<<v66-14-10,10>>^ também esse beberá do vinho da cólera de Deus, preparado, sem mistura, do cálice da sua ira, e será atormentado com fogo e enxofre, diante dos santos anjos e na presença do Cordeiro.

[[v66-14-11]]

^<<v66-14-11,11>>^ A fumaça do seu tormento sobe pelos séculos dos séculos, e não têm descanso algum, nem de dia nem de noite, os adoradores da besta e da sua imagem e quem quer que receba a marca do seu nome.

[[v66-14-12]]

^<<v66-14-12,12>>^ Aqui está a perseverança dos santos, os que guardam os mandamentos de Deus e a fé em Jesus.

[[v66-14-13]]

^<<v66-14-13,13>>^ Então, ouvi uma voz do céu, dizendo: Escreve: Bem-aventurados os mortos que, desde agora, morrem no Senhor. Sim, diz o Espírito, para que descansem das suas fadigas, pois as suas obras os acompanham.

[[v66-14-14]]

^<<v66-14-14,14>>^ Olhei, e eis uma nuvem branca, e sentado sobre a nuvem um semelhante a filho de homem, tendo na cabeça uma coroa de ouro e na mão uma foice afiada.

[[v66-14-15]]

^<<v66-14-15,15>>^ Outro anjo saiu do santuário, gritando em grande voz para aquele que se achava sentado sobre a nuvem: Toma a tua foice e ceifa, pois chegou a hora de ceifar, visto que a seara da terra já amadureceu!

[[v66-14-16]]

^<<v66-14-16,16>>^ E aquele que estava sentado sobre a nuvem passou a sua foice sobre a terra, e a terra foi ceifada.

[[v66-14-17]]

^<<v66-14-17,17>>^ Então, saiu do santuário, que se encontra no céu, outro anjo, tendo ele mesmo também uma foice afiada.

[[v66-14-18]]

^<<v66-14-18,18>>^ Saiu ainda do altar outro anjo, aquele que tem autoridade sobre o fogo, e falou em grande voz ao que tinha a foice afiada, dizendo: Toma a tua foice afiada e ajunta os cachos da videira da terra, porquanto as suas uvas estão amadurecidas!

[[v66-14-19]]

^<<v66-14-19,19>>^ Então, o anjo passou a sua foice na terra, e vindimou a videira da terra, e lançou-a no grande lagar da cólera de Deus.

[[v66-14-20]]

^<<v66-14-20,20>>^ E o lagar foi pisado fora da cidade, e correu sangue do lagar até aos freios dos cavalos, numa extensão de mil e seiscentos estádios.

'''

xref:066-apocalipse/066-apocalipse-013.adoc#v66-13-0[&#60; Capítulo Anterior] | <<v66-14-0,Topo>> | xref:066-apocalipse/066-apocalipse-015.adoc#v66-15-0[Próximo Capítulo &#62;]