include::./index.adoc[]

[[v66-9-0]]
=== Apocalipse, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-9-1]]

^<<v66-9-1,1>>^ O quinto anjo tocou a trombeta, e vi uma estrela caída do céu na terra. E foi-lhe dada a chave do poço do abismo.

[[v66-9-2]]

^<<v66-9-2,2>>^ Ela abriu o poço do abismo, e subiu fumaça do poço como fumaça de grande fornalha, e, com a fumaceira saída do poço, escureceu-se o sol e o ar.

[[v66-9-3]]

^<<v66-9-3,3>>^ Também da fumaça saíram gafanhotos para a terra; e foi-lhes dado poder como o que têm os escorpiões da terra,

[[v66-9-4]]

^<<v66-9-4,4>>^ e foi-lhes dito que não causassem dano à erva da terra, nem a qualquer coisa verde, nem a árvore alguma e tão somente aos homens que não têm o selo de Deus sobre a fronte.

[[v66-9-5]]

^<<v66-9-5,5>>^ Foi-lhes também dado, não que os matassem, e sim que os atormentassem durante cinco meses. E o seu tormento era como tormento de escorpião quando fere alguém.

[[v66-9-6]]

^<<v66-9-6,6>>^ Naqueles dias, os homens buscarão a morte e não a acharão; também terão ardente desejo de morrer, mas a morte fugirá deles.

[[v66-9-7]]

^<<v66-9-7,7>>^ O aspecto dos gafanhotos era semelhante a cavalos preparados para a peleja; na sua cabeça havia como que coroas parecendo de ouro; e o seu rosto era como rosto de homem;

[[v66-9-8]]

^<<v66-9-8,8>>^ tinham também cabelos, como cabelos de mulher; os seus dentes, como dentes de leão;

[[v66-9-9]]

^<<v66-9-9,9>>^ tinham couraças, como couraças de ferro; o barulho que as suas asas faziam era como o barulho de carros de muitos cavalos, quando correm à peleja;

[[v66-9-10]]

^<<v66-9-10,10>>^ tinham ainda cauda, como escorpiões, e ferrão; na cauda tinham poder para causar dano aos homens, por cinco meses;

[[v66-9-11]]

^<<v66-9-11,11>>^ e tinham sobre eles, como seu rei, o anjo do abismo, cujo nome em hebraico é Abadom, e em grego, Apoliom.

[[v66-9-12]]

^<<v66-9-12,12>>^ O primeiro ai passou. Eis que, depois destas coisas, vêm ainda dois ais.

[[v66-9-13]]

^<<v66-9-13,13>>^ O sexto anjo tocou a trombeta, e ouvi uma voz procedente dos quatro ângulos do altar de ouro que se encontra na presença de Deus,

[[v66-9-14]]

^<<v66-9-14,14>>^ dizendo ao sexto anjo, o mesmo que tem a trombeta: Solta os quatro anjos que se encontram atados junto ao grande rio Eufrates.

[[v66-9-15]]

^<<v66-9-15,15>>^ Foram, então, soltos os quatro anjos que se achavam preparados para a hora, o dia, o mês e o ano, para que matassem a terça parte dos homens.

[[v66-9-16]]

^<<v66-9-16,16>>^ O número dos exércitos da cavalaria era de vinte mil vezes dez milhares; eu ouvi o seu número.

[[v66-9-17]]

^<<v66-9-17,17>>^ Assim, nesta visão, contemplei que os cavalos e os seus cavaleiros tinham couraças cor de fogo, de jacinto e de enxofre. A cabeça dos cavalos era como cabeça de leão, e de sua boca saía fogo, fumaça e enxofre.

[[v66-9-18]]

^<<v66-9-18,18>>^ Por meio destes três flagelos, a saber, pelo fogo, pela fumaça e pelo enxofre que saíam da sua boca, foi morta a terça parte dos homens;

[[v66-9-19]]

^<<v66-9-19,19>>^ pois a força dos cavalos estava na sua boca e na sua cauda, porquanto a sua cauda se parecia com serpentes, e tinha cabeça, e com ela causavam dano.

[[v66-9-20]]

^<<v66-9-20,20>>^ Os outros homens, aqueles que não foram mortos por esses flagelos, não se arrependeram das obras das suas mãos, deixando de adorar os demônios e os ídolos de ouro, de prata, de cobre, de pedra e de pau, que nem podem ver, nem ouvir, nem andar;

[[v66-9-21]]

^<<v66-9-21,21>>^ nem ainda se arrependeram dos seus assassínios, nem das suas feitiçarias, nem da sua prostituição, nem dos seus furtos.

'''

xref:066-apocalipse/066-apocalipse-008.adoc#v66-8-0[&#60; Capítulo Anterior] | <<v66-9-0,Topo>> | xref:066-apocalipse/066-apocalipse-010.adoc#v66-10-0[Próximo Capítulo &#62;]