include::./index.adoc[]

[[v66-8-0]]
=== Apocalipse, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-8-1]]

^<<v66-8-1,1>>^ Quando o Cordeiro abriu o sétimo selo, houve silêncio no céu cerca de meia hora.

[[v66-8-2]]

^<<v66-8-2,2>>^ Então, vi os sete anjos que se acham em pé diante de Deus, e lhes foram dadas sete trombetas.

[[v66-8-3]]

^<<v66-8-3,3>>^ Veio outro anjo e ficou de pé junto ao altar, com um incensário de ouro, e foi-lhe dado muito incenso para oferecê-lo com as orações de todos os santos sobre o altar de ouro que se acha diante do trono;

[[v66-8-4]]

^<<v66-8-4,4>>^ e da mão do anjo subiu à presença de Deus a fumaça do incenso, com as orações dos santos.

[[v66-8-5]]

^<<v66-8-5,5>>^ E o anjo tomou o incensário, encheu-o do fogo do altar e o atirou à terra. E houve trovões, vozes, relâmpagos e terremoto.

[[v66-8-6]]

^<<v66-8-6,6>>^ Então, os sete anjos que tinham as sete trombetas prepararam-se para tocar.

[[v66-8-7]]

^<<v66-8-7,7>>^ O primeiro anjo tocou a trombeta, e houve saraiva e fogo de mistura com sangue, e foram atirados à terra. Foi, então, queimada a terça parte da terra, e das árvores, e também toda erva verde.

[[v66-8-8]]

^<<v66-8-8,8>>^ O segundo anjo tocou a trombeta, e uma como que grande montanha ardendo em chamas foi atirada ao mar, cuja terça parte se tornou em sangue,

[[v66-8-9]]

^<<v66-8-9,9>>^ e morreu a terça parte da criação que tinha vida, existente no mar, e foi destruída a terça parte das embarcações.

[[v66-8-10]]

^<<v66-8-10,10>>^ O terceiro anjo tocou a trombeta, e caiu do céu sobre a terça parte dos rios, e sobre as fontes das águas uma grande estrela, ardendo como tocha.

[[v66-8-11]]

^<<v66-8-11,11>>^ O nome da estrela é Absinto; e a terça parte das águas se tornou em absinto, e muitos dos homens morreram por causa dessas águas, porque se tornaram amargosas.

[[v66-8-12]]

^<<v66-8-12,12>>^ O quarto anjo tocou a trombeta, e foi ferida a terça parte do sol, da lua e das estrelas, para que a terça parte deles escurecesse e, na sua terça parte, não brilhasse, tanto o dia como também a noite.

[[v66-8-13]]

^<<v66-8-13,13>>^ Então, vi e ouvi uma águia que, voando pelo meio do céu, dizia em grande voz: Ai! Ai! Ai dos que moram na terra, por causa das restantes vozes da trombeta dos três anjos que ainda têm de tocar!

'''

xref:066-apocalipse/066-apocalipse-007.adoc#v66-7-0[&#60; Capítulo Anterior] | <<v66-8-0,Topo>> | xref:066-apocalipse/066-apocalipse-009.adoc#v66-9-0[Próximo Capítulo &#62;]