include::./index.adoc[]

[[v66-19-0]]
=== Apocalipse, 19
// ara ?, ARA - Almeida Revista e Atualizada

[[v66-19-1]]

^<<v66-19-1,1>>^ Depois destas coisas, ouvi no céu uma como grande voz de numerosa multidão, dizendo: Aleluia! A salvação, e a glória, e o poder são do nosso Deus,

[[v66-19-2]]

^<<v66-19-2,2>>^ porquanto verdadeiros e justos são os seus juízos, pois julgou a grande meretriz que corrompia a terra com a sua prostituição e das mãos dela vingou o sangue dos seus servos.

[[v66-19-3]]

^<<v66-19-3,3>>^ Segunda vez disseram: Aleluia! E a sua fumaça sobe pelos séculos dos séculos.

[[v66-19-4]]

^<<v66-19-4,4>>^ Os vinte e quatro anciãos e os quatro seres viventes prostraram-se e adoraram a Deus, que se acha sentado no trono, dizendo: Amém! Aleluia!

[[v66-19-5]]

^<<v66-19-5,5>>^ Saiu uma voz do trono, exclamando: Dai louvores ao nosso Deus, todos os seus servos, os que o temeis, os pequenos e os grandes.

[[v66-19-6]]

^<<v66-19-6,6>>^ Então, ouvi uma como voz de numerosa multidão, como de muitas águas e como de fortes trovões, dizendo: Aleluia! Pois reina o Senhor, nosso Deus, o Todo-Poderoso.

[[v66-19-7]]

^<<v66-19-7,7>>^ Alegremo-nos, exultemos e demos-lhe a glória, porque são chegadas as bodas do Cordeiro, cuja esposa a si mesma já se ataviou,

[[v66-19-8]]

^<<v66-19-8,8>>^ pois lhe foi dado vestir-se de linho finíssimo, resplandecente e puro. Porque o linho finíssimo são os atos de justiça dos santos.

[[v66-19-9]]

^<<v66-19-9,9>>^ Então, me falou o anjo: Escreve: Bem-aventurados aqueles que são chamados à ceia das bodas do Cordeiro. E acrescentou: São estas as verdadeiras palavras de Deus.

[[v66-19-10]]

^<<v66-19-10,10>>^ Prostrei-me ante os seus pés para adorá-lo. Ele, porém, me disse: Vê, não faças isso; sou conservo teu e dos teus irmãos que mantêm o testemunho de Jesus; adora a Deus. Pois o testemunho de Jesus é o espírito da profecia.

[[v66-19-11]]

^<<v66-19-11,11>>^ Vi o céu aberto, e eis um cavalo branco. O seu cavaleiro se chama Fiel e Verdadeiro e julga e peleja com justiça.

[[v66-19-12]]

^<<v66-19-12,12>>^ Os seus olhos são chama de fogo; na sua cabeça, há muitos diademas; tem um nome escrito que ninguém conhece, senão ele mesmo.

[[v66-19-13]]

^<<v66-19-13,13>>^ Está vestido com um manto tinto de sangue, e o seu nome se chama o Verbo de Deus;

[[v66-19-14]]

^<<v66-19-14,14>>^ e seguiam-no os exércitos que há no céu, montando cavalos brancos, com vestiduras de linho finíssimo, branco e puro.

[[v66-19-15]]

^<<v66-19-15,15>>^ Sai da sua boca uma espada afiada, para com ela ferir as nações; e ele mesmo as regerá com cetro de ferro e, pessoalmente, pisa o lagar do vinho do furor da ira do Deus Todo-Poderoso.

[[v66-19-16]]

^<<v66-19-16,16>>^ Tem no seu manto e na sua coxa um nome inscrito: Rei dos Reis e Senhor dos Senhores .

[[v66-19-17]]

^<<v66-19-17,17>>^ Então, vi um anjo posto em pé no sol, e clamou com grande voz, falando a todas as aves que voam pelo meio do céu: Vinde, reuni-vos para a grande ceia de Deus,

[[v66-19-18]]

^<<v66-19-18,18>>^ para que comais carnes de reis, carnes de comandantes, carnes de poderosos, carnes de cavalos e seus cavaleiros, carnes de todos, quer livres, quer escravos, tanto pequenos como grandes.

[[v66-19-19]]

^<<v66-19-19,19>>^ E vi a besta e os reis da terra, com os seus exércitos, congregados para pelejarem contra aquele que estava montado no cavalo e contra o seu exército.

[[v66-19-20]]

^<<v66-19-20,20>>^ Mas a besta foi aprisionada, e com ela o falso profeta que, com os sinais feitos diante dela, seduziu aqueles que receberam a marca da besta e eram os adoradores da sua imagem. Os dois foram lançados vivos dentro do lago de fogo que arde com enxofre.

[[v66-19-21]]

^<<v66-19-21,21>>^ Os restantes foram mortos com a espada que saía da boca daquele que estava montado no cavalo. E todas as aves se fartaram das suas carnes.

'''

xref:066-apocalipse/066-apocalipse-018.adoc#v66-18-0[&#60; Capítulo Anterior] | <<v66-19-0,Topo>> | xref:066-apocalipse/066-apocalipse-020.adoc#v66-20-0[Próximo Capítulo &#62;]