include::./index.adoc[]

[[v46-1-0]]
=== 1 Coríntios, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v46-1-1]]

^<<v46-1-1,1>>^ Paulo, chamado pela vontade de Deus para ser apóstolo de Jesus Cristo, e o irmão Sóstenes,

[[v46-1-2]]

^<<v46-1-2,2>>^ à igreja de Deus que está em Corinto, aos santificados em Cristo Jesus, chamados para ser santos, com todos os que em todo lugar invocam o nome de nosso Senhor Jesus Cristo, Senhor deles e nosso:

[[v46-1-3]]

^<<v46-1-3,3>>^ graça a vós outros e paz, da parte de Deus, nosso Pai, e do Senhor Jesus Cristo.

[[v46-1-4]]

^<<v46-1-4,4>>^ Sempre dou graças a [meu] Deus a vosso respeito, a propósito da sua graça, que vos foi dada em Cristo Jesus;

[[v46-1-5]]

^<<v46-1-5,5>>^ porque, em tudo, fostes enriquecidos nele, em toda a palavra e em todo o conhecimento;

[[v46-1-6]]

^<<v46-1-6,6>>^ assim como o testemunho de Cristo tem sido confirmado em vós,

[[v46-1-7]]

^<<v46-1-7,7>>^ de maneira que não vos falte nenhum dom, aguardando vós a revelação de nosso Senhor Jesus Cristo,

[[v46-1-8]]

^<<v46-1-8,8>>^ o qual também vos confirmará até ao fim, para serdes irrepreensíveis no Dia de nosso Senhor Jesus Cristo.

[[v46-1-9]]

^<<v46-1-9,9>>^ Fiel é Deus, pelo qual fostes chamados à comunhão de seu Filho Jesus Cristo, nosso Senhor.

[[v46-1-10]]

^<<v46-1-10,10>>^ Rogo-vos, irmãos, pelo nome de nosso Senhor Jesus Cristo, que faleis todos a mesma coisa e que não haja entre vós divisões; antes, sejais inteiramente unidos, na mesma disposição mental e no mesmo parecer.

[[v46-1-11]]

^<<v46-1-11,11>>^ Pois a vosso respeito, meus irmãos, fui informado, pelos da casa de Cloe, de que há contendas entre vós.

[[v46-1-12]]

^<<v46-1-12,12>>^ Refiro-me ao fato de cada um de vós dizer: Eu sou de Paulo, e eu, de Apolo, e eu, de Cefas, e eu, de Cristo.

[[v46-1-13]]

^<<v46-1-13,13>>^ Acaso, Cristo está dividido? Foi Paulo crucificado em favor de vós ou fostes, porventura, batizados em nome de Paulo?

[[v46-1-14]]

^<<v46-1-14,14>>^ Dou graças [a Deus] porque a nenhum de vós batizei, exceto Crispo e Gaio;

[[v46-1-15]]

^<<v46-1-15,15>>^ para que ninguém diga que fostes batizados em meu nome.

[[v46-1-16]]

^<<v46-1-16,16>>^ Batizei também a casa de Estéfanas; além destes, não me lembro se batizei algum outro.

[[v46-1-17]]

^<<v46-1-17,17>>^ Porque não me enviou Cristo para batizar, mas para pregar o evangelho; não com sabedoria de palavra, para que se não anule a cruz de Cristo.

[[v46-1-18]]

^<<v46-1-18,18>>^ Certamente, a palavra da cruz é loucura para os que se perdem, mas para nós, que somos salvos, poder de Deus.

[[v46-1-19]]

^<<v46-1-19,19>>^ Pois está escrito: Destruirei a sabedoria dos sábios e aniquilarei a inteligência dos instruídos.

[[v46-1-20]]

^<<v46-1-20,20>>^ Onde está o sábio? Onde, o escriba? Onde, o inquiridor deste século? Porventura, não tornou Deus louca a sabedoria do mundo?

[[v46-1-21]]

^<<v46-1-21,21>>^ Visto como, na sabedoria de Deus, o mundo não o conheceu por sua própria sabedoria, aprouve a Deus salvar os que creem pela loucura da pregação.

[[v46-1-22]]

^<<v46-1-22,22>>^ Porque tanto os judeus pedem sinais, como os gregos buscam sabedoria;

[[v46-1-23]]

^<<v46-1-23,23>>^ mas nós pregamos a Cristo crucificado, escândalo para os judeus, loucura para os gentios;

[[v46-1-24]]

^<<v46-1-24,24>>^ mas para os que foram chamados, tanto judeus como gregos, pregamos a Cristo, poder de Deus e sabedoria de Deus.

[[v46-1-25]]

^<<v46-1-25,25>>^ Porque a loucura de Deus é mais sábia do que os homens; e a fraqueza de Deus é mais forte do que os homens.

[[v46-1-26]]

^<<v46-1-26,26>>^ Irmãos, reparai, pois, na vossa vocação; visto que não foram chamados muitos sábios segundo a carne, nem muitos poderosos, nem muitos de nobre nascimento;

[[v46-1-27]]

^<<v46-1-27,27>>^ pelo contrário, Deus escolheu as coisas loucas do mundo para envergonhar os sábios e escolheu as coisas fracas do mundo para envergonhar as fortes;

[[v46-1-28]]

^<<v46-1-28,28>>^ e Deus escolheu as coisas humildes do mundo, e as desprezadas, e aquelas que não são, para reduzir a nada as que são;

[[v46-1-29]]

^<<v46-1-29,29>>^ a fim de que ninguém se vanglorie na presença de Deus.

[[v46-1-30]]

^<<v46-1-30,30>>^ Mas vós sois dele, em Cristo Jesus, o qual se nos tornou, da parte de Deus, sabedoria, e justiça, e santificação, e redenção,

[[v46-1-31]]

^<<v46-1-31,31>>^ para que, como está escrito: Aquele que se gloria, glorie-se no Senhor.

'''

xref:045-romanos/045-romanos-016.adoc#v45-16-0[&#60; Capítulo Anterior] | <<v46-1-0,Topo>> | xref:046-1-corintios/046-1-corintios-002.adoc#v46-2-0[Próximo Capítulo &#62;]