include::./index.adoc[]

[[v46-14-0]]
=== 1 Coríntios, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v46-14-1]]

^<<v46-14-1,1>>^ Segui o amor e procurai, com zelo, os dons espirituais, mas principalmente que profetizeis.

[[v46-14-2]]

^<<v46-14-2,2>>^ Pois quem fala em outra língua não fala a homens, senão a Deus, visto que ninguém o entende, e em espírito fala mistérios.

[[v46-14-3]]

^<<v46-14-3,3>>^ Mas o que profetiza fala aos homens, edificando, exortando e consolando.

[[v46-14-4]]

^<<v46-14-4,4>>^ O que fala em outra língua a si mesmo se edifica, mas o que profetiza edifica a igreja.

[[v46-14-5]]

^<<v46-14-5,5>>^ Eu quisera que vós todos falásseis em outras línguas; muito mais, porém, que profetizásseis; pois quem profetiza é superior ao que fala em outras línguas, salvo se as interpretar, para que a igreja receba edificação.

[[v46-14-6]]

^<<v46-14-6,6>>^ Agora, porém, irmãos, se eu for ter convosco falando em outras línguas, em que vos aproveitarei, se vos não falar por meio de revelação, ou de ciência, ou de profecia, ou de doutrina?

[[v46-14-7]]

^<<v46-14-7,7>>^ É assim que instrumentos inanimados, como a flauta ou a cítara, quando emitem sons, se não os derem bem distintos, como se reconhecerá o que se toca na flauta ou cítara?

[[v46-14-8]]

^<<v46-14-8,8>>^ Pois também se a trombeta der som incerto, quem se preparará para a batalha?

[[v46-14-9]]

^<<v46-14-9,9>>^ Assim, vós, se, com a língua, não disserdes palavra compreensível, como se entenderá o que dizeis? Porque estareis como se falásseis ao ar.

[[v46-14-10]]

^<<v46-14-10,10>>^ Há, sem dúvida, muitos tipos de vozes no mundo; nenhum deles, contudo, sem sentido.

[[v46-14-11]]

^<<v46-14-11,11>>^ Se eu, pois, ignorar a significação da voz, serei estrangeiro para aquele que fala; e ele, estrangeiro para mim.

[[v46-14-12]]

^<<v46-14-12,12>>^ Assim, também vós, visto que desejais dons espirituais, procurai progredir, para a edificação da igreja.

[[v46-14-13]]

^<<v46-14-13,13>>^ Pelo que, o que fala em outra língua deve orar para que a possa interpretar.

[[v46-14-14]]

^<<v46-14-14,14>>^ Porque, se eu orar em outra língua, o meu espírito ora de fato, mas a minha mente fica infrutífera.

[[v46-14-15]]

^<<v46-14-15,15>>^ Que farei, pois? Orarei com o espírito, mas também orarei com a mente; cantarei com o espírito, mas também cantarei com a mente.

[[v46-14-16]]

^<<v46-14-16,16>>^ E, se tu bendisseres apenas em espírito, como dirá o indouto o amém depois da tua ação de graças? Visto que não entende o que dizes;

[[v46-14-17]]

^<<v46-14-17,17>>^ porque tu, de fato, dás bem as graças, mas o outro não é edificado.

[[v46-14-18]]

^<<v46-14-18,18>>^ Dou graças a Deus, porque falo em outras línguas mais do que todos vós.

[[v46-14-19]]

^<<v46-14-19,19>>^ Contudo, prefiro falar na igreja cinco palavras com o meu entendimento, para instruir outros, a falar dez mil palavras em outra língua.

[[v46-14-20]]

^<<v46-14-20,20>>^ Irmãos, não sejais meninos no juízo; na malícia, sim, sede crianças; quanto ao juízo, sede homens amadurecidos.

[[v46-14-21]]

^<<v46-14-21,21>>^ Na lei está escrito: Falarei a este povo por homens de outras línguas e por lábios de outros povos, e nem assim me ouvirão, diz o Senhor.

[[v46-14-22]]

^<<v46-14-22,22>>^ De sorte que as línguas constituem um sinal não para os crentes, mas para os incrédulos; mas a profecia não é para os incrédulos, e sim para os que creem.

[[v46-14-23]]

^<<v46-14-23,23>>^ Se, pois, toda a igreja se reunir no mesmo lugar, e todos se puserem a falar em outras línguas, no caso de entrarem indoutos ou incrédulos, não dirão, porventura, que estais loucos?

[[v46-14-24]]

^<<v46-14-24,24>>^ Porém, se todos profetizarem, e entrar algum incrédulo ou indouto, é ele por todos convencido e por todos julgado;

[[v46-14-25]]

^<<v46-14-25,25>>^ tornam-se-lhe manifestos os segredos do coração, e, assim, prostrando-se com a face em terra, adorará a Deus, testemunhando que Deus está, de fato, no meio de vós.

[[v46-14-26]]

^<<v46-14-26,26>>^ Que fazer, pois, irmãos? Quando vos reunis, um tem salmo, outro, doutrina, este traz revelação, aquele, outra língua, e ainda outro, interpretação. Seja tudo feito para edificação.

[[v46-14-27]]

^<<v46-14-27,27>>^ No caso de alguém falar em outra língua, que não sejam mais do que dois ou quando muito três, e isto sucessivamente, e haja quem interprete.

[[v46-14-28]]

^<<v46-14-28,28>>^ Mas, não havendo intérprete, fique calado na igreja, falando consigo mesmo e com Deus.

[[v46-14-29]]

^<<v46-14-29,29>>^ Tratando-se de profetas, falem apenas dois ou três, e os outros julguem.

[[v46-14-30]]

^<<v46-14-30,30>>^ Se, porém, vier revelação a outrem que esteja assentado, cale-se o primeiro.

[[v46-14-31]]

^<<v46-14-31,31>>^ Porque todos podereis profetizar, um após outro, para todos aprenderem e serem consolados.

[[v46-14-32]]

^<<v46-14-32,32>>^ Os espíritos dos profetas estão sujeitos aos próprios profetas;

[[v46-14-33]]

^<<v46-14-33,33>>^ porque Deus não é de confusão, e sim de paz. Como em todas as igrejas dos santos,

[[v46-14-34]]

^<<v46-14-34,34>>^ conservem-se as mulheres caladas nas igrejas, porque não lhes é permitido falar; mas estejam submissas como também a lei o determina.

[[v46-14-35]]

^<<v46-14-35,35>>^ Se, porém, querem aprender alguma coisa, interroguem, em casa, a seu próprio marido; porque para a mulher é vergonhoso falar na igreja.

[[v46-14-36]]

^<<v46-14-36,36>>^ Porventura, a palavra de Deus se originou no meio de vós ou veio ela exclusivamente para vós outros?

[[v46-14-37]]

^<<v46-14-37,37>>^ Se alguém se considera profeta ou espiritual, reconheça ser mandamento do Senhor o que vos escrevo.

[[v46-14-38]]

^<<v46-14-38,38>>^ E, se alguém o ignorar, será ignorado.

[[v46-14-39]]

^<<v46-14-39,39>>^ Portanto, meus irmãos, procurai com zelo o dom de profetizar e não proibais o falar em outras línguas.

[[v46-14-40]]

^<<v46-14-40,40>>^ Tudo, porém, seja feito com decência e ordem.

'''

xref:046-1-corintios/046-1-corintios-013.adoc#v46-13-0[&#60; Capítulo Anterior] | <<v46-14-0,Topo>> | xref:046-1-corintios/046-1-corintios-015.adoc#v46-15-0[Próximo Capítulo &#62;]