include::./index.adoc[]

[[v46-8-0]]
=== 1 Coríntios, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v46-8-1]]

^<<v46-8-1,1>>^ No que se refere às coisas sacrificadas a ídolos, reconhecemos que todos somos senhores do saber. O saber ensoberbece, mas o amor edifica.

[[v46-8-2]]

^<<v46-8-2,2>>^ Se alguém julga saber alguma coisa, com efeito, não aprendeu ainda como convém saber.

[[v46-8-3]]

^<<v46-8-3,3>>^ Mas, se alguém ama a Deus, esse é conhecido por ele.

[[v46-8-4]]

^<<v46-8-4,4>>^ No tocante à comida sacrificada a ídolos, sabemos que o ídolo, de si mesmo, nada é no mundo e que não há senão um só Deus.

[[v46-8-5]]

^<<v46-8-5,5>>^ Porque, ainda que há também alguns que se chamem deuses, quer no céu ou sobre a terra, como há muitos deuses e muitos senhores,

[[v46-8-6]]

^<<v46-8-6,6>>^ todavia, para nós há um só Deus, o Pai, de quem são todas as coisas e para quem existimos; e um só Senhor, Jesus Cristo, pelo qual são todas as coisas, e nós também, por ele.

[[v46-8-7]]

^<<v46-8-7,7>>^ Entretanto, não há esse conhecimento em todos; porque alguns, por efeito da familiaridade até agora com o ídolo, ainda comem dessas coisas como a ele sacrificadas; e a consciência destes, por ser fraca, vem a contaminar-se.

[[v46-8-8]]

^<<v46-8-8,8>>^ Não é a comida que nos recomendará a Deus, pois nada perderemos, se não comermos, e nada ganharemos, se comermos.

[[v46-8-9]]

^<<v46-8-9,9>>^ Vede, porém, que esta vossa liberdade não venha, de algum modo, a ser tropeço para os fracos.

[[v46-8-10]]

^<<v46-8-10,10>>^ Porque, se alguém te vir a ti, que és dotado de saber, à mesa, em templo de ídolo, não será a consciência do que é fraco induzida a participar de comidas sacrificadas a ídolos?

[[v46-8-11]]

^<<v46-8-11,11>>^ E assim, por causa do teu saber, perece o irmão fraco, pelo qual Cristo morreu.

[[v46-8-12]]

^<<v46-8-12,12>>^ E deste modo, pecando contra os irmãos, golpeando-lhes a consciência fraca, é contra Cristo que pecais.

[[v46-8-13]]

^<<v46-8-13,13>>^ E, por isso, se a comida serve de escândalo a meu irmão, nunca mais comerei carne, para que não venha a escandalizá-lo.

'''

xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[&#60; Capítulo Anterior] | <<v46-8-0,Topo>> | xref:046-1-corintios/046-1-corintios-009.adoc#v46-9-0[Próximo Capítulo &#62;]