include::./index.adoc[]

[[v46-5-0]]
=== 1 Coríntios, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v46-5-1]]

^<<v46-5-1,1>>^ Geralmente, se ouve que há entre vós imoralidade e imoralidade tal, como nem mesmo entre os gentios, isto é, haver quem se atreva a possuir a mulher de seu próprio pai.

[[v46-5-2]]

^<<v46-5-2,2>>^ E, contudo, andais vós ensoberbecidos e não chegastes a lamentar, para que fosse tirado do vosso meio quem tamanho ultraje praticou?

[[v46-5-3]]

^<<v46-5-3,3>>^ Eu, na verdade, ainda que ausente em pessoa, mas presente em espírito, já sentenciei, como se estivesse presente, que o autor de tal infâmia seja,

[[v46-5-4]]

^<<v46-5-4,4>>^ em nome do Senhor Jesus, reunidos vós e o meu espírito, com o poder de Jesus, nosso Senhor,

[[v46-5-5]]

^<<v46-5-5,5>>^ entregue a Satanás para a destruição da carne, a fim de que o espírito seja salvo no Dia do SENHOR[Jesus].

[[v46-5-6]]

^<<v46-5-6,6>>^ Não é boa a vossa jactância. Não sabeis que um pouco de fermento leveda a massa toda?

[[v46-5-7]]

^<<v46-5-7,7>>^ Lançai fora o velho fermento, para que sejais nova massa, como sois, de fato, sem fermento. Pois também Cristo, nosso Cordeiro pascal, foi imolado.

[[v46-5-8]]

^<<v46-5-8,8>>^ Por isso, celebremos a festa não com o velho fermento, nem com o fermento da maldade e da malícia, e sim com os asmos da sinceridade e da verdade.

[[v46-5-9]]

^<<v46-5-9,9>>^ Já em carta vos escrevi que não vos associásseis com os impuros;

[[v46-5-10]]

^<<v46-5-10,10>>^ refiro-me, com isto, não propriamente aos impuros deste mundo, ou aos avarentos, ou roubadores, ou idólatras; pois, neste caso, teríeis de sair do mundo.

[[v46-5-11]]

^<<v46-5-11,11>>^ Mas, agora, vos escrevo que não vos associeis com alguém que, dizendo-se irmão, for impuro, ou avarento, ou idólatra, ou maldizente, ou beberrão, ou roubador; com esse tal, nem ainda comais.

[[v46-5-12]]

^<<v46-5-12,12>>^ Pois com que direito haveria eu de julgar os de fora? Não julgais vós os de dentro?

[[v46-5-13]]

^<<v46-5-13,13>>^ Os de fora, porém, Deus os julgará. Expulsai, pois, de entre vós o malfeitor.

'''

xref:046-1-corintios/046-1-corintios-004.adoc#v46-4-0[&#60; Capítulo Anterior] | <<v46-5-0,Topo>> | xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[Próximo Capítulo &#62;]