include::./index.adoc[]

[[v46-2-0]]
=== 1 Coríntios, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v46-2-1]]

^<<v46-2-1,1>>^ Eu, irmãos, quando fui ter convosco, anunciando-vos o testemunho de Deus, não o fiz com ostentação de linguagem ou de sabedoria.

[[v46-2-2]]

^<<v46-2-2,2>>^ Porque decidi nada saber entre vós, senão a Jesus Cristo e este crucificado.

[[v46-2-3]]

^<<v46-2-3,3>>^ E foi em fraqueza, temor e grande tremor que eu estive entre vós.

[[v46-2-4]]

^<<v46-2-4,4>>^ A minha palavra e a minha pregação não consistiram em linguagem persuasiva de sabedoria, mas em demonstração do Espírito e de poder,

[[v46-2-5]]

^<<v46-2-5,5>>^ para que a vossa fé não se apoiasse em sabedoria humana, e sim no poder de Deus.

[[v46-2-6]]

^<<v46-2-6,6>>^ Entretanto, expomos sabedoria entre os experimentados; não, porém, a sabedoria deste século, nem a dos poderosos desta época, que se reduzem a nada;

[[v46-2-7]]

^<<v46-2-7,7>>^ mas falamos a sabedoria de Deus em mistério, outrora oculta, a qual Deus preordenou desde a eternidade para a nossa glória;

[[v46-2-8]]

^<<v46-2-8,8>>^ sabedoria essa que nenhum dos poderosos deste século conheceu; porque, se a tivessem conhecido, jamais teriam crucificado o Senhor da glória;

[[v46-2-9]]

^<<v46-2-9,9>>^ mas, como está escrito: Nem olhos viram, nem ouvidos ouviram, nem jamais penetrou em coração humano o que Deus tem preparado para aqueles que o amam.

[[v46-2-10]]

^<<v46-2-10,10>>^ Mas Deus no-lo revelou pelo Espírito; porque o Espírito a todas as coisas perscruta, até mesmo as profundezas de Deus.

[[v46-2-11]]

^<<v46-2-11,11>>^ Porque qual dos homens sabe as coisas do homem, senão o seu próprio espírito, que nele está? Assim, também as coisas de Deus, ninguém as conhece, senão o Espírito de Deus.

[[v46-2-12]]

^<<v46-2-12,12>>^ Ora, nós não temos recebido o espírito do mundo, e sim o Espírito que vem de Deus, para que conheçamos o que por Deus nos foi dado gratuitamente.

[[v46-2-13]]

^<<v46-2-13,13>>^ Disto também falamos, não em palavras ensinadas pela sabedoria humana, mas ensinadas pelo Espírito, conferindo coisas espirituais com espirituais.

[[v46-2-14]]

^<<v46-2-14,14>>^ Ora, o homem natural não aceita as coisas do Espírito de Deus, porque lhe são loucura; e não pode entendê-las, porque elas se discernem espiritualmente.

[[v46-2-15]]

^<<v46-2-15,15>>^ Porém o homem espiritual julga todas as coisas, mas ele mesmo não é julgado por ninguém.

[[v46-2-16]]

^<<v46-2-16,16>>^ Pois quem conheceu a mente do Senhor, que o possa instruir? Nós, porém, temos a mente de Cristo.

'''

xref:046-1-corintios/046-1-corintios-001.adoc#v46-1-0[&#60; Capítulo Anterior] | <<v46-2-0,Topo>> | xref:046-1-corintios/046-1-corintios-003.adoc#v46-3-0[Próximo Capítulo &#62;]