include::./index.adoc[]

[[v46-3-0]]
=== 1 Coríntios, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v46-3-1]]

^<<v46-3-1,1>>^ Eu, porém, irmãos, não vos pude falar como a espirituais, e sim como a carnais, como a crianças em Cristo.

[[v46-3-2]]

^<<v46-3-2,2>>^ Leite vos dei a beber, não vos dei alimento sólido; porque ainda não podíeis suportá-lo. Nem ainda agora podeis, porque ainda sois carnais.

[[v46-3-3]]

^<<v46-3-3,3>>^ Porquanto, havendo entre vós ciúmes e contendas, não é assim que sois carnais e andais segundo o homem?

[[v46-3-4]]

^<<v46-3-4,4>>^ Quando, pois, alguém diz: Eu sou de Paulo, e outro: Eu, de Apolo, não é evidente que andais segundo os homens?

[[v46-3-5]]

^<<v46-3-5,5>>^ Quem é Apolo? E quem é Paulo? Servos por meio de quem crestes, e isto conforme o Senhor concedeu a cada um.

[[v46-3-6]]

^<<v46-3-6,6>>^ Eu plantei, Apolo regou; mas o crescimento veio de Deus.

[[v46-3-7]]

^<<v46-3-7,7>>^ De modo que nem o que planta é alguma coisa, nem o que rega, mas Deus, que dá o crescimento.

[[v46-3-8]]

^<<v46-3-8,8>>^ Ora, o que planta e o que rega são um; e cada um receberá o seu galardão, segundo o seu próprio trabalho.

[[v46-3-9]]

^<<v46-3-9,9>>^ Porque de Deus somos cooperadores; lavoura de Deus, edifício de Deus sois vós.

[[v46-3-10]]

^<<v46-3-10,10>>^ Segundo a graça de Deus que me foi dada, lancei o fundamento como prudente construtor; e outro edifica sobre ele. Porém cada um veja como edifica.

[[v46-3-11]]

^<<v46-3-11,11>>^ Porque ninguém pode lançar outro fundamento, além do que foi posto, o qual é Jesus Cristo.

[[v46-3-12]]

^<<v46-3-12,12>>^ Contudo, se o que alguém edifica sobre o fundamento é ouro, prata, pedras preciosas, madeira, feno, palha,

[[v46-3-13]]

^<<v46-3-13,13>>^ manifesta se tornará a obra de cada um; pois o Dia a demonstrará, porque está sendo revelada pelo fogo; e qual seja a obra de cada um o próprio fogo o provará.

[[v46-3-14]]

^<<v46-3-14,14>>^ Se permanecer a obra de alguém que sobre o fundamento edificou, esse receberá galardão;

[[v46-3-15]]

^<<v46-3-15,15>>^ se a obra de alguém se queimar, sofrerá ele dano; mas esse mesmo será salvo, todavia, como que através do fogo.

[[v46-3-16]]

^<<v46-3-16,16>>^ Não sabeis que sois santuário de Deus e que o Espírito de Deus habita em vós?

[[v46-3-17]]

^<<v46-3-17,17>>^ Se alguém destruir o santuário de Deus, Deus o destruirá; porque o santuário de Deus, que sois vós, é sagrado.

[[v46-3-18]]

^<<v46-3-18,18>>^ Ninguém se engane a si mesmo: se alguém dentre vós se tem por sábio neste século, faça-se estulto para se tornar sábio.

[[v46-3-19]]

^<<v46-3-19,19>>^ Porque a sabedoria deste mundo é loucura diante de Deus; porquanto está escrito: Ele apanha os sábios na própria astúcia deles.

[[v46-3-20]]

^<<v46-3-20,20>>^ E outra vez: O Senhor conhece os pensamentos dos sábios, que são pensamentos vãos.

[[v46-3-21]]

^<<v46-3-21,21>>^ Portanto, ninguém se glorie nos homens; porque tudo é vosso:

[[v46-3-22]]

^<<v46-3-22,22>>^ seja Paulo, seja Apolo, seja Cefas, seja o mundo, seja a vida, seja a morte, sejam as coisas presentes, sejam as futuras, tudo é vosso,

[[v46-3-23]]

^<<v46-3-23,23>>^ e vós, de Cristo, e Cristo, de Deus.

'''

xref:046-1-corintios/046-1-corintios-002.adoc#v46-2-0[&#60; Capítulo Anterior] | <<v46-3-0,Topo>> | xref:046-1-corintios/046-1-corintios-004.adoc#v46-4-0[Próximo Capítulo &#62;]