include::./index.adoc[]

[[v46-7-0]]
=== 1 Coríntios, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v46-7-1]]

^<<v46-7-1,1>>^ Quanto ao que me escrevestes, é bom que o homem não toque em mulher;

[[v46-7-2]]

^<<v46-7-2,2>>^ mas, por causa da impureza, cada um tenha a sua própria esposa, e cada uma, o seu próprio marido.

[[v46-7-3]]

^<<v46-7-3,3>>^ O marido conceda à esposa o que lhe é devido, e também, semelhantemente, a esposa, ao seu marido.

[[v46-7-4]]

^<<v46-7-4,4>>^ A mulher não tem poder sobre o seu próprio corpo, e sim o marido; e também, semelhantemente, o marido não tem poder sobre o seu próprio corpo, e sim a mulher.

[[v46-7-5]]

^<<v46-7-5,5>>^ Não vos priveis um ao outro, salvo talvez por mútuo consentimento, por algum tempo, para vos dedicardes à oração e, novamente, vos ajuntardes, para que Satanás não vos tente por causa da incontinência.

[[v46-7-6]]

^<<v46-7-6,6>>^ E isto vos digo como concessão e não por mandamento.

[[v46-7-7]]

^<<v46-7-7,7>>^ Quero que todos os homens sejam tais como também eu sou; no entanto, cada um tem de Deus o seu próprio dom; um, na verdade, de um modo; outro, de outro.

[[v46-7-8]]

^<<v46-7-8,8>>^ E aos solteiros e viúvos digo que lhes seria bom se permanecessem no estado em que também eu vivo.

[[v46-7-9]]

^<<v46-7-9,9>>^ Caso, porém, não se dominem, que se casem; porque é melhor casar do que viver abrasado.

[[v46-7-10]]

^<<v46-7-10,10>>^ Ora, aos casados, ordeno, não eu, mas o Senhor, que a mulher não se separe do marido

[[v46-7-11]]

^<<v46-7-11,11>>^ (se, porém, ela vier a separar-se, que não se case ou que se reconcilie com seu marido); e que o marido não se aparte de sua mulher.

[[v46-7-12]]

^<<v46-7-12,12>>^ Aos mais digo eu, não o Senhor: se algum irmão tem mulher incrédula, e esta consente em morar com ele, não a abandone;

[[v46-7-13]]

^<<v46-7-13,13>>^ e a mulher que tem marido incrédulo, e este consente em viver com ela, não deixe o marido.

[[v46-7-14]]

^<<v46-7-14,14>>^ Porque o marido incrédulo é santificado no convívio da esposa, e a esposa incrédula é santificada no convívio do marido crente. Doutra sorte, os vossos filhos seriam impuros; porém, agora, são santos.

[[v46-7-15]]

^<<v46-7-15,15>>^ Mas, se o descrente quiser apartar-se, que se aparte; em tais casos, não fica sujeito à servidão nem o irmão, nem a irmã; Deus vos tem chamado à paz.

[[v46-7-16]]

^<<v46-7-16,16>>^ Pois, como sabes, ó mulher, se salvarás teu marido? Ou, como sabes, ó marido, se salvarás tua mulher?

[[v46-7-17]]

^<<v46-7-17,17>>^ Ande cada um segundo o Senhor lhe tem distribuído, cada um conforme Deus o tem chamado. É assim que ordeno em todas as igrejas.

[[v46-7-18]]

^<<v46-7-18,18>>^ Foi alguém chamado, estando circunciso? Não desfaça a circuncisão. Foi alguém chamado, estando incircunciso? Não se faça circuncidar.

[[v46-7-19]]

^<<v46-7-19,19>>^ A circuncisão, em si, não é nada; a incircuncisão também nada é, mas o que vale é guardar as ordenanças de Deus.

[[v46-7-20]]

^<<v46-7-20,20>>^ Cada um permaneça na vocação em que foi chamado.

[[v46-7-21]]

^<<v46-7-21,21>>^ Foste chamado, sendo escravo? Não te preocupes com isso; mas, se ainda podes tornar-te livre, aproveita a oportunidade.

[[v46-7-22]]

^<<v46-7-22,22>>^ Porque o que foi chamado no Senhor, sendo escravo, é liberto do Senhor; semelhantemente, o que foi chamado, sendo livre, é escravo de Cristo.

[[v46-7-23]]

^<<v46-7-23,23>>^ Por preço fostes comprados; não vos torneis escravos de homens.

[[v46-7-24]]

^<<v46-7-24,24>>^ Irmãos, cada um permaneça diante de Deus naquilo em que foi chamado.

[[v46-7-25]]

^<<v46-7-25,25>>^ Com respeito às virgens, não tenho mandamento do Senhor; porém dou minha opinião, como tendo recebido do Senhor a misericórdia de ser fiel.

[[v46-7-26]]

^<<v46-7-26,26>>^ Considero, por causa da angustiosa situação presente, ser bom para o homem permanecer assim como está.

[[v46-7-27]]

^<<v46-7-27,27>>^ Estás casado? Não procures separar-te. Estás livre de mulher? Não procures casamento.

[[v46-7-28]]

^<<v46-7-28,28>>^ Mas, se te casares, com isto não pecas; e também, se a virgem se casar, por isso não peca. Ainda assim, tais pessoas sofrerão angústia na carne, e eu quisera poupar-vos.

[[v46-7-29]]

^<<v46-7-29,29>>^ Isto, porém, vos digo, irmãos: o tempo se abrevia; o que resta é que não só os casados sejam como se o não fossem;

[[v46-7-30]]

^<<v46-7-30,30>>^ mas também os que choram, como se não chorassem; e os que se alegram, como se não se alegrassem; e os que compram, como se nada possuíssem;

[[v46-7-31]]

^<<v46-7-31,31>>^ e os que se utilizam do mundo, como se dele não usassem; porque a aparência deste mundo passa.

[[v46-7-32]]

^<<v46-7-32,32>>^ O que realmente eu quero é que estejais livres de preocupações. Quem não é casado cuida das coisas do Senhor, de como agradar ao Senhor;

[[v46-7-33]]

^<<v46-7-33,33>>^ mas o que se casou cuida das coisas do mundo, de como agradar à esposa,

[[v46-7-34]]

^<<v46-7-34,34>>^ e assim está dividido. Também a mulher, tanto a viúva como a virgem, cuida das coisas do Senhor, para ser santa, assim no corpo como no espírito; a que se casou, porém, se preocupa com as coisas do mundo, de como agradar ao marido.

[[v46-7-35]]

^<<v46-7-35,35>>^ Digo isto em favor dos vossos próprios interesses; não que eu pretenda enredar-vos, mas somente para o que é decoroso e vos facilite o consagrar-vos, desimpedidamente, ao Senhor.

[[v46-7-36]]

^<<v46-7-36,36>>^ Entretanto, se alguém julga que trata sem decoro a sua filha, estando já a passar-lhe a flor da idade, e as circunstâncias o exigem, faça o que quiser. Não peca; que se casem.

[[v46-7-37]]

^<<v46-7-37,37>>^ Todavia, o que está firme em seu coração, não tendo necessidade, mas domínio sobre o seu próprio arbítrio, e isto bem-firmado no seu ânimo, para conservar virgem a sua filha, bem fará.

[[v46-7-38]]

^<<v46-7-38,38>>^ E, assim, quem casa a sua filha virgem faz bem; quem não a casa faz melhor.

[[v46-7-39]]

^<<v46-7-39,39>>^ A mulher está ligada enquanto vive o marido; contudo, se falecer o marido, fica livre para casar com quem quiser, mas somente no Senhor.

[[v46-7-40]]

^<<v46-7-40,40>>^ Todavia, será mais feliz se permanecer viúva, segundo a minha opinião; e penso que também eu tenho o Espírito de Deus.

'''

xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[&#60; Capítulo Anterior] | <<v46-7-0,Topo>> | xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[Próximo Capítulo &#62;]