include::./index.adoc[]

[[v46-11-0]]
=== 1 Coríntios, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v46-11-1]]

^<<v46-11-1,1>>^ Sede meus imitadores, como também eu sou de Cristo.

[[v46-11-2]]

^<<v46-11-2,2>>^ De fato, eu vos louvo porque, em tudo, vos lembrais de mim e retendes as tradições assim como vo-las entreguei.

[[v46-11-3]]

^<<v46-11-3,3>>^ Quero, entretanto, que saibais ser Cristo o cabeça de todo homem, e o homem, o cabeça da mulher, e Deus, o cabeça de Cristo.

[[v46-11-4]]

^<<v46-11-4,4>>^ Todo homem que ora ou profetiza, tendo a cabeça coberta, desonra a sua própria cabeça.

[[v46-11-5]]

^<<v46-11-5,5>>^ Toda mulher, porém, que ora ou profetiza com a cabeça sem véu desonra a sua própria cabeça, porque é como se a tivesse rapada.

[[v46-11-6]]

^<<v46-11-6,6>>^ Portanto, se a mulher não usa véu, nesse caso, que rape o cabelo. Mas, se lhe é vergonhoso o tosquiar-se ou rapar-se, cumpre-lhe usar véu.

[[v46-11-7]]

^<<v46-11-7,7>>^ Porque, na verdade, o homem não deve cobrir a cabeça, por ser ele imagem e glória de Deus, mas a mulher é glória do homem.

[[v46-11-8]]

^<<v46-11-8,8>>^ Porque o homem não foi feito da mulher, e sim a mulher, do homem.

[[v46-11-9]]

^<<v46-11-9,9>>^ Porque também o homem não foi criado por causa da mulher, e sim a mulher, por causa do homem.

[[v46-11-10]]

^<<v46-11-10,10>>^ Portanto, deve a mulher, por causa dos anjos, trazer véu na cabeça, como sinal de autoridade.

[[v46-11-11]]

^<<v46-11-11,11>>^ No Senhor, todavia, nem a mulher é independente do homem, nem o homem, independente da mulher.

[[v46-11-12]]

^<<v46-11-12,12>>^ Porque, como provém a mulher do homem, assim também o homem é nascido da mulher; e tudo vem de Deus.

[[v46-11-13]]

^<<v46-11-13,13>>^ Julgai entre vós mesmos: é próprio que a mulher ore a Deus sem trazer o véu?

[[v46-11-14]]

^<<v46-11-14,14>>^ Ou não vos ensina a própria natureza ser desonroso para o homem usar cabelo comprido?

[[v46-11-15]]

^<<v46-11-15,15>>^ E que, tratando-se da mulher, é para ela uma glória? Pois o cabelo lhe foi dado em lugar de mantilha.

[[v46-11-16]]

^<<v46-11-16,16>>^ Contudo, se alguém quer ser contencioso, saiba que nós não temos tal costume, nem as igrejas de Deus.

[[v46-11-17]]

^<<v46-11-17,17>>^ Nisto, porém, que vos prescrevo, não vos louvo, porquanto vos ajuntais não para melhor, e sim para pior.

[[v46-11-18]]

^<<v46-11-18,18>>^ Porque, antes de tudo, estou informado haver divisões entre vós quando vos reunis na igreja; e eu, em parte, o creio.

[[v46-11-19]]

^<<v46-11-19,19>>^ Porque até mesmo importa que haja partidos entre vós, para que também os aprovados se tornem conhecidos em vosso meio.

[[v46-11-20]]

^<<v46-11-20,20>>^ Quando, pois, vos reunis no mesmo lugar, não é a ceia do Senhor que comeis.

[[v46-11-21]]

^<<v46-11-21,21>>^ Porque, ao comerdes, cada um toma, antecipadamente, a sua própria ceia; e há quem tenha fome, ao passo que há também quem se embriague.

[[v46-11-22]]

^<<v46-11-22,22>>^ Não tendes, porventura, casas onde comer e beber? Ou menosprezais a igreja de Deus e envergonhais os que nada têm? Que vos direi? Louvar-vos-ei? Nisto, certamente, não vos louvo.

[[v46-11-23]]

^<<v46-11-23,23>>^ Porque eu recebi do Senhor o que também vos entreguei: que o Senhor Jesus, na noite em que foi traído, tomou o pão;

[[v46-11-24]]

^<<v46-11-24,24>>^ e, tendo dado graças, o partiu e disse: Isto é o meu corpo, que é dado por vós; fazei isto em memória de mim.

[[v46-11-25]]

^<<v46-11-25,25>>^ Por semelhante modo, depois de haver ceado, tomou também o cálice, dizendo: Este cálice é a nova aliança no meu sangue; fazei isto, todas as vezes que o beberdes, em memória de mim.

[[v46-11-26]]

^<<v46-11-26,26>>^ Porque, todas as vezes que comerdes este pão e beberdes o cálice, anunciais a morte do Senhor, até que ele venha.

[[v46-11-27]]

^<<v46-11-27,27>>^ Por isso, aquele que comer o pão ou beber o cálice do Senhor, indignamente, será réu do corpo e do sangue do Senhor.

[[v46-11-28]]

^<<v46-11-28,28>>^ Examine-se, pois, o homem a si mesmo, e, assim, coma do pão, e beba do cálice;

[[v46-11-29]]

^<<v46-11-29,29>>^ pois quem come e bebe sem discernir o corpo, come e bebe juízo para si.

[[v46-11-30]]

^<<v46-11-30,30>>^ Eis a razão por que há entre vós muitos fracos e doentes e não poucos que dormem.

[[v46-11-31]]

^<<v46-11-31,31>>^ Porque, se nos julgássemos a nós mesmos, não seríamos julgados.

[[v46-11-32]]

^<<v46-11-32,32>>^ Mas, quando julgados, somos disciplinados pelo Senhor, para não sermos condenados com o mundo.

[[v46-11-33]]

^<<v46-11-33,33>>^ Assim, pois, irmãos meus, quando vos reunis para comer, esperai uns pelos outros.

[[v46-11-34]]

^<<v46-11-34,34>>^ Se alguém tem fome, coma em casa, a fim de não vos reunirdes para juízo. Quanto às demais coisas, eu as ordenarei quando for ter convosco.

'''

xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[&#60; Capítulo Anterior] | <<v46-11-0,Topo>> | xref:046-1-corintios/046-1-corintios-012.adoc#v46-12-0[Próximo Capítulo &#62;]