include::./index.adoc[]

[[v46-9-0]]
=== 1 Coríntios, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v46-9-1]]

^<<v46-9-1,1>>^ Não sou eu, porventura, livre? Não sou apóstolo? Não vi Jesus, nosso Senhor? Acaso, não sois fruto do meu trabalho no Senhor?

[[v46-9-2]]

^<<v46-9-2,2>>^ Se não sou apóstolo para outrem, certamente, o sou para vós outros; porque vós sois o selo do meu apostolado no Senhor.

[[v46-9-3]]

^<<v46-9-3,3>>^ A minha defesa perante os que me interpelam é esta:

[[v46-9-4]]

^<<v46-9-4,4>>^ não temos nós o direito de comer e beber?

[[v46-9-5]]

^<<v46-9-5,5>>^ E também o de fazer-nos acompanhar de uma mulher irmã, como fazem os demais apóstolos, e os irmãos do Senhor, e Cefas?

[[v46-9-6]]

^<<v46-9-6,6>>^ Ou somente eu e Barnabé não temos direito de deixar de trabalhar?

[[v46-9-7]]

^<<v46-9-7,7>>^ Quem jamais vai à guerra à sua própria custa? Quem planta a vinha e não come do seu fruto? Ou quem apascenta um rebanho e não se alimenta do leite do rebanho?

[[v46-9-8]]

^<<v46-9-8,8>>^ Porventura, falo isto como homem ou não o diz também a lei?

[[v46-9-9]]

^<<v46-9-9,9>>^ Porque na lei de Moisés está escrito: Não atarás a boca ao boi, quando pisa o trigo. Acaso, é com bois que Deus se preocupa?

[[v46-9-10]]

^<<v46-9-10,10>>^ Ou é, seguramente, por nós que ele o diz? Certo que é por nós que está escrito; pois o que lavra cumpre fazê-lo com esperança; o que pisa o trigo faça-o na esperança de receber a parte que lhe é devida.

[[v46-9-11]]

^<<v46-9-11,11>>^ Se nós vos semeamos as coisas espirituais, será muito recolhermos de vós bens materiais?

[[v46-9-12]]

^<<v46-9-12,12>>^ Se outros participam desse direito sobre vós, não o temos nós em maior medida? Entretanto, não usamos desse direito; antes, suportamos tudo, para não criarmos qualquer obstáculo ao evangelho de Cristo.

[[v46-9-13]]

^<<v46-9-13,13>>^ Não sabeis vós que os que prestam serviços sagrados do próprio templo se alimentam? E quem serve ao altar do altar tira o seu sustento?

[[v46-9-14]]

^<<v46-9-14,14>>^ Assim ordenou também o Senhor aos que pregam o evangelho que vivam do evangelho;

[[v46-9-15]]

^<<v46-9-15,15>>^ eu, porém, não me tenho servido de nenhuma destas coisas e não escrevo isto para que assim se faça comigo; porque melhor me fora morrer, antes que alguém me anule esta glória.

[[v46-9-16]]

^<<v46-9-16,16>>^ Se anuncio o evangelho, não tenho de que me gloriar, pois sobre mim pesa essa obrigação; porque ai de mim se não pregar o evangelho!

[[v46-9-17]]

^<<v46-9-17,17>>^ Se o faço de livre vontade, tenho galardão; mas, se constrangido, é, então, a responsabilidade de despenseiro que me está confiada.

[[v46-9-18]]

^<<v46-9-18,18>>^ Nesse caso, qual é o meu galardão? É que, evangelizando, proponha, de graça, o evangelho, para não me valer do direito que ele me dá.

[[v46-9-19]]

^<<v46-9-19,19>>^ Porque, sendo livre de todos, fiz-me escravo de todos, a fim de ganhar o maior número possível.

[[v46-9-20]]

^<<v46-9-20,20>>^ Procedi, para com os judeus, como judeu, a fim de ganhar os judeus; para os que vivem sob o regime da lei, como se eu mesmo assim vivesse, para ganhar os que vivem debaixo da lei, embora não esteja eu debaixo da lei.

[[v46-9-21]]

^<<v46-9-21,21>>^ Aos sem lei, como se eu mesmo o fosse, não estando sem lei para com Deus, mas debaixo da lei de Cristo, para ganhar os que vivem fora do regime da lei.

[[v46-9-22]]

^<<v46-9-22,22>>^ Fiz-me fraco para com os fracos, com o fim de ganhar os fracos. Fiz-me tudo para com todos, com o fim de, por todos os modos, salvar alguns.

[[v46-9-23]]

^<<v46-9-23,23>>^ Tudo faço por causa do evangelho, com o fim de me tornar cooperador com ele.

[[v46-9-24]]

^<<v46-9-24,24>>^ Não sabeis vós que os que correm no estádio, todos, na verdade, correm, mas um só leva o prêmio? Correi de tal maneira que o alcanceis.

[[v46-9-25]]

^<<v46-9-25,25>>^ Todo atleta em tudo se domina; aqueles, para alcançar uma coroa corruptível; nós, porém, a incorruptível.

[[v46-9-26]]

^<<v46-9-26,26>>^ Assim corro também eu, não sem meta; assim luto, não como desferindo golpes no ar.

[[v46-9-27]]

^<<v46-9-27,27>>^ Mas esmurro o meu corpo e o reduzo à escravidão, para que, tendo pregado a outros, não venha eu mesmo a ser desqualificado.

'''

xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[&#60; Capítulo Anterior] | <<v46-9-0,Topo>> | xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[Próximo Capítulo &#62;]