include::./index.adoc[]

[[v46-10-0]]
=== 1 Coríntios, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v46-10-1]]

^<<v46-10-1,1>>^ Ora, irmãos, não quero que ignoreis que nossos pais estiveram todos sob a nuvem, e todos passaram pelo mar,

[[v46-10-2]]

^<<v46-10-2,2>>^ tendo sido todos batizados, assim na nuvem como no mar, com respeito a Moisés.

[[v46-10-3]]

^<<v46-10-3,3>>^ Todos eles comeram de um só manjar espiritual

[[v46-10-4]]

^<<v46-10-4,4>>^ e beberam da mesma fonte espiritual; porque bebiam de uma pedra espiritual que os seguia. E a pedra era Cristo.

[[v46-10-5]]

^<<v46-10-5,5>>^ Entretanto, Deus não se agradou da maioria deles, razão por que ficaram prostrados no deserto.

[[v46-10-6]]

^<<v46-10-6,6>>^ Ora, estas coisas se tornaram exemplos para nós, a fim de que não cobicemos as coisas más, como eles cobiçaram.

[[v46-10-7]]

^<<v46-10-7,7>>^ Não vos façais, pois, idólatras, como alguns deles; porquanto está escrito: O povo assentou-se para comer e beber e levantou-se para divertir-se.

[[v46-10-8]]

^<<v46-10-8,8>>^ E não pratiquemos imoralidade, como alguns deles o fizeram, e caíram, num só dia, vinte e três mil.

[[v46-10-9]]

^<<v46-10-9,9>>^ Não ponhamos o Senhor à prova, como alguns deles já fizeram e pereceram pelas mordeduras das serpentes.

[[v46-10-10]]

^<<v46-10-10,10>>^ Nem murmureis, como alguns deles murmuraram e foram destruídos pelo exterminador.

[[v46-10-11]]

^<<v46-10-11,11>>^ Estas coisas lhes sobrevieram como exemplos e foram escritas para advertência nossa, de nós outros sobre quem os fins dos séculos têm chegado.

[[v46-10-12]]

^<<v46-10-12,12>>^ Aquele, pois, que pensa estar em pé veja que não caia.

[[v46-10-13]]

^<<v46-10-13,13>>^ Não vos sobreveio tentação que não fosse humana; mas Deus é fiel e não permitirá que sejais tentados além das vossas forças; pelo contrário, juntamente com a tentação, vos proverá livramento, de sorte que a possais suportar.

[[v46-10-14]]

^<<v46-10-14,14>>^ Portanto, meus amados, fugi da idolatria.

[[v46-10-15]]

^<<v46-10-15,15>>^ Falo como a criteriosos; julgai vós mesmos o que digo.

[[v46-10-16]]

^<<v46-10-16,16>>^ Porventura, o cálice da bênção que abençoamos não é a comunhão do sangue de Cristo? O pão que partimos não é a comunhão do corpo de Cristo?

[[v46-10-17]]

^<<v46-10-17,17>>^ Porque nós, embora muitos, somos unicamente um pão, um só corpo; porque todos participamos do único pão.

[[v46-10-18]]

^<<v46-10-18,18>>^ Considerai o Israel segundo a carne; não é certo que aqueles que se alimentam dos sacrifícios são participantes do altar?

[[v46-10-19]]

^<<v46-10-19,19>>^ Que digo, pois? Que o sacrificado ao ídolo é alguma coisa? Ou que o próprio ídolo tem algum valor?

[[v46-10-20]]

^<<v46-10-20,20>>^ Antes, digo que as coisas que eles sacrificam, é a demônios que as sacrificam e não a Deus; e eu não quero que vos torneis associados aos demônios.

[[v46-10-21]]

^<<v46-10-21,21>>^ Não podeis beber o cálice do Senhor e o cálice dos demônios; não podeis ser participantes da mesa do Senhor e da mesa dos demônios.

[[v46-10-22]]

^<<v46-10-22,22>>^ Ou provocaremos zelos no Senhor? Somos, acaso, mais fortes do que ele?

[[v46-10-23]]

^<<v46-10-23,23>>^ Todas as coisas são lícitas, mas nem todas convêm; todas são lícitas, mas nem todas edificam.

[[v46-10-24]]

^<<v46-10-24,24>>^ Ninguém busque o seu próprio interesse, e sim o de outrem.

[[v46-10-25]]

^<<v46-10-25,25>>^ Comei de tudo o que se vende no mercado, sem nada perguntardes por motivo de consciência;

[[v46-10-26]]

^<<v46-10-26,26>>^ porque do Senhor é a terra e a sua plenitude.

[[v46-10-27]]

^<<v46-10-27,27>>^ Se algum dentre os incrédulos vos convidar, e quiserdes ir, comei de tudo o que for posto diante de vós, sem nada perguntardes por motivo de consciência.

[[v46-10-28]]

^<<v46-10-28,28>>^ Porém, se alguém vos disser: Isto é coisa sacrificada a ídolo, não comais, por causa daquele que vos advertiu e por causa da consciência;

[[v46-10-29]]

^<<v46-10-29,29>>^ consciência, digo, não a tua propriamente, mas a do outro. Pois por que há de ser julgada a minha liberdade pela consciência alheia?

[[v46-10-30]]

^<<v46-10-30,30>>^ Se eu participo com ações de graças, por que hei de ser vituperado por causa daquilo por que dou graças?

[[v46-10-31]]

^<<v46-10-31,31>>^ Portanto, quer comais, quer bebais ou façais outra coisa qualquer, fazei tudo para a glória de Deus.

[[v46-10-32]]

^<<v46-10-32,32>>^ Não vos torneis causa de tropeço nem para judeus, nem para gentios, nem tampouco para a igreja de Deus,

[[v46-10-33]]

^<<v46-10-33,33>>^ assim como também eu procuro, em tudo, ser agradável a todos, não buscando o meu próprio interesse, mas o de muitos, para que sejam salvos.

'''

xref:046-1-corintios/046-1-corintios-009.adoc#v46-9-0[&#60; Capítulo Anterior] | <<v46-10-0,Topo>> | xref:046-1-corintios/046-1-corintios-011.adoc#v46-11-0[Próximo Capítulo &#62;]