include::./index.adoc[]

[[v46-6-0]]
=== 1 Coríntios, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v46-6-1]]

^<<v46-6-1,1>>^ Aventura-se algum de vós, tendo questão contra outro, a submetê-lo a juízo perante os injustos e não perante os santos?

[[v46-6-2]]

^<<v46-6-2,2>>^ Ou não sabeis que os santos hão de julgar o mundo? Ora, se o mundo deverá ser julgado por vós, sois, acaso, indignos de julgar as coisas mínimas?

[[v46-6-3]]

^<<v46-6-3,3>>^ Não sabeis que havemos de julgar os próprios anjos? Quanto mais as coisas desta vida!

[[v46-6-4]]

^<<v46-6-4,4>>^ Entretanto, vós, quando tendes a julgar negócios terrenos, constituís um tribunal daqueles que não têm nenhuma aceitação na igreja.

[[v46-6-5]]

^<<v46-6-5,5>>^ Para vergonha vo-lo digo. Não há, porventura, nem ao menos um sábio entre vós, que possa julgar no meio da irmandade?

[[v46-6-6]]

^<<v46-6-6,6>>^ Mas irá um irmão a juízo contra outro irmão, e isto perante incrédulos!

[[v46-6-7]]

^<<v46-6-7,7>>^ O só existir entre vós demandas já é completa derrota para vós outros. Por que não sofreis, antes, a injustiça? Por que não sofreis, antes, o dano?

[[v46-6-8]]

^<<v46-6-8,8>>^ Mas vós mesmos fazeis a injustiça e fazeis o dano, e isto aos próprios irmãos!

[[v46-6-9]]

^<<v46-6-9,9>>^ Ou não sabeis que os injustos não herdarão o reino de Deus? Não vos enganeis: nem impuros, nem idólatras, nem adúlteros, nem efeminados, nem sodomitas,

[[v46-6-10]]

^<<v46-6-10,10>>^ nem ladrões, nem avarentos, nem bêbados, nem maldizentes, nem roubadores herdarão o reino de Deus.

[[v46-6-11]]

^<<v46-6-11,11>>^ Tais fostes alguns de vós; mas vós vos lavastes, mas fostes santificados, mas fostes justificados em o nome do Senhor Jesus Cristo e no Espírito do nosso Deus.

[[v46-6-12]]

^<<v46-6-12,12>>^ Todas as coisas me são lícitas, mas nem todas convêm. Todas as coisas me são lícitas, mas eu não me deixarei dominar por nenhuma delas.

[[v46-6-13]]

^<<v46-6-13,13>>^ Os alimentos são para o estômago, e o estômago, para os alimentos; mas Deus destruirá tanto estes como aquele. Porém o corpo não é para a impureza, mas, para o Senhor, e o Senhor, para o corpo.

[[v46-6-14]]

^<<v46-6-14,14>>^ Deus ressuscitou o Senhor e também nos ressuscitará a nós pelo seu poder.

[[v46-6-15]]

^<<v46-6-15,15>>^ Não sabeis que os vossos corpos são membros de Cristo? E eu, porventura, tomaria os membros de Cristo e os faria membros de meretriz? Absolutamente, não.

[[v46-6-16]]

^<<v46-6-16,16>>^ Ou não sabeis que o homem que se une à prostituta forma um só corpo com ela? Porque, como se diz, serão os dois uma só carne.

[[v46-6-17]]

^<<v46-6-17,17>>^ Mas aquele que se une ao Senhor é um espírito com ele.

[[v46-6-18]]

^<<v46-6-18,18>>^ Fugi da impureza. Qualquer outro pecado que uma pessoa cometer é fora do corpo; mas aquele que pratica a imoralidade peca contra o próprio corpo.

[[v46-6-19]]

^<<v46-6-19,19>>^ Acaso, não sabeis que o vosso corpo é santuário do Espírito Santo, que está em vós, o qual tendes da parte de Deus, e que não sois de vós mesmos?

[[v46-6-20]]

^<<v46-6-20,20>>^ Porque fostes comprados por preço. Agora, pois, glorificai a Deus no vosso corpo.

'''

xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[&#60; Capítulo Anterior] | <<v46-6-0,Topo>> | xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[Próximo Capítulo &#62;]