include::./index.adoc[]

[[v9-23-0]]
=== 1 Samuel, 23
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-23-1]]

^<<v9-23-1,1>>^ Foi dito a Davi: Eis que os filisteus pelejam contra Queila e saqueiam as eiras.

[[v9-23-2]]

^<<v9-23-2,2>>^ Consultou Davi ao SENHOR, dizendo: Irei eu e ferirei estes filisteus? Respondeu o SENHOR a Davi: Vai, e ferirás os filisteus, e livrarás Queila.

[[v9-23-3]]

^<<v9-23-3,3>>^ Porém os homens de Davi lhe disseram: Temos medo aqui em Judá, quanto mais indo a Queila contra as tropas dos filisteus.

[[v9-23-4]]

^<<v9-23-4,4>>^ Então, Davi tornou a consultar o SENHOR, e o SENHOR lhe respondeu e disse: Dispõe-te, desce a Queila, porque te dou os filisteus nas tuas mãos.

[[v9-23-5]]

^<<v9-23-5,5>>^ Partiu Davi com seus homens a Queila, e pelejou contra os filisteus, e levou todo o gado, e fez grande morticínio entre eles; assim, Davi salvou os moradores de Queila.

[[v9-23-6]]

^<<v9-23-6,6>>^ Sucedeu que, quando Abiatar, filho de Aimeleque, fugiu para Davi, a Queila, desceu com a estola sacerdotal na mão.

[[v9-23-7]]

^<<v9-23-7,7>>^ Foi anunciado a Saul que Davi tinha ido a Queila. Disse Saul: Deus o entregou nas minhas mãos; está encerrado, pois entrou numa cidade de portas e ferrolhos.

[[v9-23-8]]

^<<v9-23-8,8>>^ Então, Saul mandou chamar todo o povo à peleja, para que descessem a Queila e cercassem Davi e os seus homens.

[[v9-23-9]]

^<<v9-23-9,9>>^ Sabedor, porém, Davi de que Saul maquinava o mal contra ele, disse a Abiatar, sacerdote: Traze aqui a estola sacerdotal.

[[v9-23-10]]

^<<v9-23-10,10>>^ Orou Davi: Ó SENHOR, Deus de Israel, teu servo ouviu que Saul, de fato, procura vir a Queila, para destruir a cidade por causa de mim.

[[v9-23-11]]

^<<v9-23-11,11>>^ Entregar-me-ão os homens de Queila nas mãos dele? Descerá Saul, como o teu servo ouviu? Ah! SENHOR, Deus de Israel, faze-o saber ao teu servo. E disse o SENHOR: Descerá.

[[v9-23-12]]

^<<v9-23-12,12>>^ Perguntou-lhe Davi: Entregar-me-ão os homens de Queila, a mim e aos meus servos, nas mãos de Saul? Respondeu o SENHOR: Entregarão.

[[v9-23-13]]

^<<v9-23-13,13>>^ Então, se dispôs Davi com os seus homens, uns seiscentos, saíram de Queila e se foram sem rumo certo. Sendo anunciado a Saul que Davi fugira de Queila, cessou de persegui-lo.

[[v9-23-14]]

^<<v9-23-14,14>>^ Permaneceu Davi no deserto, nos lugares seguros, e ficou na região montanhosa no deserto de Zife. Saul buscava-o todos os dias, porém Deus não o entregou nas suas mãos.

[[v9-23-15]]

^<<v9-23-15,15>>^ Vendo, pois, Davi que Saul saíra a tirar-lhe a vida, deteve-se no deserto de Zife, em Horesa.

[[v9-23-16]]

^<<v9-23-16,16>>^ Então, se levantou Jônatas, filho de Saul, e foi para Davi, a Horesa, e lhe fortaleceu a confiança em Deus,

[[v9-23-17]]

^<<v9-23-17,17>>^ e lhe disse: Não temas, porque a mão de Saul, meu pai, não te achará; porém tu reinarás sobre Israel, e eu serei contigo o segundo, o que também Saul, meu pai, bem sabe.

[[v9-23-18]]

^<<v9-23-18,18>>^ E ambos fizeram aliança perante o SENHOR. Davi ficou em Horesa, e Jônatas voltou para sua casa.

[[v9-23-19]]

^<<v9-23-19,19>>^ Então, subiram os zifeus a Saul, a Gibeá, dizendo: Não se escondeu Davi entre nós, nos lugares seguros de Horesa, no outeiro de Haquila, que está ao sul de Jesimom?

[[v9-23-20]]

^<<v9-23-20,20>>^ Agora, pois, ó rei, desce conforme te impõe o coração; toca-nos a nós entregarmo-lo nas mãos do rei.

[[v9-23-21]]

^<<v9-23-21,21>>^ Disse Saul: Benditos sejais vós do SENHOR, porque vos compadecestes de mim.

[[v9-23-22]]

^<<v9-23-22,22>>^ Ide, pois, informai-vos ainda melhor, sabei e notai o lugar que frequenta e quem o tenha visto ali; porque me foi dito que é astutíssimo.

[[v9-23-23]]

^<<v9-23-23,23>>^ Pelo que atentai bem e informai-vos acerca de todos os esconderijos em que ele se oculta; então, voltai a ter comigo com seguras informações, e irei convosco; se ele estiver na terra, buscá-lo-ei entre todos os milhares de Judá.

[[v9-23-24]]

^<<v9-23-24,24>>^ Então, se levantaram eles e se foram a Zife, adiante de Saul; Davi, porém, e os seus homens estavam no deserto de Maom, na planície, ao sul de Jesimom.

[[v9-23-25]]

^<<v9-23-25,25>>^ Saul e os seus homens se foram ao encalço dele, e isto foi dito a Davi; pelo que desceu para a penha que está no deserto de Maom. Ouvindo-o Saul, perseguiu a Davi no deserto de Maom.

[[v9-23-26]]

^<<v9-23-26,26>>^ Saul ia de um lado do monte, e Davi e os seus homens, do outro; apressou-se Davi em fugir para escapar de Saul; porém este e os seus homens cercaram Davi e os seus homens para os prender.

[[v9-23-27]]

^<<v9-23-27,27>>^ Então, veio um mensageiro a Saul, dizendo: Apressa-te e vem, porque os filisteus invadiram a terra.

[[v9-23-28]]

^<<v9-23-28,28>>^ Pelo que Saul desistiu de perseguir a Davi e se foi contra os filisteus. Por esta razão, aquele lugar se chamou Pedra de Escape.

[[v9-23-29]]

^<<v9-23-29,29>>^ Subiu Davi daquele lugar e ficou nos lugares seguros de En-Gedi.

'''

xref:009-1-samuel/009-1-samuel-022.adoc#v9-22-0[&#60; Capítulo Anterior] | <<v9-23-0,Topo>> | xref:009-1-samuel/009-1-samuel-024.adoc#v9-24-0[Próximo Capítulo &#62;]