include::./index.adoc[]

[[v9-2-0]]
=== 1 Samuel, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-2-1]]

^<<v9-2-1,1>>^ Então, orou Ana e disse: O meu coração se regozija no SENHOR, a minha força está exaltada no SENHOR; a minha boca se ri dos meus inimigos, porquanto me alegro na tua salvação.

[[v9-2-2]]

^<<v9-2-2,2>>^ Não há santo como o SENHOR; porque não há outro além de ti; e Rocha não há, nenhuma, como o nosso Deus.

[[v9-2-3]]

^<<v9-2-3,3>>^ Não multipliqueis palavras de orgulho, nem saiam coisas arrogantes da vossa boca; porque o SENHOR é o Deus da sabedoria e pesa todos os feitos na balança.

[[v9-2-4]]

^<<v9-2-4,4>>^ O arco dos fortes é quebrado, porém os débeis, cingidos de força.

[[v9-2-5]]

^<<v9-2-5,5>>^ Os que antes eram fartos hoje se alugam por pão, mas os que andavam famintos não sofrem mais fome; até a estéril tem sete filhos, e a que tinha muitos filhos perde o vigor.

[[v9-2-6]]

^<<v9-2-6,6>>^ O SENHOR é o que tira a vida e a dá; faz descer à sepultura e faz subir.

[[v9-2-7]]

^<<v9-2-7,7>>^ O SENHOR empobrece e enriquece; abaixa e também exalta.

[[v9-2-8]]

^<<v9-2-8,8>>^ Levanta o pobre do pó e, desde o monturo, exalta o necessitado, para o fazer assentar entre os príncipes, para o fazer herdar o trono de glória; porque do SENHOR são as colunas da terra, e assentou sobre elas o mundo.

[[v9-2-9]]

^<<v9-2-9,9>>^ Ele guarda os pés dos seus santos, porém os perversos emudecem nas trevas da morte; porque o homem não prevalece pela força.

[[v9-2-10]]

^<<v9-2-10,10>>^ Os que contendem com o SENHOR são quebrantados; dos céus troveja contra eles. O SENHOR julga as extremidades da terra, dá força ao seu rei e exalta o poder do seu ungido.

[[v9-2-11]]

^<<v9-2-11,11>>^ Então, Elcana foi-se a Ramá, a sua casa; porém o menino ficou servindo ao SENHOR, perante o sacerdote Eli.

[[v9-2-12]]

^<<v9-2-12,12>>^ Eram, porém, os filhos de Eli filhos de Belial e não se importavam com o SENHOR;

[[v9-2-13]]

^<<v9-2-13,13>>^ pois o costume daqueles sacerdotes com o povo era que, oferecendo alguém sacrifício, vinha o moço do sacerdote, estando-se cozendo a carne, com um garfo de três dentes na mão;

[[v9-2-14]]

^<<v9-2-14,14>>^ e metia-o na caldeira, ou na panela, ou no tacho, ou na marmita, e tudo quanto o garfo tirava o sacerdote tomava para si; assim se fazia a todo o Israel que ia ali, a Siló.

[[v9-2-15]]

^<<v9-2-15,15>>^ Também, antes de se queimar a gordura, vinha o moço do sacerdote e dizia ao homem que sacrificava: Dá essa carne para assar ao sacerdote; porque não aceitará de ti carne cozida, senão crua.

[[v9-2-16]]

^<<v9-2-16,16>>^ Se o ofertante lhe respondia: Queime-se primeiro a gordura, e, depois, tomarás quanto quiseres, então, ele lhe dizia: Não, porém hás de ma dar agora; se não, tomá-la-ei à força.

[[v9-2-17]]

^<<v9-2-17,17>>^ Era, pois, mui grande o pecado destes moços perante o SENHOR, porquanto eles desprezavam a oferta do SENHOR.

[[v9-2-18]]

^<<v9-2-18,18>>^ Samuel ministrava perante o SENHOR, sendo ainda menino, vestido de uma estola sacerdotal de linho.

[[v9-2-19]]

^<<v9-2-19,19>>^ Sua mãe lhe fazia uma túnica pequena e, de ano em ano, lha trazia quando, com seu marido, subia a oferecer o sacrifício anual.

[[v9-2-20]]

^<<v9-2-20,20>>^ Eli abençoava a Elcana e a sua mulher e dizia: O SENHOR te dê filhos desta mulher, em lugar do filho que devolveu ao SENHOR. E voltavam para a sua casa.

[[v9-2-21]]

^<<v9-2-21,21>>^ Abençoou, pois, o SENHOR a Ana, e ela concebeu e teve três filhos e duas filhas; e o jovem Samuel crescia diante do SENHOR.

[[v9-2-22]]

^<<v9-2-22,22>>^ Era, porém, Eli já muito velho e ouvia tudo quanto seus filhos faziam a todo o Israel e de como se deitavam com as mulheres que serviam à porta da tenda da congregação.

[[v9-2-23]]

^<<v9-2-23,23>>^ E disse-lhes: Por que fazeis tais coisas? Pois de todo este povo ouço constantemente falar do vosso mau procedimento.

[[v9-2-24]]

^<<v9-2-24,24>>^ Não, filhos meus, porque não é boa fama esta que ouço; estais fazendo transgredir o povo do SENHOR.

[[v9-2-25]]

^<<v9-2-25,25>>^ Pecando o homem contra o próximo, Deus lhe será o árbitro; pecando, porém, contra o SENHOR, quem intercederá por ele? Entretanto, não ouviram a voz de seu pai, porque o SENHOR os queria matar.

[[v9-2-26]]

^<<v9-2-26,26>>^ Mas o jovem Samuel crescia em estatura e no favor do SENHOR e dos homens.

[[v9-2-27]]

^<<v9-2-27,27>>^ Veio um homem de Deus a Eli e lhe disse: Assim diz o SENHOR: Não me manifestei, na verdade, à casa de teu pai, estando os israelitas ainda no Egito, na casa de Faraó?

[[v9-2-28]]

^<<v9-2-28,28>>^ Eu o escolhi dentre todas as tribos de Israel para ser o meu sacerdote, para subir ao meu altar, para queimar o incenso e para trazer a estola sacerdotal perante mim; e dei à casa de teu pai todas as ofertas queimadas dos filhos de Israel.

[[v9-2-29]]

^<<v9-2-29,29>>^ Por que pisais aos pés os meus sacrifícios e as minhas ofertas de manjares, que ordenei se me fizessem na minha morada? E, tu, por que honras a teus filhos mais do que a mim, para tu e eles vos engordardes das melhores de todas as ofertas do meu povo de Israel?

[[v9-2-30]]

^<<v9-2-30,30>>^ Portanto, diz o SENHOR, Deus de Israel: Na verdade, dissera eu que a tua casa e a casa de teu pai andariam diante de mim perpetuamente; porém, agora, diz o SENHOR: Longe de mim tal coisa, porque aos que me honram, honrarei, porém os que me desprezam serão desmerecidos.

[[v9-2-31]]

^<<v9-2-31,31>>^ Eis que vêm dias em que cortarei o teu braço e o braço da casa de teu pai, para que não haja mais velho nenhum em tua casa.

[[v9-2-32]]

^<<v9-2-32,32>>^ E verás o aperto da morada de Deus, a um tempo com o bem que fará a Israel; e jamais haverá velho em tua casa.

[[v9-2-33]]

^<<v9-2-33,33>>^ O homem, porém, da tua linhagem a quem eu não afastar do meu altar será para te consumir os olhos e para te entristecer a alma; e todos os descendentes da tua casa morrerão na flor da idade.

[[v9-2-34]]

^<<v9-2-34,34>>^ Ser-te-á por sinal o que sobrevirá a teus dois filhos, a Hofni e Fineias: ambos morrerão no mesmo dia.

[[v9-2-35]]

^<<v9-2-35,35>>^ Então, suscitarei para mim um sacerdote fiel, que procederá segundo o que tenho no coração e na mente; edificar-lhe-ei uma casa estável, e andará ele diante do meu ungido para sempre.

[[v9-2-36]]

^<<v9-2-36,36>>^ Será que todo aquele que restar da tua casa virá a inclinar-se diante dele, para obter uma moeda de prata e um bocado de pão, e dirá: Rogo-te que me admitas a algum dos cargos sacerdotais, para ter um pedaço de pão, que coma.

'''

xref:009-1-samuel/009-1-samuel-001.adoc#v9-1-0[&#60; Capítulo Anterior] | <<v9-2-0,Topo>> | xref:009-1-samuel/009-1-samuel-003.adoc#v9-3-0[Próximo Capítulo &#62;]