include::./index.adoc[]

[[v9-30-0]]
=== 1 Samuel, 30
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-30-1]]

^<<v9-30-1,1>>^ Sucedeu, pois, que, chegando Davi e os seus homens, ao terceiro dia, a Ziclague, já os amalequitas tinham dado com ímpeto contra o Sul e Ziclague e a esta, ferido e queimado;

[[v9-30-2]]

^<<v9-30-2,2>>^ tinham levado cativas as mulheres que lá se achavam, porém a ninguém mataram, nem pequenos nem grandes; tão somente os levaram consigo e foram seu caminho.

[[v9-30-3]]

^<<v9-30-3,3>>^ Davi e os seus homens vieram à cidade, e ei-la queimada, e suas mulheres, seus filhos e suas filhas eram levados cativos.

[[v9-30-4]]

^<<v9-30-4,4>>^ Então, Davi e o povo que se achava com ele ergueram a voz e choraram, até não terem mais forças para chorar.

[[v9-30-5]]

^<<v9-30-5,5>>^ Também as duas mulheres de Davi foram levadas cativas: Ainoã, a jezreelita, e Abigail, a viúva de Nabal, o carmelita.

[[v9-30-6]]

^<<v9-30-6,6>>^ Davi muito se angustiou, pois o povo falava de apedrejá-lo, porque todos estavam em amargura, cada um por causa de seus filhos e de suas filhas; porém Davi se reanimou no SENHOR, seu Deus.

[[v9-30-7]]

^<<v9-30-7,7>>^ Disse Davi a Abiatar, o sacerdote, filho de Aimeleque: Traze-me aqui a estola sacerdotal. E Abiatar a trouxe a Davi.

[[v9-30-8]]

^<<v9-30-8,8>>^ Então, consultou Davi ao SENHOR, dizendo: Perseguirei eu o bando? Alcançá-lo-ei? Respondeu-lhe o SENHOR: Persegue-o, porque, de fato, o alcançarás e tudo libertarás.

[[v9-30-9]]

^<<v9-30-9,9>>^ Partiu, pois, Davi, ele e os seiscentos homens que com ele se achavam, e chegaram ao ribeiro de Besor, onde os retardatários ficaram.

[[v9-30-10]]

^<<v9-30-10,10>>^ Davi, porém, e quatrocentos homens continuaram a perseguição, pois que duzentos ficaram atrás, por não poderem, de cansados que estavam, passar o ribeiro de Besor.

[[v9-30-11]]

^<<v9-30-11,11>>^ Acharam no campo um homem egípcio e o trouxeram a Davi; deram-lhe pão, e comeu, e deram-lhe a beber água.

[[v9-30-12]]

^<<v9-30-12,12>>^ Deram-lhe também um pedaço de pasta de figos secos e dois cachos de passas, e comeu; recobrou, então, o alento, pois havia três dias e três noites que não comia pão, nem bebia água.

[[v9-30-13]]

^<<v9-30-13,13>>^ Então, lhe perguntou Davi: De quem és tu e de onde vens? Respondeu o moço egípcio: Sou servo de um amalequita, e meu senhor me deixou aqui, porque adoeci há três dias.

[[v9-30-14]]

^<<v9-30-14,14>>^ Nós demos com ímpeto contra o lado sul dos queretitas, contra o território de Judá e contra o lado sul de Calebe e pusemos fogo em Ziclague.

[[v9-30-15]]

^<<v9-30-15,15>>^ Disse-lhe Davi: Poderias, descendo, guiar-me a esse bando? Respondeu-lhe: Jura-me, por Deus, que me não matarás, nem me entregarás nas mãos de meu senhor, e descerei e te guiarei a esse bando.

[[v9-30-16]]

^<<v9-30-16,16>>^ E, descendo, o guiou. Eis que estavam espalhados sobre toda a região, comendo, bebendo e fazendo festa por todo aquele grande despojo que tomaram da terra dos filisteus e da terra de Judá.

[[v9-30-17]]

^<<v9-30-17,17>>^ Feriu-os Davi, desde o crepúsculo vespertino até à tarde do dia seguinte, e nenhum deles escapou, senão só quatrocentos moços que, montados em camelos, fugiram.

[[v9-30-18]]

^<<v9-30-18,18>>^ Assim, Davi salvou tudo quanto haviam tomado os amalequitas; também salvou as suas duas mulheres.

[[v9-30-19]]

^<<v9-30-19,19>>^ Não lhes faltou coisa alguma, nem pequena nem grande, nem os filhos, nem as filhas, nem o despojo, nada do que lhes haviam tomado: tudo Davi tornou a trazer.

[[v9-30-20]]

^<<v9-30-20,20>>^ Também tomou Davi todas as ovelhas e o gado, e o levaram diante de Davi e diziam: Este é o despojo de Davi.

[[v9-30-21]]

^<<v9-30-21,21>>^ Chegando Davi aos duzentos homens que, de cansados que estavam, não o puderam seguir e ficaram no ribeiro de Besor, estes saíram ao encontro de Davi e do povo que com ele vinha; Davi, aproximando-se destes, os saudou cordialmente.

[[v9-30-22]]

^<<v9-30-22,22>>^ Então, todos os maus e filhos de Belial, dentre os homens que tinham ido com Davi, responderam e disseram: Visto que não foram conosco, não lhes daremos do despojo que salvamos; cada um, porém, leve sua mulher e seus filhos e se vá embora.

[[v9-30-23]]

^<<v9-30-23,23>>^ Porém Davi disse: Não fareis assim, irmãos meus, com o que nos deu o SENHOR, que nos guardou e entregou às nossas mãos o bando que contra nós vinha.

[[v9-30-24]]

^<<v9-30-24,24>>^ Quem vos daria ouvidos nisso? Porque qual é a parte dos que desceram à peleja, tal será a parte dos que ficaram com a bagagem; receberão partes iguais.

[[v9-30-25]]

^<<v9-30-25,25>>^ E assim, desde aquele dia em diante, foi isso estabelecido por estatuto e direito em Israel, até ao dia de hoje.

[[v9-30-26]]

^<<v9-30-26,26>>^ Chegando Davi a Ziclague, enviou do despojo aos anciãos de Judá, seus amigos, dizendo: Eis para vós outros um presente do despojo dos inimigos do SENHOR:

[[v9-30-27]]

^<<v9-30-27,27>>^ aos de Betel, aos de Ramote do Neguebe, aos de Jatir,

[[v9-30-28]]

^<<v9-30-28,28>>^ aos de Aroer, aos de Sifmote, aos de Estemoa,

[[v9-30-29]]

^<<v9-30-29,29>>^ aos de Racal, aos que estavam nas cidades dos jerameelitas e nas cidades dos queneus,

[[v9-30-30]]

^<<v9-30-30,30>>^ aos de Horma, aos de Borasã, aos de Atace,

[[v9-30-31]]

^<<v9-30-31,31>>^ aos de Hebrom e a todos os lugares em que andara Davi, ele e os seus homens.

'''

xref:009-1-samuel/009-1-samuel-029.adoc#v9-29-0[&#60; Capítulo Anterior] | <<v9-30-0,Topo>> | xref:009-1-samuel/009-1-samuel-031.adoc#v9-31-0[Próximo Capítulo &#62;]