include::./index.adoc[]

[[v9-12-0]]
=== 1 Samuel, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-12-1]]

^<<v9-12-1,1>>^ Então, disse Samuel a todo o Israel: Eis que ouvi a vossa voz em tudo quanto me dissestes e constituí sobre vós um rei.

[[v9-12-2]]

^<<v9-12-2,2>>^ Agora, pois, eis que tendes o rei à vossa frente. Já envelheci e estou cheio de cãs, e meus filhos estão convosco; o meu procedimento esteve diante de vós desde a minha mocidade até ao dia de hoje.

[[v9-12-3]]

^<<v9-12-3,3>>^ Eis-me aqui, testemunhai contra mim perante o SENHOR e perante o seu ungido: de quem tomei o boi? De quem tomei o jumento? A quem defraudei? A quem oprimi? E das mãos de quem aceitei suborno para encobrir com ele os meus olhos? E vo-lo restituirei.

[[v9-12-4]]

^<<v9-12-4,4>>^ Então, responderam: Em nada nos defraudaste, nem nos oprimiste, nem tomaste coisa alguma das mãos de ninguém.

[[v9-12-5]]

^<<v9-12-5,5>>^ E ele lhes disse: O SENHOR é testemunha contra vós outros, e o seu ungido é, hoje, testemunha de que nada tendes achado nas minhas mãos. E o povo confirmou: Deus é testemunha.

[[v9-12-6]]

^<<v9-12-6,6>>^ Então, disse Samuel ao povo: Testemunha é o SENHOR, que escolheu a Moisés e a Arão e tirou vossos pais da terra do Egito.

[[v9-12-7]]

^<<v9-12-7,7>>^ Agora, pois, ponde-vos aqui, e pleitearei convosco perante o SENHOR, relativamente a todos os seus atos de justiça que fez a vós outros e a vossos pais.

[[v9-12-8]]

^<<v9-12-8,8>>^ Havendo entrado Jacó no Egito, clamaram vossos pais ao SENHOR, e o SENHOR enviou a Moisés e a Arão, que os tiraram do Egito e os fizeram habitar neste lugar.

[[v9-12-9]]

^<<v9-12-9,9>>^ Porém esqueceram-se do SENHOR, seu Deus; então, os entregou nas mãos de Sísera, comandante do exército de Hazor, e nas mãos dos filisteus, e nas mãos do rei de Moabe, que pelejaram contra eles.

[[v9-12-10]]

^<<v9-12-10,10>>^ E clamaram ao SENHOR e disseram: Pecamos, pois deixamos o SENHOR e servimos aos baalins e astarotes; agora, pois, livra-nos das mãos de nossos inimigos, e te serviremos.

[[v9-12-11]]

^<<v9-12-11,11>>^ O SENHOR enviou a Jerubaal, e a Baraque, e a Jefté, e a Samuel; e vos livrou das mãos de vossos inimigos em redor, e habitastes em segurança.

[[v9-12-12]]

^<<v9-12-12,12>>^ Vendo vós que Naás, rei dos filhos de Amom, vinha contra vós outros, me dissestes: Não! Mas reinará sobre nós um rei; ao passo que o SENHOR, vosso Deus, era o vosso rei.

[[v9-12-13]]

^<<v9-12-13,13>>^ Agora, pois, eis aí o rei que elegestes e que pedistes; e eis que o SENHOR vos deu um rei.

[[v9-12-14]]

^<<v9-12-14,14>>^ Se temerdes ao SENHOR, e o servirdes, e lhe atenderdes à voz, e não lhe fordes rebeldes ao mandado, e seguirdes o SENHOR, vosso Deus, tanto vós como o vosso rei que governa sobre vós, bem será.

[[v9-12-15]]

^<<v9-12-15,15>>^ Se, porém, não derdes ouvidos à voz do SENHOR, mas, antes, fordes rebeldes ao seu mandado, a mão do SENHOR será contra vós outros, como o foi contra vossos pais.

[[v9-12-16]]

^<<v9-12-16,16>>^ Ponde-vos também, agora, aqui e vede esta grande coisa que o SENHOR fará diante dos vossos olhos.

[[v9-12-17]]

^<<v9-12-17,17>>^ Não é, agora, o tempo da sega do trigo? Clamarei, pois, ao SENHOR, e dará trovões e chuva; e sabereis e vereis que é grande a vossa maldade, que tendes praticado perante o SENHOR, pedindo para vós outros um rei.

[[v9-12-18]]

^<<v9-12-18,18>>^ Então, invocou Samuel ao SENHOR, e o SENHOR deu trovões e chuva naquele dia; pelo que todo o povo temeu em grande maneira ao SENHOR e a Samuel.

[[v9-12-19]]

^<<v9-12-19,19>>^ Todo o povo disse a Samuel: Roga pelos teus servos ao SENHOR, teu Deus, para que não venhamos a morrer; porque a todos os nossos pecados acrescentamos o mal de pedir para nós um rei.

[[v9-12-20]]

^<<v9-12-20,20>>^ Então, disse Samuel ao povo: Não temais; tendes cometido todo este mal; no entanto, não vos desvieis de seguir o SENHOR, mas servi ao SENHOR de todo o vosso coração.

[[v9-12-21]]

^<<v9-12-21,21>>^ Não vos desvieis; pois seguiríeis coisas vãs, que nada aproveitam e tampouco vos podem livrar, porque vaidade são.

[[v9-12-22]]

^<<v9-12-22,22>>^ Pois o SENHOR, por causa do seu grande nome, não desamparará o seu povo, porque aprouve ao SENHOR fazer-vos o seu povo.

[[v9-12-23]]

^<<v9-12-23,23>>^ Quanto a mim, longe de mim que eu peque contra o SENHOR, deixando de orar por vós; antes, vos ensinarei o caminho bom e direito.

[[v9-12-24]]

^<<v9-12-24,24>>^ Tão somente, pois, temei ao SENHOR e servi-o fielmente de todo o vosso coração; pois vede quão grandiosas coisas vos fez.

[[v9-12-25]]

^<<v9-12-25,25>>^ Se, porém, perseverardes em fazer o mal, perecereis, tanto vós como o vosso rei.

'''

xref:009-1-samuel/009-1-samuel-011.adoc#v9-11-0[&#60; Capítulo Anterior] | <<v9-12-0,Topo>> | xref:009-1-samuel/009-1-samuel-013.adoc#v9-13-0[Próximo Capítulo &#62;]