include::./index.adoc[]

[[v9-17-0]]
=== 1 Samuel, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-17-1]]

^<<v9-17-1,1>>^ Ajuntaram os filisteus as suas tropas para a guerra, e congregaram-se em Socó, que está em Judá, e acamparam-se entre Socó e Azeca, em Efes-Damim.

[[v9-17-2]]

^<<v9-17-2,2>>^ Porém Saul e os homens de Israel se ajuntaram, e acamparam no vale de Elá, e ali ordenaram a batalha contra os filisteus.

[[v9-17-3]]

^<<v9-17-3,3>>^ Estavam estes num monte do lado dalém, e os israelitas, no outro monte do lado daquém; e, entre eles, o vale.

[[v9-17-4]]

^<<v9-17-4,4>>^ Então, saiu do arraial dos filisteus um homem guerreiro, cujo nome era Golias, de Gate, da altura de seis côvados e um palmo.

[[v9-17-5]]

^<<v9-17-5,5>>^ Trazia na cabeça um capacete de bronze e vestia uma couraça de escamas cujo peso era de cinco mil siclos de bronze.

[[v9-17-6]]

^<<v9-17-6,6>>^ Trazia caneleiras de bronze nas pernas e um dardo de bronze entre os ombros.

[[v9-17-7]]

^<<v9-17-7,7>>^ A haste da sua lança era como o eixo do tecelão, e a ponta da sua lança, de seiscentos siclos de ferro; e diante dele ia o escudeiro.

[[v9-17-8]]

^<<v9-17-8,8>>^ Parou, clamou às tropas de Israel e disse-lhes: Para que saís, formando-vos em linha de batalha? Não sou eu filisteu, e vós, servos de Saul? Escolhei dentre vós um homem que desça contra mim.

[[v9-17-9]]

^<<v9-17-9,9>>^ Se ele puder pelejar comigo e me ferir, seremos vossos servos; porém, se eu o vencer e o ferir, então, sereis nossos servos e nos servireis.

[[v9-17-10]]

^<<v9-17-10,10>>^ Disse mais o filisteu: Hoje, afronto as tropas de Israel. Dai-me um homem, para que ambos pelejemos.

[[v9-17-11]]

^<<v9-17-11,11>>^ Ouvindo Saul e todo o Israel estas palavras do filisteu, espantaram-se e temeram muito.

[[v9-17-12]]

^<<v9-17-12,12>>^ Davi era filho daquele efrateu de Belém de Judá cujo nome era Jessé, que tinha oito filhos; nos dias de Saul, era já velho e adiantado em anos entre os homens.

[[v9-17-13]]

^<<v9-17-13,13>>^ Apresentaram-se os três filhos mais velhos de Jessé a Saul e o seguiram à guerra; chamavam-se: Eliabe, o primogênito, o segundo, Abinadabe, e o terceiro, Samá.

[[v9-17-14]]

^<<v9-17-14,14>>^ Davi era o mais moço; só os três maiores seguiram Saul.

[[v9-17-15]]

^<<v9-17-15,15>>^ Davi, porém, ia a Saul e voltava, para apascentar as ovelhas de seu pai, em Belém.

[[v9-17-16]]

^<<v9-17-16,16>>^ Chegava-se, pois, o filisteu pela manhã e à tarde; e apresentou-se por quarenta dias.

[[v9-17-17]]

^<<v9-17-17,17>>^ Disse Jessé a Davi, seu filho: Leva, peço-te, para teus irmãos um efa deste trigo tostado e estes dez pães e corre a levá-los ao acampamento, a teus irmãos.

[[v9-17-18]]

^<<v9-17-18,18>>^ Porém estes dez queijos, leva-os ao comandante de mil; e visitarás teus irmãos, a ver se vão bem; e trarás uma prova de como passam.

[[v9-17-19]]

^<<v9-17-19,19>>^ Saul, e eles, e todos os homens de Israel estão no vale de Elá, pelejando com os filisteus.

[[v9-17-20]]

^<<v9-17-20,20>>^ Davi, pois, no dia seguinte, se levantou de madrugada, deixou as ovelhas com um guarda, carregou-se e partiu, como Jessé lhe ordenara; e chegou ao acampamento quando já as tropas saíam para formar-se em ordem de batalha e, a gritos, chamavam à peleja.

[[v9-17-21]]

^<<v9-17-21,21>>^ Os israelitas e filisteus se puseram em ordem, fileira contra fileira.

[[v9-17-22]]

^<<v9-17-22,22>>^ Davi, deixando o que trouxera aos cuidados do guarda da bagagem, correu à batalha; e, chegando, perguntou a seus irmãos se estavam bem.

[[v9-17-23]]

^<<v9-17-23,23>>^ Estando Davi ainda a falar com eles, eis que vinha subindo do exército dos filisteus o duelista, cujo nome era Golias, o filisteu de Gate; e falou as mesmas coisas que antes falara, e Davi o ouviu.

[[v9-17-24]]

^<<v9-17-24,24>>^ Todos os israelitas, vendo aquele homem, fugiam de diante dele, e temiam grandemente,

[[v9-17-25]]

^<<v9-17-25,25>>^ e diziam uns aos outros: Vistes aquele homem que subiu? Pois subiu para afrontar a Israel. A quem o matar, o rei o cumulará de grandes riquezas, e lhe dará por mulher a filha, e à casa de seu pai isentará de impostos em Israel.

[[v9-17-26]]

^<<v9-17-26,26>>^ Então, falou Davi aos homens que estavam consigo, dizendo: Que farão àquele homem que ferir a este filisteu e tirar a afronta de sobre Israel? Quem é, pois, esse incircunciso filisteu, para afrontar os exércitos do Deus vivo?

[[v9-17-27]]

^<<v9-17-27,27>>^ E o povo lhe repetiu as mesmas palavras, dizendo: Assim farão ao homem que o ferir.

[[v9-17-28]]

^<<v9-17-28,28>>^ Ouvindo-o Eliabe, seu irmão mais velho, falar àqueles homens, acendeu-se-lhe a ira contra Davi, e disse: Por que desceste aqui? E a quem deixaste aquelas poucas ovelhas no deserto? Bem conheço a tua presunção e a tua maldade; desceste apenas para ver a peleja.

[[v9-17-29]]

^<<v9-17-29,29>>^ Respondeu Davi: Que fiz eu agora? Fiz somente uma pergunta.

[[v9-17-30]]

^<<v9-17-30,30>>^ Desviou-se dele para outro e falou a mesma coisa; e o povo lhe tornou a responder como dantes.

[[v9-17-31]]

^<<v9-17-31,31>>^ Ouvidas as palavras que Davi falara, anunciaram-nas a Saul, que mandou chamá-lo.

[[v9-17-32]]

^<<v9-17-32,32>>^ Davi disse a Saul: Não desfaleça o coração de ninguém por causa dele; teu servo irá e pelejará contra o filisteu.

[[v9-17-33]]

^<<v9-17-33,33>>^ Porém Saul disse a Davi: Contra o filisteu não poderás ir para pelejar com ele; pois tu és ainda moço, e ele, guerreiro desde a sua mocidade.

[[v9-17-34]]

^<<v9-17-34,34>>^ Respondeu Davi a Saul: Teu servo apascentava as ovelhas de seu pai; quando veio um leão ou um urso e tomou um cordeiro do rebanho,

[[v9-17-35]]

^<<v9-17-35,35>>^ eu saí após ele, e o feri, e livrei o cordeiro da sua boca; levantando-se ele contra mim, agarrei-o pela barba, e o feri, e o matei.

[[v9-17-36]]

^<<v9-17-36,36>>^ O teu servo matou tanto o leão como o urso; este incircunciso filisteu será como um deles, porquanto afrontou os exércitos do Deus vivo.

[[v9-17-37]]

^<<v9-17-37,37>>^ Disse mais Davi: O SENHOR me livrou das garras do leão e das do urso; ele me livrará das mãos deste filisteu. Então, disse Saul a Davi: Vai-te, e o SENHOR seja contigo.

[[v9-17-38]]

^<<v9-17-38,38>>^ Saul vestiu a Davi da sua armadura, e lhe pôs sobre a cabeça um capacete de bronze, e o vestiu de uma couraça.

[[v9-17-39]]

^<<v9-17-39,39>>^ Davi cingiu a espada sobre a armadura e experimentou andar, pois jamais a havia usado; então, disse Davi a Saul: Não posso andar com isto, pois nunca o usei. E Davi tirou aquilo de sobre si.

[[v9-17-40]]

^<<v9-17-40,40>>^ Tomou o seu cajado na mão, e escolheu para si cinco pedras lisas do ribeiro, e as pôs no alforje de pastor, que trazia, a saber, no surrão; e, lançando mão da sua funda, foi-se chegando ao filisteu.

[[v9-17-41]]

^<<v9-17-41,41>>^ O filisteu também se vinha chegando a Davi; e o seu escudeiro ia adiante dele.

[[v9-17-42]]

^<<v9-17-42,42>>^ Olhando o filisteu e vendo a Davi, o desprezou, porquanto era moço ruivo e de boa aparência.

[[v9-17-43]]

^<<v9-17-43,43>>^ Disse o filisteu a Davi: Sou eu algum cão, para vires a mim com paus? E, pelos seus deuses, amaldiçoou o filisteu a Davi.

[[v9-17-44]]

^<<v9-17-44,44>>^ Disse mais o filisteu a Davi: Vem a mim, e darei a tua carne às aves do céu e às bestas-feras do campo.

[[v9-17-45]]

^<<v9-17-45,45>>^ Davi, porém, disse ao filisteu: Tu vens contra mim com espada, e com lança, e com escudo; eu, porém, vou contra ti em nome do SENHOR dos Exércitos, o Deus dos exércitos de Israel, a quem tens afrontado.

[[v9-17-46]]

^<<v9-17-46,46>>^ Hoje mesmo, o SENHOR te entregará nas minhas mãos; ferir-te-ei, tirar-te-ei a cabeça e os cadáveres do arraial dos filisteus darei, hoje mesmo, às aves dos céus e às bestas-feras da terra; e toda a terra saberá que há Deus em Israel.

[[v9-17-47]]

^<<v9-17-47,47>>^ Saberá toda esta multidão que o SENHOR salva, não com espada, nem com lança; porque do SENHOR é a guerra, e ele vos entregará nas nossas mãos.

[[v9-17-48]]

^<<v9-17-48,48>>^ Sucedeu que, dispondo-se o filisteu a encontrar-se com Davi, este se apressou e, deixando as suas fileiras, correu de encontro ao filisteu.

[[v9-17-49]]

^<<v9-17-49,49>>^ Davi meteu a mão no alforje, e tomou dali uma pedra, e com a funda lha atirou, e feriu o filisteu na testa; a pedra encravou-se-lhe na testa, e ele caiu com o rosto em terra.

[[v9-17-50]]

^<<v9-17-50,50>>^ Assim, prevaleceu Davi contra o filisteu, com uma funda e com uma pedra, e o feriu, e o matou; porém não havia espada na mão de Davi.

[[v9-17-51]]

^<<v9-17-51,51>>^ Pelo que correu Davi, e, lançando-se sobre o filisteu, tomou-lhe a espada, e desembainhou-a, e o matou, cortando-lhe com ela a cabeça. Vendo os filisteus que era morto o seu herói, fugiram.

[[v9-17-52]]

^<<v9-17-52,52>>^ Então, os homens de Israel e Judá se levantaram, e jubilaram, e perseguiram os filisteus, até Gate e até às portas de Ecrom. E caíram filisteus feridos pelo caminho, de Saaraim até Gate e até Ecrom.

[[v9-17-53]]

^<<v9-17-53,53>>^ Então, voltaram os filhos de Israel de perseguirem os filisteus e lhes despojaram os acampamentos.

[[v9-17-54]]

^<<v9-17-54,54>>^ Tomou Davi a cabeça do filisteu e a trouxe a Jerusalém; porém as armas dele pô-las Davi na sua tenda.

[[v9-17-55]]

^<<v9-17-55,55>>^ Quando Saul viu sair Davi a encontrar-se com o filisteu, disse a Abner, o comandante do exército: De quem é filho este jovem, Abner? Respondeu Abner: Tão certo como tu vives, ó rei, não o sei.

[[v9-17-56]]

^<<v9-17-56,56>>^ Disse o rei: Pergunta, pois, de quem é filho este jovem.

[[v9-17-57]]

^<<v9-17-57,57>>^ Voltando Davi de haver ferido o filisteu, Abner o tomou e o levou à presença de Saul, trazendo ele na mão a cabeça do filisteu.

[[v9-17-58]]

^<<v9-17-58,58>>^ Então, Saul lhe perguntou: De quem és filho, jovem? Respondeu Davi: Filho de teu servo Jessé, belemita.

'''

xref:009-1-samuel/009-1-samuel-016.adoc#v9-16-0[&#60; Capítulo Anterior] | <<v9-17-0,Topo>> | xref:009-1-samuel/009-1-samuel-018.adoc#v9-18-0[Próximo Capítulo &#62;]