include::./index.adoc[]

[[v9-4-0]]
=== 1 Samuel, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-4-1]]

^<<v9-4-1,1>>^ Veio a palavra de Samuel a todo o Israel. Israel saiu à peleja contra os filisteus e se acampou junto a Ebenézer; e os filisteus se acamparam junto a Afeca.

[[v9-4-2]]

^<<v9-4-2,2>>^ Dispuseram-se os filisteus em ordem de batalha, para sair de encontro a Israel; e, travada a peleja, Israel foi derrotado pelos filisteus; e estes mataram, no campo aberto, cerca de quatro mil homens.

[[v9-4-3]]

^<<v9-4-3,3>>^ Voltando o povo ao arraial, disseram os anciãos de Israel: Por que nos feriu o SENHOR, hoje, diante dos filisteus? Tragamos de Siló a arca da Aliança do SENHOR, para que venha no meio de nós e nos livre das mãos de nossos inimigos.

[[v9-4-4]]

^<<v9-4-4,4>>^ Mandou, pois, o povo trazer de Siló a arca do SENHOR dos Exércitos, entronizado entre os querubins; os dois filhos de Eli, Hofni e Fineias, estavam ali com a arca da Aliança de Deus.

[[v9-4-5]]

^<<v9-4-5,5>>^ Sucedeu que, vindo a arca da Aliança do SENHOR ao arraial, rompeu todo o Israel em grandes brados, e ressoou a terra.

[[v9-4-6]]

^<<v9-4-6,6>>^ Ouvindo os filisteus a voz do júbilo, disseram: Que voz de grande júbilo é esta no arraial dos hebreus? Então, souberam que a arca do SENHOR era vinda ao arraial.

[[v9-4-7]]

^<<v9-4-7,7>>^ E se atemorizaram os filisteus e disseram: Os deuses vieram ao arraial. E diziam mais: Ai de nós! Que tal jamais sucedeu antes.

[[v9-4-8]]

^<<v9-4-8,8>>^ Ai de nós! Quem nos livrará das mãos destes grandiosos deuses? São os deuses que feriram aos egípcios com toda sorte de pragas no deserto.

[[v9-4-9]]

^<<v9-4-9,9>>^ Sede fortes, ó filisteus! Portai-vos varonilmente, para que não venhais a ser escravos dos hebreus, como eles serviram a vós outros! Portai-vos varonilmente e pelejai!

[[v9-4-10]]

^<<v9-4-10,10>>^ Então, pelejaram os filisteus; Israel foi derrotado, e cada um fugiu para a sua tenda; foi grande a derrota, pois foram mortos de Israel trinta mil homens de pé.

[[v9-4-11]]

^<<v9-4-11,11>>^ Foi tomada a arca de Deus, e mortos os dois filhos de Eli, Hofni e Fineias.

[[v9-4-12]]

^<<v9-4-12,12>>^ Então, correu um homem de Benjamim, saído das fileiras, e, no mesmo dia, chegou a Siló; trazia rasgadas as vestes e terra sobre a cabeça.

[[v9-4-13]]

^<<v9-4-13,13>>^ Quando chegou, Eli estava assentado numa cadeira, ao pé do caminho, olhando como quem espera, porque o seu coração estava tremendo pela arca de Deus. Depois de entrar o homem na cidade e dar as novas, toda a cidade prorrompeu em gritos.

[[v9-4-14]]

^<<v9-4-14,14>>^ Eli, ouvindo os gritos, perguntou: Que alvoroço é esse? Então, se apressou o homem e, vindo, deu as notícias a Eli.

[[v9-4-15]]

^<<v9-4-15,15>>^ Era Eli da idade de noventa e oito anos; os seus olhos tinham cegado, e já não podia ver.

[[v9-4-16]]

^<<v9-4-16,16>>^ Disse o homem a Eli: Eu sou o que saí das fileiras e delas fugi hoje mesmo. Perguntou-lhe Eli: Que sucedeu, meu filho?

[[v9-4-17]]

^<<v9-4-17,17>>^ Então, respondeu o que trazia as novas e disse: Israel fugiu de diante dos filisteus, houve grande morticínio entre o povo, e também os teus dois filhos, Hofni e Fineias, foram mortos, e a arca de Deus foi tomada.

[[v9-4-18]]

^<<v9-4-18,18>>^ Ao fazer ele menção da arca de Deus, caiu Eli da cadeira para trás, junto ao portão, e quebrou-se-lhe o pescoço, e morreu, porque era já homem velho e pesado; e havia ele julgado a Israel quarenta anos.

[[v9-4-19]]

^<<v9-4-19,19>>^ Estando sua nora, a mulher de Fineias, grávida, e próximo o parto, ouvindo estas novas, de que a arca de Deus fora tomada e de que seu sogro e seu marido morreram, encurvou-se e deu à luz; porquanto as dores lhe sobrevieram.

[[v9-4-20]]

^<<v9-4-20,20>>^ Ao expirar, disseram as mulheres que a assistiam: Não temas, pois tiveste um filho. Ela, porém, não respondeu, nem fez caso disso.

[[v9-4-21]]

^<<v9-4-21,21>>^ Mas chamou ao menino Icabô, dizendo: Foi-se a glória de Israel. Isto ela disse, porque a arca de Deus fora tomada e por causa de seu sogro e de seu marido.

[[v9-4-22]]

^<<v9-4-22,22>>^ E falou mais: Foi-se a glória de Israel, pois foi tomada a arca de Deus.

'''

xref:009-1-samuel/009-1-samuel-003.adoc#v9-3-0[&#60; Capítulo Anterior] | <<v9-4-0,Topo>> | xref:009-1-samuel/009-1-samuel-005.adoc#v9-5-0[Próximo Capítulo &#62;]