include::./index.adoc[]

[[v9-9-0]]
=== 1 Samuel, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-9-1]]

^<<v9-9-1,1>>^ Havia um homem de Benjamim, cujo nome era Quis, filho de Abiel, filho de Zeror, filho de Becorate, filho de Afias, benjamita, homem de bens.

[[v9-9-2]]

^<<v9-9-2,2>>^ Tinha ele um filho cujo nome era Saul, moço e tão belo, que entre os filhos de Israel não havia outro mais belo do que ele; desde os ombros para cima, sobressaía a todo o povo.

[[v9-9-3]]

^<<v9-9-3,3>>^ Extraviaram-se as jumentas de Quis, pai de Saul. Disse Quis a Saul, seu filho: Toma agora contigo um dos moços, dispõe-te e vai procurar as jumentas.

[[v9-9-4]]

^<<v9-9-4,4>>^ Então, atravessando a região montanhosa de Efraim e a terra de Salisa, não as acharam; depois, passaram à terra de Saalim; porém elas não estavam ali; passaram ainda à terra de Benjamim; todavia, não as acharam.

[[v9-9-5]]

^<<v9-9-5,5>>^ Vindo eles, então, à terra de Zufe, Saul disse para o seu moço, com quem ele ia: Vem, e voltemos; não suceda que meu pai deixe de preocupar-se com as jumentas e se aflija por causa de nós.

[[v9-9-6]]

^<<v9-9-6,6>>^ Porém ele lhe disse: Nesta cidade há um homem de Deus, e é muito estimado; tudo quanto ele diz sucede; vamo-nos, agora, lá; mostrar-nos-á, porventura, o caminho que devemos seguir.

[[v9-9-7]]

^<<v9-9-7,7>>^ Então, Saul disse ao seu moço: Eis, porém, se lá formos, que levaremos, então, àquele homem? Porque o pão de nossos alforjes se acabou, e presente não temos que levar ao homem de Deus. Que temos?

[[v9-9-8]]

^<<v9-9-8,8>>^ O moço tornou a responder a Saul e disse: Eis que tenho ainda em mãos um quarto de siclo de prata, o qual darei ao homem de Deus, para que nos mostre o caminho.

[[v9-9-9]]

^<<v9-9-9,9>>^ (Antigamente, em Israel, indo alguém consultar a Deus, dizia: Vinde, vamos ter com o vidente; porque ao profeta de hoje, antigamente, se chamava vidente.)

[[v9-9-10]]

^<<v9-9-10,10>>^ Então, disse Saul ao moço: Dizes bem; anda, pois, vamos. E foram-se à cidade onde estava o homem de Deus.

[[v9-9-11]]

^<<v9-9-11,11>>^ Subindo eles pela encosta da cidade, encontraram umas moças que saíam a tirar água e lhes perguntaram: Está aqui o vidente?

[[v9-9-12]]

^<<v9-9-12,12>>^ Elas responderam: Está. Eis aí o tens diante de ti; apressa-te, pois, porque, hoje, veio à cidade; porquanto o povo oferece, hoje, sacrifício no alto.

[[v9-9-13]]

^<<v9-9-13,13>>^ Entrando vós na cidade, logo o achareis, antes que suba ao alto para comer; porque o povo não comerá enquanto ele não chegar, porque ele tem de abençoar o sacrifício, e só depois comem os convidados; subi, pois, agora, que, hoje, o achareis.

[[v9-9-14]]

^<<v9-9-14,14>>^ Subiram, pois, à cidade; ao entrarem, eis que Samuel lhes saiu ao encontro, para subir ao alto.

[[v9-9-15]]

^<<v9-9-15,15>>^ Ora, o SENHOR, um dia antes de Saul chegar, o revelara a Samuel, dizendo:

[[v9-9-16]]

^<<v9-9-16,16>>^ Amanhã a estas horas, te enviarei um homem da terra de Benjamim, o qual ungirás por príncipe sobre o meu povo de Israel, e ele livrará o meu povo das mãos dos filisteus; porque atentei para o meu povo, pois o seu clamor chegou a mim.

[[v9-9-17]]

^<<v9-9-17,17>>^ Quando Samuel viu a Saul, o SENHOR lhe disse: Eis o homem de quem eu já te falara. Este dominará sobre o meu povo.

[[v9-9-18]]

^<<v9-9-18,18>>^ Saul se chegou a Samuel no meio da porta e disse: Mostra-me, peço-te, onde é aqui a casa do vidente.

[[v9-9-19]]

^<<v9-9-19,19>>^ Samuel respondeu a Saul e disse: Eu sou o vidente; sobe adiante de mim ao alto; hoje, comereis comigo. Pela manhã, te despedirei e tudo quanto está no teu coração to declararei.

[[v9-9-20]]

^<<v9-9-20,20>>^ Quanto às jumentas que há três dias se te perderam, não se preocupe o teu coração com elas, porque já se encontraram. E para quem está reservado tudo o que é precioso em Israel? Não é para ti e para toda a casa de teu pai?

[[v9-9-21]]

^<<v9-9-21,21>>^ Então, respondeu Saul e disse: Porventura, não sou benjamita, da menor das tribos de Israel? E a minha família, a menor de todas as famílias da tribo de Benjamim? Por que, pois, me falas com tais palavras?

[[v9-9-22]]

^<<v9-9-22,22>>^ Samuel, tomando a Saul e ao seu moço, levou-os à sala de jantar e lhes deu o lugar de honra entre os convidados, que eram cerca de trinta pessoas.

[[v9-9-23]]

^<<v9-9-23,23>>^ Então, disse Samuel ao cozinheiro: Traze a porção que te dei, de que te disse: Põe-na à parte contigo.

[[v9-9-24]]

^<<v9-9-24,24>>^ Tomou, pois, o cozinheiro a coxa com o que havia nela e a pôs diante de Saul. Disse Samuel: Eis que isto é o que foi reservado; toma-o e come, pois se guardou para ti para esta ocasião, ao dizer eu: Convidei o povo. Assim, comeu Saul com Samuel naquele dia.

[[v9-9-25]]

^<<v9-9-25,25>>^ Tendo descido do alto para a cidade, falou Samuel com Saul sobre o eirado.

[[v9-9-26]]

^<<v9-9-26,26>>^ Levantaram-se de madrugada; e, quase ao subir da alva, chamou Samuel a Saul ao eirado, dizendo: Levanta-te; eu irei contigo para te encaminhar. Levantou-se Saul, e saíram ambos, ele e Samuel.

[[v9-9-27]]

^<<v9-9-27,27>>^ Desciam eles para a extremidade da cidade, quando Samuel disse a Saul: Dize ao moço que passe adiante de nós, e tu, tendo ele passado, espera, que te farei saber a palavra de Deus.

'''

xref:009-1-samuel/009-1-samuel-008.adoc#v9-8-0[&#60; Capítulo Anterior] | <<v9-9-0,Topo>> | xref:009-1-samuel/009-1-samuel-010.adoc#v9-10-0[Próximo Capítulo &#62;]