include::./index.adoc[]

[[v9-8-0]]
=== 1 Samuel, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-8-1]]

^<<v9-8-1,1>>^ Tendo Samuel envelhecido, constituiu seus filhos por juízes sobre Israel.

[[v9-8-2]]

^<<v9-8-2,2>>^ O primogênito chamava-se Joel, e o segundo, Abias; e foram juízes em Berseba.

[[v9-8-3]]

^<<v9-8-3,3>>^ Porém seus filhos não andaram pelos caminhos dele; antes, se inclinaram à avareza, e aceitaram subornos, e perverteram o direito.

[[v9-8-4]]

^<<v9-8-4,4>>^ Então, os anciãos todos de Israel se congregaram, e vieram a Samuel, a Ramá,

[[v9-8-5]]

^<<v9-8-5,5>>^ e lhe disseram: Vê, já estás velho, e teus filhos não andam pelos teus caminhos; constitui-nos, pois, agora, um rei sobre nós, para que nos governe, como o têm todas as nações.

[[v9-8-6]]

^<<v9-8-6,6>>^ Porém esta palavra não agradou a Samuel, quando disseram: Dá-nos um rei, para que nos governe. Então, Samuel orou ao SENHOR.

[[v9-8-7]]

^<<v9-8-7,7>>^ Disse o SENHOR a Samuel: Atende à voz do povo em tudo quanto te diz, pois não te rejeitou a ti, mas a mim, para eu não reinar sobre ele.

[[v9-8-8]]

^<<v9-8-8,8>>^ Segundo todas as obras que fez desde o dia em que o tirei do Egito até hoje, pois a mim me deixou, e a outros deuses serviu, assim também o faz a ti.

[[v9-8-9]]

^<<v9-8-9,9>>^ Agora, pois, atende à sua voz, porém adverte-o solenemente e explica-lhe qual será o direito do rei que houver de reinar sobre ele.

[[v9-8-10]]

^<<v9-8-10,10>>^ Referiu Samuel todas as palavras do SENHOR ao povo, que lhe pedia um rei,

[[v9-8-11]]

^<<v9-8-11,11>>^ e disse: Este será o direito do rei que houver de reinar sobre vós: ele tomará os vossos filhos e os empregará no serviço dos seus carros e como seus cavaleiros, para que corram adiante deles;

[[v9-8-12]]

^<<v9-8-12,12>>^ e os porá uns por capitães de mil e capitães de cinquenta; outros para lavrarem os seus campos e ceifarem as suas messes; e outros para fabricarem suas armas de guerra e o aparelhamento de seus carros.

[[v9-8-13]]

^<<v9-8-13,13>>^ Tomará as vossas filhas para perfumistas, cozinheiras e padeiras.

[[v9-8-14]]

^<<v9-8-14,14>>^ Tomará o melhor das vossas lavouras, e das vossas vinhas, e dos vossos olivais e o dará aos seus servidores.

[[v9-8-15]]

^<<v9-8-15,15>>^ As vossas sementeiras e as vossas vinhas dizimará, para dar aos seus oficiais e aos seus servidores.

[[v9-8-16]]

^<<v9-8-16,16>>^ Também tomará os vossos servos, e as vossas servas, e os vossos melhores jovens, e os vossos jumentos e os empregará no seu trabalho.

[[v9-8-17]]

^<<v9-8-17,17>>^ Dizimará o vosso rebanho, e vós lhe sereis por servos.

[[v9-8-18]]

^<<v9-8-18,18>>^ Então, naquele dia, clamareis por causa do vosso rei que houverdes escolhido; mas o SENHOR não vos ouvirá naquele dia.

[[v9-8-19]]

^<<v9-8-19,19>>^ Porém o povo não atendeu à voz de Samuel e disse: Não! Mas teremos um rei sobre nós.

[[v9-8-20]]

^<<v9-8-20,20>>^ Para que sejamos também como todas as nações; o nosso rei poderá governar-nos, sair adiante de nós e fazer as nossas guerras.

[[v9-8-21]]

^<<v9-8-21,21>>^ Ouvindo, pois, Samuel todas as palavras do povo, as repetiu perante o SENHOR.

[[v9-8-22]]

^<<v9-8-22,22>>^ Então, o SENHOR disse a Samuel: Atende à sua voz e estabelece-lhe um rei. Samuel disse aos filhos de Israel: Volte cada um para sua cidade.

'''

xref:009-1-samuel/009-1-samuel-007.adoc#v9-7-0[&#60; Capítulo Anterior] | <<v9-8-0,Topo>> | xref:009-1-samuel/009-1-samuel-009.adoc#v9-9-0[Próximo Capítulo &#62;]