include::./index.adoc[]

[[v9-3-0]]
=== 1 Samuel, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-3-1]]

^<<v9-3-1,1>>^ O jovem Samuel servia ao SENHOR, perante Eli. Naqueles dias, a palavra do SENHOR era mui rara; as visões não eram frequentes.

[[v9-3-2]]

^<<v9-3-2,2>>^ Certo dia, estando deitado no lugar costumado o sacerdote Eli, cujos olhos já começavam a escurecer-se, a ponto de não poder ver,

[[v9-3-3]]

^<<v9-3-3,3>>^ e tendo-se deitado também Samuel, no templo do SENHOR, em que estava a arca, antes que a lâmpada de Deus se apagasse,

[[v9-3-4]]

^<<v9-3-4,4>>^ o SENHOR chamou o menino: Samuel, Samuel! Este respondeu: Eis-me aqui!

[[v9-3-5]]

^<<v9-3-5,5>>^ Correu a Eli e disse: Eis-me aqui, pois tu me chamaste. Mas ele disse: Não te chamei; torna a deitar-te. Ele se foi e se deitou.

[[v9-3-6]]

^<<v9-3-6,6>>^ Tornou o SENHOR a chamar: Samuel! Este se levantou, foi a Eli e disse: Eis-me aqui, pois tu me chamaste. Mas ele disse: Não te chamei, meu filho, torna a deitar-te.

[[v9-3-7]]

^<<v9-3-7,7>>^ Porém Samuel ainda não conhecia o SENHOR, e ainda não lhe tinha sido manifestada a palavra do SENHOR.

[[v9-3-8]]

^<<v9-3-8,8>>^ O SENHOR, pois, tornou a chamar a Samuel, terceira vez, e ele se levantou, e foi a Eli, e disse: Eis-me aqui, pois tu me chamaste. Então, entendeu Eli que era o SENHOR quem chamava o jovem.

[[v9-3-9]]

^<<v9-3-9,9>>^ Por isso, Eli disse a Samuel: Vai deitar-te; se alguém te chamar, dirás: Fala, SENHOR, porque o teu servo ouve. E foi Samuel para o seu lugar e se deitou.

[[v9-3-10]]

^<<v9-3-10,10>>^ Então, veio o SENHOR, e ali esteve, e chamou como das outras vezes: Samuel, Samuel! Este respondeu: Fala, porque o teu servo ouve.

[[v9-3-11]]

^<<v9-3-11,11>>^ Disse o SENHOR a Samuel: Eis que vou fazer uma coisa em Israel, a qual todo o que a ouvir lhe tinirão ambos os ouvidos.

[[v9-3-12]]

^<<v9-3-12,12>>^ Naquele dia, suscitarei contra Eli tudo quanto tenho falado com respeito à sua casa; começarei e o cumprirei.

[[v9-3-13]]

^<<v9-3-13,13>>^ Porque já lhe disse que julgarei a sua casa para sempre, pela iniquidade que ele bem conhecia, porque seus filhos se fizeram execráveis, e ele os não repreendeu.

[[v9-3-14]]

^<<v9-3-14,14>>^ Portanto, jurei à casa de Eli que nunca lhe será expiada a iniquidade, nem com sacrifício, nem com oferta de manjares.

[[v9-3-15]]

^<<v9-3-15,15>>^ Ficou Samuel deitado até pela manhã e, então, abriu as portas da Casa do SENHOR; porém temia relatar a visão a Eli.

[[v9-3-16]]

^<<v9-3-16,16>>^ Chamou Eli a Samuel e disse: Samuel, meu filho! Ele respondeu: Eis-me aqui!

[[v9-3-17]]

^<<v9-3-17,17>>^ Então, ele disse: Que é que o SENHOR te falou? Peço-te que mo não encubras; assim Deus te faça o que bem lhe aprouver se me encobrires alguma coisa de tudo o que te falou.

[[v9-3-18]]

^<<v9-3-18,18>>^ Então, Samuel lhe referiu tudo e nada lhe encobriu. E disse Eli: É o SENHOR; faça o que bem lhe aprouver.

[[v9-3-19]]

^<<v9-3-19,19>>^ Crescia Samuel, e o SENHOR era com ele, e nenhuma de todas as suas palavras deixou cair em terra.

[[v9-3-20]]

^<<v9-3-20,20>>^ Todo o Israel, desde Dã até Berseba, conheceu que Samuel estava confirmado como profeta do SENHOR.

[[v9-3-21]]

^<<v9-3-21,21>>^ Continuou o SENHOR a aparecer em Siló, enquanto por sua palavra o SENHOR se manifestava ali a Samuel.

'''

xref:009-1-samuel/009-1-samuel-002.adoc#v9-2-0[&#60; Capítulo Anterior] | <<v9-3-0,Topo>> | xref:009-1-samuel/009-1-samuel-004.adoc#v9-4-0[Próximo Capítulo &#62;]