include::./index.adoc[]

[[v9-20-0]]
=== 1 Samuel, 20
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-20-1]]

^<<v9-20-1,1>>^ Então, fugiu Davi da casa dos profetas, em Ramá, e veio, e disse a Jônatas: Que fiz eu? Qual é a minha culpa? E qual é o meu pecado diante de teu pai, que procura tirar-me a vida?

[[v9-20-2]]

^<<v9-20-2,2>>^ Ele lhe respondeu: Tal não suceda; não serás morto. Meu pai não faz coisa nenhuma, nem grande nem pequena, sem primeiro me dizer; por que, pois, meu pai me ocultaria isso? Não há nada disso.

[[v9-20-3]]

^<<v9-20-3,3>>^ Então, Davi respondeu enfaticamente: Mui bem sabe teu pai que da tua parte achei mercê; pelo que disse consigo: Não saiba isto Jônatas, para que não se entristeça. Tão certo como vive o SENHOR, e tu vives, Jônatas, apenas há um passo entre mim e a morte.

[[v9-20-4]]

^<<v9-20-4,4>>^ Disse Jônatas a Davi: O que tu desejares eu te farei.

[[v9-20-5]]

^<<v9-20-5,5>>^ Disse Davi a Jônatas: Amanhã é a Festa da Lua Nova, em que sem falta deveria assentar-me com o rei para comer; mas deixa-me ir, e esconder-me-ei no campo, até à terceira tarde.

[[v9-20-6]]

^<<v9-20-6,6>>^ Se teu pai notar a minha ausência, dirás: Davi me pediu muito que o deixasse ir a toda pressa a Belém, sua cidade; porquanto se faz lá o sacrifício anual para toda a família.

[[v9-20-7]]

^<<v9-20-7,7>>^ Se disser assim: Está bem! Então, teu servo terá paz. Porém, se muito se indignar, sabe que já o mal está, de fato, determinado por ele.

[[v9-20-8]]

^<<v9-20-8,8>>^ Usa, pois, de misericórdia para com o teu servo, porque lhe fizeste entrar contigo em aliança no SENHOR; se, porém, há em mim culpa, mata-me tu mesmo; por que me levarias a teu pai?

[[v9-20-9]]

^<<v9-20-9,9>>^ Então, disse Jônatas: Longe de ti tal coisa; porém, se dalguma sorte soubesse que já este mal estava, de fato, determinado por meu pai, para que viesse sobre ti, não to declararia eu?

[[v9-20-10]]

^<<v9-20-10,10>>^ Perguntou Davi a Jônatas: Quem tal me fará saber, se, por acaso, teu pai te responder asperamente?

[[v9-20-11]]

^<<v9-20-11,11>>^ Então, disse Jônatas a Davi: Vem, e saiamos ao campo. E saíram.

[[v9-20-12]]

^<<v9-20-12,12>>^ E disse Jônatas a Davi: O SENHOR, Deus de Israel, seja testemunha. Amanhã ou depois de amanhã, a estas horas sondarei meu pai; se algo houver favorável a Davi, eu to mandarei dizer.

[[v9-20-13]]

^<<v9-20-13,13>>^ Mas, se meu pai quiser fazer-te mal, faça com Jônatas o SENHOR o que a este aprouver, se não to fizer saber eu e não te deixar ir embora, para que sigas em paz. E seja o SENHOR contigo, como tem sido com meu pai.

[[v9-20-14]]

^<<v9-20-14,14>>^ Se eu, então, ainda viver, porventura, não usarás para comigo da bondade do SENHOR, para que não morra?

[[v9-20-15]]

^<<v9-20-15,15>>^ Nem tampouco cortarás jamais da minha casa a tua bondade; nem ainda quando o SENHOR desarraigar da terra todos os inimigos de Davi.

[[v9-20-16]]

^<<v9-20-16,16>>^ Assim, fez Jônatas aliança com a casa de Davi, dizendo: Vingue o SENHOR os inimigos de Davi.

[[v9-20-17]]

^<<v9-20-17,17>>^ Jônatas fez jurar a Davi de novo, pelo amor que este lhe tinha, porque Jônatas o amava com todo o amor da sua alma.

[[v9-20-18]]

^<<v9-20-18,18>>^ Disse-lhe Jônatas: Amanhã é a Festa da Lua Nova; perguntar-se-á por ti, porque o teu lugar estará vazio.

[[v9-20-19]]

^<<v9-20-19,19>>^ Ao terceiro dia, descerás apressadamente e irás para o lugar em que te escondeste no dia do ajuste; e fica junto à pedra de Ezel.

[[v9-20-20]]

^<<v9-20-20,20>>^ Atirarei três flechas para aquele lado, como quem atira ao alvo.

[[v9-20-21]]

^<<v9-20-21,21>>^ Eis que mandarei o moço e lhe direi: Vai, procura as flechas; se eu disser ao moço: Olha que as flechas estão para cá de ti, traze-as; então, vem, Davi, porque, tão certo como vive o SENHOR, terás paz, e nada há que temer.

[[v9-20-22]]

^<<v9-20-22,22>>^ Porém, se disser ao moço: Olha que as flechas estão para lá de ti. Vai-te embora, porque o SENHOR te manda ir.

[[v9-20-23]]

^<<v9-20-23,23>>^ Quanto àquilo de que eu e tu falamos, eis que o SENHOR está entre mim e ti, para sempre.

[[v9-20-24]]

^<<v9-20-24,24>>^ Escondeu-se, pois, Davi no campo; e, sendo a Festa da Lua Nova, pôs-se o rei à mesa para comer.

[[v9-20-25]]

^<<v9-20-25,25>>^ Assentou-se o rei na sua cadeira, segundo o costume, no lugar junto à parede; Jônatas, defronte dele, e Abner, ao lado de Saul; mas o lugar de Davi estava desocupado.

[[v9-20-26]]

^<<v9-20-26,26>>^ Porém, naquele dia, não disse Saul nada, pois pensava: Aconteceu-lhe alguma coisa, pela qual não está limpo; talvez esteja contaminado.

[[v9-20-27]]

^<<v9-20-27,27>>^ Sucedeu também ao outro dia, o segundo da Festa da Lua Nova, que o lugar de Davi continuava desocupado; disse, pois, Saul a Jônatas, seu filho: Por que não veio a comer o filho de Jessé, nem ontem nem hoje?

[[v9-20-28]]

^<<v9-20-28,28>>^ Respondeu Jônatas a Saul: Davi me pediu, encarecidamente, que o deixasse ir a Belém.

[[v9-20-29]]

^<<v9-20-29,29>>^ Ele me disse: Peço-te que me deixes ir, porque a nossa família tem um sacrifício na cidade, e um de meus irmãos insiste comigo para que eu vá. Se, pois, agora, achei mercê aos teus olhos, peço-te que me deixes partir, para que veja meus irmãos. Por isso, não veio à mesa do rei.

[[v9-20-30]]

^<<v9-20-30,30>>^ Então, se acendeu a ira de Saul contra Jônatas, e disse-lhe: Filho de mulher perversa e rebelde; não sei eu que elegeste o filho de Jessé, para vergonha tua e para vergonha do recato de tua mãe?

[[v9-20-31]]

^<<v9-20-31,31>>^ Pois, enquanto o filho de Jessé viver sobre a terra, nem tu estarás seguro, nem seguro o teu reino; pelo que manda buscá-lo, agora, porque deve morrer.

[[v9-20-32]]

^<<v9-20-32,32>>^ Então, respondeu Jônatas a Saul, seu pai, e lhe disse: Por que há de ele morrer? Que fez ele?

[[v9-20-33]]

^<<v9-20-33,33>>^ Então, Saul atirou-lhe com a lança para o ferir; com isso entendeu Jônatas que, de fato, seu pai já determinara matar a Davi.

[[v9-20-34]]

^<<v9-20-34,34>>^ Pelo que Jônatas, todo encolerizado, se levantou da mesa e, neste segundo dia da Festa da Lua Nova, não comeu pão, pois ficara muito sentido por causa de Davi, a quem seu pai havia ultrajado.

[[v9-20-35]]

^<<v9-20-35,35>>^ Na manhã seguinte, saiu Jônatas ao campo, no tempo ajustado com Davi, e levou consigo um rapaz.

[[v9-20-36]]

^<<v9-20-36,36>>^ Então, disse ao seu rapaz: Corre a buscar as flechas que eu atirar. Este correu, e ele atirou uma flecha, que fez passar além do rapaz.

[[v9-20-37]]

^<<v9-20-37,37>>^ Chegando o rapaz ao lugar da flecha que Jônatas havia atirado, gritou Jônatas atrás dele e disse: Não está a flecha mais para lá de ti?

[[v9-20-38]]

^<<v9-20-38,38>>^ Tornou Jônatas a gritar: Apressa-te, não te demores. O rapaz de Jônatas apanhou as flechas e voltou ao seu senhor.

[[v9-20-39]]

^<<v9-20-39,39>>^ O rapaz não entendeu coisa alguma; só Jônatas e Davi sabiam deste ajuste.

[[v9-20-40]]

^<<v9-20-40,40>>^ Então, Jônatas deu as suas armas ao rapaz que o acompanhava e disse-lhe: Anda, leva-as à cidade.

[[v9-20-41]]

^<<v9-20-41,41>>^ Indo-se o rapaz, levantou-se Davi do lado do sul e prostrou-se rosto em terra três vezes; e beijaram-se um ao outro e choraram juntos; Davi, porém, muito mais.

[[v9-20-42]]

^<<v9-20-42,42>>^ Disse Jônatas a Davi: Vai-te em paz, porquanto juramos ambos em nome do SENHOR, dizendo: O SENHOR seja para sempre entre mim e ti e entre a minha descendência e a tua.

[[v9-20-43]]

^<<v9-20-43,43>>^ Então, se levantou Davi e se foi; e Jônatas entrou na cidade.

'''

xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[&#60; Capítulo Anterior] | <<v9-20-0,Topo>> | xref:009-1-samuel/009-1-samuel-021.adoc#v9-21-0[Próximo Capítulo &#62;]