include::./index.adoc[]

[[v9-31-0]]
=== 1 Samuel, 31
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-31-1]]

^<<v9-31-1,1>>^ Entretanto, os filisteus pelejaram contra Israel, e, tendo os homens de Israel fugido de diante dos filisteus, caíram feridos no monte Gilboa.

[[v9-31-2]]

^<<v9-31-2,2>>^ Os filisteus apertaram com Saul e seus filhos e mataram Jônatas, Abinadabe e Malquisua, filhos de Saul.

[[v9-31-3]]

^<<v9-31-3,3>>^ Agravou-se a peleja contra Saul; os flecheiros o avistaram, e ele muito os temeu.

[[v9-31-4]]

^<<v9-31-4,4>>^ Então, disse Saul ao seu escudeiro: Arranca a tua espada e atravessa-me com ela, para que, porventura, não venham estes incircuncisos, e me traspassem, e escarneçam de mim. Porém o seu escudeiro não o quis, porque temia muito; então, Saul tomou da espada e se lançou sobre ela.

[[v9-31-5]]

^<<v9-31-5,5>>^ Vendo, pois, o seu escudeiro que Saul já era morto, também ele se lançou sobre a sua espada e morreu com ele.

[[v9-31-6]]

^<<v9-31-6,6>>^ Morreu, pois, Saul, e seus três filhos, e o seu escudeiro, e também todos os seus homens foram mortos naquele dia com ele.

[[v9-31-7]]

^<<v9-31-7,7>>^ Vendo os homens de Israel que estavam deste lado do vale e daquém do Jordão que os homens de Israel fugiram e que Saul e seus filhos estavam mortos, desampararam as cidades e fugiram; e vieram os filisteus e habitaram nelas.

[[v9-31-8]]

^<<v9-31-8,8>>^ Sucedeu, pois, que, vindo os filisteus ao outro dia a despojar os mortos, acharam Saul e seus três filhos caídos no monte Gilboa.

[[v9-31-9]]

^<<v9-31-9,9>>^ Cortaram a cabeça a Saul e o despojaram das suas armas; enviaram mensageiros pela terra dos filisteus, em redor, a levar as boas-novas à casa dos seus ídolos e entre o povo.

[[v9-31-10]]

^<<v9-31-10,10>>^ Puseram as armas de Saul no templo de Astarote e o seu corpo afixaram no muro de Bete-Seã.

[[v9-31-11]]

^<<v9-31-11,11>>^ Então, ouvindo isto os moradores de Jabes-Gileade, o que os filisteus fizeram a Saul,

[[v9-31-12]]

^<<v9-31-12,12>>^ todos os homens valentes se levantaram, e caminharam toda a noite, e tiraram o corpo de Saul e os corpos de seus filhos do muro de Bete-Seã, e, vindo a Jabes, os queimaram.

[[v9-31-13]]

^<<v9-31-13,13>>^ Tomaram-lhes os ossos, e os sepultaram debaixo de um arvoredo, em Jabes, e jejuaram sete dias.

'''

xref:009-1-samuel/009-1-samuel-030.adoc#v9-30-0[&#60; Capítulo Anterior] | <<v9-31-0,Topo>> | xref:010-2-samuel/010-2-samuel-001.adoc#v10-1-0[Próximo Capítulo &#62;]