include::./index.adoc[]

[[v9-16-0]]
=== 1 Samuel, 16
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-16-1]]

^<<v9-16-1,1>>^ Disse o SENHOR a Samuel: Até quando terás pena de Saul, havendo-o eu rejeitado, para que não reine sobre Israel? Enche um chifre de azeite e vem; enviar-te-ei a Jessé, o belemita; porque, dentre os seus filhos, me provi de um rei.

[[v9-16-2]]

^<<v9-16-2,2>>^ Disse Samuel: Como irei eu? Pois Saul o saberá e me matará. Então, disse o SENHOR: Toma contigo um novilho e dize: Vim para sacrificar ao SENHOR.

[[v9-16-3]]

^<<v9-16-3,3>>^ Convidarás Jessé para o sacrifício; eu te mostrarei o que hás de fazer, e ungir-me-ás a quem eu te designar.

[[v9-16-4]]

^<<v9-16-4,4>>^ Fez, pois, Samuel o que dissera o SENHOR e veio a Belém. Saíram-lhe ao encontro os anciãos da cidade, tremendo, e perguntaram: É de paz a tua vinda?

[[v9-16-5]]

^<<v9-16-5,5>>^ Respondeu ele: É de paz; vim sacrificar ao SENHOR. Santificai-vos e vinde comigo ao sacrifício. Santificou ele a Jessé e os seus filhos e os convidou para o sacrifício.

[[v9-16-6]]

^<<v9-16-6,6>>^ Sucedeu que, entrando eles, viu a Eliabe e disse consigo: Certamente, está perante o SENHOR o seu ungido.

[[v9-16-7]]

^<<v9-16-7,7>>^ Porém o SENHOR disse a Samuel: Não atentes para a sua aparência, nem para a sua altura, porque o rejeitei; porque o SENHOR não vê como vê o homem. O homem vê o exterior, porém o SENHOR, o coração.

[[v9-16-8]]

^<<v9-16-8,8>>^ Então, chamou Jessé a Abinadabe e o fez passar diante de Samuel, o qual disse: Nem a este escolheu o SENHOR.

[[v9-16-9]]

^<<v9-16-9,9>>^ Então, Jessé fez passar a Samá, porém Samuel disse: Tampouco a este escolheu o SENHOR.

[[v9-16-10]]

^<<v9-16-10,10>>^ Assim, fez passar Jessé os seus sete filhos diante de Samuel; porém Samuel disse a Jessé: O SENHOR não escolheu estes.

[[v9-16-11]]

^<<v9-16-11,11>>^ Perguntou Samuel a Jessé: Acabaram-se os teus filhos? Ele respondeu: Ainda falta o mais moço, que está apascentando as ovelhas. Disse, pois, Samuel a Jessé: Manda chamá-lo, pois não nos assentaremos à mesa sem que ele venha.

[[v9-16-12]]

^<<v9-16-12,12>>^ Então, mandou chamá-lo e fê-lo entrar. Era ele ruivo, de belos olhos e boa aparência. Disse o SENHOR: Levanta-te e unge-o, pois este é ele.

[[v9-16-13]]

^<<v9-16-13,13>>^ Tomou Samuel o chifre do azeite e o ungiu no meio de seus irmãos; e, daquele dia em diante, o Espírito do SENHOR se apossou de Davi. Então, Samuel se levantou e foi para Ramá.

[[v9-16-14]]

^<<v9-16-14,14>>^ Tendo-se retirado de Saul o Espírito do SENHOR, da parte deste um espírito maligno o atormentava.

[[v9-16-15]]

^<<v9-16-15,15>>^ Então, os servos de Saul lhe disseram: Eis que, agora, um espírito maligno, enviado de Deus, te atormenta.

[[v9-16-16]]

^<<v9-16-16,16>>^ Manda, pois, senhor nosso, que teus servos, que estão em tua presença, busquem um homem que saiba tocar harpa; e será que, quando o espírito maligno, da parte do SENHOR, vier sobre ti, então, ele a dedilhará, e te acharás melhor.

[[v9-16-17]]

^<<v9-16-17,17>>^ Disse Saul aos seus servos: Buscai-me, pois, um homem que saiba tocar bem e trazei-mo.

[[v9-16-18]]

^<<v9-16-18,18>>^ Então, respondeu um dos moços e disse: Conheço um filho de Jessé, o belemita, que sabe tocar e é forte e valente, homem de guerra, sisudo em palavras e de boa aparência; e o SENHOR é com ele.

[[v9-16-19]]

^<<v9-16-19,19>>^ Saul enviou mensageiros a Jessé, dizendo: Envia-me Davi, teu filho, o que está com as ovelhas.

[[v9-16-20]]

^<<v9-16-20,20>>^ Tomou, pois, Jessé um jumento, e o carregou de pão, um odre de vinho e um cabrito, e enviou-os a Saul por intermédio de Davi, seu filho.

[[v9-16-21]]

^<<v9-16-21,21>>^ Assim, Davi foi a Saul e esteve perante ele; este o amou muito e o fez seu escudeiro.

[[v9-16-22]]

^<<v9-16-22,22>>^ Saul mandou dizer a Jessé: Deixa estar Davi perante mim, pois me caiu em graça.

[[v9-16-23]]

^<<v9-16-23,23>>^ E sucedia que, quando o espírito maligno, da parte de Deus, vinha sobre Saul, Davi tomava a harpa e a dedilhava; então, Saul sentia alívio e se achava melhor, e o espírito maligno se retirava dele.

'''

xref:009-1-samuel/009-1-samuel-015.adoc#v9-15-0[&#60; Capítulo Anterior] | <<v9-16-0,Topo>> | xref:009-1-samuel/009-1-samuel-017.adoc#v9-17-0[Próximo Capítulo &#62;]