include::./index.adoc[]

[[v9-5-0]]
=== 1 Samuel, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-5-1]]

^<<v9-5-1,1>>^ Os filisteus tomaram a arca de Deus e a levaram de Ebenézer a Asdode.

[[v9-5-2]]

^<<v9-5-2,2>>^ Tomaram os filisteus a arca de Deus e a meteram na casa de Dagom, junto a este.

[[v9-5-3]]

^<<v9-5-3,3>>^ Levantando-se, porém, de madrugada os de Asdode, no dia seguinte, eis que estava caído Dagom com o rosto em terra, diante da arca do SENHOR; tomaram-no e tornaram a pô-lo no seu lugar.

[[v9-5-4]]

^<<v9-5-4,4>>^ Levantando-se de madrugada no dia seguinte, pela manhã, eis que Dagom jazia caído de bruços diante da arca do SENHOR; a cabeça de Dagom e as duas mãos estavam cortadas sobre o limiar; dele ficara apenas o tronco.

[[v9-5-5]]

^<<v9-5-5,5>>^ Por isso, os sacerdotes de Dagom e todos os que entram no seu templo não lhe pisam o limiar em Asdode, até ao dia de hoje.

[[v9-5-6]]

^<<v9-5-6,6>>^ Porém a mão do SENHOR castigou duramente os de Asdode, e os assolou, e os feriu de tumores, tanto em Asdode como no seu território.

[[v9-5-7]]

^<<v9-5-7,7>>^ Vendo os homens de Asdode que assim era, disseram: Não fique conosco a arca do Deus de Israel; pois a sua mão é dura sobre nós e sobre Dagom, nosso deus.

[[v9-5-8]]

^<<v9-5-8,8>>^ Pelo que enviaram mensageiros, e congregaram a si todos os príncipes dos filisteus, e disseram: Que faremos da arca do Deus de Israel? Responderam: Seja levada a arca do Deus de Israel até Gate e, depois, de cidade em cidade. E a levaram até Gate.

[[v9-5-9]]

^<<v9-5-9,9>>^ Depois de a terem levado, a mão do SENHOR foi contra aquela cidade, com mui grande terror; pois feriu os homens daquela cidade, desde o pequeno até ao grande; e lhes nasceram tumores.

[[v9-5-10]]

^<<v9-5-10,10>>^ Então, enviaram a arca de Deus a Ecrom. Sucedeu, porém, que, em lá chegando, os ecronitas exclamaram, dizendo: Transportaram até nós a arca do Deus de Israel, para nos matarem, a nós e ao nosso povo.

[[v9-5-11]]

^<<v9-5-11,11>>^ Então, enviaram mensageiros, e congregaram a todos os príncipes dos filisteus, e disseram: Devolvei a arca do Deus de Israel, e torne para o seu lugar, para que não mate nem a nós nem ao nosso povo. Porque havia terror de morte em toda a cidade, e a mão de Deus castigara duramente ali.

[[v9-5-12]]

^<<v9-5-12,12>>^ Os homens que não morriam eram atingidos com os tumores; e o clamor da cidade subiu até ao céu.

'''

xref:009-1-samuel/009-1-samuel-004.adoc#v9-4-0[&#60; Capítulo Anterior] | <<v9-5-0,Topo>> | xref:009-1-samuel/009-1-samuel-006.adoc#v9-6-0[Próximo Capítulo &#62;]