include::./index.adoc[]

[[v9-27-0]]
=== 1 Samuel, 27
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-27-1]]

^<<v9-27-1,1>>^ Disse, porém, Davi consigo mesmo: Pode ser que algum dia venha eu a perecer nas mãos de Saul; nada há, pois, melhor para mim do que fugir para a terra dos filisteus; para que Saul perca de todo as esperanças e deixe de perseguir-me por todos os limites de Israel; assim, me livrarei da sua mão.

[[v9-27-2]]

^<<v9-27-2,2>>^ Dispôs-se Davi e, com os seiscentos homens que com ele estavam, passou a Aquis, filho de Maoque, rei de Gate.

[[v9-27-3]]

^<<v9-27-3,3>>^ Habitou Davi com Aquis em Gate, ele e os seus homens, cada um com a sua família; Davi, com ambas as suas mulheres, Ainoã, a jezreelita, e Abigail, a viúva de Nabal, o carmelita.

[[v9-27-4]]

^<<v9-27-4,4>>^ Avisado Saul de que Davi tinha fugido para Gate, desistiu de o perseguir.

[[v9-27-5]]

^<<v9-27-5,5>>^ Disse Davi a Aquis: Se achei mercê na tua presença, dá-me lugar numa das cidades da terra, para que ali habite; por que há de habitar o teu servo contigo na cidade real?

[[v9-27-6]]

^<<v9-27-6,6>>^ Então, lhe deu Aquis, naquele dia, a cidade de Ziclague. Pelo que Ziclague pertence aos reis de Judá, até ao dia de hoje.

[[v9-27-7]]

^<<v9-27-7,7>>^ E todo o tempo que Davi permaneceu na terra dos filisteus foi um ano e quatro meses.

[[v9-27-8]]

^<<v9-27-8,8>>^ Subia Davi com os seus homens, e davam contra os gesuritas, os gersitas e os amalequitas; porque eram estes os moradores da terra desde Telã, na direção de Sur, até à terra do Egito.

[[v9-27-9]]

^<<v9-27-9,9>>^ Davi feria aquela terra, e não deixava com vida nem homem nem mulher, e tomava as ovelhas, e os bois, e os jumentos, e os camelos, e as vestes; voltava e vinha a Aquis.

[[v9-27-10]]

^<<v9-27-10,10>>^ E perguntando Aquis: Contra quem deste hoje? Davi respondia: Contra o Sul de Judá, e o Sul dos jerameelitas, e o Sul dos queneus.

[[v9-27-11]]

^<<v9-27-11,11>>^ Davi não deixava com vida nem homem nem mulher, para os trazer a Gate, pois dizia: Para que não nos denunciem, dizendo: Assim Davi o fazia. Este era o seu proceder por todos os dias que habitou na terra dos filisteus.

[[v9-27-12]]

^<<v9-27-12,12>>^ Aquis confiava em Davi, dizendo: Fez-se ele, por certo, aborrecível para com o seu povo em Israel; pelo que me será por servo para sempre.

'''

xref:009-1-samuel/009-1-samuel-026.adoc#v9-26-0[&#60; Capítulo Anterior] | <<v9-27-0,Topo>> | xref:009-1-samuel/009-1-samuel-028.adoc#v9-28-0[Próximo Capítulo &#62;]