include::./index.adoc[]

[[v9-13-0]]
=== 1 Samuel, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-13-1]]

^<<v9-13-1,1>>^ Um ano reinara Saul em Israel. No segundo ano de seu reinado sobre o povo,

[[v9-13-2]]

^<<v9-13-2,2>>^ escolheu para si três mil homens de Israel; estavam com Saul dois mil em Micmás e na região montanhosa de Betel, e mil estavam com Jônatas em Gibeá de Benjamim; e despediu o resto do povo, cada um para sua casa.

[[v9-13-3]]

^<<v9-13-3,3>>^ Jônatas derrotou a guarnição dos filisteus que estava em Gibeá, o que os filisteus ouviram; pelo que Saul fez tocar a trombeta por toda a terra, dizendo: Ouçam isso os hebreus.

[[v9-13-4]]

^<<v9-13-4,4>>^ Todo o Israel ouviu dizer: Saul derrotou a guarnição dos filisteus, e também Israel se fez odioso aos filisteus. Então, o povo foi convocado para junto de Saul, em Gilgal.

[[v9-13-5]]

^<<v9-13-5,5>>^ Reuniram-se os filisteus para pelejar contra Israel: trinta mil carros, e seis mil cavaleiros, e povo em multidão como a areia que está à beira-mar; e subiram e se acamparam em Micmás, ao oriente de Bete-Áven.

[[v9-13-6]]

^<<v9-13-6,6>>^ Vendo, pois, os homens de Israel que estavam em apuros (porque o povo estava apertado), esconderam-se pelas cavernas, e pelos buracos, e pelos penhascos, e pelos túmulos, e pelas cisternas.

[[v9-13-7]]

^<<v9-13-7,7>>^ Também alguns dos hebreus passaram o Jordão para a terra de Gade e Gileade; e o povo que permaneceu com Saul, estando este ainda em Gilgal, se encheu de temor.

[[v9-13-8]]

^<<v9-13-8,8>>^ Esperou Saul sete dias, segundo o prazo determinado por Samuel; não vindo, porém, Samuel a Gilgal, o povo se foi espalhando dali.

[[v9-13-9]]

^<<v9-13-9,9>>^ Então, disse Saul: Trazei-me aqui o holocausto e ofertas pacíficas. E ofereceu o holocausto.

[[v9-13-10]]

^<<v9-13-10,10>>^ Mal acabara ele de oferecer o holocausto, eis que chega Samuel; Saul lhe saiu ao encontro, para o saudar.

[[v9-13-11]]

^<<v9-13-11,11>>^ Samuel perguntou: Que fizeste? Respondeu Saul: Vendo que o povo se ia espalhando daqui, e que tu não vinhas nos dias aprazados, e que os filisteus já se tinham ajuntado em Micmás,

[[v9-13-12]]

^<<v9-13-12,12>>^ eu disse comigo: Agora, descerão os filisteus contra mim a Gilgal, e ainda não obtive a benevolência do SENHOR; e, forçado pelas circunstâncias, ofereci holocaustos.

[[v9-13-13]]

^<<v9-13-13,13>>^ Então, disse Samuel a Saul: Procedeste nesciamente em não guardar o mandamento que o SENHOR, teu Deus, te ordenou; pois teria, agora, o SENHOR confirmado o teu reino sobre Israel para sempre.

[[v9-13-14]]

^<<v9-13-14,14>>^ Já agora não subsistirá o teu reino. O SENHOR buscou para si um homem que lhe agrada e já lhe ordenou que seja príncipe sobre o seu povo, porquanto não guardaste o que o SENHOR te ordenou.

[[v9-13-15]]

^<<v9-13-15,15>>^ Então, se levantou Samuel e subiu de Gilgal a Gibeá de Benjamim. Logo, Saul contou o povo que se achava com ele, cerca de seiscentos homens.

[[v9-13-16]]

^<<v9-13-16,16>>^ Saul, e Jônatas, seu filho, e o povo que se achava com eles ficaram em Geba de Benjamim; porém os filisteus se acamparam em Micmás.

[[v9-13-17]]

^<<v9-13-17,17>>^ Os saqueadores saíram do campo dos filisteus em três tropas; uma delas tomou o caminho de Ofra à terra de Sual;

[[v9-13-18]]

^<<v9-13-18,18>>^ outra tomou o caminho de Bete-Horom; e a terceira, o caminho a cavaleiro do vale de Zeboim, na direção do deserto.

[[v9-13-19]]

^<<v9-13-19,19>>^ Ora, em toda a terra de Israel nem um ferreiro se achava, porque os filisteus tinham dito: Para que os hebreus não façam espada, nem lança.

[[v9-13-20]]

^<<v9-13-20,20>>^ Pelo que todo o Israel tinha de descer aos filisteus para amolar a relha do seu arado, e a sua enxada, e o seu machado, e a sua foice.

[[v9-13-21]]

^<<v9-13-21,21>>^ Os filisteus cobravam dos israelitas dois terços de um siclo para amolar os fios das relhas e das enxadas e um terço de um siclo para amolar machados e aguilhadas.

[[v9-13-22]]

^<<v9-13-22,22>>^ Sucedeu que, no dia da peleja, não se achou nem espada, nem lança na mão de nenhum do povo que estava com Saul e com Jônatas; porém se acharam com Saul e com Jônatas, seu filho.

[[v9-13-23]]

^<<v9-13-23,23>>^ Saiu a guarnição dos filisteus ao desfiladeiro de Micmás.

'''

xref:009-1-samuel/009-1-samuel-012.adoc#v9-12-0[&#60; Capítulo Anterior] | <<v9-13-0,Topo>> | xref:009-1-samuel/009-1-samuel-014.adoc#v9-14-0[Próximo Capítulo &#62;]