include::./index.adoc[]

[[v9-7-0]]
=== 1 Samuel, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-7-1]]

^<<v9-7-1,1>>^ Então, vieram os homens de Quiriate-Jearim e levaram a arca do SENHOR à casa de Abinadabe, no outeiro; e consagraram Eleazar, seu filho, para que guardasse a arca do SENHOR.

[[v9-7-2]]

^<<v9-7-2,2>>^ Sucedeu que, desde aquele dia, a arca ficou em Quiriate-Jearim, e tantos dias se passaram, que chegaram a vinte anos; e toda a casa de Israel dirigia lamentações ao SENHOR.

[[v9-7-3]]

^<<v9-7-3,3>>^ Falou Samuel a toda a casa de Israel, dizendo: Se é de todo o vosso coração que voltais ao SENHOR, tirai dentre vós os deuses estranhos e os astarotes, e preparai o coração ao SENHOR, e servi a ele só, e ele vos livrará das mãos dos filisteus.

[[v9-7-4]]

^<<v9-7-4,4>>^ Então, os filhos de Israel tiraram dentre si os baalins e os astarotes e serviram só ao SENHOR.

[[v9-7-5]]

^<<v9-7-5,5>>^ Disse mais Samuel: Congregai todo o Israel em Mispa, e orarei por vós ao SENHOR.

[[v9-7-6]]

^<<v9-7-6,6>>^ Congregaram-se em Mispa, tiraram água e a derramaram perante o SENHOR; jejuaram aquele dia e ali disseram: Pecamos contra o SENHOR. E Samuel julgou os filhos de Israel em Mispa.

[[v9-7-7]]

^<<v9-7-7,7>>^ Quando, pois, os filisteus ouviram que os filhos de Israel estavam congregados em Mispa, subiram os príncipes dos filisteus contra Israel; o que ouvindo os filhos de Israel, tiveram medo dos filisteus.

[[v9-7-8]]

^<<v9-7-8,8>>^ Então, disseram os filhos de Israel a Samuel: Não cesses de clamar ao SENHOR, nosso Deus, por nós, para que nos livre da mão dos filisteus.

[[v9-7-9]]

^<<v9-7-9,9>>^ Tomou, pois, Samuel um cordeiro que ainda mamava e o sacrificou em holocausto ao SENHOR; clamou Samuel ao SENHOR por Israel, e o SENHOR lhe respondeu.

[[v9-7-10]]

^<<v9-7-10,10>>^ Enquanto Samuel oferecia o holocausto, os filisteus chegaram à peleja contra Israel; mas trovejou o SENHOR aquele dia com grande estampido sobre os filisteus e os aterrou de tal modo, que foram derrotados diante dos filhos de Israel.

[[v9-7-11]]

^<<v9-7-11,11>>^ Saindo de Mispa os homens de Israel, perseguiram os filisteus e os derrotaram até abaixo de Bete-Car.

[[v9-7-12]]

^<<v9-7-12,12>>^ Tomou, então, Samuel uma pedra, e a pôs entre Mispa e Sem, e lhe chamou Ebenézer, e disse: Até aqui nos ajudou o SENHOR.

[[v9-7-13]]

^<<v9-7-13,13>>^ Assim, os filisteus foram abatidos e nunca mais vieram ao território de Israel, porquanto foi a mão do SENHOR contra eles todos os dias de Samuel.

[[v9-7-14]]

^<<v9-7-14,14>>^ As cidades que os filisteus haviam tomado a Israel foram-lhe restituídas, desde Ecrom até Gate; e até os territórios delas arrebatou Israel das mãos dos filisteus. E houve paz entre Israel e os amorreus.

[[v9-7-15]]

^<<v9-7-15,15>>^ E julgou Samuel todos os dias de sua vida a Israel.

[[v9-7-16]]

^<<v9-7-16,16>>^ De ano em ano, fazia uma volta, passando por Betel, Gilgal e Mispa; e julgava a Israel em todos esses lugares.

[[v9-7-17]]

^<<v9-7-17,17>>^ Porém voltava a Ramá, porque sua casa estava ali, onde julgava a Israel e onde edificou um altar ao SENHOR.

'''

xref:009-1-samuel/009-1-samuel-006.adoc#v9-6-0[&#60; Capítulo Anterior] | <<v9-7-0,Topo>> | xref:009-1-samuel/009-1-samuel-008.adoc#v9-8-0[Próximo Capítulo &#62;]