include::./index.adoc[]

[[v9-18-0]]
=== 1 Samuel, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-18-1]]

^<<v9-18-1,1>>^ Sucedeu que, acabando Davi de falar com Saul, a alma de Jônatas se ligou com a de Davi; e Jônatas o amou como à sua própria alma.

[[v9-18-2]]

^<<v9-18-2,2>>^ Saul, naquele dia, o tomou e não lhe permitiu que tornasse para casa de seu pai.

[[v9-18-3]]

^<<v9-18-3,3>>^ Jônatas e Davi fizeram aliança; porque Jônatas o amava como à sua própria alma.

[[v9-18-4]]

^<<v9-18-4,4>>^ Despojou-se Jônatas da capa que vestia e a deu a Davi, como também a armadura, inclusive a espada, o arco e o cinto.

[[v9-18-5]]

^<<v9-18-5,5>>^ Saía Davi aonde quer que Saul o enviava e se conduzia com prudência; de modo que Saul o pôs sobre tropas do seu exército, e era ele benquisto de todo o povo e até dos próprios servos de Saul.

[[v9-18-6]]

^<<v9-18-6,6>>^ Sucedeu, porém, que, vindo Saul e seu exército, e voltando também Davi de ferir os filisteus, as mulheres de todas as cidades de Israel saíram ao encontro do rei Saul, cantando e dançando, com tambores, com júbilo e com instrumentos de música.

[[v9-18-7]]

^<<v9-18-7,7>>^ As mulheres se alegravam e, cantando alternadamente, diziam: Saul feriu os seus milhares, porém Davi, os seus dez milhares.

[[v9-18-8]]

^<<v9-18-8,8>>^ Então, Saul se indignou muito, pois estas palavras lhe desagradaram em extremo; e disse: Dez milhares deram elas a Davi, e a mim somente milhares; na verdade, que lhe falta, senão o reino?

[[v9-18-9]]

^<<v9-18-9,9>>^ Daquele dia em diante, Saul não via a Davi com bons olhos.

[[v9-18-10]]

^<<v9-18-10,10>>^ No dia seguinte, um espírito maligno, da parte de Deus, se apossou de Saul, que teve uma crise de raiva em casa; e Davi, como nos outros dias, dedilhava a harpa; Saul, porém, trazia na mão uma lança,

[[v9-18-11]]

^<<v9-18-11,11>>^ que arrojou, dizendo: Encravarei a Davi na parede. Porém Davi se desviou dele por duas vezes.

[[v9-18-12]]

^<<v9-18-12,12>>^ Saul temia a Davi, porque o SENHOR era com este e se tinha retirado de Saul.

[[v9-18-13]]

^<<v9-18-13,13>>^ Pelo que Saul o afastou de si e o pôs por chefe de mil; ele fazia saídas e entradas militares diante do povo.

[[v9-18-14]]

^<<v9-18-14,14>>^ Davi lograva bom êxito em todos os seus empreendimentos, pois o SENHOR era com ele.

[[v9-18-15]]

^<<v9-18-15,15>>^ Então, vendo Saul que Davi lograva bom êxito, tinha medo dele.

[[v9-18-16]]

^<<v9-18-16,16>>^ Porém todo o Israel e Judá amavam Davi, porquanto fazia saídas e entradas militares diante deles.

[[v9-18-17]]

^<<v9-18-17,17>>^ Disse Saul a Davi: Eis aqui Merabe, minha filha mais velha, que te darei por mulher; sê-me somente filho valente e guerreia as guerras do SENHOR; porque Saul dizia consigo: Não seja contra ele a minha mão, e sim a dos filisteus.

[[v9-18-18]]

^<<v9-18-18,18>>^ Respondeu Davi a Saul: Quem sou eu, e qual é a minha vida e a família de meu pai em Israel, para vir a ser eu genro do rei?

[[v9-18-19]]

^<<v9-18-19,19>>^ Sucedeu, porém, que, ao tempo em que Merabe, filha de Saul, devia ser dada a Davi, foi dada por mulher a Adriel, meolatita.

[[v9-18-20]]

^<<v9-18-20,20>>^ Mas Mical, a outra filha de Saul, amava a Davi. Contaram-no a Saul, e isso lhe agradou.

[[v9-18-21]]

^<<v9-18-21,21>>^ Disse Saul: Eu lha darei, para que ela lhe sirva de laço e para que a mão dos filisteus venha a ser contra ele. Pelo que Saul disse a Davi: Com esta segunda serás, hoje, meu genro.

[[v9-18-22]]

^<<v9-18-22,22>>^ Ordenou Saul aos seus servos: Falai confidencialmente a Davi, dizendo: Eis que o rei tem afeição por ti, e todos os seus servos te amam; consente, pois, em ser genro do rei.

[[v9-18-23]]

^<<v9-18-23,23>>^ Os servos de Saul falaram estas palavras a Davi, o qual respondeu: Parece-vos coisa de somenos ser genro do rei, sendo eu homem pobre e de humilde condição?

[[v9-18-24]]

^<<v9-18-24,24>>^ Os servos de Saul lhe referiram isto, dizendo: Tais foram as palavras que falou Davi.

[[v9-18-25]]

^<<v9-18-25,25>>^ Então, disse Saul: Assim direis a Davi: O rei não deseja dote algum, mas cem prepúcios de filisteus, para tomar vingança dos inimigos do rei. Porquanto Saul tentava fazer cair a Davi pelas mãos dos filisteus.

[[v9-18-26]]

^<<v9-18-26,26>>^ Tendo os servos de Saul referido estas palavras a Davi, agradou-se este de que viesse a ser genro do rei. Antes de vencido o prazo,

[[v9-18-27]]

^<<v9-18-27,27>>^ dispôs-se Davi e partiu com os seus homens, e feriram dentre os filisteus duzentos homens; trouxe os seus prepúcios e os entregou todos ao rei, para que lhe fosse genro. Então, Saul lhe deu por mulher a sua filha Mical.

[[v9-18-28]]

^<<v9-18-28,28>>^ Viu Saul e reconheceu que o SENHOR era com Davi; e Mical, filha de Saul, o amava.

[[v9-18-29]]

^<<v9-18-29,29>>^ Então, Saul temeu ainda mais a Davi e continuamente foi seu inimigo.

[[v9-18-30]]

^<<v9-18-30,30>>^ Cada vez que os príncipes dos filisteus saíam à batalha, Davi lograva mais êxito do que todos os servos de Saul; portanto, o seu nome se tornou muito estimado.

'''

xref:009-1-samuel/009-1-samuel-017.adoc#v9-17-0[&#60; Capítulo Anterior] | <<v9-18-0,Topo>> | xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[Próximo Capítulo &#62;]