include::./index.adoc[]

[[v9-22-0]]
=== 1 Samuel, 22
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-22-1]]

^<<v9-22-1,1>>^ Davi retirou-se dali e se refugiou na caverna de Adulão; quando ouviram isso seus irmãos e toda a casa de seu pai, desceram ali para ter com ele.

[[v9-22-2]]

^<<v9-22-2,2>>^ Ajuntaram-se a ele todos os homens que se achavam em aperto, e todo homem endividado, e todos os amargurados de espírito, e ele se fez chefe deles; e eram com ele uns quatrocentos homens.

[[v9-22-3]]

^<<v9-22-3,3>>^ Dali passou Davi a Mispa de Moabe e disse ao seu rei: Deixa estar meu pai e minha mãe convosco, até que eu saiba o que Deus há de fazer de mim.

[[v9-22-4]]

^<<v9-22-4,4>>^ Trouxe-os perante o rei de Moabe, e com este moraram por todo o tempo que Davi esteve neste lugar seguro.

[[v9-22-5]]

^<<v9-22-5,5>>^ Porém o profeta Gade disse a Davi: Não fiques neste lugar seguro; vai e entra na terra de Judá. Então, Davi saiu e foi para o bosque de Herete.

[[v9-22-6]]

^<<v9-22-6,6>>^ Ouviu Saul que Davi e os homens que o acompanhavam foram descobertos. Achando-se Saul em Gibeá, debaixo de um arvoredo, numa colina, tendo na mão a sua lança, e todos os seus servos com ele,

[[v9-22-7]]

^<<v9-22-7,7>>^ disse a todos estes: Ouvi, peço-vos, filhos de Benjamim, dar-vos-á também o filho de Jessé, a todos vós, terras e vinhas e vos fará a todos chefes de milhares e chefes de centenas,

[[v9-22-8]]

^<<v9-22-8,8>>^ para que todos tenhais conspirado contra mim? E ninguém houve que me desse aviso de que meu filho fez aliança com o filho de Jessé; e nenhum dentre vós há que se doa por mim e me participe que meu filho contra mim instigou a meu servo, para me armar ciladas, como se vê neste dia.

[[v9-22-9]]

^<<v9-22-9,9>>^ Então, respondeu Doegue, o edomita, que também estava com os servos de Saul, e disse: Vi o filho de Jessé chegar a Nobe, a Aimeleque, filho de Aitube,

[[v9-22-10]]

^<<v9-22-10,10>>^ e como Aimeleque, a pedido dele, consultou o SENHOR, e lhe fez provisões, e lhe deu a espada de Golias, o filisteu.

[[v9-22-11]]

^<<v9-22-11,11>>^ Então, o rei mandou chamar Aimeleque, sacerdote, filho de Aitube, e toda a casa de seu pai, a saber, os sacerdotes que estavam em Nobe; todos eles vieram ao rei.

[[v9-22-12]]

^<<v9-22-12,12>>^ Disse Saul: Ouve, peço-te, filho de Aitube! Este respondeu: Eis-me aqui, meu senhor!

[[v9-22-13]]

^<<v9-22-13,13>>^ Então, lhe disse Saul: Por que conspirastes contra mim, tu e o filho de Jessé? Pois lhe deste pão e espada e consultaste a favor dele a Deus, para que se levantasse contra mim e me armasse ciladas, como hoje se vê.

[[v9-22-14]]

^<<v9-22-14,14>>^ Respondeu Aimeleque ao rei e disse: E quem, entre todos os teus servos, há tão fiel como Davi, o genro do rei, chefe da tua guarda pessoal e honrado na tua casa?

[[v9-22-15]]

^<<v9-22-15,15>>^ Acaso, é de hoje que consulto a Deus em seu favor? Não! Jamais impute o rei coisa nenhuma a seu servo, nem a toda a casa de meu pai, pois o teu servo de nada soube de tudo isso, nem muito nem pouco.

[[v9-22-16]]

^<<v9-22-16,16>>^ Respondeu o rei: Aimeleque, morrerás, tu e toda a casa de teu pai.

[[v9-22-17]]

^<<v9-22-17,17>>^ Disse o rei aos da guarda, que estavam com ele: Volvei e matai os sacerdotes do SENHOR, porque também estão de mãos dadas com Davi e porque souberam que fugiu e não mo fizeram saber. Porém os servos do rei não quiseram estender as mãos contra os sacerdotes do SENHOR.

[[v9-22-18]]

^<<v9-22-18,18>>^ Então, disse o rei a Doegue: Volve-te e arremete contra os sacerdotes. Então, se virou Doegue, o edomita, e arremeteu contra os sacerdotes, e matou, naquele dia, oitenta e cinco homens que vestiam estola sacerdotal de linho.

[[v9-22-19]]

^<<v9-22-19,19>>^ Também a Nobe, cidade destes sacerdotes, passou a fio de espada: homens, e mulheres, e meninos, e crianças de peito, e bois, e jumentos, e ovelhas.

[[v9-22-20]]

^<<v9-22-20,20>>^ Porém dos filhos de Aimeleque, filho de Aitube, um só, cujo nome era Abiatar, salvou-se e fugiu para Davi;

[[v9-22-21]]

^<<v9-22-21,21>>^ e lhe anunciou que Saul tinha matado os sacerdotes do SENHOR.

[[v9-22-22]]

^<<v9-22-22,22>>^ Então, Davi disse a Abiatar: Bem sabia eu, naquele dia, que, estando ali Doegue, o edomita, não deixaria de o dizer a Saul. Fui a causa da morte de todas as pessoas da casa de teu pai.

[[v9-22-23]]

^<<v9-22-23,23>>^ Fica comigo, não temas, porque quem procura a minha morte procura também a tua; estarás a salvo comigo.

'''

xref:009-1-samuel/009-1-samuel-021.adoc#v9-21-0[&#60; Capítulo Anterior] | <<v9-22-0,Topo>> | xref:009-1-samuel/009-1-samuel-023.adoc#v9-23-0[Próximo Capítulo &#62;]