include::./index.adoc[]

[[v9-25-0]]
=== 1 Samuel, 25
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-25-1]]

^<<v9-25-1,1>>^ Faleceu Samuel; todos os filhos de Israel se ajuntaram, e o prantearam, e o sepultaram na sua casa, em Ramá. Davi se levantou e desceu ao deserto de Parã.

[[v9-25-2]]

^<<v9-25-2,2>>^ Havia um homem, em Maom, que tinha as suas possessões no Carmelo; homem abastado, tinha três mil ovelhas e mil cabras e estava tosquiando as suas ovelhas no Carmelo.

[[v9-25-3]]

^<<v9-25-3,3>>^ Nabal era o nome deste homem, e Abigail, o de sua mulher; esta era sensata e formosa, porém o homem era duro e maligno em todo o seu trato. Era ele da casa de Calebe.

[[v9-25-4]]

^<<v9-25-4,4>>^ Ouvindo Davi, no deserto, que Nabal tosquiava as suas ovelhas,

[[v9-25-5]]

^<<v9-25-5,5>>^ enviou dez moços e lhes disse: Subi ao Carmelo, ide a Nabal, perguntai-lhe, em meu nome, como está.

[[v9-25-6]]

^<<v9-25-6,6>>^ Direis àquele próspero: Paz seja contigo, e tenha paz a tua casa, e tudo o que possuis tenha paz!

[[v9-25-7]]

^<<v9-25-7,7>>^ Tenho ouvido que tens tosquiadores. Os teus pastores estiveram conosco; nenhum agravo lhes fizemos, e de nenhuma coisa sentiram falta todos os dias que estiveram no Carmelo.

[[v9-25-8]]

^<<v9-25-8,8>>^ Pergunta aos teus moços, e eles to dirão; achem mercê, pois, os meus moços na tua presença, porque viemos em boa hora; dá, pois, a teus servos e a Davi, teu filho, qualquer coisa que tiveres à mão.

[[v9-25-9]]

^<<v9-25-9,9>>^ Chegando, pois, os moços de Davi e tendo falado a Nabal todas essas palavras em nome de Davi, aguardaram.

[[v9-25-10]]

^<<v9-25-10,10>>^ Respondeu Nabal aos moços de Davi e disse: Quem é Davi, e quem é o filho de Jessé? Muitos são, hoje em dia, os servos que fogem ao seu senhor.

[[v9-25-11]]

^<<v9-25-11,11>>^ Tomaria eu, pois, o meu pão, e a minha água, e a carne das minhas reses que degolei para os meus tosquiadores e o daria a homens que eu não sei donde vêm?

[[v9-25-12]]

^<<v9-25-12,12>>^ Então, os moços de Davi puseram-se a caminho, voltaram e, tendo chegado, lhe contaram tudo, segundo todas estas palavras.

[[v9-25-13]]

^<<v9-25-13,13>>^ Pelo que disse Davi aos seus homens: Cada um cinja a sua espada. E cada um cingiu a sua espada, e também Davi, a sua; subiram após Davi uns quatrocentos homens, e duzentos ficaram com a bagagem.

[[v9-25-14]]

^<<v9-25-14,14>>^ Nesse meio tempo, um dentre os moços de Nabal o anunciou a Abigail, mulher deste, dizendo: Davi enviou do deserto mensageiros a saudar a nosso senhor; porém este disparatou com eles.

[[v9-25-15]]

^<<v9-25-15,15>>^ Aqueles homens, porém, nos têm sido muito bons, e nunca fomos agravados por eles e de nenhuma coisa sentimos falta em todos os dias de nosso trato com eles, quando estávamos no campo.

[[v9-25-16]]

^<<v9-25-16,16>>^ De muro em redor nos serviram, tanto de dia como de noite, todos os dias que estivemos com eles apascentando as ovelhas.

[[v9-25-17]]

^<<v9-25-17,17>>^ Agora, pois, considera e vê o que hás de fazer, porque já o mal está, de fato, determinado contra o nosso senhor e contra toda a sua casa; e ele é filho de Belial, e não há quem lhe possa falar.

[[v9-25-18]]

^<<v9-25-18,18>>^ Então, Abigail tomou, a toda pressa, duzentos pães, dois odres de vinho, cinco ovelhas preparadas, cinco medidas de trigo tostado, cem cachos de passas e duzentas pastas de figos, e os pôs sobre jumentos,

[[v9-25-19]]

^<<v9-25-19,19>>^ e disse aos seus moços: Ide adiante de mim, pois vos seguirei de perto. Porém nada disse ela a seu marido Nabal.

[[v9-25-20]]

^<<v9-25-20,20>>^ Enquanto ela, cavalgando um jumento, descia, encoberta pelo monte, Davi e seus homens também desciam, e ela se encontrou com eles.

[[v9-25-21]]

^<<v9-25-21,21>>^ Ora, Davi dissera: Com efeito, de nada me serviu ter guardado tudo quanto este possui no deserto, e de nada sentiu falta de tudo quanto lhe pertence; ele me pagou mal por bem.

[[v9-25-22]]

^<<v9-25-22,22>>^ Faça Deus o que lhe aprouver aos inimigos de Davi, se eu deixar, ao amanhecer, um só do sexo masculino dentre os seus.

[[v9-25-23]]

^<<v9-25-23,23>>^ Vendo, pois, Abigail a Davi, apressou-se, desceu do jumento e prostrou-se sobre o rosto diante de Davi, inclinando-se até à terra.

[[v9-25-24]]

^<<v9-25-24,24>>^ Lançou-se-lhe aos pés e disse: Ah! Senhor meu, caia a culpa sobre mim; permite falar a tua serva contigo e ouve as palavras da tua serva.

[[v9-25-25]]

^<<v9-25-25,25>>^ Não se importe o meu senhor com este homem de Belial, a saber, com Nabal; porque o que significa o seu nome ele é. Nabal é o seu nome, e a loucura está com ele; eu, porém, tua serva, não vi os moços de meu senhor, que enviaste.

[[v9-25-26]]

^<<v9-25-26,26>>^ Agora, pois, meu senhor, tão certo como vive o SENHOR e a tua alma, foste pelo SENHOR impedido de derramar sangue e de vingar-te por tuas próprias mãos. Como Nabal, sejam os teus inimigos e os que procuram fazer mal ao meu senhor.

[[v9-25-27]]

^<<v9-25-27,27>>^ Este é o presente que trouxe a tua serva a meu senhor; seja ele dado aos moços que seguem ao meu senhor.

[[v9-25-28]]

^<<v9-25-28,28>>^ Perdoa a transgressão da tua serva; pois, de fato, o SENHOR te fará casa firme, porque pelejas as batalhas do SENHOR, e não se ache mal em ti por todos os teus dias.

[[v9-25-29]]

^<<v9-25-29,29>>^ Se algum homem se levantar para te perseguir e buscar a tua vida, então, a tua vida será atada no feixe dos que vivem com o SENHOR, teu Deus; porém a vida de teus inimigos, este a arrojará como se a atirasse da cavidade de uma funda.

[[v9-25-30]]

^<<v9-25-30,30>>^ E há de ser que, usando o SENHOR contigo segundo todo o bem que tem dito a teu respeito e te houver estabelecido príncipe sobre Israel,

[[v9-25-31]]

^<<v9-25-31,31>>^ então, meu senhor, não te será por tropeço, nem por pesar ao coração o sangue que, sem causa, vieres a derramar e o te haveres vingado com as tuas próprias mãos; quando o SENHOR te houver feito o bem, lembrar-te-ás da tua serva.

[[v9-25-32]]

^<<v9-25-32,32>>^ Então, Davi disse a Abigail: Bendito o SENHOR, Deus de Israel, que, hoje, te enviou ao meu encontro.

[[v9-25-33]]

^<<v9-25-33,33>>^ Bendita seja a tua prudência, e bendita sejas tu mesma, que hoje me tolheste de derramar sangue e de que por minha própria mão me vingasse.

[[v9-25-34]]

^<<v9-25-34,34>>^ Porque, tão certo como vive o SENHOR, Deus de Israel, que me impediu de que te fizesse mal, se tu não te apressaras e me não vieras ao encontro, não teria ficado a Nabal, até ao amanhecer, nem um sequer do sexo masculino.

[[v9-25-35]]

^<<v9-25-35,35>>^ Então, Davi recebeu da mão de Abigail o que esta lhe havia trazido e lhe disse: Sobe em paz à tua casa; bem vês que ouvi a tua petição e a ela atendi.

[[v9-25-36]]

^<<v9-25-36,36>>^ Voltou Abigail a Nabal. Eis que ele fazia em casa um banquete, como banquete de rei; o seu coração estava alegre, e ele, já mui embriagado, pelo que não lhe referiu ela coisa alguma, nem pouco nem muito, até ao amanhecer.

[[v9-25-37]]

^<<v9-25-37,37>>^ Pela manhã, estando Nabal já livre do vinho, sua mulher lhe deu a entender aquelas coisas; e se amorteceu nele o coração, e ficou ele como pedra.

[[v9-25-38]]

^<<v9-25-38,38>>^ Passados uns dez dias, feriu o SENHOR a Nabal, e este morreu.

[[v9-25-39]]

^<<v9-25-39,39>>^ Ouvindo Davi que Nabal morrera, disse: Bendito seja o SENHOR, que pleiteou a causa da afronta que recebi de Nabal e me deteve de fazer o mal, fazendo o SENHOR cair o mal de Nabal sobre a sua cabeça. Mandou Davi falar a Abigail que desejava tomá-la por mulher.

[[v9-25-40]]

^<<v9-25-40,40>>^ Tendo ido os servos de Davi a Abigail, no Carmelo, lhe disseram: Davi nos mandou a ti, para te levar por sua mulher.

[[v9-25-41]]

^<<v9-25-41,41>>^ Então, ela se levantou, e se inclinou com o rosto em terra, e disse: Eis que a tua serva é criada para lavar os pés aos criados de meu senhor.

[[v9-25-42]]

^<<v9-25-42,42>>^ Abigail se apressou e, dispondo-se, cavalgou um jumento com as cinco moças que a assistiam; e ela seguiu os mensageiros de Davi, que a recebeu por mulher.

[[v9-25-43]]

^<<v9-25-43,43>>^ Também tomou Davi a Ainoã de Jezreel, e ambas foram suas mulheres,

[[v9-25-44]]

^<<v9-25-44,44>>^ porque Saul tinha dado sua filha Mical, mulher de Davi, a Palti, filho de Laís, o qual era de Galim.

'''

xref:009-1-samuel/009-1-samuel-024.adoc#v9-24-0[&#60; Capítulo Anterior] | <<v9-25-0,Topo>> | xref:009-1-samuel/009-1-samuel-026.adoc#v9-26-0[Próximo Capítulo &#62;]