include::./index.adoc[]

[[v9-10-0]]
=== 1 Samuel, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-10-1]]

^<<v9-10-1,1>>^ Tomou Samuel um vaso de azeite, e lho derramou sobre a cabeça, e o beijou, e disse: Não te ungiu, porventura, o SENHOR por príncipe sobre a sua herança, o povo de Israel?

[[v9-10-2]]

^<<v9-10-2,2>>^ Quando te apartares, hoje, de mim, acharás dois homens junto ao sepulcro de Raquel, no território de Benjamim, em Zelza, os quais te dirão: Acharam-se as jumentas que foste procurar, e eis que teu pai já não pensa no caso delas e se aflige por causa de vós, dizendo: Que farei eu por meu filho?

[[v9-10-3]]

^<<v9-10-3,3>>^ Quando dali passares adiante e chegares ao carvalho de Tabor, ali te encontrarão três homens, que vão subindo a Deus a Betel: um levando três cabritos; outro, três bolos de pão, e o outro, um odre de vinho.

[[v9-10-4]]

^<<v9-10-4,4>>^ Eles te saudarão e te darão dois pães, que receberás da sua mão.

[[v9-10-5]]

^<<v9-10-5,5>>^ Então, seguirás a Gibeá-Eloim, onde está a guarnição dos filisteus; e há de ser que, entrando na cidade, encontrarás um grupo de profetas que descem do alto, precedidos de saltérios, e tambores, e flautas, e harpas, e eles estarão profetizando.

[[v9-10-6]]

^<<v9-10-6,6>>^ O Espírito do SENHOR se apossará de ti, e profetizarás com eles e tu serás mudado em outro homem.

[[v9-10-7]]

^<<v9-10-7,7>>^ Quando estes sinais te sucederem, faze o que a ocasião te pedir, porque Deus é contigo.

[[v9-10-8]]

^<<v9-10-8,8>>^ Tu, porém, descerás adiante de mim a Gilgal, e eis que eu descerei a ti, para sacrificar holocausto e para apresentar ofertas pacíficas; sete dias esperarás, até que eu venha ter contigo e te declare o que hás de fazer.

[[v9-10-9]]

^<<v9-10-9,9>>^ Sucedeu, pois, que, virando-se ele para despedir-se de Samuel, Deus lhe mudou o coração; e todos esses sinais se deram naquele mesmo dia.

[[v9-10-10]]

^<<v9-10-10,10>>^ Chegando eles a Gibeá, eis que um grupo de profetas lhes saiu ao encontro; o Espírito de Deus se apossou de Saul, e ele profetizou no meio deles.

[[v9-10-11]]

^<<v9-10-11,11>>^ Todos os que, dantes, o conheciam, vendo que ele profetizava com os profetas, diziam uns aos outros: Que é isso que sucedeu ao filho de Quis? Está também Saul entre os profetas?

[[v9-10-12]]

^<<v9-10-12,12>>^ Então, um homem respondeu: Pois quem é o pai deles? Pelo que se tornou em provérbio: Está também Saul entre os profetas?

[[v9-10-13]]

^<<v9-10-13,13>>^ E, tendo profetizado, seguiu para o alto.

[[v9-10-14]]

^<<v9-10-14,14>>^ Perguntou o tio de Saul, a ele e ao seu moço: Aonde fostes? Respondeu ele: A buscar as jumentas e, vendo que não apareciam, fomos a Samuel.

[[v9-10-15]]

^<<v9-10-15,15>>^ Então, disse o tio de Saul: Conta-me, peço-te, que é o que vos disse Samuel?

[[v9-10-16]]

^<<v9-10-16,16>>^ Respondeu Saul a seu tio: Informou-nos de que as jumentas foram encontradas. Porém, com respeito ao reino, de que Samuel falara, não lho declarou.

[[v9-10-17]]

^<<v9-10-17,17>>^ Convocou Samuel o povo ao SENHOR, em Mispa,

[[v9-10-18]]

^<<v9-10-18,18>>^ e disse aos filhos de Israel: Assim diz o SENHOR, Deus de Israel: Fiz subir a Israel do Egito e livrei-vos das mãos dos egípcios e das mãos de todos os reinos que vos oprimiam.

[[v9-10-19]]

^<<v9-10-19,19>>^ Mas vós rejeitastes, hoje, a vosso Deus, que vos livrou de todos os vossos males e trabalhos, e lhe dissestes: Não! Mas constitui um rei sobre nós. Agora, pois, ponde-vos perante o SENHOR, pelas vossas tribos e pelos vossos grupos de milhares.

[[v9-10-20]]

^<<v9-10-20,20>>^ Tendo Samuel feito chegar todas as tribos, foi indicada por sorte a de Benjamim.

[[v9-10-21]]

^<<v9-10-21,21>>^ Tendo feito chegar a tribo de Benjamim pelas suas famílias, foi indicada a família de Matri; e dela foi indicado Saul, filho de Quis. Mas, quando o procuraram, não podia ser encontrado.

[[v9-10-22]]

^<<v9-10-22,22>>^ Então, tornaram a perguntar ao SENHOR se aquele homem viera ali. Respondeu o SENHOR: Está aí escondido entre a bagagem.

[[v9-10-23]]

^<<v9-10-23,23>>^ Correram e o tomaram dali. Estando ele no meio do povo, era o mais alto e sobressaía de todo o povo do ombro para cima.

[[v9-10-24]]

^<<v9-10-24,24>>^ Então, disse Samuel a todo o povo: Vedes a quem o SENHOR escolheu? Pois em todo o povo não há nenhum semelhante a ele. Então, todo o povo rompeu em gritos, exclamando: Viva o rei!

[[v9-10-25]]

^<<v9-10-25,25>>^ Declarou Samuel ao povo o direito do reino, escreveu-o num livro e o pôs perante o SENHOR. Então, despediu Samuel todo o povo, cada um para sua casa.

[[v9-10-26]]

^<<v9-10-26,26>>^ Também Saul se foi para sua casa, a Gibeá; e foi com ele uma tropa de homens cujo coração Deus tocara.

[[v9-10-27]]

^<<v9-10-27,27>>^ Mas os filhos de Belial disseram: Como poderá este homem salvar-nos? E o desprezaram e não lhe trouxeram presentes. Porém Saul se fez de surdo.

'''

xref:009-1-samuel/009-1-samuel-009.adoc#v9-9-0[&#60; Capítulo Anterior] | <<v9-10-0,Topo>> | xref:009-1-samuel/009-1-samuel-011.adoc#v9-11-0[Próximo Capítulo &#62;]