include::./index.adoc[]

[[v9-15-0]]
=== 1 Samuel, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-15-1]]

^<<v9-15-1,1>>^ Disse Samuel a Saul: Enviou-me o SENHOR a ungir-te rei sobre o seu povo, sobre Israel; atenta, pois, agora, às palavras do SENHOR.

[[v9-15-2]]

^<<v9-15-2,2>>^ Assim diz o SENHOR dos Exércitos: Castigarei Amaleque pelo que fez a Israel: ter-se oposto a Israel no caminho, quando este subia do Egito.

[[v9-15-3]]

^<<v9-15-3,3>>^ Vai, pois, agora, e fere a Amaleque, e destrói totalmente a tudo o que tiver, e nada lhe poupes; porém matarás homem e mulher, meninos e crianças de peito, bois e ovelhas, camelos e jumentos.

[[v9-15-4]]

^<<v9-15-4,4>>^ Saul convocou o povo e os contou em Telaim: duzentos mil homens de pé e dez mil homens de Judá.

[[v9-15-5]]

^<<v9-15-5,5>>^ Chegando, pois, Saul à cidade de Amaleque, pôs emboscadas no vale.

[[v9-15-6]]

^<<v9-15-6,6>>^ E disse aos queneus: Ide-vos, retirai-vos e saí do meio dos amalequitas, para que eu vos não destrua juntamente com eles, porque usastes de misericórdia para com todos os filhos de Israel, quando subiram do Egito. Assim, os queneus se retiraram do meio dos amalequitas.

[[v9-15-7]]

^<<v9-15-7,7>>^ Então, feriu Saul os amalequitas, desde Havilá até chegar a Sur, que está defronte do Egito.

[[v9-15-8]]

^<<v9-15-8,8>>^ Tomou vivo a Agague, rei dos amalequitas; porém a todo o povo destruiu a fio de espada.

[[v9-15-9]]

^<<v9-15-9,9>>^ E Saul e o povo pouparam Agague, e o melhor das ovelhas e dos bois, e os animais gordos, e os cordeiros, e o melhor que havia e não os quiseram destruir totalmente; porém toda coisa vil e desprezível destruíram.

[[v9-15-10]]

^<<v9-15-10,10>>^ Então, veio a palavra do SENHOR a Samuel, dizendo:

[[v9-15-11]]

^<<v9-15-11,11>>^ Arrependo-me de haver constituído Saul rei, porquanto deixou de me seguir e não executou as minhas palavras. Então, Samuel se contristou e toda a noite clamou ao SENHOR.

[[v9-15-12]]

^<<v9-15-12,12>>^ Madrugou Samuel para encontrar a Saul pela manhã; e anunciou-se àquele: Já chegou Saul ao Carmelo, e eis que levantou para si um monumento; e, dando volta, passou e desceu a Gilgal.

[[v9-15-13]]

^<<v9-15-13,13>>^ Veio, pois, Samuel a Saul, e este lhe disse: Bendito sejas tu do SENHOR; executei as palavras do SENHOR.

[[v9-15-14]]

^<<v9-15-14,14>>^ Então, disse Samuel: Que balido, pois, de ovelhas é este nos meus ouvidos e o mugido de bois que ouço?

[[v9-15-15]]

^<<v9-15-15,15>>^ Respondeu Saul: De Amaleque os trouxeram; porque o povo poupou o melhor das ovelhas e dos bois, para os sacrificar ao SENHOR, teu Deus; o resto, porém, destruímos totalmente.

[[v9-15-16]]

^<<v9-15-16,16>>^ Então, disse Samuel a Saul: Espera, e te declararei o que o SENHOR me disse esta noite. Respondeu-lhe Saul: Fala.

[[v9-15-17]]

^<<v9-15-17,17>>^ Prosseguiu Samuel: Porventura, sendo tu pequeno aos teus olhos, não foste por cabeça das tribos de Israel, e não te ungiu o SENHOR rei sobre ele?

[[v9-15-18]]

^<<v9-15-18,18>>^ Enviou-te o SENHOR a este caminho e disse: Vai, e destrói totalmente estes pecadores, os amalequitas, e peleja contra eles, até exterminá-los.

[[v9-15-19]]

^<<v9-15-19,19>>^ Por que, pois, não atentaste à voz do SENHOR, mas te lançaste ao despojo e fizeste o que era mau aos olhos do SENHOR?

[[v9-15-20]]

^<<v9-15-20,20>>^ Então, disse Saul a Samuel: Pelo contrário, dei ouvidos à voz do SENHOR e segui o caminho pelo qual o SENHOR me enviou; e trouxe a Agague, rei de Amaleque, e os amalequitas, os destruí totalmente;

[[v9-15-21]]

^<<v9-15-21,21>>^ mas o povo tomou do despojo ovelhas e bois, o melhor do designado à destruição para oferecer ao SENHOR, teu Deus, em Gilgal.

[[v9-15-22]]

^<<v9-15-22,22>>^ Porém Samuel disse: Tem, porventura, o SENHOR tanto prazer em holocaustos e sacrifícios quanto em que se obedeça à sua palavra? Eis que o obedecer é melhor do que o sacrificar, e o atender, melhor do que a gordura de carneiros.

[[v9-15-23]]

^<<v9-15-23,23>>^ Porque a rebelião é como o pecado de feitiçaria, e a obstinação é como a idolatria e culto a ídolos do lar. Visto que rejeitaste a palavra do SENHOR, ele também te rejeitou a ti, para que não sejas rei.

[[v9-15-24]]

^<<v9-15-24,24>>^ Então, disse Saul a Samuel: Pequei, pois transgredi o mandamento do SENHOR e as tuas palavras; porque temi o povo e dei ouvidos à sua voz.

[[v9-15-25]]

^<<v9-15-25,25>>^ Agora, pois, te rogo, perdoa-me o meu pecado e volta comigo, para que adore o SENHOR.

[[v9-15-26]]

^<<v9-15-26,26>>^ Porém Samuel disse a Saul: Não tornarei contigo; visto que rejeitaste a palavra do SENHOR, já ele te rejeitou a ti, para que não sejas rei sobre Israel.

[[v9-15-27]]

^<<v9-15-27,27>>^ Virando-se Samuel para se ir, Saul o segurou pela orla do manto, e este se rasgou.

[[v9-15-28]]

^<<v9-15-28,28>>^ Então, Samuel lhe disse: O SENHOR rasgou, hoje, de ti o reino de Israel e o deu ao teu próximo, que é melhor do que tu.

[[v9-15-29]]

^<<v9-15-29,29>>^ Também a Glória de Israel não mente, nem se arrepende, porquanto não é homem, para que se arrependa.

[[v9-15-30]]

^<<v9-15-30,30>>^ Então, disse Saul: Pequei; honra-me, porém, agora, diante dos anciãos do meu povo e diante de Israel; e volta comigo, para que adore o SENHOR, teu Deus.

[[v9-15-31]]

^<<v9-15-31,31>>^ Então, Samuel seguiu a Saul, e este adorou o SENHOR.

[[v9-15-32]]

^<<v9-15-32,32>>^ Disse Samuel: Traze-me aqui Agague, rei dos amalequitas. Agague veio a ele, confiante; e disse: Certamente, já se foi a amargura da morte.

[[v9-15-33]]

^<<v9-15-33,33>>^ Disse, porém, Samuel: Assim como a tua espada desfilhou mulheres, assim desfilhada ficará tua mãe entre as mulheres. E Samuel despedaçou a Agague perante o SENHOR, em Gilgal.

[[v9-15-34]]

^<<v9-15-34,34>>^ Então, Samuel se foi a Ramá; e Saul subiu à sua casa, a Gibeá de Saul.

[[v9-15-35]]

^<<v9-15-35,35>>^ Nunca mais viu Samuel a Saul até ao dia da sua morte; porém tinha pena de Saul. O SENHOR se arrependeu de haver constituído Saul rei sobre Israel.

'''

xref:009-1-samuel/009-1-samuel-014.adoc#v9-14-0[&#60; Capítulo Anterior] | <<v9-15-0,Topo>> | xref:009-1-samuel/009-1-samuel-016.adoc#v9-16-0[Próximo Capítulo &#62;]