include::./index.adoc[]

[[v9-1-0]]
=== 1 Samuel, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-1-1]]

^<<v9-1-1,1>>^ Houve um homem de Ramataim-Zofim, da região montanhosa de Efraim, cujo nome era Elcana, filho de Jeroão, filho de Eliú, filho de Toú, filho de Zufe, efraimita.

[[v9-1-2]]

^<<v9-1-2,2>>^ Tinha ele duas mulheres: uma se chamava Ana, e a outra, Penina; Penina tinha filhos; Ana, porém, não os tinha.

[[v9-1-3]]

^<<v9-1-3,3>>^ Este homem subia da sua cidade de ano em ano a adorar e a sacrificar ao SENHOR dos Exércitos, em Siló. Estavam ali os dois filhos de Eli, Hofni e Fineias, como sacerdotes do SENHOR.

[[v9-1-4]]

^<<v9-1-4,4>>^ No dia em que Elcana oferecia o seu sacrifício, dava ele porções deste a Penina, sua mulher, e a todos os seus filhos e filhas.

[[v9-1-5]]

^<<v9-1-5,5>>^ A Ana, porém, dava porção dupla, porque ele a amava, ainda mesmo que o SENHOR a houvesse deixado estéril.

[[v9-1-6]]

^<<v9-1-6,6>>^ (A sua rival a provocava excessivamente para a irritar, porquanto o SENHOR lhe havia cerrado a madre.)

[[v9-1-7]]

^<<v9-1-7,7>>^ E assim o fazia ele de ano em ano; e, todas as vezes que Ana subia à Casa do SENHOR, a outra a irritava; pelo que chorava e não comia.

[[v9-1-8]]

^<<v9-1-8,8>>^ Então, Elcana, seu marido, lhe disse: Ana, por que choras? E por que não comes? E por que estás de coração triste? Não te sou eu melhor do que dez filhos?

[[v9-1-9]]

^<<v9-1-9,9>>^ Após terem comido e bebido em Siló, estando Eli, o sacerdote, assentado numa cadeira, junto a um pilar do templo do SENHOR,

[[v9-1-10]]

^<<v9-1-10,10>>^ levantou-se Ana, e, com amargura de alma, orou ao SENHOR, e chorou abundantemente.

[[v9-1-11]]

^<<v9-1-11,11>>^ E fez um voto, dizendo: SENHOR dos Exércitos, se benignamente atentares para a aflição da tua serva, e de mim te lembrares, e da tua serva te não esqueceres, e lhe deres um filho varão, ao SENHOR o darei por todos os dias da sua vida, e sobre a sua cabeça não passará navalha.

[[v9-1-12]]

^<<v9-1-12,12>>^ Demorando-se ela no orar perante o SENHOR, passou Eli a observar-lhe o movimento dos lábios,

[[v9-1-13]]

^<<v9-1-13,13>>^ porquanto Ana só no coração falava; seus lábios se moviam, porém não se lhe ouvia voz nenhuma; por isso, Eli a teve por embriagada

[[v9-1-14]]

^<<v9-1-14,14>>^ e lhe disse: Até quando estarás tu embriagada? Aparta de ti esse vinho!

[[v9-1-15]]

^<<v9-1-15,15>>^ Porém Ana respondeu: Não, senhor meu! Eu sou mulher atribulada de espírito; não bebi nem vinho nem bebida forte; porém venho derramando a minha alma perante o SENHOR.

[[v9-1-16]]

^<<v9-1-16,16>>^ Não tenhas, pois, a tua serva por filha de Belial; porque pelo excesso da minha ansiedade e da minha aflição é que tenho falado até agora.

[[v9-1-17]]

^<<v9-1-17,17>>^ Então, lhe respondeu Eli: Vai-te em paz, e o Deus de Israel te conceda a petição que lhe fizeste.

[[v9-1-18]]

^<<v9-1-18,18>>^ E disse ela: Ache a tua serva mercê diante de ti. Assim, a mulher se foi seu caminho e comeu, e o seu semblante já não era triste.

[[v9-1-19]]

^<<v9-1-19,19>>^ Levantaram-se de madrugada, e adoraram perante o SENHOR, e voltaram, e chegaram a sua casa, a Ramá. Elcana coabitou com Ana, sua mulher, e, lembrando-se dela o SENHOR,

[[v9-1-20]]

^<<v9-1-20,20>>^ ela concebeu e, passado o devido tempo, teve um filho, a que chamou Samuel, pois dizia: Do SENHOR o pedi.

[[v9-1-21]]

^<<v9-1-21,21>>^ Subiu Elcana, seu marido, com toda a sua casa, a oferecer ao SENHOR o sacrifício anual e a cumprir o seu voto.

[[v9-1-22]]

^<<v9-1-22,22>>^ Ana, porém, não subiu e disse a seu marido: Quando for o menino desmamado, levá-lo-ei para ser apresentado perante o SENHOR e para lá ficar para sempre.

[[v9-1-23]]

^<<v9-1-23,23>>^ Respondeu-lhe Elcana, seu marido: Faze o que melhor te agrade; fica até que o desmames; tão somente confirme o SENHOR a sua palavra. Assim, ficou a mulher e criou o filho ao peito, até que o desmamou.

[[v9-1-24]]

^<<v9-1-24,24>>^ Havendo-o desmamado, levou-o consigo, com um novilho de três anos, um efa de farinha e um odre de vinho, e o apresentou à Casa do SENHOR, a Siló. Era o menino ainda muito criança.

[[v9-1-25]]

^<<v9-1-25,25>>^ Imolaram o novilho e trouxeram o menino a Eli.

[[v9-1-26]]

^<<v9-1-26,26>>^ E disse ela: Ah! Meu senhor, tão certo como vives, eu sou aquela mulher que aqui esteve contigo, orando ao SENHOR.

[[v9-1-27]]

^<<v9-1-27,27>>^ Por este menino orava eu; e o SENHOR me concedeu a petição que eu lhe fizera.

[[v9-1-28]]

^<<v9-1-28,28>>^ Pelo que também o trago como devolvido ao SENHOR, por todos os dias que viver; pois do SENHOR o pedi. E eles adoraram ali o SENHOR.

'''

xref:008-rute/008-rute-004.adoc#v8-4-0[&#60; Capítulo Anterior] | <<v9-1-0,Topo>> | xref:009-1-samuel/009-1-samuel-002.adoc#v9-2-0[Próximo Capítulo &#62;]