include::./index.adoc[]

[[v9-6-0]]
=== 1 Samuel, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-6-1]]

^<<v9-6-1,1>>^ Sete meses esteve a arca do SENHOR na terra dos filisteus.

[[v9-6-2]]

^<<v9-6-2,2>>^ Estes chamaram os sacerdotes e os adivinhadores e lhes disseram: Que faremos da arca do SENHOR? Fazei-nos saber como a devolveremos para o seu lugar.

[[v9-6-3]]

^<<v9-6-3,3>>^ Responderam eles: Quando enviardes a arca do Deus de Israel, não a envieis vazia, porém enviá-la-eis a seu Deus com uma oferta pela culpa; então, sereis curados e sabereis por que a sua mão se não tira de vós.

[[v9-6-4]]

^<<v9-6-4,4>>^ Então, disseram: Qual será a oferta pela culpa que lhe havemos de apresentar? Responderam: Segundo o número dos príncipes dos filisteus, cinco tumores de ouro e cinco ratos de ouro, porquanto a praga é uma e a mesma sobre todos vós e sobre todos os vossos príncipes.

[[v9-6-5]]

^<<v9-6-5,5>>^ Fazei umas imitações dos vossos tumores e dos vossos ratos, que andam destruindo a terra, e dai glória ao Deus de Israel; porventura, aliviará a sua mão de cima de vós, e do vosso deus, e da vossa terra.

[[v9-6-6]]

^<<v9-6-6,6>>^ Por que, pois, endureceríeis o coração, como os egípcios e Faraó endureceram o coração? Porventura, depois de os haverem tratado tão mal, não os deixaram ir, e eles não se foram?

[[v9-6-7]]

^<<v9-6-7,7>>^ Agora, pois, fazei um carro novo, tomai duas vacas com crias, sobre as quais não se pôs ainda jugo, e atai-as ao carro; seus bezerros, levá-los-eis para casa.

[[v9-6-8]]

^<<v9-6-8,8>>^ Então, tomai a arca do SENHOR, e ponde-a sobre o carro, e metei num cofre, ao seu lado, as figuras de ouro que lhe haveis de entregar como oferta pela culpa; e deixai-a ir.

[[v9-6-9]]

^<<v9-6-9,9>>^ Reparai: se subir pelo caminho rumo do seu território a Bete-Semes, foi ele que nos fez este grande mal; e, se não, saberemos que não foi a sua mão que nos feriu; foi casual o que nos sucedeu.

[[v9-6-10]]

^<<v9-6-10,10>>^ Assim fizeram aqueles homens, e tomaram duas vacas com crias, e as ataram ao carro, e os seus bezerros encerraram em casa.

[[v9-6-11]]

^<<v9-6-11,11>>^ Puseram a arca do SENHOR sobre o carro, como também o cofre com os ratos de ouro e com as imitações dos tumores.

[[v9-6-12]]

^<<v9-6-12,12>>^ As vacas se encaminharam diretamente para Bete-Semes e, andando e berrando, seguiam sempre por esse mesmo caminho, sem se desviarem nem para a direita nem para a esquerda; os príncipes dos filisteus foram atrás delas, até ao território de Bete-Semes.

[[v9-6-13]]

^<<v9-6-13,13>>^ Andavam os de Bete-Semes fazendo a sega do trigo no vale e, levantando os olhos, viram a arca; e, vendo-a, se alegraram.

[[v9-6-14]]

^<<v9-6-14,14>>^ O carro veio ao campo de Josué, o bete-semita, e parou ali, onde havia uma grande pedra; fenderam a madeira do carro e ofereceram as vacas ao SENHOR, em holocausto.

[[v9-6-15]]

^<<v9-6-15,15>>^ Os levitas desceram a arca do SENHOR, como também o cofre que estava junto a ela, em que estavam as obras de ouro, e os puseram sobre a grande pedra. No mesmo dia, os homens de Bete-Semes ofereceram holocaustos e imolaram sacrifícios ao SENHOR.

[[v9-6-16]]

^<<v9-6-16,16>>^ Viram aquilo os cinco príncipes dos filisteus e voltaram para Ecrom no mesmo dia.

[[v9-6-17]]

^<<v9-6-17,17>>^ São estes, pois, os tumores de ouro que enviaram os filisteus ao SENHOR como oferta pela culpa: por Asdode, um; por Gaza, outro; por Asquelom, outro; por Gate, outro; por Ecrom, outro;

[[v9-6-18]]

^<<v9-6-18,18>>^ como também os ratos de ouro, segundo o número de todas as cidades dos filisteus, pertencentes aos cinco príncipes, desde as cidades fortes até às aldeias campestres. A grande pedra, sobre a qual puseram a arca do SENHOR, está até ao dia de hoje no campo de Josué, o bete-semita.

[[v9-6-19]]

^<<v9-6-19,19>>^ Feriu o SENHOR os homens de Bete-Semes, porque olharam para dentro da arca do SENHOR, sim, feriu deles setenta homens; então, o povo chorou, porquanto o SENHOR fizera tão grande morticínio entre eles.

[[v9-6-20]]

^<<v9-6-20,20>>^ Então, disseram os homens de Bete-Semes: Quem poderia estar perante o SENHOR, este Deus santo? E para quem subirá desde nós?

[[v9-6-21]]

^<<v9-6-21,21>>^ Enviaram, pois, mensageiros aos habitantes de Quiriate-Jearim, dizendo: Os filisteus devolveram a arca do SENHOR; descei, pois, e fazei-a subir para vós outros.

'''

xref:009-1-samuel/009-1-samuel-005.adoc#v9-5-0[&#60; Capítulo Anterior] | <<v9-6-0,Topo>> | xref:009-1-samuel/009-1-samuel-007.adoc#v9-7-0[Próximo Capítulo &#62;]