include::./index.adoc[]

[[v9-26-0]]
=== 1 Samuel, 26
// ara ?, ARA - Almeida Revista e Atualizada

[[v9-26-1]]

^<<v9-26-1,1>>^ Vieram os zifeus a Saul, a Gibeá, e disseram: Não se acha Davi escondido no outeiro de Haquila, defronte de Jesimom?

[[v9-26-2]]

^<<v9-26-2,2>>^ Então, Saul se levantou e desceu ao deserto de Zife, e com ele, três mil homens escolhidos de Israel, a buscar a Davi.

[[v9-26-3]]

^<<v9-26-3,3>>^ Acampou-se Saul no outeiro de Haquila, defronte de Jesimom, junto ao caminho; porém Davi ficou no deserto, e, sabendo que Saul vinha para ali à sua procura,

[[v9-26-4]]

^<<v9-26-4,4>>^ enviou espias, e soube que Saul tinha vindo.

[[v9-26-5]]

^<<v9-26-5,5>>^ Davi se levantou, e veio ao lugar onde Saul acampara, e viu o lugar onde se deitaram Saul e Abner, filho de Ner, comandante do seu exército. Saul estava deitado no acampamento, e o povo, ao redor dele.

[[v9-26-6]]

^<<v9-26-6,6>>^ Disse Davi a Aimeleque, o heteu, e a Abisai, filho de Zeruia, irmão de Joabe: Quem descerá comigo a Saul, ao arraial? Respondeu Abisai: Eu descerei contigo.

[[v9-26-7]]

^<<v9-26-7,7>>^ Vieram, pois, Davi e Abisai, de noite, ao povo, e eis que Saul estava deitado, dormindo no acampamento, e a sua lança, fincada na terra à sua cabeceira; Abner e o povo estavam deitados ao redor dele.

[[v9-26-8]]

^<<v9-26-8,8>>^ Então, disse Abisai a Davi: Deus te entregou, hoje, nas mãos o teu inimigo; deixa-me, pois, agora, encravá-lo com a lança, ao chão, de um só golpe; não será preciso segundo.

[[v9-26-9]]

^<<v9-26-9,9>>^ Davi, porém, respondeu a Abisai: Não o mates, pois quem haverá que estenda a mão contra o ungido do SENHOR e fique inocente?

[[v9-26-10]]

^<<v9-26-10,10>>^ Acrescentou Davi: Tão certo como vive o SENHOR, este o ferirá, ou o seu dia chegará em que morra, ou em que, descendo à batalha, seja morto.

[[v9-26-11]]

^<<v9-26-11,11>>^ O SENHOR me guarde de que eu estenda a mão contra o seu ungido; agora, porém, toma a lança que está à sua cabeceira e a bilha da água, e vamo-nos.

[[v9-26-12]]

^<<v9-26-12,12>>^ Tomou, pois, Davi a lança e a bilha da água da cabeceira de Saul, e foram-se; ninguém o viu, nem o soube, nem se despertou, pois todos dormiam, porquanto, da parte do SENHOR, lhes havia caído profundo sono.

[[v9-26-13]]

^<<v9-26-13,13>>^ Tendo Davi passado ao outro lado, pôs-se no cimo do monte ao longe, de maneira que entre eles havia grande distância.

[[v9-26-14]]

^<<v9-26-14,14>>^ Bradou ao povo e a Abner, filho de Ner, dizendo: Não respondes, Abner? Então, Abner acudiu e disse: Quem és tu, que bradas ao rei?

[[v9-26-15]]

^<<v9-26-15,15>>^ Então, disse Davi a Abner: Porventura, não és homem? E quem há em Israel como tu? Por que, pois, não guardaste o rei, teu senhor? Porque veio um do povo para destruir o rei, teu senhor.

[[v9-26-16]]

^<<v9-26-16,16>>^ Não é bom isso que fizeste; tão certo como vive o SENHOR, deveis morrer, vós que não guardastes a vosso senhor, o ungido do SENHOR; vede, agora, onde está a lança do rei e a bilha da água, que tinha à sua cabeceira.

[[v9-26-17]]

^<<v9-26-17,17>>^ Então, reconheceu Saul a voz de Davi e disse: Não é a tua voz, meu filho Davi? Respondeu Davi: Sim, a minha, ó rei, meu senhor.

[[v9-26-18]]

^<<v9-26-18,18>>^ Disse mais: Por que persegue o meu senhor assim seu servo? Pois que fiz eu? E que maldade se acha nas minhas mãos?

[[v9-26-19]]

^<<v9-26-19,19>>^ Ouve, pois, agora, te rogo, ó rei, meu senhor, as palavras de teu servo: se é o SENHOR que te incita contra mim, aceite ele a oferta de manjares; porém, se são os filhos dos homens, malditos sejam perante o SENHOR; pois eles me expulsaram hoje, para que eu não tenha parte na herança do SENHOR, como que dizendo: Vai, serve a outros deuses.

[[v9-26-20]]

^<<v9-26-20,20>>^ Agora, pois, não se derrame o meu sangue longe desta terra do SENHOR; pois saiu o rei de Israel em busca de uma pulga, como quem persegue uma perdiz nos montes.

[[v9-26-21]]

^<<v9-26-21,21>>^ Então, disse Saul: Pequei; volta, meu filho Davi, pois não tornarei a fazer-te mal; porque foi, hoje, preciosa a minha vida aos teus olhos. Eis que tenho procedido como louco e errado excessivamente.

[[v9-26-22]]

^<<v9-26-22,22>>^ Davi, então, respondeu e disse: Eis aqui a lança, ó rei; venha aqui um dos moços e leve-a.

[[v9-26-23]]

^<<v9-26-23,23>>^ Pague, porém, o SENHOR a cada um a sua justiça e a sua lealdade; pois o SENHOR te havia entregado, hoje, nas minhas mãos, porém eu não quis estendê-las contra o ungido do SENHOR.

[[v9-26-24]]

^<<v9-26-24,24>>^ Assim como foi a tua vida, hoje, de muita estima aos meus olhos, assim também seja a minha aos olhos do SENHOR, e ele me livre de toda tribulação.

[[v9-26-25]]

^<<v9-26-25,25>>^ Então, Saul disse a Davi: Bendito sejas tu, meu filho Davi; pois grandes coisas farás e, de fato, prevalecerás. Então, Davi continuou o seu caminho, e Saul voltou para o seu lugar.

'''

xref:009-1-samuel/009-1-samuel-025.adoc#v9-25-0[&#60; Capítulo Anterior] | <<v9-26-0,Topo>> | xref:009-1-samuel/009-1-samuel-027.adoc#v9-27-0[Próximo Capítulo &#62;]