include::./index.adoc[]

[[v8-4-0]]
=== Rute, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v8-4-1]]

^<<v8-4-1,1>>^ Boaz subiu à porta da cidade e assentou-se ali. Eis que o resgatador de que Boaz havia falado ia passando; então, lhe disse: Ó fulano, chega-te para aqui e assenta-te; ele se virou e se assentou.

[[v8-4-2]]

^<<v8-4-2,2>>^ Então, Boaz tomou dez homens dos anciãos da cidade e disse: Assentai-vos aqui. E assentaram-se.

[[v8-4-3]]

^<<v8-4-3,3>>^ Disse ao resgatador: Aquela parte da terra que foi de Elimeleque, nosso irmão, Noemi, que tornou da terra dos moabitas, a tem para venda.

[[v8-4-4]]

^<<v8-4-4,4>>^ Resolvi, pois, informar-te disso e dizer-te: compra-a na presença destes que estão sentados aqui e na de meu povo; se queres resgatá-la, resgata-a; se não, declara-mo para que eu o saiba, pois outro não há senão tu que a resgate, e eu, depois de ti. Respondeu ele: Eu a resgatarei.

[[v8-4-5]]

^<<v8-4-5,5>>^ Disse, porém, Boaz: No dia em que tomares a terra da mão de Noemi, também a tomarás da mão de Rute, a moabita, já viúva, para suscitar o nome do esposo falecido, sobre a herança dele.

[[v8-4-6]]

^<<v8-4-6,6>>^ Então, disse o resgatador: Para mim não a poderei resgatar, para que não prejudique a minha; redime tu o que me cumpria resgatar, porque eu não poderei fazê-lo.

[[v8-4-7]]

^<<v8-4-7,7>>^ Este era, outrora, o costume em Israel, quanto a resgates e permutas: o que queria confirmar qualquer negócio tirava o calçado e o dava ao seu parceiro; assim se confirmava negócio em Israel.

[[v8-4-8]]

^<<v8-4-8,8>>^ Disse, pois, o resgatador a Boaz: Compra-a tu. E tirou o calçado.

[[v8-4-9]]

^<<v8-4-9,9>>^ Então, Boaz disse aos anciãos e a todo o povo: Sois, hoje, testemunhas de que comprei da mão de Noemi tudo o que pertencia a Elimeleque, a Quiliom e a Malom;

[[v8-4-10]]

^<<v8-4-10,10>>^ e também tomo por mulher Rute, a moabita, que foi esposa de Malom, para suscitar o nome deste sobre a sua herança, para que este nome não seja exterminado dentre seus irmãos e da porta da sua cidade; disto sois, hoje, testemunhas.

[[v8-4-11]]

^<<v8-4-11,11>>^ Todo o povo que estava na porta e os anciãos disseram: Somos testemunhas; o SENHOR faça a esta mulher, que entra na tua casa, como a Raquel e como a Lia, que ambas edificaram a casa de Israel; e tu, Boaz, há-te valorosamente em Efrata e faze-te nome afamado em Belém.

[[v8-4-12]]

^<<v8-4-12,12>>^ Seja a tua casa como a casa de Perez, que Tamar teve de Judá, pela prole que o SENHOR te der desta jovem.

[[v8-4-13]]

^<<v8-4-13,13>>^ Assim, tomou Boaz a Rute, e ela passou a ser sua mulher; coabitou com ela, e o SENHOR lhe concedeu que concebesse, e teve um filho.

[[v8-4-14]]

^<<v8-4-14,14>>^ Então, as mulheres disseram a Noemi: Seja o SENHOR bendito, que não deixou, hoje, de te dar um neto que será teu resgatador, e seja afamado em Israel o nome deste.

[[v8-4-15]]

^<<v8-4-15,15>>^ Ele será restaurador da tua vida e consolador da tua velhice, pois tua nora, que te ama, o deu à luz, e ela te é melhor do que sete filhos.

[[v8-4-16]]

^<<v8-4-16,16>>^ Noemi tomou o menino, e o pôs no regaço, e entrou a cuidar dele.

[[v8-4-17]]

^<<v8-4-17,17>>^ As vizinhas lhe deram nome, dizendo: A Noemi nasceu um filho. E lhe chamaram Obede. Este é o pai de Jessé, pai de Davi.

[[v8-4-18]]

^<<v8-4-18,18>>^ São estas, pois, as gerações de Perez: Perez gerou a Esrom,

[[v8-4-19]]

^<<v8-4-19,19>>^ Esrom gerou a Rão, Rão gerou a Aminadabe,

[[v8-4-20]]

^<<v8-4-20,20>>^ Aminadabe gerou a Naassom, Naassom gerou a Salmom,

[[v8-4-21]]

^<<v8-4-21,21>>^ Salmom gerou a Boaz, Boaz gerou a Obede,

[[v8-4-22]]

^<<v8-4-22,22>>^ Obede gerou a Jessé, e Jessé gerou a Davi.

'''

xref:008-rute/008-rute-003.adoc#v8-3-0[&#60; Capítulo Anterior] | <<v8-4-0,Topo>> | xref:009-1-samuel/009-1-samuel-001.adoc#v9-1-0[Próximo Capítulo &#62;]