include::./index.adoc[]

[[v8-1-0]]
=== Rute, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v8-1-1]]

^<<v8-1-1,1>>^ Nos dias em que julgavam os juízes, houve fome na terra; e um homem de Belém de Judá saiu a habitar na terra de Moabe, com sua mulher e seus dois filhos.

[[v8-1-2]]

^<<v8-1-2,2>>^ Este homem se chamava Elimeleque, e sua mulher, Noemi; os filhos se chamavam Malom e Quiliom, efrateus, de Belém de Judá; vieram à terra de Moabe e ficaram ali.

[[v8-1-3]]

^<<v8-1-3,3>>^ Morreu Elimeleque, marido de Noemi; e ficou ela com seus dois filhos,

[[v8-1-4]]

^<<v8-1-4,4>>^ os quais casaram com mulheres moabitas; era o nome de uma Orfa, e o nome da outra, Rute; e ficaram ali quase dez anos.

[[v8-1-5]]

^<<v8-1-5,5>>^ Morreram também ambos, Malom e Quiliom, ficando, assim, a mulher desamparada de seus dois filhos e de seu marido.

[[v8-1-6]]

^<<v8-1-6,6>>^ Então, se dispôs ela com as suas noras e voltou da terra de Moabe, porquanto, nesta, ouviu que o SENHOR se lembrara do seu povo, dando-lhe pão.

[[v8-1-7]]

^<<v8-1-7,7>>^ Saiu, pois, ela com suas duas noras do lugar onde estivera; e, indo elas caminhando, de volta para a terra de Judá,

[[v8-1-8]]

^<<v8-1-8,8>>^ disse-lhes Noemi: Ide, voltai cada uma à casa de sua mãe; e o SENHOR use convosco de benevolência, como vós usastes com os que morreram e comigo.

[[v8-1-9]]

^<<v8-1-9,9>>^ O SENHOR vos dê que sejais felizes, cada uma em casa de seu marido. E beijou-as. Elas, porém, choraram em alta voz

[[v8-1-10]]

^<<v8-1-10,10>>^ e lhe disseram: Não! Iremos contigo ao teu povo.

[[v8-1-11]]

^<<v8-1-11,11>>^ Porém Noemi disse: Voltai, minhas filhas! Por que iríeis comigo? Tenho eu ainda no ventre filhos, para que vos sejam por maridos?

[[v8-1-12]]

^<<v8-1-12,12>>^ Tornai, filhas minhas! Ide-vos embora, porque sou velha demais para ter marido. Ainda quando eu dissesse: tenho esperança ou ainda que esta noite tivesse marido e houvesse filhos,

[[v8-1-13]]

^<<v8-1-13,13>>^ esperá-los-íeis até que viessem a ser grandes? Abster-vos-íeis de tomardes marido? Não, filhas minhas! Porque, por vossa causa, a mim me amarga o ter o SENHOR descarregado contra mim a sua mão.

[[v8-1-14]]

^<<v8-1-14,14>>^ Então, de novo, choraram em voz alta; Orfa, com um beijo, se despediu de sua sogra, porém Rute se apegou a ela.

[[v8-1-15]]

^<<v8-1-15,15>>^ Disse Noemi: Eis que tua cunhada voltou ao seu povo e aos seus deuses; também tu, volta após a tua cunhada.

[[v8-1-16]]

^<<v8-1-16,16>>^ Disse, porém, Rute: Não me instes para que te deixe e me obrigue a não seguir-te; porque, aonde quer que fores, irei eu e, onde quer que pousares, ali pousarei eu; o teu povo é o meu povo, o teu Deus é o meu Deus.

[[v8-1-17]]

^<<v8-1-17,17>>^ Onde quer que morreres, morrerei eu e aí serei sepultada; faça-me o SENHOR o que bem lhe aprouver, se outra coisa que não seja a morte me separar de ti.

[[v8-1-18]]

^<<v8-1-18,18>>^ Vendo, pois, Noemi que de todo estava resolvida a acompanhá-la, deixou de insistir com ela.

[[v8-1-19]]

^<<v8-1-19,19>>^ Então, ambas se foram, até que chegaram a Belém; sucedeu que, ao chegarem ali, toda a cidade se comoveu por causa delas, e as mulheres diziam: Não é esta Noemi?

[[v8-1-20]]

^<<v8-1-20,20>>^ Porém ela lhes dizia: Não me chameis Noemi; chamai-me Mara, porque grande amargura me tem dado o Todo-Poderoso.

[[v8-1-21]]

^<<v8-1-21,21>>^ Ditosa eu parti, porém o SENHOR me fez voltar pobre; por que, pois, me chamareis Noemi, visto que o SENHOR se manifestou contra mim e o Todo-Poderoso me tem afligido?

[[v8-1-22]]

^<<v8-1-22,22>>^ Assim, voltou Noemi da terra de Moabe, com Rute, sua nora, a moabita; e chegaram a Belém no princípio da sega da cevada.

'''

xref:007-juizes/007-juizes-021.adoc#v7-21-0[&#60; Capítulo Anterior] | <<v8-1-0,Topo>> | xref:008-rute/008-rute-002.adoc#v8-2-0[Próximo Capítulo &#62;]