include::./index.adoc[]

[[v12-5-0]]
=== 2 Reis, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-5-1]]

^<<v12-5-1,1>>^ Naamã, comandante do exército do rei da Síria, era grande homem diante do seu senhor e de muito conceito, porque por ele o SENHOR dera vitória à Síria; era ele herói da guerra, porém leproso.

[[v12-5-2]]

^<<v12-5-2,2>>^ Saíram tropas da Síria, e da terra de Israel levaram cativa uma menina, que ficou ao serviço da mulher de Naamã.

[[v12-5-3]]

^<<v12-5-3,3>>^ Disse ela à sua senhora: Tomara o meu senhor estivesse diante do profeta que está em Samaria; ele o restauraria da sua lepra.

[[v12-5-4]]

^<<v12-5-4,4>>^ Então, foi Naamã e disse ao seu senhor: Assim e assim falou a jovem que é da terra de Israel.

[[v12-5-5]]

^<<v12-5-5,5>>^ Respondeu o rei da Síria: Vai, anda, e enviarei uma carta ao rei de Israel. Ele partiu e levou consigo dez talentos de prata, seis mil siclos de ouro e dez vestes festivais.

[[v12-5-6]]

^<<v12-5-6,6>>^ Levou também ao rei de Israel a carta, que dizia: Logo, em chegando a ti esta carta, saberás que eu te enviei Naamã, meu servo, para que o cures da sua lepra.

[[v12-5-7]]

^<<v12-5-7,7>>^ Tendo lido o rei de Israel a carta, rasgou as suas vestes e disse: Acaso, sou Deus com poder de tirar a vida ou dá-la, para que este envie a mim um homem para eu curá-lo de sua lepra? Notai, pois, e vede que procura um pretexto para romper comigo.

[[v12-5-8]]

^<<v12-5-8,8>>^ Ouvindo, porém, Eliseu, homem de Deus, que o rei de Israel rasgara as suas vestes, mandou dizer ao rei: Por que rasgaste as tuas vestes? Deixa-o vir a mim, e saberá que há profeta em Israel.

[[v12-5-9]]

^<<v12-5-9,9>>^ Veio, pois, Naamã com os seus cavalos e os seus carros e parou à porta da casa de Eliseu.

[[v12-5-10]]

^<<v12-5-10,10>>^ Então, Eliseu lhe mandou um mensageiro, dizendo: Vai, lava-te sete vezes no Jordão, e a tua carne será restaurada, e ficarás limpo.

[[v12-5-11]]

^<<v12-5-11,11>>^ Naamã, porém, muito se indignou e se foi, dizendo: Pensava eu que ele sairia a ter comigo, pôr-se-ia de pé, invocaria o nome do SENHOR, seu Deus, moveria a mão sobre o lugar da lepra e restauraria o leproso.

[[v12-5-12]]

^<<v12-5-12,12>>^ Não são, porventura, Abana e Farfar, rios de Damasco, melhores do que todas as águas de Israel? Não poderia eu lavar-me neles e ficar limpo? E voltou-se e se foi com indignação.

[[v12-5-13]]

^<<v12-5-13,13>>^ Então, se chegaram a ele os seus oficiais e lhe disseram: Meu pai, se te houvesse dito o profeta alguma coisa difícil, acaso, não a farias? Quanto mais, já que apenas te disse: Lava-te e ficarás limpo.

[[v12-5-14]]

^<<v12-5-14,14>>^ Então, desceu e mergulhou no Jordão sete vezes, consoante a palavra do homem de Deus; e a sua carne se tornou como a carne de uma criança, e ficou limpo.

[[v12-5-15]]

^<<v12-5-15,15>>^ Voltou ao homem de Deus, ele e toda a sua comitiva; veio, pôs-se diante dele e disse: Eis que, agora, reconheço que em toda a terra não há Deus, senão em Israel; agora, pois, te peço aceites um presente do teu servo.

[[v12-5-16]]

^<<v12-5-16,16>>^ Porém ele disse: Tão certo como vive o SENHOR, em cuja presença estou, não o aceitarei. Instou com ele para que o aceitasse, mas ele recusou.

[[v12-5-17]]

^<<v12-5-17,17>>^ Disse Naamã: Se não queres, peço-te que ao teu servo seja dado levar uma carga de terra de dois mulos; porque nunca mais oferecerá este teu servo holocausto nem sacrifício a outros deuses, senão ao SENHOR.

[[v12-5-18]]

^<<v12-5-18,18>>^ Nisto perdoe o SENHOR a teu servo; quando o meu senhor entra na casa de Rimom para ali adorar, e ele se encosta na minha mão, e eu também me tenha de encurvar na casa de Rimom, quando assim me prostrar na casa de Rimom, nisto perdoe o SENHOR a teu servo.

[[v12-5-19]]

^<<v12-5-19,19>>^ Eliseu lhe disse: Vai em paz. Quando Naamã se tinha afastado certa distância,

[[v12-5-20]]

^<<v12-5-20,20>>^ Geazi, o moço de Eliseu, homem de Deus, disse consigo: Eis que meu senhor impediu a este siro Naamã que da sua mão se lhe desse alguma coisa do que trazia; porém, tão certo como vive o SENHOR, hei de correr atrás dele e receberei dele alguma coisa.

[[v12-5-21]]

^<<v12-5-21,21>>^ Então, foi Geazi em alcance de Naamã; Naamã, vendo que corria atrás dele, saltou do carro a encontrá-lo e perguntou: Vai tudo bem?

[[v12-5-22]]

^<<v12-5-22,22>>^ Ele respondeu: Tudo vai bem; meu senhor me mandou dizer: Eis que, agora mesmo, vieram a mim dois jovens, dentre os discípulos dos profetas da região montanhosa de Efraim; dá-lhes, pois, um talento de prata e duas vestes festivais.

[[v12-5-23]]

^<<v12-5-23,23>>^ Disse Naamã: Sê servido tomar dois talentos. Instou com ele e amarrou dois talentos de prata em dois sacos e duas vestes festivais; pô-los sobre dois dos seus moços, os quais os levaram adiante dele.

[[v12-5-24]]

^<<v12-5-24,24>>^ Tendo ele chegado ao outeiro, tomou-os das suas mãos e os depositou na casa; e despediu aqueles homens, que se foram.

[[v12-5-25]]

^<<v12-5-25,25>>^ Ele, porém, entrou e se pôs diante de seu senhor. Perguntou-lhe Eliseu: Donde vens, Geazi? Respondeu ele: Teu servo não foi a parte alguma.

[[v12-5-26]]

^<<v12-5-26,26>>^ Porém ele lhe disse: Porventura, não fui contigo em espírito quando aquele homem voltou do seu carro, a encontrar-te? Era isto ocasião para tomares prata e para tomares vestes, olivais e vinhas, ovelhas e bois, servos e servas?

[[v12-5-27]]

^<<v12-5-27,27>>^ Portanto, a lepra de Naamã se pegará a ti e à tua descendência para sempre. Então, saiu de diante dele leproso, branco como a neve.

'''

xref:012-2-reis/012-2-reis-004.adoc#v12-4-0[&#60; Capítulo Anterior] | <<v12-5-0,Topo>> | xref:012-2-reis/012-2-reis-006.adoc#v12-6-0[Próximo Capítulo &#62;]