include::./index.adoc[]

[[v12-25-0]]
=== 2 Reis, 25
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-25-1]]

^<<v12-25-1,1>>^ Sucedeu que, no nono ano do reinado de Zedequias, aos dez dias do décimo mês, Nabucodonosor, rei da Babilônia, veio contra Jerusalém, ele e todo o seu exército, e se acamparam contra ela, e levantaram contra ela tranqueiras em redor.

[[v12-25-2]]

^<<v12-25-2,2>>^ A cidade ficou sitiada até ao undécimo ano do rei Zedequias.

[[v12-25-3]]

^<<v12-25-3,3>>^ Aos nove dias do quarto mês, quando a cidade se via apertada da fome, e não havia pão para o povo da terra,

[[v12-25-4]]

^<<v12-25-4,4>>^ então, a cidade foi arrombada, e todos os homens de guerra fugiram de noite pelo caminho da porta que está entre os dois muros perto do jardim do rei, a despeito de os caldeus se acharem contra a cidade em redor; o rei fugiu pelo caminho da Campina,

[[v12-25-5]]

^<<v12-25-5,5>>^ porém o exército dos caldeus perseguiu o rei Zedequias e o alcançou nas campinas de Jericó; e todo o exército deste se dispersou e o abandonou.

[[v12-25-6]]

^<<v12-25-6,6>>^ Então, o tomaram preso e o fizeram subir ao rei da Babilônia, a Ribla, o qual lhe pronunciou a sentença.

[[v12-25-7]]

^<<v12-25-7,7>>^ Aos filhos de Zedequias mataram à sua própria vista e a ele vazaram os olhos; ataram-no com duas cadeias de bronze e o levaram para a Babilônia.

[[v12-25-8]]

^<<v12-25-8,8>>^ No sétimo dia do quinto mês, do ano décimo nono de Nabucodonosor, rei da Babilônia, Nebuzaradã, chefe da guarda e servidor do rei da Babilônia, veio a Jerusalém.

[[v12-25-9]]

^<<v12-25-9,9>>^ E queimou a Casa do SENHOR e a casa do rei, como também todas as casas de Jerusalém; também entregou às chamas todos os edifícios importantes.

[[v12-25-10]]

^<<v12-25-10,10>>^ Todo o exército dos caldeus que estava com o chefe da guarda derribou os muros em redor de Jerusalém.

[[v12-25-11]]

^<<v12-25-11,11>>^ O mais do povo que havia ficado na cidade, e os desertores que se entregaram ao rei da Babilônia, e o mais da multidão, Nebuzaradã, o chefe da guarda, levou cativos.

[[v12-25-12]]

^<<v12-25-12,12>>^ Porém dos mais pobres da terra deixou o chefe da guarda ficar alguns para vinheiros e para lavradores.

[[v12-25-13]]

^<<v12-25-13,13>>^ Cortaram em pedaços os caldeus as colunas de bronze que estavam na Casa do SENHOR, como também os suportes e o mar de bronze que estavam na Casa do SENHOR; e levaram o bronze para a Babilônia.

[[v12-25-14]]

^<<v12-25-14,14>>^ Levaram também as panelas, as pás, as espevitadeiras, os recipientes de incenso e todos os utensílios de bronze, com que se ministrava.

[[v12-25-15]]

^<<v12-25-15,15>>^ Tomou também o chefe da guarda os braseiros, as bacias e tudo quanto fosse de ouro ou de prata.

[[v12-25-16]]

^<<v12-25-16,16>>^ Quanto às duas colunas, ao mar e aos suportes que Salomão fizera para a Casa do SENHOR, o peso do bronze de todos estes utensílios era incalculável.

[[v12-25-17]]

^<<v12-25-17,17>>^ A altura de uma coluna era de dezoito côvados, e sobre ela havia um capitel de bronze de três côvados de altura; a obra de rede e as romãs sobre o capitel ao redor, tudo era de bronze; semelhante a esta era a outra coluna com a rede.

[[v12-25-18]]

^<<v12-25-18,18>>^ Levou também o chefe da guarda a Seraías, sumo sacerdote, e a Sofonias, segundo sacerdote, e os três guardas da porta.

[[v12-25-19]]

^<<v12-25-19,19>>^ Da cidade tomou a um oficial, que era comandante das tropas de guerra, e cinco homens dos que eram conselheiros do rei e se achavam na cidade, como também ao escrivão-mor do exército, que alistava o povo da terra, e sessenta homens do povo do lugar, que se achavam na cidade.

[[v12-25-20]]

^<<v12-25-20,20>>^ Tomando-os, Nebuzaradã, o chefe da guarda, levou-os ao rei da Babilônia, a Ribla.

[[v12-25-21]]

^<<v12-25-21,21>>^ O rei da Babilônia os feriu e os matou em Ribla, na terra de Hamate. Assim, Judá foi levado cativo para fora da sua terra.

[[v12-25-22]]

^<<v12-25-22,22>>^ Quanto ao povo que ficara na terra de Judá, Nabucodonosor, rei da Babilônia, que o deixara ficar, nomeou governador sobre ele a Gedalias, filho de Aicão, filho de Safã.

[[v12-25-23]]

^<<v12-25-23,23>>^ Ouvindo, pois, os capitães dos exércitos, eles e os seus homens, que o rei da Babilônia nomeara governador a Gedalias, vieram ter com este em Mispa, a saber, Ismael, filho de Netanias, Joanã, filho de Careá, Seraías, filho de Tanumete, o netofatita, e Jazanias, filho do maacatita, eles e os seus homens.

[[v12-25-24]]

^<<v12-25-24,24>>^ Gedalias jurou a eles e aos seus homens e lhes disse: Nada temais da parte dos caldeus; ficai na terra, servi ao rei da Babilônia, e bem vos irá.

[[v12-25-25]]

^<<v12-25-25,25>>^ Sucedeu, porém, que, no sétimo mês, veio Ismael, filho de Netanias, filho de Elisama, de família real, e dez homens, com ele, e feriram Gedalias, e ele morreu, como também aos judeus e aos caldeus que estavam com ele em Mispa.

[[v12-25-26]]

^<<v12-25-26,26>>^ Então, se levantou todo o povo, tanto os pequenos como os grandes, como também os capitães das tropas, e foram para o Egito, porque temiam aos caldeus.

[[v12-25-27]]

^<<v12-25-27,27>>^ No trigésimo sétimo ano do cativeiro de Joaquim, rei de Judá, no dia vinte e sete do duodécimo mês, Evil-Merodaque, rei da Babilônia, no ano em que começou a reinar, libertou do cárcere a Joaquim, rei de Judá.

[[v12-25-28]]

^<<v12-25-28,28>>^ Falou com ele benignamente e lhe deu lugar de mais honra do que a dos reis que estavam com ele na Babilônia.

[[v12-25-29]]

^<<v12-25-29,29>>^ Mudou-lhe as vestes do cárcere, e Joaquim passou a comer pão na sua presença todos os dias da sua vida.

[[v12-25-30]]

^<<v12-25-30,30>>^ E da parte do rei lhe foi dada subsistência vitalícia, uma pensão diária, durante os dias da sua vida.

'''

xref:012-2-reis/012-2-reis-024.adoc#v12-24-0[&#60; Capítulo Anterior] | <<v12-25-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-001.adoc#v13-1-0[Próximo Capítulo &#62;]