include::./index.adoc[]

[[v12-2-0]]
=== 2 Reis, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-2-1]]

^<<v12-2-1,1>>^ Quando estava o SENHOR para tomar Elias ao céu por um redemoinho, Elias partiu de Gilgal em companhia de Eliseu.

[[v12-2-2]]

^<<v12-2-2,2>>^ Disse Elias a Eliseu: Fica-te aqui, porque o SENHOR me enviou a Betel. Respondeu Eliseu: Tão certo como vive o SENHOR e vive a tua alma, não te deixarei. E, assim, desceram a Betel.

[[v12-2-3]]

^<<v12-2-3,3>>^ Então, os discípulos dos profetas que estavam em Betel saíram ao encontro de Eliseu e lhe disseram: Sabes que o SENHOR, hoje, tomará o teu senhor, elevando-o por sobre a tua cabeça? Respondeu ele: Também eu o sei; calai-vos.

[[v12-2-4]]

^<<v12-2-4,4>>^ Disse Elias a Eliseu: Fica-te aqui, porque o SENHOR me enviou a Jericó. Porém ele disse: Tão certo como vive o SENHOR e vive a tua alma, não te deixarei. E, assim, foram a Jericó.

[[v12-2-5]]

^<<v12-2-5,5>>^ Então, os discípulos dos profetas que estavam em Jericó se chegaram a Eliseu e lhe disseram: Sabes que o SENHOR, hoje, tomará o teu senhor, elevando-o por sobre a tua cabeça? Respondeu ele: Também eu o sei; calai-vos.

[[v12-2-6]]

^<<v12-2-6,6>>^ Disse-lhe, pois, Elias: Fica-te aqui, porque o SENHOR me enviou ao Jordão. Mas ele disse: Tão certo como vive o SENHOR e vive a tua alma, não te deixarei. E, assim, ambos foram juntos.

[[v12-2-7]]

^<<v12-2-7,7>>^ Foram cinquenta homens dos discípulos dos profetas e pararam a certa distância deles; eles ambos pararam junto ao Jordão.

[[v12-2-8]]

^<<v12-2-8,8>>^ Então, Elias tomou o seu manto, enrolou-o e feriu as águas, as quais se dividiram para os dois lados; e passaram ambos em seco.

[[v12-2-9]]

^<<v12-2-9,9>>^ Havendo eles passado, Elias disse a Eliseu: Pede-me o que queres que eu te faça, antes que seja tomado de ti. Disse Eliseu: Peço-te que me toque por herança porção dobrada do teu espírito.

[[v12-2-10]]

^<<v12-2-10,10>>^ Tornou-lhe Elias: Dura coisa pediste. Todavia, se me vires quando for tomado de ti, assim se te fará; porém, se não me vires, não se fará.

[[v12-2-11]]

^<<v12-2-11,11>>^ Indo eles andando e falando, eis que um carro de fogo, com cavalos de fogo, os separou um do outro; e Elias subiu ao céu num redemoinho.

[[v12-2-12]]

^<<v12-2-12,12>>^ O que vendo Eliseu, clamou: Meu pai, meu pai, carros de Israel e seus cavaleiros! E nunca mais o viu; e, tomando as suas vestes, rasgou-as em duas partes.

[[v12-2-13]]

^<<v12-2-13,13>>^ Então, levantou o manto que Elias lhe deixara cair e, voltando-se, pôs-se à borda do Jordão.

[[v12-2-14]]

^<<v12-2-14,14>>^ Tomou o manto que Elias lhe deixara cair, feriu as águas e disse: Onde está o SENHOR, Deus de Elias? Quando feriu ele as águas, elas se dividiram para um e outro lado, e Eliseu passou.

[[v12-2-15]]

^<<v12-2-15,15>>^ Vendo-o, pois, os discípulos dos profetas que estavam defronte, em Jericó, disseram: O espírito de Elias repousa sobre Eliseu. Vieram-lhe ao encontro e se prostraram diante dele em terra.

[[v12-2-16]]

^<<v12-2-16,16>>^ E lhe disseram: Eis que entre os teus servos há cinquenta homens valentes; ora, deixa-os ir em procura do teu senhor; pode ser que o Espírito do SENHOR o tenha levado e lançado nalgum dos montes ou nalgum dos vales. Porém ele respondeu: Não os envieis.

[[v12-2-17]]

^<<v12-2-17,17>>^ Mas eles apertaram com ele, até que, constrangido, lhes disse: Enviai. E enviaram cinquenta homens, que o procuraram três dias, porém não o acharam.

[[v12-2-18]]

^<<v12-2-18,18>>^ Então, voltaram para ele, pois permanecera em Jericó; e ele lhes disse: Não vos disse que não fôsseis?

[[v12-2-19]]

^<<v12-2-19,19>>^ Os homens da cidade disseram a Eliseu: Eis que é bem-situada esta cidade, como vê o meu senhor, porém as águas são más, e a terra é estéril.

[[v12-2-20]]

^<<v12-2-20,20>>^ Ele disse: Trazei-me um prato novo e ponde nele sal. E lho trouxeram.

[[v12-2-21]]

^<<v12-2-21,21>>^ Então, saiu ele ao manancial das águas e deitou sal nele; e disse: Assim diz o SENHOR: Tornei saudáveis estas águas; já não procederá daí morte nem esterilidade.

[[v12-2-22]]

^<<v12-2-22,22>>^ Ficaram, pois, saudáveis aquelas águas, até ao dia de hoje, segundo a palavra que Eliseu tinha dito.

[[v12-2-23]]

^<<v12-2-23,23>>^ Então, subiu dali a Betel; e, indo ele pelo caminho, uns rapazinhos saíram da cidade, e zombavam dele, e diziam-lhe: Sobe, calvo! Sobe, calvo!

[[v12-2-24]]

^<<v12-2-24,24>>^ Virando-se ele para trás, viu-os e os amaldiçoou em nome do SENHOR; então, duas ursas saíram do bosque e despedaçaram quarenta e dois deles.

[[v12-2-25]]

^<<v12-2-25,25>>^ Dali, foi ele para o monte Carmelo, de onde voltou para Samaria.

'''

xref:012-2-reis/012-2-reis-001.adoc#v12-1-0[&#60; Capítulo Anterior] | <<v12-2-0,Topo>> | xref:012-2-reis/012-2-reis-003.adoc#v12-3-0[Próximo Capítulo &#62;]