include::./index.adoc[]

[[v12-22-0]]
=== 2 Reis, 22
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-22-1]]

^<<v12-22-1,1>>^ Tinha Josias oito anos de idade quando começou a reinar e reinou trinta e um anos em Jerusalém. Sua mãe se chamava Jedida e era filha de Adaías, de Bozcate.

[[v12-22-2]]

^<<v12-22-2,2>>^ Fez ele o que era reto perante o SENHOR, andou em todo o caminho de Davi, seu pai, e não se desviou nem para a direita nem para a esquerda.

[[v12-22-3]]

^<<v12-22-3,3>>^ No décimo oitavo ano do seu reinado, o rei Josias mandou o escrivão Safã, filho de Azalias, filho de Mesulão, à Casa do SENHOR,

[[v12-22-4]]

^<<v12-22-4,4>>^ dizendo: Sobe a Hilquias, o sumo sacerdote, para que conte o dinheiro que se trouxe à Casa do SENHOR, o qual os guardas da porta ajuntaram do povo;

[[v12-22-5]]

^<<v12-22-5,5>>^ que o deem nas mãos dos que dirigem a obra e têm a seu cargo a Casa do SENHOR, para que paguem àqueles que fazem a obra que há na Casa do SENHOR, para repararem os estragos da casa:

[[v12-22-6]]

^<<v12-22-6,6>>^ aos carpinteiros, aos edificadores e aos pedreiros; e comprem madeira e pedras lavradas, para repararem os estragos da casa.

[[v12-22-7]]

^<<v12-22-7,7>>^ Porém não se pediu conta do dinheiro que se lhes entregara nas mãos, porquanto procediam com fidelidade.

[[v12-22-8]]

^<<v12-22-8,8>>^ Então, disse o sumo sacerdote Hilquias ao escrivão Safã: Achei o Livro da Lei na Casa do SENHOR. Hilquias entregou o livro a Safã, e este o leu.

[[v12-22-9]]

^<<v12-22-9,9>>^ Então, o escrivão Safã veio ter com o rei e lhe deu relatório, dizendo: Teus servos contaram o dinheiro que se achou na casa e o entregaram nas mãos dos que dirigem a obra e têm a seu cargo a Casa do SENHOR.

[[v12-22-10]]

^<<v12-22-10,10>>^ Relatou mais o escrivão Safã ao rei, dizendo: O sacerdote Hilquias me entregou um livro. E Safã o leu diante do rei.

[[v12-22-11]]

^<<v12-22-11,11>>^ Tendo o rei ouvido as palavras do Livro da Lei, rasgou as suas vestes.

[[v12-22-12]]

^<<v12-22-12,12>>^ Ordenou o rei a Hilquias, o sacerdote, a Aicão, filho de Safã, a Acbor, filho de Micaías, a Safã, o escrivão, e a Asaías, servo do rei, dizendo:

[[v12-22-13]]

^<<v12-22-13,13>>^ Ide e consultai o SENHOR por mim, pelo povo e por todo o Judá, acerca das palavras deste livro que se achou; porque grande é o furor do SENHOR que se acendeu contra nós, porquanto nossos pais não deram ouvidos às palavras deste livro, para fazerem segundo tudo quanto de nós está escrito.

[[v12-22-14]]

^<<v12-22-14,14>>^ Então, o sacerdote Hilquias, Aicão, Acbor, Safã e Asaías foram ter com a profetisa Hulda, mulher de Salum, o guarda-roupa, filho de Ticva, filho de Harás, e lhe falaram. Ela habitava na cidade baixa de Jerusalém.

[[v12-22-15]]

^<<v12-22-15,15>>^ Ela lhes disse: Assim diz o SENHOR, o Deus de Israel: Dizei ao homem que vos enviou a mim:

[[v12-22-16]]

^<<v12-22-16,16>>^ Assim diz o SENHOR: Eis que trarei males sobre este lugar e sobre os seus moradores, a saber, todas as palavras do livro que leu o rei de Judá.

[[v12-22-17]]

^<<v12-22-17,17>>^ Visto que me deixaram e queimaram incenso a outros deuses, para me provocarem à ira com todas as obras das suas mãos, o meu furor se acendeu contra este lugar e não se apagará.

[[v12-22-18]]

^<<v12-22-18,18>>^ Porém ao rei de Judá, que vos enviou a consultar o SENHOR, assim lhe direis: Assim diz o SENHOR, o Deus de Israel, acerca das palavras que ouviste:

[[v12-22-19]]

^<<v12-22-19,19>>^ Porquanto o teu coração se enterneceu, e te humilhaste perante o SENHOR, quando ouviste o que falei contra este lugar e contra os seus moradores, que seriam para assolação e para maldição, e rasgaste as tuas vestes, e choraste perante mim, também eu te ouvi, diz o SENHOR.

[[v12-22-20]]

^<<v12-22-20,20>>^ Pelo que, eis que eu te reunirei a teus pais, e tu serás recolhido em paz à tua sepultura, e os teus olhos não verão todo o mal que hei de trazer sobre este lugar. Então, levaram eles ao rei esta resposta.

'''

xref:012-2-reis/012-2-reis-021.adoc#v12-21-0[&#60; Capítulo Anterior] | <<v12-22-0,Topo>> | xref:012-2-reis/012-2-reis-023.adoc#v12-23-0[Próximo Capítulo &#62;]