include::./index.adoc[]

[[v12-24-0]]
=== 2 Reis, 24
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-24-1]]

^<<v12-24-1,1>>^ Nos dias de Jeoaquim, subiu Nabucodonosor, rei da Babilônia, contra ele, e ele, por três anos, ficou seu servo; então, se rebelou contra ele.

[[v12-24-2]]

^<<v12-24-2,2>>^ Enviou o SENHOR contra Jeoaquim bandos de caldeus, e bandos de siros, e de moabitas, e dos filhos de Amom; enviou-os contra Judá para o destruir, segundo a palavra que o SENHOR falara pelos profetas, seus servos.

[[v12-24-3]]

^<<v12-24-3,3>>^ Com efeito, isto sucedeu a Judá por mandado do SENHOR, que o removeu da sua presença, por causa de todos os pecados cometidos por Manassés,

[[v12-24-4]]

^<<v12-24-4,4>>^ como também por causa do sangue inocente que ele derramou, com o qual encheu a cidade de Jerusalém; por isso, o SENHOR não o quis perdoar.

[[v12-24-5]]

^<<v12-24-5,5>>^ Quanto aos mais atos de Jeoaquim e a tudo quanto fez, porventura, não estão escritos no Livro da História dos Reis de Judá?

[[v12-24-6]]

^<<v12-24-6,6>>^ Descansou Jeoaquim com seus pais; e Joaquim, seu filho, reinou em seu lugar.

[[v12-24-7]]

^<<v12-24-7,7>>^ O rei do Egito nunca mais saiu da sua terra; porque o rei da Babilônia tomou tudo quanto era dele, desde o ribeiro do Egito até ao rio Eufrates.

[[v12-24-8]]

^<<v12-24-8,8>>^ Tinha Joaquim dezoito anos de idade quando começou a reinar e reinou três meses em Jerusalém. Sua mãe se chamava Neústa e era filha de Elnatã, de Jerusalém.

[[v12-24-9]]

^<<v12-24-9,9>>^ Fez ele o que era mau perante o SENHOR, conforme tudo quanto fizera seu pai.

[[v12-24-10]]

^<<v12-24-10,10>>^ Naquele tempo, subiram os servos de Nabucodonosor, rei da Babilônia, a Jerusalém, e a cidade foi cercada.

[[v12-24-11]]

^<<v12-24-11,11>>^ Nabucodonosor, rei da Babilônia, veio à cidade, quando os seus servos a sitiavam.

[[v12-24-12]]

^<<v12-24-12,12>>^ Então, subiu Joaquim, rei de Judá, a encontrar-se com o rei da Babilônia, ele, sua mãe, seus servos, seus príncipes e seus oficiais; e o rei da Babilônia, no oitavo ano do seu reinado, o levou cativo.

[[v12-24-13]]

^<<v12-24-13,13>>^ Levou dali todos os tesouros da Casa do SENHOR e os tesouros da casa do rei; e, segundo tinha dito o SENHOR, cortou em pedaços todos os utensílios de ouro que fizera Salomão, rei de Israel, para o templo do SENHOR.

[[v12-24-14]]

^<<v12-24-14,14>>^ Transportou a toda a Jerusalém, todos os príncipes, todos os homens valentes, todos os artífices e ferreiros, ao todo dez mil; ninguém ficou, senão o povo pobre da terra.

[[v12-24-15]]

^<<v12-24-15,15>>^ Transferiu também a Joaquim para a Babilônia; a mãe do rei, as mulheres deste, seus oficiais e os homens principais da terra, ele os levou cativos de Jerusalém à Babilônia.

[[v12-24-16]]

^<<v12-24-16,16>>^ Todos os homens valentes, até sete mil, e os artífices, e ferreiros, até mil, todos eles destros na guerra, levou-os o rei da Babilônia cativos para a Babilônia.

[[v12-24-17]]

^<<v12-24-17,17>>^ O rei da Babilônia estabeleceu rei, em lugar de Joaquim, ao tio paterno deste, Matanias, de quem mudou o nome para Zedequias.

[[v12-24-18]]

^<<v12-24-18,18>>^ Tinha Zedequias a idade de vinte e um anos quando começou a reinar e reinou onze anos em Jerusalém. Sua mãe se chamava Hamutal e era filha de Jeremias, de Libna.

[[v12-24-19]]

^<<v12-24-19,19>>^ Fez ele o que era mau perante o SENHOR, conforme tudo quanto fizera Joaquim.

[[v12-24-20]]

^<<v12-24-20,20>>^ Assim sucedeu por causa da ira do SENHOR contra Jerusalém e contra Judá, a ponto de os rejeitar de sua presença. Zedequias rebelou-se contra o rei da Babilônia.

'''

xref:012-2-reis/012-2-reis-023.adoc#v12-23-0[&#60; Capítulo Anterior] | <<v12-24-0,Topo>> | xref:012-2-reis/012-2-reis-025.adoc#v12-25-0[Próximo Capítulo &#62;]