include::./index.adoc[]

[[v12-4-0]]
=== 2 Reis, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-4-1]]

^<<v12-4-1,1>>^ Certa mulher, das mulheres dos discípulos dos profetas, clamou a Eliseu, dizendo: Meu marido, teu servo, morreu; e tu sabes que ele temia ao SENHOR. É chegado o credor para levar os meus dois filhos para lhe serem escravos.

[[v12-4-2]]

^<<v12-4-2,2>>^ Eliseu lhe perguntou: Que te hei de fazer? Dize-me que é o que tens em casa. Ela respondeu: Tua serva não tem nada em casa, senão uma botija de azeite.

[[v12-4-3]]

^<<v12-4-3,3>>^ Então, disse ele: Vai, pede emprestadas vasilhas a todos os teus vizinhos; vasilhas vazias, não poucas.

[[v12-4-4]]

^<<v12-4-4,4>>^ Então, entra, e fecha a porta sobre ti e sobre teus filhos, e deita o teu azeite em todas aquelas vasilhas; põe à parte a que estiver cheia.

[[v12-4-5]]

^<<v12-4-5,5>>^ Partiu, pois, dele e fechou a porta sobre si e sobre seus filhos; estes lhe chegavam as vasilhas, e ela as enchia.

[[v12-4-6]]

^<<v12-4-6,6>>^ Cheias as vasilhas, disse ela a um dos filhos: Chega-me, aqui, mais uma vasilha. Mas ele respondeu: Não há mais vasilha nenhuma. E o azeite parou.

[[v12-4-7]]

^<<v12-4-7,7>>^ Então, foi ela e fez saber ao homem de Deus; ele disse: Vai, vende o azeite e paga a tua dívida; e, tu e teus filhos, vivei do resto.

[[v12-4-8]]

^<<v12-4-8,8>>^ Certo dia, passou Eliseu por Suném, onde se achava uma mulher rica, a qual o constrangeu a comer pão. Daí, todas as vezes que passava por lá, entrava para comer.

[[v12-4-9]]

^<<v12-4-9,9>>^ Ela disse a seu marido: Vejo que este que passa sempre por nós é santo homem de Deus.

[[v12-4-10]]

^<<v12-4-10,10>>^ Façamos-lhe, pois, em cima, um pequeno quarto, obra de pedreiro, e ponhamos-lhe nele uma cama, uma mesa, uma cadeira e um candeeiro; quando ele vier à nossa casa, retirar-se-á para ali.

[[v12-4-11]]

^<<v12-4-11,11>>^ Um dia, vindo ele para ali, retirou-se para o quarto e se deitou.

[[v12-4-12]]

^<<v12-4-12,12>>^ Então, disse ao seu moço Geazi: Chama esta sunamita. Chamando-a ele, ela se pôs diante do profeta.

[[v12-4-13]]

^<<v12-4-13,13>>^ Este dissera ao seu moço: Dize-lhe: Eis que tu nos tens tratado com muita abnegação; que se há de fazer por ti? Haverá alguma coisa de que se fale a teu favor ao rei ou ao comandante do exército? Ela respondeu: Habito no meio do meu povo.

[[v12-4-14]]

^<<v12-4-14,14>>^ Então, disse o profeta: Que se há de fazer por ela? Geazi respondeu: Ora, ela não tem filho, e seu marido é velho.

[[v12-4-15]]

^<<v12-4-15,15>>^ Disse Eliseu: Chama-a. Chamando-a ele, ela se pôs à porta.

[[v12-4-16]]

^<<v12-4-16,16>>^ Disse-lhe o profeta: Por este tempo, daqui a um ano, abraçarás um filho. Ela disse: Não, meu senhor, homem de Deus, não mintas à tua serva.

[[v12-4-17]]

^<<v12-4-17,17>>^ Concebeu a mulher e deu à luz um filho, no tempo determinado, quando fez um ano, segundo Eliseu lhe dissera.

[[v12-4-18]]

^<<v12-4-18,18>>^ Tendo crescido o menino, saiu, certo dia, a ter com seu pai, que estava com os segadores.

[[v12-4-19]]

^<<v12-4-19,19>>^ Disse a seu pai: Ai! A minha cabeça! Então, o pai disse ao seu moço: Leva-o a sua mãe.

[[v12-4-20]]

^<<v12-4-20,20>>^ Ele o tomou e o levou a sua mãe, sobre cujos joelhos ficou sentado até ao meio-dia, e morreu.

[[v12-4-21]]

^<<v12-4-21,21>>^ Subiu ela e o deitou sobre a cama do homem de Deus; fechou a porta e saiu.

[[v12-4-22]]

^<<v12-4-22,22>>^ Chamou a seu marido e lhe disse: Manda-me um dos moços e uma das jumentas, para que eu corra ao homem de Deus e volte.

[[v12-4-23]]

^<<v12-4-23,23>>^ Perguntou ele: Por que vais a ele hoje? Não é dia de Festa da Lua Nova nem sábado. Ela disse: Não faz mal.

[[v12-4-24]]

^<<v12-4-24,24>>^ Então, fez ela albardar a jumenta e disse ao moço: Guia e anda, não te detenhas no caminhar, senão quando eu to disser.

[[v12-4-25]]

^<<v12-4-25,25>>^ Partiu ela, pois, e foi ter com o homem de Deus, ao monte Carmelo. Vendo-a de longe o homem de Deus, disse a Geazi, seu moço: Eis aí a sunamita;

[[v12-4-26]]

^<<v12-4-26,26>>^ corre ao seu encontro e dize-lhe: Vai tudo bem contigo, com teu marido, com o menino? Ela respondeu: Tudo bem.

[[v12-4-27]]

^<<v12-4-27,27>>^ Chegando ela, pois, ao homem de Deus, ao monte, abraçou-lhe os pés. Então, se chegou Geazi para arrancá-la; mas o homem de Deus lhe disse: Deixa-a, porque a sua alma está em amargura, e o SENHOR mo encobriu e não mo manifestou.

[[v12-4-28]]

^<<v12-4-28,28>>^ Disse ela: Pedi eu a meu senhor algum filho? Não disse eu: Não me enganes?

[[v12-4-29]]

^<<v12-4-29,29>>^ Disse o profeta a Geazi: Cinge os lombos, toma o meu bordão contigo e vai. Se encontrares alguém, não o saúdes, e, se alguém te saudar, não lhe respondas; põe o meu bordão sobre o rosto do menino.

[[v12-4-30]]

^<<v12-4-30,30>>^ Porém disse a mãe do menino: Tão certo como vive o SENHOR e vive a tua alma, não te deixarei. Então, ele se levantou e a seguiu.

[[v12-4-31]]

^<<v12-4-31,31>>^ Geazi passou adiante deles e pôs o bordão sobre o rosto do menino; porém não houve nele voz nem sinal de vida; então, voltou a encontrar-se com Eliseu, e lhe deu aviso, e disse: O menino não despertou.

[[v12-4-32]]

^<<v12-4-32,32>>^ Tendo o profeta chegado à casa, eis que o menino estava morto sobre a cama.

[[v12-4-33]]

^<<v12-4-33,33>>^ Então, entrou, fechou a porta sobre eles ambos e orou ao SENHOR.

[[v12-4-34]]

^<<v12-4-34,34>>^ Subiu à cama, deitou-se sobre o menino e, pondo a sua boca sobre a boca dele, os seus olhos sobre os olhos dele e as suas mãos sobre as mãos dele, se estendeu sobre ele; e a carne do menino aqueceu.

[[v12-4-35]]

^<<v12-4-35,35>>^ Então, se levantou, e andou no quarto uma vez de lá para cá, e tornou a subir, e se estendeu sobre o menino; este espirrou sete vezes e abriu os olhos.

[[v12-4-36]]

^<<v12-4-36,36>>^ Então, chamou a Geazi e disse: Chama a sunamita. Ele a chamou, e, apresentando-se ela ao profeta, este lhe disse: Toma o teu filho.

[[v12-4-37]]

^<<v12-4-37,37>>^ Ela entrou, lançou-se aos pés dele e prostrou-se em terra; tomou o seu filho e saiu.

[[v12-4-38]]

^<<v12-4-38,38>>^ Voltou Eliseu para Gilgal. Havia fome naquela terra, e, estando os discípulos dos profetas assentados diante dele, disse ao seu moço: Põe a panela grande ao lume e faze um cozinhado para os discípulos dos profetas.

[[v12-4-39]]

^<<v12-4-39,39>>^ Então, saiu um ao campo a apanhar ervas e achou uma trepadeira silvestre; e, colhendo dela, encheu a sua capa de colocíntidas; voltou e cortou-as em pedaços, pondo-os na panela, visto que não as conheciam.

[[v12-4-40]]

^<<v12-4-40,40>>^ Depois, deram de comer aos homens. Enquanto comiam do cozinhado, exclamaram: Morte na panela, ó homem de Deus! E não puderam comer.

[[v12-4-41]]

^<<v12-4-41,41>>^ Porém ele disse: Trazei farinha. Ele a deitou na panela e disse: Tira de comer para o povo. E já não havia mal nenhum na panela.

[[v12-4-42]]

^<<v12-4-42,42>>^ Veio um homem de Baal-Salisa e trouxe ao homem de Deus pães das primícias, vinte pães de cevada, e espigas verdes no seu alforje. Disse Eliseu: Dá ao povo para que coma.

[[v12-4-43]]

^<<v12-4-43,43>>^ Porém seu servo lhe disse: Como hei de eu pôr isto diante de cem homens? Ele tornou a dizer: Dá-o ao povo, para que coma; porque assim diz o SENHOR: Comerão, e sobejará.

[[v12-4-44]]

^<<v12-4-44,44>>^ Então, lhos pôs diante; comeram, e ainda sobrou, conforme a palavra do SENHOR.

'''

xref:012-2-reis/012-2-reis-003.adoc#v12-3-0[&#60; Capítulo Anterior] | <<v12-4-0,Topo>> | xref:012-2-reis/012-2-reis-005.adoc#v12-5-0[Próximo Capítulo &#62;]