include::./index.adoc[]

[[v12-19-0]]
=== 2 Reis, 19
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-19-1]]

^<<v12-19-1,1>>^ Tendo o rei Ezequias ouvido isto, rasgou as suas vestes, cobriu-se de pano de saco e entrou na Casa do SENHOR.

[[v12-19-2]]

^<<v12-19-2,2>>^ Então, enviou a Eliaquim, o mordomo, a Sebna, o escrivão, e os anciãos dos sacerdotes cobertos de pano de saco, ao profeta Isaías, filho de Amoz;

[[v12-19-3]]

^<<v12-19-3,3>>^ os quais lhe disseram: Assim diz Ezequias: Este dia é dia de angústia, de disciplina e de opróbrio; porque filhos são chegados à hora de nascer, e não há força para dá-los à luz.

[[v12-19-4]]

^<<v12-19-4,4>>^ Porventura, o SENHOR, teu Deus, terá ouvido todas as palavras de Rabsaqué, a quem o rei da Assíria, seu senhor, enviou para afrontar o Deus vivo, e repreenderá as palavras que ouviu; ergue, pois, orações pelos que ainda subsistem.

[[v12-19-5]]

^<<v12-19-5,5>>^ Foram, pois, os servos do rei Ezequias a ter com Isaías;

[[v12-19-6]]

^<<v12-19-6,6>>^ Isaías lhes disse: Dizei isto a vosso senhor: Assim diz o SENHOR: Não temas por causa das palavras que ouviste, com as quais os servos do rei da Assíria blasfemaram de mim.

[[v12-19-7]]

^<<v12-19-7,7>>^ Eis que meterei nele um espírito, e ele, ao ouvir certo rumor, voltará para a sua terra; e nela eu o farei cair morto à espada.

[[v12-19-8]]

^<<v12-19-8,8>>^ Voltou, pois, Rabsaqué e encontrou o rei da Assíria pelejando contra Libna; porque ouvira que o rei já se havia retirado de Laquis.

[[v12-19-9]]

^<<v12-19-9,9>>^ O rei ouviu que a respeito de Tiraca, rei da Etiópia, se dizia: Eis saiu para guerrear contra ti. Assim, tornou a enviar mensageiros a Ezequias, dizendo:

[[v12-19-10]]

^<<v12-19-10,10>>^ Assim falareis a Ezequias, rei de Judá: Não te engane o teu Deus, em quem confias, dizendo: Jerusalém não será entregue nas mãos do rei da Assíria.

[[v12-19-11]]

^<<v12-19-11,11>>^ Já tens ouvido o que fizeram os reis da Assíria a todas as terras, como as destruíram totalmente; e crês tu que te livrarias?

[[v12-19-12]]

^<<v12-19-12,12>>^ Porventura, os deuses das nações livraram os povos que meus pais destruíram, Gozã, Harã e Rezefe e os filhos de Éden, que estavam em Telassar?

[[v12-19-13]]

^<<v12-19-13,13>>^ Onde está o rei de Hamate, e o rei de Arpade, e o rei da cidade de Sefarvaim, de Hena e de Iva?

[[v12-19-14]]

^<<v12-19-14,14>>^ Tendo Ezequias recebido a carta das mãos dos mensageiros, leu-a; então, subiu à Casa do SENHOR, estendeu-a perante o Senhor

[[v12-19-15]]

^<<v12-19-15,15>>^ e orou perante o SENHOR, dizendo: Ó SENHOR, Deus de Israel, que estás entronizado acima dos querubins, tu somente és o Deus de todos os reinos da terra; tu fizeste os céus e a terra.

[[v12-19-16]]

^<<v12-19-16,16>>^ Inclina, ó SENHOR, o ouvido e ouve; abre, SENHOR, os olhos e vê; ouve todas as palavras de Senaqueribe, as quais ele enviou para afrontar o Deus vivo.

[[v12-19-17]]

^<<v12-19-17,17>>^ Verdade é, SENHOR, que os reis da Assíria assolaram todas as nações e suas terras

[[v12-19-18]]

^<<v12-19-18,18>>^ e lançaram no fogo os deuses deles, porque deuses não eram, senão obra de mãos de homens, madeira e pedra; por isso, os destruíram.

[[v12-19-19]]

^<<v12-19-19,19>>^ Agora, pois, ó SENHOR, nosso Deus, livra-nos das suas mãos, para que todos os reinos da terra saibam que só tu és o SENHOR Deus.

[[v12-19-20]]

^<<v12-19-20,20>>^ Então, Isaías, filho de Amoz, mandou dizer a Ezequias: Assim diz o SENHOR, o Deus de Israel: Quanto ao que me pediste acerca de Senaqueribe, rei da Assíria, eu te ouvi,

[[v12-19-21]]

^<<v12-19-21,21>>^ e esta é a palavra que o SENHOR falou a respeito dele: A virgem, filha de Sião, te despreza e zomba de ti; a filha de Jerusalém meneia a cabeça por detrás de ti.

[[v12-19-22]]

^<<v12-19-22,22>>^ A quem afrontaste e de quem blasfemaste? E contra quem alçaste a voz e arrogantemente ergueste os olhos? Contra o Santo de Israel.

[[v12-19-23]]

^<<v12-19-23,23>>^ Por meio dos teus mensageiros, afrontaste o SENHOR e disseste: Com a multidão dos meus carros subi ao cimo dos montes, ao mais interior do Líbano; deitarei abaixo os seus altos cedros e seus ciprestes escolhidos, chegarei a suas pousadas extremas, ao seu denso e fértil pomar.

[[v12-19-24]]

^<<v12-19-24,24>>^ Eu mesmo cavei, e bebi as águas de estrangeiros, e com as plantas de meus pés sequei todos os rios do Egito.

[[v12-19-25]]

^<<v12-19-25,25>>^ Acaso, não ouviste que já há muito dispus eu estas coisas, já desde os dias remotos o tinha planejado? Agora, porém, as faço executar e eu quis que tu reduzisses a montões de ruínas as cidades fortificadas.

[[v12-19-26]]

^<<v12-19-26,26>>^ Por isso, os seus moradores, debilitados, andaram cheios de temor e envergonhados; tornaram-se como a erva do campo, e a erva verde, e o capim dos telhados, e o cereal queimado antes de amadurecer.

[[v12-19-27]]

^<<v12-19-27,27>>^ Mas eu conheço o teu assentar, e o teu sair, e o teu entrar, e o teu furor contra mim.

[[v12-19-28]]

^<<v12-19-28,28>>^ Por causa do teu furor contra mim e porque a tua arrogância subiu até aos meus ouvidos, eis que porei o meu anzol no teu nariz e o meu freio na tua boca e te farei voltar pelo caminho por onde vieste.

[[v12-19-29]]

^<<v12-19-29,29>>^ Isto te será por sinal: este ano, se comerá o que espontaneamente nascer e, no segundo ano, o que daí proceder; no terceiro ano, porém, semeai, e colhei, e plantai vinhas, e comei os seus frutos.

[[v12-19-30]]

^<<v12-19-30,30>>^ O que escapou da casa de Judá e ficou de resto tornará a lançar raízes para baixo e dará fruto por cima;

[[v12-19-31]]

^<<v12-19-31,31>>^ porque de Jerusalém sairá o restante, e do monte Sião, o que escapou. O zelo do SENHOR fará isto.

[[v12-19-32]]

^<<v12-19-32,32>>^ Pelo que assim diz o SENHOR acerca do rei da Assíria: Não entrará nesta cidade, nem lançará nela flecha alguma, não virá perante ela com escudo, nem há de levantar tranqueiras contra ela.

[[v12-19-33]]

^<<v12-19-33,33>>^ Pelo caminho por onde vier, por esse voltará; mas, nesta cidade, não entrará, diz o SENHOR.

[[v12-19-34]]

^<<v12-19-34,34>>^ Porque eu defenderei esta cidade, para a livrar, por amor de mim e por amor de meu servo Davi.

[[v12-19-35]]

^<<v12-19-35,35>>^ Então, naquela mesma noite, saiu o Anjo do SENHOR e feriu, no arraial dos assírios, cento e oitenta e cinco mil; e, quando se levantaram os restantes pela manhã, eis que todos estes eram cadáveres.

[[v12-19-36]]

^<<v12-19-36,36>>^ Retirou-se, pois, Senaqueribe, rei da Assíria, e se foi; voltou e ficou em Nínive.

[[v12-19-37]]

^<<v12-19-37,37>>^ Sucedeu que, estando ele a adorar na casa de Nisroque, seu deus, Adrameleque e Sarezer, seus filhos, o feriram à espada; e fugiram para a terra de Ararate; e Esar-Hadom, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-018.adoc#v12-18-0[&#60; Capítulo Anterior] | <<v12-19-0,Topo>> | xref:012-2-reis/012-2-reis-020.adoc#v12-20-0[Próximo Capítulo &#62;]