include::./index.adoc[]

[[v12-8-0]]
=== 2 Reis, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-8-1]]

^<<v12-8-1,1>>^ Falou Eliseu àquela mulher cujo filho ele restaurara à vida, dizendo: Levanta-te, vai com os de tua casa e mora onde puderes; porque o SENHOR chamou a fome, a qual virá sobre a terra por sete anos.

[[v12-8-2]]

^<<v12-8-2,2>>^ Levantou-se a mulher e fez segundo a palavra do homem de Deus: saiu com os de sua casa e habitou por sete anos na terra dos filisteus.

[[v12-8-3]]

^<<v12-8-3,3>>^ Ao cabo dos sete anos, a mulher voltou da terra dos filisteus e saiu a clamar ao rei pela sua casa e pelas suas terras.

[[v12-8-4]]

^<<v12-8-4,4>>^ Ora, o rei falava a Geazi, moço do homem de Deus, dizendo: Conta-me, peço-te, todas as grandes obras que Eliseu tem feito.

[[v12-8-5]]

^<<v12-8-5,5>>^ Contava ele ao rei como Eliseu restaurara à vida a um morto, quando a mulher cujo filho ele havia restaurado à vida clamou ao rei pela sua casa e pelas suas terras; então, disse Geazi: Ó rei, meu senhor, esta é a mulher, e este, o seu filho, a quem Eliseu restaurou à vida.

[[v12-8-6]]

^<<v12-8-6,6>>^ Interrogou o rei a mulher, e ela lhe contou tudo. Então, o rei lhe deu um oficial, dizendo: Faze restituir-se-lhe tudo quanto era seu e todas as rendas do campo desde o dia em que deixou a terra até agora.

[[v12-8-7]]

^<<v12-8-7,7>>^ Veio Eliseu a Damasco. Estava doente Ben-Hadade, rei da Síria; e lhe anunciaram, dizendo: O homem de Deus é chegado aqui.

[[v12-8-8]]

^<<v12-8-8,8>>^ Então, o rei disse a Hazael: Toma presentes contigo, e vai encontrar-te com o homem de Deus, e, por seu intermédio, pergunta ao SENHOR, dizendo: Sararei eu desta doença?

[[v12-8-9]]

^<<v12-8-9,9>>^ Foi, pois, Hazael encontrar-se com ele, levando consigo um presente, a saber, quarenta camelos carregados de tudo que era bom de Damasco; chegou, apresentou-se diante dele e disse: Teu filho Ben-Hadade, rei da Síria, me enviou a perguntar-te: Sararei eu desta doença?

[[v12-8-10]]

^<<v12-8-10,10>>^ Eliseu lhe respondeu: Vai e dize-lhe: Certamente, sararás. Porém o SENHOR me mostrou que ele morrerá.

[[v12-8-11]]

^<<v12-8-11,11>>^ Olhou Eliseu para Hazael e tanto lhe fitou os olhos, que este ficou embaraçado; e chorou o homem de Deus.

[[v12-8-12]]

^<<v12-8-12,12>>^ Então, disse Hazael: Por que chora o meu senhor? Ele respondeu: Porque sei o mal que hás de fazer aos filhos de Israel; deitarás fogo às suas fortalezas, matarás à espada os seus jovens, esmagarás os seus pequeninos e rasgarás o ventre de suas mulheres grávidas.

[[v12-8-13]]

^<<v12-8-13,13>>^ Tornou Hazael: Pois que é teu servo, este cão, para fazer tão grandes coisas? Respondeu Eliseu: O SENHOR me mostrou que tu hás de ser rei da Síria.

[[v12-8-14]]

^<<v12-8-14,14>>^ Então, deixou a Eliseu e veio a seu senhor, o qual lhe perguntou: Que te disse Eliseu? Respondeu ele: Disse-me que certamente sararás.

[[v12-8-15]]

^<<v12-8-15,15>>^ No dia seguinte, Hazael tomou um cobertor, molhou-o em água e o estendeu sobre o rosto do rei até que morreu; e Hazael reinou em seu lugar.

[[v12-8-16]]

^<<v12-8-16,16>>^ No ano quinto do reinado de Jorão, filho de Acabe, rei de Israel, reinando ainda Josafá em Judá, começou a reinar Jeorão, filho de Josafá, rei de Judá.

[[v12-8-17]]

^<<v12-8-17,17>>^ Era ele da idade de trinta e dois anos quando começou a reinar e reinou oito anos em Jerusalém.

[[v12-8-18]]

^<<v12-8-18,18>>^ Andou nos caminhos dos reis de Israel, como também fizeram os da casa de Acabe, porque a filha deste era sua mulher; e fez o que era mau perante o SENHOR.

[[v12-8-19]]

^<<v12-8-19,19>>^ Porém o SENHOR não quis destruir a Judá por amor de Davi, seu servo, segundo a promessa que lhe havia feito de lhe dar sempre uma lâmpada e a seus filhos.

[[v12-8-20]]

^<<v12-8-20,20>>^ Nos dias de Jeorão, se revoltaram os edomitas contra o poder de Judá e constituíram o seu próprio rei.

[[v12-8-21]]

^<<v12-8-21,21>>^ Pelo que Jeorão passou a Zair, e todos os carros, com ele; ele se levantou de noite e feriu os edomitas que o cercavam e os capitães dos carros; o povo de Jeorão, porém, fugiu para as suas tendas.

[[v12-8-22]]

^<<v12-8-22,22>>^ Assim se rebelou Edom para livrar-se do poder de Judá até ao dia de hoje; ao mesmo tempo, se rebelou também Libna.

[[v12-8-23]]

^<<v12-8-23,23>>^ Quanto aos mais atos de Jeorão e a tudo quanto fez, porventura, não estão escritos no Livro da História dos Reis de Judá?

[[v12-8-24]]

^<<v12-8-24,24>>^ Descansou Jeorão com seus pais e com eles foi sepultado na Cidade de Davi; e Acazias, seu filho, reinou em seu lugar.

[[v12-8-25]]

^<<v12-8-25,25>>^ No décimo segundo ano de Jorão, filho de Acabe, rei de Israel, começou a reinar Acazias, filho de Jeorão, rei de Judá.

[[v12-8-26]]

^<<v12-8-26,26>>^ Era Acazias de vinte e dois anos de idade quando começou a reinar e reinou um ano em Jerusalém. Sua mãe, filha de Onri, rei de Israel, chamava-se Atalia.

[[v12-8-27]]

^<<v12-8-27,27>>^ Ele andou no caminho da casa de Acabe e fez o que era mau perante o SENHOR, como a casa de Acabe, porque era genro da casa de Acabe.

[[v12-8-28]]

^<<v12-8-28,28>>^ Foi com Jorão, filho de Acabe, a Ramote-Gileade, à peleja contra Hazael, rei da Síria; e os siros feriram Jorão.

[[v12-8-29]]

^<<v12-8-29,29>>^ Então, voltou o rei Jorão para Jezreel, para curar-se das feridas que os siros lhe fizeram em Ramá, quando pelejou contra Hazael, rei da Síria; e desceu Acazias, filho de Jeorão, rei de Judá, para ver a Jorão, filho de Acabe, em Jezreel, porquanto estava doente.

'''

xref:012-2-reis/012-2-reis-007.adoc#v12-7-0[&#60; Capítulo Anterior] | <<v12-8-0,Topo>> | xref:012-2-reis/012-2-reis-009.adoc#v12-9-0[Próximo Capítulo &#62;]