include::./index.adoc[]

[[v12-7-0]]
=== 2 Reis, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-7-1]]

^<<v12-7-1,1>>^ Então, disse Eliseu: Ouvi a palavra do SENHOR; assim diz o SENHOR: Amanhã, a estas horas mais ou menos, dar-se-á um alqueire de flor de farinha por um siclo, e dois de cevada, por um siclo, à porta de Samaria.

[[v12-7-2]]

^<<v12-7-2,2>>^ Porém o capitão a cujo braço o rei se apoiava respondeu ao homem de Deus: Ainda que o SENHOR fizesse janelas no céu, poderia suceder isso? Disse o profeta: Eis que tu o verás com os teus olhos, porém disso não comerás.

[[v12-7-3]]

^<<v12-7-3,3>>^ Quatro homens leprosos estavam à entrada da porta, os quais disseram uns aos outros: Para que estaremos nós aqui sentados até morrermos?

[[v12-7-4]]

^<<v12-7-4,4>>^ Se dissermos: entremos na cidade, há fome na cidade, e morreremos lá; se ficarmos sentados aqui, também morreremos. Vamos, pois, agora, e demos conosco no arraial dos siros; se nos deixarem viver, viveremos; se nos matarem, tão somente morreremos.

[[v12-7-5]]

^<<v12-7-5,5>>^ Levantaram-se ao anoitecer para se dirigirem ao arraial dos siros; e, tendo chegado à entrada do arraial, eis que não havia lá ninguém.

[[v12-7-6]]

^<<v12-7-6,6>>^ Porque o Senhor fizera ouvir no arraial dos siros ruído de carros e de cavalos e o ruído de um grande exército; de maneira que disseram uns aos outros: Eis que o rei de Israel alugou contra nós os reis dos heteus e os reis dos egípcios, para virem contra nós.

[[v12-7-7]]

^<<v12-7-7,7>>^ Pelo que se levantaram, e, fugindo ao anoitecer, deixaram as suas tendas, os seus cavalos, e os seus jumentos, e o arraial como estava; e fugiram para salvar a sua vida.

[[v12-7-8]]

^<<v12-7-8,8>>^ Chegando, pois, aqueles leprosos à entrada do arraial, entraram numa tenda, e comeram, e beberam, e tomaram dali prata, e ouro, e vestes, e se foram, e os esconderam; voltaram, e entraram em outra tenda, e dali também tomaram alguma coisa, e a esconderam.

[[v12-7-9]]

^<<v12-7-9,9>>^ Então, disseram uns para os outros: Não fazemos bem; este dia é dia de boas-novas, e nós nos calamos; se esperarmos até à luz da manhã, seremos tidos por culpados; agora, pois, vamos e o anunciemos à casa do rei.

[[v12-7-10]]

^<<v12-7-10,10>>^ Vieram, pois, e bradaram aos porteiros da cidade, e lhes anunciaram, dizendo: Fomos ao arraial dos siros, e eis que lá não havia ninguém, voz de ninguém, mas somente cavalos e jumentos atados, e as tendas como estavam.

[[v12-7-11]]

^<<v12-7-11,11>>^ Então, os porteiros gritaram e fizeram anunciar a nova no interior da casa do rei.

[[v12-7-12]]

^<<v12-7-12,12>>^ Levantou-se o rei de noite e disse a seus servos: Agora, eu vos direi o que é que os siros nos fizeram. Bem sabem eles que estamos esfaimados; por isso, saíram do arraial, a esconder-se pelo campo, dizendo: Quando saírem da cidade, então, os tomaremos vivos e entraremos nela.

[[v12-7-13]]

^<<v12-7-13,13>>^ Então, um dos seus servos respondeu e disse: Tomem-se, pois, cinco dos cavalos que ainda restam na cidade, pois toda a multidão de Israel que ficou aqui de resto terá a mesma sorte da multidão dos israelitas que já pereceram; enviemos homens e vejamos.

[[v12-7-14]]

^<<v12-7-14,14>>^ Tomaram, pois, dois carros com cavalos; e o rei enviou os homens após o exército dos siros, dizendo: Ide e vede.

[[v12-7-15]]

^<<v12-7-15,15>>^ Foram após eles até ao Jordão; e eis que todo o caminho estava cheio de vestes e de armas que os siros, na sua pressa, tinham lançado fora. Voltaram os mensageiros e o anunciaram ao rei.

[[v12-7-16]]

^<<v12-7-16,16>>^ Então, saiu o povo e saqueou o arraial dos siros; e, assim, se vendia um alqueire de flor de farinha por um siclo, e dois de cevada, por um siclo, segundo a palavra do SENHOR.

[[v12-7-17]]

^<<v12-7-17,17>>^ Dera o rei a guarda da porta ao capitão em cujo braço se apoiara, mas o povo o atropelou na porta, e ele morreu, como falara o homem de Deus, o que falou quando o rei descera a ele.

[[v12-7-18]]

^<<v12-7-18,18>>^ Assim se cumpriu o que falara o homem de Deus ao rei: Amanhã, a estas horas mais ou menos, vender-se-ão dois alqueires de cevada por um siclo, e um de flor de farinha, por um siclo, à porta de Samaria.

[[v12-7-19]]

^<<v12-7-19,19>>^ Aquele capitão respondera ao homem de Deus: Ainda que o SENHOR fizesse janelas no céu, poderia suceder isso, segundo essa palavra? Dissera o profeta: Eis que tu o verás com os teus olhos, porém disso não comerás.

[[v12-7-20]]

^<<v12-7-20,20>>^ Assim lhe sucedeu, porque o povo o atropelou na porta, e ele morreu.

'''

xref:012-2-reis/012-2-reis-006.adoc#v12-6-0[&#60; Capítulo Anterior] | <<v12-7-0,Topo>> | xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[Próximo Capítulo &#62;]