include::./index.adoc[]

[[v12-16-0]]
=== 2 Reis, 16
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-16-1]]

^<<v12-16-1,1>>^ No décimo sétimo ano de Peca, filho de Remalias, começou a reinar Acaz, filho de Jotão, rei de Judá.

[[v12-16-2]]

^<<v12-16-2,2>>^ Tinha Acaz vinte anos de idade quando começou a reinar e reinou dezesseis anos em Jerusalém. Não fez o que era reto perante o SENHOR, seu Deus, como Davi, seu pai.

[[v12-16-3]]

^<<v12-16-3,3>>^ Porque andou no caminho dos reis de Israel e até queimou a seu filho como sacrifício, segundo as abominações dos gentios, que o SENHOR lançara de diante dos filhos de Israel.

[[v12-16-4]]

^<<v12-16-4,4>>^ Também sacrificou e queimou incenso nos altos e nos outeiros, como também debaixo de toda árvore frondosa.

[[v12-16-5]]

^<<v12-16-5,5>>^ Então, subiu Rezim, rei da Síria, com Peca, filho de Remalias, rei de Israel, a Jerusalém para pelejarem contra ela; cercaram Acaz, porém não puderam prevalecer contra ele.

[[v12-16-6]]

^<<v12-16-6,6>>^ Naquele tempo, Rezim, rei da Síria, restituiu Elate à Síria e lançou fora dela os judeus; os siros vieram a Elate e ficaram habitando ali até ao dia de hoje.

[[v12-16-7]]

^<<v12-16-7,7>>^ Acaz enviou mensageiros a Tiglate-Pileser, rei da Assíria, dizendo: Eu sou teu servo e teu filho; sobe e livra-me do poder do rei da Síria e do poder do rei de Israel, que se levantam contra mim.

[[v12-16-8]]

^<<v12-16-8,8>>^ Tomou Acaz a prata e o ouro que se acharam na Casa do SENHOR e nos tesouros da casa do rei e mandou de presente ao rei da Assíria.

[[v12-16-9]]

^<<v12-16-9,9>>^ O rei da Assíria lhe deu ouvidos, subiu contra Damasco, tomou-a, levou o povo para Quir e matou a Rezim.

[[v12-16-10]]

^<<v12-16-10,10>>^ Então, o rei Acaz foi a Damasco, a encontrar-se com Tiglate-Pileser, rei da Assíria; e, vendo ali um altar, enviou dele ao sacerdote Urias a planta e o modelo, segundo toda a sua obra.

[[v12-16-11]]

^<<v12-16-11,11>>^ Urias, o sacerdote, edificou um altar segundo tudo o que o rei Acaz tinha ordenado de Damasco; assim o fez o sacerdote Urias, antes que o rei Acaz viesse de Damasco.

[[v12-16-12]]

^<<v12-16-12,12>>^ Vindo, pois, de Damasco o rei, viu o altar, chegou-se a ele e nele sacrificou.

[[v12-16-13]]

^<<v12-16-13,13>>^ Queimou o seu holocausto e a sua oferta de manjares, derramou a sua libação e aspergiu o sangue das suas ofertas pacíficas naquele altar.

[[v12-16-14]]

^<<v12-16-14,14>>^ Porém o altar de bronze, que estava perante o SENHOR, tirou ele de diante da casa, de entre o seu altar e a Casa do SENHOR e o pôs ao lado do seu altar, do lado norte.

[[v12-16-15]]

^<<v12-16-15,15>>^ Ordenou também o rei Acaz ao sacerdote Urias, dizendo: Queima, no grande altar, o holocausto da manhã, como também a oferta de manjares da tarde, e o holocausto do rei, e a sua oferta de manjares, e o holocausto de todo o povo da terra, e a sua oferta de manjares, e as suas libações; todo sangue dos holocaustos e todo sangue dos sacrifícios aspergirás nele; porém o altar de bronze ficará para a minha deliberação posterior.

[[v12-16-16]]

^<<v12-16-16,16>>^ Fez Urias, o sacerdote, segundo tudo quanto o rei Acaz lhe ordenara.

[[v12-16-17]]

^<<v12-16-17,17>>^ O rei Acaz cortou os painéis dos suportes, e de cima deles tomou a pia, e o mar, tirou-o de sobre os bois de bronze, que estavam debaixo dele, e o pôs sobre um pavimento de pedra.

[[v12-16-18]]

^<<v12-16-18,18>>^ Também o passadiço coberto para uso no sábado, que edificaram na casa, e a entrada real pelo lado de fora retirou da Casa do SENHOR, por causa do rei da Assíria.

[[v12-16-19]]

^<<v12-16-19,19>>^ Quanto aos mais atos de Acaz e ao que fez, porventura, não estão escritos no Livro da História dos Reis de Judá?

[[v12-16-20]]

^<<v12-16-20,20>>^ Descansou Acaz com seus pais e foi sepultado junto a seus pais, na Cidade de Davi; e Ezequias, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-015.adoc#v12-15-0[&#60; Capítulo Anterior] | <<v12-16-0,Topo>> | xref:012-2-reis/012-2-reis-017.adoc#v12-17-0[Próximo Capítulo &#62;]