include::./index.adoc[]

[[v12-17-0]]
=== 2 Reis, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-17-1]]

^<<v12-17-1,1>>^ No ano duodécimo de Acaz, rei de Judá, começou a reinar Oseias, filho de Elá; e reinou sobre Israel, em Samaria, nove anos.

[[v12-17-2]]

^<<v12-17-2,2>>^ Fez o que era mau perante o SENHOR; contudo, não como os reis de Israel que foram antes dele.

[[v12-17-3]]

^<<v12-17-3,3>>^ Contra ele subiu Salmaneser, rei da Assíria; Oseias ficou sendo servo dele e lhe pagava tributo.

[[v12-17-4]]

^<<v12-17-4,4>>^ Porém o rei da Assíria achou Oseias em conspiração, porque enviara mensageiros a Sô, rei do Egito, e não pagava tributo ao rei da Assíria, como dantes fazia de ano em ano; por isso, o rei da Assíria o encerrou em grilhões, num cárcere.

[[v12-17-5]]

^<<v12-17-5,5>>^ Porque o rei da Assíria passou por toda a terra, subiu a Samaria e a sitiou por três anos.

[[v12-17-6]]

^<<v12-17-6,6>>^ No ano nono de Oseias, o rei da Assíria tomou a Samaria e transportou a Israel para a Assíria; e os fez habitar em Hala, junto a Habor e ao rio Gozã, e nas cidades dos medos.

[[v12-17-7]]

^<<v12-17-7,7>>^ Tal sucedeu porque os filhos de Israel pecaram contra o SENHOR, seu Deus, que os fizera subir da terra do Egito, de debaixo da mão de Faraó, rei do Egito; e temeram a outros deuses.

[[v12-17-8]]

^<<v12-17-8,8>>^ Andaram nos estatutos das nações que o SENHOR lançara de diante dos filhos de Israel e nos costumes estabelecidos pelos reis de Israel.

[[v12-17-9]]

^<<v12-17-9,9>>^ Os filhos de Israel fizeram contra o SENHOR, seu Deus, o que não era reto; edificaram para si altos em todas as suas cidades, desde as atalaias dos vigias até à cidade fortificada.

[[v12-17-10]]

^<<v12-17-10,10>>^ Levantaram para si colunas e postes-ídolos, em todos os altos outeiros e debaixo de todas as árvores frondosas.

[[v12-17-11]]

^<<v12-17-11,11>>^ Queimaram ali incenso em todos os altos, como as nações que o SENHOR expulsara de diante deles; cometeram ações perversas para provocarem o SENHOR à ira

[[v12-17-12]]

^<<v12-17-12,12>>^ e serviram os ídolos, dos quais o SENHOR lhes tinha dito: Não fareis estas coisas.

[[v12-17-13]]

^<<v12-17-13,13>>^ O SENHOR advertiu a Israel e a Judá por intermédio de todos os profetas e de todos os videntes, dizendo: Voltai-vos dos vossos maus caminhos e guardai os meus mandamentos e os meus estatutos, segundo toda a Lei que prescrevi a vossos pais e que vos enviei por intermédio dos meus servos, os profetas.

[[v12-17-14]]

^<<v12-17-14,14>>^ Porém não deram ouvidos; antes, se tornaram obstinados, de dura cerviz como seus pais, que não creram no SENHOR, seu Deus.

[[v12-17-15]]

^<<v12-17-15,15>>^ Rejeitaram os estatutos e a aliança que fizera com seus pais, como também as suas advertências com que protestara contra eles; seguiram os ídolos, e se tornaram vãos, e seguiram as nações que estavam em derredor deles, das quais o SENHOR lhes havia ordenado que não as imitassem.

[[v12-17-16]]

^<<v12-17-16,16>>^ Desprezaram todos os mandamentos do SENHOR, seu Deus, e fizeram para si imagens de fundição, dois bezerros; fizeram um poste-ídolo, e adoraram todo o exército do céu, e serviram a Baal.

[[v12-17-17]]

^<<v12-17-17,17>>^ Também queimaram a seus filhos e a suas filhas como sacrifício, deram-se à prática de adivinhações e criam em agouros; e venderam-se para fazer o que era mau perante o SENHOR, para o provocarem à ira.

[[v12-17-18]]

^<<v12-17-18,18>>^ Pelo que o SENHOR muito se indignou contra Israel e o afastou da sua presença; e nada mais ficou, senão a tribo de Judá.

[[v12-17-19]]

^<<v12-17-19,19>>^ Também Judá não guardou os mandamentos do SENHOR, seu Deus; antes, andaram nos costumes que Israel introduziu.

[[v12-17-20]]

^<<v12-17-20,20>>^ Pelo que o SENHOR rejeitou a toda a descendência de Israel, e os afligiu, e os entregou nas mãos dos despojadores, até que os expulsou da sua presença.

[[v12-17-21]]

^<<v12-17-21,21>>^ Pois, quando ele rasgou a Israel da casa de Davi, e eles fizeram rei a Jeroboão, filho de Nebate, Jeroboão apartou a Israel de seguir o SENHOR e o fez cometer grande pecado.

[[v12-17-22]]

^<<v12-17-22,22>>^ Assim, andaram os filhos de Israel em todos os pecados que Jeroboão tinha cometido; nunca se apartaram deles,

[[v12-17-23]]

^<<v12-17-23,23>>^ até que o SENHOR afastou a Israel da sua presença, como falara pelo ministério de todos os seus servos, os profetas; assim, foi Israel transportado da sua terra para a Assíria, onde permanece até ao dia de hoje.

[[v12-17-24]]

^<<v12-17-24,24>>^ O rei da Assíria trouxe gente de Babilônia, de Cuta, de Ava, de Hamate e de Sefarvaim e a fez habitar nas cidades de Samaria, em lugar dos filhos de Israel; tomaram posse de Samaria e habitaram nas suas cidades.

[[v12-17-25]]

^<<v12-17-25,25>>^ A princípio, quando passaram a habitar ali, não temeram o SENHOR; então, mandou o SENHOR para o meio deles leões, os quais mataram a alguns do povo.

[[v12-17-26]]

^<<v12-17-26,26>>^ Pelo que se disse ao rei da Assíria: As gentes que transportaste e fizeste habitar nas cidades de Samaria não sabem a maneira de servir o deus da terra; por isso, enviou ele leões para o meio delas, os quais as matam, porque não sabem como servir o deus da terra.

[[v12-17-27]]

^<<v12-17-27,27>>^ Então, o rei da Assíria mandou dizer: Levai para lá um dos sacerdotes que de lá trouxestes; que ele vá, e lá habite, e lhes ensine a maneira de servir o deus da terra.

[[v12-17-28]]

^<<v12-17-28,28>>^ Foi, pois, um dos sacerdotes que haviam levado de Samaria, e habitou em Betel, e lhes ensinava como deviam temer o SENHOR.

[[v12-17-29]]

^<<v12-17-29,29>>^ Porém cada nação fez ainda os seus próprios deuses nas cidades em que habitava, e os puseram nos santuários dos altos que os samaritanos tinham feito.

[[v12-17-30]]

^<<v12-17-30,30>>^ Os de Babilônia fizeram Sucote-Benote; os de Cuta fizeram Nergal; os de Hamate fizeram Asima;

[[v12-17-31]]

^<<v12-17-31,31>>^ os aveus fizeram Nibaz e Tartaque; e os sefarvitas queimavam seus filhos a Adrameleque e a Anameleque, deuses de Sefarvaim.

[[v12-17-32]]

^<<v12-17-32,32>>^ Mas temiam também ao SENHOR; dentre os do povo constituíram sacerdotes dos lugares altos, os quais oficiavam a favor deles nos santuários dos altos.

[[v12-17-33]]

^<<v12-17-33,33>>^ De maneira que temiam o SENHOR e, ao mesmo tempo, serviam aos seus próprios deuses, segundo o costume das nações dentre as quais tinham sido transportados.

[[v12-17-34]]

^<<v12-17-34,34>>^ Até ao dia de hoje fazem segundo os antigos costumes; não temem o SENHOR, não fazem segundo os seus estatutos e juízos, nem segundo a lei e o mandamento que o SENHOR prescreveu aos filhos de Jacó, a quem deu o nome de Israel.

[[v12-17-35]]

^<<v12-17-35,35>>^ Ora, o SENHOR tinha feito aliança com eles e lhes ordenara, dizendo: Não temereis outros deuses, nem vos prostrareis diante deles, nem os servireis, nem lhes oferecereis sacrifícios;

[[v12-17-36]]

^<<v12-17-36,36>>^ mas ao SENHOR, que vos fez subir da terra do Egito com grande poder e com braço estendido, a ele temereis, e a ele vos prostrareis, e a ele oferecereis sacrifícios.

[[v12-17-37]]

^<<v12-17-37,37>>^ Os estatutos e os juízos, a lei e o mandamento que ele vos escreveu, tereis cuidado de os observar todos os dias; não temereis outros deuses.

[[v12-17-38]]

^<<v12-17-38,38>>^ Da aliança que fiz convosco não vos esquecereis; nem temereis outros deuses.

[[v12-17-39]]

^<<v12-17-39,39>>^ Mas ao SENHOR, vosso Deus, temereis, e ele vos livrará das mãos de todos os vossos inimigos.

[[v12-17-40]]

^<<v12-17-40,40>>^ Porém eles não deram ouvidos a isso; antes, procederam segundo o seu antigo costume.

[[v12-17-41]]

^<<v12-17-41,41>>^ Assim, estas nações temiam o SENHOR e serviam as suas próprias imagens de escultura; como fizeram seus pais, assim fazem também seus filhos e os filhos de seus filhos, até ao dia de hoje.

'''

xref:012-2-reis/012-2-reis-016.adoc#v12-16-0[&#60; Capítulo Anterior] | <<v12-17-0,Topo>> | xref:012-2-reis/012-2-reis-018.adoc#v12-18-0[Próximo Capítulo &#62;]