include::./index.adoc[]

[[v12-10-0]]
=== 2 Reis, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-10-1]]

^<<v12-10-1,1>>^ Achando-se em Samaria setenta filhos de Acabe, Jeú escreveu cartas e as enviou a Samaria, aos chefes da cidade, aos anciãos e aos tutores dos filhos de Acabe, dizendo:

[[v12-10-2]]

^<<v12-10-2,2>>^ Logo, em chegando a vós outros esta carta (pois estão convosco os filhos de vosso senhor, como também os carros, os cavalos, a cidade fortalecida e as armas),

[[v12-10-3]]

^<<v12-10-3,3>>^ escolhei o melhor e mais capaz dos filhos de vosso senhor, ponde-o sobre o trono de seu pai e pelejai pela casa de vosso senhor.

[[v12-10-4]]

^<<v12-10-4,4>>^ Porém eles temeram muitíssimo e disseram: Dois reis não puderam resistir a ele; como, pois, poderemos nós fazê-lo?

[[v12-10-5]]

^<<v12-10-5,5>>^ Então, o responsável pelo palácio, e o responsável pela cidade, e os anciãos, e os tutores mandaram dizer a Jeú: Teus servos somos e tudo quanto nos ordenares faremos; a ninguém constituiremos rei; faze o que bem te parecer.

[[v12-10-6]]

^<<v12-10-6,6>>^ Então, lhes escreveu outra carta, dizendo: Se estiverdes do meu lado e quiserdes obedecer-me, tomai as cabeças dos homens, filhos de vosso senhor, e amanhã a estas horas vinde a mim a Jezreel. Ora, os filhos do rei, que eram setenta, estavam com os grandes da cidade, que os criavam.

[[v12-10-7]]

^<<v12-10-7,7>>^ Chegada a eles a carta, tomaram os filhos do rei, e os mataram, setenta pessoas, e puseram as suas cabeças nuns cestos, e lhas mandaram a Jezreel.

[[v12-10-8]]

^<<v12-10-8,8>>^ Veio um mensageiro e lhe disse: Trouxeram as cabeças dos filhos do rei. Ele disse: Ponde-as em dois montões à entrada da porta, até pela manhã.

[[v12-10-9]]

^<<v12-10-9,9>>^ Saindo ele pela manhã, parou e disse a todo o povo: Vós estais sem culpa; eis que eu conspirei contra o meu senhor e o matei; mas quem feriu todos estes?

[[v12-10-10]]

^<<v12-10-10,10>>^ Sabei, pois, agora, que, da palavra do SENHOR, pronunciada contra a casa de Acabe, nada cairá em terra, porque o SENHOR fez o que falou por intermédio do seu servo Elias.

[[v12-10-11]]

^<<v12-10-11,11>>^ Jeú feriu também todos os restantes da casa de Acabe em Jezreel, como também todos os seus grandes, os seus conhecidos e os seus sacerdotes, até que nem um sequer lhe deixou ficar de resto.

[[v12-10-12]]

^<<v12-10-12,12>>^ Então, se dispôs, partiu e foi a Samaria. E, estando no caminho, em Bete-Equede dos Pastores,

[[v12-10-13]]

^<<v12-10-13,13>>^ encontrou Jeú parentes de Acazias, rei de Judá, e perguntou: Quem sois vós? Eles responderam: Parentes de Acazias; voltamos de saudar os filhos do rei e os da rainha-mãe.

[[v12-10-14]]

^<<v12-10-14,14>>^ Então, disse Jeú: Apanhai-os vivos. Eles os apanharam vivos e os mataram junto ao poço de Bete-Equede, quarenta e dois homens; e a nenhum deles deixou de resto.

[[v12-10-15]]

^<<v12-10-15,15>>^ Tendo partido dali, encontrou a Jonadabe, filho de Recabe, que lhe vinha ao encontro; Jeú saudou-o e lhe perguntou: Tens tu sincero o coração para comigo, como o meu o é para contigo? Respondeu Jonadabe: Tenho. Então, se tens, dá-me a mão. Jonadabe deu-lhe a mão; e Jeú fê-lo subir consigo ao carro

[[v12-10-16]]

^<<v12-10-16,16>>^ e lhe disse: Vem comigo e verás o meu zelo para com o SENHOR. E, assim, Jeú o levou no seu carro.

[[v12-10-17]]

^<<v12-10-17,17>>^ Tendo Jeú chegado a Samaria, feriu todos os que ali ficaram de Acabe, até destruí-los, segundo a palavra que o SENHOR dissera a Elias.

[[v12-10-18]]

^<<v12-10-18,18>>^ Ajuntou Jeú a todo o povo e lhe disse: Acabe serviu pouco a Baal; Jeú, porém, muito o servirá.

[[v12-10-19]]

^<<v12-10-19,19>>^ Pelo que chamai-me, agora, todos os profetas de Baal, todos os seus servidores e todos os seus sacerdotes; não falte nenhum, porque tenho grande sacrifício a oferecer a Baal; todo aquele que faltar não viverá. Porém Jeú fazia isto com astúcia, para destruir os servidores de Baal.

[[v12-10-20]]

^<<v12-10-20,20>>^ Disse mais Jeú: Consagrai uma assembleia solene a Baal; e a proclamaram.

[[v12-10-21]]

^<<v12-10-21,21>>^ Também Jeú enviou mensageiros por todo o Israel; vieram todos os adoradores de Baal, e nenhum homem deles ficou que não viesse. Entraram na casa de Baal, que se encheu de uma extremidade à outra.

[[v12-10-22]]

^<<v12-10-22,22>>^ Então, disse Jeú ao vestiário: Tira as vestimentas para todos os adoradores de Baal. E o fez.

[[v12-10-23]]

^<<v12-10-23,23>>^ Entrou Jeú com Jonadabe, filho de Recabe, na casa de Baal e disse aos adoradores de Baal: Examinai e vede bem não esteja aqui entre vós algum dos servos do SENHOR, mas somente os adoradores de Baal.

[[v12-10-24]]

^<<v12-10-24,24>>^ E, entrando eles a oferecerem sacrifícios e holocaustos, Jeú preparou da parte de fora oitenta homens e disse-lhes: Se escapar algum dos homens que eu entregar em vossas mãos, a vida daquele que o deixar escapar responderá pela vida dele.

[[v12-10-25]]

^<<v12-10-25,25>>^ Sucedeu que, acabado o oferecimento do holocausto, ordenou Jeú aos da sua guarda e aos capitães: Entrai, feri-os, que nenhum escape. Feriram-nos a fio de espada; e os da guarda e os capitães os lançaram fora, e penetraram no mais interior da casa de Baal,

[[v12-10-26]]

^<<v12-10-26,26>>^ e tiraram as colunas que estavam na casa de Baal, e as queimaram.

[[v12-10-27]]

^<<v12-10-27,27>>^ Também quebraram a própria coluna de Baal, e derribaram a casa de Baal, e a transformaram em latrinas até ao dia de hoje.

[[v12-10-28]]

^<<v12-10-28,28>>^ Assim, Jeú exterminou de Israel a Baal.

[[v12-10-29]]

^<<v12-10-29,29>>^ Porém não se apartou Jeú de seguir os pecados de Jeroboão, filho de Nebate, que fez pecar a Israel, a saber, dos bezerros de ouro que estavam em Betel e em Dã.

[[v12-10-30]]

^<<v12-10-30,30>>^ Pelo que disse o SENHOR a Jeú: Porquanto bem executaste o que é reto perante mim e fizeste à casa de Acabe segundo tudo quanto era do meu propósito, teus filhos até à quarta geração se assentarão no trono de Israel.

[[v12-10-31]]

^<<v12-10-31,31>>^ Mas Jeú não teve cuidado de andar de todo o seu coração na lei do SENHOR, Deus de Israel, nem se apartou dos pecados que Jeroboão fez pecar a Israel.

[[v12-10-32]]

^<<v12-10-32,32>>^ Naqueles dias, começou o SENHOR a diminuir os limites de Israel, que foi ferido por Hazael em todas as suas fronteiras,

[[v12-10-33]]

^<<v12-10-33,33>>^ desde o Jordão para o nascente do sol, toda a terra de Gileade, os gaditas, os rubenitas e os manassitas, desde Aroer, que está junto ao vale de Arnom, a saber, Gileade e Basã.

[[v12-10-34]]

^<<v12-10-34,34>>^ Ora, os mais atos de Jeú, e tudo quanto fez, e todo o seu poder, porventura, não estão escritos no Livro da História dos Reis de Israel?

[[v12-10-35]]

^<<v12-10-35,35>>^ Descansou Jeú com seus pais, e o sepultaram em Samaria; e Jeoacaz, seu filho, reinou em seu lugar.

[[v12-10-36]]

^<<v12-10-36,36>>^ Os dias que Jeú reinou sobre Israel em Samaria foram vinte e oito anos.

'''

xref:012-2-reis/012-2-reis-009.adoc#v12-9-0[&#60; Capítulo Anterior] | <<v12-10-0,Topo>> | xref:012-2-reis/012-2-reis-011.adoc#v12-11-0[Próximo Capítulo &#62;]