include::./index.adoc[]

[[v12-3-0]]
=== 2 Reis, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-3-1]]

^<<v12-3-1,1>>^ Jorão, filho de Acabe, começou a reinar sobre Israel, em Samaria, no décimo oitavo ano de Josafá, rei de Judá; e reinou doze anos.

[[v12-3-2]]

^<<v12-3-2,2>>^ Fez o que era mau perante o SENHOR; porém não como seu pai, nem como sua mãe; porque tirou a coluna de Baal, que seu pai fizera.

[[v12-3-3]]

^<<v12-3-3,3>>^ Contudo, aderiu aos pecados de Jeroboão, filho de Nebate, que fizera pecar a Israel; não se apartou deles.

[[v12-3-4]]

^<<v12-3-4,4>>^ Então, Mesa, rei dos moabitas, era criador de gado e pagava o seu tributo ao rei de Israel com cem mil cordeiros e a lã de cem mil carneiros.

[[v12-3-5]]

^<<v12-3-5,5>>^ Tendo, porém, morrido Acabe, revoltou-se o rei de Moabe contra o rei de Israel.

[[v12-3-6]]

^<<v12-3-6,6>>^ Por isso, Jorão, ao mesmo tempo, saiu de Samaria e fez revista de todo o Israel.

[[v12-3-7]]

^<<v12-3-7,7>>^ Mandou dizer a Josafá, rei de Judá: O rei de Moabe se revoltou contra mim; irás tu comigo à guerra contra Moabe? Respondeu ele: Subirei; serei como tu és, o meu povo, como o teu povo, os meus cavalos, como os teus cavalos.

[[v12-3-8]]

^<<v12-3-8,8>>^ Então, perguntou Jorão: Por que caminho subiremos? Respondeu ele: Pelo caminho do deserto de Edom.

[[v12-3-9]]

^<<v12-3-9,9>>^ Partiram o rei de Israel, o rei de Judá e o rei de Edom; após sete dias de marcha, não havia água para o exército e para o gado que os seguiam.

[[v12-3-10]]

^<<v12-3-10,10>>^ Então, disse o rei de Israel: Ai! O SENHOR chamou a estes três reis para os entregar nas mãos de Moabe.

[[v12-3-11]]

^<<v12-3-11,11>>^ Perguntou, porém, Josafá: Não há, aqui, algum profeta do SENHOR, para que consultemos o SENHOR por ele? Respondeu um dos servos do rei de Israel: Aqui está Eliseu, filho de Safate, que deitava água sobre as mãos de Elias.

[[v12-3-12]]

^<<v12-3-12,12>>^ Disse Josafá: Está com ele a palavra do SENHOR. Então, o rei de Israel, Josafá e o rei de Edom desceram a ter com ele.

[[v12-3-13]]

^<<v12-3-13,13>>^ Mas Eliseu disse ao rei de Israel: Que tenho eu contigo? Vai aos profetas de teu pai e aos profetas de tua mãe. Porém o rei de Israel lhe disse: Não, porque o SENHOR é quem chamou estes três reis para os entregar nas mãos de Moabe.

[[v12-3-14]]

^<<v12-3-14,14>>^ Disse Eliseu: Tão certo como vive o SENHOR dos Exércitos, em cuja presença estou, se eu não respeitasse a presença de Josafá, rei de Judá, não te daria atenção, nem te contemplaria.

[[v12-3-15]]

^<<v12-3-15,15>>^ Ora, pois, trazei-me um tangedor. Quando o tangedor tocava, veio o poder de Deus sobre Eliseu.

[[v12-3-16]]

^<<v12-3-16,16>>^ Este disse: Assim diz o SENHOR: Fazei, neste vale, covas e covas.

[[v12-3-17]]

^<<v12-3-17,17>>^ Porque assim diz o SENHOR: Não sentireis vento, nem vereis chuva; todavia, este vale se encherá de tanta água, que bebereis vós, e o vosso gado, e os vossos animais.

[[v12-3-18]]

^<<v12-3-18,18>>^ Isto é ainda pouco aos olhos do SENHOR; de maneira que também entregará Moabe nas vossas mãos.

[[v12-3-19]]

^<<v12-3-19,19>>^ Ferireis todas as cidades fortificadas e todas as cidades principais, e todas as boas árvores cortareis, e tapareis todas as fontes de água, e danificareis com pedras todos os bons campos.

[[v12-3-20]]

^<<v12-3-20,20>>^ Pela manhã, ao apresentar-se a oferta de manjares, eis que vinham as águas pelo caminho de Edom; e a terra se encheu de água.

[[v12-3-21]]

^<<v12-3-21,21>>^ Ouvindo, pois, todos os moabitas que os reis tinham subido para pelejar contra eles, todos os que cingiam cinto, desde o mais novo até ao mais velho, foram convocados e postos nas fronteiras.

[[v12-3-22]]

^<<v12-3-22,22>>^ Levantando-se de madrugada, em saindo o sol sobre as águas, viram os moabitas defronte deles as águas vermelhas como sangue.

[[v12-3-23]]

^<<v12-3-23,23>>^ E disseram: Isto é sangue; certamente, os reis se destruíram e se mataram um ao outro! Agora, pois, à presa, ó Moabe!

[[v12-3-24]]

^<<v12-3-24,24>>^ Porém, chegando eles ao arraial de Israel, os israelitas se levantaram e feriram aos moabitas, os quais fugiram diante deles; entraram os israelitas na terra e também aí feriram aos moabitas.

[[v12-3-25]]

^<<v12-3-25,25>>^ Arrasaram as cidades, e cada um lançou a sua pedra em todos os bons campos, e os entulharam, e taparam todas as fontes de águas, e cortaram todas as boas árvores, até que só Quir-Haresete ficou com seus muros; mas os que atiravam com fundas a cercaram e a feriram.

[[v12-3-26]]

^<<v12-3-26,26>>^ Vendo o rei de Moabe que a peleja prevalecia contra ele, tomou consigo setecentos homens que arrancavam espada, para romperem contra o rei de Edom, porém não puderam.

[[v12-3-27]]

^<<v12-3-27,27>>^ Então, tomou a seu filho primogênito, que havia de reinar em seu lugar, e o ofereceu em holocausto sobre o muro; pelo que houve grande ira contra Israel; por isso, se retiraram dali e voltaram para a sua própria terra.

'''

xref:012-2-reis/012-2-reis-002.adoc#v12-2-0[&#60; Capítulo Anterior] | <<v12-3-0,Topo>> | xref:012-2-reis/012-2-reis-004.adoc#v12-4-0[Próximo Capítulo &#62;]