include::./index.adoc[]

[[v12-1-0]]
=== 2 Reis, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-1-1]]

^<<v12-1-1,1>>^ Depois da morte de Acabe, revoltou-se Moabe contra Israel.

[[v12-1-2]]

^<<v12-1-2,2>>^ E caiu Acazias pelas grades de um quarto alto, em Samaria, e adoeceu; enviou mensageiros e disse-lhes: Ide e consultai a Baal-Zebube, deus de Ecrom, se sararei desta doença.

[[v12-1-3]]

^<<v12-1-3,3>>^ Mas o Anjo do SENHOR disse a Elias, o tesbita: Dispõe-te, e sobe para te encontrares com os mensageiros do rei de Samaria, e dize-lhes: Porventura, não há Deus em Israel, para irdes consultar Baal-Zebube, deus de Ecrom?

[[v12-1-4]]

^<<v12-1-4,4>>^ Por isso, assim diz o SENHOR: Da cama a que subiste, não descerás, mas, sem falta, morrerás. Então, Elias partiu.

[[v12-1-5]]

^<<v12-1-5,5>>^ E os mensageiros voltaram para o rei, e este lhes perguntou: Que há, por que voltastes?

[[v12-1-6]]

^<<v12-1-6,6>>^ Eles responderam: Um homem nos subiu ao encontro e nos disse: Ide, voltai para o rei que vos mandou e dizei-lhe: Assim diz o SENHOR: Porventura, não há Deus em Israel, para que mandes consultar Baal-Zebube, deus de Ecrom? Portanto, da cama a que subiste, não descerás, mas, sem falta, morrerás.

[[v12-1-7]]

^<<v12-1-7,7>>^ Ele lhes perguntou: Qual era a aparência do homem que vos veio ao encontro e vos falou tais palavras?

[[v12-1-8]]

^<<v12-1-8,8>>^ Eles lhe responderam: Era homem vestido de pelos, com os lombos cingidos de um cinto de couro. Então, disse ele: É Elias, o tesbita.

[[v12-1-9]]

^<<v12-1-9,9>>^ Então, lhe enviou o rei um capitão de cinquenta, com seus cinquenta soldados, que subiram ao profeta, pois este estava assentado no cimo do monte; disse-lhe o capitão: Homem de Deus, o rei diz: Desce.

[[v12-1-10]]

^<<v12-1-10,10>>^ Elias, porém, respondeu ao capitão de cinquenta: Se eu sou homem de Deus, desça fogo do céu e te consuma a ti e aos teus cinquenta. Então, fogo desceu do céu e o consumiu a ele e aos seus cinquenta.

[[v12-1-11]]

^<<v12-1-11,11>>^ Tornou o rei a enviar-lhe outro capitão de cinquenta, com os seus cinquenta; este lhe falou e disse: Homem de Deus, assim diz o rei: Desce depressa.

[[v12-1-12]]

^<<v12-1-12,12>>^ Respondeu Elias e disse-lhe: Se eu sou homem de Deus, desça fogo do céu e te consuma a ti e aos teus cinquenta. Então, fogo de Deus desceu do céu e o consumiu a ele e aos seus cinquenta.

[[v12-1-13]]

^<<v12-1-13,13>>^ Tornou o rei a enviar terceira vez um capitão de cinquenta, com os seus cinquenta; então, subiu o capitão de cinquenta. Indo ele, pôs-se de joelhos diante de Elias, e suplicou-lhe, e disse-lhe: Homem de Deus, seja, peço-te, preciosa aos teus olhos a minha vida e a vida destes cinquenta, teus servos;

[[v12-1-14]]

^<<v12-1-14,14>>^ pois fogo desceu do céu e consumiu aqueles dois primeiros capitães de cinquenta, com os seus cinquenta; porém, agora, seja preciosa aos teus olhos a minha vida.

[[v12-1-15]]

^<<v12-1-15,15>>^ Então, o Anjo do SENHOR disse a Elias: Desce com este, não temas. Levantou-se e desceu com ele ao rei.

[[v12-1-16]]

^<<v12-1-16,16>>^ E disse a este: Assim diz o SENHOR: Por que enviaste mensageiros a consultar Baal-Zebube, deus de Ecrom? Será, acaso, por não haver Deus em Israel, cuja palavra se consultasse? Portanto, desta cama a que subiste, não descerás, mas, sem falta, morrerás.

[[v12-1-17]]

^<<v12-1-17,17>>^ Assim, pois, morreu, segundo a palavra do SENHOR, que Elias falara; e Jorão, seu irmão, começou a reinar no seu lugar, no ano segundo de Jeorão, filho de Josafá, rei de Judá, porquanto Acazias não tinha filhos.

[[v12-1-18]]

^<<v12-1-18,18>>^ Quanto aos mais atos de Acazias e ao que fez, porventura, não estão escritos no Livro da História dos Reis de Israel?

'''

xref:011-1-reis/011-1-reis-022.adoc#v11-22-0[&#60; Capítulo Anterior] | <<v12-1-0,Topo>> | xref:012-2-reis/012-2-reis-002.adoc#v12-2-0[Próximo Capítulo &#62;]