include::./index.adoc[]

[[v12-9-0]]
=== 2 Reis, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-9-1]]

^<<v12-9-1,1>>^ Então, o profeta Eliseu chamou um dos discípulos dos profetas e lhe disse: Cinge os lombos, leva contigo este vaso de azeite e vai-te a Ramote-Gileade;

[[v12-9-2]]

^<<v12-9-2,2>>^ em lá chegando, vê onde está Jeú, filho de Josafá, filho de Ninsi; entra, e faze-o levantar-se do meio de seus irmãos, e leva-o à câmara interior.

[[v12-9-3]]

^<<v12-9-3,3>>^ Toma o vaso de azeite, derrama-lho sobre a cabeça e dize: Assim diz o SENHOR: Ungi-te rei sobre Israel. Então, abre a porta, foge e não te detenhas.

[[v12-9-4]]

^<<v12-9-4,4>>^ Foi, pois, o moço, o jovem profeta, a Ramote-Gileade.

[[v12-9-5]]

^<<v12-9-5,5>>^ Entrando ele, eis que os capitães do exército estavam assentados; ele disse: Capitão, tenho mensagem que te dizer. Perguntou-lhe Jeú: A qual de todos nós? Respondeu-lhe ele: A ti, capitão!

[[v12-9-6]]

^<<v12-9-6,6>>^ Então, se levantou Jeú e entrou na casa; o jovem derramou-lhe o azeite sobre a cabeça e lhe disse: Assim diz o SENHOR, Deus de Israel: Ungi-te rei sobre o povo do SENHOR, sobre Israel.

[[v12-9-7]]

^<<v12-9-7,7>>^ Ferirás a casa de Acabe, teu senhor, para que eu vingue da mão de Jezabel o sangue de meus servos, os profetas, e o sangue de todos os servos do SENHOR.

[[v12-9-8]]

^<<v12-9-8,8>>^ Toda a casa de Acabe perecerá; exterminarei de Acabe todos do sexo masculino, quer escravo, quer livre, em Israel.

[[v12-9-9]]

^<<v12-9-9,9>>^ Porque farei à casa de Acabe como à casa de Jeroboão, filho de Nebate, e como à casa de Baasa, filho de Aías.

[[v12-9-10]]

^<<v12-9-10,10>>^ Os cães devorarão Jezabel no campo de Jezreel; não haverá quem a enterre. Dito isto, abriu a porta e fugiu.

[[v12-9-11]]

^<<v12-9-11,11>>^ Saindo Jeú aos servos de seu senhor, disseram-lhe: Vai tudo bem? Por que veio a ti este louco? Ele lhes respondeu: Bem conheceis esse homem e o seu falar.

[[v12-9-12]]

^<<v12-9-12,12>>^ Mas eles disseram: É mentira; agora, faze-nos sabê-lo, te pedimos. Então, disse Jeú: Assim e assim me falou, a saber: Assim diz o SENHOR: Ungi-te rei sobre Israel.

[[v12-9-13]]

^<<v12-9-13,13>>^ Então, se apressaram, e, tomando cada um o seu manto, os puseram debaixo dele, sobre os degraus, e tocaram a trombeta, e disseram: Jeú é rei!

[[v12-9-14]]

^<<v12-9-14,14>>^ Assim, Jeú, filho de Josafá, filho de Ninsi, conspirou contra Jorão. Tinha, porém, Jorão cercado a Ramote-Gileade, ele e todo o Israel, por causa de Hazael, rei da Síria.

[[v12-9-15]]

^<<v12-9-15,15>>^ Porém o rei Jorão voltou para se curar em Jezreel das feridas que os siros lhe fizeram, quando pelejou contra Hazael, rei da Síria. Disse Jeú: Se é da vossa vontade, ninguém saia furtivamente da cidade, para ir anunciar isto em Jezreel.

[[v12-9-16]]

^<<v12-9-16,16>>^ Então, Jeú subiu a um carro e foi-se a Jezreel, porque Jorão estava de cama ali. Também Acazias, rei de Judá, descera para ver a Jorão.

[[v12-9-17]]

^<<v12-9-17,17>>^ Ora, o atalaia estava na torre de Jezreel, e viu a tropa de Jeú, que vinha, e disse: Vejo uma tropa. Então, disse Jorão: Toma um cavaleiro e envia-o ao seu encontro, para que lhe pergunte: Há paz?

[[v12-9-18]]

^<<v12-9-18,18>>^ Foi-lhe o cavaleiro ao encontro e disse: Assim diz o rei: Há paz? Respondeu Jeú: Que tens tu com a paz? Passa para trás de mim. O atalaia deu aviso, dizendo: Chegou a eles o mensageiro, porém não volta.

[[v12-9-19]]

^<<v12-9-19,19>>^ Então, enviou Jorão outro cavaleiro; chegando este a eles, disse: Assim diz o rei: Há paz? Respondeu Jeú: Que tens tu com a paz? Passa para trás de mim.

[[v12-9-20]]

^<<v12-9-20,20>>^ O atalaia deu aviso, dizendo: Também este chegou a eles, porém não volta; e o guiar do carro parece como o de Jeú, filho de Ninsi, porque guia furiosamente.

[[v12-9-21]]

^<<v12-9-21,21>>^ Disse Jorão: Aparelha o carro. E lhe aparelharam o carro. Saiu Jorão, rei de Israel, e Acazias, rei de Judá, cada um em seu carro, e foram ao encontro de Jeú, e o acharam no campo de Nabote, o jezreelita.

[[v12-9-22]]

^<<v12-9-22,22>>^ Sucedeu que, vendo Jorão a Jeú, perguntou: Há paz, Jeú? Ele respondeu: Que paz, enquanto perduram as prostituições de tua mãe Jezabel e as suas muitas feitiçarias?

[[v12-9-23]]

^<<v12-9-23,23>>^ Então, Jorão voltou as rédeas, fugiu e disse a Acazias: Há traição, Acazias!

[[v12-9-24]]

^<<v12-9-24,24>>^ Mas Jeú entesou o seu arco com toda a força e feriu a Jorão entre as espáduas; a flecha saiu-lhe pelo coração, e ele caiu no seu carro.

[[v12-9-25]]

^<<v12-9-25,25>>^ Então, Jeú disse a Bidcar, seu capitão: Toma-o, lança-o no campo da herdade de Nabote, o jezreelita; pois, lembra-te de que, indo eu e tu, juntos, montados, após Acabe, seu pai, o SENHOR pronunciou contra ele esta sentença:

[[v12-9-26]]

^<<v12-9-26,26>>^ Tão certo como vi ontem à tarde o sangue de Nabote e o sangue de seus filhos, diz o SENHOR, assim to retribuirei neste campo, diz o SENHOR. Agora, pois, toma-o e lança-o neste campo, segundo a palavra do SENHOR.

[[v12-9-27]]

^<<v12-9-27,27>>^ À vista disto, Acazias, rei de Judá, fugiu pelo caminho de Bete-Hagã; porém Jeú o perseguiu e disse: Feri também a este; e o feriram no carro, à subida de Gur, que está junto a Ibleão. E fugiu para Megido, onde morreu.

[[v12-9-28]]

^<<v12-9-28,28>>^ Levaram-no os seus servos, num carro, a Jerusalém e o enterraram na sua sepultura junto a seus pais, na Cidade de Davi.

[[v12-9-29]]

^<<v12-9-29,29>>^ No ano undécimo de Jorão, filho de Acabe, começara Acazias a reinar sobre Judá.

[[v12-9-30]]

^<<v12-9-30,30>>^ Tendo Jeú chegado a Jezreel, Jezabel o soube; então, se pintou em volta dos olhos, enfeitou a cabeça e olhou pela janela.

[[v12-9-31]]

^<<v12-9-31,31>>^ Ao entrar Jeú pelo portão do palácio, disse ela: Teve paz Zinri, que matou a seu senhor?

[[v12-9-32]]

^<<v12-9-32,32>>^ Levantou ele o rosto para a janela e disse: Quem é comigo? Quem? E dois ou três eunucos olharam para ele.

[[v12-9-33]]

^<<v12-9-33,33>>^ Então, disse ele: Lançai-a daí abaixo. Lançaram-na abaixo; e foram salpicados com o seu sangue a parede e os cavalos, e Jeú a atropelou.

[[v12-9-34]]

^<<v12-9-34,34>>^ Entrando ele e havendo comido e bebido, disse: Olhai por aquela maldita e sepultai-a, porque é filha de rei.

[[v12-9-35]]

^<<v12-9-35,35>>^ Foram para a sepultar; porém não acharam dela senão a caveira, os pés e as palmas das mãos.

[[v12-9-36]]

^<<v12-9-36,36>>^ Então, voltaram e lho fizeram saber. Ele disse: Esta é a palavra do SENHOR, que falou por intermédio de Elias, o tesbita, seu servo, dizendo: No campo de Jezreel, os cães comerão a carne de Jezabel.

[[v12-9-37]]

^<<v12-9-37,37>>^ O cadáver de Jezabel será como esterco sobre o campo da herdade de Jezreel, de maneira que já não dirão: Esta é Jezabel.

'''

xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[&#60; Capítulo Anterior] | <<v12-9-0,Topo>> | xref:012-2-reis/012-2-reis-010.adoc#v12-10-0[Próximo Capítulo &#62;]