include::./index.adoc[]

[[v12-13-0]]
=== 2 Reis, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-13-1]]

^<<v12-13-1,1>>^ No vigésimo terceiro ano de Joás, filho de Acazias, rei de Judá, começou a reinar Jeoacaz, filho de Jeú, sobre Israel, em Samaria, e reinou dezessete anos.

[[v12-13-2]]

^<<v12-13-2,2>>^ E fez o que era mau perante o SENHOR; porque andou nos pecados de Jeroboão, filho de Nebate, que fez pecar a Israel; não se apartou deles.

[[v12-13-3]]

^<<v12-13-3,3>>^ Pelo que se acendeu contra Israel a ira do SENHOR, o qual os entregou nas mãos de Hazael, rei da Síria, e nas mãos de Ben-Hadade, filho de Hazael, todos aqueles dias.

[[v12-13-4]]

^<<v12-13-4,4>>^ Porém Jeoacaz fez súplicas diante do SENHOR, e o SENHOR o ouviu; pois viu a opressão com que o rei da Síria atormentava a Israel.

[[v12-13-5]]

^<<v12-13-5,5>>^ O SENHOR deu um salvador a Israel, de modo que os filhos de Israel saíram de sob o poder dos siros e habitaram, de novo, em seus lares, como dantes.

[[v12-13-6]]

^<<v12-13-6,6>>^ Contudo, não se apartaram dos pecados da casa de Jeroboão, que fez pecar a Israel, porém andaram neles; e também o poste-ídolo permaneceu em Samaria.

[[v12-13-7]]

^<<v12-13-7,7>>^ E foi o caso que não se deixaram a Jeoacaz, do exército, senão cinquenta cavaleiros, dez carros e dez mil homens de pé; porquanto o rei da Síria os havia destruído e feito como o pó, trilhando-os.

[[v12-13-8]]

^<<v12-13-8,8>>^ Ora, os mais atos de Jeoacaz, e tudo o que fez, e o seu poder, porventura, não estão escritos no Livro da História dos Reis de Israel?

[[v12-13-9]]

^<<v12-13-9,9>>^ Jeoacaz descansou com seus pais, e o sepultaram em Samaria; e Jeoás, seu filho, reinou em seu lugar.

[[v12-13-10]]

^<<v12-13-10,10>>^ No trigésimo sétimo ano de Joás, rei de Judá, começou Jeoás, filho de Jeoacaz, a reinar sobre Israel, em Samaria; e reinou dezesseis anos.

[[v12-13-11]]

^<<v12-13-11,11>>^ Fez o que era mau perante o SENHOR; não se apartou de nenhum dos pecados de Jeroboão, filho de Nebate, que fez pecar a Israel; porém andou neles.

[[v12-13-12]]

^<<v12-13-12,12>>^ Quanto aos mais atos de Jeoás, e a tudo o que fez, e ao seu poder, com que pelejou contra Amazias, rei de Judá, porventura, não estão escritos no Livro da História dos Reis de Israel?

[[v12-13-13]]

^<<v12-13-13,13>>^ Descansou Jeoás com seus pais, e no seu trono se assentou Jeroboão. Jeoás foi sepultado em Samaria, junto aos reis de Israel.

[[v12-13-14]]

^<<v12-13-14,14>>^ Estando Eliseu padecendo da enfermidade de que havia de morrer, Jeoás, rei de Israel, desceu a visitá-lo, chorou sobre ele e disse: Meu pai, meu pai! Carros de Israel e seus cavaleiros!

[[v12-13-15]]

^<<v12-13-15,15>>^ Então, lhe disse Eliseu: Toma um arco e flechas; ele tomou um arco e flechas.

[[v12-13-16]]

^<<v12-13-16,16>>^ Disse ao rei de Israel: Retesa o arco; e ele o fez. Então, Eliseu pôs as mãos sobre as mãos do rei.

[[v12-13-17]]

^<<v12-13-17,17>>^ E disse: Abre a janela para o oriente; ele a abriu. Disse mais Eliseu: Atira; e ele atirou. Prosseguiu: Flecha da vitória do SENHOR! Flecha da vitória contra os siros! Porque ferirás os siros em Afeca, até os consumir.

[[v12-13-18]]

^<<v12-13-18,18>>^ Disse ainda: Toma as flechas. Ele as tomou. Então, disse ao rei de Israel: Atira contra a terra; ele a feriu três vezes e cessou.

[[v12-13-19]]

^<<v12-13-19,19>>^ Então, o homem de Deus se indignou muito contra ele e disse: Cinco ou seis vezes a deverias ter ferido; então, feririas os siros até os consumir; porém, agora, só três vezes ferirás os siros.

[[v12-13-20]]

^<<v12-13-20,20>>^ Morreu Eliseu, e o sepultaram. Ora, bandos dos moabitas costumavam invadir a terra, à entrada do ano.

[[v12-13-21]]

^<<v12-13-21,21>>^ Sucedeu que, enquanto alguns enterravam um homem, eis que viram um bando; então, lançaram o homem na sepultura de Eliseu; e, logo que o cadáver tocou os ossos de Eliseu, reviveu o homem e se levantou sobre os pés.

[[v12-13-22]]

^<<v12-13-22,22>>^ Hazael, rei da Síria, oprimiu a Israel todos os dias de Jeoacaz.

[[v12-13-23]]

^<<v12-13-23,23>>^ Porém o SENHOR teve misericórdia de Israel, e se compadeceu dele, e se tornou para ele, por amor da aliança com Abraão, Isaque e Jacó; e não o quis destruir e não o lançou ainda da sua presença.

[[v12-13-24]]

^<<v12-13-24,24>>^ Morreu Hazael, rei da Síria; e Ben-Hadade, seu filho, reinou em seu lugar.

[[v12-13-25]]

^<<v12-13-25,25>>^ Jeoás, filho de Jeoacaz, retomou as cidades das mãos de Ben-Hadade, que este havia tomado das mãos de Jeoacaz, seu pai, na guerra; três vezes Jeoás o feriu e recuperou as cidades de Israel.

'''

xref:012-2-reis/012-2-reis-012.adoc#v12-12-0[&#60; Capítulo Anterior] | <<v12-13-0,Topo>> | xref:012-2-reis/012-2-reis-014.adoc#v12-14-0[Próximo Capítulo &#62;]