include::./index.adoc[]

[[v12-21-0]]
=== 2 Reis, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-21-1]]

^<<v12-21-1,1>>^ Tinha Manassés doze anos de idade quando começou a reinar e reinou cinquenta e cinco anos em Jerusalém. Sua mãe chamava-se Hefzibá.

[[v12-21-2]]

^<<v12-21-2,2>>^ Fez ele o que era mau perante o SENHOR, segundo as abominações dos gentios que o SENHOR expulsara de suas possessões, de diante dos filhos de Israel.

[[v12-21-3]]

^<<v12-21-3,3>>^ Pois tornou a edificar os altos que Ezequias, seu pai, havia destruído, e levantou altares a Baal, e fez um poste-ídolo como o que fizera Acabe, rei de Israel, e se prostrou diante de todo o exército dos céus, e o serviu.

[[v12-21-4]]

^<<v12-21-4,4>>^ Edificou altares na Casa do SENHOR, da qual o SENHOR tinha dito: Em Jerusalém porei o meu nome.

[[v12-21-5]]

^<<v12-21-5,5>>^ Também edificou altares a todo o exército dos céus nos dois átrios da Casa do SENHOR.

[[v12-21-6]]

^<<v12-21-6,6>>^ E queimou a seu filho como sacrifício, adivinhava pelas nuvens, era agoureiro e tratava com médiuns e feiticeiros; prosseguiu em fazer o que era mau perante o SENHOR, para o provocar à ira.

[[v12-21-7]]

^<<v12-21-7,7>>^ Também pôs a imagem de escultura do poste-ídolo que tinha feito na casa de que o SENHOR dissera a Davi e a Salomão, seu filho: Nesta casa e em Jerusalém, que escolhi de todas as tribos de Israel, porei o meu nome para sempre;

[[v12-21-8]]

^<<v12-21-8,8>>^ e não farei que os pés de Israel andem errantes da terra que dei a seus pais, contanto que tenham cuidado de fazer segundo tudo o que lhes tenho mandado e conforme toda a lei que Moisés, meu servo, lhes ordenou.

[[v12-21-9]]

^<<v12-21-9,9>>^ Eles, porém, não ouviram; e Manassés de tal modo os fez errar, que fizeram pior do que as nações que o SENHOR tinha destruído de diante dos filhos de Israel.

[[v12-21-10]]

^<<v12-21-10,10>>^ Então, o SENHOR falou por intermédio dos profetas, seus servos, dizendo:

[[v12-21-11]]

^<<v12-21-11,11>>^ Visto que Manassés, rei de Judá, cometeu estas abominações, fazendo pior que tudo que fizeram os amorreus antes dele, e também a Judá fez pecar com os ídolos dele,

[[v12-21-12]]

^<<v12-21-12,12>>^ assim diz o SENHOR, Deus de Israel: Eis que hei de trazer tais males sobre Jerusalém e Judá, que todo o que os ouvir, lhe tinirão ambos os ouvidos.

[[v12-21-13]]

^<<v12-21-13,13>>^ Estenderei sobre Jerusalém o cordel de Samaria e o prumo da casa de Acabe; eliminarei Jerusalém, como quem elimina a sujeira de um prato, elimina-a e o emborca.

[[v12-21-14]]

^<<v12-21-14,14>>^ Abandonarei o resto da minha herança, entregá-lo-ei nas mãos de seus inimigos; servirá de presa e despojo para todos os seus inimigos.

[[v12-21-15]]

^<<v12-21-15,15>>^ Porquanto fizeram o que era mau perante mim e me provocaram à ira, desde o dia em que seus pais saíram do Egito até ao dia de hoje.

[[v12-21-16]]

^<<v12-21-16,16>>^ Além disso, Manassés derramou muitíssimo sangue inocente, até encher Jerusalém de um ao outro extremo, afora o seu pecado, com que fez pecar a Judá, praticando o que era mau perante o SENHOR.

[[v12-21-17]]

^<<v12-21-17,17>>^ Quanto aos mais atos de Manassés, e a tudo quanto fez, e ao seu pecado, que cometeu, porventura, não estão escritos no Livro da História dos Reis de Judá?

[[v12-21-18]]

^<<v12-21-18,18>>^ Manassés descansou com seus pais e foi sepultado no jardim da sua própria casa, no jardim de Uzá; e Amom, seu filho, reinou em seu lugar.

[[v12-21-19]]

^<<v12-21-19,19>>^ Tinha Amom vinte e dois anos de idade quando começou a reinar e reinou dois anos em Jerusalém. Sua mãe se chamava Mesulemete e era filha de Haruz, de Jotbá.

[[v12-21-20]]

^<<v12-21-20,20>>^ Fez o que era mau perante o SENHOR, como fizera Manassés, seu pai.

[[v12-21-21]]

^<<v12-21-21,21>>^ Andou em todo o caminho em que andara seu pai, serviu os ídolos a que ele servira e os adorou.

[[v12-21-22]]

^<<v12-21-22,22>>^ Assim, abandonou ele o SENHOR, Deus de seus pais, e não andou no caminho do SENHOR.

[[v12-21-23]]

^<<v12-21-23,23>>^ Os servos do rei Amom conspiraram contra ele e o mataram em sua própria casa.

[[v12-21-24]]

^<<v12-21-24,24>>^ Porém o povo da terra feriu todos os que conspiraram contra o rei Amom e constituiu a Josias, seu filho, rei em seu lugar.

[[v12-21-25]]

^<<v12-21-25,25>>^ Quanto aos mais atos de Amom e a tudo que fez, porventura, não estão escritos no Livro da História dos Reis de Judá?

[[v12-21-26]]

^<<v12-21-26,26>>^ Foi ele enterrado na sua sepultura, no jardim de Uzá; e Josias, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-020.adoc#v12-20-0[&#60; Capítulo Anterior] | <<v12-21-0,Topo>> | xref:012-2-reis/012-2-reis-022.adoc#v12-22-0[Próximo Capítulo &#62;]