include::./index.adoc[]

[[v12-14-0]]
=== 2 Reis, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-14-1]]

^<<v12-14-1,1>>^ No segundo ano de Jeoás, filho de Jeoacaz, rei de Israel, começou a reinar Amazias, filho de Joás, rei de Judá.

[[v12-14-2]]

^<<v12-14-2,2>>^ Tinha vinte e cinco anos quando começou a reinar e vinte e nove reinou em Jerusalém. Era o nome de sua mãe Jeoadã, de Jerusalém.

[[v12-14-3]]

^<<v12-14-3,3>>^ Fez ele o que era reto perante o SENHOR, ainda que não como Davi, seu pai; fez, porém, segundo tudo o que fizera Joás, seu pai.

[[v12-14-4]]

^<<v12-14-4,4>>^ Tão somente os altos não se tiraram; o povo ainda sacrificava e queimava incenso nos altos.

[[v12-14-5]]

^<<v12-14-5,5>>^ Uma vez confirmado o reino em sua mão, matou os seus servos que tinham assassinado o rei, seu pai.

[[v12-14-6]]

^<<v12-14-6,6>>^ Porém os filhos dos assassinos não matou, segundo está escrito no Livro da Lei de Moisés, no qual o SENHOR deu ordem, dizendo: Os pais não serão mortos por causa dos filhos, nem os filhos por causa dos pais; cada qual será morto pelo seu próprio pecado.

[[v12-14-7]]

^<<v12-14-7,7>>^ Ele feriu dez mil edomitas no vale do Sal e tomou a Sela na guerra; e chamou o seu nome Jocteel, até ao dia de hoje.

[[v12-14-8]]

^<<v12-14-8,8>>^ Então, Amazias enviou mensageiros a Jeoás, filho de Jeoacaz, filho de Jeú, rei de Israel, dizendo: Vem, meçamos armas.

[[v12-14-9]]

^<<v12-14-9,9>>^ Porém Jeoás, rei de Israel, respondeu a Amazias, rei de Judá: O cardo que está no Líbano mandou dizer ao cedro que lá está: Dá tua filha por mulher a meu filho; mas os animais do campo, que estavam no Líbano, passaram e pisaram o cardo.

[[v12-14-10]]

^<<v12-14-10,10>>^ Na verdade, feriste os edomitas, e o teu coração se ensoberbeceu; gloria-te disso e fica em casa; por que provocarias o mal para caíres tu, e Judá, contigo?

[[v12-14-11]]

^<<v12-14-11,11>>^ Mas Amazias não quis atendê-lo. Subiu, então, Jeoás, rei de Israel, e Amazias, rei de Judá, e mediram armas em Bete-Semes, que está em Judá.

[[v12-14-12]]

^<<v12-14-12,12>>^ Judá foi derrotado diante de Israel, e fugiu cada um para sua casa.

[[v12-14-13]]

^<<v12-14-13,13>>^ Jeoás, rei de Israel, prendeu Amazias, rei de Judá, filho de Joás, filho de Acazias, em Bete-Semes; e veio a Jerusalém, cujo muro ele rompeu desde a Porta de Efraim até à Porta da Esquina, quatrocentos côvados.

[[v12-14-14]]

^<<v12-14-14,14>>^ Tomou todo o ouro, e a prata, e todos os utensílios que se acharam na Casa do SENHOR e nos tesouros da casa do rei, como também reféns; e voltou para Samaria.

[[v12-14-15]]

^<<v12-14-15,15>>^ Ora, os mais atos de Jeoás, o que fez, o seu poder e como pelejou contra Amazias, rei de Judá, porventura, não estão escritos no Livro da História dos Reis de Israel?

[[v12-14-16]]

^<<v12-14-16,16>>^ Descansou Jeoás com seus pais e foi sepultado em Samaria, junto aos reis de Israel; e Jeroboão, seu filho, reinou em seu lugar.

[[v12-14-17]]

^<<v12-14-17,17>>^ Amazias, filho de Joás, rei de Judá, viveu quinze anos depois da morte de Jeoás, filho de Jeoacaz, rei de Israel.

[[v12-14-18]]

^<<v12-14-18,18>>^ Ora, os mais atos de Amazias, porventura, não estão escritos no Livro da História dos Reis de Judá?

[[v12-14-19]]

^<<v12-14-19,19>>^ Conspiraram contra ele em Jerusalém, e ele fugiu para Laquis; porém enviaram após ele homens até Laquis; e o mataram ali.

[[v12-14-20]]

^<<v12-14-20,20>>^ Trouxeram-no sobre cavalos e o sepultaram em Jerusalém, junto a seus pais, na Cidade de Davi.

[[v12-14-21]]

^<<v12-14-21,21>>^ Todo o povo de Judá tomou a Uzias, que era de dezesseis anos, e o constituiu rei em lugar de Amazias, seu pai.

[[v12-14-22]]

^<<v12-14-22,22>>^ Ele edificou a Elate e a restituiu a Judá, depois que o rei descansou com seus pais.

[[v12-14-23]]

^<<v12-14-23,23>>^ No décimo quinto ano de Amazias, filho de Joás, rei de Judá, começou a reinar em Samaria Jeroboão, filho de Jeoás, rei de Israel; e reinou quarenta e um anos.

[[v12-14-24]]

^<<v12-14-24,24>>^ Fez o que era mau perante o SENHOR; jamais se apartou de nenhum dos pecados de Jeroboão, filho de Nebate, que fez pecar a Israel.

[[v12-14-25]]

^<<v12-14-25,25>>^ Restabeleceu ele os limites de Israel, desde a entrada de Hamate até ao mar da Planície, segundo a palavra do SENHOR, Deus de Israel, a qual falara por intermédio de seu servo Jonas, filho de Amitai, o profeta, o qual era de Gate-Hefer.

[[v12-14-26]]

^<<v12-14-26,26>>^ Porque viu o SENHOR que a aflição de Israel era mui amarga, porque não havia nem escravo, nem livre, nem quem socorresse a Israel.

[[v12-14-27]]

^<<v12-14-27,27>>^ Ainda não falara o SENHOR em apagar o nome de Israel de debaixo do céu; porém os livrou por intermédio de Jeroboão, filho de Jeoás.

[[v12-14-28]]

^<<v12-14-28,28>>^ Quanto aos mais atos de Jeroboão, tudo quanto fez, o seu poder, como pelejou e como reconquistou Damasco e Hamate, pertencentes a Judá, para Israel, porventura, não estão escritos no Livro da História dos Reis de Israel?

[[v12-14-29]]

^<<v12-14-29,29>>^ Descansou Jeroboão com seus pais, com os reis de Israel; e Zacarias, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-013.adoc#v12-13-0[&#60; Capítulo Anterior] | <<v12-14-0,Topo>> | xref:012-2-reis/012-2-reis-015.adoc#v12-15-0[Próximo Capítulo &#62;]