include::./index.adoc[]

[[v12-18-0]]
=== 2 Reis, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-18-1]]

^<<v12-18-1,1>>^ No terceiro ano de Oseias, filho de Elá, rei de Israel, começou a reinar Ezequias, filho de Acaz, rei de Judá.

[[v12-18-2]]

^<<v12-18-2,2>>^ Tinha vinte e cinco anos de idade quando começou a reinar e reinou vinte e nove anos em Jerusalém; sua mãe se chamava Abi e era filha de Zacarias.

[[v12-18-3]]

^<<v12-18-3,3>>^ Fez ele o que era reto perante o SENHOR, segundo tudo o que fizera Davi, seu pai.

[[v12-18-4]]

^<<v12-18-4,4>>^ Removeu os altos, quebrou as colunas e deitou abaixo o poste-ídolo; e fez em pedaços a serpente de bronze que Moisés fizera, porque até àquele dia os filhos de Israel lhe queimavam incenso e lhe chamavam Neustã.

[[v12-18-5]]

^<<v12-18-5,5>>^ Confiou no SENHOR, Deus de Israel, de maneira que depois dele não houve seu semelhante entre todos os reis de Judá, nem entre os que foram antes dele.

[[v12-18-6]]

^<<v12-18-6,6>>^ Porque se apegou ao SENHOR, não deixou de segui-lo e guardou os mandamentos que o SENHOR ordenara a Moisés.

[[v12-18-7]]

^<<v12-18-7,7>>^ Assim, foi o SENHOR com ele; para onde quer que saía, lograva bom êxito; rebelou-se contra o rei da Assíria e não o serviu.

[[v12-18-8]]

^<<v12-18-8,8>>^ Feriu ele os filisteus até Gaza e seus limites, desde as atalaias dos vigias até à cidade fortificada.

[[v12-18-9]]

^<<v12-18-9,9>>^ No quarto ano do rei Ezequias, que era o sétimo de Oseias, filho de Elá, rei de Israel, subiu Salmaneser, rei da Assíria, contra Samaria e a cercou.

[[v12-18-10]]

^<<v12-18-10,10>>^ Ao cabo de três anos, foi tomada; sim, no ano sexto de Ezequias, que era o nono de Oseias, rei de Israel, Samaria foi tomada.

[[v12-18-11]]

^<<v12-18-11,11>>^ O rei da Assíria transportou a Israel para a Assíria e o fez habitar em Hala, junto a Habor e ao rio Gozã, e nas cidades dos medos;

[[v12-18-12]]

^<<v12-18-12,12>>^ porquanto não obedeceram à voz do SENHOR, seu Deus; antes, violaram a sua aliança e tudo quanto Moisés, servo do SENHOR, tinha ordenado; não o ouviram, nem o fizeram.

[[v12-18-13]]

^<<v12-18-13,13>>^ No ano décimo quarto do rei Ezequias, subiu Senaqueribe, rei da Assíria, contra todas as cidades fortificadas de Judá e as tomou.

[[v12-18-14]]

^<<v12-18-14,14>>^ Então, Ezequias, rei de Judá, enviou mensageiros ao rei da Assíria, a Laquis, dizendo: Errei; retira-te de mim; tudo o que me impuseres suportarei. Então, o rei da Assíria impôs a Ezequias, rei de Judá, trezentos talentos de prata e trinta talentos de ouro.

[[v12-18-15]]

^<<v12-18-15,15>>^ Deu-lhe Ezequias toda a prata que se achou na Casa do SENHOR e nos tesouros da casa do rei.

[[v12-18-16]]

^<<v12-18-16,16>>^ Foi quando Ezequias arrancou das portas do templo do SENHOR e das ombreiras o ouro de que ele, rei de Judá, as cobrira, e o deu ao rei da Assíria.

[[v12-18-17]]

^<<v12-18-17,17>>^ Contudo, o rei da Assíria enviou, de Laquis, a Tartã, a Rabe-Saris e a Rabsaqué, com um grande exército, ao rei Ezequias, a Jerusalém; subiram e vieram a Jerusalém. Tendo eles subido e chegado, pararam na extremidade do aqueduto do açude superior, junto ao caminho do campo do Lavandeiro.

[[v12-18-18]]

^<<v12-18-18,18>>^ Tendo eles chamado o rei, saíram-lhes ao encontro Eliaquim, filho de Hilquias, o mordomo, Sebna, o escrivão, e Joá, filho de Asafe, o cronista.

[[v12-18-19]]

^<<v12-18-19,19>>^ Rabsaqué lhes disse: Dizei a Ezequias: Assim diz o sumo rei, o rei da Assíria: Que confiança é essa em que te estribas?

[[v12-18-20]]

^<<v12-18-20,20>>^ Bem posso dizer-te que teu conselho e poder para guerra não passam de vãs palavras; em quem, pois, agora, confias, para que te rebeles contra mim?

[[v12-18-21]]

^<<v12-18-21,21>>^ Confias no Egito, esse bordão de cana esmagada, o qual, se alguém nele apoiar-se, lhe entrará pela mão e a traspassará; assim é Faraó, rei do Egito, para com todos os que nele confiam.

[[v12-18-22]]

^<<v12-18-22,22>>^ Mas, se me dizeis: Confiamos no SENHOR, nosso Deus, não é esse aquele cujos altos e altares Ezequias removeu, dizendo a Judá e a Jerusalém: Perante este altar adorareis em Jerusalém?

[[v12-18-23]]

^<<v12-18-23,23>>^ Ora, pois, empenha-te com meu senhor, rei da Assíria, e dar-te-ei dois mil cavalos, se de tua parte achares cavaleiros para os montar.

[[v12-18-24]]

^<<v12-18-24,24>>^ Como, pois, se não podes afugentar um só capitão dos menores dos servos do meu senhor, confias no Egito, por causa dos carros e cavaleiros?

[[v12-18-25]]

^<<v12-18-25,25>>^ Acaso, subi eu, agora, sem o SENHOR contra este lugar, para o destruir? Pois o SENHOR mesmo me disse: Sobe contra a terra e destrói-a.

[[v12-18-26]]

^<<v12-18-26,26>>^ Então, disseram Eliaquim, filho de Hilquias, Sebna e Joá a Rabsaqué: Rogamos-te que fales em aramaico aos teus servos, porque o entendemos, e não nos fales em judaico, aos ouvidos do povo que está sobre as muralhas.

[[v12-18-27]]

^<<v12-18-27,27>>^ Mas Rabsaqué lhes respondeu: Mandou-me, acaso, o meu senhor para dizer-te estas palavras a ti somente e a teu senhor? E não, antes, aos homens que estão sentados sobre as muralhas, para que comam convosco o seu próprio excremento e bebam a sua própria urina?

[[v12-18-28]]

^<<v12-18-28,28>>^ Então, Rabsaqué se pôs em pé, e clamou em alta voz em judaico, e disse: Ouvi as palavras do sumo rei, do rei da Assíria.

[[v12-18-29]]

^<<v12-18-29,29>>^ Assim diz o rei: Não vos engane Ezequias; porque não vos poderá livrar da sua mão;

[[v12-18-30]]

^<<v12-18-30,30>>^ nem tampouco vos faça Ezequias confiar no SENHOR, dizendo: O SENHOR, certamente, nos livrará, e esta cidade não será entregue nas mãos do rei da Assíria.

[[v12-18-31]]

^<<v12-18-31,31>>^ Não deis ouvidos a Ezequias; porque assim diz o rei da Assíria: Fazei as pazes comigo e vinde para mim; e comei, cada um da sua própria vide e da sua própria figueira, e bebei, cada um da água da sua própria cisterna.

[[v12-18-32]]

^<<v12-18-32,32>>^ Até que eu venha e vos leve para uma terra como a vossa, terra de cereal e de vinho, terra de pão e de vinhas, terra de oliveiras e de mel, para que vivais e não morrais. Não deis ouvidos a Ezequias, porque vos engana, dizendo: O SENHOR nos livrará.

[[v12-18-33]]

^<<v12-18-33,33>>^ Acaso, os deuses das nações puderam livrar, cada um a sua terra, das mãos do rei da Assíria?

[[v12-18-34]]

^<<v12-18-34,34>>^ Onde estão os deuses de Hamate e de Arpade? Onde estão os deuses de Sefarvaim, Hena e Iva? Acaso, livraram eles a Samaria das minhas mãos?

[[v12-18-35]]

^<<v12-18-35,35>>^ Quais são, dentre todos os deuses destes países, os que livraram a sua terra das minhas mãos, para que o SENHOR possa livrar a Jerusalém das minhas mãos?

[[v12-18-36]]

^<<v12-18-36,36>>^ Calou-se, porém, o povo e não lhe respondeu palavra; porque assim lhe havia ordenado o rei: Não lhe respondereis.

[[v12-18-37]]

^<<v12-18-37,37>>^ Então, Eliaquim, filho de Hilquias, o mordomo, e Sebna, o escrivão, e Joá, filho de Asafe, o cronista, vieram ter com Ezequias, com suas vestes rasgadas, e lhe referiram as palavras de Rabsaqué.

'''

xref:012-2-reis/012-2-reis-017.adoc#v12-17-0[&#60; Capítulo Anterior] | <<v12-18-0,Topo>> | xref:012-2-reis/012-2-reis-019.adoc#v12-19-0[Próximo Capítulo &#62;]