include::./index.adoc[]

[[v12-20-0]]
=== 2 Reis, 20
// ara ?, ARA - Almeida Revista e Atualizada

[[v12-20-1]]

^<<v12-20-1,1>>^ Naqueles dias, Ezequias adoeceu de uma enfermidade mortal; veio ter com ele o profeta Isaías, filho de Amoz, e lhe disse: Assim diz o SENHOR: Põe em ordem a tua casa, porque morrerás e não viverás.

[[v12-20-2]]

^<<v12-20-2,2>>^ Então, virou Ezequias o rosto para a parede e orou ao SENHOR, dizendo:

[[v12-20-3]]

^<<v12-20-3,3>>^ Lembra-te, SENHOR, peço-te, de que andei diante de ti com fidelidade, com inteireza de coração, e fiz o que era reto aos teus olhos; e chorou muitíssimo.

[[v12-20-4]]

^<<v12-20-4,4>>^ Antes que Isaías tivesse saído da parte central da cidade, veio a ele a palavra do SENHOR, dizendo:

[[v12-20-5]]

^<<v12-20-5,5>>^ Volta e dize a Ezequias, príncipe do meu povo: Assim diz o SENHOR, o Deus de Davi, teu pai: Ouvi a tua oração e vi as tuas lágrimas; eis que eu te curarei; ao terceiro dia, subirás à Casa do SENHOR.

[[v12-20-6]]

^<<v12-20-6,6>>^ Acrescentarei aos teus dias quinze anos e das mãos do rei da Assíria te livrarei, a ti e a esta cidade; e defenderei esta cidade por amor de mim e por amor de Davi, meu servo.

[[v12-20-7]]

^<<v12-20-7,7>>^ Disse mais Isaías: Tomai uma pasta de figos; tomaram-na e a puseram sobre a úlcera; e ele recuperou a saúde.

[[v12-20-8]]

^<<v12-20-8,8>>^ Ezequias disse a Isaías: Qual será o sinal de que o SENHOR me curará e de que, ao terceiro dia, subirei à Casa do SENHOR?

[[v12-20-9]]

^<<v12-20-9,9>>^ Respondeu Isaías: Ser-te-á isto da parte do SENHOR como sinal de que ele cumprirá a palavra que disse: Adiantar-se-á a sombra dez graus ou os retrocederá?

[[v12-20-10]]

^<<v12-20-10,10>>^ Então, disse Ezequias: É fácil que a sombra adiante dez graus; tal, porém, não aconteça; antes, retroceda dez graus.

[[v12-20-11]]

^<<v12-20-11,11>>^ Então, o profeta Isaías clamou ao SENHOR; e fez retroceder dez graus a sombra lançada pelo sol declinante no relógio de Acaz.

[[v12-20-12]]

^<<v12-20-12,12>>^ Nesse tempo, Merodaque-Baladã, filho de Baladã, rei da Babilônia, enviou cartas e um presente a Ezequias, porque soube que estivera doente.

[[v12-20-13]]

^<<v12-20-13,13>>^ Ezequias se agradou dos mensageiros e lhes mostrou toda a casa do seu tesouro, a prata, o ouro, as especiarias, os óleos finos, o seu arsenal e tudo quanto se achava nos seus tesouros; nenhuma coisa houve, nem em sua casa, nem em todo o seu domínio que Ezequias não lhes mostrasse.

[[v12-20-14]]

^<<v12-20-14,14>>^ Então, Isaías, o profeta, veio ao rei Ezequias e lhe disse: Que foi que aqueles homens disseram e donde vieram a ti? Respondeu Ezequias: De uma terra longínqua vieram, da Babilônia.

[[v12-20-15]]

^<<v12-20-15,15>>^ Perguntou ele: Que viram em tua casa? Respondeu Ezequias: Viram tudo quanto há em minha casa; coisa nenhuma há nos meus tesouros que eu não lhes mostrasse.

[[v12-20-16]]

^<<v12-20-16,16>>^ Então, disse Isaías a Ezequias: Ouve a palavra do SENHOR:

[[v12-20-17]]

^<<v12-20-17,17>>^ Eis que virão dias em que tudo quanto houver em tua casa, com o que entesouraram teus pais até ao dia de hoje, será levado para a Babilônia; não ficará coisa alguma, disse o SENHOR.

[[v12-20-18]]

^<<v12-20-18,18>>^ Dos teus próprios filhos, que tu gerares, tomarão, para que sejam eunucos no palácio do rei da Babilônia.

[[v12-20-19]]

^<<v12-20-19,19>>^ Então, disse Ezequias a Isaías: Boa é a palavra do SENHOR que disseste. Pois pensava: Haverá paz e segurança em meus dias.

[[v12-20-20]]

^<<v12-20-20,20>>^ Quanto aos mais atos de Ezequias, e todo o seu poder, e como fez o açude e o aqueduto, e trouxe água para dentro da cidade, porventura, não estão escritos no Livro da História dos Reis de Judá?

[[v12-20-21]]

^<<v12-20-21,21>>^ Descansou Ezequias com seus pais; e Manassés, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-019.adoc#v12-19-0[&#60; Capítulo Anterior] | <<v12-20-0,Topo>> | xref:012-2-reis/012-2-reis-021.adoc#v12-21-0[Próximo Capítulo &#62;]