include::./index.adoc[]

[[v1-21-0]]
=== Gênesis, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-21-1]]

^<<v1-21-1,1>>^ Visitou o SENHOR a Sara, como lhe dissera, e o SENHOR cumpriu o que lhe havia prometido.

[[v1-21-2]]

^<<v1-21-2,2>>^ Sara concebeu e deu à luz um filho a Abraão na sua velhice, no tempo determinado, de que Deus lhe falara.

[[v1-21-3]]

^<<v1-21-3,3>>^ Ao filho que lhe nasceu, que Sara lhe dera à luz, pôs Abraão o nome de Isaque.

[[v1-21-4]]

^<<v1-21-4,4>>^ Abraão circuncidou a seu filho Isaque, quando este era de oito dias, segundo Deus lhe havia ordenado.

[[v1-21-5]]

^<<v1-21-5,5>>^ Tinha Abraão cem anos, quando lhe nasceu Isaque, seu filho.

[[v1-21-6]]

^<<v1-21-6,6>>^ E disse Sara: Deus me deu motivo de riso; e todo aquele que ouvir isso vai rir-se juntamente comigo.

[[v1-21-7]]

^<<v1-21-7,7>>^ E acrescentou: Quem teria dito a Abraão que Sara amamentaria um filho? Pois na sua velhice lhe dei um filho.

[[v1-21-8]]

^<<v1-21-8,8>>^ Isaque cresceu e foi desmamado. Nesse dia em que o menino foi desmamado, deu Abraão um grande banquete.

[[v1-21-9]]

^<<v1-21-9,9>>^ Vendo Sara que o filho de Agar, a egípcia, o qual ela dera à luz a Abraão, caçoava de Isaque,

[[v1-21-10]]

^<<v1-21-10,10>>^ disse a Abraão: Rejeita essa escrava e seu filho; porque o filho dessa escrava não será herdeiro com Isaque, meu filho.

[[v1-21-11]]

^<<v1-21-11,11>>^ Pareceu isso mui penoso aos olhos de Abraão, por causa de seu filho.

[[v1-21-12]]

^<<v1-21-12,12>>^ Disse, porém, Deus a Abraão: Não te pareça isso mal por causa do moço e por causa da tua serva; atende a Sara em tudo o que ela te disser; porque por Isaque será chamada a tua descendência.

[[v1-21-13]]

^<<v1-21-13,13>>^ Mas também do filho da serva farei uma grande nação, por ser ele teu descendente.

[[v1-21-14]]

^<<v1-21-14,14>>^ Levantou-se, pois, Abraão de madrugada, tomou pão e um odre de água, pô-los às costas de Agar, deu-lhe o menino e a despediu. Ela saiu, andando errante pelo deserto de Berseba.

[[v1-21-15]]

^<<v1-21-15,15>>^ Tendo-se acabado a água do odre, colocou ela o menino debaixo de um dos arbustos

[[v1-21-16]]

^<<v1-21-16,16>>^ e, afastando-se, foi sentar-se defronte, à distância de um tiro de arco; porque dizia: Assim, não verei morrer o menino; e, sentando-se em frente dele, levantou a voz e chorou.

[[v1-21-17]]

^<<v1-21-17,17>>^ Deus, porém, ouviu a voz do menino; e o Anjo de Deus chamou do céu a Agar e lhe disse: Que tens, Agar? Não temas, porque Deus ouviu a voz do menino, daí onde está.

[[v1-21-18]]

^<<v1-21-18,18>>^ Ergue-te, levanta o rapaz, segura-o pela mão, porque eu farei dele um grande povo.

[[v1-21-19]]

^<<v1-21-19,19>>^ Abrindo-lhe Deus os olhos, viu ela um poço de água, e, indo a ele, encheu de água o odre, e deu de beber ao rapaz.

[[v1-21-20]]

^<<v1-21-20,20>>^ Deus estava com o rapaz, que cresceu, habitou no deserto e se tornou flecheiro;

[[v1-21-21]]

^<<v1-21-21,21>>^ habitou no deserto de Parã, e sua mãe o casou com uma mulher da terra do Egito.

[[v1-21-22]]

^<<v1-21-22,22>>^ Por esse tempo, Abimeleque e Ficol, comandante do seu exército, disseram a Abraão: Deus é contigo em tudo o que fazes;

[[v1-21-23]]

^<<v1-21-23,23>>^ agora, pois, jura-me aqui por Deus que me não mentirás, nem a meu filho, nem a meu neto; e sim que usarás comigo e com a terra em que tens habitado daquela mesma bondade com que eu te tratei.

[[v1-21-24]]

^<<v1-21-24,24>>^ Respondeu Abraão: Juro.

[[v1-21-25]]

^<<v1-21-25,25>>^ Nada obstante, Abraão repreendeu a Abimeleque por causa de um poço de água que os servos deste lhe haviam tomado à força.

[[v1-21-26]]

^<<v1-21-26,26>>^ Respondeu-lhe Abimeleque: Não sei quem terá feito isso; também nada me fizeste saber, nem tampouco ouvi falar disso, senão hoje.

[[v1-21-27]]

^<<v1-21-27,27>>^ Tomou Abraão ovelhas e bois e deu-os a Abimeleque; e fizeram ambos uma aliança.

[[v1-21-28]]

^<<v1-21-28,28>>^ Pôs Abraão à parte sete cordeiras do rebanho.

[[v1-21-29]]

^<<v1-21-29,29>>^ Perguntou Abimeleque a Abraão: Que significam as sete cordeiras que puseste à parte?

[[v1-21-30]]

^<<v1-21-30,30>>^ Respondeu Abraão: Receberás de minhas mãos as sete cordeiras, para que me sirvam de testemunho de que eu cavei este poço.

[[v1-21-31]]

^<<v1-21-31,31>>^ Por isso, se chamou aquele lugar Berseba, porque ali juraram eles ambos.

[[v1-21-32]]

^<<v1-21-32,32>>^ Assim, fizeram aliança em Berseba; levantaram-se Abimeleque e Ficol, comandante do seu exército, e voltaram para as terras dos filisteus.

[[v1-21-33]]

^<<v1-21-33,33>>^ Plantou Abraão tamargueiras em Berseba e invocou ali o nome do SENHOR, Deus Eterno.

[[v1-21-34]]

^<<v1-21-34,34>>^ E foi Abraão, por muito tempo, morador na terra dos filisteus.

'''

xref:001-genesis/001-genesis-020.adoc#v1-20-0[&#60; Capítulo Anterior] | <<v1-21-0,Topo>> | xref:001-genesis/001-genesis-022.adoc#v1-22-0[Próximo Capítulo &#62;]