include::./index.adoc[]

[[v1-24-0]]
=== Gênesis, 24
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-24-1]]

^<<v1-24-1,1>>^ Era Abraão já idoso, bem avançado em anos; e o SENHOR em tudo o havia abençoado.

[[v1-24-2]]

^<<v1-24-2,2>>^ Disse Abraão ao seu mais antigo servo da casa, que governava tudo o que possuía: Põe a mão por baixo da minha coxa,

[[v1-24-3]]

^<<v1-24-3,3>>^ para que eu te faça jurar pelo SENHOR, Deus do céu e da terra, que não tomarás esposa para meu filho das filhas dos cananeus, entre os quais habito;

[[v1-24-4]]

^<<v1-24-4,4>>^ mas irás à minha parentela e daí tomarás esposa para Isaque, meu filho.

[[v1-24-5]]

^<<v1-24-5,5>>^ Disse-lhe o servo: Talvez não queira a mulher seguir-me para esta terra; nesse caso, levarei teu filho à terra donde saíste?

[[v1-24-6]]

^<<v1-24-6,6>>^ Respondeu-lhe Abraão: Cautela! Não faças voltar para lá meu filho.

[[v1-24-7]]

^<<v1-24-7,7>>^ O SENHOR, Deus do céu, que me tirou da casa de meu pai e de minha terra natal, e que me falou, e jurou, dizendo: À tua descendência darei esta terra, ele enviará o seu anjo, que te há de preceder, e tomarás de lá esposa para meu filho.

[[v1-24-8]]

^<<v1-24-8,8>>^ Caso a mulher não queira seguir-te, ficarás desobrigado do teu juramento; entretanto, não levarás para lá meu filho.

[[v1-24-9]]

^<<v1-24-9,9>>^ Com isso, pôs o servo a mão por baixo da coxa de Abraão, seu senhor, e jurou fazer segundo o resolvido.

[[v1-24-10]]

^<<v1-24-10,10>>^ Tomou o servo dez dos camelos do seu senhor e, levando consigo de todos os bens dele, levantou-se e partiu, rumo da Mesopotâmia, para a cidade de Naor.

[[v1-24-11]]

^<<v1-24-11,11>>^ Fora da cidade, fez ajoelhar os camelos junto a um poço de água, à tarde, hora em que as moças saem a tirar água.

[[v1-24-12]]

^<<v1-24-12,12>>^ E disse consigo: Ó SENHOR, Deus de meu senhor Abraão, rogo-te que me acudas hoje e uses de bondade para com o meu senhor Abraão!

[[v1-24-13]]

^<<v1-24-13,13>>^ Eis que estou ao pé da fonte de água, e as filhas dos homens desta cidade saem para tirar água;

[[v1-24-14]]

^<<v1-24-14,14>>^ dá-me, pois, que a moça a quem eu disser: inclina o cântaro para que eu beba; e ela me responder: Bebe, e darei ainda de beber aos teus camelos, seja a que designaste para o teu servo Isaque; e nisso verei que usaste de bondade para com o meu senhor.

[[v1-24-15]]

^<<v1-24-15,15>>^ Considerava ele ainda, quando saiu Rebeca, filha de Betuel, filho de Milca, mulher de Naor, irmão de Abraão, trazendo um cântaro ao ombro.

[[v1-24-16]]

^<<v1-24-16,16>>^ A moça era mui formosa de aparência, virgem, a quem nenhum homem havia possuído; ela desceu à fonte, encheu o seu cântaro e subiu.

[[v1-24-17]]

^<<v1-24-17,17>>^ Então, o servo saiu-lhe ao encontro e disse: Dá-me de beber um pouco da água do teu cântaro.

[[v1-24-18]]

^<<v1-24-18,18>>^ Ela respondeu: Bebe, meu senhor. E, prontamente, baixando o cântaro para a mão, lhe deu de beber.

[[v1-24-19]]

^<<v1-24-19,19>>^ Acabando ela de dar a beber, disse: Tirarei água também para os teus camelos, até que todos bebam.

[[v1-24-20]]

^<<v1-24-20,20>>^ E, apressando-se em despejar o cântaro no bebedouro, correu outra vez ao poço para tirar mais água; tirou-a e deu-a a todos os camelos.

[[v1-24-21]]

^<<v1-24-21,21>>^ O homem a observava, em silêncio, atentamente, para saber se teria o SENHOR levado a bom termo a sua jornada ou não.

[[v1-24-22]]

^<<v1-24-22,22>>^ Tendo os camelos acabado de beber, tomou o homem um pendente de ouro de meio siclo de peso e duas pulseiras para as mãos dela, do peso de dez siclos de ouro;

[[v1-24-23]]

^<<v1-24-23,23>>^ e lhe perguntou: De quem és filha? Peço-te que me digas. Haverá em casa de teu pai lugar em que eu fique, e a comitiva?

[[v1-24-24]]

^<<v1-24-24,24>>^ Ela respondeu: Sou filha de Betuel, filho de Milca, o qual ela deu à luz a Naor.

[[v1-24-25]]

^<<v1-24-25,25>>^ E acrescentou: Temos palha, e muito pasto, e lugar para passar a noite.

[[v1-24-26]]

^<<v1-24-26,26>>^ Então, se inclinou o homem e adorou ao SENHOR.

[[v1-24-27]]

^<<v1-24-27,27>>^ E disse: Bendito seja o SENHOR, Deus de meu senhor Abraão, que não retirou a sua benignidade e a sua verdade de meu senhor; quanto a mim, estando no caminho, o SENHOR me guiou à casa dos parentes de meu senhor.

[[v1-24-28]]

^<<v1-24-28,28>>^ E a moça correu e contou aos da casa de sua mãe todas essas coisas.

[[v1-24-29]]

^<<v1-24-29,29>>^ Ora, Rebeca tinha um irmão, chamado Labão; este correu ao encontro do homem junto à fonte.

[[v1-24-30]]

^<<v1-24-30,30>>^ Pois, quando viu o pendente e as pulseiras nas mãos de sua irmã, tendo ouvido as palavras de Rebeca, sua irmã, que dizia: Assim me falou o homem, foi Labão ter com ele, o qual estava em pé junto aos camelos, junto à fonte.

[[v1-24-31]]

^<<v1-24-31,31>>^ E lhe disse: Entra, bendito do SENHOR, por que estás aí fora? Pois já preparei a casa e o lugar para os camelos.

[[v1-24-32]]

^<<v1-24-32,32>>^ Então, fez entrar o homem; descarregaram-lhe os camelos e lhes deram forragem e pasto; deu-se-lhe água para lavar os pés e também aos homens que estavam com ele.

[[v1-24-33]]

^<<v1-24-33,33>>^ Diante dele puseram comida; porém ele disse: Não comerei enquanto não expuser o propósito a que venho. Labão respondeu-lhe: Dize.

[[v1-24-34]]

^<<v1-24-34,34>>^ Então, disse: Sou servo de Abraão.

[[v1-24-35]]

^<<v1-24-35,35>>^ O SENHOR tem abençoado muito ao meu senhor, e ele se tornou grande; deu-lhe ovelhas e bois, e prata e ouro, e servos e servas, e camelos e jumentos.

[[v1-24-36]]

^<<v1-24-36,36>>^ Sara, mulher do meu senhor, era já idosa quando lhe deu à luz um filho; a este deu ele tudo quanto tem.

[[v1-24-37]]

^<<v1-24-37,37>>^ E meu senhor me fez jurar, dizendo: Não tomarás esposa para meu filho das mulheres dos cananeus, em cuja terra habito;

[[v1-24-38]]

^<<v1-24-38,38>>^ porém irás à casa de meu pai e à minha família e tomarás esposa para meu filho.

[[v1-24-39]]

^<<v1-24-39,39>>^ Respondi ao meu senhor: Talvez não queira a mulher seguir-me.

[[v1-24-40]]

^<<v1-24-40,40>>^ Ele me disse: O SENHOR, em cuja presença eu ando, enviará contigo o seu Anjo e levará a bom termo a tua jornada, para que, da minha família e da casa de meu pai, tomes esposa para meu filho.

[[v1-24-41]]

^<<v1-24-41,41>>^ Então, serás desobrigado do meu juramento, quando fores à minha família; se não ta derem, desobrigado estarás do meu juramento.

[[v1-24-42]]

^<<v1-24-42,42>>^ Hoje, pois, cheguei à fonte e disse comigo: ó SENHOR, Deus de meu senhor Abraão, se me levas a bom termo a jornada em que sigo,

[[v1-24-43]]

^<<v1-24-43,43>>^ eis-me agora junto à fonte de água; a moça que sair para tirar água, a quem eu disser: dá-me um pouco de água do teu cântaro,

[[v1-24-44]]

^<<v1-24-44,44>>^ e ela me responder: Bebe, e também tirarei água para os teus camelos, seja essa a mulher que o SENHOR designou para o filho de meu senhor.

[[v1-24-45]]

^<<v1-24-45,45>>^ Considerava ainda eu assim, no meu íntimo, quando saiu Rebeca trazendo o seu cântaro ao ombro, desceu à fonte e tirou água. E eu lhe disse: peço-te que me dês de beber.

[[v1-24-46]]

^<<v1-24-46,46>>^ Ela se apressou e, baixando o cântaro do ombro, disse: Bebe, e também darei de beber aos teus camelos. Bebi, e ela deu de beber aos camelos.

[[v1-24-47]]

^<<v1-24-47,47>>^ Daí lhe perguntei: de quem és filha? Ela respondeu: Filha de Betuel, filho de Naor e Milca. Então, lhe pus o pendente no nariz e as pulseiras nas mãos.

[[v1-24-48]]

^<<v1-24-48,48>>^ E, prostrando-me, adorei ao SENHOR e bendisse ao SENHOR, Deus do meu senhor Abraão, que me havia conduzido por um caminho direito, a fim de tomar para o filho do meu senhor uma filha do seu parente.

[[v1-24-49]]

^<<v1-24-49,49>>^ Agora, pois, se haveis de usar de benevolência e de verdade para com o meu senhor, fazei-mo saber; se não, declarai-mo, para que eu vá, ou para a direita ou para a esquerda.

[[v1-24-50]]

^<<v1-24-50,50>>^ Então, responderam Labão e Betuel: Isto procede do SENHOR, nada temos a dizer fora da sua verdade.

[[v1-24-51]]

^<<v1-24-51,51>>^ Eis Rebeca na tua presença; toma-a e vai-te; seja ela a mulher do filho do teu senhor, segundo a palavra do SENHOR.

[[v1-24-52]]

^<<v1-24-52,52>>^ Tendo ouvido o servo de Abraão tais palavras, prostrou-se em terra diante do SENHOR;

[[v1-24-53]]

^<<v1-24-53,53>>^ e tirou joias de ouro e de prata e vestidos e os deu a Rebeca; também deu ricos presentes a seu irmão e a sua mãe.

[[v1-24-54]]

^<<v1-24-54,54>>^ Depois, comeram, e beberam, ele e os homens que estavam com ele, e passaram a noite. De madrugada, quando se levantaram, disse o servo: Permiti que eu volte ao meu senhor.

[[v1-24-55]]

^<<v1-24-55,55>>^ Mas o irmão e a mãe da moça disseram: Fique ela ainda conosco alguns dias, pelo menos dez; e depois irá.

[[v1-24-56]]

^<<v1-24-56,56>>^ Ele, porém, lhes disse: Não me detenhais, pois o SENHOR me tem levado a bom termo na jornada; permiti que eu volte ao meu senhor.

[[v1-24-57]]

^<<v1-24-57,57>>^ Disseram: Chamemos a moça e ouçamo-la pessoalmente.

[[v1-24-58]]

^<<v1-24-58,58>>^ Chamaram, pois, a Rebeca e lhe perguntaram: Queres ir com este homem? Ela respondeu: Irei.

[[v1-24-59]]

^<<v1-24-59,59>>^ Então, despediram a Rebeca, sua irmã, e a sua ama, e ao servo de Abraão, e a seus homens.

[[v1-24-60]]

^<<v1-24-60,60>>^ Abençoaram a Rebeca e lhe disseram: És nossa irmã; sê tu a mãe de milhares de milhares, e que a tua descendência possua a porta dos seus inimigos.

[[v1-24-61]]

^<<v1-24-61,61>>^ Então, se levantou Rebeca com suas moças e, montando os camelos, seguiram o homem. O servo tomou a Rebeca e partiu.

[[v1-24-62]]

^<<v1-24-62,62>>^ Ora, Isaque vinha de caminho de Beer-Laai-Roi, porque habitava na terra do Neguebe.

[[v1-24-63]]

^<<v1-24-63,63>>^ Saíra Isaque a meditar no campo, ao cair da tarde; erguendo os olhos, viu, e eis que vinham camelos.

[[v1-24-64]]

^<<v1-24-64,64>>^ Também Rebeca levantou os olhos, e, vendo a Isaque, apeou do camelo,

[[v1-24-65]]

^<<v1-24-65,65>>^ e perguntou ao servo: Quem é aquele homem que vem pelo campo ao nosso encontro? É o meu senhor, respondeu. Então, tomou ela o véu e se cobriu.

[[v1-24-66]]

^<<v1-24-66,66>>^ O servo contou a Isaque todas as coisas que havia feito.

[[v1-24-67]]

^<<v1-24-67,67>>^ Isaque conduziu-a até à tenda de Sara, mãe dele, e tomou a Rebeca, e esta lhe foi por mulher. Ele a amou; assim, foi Isaque consolado depois da morte de sua mãe.

'''

xref:001-genesis/001-genesis-023.adoc#v1-23-0[&#60; Capítulo Anterior] | <<v1-24-0,Topo>> | xref:001-genesis/001-genesis-025.adoc#v1-25-0[Próximo Capítulo &#62;]