include::./index.adoc[]

[[v1-2-0]]
=== Gênesis, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-2-1]]

^<<v1-2-1,1>>^ Assim, pois, foram acabados os céus e a terra e todo o seu exército.

[[v1-2-2]]

^<<v1-2-2,2>>^ E, havendo Deus terminado no dia sétimo a sua obra, que fizera, descansou nesse dia de toda a sua obra que tinha feito.

[[v1-2-3]]

^<<v1-2-3,3>>^ E abençoou Deus o dia sétimo e o santificou; porque nele descansou de toda a obra que, como Criador, fizera.

[[v1-2-4]]

^<<v1-2-4,4>>^ Esta é a gênese dos céus e da terra quando foram criados, quando o SENHOR Deus os criou.

[[v1-2-5]]

^<<v1-2-5,5>>^ Não havia ainda nenhuma planta do campo na terra, pois ainda nenhuma erva do campo havia brotado; porque o SENHOR Deus não fizera chover sobre a terra, e também não havia homem para lavrar o solo.

[[v1-2-6]]

^<<v1-2-6,6>>^ Mas uma neblina subia da terra e regava toda a superfície do solo.

[[v1-2-7]]

^<<v1-2-7,7>>^ Então, formou o SENHOR Deus ao homem do pó da terra e lhe soprou nas narinas o fôlego de vida, e o homem passou a ser alma vivente.

[[v1-2-8]]

^<<v1-2-8,8>>^ E plantou o SENHOR Deus um jardim no Éden, na direção do Oriente, e pôs nele o homem que havia formado.

[[v1-2-9]]

^<<v1-2-9,9>>^ Do solo fez o SENHOR Deus brotar toda sorte de árvores agradáveis à vista e boas para alimento; e também a árvore da vida no meio do jardim e a árvore do conhecimento do bem e do mal.

[[v1-2-10]]

^<<v1-2-10,10>>^ E saía um rio do Éden para regar o jardim e dali se dividia, repartindo-se em quatro braços.

[[v1-2-11]]

^<<v1-2-11,11>>^ O primeiro chama-se Pisom; é o que rodeia a terra de Havilá, onde há ouro.

[[v1-2-12]]

^<<v1-2-12,12>>^ O ouro dessa terra é bom; também se encontram lá o bdélio e a pedra de ônix.

[[v1-2-13]]

^<<v1-2-13,13>>^ O segundo rio chama-se Giom; é o que circunda a terra de Cuxe.

[[v1-2-14]]

^<<v1-2-14,14>>^ O nome do terceiro rio é Tigre; é o que corre pelo oriente da Assíria. E o quarto é o Eufrates.

[[v1-2-15]]

^<<v1-2-15,15>>^ Tomou, pois, o SENHOR Deus ao homem e o colocou no jardim do Éden para o cultivar e o guardar.

[[v1-2-16]]

^<<v1-2-16,16>>^ E o SENHOR Deus lhe deu esta ordem: De toda árvore do jardim comerás livremente,

[[v1-2-17]]

^<<v1-2-17,17>>^ mas da árvore do conhecimento do bem e do mal não comerás; porque, no dia em que dela comeres, certamente morrerás.

[[v1-2-18]]

^<<v1-2-18,18>>^ Disse mais o SENHOR Deus: Não é bom que o homem esteja só; far-lhe-ei uma auxiliadora que lhe seja idônea.

[[v1-2-19]]

^<<v1-2-19,19>>^ Havendo, pois, o SENHOR Deus formado da terra todos os animais do campo e todas as aves dos céus, trouxe-os ao homem, para ver como este lhes chamaria; e o nome que o homem desse a todos os seres viventes, esse seria o nome deles.

[[v1-2-20]]

^<<v1-2-20,20>>^ Deu nome o homem a todos os animais domésticos, às aves dos céus e a todos os animais selváticos; para o homem, todavia, não se achava uma auxiliadora que lhe fosse idônea.

[[v1-2-21]]

^<<v1-2-21,21>>^ Então, o SENHOR Deus fez cair pesado sono sobre o homem, e este adormeceu; tomou uma das suas costelas e fechou o lugar com carne.

[[v1-2-22]]

^<<v1-2-22,22>>^ E a costela que o SENHOR Deus tomara ao homem, transformou-a numa mulher e lha trouxe.

[[v1-2-23]]

^<<v1-2-23,23>>^ E disse o homem: Esta, afinal, é osso dos meus ossos e carne da minha carne; chamar-se-á varoa, porquanto do varão foi tomada.

[[v1-2-24]]

^<<v1-2-24,24>>^ Por isso, deixa o homem pai e mãe e se une à sua mulher, tornando-se os dois uma só carne.

[[v1-2-25]]

^<<v1-2-25,25>>^ Ora, um e outro, o homem e sua mulher, estavam nus e não se envergonhavam.

'''

xref:001-genesis/001-genesis-001.adoc#v1-1-0[&#60; Capítulo Anterior] | <<v1-2-0,Topo>> | xref:001-genesis/001-genesis-003.adoc#v1-3-0[Próximo Capítulo &#62;]