include::./index.adoc[]

[[v1-50-0]]
=== Gênesis, 50
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-50-1]]

^<<v1-50-1,1>>^ Então, José se lançou sobre o rosto de seu pai, e chorou sobre ele, e o beijou.

[[v1-50-2]]

^<<v1-50-2,2>>^ Ordenou José a seus servos, aos que eram médicos, que embalsamassem a seu pai; e os médicos embalsamaram a Israel,

[[v1-50-3]]

^<<v1-50-3,3>>^ gastando nisso quarenta dias, pois assim se cumprem os dias do embalsamamento; e os egípcios o choraram setenta dias.

[[v1-50-4]]

^<<v1-50-4,4>>^ Passados os dias de o chorarem, falou José à casa de Faraó: Se agora achei mercê perante vós, rogo-vos que faleis aos ouvidos de Faraó, dizendo:

[[v1-50-5]]

^<<v1-50-5,5>>^ Meu pai me fez jurar, declarando: Eis que eu morro; no meu sepulcro que abri para mim na terra de Canaã, ali me sepultarás. Agora, pois, desejo subir e sepultar meu pai, depois voltarei.

[[v1-50-6]]

^<<v1-50-6,6>>^ Respondeu Faraó: Sobe e sepulta o teu pai como ele te fez jurar.

[[v1-50-7]]

^<<v1-50-7,7>>^ José subiu para sepultar o seu pai; e subiram com ele todos os oficiais de Faraó, os principais da sua casa e todos os principais da terra do Egito,

[[v1-50-8]]

^<<v1-50-8,8>>^ como também toda a casa de José, e seus irmãos, e a casa de seu pai; somente deixaram na terra de Gósen as crianças, e os rebanhos, e o gado.

[[v1-50-9]]

^<<v1-50-9,9>>^ E subiram também com ele tanto carros como cavaleiros; e o cortejo foi grandíssimo.

[[v1-50-10]]

^<<v1-50-10,10>>^ Chegando eles, pois, à eira de Atade, que está além do Jordão, fizeram ali grande e intensa lamentação; e José pranteou seu pai durante sete dias.

[[v1-50-11]]

^<<v1-50-11,11>>^ Tendo visto os moradores da terra, os cananeus, o luto na eira de Atade, disseram: Grande pranto é este dos egípcios. E por isso se chamou aquele lugar de Abel-Mizraim, que está além do Jordão.

[[v1-50-12]]

^<<v1-50-12,12>>^ Fizeram-lhe seus filhos como lhes havia ordenado:

[[v1-50-13]]

^<<v1-50-13,13>>^ levaram-no para a terra de Canaã e o sepultaram na caverna do campo de Macpela, que Abraão comprara com o campo, por posse de sepultura, a Efrom, o heteu, fronteiro a Manre.

[[v1-50-14]]

^<<v1-50-14,14>>^ Depois disso, voltou José para o Egito, ele, seus irmãos e todos os que com ele subiram a sepultar o seu pai.

[[v1-50-15]]

^<<v1-50-15,15>>^ Vendo os irmãos de José que seu pai já era morto, disseram: É o caso de José nos perseguir e nos retribuir certamente o mal todo que lhe fizemos.

[[v1-50-16]]

^<<v1-50-16,16>>^ Portanto, mandaram dizer a José: Teu pai ordenou, antes da sua morte, dizendo:

[[v1-50-17]]

^<<v1-50-17,17>>^ Assim direis a José: Perdoa, pois, a transgressão de teus irmãos e o seu pecado, porque te fizeram mal; agora, pois, te rogamos que perdoes a transgressão dos servos do Deus de teu pai. José chorou enquanto lhe falavam.

[[v1-50-18]]

^<<v1-50-18,18>>^ Depois, vieram também seus irmãos, prostraram-se diante dele e disseram: Eis-nos aqui por teus servos.

[[v1-50-19]]

^<<v1-50-19,19>>^ Respondeu-lhes José: Não temais; acaso, estou eu em lugar de Deus?

[[v1-50-20]]

^<<v1-50-20,20>>^ Vós, na verdade, intentastes o mal contra mim; porém Deus o tornou em bem, para fazer, como vedes agora, que se conserve muita gente em vida.

[[v1-50-21]]

^<<v1-50-21,21>>^ Não temais, pois; eu vos sustentarei a vós outros e a vossos filhos. Assim, os consolou e lhes falou ao coração.

[[v1-50-22]]

^<<v1-50-22,22>>^ José habitou no Egito, ele e a casa de seu pai; e viveu cento e dez anos.

[[v1-50-23]]

^<<v1-50-23,23>>^ Viu José os filhos de Efraim até à terceira geração; também os filhos de Maquir, filho de Manassés, os quais José tomou sobre seus joelhos.

[[v1-50-24]]

^<<v1-50-24,24>>^ Disse José a seus irmãos: Eu morro; porém Deus certamente vos visitará e vos fará subir desta terra para a terra que jurou dar a Abraão, a Isaque e a Jacó.

[[v1-50-25]]

^<<v1-50-25,25>>^ José fez jurar os filhos de Israel, dizendo: Certamente Deus vos visitará, e fareis transportar os meus ossos daqui.

[[v1-50-26]]

^<<v1-50-26,26>>^ Morreu José da idade de cento e dez anos; embalsamaram-no e o puseram num caixão no Egito.

'''

xref:001-genesis/001-genesis-049.adoc#v1-49-0[&#60; Capítulo Anterior] | <<v1-50-0,Topo>> | xref:002-exodo/002-exodo-001.adoc#v2-1-0[Próximo Capítulo &#62;]