include::./index.adoc[]

[[v1-14-0]]
=== Gênesis, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-14-1]]

^<<v1-14-1,1>>^ Sucedeu naquele tempo que Anrafel, rei de Sinar, Arioque, rei de Elasar, Quedorlaomer, rei de Elão, e Tidal, rei de Goim,

[[v1-14-2]]

^<<v1-14-2,2>>^ fizeram guerra contra Bera, rei de Sodoma, contra Birsa, rei de Gomorra, contra Sinabe, rei de Admá, contra Semeber, rei de Zeboim, e contra o rei de Bela (esta é Zoar).

[[v1-14-3]]

^<<v1-14-3,3>>^ Todos estes se ajuntaram no vale de Sidim (que é o mar Salgado).

[[v1-14-4]]

^<<v1-14-4,4>>^ Doze anos serviram a Quedorlaomer, porém no décimo terceiro se rebelaram.

[[v1-14-5]]

^<<v1-14-5,5>>^ Ao décimo quarto ano, veio Quedorlaomer e os reis que estavam com ele e feriram aos refains em Asterote-Carnaim, e aos zuzins em Hã, e aos emins em Savé-Quiriataim,

[[v1-14-6]]

^<<v1-14-6,6>>^ e aos horeus no seu monte Seir, até El-Parã, que está junto ao deserto.

[[v1-14-7]]

^<<v1-14-7,7>>^ De volta passaram em En-Mispate (que é Cades) e feriram toda a terra dos amalequitas e dos amorreus, que habitavam em Hazazom-Tamar.

[[v1-14-8]]

^<<v1-14-8,8>>^ Então, saíram os reis de Sodoma, de Gomorra, de Admá, de Zeboim e de Bela (esta é Zoar) e se ordenaram e levantaram batalha contra eles no vale de Sidim,

[[v1-14-9]]

^<<v1-14-9,9>>^ contra Quedorlaomer, rei de Elão, contra Tidal, rei de Goim, contra Anrafel, rei de Sinar, contra Arioque, rei de Elasar: quatro reis contra cinco.

[[v1-14-10]]

^<<v1-14-10,10>>^ Ora, o vale de Sidim estava cheio de poços de betume; os reis de Sodoma e de Gomorra fugiram; alguns caíram neles, e os restantes fugiram para um monte.

[[v1-14-11]]

^<<v1-14-11,11>>^ Tomaram, pois, todos os bens de Sodoma e de Gomorra e todo o seu mantimento e se foram.

[[v1-14-12]]

^<<v1-14-12,12>>^ Apossaram-se também de Ló, filho do irmão de Abrão, que morava em Sodoma, e dos seus bens e partiram.

[[v1-14-13]]

^<<v1-14-13,13>>^ Porém veio um, que escapara, e o contou a Abrão, o hebreu; este habitava junto dos carvalhais de Manre, o amorreu, irmão de Escol e de Aner, os quais eram aliados de Abrão.

[[v1-14-14]]

^<<v1-14-14,14>>^ Ouvindo Abrão que seu sobrinho estava preso, fez sair trezentos e dezoito homens dos mais capazes, nascidos em sua casa, e os perseguiu até Dã.

[[v1-14-15]]

^<<v1-14-15,15>>^ E, repartidos contra eles de noite, ele e os seus homens, feriu-os e os perseguiu até Hobá, que fica à esquerda de Damasco.

[[v1-14-16]]

^<<v1-14-16,16>>^ Trouxe de novo todos os bens, e também a Ló, seu sobrinho, os bens dele, e ainda as mulheres, e o povo.

[[v1-14-17]]

^<<v1-14-17,17>>^ Após voltar Abrão de ferir a Quedorlaomer e aos reis que estavam com ele, saiu-lhe ao encontro o rei de Sodoma no vale de Savé, que é o vale do Rei.

[[v1-14-18]]

^<<v1-14-18,18>>^ Melquisedeque, rei de Salém, trouxe pão e vinho; era sacerdote do Deus Altíssimo;

[[v1-14-19]]

^<<v1-14-19,19>>^ abençoou ele a Abrão e disse: Bendito seja Abrão pelo Deus Altíssimo, que possui os céus e a terra;

[[v1-14-20]]

^<<v1-14-20,20>>^ e bendito seja o Deus Altíssimo, que entregou os teus adversários nas tuas mãos. E de tudo lhe deu Abrão o dízimo.

[[v1-14-21]]

^<<v1-14-21,21>>^ Então, disse o rei de Sodoma a Abrão: Dá-me as pessoas, e os bens ficarão contigo.

[[v1-14-22]]

^<<v1-14-22,22>>^ Mas Abrão lhe respondeu: Levanto a mão ao SENHOR, o Deus Altíssimo, o que possui os céus e a terra,

[[v1-14-23]]

^<<v1-14-23,23>>^ e juro que nada tomarei de tudo o que te pertence, nem um fio, nem uma correia de sandália, para que não digas: Eu enriqueci a Abrão;

[[v1-14-24]]

^<<v1-14-24,24>>^ nada quero para mim, senão o que os rapazes comeram e a parte que toca aos homens Aner, Escol e Manre, que foram comigo; estes que tomem o seu quinhão.

'''

xref:001-genesis/001-genesis-013.adoc#v1-13-0[&#60; Capítulo Anterior] | <<v1-14-0,Topo>> | xref:001-genesis/001-genesis-015.adoc#v1-15-0[Próximo Capítulo &#62;]