include::./index.adoc[]

[[v1-17-0]]
=== Gênesis, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-17-1]]

^<<v1-17-1,1>>^ Quando atingiu Abrão a idade de noventa e nove anos, apareceu-lhe o SENHOR e disse-lhe: Eu sou o Deus Todo-Poderoso; anda na minha presença e sê perfeito.

[[v1-17-2]]

^<<v1-17-2,2>>^ Farei uma aliança entre mim e ti e te multiplicarei extraordinariamente.

[[v1-17-3]]

^<<v1-17-3,3>>^ Prostrou-se Abrão, rosto em terra, e Deus lhe falou:

[[v1-17-4]]

^<<v1-17-4,4>>^ Quanto a mim, será contigo a minha aliança; serás pai de numerosas nações.

[[v1-17-5]]

^<<v1-17-5,5>>^ Abrão já não será o teu nome, e sim Abraão; porque por pai de numerosas nações te constituí.

[[v1-17-6]]

^<<v1-17-6,6>>^ Far-te-ei fecundo extraordinariamente, de ti farei nações, e reis procederão de ti.

[[v1-17-7]]

^<<v1-17-7,7>>^ Estabelecerei a minha aliança entre mim e ti e a tua descendência no decurso das suas gerações, aliança perpétua, para ser o teu Deus e da tua descendência.

[[v1-17-8]]

^<<v1-17-8,8>>^ Dar-te-ei e à tua descendência a terra das tuas peregrinações, toda a terra de Canaã, em possessão perpétua, e serei o seu Deus.

[[v1-17-9]]

^<<v1-17-9,9>>^ Disse mais Deus a Abraão: Guardarás a minha aliança, tu e a tua descendência no decurso das suas gerações.

[[v1-17-10]]

^<<v1-17-10,10>>^ Esta é a minha aliança, que guardareis entre mim e vós e a tua descendência: todo macho entre vós será circuncidado.

[[v1-17-11]]

^<<v1-17-11,11>>^ Circuncidareis a carne do vosso prepúcio; será isso por sinal de aliança entre mim e vós.

[[v1-17-12]]

^<<v1-17-12,12>>^ O que tem oito dias será circuncidado entre vós, todo macho nas vossas gerações, tanto o escravo nascido em casa como o comprado a qualquer estrangeiro, que não for da tua estirpe.

[[v1-17-13]]

^<<v1-17-13,13>>^ Com efeito, será circuncidado o nascido em tua casa e o comprado por teu dinheiro; a minha aliança estará na vossa carne e será aliança perpétua.

[[v1-17-14]]

^<<v1-17-14,14>>^ O incircunciso, que não for circuncidado na carne do prepúcio, essa vida será eliminada do seu povo; quebrou a minha aliança.

[[v1-17-15]]

^<<v1-17-15,15>>^ Disse também Deus a Abraão: A Sarai, tua mulher, já não lhe chamarás Sarai, porém Sara.

[[v1-17-16]]

^<<v1-17-16,16>>^ Abençoá-la-ei e dela te darei um filho; sim, eu a abençoarei, e ela se tornará nações; reis de povos procederão dela.

[[v1-17-17]]

^<<v1-17-17,17>>^ Então, se prostrou Abraão, rosto em terra, e se riu, e disse consigo: A um homem de cem anos há de nascer um filho? Dará à luz Sara com seus noventa anos?

[[v1-17-18]]

^<<v1-17-18,18>>^ Disse Abraão a Deus: Tomara que viva Ismael diante de ti.

[[v1-17-19]]

^<<v1-17-19,19>>^ Deus lhe respondeu: De fato, Sara, tua mulher, te dará um filho, e lhe chamarás Isaque; estabelecerei com ele a minha aliança, aliança perpétua para a sua descendência.

[[v1-17-20]]

^<<v1-17-20,20>>^ Quanto a Ismael, eu te ouvi: abençoá-lo-ei, fá-lo-ei fecundo e o multiplicarei extraordinariamente; gerará doze príncipes, e dele farei uma grande nação.

[[v1-17-21]]

^<<v1-17-21,21>>^ A minha aliança, porém, estabelecê-la-ei com Isaque, o qual Sara te dará à luz, neste mesmo tempo, daqui a um ano.

[[v1-17-22]]

^<<v1-17-22,22>>^ E, finda esta fala com Abraão, Deus se retirou dele, elevando-se.

[[v1-17-23]]

^<<v1-17-23,23>>^ Tomou, pois, Abraão a seu filho Ismael, e a todos os escravos nascidos em sua casa, e a todos os comprados por seu dinheiro, todo macho dentre os de sua casa, e lhes circuncidou a carne do prepúcio de cada um, naquele mesmo dia, como Deus lhe ordenara.

[[v1-17-24]]

^<<v1-17-24,24>>^ Tinha Abraão noventa e nove anos de idade, quando foi circuncidado na carne do seu prepúcio.

[[v1-17-25]]

^<<v1-17-25,25>>^ Ismael, seu filho, era de treze anos, quando foi circuncidado na carne do seu prepúcio.

[[v1-17-26]]

^<<v1-17-26,26>>^ Abraão e seu filho, Ismael, foram circuncidados no mesmo dia.

[[v1-17-27]]

^<<v1-17-27,27>>^ E também foram circuncidados todos os homens de sua casa, tanto os escravos nascidos nela como os comprados por dinheiro ao estrangeiro.

'''

xref:001-genesis/001-genesis-016.adoc#v1-16-0[&#60; Capítulo Anterior] | <<v1-17-0,Topo>> | xref:001-genesis/001-genesis-018.adoc#v1-18-0[Próximo Capítulo &#62;]