include::./index.adoc[]

[[v1-33-0]]
=== Gênesis, 33
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-33-1]]

^<<v1-33-1,1>>^ Levantando Jacó os olhos, viu que Esaú se aproximava, e com ele quatrocentos homens. Então, passou os filhos a Lia, a Raquel e às duas servas.

[[v1-33-2]]

^<<v1-33-2,2>>^ Pôs as servas e seus filhos à frente, Lia e seus filhos atrás deles e Raquel e José por últimos.

[[v1-33-3]]

^<<v1-33-3,3>>^ E ele mesmo, adiantando-se, prostrou-se à terra sete vezes, até aproximar-se de seu irmão.

[[v1-33-4]]

^<<v1-33-4,4>>^ Então, Esaú correu-lhe ao encontro e o abraçou; arrojou-se-lhe ao pescoço e o beijou; e choraram.

[[v1-33-5]]

^<<v1-33-5,5>>^ Daí, levantando os olhos, viu as mulheres e os meninos e disse: Quem são estes contigo? Respondeu-lhe Jacó: Os filhos com que Deus agraciou a teu servo.

[[v1-33-6]]

^<<v1-33-6,6>>^ Então, se aproximaram as servas, elas e seus filhos, e se prostraram.

[[v1-33-7]]

^<<v1-33-7,7>>^ Chegaram também Lia e seus filhos e se prostraram; por último chegaram José e Raquel e se prostraram.

[[v1-33-8]]

^<<v1-33-8,8>>^ Perguntou Esaú: Qual é o teu propósito com todos esses bandos que encontrei? Respondeu Jacó: Para lograr mercê na presença de meu senhor.

[[v1-33-9]]

^<<v1-33-9,9>>^ Então, disse Esaú: Eu tenho muitos bens, meu irmão; guarda o que tens.

[[v1-33-10]]

^<<v1-33-10,10>>^ Mas Jacó insistiu: Não recuses; se logrei mercê diante de ti, peço-te que aceites o meu presente, porquanto vi o teu rosto como se tivesse contemplado o semblante de Deus; e te agradaste de mim.

[[v1-33-11]]

^<<v1-33-11,11>>^ Peço-te, pois, recebe o meu presente, que eu te trouxe; porque Deus tem sido generoso para comigo, e tenho fartura. E instou com ele, até que o aceitou.

[[v1-33-12]]

^<<v1-33-12,12>>^ Disse Esaú: Partamos e caminhemos; eu seguirei junto de ti.

[[v1-33-13]]

^<<v1-33-13,13>>^ Porém Jacó lhe disse: Meu senhor sabe que estes meninos são tenros, e tenho comigo ovelhas e vacas de leite; se forçadas a caminhar demais um só dia, morrerão todos os rebanhos.

[[v1-33-14]]

^<<v1-33-14,14>>^ Passe meu senhor adiante de seu servo; eu seguirei guiando-as pouco a pouco, no passo do gado que me vai à frente e no passo dos meninos, até chegar a meu senhor, em Seir.

[[v1-33-15]]

^<<v1-33-15,15>>^ Respondeu Esaú: Então, permite que eu deixe contigo da gente que está comigo. Disse Jacó: Para quê? Basta que eu alcance mercê aos olhos de meu senhor.

[[v1-33-16]]

^<<v1-33-16,16>>^ Assim, voltou Esaú aquele dia a Seir, pelo caminho por onde viera.

[[v1-33-17]]

^<<v1-33-17,17>>^ E Jacó partiu para Sucote, e edificou para si uma casa, e fez palhoças para o seu gado; por isso, o lugar se chamou Sucote.

[[v1-33-18]]

^<<v1-33-18,18>>^ Voltando de Padã-Arã, chegou Jacó são e salvo à cidade de Siquém, que está na terra de Canaã; e armou a sua tenda junto da cidade.

[[v1-33-19]]

^<<v1-33-19,19>>^ A parte do campo, onde armara a sua tenda, ele a comprou dos filhos de Hamor, pai de Siquém, por cem peças de dinheiro.

[[v1-33-20]]

^<<v1-33-20,20>>^ E levantou ali um altar e lhe chamou Deus, o Deus de Israel.

'''

xref:001-genesis/001-genesis-032.adoc#v1-32-0[&#60; Capítulo Anterior] | <<v1-33-0,Topo>> | xref:001-genesis/001-genesis-034.adoc#v1-34-0[Próximo Capítulo &#62;]