include::./index.adoc[]

[[v1-20-0]]
=== Gênesis, 20
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-20-1]]

^<<v1-20-1,1>>^ Partindo Abraão dali para a terra do Neguebe, habitou entre Cades e Sur e morou em Gerar.

[[v1-20-2]]

^<<v1-20-2,2>>^ Disse Abraão de Sara, sua mulher: Ela é minha irmã; assim, pois, Abimeleque, rei de Gerar, mandou buscá-la.

[[v1-20-3]]

^<<v1-20-3,3>>^ Deus, porém, veio a Abimeleque em sonhos de noite e lhe disse: Vais ser punido de morte por causa da mulher que tomaste, porque ela tem marido.

[[v1-20-4]]

^<<v1-20-4,4>>^ Ora, Abimeleque ainda não a havia possuído; por isso, disse: Senhor, matarás até uma nação inocente?

[[v1-20-5]]

^<<v1-20-5,5>>^ Não foi ele mesmo que me disse: É minha irmã? E ela também me disse: Ele é meu irmão. Com sinceridade de coração e na minha inocência, foi que eu fiz isso.

[[v1-20-6]]

^<<v1-20-6,6>>^ Respondeu-lhe Deus em sonho: Bem sei que com sinceridade de coração fizeste isso; daí o ter impedido eu de pecares contra mim e não te permiti que a tocasses.

[[v1-20-7]]

^<<v1-20-7,7>>^ Agora, pois, restitui a mulher a seu marido, pois ele é profeta e intercederá por ti, e viverás; se, porém, não lha restituíres, sabe que certamente morrerás, tu e tudo o que é teu.

[[v1-20-8]]

^<<v1-20-8,8>>^ Levantou-se Abimeleque de madrugada, e chamou todos os seus servos, e lhes contou todas essas coisas; e os homens ficaram muito atemorizados.

[[v1-20-9]]

^<<v1-20-9,9>>^ Então, chamou Abimeleque a Abraão e lhe disse: Que é isso que nos fizeste? Em que pequei eu contra ti, para trazeres tamanho pecado sobre mim e sobre o meu reino? Tu me fizeste o que não se deve fazer.

[[v1-20-10]]

^<<v1-20-10,10>>^ Disse mais Abimeleque a Abraão: Que estavas pensando para fazeres tal coisa?

[[v1-20-11]]

^<<v1-20-11,11>>^ Respondeu Abraão: Eu dizia comigo mesmo: Certamente não há temor de Deus neste lugar, e eles me matarão por causa de minha mulher.

[[v1-20-12]]

^<<v1-20-12,12>>^ Por outro lado, ela, de fato, é também minha irmã, filha de meu pai e não de minha mãe; e veio a ser minha mulher.

[[v1-20-13]]

^<<v1-20-13,13>>^ Quando Deus me fez andar errante da casa de meu pai, eu disse a ela: Este favor me farás: em todo lugar em que entrarmos, dirás a meu respeito: Ele é meu irmão.

[[v1-20-14]]

^<<v1-20-14,14>>^ Então, Abimeleque tomou ovelhas e bois, e servos e servas e os deu a Abraão; e lhe restituiu a Sara, sua mulher.

[[v1-20-15]]

^<<v1-20-15,15>>^ Disse Abimeleque: A minha terra está diante de ti; habita onde melhor te parecer.

[[v1-20-16]]

^<<v1-20-16,16>>^ E a Sara disse: Dei mil siclos de prata a teu irmão; será isto compensação por tudo quanto se deu contigo; e perante todos estás justificada.

[[v1-20-17]]

^<<v1-20-17,17>>^ E, orando Abraão, sarou Deus Abimeleque, sua mulher e suas servas, de sorte que elas pudessem ter filhos;

[[v1-20-18]]

^<<v1-20-18,18>>^ porque o SENHOR havia tornado estéreis todas as mulheres da casa de Abimeleque, por causa de Sara, mulher de Abraão.

'''

xref:001-genesis/001-genesis-019.adoc#v1-19-0[&#60; Capítulo Anterior] | <<v1-20-0,Topo>> | xref:001-genesis/001-genesis-021.adoc#v1-21-0[Próximo Capítulo &#62;]