include::./index.adoc[]

[[v1-6-0]]
=== Gênesis, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-6-1]]

^<<v1-6-1,1>>^ Como se foram multiplicando os homens na terra, e lhes nasceram filhas,

[[v1-6-2]]

^<<v1-6-2,2>>^ vendo os filhos de Deus que as filhas dos homens eram formosas, tomaram para si mulheres, as que, entre todas, mais lhes agradaram.

[[v1-6-3]]

^<<v1-6-3,3>>^ Então, disse o SENHOR: O meu Espírito não agirá para sempre no homem, pois este é carnal; e os seus dias serão cento e vinte anos.

[[v1-6-4]]

^<<v1-6-4,4>>^ Ora, naquele tempo havia gigantes na terra; e também depois, quando os filhos de Deus possuíram as filhas dos homens, as quais lhes deram filhos; estes foram valentes, varões de renome, na antiguidade.

[[v1-6-5]]

^<<v1-6-5,5>>^ Viu o SENHOR que a maldade do homem se havia multiplicado na terra e que era continuamente mau todo desígnio do seu coração;

[[v1-6-6]]

^<<v1-6-6,6>>^ então, se arrependeu o SENHOR de ter feito o homem na terra, e isso lhe pesou no coração.

[[v1-6-7]]

^<<v1-6-7,7>>^ Disse o SENHOR: Farei desaparecer da face da terra o homem que criei, o homem e o animal, os répteis e as aves dos céus; porque me arrependo de os haver feito.

[[v1-6-8]]

^<<v1-6-8,8>>^ Porém Noé achou graça diante do SENHOR.

[[v1-6-9]]

^<<v1-6-9,9>>^ Eis a história de Noé. Noé era homem justo e íntegro entre os seus contemporâneos; Noé andava com Deus.

[[v1-6-10]]

^<<v1-6-10,10>>^ Gerou três filhos: Sem, Cam e Jafé.

[[v1-6-11]]

^<<v1-6-11,11>>^ A terra estava corrompida à vista de Deus e cheia de violência.

[[v1-6-12]]

^<<v1-6-12,12>>^ Viu Deus a terra, e eis que estava corrompida; porque todo ser vivente havia corrompido o seu caminho na terra.

[[v1-6-13]]

^<<v1-6-13,13>>^ Então, disse Deus a Noé: Resolvi dar cabo de toda carne, porque a terra está cheia da violência dos homens; eis que os farei perecer juntamente com a terra.

[[v1-6-14]]

^<<v1-6-14,14>>^ Faze uma arca de tábuas de cipreste; nela farás compartimentos e a calafetarás com betume por dentro e por fora.

[[v1-6-15]]

^<<v1-6-15,15>>^ Deste modo a farás: de trezentos côvados será o comprimento; de cinquenta, a largura; e a altura, de trinta.

[[v1-6-16]]

^<<v1-6-16,16>>^ Farás ao seu redor uma abertura de um côvado de altura; a porta da arca colocarás lateralmente; farás pavimentos na arca: um em baixo, um segundo e um terceiro.

[[v1-6-17]]

^<<v1-6-17,17>>^ Porque estou para derramar águas em dilúvio sobre a terra para consumir toda carne em que há fôlego de vida debaixo dos céus; tudo o que há na terra perecerá.

[[v1-6-18]]

^<<v1-6-18,18>>^ Contigo, porém, estabelecerei a minha aliança; entrarás na arca, tu e teus filhos, e tua mulher, e as mulheres de teus filhos.

[[v1-6-19]]

^<<v1-6-19,19>>^ De tudo o que vive, de toda carne, dois de cada espécie, macho e fêmea, farás entrar na arca, para os conservares vivos contigo.

[[v1-6-20]]

^<<v1-6-20,20>>^ Das aves segundo as suas espécies, do gado segundo as suas espécies, de todo réptil da terra segundo as suas espécies, dois de cada espécie virão a ti, para os conservares em vida.

[[v1-6-21]]

^<<v1-6-21,21>>^ Leva contigo de tudo o que se come, ajunta-o contigo; ser-te-á para alimento, a ti e a eles.

[[v1-6-22]]

^<<v1-6-22,22>>^ Assim fez Noé, consoante a tudo o que Deus lhe ordenara.

'''

xref:001-genesis/001-genesis-005.adoc#v1-5-0[&#60; Capítulo Anterior] | <<v1-6-0,Topo>> | xref:001-genesis/001-genesis-007.adoc#v1-7-0[Próximo Capítulo &#62;]