include::./index.adoc[]

[[v1-32-0]]
=== Gênesis, 32
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-32-1]]

^<<v1-32-1,1>>^ Também Jacó seguiu o seu caminho, e anjos de Deus lhe saíram a encontrá-lo.

[[v1-32-2]]

^<<v1-32-2,2>>^ Quando os viu, disse: Este é o acampamento de Deus. E chamou àquele lugar Maanaim.

[[v1-32-3]]

^<<v1-32-3,3>>^ Então, Jacó enviou mensageiros adiante de si a Esaú, seu irmão, à terra de Seir, território de Edom,

[[v1-32-4]]

^<<v1-32-4,4>>^ e lhes ordenou: Assim falareis a meu senhor Esaú: Teu servo Jacó manda dizer isto: Como peregrino morei com Labão, em cuja companhia fiquei até agora.

[[v1-32-5]]

^<<v1-32-5,5>>^ Tenho bois, jumentos, rebanhos, servos e servas; mando comunicá-lo a meu senhor, para lograr mercê à sua presença.

[[v1-32-6]]

^<<v1-32-6,6>>^ Voltaram os mensageiros a Jacó, dizendo: Fomos a teu irmão Esaú; também ele vem de caminho para se encontrar contigo, e quatrocentos homens com ele.

[[v1-32-7]]

^<<v1-32-7,7>>^ Então, Jacó teve medo e se perturbou; dividiu em dois bandos o povo que com ele estava, e os rebanhos, e os bois, e os camelos.

[[v1-32-8]]

^<<v1-32-8,8>>^ Pois disse: Se vier Esaú a um bando e o ferir, o outro bando escapará.

[[v1-32-9]]

^<<v1-32-9,9>>^ E orou Jacó: Deus de meu pai Abraão e Deus de meu pai Isaque, ó SENHOR, que me disseste: Torna à tua terra e à tua parentela, e te farei bem;

[[v1-32-10]]

^<<v1-32-10,10>>^ sou indigno de todas as misericórdias e de toda a fidelidade que tens usado para com teu servo; pois com apenas o meu cajado atravessei este Jordão; já agora sou dois bandos.

[[v1-32-11]]

^<<v1-32-11,11>>^ Livra-me das mãos de meu irmão Esaú, porque eu o temo, para que não venha ele matar-me e as mães com os filhos.

[[v1-32-12]]

^<<v1-32-12,12>>^ E disseste: Certamente eu te farei bem e dar-te-ei a descendência como a areia do mar, que, pela multidão, não se pode contar.

[[v1-32-13]]

^<<v1-32-13,13>>^ E, tendo passado ali aquela noite, separou do que tinha um presente para seu irmão Esaú:

[[v1-32-14]]

^<<v1-32-14,14>>^ duzentas cabras e vinte bodes; duzentas ovelhas e vinte carneiros;

[[v1-32-15]]

^<<v1-32-15,15>>^ trinta camelas de leite com suas crias, quarenta vacas e dez touros; vinte jumentas e dez jumentinhos.

[[v1-32-16]]

^<<v1-32-16,16>>^ Entregou-os às mãos dos seus servos, cada rebanho à parte, e disse aos servos: Passai adiante de mim e deixai espaço entre rebanho e rebanho.

[[v1-32-17]]

^<<v1-32-17,17>>^ Ordenou ao primeiro, dizendo: Quando Esaú, meu irmão, te encontrar e te perguntar: De quem és, para onde vais, de quem são estes diante de ti?

[[v1-32-18]]

^<<v1-32-18,18>>^ Responderás: São de teu servo Jacó; é presente que ele envia a meu senhor Esaú; e eis que ele mesmo vem vindo atrás de nós.

[[v1-32-19]]

^<<v1-32-19,19>>^ Ordenou também ao segundo, ao terceiro e a todos os que vinham conduzindo os rebanhos: Falareis desta maneira a Esaú, quando vos encontrardes com ele.

[[v1-32-20]]

^<<v1-32-20,20>>^ Direis assim: Eis que o teu servo Jacó vem vindo atrás de nós. Porque dizia consigo mesmo: Eu o aplacarei com o presente que me antecede, depois o verei; porventura me aceitará a presença.

[[v1-32-21]]

^<<v1-32-21,21>>^ Assim, passou o presente para diante dele; ele, porém, ficou aquela noite no acampamento.

[[v1-32-22]]

^<<v1-32-22,22>>^ Levantou-se naquela mesma noite, tomou suas duas mulheres, suas duas servas e seus onze filhos e transpôs o vau de Jaboque.

[[v1-32-23]]

^<<v1-32-23,23>>^ Tomou-os e fê-los passar o ribeiro; fez passar tudo o que lhe pertencia,

[[v1-32-24]]

^<<v1-32-24,24>>^ ficando ele só; e lutava com ele um homem, até ao romper do dia.

[[v1-32-25]]

^<<v1-32-25,25>>^ Vendo este que não podia com ele, tocou-lhe na articulação da coxa; deslocou-se a junta da coxa de Jacó, na luta com o homem.

[[v1-32-26]]

^<<v1-32-26,26>>^ Disse este: Deixa-me ir, pois já rompeu o dia. Respondeu Jacó: Não te deixarei ir se me não abençoares.

[[v1-32-27]]

^<<v1-32-27,27>>^ Perguntou-lhe, pois: Como te chamas? Ele respondeu: Jacó.

[[v1-32-28]]

^<<v1-32-28,28>>^ Então, disse: Já não te chamarás Jacó, e sim Israel, pois como príncipe lutaste com Deus e com os homens e prevaleceste.

[[v1-32-29]]

^<<v1-32-29,29>>^ Tornou Jacó: Dize, rogo-te, como te chamas? Respondeu ele: Por que perguntas pelo meu nome? E o abençoou ali.

[[v1-32-30]]

^<<v1-32-30,30>>^ Àquele lugar chamou Jacó Peniel, pois disse: Vi a Deus face a face, e a minha vida foi salva.

[[v1-32-31]]

^<<v1-32-31,31>>^ Nasceu-lhe o sol, quando ele atravessava Peniel; e manquejava de uma coxa.

[[v1-32-32]]

^<<v1-32-32,32>>^ Por isso, os filhos de Israel não comem, até hoje, o nervo do quadril, na articulação da coxa, porque o homem tocou a articulação da coxa de Jacó no nervo do quadril.

'''

xref:001-genesis/001-genesis-031.adoc#v1-31-0[&#60; Capítulo Anterior] | <<v1-32-0,Topo>> | xref:001-genesis/001-genesis-033.adoc#v1-33-0[Próximo Capítulo &#62;]