include::./index.adoc[]

[[v1-11-0]]
=== Gênesis, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-11-1]]

^<<v1-11-1,1>>^ Ora, em toda a terra havia apenas uma linguagem e uma só maneira de falar.

[[v1-11-2]]

^<<v1-11-2,2>>^ Sucedeu que, partindo eles do Oriente, deram com uma planície na terra de Sinar; e habitaram ali.

[[v1-11-3]]

^<<v1-11-3,3>>^ E disseram uns aos outros: Vinde, façamos tijolos e queimemo-los bem. Os tijolos serviram-lhes de pedra, e o betume, de argamassa.

[[v1-11-4]]

^<<v1-11-4,4>>^ Disseram: Vinde, edifiquemos para nós uma cidade e uma torre cujo tope chegue até aos céus e tornemos célebre o nosso nome, para que não sejamos espalhados por toda a terra.

[[v1-11-5]]

^<<v1-11-5,5>>^ Então, desceu o SENHOR para ver a cidade e a torre, que os filhos dos homens edificavam;

[[v1-11-6]]

^<<v1-11-6,6>>^ e o SENHOR disse: Eis que o povo é um, e todos têm a mesma linguagem. Isto é apenas o começo; agora não haverá restrição para tudo que intentam fazer.

[[v1-11-7]]

^<<v1-11-7,7>>^ Vinde, desçamos e confundamos ali a sua linguagem, para que um não entenda a linguagem de outro.

[[v1-11-8]]

^<<v1-11-8,8>>^ Destarte, o SENHOR os dispersou dali pela superfície da terra; e cessaram de edificar a cidade.

[[v1-11-9]]

^<<v1-11-9,9>>^ Chamou-se-lhe, por isso, o nome de Babel, porque ali confundiu o SENHOR a linguagem de toda a terra e dali o SENHOR os dispersou por toda a superfície dela.

[[v1-11-10]]

^<<v1-11-10,10>>^ São estas as gerações de Sem. Ora, ele era da idade de cem anos quando gerou a Arfaxade, dois anos depois do dilúvio;

[[v1-11-11]]

^<<v1-11-11,11>>^ e, depois que gerou a Arfaxade, viveu Sem quinhentos anos; e gerou filhos e filhas.

[[v1-11-12]]

^<<v1-11-12,12>>^ Viveu Arfaxade trinta e cinco anos e gerou a Salá;

[[v1-11-13]]

^<<v1-11-13,13>>^ e, depois que gerou a Salá, viveu Arfaxade quatrocentos e três anos; e gerou filhos e filhas.

[[v1-11-14]]

^<<v1-11-14,14>>^ Viveu Salá trinta anos e gerou a Héber;

[[v1-11-15]]

^<<v1-11-15,15>>^ e, depois que gerou a Héber, viveu Salá quatrocentos e três anos; e gerou filhos e filhas.

[[v1-11-16]]

^<<v1-11-16,16>>^ Viveu Héber trinta e quatro anos e gerou a Pelegue;

[[v1-11-17]]

^<<v1-11-17,17>>^ e, depois que gerou a Pelegue, viveu Héber quatrocentos e trinta anos; e gerou filhos e filhas.

[[v1-11-18]]

^<<v1-11-18,18>>^ Viveu Pelegue trinta anos e gerou a Reú;

[[v1-11-19]]

^<<v1-11-19,19>>^ e, depois que gerou a Reú, viveu Pelegue duzentos e nove anos; e gerou filhos e filhas.

[[v1-11-20]]

^<<v1-11-20,20>>^ Viveu Reú trinta e dois anos e gerou a Serugue;

[[v1-11-21]]

^<<v1-11-21,21>>^ e, depois que gerou a Serugue, viveu Reú duzentos e sete anos; e gerou filhos e filhas.

[[v1-11-22]]

^<<v1-11-22,22>>^ Viveu Serugue trinta anos e gerou a Naor;

[[v1-11-23]]

^<<v1-11-23,23>>^ e, depois que gerou a Naor, viveu Serugue duzentos anos; e gerou filhos e filhas.

[[v1-11-24]]

^<<v1-11-24,24>>^ Viveu Naor vinte e nove anos e gerou a Tera;

[[v1-11-25]]

^<<v1-11-25,25>>^ e, depois que gerou a Tera, viveu Naor cento e dezenove anos; e gerou filhos e filhas.

[[v1-11-26]]

^<<v1-11-26,26>>^ Viveu Tera setenta anos e gerou a Abrão, a Naor e a Harã.

[[v1-11-27]]

^<<v1-11-27,27>>^ São estas as gerações de Tera. Tera gerou a Abrão, a Naor e a Harã; e Harã gerou a Ló.

[[v1-11-28]]

^<<v1-11-28,28>>^ Morreu Harã na terra de seu nascimento, em Ur dos caldeus, estando Tera, seu pai, ainda vivo.

[[v1-11-29]]

^<<v1-11-29,29>>^ Abrão e Naor tomaram para si mulheres; a de Abrão chamava-se Sarai, a de Naor, Milca, filha de Harã, que foi pai de Milca e de Iscá.

[[v1-11-30]]

^<<v1-11-30,30>>^ Sarai era estéril, não tinha filhos.

[[v1-11-31]]

^<<v1-11-31,31>>^ Tomou Tera a Abrão, seu filho, e a Ló, filho de Harã, filho de seu filho, e a Sarai, sua nora, mulher de seu filho Abrão, e saiu com eles de Ur dos caldeus, para ir à terra de Canaã; foram até Harã, onde ficaram.

[[v1-11-32]]

^<<v1-11-32,32>>^ E, havendo Tera vivido duzentos e cinco anos ao todo, morreu em Harã.

'''

xref:001-genesis/001-genesis-010.adoc#v1-10-0[&#60; Capítulo Anterior] | <<v1-11-0,Topo>> | xref:001-genesis/001-genesis-012.adoc#v1-12-0[Próximo Capítulo &#62;]