include::./index.adoc[]

[[v1-5-0]]
=== Gênesis, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-5-1]]

^<<v1-5-1,1>>^ Este é o livro da genealogia de Adão. No dia em que Deus criou o homem, à semelhança de Deus o fez;

[[v1-5-2]]

^<<v1-5-2,2>>^ homem e mulher os criou, e os abençoou, e lhes chamou pelo nome de Adão, no dia em que foram criados.

[[v1-5-3]]

^<<v1-5-3,3>>^ Viveu Adão cento e trinta anos, e gerou um filho à sua semelhança, conforme a sua imagem, e lhe chamou Sete.

[[v1-5-4]]

^<<v1-5-4,4>>^ Depois que gerou a Sete, viveu Adão oitocentos anos; e teve filhos e filhas.

[[v1-5-5]]

^<<v1-5-5,5>>^ Os dias todos da vida de Adão foram novecentos e trinta anos; e morreu.

[[v1-5-6]]

^<<v1-5-6,6>>^ Sete viveu cento e cinco anos e gerou a Enos.

[[v1-5-7]]

^<<v1-5-7,7>>^ Depois que gerou a Enos, viveu Sete oitocentos e sete anos; e teve filhos e filhas.

[[v1-5-8]]

^<<v1-5-8,8>>^ Todos os dias de Sete foram novecentos e doze anos; e morreu.

[[v1-5-9]]

^<<v1-5-9,9>>^ Enos viveu noventa anos e gerou a Cainã.

[[v1-5-10]]

^<<v1-5-10,10>>^ Depois que gerou a Cainã, viveu Enos oitocentos e quinze anos; e teve filhos e filhas.

[[v1-5-11]]

^<<v1-5-11,11>>^ Todos os dias de Enos foram novecentos e cinco anos; e morreu.

[[v1-5-12]]

^<<v1-5-12,12>>^ Cainã viveu setenta anos e gerou a Maalalel.

[[v1-5-13]]

^<<v1-5-13,13>>^ Depois que gerou a Maalalel, viveu Cainã oitocentos e quarenta anos; e teve filhos e filhas.

[[v1-5-14]]

^<<v1-5-14,14>>^ Todos os dias de Cainã foram novecentos e dez anos; e morreu.

[[v1-5-15]]

^<<v1-5-15,15>>^ Maalalel viveu sessenta e cinco anos e gerou a Jarede.

[[v1-5-16]]

^<<v1-5-16,16>>^ Depois que gerou a Jarede, viveu Maalalel oitocentos e trinta anos; e teve filhos e filhas.

[[v1-5-17]]

^<<v1-5-17,17>>^ Todos os dias de Maalalel foram oitocentos e noventa e cinco anos; e morreu.

[[v1-5-18]]

^<<v1-5-18,18>>^ Jarede viveu cento e sessenta e dois anos e gerou a Enoque.

[[v1-5-19]]

^<<v1-5-19,19>>^ Depois que gerou a Enoque, viveu Jarede oitocentos anos; e teve filhos e filhas.

[[v1-5-20]]

^<<v1-5-20,20>>^ Todos os dias de Jarede foram novecentos e sessenta e dois anos; e morreu.

[[v1-5-21]]

^<<v1-5-21,21>>^ Enoque viveu sessenta e cinco anos e gerou a Metusalém.

[[v1-5-22]]

^<<v1-5-22,22>>^ Andou Enoque com Deus; e, depois que gerou a Metusalém, viveu trezentos anos; e teve filhos e filhas.

[[v1-5-23]]

^<<v1-5-23,23>>^ Todos os dias de Enoque foram trezentos e sessenta e cinco anos.

[[v1-5-24]]

^<<v1-5-24,24>>^ Andou Enoque com Deus e já não era, porque Deus o tomou para si.

[[v1-5-25]]

^<<v1-5-25,25>>^ Metusalém viveu cento e oitenta e sete anos e gerou a Lameque.

[[v1-5-26]]

^<<v1-5-26,26>>^ Depois que gerou a Lameque, viveu Metusalém setecentos e oitenta e dois anos; e teve filhos e filhas.

[[v1-5-27]]

^<<v1-5-27,27>>^ Todos os dias de Metusalém foram novecentos e sessenta e nove anos; e morreu.

[[v1-5-28]]

^<<v1-5-28,28>>^ Lameque viveu cento e oitenta e dois anos e gerou um filho;

[[v1-5-29]]

^<<v1-5-29,29>>^ pôs-lhe o nome de Noé, dizendo: Este nos consolará dos nossos trabalhos e das fadigas de nossas mãos, nesta terra que o SENHOR amaldiçoou.

[[v1-5-30]]

^<<v1-5-30,30>>^ Depois que gerou a Noé, viveu Lameque quinhentos e noventa e cinco anos; e teve filhos e filhas.

[[v1-5-31]]

^<<v1-5-31,31>>^ Todos os dias de Lameque foram setecentos e setenta e sete anos; e morreu.

[[v1-5-32]]

^<<v1-5-32,32>>^ Era Noé da idade de quinhentos anos e gerou a Sem, Cam e Jafé.

'''

xref:001-genesis/001-genesis-004.adoc#v1-4-0[&#60; Capítulo Anterior] | <<v1-5-0,Topo>> | xref:001-genesis/001-genesis-006.adoc#v1-6-0[Próximo Capítulo &#62;]