include::./index.adoc[]

[[v1-46-0]]
=== Gênesis, 46
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-46-1]]

^<<v1-46-1,1>>^ Partiu, pois, Israel com tudo o que possuía, e veio a Berseba, e ofereceu sacrifícios ao Deus de Isaque, seu pai.

[[v1-46-2]]

^<<v1-46-2,2>>^ Falou Deus a Israel em visões, de noite, e disse: Jacó! Jacó! Ele respondeu: Eis-me aqui!

[[v1-46-3]]

^<<v1-46-3,3>>^ Então, disse: Eu sou Deus, o Deus de teu pai; não temas descer para o Egito, porque lá eu farei de ti uma grande nação.

[[v1-46-4]]

^<<v1-46-4,4>>^ Eu descerei contigo para o Egito e te farei tornar a subir, certamente. A mão de José fechará os teus olhos.

[[v1-46-5]]

^<<v1-46-5,5>>^ Então, se levantou Jacó de Berseba; e os filhos de Israel levaram Jacó, seu pai, e seus filhinhos, e as suas mulheres nos carros que Faraó enviara para o levar.

[[v1-46-6]]

^<<v1-46-6,6>>^ Tomaram o seu gado e os bens que haviam adquirido na terra de Canaã e vieram para o Egito, Jacó e toda a sua descendência.

[[v1-46-7]]

^<<v1-46-7,7>>^ Seus filhos e os filhos de seus filhos, suas filhas e as filhas de seus filhos e toda a sua descendência, levou-os consigo para o Egito.

[[v1-46-8]]

^<<v1-46-8,8>>^ São estes os nomes dos filhos de Israel, Jacó, e seus filhos, que vieram para o Egito: Rúben, o primogênito de Jacó.

[[v1-46-9]]

^<<v1-46-9,9>>^ Os filhos de Rúben: Enoque, Palu, Hezrom e Carmi.

[[v1-46-10]]

^<<v1-46-10,10>>^ Os filhos de Simeão: Jemuel, Jamim, Oade, Jaquim, Zoar e Saul, filho de uma mulher cananeia.

[[v1-46-11]]

^<<v1-46-11,11>>^ Os filhos de Levi: Gérson, Coate e Merari.

[[v1-46-12]]

^<<v1-46-12,12>>^ Os filhos de Judá: Er, Onã, Selá, Perez e Zera; Er e Onã, porém, morreram na terra de Canaã. Os filhos de Perez foram: Hezrom e Hamul.

[[v1-46-13]]

^<<v1-46-13,13>>^ Os filhos de Issacar: Tola, Puva, Jó e Sinrom.

[[v1-46-14]]

^<<v1-46-14,14>>^ Os filhos de Zebulom: Serede, Elom e Jaleel.

[[v1-46-15]]

^<<v1-46-15,15>>^ São estes os filhos de Lia, que ela deu à luz a Jacó em Padã-Arã, além de Diná, sua filha; todas as pessoas, de seus filhos e de suas filhas, trinta e três.

[[v1-46-16]]

^<<v1-46-16,16>>^ Os filhos de Gade: Zifiom, Hagi, Suni, Esbom, Eri, Arodi e Areli.

[[v1-46-17]]

^<<v1-46-17,17>>^ Os filhos de Aser: Imna, Isvá, Isvi, Berias e Sera, irmã deles; e os filhos de Berias: Héber e Malquiel.

[[v1-46-18]]

^<<v1-46-18,18>>^ São estes os filhos de Zilpa, a qual Labão deu a sua filha Lia; e estes deu ela à luz a Jacó, a saber, dezesseis pessoas.

[[v1-46-19]]

^<<v1-46-19,19>>^ Os filhos de Raquel, mulher de Jacó: José e Benjamim.

[[v1-46-20]]

^<<v1-46-20,20>>^ Nasceram a José na terra do Egito Manassés e Efraim, que lhe deu à luz Asenate, filha de Potífera, sacerdote de Om.

[[v1-46-21]]

^<<v1-46-21,21>>^ Os filhos de Benjamim: Belá, Bequer, Asbel, Gera, Naamã, Eí, Rôs, Mupim, Hupim e Arde.

[[v1-46-22]]

^<<v1-46-22,22>>^ São estes os filhos de Raquel, que nasceram a Jacó, ao todo catorze pessoas.

[[v1-46-23]]

^<<v1-46-23,23>>^ O filho de Dã: Husim.

[[v1-46-24]]

^<<v1-46-24,24>>^ Os filhos de Naftali: Jazeel, Guni, Jezer e Silém.

[[v1-46-25]]

^<<v1-46-25,25>>^ São estes os filhos de Bila, a qual Labão deu a sua filha Raquel; e estes deu ela à luz a Jacó, ao todo sete pessoas.

[[v1-46-26]]

^<<v1-46-26,26>>^ Todos os que vieram com Jacó para o Egito, que eram os seus descendentes, fora as mulheres dos filhos de Jacó, todos eram sessenta e seis pessoas;

[[v1-46-27]]

^<<v1-46-27,27>>^ e os filhos de José, que lhe nasceram no Egito, eram dois. Todas as pessoas da casa de Jacó, que vieram para o Egito, foram setenta.

[[v1-46-28]]

^<<v1-46-28,28>>^ Jacó enviou Judá adiante de si a José para que soubesse encaminhá-lo a Gósen; e chegaram à terra de Gósen.

[[v1-46-29]]

^<<v1-46-29,29>>^ Então, José aprontou o seu carro e subiu ao encontro de Israel, seu pai, a Gósen. Apresentou-se, lançou-se-lhe ao pescoço e chorou assim longo tempo.

[[v1-46-30]]

^<<v1-46-30,30>>^ Disse Israel a José: Já posso morrer, pois já vi o teu rosto, e ainda vives.

[[v1-46-31]]

^<<v1-46-31,31>>^ E José disse a seus irmãos e à casa de seu pai: Subirei, e farei saber a Faraó, e lhe direi: Meus irmãos e a casa de meu pai, que estavam na terra de Canaã, vieram para mim.

[[v1-46-32]]

^<<v1-46-32,32>>^ Os homens são pastores, são homens de gado, e trouxeram consigo o seu rebanho, e o seu gado, e tudo o que têm.

[[v1-46-33]]

^<<v1-46-33,33>>^ Quando, pois, Faraó vos chamar e disser: Qual é o vosso trabalho?

[[v1-46-34]]

^<<v1-46-34,34>>^ Respondereis: Teus servos foram homens de gado desde a mocidade até agora, tanto nós como nossos pais; para que habiteis na terra de Gósen, porque todo pastor de rebanho é abominação para os egípcios.

'''

xref:001-genesis/001-genesis-045.adoc#v1-45-0[&#60; Capítulo Anterior] | <<v1-46-0,Topo>> | xref:001-genesis/001-genesis-047.adoc#v1-47-0[Próximo Capítulo &#62;]