include::./index.adoc[]

[[v1-42-0]]
=== Gênesis, 42
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-42-1]]

^<<v1-42-1,1>>^ Sabedor Jacó de que havia mantimento no Egito, disse a seus filhos: Por que estais aí a olhar uns para os outros?

[[v1-42-2]]

^<<v1-42-2,2>>^ E ajuntou: Tenho ouvido que há cereais no Egito; descei até lá e comprai-nos deles, para que vivamos e não morramos.

[[v1-42-3]]

^<<v1-42-3,3>>^ Então, desceram dez dos irmãos de José, para comprar cereal do Egito.

[[v1-42-4]]

^<<v1-42-4,4>>^ A Benjamim, porém, irmão de José, não enviou Jacó na companhia dos irmãos, porque dizia: Para que não lhe suceda, acaso, algum desastre.

[[v1-42-5]]

^<<v1-42-5,5>>^ Entre os que iam, pois, para lá, foram também os filhos de Israel; porque havia fome na terra de Canaã.

[[v1-42-6]]

^<<v1-42-6,6>>^ José era governador daquela terra; era ele quem vendia a todos os povos da terra; e os irmãos de José vieram e se prostraram rosto em terra, perante ele.

[[v1-42-7]]

^<<v1-42-7,7>>^ Vendo José a seus irmãos, reconheceu-os, porém não se deu a conhecer, e lhes falou asperamente, e lhes perguntou: Donde vindes? Responderam: Da terra de Canaã, para comprar mantimento.

[[v1-42-8]]

^<<v1-42-8,8>>^ José reconheceu os irmãos; porém eles não o reconheceram.

[[v1-42-9]]

^<<v1-42-9,9>>^ Então, se lembrou José dos sonhos que tivera a respeito deles e lhes disse: Vós sois espiões e viestes para ver os pontos fracos da terra.

[[v1-42-10]]

^<<v1-42-10,10>>^ Responderam-lhe: Não, senhor meu; mas vieram os teus servos para comprar mantimento.

[[v1-42-11]]

^<<v1-42-11,11>>^ Somos todos filhos de um mesmo homem; somos homens honestos; os teus servos não são espiões.

[[v1-42-12]]

^<<v1-42-12,12>>^ Ele, porém, lhes respondeu: Nada disso; pelo contrário, viestes para ver os pontos fracos da terra.

[[v1-42-13]]

^<<v1-42-13,13>>^ Eles disseram: Nós, teus servos, somos doze irmãos, filhos de um homem na terra de Canaã; o mais novo está hoje com nosso pai, outro já não existe.

[[v1-42-14]]

^<<v1-42-14,14>>^ Então, lhes falou José: É como já vos disse: sois espiões.

[[v1-42-15]]

^<<v1-42-15,15>>^ Nisto sereis provados: pela vida de Faraó, daqui não saireis, sem que primeiro venha o vosso irmão mais novo.

[[v1-42-16]]

^<<v1-42-16,16>>^ Enviai um dentre vós, que traga vosso irmão; vós ficareis detidos para que sejam provadas as vossas palavras, se há verdade no que dizeis; ou se não, pela vida de Faraó, sois espiões.

[[v1-42-17]]

^<<v1-42-17,17>>^ E os meteu juntos em prisão três dias.

[[v1-42-18]]

^<<v1-42-18,18>>^ Ao terceiro dia, disse-lhes José: Fazei o seguinte e vivereis, pois temo a Deus.

[[v1-42-19]]

^<<v1-42-19,19>>^ Se sois homens honestos, fique detido um de vós na casa da vossa prisão; vós outros ide, levai cereal para suprir a fome das vossas casas.

[[v1-42-20]]

^<<v1-42-20,20>>^ E trazei-me vosso irmão mais novo, com o que serão verificadas as vossas palavras, e não morrereis. E eles se dispuseram a fazê-lo.

[[v1-42-21]]

^<<v1-42-21,21>>^ Então, disseram uns aos outros: Na verdade, somos culpados, no tocante a nosso irmão, pois lhe vimos a angústia da alma, quando nos rogava, e não lhe acudimos; por isso, nos vem esta ansiedade.

[[v1-42-22]]

^<<v1-42-22,22>>^ Respondeu-lhes Rúben: Não vos disse eu: Não pequeis contra o jovem? E não me quisestes ouvir. Pois vedes aí que se requer de nós o seu sangue.

[[v1-42-23]]

^<<v1-42-23,23>>^ Eles, porém, não sabiam que José os entendia, porque lhes falava por intérprete.

[[v1-42-24]]

^<<v1-42-24,24>>^ E, retirando-se deles, chorou; depois, tornando, lhes falou; tomou a Simeão dentre eles e o algemou na presença deles.

[[v1-42-25]]

^<<v1-42-25,25>>^ Ordenou José que lhes enchessem de cereal os sacos, e lhes restituíssem o dinheiro, a cada um no saco de cereal, e os suprissem de comida para o caminho; e assim lhes foi feito.

[[v1-42-26]]

^<<v1-42-26,26>>^ E carregaram o cereal sobre os seus jumentos e partiram dali.

[[v1-42-27]]

^<<v1-42-27,27>>^ Abrindo um deles o saco de cereal, para dar de comer ao seu jumento na estalagem, deu com o dinheiro na boca do saco de cereal.

[[v1-42-28]]

^<<v1-42-28,28>>^ Então, disse aos irmãos: Devolveram o meu dinheiro; aqui está na boca do saco de cereal. Desfaleceu-lhes o coração, e, atemorizados, entreolhavam-se, dizendo: Que é isto que Deus nos fez?

[[v1-42-29]]

^<<v1-42-29,29>>^ E vieram para Jacó, seu pai, na terra de Canaã, e lhe contaram tudo o que lhes acontecera, dizendo:

[[v1-42-30]]

^<<v1-42-30,30>>^ O homem, o senhor da terra, falou conosco asperamente e nos tratou como espiões da terra.

[[v1-42-31]]

^<<v1-42-31,31>>^ Dissemos-lhe: Somos homens honestos; não somos espiões;

[[v1-42-32]]

^<<v1-42-32,32>>^ somos doze irmãos, filhos de um mesmo pai; um já não existe, e o mais novo está hoje com nosso pai na terra de Canaã.

[[v1-42-33]]

^<<v1-42-33,33>>^ Respondeu-nos o homem, o senhor da terra: Nisto conhecerei que sois homens honestos: deixai comigo um de vossos irmãos, tomai o cereal para remediar a fome de vossas casas e parti;

[[v1-42-34]]

^<<v1-42-34,34>>^ trazei-me vosso irmão mais novo; assim saberei que não sois espiões, mas homens honestos. Então, vos entregarei vosso irmão, e negociareis na terra.

[[v1-42-35]]

^<<v1-42-35,35>>^ Aconteceu que, despejando eles os sacos de cereal, eis cada um tinha a sua trouxinha de dinheiro no saco de cereal; e viram as trouxinhas com o dinheiro, eles e seu pai, e temeram.

[[v1-42-36]]

^<<v1-42-36,36>>^ Então, lhes disse Jacó, seu pai: Tendes-me privado de filhos: José já não existe, Simeão não está aqui, e ides levar a Benjamim! Todas estas coisas me sobrevêm.

[[v1-42-37]]

^<<v1-42-37,37>>^ Mas Rúben disse a seu pai: Mata os meus dois filhos, se to não tornar a trazer; entrega-mo, e eu to restituirei.

[[v1-42-38]]

^<<v1-42-38,38>>^ Ele, porém, disse: Meu filho não descerá convosco; seu irmão é morto, e ele ficou só; se lhe sucede algum desastre no caminho por onde fordes, fareis descer minhas cãs com tristeza à sepultura.

'''

xref:001-genesis/001-genesis-041.adoc#v1-41-0[&#60; Capítulo Anterior] | <<v1-42-0,Topo>> | xref:001-genesis/001-genesis-043.adoc#v1-43-0[Próximo Capítulo &#62;]