include::./index.adoc[]

[[v1-28-0]]
=== Gênesis, 28
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-28-1]]

^<<v1-28-1,1>>^ Isaque chamou a Jacó e, dando-lhe a sua bênção, lhe ordenou, dizendo: Não tomarás esposa dentre as filhas de Canaã.

[[v1-28-2]]

^<<v1-28-2,2>>^ Levanta-te, vai a Padã-Arã, à casa de Betuel, pai de tua mãe, e toma lá por esposa uma das filhas de Labão, irmão de tua mãe.

[[v1-28-3]]

^<<v1-28-3,3>>^ Deus Todo-Poderoso te abençoe, e te faça fecundo, e te multiplique para que venhas a ser uma multidão de povos;

[[v1-28-4]]

^<<v1-28-4,4>>^ e te dê a bênção de Abraão, a ti e à tua descendência contigo, para que possuas a terra de tuas peregrinações, concedida por Deus a Abraão.

[[v1-28-5]]

^<<v1-28-5,5>>^ Assim, despediu Isaque a Jacó, que se foi a Padã-Arã, à casa de Labão, filho de Betuel, o arameu, irmão de Rebeca, mãe de Jacó e de Esaú.

[[v1-28-6]]

^<<v1-28-6,6>>^ Vendo, pois, Esaú que Isaque abençoara a Jacó e o enviara a Padã-Arã, para tomar de lá esposa para si; e vendo que, ao abençoá-lo, lhe ordenara, dizendo: Não tomarás mulher dentre as filhas de Canaã;

[[v1-28-7]]

^<<v1-28-7,7>>^ e vendo, ainda, que Jacó, obedecendo a seu pai e a sua mãe, fora a Padã-Arã;

[[v1-28-8]]

^<<v1-28-8,8>>^ sabedor também de que Isaque, seu pai, não via com bons olhos as filhas de Canaã,

[[v1-28-9]]

^<<v1-28-9,9>>^ foi Esaú à casa de Ismael e, além das mulheres que já possuía, tomou por mulher a Maalate, filha de Ismael, filho de Abraão, e irmã de Nebaiote.

[[v1-28-10]]

^<<v1-28-10,10>>^ Partiu Jacó de Berseba e seguiu para Harã.

[[v1-28-11]]

^<<v1-28-11,11>>^ Tendo chegado a certo lugar, ali passou a noite, pois já era sol-posto; tomou uma das pedras do lugar, fê-la seu travesseiro e se deitou ali mesmo para dormir.

[[v1-28-12]]

^<<v1-28-12,12>>^ E sonhou: Eis posta na terra uma escada cujo topo atingia o céu; e os anjos de Deus subiam e desciam por ela.

[[v1-28-13]]

^<<v1-28-13,13>>^ Perto dele estava o SENHOR e lhe disse: Eu sou o SENHOR, Deus de Abraão, teu pai, e Deus de Isaque. A terra em que agora estás deitado, eu ta darei, a ti e à tua descendência.

[[v1-28-14]]

^<<v1-28-14,14>>^ A tua descendência será como o pó da terra; estender-te-ás para o Ocidente e para o Oriente, para o Norte e para o Sul. Em ti e na tua descendência serão abençoadas todas as famílias da terra.

[[v1-28-15]]

^<<v1-28-15,15>>^ Eis que eu estou contigo, e te guardarei por onde quer que fores, e te farei voltar a esta terra, porque te não desampararei, até cumprir eu aquilo que te hei referido.

[[v1-28-16]]

^<<v1-28-16,16>>^ Despertado Jacó do seu sono, disse: Na verdade, o SENHOR está neste lugar, e eu não o sabia.

[[v1-28-17]]

^<<v1-28-17,17>>^ E, temendo, disse: Quão temível é este lugar! É a Casa de Deus, a porta dos céus.

[[v1-28-18]]

^<<v1-28-18,18>>^ Tendo-se levantado Jacó, cedo, de madrugada, tomou a pedra que havia posto por travesseiro e a erigiu em coluna, sobre cujo topo entornou azeite.

[[v1-28-19]]

^<<v1-28-19,19>>^ E ao lugar, cidade que outrora se chamava Luz, deu o nome de Betel.

[[v1-28-20]]

^<<v1-28-20,20>>^ Fez também Jacó um voto, dizendo: Se Deus for comigo, e me guardar nesta jornada que empreendo, e me der pão para comer e roupa que me vista,

[[v1-28-21]]

^<<v1-28-21,21>>^ de maneira que eu volte em paz para a casa de meu pai, então, o SENHOR será o meu Deus;

[[v1-28-22]]

^<<v1-28-22,22>>^ e a pedra, que erigi por coluna, será a Casa de Deus; e, de tudo quanto me concederes, certamente eu te darei o dízimo.

'''

xref:001-genesis/001-genesis-027.adoc#v1-27-0[&#60; Capítulo Anterior] | <<v1-28-0,Topo>> | xref:001-genesis/001-genesis-029.adoc#v1-29-0[Próximo Capítulo &#62;]