include::./index.adoc[]

[[v1-47-0]]
=== Gênesis, 47
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-47-1]]

^<<v1-47-1,1>>^ Então, veio José e disse a Faraó: Meu pai e meus irmãos, com os seus rebanhos e o seu gado, com tudo o que têm, chegaram da terra de Canaã; e eis que estão na terra de Gósen.

[[v1-47-2]]

^<<v1-47-2,2>>^ E tomou cinco dos seus irmãos e os apresentou a Faraó.

[[v1-47-3]]

^<<v1-47-3,3>>^ Então, perguntou Faraó aos irmãos de José: Qual é o vosso trabalho? Eles responderam: Os teus servos somos pastores de rebanho, tanto nós como nossos pais.

[[v1-47-4]]

^<<v1-47-4,4>>^ Disseram mais a Faraó: Viemos para habitar nesta terra; porque não há pasto para o rebanho de teus servos, pois a fome é severa na terra de Canaã; agora, pois, te rogamos permitas habitem os teus servos na terra de Gósen.

[[v1-47-5]]

^<<v1-47-5,5>>^ Então, disse Faraó a José: Teu pai e teus irmãos vieram a ti.

[[v1-47-6]]

^<<v1-47-6,6>>^ A terra do Egito está perante ti; no melhor da terra faze habitar teu pai e teus irmãos; habitem na terra de Gósen. Se sabes haver entre eles homens capazes, põe-nos por chefes do gado que me pertence.

[[v1-47-7]]

^<<v1-47-7,7>>^ Trouxe José a Jacó, seu pai, e o apresentou a Faraó; e Jacó abençoou a Faraó.

[[v1-47-8]]

^<<v1-47-8,8>>^ Perguntou Faraó a Jacó: Quantos são os dias dos anos da tua vida?

[[v1-47-9]]

^<<v1-47-9,9>>^ Jacó lhe respondeu: Os dias dos anos das minhas peregrinações são cento e trinta anos; poucos e maus foram os dias dos anos da minha vida e não chegaram aos dias dos anos da vida de meus pais, nos dias das suas peregrinações.

[[v1-47-10]]

^<<v1-47-10,10>>^ E, tendo Jacó abençoado a Faraó, saiu de sua presença.

[[v1-47-11]]

^<<v1-47-11,11>>^ Então, José estabeleceu a seu pai e a seus irmãos e lhes deu possessão na terra do Egito, no melhor da terra, na terra de Ramessés, como Faraó ordenara.

[[v1-47-12]]

^<<v1-47-12,12>>^ E José sustentou de pão a seu pai, a seus irmãos e a toda a casa de seu pai, segundo o número de seus filhos.

[[v1-47-13]]

^<<v1-47-13,13>>^ Não havia pão em toda a terra, porque a fome era mui severa; de maneira que desfalecia o povo do Egito e o povo de Canaã por causa da fome.

[[v1-47-14]]

^<<v1-47-14,14>>^ Então, José arrecadou todo o dinheiro que se achou na terra do Egito e na terra de Canaã, pelo cereal que compravam, e o recolheu à casa de Faraó.

[[v1-47-15]]

^<<v1-47-15,15>>^ Tendo-se acabado, pois, o dinheiro, na terra do Egito e na terra de Canaã, foram todos os egípcios a José e disseram: Dá-nos pão; por que haveremos de morrer em tua presença? Porquanto o dinheiro nos falta.

[[v1-47-16]]

^<<v1-47-16,16>>^ Respondeu José: Se vos falta o dinheiro, trazei o vosso gado; em troca do vosso gado eu vos suprirei.

[[v1-47-17]]

^<<v1-47-17,17>>^ Então, trouxeram o seu gado a José; e José lhes deu pão em troca de cavalos, de rebanhos, de gado e de jumentos; e os sustentou de pão aquele ano em troca do seu gado.

[[v1-47-18]]

^<<v1-47-18,18>>^ Findo aquele ano, foram a José no ano próximo e lhe disseram: Não ocultaremos a meu senhor que se acabou totalmente o dinheiro; e meu senhor já possui os animais; nada mais nos resta diante de meu senhor, senão o nosso corpo e a nossa terra.

[[v1-47-19]]

^<<v1-47-19,19>>^ Por que haveremos de perecer diante dos teus olhos, tanto nós como a nossa terra? Compra-nos a nós e a nossa terra a troco de pão, e nós e a nossa terra seremos escravos de Faraó; dá-nos semente para que vivamos e não morramos, e a terra não fique deserta.

[[v1-47-20]]

^<<v1-47-20,20>>^ Assim, comprou José toda a terra do Egito para Faraó, porque os egípcios venderam cada um o seu campo, porquanto a fome era extrema sobre eles; e a terra passou a ser de Faraó.

[[v1-47-21]]

^<<v1-47-21,21>>^ Quanto ao povo, ele o escravizou de uma a outra extremidade da terra do Egito.

[[v1-47-22]]

^<<v1-47-22,22>>^ Somente a terra dos sacerdotes não a comprou ele; pois os sacerdotes tinham porção de Faraó e eles comiam a sua porção que Faraó lhes tinha dado; por isso, não venderam a sua terra.

[[v1-47-23]]

^<<v1-47-23,23>>^ Então, disse José ao povo: Eis que hoje vos comprei a vós outros e a vossa terra para Faraó; aí tendes sementes, semeai a terra.

[[v1-47-24]]

^<<v1-47-24,24>>^ Das colheitas dareis o quinto a Faraó, e as quatro partes serão vossas, para semente do campo, e para o vosso mantimento e dos que estão em vossas casas, e para que comam as vossas crianças.

[[v1-47-25]]

^<<v1-47-25,25>>^ Responderam eles: A vida nos tens dado! Achemos mercê perante meu senhor e seremos escravos de Faraó.

[[v1-47-26]]

^<<v1-47-26,26>>^ E José estabeleceu por lei até ao dia de hoje que, na terra do Egito, tirasse Faraó o quinto; só a terra dos sacerdotes não ficou sendo de Faraó.

[[v1-47-27]]

^<<v1-47-27,27>>^ Assim, habitou Israel na terra do Egito, na terra de Gósen; nela tomaram possessão, e foram fecundos, e muito se multiplicaram.

[[v1-47-28]]

^<<v1-47-28,28>>^ Jacó viveu na terra do Egito dezessete anos; de sorte que os dias de Jacó, os anos da sua vida, foram cento e quarenta e sete.

[[v1-47-29]]

^<<v1-47-29,29>>^ Aproximando-se, pois, o tempo da morte de Israel, chamou a José, seu filho, e lhe disse: Se agora achei mercê à tua presença, rogo-te que ponhas a mão debaixo da minha coxa e uses comigo de beneficência e de verdade; rogo-te que me não enterres no Egito,

[[v1-47-30]]

^<<v1-47-30,30>>^ porém que eu jaza com meus pais; por isso, me levarás do Egito e me enterrarás no lugar da sepultura deles. Respondeu José: Farei segundo a tua palavra.

[[v1-47-31]]

^<<v1-47-31,31>>^ Então, lhe disse Jacó: Jura-me. E ele jurou-lhe; e Israel se inclinou sobre a cabeceira da cama.

'''

xref:001-genesis/001-genesis-046.adoc#v1-46-0[&#60; Capítulo Anterior] | <<v1-47-0,Topo>> | xref:001-genesis/001-genesis-048.adoc#v1-48-0[Próximo Capítulo &#62;]