include::./index.adoc[]

[[v1-10-0]]
=== Gênesis, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-10-1]]

^<<v1-10-1,1>>^ São estas as gerações dos filhos de Noé, Sem, Cam e Jafé; e nasceram-lhes filhos depois do dilúvio.

[[v1-10-2]]

^<<v1-10-2,2>>^ Os filhos de Jafé são: Gomer, Magogue, Madai, Javã, Tubal, Meseque e Tiras.

[[v1-10-3]]

^<<v1-10-3,3>>^ Os filhos de Gomer são: Asquenaz, Rifate e Togarma.

[[v1-10-4]]

^<<v1-10-4,4>>^ Os de Javã são: Elisá, Társis, Quitim e Dodanim.

[[v1-10-5]]

^<<v1-10-5,5>>^ Estes repartiram entre si as ilhas das nações nas suas terras, cada qual segundo a sua língua, segundo as suas famílias, em suas nações.

[[v1-10-6]]

^<<v1-10-6,6>>^ Os filhos de Cam: Cuxe, Mizraim, Pute e Canaã.

[[v1-10-7]]

^<<v1-10-7,7>>^ Os filhos de Cuxe: Sebá, Havilá, Sabtá, Raamá e Sabtecá; e os filhos de Raamá: Sabá e Dedã.

[[v1-10-8]]

^<<v1-10-8,8>>^ Cuxe gerou a Ninrode, o qual começou a ser poderoso na terra.

[[v1-10-9]]

^<<v1-10-9,9>>^ Foi valente caçador diante do SENHOR; daí dizer-se: Como Ninrode, poderoso caçador diante do SENHOR.

[[v1-10-10]]

^<<v1-10-10,10>>^ O princípio do seu reino foi Babel, Ereque, Acade e Calné, na terra de Sinar.

[[v1-10-11]]

^<<v1-10-11,11>>^ Daquela terra saiu ele para a Assíria e edificou Nínive, Reobote-Ir e Calá.

[[v1-10-12]]

^<<v1-10-12,12>>^ E, entre Nínive e Calá, a grande cidade de Resém.

[[v1-10-13]]

^<<v1-10-13,13>>^ Mizraim gerou a Ludim, a Anamim, a Leabim, a Naftuim,

[[v1-10-14]]

^<<v1-10-14,14>>^ a Patrusim, a Casluim (donde saíram os filisteus) e a Caftorim.

[[v1-10-15]]

^<<v1-10-15,15>>^ Canaã gerou a Sidom, seu primogênito, e a Hete,

[[v1-10-16]]

^<<v1-10-16,16>>^ e aos jebuseus, aos amorreus, aos girgaseus,

[[v1-10-17]]

^<<v1-10-17,17>>^ aos heveus, aos arqueus, aos sineus,

[[v1-10-18]]

^<<v1-10-18,18>>^ aos arvadeus, aos zemareus e aos hamateus; e depois se espalharam as famílias dos cananeus.

[[v1-10-19]]

^<<v1-10-19,19>>^ E o limite dos cananeus foi desde Sidom, indo para Gerar, até Gaza, indo para Sodoma, Gomorra, Admá e Zeboim, até Lasa.

[[v1-10-20]]

^<<v1-10-20,20>>^ São estes os filhos de Cam, segundo as suas famílias, segundo as suas línguas, em suas terras, em suas nações.

[[v1-10-21]]

^<<v1-10-21,21>>^ A Sem, que foi pai de todos os filhos de Héber e irmão mais velho de Jafé, também lhe nasceram filhos.

[[v1-10-22]]

^<<v1-10-22,22>>^ Os filhos de Sem são: Elão, Assur, Arfaxade, Lude e Arã.

[[v1-10-23]]

^<<v1-10-23,23>>^ Os filhos de Arã: Uz, Hul, Geter e Más.

[[v1-10-24]]

^<<v1-10-24,24>>^ Arfaxade gerou a Salá; Salá gerou a Héber.

[[v1-10-25]]

^<<v1-10-25,25>>^ A Héber nasceram dois filhos: um teve por nome Pelegue, porquanto em seus dias se repartiu a terra; e o nome de seu irmão foi Joctã.

[[v1-10-26]]

^<<v1-10-26,26>>^ Joctã gerou a Almodá, a Selefe, a Hazar-Mavé, a Jerá,

[[v1-10-27]]

^<<v1-10-27,27>>^ a Hadorão, a Uzal, a Dicla,

[[v1-10-28]]

^<<v1-10-28,28>>^ a Obal, a Abimael, a Sabá,

[[v1-10-29]]

^<<v1-10-29,29>>^ a Ofir, a Havilá e a Jobabe; todos estes foram filhos de Joctã.

[[v1-10-30]]

^<<v1-10-30,30>>^ E habitaram desde Messa, indo para Sefar, montanha do Oriente.

[[v1-10-31]]

^<<v1-10-31,31>>^ São estes os filhos de Sem, segundo as suas famílias, segundo as suas línguas, em suas terras, em suas nações.

[[v1-10-32]]

^<<v1-10-32,32>>^ São estas as famílias dos filhos de Noé, segundo as suas gerações, nas suas nações; e destes foram disseminadas as nações na terra, depois do dilúvio.

'''

xref:001-genesis/001-genesis-009.adoc#v1-9-0[&#60; Capítulo Anterior] | <<v1-10-0,Topo>> | xref:001-genesis/001-genesis-011.adoc#v1-11-0[Próximo Capítulo &#62;]