include::./index.adoc[]

[[v1-26-0]]
=== Gênesis, 26
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-26-1]]

^<<v1-26-1,1>>^ Sobrevindo fome à terra, além da primeira havida nos dias de Abraão, foi Isaque a Gerar, avistar-se com Abimeleque, rei dos filisteus.

[[v1-26-2]]

^<<v1-26-2,2>>^ Apareceu-lhe o SENHOR e disse: Não desças ao Egito. Fica na terra que eu te disser;

[[v1-26-3]]

^<<v1-26-3,3>>^ habita nela, e serei contigo e te abençoarei; porque a ti e a tua descendência darei todas estas terras e confirmarei o juramento que fiz a Abraão, teu pai.

[[v1-26-4]]

^<<v1-26-4,4>>^ Multiplicarei a tua descendência como as estrelas dos céus e lhe darei todas estas terras. Na tua descendência serão abençoadas todas as nações da terra;

[[v1-26-5]]

^<<v1-26-5,5>>^ porque Abraão obedeceu à minha palavra e guardou os meus mandados, os meus preceitos, os meus estatutos e as minhas leis.

[[v1-26-6]]

^<<v1-26-6,6>>^ Isaque, pois, ficou em Gerar.

[[v1-26-7]]

^<<v1-26-7,7>>^ Perguntando-lhe os homens daquele lugar a respeito de sua mulher, disse: É minha irmã; pois temia dizer: É minha mulher; para que, dizia ele consigo, os homens do lugar não me matem por amor de Rebeca, porque era formosa de aparência.

[[v1-26-8]]

^<<v1-26-8,8>>^ Ora, tendo Isaque permanecido ali por muito tempo, Abimeleque, rei dos filisteus, olhando da janela, viu que Isaque acariciava a Rebeca, sua mulher.

[[v1-26-9]]

^<<v1-26-9,9>>^ Então, Abimeleque chamou a Isaque e lhe disse: É evidente que ela é tua esposa; como, pois, disseste: É minha irmã? Respondeu-lhe Isaque: Porque eu dizia: para que eu não morra por causa dela.

[[v1-26-10]]

^<<v1-26-10,10>>^ Disse Abimeleque: Que é isso que nos fizeste? Facilmente algum do povo teria abusado de tua mulher, e tu, atraído sobre nós grave delito.

[[v1-26-11]]

^<<v1-26-11,11>>^ E deu esta ordem a todo o povo: Qualquer que tocar a este homem ou à sua mulher certamente morrerá.

[[v1-26-12]]

^<<v1-26-12,12>>^ Semeou Isaque naquela terra e, no mesmo ano, recolheu cento por um, porque o SENHOR o abençoava.

[[v1-26-13]]

^<<v1-26-13,13>>^ Enriqueceu-se o homem, prosperou, ficou riquíssimo;

[[v1-26-14]]

^<<v1-26-14,14>>^ possuía ovelhas e bois e grande número de servos, de maneira que os filisteus lhe tinham inveja.

[[v1-26-15]]

^<<v1-26-15,15>>^ E, por isso, lhe entulharam todos os poços que os servos de seu pai haviam cavado, nos dias de Abraão, enchendo-os de terra.

[[v1-26-16]]

^<<v1-26-16,16>>^ Disse Abimeleque a Isaque: Aparta-te de nós, porque já és muito mais poderoso do que nós.

[[v1-26-17]]

^<<v1-26-17,17>>^ Então, Isaque saiu dali e se acampou no vale de Gerar, onde habitou.

[[v1-26-18]]

^<<v1-26-18,18>>^ E tornou Isaque a abrir os poços que se cavaram nos dias de Abraão, seu pai (porque os filisteus os haviam entulhado depois da morte de Abraão), e lhes deu os mesmos nomes que já seu pai lhes havia posto.

[[v1-26-19]]

^<<v1-26-19,19>>^ Cavaram os servos de Isaque no vale e acharam um poço de água nascente.

[[v1-26-20]]

^<<v1-26-20,20>>^ Mas os pastores de Gerar contenderam com os pastores de Isaque, dizendo: Esta água é nossa. Por isso, chamou o poço de Eseque, porque contenderam com ele.

[[v1-26-21]]

^<<v1-26-21,21>>^ Então, cavaram outro poço e também por causa desse contenderam. Por isso, recebeu o nome de Sitna.

[[v1-26-22]]

^<<v1-26-22,22>>^ Partindo dali, cavou ainda outro poço; e, como por esse não contenderam, chamou-lhe Reobote e disse: Porque agora nos deu lugar o SENHOR, e prosperaremos na terra.

[[v1-26-23]]

^<<v1-26-23,23>>^ Dali subiu para Berseba.

[[v1-26-24]]

^<<v1-26-24,24>>^ Na mesma noite, lhe apareceu o SENHOR e disse: Eu sou o Deus de Abraão, teu pai. Não temas, porque eu sou contigo; abençoar-te-ei e multiplicarei a tua descendência por amor de Abraão, meu servo.

[[v1-26-25]]

^<<v1-26-25,25>>^ Então, levantou ali um altar e, tendo invocado o nome do SENHOR, armou a sua tenda; e os servos de Isaque abriram ali um poço.

[[v1-26-26]]

^<<v1-26-26,26>>^ De Gerar foram ter com ele Abimeleque e seu amigo Ausate e Ficol, comandante do seu exército.

[[v1-26-27]]

^<<v1-26-27,27>>^ Disse-lhes Isaque: Por que viestes a mim, pois me odiais e me expulsastes do vosso meio?

[[v1-26-28]]

^<<v1-26-28,28>>^ Eles responderam: Vimos claramente que o SENHOR é contigo; então, dissemos: Haja agora juramento entre nós e ti, e façamos aliança contigo.

[[v1-26-29]]

^<<v1-26-29,29>>^ Jura que nos não farás mal, como também não te havemos tocado, e como te fizemos somente o bem, e te deixamos ir em paz. Tu és agora o abençoado do SENHOR.

[[v1-26-30]]

^<<v1-26-30,30>>^ Então, Isaque lhes deu um banquete, e comeram e beberam.

[[v1-26-31]]

^<<v1-26-31,31>>^ Levantando-se de madrugada, juraram de parte a parte; Isaque os despediu, e eles se foram em paz.

[[v1-26-32]]

^<<v1-26-32,32>>^ Nesse mesmo dia, vieram os servos de Isaque e, dando-lhe notícia do poço que tinham cavado, lhe disseram: Achamos água.

[[v1-26-33]]

^<<v1-26-33,33>>^ Ao poço, chamou-lhe Seba; por isso, Berseba é o nome daquela cidade até ao dia de hoje.

[[v1-26-34]]

^<<v1-26-34,34>>^ Tendo Esaú quarenta anos de idade, tomou por esposa a Judite, filha de Beeri, heteu, e a Basemate, filha de Elom, heteu.

[[v1-26-35]]

^<<v1-26-35,35>>^ Ambas se tornaram amargura de espírito para Isaque e para Rebeca.

'''

xref:001-genesis/001-genesis-025.adoc#v1-25-0[&#60; Capítulo Anterior] | <<v1-26-0,Topo>> | xref:001-genesis/001-genesis-027.adoc#v1-27-0[Próximo Capítulo &#62;]