include::./index.adoc[]

[[v1-13-0]]
=== Gênesis, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-13-1]]

^<<v1-13-1,1>>^ Saiu, pois, Abrão do Egito para o Neguebe, ele e sua mulher e tudo o que tinha, e Ló com ele.

[[v1-13-2]]

^<<v1-13-2,2>>^ Era Abrão muito rico; possuía gado, prata e ouro.

[[v1-13-3]]

^<<v1-13-3,3>>^ Fez as suas jornadas do Neguebe até Betel, até ao lugar onde primeiro estivera a sua tenda, entre Betel e Ai,

[[v1-13-4]]

^<<v1-13-4,4>>^ até ao lugar do altar, que outrora tinha feito; e aí Abrão invocou o nome do SENHOR.

[[v1-13-5]]

^<<v1-13-5,5>>^ Ló, que ia com Abrão, também tinha rebanhos, gado e tendas.

[[v1-13-6]]

^<<v1-13-6,6>>^ E a terra não podia sustentá-los, para que habitassem juntos, porque eram muitos os seus bens; de sorte que não podiam habitar um na companhia do outro.

[[v1-13-7]]

^<<v1-13-7,7>>^ Houve contenda entre os pastores do gado de Abrão e os pastores do gado de Ló. Nesse tempo os cananeus e os ferezeus habitavam essa terra.

[[v1-13-8]]

^<<v1-13-8,8>>^ Disse Abrão a Ló: Não haja contenda entre mim e ti e entre os meus pastores e os teus pastores, porque somos parentes chegados.

[[v1-13-9]]

^<<v1-13-9,9>>^ Acaso, não está diante de ti toda a terra? Peço-te que te apartes de mim; se fores para a esquerda, irei para a direita; se fores para a direita, irei para a esquerda.

[[v1-13-10]]

^<<v1-13-10,10>>^ Levantou Ló os olhos e viu toda a campina do Jordão, que era toda bem-regada (antes de haver o SENHOR destruído Sodoma e Gomorra), como o jardim do SENHOR, como a terra do Egito, como quem vai para Zoar.

[[v1-13-11]]

^<<v1-13-11,11>>^ Então, Ló escolheu para si toda a campina do Jordão e partiu para o Oriente; separaram-se um do outro.

[[v1-13-12]]

^<<v1-13-12,12>>^ Habitou Abrão na terra de Canaã; e Ló, nas cidades da campina e ia armando as suas tendas até Sodoma.

[[v1-13-13]]

^<<v1-13-13,13>>^ Ora, os homens de Sodoma eram maus e grandes pecadores contra o SENHOR.

[[v1-13-14]]

^<<v1-13-14,14>>^ Disse o SENHOR a Abrão, depois que Ló se separou dele: Ergue os olhos e olha desde onde estás para o norte, para o sul, para o oriente e para o ocidente;

[[v1-13-15]]

^<<v1-13-15,15>>^ porque toda essa terra que vês, eu ta darei, a ti e à tua descendência, para sempre.

[[v1-13-16]]

^<<v1-13-16,16>>^ Farei a tua descendência como o pó da terra; de maneira que, se alguém puder contar o pó da terra, então se contará também a tua descendência.

[[v1-13-17]]

^<<v1-13-17,17>>^ Levanta-te, percorre essa terra no seu comprimento e na sua largura; porque eu ta darei.

[[v1-13-18]]

^<<v1-13-18,18>>^ E Abrão, mudando as suas tendas, foi habitar nos carvalhais de Manre, que estão junto a Hebrom; e levantou ali um altar ao SENHOR.

'''

xref:001-genesis/001-genesis-012.adoc#v1-12-0[&#60; Capítulo Anterior] | <<v1-13-0,Topo>> | xref:001-genesis/001-genesis-014.adoc#v1-14-0[Próximo Capítulo &#62;]