include::./index.adoc[]

[[v1-35-0]]
=== Gênesis, 35
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-35-1]]

^<<v1-35-1,1>>^ Disse Deus a Jacó: Levanta-te, sobe a Betel e habita ali; faze ali um altar ao Deus que te apareceu quando fugias da presença de Esaú, teu irmão.

[[v1-35-2]]

^<<v1-35-2,2>>^ Então, disse Jacó à sua família e a todos os que com ele estavam: Lançai fora os deuses estranhos que há no vosso meio, purificai-vos e mudai as vossas vestes;

[[v1-35-3]]

^<<v1-35-3,3>>^ levantemo-nos e subamos a Betel. Farei ali um altar ao Deus que me respondeu no dia da minha angústia e me acompanhou no caminho por onde andei.

[[v1-35-4]]

^<<v1-35-4,4>>^ Então, deram a Jacó todos os deuses estrangeiros que tinham em mãos e as argolas que lhes pendiam das orelhas; e Jacó os escondeu debaixo do carvalho que está junto a Siquém.

[[v1-35-5]]

^<<v1-35-5,5>>^ E, tendo eles partido, o terror de Deus invadiu as cidades que lhes eram circunvizinhas, e não perseguiram aos filhos de Jacó.

[[v1-35-6]]

^<<v1-35-6,6>>^ Assim, chegou Jacó a Luz, chamada Betel, que está na terra de Canaã, ele e todo o povo que com ele estava.

[[v1-35-7]]

^<<v1-35-7,7>>^ E edificou ali um altar e ao lugar chamou El-Betel; porque ali Deus se lhe revelou quando fugia da presença de seu irmão.

[[v1-35-8]]

^<<v1-35-8,8>>^ Morreu Débora, a ama de Rebeca, e foi sepultada ao pé de Betel, debaixo do carvalho que se chama Alom-Bacute.

[[v1-35-9]]

^<<v1-35-9,9>>^ Vindo Jacó de Padã-Arã, outra vez lhe apareceu Deus e o abençoou.

[[v1-35-10]]

^<<v1-35-10,10>>^ Disse-lhe Deus: O teu nome é Jacó. Já não te chamarás Jacó, porém Israel será o teu nome. E lhe chamou Israel.

[[v1-35-11]]

^<<v1-35-11,11>>^ Disse-lhe mais: Eu sou o Deus Todo-Poderoso; sê fecundo e multiplica-te; uma nação e multidão de nações sairão de ti, e reis procederão de ti.

[[v1-35-12]]

^<<v1-35-12,12>>^ A terra que dei a Abraão e a Isaque dar-te-ei a ti e, depois de ti, à tua descendência.

[[v1-35-13]]

^<<v1-35-13,13>>^ E Deus se retirou dele, elevando-se do lugar onde lhe falara.

[[v1-35-14]]

^<<v1-35-14,14>>^ Então, Jacó erigiu uma coluna de pedra no lugar onde Deus falara com ele; e derramou sobre ela uma libação e lhe deitou óleo.

[[v1-35-15]]

^<<v1-35-15,15>>^ Ao lugar onde Deus lhe falara, Jacó lhe chamou Betel.

[[v1-35-16]]

^<<v1-35-16,16>>^ Partiram de Betel, e, havendo ainda pequena distância para chegar a Efrata, deu à luz Raquel um filho, cujo nascimento lhe foi a ela penoso.

[[v1-35-17]]

^<<v1-35-17,17>>^ Em meio às dores do parto, disse-lhe a parteira: Não temas, pois ainda terás este filho.

[[v1-35-18]]

^<<v1-35-18,18>>^ Ao sair-lhe a alma (porque morreu), deu-lhe o nome de Benoni; mas seu pai lhe chamou Benjamim.

[[v1-35-19]]

^<<v1-35-19,19>>^ Assim, morreu Raquel e foi sepultada no caminho de Efrata, que é Belém.

[[v1-35-20]]

^<<v1-35-20,20>>^ Sobre a sepultura de Raquel levantou Jacó uma coluna que existe até ao dia de hoje.

[[v1-35-21]]

^<<v1-35-21,21>>^ Então, partiu Israel e armou a sua tenda além da torre de Éder.

[[v1-35-22]]

^<<v1-35-22,22>>^ E aconteceu que, habitando Israel naquela terra, foi Rúben e se deitou com Bila, concubina de seu pai; e Israel o soube. Eram doze os filhos de Israel.

[[v1-35-23]]

^<<v1-35-23,23>>^ Rúben, o primogênito de Jacó, Simeão, Levi, Judá, Issacar e Zebulom, filhos de Lia;

[[v1-35-24]]

^<<v1-35-24,24>>^ José e Benjamim, filhos de Raquel;

[[v1-35-25]]

^<<v1-35-25,25>>^ Dã e Naftali, filhos de Bila, serva de Raquel;

[[v1-35-26]]

^<<v1-35-26,26>>^ e Gade e Aser, filhos de Zilpa, serva de Lia. São estes os filhos de Jacó, que lhe nasceram em Padã-Arã.

[[v1-35-27]]

^<<v1-35-27,27>>^ Veio Jacó a Isaque, seu pai, a Manre, a Quiriate-Arba (que é Hebrom), onde peregrinaram Abraão e Isaque.

[[v1-35-28]]

^<<v1-35-28,28>>^ Foram os dias de Isaque cento e oitenta anos.

[[v1-35-29]]

^<<v1-35-29,29>>^ Velho e farto de dias, expirou Isaque e morreu, sendo recolhido ao seu povo; e Esaú e Jacó, seus filhos, o sepultaram.

'''

xref:001-genesis/001-genesis-034.adoc#v1-34-0[&#60; Capítulo Anterior] | <<v1-35-0,Topo>> | xref:001-genesis/001-genesis-036.adoc#v1-36-0[Próximo Capítulo &#62;]