include::./index.adoc[]

[[v1-41-0]]
=== Gênesis, 41
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-41-1]]

^<<v1-41-1,1>>^ Passados dois anos completos, Faraó teve um sonho. Parecia-lhe achar-se ele de pé junto ao Nilo.

[[v1-41-2]]

^<<v1-41-2,2>>^ Do rio subiam sete vacas formosas à vista e gordas e pastavam no carriçal.

[[v1-41-3]]

^<<v1-41-3,3>>^ Após elas subiam do rio outras sete vacas, feias à vista e magras; e pararam junto às primeiras, na margem do rio.

[[v1-41-4]]

^<<v1-41-4,4>>^ As vacas feias à vista e magras comiam as sete formosas à vista e gordas. Então, acordou Faraó.

[[v1-41-5]]

^<<v1-41-5,5>>^ Tornando a dormir, sonhou outra vez. De uma só haste saíam sete espigas cheias e boas.

[[v1-41-6]]

^<<v1-41-6,6>>^ E após elas nasciam sete espigas mirradas, crestadas do vento oriental.

[[v1-41-7]]

^<<v1-41-7,7>>^ As espigas mirradas devoravam as sete espigas grandes e cheias. Então, acordou Faraó. Fora isto um sonho.

[[v1-41-8]]

^<<v1-41-8,8>>^ De manhã, achando-se ele de espírito perturbado, mandou chamar todos os magos do Egito e todos os seus sábios e lhes contou os sonhos; mas ninguém havia que lhos interpretasse.

[[v1-41-9]]

^<<v1-41-9,9>>^ Então, disse a Faraó o copeiro-chefe: Lembro-me hoje das minhas ofensas.

[[v1-41-10]]

^<<v1-41-10,10>>^ Estando Faraó mui indignado contra os seus servos e pondo-me sob prisão na casa do comandante da guarda, a mim e ao padeiro-chefe,

[[v1-41-11]]

^<<v1-41-11,11>>^ tivemos um sonho na mesma noite, eu e ele; sonhamos, e cada sonho com a sua própria significação.

[[v1-41-12]]

^<<v1-41-12,12>>^ Achava-se conosco um jovem hebreu, servo do comandante da guarda; contamos-lhe os nossos sonhos, e ele no-los interpretou, a cada um segundo o seu sonho.

[[v1-41-13]]

^<<v1-41-13,13>>^ E como nos interpretou, assim mesmo se deu: eu fui restituído ao meu cargo, o outro foi enforcado.

[[v1-41-14]]

^<<v1-41-14,14>>^ Então, Faraó mandou chamar a José, e o fizeram sair à pressa da masmorra; ele se barbeou, mudou de roupa e foi apresentar-se a Faraó.

[[v1-41-15]]

^<<v1-41-15,15>>^ Este lhe disse: Tive um sonho, e não há quem o interprete. Ouvi dizer, porém, a teu respeito que, quando ouves um sonho, podes interpretá-lo.

[[v1-41-16]]

^<<v1-41-16,16>>^ Respondeu-lhe José: Não está isso em mim; mas Deus dará resposta favorável a Faraó.

[[v1-41-17]]

^<<v1-41-17,17>>^ Então, contou Faraó a José: No meu sonho, estava eu de pé na margem do Nilo,

[[v1-41-18]]

^<<v1-41-18,18>>^ e eis que subiam dele sete vacas gordas e formosas à vista e pastavam no carriçal.

[[v1-41-19]]

^<<v1-41-19,19>>^ Após estas subiam outras vacas, fracas, mui feias à vista e magras; nunca vi outras assim disformes, em toda a terra do Egito.

[[v1-41-20]]

^<<v1-41-20,20>>^ E as vacas magras e ruins comiam as primeiras sete gordas;

[[v1-41-21]]

^<<v1-41-21,21>>^ e, depois de as terem engolido, não davam aparência de as terem devorado, pois o seu aspecto continuava ruim como no princípio. Então, acordei.

[[v1-41-22]]

^<<v1-41-22,22>>^ Depois, vi, em meu sonho, que sete espigas saíam da mesma haste, cheias e boas;

[[v1-41-23]]

^<<v1-41-23,23>>^ após elas nasceram sete espigas secas, mirradas e crestadas do vento oriental.

[[v1-41-24]]

^<<v1-41-24,24>>^ As sete espigas mirradas devoravam as sete espigas boas. Contei-o aos magos, mas ninguém houve que mo interpretasse.

[[v1-41-25]]

^<<v1-41-25,25>>^ Então, lhe respondeu José: O sonho de Faraó é apenas um; Deus manifestou a Faraó o que há de fazer.

[[v1-41-26]]

^<<v1-41-26,26>>^ As sete vacas boas serão sete anos; as sete espigas boas, também sete anos; o sonho é um só.

[[v1-41-27]]

^<<v1-41-27,27>>^ As sete vacas magras e feias, que subiam após as primeiras, serão sete anos, bem como as sete espigas mirradas e crestadas do vento oriental serão sete anos de fome.

[[v1-41-28]]

^<<v1-41-28,28>>^ Esta é a palavra, como acabo de dizer a Faraó, que Deus manifestou a Faraó que ele há de fazer.

[[v1-41-29]]

^<<v1-41-29,29>>^ Eis aí vêm sete anos de grande abundância por toda a terra do Egito.

[[v1-41-30]]

^<<v1-41-30,30>>^ Seguir-se-ão sete anos de fome, e toda aquela abundância será esquecida na terra do Egito, e a fome consumirá a terra;

[[v1-41-31]]

^<<v1-41-31,31>>^ e não será lembrada a abundância na terra, em vista da fome que seguirá, porque será gravíssima.

[[v1-41-32]]

^<<v1-41-32,32>>^ O sonho de Faraó foi dúplice, porque a coisa é estabelecida por Deus, e Deus se apressa a fazê-la.

[[v1-41-33]]

^<<v1-41-33,33>>^ Agora, pois, escolha Faraó um homem ajuizado e sábio e o ponha sobre a terra do Egito.

[[v1-41-34]]

^<<v1-41-34,34>>^ Faça isso Faraó, e ponha administradores sobre a terra, e tome a quinta parte dos frutos da terra do Egito nos sete anos de fartura.

[[v1-41-35]]

^<<v1-41-35,35>>^ Ajuntem os administradores toda a colheita dos bons anos que virão, recolham cereal debaixo do poder de Faraó, para mantimento nas cidades, e o guardem.

[[v1-41-36]]

^<<v1-41-36,36>>^ Assim, o mantimento será para abastecer a terra nos sete anos da fome que haverá no Egito; para que a terra não pereça de fome.

[[v1-41-37]]

^<<v1-41-37,37>>^ O conselho foi agradável a Faraó e a todos os seus oficiais.

[[v1-41-38]]

^<<v1-41-38,38>>^ Disse Faraó aos seus oficiais: Acharíamos, porventura, homem como este, em quem há o Espírito de Deus?

[[v1-41-39]]

^<<v1-41-39,39>>^ Depois, disse Faraó a José: Visto que Deus te fez saber tudo isto, ninguém há tão ajuizado e sábio como tu.

[[v1-41-40]]

^<<v1-41-40,40>>^ Administrarás a minha casa, e à tua palavra obedecerá todo o meu povo; somente no trono eu serei maior do que tu.

[[v1-41-41]]

^<<v1-41-41,41>>^ Disse mais Faraó a José: Vês que te faço autoridade sobre toda a terra do Egito.

[[v1-41-42]]

^<<v1-41-42,42>>^ Então, tirou Faraó o seu anel de sinete da mão e o pôs na mão de José, fê-lo vestir roupas de linho fino e lhe pôs ao pescoço um colar de ouro.

[[v1-41-43]]

^<<v1-41-43,43>>^ E fê-lo subir ao seu segundo carro, e clamavam diante dele: Inclinai-vos! Desse modo, o constituiu sobre toda a terra do Egito.

[[v1-41-44]]

^<<v1-41-44,44>>^ Disse ainda Faraó a José: Eu sou Faraó, contudo sem a tua ordem ninguém levantará mão ou pé em toda a terra do Egito.

[[v1-41-45]]

^<<v1-41-45,45>>^ E a José chamou Faraó de Zafenate-Paneia e lhe deu por mulher a Asenate, filha de Potífera, sacerdote de Om; e percorreu José toda a terra do Egito.

[[v1-41-46]]

^<<v1-41-46,46>>^ Era José da idade de trinta anos quando se apresentou a Faraó, rei do Egito, e andou por toda a terra do Egito.

[[v1-41-47]]

^<<v1-41-47,47>>^ Nos sete anos de fartura a terra produziu abundantemente.

[[v1-41-48]]

^<<v1-41-48,48>>^ E ajuntou José todo o mantimento que houve na terra do Egito durante os sete anos e o guardou nas cidades; o mantimento do campo ao redor de cada cidade foi guardado na mesma cidade.

[[v1-41-49]]

^<<v1-41-49,49>>^ Assim, ajuntou José muitíssimo cereal, como a areia do mar, até perder a conta, porque ia além das medidas.

[[v1-41-50]]

^<<v1-41-50,50>>^ Antes de chegar a fome, nasceram dois filhos a José, os quais lhe deu Asenate, filha de Potífera, sacerdote de Om.

[[v1-41-51]]

^<<v1-41-51,51>>^ José ao primogênito chamou de Manassés, pois disse: Deus me fez esquecer de todos os meus trabalhos e de toda a casa de meu pai.

[[v1-41-52]]

^<<v1-41-52,52>>^ Ao segundo, chamou-lhe Efraim, pois disse: Deus me fez próspero na terra da minha aflição.

[[v1-41-53]]

^<<v1-41-53,53>>^ Passados os sete anos de abundância, que houve na terra do Egito,

[[v1-41-54]]

^<<v1-41-54,54>>^ começaram a vir os sete anos de fome, como José havia predito; e havia fome em todas as terras, mas em toda a terra do Egito havia pão.

[[v1-41-55]]

^<<v1-41-55,55>>^ Sentindo toda a terra do Egito a fome, clamou o povo a Faraó por pão; e Faraó dizia a todos os egípcios: Ide a José; o que ele vos disser fazei.

[[v1-41-56]]

^<<v1-41-56,56>>^ Havendo, pois, fome sobre toda a terra, abriu José todos os celeiros e vendia aos egípcios; porque a fome prevaleceu na terra do Egito.

[[v1-41-57]]

^<<v1-41-57,57>>^ E todas as terras vinham ao Egito, para comprar de José, porque a fome prevaleceu em todo o mundo.

'''

xref:001-genesis/001-genesis-040.adoc#v1-40-0[&#60; Capítulo Anterior] | <<v1-41-0,Topo>> | xref:001-genesis/001-genesis-042.adoc#v1-42-0[Próximo Capítulo &#62;]