include::./index.adoc[]

[[v1-29-0]]
=== Gênesis, 29
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-29-1]]

^<<v1-29-1,1>>^ Pôs-se Jacó a caminho e se foi à terra do povo do Oriente.

[[v1-29-2]]

^<<v1-29-2,2>>^ Olhou, e eis um poço no campo e três rebanhos de ovelhas deitados junto dele; porque daquele poço davam de beber aos rebanhos; e havia grande pedra que tapava a boca do poço.

[[v1-29-3]]

^<<v1-29-3,3>>^ Ajuntavam-se ali todos os rebanhos, os pastores removiam a pedra da boca do poço, davam de beber às ovelhas e tornavam a colocá-la no seu devido lugar.

[[v1-29-4]]

^<<v1-29-4,4>>^ Perguntou-lhes Jacó: Meus irmãos, donde sois? Responderam: Somos de Harã.

[[v1-29-5]]

^<<v1-29-5,5>>^ Perguntou-lhes: Conheceis a Labão, filho de Naor? Responderam: Conhecemos.

[[v1-29-6]]

^<<v1-29-6,6>>^ Ele está bom? Perguntou ainda Jacó. Responderam: Está bom. Raquel, sua filha, vem vindo aí com as ovelhas.

[[v1-29-7]]

^<<v1-29-7,7>>^ Então, lhes disse: É ainda pleno dia, não é tempo de se recolherem os rebanhos; dai de beber às ovelhas e ide apascentá-las.

[[v1-29-8]]

^<<v1-29-8,8>>^ Não o podemos, responderam eles, enquanto não se ajuntarem todos os rebanhos, e seja removida a pedra da boca do poço, e lhes demos de beber.

[[v1-29-9]]

^<<v1-29-9,9>>^ Falava-lhes ainda, quando chegou Raquel com as ovelhas de seu pai; porque era pastora.

[[v1-29-10]]

^<<v1-29-10,10>>^ Tendo visto Jacó a Raquel, filha de Labão, irmão de sua mãe, e as ovelhas de Labão, chegou-se, removeu a pedra da boca do poço e deu de beber ao rebanho de Labão, irmão de sua mãe.

[[v1-29-11]]

^<<v1-29-11,11>>^ Feito isso, Jacó beijou a Raquel e, erguendo a voz, chorou.

[[v1-29-12]]

^<<v1-29-12,12>>^ Então, contou Jacó a Raquel que ele era parente de seu pai, pois era filho de Rebeca; ela correu e o comunicou a seu pai.

[[v1-29-13]]

^<<v1-29-13,13>>^ Tendo Labão ouvido as novas de Jacó, filho de sua irmã, correu-lhe ao encontro, abraçou-o, beijou-o e o levou para casa. E contou Jacó a Labão os acontecimentos de sua viagem.

[[v1-29-14]]

^<<v1-29-14,14>>^ Disse-lhe Labão: De fato, és meu osso e minha carne. E Jacó, pelo espaço de um mês, permaneceu com ele.

[[v1-29-15]]

^<<v1-29-15,15>>^ Depois, disse Labão a Jacó: Acaso, por seres meu parente, irás servir-me de graça? Dize-me, qual será o teu salário?

[[v1-29-16]]

^<<v1-29-16,16>>^ Ora, Labão tinha duas filhas: Lia, a mais velha, e Raquel, a mais moça.

[[v1-29-17]]

^<<v1-29-17,17>>^ Lia tinha os olhos baços, porém Raquel era formosa de porte e de semblante.

[[v1-29-18]]

^<<v1-29-18,18>>^ Jacó amava a Raquel e disse: Sete anos te servirei por tua filha mais moça, Raquel.

[[v1-29-19]]

^<<v1-29-19,19>>^ Respondeu Labão: Melhor é que eu ta dê, em vez de dá-la a outro homem; fica, pois, comigo.

[[v1-29-20]]

^<<v1-29-20,20>>^ Assim, por amor a Raquel, serviu Jacó sete anos; e estes lhe pareceram como poucos dias, pelo muito que a amava.

[[v1-29-21]]

^<<v1-29-21,21>>^ Disse Jacó a Labão: Dá-me minha mulher, pois já venceu o prazo, para que me case com ela.

[[v1-29-22]]

^<<v1-29-22,22>>^ Reuniu, pois, Labão todos os homens do lugar e deu um banquete.

[[v1-29-23]]

^<<v1-29-23,23>>^ À noite, conduziu a Lia, sua filha, e a entregou a Jacó. E coabitaram.

[[v1-29-24]]

^<<v1-29-24,24>>^ (Para serva de Lia, sua filha, deu Labão Zilpa, sua serva.)

[[v1-29-25]]

^<<v1-29-25,25>>^ Ao amanhecer, viu que era Lia. Por isso, disse Jacó a Labão: Que é isso que me fizeste? Não te servi eu por amor a Raquel? Por que, pois, me enganaste?

[[v1-29-26]]

^<<v1-29-26,26>>^ Respondeu Labão: Não se faz assim em nossa terra, dar-se a mais nova antes da primogênita.

[[v1-29-27]]

^<<v1-29-27,27>>^ Decorrida a semana desta, dar-te-emos também a outra, pelo trabalho de mais sete anos que ainda me servirás.

[[v1-29-28]]

^<<v1-29-28,28>>^ Concordou Jacó, e se passou a semana desta; então, Labão lhe deu por mulher Raquel, sua filha.

[[v1-29-29]]

^<<v1-29-29,29>>^ (Para serva de Raquel, sua filha, deu Labão a sua serva Bila.)

[[v1-29-30]]

^<<v1-29-30,30>>^ E coabitaram. Mas Jacó amava mais a Raquel do que a Lia; e continuou servindo a Labão por outros sete anos.

[[v1-29-31]]

^<<v1-29-31,31>>^ Vendo o SENHOR que Lia era desprezada, fê-la fecunda; ao passo que Raquel era estéril.

[[v1-29-32]]

^<<v1-29-32,32>>^ Concebeu, pois, Lia e deu à luz um filho, a quem chamou Rúben, pois disse: O SENHOR atendeu à minha aflição. Por isso, agora me amará meu marido.

[[v1-29-33]]

^<<v1-29-33,33>>^ Concebeu outra vez, e deu à luz um filho, e disse: Soube o SENHOR que era preterida e me deu mais este; chamou-lhe, pois, Simeão.

[[v1-29-34]]

^<<v1-29-34,34>>^ Outra vez concebeu Lia, e deu à luz um filho, e disse: Agora, desta vez, se unirá mais a mim meu marido, porque lhe dei à luz três filhos; por isso, lhe chamou Levi.

[[v1-29-35]]

^<<v1-29-35,35>>^ De novo concebeu e deu à luz um filho; então, disse: Esta vez louvarei o SENHOR. E por isso lhe chamou Judá; e cessou de dar à luz.

'''

xref:001-genesis/001-genesis-028.adoc#v1-28-0[&#60; Capítulo Anterior] | <<v1-29-0,Topo>> | xref:001-genesis/001-genesis-030.adoc#v1-30-0[Próximo Capítulo &#62;]