include::./index.adoc[]

[[v1-25-0]]
=== Gênesis, 25
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-25-1]]

^<<v1-25-1,1>>^ Desposou Abraão outra mulher; chamava-se Quetura.

[[v1-25-2]]

^<<v1-25-2,2>>^ Ela lhe deu à luz a Zinrã, Jocsã, Medã, Midiã, Isbaque e Suá.

[[v1-25-3]]

^<<v1-25-3,3>>^ Jocsã gerou a Seba e a Dedã; os filhos de Dedã foram: Assurim, Letusim e Leumim.

[[v1-25-4]]

^<<v1-25-4,4>>^ Os filhos de Midiã foram: Efá, Efer, Enoque, Abida e Elda. Todos estes foram filhos de Quetura.

[[v1-25-5]]

^<<v1-25-5,5>>^ Abraão deu tudo o que possuía a Isaque.

[[v1-25-6]]

^<<v1-25-6,6>>^ Porém, aos filhos das concubinas que tinha, deu ele presentes e, ainda em vida, os separou de seu filho Isaque, enviando-os para a terra oriental.

[[v1-25-7]]

^<<v1-25-7,7>>^ Foram os dias da vida de Abraão cento e setenta e cinco anos.

[[v1-25-8]]

^<<v1-25-8,8>>^ Expirou Abraão; morreu em ditosa velhice, avançado em anos; e foi reunido ao seu povo.

[[v1-25-9]]

^<<v1-25-9,9>>^ Sepultaram-no Isaque e Ismael, seus filhos, na caverna de Macpela, no campo de Efrom, filho de Zoar, o heteu, fronteiro a Manre,

[[v1-25-10]]

^<<v1-25-10,10>>^ o campo que Abraão comprara aos filhos de Hete. Ali foi sepultado Abraão e Sara, sua mulher.

[[v1-25-11]]

^<<v1-25-11,11>>^ Depois da morte de Abraão, Deus abençoou a Isaque, seu filho; Isaque habitava junto a Beer-Laai-Roi.

[[v1-25-12]]

^<<v1-25-12,12>>^ São estas as gerações de Ismael, filho de Abraão, que Agar, egípcia, serva de Sara, lhe deu à luz.

[[v1-25-13]]

^<<v1-25-13,13>>^ E estes, os filhos de Ismael, pelos seus nomes, segundo o seu nascimento: o primogênito de Ismael foi Nebaiote; depois, Quedar, Abdeel, Mibsão,

[[v1-25-14]]

^<<v1-25-14,14>>^ Misma, Dumá, Massá,

[[v1-25-15]]

^<<v1-25-15,15>>^ Hadade, Tema, Jetur, Nafis e Quedemá.

[[v1-25-16]]

^<<v1-25-16,16>>^ São estes os filhos de Ismael, e estes, os seus nomes pelas suas vilas e pelos seus acampamentos: doze príncipes de seus povos.

[[v1-25-17]]

^<<v1-25-17,17>>^ E os anos da vida de Ismael foram cento e trinta e sete; e morreu e foi reunido ao seu povo.

[[v1-25-18]]

^<<v1-25-18,18>>^ Habitaram desde Havilá até Sur, que olha para o Egito, como quem vai para a Assíria. Ele se estabeleceu fronteiro a todos os seus irmãos.

[[v1-25-19]]

^<<v1-25-19,19>>^ São estas as gerações de Isaque, filho de Abraão. Abraão gerou a Isaque;

[[v1-25-20]]

^<<v1-25-20,20>>^ era Isaque de quarenta anos, quando tomou por esposa a Rebeca, filha de Betuel, o arameu de Padã-Arã, e irmã de Labão, o arameu.

[[v1-25-21]]

^<<v1-25-21,21>>^ Isaque orou ao SENHOR por sua mulher, porque ela era estéril; e o SENHOR lhe ouviu as orações, e Rebeca, sua mulher, concebeu.

[[v1-25-22]]

^<<v1-25-22,22>>^ Os filhos lutavam no ventre dela; então, disse: Se é assim, por que vivo eu? E consultou ao SENHOR.

[[v1-25-23]]

^<<v1-25-23,23>>^ Respondeu-lhe o SENHOR: Duas nações há no teu ventre, dois povos, nascidos de ti, se dividirão: um povo será mais forte que o outro, e o mais velho servirá ao mais moço.

[[v1-25-24]]

^<<v1-25-24,24>>^ Cumpridos os dias para que desse à luz, eis que se achavam gêmeos no seu ventre.

[[v1-25-25]]

^<<v1-25-25,25>>^ Saiu o primeiro, ruivo, todo revestido de pelo; por isso, lhe chamaram Esaú.

[[v1-25-26]]

^<<v1-25-26,26>>^ Depois, nasceu o irmão; segurava com a mão o calcanhar de Esaú; por isso, lhe chamaram Jacó. Era Isaque de sessenta anos, quando Rebeca lhos deu à luz.

[[v1-25-27]]

^<<v1-25-27,27>>^ Cresceram os meninos. Esaú saiu perito caçador, homem do campo; Jacó, porém, homem pacato, habitava em tendas.

[[v1-25-28]]

^<<v1-25-28,28>>^ Isaque amava a Esaú, porque se saboreava de sua caça; Rebeca, porém, amava a Jacó.

[[v1-25-29]]

^<<v1-25-29,29>>^ Tinha Jacó feito um cozinhado, quando, esmorecido, veio do campo Esaú

[[v1-25-30]]

^<<v1-25-30,30>>^ e lhe disse: Peço-te que me deixes comer um pouco desse cozinhado vermelho, pois estou esmorecido. Daí chamar-se Edom.

[[v1-25-31]]

^<<v1-25-31,31>>^ Disse Jacó: Vende-me primeiro o teu direito de primogenitura.

[[v1-25-32]]

^<<v1-25-32,32>>^ Ele respondeu: Estou a ponto de morrer; de que me aproveitará o direito de primogenitura?

[[v1-25-33]]

^<<v1-25-33,33>>^ Então, disse Jacó: Jura-me primeiro. Ele jurou e vendeu o seu direito de primogenitura a Jacó.

[[v1-25-34]]

^<<v1-25-34,34>>^ Deu, pois, Jacó a Esaú pão e o cozinhado de lentilhas; ele comeu e bebeu, levantou-se e saiu. Assim, desprezou Esaú o seu direito de primogenitura.

'''

xref:001-genesis/001-genesis-024.adoc#v1-24-0[&#60; Capítulo Anterior] | <<v1-25-0,Topo>> | xref:001-genesis/001-genesis-026.adoc#v1-26-0[Próximo Capítulo &#62;]