include::./index.adoc[]

[[v1-9-0]]
=== Gênesis, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-9-1]]

^<<v1-9-1,1>>^ Abençoou Deus a Noé e a seus filhos e lhes disse: Sede fecundos, multiplicai-vos e enchei a terra.

[[v1-9-2]]

^<<v1-9-2,2>>^ Pavor e medo de vós virão sobre todos os animais da terra e sobre todas as aves dos céus; tudo o que se move sobre a terra e todos os peixes do mar nas vossas mãos serão entregues.

[[v1-9-3]]

^<<v1-9-3,3>>^ Tudo o que se move e vive ser-vos-á para alimento; como vos dei a erva verde, tudo vos dou agora.

[[v1-9-4]]

^<<v1-9-4,4>>^ Carne, porém, com sua vida, isto é, com seu sangue, não comereis.

[[v1-9-5]]

^<<v1-9-5,5>>^ Certamente, requererei o vosso sangue, o sangue da vossa vida; de todo animal o requererei, como também da mão do homem, sim, da mão do próximo de cada um requererei a vida do homem.

[[v1-9-6]]

^<<v1-9-6,6>>^ Se alguém derramar o sangue do homem, pelo homem se derramará o seu; porque Deus fez o homem segundo a sua imagem.

[[v1-9-7]]

^<<v1-9-7,7>>^ Mas sede fecundos e multiplicai-vos; povoai a terra e multiplicai-vos nela.

[[v1-9-8]]

^<<v1-9-8,8>>^ Disse também Deus a Noé e a seus filhos:

[[v1-9-9]]

^<<v1-9-9,9>>^ Eis que estabeleço a minha aliança convosco, e com a vossa descendência,

[[v1-9-10]]

^<<v1-9-10,10>>^ e com todos os seres viventes que estão convosco: tanto as aves, os animais domésticos e os animais selváticos que saíram da arca como todos os animais da terra.

[[v1-9-11]]

^<<v1-9-11,11>>^ Estabeleço a minha aliança convosco: não será mais destruída toda carne por águas de dilúvio, nem mais haverá dilúvio para destruir a terra.

[[v1-9-12]]

^<<v1-9-12,12>>^ Disse Deus: Este é o sinal da minha aliança que faço entre mim e vós e entre todos os seres viventes que estão convosco, para perpétuas gerações:

[[v1-9-13]]

^<<v1-9-13,13>>^ porei nas nuvens o meu arco; será por sinal da aliança entre mim e a terra.

[[v1-9-14]]

^<<v1-9-14,14>>^ Sucederá que, quando eu trouxer nuvens sobre a terra, e nelas aparecer o arco,

[[v1-9-15]]

^<<v1-9-15,15>>^ então, me lembrarei da minha aliança, firmada entre mim e vós e todos os seres viventes de toda carne; e as águas não mais se tornarão em dilúvio para destruir toda carne.

[[v1-9-16]]

^<<v1-9-16,16>>^ O arco estará nas nuvens; vê-lo-ei e me lembrarei da aliança eterna entre Deus e todos os seres viventes de toda carne que há sobre a terra.

[[v1-9-17]]

^<<v1-9-17,17>>^ Disse Deus a Noé: Este é o sinal da aliança estabelecida entre mim e toda carne sobre a terra.

[[v1-9-18]]

^<<v1-9-18,18>>^ Os filhos de Noé, que saíram da arca, foram Sem, Cam e Jafé; Cam é o pai de Canaã.

[[v1-9-19]]

^<<v1-9-19,19>>^ São eles os três filhos de Noé; e deles se povoou toda a terra.

[[v1-9-20]]

^<<v1-9-20,20>>^ Sendo Noé lavrador, passou a plantar uma vinha.

[[v1-9-21]]

^<<v1-9-21,21>>^ Bebendo do vinho, embriagou-se e se pôs nu dentro de sua tenda.

[[v1-9-22]]

^<<v1-9-22,22>>^ Cam, pai de Canaã, vendo a nudez do pai, fê-lo saber, fora, a seus dois irmãos.

[[v1-9-23]]

^<<v1-9-23,23>>^ Então, Sem e Jafé tomaram uma capa, puseram-na sobre os próprios ombros de ambos e, andando de costas, rostos desviados, cobriram a nudez do pai, sem que a vissem.

[[v1-9-24]]

^<<v1-9-24,24>>^ Despertando Noé do seu vinho, soube o que lhe fizera o filho mais moço

[[v1-9-25]]

^<<v1-9-25,25>>^ e disse: Maldito seja Canaã; seja servo dos servos a seus irmãos.

[[v1-9-26]]

^<<v1-9-26,26>>^ E ajuntou: Bendito seja o SENHOR, Deus de Sem; e Canaã lhe seja servo.

[[v1-9-27]]

^<<v1-9-27,27>>^ Engrandeça Deus a Jafé, e habite ele nas tendas de Sem; e Canaã lhe seja servo.

[[v1-9-28]]

^<<v1-9-28,28>>^ Noé, passado o dilúvio, viveu ainda trezentos e cinquenta anos.

[[v1-9-29]]

^<<v1-9-29,29>>^ Todos os dias de Noé foram novecentos e cinquenta anos; e morreu.

'''

xref:001-genesis/001-genesis-008.adoc#v1-8-0[&#60; Capítulo Anterior] | <<v1-9-0,Topo>> | xref:001-genesis/001-genesis-010.adoc#v1-10-0[Próximo Capítulo &#62;]