include::./index.adoc[]

[[v1-39-0]]
=== Gênesis, 39
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-39-1]]

^<<v1-39-1,1>>^ José foi levado ao Egito, e Potifar, oficial de Faraó, comandante da guarda, egípcio, comprou-o dos ismaelitas que o tinham levado para lá.

[[v1-39-2]]

^<<v1-39-2,2>>^ O SENHOR era com José, que veio a ser homem próspero; e estava na casa de seu senhor egípcio.

[[v1-39-3]]

^<<v1-39-3,3>>^ Vendo Potifar que o SENHOR era com ele e que tudo o que ele fazia o SENHOR prosperava em suas mãos,

[[v1-39-4]]

^<<v1-39-4,4>>^ logrou José mercê perante ele, a quem servia; e ele o pôs por mordomo de sua casa e lhe passou às mãos tudo o que tinha.

[[v1-39-5]]

^<<v1-39-5,5>>^ E, desde que o fizera mordomo de sua casa e sobre tudo o que tinha, o SENHOR abençoou a casa do egípcio por amor de José; a bênção do SENHOR estava sobre tudo o que tinha, tanto em casa como no campo.

[[v1-39-6]]

^<<v1-39-6,6>>^ Potifar tudo o que tinha confiou às mãos de José, de maneira que, tendo-o por mordomo, de nada sabia, além do pão com que se alimentava. José era formoso de porte e de aparência.

[[v1-39-7]]

^<<v1-39-7,7>>^ Aconteceu, depois destas coisas, que a mulher de seu senhor pôs os olhos em José e lhe disse: Deita-te comigo.

[[v1-39-8]]

^<<v1-39-8,8>>^ Ele, porém, recusou e disse à mulher do seu senhor: Tem-me por mordomo o meu senhor e não sabe do que há em casa, pois tudo o que tem me passou ele às minhas mãos.

[[v1-39-9]]

^<<v1-39-9,9>>^ Ele não é maior do que eu nesta casa e nenhuma coisa me vedou, senão a ti, porque és sua mulher; como, pois, cometeria eu tamanha maldade e pecaria contra Deus?

[[v1-39-10]]

^<<v1-39-10,10>>^ Falando ela a José todos os dias, e não lhe dando ele ouvidos, para se deitar com ela e estar com ela,

[[v1-39-11]]

^<<v1-39-11,11>>^ sucedeu que, certo dia, veio ele a casa, para atender aos negócios; e ninguém dos de casa se achava presente.

[[v1-39-12]]

^<<v1-39-12,12>>^ Então, ela o pegou pelas vestes e lhe disse: Deita-te comigo; ele, porém, deixando as vestes nas mãos dela, saiu, fugindo para fora.

[[v1-39-13]]

^<<v1-39-13,13>>^ Vendo ela que ele fugira para fora, mas havia deixado as vestes nas mãos dela,

[[v1-39-14]]

^<<v1-39-14,14>>^ chamou pelos homens de sua casa e lhes disse: Vede, trouxe-nos meu marido este hebreu para insultar-nos; veio até mim para se deitar comigo; mas eu gritei em alta voz.

[[v1-39-15]]

^<<v1-39-15,15>>^ Ouvindo ele que eu levantava a voz e gritava, deixou as vestes ao meu lado e saiu, fugindo para fora.

[[v1-39-16]]

^<<v1-39-16,16>>^ Conservou ela junto de si as vestes dele, até que seu senhor tornou a casa.

[[v1-39-17]]

^<<v1-39-17,17>>^ Então, lhe falou, segundo as mesmas palavras, e disse: O servo hebreu, que nos trouxeste, veio ter comigo para insultar-me;

[[v1-39-18]]

^<<v1-39-18,18>>^ quando, porém, levantei a voz e gritei, ele, deixando as vestes ao meu lado, fugiu para fora.

[[v1-39-19]]

^<<v1-39-19,19>>^ Tendo o senhor ouvido as palavras de sua mulher, como lhe tinha dito: Desta maneira me fez o teu servo; então, se lhe acendeu a ira.

[[v1-39-20]]

^<<v1-39-20,20>>^ E o senhor de José o tomou e o lançou no cárcere, no lugar onde os presos do rei estavam encarcerados; ali ficou ele na prisão.

[[v1-39-21]]

^<<v1-39-21,21>>^ O SENHOR, porém, era com José, e lhe foi benigno, e lhe deu mercê perante o carcereiro;

[[v1-39-22]]

^<<v1-39-22,22>>^ o qual confiou às mãos de José todos os presos que estavam no cárcere; e ele fazia tudo quanto se devia fazer ali.

[[v1-39-23]]

^<<v1-39-23,23>>^ E nenhum cuidado tinha o carcereiro de todas as coisas que estavam nas mãos de José, porquanto o SENHOR era com ele, e tudo o que ele fazia o SENHOR prosperava.

'''

xref:001-genesis/001-genesis-038.adoc#v1-38-0[&#60; Capítulo Anterior] | <<v1-39-0,Topo>> | xref:001-genesis/001-genesis-040.adoc#v1-40-0[Próximo Capítulo &#62;]