include::./index.adoc[]

[[v1-1-0]]
=== Gênesis, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-1-1]]

^<<v1-1-1,1>>^ No princípio, criou Deus os céus e a terra.

[[v1-1-2]]

^<<v1-1-2,2>>^ A terra, porém, estava sem forma e vazia; havia trevas sobre a face do abismo, e o Espírito de Deus pairava por sobre as águas.

[[v1-1-3]]

^<<v1-1-3,3>>^ Disse Deus: Haja luz; e houve luz.

[[v1-1-4]]

^<<v1-1-4,4>>^ E viu Deus que a luz era boa; e fez separação entre a luz e as trevas.

[[v1-1-5]]

^<<v1-1-5,5>>^ Chamou Deus à luz Dia e às trevas, Noite. Houve tarde e manhã, o primeiro dia.

[[v1-1-6]]

^<<v1-1-6,6>>^ E disse Deus: Haja firmamento no meio das águas e separação entre águas e águas.

[[v1-1-7]]

^<<v1-1-7,7>>^ Fez, pois, Deus o firmamento e separação entre as águas debaixo do firmamento e as águas sobre o firmamento. E assim se fez.

[[v1-1-8]]

^<<v1-1-8,8>>^ E chamou Deus ao firmamento Céus. Houve tarde e manhã, o segundo dia.

[[v1-1-9]]

^<<v1-1-9,9>>^ Disse também Deus: Ajuntem-se as águas debaixo dos céus num só lugar, e apareça a porção seca. E assim se fez.

[[v1-1-10]]

^<<v1-1-10,10>>^ À porção seca chamou Deus Terra e ao ajuntamento das águas, Mares. E viu Deus que isso era bom.

[[v1-1-11]]

^<<v1-1-11,11>>^ E disse: Produza a terra relva, ervas que deem semente e árvores frutíferas que deem fruto segundo a sua espécie, cuja semente esteja nele, sobre a terra. E assim se fez.

[[v1-1-12]]

^<<v1-1-12,12>>^ A terra, pois, produziu relva, ervas que davam semente segundo a sua espécie e árvores que davam fruto, cuja semente estava nele, conforme a sua espécie. E viu Deus que isso era bom.

[[v1-1-13]]

^<<v1-1-13,13>>^ Houve tarde e manhã, o terceiro dia.

[[v1-1-14]]

^<<v1-1-14,14>>^ Disse também Deus: Haja luzeiros no firmamento dos céus, para fazerem separação entre o dia e a noite; e sejam eles para sinais, para estações, para dias e anos.

[[v1-1-15]]

^<<v1-1-15,15>>^ E sejam para luzeiros no firmamento dos céus, para alumiar a terra. E assim se fez.

[[v1-1-16]]

^<<v1-1-16,16>>^ Fez Deus os dois grandes luzeiros: o maior para governar o dia, e o menor para governar a noite; e fez também as estrelas.

[[v1-1-17]]

^<<v1-1-17,17>>^ E os colocou no firmamento dos céus para alumiarem a terra,

[[v1-1-18]]

^<<v1-1-18,18>>^ para governarem o dia e a noite e fazerem separação entre a luz e as trevas. E viu Deus que isso era bom.

[[v1-1-19]]

^<<v1-1-19,19>>^ Houve tarde e manhã, o quarto dia.

[[v1-1-20]]

^<<v1-1-20,20>>^ Disse também Deus: Povoem-se as águas de enxames de seres viventes; e voem as aves sobre a terra, sob o firmamento dos céus.

[[v1-1-21]]

^<<v1-1-21,21>>^ Criou, pois, Deus os grandes animais marinhos e todos os seres viventes que rastejam, os quais povoavam as águas, segundo as suas espécies; e todas as aves, segundo as suas espécies. E viu Deus que isso era bom.

[[v1-1-22]]

^<<v1-1-22,22>>^ E Deus os abençoou, dizendo: Sede fecundos, multiplicai-vos e enchei as águas dos mares; e, na terra, se multipliquem as aves.

[[v1-1-23]]

^<<v1-1-23,23>>^ Houve tarde e manhã, o quinto dia.

[[v1-1-24]]

^<<v1-1-24,24>>^ Disse também Deus: Produza a terra seres viventes, conforme a sua espécie: animais domésticos, répteis e animais selváticos, segundo a sua espécie. E assim se fez.

[[v1-1-25]]

^<<v1-1-25,25>>^ E fez Deus os animais selváticos, segundo a sua espécie, e os animais domésticos, conforme a sua espécie, e todos os répteis da terra, conforme a sua espécie. E viu Deus que isso era bom.

[[v1-1-26]]

^<<v1-1-26,26>>^ Também disse Deus: Façamos o homem à nossa imagem, conforme a nossa semelhança; tenha ele domínio sobre os peixes do mar, sobre as aves dos céus, sobre os animais domésticos, sobre toda a terra e sobre todos os répteis que rastejam pela terra.

[[v1-1-27]]

^<<v1-1-27,27>>^ Criou Deus, pois, o homem à sua imagem, à imagem de Deus o criou; homem e mulher os criou.

[[v1-1-28]]

^<<v1-1-28,28>>^ E Deus os abençoou e lhes disse: Sede fecundos, multiplicai-vos, enchei a terra e sujeitai-a; dominai sobre os peixes do mar, sobre as aves dos céus e sobre todo animal que rasteja pela terra.

[[v1-1-29]]

^<<v1-1-29,29>>^ E disse Deus ainda: Eis que vos tenho dado todas as ervas que dão semente e se acham na superfície de toda a terra e todas as árvores em que há fruto que dê semente; isso vos será para mantimento.

[[v1-1-30]]

^<<v1-1-30,30>>^ E a todos os animais da terra, e a todas as aves dos céus, e a todos os répteis da terra, em que há fôlego de vida, toda erva verde lhes será para mantimento. E assim se fez.

[[v1-1-31]]

^<<v1-1-31,31>>^ Viu Deus tudo quanto fizera, e eis que era muito bom. Houve tarde e manhã, o sexto dia.

'''

**&#60; Capítulo Anterior** | <<v1-1-0,Topo>> | xref:001-genesis/001-genesis-002.adoc#v1-2-0[Próximo Capítulo &#62;]