include::./index.adoc[]

[[v1-7-0]]
=== Gênesis, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-7-1]]

^<<v1-7-1,1>>^ Disse o SENHOR a Noé: Entra na arca, tu e toda a tua casa, porque reconheço que tens sido justo diante de mim no meio desta geração.

[[v1-7-2]]

^<<v1-7-2,2>>^ De todo animal limpo levarás contigo sete pares: o macho e sua fêmea; mas dos animais imundos, um par: o macho e sua fêmea.

[[v1-7-3]]

^<<v1-7-3,3>>^ Também das aves dos céus, sete pares: macho e fêmea; para se conservar a semente sobre a face da terra.

[[v1-7-4]]

^<<v1-7-4,4>>^ Porque, daqui a sete dias, farei chover sobre a terra durante quarenta dias e quarenta noites; e da superfície da terra exterminarei todos os seres que fiz.

[[v1-7-5]]

^<<v1-7-5,5>>^ E tudo fez Noé, segundo o SENHOR lhe ordenara.

[[v1-7-6]]

^<<v1-7-6,6>>^ Tinha Noé seiscentos anos de idade, quando as águas do dilúvio inundaram a terra.

[[v1-7-7]]

^<<v1-7-7,7>>^ Por causa das águas do dilúvio, entrou Noé na arca, ele com seus filhos, sua mulher e as mulheres de seus filhos.

[[v1-7-8]]

^<<v1-7-8,8>>^ Dos animais limpos, e dos animais imundos, e das aves, e de todo réptil sobre a terra,

[[v1-7-9]]

^<<v1-7-9,9>>^ entraram para Noé, na arca, de dois em dois, macho e fêmea, como Deus lhe ordenara.

[[v1-7-10]]

^<<v1-7-10,10>>^ E aconteceu que, depois de sete dias, vieram sobre a terra as águas do dilúvio.

[[v1-7-11]]

^<<v1-7-11,11>>^ No ano seiscentos da vida de Noé, aos dezessete dias do segundo mês, nesse dia romperam-se todas as fontes do grande abismo, e as comportas dos céus se abriram,

[[v1-7-12]]

^<<v1-7-12,12>>^ e houve copiosa chuva sobre a terra durante quarenta dias e quarenta noites.

[[v1-7-13]]

^<<v1-7-13,13>>^ Nesse mesmo dia entraram na arca Noé, seus filhos Sem, Cam e Jafé, sua mulher e as mulheres de seus filhos;

[[v1-7-14]]

^<<v1-7-14,14>>^ eles, e todos os animais segundo as suas espécies, todo gado segundo as suas espécies, todos os répteis que rastejam sobre a terra segundo as suas espécies, todas as aves segundo as suas espécies, todos os pássaros e tudo o que tem asa.

[[v1-7-15]]

^<<v1-7-15,15>>^ De toda carne, em que havia fôlego de vida, entraram de dois em dois para Noé na arca;

[[v1-7-16]]

^<<v1-7-16,16>>^ eram macho e fêmea os que entraram de toda carne, como Deus lhe havia ordenado; e o SENHOR fechou a porta após ele.

[[v1-7-17]]

^<<v1-7-17,17>>^ Durou o dilúvio quarenta dias sobre a terra; cresceram as águas e levantaram a arca de sobre a terra.

[[v1-7-18]]

^<<v1-7-18,18>>^ Predominaram as águas e cresceram sobremodo na terra; a arca, porém, vogava sobre as águas.

[[v1-7-19]]

^<<v1-7-19,19>>^ Prevaleceram as águas excessivamente sobre a terra e cobriram todos os altos montes que havia debaixo do céu.

[[v1-7-20]]

^<<v1-7-20,20>>^ Quinze côvados acima deles prevaleceram as águas; e os montes foram cobertos.

[[v1-7-21]]

^<<v1-7-21,21>>^ Pereceu toda carne que se movia sobre a terra, tanto de ave como de animais domésticos e animais selváticos, e de todos os enxames de criaturas que povoam a terra, e todo homem.

[[v1-7-22]]

^<<v1-7-22,22>>^ Tudo o que tinha fôlego de vida em suas narinas, tudo o que havia em terra seca, morreu.

[[v1-7-23]]

^<<v1-7-23,23>>^ Assim, foram exterminados todos os seres que havia sobre a face da terra; o homem e o animal, os répteis e as aves dos céus foram extintos da terra; ficou somente Noé e os que com ele estavam na arca.

[[v1-7-24]]

^<<v1-7-24,24>>^ E as águas durante cento e cinquenta dias predominaram sobre a terra.

'''

xref:001-genesis/001-genesis-006.adoc#v1-6-0[&#60; Capítulo Anterior] | <<v1-7-0,Topo>> | xref:001-genesis/001-genesis-008.adoc#v1-8-0[Próximo Capítulo &#62;]