include::./index.adoc[]

[[v1-18-0]]
=== Gênesis, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-18-1]]

^<<v1-18-1,1>>^ Apareceu o SENHOR a Abraão nos carvalhais de Manre, quando ele estava assentado à entrada da tenda, no maior calor do dia.

[[v1-18-2]]

^<<v1-18-2,2>>^ Levantou ele os olhos, olhou, e eis três homens de pé em frente dele. Vendo-os, correu da porta da tenda ao seu encontro, prostrou-se em terra

[[v1-18-3]]

^<<v1-18-3,3>>^ e disse: Senhor meu, se acho mercê em tua presença, rogo-te que não passes do teu servo;

[[v1-18-4]]

^<<v1-18-4,4>>^ traga-se um pouco de água, lavai os pés e repousai debaixo desta árvore;

[[v1-18-5]]

^<<v1-18-5,5>>^ trarei um bocado de pão; refazei as vossas forças, visto que chegastes até vosso servo; depois, seguireis avante. Responderam: Faze como disseste.

[[v1-18-6]]

^<<v1-18-6,6>>^ Apressou-se, pois, Abraão para a tenda de Sara e lhe disse: Amassa depressa três medidas de flor de farinha e faze pão assado ao borralho.

[[v1-18-7]]

^<<v1-18-7,7>>^ Abraão, por sua vez, correu ao gado, tomou um novilho, tenro e bom, e deu-o ao criado, que se apressou em prepará-lo.

[[v1-18-8]]

^<<v1-18-8,8>>^ Tomou também coalhada e leite e o novilho que mandara preparar e pôs tudo diante deles; e permaneceu de pé junto a eles debaixo da árvore; e eles comeram.

[[v1-18-9]]

^<<v1-18-9,9>>^ Então, lhe perguntaram: Sara, tua mulher, onde está? Ele respondeu: Está aí na tenda.

[[v1-18-10]]

^<<v1-18-10,10>>^ Disse um deles: Certamente voltarei a ti, daqui a um ano; e Sara, tua mulher, dará à luz um filho. Sara o estava escutando, à porta da tenda, atrás dele.

[[v1-18-11]]

^<<v1-18-11,11>>^ Abraão e Sara eram já velhos, avançados em idade; e a Sara já lhe havia cessado o costume das mulheres.

[[v1-18-12]]

^<<v1-18-12,12>>^ Riu-se, pois, Sara no seu íntimo, dizendo consigo mesma: Depois de velha, e velho também o meu senhor, terei ainda prazer?

[[v1-18-13]]

^<<v1-18-13,13>>^ Disse o SENHOR a Abraão: Por que se riu Sara, dizendo: Será verdade que darei ainda à luz, sendo velha?

[[v1-18-14]]

^<<v1-18-14,14>>^ Acaso, para o SENHOR há coisa demasiadamente difícil? Daqui a um ano, neste mesmo tempo, voltarei a ti, e Sara terá um filho.

[[v1-18-15]]

^<<v1-18-15,15>>^ Então, Sara, receosa, o negou, dizendo: Não me ri. Ele, porém, disse: Não é assim, é certo que riste.

[[v1-18-16]]

^<<v1-18-16,16>>^ Tendo-se levantado dali aqueles homens, olharam para Sodoma; e Abraão ia com eles, para os encaminhar.

[[v1-18-17]]

^<<v1-18-17,17>>^ Disse o SENHOR: Ocultarei a Abraão o que estou para fazer,

[[v1-18-18]]

^<<v1-18-18,18>>^ visto que Abraão certamente virá a ser uma grande e poderosa nação, e nele serão benditas todas as nações da terra?

[[v1-18-19]]

^<<v1-18-19,19>>^ Porque eu o escolhi para que ordene a seus filhos e a sua casa depois dele, a fim de que guardem o caminho do SENHOR e pratiquem a justiça e o juízo; para que o SENHOR faça vir sobre Abraão o que tem falado a seu respeito.

[[v1-18-20]]

^<<v1-18-20,20>>^ Disse mais o SENHOR: Com efeito, o clamor de Sodoma e Gomorra tem-se multiplicado, e o seu pecado se tem agravado muito.

[[v1-18-21]]

^<<v1-18-21,21>>^ Descerei e verei se, de fato, o que têm praticado corresponde a esse clamor que é vindo até mim; e, se assim não é, sabê-lo-ei.

[[v1-18-22]]

^<<v1-18-22,22>>^ Então, partiram dali aqueles homens e foram para Sodoma; porém Abraão permaneceu ainda na presença do SENHOR.

[[v1-18-23]]

^<<v1-18-23,23>>^ E, aproximando-se a ele, disse: Destruirás o justo com o ímpio?

[[v1-18-24]]

^<<v1-18-24,24>>^ Se houver, porventura, cinquenta justos na cidade, destruirás ainda assim e não pouparás o lugar por amor dos cinquenta justos que nela se encontram?

[[v1-18-25]]

^<<v1-18-25,25>>^ Longe de ti o fazeres tal coisa, matares o justo com o ímpio, como se o justo fosse igual ao ímpio; longe de ti. Não fará justiça o Juiz de toda a terra?

[[v1-18-26]]

^<<v1-18-26,26>>^ Então, disse o SENHOR: Se eu achar em Sodoma cinquenta justos dentro da cidade, pouparei a cidade toda por amor deles.

[[v1-18-27]]

^<<v1-18-27,27>>^ Disse mais Abraão: Eis que me atrevo a falar ao Senhor, eu que sou pó e cinza.

[[v1-18-28]]

^<<v1-18-28,28>>^ Na hipótese de faltarem cinco para cinquenta justos, destruirás por isso toda a cidade? Ele respondeu: Não a destruirei se eu achar ali quarenta e cinco.

[[v1-18-29]]

^<<v1-18-29,29>>^ Disse-lhe ainda mais Abraão: E se, porventura, houver ali quarenta? Respondeu: Não o farei por amor dos quarenta.

[[v1-18-30]]

^<<v1-18-30,30>>^ Insistiu: Não se ire o Senhor, falarei ainda: Se houver, porventura, ali trinta? Respondeu o SENHOR: Não o farei se eu encontrar ali trinta.

[[v1-18-31]]

^<<v1-18-31,31>>^ Continuou Abraão: Eis que me atrevi a falar ao Senhor: Se, porventura, houver ali vinte? Respondeu o SENHOR: Não a destruirei por amor dos vinte.

[[v1-18-32]]

^<<v1-18-32,32>>^ Disse ainda Abraão: Não se ire o Senhor, se lhe falo somente mais esta vez: Se, porventura, houver ali dez? Respondeu o SENHOR: Não a destruirei por amor dos dez.

[[v1-18-33]]

^<<v1-18-33,33>>^ Tendo cessado de falar a Abraão, retirou-se o SENHOR; e Abraão voltou para o seu lugar.

'''

xref:001-genesis/001-genesis-017.adoc#v1-17-0[&#60; Capítulo Anterior] | <<v1-18-0,Topo>> | xref:001-genesis/001-genesis-019.adoc#v1-19-0[Próximo Capítulo &#62;]