include::./index.adoc[]

[[v1-34-0]]
=== Gênesis, 34
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-34-1]]

^<<v1-34-1,1>>^ Ora, Diná, filha que Lia dera à luz a Jacó, saiu para ver as filhas da terra.

[[v1-34-2]]

^<<v1-34-2,2>>^ Viu-a Siquém, filho do heveu Hamor, que era príncipe daquela terra, e, tomando-a, a possuiu e assim a humilhou.

[[v1-34-3]]

^<<v1-34-3,3>>^ Sua alma se apegou a Diná, filha de Jacó, e amou a jovem, e falou-lhe ao coração.

[[v1-34-4]]

^<<v1-34-4,4>>^ Então, disse Siquém a Hamor, seu pai: Consegue-me esta jovem para esposa.

[[v1-34-5]]

^<<v1-34-5,5>>^ Quando soube Jacó que Diná, sua filha, fora violada por Siquém, estavam os seus filhos no campo com o gado; calou-se, pois, até que voltassem.

[[v1-34-6]]

^<<v1-34-6,6>>^ E saiu Hamor, pai de Siquém, para falar com Jacó.

[[v1-34-7]]

^<<v1-34-7,7>>^ Vindo os filhos de Jacó do campo e ouvindo o que acontecera, indignaram-se e muito se iraram, pois Siquém praticara um desatino em Israel, violentando a filha de Jacó, o que se não devia fazer.

[[v1-34-8]]

^<<v1-34-8,8>>^ Disse-lhes Hamor: A alma de meu filho Siquém está enamorada fortemente de vossa filha; peço-vos que lha deis por esposa.

[[v1-34-9]]

^<<v1-34-9,9>>^ Aparentai-vos conosco, dai-nos as vossas filhas e tomai as nossas;

[[v1-34-10]]

^<<v1-34-10,10>>^ habitareis conosco, a terra estará ao vosso dispor; habitai e negociai nela e nela tende possessões.

[[v1-34-11]]

^<<v1-34-11,11>>^ E o próprio Siquém disse ao pai e aos irmãos de Diná: Ache eu mercê diante de vós e vos darei o que determinardes.

[[v1-34-12]]

^<<v1-34-12,12>>^ Majorai de muito o dote de casamento e as dádivas, e darei o que me pedirdes; dai-me, porém, a jovem por esposa.

[[v1-34-13]]

^<<v1-34-13,13>>^ Então, os filhos de Jacó, por causa de lhes haver Siquém violado a irmã, Diná, responderam com dolo a Siquém e a seu pai Hamor e lhes disseram:

[[v1-34-14]]

^<<v1-34-14,14>>^ Não podemos fazer isso, dar nossa irmã a um homem incircunciso; porque isso nos seria ignomínia.

[[v1-34-15]]

^<<v1-34-15,15>>^ Sob uma única condição permitiremos: que vos torneis como nós, circuncidando-se todo macho entre vós;

[[v1-34-16]]

^<<v1-34-16,16>>^ então, vos daremos nossas filhas, tomaremos para nós as vossas, habitaremos convosco e seremos um só povo.

[[v1-34-17]]

^<<v1-34-17,17>>^ Se, porém, não nos ouvirdes e não vos circuncidardes, tomaremos a nossa filha e nos retiraremos embora.

[[v1-34-18]]

^<<v1-34-18,18>>^ Tais palavras agradaram a Hamor e a Siquém, seu filho.

[[v1-34-19]]

^<<v1-34-19,19>>^ Não tardou o jovem em fazer isso, porque amava a filha de Jacó e era o mais honrado de toda a casa de seu pai.

[[v1-34-20]]

^<<v1-34-20,20>>^ Vieram, pois, Hamor e Siquém, seu filho, à porta da sua cidade e falaram aos homens da cidade:

[[v1-34-21]]

^<<v1-34-21,21>>^ Estes homens são pacíficos para conosco; portanto, habitem na terra e negociem nela. A terra é bastante espaçosa para contê-los; recebamos por mulheres a suas filhas e demos-lhes também as nossas.

[[v1-34-22]]

^<<v1-34-22,22>>^ Somente, porém, consentirão os homens em habitar conosco, tornando-nos um só povo, se todo macho entre nós se circuncidar, como eles são circuncidados.

[[v1-34-23]]

^<<v1-34-23,23>>^ O seu gado, as suas possessões e todos os seus animais não serão nossos? Consintamos, pois, com eles, e habitarão conosco.

[[v1-34-24]]

^<<v1-34-24,24>>^ E deram ouvidos a Hamor e a Siquém, seu filho, todos os que saíam da porta da cidade; e todo homem foi circuncidado, dos que saíam pela porta da sua cidade.

[[v1-34-25]]

^<<v1-34-25,25>>^ Ao terceiro dia, quando os homens sentiam mais forte a dor, dois filhos de Jacó, Simeão e Levi, irmãos de Diná, tomaram cada um a sua espada, entraram inesperadamente na cidade e mataram os homens todos.

[[v1-34-26]]

^<<v1-34-26,26>>^ Passaram também ao fio da espada a Hamor e a seu filho Siquém; tomaram a Diná da casa de Siquém e saíram.

[[v1-34-27]]

^<<v1-34-27,27>>^ Sobrevieram os filhos de Jacó aos mortos e saquearam a cidade, porque sua irmã fora violada.

[[v1-34-28]]

^<<v1-34-28,28>>^ Levaram deles os rebanhos, os bois, os jumentos e o que havia na cidade e no campo;

[[v1-34-29]]

^<<v1-34-29,29>>^ todos os seus bens, e todos os seus meninos, e as suas mulheres levaram cativos e pilharam tudo o que havia nas casas.

[[v1-34-30]]

^<<v1-34-30,30>>^ Então, disse Jacó a Simeão e a Levi: Vós me afligistes e me fizestes odioso entre os moradores desta terra, entre os cananeus e os ferezeus; sendo nós pouca gente, reunir-se-ão contra mim, e serei destruído, eu e minha casa.

[[v1-34-31]]

^<<v1-34-31,31>>^ Responderam: Abusaria ele de nossa irmã, como se fosse prostituta?

'''

xref:001-genesis/001-genesis-033.adoc#v1-33-0[&#60; Capítulo Anterior] | <<v1-34-0,Topo>> | xref:001-genesis/001-genesis-035.adoc#v1-35-0[Próximo Capítulo &#62;]