include::./index.adoc[]

[[v1-38-0]]
=== Gênesis, 38
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-38-1]]

^<<v1-38-1,1>>^ Aconteceu, por esse tempo, que Judá se apartou de seus irmãos e se hospedou na casa de um adulamita, chamado Hira.

[[v1-38-2]]

^<<v1-38-2,2>>^ Ali viu Judá a filha de um cananeu, chamado Sua; ele a tomou por mulher e a possuiu.

[[v1-38-3]]

^<<v1-38-3,3>>^ E ela concebeu e deu à luz um filho, e o pai lhe chamou Er.

[[v1-38-4]]

^<<v1-38-4,4>>^ Tornou a conceber e deu à luz um filho; a este deu a mãe o nome de Onã.

[[v1-38-5]]

^<<v1-38-5,5>>^ Continuou ainda e deu à luz outro filho, cujo nome foi Selá; ela estava em Quezibe quando o teve.

[[v1-38-6]]

^<<v1-38-6,6>>^ Judá, pois, tomou esposa para Er, o seu primogênito; o nome dela era Tamar.

[[v1-38-7]]

^<<v1-38-7,7>>^ Er, porém, o primogênito de Judá, era perverso perante o SENHOR, pelo que o SENHOR o fez morrer.

[[v1-38-8]]

^<<v1-38-8,8>>^ Então, disse Judá a Onã: Possui a mulher de teu irmão, cumpre o levirato e suscita descendência a teu irmão.

[[v1-38-9]]

^<<v1-38-9,9>>^ Sabia, porém, Onã que o filho não seria tido por seu; e todas as vezes que possuía a mulher de seu irmão deixava o sêmen cair na terra, para não dar descendência a seu irmão.

[[v1-38-10]]

^<<v1-38-10,10>>^ Isso, porém, que fazia, era mau perante o SENHOR, pelo que também a este fez morrer.

[[v1-38-11]]

^<<v1-38-11,11>>^ Então, disse Judá a Tamar, sua nora: Permanece viúva em casa de teu pai, até que Selá, meu filho, venha a ser homem. Pois disse: Para que não morra também este, como seus irmãos. Assim, Tamar se foi, passando a residir em casa de seu pai.

[[v1-38-12]]

^<<v1-38-12,12>>^ No correr do tempo morreu a filha de Sua, mulher de Judá; e, consolado Judá, subiu aos tosquiadores de suas ovelhas, em Timna, ele e seu amigo Hira, o adulamita.

[[v1-38-13]]

^<<v1-38-13,13>>^ E o comunicaram a Tamar: Eis que o teu sogro sobe a Timna, para tosquiar as ovelhas.

[[v1-38-14]]

^<<v1-38-14,14>>^ Então, ela despiu as vestes de sua viuvez, e, cobrindo-se com um véu, se disfarçou, e se assentou à entrada de Enaim, no caminho de Timna; pois via que Selá já era homem, e ela não lhe fora dada por mulher.

[[v1-38-15]]

^<<v1-38-15,15>>^ Vendo-a Judá, teve-a por meretriz; pois ela havia coberto o rosto.

[[v1-38-16]]

^<<v1-38-16,16>>^ Então, se dirigiu a ela no caminho e lhe disse: Vem, deixa-me possuir-te; porque não sabia que era a sua nora. Ela respondeu: Que me darás para coabitares comigo?

[[v1-38-17]]

^<<v1-38-17,17>>^ Ele respondeu: Enviar-te-ei um cabrito do rebanho. Perguntou ela: Dar-me-ás penhor até que o mandes?

[[v1-38-18]]

^<<v1-38-18,18>>^ Respondeu ele: Que penhor te darei? Ela disse: O teu selo, o teu cordão e o cajado que seguras. Ele, pois, lhos deu e a possuiu; e ela concebeu dele.

[[v1-38-19]]

^<<v1-38-19,19>>^ Levantou-se ela e se foi; tirou de sobre si o véu e tornou às vestes da sua viuvez.

[[v1-38-20]]

^<<v1-38-20,20>>^ Enviou Judá o cabrito, por mão do adulamita, seu amigo, para reaver o penhor da mão da mulher; porém não a encontrou.

[[v1-38-21]]

^<<v1-38-21,21>>^ Então, perguntou aos homens daquele lugar: Onde está a prostituta cultual que se achava junto ao caminho de Enaim? Responderam: Aqui não esteve meretriz nenhuma.

[[v1-38-22]]

^<<v1-38-22,22>>^ Tendo voltado a Judá, disse: Não a encontrei; e também os homens do lugar me disseram: Aqui não esteve prostituta cultual nenhuma.

[[v1-38-23]]

^<<v1-38-23,23>>^ Respondeu Judá: Que ela o guarde para si, para que não nos tornemos em opróbrio; mandei-lhe, com efeito, o cabrito, todavia, não a achaste.

[[v1-38-24]]

^<<v1-38-24,24>>^ Passados quase três meses, foi dito a Judá: Tamar, tua nora, adulterou, pois está grávida. Então, disse Judá: Tirai-a fora para que seja queimada.

[[v1-38-25]]

^<<v1-38-25,25>>^ Em tirando-a, mandou ela dizer a seu sogro: Do homem de quem são estas coisas eu concebi. E disse mais: Reconhece de quem é este selo, e este cordão, e este cajado.

[[v1-38-26]]

^<<v1-38-26,26>>^ Reconheceu-os Judá e disse: Mais justa é ela do que eu, porquanto não a dei a Selá, meu filho. E nunca mais a possuiu.

[[v1-38-27]]

^<<v1-38-27,27>>^ E aconteceu que, estando ela para dar à luz, havia gêmeos no seu ventre.

[[v1-38-28]]

^<<v1-38-28,28>>^ Ao nascerem, um pôs a mão fora, e a parteira, tomando-a, lhe atou um fio encarnado e disse: Este saiu primeiro.

[[v1-38-29]]

^<<v1-38-29,29>>^ Mas, recolhendo ele a mão, saiu o outro; e ela disse: Como rompeste saída? E lhe chamaram Perez.

[[v1-38-30]]

^<<v1-38-30,30>>^ Depois, lhe saiu o irmão, em cuja mão estava o fio encarnado; e lhe chamaram Zera.

'''

xref:001-genesis/001-genesis-037.adoc#v1-37-0[&#60; Capítulo Anterior] | <<v1-38-0,Topo>> | xref:001-genesis/001-genesis-039.adoc#v1-39-0[Próximo Capítulo &#62;]