include::./index.adoc[]

[[v1-16-0]]
=== Gênesis, 16
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-16-1]]

^<<v1-16-1,1>>^ Ora, Sarai, mulher de Abrão, não lhe dava filhos; tendo, porém, uma serva egípcia, por nome Agar,

[[v1-16-2]]

^<<v1-16-2,2>>^ disse Sarai a Abrão: Eis que o SENHOR me tem impedido de dar à luz filhos; toma, pois, a minha serva, e assim me edificarei com filhos por meio dela. E Abrão anuiu ao conselho de Sarai.

[[v1-16-3]]

^<<v1-16-3,3>>^ Então, Sarai, mulher de Abrão, tomou a Agar, egípcia, sua serva, e deu-a por mulher a Abrão, seu marido, depois de ter ele habitado por dez anos na terra de Canaã.

[[v1-16-4]]

^<<v1-16-4,4>>^ Ele a possuiu, e ela concebeu. Vendo ela que havia concebido, foi sua senhora por ela desprezada.

[[v1-16-5]]

^<<v1-16-5,5>>^ Disse Sarai a Abrão: Seja sobre ti a afronta que se me faz a mim. Eu te dei a minha serva para a possuíres; ela, porém, vendo que concebeu, desprezou-me. Julgue o SENHOR entre mim e ti.

[[v1-16-6]]

^<<v1-16-6,6>>^ Respondeu Abrão a Sarai: A tua serva está nas tuas mãos, procede segundo melhor te parecer. Sarai humilhou-a, e ela fugiu de sua presença.

[[v1-16-7]]

^<<v1-16-7,7>>^ Tendo-a achado o Anjo do SENHOR junto a uma fonte de água no deserto, junto à fonte no caminho de Sur,

[[v1-16-8]]

^<<v1-16-8,8>>^ disse-lhe: Agar, serva de Sarai, donde vens e para onde vais? Ela respondeu: Fujo da presença de Sarai, minha senhora.

[[v1-16-9]]

^<<v1-16-9,9>>^ Então, lhe disse o Anjo do SENHOR: Volta para a tua senhora e humilha-te sob suas mãos.

[[v1-16-10]]

^<<v1-16-10,10>>^ Disse-lhe mais o Anjo do SENHOR: Multiplicarei sobremodo a tua descendência, de maneira que, por numerosa, não será contada.

[[v1-16-11]]

^<<v1-16-11,11>>^ Disse-lhe ainda o Anjo do SENHOR: Concebeste e darás à luz um filho, a quem chamarás Ismael, porque o SENHOR te acudiu na tua aflição.

[[v1-16-12]]

^<<v1-16-12,12>>^ Ele será, entre os homens, como um jumento selvagem; a sua mão será contra todos, e a mão de todos, contra ele; e habitará fronteiro a todos os seus irmãos.

[[v1-16-13]]

^<<v1-16-13,13>>^ Então, ela invocou o nome do SENHOR, que lhe falava: Tu és Deus que vê; pois disse ela: Não olhei eu neste lugar para aquele que me vê?

[[v1-16-14]]

^<<v1-16-14,14>>^ Por isso, aquele poço se chama Beer-Laai-Roi; está entre Cades e Berede.

[[v1-16-15]]

^<<v1-16-15,15>>^ Agar deu à luz um filho a Abrão; e Abrão, a seu filho que lhe dera Agar, chamou-lhe Ismael.

[[v1-16-16]]

^<<v1-16-16,16>>^ Era Abrão de oitenta e seis anos, quando Agar lhe deu à luz Ismael.

'''

xref:001-genesis/001-genesis-015.adoc#v1-15-0[&#60; Capítulo Anterior] | <<v1-16-0,Topo>> | xref:001-genesis/001-genesis-017.adoc#v1-17-0[Próximo Capítulo &#62;]