include::./index.adoc[]

[[v1-44-0]]
=== Gênesis, 44
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-44-1]]

^<<v1-44-1,1>>^ Deu José esta ordem ao mordomo de sua casa: Enche de mantimento os sacos que estes homens trouxeram, quanto puderem levar, e põe o dinheiro de cada um na boca do saco de mantimento.

[[v1-44-2]]

^<<v1-44-2,2>>^ O meu copo de prata pô-lo-ás na boca do saco de mantimento do mais novo, com o dinheiro do seu cereal. E assim se fez segundo José dissera.

[[v1-44-3]]

^<<v1-44-3,3>>^ De manhã, quando já claro, despediram-se estes homens, eles com os seus jumentos.

[[v1-44-4]]

^<<v1-44-4,4>>^ Tendo saído eles da cidade, não se havendo ainda distanciado, disse José ao mordomo de sua casa: Levanta-te e segue após esses homens; e, alcançando-os, lhes dirás: Por que pagastes mal por bem?

[[v1-44-5]]

^<<v1-44-5,5>>^ Não é este o copo em que bebe meu senhor? E por meio do qual faz as suas adivinhações? Procedestes mal no que fizestes.

[[v1-44-6]]

^<<v1-44-6,6>>^ E alcançou-os e lhes falou essas palavras.

[[v1-44-7]]

^<<v1-44-7,7>>^ Então, lhe responderam: Por que diz meu senhor tais palavras? Longe estejam teus servos de praticar semelhante coisa.

[[v1-44-8]]

^<<v1-44-8,8>>^ O dinheiro que achamos na boca dos sacos de mantimento, tornamos a trazer-te desde a terra de Canaã; como, pois, furtaríamos da casa do teu senhor prata ou ouro?

[[v1-44-9]]

^<<v1-44-9,9>>^ Aquele dos teus servos, com quem for achado, morra; e nós ainda seremos escravos do meu senhor.

[[v1-44-10]]

^<<v1-44-10,10>>^ Então, lhes respondeu: Seja conforme as vossas palavras; aquele com quem se achar será meu escravo, porém vós sereis inculpados.

[[v1-44-11]]

^<<v1-44-11,11>>^ E se apressaram, e, tendo cada um posto o saco de mantimento em terra, o abriu.

[[v1-44-12]]

^<<v1-44-12,12>>^ O mordomo os examinou, começando do mais velho e acabando no mais novo; e achou-se o copo no saco de mantimento de Benjamim.

[[v1-44-13]]

^<<v1-44-13,13>>^ Então, rasgaram as suas vestes e, carregados de novo os jumentos, tornaram à cidade.

[[v1-44-14]]

^<<v1-44-14,14>>^ E chegou Judá com seus irmãos à casa de José; este ainda estava ali; e prostraram-se em terra diante dele.

[[v1-44-15]]

^<<v1-44-15,15>>^ Disse-lhes José: Que é isso que fizestes? Não sabíeis vós que tal homem como eu é capaz de adivinhar?

[[v1-44-16]]

^<<v1-44-16,16>>^ Então, disse Judá: Que responderemos a meu senhor? Que falaremos? E como nos justificaremos? Achou Deus a iniquidade de teus servos; eis que somos escravos de meu senhor, tanto nós como aquele em cuja mão se achou o copo.

[[v1-44-17]]

^<<v1-44-17,17>>^ Mas ele disse: Longe de mim que eu tal faça; o homem em cuja mão foi achado o copo, esse será meu servo; vós, no entanto, subi em paz para vosso pai.

[[v1-44-18]]

^<<v1-44-18,18>>^ Então, Judá se aproximou dele e disse: Ah! Senhor meu, rogo-te, permite que teu servo diga uma palavra aos ouvidos do meu senhor, e não se acenda a tua ira contra o teu servo; porque tu és como o próprio Faraó.

[[v1-44-19]]

^<<v1-44-19,19>>^ Meu senhor perguntou a seus servos: Tendes pai ou irmão?

[[v1-44-20]]

^<<v1-44-20,20>>^ E respondemos a meu senhor: Temos pai já velho e um filho da sua velhice, o mais novo, cujo irmão é morto; e só ele ficou de sua mãe, e seu pai o ama.

[[v1-44-21]]

^<<v1-44-21,21>>^ Então, disseste a teus servos: Trazei-mo, para que ponha os olhos sobre ele.

[[v1-44-22]]

^<<v1-44-22,22>>^ Respondemos ao meu senhor: O moço não pode deixar o pai; se deixar o pai, este morrerá.

[[v1-44-23]]

^<<v1-44-23,23>>^ Então, disseste a teus servos: Se vosso irmão mais novo não descer convosco, nunca mais me vereis o rosto.

[[v1-44-24]]

^<<v1-44-24,24>>^ Tendo nós subido a teu servo, meu pai, e a ele repetido as palavras de meu senhor,

[[v1-44-25]]

^<<v1-44-25,25>>^ disse nosso pai: Voltai, comprai-nos um pouco de mantimento.

[[v1-44-26]]

^<<v1-44-26,26>>^ Nós respondemos: Não podemos descer; mas, se nosso irmão mais moço for conosco, desceremos; pois não podemos ver a face do homem, se este nosso irmão mais moço não estiver conosco.

[[v1-44-27]]

^<<v1-44-27,27>>^ Então, nos disse o teu servo, nosso pai: Sabeis que minha mulher me deu dois filhos;

[[v1-44-28]]

^<<v1-44-28,28>>^ um se ausentou de mim, e eu disse: Certamente foi despedaçado, e até agora não mais o vi;

[[v1-44-29]]

^<<v1-44-29,29>>^ se agora também tirardes este da minha presença, e lhe acontecer algum desastre, fareis descer as minhas cãs com pesar à sepultura.

[[v1-44-30]]

^<<v1-44-30,30>>^ Agora, pois, indo eu a teu servo, meu pai, e não indo o moço conosco, visto a sua alma estar ligada com a alma dele,

[[v1-44-31]]

^<<v1-44-31,31>>^ vendo ele que o moço não está conosco, morrerá; e teus servos farão descer as cãs de teu servo, nosso pai, com tristeza à sepultura.

[[v1-44-32]]

^<<v1-44-32,32>>^ Porque teu servo se deu por fiador por este moço para com o meu pai, dizendo: Se eu o não tornar a trazer-te, serei culpado para com o meu pai todos os dias.

[[v1-44-33]]

^<<v1-44-33,33>>^ Agora, pois, fique teu servo em lugar do moço por servo de meu senhor, e o moço que suba com seus irmãos.

[[v1-44-34]]

^<<v1-44-34,34>>^ Porque como subirei eu a meu pai, se o moço não for comigo? Para que não veja eu o mal que a meu pai sobrevirá.

'''

xref:001-genesis/001-genesis-043.adoc#v1-43-0[&#60; Capítulo Anterior] | <<v1-44-0,Topo>> | xref:001-genesis/001-genesis-045.adoc#v1-45-0[Próximo Capítulo &#62;]