include::./index.adoc[]

[[v1-40-0]]
=== Gênesis, 40
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-40-1]]

^<<v1-40-1,1>>^ Passadas estas coisas, aconteceu que o mordomo do rei do Egito e o padeiro ofenderam o seu senhor, o rei do Egito.

[[v1-40-2]]

^<<v1-40-2,2>>^ Indignou-se Faraó contra os seus dois oficiais, o copeiro-chefe e o padeiro-chefe.

[[v1-40-3]]

^<<v1-40-3,3>>^ E mandou detê-los na casa do comandante da guarda, no cárcere onde José estava preso.

[[v1-40-4]]

^<<v1-40-4,4>>^ O comandante da guarda pô-los a cargo de José, para que os servisse; e por algum tempo estiveram na prisão.

[[v1-40-5]]

^<<v1-40-5,5>>^ E ambos sonharam, cada um o seu sonho, na mesma noite; cada sonho com a sua própria significação, o copeiro e o padeiro do rei do Egito, que se achavam encarcerados.

[[v1-40-6]]

^<<v1-40-6,6>>^ Vindo José, pela manhã, viu-os, e eis que estavam turbados.

[[v1-40-7]]

^<<v1-40-7,7>>^ Então, perguntou aos oficiais de Faraó, que com ele estavam no cárcere da casa do seu senhor: Por que tendes, hoje, triste o semblante?

[[v1-40-8]]

^<<v1-40-8,8>>^ Eles responderam: Tivemos um sonho, e não há quem o possa interpretar. Disse-lhes José: Porventura, não pertencem a Deus as interpretações? Contai-me o sonho.

[[v1-40-9]]

^<<v1-40-9,9>>^ Então, o copeiro-chefe contou o seu sonho a José e lhe disse: Em meu sonho havia uma videira perante mim.

[[v1-40-10]]

^<<v1-40-10,10>>^ E, na videira, três ramos; ao brotar a vide, havia flores, e seus cachos produziam uvas maduras.

[[v1-40-11]]

^<<v1-40-11,11>>^ O copo de Faraó estava na minha mão; tomei as uvas, e as espremi no copo de Faraó, e o dei na própria mão de Faraó.

[[v1-40-12]]

^<<v1-40-12,12>>^ Então, lhe disse José: Esta é a sua interpretação: os três ramos são três dias;

[[v1-40-13]]

^<<v1-40-13,13>>^ dentro ainda de três dias, Faraó te reabilitará e te reintegrará no teu cargo, e tu lhe darás o copo na própria mão dele, segundo o costume antigo, quando lhe eras copeiro.

[[v1-40-14]]

^<<v1-40-14,14>>^ Porém lembra-te de mim, quando tudo te correr bem; e rogo-te que sejas bondoso para comigo, e faças menção de mim a Faraó, e me faças sair desta casa;

[[v1-40-15]]

^<<v1-40-15,15>>^ porque, de fato, fui roubado da terra dos hebreus; e, aqui, nada fiz, para que me pusessem nesta masmorra.

[[v1-40-16]]

^<<v1-40-16,16>>^ Vendo o padeiro-chefe que a interpretação era boa, disse a José: Eu também sonhei, e eis que três cestos de pão alvo me estavam sobre a cabeça;

[[v1-40-17]]

^<<v1-40-17,17>>^ e no cesto mais alto havia de todos os manjares de Faraó, arte de padeiro; e as aves os comiam do cesto na minha cabeça.

[[v1-40-18]]

^<<v1-40-18,18>>^ Então, lhe disse José: A interpretação é esta: os três cestos são três dias;

[[v1-40-19]]

^<<v1-40-19,19>>^ dentro ainda de três dias, Faraó te tirará fora a cabeça e te pendurará num madeiro, e as aves te comerão as carnes.

[[v1-40-20]]

^<<v1-40-20,20>>^ No terceiro dia, que era aniversário de nascimento de Faraó, deu este um banquete a todos os seus servos; e, no meio destes, reabilitou o copeiro-chefe e condenou o padeiro-chefe.

[[v1-40-21]]

^<<v1-40-21,21>>^ Ao copeiro-chefe reintegrou no seu cargo, no qual dava o copo na mão de Faraó;

[[v1-40-22]]

^<<v1-40-22,22>>^ mas ao padeiro-chefe enforcou, como José havia interpretado.

[[v1-40-23]]

^<<v1-40-23,23>>^ O copeiro-chefe, todavia, não se lembrou de José, porém dele se esqueceu.

'''

xref:001-genesis/001-genesis-039.adoc#v1-39-0[&#60; Capítulo Anterior] | <<v1-40-0,Topo>> | xref:001-genesis/001-genesis-041.adoc#v1-41-0[Próximo Capítulo &#62;]