include::./index.adoc[]

[[v1-27-0]]
=== Gênesis, 27
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-27-1]]

^<<v1-27-1,1>>^ Tendo-se envelhecido Isaque e já não podendo ver, porque os olhos se lhe enfraqueciam, chamou a Esaú, seu filho mais velho, e lhe disse: Meu filho! Respondeu ele: Aqui estou!

[[v1-27-2]]

^<<v1-27-2,2>>^ Disse-lhe o pai: Estou velho e não sei o dia da minha morte.

[[v1-27-3]]

^<<v1-27-3,3>>^ Agora, pois, toma as tuas armas, a tua aljava e o teu arco, sai ao campo, e apanha para mim alguma caça,

[[v1-27-4]]

^<<v1-27-4,4>>^ e faze-me uma comida saborosa, como eu aprecio, e traze-ma, para que eu coma e te abençoe antes que eu morra.

[[v1-27-5]]

^<<v1-27-5,5>>^ Rebeca esteve escutando enquanto Isaque falava com Esaú, seu filho. E foi-se Esaú ao campo para apanhar a caça e trazê-la.

[[v1-27-6]]

^<<v1-27-6,6>>^ Então, disse Rebeca a Jacó, seu filho: Ouvi teu pai falar com Esaú, teu irmão, assim:

[[v1-27-7]]

^<<v1-27-7,7>>^ Traze caça e faze-me uma comida saborosa, para que eu coma e te abençoe diante do SENHOR, antes que eu morra.

[[v1-27-8]]

^<<v1-27-8,8>>^ Agora, pois, meu filho, atende às minhas palavras com que te ordeno.

[[v1-27-9]]

^<<v1-27-9,9>>^ Vai ao rebanho e traze-me dois bons cabritos; deles farei uma saborosa comida para teu pai, como ele aprecia;

[[v1-27-10]]

^<<v1-27-10,10>>^ levá-la-ás a teu pai, para que a coma e te abençoe, antes que morra.

[[v1-27-11]]

^<<v1-27-11,11>>^ Disse Jacó a Rebeca, sua mãe: Esaú, meu irmão, é homem cabeludo, e eu, homem liso.

[[v1-27-12]]

^<<v1-27-12,12>>^ Dar-se-á o caso de meu pai me apalpar, e passarei a seus olhos por zombador; assim, trarei sobre mim maldição e não bênção.

[[v1-27-13]]

^<<v1-27-13,13>>^ Respondeu-lhe a mãe: Caia sobre mim essa maldição, meu filho; atende somente o que eu te digo, vai e traze-mos.

[[v1-27-14]]

^<<v1-27-14,14>>^ Ele foi, tomou-os e os trouxe a sua mãe, que fez uma saborosa comida, como o pai dele apreciava.

[[v1-27-15]]

^<<v1-27-15,15>>^ Depois, tomou Rebeca a melhor roupa de Esaú, seu filho mais velho, roupa que tinha consigo em casa, e vestiu a Jacó, seu filho mais novo.

[[v1-27-16]]

^<<v1-27-16,16>>^ Com a pele dos cabritos cobriu-lhe as mãos e a lisura do pescoço.

[[v1-27-17]]

^<<v1-27-17,17>>^ Então, entregou a Jacó, seu filho, a comida saborosa e o pão que havia preparado.

[[v1-27-18]]

^<<v1-27-18,18>>^ Jacó foi a seu pai e disse: Meu pai! Ele respondeu: Fala! Quem és tu, meu filho?

[[v1-27-19]]

^<<v1-27-19,19>>^ Respondeu Jacó a seu pai: Sou Esaú, teu primogênito; fiz o que me ordenaste. Levanta-te, pois, assenta-te e come da minha caça, para que me abençoes.

[[v1-27-20]]

^<<v1-27-20,20>>^ Disse Isaque a seu filho: Como é isso que a pudeste achar tão depressa, meu filho? Ele respondeu: Porque o SENHOR, teu Deus, a mandou ao meu encontro.

[[v1-27-21]]

^<<v1-27-21,21>>^ Então, disse Isaque a Jacó: Chega-te aqui, para que eu te apalpe, meu filho, e veja se és meu filho Esaú ou não.

[[v1-27-22]]

^<<v1-27-22,22>>^ Jacó chegou-se a Isaque, seu pai, que o apalpou e disse: A voz é de Jacó, porém as mãos são de Esaú.

[[v1-27-23]]

^<<v1-27-23,23>>^ E não o reconheceu, porque as mãos, com efeito, estavam peludas como as de seu irmão Esaú. E o abençoou.

[[v1-27-24]]

^<<v1-27-24,24>>^ E lhe disse: És meu filho Esaú mesmo? Ele respondeu: Eu sou.

[[v1-27-25]]

^<<v1-27-25,25>>^ Então, disse: Chega isso para perto de mim, para que eu coma da caça de meu filho; para que eu te abençoe. Chegou-lho, e ele comeu; trouxe-lhe também vinho, e ele bebeu.

[[v1-27-26]]

^<<v1-27-26,26>>^ Então, lhe disse Isaque, seu pai: Chega-te e dá-me um beijo, meu filho.

[[v1-27-27]]

^<<v1-27-27,27>>^ Ele se chegou e o beijou. Então, o pai aspirou o cheiro da roupa dele, e o abençoou, e disse: Eis que o cheiro do meu filho é como o cheiro do campo, que o SENHOR abençoou;

[[v1-27-28]]

^<<v1-27-28,28>>^ Deus te dê do orvalho do céu, e da exuberância da terra, e fartura de trigo e de mosto.

[[v1-27-29]]

^<<v1-27-29,29>>^ Sirvam-te povos, e nações te reverenciem; sê senhor de teus irmãos, e os filhos de tua mãe se encurvem a ti; maldito seja o que te amaldiçoar, e abençoado o que te abençoar.

[[v1-27-30]]

^<<v1-27-30,30>>^ Mal acabara Isaque de abençoar a Jacó, tendo este saído da presença de Isaque, seu pai, chega Esaú, seu irmão, da sua caçada.

[[v1-27-31]]

^<<v1-27-31,31>>^ E fez também ele uma comida saborosa, a trouxe a seu pai e lhe disse: Levanta-te, meu pai, e come da caça de teu filho, para que me abençoes.

[[v1-27-32]]

^<<v1-27-32,32>>^ Perguntou-lhe Isaque, seu pai: Quem és tu? Sou Esaú, teu filho, o teu primogênito, respondeu.

[[v1-27-33]]

^<<v1-27-33,33>>^ Então, estremeceu Isaque de violenta comoção e disse: Quem é, pois, aquele que apanhou a caça e ma trouxe? Eu comi de tudo, antes que viesses, e o abençoei, e ele será abençoado.

[[v1-27-34]]

^<<v1-27-34,34>>^ Como ouvisse Esaú tais palavras de seu pai, bradou com profundo amargor e lhe disse: Abençoa-me também a mim, meu pai!

[[v1-27-35]]

^<<v1-27-35,35>>^ Respondeu-lhe o pai: Veio teu irmão astuciosamente e tomou a tua bênção.

[[v1-27-36]]

^<<v1-27-36,36>>^ Disse Esaú: Não é com razão que se chama ele Jacó? Pois já duas vezes me enganou: tirou-me o direito de primogenitura e agora usurpa a bênção que era minha. Disse ainda: Não reservaste, pois, bênção nenhuma para mim?

[[v1-27-37]]

^<<v1-27-37,37>>^ Então, respondeu Isaque a Esaú: Eis que o constituí em teu senhor, e todos os seus irmãos lhe dei por servos; de trigo e de mosto o apercebi; que me será dado fazer-te agora, meu filho?

[[v1-27-38]]

^<<v1-27-38,38>>^ Disse Esaú a seu pai: Acaso, tens uma única bênção, meu pai? Abençoa-me, também a mim, meu pai. E, levantando Esaú a voz, chorou.

[[v1-27-39]]

^<<v1-27-39,39>>^ Então, lhe respondeu Isaque, seu pai: Longe dos lugares férteis da terra será a tua habitação, e sem orvalho que cai do alto.

[[v1-27-40]]

^<<v1-27-40,40>>^ Viverás da tua espada e servirás a teu irmão; quando, porém, te libertares, sacudirás o seu jugo da tua cerviz.

[[v1-27-41]]

^<<v1-27-41,41>>^ Passou Esaú a odiar a Jacó por causa da bênção, com que seu pai o tinha abençoado; e disse consigo: Vêm próximos os dias de luto por meu pai; então, matarei a Jacó, meu irmão.

[[v1-27-42]]

^<<v1-27-42,42>>^ Chegaram aos ouvidos de Rebeca estas palavras de Esaú, seu filho mais velho; ela, pois, mandou chamar a Jacó, seu filho mais moço, e lhe disse: Eis que Esaú, teu irmão, se consola a teu respeito, resolvendo matar-te.

[[v1-27-43]]

^<<v1-27-43,43>>^ Agora, pois, meu filho, ouve o que te digo: retira-te para a casa de Labão, meu irmão, em Harã;

[[v1-27-44]]

^<<v1-27-44,44>>^ fica com ele alguns dias, até que passe o furor de teu irmão,

[[v1-27-45]]

^<<v1-27-45,45>>^ e cesse o seu rancor contra ti, e se esqueça do que lhe fizeste. Então, providenciarei e te farei regressar de lá. Por que hei de eu perder os meus dois filhos num só dia?

[[v1-27-46]]

^<<v1-27-46,46>>^ Disse Rebeca a Isaque: Aborrecida estou da minha vida, por causa das filhas de Hete; se Jacó tomar esposa dentre as filhas de Hete, tais como estas, as filhas desta terra, de que me servirá a vida?

'''

xref:001-genesis/001-genesis-026.adoc#v1-26-0[&#60; Capítulo Anterior] | <<v1-27-0,Topo>> | xref:001-genesis/001-genesis-028.adoc#v1-28-0[Próximo Capítulo &#62;]