include::./index.adoc[]

[[v1-36-0]]
=== Gênesis, 36
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-36-1]]

^<<v1-36-1,1>>^ São estes os descendentes de Esaú, que é Edom.

[[v1-36-2]]

^<<v1-36-2,2>>^ Esaú tomou por mulheres dentre as filhas de Canaã: Ada, filha de Elom, heteu; Oolibama, filha de Aná, filho de Zibeão, heveu;

[[v1-36-3]]

^<<v1-36-3,3>>^ e Basemate, filha de Ismael, irmã de Nebaiote.

[[v1-36-4]]

^<<v1-36-4,4>>^ A Ada de Esaú lhe nasceu Elifaz, a Basemate lhe nasceu Reuel;

[[v1-36-5]]

^<<v1-36-5,5>>^ e a Oolibama nasceu Jeús, Jalão e Corá; são estes os filhos de Esaú, que lhe nasceram na terra de Canaã.

[[v1-36-6]]

^<<v1-36-6,6>>^ Levou Esaú suas mulheres, e seus filhos, e suas filhas, e todas as pessoas de sua casa, e seu rebanho, e todo o seu gado, e toda propriedade, tudo que havia adquirido na terra de Canaã; e se foi para outra terra, apartando-se de Jacó, seu irmão.

[[v1-36-7]]

^<<v1-36-7,7>>^ Porque os bens deles eram muitos para habitarem juntos; e a terra de suas peregrinações não os podia sustentar por causa do seu gado.

[[v1-36-8]]

^<<v1-36-8,8>>^ Então, Esaú, que é Edom, habitou no monte Seir.

[[v1-36-9]]

^<<v1-36-9,9>>^ Esta é a descendência de Esaú, pai dos edomitas, no monte Seir.

[[v1-36-10]]

^<<v1-36-10,10>>^ São estes os nomes dos filhos de Esaú: Elifaz, filho de Ada, mulher de Esaú; Reuel, filho de Basemate, mulher de Esaú.

[[v1-36-11]]

^<<v1-36-11,11>>^ Os filhos de Elifaz são: Temã, Omar, Zefô, Gaetã e Quenaz.

[[v1-36-12]]

^<<v1-36-12,12>>^ Timna era concubina de Elifaz, filho de Esaú, e teve de Elifaz a Amaleque; são estes os filhos de Ada, mulher de Esaú.

[[v1-36-13]]

^<<v1-36-13,13>>^ E os filhos de Reuel são estes: Naate, Zerá, Samá e Mizá; estes foram os filhos de Basemate, mulher de Esaú.

[[v1-36-14]]

^<<v1-36-14,14>>^ E são estes os filhos de Oolibama, filha de Aná, filho de Zibeão, mulher de Esaú; e deu a Esaú: Jeús, Jalão e Corá.

[[v1-36-15]]

^<<v1-36-15,15>>^ São estes os príncipes dos filhos de Esaú; os filhos de Elifaz, o primogênito de Esaú: o príncipe Temã, o príncipe Omar, o príncipe Zefô, o príncipe Quenaz,

[[v1-36-16]]

^<<v1-36-16,16>>^ o príncipe Corá, o príncipe Gaetã, o príncipe Amaleque; são estes os príncipes que nasceram a Elifaz na terra de Edom; são os filhos de Ada.

[[v1-36-17]]

^<<v1-36-17,17>>^ São estes os filhos de Reuel, filho de Esaú: o príncipe Naate, o príncipe Zerá, o príncipe Samá, o príncipe Mizá; são estes os príncipes que nasceram a Reuel na terra de Edom; são os filhos de Basemate, mulher de Esaú.

[[v1-36-18]]

^<<v1-36-18,18>>^ São estes os filhos de Oolibama, mulher de Esaú: o príncipe Jeús, o príncipe Jalão, o príncipe Corá; são estes os príncipes que procederam de Oolibama, filha de Aná, mulher de Esaú.

[[v1-36-19]]

^<<v1-36-19,19>>^ São estes os filhos de Esaú, e esses seus príncipes; ele é Edom.

[[v1-36-20]]

^<<v1-36-20,20>>^ São estes os filhos de Seir, o horeu, moradores da terra: Lotã, Sobal, Zibeão e Aná,

[[v1-36-21]]

^<<v1-36-21,21>>^ Disom, Eser e Disã; são estes os príncipes dos horeus, filhos de Seir na terra de Edom.

[[v1-36-22]]

^<<v1-36-22,22>>^ Os filhos de Lotã são Hori e Homã; a irmã de Lotã é Timna.

[[v1-36-23]]

^<<v1-36-23,23>>^ São estes os filhos de Sobal: Alvã, Manaate, Ebal, Sefô e Onã.

[[v1-36-24]]

^<<v1-36-24,24>>^ São estes os filhos de Zibeão: Aiá e Aná; este é o Aná que achou as fontes termais no deserto, quando apascentava os jumentos de Zibeão, seu pai.

[[v1-36-25]]

^<<v1-36-25,25>>^ São estes os filhos de Aná: Disom e Oolibama, a filha de Aná.

[[v1-36-26]]

^<<v1-36-26,26>>^ São estes os filhos de Disom: Hendã, Esbã, Itrã e Querã.

[[v1-36-27]]

^<<v1-36-27,27>>^ São estes os filhos de Eser: Bilã, Zaavã e Acã.

[[v1-36-28]]

^<<v1-36-28,28>>^ São estes os filhos de Disã: Uz e Arã.

[[v1-36-29]]

^<<v1-36-29,29>>^ São estes os príncipes dos horeus: o príncipe Lotã, o príncipe Sobal, o príncipe Zibeão, o príncipe Aná,

[[v1-36-30]]

^<<v1-36-30,30>>^ o príncipe Disom, o príncipe Eser, o príncipe Disã; são estes os príncipes dos horeus, segundo os seus principados na terra de Seir.

[[v1-36-31]]

^<<v1-36-31,31>>^ São estes os reis que reinaram na terra de Edom, antes que houvesse rei sobre os filhos de Israel.

[[v1-36-32]]

^<<v1-36-32,32>>^ Em Edom reinou Belá, filho de Beor, e o nome da sua cidade era Dinabá.

[[v1-36-33]]

^<<v1-36-33,33>>^ Morreu Belá, e, em seu lugar, reinou Jobabe, filho de Zerá, de Bozra.

[[v1-36-34]]

^<<v1-36-34,34>>^ Morreu Jobabe, e, em seu lugar, reinou Husão, da terra dos temanitas.

[[v1-36-35]]

^<<v1-36-35,35>>^ Morreu Husão, e, em seu lugar, reinou Hadade, filho de Bedade, o que feriu a Midiã no campo de Moabe; o nome da sua cidade era Avite.

[[v1-36-36]]

^<<v1-36-36,36>>^ Morreu Hadade, e, em seu lugar, reinou Samlá, de Masreca.

[[v1-36-37]]

^<<v1-36-37,37>>^ Morreu Samlá, e, em seu lugar, reinou Saul, de Reobote, junto ao Eufrates.

[[v1-36-38]]

^<<v1-36-38,38>>^ Morreu Saul, e, em seu lugar, reinou Baal-Hanã, filho de Acbor.

[[v1-36-39]]

^<<v1-36-39,39>>^ Morreu Baal-Hanã, filho de Acbor, e, em seu lugar, reinou Hadar; o nome de sua cidade era Paú; e o de sua mulher era Meetabel, filha de Matrede, filha de Me-Zaabe.

[[v1-36-40]]

^<<v1-36-40,40>>^ São estes os nomes dos príncipes de Esaú, segundo as suas famílias, os seus lugares e os seus nomes: o príncipe Timna, o príncipe Alva, o príncipe Jetete,

[[v1-36-41]]

^<<v1-36-41,41>>^ o príncipe Oolibama, o príncipe Elá, o príncipe Pinom,

[[v1-36-42]]

^<<v1-36-42,42>>^ o príncipe Quenaz, o príncipe Temã, o príncipe Mibzar,

[[v1-36-43]]

^<<v1-36-43,43>>^ o príncipe Magdiel e o príncipe Irã; são estes os príncipes de Edom, segundo as suas habitações na terra da sua possessão. Este é Esaú, pai de Edom.

'''

xref:001-genesis/001-genesis-035.adoc#v1-35-0[&#60; Capítulo Anterior] | <<v1-36-0,Topo>> | xref:001-genesis/001-genesis-037.adoc#v1-37-0[Próximo Capítulo &#62;]