include::./index.adoc[]

[[v1-30-0]]
=== Gênesis, 30
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-30-1]]

^<<v1-30-1,1>>^ Vendo Raquel que não dava filhos a Jacó, teve ciúmes de sua irmã e disse a Jacó: Dá-me filhos, senão morrerei.

[[v1-30-2]]

^<<v1-30-2,2>>^ Então, Jacó se irou contra Raquel e disse: Acaso, estou eu em lugar de Deus que ao teu ventre impediu frutificar?

[[v1-30-3]]

^<<v1-30-3,3>>^ Respondeu ela: Eis aqui Bila, minha serva; coabita com ela, para que dê à luz, e eu traga filhos ao meu colo, por meio dela.

[[v1-30-4]]

^<<v1-30-4,4>>^ Assim, lhe deu a Bila, sua serva, por mulher; e Jacó a possuiu.

[[v1-30-5]]

^<<v1-30-5,5>>^ Bila concebeu e deu à luz um filho a Jacó.

[[v1-30-6]]

^<<v1-30-6,6>>^ Então, disse Raquel: Deus me julgou, e também me ouviu a voz, e me deu um filho; portanto, lhe chamou Dã.

[[v1-30-7]]

^<<v1-30-7,7>>^ Concebeu outra vez Bila, serva de Raquel, e deu à luz o segundo filho a Jacó.

[[v1-30-8]]

^<<v1-30-8,8>>^ Disse Raquel: Com grandes lutas tenho competido com minha irmã e logrei prevalecer; chamou-lhe, pois, Naftali.

[[v1-30-9]]

^<<v1-30-9,9>>^ Vendo Lia que ela mesma cessara de conceber, tomou também a Zilpa, sua serva, e deu-a a Jacó, por mulher.

[[v1-30-10]]

^<<v1-30-10,10>>^ Zilpa, serva de Lia, deu a Jacó um filho.

[[v1-30-11]]

^<<v1-30-11,11>>^ Disse Lia: Afortunada! E lhe chamou Gade.

[[v1-30-12]]

^<<v1-30-12,12>>^ Depois, Zilpa, serva de Lia, deu o segundo filho a Jacó.

[[v1-30-13]]

^<<v1-30-13,13>>^ Então, disse Lia: É a minha felicidade! Porque as filhas me terão por venturosa; e lhe chamou Aser.

[[v1-30-14]]

^<<v1-30-14,14>>^ Foi Rúben nos dias da ceifa do trigo, e achou mandrágoras no campo, e trouxe-as a Lia, sua mãe. Então, disse Raquel a Lia: Dá-me das mandrágoras de teu filho.

[[v1-30-15]]

^<<v1-30-15,15>>^ Respondeu ela: Achas pouco o me teres levado o marido? Tomarás também as mandrágoras de meu filho? Disse Raquel: Ele te possuirá esta noite, a troco das mandrágoras de teu filho.

[[v1-30-16]]

^<<v1-30-16,16>>^ À tarde, vindo Jacó do campo, saiu-lhe ao encontro Lia e lhe disse: Esta noite me possuirás, pois eu te aluguei pelas mandrágoras de meu filho. E Jacó, naquela noite, coabitou com ela.

[[v1-30-17]]

^<<v1-30-17,17>>^ Ouviu Deus a Lia; ela concebeu e deu à luz o quinto filho.

[[v1-30-18]]

^<<v1-30-18,18>>^ Então, disse Lia: Deus me recompensou, porque dei a minha serva a meu marido; e chamou-lhe Issacar.

[[v1-30-19]]

^<<v1-30-19,19>>^ E Lia, tendo concebido outra vez, deu a Jacó o sexto filho.

[[v1-30-20]]

^<<v1-30-20,20>>^ E disse: Deus me concedeu excelente dote; desta vez permanecerá comigo meu marido, porque lhe dei seis filhos; e lhe chamou Zebulom.

[[v1-30-21]]

^<<v1-30-21,21>>^ Depois disto, deu à luz uma filha e lhe chamou Diná.

[[v1-30-22]]

^<<v1-30-22,22>>^ Lembrou-se Deus de Raquel, ouviu-a e a fez fecunda.

[[v1-30-23]]

^<<v1-30-23,23>>^ Ela concebeu, deu à luz um filho e disse: Deus me tirou o meu vexame.

[[v1-30-24]]

^<<v1-30-24,24>>^ E lhe chamou José, dizendo: Dê-me o SENHOR ainda outro filho.

[[v1-30-25]]

^<<v1-30-25,25>>^ Tendo Raquel dado à luz a José, disse Jacó a Labão: Permite-me que eu volte ao meu lugar e à minha terra.

[[v1-30-26]]

^<<v1-30-26,26>>^ Dá-me meus filhos e as mulheres, pelas quais eu te servi, e partirei; pois tu sabes quanto e de que maneira te servi.

[[v1-30-27]]

^<<v1-30-27,27>>^ Labão lhe respondeu: Ache eu mercê diante de ti; fica comigo. Tenho experimentado que o SENHOR me abençoou por amor de ti.

[[v1-30-28]]

^<<v1-30-28,28>>^ E disse ainda: Fixa o teu salário, que te pagarei.

[[v1-30-29]]

^<<v1-30-29,29>>^ Disse-lhe Jacó: Tu sabes como te venho servindo e como cuidei do teu gado.

[[v1-30-30]]

^<<v1-30-30,30>>^ Porque o pouco que tinhas antes da minha vinda foi aumentado grandemente; e o SENHOR te abençoou por meu trabalho. Agora, pois, quando hei de eu trabalhar também por minha casa?

[[v1-30-31]]

^<<v1-30-31,31>>^ Então, Labão lhe perguntou: Que te darei? Respondeu Jacó: Nada me darás; tornarei a apascentar e a guardar o teu rebanho, se me fizeres isto:

[[v1-30-32]]

^<<v1-30-32,32>>^ Passarei hoje por todo o teu rebanho, separando dele os salpicados e malhados, e todos os negros entre os cordeiros, e o que é malhado e salpicado entre as cabras; será isto o meu salário.

[[v1-30-33]]

^<<v1-30-33,33>>^ Assim, responderá por mim a minha justiça, no dia de amanhã, quando vieres ver o meu salário diante de ti; o que não for salpicado e malhado entre as cabras e negro entre as ovelhas, esse, se for achado comigo, será tido por furtado.

[[v1-30-34]]

^<<v1-30-34,34>>^ Disse Labão: Pois sim! Seja conforme a tua palavra.

[[v1-30-35]]

^<<v1-30-35,35>>^ Mas, naquele mesmo dia, separou Labão os bodes listados e malhados e todas as cabras salpicadas e malhadas, todos os que tinham alguma brancura e todos os negros entre os cordeiros; e os passou às mãos de seus filhos.

[[v1-30-36]]

^<<v1-30-36,36>>^ E pôs a distância de três dias de jornada entre si e Jacó; e Jacó apascentava o restante dos rebanhos de Labão.

[[v1-30-37]]

^<<v1-30-37,37>>^ Tomou, então, Jacó varas verdes de álamo, de aveleira e de plátano e lhes removeu a casca, em riscas abertas, deixando aparecer a brancura das varas,

[[v1-30-38]]

^<<v1-30-38,38>>^ as quais, assim escorchadas, pôs ele em frente do rebanho, nos canais de água e nos bebedouros, aonde os rebanhos vinham para dessedentar-se, e conceberam quando vinham a beber.

[[v1-30-39]]

^<<v1-30-39,39>>^ E concebia o rebanho diante das varas, e as ovelhas davam crias listadas, salpicadas e malhadas.

[[v1-30-40]]

^<<v1-30-40,40>>^ Então, separou Jacó os cordeiros e virou o rebanho para o lado dos listados e dos pretos nos rebanhos de Labão; e pôs o seu rebanho à parte e não o juntou com o rebanho de Labão.

[[v1-30-41]]

^<<v1-30-41,41>>^ E, todas as vezes que concebiam as ovelhas fortes, punha Jacó as varas à vista do rebanho nos canais de água, para que concebessem diante das varas.

[[v1-30-42]]

^<<v1-30-42,42>>^ Porém, quando o rebanho era fraco, não as punha; assim, as fracas eram de Labão, e as fortes, de Jacó.

[[v1-30-43]]

^<<v1-30-43,43>>^ E o homem se tornou mais e mais rico; teve muitos rebanhos, e servas, e servos, e camelos, e jumentos.

'''

xref:001-genesis/001-genesis-029.adoc#v1-29-0[&#60; Capítulo Anterior] | <<v1-30-0,Topo>> | xref:001-genesis/001-genesis-031.adoc#v1-31-0[Próximo Capítulo &#62;]