include::./index.adoc[]

[[v1-49-0]]
=== Gênesis, 49
// ara ?, ARA - Almeida Revista e Atualizada

[[v1-49-1]]

^<<v1-49-1,1>>^ Depois, chamou Jacó a seus filhos e disse: Ajuntai-vos, e eu vos farei saber o que vos há de acontecer nos dias vindouros:

[[v1-49-2]]

^<<v1-49-2,2>>^ Ajuntai-vos e ouvi, filhos de Jacó; ouvi a Israel, vosso pai.

[[v1-49-3]]

^<<v1-49-3,3>>^ Rúben, tu és meu primogênito, minha força e as primícias do meu vigor, o mais excelente em altivez e o mais excelente em poder.

[[v1-49-4]]

^<<v1-49-4,4>>^ Impetuoso como a água, não serás o mais excelente, porque subiste ao leito de teu pai e o profanaste; subiste à minha cama.

[[v1-49-5]]

^<<v1-49-5,5>>^ Simeão e Levi são irmãos; as suas espadas são instrumentos de violência.

[[v1-49-6]]

^<<v1-49-6,6>>^ No seu conselho, não entre minha alma; com o seu agrupamento, minha glória não se ajunte; porque no seu furor mataram homens, e na sua vontade perversa jarretaram touros.

[[v1-49-7]]

^<<v1-49-7,7>>^ Maldito seja o seu furor, pois era forte, e a sua ira, pois era dura; dividi-los-ei em Jacó e os espalharei em Israel.

[[v1-49-8]]

^<<v1-49-8,8>>^ Judá, teus irmãos te louvarão; a tua mão estará sobre a cerviz de teus inimigos; os filhos de teu pai se inclinarão a ti.

[[v1-49-9]]

^<<v1-49-9,9>>^ Judá é leãozinho; da presa subiste, filho meu. Encurva-se e deita-se como leão e como leoa; quem o despertará?

[[v1-49-10]]

^<<v1-49-10,10>>^ O cetro não se arredará de Judá, nem o bastão de entre seus pés, até que venha Siló; e a ele obedecerão os povos.

[[v1-49-11]]

^<<v1-49-11,11>>^ Ele amarrará o seu jumentinho à vide e o filho da sua jumenta, à videira mais excelente; lavará as suas vestes no vinho e a sua capa, em sangue de uvas.

[[v1-49-12]]

^<<v1-49-12,12>>^ Os seus olhos serão cintilantes de vinho, e os dentes, brancos de leite.

[[v1-49-13]]

^<<v1-49-13,13>>^ Zebulom habitará na praia dos mares e servirá de porto de navios, e o seu limite se estenderá até Sidom.

[[v1-49-14]]

^<<v1-49-14,14>>^ Issacar é jumento de fortes ossos, de repouso entre os rebanhos de ovelhas.

[[v1-49-15]]

^<<v1-49-15,15>>^ Viu que o repouso era bom e que a terra era deliciosa; baixou os ombros à carga e sujeitou-se ao trabalho servil.

[[v1-49-16]]

^<<v1-49-16,16>>^ Dã julgará o seu povo, como uma das tribos de Israel.

[[v1-49-17]]

^<<v1-49-17,17>>^ Dã será serpente junto ao caminho, uma víbora junto à vereda, que morde os talões do cavalo e faz cair o seu cavaleiro por detrás.

[[v1-49-18]]

^<<v1-49-18,18>>^ A tua salvação espero, ó SENHOR!

[[v1-49-19]]

^<<v1-49-19,19>>^ Gade, uma guerrilha o acometerá; mas ele a acometerá por sua retaguarda.

[[v1-49-20]]

^<<v1-49-20,20>>^ Aser, o seu pão será abundante e ele motivará delícias reais.

[[v1-49-21]]

^<<v1-49-21,21>>^ Naftali é uma gazela solta; ele profere palavras formosas.

[[v1-49-22]]

^<<v1-49-22,22>>^ José é um ramo frutífero, ramo frutífero junto à fonte; seus galhos se estendem sobre o muro.

[[v1-49-23]]

^<<v1-49-23,23>>^ Os flecheiros lhe dão amargura, atiram contra ele e o aborrecem.

[[v1-49-24]]

^<<v1-49-24,24>>^ O seu arco, porém, permanece firme, e os seus braços são feitos ativos pelas mãos do Poderoso de Jacó, sim, pelo Pastor e pela Pedra de Israel,

[[v1-49-25]]

^<<v1-49-25,25>>^ pelo Deus de teu pai, o qual te ajudará, e pelo Todo-Poderoso, o qual te abençoará com bênçãos dos altos céus, com bênçãos das profundezas, com bênçãos dos seios e da madre.

[[v1-49-26]]

^<<v1-49-26,26>>^ As bênçãos de teu pai excederão as bênçãos de meus pais até ao cimo dos montes eternos; estejam elas sobre a cabeça de José e sobre o alto da cabeça do que foi distinguido entre seus irmãos.

[[v1-49-27]]

^<<v1-49-27,27>>^ Benjamim é lobo que despedaça; pela manhã devora a presa e à tarde reparte o despojo.

[[v1-49-28]]

^<<v1-49-28,28>>^ São estas as doze tribos de Israel; e isto é o que lhes falou seu pai quando os abençoou; a cada um deles abençoou segundo a bênção que lhe cabia.

[[v1-49-29]]

^<<v1-49-29,29>>^ Depois, lhes ordenou, dizendo: Eu me reúno ao meu povo; sepultai-me, com meus pais, na caverna que está no campo de Efrom, o heteu,

[[v1-49-30]]

^<<v1-49-30,30>>^ na caverna que está no campo de Macpela, fronteiro a Manre, na terra de Canaã, a qual Abraão comprou de Efrom com aquele campo, em posse de sepultura.

[[v1-49-31]]

^<<v1-49-31,31>>^ Ali sepultaram Abraão e Sara, sua mulher; ali sepultaram Isaque e Rebeca, sua mulher; e ali sepultei Lia;

[[v1-49-32]]

^<<v1-49-32,32>>^ o campo e a caverna que nele está, comprados aos filhos de Hete.

[[v1-49-33]]

^<<v1-49-33,33>>^ Tendo Jacó acabado de dar determinações a seus filhos, recolheu os pés na cama, e expirou, e foi reunido ao seu povo.

'''

xref:001-genesis/001-genesis-048.adoc#v1-48-0[&#60; Capítulo Anterior] | <<v1-49-0,Topo>> | xref:001-genesis/001-genesis-050.adoc#v1-50-0[Próximo Capítulo &#62;]