include::./index.adoc[]

[[v51-1-0]]
=== Colossenses, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v51-1-1]]

^<<v51-1-1,1>>^ Paulo, apóstolo de Cristo Jesus, por vontade de Deus, e o irmão Timóteo,

[[v51-1-2]]

^<<v51-1-2,2>>^ aos santos e fiéis irmãos em Cristo que se encontram em Colossos, graça e paz a vós outros, da parte de Deus, nosso Pai.

[[v51-1-3]]

^<<v51-1-3,3>>^ Damos sempre graças a Deus, Pai de nosso Senhor Jesus Cristo, quando oramos por vós,

[[v51-1-4]]

^<<v51-1-4,4>>^ desde que ouvimos da vossa fé em Cristo Jesus e do amor que tendes para com todos os santos;

[[v51-1-5]]

^<<v51-1-5,5>>^ por causa da esperança que vos está preservada nos céus, da qual antes ouvistes pela palavra da verdade do evangelho,

[[v51-1-6]]

^<<v51-1-6,6>>^ que chegou até vós; como também, em todo o mundo, está produzindo fruto e crescendo, tal acontece entre vós, desde o dia em que ouvistes e entendestes a graça de Deus na verdade;

[[v51-1-7]]

^<<v51-1-7,7>>^ segundo fostes instruídos por Epafras, nosso amado conservo e, quanto a vós outros, fiel ministro de Cristo,

[[v51-1-8]]

^<<v51-1-8,8>>^ o qual também nos relatou do vosso amor no Espírito.

[[v51-1-9]]

^<<v51-1-9,9>>^ Por esta razão, também nós, desde o dia em que o ouvimos, não cessamos de orar por vós e de pedir que transbordeis de pleno conhecimento da sua vontade, em toda a sabedoria e entendimento espiritual;

[[v51-1-10]]

^<<v51-1-10,10>>^ a fim de viverdes de modo digno do Senhor, para o seu inteiro agrado, frutificando em toda boa obra e crescendo no pleno conhecimento de Deus;

[[v51-1-11]]

^<<v51-1-11,11>>^ sendo fortalecidos com todo o poder, segundo a força da sua glória, em toda a perseverança e longanimidade; com alegria,

[[v51-1-12]]

^<<v51-1-12,12>>^ dando graças ao Pai, que vos fez idôneos à parte que vos cabe da herança dos santos na luz.

[[v51-1-13]]

^<<v51-1-13,13>>^ Ele nos libertou do império das trevas e nos transportou para o reino do Filho do seu amor,

[[v51-1-14]]

^<<v51-1-14,14>>^ no qual temos a redenção, a remissão dos pecados.

[[v51-1-15]]

^<<v51-1-15,15>>^ Este é a imagem do Deus invisível, o primogênito de toda a criação;

[[v51-1-16]]

^<<v51-1-16,16>>^ pois, nele, foram criadas todas as coisas, nos céus e sobre a terra, as visíveis e as invisíveis, sejam tronos, sejam soberanias, quer principados, quer potestades. Tudo foi criado por meio dele e para ele.

[[v51-1-17]]

^<<v51-1-17,17>>^ Ele é antes de todas as coisas. Nele, tudo subsiste.

[[v51-1-18]]

^<<v51-1-18,18>>^ Ele é a cabeça do corpo, da igreja. Ele é o princípio, o primogênito de entre os mortos, para em todas as coisas ter a primazia,

[[v51-1-19]]

^<<v51-1-19,19>>^ porque aprouve a Deus que, nele, residisse toda a plenitude

[[v51-1-20]]

^<<v51-1-20,20>>^ e que, havendo feito a paz pelo sangue da sua cruz, por meio dele, reconciliasse consigo mesmo todas as coisas, quer sobre a terra, quer nos céus.

[[v51-1-21]]

^<<v51-1-21,21>>^ E a vós outros também que, outrora, éreis estranhos e inimigos no entendimento pelas vossas obras malignas,

[[v51-1-22]]

^<<v51-1-22,22>>^ agora, porém, vos reconciliou no corpo da sua carne, mediante a sua morte, para apresentar-vos perante ele santos, inculpáveis e irrepreensíveis,

[[v51-1-23]]

^<<v51-1-23,23>>^ se é que permaneceis na fé, alicerçados e firmes, não vos deixando afastar da esperança do evangelho que ouvistes e que foi pregado a toda criatura debaixo do céu, e do qual eu, Paulo, me tornei ministro.

[[v51-1-24]]

^<<v51-1-24,24>>^ Agora, me regozijo nos meus sofrimentos por vós; e preencho o que resta das aflições de Cristo, na minha carne, a favor do seu corpo, que é a igreja;

[[v51-1-25]]

^<<v51-1-25,25>>^ da qual me tornei ministro de acordo com a dispensação da parte de Deus, que me foi confiada a vosso favor, para dar pleno cumprimento à palavra de Deus:

[[v51-1-26]]

^<<v51-1-26,26>>^ o mistério que estivera oculto dos séculos e das gerações; agora, todavia, se manifestou aos seus santos;

[[v51-1-27]]

^<<v51-1-27,27>>^ aos quais Deus quis dar a conhecer qual seja a riqueza da glória deste mistério entre os gentios, isto é, Cristo em vós, a esperança da glória;

[[v51-1-28]]

^<<v51-1-28,28>>^ o qual nós anunciamos, advertindo a todo homem e ensinando a todo homem em toda a sabedoria, a fim de que apresentemos todo homem perfeito em Cristo;

[[v51-1-29]]

^<<v51-1-29,29>>^ para isso é que eu também me afadigo, esforçando-me o mais possível, segundo a sua eficácia que opera eficientemente em mim.

'''

xref:050-filipenses/050-filipenses-004.adoc#v50-4-0[&#60; Capítulo Anterior] | <<v51-1-0,Topo>> | xref:051-colossenses/051-colossenses-002.adoc#v51-2-0[Próximo Capítulo &#62;]