include::./index.adoc[]

[[v51-3-0]]
=== Colossenses, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v51-3-1]]

^<<v51-3-1,1>>^ Portanto, se fostes ressuscitados juntamente com Cristo, buscai as coisas lá do alto, onde Cristo vive, assentado à direita de Deus.

[[v51-3-2]]

^<<v51-3-2,2>>^ Pensai nas coisas lá do alto, não nas que são aqui da terra;

[[v51-3-3]]

^<<v51-3-3,3>>^ porque morrestes, e a vossa vida está oculta juntamente com Cristo, em Deus.

[[v51-3-4]]

^<<v51-3-4,4>>^ Quando Cristo, que é a nossa vida, se manifestar, então, vós também sereis manifestados com ele, em glória.

[[v51-3-5]]

^<<v51-3-5,5>>^ Fazei, pois, morrer a vossa natureza terrena: prostituição, impureza, paixão lasciva, desejo maligno e a avareza, que é idolatria;

[[v51-3-6]]

^<<v51-3-6,6>>^ por estas coisas é que vem a ira de Deus [sobre os filhos da desobediência].

[[v51-3-7]]

^<<v51-3-7,7>>^ Ora, nessas mesmas coisas andastes vós também, noutro tempo, quando vivíeis nelas.

[[v51-3-8]]

^<<v51-3-8,8>>^ Agora, porém, despojai-vos, igualmente, de tudo isto: ira, indignação, maldade, maledicência, linguagem obscena do vosso falar.

[[v51-3-9]]

^<<v51-3-9,9>>^ Não mintais uns aos outros, uma vez que vos despistes do velho homem com os seus feitos

[[v51-3-10]]

^<<v51-3-10,10>>^ e vos revestistes do novo homem que se refaz para o pleno conhecimento, segundo a imagem daquele que o criou;

[[v51-3-11]]

^<<v51-3-11,11>>^ no qual não pode haver grego nem judeu, circuncisão nem incircuncisão, bárbaro, cita, escravo, livre; porém Cristo é tudo em todos.

[[v51-3-12]]

^<<v51-3-12,12>>^ Revesti-vos, pois, como eleitos de Deus, santos e amados, de ternos afetos de misericórdia, de bondade, de humildade, de mansidão, de longanimidade.

[[v51-3-13]]

^<<v51-3-13,13>>^ Suportai-vos uns aos outros, perdoai-vos mutuamente, caso alguém tenha motivo de queixa contra outrem. Assim como o Senhor vos perdoou, assim também perdoai vós;

[[v51-3-14]]

^<<v51-3-14,14>>^ acima de tudo isto, porém, esteja o amor, que é o vínculo da perfeição.

[[v51-3-15]]

^<<v51-3-15,15>>^ Seja a paz de Cristo o árbitro em vosso coração, à qual, também, fostes chamados em um só corpo; e sede agradecidos.

[[v51-3-16]]

^<<v51-3-16,16>>^ Habite, ricamente, em vós a palavra de Cristo; instruí-vos e aconselhai-vos mutuamente em toda a sabedoria, louvando a Deus, com salmos, e hinos, e cânticos espirituais, com gratidão, em vosso coração.

[[v51-3-17]]

^<<v51-3-17,17>>^ E tudo o que fizerdes, seja em palavra, seja em ação, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai.

[[v51-3-18]]

^<<v51-3-18,18>>^ Esposas, sede submissas ao próprio marido, como convém no Senhor.

[[v51-3-19]]

^<<v51-3-19,19>>^ Maridos, amai vossa esposa e não a trateis com amargura.

[[v51-3-20]]

^<<v51-3-20,20>>^ Filhos, em tudo obedecei a vossos pais; pois fazê-lo é grato diante do Senhor.

[[v51-3-21]]

^<<v51-3-21,21>>^ Pais, não irriteis os vossos filhos, para que não fiquem desanimados.

[[v51-3-22]]

^<<v51-3-22,22>>^ Servos, obedecei em tudo ao vosso senhor segundo a carne, não servindo apenas sob vigilância, visando tão somente agradar homens, mas em singeleza de coração, temendo ao Senhor.

[[v51-3-23]]

^<<v51-3-23,23>>^ Tudo quanto fizerdes, fazei-o de todo o coração, como para o Senhor e não para homens,

[[v51-3-24]]

^<<v51-3-24,24>>^ cientes de que recebereis do Senhor a recompensa da herança. A Cristo, o Senhor, é que estais servindo;

[[v51-3-25]]

^<<v51-3-25,25>>^ pois aquele que faz injustiça receberá em troco a injustiça feita; e nisto não há acepção de pessoas.

'''

xref:051-colossenses/051-colossenses-002.adoc#v51-2-0[&#60; Capítulo Anterior] | <<v51-3-0,Topo>> | xref:051-colossenses/051-colossenses-004.adoc#v51-4-0[Próximo Capítulo &#62;]