include::./index.adoc[]

[[v51-2-0]]
=== Colossenses, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v51-2-1]]

^<<v51-2-1,1>>^ Gostaria, pois, que soubésseis quão grande luta venho mantendo por vós, pelos laodicenses e por quantos não me viram face a face;

[[v51-2-2]]

^<<v51-2-2,2>>^ para que o coração deles seja confortado e vinculado juntamente em amor, e eles tenham toda a riqueza da forte convicção do entendimento, para compreenderem plenamente o mistério de Deus, Cristo,

[[v51-2-3]]

^<<v51-2-3,3>>^ em quem todos os tesouros da sabedoria e do conhecimento estão ocultos.

[[v51-2-4]]

^<<v51-2-4,4>>^ Assim digo para que ninguém vos engane com raciocínios falazes.

[[v51-2-5]]

^<<v51-2-5,5>>^ Pois, embora ausente quanto ao corpo, contudo, em espírito, estou convosco, alegrando-me e verificando a vossa boa ordem e a firmeza da vossa fé em Cristo.

[[v51-2-6]]

^<<v51-2-6,6>>^ Ora, como recebestes Cristo Jesus, o Senhor, assim andai nele,

[[v51-2-7]]

^<<v51-2-7,7>>^ nele radicados, e edificados, e confirmados na fé, tal como fostes instruídos, crescendo em ações de graças.

[[v51-2-8]]

^<<v51-2-8,8>>^ Cuidado que ninguém vos venha a enredar com sua filosofia e vãs sutilezas, conforme a tradição dos homens, conforme os rudimentos do mundo e não segundo Cristo;

[[v51-2-9]]

^<<v51-2-9,9>>^ porquanto, nele, habita, corporalmente, toda a plenitude da Divindade.

[[v51-2-10]]

^<<v51-2-10,10>>^ Também, nele, estais aperfeiçoados. Ele é o cabeça de todo principado e potestade.

[[v51-2-11]]

^<<v51-2-11,11>>^ Nele, também fostes circuncidados, não por intermédio de mãos, mas no despojamento do corpo da carne, que é a circuncisão de Cristo,

[[v51-2-12]]

^<<v51-2-12,12>>^ tendo sido sepultados, juntamente com ele, no batismo, no qual igualmente fostes ressuscitados mediante a fé no poder de Deus que o ressuscitou dentre os mortos.

[[v51-2-13]]

^<<v51-2-13,13>>^ E a vós outros, que estáveis mortos pelas vossas transgressões e pela incircuncisão da vossa carne, vos deu vida juntamente com ele, perdoando todos os nossos delitos;

[[v51-2-14]]

^<<v51-2-14,14>>^ tendo cancelado o escrito de dívida, que era contra nós e que constava de ordenanças, o qual nos era prejudicial, removeu-o inteiramente, encravando-o na cruz;

[[v51-2-15]]

^<<v51-2-15,15>>^ e, despojando os principados e as potestades, publicamente os expôs ao desprezo, triunfando deles na cruz.

[[v51-2-16]]

^<<v51-2-16,16>>^ Ninguém, pois, vos julgue por causa de comida e bebida, ou dia de festa, ou lua nova, ou sábados,

[[v51-2-17]]

^<<v51-2-17,17>>^ porque tudo isso tem sido sombra das coisas que haviam de vir; porém o corpo é de Cristo.

[[v51-2-18]]

^<<v51-2-18,18>>^ Ninguém se faça árbitro contra vós outros, pretextando humildade e culto dos anjos, baseando-se em visões, enfatuado, sem motivo algum, na sua mente carnal,

[[v51-2-19]]

^<<v51-2-19,19>>^ e não retendo a cabeça, da qual todo o corpo, suprido e bem-vinculado por suas juntas e ligamentos, cresce o crescimento que procede de Deus.

[[v51-2-20]]

^<<v51-2-20,20>>^ Se morrestes com Cristo para os rudimentos do mundo, por que, como se vivêsseis no mundo, vos sujeitais a ordenanças:

[[v51-2-21]]

^<<v51-2-21,21>>^ não manuseies isto, não proves aquilo, não toques aquiloutro,

[[v51-2-22]]

^<<v51-2-22,22>>^ segundo os preceitos e doutrinas dos homens? Pois que todas estas coisas, com o uso, se destroem.

[[v51-2-23]]

^<<v51-2-23,23>>^ Tais coisas, com efeito, têm aparência de sabedoria, como culto de si mesmo, e de falsa humildade, e de rigor ascético; todavia, não têm valor algum contra a sensualidade.

'''

xref:051-colossenses/051-colossenses-001.adoc#v51-1-0[&#60; Capítulo Anterior] | <<v51-2-0,Topo>> | xref:051-colossenses/051-colossenses-003.adoc#v51-3-0[Próximo Capítulo &#62;]