include::./index.adoc[]

[[v51-4-0]]
=== Colossenses, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v51-4-1]]

^<<v51-4-1,1>>^ Senhores, tratai os servos com justiça e com equidade, certos de que também vós tendes Senhor no céu.

[[v51-4-2]]

^<<v51-4-2,2>>^ Perseverai na oração, vigiando com ações de graças.

[[v51-4-3]]

^<<v51-4-3,3>>^ Suplicai, ao mesmo tempo, também por nós, para que Deus nos abra porta à palavra, a fim de falarmos do mistério de Cristo, pelo qual também estou algemado;

[[v51-4-4]]

^<<v51-4-4,4>>^ para que eu o manifeste, como devo fazer.

[[v51-4-5]]

^<<v51-4-5,5>>^ Portai-vos com sabedoria para com os que são de fora; aproveitai as oportunidades.

[[v51-4-6]]

^<<v51-4-6,6>>^ A vossa palavra seja sempre agradável, temperada com sal, para saberdes como deveis responder a cada um.

[[v51-4-7]]

^<<v51-4-7,7>>^ Quanto à minha situação, Tíquico, irmão amado, e fiel ministro, e conservo no Senhor, de tudo vos informará.

[[v51-4-8]]

^<<v51-4-8,8>>^ Eu vo-lo envio com o expresso propósito de vos dar conhecimento da nossa situação e de alentar o vosso coração.

[[v51-4-9]]

^<<v51-4-9,9>>^ Em sua companhia, vos envio Onésimo, o fiel e amado irmão, que é do vosso meio. Eles vos farão saber tudo o que por aqui ocorre.

[[v51-4-10]]

^<<v51-4-10,10>>^ Saúda-vos Aristarco, prisioneiro comigo, e Marcos, primo de Barnabé (sobre quem recebestes instruções; se ele for ter convosco, acolhei-o),

[[v51-4-11]]

^<<v51-4-11,11>>^ e Jesus, conhecido por Justo, os quais são os únicos da circuncisão que cooperam pessoalmente comigo pelo reino de Deus. Eles têm sido o meu lenitivo.

[[v51-4-12]]

^<<v51-4-12,12>>^ Saúda-vos Epafras, que é dentre vós, servo de Cristo Jesus, o qual se esforça sobremaneira, continuamente, por vós nas orações, para que vos conserveis perfeitos e plenamente convictos em toda a vontade de Deus.

[[v51-4-13]]

^<<v51-4-13,13>>^ E dele dou testemunho de que muito se preocupa por vós, pelos de Laodiceia e pelos de Hierápolis.

[[v51-4-14]]

^<<v51-4-14,14>>^ Saúda-vos Lucas, o médico amado, e também Demas.

[[v51-4-15]]

^<<v51-4-15,15>>^ Saudai os irmãos de Laodiceia, e Ninfa, e à igreja que ela hospeda em sua casa.

[[v51-4-16]]

^<<v51-4-16,16>>^ E, uma vez lida esta epístola perante vós, providenciai por que seja também lida na igreja dos laodicenses; e a dos de Laodiceia, lede-a igualmente perante vós.

[[v51-4-17]]

^<<v51-4-17,17>>^ Também dizei a Arquipo: atenta para o ministério que recebeste no Senhor, para o cumprires.

[[v51-4-18]]

^<<v51-4-18,18>>^ A saudação é de próprio punho: Paulo. Lembrai-vos das minhas algemas. A graça seja convosco.

'''

xref:051-colossenses/051-colossenses-003.adoc#v51-3-0[&#60; Capítulo Anterior] | <<v51-4-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[Próximo Capítulo &#62;]