include::./index.adoc[]

[[v35-1-0]]
=== Habacuque, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v35-1-1]]

^<<v35-1-1,1>>^ Sentença revelada ao profeta Habacuque.

[[v35-1-2]]

^<<v35-1-2,2>>^ Até quando, SENHOR, clamarei eu, e tu não me escutarás? Gritar-te-ei: Violência! E não salvarás?

[[v35-1-3]]

^<<v35-1-3,3>>^ Por que me mostras a iniquidade e me fazes ver a opressão? Pois a destruição e a violência estão diante de mim; há contendas, e o litígio se suscita.

[[v35-1-4]]

^<<v35-1-4,4>>^ Por esta causa, a lei se afrouxa, e a justiça nunca se manifesta, porque o perverso cerca o justo, a justiça é torcida.

[[v35-1-5]]

^<<v35-1-5,5>>^ Vede entre as nações, olhai, maravilhai-vos e desvanecei, porque realizo, em vossos dias, obra tal, que vós não crereis, quando vos for contada.

[[v35-1-6]]

^<<v35-1-6,6>>^ Pois eis que suscito os caldeus, nação amarga e impetuosa, que marcham pela largura da terra, para apoderar-se de moradas que não são suas.

[[v35-1-7]]

^<<v35-1-7,7>>^ Eles são pavorosos e terríveis, e criam eles mesmos o seu direito e a sua dignidade.

[[v35-1-8]]

^<<v35-1-8,8>>^ Os seus cavalos são mais ligeiros do que os leopardos, mais ferozes do que os lobos ao anoitecer são os seus cavaleiros que se espalham por toda parte; sim, os seus cavaleiros chegam de longe, voam como águia que se precipita a devorar.

[[v35-1-9]]

^<<v35-1-9,9>>^ Eles todos vêm para fazer violência; o seu rosto suspira por seguir avante; eles reúnem os cativos como areia.

[[v35-1-10]]

^<<v35-1-10,10>>^ Eles escarnecem dos reis; os príncipes são objeto do seu riso; riem-se de todas as fortalezas, porque, amontoando terra, as tomam.

[[v35-1-11]]

^<<v35-1-11,11>>^ Então, passam como passa o vento e seguem; fazem-se culpados estes cujo poder é o seu deus.

[[v35-1-12]]

^<<v35-1-12,12>>^ Não és tu desde a eternidade, ó SENHOR, meu Deus, ó meu Santo? Não morreremos. Ó SENHOR, para executar juízo, puseste aquele povo; tu, ó Rocha, o fundaste para servir de disciplina.

[[v35-1-13]]

^<<v35-1-13,13>>^ Tu és tão puro de olhos, que não podes ver o mal e a opressão não podes contemplar; por que, pois, toleras os que procedem perfidamente e te calas quando o perverso devora aquele que é mais justo do que ele?

[[v35-1-14]]

^<<v35-1-14,14>>^ Por que fazes os homens como os peixes do mar, como os répteis, que não têm quem os governe?

[[v35-1-15]]

^<<v35-1-15,15>>^ A todos levanta o inimigo com o anzol, pesca-os de arrastão e os ajunta na sua rede varredoura; por isso, ele se alegra e se regozija.

[[v35-1-16]]

^<<v35-1-16,16>>^ Por isso, oferece sacrifício à sua rede e queima incenso à sua varredoura; porque por elas enriqueceu a sua porção, e tem gordura a sua comida.

[[v35-1-17]]

^<<v35-1-17,17>>^ Acaso, continuará, por isso, esvaziando a sua rede e matando sem piedade os povos?

'''

xref:034-naum/034-naum-003.adoc#v34-3-0[&#60; Capítulo Anterior] | <<v35-1-0,Topo>> | xref:035-habacuque/035-habacuque-002.adoc#v35-2-0[Próximo Capítulo &#62;]