include::./index.adoc[]

[[v33-4-0]]
=== Miquéias, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v33-4-1]]

^<<v33-4-1,1>>^ Mas, nos últimos dias, acontecerá que o monte da Casa do SENHOR será estabelecido no cimo dos montes e se elevará sobre os outeiros, e para ele afluirão os povos.

[[v33-4-2]]

^<<v33-4-2,2>>^ Irão muitas nações e dirão: Vinde, e subamos ao monte do SENHOR e à casa do Deus de Jacó, para que nos ensine os seus caminhos, e andemos pelas suas veredas; porque de Sião procederá a lei, e a palavra do SENHOR, de Jerusalém.

[[v33-4-3]]

^<<v33-4-3,3>>^ Ele julgará entre muitos povos e corrigirá nações poderosas e longínquas; estes converterão as suas espadas em relhas de arados e suas lanças, em podadeiras; uma nação não levantará a espada contra outra nação, nem aprenderão mais a guerra.

[[v33-4-4]]

^<<v33-4-4,4>>^ Mas assentar-se-á cada um debaixo da sua videira e debaixo da sua figueira, e não haverá quem os espante, porque a boca do SENHOR dos Exércitos o disse.

[[v33-4-5]]

^<<v33-4-5,5>>^ Porque todos os povos andam, cada um em nome do seu deus; mas, quanto a nós, andaremos em o nome do SENHOR, nosso Deus, para todo o sempre.

[[v33-4-6]]

^<<v33-4-6,6>>^ Naquele dia, diz o SENHOR, congregarei os que coxeiam e recolherei os que foram expulsos e os que eu afligira.

[[v33-4-7]]

^<<v33-4-7,7>>^ Dos que coxeiam farei a parte restante e dos que foram arrojados para longe, uma poderosa nação; e o SENHOR reinará sobre eles no monte Sião, desde agora e para sempre.

[[v33-4-8]]

^<<v33-4-8,8>>^ A ti, ó torre do rebanho, monte da filha de Sião, a ti virá; sim, virá o primeiro domínio, o reino da filha de Jerusalém.

[[v33-4-9]]

^<<v33-4-9,9>>^ Agora, por que tamanho grito? Não há rei em ti? Pereceu o teu conselheiro? Apoderou-se de ti a dor como da que está para dar à luz?

[[v33-4-10]]

^<<v33-4-10,10>>^ Sofre dores e esforça-te, ó filha de Sião, como a que está para dar à luz, porque, agora, sairás da cidade, e habitarás no campo, e virás até à Babilônia; ali, porém, serás libertada; ali, te remirá o SENHOR das mãos dos teus inimigos.

[[v33-4-11]]

^<<v33-4-11,11>>^ Acham-se, agora, congregadas muitas nações contra ti, que dizem: Seja profanada, e vejam os nossos olhos o seu desejo sobre Sião.

[[v33-4-12]]

^<<v33-4-12,12>>^ Mas não sabem os pensamentos do SENHOR, nem lhe entendem o plano que as ajuntou como feixes na eira.

[[v33-4-13]]

^<<v33-4-13,13>>^ Levanta-te e debulha, ó filha de Sião, porque farei de ferro o teu chifre e de bronze, as tuas unhas; e esmiuçarás a muitos povos, e o seu ganho será dedicado ao SENHOR, e os seus bens, ao Senhor de toda a terra.

'''

xref:033-miqueias/033-miqueias-003.adoc#v33-3-0[&#60; Capítulo Anterior] | <<v33-4-0,Topo>> | xref:033-miqueias/033-miqueias-005.adoc#v33-5-0[Próximo Capítulo &#62;]