include::./index.adoc[]

[[v33-6-0]]
=== Miquéias, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v33-6-1]]

^<<v33-6-1,1>>^ Ouvi, agora, o que diz o SENHOR: Levanta-te, defende a tua causa perante os montes, e ouçam os outeiros a tua voz.

[[v33-6-2]]

^<<v33-6-2,2>>^ Ouvi, montes, a controvérsia do SENHOR, e vós, duráveis fundamentos da terra, porque o SENHOR tem controvérsia com o seu povo e com Israel entrará em juízo.

[[v33-6-3]]

^<<v33-6-3,3>>^ Povo meu, que te tenho feito? E com que te enfadei? Responde-me!

[[v33-6-4]]

^<<v33-6-4,4>>^ Pois te fiz sair da terra do Egito e da casa da servidão te remi; e enviei adiante de ti Moisés, Arão e Miriã.

[[v33-6-5]]

^<<v33-6-5,5>>^ Povo meu, lembra-te, agora, do que maquinou Balaque, rei de Moabe, e do que lhe respondeu Balaão, filho de Beor, e do que aconteceu desde Sitim até Gilgal, para que conheças os atos de justiça do SENHOR.

[[v33-6-6]]

^<<v33-6-6,6>>^ Com que me apresentarei ao SENHOR e me inclinarei ante o Deus excelso? Virei perante ele com holocaustos, com bezerros de um ano?

[[v33-6-7]]

^<<v33-6-7,7>>^ Agradar-se-á o SENHOR de milhares de carneiros, de dez mil ribeiros de azeite? Darei o meu primogênito pela minha transgressão, o fruto do meu corpo, pelo pecado da minha alma?

[[v33-6-8]]

^<<v33-6-8,8>>^ Ele te declarou, ó homem, o que é bom e que é o que o SENHOR pede de ti: que pratiques a justiça, e ames a misericórdia, e andes humildemente com o teu Deus.

[[v33-6-9]]

^<<v33-6-9,9>>^ A voz do SENHOR clama à cidade (e é verdadeira sabedoria temer-lhe o nome): Ouvi, ó tribos, aquele que a cita.

[[v33-6-10]]

^<<v33-6-10,10>>^ Ainda há, na casa do ímpio, os tesouros da impiedade e o detestável efa minguado?

[[v33-6-11]]

^<<v33-6-11,11>>^ Poderei eu inocentar balanças falsas e bolsas de pesos enganosos?

[[v33-6-12]]

^<<v33-6-12,12>>^ Porque os ricos da cidade estão cheios de violência, e os seus habitantes falam mentiras, e a língua deles é enganosa na sua boca.

[[v33-6-13]]

^<<v33-6-13,13>>^ Assim, também passarei eu a ferir-te e te deixarei desolada por causa dos teus pecados.

[[v33-6-14]]

^<<v33-6-14,14>>^ Comerás e não te fartarás; a fome estará nas tuas entranhas; removerás os teus bens, mas não os livrarás; e aquilo que livrares, eu o entregarei à espada.

[[v33-6-15]]

^<<v33-6-15,15>>^ Semearás; contudo, não segarás; pisarás a azeitona, porém não te ungirás com azeite; pisarás a vindima; no entanto, não lhe beberás o vinho,

[[v33-6-16]]

^<<v33-6-16,16>>^ porque observaste os estatutos de Onri e todas as obras da casa de Acabe e andaste nos conselhos deles. Por isso, eu farei de ti uma desolação e dos habitantes da tua cidade, um alvo de vaias; assim, trareis sobre vós o opróbrio dos povos.

'''

xref:033-miqueias/033-miqueias-005.adoc#v33-5-0[&#60; Capítulo Anterior] | <<v33-6-0,Topo>> | xref:033-miqueias/033-miqueias-007.adoc#v33-7-0[Próximo Capítulo &#62;]