include::./index.adoc[]

[[v33-7-0]]
=== Miquéias, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v33-7-1]]

^<<v33-7-1,1>>^ Ai de mim! Porque estou como quando são colhidas as frutas do verão, como os rabiscos da vindima: não há cacho de uvas para chupar, nem figos temporãos que a minha alma deseja.

[[v33-7-2]]

^<<v33-7-2,2>>^ Pereceu da terra o piedoso, e não há entre os homens um que seja reto; todos espreitam para derramarem sangue; cada um caça a seu irmão com rede.

[[v33-7-3]]

^<<v33-7-3,3>>^ As suas mãos estão sobre o mal e o fazem diligentemente; o príncipe exige condenação, o juiz aceita suborno, o grande fala dos maus desejos de sua alma, e, assim, todos eles juntamente urdem a trama.

[[v33-7-4]]

^<<v33-7-4,4>>^ O melhor deles é como um espinheiro; o mais reto é pior do que uma sebe de espinhos. É chegado o dia anunciado por tuas sentinelas, o dia do teu castigo; aí está a confusão deles.

[[v33-7-5]]

^<<v33-7-5,5>>^ Não creiais no amigo, nem confieis no companheiro. Guarda a porta de tua boca àquela que reclina sobre o teu peito.

[[v33-7-6]]

^<<v33-7-6,6>>^ Porque o filho despreza o pai, a filha se levanta contra a mãe, a nora, contra a sogra; os inimigos do homem são os da sua própria casa.

[[v33-7-7]]

^<<v33-7-7,7>>^ Eu, porém, olharei para o SENHOR e esperarei no Deus da minha salvação; o meu Deus me ouvirá.

[[v33-7-8]]

^<<v33-7-8,8>>^ Ó inimiga minha, não te alegres a meu respeito; ainda que eu tenha caído, levantar-me-ei; se morar nas trevas, o SENHOR será a minha luz.

[[v33-7-9]]

^<<v33-7-9,9>>^ Sofrerei a ira do SENHOR, porque pequei contra ele, até que julgue a minha causa e execute o meu direito; ele me tirará para a luz, e eu verei a sua justiça.

[[v33-7-10]]

^<<v33-7-10,10>>^ A minha inimiga verá isso, e a ela cobrirá a vergonha, a ela que me diz: Onde está o SENHOR, teu Deus? Os meus olhos a contemplarão; agora, será pisada aos pés como a lama das ruas.

[[v33-7-11]]

^<<v33-7-11,11>>^ No dia da reedificação dos teus muros, nesse dia, serão os teus limites removidos para mais longe.

[[v33-7-12]]

^<<v33-7-12,12>>^ Nesse dia, virão a ti, desde a Assíria até às cidades do Egito, e do Egito até ao rio Eufrates, e do mar até ao mar, e da montanha até à montanha.

[[v33-7-13]]

^<<v33-7-13,13>>^ Todavia, a terra será posta em desolação, por causa dos seus moradores, por causa do fruto das suas obras.

[[v33-7-14]]

^<<v33-7-14,14>>^ Apascenta o teu povo com o teu bordão, o rebanho da tua herança, que mora a sós no bosque, no meio da terra fértil; apascentem-se em Basã e Gileade, como nos dias de outrora.

[[v33-7-15]]

^<<v33-7-15,15>>^ Eu lhe mostrarei maravilhas, como nos dias da tua saída da terra do Egito.

[[v33-7-16]]

^<<v33-7-16,16>>^ As nações verão isso e se envergonharão de todo o seu poder; porão a mão sobre a boca, e os seus ouvidos ficarão surdos.

[[v33-7-17]]

^<<v33-7-17,17>>^ Lamberão o pó como serpentes; como répteis da terra, tremendo, sairão dos seus esconderijos e, tremendo, virão ao SENHOR, nosso Deus; e terão medo de ti.

[[v33-7-18]]

^<<v33-7-18,18>>^ Quem, ó Deus, é semelhante a ti, que perdoas a iniquidade e te esqueces da transgressão do restante da tua herança? O SENHOR não retém a sua ira para sempre, porque tem prazer na misericórdia.

[[v33-7-19]]

^<<v33-7-19,19>>^ Tornará a ter compaixão de nós; pisará aos pés as nossas iniquidades e lançará todos os nossos pecados nas profundezas do mar.

[[v33-7-20]]

^<<v33-7-20,20>>^ Mostrarás a Jacó a fidelidade e a Abraão, a misericórdia, as quais juraste a nossos pais, desde os dias antigos.

'''

xref:033-miqueias/033-miqueias-006.adoc#v33-6-0[&#60; Capítulo Anterior] | <<v33-7-0,Topo>> | xref:034-naum/034-naum-001.adoc#v34-1-0[Próximo Capítulo &#62;]