include::./index.adoc[]

[[v33-3-0]]
=== Miquéias, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v33-3-1]]

^<<v33-3-1,1>>^ Disse eu: Ouvi, agora, vós, cabeças de Jacó, e vós, chefes da casa de Israel: Não é a vós outros que pertence saber o juízo?

[[v33-3-2]]

^<<v33-3-2,2>>^ Os que aborreceis o bem e amais o mal; e deles arrancais a pele e a carne de cima dos seus ossos;

[[v33-3-3]]

^<<v33-3-3,3>>^ que comeis a carne do meu povo, e lhes arrancais a pele, e lhes esmiuçais os ossos, e os repartis como para a panela e como carne no meio do caldeirão?

[[v33-3-4]]

^<<v33-3-4,4>>^ Então, chamarão ao SENHOR, mas não os ouvirá; antes, esconderá deles a sua face, naquele tempo, visto que eles fizeram mal nas suas obras.

[[v33-3-5]]

^<<v33-3-5,5>>^ Assim diz o SENHOR acerca dos profetas que fazem errar o meu povo e que clamam: Paz, quando têm o que mastigar, mas apregoam guerra santa contra aqueles que nada lhes metem na boca.

[[v33-3-6]]

^<<v33-3-6,6>>^ Portanto, se vos fará noite sem visão, e tereis treva sem adivinhação; pôr-se-á o sol sobre os profetas, e sobre eles se enegrecerá o dia.

[[v33-3-7]]

^<<v33-3-7,7>>^ Os videntes se envergonharão, e os adivinhadores se confundirão; sim, todos eles cobrirão o seu bigode, porque não há resposta de Deus.

[[v33-3-8]]

^<<v33-3-8,8>>^ Eu, porém, estou cheio do poder do Espírito do SENHOR, cheio de juízo e de força, para declarar a Jacó a sua transgressão e a Israel, o seu pecado.

[[v33-3-9]]

^<<v33-3-9,9>>^ Ouvi, agora, isto, vós, cabeças de Jacó, e vós, chefes da casa de Israel, que abominais o juízo, e perverteis tudo o que é direito,

[[v33-3-10]]

^<<v33-3-10,10>>^ e edificais a Sião com sangue e a Jerusalém, com perversidade.

[[v33-3-11]]

^<<v33-3-11,11>>^ Os seus cabeças dão as sentenças por suborno, os seus sacerdotes ensinam por interesse, e os seus profetas adivinham por dinheiro; e ainda se encostam ao SENHOR, dizendo: Não está o SENHOR no meio de nós? Nenhum mal nos sobrevirá.

[[v33-3-12]]

^<<v33-3-12,12>>^ Portanto, por causa de vós, Sião será lavrada como um campo, e Jerusalém se tornará em montões de ruínas, e o monte do templo, numa colina coberta de mato.

'''

xref:033-miqueias/033-miqueias-002.adoc#v33-2-0[&#60; Capítulo Anterior] | <<v33-3-0,Topo>> | xref:033-miqueias/033-miqueias-004.adoc#v33-4-0[Próximo Capítulo &#62;]