include::./index.adoc[]

[[v33-2-0]]
=== Miquéias, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v33-2-1]]

^<<v33-2-1,1>>^ Ai daqueles que, no seu leito, imaginam a iniquidade e maquinam o mal! À luz da alva, o praticam, porque o poder está em suas mãos.

[[v33-2-2]]

^<<v33-2-2,2>>^ Se cobiçam campos, os arrebatam; se casas, as tomam; assim, fazem violência a um homem e à sua casa, a uma pessoa e à sua herança.

[[v33-2-3]]

^<<v33-2-3,3>>^ Portanto, assim diz o SENHOR: Eis que projeto mal contra esta família, do qual não tirareis a vossa cerviz; e não andareis altivamente, porque o tempo será mau.

[[v33-2-4]]

^<<v33-2-4,4>>^ Naquele dia, se criará contra vós outros um provérbio, se levantará pranto lastimoso e se dirá: Estamos inteiramente desolados! A porção do meu povo, Deus a troca! Como me despoja! Reparte os nossos campos aos rebeldes!

[[v33-2-5]]

^<<v33-2-5,5>>^ Portanto, não terás, na congregação do SENHOR, quem, pela sorte, lançando o cordel, meça possessões.

[[v33-2-6]]

^<<v33-2-6,6>>^ Não babujeis, dizem eles. Não babujeis tais coisas, porque a desgraça não cairá sobre nós.

[[v33-2-7]]

^<<v33-2-7,7>>^ Tais coisas anunciadas não alcançarão a casa de Jacó. Está irritado o Espírito do SENHOR? São estas as suas obras? Sim, as minhas palavras fazem o bem ao que anda retamente;

[[v33-2-8]]

^<<v33-2-8,8>>^ mas, há pouco, se levantou o meu povo como inimigo; além da roupa, roubais a capa àqueles que passam seguros, sem pensar em guerra.

[[v33-2-9]]

^<<v33-2-9,9>>^ Lançais fora as mulheres de meu povo do seu lar querido; dos filhinhos delas tirais a minha glória, para sempre.

[[v33-2-10]]

^<<v33-2-10,10>>^ Levantai-vos e ide-vos embora, porque não é lugar aqui de descanso; ide-vos por causa da imundícia que destrói, sim, que destrói dolorosamente.

[[v33-2-11]]

^<<v33-2-11,11>>^ Se houver alguém que, seguindo o vento da falsidade, mentindo, diga: Eu te profetizarei do vinho e da bebida forte, será este tal o profeta deste povo.

[[v33-2-12]]

^<<v33-2-12,12>>^ Certamente, te ajuntarei todo, ó Jacó; certamente, congregarei o restante de Israel; pô-los-ei todos juntos, como ovelhas no aprisco, como rebanho no meio do seu pasto; farão grande ruído, por causa da multidão dos homens.

[[v33-2-13]]

^<<v33-2-13,13>>^ Subirá diante deles o que abre caminho; eles romperão, entrarão pela porta e sairão por ela; e o seu Rei irá adiante deles; sim, o SENHOR, à sua frente.

'''

xref:033-miqueias/033-miqueias-001.adoc#v33-1-0[&#60; Capítulo Anterior] | <<v33-2-0,Topo>> | xref:033-miqueias/033-miqueias-003.adoc#v33-3-0[Próximo Capítulo &#62;]