include::./index.adoc[]

[[v49-5-0]]
=== Efésios, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v49-5-1]]

^<<v49-5-1,1>>^ Sede, pois, imitadores de Deus, como filhos amados;

[[v49-5-2]]

^<<v49-5-2,2>>^ e andai em amor, como também Cristo nos amou e se entregou a si mesmo por nós, como oferta e sacrifício a Deus, em aroma suave.

[[v49-5-3]]

^<<v49-5-3,3>>^ Mas a impudicícia e toda sorte de impurezas ou cobiça nem sequer se nomeiem entre vós, como convém a santos;

[[v49-5-4]]

^<<v49-5-4,4>>^ nem conversação torpe, nem palavras vãs ou chocarrices, coisas essas inconvenientes; antes, pelo contrário, ações de graças.

[[v49-5-5]]

^<<v49-5-5,5>>^ Sabei, pois, isto: nenhum incontinente, ou impuro, ou avarento, que é idólatra, tem herança no reino de Cristo e de Deus.

[[v49-5-6]]

^<<v49-5-6,6>>^ Ninguém vos engane com palavras vãs; porque, por essas coisas, vem a ira de Deus sobre os filhos da desobediência.

[[v49-5-7]]

^<<v49-5-7,7>>^ Portanto, não sejais participantes com eles.

[[v49-5-8]]

^<<v49-5-8,8>>^ Pois, outrora, éreis trevas, porém, agora, sois luz no Senhor; andai como filhos da luz

[[v49-5-9]]

^<<v49-5-9,9>>^ (porque o fruto da luz consiste em toda bondade, e justiça, e verdade),

[[v49-5-10]]

^<<v49-5-10,10>>^ provando sempre o que é agradável ao Senhor.

[[v49-5-11]]

^<<v49-5-11,11>>^ E não sejais cúmplices nas obras infrutíferas das trevas; antes, porém, reprovai-as.

[[v49-5-12]]

^<<v49-5-12,12>>^ Porque o que eles fazem em oculto, o só referir é vergonha.

[[v49-5-13]]

^<<v49-5-13,13>>^ Mas todas as coisas, quando reprovadas pela luz, se tornam manifestas; porque tudo que se manifesta é luz.

[[v49-5-14]]

^<<v49-5-14,14>>^ Pelo que diz: Desperta, ó tu que dormes, levanta-te de entre os mortos, e Cristo te iluminará.

[[v49-5-15]]

^<<v49-5-15,15>>^ Portanto, vede prudentemente como andais, não como néscios, e sim como sábios,

[[v49-5-16]]

^<<v49-5-16,16>>^ remindo o tempo, porque os dias são maus.

[[v49-5-17]]

^<<v49-5-17,17>>^ Por esta razão, não vos torneis insensatos, mas procurai compreender qual a vontade do Senhor.

[[v49-5-18]]

^<<v49-5-18,18>>^ E não vos embriagueis com vinho, no qual há dissolução, mas enchei-vos do Espírito,

[[v49-5-19]]

^<<v49-5-19,19>>^ falando entre vós com salmos, entoando e louvando de coração ao Senhor com hinos e cânticos espirituais,

[[v49-5-20]]

^<<v49-5-20,20>>^ dando sempre graças por tudo a nosso Deus e Pai, em nome de nosso Senhor Jesus Cristo,

[[v49-5-21]]

^<<v49-5-21,21>>^ sujeitando-vos uns aos outros no temor de Cristo.

[[v49-5-22]]

^<<v49-5-22,22>>^ As mulheres sejam submissas ao seu próprio marido, como ao Senhor;

[[v49-5-23]]

^<<v49-5-23,23>>^ porque o marido é o cabeça da mulher, como também Cristo é o cabeça da igreja, sendo este mesmo o salvador do corpo.

[[v49-5-24]]

^<<v49-5-24,24>>^ Como, porém, a igreja está sujeita a Cristo, assim também as mulheres sejam em tudo submissas ao seu marido.

[[v49-5-25]]

^<<v49-5-25,25>>^ Maridos, amai vossa mulher, como também Cristo amou a igreja e a si mesmo se entregou por ela,

[[v49-5-26]]

^<<v49-5-26,26>>^ para que a santificasse, tendo-a purificado por meio da lavagem de água pela palavra,

[[v49-5-27]]

^<<v49-5-27,27>>^ para a apresentar a si mesmo igreja gloriosa, sem mácula, nem ruga, nem coisa semelhante, porém santa e sem defeito.

[[v49-5-28]]

^<<v49-5-28,28>>^ Assim também os maridos devem amar a sua mulher como ao próprio corpo. Quem ama a esposa a si mesmo se ama.

[[v49-5-29]]

^<<v49-5-29,29>>^ Porque ninguém jamais odiou a própria carne; antes, a alimenta e dela cuida, como também Cristo o faz com a igreja;

[[v49-5-30]]

^<<v49-5-30,30>>^ porque somos membros do seu corpo.

[[v49-5-31]]

^<<v49-5-31,31>>^ Eis por que deixará o homem a seu pai e a sua mãe e se unirá à sua mulher, e se tornarão os dois uma só carne.

[[v49-5-32]]

^<<v49-5-32,32>>^ Grande é este mistério, mas eu me refiro a Cristo e à igreja.

[[v49-5-33]]

^<<v49-5-33,33>>^ Não obstante, vós, cada um de per si também ame a própria esposa como a si mesmo, e a esposa respeite ao marido.

'''

xref:049-efesios/049-efesios-004.adoc#v49-4-0[&#60; Capítulo Anterior] | <<v49-5-0,Topo>> | xref:049-efesios/049-efesios-006.adoc#v49-6-0[Próximo Capítulo &#62;]