include::./index.adoc[]

[[v49-4-0]]
=== Efésios, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v49-4-1]]

^<<v49-4-1,1>>^ Rogo-vos, pois, eu, o prisioneiro no Senhor, que andeis de modo digno da vocação a que fostes chamados,

[[v49-4-2]]

^<<v49-4-2,2>>^ com toda a humildade e mansidão, com longanimidade, suportando-vos uns aos outros em amor,

[[v49-4-3]]

^<<v49-4-3,3>>^ esforçando-vos diligentemente por preservar a unidade do Espírito no vínculo da paz;

[[v49-4-4]]

^<<v49-4-4,4>>^ há somente um corpo e um Espírito, como também fostes chamados numa só esperança da vossa vocação;

[[v49-4-5]]

^<<v49-4-5,5>>^ há um só Senhor, uma só fé, um só batismo;

[[v49-4-6]]

^<<v49-4-6,6>>^ um só Deus e Pai de todos, o qual é sobre todos, age por meio de todos e está em todos.

[[v49-4-7]]

^<<v49-4-7,7>>^ E a graça foi concedida a cada um de nós segundo a proporção do dom de Cristo.

[[v49-4-8]]

^<<v49-4-8,8>>^ Por isso, diz: Quando ele subiu às alturas, levou cativo o cativeiro e concedeu dons aos homens.

[[v49-4-9]]

^<<v49-4-9,9>>^ Ora, que quer dizer subiu, senão que também havia descido até às regiões inferiores da terra?

[[v49-4-10]]

^<<v49-4-10,10>>^ Aquele que desceu é também o mesmo que subiu acima de todos os céus, para encher todas as coisas.

[[v49-4-11]]

^<<v49-4-11,11>>^ E ele mesmo concedeu uns para apóstolos, outros para profetas, outros para evangelistas e outros para pastores e mestres,

[[v49-4-12]]

^<<v49-4-12,12>>^ com vistas ao aperfeiçoamento dos santos para o desempenho do seu serviço, para a edificação do corpo de Cristo,

[[v49-4-13]]

^<<v49-4-13,13>>^ até que todos cheguemos à unidade da fé e do pleno conhecimento do Filho de Deus, à perfeita varonilidade, à medida da estatura da plenitude de Cristo,

[[v49-4-14]]

^<<v49-4-14,14>>^ para que não mais sejamos como meninos, agitados de um lado para outro e levados ao redor por todo vento de doutrina, pela artimanha dos homens, pela astúcia com que induzem ao erro.

[[v49-4-15]]

^<<v49-4-15,15>>^ Mas, seguindo a verdade em amor, cresçamos em tudo naquele que é a cabeça, Cristo,

[[v49-4-16]]

^<<v49-4-16,16>>^ de quem todo o corpo, bem-ajustado e consolidado pelo auxílio de toda junta, segundo a justa cooperação de cada parte, efetua o seu próprio aumento para a edificação de si mesmo em amor.

[[v49-4-17]]

^<<v49-4-17,17>>^ Isto, portanto, digo e no Senhor testifico que não mais andeis como também andam os gentios, na vaidade dos seus próprios pensamentos,

[[v49-4-18]]

^<<v49-4-18,18>>^ obscurecidos de entendimento, alheios à vida de Deus por causa da ignorância em que vivem, pela dureza do seu coração,

[[v49-4-19]]

^<<v49-4-19,19>>^ os quais, tendo-se tornado insensíveis, se entregaram à dissolução para, com avidez, cometerem toda sorte de impureza.

[[v49-4-20]]

^<<v49-4-20,20>>^ Mas não foi assim que aprendestes a Cristo,

[[v49-4-21]]

^<<v49-4-21,21>>^ se é que, de fato, o tendes ouvido e nele fostes instruídos, segundo é a verdade em Jesus,

[[v49-4-22]]

^<<v49-4-22,22>>^ no sentido de que, quanto ao trato passado, vos despojeis do velho homem, que se corrompe segundo as concupiscências do engano,

[[v49-4-23]]

^<<v49-4-23,23>>^ e vos renoveis no espírito do vosso entendimento,

[[v49-4-24]]

^<<v49-4-24,24>>^ e vos revistais do novo homem, criado segundo Deus, em justiça e retidão procedentes da verdade.

[[v49-4-25]]

^<<v49-4-25,25>>^ Por isso, deixando a mentira, fale cada um a verdade com o seu próximo, porque somos membros uns dos outros.

[[v49-4-26]]

^<<v49-4-26,26>>^ Irai-vos e não pequeis; não se ponha o sol sobre a vossa ira,

[[v49-4-27]]

^<<v49-4-27,27>>^ nem deis lugar ao diabo.

[[v49-4-28]]

^<<v49-4-28,28>>^ Aquele que furtava não furte mais; antes, trabalhe, fazendo com as próprias mãos o que é bom, para que tenha com que acudir ao necessitado.

[[v49-4-29]]

^<<v49-4-29,29>>^ Não saia da vossa boca nenhuma palavra torpe, e sim unicamente a que for boa para edificação, conforme a necessidade, e, assim, transmita graça aos que ouvem.

[[v49-4-30]]

^<<v49-4-30,30>>^ E não entristeçais o Espírito de Deus, no qual fostes selados para o dia da redenção.

[[v49-4-31]]

^<<v49-4-31,31>>^ Longe de vós, toda amargura, e cólera, e ira, e gritaria, e blasfêmias, e bem assim toda malícia.

[[v49-4-32]]

^<<v49-4-32,32>>^ Antes, sede uns para com os outros benignos, compassivos, perdoando-vos uns aos outros, como também Deus, em Cristo, vos perdoou.

'''

xref:049-efesios/049-efesios-003.adoc#v49-3-0[&#60; Capítulo Anterior] | <<v49-4-0,Topo>> | xref:049-efesios/049-efesios-005.adoc#v49-5-0[Próximo Capítulo &#62;]