include::./index.adoc[]

[[v49-6-0]]
=== Efésios, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v49-6-1]]

^<<v49-6-1,1>>^ Filhos, obedecei a vossos pais no Senhor, pois isto é justo.

[[v49-6-2]]

^<<v49-6-2,2>>^ Honra a teu pai e a tua mãe (que é o primeiro mandamento com promessa),

[[v49-6-3]]

^<<v49-6-3,3>>^ para que te vá bem, e sejas de longa vida sobre a terra.

[[v49-6-4]]

^<<v49-6-4,4>>^ E vós, pais, não provoqueis vossos filhos à ira, mas criai-os na disciplina e na admoestação do Senhor.

[[v49-6-5]]

^<<v49-6-5,5>>^ Quanto a vós outros, servos, obedecei a vosso senhor segundo a carne com temor e tremor, na sinceridade do vosso coração, como a Cristo,

[[v49-6-6]]

^<<v49-6-6,6>>^ não servindo à vista, como para agradar a homens, mas como servos de Cristo, fazendo, de coração, a vontade de Deus;

[[v49-6-7]]

^<<v49-6-7,7>>^ servindo de boa vontade, como ao Senhor e não como a homens,

[[v49-6-8]]

^<<v49-6-8,8>>^ certos de que cada um, se fizer alguma coisa boa, receberá isso outra vez do Senhor, quer seja servo, quer livre.

[[v49-6-9]]

^<<v49-6-9,9>>^ E vós, senhores, de igual modo procedei para com eles, deixando as ameaças, sabendo que o Senhor, tanto deles como vosso, está nos céus e que para com ele não há acepção de pessoas.

[[v49-6-10]]

^<<v49-6-10,10>>^ Quanto ao mais, sede fortalecidos no Senhor e na força do seu poder.

[[v49-6-11]]

^<<v49-6-11,11>>^ Revesti-vos de toda a armadura de Deus, para poderdes ficar firmes contra as ciladas do diabo;

[[v49-6-12]]

^<<v49-6-12,12>>^ porque a nossa luta não é contra o sangue e a carne, e sim contra os principados e potestades, contra os dominadores deste mundo tenebroso, contra as forças espirituais do mal, nas regiões celestes.

[[v49-6-13]]

^<<v49-6-13,13>>^ Portanto, tomai toda a armadura de Deus, para que possais resistir no dia mau e, depois de terdes vencido tudo, permanecer inabaláveis.

[[v49-6-14]]

^<<v49-6-14,14>>^ Estai, pois, firmes, cingindo-vos com a verdade e vestindo-vos da couraça da justiça.

[[v49-6-15]]

^<<v49-6-15,15>>^ Calçai os pés com a preparação do evangelho da paz;

[[v49-6-16]]

^<<v49-6-16,16>>^ embraçando sempre o escudo da fé, com o qual podereis apagar todos os dardos inflamados do Maligno.

[[v49-6-17]]

^<<v49-6-17,17>>^ Tomai também o capacete da salvação e a espada do Espírito, que é a palavra de Deus;

[[v49-6-18]]

^<<v49-6-18,18>>^ com toda oração e súplica, orando em todo tempo no Espírito e para isto vigiando com toda perseverança e súplica por todos os santos

[[v49-6-19]]

^<<v49-6-19,19>>^ e também por mim; para que me seja dada, no abrir da minha boca, a palavra, para, com intrepidez, fazer conhecido o mistério do evangelho,

[[v49-6-20]]

^<<v49-6-20,20>>^ pelo qual sou embaixador em cadeias, para que, em Cristo, eu seja ousado para falar, como me cumpre fazê-lo.

[[v49-6-21]]

^<<v49-6-21,21>>^ E, para que saibais também a meu respeito e o que faço, de tudo vos informará Tíquico, o irmão amado e fiel ministro do Senhor.

[[v49-6-22]]

^<<v49-6-22,22>>^ Foi para isso que eu vo-lo enviei, para que saibais a nosso respeito, e ele console o vosso coração.

[[v49-6-23]]

^<<v49-6-23,23>>^ Paz seja com os irmãos e amor com fé, da parte de Deus Pai e do Senhor Jesus Cristo.

[[v49-6-24]]

^<<v49-6-24,24>>^ A graça seja com todos os que amam sinceramente a nosso Senhor Jesus Cristo.

'''

xref:049-efesios/049-efesios-005.adoc#v49-5-0[&#60; Capítulo Anterior] | <<v49-6-0,Topo>> | xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[Próximo Capítulo &#62;]