include::./index.adoc[]

[[v49-2-0]]
=== Efésios, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v49-2-1]]

^<<v49-2-1,1>>^ Ele vos deu vida, estando vós mortos nos vossos delitos e pecados,

[[v49-2-2]]

^<<v49-2-2,2>>^ nos quais andastes outrora, segundo o curso deste mundo, segundo o príncipe da potestade do ar, do espírito que agora atua nos filhos da desobediência;

[[v49-2-3]]

^<<v49-2-3,3>>^ entre os quais também todos nós andamos outrora, segundo as inclinações da nossa carne, fazendo a vontade da carne e dos pensamentos; e éramos, por natureza, filhos da ira, como também os demais.

[[v49-2-4]]

^<<v49-2-4,4>>^ Mas Deus, sendo rico em misericórdia, por causa do grande amor com que nos amou,

[[v49-2-5]]

^<<v49-2-5,5>>^ e estando nós mortos em nossos delitos, nos deu vida juntamente com Cristo, — pela graça sois salvos,

[[v49-2-6]]

^<<v49-2-6,6>>^ e, juntamente com ele, nos ressuscitou, e nos fez assentar nos lugares celestiais em Cristo Jesus;

[[v49-2-7]]

^<<v49-2-7,7>>^ para mostrar, nos séculos vindouros, a suprema riqueza da sua graça, em bondade para conosco, em Cristo Jesus.

[[v49-2-8]]

^<<v49-2-8,8>>^ Porque pela graça sois salvos, mediante a fé; e isto não vem de vós; é dom de Deus;

[[v49-2-9]]

^<<v49-2-9,9>>^ não de obras, para que ninguém se glorie.

[[v49-2-10]]

^<<v49-2-10,10>>^ Pois somos feitura dele, criados em Cristo Jesus para boas obras, as quais Deus de antemão preparou para que andássemos nelas.

[[v49-2-11]]

^<<v49-2-11,11>>^ Portanto, lembrai-vos de que, outrora, vós, gentios na carne, chamados incircuncisão por aqueles que se intitulam circuncisos, na carne, por mãos humanas,

[[v49-2-12]]

^<<v49-2-12,12>>^ naquele tempo, estáveis sem Cristo, separados da comunidade de Israel e estranhos às alianças da promessa, não tendo esperança e sem Deus no mundo.

[[v49-2-13]]

^<<v49-2-13,13>>^ Mas, agora, em Cristo Jesus, vós, que antes estáveis longe, fostes aproximados pelo sangue de Cristo.

[[v49-2-14]]

^<<v49-2-14,14>>^ Porque ele é a nossa paz, o qual de ambos fez um; e, tendo derribado a parede da separação que estava no meio, a inimizade,

[[v49-2-15]]

^<<v49-2-15,15>>^ aboliu, na sua carne, a lei dos mandamentos na forma de ordenanças, para que dos dois criasse, em si mesmo, um novo homem, fazendo a paz,

[[v49-2-16]]

^<<v49-2-16,16>>^ e reconciliasse ambos em um só corpo com Deus, por intermédio da cruz, destruindo por ela a inimizade.

[[v49-2-17]]

^<<v49-2-17,17>>^ E, vindo, evangelizou paz a vós outros que estáveis longe e paz também aos que estavam perto;

[[v49-2-18]]

^<<v49-2-18,18>>^ porque, por ele, ambos temos acesso ao Pai em um Espírito.

[[v49-2-19]]

^<<v49-2-19,19>>^ Assim, já não sois estrangeiros e peregrinos, mas concidadãos dos santos, e sois da família de Deus,

[[v49-2-20]]

^<<v49-2-20,20>>^ edificados sobre o fundamento dos apóstolos e profetas, sendo ele mesmo, Cristo Jesus, a pedra angular;

[[v49-2-21]]

^<<v49-2-21,21>>^ no qual todo o edifício, bem-ajustado, cresce para santuário dedicado ao Senhor,

[[v49-2-22]]

^<<v49-2-22,22>>^ no qual também vós juntamente estais sendo edificados para habitação de Deus no Espírito.

'''

xref:049-efesios/049-efesios-001.adoc#v49-1-0[&#60; Capítulo Anterior] | <<v49-2-0,Topo>> | xref:049-efesios/049-efesios-003.adoc#v49-3-0[Próximo Capítulo &#62;]