include::./index.adoc[]

[[v49-3-0]]
=== Efésios, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v49-3-1]]

^<<v49-3-1,1>>^ Por esta causa eu, Paulo, sou o prisioneiro de Cristo Jesus, por amor de vós, gentios,

[[v49-3-2]]

^<<v49-3-2,2>>^ se é que tendes ouvido a respeito da dispensação da graça de Deus a mim confiada para vós outros;

[[v49-3-3]]

^<<v49-3-3,3>>^ pois, segundo uma revelação, me foi dado conhecer o mistério, conforme escrevi há pouco, resumidamente;

[[v49-3-4]]

^<<v49-3-4,4>>^ pelo que, quando ledes, podeis compreender o meu discernimento do mistério de Cristo,

[[v49-3-5]]

^<<v49-3-5,5>>^ o qual, em outras gerações, não foi dado a conhecer aos filhos dos homens, como, agora, foi revelado aos seus santos apóstolos e profetas, no Espírito,

[[v49-3-6]]

^<<v49-3-6,6>>^ a saber, que os gentios são coerdeiros, membros do mesmo corpo e coparticipantes da promessa em Cristo Jesus por meio do evangelho;

[[v49-3-7]]

^<<v49-3-7,7>>^ do qual fui constituído ministro conforme o dom da graça de Deus a mim concedida segundo a força operante do seu poder.

[[v49-3-8]]

^<<v49-3-8,8>>^ A mim, o menor de todos os santos, me foi dada esta graça de pregar aos gentios o evangelho das insondáveis riquezas de Cristo

[[v49-3-9]]

^<<v49-3-9,9>>^ e manifestar qual seja a dispensação do mistério, desde os séculos, oculto em Deus, que criou todas as coisas,

[[v49-3-10]]

^<<v49-3-10,10>>^ para que, pela igreja, a multiforme sabedoria de Deus se torne conhecida, agora, dos principados e potestades nos lugares celestiais,

[[v49-3-11]]

^<<v49-3-11,11>>^ segundo o eterno propósito que estabeleceu em Cristo Jesus, nosso Senhor,

[[v49-3-12]]

^<<v49-3-12,12>>^ pelo qual temos ousadia e acesso com confiança, mediante a fé nele.

[[v49-3-13]]

^<<v49-3-13,13>>^ Portanto, vos peço que não desfaleçais nas minhas tribulações por vós, pois nisso está a vossa glória.

[[v49-3-14]]

^<<v49-3-14,14>>^ Por esta causa, me ponho de joelhos diante do Pai,

[[v49-3-15]]

^<<v49-3-15,15>>^ de quem toma o nome toda família, tanto no céu como sobre a terra,

[[v49-3-16]]

^<<v49-3-16,16>>^ para que, segundo a riqueza da sua glória, vos conceda que sejais fortalecidos com poder, mediante o seu Espírito no homem interior;

[[v49-3-17]]

^<<v49-3-17,17>>^ e, assim, habite Cristo no vosso coração, pela fé, estando vós arraigados e alicerçados em amor,

[[v49-3-18]]

^<<v49-3-18,18>>^ a fim de poderdes compreender, com todos os santos, qual é a largura, e o comprimento, e a altura, e a profundidade

[[v49-3-19]]

^<<v49-3-19,19>>^ e conhecer o amor de Cristo, que excede todo entendimento, para que sejais tomados de toda a plenitude de Deus.

[[v49-3-20]]

^<<v49-3-20,20>>^ Ora, àquele que é poderoso para fazer infinitamente mais do que tudo quanto pedimos ou pensamos, conforme o seu poder que opera em nós,

[[v49-3-21]]

^<<v49-3-21,21>>^ a ele seja a glória, na igreja e em Cristo Jesus, por todas as gerações, para todo o sempre. Amém!

'''

xref:049-efesios/049-efesios-002.adoc#v49-2-0[&#60; Capítulo Anterior] | <<v49-3-0,Topo>> | xref:049-efesios/049-efesios-004.adoc#v49-4-0[Próximo Capítulo &#62;]