include::./index.adoc[]

[[v37-2-0]]
=== Ageu, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v37-2-1]]

^<<v37-2-1,1>>^ No segundo ano do rei Dario, no sétimo mês, ao vigésimo primeiro do mês, veio a palavra do SENHOR por intermédio do profeta Ageu, dizendo:

[[v37-2-2]]

^<<v37-2-2,2>>^ Fala, agora, a Zorobabel, filho de Salatiel, governador de Judá, e a Josué, filho de Jozadaque, o sumo sacerdote, e ao resto do povo, dizendo:

[[v37-2-3]]

^<<v37-2-3,3>>^ Quem dentre vós, que tenha sobrevivido, contemplou esta casa na sua primeira glória? E como a vedes agora? Não é ela como nada aos vossos olhos?

[[v37-2-4]]

^<<v37-2-4,4>>^ Ora, pois, sê forte, Zorobabel, diz o SENHOR, e sê forte, Josué, filho de Jozadaque, o sumo sacerdote, e tu, todo o povo da terra, sê forte, diz o SENHOR, e trabalhai, porque eu sou convosco, diz o SENHOR dos Exércitos;

[[v37-2-5]]

^<<v37-2-5,5>>^ segundo a palavra da aliança que fiz convosco, quando saístes do Egito, o meu Espírito habita no meio de vós; não temais.

[[v37-2-6]]

^<<v37-2-6,6>>^ Pois assim diz o SENHOR dos Exércitos: Ainda uma vez, dentro em pouco, farei abalar o céu, a terra, o mar e a terra seca;

[[v37-2-7]]

^<<v37-2-7,7>>^ farei abalar todas as nações, e as coisas preciosas de todas as nações virão, e encherei de glória esta casa, diz o SENHOR dos Exércitos.

[[v37-2-8]]

^<<v37-2-8,8>>^ Minha é a prata, meu é o ouro, diz o SENHOR dos Exércitos.

[[v37-2-9]]

^<<v37-2-9,9>>^ A glória desta última casa será maior do que a da primeira, diz o SENHOR dos Exércitos; e, neste lugar, darei a paz, diz o SENHOR dos Exércitos.

[[v37-2-10]]

^<<v37-2-10,10>>^ Ao vigésimo quarto dia do mês nono, no segundo ano de Dario, veio a palavra do SENHOR por intermédio do profeta Ageu, dizendo:

[[v37-2-11]]

^<<v37-2-11,11>>^ Assim diz o SENHOR dos Exércitos: Pergunta, agora, aos sacerdotes a respeito da lei:

[[v37-2-12]]

^<<v37-2-12,12>>^ Se alguém leva carne santa na orla de sua veste, e ela vier a tocar no pão, ou no cozinhado, ou no vinho, ou no azeite, ou em qualquer outro mantimento, ficará isto santificado? Responderam os sacerdotes: Não.

[[v37-2-13]]

^<<v37-2-13,13>>^ Então, perguntou Ageu: Se alguém que se tinha tornado impuro pelo contato com um corpo morto tocar nalguma destas coisas, ficará ela imunda? Responderam os sacerdotes: Ficará imunda.

[[v37-2-14]]

^<<v37-2-14,14>>^ Então, prosseguiu Ageu: Assim é este povo, e assim esta nação perante mim, diz o SENHOR; assim é toda a obra das suas mãos, e o que ali oferecem: tudo é imundo.

[[v37-2-15]]

^<<v37-2-15,15>>^ Agora, pois, considerai tudo o que está acontecendo desde aquele dia. Antes de pordes pedra sobre pedra no templo do SENHOR,

[[v37-2-16]]

^<<v37-2-16,16>>^ antes daquele tempo, alguém vinha a um monte de vinte medidas, e havia somente dez; vinha ao lagar para tirar cinquenta, e havia somente vinte.

[[v37-2-17]]

^<<v37-2-17,17>>^ Eu vos feri com queimaduras, e com ferrugem, e com saraiva, em toda a obra das vossas mãos; e não houve, entre vós, quem voltasse para mim, diz o SENHOR.

[[v37-2-18]]

^<<v37-2-18,18>>^ Considerai, eu vos rogo, desde este dia em diante, desde o vigésimo quarto dia do mês nono, desde o dia em que se fundou o templo do SENHOR, considerai nestas coisas.

[[v37-2-19]]

^<<v37-2-19,19>>^ Já não há semente no celeiro. Além disso, a videira, a figueira, a romeira e a oliveira não têm dado os seus frutos; mas, desde este dia, vos abençoarei.

[[v37-2-20]]

^<<v37-2-20,20>>^ Veio a palavra do SENHOR segunda vez a Ageu, ao vigésimo quarto dia do mês, dizendo:

[[v37-2-21]]

^<<v37-2-21,21>>^ Fala a Zorobabel, governador de Judá: Farei abalar o céu e a terra;

[[v37-2-22]]

^<<v37-2-22,22>>^ derribarei o trono dos reinos e destruirei a força dos reinos das nações; destruirei o carro e os que andam nele; os cavalos e os seus cavaleiros cairão, um pela espada do outro.

[[v37-2-23]]

^<<v37-2-23,23>>^ Naquele dia, diz o SENHOR dos Exércitos, tomar-te-ei, ó Zorobabel, filho de Salatiel, servo meu, diz o SENHOR, e te farei como um anel de selar, porque te escolhi, diz o SENHOR dos Exércitos.

'''

xref:037-ageu/037-ageu-001.adoc#v37-1-0[&#60; Capítulo Anterior] | <<v37-2-0,Topo>> | xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[Próximo Capítulo &#62;]