include::./index.adoc[]

[[v37-1-0]]
=== Ageu, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v37-1-1]]

^<<v37-1-1,1>>^ No segundo ano do rei Dario, no sexto mês, no primeiro dia do mês, veio a palavra do SENHOR, por intermédio do profeta Ageu, a Zorobabel, filho de Salatiel, governador de Judá, e a Josué, filho de Jozadaque, o sumo sacerdote, dizendo:

[[v37-1-2]]

^<<v37-1-2,2>>^ Assim fala o SENHOR dos Exércitos: Este povo diz: Não veio ainda o tempo, o tempo em que a Casa do SENHOR deve ser edificada.

[[v37-1-3]]

^<<v37-1-3,3>>^ Veio, pois, a palavra do SENHOR, por intermédio do profeta Ageu, dizendo:

[[v37-1-4]]

^<<v37-1-4,4>>^ Acaso, é tempo de habitardes vós em casas apaineladas, enquanto esta casa permanece em ruínas?

[[v37-1-5]]

^<<v37-1-5,5>>^ Ora, pois, assim diz o SENHOR dos Exércitos: Considerai o vosso passado.

[[v37-1-6]]

^<<v37-1-6,6>>^ Tendes semeado muito e recolhido pouco; comeis, mas não chega para fartar-vos; bebeis, mas não dá para saciar-vos; vestis-vos, mas ninguém se aquece; e o que recebe salário, recebe-o para pô-lo num saquitel furado.

[[v37-1-7]]

^<<v37-1-7,7>>^ Assim diz o SENHOR dos Exércitos: Considerai o vosso passado.

[[v37-1-8]]

^<<v37-1-8,8>>^ Subi ao monte, trazei madeira e edificai a casa; dela me agradarei e serei glorificado, diz o SENHOR.

[[v37-1-9]]

^<<v37-1-9,9>>^ Esperastes o muito, e eis que veio a ser pouco, e esse pouco, quando o trouxestes para casa, eu com um assopro o dissipei. Por quê? — diz o SENHOR dos Exércitos; por causa da minha casa, que permanece em ruínas, ao passo que cada um de vós corre por causa de sua própria casa.

[[v37-1-10]]

^<<v37-1-10,10>>^ Por isso, os céus sobre vós retêm o seu orvalho, e a terra, os seus frutos.

[[v37-1-11]]

^<<v37-1-11,11>>^ Fiz vir a seca sobre a terra e sobre os montes; sobre o cereal, sobre o vinho, sobre o azeite e sobre o que a terra produz, como também sobre os homens, sobre os animais e sobre todo trabalho das mãos.

[[v37-1-12]]

^<<v37-1-12,12>>^ Então, Zorobabel, filho de Salatiel, e Josué, filho de Jozadaque, o sumo sacerdote, e todo o resto do povo atenderam à voz do SENHOR, seu Deus, e às palavras do profeta Ageu, as quais o SENHOR, seu Deus, o tinha mandado dizer; e o povo temeu diante do SENHOR.

[[v37-1-13]]

^<<v37-1-13,13>>^ Então, Ageu, o enviado do SENHOR, falou ao povo, segundo a mensagem do SENHOR, dizendo: Eu sou convosco, diz o SENHOR.

[[v37-1-14]]

^<<v37-1-14,14>>^ O SENHOR despertou o espírito de Zorobabel, filho de Salatiel, governador de Judá, e o espírito de Josué, filho de Jozadaque, o sumo sacerdote, e o espírito do resto de todo o povo; eles vieram e se puseram ao trabalho na Casa do SENHOR dos Exércitos, seu Deus,

[[v37-1-15]]

^<<v37-1-15,15>>^ ao vigésimo quarto dia do sexto mês.

'''

xref:036-sofonias/036-sofonias-003.adoc#v36-3-0[&#60; Capítulo Anterior] | <<v37-1-0,Topo>> | xref:037-ageu/037-ageu-002.adoc#v37-2-0[Próximo Capítulo &#62;]