include::./index.adoc[]

[[v60-3-0]]
=== 1 Pedro, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v60-3-1]]

^<<v60-3-1,1>>^ Mulheres, sede vós, igualmente, submissas a vosso próprio marido, para que, se ele ainda não obedece à palavra, seja ganho, sem palavra alguma, por meio do procedimento de sua esposa,

[[v60-3-2]]

^<<v60-3-2,2>>^ ao observar o vosso honesto comportamento cheio de temor.

[[v60-3-3]]

^<<v60-3-3,3>>^ Não seja o adorno da esposa o que é exterior, como frisado de cabelos, adereços de ouro, aparato de vestuário;

[[v60-3-4]]

^<<v60-3-4,4>>^ seja, porém, o homem interior do coração, unido ao incorruptível trajo de um espírito manso e tranquilo, que é de grande valor diante de Deus.

[[v60-3-5]]

^<<v60-3-5,5>>^ Pois foi assim também que a si mesmas se ataviaram, outrora, as santas mulheres que esperavam em Deus, estando submissas a seu próprio marido,

[[v60-3-6]]

^<<v60-3-6,6>>^ como fazia Sara, que obedeceu a Abraão, chamando-lhe senhor, da qual vós vos tornastes filhas, praticando o bem e não temendo perturbação alguma.

[[v60-3-7]]

^<<v60-3-7,7>>^ Maridos, vós, igualmente, vivei a vida comum do lar, com discernimento; e, tendo consideração para com a vossa mulher como parte mais frágil, tratai-a com dignidade, porque sois, juntamente, herdeiros da mesma graça de vida, para que não se interrompam as vossas orações.

[[v60-3-8]]

^<<v60-3-8,8>>^ Finalmente, sede todos de igual ânimo, compadecidos, fraternalmente amigos, misericordiosos, humildes,

[[v60-3-9]]

^<<v60-3-9,9>>^ não pagando mal por mal ou injúria por injúria; antes, pelo contrário, bendizendo, pois para isto mesmo fostes chamados, a fim de receberdes bênção por herança.

[[v60-3-10]]

^<<v60-3-10,10>>^ Pois quem quer amar a vida e ver dias felizes refreie a língua do mal e evite que os seus lábios falem dolosamente;

[[v60-3-11]]

^<<v60-3-11,11>>^ aparte-se do mal, pratique o que é bom, busque a paz e empenhe-se por alcançá-la.

[[v60-3-12]]

^<<v60-3-12,12>>^ Porque os olhos do Senhor repousam sobre os justos, e os seus ouvidos estão abertos às suas súplicas, mas o rosto do Senhor está contra aqueles que praticam males.

[[v60-3-13]]

^<<v60-3-13,13>>^ Ora, quem é que vos há de maltratar, se fordes zelosos do que é bom?

[[v60-3-14]]

^<<v60-3-14,14>>^ Mas, ainda que venhais a sofrer por causa da justiça, bem-aventurados sois. Não vos amedronteis, portanto, com as suas ameaças, nem fiqueis alarmados;

[[v60-3-15]]

^<<v60-3-15,15>>^ antes, santificai a Cristo, como Senhor, em vosso coração, estando sempre preparados para responder a todo aquele que vos pedir razão da esperança que há em vós,

[[v60-3-16]]

^<<v60-3-16,16>>^ fazendo-o, todavia, com mansidão e temor, com boa consciência, de modo que, naquilo em que falam contra vós outros, fiquem envergonhados os que difamam o vosso bom procedimento em Cristo,

[[v60-3-17]]

^<<v60-3-17,17>>^ porque, se for da vontade de Deus, é melhor que sofrais por praticardes o que é bom do que praticando o mal.

[[v60-3-18]]

^<<v60-3-18,18>>^ Pois também Cristo morreu, uma única vez, pelos pecados, o justo pelos injustos, para conduzir-vos a Deus; morto, sim, na carne, mas vivificado no espírito,

[[v60-3-19]]

^<<v60-3-19,19>>^ no qual também foi e pregou aos espíritos em prisão,

[[v60-3-20]]

^<<v60-3-20,20>>^ os quais, noutro tempo, foram desobedientes quando a longanimidade de Deus aguardava nos dias de Noé, enquanto se preparava a arca, na qual poucos, a saber, oito pessoas, foram salvos, através da água,

[[v60-3-21]]

^<<v60-3-21,21>>^ a qual, figurando o batismo, agora também vos salva, não sendo a remoção da imundícia da carne, mas a indagação de uma boa consciência para com Deus, por meio da ressurreição de Jesus Cristo;

[[v60-3-22]]

^<<v60-3-22,22>>^ o qual, depois de ir para o céu, está à destra de Deus, ficando-lhe subordinados anjos, e potestades, e poderes.

'''

xref:060-1-pedro/060-1-pedro-002.adoc#v60-2-0[&#60; Capítulo Anterior] | <<v60-3-0,Topo>> | xref:060-1-pedro/060-1-pedro-004.adoc#v60-4-0[Próximo Capítulo &#62;]