include::./index.adoc[]

[[v60-4-0]]
=== 1 Pedro, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v60-4-1]]

^<<v60-4-1,1>>^ Ora, tendo Cristo sofrido na carne, armai-vos também vós do mesmo pensamento; pois aquele que sofreu na carne deixou o pecado,

[[v60-4-2]]

^<<v60-4-2,2>>^ para que, no tempo que vos resta na carne, já não vivais de acordo com as paixões dos homens, mas segundo a vontade de Deus.

[[v60-4-3]]

^<<v60-4-3,3>>^ Porque basta o tempo decorrido para terdes executado a vontade dos gentios, tendo andado em dissoluções, concupiscências, borracheiras, orgias, bebedices e em detestáveis idolatrias.

[[v60-4-4]]

^<<v60-4-4,4>>^ Por isso, difamando-vos, estranham que não concorrais com eles ao mesmo excesso de devassidão,

[[v60-4-5]]

^<<v60-4-5,5>>^ os quais hão de prestar contas àquele que é competente para julgar vivos e mortos;

[[v60-4-6]]

^<<v60-4-6,6>>^ pois, para este fim, foi o evangelho pregado também a mortos, para que, mesmo julgados na carne segundo os homens, vivam no espírito segundo Deus.

[[v60-4-7]]

^<<v60-4-7,7>>^ Ora, o fim de todas as coisas está próximo; sede, portanto, criteriosos e sóbrios a bem das vossas orações.

[[v60-4-8]]

^<<v60-4-8,8>>^ Acima de tudo, porém, tende amor intenso uns para com os outros, porque o amor cobre multidão de pecados.

[[v60-4-9]]

^<<v60-4-9,9>>^ Sede, mutuamente, hospitaleiros, sem murmuração.

[[v60-4-10]]

^<<v60-4-10,10>>^ Servi uns aos outros, cada um conforme o dom que recebeu, como bons despenseiros da multiforme graça de Deus.

[[v60-4-11]]

^<<v60-4-11,11>>^ Se alguém fala, fale de acordo com os oráculos de Deus; se alguém serve, faça-o na força que Deus supre, para que, em todas as coisas, seja Deus glorificado, por meio de Jesus Cristo, a quem pertence a glória e o domínio pelos séculos dos séculos. Amém!

[[v60-4-12]]

^<<v60-4-12,12>>^ Amados, não estranheis o fogo ardente que surge no meio de vós, destinado a provar-vos, como se alguma coisa extraordinária vos estivesse acontecendo;

[[v60-4-13]]

^<<v60-4-13,13>>^ pelo contrário, alegrai-vos na medida em que sois coparticipantes dos sofrimentos de Cristo, para que também, na revelação de sua glória, vos alegreis exultando.

[[v60-4-14]]

^<<v60-4-14,14>>^ Se, pelo nome de Cristo, sois injuriados, bem-aventurados sois, porque sobre vós repousa o Espírito da glória e de Deus.

[[v60-4-15]]

^<<v60-4-15,15>>^ Não sofra, porém, nenhum de vós como assassino, ou ladrão, ou malfeitor, ou como quem se intromete em negócios de outrem;

[[v60-4-16]]

^<<v60-4-16,16>>^ mas, se sofrer como cristão, não se envergonhe disso; antes, glorifique a Deus com esse nome.

[[v60-4-17]]

^<<v60-4-17,17>>^ Porque a ocasião de começar o juízo pela casa de Deus é chegada; ora, se primeiro vem por nós, qual será o fim daqueles que não obedecem ao evangelho de Deus?

[[v60-4-18]]

^<<v60-4-18,18>>^ E, se é com dificuldade que o justo é salvo, onde vai comparecer o ímpio, sim, o pecador?

[[v60-4-19]]

^<<v60-4-19,19>>^ Por isso, também os que sofrem segundo a vontade de Deus encomendem a sua alma ao fiel Criador, na prática do bem.

'''

xref:060-1-pedro/060-1-pedro-003.adoc#v60-3-0[&#60; Capítulo Anterior] | <<v60-4-0,Topo>> | xref:060-1-pedro/060-1-pedro-005.adoc#v60-5-0[Próximo Capítulo &#62;]