include::./index.adoc[]

[[v60-2-0]]
=== 1 Pedro, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v60-2-1]]

^<<v60-2-1,1>>^ Despojando-vos, portanto, de toda maldade e dolo, de hipocrisias e invejas e de toda sorte de maledicências,

[[v60-2-2]]

^<<v60-2-2,2>>^ desejai ardentemente, como crianças recém-nascidas, o genuíno leite espiritual, para que, por ele, vos seja dado crescimento para salvação,

[[v60-2-3]]

^<<v60-2-3,3>>^ se é que já tendes a experiência de que o Senhor é bondoso.

[[v60-2-4]]

^<<v60-2-4,4>>^ Chegando-vos para ele, a pedra que vive, rejeitada, sim, pelos homens, mas para com Deus eleita e preciosa,

[[v60-2-5]]

^<<v60-2-5,5>>^ também vós mesmos, como pedras que vivem, sois edificados casa espiritual para serdes sacerdócio santo, a fim de oferecerdes sacrifícios espirituais agradáveis a Deus por intermédio de Jesus Cristo.

[[v60-2-6]]

^<<v60-2-6,6>>^ Pois isso está na Escritura: Eis que ponho em Sião uma pedra angular, eleita e preciosa; e quem nela crer não será, de modo algum, envergonhado.

[[v60-2-7]]

^<<v60-2-7,7>>^ Para vós outros, portanto, os que credes, é a preciosidade; mas, para os descrentes, A pedra que os construtores rejeitaram, essa veio a ser a principal pedra, angular

[[v60-2-8]]

^<<v60-2-8,8>>^ e: Pedra de tropeço e rocha de ofensa. São estes os que tropeçam na palavra, sendo desobedientes, para o que também foram postos.

[[v60-2-9]]

^<<v60-2-9,9>>^ Vós, porém, sois raça eleita, sacerdócio real, nação santa, povo de propriedade exclusiva de Deus, a fim de proclamardes as virtudes daquele que vos chamou das trevas para a sua maravilhosa luz;

[[v60-2-10]]

^<<v60-2-10,10>>^ vós, sim, que, antes, não éreis povo, mas, agora, sois povo de Deus, que não tínheis alcançado misericórdia, mas, agora, alcançastes misericórdia.

[[v60-2-11]]

^<<v60-2-11,11>>^ Amados, exorto-vos, como peregrinos e forasteiros que sois, a vos absterdes das paixões carnais, que fazem guerra contra a alma,

[[v60-2-12]]

^<<v60-2-12,12>>^ mantendo exemplar o vosso procedimento no meio dos gentios, para que, naquilo que falam contra vós outros como de malfeitores, observando-vos em vossas boas obras, glorifiquem a Deus no dia da visitação.

[[v60-2-13]]

^<<v60-2-13,13>>^ Sujeitai-vos a toda instituição humana por causa do Senhor, quer seja ao rei, como soberano,

[[v60-2-14]]

^<<v60-2-14,14>>^ quer às autoridades, como enviadas por ele, tanto para castigo dos malfeitores como para louvor dos que praticam o bem.

[[v60-2-15]]

^<<v60-2-15,15>>^ Porque assim é a vontade de Deus, que, pela prática do bem, façais emudecer a ignorância dos insensatos;

[[v60-2-16]]

^<<v60-2-16,16>>^ como livres que sois, não usando, todavia, a liberdade por pretexto da malícia, mas vivendo como servos de Deus.

[[v60-2-17]]

^<<v60-2-17,17>>^ Tratai todos com honra, amai os irmãos, temei a Deus, honrai o rei.

[[v60-2-18]]

^<<v60-2-18,18>>^ Servos, sede submissos, com todo o temor ao vosso senhor, não somente se for bom e cordato, mas também ao perverso;

[[v60-2-19]]

^<<v60-2-19,19>>^ porque isto é grato, que alguém suporte tristezas, sofrendo injustamente, por motivo de sua consciência para com Deus.

[[v60-2-20]]

^<<v60-2-20,20>>^ Pois que glória há, se, pecando e sendo esbofeteados por isso, o suportais com paciência? Se, entretanto, quando praticais o bem, sois igualmente afligidos e o suportais com paciência, isto é grato a Deus.

[[v60-2-21]]

^<<v60-2-21,21>>^ Porquanto para isto mesmo fostes chamados, pois que também Cristo sofreu em vosso lugar, deixando-vos exemplo para seguirdes os seus passos,

[[v60-2-22]]

^<<v60-2-22,22>>^ o qual não cometeu pecado, nem dolo algum se achou em sua boca;

[[v60-2-23]]

^<<v60-2-23,23>>^ pois ele, quando ultrajado, não revidava com ultraje; quando maltratado, não fazia ameaças, mas entregava-se àquele que julga retamente,

[[v60-2-24]]

^<<v60-2-24,24>>^ carregando ele mesmo em seu corpo, sobre o madeiro, os nossos pecados, para que nós, mortos para os pecados, vivamos para a justiça; por suas chagas, fostes sarados.

[[v60-2-25]]

^<<v60-2-25,25>>^ Porque estáveis desgarrados como ovelhas; agora, porém, vos convertestes ao Pastor e Bispo da vossa alma.

'''

xref:060-1-pedro/060-1-pedro-001.adoc#v60-1-0[&#60; Capítulo Anterior] | <<v60-2-0,Topo>> | xref:060-1-pedro/060-1-pedro-003.adoc#v60-3-0[Próximo Capítulo &#62;]