include::./index.adoc[]

[[v60-1-0]]
=== 1 Pedro, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v60-1-1]]

^<<v60-1-1,1>>^ Pedro, apóstolo de Jesus Cristo, aos eleitos que são forasteiros da Dispersão no Ponto, Galácia, Capadócia, Ásia e Bitínia,

[[v60-1-2]]

^<<v60-1-2,2>>^ eleitos, segundo a presciência de Deus Pai, em santificação do Espírito, para a obediência e a aspersão do sangue de Jesus Cristo, graça e paz vos sejam multiplicadas.

[[v60-1-3]]

^<<v60-1-3,3>>^ Bendito o Deus e Pai de nosso Senhor Jesus Cristo, que, segundo a sua muita misericórdia, nos regenerou para uma viva esperança, mediante a ressurreição de Jesus Cristo dentre os mortos,

[[v60-1-4]]

^<<v60-1-4,4>>^ para uma herança incorruptível, sem mácula, imarcescível, reservada nos céus para vós outros

[[v60-1-5]]

^<<v60-1-5,5>>^ que sois guardados pelo poder de Deus, mediante a fé, para a salvação preparada para revelar-se no último tempo.

[[v60-1-6]]

^<<v60-1-6,6>>^ Nisso exultais, embora, no presente, por breve tempo, se necessário, sejais contristados por várias provações,

[[v60-1-7]]

^<<v60-1-7,7>>^ para que, uma vez confirmado o valor da vossa fé, muito mais preciosa do que o ouro perecível, mesmo apurado por fogo, redunde em louvor, glória e honra na revelação de Jesus Cristo;

[[v60-1-8]]

^<<v60-1-8,8>>^ a quem, não havendo visto, amais; no qual, não vendo agora, mas crendo, exultais com alegria indizível e cheia de glória,

[[v60-1-9]]

^<<v60-1-9,9>>^ obtendo o fim da vossa fé: a salvação da vossa alma.

[[v60-1-10]]

^<<v60-1-10,10>>^ Foi a respeito desta salvação que os profetas indagaram e inquiriram, os quais profetizaram acerca da graça a vós outros destinada,

[[v60-1-11]]

^<<v60-1-11,11>>^ investigando, atentamente, qual a ocasião ou quais as circunstâncias oportunas, indicadas pelo Espírito de Cristo, que neles estava, ao dar de antemão testemunho sobre os sofrimentos referentes a Cristo e sobre as glórias que os seguiriam.

[[v60-1-12]]

^<<v60-1-12,12>>^ A eles foi revelado que, não para si mesmos, mas para vós outros, ministravam as coisas que, agora, vos foram anunciadas por aqueles que, pelo Espírito Santo enviado do céu, vos pregaram o evangelho, coisas essas que anjos anelam perscrutar.

[[v60-1-13]]

^<<v60-1-13,13>>^ Por isso, cingindo o vosso entendimento, sede sóbrios e esperai inteiramente na graça que vos está sendo trazida na revelação de Jesus Cristo.

[[v60-1-14]]

^<<v60-1-14,14>>^ Como filhos da obediência, não vos amoldeis às paixões que tínheis anteriormente na vossa ignorância;

[[v60-1-15]]

^<<v60-1-15,15>>^ pelo contrário, segundo é santo aquele que vos chamou, tornai-vos santos também vós mesmos em todo o vosso procedimento,

[[v60-1-16]]

^<<v60-1-16,16>>^ porque escrito está: Sede santos, porque eu sou santo.

[[v60-1-17]]

^<<v60-1-17,17>>^ Ora, se invocais como Pai aquele que, sem acepção de pessoas, julga segundo as obras de cada um, portai-vos com temor durante o tempo da vossa peregrinação,

[[v60-1-18]]

^<<v60-1-18,18>>^ sabendo que não foi mediante coisas corruptíveis, como prata ou ouro, que fostes resgatados do vosso fútil procedimento que vossos pais vos legaram,

[[v60-1-19]]

^<<v60-1-19,19>>^ mas pelo precioso sangue, como de cordeiro sem defeito e sem mácula, o sangue de Cristo,

[[v60-1-20]]

^<<v60-1-20,20>>^ conhecido, com efeito, antes da fundação do mundo, porém manifestado no fim dos tempos, por amor de vós

[[v60-1-21]]

^<<v60-1-21,21>>^ que, por meio dele, tendes fé em Deus, o qual o ressuscitou dentre os mortos e lhe deu glória, de sorte que a vossa fé e esperança estejam em Deus.

[[v60-1-22]]

^<<v60-1-22,22>>^ Tendo purificado a vossa alma, pela vossa obediência à verdade, tendo em vista o amor fraternal não fingido, amai-vos, de coração, uns aos outros ardentemente,

[[v60-1-23]]

^<<v60-1-23,23>>^ pois fostes regenerados não de semente corruptível, mas de incorruptível, mediante a palavra de Deus, a qual vive e é permanente.

[[v60-1-24]]

^<<v60-1-24,24>>^ Pois toda carne é como a erva, e toda a sua glória, como a flor da erva; seca-se a erva, e cai a sua flor;

[[v60-1-25]]

^<<v60-1-25,25>>^ a palavra do Senhor, porém, permanece eternamente. Ora, esta é a palavra que vos foi evangelizada.

'''

xref:059-tiago/059-tiago-005.adoc#v59-5-0[&#60; Capítulo Anterior] | <<v60-1-0,Topo>> | xref:060-1-pedro/060-1-pedro-002.adoc#v60-2-0[Próximo Capítulo &#62;]