include::./index.adoc[]

[[v45-4-0]]
=== Romanos, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v45-4-1]]

^<<v45-4-1,1>>^ Que, pois, diremos ter alcançado Abraão, nosso pai segundo a carne?

[[v45-4-2]]

^<<v45-4-2,2>>^ Porque, se Abraão foi justificado por obras, tem de que se gloriar, porém não diante de Deus.

[[v45-4-3]]

^<<v45-4-3,3>>^ Pois que diz a Escritura? Abraão creu em Deus, e isso lhe foi imputado para justiça.

[[v45-4-4]]

^<<v45-4-4,4>>^ Ora, ao que trabalha, o salário não é considerado como favor, e sim como dívida.

[[v45-4-5]]

^<<v45-4-5,5>>^ Mas, ao que não trabalha, porém crê naquele que justifica o ímpio, a sua fé lhe é atribuída como justiça.

[[v45-4-6]]

^<<v45-4-6,6>>^ E é assim também que Davi declara ser bem-aventurado o homem a quem Deus atribui justiça, independentemente de obras:

[[v45-4-7]]

^<<v45-4-7,7>>^ Bem-aventurados aqueles cujas iniquidades são perdoadas, e cujos pecados são cobertos;

[[v45-4-8]]

^<<v45-4-8,8>>^ bem-aventurado o homem a quem o Senhor jamais imputará pecado.

[[v45-4-9]]

^<<v45-4-9,9>>^ Vem, pois, esta bem-aventurança exclusivamente sobre os circuncisos ou também sobre os incircuncisos? Visto que dizemos: a fé foi imputada a Abraão para justiça.

[[v45-4-10]]

^<<v45-4-10,10>>^ Como, pois, lhe foi atribuída? Estando ele já circuncidado ou ainda incircunciso? Não no regime da circuncisão, e sim quando incircunciso.

[[v45-4-11]]

^<<v45-4-11,11>>^ E recebeu o sinal da circuncisão como selo da justiça da fé que teve quando ainda incircunciso; para vir a ser o pai de todos os que creem, embora não circuncidados, a fim de que lhes fosse imputada a justiça,

[[v45-4-12]]

^<<v45-4-12,12>>^ e pai da circuncisão, isto é, daqueles que não são apenas circuncisos, mas também andam nas pisadas da fé que teve Abraão, nosso pai, antes de ser circuncidado.

[[v45-4-13]]

^<<v45-4-13,13>>^ Não foi por intermédio da lei que a Abraão ou a sua descendência coube a promessa de ser herdeiro do mundo, e sim mediante a justiça da fé.

[[v45-4-14]]

^<<v45-4-14,14>>^ Pois, se os da lei é que são os herdeiros, anula-se a fé e cancela-se a promessa,

[[v45-4-15]]

^<<v45-4-15,15>>^ porque a lei suscita a ira; mas onde não há lei, também não há transgressão.

[[v45-4-16]]

^<<v45-4-16,16>>^ Essa é a razão por que provém da fé, para que seja segundo a graça, a fim de que seja firme a promessa para toda a descendência, não somente ao que está no regime da lei, mas também ao que é da fé que teve Abraão (porque Abraão é pai de todos nós,

[[v45-4-17]]

^<<v45-4-17,17>>^ como está escrito: Por pai de muitas nações te constituí. ), perante aquele no qual creu, o Deus que vivifica os mortos e chama à existência as coisas que não existem.

[[v45-4-18]]

^<<v45-4-18,18>>^ Abraão, esperando contra a esperança, creu, para vir a ser pai de muitas nações, segundo lhe fora dito: Assim será a tua descendência.

[[v45-4-19]]

^<<v45-4-19,19>>^ E, sem enfraquecer na fé, embora levasse em conta o seu próprio corpo amortecido, sendo já de cem anos, e a idade avançada de Sara,

[[v45-4-20]]

^<<v45-4-20,20>>^ não duvidou, por incredulidade, da promessa de Deus; mas, pela fé, se fortaleceu, dando glória a Deus,

[[v45-4-21]]

^<<v45-4-21,21>>^ estando plenamente convicto de que ele era poderoso para cumprir o que prometera.

[[v45-4-22]]

^<<v45-4-22,22>>^ Pelo que isso lhe foi também imputado para justiça.

[[v45-4-23]]

^<<v45-4-23,23>>^ E não somente por causa dele está escrito que lhe foi levado em conta,

[[v45-4-24]]

^<<v45-4-24,24>>^ mas também por nossa causa, posto que a nós igualmente nos será imputado, a saber, a nós que cremos naquele que ressuscitou dentre os mortos a Jesus, nosso Senhor,

[[v45-4-25]]

^<<v45-4-25,25>>^ o qual foi entregue por causa das nossas transgressões e ressuscitou por causa da nossa justificação.

'''

xref:045-romanos/045-romanos-003.adoc#v45-3-0[&#60; Capítulo Anterior] | <<v45-4-0,Topo>> | xref:045-romanos/045-romanos-005.adoc#v45-5-0[Próximo Capítulo &#62;]