include::./index.adoc[]

[[v45-13-0]]
=== Romanos, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v45-13-1]]

^<<v45-13-1,1>>^ Todo homem esteja sujeito às autoridades superiores; porque não há autoridade que não proceda de Deus; e as autoridades que existem foram por ele instituídas.

[[v45-13-2]]

^<<v45-13-2,2>>^ De modo que aquele que se opõe à autoridade resiste à ordenação de Deus; e os que resistem trarão sobre si mesmos condenação.

[[v45-13-3]]

^<<v45-13-3,3>>^ Porque os magistrados não são para temor, quando se faz o bem, e sim quando se faz o mal. Queres tu não temer a autoridade? Faze o bem e terás louvor dela,

[[v45-13-4]]

^<<v45-13-4,4>>^ visto que a autoridade é ministro de Deus para teu bem. Entretanto, se fizeres o mal, teme; porque não é sem motivo que ela traz a espada; pois é ministro de Deus, vingador, para castigar o que pratica o mal.

[[v45-13-5]]

^<<v45-13-5,5>>^ É necessário que lhe estejais sujeitos, não somente por causa do temor da punição, mas também por dever de consciência.

[[v45-13-6]]

^<<v45-13-6,6>>^ Por esse motivo, também pagais tributos, porque são ministros de Deus, atendendo, constantemente, a este serviço.

[[v45-13-7]]

^<<v45-13-7,7>>^ Pagai a todos o que lhes é devido: a quem tributo, tributo; a quem imposto, imposto; a quem respeito, respeito; a quem honra, honra.

[[v45-13-8]]

^<<v45-13-8,8>>^ A ninguém fiqueis devendo coisa alguma, exceto o amor com que vos ameis uns aos outros; pois quem ama o próximo tem cumprido a lei.

[[v45-13-9]]

^<<v45-13-9,9>>^ Pois isto: Não adulterarás, não matarás, não furtarás, não cobiçarás, e, se há qualquer outro mandamento, tudo nesta palavra se resume: Amarás o teu próximo como a ti mesmo.

[[v45-13-10]]

^<<v45-13-10,10>>^ O amor não pratica o mal contra o próximo; de sorte que o cumprimento da lei é o amor.

[[v45-13-11]]

^<<v45-13-11,11>>^ E digo isto a vós outros que conheceis o tempo: já é hora de vos despertardes do sono; porque a nossa salvação está, agora, mais perto do que quando no princípio cremos.

[[v45-13-12]]

^<<v45-13-12,12>>^ Vai alta a noite, e vem chegando o dia. Deixemos, pois, as obras das trevas e revistamo-nos das armas da luz.

[[v45-13-13]]

^<<v45-13-13,13>>^ Andemos dignamente, como em pleno dia, não em orgias e bebedices, não em impudicícias e dissoluções, não em contendas e ciúmes;

[[v45-13-14]]

^<<v45-13-14,14>>^ mas revesti-vos do Senhor Jesus Cristo e nada disponhais para a carne no tocante às suas concupiscências.

'''

xref:045-romanos/045-romanos-012.adoc#v45-12-0[&#60; Capítulo Anterior] | <<v45-13-0,Topo>> | xref:045-romanos/045-romanos-014.adoc#v45-14-0[Próximo Capítulo &#62;]