include::./index.adoc[]

[[v45-9-0]]
=== Romanos, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v45-9-1]]

^<<v45-9-1,1>>^ Digo a verdade em Cristo, não minto, testemunhando comigo, no Espírito Santo, a minha própria consciência:

[[v45-9-2]]

^<<v45-9-2,2>>^ tenho grande tristeza e incessante dor no coração;

[[v45-9-3]]

^<<v45-9-3,3>>^ porque eu mesmo desejaria ser anátema, separado de Cristo, por amor de meus irmãos, meus compatriotas, segundo a carne.

[[v45-9-4]]

^<<v45-9-4,4>>^ São israelitas. Pertence-lhes a adoção e também a glória, as alianças, a legislação, o culto e as promessas;

[[v45-9-5]]

^<<v45-9-5,5>>^ deles são os patriarcas, e também deles descende o Cristo, segundo a carne, o qual é sobre todos, Deus bendito para todo o sempre. Amém!

[[v45-9-6]]

^<<v45-9-6,6>>^ E não pensemos que a palavra de Deus haja falhado, porque nem todos os de Israel são, de fato, israelitas;

[[v45-9-7]]

^<<v45-9-7,7>>^ nem por serem descendentes de Abraão são todos seus filhos; mas: Em Isaque será chamada a tua descendência.

[[v45-9-8]]

^<<v45-9-8,8>>^ Isto é, estes filhos de Deus não são propriamente os da carne, mas devem ser considerados como descendência os filhos da promessa.

[[v45-9-9]]

^<<v45-9-9,9>>^ Porque a palavra da promessa é esta: Por esse tempo, virei, e Sara terá um filho.

[[v45-9-10]]

^<<v45-9-10,10>>^ E não ela somente, mas também Rebeca, ao conceber de um só, Isaque, nosso pai.

[[v45-9-11]]

^<<v45-9-11,11>>^ E ainda não eram os gêmeos nascidos, nem tinham praticado o bem ou o mal (para que o propósito de Deus, quanto à eleição, prevalecesse, não por obras, mas por aquele que chama),

[[v45-9-12]]

^<<v45-9-12,12>>^ já fora dito a ela: O mais velho será servo do mais moço.

[[v45-9-13]]

^<<v45-9-13,13>>^ Como está escrito: Amei Jacó, porém me aborreci de Esaú.

[[v45-9-14]]

^<<v45-9-14,14>>^ Que diremos, pois? Há injustiça da parte de Deus? De modo nenhum!

[[v45-9-15]]

^<<v45-9-15,15>>^ Pois ele diz a Moisés: Terei misericórdia de quem me aprouver ter misericórdia e compadecer-me-ei de quem me aprouver ter compaixão.

[[v45-9-16]]

^<<v45-9-16,16>>^ Assim, pois, não depende de quem quer ou de quem corre, mas de usar Deus a sua misericórdia.

[[v45-9-17]]

^<<v45-9-17,17>>^ Porque a Escritura diz a Faraó: Para isto mesmo te levantei, para mostrar em ti o meu poder e para que o meu nome seja anunciado por toda a terra.

[[v45-9-18]]

^<<v45-9-18,18>>^ Logo, tem ele misericórdia de quem quer e também endurece a quem lhe apraz.

[[v45-9-19]]

^<<v45-9-19,19>>^ Tu, porém, me dirás: De que se queixa ele ainda? Pois quem jamais resistiu à sua vontade?

[[v45-9-20]]

^<<v45-9-20,20>>^ Quem és tu, ó homem, para discutires com Deus?! Porventura, pode o objeto perguntar a quem o fez: Por que me fizeste assim?

[[v45-9-21]]

^<<v45-9-21,21>>^ Ou não tem o oleiro direito sobre a massa, para do mesmo barro fazer um vaso para honra e outro, para desonra?

[[v45-9-22]]

^<<v45-9-22,22>>^ Que diremos, pois, se Deus, querendo mostrar a sua ira e dar a conhecer o seu poder, suportou com muita longanimidade os vasos de ira, preparados para a perdição,

[[v45-9-23]]

^<<v45-9-23,23>>^ a fim de que também desse a conhecer as riquezas da sua glória em vasos de misericórdia, que para glória preparou de antemão,

[[v45-9-24]]

^<<v45-9-24,24>>^ os quais somos nós, a quem também chamou, não só dentre os judeus, mas também dentre os gentios?

[[v45-9-25]]

^<<v45-9-25,25>>^ Assim como também diz em Oseias: Chamarei povo meu ao que não era meu povo; e amada, à que não era amada;

[[v45-9-26]]

^<<v45-9-26,26>>^ e no lugar em que se lhes disse: Vós não sois meu povo, ali mesmo serão chamados filhos do Deus vivo.

[[v45-9-27]]

^<<v45-9-27,27>>^ Mas, relativamente a Israel, dele clama Isaías: Ainda que o número dos filhos de Israel seja como a areia do mar, o remanescente é que será salvo.

[[v45-9-28]]

^<<v45-9-28,28>>^ Porque o Senhor cumprirá a sua palavra sobre a terra, cabalmente e em breve;

[[v45-9-29]]

^<<v45-9-29,29>>^ como Isaías já disse: Se o Senhor dos Exércitos não nos tivesse deixado descendência, ter-nos-íamos tornado como Sodoma e semelhantes a Gomorra.

[[v45-9-30]]

^<<v45-9-30,30>>^ Que diremos, pois? Que os gentios, que não buscavam a justificação, vieram a alcançá-la, todavia, a que decorre da fé;

[[v45-9-31]]

^<<v45-9-31,31>>^ e Israel, que buscava a lei de justiça, não chegou a atingir essa lei.

[[v45-9-32]]

^<<v45-9-32,32>>^ Por quê? Porque não decorreu da fé, e sim como que das obras. Tropeçaram na pedra de tropeço,

[[v45-9-33]]

^<<v45-9-33,33>>^ como está escrito: Eis que ponho em Sião uma pedra de tropeço e rocha de escândalo, e aquele que nela crê não será confundido.

'''

xref:045-romanos/045-romanos-008.adoc#v45-8-0[&#60; Capítulo Anterior] | <<v45-9-0,Topo>> | xref:045-romanos/045-romanos-010.adoc#v45-10-0[Próximo Capítulo &#62;]