include::./index.adoc[]

[[v45-8-0]]
=== Romanos, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v45-8-1]]

^<<v45-8-1,1>>^ Agora, pois, já nenhuma condenação há para os que estão em Cristo Jesus.

[[v45-8-2]]

^<<v45-8-2,2>>^ Porque a lei do Espírito da vida, em Cristo Jesus, te livrou da lei do pecado e da morte.

[[v45-8-3]]

^<<v45-8-3,3>>^ Porquanto o que fora impossível à lei, no que estava enferma pela carne, isso fez Deus enviando o seu próprio Filho em semelhança de carne pecaminosa e no tocante ao pecado; e, com efeito, condenou Deus, na carne, o pecado,

[[v45-8-4]]

^<<v45-8-4,4>>^ a fim de que o preceito da lei se cumprisse em nós, que não andamos segundo a carne, mas segundo o Espírito.

[[v45-8-5]]

^<<v45-8-5,5>>^ Porque os que se inclinam para a carne cogitam das coisas da carne; mas os que se inclinam para o Espírito, das coisas do Espírito.

[[v45-8-6]]

^<<v45-8-6,6>>^ Porque o pendor da carne dá para a morte, mas o do Espírito, para a vida e paz.

[[v45-8-7]]

^<<v45-8-7,7>>^ Por isso, o pendor da carne é inimizade contra Deus, pois não está sujeito à lei de Deus, nem mesmo pode estar.

[[v45-8-8]]

^<<v45-8-8,8>>^ Portanto, os que estão na carne não podem agradar a Deus.

[[v45-8-9]]

^<<v45-8-9,9>>^ Vós, porém, não estais na carne, mas no Espírito, se, de fato, o Espírito de Deus habita em vós. E, se alguém não tem o Espírito de Cristo, esse tal não é dele.

[[v45-8-10]]

^<<v45-8-10,10>>^ Se, porém, Cristo está em vós, o corpo, na verdade, está morto por causa do pecado, mas o espírito é vida, por causa da justiça.

[[v45-8-11]]

^<<v45-8-11,11>>^ Se habita em vós o Espírito daquele que ressuscitou a Jesus dentre os mortos, esse mesmo que ressuscitou a Cristo Jesus dentre os mortos vivificará também o vosso corpo mortal, por meio do seu Espírito, que em vós habita.

[[v45-8-12]]

^<<v45-8-12,12>>^ Assim, pois, irmãos, somos devedores, não à carne como se constrangidos a viver segundo a carne.

[[v45-8-13]]

^<<v45-8-13,13>>^ Porque, se viverdes segundo a carne, caminhais para a morte; mas, se, pelo Espírito, mortificardes os feitos do corpo, certamente, vivereis.

[[v45-8-14]]

^<<v45-8-14,14>>^ Pois todos os que são guiados pelo Espírito de Deus são filhos de Deus.

[[v45-8-15]]

^<<v45-8-15,15>>^ Porque não recebestes o espírito de escravidão, para viverdes, outra vez, atemorizados, mas recebestes o espírito de adoção, baseados no qual clamamos: Aba, Pai.

[[v45-8-16]]

^<<v45-8-16,16>>^ O próprio Espírito testifica com o nosso espírito que somos filhos de Deus.

[[v45-8-17]]

^<<v45-8-17,17>>^ Ora, se somos filhos, somos também herdeiros, herdeiros de Deus e coerdeiros com Cristo; se com ele sofremos, também com ele seremos glorificados.

[[v45-8-18]]

^<<v45-8-18,18>>^ Porque para mim tenho por certo que os sofrimentos do tempo presente não podem ser comparados com a glória a ser revelada em nós.

[[v45-8-19]]

^<<v45-8-19,19>>^ A ardente expectativa da criação aguarda a revelação dos filhos de Deus.

[[v45-8-20]]

^<<v45-8-20,20>>^ Pois a criação está sujeita à vaidade, não voluntariamente, mas por causa daquele que a sujeitou,

[[v45-8-21]]

^<<v45-8-21,21>>^ na esperança de que a própria criação será redimida do cativeiro da corrupção, para a liberdade da glória dos filhos de Deus.

[[v45-8-22]]

^<<v45-8-22,22>>^ Porque sabemos que toda a criação, a um só tempo, geme e suporta angústias até agora.

[[v45-8-23]]

^<<v45-8-23,23>>^ E não somente ela, mas também nós, que temos as primícias do Espírito, igualmente gememos em nosso íntimo, aguardando a adoção de filhos, a redenção do nosso corpo.

[[v45-8-24]]

^<<v45-8-24,24>>^ Porque, na esperança, fomos salvos. Ora, esperança que se vê não é esperança; pois o que alguém vê, como o espera?

[[v45-8-25]]

^<<v45-8-25,25>>^ Mas, se esperamos o que não vemos, com paciência o aguardamos.

[[v45-8-26]]

^<<v45-8-26,26>>^ Também o Espírito, semelhantemente, nos assiste em nossa fraqueza; porque não sabemos orar como convém, mas o mesmo Espírito intercede por nós sobremaneira, com gemidos inexprimíveis.

[[v45-8-27]]

^<<v45-8-27,27>>^ E aquele que sonda os corações sabe qual é a mente do Espírito, porque segundo a vontade de Deus é que ele intercede pelos santos.

[[v45-8-28]]

^<<v45-8-28,28>>^ Sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus, daqueles que são chamados segundo o seu propósito.

[[v45-8-29]]

^<<v45-8-29,29>>^ Porquanto aos que de antemão conheceu, também os predestinou para serem conformes à imagem de seu Filho, a fim de que ele seja o primogênito entre muitos irmãos.

[[v45-8-30]]

^<<v45-8-30,30>>^ E aos que predestinou, a esses também chamou; e aos que chamou, a esses também justificou; e aos que justificou, a esses também glorificou.

[[v45-8-31]]

^<<v45-8-31,31>>^ Que diremos, pois, à vista destas coisas? Se Deus é por nós, quem será contra nós?

[[v45-8-32]]

^<<v45-8-32,32>>^ Aquele que não poupou o seu próprio Filho, antes, por todos nós o entregou, porventura, não nos dará graciosamente com ele todas as coisas?

[[v45-8-33]]

^<<v45-8-33,33>>^ Quem intentará acusação contra os eleitos de Deus? É Deus quem os justifica.

[[v45-8-34]]

^<<v45-8-34,34>>^ Quem os condenará? É Cristo Jesus quem morreu ou, antes, quem ressuscitou, o qual está à direita de Deus e também intercede por nós.

[[v45-8-35]]

^<<v45-8-35,35>>^ Quem nos separará do amor de Cristo? Será tribulação, ou angústia, ou perseguição, ou fome, ou nudez, ou perigo, ou espada?

[[v45-8-36]]

^<<v45-8-36,36>>^ Como está escrito: Por amor de ti, somos entregues à morte o dia todo, fomos considerados como ovelhas para o matadouro.

[[v45-8-37]]

^<<v45-8-37,37>>^ Em todas estas coisas, porém, somos mais que vencedores, por meio daquele que nos amou.

[[v45-8-38]]

^<<v45-8-38,38>>^ Porque eu estou bem certo de que nem a morte, nem a vida, nem os anjos, nem os principados, nem as coisas do presente, nem do porvir, nem os poderes,

[[v45-8-39]]

^<<v45-8-39,39>>^ nem a altura, nem a profundidade, nem qualquer outra criatura poderá separar-nos do amor de Deus, que está em Cristo Jesus, nosso Senhor.

'''

xref:045-romanos/045-romanos-007.adoc#v45-7-0[&#60; Capítulo Anterior] | <<v45-8-0,Topo>> | xref:045-romanos/045-romanos-009.adoc#v45-9-0[Próximo Capítulo &#62;]