include::./index.adoc[]

[[v45-3-0]]
=== Romanos, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v45-3-1]]

^<<v45-3-1,1>>^ Qual é, pois, a vantagem do judeu? Ou qual a utilidade da circuncisão?

[[v45-3-2]]

^<<v45-3-2,2>>^ Muita, sob todos os aspectos. Principalmente porque aos judeus foram confiados os oráculos de Deus.

[[v45-3-3]]

^<<v45-3-3,3>>^ E daí? Se alguns não creram, a incredulidade deles virá desfazer a fidelidade de Deus?

[[v45-3-4]]

^<<v45-3-4,4>>^ De maneira nenhuma! Seja Deus verdadeiro, e mentiroso, todo homem, segundo está escrito: Para seres justificado nas tuas palavras e venhas a vencer quando fores julgado.

[[v45-3-5]]

^<<v45-3-5,5>>^ Mas, se a nossa injustiça traz a lume a justiça de Deus, que diremos? Porventura, será Deus injusto por aplicar a sua ira? (Falo como homem.)

[[v45-3-6]]

^<<v45-3-6,6>>^ Certo que não. Do contrário, como julgará Deus o mundo?

[[v45-3-7]]

^<<v45-3-7,7>>^ E, se por causa da minha mentira, fica em relevo a verdade de Deus para a sua glória, por que sou eu ainda condenado como pecador?

[[v45-3-8]]

^<<v45-3-8,8>>^ E por que não dizemos, como alguns, caluniosamente, afirmam que o fazemos: Pratiquemos males para que venham bens? A condenação destes é justa.

[[v45-3-9]]

^<<v45-3-9,9>>^ Que se conclui? Temos nós qualquer vantagem? Não, de forma nenhuma; pois já temos demonstrado que todos, tanto judeus como gregos, estão debaixo do pecado;

[[v45-3-10]]

^<<v45-3-10,10>>^ como está escrito: Não há justo, nem um sequer,

[[v45-3-11]]

^<<v45-3-11,11>>^ não há quem entenda, não há quem busque a Deus;

[[v45-3-12]]

^<<v45-3-12,12>>^ todos se extraviaram, à uma se fizeram inúteis; não há quem faça o bem, não há nem um sequer.

[[v45-3-13]]

^<<v45-3-13,13>>^ A garganta deles é sepulcro aberto; com a língua, urdem engano, veneno de víbora está nos seus lábios,

[[v45-3-14]]

^<<v45-3-14,14>>^ a boca, eles a têm cheia de maldição e de amargura;

[[v45-3-15]]

^<<v45-3-15,15>>^ são os seus pés velozes para derramar sangue,

[[v45-3-16]]

^<<v45-3-16,16>>^ nos seus caminhos, há destruição e miséria;

[[v45-3-17]]

^<<v45-3-17,17>>^ desconheceram o caminho da paz.

[[v45-3-18]]

^<<v45-3-18,18>>^ Não há temor de Deus diante de seus olhos.

[[v45-3-19]]

^<<v45-3-19,19>>^ Ora, sabemos que tudo o que a lei diz, aos que vivem na lei o diz para que se cale toda boca, e todo o mundo seja culpável perante Deus,

[[v45-3-20]]

^<<v45-3-20,20>>^ visto que ninguém será justificado diante dele por obras da lei, em razão de que pela lei vem o pleno conhecimento do pecado.

[[v45-3-21]]

^<<v45-3-21,21>>^ Mas agora, sem lei, se manifestou a justiça de Deus testemunhada pela lei e pelos profetas;

[[v45-3-22]]

^<<v45-3-22,22>>^ justiça de Deus mediante a fé em Jesus Cristo, para todos [e sobre todos] os que creem; porque não há distinção,

[[v45-3-23]]

^<<v45-3-23,23>>^ pois todos pecaram e carecem da glória de Deus,

[[v45-3-24]]

^<<v45-3-24,24>>^ sendo justificados gratuitamente, por sua graça, mediante a redenção que há em Cristo Jesus,

[[v45-3-25]]

^<<v45-3-25,25>>^ a quem Deus propôs, no seu sangue, como propiciação, mediante a fé, para manifestar a sua justiça, por ter Deus, na sua tolerância, deixado impunes os pecados anteriormente cometidos;

[[v45-3-26]]

^<<v45-3-26,26>>^ tendo em vista a manifestação da sua justiça no tempo presente, para ele mesmo ser justo e o justificador daquele que tem fé em Jesus.

[[v45-3-27]]

^<<v45-3-27,27>>^ Onde, pois, a jactância? Foi de todo excluída. Por que lei? Das obras? Não; pelo contrário, pela lei da fé.

[[v45-3-28]]

^<<v45-3-28,28>>^ Concluímos, pois, que o homem é justificado pela fé, independentemente das obras da lei.

[[v45-3-29]]

^<<v45-3-29,29>>^ É, porventura, Deus somente dos judeus? Não o é também dos gentios? Sim, também dos gentios,

[[v45-3-30]]

^<<v45-3-30,30>>^ visto que Deus é um só, o qual justificará, por fé, o circunciso e, mediante a fé, o incircunciso.

[[v45-3-31]]

^<<v45-3-31,31>>^ Anulamos, pois, a lei pela fé? Não, de maneira nenhuma! Antes, confirmamos a lei.

'''

xref:045-romanos/045-romanos-002.adoc#v45-2-0[&#60; Capítulo Anterior] | <<v45-3-0,Topo>> | xref:045-romanos/045-romanos-004.adoc#v45-4-0[Próximo Capítulo &#62;]