include::./index.adoc[]

[[v45-10-0]]
=== Romanos, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v45-10-1]]

^<<v45-10-1,1>>^ Irmãos, a boa vontade do meu coração e a minha súplica a Deus a favor deles são para que sejam salvos.

[[v45-10-2]]

^<<v45-10-2,2>>^ Porque lhes dou testemunho de que eles têm zelo por Deus, porém não com entendimento.

[[v45-10-3]]

^<<v45-10-3,3>>^ Porquanto, desconhecendo a justiça de Deus e procurando estabelecer a sua própria, não se sujeitaram à que vem de Deus.

[[v45-10-4]]

^<<v45-10-4,4>>^ Porque o fim da lei é Cristo, para justiça de todo aquele que crê.

[[v45-10-5]]

^<<v45-10-5,5>>^ Ora, Moisés escreveu que o homem que praticar a justiça decorrente da lei viverá por ela.

[[v45-10-6]]

^<<v45-10-6,6>>^ Mas a justiça decorrente da fé assim diz: Não perguntes em teu coração: Quem subirá ao céu?, isto é, para trazer do alto a Cristo;

[[v45-10-7]]

^<<v45-10-7,7>>^ ou: Quem descerá ao abismo?, isto é, para levantar Cristo dentre os mortos.

[[v45-10-8]]

^<<v45-10-8,8>>^ Porém que se diz? A palavra está perto de ti, na tua boca e no teu coração; isto é, a palavra da fé que pregamos.

[[v45-10-9]]

^<<v45-10-9,9>>^ Se, com a tua boca, confessares Jesus como Senhor e, em teu coração, creres que Deus o ressuscitou dentre os mortos, serás salvo.

[[v45-10-10]]

^<<v45-10-10,10>>^ Porque com o coração se crê para justiça e com a boca se confessa a respeito da salvação.

[[v45-10-11]]

^<<v45-10-11,11>>^ Porquanto a Escritura diz: Todo aquele que nele crê não será confundido.

[[v45-10-12]]

^<<v45-10-12,12>>^ Pois não há distinção entre judeu e grego, uma vez que o mesmo é o Senhor de todos, rico para com todos os que o invocam.

[[v45-10-13]]

^<<v45-10-13,13>>^ Porque: Todo aquele que invocar o nome do Senhor será salvo.

[[v45-10-14]]

^<<v45-10-14,14>>^ Como, porém, invocarão aquele em quem não creram? E como crerão naquele de quem nada ouviram? E como ouvirão, se não há quem pregue?

[[v45-10-15]]

^<<v45-10-15,15>>^ E como pregarão, se não forem enviados? Como está escrito: Quão formosos são os pés dos que anunciam coisas boas!

[[v45-10-16]]

^<<v45-10-16,16>>^ Mas nem todos obedeceram ao evangelho; pois Isaías diz: Senhor, quem acreditou na nossa pregação?

[[v45-10-17]]

^<<v45-10-17,17>>^ E, assim, a fé vem pela pregação, e a pregação, pela palavra de Cristo.

[[v45-10-18]]

^<<v45-10-18,18>>^ Mas pergunto: Porventura, não ouviram? Sim, por certo: Por toda a terra se fez ouvir a sua voz, e as suas palavras, até aos confins do mundo.

[[v45-10-19]]

^<<v45-10-19,19>>^ Pergunto mais: Porventura, não terá chegado isso ao conhecimento de Israel? Moisés já dizia: Eu vos porei em ciúmes com um povo que não é nação, com gente insensata eu vos provocarei à ira.

[[v45-10-20]]

^<<v45-10-20,20>>^ E Isaías a mais se atreve e diz: Fui achado pelos que não me procuravam, revelei-me aos que não perguntavam por mim.

[[v45-10-21]]

^<<v45-10-21,21>>^ Quanto a Israel, porém, diz: Todo o dia estendi as mãos a um povo rebelde e contradizente.

'''

xref:045-romanos/045-romanos-009.adoc#v45-9-0[&#60; Capítulo Anterior] | <<v45-10-0,Topo>> | xref:045-romanos/045-romanos-011.adoc#v45-11-0[Próximo Capítulo &#62;]