include::./index.adoc[]

[[v45-7-0]]
=== Romanos, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v45-7-1]]

^<<v45-7-1,1>>^ Porventura, ignorais, irmãos (pois falo aos que conhecem a lei), que a lei tem domínio sobre o homem toda a sua vida?

[[v45-7-2]]

^<<v45-7-2,2>>^ Ora, a mulher casada está ligada pela lei ao marido, enquanto ele vive; mas, se o mesmo morrer, desobrigada ficará da lei conjugal.

[[v45-7-3]]

^<<v45-7-3,3>>^ De sorte que será considerada adúltera se, vivendo ainda o marido, unir-se com outro homem; porém, se morrer o marido, estará livre da lei e não será adúltera se contrair novas núpcias.

[[v45-7-4]]

^<<v45-7-4,4>>^ Assim, meus irmãos, também vós morrestes relativamente à lei, por meio do corpo de Cristo, para pertencerdes a outro, a saber, aquele que ressuscitou dentre os mortos, a fim de que frutifiquemos para Deus.

[[v45-7-5]]

^<<v45-7-5,5>>^ Porque, quando vivíamos segundo a carne, as paixões pecaminosas postas em realce pela lei operavam em nossos membros, a fim de frutificarem para a morte.

[[v45-7-6]]

^<<v45-7-6,6>>^ Agora, porém, libertados da lei, estamos mortos para aquilo a que estávamos sujeitos, de modo que servimos em novidade de espírito e não na caducidade da letra.

[[v45-7-7]]

^<<v45-7-7,7>>^ Que diremos, pois? É a lei pecado? De modo nenhum! Mas eu não teria conhecido o pecado, senão por intermédio da lei; pois não teria eu conhecido a cobiça, se a lei não dissera: Não cobiçarás.

[[v45-7-8]]

^<<v45-7-8,8>>^ Mas o pecado, tomando ocasião pelo mandamento, despertou em mim toda sorte de concupiscência; porque, sem lei, está morto o pecado.

[[v45-7-9]]

^<<v45-7-9,9>>^ Outrora, sem a lei, eu vivia; mas, sobrevindo o preceito, reviveu o pecado, e eu morri.

[[v45-7-10]]

^<<v45-7-10,10>>^ E o mandamento que me fora para vida, verifiquei que este mesmo se me tornou para morte.

[[v45-7-11]]

^<<v45-7-11,11>>^ Porque o pecado, prevalecendo-se do mandamento, pelo mesmo mandamento, me enganou e me matou.

[[v45-7-12]]

^<<v45-7-12,12>>^ Por conseguinte, a lei é santa; e o mandamento, santo, e justo, e bom.

[[v45-7-13]]

^<<v45-7-13,13>>^ Acaso o bom se me tornou em morte? De modo nenhum! Pelo contrário, o pecado, para revelar-se como pecado, por meio de uma coisa boa, causou-me a morte, a fim de que, pelo mandamento, se mostrasse sobremaneira maligno.

[[v45-7-14]]

^<<v45-7-14,14>>^ Porque bem sabemos que a lei é espiritual; eu, todavia, sou carnal, vendido à escravidão do pecado.

[[v45-7-15]]

^<<v45-7-15,15>>^ Porque nem mesmo compreendo o meu próprio modo de agir, pois não faço o que prefiro, e sim o que detesto.

[[v45-7-16]]

^<<v45-7-16,16>>^ Ora, se faço o que não quero, consinto com a lei, que é boa.

[[v45-7-17]]

^<<v45-7-17,17>>^ Neste caso, quem faz isto já não sou eu, mas o pecado que habita em mim.

[[v45-7-18]]

^<<v45-7-18,18>>^ Porque eu sei que em mim, isto é, na minha carne, não habita bem nenhum, pois o querer o bem está em mim; não, porém, o efetuá-lo.

[[v45-7-19]]

^<<v45-7-19,19>>^ Porque não faço o bem que prefiro, mas o mal que não quero, esse faço.

[[v45-7-20]]

^<<v45-7-20,20>>^ Mas, se eu faço o que não quero, já não sou eu quem o faz, e sim o pecado que habita em mim.

[[v45-7-21]]

^<<v45-7-21,21>>^ Então, ao querer fazer o bem, encontro a lei de que o mal reside em mim.

[[v45-7-22]]

^<<v45-7-22,22>>^ Porque, no tocante ao homem interior, tenho prazer na lei de Deus;

[[v45-7-23]]

^<<v45-7-23,23>>^ mas vejo, nos meus membros, outra lei que, guerreando contra a lei da minha mente, me faz prisioneiro da lei do pecado que está nos meus membros.

[[v45-7-24]]

^<<v45-7-24,24>>^ Desventurado homem que sou! Quem me livrará do corpo desta morte?

[[v45-7-25]]

^<<v45-7-25,25>>^ Graças a Deus por Jesus Cristo, nosso Senhor. De maneira que eu, de mim mesmo, com a mente, sou escravo da lei de Deus, mas, segundo a carne, da lei do pecado.

'''

xref:045-romanos/045-romanos-006.adoc#v45-6-0[&#60; Capítulo Anterior] | <<v45-7-0,Topo>> | xref:045-romanos/045-romanos-008.adoc#v45-8-0[Próximo Capítulo &#62;]