include::./index.adoc[]

[[v45-14-0]]
=== Romanos, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v45-14-1]]

^<<v45-14-1,1>>^ Acolhei ao que é débil na fé, não, porém, para discutir opiniões.

[[v45-14-2]]

^<<v45-14-2,2>>^ Um crê que de tudo pode comer, mas o débil come legumes;

[[v45-14-3]]

^<<v45-14-3,3>>^ quem come não despreze o que não come; e o que não come não julgue o que come, porque Deus o acolheu.

[[v45-14-4]]

^<<v45-14-4,4>>^ Quem és tu que julgas o servo alheio? Para o seu próprio senhor está em pé ou cai; mas estará em pé, porque o Senhor é poderoso para o suster.

[[v45-14-5]]

^<<v45-14-5,5>>^ Um faz diferença entre dia e dia; outro julga iguais todos os dias. Cada um tenha opinião bem-definida em sua própria mente.

[[v45-14-6]]

^<<v45-14-6,6>>^ Quem distingue entre dia e dia para o Senhor o faz; e quem come para o Senhor come, porque dá graças a Deus; e quem não come para o Senhor não come e dá graças a Deus.

[[v45-14-7]]

^<<v45-14-7,7>>^ Porque nenhum de nós vive para si mesmo, nem morre para si.

[[v45-14-8]]

^<<v45-14-8,8>>^ Porque, se vivemos, para o Senhor vivemos; se morremos, para o Senhor morremos. Quer, pois, vivamos ou morramos, somos do Senhor.

[[v45-14-9]]

^<<v45-14-9,9>>^ Foi precisamente para esse fim que Cristo morreu e ressurgiu: para ser Senhor tanto de mortos como de vivos.

[[v45-14-10]]

^<<v45-14-10,10>>^ Tu, porém, por que julgas teu irmão? E tu, por que desprezas o teu? Pois todos compareceremos perante o tribunal de Deus.

[[v45-14-11]]

^<<v45-14-11,11>>^ Como está escrito: Por minha vida, diz o Senhor, diante de mim se dobrará todo joelho, e toda língua dará louvores a Deus.

[[v45-14-12]]

^<<v45-14-12,12>>^ Assim, pois, cada um de nós dará contas de si mesmo a Deus.

[[v45-14-13]]

^<<v45-14-13,13>>^ Não nos julguemos mais uns aos outros; pelo contrário, tomai o propósito de não pordes tropeço ou escândalo ao vosso irmão.

[[v45-14-14]]

^<<v45-14-14,14>>^ Eu sei e estou persuadido, no Senhor Jesus, de que nenhuma coisa é de si mesma impura, salvo para aquele que assim a considera; para esse é impura.

[[v45-14-15]]

^<<v45-14-15,15>>^ Se, por causa de comida, o teu irmão se entristece, já não andas segundo o amor fraternal. Por causa da tua comida, não faças perecer aquele a favor de quem Cristo morreu.

[[v45-14-16]]

^<<v45-14-16,16>>^ Não seja, pois, vituperado o vosso bem.

[[v45-14-17]]

^<<v45-14-17,17>>^ Porque o reino de Deus não é comida nem bebida, mas justiça, e paz, e alegria no Espírito Santo.

[[v45-14-18]]

^<<v45-14-18,18>>^ Aquele que deste modo serve a Cristo é agradável a Deus e aprovado pelos homens.

[[v45-14-19]]

^<<v45-14-19,19>>^ Assim, pois, seguimos as coisas da paz e também as da edificação de uns para com os outros.

[[v45-14-20]]

^<<v45-14-20,20>>^ Não destruas a obra de Deus por causa da comida. Todas as coisas, na verdade, são limpas, mas é mau para o homem o comer com escândalo.

[[v45-14-21]]

^<<v45-14-21,21>>^ É bom não comer carne, nem beber vinho, nem fazer qualquer outra coisa com que teu irmão venha a tropeçar [ou se ofender ou se enfraquecer].

[[v45-14-22]]

^<<v45-14-22,22>>^ A fé que tens, tem-na para ti mesmo perante Deus. Bem-aventurado é aquele que não se condena naquilo que aprova.

[[v45-14-23]]

^<<v45-14-23,23>>^ Mas aquele que tem dúvidas é condenado se comer, porque o que faz não provém de fé; e tudo o que não provém de fé é pecado.

'''

xref:045-romanos/045-romanos-013.adoc#v45-13-0[&#60; Capítulo Anterior] | <<v45-14-0,Topo>> | xref:045-romanos/045-romanos-015.adoc#v45-15-0[Próximo Capítulo &#62;]