include::./index.adoc[]

[[v45-11-0]]
=== Romanos, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v45-11-1]]

^<<v45-11-1,1>>^ Pergunto, pois: terá Deus, porventura, rejeitado o seu povo? De modo nenhum! Porque eu também sou israelita da descendência de Abraão, da tribo de Benjamim.

[[v45-11-2]]

^<<v45-11-2,2>>^ Deus não rejeitou o seu povo, a quem de antemão conheceu. Ou não sabeis o que a Escritura refere a respeito de Elias, como insta perante Deus contra Israel, dizendo:

[[v45-11-3]]

^<<v45-11-3,3>>^ Senhor, mataram os teus profetas, arrasaram os teus altares, e só eu fiquei, e procuram tirar-me a vida.

[[v45-11-4]]

^<<v45-11-4,4>>^ Que lhe disse, porém, a resposta divina? Reservei para mim sete mil homens, que não dobraram os joelhos diante de Baal.

[[v45-11-5]]

^<<v45-11-5,5>>^ Assim, pois, também agora, no tempo de hoje, sobrevive um remanescente segundo a eleição da graça.

[[v45-11-6]]

^<<v45-11-6,6>>^ E, se é pela graça, já não é pelas obras; do contrário, a graça já não é graça.

[[v45-11-7]]

^<<v45-11-7,7>>^ Que diremos, pois? O que Israel busca, isso não conseguiu; mas a eleição o alcançou; e os mais foram endurecidos,

[[v45-11-8]]

^<<v45-11-8,8>>^ como está escrito: Deus lhes deu espírito de entorpecimento, olhos para não ver e ouvidos para não ouvir, até ao dia de hoje.

[[v45-11-9]]

^<<v45-11-9,9>>^ E diz Davi: Torne-se-lhes a mesa em laço e armadilha, em tropeço e punição;

[[v45-11-10]]

^<<v45-11-10,10>>^ escureçam-se-lhes os olhos, para que não vejam, e fiquem para sempre encurvadas as suas costas.

[[v45-11-11]]

^<<v45-11-11,11>>^ Pergunto, pois: porventura, tropeçaram para que caíssem? De modo nenhum! Mas, pela sua transgressão, veio a salvação aos gentios, para pô-los em ciúmes.

[[v45-11-12]]

^<<v45-11-12,12>>^ Ora, se a transgressão deles redundou em riqueza para o mundo, e o seu abatimento, em riqueza para os gentios, quanto mais a sua plenitude!

[[v45-11-13]]

^<<v45-11-13,13>>^ Dirijo-me a vós outros, que sois gentios! Visto, pois, que eu sou apóstolo dos gentios, glorifico o meu ministério,

[[v45-11-14]]

^<<v45-11-14,14>>^ para ver se, de algum modo, posso incitar à emulação os do meu povo e salvar alguns deles.

[[v45-11-15]]

^<<v45-11-15,15>>^ Porque, se o fato de terem sido eles rejeitados trouxe reconciliação ao mundo, que será o seu restabelecimento, senão vida dentre os mortos?

[[v45-11-16]]

^<<v45-11-16,16>>^ E, se forem santas as primícias da massa, igualmente o será a sua totalidade; se for santa a raiz, também os ramos o serão.

[[v45-11-17]]

^<<v45-11-17,17>>^ Se, porém, alguns dos ramos foram quebrados, e tu, sendo oliveira brava, foste enxertado em meio deles e te tornaste participante da raiz e da seiva da oliveira,

[[v45-11-18]]

^<<v45-11-18,18>>^ não te glories contra os ramos; porém, se te gloriares, sabe que não és tu que sustentas a raiz, mas a raiz, a ti.

[[v45-11-19]]

^<<v45-11-19,19>>^ Dirás, pois: Alguns ramos foram quebrados, para que eu fosse enxertado.

[[v45-11-20]]

^<<v45-11-20,20>>^ Bem! Pela sua incredulidade, foram quebrados; tu, porém, mediante a fé, estás firme. Não te ensoberbeças, mas teme.

[[v45-11-21]]

^<<v45-11-21,21>>^ Porque, se Deus não poupou os ramos naturais, também não te poupará.

[[v45-11-22]]

^<<v45-11-22,22>>^ Considerai, pois, a bondade e a severidade de Deus: para com os que caíram, severidade; mas, para contigo, a bondade de Deus, se nela permaneceres; doutra sorte, também tu serás cortado.

[[v45-11-23]]

^<<v45-11-23,23>>^ Eles também, se não permanecerem na incredulidade, serão enxertados; pois Deus é poderoso para os enxertar de novo.

[[v45-11-24]]

^<<v45-11-24,24>>^ Pois, se foste cortado da que, por natureza, era oliveira brava e, contra a natureza, enxertado em boa oliveira, quanto mais não serão enxertados na sua própria oliveira aqueles que são ramos naturais!

[[v45-11-25]]

^<<v45-11-25,25>>^ Porque não quero, irmãos, que ignoreis este mistério (para que não sejais presumidos em vós mesmos): que veio endurecimento em parte a Israel, até que haja entrado a plenitude dos gentios.

[[v45-11-26]]

^<<v45-11-26,26>>^ E, assim, todo o Israel será salvo, como está escrito: Virá de Sião o Libertador e ele apartará de Jacó as impiedades.

[[v45-11-27]]

^<<v45-11-27,27>>^ Esta é a minha aliança com eles, quando eu tirar os seus pecados.

[[v45-11-28]]

^<<v45-11-28,28>>^ Quanto ao evangelho, são eles inimigos por vossa causa; quanto, porém, à eleição, amados por causa dos patriarcas;

[[v45-11-29]]

^<<v45-11-29,29>>^ porque os dons e a vocação de Deus são irrevogáveis.

[[v45-11-30]]

^<<v45-11-30,30>>^ Porque assim como vós também, outrora, fostes desobedientes a Deus, mas, agora, alcançastes misericórdia, à vista da desobediência deles,

[[v45-11-31]]

^<<v45-11-31,31>>^ assim também estes, agora, foram desobedientes, para que, igualmente, eles alcancem misericórdia, à vista da que vos foi concedida.

[[v45-11-32]]

^<<v45-11-32,32>>^ Porque Deus a todos encerrou na desobediência, a fim de usar de misericórdia para com todos.

[[v45-11-33]]

^<<v45-11-33,33>>^ Ó profundidade da riqueza, tanto da sabedoria como do conhecimento de Deus! Quão insondáveis são os seus juízos, e quão inescrutáveis, os seus caminhos!

[[v45-11-34]]

^<<v45-11-34,34>>^ Quem, pois, conheceu a mente do Senhor? Ou quem foi o seu conselheiro?

[[v45-11-35]]

^<<v45-11-35,35>>^ Ou quem primeiro deu a ele para que lhe venha a ser restituído?

[[v45-11-36]]

^<<v45-11-36,36>>^ Porque dele, e por meio dele, e para ele são todas as coisas. A ele, pois, a glória eternamente. Amém!

'''

xref:045-romanos/045-romanos-010.adoc#v45-10-0[&#60; Capítulo Anterior] | <<v45-11-0,Topo>> | xref:045-romanos/045-romanos-012.adoc#v45-12-0[Próximo Capítulo &#62;]