include::./index.adoc[]

[[v52-3-0]]
=== 1 Tessalonicenses, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v52-3-1]]

^<<v52-3-1,1>>^ Pelo que, não podendo suportar mais o cuidado por vós, pareceu-nos bem ficar sozinhos em Atenas;

[[v52-3-2]]

^<<v52-3-2,2>>^ e enviamos nosso irmão Timóteo, ministro de Deus no evangelho de Cristo, para, em benefício da vossa fé, confirmar-vos e exortar-vos,

[[v52-3-3]]

^<<v52-3-3,3>>^ a fim de que ninguém se inquiete com estas tribulações. Porque vós mesmos sabeis que estamos designados para isto;

[[v52-3-4]]

^<<v52-3-4,4>>^ pois, quando ainda estávamos convosco, predissemos que íamos ser afligidos, o que, de fato, aconteceu e é do vosso conhecimento.

[[v52-3-5]]

^<<v52-3-5,5>>^ Foi por isso que, já não me sendo possível continuar esperando, mandei indagar o estado da vossa fé, temendo que o Tentador vos provasse, e se tornasse inútil o nosso labor.

[[v52-3-6]]

^<<v52-3-6,6>>^ Agora, porém, com o regresso de Timóteo, vindo do vosso meio, trazendo-nos boas notícias da vossa fé e do vosso amor, e, ainda, de que sempre guardais grata lembrança de nós, desejando muito ver-nos, como, aliás, também nós a vós outros,

[[v52-3-7]]

^<<v52-3-7,7>>^ sim, irmãos, por isso, fomos consolados acerca de vós, pela vossa fé, apesar de todas as nossas privações e tribulação,

[[v52-3-8]]

^<<v52-3-8,8>>^ porque, agora, vivemos, se é que estais firmados no Senhor.

[[v52-3-9]]

^<<v52-3-9,9>>^ Pois que ações de graças podemos tributar a Deus no tocante a vós outros, por toda a alegria com que nos regozijamos por vossa causa, diante do nosso Deus,

[[v52-3-10]]

^<<v52-3-10,10>>^ orando noite e dia, com máximo empenho, para vos ver pessoalmente e reparar as deficiências da vossa fé?

[[v52-3-11]]

^<<v52-3-11,11>>^ Ora, o nosso mesmo Deus e Pai, e Jesus, nosso Senhor, dirijam-nos o caminho até vós,

[[v52-3-12]]

^<<v52-3-12,12>>^ e o Senhor vos faça crescer e aumentar no amor uns para com os outros e para com todos, como também nós para convosco,

[[v52-3-13]]

^<<v52-3-13,13>>^ a fim de que seja o vosso coração confirmado em santidade, isento de culpa, na presença de nosso Deus e Pai, na vinda de nosso Senhor Jesus, com todos os seus santos.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-002.adoc#v52-2-0[&#60; Capítulo Anterior] | <<v52-3-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-004.adoc#v52-4-0[Próximo Capítulo &#62;]