include::./index.adoc[]

[[v52-2-0]]
=== 1 Tessalonicenses, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v52-2-1]]

^<<v52-2-1,1>>^ Porque vós, irmãos, sabeis, pessoalmente, que a nossa estada entre vós não se tornou infrutífera;

[[v52-2-2]]

^<<v52-2-2,2>>^ mas, apesar de maltratados e ultrajados em Filipos, como é do vosso conhecimento, tivemos ousada confiança em nosso Deus, para vos anunciar o evangelho de Deus, em meio a muita luta.

[[v52-2-3]]

^<<v52-2-3,3>>^ Pois a nossa exortação não procede de engano, nem de impureza, nem se baseia em dolo;

[[v52-2-4]]

^<<v52-2-4,4>>^ pelo contrário, visto que fomos aprovados por Deus, a ponto de nos confiar ele o evangelho, assim falamos, não para que agrademos a homens, e sim a Deus, que prova o nosso coração.

[[v52-2-5]]

^<<v52-2-5,5>>^ A verdade é que nunca usamos de linguagem de bajulação, como sabeis, nem de intuitos gananciosos. Deus disto é testemunha.

[[v52-2-6]]

^<<v52-2-6,6>>^ Também jamais andamos buscando glória de homens, nem de vós, nem de outros.

[[v52-2-7]]

^<<v52-2-7,7>>^ Embora pudéssemos, como enviados de Cristo, exigir de vós a nossa manutenção, todavia, nos tornamos carinhosos entre vós, qual ama que acaricia os próprios filhos;

[[v52-2-8]]

^<<v52-2-8,8>>^ assim, querendo-vos muito, estávamos prontos a oferecer-vos não somente o evangelho de Deus, mas, igualmente, a própria vida; por isso que vos tornastes muito amados de nós.

[[v52-2-9]]

^<<v52-2-9,9>>^ Porque, vos recordais, irmãos, do nosso labor e fadiga; e de como, noite e dia labutando para não vivermos à custa de nenhum de vós, vos proclamamos o evangelho de Deus.

[[v52-2-10]]

^<<v52-2-10,10>>^ Vós e Deus sois testemunhas do modo por que piedosa, justa e irrepreensivelmente procedemos em relação a vós outros, que credes.

[[v52-2-11]]

^<<v52-2-11,11>>^ E sabeis, ainda, de que maneira, como pai a seus filhos, a cada um de vós,

[[v52-2-12]]

^<<v52-2-12,12>>^ exortamos, consolamos e admoestamos, para viverdes por modo digno de Deus, que vos chama para o seu reino e glória.

[[v52-2-13]]

^<<v52-2-13,13>>^ Outra razão ainda temos nós para, incessantemente, dar graças a Deus: é que, tendo vós recebido a palavra que de nós ouvistes, que é de Deus, acolhestes não como palavra de homens, e sim como, em verdade é, a palavra de Deus, a qual, com efeito, está operando eficazmente em vós, os que credes.

[[v52-2-14]]

^<<v52-2-14,14>>^ Tanto é assim, irmãos, que vos tornastes imitadores das igrejas de Deus existentes na Judeia em Cristo Jesus; porque também padecestes, da parte dos vossos patrícios, as mesmas coisas que eles, por sua vez, sofreram dos judeus,

[[v52-2-15]]

^<<v52-2-15,15>>^ os quais não somente mataram o Senhor Jesus e os profetas, como também nos perseguiram, e não agradam a Deus, e são adversários de todos os homens,

[[v52-2-16]]

^<<v52-2-16,16>>^ a ponto de nos impedirem de falar aos gentios para que estes sejam salvos, a fim de irem enchendo sempre a medida de seus pecados. A ira, porém, sobreveio contra eles, definitivamente.

[[v52-2-17]]

^<<v52-2-17,17>>^ Ora, nós, irmãos, orfanados, por breve tempo, de vossa presença, não, porém, do coração, com tanto mais empenho diligenciamos, com grande desejo, ir ver-vos pessoalmente.

[[v52-2-18]]

^<<v52-2-18,18>>^ Por isso, quisemos ir até vós (pelo menos eu, Paulo, não somente uma vez, mas duas); contudo, Satanás nos barrou o caminho.

[[v52-2-19]]

^<<v52-2-19,19>>^ Pois quem é a nossa esperança, ou alegria, ou coroa em que exultamos, na presença de nosso Senhor Jesus em sua vinda? Não sois vós?

[[v52-2-20]]

^<<v52-2-20,20>>^ Sim, vós sois realmente a nossa glória e a nossa alegria!

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[&#60; Capítulo Anterior] | <<v52-2-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-003.adoc#v52-3-0[Próximo Capítulo &#62;]