include::./index.adoc[]

[[v52-5-0]]
=== 1 Tessalonicenses, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v52-5-1]]

^<<v52-5-1,1>>^ Irmãos, relativamente aos tempos e às épocas, não há necessidade de que eu vos escreva;

[[v52-5-2]]

^<<v52-5-2,2>>^ pois vós mesmos estais inteirados com precisão de que o Dia do Senhor vem como ladrão de noite.

[[v52-5-3]]

^<<v52-5-3,3>>^ Quando andarem dizendo: Paz e segurança, eis que lhes sobrevirá repentina destruição, como vêm as dores de parto à que está para dar à luz; e de nenhum modo escaparão.

[[v52-5-4]]

^<<v52-5-4,4>>^ Mas vós, irmãos, não estais em trevas, para que esse Dia como ladrão vos apanhe de surpresa;

[[v52-5-5]]

^<<v52-5-5,5>>^ porquanto vós todos sois filhos da luz e filhos do dia; nós não somos da noite, nem das trevas.

[[v52-5-6]]

^<<v52-5-6,6>>^ Assim, pois, não durmamos como os demais; pelo contrário, vigiemos e sejamos sóbrios.

[[v52-5-7]]

^<<v52-5-7,7>>^ Ora, os que dormem dormem de noite, e os que se embriagam é de noite que se embriagam.

[[v52-5-8]]

^<<v52-5-8,8>>^ Nós, porém, que somos do dia, sejamos sóbrios, revestindo-nos da couraça da fé e do amor e tomando como capacete a esperança da salvação;

[[v52-5-9]]

^<<v52-5-9,9>>^ porque Deus não nos destinou para a ira, mas para alcançar a salvação mediante nosso Senhor Jesus Cristo,

[[v52-5-10]]

^<<v52-5-10,10>>^ que morreu por nós para que, quer vigiemos, quer durmamos, vivamos em união com ele.

[[v52-5-11]]

^<<v52-5-11,11>>^ Consolai-vos, pois, uns aos outros e edificai-vos reciprocamente, como também estais fazendo.

[[v52-5-12]]

^<<v52-5-12,12>>^ Agora, vos rogamos, irmãos, que acateis com apreço os que trabalham entre vós e os que vos presidem no Senhor e vos admoestam;

[[v52-5-13]]

^<<v52-5-13,13>>^ e que os tenhais com amor em máxima consideração, por causa do trabalho que realizam. Vivei em paz uns com os outros.

[[v52-5-14]]

^<<v52-5-14,14>>^ Exortamo-vos, também, irmãos, a que admoesteis os insubmissos, consoleis os desanimados, ampareis os fracos e sejais longânimos para com todos.

[[v52-5-15]]

^<<v52-5-15,15>>^ Evitai que alguém retribua a outrem mal por mal; pelo contrário, segui sempre o bem entre vós e para com todos.

[[v52-5-16]]

^<<v52-5-16,16>>^ Regozijai-vos sempre.

[[v52-5-17]]

^<<v52-5-17,17>>^ Orai sem cessar.

[[v52-5-18]]

^<<v52-5-18,18>>^ Em tudo, dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco.

[[v52-5-19]]

^<<v52-5-19,19>>^ Não apagueis o Espírito.

[[v52-5-20]]

^<<v52-5-20,20>>^ Não desprezeis as profecias;

[[v52-5-21]]

^<<v52-5-21,21>>^ julgai todas as coisas, retende o que é bom;

[[v52-5-22]]

^<<v52-5-22,22>>^ abstende-vos de toda forma de mal.

[[v52-5-23]]

^<<v52-5-23,23>>^ O mesmo Deus da paz vos santifique em tudo; e o vosso espírito, alma e corpo sejam conservados íntegros e irrepreensíveis na vinda de nosso Senhor Jesus Cristo.

[[v52-5-24]]

^<<v52-5-24,24>>^ Fiel é o que vos chama, o qual também o fará.

[[v52-5-25]]

^<<v52-5-25,25>>^ Irmãos, orai por nós.

[[v52-5-26]]

^<<v52-5-26,26>>^ Saudai todos os irmãos com ósculo santo.

[[v52-5-27]]

^<<v52-5-27,27>>^ Conjuro-vos, pelo Senhor, que esta epístola seja lida a todos os irmãos.

[[v52-5-28]]

^<<v52-5-28,28>>^ A graça de nosso Senhor Jesus Cristo seja convosco.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-004.adoc#v52-4-0[&#60; Capítulo Anterior] | <<v52-5-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-001.adoc#v53-1-0[Próximo Capítulo &#62;]