include::./index.adoc[]

[[v52-1-0]]
=== 1 Tessalonicenses, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v52-1-1]]

^<<v52-1-1,1>>^ Paulo, Silvano e Timóteo, à igreja dos tessalonicenses em Deus Pai e no Senhor Jesus Cristo, graça e paz a vós outros.

[[v52-1-2]]

^<<v52-1-2,2>>^ Damos, sempre, graças a Deus por todos vós, mencionando-vos em nossas orações e, sem cessar,

[[v52-1-3]]

^<<v52-1-3,3>>^ recordando-nos, diante do nosso Deus e Pai, da operosidade da vossa fé, da abnegação do vosso amor e da firmeza da vossa esperança em nosso Senhor Jesus Cristo,

[[v52-1-4]]

^<<v52-1-4,4>>^ reconhecendo, irmãos, amados de Deus, a vossa eleição,

[[v52-1-5]]

^<<v52-1-5,5>>^ porque o nosso evangelho não chegou até vós tão somente em palavra, mas, sobretudo, em poder, no Espírito Santo e em plena convicção, assim como sabeis ter sido o nosso procedimento entre vós e por amor de vós.

[[v52-1-6]]

^<<v52-1-6,6>>^ Com efeito, vos tornastes imitadores nossos e do Senhor, tendo recebido a palavra, posto que em meio de muita tribulação, com alegria do Espírito Santo,

[[v52-1-7]]

^<<v52-1-7,7>>^ de sorte que vos tornastes o modelo para todos os crentes na Macedônia e na Acaia.

[[v52-1-8]]

^<<v52-1-8,8>>^ Porque de vós repercutiu a palavra do Senhor não só na Macedônia e Acaia, mas também por toda parte se divulgou a vossa fé para com Deus, a tal ponto de não termos necessidade de acrescentar coisa alguma;

[[v52-1-9]]

^<<v52-1-9,9>>^ pois eles mesmos, no tocante a nós, proclamam que repercussão teve o nosso ingresso no vosso meio, e como, deixando os ídolos, vos convertestes a Deus, para servirdes o Deus vivo e verdadeiro

[[v52-1-10]]

^<<v52-1-10,10>>^ e para aguardardes dos céus o seu Filho, a quem ele ressuscitou dentre os mortos, Jesus, que nos livra da ira vindoura.

'''

xref:051-colossenses/051-colossenses-004.adoc#v51-4-0[&#60; Capítulo Anterior] | <<v52-1-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-002.adoc#v52-2-0[Próximo Capítulo &#62;]