include::./index.adoc[]

[[v18-32-0]]
=== Jó, 32
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-32-1]]

^<<v18-32-1,1>>^ Cessaram aqueles três homens de responder a Jó no tocante ao se ter ele por justo aos seus próprios olhos.

[[v18-32-2]]

^<<v18-32-2,2>>^ Então, se acendeu a ira de Eliú, filho de Baraquel, o buzita, da família de Rão; acendeu-se a sua ira contra Jó, porque este pretendia ser mais justo do que Deus.

[[v18-32-3]]

^<<v18-32-3,3>>^ Também a sua ira se acendeu contra os três amigos, porque, mesmo não achando eles o que responder, condenavam a Jó.

[[v18-32-4]]

^<<v18-32-4,4>>^ Eliú, porém, esperara para falar a Jó, pois eram de mais idade do que ele.

[[v18-32-5]]

^<<v18-32-5,5>>^ Vendo Eliú que já não havia resposta na boca daqueles três homens, a sua ira se acendeu.

[[v18-32-6]]

^<<v18-32-6,6>>^ Disse Eliú, filho de Baraquel, o buzita: Eu sou de menos idade, e vós sois idosos; arreceei-me e temi de vos declarar a minha opinião.

[[v18-32-7]]

^<<v18-32-7,7>>^ Dizia eu: Falem os dias, e a multidão dos anos ensine a sabedoria.

[[v18-32-8]]

^<<v18-32-8,8>>^ Na verdade, há um espírito no homem, e o sopro do Todo-Poderoso o faz sábio.

[[v18-32-9]]

^<<v18-32-9,9>>^ Os de mais idade não é que são os sábios, nem os velhos, os que entendem o que é reto.

[[v18-32-10]]

^<<v18-32-10,10>>^ Pelo que digo: dai-me ouvidos, e também eu declararei a minha opinião.

[[v18-32-11]]

^<<v18-32-11,11>>^ Eis que aguardei as vossas palavras e dei ouvidos às vossas considerações, enquanto, quem sabe, buscáveis o que dizer.

[[v18-32-12]]

^<<v18-32-12,12>>^ Atentando, pois, para vós outros, eis que nenhum de vós houve que refutasse a Jó, nem que respondesse às suas razões.

[[v18-32-13]]

^<<v18-32-13,13>>^ Não vos desculpeis, pois, dizendo: Achamos sabedoria nele; Deus pode vencê-lo, e não o homem.

[[v18-32-14]]

^<<v18-32-14,14>>^ Ora, ele não me dirigiu palavra alguma, nem eu lhe retorquirei com as vossas palavras.

[[v18-32-15]]

^<<v18-32-15,15>>^ Jó, os três estão pasmados, já não respondem, faltam-lhes as palavras.

[[v18-32-16]]

^<<v18-32-16,16>>^ Acaso, devo esperar, pois não falam, estão parados e nada mais respondem?

[[v18-32-17]]

^<<v18-32-17,17>>^ Também eu concorrerei com a minha resposta; declararei a minha opinião.

[[v18-32-18]]

^<<v18-32-18,18>>^ Porque tenho muito que falar, e o meu espírito me constrange.

[[v18-32-19]]

^<<v18-32-19,19>>^ Eis que dentro de mim sou como o vinho, sem respiradouro, como odres novos, prestes a arrebentar-se.

[[v18-32-20]]

^<<v18-32-20,20>>^ Permiti, pois, que eu fale para desafogar-me; abrirei os lábios e responderei.

[[v18-32-21]]

^<<v18-32-21,21>>^ Não farei acepção de pessoas, nem usarei de lisonjas com o homem.

[[v18-32-22]]

^<<v18-32-22,22>>^ Porque não sei lisonjear; em caso contrário, em breve me levaria o meu Criador.

'''

xref:018-jo/018-jo-031.adoc#v18-31-0[&#60; Capítulo Anterior] | <<v18-32-0,Topo>> | xref:018-jo/018-jo-033.adoc#v18-33-0[Próximo Capítulo &#62;]