include::./index.adoc[]

[[v18-14-0]]
=== Jó, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-14-1]]

^<<v18-14-1,1>>^ O homem, nascido de mulher, vive breve tempo, cheio de inquietação.

[[v18-14-2]]

^<<v18-14-2,2>>^ Nasce como a flor e murcha; foge como a sombra e não permanece;

[[v18-14-3]]

^<<v18-14-3,3>>^ e sobre tal homem abres os olhos e o fazes entrar em juízo contigo?

[[v18-14-4]]

^<<v18-14-4,4>>^ Quem da imundícia poderá tirar coisa pura? Ninguém!

[[v18-14-5]]

^<<v18-14-5,5>>^ Visto que os seus dias estão contados, contigo está o número dos seus meses; tu ao homem puseste limites além dos quais não passará.

[[v18-14-6]]

^<<v18-14-6,6>>^ Desvia dele os olhares, para que tenha repouso, até que, como o jornaleiro, tenha prazer no seu dia.

[[v18-14-7]]

^<<v18-14-7,7>>^ Porque há esperança para a árvore, pois, mesmo cortada, ainda se renovará, e não cessarão os seus rebentos.

[[v18-14-8]]

^<<v18-14-8,8>>^ Se envelhecer na terra a sua raiz, e no chão morrer o seu tronco,

[[v18-14-9]]

^<<v18-14-9,9>>^ ao cheiro das águas brotará e dará ramos como a planta nova.

[[v18-14-10]]

^<<v18-14-10,10>>^ O homem, porém, morre e fica prostrado; expira o homem e onde está?

[[v18-14-11]]

^<<v18-14-11,11>>^ Como as águas do lago se evaporam, e o rio se esgota e seca,

[[v18-14-12]]

^<<v18-14-12,12>>^ assim o homem se deita e não se levanta; enquanto existirem os céus, não acordará, nem será despertado do seu sono.

[[v18-14-13]]

^<<v18-14-13,13>>^ Que me encobrisses na sepultura e me ocultasses até que a tua ira se fosse, e me pusesses um prazo e depois te lembrasses de mim!

[[v18-14-14]]

^<<v18-14-14,14>>^ Morrendo o homem, porventura tornará a viver? Todos os dias da minha luta esperaria, até que eu fosse substituído.

[[v18-14-15]]

^<<v18-14-15,15>>^ Chamar-me-ias, e eu te responderia; terias saudades da obra de tuas mãos;

[[v18-14-16]]

^<<v18-14-16,16>>^ e até contarias os meus passos e não levarias em conta os meus pecados.

[[v18-14-17]]

^<<v18-14-17,17>>^ A minha transgressão estaria selada num saco, e terias encoberto as minhas iniquidades.

[[v18-14-18]]

^<<v18-14-18,18>>^ Como o monte que se esboroa e se desfaz, e a rocha que se remove do seu lugar,

[[v18-14-19]]

^<<v18-14-19,19>>^ como as águas gastam as pedras, e as cheias arrebatam o pó da terra, assim destróis a esperança do homem.

[[v18-14-20]]

^<<v18-14-20,20>>^ Tu prevaleces para sempre contra ele, e ele passa, mudas-lhe o semblante e o despedes para o além.

[[v18-14-21]]

^<<v18-14-21,21>>^ Os seus filhos recebem honras, e ele o não sabe; são humilhados, e ele o não percebe.

[[v18-14-22]]

^<<v18-14-22,22>>^ Ele sente as dores apenas de seu próprio corpo, e só a seu respeito sofre a sua alma.

'''

xref:018-jo/018-jo-013.adoc#v18-13-0[&#60; Capítulo Anterior] | <<v18-14-0,Topo>> | xref:018-jo/018-jo-015.adoc#v18-15-0[Próximo Capítulo &#62;]