include::./index.adoc[]

[[v18-42-0]]
=== Jó, 42
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-42-1]]

^<<v18-42-1,1>>^ Então, respondeu Jó ao SENHOR:

[[v18-42-2]]

^<<v18-42-2,2>>^ Bem sei que tudo podes, e nenhum dos teus planos pode ser frustrado.

[[v18-42-3]]

^<<v18-42-3,3>>^ Quem é aquele, como disseste, que sem conhecimento encobre o conselho? Na verdade, falei do que não entendia; coisas maravilhosas demais para mim, coisas que eu não conhecia.

[[v18-42-4]]

^<<v18-42-4,4>>^ Escuta-me, pois, havias dito, e eu falarei; eu te perguntarei, e tu me ensinarás.

[[v18-42-5]]

^<<v18-42-5,5>>^ Eu te conhecia só de ouvir, mas agora os meus olhos te veem.

[[v18-42-6]]

^<<v18-42-6,6>>^ Por isso, me abomino e me arrependo no pó e na cinza.

[[v18-42-7]]

^<<v18-42-7,7>>^ Tendo o SENHOR falado estas palavras a Jó, o SENHOR disse também a Elifaz, o temanita: A minha ira se acendeu contra ti e contra os teus dois amigos; porque não dissestes de mim o que era reto, como o meu servo Jó.

[[v18-42-8]]

^<<v18-42-8,8>>^ Tomai, pois, sete novilhos e sete carneiros, e ide ao meu servo Jó, e oferecei holocaustos por vós. O meu servo Jó orará por vós; porque dele aceitarei a intercessão, para que eu não vos trate segundo a vossa loucura; porque vós não dissestes de mim o que era reto, como o meu servo Jó.

[[v18-42-9]]

^<<v18-42-9,9>>^ Então, foram Elifaz, o temanita, e Bildade, o suíta, e Zofar, o naamatita, e fizeram como o SENHOR lhes ordenara; e o SENHOR aceitou a oração de Jó.

[[v18-42-10]]

^<<v18-42-10,10>>^ Mudou o SENHOR a sorte de Jó, quando este orava pelos seus amigos; e o SENHOR deu-lhe o dobro de tudo o que antes possuíra.

[[v18-42-11]]

^<<v18-42-11,11>>^ Então, vieram a ele todos os seus irmãos, e todas as suas irmãs, e todos quantos dantes o conheceram, e comeram com ele em sua casa, e se condoeram dele, e o consolaram de todo o mal que o SENHOR lhe havia enviado; cada um lhe deu dinheiro e um anel de ouro.

[[v18-42-12]]

^<<v18-42-12,12>>^ Assim, abençoou o SENHOR o último estado de Jó mais do que o primeiro; porque veio a ter catorze mil ovelhas, seis mil camelos, mil juntas de bois e mil jumentas.

[[v18-42-13]]

^<<v18-42-13,13>>^ Também teve outros sete filhos e três filhas.

[[v18-42-14]]

^<<v18-42-14,14>>^ Chamou o nome da primeira Jemima, o da outra, Quezia, e o da terceira, Quéren-Hapuque.

[[v18-42-15]]

^<<v18-42-15,15>>^ Em toda aquela terra não se acharam mulheres tão formosas como as filhas de Jó; e seu pai lhes deu herança entre seus irmãos.

[[v18-42-16]]

^<<v18-42-16,16>>^ Depois disto, viveu Jó cento e quarenta anos; e viu a seus filhos e aos filhos de seus filhos, até à quarta geração.

[[v18-42-17]]

^<<v18-42-17,17>>^ Então, morreu Jó, velho e farto de dias.

'''

xref:018-jo/018-jo-041.adoc#v18-41-0[&#60; Capítulo Anterior] | <<v18-42-0,Topo>> | xref:019-salmos/019-salmos-001.adoc#v19-1-0[Próximo Capítulo &#62;]