include::./index.adoc[]

[[v18-4-0]]
=== Jó, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-4-1]]

^<<v18-4-1,1>>^ Então, respondeu Elifaz, o temanita, e disse:

[[v18-4-2]]

^<<v18-4-2,2>>^ Se intentar alguém falar-te, enfadar-te-ás? Quem, todavia, poderá conter as palavras?

[[v18-4-3]]

^<<v18-4-3,3>>^ Eis que tens ensinado a muitos e tens fortalecido mãos fracas.

[[v18-4-4]]

^<<v18-4-4,4>>^ As tuas palavras têm sustentado aos que tropeçavam, e os joelhos vacilantes tens fortificado.

[[v18-4-5]]

^<<v18-4-5,5>>^ Mas agora, em chegando a tua vez, tu te enfadas; sendo tu atingido, te perturbas.

[[v18-4-6]]

^<<v18-4-6,6>>^ Porventura, não é o teu temor de Deus aquilo em que confias, e a tua esperança, a retidão dos teus caminhos?

[[v18-4-7]]

^<<v18-4-7,7>>^ Lembra-te: acaso, já pereceu algum inocente? E onde foram os retos destruídos?

[[v18-4-8]]

^<<v18-4-8,8>>^ Segundo eu tenho visto, os que lavram a iniquidade e semeiam o mal, isso mesmo eles segam.

[[v18-4-9]]

^<<v18-4-9,9>>^ Com o hálito de Deus perecem; e com o assopro da sua ira se consomem.

[[v18-4-10]]

^<<v18-4-10,10>>^ Cessa o bramido do leão e a voz do leão feroz, e os dentes dos leõezinhos se quebram.

[[v18-4-11]]

^<<v18-4-11,11>>^ Perece o leão, porque não há presa, e os filhos da leoa andam dispersos.

[[v18-4-12]]

^<<v18-4-12,12>>^ Uma palavra se me disse em segredo; e os meus ouvidos perceberam um sussurro dela.

[[v18-4-13]]

^<<v18-4-13,13>>^ Entre pensamentos de visões noturnas, quando profundo sono cai sobre os homens,

[[v18-4-14]]

^<<v18-4-14,14>>^ sobrevieram-me o espanto e o tremor, e todos os meus ossos estremeceram.

[[v18-4-15]]

^<<v18-4-15,15>>^ Então, um espírito passou por diante de mim; fez-me arrepiar os cabelos do meu corpo;

[[v18-4-16]]

^<<v18-4-16,16>>^ parou ele, mas não lhe discerni a aparência; um vulto estava diante dos meus olhos; houve silêncio, e ouvi uma voz:

[[v18-4-17]]

^<<v18-4-17,17>>^ Seria, porventura, o mortal justo diante de Deus? Seria, acaso, o homem puro diante do seu Criador?

[[v18-4-18]]

^<<v18-4-18,18>>^ Eis que Deus não confia nos seus servos e aos seus anjos atribui imperfeições;

[[v18-4-19]]

^<<v18-4-19,19>>^ quanto mais àqueles que habitam em casas de barro, cujo fundamento está no pó, e são esmagados como a traça!

[[v18-4-20]]

^<<v18-4-20,20>>^ Nascem de manhã e à tarde são destruídos; perecem para sempre, sem que disso se faça caso.

[[v18-4-21]]

^<<v18-4-21,21>>^ Se se lhes corta o fio da vida, morrem e não atingem a sabedoria.

'''

xref:018-jo/018-jo-003.adoc#v18-3-0[&#60; Capítulo Anterior] | <<v18-4-0,Topo>> | xref:018-jo/018-jo-005.adoc#v18-5-0[Próximo Capítulo &#62;]