include::./index.adoc[]

[[v18-10-0]]
=== Jó, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-10-1]]

^<<v18-10-1,1>>^ A minha alma tem tédio à minha vida; darei livre curso à minha queixa, falarei com amargura da minha alma.

[[v18-10-2]]

^<<v18-10-2,2>>^ Direi a Deus: Não me condenes; faze-me saber por que contendes comigo.

[[v18-10-3]]

^<<v18-10-3,3>>^ Parece-te bem que me oprimas, que rejeites a obra das tuas mãos e favoreças o conselho dos perversos?

[[v18-10-4]]

^<<v18-10-4,4>>^ Tens tu olhos de carne? Acaso, vês tu como vê o homem?

[[v18-10-5]]

^<<v18-10-5,5>>^ São os teus dias como os dias do mortal? Ou são os teus anos como os anos de um homem,

[[v18-10-6]]

^<<v18-10-6,6>>^ para te informares da minha iniquidade e averiguares o meu pecado?

[[v18-10-7]]

^<<v18-10-7,7>>^ Bem sabes tu que eu não sou culpado; todavia, ninguém há que me livre da tua mão.

[[v18-10-8]]

^<<v18-10-8,8>>^ As tuas mãos me plasmaram e me aperfeiçoaram, porém, agora, queres devorar-me.

[[v18-10-9]]

^<<v18-10-9,9>>^ Lembra-te de que me formaste como em barro; e queres, agora, reduzir-me a pó?

[[v18-10-10]]

^<<v18-10-10,10>>^ Porventura, não me derramaste como leite e não me coalhaste como queijo?

[[v18-10-11]]

^<<v18-10-11,11>>^ De pele e carne me vestiste e de ossos e tendões me entreteceste.

[[v18-10-12]]

^<<v18-10-12,12>>^ Vida me concedeste na tua benevolência, e o teu cuidado a mim me guardou.

[[v18-10-13]]

^<<v18-10-13,13>>^ Estas coisas, as ocultaste no teu coração; mas bem sei o que resolveste contigo mesmo.

[[v18-10-14]]

^<<v18-10-14,14>>^ Se eu pecar, tu me observas; e da minha iniquidade não me perdoarás.

[[v18-10-15]]

^<<v18-10-15,15>>^ Se for perverso, ai de mim! E, se for justo, não ouso levantar a cabeça, pois estou cheio de ignomínia e olho para a minha miséria.

[[v18-10-16]]

^<<v18-10-16,16>>^ Porque, se a levanto, tu me caças como a um leão feroz e de novo revelas poder maravilhoso contra mim.

[[v18-10-17]]

^<<v18-10-17,17>>^ Tu renovas contra mim as tuas testemunhas e multiplicas contra mim a tua ira; males e lutas se sucedem contra mim.

[[v18-10-18]]

^<<v18-10-18,18>>^ Por que, pois, me tiraste da madre? Ah! Se eu morresse antes que olhos nenhuns me vissem!

[[v18-10-19]]

^<<v18-10-19,19>>^ Teria eu sido como se nunca existira e já do ventre teria sido levado à sepultura.

[[v18-10-20]]

^<<v18-10-20,20>>^ Não são poucos os meus dias? Cessa, pois, e deixa-me, para que por um pouco eu tome alento,

[[v18-10-21]]

^<<v18-10-21,21>>^ antes que eu vá para o lugar de que não voltarei, para a terra das trevas e da sombra da morte;

[[v18-10-22]]

^<<v18-10-22,22>>^ terra de negridão, de profunda escuridade, terra da sombra da morte e do caos, onde a própria luz é tenebrosa.

'''

xref:018-jo/018-jo-009.adoc#v18-9-0[&#60; Capítulo Anterior] | <<v18-10-0,Topo>> | xref:018-jo/018-jo-011.adoc#v18-11-0[Próximo Capítulo &#62;]