include::./index.adoc[]

[[v18-15-0]]
=== Jó, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-15-1]]

^<<v18-15-1,1>>^ Então, respondeu Elifaz, o temanita:

[[v18-15-2]]

^<<v18-15-2,2>>^ Porventura, dará o sábio em resposta ciência de vento? E encher-se-á a si mesmo de vento oriental,

[[v18-15-3]]

^<<v18-15-3,3>>^ arguindo com palavras que de nada servem e com razões de que nada aproveita?

[[v18-15-4]]

^<<v18-15-4,4>>^ Tornas vão o temor de Deus e diminuis a devoção a ele devida.

[[v18-15-5]]

^<<v18-15-5,5>>^ Pois a tua iniquidade ensina à tua boca, e tu escolheste a língua dos astutos.

[[v18-15-6]]

^<<v18-15-6,6>>^ A tua própria boca te condena, e não eu; os teus lábios testificam contra ti.

[[v18-15-7]]

^<<v18-15-7,7>>^ És tu, porventura, o primeiro homem que nasceu? Ou foste formado antes dos outeiros?

[[v18-15-8]]

^<<v18-15-8,8>>^ Ou ouviste o secreto conselho de Deus e a ti só limitaste a sabedoria?

[[v18-15-9]]

^<<v18-15-9,9>>^ Que sabes tu, que nós não saibamos? Que entendes, que não haja em nós?

[[v18-15-10]]

^<<v18-15-10,10>>^ Também há entre nós encanecidos e idosos, muito mais idosos do que teu pai.

[[v18-15-11]]

^<<v18-15-11,11>>^ Porventura, fazes pouco caso das consolações de Deus e das suaves palavras que te dirigimos nós?

[[v18-15-12]]

^<<v18-15-12,12>>^ Por que te arrebata o teu coração? Por que flamejam os teus olhos,

[[v18-15-13]]

^<<v18-15-13,13>>^ para voltares contra Deus o teu furor e deixares sair tais palavras da tua boca?

[[v18-15-14]]

^<<v18-15-14,14>>^ Que é o homem, para que seja puro? E o que nasce de mulher, para ser justo?

[[v18-15-15]]

^<<v18-15-15,15>>^ Eis que Deus não confia nem nos seus santos; nem os céus são puros aos seus olhos,

[[v18-15-16]]

^<<v18-15-16,16>>^ quanto menos o homem, que é abominável e corrupto, que bebe a iniquidade como a água!

[[v18-15-17]]

^<<v18-15-17,17>>^ Escuta-me, mostrar-to-ei; e o que tenho visto te contarei,

[[v18-15-18]]

^<<v18-15-18,18>>^ o que os sábios anunciaram, que o ouviram de seus pais e não o ocultaram

[[v18-15-19]]

^<<v18-15-19,19>>^ (aos quais somente se dera a terra, e nenhum estranho passou por entre eles):

[[v18-15-20]]

^<<v18-15-20,20>>^ Todos os dias o perverso é atormentado, no curto número de anos que se reservam para o opressor.

[[v18-15-21]]

^<<v18-15-21,21>>^ O sonido dos horrores está nos seus ouvidos; na prosperidade lhe sobrevém o assolador.

[[v18-15-22]]

^<<v18-15-22,22>>^ Não crê que tornará das trevas, e sim que o espera a espada.

[[v18-15-23]]

^<<v18-15-23,23>>^ Por pão anda vagueando, dizendo: Onde está? Bem sabe que o dia das trevas lhe está preparado, à mão.

[[v18-15-24]]

^<<v18-15-24,24>>^ Assombram-no a angústia e a tribulação; prevalecem contra ele, como o rei preparado para a peleja,

[[v18-15-25]]

^<<v18-15-25,25>>^ porque estendeu a mão contra Deus e desafiou o Todo-Poderoso;

[[v18-15-26]]

^<<v18-15-26,26>>^ arremete contra ele obstinadamente, atrás da grossura dos seus escudos,

[[v18-15-27]]

^<<v18-15-27,27>>^ porquanto cobriu o rosto com a sua gordura e criou enxúndia nas ilhargas;

[[v18-15-28]]

^<<v18-15-28,28>>^ habitou em cidades assoladas, em casas em que ninguém devia morar, que estavam destinadas a se fazerem montões de ruínas.

[[v18-15-29]]

^<<v18-15-29,29>>^ Por isso, não se enriquecerá, nem subsistirá a sua fazenda, nem se estenderão seus bens pela terra.

[[v18-15-30]]

^<<v18-15-30,30>>^ Não escapará das trevas; a chama do fogo secará os seus renovos, e ao assopro da boca de Deus será arrebatado.

[[v18-15-31]]

^<<v18-15-31,31>>^ Não confie, pois, na vaidade, enganando-se a si mesmo, porque a vaidade será a sua recompensa.

[[v18-15-32]]

^<<v18-15-32,32>>^ Esta se lhe consumará antes dos seus dias, e o seu ramo não reverdecerá.

[[v18-15-33]]

^<<v18-15-33,33>>^ Sacudirá as suas uvas verdes, como a vide, e deixará cair a sua flor, como a oliveira;

[[v18-15-34]]

^<<v18-15-34,34>>^ pois a companhia dos ímpios será estéril, e o fogo consumirá as tendas de suborno.

[[v18-15-35]]

^<<v18-15-35,35>>^ Concebem a malícia e dão à luz a iniquidade, pois o seu coração só prepara enganos.

'''

xref:018-jo/018-jo-014.adoc#v18-14-0[&#60; Capítulo Anterior] | <<v18-15-0,Topo>> | xref:018-jo/018-jo-016.adoc#v18-16-0[Próximo Capítulo &#62;]