include::./index.adoc[]

[[v18-38-0]]
=== Jó, 38
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-38-1]]

^<<v18-38-1,1>>^ Depois disto, o SENHOR, do meio de um redemoinho, respondeu a Jó:

[[v18-38-2]]

^<<v18-38-2,2>>^ Quem é este que escurece os meus desígnios com palavras sem conhecimento?

[[v18-38-3]]

^<<v18-38-3,3>>^ Cinge, pois, os lombos como homem, pois eu te perguntarei, e tu me farás saber.

[[v18-38-4]]

^<<v18-38-4,4>>^ Onde estavas tu, quando eu lançava os fundamentos da terra? Dize-mo, se tens entendimento.

[[v18-38-5]]

^<<v18-38-5,5>>^ Quem lhe pôs as medidas, se é que o sabes? Ou quem estendeu sobre ela o cordel?

[[v18-38-6]]

^<<v18-38-6,6>>^ Sobre que estão fundadas as suas bases ou quem lhe assentou a pedra angular,

[[v18-38-7]]

^<<v18-38-7,7>>^ quando as estrelas da alva, juntas, alegremente cantavam, e rejubilavam todos os filhos de Deus?

[[v18-38-8]]

^<<v18-38-8,8>>^ Ou quem encerrou o mar com portas, quando irrompeu da madre;

[[v18-38-9]]

^<<v18-38-9,9>>^ quando eu lhe pus as nuvens por vestidura e a escuridão por fraldas?

[[v18-38-10]]

^<<v18-38-10,10>>^ Quando eu lhe tracei limites, e lhe pus ferrolhos e portas,

[[v18-38-11]]

^<<v18-38-11,11>>^ e disse: até aqui virás e não mais adiante, e aqui se quebrará o orgulho das tuas ondas?

[[v18-38-12]]

^<<v18-38-12,12>>^ Acaso, desde que começaram os teus dias, deste ordem à madrugada ou fizeste a alva saber o seu lugar,

[[v18-38-13]]

^<<v18-38-13,13>>^ para que se apegasse às orlas da terra, e desta fossem os perversos sacudidos?

[[v18-38-14]]

^<<v18-38-14,14>>^ A terra se modela como o barro debaixo do selo, e tudo se apresenta como vestidos;

[[v18-38-15]]

^<<v18-38-15,15>>^ dos perversos se desvia a sua luz, e o braço levantado para ferir se quebranta.

[[v18-38-16]]

^<<v18-38-16,16>>^ Acaso, entraste nos mananciais do mar ou percorreste o mais profundo do abismo?

[[v18-38-17]]

^<<v18-38-17,17>>^ Porventura, te foram reveladas as portas da morte ou viste essas portas da região tenebrosa?

[[v18-38-18]]

^<<v18-38-18,18>>^ Tens ideia nítida da largura da terra? Dize-mo, se o sabes.

[[v18-38-19]]

^<<v18-38-19,19>>^ Onde está o caminho para a morada da luz? E, quanto às trevas, onde é o seu lugar,

[[v18-38-20]]

^<<v18-38-20,20>>^ para que as conduzas aos seus limites e discirnas as veredas para a sua casa?

[[v18-38-21]]

^<<v18-38-21,21>>^ Tu o sabes, porque nesse tempo eras nascido e porque é grande o número dos teus dias!

[[v18-38-22]]

^<<v18-38-22,22>>^ Acaso, entraste nos depósitos da neve e viste os tesouros da saraiva,

[[v18-38-23]]

^<<v18-38-23,23>>^ que eu retenho até ao tempo da angústia, até ao dia da peleja e da guerra?

[[v18-38-24]]

^<<v18-38-24,24>>^ Onde está o caminho para onde se difunde a luz e se espalha o vento oriental sobre a terra?

[[v18-38-25]]

^<<v18-38-25,25>>^ Quem abriu regos para o aguaceiro ou caminho para os relâmpagos dos trovões;

[[v18-38-26]]

^<<v18-38-26,26>>^ para que se faça chover sobre a terra, onde não há ninguém, e no ermo, em que não há gente;

[[v18-38-27]]

^<<v18-38-27,27>>^ para dessedentar a terra deserta e assolada e para fazer crescer os renovos da erva?

[[v18-38-28]]

^<<v18-38-28,28>>^ Acaso, a chuva tem pai? Ou quem gera as gotas do orvalho?

[[v18-38-29]]

^<<v18-38-29,29>>^ De que ventre procede o gelo? E quem dá à luz a geada do céu?

[[v18-38-30]]

^<<v18-38-30,30>>^ As águas ficam duras como a pedra, e a superfície das profundezas se torna compacta.

[[v18-38-31]]

^<<v18-38-31,31>>^ Ou poderás tu atar as cadeias do Sete-estrelo ou soltar os laços do Órion?

[[v18-38-32]]

^<<v18-38-32,32>>^ Ou fazer aparecer os signos do Zodíaco ou guiar a Ursa com seus filhos?

[[v18-38-33]]

^<<v18-38-33,33>>^ Sabes tu as ordenanças dos céus, podes estabelecer a sua influência sobre a terra?

[[v18-38-34]]

^<<v18-38-34,34>>^ Podes levantar a tua voz até às nuvens, para que a abundância das águas te cubra?

[[v18-38-35]]

^<<v18-38-35,35>>^ Ou ordenarás aos relâmpagos que saiam e te digam: Eis-nos aqui?

[[v18-38-36]]

^<<v18-38-36,36>>^ Quem pôs sabedoria nas camadas de nuvens? Ou quem deu entendimento ao meteoro?

[[v18-38-37]]

^<<v18-38-37,37>>^ Quem pode numerar com sabedoria as nuvens? Ou os odres dos céus, quem os pode despejar,

[[v18-38-38]]

^<<v18-38-38,38>>^ para que o pó se transforme em massa sólida, e os torrões se apeguem uns aos outros?

[[v18-38-39]]

^<<v18-38-39,39>>^ Caçarás, porventura, a presa para a leoa? Ou saciarás a fome dos leõezinhos,

[[v18-38-40]]

^<<v18-38-40,40>>^ quando se agacham nos covis e estão à espreita nas covas?

[[v18-38-41]]

^<<v18-38-41,41>>^ Quem prepara aos corvos o seu alimento, quando os seus pintainhos gritam a Deus e andam vagueando, por não terem que comer?

'''

xref:018-jo/018-jo-037.adoc#v18-37-0[&#60; Capítulo Anterior] | <<v18-38-0,Topo>> | xref:018-jo/018-jo-039.adoc#v18-39-0[Próximo Capítulo &#62;]