include::./index.adoc[]

[[v18-34-0]]
=== Jó, 34
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-34-1]]

^<<v18-34-1,1>>^ Disse mais Eliú:

[[v18-34-2]]

^<<v18-34-2,2>>^ Ouvi, ó sábios, as minhas razões; vós, instruídos, inclinai os ouvidos para mim.

[[v18-34-3]]

^<<v18-34-3,3>>^ Porque o ouvido prova as palavras, como o paladar, a comida.

[[v18-34-4]]

^<<v18-34-4,4>>^ O que é direito escolhamos para nós; conheçamos entre nós o que é bom.

[[v18-34-5]]

^<<v18-34-5,5>>^ Porque Jó disse: Sou justo, e Deus tirou o meu direito.

[[v18-34-6]]

^<<v18-34-6,6>>^ Apesar do meu direito, sou tido por mentiroso; a minha ferida é incurável, sem que haja pecado em mim.

[[v18-34-7]]

^<<v18-34-7,7>>^ Que homem há como Jó, que bebe a zombaria como água?

[[v18-34-8]]

^<<v18-34-8,8>>^ E anda em companhia dos que praticam a iniquidade e caminha com homens perversos?

[[v18-34-9]]

^<<v18-34-9,9>>^ Pois disse: De nada aproveita ao homem o comprazer-se em Deus.

[[v18-34-10]]

^<<v18-34-10,10>>^ Pelo que vós, homens sensatos, escutai-me: longe de Deus o praticar ele a perversidade, e do Todo-Poderoso o cometer injustiça.

[[v18-34-11]]

^<<v18-34-11,11>>^ Pois retribui ao homem segundo as suas obras e faz que a cada um toque segundo o seu caminho.

[[v18-34-12]]

^<<v18-34-12,12>>^ Na verdade, Deus não procede maliciosamente; nem o Todo-Poderoso perverte o juízo.

[[v18-34-13]]

^<<v18-34-13,13>>^ Quem lhe entregou o governo da terra? Quem lhe confiou o universo?

[[v18-34-14]]

^<<v18-34-14,14>>^ Se Deus pensasse apenas em si mesmo e para si recolhesse o seu espírito e o seu sopro,

[[v18-34-15]]

^<<v18-34-15,15>>^ toda a carne juntamente expiraria, e o homem voltaria para o pó.

[[v18-34-16]]

^<<v18-34-16,16>>^ Se, pois, há em ti entendimento, ouve isto; inclina os ouvidos ao som das minhas palavras.

[[v18-34-17]]

^<<v18-34-17,17>>^ Acaso, governaria o que aborrecesse o direito? E quererás tu condenar aquele que é justo e poderoso?

[[v18-34-18]]

^<<v18-34-18,18>>^ Dir-se-á a um rei: Oh! Vil? Ou aos príncipes: Oh! Perversos?

[[v18-34-19]]

^<<v18-34-19,19>>^ Quanto menos àquele que não faz acepção das pessoas de príncipes, nem estima ao rico mais do que ao pobre; porque todos são obra de suas mãos.

[[v18-34-20]]

^<<v18-34-20,20>>^ De repente, morrem; à meia-noite, os povos são perturbados e passam, e os poderosos são tomados por força invisível.

[[v18-34-21]]

^<<v18-34-21,21>>^ Os olhos de Deus estão sobre os caminhos do homem e veem todos os seus passos.

[[v18-34-22]]

^<<v18-34-22,22>>^ Não há trevas nem sombra assaz profunda, onde se escondam os que praticam a iniquidade.

[[v18-34-23]]

^<<v18-34-23,23>>^ Pois Deus não precisa observar por muito tempo o homem antes de o fazer ir a juízo perante ele.

[[v18-34-24]]

^<<v18-34-24,24>>^ Quebranta os fortes, sem os inquirir, e põe outros em seu lugar.

[[v18-34-25]]

^<<v18-34-25,25>>^ Ele conhece, pois, as suas obras; de noite, os transtorna, e ficam moídos.

[[v18-34-26]]

^<<v18-34-26,26>>^ Ele os fere como a perversos, à vista de todos;

[[v18-34-27]]

^<<v18-34-27,27>>^ porque dele se desviaram, e não quiseram compreender nenhum de seus caminhos,

[[v18-34-28]]

^<<v18-34-28,28>>^ e, assim, fizeram que o clamor do pobre subisse até Deus, e este ouviu o lamento dos aflitos.

[[v18-34-29]]

^<<v18-34-29,29>>^ Se ele aquietar-se, quem o condenará? Se encobrir o rosto, quem o poderá contemplar, seja um povo, seja um homem?

[[v18-34-30]]

^<<v18-34-30,30>>^ Para que o ímpio não reine, e não haja quem iluda o povo.

[[v18-34-31]]

^<<v18-34-31,31>>^ Se alguém diz a Deus: Sofri, não pecarei mais;

[[v18-34-32]]

^<<v18-34-32,32>>^ o que não vejo, ensina-mo tu; se cometi injustiça, jamais a tornarei a praticar,

[[v18-34-33]]

^<<v18-34-33,33>>^ acaso, deve ele recompensar-te segundo tu queres ou não queres? Acaso, deve ele dizer-te: Escolhe tu, e não eu; declara o que sabes, fala?

[[v18-34-34]]

^<<v18-34-34,34>>^ Os homens sensatos dir-me-ão, dir-me-á o sábio que me ouve:

[[v18-34-35]]

^<<v18-34-35,35>>^ Jó falou sem conhecimento, e nas suas palavras não há sabedoria.

[[v18-34-36]]

^<<v18-34-36,36>>^ Tomara fosse Jó provado até ao fim, porque ele respondeu como homem de iniquidade.

[[v18-34-37]]

^<<v18-34-37,37>>^ Pois ao seu pecado acrescenta rebelião, entre nós, com desprezo, bate ele palmas e multiplica as suas palavras contra Deus.

'''

xref:018-jo/018-jo-033.adoc#v18-33-0[&#60; Capítulo Anterior] | <<v18-34-0,Topo>> | xref:018-jo/018-jo-035.adoc#v18-35-0[Próximo Capítulo &#62;]