include::./index.adoc[]

[[v18-13-0]]
=== Jó, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-13-1]]

^<<v18-13-1,1>>^ Eis que tudo isso viram os meus olhos, e os meus ouvidos o ouviram e entenderam.

[[v18-13-2]]

^<<v18-13-2,2>>^ Como vós o sabeis, também eu o sei; não vos sou inferior.

[[v18-13-3]]

^<<v18-13-3,3>>^ Mas falarei ao Todo-Poderoso e quero defender-me perante Deus.

[[v18-13-4]]

^<<v18-13-4,4>>^ Vós, porém, besuntais a verdade com mentiras e vós todos sois médicos que não valem nada.

[[v18-13-5]]

^<<v18-13-5,5>>^ Tomara vos calásseis de todo, que isso seria a vossa sabedoria!

[[v18-13-6]]

^<<v18-13-6,6>>^ Ouvi agora a minha defesa e atentai para os argumentos dos meus lábios.

[[v18-13-7]]

^<<v18-13-7,7>>^ Porventura, falareis perversidade em favor de Deus e a seu favor falareis mentiras?

[[v18-13-8]]

^<<v18-13-8,8>>^ Sereis parciais por ele? Contendereis a favor de Deus?

[[v18-13-9]]

^<<v18-13-9,9>>^ Ser-vos-ia bom, se ele vos esquadrinhasse? Ou zombareis dele, como se zomba de um homem qualquer?

[[v18-13-10]]

^<<v18-13-10,10>>^ Acerbamente vos repreenderá, se em oculto fordes parciais.

[[v18-13-11]]

^<<v18-13-11,11>>^ Porventura, não vos amedrontará a sua dignidade, e não cairá sobre vós o seu terror?

[[v18-13-12]]

^<<v18-13-12,12>>^ As vossas máximas são como provérbios de cinza, os vossos baluartes, baluartes de barro.

[[v18-13-13]]

^<<v18-13-13,13>>^ Calai-vos perante mim, e falarei eu, e venha sobre mim o que vier.

[[v18-13-14]]

^<<v18-13-14,14>>^ Tomarei a minha carne nos meus dentes e porei a vida na minha mão.

[[v18-13-15]]

^<<v18-13-15,15>>^ Eis que me matará, já não tenho esperança; contudo, defenderei o meu procedimento.

[[v18-13-16]]

^<<v18-13-16,16>>^ Também isto será a minha salvação, o fato de o ímpio não vir perante ele.

[[v18-13-17]]

^<<v18-13-17,17>>^ Atentai para as minhas razões e dai ouvidos à minha exposição.

[[v18-13-18]]

^<<v18-13-18,18>>^ Tenho já bem-encaminhada minha causa e estou certo de que serei justificado.

[[v18-13-19]]

^<<v18-13-19,19>>^ Quem há que possa contender comigo? Neste caso, eu me calaria e renderia o espírito.

[[v18-13-20]]

^<<v18-13-20,20>>^ Concede-me somente duas coisas; então, me não esconderei do teu rosto:

[[v18-13-21]]

^<<v18-13-21,21>>^ alivia a tua mão de sobre mim, e não me espante o teu terror.

[[v18-13-22]]

^<<v18-13-22,22>>^ Interpela-me, e te responderei ou deixa-me falar e tu me responderás.

[[v18-13-23]]

^<<v18-13-23,23>>^ Quantas culpas e pecados tenho eu? Notifica-me a minha transgressão e o meu pecado.

[[v18-13-24]]

^<<v18-13-24,24>>^ Por que escondes o rosto e me tens por teu inimigo?

[[v18-13-25]]

^<<v18-13-25,25>>^ Queres aterrorizar uma folha arrebatada pelo vento? E perseguirás a palha seca?

[[v18-13-26]]

^<<v18-13-26,26>>^ Pois decretas contra mim coisas amargas e me atribuis as culpas da minha mocidade.

[[v18-13-27]]

^<<v18-13-27,27>>^ Também pões os meus pés no tronco, observas todos os meus caminhos e traças limites à planta dos meus pés,

[[v18-13-28]]

^<<v18-13-28,28>>^ apesar de eu ser como uma coisa podre que se consome e como a roupa que é comida da traça.

'''

xref:018-jo/018-jo-012.adoc#v18-12-0[&#60; Capítulo Anterior] | <<v18-13-0,Topo>> | xref:018-jo/018-jo-014.adoc#v18-14-0[Próximo Capítulo &#62;]