include::./index.adoc[]

[[v18-3-0]]
=== Jó, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-3-1]]

^<<v18-3-1,1>>^ Depois disto, passou Jó a falar e amaldiçoou o seu dia natalício.

[[v18-3-2]]

^<<v18-3-2,2>>^ Disse Jó:

[[v18-3-3]]

^<<v18-3-3,3>>^ Pereça o dia em que nasci e a noite em que se disse: Foi concebido um homem!

[[v18-3-4]]

^<<v18-3-4,4>>^ Converta-se aquele dia em trevas; e Deus, lá de cima, não tenha cuidado dele, nem resplandeça sobre ele a luz.

[[v18-3-5]]

^<<v18-3-5,5>>^ Reclamem-no as trevas e a sombra de morte; habitem sobre ele nuvens; espante-o tudo o que pode enegrecer o dia.

[[v18-3-6]]

^<<v18-3-6,6>>^ Aquela noite, que dela se apoderem densas trevas; não se regozije ela entre os dias do ano, não entre na conta dos meses.

[[v18-3-7]]

^<<v18-3-7,7>>^ Seja estéril aquela noite, e dela sejam banidos os sons de júbilo.

[[v18-3-8]]

^<<v18-3-8,8>>^ Amaldiçoem-na aqueles que sabem amaldiçoar o dia e sabem excitar o monstro marinho.

[[v18-3-9]]

^<<v18-3-9,9>>^ Escureçam-se as estrelas do crepúsculo matutino dessa noite; que ela espere a luz, e a luz não venha; que não veja as pálpebras dos olhos da alva,

[[v18-3-10]]

^<<v18-3-10,10>>^ pois não fechou as portas do ventre de minha mãe, nem escondeu dos meus olhos o sofrimento.

[[v18-3-11]]

^<<v18-3-11,11>>^ Por que não morri eu na madre? Por que não expirei ao sair dela?

[[v18-3-12]]

^<<v18-3-12,12>>^ Por que houve regaço que me acolhesse? E por que peitos, para que eu mamasse?

[[v18-3-13]]

^<<v18-3-13,13>>^ Porque já agora repousaria tranquilo; dormiria, e, então, haveria para mim descanso,

[[v18-3-14]]

^<<v18-3-14,14>>^ com os reis e conselheiros da terra que para si edificaram mausoléus;

[[v18-3-15]]

^<<v18-3-15,15>>^ ou com os príncipes que tinham ouro e encheram de prata as suas casas;

[[v18-3-16]]

^<<v18-3-16,16>>^ ou, como aborto oculto, eu não existiria, como crianças que nunca viram a luz.

[[v18-3-17]]

^<<v18-3-17,17>>^ Ali, os maus cessam de perturbar, e, ali, repousam os cansados.

[[v18-3-18]]

^<<v18-3-18,18>>^ Ali, os presos juntamente repousam e não ouvem a voz do feitor.

[[v18-3-19]]

^<<v18-3-19,19>>^ Ali, está tanto o pequeno como o grande e o servo livre de seu senhor.

[[v18-3-20]]

^<<v18-3-20,20>>^ Por que se concede luz ao miserável e vida aos amargurados de ânimo,

[[v18-3-21]]

^<<v18-3-21,21>>^ que esperam a morte, e ela não vem? Eles cavam em procura dela mais do que tesouros ocultos.

[[v18-3-22]]

^<<v18-3-22,22>>^ Eles se regozijariam por um túmulo e exultariam se achassem a sepultura.

[[v18-3-23]]

^<<v18-3-23,23>>^ Por que se concede luz ao homem, cujo caminho é oculto, e a quem Deus cercou de todos os lados?

[[v18-3-24]]

^<<v18-3-24,24>>^ Por que em vez do meu pão me vêm gemidos, e os meus lamentos se derramam como água?

[[v18-3-25]]

^<<v18-3-25,25>>^ Aquilo que temo me sobrevém, e o que receio me acontece.

[[v18-3-26]]

^<<v18-3-26,26>>^ Não tenho descanso, nem sossego, nem repouso, e já me vem grande perturbação.

'''

xref:018-jo/018-jo-002.adoc#v18-2-0[&#60; Capítulo Anterior] | <<v18-3-0,Topo>> | xref:018-jo/018-jo-004.adoc#v18-4-0[Próximo Capítulo &#62;]