include::./index.adoc[]

[[v18-36-0]]
=== Jó, 36
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-36-1]]

^<<v18-36-1,1>>^ Prosseguiu Eliú e disse:

[[v18-36-2]]

^<<v18-36-2,2>>^ Mais um pouco de paciência, e te mostrarei que ainda tenho argumentos a favor de Deus.

[[v18-36-3]]

^<<v18-36-3,3>>^ De longe trarei o meu conhecimento e ao meu Criador atribuirei a justiça.

[[v18-36-4]]

^<<v18-36-4,4>>^ Porque, na verdade, as minhas palavras não são falsas; contigo está quem é senhor do assunto.

[[v18-36-5]]

^<<v18-36-5,5>>^ Eis que Deus é mui grande; contudo a ninguém despreza; é grande na força da sua compreensão.

[[v18-36-6]]

^<<v18-36-6,6>>^ Não poupa a vida ao perverso, mas faz justiça aos aflitos.

[[v18-36-7]]

^<<v18-36-7,7>>^ Dos justos não tira os olhos; antes, com os reis, no trono os assenta para sempre, e são exaltados.

[[v18-36-8]]

^<<v18-36-8,8>>^ Se estão presos em grilhões e amarrados com cordas de aflição,

[[v18-36-9]]

^<<v18-36-9,9>>^ ele lhes faz ver as suas obras, as suas transgressões, e que se houveram com soberba.

[[v18-36-10]]

^<<v18-36-10,10>>^ Abre-lhes também os ouvidos para a instrução e manda-lhes que se convertam da iniquidade.

[[v18-36-11]]

^<<v18-36-11,11>>^ Se o ouvirem e o servirem, acabarão seus dias em felicidade e os seus anos em delícias.

[[v18-36-12]]

^<<v18-36-12,12>>^ Porém, se não o ouvirem, serão traspassados pela lança e morrerão na sua cegueira.

[[v18-36-13]]

^<<v18-36-13,13>>^ Os ímpios de coração amontoam para si a ira; e, agrilhoados por Deus, não clamam por socorro.

[[v18-36-14]]

^<<v18-36-14,14>>^ Perdem a vida na sua mocidade e morrem entre os prostitutos cultuais.

[[v18-36-15]]

^<<v18-36-15,15>>^ Ao aflito livra por meio da sua aflição e pela opressão lhe abre os ouvidos.

[[v18-36-16]]

^<<v18-36-16,16>>^ Assim também procura tirar-te das fauces da angústia para um lugar espaçoso, em que não há aperto, e as iguarias da tua mesa seriam cheias de gordura;

[[v18-36-17]]

^<<v18-36-17,17>>^ mas tu te enches do juízo do perverso, e, por isso, o juízo e a justiça te alcançarão.

[[v18-36-18]]

^<<v18-36-18,18>>^ Guarda-te, pois, de que a ira não te induza a escarnecer, nem te desvie a grande quantia do resgate.

[[v18-36-19]]

^<<v18-36-19,19>>^ Estimaria ele as tuas lamúrias e todos os teus grandes esforços, para que te vejas livre da tua angústia?

[[v18-36-20]]

^<<v18-36-20,20>>^ Não suspires pela noite, em que povos serão tomados do seu lugar.

[[v18-36-21]]

^<<v18-36-21,21>>^ Guarda-te, não te inclines para a iniquidade; pois isso preferes à tua miséria.

[[v18-36-22]]

^<<v18-36-22,22>>^ Eis que Deus se mostra grande em seu poder! Quem é mestre como ele?

[[v18-36-23]]

^<<v18-36-23,23>>^ Quem lhe prescreveu o seu caminho ou quem lhe pode dizer: Praticaste a injustiça?

[[v18-36-24]]

^<<v18-36-24,24>>^ Lembra-te de lhe magnificares as obras que os homens celebram.

[[v18-36-25]]

^<<v18-36-25,25>>^ Todos os homens as contemplam; de longe as admira o homem.

[[v18-36-26]]

^<<v18-36-26,26>>^ Eis que Deus é grande, e não o podemos compreender; o número dos seus anos não se pode calcular.

[[v18-36-27]]

^<<v18-36-27,27>>^ Porque atrai para si as gotas de água que de seu vapor destilam em chuva,

[[v18-36-28]]

^<<v18-36-28,28>>^ a qual as nuvens derramam e gotejam sobre o homem abundantemente.

[[v18-36-29]]

^<<v18-36-29,29>>^ Acaso, pode alguém entender o estender-se das nuvens e os trovões do seu pavilhão?

[[v18-36-30]]

^<<v18-36-30,30>>^ Eis que estende sobre elas o seu relâmpago e encobre as profundezas do mar.

[[v18-36-31]]

^<<v18-36-31,31>>^ Pois por estas coisas julga os povos e lhes dá mantimento em abundância.

[[v18-36-32]]

^<<v18-36-32,32>>^ Enche as mãos de relâmpagos e os dardeja contra o adversário.

[[v18-36-33]]

^<<v18-36-33,33>>^ O fragor da tempestade dá notícias a respeito dele, dele que é zeloso na sua ira contra a injustiça.

'''

xref:018-jo/018-jo-035.adoc#v18-35-0[&#60; Capítulo Anterior] | <<v18-36-0,Topo>> | xref:018-jo/018-jo-037.adoc#v18-37-0[Próximo Capítulo &#62;]