include::./index.adoc[]

[[v18-7-0]]
=== Jó, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-7-1]]

^<<v18-7-1,1>>^ Não é penosa a vida do homem sobre a terra? Não são os seus dias como os de um jornaleiro?

[[v18-7-2]]

^<<v18-7-2,2>>^ Como o escravo que suspira pela sombra e como o jornaleiro que espera pela sua paga,

[[v18-7-3]]

^<<v18-7-3,3>>^ assim me deram por herança meses de desengano e noites de aflição me proporcionaram.

[[v18-7-4]]

^<<v18-7-4,4>>^ Ao deitar-me, digo: quando me levantarei? Mas comprida é a noite, e farto-me de me revolver na cama, até à alva.

[[v18-7-5]]

^<<v18-7-5,5>>^ A minha carne está vestida de vermes e de crostas terrosas; a minha pele se encrosta e de novo supura.

[[v18-7-6]]

^<<v18-7-6,6>>^ Os meus dias são mais velozes do que a lançadeira do tecelão e se findam sem esperança.

[[v18-7-7]]

^<<v18-7-7,7>>^ Lembra-te de que a minha vida é um sopro; os meus olhos não tornarão a ver o bem.

[[v18-7-8]]

^<<v18-7-8,8>>^ Os olhos dos que agora me veem não me verão mais; os teus olhos me procurarão, mas já não serei.

[[v18-7-9]]

^<<v18-7-9,9>>^ Tal como a nuvem se desfaz e passa, aquele que desce à sepultura jamais tornará a subir.

[[v18-7-10]]

^<<v18-7-10,10>>^ Nunca mais tornará à sua casa, nem o lugar onde habita o conhecerá jamais.

[[v18-7-11]]

^<<v18-7-11,11>>^ Por isso, não reprimirei a boca, falarei na angústia do meu espírito, queixar-me-ei na amargura da minha alma.

[[v18-7-12]]

^<<v18-7-12,12>>^ Acaso, sou eu o mar ou algum monstro marinho, para que me ponhas guarda?

[[v18-7-13]]

^<<v18-7-13,13>>^ Dizendo eu: consolar-me-á o meu leito, a minha cama aliviará a minha queixa,

[[v18-7-14]]

^<<v18-7-14,14>>^ então, me espantas com sonhos e com visões me assombras;

[[v18-7-15]]

^<<v18-7-15,15>>^ pelo que a minha alma escolheria, antes, ser estrangulada; antes, a morte do que esta tortura.

[[v18-7-16]]

^<<v18-7-16,16>>^ Estou farto da minha vida; não quero viver para sempre. Deixa-me, pois, porque os meus dias são um sopro.

[[v18-7-17]]

^<<v18-7-17,17>>^ Que é o homem, para que tanto o estimes, e ponhas nele o teu cuidado,

[[v18-7-18]]

^<<v18-7-18,18>>^ e cada manhã o visites, e cada momento o ponhas à prova?

[[v18-7-19]]

^<<v18-7-19,19>>^ Até quando não apartarás de mim a tua vista? Até quando não me darás tempo de engolir a minha saliva?

[[v18-7-20]]

^<<v18-7-20,20>>^ Se pequei, que mal te fiz a ti, ó Espreitador dos homens? Por que fizeste de mim um alvo para ti, para que a mim mesmo me seja pesado?

[[v18-7-21]]

^<<v18-7-21,21>>^ Por que não perdoas a minha transgressão e não tiras a minha iniquidade? Pois agora me deitarei no pó; e, se me buscas, já não serei.

'''

xref:018-jo/018-jo-006.adoc#v18-6-0[&#60; Capítulo Anterior] | <<v18-7-0,Topo>> | xref:018-jo/018-jo-008.adoc#v18-8-0[Próximo Capítulo &#62;]