include::./index.adoc[]

[[v18-33-0]]
=== Jó, 33
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-33-1]]

^<<v18-33-1,1>>^ Ouve, pois, Jó, as minhas razões e dá ouvidos a todas as minhas palavras.

[[v18-33-2]]

^<<v18-33-2,2>>^ Passo agora a falar, em minha boca fala a língua.

[[v18-33-3]]

^<<v18-33-3,3>>^ As minhas razões provam a sinceridade do meu coração, e os meus lábios proferem o puro saber.

[[v18-33-4]]

^<<v18-33-4,4>>^ O Espírito de Deus me fez, e o sopro do Todo-Poderoso me dá vida.

[[v18-33-5]]

^<<v18-33-5,5>>^ Se podes, contesta-me, dispõe bem as tuas razões perante mim e apresenta-te.

[[v18-33-6]]

^<<v18-33-6,6>>^ Eis que diante de Deus sou como tu és; também eu sou formado do barro.

[[v18-33-7]]

^<<v18-33-7,7>>^ Por isso, não te inspiro terror, nem será pesada sobre ti a minha mão.

[[v18-33-8]]

^<<v18-33-8,8>>^ Na verdade, falaste perante mim, e eu ouvi o som das tuas palavras:

[[v18-33-9]]

^<<v18-33-9,9>>^ Estou limpo, sem transgressão; puro sou e não tenho iniquidade.

[[v18-33-10]]

^<<v18-33-10,10>>^ Eis que Deus procura pretextos contra mim e me considera como seu inimigo.

[[v18-33-11]]

^<<v18-33-11,11>>^ Põe no tronco os meus pés e observa todas as minhas veredas.

[[v18-33-12]]

^<<v18-33-12,12>>^ Nisto não tens razão, eu te respondo; porque Deus é maior do que o homem.

[[v18-33-13]]

^<<v18-33-13,13>>^ Por que contendes com ele, afirmando que não te dá contas de nenhum dos seus atos?

[[v18-33-14]]

^<<v18-33-14,14>>^ Pelo contrário, Deus fala de um modo, sim, de dois modos, mas o homem não atenta para isso.

[[v18-33-15]]

^<<v18-33-15,15>>^ Em sonho ou em visão de noite, quando cai sono profundo sobre os homens, quando adormecem na cama,

[[v18-33-16]]

^<<v18-33-16,16>>^ então, lhes abre os ouvidos e lhes sela a sua instrução,

[[v18-33-17]]

^<<v18-33-17,17>>^ para apartar o homem do seu desígnio e livrá-lo da soberba;

[[v18-33-18]]

^<<v18-33-18,18>>^ para guardar a sua alma da cova e a sua vida de passar pela espada.

[[v18-33-19]]

^<<v18-33-19,19>>^ Também no seu leito é castigado com dores, com incessante contenda nos seus ossos;

[[v18-33-20]]

^<<v18-33-20,20>>^ de modo que a sua vida abomina o pão, e a sua alma, a comida apetecível.

[[v18-33-21]]

^<<v18-33-21,21>>^ A sua carne, que se via, agora desaparece, e os seus ossos, que não se viam, agora se descobrem.

[[v18-33-22]]

^<<v18-33-22,22>>^ A sua alma se vai chegando à cova, e a sua vida, aos portadores da morte.

[[v18-33-23]]

^<<v18-33-23,23>>^ Se com ele houver um anjo intercessor, um dos milhares, para declarar ao homem o que lhe convém,

[[v18-33-24]]

^<<v18-33-24,24>>^ então, Deus terá misericórdia dele e dirá ao anjo: Redime-o, para que não desça à cova; achei resgate.

[[v18-33-25]]

^<<v18-33-25,25>>^ Sua carne se robustecerá com o vigor da sua infância, e ele tornará aos dias da sua juventude.

[[v18-33-26]]

^<<v18-33-26,26>>^ Deveras orará a Deus, que lhe será propício; ele, com júbilo, verá a face de Deus, e este lhe restituirá a sua justiça.

[[v18-33-27]]

^<<v18-33-27,27>>^ Cantará diante dos homens e dirá: Pequei, perverti o direito e não fui punido segundo merecia.

[[v18-33-28]]

^<<v18-33-28,28>>^ Deus redimiu a minha alma de ir para a cova; e a minha vida verá a luz.

[[v18-33-29]]

^<<v18-33-29,29>>^ Eis que tudo isto é obra de Deus, duas e três vezes para com o homem,

[[v18-33-30]]

^<<v18-33-30,30>>^ para reconduzir da cova a sua alma e o alumiar com a luz dos viventes.

[[v18-33-31]]

^<<v18-33-31,31>>^ Escuta, pois, ó Jó, ouve-me; cala-te, e eu falarei.

[[v18-33-32]]

^<<v18-33-32,32>>^ Se tens alguma coisa que dizer, responde-me; fala, porque desejo justificar-te.

[[v18-33-33]]

^<<v18-33-33,33>>^ Se não, escuta-me; cala-te, e ensinar-te-ei a sabedoria.

'''

xref:018-jo/018-jo-032.adoc#v18-32-0[&#60; Capítulo Anterior] | <<v18-33-0,Topo>> | xref:018-jo/018-jo-034.adoc#v18-34-0[Próximo Capítulo &#62;]