include::./index.adoc[]

[[v18-19-0]]
=== Jó, 19
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-19-1]]

^<<v18-19-1,1>>^ Então, respondeu Jó:

[[v18-19-2]]

^<<v18-19-2,2>>^ Até quando afligireis a minha alma e me quebrantareis com palavras?

[[v18-19-3]]

^<<v18-19-3,3>>^ Já dez vezes me vituperastes e não vos envergonhais de injuriar-me.

[[v18-19-4]]

^<<v18-19-4,4>>^ Embora haja eu, na verdade, errado, comigo ficará o meu erro.

[[v18-19-5]]

^<<v18-19-5,5>>^ Se quereis engrandecer-vos contra mim e me arguis pelo meu opróbrio,

[[v18-19-6]]

^<<v18-19-6,6>>^ sabei agora que Deus é que me oprimiu e com a sua rede me cercou.

[[v18-19-7]]

^<<v18-19-7,7>>^ Eis que clamo: violência! Mas não sou ouvido; grito: socorro! Porém não há justiça.

[[v18-19-8]]

^<<v18-19-8,8>>^ O meu caminho ele fechou, e não posso passar; e nas minhas veredas pôs trevas.

[[v18-19-9]]

^<<v18-19-9,9>>^ Da minha honra me despojou e tirou-me da cabeça a coroa.

[[v18-19-10]]

^<<v18-19-10,10>>^ Arruinou-me de todos os lados, e eu me vou; e arrancou-me a esperança, como a uma árvore.

[[v18-19-11]]

^<<v18-19-11,11>>^ Inflamou contra mim a sua ira e me tem na conta de seu adversário.

[[v18-19-12]]

^<<v18-19-12,12>>^ Juntas vieram as suas tropas, prepararam contra mim o seu caminho e se acamparam ao redor da minha tenda.

[[v18-19-13]]

^<<v18-19-13,13>>^ Pôs longe de mim a meus irmãos, e os que me conhecem, como estranhos, se apartaram de mim.

[[v18-19-14]]

^<<v18-19-14,14>>^ Os meus parentes me desampararam, e os meus conhecidos se esqueceram de mim.

[[v18-19-15]]

^<<v18-19-15,15>>^ Os que se abrigam na minha casa e as minhas servas me têm por estranho, e vim a ser estrangeiro aos seus olhos.

[[v18-19-16]]

^<<v18-19-16,16>>^ Chamo o meu criado, e ele não me responde; tenho de suplicar-lhe, eu mesmo.

[[v18-19-17]]

^<<v18-19-17,17>>^ O meu hálito é intolerável à minha mulher, e pelo mau cheiro sou repugnante aos filhos de minha mãe.

[[v18-19-18]]

^<<v18-19-18,18>>^ Até as crianças me desprezam, e, querendo eu levantar-me, zombam de mim.

[[v18-19-19]]

^<<v18-19-19,19>>^ Todos os meus amigos íntimos me abominam, e até os que eu amava se tornaram contra mim.

[[v18-19-20]]

^<<v18-19-20,20>>^ Os meus ossos se apegam à minha pele e à minha carne, e salvei-me só com a pele dos meus dentes.

[[v18-19-21]]

^<<v18-19-21,21>>^ Compadecei-vos de mim, amigos meus, compadecei-vos de mim, porque a mão de Deus me atingiu.

[[v18-19-22]]

^<<v18-19-22,22>>^ Por que me perseguis como Deus me persegue e não cessais de devorar a minha carne?

[[v18-19-23]]

^<<v18-19-23,23>>^ Quem me dera fossem agora escritas as minhas palavras! Quem me dera fossem gravadas em livro!

[[v18-19-24]]

^<<v18-19-24,24>>^ Que, com pena de ferro e com chumbo, para sempre fossem esculpidas na rocha!

[[v18-19-25]]

^<<v18-19-25,25>>^ Porque eu sei que o meu Redentor vive e por fim se levantará sobre a terra.

[[v18-19-26]]

^<<v18-19-26,26>>^ Depois, revestido este meu corpo da minha pele, em minha carne verei a Deus.

[[v18-19-27]]

^<<v18-19-27,27>>^ Vê-lo-ei por mim mesmo, os meus olhos o verão, e não outros; de saudade me desfalece o coração dentro de mim.

[[v18-19-28]]

^<<v18-19-28,28>>^ Se disserdes: Como o perseguiremos? E: A causa deste mal se acha nele,

[[v18-19-29]]

^<<v18-19-29,29>>^ temei, pois, a espada, porque tais acusações merecem o seu furor, para saberdes que há um juízo.

'''

xref:018-jo/018-jo-018.adoc#v18-18-0[&#60; Capítulo Anterior] | <<v18-19-0,Topo>> | xref:018-jo/018-jo-020.adoc#v18-20-0[Próximo Capítulo &#62;]