include::./index.adoc[]

[[v18-24-0]]
=== Jó, 24
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-24-1]]

^<<v18-24-1,1>>^ Por que o Todo-Poderoso não designa tempos de julgamento? E por que os que o conhecem não veem tais dias?

[[v18-24-2]]

^<<v18-24-2,2>>^ Há os que removem os limites, roubam os rebanhos e os apascentam.

[[v18-24-3]]

^<<v18-24-3,3>>^ Levam do órfão o jumento, da viúva, tomam-lhe o boi.

[[v18-24-4]]

^<<v18-24-4,4>>^ Desviam do caminho aos necessitados, e os pobres da terra todos têm de esconder-se.

[[v18-24-5]]

^<<v18-24-5,5>>^ Como asnos monteses no deserto, saem estes para o seu mister, à procura de presa no campo aberto, como pão para eles e seus filhos.

[[v18-24-6]]

^<<v18-24-6,6>>^ No campo segam o pasto do perverso e lhe rabiscam a vinha.

[[v18-24-7]]

^<<v18-24-7,7>>^ Passam a noite nus por falta de roupa e não têm cobertas contra o frio.

[[v18-24-8]]

^<<v18-24-8,8>>^ Pelas chuvas das montanhas são molhados e, não tendo refúgio, abraçam-se com as rochas.

[[v18-24-9]]

^<<v18-24-9,9>>^ Orfãozinhos são arrancados ao peito, e dos pobres se toma penhor;

[[v18-24-10]]

^<<v18-24-10,10>>^ de modo que estes andam nus, sem roupa, e, famintos, arrastam os molhos.

[[v18-24-11]]

^<<v18-24-11,11>>^ Entre os muros desses perversos espremem o azeite, pisam-lhes o lagar; contudo, padecem sede.

[[v18-24-12]]

^<<v18-24-12,12>>^ Desde as cidades gemem os homens, e a alma dos feridos clama; e, contudo, Deus não tem isso por anormal.

[[v18-24-13]]

^<<v18-24-13,13>>^ Os perversos são inimigos da luz, não conhecem os seus caminhos, nem permanecem nas suas veredas.

[[v18-24-14]]

^<<v18-24-14,14>>^ De madrugada se levanta o homicida, mata ao pobre e ao necessitado, e de noite se torna ladrão.

[[v18-24-15]]

^<<v18-24-15,15>>^ Aguardam o crepúsculo os olhos do adúltero; este diz consigo: Ninguém me reconhecerá; e cobre o rosto.

[[v18-24-16]]

^<<v18-24-16,16>>^ Nas trevas minam as casas, de dia se conservam encerrados, nada querem com a luz.

[[v18-24-17]]

^<<v18-24-17,17>>^ Pois a manhã para todos eles é como sombra de morte; mas os terrores da noite lhes são familiares.

[[v18-24-18]]

^<<v18-24-18,18>>^ Vós dizeis: Os perversos são levados rapidamente na superfície das águas; maldita é a porção dos tais na terra; já não andam pelo caminho das vinhas.

[[v18-24-19]]

^<<v18-24-19,19>>^ A secura e o calor desfazem as águas da neve; assim faz a sepultura aos que pecaram.

[[v18-24-20]]

^<<v18-24-20,20>>^ A mãe se esquecerá deles, os vermes os comerão gostosamente; nunca mais haverá lembrança deles; como árvore será quebrado o injusto,

[[v18-24-21]]

^<<v18-24-21,21>>^ aquele que devora a estéril que não tem filhos e não faz o bem à viúva.

[[v18-24-22]]

^<<v18-24-22,22>>^ Não! Pelo contrário, Deus por sua força prolonga os dias dos valentes; veem-se eles de pé quando desesperavam da vida.

[[v18-24-23]]

^<<v18-24-23,23>>^ Ele lhes dá descanso, e nisso se estribam; os olhos de Deus estão nos caminhos deles.

[[v18-24-24]]

^<<v18-24-24,24>>^ São exaltados por breve tempo; depois, passam, colhidos como todos os mais; são cortados como as pontas das espigas.

[[v18-24-25]]

^<<v18-24-25,25>>^ Se não é assim, quem me desmentirá e anulará as minhas razões?

'''

xref:018-jo/018-jo-023.adoc#v18-23-0[&#60; Capítulo Anterior] | <<v18-24-0,Topo>> | xref:018-jo/018-jo-025.adoc#v18-25-0[Próximo Capítulo &#62;]