include::./index.adoc[]

[[v18-6-0]]
=== Jó, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-6-1]]

^<<v18-6-1,1>>^ Então, Jó respondeu:

[[v18-6-2]]

^<<v18-6-2,2>>^ Oh! Se a minha queixa, de fato, se pesasse, e contra ela, numa balança, se pusesse a minha miséria,

[[v18-6-3]]

^<<v18-6-3,3>>^ esta, na verdade, pesaria mais que a areia dos mares; por isso é que as minhas palavras foram precipitadas.

[[v18-6-4]]

^<<v18-6-4,4>>^ Porque as flechas do Todo-Poderoso estão em mim cravadas, e o meu espírito sorve o veneno delas; os terrores de Deus se arregimentam contra mim.

[[v18-6-5]]

^<<v18-6-5,5>>^ Zurrará o jumento montês junto à relva? Ou mugirá o boi junto à sua forragem?

[[v18-6-6]]

^<<v18-6-6,6>>^ Comer-se-á sem sal o que é insípido? Ou haverá sabor na clara do ovo?

[[v18-6-7]]

^<<v18-6-7,7>>^ Aquilo que a minha alma recusava tocar, isso é agora a minha comida repugnante.

[[v18-6-8]]

^<<v18-6-8,8>>^ Quem dera que se cumprisse o meu pedido, e que Deus me concedesse o que anelo!

[[v18-6-9]]

^<<v18-6-9,9>>^ Que fosse do agrado de Deus esmagar-me, que soltasse a sua mão e acabasse comigo!

[[v18-6-10]]

^<<v18-6-10,10>>^ Isto ainda seria a minha consolação, e saltaria de contente na minha dor, que ele não poupa; porque não tenho negado as palavras do Santo.

[[v18-6-11]]

^<<v18-6-11,11>>^ Por que esperar, se já não tenho forças? Por que prolongar a vida, se o meu fim é certo?

[[v18-6-12]]

^<<v18-6-12,12>>^ Acaso, a minha força é a força da pedra? Ou é de bronze a minha carne?

[[v18-6-13]]

^<<v18-6-13,13>>^ Não! Jamais haverá socorro para mim; foram afastados de mim os meus recursos.

[[v18-6-14]]

^<<v18-6-14,14>>^ Ao aflito deve o amigo mostrar compaixão, a menos que tenha abandonado o temor do Todo-Poderoso.

[[v18-6-15]]

^<<v18-6-15,15>>^ Meus irmãos aleivosamente me trataram; são como um ribeiro, como a torrente que transborda no vale,

[[v18-6-16]]

^<<v18-6-16,16>>^ turvada com o gelo e com a neve que nela se esconde,

[[v18-6-17]]

^<<v18-6-17,17>>^ torrente que no tempo do calor seca, emudece e desaparece do seu lugar.

[[v18-6-18]]

^<<v18-6-18,18>>^ Desviam-se as caravanas dos seus caminhos, sobem para lugares desolados e perecem.

[[v18-6-19]]

^<<v18-6-19,19>>^ As caravanas de Temá procuram essa torrente, os viajantes de Sabá por ela suspiram.

[[v18-6-20]]

^<<v18-6-20,20>>^ Ficam envergonhados por terem confiado; em chegando ali, confundem-se.

[[v18-6-21]]

^<<v18-6-21,21>>^ Assim também vós outros sois nada para mim; vedes os meus males e vos espantais.

[[v18-6-22]]

^<<v18-6-22,22>>^ Acaso, disse eu: dai-me um presente? Ou: oferecei-me um suborno da vossa fazenda?

[[v18-6-23]]

^<<v18-6-23,23>>^ Ou: livrai-me do poder do opressor? Ou: redimi-me das mãos dos tiranos?

[[v18-6-24]]

^<<v18-6-24,24>>^ Ensinai-me, e eu me calarei; dai-me a entender em que tenho errado.

[[v18-6-25]]

^<<v18-6-25,25>>^ Oh! Como são persuasivas as palavras retas! Mas que é o que repreende a vossa repreensão?

[[v18-6-26]]

^<<v18-6-26,26>>^ Acaso, pensais em reprovar as minhas palavras, ditas por um desesperado ao vento?

[[v18-6-27]]

^<<v18-6-27,27>>^ Até sobre o órfão lançaríeis sorte e especularíeis com o vosso amigo?

[[v18-6-28]]

^<<v18-6-28,28>>^ Agora, pois, se sois servidos, olhai para mim e vede que não minto na vossa cara.

[[v18-6-29]]

^<<v18-6-29,29>>^ Tornai a julgar, vos peço, e não haja iniquidade; tornai a julgar, e a justiça da minha causa triunfará.

[[v18-6-30]]

^<<v18-6-30,30>>^ Há iniquidade na minha língua? Não pode o meu paladar discernir coisas perniciosas?

'''

xref:018-jo/018-jo-005.adoc#v18-5-0[&#60; Capítulo Anterior] | <<v18-6-0,Topo>> | xref:018-jo/018-jo-007.adoc#v18-7-0[Próximo Capítulo &#62;]