include::./index.adoc[]

[[v18-35-0]]
=== Jó, 35
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-35-1]]

^<<v18-35-1,1>>^ Disse mais Eliú:

[[v18-35-2]]

^<<v18-35-2,2>>^ Achas que é justo dizeres: Maior é a minha justiça do que a de Deus?

[[v18-35-3]]

^<<v18-35-3,3>>^ Porque dizes: De que me serviria ela? Que proveito tiraria dela mais do que do meu pecado?

[[v18-35-4]]

^<<v18-35-4,4>>^ Dar-te-ei resposta, a ti e aos teus amigos contigo.

[[v18-35-5]]

^<<v18-35-5,5>>^ Atenta para os céus e vê; contempla as altas nuvens acima de ti.

[[v18-35-6]]

^<<v18-35-6,6>>^ Se pecas, que mal lhe causas tu? Se as tuas transgressões se multiplicam, que lhe fazes?

[[v18-35-7]]

^<<v18-35-7,7>>^ Se és justo, que lhe dás ou que recebe ele da tua mão?

[[v18-35-8]]

^<<v18-35-8,8>>^ A tua impiedade só pode fazer o mal ao homem como tu mesmo; e a tua justiça, dar proveito ao filho do homem.

[[v18-35-9]]

^<<v18-35-9,9>>^ Por causa das muitas opressões, os homens clamam, clamam por socorro contra o braço dos poderosos.

[[v18-35-10]]

^<<v18-35-10,10>>^ Mas ninguém diz: Onde está Deus, que me fez, que inspira canções de louvor durante a noite,

[[v18-35-11]]

^<<v18-35-11,11>>^ que nos ensina mais do que aos animais da terra e nos faz mais sábios do que as aves dos céus?

[[v18-35-12]]

^<<v18-35-12,12>>^ Clamam, porém ele não responde, por causa da arrogância dos maus.

[[v18-35-13]]

^<<v18-35-13,13>>^ Só gritos vazios Deus não ouvirá, nem atentará para eles o Todo-Poderoso.

[[v18-35-14]]

^<<v18-35-14,14>>^ Jó, ainda que dizes que não o vês, a tua causa está diante dele; por isso, espera nele.

[[v18-35-15]]

^<<v18-35-15,15>>^ Mas agora, porque Deus na sua ira não está punindo, nem fazendo muito caso das transgressões,

[[v18-35-16]]

^<<v18-35-16,16>>^ abres a tua boca, com palavras vãs, amontoando frases de ignorante.

'''

xref:018-jo/018-jo-034.adoc#v18-34-0[&#60; Capítulo Anterior] | <<v18-35-0,Topo>> | xref:018-jo/018-jo-036.adoc#v18-36-0[Próximo Capítulo &#62;]