include::./index.adoc[]

[[v18-31-0]]
=== Jó, 31
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-31-1]]

^<<v18-31-1,1>>^ Fiz aliança com meus olhos; como, pois, os fixaria eu numa donzela?

[[v18-31-2]]

^<<v18-31-2,2>>^ Que porção, pois, teria eu do Deus lá de cima e que herança, do Todo-Poderoso desde as alturas?

[[v18-31-3]]

^<<v18-31-3,3>>^ Acaso, não é a perdição para o iníquo, e o infortúnio, para os que praticam a maldade?

[[v18-31-4]]

^<<v18-31-4,4>>^ Ou não vê Deus os meus caminhos e não conta todos os meus passos?

[[v18-31-5]]

^<<v18-31-5,5>>^ Se andei com falsidade, e se o meu pé se apressou para o engano

[[v18-31-6]]

^<<v18-31-6,6>>^ (pese-me Deus em balanças fiéis e conhecerá a minha integridade);

[[v18-31-7]]

^<<v18-31-7,7>>^ se os meus passos se desviaram do caminho, e se o meu coração segue os meus olhos, e se às minhas mãos se apegou qualquer mancha,

[[v18-31-8]]

^<<v18-31-8,8>>^ então, semeie eu, e outro coma, e sejam arrancados os renovos do meu campo.

[[v18-31-9]]

^<<v18-31-9,9>>^ Se o meu coração se deixou seduzir por causa de mulher, se andei à espreita à porta do meu próximo,

[[v18-31-10]]

^<<v18-31-10,10>>^ então, moa minha mulher para outro, e outros se encurvem sobre ela.

[[v18-31-11]]

^<<v18-31-11,11>>^ Pois seria isso um crime hediondo, delito à punição de juízes;

[[v18-31-12]]

^<<v18-31-12,12>>^ pois seria fogo que consome até à destruição e desarraigaria toda a minha renda.

[[v18-31-13]]

^<<v18-31-13,13>>^ Se desprezei o direito do meu servo ou da minha serva, quando eles contendiam comigo,

[[v18-31-14]]

^<<v18-31-14,14>>^ então, que faria eu quando Deus se levantasse? E, inquirindo ele a causa, que lhe responderia eu?

[[v18-31-15]]

^<<v18-31-15,15>>^ Aquele que me formou no ventre materno não os fez também a eles? Ou não é o mesmo que nos formou na madre?

[[v18-31-16]]

^<<v18-31-16,16>>^ Se retive o que os pobres desejavam ou fiz desfalecer os olhos da viúva;

[[v18-31-17]]

^<<v18-31-17,17>>^ ou, se sozinho comi o meu bocado, e o órfão dele não participou

[[v18-31-18]]

^<<v18-31-18,18>>^ (Porque desde a minha mocidade cresceu comigo como se eu lhe fora o pai, e desde o ventre da minha mãe fui o guia da viúva.);

[[v18-31-19]]

^<<v18-31-19,19>>^ se a alguém vi perecer por falta de roupa e ao necessitado, por não ter coberta;

[[v18-31-20]]

^<<v18-31-20,20>>^ se os seus lombos não me abençoaram, se ele não se aquentava com a lã dos meus cordeiros;

[[v18-31-21]]

^<<v18-31-21,21>>^ se eu levantei a mão contra o órfão, por me ver apoiado pelos juízes da porta,

[[v18-31-22]]

^<<v18-31-22,22>>^ então, caia a omoplata do meu ombro, e seja arrancado o meu braço da articulação.

[[v18-31-23]]

^<<v18-31-23,23>>^ Porque o castigo de Deus seria para mim um assombro, e eu não poderia enfrentar a sua majestade.

[[v18-31-24]]

^<<v18-31-24,24>>^ Se no ouro pus a minha esperança ou disse ao ouro fino: em ti confio;

[[v18-31-25]]

^<<v18-31-25,25>>^ se me alegrei por serem grandes os meus bens e por ter a minha mão alcançado muito;

[[v18-31-26]]

^<<v18-31-26,26>>^ se olhei para o sol, quando resplandecia, ou para a lua, que caminhava esplendente,

[[v18-31-27]]

^<<v18-31-27,27>>^ e o meu coração se deixou enganar em oculto, e beijos lhes atirei com a mão,

[[v18-31-28]]

^<<v18-31-28,28>>^ também isto seria delito à punição de juízes; pois assim negaria eu ao Deus lá de cima.

[[v18-31-29]]

^<<v18-31-29,29>>^ Se me alegrei da desgraça do que me tem ódio e se exultei quando o mal o atingiu

[[v18-31-30]]

^<<v18-31-30,30>>^ (Também não deixei pecar a minha boca, pedindo com imprecações a sua morte.);

[[v18-31-31]]

^<<v18-31-31,31>>^ se a gente da minha tenda não disse: Ah! Quem haverá aí que não se saciou de carne provida por ele

[[v18-31-32]]

^<<v18-31-32,32>>^ (O estrangeiro não pernoitava na rua; as minhas portas abria ao viandante.)!

[[v18-31-33]]

^<<v18-31-33,33>>^ Se, como Adão, encobri as minhas transgressões, ocultando o meu delito no meu seio;

[[v18-31-34]]

^<<v18-31-34,34>>^ porque eu temia a grande multidão, e o desprezo das famílias me apavorava, de sorte que me calei e não saí da porta.

[[v18-31-35]]

^<<v18-31-35,35>>^ Tomara eu tivesse quem me ouvisse! Eis aqui a minha defesa assinada! Que o Todo-Poderoso me responda! Que o meu adversário escreva a sua acusação!

[[v18-31-36]]

^<<v18-31-36,36>>^ Por certo que a levaria sobre o meu ombro, atá-la-ia sobre mim como coroa;

[[v18-31-37]]

^<<v18-31-37,37>>^ mostrar-lhe-ia o número dos meus passos; como príncipe me chegaria a ele.

[[v18-31-38]]

^<<v18-31-38,38>>^ Se a minha terra clamar contra mim, e se os seus sulcos juntamente chorarem;

[[v18-31-39]]

^<<v18-31-39,39>>^ se comi os seus frutos sem tê-la pago devidamente e causei a morte aos seus donos,

[[v18-31-40]]

^<<v18-31-40,40>>^ por trigo me produza cardos, e por cevada, joio. Fim das palavras de Jó.

'''

xref:018-jo/018-jo-030.adoc#v18-30-0[&#60; Capítulo Anterior] | <<v18-31-0,Topo>> | xref:018-jo/018-jo-032.adoc#v18-32-0[Próximo Capítulo &#62;]