include::./index.adoc[]

[[v18-22-0]]
=== Jó, 22
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-22-1]]

^<<v18-22-1,1>>^ Então, respondeu Elifaz, o temanita:

[[v18-22-2]]

^<<v18-22-2,2>>^ Porventura, será o homem de algum proveito a Deus? Antes, o sábio é só útil a si mesmo.

[[v18-22-3]]

^<<v18-22-3,3>>^ Ou tem o Todo-Poderoso interesse em que sejas justo ou algum lucro em que faças perfeitos os teus caminhos?

[[v18-22-4]]

^<<v18-22-4,4>>^ Ou te repreende pelo teu temor de Deus ou entra contra ti em juízo?

[[v18-22-5]]

^<<v18-22-5,5>>^ Porventura, não é grande a tua malícia, e sem termo, as tuas iniquidades?

[[v18-22-6]]

^<<v18-22-6,6>>^ Porque sem causa tomaste penhores a teu irmão e aos seminus despojaste das suas roupas.

[[v18-22-7]]

^<<v18-22-7,7>>^ Não deste água a beber ao cansado e ao faminto retiveste o pão.

[[v18-22-8]]

^<<v18-22-8,8>>^ Ao braço forte pertencia a terra, e só os homens favorecidos habitavam nela.

[[v18-22-9]]

^<<v18-22-9,9>>^ As viúvas despediste de mãos vazias, e os braços dos órfãos foram quebrados.

[[v18-22-10]]

^<<v18-22-10,10>>^ Por isso, estás cercado de laços, e repentino pavor te conturba

[[v18-22-11]]

^<<v18-22-11,11>>^ ou trevas, em que nada vês; e águas transbordantes te cobrem.

[[v18-22-12]]

^<<v18-22-12,12>>^ Porventura, não está Deus nas alturas do céu? Olha para as estrelas mais altas. Que altura!

[[v18-22-13]]

^<<v18-22-13,13>>^ E dizes: Que sabe Deus? Acaso, poderá ele julgar através de densa escuridão?

[[v18-22-14]]

^<<v18-22-14,14>>^ Grossas nuvens o encobrem, de modo que não pode ver; ele passeia pela abóbada do céu.

[[v18-22-15]]

^<<v18-22-15,15>>^ Queres seguir a rota antiga, que os homens iníquos pisaram?

[[v18-22-16]]

^<<v18-22-16,16>>^ Estes foram arrebatados antes do tempo; o seu fundamento, uma torrente o arrasta.

[[v18-22-17]]

^<<v18-22-17,17>>^ Diziam a Deus: Retira-te de nós. E: Que pode fazer-nos o Todo-Poderoso?

[[v18-22-18]]

^<<v18-22-18,18>>^ Contudo, ele enchera de bens as suas casas. Longe de mim o conselho dos perversos!

[[v18-22-19]]

^<<v18-22-19,19>>^ Os justos o veem e se alegram, e o inocente escarnece deles,

[[v18-22-20]]

^<<v18-22-20,20>>^ dizendo: Na verdade, os nossos adversários foram destruídos, e o fogo consumiu o resto deles.

[[v18-22-21]]

^<<v18-22-21,21>>^ Reconcilia-te, pois, com ele e tem paz, e assim te sobrevirá o bem.

[[v18-22-22]]

^<<v18-22-22,22>>^ Aceita, peço-te, a instrução que profere e põe as suas palavras no teu coração.

[[v18-22-23]]

^<<v18-22-23,23>>^ Se te converteres ao Todo-Poderoso, serás restabelecido; se afastares a injustiça da tua tenda

[[v18-22-24]]

^<<v18-22-24,24>>^ e deitares ao pó o teu ouro e o ouro de Ofir entre pedras dos ribeiros,

[[v18-22-25]]

^<<v18-22-25,25>>^ então, o Todo-Poderoso será o teu ouro e a tua prata escolhida.

[[v18-22-26]]

^<<v18-22-26,26>>^ Deleitar-te-ás, pois, no Todo-Poderoso e levantarás o rosto para Deus.

[[v18-22-27]]

^<<v18-22-27,27>>^ Orarás a ele, e ele te ouvirá; e pagarás os teus votos.

[[v18-22-28]]

^<<v18-22-28,28>>^ Se projetas alguma coisa, ela te sairá bem, e a luz brilhará em teus caminhos.

[[v18-22-29]]

^<<v18-22-29,29>>^ Se estes descem, então, dirás: Para cima! E Deus salvará o humilde

[[v18-22-30]]

^<<v18-22-30,30>>^ e livrará até ao que não é inocente; sim, será libertado, graças à pureza de tuas mãos.

'''

xref:018-jo/018-jo-021.adoc#v18-21-0[&#60; Capítulo Anterior] | <<v18-22-0,Topo>> | xref:018-jo/018-jo-023.adoc#v18-23-0[Próximo Capítulo &#62;]