include::./index.adoc[]

[[v18-30-0]]
=== Jó, 30
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-30-1]]

^<<v18-30-1,1>>^ Mas agora se riem de mim os de menos idade do que eu, e cujos pais eu teria desdenhado de pôr ao lado dos cães do meu rebanho.

[[v18-30-2]]

^<<v18-30-2,2>>^ De que também me serviria a força das suas mãos, homens cujo vigor já pereceu?

[[v18-30-3]]

^<<v18-30-3,3>>^ De míngua e fome se debilitaram; roem os lugares secos, desde muito em ruínas e desolados.

[[v18-30-4]]

^<<v18-30-4,4>>^ Apanham malvas e folhas dos arbustos e se sustentam de raízes de zimbro.

[[v18-30-5]]

^<<v18-30-5,5>>^ Do meio dos homens são expulsos; grita-se contra eles, como se grita atrás de um ladrão;

[[v18-30-6]]

^<<v18-30-6,6>>^ habitam nos desfiladeiros sombrios, nas cavernas da terra e das rochas.

[[v18-30-7]]

^<<v18-30-7,7>>^ Bramam entre os arbustos e se ajuntam debaixo dos espinheiros.

[[v18-30-8]]

^<<v18-30-8,8>>^ São filhos de doidos, raça infame, e da terra são escorraçados.

[[v18-30-9]]

^<<v18-30-9,9>>^ Mas agora sou a sua canção de motejo e lhes sirvo de provérbio.

[[v18-30-10]]

^<<v18-30-10,10>>^ Abominam-me, fogem para longe de mim e não se abstêm de me cuspir no rosto.

[[v18-30-11]]

^<<v18-30-11,11>>^ Porque Deus afrouxou a corda do meu arco e me oprimiu; pelo que sacudiram de si o freio perante o meu rosto.

[[v18-30-12]]

^<<v18-30-12,12>>^ À direita se levanta uma súcia, e me empurra, e contra mim prepara o seu caminho de destruição.

[[v18-30-13]]

^<<v18-30-13,13>>^ Arruínam a minha vereda, promovem a minha calamidade; gente para quem já não há socorro.

[[v18-30-14]]

^<<v18-30-14,14>>^ Vêm contra mim como por uma grande brecha e se revolvem avante entre as ruínas.

[[v18-30-15]]

^<<v18-30-15,15>>^ Sobrevieram-me pavores, como pelo vento é varrida a minha honra; como nuvem passou a minha felicidade.

[[v18-30-16]]

^<<v18-30-16,16>>^ Agora, dentro de mim se me derrama a alma; os dias da aflição se apoderaram de mim.

[[v18-30-17]]

^<<v18-30-17,17>>^ A noite me verruma os ossos e os desloca, e não descansa o mal que me rói.

[[v18-30-18]]

^<<v18-30-18,18>>^ Pela grande violência do meu mal está desfigurada a minha veste, mal que me cinge como a gola da minha túnica.

[[v18-30-19]]

^<<v18-30-19,19>>^ Deus, tu me lançaste na lama, e me tornei semelhante ao pó e à cinza.

[[v18-30-20]]

^<<v18-30-20,20>>^ Clamo a ti, e não me respondes; estou em pé, mas apenas olhas para mim.

[[v18-30-21]]

^<<v18-30-21,21>>^ Tu foste cruel comigo; com a força da tua mão tu me combates.

[[v18-30-22]]

^<<v18-30-22,22>>^ Levantas-me sobre o vento e me fazes cavalgá-lo; dissolves-me no estrondo da tempestade.

[[v18-30-23]]

^<<v18-30-23,23>>^ Pois eu sei que me levarás à morte e à casa destinada a todo vivente.

[[v18-30-24]]

^<<v18-30-24,24>>^ De um montão de ruínas não estenderá o homem a mão e na sua desventura não levantará um grito por socorro?

[[v18-30-25]]

^<<v18-30-25,25>>^ Acaso, não chorei sobre aquele que atravessava dias difíceis ou não se angustiou a minha alma pelo necessitado?

[[v18-30-26]]

^<<v18-30-26,26>>^ Aguardava eu o bem, e eis que me veio o mal; esperava a luz, veio-me a escuridão.

[[v18-30-27]]

^<<v18-30-27,27>>^ O meu íntimo se agita sem cessar; e dias de aflição me sobrevêm.

[[v18-30-28]]

^<<v18-30-28,28>>^ Ando de luto, sem a luz do sol; levanto-me na congregação e clamo por socorro.

[[v18-30-29]]

^<<v18-30-29,29>>^ Sou irmão dos chacais e companheiro de avestruzes.

[[v18-30-30]]

^<<v18-30-30,30>>^ Enegrecida se me cai a pele, e os meus ossos queimam em febre.

[[v18-30-31]]

^<<v18-30-31,31>>^ Por isso, a minha harpa se me tornou em prantos de luto, e a minha flauta, em voz dos que choram.

'''

xref:018-jo/018-jo-029.adoc#v18-29-0[&#60; Capítulo Anterior] | <<v18-30-0,Topo>> | xref:018-jo/018-jo-031.adoc#v18-31-0[Próximo Capítulo &#62;]