include::./index.adoc[]

[[v18-17-0]]
=== Jó, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-17-1]]

^<<v18-17-1,1>>^ O meu espírito se vai consumindo, os meus dias se vão apagando, e só tenho perante mim a sepultura.

[[v18-17-2]]

^<<v18-17-2,2>>^ Estou, de fato, cercado de zombadores, e os meus olhos são obrigados a lhes contemplar a provocação.

[[v18-17-3]]

^<<v18-17-3,3>>^ Dá-me, pois, um penhor; sê o meu fiador para contigo mesmo; quem mais haverá que se possa comprometer comigo?

[[v18-17-4]]

^<<v18-17-4,4>>^ Porque ao seu coração encobriste o entendimento, pelo que não os exaltarás.

[[v18-17-5]]

^<<v18-17-5,5>>^ Se alguém oferece os seus amigos como presa, os olhos de seus filhos desfalecerão.

[[v18-17-6]]

^<<v18-17-6,6>>^ Mas a mim me pôs por provérbio dos povos; tornei-me como aquele em cujo rosto se cospe.

[[v18-17-7]]

^<<v18-17-7,7>>^ Pelo que já se escureceram de mágoa os meus olhos, e já todos os meus membros são como a sombra;

[[v18-17-8]]

^<<v18-17-8,8>>^ os retos pasmam disto, e o inocente se levanta contra o ímpio.

[[v18-17-9]]

^<<v18-17-9,9>>^ Contudo, o justo segue o seu caminho, e o puro de mãos cresce mais e mais em força.

[[v18-17-10]]

^<<v18-17-10,10>>^ Mas tornai-vos, todos vós, e vinde cá; porque sábio nenhum acharei entre vós.

[[v18-17-11]]

^<<v18-17-11,11>>^ Os meus dias passaram, e se malograram os meus propósitos, as aspirações do meu coração.

[[v18-17-12]]

^<<v18-17-12,12>>^ Convertem-me a noite em dia, e a luz, dizem, está perto das trevas.

[[v18-17-13]]

^<<v18-17-13,13>>^ Mas, se eu aguardo já a sepultura por minha casa; se nas trevas estendo a minha cama;

[[v18-17-14]]

^<<v18-17-14,14>>^ se ao sepulcro eu clamo: tu és meu pai; e aos vermes: vós sois minha mãe e minha irmã,

[[v18-17-15]]

^<<v18-17-15,15>>^ onde está, pois, a minha esperança? Sim, a minha esperança, quem a poderá ver?

[[v18-17-16]]

^<<v18-17-16,16>>^ Ela descerá até às portas da morte, quando juntamente no pó teremos descanso.

'''

xref:018-jo/018-jo-016.adoc#v18-16-0[&#60; Capítulo Anterior] | <<v18-17-0,Topo>> | xref:018-jo/018-jo-018.adoc#v18-18-0[Próximo Capítulo &#62;]