include::./index.adoc[]

[[v18-37-0]]
=== Jó, 37
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-37-1]]

^<<v18-37-1,1>>^ Sobre isto treme também o meu coração e salta do seu lugar.

[[v18-37-2]]

^<<v18-37-2,2>>^ Dai ouvidos ao trovão de Deus, estrondo que sai da sua boca;

[[v18-37-3]]

^<<v18-37-3,3>>^ ele o solta por debaixo de todos os céus, e o seu relâmpago, até aos confins da terra.

[[v18-37-4]]

^<<v18-37-4,4>>^ Depois deste, ruge a sua voz, troveja com o estrondo da sua majestade, e já ele não retém o relâmpago quando lhe ouvem a voz.

[[v18-37-5]]

^<<v18-37-5,5>>^ Com a sua voz troveja Deus maravilhosamente; faz grandes coisas, que nós não compreendemos.

[[v18-37-6]]

^<<v18-37-6,6>>^ Porque ele diz à neve: Cai sobre a terra; e à chuva e ao aguaceiro: Sede fortes.

[[v18-37-7]]

^<<v18-37-7,7>>^ Assim, torna ele inativas as mãos de todos os homens, para que reconheçam as obras dele.

[[v18-37-8]]

^<<v18-37-8,8>>^ E as alimárias entram nos seus esconderijos e ficam nas suas cavernas.

[[v18-37-9]]

^<<v18-37-9,9>>^ De suas recâmaras sai o pé de vento, e, dos ventos do norte, o frio.

[[v18-37-10]]

^<<v18-37-10,10>>^ Pelo sopro de Deus se dá a geada, e as largas águas se congelam.

[[v18-37-11]]

^<<v18-37-11,11>>^ Também de umidade carrega as densas nuvens, nuvens que espargem os relâmpagos.

[[v18-37-12]]

^<<v18-37-12,12>>^ Então, elas, segundo o rumo que ele dá, se espalham para uma e outra direção, para fazerem tudo o que lhes ordena sobre a redondeza da terra.

[[v18-37-13]]

^<<v18-37-13,13>>^ E tudo isso faz ele vir para disciplina, se convém à terra, ou para exercer a sua misericórdia.

[[v18-37-14]]

^<<v18-37-14,14>>^ Inclina, Jó, os ouvidos a isto, para e considera as maravilhas de Deus.

[[v18-37-15]]

^<<v18-37-15,15>>^ Porventura, sabes tu como Deus as opera e como faz resplandecer o relâmpago da sua nuvem?

[[v18-37-16]]

^<<v18-37-16,16>>^ Tens tu notícia do equilíbrio das nuvens e das maravilhas daquele que é perfeito em conhecimento?

[[v18-37-17]]

^<<v18-37-17,17>>^ Que faz aquecer as tuas vestes, quando há calma sobre a terra por causa do vento sul?

[[v18-37-18]]

^<<v18-37-18,18>>^ Ou estendeste com ele o firmamento, que é sólido como espelho fundido?

[[v18-37-19]]

^<<v18-37-19,19>>^ Ensina-nos o que lhe diremos; porque nós, envoltos em trevas, nada lhe podemos expor.

[[v18-37-20]]

^<<v18-37-20,20>>^ Contar-lhe-ia alguém o que tenho dito? Seria isso desejar o homem ser devorado.

[[v18-37-21]]

^<<v18-37-21,21>>^ Eis que o homem não pode olhar para o sol, que brilha no céu, uma vez passado o vento que o deixa limpo.

[[v18-37-22]]

^<<v18-37-22,22>>^ Do norte vem o áureo esplendor, pois Deus está cercado de tremenda majestade.

[[v18-37-23]]

^<<v18-37-23,23>>^ Ao Todo-Poderoso, não o podemos alcançar; ele é grande em poder, porém não perverte o juízo e a plenitude da justiça.

[[v18-37-24]]

^<<v18-37-24,24>>^ Por isso, os homens o temem; ele não olha para os que se julgam sábios.

'''

xref:018-jo/018-jo-036.adoc#v18-36-0[&#60; Capítulo Anterior] | <<v18-37-0,Topo>> | xref:018-jo/018-jo-038.adoc#v18-38-0[Próximo Capítulo &#62;]