include::./index.adoc[]

[[v18-5-0]]
=== Jó, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-5-1]]

^<<v18-5-1,1>>^ Chama agora! Haverá alguém que te atenda? E para qual dos santos anjos te virarás?

[[v18-5-2]]

^<<v18-5-2,2>>^ Porque a ira do louco o destrói, e o zelo do tolo o mata.

[[v18-5-3]]

^<<v18-5-3,3>>^ Bem vi eu o louco lançar raízes; mas logo declarei maldita a sua habitação.

[[v18-5-4]]

^<<v18-5-4,4>>^ Seus filhos estão longe do socorro, são espezinhados às portas, e não há quem os livre.

[[v18-5-5]]

^<<v18-5-5,5>>^ A sua messe, o faminto a devora e até do meio dos espinhos a arrebata; e o intrigante abocanha os seus bens.

[[v18-5-6]]

^<<v18-5-6,6>>^ Porque a aflição não vem do pó, e não é da terra que brota o enfado.

[[v18-5-7]]

^<<v18-5-7,7>>^ Mas o homem nasce para o enfado, como as faíscas das brasas voam para cima.

[[v18-5-8]]

^<<v18-5-8,8>>^ Quanto a mim, eu buscaria a Deus e a ele entregaria a minha causa;

[[v18-5-9]]

^<<v18-5-9,9>>^ ele faz coisas grandes e inescrutáveis e maravilhas que não se podem contar;

[[v18-5-10]]

^<<v18-5-10,10>>^ faz chover sobre a terra e envia águas sobre os campos,

[[v18-5-11]]

^<<v18-5-11,11>>^ para pôr os abatidos num lugar alto e para que os enlutados se alegrem da maior ventura.

[[v18-5-12]]

^<<v18-5-12,12>>^ Ele frustra as maquinações dos astutos, para que as suas mãos não possam realizar seus projetos.

[[v18-5-13]]

^<<v18-5-13,13>>^ Ele apanha os sábios na sua própria astúcia; e o conselho dos que tramam se precipita.

[[v18-5-14]]

^<<v18-5-14,14>>^ Eles de dia encontram as trevas; ao meio-dia andam como de noite, às apalpadelas.

[[v18-5-15]]

^<<v18-5-15,15>>^ Porém Deus salva da espada que lhes sai da boca, salva o necessitado da mão do poderoso.

[[v18-5-16]]

^<<v18-5-16,16>>^ Assim, há esperança para o pobre, e a iniquidade tapa a sua própria boca.

[[v18-5-17]]

^<<v18-5-17,17>>^ Bem-aventurado é o homem a quem Deus disciplina; não desprezes, pois, a disciplina do Todo-Poderoso.

[[v18-5-18]]

^<<v18-5-18,18>>^ Porque ele faz a ferida e ele mesmo a ata; ele fere, e as suas mãos curam.

[[v18-5-19]]

^<<v18-5-19,19>>^ De seis angústias te livrará, e na sétima o mal te não tocará.

[[v18-5-20]]

^<<v18-5-20,20>>^ Na fome te livrará da morte; na guerra, do poder da espada.

[[v18-5-21]]

^<<v18-5-21,21>>^ Do açoite da língua estarás abrigado e, quando vier a assolação, não a temerás.

[[v18-5-22]]

^<<v18-5-22,22>>^ Da assolação e da fome te rirás e das feras da terra não terás medo.

[[v18-5-23]]

^<<v18-5-23,23>>^ Porque até com as pedras do campo terás a tua aliança, e os animais da terra viverão em paz contigo.

[[v18-5-24]]

^<<v18-5-24,24>>^ Saberás que a paz é a tua tenda, percorrerás as tuas possessões, e nada te faltará.

[[v18-5-25]]

^<<v18-5-25,25>>^ Saberás também que se multiplicará a tua descendência, e a tua posteridade, como a erva da terra.

[[v18-5-26]]

^<<v18-5-26,26>>^ Em robusta velhice entrarás para a sepultura, como se recolhe o feixe de trigo a seu tempo.

[[v18-5-27]]

^<<v18-5-27,27>>^ Eis que isto já o havemos inquirido, e assim é; ouve-o e medita nisso para teu bem.

'''

xref:018-jo/018-jo-004.adoc#v18-4-0[&#60; Capítulo Anterior] | <<v18-5-0,Topo>> | xref:018-jo/018-jo-006.adoc#v18-6-0[Próximo Capítulo &#62;]