include::./index.adoc[]

[[v18-29-0]]
=== Jó, 29
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-29-1]]

^<<v18-29-1,1>>^ Prosseguiu Jó no seu discurso e disse:

[[v18-29-2]]

^<<v18-29-2,2>>^ Ah! Quem me dera ser como fui nos meses passados, como nos dias em que Deus me guardava!

[[v18-29-3]]

^<<v18-29-3,3>>^ Quando fazia resplandecer a sua lâmpada sobre a minha cabeça, quando eu, guiado por sua luz, caminhava pelas trevas;

[[v18-29-4]]

^<<v18-29-4,4>>^ como fui nos dias do meu vigor, quando a amizade de Deus estava sobre a minha tenda;

[[v18-29-5]]

^<<v18-29-5,5>>^ quando o Todo-Poderoso ainda estava comigo, e os meus filhos, em redor de mim;

[[v18-29-6]]

^<<v18-29-6,6>>^ quando eu lavava os pés em leite, e da rocha me corriam ribeiros de azeite.

[[v18-29-7]]

^<<v18-29-7,7>>^ Quando eu saía para a porta da cidade, e na praça me era dado sentar-me,

[[v18-29-8]]

^<<v18-29-8,8>>^ os moços me viam e se retiravam; os idosos se levantavam e se punham em pé;

[[v18-29-9]]

^<<v18-29-9,9>>^ os príncipes reprimiam as suas palavras e punham a mão sobre a boca;

[[v18-29-10]]

^<<v18-29-10,10>>^ a voz dos nobres emudecia, e a sua língua se apegava ao paladar.

[[v18-29-11]]

^<<v18-29-11,11>>^ Ouvindo-me algum ouvido, esse me chamava feliz; vendo-me algum olho, dava testemunho de mim;

[[v18-29-12]]

^<<v18-29-12,12>>^ porque eu livrava os pobres que clamavam e também o órfão que não tinha quem o socorresse.

[[v18-29-13]]

^<<v18-29-13,13>>^ A bênção do que estava a perecer vinha sobre mim, e eu fazia rejubilar-se o coração da viúva.

[[v18-29-14]]

^<<v18-29-14,14>>^ Eu me cobria de justiça, e esta me servia de veste; como manto e turbante era a minha equidade.

[[v18-29-15]]

^<<v18-29-15,15>>^ Eu me fazia de olhos para o cego e de pés para o coxo.

[[v18-29-16]]

^<<v18-29-16,16>>^ Dos necessitados era pai e até as causas dos desconhecidos eu examinava.

[[v18-29-17]]

^<<v18-29-17,17>>^ Eu quebrava os queixos do iníquo e dos seus dentes lhe fazia eu cair a vítima.

[[v18-29-18]]

^<<v18-29-18,18>>^ Eu dizia: no meu ninho expirarei, multiplicarei os meus dias como a areia.

[[v18-29-19]]

^<<v18-29-19,19>>^ A minha raiz se estenderá até às águas, e o orvalho ficará durante a noite sobre os meus ramos;

[[v18-29-20]]

^<<v18-29-20,20>>^ a minha honra se renovará em mim, e o meu arco se reforçará na minha mão.

[[v18-29-21]]

^<<v18-29-21,21>>^ Os que me ouviam esperavam o meu conselho e guardavam silêncio para ouvi-lo.

[[v18-29-22]]

^<<v18-29-22,22>>^ Havendo eu falado, não replicavam; as minhas palavras caíam sobre eles como orvalho.

[[v18-29-23]]

^<<v18-29-23,23>>^ Esperavam-me como à chuva, abriam a boca como à chuva de primavera.

[[v18-29-24]]

^<<v18-29-24,24>>^ Sorria-me para eles quando não tinham confiança; e a luz do meu rosto não desprezavam.

[[v18-29-25]]

^<<v18-29-25,25>>^ Eu lhes escolhia o caminho, assentava-me como chefe e habitava como rei entre as suas tropas, como quem consola os que pranteiam.

'''

xref:018-jo/018-jo-028.adoc#v18-28-0[&#60; Capítulo Anterior] | <<v18-29-0,Topo>> | xref:018-jo/018-jo-030.adoc#v18-30-0[Próximo Capítulo &#62;]