include::./index.adoc[]

[[v18-28-0]]
=== Jó, 28
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-28-1]]

^<<v18-28-1,1>>^ Na verdade, a prata tem suas minas, e o ouro, que se refina, o seu lugar.

[[v18-28-2]]

^<<v18-28-2,2>>^ O ferro tira-se da terra, e da pedra se funde o cobre.

[[v18-28-3]]

^<<v18-28-3,3>>^ Os homens põem termo à escuridão e até aos últimos confins procuram as pedras ocultas nas trevas e na densa escuridade.

[[v18-28-4]]

^<<v18-28-4,4>>^ Abrem entrada para minas longe da habitação dos homens, esquecidos dos transeuntes; e, assim, longe deles, dependurados, oscilam de um lado para outro.

[[v18-28-5]]

^<<v18-28-5,5>>^ Da terra procede o pão, mas embaixo é revolvida como por fogo.

[[v18-28-6]]

^<<v18-28-6,6>>^ Nas suas pedras se encontra safira, e há pó que contém ouro.

[[v18-28-7]]

^<<v18-28-7,7>>^ Essa vereda, a ave de rapina a ignora, e jamais a viram os olhos do falcão.

[[v18-28-8]]

^<<v18-28-8,8>>^ Nunca a pisaram feras majestosas, nem o leãozinho passou por ela.

[[v18-28-9]]

^<<v18-28-9,9>>^ Estende o homem a mão contra o rochedo e revolve os montes desde as suas raízes.

[[v18-28-10]]

^<<v18-28-10,10>>^ Abre canais nas pedras, e os seus olhos veem tudo o que há de mais precioso.

[[v18-28-11]]

^<<v18-28-11,11>>^ Tapa os veios de água, e nem uma gota sai deles, e traz à luz o que estava escondido.

[[v18-28-12]]

^<<v18-28-12,12>>^ Mas onde se achará a sabedoria? E onde está o lugar do entendimento?

[[v18-28-13]]

^<<v18-28-13,13>>^ O homem não conhece o valor dela, nem se acha ela na terra dos viventes.

[[v18-28-14]]

^<<v18-28-14,14>>^ O abismo diz: Ela não está em mim; e o mar diz: Não está comigo.

[[v18-28-15]]

^<<v18-28-15,15>>^ Não se dá por ela ouro fino, nem se pesa prata em câmbio dela.

[[v18-28-16]]

^<<v18-28-16,16>>^ O seu valor não se pode avaliar pelo ouro de Ofir, nem pelo precioso ônix, nem pela safira.

[[v18-28-17]]

^<<v18-28-17,17>>^ O ouro não se iguala a ela, nem o cristal; ela não se trocará por joia de ouro fino;

[[v18-28-18]]

^<<v18-28-18,18>>^ ela faz esquecer o coral e o cristal; a aquisição da sabedoria é melhor que a das pérolas.

[[v18-28-19]]

^<<v18-28-19,19>>^ Não se lhe igualará o topázio da Etiópia, nem se pode avaliar por ouro puro.

[[v18-28-20]]

^<<v18-28-20,20>>^ Donde, pois, vem a sabedoria, e onde está o lugar do entendimento?

[[v18-28-21]]

^<<v18-28-21,21>>^ Está encoberta aos olhos de todo vivente e oculta às aves do céu.

[[v18-28-22]]

^<<v18-28-22,22>>^ O abismo e a morte dizem: Ouvimos com os nossos ouvidos a sua fama.

[[v18-28-23]]

^<<v18-28-23,23>>^ Deus lhe entende o caminho, e ele é quem sabe o seu lugar.

[[v18-28-24]]

^<<v18-28-24,24>>^ Porque ele perscruta até as extremidades da terra, vê tudo o que há debaixo dos céus.

[[v18-28-25]]

^<<v18-28-25,25>>^ Quando regulou o peso do vento e fixou a medida das águas;

[[v18-28-26]]

^<<v18-28-26,26>>^ quando determinou leis para a chuva e caminho para o relâmpago dos trovões,

[[v18-28-27]]

^<<v18-28-27,27>>^ então, viu ele a sabedoria e a manifestou; estabeleceu-a e também a esquadrinhou.

[[v18-28-28]]

^<<v18-28-28,28>>^ E disse ao homem: Eis que o temor do Senhor é a sabedoria, e o apartar-se do mal é o entendimento.

'''

xref:018-jo/018-jo-027.adoc#v18-27-0[&#60; Capítulo Anterior] | <<v18-28-0,Topo>> | xref:018-jo/018-jo-029.adoc#v18-29-0[Próximo Capítulo &#62;]