include::./index.adoc[]

[[v18-27-0]]
=== Jó, 27
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-27-1]]

^<<v18-27-1,1>>^ Prosseguindo Jó em seu discurso, disse:

[[v18-27-2]]

^<<v18-27-2,2>>^ Tão certo como vive Deus, que me tirou o direito, e o Todo-Poderoso, que amargurou a minha alma,

[[v18-27-3]]

^<<v18-27-3,3>>^ enquanto em mim estiver a minha vida, e o sopro de Deus nos meus narizes,

[[v18-27-4]]

^<<v18-27-4,4>>^ nunca os meus lábios falarão injustiça, nem a minha língua pronunciará engano.

[[v18-27-5]]

^<<v18-27-5,5>>^ Longe de mim que eu vos dê razão! Até que eu expire, nunca afastarei de mim a minha integridade.

[[v18-27-6]]

^<<v18-27-6,6>>^ À minha justiça me apegarei e não a largarei; não me reprova a minha consciência por qualquer dia da minha vida.

[[v18-27-7]]

^<<v18-27-7,7>>^ Seja como o perverso o meu inimigo, e o que se levantar contra mim, como o injusto.

[[v18-27-8]]

^<<v18-27-8,8>>^ Porque qual será a esperança do ímpio, quando lhe for cortada a vida, quando Deus lhe arrancar a alma?

[[v18-27-9]]

^<<v18-27-9,9>>^ Acaso, ouvirá Deus o seu clamor, em lhe sobrevindo a tribulação?

[[v18-27-10]]

^<<v18-27-10,10>>^ Deleitar-se-á o perverso no Todo-Poderoso e invocará a Deus em todo o tempo?

[[v18-27-11]]

^<<v18-27-11,11>>^ Ensinar-vos-ei o que encerra a mão de Deus e não vos ocultarei o que está com o Todo-Poderoso.

[[v18-27-12]]

^<<v18-27-12,12>>^ Eis que todos vós já vistes isso; por que, pois, alimentais vãs noções?

[[v18-27-13]]

^<<v18-27-13,13>>^ Eis qual será da parte de Deus a porção do perverso e a herança que os opressores receberão do Todo-Poderoso:

[[v18-27-14]]

^<<v18-27-14,14>>^ Se os seus filhos se multiplicarem, será para a espada, e a sua prole não se fartará de pão.

[[v18-27-15]]

^<<v18-27-15,15>>^ Os que ficarem dela, a peste os enterrará, e as suas viúvas não chorarão.

[[v18-27-16]]

^<<v18-27-16,16>>^ Se o perverso amontoar prata como pó e acumular vestes como barro,

[[v18-27-17]]

^<<v18-27-17,17>>^ ele os acumulará, mas o justo é que os vestirá, e o inocente repartirá a prata.

[[v18-27-18]]

^<<v18-27-18,18>>^ Ele edifica a sua casa como a da traça e como a choça que o vigia constrói.

[[v18-27-19]]

^<<v18-27-19,19>>^ Rico se deita com a sua riqueza, abre os seus olhos e já não a vê.

[[v18-27-20]]

^<<v18-27-20,20>>^ Pavores se apoderam dele como inundação, de noite a tempestade o arrebata.

[[v18-27-21]]

^<<v18-27-21,21>>^ O vento oriental o leva, e ele se vai; varre-o com ímpeto do seu lugar.

[[v18-27-22]]

^<<v18-27-22,22>>^ Deus lança isto sobre ele e não o poupa, a ele que procura fugir precipitadamente da sua mão;

[[v18-27-23]]

^<<v18-27-23,23>>^ à sua queda lhe batem palmas, à saída o apupam com assobios.

'''

xref:018-jo/018-jo-026.adoc#v18-26-0[&#60; Capítulo Anterior] | <<v18-27-0,Topo>> | xref:018-jo/018-jo-028.adoc#v18-28-0[Próximo Capítulo &#62;]