include::./index.adoc[]

[[v18-11-0]]
=== Jó, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-11-1]]

^<<v18-11-1,1>>^ Então, respondeu Zofar, o naamatita:

[[v18-11-2]]

^<<v18-11-2,2>>^ Porventura, não se dará resposta a esse palavrório? Acaso, tem razão o tagarela?

[[v18-11-3]]

^<<v18-11-3,3>>^ Será o caso de as tuas parolas fazerem calar os homens? E zombarás tu sem que ninguém te envergonhe?

[[v18-11-4]]

^<<v18-11-4,4>>^ Pois dizes: A minha doutrina é pura, e sou limpo aos teus olhos.

[[v18-11-5]]

^<<v18-11-5,5>>^ Oh! Falasse Deus, e abrisse os seus lábios contra ti,

[[v18-11-6]]

^<<v18-11-6,6>>^ e te revelasse os segredos da sabedoria, da verdadeira sabedoria, que é multiforme! Sabe, portanto, que Deus permite seja esquecida parte da tua iniquidade.

[[v18-11-7]]

^<<v18-11-7,7>>^ Porventura, desvendarás os arcanos de Deus ou penetrarás até à perfeição do Todo-Poderoso?

[[v18-11-8]]

^<<v18-11-8,8>>^ Como as alturas dos céus é a sua sabedoria; que poderás fazer? Mais profunda é ela do que o abismo; que poderás saber?

[[v18-11-9]]

^<<v18-11-9,9>>^ A sua medida é mais longa do que a terra e mais larga do que o mar.

[[v18-11-10]]

^<<v18-11-10,10>>^ Se ele passa, prende a alguém e chama a juízo, quem o poderá impedir?

[[v18-11-11]]

^<<v18-11-11,11>>^ Porque ele conhece os homens vãos e, sem esforço, vê a iniquidade.

[[v18-11-12]]

^<<v18-11-12,12>>^ Mas o homem estúpido se tornará sábio, quando a cria de um asno montês nascer homem.

[[v18-11-13]]

^<<v18-11-13,13>>^ Se dispuseres o coração e estenderes as mãos para Deus;

[[v18-11-14]]

^<<v18-11-14,14>>^ se lançares para longe a iniquidade da tua mão e não permitires habitar na tua tenda a injustiça,

[[v18-11-15]]

^<<v18-11-15,15>>^ então, levantarás o rosto sem mácula, estarás seguro e não temerás.

[[v18-11-16]]

^<<v18-11-16,16>>^ Pois te esquecerás dos teus sofrimentos e deles só terás lembrança como de águas que passaram.

[[v18-11-17]]

^<<v18-11-17,17>>^ A tua vida será mais clara que o meio-dia; ainda que lhe haja trevas, serão como a manhã.

[[v18-11-18]]

^<<v18-11-18,18>>^ Sentir-te-ás seguro, porque haverá esperança; olharás em derredor e dormirás tranquilo.

[[v18-11-19]]

^<<v18-11-19,19>>^ Deitar-te-ás, e ninguém te espantará; e muitos procurarão obter o teu favor.

[[v18-11-20]]

^<<v18-11-20,20>>^ Mas os olhos dos perversos desfalecerão, o seu refúgio perecerá; sua esperança será o render do espírito.

'''

xref:018-jo/018-jo-010.adoc#v18-10-0[&#60; Capítulo Anterior] | <<v18-11-0,Topo>> | xref:018-jo/018-jo-012.adoc#v18-12-0[Próximo Capítulo &#62;]