include::./index.adoc[]

[[v18-2-0]]
=== Jó, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-2-1]]

^<<v18-2-1,1>>^ Num dia em que os filhos de Deus vieram apresentar-se perante o SENHOR, veio também Satanás entre eles apresentar-se perante o SENHOR.

[[v18-2-2]]

^<<v18-2-2,2>>^ Então, o SENHOR disse a Satanás: Donde vens? Respondeu Satanás ao SENHOR e disse: De rodear a terra e passear por ela.

[[v18-2-3]]

^<<v18-2-3,3>>^ Perguntou o SENHOR a Satanás: Observaste o meu servo Jó? Porque ninguém há na terra semelhante a ele, homem íntegro e reto, temente a Deus e que se desvia do mal. Ele conserva a sua integridade, embora me incitasses contra ele, para o consumir sem causa.

[[v18-2-4]]

^<<v18-2-4,4>>^ Então, Satanás respondeu ao SENHOR: Pele por pele, e tudo quanto o homem tem dará pela sua vida.

[[v18-2-5]]

^<<v18-2-5,5>>^ Estende, porém, a mão, toca-lhe nos ossos e na carne e verás se não blasfema contra ti na tua face.

[[v18-2-6]]

^<<v18-2-6,6>>^ Disse o SENHOR a Satanás: Eis que ele está em teu poder; mas poupa-lhe a vida.

[[v18-2-7]]

^<<v18-2-7,7>>^ Então, saiu Satanás da presença do SENHOR e feriu a Jó de tumores malignos, desde a planta do pé até ao alto da cabeça.

[[v18-2-8]]

^<<v18-2-8,8>>^ Jó, sentado em cinza, tomou um caco para com ele raspar-se.

[[v18-2-9]]

^<<v18-2-9,9>>^ Então, sua mulher lhe disse: Ainda conservas a tua integridade? Amaldiçoa a Deus e morre.

[[v18-2-10]]

^<<v18-2-10,10>>^ Mas ele lhe respondeu: Falas como qualquer doida; temos recebido o bem de Deus e não receberíamos também o mal? Em tudo isto não pecou Jó com os seus lábios.

[[v18-2-11]]

^<<v18-2-11,11>>^ Ouvindo, pois, três amigos de Jó todo este mal que lhe sobreviera, chegaram, cada um do seu lugar: Elifaz, o temanita, Bildade, o suíta, e Zofar, o naamatita; e combinaram ir juntamente condoer-se dele e consolá-lo.

[[v18-2-12]]

^<<v18-2-12,12>>^ Levantando eles de longe os olhos e não o reconhecendo, ergueram a voz e choraram; e cada um, rasgando o seu manto, lançava pó ao ar sobre a cabeça.

[[v18-2-13]]

^<<v18-2-13,13>>^ Sentaram-se com ele na terra, sete dias e sete noites; e nenhum lhe dizia palavra alguma, pois viam que a dor era muito grande.

'''

xref:018-jo/018-jo-001.adoc#v18-1-0[&#60; Capítulo Anterior] | <<v18-2-0,Topo>> | xref:018-jo/018-jo-003.adoc#v18-3-0[Próximo Capítulo &#62;]