include::./index.adoc[]

[[v18-40-0]]
=== Jó, 40
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-40-1]]

^<<v18-40-1,1>>^ Disse mais o SENHOR a Jó:

[[v18-40-2]]

^<<v18-40-2,2>>^ Acaso, quem usa de censuras contenderá com o Todo-Poderoso? Quem assim argui a Deus que responda.

[[v18-40-3]]

^<<v18-40-3,3>>^ Então, Jó respondeu ao SENHOR e disse:

[[v18-40-4]]

^<<v18-40-4,4>>^ Sou indigno; que te responderia eu? Ponho a mão na minha boca.

[[v18-40-5]]

^<<v18-40-5,5>>^ Uma vez falei e não replicarei, aliás, duas vezes, porém não prosseguirei.

[[v18-40-6]]

^<<v18-40-6,6>>^ Então, o SENHOR, do meio de um redemoinho, respondeu a Jó:

[[v18-40-7]]

^<<v18-40-7,7>>^ Cinge agora os lombos como homem; eu te perguntarei, e tu me responderás.

[[v18-40-8]]

^<<v18-40-8,8>>^ Acaso, anularás tu, de fato, o meu juízo? Ou me condenarás, para te justificares?

[[v18-40-9]]

^<<v18-40-9,9>>^ Ou tens braço como Deus ou podes trovejar com a voz como ele o faz?

[[v18-40-10]]

^<<v18-40-10,10>>^ Orna-te, pois, de excelência e grandeza, veste-te de majestade e de glória.

[[v18-40-11]]

^<<v18-40-11,11>>^ Derrama as torrentes da tua ira e atenta para todo soberbo e abate-o.

[[v18-40-12]]

^<<v18-40-12,12>>^ Olha para todo soberbo e humilha-o, calca aos pés os perversos no seu lugar.

[[v18-40-13]]

^<<v18-40-13,13>>^ Cobre-os juntamente no pó, encerra-lhes o rosto no sepulcro.

[[v18-40-14]]

^<<v18-40-14,14>>^ Então, também eu confessarei a teu respeito que a tua mão direita te dá vitória.

[[v18-40-15]]

^<<v18-40-15,15>>^ Contempla agora o hipopótamo, que eu criei contigo, que come a erva como o boi.

[[v18-40-16]]

^<<v18-40-16,16>>^ Sua força está nos seus lombos, e o seu poder, nos músculos do seu ventre.

[[v18-40-17]]

^<<v18-40-17,17>>^ Endurece a sua cauda como cedro; os tendões das suas coxas estão entretecidos.

[[v18-40-18]]

^<<v18-40-18,18>>^ Os seus ossos são como tubos de bronze, o seu arcabouço, como barras de ferro.

[[v18-40-19]]

^<<v18-40-19,19>>^ Ele é obra-prima dos feitos de Deus; quem o fez o proveu de espada.

[[v18-40-20]]

^<<v18-40-20,20>>^ Em verdade, os montes lhe produzem pasto, onde todos os animais do campo folgam.

[[v18-40-21]]

^<<v18-40-21,21>>^ Deita-se debaixo dos lotos, no esconderijo dos canaviais e da lama.

[[v18-40-22]]

^<<v18-40-22,22>>^ Os lotos o cobrem com sua sombra; os salgueiros do ribeiro o cercam.

[[v18-40-23]]

^<<v18-40-23,23>>^ Se um rio transborda, ele não se apressa; fica tranquilo ainda que o Jordão se levante até à sua boca.

[[v18-40-24]]

^<<v18-40-24,24>>^ Acaso, pode alguém apanhá-lo quando ele está olhando? Ou lhe meter um laço pelo nariz?

'''

xref:018-jo/018-jo-039.adoc#v18-39-0[&#60; Capítulo Anterior] | <<v18-40-0,Topo>> | xref:018-jo/018-jo-041.adoc#v18-41-0[Próximo Capítulo &#62;]