include::./index.adoc[]

[[v18-8-0]]
=== Jó, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-8-1]]

^<<v18-8-1,1>>^ Então, respondeu Bildade, o suíta:

[[v18-8-2]]

^<<v18-8-2,2>>^ Até quando falarás tais coisas? E até quando as palavras da tua boca serão qual vento impetuoso?

[[v18-8-3]]

^<<v18-8-3,3>>^ Perverteria Deus o direito ou perverteria o Todo-Poderoso a justiça?

[[v18-8-4]]

^<<v18-8-4,4>>^ Se teus filhos pecaram contra ele, também ele os lançou no poder da sua transgressão.

[[v18-8-5]]

^<<v18-8-5,5>>^ Mas, se tu buscares a Deus e ao Todo-Poderoso pedires misericórdia,

[[v18-8-6]]

^<<v18-8-6,6>>^ se fores puro e reto, ele, sem demora, despertará em teu favor e restaurará a justiça da tua morada.

[[v18-8-7]]

^<<v18-8-7,7>>^ O teu primeiro estado, na verdade, terá sido pequeno, mas o teu último crescerá sobremaneira.

[[v18-8-8]]

^<<v18-8-8,8>>^ Pois, eu te peço, pergunta agora a gerações passadas e atenta para a experiência de seus pais;

[[v18-8-9]]

^<<v18-8-9,9>>^ porque nós somos de ontem e nada sabemos; porquanto nossos dias sobre a terra são como a sombra.

[[v18-8-10]]

^<<v18-8-10,10>>^ Porventura, não te ensinarão os pais, não haverão de falar-te e do próprio entendimento não proferirão estas palavras:

[[v18-8-11]]

^<<v18-8-11,11>>^ Pode o papiro crescer sem lodo? Ou viça o junco sem água?

[[v18-8-12]]

^<<v18-8-12,12>>^ Estando ainda na sua verdura e ainda não colhidos, todavia, antes de qualquer outra erva se secam.

[[v18-8-13]]

^<<v18-8-13,13>>^ São assim as veredas de todos quantos se esquecem de Deus; e a esperança do ímpio perecerá.

[[v18-8-14]]

^<<v18-8-14,14>>^ A sua firmeza será frustrada, e a sua confiança é teia de aranha.

[[v18-8-15]]

^<<v18-8-15,15>>^ Encostar-se-á à sua casa, e ela não se manterá, agarrar-se-á a ela, e ela não ficará em pé.

[[v18-8-16]]

^<<v18-8-16,16>>^ Ele é viçoso perante o sol, e os seus renovos irrompem no seu jardim;

[[v18-8-17]]

^<<v18-8-17,17>>^ as suas raízes se entrelaçam num montão de pedras e penetram até às muralhas.

[[v18-8-18]]

^<<v18-8-18,18>>^ Mas, se Deus o arranca do seu lugar, então, este o negará, dizendo: Nunca te vi.

[[v18-8-19]]

^<<v18-8-19,19>>^ Eis em que deu a sua vida! E do pó brotarão outros.

[[v18-8-20]]

^<<v18-8-20,20>>^ Eis que Deus não rejeita ao íntegro, nem toma pela mão os malfeitores.

[[v18-8-21]]

^<<v18-8-21,21>>^ Ele te encherá a boca de riso e os teus lábios, de júbilo.

[[v18-8-22]]

^<<v18-8-22,22>>^ Teus aborrecedores se vestirão de ignomínia, e a tenda dos perversos não subsistirá.

'''

xref:018-jo/018-jo-007.adoc#v18-7-0[&#60; Capítulo Anterior] | <<v18-8-0,Topo>> | xref:018-jo/018-jo-009.adoc#v18-9-0[Próximo Capítulo &#62;]