include::./index.adoc[]

[[v18-16-0]]
=== Jó, 16
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-16-1]]

^<<v18-16-1,1>>^ Então, respondeu Jó:

[[v18-16-2]]

^<<v18-16-2,2>>^ Tenho ouvido muitas coisas como estas; todos vós sois consoladores molestos.

[[v18-16-3]]

^<<v18-16-3,3>>^ Porventura, não terão fim essas palavras de vento? Ou que é que te instiga para responderes assim?

[[v18-16-4]]

^<<v18-16-4,4>>^ Eu também poderia falar como vós falais; se a vossa alma estivesse em lugar da minha, eu poderia dirigir-vos um montão de palavras e menear contra vós outros a minha cabeça;

[[v18-16-5]]

^<<v18-16-5,5>>^ poderia fortalecer-vos com as minhas palavras, e a compaixão dos meus lábios abrandaria a vossa dor.

[[v18-16-6]]

^<<v18-16-6,6>>^ Se eu falar, a minha dor não cessa; se me calar, qual é o meu alívio?

[[v18-16-7]]

^<<v18-16-7,7>>^ Na verdade, as minhas forças estão exaustas; tu, ó Deus, destruíste a minha família toda.

[[v18-16-8]]

^<<v18-16-8,8>>^ Testemunha disto é que já me tornaste encarquilhado, a minha magreza já se levanta contra mim e me acusa cara a cara.

[[v18-16-9]]

^<<v18-16-9,9>>^ Na sua ira me despedaçou e tem animosidade contra mim; contra mim rangeu os dentes e, como meu adversário, aguça os olhos.

[[v18-16-10]]

^<<v18-16-10,10>>^ Homens abrem contra mim a boca, com desprezo me esbofeteiam, e contra mim todos se ajuntam.

[[v18-16-11]]

^<<v18-16-11,11>>^ Deus me entrega ao ímpio e nas mãos dos perversos me faz cair.

[[v18-16-12]]

^<<v18-16-12,12>>^ Em paz eu vivia, porém ele me quebrantou; pegou-me pelo pescoço e me despedaçou; pôs-me por seu alvo.

[[v18-16-13]]

^<<v18-16-13,13>>^ Cercam-me as suas flechas, atravessa-me os rins, e não me poupa, e o meu fel derrama na terra.

[[v18-16-14]]

^<<v18-16-14,14>>^ Fere-me com ferimento sobre ferimento, arremete contra mim como um guerreiro.

[[v18-16-15]]

^<<v18-16-15,15>>^ Cosi sobre a minha pele o cilício e revolvi o meu orgulho no pó.

[[v18-16-16]]

^<<v18-16-16,16>>^ O meu rosto está todo afogueado de chorar, e sobre as minhas pálpebras está a sombra da morte,

[[v18-16-17]]

^<<v18-16-17,17>>^ embora não haja violência nas minhas mãos, e seja pura a minha oração.

[[v18-16-18]]

^<<v18-16-18,18>>^ Ó terra, não cubras o meu sangue, e não haja lugar em que se oculte o meu clamor!

[[v18-16-19]]

^<<v18-16-19,19>>^ Já agora sabei que a minha testemunha está no céu, e, nas alturas, quem advoga a minha causa.

[[v18-16-20]]

^<<v18-16-20,20>>^ Os meus amigos zombam de mim, mas os meus olhos se desfazem em lágrimas diante de Deus,

[[v18-16-21]]

^<<v18-16-21,21>>^ para que ele mantenha o direito do homem contra o próprio Deus e o do filho do homem contra o seu próximo.

[[v18-16-22]]

^<<v18-16-22,22>>^ Porque dentro de poucos anos eu seguirei o caminho de onde não tornarei.

'''

xref:018-jo/018-jo-015.adoc#v18-15-0[&#60; Capítulo Anterior] | <<v18-16-0,Topo>> | xref:018-jo/018-jo-017.adoc#v18-17-0[Próximo Capítulo &#62;]