include::./index.adoc[]

[[v18-20-0]]
=== Jó, 20
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-20-1]]

^<<v18-20-1,1>>^ Então, respondeu Zofar, o naamatita:

[[v18-20-2]]

^<<v18-20-2,2>>^ Visto que os meus pensamentos me impõem resposta, eu me apresso.

[[v18-20-3]]

^<<v18-20-3,3>>^ Eu ouvi a repreensão, que me envergonha, mas o meu espírito me obriga a responder segundo o meu entendimento.

[[v18-20-4]]

^<<v18-20-4,4>>^ Porventura, não sabes tu que desde todos os tempos, desde que o homem foi posto sobre a terra,

[[v18-20-5]]

^<<v18-20-5,5>>^ o júbilo dos perversos é breve, e a alegria dos ímpios, momentânea?

[[v18-20-6]]

^<<v18-20-6,6>>^ Ainda que a sua presunção remonte aos céus, e a sua cabeça atinja as nuvens,

[[v18-20-7]]

^<<v18-20-7,7>>^ como o seu próprio esterco, apodrecerá para sempre; e os que o conheceram dirão: Onde está?

[[v18-20-8]]

^<<v18-20-8,8>>^ Voará como um sonho e não será achado, será afugentado como uma visão da noite.

[[v18-20-9]]

^<<v18-20-9,9>>^ Os olhos que o viram jamais o verão, e o seu lugar não o verá outra vez.

[[v18-20-10]]

^<<v18-20-10,10>>^ Os seus filhos procurarão aplacar aos pobres, e as suas mãos lhes restaurarão os seus bens.

[[v18-20-11]]

^<<v18-20-11,11>>^ Ainda que os seus ossos estejam cheios do vigor da sua juventude, esse vigor se deitará com ele no pó.

[[v18-20-12]]

^<<v18-20-12,12>>^ Ainda que o mal lhe seja doce na boca, e ele o esconda debaixo da língua,

[[v18-20-13]]

^<<v18-20-13,13>>^ e o saboreie, e o não deixe; antes, o retenha no seu paladar,

[[v18-20-14]]

^<<v18-20-14,14>>^ contudo, a sua comida se transformará nas suas entranhas; fel de áspides será no seu interior.

[[v18-20-15]]

^<<v18-20-15,15>>^ Engoliu riquezas, mas vomitá-las-á; do seu ventre Deus as lançará.

[[v18-20-16]]

^<<v18-20-16,16>>^ Veneno de áspides sorveu; língua de víbora o matará.

[[v18-20-17]]

^<<v18-20-17,17>>^ Não se deliciará com a vista dos ribeiros e dos rios transbordantes de mel e de leite.

[[v18-20-18]]

^<<v18-20-18,18>>^ Devolverá o fruto do seu trabalho e não o engolirá; do lucro de sua barganha não tirará prazer nenhum.

[[v18-20-19]]

^<<v18-20-19,19>>^ Oprimiu e desamparou os pobres, roubou casas que não edificou.

[[v18-20-20]]

^<<v18-20-20,20>>^ Por não haver limites à sua cobiça, não chegará a salvar as coisas por ele desejadas.

[[v18-20-21]]

^<<v18-20-21,21>>^ Nada escapou à sua cobiça insaciável, pelo que a sua prosperidade não durará.

[[v18-20-22]]

^<<v18-20-22,22>>^ Na plenitude da sua abastança, ver-se-á angustiado; toda a força da miséria virá sobre ele.

[[v18-20-23]]

^<<v18-20-23,23>>^ Para encher a sua barriga, Deus mandará sobre ele o furor da sua ira, que, por alimento, mandará chover sobre ele.

[[v18-20-24]]

^<<v18-20-24,24>>^ Se fugir das armas de ferro, o arco de bronze o traspassará.

[[v18-20-25]]

^<<v18-20-25,25>>^ Ele arranca das suas costas a flecha, e esta vem resplandecente do seu fel; e haverá assombro sobre ele.

[[v18-20-26]]

^<<v18-20-26,26>>^ Todas as calamidades serão reservadas contra os seus tesouros; fogo não assoprado o consumirá, fogo que se apascentará do que ficar na sua tenda.

[[v18-20-27]]

^<<v18-20-27,27>>^ Os céus lhe manifestarão a sua iniquidade; e a terra se levantará contra ele.

[[v18-20-28]]

^<<v18-20-28,28>>^ As riquezas de sua casa serão transportadas; como água serão derramadas no dia da ira de Deus.

[[v18-20-29]]

^<<v18-20-29,29>>^ Tal é, da parte de Deus, a sorte do homem perverso, tal a herança decretada por Deus.

'''

xref:018-jo/018-jo-019.adoc#v18-19-0[&#60; Capítulo Anterior] | <<v18-20-0,Topo>> | xref:018-jo/018-jo-021.adoc#v18-21-0[Próximo Capítulo &#62;]