include::./index.adoc[]

[[v18-21-0]]
=== Jó, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-21-1]]

^<<v18-21-1,1>>^ Respondeu, porém, Jó:

[[v18-21-2]]

^<<v18-21-2,2>>^ Ouvi atentamente as minhas razões, e já isso me será a vossa consolação.

[[v18-21-3]]

^<<v18-21-3,3>>^ Tolerai-me, e eu falarei; e, havendo eu falado, podereis zombar.

[[v18-21-4]]

^<<v18-21-4,4>>^ Acaso, é do homem que eu me queixo? Não tenho motivo de me impacientar?

[[v18-21-5]]

^<<v18-21-5,5>>^ Olhai para mim e pasmai; e ponde a mão sobre a boca;

[[v18-21-6]]

^<<v18-21-6,6>>^ porque só de pensar nisso me perturbo, e um calafrio se apodera de toda a minha carne.

[[v18-21-7]]

^<<v18-21-7,7>>^ Como é, pois, que vivem os perversos, envelhecem e ainda se tornam mais poderosos?

[[v18-21-8]]

^<<v18-21-8,8>>^ Seus filhos se estabelecem na sua presença; e os seus descendentes, ante seus olhos.

[[v18-21-9]]

^<<v18-21-9,9>>^ As suas casas têm paz, sem temor, e a vara de Deus não os fustiga.

[[v18-21-10]]

^<<v18-21-10,10>>^ O seu touro gera e não falha, suas novilhas têm a cria e não abortam.

[[v18-21-11]]

^<<v18-21-11,11>>^ Deixam correr suas crianças, como a um rebanho, e seus filhos saltam de alegria;

[[v18-21-12]]

^<<v18-21-12,12>>^ cantam com tamboril e harpa e alegram-se ao som da flauta.

[[v18-21-13]]

^<<v18-21-13,13>>^ Passam eles os seus dias em prosperidade e em paz descem à sepultura.

[[v18-21-14]]

^<<v18-21-14,14>>^ E são estes os que disseram a Deus: Retira-te de nós! Não desejamos conhecer os teus caminhos.

[[v18-21-15]]

^<<v18-21-15,15>>^ Que é o Todo-Poderoso, para que nós o sirvamos? E que nos aproveitará que lhe façamos orações?

[[v18-21-16]]

^<<v18-21-16,16>>^ Vede, porém, que não provém deles a sua prosperidade; longe de mim o conselho dos perversos!

[[v18-21-17]]

^<<v18-21-17,17>>^ Quantas vezes sucede que se apaga a lâmpada dos perversos? Quantas vezes lhes sobrevém a destruição? Quantas vezes Deus na sua ira lhes reparte dores?

[[v18-21-18]]

^<<v18-21-18,18>>^ Quantas vezes são como a palha diante do vento e como a pragana arrebatada pelo remoinho?

[[v18-21-19]]

^<<v18-21-19,19>>^ Deus, dizeis vós, guarda a iniquidade do perverso para seus filhos. Mas é a ele que deveria Deus dar o pago, para que o sinta.

[[v18-21-20]]

^<<v18-21-20,20>>^ Seus próprios olhos devem ver a sua ruína, e ele, beber do furor do Todo-Poderoso.

[[v18-21-21]]

^<<v18-21-21,21>>^ Porque depois de morto, cortado já o número dos seus meses, que interessa a ele a sua casa?

[[v18-21-22]]

^<<v18-21-22,22>>^ Acaso, alguém ensinará ciência a Deus, a ele que julga os que estão nos céus?

[[v18-21-23]]

^<<v18-21-23,23>>^ Um morre em pleno vigor, despreocupado e tranquilo,

[[v18-21-24]]

^<<v18-21-24,24>>^ com seus baldes cheios de leite e fresca a medula dos seus ossos.

[[v18-21-25]]

^<<v18-21-25,25>>^ Outro, ao contrário, morre na amargura do seu coração, não havendo provado do bem.

[[v18-21-26]]

^<<v18-21-26,26>>^ Juntamente jazem no pó, onde os vermes os cobrem.

[[v18-21-27]]

^<<v18-21-27,27>>^ Vede que conheço os vossos pensamentos e os injustos desígnios com que me tratais.

[[v18-21-28]]

^<<v18-21-28,28>>^ Porque direis: Onde está a casa do príncipe, e onde, a tenda em que morava o perverso?

[[v18-21-29]]

^<<v18-21-29,29>>^ Porventura, não tendes interrogado os que viajam? E não considerastes as suas declarações,

[[v18-21-30]]

^<<v18-21-30,30>>^ que o mau é poupado no dia da calamidade, é socorrido no dia do furor?

[[v18-21-31]]

^<<v18-21-31,31>>^ Quem lhe lançará em rosto o seu proceder? Quem lhe dará o pago do que faz?

[[v18-21-32]]

^<<v18-21-32,32>>^ Finalmente, é levado à sepultura, e sobre o seu túmulo se faz vigilância.

[[v18-21-33]]

^<<v18-21-33,33>>^ Os torrões do vale lhe são leves, todos os homens o seguem, assim como não têm número os que foram adiante dele.

[[v18-21-34]]

^<<v18-21-34,34>>^ Como, pois, me consolais em vão? Das vossas respostas só resta falsidade.

'''

xref:018-jo/018-jo-020.adoc#v18-20-0[&#60; Capítulo Anterior] | <<v18-21-0,Topo>> | xref:018-jo/018-jo-022.adoc#v18-22-0[Próximo Capítulo &#62;]