include::./index.adoc[]

[[v18-18-0]]
=== Jó, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-18-1]]

^<<v18-18-1,1>>^ Então, respondeu Bildade, o suíta:

[[v18-18-2]]

^<<v18-18-2,2>>^ Até quando andarás à caça de palavras? Considera bem, e, então, falaremos.

[[v18-18-3]]

^<<v18-18-3,3>>^ Por que somos reputados por animais, e aos teus olhos passamos por curtos de inteligência?

[[v18-18-4]]

^<<v18-18-4,4>>^ Oh! Tu, que te despedaças na tua ira, será a terra abandonada por tua causa? Remover-se-ão as rochas do seu lugar?

[[v18-18-5]]

^<<v18-18-5,5>>^ Na verdade, a luz do perverso se apagará, e para seu fogo não resplandecerá a faísca;

[[v18-18-6]]

^<<v18-18-6,6>>^ a luz se escurecerá nas suas tendas, e a sua lâmpada sobre ele se apagará;

[[v18-18-7]]

^<<v18-18-7,7>>^ os seus passos fortes se estreitarão, e a sua própria trama o derribará.

[[v18-18-8]]

^<<v18-18-8,8>>^ Porque por seus próprios pés é lançado na rede e andará na boca de forje.

[[v18-18-9]]

^<<v18-18-9,9>>^ A armadilha o apanhará pelo calcanhar, e o laço o prenderá.

[[v18-18-10]]

^<<v18-18-10,10>>^ A corda está-lhe escondida na terra, e a armadilha, na vereda.

[[v18-18-11]]

^<<v18-18-11,11>>^ Os assombros o espantarão de todos os lados e o perseguirão a cada passo.

[[v18-18-12]]

^<<v18-18-12,12>>^ A calamidade virá faminta sobre ele, e a miséria estará alerta ao seu lado,

[[v18-18-13]]

^<<v18-18-13,13>>^ a qual lhe devorará os membros do corpo; serão devorados pelo primogênito da morte.

[[v18-18-14]]

^<<v18-18-14,14>>^ O perverso será arrancado da sua tenda, onde está confiado, e será levado ao rei dos terrores.

[[v18-18-15]]

^<<v18-18-15,15>>^ Nenhum dos seus morará na sua tenda, espalhar-se-á enxofre sobre a sua habitação.

[[v18-18-16]]

^<<v18-18-16,16>>^ Por baixo secarão as suas raízes, e murcharão por cima os seus ramos.

[[v18-18-17]]

^<<v18-18-17,17>>^ A sua memória desaparecerá da terra, e pelas praças não terá nome.

[[v18-18-18]]

^<<v18-18-18,18>>^ Da luz o lançarão nas trevas e o afugentarão do mundo.

[[v18-18-19]]

^<<v18-18-19,19>>^ Não terá filho nem posteridade entre o seu povo, nem sobrevivente algum ficará nas suas moradas.

[[v18-18-20]]

^<<v18-18-20,20>>^ Do seu dia se espantarão os do Ocidente, e os do Oriente serão tomados de horror.

[[v18-18-21]]

^<<v18-18-21,21>>^ Tais são, na verdade, as moradas do perverso, e este é o paradeiro do que não conhece a Deus.

'''

xref:018-jo/018-jo-017.adoc#v18-17-0[&#60; Capítulo Anterior] | <<v18-18-0,Topo>> | xref:018-jo/018-jo-019.adoc#v18-19-0[Próximo Capítulo &#62;]