include::./index.adoc[]

[[v18-12-0]]
=== Jó, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v18-12-1]]

^<<v18-12-1,1>>^ Então, Jó respondeu:

[[v18-12-2]]

^<<v18-12-2,2>>^ Na verdade, vós sois o povo, e convosco morrerá a sabedoria.

[[v18-12-3]]

^<<v18-12-3,3>>^ Também eu tenho entendimento como vós; eu não vos sou inferior; quem não sabe coisas como essas?

[[v18-12-4]]

^<<v18-12-4,4>>^ Eu sou irrisão para os meus amigos; eu, que invocava a Deus, e ele me respondia; o justo e o reto servem de irrisão.

[[v18-12-5]]

^<<v18-12-5,5>>^ No pensamento de quem está seguro, há desprezo para o infortúnio, um empurrão para aquele cujos pés já vacilam.

[[v18-12-6]]

^<<v18-12-6,6>>^ As tendas dos tiranos gozam paz, e os que provocam a Deus estão seguros; têm o punho por seu deus.

[[v18-12-7]]

^<<v18-12-7,7>>^ Mas pergunta agora às alimárias, e cada uma delas to ensinará; e às aves dos céus, e elas to farão saber.

[[v18-12-8]]

^<<v18-12-8,8>>^ Ou fala com a terra, e ela te instruirá; até os peixes do mar to contarão.

[[v18-12-9]]

^<<v18-12-9,9>>^ Qual entre todos estes não sabe que a mão do SENHOR fez isto?

[[v18-12-10]]

^<<v18-12-10,10>>^ Na sua mão está a alma de todo ser vivente e o espírito de todo o gênero humano.

[[v18-12-11]]

^<<v18-12-11,11>>^ Porventura, o ouvido não submete à prova as palavras, como o paladar prova as comidas?

[[v18-12-12]]

^<<v18-12-12,12>>^ Está a sabedoria com os idosos, e, na longevidade, o entendimento?

[[v18-12-13]]

^<<v18-12-13,13>>^ Não! Com Deus está a sabedoria e a força; ele tem conselho e entendimento.

[[v18-12-14]]

^<<v18-12-14,14>>^ O que ele deitar abaixo não se reedificará; lança na prisão, e ninguém a pode abrir.

[[v18-12-15]]

^<<v18-12-15,15>>^ Se retém as águas, elas secam; se as larga, devastam a terra.

[[v18-12-16]]

^<<v18-12-16,16>>^ Com ele está a força e a sabedoria; seu é o que erra e o que faz errar.

[[v18-12-17]]

^<<v18-12-17,17>>^ Aos conselheiros, leva-os despojados do seu cargo e aos juízes faz desvairar.

[[v18-12-18]]

^<<v18-12-18,18>>^ Dissolve a autoridade dos reis, e uma corda lhes cinge os lombos.

[[v18-12-19]]

^<<v18-12-19,19>>^ Aos sacerdotes, leva-os despojados do seu cargo e aos poderosos transtorna.

[[v18-12-20]]

^<<v18-12-20,20>>^ Aos eloquentes ele tira a palavra e tira o entendimento aos anciãos.

[[v18-12-21]]

^<<v18-12-21,21>>^ Lança desprezo sobre os príncipes e afrouxa o cinto dos fortes.

[[v18-12-22]]

^<<v18-12-22,22>>^ Das trevas manifesta coisas profundas e traz à luz a densa escuridade.

[[v18-12-23]]

^<<v18-12-23,23>>^ Multiplica as nações e as faz perecer; dispersa-as e de novo as congrega.

[[v18-12-24]]

^<<v18-12-24,24>>^ Tira o entendimento aos príncipes do povo da terra e os faz vaguear pelos desertos sem caminho.

[[v18-12-25]]

^<<v18-12-25,25>>^ Nas trevas andam às apalpadelas, sem terem luz, e os faz cambalear como ébrios.

'''

xref:018-jo/018-jo-011.adoc#v18-11-0[&#60; Capítulo Anterior] | <<v18-12-0,Topo>> | xref:018-jo/018-jo-013.adoc#v18-13-0[Próximo Capítulo &#62;]