include::./index.adoc[]

[[v54-3-0]]
=== 1 Timóteo, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v54-3-1]]

^<<v54-3-1,1>>^ Fiel é a palavra: se alguém aspira ao episcopado, excelente obra almeja.

[[v54-3-2]]

^<<v54-3-2,2>>^ É necessário, portanto, que o bispo seja irrepreensível, esposo de uma só mulher, temperante, sóbrio, modesto, hospitaleiro, apto para ensinar;

[[v54-3-3]]

^<<v54-3-3,3>>^ não dado ao vinho, não violento, porém cordato, inimigo de contendas, não avarento;

[[v54-3-4]]

^<<v54-3-4,4>>^ e que governe bem a própria casa, criando os filhos sob disciplina, com todo o respeito

[[v54-3-5]]

^<<v54-3-5,5>>^ (pois, se alguém não sabe governar a própria casa, como cuidará da igreja de Deus?);

[[v54-3-6]]

^<<v54-3-6,6>>^ não seja neófito, para não suceder que se ensoberbeça e incorra na condenação do diabo.

[[v54-3-7]]

^<<v54-3-7,7>>^ Pelo contrário, é necessário que ele tenha bom testemunho dos de fora, a fim de não cair no opróbrio e no laço do diabo.

[[v54-3-8]]

^<<v54-3-8,8>>^ Semelhantemente, quanto a diáconos, é necessário que sejam respeitáveis, de uma só palavra, não inclinados a muito vinho, não cobiçosos de sórdida ganância,

[[v54-3-9]]

^<<v54-3-9,9>>^ conservando o mistério da fé com a consciência limpa.

[[v54-3-10]]

^<<v54-3-10,10>>^ Também sejam estes primeiramente experimentados; e, se se mostrarem irrepreensíveis, exerçam o diaconato.

[[v54-3-11]]

^<<v54-3-11,11>>^ Da mesma sorte, quanto a mulheres, é necessário que sejam elas respeitáveis, não maldizentes, temperantes e fiéis em tudo.

[[v54-3-12]]

^<<v54-3-12,12>>^ O diácono seja marido de uma só mulher e governe bem seus filhos e a própria casa.

[[v54-3-13]]

^<<v54-3-13,13>>^ Pois os que desempenharem bem o diaconato alcançam para si mesmos justa preeminência e muita intrepidez na fé em Cristo Jesus.

[[v54-3-14]]

^<<v54-3-14,14>>^ Escrevo-te estas coisas, esperando ir ver-te em breve;

[[v54-3-15]]

^<<v54-3-15,15>>^ para que, se eu tardar, fiques ciente de como se deve proceder na casa de Deus, que é a igreja do Deus vivo, coluna e baluarte da verdade.

[[v54-3-16]]

^<<v54-3-16,16>>^ Evidentemente, grande é o mistério da piedade: Aquele que foi manifestado na carne foi justificado em espírito, contemplado por anjos, pregado entre os gentios, crido no mundo, recebido na glória.

'''

xref:054-1-timoteo/054-1-timoteo-002.adoc#v54-2-0[&#60; Capítulo Anterior] | <<v54-3-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-004.adoc#v54-4-0[Próximo Capítulo &#62;]