include::./index.adoc[]

[[v54-4-0]]
=== 1 Timóteo, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v54-4-1]]

^<<v54-4-1,1>>^ Ora, o Espírito afirma expressamente que, nos últimos tempos, alguns apostatarão da fé, por obedecerem a espíritos enganadores e a ensinos de demônios,

[[v54-4-2]]

^<<v54-4-2,2>>^ pela hipocrisia dos que falam mentiras e que têm cauterizada a própria consciência,

[[v54-4-3]]

^<<v54-4-3,3>>^ que proíbem o casamento e exigem abstinência de alimentos que Deus criou para serem recebidos, com ações de graças, pelos fiéis e por quantos conhecem plenamente a verdade;

[[v54-4-4]]

^<<v54-4-4,4>>^ pois tudo que Deus criou é bom, e, recebido com ações de graças, nada é recusável,

[[v54-4-5]]

^<<v54-4-5,5>>^ porque, pela palavra de Deus e pela oração, é santificado.

[[v54-4-6]]

^<<v54-4-6,6>>^ Expondo estas coisas aos irmãos, serás bom ministro de Cristo Jesus, alimentado com as palavras da fé e da boa doutrina que tens seguido.

[[v54-4-7]]

^<<v54-4-7,7>>^ Mas rejeita as fábulas profanas e de velhas caducas. Exercita-te, pessoalmente, na piedade.

[[v54-4-8]]

^<<v54-4-8,8>>^ Pois o exercício físico para pouco é proveitoso, mas a piedade para tudo é proveitosa, porque tem a promessa da vida que agora é e da que há de ser.

[[v54-4-9]]

^<<v54-4-9,9>>^ Fiel é esta palavra e digna de inteira aceitação.

[[v54-4-10]]

^<<v54-4-10,10>>^ Ora, é para esse fim que labutamos e nos esforçamos sobremodo, porquanto temos posto a nossa esperança no Deus vivo, Salvador de todos os homens, especialmente dos fiéis.

[[v54-4-11]]

^<<v54-4-11,11>>^ Ordena e ensina estas coisas.

[[v54-4-12]]

^<<v54-4-12,12>>^ Ninguém despreze a tua mocidade; pelo contrário, torna-te padrão dos fiéis, na palavra, no procedimento, no amor, na fé, na pureza.

[[v54-4-13]]

^<<v54-4-13,13>>^ Até à minha chegada, aplica-te à leitura, à exortação, ao ensino.

[[v54-4-14]]

^<<v54-4-14,14>>^ Não te faças negligente para com o dom que há em ti, o qual te foi concedido mediante profecia, com a imposição das mãos do presbitério.

[[v54-4-15]]

^<<v54-4-15,15>>^ Medita estas coisas e nelas sê diligente, para que o teu progresso a todos seja manifesto.

[[v54-4-16]]

^<<v54-4-16,16>>^ Tem cuidado de ti mesmo e da doutrina. Continua nestes deveres; porque, fazendo assim, salvarás tanto a ti mesmo como aos teus ouvintes.

'''

xref:054-1-timoteo/054-1-timoteo-003.adoc#v54-3-0[&#60; Capítulo Anterior] | <<v54-4-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-005.adoc#v54-5-0[Próximo Capítulo &#62;]