include::./index.adoc[]

[[v54-1-0]]
=== 1 Timóteo, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v54-1-1]]

^<<v54-1-1,1>>^ Paulo, apóstolo de Cristo Jesus, pelo mandato de Deus, nosso Salvador, e de Cristo Jesus, nossa esperança,

[[v54-1-2]]

^<<v54-1-2,2>>^ a Timóteo, verdadeiro filho na fé, graça, misericórdia e paz, da parte de Deus Pai e de Cristo Jesus, nosso Senhor.

[[v54-1-3]]

^<<v54-1-3,3>>^ Quando eu estava de viagem, rumo da Macedônia, te roguei permanecesses ainda em Éfeso para admoestares a certas pessoas, a fim de que não ensinem outra doutrina,

[[v54-1-4]]

^<<v54-1-4,4>>^ nem se ocupem com fábulas e genealogias sem fim, que, antes, promovem discussões do que o serviço de Deus, na fé.

[[v54-1-5]]

^<<v54-1-5,5>>^ Ora, o intuito da presente admoestação visa ao amor que procede de coração puro, e de consciência boa, e de fé sem hipocrisia.

[[v54-1-6]]

^<<v54-1-6,6>>^ Desviando-se algumas pessoas destas coisas, perderam-se em loquacidade frívola,

[[v54-1-7]]

^<<v54-1-7,7>>^ pretendendo passar por mestres da lei, não compreendendo, todavia, nem o que dizem, nem os assuntos sobre os quais fazem ousadas asseverações.

[[v54-1-8]]

^<<v54-1-8,8>>^ Sabemos, porém, que a lei é boa, se alguém dela se utiliza de modo legítimo,

[[v54-1-9]]

^<<v54-1-9,9>>^ tendo em vista que não se promulga lei para quem é justo, mas para transgressores e rebeldes, irreverentes e pecadores, ímpios e profanos, parricidas e matricidas, homicidas,

[[v54-1-10]]

^<<v54-1-10,10>>^ impuros, sodomitas, raptores de homens, mentirosos, perjuros e para tudo quanto se opõe à sã doutrina,

[[v54-1-11]]

^<<v54-1-11,11>>^ segundo o evangelho da glória do Deus bendito, do qual fui encarregado.

[[v54-1-12]]

^<<v54-1-12,12>>^ Sou grato para com aquele que me fortaleceu, Cristo Jesus, nosso Senhor, que me considerou fiel, designando-me para o ministério,

[[v54-1-13]]

^<<v54-1-13,13>>^ a mim, que, noutro tempo, era blasfemo, e perseguidor, e insolente. Mas obtive misericórdia, pois o fiz na ignorância, na incredulidade.

[[v54-1-14]]

^<<v54-1-14,14>>^ Transbordou, porém, a graça de nosso Senhor com a fé e o amor que há em Cristo Jesus.

[[v54-1-15]]

^<<v54-1-15,15>>^ Fiel é a palavra e digna de toda aceitação: que Cristo Jesus veio ao mundo para salvar os pecadores, dos quais eu sou o principal.

[[v54-1-16]]

^<<v54-1-16,16>>^ Mas, por esta mesma razão, me foi concedida misericórdia, para que, em mim, o principal, evidenciasse Jesus Cristo a sua completa longanimidade, e servisse eu de modelo a quantos hão de crer nele para a vida eterna.

[[v54-1-17]]

^<<v54-1-17,17>>^ Assim, ao Rei eterno, imortal, invisível, Deus único, honra e glória pelos séculos dos séculos. Amém!

[[v54-1-18]]

^<<v54-1-18,18>>^ Este é o dever de que te encarrego, ó filho Timóteo, segundo as profecias de que antecipadamente foste objeto: combate, firmado nelas, o bom combate,

[[v54-1-19]]

^<<v54-1-19,19>>^ mantendo fé e boa consciência, porquanto alguns, tendo rejeitado a boa consciência, vieram a naufragar na fé.

[[v54-1-20]]

^<<v54-1-20,20>>^ E dentre esses se contam Himeneu e Alexandre, os quais entreguei a Satanás, para serem castigados, a fim de não mais blasfemarem.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-003.adoc#v53-3-0[&#60; Capítulo Anterior] | <<v54-1-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-002.adoc#v54-2-0[Próximo Capítulo &#62;]