include::./index.adoc[]

[[v54-2-0]]
=== 1 Timóteo, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v54-2-1]]

^<<v54-2-1,1>>^ Antes de tudo, pois, exorto que se use a prática de súplicas, orações, intercessões, ações de graças, em favor de todos os homens,

[[v54-2-2]]

^<<v54-2-2,2>>^ em favor dos reis e de todos os que se acham investidos de autoridade, para que vivamos vida tranquila e mansa, com toda piedade e respeito.

[[v54-2-3]]

^<<v54-2-3,3>>^ Isto é bom e aceitável diante de Deus, nosso Salvador,

[[v54-2-4]]

^<<v54-2-4,4>>^ o qual deseja que todos os homens sejam salvos e cheguem ao pleno conhecimento da verdade.

[[v54-2-5]]

^<<v54-2-5,5>>^ Porquanto há um só Deus e um só Mediador entre Deus e os homens, Cristo Jesus, homem,

[[v54-2-6]]

^<<v54-2-6,6>>^ o qual a si mesmo se deu em resgate por todos: testemunho que se deve prestar em tempos oportunos.

[[v54-2-7]]

^<<v54-2-7,7>>^ Para isto fui designado pregador e apóstolo (afirmo a verdade, não minto), mestre dos gentios na fé e na verdade.

[[v54-2-8]]

^<<v54-2-8,8>>^ Quero, portanto, que os varões orem em todo lugar, levantando mãos santas, sem ira e sem animosidade.

[[v54-2-9]]

^<<v54-2-9,9>>^ Da mesma sorte, que as mulheres, em traje decente, se ataviem com modéstia e bom senso, não com cabeleira frisada e com ouro, ou pérolas, ou vestuário dispendioso,

[[v54-2-10]]

^<<v54-2-10,10>>^ porém com boas obras (como é próprio às mulheres que professam ser piedosas).

[[v54-2-11]]

^<<v54-2-11,11>>^ A mulher aprenda em silêncio, com toda a submissão.

[[v54-2-12]]

^<<v54-2-12,12>>^ E não permito que a mulher ensine, nem exerça autoridade de homem; esteja, porém, em silêncio.

[[v54-2-13]]

^<<v54-2-13,13>>^ Porque, primeiro, foi formado Adão, depois, Eva.

[[v54-2-14]]

^<<v54-2-14,14>>^ E Adão não foi iludido, mas a mulher, sendo enganada, caiu em transgressão.

[[v54-2-15]]

^<<v54-2-15,15>>^ Todavia, será preservada através de sua missão de mãe, se ela permanecer em fé, e amor, e santificação, com bom senso.

'''

xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[&#60; Capítulo Anterior] | <<v54-2-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-003.adoc#v54-3-0[Próximo Capítulo &#62;]