include::./index.adoc[]

[[v54-5-0]]
=== 1 Timóteo, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v54-5-1]]

^<<v54-5-1,1>>^ Não repreendas ao homem idoso; antes, exorta-o como a pai; aos moços, como a irmãos;

[[v54-5-2]]

^<<v54-5-2,2>>^ às mulheres idosas, como a mães; às moças, como a irmãs, com toda a pureza.

[[v54-5-3]]

^<<v54-5-3,3>>^ Honra as viúvas verdadeiramente viúvas.

[[v54-5-4]]

^<<v54-5-4,4>>^ Mas, se alguma viúva tem filhos ou netos, que estes aprendam primeiro a exercer piedade para com a própria casa e a recompensar a seus progenitores; pois isto é aceitável diante de Deus.

[[v54-5-5]]

^<<v54-5-5,5>>^ Aquela, porém, que é verdadeiramente viúva e não tem amparo espera em Deus e persevera em súplicas e orações, noite e dia;

[[v54-5-6]]

^<<v54-5-6,6>>^ entretanto, a que se entrega aos prazeres, mesmo viva, está morta.

[[v54-5-7]]

^<<v54-5-7,7>>^ Prescreve, pois, estas coisas, para que sejam irrepreensíveis.

[[v54-5-8]]

^<<v54-5-8,8>>^ Ora, se alguém não tem cuidado dos seus e especialmente dos da própria casa, tem negado a fé e é pior do que o descrente.

[[v54-5-9]]

^<<v54-5-9,9>>^ Não seja inscrita senão viúva que conte ao menos sessenta anos de idade, tenha sido esposa de um só marido,

[[v54-5-10]]

^<<v54-5-10,10>>^ seja recomendada pelo testemunho de boas obras, tenha criado filhos, exercitado hospitalidade, lavado os pés aos santos, socorrido a atribulados, se viveu na prática zelosa de toda boa obra.

[[v54-5-11]]

^<<v54-5-11,11>>^ Mas rejeita viúvas mais novas, porque, quando se tornam levianas contra Cristo, querem casar-se,

[[v54-5-12]]

^<<v54-5-12,12>>^ tornando-se condenáveis por anularem o seu primeiro compromisso.

[[v54-5-13]]

^<<v54-5-13,13>>^ Além do mais, aprendem também a viver ociosas, andando de casa em casa; e não somente ociosas, mas ainda tagarelas e intrigantes, falando o que não devem.

[[v54-5-14]]

^<<v54-5-14,14>>^ Quero, portanto, que as viúvas mais novas se casem, criem filhos, sejam boas donas de casa e não deem ao adversário ocasião favorável de maledicência.

[[v54-5-15]]

^<<v54-5-15,15>>^ Pois, com efeito, já algumas se desviaram, seguindo a Satanás.

[[v54-5-16]]

^<<v54-5-16,16>>^ Se alguma crente tem viúvas em sua família, socorra-as, e não fique sobrecarregada a igreja, para que esta possa socorrer as que são verdadeiramente viúvas.

[[v54-5-17]]

^<<v54-5-17,17>>^ Devem ser considerados merecedores de dobrados honorários os presbíteros que presidem bem, com especialidade os que se afadigam na palavra e no ensino.

[[v54-5-18]]

^<<v54-5-18,18>>^ Pois a Escritura declara: Não amordaces o boi, quando pisa o trigo. E ainda: O trabalhador é digno do seu salário.

[[v54-5-19]]

^<<v54-5-19,19>>^ Não aceites denúncia contra presbítero, senão exclusivamente sob o depoimento de duas ou três testemunhas.

[[v54-5-20]]

^<<v54-5-20,20>>^ Quanto aos que vivem no pecado, repreende-os na presença de todos, para que também os demais temam.

[[v54-5-21]]

^<<v54-5-21,21>>^ Conjuro-te, perante Deus, e Cristo Jesus, e os anjos eleitos, que guardes estes conselhos, sem prevenção, nada fazendo com parcialidade.

[[v54-5-22]]

^<<v54-5-22,22>>^ A ninguém imponhas precipitadamente as mãos. Não te tornes cúmplice de pecados de outrem. Conserva-te a ti mesmo puro.

[[v54-5-23]]

^<<v54-5-23,23>>^ Não continues a beber somente água; usa um pouco de vinho, por causa do teu estômago e das tuas frequentes enfermidades.

[[v54-5-24]]

^<<v54-5-24,24>>^ Os pecados de alguns homens são notórios e levam a juízo, ao passo que os de outros só mais tarde se manifestam.

[[v54-5-25]]

^<<v54-5-25,25>>^ Da mesma sorte também as boas obras, antecipadamente, se evidenciam e, quando assim não seja, não podem ocultar-se.

'''

xref:054-1-timoteo/054-1-timoteo-004.adoc#v54-4-0[&#60; Capítulo Anterior] | <<v54-5-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-006.adoc#v54-6-0[Próximo Capítulo &#62;]