include::./index.adoc[]

[[v54-6-0]]
=== 1 Timóteo, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v54-6-1]]

^<<v54-6-1,1>>^ Todos os servos que estão debaixo de jugo considerem dignos de toda honra o próprio senhor, para que o nome de Deus e a doutrina não sejam blasfemados.

[[v54-6-2]]

^<<v54-6-2,2>>^ Também os que têm senhor fiel não o tratem com desrespeito, porque é irmão; pelo contrário, trabalhem ainda mais, pois ele, que partilha do seu bom serviço, é crente e amado. Ensina e recomenda estas coisas.

[[v54-6-3]]

^<<v54-6-3,3>>^ Se alguém ensina outra doutrina e não concorda com as sãs palavras de nosso Senhor Jesus Cristo e com o ensino segundo a piedade,

[[v54-6-4]]

^<<v54-6-4,4>>^ é enfatuado, nada entende, mas tem mania por questões e contendas de palavras, de que nascem inveja, provocação, difamações, suspeitas malignas,

[[v54-6-5]]

^<<v54-6-5,5>>^ altercações sem fim, por homens cuja mente é pervertida e privados da verdade, supondo que a piedade é fonte de lucro.

[[v54-6-6]]

^<<v54-6-6,6>>^ De fato, grande fonte de lucro é a piedade com o contentamento.

[[v54-6-7]]

^<<v54-6-7,7>>^ Porque nada temos trazido para o mundo, nem coisa alguma podemos levar dele.

[[v54-6-8]]

^<<v54-6-8,8>>^ Tendo sustento e com que nos vestir, estejamos contentes.

[[v54-6-9]]

^<<v54-6-9,9>>^ Ora, os que querem ficar ricos caem em tentação, e cilada, e em muitas concupiscências insensatas e perniciosas, as quais afogam os homens na ruína e perdição.

[[v54-6-10]]

^<<v54-6-10,10>>^ Porque o amor do dinheiro é raiz de todos os males; e alguns, nessa cobiça, se desviaram da fé e a si mesmos se atormentaram com muitas dores.

[[v54-6-11]]

^<<v54-6-11,11>>^ Tu, porém, ó homem de Deus, foge destas coisas; antes, segue a justiça, a piedade, a fé, o amor, a constância, a mansidão.

[[v54-6-12]]

^<<v54-6-12,12>>^ Combate o bom combate da fé. Toma posse da vida eterna, para a qual também foste chamado e de que fizeste a boa confissão perante muitas testemunhas.

[[v54-6-13]]

^<<v54-6-13,13>>^ Exorto-te, perante Deus, que preserva a vida de todas as coisas, e perante Cristo Jesus, que, diante de Pôncio Pilatos, fez a boa confissão,

[[v54-6-14]]

^<<v54-6-14,14>>^ que guardes o mandato imaculado, irrepreensível, até à manifestação de nosso Senhor Jesus Cristo;

[[v54-6-15]]

^<<v54-6-15,15>>^ a qual, em suas épocas determinadas, há de ser revelada pelo bendito e único Soberano, o Rei dos reis e Senhor dos senhores;

[[v54-6-16]]

^<<v54-6-16,16>>^ o único que possui imortalidade, que habita em luz inacessível, a quem homem algum jamais viu, nem é capaz de ver. A ele honra e poder eterno. Amém!

[[v54-6-17]]

^<<v54-6-17,17>>^ Exorta aos ricos do presente século que não sejam orgulhosos, nem depositem a sua esperança na instabilidade da riqueza, mas em Deus, que tudo nos proporciona ricamente para nosso aprazimento;

[[v54-6-18]]

^<<v54-6-18,18>>^ que pratiquem o bem, sejam ricos de boas obras, generosos em dar e prontos a repartir;

[[v54-6-19]]

^<<v54-6-19,19>>^ que acumulem para si mesmos tesouros, sólido fundamento para o futuro, a fim de se apoderarem da verdadeira vida.

[[v54-6-20]]

^<<v54-6-20,20>>^ E tu, ó Timóteo, guarda o que te foi confiado, evitando os falatórios inúteis e profanos e as contradições do saber, como falsamente lhe chamam,

[[v54-6-21]]

^<<v54-6-21,21>>^ pois alguns, professando-o, se desviaram da fé. A graça seja convosco.

'''

xref:054-1-timoteo/054-1-timoteo-005.adoc#v54-5-0[&#60; Capítulo Anterior] | <<v54-6-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-001.adoc#v55-1-0[Próximo Capítulo &#62;]