include::./index.adoc[]

[[v44-7-0]]
=== Atos, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-7-1]]

^<<v44-7-1,1>>^ Então, lhe perguntou o sumo sacerdote: Porventura, é isto assim?

[[v44-7-2]]

^<<v44-7-2,2>>^ Estêvão respondeu: Varões irmãos e pais, ouvi. O Deus da glória apareceu a Abraão, nosso pai, quando estava na Mesopotâmia, antes de habitar em Harã,

[[v44-7-3]]

^<<v44-7-3,3>>^ e lhe disse: Sai da tua terra e da tua parentela e vem para a terra que eu te mostrarei.

[[v44-7-4]]

^<<v44-7-4,4>>^ Então, saiu da terra dos caldeus e foi habitar em Harã. E dali, com a morte de seu pai, Deus o trouxe para esta terra em que vós agora habitais.

[[v44-7-5]]

^<<v44-7-5,5>>^ Nela, não lhe deu herança, nem sequer o espaço de um pé; mas prometeu dar-lhe a posse dela e, depois dele, à sua descendência, não tendo ele filho.

[[v44-7-6]]

^<<v44-7-6,6>>^ E falou Deus que a sua descendência seria peregrina em terra estrangeira, onde seriam escravizados e maltratados por quatrocentos anos;

[[v44-7-7]]

^<<v44-7-7,7>>^ eu, disse Deus, julgarei a nação da qual forem escravos; e, depois disto, sairão daí e me servirão neste lugar.

[[v44-7-8]]

^<<v44-7-8,8>>^ Então, lhe deu a aliança da circuncisão; assim, nasceu Isaque, e Abraão o circuncidou ao oitavo dia; de Isaque procedeu Jacó, e deste, os doze patriarcas.

[[v44-7-9]]

^<<v44-7-9,9>>^ Os patriarcas, invejosos de José, venderam-no para o Egito; mas Deus estava com ele

[[v44-7-10]]

^<<v44-7-10,10>>^ e livrou-o de todas as suas aflições, concedendo-lhe também graça e sabedoria perante Faraó, rei do Egito, que o constituiu governador daquela nação e de toda a casa real.

[[v44-7-11]]

^<<v44-7-11,11>>^ Sobreveio, porém, fome em todo o Egito; e, em Canaã, houve grande tribulação, e nossos pais não achavam mantimentos.

[[v44-7-12]]

^<<v44-7-12,12>>^ Mas, tendo ouvido Jacó que no Egito havia trigo, enviou, pela primeira vez, os nossos pais.

[[v44-7-13]]

^<<v44-7-13,13>>^ Na segunda vez, José se fez reconhecer por seus irmãos, e se tornou conhecida de Faraó a família de José.

[[v44-7-14]]

^<<v44-7-14,14>>^ Então, José mandou chamar a Jacó, seu pai, e toda a sua parentela, isto é, setenta e cinco pessoas.

[[v44-7-15]]

^<<v44-7-15,15>>^ Jacó desceu ao Egito, e ali morreu ele e também nossos pais;

[[v44-7-16]]

^<<v44-7-16,16>>^ e foram transportados para Siquém e postos no sepulcro que Abraão ali comprara a dinheiro aos filhos de Hamor.

[[v44-7-17]]

^<<v44-7-17,17>>^ Como, porém, se aproximasse o tempo da promessa que Deus jurou a Abraão, o povo cresceu e se multiplicou no Egito,

[[v44-7-18]]

^<<v44-7-18,18>>^ até que se levantou ali outro rei, que não conhecia a José.

[[v44-7-19]]

^<<v44-7-19,19>>^ Este outro rei tratou com astúcia a nossa raça e torturou os nossos pais, a ponto de forçá-los a enjeitar seus filhos, para que não sobrevivessem.

[[v44-7-20]]

^<<v44-7-20,20>>^ Por esse tempo, nasceu Moisés, que era formoso aos olhos de Deus. Por três meses, foi ele mantido na casa de seu pai;

[[v44-7-21]]

^<<v44-7-21,21>>^ quando foi exposto, a filha de Faraó o recolheu e criou como seu próprio filho.

[[v44-7-22]]

^<<v44-7-22,22>>^ E Moisés foi educado em toda a ciência dos egípcios e era poderoso em palavras e obras.

[[v44-7-23]]

^<<v44-7-23,23>>^ Quando completou quarenta anos, veio-lhe a ideia de visitar seus irmãos, os filhos de Israel.

[[v44-7-24]]

^<<v44-7-24,24>>^ Vendo um homem tratado injustamente, tomou-lhe a defesa e vingou o oprimido, matando o egípcio.

[[v44-7-25]]

^<<v44-7-25,25>>^ Ora, Moisés cuidava que seus irmãos entenderiam que Deus os queria salvar por intermédio dele; eles, porém, não compreenderam.

[[v44-7-26]]

^<<v44-7-26,26>>^ No dia seguinte, aproximou-se de uns que brigavam e procurou reconduzi-los à paz, dizendo: Homens, vós sois irmãos; por que vos ofendeis uns aos outros?

[[v44-7-27]]

^<<v44-7-27,27>>^ Mas o que agredia o próximo o repeliu, dizendo: Quem te constituiu autoridade e juiz sobre nós?

[[v44-7-28]]

^<<v44-7-28,28>>^ Acaso, queres matar-me, como fizeste ontem ao egípcio?

[[v44-7-29]]

^<<v44-7-29,29>>^ A estas palavras Moisés fugiu e tornou-se peregrino na terra de Midiã, onde lhe nasceram dois filhos.

[[v44-7-30]]

^<<v44-7-30,30>>^ Decorridos quarenta anos, apareceu-lhe, no deserto do monte Sinai, um anjo, por entre as chamas de uma sarça que ardia.

[[v44-7-31]]

^<<v44-7-31,31>>^ Moisés, porém, diante daquela visão, ficou maravilhado e, aproximando-se para observar, ouviu-se a voz do Senhor:

[[v44-7-32]]

^<<v44-7-32,32>>^ Eu sou o Deus dos teus pais, o Deus de Abraão, de Isaque e de Jacó. Moisés, tremendo de medo, não ousava contemplá-la.

[[v44-7-33]]

^<<v44-7-33,33>>^ Disse-lhe o Senhor: Tira a sandália dos pés, porque o lugar em que estás é terra santa.

[[v44-7-34]]

^<<v44-7-34,34>>^ Vi, com efeito, o sofrimento do meu povo no Egito, ouvi o seu gemido e desci para libertá-lo. Vem agora, e eu te enviarei ao Egito.

[[v44-7-35]]

^<<v44-7-35,35>>^ A este Moisés, a quem negaram reconhecer, dizendo: Quem te constituiu autoridade e juiz? A este enviou Deus como chefe e libertador, com a assistência do anjo que lhe apareceu na sarça.

[[v44-7-36]]

^<<v44-7-36,36>>^ Este os tirou, fazendo prodígios e sinais na terra do Egito, assim como no mar Vermelho e no deserto, durante quarenta anos.

[[v44-7-37]]

^<<v44-7-37,37>>^ Foi Moisés quem disse aos filhos de Israel: Deus vos suscitará dentre vossos irmãos um profeta semelhante a mim.

[[v44-7-38]]

^<<v44-7-38,38>>^ É este Moisés quem esteve na congregação no deserto, com o anjo que lhe falava no monte Sinai e com os nossos pais; o qual recebeu palavras vivas para no-las transmitir.

[[v44-7-39]]

^<<v44-7-39,39>>^ A quem nossos pais não quiseram obedecer; antes, o repeliram e, no seu coração, voltaram para o Egito,

[[v44-7-40]]

^<<v44-7-40,40>>^ dizendo a Arão: Faze-nos deuses que vão adiante de nós; porque, quanto a este Moisés, que nos tirou da terra do Egito, não sabemos o que lhe aconteceu.

[[v44-7-41]]

^<<v44-7-41,41>>^ Naqueles dias, fizeram um bezerro e ofereceram sacrifício ao ídolo, alegrando-se com as obras das suas mãos.

[[v44-7-42]]

^<<v44-7-42,42>>^ Mas Deus se afastou e os entregou ao culto da milícia celestial, como está escrito no Livro dos Profetas: Ó casa de Israel, porventura, me oferecestes vítimas e sacrifícios no deserto, pelo espaço de quarenta anos,

[[v44-7-43]]

^<<v44-7-43,43>>^ e, acaso, não levantastes o tabernáculo de Moloque e a estrela do deus Renfã, figuras que fizestes para as adorar? Por isso, vos desterrarei para além da Babilônia.

[[v44-7-44]]

^<<v44-7-44,44>>^ O tabernáculo do Testemunho estava entre nossos pais no deserto, como determinara aquele que disse a Moisés que o fizesse segundo o modelo que tinha visto.

[[v44-7-45]]

^<<v44-7-45,45>>^ O qual também nossos pais, com Josué, tendo-o recebido, o levaram, quando tomaram posse das nações que Deus expulsou da presença deles, até aos dias de Davi.

[[v44-7-46]]

^<<v44-7-46,46>>^ Este achou graça diante de Deus e lhe suplicou a faculdade de prover morada para o Deus de Jacó.

[[v44-7-47]]

^<<v44-7-47,47>>^ Mas foi Salomão quem lhe edificou a casa.

[[v44-7-48]]

^<<v44-7-48,48>>^ Entretanto, não habita o Altíssimo em casas feitas por mãos humanas; como diz o profeta:

[[v44-7-49]]

^<<v44-7-49,49>>^ O céu é o meu trono, e a terra, o estrado dos meus pés; que casa me edificareis, diz o Senhor, ou qual é o lugar do meu repouso?

[[v44-7-50]]

^<<v44-7-50,50>>^ Não foi, porventura, a minha mão que fez todas estas coisas?

[[v44-7-51]]

^<<v44-7-51,51>>^ Homens de dura cerviz e incircuncisos de coração e de ouvidos, vós sempre resistis ao Espírito Santo; assim como fizeram vossos pais, também vós o fazeis.

[[v44-7-52]]

^<<v44-7-52,52>>^ Qual dos profetas vossos pais não perseguiram? Eles mataram os que anteriormente anunciavam a vinda do Justo, do qual vós agora vos tornastes traidores e assassinos,

[[v44-7-53]]

^<<v44-7-53,53>>^ vós que recebestes a lei por ministério de anjos e não a guardastes.

[[v44-7-54]]

^<<v44-7-54,54>>^ Ouvindo eles isto, enfureciam-se no seu coração e rilhavam os dentes contra ele.

[[v44-7-55]]

^<<v44-7-55,55>>^ Mas Estêvão, cheio do Espírito Santo, fitou os olhos no céu e viu a glória de Deus e Jesus, que estava à sua direita,

[[v44-7-56]]

^<<v44-7-56,56>>^ e disse: Eis que vejo os céus abertos e o Filho do Homem, em pé à destra de Deus.

[[v44-7-57]]

^<<v44-7-57,57>>^ Eles, porém, clamando em alta voz, taparam os ouvidos e, unânimes, arremeteram contra ele.

[[v44-7-58]]

^<<v44-7-58,58>>^ E, lançando-o fora da cidade, o apedrejaram. As testemunhas deixaram suas vestes aos pés de um jovem chamado Saulo.

[[v44-7-59]]

^<<v44-7-59,59>>^ E apedrejavam Estêvão, que invocava e dizia: Senhor Jesus, recebe o meu espírito!

[[v44-7-60]]

^<<v44-7-60,60>>^ Então, ajoelhando-se, clamou em alta voz: Senhor, não lhes imputes este pecado! Com estas palavras, adormeceu.

'''

xref:044-atos/044-atos-006.adoc#v44-6-0[&#60; Capítulo Anterior] | <<v44-7-0,Topo>> | xref:044-atos/044-atos-008.adoc#v44-8-0[Próximo Capítulo &#62;]