include::./index.adoc[]

[[v44-22-0]]
=== Atos, 22
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-22-1]]

^<<v44-22-1,1>>^ Irmãos e pais, ouvi, agora, a minha defesa perante vós.

[[v44-22-2]]

^<<v44-22-2,2>>^ Quando ouviram que lhes falava em língua hebraica, guardaram ainda maior silêncio. E continuou:

[[v44-22-3]]

^<<v44-22-3,3>>^ Eu sou judeu, nasci em Tarso da Cilícia, mas criei-me nesta cidade e aqui fui instruído aos pés de Gamaliel, segundo a exatidão da lei de nossos antepassados, sendo zeloso para com Deus, assim como todos vós o sois no dia de hoje.

[[v44-22-4]]

^<<v44-22-4,4>>^ Persegui este Caminho até à morte, prendendo e metendo em cárceres homens e mulheres,

[[v44-22-5]]

^<<v44-22-5,5>>^ de que são testemunhas o sumo sacerdote e todos os anciãos. Destes, recebi cartas para os irmãos; e ia para Damasco, no propósito de trazer manietados para Jerusalém os que também lá estivessem, para serem punidos.

[[v44-22-6]]

^<<v44-22-6,6>>^ Ora, aconteceu que, indo de caminho e já perto de Damasco, quase ao meio-dia, repentinamente, grande luz do céu brilhou ao redor de mim.

[[v44-22-7]]

^<<v44-22-7,7>>^ Então, caí por terra, ouvindo uma voz que me dizia: Saulo, Saulo, por que me persegues?

[[v44-22-8]]

^<<v44-22-8,8>>^ Perguntei: quem és tu, Senhor? Ao que me respondeu: Eu sou Jesus, o Nazareno, a quem tu persegues.

[[v44-22-9]]

^<<v44-22-9,9>>^ Os que estavam comigo viram a luz, sem, contudo, perceberem o sentido da voz de quem falava comigo.

[[v44-22-10]]

^<<v44-22-10,10>>^ Então, perguntei: que farei, Senhor? E o Senhor me disse: Levanta-te, entra em Damasco, pois ali te dirão acerca de tudo o que te é ordenado fazer.

[[v44-22-11]]

^<<v44-22-11,11>>^ Tendo ficado cego por causa do fulgor daquela luz, guiado pela mão dos que estavam comigo, cheguei a Damasco.

[[v44-22-12]]

^<<v44-22-12,12>>^ Um homem, chamado Ananias, piedoso conforme a lei, tendo bom testemunho de todos os judeus que ali moravam,

[[v44-22-13]]

^<<v44-22-13,13>>^ veio procurar-me e, pondo-se junto a mim, disse: Saulo, irmão, recebe novamente a vista. Nessa mesma hora, recobrei a vista e olhei para ele.

[[v44-22-14]]

^<<v44-22-14,14>>^ Então, ele disse: O Deus de nossos pais, de antemão, te escolheu para conheceres a sua vontade, veres o Justo e ouvires uma voz da sua própria boca,

[[v44-22-15]]

^<<v44-22-15,15>>^ porque terás de ser sua testemunha diante de todos os homens, das coisas que tens visto e ouvido.

[[v44-22-16]]

^<<v44-22-16,16>>^ E agora, por que te demoras? Levanta-te, recebe o batismo e lava os teus pecados, invocando o nome dele.

[[v44-22-17]]

^<<v44-22-17,17>>^ Tendo eu voltado para Jerusalém, enquanto orava no templo, sobreveio-me um êxtase,

[[v44-22-18]]

^<<v44-22-18,18>>^ e vi aquele que falava comigo: Apressa-te e sai logo de Jerusalém, porque não receberão o teu testemunho a meu respeito.

[[v44-22-19]]

^<<v44-22-19,19>>^ Eu disse: Senhor, eles bem sabem que eu encerrava em prisão e, nas sinagogas, açoitava os que criam em ti.

[[v44-22-20]]

^<<v44-22-20,20>>^ Quando se derramava o sangue de Estêvão, tua testemunha, eu também estava presente, consentia nisso e até guardei as vestes dos que o matavam.

[[v44-22-21]]

^<<v44-22-21,21>>^ Mas ele me disse: Vai, porque eu te enviarei para longe, aos gentios.

[[v44-22-22]]

^<<v44-22-22,22>>^ Ouviram-no até essa palavra e, então, gritaram, dizendo: Tira tal homem da terra, porque não convém que ele viva!

[[v44-22-23]]

^<<v44-22-23,23>>^ Ora, estando eles gritando, arrojando de si as suas capas, atirando poeira para os ares,

[[v44-22-24]]

^<<v44-22-24,24>>^ ordenou o comandante que Paulo fosse recolhido à fortaleza e que, sob açoite, fosse interrogado para saber por que motivo assim clamavam contra ele.

[[v44-22-25]]

^<<v44-22-25,25>>^ Quando o estavam amarrando com correias, disse Paulo ao centurião presente: Ser-vos-á, porventura, lícito açoitar um cidadão romano, sem estar condenado?

[[v44-22-26]]

^<<v44-22-26,26>>^ Ouvindo isto, o centurião procurou o comandante e lhe disse: Que estás para fazer? Porque este homem é cidadão romano.

[[v44-22-27]]

^<<v44-22-27,27>>^ Vindo o comandante, perguntou a Paulo: Dize-me: és tu romano? Ele disse: Sou.

[[v44-22-28]]

^<<v44-22-28,28>>^ Respondeu-lhe o comandante: A mim me custou grande soma de dinheiro este título de cidadão. Disse Paulo: Pois eu o tenho por direito de nascimento.

[[v44-22-29]]

^<<v44-22-29,29>>^ Imediatamente, se afastaram os que estavam para o inquirir com açoites. O próprio comandante sentiu-se receoso quando soube que Paulo era romano, porque o mandara amarrar.

[[v44-22-30]]

^<<v44-22-30,30>>^ No dia seguinte, querendo certificar-se dos motivos por que vinha ele sendo acusado pelos judeus, soltou-o, e ordenou que se reunissem os principais sacerdotes e todo o Sinédrio, e, mandando trazer Paulo, apresentou-o perante eles.

'''

xref:044-atos/044-atos-021.adoc#v44-21-0[&#60; Capítulo Anterior] | <<v44-22-0,Topo>> | xref:044-atos/044-atos-023.adoc#v44-23-0[Próximo Capítulo &#62;]