include::./index.adoc[]

[[v44-5-0]]
=== Atos, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-5-1]]

^<<v44-5-1,1>>^ Entretanto, certo homem, chamado Ananias, com sua mulher Safira, vendeu uma propriedade,

[[v44-5-2]]

^<<v44-5-2,2>>^ mas, em acordo com sua mulher, reteve parte do preço e, levando o restante, depositou-o aos pés dos apóstolos.

[[v44-5-3]]

^<<v44-5-3,3>>^ Então, disse Pedro: Ananias, por que encheu Satanás teu coração, para que mentisses ao Espírito Santo, reservando parte do valor do campo?

[[v44-5-4]]

^<<v44-5-4,4>>^ Conservando-o, porventura, não seria teu? E, vendido, não estaria em teu poder? Como, pois, assentaste no coração este desígnio? Não mentiste aos homens, mas a Deus.

[[v44-5-5]]

^<<v44-5-5,5>>^ Ouvindo estas palavras, Ananias caiu e expirou, sobrevindo grande temor a todos os ouvintes.

[[v44-5-6]]

^<<v44-5-6,6>>^ Levantando-se os moços, cobriram-lhe o corpo e, levando-o, o sepultaram.

[[v44-5-7]]

^<<v44-5-7,7>>^ Quase três horas depois, entrou a mulher de Ananias, não sabendo o que ocorrera.

[[v44-5-8]]

^<<v44-5-8,8>>^ Então, Pedro, dirigindo-se a ela, perguntou-lhe: Dize-me, vendestes por tanto aquela terra? Ela respondeu: Sim, por tanto.

[[v44-5-9]]

^<<v44-5-9,9>>^ Tornou-lhe Pedro: Por que entrastes em acordo para tentar o Espírito do Senhor? Eis aí à porta os pés dos que sepultaram o teu marido, e eles também te levarão.

[[v44-5-10]]

^<<v44-5-10,10>>^ No mesmo instante, caiu ela aos pés de Pedro e expirou. Entrando os moços, acharam-na morta e, levando-a, sepultaram-na junto do marido.

[[v44-5-11]]

^<<v44-5-11,11>>^ E sobreveio grande temor a toda a igreja e a todos quantos ouviram a notícia destes acontecimentos.

[[v44-5-12]]

^<<v44-5-12,12>>^ Muitos sinais e prodígios eram feitos entre o povo pelas mãos dos apóstolos. E costumavam todos reunir-se, de comum acordo, no Pórtico de Salomão.

[[v44-5-13]]

^<<v44-5-13,13>>^ Mas, dos restantes, ninguém ousava ajuntar-se a eles; porém o povo lhes tributava grande admiração.

[[v44-5-14]]

^<<v44-5-14,14>>^ E crescia mais e mais a multidão de crentes, tanto homens como mulheres, agregados ao Senhor,

[[v44-5-15]]

^<<v44-5-15,15>>^ a ponto de levarem os enfermos até pelas ruas e os colocarem sobre leitos e macas, para que, ao passar Pedro, ao menos a sua sombra se projetasse nalguns deles.

[[v44-5-16]]

^<<v44-5-16,16>>^ Afluía também muita gente das cidades vizinhas a Jerusalém, levando doentes e atormentados de espíritos imundos, e todos eram curados.

[[v44-5-17]]

^<<v44-5-17,17>>^ Levantando-se, porém, o sumo sacerdote e todos os que estavam com ele, isto é, a seita dos saduceus, tomaram-se de inveja,

[[v44-5-18]]

^<<v44-5-18,18>>^ prenderam os apóstolos e os recolheram à prisão pública.

[[v44-5-19]]

^<<v44-5-19,19>>^ Mas, de noite, um anjo do Senhor abriu as portas do cárcere e, conduzindo-os para fora, lhes disse:

[[v44-5-20]]

^<<v44-5-20,20>>^ Ide e, apresentando-vos no templo, dizei ao povo todas as palavras desta Vida.

[[v44-5-21]]

^<<v44-5-21,21>>^ Tendo ouvido isto, logo ao romper do dia, entraram no templo e ensinavam. Chegando, porém, o sumo sacerdote e os que com ele estavam, convocaram o Sinédrio e todo o senado dos filhos de Israel e mandaram buscá-los no cárcere.

[[v44-5-22]]

^<<v44-5-22,22>>^ Mas os guardas, indo, não os acharam no cárcere; e, tendo voltado, relataram,

[[v44-5-23]]

^<<v44-5-23,23>>^ dizendo: Achamos o cárcere fechado com toda a segurança e as sentinelas nos seus postos junto às portas; mas, abrindo-as, a ninguém encontramos dentro.

[[v44-5-24]]

^<<v44-5-24,24>>^ Quando o capitão do templo e os principais sacerdotes ouviram estas informações, ficaram perplexos a respeito deles e do que viria a ser isto.

[[v44-5-25]]

^<<v44-5-25,25>>^ Nesse ínterim, alguém chegou e lhes comunicou: Eis que os homens que recolhestes no cárcere, estão no templo ensinando o povo.

[[v44-5-26]]

^<<v44-5-26,26>>^ Nisto, indo o capitão e os guardas, os trouxeram sem violência, porque temiam ser apedrejados pelo povo.

[[v44-5-27]]

^<<v44-5-27,27>>^ Trouxeram-nos, apresentando-os ao Sinédrio. E o sumo sacerdote interrogou-os,

[[v44-5-28]]

^<<v44-5-28,28>>^ dizendo: Expressamente vos ordenamos que não ensinásseis nesse nome; contudo, enchestes Jerusalém de vossa doutrina; e quereis lançar sobre nós o sangue desse homem.

[[v44-5-29]]

^<<v44-5-29,29>>^ Então, Pedro e os demais apóstolos afirmaram: Antes, importa obedecer a Deus do que aos homens.

[[v44-5-30]]

^<<v44-5-30,30>>^ O Deus de nossos pais ressuscitou a Jesus, a quem vós matastes, pendurando-o num madeiro.

[[v44-5-31]]

^<<v44-5-31,31>>^ Deus, porém, com a sua destra, o exaltou a Príncipe e Salvador, a fim de conceder a Israel o arrependimento e a remissão de pecados.

[[v44-5-32]]

^<<v44-5-32,32>>^ Ora, nós somos testemunhas destes fatos, e bem assim o Espírito Santo, que Deus outorgou aos que lhe obedecem.

[[v44-5-33]]

^<<v44-5-33,33>>^ Eles, porém, ouvindo, se enfureceram e queriam matá-los.

[[v44-5-34]]

^<<v44-5-34,34>>^ Mas, levantando-se no Sinédrio um fariseu, chamado Gamaliel, mestre da lei, acatado por todo o povo, mandou retirar os homens, por um pouco,

[[v44-5-35]]

^<<v44-5-35,35>>^ e lhes disse: Israelitas, atentai bem no que ides fazer a estes homens.

[[v44-5-36]]

^<<v44-5-36,36>>^ Porque, antes destes dias, se levantou Teudas, insinuando ser ele alguma coisa, ao qual se agregaram cerca de quatrocentos homens; mas ele foi morto, e todos quantos lhe prestavam obediência se dispersaram e deram em nada.

[[v44-5-37]]

^<<v44-5-37,37>>^ Depois desse, levantou-se Judas, o galileu, nos dias do recenseamento, e levou muitos consigo; também este pereceu, e todos quantos lhe obedeciam foram dispersos.

[[v44-5-38]]

^<<v44-5-38,38>>^ Agora, vos digo: dai de mão a estes homens, deixai-os; porque, se este conselho ou esta obra vem de homens, perecerá;

[[v44-5-39]]

^<<v44-5-39,39>>^ mas, se é de Deus, não podereis destruí-los, para que não sejais, porventura, achados lutando contra Deus. E concordaram com ele.

[[v44-5-40]]

^<<v44-5-40,40>>^ Chamando os apóstolos, açoitaram-nos e, ordenando-lhes que não falassem em o nome de Jesus, os soltaram.

[[v44-5-41]]

^<<v44-5-41,41>>^ E eles se retiraram do Sinédrio regozijando-se por terem sido considerados dignos de sofrer afrontas por esse Nome.

[[v44-5-42]]

^<<v44-5-42,42>>^ E todos os dias, no templo e de casa em casa, não cessavam de ensinar e de pregar Jesus, o Cristo.

'''

xref:044-atos/044-atos-004.adoc#v44-4-0[&#60; Capítulo Anterior] | <<v44-5-0,Topo>> | xref:044-atos/044-atos-006.adoc#v44-6-0[Próximo Capítulo &#62;]