include::./index.adoc[]

[[v44-2-0]]
=== Atos, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-2-1]]

^<<v44-2-1,1>>^ Ao cumprir-se o dia de Pentecostes, estavam todos reunidos no mesmo lugar;

[[v44-2-2]]

^<<v44-2-2,2>>^ de repente, veio do céu um som, como de um vento impetuoso, e encheu toda a casa onde estavam assentados.

[[v44-2-3]]

^<<v44-2-3,3>>^ E apareceram, distribuídas entre eles, línguas, como de fogo, e pousou uma sobre cada um deles.

[[v44-2-4]]

^<<v44-2-4,4>>^ Todos ficaram cheios do Espírito Santo e passaram a falar em outras línguas, segundo o Espírito lhes concedia que falassem.

[[v44-2-5]]

^<<v44-2-5,5>>^ Ora, estavam habitando em Jerusalém judeus, homens piedosos, vindos de todas as nações debaixo do céu.

[[v44-2-6]]

^<<v44-2-6,6>>^ Quando, pois, se fez ouvir aquela voz, afluiu a multidão, que se possuiu de perplexidade, porquanto cada um os ouvia falar na sua própria língua.

[[v44-2-7]]

^<<v44-2-7,7>>^ Estavam, pois, atônitos e se admiravam, dizendo: Vede! Não são, porventura, galileus todos esses que aí estão falando?

[[v44-2-8]]

^<<v44-2-8,8>>^ E como os ouvimos falar, cada um em nossa própria língua materna?

[[v44-2-9]]

^<<v44-2-9,9>>^ Somos partos, medos, elamitas e os naturais da Mesopotâmia, Judeia, Capadócia, Ponto e Ásia,

[[v44-2-10]]

^<<v44-2-10,10>>^ da Frígia, da Panfília, do Egito e das regiões da Líbia, nas imediações de Cirene, e romanos que aqui residem,

[[v44-2-11]]

^<<v44-2-11,11>>^ tanto judeus como prosélitos, cretenses e arábios. Como os ouvimos falar em nossas próprias línguas as grandezas de Deus?

[[v44-2-12]]

^<<v44-2-12,12>>^ Todos, atônitos e perplexos, interpelavam uns aos outros: Que quer isto dizer?

[[v44-2-13]]

^<<v44-2-13,13>>^ Outros, porém, zombando, diziam: Estão embriagados!

[[v44-2-14]]

^<<v44-2-14,14>>^ Então, se levantou Pedro, com os onze; e, erguendo a voz, advertiu-os nestes termos: Varões judeus e todos os habitantes de Jerusalém, tomai conhecimento disto e atentai nas minhas palavras.

[[v44-2-15]]

^<<v44-2-15,15>>^ Estes homens não estão embriagados, como vindes pensando, sendo esta a terceira hora do dia.

[[v44-2-16]]

^<<v44-2-16,16>>^ Mas o que ocorre é o que foi dito por intermédio do profeta Joel:

[[v44-2-17]]

^<<v44-2-17,17>>^ E acontecerá nos últimos dias, diz o Senhor, que derramarei do meu Espírito sobre toda a carne; vossos filhos e vossas filhas profetizarão, vossos jovens terão visões, e sonharão vossos velhos;

[[v44-2-18]]

^<<v44-2-18,18>>^ até sobre os meus servos e sobre as minhas servas derramarei do meu Espírito naqueles dias, e profetizarão.

[[v44-2-19]]

^<<v44-2-19,19>>^ Mostrarei prodígios em cima no céu e sinais embaixo na terra: sangue, fogo e vapor de fumaça.

[[v44-2-20]]

^<<v44-2-20,20>>^ O sol se converterá em trevas, e a lua, em sangue, antes que venha o grande e glorioso Dia do Senhor.

[[v44-2-21]]

^<<v44-2-21,21>>^ E acontecerá que todo aquele que invocar o nome do Senhor será salvo.

[[v44-2-22]]

^<<v44-2-22,22>>^ Varões israelitas, atendei a estas palavras: Jesus, o Nazareno, varão aprovado por Deus diante de vós com milagres, prodígios e sinais, os quais o próprio Deus realizou por intermédio dele entre vós, como vós mesmos sabeis;

[[v44-2-23]]

^<<v44-2-23,23>>^ sendo este entregue pelo determinado desígnio e presciência de Deus, vós o matastes, crucificando-o por mãos de iníquos;

[[v44-2-24]]

^<<v44-2-24,24>>^ ao qual, porém, Deus ressuscitou, rompendo os grilhões da morte; porquanto não era possível fosse ele retido por ela.

[[v44-2-25]]

^<<v44-2-25,25>>^ Porque a respeito dele diz Davi: Diante de mim via sempre o Senhor, porque está à minha direita, para que eu não seja abalado.

[[v44-2-26]]

^<<v44-2-26,26>>^ Por isso, se alegrou o meu coração, e a minha língua exultou; além disto, também a minha própria carne repousará em esperança,

[[v44-2-27]]

^<<v44-2-27,27>>^ porque não deixarás a minha alma na morte, nem permitirás que o teu Santo veja corrupção.

[[v44-2-28]]

^<<v44-2-28,28>>^ Fizeste-me conhecer os caminhos da vida, encher-me-ás de alegria na tua presença.

[[v44-2-29]]

^<<v44-2-29,29>>^ Irmãos, seja-me permitido dizer-vos claramente a respeito do patriarca Davi que ele morreu e foi sepultado, e o seu túmulo permanece entre nós até hoje.

[[v44-2-30]]

^<<v44-2-30,30>>^ Sendo, pois, profeta e sabendo que Deus lhe havia jurado que um dos seus descendentes se assentaria no seu trono,

[[v44-2-31]]

^<<v44-2-31,31>>^ prevendo isto, referiu-se à ressurreição de Cristo, que nem foi deixado na morte, nem o seu corpo experimentou corrupção.

[[v44-2-32]]

^<<v44-2-32,32>>^ A este Jesus Deus ressuscitou, do que todos nós somos testemunhas.

[[v44-2-33]]

^<<v44-2-33,33>>^ Exaltado, pois, à destra de Deus, tendo recebido do Pai a promessa do Espírito Santo, derramou isto que vedes e ouvis.

[[v44-2-34]]

^<<v44-2-34,34>>^ Porque Davi não subiu aos céus, mas ele mesmo declara: Disse o Senhor ao meu Senhor: Assenta-te à minha direita,

[[v44-2-35]]

^<<v44-2-35,35>>^ até que eu ponha os teus inimigos por estrado dos teus pés.

[[v44-2-36]]

^<<v44-2-36,36>>^ Esteja absolutamente certa, pois, toda a casa de Israel de que a este Jesus, que vós crucificastes, Deus o fez Senhor e Cristo.

[[v44-2-37]]

^<<v44-2-37,37>>^ Ouvindo eles estas coisas, compungiu-se-lhes o coração e perguntaram a Pedro e aos demais apóstolos: Que faremos, irmãos?

[[v44-2-38]]

^<<v44-2-38,38>>^ Respondeu-lhes Pedro: Arrependei-vos, e cada um de vós seja batizado em nome de Jesus Cristo para remissão dos vossos pecados, e recebereis o dom do Espírito Santo.

[[v44-2-39]]

^<<v44-2-39,39>>^ Pois para vós outros é a promessa, para vossos filhos e para todos os que ainda estão longe, isto é, para quantos o Senhor, nosso Deus, chamar.

[[v44-2-40]]

^<<v44-2-40,40>>^ Com muitas outras palavras deu testemunho e exortava-os, dizendo: Salvai-vos desta geração perversa.

[[v44-2-41]]

^<<v44-2-41,41>>^ Então, os que lhe aceitaram a palavra foram batizados, havendo um acréscimo naquele dia de quase três mil pessoas.

[[v44-2-42]]

^<<v44-2-42,42>>^ E perseveravam na doutrina dos apóstolos e na comunhão, no partir do pão e nas orações.

[[v44-2-43]]

^<<v44-2-43,43>>^ Em cada alma havia temor; e muitos prodígios e sinais eram feitos por intermédio dos apóstolos.

[[v44-2-44]]

^<<v44-2-44,44>>^ Todos os que creram estavam juntos e tinham tudo em comum.

[[v44-2-45]]

^<<v44-2-45,45>>^ Vendiam as suas propriedades e bens, distribuindo o produto entre todos, à medida que alguém tinha necessidade.

[[v44-2-46]]

^<<v44-2-46,46>>^ Diariamente perseveravam unânimes no templo, partiam pão de casa em casa e tomavam as suas refeições com alegria e singeleza de coração,

[[v44-2-47]]

^<<v44-2-47,47>>^ louvando a Deus e contando com a simpatia de todo o povo. Enquanto isso, acrescentava-lhes o Senhor, dia a dia, os que iam sendo salvos.

'''

xref:044-atos/044-atos-001.adoc#v44-1-0[&#60; Capítulo Anterior] | <<v44-2-0,Topo>> | xref:044-atos/044-atos-003.adoc#v44-3-0[Próximo Capítulo &#62;]