include::./index.adoc[]

[[v44-4-0]]
=== Atos, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-4-1]]

^<<v44-4-1,1>>^ Falavam eles ainda ao povo quando sobrevieram os sacerdotes, o capitão do templo e os saduceus,

[[v44-4-2]]

^<<v44-4-2,2>>^ ressentidos por ensinarem eles o povo e anunciarem, em Jesus, a ressurreição dentre os mortos;

[[v44-4-3]]

^<<v44-4-3,3>>^ e os prenderam, recolhendo-os ao cárcere até ao dia seguinte, pois já era tarde.

[[v44-4-4]]

^<<v44-4-4,4>>^ Muitos, porém, dos que ouviram a palavra a aceitaram, subindo o número de homens a quase cinco mil.

[[v44-4-5]]

^<<v44-4-5,5>>^ No dia seguinte, reuniram-se em Jerusalém as autoridades, os anciãos e os escribas

[[v44-4-6]]

^<<v44-4-6,6>>^ com o sumo sacerdote Anás, Caifás, João, Alexandre e todos os que eram da linhagem do sumo sacerdote;

[[v44-4-7]]

^<<v44-4-7,7>>^ e, pondo-os perante eles, os arguiram: Com que poder ou em nome de quem fizestes isto?

[[v44-4-8]]

^<<v44-4-8,8>>^ Então, Pedro, cheio do Espírito Santo, lhes disse: Autoridades do povo e anciãos,

[[v44-4-9]]

^<<v44-4-9,9>>^ visto que hoje somos interrogados a propósito do benefício feito a um homem enfermo e do modo por que foi curado,

[[v44-4-10]]

^<<v44-4-10,10>>^ tomai conhecimento, vós todos e todo o povo de Israel, de que, em nome de Jesus Cristo, o Nazareno, a quem vós crucificastes, e a quem Deus ressuscitou dentre os mortos, sim, em seu nome é que este está curado perante vós.

[[v44-4-11]]

^<<v44-4-11,11>>^ Este Jesus é pedra rejeitada por vós, os construtores, a qual se tornou a pedra angular.

[[v44-4-12]]

^<<v44-4-12,12>>^ E não há salvação em nenhum outro; porque abaixo do céu não existe nenhum outro nome, dado entre os homens, pelo qual importa que sejamos salvos.

[[v44-4-13]]

^<<v44-4-13,13>>^ Ao verem a intrepidez de Pedro e João, sabendo que eram homens iletrados e incultos, admiraram-se; e reconheceram que haviam eles estado com Jesus.

[[v44-4-14]]

^<<v44-4-14,14>>^ Vendo com eles o homem que fora curado, nada tinham que dizer em contrário.

[[v44-4-15]]

^<<v44-4-15,15>>^ E, mandando-os sair do Sinédrio, consultavam entre si,

[[v44-4-16]]

^<<v44-4-16,16>>^ dizendo: Que faremos com estes homens? Pois, na verdade, é manifesto a todos os habitantes de Jerusalém que um sinal notório foi feito por eles, e não o podemos negar;

[[v44-4-17]]

^<<v44-4-17,17>>^ mas, para que não haja maior divulgação entre o povo, ameacemo-los para não mais falarem neste nome a quem quer que seja.

[[v44-4-18]]

^<<v44-4-18,18>>^ Chamando-os, ordenaram-lhes que absolutamente não falassem, nem ensinassem em o nome de Jesus.

[[v44-4-19]]

^<<v44-4-19,19>>^ Mas Pedro e João lhes responderam: Julgai se é justo diante de Deus ouvir-vos antes a vós outros do que a Deus;

[[v44-4-20]]

^<<v44-4-20,20>>^ pois nós não podemos deixar de falar das coisas que vimos e ouvimos.

[[v44-4-21]]

^<<v44-4-21,21>>^ Depois, ameaçando-os mais ainda, os soltaram, não tendo achado como os castigar, por causa do povo, porque todos glorificavam a Deus pelo que acontecera.

[[v44-4-22]]

^<<v44-4-22,22>>^ Ora, tinha mais de quarenta anos aquele em quem se operara essa cura milagrosa.

[[v44-4-23]]

^<<v44-4-23,23>>^ Uma vez soltos, procuraram os irmãos e lhes contaram quantas coisas lhes haviam dito os principais sacerdotes e os anciãos.

[[v44-4-24]]

^<<v44-4-24,24>>^ Ouvindo isto, unânimes, levantaram a voz a Deus e disseram: Tu, Soberano Senhor, que fizeste o céu, a terra, o mar e tudo o que neles há;

[[v44-4-25]]

^<<v44-4-25,25>>^ que disseste por intermédio do Espírito Santo, por boca de Davi, nosso pai, teu servo: Por que se enfureceram os gentios, e os povos imaginaram coisas vãs?

[[v44-4-26]]

^<<v44-4-26,26>>^ Levantaram-se os reis da terra, e as autoridades ajuntaram-se à uma contra o Senhor e contra o seu Ungido;

[[v44-4-27]]

^<<v44-4-27,27>>^ porque verdadeiramente se ajuntaram nesta cidade contra o teu santo Servo Jesus, ao qual ungiste, Herodes e Pôncio Pilatos, com gentios e gente de Israel,

[[v44-4-28]]

^<<v44-4-28,28>>^ para fazerem tudo o que a tua mão e o teu propósito predeterminaram;

[[v44-4-29]]

^<<v44-4-29,29>>^ agora, Senhor, olha para as suas ameaças e concede aos teus servos que anunciem com toda a intrepidez a tua palavra,

[[v44-4-30]]

^<<v44-4-30,30>>^ enquanto estendes a mão para fazer curas, sinais e prodígios por intermédio do nome do teu santo Servo Jesus.

[[v44-4-31]]

^<<v44-4-31,31>>^ Tendo eles orado, tremeu o lugar onde estavam reunidos; todos ficaram cheios do Espírito Santo e, com intrepidez, anunciavam a palavra de Deus.

[[v44-4-32]]

^<<v44-4-32,32>>^ Da multidão dos que creram era um o coração e a alma. Ninguém considerava exclusivamente sua nem uma das coisas que possuía; tudo, porém, lhes era comum.

[[v44-4-33]]

^<<v44-4-33,33>>^ Com grande poder, os apóstolos davam testemunho da ressurreição do Senhor Jesus, e em todos eles havia abundante graça.

[[v44-4-34]]

^<<v44-4-34,34>>^ Pois nenhum necessitado havia entre eles, porquanto os que possuíam terras ou casas, vendendo-as, traziam os valores correspondentes

[[v44-4-35]]

^<<v44-4-35,35>>^ e depositavam aos pés dos apóstolos; então, se distribuía a qualquer um à medida que alguém tinha necessidade.

[[v44-4-36]]

^<<v44-4-36,36>>^ José, a quem os apóstolos deram o sobrenome de Barnabé, que quer dizer filho de exortação, levita, natural de Chipre,

[[v44-4-37]]

^<<v44-4-37,37>>^ como tivesse um campo, vendendo-o, trouxe o preço e o depositou aos pés dos apóstolos.

'''

xref:044-atos/044-atos-003.adoc#v44-3-0[&#60; Capítulo Anterior] | <<v44-4-0,Topo>> | xref:044-atos/044-atos-005.adoc#v44-5-0[Próximo Capítulo &#62;]