include::./index.adoc[]

[[v44-10-0]]
=== Atos, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-10-1]]

^<<v44-10-1,1>>^ Morava em Cesareia um homem de nome Cornélio, centurião da coorte chamada Italiana,

[[v44-10-2]]

^<<v44-10-2,2>>^ piedoso e temente a Deus com toda a sua casa e que fazia muitas esmolas ao povo e, de contínuo, orava a Deus.

[[v44-10-3]]

^<<v44-10-3,3>>^ Esse homem observou claramente durante uma visão, cerca da hora nona do dia, um anjo de Deus que se aproximou dele e lhe disse:

[[v44-10-4]]

^<<v44-10-4,4>>^ Cornélio! Este, fixando nele os olhos e possuído de temor, perguntou: Que é, Senhor? E o anjo lhe disse: As tuas orações e as tuas esmolas subiram para memória diante de Deus.

[[v44-10-5]]

^<<v44-10-5,5>>^ Agora, envia mensageiros a Jope e manda chamar Simão, que tem por sobrenome Pedro.

[[v44-10-6]]

^<<v44-10-6,6>>^ Ele está hospedado com Simão, curtidor, cuja residência está situada à beira-mar.

[[v44-10-7]]

^<<v44-10-7,7>>^ Logo que se retirou o anjo que lhe falava, chamou dois dos seus domésticos e um soldado piedoso dos que estavam a seu serviço

[[v44-10-8]]

^<<v44-10-8,8>>^ e, havendo-lhes contado tudo, enviou-os a Jope.

[[v44-10-9]]

^<<v44-10-9,9>>^ No dia seguinte, indo eles de caminho e estando já perto da cidade, subiu Pedro ao eirado, por volta da hora sexta, a fim de orar.

[[v44-10-10]]

^<<v44-10-10,10>>^ Estando com fome, quis comer; mas, enquanto lhe preparavam a comida, sobreveio-lhe um êxtase;

[[v44-10-11]]

^<<v44-10-11,11>>^ então, viu o céu aberto e descendo um objeto como se fosse um grande lençol, o qual era baixado à terra pelas quatro pontas,

[[v44-10-12]]

^<<v44-10-12,12>>^ contendo toda sorte de quadrúpedes, répteis da terra e aves do céu.

[[v44-10-13]]

^<<v44-10-13,13>>^ E ouviu-se uma voz que se dirigia a ele: Levanta-te, Pedro! Mata e come.

[[v44-10-14]]

^<<v44-10-14,14>>^ Mas Pedro replicou: De modo nenhum, Senhor! Porque jamais comi coisa alguma comum e imunda.

[[v44-10-15]]

^<<v44-10-15,15>>^ Segunda vez, a voz lhe falou: Ao que Deus purificou não consideres comum.

[[v44-10-16]]

^<<v44-10-16,16>>^ Sucedeu isto por três vezes, e, logo, aquele objeto foi recolhido ao céu.

[[v44-10-17]]

^<<v44-10-17,17>>^ Enquanto Pedro estava perplexo sobre qual seria o significado da visão, eis que os homens enviados da parte de Cornélio, tendo perguntado pela casa de Simão, pararam junto à porta;

[[v44-10-18]]

^<<v44-10-18,18>>^ e, chamando, indagavam se estava ali hospedado Simão, por sobrenome Pedro.

[[v44-10-19]]

^<<v44-10-19,19>>^ Enquanto meditava Pedro acerca da visão, disse-lhe o Espírito: Estão aí dois homens que te procuram;

[[v44-10-20]]

^<<v44-10-20,20>>^ levanta-te, pois, desce e vai com eles, nada duvidando; porque eu os enviei.

[[v44-10-21]]

^<<v44-10-21,21>>^ E, descendo Pedro para junto dos homens, disse: Aqui me tendes; sou eu a quem buscais? A que viestes?

[[v44-10-22]]

^<<v44-10-22,22>>^ Então, disseram: O centurião Cornélio, homem reto e temente a Deus e tendo bom testemunho de toda a nação judaica, foi instruído por um santo anjo para chamar-te a sua casa e ouvir as tuas palavras.

[[v44-10-23]]

^<<v44-10-23,23>>^ Pedro, pois, convidando-os a entrar, hospedou-os. No dia seguinte, levantou-se e partiu com eles; também alguns irmãos dos que habitavam em Jope foram em sua companhia.

[[v44-10-24]]

^<<v44-10-24,24>>^ No dia imediato, entrou em Cesareia. Cornélio estava esperando por eles, tendo reunido seus parentes e amigos íntimos.

[[v44-10-25]]

^<<v44-10-25,25>>^ Aconteceu que, indo Pedro a entrar, lhe saiu Cornélio ao encontro e, prostrando-se-lhe aos pés, o adorou.

[[v44-10-26]]

^<<v44-10-26,26>>^ Mas Pedro o levantou, dizendo: Ergue-te, que eu também sou homem.

[[v44-10-27]]

^<<v44-10-27,27>>^ Falando com ele, entrou, encontrando muitos reunidos ali,

[[v44-10-28]]

^<<v44-10-28,28>>^ a quem se dirigiu, dizendo: Vós bem sabeis que é proibido a um judeu ajuntar-se ou mesmo aproximar-se a alguém de outra raça; mas Deus me demonstrou que a nenhum homem considerasse comum ou imundo;

[[v44-10-29]]

^<<v44-10-29,29>>^ por isso, uma vez chamado, vim sem vacilar. Pergunto, pois: por que razão me mandastes chamar?

[[v44-10-30]]

^<<v44-10-30,30>>^ Respondeu-lhe Cornélio: Faz, hoje, quatro dias que, por volta desta hora, estava eu observando em minha casa a hora nona de oração, e eis que se apresentou diante de mim um varão de vestes resplandecentes

[[v44-10-31]]

^<<v44-10-31,31>>^ e disse: Cornélio, a tua oração foi ouvida, e as tuas esmolas, lembradas na presença de Deus.

[[v44-10-32]]

^<<v44-10-32,32>>^ Manda, pois, alguém a Jope a chamar Simão, por sobrenome Pedro; acha-se este hospedado em casa de Simão, curtidor, à beira-mar.

[[v44-10-33]]

^<<v44-10-33,33>>^ Portanto, sem demora, mandei chamar-te, e fizeste bem em vir. Agora, pois, estamos todos aqui, na presença de Deus, prontos para ouvir tudo o que te foi ordenado da parte do Senhor.

[[v44-10-34]]

^<<v44-10-34,34>>^ Então, falou Pedro, dizendo: Reconheço, por verdade, que Deus não faz acepção de pessoas;

[[v44-10-35]]

^<<v44-10-35,35>>^ pelo contrário, em qualquer nação, aquele que o teme e faz o que é justo lhe é aceitável.

[[v44-10-36]]

^<<v44-10-36,36>>^ Esta é a palavra que Deus enviou aos filhos de Israel, anunciando-lhes o evangelho da paz, por meio de Jesus Cristo. Este é o Senhor de todos.

[[v44-10-37]]

^<<v44-10-37,37>>^ Vós conheceis a palavra que se divulgou por toda a Judeia, tendo começado desde a Galileia, depois do batismo que João pregou,

[[v44-10-38]]

^<<v44-10-38,38>>^ como Deus ungiu a Jesus de Nazaré com o Espírito Santo e com poder, o qual andou por toda parte, fazendo o bem e curando a todos os oprimidos do diabo, porque Deus era com ele;

[[v44-10-39]]

^<<v44-10-39,39>>^ e nós somos testemunhas de tudo o que ele fez na terra dos judeus e em Jerusalém; ao qual também tiraram a vida, pendurando-o no madeiro.

[[v44-10-40]]

^<<v44-10-40,40>>^ A este ressuscitou Deus no terceiro dia e concedeu que fosse manifesto,

[[v44-10-41]]

^<<v44-10-41,41>>^ não a todo o povo, mas às testemunhas que foram anteriormente escolhidas por Deus, isto é, a nós que comemos e bebemos com ele, depois que ressurgiu dentre os mortos;

[[v44-10-42]]

^<<v44-10-42,42>>^ e nos mandou pregar ao povo e testificar que ele é quem foi constituído por Deus Juiz de vivos e de mortos.

[[v44-10-43]]

^<<v44-10-43,43>>^ Dele todos os profetas dão testemunho de que, por meio de seu nome, todo aquele que nele crê recebe remissão de pecados.

[[v44-10-44]]

^<<v44-10-44,44>>^ Ainda Pedro falava estas coisas quando caiu o Espírito Santo sobre todos os que ouviam a palavra.

[[v44-10-45]]

^<<v44-10-45,45>>^ E os fiéis que eram da circuncisão, que vieram com Pedro, admiraram-se, porque também sobre os gentios foi derramado o dom do Espírito Santo;

[[v44-10-46]]

^<<v44-10-46,46>>^ pois os ouviam falando em línguas e engrandecendo a Deus. Então, perguntou Pedro:

[[v44-10-47]]

^<<v44-10-47,47>>^ Porventura, pode alguém recusar a água, para que não sejam batizados estes que, assim como nós, receberam o Espírito Santo?

[[v44-10-48]]

^<<v44-10-48,48>>^ E ordenou que fossem batizados em nome de Jesus Cristo. Então, lhe pediram que permanecesse com eles por alguns dias.

'''

xref:044-atos/044-atos-009.adoc#v44-9-0[&#60; Capítulo Anterior] | <<v44-10-0,Topo>> | xref:044-atos/044-atos-011.adoc#v44-11-0[Próximo Capítulo &#62;]