include::./index.adoc[]

[[v44-14-0]]
=== Atos, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-14-1]]

^<<v44-14-1,1>>^ Em Icônio, Paulo e Barnabé entraram juntos na sinagoga judaica e falaram de tal modo, que veio a crer grande multidão, tanto de judeus como de gregos.

[[v44-14-2]]

^<<v44-14-2,2>>^ Mas os judeus incrédulos incitaram e irritaram os ânimos dos gentios contra os irmãos.

[[v44-14-3]]

^<<v44-14-3,3>>^ Entretanto, demoraram-se ali muito tempo, falando ousadamente no Senhor, o qual confirmava a palavra da sua graça, concedendo que, por mão deles, se fizessem sinais e prodígios.

[[v44-14-4]]

^<<v44-14-4,4>>^ Mas dividiu-se o povo da cidade: uns eram pelos judeus; outros, pelos apóstolos.

[[v44-14-5]]

^<<v44-14-5,5>>^ E, como surgisse um tumulto dos gentios e judeus, associados com as suas autoridades, para os ultrajar e apedrejar,

[[v44-14-6]]

^<<v44-14-6,6>>^ sabendo-o eles, fugiram para Listra e Derbe, cidades da Licaônia e circunvizinhança,

[[v44-14-7]]

^<<v44-14-7,7>>^ onde anunciaram o evangelho.

[[v44-14-8]]

^<<v44-14-8,8>>^ Em Listra, costumava estar assentado certo homem aleijado, paralítico desde o seu nascimento, o qual jamais pudera andar.

[[v44-14-9]]

^<<v44-14-9,9>>^ Esse homem ouviu falar Paulo, que, fixando nele os olhos e vendo que possuía fé para ser curado,

[[v44-14-10]]

^<<v44-14-10,10>>^ disse-lhe em alta voz: Apruma-te direito sobre os pés! Ele saltou e andava.

[[v44-14-11]]

^<<v44-14-11,11>>^ Quando as multidões viram o que Paulo fizera, gritaram em língua licaônica, dizendo: Os deuses, em forma de homens, baixaram até nós.

[[v44-14-12]]

^<<v44-14-12,12>>^ A Barnabé chamavam Júpiter, e a Paulo, Mercúrio, porque era este o principal portador da palavra.

[[v44-14-13]]

^<<v44-14-13,13>>^ O sacerdote de Júpiter, cujo templo estava em frente da cidade, trazendo para junto das portas touros e grinaldas, queria sacrificar juntamente com as multidões.

[[v44-14-14]]

^<<v44-14-14,14>>^ Porém, ouvindo isto, os apóstolos Barnabé e Paulo, rasgando as suas vestes, saltaram para o meio da multidão, clamando:

[[v44-14-15]]

^<<v44-14-15,15>>^ Senhores, por que fazeis isto? Nós também somos homens como vós, sujeitos aos mesmos sentimentos, e vos anunciamos o evangelho para que destas coisas vãs vos convertais ao Deus vivo, que fez o céu, a terra, o mar e tudo o que há neles;

[[v44-14-16]]

^<<v44-14-16,16>>^ o qual, nas gerações passadas, permitiu que todos os povos andassem nos seus próprios caminhos;

[[v44-14-17]]

^<<v44-14-17,17>>^ contudo, não se deixou ficar sem testemunho de si mesmo, fazendo o bem, dando-vos do céu chuvas e estações frutíferas, enchendo o vosso coração de fartura e de alegria.

[[v44-14-18]]

^<<v44-14-18,18>>^ Dizendo isto, foi ainda com dificuldade que impediram as multidões de lhes oferecerem sacrifícios.

[[v44-14-19]]

^<<v44-14-19,19>>^ Sobrevieram, porém, judeus de Antioquia e Icônio e, instigando as multidões e apedrejando a Paulo, arrastaram-no para fora da cidade, dando-o por morto.

[[v44-14-20]]

^<<v44-14-20,20>>^ Rodeando-o, porém, os discípulos, levantou-se e entrou na cidade. No dia seguinte, partiu, com Barnabé, para Derbe.

[[v44-14-21]]

^<<v44-14-21,21>>^ E, tendo anunciado o evangelho naquela cidade e feito muitos discípulos, voltaram para Listra, e Icônio, e Antioquia,

[[v44-14-22]]

^<<v44-14-22,22>>^ fortalecendo a alma dos discípulos, exortando-os a permanecer firmes na fé; e mostrando que, através de muitas tribulações, nos importa entrar no reino de Deus.

[[v44-14-23]]

^<<v44-14-23,23>>^ E, promovendo-lhes, em cada igreja, a eleição de presbíteros, depois de orar com jejuns, os encomendaram ao Senhor em quem haviam crido.

[[v44-14-24]]

^<<v44-14-24,24>>^ Atravessando a Pisídia, dirigiram-se a Panfília.

[[v44-14-25]]

^<<v44-14-25,25>>^ E, tendo anunciado a palavra em Perge, desceram a Atália

[[v44-14-26]]

^<<v44-14-26,26>>^ e dali navegaram para Antioquia, onde tinham sido recomendados à graça de Deus para a obra que haviam já cumprido.

[[v44-14-27]]

^<<v44-14-27,27>>^ Ali chegados, reunida a igreja, relataram quantas coisas fizera Deus com eles e como abrira aos gentios a porta da fé.

[[v44-14-28]]

^<<v44-14-28,28>>^ E permaneceram não pouco tempo com os discípulos.

'''

xref:044-atos/044-atos-013.adoc#v44-13-0[&#60; Capítulo Anterior] | <<v44-14-0,Topo>> | xref:044-atos/044-atos-015.adoc#v44-15-0[Próximo Capítulo &#62;]