include::./index.adoc[]

[[v44-9-0]]
=== Atos, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-9-1]]

^<<v44-9-1,1>>^ Saulo, respirando ainda ameaças e morte contra os discípulos do Senhor, dirigiu-se ao sumo sacerdote

[[v44-9-2]]

^<<v44-9-2,2>>^ e lhe pediu cartas para as sinagogas de Damasco, a fim de que, caso achasse alguns que eram do Caminho, assim homens como mulheres, os levasse presos para Jerusalém.

[[v44-9-3]]

^<<v44-9-3,3>>^ Seguindo ele estrada fora, ao aproximar-se de Damasco, subitamente uma luz do céu brilhou ao seu redor,

[[v44-9-4]]

^<<v44-9-4,4>>^ e, caindo por terra, ouviu uma voz que lhe dizia: Saulo, Saulo, por que me persegues?

[[v44-9-5]]

^<<v44-9-5,5>>^ Ele perguntou: Quem és tu, Senhor? E a resposta foi: Eu sou Jesus, a quem tu persegues;

[[v44-9-6]]

^<<v44-9-6,6>>^ mas levanta-te e entra na cidade, onde te dirão o que te convém fazer.

[[v44-9-7]]

^<<v44-9-7,7>>^ Os seus companheiros de viagem pararam emudecidos, ouvindo a voz, não vendo, contudo, ninguém.

[[v44-9-8]]

^<<v44-9-8,8>>^ Então, se levantou Saulo da terra e, abrindo os olhos, nada podia ver. E, guiando-o pela mão, levaram-no para Damasco.

[[v44-9-9]]

^<<v44-9-9,9>>^ Esteve três dias sem ver, durante os quais nada comeu, nem bebeu.

[[v44-9-10]]

^<<v44-9-10,10>>^ Ora, havia em Damasco um discípulo chamado Ananias. Disse-lhe o Senhor numa visão: Ananias!  Ao que respondeu: Eis-me aqui, Senhor!

[[v44-9-11]]

^<<v44-9-11,11>>^ Então, o Senhor lhe ordenou: Dispõe-te, e vai à rua que se chama Direita, e, na casa de Judas, procura por Saulo, apelidado de Tarso; pois ele está orando

[[v44-9-12]]

^<<v44-9-12,12>>^ e viu entrar um homem, chamado Ananias, e impor-lhe as mãos, para que recuperasse a vista.

[[v44-9-13]]

^<<v44-9-13,13>>^ Ananias, porém, respondeu: Senhor, de muitos tenho ouvido a respeito desse homem, quantos males tem feito aos teus santos em Jerusalém;

[[v44-9-14]]

^<<v44-9-14,14>>^ e para aqui trouxe autorização dos principais sacerdotes para prender a todos os que invocam o teu nome.

[[v44-9-15]]

^<<v44-9-15,15>>^ Mas o Senhor lhe disse: Vai, porque este é para mim um instrumento escolhido para levar o meu nome perante os gentios e reis, bem como perante os filhos de Israel;

[[v44-9-16]]

^<<v44-9-16,16>>^ pois eu lhe mostrarei quanto lhe importa sofrer pelo meu nome.

[[v44-9-17]]

^<<v44-9-17,17>>^ Então, Ananias foi e, entrando na casa, impôs sobre ele as mãos, dizendo: Saulo, irmão, o Senhor me enviou, a saber, o próprio Jesus que te apareceu no caminho por onde vinhas, para que recuperes a vista e fiques cheio do Espírito Santo.

[[v44-9-18]]

^<<v44-9-18,18>>^ Imediatamente, lhe caíram dos olhos como que umas escamas, e tornou a ver. A seguir, levantou-se e foi batizado.

[[v44-9-19]]

^<<v44-9-19,19>>^ E, depois de ter-se alimentado, sentiu-se fortalecido. Então, permaneceu em Damasco alguns dias com os discípulos.

[[v44-9-20]]

^<<v44-9-20,20>>^ E logo pregava, nas sinagogas, a Jesus, afirmando que este é o Filho de Deus.

[[v44-9-21]]

^<<v44-9-21,21>>^ Ora, todos os que o ouviam estavam atônitos e diziam: Não é este o que exterminava em Jerusalém os que invocavam o nome de Jesus e para aqui veio precisamente com o fim de os levar amarrados aos principais sacerdotes?

[[v44-9-22]]

^<<v44-9-22,22>>^ Saulo, porém, mais e mais se fortalecia e confundia os judeus que moravam em Damasco, demonstrando que Jesus é o Cristo.

[[v44-9-23]]

^<<v44-9-23,23>>^ Decorridos muitos dias, os judeus deliberaram entre si tirar-lhe a vida;

[[v44-9-24]]

^<<v44-9-24,24>>^ porém o plano deles chegou ao conhecimento de Saulo. Dia e noite guardavam também as portas, para o matarem.

[[v44-9-25]]

^<<v44-9-25,25>>^ Mas os seus discípulos tomaram-no de noite e, colocando-o num cesto, desceram-no pela muralha.

[[v44-9-26]]

^<<v44-9-26,26>>^ Tendo chegado a Jerusalém, procurou juntar-se com os discípulos; todos, porém, o temiam, não acreditando que ele fosse discípulo.

[[v44-9-27]]

^<<v44-9-27,27>>^ Mas Barnabé, tomando-o consigo, levou-o aos apóstolos; e contou-lhes como ele vira o Senhor no caminho, e que este lhe falara, e como em Damasco pregara ousadamente em nome de Jesus.

[[v44-9-28]]

^<<v44-9-28,28>>^ Estava com eles em Jerusalém, entrando e saindo, pregando ousadamente em nome do Senhor.

[[v44-9-29]]

^<<v44-9-29,29>>^ Falava e discutia com os helenistas; mas eles procuravam tirar-lhe a vida.

[[v44-9-30]]

^<<v44-9-30,30>>^ Tendo, porém, isto chegado ao conhecimento dos irmãos, levaram-no até Cesareia e dali o enviaram para Tarso.

[[v44-9-31]]

^<<v44-9-31,31>>^ A igreja, na verdade, tinha paz por toda a Judeia, Galileia e Samaria, edificando-se e caminhando no temor do Senhor, e, no conforto do Espírito Santo, crescia em número.

[[v44-9-32]]

^<<v44-9-32,32>>^ Passando Pedro por toda parte, desceu também aos santos que habitavam em Lida.

[[v44-9-33]]

^<<v44-9-33,33>>^ Encontrou ali certo homem, chamado Eneias, que havia oito anos jazia de cama, pois era paralítico.

[[v44-9-34]]

^<<v44-9-34,34>>^ Disse-lhe Pedro: Eneias, Jesus Cristo te cura! Levanta-te e arruma o teu leito. Ele, imediatamente, se levantou.

[[v44-9-35]]

^<<v44-9-35,35>>^ Viram-no todos os habitantes de Lida e Sarona, os quais se converteram ao Senhor.

[[v44-9-36]]

^<<v44-9-36,36>>^ Havia em Jope uma discípula por nome Tabita, nome este que, traduzido, quer dizer Dorcas; era ela notável pelas boas obras e esmolas que fazia.

[[v44-9-37]]

^<<v44-9-37,37>>^ Ora, aconteceu, naqueles dias, que ela adoeceu e veio a morrer; e, depois de a lavarem, puseram-na no cenáculo.

[[v44-9-38]]

^<<v44-9-38,38>>^ Como Lida era perto de Jope, ouvindo os discípulos que Pedro estava ali, enviaram-lhe dois homens que lhe pedissem: Não demores em vir ter conosco.

[[v44-9-39]]

^<<v44-9-39,39>>^ Pedro atendeu e foi com eles. Tendo chegado, conduziram-no para o cenáculo; e todas as viúvas o cercaram, chorando e mostrando-lhe túnicas e vestidos que Dorcas fizera enquanto estava com elas.

[[v44-9-40]]

^<<v44-9-40,40>>^ Mas Pedro, tendo feito sair a todos, pondo-se de joelhos, orou; e, voltando-se para o corpo, disse: Tabita, levanta-te! Ela abriu os olhos e, vendo a Pedro, sentou-se.

[[v44-9-41]]

^<<v44-9-41,41>>^ Ele, dando-lhe a mão, levantou-a; e, chamando os santos, especialmente as viúvas, apresentou-a viva.

[[v44-9-42]]

^<<v44-9-42,42>>^ Isto se tornou conhecido por toda Jope, e muitos creram no Senhor.

[[v44-9-43]]

^<<v44-9-43,43>>^ Pedro ficou em Jope muitos dias, em casa de um curtidor chamado Simão.

'''

xref:044-atos/044-atos-008.adoc#v44-8-0[&#60; Capítulo Anterior] | <<v44-9-0,Topo>> | xref:044-atos/044-atos-010.adoc#v44-10-0[Próximo Capítulo &#62;]