include::./index.adoc[]

[[v44-15-0]]
=== Atos, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-15-1]]

^<<v44-15-1,1>>^ Alguns indivíduos que desceram da Judeia ensinavam aos irmãos: Se não vos circuncidardes segundo o costume de Moisés, não podeis ser salvos.

[[v44-15-2]]

^<<v44-15-2,2>>^ Tendo havido, da parte de Paulo e Barnabé, contenda e não pequena discussão com eles, resolveram que esses dois e alguns outros dentre eles subissem a Jerusalém, aos apóstolos e presbíteros, com respeito a esta questão.

[[v44-15-3]]

^<<v44-15-3,3>>^ Enviados, pois, e até certo ponto acompanhados pela igreja, atravessaram as províncias da Fenícia e Samaria e, narrando a conversão dos gentios, causaram grande alegria a todos os irmãos.

[[v44-15-4]]

^<<v44-15-4,4>>^ Tendo eles chegado a Jerusalém, foram bem-recebidos pela igreja, pelos apóstolos e pelos presbíteros e relataram tudo o que Deus fizera com eles.

[[v44-15-5]]

^<<v44-15-5,5>>^ Insurgiram-se, entretanto, alguns da seita dos fariseus que haviam crido, dizendo: É necessário circuncidá-los e determinar-lhes que observem a lei de Moisés.

[[v44-15-6]]

^<<v44-15-6,6>>^ Então, se reuniram os apóstolos e os presbíteros para examinar a questão.

[[v44-15-7]]

^<<v44-15-7,7>>^ Havendo grande debate, Pedro tomou a palavra e lhes disse: Irmãos, vós sabeis que, desde há muito, Deus me escolheu dentre vós para que, por meu intermédio, ouvissem os gentios a palavra do evangelho e cressem.

[[v44-15-8]]

^<<v44-15-8,8>>^ Ora, Deus, que conhece os corações, lhes deu testemunho, concedendo o Espírito Santo a eles, como também a nós nos concedera.

[[v44-15-9]]

^<<v44-15-9,9>>^ E não estabeleceu distinção alguma entre nós e eles, purificando-lhes pela fé o coração.

[[v44-15-10]]

^<<v44-15-10,10>>^ Agora, pois, por que tentais a Deus, pondo sobre a cerviz dos discípulos um jugo que nem nossos pais puderam suportar, nem nós?

[[v44-15-11]]

^<<v44-15-11,11>>^ Mas cremos que fomos salvos pela graça do Senhor Jesus, como também aqueles o foram.

[[v44-15-12]]

^<<v44-15-12,12>>^ E toda a multidão silenciou, passando a ouvir a Barnabé e a Paulo, que contavam quantos sinais e prodígios Deus fizera por meio deles entre os gentios.

[[v44-15-13]]

^<<v44-15-13,13>>^ Depois que eles terminaram, falou Tiago, dizendo: Irmãos, atentai nas minhas palavras:

[[v44-15-14]]

^<<v44-15-14,14>>^ expôs Simão como Deus, primeiramente, visitou os gentios, a fim de constituir dentre eles um povo para o seu nome.

[[v44-15-15]]

^<<v44-15-15,15>>^ Conferem com isto as palavras dos profetas, como está escrito:

[[v44-15-16]]

^<<v44-15-16,16>>^ Cumpridas estas coisas, voltarei e reedificarei o tabernáculo caído de Davi; e, levantando-o de suas ruínas, restaurá-lo-ei.

[[v44-15-17]]

^<<v44-15-17,17>>^ Para que os demais homens busquem o Senhor, e também todos os gentios sobre os quais tem sido invocado o meu nome,

[[v44-15-18]]

^<<v44-15-18,18>>^ diz o Senhor, que faz estas coisas conhecidas desde séculos.

[[v44-15-19]]

^<<v44-15-19,19>>^ Pelo que, julgo eu, não devemos perturbar aqueles que, dentre os gentios, se convertem a Deus,

[[v44-15-20]]

^<<v44-15-20,20>>^ mas escrever-lhes que se abstenham das contaminações dos ídolos, bem como das relações sexuais ilícitas, da carne de animais sufocados e do sangue.

[[v44-15-21]]

^<<v44-15-21,21>>^ Porque Moisés tem, em cada cidade, desde tempos antigos, os que o pregam nas sinagogas, onde é lido todos os sábados.

[[v44-15-22]]

^<<v44-15-22,22>>^ Então, pareceu bem aos apóstolos e aos presbíteros, com toda a igreja, tendo elegido homens dentre eles, enviá-los, juntamente com Paulo e Barnabé, a Antioquia: foram Judas, chamado Barsabás, e Silas, homens notáveis entre os irmãos,

[[v44-15-23]]

^<<v44-15-23,23>>^ escrevendo, por mão deles: Os irmãos, tanto os apóstolos como os presbíteros, aos irmãos de entre os gentios em Antioquia, Síria e Cilícia, saudações.

[[v44-15-24]]

^<<v44-15-24,24>>^ Visto sabermos que alguns [que saíram] de entre nós, sem nenhuma autorização, vos têm perturbado com palavras, transtornando a vossa alma,

[[v44-15-25]]

^<<v44-15-25,25>>^ pareceu-nos bem, chegados a pleno acordo, eleger alguns homens e enviá-los a vós outros com os nossos amados Barnabé e Paulo,

[[v44-15-26]]

^<<v44-15-26,26>>^ homens que têm exposto a vida pelo nome de nosso Senhor Jesus Cristo.

[[v44-15-27]]

^<<v44-15-27,27>>^ Enviamos, portanto, Judas e Silas, os quais pessoalmente vos dirão também estas coisas.

[[v44-15-28]]

^<<v44-15-28,28>>^ Pois pareceu bem ao Espírito Santo e a nós não vos impor maior encargo além destas coisas essenciais:

[[v44-15-29]]

^<<v44-15-29,29>>^ que vos abstenhais das coisas sacrificadas a ídolos, bem como do sangue, da carne de animais sufocados e das relações sexuais ilícitas; destas coisas fareis bem se vos guardardes. Saúde.

[[v44-15-30]]

^<<v44-15-30,30>>^ Os que foram enviados desceram logo para Antioquia e, tendo reunido a comunidade, entregaram a epístola.

[[v44-15-31]]

^<<v44-15-31,31>>^ Quando a leram, sobremaneira se alegraram pelo conforto recebido.

[[v44-15-32]]

^<<v44-15-32,32>>^ Judas e Silas, que eram também profetas, consolaram os irmãos com muitos conselhos e os fortaleceram.

[[v44-15-33]]

^<<v44-15-33,33>>^ Tendo-se demorado ali por algum tempo, os irmãos os deixaram voltar em paz aos que os enviaram.

[[v44-15-34]]

^<<v44-15-34,34>>^ [Mas pareceu bem a Silas permanecer ali.]

[[v44-15-35]]

^<<v44-15-35,35>>^ Paulo e Barnabé demoraram-se em Antioquia, ensinando e pregando, com muitos outros, a palavra do Senhor.

[[v44-15-36]]

^<<v44-15-36,36>>^ Alguns dias depois, disse Paulo a Barnabé: Voltemos, agora, para visitar os irmãos por todas as cidades nas quais anunciamos a palavra do Senhor, para ver como passam.

[[v44-15-37]]

^<<v44-15-37,37>>^ E Barnabé queria levar também a João, chamado Marcos.

[[v44-15-38]]

^<<v44-15-38,38>>^ Mas Paulo não achava justo levarem aquele que se afastara desde a Panfília, não os acompanhando no trabalho.

[[v44-15-39]]

^<<v44-15-39,39>>^ Houve entre eles tal desavença, que vieram a separar-se. Então, Barnabé, levando consigo a Marcos, navegou para Chipre.

[[v44-15-40]]

^<<v44-15-40,40>>^ Mas Paulo, tendo escolhido a Silas, partiu encomendado pelos irmãos à graça do Senhor.

[[v44-15-41]]

^<<v44-15-41,41>>^ E passou pela Síria e Cilícia, confirmando as igrejas.

'''

xref:044-atos/044-atos-014.adoc#v44-14-0[&#60; Capítulo Anterior] | <<v44-15-0,Topo>> | xref:044-atos/044-atos-016.adoc#v44-16-0[Próximo Capítulo &#62;]