include::./index.adoc[]

[[v44-24-0]]
=== Atos, 24
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-24-1]]

^<<v44-24-1,1>>^ Cinco dias depois, desceu o sumo sacerdote, Ananias, com alguns anciãos e com certo orador, chamado Tértulo, os quais apresentaram ao governador libelo contra Paulo.

[[v44-24-2]]

^<<v44-24-2,2>>^ Sendo este chamado, passou Tértulo a acusá-lo, dizendo: Excelentíssimo Félix, tendo nós, por teu intermédio, gozado de paz perene, e, também por teu providente cuidado, se terem feito notáveis reformas em benefício deste povo,

[[v44-24-3]]

^<<v44-24-3,3>>^ sempre e por toda parte, isto reconhecemos com toda a gratidão.

[[v44-24-4]]

^<<v44-24-4,4>>^ Entretanto, para não te deter por longo tempo, rogo-te que, de conformidade com a tua clemência, nos atendas por um pouco.

[[v44-24-5]]

^<<v44-24-5,5>>^ Porque, tendo nós verificado que este homem é uma peste e promove sedições entre os judeus esparsos por todo o mundo, sendo também o principal agitador da seita dos nazarenos,

[[v44-24-6]]

^<<v44-24-6,6>>^ o qual também tentou profanar o templo, nós o prendemos [com o intuito de julgá-lo segundo a nossa lei.

[[v44-24-7]]

^<<v44-24-7,7>>^ Mas, sobrevindo o comandante Lísias, o arrebatou das nossas mãos com grande violência,

[[v44-24-8]]

^<<v44-24-8,8>>^ ordenando que os seus acusadores viessem à tua presença]. Tu mesmo, examinando-o, poderás tomar conhecimento de todas as coisas de que nós o acusamos.

[[v44-24-9]]

^<<v44-24-9,9>>^ Os judeus também concordaram na acusação, afirmando que estas coisas eram assim.

[[v44-24-10]]

^<<v44-24-10,10>>^ Paulo, tendo-lhe o governador feito sinal que falasse, respondeu: Sabendo que há muitos anos és juiz desta nação, sinto-me à vontade para me defender,

[[v44-24-11]]

^<<v44-24-11,11>>^ visto poderes verificar que não há mais de doze dias desde que subi a Jerusalém para adorar;

[[v44-24-12]]

^<<v44-24-12,12>>^ e que não me acharam no templo discutindo com alguém, nem tampouco amotinando o povo, fosse nas sinagogas ou na cidade;

[[v44-24-13]]

^<<v44-24-13,13>>^ nem te podem provar as acusações que, agora, fazem contra mim.

[[v44-24-14]]

^<<v44-24-14,14>>^ Porém confesso-te que, segundo o Caminho, a que chamam seita, assim eu sirvo ao Deus de nossos pais, acreditando em todas as coisas que estejam de acordo com a lei e nos escritos dos profetas,

[[v44-24-15]]

^<<v44-24-15,15>>^ tendo esperança em Deus, como também estes a têm, de que haverá ressurreição, tanto de justos como de injustos.

[[v44-24-16]]

^<<v44-24-16,16>>^ Por isso, também me esforço por ter sempre consciência pura diante de Deus e dos homens.

[[v44-24-17]]

^<<v44-24-17,17>>^ Depois de anos, vim trazer esmolas à minha nação e também fazer oferendas,

[[v44-24-18]]

^<<v44-24-18,18>>^ e foi nesta prática que alguns judeus da Ásia me encontraram já purificado no templo, sem ajuntamento e sem tumulto,

[[v44-24-19]]

^<<v44-24-19,19>>^ os quais deviam comparecer diante de ti e acusar, se tivessem alguma coisa contra mim.

[[v44-24-20]]

^<<v44-24-20,20>>^ Ou estes mesmos digam que iniquidade acharam em mim, por ocasião do meu comparecimento perante o Sinédrio,

[[v44-24-21]]

^<<v44-24-21,21>>^ salvo estas palavras que clamei, estando entre eles: hoje, sou eu julgado por vós acerca da ressurreição dos mortos.

[[v44-24-22]]

^<<v44-24-22,22>>^ Então, Félix, conhecendo mais acuradamente as coisas com respeito ao Caminho, adiou a causa, dizendo: Quando descer o comandante Lísias, tomarei inteiro conhecimento do vosso caso.

[[v44-24-23]]

^<<v44-24-23,23>>^ E mandou ao centurião que conservasse a Paulo detido, tratando-o com indulgência e não impedindo que os seus próprios o servissem.

[[v44-24-24]]

^<<v44-24-24,24>>^ Passados alguns dias, vindo Félix com Drusila, sua mulher, que era judia, mandou chamar Paulo e passou a ouvi-lo a respeito da fé em Cristo Jesus.

[[v44-24-25]]

^<<v44-24-25,25>>^ Dissertando ele acerca da justiça, do domínio próprio e do Juízo vindouro, ficou Félix amedrontado e disse: Por agora, podes retirar-te, e, quando eu tiver vagar, chamar-te-ei;

[[v44-24-26]]

^<<v44-24-26,26>>^ esperando também, ao mesmo tempo, que Paulo lhe desse dinheiro; pelo que, chamando-o mais frequentemente, conversava com ele.

[[v44-24-27]]

^<<v44-24-27,27>>^ Dois anos mais tarde, Félix teve por sucessor Pórcio Festo; e, querendo Félix assegurar o apoio dos judeus, manteve Paulo encarcerado.

'''

xref:044-atos/044-atos-023.adoc#v44-23-0[&#60; Capítulo Anterior] | <<v44-24-0,Topo>> | xref:044-atos/044-atos-025.adoc#v44-25-0[Próximo Capítulo &#62;]