include::./index.adoc[]

[[v44-28-0]]
=== Atos, 28
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-28-1]]

^<<v44-28-1,1>>^ Uma vez em terra, verificamos que a ilha se chamava Malta.

[[v44-28-2]]

^<<v44-28-2,2>>^ Os bárbaros trataram-nos com singular humanidade, porque, acendendo uma fogueira, acolheram-nos a todos por causa da chuva que caía e por causa do frio.

[[v44-28-3]]

^<<v44-28-3,3>>^ Tendo Paulo ajuntado e atirado à fogueira um feixe de gravetos, uma víbora, fugindo do calor, prendeu-se-lhe à mão.

[[v44-28-4]]

^<<v44-28-4,4>>^ Quando os bárbaros viram a víbora pendente da mão dele, disseram uns aos outros: Certamente, este homem é assassino, porque, salvo do mar, a Justiça não o deixa viver.

[[v44-28-5]]

^<<v44-28-5,5>>^ Porém ele, sacudindo o réptil no fogo, não sofreu mal nenhum;

[[v44-28-6]]

^<<v44-28-6,6>>^ mas eles esperavam que ele viesse a inchar ou a cair morto de repente. Mas, depois de muito esperar, vendo que nenhum mal lhe sucedia, mudando de parecer, diziam ser ele um deus.

[[v44-28-7]]

^<<v44-28-7,7>>^ Perto daquele lugar, havia um sítio pertencente ao homem principal da ilha, chamado Públio, o qual nos recebeu e hospedou benignamente por três dias.

[[v44-28-8]]

^<<v44-28-8,8>>^ Aconteceu achar-se enfermo de disenteria, ardendo em febre, o pai de Públio. Paulo foi visitá-lo, e, orando, impôs-lhe as mãos, e o curou.

[[v44-28-9]]

^<<v44-28-9,9>>^ À vista deste acontecimento, os demais enfermos da ilha vieram e foram curados,

[[v44-28-10]]

^<<v44-28-10,10>>^ os quais nos distinguiram com muitas honrarias; e, tendo nós de prosseguir viagem, nos puseram a bordo tudo o que era necessário.

[[v44-28-11]]

^<<v44-28-11,11>>^ Ao cabo de três meses, embarcamos num navio alexandrino, que invernara na ilha e tinha por emblema Dióscuros.

[[v44-28-12]]

^<<v44-28-12,12>>^ Tocando em Siracusa, ficamos ali três dias,

[[v44-28-13]]

^<<v44-28-13,13>>^ donde, bordejando, chegamos a Régio. No dia seguinte, tendo soprado vento sul, em dois dias, chegamos a Putéoli,

[[v44-28-14]]

^<<v44-28-14,14>>^ onde achamos alguns irmãos que nos rogaram ficássemos com eles sete dias; e foi assim que nos dirigimos a Roma.

[[v44-28-15]]

^<<v44-28-15,15>>^ Tendo ali os irmãos ouvido notícias nossas, vieram ao nosso encontro até à Praça de Ápio e às Três Vendas. Vendo-os Paulo e dando, por isso, graças a Deus, sentiu-se mais animado.

[[v44-28-16]]

^<<v44-28-16,16>>^ Uma vez em Roma, foi permitido a Paulo morar por sua conta, tendo em sua companhia o soldado que o guardava.

[[v44-28-17]]

^<<v44-28-17,17>>^ Três dias depois, ele convocou os principais dos judeus e, quando se reuniram, lhes disse: Varões irmãos, nada havendo feito contra o povo ou contra os costumes paternos, contudo, vim preso desde Jerusalém, entregue nas mãos dos romanos;

[[v44-28-18]]

^<<v44-28-18,18>>^ os quais, havendo-me interrogado, quiseram soltar-me sob a preliminar de não haver em mim nenhum crime passível de morte.

[[v44-28-19]]

^<<v44-28-19,19>>^ Diante da oposição dos judeus, senti-me compelido a apelar para César, não tendo eu, porém, nada de que acusar minha nação.

[[v44-28-20]]

^<<v44-28-20,20>>^ Foi por isto que vos chamei para vos ver e falar; porque é pela esperança de Israel que estou preso com esta cadeia.

[[v44-28-21]]

^<<v44-28-21,21>>^ Então, eles lhe disseram: Nós não recebemos da Judeia nenhuma carta que te dissesse respeito; também não veio qualquer dos irmãos que nos anunciasse ou dissesse de ti mal algum.

[[v44-28-22]]

^<<v44-28-22,22>>^ Contudo, gostaríamos de ouvir o que pensas; porque, na verdade, é corrente a respeito desta seita que, por toda parte, é ela impugnada.

[[v44-28-23]]

^<<v44-28-23,23>>^ Havendo-lhe eles marcado um dia, vieram em grande número ao encontro de Paulo na sua própria residência. Então, desde a manhã até à tarde, lhes fez uma exposição em testemunho do reino de Deus, procurando persuadi-los a respeito de Jesus, tanto pela lei de Moisés como pelos profetas.

[[v44-28-24]]

^<<v44-28-24,24>>^ Houve alguns que ficaram persuadidos pelo que ele dizia; outros, porém, continuaram incrédulos.

[[v44-28-25]]

^<<v44-28-25,25>>^ E, havendo discordância entre eles, despediram-se, dizendo Paulo estas palavras: Bem falou o Espírito Santo a vossos pais, por intermédio do profeta Isaías, quando disse:

[[v44-28-26]]

^<<v44-28-26,26>>^ Vai a este povo e dize-lhe: De ouvido, ouvireis e não entendereis; vendo, vereis e não percebereis.

[[v44-28-27]]

^<<v44-28-27,27>>^ Porquanto o coração deste povo se tornou endurecido; com os ouvidos ouviram tardiamente e fecharam os olhos, para que jamais vejam com os olhos, nem ouçam com os ouvidos, para que não entendam com o coração, e se convertam, e por mim sejam curados.

[[v44-28-28]]

^<<v44-28-28,28>>^ Tomai, pois, conhecimento de que esta salvação de Deus foi enviada aos gentios. E eles a ouvirão.

[[v44-28-29]]

^<<v44-28-29,29>>^ [Ditas estas palavras, partiram os judeus, tendo entre si grande contenda.]

[[v44-28-30]]

^<<v44-28-30,30>>^ Por dois anos, permaneceu Paulo na sua própria casa, que alugara, onde recebia todos que o procuravam,

[[v44-28-31]]

^<<v44-28-31,31>>^ pregando o reino de Deus, e, com toda a intrepidez, sem impedimento algum, ensinava as coisas referentes ao Senhor Jesus Cristo.

'''

xref:044-atos/044-atos-027.adoc#v44-27-0[&#60; Capítulo Anterior] | <<v44-28-0,Topo>> | xref:045-romanos/045-romanos-001.adoc#v45-1-0[Próximo Capítulo &#62;]