include::./index.adoc[]

[[v44-8-0]]
=== Atos, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-8-1]]

^<<v44-8-1,1>>^ E Saulo consentia na sua morte. Naquele dia, levantou-se grande perseguição contra a igreja em Jerusalém; e todos, exceto os apóstolos, foram dispersos pelas regiões da Judeia e Samaria.

[[v44-8-2]]

^<<v44-8-2,2>>^ Alguns homens piedosos sepultaram Estêvão e fizeram grande pranto sobre ele.

[[v44-8-3]]

^<<v44-8-3,3>>^ Saulo, porém, assolava a igreja, entrando pelas casas; e, arrastando homens e mulheres, encerrava-os no cárcere.

[[v44-8-4]]

^<<v44-8-4,4>>^ Entrementes, os que foram dispersos iam por toda parte pregando a palavra.

[[v44-8-5]]

^<<v44-8-5,5>>^ Filipe, descendo à cidade de Samaria, anunciava-lhes a Cristo.

[[v44-8-6]]

^<<v44-8-6,6>>^ As multidões atendiam, unânimes, às coisas que Filipe dizia, ouvindo-as e vendo os sinais que ele operava.

[[v44-8-7]]

^<<v44-8-7,7>>^ Pois os espíritos imundos de muitos possessos saíam gritando em alta voz; e muitos paralíticos e coxos foram curados.

[[v44-8-8]]

^<<v44-8-8,8>>^ E houve grande alegria naquela cidade.

[[v44-8-9]]

^<<v44-8-9,9>>^ Ora, havia certo homem, chamado Simão, que ali praticava a mágica, iludindo o povo de Samaria, insinuando ser ele grande vulto;

[[v44-8-10]]

^<<v44-8-10,10>>^ ao qual todos davam ouvidos, do menor ao maior, dizendo: Este homem é o poder de Deus, chamado o Grande Poder.

[[v44-8-11]]

^<<v44-8-11,11>>^ Aderiam a ele porque havia muito os iludira com mágicas.

[[v44-8-12]]

^<<v44-8-12,12>>^ Quando, porém, deram crédito a Filipe, que os evangelizava a respeito do reino de Deus e do nome de Jesus Cristo, iam sendo batizados, assim homens como mulheres.

[[v44-8-13]]

^<<v44-8-13,13>>^ O próprio Simão abraçou a fé; e, tendo sido batizado, acompanhava a Filipe de perto, observando extasiado os sinais e grandes milagres praticados.

[[v44-8-14]]

^<<v44-8-14,14>>^ Ouvindo os apóstolos, que estavam em Jerusalém, que Samaria recebera a palavra de Deus, enviaram-lhe Pedro e João;

[[v44-8-15]]

^<<v44-8-15,15>>^ os quais, descendo para lá, oraram por eles para que recebessem o Espírito Santo;

[[v44-8-16]]

^<<v44-8-16,16>>^ porquanto não havia ainda descido sobre nenhum deles, mas somente haviam sido batizados em o nome do Senhor Jesus.

[[v44-8-17]]

^<<v44-8-17,17>>^ Então, lhes impunham as mãos, e recebiam estes o Espírito Santo.

[[v44-8-18]]

^<<v44-8-18,18>>^ Vendo, porém, Simão que, pelo fato de imporem os apóstolos as mãos, era concedido o Espírito [Santo], ofereceu-lhes dinheiro,

[[v44-8-19]]

^<<v44-8-19,19>>^ propondo: Concedei-me também a mim este poder, para que aquele sobre quem eu impuser as mãos receba o Espírito Santo.

[[v44-8-20]]

^<<v44-8-20,20>>^ Pedro, porém, lhe respondeu: O teu dinheiro seja contigo para perdição, pois julgaste adquirir, por meio dele, o dom de Deus.

[[v44-8-21]]

^<<v44-8-21,21>>^ Não tens parte nem sorte neste ministério, porque o teu coração não é reto diante de Deus.

[[v44-8-22]]

^<<v44-8-22,22>>^ Arrepende-te, pois, da tua maldade e roga ao Senhor; talvez te seja perdoado o intento do coração;

[[v44-8-23]]

^<<v44-8-23,23>>^ pois vejo que estás em fel de amargura e laço de iniquidade.

[[v44-8-24]]

^<<v44-8-24,24>>^ Respondendo, porém, Simão lhes pediu: Rogai vós por mim ao Senhor, para que nada do que dissestes sobrevenha a mim.

[[v44-8-25]]

^<<v44-8-25,25>>^ Eles, porém, havendo testificado e falado a palavra do Senhor, voltaram para Jerusalém e evangelizavam muitas aldeias dos samaritanos.

[[v44-8-26]]

^<<v44-8-26,26>>^ Um anjo do Senhor falou a Filipe, dizendo: Dispõe-te e vai para o lado do Sul, no caminho que desce de Jerusalém a Gaza; este se acha deserto. Ele se levantou e foi.

[[v44-8-27]]

^<<v44-8-27,27>>^ Eis que um etíope, eunuco, alto oficial de Candace, rainha dos etíopes, o qual era superintendente de todo o seu tesouro, que viera adorar em Jerusalém,

[[v44-8-28]]

^<<v44-8-28,28>>^ estava de volta e, assentado no seu carro, vinha lendo o profeta Isaías.

[[v44-8-29]]

^<<v44-8-29,29>>^ Então, disse o Espírito a Filipe: Aproxima-te desse carro e acompanha-o.

[[v44-8-30]]

^<<v44-8-30,30>>^ Correndo Filipe, ouviu-o ler o profeta Isaías e perguntou: Compreendes o que vens lendo?

[[v44-8-31]]

^<<v44-8-31,31>>^ Ele respondeu: Como poderei entender, se alguém não me explicar? E convidou Filipe a subir e a sentar-se junto a ele.

[[v44-8-32]]

^<<v44-8-32,32>>^ Ora, a passagem da Escritura que estava lendo era esta: Foi levado como ovelha ao matadouro; e, como um cordeiro mudo perante o seu tosquiador, assim ele não abriu a boca.

[[v44-8-33]]

^<<v44-8-33,33>>^ Na sua humilhação, lhe negaram justiça; quem lhe poderá descrever a geração? Porque da terra a sua vida é tirada.

[[v44-8-34]]

^<<v44-8-34,34>>^ Então, o eunuco disse a Filipe: Peço-te que me expliques a quem se refere o profeta. Fala de si mesmo ou de algum outro?

[[v44-8-35]]

^<<v44-8-35,35>>^ Então, Filipe explicou; e, começando por esta passagem da Escritura, anunciou-lhe a Jesus.

[[v44-8-36]]

^<<v44-8-36,36>>^ Seguindo eles caminho fora, chegando a certo lugar onde havia água, disse o eunuco: Eis aqui água; que impede que seja eu batizado?

[[v44-8-37]]

^<<v44-8-37,37>>^ [Filipe respondeu: É lícito, se crês de todo o coração. E, respondendo ele, disse: Creio que Jesus Cristo é o Filho de Deus.]

[[v44-8-38]]

^<<v44-8-38,38>>^ Então, mandou parar o carro, ambos desceram à água, e Filipe batizou o eunuco.

[[v44-8-39]]

^<<v44-8-39,39>>^ Quando saíram da água, o Espírito do Senhor arrebatou a Filipe, não o vendo mais o eunuco; e este foi seguindo o seu caminho, cheio de júbilo.

[[v44-8-40]]

^<<v44-8-40,40>>^ Mas Filipe veio a achar-se em Azoto; e, passando além, evangelizava todas as cidades até chegar a Cesareia.

'''

xref:044-atos/044-atos-007.adoc#v44-7-0[&#60; Capítulo Anterior] | <<v44-8-0,Topo>> | xref:044-atos/044-atos-009.adoc#v44-9-0[Próximo Capítulo &#62;]