include::./index.adoc[]

[[v44-13-0]]
=== Atos, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-13-1]]

^<<v44-13-1,1>>^ Havia na igreja de Antioquia profetas e mestres: Barnabé, Simeão, por sobrenome Níger, Lúcio de Cirene, Manaém, colaço de Herodes, o tetrarca, e Saulo.

[[v44-13-2]]

^<<v44-13-2,2>>^ E, servindo eles ao Senhor e jejuando, disse o Espírito Santo: Separai-me, agora, Barnabé e Saulo para a obra a que os tenho chamado.

[[v44-13-3]]

^<<v44-13-3,3>>^ Então, jejuando, e orando, e impondo sobre eles as mãos, os despediram.

[[v44-13-4]]

^<<v44-13-4,4>>^ Enviados, pois, pelo Espírito Santo, desceram a Selêucia e dali navegaram para Chipre.

[[v44-13-5]]

^<<v44-13-5,5>>^ Chegados a Salamina, anunciavam a palavra de Deus nas sinagogas judaicas; tinham também João como auxiliar.

[[v44-13-6]]

^<<v44-13-6,6>>^ Havendo atravessado toda a ilha até Pafos, encontraram certo judeu, mágico, falso profeta, de nome Barjesus,

[[v44-13-7]]

^<<v44-13-7,7>>^ o qual estava com o procônsul Sérgio Paulo, que era homem inteligente. Este, tendo chamado Barnabé e Saulo, diligenciava para ouvir a palavra de Deus.

[[v44-13-8]]

^<<v44-13-8,8>>^ Mas opunha-se-lhes Elimas, o mágico (porque assim se interpreta o seu nome), procurando afastar da fé o procônsul.

[[v44-13-9]]

^<<v44-13-9,9>>^ Todavia, Saulo, também chamado Paulo, cheio do Espírito Santo, fixando nele os olhos, disse:

[[v44-13-10]]

^<<v44-13-10,10>>^ Ó filho do diabo, cheio de todo o engano e de toda a malícia, inimigo de toda a justiça, não cessarás de perverter os retos caminhos do Senhor?

[[v44-13-11]]

^<<v44-13-11,11>>^ Pois, agora, eis aí está sobre ti a mão do Senhor, e ficarás cego, não vendo o sol por algum tempo. No mesmo instante, caiu sobre ele névoa e escuridade, e, andando à roda, procurava quem o guiasse pela mão.

[[v44-13-12]]

^<<v44-13-12,12>>^ Então, o procônsul, vendo o que sucedera, creu, maravilhado com a doutrina do Senhor.

[[v44-13-13]]

^<<v44-13-13,13>>^ E, navegando de Pafos, Paulo e seus companheiros dirigiram-se a Perge da Panfília. João, porém, apartando-se deles, voltou para Jerusalém.

[[v44-13-14]]

^<<v44-13-14,14>>^ Mas eles, atravessando de Perge para a Antioquia da Pisídia, indo num sábado à sinagoga, assentaram-se.

[[v44-13-15]]

^<<v44-13-15,15>>^ Depois da leitura da lei e dos profetas, os chefes da sinagoga mandaram dizer-lhes: Irmãos, se tendes alguma palavra de exortação para o povo, dizei-a.

[[v44-13-16]]

^<<v44-13-16,16>>^ Paulo, levantando-se e fazendo com a mão sinal de silêncio, disse: Varões israelitas e vós outros que também temeis a Deus, ouvi.

[[v44-13-17]]

^<<v44-13-17,17>>^ O Deus deste povo de Israel escolheu nossos pais e exaltou o povo durante sua peregrinação na terra do Egito, donde os tirou com braço poderoso;

[[v44-13-18]]

^<<v44-13-18,18>>^ e suportou-lhes os maus costumes por cerca de quarenta anos no deserto;

[[v44-13-19]]

^<<v44-13-19,19>>^ e, havendo destruído sete nações na terra de Canaã, deu-lhes essa terra por herança,

[[v44-13-20]]

^<<v44-13-20,20>>^ vencidos cerca de quatrocentos e cinquenta anos. Depois disto, lhes deu juízes, até o profeta Samuel.

[[v44-13-21]]

^<<v44-13-21,21>>^ Então, eles pediram um rei, e Deus lhes deparou Saul, filho de Quis, da tribo de Benjamim, e isto pelo espaço de quarenta anos.

[[v44-13-22]]

^<<v44-13-22,22>>^ E, tendo tirado a este, levantou-lhes o rei Davi, do qual também, dando testemunho, disse: Achei Davi, filho de Jessé, homem segundo o meu coração, que fará toda a minha vontade.

[[v44-13-23]]

^<<v44-13-23,23>>^ Da descendência deste, conforme a promessa, trouxe Deus a Israel o Salvador, que é Jesus,

[[v44-13-24]]

^<<v44-13-24,24>>^ havendo João, primeiro, pregado a todo o povo de Israel, antes da manifestação dele, batismo de arrependimento.

[[v44-13-25]]

^<<v44-13-25,25>>^ Mas, ao completar João a sua carreira, dizia: Não sou quem supondes; mas após mim vem aquele de cujos pés não sou digno de desatar as sandálias.

[[v44-13-26]]

^<<v44-13-26,26>>^ Irmãos, descendência de Abraão e vós outros os que temeis a Deus, a nós nos foi enviada a palavra desta salvação.

[[v44-13-27]]

^<<v44-13-27,27>>^ Pois os que habitavam em Jerusalém e as suas autoridades, não conhecendo Jesus nem os ensinos dos profetas que se leem todos os sábados, quando o condenaram, cumpriram as profecias;

[[v44-13-28]]

^<<v44-13-28,28>>^ e, embora não achassem nenhuma causa de morte, pediram a Pilatos que ele fosse morto.

[[v44-13-29]]

^<<v44-13-29,29>>^ Depois de cumprirem tudo o que a respeito dele estava escrito, tirando-o do madeiro, puseram-no em um túmulo.

[[v44-13-30]]

^<<v44-13-30,30>>^ Mas Deus o ressuscitou dentre os mortos;

[[v44-13-31]]

^<<v44-13-31,31>>^ e foi visto muitos dias pelos que, com ele, subiram da Galileia para Jerusalém, os quais são agora as suas testemunhas perante o povo.

[[v44-13-32]]

^<<v44-13-32,32>>^ Nós vos anunciamos o evangelho da promessa feita a nossos pais,

[[v44-13-33]]

^<<v44-13-33,33>>^ como Deus a cumpriu plenamente a nós, seus filhos, ressuscitando a Jesus, como também está escrito no Salmo segundo: Tu és meu Filho, eu, hoje, te gerei.

[[v44-13-34]]

^<<v44-13-34,34>>^ E, que Deus o ressuscitou dentre os mortos para que jamais voltasse à corrupção, desta maneira o disse: E cumprirei a vosso favor as santas e fiéis promessas feitas a Davi.

[[v44-13-35]]

^<<v44-13-35,35>>^ Por isso, também diz em outro Salmo: Não permitirás que o teu Santo veja corrupção.

[[v44-13-36]]

^<<v44-13-36,36>>^ Porque, na verdade, tendo Davi servido à sua própria geração, conforme o desígnio de Deus, adormeceu, foi para junto de seus pais e viu corrupção.

[[v44-13-37]]

^<<v44-13-37,37>>^ Porém aquele a quem Deus ressuscitou não viu corrupção.

[[v44-13-38]]

^<<v44-13-38,38>>^ Tomai, pois, irmãos, conhecimento de que se vos anuncia remissão de pecados por intermédio deste;

[[v44-13-39]]

^<<v44-13-39,39>>^ e, por meio dele, todo o que crê é justificado de todas as coisas das quais vós não pudestes ser justificados pela lei de Moisés.

[[v44-13-40]]

^<<v44-13-40,40>>^ Notai, pois, que não vos sobrevenha o que está dito nos profetas:

[[v44-13-41]]

^<<v44-13-41,41>>^ Vede, ó desprezadores, maravilhai-vos e desvanecei, porque eu realizo, em vossos dias, obra tal que não crereis se alguém vo-la contar.

[[v44-13-42]]

^<<v44-13-42,42>>^ Ao saírem eles, rogaram-lhes que, no sábado seguinte, lhes falassem estas mesmas palavras.

[[v44-13-43]]

^<<v44-13-43,43>>^ Despedida a sinagoga, muitos dos judeus e dos prosélitos piedosos seguiram Paulo e Barnabé, e estes, falando-lhes, os persuadiam a perseverar na graça de Deus.

[[v44-13-44]]

^<<v44-13-44,44>>^ No sábado seguinte, afluiu quase toda a cidade para ouvir a palavra de Deus.

[[v44-13-45]]

^<<v44-13-45,45>>^ Mas os judeus, vendo as multidões, tomaram-se de inveja e, blasfemando, contradiziam o que Paulo falava.

[[v44-13-46]]

^<<v44-13-46,46>>^ Então, Paulo e Barnabé, falando ousadamente, disseram: Cumpria que a vós outros, em primeiro lugar, fosse pregada a palavra de Deus; mas, posto que a rejeitais e a vós mesmos vos julgais indignos da vida eterna, eis aí que nos volvemos para os gentios.

[[v44-13-47]]

^<<v44-13-47,47>>^ Porque o Senhor assim no-lo determinou: Eu te constituí para luz dos gentios, a fim de que sejas para salvação até aos confins da terra.

[[v44-13-48]]

^<<v44-13-48,48>>^ Os gentios, ouvindo isto, regozijavam-se e glorificavam a palavra do Senhor, e creram todos os que haviam sido destinados para a vida eterna.

[[v44-13-49]]

^<<v44-13-49,49>>^ E divulgava-se a palavra do Senhor por toda aquela região.

[[v44-13-50]]

^<<v44-13-50,50>>^ Mas os judeus instigaram as mulheres piedosas de alta posição e os principais da cidade e levantaram perseguição contra Paulo e Barnabé, expulsando-os do seu território.

[[v44-13-51]]

^<<v44-13-51,51>>^ E estes, sacudindo contra aqueles o pó dos pés, partiram para Icônio.

[[v44-13-52]]

^<<v44-13-52,52>>^ Os discípulos, porém, transbordavam de alegria e do Espírito Santo.

'''

xref:044-atos/044-atos-012.adoc#v44-12-0[&#60; Capítulo Anterior] | <<v44-13-0,Topo>> | xref:044-atos/044-atos-014.adoc#v44-14-0[Próximo Capítulo &#62;]