include::./index.adoc[]

[[v44-1-0]]
=== Atos, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-1-1]]

^<<v44-1-1,1>>^ Escrevi o primeiro livro, ó Teófilo, relatando todas as coisas que Jesus começou a fazer e a ensinar

[[v44-1-2]]

^<<v44-1-2,2>>^ até ao dia em que, depois de haver dado mandamentos por intermédio do Espírito Santo aos apóstolos que escolhera, foi elevado às alturas.

[[v44-1-3]]

^<<v44-1-3,3>>^ A estes também, depois de ter padecido, se apresentou vivo, com muitas provas incontestáveis, aparecendo-lhes durante quarenta dias e falando das coisas concernentes ao reino de Deus.

[[v44-1-4]]

^<<v44-1-4,4>>^ E, comendo com eles, determinou-lhes que não se ausentassem de Jerusalém, mas que esperassem a promessa do Pai, a qual,  disse ele, de mim ouvistes.

[[v44-1-5]]

^<<v44-1-5,5>>^ Porque João, na verdade, batizou com água, mas vós sereis batizados com o Espírito Santo, não muito depois destes dias.

[[v44-1-6]]

^<<v44-1-6,6>>^ Então, os que estavam reunidos lhe perguntaram: Senhor, será este o tempo em que restaures o reino a Israel?

[[v44-1-7]]

^<<v44-1-7,7>>^ Respondeu-lhes: Não vos compete conhecer tempos ou épocas que o Pai reservou pela sua exclusiva autoridade;

[[v44-1-8]]

^<<v44-1-8,8>>^ mas recebereis poder, ao descer sobre vós o Espírito Santo, e sereis minhas testemunhas tanto em Jerusalém como em toda a Judeia e Samaria e até aos confins da terra.

[[v44-1-9]]

^<<v44-1-9,9>>^ Ditas estas palavras, foi Jesus elevado às alturas, à vista deles, e uma nuvem o encobriu dos seus olhos.

[[v44-1-10]]

^<<v44-1-10,10>>^ E, estando eles com os olhos fitos no céu, enquanto Jesus subia, eis que dois varões vestidos de branco se puseram ao lado deles

[[v44-1-11]]

^<<v44-1-11,11>>^ e lhes disseram: Varões galileus, por que estais olhando para as alturas? Esse Jesus que dentre vós foi assunto ao céu virá do modo como o vistes subir.

[[v44-1-12]]

^<<v44-1-12,12>>^ Então, voltaram para Jerusalém, do monte chamado Olival, que dista daquela cidade tanto como a jornada de um sábado.

[[v44-1-13]]

^<<v44-1-13,13>>^ Quando ali entraram, subiram para o cenáculo onde se reuniam Pedro, João, Tiago, André, Filipe, Tomé, Bartolomeu, Mateus, Tiago, filho de Alfeu, Simão, o Zelote, e Judas, filho de Tiago.

[[v44-1-14]]

^<<v44-1-14,14>>^ Todos estes perseveravam unânimes em oração, com as mulheres, com Maria, mãe de Jesus, e com os irmãos dele.

[[v44-1-15]]

^<<v44-1-15,15>>^ Naqueles dias, levantou-se Pedro no meio dos irmãos (ora, compunha-se a assembleia de umas cento e vinte pessoas) e disse:

[[v44-1-16]]

^<<v44-1-16,16>>^ Irmãos, convinha que se cumprisse a Escritura que o Espírito Santo proferiu anteriormente por boca de Davi, acerca de Judas, que foi o guia daqueles que prenderam Jesus,

[[v44-1-17]]

^<<v44-1-17,17>>^ porque ele era contado entre nós e teve parte neste ministério.

[[v44-1-18]]

^<<v44-1-18,18>>^ (Ora, este homem adquiriu um campo com o preço da iniquidade; e, precipitando-se, rompeu-se pelo meio, e todas as suas entranhas se derramaram;

[[v44-1-19]]

^<<v44-1-19,19>>^ e isto chegou ao conhecimento de todos os habitantes de Jerusalém, de maneira que em sua própria língua esse campo era chamado Aceldama, isto é, Campo de Sangue. )

[[v44-1-20]]

^<<v44-1-20,20>>^ Porque está escrito no Livro dos Salmos: Fique deserta a sua morada; e não haja quem nela habite; e: Tome outro o seu encargo.

[[v44-1-21]]

^<<v44-1-21,21>>^ É necessário, pois, que, dos homens que nos acompanharam todo o tempo que o Senhor Jesus andou entre nós,

[[v44-1-22]]

^<<v44-1-22,22>>^ começando no batismo de João, até ao dia em que dentre nós foi levado às alturas, um destes se torne testemunha conosco da sua ressurreição.

[[v44-1-23]]

^<<v44-1-23,23>>^ Então, propuseram dois: José, chamado Barsabás, cognominado Justo, e Matias.

[[v44-1-24]]

^<<v44-1-24,24>>^ E, orando, disseram: Tu, Senhor, que conheces o coração de todos, revela-nos qual destes dois tens escolhido

[[v44-1-25]]

^<<v44-1-25,25>>^ para preencher a vaga neste ministério e apostolado, do qual Judas se transviou, indo para o seu próprio lugar.

[[v44-1-26]]

^<<v44-1-26,26>>^ E os lançaram em sortes, vindo a sorte recair sobre Matias, sendo-lhe, então, votado lugar com os onze apóstolos.

'''

xref:043-joao/043-joao-021.adoc#v43-21-0[&#60; Capítulo Anterior] | <<v44-1-0,Topo>> | xref:044-atos/044-atos-002.adoc#v44-2-0[Próximo Capítulo &#62;]