include::./index.adoc[]

[[v44-17-0]]
=== Atos, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-17-1]]

^<<v44-17-1,1>>^ Tendo passado por Anfípolis e Apolônia, chegaram a Tessalônica, onde havia uma sinagoga de judeus.

[[v44-17-2]]

^<<v44-17-2,2>>^ Paulo, segundo o seu costume, foi procurá-los e, por três sábados, arrazoou com eles acerca das Escrituras,

[[v44-17-3]]

^<<v44-17-3,3>>^ expondo e demonstrando ter sido necessário que o Cristo padecesse e ressurgisse dentre os mortos; e este, dizia ele, é o Cristo, Jesus, que eu vos anuncio.

[[v44-17-4]]

^<<v44-17-4,4>>^ Alguns deles foram persuadidos e unidos a Paulo e Silas, bem como numerosa multidão de gregos piedosos e muitas distintas mulheres.

[[v44-17-5]]

^<<v44-17-5,5>>^ Os judeus, porém, movidos de inveja, trazendo consigo alguns homens maus dentre a malandragem, ajuntando a turba, alvoroçaram a cidade e, assaltando a casa de Jasom, procuravam trazê-los para o meio do povo.

[[v44-17-6]]

^<<v44-17-6,6>>^ Porém, não os encontrando, arrastaram Jasom e alguns irmãos perante as autoridades, clamando: Estes que têm transtornado o mundo chegaram também aqui,

[[v44-17-7]]

^<<v44-17-7,7>>^ os quais Jasom hospedou. Todos estes procedem contra os decretos de César, afirmando ser Jesus outro rei.

[[v44-17-8]]

^<<v44-17-8,8>>^ Tanto a multidão como as autoridades ficaram agitadas ao ouvirem estas palavras;

[[v44-17-9]]

^<<v44-17-9,9>>^ contudo, soltaram Jasom e os mais, após terem recebido deles a fiança estipulada.

[[v44-17-10]]

^<<v44-17-10,10>>^ E logo, durante a noite, os irmãos enviaram Paulo e Silas para Bereia; ali chegados, dirigiram-se à sinagoga dos judeus.

[[v44-17-11]]

^<<v44-17-11,11>>^ Ora, estes de Bereia eram mais nobres que os de Tessalônica; pois receberam a palavra com toda a avidez, examinando as Escrituras todos os dias para ver se as coisas eram, de fato, assim.

[[v44-17-12]]

^<<v44-17-12,12>>^ Com isso, muitos deles creram, mulheres gregas de alta posição e não poucos homens.

[[v44-17-13]]

^<<v44-17-13,13>>^ Mas, logo que os judeus de Tessalônica souberam que a palavra de Deus era anunciada por Paulo também em Bereia, foram lá excitar e perturbar o povo.

[[v44-17-14]]

^<<v44-17-14,14>>^ Então, os irmãos promoveram, sem detença, a partida de Paulo para os lados do mar. Porém Silas e Timóteo continuaram ali.

[[v44-17-15]]

^<<v44-17-15,15>>^ Os responsáveis por Paulo levaram-no até Atenas e regressaram trazendo ordem a Silas e Timóteo para que, o mais depressa possível, fossem ter com ele.

[[v44-17-16]]

^<<v44-17-16,16>>^ Enquanto Paulo os esperava em Atenas, o seu espírito se revoltava em face da idolatria dominante na cidade.

[[v44-17-17]]

^<<v44-17-17,17>>^ Por isso, dissertava na sinagoga entre os judeus e os gentios piedosos; também na praça, todos os dias, entre os que se encontravam ali.

[[v44-17-18]]

^<<v44-17-18,18>>^ E alguns dos filósofos epicureus e estoicos contendiam com ele, havendo quem perguntasse: Que quer dizer esse tagarela? E outros: Parece pregador de estranhos deuses; pois pregava a Jesus e a ressurreição.

[[v44-17-19]]

^<<v44-17-19,19>>^ Então, tomando-o consigo, o levaram ao Areópago, dizendo: Poderemos saber que nova doutrina é essa que ensinas?

[[v44-17-20]]

^<<v44-17-20,20>>^ Posto que nos trazes aos ouvidos coisas estranhas, queremos saber o que vem a ser isso.

[[v44-17-21]]

^<<v44-17-21,21>>^ Pois todos os de Atenas e os estrangeiros residentes de outra coisa não cuidavam senão dizer ou ouvir as últimas novidades.

[[v44-17-22]]

^<<v44-17-22,22>>^ Então, Paulo, levantando-se no meio do Areópago, disse: Senhores atenienses! Em tudo vos vejo acentuadamente religiosos;

[[v44-17-23]]

^<<v44-17-23,23>>^ porque, passando e observando os objetos de vosso culto, encontrei também um altar no qual está inscrito: Ao Deus Desconhecido . Pois esse que adorais sem conhecer é precisamente aquele que eu vos anuncio.

[[v44-17-24]]

^<<v44-17-24,24>>^ O Deus que fez o mundo e tudo o que nele existe, sendo ele Senhor do céu e da terra, não habita em santuários feitos por mãos humanas.

[[v44-17-25]]

^<<v44-17-25,25>>^ Nem é servido por mãos humanas, como se de alguma coisa precisasse; pois ele mesmo é quem a todos dá vida, respiração e tudo mais;

[[v44-17-26]]

^<<v44-17-26,26>>^ de um só fez toda a raça humana para habitar sobre toda a face da terra, havendo fixado os tempos previamente estabelecidos e os limites da sua habitação;

[[v44-17-27]]

^<<v44-17-27,27>>^ para buscarem a Deus se, porventura, tateando, o possam achar, bem que não está longe de cada um de nós;

[[v44-17-28]]

^<<v44-17-28,28>>^ pois nele vivemos, e nos movemos, e existimos, como alguns dos vossos poetas têm dito: Porque dele também somos geração.

[[v44-17-29]]

^<<v44-17-29,29>>^ Sendo, pois, geração de Deus, não devemos pensar que a divindade é semelhante ao ouro, à prata ou à pedra, trabalhados pela arte e imaginação do homem.

[[v44-17-30]]

^<<v44-17-30,30>>^ Ora, não levou Deus em conta os tempos da ignorância; agora, porém, notifica aos homens que todos, em toda parte, se arrependam;

[[v44-17-31]]

^<<v44-17-31,31>>^ porquanto estabeleceu um dia em que há de julgar o mundo com justiça, por meio de um varão que destinou e acreditou diante de todos, ressuscitando-o dentre os mortos.

[[v44-17-32]]

^<<v44-17-32,32>>^ Quando ouviram falar de ressurreição de mortos, uns escarneceram, e outros disseram: A respeito disso te ouviremos noutra ocasião.

[[v44-17-33]]

^<<v44-17-33,33>>^ A essa altura, Paulo se retirou do meio deles.

[[v44-17-34]]

^<<v44-17-34,34>>^ Houve, porém, alguns homens que se agregaram a ele e creram; entre eles estava Dionísio, o areopagita, uma mulher chamada Dâmaris e, com eles, outros mais.

'''

xref:044-atos/044-atos-016.adoc#v44-16-0[&#60; Capítulo Anterior] | <<v44-17-0,Topo>> | xref:044-atos/044-atos-018.adoc#v44-18-0[Próximo Capítulo &#62;]