include::./index.adoc[]

[[v44-6-0]]
=== Atos, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-6-1]]

^<<v44-6-1,1>>^ Ora, naqueles dias, multiplicando-se o número dos discípulos, houve murmuração dos helenistas contra os hebreus, porque as viúvas deles estavam sendo esquecidas na distribuição diária.

[[v44-6-2]]

^<<v44-6-2,2>>^ Então, os doze convocaram a comunidade dos discípulos e disseram: Não é razoável que nós abandonemos a palavra de Deus para servir às mesas.

[[v44-6-3]]

^<<v44-6-3,3>>^ Mas, irmãos, escolhei dentre vós sete homens de boa reputação, cheios do Espírito e de sabedoria, aos quais encarregaremos deste serviço;

[[v44-6-4]]

^<<v44-6-4,4>>^ e, quanto a nós, nos consagraremos à oração e ao ministério da palavra.

[[v44-6-5]]

^<<v44-6-5,5>>^ O parecer agradou a toda a comunidade; e elegeram Estêvão, homem cheio de fé e do Espírito Santo, Filipe, Prócoro, Nicanor, Timão, Pármenas e Nicolau, prosélito de Antioquia.

[[v44-6-6]]

^<<v44-6-6,6>>^ Apresentaram-nos perante os apóstolos, e estes, orando, lhes impuseram as mãos.

[[v44-6-7]]

^<<v44-6-7,7>>^ Crescia a palavra de Deus, e, em Jerusalém, se multiplicava o número dos discípulos; também muitíssimos sacerdotes obedeciam à fé.

[[v44-6-8]]

^<<v44-6-8,8>>^ Estêvão, cheio de graça e poder, fazia prodígios e grandes sinais entre o povo.

[[v44-6-9]]

^<<v44-6-9,9>>^ Levantaram-se, porém, alguns dos que eram da sinagoga chamada dos Libertos, dos cireneus, dos alexandrinos e dos da Cilícia e Ásia, e discutiam com Estêvão;

[[v44-6-10]]

^<<v44-6-10,10>>^ e não podiam resistir à sabedoria e ao Espírito, pelo qual ele falava.

[[v44-6-11]]

^<<v44-6-11,11>>^ Então, subornaram homens que dissessem: Temos ouvido este homem proferir blasfêmias contra Moisés e contra Deus.

[[v44-6-12]]

^<<v44-6-12,12>>^ Sublevaram o povo, os anciãos e os escribas e, investindo, o arrebataram, levando-o ao Sinédrio.

[[v44-6-13]]

^<<v44-6-13,13>>^ Apresentaram testemunhas falsas, que depuseram: Este homem não cessa de falar contra o lugar santo e contra a lei;

[[v44-6-14]]

^<<v44-6-14,14>>^ porque o temos ouvido dizer que esse Jesus, o Nazareno, destruirá este lugar e mudará os costumes que Moisés nos deu.

[[v44-6-15]]

^<<v44-6-15,15>>^ Todos os que estavam assentados no Sinédrio, fitando os olhos em Estêvão, viram o seu rosto como se fosse rosto de anjo.

'''

xref:044-atos/044-atos-005.adoc#v44-5-0[&#60; Capítulo Anterior] | <<v44-6-0,Topo>> | xref:044-atos/044-atos-007.adoc#v44-7-0[Próximo Capítulo &#62;]