include::./index.adoc[]

[[v44-26-0]]
=== Atos, 26
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-26-1]]

^<<v44-26-1,1>>^ A seguir, Agripa, dirigindo-se a Paulo, disse: É permitido que uses da palavra em tua defesa. Então, Paulo, estendendo a mão, passou a defender-se nestes termos:

[[v44-26-2]]

^<<v44-26-2,2>>^ Tenho-me por feliz, ó rei Agripa, pelo privilégio de, hoje, na tua presença, poder produzir a minha defesa de todas as acusações feitas contra mim pelos judeus;

[[v44-26-3]]

^<<v44-26-3,3>>^ mormente porque és versado em todos os costumes e questões que há entre os judeus; por isso, eu te peço que me ouças com paciência.

[[v44-26-4]]

^<<v44-26-4,4>>^ Quanto à minha vida, desde a mocidade, como decorreu desde o princípio entre o meu povo e em Jerusalém, todos os judeus a conhecem;

[[v44-26-5]]

^<<v44-26-5,5>>^ pois, na verdade, eu era conhecido deles desde o princípio, se assim o quiserem testemunhar, porque vivi fariseu conforme a seita mais severa da nossa religião.

[[v44-26-6]]

^<<v44-26-6,6>>^ E, agora, estou sendo julgado por causa da esperança da promessa que por Deus foi feita a nossos pais,

[[v44-26-7]]

^<<v44-26-7,7>>^ a qual as nossas doze tribos, servindo a Deus fervorosamente de noite e de dia, almejam alcançar; é no tocante a esta esperança, ó rei, que eu sou acusado pelos judeus.

[[v44-26-8]]

^<<v44-26-8,8>>^ Por que se julga incrível entre vós que Deus ressuscite os mortos?

[[v44-26-9]]

^<<v44-26-9,9>>^ Na verdade, a mim me parecia que muitas coisas devia eu praticar contra o nome de Jesus, o Nazareno;

[[v44-26-10]]

^<<v44-26-10,10>>^ e assim procedi em Jerusalém. Havendo eu recebido autorização dos principais sacerdotes, encerrei muitos dos santos nas prisões; e contra estes dava o meu voto, quando os matavam.

[[v44-26-11]]

^<<v44-26-11,11>>^ Muitas vezes, os castiguei por todas as sinagogas, obrigando-os até a blasfemar. E, demasiadamente enfurecido contra eles, mesmo por cidades estranhas os perseguia.

[[v44-26-12]]

^<<v44-26-12,12>>^ Com estes intuitos, parti para Damasco, levando autorização dos principais sacerdotes e por eles comissionado.

[[v44-26-13]]

^<<v44-26-13,13>>^ Ao meio-dia, ó rei, indo eu caminho fora, vi uma luz no céu, mais resplandecente que o sol, que brilhou ao redor de mim e dos que iam comigo.

[[v44-26-14]]

^<<v44-26-14,14>>^ E, caindo todos nós por terra, ouvi uma voz que me falava em língua hebraica: Saulo, Saulo, por que me persegues? Dura coisa é recalcitrares contra os aguilhões.

[[v44-26-15]]

^<<v44-26-15,15>>^ Então, eu perguntei: Quem és tu, Senhor? Ao que o Senhor respondeu: Eu sou Jesus, a quem tu persegues.

[[v44-26-16]]

^<<v44-26-16,16>>^ Mas levanta-te e firma-te sobre teus pés, porque por isto te apareci, para te constituir ministro e testemunha, tanto das coisas em que me viste como daquelas pelas quais te aparecerei ainda,

[[v44-26-17]]

^<<v44-26-17,17>>^ livrando-te do povo e dos gentios, para os quais eu te envio,

[[v44-26-18]]

^<<v44-26-18,18>>^ para lhes abrires os olhos e os converteres das trevas para a luz e da potestade de Satanás para Deus, a fim de que recebam eles remissão de pecados e herança entre os que são santificados pela fé em mim.

[[v44-26-19]]

^<<v44-26-19,19>>^ Pelo que, ó rei Agripa, não fui desobediente à visão celestial,

[[v44-26-20]]

^<<v44-26-20,20>>^ mas anunciei primeiramente aos de Damasco e em Jerusalém, por toda a região da Judeia, e aos gentios, que se arrependessem e se convertessem a Deus, praticando obras dignas de arrependimento.

[[v44-26-21]]

^<<v44-26-21,21>>^ Por causa disto, alguns judeus me prenderam, estando eu no templo, e tentaram matar-me.

[[v44-26-22]]

^<<v44-26-22,22>>^ Mas, alcançando socorro de Deus, permaneço até ao dia de hoje, dando testemunho, tanto a pequenos como a grandes, nada dizendo, senão o que os profetas e Moisés disseram haver de acontecer,

[[v44-26-23]]

^<<v44-26-23,23>>^ isto é, que o Cristo devia padecer e, sendo o primeiro da ressurreição dos mortos, anunciaria a luz ao povo e aos gentios.

[[v44-26-24]]

^<<v44-26-24,24>>^ Dizendo ele estas coisas em sua defesa, Festo o interrompeu em alta voz: Estás louco, Paulo! As muitas letras te fazem delirar!

[[v44-26-25]]

^<<v44-26-25,25>>^ Paulo, porém, respondeu: Não estou louco, ó excelentíssimo Festo! Pelo contrário, digo palavras de verdade e de bom senso.

[[v44-26-26]]

^<<v44-26-26,26>>^ Porque tudo isto é do conhecimento do rei, a quem me dirijo com franqueza, pois estou persuadido de que nenhuma destas coisas lhe é oculta; porquanto nada se passou em algum lugar escondido.

[[v44-26-27]]

^<<v44-26-27,27>>^ Acreditas, ó rei Agripa, nos profetas? Bem sei que acreditas.

[[v44-26-28]]

^<<v44-26-28,28>>^ Então, Agripa se dirigiu a Paulo e disse: Por pouco me persuades a me fazer cristão.

[[v44-26-29]]

^<<v44-26-29,29>>^ Paulo respondeu: Assim Deus permitisse que, por pouco ou por muito, não apenas tu, ó rei, porém todos os que hoje me ouvem se tornassem tais qual eu sou, exceto estas cadeias.

[[v44-26-30]]

^<<v44-26-30,30>>^ A essa altura, levantou-se o rei, e também o governador, e Berenice, bem como os que estavam assentados com eles;

[[v44-26-31]]

^<<v44-26-31,31>>^ e, havendo-se retirado, falavam uns com os outros, dizendo: Este homem nada tem feito passível de morte ou de prisão.

[[v44-26-32]]

^<<v44-26-32,32>>^ Então, Agripa se dirigiu a Festo e disse: Este homem bem podia ser solto, se não tivesse apelado para César.

'''

xref:044-atos/044-atos-025.adoc#v44-25-0[&#60; Capítulo Anterior] | <<v44-26-0,Topo>> | xref:044-atos/044-atos-027.adoc#v44-27-0[Próximo Capítulo &#62;]