include::./index.adoc[]

[[v44-23-0]]
=== Atos, 23
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-23-1]]

^<<v44-23-1,1>>^ Fitando Paulo os olhos no Sinédrio, disse: Varões, irmãos, tenho andado diante de Deus com toda a boa consciência até ao dia de hoje.

[[v44-23-2]]

^<<v44-23-2,2>>^ Mas o sumo sacerdote, Ananias, mandou aos que estavam perto dele que lhe batessem na boca.

[[v44-23-3]]

^<<v44-23-3,3>>^ Então, lhe disse Paulo: Deus há de ferir-te, parede branqueada! Tu estás aí sentado para julgar-me segundo a lei e, contra a lei, mandas agredir-me?

[[v44-23-4]]

^<<v44-23-4,4>>^ Os que estavam a seu lado disseram: Estás injuriando o sumo sacerdote de Deus?

[[v44-23-5]]

^<<v44-23-5,5>>^ Respondeu Paulo: Não sabia, irmãos, que ele é sumo sacerdote; porque está escrito: Não falarás mal de uma autoridade do teu povo.

[[v44-23-6]]

^<<v44-23-6,6>>^ Sabendo Paulo que uma parte do Sinédrio se compunha de saduceus e outra, de fariseus, exclamou: Varões, irmãos, eu sou fariseu, filho de fariseus! No tocante à esperança e à ressurreição dos mortos sou julgado!

[[v44-23-7]]

^<<v44-23-7,7>>^ Ditas estas palavras, levantou-se grande dissensão entre fariseus e saduceus, e a multidão se dividiu.

[[v44-23-8]]

^<<v44-23-8,8>>^ Pois os saduceus declaram não haver ressurreição, nem anjo, nem espírito; ao passo que os fariseus admitem todas essas coisas.

[[v44-23-9]]

^<<v44-23-9,9>>^ Houve, pois, grande vozearia. E, levantando-se alguns escribas da parte dos fariseus, contendiam, dizendo: Não achamos neste homem mal algum; e será que algum espírito ou anjo lhe tenha falado?

[[v44-23-10]]

^<<v44-23-10,10>>^ Tomando vulto a celeuma, temendo o comandante que fosse Paulo espedaçado por eles, mandou descer a guarda para que o retirassem dali e o levassem para a fortaleza.

[[v44-23-11]]

^<<v44-23-11,11>>^ Na noite seguinte, o Senhor, pondo-se ao lado dele, disse: Coragem! Pois do modo por que deste testemunho a meu respeito em Jerusalém, assim importa que também o faças em Roma.

[[v44-23-12]]

^<<v44-23-12,12>>^ Quando amanheceu, os judeus se reuniram e, sob anátema, juraram que não haviam de comer, nem beber, enquanto não matassem Paulo.

[[v44-23-13]]

^<<v44-23-13,13>>^ Eram mais de quarenta os que entraram nesta conspirata.

[[v44-23-14]]

^<<v44-23-14,14>>^ Estes, indo ter com os principais sacerdotes e os anciãos, disseram: Juramos, sob pena de anátema, não comer coisa alguma, enquanto não matarmos Paulo.

[[v44-23-15]]

^<<v44-23-15,15>>^ Agora, pois, notificai ao comandante, juntamente com o Sinédrio, que vo-lo apresente como se estivésseis para investigar mais acuradamente a sua causa; e nós, antes que ele chegue, estaremos prontos para assassiná-lo.

[[v44-23-16]]

^<<v44-23-16,16>>^ Mas o filho da irmã de Paulo, tendo ouvido a trama, foi, entrou na fortaleza e de tudo avisou a Paulo.

[[v44-23-17]]

^<<v44-23-17,17>>^ Então, este, chamando um dos centuriões, disse: Leva este rapaz ao comandante, porque tem alguma coisa a comunicar-lhe.

[[v44-23-18]]

^<<v44-23-18,18>>^ Tomando-o, pois, levou-o ao comandante, dizendo: O preso Paulo, chamando-me, pediu-me que trouxesse à tua presença este rapaz, pois tem algo que dizer-te.

[[v44-23-19]]

^<<v44-23-19,19>>^ Tomou-o pela mão o comandante e, pondo-se à parte, perguntou-lhe: Que tens a comunicar-me?

[[v44-23-20]]

^<<v44-23-20,20>>^ Respondeu ele: Os judeus decidiram rogar-te que, amanhã, apresentes Paulo ao Sinédrio, como se houvesse de inquirir mais acuradamente a seu respeito.

[[v44-23-21]]

^<<v44-23-21,21>>^ Tu, pois, não te deixes persuadir, porque mais de quarenta entre eles estão pactuados entre si, sob anátema, de não comer, nem beber, enquanto não o matarem; e, agora, estão prontos, esperando a tua promessa.

[[v44-23-22]]

^<<v44-23-22,22>>^ Então, o comandante despediu o rapaz, recomendando-lhe que a ninguém dissesse ter-lhe trazido estas informações.

[[v44-23-23]]

^<<v44-23-23,23>>^ Chamando dois centuriões, ordenou: Tende de prontidão, desde a hora terceira da noite, duzentos soldados, setenta de cavalaria e duzentos lanceiros para irem até Cesareia;

[[v44-23-24]]

^<<v44-23-24,24>>^ preparai também animais para fazer Paulo montar e ir com segurança ao governador Félix.

[[v44-23-25]]

^<<v44-23-25,25>>^ E o comandante escreveu uma carta nestes termos:

[[v44-23-26]]

^<<v44-23-26,26>>^ Cláudio Lísias ao excelentíssimo governador Félix, saúde.

[[v44-23-27]]

^<<v44-23-27,27>>^ Este homem foi preso pelos judeus e estava prestes a ser morto por eles, quando eu, sobrevindo com a guarda, o livrei, por saber que ele era romano.

[[v44-23-28]]

^<<v44-23-28,28>>^ Querendo certificar-me do motivo por que o acusavam, fi-lo descer ao Sinédrio deles;

[[v44-23-29]]

^<<v44-23-29,29>>^ verifiquei ser ele acusado de coisas referentes à lei que os rege, nada, porém, que justificasse morte ou mesmo prisão.

[[v44-23-30]]

^<<v44-23-30,30>>^ Sendo eu informado de que ia haver uma cilada contra o homem, tratei de enviá-lo a ti, sem demora, intimando também os acusadores a irem dizer, na tua presença, o que há contra ele. [Saúde.]

[[v44-23-31]]

^<<v44-23-31,31>>^ Os soldados, pois, conforme lhes foi ordenado, tomaram Paulo e, durante a noite, o conduziram até Antipátride;

[[v44-23-32]]

^<<v44-23-32,32>>^ no dia seguinte, voltaram para a fortaleza, tendo deixado aos de cavalaria o irem com ele;

[[v44-23-33]]

^<<v44-23-33,33>>^ os quais, chegando a Cesareia, entregaram a carta ao governador e também lhe apresentaram Paulo.

[[v44-23-34]]

^<<v44-23-34,34>>^ Lida a carta, perguntou o governador de que província ele era; e, quando soube que era da Cilícia,

[[v44-23-35]]

^<<v44-23-35,35>>^ disse: Ouvir-te-ei quando chegarem os teus acusadores. E mandou que ele fosse detido no pretório de Herodes.

'''

xref:044-atos/044-atos-022.adoc#v44-22-0[&#60; Capítulo Anterior] | <<v44-23-0,Topo>> | xref:044-atos/044-atos-024.adoc#v44-24-0[Próximo Capítulo &#62;]