include::./index.adoc[]

[[v44-21-0]]
=== Atos, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-21-1]]

^<<v44-21-1,1>>^ Depois de nos apartarmos, fizemo-nos à vela e, correndo em direitura, chegamos a Cós; no dia seguinte, a Rodes, e dali, a Pátara.

[[v44-21-2]]

^<<v44-21-2,2>>^ Achando um navio que ia para a Fenícia, embarcamos nele, seguindo viagem.

[[v44-21-3]]

^<<v44-21-3,3>>^ Quando Chipre já estava à vista, deixando-a à esquerda, navegamos para a Síria e chegamos a Tiro; pois o navio devia ser descarregado ali.

[[v44-21-4]]

^<<v44-21-4,4>>^ Encontrando os discípulos, permanecemos lá durante sete dias; e eles, movidos pelo Espírito, recomendavam a Paulo que não fosse a Jerusalém.

[[v44-21-5]]

^<<v44-21-5,5>>^ Passados aqueles dias, tendo-nos retirado, prosseguimos viagem, acompanhados por todos, cada um com sua mulher e filhos, até fora da cidade; ajoelhados na praia, oramos.

[[v44-21-6]]

^<<v44-21-6,6>>^ E, despedindo-nos uns dos outros, então, embarcamos; e eles voltaram para casa.

[[v44-21-7]]

^<<v44-21-7,7>>^ Quanto a nós, concluindo a viagem de Tiro, chegamos a Ptolemaida, onde saudamos os irmãos, passando um dia com eles.

[[v44-21-8]]

^<<v44-21-8,8>>^ No dia seguinte, partimos e fomos para Cesareia; e, entrando na casa de Filipe, o evangelista, que era um dos sete, ficamos com ele.

[[v44-21-9]]

^<<v44-21-9,9>>^ Tinha este quatro filhas donzelas, que profetizavam.

[[v44-21-10]]

^<<v44-21-10,10>>^ Demorando-nos ali alguns dias, desceu da Judeia um profeta chamado Ágabo;

[[v44-21-11]]

^<<v44-21-11,11>>^ e, vindo ter conosco, tomando o cinto de Paulo, ligando com ele os próprios pés e mãos, declarou: Isto diz o Espírito Santo: Assim os judeus, em Jerusalém, farão ao dono deste cinto e o entregarão nas mãos dos gentios.

[[v44-21-12]]

^<<v44-21-12,12>>^ Quando ouvimos estas palavras, tanto nós como os daquele lugar, rogamos a Paulo que não subisse a Jerusalém.

[[v44-21-13]]

^<<v44-21-13,13>>^ Então, ele respondeu: Que fazeis chorando e quebrantando-me o coração? Pois estou pronto não só para ser preso, mas até para morrer em Jerusalém pelo nome do Senhor Jesus.

[[v44-21-14]]

^<<v44-21-14,14>>^ Como, porém, não o persuadimos, conformados, dissemos: Faça-se a vontade do Senhor!

[[v44-21-15]]

^<<v44-21-15,15>>^ Passados aqueles dias, tendo feito os preparativos, subimos para Jerusalém;

[[v44-21-16]]

^<<v44-21-16,16>>^ e alguns dos discípulos também vieram de Cesareia conosco, trazendo consigo Mnasom, natural de Chipre, velho discípulo, com quem nos deveríamos hospedar.

[[v44-21-17]]

^<<v44-21-17,17>>^ Tendo nós chegado a Jerusalém, os irmãos nos receberam com alegria.

[[v44-21-18]]

^<<v44-21-18,18>>^ No dia seguinte, Paulo foi conosco encontrar-se com Tiago, e todos os presbíteros se reuniram.

[[v44-21-19]]

^<<v44-21-19,19>>^ E, tendo-os saudado, contou minuciosamente o que Deus fizera entre os gentios por seu ministério.

[[v44-21-20]]

^<<v44-21-20,20>>^ Ouvindo-o, deram eles glória a Deus e lhe disseram: Bem vês, irmão, quantas dezenas de milhares há entre os judeus que creram, e todos são zelosos da lei;

[[v44-21-21]]

^<<v44-21-21,21>>^ e foram informados a teu respeito que ensinas todos os judeus entre os gentios a apostatarem de Moisés, dizendo-lhes que não devem circuncidar os filhos, nem andar segundo os costumes da lei.

[[v44-21-22]]

^<<v44-21-22,22>>^ Que se há de fazer, pois? Certamente saberão da tua chegada.

[[v44-21-23]]

^<<v44-21-23,23>>^ Faze, portanto, o que te vamos dizer: estão entre nós quatro homens que, voluntariamente, aceitaram voto;

[[v44-21-24]]

^<<v44-21-24,24>>^ toma-os, purifica-te com eles e faze a despesa necessária para que raspem a cabeça; e saberão todos que não é verdade o que se diz a teu respeito; e que, pelo contrário, andas também, tu mesmo, guardando a lei.

[[v44-21-25]]

^<<v44-21-25,25>>^ Quanto aos gentios que creram, já lhes transmitimos decisões para que se abstenham das coisas sacrificadas a ídolos, do sangue, da carne de animais sufocados e das relações sexuais ilícitas.

[[v44-21-26]]

^<<v44-21-26,26>>^ Então, Paulo, tomando aqueles homens, no dia seguinte, tendo-se purificado com eles, entrou no templo, acertando o cumprimento dos dias da purificação, até que se fizesse a oferta em favor de cada um deles.

[[v44-21-27]]

^<<v44-21-27,27>>^ Quando já estavam por findar os sete dias, os judeus vindos da Ásia, tendo visto Paulo no templo, alvoroçaram todo o povo e o agarraram,

[[v44-21-28]]

^<<v44-21-28,28>>^ gritando: Israelitas, socorro! Este é o homem que por toda parte ensina todos a serem contra o povo, contra a lei e contra este lugar; ainda mais, introduziu até gregos no templo e profanou este recinto sagrado.

[[v44-21-29]]

^<<v44-21-29,29>>^ Pois, antes, tinham visto Trófimo, o efésio, em sua companhia na cidade e julgavam que Paulo o introduzira no templo.

[[v44-21-30]]

^<<v44-21-30,30>>^ Agitou-se toda a cidade, havendo concorrência do povo; e, agarrando a Paulo, arrastaram-no para fora do templo, e imediatamente foram fechadas as portas.

[[v44-21-31]]

^<<v44-21-31,31>>^ Procurando eles matá-lo, chegou ao conhecimento do comandante da força que toda a Jerusalém estava amotinada.

[[v44-21-32]]

^<<v44-21-32,32>>^ Então, este, levando logo soldados e centuriões, correu para o meio do povo. Ao verem chegar o comandante e os soldados, cessaram de espancar Paulo.

[[v44-21-33]]

^<<v44-21-33,33>>^ Aproximando-se o comandante, apoderou-se de Paulo e ordenou que fosse acorrentado com duas cadeias, perguntando quem era e o que havia feito.

[[v44-21-34]]

^<<v44-21-34,34>>^ Na multidão, uns gritavam de um modo; outros, de outro; não podendo ele, porém, saber a verdade por causa do tumulto, ordenou que Paulo fosse recolhido à fortaleza.

[[v44-21-35]]

^<<v44-21-35,35>>^ Ao chegar às escadas, foi preciso que os soldados o carregassem, por causa da violência da multidão,

[[v44-21-36]]

^<<v44-21-36,36>>^ pois a massa de povo o seguia gritando: Mata-o!

[[v44-21-37]]

^<<v44-21-37,37>>^ E, quando Paulo ia sendo recolhido à fortaleza, disse ao comandante: É-me permitido dizer-te alguma coisa? Respondeu ele: Sabes o grego?

[[v44-21-38]]

^<<v44-21-38,38>>^ Não és tu, porventura, o egípcio que, há tempos, sublevou e conduziu ao deserto quatro mil sicários?

[[v44-21-39]]

^<<v44-21-39,39>>^ Respondeu-lhe Paulo: Eu sou judeu, natural de Tarso, cidade não insignificante da Cilícia; e rogo-te que me permitas falar ao povo.

[[v44-21-40]]

^<<v44-21-40,40>>^ Obtida a permissão, Paulo, em pé na escada, fez com a mão sinal ao povo. Fez-se grande silêncio, e ele falou em língua hebraica, dizendo:

'''

xref:044-atos/044-atos-020.adoc#v44-20-0[&#60; Capítulo Anterior] | <<v44-21-0,Topo>> | xref:044-atos/044-atos-022.adoc#v44-22-0[Próximo Capítulo &#62;]