include::./index.adoc[]

[[v44-18-0]]
=== Atos, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-18-1]]

^<<v44-18-1,1>>^ Depois disto, deixando Paulo Atenas, partiu para Corinto.

[[v44-18-2]]

^<<v44-18-2,2>>^ Lá, encontrou certo judeu chamado Áquila, natural do Ponto, recentemente chegado da Itália, com Priscila, sua mulher, em vista de ter Cláudio decretado que todos os judeus se retirassem de Roma. Paulo aproximou-se deles.

[[v44-18-3]]

^<<v44-18-3,3>>^ E, posto que eram do mesmo ofício, passou a morar com eles e ali trabalhava, pois a profissão deles era fazer tendas.

[[v44-18-4]]

^<<v44-18-4,4>>^ E todos os sábados discorria na sinagoga, persuadindo tanto judeus como gregos.

[[v44-18-5]]

^<<v44-18-5,5>>^ Quando Silas e Timóteo desceram da Macedônia, Paulo se entregou totalmente à palavra, testemunhando aos judeus que o Cristo é Jesus.

[[v44-18-6]]

^<<v44-18-6,6>>^ Opondo-se eles e blasfemando, sacudiu Paulo as vestes e disse-lhes: Sobre a vossa cabeça, o vosso sangue! Eu dele estou limpo e, desde agora, vou para os gentios.

[[v44-18-7]]

^<<v44-18-7,7>>^ Saindo dali, entrou na casa de um homem chamado Tício Justo, que era temente a Deus; a casa era contígua à sinagoga.

[[v44-18-8]]

^<<v44-18-8,8>>^ Mas Crispo, o principal da sinagoga, creu no Senhor, com toda a sua casa; também muitos dos coríntios, ouvindo, criam e eram batizados.

[[v44-18-9]]

^<<v44-18-9,9>>^ Teve Paulo durante a noite uma visão em que o Senhor lhe disse: Não temas; pelo contrário, fala e não te cales;

[[v44-18-10]]

^<<v44-18-10,10>>^ porquanto eu estou contigo, e ninguém ousará fazer-te mal, pois tenho muito povo nesta cidade.

[[v44-18-11]]

^<<v44-18-11,11>>^ E ali permaneceu um ano e seis meses, ensinando entre eles a palavra de Deus.

[[v44-18-12]]

^<<v44-18-12,12>>^ Quando, porém, Gálio era procônsul da Acaia, levantaram-se os judeus, concordemente, contra Paulo e o levaram ao tribunal,

[[v44-18-13]]

^<<v44-18-13,13>>^ dizendo: Este persuade os homens a adorar a Deus por modo contrário à lei.

[[v44-18-14]]

^<<v44-18-14,14>>^ Ia Paulo falar, quando Gálio declarou aos judeus: Se fosse, com efeito, alguma injustiça ou crime da maior gravidade, ó judeus, de razão seria atender-vos;

[[v44-18-15]]

^<<v44-18-15,15>>^ mas, se é questão de palavra, de nomes e da vossa lei, tratai disso vós mesmos; eu não quero ser juiz dessas coisas!

[[v44-18-16]]

^<<v44-18-16,16>>^ E os expulsou do tribunal.

[[v44-18-17]]

^<<v44-18-17,17>>^ Então, todos agarraram Sóstenes, o principal da sinagoga, e o espancavam diante do tribunal; Gálio, todavia, não se incomodava com estas coisas.

[[v44-18-18]]

^<<v44-18-18,18>>^ Mas Paulo, havendo permanecido ali ainda muitos dias, por fim, despedindo-se dos irmãos, navegou para a Síria, levando em sua companhia Priscila e Áquila, depois de ter raspado a cabeça em Cencreia, porque tomara voto.

[[v44-18-19]]

^<<v44-18-19,19>>^ Chegados a Éfeso, deixou-os ali; ele, porém, entrando na sinagoga, pregava aos judeus.

[[v44-18-20]]

^<<v44-18-20,20>>^ Rogando-lhe eles que permanecesse ali mais algum tempo, não acedeu.

[[v44-18-21]]

^<<v44-18-21,21>>^ Mas, despedindo-se, disse: Se Deus quiser, voltarei para vós outros. E, embarcando, partiu de Éfeso.

[[v44-18-22]]

^<<v44-18-22,22>>^ Chegando a Cesareia, desembarcou, subindo a Jerusalém; e, tendo saudado a igreja, desceu para Antioquia.

[[v44-18-23]]

^<<v44-18-23,23>>^ Havendo passado ali algum tempo, saiu, atravessando sucessivamente a região da Galácia e Frígia, confirmando todos os discípulos.

[[v44-18-24]]

^<<v44-18-24,24>>^ Nesse meio tempo, chegou a Éfeso um judeu, natural de Alexandria, chamado Apolo, homem eloquente e poderoso nas Escrituras.

[[v44-18-25]]

^<<v44-18-25,25>>^ Era ele instruído no caminho do Senhor; e, sendo fervoroso de espírito, falava e ensinava com precisão a respeito de Jesus, conhecendo apenas o batismo de João.

[[v44-18-26]]

^<<v44-18-26,26>>^ Ele, pois, começou a falar ousadamente na sinagoga. Ouvindo-o, porém, Priscila e Áquila, tomaram-no consigo e, com mais exatidão, lhe expuseram o caminho de Deus.

[[v44-18-27]]

^<<v44-18-27,27>>^ Querendo ele percorrer a Acaia, animaram-no os irmãos e escreveram aos discípulos para o receberem. Tendo chegado, auxiliou muito aqueles que, mediante a graça, haviam crido;

[[v44-18-28]]

^<<v44-18-28,28>>^ porque, com grande poder, convencia publicamente os judeus, provando, por meio das Escrituras, que o Cristo é Jesus.

'''

xref:044-atos/044-atos-017.adoc#v44-17-0[&#60; Capítulo Anterior] | <<v44-18-0,Topo>> | xref:044-atos/044-atos-019.adoc#v44-19-0[Próximo Capítulo &#62;]