include::./index.adoc[]

[[v44-12-0]]
=== Atos, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-12-1]]

^<<v44-12-1,1>>^ Por aquele tempo, mandou o rei Herodes prender alguns da igreja para os maltratar,

[[v44-12-2]]

^<<v44-12-2,2>>^ fazendo passar a fio de espada a Tiago, irmão de João.

[[v44-12-3]]

^<<v44-12-3,3>>^ Vendo ser isto agradável aos judeus, prosseguiu, prendendo também a Pedro. E eram os dias dos pães asmos.

[[v44-12-4]]

^<<v44-12-4,4>>^ Tendo-o feito prender, lançou-o no cárcere, entregando-o a quatro escoltas de quatro soldados cada uma, para o guardarem, tencionando apresentá-lo ao povo depois da Páscoa.

[[v44-12-5]]

^<<v44-12-5,5>>^ Pedro, pois, estava guardado no cárcere; mas havia oração incessante a Deus por parte da igreja a favor dele.

[[v44-12-6]]

^<<v44-12-6,6>>^ Quando Herodes estava para apresentá-lo, naquela mesma noite, Pedro dormia entre dois soldados, acorrentado com duas cadeias, e sentinelas à porta guardavam o cárcere.

[[v44-12-7]]

^<<v44-12-7,7>>^ Eis, porém, que sobreveio um anjo do Senhor, e uma luz iluminou a prisão; e, tocando ele o lado de Pedro, o despertou, dizendo: Levanta-te depressa! Então, as cadeias caíram-lhe das mãos.

[[v44-12-8]]

^<<v44-12-8,8>>^ Disse-lhe o anjo: Cinge-te e calça as sandálias. E ele assim o fez. Disse-lhe mais: Põe a capa e segue-me.

[[v44-12-9]]

^<<v44-12-9,9>>^ Então, saindo, o seguia, não sabendo que era real o que se fazia por meio do anjo; parecia-lhe, antes, uma visão.

[[v44-12-10]]

^<<v44-12-10,10>>^ Depois de terem passado a primeira e a segunda sentinela, chegaram ao portão de ferro que dava para a cidade, o qual se lhes abriu automaticamente; e, saindo, enveredaram por uma rua, e logo adiante o anjo se apartou dele.

[[v44-12-11]]

^<<v44-12-11,11>>^ Então, Pedro, caindo em si, disse: Agora, sei, verdadeiramente, que o Senhor enviou o seu anjo e me livrou da mão de Herodes e de toda a expectativa do povo judaico.

[[v44-12-12]]

^<<v44-12-12,12>>^ Considerando ele a sua situação, resolveu ir à casa de Maria, mãe de João, cognominado Marcos, onde muitas pessoas estavam congregadas e oravam.

[[v44-12-13]]

^<<v44-12-13,13>>^ Quando ele bateu ao postigo do portão, veio uma criada, chamada Rode, ver quem era;

[[v44-12-14]]

^<<v44-12-14,14>>^ reconhecendo a voz de Pedro, tão alegre ficou, que nem o fez entrar, mas voltou correndo para anunciar que Pedro estava junto do portão.

[[v44-12-15]]

^<<v44-12-15,15>>^ Eles lhe disseram: Estás louca. Ela, porém, persistia em afirmar que assim era. Então, disseram: É o seu anjo.

[[v44-12-16]]

^<<v44-12-16,16>>^ Entretanto, Pedro continuava batendo; então, eles abriram, viram-no e ficaram atônitos.

[[v44-12-17]]

^<<v44-12-17,17>>^ Ele, porém, fazendo-lhes sinal com a mão para que se calassem, contou-lhes como o Senhor o tirara da prisão e acrescentou: Anunciai isto a Tiago e aos irmãos. E, saindo, retirou-se para outro lugar.

[[v44-12-18]]

^<<v44-12-18,18>>^ Sendo já dia, houve não pouco alvoroço entre os soldados sobre o que teria acontecido a Pedro.

[[v44-12-19]]

^<<v44-12-19,19>>^ Herodes, tendo-o procurado e não o achando, submetendo as sentinelas a inquérito, ordenou que fossem justiçadas. E, descendo da Judeia para Cesareia, Herodes passou ali algum tempo.

[[v44-12-20]]

^<<v44-12-20,20>>^ Ora, havia séria divergência entre Herodes e os habitantes de Tiro e de Sidom; porém estes, de comum acordo, se apresentaram a ele e, depois de alcançar o favor de Blasto, camarista do rei, pediram reconciliação, porque a sua terra se abastecia do país do rei.

[[v44-12-21]]

^<<v44-12-21,21>>^ Em dia designado, Herodes, vestido de trajo real, assentado no trono, dirigiu-lhes a palavra;

[[v44-12-22]]

^<<v44-12-22,22>>^ e o povo clamava: É voz de um deus, e não de homem!

[[v44-12-23]]

^<<v44-12-23,23>>^ No mesmo instante, um anjo do Senhor o feriu, por ele não haver dado glória a Deus; e, comido de vermes, expirou.

[[v44-12-24]]

^<<v44-12-24,24>>^ Entretanto, a palavra do Senhor crescia e se multiplicava.

[[v44-12-25]]

^<<v44-12-25,25>>^ Barnabé e Saulo, cumprida a sua missão, voltaram de Jerusalém, levando também consigo a João, apelidado Marcos.

'''

xref:044-atos/044-atos-011.adoc#v44-11-0[&#60; Capítulo Anterior] | <<v44-12-0,Topo>> | xref:044-atos/044-atos-013.adoc#v44-13-0[Próximo Capítulo &#62;]