include::./index.adoc[]

[[v44-16-0]]
=== Atos, 16
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-16-1]]

^<<v44-16-1,1>>^ Chegou também a Derbe e a Listra. Havia ali um discípulo chamado Timóteo, filho de uma judia crente, mas de pai grego;

[[v44-16-2]]

^<<v44-16-2,2>>^ dele davam bom testemunho os irmãos em Listra e Icônio.

[[v44-16-3]]

^<<v44-16-3,3>>^ Quis Paulo que ele fosse em sua companhia e, por isso, circuncidou-o por causa dos judeus daqueles lugares; pois todos sabiam que seu pai era grego.

[[v44-16-4]]

^<<v44-16-4,4>>^ Ao passar pelas cidades, entregavam aos irmãos, para que as observassem, as decisões tomadas pelos apóstolos e presbíteros de Jerusalém.

[[v44-16-5]]

^<<v44-16-5,5>>^ Assim, as igrejas eram fortalecidas na fé e, dia a dia, aumentavam em número.

[[v44-16-6]]

^<<v44-16-6,6>>^ E, percorrendo a região frígio-gálata, tendo sido impedidos pelo Espírito Santo de pregar a palavra na Ásia,

[[v44-16-7]]

^<<v44-16-7,7>>^ defrontando Mísia, tentavam ir para Bitínia, mas o Espírito de Jesus não o permitiu.

[[v44-16-8]]

^<<v44-16-8,8>>^ E, tendo contornado Mísia, desceram a Trôade.

[[v44-16-9]]

^<<v44-16-9,9>>^ À noite, sobreveio a Paulo uma visão na qual um varão macedônio estava em pé e lhe rogava, dizendo: Passa à Macedônia e ajuda-nos.

[[v44-16-10]]

^<<v44-16-10,10>>^ Assim que teve a visão, imediatamente, procuramos partir para aquele destino, concluindo que Deus nos havia chamado para lhes anunciar o evangelho.

[[v44-16-11]]

^<<v44-16-11,11>>^ Tendo, pois, navegado de Trôade, seguimos em direitura a Samotrácia, no dia seguinte, a Neápolis

[[v44-16-12]]

^<<v44-16-12,12>>^ e dali, a Filipos, cidade da Macedônia, primeira do distrito e colônia. Nesta cidade, permanecemos alguns dias.

[[v44-16-13]]

^<<v44-16-13,13>>^ No sábado, saímos da cidade para junto do rio, onde nos pareceu haver um lugar de oração; e, assentando-nos, falamos às mulheres que para ali tinham concorrido.

[[v44-16-14]]

^<<v44-16-14,14>>^ Certa mulher, chamada Lídia, da cidade de Tiatira, vendedora de púrpura, temente a Deus, nos escutava; o Senhor lhe abriu o coração para atender às coisas que Paulo dizia.

[[v44-16-15]]

^<<v44-16-15,15>>^ Depois de ser batizada, ela e toda a sua casa, nos rogou, dizendo: Se julgais que eu sou fiel ao Senhor, entrai em minha casa e aí ficai. E nos constrangeu a isso.

[[v44-16-16]]

^<<v44-16-16,16>>^ Aconteceu que, indo nós para o lugar de oração, nos saiu ao encontro uma jovem possessa de espírito adivinhador, a qual, adivinhando, dava grande lucro aos seus senhores.

[[v44-16-17]]

^<<v44-16-17,17>>^ Seguindo a Paulo e a nós, clamava, dizendo: Estes homens são servos do Deus Altíssimo e vos anunciam o caminho da salvação.

[[v44-16-18]]

^<<v44-16-18,18>>^ Isto se repetia por muitos dias. Então, Paulo, já indignado, voltando-se, disse ao espírito: Em nome de Jesus Cristo, eu te mando: retira-te dela. E ele, na mesma hora, saiu.

[[v44-16-19]]

^<<v44-16-19,19>>^ Vendo os seus senhores que se lhes desfizera a esperança do lucro, agarrando em Paulo e Silas, os arrastaram para a praça, à presença das autoridades;

[[v44-16-20]]

^<<v44-16-20,20>>^ e, levando-os aos pretores, disseram: Estes homens, sendo judeus, perturbam a nossa cidade,

[[v44-16-21]]

^<<v44-16-21,21>>^ propagando costumes que não podemos receber, nem praticar, porque somos romanos.

[[v44-16-22]]

^<<v44-16-22,22>>^ Levantou-se a multidão, unida contra eles, e os pretores, rasgando-lhes as vestes, mandaram açoitá-los com varas.

[[v44-16-23]]

^<<v44-16-23,23>>^ E, depois de lhes darem muitos açoites, os lançaram no cárcere, ordenando ao carcereiro que os guardasse com toda a segurança.

[[v44-16-24]]

^<<v44-16-24,24>>^ Este, recebendo tal ordem, levou-os para o cárcere interior e lhes prendeu os pés no tronco.

[[v44-16-25]]

^<<v44-16-25,25>>^ Por volta da meia-noite, Paulo e Silas oravam e cantavam louvores a Deus, e os demais companheiros de prisão escutavam.

[[v44-16-26]]

^<<v44-16-26,26>>^ De repente, sobreveio tamanho terremoto, que sacudiu os alicerces da prisão; abriram-se todas as portas, e soltaram-se as cadeias de todos.

[[v44-16-27]]

^<<v44-16-27,27>>^ O carcereiro despertou do sono e, vendo abertas as portas do cárcere, puxando da espada, ia suicidar-se, supondo que os presos tivessem fugido.

[[v44-16-28]]

^<<v44-16-28,28>>^ Mas Paulo bradou em alta voz: Não te faças nenhum mal, que todos aqui estamos!

[[v44-16-29]]

^<<v44-16-29,29>>^ Então, o carcereiro, tendo pedido uma luz, entrou precipitadamente e, trêmulo, prostrou-se diante de Paulo e Silas.

[[v44-16-30]]

^<<v44-16-30,30>>^ Depois, trazendo-os para fora, disse: Senhores, que devo fazer para que seja salvo?

[[v44-16-31]]

^<<v44-16-31,31>>^ Responderam-lhe: Crê no Senhor Jesus e serás salvo, tu e tua casa.

[[v44-16-32]]

^<<v44-16-32,32>>^ E lhe pregaram a palavra de Deus e a todos os de sua casa.

[[v44-16-33]]

^<<v44-16-33,33>>^ Naquela mesma hora da noite, cuidando deles, lavou-lhes os vergões dos açoites. A seguir, foi ele batizado, e todos os seus.

[[v44-16-34]]

^<<v44-16-34,34>>^ Então, levando-os para a sua própria casa, lhes pôs a mesa; e, com todos os seus, manifestava grande alegria, por terem crido em Deus.

[[v44-16-35]]

^<<v44-16-35,35>>^ Quando amanheceu, os pretores enviaram oficiais de justiça, com a seguinte ordem: Põe aqueles homens em liberdade.

[[v44-16-36]]

^<<v44-16-36,36>>^ Então, o carcereiro comunicou a Paulo estas palavras: Os pretores ordenaram que fôsseis postos em liberdade. Agora, pois, saí e ide em paz.

[[v44-16-37]]

^<<v44-16-37,37>>^ Paulo, porém, lhes replicou: Sem ter havido processo formal contra nós, nos açoitaram publicamente e nos recolheram ao cárcere, sendo nós cidadãos romanos; querem agora, às ocultas, lançar-nos fora? Não será assim; pelo contrário, venham eles e, pessoalmente, nos ponham em liberdade.

[[v44-16-38]]

^<<v44-16-38,38>>^ Os oficiais de justiça comunicaram isso aos pretores; e estes ficaram possuídos de temor, quando souberam que se tratava de cidadãos romanos.

[[v44-16-39]]

^<<v44-16-39,39>>^ Então, foram ter com eles e lhes pediram desculpas; e, relaxando-lhes a prisão, rogaram que se retirassem da cidade.

[[v44-16-40]]

^<<v44-16-40,40>>^ Tendo-se retirado do cárcere, dirigiram-se para a casa de Lídia e, vendo os irmãos, os confortaram. Então, partiram.

'''

xref:044-atos/044-atos-015.adoc#v44-15-0[&#60; Capítulo Anterior] | <<v44-16-0,Topo>> | xref:044-atos/044-atos-017.adoc#v44-17-0[Próximo Capítulo &#62;]