include::./index.adoc[]

[[v44-19-0]]
=== Atos, 19
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-19-1]]

^<<v44-19-1,1>>^ Aconteceu que, estando Apolo em Corinto, Paulo, tendo passado pelas regiões mais altas, chegou a Éfeso e, achando ali alguns discípulos,

[[v44-19-2]]

^<<v44-19-2,2>>^ perguntou-lhes: Recebestes, porventura, o Espírito Santo quando crestes? Ao que lhe responderam: Pelo contrário, nem mesmo ouvimos que existe o Espírito Santo.

[[v44-19-3]]

^<<v44-19-3,3>>^ Então, Paulo perguntou: Em que, pois, fostes batizados? Responderam: No batismo de João.

[[v44-19-4]]

^<<v44-19-4,4>>^ Disse-lhes Paulo: João realizou batismo de arrependimento, dizendo ao povo que cresse naquele que vinha depois dele, a saber, em Jesus.

[[v44-19-5]]

^<<v44-19-5,5>>^ Eles, tendo ouvido isto, foram batizados em o nome do Senhor Jesus.

[[v44-19-6]]

^<<v44-19-6,6>>^ E, impondo-lhes Paulo as mãos, veio sobre eles o Espírito Santo; e tanto falavam em línguas como profetizavam.

[[v44-19-7]]

^<<v44-19-7,7>>^ Eram, ao todo, uns doze homens.

[[v44-19-8]]

^<<v44-19-8,8>>^ Durante três meses, Paulo frequentou a sinagoga, onde falava ousadamente, dissertando e persuadindo com respeito ao reino de Deus.

[[v44-19-9]]

^<<v44-19-9,9>>^ Visto que alguns deles se mostravam empedernidos e descrentes, falando mal do Caminho diante da multidão, Paulo, apartando-se deles, separou os discípulos, passando a discorrer diariamente na escola de Tirano.

[[v44-19-10]]

^<<v44-19-10,10>>^ Durou isto por espaço de dois anos, dando ensejo a que todos os habitantes da Ásia ouvissem a palavra do Senhor, tanto judeus como gregos.

[[v44-19-11]]

^<<v44-19-11,11>>^ E Deus, pelas mãos de Paulo, fazia milagres extraordinários,

[[v44-19-12]]

^<<v44-19-12,12>>^ a ponto de levarem aos enfermos lenços e aventais do seu uso pessoal, diante dos quais as enfermidades fugiam das suas vítimas, e os espíritos malignos se retiravam.

[[v44-19-13]]

^<<v44-19-13,13>>^ E alguns judeus, exorcistas ambulantes, tentaram invocar o nome do Senhor Jesus sobre possessos de espíritos malignos, dizendo: Esconjuro-vos por Jesus, a quem Paulo prega.

[[v44-19-14]]

^<<v44-19-14,14>>^ Os que faziam isto eram sete filhos de um judeu chamado Ceva, sumo sacerdote.

[[v44-19-15]]

^<<v44-19-15,15>>^ Mas o espírito maligno lhes respondeu: Conheço a Jesus e sei quem é Paulo; mas vós, quem sois?

[[v44-19-16]]

^<<v44-19-16,16>>^ E o possesso do espírito maligno saltou sobre eles, subjugando a todos, e, de tal modo prevaleceu contra eles, que, desnudos e feridos, fugiram daquela casa.

[[v44-19-17]]

^<<v44-19-17,17>>^ Chegou este fato ao conhecimento de todos, assim judeus como gregos habitantes de Éfeso; veio temor sobre todos eles, e o nome do Senhor Jesus era engrandecido.

[[v44-19-18]]

^<<v44-19-18,18>>^ Muitos dos que creram vieram confessando e denunciando publicamente as suas próprias obras.

[[v44-19-19]]

^<<v44-19-19,19>>^ Também muitos dos que haviam praticado artes mágicas, reunindo os seus livros, os queimaram diante de todos. Calculados os seus preços, achou-se que montavam a cinquenta mil denários.

[[v44-19-20]]

^<<v44-19-20,20>>^ Assim, a palavra do Senhor crescia e prevalecia poderosamente.

[[v44-19-21]]

^<<v44-19-21,21>>^ Cumpridas estas coisas, Paulo resolveu, no seu espírito, ir a Jerusalém, passando pela Macedônia e Acaia, considerando: Depois de haver estado ali, importa-me ver também Roma.

[[v44-19-22]]

^<<v44-19-22,22>>^ Tendo enviado à Macedônia dois daqueles que lhe ministravam, Timóteo e Erasto, permaneceu algum tempo na Ásia.

[[v44-19-23]]

^<<v44-19-23,23>>^ Por esse tempo, houve grande alvoroço acerca do Caminho.

[[v44-19-24]]

^<<v44-19-24,24>>^ Pois um ourives, chamado Demétrio, que fazia, de prata, nichos de Diana e que dava muito lucro aos artífices,

[[v44-19-25]]

^<<v44-19-25,25>>^ convocando-os juntamente com outros da mesma profissão, disse-lhes: Senhores, sabeis que deste ofício vem a nossa prosperidade

[[v44-19-26]]

^<<v44-19-26,26>>^ e estais vendo e ouvindo que não só em Éfeso, mas em quase toda a Ásia, este Paulo tem persuadido e desencaminhado muita gente, afirmando não serem deuses os que são feitos por mãos humanas.

[[v44-19-27]]

^<<v44-19-27,27>>^ Não somente há o perigo de a nossa profissão cair em descrédito, como também o de o próprio templo da grande deusa, Diana, ser estimado em nada, e ser mesmo destruída a majestade daquela que toda a Ásia e o mundo adoram.

[[v44-19-28]]

^<<v44-19-28,28>>^ Ouvindo isto, encheram-se de furor e clamavam: Grande é a Diana dos efésios!

[[v44-19-29]]

^<<v44-19-29,29>>^ Foi a cidade tomada de confusão, e todos, à uma, arremeteram para o teatro, arrebatando os macedônios Gaio e Aristarco, companheiros de Paulo.

[[v44-19-30]]

^<<v44-19-30,30>>^ Querendo este apresentar-se ao povo, não lhe permitiram os discípulos.

[[v44-19-31]]

^<<v44-19-31,31>>^ Também asiarcas, que eram amigos de Paulo, mandaram rogar-lhe que não se arriscasse indo ao teatro.

[[v44-19-32]]

^<<v44-19-32,32>>^ Uns, pois, gritavam de uma forma; outros, de outra; porque a assembleia caíra em confusão. E, na sua maior parte, nem sabiam por que motivo estavam reunidos.

[[v44-19-33]]

^<<v44-19-33,33>>^ Então, tiraram Alexandre dentre a multidão, impelindo-o os judeus para a frente. Este, acenando com a mão, queria falar ao povo.

[[v44-19-34]]

^<<v44-19-34,34>>^ Quando, porém, reconheceram que ele era judeu, todos, a uma voz, gritaram por espaço de quase duas horas: Grande é a Diana dos efésios!

[[v44-19-35]]

^<<v44-19-35,35>>^ O escrivão da cidade, tendo apaziguado o povo, disse: Senhores, efésios: quem, porventura, não sabe que a cidade de Éfeso é a guardiã do templo da grande Diana e da imagem que caiu de Júpiter?

[[v44-19-36]]

^<<v44-19-36,36>>^ Ora, não podendo isto ser contraditado, convém que vos mantenhais calmos e nada façais precipitadamente;

[[v44-19-37]]

^<<v44-19-37,37>>^ porque estes homens que aqui trouxestes não são sacrílegos, nem blasfemam contra a nossa deusa.

[[v44-19-38]]

^<<v44-19-38,38>>^ Portanto, se Demétrio e os artífices que o acompanham têm alguma queixa contra alguém, há audiências e procônsules; que se acusem uns aos outros.

[[v44-19-39]]

^<<v44-19-39,39>>^ Mas, se alguma outra coisa pleiteais, será decidida em assembleia regular.

[[v44-19-40]]

^<<v44-19-40,40>>^ Porque também corremos perigo de que, por hoje, sejamos acusados de sedição, não havendo motivo algum que possamos alegar para justificar este ajuntamento.

[[v44-19-41]]

^<<v44-19-41,41>>^ E, havendo dito isto, dissolveu a assembleia.

'''

xref:044-atos/044-atos-018.adoc#v44-18-0[&#60; Capítulo Anterior] | <<v44-19-0,Topo>> | xref:044-atos/044-atos-020.adoc#v44-20-0[Próximo Capítulo &#62;]