include::./index.adoc[]

[[v44-27-0]]
=== Atos, 27
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-27-1]]

^<<v44-27-1,1>>^ Quando foi decidido que navegássemos para a Itália, entregaram Paulo e alguns outros presos a um centurião chamado Júlio, da Coorte Imperial.

[[v44-27-2]]

^<<v44-27-2,2>>^ Embarcando num navio adramitino, que estava de partida para costear a Ásia, fizemo-nos ao mar, indo conosco Aristarco, macedônio de Tessalônica.

[[v44-27-3]]

^<<v44-27-3,3>>^ No dia seguinte, chegamos a Sidom, e Júlio, tratando Paulo com humanidade, permitiu-lhe ir ver os amigos e obter assistência.

[[v44-27-4]]

^<<v44-27-4,4>>^ Partindo dali, navegamos sob a proteção de Chipre, por serem contrários os ventos;

[[v44-27-5]]

^<<v44-27-5,5>>^ e, tendo atravessado o mar ao longo da Cilícia e Panfília, chegamos a Mirra, na Lícia.

[[v44-27-6]]

^<<v44-27-6,6>>^ Achando ali o centurião um navio de Alexandria, que estava de partida para a Itália, nele nos fez embarcar.

[[v44-27-7]]

^<<v44-27-7,7>>^ Navegando vagarosamente muitos dias e tendo chegado com dificuldade defronte de Cnido, não nos sendo permitido prosseguir, por causa do vento contrário, navegamos sob a proteção de Creta, na altura de Salmona.

[[v44-27-8]]

^<<v44-27-8,8>>^ Costeando-a, penosamente, chegamos a um lugar chamado Bons Portos, perto do qual estava a cidade de Laseia.

[[v44-27-9]]

^<<v44-27-9,9>>^ Depois de muito tempo, tendo-se tornado a navegação perigosa, e já passado o tempo do Dia do Jejum, admoestava-os Paulo,

[[v44-27-10]]

^<<v44-27-10,10>>^ dizendo-lhes: Senhores, vejo que a viagem vai ser trabalhosa, com dano e muito prejuízo, não só da carga e do navio, mas também da nossa vida.

[[v44-27-11]]

^<<v44-27-11,11>>^ Mas o centurião dava mais crédito ao piloto e ao mestre do navio do que ao que Paulo dizia.

[[v44-27-12]]

^<<v44-27-12,12>>^ Não sendo o porto próprio para invernar, a maioria deles era de opinião que partissem dali, para ver se podiam chegar a Fenice e aí passar o inverno, visto ser um porto de Creta, o qual olhava para o nordeste e para o sudeste.

[[v44-27-13]]

^<<v44-27-13,13>>^ Soprando brandamente o vento sul, e pensando eles ter alcançado o que desejavam, levantaram âncora e foram costeando mais de perto a ilha de Creta.

[[v44-27-14]]

^<<v44-27-14,14>>^ Entretanto, não muito depois, desencadeou-se, do lado da ilha, um tufão de vento, chamado Euroaquilão;

[[v44-27-15]]

^<<v44-27-15,15>>^ e, sendo o navio arrastado com violência, sem poder resistir ao vento, cessamos a manobra e nos fomos deixando levar.

[[v44-27-16]]

^<<v44-27-16,16>>^ Passando sob a proteção de uma ilhota chamada Cauda, a custo conseguimos recolher o bote;

[[v44-27-17]]

^<<v44-27-17,17>>^ e, levantando este, usaram de todos os meios para cingir o navio, e, temendo que dessem na Sirte, arriaram os aparelhos, e foram ao léu.

[[v44-27-18]]

^<<v44-27-18,18>>^ Açoitados severamente pela tormenta, no dia seguinte, já aliviavam o navio.

[[v44-27-19]]

^<<v44-27-19,19>>^ E, ao terceiro dia, nós mesmos, com as próprias mãos, lançamos ao mar a armação do navio.

[[v44-27-20]]

^<<v44-27-20,20>>^ E, não aparecendo, havia já alguns dias, nem sol nem estrelas, caindo sobre nós grande tempestade, dissipou-se, afinal, toda a esperança de salvamento.

[[v44-27-21]]

^<<v44-27-21,21>>^ Havendo todos estado muito tempo sem comer, Paulo, pondo-se em pé no meio deles, disse: Senhores, na verdade, era preciso terem-me atendido e não partir de Creta, para evitar este dano e perda.

[[v44-27-22]]

^<<v44-27-22,22>>^ Mas, já agora, vos aconselho bom ânimo, porque nenhuma vida se perderá de entre vós, mas somente o navio.

[[v44-27-23]]

^<<v44-27-23,23>>^ Porque, esta mesma noite, um anjo de Deus, de quem eu sou e a quem sirvo, esteve comigo,

[[v44-27-24]]

^<<v44-27-24,24>>^ dizendo: Paulo, não temas! É preciso que compareças perante César, e eis que Deus, por sua graça, te deu todos quantos navegam contigo.

[[v44-27-25]]

^<<v44-27-25,25>>^ Portanto, senhores, tende bom ânimo! Pois eu confio em Deus que sucederá do modo por que me foi dito.

[[v44-27-26]]

^<<v44-27-26,26>>^ Porém é necessário que vamos dar a uma ilha.

[[v44-27-27]]

^<<v44-27-27,27>>^ Quando chegou a décima quarta noite, sendo nós batidos de um lado para outro no mar Adriático, por volta da meia-noite, pressentiram os marinheiros que se aproximavam de alguma terra.

[[v44-27-28]]

^<<v44-27-28,28>>^ E, lançando o prumo, acharam vinte braças; passando um pouco mais adiante, tornando a lançar o prumo, acharam quinze braças.

[[v44-27-29]]

^<<v44-27-29,29>>^ E, receosos de que fôssemos atirados contra lugares rochosos, lançaram da popa quatro âncoras e oravam para que rompesse o dia.

[[v44-27-30]]

^<<v44-27-30,30>>^ Procurando os marinheiros fugir do navio, e, tendo arriado o bote no mar, a pretexto de que estavam para largar âncoras da proa,

[[v44-27-31]]

^<<v44-27-31,31>>^ disse Paulo ao centurião e aos soldados: Se estes não permanecerem a bordo, vós não podereis salvar-vos.

[[v44-27-32]]

^<<v44-27-32,32>>^ Então, os soldados cortaram os cabos do bote e o deixaram afastar-se.

[[v44-27-33]]

^<<v44-27-33,33>>^ Enquanto amanhecia, Paulo rogava a todos que se alimentassem, dizendo: Hoje, é o décimo quarto dia em que, esperando, estais sem comer, nada tendo provado.

[[v44-27-34]]

^<<v44-27-34,34>>^ Eu vos rogo que comais alguma coisa; porque disto depende a vossa segurança; pois nenhum de vós perderá nem mesmo um fio de cabelo.

[[v44-27-35]]

^<<v44-27-35,35>>^ Tendo dito isto, tomando um pão, deu graças a Deus na presença de todos e, depois de o partir, começou a comer.

[[v44-27-36]]

^<<v44-27-36,36>>^ Todos cobraram ânimo e se puseram também a comer.

[[v44-27-37]]

^<<v44-27-37,37>>^ Estávamos no navio duzentas e setenta e seis pessoas ao todo.

[[v44-27-38]]

^<<v44-27-38,38>>^ Refeitos com a comida, aliviaram o navio, lançando o trigo ao mar.

[[v44-27-39]]

^<<v44-27-39,39>>^ Quando amanheceu, não reconheceram a terra, mas avistaram uma enseada, onde havia praia; então, consultaram entre si se não podiam encalhar ali o navio.

[[v44-27-40]]

^<<v44-27-40,40>>^ Levantando as âncoras, deixaram-no ir ao mar, largando também as amarras do leme; e, alçando a vela de proa ao vento, dirigiram-se para a praia.

[[v44-27-41]]

^<<v44-27-41,41>>^ Dando, porém, num lugar onde duas correntes se encontravam, encalharam ali o navio; a proa encravou-se e ficou imóvel, mas a popa se abria pela violência do mar.

[[v44-27-42]]

^<<v44-27-42,42>>^ O parecer dos soldados era que matassem os presos, para que nenhum deles, nadando, fugisse;

[[v44-27-43]]

^<<v44-27-43,43>>^ mas o centurião, querendo salvar a Paulo, impediu-os de o fazer; e ordenou que os que soubessem nadar fossem os primeiros a lançar-se ao mar e alcançar a terra.

[[v44-27-44]]

^<<v44-27-44,44>>^ Quanto aos demais, que se salvassem, uns, em tábuas, e outros, em destroços do navio. E foi assim que todos se salvaram em terra.

'''

xref:044-atos/044-atos-026.adoc#v44-26-0[&#60; Capítulo Anterior] | <<v44-27-0,Topo>> | xref:044-atos/044-atos-028.adoc#v44-28-0[Próximo Capítulo &#62;]