include::./index.adoc[]

[[v44-25-0]]
=== Atos, 25
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-25-1]]

^<<v44-25-1,1>>^ Tendo, pois, Festo assumido o governo da província, três dias depois, subiu de Cesareia para Jerusalém;

[[v44-25-2]]

^<<v44-25-2,2>>^ e, logo, os principais sacerdotes e os maiorais dos judeus lhe apresentaram queixa contra Paulo e lhe solicitavam,

[[v44-25-3]]

^<<v44-25-3,3>>^ pedindo como favor, em detrimento de Paulo, que o mandasse vir a Jerusalém, armando eles cilada para o matarem na estrada.

[[v44-25-4]]

^<<v44-25-4,4>>^ Festo, porém, respondeu achar-se Paulo detido em Cesareia; e que ele mesmo, muito em breve, partiria para lá.

[[v44-25-5]]

^<<v44-25-5,5>>^ Portanto, disse ele, os que dentre vós estiverem habilitados que desçam comigo; e, havendo contra este homem qualquer crime, acusem-no.

[[v44-25-6]]

^<<v44-25-6,6>>^ E, não se demorando entre eles mais de oito ou dez dias, desceu para Cesareia; e, no dia seguinte, assentando-se no tribunal, ordenou que Paulo fosse trazido.

[[v44-25-7]]

^<<v44-25-7,7>>^ Comparecendo este, rodearam-no os judeus que haviam descido de Jerusalém, trazendo muitas e graves acusações contra ele, as quais, entretanto, não podiam provar.

[[v44-25-8]]

^<<v44-25-8,8>>^ Paulo, porém, defendendo-se, proferiu as seguintes palavras: Nenhum pecado cometi contra a lei dos judeus, nem contra o templo, nem contra César.

[[v44-25-9]]

^<<v44-25-9,9>>^ Então, Festo, querendo assegurar o apoio dos judeus, respondeu a Paulo: Queres tu subir a Jerusalém e ser ali julgado por mim a respeito destas coisas?

[[v44-25-10]]

^<<v44-25-10,10>>^ Disse-lhe Paulo: Estou perante o tribunal de César, onde convém seja eu julgado; nenhum agravo pratiquei contra os judeus, como tu muito bem sabes.

[[v44-25-11]]

^<<v44-25-11,11>>^ Caso, pois, tenha eu praticado algum mal ou crime digno de morte, estou pronto para morrer; se, pelo contrário, não são verdadeiras as coisas de que me acusam, ninguém, para lhes ser agradável, pode entregar-me a eles. Apelo para César.

[[v44-25-12]]

^<<v44-25-12,12>>^ Então, Festo, tendo falado com o conselho, respondeu: Para César apelaste, para César irás.

[[v44-25-13]]

^<<v44-25-13,13>>^ Passados alguns dias, o rei Agripa e Berenice chegaram a Cesareia a fim de saudar a Festo.

[[v44-25-14]]

^<<v44-25-14,14>>^ Como se demorassem ali alguns dias, Festo expôs ao rei o caso de Paulo, dizendo: Félix deixou aqui preso certo homem,

[[v44-25-15]]

^<<v44-25-15,15>>^ a respeito de quem os principais sacerdotes e os anciãos dos judeus apresentaram queixa, estando eu em Jerusalém, pedindo que o condenasse.

[[v44-25-16]]

^<<v44-25-16,16>>^ A eles respondi que não é costume dos romanos condenar quem quer que seja, sem que o acusado tenha presentes os seus acusadores e possa defender-se da acusação.

[[v44-25-17]]

^<<v44-25-17,17>>^ De sorte que, chegando eles aqui juntos, sem nenhuma demora, no dia seguinte, assentando-me no tribunal, determinei fosse trazido o homem;

[[v44-25-18]]

^<<v44-25-18,18>>^ e, levantando-se os acusadores, nenhum delito referiram dos crimes de que eu suspeitava.

[[v44-25-19]]

^<<v44-25-19,19>>^ Traziam contra ele algumas questões referentes à sua própria religião e particularmente a certo morto, chamado Jesus, que Paulo afirmava estar vivo.

[[v44-25-20]]

^<<v44-25-20,20>>^ Estando eu perplexo quanto ao modo de investigar estas coisas, perguntei-lhe se queria ir a Jerusalém para ser ali julgado a respeito disso.

[[v44-25-21]]

^<<v44-25-21,21>>^ Mas, havendo Paulo apelado para que ficasse em custódia para o julgamento de César, ordenei que o acusado continuasse detido até que eu o enviasse a César.

[[v44-25-22]]

^<<v44-25-22,22>>^ Então, Agripa disse a Festo: Eu também gostaria de ouvir este homem. Amanhã, respondeu ele, o ouvirás.

[[v44-25-23]]

^<<v44-25-23,23>>^ De fato, no dia seguinte, vindo Agripa e Berenice, com grande pompa, tendo eles entrado na audiência juntamente com oficiais superiores e homens eminentes da cidade, Paulo foi trazido por ordem de Festo.

[[v44-25-24]]

^<<v44-25-24,24>>^ Então, disse Festo: Rei Agripa e todos vós que estais presentes conosco, vedes este homem, por causa de quem toda a multidão dos judeus recorreu a mim tanto em Jerusalém como aqui, clamando que não convinha que ele vivesse mais.

[[v44-25-25]]

^<<v44-25-25,25>>^ Porém eu achei que ele nada praticara passível de morte; entretanto, tendo ele apelado para o imperador, resolvi mandá-lo ao imperador.

[[v44-25-26]]

^<<v44-25-26,26>>^ Contudo, a respeito dele, nada tenho de positivo que escreva ao soberano; por isso, eu o trouxe à vossa presença e, mormente, à tua, ó rei Agripa, para que, feita a arguição, tenha eu alguma coisa que escrever;

[[v44-25-27]]

^<<v44-25-27,27>>^ porque não me parece razoável remeter um preso sem mencionar, ao mesmo tempo, as acusações que militam contra ele.

'''

xref:044-atos/044-atos-024.adoc#v44-24-0[&#60; Capítulo Anterior] | <<v44-25-0,Topo>> | xref:044-atos/044-atos-026.adoc#v44-26-0[Próximo Capítulo &#62;]