include::./index.adoc[]

[[v44-3-0]]
=== Atos, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v44-3-1]]

^<<v44-3-1,1>>^ Pedro e João subiam ao templo para a oração da hora nona.

[[v44-3-2]]

^<<v44-3-2,2>>^ Era levado um homem, coxo de nascença, o qual punham diariamente à porta do templo chamada Formosa, para pedir esmola aos que entravam.

[[v44-3-3]]

^<<v44-3-3,3>>^ Vendo ele a Pedro e João, que iam entrar no templo, implorava que lhe dessem uma esmola.

[[v44-3-4]]

^<<v44-3-4,4>>^ Pedro, fitando-o, juntamente com João, disse: Olha para nós.

[[v44-3-5]]

^<<v44-3-5,5>>^ Ele os olhava atentamente, esperando receber alguma coisa.

[[v44-3-6]]

^<<v44-3-6,6>>^ Pedro, porém, lhe disse: Não possuo nem prata nem ouro, mas o que tenho, isso te dou: em nome de Jesus Cristo, o Nazareno, anda!

[[v44-3-7]]

^<<v44-3-7,7>>^ E, tomando-o pela mão direita, o levantou; imediatamente, os seus pés e tornozelos se firmaram;

[[v44-3-8]]

^<<v44-3-8,8>>^ de um salto se pôs em pé, passou a andar e entrou com eles no templo, saltando e louvando a Deus.

[[v44-3-9]]

^<<v44-3-9,9>>^ Viu-o todo o povo a andar e a louvar a Deus,

[[v44-3-10]]

^<<v44-3-10,10>>^ e reconheceram ser ele o mesmo que esmolava, assentado à Porta Formosa do templo; e se encheram de admiração e assombro por isso que lhe acontecera.

[[v44-3-11]]

^<<v44-3-11,11>>^ Apegando-se ele a Pedro e a João, todo o povo correu atônito para junto deles no pórtico chamado de Salomão.

[[v44-3-12]]

^<<v44-3-12,12>>^ À vista disto, Pedro se dirigiu ao povo, dizendo: Israelitas, por que vos maravilhais disto ou por que fitais os olhos em nós como se pelo nosso próprio poder ou piedade o tivéssemos feito andar?

[[v44-3-13]]

^<<v44-3-13,13>>^ O Deus de Abraão, de Isaque e de Jacó, o Deus de nossos pais, glorificou a seu Servo Jesus, a quem vós traístes e negastes perante Pilatos, quando este havia decidido soltá-lo.

[[v44-3-14]]

^<<v44-3-14,14>>^ Vós, porém, negastes o Santo e o Justo e pedistes que vos concedessem um homicida.

[[v44-3-15]]

^<<v44-3-15,15>>^ Dessarte, matastes o Autor da vida, a quem Deus ressuscitou dentre os mortos, do que nós somos testemunhas.

[[v44-3-16]]

^<<v44-3-16,16>>^ Pela fé em o nome de Jesus, é que esse mesmo nome fortaleceu a este homem que agora vedes e reconheceis; sim, a fé que vem por meio de Jesus deu a este saúde perfeita na presença de todos vós.

[[v44-3-17]]

^<<v44-3-17,17>>^ E agora, irmãos, eu sei que o fizestes por ignorância, como também as vossas autoridades;

[[v44-3-18]]

^<<v44-3-18,18>>^ mas Deus, assim, cumpriu o que dantes anunciara por boca de todos os profetas: que o seu Cristo havia de padecer.

[[v44-3-19]]

^<<v44-3-19,19>>^ Arrependei-vos, pois, e convertei-vos para serem cancelados os vossos pecados,

[[v44-3-20]]

^<<v44-3-20,20>>^ a fim de que, da presença do Senhor, venham tempos de refrigério, e que envie ele o Cristo, que já vos foi designado, Jesus,

[[v44-3-21]]

^<<v44-3-21,21>>^ ao qual é necessário que o céu receba até aos tempos da restauração de todas as coisas, de que Deus falou por boca dos seus santos profetas desde a antiguidade.

[[v44-3-22]]

^<<v44-3-22,22>>^ Disse, na verdade, Moisés: O Senhor Deus vos suscitará dentre vossos irmãos um profeta semelhante a mim; a ele ouvireis em tudo quanto vos disser.

[[v44-3-23]]

^<<v44-3-23,23>>^ Acontecerá que toda alma que não ouvir a esse profeta será exterminada do meio do povo.

[[v44-3-24]]

^<<v44-3-24,24>>^ E todos os profetas, a começar com Samuel, assim como todos quantos depois falaram, também anunciaram estes dias.

[[v44-3-25]]

^<<v44-3-25,25>>^ Vós sois os filhos dos profetas e da aliança que Deus estabeleceu com vossos pais, dizendo a Abraão: Na tua descendência, serão abençoadas todas as nações da terra.

[[v44-3-26]]

^<<v44-3-26,26>>^ Tendo Deus ressuscitado o seu Servo, enviou-o primeiramente a vós outros para vos abençoar, no sentido de que cada um se aparte das suas perversidades.

'''

xref:044-atos/044-atos-002.adoc#v44-2-0[&#60; Capítulo Anterior] | <<v44-3-0,Topo>> | xref:044-atos/044-atos-004.adoc#v44-4-0[Próximo Capítulo &#62;]