include::./index.adoc[]

[[v14-7-0]]
=== 2 Crônicas, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-7-1]]

^<<v14-7-1,1>>^ Tendo Salomão acabado de orar, desceu fogo do céu e consumiu o holocausto e os sacrifícios; e a glória do SENHOR encheu a casa.

[[v14-7-2]]

^<<v14-7-2,2>>^ Os sacerdotes não podiam entrar na Casa do SENHOR, porque a glória do SENHOR tinha enchido a Casa do SENHOR.

[[v14-7-3]]

^<<v14-7-3,3>>^ Todos os filhos de Israel, vendo descer o fogo e a glória do SENHOR sobre a casa, se encurvaram com o rosto em terra sobre o pavimento, e adoraram, e louvaram o SENHOR, porque é bom, porque a sua misericórdia dura para sempre.

[[v14-7-4]]

^<<v14-7-4,4>>^ Então, o rei e todo o povo ofereceram sacrifícios diante do SENHOR.

[[v14-7-5]]

^<<v14-7-5,5>>^ Ofereceu o rei Salomão em sacrifício vinte e dois mil bois e cento e vinte mil ovelhas.

[[v14-7-6]]

^<<v14-7-6,6>>^ Assim, o rei e todo o povo consagraram a Casa de Deus. Os sacerdotes estavam nos seus devidos lugares, como também os levitas com os instrumentos músicos do SENHOR, que o rei Davi tinha feito para deles se utilizar nas ações de graças ao SENHOR, porque a sua misericórdia dura para sempre. Os sacerdotes que tocavam as trombetas estavam defronte deles, e todo o Israel se mantinha em pé.

[[v14-7-7]]

^<<v14-7-7,7>>^ Salomão consagrou também o meio do átrio que estava diante da Casa do SENHOR, porquanto ali prepararam os holocaustos e a gordura dos sacrifícios pacíficos; porque, no altar de bronze, que Salomão fizera, não podiam caber os holocaustos, as ofertas de manjares e a gordura dos sacrifícios pacíficos.

[[v14-7-8]]

^<<v14-7-8,8>>^ Assim, celebrou Salomão a festa por sete dias, e todo o Israel, com ele, uma grande congregação, desde a entrada de Hamate até ao rio do Egito.

[[v14-7-9]]

^<<v14-7-9,9>>^ Ao oitavo dia, começaram a celebrar a Festa dos Tabernáculos, porque, por sete dias, já haviam celebrado a consagração do altar; a festa durava sete dias.

[[v14-7-10]]

^<<v14-7-10,10>>^ No vigésimo terceiro dia do sétimo mês, o rei despediu o povo para as suas tendas; e todos se foram alegres e de coração contente por causa do bem que o SENHOR fizera a Davi, a Salomão e a Israel, seu povo.

[[v14-7-11]]

^<<v14-7-11,11>>^ Assim, Salomão acabou a Casa do SENHOR e a casa do rei; tudo quanto Salomão intentou fazer na Casa do SENHOR e na sua casa, prosperamente o efetuou.

[[v14-7-12]]

^<<v14-7-12,12>>^ De noite, apareceu o SENHOR a Salomão e lhe disse: Ouvi a tua oração e escolhi para mim este lugar para casa do sacrifício.

[[v14-7-13]]

^<<v14-7-13,13>>^ Se eu cerrar os céus de modo que não haja chuva, ou se ordenar aos gafanhotos que consumam a terra, ou se enviar a peste entre o meu povo;

[[v14-7-14]]

^<<v14-7-14,14>>^ se o meu povo, que se chama pelo meu nome, se humilhar, e orar, e me buscar, e se converter dos seus maus caminhos, então, eu ouvirei dos céus, perdoarei os seus pecados e sararei a sua terra.

[[v14-7-15]]

^<<v14-7-15,15>>^ Estarão abertos os meus olhos e atentos os meus ouvidos à oração que se fizer neste lugar.

[[v14-7-16]]

^<<v14-7-16,16>>^ Porque escolhi e santifiquei esta casa, para que nela esteja o meu nome perpetuamente; nela, estarão fixos os meus olhos e o meu coração todos os dias.

[[v14-7-17]]

^<<v14-7-17,17>>^ Quanto a ti, se andares diante de mim, como andou Davi, teu pai, e fizeres segundo tudo o que te ordenei, e guardares os meus estatutos e os meus juízos,

[[v14-7-18]]

^<<v14-7-18,18>>^ também confirmarei o trono do teu reino, segundo a aliança que fiz com Davi, teu pai, dizendo: Não te faltará sucessor que domine em Israel.

[[v14-7-19]]

^<<v14-7-19,19>>^ Porém, se vós vos desviardes, e deixardes os meus estatutos e os meus mandamentos, que vos prescrevi, e fordes, e servirdes a outros deuses, e os adorardes,

[[v14-7-20]]

^<<v14-7-20,20>>^ então, vos arrancarei da minha terra que vos dei, e esta casa, que santifiquei ao meu nome, lançarei longe da minha presença, e a tornarei em provérbio e motejo entre todos os povos.

[[v14-7-21]]

^<<v14-7-21,21>>^ Desta casa, agora tão exaltada, todo aquele que por ela passar pasmará e dirá: Por que procedeu o SENHOR assim para com esta terra e esta casa?

[[v14-7-22]]

^<<v14-7-22,22>>^ Responder-se-lhe-á: Porque deixaram o SENHOR, o Deus de seus pais, que os tirou da terra do Egito, e se apegaram a outros deuses, e os adoraram, e os serviram. Por isso, trouxe sobre eles todo este mal.

'''

xref:014-2-cronicas/014-2-cronicas-006.adoc#v14-6-0[&#60; Capítulo Anterior] | <<v14-7-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-008.adoc#v14-8-0[Próximo Capítulo &#62;]