include::./index.adoc[]

[[v14-12-0]]
=== 2 Crônicas, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-12-1]]

^<<v14-12-1,1>>^ Tendo Roboão confirmado o reino e havendo-se fortalecido, deixou a lei do SENHOR, e, com ele, todo o Israel.

[[v14-12-2]]

^<<v14-12-2,2>>^ No ano quinto do rei Roboão, Sisaque, rei do Egito, subiu contra Jerusalém (porque tinham transgredido contra o SENHOR),

[[v14-12-3]]

^<<v14-12-3,3>>^ com mil e duzentos carros e sessenta mil cavaleiros; era inumerável a gente que vinha com ele do Egito, de líbios, suquitas e etíopes.

[[v14-12-4]]

^<<v14-12-4,4>>^ Tomou as cidades fortificadas que pertenciam a Judá e veio a Jerusalém.

[[v14-12-5]]

^<<v14-12-5,5>>^ Então, veio Semaías, o profeta, a Roboão e aos príncipes de Judá, que, por causa de Sisaque, se ajuntaram em Jerusalém, e disse-lhes: Assim diz o SENHOR: Vós me deixastes a mim, pelo que eu também vos deixei em poder de Sisaque.

[[v14-12-6]]

^<<v14-12-6,6>>^ Então, se humilharam os príncipes de Israel e o rei e disseram: O SENHOR é justo.

[[v14-12-7]]

^<<v14-12-7,7>>^ Vendo, pois, o SENHOR que se humilharam, veio a palavra do SENHOR a Semaías, dizendo: Humilharam-se, não os destruirei; antes, em breve lhes darei socorro, para que o meu furor não se derrame sobre Jerusalém, por intermédio de Sisaque.

[[v14-12-8]]

^<<v14-12-8,8>>^ Porém serão seus servos, para que conheçam a diferença entre a minha servidão e a servidão dos reinos da terra.

[[v14-12-9]]

^<<v14-12-9,9>>^ Subiu, pois, Sisaque, rei do Egito, contra Jerusalém e tomou os tesouros da Casa do SENHOR e os tesouros da casa do rei; tomou tudo. Também levou todos os escudos de ouro que Salomão tinha feito.

[[v14-12-10]]

^<<v14-12-10,10>>^ Em lugar destes fez o rei Roboão escudos de bronze e os entregou nas mãos dos capitães da guarda, que guardavam a porta da casa do rei.

[[v14-12-11]]

^<<v14-12-11,11>>^ Toda vez que o rei entrava na Casa do SENHOR, os da guarda vinham, e usavam os escudos, e tornavam a trazê-los para a câmara da guarda.

[[v14-12-12]]

^<<v14-12-12,12>>^ Tendo-se ele humilhado, apartou-se dele a ira do SENHOR para que não o destruísse de todo; porque em Judá ainda havia boas coisas.

[[v14-12-13]]

^<<v14-12-13,13>>^ Fortificou-se, pois, o rei Roboão em Jerusalém e continuou reinando. Tinha Roboão quarenta e um anos de idade quando começou a reinar e reinou dezessete anos em Jerusalém, cidade que o SENHOR escolheu dentre todas as tribos de Israel, para ali estabelecer o seu nome. Sua mãe se chamava Naamá, amonita.

[[v14-12-14]]

^<<v14-12-14,14>>^ Fez ele o que era mau, porquanto não dispôs o coração para buscar ao SENHOR.

[[v14-12-15]]

^<<v14-12-15,15>>^ Quanto aos mais atos de Roboão, tanto os primeiros como os últimos, porventura, não estão escritos no Livro da História de Semaías, o profeta, e no de Ido, o vidente, no registro das genealogias? Houve guerras entre Roboão e Jeroboão todos os seus dias.

[[v14-12-16]]

^<<v14-12-16,16>>^ Descansou Roboão com seus pais e foi sepultado na Cidade de Davi; e Abias, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-011.adoc#v14-11-0[&#60; Capítulo Anterior] | <<v14-12-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-013.adoc#v14-13-0[Próximo Capítulo &#62;]