include::./index.adoc[]

[[v14-18-0]]
=== 2 Crônicas, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-18-1]]

^<<v14-18-1,1>>^ Tinha Josafá riquezas e glória em abundância; e aparentou-se com Acabe.

[[v14-18-2]]

^<<v14-18-2,2>>^ Ao cabo de alguns anos, foi ter com Acabe, em Samaria. Acabe matou ovelhas e bois em abundância, para ele e para o povo que viera com ele; e o persuadiu a subir, com ele, a Ramote-Gileade.

[[v14-18-3]]

^<<v14-18-3,3>>^ Acabe, rei de Israel, perguntou a Josafá, rei de Judá: Irás tu, comigo, a Ramote-Gileade? Respondeu-lhe Josafá: Serei como tu és, o meu povo, como o teu povo; iremos, contigo, à peleja.

[[v14-18-4]]

^<<v14-18-4,4>>^ Disse mais Josafá ao rei de Israel: Consulta, primeiro, a palavra do SENHOR.

[[v14-18-5]]

^<<v14-18-5,5>>^ Então, o rei de Israel ajuntou os profetas, quatrocentos homens, e lhes disse: Iremos à peleja contra Ramote-Gileade ou deixarei de ir? Eles disseram:

[[v14-18-6]]

^<<v14-18-6,6>>^ Sobe, porque Deus a entregará nas mãos do rei. Disse, porém, Josafá: Não há, aqui, ainda algum profeta do SENHOR, para o consultarmos?

[[v14-18-7]]

^<<v14-18-7,7>>^ Respondeu o rei de Israel a Josafá: Há um ainda, por quem podemos consultar o SENHOR; porém eu o aborreço, porque nunca profetiza de mim o que é bom, mas somente o que é mau.

[[v14-18-8]]

^<<v14-18-8,8>>^ Este é Micaías, filho de Inlá. Disse Josafá: Não fale o rei assim. Então, o rei de Israel chamou um oficial e disse: Traze-me depressa a Micaías, filho de Inlá.

[[v14-18-9]]

^<<v14-18-9,9>>^ O rei de Israel e Josafá, rei de Judá, estavam assentados, cada um no seu trono, vestidos de trajes reais, numa eira à entrada da porta de Samaria; e todos os profetas profetizavam diante deles.

[[v14-18-10]]

^<<v14-18-10,10>>^ Zedequias, filho de Quenaana, fez para si uns chifres de ferro e disse: Assim diz o SENHOR: Com este, escornearás os siros, até de todo os consumir.

[[v14-18-11]]

^<<v14-18-11,11>>^ Todos os profetas profetizaram assim, dizendo: Sobe a Ramote-Gileade e triunfarás, porque o SENHOR a entregará nas mãos do rei.

[[v14-18-12]]

^<<v14-18-12,12>>^ O mensageiro que fora chamar a Micaías falou-lhe, dizendo: Eis que as palavras dos profetas, a uma voz, predizem coisas boas para o rei; seja, pois, a tua palavra como a palavra de um deles, e fala o que é bom.

[[v14-18-13]]

^<<v14-18-13,13>>^ Respondeu Micaías: Tão certo como vive o SENHOR, o que meu Deus me disser, isso falarei.

[[v14-18-14]]

^<<v14-18-14,14>>^ E, vindo ele ao rei, este lhe perguntou: Micaías, iremos a Ramote-Gileade, à peleja, ou deixarei de ir? Ele respondeu: Sobe e triunfarás, porque eles serão entregues nas vossas mãos.

[[v14-18-15]]

^<<v14-18-15,15>>^ O rei lhe disse: Quantas vezes te conjurarei que não me fales senão a verdade em nome do SENHOR?

[[v14-18-16]]

^<<v14-18-16,16>>^ Então, disse ele: Vi todo o Israel disperso pelos montes, como ovelhas que não têm pastor; e disse o SENHOR: Estes não têm dono; torne cada um em paz para sua casa.

[[v14-18-17]]

^<<v14-18-17,17>>^ Então, o rei de Israel disse a Josafá: Não te disse eu que ele não profetiza a meu respeito o que é bom, mas somente o que é mau?

[[v14-18-18]]

^<<v14-18-18,18>>^ Micaías prosseguiu: Ouvi, pois, a palavra do SENHOR: Vi o SENHOR assentado no seu trono, e todo o exército do céu estava à sua direita e à sua esquerda.

[[v14-18-19]]

^<<v14-18-19,19>>^ Perguntou o SENHOR: Quem enganará Acabe, o rei de Israel, para que suba e caia em Ramote-Gileade? Um dizia desta maneira, e outro, de outra.

[[v14-18-20]]

^<<v14-18-20,20>>^ Então, saiu um espírito, e se apresentou diante do SENHOR, e disse: Eu o enganarei. Perguntou-lhe o SENHOR: Com quê?

[[v14-18-21]]

^<<v14-18-21,21>>^ Respondeu ele: Sairei e serei espírito mentiroso na boca de todos os seus profetas. Disse o SENHOR: Tu o enganarás e ainda prevalecerás; sai e faze-o assim.

[[v14-18-22]]

^<<v14-18-22,22>>^ Eis que o SENHOR pôs o espírito mentiroso na boca de todos estes teus profetas e o SENHOR falou o que é mau contra ti.

[[v14-18-23]]

^<<v14-18-23,23>>^ Então, Zedequias, filho de Quenaana, deu uma bofetada em Micaías e disse:

[[v14-18-24]]

^<<v14-18-24,24>>^ Por onde saiu o Espírito do SENHOR para falar a ti? Disse Micaías: Eis que o verás naquele mesmo dia, quando entrares de câmara em câmara, para te esconderes.

[[v14-18-25]]

^<<v14-18-25,25>>^ Então, disse o rei de Israel: Tomai a Micaías e devolvei-o a Amom, governador da cidade, e a Joás, filho do rei;

[[v14-18-26]]

^<<v14-18-26,26>>^ e direis: Assim diz o rei: Metei este homem na casa do cárcere e angustiai-o com escassez de pão e de água, até que eu volte em paz.

[[v14-18-27]]

^<<v14-18-27,27>>^ Disse Micaías: Se voltares em paz, não falou o SENHOR, na verdade, por mim. Disse mais: Ouvi isto, vós, todos os povos!

[[v14-18-28]]

^<<v14-18-28,28>>^ Subiram o rei de Israel e Josafá, rei de Judá, a Ramote-Gileade.

[[v14-18-29]]

^<<v14-18-29,29>>^ Disse o rei de Israel a Josafá: Eu me disfarçarei e entrarei na peleja; tu, porém, traja as tuas vestes. Disfarçou-se, pois, o rei de Israel, e entraram na peleja.

[[v14-18-30]]

^<<v14-18-30,30>>^ Ora, o rei da Síria dera ordem aos capitães dos seus carros, dizendo: Não pelejareis nem contra pequeno nem contra grande, mas somente contra o rei de Israel.

[[v14-18-31]]

^<<v14-18-31,31>>^ Vendo os capitães dos carros a Josafá, disseram: Este é o rei de Israel. Portanto, a ele se dirigiram para o atacar. Josafá, porém, gritou, e o SENHOR o socorreu; Deus os desviou dele.

[[v14-18-32]]

^<<v14-18-32,32>>^ Vendo os capitães dos carros que não era o rei de Israel, deixaram de o perseguir.

[[v14-18-33]]

^<<v14-18-33,33>>^ Então, um homem entesou o arco e, atirando ao acaso, feriu o rei de Israel por entre as juntas da sua armadura; então, disse este ao seu cocheiro: Vira e leva-me para fora do combate, porque estou gravemente ferido.

[[v14-18-34]]

^<<v14-18-34,34>>^ A peleja tornou-se renhida naquele dia; quanto ao rei, segurou-se a si mesmo de pé no carro defronte dos siros, até à tarde, mas, ao pôr do sol, morreu.

'''

xref:014-2-cronicas/014-2-cronicas-017.adoc#v14-17-0[&#60; Capítulo Anterior] | <<v14-18-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-019.adoc#v14-19-0[Próximo Capítulo &#62;]