include::./index.adoc[]

[[v14-34-0]]
=== 2 Crônicas, 34
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-34-1]]

^<<v14-34-1,1>>^ Tinha Josias oito anos de idade quando começou a reinar e reinou trinta e um anos em Jerusalém.

[[v14-34-2]]

^<<v14-34-2,2>>^ Fez o que era reto perante o SENHOR, andou em todo o caminho de Davi, seu pai, e não se desviou nem para a direita nem para a esquerda.

[[v14-34-3]]

^<<v14-34-3,3>>^ Porque, no oitavo ano de seu reinado, sendo ainda moço, começou a buscar o Deus de Davi, seu pai; e, no duodécimo ano, começou a purificar a Judá e a Jerusalém dos altos, dos postes-ídolos e das imagens de escultura e de fundição.

[[v14-34-4]]

^<<v14-34-4,4>>^ Na presença dele, derribaram os altares dos baalins; ele despedaçou os altares do incenso que estavam acima deles; os postes-ídolos e as imagens de escultura e de fundição, quebrou-os, reduziu-os a pó e o aspergiu sobre as sepulturas dos que lhes tinham sacrificado.

[[v14-34-5]]

^<<v14-34-5,5>>^ Os ossos dos sacerdotes queimou sobre os seus altares e purificou a Judá e a Jerusalém.

[[v14-34-6]]

^<<v14-34-6,6>>^ O mesmo fez nas cidades de Manassés, de Efraim e de Simeão, até Naftali, por todos os lados no meio das suas ruínas.

[[v14-34-7]]

^<<v14-34-7,7>>^ Tendo derribado os altares, os postes-ídolos e as imagens de escultura, até reduzi-los a pó, e tendo despedaçado todos os altares do incenso em toda a terra de Israel, então, voltou para Jerusalém.

[[v14-34-8]]

^<<v14-34-8,8>>^ No décimo oitavo ano do seu reinado, havendo já purificado a terra e a casa, enviou a Safã, filho de Azalias, a Maaseias, governador da cidade, e a Joá, filho de Joacaz, cronista, para repararem a Casa do SENHOR, seu Deus.

[[v14-34-9]]

^<<v14-34-9,9>>^ Foram a Hilquias, sumo sacerdote, e entregaram o dinheiro que se tinha trazido à Casa de Deus e que os levitas, guardas da porta, tinham ajuntado, dinheiro provindo das mãos de Manassés, de Efraim e de todo o resto de Israel, como também de todo o Judá e Benjamim e dos habitantes de Jerusalém.

[[v14-34-10]]

^<<v14-34-10,10>>^ Eles o entregaram aos que dirigiam a obra e tinham a seu cargo a Casa do SENHOR, para que pagassem àqueles que faziam a obra, trabalhadores na Casa do SENHOR, para repararem e restaurarem a casa.

[[v14-34-11]]

^<<v14-34-11,11>>^ Deram-no aos carpinteiros e aos edificadores, para comprarem pedras lavradas e madeiras para as junturas e para servirem de vigas para as casas que os reis de Judá deixaram cair em ruína.

[[v14-34-12]]

^<<v14-34-12,12>>^ Os homens procederam fielmente na obra; e os superintendentes deles eram Jaate e Obadias, levitas, dos filhos de Merari, como também Zacarias e Mesulão, dos filhos dos coatitas, para superintenderem a obra.

[[v14-34-13]]

^<<v14-34-13,13>>^ Todos os levitas peritos em instrumentos músicos eram superintendentes dos carregadores e dirigiam a todos os que faziam a obra, em qualquer sorte de trabalho. Outros levitas eram escrivães, oficiais e porteiros.

[[v14-34-14]]

^<<v14-34-14,14>>^ Quando se tirava o dinheiro que se havia trazido à Casa do SENHOR, Hilquias, o sacerdote, achou o Livro da Lei do SENHOR, dada por intermédio de Moisés.

[[v14-34-15]]

^<<v14-34-15,15>>^ Então, disse Hilquias ao escrivão Safã: Achei o Livro da Lei na Casa do SENHOR.

[[v14-34-16]]

^<<v14-34-16,16>>^ Hilquias entregou o livro a Safã. Então, Safã levou o livro ao rei e lhe deu relatório, dizendo: Tudo quanto se encomendou a teus servos, eles o fazem.

[[v14-34-17]]

^<<v14-34-17,17>>^ Contaram o dinheiro que se achou na Casa do SENHOR e o entregaram nas mãos dos que dirigem a obra e dos que a executam.

[[v14-34-18]]

^<<v14-34-18,18>>^ Relatou mais o escrivão ao rei, dizendo: O sacerdote Hilquias me entregou um livro. Safã leu nele diante do rei.

[[v14-34-19]]

^<<v14-34-19,19>>^ Tendo o rei ouvido as palavras da lei, rasgou as suas vestes.

[[v14-34-20]]

^<<v14-34-20,20>>^ Ordenou o rei a Hilquias, a Aicão, filho de Safã, a Abdom, filho de Mica, a Safã, o escrivão, e a Asaías, servo do rei, dizendo:

[[v14-34-21]]

^<<v14-34-21,21>>^ Ide e consultai o SENHOR por mim e pelos restantes em Israel e Judá, acerca das palavras deste livro que se achou; porque grande é o furor do SENHOR, que se derramou sobre nós, porquanto nossos pais não guardaram as palavras do SENHOR, para fazerem tudo quanto está escrito neste livro.

[[v14-34-22]]

^<<v14-34-22,22>>^ Então, Hilquias e os enviados pelo rei foram ter com a profetisa Hulda, mulher de Salum, o guarda-roupa, filho de Tocate, filho de Harás, e lhe falaram a esse respeito. Ela habitava na Cidade Baixa, em Jerusalém.

[[v14-34-23]]

^<<v14-34-23,23>>^ Ela lhes disse: Assim diz o SENHOR, o Deus de Israel: Dizei ao homem que vos enviou a mim:

[[v14-34-24]]

^<<v14-34-24,24>>^ Assim diz o SENHOR: Eis que trarei males sobre este lugar e sobre os seus moradores, a saber, todas as maldições escritas no livro que leram diante do rei de Judá.

[[v14-34-25]]

^<<v14-34-25,25>>^ Visto que me deixaram e queimaram incenso a outros deuses, para me provocarem à ira com todas as obras das suas mãos, o meu furor está derramado sobre este lugar e não se apagará.

[[v14-34-26]]

^<<v14-34-26,26>>^ Porém ao rei de Judá, que vos enviou a consultar o SENHOR, assim lhe direis: Assim diz o SENHOR, o Deus de Israel, acerca das palavras que ouviste:

[[v14-34-27]]

^<<v14-34-27,27>>^ Porquanto o teu coração se enterneceu, e te humilhaste perante Deus, quando ouviste as suas ameaças contra este lugar e contra os seus moradores, e te humilhaste perante mim, e rasgaste as tuas vestes, e choraste perante mim, também eu te ouvi, diz o SENHOR.

[[v14-34-28]]

^<<v14-34-28,28>>^ Pelo que eu te reunirei a teus pais, e tu serás recolhido em paz à tua sepultura, e os teus olhos não verão todo o mal que hei de trazer sobre este lugar e sobre os seus moradores. Então, levaram eles ao rei esta resposta.

[[v14-34-29]]

^<<v14-34-29,29>>^ Então, deu ordem o rei, e todos os anciãos de Judá e de Jerusalém se ajuntaram.

[[v14-34-30]]

^<<v14-34-30,30>>^ O rei subiu à Casa do SENHOR, e todos os homens de Judá, todos os moradores de Jerusalém, os sacerdotes, os levitas e todo o povo, desde o menor até ao maior; e leu diante deles todas as palavras do Livro da Aliança que fora encontrado na Casa do SENHOR.

[[v14-34-31]]

^<<v14-34-31,31>>^ O rei se pôs no seu lugar e fez aliança ante o SENHOR, para o seguirem, guardarem os seus mandamentos, os seus testemunhos e os seus estatutos, de todo o coração e de toda a alma, cumprindo as palavras desta aliança, que estavam escritas naquele livro.

[[v14-34-32]]

^<<v14-34-32,32>>^ Todos os que se acharam em Jerusalém e em Benjamim anuíram a esta aliança; e os habitantes de Jerusalém fizeram segundo a aliança de Deus, o Deus de seus pais.

[[v14-34-33]]

^<<v14-34-33,33>>^ Josias tirou todas as abominações de todas as terras que eram dos filhos de Israel; e a todos quantos se acharam em Israel os obrigou a que servissem ao SENHOR, seu Deus. Enquanto ele viveu, não se desviaram de seguir o SENHOR, Deus de seus pais.

'''

xref:014-2-cronicas/014-2-cronicas-033.adoc#v14-33-0[&#60; Capítulo Anterior] | <<v14-34-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-035.adoc#v14-35-0[Próximo Capítulo &#62;]