include::./index.adoc[]

[[v14-14-0]]
=== 2 Crônicas, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-14-1]]

^<<v14-14-1,1>>^ Abias descansou com seus pais, e o sepultaram na Cidade de Davi. Em seu lugar reinou seu filho Asa, em cujos dias a terra esteve em paz dez anos.

[[v14-14-2]]

^<<v14-14-2,2>>^ Asa fez o que era bom e reto perante o SENHOR, seu Deus.

[[v14-14-3]]

^<<v14-14-3,3>>^ Porque aboliu os altares dos deuses estranhos e o culto nos altos, quebrou as colunas e cortou os postes-ídolos.

[[v14-14-4]]

^<<v14-14-4,4>>^ Ordenou a Judá que buscasse ao SENHOR, Deus de seus pais, e que observasse a lei e o mandamento.

[[v14-14-5]]

^<<v14-14-5,5>>^ Também aboliu de todas as cidades de Judá o culto nos altos e os altares do incenso; e houve paz no seu reinado.

[[v14-14-6]]

^<<v14-14-6,6>>^ Edificou cidades fortificadas em Judá, pois havia paz na terra, e não houve guerra contra ele naqueles anos, porquanto o SENHOR lhe dera repouso.

[[v14-14-7]]

^<<v14-14-7,7>>^ Disse, pois, a Judá: Edifiquemos estas cidades, cerquemo-las de muros e torres, portas e ferrolhos, enquanto a terra ainda está em paz diante de nós, pois temos buscado ao SENHOR, nosso Deus; temo-lo buscado, e ele nos deu repouso de todos os lados.

[[v14-14-8]]

^<<v14-14-8,8>>^ Edificaram e prosperaram. Tinha Asa, no seu exército, trezentos mil de Judá, que traziam pavês e lança, e duzentos e oitenta mil de Benjamim, que traziam escudo e atiravam com arco; todos eram homens valentes.

[[v14-14-9]]

^<<v14-14-9,9>>^ Zerá, o etíope, saiu contra eles, com um exército de um milhão de homens e trezentos carros, e chegou até Maressa.

[[v14-14-10]]

^<<v14-14-10,10>>^ Então, Asa saiu contra ele; e ordenaram a batalha no vale de Zefatá, perto de Maressa.

[[v14-14-11]]

^<<v14-14-11,11>>^ Clamou Asa ao SENHOR, seu Deus, e disse: SENHOR, além de ti não há quem possa socorrer numa batalha entre o poderoso e o fraco; ajuda-nos, pois, SENHOR, nosso Deus, porque em ti confiamos e no teu nome viemos contra esta multidão. SENHOR, tu és o nosso Deus, não prevaleça contra ti o homem.

[[v14-14-12]]

^<<v14-14-12,12>>^ O SENHOR feriu os etíopes diante de Asa e diante de Judá; e eles fugiram.

[[v14-14-13]]

^<<v14-14-13,13>>^ Asa e o povo que estava com ele os perseguiram até Gerar; e caíram os etíopes sem restar nem um sequer; porque foram destroçados diante do SENHOR e diante do seu exército, e levaram dali mui grande despojo.

[[v14-14-14]]

^<<v14-14-14,14>>^ Feriram todas as cidades ao redor de Gerar, porque o terror do SENHOR as havia invadido; e saquearam todas as cidades, porque havia nelas muita presa.

[[v14-14-15]]

^<<v14-14-15,15>>^ Também feriram as tendas dos donos do gado, levaram ovelhas em abundância e camelos e voltaram para Jerusalém.

'''

xref:014-2-cronicas/014-2-cronicas-013.adoc#v14-13-0[&#60; Capítulo Anterior] | <<v14-14-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-015.adoc#v14-15-0[Próximo Capítulo &#62;]