include::./index.adoc[]

[[v14-4-0]]
=== 2 Crônicas, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-4-1]]

^<<v14-4-1,1>>^ Também fez um altar de bronze de vinte côvados de comprimento, vinte de largura e dez de altura.

[[v14-4-2]]

^<<v14-4-2,2>>^ Fez também o mar de fundição, redondo, de dez côvados de uma borda até a outra borda, e de cinco de altura; e um fio de trinta côvados era a medida de sua circunferência.

[[v14-4-3]]

^<<v14-4-3,3>>^ Por baixo da sua borda, em redor, havia figuras de colocíntidas, dez em cada côvado; estavam em duas fileiras, fundidas quando se fundiu o mar.

[[v14-4-4]]

^<<v14-4-4,4>>^ Assentava-se o mar sobre doze bois; três olhavam para o norte, três, para o ocidente, três, para o sul, e três, para o oriente; o mar apoiava-se sobre eles, cujas partes posteriores convergiam para dentro.

[[v14-4-5]]

^<<v14-4-5,5>>^ A grossura dele era de quatro dedos, a sua borda, como borda de copo, como flor de lírios; comportava três mil batos.

[[v14-4-6]]

^<<v14-4-6,6>>^ Também fez dez pias e pôs cinco à direita e cinco, à esquerda, para lavarem nelas o que pertencia ao holocausto; o mar, porém, era para que os sacerdotes se lavassem nele.

[[v14-4-7]]

^<<v14-4-7,7>>^ Fez também dez candeeiros de ouro, segundo fora ordenado, e os pôs no templo, cinco à direita e cinco à esquerda.

[[v14-4-8]]

^<<v14-4-8,8>>^ Também fez dez mesas e as pôs no templo, cinco à direita e cinco à esquerda; também fez cem bacias de ouro.

[[v14-4-9]]

^<<v14-4-9,9>>^ Fez mais o pátio dos sacerdotes e o pátio grande, como também as portas deles, as quais cobriu de bronze.

[[v14-4-10]]

^<<v14-4-10,10>>^ E o mar pôs ao lado direito, para o lado sudeste.

[[v14-4-11]]

^<<v14-4-11,11>>^ Depois, fez Hirão as panelas, e as pás, e as bacias. Assim, terminou ele de fazer a obra para o rei Salomão, para a Casa de Deus:

[[v14-4-12]]

^<<v14-4-12,12>>^ as duas colunas, os dois globos e os dois capitéis que estavam no alto das duas colunas; as duas redes, para cobrirem os dois globos dos capitéis que estavam no alto das colunas;

[[v14-4-13]]

^<<v14-4-13,13>>^ as quatrocentas romãs para as duas redes, isto é, duas fileiras de romãs para cada rede, para cobrirem os dois globos dos capitéis que estavam no alto das colunas.

[[v14-4-14]]

^<<v14-4-14,14>>^ Fez também os suportes e as pias sobre eles,

[[v14-4-15]]

^<<v14-4-15,15>>^ o mar com os doze bois por baixo.

[[v14-4-16]]

^<<v14-4-16,16>>^ Também as panelas, as pás, os garfos e todos os utensílios fez Hirão-Abi para o rei Salomão, para a Casa do SENHOR, de bronze purificado.

[[v14-4-17]]

^<<v14-4-17,17>>^ Na planície do Jordão, o rei os fez fundir em terra barrenta, entre Sucote e Zereda.

[[v14-4-18]]

^<<v14-4-18,18>>^ Fez Salomão todos estes objetos em grande abundância, não se verificando o peso do seu bronze.

[[v14-4-19]]

^<<v14-4-19,19>>^ Também fez Salomão todos os utensílios do Santo Lugar de Deus: o altar de ouro e as mesas, sobre as quais estavam os pães da proposição;

[[v14-4-20]]

^<<v14-4-20,20>>^ e os candeeiros com as suas lâmpadas de ouro puro, para as acenderem, segundo o costume, perante o Santo dos Santos.

[[v14-4-21]]

^<<v14-4-21,21>>^ As flores, as lâmpadas e as tenazes eram do mais fino ouro,

[[v14-4-22]]

^<<v14-4-22,22>>^ como também as espevitadeiras, as bacias, as taças e os incensários, de ouro finíssimo; quanto à entrada da casa, as suas portas de dentro do Santo dos Santos e as portas do Santo Lugar do templo eram de ouro.

'''

xref:014-2-cronicas/014-2-cronicas-003.adoc#v14-3-0[&#60; Capítulo Anterior] | <<v14-4-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-005.adoc#v14-5-0[Próximo Capítulo &#62;]