include::./index.adoc[]

[[v14-36-0]]
=== 2 Crônicas, 36
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-36-1]]

^<<v14-36-1,1>>^ O povo da terra tomou a Joacaz, filho de Josias, e o fez rei em lugar de seu pai, em Jerusalém.

[[v14-36-2]]

^<<v14-36-2,2>>^ Tinha Joacaz vinte e três anos de idade quando começou a reinar e reinou três meses em Jerusalém;

[[v14-36-3]]

^<<v14-36-3,3>>^ porque o rei do Egito o depôs em Jerusalém e impôs à terra a pena de cem talentos de prata e um de ouro.

[[v14-36-4]]

^<<v14-36-4,4>>^ O rei do Egito constituiu a Eliaquim, irmão de Joacaz, rei sobre Judá e Jerusalém e lhe mudou o nome para Jeoaquim; mas ao irmão Joacaz tomou Neco e o levou para o Egito.

[[v14-36-5]]

^<<v14-36-5,5>>^ Tinha Jeoaquim a idade de vinte e cinco anos quando começou a reinar e reinou onze anos em Jerusalém. Fez ele o que era mau perante o SENHOR, seu Deus.

[[v14-36-6]]

^<<v14-36-6,6>>^ Subiu, pois, contra ele Nabucodonosor, rei da Babilônia, e o amarrou com duas cadeias de bronze, para o levar à Babilônia.

[[v14-36-7]]

^<<v14-36-7,7>>^ Também alguns dos utensílios da Casa do SENHOR levou Nabucodonosor para a Babilônia, onde os pôs no seu templo.

[[v14-36-8]]

^<<v14-36-8,8>>^ Quanto aos mais atos de Jeoaquim, e às abominações que cometeu, e ao mais que se achou nele, eis que estão escritos no Livro da História dos Reis de Israel e de Judá; e Joaquim, seu filho, reinou em seu lugar.

[[v14-36-9]]

^<<v14-36-9,9>>^ Tinha Joaquim dezoito anos quando começou a reinar e reinou três meses e dez dias em Jerusalém. Fez ele o que era mau perante o SENHOR.

[[v14-36-10]]

^<<v14-36-10,10>>^ Na primavera do ano, mandou o rei Nabucodonosor levá-lo à Babilônia, com os mais preciosos utensílios da Casa do SENHOR; e estabeleceu a Zedequias, seu irmão, rei sobre Judá e Jerusalém.

[[v14-36-11]]

^<<v14-36-11,11>>^ Tinha Zedequias a idade de vinte e um anos quando começou a reinar e reinou onze anos em Jerusalém.

[[v14-36-12]]

^<<v14-36-12,12>>^ Fez o que era mau perante o SENHOR, seu Deus, e não se humilhou perante o profeta Jeremias, que falava da parte do SENHOR.

[[v14-36-13]]

^<<v14-36-13,13>>^ Rebelou-se também contra o rei Nabucodonosor, que o tinha ajuramentado por Deus; mas endureceu a sua cerviz e tanto se obstinou no seu coração, que não voltou ao SENHOR, Deus de Israel.

[[v14-36-14]]

^<<v14-36-14,14>>^ Também todos os chefes dos sacerdotes e o povo aumentavam mais e mais as transgressões, segundo todas as abominações dos gentios; e contaminaram a casa que o SENHOR tinha santificado em Jerusalém.

[[v14-36-15]]

^<<v14-36-15,15>>^ O SENHOR, Deus de seus pais, começando de madrugada, falou-lhes por intermédio dos seus mensageiros, porque se compadecera do seu povo e da sua própria morada.

[[v14-36-16]]

^<<v14-36-16,16>>^ Eles, porém, zombavam dos mensageiros, desprezavam as palavras de Deus e mofavam dos seus profetas, até que subiu a ira do SENHOR contra o seu povo, e não houve remédio algum.

[[v14-36-17]]

^<<v14-36-17,17>>^ Por isso, o SENHOR fez subir contra ele o rei dos caldeus, o qual matou os seus jovens à espada, na casa do seu santuário; e não teve piedade nem dos jovens nem das donzelas, nem dos velhos nem dos mais avançados em idade; a todos os deu nas suas mãos.

[[v14-36-18]]

^<<v14-36-18,18>>^ Todos os utensílios da Casa de Deus, grandes e pequenos, os tesouros da Casa do SENHOR e os tesouros do rei e dos seus príncipes, tudo levou ele para a Babilônia.

[[v14-36-19]]

^<<v14-36-19,19>>^ Queimaram a Casa de Deus e derribaram os muros de Jerusalém; todos os seus palácios queimaram, destruindo também todos os seus preciosos objetos.

[[v14-36-20]]

^<<v14-36-20,20>>^ Os que escaparam da espada, a esses levou ele para a Babilônia, onde se tornaram seus servos e de seus filhos, até ao tempo do reino da Pérsia;

[[v14-36-21]]

^<<v14-36-21,21>>^ para que se cumprisse a palavra do SENHOR, por boca de Jeremias, até que a terra se agradasse dos seus sábados; todos os dias da desolação repousou, até que os setenta anos se cumpriram.

[[v14-36-22]]

^<<v14-36-22,22>>^ Porém, no primeiro ano de Ciro, rei da Pérsia, para que se cumprisse a palavra do SENHOR, por boca de Jeremias, despertou o SENHOR o espírito de Ciro, rei da Pérsia, o qual fez passar pregão por todo o seu reino, como também por escrito, dizendo:

[[v14-36-23]]

^<<v14-36-23,23>>^ Assim diz Ciro, rei da Pérsia: O SENHOR, Deus dos céus, me deu todos os reinos da terra e me encarregou de lhe edificar uma casa em Jerusalém, que está em Judá; quem entre vós é de todo o seu povo, que suba, e o SENHOR, seu Deus, seja com ele.

'''

xref:014-2-cronicas/014-2-cronicas-035.adoc#v14-35-0[&#60; Capítulo Anterior] | <<v14-36-0,Topo>> | xref:015-esdras/015-esdras-001.adoc#v15-1-0[Próximo Capítulo &#62;]