include::./index.adoc[]

[[v14-24-0]]
=== 2 Crônicas, 24
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-24-1]]

^<<v14-24-1,1>>^ Tinha Joás sete anos de idade quando começou a reinar e quarenta anos reinou em Jerusalém.

[[v14-24-2]]

^<<v14-24-2,2>>^ Era o nome de sua mãe Zíbia, de Berseba. Fez Joás o que era reto perante o SENHOR todos os dias do sacerdote Joiada.

[[v14-24-3]]

^<<v14-24-3,3>>^ Tomou-lhe Joiada duas mulheres; e gerou filhos e filhas.

[[v14-24-4]]

^<<v14-24-4,4>>^ Depois disto, resolveu Joás restaurar a Casa do SENHOR.

[[v14-24-5]]

^<<v14-24-5,5>>^ Reuniu os sacerdotes e os levitas e lhes disse: Saí pelas cidades de Judá e levantai dinheiro de todo o Israel para reparardes a casa do vosso Deus, de ano em ano; e, vós, apressai-vos nisto. Porém os levitas não se apressaram.

[[v14-24-6]]

^<<v14-24-6,6>>^ Mandou o rei chamar a Joiada, o chefe, e lhe perguntou: Por que não requereste dos levitas que trouxessem de Judá e de Jerusalém o imposto que Moisés, servo do SENHOR, pôs sobre a congregação de Israel, para a tenda do Testemunho?

[[v14-24-7]]

^<<v14-24-7,7>>^ Porque a perversa Atalia e seus filhos arruinaram a Casa de Deus; e usaram todas as coisas sagradas da Casa do SENHOR no serviço dos baalins.

[[v14-24-8]]

^<<v14-24-8,8>>^ Deu o rei ordem e fizeram um cofre e o puseram do lado de fora, à porta da Casa do SENHOR.

[[v14-24-9]]

^<<v14-24-9,9>>^ Publicou-se, em Judá e em Jerusalém, que trouxessem ao SENHOR o imposto que Moisés, servo de Deus, havia posto sobre Israel, no deserto.

[[v14-24-10]]

^<<v14-24-10,10>>^ Então, todos os príncipes e todo o povo se alegraram, e trouxeram o imposto, e o lançaram no cofre, até acabar a obra.

[[v14-24-11]]

^<<v14-24-11,11>>^ Quando o cofre era levado por intermédio dos levitas a uma comissão real, vendo-se que havia muito dinheiro, vinha o escrivão do rei e o comissário do sumo sacerdote, esvaziavam-no, tomavam-no e o levavam de novo ao seu lugar; assim faziam dia após dia e ajuntaram dinheiro em abundância,

[[v14-24-12]]

^<<v14-24-12,12>>^ o qual o rei e Joiada davam aos que dirigiam a obra e tinham a seu cargo a Casa do SENHOR; contrataram pedreiros e carpinteiros, para restaurarem a Casa do SENHOR, como também os que trabalhavam em ferro e em bronze, para repararem a Casa do SENHOR.

[[v14-24-13]]

^<<v14-24-13,13>>^ Os que tinham o encargo da obra trabalhavam, e a reparação tinha bom êxito com eles; restauraram a Casa de Deus no seu próprio estado e a consolidaram.

[[v14-24-14]]

^<<v14-24-14,14>>^ Tendo eles acabado a obra, trouxeram ao rei e a Joiada o resto do dinheiro, de que se fizeram utensílios para a Casa do SENHOR, objetos para o ministério e para os holocaustos, taças e outros objetos de ouro e de prata. E continuamente ofereceram holocaustos na Casa do SENHOR, todos os dias de Joiada.

[[v14-24-15]]

^<<v14-24-15,15>>^ Envelheceu Joiada e morreu farto de dias; era da idade de cento e trinta anos quando morreu.

[[v14-24-16]]

^<<v14-24-16,16>>^ Sepultaram-no na Cidade de Davi com os reis; porque tinha feito bem em Israel e para com Deus e a sua casa.

[[v14-24-17]]

^<<v14-24-17,17>>^ Depois da morte de Joiada, vieram os príncipes de Judá e se prostraram perante o rei, e o rei os ouviu.

[[v14-24-18]]

^<<v14-24-18,18>>^ Deixaram a Casa do SENHOR, Deus de seus pais, e serviram aos postes-ídolos e aos ídolos; e, por esta sua culpa, veio grande ira sobre Judá e Jerusalém.

[[v14-24-19]]

^<<v14-24-19,19>>^ Porém o SENHOR lhes enviou profetas para os reconduzir a si; estes profetas testemunharam contra eles, mas eles não deram ouvidos.

[[v14-24-20]]

^<<v14-24-20,20>>^ O Espírito de Deus se apoderou de Zacarias, filho do sacerdote Joiada, o qual se pôs em pé diante do povo e lhes disse: Assim diz Deus: Por que transgredis os mandamentos do SENHOR, de modo que não prosperais? Porque deixastes o SENHOR, também ele vos deixará.

[[v14-24-21]]

^<<v14-24-21,21>>^ Conspiraram contra ele e o apedrejaram, por mandado do rei, no pátio da Casa do SENHOR.

[[v14-24-22]]

^<<v14-24-22,22>>^ Assim, o rei Joás não se lembrou da beneficência que Joiada, pai de Zacarias, lhe fizera, porém matou-lhe o filho; este, ao expirar, disse: O SENHOR o verá e o retribuirá.

[[v14-24-23]]

^<<v14-24-23,23>>^ Antes de se findar o ano, subiu contra Joás o exército dos siros; e, vindo a Judá e a Jerusalém, destruíram, dentre o povo, a todos os seus príncipes, cujo despojo remeteram ao rei de Damasco.

[[v14-24-24]]

^<<v14-24-24,24>>^ Ainda que o exército dos siros viera com poucos homens, contudo, o SENHOR lhes permitiu vencer um exército mui numeroso dos judeus, porque estes deixaram o SENHOR, Deus de seus pais. Assim, executaram os siros os juízos de Deus contra Joás.

[[v14-24-25]]

^<<v14-24-25,25>>^ Quando os siros se retiraram dele, deixando-o gravemente enfermo, conspiraram contra ele os seus servos, por causa do sangue dos filhos do sacerdote Joiada, e o feriram no seu leito, e morreu.

[[v14-24-26]]

^<<v14-24-26,26>>^ Sepultaram-no na Cidade de Davi, porém não nos sepulcros dos reis. Foram estes os que conspiraram contra ele: Zabade, filho de Simeate, a amonita, e Jeozabade, filho de Sinrite, a moabita.

[[v14-24-27]]

^<<v14-24-27,27>>^ Quanto a seus filhos, e às numerosas sentenças proferidas contra ele, e à restauração da Casa de Deus, eis que estão escritos no Livro da História dos Reis. Em seu lugar, reinou Amazias, seu filho.

'''

xref:014-2-cronicas/014-2-cronicas-023.adoc#v14-23-0[&#60; Capítulo Anterior] | <<v14-24-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[Próximo Capítulo &#62;]