include::./index.adoc[]

[[v14-31-0]]
=== 2 Crônicas, 31
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-31-1]]

^<<v14-31-1,1>>^ Acabando tudo isto, todos os israelitas que se achavam ali saíram às cidades de Judá, quebraram as estátuas, cortaram os postes-ídolos e derribaram os altos e altares por todo o Judá e Benjamim, como também em Efraim e Manassés, até que tudo destruíram; então, tornaram todos os filhos de Israel, cada um para sua possessão, para as cidades deles.

[[v14-31-2]]

^<<v14-31-2,2>>^ Estabeleceu Ezequias os turnos dos sacerdotes e dos levitas, turno após turno, segundo o seu mister: os sacerdotes e levitas, para o holocausto e para as ofertas pacíficas, para ministrarem e cantarem, portas a dentro, nos arraiais do SENHOR.

[[v14-31-3]]

^<<v14-31-3,3>>^ A contribuição que fazia o rei da sua própria fazenda era destinada para os holocaustos, para os da manhã e os da tarde e para os holocaustos dos sábados, das Festas da Lua Nova e das festas fixas, como está escrito na Lei do SENHOR.

[[v14-31-4]]

^<<v14-31-4,4>>^ Além disso, ordenou ao povo, moradores de Jerusalém, que contribuísse com sua parte devida aos sacerdotes e aos levitas, para que pudessem dedicar-se à Lei do SENHOR.

[[v14-31-5]]

^<<v14-31-5,5>>^ Logo que se divulgou esta ordem, os filhos de Israel trouxeram em abundância as primícias do cereal, do vinho, do azeite, do mel e de todo produto do campo; também os dízimos de tudo trouxeram em abundância.

[[v14-31-6]]

^<<v14-31-6,6>>^ Os filhos de Israel e de Judá que habitavam nas cidades de Judá também trouxeram dízimos das vacas e das ovelhas e dízimos das coisas que foram consagradas ao SENHOR, seu Deus; e fizeram montões e montões.

[[v14-31-7]]

^<<v14-31-7,7>>^ No terceiro mês, começaram a fazer os primeiros montões; e, no sétimo mês, acabaram.

[[v14-31-8]]

^<<v14-31-8,8>>^ Vindo, pois, Ezequias e os príncipes e vendo aqueles montões, bendisseram ao SENHOR e ao seu povo de Israel.

[[v14-31-9]]

^<<v14-31-9,9>>^ Perguntou Ezequias aos sacerdotes e aos levitas acerca daqueles montões.

[[v14-31-10]]

^<<v14-31-10,10>>^ Então, o sumo sacerdote Azarias, da casa de Zadoque, lhe respondeu: Desde que se começou a trazer à Casa do SENHOR estas ofertas, temos comido e nos temos fartado delas, e ainda há sobra em abundância; porque o SENHOR abençoou ao seu povo, e esta grande quantidade é o que sobra.

[[v14-31-11]]

^<<v14-31-11,11>>^ Então, ordenou Ezequias que se preparassem depósitos na Casa do SENHOR.

[[v14-31-12]]

^<<v14-31-12,12>>^ Uma vez preparados, recolheram neles fielmente as ofertas, os dízimos e as coisas consagradas; disto era intendente Conanias, o levita, e Simei, seu irmão, era o segundo.

[[v14-31-13]]

^<<v14-31-13,13>>^ Jeiel, Azarias, Naate, Asael, Jerimote, Jozabade, Eliel, Ismaquias, Maate e Benaia eram superintendentes sob a direção de Conanias e Simei, seu irmão, nomeados pelo rei Ezequias e por Azarias, chefe da Casa de Deus.

[[v14-31-14]]

^<<v14-31-14,14>>^ O levita Coré, filho de Imna e guarda da porta oriental, estava encarregado das ofertas voluntárias que se faziam a Deus, para distribuir as ofertas do SENHOR e as coisas santíssimas.

[[v14-31-15]]

^<<v14-31-15,15>>^ Debaixo das suas ordens estavam Éden, Miniamim, Jesua, Semaías, Amarias e Secanias, nas cidades dos sacerdotes, para com fidelidade distribuírem as porções a seus irmãos, segundo os seus turnos, tanto aos pequenos como aos grandes;

[[v14-31-16]]

^<<v14-31-16,16>>^ exceto aos que estavam registrados nas genealogias dos homens, de três anos para cima, e que entravam na Casa do SENHOR, para a obra de cada dia pelo seu ministério nos seus cargos, segundo os seus turnos.

[[v14-31-17]]

^<<v14-31-17,17>>^ Quanto ao registro dos sacerdotes, foi ele feito segundo as suas famílias, e o dos levitas de vinte anos para cima foi feito segundo os seus cargos nos seus turnos.

[[v14-31-18]]

^<<v14-31-18,18>>^ Deles, foram registrados as crianças, as mulheres, os filhos e as filhas, uma grande multidão, porque com fidelidade se houveram santamente com as coisas sagradas.

[[v14-31-19]]

^<<v14-31-19,19>>^ Dentre os sacerdotes, filhos de Arão, que moravam nos campos dos arredores das suas cidades, havia, em cada cidade, homens que foram designados nominalmente para distribuírem as porções a todo homem entre os sacerdotes e a todos os levitas que foram registrados.

[[v14-31-20]]

^<<v14-31-20,20>>^ Assim fez Ezequias em todo o Judá; fez o que era bom, reto e verdadeiro perante o SENHOR, seu Deus.

[[v14-31-21]]

^<<v14-31-21,21>>^ Em toda a obra que começou no serviço da Casa de Deus, na lei e nos mandamentos, para buscar a seu Deus, de todo o coração o fez e prosperou.

'''

xref:014-2-cronicas/014-2-cronicas-030.adoc#v14-30-0[&#60; Capítulo Anterior] | <<v14-31-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-032.adoc#v14-32-0[Próximo Capítulo &#62;]