include::./index.adoc[]

[[v14-2-0]]
=== 2 Crônicas, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-2-1]]

^<<v14-2-1,1>>^ Resolveu Salomão edificar a casa ao nome do SENHOR, como também casa para o seu reino.

[[v14-2-2]]

^<<v14-2-2,2>>^ Designou Salomão setenta mil homens para levarem as cargas, oitenta mil, para talharem pedras nas montanhas e três mil e seiscentos, para dirigirem a obra.

[[v14-2-3]]

^<<v14-2-3,3>>^ Salomão mandou dizer a Hirão, rei de Tiro: Como procedeste para com Davi, meu pai, e lhe mandaste cedros, para edificar a casa em que morasse, assim também procede comigo.

[[v14-2-4]]

^<<v14-2-4,4>>^ Eis que estou para edificar a casa ao nome do SENHOR, meu Deus, e lha consagrar, para queimar perante ele incenso aromático, e lhe apresentar o pão contínuo da proposição e os holocaustos da manhã e da tarde, nos sábados, nas Festas da Lua Nova e nas festividades do SENHOR, nosso Deus; o que é obrigação perpétua para Israel.

[[v14-2-5]]

^<<v14-2-5,5>>^ A casa que edificarei há de ser grande, porque o nosso Deus é maior do que todos os deuses.

[[v14-2-6]]

^<<v14-2-6,6>>^ No entanto, quem seria capaz de lhe edificar a casa, visto que os céus e até os céus dos céus o não podem conter? E quem sou eu para lhe edificar a casa, senão para queimar incenso perante ele?

[[v14-2-7]]

^<<v14-2-7,7>>^ Manda-me, pois, agora, um homem que saiba trabalhar em ouro, em prata, em bronze, em ferro, em obras de púrpura, de carmesim e de pano azul; que saiba fazer obras de entalhe juntamente com os peritos que estão comigo em Judá e em Jerusalém, os quais Davi, meu pai, empregou.

[[v14-2-8]]

^<<v14-2-8,8>>^ Manda-me também madeira de cedros, ciprestes e sândalo do Líbano; porque bem sei que os teus servos sabem cortar madeira no Líbano. Eis que os meus servos estarão com os teus,

[[v14-2-9]]

^<<v14-2-9,9>>^ para me prepararem muita madeira; porque a casa que edificarei há de ser grande e maravilhosa.

[[v14-2-10]]

^<<v14-2-10,10>>^ Aos teus servos, cortadores da madeira, darei vinte mil coros de trigo batido, vinte mil coros de cevada, vinte mil batos de vinho e vinte mil batos de azeite.

[[v14-2-11]]

^<<v14-2-11,11>>^ Hirão, rei de Tiro, respondeu por uma carta que enviou a Salomão, dizendo: Porquanto o SENHOR ama ao seu povo, te constituiu rei sobre ele.

[[v14-2-12]]

^<<v14-2-12,12>>^ Disse mais Hirão: Bendito seja o SENHOR, Deus de Israel, que fez os céus e a terra; que deu ao rei Davi um filho sábio, dotado de discrição e entendimento, que edifique casa ao SENHOR e para o seu próprio reino.

[[v14-2-13]]

^<<v14-2-13,13>>^ Agora, pois, envio um homem sábio de grande entendimento, a saber, Hirão-Abi,

[[v14-2-14]]

^<<v14-2-14,14>>^ filho de uma mulher das filhas de Dã e cujo pai foi homem de Tiro; ele sabe lavrar em ouro, em prata, em bronze, em ferro, em pedras e em madeira, em obras de púrpura, de pano azul, e de linho fino e em obras de carmesim; e é hábil para toda obra de entalhe e para elaborar qualquer plano que se lhe proponha, juntamente com os teus peritos e os peritos de Davi, meu senhor, teu pai.

[[v14-2-15]]

^<<v14-2-15,15>>^ Agora, pois, mande o meu senhor para os seus servos o trigo, a cevada, o azeite e o vinho de que falou.

[[v14-2-16]]

^<<v14-2-16,16>>^ E nós cortaremos tanta madeira no Líbano quanta houveres mister e ta faremos chegar em jangadas, pelo mar, a Jope, e tu a farás subir a Jerusalém.

[[v14-2-17]]

^<<v14-2-17,17>>^ Salomão levantou o censo de todos os homens estrangeiros que havia na terra de Israel, segundo o censo que fizera Davi, seu pai; e acharam-se cento e cinquenta e três mil e seiscentos.

[[v14-2-18]]

^<<v14-2-18,18>>^ Designou deles setenta mil para levarem as cargas, oitenta mil para talharem pedras nas montanhas, como também três mil e seiscentos para dirigirem o trabalho do povo.

'''

xref:014-2-cronicas/014-2-cronicas-001.adoc#v14-1-0[&#60; Capítulo Anterior] | <<v14-2-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-003.adoc#v14-3-0[Próximo Capítulo &#62;]