include::./index.adoc[]

[[v14-8-0]]
=== 2 Crônicas, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-8-1]]

^<<v14-8-1,1>>^ Ao fim de vinte anos, tendo Salomão terminado a Casa do SENHOR e a sua própria casa,

[[v14-8-2]]

^<<v14-8-2,2>>^ edificou as cidades que Hirão lhe tinha dado; e fez habitar nelas os filhos de Israel.

[[v14-8-3]]

^<<v14-8-3,3>>^ Depois, foi Salomão a Hamate-Zoba e a tomou.

[[v14-8-4]]

^<<v14-8-4,4>>^ Também edificou a Tadmor no deserto e a todas as cidades-armazéns em Hamate.

[[v14-8-5]]

^<<v14-8-5,5>>^ Edificou também a Bete-Horom, a de cima e a de baixo, cidades fortificadas com muros, portas e ferrolhos;

[[v14-8-6]]

^<<v14-8-6,6>>^ como também a Baalate, e todas as cidades-armazéns que Salomão tinha, e todas as cidades para os carros, e as cidades para os cavaleiros, e tudo o que desejou, enfim, edificar em Jerusalém, no Líbano e em toda a terra do seu domínio.

[[v14-8-7]]

^<<v14-8-7,7>>^ Quanto a todo o povo que restou dos heteus, amorreus, ferezeus, heveus e jebuseus e que não eram de Israel,

[[v14-8-8]]

^<<v14-8-8,8>>^ a seus filhos, que restaram depois deles na terra, os quais os filhos de Israel não puderam destruir totalmente, a esses fez Salomão trabalhadores forçados, até hoje.

[[v14-8-9]]

^<<v14-8-9,9>>^ Porém dos filhos de Israel não fez Salomão escravo algum; eram homens de guerra, seus comandantes, chefes dos seus carros e dos seus cavaleiros;

[[v14-8-10]]

^<<v14-8-10,10>>^ estes eram os principais oficiais que tinha o rei Salomão, duzentos e cinquenta, que presidiam sobre o povo.

[[v14-8-11]]

^<<v14-8-11,11>>^ Salomão fez subir a filha de Faraó da Cidade de Davi para a casa que a ela lhe edificara; porque disse: Minha esposa não morará na casa de Davi, rei de Israel, porque santos são os lugares nos quais entrou a arca do SENHOR.

[[v14-8-12]]

^<<v14-8-12,12>>^ Então, Salomão ofereceu holocaustos ao SENHOR, sobre o altar que tinha edificado ao SENHOR diante do pórtico;

[[v14-8-13]]

^<<v14-8-13,13>>^ e isto segundo o dever de cada dia, conforme o preceito de Moisés, nos sábados, nas Festas da Lua Nova, e nas festas fixas, três vezes no ano: na Festa dos Pães Asmos, na Festa das Semanas e na Festa dos Tabernáculos.

[[v14-8-14]]

^<<v14-8-14,14>>^ Também, segundo a ordem de Davi, seu pai, dispôs os turnos dos sacerdotes nos seus ministérios, como também os dos levitas para os seus cargos, para louvarem a Deus e servirem diante dos sacerdotes, segundo o dever de cada dia, e os porteiros pelos seus turnos a cada porta; porque tal era a ordem de Davi, o homem de Deus.

[[v14-8-15]]

^<<v14-8-15,15>>^ Não se desviaram do que ordenara o rei aos sacerdotes e levitas, em coisa nenhuma, nem acerca dos tesouros.

[[v14-8-16]]

^<<v14-8-16,16>>^ Assim se executou toda a obra de Salomão, desde o dia da fundação da Casa do SENHOR até se acabar; e assim se concluiu a Casa do SENHOR.

[[v14-8-17]]

^<<v14-8-17,17>>^ Então, foi Salomão a Eziom-Geber e a Elate, à praia do mar, na terra de Edom.

[[v14-8-18]]

^<<v14-8-18,18>>^ Enviou-lhe Hirão, por intermédio de seus servos, navios e marinheiros práticos; foram com os servos de Salomão a Ofir e tomaram de lá quatrocentos e cinquenta talentos de ouro, que trouxeram ao rei Salomão.

'''

xref:014-2-cronicas/014-2-cronicas-007.adoc#v14-7-0[&#60; Capítulo Anterior] | <<v14-8-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-009.adoc#v14-9-0[Próximo Capítulo &#62;]