include::./index.adoc[]

[[v14-33-0]]
=== 2 Crônicas, 33
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-33-1]]

^<<v14-33-1,1>>^ Tinha Manassés doze anos de idade quando começou a reinar e cinquenta e cinco anos reinou em Jerusalém.

[[v14-33-2]]

^<<v14-33-2,2>>^ Fez o que era mau perante o SENHOR, segundo as abominações dos gentios que o SENHOR expulsara de suas possessões, de diante dos filhos de Israel.

[[v14-33-3]]

^<<v14-33-3,3>>^ Pois tornou a edificar os altos que Ezequias, seu pai, havia derribado, levantou altares aos baalins, e fez postes-ídolos, e se prostrou diante de todo o exército dos céus, e o serviu.

[[v14-33-4]]

^<<v14-33-4,4>>^ Edificou altares na Casa do SENHOR, da qual o SENHOR tinha dito: Em Jerusalém, porei o meu nome para sempre.

[[v14-33-5]]

^<<v14-33-5,5>>^ Também edificou altares a todo o exército dos céus nos dois átrios da Casa do SENHOR,

[[v14-33-6]]

^<<v14-33-6,6>>^ queimou seus filhos como oferta no vale do filho de Hinom, adivinhava pelas nuvens, era agoureiro, praticava feitiçarias, tratava com necromantes e feiticeiros e prosseguiu em fazer o que era mau perante o SENHOR, para o provocar à ira.

[[v14-33-7]]

^<<v14-33-7,7>>^ Também pôs a imagem de escultura do ídolo que tinha feito na Casa de Deus, de que Deus dissera a Davi e a Salomão, seu filho: Nesta casa e em Jerusalém, que escolhi de todas as tribos de Israel, porei o meu nome para sempre

[[v14-33-8]]

^<<v14-33-8,8>>^ e não removerei mais o pé de Israel da terra que destinei a seus pais, contanto que tenham cuidado de fazer tudo o que lhes tenho mandado, toda a lei, os estatutos e os juízos dados por intermédio de Moisés.

[[v14-33-9]]

^<<v14-33-9,9>>^ Manassés fez errar a Judá e os moradores de Jerusalém, de maneira que fizeram pior do que as nações que o SENHOR tinha destruído de diante dos filhos de Israel.

[[v14-33-10]]

^<<v14-33-10,10>>^ Falou o SENHOR a Manassés e ao seu povo, porém não lhe deram ouvidos.

[[v14-33-11]]

^<<v14-33-11,11>>^ Pelo que o SENHOR trouxe sobre eles os príncipes do exército do rei da Assíria, os quais prenderam Manassés com ganchos, amarraram-no com cadeias e o levaram à Babilônia.

[[v14-33-12]]

^<<v14-33-12,12>>^ Ele, angustiado, suplicou deveras ao SENHOR, seu Deus, e muito se humilhou perante o Deus de seus pais;

[[v14-33-13]]

^<<v14-33-13,13>>^ fez-lhe oração, e Deus se tornou favorável para com ele, atendeu-lhe a súplica e o fez voltar para Jerusalém, ao seu reino; então, reconheceu Manassés que o SENHOR era Deus.

[[v14-33-14]]

^<<v14-33-14,14>>^ Depois disto, edificou o muro de fora da Cidade de Davi, ao ocidente de Giom, no vale, e à entrada da Porta do Peixe, abrangendo Ofel, e o levantou mui alto; também pôs chefes militares em todas as cidades fortificadas de Judá.

[[v14-33-15]]

^<<v14-33-15,15>>^ Tirou da Casa do SENHOR os deuses estranhos e o ídolo, como também todos os altares que edificara no monte da Casa do SENHOR e em Jerusalém, e os lançou fora da cidade.

[[v14-33-16]]

^<<v14-33-16,16>>^ Restaurou o altar do SENHOR, sacrificou sobre ele ofertas pacíficas e de ações de graças e ordenou a Judá que servisse ao SENHOR, Deus de Israel.

[[v14-33-17]]

^<<v14-33-17,17>>^ Contudo, o povo ainda sacrificava nos altos, mas somente ao SENHOR, seu Deus.

[[v14-33-18]]

^<<v14-33-18,18>>^ Quanto aos mais atos de Manassés, e à sua oração ao seu Deus, e às palavras dos videntes que lhe falaram no nome do SENHOR, Deus de Israel, eis que estão escritos na História dos Reis de Israel.

[[v14-33-19]]

^<<v14-33-19,19>>^ A sua oração e como Deus se tornou favorável para com ele, todo o seu pecado, a sua transgressão e os lugares onde edificou altos e colocou postes-ídolos e imagens de escultura, antes que se humilhasse, eis que tudo está na História dos Videntes.

[[v14-33-20]]

^<<v14-33-20,20>>^ Assim, Manassés descansou com seus pais e foi sepultado na sua própria casa; e Amom, seu filho, reinou em seu lugar.

[[v14-33-21]]

^<<v14-33-21,21>>^ Tinha Amom vinte e dois anos de idade quando começou a reinar e reinou dois anos em Jerusalém.

[[v14-33-22]]

^<<v14-33-22,22>>^ Fez o que era mau perante o SENHOR, como fizera Manassés, seu pai; porque Amom fez sacrifício a todas as imagens de escultura que Manassés, seu pai, tinha feito e as serviu.

[[v14-33-23]]

^<<v14-33-23,23>>^ Mas não se humilhou perante o SENHOR, como Manassés, seu pai, se humilhara; antes, Amom se tornou mais e mais culpável.

[[v14-33-24]]

^<<v14-33-24,24>>^ Conspiraram contra ele os seus servos e o mataram em sua casa.

[[v14-33-25]]

^<<v14-33-25,25>>^ Porém o povo da terra feriu todos os que conspiraram contra o rei Amom e constituiu a Josias, seu filho, rei em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-032.adoc#v14-32-0[&#60; Capítulo Anterior] | <<v14-33-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[Próximo Capítulo &#62;]