include::./index.adoc[]

[[v14-17-0]]
=== 2 Crônicas, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-17-1]]

^<<v14-17-1,1>>^ Em lugar de Asa, reinou seu filho Josafá, que se fortificou contra Israel;

[[v14-17-2]]

^<<v14-17-2,2>>^ ele pôs tropas em todas as cidades fortificadas de Judá e estabeleceu guarnições na terra de Judá, como também nas cidades de Efraim, que Asa, seu pai, tinha tomado.

[[v14-17-3]]

^<<v14-17-3,3>>^ O SENHOR foi com Josafá, porque andou nos primeiros caminhos de Davi, seu pai, e não procurou a baalins.

[[v14-17-4]]

^<<v14-17-4,4>>^ Antes, procurou ao Deus de seu pai e andou nos seus mandamentos e não segundo as obras de Israel.

[[v14-17-5]]

^<<v14-17-5,5>>^ O SENHOR confirmou o reino nas suas mãos, e todo o Judá deu presentes a Josafá, o qual teve riquezas e glória em abundância.

[[v14-17-6]]

^<<v14-17-6,6>>^ Tornou-se-lhe ousado o coração em seguir os caminhos do SENHOR, e ainda tirou os altos e os postes-ídolos de Judá.

[[v14-17-7]]

^<<v14-17-7,7>>^ No terceiro ano do seu reinado, enviou ele os seus príncipes Ben-Hail, Obadias, Zacarias, Natanael e Micaías, para ensinarem nas cidades de Judá;

[[v14-17-8]]

^<<v14-17-8,8>>^ e, com eles, os levitas Semaías, Netanias, Zebadias, Asael, Semiramote, Jônatas, Adonias, Tobias e Tobe-Adonias; e, com estes levitas, os sacerdotes Elisama e Jeorão.

[[v14-17-9]]

^<<v14-17-9,9>>^ Ensinaram em Judá, tendo consigo o Livro da Lei do SENHOR; percorriam todas as cidades de Judá e ensinavam ao povo.

[[v14-17-10]]

^<<v14-17-10,10>>^ Veio o terror do SENHOR sobre todos os reinos das terras que estavam ao redor de Judá, de maneira que não fizeram guerra contra Josafá.

[[v14-17-11]]

^<<v14-17-11,11>>^ Alguns dos filisteus traziam presentes a Josafá e prata como tributo; também os arábios lhe trouxeram gado miúdo, sete mil e setecentos carneiros e sete mil e setecentos bodes.

[[v14-17-12]]

^<<v14-17-12,12>>^ Josafá se engrandeceu em extremo, continuamente; e edificou fortalezas e cidades-armazéns em Judá.

[[v14-17-13]]

^<<v14-17-13,13>>^ Empreendeu muitas obras nas cidades de Judá; e tinha, em Jerusalém, gente de guerra e homens valentes.

[[v14-17-14]]

^<<v14-17-14,14>>^ Este é o número deles segundo as suas famílias: em Judá, eram capitães de mil: o chefe Adna e, com ele, trezentos mil homens valentes;

[[v14-17-15]]

^<<v14-17-15,15>>^ depois dele, o capitão Joanã e, com ele, duzentos e oitenta mil;

[[v14-17-16]]

^<<v14-17-16,16>>^ e, depois, Amasias, filho de Zicri, que, voluntariamente, se ofereceu ao serviço do SENHOR, e, às suas ordens, duzentos mil homens valentes.

[[v14-17-17]]

^<<v14-17-17,17>>^ De Benjamim, Eliada, homem valente, e, com ele, duzentos mil, armados de arco e de escudo;

[[v14-17-18]]

^<<v14-17-18,18>>^ depois dele, Jozabade, com cento e oitenta mil armados para a guerra.

[[v14-17-19]]

^<<v14-17-19,19>>^ Estavam estes no serviço do rei, afora os que o rei tinha posto nas cidades fortificadas por todo o Judá.

'''

xref:014-2-cronicas/014-2-cronicas-016.adoc#v14-16-0[&#60; Capítulo Anterior] | <<v14-17-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-018.adoc#v14-18-0[Próximo Capítulo &#62;]