include::./index.adoc[]

[[v14-6-0]]
=== 2 Crônicas, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-6-1]]

^<<v14-6-1,1>>^ Então, disse Salomão: O SENHOR declarou que habitaria em nuvem espessa!

[[v14-6-2]]

^<<v14-6-2,2>>^ Edifiquei uma casa para tua morada, lugar para a tua eterna habitação.

[[v14-6-3]]

^<<v14-6-3,3>>^ Voltou, então, o rei o rosto, e abençoou a toda a congregação de Israel, enquanto ela se mantinha em pé,

[[v14-6-4]]

^<<v14-6-4,4>>^ e disse: Bendito seja o SENHOR, o Deus de Israel, que falou pessoalmente a Davi, meu pai, e pelo seu poder o cumpriu, dizendo:

[[v14-6-5]]

^<<v14-6-5,5>>^ Desde o dia em que eu tirei o meu povo da terra do Egito, não escolhi cidade alguma de todas as tribos de Israel, para edificar uma casa a fim de ali estabelecer o meu nome; nem escolhi homem algum para chefe do meu povo de Israel.

[[v14-6-6]]

^<<v14-6-6,6>>^ Mas escolhi Jerusalém para que ali seja estabelecido o meu nome e escolhi a Davi para chefe do meu povo de Israel.

[[v14-6-7]]

^<<v14-6-7,7>>^ Também Davi, meu pai, propusera em seu coração o edificar uma casa ao nome do SENHOR, o Deus de Israel.

[[v14-6-8]]

^<<v14-6-8,8>>^ Porém o SENHOR disse a Davi, meu pai: Já que desejaste edificar uma casa ao meu nome, bem fizeste em o resolver em teu coração.

[[v14-6-9]]

^<<v14-6-9,9>>^ Todavia, tu não edificarás a casa; porém teu filho, que descenderá de ti, ele a edificará ao meu nome.

[[v14-6-10]]

^<<v14-6-10,10>>^ Assim, cumpriu o SENHOR a sua palavra que tinha dito, pois me levantei em lugar de Davi, meu pai, e me assentei no trono de Israel, como prometera o SENHOR; e edifiquei a casa ao nome do SENHOR, o Deus de Israel.

[[v14-6-11]]

^<<v14-6-11,11>>^ Nela pus a arca em que estão as tábuas da aliança que o SENHOR fez com os filhos de Israel.

[[v14-6-12]]

^<<v14-6-12,12>>^ Pôs-se Salomão diante do altar do SENHOR, na presença de toda a congregação de Israel, e estendeu as mãos.

[[v14-6-13]]

^<<v14-6-13,13>>^ Porque Salomão tinha feito uma tribuna de bronze, de cinco côvados de comprimento, cinco de largura e três de altura, e a pusera no meio do pátio; pôs-se em pé sobre ela, ajoelhou-se em presença de toda a congregação de Israel, estendeu as mãos para o céu

[[v14-6-14]]

^<<v14-6-14,14>>^ e disse: Ó SENHOR, Deus de Israel, não há Deus como tu, nos céus e na terra, como tu que guardas a aliança e a misericórdia a teus servos que de todo o coração andam diante de ti;

[[v14-6-15]]

^<<v14-6-15,15>>^ que cumpriste para com teu servo Davi, meu pai, o que lhe prometeste; pessoalmente, o disseste e, pelo teu poder, o cumpriste, como hoje se vê.

[[v14-6-16]]

^<<v14-6-16,16>>^ Agora, pois, ó SENHOR, Deus de Israel, faze a teu servo Davi, meu pai, o que lhe declaraste, dizendo: Não te faltará sucessor diante de mim, que se assente no trono de Israel, contanto que teus filhos guardem o seu caminho, para andarem na lei diante de mim, como tu andaste.

[[v14-6-17]]

^<<v14-6-17,17>>^ Agora, também, ó SENHOR, Deus de Israel, cumpra-se a tua palavra que disseste a teu servo Davi.

[[v14-6-18]]

^<<v14-6-18,18>>^ Mas, de fato, habitaria Deus com os homens na terra? Eis que os céus e até o céu dos céus não te podem conter, quanto menos esta casa que eu edifiquei.

[[v14-6-19]]

^<<v14-6-19,19>>^ Atenta, pois, para a oração de teu servo e para a sua súplica, ó SENHOR, meu Deus, para ouvires o clamor e a oração que faz o teu servo diante de ti.

[[v14-6-20]]

^<<v14-6-20,20>>^ Para que os teus olhos estejam abertos dia e noite sobre esta casa, sobre este lugar, do qual disseste que o teu nome estaria ali; para ouvires a oração que o teu servo fizer neste lugar.

[[v14-6-21]]

^<<v14-6-21,21>>^ Ouve, pois, a súplica do teu servo e do teu povo de Israel, quando orarem neste lugar; ouve do lugar da tua habitação, dos céus; ouve e perdoa.

[[v14-6-22]]

^<<v14-6-22,22>>^ Quando alguém pecar contra o seu próximo, e lhe for exigido que jure, e ele vier a jurar diante do teu altar nesta casa,

[[v14-6-23]]

^<<v14-6-23,23>>^ ouve tu dos céus, age e julga a teus servos, dando a paga ao perverso, fazendo recair o seu proceder sobre a sua cabeça e justificando ao justo, para lhe retribuíres segundo a sua justiça.

[[v14-6-24]]

^<<v14-6-24,24>>^ Quando o teu povo de Israel, por ter pecado contra ti, for ferido diante do inimigo, e se converter, e confessar o teu nome, e orar, e suplicar diante de ti nesta casa,

[[v14-6-25]]

^<<v14-6-25,25>>^ ouve tu dos céus, e perdoa o pecado do teu povo de Israel, e faze-o voltar à terra que lhe deste e a seus pais.

[[v14-6-26]]

^<<v14-6-26,26>>^ Quando os céus se cerrarem, e não houver chuva, por ter o povo pecado contra ti, e ele orar neste lugar, e confessar o teu nome, e se converter dos seus pecados, havendo-o tu afligido,

[[v14-6-27]]

^<<v14-6-27,27>>^ ouve tu nos céus, perdoa o pecado de teus servos e do teu povo de Israel, ensinando-lhes o bom caminho em que andem, e dá chuva na tua terra que deste em herança ao teu povo.

[[v14-6-28]]

^<<v14-6-28,28>>^ Quando houver fome na terra ou peste, quando houver crestamento ou ferrugem, gafanhotos e larvas, quando o seu inimigo o cercar em qualquer das suas cidades ou houver alguma praga ou doença,

[[v14-6-29]]

^<<v14-6-29,29>>^ toda oração e súplica, que qualquer homem ou todo o teu povo de Israel fizer, conhecendo cada um a sua própria chaga e a sua dor, e estendendo as mãos para o rumo desta casa,

[[v14-6-30]]

^<<v14-6-30,30>>^ ouve tu dos céus, lugar da tua habitação, perdoa e dá a cada um segundo todos os seus caminhos, já que lhe conheces o coração, porque tu, só tu, és conhecedor do coração dos filhos dos homens;

[[v14-6-31]]

^<<v14-6-31,31>>^ para que te temam, para andarem nos teus caminhos, todos os dias que viverem na terra que deste a nossos pais.

[[v14-6-32]]

^<<v14-6-32,32>>^ Também ao estrangeiro que não for do teu povo de Israel, porém vier de terras remotas, por amor do teu grande nome e por causa da tua mão poderosa e do teu braço estendido, e orar, voltado para esta casa,

[[v14-6-33]]

^<<v14-6-33,33>>^ ouve tu dos céus, do lugar da tua habitação, e faze tudo o que o estrangeiro te pedir, a fim de que todos os povos da terra conheçam o teu nome, para te temerem como o teu povo de Israel e para saberem que esta casa, que eu edifiquei, é chamada pelo teu nome.

[[v14-6-34]]

^<<v14-6-34,34>>^ Quando o teu povo sair à guerra contra o seu inimigo, pelo caminho por que os enviares, e orarem a ti, voltados para esta cidade, que tu escolheste, e para a casa que edifiquei ao teu nome,

[[v14-6-35]]

^<<v14-6-35,35>>^ ouve tu dos céus a sua oração e a sua súplica e faze-lhes justiça.

[[v14-6-36]]

^<<v14-6-36,36>>^ Quando pecarem contra ti (pois não há homem que não peque), e tu te indignares contra eles e os entregares às mãos do inimigo, a fim de que os leve cativos a uma terra, longe ou perto esteja;

[[v14-6-37]]

^<<v14-6-37,37>>^ e na terra aonde forem levados caírem em si, e se converterem, e na terra do seu cativeiro te suplicarem, dizendo: Pecamos, e perversamente procedemos, e cometemos iniquidade; e se converterem a ti de todo o seu coração e de toda a sua alma,

[[v14-6-38]]

^<<v14-6-38,38>>^ na terra do seu cativeiro, para onde foram levados cativos, e orarem, voltados para a sua terra que deste a seus pais, para esta cidade que escolheste e para a casa que edifiquei ao teu nome,

[[v14-6-39]]

^<<v14-6-39,39>>^ ouve tu dos céus, do lugar da tua habitação, a sua prece e a sua súplica e faze-lhes justiça; perdoa ao teu povo que houver pecado contra ti.

[[v14-6-40]]

^<<v14-6-40,40>>^ Agora, pois, ó meu Deus, estejam os teus olhos abertos, e os teus ouvidos atentos à oração que se fizer deste lugar.

[[v14-6-41]]

^<<v14-6-41,41>>^ Levanta-te, pois, SENHOR Deus, e entra para o teu repouso, tu e a arca do teu poder; os teus sacerdotes, ó SENHOR Deus, se revistam de salvação, e os teus santos se alegrem do bem.

[[v14-6-42]]

^<<v14-6-42,42>>^ Ah! SENHOR Deus, não repulses o teu ungido; lembra-te das misericórdias que usaste para com Davi, teu servo.

'''

xref:014-2-cronicas/014-2-cronicas-005.adoc#v14-5-0[&#60; Capítulo Anterior] | <<v14-6-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-007.adoc#v14-7-0[Próximo Capítulo &#62;]