include::./index.adoc[]

[[v14-13-0]]
=== 2 Crônicas, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-13-1]]

^<<v14-13-1,1>>^ No décimo oitavo ano do rei Jeroboão, Abias começou a reinar sobre Judá. Três anos reinou em Jerusalém.

[[v14-13-2]]

^<<v14-13-2,2>>^ Era o nome de sua mãe Micaía, filha de Uriel, de Gibeá. Também houve guerra entre Abias e Jeroboão.

[[v14-13-3]]

^<<v14-13-3,3>>^ Abias ordenou a peleja com um exército de valentes guerreiros, de quatrocentos mil homens escolhidos; e Jeroboão dispôs contra ele a batalha com oitocentos mil homens escolhidos, todos guerreiros valentes.

[[v14-13-4]]

^<<v14-13-4,4>>^ Pôs-se Abias em pé no alto do monte Zemaraim, que está na região montanhosa de Efraim, e disse: Ouvi-me, Jeroboão e todo o Israel:

[[v14-13-5]]

^<<v14-13-5,5>>^ Não vos convém saber que o SENHOR, Deus de Israel, deu para sempre a Davi a soberania de Israel, a ele e a seus filhos, por uma aliança de sal?

[[v14-13-6]]

^<<v14-13-6,6>>^ Contudo, se levantou Jeroboão, filho de Nebate, servo de Salomão, filho de Davi, e se rebelou contra seu senhor.

[[v14-13-7]]

^<<v14-13-7,7>>^ Ajuntou-se a ele gente vadia, homens malignos; fortificaram-se contra Roboão, filho de Salomão; sendo Roboão ainda jovem e indeciso, não lhes pôde resistir.

[[v14-13-8]]

^<<v14-13-8,8>>^ Agora, pensais que podeis resistir ao reino do SENHOR, que está nas mãos dos filhos de Davi; bem sois vós uma grande multidão e tendes convosco os bezerros de ouro que Jeroboão vos fez para deuses.

[[v14-13-9]]

^<<v14-13-9,9>>^ Não lançastes fora os sacerdotes do SENHOR, os filhos de Arão e os levitas, e não fizestes para vós outros sacerdotes, como as gentes das outras terras? Qualquer que vem a consagrar-se com um novilho e sete carneiros logo se faz sacerdote daqueles que não são deuses.

[[v14-13-10]]

^<<v14-13-10,10>>^ Porém, quanto a nós, o SENHOR é nosso Deus, e nunca o deixamos; temos sacerdotes, que ministram ao SENHOR, a saber, os filhos de Arão e os levitas na sua obra.

[[v14-13-11]]

^<<v14-13-11,11>>^ Cada dia, de manhã e à tarde, oferecem holocaustos e queimam incenso aromático, dispondo os pães da proposição sobre a mesa puríssima e o candeeiro de ouro e as suas lâmpadas para se acenderem cada tarde, porque nós guardamos o preceito do SENHOR, nosso Deus; porém vós o deixastes.

[[v14-13-12]]

^<<v14-13-12,12>>^ Eis que Deus está conosco, à nossa frente, como também os seus sacerdotes, tocando com as trombetas, para rebate contra vós outros, ó filhos de Israel; não pelejeis contra o SENHOR, Deus de vossos pais, porque não sereis bem-sucedidos.

[[v14-13-13]]

^<<v14-13-13,13>>^ Mas Jeroboão ordenou aos que estavam de emboscada que fizessem uma volta e dessem contra eles por detrás; de maneira que estavam em frente dos homens de Judá, e a emboscada, por detrás deles.

[[v14-13-14]]

^<<v14-13-14,14>>^ Olhou Judá e viu que a peleja estava por diante e por detrás; então, clamaram ao SENHOR, e os sacerdotes tocaram as trombetas.

[[v14-13-15]]

^<<v14-13-15,15>>^ Os homens de Judá gritaram; quando gritavam, feriu Deus a Jeroboão e a todo o Israel diante de Abias e de Judá.

[[v14-13-16]]

^<<v14-13-16,16>>^ Os filhos de Israel fugiram de diante de Judá, pois Deus os entregara nas suas mãos.

[[v14-13-17]]

^<<v14-13-17,17>>^ De maneira que Abias e o seu povo fizeram grande matança entre eles; porque caíram feridos de Israel quinhentos mil homens escolhidos.

[[v14-13-18]]

^<<v14-13-18,18>>^ Assim, foram humilhados os filhos de Israel naquele tempo; prevaleceram os filhos de Judá, porque confiaram no SENHOR, Deus de seus pais.

[[v14-13-19]]

^<<v14-13-19,19>>^ Abias perseguiu a Jeroboão e lhe tomou cidades: Betel, Jesana e Efrom, com suas respectivas vilas.

[[v14-13-20]]

^<<v14-13-20,20>>^ Jeroboão não restaurou mais o seu poder no tempo de Abias; feriu o SENHOR a Jeroboão, que morreu.

[[v14-13-21]]

^<<v14-13-21,21>>^ Abias, porém, se fortificou, e tomou para si catorze mulheres, e gerou vinte e dois filhos e dezesseis filhas.

[[v14-13-22]]

^<<v14-13-22,22>>^ Quanto aos mais atos de Abias, tanto o que fez como o que disse, estão escritos no Livro da História do Profeta Ido.

'''

xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[&#60; Capítulo Anterior] | <<v14-13-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-014.adoc#v14-14-0[Próximo Capítulo &#62;]