include::./index.adoc[]

[[v14-26-0]]
=== 2 Crônicas, 26
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-26-1]]

^<<v14-26-1,1>>^ Todo o povo de Judá tomou a Uzias, que era de dezesseis anos, e o constituiu rei em lugar de Amazias, seu pai.

[[v14-26-2]]

^<<v14-26-2,2>>^ Ele edificou a Elate e a restituiu a Judá, depois que o rei descansou com seus pais.

[[v14-26-3]]

^<<v14-26-3,3>>^ Uzias tinha dezesseis anos quando começou a reinar e cinquenta e dois anos reinou em Jerusalém. Era o nome de sua mãe Jecolias, de Jerusalém.

[[v14-26-4]]

^<<v14-26-4,4>>^ Ele fez o que era reto perante o SENHOR, segundo tudo o que fizera Amazias, seu pai.

[[v14-26-5]]

^<<v14-26-5,5>>^ Propôs-se buscar a Deus nos dias de Zacarias, que era sábio nas visões de Deus; nos dias em que buscou ao SENHOR, Deus o fez prosperar.

[[v14-26-6]]

^<<v14-26-6,6>>^ Saiu e guerreou contra os filisteus e quebrou o muro de Gate, o de Jabné e o de Asdode; e edificou cidades no território de Asdode e entre os filisteus.

[[v14-26-7]]

^<<v14-26-7,7>>^ Deus o ajudou contra os filisteus, e contra os arábios que habitavam em Gur-Baal, e contra os meunitas.

[[v14-26-8]]

^<<v14-26-8,8>>^ Os amonitas deram presentes a Uzias, cujo renome se espalhara até à entrada do Egito, porque se tinha tornado em extremo forte.

[[v14-26-9]]

^<<v14-26-9,9>>^ Também edificou Uzias torres em Jerusalém, à Porta da Esquina, à Porta do Vale e à Porta do Ângulo e as fortificou.

[[v14-26-10]]

^<<v14-26-10,10>>^ Também edificou torres no deserto e cavou muitas cisternas, porque tinha muito gado, tanto nos vales como nas campinas; tinha lavradores e vinhateiros, nos montes e nos campos férteis, porque era amigo da agricultura.

[[v14-26-11]]

^<<v14-26-11,11>>^ Tinha também Uzias um exército de homens destros nas armas, que saíam à guerra em tropas, segundo o rol feito pelo escrivão Jeiel e Maaseias, oficial, sob a direção de Hananias, um dos príncipes do rei.

[[v14-26-12]]

^<<v14-26-12,12>>^ O número total dos cabeças das famílias, homens valentes, era de dois mil e seiscentos.

[[v14-26-13]]

^<<v14-26-13,13>>^ Debaixo das suas ordens, havia um exército guerreiro de trezentos e sete mil e quinhentos homens, que faziam a guerra com grande poder, para ajudar o rei contra os inimigos.

[[v14-26-14]]

^<<v14-26-14,14>>^ Preparou-lhes Uzias, para todo o exército, escudos, lanças, capacetes, couraças e arcos e até fundas para atirar pedras.

[[v14-26-15]]

^<<v14-26-15,15>>^ Fabricou em Jerusalém máquinas, de invenção de homens peritos, destinadas para as torres e cantos das muralhas, para atirarem flechas e grandes pedras; divulgou-se a sua fama até muito longe, porque foi maravilhosamente ajudado, até que se tornou forte.

[[v14-26-16]]

^<<v14-26-16,16>>^ Mas, havendo-se já fortificado, exaltou-se o seu coração para a sua própria ruína, e cometeu transgressões contra o SENHOR, seu Deus, porque entrou no templo do SENHOR para queimar incenso no altar do incenso.

[[v14-26-17]]

^<<v14-26-17,17>>^ Porém o sacerdote Azarias entrou após ele, com oitenta sacerdotes do SENHOR, homens da maior firmeza;

[[v14-26-18]]

^<<v14-26-18,18>>^ e resistiram ao rei Uzias e lhe disseram: A ti, Uzias, não compete queimar incenso perante o SENHOR, mas aos sacerdotes, filhos de Arão, que são consagrados para este mister; sai do santuário, porque transgrediste; nem será isso para honra tua da parte do SENHOR Deus.

[[v14-26-19]]

^<<v14-26-19,19>>^ Então, Uzias se indignou; tinha o incensário na mão para queimar incenso; indignando-se ele, pois, contra os sacerdotes, a lepra lhe saiu na testa perante os sacerdotes, na Casa do SENHOR, junto ao altar do incenso.

[[v14-26-20]]

^<<v14-26-20,20>>^ Então, o sumo sacerdote Azarias e todos os sacerdotes voltaram-se para ele, e eis que estava leproso na testa, e apressadamente o lançaram fora; até ele mesmo se deu pressa em sair, visto que o SENHOR o ferira.

[[v14-26-21]]

^<<v14-26-21,21>>^ Assim, ficou leproso o rei Uzias até ao dia da sua morte; e morou, por ser leproso, numa casa separada, porque foi excluído da Casa do SENHOR; e Jotão, seu filho, tinha a seu cargo a casa do rei, julgando o povo da terra.

[[v14-26-22]]

^<<v14-26-22,22>>^ Quanto aos mais atos de Uzias, tanto os primeiros como os últimos, o profeta Isaías, filho de Amoz, os escreveu.

[[v14-26-23]]

^<<v14-26-23,23>>^ Descansou Uzias com seus pais, e, com seus pais, o sepultaram no campo do sepulcro que era dos reis; porque disseram: Ele é leproso. E Jotão, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[&#60; Capítulo Anterior] | <<v14-26-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[Próximo Capítulo &#62;]