include::./index.adoc[]

[[v14-25-0]]
=== 2 Crônicas, 25
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-25-1]]

^<<v14-25-1,1>>^ Era Amazias da idade de vinte e cinco anos quando começou a reinar e reinou vinte e nove anos em Jerusalém; sua mãe se chamava Jeoadã, de Jerusalém.

[[v14-25-2]]

^<<v14-25-2,2>>^ Fez ele o que era reto perante o SENHOR; não, porém, com inteireza de coração.

[[v14-25-3]]

^<<v14-25-3,3>>^ Uma vez confirmado o reino nas suas mãos, matou os seus servos que tinham assassinado o rei, seu pai.

[[v14-25-4]]

^<<v14-25-4,4>>^ Porém os filhos deles não matou, mas fez segundo está escrito na Lei, no Livro de Moisés, no qual o SENHOR deu ordem, dizendo: Os pais não serão mortos por causa dos filhos, nem os filhos, por causa dos pais; cada qual será morto pelo seu próprio pecado.

[[v14-25-5]]

^<<v14-25-5,5>>^ Amazias congregou a Judá e o pôs, segundo as suas famílias, sob chefes de mil e chefes de cem, por todo o Judá e Benjamim; contou-os de vinte anos para cima e achou trezentos mil escolhidos capazes de sair à guerra e manejar lança e escudo.

[[v14-25-6]]

^<<v14-25-6,6>>^ Também tomou de Israel a soldo cem mil homens valentes por cem talentos de prata.

[[v14-25-7]]

^<<v14-25-7,7>>^ Porém certo homem de Deus veio a ele, dizendo: Ó rei, não deixes ir contigo o exército de Israel; porque o SENHOR não é com Israel, isto é, com os filhos de Efraim.

[[v14-25-8]]

^<<v14-25-8,8>>^ Porém vai só, age e sê forte; do contrário, Deus te faria cair diante do inimigo, porque Deus tem força para ajudar e para fazer cair.

[[v14-25-9]]

^<<v14-25-9,9>>^ Disse Amazias ao homem de Deus: Que se fará, pois, dos cem talentos de prata que dei às tropas de Israel? Respondeu-lhe o homem de Deus: Muito mais do que isso pode dar-te o SENHOR.

[[v14-25-10]]

^<<v14-25-10,10>>^ Então, separou Amazias as tropas que lhe tinham vindo de Efraim para que voltassem para casa; pelo que muito se acendeu a ira deles contra Judá, e voltaram para casa ardendo em ira.

[[v14-25-11]]

^<<v14-25-11,11>>^ Animou-se Amazias e, conduzindo o seu povo, foi-se ao vale do Sal, onde feriu dez mil dos filhos de Seir.

[[v14-25-12]]

^<<v14-25-12,12>>^ Também os filhos de Judá prenderam vivos dez mil e os trouxeram ao cimo de um penhasco, de onde os precipitaram, de modo que todos foram esmigalhados.

[[v14-25-13]]

^<<v14-25-13,13>>^ Porém os homens das tropas que Amazias despedira, para que não fossem com ele à peleja, deram sobre as cidades de Judá, desde Samaria até Bete-Horom; feriram deles três mil e fizeram grande despojo.

[[v14-25-14]]

^<<v14-25-14,14>>^ Vindo Amazias da matança dos edomitas, trouxe consigo os deuses dos filhos de Seir, tomou-os por seus deuses, adorou-os e lhes queimou incenso.

[[v14-25-15]]

^<<v14-25-15,15>>^ Então, a ira do SENHOR se acendeu contra Amazias, e mandou-lhe um profeta que lhe disse: Por que buscaste deuses que a seu povo não livraram das tuas mãos?

[[v14-25-16]]

^<<v14-25-16,16>>^ Enquanto lhe falava o profeta, disse-lhe o rei: Acaso, te pusemos por conselheiro do rei? Para com isso. Por que teríamos de ferir-te? Então, parou o profeta, mas disse: Sei que Deus resolveu destruir-te, porque fizeste isso e não deste ouvidos ao meu conselho.

[[v14-25-17]]

^<<v14-25-17,17>>^ Então, Amazias, rei de Judá, tomou conselho e enviou mensageiros a Jeoás, filho de Jeoacaz, filho de Jeú, rei de Israel, dizendo: Vem, meçamos armas.

[[v14-25-18]]

^<<v14-25-18,18>>^ Porém Jeoás, rei de Israel, respondeu a Amazias, rei de Judá: O cardo que está no Líbano mandou dizer ao cedro que lá está: Dá tua filha por mulher a meu filho; mas os animais do campo, que estavam no Líbano, passaram e pisaram o cardo.

[[v14-25-19]]

^<<v14-25-19,19>>^ Tu dizes: Eis que feri os edomitas; e o teu coração se ensoberbeceu para te gloriares; agora, fica em casa; por que provocarias o mal para caíres tu, e Judá, contigo?

[[v14-25-20]]

^<<v14-25-20,20>>^ Mas Amazias não quis atendê-lo; porque isto vinha de Deus, para entregá-los nas mãos dos seus inimigos, porquanto buscaram os deuses dos edomitas.

[[v14-25-21]]

^<<v14-25-21,21>>^ Subiu, então, Jeoás, rei de Israel, e Amazias, rei de Judá, e mediram armas em Bete-Semes, que pertence a Judá.

[[v14-25-22]]

^<<v14-25-22,22>>^ Judá foi derrotado por Israel, e fugiu cada um para sua casa.

[[v14-25-23]]

^<<v14-25-23,23>>^ E Jeoás, rei de Israel, prendeu a Amazias, rei de Judá, filho de Joás, filho de Jeoacaz, em Bete-Semes; levou-o a Jerusalém, cujo muro ele rompeu desde a Porta de Efraim até à Porta da Esquina, quatrocentos côvados.

[[v14-25-24]]

^<<v14-25-24,24>>^ Tomou todo o ouro e a prata, e todos os utensílios que se acharam na Casa de Deus, com Obede-Edom, e os tesouros da casa do rei, como também reféns; e voltou para Samaria.

[[v14-25-25]]

^<<v14-25-25,25>>^ Amazias, filho de Joás, rei de Judá, viveu quinze anos depois da morte de Jeoás, filho de Jeoacaz, rei de Israel.

[[v14-25-26]]

^<<v14-25-26,26>>^ Ora, os mais atos de Amazias, tanto os primeiros como os últimos, porventura, não estão escritos no Livro da História dos Reis de Judá e de Israel?

[[v14-25-27]]

^<<v14-25-27,27>>^ Depois que Amazias deixou de seguir ao SENHOR, conspiraram contra ele em Jerusalém, e ele fugiu para Laquis; porém enviaram após ele homens até Laquis e o mataram ali.

[[v14-25-28]]

^<<v14-25-28,28>>^ Trouxeram-no sobre cavalos e o sepultaram junto a seus pais na Cidade de Davi.

'''

xref:014-2-cronicas/014-2-cronicas-024.adoc#v14-24-0[&#60; Capítulo Anterior] | <<v14-25-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-026.adoc#v14-26-0[Próximo Capítulo &#62;]