include::./index.adoc[]

[[v14-30-0]]
=== 2 Crônicas, 30
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-30-1]]

^<<v14-30-1,1>>^ Depois disto, Ezequias enviou mensageiros por todo o Israel e Judá; escreveu também cartas a Efraim e a Manassés para que viessem à Casa do SENHOR, em Jerusalém, para celebrarem a Páscoa ao SENHOR, Deus de Israel.

[[v14-30-2]]

^<<v14-30-2,2>>^ Porque o rei tivera conselho com os seus príncipes e com toda a congregação em Jerusalém, para celebrarem a Páscoa no segundo mês

[[v14-30-3]]

^<<v14-30-3,3>>^ (Porquanto não a puderam celebrar no devido tempo, porque não se tinham santificado sacerdotes em número suficiente, e o povo não se ajuntara ainda em Jerusalém.).

[[v14-30-4]]

^<<v14-30-4,4>>^ Foi isto aprovado pelo rei e toda a congregação;

[[v14-30-5]]

^<<v14-30-5,5>>^ e resolveram que se fizesse pregão por todo o Israel, desde Berseba até Dã, para que viessem a celebrar a Páscoa ao SENHOR, Deus de Israel, em Jerusalém; porque não a celebravam já com grande número de assistentes, como prescrito.

[[v14-30-6]]

^<<v14-30-6,6>>^ Partiram os correios com as cartas do rei e dos seus príncipes, por todo o Israel e Judá, segundo o mandado do rei, dizendo: Filhos de Israel, voltai-vos ao SENHOR, Deus de Abraão, de Isaque e de Israel, para que ele se volte para o restante que escapou do poder dos reis da Assíria.

[[v14-30-7]]

^<<v14-30-7,7>>^ Não sejais como vossos pais e como vossos irmãos, que prevaricaram contra o SENHOR, Deus de seus pais, pelo que os entregou à desolação, como estais vendo.

[[v14-30-8]]

^<<v14-30-8,8>>^ Não endureçais, agora, a vossa cerviz, como vossos pais; confiai-vos ao SENHOR, e vinde ao seu santuário que ele santificou para sempre, e servi ao SENHOR, vosso Deus, para que o ardor da sua ira se desvie de vós.

[[v14-30-9]]

^<<v14-30-9,9>>^ Porque, se vós vos converterdes ao SENHOR, vossos irmãos e vossos filhos acharão misericórdia perante os que os levaram cativos e tornarão a esta terra; porque o SENHOR, vosso Deus, é misericordioso e compassivo e não desviará de vós o rosto, se vos converterdes a ele.

[[v14-30-10]]

^<<v14-30-10,10>>^ Os correios foram passando de cidade em cidade, pela terra de Efraim e Manassés até Zebulom; porém riram-se e zombaram deles.

[[v14-30-11]]

^<<v14-30-11,11>>^ Todavia, alguns de Aser, de Manassés e de Zebulom se humilharam e foram a Jerusalém.

[[v14-30-12]]

^<<v14-30-12,12>>^ Também em Judá se fez sentir a mão de Deus, dando-lhes um só coração, para cumprirem o mandado do rei e dos príncipes, segundo a palavra do SENHOR.

[[v14-30-13]]

^<<v14-30-13,13>>^ Ajuntou-se em Jerusalém muito povo, para celebrar a Festa dos Pães Asmos, no segundo mês, mui grande congregação.

[[v14-30-14]]

^<<v14-30-14,14>>^ Dispuseram-se e tiraram os altares que havia em Jerusalém; também tiraram todos os altares do incenso e os lançaram no vale de Cedrom.

[[v14-30-15]]

^<<v14-30-15,15>>^ Então, imolaram o cordeiro da Páscoa no décimo quarto dia do segundo mês; os sacerdotes e os levitas se envergonharam, e se santificaram, e trouxeram holocaustos à Casa do SENHOR.

[[v14-30-16]]

^<<v14-30-16,16>>^ Tomaram os seus devidos lugares, segundo a Lei de Moisés, o homem de Deus; e os sacerdotes aspergiam o sangue, tomando-o das mãos dos levitas.

[[v14-30-17]]

^<<v14-30-17,17>>^ Porque havia muitos na congregação que não se tinham santificado; pelo que os levitas estavam encarregados de imolar os cordeiros da Páscoa por todo aquele que não estava limpo, para o santificarem ao SENHOR.

[[v14-30-18]]

^<<v14-30-18,18>>^ Porque uma multidão do povo, muitos de Efraim, de Manassés, de Issacar e de Zebulom não se tinham purificado e, contudo, comeram a Páscoa, não como está escrito; porém Ezequias orou por eles, dizendo: O SENHOR, que é bom, perdoe a todo aquele

[[v14-30-19]]

^<<v14-30-19,19>>^ que dispôs o coração para buscar o SENHOR Deus, o Deus de seus pais, ainda que não segundo a purificação exigida pelo santuário.

[[v14-30-20]]

^<<v14-30-20,20>>^ Ouviu o SENHOR a Ezequias e sarou a alma do povo.

[[v14-30-21]]

^<<v14-30-21,21>>^ Os filhos de Israel que se acharam em Jerusalém celebraram a Festa dos Pães Asmos por sete dias, com grande júbilo; e os levitas e os sacerdotes louvaram ao SENHOR de dia em dia, com instrumentos que tocaram fortemente em honra ao SENHOR.

[[v14-30-22]]

^<<v14-30-22,22>>^ Ezequias falou ao coração de todos os levitas que revelavam bom entendimento no serviço do SENHOR; e comeram, por sete dias, as ofertas da festa, trouxeram ofertas pacíficas e renderam graças ao SENHOR, Deus de seus pais.

[[v14-30-23]]

^<<v14-30-23,23>>^ Concordou toda a congregação em celebrar outros sete dias, e, de fato, o fizeram com júbilo;

[[v14-30-24]]

^<<v14-30-24,24>>^ pois Ezequias, rei de Judá, apresentou à congregação mil novilhos e sete mil ovelhas para sacrifício; e os príncipes apresentaram à congregação mil novilhos e dez mil ovelhas; e os sacerdotes se santificaram em grande número.

[[v14-30-25]]

^<<v14-30-25,25>>^ Alegraram-se toda a congregação de Judá, os sacerdotes, os levitas e toda a congregação de todos os que vieram de Israel, como também os estrangeiros que vieram da terra de Israel e os que habitavam em Judá.

[[v14-30-26]]

^<<v14-30-26,26>>^ Houve grande alegria em Jerusalém; porque desde os dias de Salomão, filho de Davi, rei de Israel, não houve coisa semelhante em Jerusalém.

[[v14-30-27]]

^<<v14-30-27,27>>^ Então, os sacerdotes e os levitas se levantaram para abençoar o povo; a sua voz foi ouvida, e a sua oração chegou até à santa habitação de Deus, até aos céus.

'''

xref:014-2-cronicas/014-2-cronicas-029.adoc#v14-29-0[&#60; Capítulo Anterior] | <<v14-30-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-031.adoc#v14-31-0[Próximo Capítulo &#62;]