include::./index.adoc[]

[[v14-3-0]]
=== 2 Crônicas, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-3-1]]

^<<v14-3-1,1>>^ Começou Salomão a edificar a Casa do SENHOR em Jerusalém, no monte Moriá, onde o SENHOR aparecera a Davi, seu pai, lugar que Davi tinha designado na eira de Ornã, o jebuseu.

[[v14-3-2]]

^<<v14-3-2,2>>^ Começou a edificar no segundo mês, no dia segundo, no ano quarto do seu reinado.

[[v14-3-3]]

^<<v14-3-3,3>>^ Foram estas as medidas dos alicerces que Salomão lançou para edificar a Casa de Deus: o comprimento em côvados, segundo o primitivo padrão, sessenta côvados, e a largura, vinte.

[[v14-3-4]]

^<<v14-3-4,4>>^ O pórtico diante da casa media vinte côvados no sentido da largura do Lugar Santo, e a altura, cento e vinte, o que, dentro, cobriu de ouro puro.

[[v14-3-5]]

^<<v14-3-5,5>>^ Também fez forrar de madeira de cipreste a sala grande, e a cobriu de ouro puro, e gravou nela palmas e cadeias.

[[v14-3-6]]

^<<v14-3-6,6>>^ Também adornou a sala de pedras preciosas; e o ouro era de Parvaim.

[[v14-3-7]]

^<<v14-3-7,7>>^ Cobriu também de ouro a sala, as traves, os umbrais, as paredes e as portas; e lavrou querubins nas paredes.

[[v14-3-8]]

^<<v14-3-8,8>>^ Fez mais o Santo dos Santos, cujo comprimento, segundo a largura da sala grande, era de vinte côvados, e também a largura, de vinte; cobriu-a de ouro puro do peso de seiscentos talentos.

[[v14-3-9]]

^<<v14-3-9,9>>^ O peso dos pregos era de cinquenta siclos de ouro. Cobriu de ouro os cenáculos.

[[v14-3-10]]

^<<v14-3-10,10>>^ No Santo dos Santos, fez dois querubins de madeira e os cobriu de ouro.

[[v14-3-11]]

^<<v14-3-11,11>>^ As asas estendidas, juntas, dos querubins mediam o comprimento de vinte côvados; a asa de um deles, de cinco côvados, tocava na parede da casa; e a outra asa, de cinco côvados, tocava na asa do outro querubim.

[[v14-3-12]]

^<<v14-3-12,12>>^ Também a asa do outro querubim era de cinco côvados e tocava na outra parede; era também a outra asa igualmente de cinco côvados e estava unida à asa do outro querubim. As asas destes querubins se estendiam por vinte côvados;

[[v14-3-13]]

^<<v14-3-13,13>>^ eles estavam postos em pé, e o seu rosto, virado para o Santo Lugar.

[[v14-3-14]]

^<<v14-3-14,14>>^ Também fez o véu de estofo azul, púrpura, carmesim e linho fino; e fez bordar nele querubins.

[[v14-3-15]]

^<<v14-3-15,15>>^ Fez também diante da sala duas colunas de trinta e cinco côvados de altura; e o capitel, sobre cada uma, de cinco côvados.

[[v14-3-16]]

^<<v14-3-16,16>>^ Também fez cadeias, como no Santo dos Santos, e as pôs sobre as cabeças das colunas; fez também cem romãs, as quais pôs nas cadeias.

[[v14-3-17]]

^<<v14-3-17,17>>^ Levantou as colunas diante do templo, uma à direita, e outra à esquerda; a da direita, chamou-lhe Jaquim, a da esquerda, Boaz.

'''

xref:014-2-cronicas/014-2-cronicas-002.adoc#v14-2-0[&#60; Capítulo Anterior] | <<v14-3-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-004.adoc#v14-4-0[Próximo Capítulo &#62;]