include::./index.adoc[]

[[v14-21-0]]
=== 2 Crônicas, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-21-1]]

^<<v14-21-1,1>>^ Descansou Josafá com seus pais e foi sepultado com eles na Cidade de Davi; e Jeorão, seu filho, reinou em seu lugar.

[[v14-21-2]]

^<<v14-21-2,2>>^ Teve este irmãos, filhos de Josafá: Azarias, Jeiel, Zacarias, Azarias, Micael e Sefatias; todos estes foram filhos de Josafá, rei de Israel.

[[v14-21-3]]

^<<v14-21-3,3>>^ Seu pai lhes fez muitas dádivas de prata, ouro e coisas preciosas e ainda de cidades fortificadas em Judá; porém o reino deu a Jeorão, por ser o primogênito.

[[v14-21-4]]

^<<v14-21-4,4>>^ Tendo Jeorão assumido o reino de seu pai e havendo-se fortificado, matou todos os seus irmãos à espada, como também alguns dos príncipes de Israel.

[[v14-21-5]]

^<<v14-21-5,5>>^ Era Jeorão da idade de trinta e dois anos quando começou a reinar e reinou oito anos em Jerusalém.

[[v14-21-6]]

^<<v14-21-6,6>>^ Andou nos caminhos dos reis de Israel, como também fizeram os da casa de Acabe, porque a filha deste era sua mulher; e fez o que era mau perante o SENHOR.

[[v14-21-7]]

^<<v14-21-7,7>>^ Porém o SENHOR não quis destruir a casa de Davi por causa da aliança que com ele fizera, segundo a promessa que lhe havia feito de dar a ele, sempre, uma lâmpada e a seus filhos.

[[v14-21-8]]

^<<v14-21-8,8>>^ Nos dias de Jeorão, se revoltaram os edomitas contra o poder de Judá e constituíram o seu próprio rei.

[[v14-21-9]]

^<<v14-21-9,9>>^ Pelo que Jeorão passou adiante com todos os seus chefes, e todos os carros, com ele; de noite, se levantou e feriu os edomitas que o cercavam e os capitães dos carros.

[[v14-21-10]]

^<<v14-21-10,10>>^ Assim, se rebelou Edom para livrar-se do poder de Judá, até ao dia de hoje; ao mesmo tempo, se rebelou também Libna contra Jeorão, porque este deixara ao SENHOR, Deus de seus pais.

[[v14-21-11]]

^<<v14-21-11,11>>^ Também fez altos nos montes de Judá, e seduziu os habitantes de Jerusalém à idolatria, e fez desgarrar a Judá.

[[v14-21-12]]

^<<v14-21-12,12>>^ Então, lhe chegou às mãos uma carta do profeta Elias, em que estava escrito: Assim diz o SENHOR, Deus de Davi, teu pai: Porquanto não andaste nos caminhos de Josafá, teu pai, e nos caminhos de Asa, rei de Judá,

[[v14-21-13]]

^<<v14-21-13,13>>^ mas andaste nos caminhos dos reis de Israel, e induziste à idolatria a Judá e os moradores de Jerusalém, segundo a idolatria da casa de Acabe, e também mataste a teus irmãos, da casa de teu pai, melhores do que tu,

[[v14-21-14]]

^<<v14-21-14,14>>^ eis que o SENHOR castigará com grande flagelo ao teu povo, aos teus filhos, às tuas mulheres e todas as tuas possessões.

[[v14-21-15]]

^<<v14-21-15,15>>^ Tu terás grande enfermidade nas tuas entranhas, enfermidade que aumentará dia após dia, até que saiam as tuas entranhas.

[[v14-21-16]]

^<<v14-21-16,16>>^ Despertou, pois, o SENHOR contra Jeorão o ânimo dos filisteus e dos arábios que estão do lado dos etíopes.

[[v14-21-17]]

^<<v14-21-17,17>>^ Estes subiram a Judá, deram contra ele e levaram todos os bens que se acharam na casa do rei, como também a seus filhos e as suas mulheres; de modo que não lhe deixaram filho algum, senão Jeoacaz, o mais moço deles.

[[v14-21-18]]

^<<v14-21-18,18>>^ Depois de tudo isto, o SENHOR o feriu nas suas entranhas com enfermidade incurável.

[[v14-21-19]]

^<<v14-21-19,19>>^ E, aumentando esta dia após dia, ao cabo de dois anos, saíram-lhe as entranhas por causa da enfermidade, e morreu com terríveis agonias. O seu povo não lhe queimou aromas, como se fez a seus pais.

[[v14-21-20]]

^<<v14-21-20,20>>^ Era ele da idade de trinta e dois anos quando começou a reinar e reinou oito anos em Jerusalém. E se foi sem deixar de si saudades; sepultaram-no na Cidade de Davi, porém não nos sepulcros dos reis.

'''

xref:014-2-cronicas/014-2-cronicas-020.adoc#v14-20-0[&#60; Capítulo Anterior] | <<v14-21-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-022.adoc#v14-22-0[Próximo Capítulo &#62;]