include::./index.adoc[]

[[v14-5-0]]
=== 2 Crônicas, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-5-1]]

^<<v14-5-1,1>>^ Assim, se acabou toda a obra que fez o rei Salomão para a Casa do SENHOR; então, trouxe Salomão as coisas que Davi, seu pai, havia dedicado; a prata, o ouro e os utensílios, ele os pôs entre os tesouros da Casa de Deus.

[[v14-5-2]]

^<<v14-5-2,2>>^ Congregou Salomão os anciãos de Israel e todos os cabeças das tribos, os príncipes das famílias dos israelitas, em Jerusalém, para fazerem subir a arca da Aliança do SENHOR, da Cidade de Davi, que é Sião, para o templo.

[[v14-5-3]]

^<<v14-5-3,3>>^ Todos os homens de Israel se congregaram junto ao rei, na ocasião da festa, que foi no sétimo mês.

[[v14-5-4]]

^<<v14-5-4,4>>^ Vieram todos os anciãos de Israel, e os levitas tomaram a arca

[[v14-5-5]]

^<<v14-5-5,5>>^ e a levaram para cima, com a tenda da congregação, e também os utensílios sagrados que nela havia; os levitas sacerdotes é que os fizeram subir.

[[v14-5-6]]

^<<v14-5-6,6>>^ O rei Salomão e toda a congregação de Israel, que se reunira a ele, estavam diante da arca, sacrificando ovelhas e bois, que, de tão numerosos, não se podiam contar.

[[v14-5-7]]

^<<v14-5-7,7>>^ Puseram os sacerdotes a arca da Aliança do SENHOR no seu lugar, no santuário mais interior do templo, no Santo dos Santos, debaixo das asas dos querubins.

[[v14-5-8]]

^<<v14-5-8,8>>^ (Pois os querubins estendiam as asas sobre o lugar da arca e, do alto, cobriam a arca e os seus varais.

[[v14-5-9]]

^<<v14-5-9,9>>^ Os varais sobressaíam tanto, que suas pontas eram vistas do Santo Lugar, defronte do Santo dos Santos, porém de fora não se viam.

[[v14-5-10]]

^<<v14-5-10,10>>^ Aí estão os varais até ao dia de hoje.) Nada havia na arca senão as duas tábuas que Moisés ali pusera junto a Horebe, quando o SENHOR fez aliança com os filhos de Israel, ao saírem do Egito.

[[v14-5-11]]

^<<v14-5-11,11>>^ Quando saíram os sacerdotes do santuário (porque todos os sacerdotes, que estavam presentes, se santificaram, sem respeitarem os seus turnos);

[[v14-5-12]]

^<<v14-5-12,12>>^ e quando todos os levitas que eram cantores, isto é, Asafe, Hemã, Jedutum e os filhos e irmãos deles, vestidos de linho fino, estavam de pé, para o oriente do altar, com címbalos, alaúdes e harpas, e com eles até cento e vinte sacerdotes, que tocavam as trombetas;

[[v14-5-13]]

^<<v14-5-13,13>>^ e quando em uníssono, a um tempo, tocaram as trombetas e cantaram para se fazerem ouvir, para louvarem o SENHOR e render-lhe graças; e quando levantaram eles a voz com trombetas, címbalos e outros instrumentos músicos para louvarem o SENHOR, porque ele é bom, porque a sua misericórdia dura para sempre, então, sucedeu que a casa, a saber, a Casa do SENHOR, se encheu de uma nuvem;

[[v14-5-14]]

^<<v14-5-14,14>>^ de maneira que os sacerdotes não podiam estar ali para ministrar, por causa da nuvem, porque a glória do SENHOR encheu a Casa de Deus.

'''

xref:014-2-cronicas/014-2-cronicas-004.adoc#v14-4-0[&#60; Capítulo Anterior] | <<v14-5-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-006.adoc#v14-6-0[Próximo Capítulo &#62;]