include::./index.adoc[]

[[v14-32-0]]
=== 2 Crônicas, 32
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-32-1]]

^<<v14-32-1,1>>^ Depois destas coisas e desta fidelidade, veio Senaqueribe, rei da Assíria, entrou em Judá, acampou-se contra as cidades fortificadas e intentou apoderar-se delas.

[[v14-32-2]]

^<<v14-32-2,2>>^ Vendo, pois, Ezequias que Senaqueribe vinha e que estava resolvido a pelejar contra Jerusalém,

[[v14-32-3]]

^<<v14-32-3,3>>^ resolveu, de acordo com os seus príncipes e os seus homens valentes, tapar as fontes das águas que havia fora da cidade; e eles o ajudaram.

[[v14-32-4]]

^<<v14-32-4,4>>^ Assim, muito povo se ajuntou, e taparam todas as fontes, como também o ribeiro que corria pelo meio da terra, pois diziam: Por que viriam os reis da Assíria e achariam tantas águas?

[[v14-32-5]]

^<<v14-32-5,5>>^ Ele cobrou ânimo, restaurou todo o muro quebrado e sobre ele ergueu torres; levantou também o outro muro por fora, fortificou a Milo na Cidade de Davi e fez armas e escudos em abundância.

[[v14-32-6]]

^<<v14-32-6,6>>^ Pôs oficiais de guerra sobre o povo, reuniu-os na praça da porta da cidade e lhes falou ao coração, dizendo:

[[v14-32-7]]

^<<v14-32-7,7>>^ Sede fortes e corajosos, não temais, nem vos assusteis por causa do rei da Assíria, nem por causa de toda a multidão que está com ele; porque um há conosco maior do que o que está com ele.

[[v14-32-8]]

^<<v14-32-8,8>>^ Com ele está o braço de carne, mas conosco, o SENHOR, nosso Deus, para nos ajudar e para guerrear nossas guerras. O povo cobrou ânimo com as palavras de Ezequias, rei de Judá.

[[v14-32-9]]

^<<v14-32-9,9>>^ Depois disto, enquanto Senaqueribe, rei da Assíria, com todo o seu exército sitiava Laquis, enviou os seus servos a Ezequias, rei de Judá, que estava em Jerusalém, dizendo:

[[v14-32-10]]

^<<v14-32-10,10>>^ Assim diz Senaqueribe, rei da Assíria: Em que confiais vós, para vos deixardes sitiar em Jerusalém?

[[v14-32-11]]

^<<v14-32-11,11>>^ Acaso, não vos incita Ezequias, para morrerdes à fome e à sede, dizendo: O SENHOR, nosso Deus, nos livrará das mãos do rei da Assíria?

[[v14-32-12]]

^<<v14-32-12,12>>^ Não é Ezequias o mesmo que tirou os seus altos e os seus altares e falou a Judá e a Jerusalém, dizendo: Diante de apenas um altar vos prostrareis e sobre ele queimareis incenso?

[[v14-32-13]]

^<<v14-32-13,13>>^ Não sabeis vós o que eu e meus pais fizemos a todos os povos das terras? Acaso, puderam, de qualquer maneira, os deuses das nações daquelas terras livrar o seu país das minhas mãos?

[[v14-32-14]]

^<<v14-32-14,14>>^ Qual é, de todos os deuses daquelas nações que meus pais destruíram, que pôde livrar o seu povo das minhas mãos, para que vosso Deus vos possa livrar das minhas mãos?

[[v14-32-15]]

^<<v14-32-15,15>>^ Agora, pois, não vos engane Ezequias, nem vos incite assim, nem lhe deis crédito; porque nenhum deus de nação alguma, nem de reino algum pôde livrar o seu povo das minhas mãos, nem das mãos de meus pais; quanto menos vos poderá livrar o vosso Deus das minhas mãos?

[[v14-32-16]]

^<<v14-32-16,16>>^ Os seus servos falaram ainda mais contra o SENHOR Deus e contra Ezequias, seu servo.

[[v14-32-17]]

^<<v14-32-17,17>>^ Senaqueribe escreveu também cartas, para blasfemar do SENHOR, Deus de Israel, e para falar contra ele, dizendo: Assim como os deuses das nações de outras terras não livraram o seu povo das minhas mãos, assim também o Deus de Ezequias não livrará o seu povo das minhas mãos.

[[v14-32-18]]

^<<v14-32-18,18>>^ Clamaram os servos em alta voz em judaico contra o povo de Jerusalém, que estava sobre o muro, para os atemorizar e os perturbar, para tomarem a cidade.

[[v14-32-19]]

^<<v14-32-19,19>>^ Falaram do Deus de Jerusalém, como dos deuses dos povos da terra, obras das mãos dos homens.

[[v14-32-20]]

^<<v14-32-20,20>>^ Porém o rei Ezequias e Isaías, o profeta, filho de Amoz, oraram por causa disso e clamaram ao céu.

[[v14-32-21]]

^<<v14-32-21,21>>^ Então, o SENHOR enviou um anjo que destruiu todos os homens valentes, os chefes e os príncipes no arraial do rei da Assíria; e este, com o rosto coberto de vergonha, voltou para a sua terra. Tendo ele entrado na casa de seu deus, os seus próprios filhos ali o mataram à espada.

[[v14-32-22]]

^<<v14-32-22,22>>^ Assim, livrou o SENHOR a Ezequias e os moradores de Jerusalém das mãos de Senaqueribe, rei da Assíria, e das mãos de todos os inimigos; e lhes deu paz por todos os lados.

[[v14-32-23]]

^<<v14-32-23,23>>^ Muitos traziam presentes a Jerusalém ao SENHOR e coisas preciosíssimas a Ezequias, rei de Judá, de modo que, depois disto, foi enaltecido à vista de todas as nações.

[[v14-32-24]]

^<<v14-32-24,24>>^ Naqueles dias, adoeceu Ezequias mortalmente; então, orou ao SENHOR, que lhe falou e lhe deu um sinal.

[[v14-32-25]]

^<<v14-32-25,25>>^ Mas não correspondeu Ezequias aos benefícios que lhe foram feitos; pois o seu coração se exaltou. Pelo que houve ira contra ele e contra Judá e Jerusalém.

[[v14-32-26]]

^<<v14-32-26,26>>^ Ezequias, porém, se humilhou por se ter exaltado o seu coração, ele e os habitantes de Jerusalém; e a ira do SENHOR não veio contra eles nos dias de Ezequias.

[[v14-32-27]]

^<<v14-32-27,27>>^ Teve Ezequias riquezas e glória em grande abundância; proveu-se de tesourarias para prata, ouro, pedras preciosas, especiarias, escudos e toda sorte de objetos desejáveis;

[[v14-32-28]]

^<<v14-32-28,28>>^ também proveu-se de armazéns para a colheita do cereal, do vinho e do azeite; e de estrebarias para toda espécie de animais e de redis para os rebanhos.

[[v14-32-29]]

^<<v14-32-29,29>>^ Edificou também cidades e possuiu ovelhas e vacas em abundância; porque Deus lhe tinha dado mui numerosas possessões.

[[v14-32-30]]

^<<v14-32-30,30>>^ Também o mesmo Ezequias tapou o manancial superior das águas de Giom e as canalizou para o ocidente da Cidade de Davi. Ezequias prosperou em toda a sua obra.

[[v14-32-31]]

^<<v14-32-31,31>>^ Contudo, quando os embaixadores dos príncipes da Babilônia lhe foram enviados para se informarem do prodígio que se dera naquela terra, Deus o desamparou, para prová-lo e fazê-lo conhecer tudo o que lhe estava no coração.

[[v14-32-32]]

^<<v14-32-32,32>>^ Quanto aos mais atos de Ezequias e às suas obras de misericórdia, eis que estão escritos na Visão do Profeta Isaías, filho de Amoz, e no Livro da História dos Reis de Judá e de Israel.

[[v14-32-33]]

^<<v14-32-33,33>>^ Descansou Ezequias com seus pais, e o sepultaram na subida para os sepulcros dos filhos de Davi; e todo o Judá e os habitantes de Jerusalém lhe prestaram honras na sua morte; e Manassés, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-031.adoc#v14-31-0[&#60; Capítulo Anterior] | <<v14-32-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-033.adoc#v14-33-0[Próximo Capítulo &#62;]