include::./index.adoc[]

[[v14-29-0]]
=== 2 Crônicas, 29
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-29-1]]

^<<v14-29-1,1>>^ Tinha Ezequias vinte e cinco anos de idade quando começou a reinar e reinou vinte e nove anos em Jerusalém. Sua mãe se chamava Abia e era filha de Zacarias.

[[v14-29-2]]

^<<v14-29-2,2>>^ Fez ele o que era reto perante o SENHOR, segundo tudo quanto fizera Davi, seu pai.

[[v14-29-3]]

^<<v14-29-3,3>>^ No primeiro ano do seu reinado, no primeiro mês, abriu as portas da Casa do SENHOR e as reparou.

[[v14-29-4]]

^<<v14-29-4,4>>^ Trouxe os sacerdotes e os levitas, ajuntou-os na praça oriental

[[v14-29-5]]

^<<v14-29-5,5>>^ e lhes disse: Ouvi-me, ó levitas! Santificai-vos, agora, e santificai a Casa do SENHOR, Deus de vossos pais; tirai do santuário a imundícia.

[[v14-29-6]]

^<<v14-29-6,6>>^ Porque nossos pais prevaricaram e fizeram o que era mau perante o SENHOR, nosso Deus, e o deixaram; desviaram o seu rosto do tabernáculo do SENHOR e lhe voltaram as costas.

[[v14-29-7]]

^<<v14-29-7,7>>^ Também fecharam as portas do pórtico, apagaram as lâmpadas, não queimaram incenso, nem ofereceram holocaustos nos santuários ao Deus de Israel.

[[v14-29-8]]

^<<v14-29-8,8>>^ Pelo que veio grande ira do SENHOR sobre Judá e Jerusalém, e os entregou ao terror, ao espanto e aos assobios, como vós o estais vendo com os próprios olhos.

[[v14-29-9]]

^<<v14-29-9,9>>^ Porque eis que nossos pais caíram à espada, e, por isso, nossos filhos, nossas filhas e nossas mulheres estiveram em cativeiro.

[[v14-29-10]]

^<<v14-29-10,10>>^ Agora, estou resolvido a fazer aliança com o SENHOR, Deus de Israel, para que se desvie de nós o ardor da sua ira.

[[v14-29-11]]

^<<v14-29-11,11>>^ Filhos meus, não sejais negligentes, pois o SENHOR vos escolheu para estardes diante dele para o servirdes, para serdes seus ministros e queimardes incenso.

[[v14-29-12]]

^<<v14-29-12,12>>^ Então, se levantaram os levitas: Maate, filho de Amasai, e Joel, filho de Azarias, dos filhos dos coatitas; dos filhos de Merari, Quis, filho de Abdi, e Azarias, filho de Jealelel; dos gersonitas, Joá, filho de Zima, e Éden, filho de Joá;

[[v14-29-13]]

^<<v14-29-13,13>>^ dos filhos de Elisafã, Sinri e Jeuel; dos filhos de Asafe, Zacarias e Matanias;

[[v14-29-14]]

^<<v14-29-14,14>>^ dos filhos de Hemã, Jeuel e Simei; dos filhos de Jedutum, Semaías e Uziel.

[[v14-29-15]]

^<<v14-29-15,15>>^ Congregaram a seus irmãos, santificaram-se e vieram segundo a ordem do rei pelas palavras do SENHOR, para purificarem a Casa do SENHOR.

[[v14-29-16]]

^<<v14-29-16,16>>^ Os sacerdotes entraram na Casa do SENHOR, para a purificar, e tiraram para fora, ao pátio da Casa do SENHOR, toda imundícia que acharam no templo do SENHOR; e os levitas a tomaram, para a levarem fora, ao ribeiro de Cedrom.

[[v14-29-17]]

^<<v14-29-17,17>>^ Começaram, pois, a santificar no primeiro dia do primeiro mês; ao oitavo dia do mês, vieram ao pórtico do SENHOR e santificaram a Casa do SENHOR em oito dias; no décimo sexto dia do mês, acabaram.

[[v14-29-18]]

^<<v14-29-18,18>>^ Então, foram ter com o rei Ezequias no palácio e disseram: Já purificamos toda a Casa do SENHOR, como também o altar do holocausto com todos os seus utensílios e a mesa da proposição com todos os seus objetos.

[[v14-29-19]]

^<<v14-29-19,19>>^ Também todos os objetos que o rei Acaz, no seu reinado, lançou fora, na sua transgressão, já preparamos e santificamos; e eis que estão diante do altar do SENHOR.

[[v14-29-20]]

^<<v14-29-20,20>>^ Então, o rei Ezequias se levantou de madrugada, reuniu os príncipes da cidade e subiu à Casa do SENHOR.

[[v14-29-21]]

^<<v14-29-21,21>>^ Mandou trazer sete novilhos, sete carneiros, sete cordeiros e sete bodes, como oferta pelo pecado a favor do reino, do santuário e de Judá; e aos filhos de Arão, os sacerdotes, que os oferecessem sobre o altar do SENHOR.

[[v14-29-22]]

^<<v14-29-22,22>>^ Mortos os novilhos, os sacerdotes tomaram o sangue e o aspergiram sobre o altar; mataram os carneiros e aspergiram o sangue sobre o altar; também mataram os cordeiros e aspergiram o sangue sobre o altar.

[[v14-29-23]]

^<<v14-29-23,23>>^ Para oferta pelo pecado, trouxeram os bodes perante o rei e a congregação e puseram as mãos sobre eles.

[[v14-29-24]]

^<<v14-29-24,24>>^ Os sacerdotes os mataram e, com o sangue, fizeram uma oferta pelo pecado, ao pé do altar, para expiação de todo o Israel, porque o rei tinha ordenado que se fizesse aquele holocausto e oferta pelo pecado, por todo o Israel.

[[v14-29-25]]

^<<v14-29-25,25>>^ Também estabeleceu os levitas na Casa do SENHOR com címbalos, alaúdes e harpas, segundo mandado de Davi e de Gade, o vidente do rei, e do profeta Natã; porque este mandado veio do SENHOR, por intermédio de seus profetas.

[[v14-29-26]]

^<<v14-29-26,26>>^ Estavam, pois, os levitas em pé com os instrumentos de Davi, e os sacerdotes, com as trombetas.

[[v14-29-27]]

^<<v14-29-27,27>>^ Deu ordem Ezequias que oferecessem o holocausto sobre o altar. Em começando o holocausto, começou também o cântico ao SENHOR com as trombetas, ao som dos instrumentos de Davi, rei de Israel.

[[v14-29-28]]

^<<v14-29-28,28>>^ Toda a congregação se prostrou, quando se entoava o cântico, e as trombetas soavam; tudo isto até findar-se o holocausto.

[[v14-29-29]]

^<<v14-29-29,29>>^ Tendo eles acabado de oferecer o sacrifício, o rei e todos os que se achavam com ele prostraram-se e adoraram.

[[v14-29-30]]

^<<v14-29-30,30>>^ Então, o rei Ezequias e os príncipes ordenaram aos levitas que louvassem o SENHOR com as palavras de Davi e de Asafe, o vidente. Eles o fizeram com alegria, e se inclinaram, e adoraram.

[[v14-29-31]]

^<<v14-29-31,31>>^ Disse ainda Ezequias: Agora, vos consagrastes a vós mesmos ao SENHOR; chegai-vos e trazei sacrifícios e ofertas de ações de graças à Casa do SENHOR. A congregação trouxe sacrifícios e ofertas de ações de graças, e todos os que estavam de coração disposto trouxeram holocaustos.

[[v14-29-32]]

^<<v14-29-32,32>>^ O número dos holocaustos, que a congregação trouxe, foi de setenta bois, cem carneiros e duzentos cordeiros; tudo isto em holocausto para o SENHOR.

[[v14-29-33]]

^<<v14-29-33,33>>^ Também foram consagrados seiscentos bois e três mil ovelhas.

[[v14-29-34]]

^<<v14-29-34,34>>^ Os sacerdotes, porém, eram mui poucos e não podiam esfolar a todos os holocaustos; pelo que seus irmãos, os levitas, os ajudaram, até findar-se a obra e até que os outros sacerdotes se santificaram; porque os levitas foram mais retos de coração, para se santificarem, do que os sacerdotes.

[[v14-29-35]]

^<<v14-29-35,35>>^ Além dos holocaustos em abundância, houve também a gordura das ofertas pacíficas e as libações para os holocaustos. Assim, se estabeleceu o ministério da Casa do SENHOR.

[[v14-29-36]]

^<<v14-29-36,36>>^ Ezequias e todo o povo se alegraram por causa daquilo que Deus fizera para o povo, porque, subitamente, se fez esta obra.

'''

xref:014-2-cronicas/014-2-cronicas-028.adoc#v14-28-0[&#60; Capítulo Anterior] | <<v14-29-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-030.adoc#v14-30-0[Próximo Capítulo &#62;]