include::./index.adoc[]

[[v14-28-0]]
=== 2 Crônicas, 28
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-28-1]]

^<<v14-28-1,1>>^ Tinha Acaz vinte anos de idade quando começou a reinar e reinou dezesseis anos em Jerusalém; e não fez o que era reto perante o SENHOR, como Davi, seu pai.

[[v14-28-2]]

^<<v14-28-2,2>>^ Andou nos caminhos dos reis de Israel e até fez imagens fundidas a baalins.

[[v14-28-3]]

^<<v14-28-3,3>>^ Também queimou incenso no vale do filho de Hinom e queimou a seus próprios filhos, segundo as abominações dos gentios que o SENHOR lançara de diante dos filhos de Israel.

[[v14-28-4]]

^<<v14-28-4,4>>^ Também sacrificou e queimou incenso nos altos e nos outeiros, como também debaixo de toda árvore frondosa.

[[v14-28-5]]

^<<v14-28-5,5>>^ Pelo que o SENHOR, seu Deus, o entregou nas mãos do rei dos siros, os quais o derrotaram e levaram dele em cativeiro uma grande multidão de presos, que trouxeram a Damasco; também foi entregue nas mãos do rei de Israel, o qual lhe infligiu grande derrota.

[[v14-28-6]]

^<<v14-28-6,6>>^ Porque Peca, filho de Remalias, matou em Judá, num só dia, cento e vinte mil, todos homens poderosos, por terem abandonado o SENHOR, Deus de seus pais.

[[v14-28-7]]

^<<v14-28-7,7>>^ Zicri, homem valente de Efraim, matou a Maaseias, filho do rei, a Azricão, alto oficial do palácio, e a Elcana, o segundo depois do rei.

[[v14-28-8]]

^<<v14-28-8,8>>^ Os filhos de Israel levaram presos de Judá, seu povo irmão, duzentos mil: mulheres, filhos e filhas; e saquearam deles grande despojo e o trouxeram para Samaria.

[[v14-28-9]]

^<<v14-28-9,9>>^ Mas estava ali um profeta do SENHOR, cujo nome era Odede, o qual saiu ao encontro do exército que vinha para Samaria e lhe disse: Eis que, irando-se o SENHOR, Deus de vossos pais, contra Judá, os entregou nas vossas mãos, e vós os matastes com tamanha raiva, que chegou até aos céus.

[[v14-28-10]]

^<<v14-28-10,10>>^ Agora, cuidais em sujeitar os filhos de Judá e Jerusalém, para vos serem escravos e escravas; acaso, não sois vós mesmos culpados contra o SENHOR, vosso Deus?

[[v14-28-11]]

^<<v14-28-11,11>>^ Agora, pois, atendei-me e fazei voltar os presos que trouxestes cativos de vossos irmãos, porque o brasume da ira do SENHOR está sobre vós.

[[v14-28-12]]

^<<v14-28-12,12>>^ Então, se levantaram alguns homens dentre os cabeças dos filhos de Efraim, a saber, Azarias, filho de Joanã, Berequias, filho de Mesilemote, Jeizquias, filho de Salum, e Amasa, filho de Hadlai, contra os que voltavam da batalha

[[v14-28-13]]

^<<v14-28-13,13>>^ e lhes disseram: Não fareis entrar aqui esses cativos, porque intentais acrescentar aos nossos pecados e à nossa culpa diante do SENHOR ainda outros; a nossa culpa já é grande, e o brasume da ira do SENHOR está sobre nós.

[[v14-28-14]]

^<<v14-28-14,14>>^ Então, os homens armados deixaram os presos e o despojo diante dos príncipes e de toda a congregação.

[[v14-28-15]]

^<<v14-28-15,15>>^ Homens foram designados nominalmente, os quais se levantaram, e tomaram os cativos, e do despojo vestiram a todos os que estavam nus; vestiram-nos, e calçaram-nos, e lhes deram de comer e de beber, e os ungiram; a todos os que, por fracos, não podiam andar, levaram sobre jumentos a Jericó, cidade das Palmeiras, a seus irmãos. Então, voltaram para Samaria.

[[v14-28-16]]

^<<v14-28-16,16>>^ Naquele tempo, mandou o rei Acaz pedir aos reis da Assíria que o ajudassem.

[[v14-28-17]]

^<<v14-28-17,17>>^ Pois vieram, de novo, os edomitas, e derrotaram Judá, e levaram presos em cativeiro.

[[v14-28-18]]

^<<v14-28-18,18>>^ Também os filisteus deram contra as cidades da campina e do sul de Judá, e tomaram Bete-Semes, Aijalom, Gederote, Socó e suas aldeias, Timna e suas aldeias e Ginzo e suas aldeias; e habitavam ali.

[[v14-28-19]]

^<<v14-28-19,19>>^ Porque o SENHOR humilhou a Judá por causa de Acaz, rei de Israel; porque este permitira que Judá caísse em dissolução, e ele, de todo, se entregou à transgressão contra o SENHOR.

[[v14-28-20]]

^<<v14-28-20,20>>^ Veio a ele Tiglate-Pileser, rei da Assíria; porém o pôs em aperto, em vez de fortalecê-lo.

[[v14-28-21]]

^<<v14-28-21,21>>^ Porque Acaz tomou despojos da Casa do SENHOR, da casa do rei e da dos príncipes e os deu ao rei da Assíria; porém isso não o ajudou.

[[v14-28-22]]

^<<v14-28-22,22>>^ No tempo da sua angústia, cometeu ainda maiores transgressões contra o SENHOR; ele mesmo, o rei Acaz.

[[v14-28-23]]

^<<v14-28-23,23>>^ Pois ofereceu sacrifícios aos deuses de Damasco, que o feriram, e disse: Visto que os deuses dos reis da Síria os ajudam, eu lhes oferecerei sacrifícios para que me ajudem a mim. Porém eles foram a sua ruína e a de todo o Israel.

[[v14-28-24]]

^<<v14-28-24,24>>^ Ajuntou Acaz os utensílios da Casa de Deus, fê-los em pedaços e fechou as portas da Casa do SENHOR; e fez para si altares em todos os cantos de Jerusalém.

[[v14-28-25]]

^<<v14-28-25,25>>^ Também, em cada cidade de Judá, fez altos para queimar incenso a outros deuses; assim, provocou à ira o SENHOR, Deus de seus pais.

[[v14-28-26]]

^<<v14-28-26,26>>^ Quanto aos mais atos dele e a todos os seus caminhos, tanto os primeiros como os últimos, eis que estão escritos no Livro da História dos Reis de Judá e de Israel.

[[v14-28-27]]

^<<v14-28-27,27>>^ Descansou Acaz com seus pais, e o sepultaram na cidade, em Jerusalém, porém não o puseram nos sepulcros dos reis de Israel; e Ezequias, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[&#60; Capítulo Anterior] | <<v14-28-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-029.adoc#v14-29-0[Próximo Capítulo &#62;]