include::./index.adoc[]

[[v14-23-0]]
=== 2 Crônicas, 23
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-23-1]]

^<<v14-23-1,1>>^ No sétimo ano, Joiada se animou e entrou em aliança com os capitães de cem: Azarias, filho de Jeroão, Ismael, filho de Joanã, Azarias, filho de Obede, Maaseias, filho de Adaías, e Elisafate, filho de Zicri.

[[v14-23-2]]

^<<v14-23-2,2>>^ Estes percorreram Judá, e congregaram os levitas de todas as cidades de Judá e os cabeças das famílias de Israel, e vieram para Jerusalém.

[[v14-23-3]]

^<<v14-23-3,3>>^ Toda essa congregação fez aliança com o rei na Casa de Deus; e Joiada lhes disse: Eis que reinará o filho do rei, como falou o SENHOR a respeito dos filhos de Davi.

[[v14-23-4]]

^<<v14-23-4,4>>^ Esta é a obra que haveis de fazer: uma terça parte de vós, sacerdotes e levitas, que entrais no sábado, servirá de guardas da porta;

[[v14-23-5]]

^<<v14-23-5,5>>^ outra terça parte estará na casa do rei; e a outra terça parte, à Porta do Fundamento; e todo o povo estará nos pátios da Casa do SENHOR.

[[v14-23-6]]

^<<v14-23-6,6>>^ Porém ninguém entre na Casa do SENHOR, senão os sacerdotes e os levitas que ministram; estes entrarão, porque são santos; mas todo o povo guardará o preceito do SENHOR.

[[v14-23-7]]

^<<v14-23-7,7>>^ Os levitas rodearão o rei, cada um de armas na mão, e qualquer que entrar na casa, seja morto; estareis com o rei quando entrar e quando sair.

[[v14-23-8]]

^<<v14-23-8,8>>^ Fizeram, pois, os levitas e todo o Judá segundo tudo quanto lhes ordenara o sacerdote Joiada; tomou cada um os seus homens, tanto os que entravam como os que saíam no sábado; porquanto o sacerdote Joiada não despediu os turnos.

[[v14-23-9]]

^<<v14-23-9,9>>^ O sacerdote Joiada entregou aos capitães de cem as lanças, os paveses e os escudos que haviam sido do rei Davi e estavam na Casa de Deus.

[[v14-23-10]]

^<<v14-23-10,10>>^ Dispôs todo o povo, cada um de armas na mão, desde o lado direito da casa real até ao seu lado esquerdo, e até ao altar, e até ao templo, para rodear o rei.

[[v14-23-11]]

^<<v14-23-11,11>>^ Então, trouxeram para fora o filho do rei, puseram-lhe a coroa, entregaram-lhe o Livro do Testemunho e o constituíram rei; Joiada e seus filhos o ungiram e gritaram: Viva o rei!

[[v14-23-12]]

^<<v14-23-12,12>>^ Ouvindo Atalia o clamor do povo que corria e louvava o rei, veio para onde este se achava na Casa do SENHOR;

[[v14-23-13]]

^<<v14-23-13,13>>^ olhou, e eis que o rei estava junto à coluna, à entrada, e os capitães e os que tocavam trombetas, junto ao rei; e todo o povo da terra se alegrava, e se tocavam trombetas. Também os cantores com os instrumentos músicos dirigiam o canto de louvores. Então, Atalia rasgou os seus vestidos e clamou: Traição! Traição!

[[v14-23-14]]

^<<v14-23-14,14>>^ Porém o sacerdote Joiada trouxe para fora os capitães que comandavam as tropas e disse-lhes: Fazei-a sair por entre as fileiras; se alguém a seguir, matai-o à espada. Porque o sacerdote tinha dito: Não a matem na Casa do SENHOR.

[[v14-23-15]]

^<<v14-23-15,15>>^ Lançaram mão dela; e ela, pelo caminho da entrada dos cavalos, foi à casa do rei, onde a mataram.

[[v14-23-16]]

^<<v14-23-16,16>>^ Joiada fez aliança entre si mesmo, o povo e o rei, para serem eles o povo do SENHOR.

[[v14-23-17]]

^<<v14-23-17,17>>^ Então, todo o povo se dirigiu para a casa de Baal e a derribaram; despedaçaram os seus altares e as suas imagens e a Matã, sacerdote de Baal, mataram perante os altares.

[[v14-23-18]]

^<<v14-23-18,18>>^ Entregou Joiada a superintendência da Casa do SENHOR nas mãos dos sacerdotes levitas, a quem Davi designara para o encargo da Casa do SENHOR, para oferecerem os holocaustos do SENHOR, como está escrito na Lei de Moisés, com alegria e com canto, segundo a instituição de Davi.

[[v14-23-19]]

^<<v14-23-19,19>>^ Colocou porteiros às portas da Casa do SENHOR, para que nela não entrasse ninguém que de qualquer forma fosse imundo.

[[v14-23-20]]

^<<v14-23-20,20>>^ Tomou os capitães de cem, os nobres, os governadores do povo e todo o povo da terra, e todos estes conduziram, da Casa do SENHOR, o rei; passaram, pela porta superior, para a casa do rei e assentaram o rei no trono do reino.

[[v14-23-21]]

^<<v14-23-21,21>>^ Alegrou-se todo o povo da terra, e a cidade ficou tranquila, pois haviam matado Atalia à espada.

'''

xref:014-2-cronicas/014-2-cronicas-022.adoc#v14-22-0[&#60; Capítulo Anterior] | <<v14-23-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-024.adoc#v14-24-0[Próximo Capítulo &#62;]