include::./index.adoc[]

[[v14-11-0]]
=== 2 Crônicas, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v14-11-1]]

^<<v14-11-1,1>>^ Vindo, pois, Roboão a Jerusalém, reuniu a casa de Judá e de Benjamim, cento e oitenta mil escolhidos, destros para a guerra, para pelejar contra Israel, a fim de restituir o reino a Roboão.

[[v14-11-2]]

^<<v14-11-2,2>>^ Porém veio a palavra do SENHOR a Semaías, homem de Deus, dizendo:

[[v14-11-3]]

^<<v14-11-3,3>>^ Fala a Roboão, filho de Salomão, rei de Judá, e a todo o Israel em Judá e Benjamim, dizendo:

[[v14-11-4]]

^<<v14-11-4,4>>^ Assim diz o SENHOR: Não subireis, nem pelejareis contra vossos irmãos; cada um volte para sua casa, porque eu é que fiz isto. E, obedecendo eles à palavra do SENHOR, desistiram de subir contra Jeroboão.

[[v14-11-5]]

^<<v14-11-5,5>>^ Roboão habitou em Jerusalém e, para defesa, fortificou cidades em Judá;

[[v14-11-6]]

^<<v14-11-6,6>>^ fortificou, pois, a Belém, a Etã, a Tecoa,

[[v14-11-7]]

^<<v14-11-7,7>>^ a Bete-Zur, a Socó, a Adulão,

[[v14-11-8]]

^<<v14-11-8,8>>^ a Gate, a Maressa, a Zife,

[[v14-11-9]]

^<<v14-11-9,9>>^ a Adoraim, a Laquis, a Azeca,

[[v14-11-10]]

^<<v14-11-10,10>>^ a Zorá, a Aijalom e a Hebrom, todas em Judá e Benjamim, cidades fortificadas.

[[v14-11-11]]

^<<v14-11-11,11>>^ Assim, as tornou em fortalezas e pôs nelas comandantes e depósitos de víveres, de azeite e de vinho.

[[v14-11-12]]

^<<v14-11-12,12>>^ E pôs em cada cidade arsenal de paveses e lanças; fortificou-as sobremaneira. Judá e Benjamim ficaram-lhe sujeitas.

[[v14-11-13]]

^<<v14-11-13,13>>^ Também os sacerdotes e os levitas que havia em todo o Israel recorreram a Roboão de todos os seus limites,

[[v14-11-14]]

^<<v14-11-14,14>>^ porque os levitas deixaram os arredores das suas cidades e as suas possessões e vieram para Judá e para Jerusalém, porque Jeroboão e seus filhos os lançaram fora, para que não ministrassem ao SENHOR.

[[v14-11-15]]

^<<v14-11-15,15>>^ Jeroboão constituiu os seus próprios sacerdotes, para os altos, para os sátiros e para os bezerros que fizera.

[[v14-11-16]]

^<<v14-11-16,16>>^ Além destes, também de todas as tribos de Israel os que de coração resolveram buscar o SENHOR, Deus de Israel, foram a Jerusalém, para oferecerem sacrifícios ao SENHOR, Deus de seus pais.

[[v14-11-17]]

^<<v14-11-17,17>>^ Assim, fortaleceram o reino de Judá e corroboraram com Roboão, filho de Salomão, por três anos; porque três anos andaram no caminho de Davi e Salomão.

[[v14-11-18]]

^<<v14-11-18,18>>^ Roboão tomou por esposa a Maalate, filha de Jerimote, filho de Davi, e filha de Abiail, filha de Eliabe, filho de Jessé,

[[v14-11-19]]

^<<v14-11-19,19>>^ a qual lhe deu filhos: Jeús, Semarias e Zaão.

[[v14-11-20]]

^<<v14-11-20,20>>^ Depois dela, tomou a Maaca, filha de Absalão; esta lhe deu a Abias, a Atai, a Ziza e a Selomite.

[[v14-11-21]]

^<<v14-11-21,21>>^ Amava Roboão mais a Maaca, filha de Absalão, do que a todas as suas outras mulheres e concubinas; porque ele havia tomado dezoito mulheres e sessenta concubinas; e gerou vinte e oito filhos e sessenta filhas.

[[v14-11-22]]

^<<v14-11-22,22>>^ Roboão designou a Abias, filho de Maaca, para ser chefe, príncipe entre seus irmãos, porque o queria fazer rei.

[[v14-11-23]]

^<<v14-11-23,23>>^ Procedeu prudentemente e distribuiu todos os seus filhos por todas as terras de Judá e Benjamim, por todas as cidades fortificadas; deu-lhes víveres em abundância e lhes procurou muitas mulheres.

'''

xref:014-2-cronicas/014-2-cronicas-010.adoc#v14-10-0[&#60; Capítulo Anterior] | <<v14-11-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[Próximo Capítulo &#62;]