include::./index.adoc[]

[[v2-12-0]]
=== Êxodo, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-12-1]]

^<<v2-12-1,1>>^ Disse o SENHOR a Moisés e a Arão na terra do Egito:

[[v2-12-2]]

^<<v2-12-2,2>>^ Este mês vos será o principal dos meses; será o primeiro mês do ano.

[[v2-12-3]]

^<<v2-12-3,3>>^ Falai a toda a congregação de Israel, dizendo: Aos dez deste mês, cada um tomará para si um cordeiro, segundo a casa dos pais, um cordeiro para cada família.

[[v2-12-4]]

^<<v2-12-4,4>>^ Mas, se a família for pequena para um cordeiro, então, convidará ele o seu vizinho mais próximo, conforme o número das almas; conforme o que cada um puder comer, por aí calculareis quantos bastem para o cordeiro.

[[v2-12-5]]

^<<v2-12-5,5>>^ O cordeiro será sem defeito, macho de um ano; podereis tomar um cordeiro ou um cabrito;

[[v2-12-6]]

^<<v2-12-6,6>>^ e o guardareis até ao décimo quarto dia deste mês, e todo o ajuntamento da congregação de Israel o imolará no crepúsculo da tarde.

[[v2-12-7]]

^<<v2-12-7,7>>^ Tomarão do sangue e o porão em ambas as ombreiras e na verga da porta, nas casas em que o comerem;

[[v2-12-8]]

^<<v2-12-8,8>>^ naquela noite, comerão a carne assada no fogo; com pães asmos e ervas amargas a comerão.

[[v2-12-9]]

^<<v2-12-9,9>>^ Não comereis do animal nada cru, nem cozido em água, porém assado ao fogo: a cabeça, as pernas e a fressura.

[[v2-12-10]]

^<<v2-12-10,10>>^ Nada deixareis dele até pela manhã; o que, porém, ficar até pela manhã, queimá-lo-eis.

[[v2-12-11]]

^<<v2-12-11,11>>^ Desta maneira o comereis: lombos cingidos, sandálias nos pés e cajado na mão; comê-lo-eis à pressa; é a Páscoa do SENHOR.

[[v2-12-12]]

^<<v2-12-12,12>>^ Porque, naquela noite, passarei pela terra do Egito e ferirei na terra do Egito todos os primogênitos, desde os homens até aos animais; executarei juízo sobre todos os deuses do Egito. Eu sou o SENHOR.

[[v2-12-13]]

^<<v2-12-13,13>>^ O sangue vos será por sinal nas casas em que estiverdes; quando eu vir o sangue, passarei por vós, e não haverá entre vós praga destruidora, quando eu ferir a terra do Egito.

[[v2-12-14]]

^<<v2-12-14,14>>^ Este dia vos será por memorial, e o celebrareis como solenidade ao SENHOR; nas vossas gerações o celebrareis por estatuto perpétuo.

[[v2-12-15]]

^<<v2-12-15,15>>^ Sete dias comereis pães asmos. Logo ao primeiro dia, tirareis o fermento das vossas casas, pois qualquer que comer coisa levedada, desde o primeiro dia até ao sétimo dia, essa pessoa será eliminada de Israel.

[[v2-12-16]]

^<<v2-12-16,16>>^ Ao primeiro dia, haverá para vós outros santa assembleia; também, ao sétimo dia, tereis santa assembleia; nenhuma obra se fará nele, exceto o que diz respeito ao comer; somente isso podereis fazer.

[[v2-12-17]]

^<<v2-12-17,17>>^ Guardai, pois, a Festa dos Pães Asmos, porque, nesse mesmo dia, tirei vossas hostes da terra do Egito; portanto, guardareis este dia nas vossas gerações por estatuto perpétuo.

[[v2-12-18]]

^<<v2-12-18,18>>^ Desde o dia catorze do primeiro mês, à tarde, comereis pães asmos até à tarde do dia vinte e um do mesmo mês.

[[v2-12-19]]

^<<v2-12-19,19>>^ Por sete dias, não se ache nenhum fermento nas vossas casas; porque qualquer que comer pão levedado será eliminado da congregação de Israel, tanto o peregrino como o natural da terra.

[[v2-12-20]]

^<<v2-12-20,20>>^ Nenhuma coisa levedada comereis; em todas as vossas habitações, comereis pães asmos.

[[v2-12-21]]

^<<v2-12-21,21>>^ Chamou, pois, Moisés todos os anciãos de Israel e lhes disse: Escolhei, e tomai cordeiros segundo as vossas famílias, e imolai a Páscoa.

[[v2-12-22]]

^<<v2-12-22,22>>^ Tomai um molho de hissopo, molhai-o no sangue que estiver na bacia e marcai a verga da porta e suas ombreiras com o sangue que estiver na bacia; nenhum de vós saia da porta da sua casa até pela manhã.

[[v2-12-23]]

^<<v2-12-23,23>>^ Porque o SENHOR passará para ferir os egípcios; quando vir, porém, o sangue na verga da porta e em ambas as ombreiras, passará o SENHOR aquela porta e não permitirá ao Destruidor que entre em vossas casas, para vos ferir.

[[v2-12-24]]

^<<v2-12-24,24>>^ Guardai, pois, isto por estatuto para vós outros e para vossos filhos, para sempre.

[[v2-12-25]]

^<<v2-12-25,25>>^ E, uma vez dentro na terra que o SENHOR vos dará, como tem dito, observai este rito.

[[v2-12-26]]

^<<v2-12-26,26>>^ Quando vossos filhos vos perguntarem: Que rito é este?

[[v2-12-27]]

^<<v2-12-27,27>>^ Respondereis: É o sacrifício da Páscoa ao SENHOR, que passou por cima das casas dos filhos de Israel no Egito, quando feriu os egípcios e livrou as nossas casas. Então, o povo se inclinou e adorou.

[[v2-12-28]]

^<<v2-12-28,28>>^ E foram os filhos de Israel e fizeram isso; como o SENHOR ordenara a Moisés e a Arão, assim fizeram.

[[v2-12-29]]

^<<v2-12-29,29>>^ Aconteceu que, à meia-noite, feriu o SENHOR todos os primogênitos na terra do Egito, desde o primogênito de Faraó, que se assentava no seu trono, até ao primogênito do cativo que estava na enxovia, e todos os primogênitos dos animais.

[[v2-12-30]]

^<<v2-12-30,30>>^ Levantou-se Faraó de noite, ele, todos os seus oficiais e todos os egípcios; e fez-se grande clamor no Egito, pois não havia casa em que não houvesse morto.

[[v2-12-31]]

^<<v2-12-31,31>>^ Então, naquela mesma noite, Faraó chamou a Moisés e a Arão e lhes disse: Levantai-vos, saí do meio do meu povo, tanto vós como os filhos de Israel; ide, servi ao SENHOR, como tendes dito.

[[v2-12-32]]

^<<v2-12-32,32>>^ Levai também convosco vossas ovelhas e vosso gado, como tendes dito; ide-vos embora e abençoai-me também a mim.

[[v2-12-33]]

^<<v2-12-33,33>>^ Os egípcios apertavam com o povo, apressando-se em lançá-los fora da terra, pois diziam: Todos morreremos.

[[v2-12-34]]

^<<v2-12-34,34>>^ O povo tomou a sua massa, antes que levedasse, e as suas amassadeiras atadas em trouxas com seus vestidos, sobre os ombros.

[[v2-12-35]]

^<<v2-12-35,35>>^ Fizeram, pois, os filhos de Israel conforme a palavra de Moisés e pediram aos egípcios objetos de prata, e objetos de ouro, e roupas.

[[v2-12-36]]

^<<v2-12-36,36>>^ E o SENHOR fez que seu povo encontrasse favor da parte dos egípcios, de maneira que estes lhes davam o que pediam. E despojaram os egípcios.

[[v2-12-37]]

^<<v2-12-37,37>>^ Assim, partiram os filhos de Israel de Ramessés para Sucote, cerca de seiscentos mil a pé, somente de homens, sem contar mulheres e crianças.

[[v2-12-38]]

^<<v2-12-38,38>>^ Subiu também com eles um misto de gente, ovelhas, gado, muitíssimos animais.

[[v2-12-39]]

^<<v2-12-39,39>>^ E cozeram bolos asmos da massa que levaram do Egito; pois não se tinha levedado, porque foram lançados fora do Egito; não puderam deter-se e não haviam preparado para si provisões.

[[v2-12-40]]

^<<v2-12-40,40>>^ Ora, o tempo que os filhos de Israel habitaram no Egito foi de quatrocentos e trinta anos.

[[v2-12-41]]

^<<v2-12-41,41>>^ Aconteceu que, ao cabo dos quatrocentos e trinta anos, nesse mesmo dia, todas as hostes do SENHOR saíram da terra do Egito.

[[v2-12-42]]

^<<v2-12-42,42>>^ Esta noite se observará ao SENHOR, porque, nela, os tirou da terra do Egito; esta é a noite do SENHOR, que devem todos os filhos de Israel comemorar nas suas gerações.

[[v2-12-43]]

^<<v2-12-43,43>>^ Disse mais o SENHOR a Moisés e a Arão: Esta é a ordenança da Páscoa: nenhum estrangeiro comerá dela.

[[v2-12-44]]

^<<v2-12-44,44>>^ Porém todo escravo comprado por dinheiro, depois de o teres circuncidado, comerá dela.

[[v2-12-45]]

^<<v2-12-45,45>>^ O estrangeiro e o assalariado não comerão dela.

[[v2-12-46]]

^<<v2-12-46,46>>^ O cordeiro há de ser comido numa só casa; da sua carne não levareis fora da casa, nem lhe quebrareis osso nenhum.

[[v2-12-47]]

^<<v2-12-47,47>>^ Toda a congregação de Israel o fará.

[[v2-12-48]]

^<<v2-12-48,48>>^ Porém, se algum estrangeiro se hospedar contigo e quiser celebrar a Páscoa do SENHOR, seja-lhe circuncidado todo macho; e, então, se chegará, e a observará, e será como o natural da terra; mas nenhum incircunciso comerá dela.

[[v2-12-49]]

^<<v2-12-49,49>>^ A mesma lei haja para o natural e para o forasteiro que peregrinar entre vós.

[[v2-12-50]]

^<<v2-12-50,50>>^ Assim fizeram todos os filhos de Israel; como o SENHOR ordenara a Moisés e a Arão, assim fizeram.

[[v2-12-51]]

^<<v2-12-51,51>>^ Naquele mesmo dia, tirou o SENHOR os filhos de Israel do Egito, segundo as suas turmas.

'''

xref:002-exodo/002-exodo-011.adoc#v2-11-0[&#60; Capítulo Anterior] | <<v2-12-0,Topo>> | xref:002-exodo/002-exodo-013.adoc#v2-13-0[Próximo Capítulo &#62;]