include::./index.adoc[]

[[v2-23-0]]
=== Êxodo, 23
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-23-1]]

^<<v2-23-1,1>>^ Não espalharás notícias falsas, nem darás mão ao ímpio, para seres testemunha maldosa.

[[v2-23-2]]

^<<v2-23-2,2>>^ Não seguirás a multidão para fazeres mal; nem deporás, numa demanda, inclinando-te para a maioria, para torcer o direito.

[[v2-23-3]]

^<<v2-23-3,3>>^ Nem com o pobre serás parcial na sua demanda.

[[v2-23-4]]

^<<v2-23-4,4>>^ Se encontrares desgarrado o boi do teu inimigo ou o seu jumento, lho reconduzirás.

[[v2-23-5]]

^<<v2-23-5,5>>^ Se vires prostrado debaixo da sua carga o jumento daquele que te aborrece, não o abandonarás, mas ajudá-lo-ás a erguê-lo.

[[v2-23-6]]

^<<v2-23-6,6>>^ Não perverterás o julgamento do teu pobre na sua causa.

[[v2-23-7]]

^<<v2-23-7,7>>^ Da falsa acusação te afastarás; não matarás o inocente e o justo, porque não justificarei o ímpio.

[[v2-23-8]]

^<<v2-23-8,8>>^ Também suborno não aceitarás, porque o suborno cega até o perspicaz e perverte as palavras dos justos.

[[v2-23-9]]

^<<v2-23-9,9>>^ Também não oprimirás o forasteiro; pois vós conheceis o coração do forasteiro, visto que fostes forasteiros na terra do Egito.

[[v2-23-10]]

^<<v2-23-10,10>>^ Seis anos semearás a tua terra e recolherás os seus frutos;

[[v2-23-11]]

^<<v2-23-11,11>>^ porém, no sétimo ano, a deixarás descansar e não a cultivarás, para que os pobres do teu povo achem o que comer, e do sobejo comam os animais do campo. Assim farás com a tua vinha e com o teu olival.

[[v2-23-12]]

^<<v2-23-12,12>>^ Seis dias farás a tua obra, mas, ao sétimo dia, descansarás; para que descanse o teu boi e o teu jumento; e para que tome alento o filho da tua serva e o forasteiro.

[[v2-23-13]]

^<<v2-23-13,13>>^ Em tudo o que vos tenho dito, andai apercebidos; do nome de outros deuses nem vos lembreis, nem se ouça de vossa boca.

[[v2-23-14]]

^<<v2-23-14,14>>^ Três vezes no ano me celebrareis festa.

[[v2-23-15]]

^<<v2-23-15,15>>^ Guardarás a Festa dos Pães Asmos; sete dias comerás pães asmos, como te ordenei, ao tempo apontado no mês de abibe, porque nele saíste do Egito; ninguém apareça de mãos vazias perante mim.

[[v2-23-16]]

^<<v2-23-16,16>>^ Guardarás a Festa da Sega, dos primeiros frutos do teu trabalho, que houveres semeado no campo, e a Festa da Colheita, à saída do ano, quando recolheres do campo o fruto do teu trabalho.

[[v2-23-17]]

^<<v2-23-17,17>>^ Três vezes no ano, todo homem aparecerá diante do SENHOR Deus.

[[v2-23-18]]

^<<v2-23-18,18>>^ Não oferecerás o sangue do meu sacrifício com pão levedado, nem ficará gordura da minha festa durante a noite até pela manhã.

[[v2-23-19]]

^<<v2-23-19,19>>^ As primícias dos frutos da tua terra trarás à Casa do SENHOR, teu Deus. Não cozerás o cabrito no leite da sua própria mãe.

[[v2-23-20]]

^<<v2-23-20,20>>^ Eis que eu envio um Anjo adiante de ti, para que te guarde pelo caminho e te leve ao lugar que tenho preparado.

[[v2-23-21]]

^<<v2-23-21,21>>^ Guarda-te diante dele, e ouve a sua voz, e não te rebeles contra ele, porque não perdoará a vossa transgressão; pois nele está o meu nome.

[[v2-23-22]]

^<<v2-23-22,22>>^ Mas, se diligentemente lhe ouvires a voz e fizeres tudo o que eu disser, então, serei inimigo dos teus inimigos e adversário dos teus adversários.

[[v2-23-23]]

^<<v2-23-23,23>>^ Porque o meu Anjo irá adiante de ti e te levará aos amorreus, aos heteus, aos ferezeus, aos cananeus, aos heveus e aos jebuseus; e eu os destruirei.

[[v2-23-24]]

^<<v2-23-24,24>>^ Não adorarás os seus deuses, nem lhes darás culto, nem farás conforme as suas obras; antes, os destruirás totalmente e despedaçarás de todo as suas colunas.

[[v2-23-25]]

^<<v2-23-25,25>>^ Servireis ao SENHOR, vosso Deus, e ele abençoará o vosso pão e a vossa água; e tirará do vosso meio as enfermidades.

[[v2-23-26]]

^<<v2-23-26,26>>^ Na tua terra, não haverá mulher que aborte, nem estéril; completarei o número dos teus dias.

[[v2-23-27]]

^<<v2-23-27,27>>^ Enviarei o meu terror diante de ti, confundindo a todo povo onde entrares; farei que todos os teus inimigos te voltem as costas.

[[v2-23-28]]

^<<v2-23-28,28>>^ Também enviarei vespas diante de ti, que lancem os heveus, os cananeus e os heteus de diante de ti.

[[v2-23-29]]

^<<v2-23-29,29>>^ Não os lançarei de diante de ti num só ano, para que a terra se não torne em desolação, e as feras do campo se não multipliquem contra ti.

[[v2-23-30]]

^<<v2-23-30,30>>^ Pouco a pouco, os lançarei de diante de ti, até que te multipliques e possuas a terra por herança.

[[v2-23-31]]

^<<v2-23-31,31>>^ Porei os teus limites desde o mar Vermelho até ao mar dos filisteus e desde o deserto até ao Eufrates; porque darei nas tuas mãos os moradores da terra, para que os lances de diante de ti.

[[v2-23-32]]

^<<v2-23-32,32>>^ Não farás aliança nenhuma com eles, nem com os seus deuses.

[[v2-23-33]]

^<<v2-23-33,33>>^ Eles não habitarão na tua terra, para que te não façam pecar contra mim; se servires aos seus deuses, isso te será cilada.

'''

xref:002-exodo/002-exodo-022.adoc#v2-22-0[&#60; Capítulo Anterior] | <<v2-23-0,Topo>> | xref:002-exodo/002-exodo-024.adoc#v2-24-0[Próximo Capítulo &#62;]