include::./index.adoc[]

[[v2-27-0]]
=== Êxodo, 27
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-27-1]]

^<<v2-27-1,1>>^ Farás também o altar de madeira de acácia; de cinco côvados será o seu comprimento, e de cinco, a largura (será quadrado o altar), e de três côvados, a altura.

[[v2-27-2]]

^<<v2-27-2,2>>^ Dos quatro cantos farás levantar-se quatro chifres, os quais formarão uma só peça com o altar; e o cobrirás de bronze.

[[v2-27-3]]

^<<v2-27-3,3>>^ Far-lhe-ás também recipientes para recolher a sua cinza, e pás, e bacias, e garfos, e braseiros; todos esses utensílios farás de bronze.

[[v2-27-4]]

^<<v2-27-4,4>>^ Far-lhe-ás também uma grelha de bronze em forma de rede, à qual farás quatro argolas de metal nos seus quatro cantos,

[[v2-27-5]]

^<<v2-27-5,5>>^ e as porás dentro do rebordo do altar para baixo, de maneira que a rede chegue até ao meio do altar.

[[v2-27-6]]

^<<v2-27-6,6>>^ Farás também varais para o altar, varais de madeira de acácia, e os cobrirás de bronze.

[[v2-27-7]]

^<<v2-27-7,7>>^ Os varais se meterão nas argolas, de um e de outro lado do altar, quando for levado.

[[v2-27-8]]

^<<v2-27-8,8>>^ Oco e de tábuas o farás; como se te mostrou no monte, assim o farão.

[[v2-27-9]]

^<<v2-27-9,9>>^ Farás também o átrio do tabernáculo; ao lado meridional (que dá para o sul), o átrio terá cortinas de linho fino retorcido; o comprimento de cada lado será de cem côvados.

[[v2-27-10]]

^<<v2-27-10,10>>^ Também as suas vinte colunas e as suas vinte bases serão de bronze; os ganchos das colunas e as suas vergas serão de prata.

[[v2-27-11]]

^<<v2-27-11,11>>^ De igual modo, para o lado norte ao comprido, haverá cortinas de cem côvados de comprimento; e as suas vinte colunas e as suas vinte bases serão de bronze; os ganchos das colunas e as suas vergas serão de prata.

[[v2-27-12]]

^<<v2-27-12,12>>^ Na largura do átrio para o lado do ocidente, haverá cortinas de cinquenta côvados; as colunas serão dez, e as suas bases, dez.

[[v2-27-13]]

^<<v2-27-13,13>>^ A largura do átrio do lado oriental (para o levante) será de cinquenta côvados.

[[v2-27-14]]

^<<v2-27-14,14>>^ As cortinas para um lado da entrada serão de quinze côvados; as suas colunas serão três, e as suas bases, três.

[[v2-27-15]]

^<<v2-27-15,15>>^ Para o outro lado da entrada, haverá cortinas de quinze côvados; as suas colunas serão três, e as suas bases, três.

[[v2-27-16]]

^<<v2-27-16,16>>^ À porta do átrio, haverá um reposteiro de vinte côvados, de estofo azul, e púrpura, e carmesim, e linho fino retorcido, obra de bordador; as suas colunas serão quatro, e as suas bases, quatro.

[[v2-27-17]]

^<<v2-27-17,17>>^ Todas as colunas ao redor do átrio serão cingidas de vergas de prata; os seus ganchos serão de prata, mas as suas bases, de bronze.

[[v2-27-18]]

^<<v2-27-18,18>>^ O átrio terá cem côvados de comprimento, e cinquenta de largura por todo o lado, e cinco de altura; as suas cortinas serão de linho fino retorcido, e as suas bases, de bronze.

[[v2-27-19]]

^<<v2-27-19,19>>^ Todos os utensílios do tabernáculo em todo o seu serviço, e todas as suas estacas, e todas as estacas do átrio serão de bronze.

[[v2-27-20]]

^<<v2-27-20,20>>^ Ordenarás aos filhos de Israel que te tragam azeite puro de oliveira, batido, para o candelabro, para que haja lâmpada acesa continuamente.

[[v2-27-21]]

^<<v2-27-21,21>>^ Na tenda da congregação fora do véu, que está diante do Testemunho, Arão e seus filhos a conservarão em ordem, desde a tarde até pela manhã, perante o SENHOR; estatuto perpétuo será este a favor dos filhos de Israel pelas suas gerações.

'''

xref:002-exodo/002-exodo-026.adoc#v2-26-0[&#60; Capítulo Anterior] | <<v2-27-0,Topo>> | xref:002-exodo/002-exodo-028.adoc#v2-28-0[Próximo Capítulo &#62;]