include::./index.adoc[]

[[v2-5-0]]
=== Êxodo, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-5-1]]

^<<v2-5-1,1>>^ Depois, foram Moisés e Arão e disseram a Faraó: Assim diz o SENHOR, Deus de Israel: Deixa ir o meu povo, para que me celebre uma festa no deserto.

[[v2-5-2]]

^<<v2-5-2,2>>^ Respondeu Faraó: Quem é o SENHOR para que lhe ouça eu a voz e deixe ir a Israel? Não conheço o SENHOR, nem tampouco deixarei ir a Israel.

[[v2-5-3]]

^<<v2-5-3,3>>^ Eles prosseguiram: O Deus dos hebreus nos encontrou; deixa-nos ir, pois, caminho de três dias ao deserto, para que ofereçamos sacrifícios ao SENHOR, nosso Deus, e não venha ele sobre nós com pestilência ou com espada.

[[v2-5-4]]

^<<v2-5-4,4>>^ Então, lhes disse o rei do Egito: Por que, Moisés e Arão, por que interrompeis o povo no seu trabalho? Ide às vossas tarefas.

[[v2-5-5]]

^<<v2-5-5,5>>^ Disse também Faraó: O povo da terra já é muito, e vós o distraís das suas tarefas.

[[v2-5-6]]

^<<v2-5-6,6>>^ Naquele mesmo dia, pois, deu ordem Faraó aos superintendentes do povo e aos seus capatazes, dizendo:

[[v2-5-7]]

^<<v2-5-7,7>>^ Daqui em diante não torneis a dar palha ao povo, para fazer tijolos, como antes; eles mesmos que vão e ajuntem para si a palha.

[[v2-5-8]]

^<<v2-5-8,8>>^ E exigireis deles a mesma conta de tijolos que antes faziam; nada diminuireis dela; estão ociosos e, por isso, clamam: Vamos e sacrifiquemos ao nosso Deus.

[[v2-5-9]]

^<<v2-5-9,9>>^ Agrave-se o serviço sobre esses homens, para que nele se apliquem e não deem ouvidos a palavras mentirosas.

[[v2-5-10]]

^<<v2-5-10,10>>^ Então, saíram os superintendentes do povo e seus capatazes e falaram ao povo: Assim diz Faraó: Não vos darei palha.

[[v2-5-11]]

^<<v2-5-11,11>>^ Ide vós mesmos e ajuntai palha onde a puderdes achar; porque nada se diminuirá do vosso trabalho.

[[v2-5-12]]

^<<v2-5-12,12>>^ Então, o povo se espalhou por toda a terra do Egito a ajuntar restolho em lugar de palha.

[[v2-5-13]]

^<<v2-5-13,13>>^ Os superintendentes os apertavam, dizendo: Acabai vossa obra, a tarefa do dia, como quando havia palha.

[[v2-5-14]]

^<<v2-5-14,14>>^ E foram açoitados os capatazes dos filhos de Israel, que os superintendentes de Faraó tinham posto sobre eles; e os superintendentes lhes diziam: Por que não acabastes nem ontem, nem hoje a vossa tarefa, fazendo tijolos como antes?

[[v2-5-15]]

^<<v2-5-15,15>>^ Então, foram os capatazes dos filhos de Israel e clamaram a Faraó, dizendo: Por que tratas assim a teus servos?

[[v2-5-16]]

^<<v2-5-16,16>>^ Palha não se dá a teus servos, e nos dizem: Fazei tijolos. Eis que teus servos são açoitados; porém o teu próprio povo é que tem a culpa.

[[v2-5-17]]

^<<v2-5-17,17>>^ Mas ele respondeu: Estais ociosos, estais ociosos; por isso, dizeis: Vamos, sacrifiquemos ao SENHOR.

[[v2-5-18]]

^<<v2-5-18,18>>^ Ide, pois, agora, e trabalhai; palha, porém, não se vos dará; contudo, dareis a mesma quantidade de tijolos.

[[v2-5-19]]

^<<v2-5-19,19>>^ Então, os capatazes dos filhos de Israel se viram em aperto, porquanto se lhes dizia: Nada diminuireis dos vossos tijolos, da vossa tarefa diária.

[[v2-5-20]]

^<<v2-5-20,20>>^ Quando saíram da presença de Faraó, encontraram Moisés e Arão, que estavam à espera deles;

[[v2-5-21]]

^<<v2-5-21,21>>^ e lhes disseram: Olhe o SENHOR para vós outros e vos julgue, porquanto nos fizestes odiosos aos olhos de Faraó e diante dos seus servos, dando-lhes a espada na mão para nos matar.

[[v2-5-22]]

^<<v2-5-22,22>>^ Então, Moisés, tornando-se ao SENHOR, disse: Ó Senhor, por que afligiste este povo? Por que me enviaste?

[[v2-5-23]]

^<<v2-5-23,23>>^ Pois, desde que me apresentei a Faraó, para falar-lhe em teu nome, ele tem maltratado este povo; e tu, de nenhuma sorte, livraste o teu povo.

'''

xref:002-exodo/002-exodo-004.adoc#v2-4-0[&#60; Capítulo Anterior] | <<v2-5-0,Topo>> | xref:002-exodo/002-exodo-006.adoc#v2-6-0[Próximo Capítulo &#62;]