include::./index.adoc[]

[[v2-39-0]]
=== Êxodo, 39
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-39-1]]

^<<v2-39-1,1>>^ Fizeram também de estofo azul, púrpura e carmesim as vestes, finamente tecidas, para ministrar no santuário, e também fizeram as vestes sagradas para Arão, como o SENHOR ordenara a Moisés.

[[v2-39-2]]

^<<v2-39-2,2>>^ Fizeram a estola sacerdotal de ouro, estofo azul, púrpura, carmesim e linho fino retorcido.

[[v2-39-3]]

^<<v2-39-3,3>>^ De ouro batido fizeram lâminas delgadas e as cortaram em fios, para permearem entre o estofo azul, a púrpura, o carmesim e o linho fino da obra de desenhista.

[[v2-39-4]]

^<<v2-39-4,4>>^ Tinha duas ombreiras que se ajuntavam às suas duas extremidades, e assim se uniam.

[[v2-39-5]]

^<<v2-39-5,5>>^ O cinto de obra esmerada, que estava sobre a estola sacerdotal, era de obra igual, da mesma obra de ouro, estofo azul, púrpura, carmesim e linho fino retorcido, segundo o SENHOR ordenara a Moisés.

[[v2-39-6]]

^<<v2-39-6,6>>^ Também se prepararam as pedras de ônix, engastadas em ouro, trabalhadas como lavores de sinete, com os nomes dos filhos de Israel,

[[v2-39-7]]

^<<v2-39-7,7>>^ e as puseram nas ombreiras da estola sacerdotal, por pedras de memória aos filhos de Israel, segundo o SENHOR ordenara a Moisés.

[[v2-39-8]]

^<<v2-39-8,8>>^ Fizeram também o peitoral de obra esmerada, conforme a obra da estola sacerdotal: de ouro, estofo azul, púrpura, carmesim e linho fino retorcido.

[[v2-39-9]]

^<<v2-39-9,9>>^ Era quadrado; duplo fizeram o peitoral: de um palmo era o seu comprimento, e de um palmo dobrado, a sua largura.

[[v2-39-10]]

^<<v2-39-10,10>>^ Colocaram, nele, engastes de pedras, com quatro ordens de pedras: a ordem de sárdio, topázio e carbúnculo era a primeira;

[[v2-39-11]]

^<<v2-39-11,11>>^ a segunda ordem era de esmeralda, safira e diamante;

[[v2-39-12]]

^<<v2-39-12,12>>^ a terceira ordem era de jacinto, ágata e ametista;

[[v2-39-13]]

^<<v2-39-13,13>>^ e a quarta ordem era de berilo, ônix e jaspe; eram elas guarnecidas de ouro nos seus engastes.

[[v2-39-14]]

^<<v2-39-14,14>>^ As pedras eram conforme os nomes dos filhos de Israel, doze segundo os seus nomes; eram esculpidas como sinete, cada uma com o seu nome para as doze tribos.

[[v2-39-15]]

^<<v2-39-15,15>>^ E fizeram para o peitoral correntes como cordas, de obra trançada de ouro puro.

[[v2-39-16]]

^<<v2-39-16,16>>^ Também fizeram para o peitoral dois engastes de ouro e duas argolas de ouro; e puseram as duas argolas nas extremidades do peitoral.

[[v2-39-17]]

^<<v2-39-17,17>>^ E meteram as duas correntes trançadas de ouro nas duas argolas, nas extremidades do peitoral.

[[v2-39-18]]

^<<v2-39-18,18>>^ As outras duas pontas das duas correntes trançadas meteram nos dois engastes e as puseram nas ombreiras da estola sacerdotal, na frente dele.

[[v2-39-19]]

^<<v2-39-19,19>>^ Fizeram também duas argolas de ouro e as puseram nas duas extremidades do peitoral, na sua orla interior oposta à estola sacerdotal.

[[v2-39-20]]

^<<v2-39-20,20>>^ Fizeram também mais duas argolas de ouro e as puseram nas duas ombreiras da estola sacerdotal, abaixo, na frente dele, perto da sua juntura, sobre o cinto de obra esmerada da estola sacerdotal.

[[v2-39-21]]

^<<v2-39-21,21>>^ E ligaram o peitoral com as suas argolas às argolas da estola sacerdotal, por cima com uma fita azul, para que estivesse sobre o cinto de obra esmerada da estola sacerdotal, e nunca o peitoral se separasse da estola sacerdotal, segundo o SENHOR ordenara a Moisés.

[[v2-39-22]]

^<<v2-39-22,22>>^ Fizeram também a sobrepeliz da estola sacerdotal, de obra tecida, toda de estofo azul.

[[v2-39-23]]

^<<v2-39-23,23>>^ No meio dela havia uma abertura; era debruada como abertura de uma saia de malha, para que se não rompesse.

[[v2-39-24]]

^<<v2-39-24,24>>^ Em toda a orla da sobrepeliz, fizeram romãs de estofo azul, carmesim e linho retorcido.

[[v2-39-25]]

^<<v2-39-25,25>>^ Fizeram campainhas de ouro puro e as colocaram no meio das romãs em toda a orla da sobrepeliz;

[[v2-39-26]]

^<<v2-39-26,26>>^ uma campainha e uma romã, outra campainha e outra romã, em toda a orla da sobrepeliz, para se usar ao ministrar, segundo o SENHOR ordenara a Moisés.

[[v2-39-27]]

^<<v2-39-27,27>>^ Fizeram também as túnicas de linho fino, de obra tecida, para Arão e para seus filhos,

[[v2-39-28]]

^<<v2-39-28,28>>^ e a mitra de linho fino, e as tiaras de linho fino, e os calções de linho fino retorcido,

[[v2-39-29]]

^<<v2-39-29,29>>^ e o cinto de linho fino retorcido, e de estofo azul, e de púrpura, e de carmesim, obra de bordador, segundo o SENHOR ordenara a Moisés.

[[v2-39-30]]

^<<v2-39-30,30>>^ Também fizeram de ouro puro a lâmina da coroa sagrada e, nela, gravaram à maneira de gravuras de sinete: Santidade ao SENHOR.

[[v2-39-31]]

^<<v2-39-31,31>>^ E ataram-na com um cordão de estofo azul, para prender a lâmina à parte superior da mitra, segundo o SENHOR ordenara a Moisés.

[[v2-39-32]]

^<<v2-39-32,32>>^ Assim se concluiu toda a obra do tabernáculo da tenda da congregação; e os filhos de Israel fizeram tudo segundo o SENHOR tinha ordenado a Moisés; assim o fizeram.

[[v2-39-33]]

^<<v2-39-33,33>>^ Depois, trouxeram a Moisés o tabernáculo, a tenda e todos os seus pertences, os seus colchetes, as suas tábuas, as suas vergas, as suas colunas e as suas bases;

[[v2-39-34]]

^<<v2-39-34,34>>^ a coberta de peles de carneiro tintas de vermelho, e a coberta de peles finas, e o véu do reposteiro;

[[v2-39-35]]

^<<v2-39-35,35>>^ a arca do Testemunho, e os seus varais, e o propiciatório;

[[v2-39-36]]

^<<v2-39-36,36>>^ a mesa com todos os seus utensílios e os pães da proposição;

[[v2-39-37]]

^<<v2-39-37,37>>^ o candelabro de ouro puro com suas lâmpadas; as lâmpadas colocadas em ordem, e todos os seus utensílios, e o azeite para a iluminação;

[[v2-39-38]]

^<<v2-39-38,38>>^ também o altar de ouro, e o óleo da unção, e o incenso aromático, e o reposteiro da porta da tenda;

[[v2-39-39]]

^<<v2-39-39,39>>^ o altar de bronze, e a sua grelha de bronze, e os seus varais, e todos os seus utensílios, e a bacia, e o seu suporte;

[[v2-39-40]]

^<<v2-39-40,40>>^ as cortinas do átrio, e as suas colunas, e as suas bases, e o reposteiro para a porta do átrio, e as suas cordas, e os seus pregos, e todos os utensílios do serviço do tabernáculo, para a tenda da congregação;

[[v2-39-41]]

^<<v2-39-41,41>>^ as vestes finamente tecidas para ministrar no santuário, e as vestes sagradas do sacerdote Arão, e as vestes de seus filhos, para oficiarem como sacerdotes.

[[v2-39-42]]

^<<v2-39-42,42>>^ Tudo segundo o SENHOR ordenara a Moisés, assim fizeram os filhos de Israel toda a obra.

[[v2-39-43]]

^<<v2-39-43,43>>^ Viu, pois, Moisés toda a obra, e eis que a tinham feito segundo o SENHOR havia ordenado; assim a fizeram, e Moisés os abençoou.

'''

xref:002-exodo/002-exodo-038.adoc#v2-38-0[&#60; Capítulo Anterior] | <<v2-39-0,Topo>> | xref:002-exodo/002-exodo-040.adoc#v2-40-0[Próximo Capítulo &#62;]