include::./index.adoc[]

[[v2-1-0]]
=== Êxodo, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-1-1]]

^<<v2-1-1,1>>^ São estes os nomes dos filhos de Israel que entraram com Jacó no Egito; cada um entrou com sua família:

[[v2-1-2]]

^<<v2-1-2,2>>^ Rúben, Simeão, Levi e Judá,

[[v2-1-3]]

^<<v2-1-3,3>>^ Issacar, Zebulom e Benjamim,

[[v2-1-4]]

^<<v2-1-4,4>>^ Dã, Naftali, Gade e Aser.

[[v2-1-5]]

^<<v2-1-5,5>>^ Todas as pessoas, pois, que descenderam de Jacó foram setenta; José, porém, estava no Egito.

[[v2-1-6]]

^<<v2-1-6,6>>^ Faleceu José, e todos os seus irmãos, e toda aquela geração.

[[v2-1-7]]

^<<v2-1-7,7>>^ Mas os filhos de Israel foram fecundos, e aumentaram muito, e se multiplicaram, e grandemente se fortaleceram, de maneira que a terra se encheu deles.

[[v2-1-8]]

^<<v2-1-8,8>>^ Entrementes, se levantou novo rei sobre o Egito, que não conhecera a José.

[[v2-1-9]]

^<<v2-1-9,9>>^ Ele disse ao seu povo: Eis que o povo dos filhos de Israel é mais numeroso e mais forte do que nós.

[[v2-1-10]]

^<<v2-1-10,10>>^ Eia, usemos de astúcia para com ele, para que não se multiplique, e seja o caso que, vindo guerra, ele se ajunte com os nossos inimigos, peleje contra nós e saia da terra.

[[v2-1-11]]

^<<v2-1-11,11>>^ E os egípcios puseram sobre eles feitores de obras, para os afligirem com suas cargas. E os israelitas edificaram a Faraó as cidades-celeiros, Pitom e Ramessés.

[[v2-1-12]]

^<<v2-1-12,12>>^ Mas, quanto mais os afligiam, tanto mais se multiplicavam e tanto mais se espalhavam; de maneira que se inquietavam por causa dos filhos de Israel;

[[v2-1-13]]

^<<v2-1-13,13>>^ então, os egípcios, com tirania, faziam servir os filhos de Israel

[[v2-1-14]]

^<<v2-1-14,14>>^ e lhes fizeram amargar a vida com dura servidão, em barro, e em tijolos, e com todo o trabalho no campo; com todo o serviço em que na tirania os serviam.

[[v2-1-15]]

^<<v2-1-15,15>>^ O rei do Egito ordenou às parteiras hebreias, das quais uma se chamava Sifrá, e outra, Puá,

[[v2-1-16]]

^<<v2-1-16,16>>^ dizendo: Quando servirdes de parteira às hebreias, examinai: se for filho, matai-o; mas, se for filha, que viva.

[[v2-1-17]]

^<<v2-1-17,17>>^ As parteiras, porém, temeram a Deus e não fizeram como lhes ordenara o rei do Egito; antes, deixaram viver os meninos.

[[v2-1-18]]

^<<v2-1-18,18>>^ Então, o rei do Egito chamou as parteiras e lhes disse: Por que fizestes isso e deixastes viver os meninos?

[[v2-1-19]]

^<<v2-1-19,19>>^ Responderam as parteiras a Faraó: É que as mulheres hebreias não são como as egípcias; são vigorosas e, antes que lhes chegue a parteira, já deram à luz os seus filhos.

[[v2-1-20]]

^<<v2-1-20,20>>^ E Deus fez bem às parteiras; e o povo aumentou e se tornou muito forte.

[[v2-1-21]]

^<<v2-1-21,21>>^ E, porque as parteiras temeram a Deus, ele lhes constituiu família.

[[v2-1-22]]

^<<v2-1-22,22>>^ Então, ordenou Faraó a todo o seu povo, dizendo: A todos os filhos que nascerem aos hebreus lançareis no Nilo, mas a todas as filhas deixareis viver.

'''

xref:001-genesis/001-genesis-050.adoc#v1-50-0[&#60; Capítulo Anterior] | <<v2-1-0,Topo>> | xref:002-exodo/002-exodo-002.adoc#v2-2-0[Próximo Capítulo &#62;]