include::./index.adoc[]

[[v2-36-0]]
=== Êxodo, 36
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-36-1]]

^<<v2-36-1,1>>^ Assim, trabalharam Bezalel, e Aoliabe, e todo homem hábil a quem o SENHOR dera habilidade e inteligência para saberem fazer toda obra para o serviço do santuário, segundo tudo o que o SENHOR havia ordenado.

[[v2-36-2]]

^<<v2-36-2,2>>^ Moisés chamou a Bezalel, e a Aoliabe, e a todo homem hábil em cujo coração o SENHOR tinha posto sabedoria, isto é, a todo homem cujo coração o impeliu a se chegar à obra para fazê-la.

[[v2-36-3]]

^<<v2-36-3,3>>^ Estes receberam de Moisés todas as ofertas que os filhos de Israel haviam trazido para a obra do serviço do santuário, para fazê-la; e, ainda, cada manhã o povo trazia a Moisés ofertas voluntárias.

[[v2-36-4]]

^<<v2-36-4,4>>^ Então, deixando cada um a obra que fazia, vieram todos os homens sábios que se ocupavam em toda a obra do santuário

[[v2-36-5]]

^<<v2-36-5,5>>^ e disseram a Moisés: O povo traz muito mais do que é necessário para o serviço da obra que o SENHOR ordenou se fizesse.

[[v2-36-6]]

^<<v2-36-6,6>>^ Então, ordenou Moisés — e a ordem foi proclamada no arraial, dizendo: Nenhum homem ou mulher faça mais obra alguma para a oferta do santuário. Assim, o povo foi proibido de trazer mais.

[[v2-36-7]]

^<<v2-36-7,7>>^ Porque o material que tinham era suficiente para toda a obra que se devia fazer e ainda sobejava.

[[v2-36-8]]

^<<v2-36-8,8>>^ Assim, todos os homens hábeis, entre os que faziam a obra, fizeram o tabernáculo com dez cortinas de linho fino retorcido, estofo azul, púrpura e carmesim com querubins; de obra de artista as fizeram.

[[v2-36-9]]

^<<v2-36-9,9>>^ O comprimento de cada cortina era de vinte e oito côvados, e a largura, de quatro côvados; todas as cortinas eram de igual medida.

[[v2-36-10]]

^<<v2-36-10,10>>^ Cinco cortinas eram ligadas uma à outra; e as outras cinco também ligadas uma à outra.

[[v2-36-11]]

^<<v2-36-11,11>>^ Fizeram laçadas de estofo azul na orla da cortina, que estava na extremidade do primeiro agrupamento; e de igual modo fizeram na orla da cortina, que estava na extremidade do segundo agrupamento.

[[v2-36-12]]

^<<v2-36-12,12>>^ Cinquenta laçadas fizeram numa cortina, e cinquenta, na outra cortina na extremidade do segundo agrupamento; as laçadas eram contrapostas uma à outra.

[[v2-36-13]]

^<<v2-36-13,13>>^ Fizeram cinquenta colchetes de ouro, com os quais prenderam as cortinas uma à outra; e o tabernáculo passou a ser um todo.

[[v2-36-14]]

^<<v2-36-14,14>>^ Fizeram também de pelos de cabra cortinas para servirem de tenda sobre o tabernáculo; fizeram onze cortinas.

[[v2-36-15]]

^<<v2-36-15,15>>^ O comprimento de cada cortina era de trinta côvados, e a largura, de quatro côvados; as onze cortinas eram de igual medida.

[[v2-36-16]]

^<<v2-36-16,16>>^ Ajuntaram à parte cinco cortinas entre si e, de igual modo, as seis restantes.

[[v2-36-17]]

^<<v2-36-17,17>>^ E fizeram cinquenta laçadas na orla da cortina, que estava na extremidade do primeiro agrupamento.

[[v2-36-18]]

^<<v2-36-18,18>>^ Fizeram também cinquenta colchetes de bronze para ajuntar a tenda, para que viesse a ser um todo.

[[v2-36-19]]

^<<v2-36-19,19>>^ Fizeram também de peles de carneiro tintas de vermelho uma coberta para a tenda e outra coberta de peles finas.

[[v2-36-20]]

^<<v2-36-20,20>>^ Fizeram também de madeira de acácia as tábuas para o tabernáculo, as quais eram colocadas verticalmente.

[[v2-36-21]]

^<<v2-36-21,21>>^ Cada uma das tábuas tinha dez côvados de comprimento e côvado e meio de largura.

[[v2-36-22]]

^<<v2-36-22,22>>^ Cada tábua tinha dois encaixes, travados um com o outro; assim fizeram com todas as tábuas do tabernáculo.

[[v2-36-23]]

^<<v2-36-23,23>>^ No preparar as tábuas para o tabernáculo, fizeram vinte delas para o lado sul.

[[v2-36-24]]

^<<v2-36-24,24>>^ Fizeram também quarenta bases de prata debaixo das vinte tábuas: duas bases debaixo de uma tábua para os seus dois encaixes e duas bases debaixo de outra tábua para os seus dois encaixes.

[[v2-36-25]]

^<<v2-36-25,25>>^ Também fizeram vinte tábuas ao outro lado do tabernáculo, para o lado norte,

[[v2-36-26]]

^<<v2-36-26,26>>^ com as suas quarenta bases de prata: duas bases debaixo de uma tábua e duas bases debaixo de outra tábua;

[[v2-36-27]]

^<<v2-36-27,27>>^ ao lado do tabernáculo para o ocidente, fizeram seis tábuas.

[[v2-36-28]]

^<<v2-36-28,28>>^ Fizeram também duas tábuas para os cantos do tabernáculo de ambos os lados,

[[v2-36-29]]

^<<v2-36-29,29>>^ as quais, por baixo, estavam separadas, mas, em cima, se ajustavam à primeira argola; assim se fez com as duas tábuas nos dois cantos.

[[v2-36-30]]

^<<v2-36-30,30>>^ Assim eram as oito tábuas com as suas bases de prata, dezesseis bases: duas bases debaixo de uma tábua e duas debaixo de outra tábua.

[[v2-36-31]]

^<<v2-36-31,31>>^ Fizeram também travessas de madeira de acácia; cinco para as tábuas de um lado do tabernáculo,

[[v2-36-32]]

^<<v2-36-32,32>>^ cinco para as tábuas do outro lado do tabernáculo e cinco para as tábuas do tabernáculo, ao lado posterior, que olha para o ocidente.

[[v2-36-33]]

^<<v2-36-33,33>>^ A travessa do meio passava ao meio das tábuas, de uma extremidade à outra.

[[v2-36-34]]

^<<v2-36-34,34>>^ Cobriram de ouro as tábuas e de ouro fizeram as suas argolas, pelas quais passavam as travessas; e cobriram também de ouro as travessas.

[[v2-36-35]]

^<<v2-36-35,35>>^ Fizeram também o véu de estofo azul, púrpura, carmesim e linho fino retorcido; com querubins o fizeram de obra de artista.

[[v2-36-36]]

^<<v2-36-36,36>>^ E fizeram-lhe quatro colunas de madeira de acácia, cobertas de ouro; os seus colchetes eram de ouro, sobre quatro bases de prata.

[[v2-36-37]]

^<<v2-36-37,37>>^ Fizeram também para a porta da tenda um reposteiro de estofo azul, púrpura, carmesim e linho fino retorcido, obra de bordador,

[[v2-36-38]]

^<<v2-36-38,38>>^ e as suas cinco colunas, e os seus colchetes; as suas cabeças e as suas molduras cobriram de ouro, mas as suas cinco bases eram de bronze.

'''

xref:002-exodo/002-exodo-035.adoc#v2-35-0[&#60; Capítulo Anterior] | <<v2-36-0,Topo>> | xref:002-exodo/002-exodo-037.adoc#v2-37-0[Próximo Capítulo &#62;]