include::./index.adoc[]

[[v2-40-0]]
=== Êxodo, 40
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-40-1]]

^<<v2-40-1,1>>^ Depois, disse o SENHOR a Moisés:

[[v2-40-2]]

^<<v2-40-2,2>>^ No primeiro dia do primeiro mês, levantarás o tabernáculo da tenda da congregação.

[[v2-40-3]]

^<<v2-40-3,3>>^ Porás, nele, a arca do Testemunho e a cobrirás com o véu.

[[v2-40-4]]

^<<v2-40-4,4>>^ Meterás, nele, a mesa e porás por ordem as coisas que estão sobre ela; também meterás, nele, o candelabro e acenderás as suas lâmpadas.

[[v2-40-5]]

^<<v2-40-5,5>>^ Porás o altar de ouro para o incenso diante da arca do Testemunho e pendurarás o reposteiro da porta do tabernáculo.

[[v2-40-6]]

^<<v2-40-6,6>>^ Porás o altar do holocausto diante da porta do tabernáculo da tenda da congregação.

[[v2-40-7]]

^<<v2-40-7,7>>^ Porás a bacia entre a tenda da congregação e o altar e a encherás de água.

[[v2-40-8]]

^<<v2-40-8,8>>^ Depois, porás o átrio ao redor e pendurarás o reposteiro à porta do átrio.

[[v2-40-9]]

^<<v2-40-9,9>>^ E tomarás o óleo da unção, e ungirás o tabernáculo e tudo o que nele está, e o consagrarás com todos os seus pertences; e será santo.

[[v2-40-10]]

^<<v2-40-10,10>>^ Ungirás também o altar do holocausto e todos os seus utensílios e consagrarás o altar; e o altar se tornará santíssimo.

[[v2-40-11]]

^<<v2-40-11,11>>^ Então, ungirás a bacia e o seu suporte e a consagrarás.

[[v2-40-12]]

^<<v2-40-12,12>>^ Farás também chegar Arão e seus filhos à porta da tenda da congregação e os lavarás com água.

[[v2-40-13]]

^<<v2-40-13,13>>^ Vestirás Arão das vestes sagradas, e o ungirás, e o consagrarás para que me oficie como sacerdote.

[[v2-40-14]]

^<<v2-40-14,14>>^ Também farás chegar seus filhos, e lhes vestirás as túnicas,

[[v2-40-15]]

^<<v2-40-15,15>>^ e os ungirás como ungiste seu pai, para que me oficiem como sacerdotes; sua unção lhes será por sacerdócio perpétuo durante as suas gerações.

[[v2-40-16]]

^<<v2-40-16,16>>^ E tudo fez Moisés segundo o SENHOR lhe havia ordenado; assim o fez.

[[v2-40-17]]

^<<v2-40-17,17>>^ No primeiro mês do segundo ano, no primeiro dia do mês, se levantou o tabernáculo.

[[v2-40-18]]

^<<v2-40-18,18>>^ Moisés levantou o tabernáculo, e pôs as suas bases, e armou as suas tábuas, e meteu, nele, as suas vergas, e levantou as suas colunas;

[[v2-40-19]]

^<<v2-40-19,19>>^ estendeu a tenda sobre o tabernáculo e pôs a coberta da tenda por cima, segundo o SENHOR ordenara a Moisés.

[[v2-40-20]]

^<<v2-40-20,20>>^ Tomou o Testemunho, e o pôs na arca, e meteu os varais na arca, e pôs o propiciatório em cima da arca.

[[v2-40-21]]

^<<v2-40-21,21>>^ Introduziu a arca no tabernáculo, e pendurou o véu do reposteiro, e com ele cobriu a arca do Testemunho, segundo o SENHOR ordenara a Moisés.

[[v2-40-22]]

^<<v2-40-22,22>>^ Pôs também a mesa na tenda da congregação, ao lado do tabernáculo, para o norte, fora do véu,

[[v2-40-23]]

^<<v2-40-23,23>>^ e sobre ela pôs em ordem os pães da proposição perante o SENHOR, segundo o SENHOR ordenara a Moisés.

[[v2-40-24]]

^<<v2-40-24,24>>^ Pôs também, na tenda da congregação, o candelabro defronte da mesa, ao lado do tabernáculo, para o sul,

[[v2-40-25]]

^<<v2-40-25,25>>^ e preparou as lâmpadas perante o SENHOR, segundo o SENHOR ordenara a Moisés.

[[v2-40-26]]

^<<v2-40-26,26>>^ Pôs o altar de ouro na tenda da congregação, diante do véu,

[[v2-40-27]]

^<<v2-40-27,27>>^ e acendeu sobre ele o incenso aromático, segundo o SENHOR ordenara a Moisés.

[[v2-40-28]]

^<<v2-40-28,28>>^ Pendurou também o reposteiro da porta do tabernáculo,

[[v2-40-29]]

^<<v2-40-29,29>>^ pôs o altar do holocausto à porta do tabernáculo da tenda da congregação e ofereceu sobre ele holocausto e oferta de cereais, segundo o SENHOR ordenara a Moisés.

[[v2-40-30]]

^<<v2-40-30,30>>^ Pôs a bacia entre a tenda da congregação e o altar e a encheu de água, para se lavar.

[[v2-40-31]]

^<<v2-40-31,31>>^ Nela, Moisés, Arão e seus filhos lavavam as mãos e os pés,

[[v2-40-32]]

^<<v2-40-32,32>>^ quando entravam na tenda da congregação e quando se chegavam ao altar, segundo o SENHOR ordenara a Moisés.

[[v2-40-33]]

^<<v2-40-33,33>>^ Levantou também o átrio ao redor do tabernáculo e do altar e pendurou o reposteiro da porta do átrio. Assim Moisés acabou a obra.

[[v2-40-34]]

^<<v2-40-34,34>>^ Então, a nuvem cobriu a tenda da congregação, e a glória do SENHOR encheu o tabernáculo.

[[v2-40-35]]

^<<v2-40-35,35>>^ Moisés não podia entrar na tenda da congregação, porque a nuvem permanecia sobre ela, e a glória do SENHOR enchia o tabernáculo.

[[v2-40-36]]

^<<v2-40-36,36>>^ Quando a nuvem se levantava de sobre o tabernáculo, os filhos de Israel caminhavam avante, em todas as suas jornadas;

[[v2-40-37]]

^<<v2-40-37,37>>^ se a nuvem, porém, não se levantava, não caminhavam, até ao dia em que ela se levantava.

[[v2-40-38]]

^<<v2-40-38,38>>^ De dia, a nuvem do SENHOR repousava sobre o tabernáculo, e, de noite, havia fogo nela, à vista de toda a casa de Israel, em todas as suas jornadas.

'''

xref:002-exodo/002-exodo-039.adoc#v2-39-0[&#60; Capítulo Anterior] | <<v2-40-0,Topo>> | xref:003-levitico/003-levitico-001.adoc#v3-1-0[Próximo Capítulo &#62;]