include::./index.adoc[]

[[v2-28-0]]
=== Êxodo, 28
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-28-1]]

^<<v2-28-1,1>>^ Faze também vir para junto de ti Arão, teu irmão, e seus filhos com ele, dentre os filhos de Israel, para me oficiarem como sacerdotes, a saber, Arão e seus filhos Nadabe, Abiú, Eleazar e Itamar.

[[v2-28-2]]

^<<v2-28-2,2>>^ Farás vestes sagradas para Arão, teu irmão, para glória e ornamento.

[[v2-28-3]]

^<<v2-28-3,3>>^ Falarás também a todos os homens hábeis a quem enchi do espírito de sabedoria, que façam vestes para Arão para consagrá-lo, para que me ministre o ofício sacerdotal.

[[v2-28-4]]

^<<v2-28-4,4>>^ As vestes, pois, que farão são estas: um peitoral, uma estola sacerdotal, uma sobrepeliz, uma túnica bordada, mitra e cinto. Farão vestes sagradas para Arão, teu irmão, e para seus filhos, para me oficiarem como sacerdotes.

[[v2-28-5]]

^<<v2-28-5,5>>^ Tomarão ouro, estofo azul, púrpura, carmesim e linho fino

[[v2-28-6]]

^<<v2-28-6,6>>^ e farão a estola sacerdotal de ouro, e estofo azul, e púrpura, e carmesim, e linho fino retorcido, obra esmerada.

[[v2-28-7]]

^<<v2-28-7,7>>^ Terá duas ombreiras que se unam às suas duas extremidades, e assim se unirá.

[[v2-28-8]]

^<<v2-28-8,8>>^ E o cinto de obra esmerada, que estará sobre a estola sacerdotal, será de obra igual, da mesma obra de ouro, e estofo azul, e púrpura, e carmesim, e linho fino retorcido.

[[v2-28-9]]

^<<v2-28-9,9>>^ Tomarás duas pedras de ônix e gravarás nelas os nomes dos filhos de Israel:

[[v2-28-10]]

^<<v2-28-10,10>>^ seis de seus nomes numa pedra e os outros seis na outra pedra, segundo a ordem do seu nascimento.

[[v2-28-11]]

^<<v2-28-11,11>>^ Conforme a obra de lapidador, como lavores de sinete, gravarás as duas pedras com os nomes dos filhos de Israel; engastadas ao redor de ouro, as farás.

[[v2-28-12]]

^<<v2-28-12,12>>^ E porás as duas pedras nas ombreiras da estola sacerdotal, por pedras de memória aos filhos de Israel; e Arão levará os seus nomes sobre ambos os seus ombros, para memória diante do SENHOR.

[[v2-28-13]]

^<<v2-28-13,13>>^ Farás também engastes de ouro

[[v2-28-14]]

^<<v2-28-14,14>>^ e duas correntes de ouro puro; obra de fieira as farás; e as correntes de fieira prenderás nos engastes.

[[v2-28-15]]

^<<v2-28-15,15>>^ Farás também o peitoral do juízo de obra esmerada, conforme a obra da estola sacerdotal o farás: de ouro, e estofo azul, e púrpura, e carmesim, e linho fino retorcido o farás.

[[v2-28-16]]

^<<v2-28-16,16>>^ Quadrado e duplo, será de um palmo o seu comprimento, e de um palmo, a sua largura.

[[v2-28-17]]

^<<v2-28-17,17>>^ Colocarás nele engaste de pedras, com quatro ordens de pedras: a ordem de sárdio, topázio e carbúnculo será a primeira ordem;

[[v2-28-18]]

^<<v2-28-18,18>>^ a segunda ordem será de esmeralda, safira e diamante;

[[v2-28-19]]

^<<v2-28-19,19>>^ a terceira ordem será de jacinto, ágata e ametista;

[[v2-28-20]]

^<<v2-28-20,20>>^ a quarta ordem será de berilo, ônix e jaspe; elas serão guarnecidas de ouro nos seus engastes.

[[v2-28-21]]

^<<v2-28-21,21>>^ As pedras serão conforme os nomes dos filhos de Israel, doze, segundo os seus nomes; serão esculpidas como sinetes, cada uma com o seu nome, para as doze tribos.

[[v2-28-22]]

^<<v2-28-22,22>>^ Para o peitoral farás correntes como cordas, de obra trançada de ouro puro.

[[v2-28-23]]

^<<v2-28-23,23>>^ Também farás para o peitoral duas argolas de ouro e porás as duas argolas nas extremidades do peitoral.

[[v2-28-24]]

^<<v2-28-24,24>>^ Então, meterás as duas correntes de ouro nas duas argolas, nas extremidades do peitoral.

[[v2-28-25]]

^<<v2-28-25,25>>^ As duas pontas das correntes prenderás nos dois engastes e as porás nas ombreiras da estola sacerdotal na frente dele.

[[v2-28-26]]

^<<v2-28-26,26>>^ Farás também duas argolas de ouro e as porás nas duas extremidades do peitoral, na sua orla interior junto à estola sacerdotal.

[[v2-28-27]]

^<<v2-28-27,27>>^ Farás também duas argolas de ouro e as porás nas duas ombreiras da estola sacerdotal, abaixo, na frente dele, perto da sua juntura, sobre o cinto de obra esmerada da estola sacerdotal.

[[v2-28-28]]

^<<v2-28-28,28>>^ E ligarão o peitoral com as suas argolas às argolas da estola sacerdotal por cima com uma fita azul, para que esteja sobre o cinto da estola sacerdotal; e nunca o peitoral se separará da estola sacerdotal.

[[v2-28-29]]

^<<v2-28-29,29>>^ Assim, Arão levará os nomes dos filhos de Israel no peitoral do juízo sobre o seu coração, quando entrar no santuário, para memória diante do SENHOR continuamente.

[[v2-28-30]]

^<<v2-28-30,30>>^ Também porás no peitoral do juízo o Urim e o Tumim, para que estejam sobre o coração de Arão, quando entrar perante o SENHOR; assim, Arão levará o juízo dos filhos de Israel sobre o seu coração diante do SENHOR continuamente.

[[v2-28-31]]

^<<v2-28-31,31>>^ Farás também a sobrepeliz da estola sacerdotal toda de estofo azul.

[[v2-28-32]]

^<<v2-28-32,32>>^ No meio dela, haverá uma abertura para a cabeça; será debruada essa abertura, como a abertura de uma saia de malha, para que não se rompa.

[[v2-28-33]]

^<<v2-28-33,33>>^ Em toda a orla da sobrepeliz, farás romãs de estofo azul, e púrpura, e carmesim; e campainhas de ouro no meio delas.

[[v2-28-34]]

^<<v2-28-34,34>>^ Haverá em toda a orla da sobrepeliz uma campainha de ouro e uma romã, outra campainha de ouro e outra romã.

[[v2-28-35]]

^<<v2-28-35,35>>^ Esta sobrepeliz estará sobre Arão quando ministrar, para que se ouça o seu sonido, quando entrar no santuário diante do SENHOR e quando sair; e isso para que não morra.

[[v2-28-36]]

^<<v2-28-36,36>>^ Farás também uma lâmina de ouro puro e nela gravarás à maneira de gravuras de sinetes: Santidade ao SENHOR.

[[v2-28-37]]

^<<v2-28-37,37>>^ Atá-la-ás com um cordão de estofo azul, de maneira que esteja na mitra; bem na frente da mitra estará.

[[v2-28-38]]

^<<v2-28-38,38>>^ E estará sobre a testa de Arão, para que Arão leve a iniquidade concernente às coisas santas que os filhos de Israel consagrarem em todas as ofertas de suas coisas santas; sempre estará sobre a testa de Arão, para que eles sejam aceitos perante o SENHOR.

[[v2-28-39]]

^<<v2-28-39,39>>^ Tecerás, quadriculada, a túnica de linho fino e farás uma mitra de linho fino e um cinto de obra de bordador.

[[v2-28-40]]

^<<v2-28-40,40>>^ Para os filhos de Arão farás túnicas, e cintos, e tiaras; fá-los-ás para glória e ornamento.

[[v2-28-41]]

^<<v2-28-41,41>>^ E, com isso, vestirás Arão, teu irmão, bem como seus filhos; e os ungirás, e consagrarás, e santificarás, para que me oficiem como sacerdotes.

[[v2-28-42]]

^<<v2-28-42,42>>^ Faze-lhes também calções de linho, para cobrirem a pele nua; irão da cintura às coxas.

[[v2-28-43]]

^<<v2-28-43,43>>^ E estarão sobre Arão e sobre seus filhos, quando entrarem na tenda da congregação ou quando se chegarem ao altar para ministrar no santuário, para que não levem iniquidade e morram; isto será estatuto perpétuo para ele e para sua posteridade depois dele.

'''

xref:002-exodo/002-exodo-027.adoc#v2-27-0[&#60; Capítulo Anterior] | <<v2-28-0,Topo>> | xref:002-exodo/002-exodo-029.adoc#v2-29-0[Próximo Capítulo &#62;]