include::./index.adoc[]

[[v2-18-0]]
=== Êxodo, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-18-1]]

^<<v2-18-1,1>>^ Ora, Jetro, sacerdote de Midiã, sogro de Moisés, ouviu todas as coisas que Deus tinha feito a Moisés e a Israel, seu povo; como o SENHOR trouxera a Israel do Egito.

[[v2-18-2]]

^<<v2-18-2,2>>^ Jetro, sogro de Moisés, tomou a Zípora, mulher de Moisés, depois que este lha enviara,

[[v2-18-3]]

^<<v2-18-3,3>>^ com os dois filhos dela, dos quais um se chamava Gérson, pois disse Moisés: Fui peregrino em terra estrangeira;

[[v2-18-4]]

^<<v2-18-4,4>>^ e o outro, Eliézer, pois disse: O Deus de meu pai foi a minha ajuda e me livrou da espada de Faraó.

[[v2-18-5]]

^<<v2-18-5,5>>^ Veio Jetro, sogro de Moisés, com os filhos e a mulher deste, a Moisés no deserto onde se achava acampado, junto ao monte de Deus,

[[v2-18-6]]

^<<v2-18-6,6>>^ e mandou dizer a Moisés: Eu, teu sogro Jetro, venho a ti, com a tua mulher e seus dois filhos.

[[v2-18-7]]

^<<v2-18-7,7>>^ Então, saiu Moisés ao encontro do seu sogro, inclinou-se e o beijou; e, indagando pelo bem-estar um do outro, entraram na tenda.

[[v2-18-8]]

^<<v2-18-8,8>>^ Contou Moisés a seu sogro tudo o que o SENHOR havia feito a Faraó e aos egípcios por amor de Israel, e todo o trabalho que passaram no Egito, e como o SENHOR os livrara.

[[v2-18-9]]

^<<v2-18-9,9>>^ Alegrou-se Jetro de todo o bem que o SENHOR fizera a Israel, livrando-o da mão dos egípcios,

[[v2-18-10]]

^<<v2-18-10,10>>^ e disse: Bendito seja o SENHOR, que vos livrou da mão dos egípcios e da mão de Faraó;

[[v2-18-11]]

^<<v2-18-11,11>>^ agora, sei que o SENHOR é maior que todos os deuses, porque livrou este povo de debaixo da mão dos egípcios, quando agiram arrogantemente contra o povo.

[[v2-18-12]]

^<<v2-18-12,12>>^ Então, Jetro, sogro de Moisés, tomou holocausto e sacrifícios para Deus; e veio Arão e todos os anciãos de Israel para comerem pão com o sogro de Moisés, diante de Deus.

[[v2-18-13]]

^<<v2-18-13,13>>^ No dia seguinte, assentou-se Moisés para julgar o povo; e o povo estava em pé diante de Moisés desde a manhã até ao pôr do sol.

[[v2-18-14]]

^<<v2-18-14,14>>^ Vendo, pois, o sogro de Moisés tudo o que ele fazia ao povo, disse: Que é isto que fazes ao povo? Por que te assentas só, e todo o povo está em pé diante de ti, desde a manhã até ao pôr do sol?

[[v2-18-15]]

^<<v2-18-15,15>>^ Respondeu Moisés a seu sogro: É porque o povo me vem a mim para consultar a Deus;

[[v2-18-16]]

^<<v2-18-16,16>>^ quando tem alguma questão, vem a mim, para que eu julgue entre um e outro e lhes declare os estatutos de Deus e as suas leis.

[[v2-18-17]]

^<<v2-18-17,17>>^ O sogro de Moisés, porém, lhe disse: Não é bom o que fazes.

[[v2-18-18]]

^<<v2-18-18,18>>^ Sem dúvida, desfalecerás, tanto tu como este povo que está contigo; pois isto é pesado demais para ti; tu só não o podes fazer.

[[v2-18-19]]

^<<v2-18-19,19>>^ Ouve, pois, as minhas palavras; eu te aconselharei, e Deus seja contigo; representa o povo perante Deus, leva as suas causas a Deus,

[[v2-18-20]]

^<<v2-18-20,20>>^ ensina-lhes os estatutos e as leis e faze-lhes saber o caminho em que devem andar e a obra que devem fazer.

[[v2-18-21]]

^<<v2-18-21,21>>^ Procura dentre o povo homens capazes, tementes a Deus, homens de verdade, que aborreçam a avareza; põe-nos sobre eles por chefes de mil, chefes de cem, chefes de cinquenta e chefes de dez;

[[v2-18-22]]

^<<v2-18-22,22>>^ para que julguem este povo em todo tempo. Toda causa grave trarão a ti, mas toda causa pequena eles mesmos julgarão; será assim mais fácil para ti, e eles levarão a carga contigo.

[[v2-18-23]]

^<<v2-18-23,23>>^ Se isto fizeres, e assim Deus to mandar, poderás, então, suportar; e assim também todo este povo tornará em paz ao seu lugar.

[[v2-18-24]]

^<<v2-18-24,24>>^ Moisés atendeu às palavras de seu sogro e fez tudo quanto este lhe dissera.

[[v2-18-25]]

^<<v2-18-25,25>>^ Escolheu Moisés homens capazes, de todo o Israel, e os constituiu por cabeças sobre o povo: chefes de mil, chefes de cem, chefes de cinquenta e chefes de dez.

[[v2-18-26]]

^<<v2-18-26,26>>^ Estes julgaram o povo em todo tempo; a causa grave trouxeram a Moisés e toda causa simples julgaram eles.

[[v2-18-27]]

^<<v2-18-27,27>>^ Então, se despediu Moisés de seu sogro, e este se foi para a sua terra.

'''

xref:002-exodo/002-exodo-017.adoc#v2-17-0[&#60; Capítulo Anterior] | <<v2-18-0,Topo>> | xref:002-exodo/002-exodo-019.adoc#v2-19-0[Próximo Capítulo &#62;]