include::./index.adoc[]

[[v2-31-0]]
=== Êxodo, 31
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-31-1]]

^<<v2-31-1,1>>^ Disse mais o SENHOR a Moisés:

[[v2-31-2]]

^<<v2-31-2,2>>^ Eis que chamei pelo nome a Bezalel, filho de Uri, filho de Hur, da tribo de Judá,

[[v2-31-3]]

^<<v2-31-3,3>>^ e o enchi do Espírito de Deus, de habilidade, de inteligência e de conhecimento, em todo artifício,

[[v2-31-4]]

^<<v2-31-4,4>>^ para elaborar desenhos e trabalhar em ouro, em prata, em bronze,

[[v2-31-5]]

^<<v2-31-5,5>>^ para lapidação de pedras de engaste, para entalho de madeira, para toda sorte de lavores.

[[v2-31-6]]

^<<v2-31-6,6>>^ Eis que lhe dei por companheiro Aoliabe, filho de Aisamaque, da tribo de Dã; e dei habilidade a todos os homens hábeis, para que me façam tudo o que tenho ordenado:

[[v2-31-7]]

^<<v2-31-7,7>>^ a tenda da congregação, e a arca do Testemunho, e o propiciatório que está por cima dela, e todos os pertences da tenda;

[[v2-31-8]]

^<<v2-31-8,8>>^ e a mesa com os seus utensílios, e o candelabro de ouro puro com todos os seus utensílios, e o altar do incenso;

[[v2-31-9]]

^<<v2-31-9,9>>^ e o altar do holocausto com todos os seus utensílios e a bacia com seu suporte;

[[v2-31-10]]

^<<v2-31-10,10>>^ e as vestes finamente tecidas, e as vestes sagradas do sacerdote Arão, e as vestes de seus filhos, para oficiarem como sacerdotes;

[[v2-31-11]]

^<<v2-31-11,11>>^ e o óleo da unção e o incenso aromático para o santuário; eles farão tudo segundo tenho ordenado.

[[v2-31-12]]

^<<v2-31-12,12>>^ Disse mais o SENHOR a Moisés:

[[v2-31-13]]

^<<v2-31-13,13>>^ Tu, pois, falarás aos filhos de Israel e lhes dirás: Certamente, guardareis os meus sábados; pois é sinal entre mim e vós nas vossas gerações; para que saibais que eu sou o SENHOR, que vos santifica.

[[v2-31-14]]

^<<v2-31-14,14>>^ Portanto, guardareis o sábado, porque é santo para vós outros; aquele que o profanar morrerá; pois qualquer que nele fizer alguma obra será eliminado do meio do seu povo.

[[v2-31-15]]

^<<v2-31-15,15>>^ Seis dias se trabalhará, porém o sétimo dia é o sábado do repouso solene, santo ao SENHOR; qualquer que no dia do sábado fizer alguma obra morrerá.

[[v2-31-16]]

^<<v2-31-16,16>>^ Pelo que os filhos de Israel guardarão o sábado, celebrando-o por aliança perpétua nas suas gerações.

[[v2-31-17]]

^<<v2-31-17,17>>^ Entre mim e os filhos de Israel é sinal para sempre; porque, em seis dias, fez o SENHOR os céus e a terra, e, ao sétimo dia, descansou, e tomou alento.

[[v2-31-18]]

^<<v2-31-18,18>>^ E, tendo acabado de falar com ele no monte Sinai, deu a Moisés as duas tábuas do Testemunho, tábuas de pedra, escritas pelo dedo de Deus.

'''

xref:002-exodo/002-exodo-030.adoc#v2-30-0[&#60; Capítulo Anterior] | <<v2-31-0,Topo>> | xref:002-exodo/002-exodo-032.adoc#v2-32-0[Próximo Capítulo &#62;]