include::./index.adoc[]

[[v2-30-0]]
=== Êxodo, 30
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-30-1]]

^<<v2-30-1,1>>^ Farás também um altar para queimares nele o incenso; de madeira de acácia o farás.

[[v2-30-2]]

^<<v2-30-2,2>>^ Terá um côvado de comprimento, e um de largura (será quadrado), e dois de altura; os chifres formarão uma só peça com ele.

[[v2-30-3]]

^<<v2-30-3,3>>^ De ouro puro o cobrirás, a parte superior, as paredes ao redor e os chifres; e lhe farás uma bordadura de ouro ao redor.

[[v2-30-4]]

^<<v2-30-4,4>>^ Também lhe farás duas argolas de ouro debaixo da bordadura; de ambos os lados as farás; nelas, se meterão os varais para se levar o altar.

[[v2-30-5]]

^<<v2-30-5,5>>^ De madeira de acácia farás os varais e os cobrirás de ouro.

[[v2-30-6]]

^<<v2-30-6,6>>^ Porás o altar defronte do véu que está diante da arca do Testemunho, diante do propiciatório que está sobre o Testemunho, onde me avistarei contigo.

[[v2-30-7]]

^<<v2-30-7,7>>^ Arão queimará sobre ele o incenso aromático; cada manhã, quando preparar as lâmpadas, o queimará.

[[v2-30-8]]

^<<v2-30-8,8>>^ Quando, ao crepúsculo da tarde, acender as lâmpadas, o queimará; será incenso contínuo perante o SENHOR, pelas vossas gerações.

[[v2-30-9]]

^<<v2-30-9,9>>^ Não oferecereis sobre ele incenso estranho, nem holocausto, nem ofertas de manjares; nem tampouco derramareis libações sobre ele.

[[v2-30-10]]

^<<v2-30-10,10>>^ Uma vez no ano, Arão fará expiação sobre os chifres do altar com o sangue da oferta pelo pecado; uma vez no ano, fará expiação sobre ele, pelas vossas gerações; santíssimo é ao SENHOR.

[[v2-30-11]]

^<<v2-30-11,11>>^ Disse mais o SENHOR a Moisés:

[[v2-30-12]]

^<<v2-30-12,12>>^ Quando fizeres recenseamento dos filhos de Israel, cada um deles dará ao SENHOR o resgate de si próprio, quando os contares; para que não haja entre eles praga nenhuma, quando os arrolares.

[[v2-30-13]]

^<<v2-30-13,13>>^ Todo aquele que passar ao arrolamento dará isto: metade de um siclo, segundo o siclo do santuário (este siclo é de vinte geras); a metade de um siclo é a oferta ao SENHOR.

[[v2-30-14]]

^<<v2-30-14,14>>^ Qualquer que entrar no arrolamento, de vinte anos para cima, dará a oferta ao SENHOR.

[[v2-30-15]]

^<<v2-30-15,15>>^ O rico não dará mais de meio siclo, nem o pobre, menos, quando derem a oferta ao SENHOR, para fazerdes expiação pela vossa alma.

[[v2-30-16]]

^<<v2-30-16,16>>^ Tomarás o dinheiro das expiações dos filhos de Israel e o darás ao serviço da tenda da congregação; e será para memória aos filhos de Israel diante do SENHOR, para fazerdes expiação pela vossa alma.

[[v2-30-17]]

^<<v2-30-17,17>>^ Disse mais o SENHOR a Moisés:

[[v2-30-18]]

^<<v2-30-18,18>>^ Farás também uma bacia de bronze com o seu suporte de bronze, para lavar. Pô-la-ás entre a tenda da congregação e o altar e deitarás água nela.

[[v2-30-19]]

^<<v2-30-19,19>>^ Nela, Arão e seus filhos lavarão as mãos e os pés.

[[v2-30-20]]

^<<v2-30-20,20>>^ Quando entrarem na tenda da congregação, lavar-se-ão com água, para que não morram; ou quando se chegarem ao altar para ministrar, para acender a oferta queimada ao SENHOR.

[[v2-30-21]]

^<<v2-30-21,21>>^ Lavarão, pois, as mãos e os pés, para que não morram; e isto lhes será por estatuto perpétuo, a ele e à sua posteridade, através de suas gerações.

[[v2-30-22]]

^<<v2-30-22,22>>^ Disse mais o SENHOR a Moisés:

[[v2-30-23]]

^<<v2-30-23,23>>^ Tu, pois, toma das mais excelentes especiarias: de mirra fluida quinhentos siclos, de cinamomo odoroso a metade, a saber, duzentos e cinquenta siclos, e de cálamo aromático duzentos e cinquenta siclos,

[[v2-30-24]]

^<<v2-30-24,24>>^ e de cássia quinhentos siclos, segundo o siclo do santuário, e de azeite de oliveira um him.

[[v2-30-25]]

^<<v2-30-25,25>>^ Disto farás o óleo sagrado para a unção, o perfume composto segundo a arte do perfumista; este será o óleo sagrado da unção.

[[v2-30-26]]

^<<v2-30-26,26>>^ Com ele ungirás a tenda da congregação, e a arca do Testemunho,

[[v2-30-27]]

^<<v2-30-27,27>>^ e a mesa com todos os seus utensílios, e o candelabro com os seus utensílios, e o altar do incenso,

[[v2-30-28]]

^<<v2-30-28,28>>^ e o altar do holocausto com todos os utensílios, e a bacia com o seu suporte.

[[v2-30-29]]

^<<v2-30-29,29>>^ Assim consagrarás estas coisas, para que sejam santíssimas; tudo o que tocar nelas será santo.

[[v2-30-30]]

^<<v2-30-30,30>>^ Também ungirás Arão e seus filhos e os consagrarás para que me oficiem como sacerdotes.

[[v2-30-31]]

^<<v2-30-31,31>>^ Dirás aos filhos de Israel: Este me será o óleo sagrado da unção nas vossas gerações.

[[v2-30-32]]

^<<v2-30-32,32>>^ Não se ungirá com ele o corpo do homem que não seja sacerdote, nem fareis outro semelhante, da mesma composição; é santo e será santo para vós outros.

[[v2-30-33]]

^<<v2-30-33,33>>^ Qualquer que compuser óleo igual a este ou dele puser sobre um estranho será eliminado do seu povo.

[[v2-30-34]]

^<<v2-30-34,34>>^ Disse mais o SENHOR a Moisés: Toma substâncias odoríferas, estoraque, ônica e gálbano; estes arômatas com incenso puro, cada um de igual peso;

[[v2-30-35]]

^<<v2-30-35,35>>^ e disto farás incenso, perfume segundo a arte do perfumista, temperado com sal, puro e santo.

[[v2-30-36]]

^<<v2-30-36,36>>^ Uma parte dele reduzirás a pó e o porás diante do Testemunho na tenda da congregação, onde me avistarei contigo; será para vós outros santíssimo.

[[v2-30-37]]

^<<v2-30-37,37>>^ Porém o incenso que fareis, segundo a composição deste, não o fareis para vós mesmos; santo será para o SENHOR.

[[v2-30-38]]

^<<v2-30-38,38>>^ Quem fizer tal como este para o cheirar será eliminado do seu povo.

'''

xref:002-exodo/002-exodo-029.adoc#v2-29-0[&#60; Capítulo Anterior] | <<v2-30-0,Topo>> | xref:002-exodo/002-exodo-031.adoc#v2-31-0[Próximo Capítulo &#62;]