include::./index.adoc[]

[[v2-25-0]]
=== Êxodo, 25
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-25-1]]

^<<v2-25-1,1>>^ Disse o SENHOR a Moisés:

[[v2-25-2]]

^<<v2-25-2,2>>^ Fala aos filhos de Israel que me tragam oferta; de todo homem cujo coração o mover para isso, dele recebereis a minha oferta.

[[v2-25-3]]

^<<v2-25-3,3>>^ Esta é a oferta que dele recebereis: ouro, e prata, e bronze,

[[v2-25-4]]

^<<v2-25-4,4>>^ e estofo azul, e púrpura, e carmesim, e linho fino, e pelos de cabra,

[[v2-25-5]]

^<<v2-25-5,5>>^ e peles de carneiro tintas de vermelho, e peles finas, e madeira de acácia,

[[v2-25-6]]

^<<v2-25-6,6>>^ azeite para a luz, especiarias para o óleo de unção e para o incenso aromático,

[[v2-25-7]]

^<<v2-25-7,7>>^ pedras de ônix e pedras de engaste, para a estola sacerdotal e para o peitoral.

[[v2-25-8]]

^<<v2-25-8,8>>^ E me farão um santuário, para que eu possa habitar no meio deles.

[[v2-25-9]]

^<<v2-25-9,9>>^ Segundo tudo o que eu te mostrar para modelo do tabernáculo e para modelo de todos os seus móveis, assim mesmo o fareis.

[[v2-25-10]]

^<<v2-25-10,10>>^ Também farão uma arca de madeira de acácia; de dois côvados e meio será o seu comprimento, de um côvado e meio, a largura, e de um côvado e meio, a altura.

[[v2-25-11]]

^<<v2-25-11,11>>^ De ouro puro a cobrirás; por dentro e por fora a cobrirás e farás sobre ela uma bordadura de ouro ao redor.

[[v2-25-12]]

^<<v2-25-12,12>>^ Fundirás para ela quatro argolas de ouro e as porás nos quatro cantos da arca: duas argolas num lado dela e duas argolas noutro lado.

[[v2-25-13]]

^<<v2-25-13,13>>^ Farás também varais de madeira de acácia e os cobrirás de ouro;

[[v2-25-14]]

^<<v2-25-14,14>>^ meterás os varais nas argolas aos lados da arca, para se levar por meio deles a arca.

[[v2-25-15]]

^<<v2-25-15,15>>^ Os varais ficarão nas argolas da arca e não se tirarão dela.

[[v2-25-16]]

^<<v2-25-16,16>>^ E porás na arca o Testemunho, que eu te darei.

[[v2-25-17]]

^<<v2-25-17,17>>^ Farás também um propiciatório de ouro puro; de dois côvados e meio será o seu comprimento, e a largura, de um côvado e meio.

[[v2-25-18]]

^<<v2-25-18,18>>^ Farás dois querubins de ouro; de ouro batido os farás, nas duas extremidades do propiciatório;

[[v2-25-19]]

^<<v2-25-19,19>>^ um querubim, na extremidade de uma parte, e o outro, na extremidade da outra parte; de uma só peça com o propiciatório fareis os querubins nas duas extremidades dele.

[[v2-25-20]]

^<<v2-25-20,20>>^ Os querubins estenderão as asas por cima, cobrindo com elas o propiciatório; estarão eles de faces voltadas uma para a outra, olhando para o propiciatório.

[[v2-25-21]]

^<<v2-25-21,21>>^ Porás o propiciatório em cima da arca; e dentro dela porás o Testemunho, que eu te darei.

[[v2-25-22]]

^<<v2-25-22,22>>^ Ali, virei a ti e, de cima do propiciatório, do meio dos dois querubins que estão sobre a arca do Testemunho, falarei contigo acerca de tudo o que eu te ordenar para os filhos de Israel.

[[v2-25-23]]

^<<v2-25-23,23>>^ Também farás a mesa de madeira de acácia; terá o comprimento de dois côvados, a largura, de um côvado, e a altura, de um côvado e meio;

[[v2-25-24]]

^<<v2-25-24,24>>^ de ouro puro a cobrirás e lhe farás uma bordadura de ouro ao redor.

[[v2-25-25]]

^<<v2-25-25,25>>^ Também lhe farás moldura ao redor, da largura de quatro dedos, e lhe farás uma bordadura de ouro ao redor da moldura.

[[v2-25-26]]

^<<v2-25-26,26>>^ Também lhe farás quatro argolas de ouro; e porás as argolas nos quatro cantos, que estão nos seus quatro pés.

[[v2-25-27]]

^<<v2-25-27,27>>^ Perto da moldura estarão as argolas, como lugares para os varais, para se levar a mesa.

[[v2-25-28]]

^<<v2-25-28,28>>^ Farás, pois, estes varais de madeira de acácia e os cobrirás de ouro; por meio deles, se levará a mesa.

[[v2-25-29]]

^<<v2-25-29,29>>^ Também farás os seus pratos, e os seus recipientes para incenso, e as suas galhetas, e as suas taças em que se hão de oferecer libações; de ouro puro os farás.

[[v2-25-30]]

^<<v2-25-30,30>>^ Porás sobre a mesa os pães da proposição diante de mim perpetuamente.

[[v2-25-31]]

^<<v2-25-31,31>>^ Farás também um candelabro de ouro puro; de ouro batido se fará este candelabro; o seu pedestal, a sua hástea, os seus cálices, as suas maçanetas e as suas flores formarão com ele uma só peça.

[[v2-25-32]]

^<<v2-25-32,32>>^ Seis hásteas sairão dos seus lados: três de um lado e três do outro.

[[v2-25-33]]

^<<v2-25-33,33>>^ Numa hástea, haverá três cálices com formato de amêndoas, uma maçaneta e uma flor; e três cálices, com formato de amêndoas na outra hástea, uma maçaneta e uma flor; assim serão as seis hásteas que saem do candelabro.

[[v2-25-34]]

^<<v2-25-34,34>>^ Mas no candelabro mesmo haverá quatro cálices com formato de amêndoas, com suas maçanetas e com suas flores.

[[v2-25-35]]

^<<v2-25-35,35>>^ Haverá uma maçaneta sob duas hásteas que saem dele; e ainda uma maçaneta sob duas outras hásteas que saem dele; e ainda mais uma maçaneta sob duas outras hásteas que saem dele; assim se fará com as seis hásteas que saem do candelabro.

[[v2-25-36]]

^<<v2-25-36,36>>^ As suas maçanetas e as suas hásteas serão do mesmo; tudo será de uma só peça, obra batida de ouro puro.

[[v2-25-37]]

^<<v2-25-37,37>>^ Também lhe farás sete lâmpadas, as quais se acenderão para alumiar defronte dele.

[[v2-25-38]]

^<<v2-25-38,38>>^ As suas espevitadeiras e os seus apagadores serão de ouro puro.

[[v2-25-39]]

^<<v2-25-39,39>>^ De um talento de ouro puro se fará o candelabro com todos estes utensílios.

[[v2-25-40]]

^<<v2-25-40,40>>^ Vê, pois, que tudo faças segundo o modelo que te foi mostrado no monte.

'''

xref:002-exodo/002-exodo-024.adoc#v2-24-0[&#60; Capítulo Anterior] | <<v2-25-0,Topo>> | xref:002-exodo/002-exodo-026.adoc#v2-26-0[Próximo Capítulo &#62;]