include::./index.adoc[]

[[v2-32-0]]
=== Êxodo, 32
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-32-1]]

^<<v2-32-1,1>>^ Mas, vendo o povo que Moisés tardava em descer do monte, acercou-se de Arão e lhe disse: Levanta-te, faze-nos deuses que vão adiante de nós; pois, quanto a este Moisés, o homem que nos tirou do Egito, não sabemos o que lhe terá sucedido.

[[v2-32-2]]

^<<v2-32-2,2>>^ Disse-lhes Arão: Tirai as argolas de ouro das orelhas de vossas mulheres, vossos filhos e vossas filhas e trazei-mas.

[[v2-32-3]]

^<<v2-32-3,3>>^ Então, todo o povo tirou das orelhas as argolas e as trouxe a Arão.

[[v2-32-4]]

^<<v2-32-4,4>>^ Este, recebendo-as das suas mãos, trabalhou o ouro com buril e fez dele um bezerro fundido. Então, disseram: São estes, ó Israel, os teus deuses, que te tiraram da terra do Egito.

[[v2-32-5]]

^<<v2-32-5,5>>^ Arão, vendo isso, edificou um altar diante dele e, apregoando, disse: Amanhã, será festa ao SENHOR.

[[v2-32-6]]

^<<v2-32-6,6>>^ No dia seguinte, madrugaram, e ofereceram holocaustos, e trouxeram ofertas pacíficas; e o povo assentou-se para comer e beber e levantou-se para divertir-se.

[[v2-32-7]]

^<<v2-32-7,7>>^ Então, disse o SENHOR a Moisés: Vai, desce; porque o teu povo, que fizeste sair do Egito, se corrompeu

[[v2-32-8]]

^<<v2-32-8,8>>^ e depressa se desviou do caminho que lhe havia eu ordenado; fez para si um bezerro fundido, e o adorou, e lhe sacrificou, e diz: São estes, ó Israel, os teus deuses, que te tiraram da terra do Egito.

[[v2-32-9]]

^<<v2-32-9,9>>^ Disse mais o SENHOR a Moisés: Tenho visto este povo, e eis que é povo de dura cerviz.

[[v2-32-10]]

^<<v2-32-10,10>>^ Agora, pois, deixa-me, para que se acenda contra eles o meu furor, e eu os consuma; e de ti farei uma grande nação.

[[v2-32-11]]

^<<v2-32-11,11>>^ Porém Moisés suplicou ao SENHOR, seu Deus, e disse: Por que se acende, SENHOR, a tua ira contra o teu povo, que tiraste da terra do Egito com grande fortaleza e poderosa mão?

[[v2-32-12]]

^<<v2-32-12,12>>^ Por que hão de dizer os egípcios: Com maus intentos os tirou, para matá-los nos montes e para consumi-los da face da terra? Torna-te do furor da tua ira e arrepende-te deste mal contra o teu povo.

[[v2-32-13]]

^<<v2-32-13,13>>^ Lembra-te de Abraão, de Isaque e de Israel, teus servos, aos quais por ti mesmo tens jurado e lhes disseste: Multiplicarei a vossa descendência como as estrelas do céu, e toda esta terra de que tenho falado, dá-la-ei à vossa descendência, para que a possuam por herança eternamente.

[[v2-32-14]]

^<<v2-32-14,14>>^ Então, se arrependeu o SENHOR do mal que dissera havia de fazer ao povo.

[[v2-32-15]]

^<<v2-32-15,15>>^ E, voltando-se, desceu Moisés do monte com as duas tábuas do Testemunho nas mãos, tábuas escritas de ambos os lados; de um e de outro lado estavam escritas.

[[v2-32-16]]

^<<v2-32-16,16>>^ As tábuas eram obra de Deus; também a escritura era a mesma escritura de Deus, esculpida nas tábuas.

[[v2-32-17]]

^<<v2-32-17,17>>^ Ouvindo Josué a voz do povo que gritava, disse a Moisés: Há alarido de guerra no arraial.

[[v2-32-18]]

^<<v2-32-18,18>>^ Respondeu-lhe Moisés: Não é alarido dos vencedores nem alarido dos vencidos, mas alarido dos que cantam é o que ouço.

[[v2-32-19]]

^<<v2-32-19,19>>^ Logo que se aproximou do arraial, viu ele o bezerro e as danças; então, acendendo-se-lhe a ira, arrojou das mãos as tábuas e quebrou-as ao pé do monte;

[[v2-32-20]]

^<<v2-32-20,20>>^ e, pegando no bezerro que tinham feito, queimou-o, e o reduziu a pó, que espalhou sobre a água, e deu de beber aos filhos de Israel.

[[v2-32-21]]

^<<v2-32-21,21>>^ Depois, perguntou Moisés a Arão: Que te fez este povo, que trouxeste sobre ele tamanho pecado?

[[v2-32-22]]

^<<v2-32-22,22>>^ Respondeu-lhe Arão: Não se acenda a ira do meu senhor; tu sabes que o povo é propenso para o mal.

[[v2-32-23]]

^<<v2-32-23,23>>^ Pois me disseram: Faze-nos deuses que vão adiante de nós; pois, quanto a este Moisés, o homem que nos tirou da terra do Egito, não sabemos o que lhe terá acontecido.

[[v2-32-24]]

^<<v2-32-24,24>>^ Então, eu lhes disse: quem tem ouro, tire-o. Deram-mo; e eu o lancei no fogo, e saiu este bezerro.

[[v2-32-25]]

^<<v2-32-25,25>>^ Vendo Moisés que o povo estava desenfreado, pois Arão o deixara à solta para vergonha no meio dos seus inimigos,

[[v2-32-26]]

^<<v2-32-26,26>>^ pôs-se em pé à entrada do arraial e disse: Quem é do SENHOR venha até mim. Então, se ajuntaram a ele todos os filhos de Levi,

[[v2-32-27]]

^<<v2-32-27,27>>^ aos quais disse: Assim diz o SENHOR, o Deus de Israel: Cada um cinja a espada sobre o lado, passai e tornai a passar pelo arraial de porta em porta, e mate cada um a seu irmão, cada um, a seu amigo, e cada um, a seu vizinho.

[[v2-32-28]]

^<<v2-32-28,28>>^ E fizeram os filhos de Levi segundo a palavra de Moisés; e caíram do povo, naquele dia, uns três mil homens.

[[v2-32-29]]

^<<v2-32-29,29>>^ Pois Moisés dissera: Consagrai-vos, hoje, ao SENHOR; cada um contra o seu filho e contra o seu irmão, para que ele vos conceda, hoje, bênção.

[[v2-32-30]]

^<<v2-32-30,30>>^ No dia seguinte, disse Moisés ao povo: Vós cometestes grande pecado; agora, porém, subirei ao SENHOR e, porventura, farei propiciação pelo vosso pecado.

[[v2-32-31]]

^<<v2-32-31,31>>^ Tornou Moisés ao SENHOR e disse: Ora, o povo cometeu grande pecado, fazendo para si deuses de ouro.

[[v2-32-32]]

^<<v2-32-32,32>>^ Agora, pois, perdoa-lhe o pecado; ou, se não, risca-me, peço-te, do livro que escreveste.

[[v2-32-33]]

^<<v2-32-33,33>>^ Então, disse o SENHOR a Moisés: Riscarei do meu livro todo aquele que pecar contra mim.

[[v2-32-34]]

^<<v2-32-34,34>>^ Vai, pois, agora, e conduze o povo para onde te disse; eis que o meu Anjo irá adiante de ti; porém, no dia da minha visitação, vingarei, neles, o seu pecado.

[[v2-32-35]]

^<<v2-32-35,35>>^ Feriu, pois, o SENHOR ao povo, porque fizeram o bezerro que Arão fabricara.

'''

xref:002-exodo/002-exodo-031.adoc#v2-31-0[&#60; Capítulo Anterior] | <<v2-32-0,Topo>> | xref:002-exodo/002-exodo-033.adoc#v2-33-0[Próximo Capítulo &#62;]