include::./index.adoc[]

[[v2-24-0]]
=== Êxodo, 24
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-24-1]]

^<<v2-24-1,1>>^ Disse também Deus a Moisés: Sobe ao SENHOR, tu, e Arão, e Nadabe, e Abiú, e setenta dos anciãos de Israel; e adorai de longe.

[[v2-24-2]]

^<<v2-24-2,2>>^ Só Moisés se chegará ao SENHOR; os outros não se chegarão, nem o povo subirá com ele.

[[v2-24-3]]

^<<v2-24-3,3>>^ Veio, pois, Moisés e referiu ao povo todas as palavras do SENHOR e todos os estatutos; então, todo o povo respondeu a uma voz e disse: Tudo o que falou o SENHOR faremos.

[[v2-24-4]]

^<<v2-24-4,4>>^ Moisés escreveu todas as palavras do SENHOR e, tendo-se levantado pela manhã de madrugada, erigiu um altar ao pé do monte e doze colunas, segundo as doze tribos de Israel.

[[v2-24-5]]

^<<v2-24-5,5>>^ E enviou alguns jovens dos filhos de Israel, os quais ofereceram ao SENHOR holocaustos e sacrifícios pacíficos de novilhos.

[[v2-24-6]]

^<<v2-24-6,6>>^ Moisés tomou metade do sangue e o pôs em bacias; e a outra metade aspergiu sobre o altar.

[[v2-24-7]]

^<<v2-24-7,7>>^ E tomou o livro da aliança e o leu ao povo; e eles disseram: Tudo o que falou o SENHOR faremos e obedeceremos.

[[v2-24-8]]

^<<v2-24-8,8>>^ Então, tomou Moisés aquele sangue, e o aspergiu sobre o povo, e disse: Eis aqui o sangue da aliança que o SENHOR fez convosco a respeito de todas estas palavras.

[[v2-24-9]]

^<<v2-24-9,9>>^ E subiram Moisés, e Arão, e Nadabe, e Abiú, e setenta dos anciãos de Israel.

[[v2-24-10]]

^<<v2-24-10,10>>^ E viram o Deus de Israel, sob cujos pés havia uma como pavimentação de pedra de safira, que se parecia com o céu na sua claridade.

[[v2-24-11]]

^<<v2-24-11,11>>^ Ele não estendeu a mão sobre os escolhidos dos filhos de Israel; porém eles viram a Deus, e comeram, e beberam.

[[v2-24-12]]

^<<v2-24-12,12>>^ Então, disse o SENHOR a Moisés: Sobe a mim, ao monte, e fica lá; dar-te-ei tábuas de pedra, e a lei, e os mandamentos que escrevi, para os ensinares.

[[v2-24-13]]

^<<v2-24-13,13>>^ Levantou-se Moisés com Josué, seu servidor; e, subindo Moisés ao monte de Deus,

[[v2-24-14]]

^<<v2-24-14,14>>^ disse aos anciãos: Esperai-nos aqui até que voltemos a vós outros. Eis que Arão e Hur ficam convosco; quem tiver alguma questão se chegará a eles.

[[v2-24-15]]

^<<v2-24-15,15>>^ Tendo Moisés subido, uma nuvem cobriu o monte.

[[v2-24-16]]

^<<v2-24-16,16>>^ E a glória do SENHOR pousou sobre o monte Sinai, e a nuvem o cobriu por seis dias; ao sétimo dia, do meio da nuvem chamou o SENHOR a Moisés.

[[v2-24-17]]

^<<v2-24-17,17>>^ O aspecto da glória do SENHOR era como um fogo consumidor no cimo do monte, aos olhos dos filhos de Israel.

[[v2-24-18]]

^<<v2-24-18,18>>^ E Moisés, entrando pelo meio da nuvem, subiu ao monte; e lá permaneceu quarenta dias e quarenta noites.

'''

xref:002-exodo/002-exodo-023.adoc#v2-23-0[&#60; Capítulo Anterior] | <<v2-24-0,Topo>> | xref:002-exodo/002-exodo-025.adoc#v2-25-0[Próximo Capítulo &#62;]