include::./index.adoc[]

[[v2-37-0]]
=== Êxodo, 37
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-37-1]]

^<<v2-37-1,1>>^ Fez também Bezalel a arca de madeira de acácia; de dois côvados e meio era o seu comprimento, de um côvado e meio, a largura, e, de um côvado e meio, a altura.

[[v2-37-2]]

^<<v2-37-2,2>>^ De ouro puro a cobriu; por dentro e por fora a cobriu e fez uma bordadura de ouro ao redor.

[[v2-37-3]]

^<<v2-37-3,3>>^ Fundiu para ela quatro argolas de ouro e as pôs nos quatro cantos da arca: duas argolas num lado dela e duas argolas noutro lado.

[[v2-37-4]]

^<<v2-37-4,4>>^ Fez também varais de madeira de acácia e os cobriu de ouro;

[[v2-37-5]]

^<<v2-37-5,5>>^ meteu os varais nas argolas aos lados da arca, para se levar por meio deles a arca.

[[v2-37-6]]

^<<v2-37-6,6>>^ Fez também o propiciatório de ouro puro; de dois côvados e meio era o seu comprimento, e a largura, de um côvado e meio.

[[v2-37-7]]

^<<v2-37-7,7>>^ Fez também dois querubins de ouro; de ouro batido os fez, nas duas extremidades do propiciatório.

[[v2-37-8]]

^<<v2-37-8,8>>^ Um querubim, na extremidade de uma parte, e o outro, na extremidade da outra parte; de uma só peça com o propiciatório fez os querubins nas duas extremidades dele.

[[v2-37-9]]

^<<v2-37-9,9>>^ Os querubins estendiam as asas por cima, cobrindo com elas o propiciatório; estavam eles de faces voltadas uma para a outra, olhando para o propiciatório.

[[v2-37-10]]

^<<v2-37-10,10>>^ Fez também a mesa de madeira de acácia; tinha o comprimento de dois côvados, a largura, de um côvado, e a altura, de um côvado e meio.

[[v2-37-11]]

^<<v2-37-11,11>>^ De ouro puro a cobriu e lhe fez uma bordadura de ouro ao redor.

[[v2-37-12]]

^<<v2-37-12,12>>^ Também lhe fez moldura ao redor, na largura de quatro dedos, e lhe fez uma bordadura de ouro ao redor da moldura.

[[v2-37-13]]

^<<v2-37-13,13>>^ Também lhe fundiu quatro argolas de ouro e pôs as argolas nos quatro cantos que estavam nos seus quatro pés.

[[v2-37-14]]

^<<v2-37-14,14>>^ Perto da moldura estavam as argolas, como lugares para os varais, para se levar a mesa.

[[v2-37-15]]

^<<v2-37-15,15>>^ Fez os varais de madeira de acácia e os cobriu de ouro, para se levar a mesa.

[[v2-37-16]]

^<<v2-37-16,16>>^ Também fez de ouro puro os utensílios que haviam de estar sobre a mesa: os seus pratos, e os seus recipientes para incenso, e as suas galhetas, e as suas taças em que se haviam de oferecer libações.

[[v2-37-17]]

^<<v2-37-17,17>>^ Fez também o candelabro de ouro puro; de ouro batido o fez; o seu pedestal, a sua hástea, os seus cálices, as suas maçanetas e as suas flores formavam com ele uma só peça.

[[v2-37-18]]

^<<v2-37-18,18>>^ Seis hásteas saíam dos seus lados; três de um lado e três do outro.

[[v2-37-19]]

^<<v2-37-19,19>>^ Numa hástea havia três cálices com formato de amêndoas, uma maçaneta e uma flor; e três cálices com formato de amêndoas na outra hástea, uma maçaneta e uma flor; assim eram as seis hásteas que saíam do candelabro.

[[v2-37-20]]

^<<v2-37-20,20>>^ Mas no candelabro mesmo havia quatro cálices com formato de amêndoas, com suas maçanetas e com suas flores.

[[v2-37-21]]

^<<v2-37-21,21>>^ Havia uma maçaneta sob duas hásteas que saíam dele; e ainda uma maçaneta sob duas outras hásteas que saíam dele; e ainda mais uma maçaneta sob duas outras hásteas que saíam dele; assim se fez com as seis hásteas que saíam do candelabro.

[[v2-37-22]]

^<<v2-37-22,22>>^ As suas maçanetas e as suas hásteas eram do mesmo; tudo era de uma só peça, obra batida de ouro puro.

[[v2-37-23]]

^<<v2-37-23,23>>^ Também lhe fez sete lâmpadas; as suas espevitadeiras e os seus apagadores eram de ouro puro.

[[v2-37-24]]

^<<v2-37-24,24>>^ De um talento de ouro puro se fez o candelabro com todos os seus utensílios.

[[v2-37-25]]

^<<v2-37-25,25>>^ Fez de madeira de acácia o altar do incenso; tinha um côvado de comprimento, e um de largura (era quadrado), e dois de altura; os chifres formavam uma só peça com ele.

[[v2-37-26]]

^<<v2-37-26,26>>^ De ouro puro o cobriu, a parte superior, as paredes ao redor e os chifres; e lhe fez uma bordadura de ouro ao redor.

[[v2-37-27]]

^<<v2-37-27,27>>^ Também lhe fez duas argolas de ouro debaixo da bordadura, de ambos os lados as fez; nelas, se meteram os varais para se levar o altar;

[[v2-37-28]]

^<<v2-37-28,28>>^ de madeira de acácia fez os varais e os cobriu de ouro.

[[v2-37-29]]

^<<v2-37-29,29>>^ Fez também o óleo santo da unção e o incenso aromático, puro, de obra de perfumista.

'''

xref:002-exodo/002-exodo-036.adoc#v2-36-0[&#60; Capítulo Anterior] | <<v2-37-0,Topo>> | xref:002-exodo/002-exodo-038.adoc#v2-38-0[Próximo Capítulo &#62;]