include::./index.adoc[]

[[v2-3-0]]
=== Êxodo, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-3-1]]

^<<v2-3-1,1>>^ Apascentava Moisés o rebanho de Jetro, seu sogro, sacerdote de Midiã; e, levando o rebanho para o lado ocidental do deserto, chegou ao monte de Deus, a Horebe.

[[v2-3-2]]

^<<v2-3-2,2>>^ Apareceu-lhe o Anjo do SENHOR numa chama de fogo, no meio de uma sarça; Moisés olhou, e eis que a sarça ardia no fogo e a sarça não se consumia.

[[v2-3-3]]

^<<v2-3-3,3>>^ Então, disse consigo mesmo: Irei para lá e verei essa grande maravilha; por que a sarça não se queima?

[[v2-3-4]]

^<<v2-3-4,4>>^ Vendo o SENHOR que ele se voltava para ver, Deus, do meio da sarça, o chamou e disse: Moisés! Moisés! Ele respondeu: Eis-me aqui!

[[v2-3-5]]

^<<v2-3-5,5>>^ Deus continuou: Não te chegues para cá; tira as sandálias dos pés, porque o lugar em que estás é terra santa.

[[v2-3-6]]

^<<v2-3-6,6>>^ Disse mais: Eu sou o Deus de teu pai, o Deus de Abraão, o Deus de Isaque e o Deus de Jacó. Moisés escondeu o rosto, porque temeu olhar para Deus.

[[v2-3-7]]

^<<v2-3-7,7>>^ Disse ainda o SENHOR: Certamente, vi a aflição do meu povo, que está no Egito, e ouvi o seu clamor por causa dos seus exatores. Conheço-lhe o sofrimento;

[[v2-3-8]]

^<<v2-3-8,8>>^ por isso, desci a fim de livrá-lo da mão dos egípcios e para fazê-lo subir daquela terra a uma terra boa e ampla, terra que mana leite e mel; o lugar do cananeu, do heteu, do amorreu, do ferezeu, do heveu e do jebuseu.

[[v2-3-9]]

^<<v2-3-9,9>>^ Pois o clamor dos filhos de Israel chegou até mim, e também vejo a opressão com que os egípcios os estão oprimindo.

[[v2-3-10]]

^<<v2-3-10,10>>^ Vem, agora, e eu te enviarei a Faraó, para que tires o meu povo, os filhos de Israel, do Egito.

[[v2-3-11]]

^<<v2-3-11,11>>^ Então, disse Moisés a Deus: Quem sou eu para ir a Faraó e tirar do Egito os filhos de Israel?

[[v2-3-12]]

^<<v2-3-12,12>>^ Deus lhe respondeu: Eu serei contigo; e este será o sinal de que eu te enviei: depois de haveres tirado o povo do Egito, servireis a Deus neste monte.

[[v2-3-13]]

^<<v2-3-13,13>>^ Disse Moisés a Deus: Eis que, quando eu vier aos filhos de Israel e lhes disser: O Deus de vossos pais me enviou a vós outros; e eles me perguntarem: Qual é o seu nome? Que lhes direi?

[[v2-3-14]]

^<<v2-3-14,14>>^ Disse Deus a Moisés: Eu Sou o Que Sou . Disse mais: Assim dirás aos filhos de Israel: Eu Sou  me enviou a vós outros.

[[v2-3-15]]

^<<v2-3-15,15>>^ Disse Deus ainda mais a Moisés: Assim dirás aos filhos de Israel: O SENHOR, o Deus de vossos pais, o Deus de Abraão, o Deus de Isaque e o Deus de Jacó, me enviou a vós outros; este é o meu nome eternamente, e assim serei lembrado de geração em geração.

[[v2-3-16]]

^<<v2-3-16,16>>^ Vai, ajunta os anciãos de Israel e dize-lhes: O SENHOR, o Deus de vossos pais, o Deus de Abraão, o Deus de Isaque e o Deus de Jacó, me apareceu, dizendo: Em verdade vos tenho visitado e visto o que vos tem sido feito no Egito.

[[v2-3-17]]

^<<v2-3-17,17>>^ Portanto, disse eu: Far-vos-ei subir da aflição do Egito para a terra do cananeu, do heteu, do amorreu, do ferezeu, do heveu e do jebuseu, para uma terra que mana leite e mel.

[[v2-3-18]]

^<<v2-3-18,18>>^ E ouvirão a tua voz; e irás, com os anciãos de Israel, ao rei do Egito e lhe dirás: O SENHOR, o Deus dos hebreus, nos encontrou. Agora, pois, deixa-nos ir caminho de três dias para o deserto, a fim de que sacrifiquemos ao SENHOR, nosso Deus.

[[v2-3-19]]

^<<v2-3-19,19>>^ Eu sei, porém, que o rei do Egito não vos deixará ir se não for obrigado por mão forte.

[[v2-3-20]]

^<<v2-3-20,20>>^ Portanto, estenderei a mão e ferirei o Egito com todos os meus prodígios que farei no meio dele; depois, vos deixará ir.

[[v2-3-21]]

^<<v2-3-21,21>>^ Eu darei mercê a este povo aos olhos dos egípcios; e, quando sairdes, não será de mãos vazias.

[[v2-3-22]]

^<<v2-3-22,22>>^ Cada mulher pedirá à sua vizinha e à sua hóspeda joias de prata, e joias de ouro, e vestimentas; as quais poreis sobre vossos filhos e sobre vossas filhas; e despojareis os egípcios.

'''

xref:002-exodo/002-exodo-002.adoc#v2-2-0[&#60; Capítulo Anterior] | <<v2-3-0,Topo>> | xref:002-exodo/002-exodo-004.adoc#v2-4-0[Próximo Capítulo &#62;]