include::./index.adoc[]

[[v2-21-0]]
=== Êxodo, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-21-1]]

^<<v2-21-1,1>>^ São estes os estatutos que lhes proporás:

[[v2-21-2]]

^<<v2-21-2,2>>^ Se comprares um escravo hebreu, seis anos servirá; mas, ao sétimo, sairá forro, de graça.

[[v2-21-3]]

^<<v2-21-3,3>>^ Se entrou solteiro, sozinho sairá; se era homem casado, com ele sairá sua mulher.

[[v2-21-4]]

^<<v2-21-4,4>>^ Se o seu senhor lhe der mulher, e ela der à luz filhos e filhas, a mulher e seus filhos serão do seu senhor, e ele sairá sozinho.

[[v2-21-5]]

^<<v2-21-5,5>>^ Porém, se o escravo expressamente disser: Eu amo meu senhor, minha mulher e meus filhos, não quero sair forro.

[[v2-21-6]]

^<<v2-21-6,6>>^ Então, o seu senhor o levará aos juízes, e o fará chegar à porta ou à ombreira, e o seu senhor lhe furará a orelha com uma sovela; e ele o servirá para sempre.

[[v2-21-7]]

^<<v2-21-7,7>>^ Se um homem vender sua filha para ser escrava, esta não lhe sairá como saem os escravos.

[[v2-21-8]]

^<<v2-21-8,8>>^ Se ela não agradar ao seu senhor, que se comprometeu a desposá-la, ele terá de permitir-lhe o resgate; não poderá vendê-la a um povo estranho, pois será isso deslealdade para com ela.

[[v2-21-9]]

^<<v2-21-9,9>>^ Mas, se a casar com seu filho, tratá-la-á como se tratam as filhas.

[[v2-21-10]]

^<<v2-21-10,10>>^ Se ele der ao filho outra mulher, não diminuirá o mantimento da primeira, nem os seus vestidos, nem os seus direitos conjugais.

[[v2-21-11]]

^<<v2-21-11,11>>^ Se não lhe fizer estas três coisas, ela sairá sem retribuição, nem pagamento em dinheiro.

[[v2-21-12]]

^<<v2-21-12,12>>^ Quem ferir a outro, de modo que este morra, também será morto.

[[v2-21-13]]

^<<v2-21-13,13>>^ Porém, se não lhe armou ciladas, mas Deus lhe permitiu caísse em suas mãos, então, te designarei um lugar para onde ele fugirá.

[[v2-21-14]]

^<<v2-21-14,14>>^ Se alguém vier maliciosamente contra o próximo, matando-o à traição, tirá-lo-ás até mesmo do meu altar, para que morra.

[[v2-21-15]]

^<<v2-21-15,15>>^ Quem ferir seu pai ou sua mãe será morto.

[[v2-21-16]]

^<<v2-21-16,16>>^ O que raptar alguém e o vender, ou for achado na sua mão, será morto.

[[v2-21-17]]

^<<v2-21-17,17>>^ Quem amaldiçoar seu pai ou sua mãe será morto.

[[v2-21-18]]

^<<v2-21-18,18>>^ Se dois brigarem, ferindo um ao outro com pedra ou com o punho, e o ferido não morrer, mas cair de cama;

[[v2-21-19]]

^<<v2-21-19,19>>^ se ele tornar a levantar-se e andar fora, apoiado ao seu bordão, então, será absolvido aquele que o feriu; somente lhe pagará o tempo que perdeu e o fará curar-se totalmente.

[[v2-21-20]]

^<<v2-21-20,20>>^ Se alguém ferir com bordão o seu escravo ou a sua escrava, e o ferido morrer debaixo da sua mão, será punido;

[[v2-21-21]]

^<<v2-21-21,21>>^ porém, se ele sobreviver por um ou dois dias, não será punido, porque é dinheiro seu.

[[v2-21-22]]

^<<v2-21-22,22>>^ Se homens brigarem, e ferirem mulher grávida, e forem causa de que aborte, porém sem maior dano, aquele que feriu será obrigado a indenizar segundo o que lhe exigir o marido da mulher; e pagará como os juízes lhe determinarem.

[[v2-21-23]]

^<<v2-21-23,23>>^ Mas, se houver dano grave, então, darás vida por vida,

[[v2-21-24]]

^<<v2-21-24,24>>^ olho por olho, dente por dente, mão por mão, pé por pé,

[[v2-21-25]]

^<<v2-21-25,25>>^ queimadura por queimadura, ferimento por ferimento, golpe por golpe.

[[v2-21-26]]

^<<v2-21-26,26>>^ Se alguém ferir o olho do seu escravo ou o olho da sua escrava e o inutilizar, deixá-lo-á ir forro pelo seu olho.

[[v2-21-27]]

^<<v2-21-27,27>>^ E, se com violência fizer cair um dente do seu escravo ou da sua escrava, deixá-lo-á ir forro pelo seu dente.

[[v2-21-28]]

^<<v2-21-28,28>>^ Se algum boi chifrar homem ou mulher, que morra, o boi será apedrejado, e não lhe comerão a carne; mas o dono do boi será absolvido.

[[v2-21-29]]

^<<v2-21-29,29>>^ Mas, se o boi, dantes, era dado a chifrar, e o seu dono era disso conhecedor e não o prendeu, e o boi matar homem ou mulher, o boi será apedrejado, e também será morto o seu dono.

[[v2-21-30]]

^<<v2-21-30,30>>^ Se lhe for exigido resgate, dará, então, como resgate da sua vida tudo o que lhe for exigido.

[[v2-21-31]]

^<<v2-21-31,31>>^ Quer tenha chifrado um filho, quer tenha chifrado uma filha, este julgamento lhe será aplicado.

[[v2-21-32]]

^<<v2-21-32,32>>^ Se o boi chifrar um escravo ou uma escrava, dar-se-ão trinta siclos de prata ao senhor destes, e o boi será apedrejado.

[[v2-21-33]]

^<<v2-21-33,33>>^ Se alguém deixar aberta uma cova ou se alguém cavar uma cova e não a tapar, e nela cair boi ou jumento,

[[v2-21-34]]

^<<v2-21-34,34>>^ o dono da cova o pagará, pagará dinheiro ao seu dono, mas o animal morto será seu.

[[v2-21-35]]

^<<v2-21-35,35>>^ Se um boi de um homem ferir o boi de outro, e o boi ferido morrer, venderão o boi vivo e repartirão o valor; e dividirão entre si o boi morto.

[[v2-21-36]]

^<<v2-21-36,36>>^ Mas, se for notório que o boi era já, dantes, chifrador, e o seu dono não o prendeu, certamente, pagará boi por boi; porém o morto será seu.

'''

xref:002-exodo/002-exodo-020.adoc#v2-20-0[&#60; Capítulo Anterior] | <<v2-21-0,Topo>> | xref:002-exodo/002-exodo-022.adoc#v2-22-0[Próximo Capítulo &#62;]