include::./index.adoc[]

[[v2-16-0]]
=== Êxodo, 16
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-16-1]]

^<<v2-16-1,1>>^ Partiram de Elim, e toda a congregação dos filhos de Israel veio para o deserto de Sim, que está entre Elim e Sinai, aos quinze dias do segundo mês, depois que saíram da terra do Egito.

[[v2-16-2]]

^<<v2-16-2,2>>^ Toda a congregação dos filhos de Israel murmurou contra Moisés e Arão no deserto;

[[v2-16-3]]

^<<v2-16-3,3>>^ disseram-lhes os filhos de Israel: Quem nos dera tivéssemos morrido pela mão do SENHOR, na terra do Egito, quando estávamos sentados junto às panelas de carne e comíamos pão a fartar! Pois nos trouxestes a este deserto, para matardes de fome toda esta multidão.

[[v2-16-4]]

^<<v2-16-4,4>>^ Então, disse o SENHOR a Moisés: Eis que vos farei chover do céu pão, e o povo sairá e colherá diariamente a porção para cada dia, para que eu ponha à prova se anda na minha lei ou não.

[[v2-16-5]]

^<<v2-16-5,5>>^ Dar-se-á que, ao sexto dia, prepararão o que colherem; e será o dobro do que colhem cada dia.

[[v2-16-6]]

^<<v2-16-6,6>>^ Então, disse Moisés e Arão a todos os filhos de Israel: à tarde, sabereis que foi o SENHOR quem vos tirou da terra do Egito,

[[v2-16-7]]

^<<v2-16-7,7>>^ e, pela manhã, vereis a glória do SENHOR, porquanto ouviu as vossas murmurações; pois quem somos nós, para que murmureis contra nós?

[[v2-16-8]]

^<<v2-16-8,8>>^ Prosseguiu Moisés: Será isso quando o SENHOR, à tarde, vos der carne para comer e, pela manhã, pão que vos farte, porquanto o SENHOR ouviu as vossas murmurações, com que vos queixais contra ele; pois quem somos nós? As vossas murmurações não são contra nós, e sim contra o SENHOR.

[[v2-16-9]]

^<<v2-16-9,9>>^ Disse Moisés a Arão: Dize a toda a congregação dos filhos de Israel: Chegai-vos à presença do SENHOR, pois ouviu as vossas murmurações.

[[v2-16-10]]

^<<v2-16-10,10>>^ Quando Arão falava a toda a congregação dos filhos de Israel, olharam para o deserto, e eis que a glória do SENHOR apareceu na nuvem.

[[v2-16-11]]

^<<v2-16-11,11>>^ E o SENHOR disse a Moisés:

[[v2-16-12]]

^<<v2-16-12,12>>^ Tenho ouvido as murmurações dos filhos de Israel; dize-lhes: Ao crepúsculo da tarde, comereis carne, e, pela manhã, vos fartareis de pão, e sabereis que eu sou o SENHOR, vosso Deus.

[[v2-16-13]]

^<<v2-16-13,13>>^ À tarde, subiram codornizes e cobriram o arraial; pela manhã, jazia o orvalho ao redor do arraial.

[[v2-16-14]]

^<<v2-16-14,14>>^ E, quando se evaporou o orvalho que caíra, na superfície do deserto restava uma coisa fina e semelhante a escamas, fina como a geada sobre a terra.

[[v2-16-15]]

^<<v2-16-15,15>>^ Vendo-a os filhos de Israel, disseram uns aos outros: Que é isto? Pois não sabiam o que era. Disse-lhes Moisés: Isto é o pão que o SENHOR vos dá para vosso alimento.

[[v2-16-16]]

^<<v2-16-16,16>>^ Eis o que o SENHOR vos ordenou: Colhei disso cada um segundo o que pode comer, um gômer por cabeça, segundo o número de vossas pessoas; cada um tomará para os que se acharem na sua tenda.

[[v2-16-17]]

^<<v2-16-17,17>>^ Assim o fizeram os filhos de Israel; e colheram, uns, mais, outros, menos.

[[v2-16-18]]

^<<v2-16-18,18>>^ Porém, medindo-o com o gômer, não sobejava ao que colhera muito, nem faltava ao que colhera pouco, pois colheram cada um quanto podia comer.

[[v2-16-19]]

^<<v2-16-19,19>>^ Disse-lhes Moisés: Ninguém deixe dele para a manhã seguinte.

[[v2-16-20]]

^<<v2-16-20,20>>^ Eles, porém, não deram ouvidos a Moisés, e alguns deixaram do maná para a manhã seguinte; porém deu bichos e cheirava mal. E Moisés se indignou contra eles.

[[v2-16-21]]

^<<v2-16-21,21>>^ Colhiam-no, pois, manhã após manhã, cada um quanto podia comer; porque, em vindo o calor, se derretia.

[[v2-16-22]]

^<<v2-16-22,22>>^ Ao sexto dia, colheram pão em dobro, dois gômeres para cada um; e os principais da congregação vieram e contaram-no a Moisés.

[[v2-16-23]]

^<<v2-16-23,23>>^ Respondeu-lhes ele: Isto é o que disse o SENHOR: Amanhã é repouso, o santo sábado do SENHOR; o que quiserdes cozer no forno, cozei-o, e o que quiserdes cozer em água, cozei-o em água; e tudo o que sobrar separai, guardando para a manhã seguinte.

[[v2-16-24]]

^<<v2-16-24,24>>^ E guardaram-no até pela manhã seguinte, como Moisés ordenara; e não cheirou mal, nem deu bichos.

[[v2-16-25]]

^<<v2-16-25,25>>^ Então, disse Moisés: Comei-o hoje, porquanto o sábado é do SENHOR; hoje, não o achareis no campo.

[[v2-16-26]]

^<<v2-16-26,26>>^ Seis dias o colhereis, mas o sétimo dia é o sábado; nele, não haverá.

[[v2-16-27]]

^<<v2-16-27,27>>^ Ao sétimo dia, saíram alguns do povo para o colher, porém não o acharam.

[[v2-16-28]]

^<<v2-16-28,28>>^ Então, disse o SENHOR a Moisés: Até quando recusareis guardar os meus mandamentos e as minhas leis?

[[v2-16-29]]

^<<v2-16-29,29>>^ Considerai que o SENHOR vos deu o sábado; por isso, ele, no sexto dia, vos dá pão para dois dias; cada um fique onde está, ninguém saia do seu lugar no sétimo dia.

[[v2-16-30]]

^<<v2-16-30,30>>^ Assim, descansou o povo no sétimo dia.

[[v2-16-31]]

^<<v2-16-31,31>>^ Deu-lhe a casa de Israel o nome de maná; era como semente de coentro, branco e de sabor como bolos de mel.

[[v2-16-32]]

^<<v2-16-32,32>>^ Disse Moisés: Esta é a palavra que o SENHOR ordenou: Dele encherás um gômer e o guardarás para as vossas gerações, para que vejam o pão com que vos sustentei no deserto, quando vos tirei do Egito.

[[v2-16-33]]

^<<v2-16-33,33>>^ Disse também Moisés a Arão: Toma um vaso, mete nele um gômer cheio de maná e coloca-o diante do SENHOR, para guardar-se às vossas gerações.

[[v2-16-34]]

^<<v2-16-34,34>>^ Como o SENHOR ordenara a Moisés, assim Arão o colocou diante do Testemunho para o guardar.

[[v2-16-35]]

^<<v2-16-35,35>>^ E comeram os filhos de Israel maná quarenta anos, até que entraram em terra habitada; comeram maná até que chegaram aos limites da terra de Canaã.

[[v2-16-36]]

^<<v2-16-36,36>>^ Gômer é a décima parte do efa.

'''

xref:002-exodo/002-exodo-015.adoc#v2-15-0[&#60; Capítulo Anterior] | <<v2-16-0,Topo>> | xref:002-exodo/002-exodo-017.adoc#v2-17-0[Próximo Capítulo &#62;]