include::./index.adoc[]

[[v2-7-0]]
=== Êxodo, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-7-1]]

^<<v2-7-1,1>>^ Então, disse o SENHOR a Moisés: Vê que te constituí como Deus sobre Faraó, e Arão, teu irmão, será teu profeta.

[[v2-7-2]]

^<<v2-7-2,2>>^ Tu falarás tudo o que eu te ordenar; e Arão, teu irmão, falará a Faraó, para que deixe ir da sua terra os filhos de Israel.

[[v2-7-3]]

^<<v2-7-3,3>>^ Eu, porém, endurecerei o coração de Faraó e multiplicarei na terra do Egito os meus sinais e as minhas maravilhas.

[[v2-7-4]]

^<<v2-7-4,4>>^ Faraó não vos ouvirá; e eu porei a mão sobre o Egito e farei sair as minhas hostes, o meu povo, os filhos de Israel, da terra do Egito, com grandes manifestações de julgamento.

[[v2-7-5]]

^<<v2-7-5,5>>^ Saberão os egípcios que eu sou o SENHOR, quando estender eu a mão sobre o Egito e tirar do meio deles os filhos de Israel.

[[v2-7-6]]

^<<v2-7-6,6>>^ Assim fez Moisés e Arão; como o SENHOR lhes ordenara, assim fizeram.

[[v2-7-7]]

^<<v2-7-7,7>>^ Era Moisés de oitenta anos, e Arão, de oitenta e três, quando falaram a Faraó.

[[v2-7-8]]

^<<v2-7-8,8>>^ Falou o SENHOR a Moisés e a Arão:

[[v2-7-9]]

^<<v2-7-9,9>>^ Quando Faraó vos disser: Fazei milagres que vos acreditem, dirás a Arão: Toma o teu bordão e lança-o diante de Faraó; e o bordão se tornará em serpente.

[[v2-7-10]]

^<<v2-7-10,10>>^ Então, Moisés e Arão se chegaram a Faraó e fizeram como o SENHOR lhes ordenara; lançou Arão o seu bordão diante de Faraó e diante dos seus oficiais, e ele se tornou em serpente.

[[v2-7-11]]

^<<v2-7-11,11>>^ Faraó, porém, mandou vir os sábios e encantadores; e eles, os sábios do Egito, fizeram também o mesmo com as suas ciências ocultas.

[[v2-7-12]]

^<<v2-7-12,12>>^ Pois lançaram eles cada um o seu bordão, e eles se tornaram em serpentes; mas o bordão de Arão devorou os bordões deles.

[[v2-7-13]]

^<<v2-7-13,13>>^ Todavia, o coração de Faraó se endureceu, e não os ouviu, como o SENHOR tinha dito.

[[v2-7-14]]

^<<v2-7-14,14>>^ Disse o SENHOR a Moisés: O coração de Faraó está obstinado; recusa deixar ir o povo.

[[v2-7-15]]

^<<v2-7-15,15>>^ Vai ter com Faraó pela manhã; ele sairá às águas; estarás à espera dele na beira do rio, tomarás na mão o bordão que se tornou em serpente

[[v2-7-16]]

^<<v2-7-16,16>>^ e lhe dirás: O SENHOR, o Deus dos hebreus, me enviou a ti para te dizer: Deixa ir o meu povo, para que me sirva no deserto; e, até agora, não tens ouvido.

[[v2-7-17]]

^<<v2-7-17,17>>^ Assim diz o SENHOR: Nisto saberás que eu sou o SENHOR: com este bordão que tenho na mão ferirei as águas do rio, e se tornarão em sangue.

[[v2-7-18]]

^<<v2-7-18,18>>^ Os peixes que estão no rio morrerão, o rio cheirará mal, e os egípcios terão nojo de beber água do rio.

[[v2-7-19]]

^<<v2-7-19,19>>^ Disse mais o SENHOR a Moisés: Dize a Arão: toma o teu bordão e estende a mão sobre as águas do Egito, sobre os seus rios, sobre os seus canais, sobre as suas lagoas e sobre todos os seus reservatórios, para que se tornem em sangue; haja sangue em toda a terra do Egito, tanto nos vasos de madeira como nos de pedra.

[[v2-7-20]]

^<<v2-7-20,20>>^ Fizeram Moisés e Arão como o SENHOR lhes havia ordenado: Arão, levantando o bordão, feriu as águas que estavam no rio, à vista de Faraó e seus oficiais; e toda a água do rio se tornou em sangue.

[[v2-7-21]]

^<<v2-7-21,21>>^ De sorte que os peixes que estavam no rio morreram, o rio cheirou mal, e os egípcios não podiam beber a água do rio; e houve sangue por toda a terra do Egito.

[[v2-7-22]]

^<<v2-7-22,22>>^ Porém os magos do Egito fizeram também o mesmo com as suas ciências ocultas; de maneira que o coração de Faraó se endureceu, e não os ouviu, como o SENHOR tinha dito.

[[v2-7-23]]

^<<v2-7-23,23>>^ Virou-se Faraó e foi para casa; nem ainda isso considerou o seu coração.

[[v2-7-24]]

^<<v2-7-24,24>>^ Todos os egípcios cavaram junto ao rio para encontrar água que beber, pois das águas do rio não podiam beber.

[[v2-7-25]]

^<<v2-7-25,25>>^ Assim se passaram sete dias, depois que o SENHOR feriu o rio.

'''

xref:002-exodo/002-exodo-006.adoc#v2-6-0[&#60; Capítulo Anterior] | <<v2-7-0,Topo>> | xref:002-exodo/002-exodo-008.adoc#v2-8-0[Próximo Capítulo &#62;]