include::./index.adoc[]

[[v2-17-0]]
=== Êxodo, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-17-1]]

^<<v2-17-1,1>>^ Tendo partido toda a congregação dos filhos de Israel do deserto de Sim, fazendo suas paradas, segundo o mandamento do SENHOR, acamparam-se em Refidim; e não havia ali água para o povo beber.

[[v2-17-2]]

^<<v2-17-2,2>>^ Contendeu, pois, o povo com Moisés e disse: Dá-nos água para beber. Respondeu-lhes Moisés: Por que contendeis comigo? Por que tentais ao SENHOR?

[[v2-17-3]]

^<<v2-17-3,3>>^ Tendo aí o povo sede de água, murmurou contra Moisés e disse: Por que nos fizeste subir do Egito, para nos matares de sede, a nós, a nossos filhos e aos nossos rebanhos?

[[v2-17-4]]

^<<v2-17-4,4>>^ Então, clamou Moisés ao SENHOR: Que farei a este povo? Só lhe resta apedrejar-me.

[[v2-17-5]]

^<<v2-17-5,5>>^ Respondeu o SENHOR a Moisés: Passa adiante do povo e toma contigo alguns dos anciãos de Israel, leva contigo em mão o bordão com que feriste o rio e vai.

[[v2-17-6]]

^<<v2-17-6,6>>^ Eis que estarei ali diante de ti sobre a rocha em Horebe; ferirás a rocha, e dela sairá água, e o povo beberá. Moisés assim o fez na presença dos anciãos de Israel.

[[v2-17-7]]

^<<v2-17-7,7>>^ E chamou o nome daquele lugar Massá e Meribá, por causa da contenda dos filhos de Israel e porque tentaram ao SENHOR, dizendo: Está o SENHOR no meio de nós ou não?

[[v2-17-8]]

^<<v2-17-8,8>>^ Então, veio Amaleque e pelejou contra Israel em Refidim.

[[v2-17-9]]

^<<v2-17-9,9>>^ Com isso, ordenou Moisés a Josué: Escolhe-nos homens, e sai, e peleja contra Amaleque; amanhã, estarei eu no cimo do outeiro, e o bordão de Deus estará na minha mão.

[[v2-17-10]]

^<<v2-17-10,10>>^ Fez Josué como Moisés lhe dissera e pelejou contra Amaleque; Moisés, porém, Arão e Hur subiram ao cimo do outeiro.

[[v2-17-11]]

^<<v2-17-11,11>>^ Quando Moisés levantava a mão, Israel prevalecia; quando, porém, ele abaixava a mão, prevalecia Amaleque.

[[v2-17-12]]

^<<v2-17-12,12>>^ Ora, as mãos de Moisés eram pesadas; por isso, tomaram uma pedra e a puseram por baixo dele, e ele nela se assentou; Arão e Hur sustentavam-lhe as mãos, um, de um lado, e o outro, do outro; assim lhe ficaram as mãos firmes até ao pôr do sol.

[[v2-17-13]]

^<<v2-17-13,13>>^ E Josué desbaratou a Amaleque e a seu povo a fio de espada.

[[v2-17-14]]

^<<v2-17-14,14>>^ Então, disse o SENHOR a Moisés: Escreve isto para memória num livro e repete-o a Josué; porque eu hei de riscar totalmente a memória de Amaleque de debaixo do céu.

[[v2-17-15]]

^<<v2-17-15,15>>^ E Moisés edificou um altar e lhe chamou: O SENHOR É Minha Bandeira.

[[v2-17-16]]

^<<v2-17-16,16>>^ E disse: Porquanto o SENHOR jurou, haverá guerra do SENHOR contra Amaleque de geração em geração.

'''

xref:002-exodo/002-exodo-016.adoc#v2-16-0[&#60; Capítulo Anterior] | <<v2-17-0,Topo>> | xref:002-exodo/002-exodo-018.adoc#v2-18-0[Próximo Capítulo &#62;]