include::./index.adoc[]

[[v2-20-0]]
=== Êxodo, 20
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-20-1]]

^<<v2-20-1,1>>^ Então, falou Deus todas estas palavras:

[[v2-20-2]]

^<<v2-20-2,2>>^ Eu sou o SENHOR, teu Deus, que te tirei da terra do Egito, da casa da servidão.

[[v2-20-3]]

^<<v2-20-3,3>>^ Não terás outros deuses diante de mim.

[[v2-20-4]]

^<<v2-20-4,4>>^ Não farás para ti imagem de escultura, nem semelhança alguma do que há em cima nos céus, nem embaixo na terra, nem nas águas debaixo da terra.

[[v2-20-5]]

^<<v2-20-5,5>>^ Não as adorarás, nem lhes darás culto; porque eu sou o SENHOR, teu Deus, Deus zeloso, que visito a iniquidade dos pais nos filhos até à terceira e quarta geração daqueles que me aborrecem

[[v2-20-6]]

^<<v2-20-6,6>>^ e faço misericórdia até mil gerações daqueles que me amam e guardam os meus mandamentos.

[[v2-20-7]]

^<<v2-20-7,7>>^ Não tomarás o nome do SENHOR, teu Deus, em vão, porque o SENHOR não terá por inocente o que tomar o seu nome em vão.

[[v2-20-8]]

^<<v2-20-8,8>>^ Lembra-te do dia de sábado, para o santificar.

[[v2-20-9]]

^<<v2-20-9,9>>^ Seis dias trabalharás e farás toda a tua obra.

[[v2-20-10]]

^<<v2-20-10,10>>^ Mas o sétimo dia é o sábado do SENHOR, teu Deus; não farás nenhum trabalho, nem tu, nem o teu filho, nem a tua filha, nem o teu servo, nem a tua serva, nem o teu animal, nem o forasteiro das tuas portas para dentro;

[[v2-20-11]]

^<<v2-20-11,11>>^ porque, em seis dias, fez o SENHOR os céus e a terra, o mar e tudo o que neles há e, ao sétimo dia, descansou; por isso, o SENHOR abençoou o dia de sábado e o santificou.

[[v2-20-12]]

^<<v2-20-12,12>>^ Honra teu pai e tua mãe, para que se prolonguem os teus dias na terra que o SENHOR, teu Deus, te dá.

[[v2-20-13]]

^<<v2-20-13,13>>^ Não matarás.

[[v2-20-14]]

^<<v2-20-14,14>>^ Não adulterarás.

[[v2-20-15]]

^<<v2-20-15,15>>^ Não furtarás.

[[v2-20-16]]

^<<v2-20-16,16>>^ Não dirás falso testemunho contra o teu próximo.

[[v2-20-17]]

^<<v2-20-17,17>>^ Não cobiçarás a casa do teu próximo. Não cobiçarás a mulher do teu próximo, nem o seu servo, nem a sua serva, nem o seu boi, nem o seu jumento, nem coisa alguma que pertença ao teu próximo.

[[v2-20-18]]

^<<v2-20-18,18>>^ Todo o povo presenciou os trovões, e os relâmpagos, e o clangor da trombeta, e o monte fumegante; e o povo, observando, se estremeceu e ficou de longe.

[[v2-20-19]]

^<<v2-20-19,19>>^ Disseram a Moisés: Fala-nos tu, e te ouviremos; porém não fale Deus conosco, para que não morramos.

[[v2-20-20]]

^<<v2-20-20,20>>^ Respondeu Moisés ao povo: Não temais; Deus veio para vos provar e para que o seu temor esteja diante de vós, a fim de que não pequeis.

[[v2-20-21]]

^<<v2-20-21,21>>^ O povo estava de longe, em pé; Moisés, porém, se chegou à nuvem escura onde Deus estava.

[[v2-20-22]]

^<<v2-20-22,22>>^ Então, disse o SENHOR a Moisés: Assim dirás aos filhos de Israel: Vistes que dos céus eu vos falei.

[[v2-20-23]]

^<<v2-20-23,23>>^ Não fareis deuses de prata ao lado de mim, nem deuses de ouro fareis para vós outros.

[[v2-20-24]]

^<<v2-20-24,24>>^ Um altar de terra me farás e sobre ele sacrificarás os teus holocaustos, as tuas ofertas pacíficas, as tuas ovelhas e os teus bois; em todo lugar onde eu fizer celebrar a memória do meu nome, virei a ti e te abençoarei.

[[v2-20-25]]

^<<v2-20-25,25>>^ Se me levantares um altar de pedras, não o farás de pedras lavradas; pois, se sobre ele manejares a tua ferramenta, profaná-lo-ás.

[[v2-20-26]]

^<<v2-20-26,26>>^ Nem subirás por degrau ao meu altar, para que a tua nudez não seja ali exposta.

'''

xref:002-exodo/002-exodo-019.adoc#v2-19-0[&#60; Capítulo Anterior] | <<v2-20-0,Topo>> | xref:002-exodo/002-exodo-021.adoc#v2-21-0[Próximo Capítulo &#62;]