include::./index.adoc[]

[[v2-26-0]]
=== Êxodo, 26
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-26-1]]

^<<v2-26-1,1>>^ Farás o tabernáculo, que terá dez cortinas, de linho retorcido, estofo azul, púrpura e carmesim; com querubins, as farás de obra de artista.

[[v2-26-2]]

^<<v2-26-2,2>>^ O comprimento de cada cortina será de vinte e oito côvados, e a largura, de quatro côvados; todas as cortinas serão de igual medida.

[[v2-26-3]]

^<<v2-26-3,3>>^ Cinco cortinas serão ligadas umas às outras; e as outras cinco também ligadas umas às outras.

[[v2-26-4]]

^<<v2-26-4,4>>^ Farás laçadas de estofo azul na orla da cortina extrema do primeiro agrupamento; e de igual modo farás na orla da cortina extrema do segundo agrupamento.

[[v2-26-5]]

^<<v2-26-5,5>>^ Cinquenta laçadas farás numa cortina, e cinquenta, na outra cortina no extremo do segundo agrupamento; as laçadas serão contrapostas uma à outra.

[[v2-26-6]]

^<<v2-26-6,6>>^ Farás cinquenta colchetes de ouro, com os quais prenderás as cortinas uma à outra; e o tabernáculo passará a ser um todo.

[[v2-26-7]]

^<<v2-26-7,7>>^ Farás também de pelos de cabra cortinas para servirem de tenda sobre o tabernáculo; onze cortinas farás.

[[v2-26-8]]

^<<v2-26-8,8>>^ O comprimento de cada cortina será de trinta côvados, e a largura, de quatro côvados; as onze cortinas serão de igual medida.

[[v2-26-9]]

^<<v2-26-9,9>>^ Ajuntarás à parte cinco cortinas entre si, e de igual modo as seis restantes, a sexta das quais dobrarás na parte dianteira da tenda.

[[v2-26-10]]

^<<v2-26-10,10>>^ Farás cinquenta laçadas na orla da cortina extrema do primeiro agrupamento e cinquenta laçadas na orla da cortina extrema do segundo agrupamento.

[[v2-26-11]]

^<<v2-26-11,11>>^ Farás também cinquenta colchetes de bronze, e meterás os colchetes nas laçadas, e ajuntarás a tenda, para que venha a ser um todo.

[[v2-26-12]]

^<<v2-26-12,12>>^ A parte que restar das cortinas da tenda, a saber, a meia cortina que sobrar, penderá às costas do tabernáculo.

[[v2-26-13]]

^<<v2-26-13,13>>^ O côvado de um lado e o côvado de outro lado, do que sobejar no comprimento das cortinas da tenda, penderão de um e de outro lado do tabernáculo para o cobrir.

[[v2-26-14]]

^<<v2-26-14,14>>^ Também farás de peles de carneiro tintas de vermelho uma coberta para a tenda e outra coberta de peles finas.

[[v2-26-15]]

^<<v2-26-15,15>>^ Farás também de madeira de acácia as tábuas para o tabernáculo, as quais serão colocadas verticalmente.

[[v2-26-16]]

^<<v2-26-16,16>>^ Cada uma das tábuas terá dez côvados de comprimento e côvado e meio de largura.

[[v2-26-17]]

^<<v2-26-17,17>>^ Cada tábua terá dois encaixes, travados um com o outro; assim farás com todas as tábuas do tabernáculo.

[[v2-26-18]]

^<<v2-26-18,18>>^ No preparar as tábuas para o tabernáculo, farás vinte delas para o lado sul.

[[v2-26-19]]

^<<v2-26-19,19>>^ Farás também quarenta bases de prata debaixo das vinte tábuas: duas bases debaixo de uma tábua para os seus dois encaixes e duas bases debaixo de outra tábua para os seus dois encaixes.

[[v2-26-20]]

^<<v2-26-20,20>>^ Também haverá vinte tábuas ao outro lado do tabernáculo, para o lado norte,

[[v2-26-21]]

^<<v2-26-21,21>>^ com as suas quarenta bases de prata: duas bases debaixo de uma tábua e duas bases debaixo de outra tábua;

[[v2-26-22]]

^<<v2-26-22,22>>^ ao lado posterior do tabernáculo para o ocidente, farás seis tábuas.

[[v2-26-23]]

^<<v2-26-23,23>>^ Farás também duas tábuas para os cantos do tabernáculo, na parte posterior;

[[v2-26-24]]

^<<v2-26-24,24>>^ as quais, por baixo, estarão separadas, mas, em cima, se ajustarão à primeira argola; assim se fará com as duas tábuas; serão duas para cada um dos dois cantos.

[[v2-26-25]]

^<<v2-26-25,25>>^ Assim serão as oito tábuas com as suas bases de prata, dezesseis bases: duas bases debaixo de uma tábua e duas debaixo de outra tábua.

[[v2-26-26]]

^<<v2-26-26,26>>^ Farás travessas de madeira de acácia; cinco para as tábuas de um lado do tabernáculo,

[[v2-26-27]]

^<<v2-26-27,27>>^ cinco para as tábuas do outro lado do tabernáculo e cinco para as tábuas do tabernáculo ao lado posterior que olha para o ocidente.

[[v2-26-28]]

^<<v2-26-28,28>>^ A travessa do meio passará ao meio das tábuas de uma extremidade à outra.

[[v2-26-29]]

^<<v2-26-29,29>>^ Cobrirás de ouro as tábuas e de ouro farás as suas argolas, pelas quais hão de passar as travessas; e cobrirás também de ouro as travessas.

[[v2-26-30]]

^<<v2-26-30,30>>^ Levantarás o tabernáculo segundo o modelo que te foi mostrado no monte.

[[v2-26-31]]

^<<v2-26-31,31>>^ Farás também um véu de estofo azul, e púrpura, e carmesim, e linho fino retorcido; com querubins, o farás de obra de artista.

[[v2-26-32]]

^<<v2-26-32,32>>^ Suspendê-lo-ás sobre quatro colunas de madeira de acácia, cobertas de ouro; os seus colchetes serão de ouro, sobre quatro bases de prata.

[[v2-26-33]]

^<<v2-26-33,33>>^ Pendurarás o véu debaixo dos colchetes e trarás para lá a arca do Testemunho, para dentro do véu; o véu vos fará separação entre o Santo Lugar e o Santo dos Santos.

[[v2-26-34]]

^<<v2-26-34,34>>^ Porás a coberta do propiciatório sobre a arca do Testemunho no Santo dos Santos.

[[v2-26-35]]

^<<v2-26-35,35>>^ A mesa porás fora do véu e o candelabro, defronte da mesa, ao lado do tabernáculo, para o sul; e a mesa porás para o lado norte.

[[v2-26-36]]

^<<v2-26-36,36>>^ Farás também para a porta da tenda um reposteiro de estofo azul, e púrpura, e carmesim, e linho fino retorcido, obra de bordador.

[[v2-26-37]]

^<<v2-26-37,37>>^ Para este reposteiro farás cinco colunas de madeira de acácia e as cobrirás de ouro; os seus colchetes serão de ouro, e para elas fundirás cinco bases de bronze.

'''

xref:002-exodo/002-exodo-025.adoc#v2-25-0[&#60; Capítulo Anterior] | <<v2-26-0,Topo>> | xref:002-exodo/002-exodo-027.adoc#v2-27-0[Próximo Capítulo &#62;]