include::./index.adoc[]

[[v2-14-0]]
=== Êxodo, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-14-1]]

^<<v2-14-1,1>>^ Disse o SENHOR a Moisés:

[[v2-14-2]]

^<<v2-14-2,2>>^ Fala aos filhos de Israel que retrocedam e se acampem defronte de Pi-Hairote, entre Migdol e o mar, diante de Baal-Zefom; em frente dele vos acampareis junto ao mar.

[[v2-14-3]]

^<<v2-14-3,3>>^ Então, Faraó dirá dos filhos de Israel: Estão desorientados na terra, o deserto os encerrou.

[[v2-14-4]]

^<<v2-14-4,4>>^ Endurecerei o coração de Faraó, para que os persiga, e serei glorificado em Faraó e em todo o seu exército; e saberão os egípcios que eu sou o SENHOR. Eles assim o fizeram.

[[v2-14-5]]

^<<v2-14-5,5>>^ Sendo, pois, anunciado ao rei do Egito que o povo fugia, mudou-se o coração de Faraó e dos seus oficiais contra o povo, e disseram: Que é isto que fizemos, permitindo que Israel nos deixasse de servir?

[[v2-14-6]]

^<<v2-14-6,6>>^ E aprontou Faraó o seu carro e tomou consigo o seu povo;

[[v2-14-7]]

^<<v2-14-7,7>>^ e tomou também seiscentos carros escolhidos e todos os carros do Egito com capitães sobre todos eles.

[[v2-14-8]]

^<<v2-14-8,8>>^ Porque o SENHOR endureceu o coração de Faraó, rei do Egito, para que perseguisse os filhos de Israel; porém os filhos de Israel saíram afoitamente.

[[v2-14-9]]

^<<v2-14-9,9>>^ Perseguiram-nos os egípcios, todos os cavalos e carros de Faraó, e os seus cavalarianos, e o seu exército e os alcançaram acampados junto ao mar, perto de Pi-Hairote, defronte de Baal-Zefom.

[[v2-14-10]]

^<<v2-14-10,10>>^ E, chegando Faraó, os filhos de Israel levantaram os olhos, e eis que os egípcios vinham atrás deles, e temeram muito; então, os filhos de Israel clamaram ao SENHOR.

[[v2-14-11]]

^<<v2-14-11,11>>^ Disseram a Moisés: Será, por não haver sepulcros no Egito, que nos tiraste de lá, para que morramos neste deserto? Por que nos trataste assim, fazendo-nos sair do Egito?

[[v2-14-12]]

^<<v2-14-12,12>>^ Não é isso o que te dissemos no Egito: deixa-nos, para que sirvamos os egípcios? Pois melhor nos fora servir aos egípcios do que morrermos no deserto.

[[v2-14-13]]

^<<v2-14-13,13>>^ Moisés, porém, respondeu ao povo: Não temais; aquietai-vos e vede o livramento do SENHOR que, hoje, vos fará; porque os egípcios, que hoje vedes, nunca mais os tornareis a ver.

[[v2-14-14]]

^<<v2-14-14,14>>^ O SENHOR pelejará por vós, e vós vos calareis.

[[v2-14-15]]

^<<v2-14-15,15>>^ Disse o SENHOR a Moisés: Por que clamas a mim? Dize aos filhos de Israel que marchem.

[[v2-14-16]]

^<<v2-14-16,16>>^ E tu, levanta o teu bordão, estende a mão sobre o mar e divide-o, para que os filhos de Israel passem pelo meio do mar em seco.

[[v2-14-17]]

^<<v2-14-17,17>>^ Eis que endurecerei o coração dos egípcios, para que vos sigam e entrem nele; serei glorificado em Faraó e em todo o seu exército, nos seus carros e nos seus cavalarianos;

[[v2-14-18]]

^<<v2-14-18,18>>^ e os egípcios saberão que eu sou o SENHOR, quando for glorificado em Faraó, nos seus carros e nos seus cavalarianos.

[[v2-14-19]]

^<<v2-14-19,19>>^ Então, o Anjo de Deus, que ia adiante do exército de Israel, se retirou e passou para trás deles; também a coluna de nuvem se retirou de diante deles, e se pôs atrás deles,

[[v2-14-20]]

^<<v2-14-20,20>>^ e ia entre o campo dos egípcios e o campo de Israel; a nuvem era escuridade para aqueles e para este esclarecia a noite; de maneira que, em toda a noite, este e aqueles não puderam aproximar-se.

[[v2-14-21]]

^<<v2-14-21,21>>^ Então, Moisés estendeu a mão sobre o mar, e o SENHOR, por um forte vento oriental que soprou toda aquela noite, fez retirar-se o mar, que se tornou terra seca, e as águas foram divididas.

[[v2-14-22]]

^<<v2-14-22,22>>^ Os filhos de Israel entraram pelo meio do mar em seco; e as águas lhes foram qual muro à sua direita e à sua esquerda.

[[v2-14-23]]

^<<v2-14-23,23>>^ Os egípcios que os perseguiam entraram atrás deles, todos os cavalos de Faraó, os seus carros e os seus cavalarianos, até ao meio do mar.

[[v2-14-24]]

^<<v2-14-24,24>>^ Na vigília da manhã, o SENHOR, na coluna de fogo e de nuvem, viu o acampamento dos egípcios e alvorotou o acampamento dos egípcios;

[[v2-14-25]]

^<<v2-14-25,25>>^ emperrou-lhes as rodas dos carros e fê-los andar dificultosamente. Então, disseram os egípcios: Fujamos da presença de Israel, porque o SENHOR peleja por eles contra os egípcios.

[[v2-14-26]]

^<<v2-14-26,26>>^ Disse o SENHOR a Moisés: Estende a mão sobre o mar, para que as águas se voltem sobre os egípcios, sobre os seus carros e sobre os seus cavalarianos.

[[v2-14-27]]

^<<v2-14-27,27>>^ Então, Moisés estendeu a mão sobre o mar, e o mar, ao romper da manhã, retomou a sua força; os egípcios, ao fugirem, foram de encontro a ele, e o SENHOR derribou os egípcios no meio do mar.

[[v2-14-28]]

^<<v2-14-28,28>>^ E, voltando as águas, cobriram os carros e os cavalarianos de todo o exército de Faraó, que os haviam seguido no mar; nem ainda um deles ficou.

[[v2-14-29]]

^<<v2-14-29,29>>^ Mas os filhos de Israel caminhavam a pé enxuto pelo meio do mar; e as águas lhes eram quais muros, à sua direita e à sua esquerda.

[[v2-14-30]]

^<<v2-14-30,30>>^ Assim, o SENHOR livrou Israel, naquele dia, da mão dos egípcios; e Israel viu os egípcios mortos na praia do mar.

[[v2-14-31]]

^<<v2-14-31,31>>^ E viu Israel o grande poder que o SENHOR exercitara contra os egípcios; e o povo temeu ao SENHOR e confiou no SENHOR e em Moisés, seu servo.

'''

xref:002-exodo/002-exodo-013.adoc#v2-13-0[&#60; Capítulo Anterior] | <<v2-14-0,Topo>> | xref:002-exodo/002-exodo-015.adoc#v2-15-0[Próximo Capítulo &#62;]