include::./index.adoc[]

[[v2-8-0]]
=== Êxodo, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-8-1]]

^<<v2-8-1,1>>^ Depois, disse o SENHOR a Moisés: Chega-te a Faraó e dize-lhe: Assim diz o SENHOR: Deixa ir o meu povo, para que me sirva.

[[v2-8-2]]

^<<v2-8-2,2>>^ Se recusares deixá-lo ir, eis que castigarei com rãs todos os teus territórios.

[[v2-8-3]]

^<<v2-8-3,3>>^ O rio produzirá rãs em abundância, que subirão e entrarão em tua casa, e no teu quarto de dormir, e sobre o teu leito, e nas casas dos teus oficiais, e sobre o teu povo, e nos teus fornos, e nas tuas amassadeiras.

[[v2-8-4]]

^<<v2-8-4,4>>^ As rãs virão sobre ti, sobre o teu povo e sobre todos os teus oficiais.

[[v2-8-5]]

^<<v2-8-5,5>>^ Disse mais o SENHOR a Moisés: Dize a Arão: Estende a mão com o teu bordão sobre os rios, sobre os canais e sobre as lagoas e faze subir rãs sobre a terra do Egito.

[[v2-8-6]]

^<<v2-8-6,6>>^ Arão estendeu a mão sobre as águas do Egito, e subiram rãs e cobriram a terra do Egito.

[[v2-8-7]]

^<<v2-8-7,7>>^ Então, os magos fizeram o mesmo com suas ciências ocultas e fizeram aparecer rãs sobre a terra do Egito.

[[v2-8-8]]

^<<v2-8-8,8>>^ Chamou Faraó a Moisés e a Arão e lhes disse: Rogai ao SENHOR que tire as rãs de mim e do meu povo; então, deixarei ir o povo, para que ofereça sacrifícios ao SENHOR.

[[v2-8-9]]

^<<v2-8-9,9>>^ Falou Moisés a Faraó: Digna-te dizer-me quando é que hei de rogar por ti, pelos teus oficiais e pelo teu povo, para que as rãs sejam retiradas de ti e das tuas casas e fiquem somente no rio.

[[v2-8-10]]

^<<v2-8-10,10>>^ Ele respondeu: Amanhã. Moisés disse: Seja conforme a tua palavra, para que saibas que ninguém há como o SENHOR, nosso Deus.

[[v2-8-11]]

^<<v2-8-11,11>>^ Retirar-se-ão as rãs de ti, e das tuas casas, e dos teus oficiais, e do teu povo; ficarão somente no rio.

[[v2-8-12]]

^<<v2-8-12,12>>^ Então, saíram Moisés e Arão da presença de Faraó; e Moisés clamou ao SENHOR por causa das rãs, conforme combinara com Faraó.

[[v2-8-13]]

^<<v2-8-13,13>>^ E o SENHOR fez conforme a palavra de Moisés; morreram as rãs nas casas, nos pátios e nos campos.

[[v2-8-14]]

^<<v2-8-14,14>>^ Ajuntaram-nas em montões e montões, e a terra cheirou mal.

[[v2-8-15]]

^<<v2-8-15,15>>^ Vendo, porém, Faraó que havia alívio, continuou de coração endurecido e não os ouviu, como o SENHOR tinha dito.

[[v2-8-16]]

^<<v2-8-16,16>>^ Disse o SENHOR a Moisés: Dize a Arão: Estende o teu bordão e fere o pó da terra, para que se torne em piolhos por toda a terra do Egito.

[[v2-8-17]]

^<<v2-8-17,17>>^ Fizeram assim; Arão estendeu a mão com seu bordão e feriu o pó da terra, e houve muitos piolhos nos homens e no gado; todo o pó da terra se tornou em piolhos por toda a terra do Egito.

[[v2-8-18]]

^<<v2-8-18,18>>^ E fizeram os magos o mesmo com suas ciências ocultas para produzirem piolhos, porém não o puderam; e havia piolhos nos homens e no gado.

[[v2-8-19]]

^<<v2-8-19,19>>^ Então, disseram os magos a Faraó: Isto é o dedo de Deus. Porém o coração de Faraó se endureceu, e não os ouviu, como o SENHOR tinha dito.

[[v2-8-20]]

^<<v2-8-20,20>>^ Disse o SENHOR a Moisés: Levanta-te pela manhã cedo e apresenta-te a Faraó; eis que ele sairá às águas; e dize-lhe: Assim diz o SENHOR: Deixa ir o meu povo, para que me sirva.

[[v2-8-21]]

^<<v2-8-21,21>>^ Do contrário, se tu não deixares ir o meu povo, eis que eu enviarei enxames de moscas sobre ti, e sobre os teus oficiais, e sobre o teu povo, e nas tuas casas; e as casas dos egípcios se encherão destes enxames, e também a terra em que eles estiverem.

[[v2-8-22]]

^<<v2-8-22,22>>^ Naquele dia, separarei a terra de Gósen, em que habita o meu povo, para que nela não haja enxames de moscas, e saibas que eu sou o SENHOR no meio desta terra.

[[v2-8-23]]

^<<v2-8-23,23>>^ Farei distinção entre o meu povo e o teu povo; amanhã se dará este sinal.

[[v2-8-24]]

^<<v2-8-24,24>>^ Assim fez o SENHOR; e vieram grandes enxames de moscas à casa de Faraó, e às casas dos seus oficiais, e sobre toda a terra do Egito; e a terra ficou arruinada com estes enxames.

[[v2-8-25]]

^<<v2-8-25,25>>^ Chamou Faraó a Moisés e a Arão e disse: Ide, oferecei sacrifícios ao vosso Deus nesta terra.

[[v2-8-26]]

^<<v2-8-26,26>>^ Respondeu Moisés: Não convém que façamos assim porque ofereceríamos ao SENHOR, nosso Deus, sacrifícios abomináveis aos egípcios; eis que, se oferecermos tais sacrifícios perante os seus olhos, não nos apedrejarão eles?

[[v2-8-27]]

^<<v2-8-27,27>>^ Temos de ir caminho de três dias ao deserto e ofereceremos sacrifícios ao SENHOR, nosso Deus, como ele nos disser.

[[v2-8-28]]

^<<v2-8-28,28>>^ Então, disse Faraó: Deixar-vos-ei ir, para que ofereçais sacrifícios ao SENHOR, vosso Deus, no deserto; somente que, saindo, não vades muito longe; orai também por mim.

[[v2-8-29]]

^<<v2-8-29,29>>^ Respondeu-lhe Moisés: Eis que saio da tua presença e orarei ao SENHOR; amanhã, estes enxames de moscas se retirarão de Faraó, dos seus oficiais e do seu povo; somente que Faraó não mais me engane, não deixando ir o povo para que ofereça sacrifícios ao SENHOR.

[[v2-8-30]]

^<<v2-8-30,30>>^ Então, saiu Moisés da presença de Faraó e orou ao SENHOR.

[[v2-8-31]]

^<<v2-8-31,31>>^ E fez o SENHOR conforme a palavra de Moisés, e os enxames de moscas se retiraram de Faraó, dos seus oficiais e do seu povo; não ficou uma só mosca.

[[v2-8-32]]

^<<v2-8-32,32>>^ Mas ainda esta vez endureceu Faraó o coração e não deixou ir o povo.

'''

xref:002-exodo/002-exodo-007.adoc#v2-7-0[&#60; Capítulo Anterior] | <<v2-8-0,Topo>> | xref:002-exodo/002-exodo-009.adoc#v2-9-0[Próximo Capítulo &#62;]