include::./index.adoc[]

[[v2-4-0]]
=== Êxodo, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-4-1]]

^<<v2-4-1,1>>^ Respondeu Moisés: Mas eis que não crerão, nem acudirão à minha voz, pois dirão: O SENHOR não te apareceu.

[[v2-4-2]]

^<<v2-4-2,2>>^ Perguntou-lhe o SENHOR: Que é isso que tens na mão? Respondeu-lhe: Um bordão.

[[v2-4-3]]

^<<v2-4-3,3>>^ Então, lhe disse: Lança-o na terra. Ele o lançou na terra, e o bordão virou uma serpente. E Moisés fugia dela.

[[v2-4-4]]

^<<v2-4-4,4>>^ Disse o SENHOR a Moisés: Estende a mão e pega-lhe pela cauda (estendeu ele a mão, pegou-lhe pela cauda, e ela se tornou em bordão);

[[v2-4-5]]

^<<v2-4-5,5>>^ para que creiam que te apareceu o SENHOR, Deus de seus pais, o Deus de Abraão, o Deus de Isaque e o Deus de Jacó.

[[v2-4-6]]

^<<v2-4-6,6>>^ Disse-lhe mais o SENHOR: Mete, agora, a mão no peito. Ele o fez; e, tirando-a, eis que a mão estava leprosa, branca como a neve.

[[v2-4-7]]

^<<v2-4-7,7>>^ Disse ainda o SENHOR: Torna a meter a mão no peito. Ele a meteu no peito, novamente; e, quando a tirou, eis que se havia tornado como o restante de sua carne.

[[v2-4-8]]

^<<v2-4-8,8>>^ Se eles te não crerem, nem atenderem à evidência do primeiro sinal, talvez crerão na evidência do segundo.

[[v2-4-9]]

^<<v2-4-9,9>>^ Se nem ainda crerem mediante estes dois sinais, nem te ouvirem a voz, tomarás das águas do rio e as derramarás na terra seca; e as águas que do rio tomares tornar-se-ão em sangue sobre a terra.

[[v2-4-10]]

^<<v2-4-10,10>>^ Então, disse Moisés ao SENHOR: Ah! Senhor! Eu nunca fui eloquente, nem outrora, nem depois que falaste a teu servo; pois sou pesado de boca e pesado de língua.

[[v2-4-11]]

^<<v2-4-11,11>>^ Respondeu-lhe o SENHOR: Quem fez a boca do homem? Ou quem faz o mudo, ou o surdo, ou o que vê, ou o cego? Não sou eu, o SENHOR?

[[v2-4-12]]

^<<v2-4-12,12>>^ Vai, pois, agora, e eu serei com a tua boca e te ensinarei o que hás de falar.

[[v2-4-13]]

^<<v2-4-13,13>>^ Ele, porém, respondeu: Ah! Senhor! Envia aquele que hás de enviar, menos a mim.

[[v2-4-14]]

^<<v2-4-14,14>>^ Então, se acendeu a ira do SENHOR contra Moisés, e disse: Não é Arão, o levita, teu irmão? Eu sei que ele fala fluentemente; e eis que ele sai ao teu encontro e, vendo-te, se alegrará em seu coração.

[[v2-4-15]]

^<<v2-4-15,15>>^ Tu, pois, lhe falarás e lhe porás na boca as palavras; eu serei com a tua boca e com a dele e vos ensinarei o que deveis fazer.

[[v2-4-16]]

^<<v2-4-16,16>>^ Ele falará por ti ao povo; ele te será por boca, e tu lhe serás por Deus.

[[v2-4-17]]

^<<v2-4-17,17>>^ Toma, pois, este bordão na mão, com o qual hás de fazer os sinais.

[[v2-4-18]]

^<<v2-4-18,18>>^ Saindo Moisés, voltou para Jetro, seu sogro, e lhe disse: Deixa-me ir, voltar a meus irmãos que estão no Egito para ver se ainda vivem. Disse-lhe Jetro: Vai-te em paz.

[[v2-4-19]]

^<<v2-4-19,19>>^ Disse também o SENHOR a Moisés, em Midiã: Vai, torna para o Egito, porque são mortos todos os que procuravam tirar-te a vida.

[[v2-4-20]]

^<<v2-4-20,20>>^ Tomou, pois, Moisés a sua mulher e os seus filhos; fê-los montar num jumento e voltou para a terra do Egito. Moisés levava na mão o bordão de Deus.

[[v2-4-21]]

^<<v2-4-21,21>>^ Disse o SENHOR a Moisés: Quando voltares ao Egito, vê que faças diante de Faraó todos os milagres que te hei posto na mão; mas eu lhe endurecerei o coração, para que não deixe ir o povo.

[[v2-4-22]]

^<<v2-4-22,22>>^ Dirás a Faraó: Assim diz o SENHOR: Israel é meu filho, meu primogênito.

[[v2-4-23]]

^<<v2-4-23,23>>^ Digo-te, pois: deixa ir meu filho, para que me sirva; mas, se recusares deixá-lo ir, eis que eu matarei teu filho, teu primogênito.

[[v2-4-24]]

^<<v2-4-24,24>>^ Estando Moisés no caminho, numa estalagem, encontrou-o o SENHOR e o quis matar.

[[v2-4-25]]

^<<v2-4-25,25>>^ Então, Zípora tomou uma pedra aguda, cortou o prepúcio de seu filho, lançou-o aos pés de Moisés e lhe disse: Sem dúvida, tu és para mim esposo sanguinário.

[[v2-4-26]]

^<<v2-4-26,26>>^ Assim, o SENHOR o deixou. Ela disse: Esposo sanguinário, por causa da circuncisão.

[[v2-4-27]]

^<<v2-4-27,27>>^ Disse também o SENHOR a Arão: Vai ao deserto para te encontrares com Moisés. Ele foi e, encontrando-o no monte de Deus, o beijou.

[[v2-4-28]]

^<<v2-4-28,28>>^ Relatou Moisés a Arão todas as palavras do SENHOR, com as quais o enviara, e todos os sinais que lhe mandara.

[[v2-4-29]]

^<<v2-4-29,29>>^ Então, se foram Moisés e Arão e ajuntaram todos os anciãos dos filhos de Israel.

[[v2-4-30]]

^<<v2-4-30,30>>^ Arão falou todas as palavras que o SENHOR tinha dito a Moisés, e este fez os sinais à vista do povo.

[[v2-4-31]]

^<<v2-4-31,31>>^ E o povo creu; e, tendo ouvido que o SENHOR havia visitado os filhos de Israel e lhes vira a aflição, inclinaram-se e o adoraram.

'''

xref:002-exodo/002-exodo-003.adoc#v2-3-0[&#60; Capítulo Anterior] | <<v2-4-0,Topo>> | xref:002-exodo/002-exodo-005.adoc#v2-5-0[Próximo Capítulo &#62;]