include::./index.adoc[]

[[v2-22-0]]
=== Êxodo, 22
// ara ?, ARA - Almeida Revista e Atualizada

[[v2-22-1]]

^<<v2-22-1,1>>^ Se alguém furtar boi ou ovelha e o abater ou vender, por um boi pagará cinco bois, e quatro ovelhas por uma ovelha.

[[v2-22-2]]

^<<v2-22-2,2>>^ Se um ladrão for achado arrombando uma casa e, sendo ferido, morrer, quem o feriu não será culpado do sangue.

[[v2-22-3]]

^<<v2-22-3,3>>^ Se, porém, já havia sol quando tal se deu, quem o feriu será culpado do sangue; neste caso, o ladrão fará restituição total. Se não tiver com que pagar, será vendido por seu furto.

[[v2-22-4]]

^<<v2-22-4,4>>^ Se aquilo que roubou for achado vivo em seu poder, seja boi, jumento ou ovelha, pagará o dobro.

[[v2-22-5]]

^<<v2-22-5,5>>^ Se alguém fizer pastar o seu animal num campo ou numa vinha e o largar para comer em campo de outrem, pagará com o melhor do seu próprio campo e o melhor da sua própria vinha.

[[v2-22-6]]

^<<v2-22-6,6>>^ Se irromper fogo, e pegar nos espinheiros, e destruir as medas de cereais, ou a messe, ou o campo, aquele que acendeu o fogo pagará totalmente o queimado.

[[v2-22-7]]

^<<v2-22-7,7>>^ Se alguém der ao seu próximo dinheiro ou objetos a guardar, e isso for furtado àquele que o recebeu, se for achado o ladrão, este pagará o dobro.

[[v2-22-8]]

^<<v2-22-8,8>>^ Se o ladrão não for achado, então, o dono da casa será levado perante os juízes, a ver se não meteu a mão nos bens do próximo.

[[v2-22-9]]

^<<v2-22-9,9>>^ Em todo negócio frauduloso, seja a respeito de boi, ou de jumento, ou de ovelhas, ou de roupas, ou de qualquer coisa perdida, de que uma das partes diz: Esta é a coisa, a causa de ambas as partes se levará perante os juízes; aquele a quem os juízes condenarem pagará o dobro ao seu próximo.

[[v2-22-10]]

^<<v2-22-10,10>>^ Se alguém der ao seu próximo a guardar jumento, ou boi, ou ovelha, ou outro animal qualquer, e este morrer, ou ficar aleijado, ou for afugentado, sem que ninguém o veja,

[[v2-22-11]]

^<<v2-22-11,11>>^ então, haverá juramento do SENHOR entre ambos, de que não meteu a mão nos bens do seu próximo; o dono aceitará o juramento, e o outro não fará restituição.

[[v2-22-12]]

^<<v2-22-12,12>>^ Porém, se, de fato, lhe for furtado, pagá-lo-á ao seu dono.

[[v2-22-13]]

^<<v2-22-13,13>>^ Se for dilacerado, trá-lo-á em testemunho disso e não pagará o dilacerado.

[[v2-22-14]]

^<<v2-22-14,14>>^ Se alguém pedir emprestado a seu próximo um animal, e este ficar aleijado ou morrer, não estando presente o dono, pagá-lo-á.

[[v2-22-15]]

^<<v2-22-15,15>>^ Se o dono esteve presente, não o pagará; se foi alugado, o preço do aluguel será o pagamento.

[[v2-22-16]]

^<<v2-22-16,16>>^ Se alguém seduzir qualquer virgem que não estava desposada e se deitar com ela, pagará seu dote e a tomará por mulher.

[[v2-22-17]]

^<<v2-22-17,17>>^ Se o pai dela definitivamente recusar dar-lha, pagará ele em dinheiro conforme o dote das virgens.

[[v2-22-18]]

^<<v2-22-18,18>>^ A feiticeira não deixarás viver.

[[v2-22-19]]

^<<v2-22-19,19>>^ Quem tiver coito com animal será morto.

[[v2-22-20]]

^<<v2-22-20,20>>^ Quem sacrificar aos deuses e não somente ao SENHOR será destruído.

[[v2-22-21]]

^<<v2-22-21,21>>^ Não afligirás o forasteiro, nem o oprimirás; pois forasteiros fostes na terra do Egito.

[[v2-22-22]]

^<<v2-22-22,22>>^ A nenhuma viúva nem órfão afligireis.

[[v2-22-23]]

^<<v2-22-23,23>>^ Se de algum modo os afligirdes, e eles clamarem a mim, eu lhes ouvirei o clamor;

[[v2-22-24]]

^<<v2-22-24,24>>^ a minha ira se acenderá, e vos matarei à espada; vossas mulheres ficarão viúvas, e vossos filhos, órfãos.

[[v2-22-25]]

^<<v2-22-25,25>>^ Se emprestares dinheiro ao meu povo, ao pobre que está contigo, não te haverás com ele como credor que impõe juros.

[[v2-22-26]]

^<<v2-22-26,26>>^ Se do teu próximo tomares em penhor a sua veste, lha restituirás antes do pôr do sol;

[[v2-22-27]]

^<<v2-22-27,27>>^ porque é com ela que se cobre, é a veste do seu corpo; em que se deitaria? Será, pois, que, quando clamar a mim, eu o ouvirei, porque sou misericordioso.

[[v2-22-28]]

^<<v2-22-28,28>>^ Contra Deus não blasfemarás, nem amaldiçoarás o príncipe do teu povo.

[[v2-22-29]]

^<<v2-22-29,29>>^ Não tardarás em trazer ofertas do melhor das tuas ceifas e das tuas vinhas; o primogênito de teus filhos me darás.

[[v2-22-30]]

^<<v2-22-30,30>>^ Da mesma sorte, farás com os teus bois e com as tuas ovelhas; sete dias ficará a cria com a mãe, e, ao oitavo dia, ma darás.

[[v2-22-31]]

^<<v2-22-31,31>>^ Ser-me-eis homens consagrados; portanto, não comereis carne dilacerada no campo; deitá-la-eis aos cães.

'''

xref:002-exodo/002-exodo-021.adoc#v2-21-0[&#60; Capítulo Anterior] | <<v2-22-0,Topo>> | xref:002-exodo/002-exodo-023.adoc#v2-23-0[Próximo Capítulo &#62;]