include::./index.adoc[]

[[v7-13-0]]
=== Juízes, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v7-13-1]]

^<<v7-13-1,1>>^ Tendo os filhos de Israel tornado a fazer o que era mau perante o SENHOR, este os entregou nas mãos dos filisteus por quarenta anos.

[[v7-13-2]]

^<<v7-13-2,2>>^ Havia um homem de Zorá, da linhagem de Dã, chamado Manoá, cuja mulher era estéril e não tinha filhos.

[[v7-13-3]]

^<<v7-13-3,3>>^ Apareceu o Anjo do SENHOR a esta mulher e lhe disse: Eis que és estéril e nunca tiveste filho; porém conceberás e darás à luz um filho.

[[v7-13-4]]

^<<v7-13-4,4>>^ Agora, pois, guarda-te, não bebas vinho ou bebida forte, nem comas coisa imunda;

[[v7-13-5]]

^<<v7-13-5,5>>^ porque eis que tu conceberás e darás à luz um filho sobre cuja cabeça não passará navalha; porquanto o menino será nazireu consagrado a Deus desde o ventre de sua mãe; e ele começará a livrar a Israel do poder dos filisteus.

[[v7-13-6]]

^<<v7-13-6,6>>^ Então, a mulher foi a seu marido e lhe disse: Um homem de Deus veio a mim; sua aparência era semelhante à de um anjo de Deus, tremenda; não lhe perguntei donde era, nem ele me disse o seu nome.

[[v7-13-7]]

^<<v7-13-7,7>>^ Porém me disse: Eis que tu conceberás e darás à luz um filho; agora, pois, não bebas vinho, nem bebida forte, nem comas coisa imunda; porque o menino será nazireu consagrado a Deus, desde o ventre materno até ao dia de sua morte.

[[v7-13-8]]

^<<v7-13-8,8>>^ Então, Manoá orou ao SENHOR e disse: Ah! Senhor meu, rogo-te que o homem de Deus que enviaste venha outra vez e nos ensine o que devemos fazer ao menino que há de nascer.

[[v7-13-9]]

^<<v7-13-9,9>>^ Deus ouviu a voz de Manoá, e o Anjo de Deus veio outra vez à mulher, quando esta se achava assentada no campo; porém não estava com ela seu marido Manoá.

[[v7-13-10]]

^<<v7-13-10,10>>^ Apressou-se, pois, a mulher, e, correndo, noticiou-o a seu marido, e lhe disse: Eis que me apareceu aquele homem que viera a mim no outro dia.

[[v7-13-11]]

^<<v7-13-11,11>>^ Então, se levantou Manoá, e seguiu a sua mulher, e, tendo chegado ao homem, lhe disse: És tu o que falaste a esta mulher? Ele respondeu: Eu sou.

[[v7-13-12]]

^<<v7-13-12,12>>^ Então, disse Manoá: Quando se cumprirem as tuas palavras, qual será o modo de viver do menino e o seu serviço?

[[v7-13-13]]

^<<v7-13-13,13>>^ Respondeu-lhe o Anjo do SENHOR: Guarde-se a mulher de tudo quanto eu lhe disse.

[[v7-13-14]]

^<<v7-13-14,14>>^ De tudo quanto procede da videira não comerá, nem vinho nem bebida forte beberá, nem coisa imunda comerá; tudo quanto lhe tenho ordenado guardará.

[[v7-13-15]]

^<<v7-13-15,15>>^ Então, Manoá disse ao Anjo do SENHOR: Permite-nos deter-te, e te prepararemos um cabrito.

[[v7-13-16]]

^<<v7-13-16,16>>^ Porém o Anjo do SENHOR disse a Manoá: Ainda que me detenhas, não comerei de teu pão; e, se preparares holocausto, ao SENHOR o oferecerás. Porque não sabia Manoá que era o Anjo do SENHOR.

[[v7-13-17]]

^<<v7-13-17,17>>^ Perguntou Manoá ao Anjo do SENHOR: Qual é o teu nome, para que, quando se cumprir a tua palavra, te honremos?

[[v7-13-18]]

^<<v7-13-18,18>>^ Respondeu-lhe o Anjo do SENHOR e lhe disse: Por que perguntas assim pelo meu nome, que é maravilhoso?

[[v7-13-19]]

^<<v7-13-19,19>>^ Tomou, pois, Manoá um cabrito e uma oferta de manjares e os apresentou sobre uma rocha ao SENHOR; e o Anjo do SENHOR se houve maravilhosamente. Manoá e sua mulher estavam observando.

[[v7-13-20]]

^<<v7-13-20,20>>^ Sucedeu que, subindo para o céu a chama que saiu do altar, o Anjo do SENHOR subiu nela; o que vendo Manoá e sua mulher, caíram com o rosto em terra.

[[v7-13-21]]

^<<v7-13-21,21>>^ Nunca mais apareceu o Anjo do SENHOR a Manoá, nem a sua mulher; então, Manoá ficou sabendo que era o Anjo do SENHOR.

[[v7-13-22]]

^<<v7-13-22,22>>^ Disse Manoá a sua mulher: Certamente, morreremos, porque vimos a Deus.

[[v7-13-23]]

^<<v7-13-23,23>>^ Porém sua mulher lhe disse: Se o SENHOR nos quisera matar, não aceitaria de nossas mãos o holocausto e a oferta de manjares, nem nos teria mostrado tudo isto, nem nos teria revelado tais coisas.

[[v7-13-24]]

^<<v7-13-24,24>>^ Depois, deu a mulher à luz um filho e lhe chamou Sansão; o menino cresceu, e o SENHOR o abençoou.

[[v7-13-25]]

^<<v7-13-25,25>>^ E o Espírito do SENHOR passou a incitá-lo em Maané-Dã, entre Zorá e Estaol.

'''

xref:007-juizes/007-juizes-012.adoc#v7-12-0[&#60; Capítulo Anterior] | <<v7-13-0,Topo>> | xref:007-juizes/007-juizes-014.adoc#v7-14-0[Próximo Capítulo &#62;]