include::./index.adoc[]

[[v7-21-0]]
=== Juízes, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v7-21-1]]

^<<v7-21-1,1>>^ Ora, haviam jurado os homens de Israel em Mispa, dizendo: Nenhum de nós dará sua filha por mulher aos benjamitas.

[[v7-21-2]]

^<<v7-21-2,2>>^ Veio o povo a Betel, e ali ficaram até à tarde diante de Deus, e levantaram a voz, e prantearam com grande pranto.

[[v7-21-3]]

^<<v7-21-3,3>>^ Disseram: Ah! SENHOR, Deus de Israel, por que sucedeu isto em Israel, que, hoje, lhe falte uma tribo?

[[v7-21-4]]

^<<v7-21-4,4>>^ Ao dia seguinte, o povo, pela manhã, se levantou e edificou ali um altar; e apresentaram holocaustos e ofertas pacíficas.

[[v7-21-5]]

^<<v7-21-5,5>>^ Disseram os filhos de Israel: Quem de todas as tribos de Israel não subiu à assembleia do SENHOR? Porque se tinha feito um grande juramento acerca do que não viesse ao SENHOR a Mispa, que dizia: Será morto.

[[v7-21-6]]

^<<v7-21-6,6>>^ Os filhos de Israel tiveram compaixão de seu irmão Benjamim e disseram: Foi, hoje, eliminada uma tribo de Israel.

[[v7-21-7]]

^<<v7-21-7,7>>^ Como obteremos mulheres para os restantes deles, pois juramos, pelo SENHOR, que das nossas filhas não lhes daríamos por mulheres?

[[v7-21-8]]

^<<v7-21-8,8>>^ E disseram: Há alguma das tribos de Israel que não tenha subido ao SENHOR a Mispa? E eis que ninguém de Jabes-Gileade viera ao acampamento, à assembleia.

[[v7-21-9]]

^<<v7-21-9,9>>^ Quando se contou o povo, eis que nenhum dos moradores de Jabes-Gileade se achou ali.

[[v7-21-10]]

^<<v7-21-10,10>>^ Por isso, a congregação enviou lá doze mil homens dos mais valentes e lhes ordenou, dizendo: Ide e, a fio de espada, feri os moradores de Jabes-Gileade, e as mulheres, e as crianças.

[[v7-21-11]]

^<<v7-21-11,11>>^ Isto é o que haveis de fazer: a todo homem e a toda mulher que se houver deitado com homem destruireis.

[[v7-21-12]]

^<<v7-21-12,12>>^ Acharam entre os moradores de Jabes-Gileade quatrocentas moças virgens, que não se deitaram com homem; e as trouxeram ao acampamento, a Siló, que está na terra de Canaã.

[[v7-21-13]]

^<<v7-21-13,13>>^ Toda a congregação, pois, enviou mensageiros aos filhos de Benjamim que estavam na penha Rimom, e lhes proclamaram a paz.

[[v7-21-14]]

^<<v7-21-14,14>>^ Nesse mesmo tempo, voltaram os benjamitas; e se lhes deram por mulheres as que foram conservadas com vida, das de Jabes-Gileade; porém estas ainda não lhes bastaram.

[[v7-21-15]]

^<<v7-21-15,15>>^ Então, o povo teve compaixão de Benjamim, porquanto o SENHOR tinha feito brecha nas tribos de Israel.

[[v7-21-16]]

^<<v7-21-16,16>>^ Disseram os anciãos da congregação: Como obteremos mulheres para os restantes ainda, pois foram exterminadas as mulheres dos benjamitas?

[[v7-21-17]]

^<<v7-21-17,17>>^ Disseram mais: A herança dos que ficaram de resto não na deve perder Benjamim, visto que nenhuma tribo de Israel deve ser destruída.

[[v7-21-18]]

^<<v7-21-18,18>>^ Porém nós não lhes poderemos dar mulheres de nossas filhas, porque os filhos de Israel juraram, dizendo: Maldito o que der mulher aos benjamitas.

[[v7-21-19]]

^<<v7-21-19,19>>^ Então, disseram: Eis que, de ano em ano, há solenidade do SENHOR em Siló, que se celebra para o norte de Betel, do lado do nascente do sol, pelo caminho alto que sobe de Betel a Siquém e para o sul de Lebona.

[[v7-21-20]]

^<<v7-21-20,20>>^ Ordenaram aos filhos de Benjamim, dizendo: Ide, e emboscai-vos nas vinhas,

[[v7-21-21]]

^<<v7-21-21,21>>^ e olhai; e eis aí, saindo as filhas de Siló a dançar em rodas, saí vós das vinhas, e arrebatai, dentre elas, cada um sua mulher, e ide-vos à terra de Benjamim.

[[v7-21-22]]

^<<v7-21-22,22>>^ Quando seus pais ou seus irmãos vierem queixar-se a nós, nós lhes diremos: por amor de nós, tende compaixão deles, pois, na guerra contra Jabes-Gileade, não obtivemos mulheres para cada um deles; e também não lhes destes, pois neste caso ficaríeis culpados.

[[v7-21-23]]

^<<v7-21-23,23>>^ Assim fizeram os filhos de Benjamim e levaram mulheres conforme o número deles, das que arrebataram das rodas que dançavam; e foram-se, voltaram à sua herança, reedificaram as cidades e habitaram nelas.

[[v7-21-24]]

^<<v7-21-24,24>>^ Então, os filhos de Israel também partiram dali, cada um para a sua tribo, para a sua família e para a sua herança.

[[v7-21-25]]

^<<v7-21-25,25>>^ Naqueles dias, não havia rei em Israel; cada um fazia o que achava mais reto.

'''

xref:007-juizes/007-juizes-020.adoc#v7-20-0[&#60; Capítulo Anterior] | <<v7-21-0,Topo>> | xref:008-rute/008-rute-001.adoc#v8-1-0[Próximo Capítulo &#62;]