include::./index.adoc[]

[[v7-11-0]]
=== Juízes, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v7-11-1]]

^<<v7-11-1,1>>^ Era, então, Jefté, o gileadita, homem valente, porém filho de uma prostituta; Gileade gerara a Jefté.

[[v7-11-2]]

^<<v7-11-2,2>>^ Também a mulher de Gileade lhe deu filhos, os quais, quando já grandes, expulsaram Jefté e lhe disseram: Não herdarás em casa de nosso pai, porque és filho doutra mulher.

[[v7-11-3]]

^<<v7-11-3,3>>^ Então, Jefté fugiu da presença de seus irmãos e habitou na terra de Tobe; e homens levianos se ajuntaram com ele e com ele saíam.

[[v7-11-4]]

^<<v7-11-4,4>>^ Passado algum tempo, pelejaram os filhos de Amom contra Israel.

[[v7-11-5]]

^<<v7-11-5,5>>^ Quando pelejavam, foram os anciãos de Gileade buscar Jefté da terra de Tobe.

[[v7-11-6]]

^<<v7-11-6,6>>^ E disseram a Jefté: Vem e sê nosso chefe, para que combatamos contra os filhos de Amom.

[[v7-11-7]]

^<<v7-11-7,7>>^ Porém Jefté disse aos anciãos de Gileade: Porventura, não me aborrecestes a mim e não me expulsastes da casa de meu pai? Por que, pois, vindes a mim, agora, quando estais em aperto?

[[v7-11-8]]

^<<v7-11-8,8>>^ Responderam os anciãos de Gileade a Jefté: Por isso mesmo, tornamos a ti. Vem, pois, conosco, e combate contra os filhos de Amom, e sê o nosso chefe sobre todos os moradores de Gileade.

[[v7-11-9]]

^<<v7-11-9,9>>^ Então, Jefté perguntou aos anciãos de Gileade: Se me tornardes a levar para combater contra os filhos de Amom, e o SENHOR mos der a mim, então, eu vos serei por cabeça?

[[v7-11-10]]

^<<v7-11-10,10>>^ Responderam os anciãos de Gileade a Jefté: O SENHOR será testemunha entre nós e nos castigará se não fizermos segundo a tua palavra.

[[v7-11-11]]

^<<v7-11-11,11>>^ Então, Jefté foi com os anciãos de Gileade, e o povo o pôs por cabeça e chefe sobre si; e Jefté proferiu todas as suas palavras perante o SENHOR, em Mispa.

[[v7-11-12]]

^<<v7-11-12,12>>^ Enviou Jefté mensageiros ao rei dos filhos de Amom, dizendo: Que há entre mim e ti que vieste a mim a pelejar contra a minha terra?

[[v7-11-13]]

^<<v7-11-13,13>>^ Respondeu o rei dos filhos de Amom aos mensageiros de Jefté: É porque, subindo Israel do Egito, me tomou a terra desde Arnom até ao Jaboque e ainda até ao Jordão; restitui-ma, agora, pacificamente.

[[v7-11-14]]

^<<v7-11-14,14>>^ Porém Jefté tornou a enviar mensageiros ao rei dos filhos de Amom,

[[v7-11-15]]

^<<v7-11-15,15>>^ dizendo-lhe: Assim diz Jefté: Israel não tomou nem a terra dos moabitas nem a terra dos filhos de Amom;

[[v7-11-16]]

^<<v7-11-16,16>>^ porque, subindo Israel do Egito, andou pelo deserto até ao mar Vermelho e chegou a Cades.

[[v7-11-17]]

^<<v7-11-17,17>>^ Então, Israel enviou mensageiros ao rei dos edomitas, dizendo: Rogo-te que me deixes passar pela tua terra. Porém o rei dos edomitas não lhe deu ouvidos; a mesma coisa mandou Israel pedir ao rei dos moabitas, o qual também não lhe quis atender; e, assim, Israel ficou em Cades.

[[v7-11-18]]

^<<v7-11-18,18>>^ Depois, andou pelo deserto, e rodeou a terra dos edomitas e a terra dos moabitas, e chegou ao oriente da terra destes, e se acampou além do Arnom; por isso, não entrou no território dos moabitas, porque Arnom é o limite deles.

[[v7-11-19]]

^<<v7-11-19,19>>^ Mas Israel enviou mensageiros a Seom, rei dos amorreus, rei de Hesbom; e disse-lhe: Deixa-nos, peço-te, passar pela tua terra até ao meu lugar.

[[v7-11-20]]

^<<v7-11-20,20>>^ Porém Seom, não confiando em Israel, recusou deixá-lo passar pelo seu território; pelo contrário, ajuntou todo o seu povo, e se acampou em Jaza, e pelejou contra Israel.

[[v7-11-21]]

^<<v7-11-21,21>>^ O SENHOR, Deus de Israel, entregou Seom e todo o seu povo nas mãos de Israel, que os feriu; e Israel desapossou os amorreus das terras que habitavam.

[[v7-11-22]]

^<<v7-11-22,22>>^ Tomou posse de todo o território dos amorreus, desde o Arnom até ao Jaboque e desde o deserto até ao Jordão.

[[v7-11-23]]

^<<v7-11-23,23>>^ Assim, o SENHOR, Deus de Israel, desapossou os amorreus ante o seu povo de Israel. E pretendes tu ser dono desta terra?

[[v7-11-24]]

^<<v7-11-24,24>>^ Não é certo que aquilo que Quemos, teu deus, te dá consideras como tua possessão? Assim, possuiremos nós o território de todos quantos o SENHOR, nosso Deus, expulsou de diante de nós.

[[v7-11-25]]

^<<v7-11-25,25>>^ És tu melhor do que o filho de Zipor, Balaque, rei dos moabitas? Porventura, contendeu este, em algum tempo, com Israel ou pelejou alguma vez contra ele?

[[v7-11-26]]

^<<v7-11-26,26>>^ Enquanto Israel habitou trezentos anos em Hesbom e nas suas vilas, e em Aroer e nas suas vilas, e em todas as cidades que estão ao longe do Arnom, por que vós, amonitas, não as recuperastes durante esse tempo?

[[v7-11-27]]

^<<v7-11-27,27>>^ Não sou eu, portanto, quem pecou contra ti! Porém tu fazes mal em pelejar contra mim; o SENHOR, que é juiz, julgue hoje entre os filhos de Israel e os filhos de Amom.

[[v7-11-28]]

^<<v7-11-28,28>>^ Porém o rei dos filhos de Amom não deu ouvidos à mensagem que Jefté lhe enviara.

[[v7-11-29]]

^<<v7-11-29,29>>^ Então, o Espírito do SENHOR veio sobre Jefté; e, atravessando este por Gileade e Manassés, passou até Mispa de Gileade e de Mispa de Gileade passou contra os filhos de Amom.

[[v7-11-30]]

^<<v7-11-30,30>>^ Fez Jefté um voto ao SENHOR e disse: Se, com efeito, me entregares os filhos de Amom nas minhas mãos,

[[v7-11-31]]

^<<v7-11-31,31>>^ quem primeiro da porta da minha casa me sair ao encontro, voltando eu vitorioso dos filhos de Amom, esse será do SENHOR, e eu o oferecerei em holocausto.

[[v7-11-32]]

^<<v7-11-32,32>>^ Assim, Jefté foi de encontro aos filhos de Amom, a combater contra eles; e o SENHOR os entregou nas mãos de Jefté.

[[v7-11-33]]

^<<v7-11-33,33>>^ Este os derrotou desde Aroer até às proximidades de Minite (vinte cidades ao todo) e até Abel-Queramim; e foi mui grande a derrota. Assim, foram subjugados os filhos de Amom diante dos filhos de Israel.

[[v7-11-34]]

^<<v7-11-34,34>>^ Vindo, pois, Jefté a Mispa, a sua casa, saiu-lhe a filha ao seu encontro, com adufes e com danças; e era ela filha única; não tinha ele outro filho nem filha.

[[v7-11-35]]

^<<v7-11-35,35>>^ Quando a viu, rasgou as suas vestes e disse: Ah! Filha minha, tu me prostras por completo; tu passaste a ser a causa da minha calamidade, porquanto fiz voto ao SENHOR e não tornarei atrás.

[[v7-11-36]]

^<<v7-11-36,36>>^ E ela lhe disse: Pai meu, fizeste voto ao SENHOR; faze, pois, de mim segundo o teu voto; pois o SENHOR te vingou dos teus inimigos, os filhos de Amom.

[[v7-11-37]]

^<<v7-11-37,37>>^ Disse mais a seu pai: Concede-me isto: deixa-me por dois meses, para que eu vá, e desça pelos montes, e chore a minha virgindade, eu e as minhas companheiras.

[[v7-11-38]]

^<<v7-11-38,38>>^ Consentiu ele: Vai. E deixou-a ir por dois meses; então, se foi ela com as suas companheiras e chorou a sua virgindade pelos montes.

[[v7-11-39]]

^<<v7-11-39,39>>^ Ao fim dos dois meses, tornou ela para seu pai, o qual lhe fez segundo o voto por ele proferido; assim, ela jamais foi possuída por varão. Daqui veio o costume em Israel

[[v7-11-40]]

^<<v7-11-40,40>>^ de as filhas de Israel saírem por quatro dias, de ano em ano, a cantar em memória da filha de Jefté, o gileadita.

'''

xref:007-juizes/007-juizes-010.adoc#v7-10-0[&#60; Capítulo Anterior] | <<v7-11-0,Topo>> | xref:007-juizes/007-juizes-012.adoc#v7-12-0[Próximo Capítulo &#62;]