include::./index.adoc[]

[[v7-3-0]]
=== Juízes, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v7-3-1]]

^<<v7-3-1,1>>^ São estas as nações que o SENHOR deixou para, por elas, provar a Israel, isto é, provar quantos em Israel não sabiam de todas as guerras de Canaã.

[[v7-3-2]]

^<<v7-3-2,2>>^ Isso tão somente para que as gerações dos filhos de Israel delas soubessem (para lhes ensinar a guerra), pelo menos as gerações que, dantes, não sabiam disso:

[[v7-3-3]]

^<<v7-3-3,3>>^ cinco príncipes dos filisteus, e todos os cananeus, e sidônios, e heveus que habitavam as montanhas do Líbano, desde o monte de Baal-Hermom até à entrada de Hamate.

[[v7-3-4]]

^<<v7-3-4,4>>^ Estes ficaram para, por eles, o SENHOR pôr Israel à prova, para saber se dariam ouvidos aos mandamentos que havia ordenado a seus pais por intermédio de Moisés.

[[v7-3-5]]

^<<v7-3-5,5>>^ Habitando, pois, os filhos de Israel no meio dos cananeus, dos heteus, e amorreus, e ferezeus, e heveus, e jebuseus,

[[v7-3-6]]

^<<v7-3-6,6>>^ tomaram de suas filhas para si por mulheres e deram as suas próprias aos filhos deles; e rendiam culto a seus deuses.

[[v7-3-7]]

^<<v7-3-7,7>>^ Os filhos de Israel fizeram o que era mau perante o SENHOR e se esqueceram do SENHOR, seu Deus; e renderam culto aos baalins e ao poste-ídolo.

[[v7-3-8]]

^<<v7-3-8,8>>^ Então, a ira do SENHOR se acendeu contra Israel, e ele os entregou nas mãos de Cusã-Risataim, rei da Mesopotâmia; e os filhos de Israel serviram a Cusã-Risataim oito anos.

[[v7-3-9]]

^<<v7-3-9,9>>^ Clamaram ao SENHOR os filhos de Israel, e o SENHOR lhes suscitou libertador, que os libertou: Otniel, filho de Quenaz, que era irmão de Calebe e mais novo do que ele.

[[v7-3-10]]

^<<v7-3-10,10>>^ Veio sobre ele o Espírito do SENHOR, e ele julgou a Israel; saiu à peleja, e o SENHOR lhe entregou nas mãos a Cusã-Risataim, rei da Mesopotâmia, contra o qual ele prevaleceu.

[[v7-3-11]]

^<<v7-3-11,11>>^ Então, a terra ficou em paz durante quarenta anos. Otniel, filho de Quenaz, faleceu.

[[v7-3-12]]

^<<v7-3-12,12>>^ Tornaram, então, os filhos de Israel a fazer o que era mau perante o SENHOR; mas o SENHOR deu poder a Eglom, rei dos moabitas, contra Israel, porquanto fizeram o que era mau perante o SENHOR.

[[v7-3-13]]

^<<v7-3-13,13>>^ E ajuntou consigo os filhos de Amom e os amalequitas, e foi, e feriu a Israel; e apoderaram-se da cidade das Palmeiras.

[[v7-3-14]]

^<<v7-3-14,14>>^ E os filhos de Israel serviram a Eglom, rei dos moabitas, dezoito anos.

[[v7-3-15]]

^<<v7-3-15,15>>^ Então, os filhos de Israel clamaram ao SENHOR, e o SENHOR lhes suscitou libertador: Eúde, homem canhoto, filho de Gera, benjamita. Por intermédio dele, enviaram os filhos de Israel tributo a Eglom, rei dos moabitas.

[[v7-3-16]]

^<<v7-3-16,16>>^ Eúde fez para si um punhal de dois gumes, do comprimento de um côvado; e cingiu-o debaixo das suas vestes, do lado direito.

[[v7-3-17]]

^<<v7-3-17,17>>^ Levou o tributo a Eglom, rei dos moabitas; era Eglom homem gordo.

[[v7-3-18]]

^<<v7-3-18,18>>^ Tendo entregado o tributo, despediu a gente que o trouxera e saiu com ela.

[[v7-3-19]]

^<<v7-3-19,19>>^ Porém voltou do ponto em que estavam as imagens de escultura ao pé de Gilgal e disse ao rei: Tenho uma palavra secreta a dizer-te, ó rei. O rei disse: Cala-te. Então, todos os que lhe assistiam saíram de sua presença.

[[v7-3-20]]

^<<v7-3-20,20>>^ Eúde entrou numa sala de verão, que o rei tinha só para si, onde estava assentado, e disse: Tenho a dizer-te uma palavra de Deus. E Eglom se levantou da cadeira.

[[v7-3-21]]

^<<v7-3-21,21>>^ Então, Eúde, estendendo a mão esquerda, puxou o seu punhal do lado direito e lho cravou no ventre,

[[v7-3-22]]

^<<v7-3-22,22>>^ de tal maneira que entrou também o cabo com a lâmina, e, porque não o retirou do ventre, a gordura se fechou sobre ele; e Eúde, saindo por um postigo,

[[v7-3-23]]

^<<v7-3-23,23>>^ passou para o vestíbulo, depois de cerrar sobre ele as portas, trancando-as.

[[v7-3-24]]

^<<v7-3-24,24>>^ Tendo saído, vieram os servos do rei e viram, e eis que as portas da sala de verão estavam trancadas; e disseram: Sem dúvida está ele aliviando o ventre na privada da sala de verão.

[[v7-3-25]]

^<<v7-3-25,25>>^ Aborreceram-se de esperar; e, como não abria a porta da sala, tomaram da chave e a abriram; e eis seu senhor estendido morto em terra.

[[v7-3-26]]

^<<v7-3-26,26>>^ Eúde escapou enquanto eles se demoravam e, tendo passado pelas imagens de escultura, foi para Seirá.

[[v7-3-27]]

^<<v7-3-27,27>>^ Tendo ele chegado, tocou a trombeta nas montanhas de Efraim; e os filhos de Israel desceram com ele das montanhas, indo ele à frente.

[[v7-3-28]]

^<<v7-3-28,28>>^ E lhes disse: Segui-me, porque o SENHOR entregou nas vossas mãos os vossos inimigos, os moabitas; e desceram após ele, e tomaram os vaus do Jordão contra os moabitas, e a nenhum deles deixaram passar.

[[v7-3-29]]

^<<v7-3-29,29>>^ Naquele tempo, feriram dos moabitas uns dez mil homens, todos robustos e valentes; e não escapou nem sequer um.

[[v7-3-30]]

^<<v7-3-30,30>>^ Assim, foi Moabe subjugado, naquele dia, sob o poder de Israel; e a terra ficou em paz oitenta anos.

[[v7-3-31]]

^<<v7-3-31,31>>^ Depois dele, foi Sangar, filho de Anate, que feriu seiscentos homens dos filisteus com uma aguilhada de bois; e também ele libertou a Israel.

'''

xref:007-juizes/007-juizes-002.adoc#v7-2-0[&#60; Capítulo Anterior] | <<v7-3-0,Topo>> | xref:007-juizes/007-juizes-004.adoc#v7-4-0[Próximo Capítulo &#62;]