include::./index.adoc[]

[[v7-17-0]]
=== Juízes, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v7-17-1]]

^<<v7-17-1,1>>^ Havia um homem da região montanhosa de Efraim cujo nome era Mica,

[[v7-17-2]]

^<<v7-17-2,2>>^ o qual disse a sua mãe: Os mil e cem siclos de prata que te foram tirados, por cuja causa deitavas maldições e de que também me falaste, eis que esse dinheiro está comigo; eu o tomei. Então, lhe disse a mãe: Bendito do SENHOR seja meu filho!

[[v7-17-3]]

^<<v7-17-3,3>>^ Assim, restituiu os mil e cem siclos de prata a sua mãe, que disse: De minha mão dedico este dinheiro ao SENHOR para meu filho, para fazer uma imagem de escultura e uma de fundição, de sorte que, agora, eu to devolvo.

[[v7-17-4]]

^<<v7-17-4,4>>^ Porém ele restituiu o dinheiro a sua mãe, que tomou duzentos siclos de prata e os deu ao ourives, o qual fez deles uma imagem de escultura e uma de fundição; e a imagem esteve em casa de Mica.

[[v7-17-5]]

^<<v7-17-5,5>>^ E, assim, este homem, Mica, veio a ter uma casa de deuses; fez uma estola sacerdotal e ídolos do lar e consagrou a um de seus filhos, para que lhe fosse por sacerdote.

[[v7-17-6]]

^<<v7-17-6,6>>^ Naqueles dias, não havia rei em Israel; cada qual fazia o que achava mais reto.

[[v7-17-7]]

^<<v7-17-7,7>>^ Havia um moço de Belém de Judá, da tribo de Judá, que era levita e se demorava ali.

[[v7-17-8]]

^<<v7-17-8,8>>^ Esse homem partiu da cidade de Belém de Judá para ficar onde melhor lhe parecesse. Seguindo, pois, o seu caminho, chegou à região montanhosa de Efraim, até à casa de Mica.

[[v7-17-9]]

^<<v7-17-9,9>>^ Perguntou-lhe Mica: Donde vens? Ele lhe respondeu: Sou levita de Belém de Judá e vou ficar onde melhor me parecer.

[[v7-17-10]]

^<<v7-17-10,10>>^ Então, lhe disse Mica: Fica comigo e sê-me por pai e sacerdote; e cada ano te darei dez siclos de prata, o vestuário e o sustento. O levita entrou

[[v7-17-11]]

^<<v7-17-11,11>>^ e consentiu em ficar com aquele homem; e o moço lhe foi como um de seus filhos.

[[v7-17-12]]

^<<v7-17-12,12>>^ Consagrou Mica ao moço levita, que lhe passou a ser sacerdote; e ficou em casa de Mica.

[[v7-17-13]]

^<<v7-17-13,13>>^ Então, disse Mica: Sei, agora, que o SENHOR me fará bem, porquanto tenho um levita por sacerdote.

'''

xref:007-juizes/007-juizes-016.adoc#v7-16-0[&#60; Capítulo Anterior] | <<v7-17-0,Topo>> | xref:007-juizes/007-juizes-018.adoc#v7-18-0[Próximo Capítulo &#62;]