include::./index.adoc[]

[[v7-15-0]]
=== Juízes, 15
// ara ?, ARA - Almeida Revista e Atualizada

[[v7-15-1]]

^<<v7-15-1,1>>^ Passado algum tempo, nos dias da ceifa do trigo, Sansão, levando um cabrito, foi visitar a sua mulher, pois dizia: Entrarei na câmara de minha mulher. Porém o pai dela não o deixou entrar

[[v7-15-2]]

^<<v7-15-2,2>>^ e lhe disse: Por certo, pensava eu que de todo a aborrecias, de sorte que a dei ao teu companheiro; porém não é mais formosa do que ela a irmã que é mais nova? Toma-a, pois, em seu lugar.

[[v7-15-3]]

^<<v7-15-3,3>>^ Então, Sansão lhe respondeu: Desta feita sou inocente para com os filisteus, quando lhes fizer algum mal.

[[v7-15-4]]

^<<v7-15-4,4>>^ E saiu e tomou trezentas raposas; e, tomando fachos, as virou cauda com cauda e lhes atou um facho no meio delas.

[[v7-15-5]]

^<<v7-15-5,5>>^ Tendo ele chegado fogo aos tições, largou-as na seara dos filisteus e, assim, incendiou tanto os molhos como o cereal por ceifar, e as vinhas, e os olivais.

[[v7-15-6]]

^<<v7-15-6,6>>^ Perguntaram os filisteus: Quem fez isto? Responderam: Sansão, o genro do timnita, porque lhe tomou a mulher e a deu a seu companheiro. Então, subiram os filisteus e queimaram a ela e o seu pai.

[[v7-15-7]]

^<<v7-15-7,7>>^ Disse-lhes Sansão: Se assim procedeis, não desistirei enquanto não me vingar.

[[v7-15-8]]

^<<v7-15-8,8>>^ E feriu-os com grande carnificina; e desceu e habitou na fenda da rocha de Etã.

[[v7-15-9]]

^<<v7-15-9,9>>^ Então, os filisteus subiram, e acamparam-se contra Judá, e estenderam-se por Leí.

[[v7-15-10]]

^<<v7-15-10,10>>^ Perguntaram-lhes os homens de Judá: Por que subistes contra nós? Responderam: Subimos para amarrar Sansão, para lhe fazer a ele como ele nos fez a nós.

[[v7-15-11]]

^<<v7-15-11,11>>^ Então, três mil homens de Judá desceram até à fenda da rocha de Etã e disseram a Sansão: Não sabias tu que os filisteus dominam sobre nós? Por que, pois, nos fizeste isto? Ele lhes respondeu: Assim como me fizeram a mim, eu lhes fiz a eles.

[[v7-15-12]]

^<<v7-15-12,12>>^ Descemos, replicaram eles, para te amarrar, para te entregar nas mãos dos filisteus. Sansão lhes disse: Jurai-me que vós mesmos não me acometereis.

[[v7-15-13]]

^<<v7-15-13,13>>^ Eles lhe disseram: Não, mas somente te amarraremos e te entregaremos nas suas mãos; porém de maneira nenhuma te mataremos. E amarraram-no com duas cordas novas e fizeram-no subir da rocha.

[[v7-15-14]]

^<<v7-15-14,14>>^ Chegando ele a Leí, os filisteus lhe saíram ao encontro, jubilando; porém o Espírito do SENHOR de tal maneira se apossou dele, que as cordas que tinha nos braços se tornaram como fios de linho queimados, e as suas amarraduras se desfizeram das suas mãos.

[[v7-15-15]]

^<<v7-15-15,15>>^ Achou uma queixada de jumento, ainda fresca, à mão, e tomou-a, e feriu com ela mil homens.

[[v7-15-16]]

^<<v7-15-16,16>>^ E disse: Com uma queixada de jumento um montão, outro montão; com uma queixada de jumento feri mil homens.

[[v7-15-17]]

^<<v7-15-17,17>>^ Tendo ele acabado de falar, lançou da sua mão a queixada. Chamou-se aquele lugar Ramate-Leí.

[[v7-15-18]]

^<<v7-15-18,18>>^ Sentindo grande sede, clamou ao SENHOR e disse: Por intermédio do teu servo deste esta grande salvação; morrerei eu, agora, de sede e cairei nas mãos destes incircuncisos?

[[v7-15-19]]

^<<v7-15-19,19>>^ Então, o SENHOR fendeu a cavidade que estava em Leí, e dela saiu água; tendo Sansão bebido, recobrou alento e reviveu; daí chamar-se aquele lugar En-Hacoré até ao dia de hoje.

[[v7-15-20]]

^<<v7-15-20,20>>^ Sansão julgou a Israel, nos dias dos filisteus, vinte anos.

'''

xref:007-juizes/007-juizes-014.adoc#v7-14-0[&#60; Capítulo Anterior] | <<v7-15-0,Topo>> | xref:007-juizes/007-juizes-016.adoc#v7-16-0[Próximo Capítulo &#62;]