include::./index.adoc[]

[[v7-1-0]]
=== Juízes, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v7-1-1]]

^<<v7-1-1,1>>^ Depois da morte de Josué, os filhos de Israel consultaram o SENHOR, dizendo: Quem dentre nós, primeiro, subirá aos cananeus para pelejar contra eles?

[[v7-1-2]]

^<<v7-1-2,2>>^ Respondeu o SENHOR: Judá subirá; eis que nas suas mãos entreguei a terra.

[[v7-1-3]]

^<<v7-1-3,3>>^ Disse, pois, Judá a Simeão, seu irmão: Sobe comigo à herança que me caiu por sorte, e pelejemos contra os cananeus, e também eu subirei contigo à tua, que te caiu por sorte. E Simeão partiu com ele.

[[v7-1-4]]

^<<v7-1-4,4>>^ Subiu Judá, e o SENHOR lhe entregou nas mãos os cananeus e os ferezeus; e feriram deles, em Bezeque, dez mil homens.

[[v7-1-5]]

^<<v7-1-5,5>>^ Em Bezeque, encontraram Adoni-Bezeque e pelejaram contra ele; e feriram aos cananeus e aos ferezeus.

[[v7-1-6]]

^<<v7-1-6,6>>^ Adoni-Bezeque, porém, fugiu; mas o perseguiram e, prendendo-o, lhe cortaram os polegares das mãos e dos pés.

[[v7-1-7]]

^<<v7-1-7,7>>^ Então, disse Adoni-Bezeque: Setenta reis, a quem haviam sido cortados os polegares das mãos e dos pés, apanhavam migalhas debaixo da minha mesa; assim como eu fiz, assim Deus me pagou. E o levaram a Jerusalém, e morreu ali.

[[v7-1-8]]

^<<v7-1-8,8>>^ Os filhos de Judá pelejaram contra Jerusalém e, tomando-a, passaram-na a fio de espada, pondo fogo à cidade.

[[v7-1-9]]

^<<v7-1-9,9>>^ Depois, os filhos de Judá desceram a pelejar contra os cananeus que habitavam nas montanhas, no Neguebe e nas planícies.

[[v7-1-10]]

^<<v7-1-10,10>>^ Partiu Judá contra os cananeus que habitavam em Hebrom, cujo nome, outrora, era Quiriate-Arba, e Judá feriu a Sesai, a Aimã e a Talmai.

[[v7-1-11]]

^<<v7-1-11,11>>^ Dali partiu contra os moradores de Debir; e era, dantes, o nome de Debir Quiriate-Sefer.

[[v7-1-12]]

^<<v7-1-12,12>>^ Disse Calebe: A quem derrotar Quiriate-Sefer e a tomar, darei minha filha Acsa por mulher.

[[v7-1-13]]

^<<v7-1-13,13>>^ Tomou-a, pois, Otniel, filho de Quenaz, o irmão de Calebe, mais novo do que ele; e Calebe lhe deu sua filha Acsa por mulher.

[[v7-1-14]]

^<<v7-1-14,14>>^ Esta, quando se foi a ele, insistiu com ele para que pedisse um campo ao pai dela; e ela apeou do jumento; então, Calebe lhe perguntou: Que desejas?

[[v7-1-15]]

^<<v7-1-15,15>>^ Respondeu ela: Dá-me um presente; deste-me terra seca, dá-me também fontes de água. Então, Calebe lhe deu as fontes superiores e as fontes inferiores.

[[v7-1-16]]

^<<v7-1-16,16>>^ Os filhos do queneu, sogro de Moisés, subiram, com os filhos de Judá, da cidade das Palmeiras ao deserto de Judá, que está ao sul de Arade; foram e habitaram com este povo.

[[v7-1-17]]

^<<v7-1-17,17>>^ Foi-se, pois, Judá com Simeão, seu irmão, e feriram aos cananeus que habitavam em Zefate e totalmente a destruíram; por isso, lhe chamaram Horma.

[[v7-1-18]]

^<<v7-1-18,18>>^ Tomou ainda Judá a Gaza, a Asquelom e a Ecrom com os seus respectivos territórios.

[[v7-1-19]]

^<<v7-1-19,19>>^ Esteve o SENHOR com Judá, e este despovoou as montanhas; porém não expulsou os moradores do vale, porquanto tinham carros de ferro.

[[v7-1-20]]

^<<v7-1-20,20>>^ E, como Moisés o dissera, deram Hebrom a Calebe, e este expulsou dali os três filhos de Anaque.

[[v7-1-21]]

^<<v7-1-21,21>>^ Porém os filhos de Benjamim não expulsaram os jebuseus que habitavam em Jerusalém; antes, os jebuseus habitam com os filhos de Benjamim em Jerusalém, até ao dia de hoje.

[[v7-1-22]]

^<<v7-1-22,22>>^ Subiu também a casa de José contra Betel, e o SENHOR era com eles.

[[v7-1-23]]

^<<v7-1-23,23>>^ A casa de José enviou homens a espiar Betel, cujo nome, dantes, era Luz.

[[v7-1-24]]

^<<v7-1-24,24>>^ Vendo os espias um homem que saía da cidade, lhe disseram: Mostra-nos a entrada da cidade, e usaremos de misericórdia para contigo.

[[v7-1-25]]

^<<v7-1-25,25>>^ Mostrando-lhes ele a entrada da cidade, feriram a cidade a fio de espada; porém, àquele homem e a toda a sua família, deixaram ir.

[[v7-1-26]]

^<<v7-1-26,26>>^ Então, se foi ele à terra dos heteus, e edificou uma cidade, e lhe chamou Luz; este é o seu nome até ao dia de hoje.

[[v7-1-27]]

^<<v7-1-27,27>>^ Manassés não expulsou os habitantes de Bete-Seã, nem os de Taanaque, nem os de Dor, nem os de Ibleão, nem os de Megido, todas com suas respectivas aldeias; pelo que os cananeus lograram permanecer na mesma terra.

[[v7-1-28]]

^<<v7-1-28,28>>^ Quando, porém, Israel se tornou mais forte, sujeitou os cananeus a trabalhos forçados e não os expulsou de todo.

[[v7-1-29]]

^<<v7-1-29,29>>^ Efraim não expulsou os cananeus, habitantes de Gezer; antes, continuaram com ele em Gezer.

[[v7-1-30]]

^<<v7-1-30,30>>^ Zebulom não expulsou os habitantes de Quitrom, nem os de Naalol; porém os cananeus continuaram com ele, sujeitos a trabalhos forçados.

[[v7-1-31]]

^<<v7-1-31,31>>^ Aser não expulsou os habitantes de Aco, nem os de Sidom, os de Alabe, os de Aczibe, os de Helba, os de Afeca e os de Reobe;

[[v7-1-32]]

^<<v7-1-32,32>>^ porém os aseritas continuaram no meio dos cananeus que habitavam na terra, porquanto os não expulsaram.

[[v7-1-33]]

^<<v7-1-33,33>>^ Naftali não expulsou os habitantes de Bete-Semes, nem os de Bete-Anate; mas continuou no meio dos cananeus que habitavam na terra; porém os de Bete-Semes e Bete-Anate lhe foram sujeitos a trabalhos forçados.

[[v7-1-34]]

^<<v7-1-34,34>>^ Os amorreus arredaram os filhos de Dã até às montanhas e não os deixavam descer ao vale.

[[v7-1-35]]

^<<v7-1-35,35>>^ Porém os amorreus lograram habitar nas montanhas de Heres, em Aijalom e em Saalabim; contudo, a mão da casa de José prevaleceu, e foram sujeitos a trabalhos forçados.

[[v7-1-36]]

^<<v7-1-36,36>>^ O limite dos amorreus foi desde a subida de Acrabim e desde Sela para cima.

'''

xref:006-josue/006-josue-024.adoc#v6-24-0[&#60; Capítulo Anterior] | <<v7-1-0,Topo>> | xref:007-juizes/007-juizes-002.adoc#v7-2-0[Próximo Capítulo &#62;]