include::./index.adoc[]

[[v7-12-0]]
=== Juízes, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v7-12-1]]

^<<v7-12-1,1>>^ Então, foram convocados os homens de Efraim, e passaram para Zafom, e disseram a Jefté: Por que foste combater contra os filhos de Amom e não nos chamaste para ir contigo? Queimaremos a tua casa, estando tu dentro dela.

[[v7-12-2]]

^<<v7-12-2,2>>^ E Jefté lhes disse: Eu e o meu povo tivemos grande contenda com os filhos de Amom; chamei-vos, e não me livrastes das suas mãos.

[[v7-12-3]]

^<<v7-12-3,3>>^ Vendo eu que não me livráveis, arrisquei a minha vida e passei contra os filhos de Amom, e o SENHOR os entregou nas minhas mãos; por que, pois, subistes, hoje, contra mim, para me combaterdes?

[[v7-12-4]]

^<<v7-12-4,4>>^ Ajuntou Jefté todos os homens de Gileade e pelejou contra Efraim; e os homens de Gileade feriram Efraim, porque este dissera: Fugitivos sois de Efraim, vós, gileaditas, que morais no meio de Efraim e Manassés.

[[v7-12-5]]

^<<v7-12-5,5>>^ Porém os gileaditas tomaram os vaus do Jordão que conduzem a Efraim; de sorte que, quando qualquer fugitivo de Efraim dizia: Quero passar; então, os homens de Gileade lhe perguntavam: És tu efraimita? Se respondia: Não;

[[v7-12-6]]

^<<v7-12-6,6>>^ então, lhe tornavam: Dize, pois, chibolete; quando dizia sibolete, não podendo exprimir bem a palavra, então, pegavam dele e o matavam nos vaus do Jordão. E caíram de Efraim, naquele tempo, quarenta e dois mil.

[[v7-12-7]]

^<<v7-12-7,7>>^ Jefté, o gileadita, julgou a Israel seis anos; e morreu e foi sepultado numa das cidades de Gileade.

[[v7-12-8]]

^<<v7-12-8,8>>^ Depois dele, julgou a Israel Ibsã, de Belém.

[[v7-12-9]]

^<<v7-12-9,9>>^ Tinha este trinta filhos e trinta filhas; a estas, casou fora; e, de fora, trouxe trinta mulheres para seus filhos. Julgou a Israel sete anos.

[[v7-12-10]]

^<<v7-12-10,10>>^ Então, faleceu Ibsã e foi sepultado em Belém.

[[v7-12-11]]

^<<v7-12-11,11>>^ Depois dele, veio Elom, o zebulonita, que julgou a Israel dez anos.

[[v7-12-12]]

^<<v7-12-12,12>>^ Faleceu Elom, o zebulonita, e foi sepultado em Aijalom, na terra de Zebulom.

[[v7-12-13]]

^<<v7-12-13,13>>^ Depois dele, julgou a Israel Abdom, filho de Hilel, o piratonita.

[[v7-12-14]]

^<<v7-12-14,14>>^ Tinha este quarenta filhos e trinta netos, que cavalgavam setenta jumentos. Julgou a Israel oito anos.

[[v7-12-15]]

^<<v7-12-15,15>>^ Então, faleceu Abdom, filho de Hilel, o piratonita; e foi sepultado em Piratom, na terra de Efraim, na região montanhosa dos amalequitas.

'''

xref:007-juizes/007-juizes-011.adoc#v7-11-0[&#60; Capítulo Anterior] | <<v7-12-0,Topo>> | xref:007-juizes/007-juizes-013.adoc#v7-13-0[Próximo Capítulo &#62;]