include::./index.adoc[]

[[v7-4-0]]
=== Juízes, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v7-4-1]]

^<<v7-4-1,1>>^ Os filhos de Israel tornaram a fazer o que era mau perante o SENHOR, depois de falecer Eúde.

[[v7-4-2]]

^<<v7-4-2,2>>^ Entregou-os o SENHOR nas mãos de Jabim, rei de Canaã, que reinava em Hazor. Sísera era o comandante do seu exército, o qual, então, habitava em Harosete-Hagoim.

[[v7-4-3]]

^<<v7-4-3,3>>^ Clamaram os filhos de Israel ao SENHOR, porquanto Jabim tinha novecentos carros de ferro e, por vinte anos, oprimia duramente os filhos de Israel.

[[v7-4-4]]

^<<v7-4-4,4>>^ Débora, profetisa, mulher de Lapidote, julgava a Israel naquele tempo.

[[v7-4-5]]

^<<v7-4-5,5>>^ Ela atendia debaixo da palmeira de Débora, entre Ramá e Betel, na região montanhosa de Efraim; e os filhos de Israel subiam a ela a juízo.

[[v7-4-6]]

^<<v7-4-6,6>>^ Mandou ela chamar a Baraque, filho de Abinoão, de Quedes de Naftali, e disse-lhe: Porventura, o SENHOR, Deus de Israel, não deu ordem, dizendo: Vai, e leva gente ao monte Tabor, e toma contigo dez mil homens dos filhos de Naftali e dos filhos de Zebulom?

[[v7-4-7]]

^<<v7-4-7,7>>^ E farei ir a ti para o ribeiro Quisom a Sísera, comandante do exército de Jabim, com os seus carros e as suas tropas; e o darei nas tuas mãos.

[[v7-4-8]]

^<<v7-4-8,8>>^ Então, lhe disse Baraque: Se fores comigo, irei; porém, se não fores comigo, não irei.

[[v7-4-9]]

^<<v7-4-9,9>>^ Ela respondeu: Certamente, irei contigo, porém não será tua a honra da investida que empreendes; pois às mãos de uma mulher o SENHOR entregará a Sísera. E saiu Débora e se foi com Baraque para Quedes.

[[v7-4-10]]

^<<v7-4-10,10>>^ Então, Baraque convocou a Zebulom e a Naftali em Quedes, e com ele subiram dez mil homens; e Débora também subiu com ele.

[[v7-4-11]]

^<<v7-4-11,11>>^ Ora, Héber, queneu, se tinha apartado dos queneus, dos filhos de Hobabe, sogro de Moisés, e havia armado as suas tendas até ao carvalho de Zaananim, que está junto a Quedes.

[[v7-4-12]]

^<<v7-4-12,12>>^ Anunciaram a Sísera que Baraque, filho de Abinoão, tinha subido ao monte Tabor.

[[v7-4-13]]

^<<v7-4-13,13>>^ Sísera convocou todos os seus carros, novecentos carros de ferro, e todo o povo que estava com ele, de Harosete-Hagoim para o ribeiro Quisom.

[[v7-4-14]]

^<<v7-4-14,14>>^ Então, disse Débora a Baraque: Dispõe-te, porque este é o dia em que o SENHOR entregou a Sísera nas tuas mãos; porventura, o SENHOR não saiu adiante de ti? Baraque, pois, desceu do monte Tabor, e dez mil homens, após ele.

[[v7-4-15]]

^<<v7-4-15,15>>^ E o SENHOR derrotou a Sísera, e todos os seus carros, e a todo o seu exército a fio de espada, diante de Baraque; e Sísera saltou do carro e fugiu a pé.

[[v7-4-16]]

^<<v7-4-16,16>>^ Mas Baraque perseguiu os carros e os exércitos até Harosete-Hagoim; e todo o exército de Sísera caiu a fio de espada, sem escapar nem sequer um.

[[v7-4-17]]

^<<v7-4-17,17>>^ Porém Sísera fugiu a pé para a tenda de Jael, mulher de Héber, queneu; porquanto havia paz entre Jabim, rei de Hazor, e a casa de Héber, queneu.

[[v7-4-18]]

^<<v7-4-18,18>>^ Saindo Jael ao encontro de Sísera, disse-lhe: Entra, senhor meu, entra na minha tenda, não temas. Retirou-se para a sua tenda, e ela pôs sobre ele uma coberta.

[[v7-4-19]]

^<<v7-4-19,19>>^ Então, ele lhe disse: Dá-me, peço-te, de beber um pouco de água, porque tenho sede. Ela abriu um odre de leite, e deu-lhe de beber, e o cobriu.

[[v7-4-20]]

^<<v7-4-20,20>>^ E ele lhe disse mais: Põe-te à porta da tenda; e há de ser que, se vier alguém e te perguntar: Há aqui alguém?, responde: Não.

[[v7-4-21]]

^<<v7-4-21,21>>^ Então, Jael, mulher de Héber, tomou uma estaca da tenda, e lançou mão de um martelo, e foi-se mansamente a ele, e lhe cravou a estaca na fonte, de sorte que penetrou na terra, estando ele em profundo sono e mui exausto; e, assim, morreu.

[[v7-4-22]]

^<<v7-4-22,22>>^ E eis que, perseguindo Baraque a Sísera, Jael lhe saiu ao encontro e lhe disse: Vem, e mostrar-te-ei o homem que procuras. Ele a seguiu; e eis que Sísera jazia morto, e a estaca na fonte.

[[v7-4-23]]

^<<v7-4-23,23>>^ Assim, Deus, naquele dia, humilhou a Jabim, rei de Canaã, diante dos filhos de Israel.

[[v7-4-24]]

^<<v7-4-24,24>>^ E cada vez mais a mão dos filhos de Israel prevalecia contra Jabim, rei de Canaã, até que o exterminaram.

'''

xref:007-juizes/007-juizes-003.adoc#v7-3-0[&#60; Capítulo Anterior] | <<v7-4-0,Topo>> | xref:007-juizes/007-juizes-005.adoc#v7-5-0[Próximo Capítulo &#62;]