include::./index.adoc[]

[[v7-18-0]]
=== Juízes, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v7-18-1]]

^<<v7-18-1,1>>^ Naqueles dias, não havia rei em Israel, e a tribo dos danitas buscava para si herança em que habitar; porquanto, até àquele dia, entre as tribos de Israel, não lhe havia caído por sorte a herança.

[[v7-18-2]]

^<<v7-18-2,2>>^ Enviaram os filhos de Dã cinco homens dentre todos os da sua tribo, homens valentes, de Zorá e de Estaol, a espiar e explorar a terra; e lhes disseram: Ide, explorai a terra. Chegaram à região montanhosa de Efraim, até à casa de Mica, e ali pernoitaram.

[[v7-18-3]]

^<<v7-18-3,3>>^ Estando eles junto da casa de Mica, reconheceram a voz do moço, do levita; chegaram-se para lá e lhe disseram: Quem te trouxe para aqui? Que fazes aqui? E que é que tens aqui?

[[v7-18-4]]

^<<v7-18-4,4>>^ Ele respondeu: Assim e assim me fez Mica; pois me assalariou, e eu lhe sirvo de sacerdote.

[[v7-18-5]]

^<<v7-18-5,5>>^ Então, lhe disseram: Consulta a Deus, para que saibamos se prosperará o caminho que levamos.

[[v7-18-6]]

^<<v7-18-6,6>>^ Disse-lhes o sacerdote: Ide em paz; o caminho que levais está sob as vistas do SENHOR.

[[v7-18-7]]

^<<v7-18-7,7>>^ Partiram os cinco homens, e chegaram a Laís, e viram que o povo que havia nela estava seguro, segundo o costume dos sidônios, em paz e confiado. Nenhuma autoridade havia que, por qualquer coisa, o oprimisse; também estava longe dos sidônios e não tinha trato com nenhuma outra gente.

[[v7-18-8]]

^<<v7-18-8,8>>^ Então, voltaram a seus irmãos, a Zorá e a Estaol; e estes lhes perguntaram: Que nos dizeis?

[[v7-18-9]]

^<<v7-18-9,9>>^ Eles disseram: Disponde-vos e subamos contra eles; porque examinamos a terra, e eis que é muito boa. Estais aí parados? Não vos demoreis em sair para ocupardes a terra.

[[v7-18-10]]

^<<v7-18-10,10>>^ Quando lá chegardes, achareis um povo confiado, e a terra é ampla; porque Deus vo-la entregou nas mãos; é um lugar em que não há falta de coisa alguma que há na terra.

[[v7-18-11]]

^<<v7-18-11,11>>^ Então, partiram dali, da tribo dos danitas, de Zorá e de Estaol, seiscentos homens armados de suas armas de guerra.

[[v7-18-12]]

^<<v7-18-12,12>>^ Subiram e acamparam-se em Quiriate-Jearim, em Judá; pelo que chamaram a este lugar Maané-Dã, até ao dia de hoje; está por detrás de Quiriate-Jearim.

[[v7-18-13]]

^<<v7-18-13,13>>^ Dali, passaram à região montanhosa de Efraim e chegaram até à casa de Mica.

[[v7-18-14]]

^<<v7-18-14,14>>^ Os cinco homens que foram espiar a terra de Laís disseram a seus irmãos: Sabeis vós que, naquelas casas, há uma estola sacerdotal, e ídolos do lar, e uma imagem de escultura, e uma de fundição? Vede, pois, o que haveis de fazer.

[[v7-18-15]]

^<<v7-18-15,15>>^ Então, foram para lá, e chegaram à casa do moço, o levita, em casa de Mica, e o saudaram.

[[v7-18-16]]

^<<v7-18-16,16>>^ Os seiscentos homens que eram dos filhos de Dã, armados de suas armas de guerra, ficaram à entrada da porta.

[[v7-18-17]]

^<<v7-18-17,17>>^ Porém, subindo os cinco homens que foram espiar a terra, entraram e apanharam a imagem de escultura, a estola sacerdotal, os ídolos do lar e a imagem de fundição, ficando o sacerdote em pé à entrada da porta, com os seiscentos homens que estavam armados com as armas de guerra.

[[v7-18-18]]

^<<v7-18-18,18>>^ Entrando eles, pois, na casa de Mica e tomando a imagem de escultura, a estola sacerdotal, os ídolos do lar e a imagem de fundição, disse-lhes o sacerdote: Que estais fazendo?

[[v7-18-19]]

^<<v7-18-19,19>>^ Eles lhe disseram: Cala-te, e põe a mão na boca, e vem conosco, e sê-nos por pai e sacerdote. Ser-te-á melhor seres sacerdote da casa de um só homem do que seres sacerdote de uma tribo e de uma família em Israel?

[[v7-18-20]]

^<<v7-18-20,20>>^ Então, se alegrou o coração do sacerdote, tomou a estola sacerdotal, os ídolos do lar e a imagem de escultura e entrou no meio do povo.

[[v7-18-21]]

^<<v7-18-21,21>>^ Assim, viraram e, tendo posto diante de si os meninos, o gado e seus bens, partiram.

[[v7-18-22]]

^<<v7-18-22,22>>^ Estando já longe da casa de Mica, reuniram-se os homens que estavam nas casas junto à dele e alcançaram os filhos de Dã.

[[v7-18-23]]

^<<v7-18-23,23>>^ E clamaram após eles, os quais, voltando-se, disseram a Mica: Que tens, que convocaste esse povo?

[[v7-18-24]]

^<<v7-18-24,24>>^ Respondeu-lhes: Os deuses que eu fiz me tomastes e também o sacerdote e vos fostes; que mais me resta? Como, pois, me perguntais: Que é o que tens?

[[v7-18-25]]

^<<v7-18-25,25>>^ Porém os filhos de Dã lhe disseram: Não nos faças ouvir a tua voz, para que, porventura, homens de ânimo amargoso não se lancem sobre ti, e tu percas a tua vida e a vida dos da tua casa.

[[v7-18-26]]

^<<v7-18-26,26>>^ Assim, prosseguiram o seu caminho os filhos de Dã; e Mica, vendo que eram mais fortes do que ele, voltou-se e tornou para sua casa.

[[v7-18-27]]

^<<v7-18-27,27>>^ Levaram eles o que Mica havia feito e o sacerdote que tivera, e chegaram a Laís, a um povo em paz e confiado, e os feriram a fio de espada, e queimaram a cidade.

[[v7-18-28]]

^<<v7-18-28,28>>^ Ninguém houve que os livrasse, porquanto estavam longe de Sidom e não tinham trato com ninguém; a cidade estava no vale junto a Bete-Reobe. Reedificaram a cidade, habitaram nela

[[v7-18-29]]

^<<v7-18-29,29>>^ e lhe chamaram Dã, segundo o nome de Dã, seu pai, que nascera a Israel; porém, outrora, o nome desta cidade era Laís.

[[v7-18-30]]

^<<v7-18-30,30>>^ Os filhos de Dã levantaram para si aquela imagem de escultura; e Jônatas, filho de Gérson, o filho de Manassés, ele e seus filhos foram sacerdotes da tribo dos danitas até ao dia do cativeiro do povo.

[[v7-18-31]]

^<<v7-18-31,31>>^ Assim, pois, a imagem de escultura feita por Mica estabeleceram para si todos os dias que a Casa de Deus esteve em Siló.

'''

xref:007-juizes/007-juizes-017.adoc#v7-17-0[&#60; Capítulo Anterior] | <<v7-18-0,Topo>> | xref:007-juizes/007-juizes-019.adoc#v7-19-0[Próximo Capítulo &#62;]