include::./index.adoc[]

[[v7-20-0]]
=== Juízes, 20
// ara ?, ARA - Almeida Revista e Atualizada

[[v7-20-1]]

^<<v7-20-1,1>>^ Saíram todos os filhos de Israel, e a congregação se ajuntou perante o SENHOR em Mispa, como se fora um só homem, desde Dã até Berseba, como também a terra de Gileade.

[[v7-20-2]]

^<<v7-20-2,2>>^ Os príncipes de todo o povo e todas as tribos de Israel se apresentaram na congregação do povo de Deus. Havia quatrocentos mil homens de pé, que puxavam da espada.

[[v7-20-3]]

^<<v7-20-3,3>>^ Ouviram os filhos de Benjamim que os filhos de Israel haviam subido a Mispa. Disseram os filhos de Israel: Contai-nos como sucedeu esta maldade.

[[v7-20-4]]

^<<v7-20-4,4>>^ Então, respondeu o homem levita, marido da mulher que fora morta, e disse: Cheguei com a minha concubina a Gibeá, cidade de Benjamim, para passar a noite;

[[v7-20-5]]

^<<v7-20-5,5>>^ os cidadãos de Gibeá se levantaram contra mim e, à noite, cercaram a casa em que eu estava; intentaram matar-me e violaram a minha concubina, de maneira que morreu.

[[v7-20-6]]

^<<v7-20-6,6>>^ Então, peguei a minha concubina, e a fiz em pedaços, e os enviei por toda a terra da herança de Israel, porquanto fizeram vergonha e loucura em Israel.

[[v7-20-7]]

^<<v7-20-7,7>>^ Eis que todos sois filhos de Israel; eia! Dai a vossa palavra e conselho neste caso.

[[v7-20-8]]

^<<v7-20-8,8>>^ Então, todo o povo se levantou como um só homem, dizendo: Nenhum de nós voltará para sua tenda, nenhum de nós se retirará para casa.

[[v7-20-9]]

^<<v7-20-9,9>>^ Porém isto é o que faremos a Gibeá: subiremos contra ela por sorte.

[[v7-20-10]]

^<<v7-20-10,10>>^ Tomaremos dez homens de cem de todas as tribos de Israel, e cem de mil, e mil de dez mil, para providenciarem mantimento para o povo, a fim de que este, vindo a Gibeá de Benjamim, faça a ela conforme toda a loucura que tem feito em Israel.

[[v7-20-11]]

^<<v7-20-11,11>>^ Assim, se ajuntaram contra esta cidade todos os homens de Israel, unidos como um só homem.

[[v7-20-12]]

^<<v7-20-12,12>>^ As tribos de Israel enviaram homens por toda a tribo de Benjamim, para lhe dizerem: Que maldade é essa que se fez entre vós?

[[v7-20-13]]

^<<v7-20-13,13>>^ Dai-nos, agora, os homens, filhos de Belial, que estão em Gibeá, para que os matemos e tiremos de Israel o mal; porém Benjamim não quis ouvir a voz de seus irmãos, os filhos de Israel.

[[v7-20-14]]

^<<v7-20-14,14>>^ Antes, os filhos de Benjamim se ajuntaram, vindos das cidades em Gibeá, para saírem a pelejar contra os filhos de Israel.

[[v7-20-15]]

^<<v7-20-15,15>>^ E contaram-se, naquele dia, os filhos de Benjamim vindos das cidades; eram vinte e seis mil homens que puxavam da espada, afora os moradores de Gibeá, de que se contavam setecentos homens escolhidos.

[[v7-20-16]]

^<<v7-20-16,16>>^ Entre todo este povo havia setecentos homens escolhidos, canhotos, os quais atiravam com a funda uma pedra num cabelo e não erravam.

[[v7-20-17]]

^<<v7-20-17,17>>^ Contaram-se dos homens de Israel, afora os de Benjamim, quatrocentos mil homens que puxavam da espada, e todos eles, homens de guerra.

[[v7-20-18]]

^<<v7-20-18,18>>^ Levantaram-se os israelitas, subiram a Betel e consultaram a Deus, dizendo: Quem dentre nós subirá, primeiro, a pelejar contra Benjamim? Respondeu o SENHOR: Judá subirá primeiro.

[[v7-20-19]]

^<<v7-20-19,19>>^ Levantaram-se, pois, os filhos de Israel pela manhã e acamparam-se contra Gibeá.

[[v7-20-20]]

^<<v7-20-20,20>>^ Saíram os homens de Israel à peleja contra Benjamim; e, junto a Gibeá, se ordenaram contra ele.

[[v7-20-21]]

^<<v7-20-21,21>>^ Então, os filhos de Benjamim saíram de Gibeá e derribaram por terra, naquele dia, vinte e dois mil homens de Israel.

[[v7-20-22]]

^<<v7-20-22,22>>^ Porém se animou o povo dos homens de Israel e tornaram a ordenar-se para a peleja, no lugar onde, no primeiro dia, o tinham feito.

[[v7-20-23]]

^<<v7-20-23,23>>^ Antes, subiram os filhos de Israel, e choraram perante o SENHOR até à tarde, e consultaram o SENHOR, dizendo: Tornaremos a pelejar contra os filhos de Benjamim, nosso irmão? Respondeu o SENHOR: Subi contra ele.

[[v7-20-24]]

^<<v7-20-24,24>>^ Chegaram-se, pois, os filhos de Israel contra os filhos de Benjamim, no dia seguinte.

[[v7-20-25]]

^<<v7-20-25,25>>^ Também os de Benjamim, no dia seguinte, saíram de Gibeá de encontro a eles e derribaram ainda por terra mais dezoito mil homens, todos dos que puxavam da espada.

[[v7-20-26]]

^<<v7-20-26,26>>^ Então, todos os filhos de Israel, todo o povo, subiram, e vieram a Betel, e choraram, e estiveram ali perante o SENHOR, e jejuaram aquele dia até à tarde; e, perante o SENHOR, ofereceram holocaustos e ofertas pacíficas.

[[v7-20-27]]

^<<v7-20-27,27>>^ E os filhos de Israel perguntaram ao SENHOR (porquanto a arca da Aliança de Deus estava ali naqueles dias;

[[v7-20-28]]

^<<v7-20-28,28>>^ e Fineias, filho de Eleazar, filho de Arão, ministrava perante ela naqueles dias), dizendo: Tornaremos a sair ainda a pelejar contra os filhos de Benjamim, nosso irmão, ou desistiremos? Respondeu o SENHOR: Subi, que amanhã eu os entregarei nas vossas mãos.

[[v7-20-29]]

^<<v7-20-29,29>>^ Então, Israel pôs emboscadas em redor de Gibeá.

[[v7-20-30]]

^<<v7-20-30,30>>^ Ao terceiro dia, subiram os filhos de Israel contra os filhos de Benjamim e se ordenaram à peleja contra Gibeá, como das outras vezes.

[[v7-20-31]]

^<<v7-20-31,31>>^ Então, os filhos de Benjamim saíram de encontro ao povo, e, deixando-se atrair para longe da cidade, começaram a ferir alguns do povo, e mataram, como das outras vezes, uns trinta dos homens de Israel, pelas estradas, das quais uma sobe para Betel, a outra, para Gibeá do Campo.

[[v7-20-32]]

^<<v7-20-32,32>>^ Então, os filhos de Benjamim disseram: Vão derrotados diante de nós como dantes. Porém os filhos de Israel disseram: Fujamos e atraiamo-los da cidade para as estradas.

[[v7-20-33]]

^<<v7-20-33,33>>^ Todos os homens de Israel se levantaram do seu lugar e se ordenaram para a peleja em Baal-Tamar; e a emboscada de Israel saiu do seu lugar, das vizinhanças de Geba.

[[v7-20-34]]

^<<v7-20-34,34>>^ Dez mil homens escolhidos de todo o Israel vieram contra Gibeá, e a peleja se tornou renhida; porém eles não imaginavam que a calamidade lhes tocaria.

[[v7-20-35]]

^<<v7-20-35,35>>^ Então, feriu o SENHOR a Benjamim diante de Israel; e mataram os filhos de Israel, naquele dia, vinte e cinco mil e cem homens de Benjamim, todos dos que puxavam da espada;

[[v7-20-36]]

^<<v7-20-36,36>>^ assim, viram os filhos de Benjamim que estavam feridos. Os homens de Israel retiraram-se perante os benjamitas, porquanto estavam confiados na emboscada que haviam posto contra Gibeá.

[[v7-20-37]]

^<<v7-20-37,37>>^ A emboscada se apressou, e acometeu a Gibeá, e de golpe feriu-a toda a fio de espada.

[[v7-20-38]]

^<<v7-20-38,38>>^ Os homens de Israel tinham um sinal determinado com a emboscada, que era fazerem levantar da cidade uma grande nuvem de fumaça.

[[v7-20-39]]

^<<v7-20-39,39>>^ Então, os homens de Israel deviam voltar à peleja. Começara Benjamim a ferir e havia já matado uns trinta entre os homens de Israel, porque diziam: Com efeito, já estão derrotados diante de nós, como na peleja anterior.

[[v7-20-40]]

^<<v7-20-40,40>>^ Então, a nuvem de fumaça começou a levantar-se da cidade, como se fora uma coluna; virando-se Benjamim a olhar para trás de si, eis que toda a cidade subia em chamas para o céu.

[[v7-20-41]]

^<<v7-20-41,41>>^ Viraram os homens de Israel, e os de Benjamim pasmaram, porque viram que a calamidade lhes tocaria.

[[v7-20-42]]

^<<v7-20-42,42>>^ E viraram diante dos homens de Israel, para o caminho do deserto; porém a peleja os apertou; e os que vinham das cidades os destruíram no meio deles.

[[v7-20-43]]

^<<v7-20-43,43>>^ Cercaram a Benjamim, seguiram-no e, onde repousava, ali o alcançavam, até diante de Gibeá, para o nascente do sol.

[[v7-20-44]]

^<<v7-20-44,44>>^ Caíram de Benjamim dezoito mil homens, todos estes homens valentes.

[[v7-20-45]]

^<<v7-20-45,45>>^ Então, viraram e fugiram para o deserto, à penha Rimom; e, na respiga, mataram ainda pelos caminhos uns cinco mil homens, e de perto os seguiram até Gidom, e feriram deles dois mil homens.

[[v7-20-46]]

^<<v7-20-46,46>>^ Todos os que de Benjamim caíram, naquele dia, foram vinte e cinco mil homens que puxavam da espada, todos eles homens valentes.

[[v7-20-47]]

^<<v7-20-47,47>>^ Porém seiscentos homens viraram e fugiram para o deserto, à penha Rimom, onde ficaram quatro meses.

[[v7-20-48]]

^<<v7-20-48,48>>^ Os homens de Israel voltaram para os filhos de Benjamim e passaram a fio de espada tudo o que restou da cidade, tanto homens como animais, em suma, tudo o que encontraram; e também a todas as cidades que acharam puseram fogo.

'''

xref:007-juizes/007-juizes-019.adoc#v7-19-0[&#60; Capítulo Anterior] | <<v7-20-0,Topo>> | xref:007-juizes/007-juizes-021.adoc#v7-21-0[Próximo Capítulo &#62;]