include::./index.adoc[]

[[v7-8-0]]
=== Juízes, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v7-8-1]]

^<<v7-8-1,1>>^ Então, os homens de Efraim disseram a Gideão: Que é isto que nos fizeste, que não nos chamaste quando foste pelejar contra os midianitas? E contenderam fortemente com ele.

[[v7-8-2]]

^<<v7-8-2,2>>^ Porém ele lhes disse: Que mais fiz eu, agora, do que vós? Não são, porventura, os rabiscos de Efraim melhores do que a vindima de Abiezer?

[[v7-8-3]]

^<<v7-8-3,3>>^ Deus entregou nas vossas mãos os príncipes dos midianitas, Orebe e Zeebe; que pude eu fazer comparável com o que fizestes? Então, com falar-lhes esta palavra, abrandou-se-lhes a ira para com ele.

[[v7-8-4]]

^<<v7-8-4,4>>^ Vindo Gideão ao Jordão, passou com os trezentos homens que com ele estavam, cansados mas ainda perseguindo.

[[v7-8-5]]

^<<v7-8-5,5>>^ E disse aos homens de Sucote: Dai, peço-vos, alguns pães para estes que me seguem, pois estão cansados, e eu vou ao encalço de Zeba e Salmuna, reis dos midianitas.

[[v7-8-6]]

^<<v7-8-6,6>>^ Porém os príncipes de Sucote disseram: Porventura, tens já sob teu poder o punho de Zeba e de Salmuna, para que demos pão ao teu exército?

[[v7-8-7]]

^<<v7-8-7,7>>^ Então, disse Gideão: Por isso, quando o SENHOR entregar nas minhas mãos Zeba e Salmuna, trilharei a vossa carne com os espinhos do deserto e com os abrolhos.

[[v7-8-8]]

^<<v7-8-8,8>>^ Dali subiu a Penuel e de igual modo falou a seus homens; estes de Penuel lhe responderam como os homens de Sucote lhe haviam respondido.

[[v7-8-9]]

^<<v7-8-9,9>>^ Pelo que também falou aos homens de Penuel, dizendo: Quando eu voltar em paz, derribarei esta torre.

[[v7-8-10]]

^<<v7-8-10,10>>^ Estavam, pois, Zeba e Salmuna em Carcor, e os seus exércitos, com eles, uns quinze mil homens, todos os que restaram do exército de povos do Oriente; e os que caíram foram cento e vinte mil homens que puxavam da espada.

[[v7-8-11]]

^<<v7-8-11,11>>^ Subiu Gideão pelo caminho dos nômades, ao oriente de Noba e Jogbeá, e feriu aquele exército, que se achava descuidado.

[[v7-8-12]]

^<<v7-8-12,12>>^ Fugiram Zeba e Salmuna; porém ele os perseguiu, e prendeu os dois reis dos midianitas, Zeba e Salmuna, e desbaratou todo o exército.

[[v7-8-13]]

^<<v7-8-13,13>>^ Voltando, pois, Gideão, filho de Joás, da peleja, pela subida de Heres,

[[v7-8-14]]

^<<v7-8-14,14>>^ deteve a um moço de Sucote e lhe fez perguntas; o moço deu por escrito o nome dos príncipes e anciãos de Sucote, setenta e sete homens.

[[v7-8-15]]

^<<v7-8-15,15>>^ Então, veio Gideão aos homens de Sucote e disse: Vedes aqui Zeba e Salmuna, a respeito dos quais motejastes de mim, dizendo: Porventura, tens tu já sob teu poder o punho de Zeba e Salmuna para que demos pão aos teus homens cansados?

[[v7-8-16]]

^<<v7-8-16,16>>^ E tomou os anciãos da cidade, e espinhos do deserto, e abrolhos e, com eles, deu severa lição aos homens de Sucote.

[[v7-8-17]]

^<<v7-8-17,17>>^ Derribou a torre de Penuel e matou os homens da cidade.

[[v7-8-18]]

^<<v7-8-18,18>>^ Depois disse a Zeba e a Salmuna: Que homens eram os que matastes em Tabor? Responderam: Como tu és, assim eram eles; cada um se assemelhava a filho de rei.

[[v7-8-19]]

^<<v7-8-19,19>>^ Então, disse ele: Eram meus irmãos, filhos de minha mãe. Tão certo como vive o SENHOR, se os tivésseis deixado com vida, eu não vos mataria a vós outros.

[[v7-8-20]]

^<<v7-8-20,20>>^ E disse a Jéter, seu primogênito: Dispõe-te e mata-os. Porém o moço não arrancou da sua espada, porque temia, porquanto ainda era jovem.

[[v7-8-21]]

^<<v7-8-21,21>>^ Então, disseram Zeba e Salmuna: Levanta-te e arremete contra nós, porque qual o homem, tal a sua valentia. Dispôs-se, pois, Gideão, e matou a Zeba e a Salmuna, e tomou os ornamentos em forma de meia-lua que estavam no pescoço dos seus camelos.

[[v7-8-22]]

^<<v7-8-22,22>>^ Então, os homens de Israel disseram a Gideão: Domina sobre nós, tanto tu como teu filho e o filho de teu filho, porque nos livraste do poder dos midianitas.

[[v7-8-23]]

^<<v7-8-23,23>>^ Porém Gideão lhes disse: Não dominarei sobre vós, nem tampouco meu filho dominará sobre vós; o SENHOR vos dominará.

[[v7-8-24]]

^<<v7-8-24,24>>^ Disse-lhes mais Gideão: Um pedido vos farei: dai-me vós, cada um as argolas do seu despojo (porque tinham argolas de ouro, pois eram ismaelitas).

[[v7-8-25]]

^<<v7-8-25,25>>^ Disseram eles: De bom grado as daremos. E estenderam uma capa, e cada um deles deitou ali uma argola do seu despojo.

[[v7-8-26]]

^<<v7-8-26,26>>^ O peso das argolas de ouro que pediu foram mil e setecentos siclos de ouro (afora os ornamentos em forma de meia-lua, as arrecadas e as vestes de púrpura que traziam os reis dos midianitas, e afora os ornamentos que os camelos traziam ao pescoço).

[[v7-8-27]]

^<<v7-8-27,27>>^ Desse peso fez Gideão uma estola sacerdotal e a pôs na sua cidade, em Ofra; e todo o Israel se prostituiu ali após ela; a estola veio a ser um laço a Gideão e à sua casa.

[[v7-8-28]]

^<<v7-8-28,28>>^ Assim, foram abatidos os midianitas diante dos filhos de Israel e nunca mais levantaram a cabeça; e ficou a terra em paz durante quarenta anos nos dias de Gideão.

[[v7-8-29]]

^<<v7-8-29,29>>^ Retirou-se Jerubaal, filho de Joás, e habitou em sua casa.

[[v7-8-30]]

^<<v7-8-30,30>>^ Teve Gideão setenta filhos, todos provindos dele, porque tinha muitas mulheres.

[[v7-8-31]]

^<<v7-8-31,31>>^ A sua concubina, que estava em Siquém, lhe deu também à luz um filho; e ele lhe pôs por nome Abimeleque.

[[v7-8-32]]

^<<v7-8-32,32>>^ Faleceu Gideão, filho de Joás, em boa velhice; e foi sepultado no sepulcro de Joás, seu pai, em Ofra dos abiezritas.

[[v7-8-33]]

^<<v7-8-33,33>>^ Morto Gideão, tornaram a prostituir-se os filhos de Israel após os baalins e puseram Baal-Berite por deus.

[[v7-8-34]]

^<<v7-8-34,34>>^ Os filhos de Israel não se lembraram do SENHOR, seu Deus, que os livrara do poder de todos os seus inimigos ao redor;

[[v7-8-35]]

^<<v7-8-35,35>>^ nem usaram de benevolência com a casa de Jerubaal, a saber, Gideão, segundo todo o bem que ele fizera a Israel.

'''

xref:007-juizes/007-juizes-007.adoc#v7-7-0[&#60; Capítulo Anterior] | <<v7-8-0,Topo>> | xref:007-juizes/007-juizes-009.adoc#v7-9-0[Próximo Capítulo &#62;]