include::./index.adoc[]

[[v7-5-0]]
=== Juízes, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v7-5-1]]

^<<v7-5-1,1>>^ Naquele dia, cantaram Débora e Baraque, filho de Abinoão, dizendo:

[[v7-5-2]]

^<<v7-5-2,2>>^ Desde que os chefes se puseram à frente de Israel, e o povo se ofereceu voluntariamente, bendizei ao SENHOR.

[[v7-5-3]]

^<<v7-5-3,3>>^ Ouvi, reis, dai ouvidos, príncipes: eu, eu mesma cantarei ao SENHOR; salmodiarei ao SENHOR, Deus de Israel.

[[v7-5-4]]

^<<v7-5-4,4>>^ Saindo tu, ó SENHOR, de Seir, marchando desde o campo de Edom, a terra estremeceu; os céus gotejaram, sim, até as nuvens gotejaram águas.

[[v7-5-5]]

^<<v7-5-5,5>>^ Os montes vacilaram diante do SENHOR, e até o Sinai, diante do SENHOR, Deus de Israel.

[[v7-5-6]]

^<<v7-5-6,6>>^ Nos dias de Sangar, filho de Anate, nos dias de Jael, cessaram as caravanas; e os viajantes tomavam desvios tortuosos.

[[v7-5-7]]

^<<v7-5-7,7>>^ Ficaram desertas as aldeias em Israel, repousaram, até que eu, Débora, me levantei, levantei-me por mãe em Israel.

[[v7-5-8]]

^<<v7-5-8,8>>^ Escolheram-se deuses novos; então, a guerra estava às portas; não se via escudo nem lança entre quarenta mil em Israel.

[[v7-5-9]]

^<<v7-5-9,9>>^ Meu coração se inclina para os comandantes de Israel, que, voluntariamente, se ofereceram entre o povo; bendizei ao SENHOR.

[[v7-5-10]]

^<<v7-5-10,10>>^ Vós, os que cavalgais jumentas brancas, que vos assentais em juízo e que andais pelo caminho, falai disto.

[[v7-5-11]]

^<<v7-5-11,11>>^ À música dos distribuidores de água, lá entre os canais dos rebanhos, falai dos atos de justiça do SENHOR, das justiças a prol de suas aldeias em Israel. Então, o povo do Senhor pôde descer ao seu lar.

[[v7-5-12]]

^<<v7-5-12,12>>^ Desperta, Débora, desperta, desperta, acorda, entoa um cântico; levanta-te, Baraque, e leva presos os que te prenderam, tu, filho de Abinoão.

[[v7-5-13]]

^<<v7-5-13,13>>^ Então, desceu o restante dos nobres, o povo do SENHOR em meu auxílio contra os poderosos.

[[v7-5-14]]

^<<v7-5-14,14>>^ De Efraim, cujas raízes estão na antiga região de Amaleque, desceram guerreiros; depois de ti, ó Débora, seguiu Benjamim com seus povos; de Maquir desceram comandantes, e, de Zebulom, os que levam a vara de comando.

[[v7-5-15]]

^<<v7-5-15,15>>^ Também os príncipes de Issacar foram com Débora; Issacar seguiu a Baraque, em cujas pegadas foi enviado para o vale. Entre as facções de Rúben houve grande discussão.

[[v7-5-16]]

^<<v7-5-16,16>>^ Por que ficaste entre os currais para ouvires a flauta? Entre as facções de Rúben houve grande discussão.

[[v7-5-17]]

^<<v7-5-17,17>>^ Gileade ficou dalém do Jordão, e Dã, por que se deteve junto a seus navios? Aser se assentou nas costas do mar e repousou nas suas baías.

[[v7-5-18]]

^<<v7-5-18,18>>^ Zebulom é povo que expôs a sua vida à morte, como também Naftali, nas alturas do campo.

[[v7-5-19]]

^<<v7-5-19,19>>^ Vieram reis e pelejaram; pelejaram os reis de Canaã em Taanaque, junto às águas de Megido; porém não levaram nenhum despojo de prata.

[[v7-5-20]]

^<<v7-5-20,20>>^ Desde os céus pelejaram as estrelas contra Sísera, desde a sua órbita o fizeram.

[[v7-5-21]]

^<<v7-5-21,21>>^ O ribeiro Quisom os arrastou, Quisom, o ribeiro das batalhas. Avante, ó minha alma, firme!

[[v7-5-22]]

^<<v7-5-22,22>>^ Então, as unhas dos cavalos socavam pelo galopar, o galopar dos seus guerreiros.

[[v7-5-23]]

^<<v7-5-23,23>>^ Amaldiçoai a Meroz, diz o Anjo do SENHOR, amaldiçoai duramente os seus moradores, porque não vieram em socorro do SENHOR, em socorro do SENHOR e seus heróis.

[[v7-5-24]]

^<<v7-5-24,24>>^ Bendita seja sobre as mulheres Jael, mulher de Héber, o queneu; bendita seja sobre as mulheres que vivem em tendas.

[[v7-5-25]]

^<<v7-5-25,25>>^ Água pediu ele, leite lhe deu ela; em taça de príncipes lhe ofereceu nata.

[[v7-5-26]]

^<<v7-5-26,26>>^ À estaca estendeu a mão e, ao maço dos trabalhadores, a direita; e deu o golpe em Sísera, rachou-lhe a cabeça, furou e traspassou-lhe as fontes.

[[v7-5-27]]

^<<v7-5-27,27>>^ Aos pés dela se encurvou, caiu e ficou estirado; a seus pés se encurvou e caiu; onde se encurvou, ali caiu morto.

[[v7-5-28]]

^<<v7-5-28,28>>^ A mãe de Sísera olhava pela janela e exclamava pela grade: Por que tarda em vir o seu carro? Por que se demoram os passos dos seus cavalos?

[[v7-5-29]]

^<<v7-5-29,29>>^ As mais sábias das suas damas respondem, e até ela a si mesma respondia:

[[v7-5-30]]

^<<v7-5-30,30>>^ Porventura, não achariam e repartiriam despojos? Uma ou duas moças, a cada homem? Para Sísera, estofos de várias cores, estofos de várias cores de bordados; um ou dois estofos bordados, para o pescoço da esposa?

[[v7-5-31]]

^<<v7-5-31,31>>^ Assim, ó SENHOR, pereçam todos os teus inimigos! Porém os que te amam brilham como o sol quando se levanta no seu esplendor. E a terra ficou em paz quarenta anos.

'''

xref:007-juizes/007-juizes-004.adoc#v7-4-0[&#60; Capítulo Anterior] | <<v7-5-0,Topo>> | xref:007-juizes/007-juizes-006.adoc#v7-6-0[Próximo Capítulo &#62;]