include::./index.adoc[]

[[v7-9-0]]
=== Juízes, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v7-9-1]]

^<<v7-9-1,1>>^ Abimeleque, filho de Jerubaal, foi-se a Siquém, aos irmãos de sua mãe, e falou-lhes e a toda a geração da casa do pai de sua mãe, dizendo:

[[v7-9-2]]

^<<v7-9-2,2>>^ Falai, peço-vos, aos ouvidos de todos os cidadãos de Siquém: Que vos parece melhor: que setenta homens, todos os filhos de Jerubaal, dominem sobre vós ou que apenas um domine sobre vós? Lembrai-vos também de que sou osso vosso e carne vossa.

[[v7-9-3]]

^<<v7-9-3,3>>^ Então, os irmãos de sua mãe falaram a todos os cidadãos de Siquém todas aquelas palavras; e o coração deles se inclinou a seguir Abimeleque, porque disseram: É nosso irmão.

[[v7-9-4]]

^<<v7-9-4,4>>^ E deram-lhe setenta peças de prata, da casa de Baal-Berite, com as quais alugou Abimeleque uns homens levianos e atrevidos, que o seguiram.

[[v7-9-5]]

^<<v7-9-5,5>>^ Foi à casa de seu pai, a Ofra, e matou seus irmãos, os filhos de Jerubaal, setenta homens, sobre uma pedra. Porém Jotão, filho menor de Jerubaal, ficou, porque se escondera.

[[v7-9-6]]

^<<v7-9-6,6>>^ Então, se ajuntaram todos os cidadãos de Siquém e toda Bete-Milo; e foram e proclamaram Abimeleque rei, junto ao carvalho memorial que está perto de Siquém.

[[v7-9-7]]

^<<v7-9-7,7>>^ Avisado disto, Jotão foi, e se pôs no cimo do monte Gerizim, e em alta voz clamou, e disse-lhes: Ouvi-me, cidadãos de Siquém, e Deus vos ouvirá a vós outros.

[[v7-9-8]]

^<<v7-9-8,8>>^ Foram, certa vez, as árvores ungir para si um rei e disseram à oliveira: Reina sobre nós.

[[v7-9-9]]

^<<v7-9-9,9>>^ Porém a oliveira lhes respondeu: Deixaria eu o meu óleo, que Deus e os homens em mim prezam, e iria pairar sobre as árvores?

[[v7-9-10]]

^<<v7-9-10,10>>^ Então, disseram as árvores à figueira: Vem tu e reina sobre nós.

[[v7-9-11]]

^<<v7-9-11,11>>^ Porém a figueira lhes respondeu: Deixaria eu a minha doçura, o meu bom fruto e iria pairar sobre as árvores?

[[v7-9-12]]

^<<v7-9-12,12>>^ Então, disseram as árvores à videira: Vem tu e reina sobre nós.

[[v7-9-13]]

^<<v7-9-13,13>>^ Porém a videira lhes respondeu: Deixaria eu o meu vinho, que agrada a Deus e aos homens, e iria pairar sobre as árvores?

[[v7-9-14]]

^<<v7-9-14,14>>^ Então, todas as árvores disseram ao espinheiro: Vem tu e reina sobre nós.

[[v7-9-15]]

^<<v7-9-15,15>>^ Respondeu o espinheiro às árvores: Se, deveras, me ungis rei sobre vós, vinde e refugiai-vos debaixo de minha sombra; mas, se não, saia do espinheiro fogo que consuma os cedros do Líbano.

[[v7-9-16]]

^<<v7-9-16,16>>^ Agora, pois, se, deveras e sinceramente, procedestes, proclamando rei Abimeleque, e se bem vos portastes para com Jerubaal e para com a sua casa, e se com ele agistes segundo o merecimento dos seus feitos

[[v7-9-17]]

^<<v7-9-17,17>>^ (porque meu pai pelejou por vós e, arriscando a vida, vos livrou das mãos dos midianitas;

[[v7-9-18]]

^<<v7-9-18,18>>^ porém vós, hoje, vos levantastes contra a casa de meu pai e matastes seus filhos, setenta homens, sobre uma pedra; e a Abimeleque, filho de sua serva, fizestes reinar sobre os cidadãos de Siquém, porque é vosso irmão),

[[v7-9-19]]

^<<v7-9-19,19>>^ se, deveras e sinceramente, procedestes, hoje, com Jerubaal e com a sua casa, alegrai-vos com Abimeleque, e também ele se alegre convosco.

[[v7-9-20]]

^<<v7-9-20,20>>^ Mas, se não, saia fogo de Abimeleque e consuma os cidadãos de Siquém e Bete-Milo; e saia fogo dos cidadãos de Siquém e de Bete-Milo, que consuma a Abimeleque.

[[v7-9-21]]

^<<v7-9-21,21>>^ Fugiu logo Jotão, e foi-se para Beer, e ali habitou por temer seu irmão Abimeleque.

[[v7-9-22]]

^<<v7-9-22,22>>^ Havendo, pois, Abimeleque dominado três anos sobre Israel,

[[v7-9-23]]

^<<v7-9-23,23>>^ suscitou Deus um espírito de aversão entre Abimeleque e os cidadãos de Siquém; e estes se houveram aleivosamente contra Abimeleque,

[[v7-9-24]]

^<<v7-9-24,24>>^ para que a vingança da violência praticada contra os setenta filhos de Jerubaal viesse, e o seu sangue caísse sobre Abimeleque, seu irmão, que os matara, e sobre os cidadãos de Siquém, que contribuíram para que ele matasse seus próprios irmãos.

[[v7-9-25]]

^<<v7-9-25,25>>^ Os cidadãos de Siquém puseram contra ele homens de emboscada sobre os cimos dos montes; e todo aquele que passava pelo caminho junto a eles, eles o assaltavam; e isto se contou a Abimeleque.

[[v7-9-26]]

^<<v7-9-26,26>>^ Veio também Gaal, filho de Ebede, com seus irmãos, e se estabeleceram em Siquém; e os cidadãos de Siquém confiaram nele,

[[v7-9-27]]

^<<v7-9-27,27>>^ e saíram ao campo, e vindimaram as suas vinhas, e pisaram as uvas, e fizeram festas, e foram à casa de seu deus, e comeram, e beberam, e amaldiçoaram Abimeleque.

[[v7-9-28]]

^<<v7-9-28,28>>^ Disse Gaal, filho de Ebede: Quem é Abimeleque, e quem somos nós de Siquém, para que o sirvamos? Não é, porventura, filho de Jerubaal? E não é Zebul o seu oficial? Servi, antes, aos homens de Hamor, pai de Siquém. Mas nós, por que serviremos a ele?

[[v7-9-29]]

^<<v7-9-29,29>>^ Quem dera estivesse este povo sob a minha mão, e eu expulsaria Abimeleque e lhe diria: Multiplica o teu exército e sai.

[[v7-9-30]]

^<<v7-9-30,30>>^ Ouvindo Zebul, governador da cidade, as palavras de Gaal, filho de Ebede, se acendeu em ira;

[[v7-9-31]]

^<<v7-9-31,31>>^ e enviou, astutamente, mensageiros a Abimeleque, dizendo: Eis que Gaal, filho de Ebede, e seus irmãos vieram a Siquém e alvoroçaram a cidade contra ti.

[[v7-9-32]]

^<<v7-9-32,32>>^ Levanta-te, pois, de noite, tu e o povo que tiveres contigo, e ponde-vos de emboscada no campo.

[[v7-9-33]]

^<<v7-9-33,33>>^ Levanta-te pela manhã, ao sair o sol, e dá de golpe sobre a cidade; saindo contra ti Gaal com a sua gente, procede com ele como puderes.

[[v7-9-34]]

^<<v7-9-34,34>>^ Levantou-se, pois, de noite, Abimeleque e todo o povo que com ele estava, e se puseram de emboscada contra Siquém, em quatro grupos.

[[v7-9-35]]

^<<v7-9-35,35>>^ Gaal, filho de Ebede, saiu e pôs-se à entrada da porta da cidade; com isto Abimeleque e todo o povo que com ele estava se levantaram das emboscadas.

[[v7-9-36]]

^<<v7-9-36,36>>^ Vendo Gaal aquele povo, disse a Zebul: Eis que desce gente dos cimos dos montes. Zebul, ao contrário, lhe disse: As sombras dos montes vês por homens.

[[v7-9-37]]

^<<v7-9-37,37>>^ Porém Gaal tornou ainda a falar e disse: Eis ali desce gente defronte de nós, e uma tropa vem do caminho do carvalho dos Adivinhadores.

[[v7-9-38]]

^<<v7-9-38,38>>^ Então, lhe disse Zebul: Onde está, agora, a tua boca, com a qual dizias: Quem é Abimeleque, para que o sirvamos? Não é este, porventura, o povo que desprezaste? Sai, pois, e peleja contra ele.

[[v7-9-39]]

^<<v7-9-39,39>>^ Saiu Gaal adiante dos cidadãos de Siquém e pelejou contra Abimeleque.

[[v7-9-40]]

^<<v7-9-40,40>>^ Abimeleque o perseguiu; Gaal fugiu de diante dele, e muitos feridos caíram até a entrada da porta da cidade.

[[v7-9-41]]

^<<v7-9-41,41>>^ Abimeleque ficou em Arumá. E Zebul expulsou a Gaal e seus irmãos, para que não habitassem em Siquém.

[[v7-9-42]]

^<<v7-9-42,42>>^ No dia seguinte, saiu o povo ao campo; disto foi avisado Abimeleque,

[[v7-9-43]]

^<<v7-9-43,43>>^ que tomou os seus homens, e os repartiu em três grupos, e os pôs de emboscada no campo. Olhando, viu que o povo saía da cidade; então, se levantou contra eles e os feriu.

[[v7-9-44]]

^<<v7-9-44,44>>^ Abimeleque e o grupo que com ele estava romperam de improviso e tomaram posição à porta da cidade, enquanto os dois outros grupos deram de golpe sobre todos quantos estavam no campo e os destroçaram.

[[v7-9-45]]

^<<v7-9-45,45>>^ Todo aquele dia pelejou Abimeleque contra a cidade e a tomou. Matou o povo que nela havia, assolou-a e a semeou de sal.

[[v7-9-46]]

^<<v7-9-46,46>>^ Tendo ouvido isto todos os cidadãos da Torre de Siquém, entraram na fortaleza subterrânea, no templo de El-Berite.

[[v7-9-47]]

^<<v7-9-47,47>>^ Contou-se a Abimeleque que todos os cidadãos da Torre de Siquém se haviam congregado.

[[v7-9-48]]

^<<v7-9-48,48>>^ Então, subiu ele ao monte Salmom, ele e todo o seu povo; Abimeleque tomou de um machado, e cortou uma ramada de árvore, e a levantou, e pô-la ao ombro, e disse ao povo que com ele estava: O que me vistes fazer, fazei-o também vós, depressa.

[[v7-9-49]]

^<<v7-9-49,49>>^ Assim, cada um de todo o povo cortou a sua ramada, e seguiram Abimeleque, e as puseram em cima da fortaleza subterrânea, e queimaram sobre todos os da Torre de Siquém, de maneira que morreram todos, uns mil homens e mulheres.

[[v7-9-50]]

^<<v7-9-50,50>>^ Então, se foi Abimeleque a Tebes, e a sitiou, e a tomou.

[[v7-9-51]]

^<<v7-9-51,51>>^ Havia, porém, no meio da cidade, uma torre forte; e todos os homens e mulheres, todos os moradores da cidade, se acolheram a ela, e fecharam após si as portas da torre, e subiram ao seu eirado.

[[v7-9-52]]

^<<v7-9-52,52>>^ Abimeleque veio até à torre, pelejou contra ela e se chegou até à sua porta para a incendiar.

[[v7-9-53]]

^<<v7-9-53,53>>^ Porém certa mulher lançou uma pedra superior de moinho sobre a cabeça de Abimeleque e lhe quebrou o crânio.

[[v7-9-54]]

^<<v7-9-54,54>>^ Então, chamou logo ao moço, seu escudeiro, e lhe disse: Desembainha a tua espada e mata-me, para que não se diga de mim: Mulher o matou. O moço o atravessou, e ele morreu.

[[v7-9-55]]

^<<v7-9-55,55>>^ Vendo, pois, os homens de Israel que Abimeleque já estava morto, foram-se, cada um para sua casa.

[[v7-9-56]]

^<<v7-9-56,56>>^ Assim, Deus fez tornar sobre Abimeleque o mal que fizera a seu pai, por ter aquele matado os seus setenta irmãos.

[[v7-9-57]]

^<<v7-9-57,57>>^ De igual modo, todo o mal dos homens de Siquém Deus fez cair sobre a cabeça deles. Assim, veio sobre eles a maldição de Jotão, filho de Jerubaal.

'''

xref:007-juizes/007-juizes-008.adoc#v7-8-0[&#60; Capítulo Anterior] | <<v7-9-0,Topo>> | xref:007-juizes/007-juizes-010.adoc#v7-10-0[Próximo Capítulo &#62;]