include::./index.adoc[]

[[v7-6-0]]
=== Juízes, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v7-6-1]]

^<<v7-6-1,1>>^ Fizeram os filhos de Israel o que era mau perante o SENHOR; por isso, o SENHOR os entregou nas mãos dos midianitas por sete anos.

[[v7-6-2]]

^<<v7-6-2,2>>^ Prevalecendo o domínio dos midianitas sobre Israel, fizeram estes para si, por causa dos midianitas, as covas que estão nos montes, e as cavernas, e as fortificações.

[[v7-6-3]]

^<<v7-6-3,3>>^ Porque, cada vez que Israel semeava, os midianitas e os amalequitas, como também os povos do Oriente, subiam contra ele.

[[v7-6-4]]

^<<v7-6-4,4>>^ E contra ele se acampavam, destruindo os produtos da terra até à vizinhança de Gaza, e não deixavam em Israel sustento algum, nem ovelhas, nem bois, nem jumentos.

[[v7-6-5]]

^<<v7-6-5,5>>^ Pois subiam com os seus gados e tendas e vinham como gafanhotos, em tanta multidão, que não se podiam contar, nem a eles nem aos seus camelos; e entravam na terra para a destruir.

[[v7-6-6]]

^<<v7-6-6,6>>^ Assim, Israel ficou muito debilitado com a presença dos midianitas; então, os filhos de Israel clamavam ao SENHOR.

[[v7-6-7]]

^<<v7-6-7,7>>^ Tendo os filhos de Israel clamado ao SENHOR, por causa dos midianitas,

[[v7-6-8]]

^<<v7-6-8,8>>^ o SENHOR lhes enviou um profeta, que lhes disse: Assim diz o SENHOR, Deus de Israel: Eu é que vos fiz subir do Egito e vos tirei da casa da servidão;

[[v7-6-9]]

^<<v7-6-9,9>>^ e vos livrei da mão dos egípcios e da mão de todos quantos vos oprimiam; e os expulsei de diante de vós e vos dei a sua terra;

[[v7-6-10]]

^<<v7-6-10,10>>^ e disse: Eu sou o SENHOR, vosso Deus; não temais os deuses dos amorreus, em cuja terra habitais; contudo, não destes ouvidos à minha voz.

[[v7-6-11]]

^<<v7-6-11,11>>^ Então, veio o Anjo do SENHOR, e assentou-se debaixo do carvalho que está em Ofra, que pertencia a Joás, abiezrita; e Gideão, seu filho, estava malhando o trigo no lagar, para o pôr a salvo dos midianitas.

[[v7-6-12]]

^<<v7-6-12,12>>^ Então, o Anjo do SENHOR lhe apareceu e lhe disse: O SENHOR é contigo, homem valente.

[[v7-6-13]]

^<<v7-6-13,13>>^ Respondeu-lhe Gideão: Ai, senhor meu! Se o SENHOR é conosco, por que nos sobreveio tudo isto? E que é feito de todas as suas maravilhas que nossos pais nos contaram, dizendo: Não nos fez o SENHOR subir do Egito? Porém, agora, o SENHOR nos desamparou e nos entregou nas mãos dos midianitas.

[[v7-6-14]]

^<<v7-6-14,14>>^ Então, se virou o SENHOR para ele e disse: Vai nessa tua força e livra Israel da mão dos midianitas; porventura, não te enviei eu?

[[v7-6-15]]

^<<v7-6-15,15>>^ E ele lhe disse: Ai, Senhor meu! Com que livrarei Israel? Eis que a minha família é a mais pobre em Manassés, e eu, o menor na casa de meu pai.

[[v7-6-16]]

^<<v7-6-16,16>>^ Tornou-lhe o SENHOR: Já que eu estou contigo, ferirás os midianitas como se fossem um só homem.

[[v7-6-17]]

^<<v7-6-17,17>>^ Ele respondeu: Se, agora, achei mercê diante dos teus olhos, dá-me um sinal de que és tu, SENHOR, que me falas.

[[v7-6-18]]

^<<v7-6-18,18>>^ Rogo-te que daqui não te apartes até que eu volte, e traga a minha oferta, e a deponha perante ti. Respondeu ele: Esperarei até que voltes.

[[v7-6-19]]

^<<v7-6-19,19>>^ Entrou Gideão e preparou um cabrito e bolos asmos de um efa de farinha; a carne pôs num cesto, e o caldo, numa panela; e trouxe-lho até debaixo do carvalho e lho apresentou.

[[v7-6-20]]

^<<v7-6-20,20>>^ Porém o Anjo de Deus lhe disse: Toma a carne e os bolos asmos, põe-nos sobre esta penha e derrama-lhes por cima o caldo. E assim o fez.

[[v7-6-21]]

^<<v7-6-21,21>>^ Estendeu o Anjo do SENHOR a ponta do cajado que trazia na mão e tocou a carne e os bolos asmos; então, subiu fogo da penha e consumiu a carne e os bolos; e o Anjo do SENHOR desapareceu de sua presença.

[[v7-6-22]]

^<<v7-6-22,22>>^ Viu Gideão que era o Anjo do SENHOR e disse: Ai de mim, SENHOR Deus! Pois vi o Anjo do SENHOR face a face.

[[v7-6-23]]

^<<v7-6-23,23>>^ Porém o SENHOR lhe disse: Paz seja contigo! Não temas! Não morrerás!

[[v7-6-24]]

^<<v7-6-24,24>>^ Então, Gideão edificou ali um altar ao SENHOR e lhe chamou de O SENHOR É Paz. Ainda até ao dia de hoje está o altar em Ofra, que pertence aos abiezritas.

[[v7-6-25]]

^<<v7-6-25,25>>^ Naquela mesma noite, lhe disse o SENHOR: Toma um boi que pertence a teu pai, a saber, o segundo boi de sete anos, e derriba o altar de Baal que é de teu pai, e corta o poste-ídolo que está junto ao altar.

[[v7-6-26]]

^<<v7-6-26,26>>^ Edifica ao SENHOR, teu Deus, um altar no cimo deste baluarte, em camadas de pedra, e toma o segundo boi, e o oferecerás em holocausto com a lenha do poste-ídolo que vieres a cortar.

[[v7-6-27]]

^<<v7-6-27,27>>^ Então, Gideão tomou dez homens dentre os seus servos e fez como o SENHOR lhe dissera; temendo ele, porém, a casa de seu pai e os homens daquela cidade, não o fez de dia, mas de noite.

[[v7-6-28]]

^<<v7-6-28,28>>^ Levantando-se, pois, de madrugada, os homens daquela cidade, eis que estava o altar de Baal derribado, e o poste-ídolo que estava junto dele, cortado; e o referido segundo boi fora oferecido no altar edificado.

[[v7-6-29]]

^<<v7-6-29,29>>^ E uns aos outros diziam: Quem fez isto? E, perguntando e inquirindo, disseram: Gideão, o filho de Joás, fez esta coisa.

[[v7-6-30]]

^<<v7-6-30,30>>^ Então, os homens daquela cidade disseram a Joás: Leva para fora o teu filho, para que morra; pois derribou o altar de Baal e cortou o poste-ídolo que estava junto dele.

[[v7-6-31]]

^<<v7-6-31,31>>^ Porém Joás disse a todos os que se puseram contra ele: Contendereis vós por Baal? Livrá-lo-eis vós? Qualquer que por ele contender, ainda esta manhã, será morto. Se é deus, que por si mesmo contenda; pois derribaram o seu altar.

[[v7-6-32]]

^<<v7-6-32,32>>^ Naquele dia, Gideão passou a ser chamado Jerubaal, porque foi dito: Baal contenda contra ele, pois ele derribou o seu altar.

[[v7-6-33]]

^<<v7-6-33,33>>^ E todos os midianitas, e amalequitas, e povos do Oriente se ajuntaram, e passaram, e se acamparam no vale de Jezreel.

[[v7-6-34]]

^<<v7-6-34,34>>^ Então, o Espírito do SENHOR revestiu a Gideão, o qual tocou a rebate, e os abiezritas se ajuntaram após dele.

[[v7-6-35]]

^<<v7-6-35,35>>^ Enviou mensageiros por toda a tribo de Manassés, que também foi convocada para o seguir; enviou ainda mensageiros a Aser, e a Zebulom, e a Naftali, e saíram para encontrar-se com ele.

[[v7-6-36]]

^<<v7-6-36,36>>^ Disse Gideão a Deus: Se hás de livrar a Israel por meu intermédio, como disseste,

[[v7-6-37]]

^<<v7-6-37,37>>^ eis que eu porei uma porção de lã na eira; se o orvalho estiver somente nela, e seca a terra ao redor, então, conhecerei que hás de livrar Israel por meu intermédio, como disseste.

[[v7-6-38]]

^<<v7-6-38,38>>^ E assim sucedeu, porque, ao outro dia, se levantou de madrugada e, apertando a lã, do orvalho dela espremeu uma taça cheia de água.

[[v7-6-39]]

^<<v7-6-39,39>>^ Disse mais Gideão: Não se acenda contra mim a tua ira, se ainda falar só esta vez; rogo-te que mais esta vez faça eu a prova com a lã; que só a lã esteja seca, e na terra ao redor haja orvalho.

[[v7-6-40]]

^<<v7-6-40,40>>^ E Deus assim o fez naquela noite, pois só a lã estava seca, e sobre a terra ao redor havia orvalho.

'''

xref:007-juizes/007-juizes-005.adoc#v7-5-0[&#60; Capítulo Anterior] | <<v7-6-0,Topo>> | xref:007-juizes/007-juizes-007.adoc#v7-7-0[Próximo Capítulo &#62;]