include::./index.adoc[]

[[v29-1-0]]
=== Joel, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v29-1-1]]

^<<v29-1-1,1>>^ Palavra do SENHOR que foi dirigida a Joel, filho de Petuel.

[[v29-1-2]]

^<<v29-1-2,2>>^ Ouvi isto, vós, velhos, e escutai, todos os habitantes da terra: Aconteceu isto em vossos dias? Ou nos dias de vossos pais?

[[v29-1-3]]

^<<v29-1-3,3>>^ Narrai isto a vossos filhos, e vossos filhos o façam a seus filhos, e os filhos destes, à outra geração.

[[v29-1-4]]

^<<v29-1-4,4>>^ O que deixou o gafanhoto cortador, comeu-o o gafanhoto migrador; o que deixou o migrador, comeu-o o gafanhoto devorador; o que deixou o devorador, comeu-o o gafanhoto destruidor.

[[v29-1-5]]

^<<v29-1-5,5>>^ Ébrios, despertai-vos e chorai; uivai, todos os que bebeis vinho, por causa do mosto, porque está ele tirado da vossa boca.

[[v29-1-6]]

^<<v29-1-6,6>>^ Porque veio um povo contra a minha terra, poderoso e inumerável; os seus dentes são dentes de leão, e ele tem os queixais de uma leoa.

[[v29-1-7]]

^<<v29-1-7,7>>^ Fez de minha vide uma assolação, destroçou a minha figueira, tirou-lhe a casca, que lançou por terra; os seus sarmentos se fizeram brancos.

[[v29-1-8]]

^<<v29-1-8,8>>^ Lamenta com a virgem que, pelo marido da sua mocidade, está cingida de pano de saco.

[[v29-1-9]]

^<<v29-1-9,9>>^ Cortada está da Casa do SENHOR a oferta de manjares e a libação; os sacerdotes, ministros do SENHOR, estão enlutados.

[[v29-1-10]]

^<<v29-1-10,10>>^ O campo está assolado, e a terra, de luto, porque o cereal está destruído, a vide se secou, as olivas se murcharam.

[[v29-1-11]]

^<<v29-1-11,11>>^ Envergonhai-vos, lavradores, uivai, vinhateiros, sobre o trigo e sobre a cevada, porque pereceu a messe do campo.

[[v29-1-12]]

^<<v29-1-12,12>>^ A vide se secou, a figueira se murchou, a romeira também, e a palmeira e a macieira; todas as árvores do campo se secaram, e já não há alegria entre os filhos dos homens.

[[v29-1-13]]

^<<v29-1-13,13>>^ Cingi-vos de pano de saco e lamentai, sacerdotes; uivai, ministros do altar; vinde, ministros de meu Deus; passai a noite vestidos de panos de saco; porque da casa de vosso Deus foi cortada a oferta de manjares e a libação.

[[v29-1-14]]

^<<v29-1-14,14>>^ Promulgai um santo jejum, convocai uma assembleia solene, congregai os anciãos, todos os moradores desta terra, para a Casa do SENHOR, vosso Deus, e clamai ao SENHOR.

[[v29-1-15]]

^<<v29-1-15,15>>^ Ah! Que dia! Porque o Dia do SENHOR está perto e vem como assolação do Todo-Poderoso.

[[v29-1-16]]

^<<v29-1-16,16>>^ Acaso, não está destruído o mantimento diante dos vossos olhos? E, da casa do nosso Deus, a alegria e o regozijo?

[[v29-1-17]]

^<<v29-1-17,17>>^ A semente mirrou debaixo dos seus torrões, os celeiros foram assolados, os armazéns, derribados, porque se perdeu o cereal.

[[v29-1-18]]

^<<v29-1-18,18>>^ Como geme o gado! As manadas de bois estão sobremodo inquietas, porque não têm pasto; também os rebanhos de ovelhas estão perecendo.

[[v29-1-19]]

^<<v29-1-19,19>>^ A ti, ó SENHOR, clamo, porque o fogo consumiu os pastos do deserto, e a chama abrasou todas as árvores do campo.

[[v29-1-20]]

^<<v29-1-20,20>>^ Também todos os animais do campo bramam suspirantes por ti; porque os rios se secaram, e o fogo devorou os pastos do deserto.

'''

xref:028-oseias/028-oseias-014.adoc#v28-14-0[&#60; Capítulo Anterior] | <<v29-1-0,Topo>> | xref:029-joel/029-joel-002.adoc#v29-2-0[Próximo Capítulo &#62;]