include::./index.adoc[]

[[v29-3-0]]
=== Joel, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v29-3-1]]

^<<v29-3-1,1>>^ Eis que, naqueles dias e naquele tempo, em que mudarei a sorte de Judá e de Jerusalém,

[[v29-3-2]]

^<<v29-3-2,2>>^ congregarei todas as nações e as farei descer ao vale de Josafá; e ali entrarei em juízo contra elas por causa do meu povo e da minha herança, Israel, a quem elas espalharam por entre os povos, repartindo a minha terra entre si.

[[v29-3-3]]

^<<v29-3-3,3>>^ Lançaram sortes sobre o meu povo, e deram meninos por meretrizes, e venderam meninas por vinho, que beberam.

[[v29-3-4]]

^<<v29-3-4,4>>^ Que tendes vós comigo, Tiro, e Sidom, e todas as regiões da Filístia? É isso vingança que quereis contra mim? Se assim me quereis vingar, farei, sem demora, cair sobre a vossa cabeça a vossa vingança.

[[v29-3-5]]

^<<v29-3-5,5>>^ Visto que levastes a minha prata e o meu ouro, e as minhas joias preciosas metestes nos vossos templos,

[[v29-3-6]]

^<<v29-3-6,6>>^ e vendestes os filhos de Judá e os filhos de Jerusalém aos filhos dos gregos, para os apartar para longe dos seus limites,

[[v29-3-7]]

^<<v29-3-7,7>>^ eis que eu os suscitarei do lugar para onde os vendestes e farei cair a vossa vingança sobre a vossa própria cabeça.

[[v29-3-8]]

^<<v29-3-8,8>>^ Venderei vossos filhos e vossas filhas aos filhos de Judá, e estes, aos sabeus, a uma nação remota, porque o SENHOR o disse.

[[v29-3-9]]

^<<v29-3-9,9>>^ Proclamai isto entre as nações: Apregoai guerra santa e suscitai os valentes; cheguem-se, subam todos os homens de guerra.

[[v29-3-10]]

^<<v29-3-10,10>>^ Forjai espadas das vossas relhas de arado e lanças, das vossas podadeiras; diga o fraco: Eu sou forte.

[[v29-3-11]]

^<<v29-3-11,11>>^ Apressai-vos, e vinde, todos os povos em redor, e congregai-vos; para ali, ó SENHOR, faze descer os teus valentes.

[[v29-3-12]]

^<<v29-3-12,12>>^ Levantem-se as nações e sigam para o vale de Josafá; porque ali me assentarei para julgar todas as nações em redor.

[[v29-3-13]]

^<<v29-3-13,13>>^ Lançai a foice, porque está madura a seara; vinde, pisai, porque o lagar está cheio, os seus compartimentos transbordam, porquanto a sua malícia é grande.

[[v29-3-14]]

^<<v29-3-14,14>>^ Multidões, multidões no vale da Decisão! Porque o Dia do SENHOR está perto, no vale da Decisão.

[[v29-3-15]]

^<<v29-3-15,15>>^ O sol e a lua se escurecem, e as estrelas retiram o seu resplendor.

[[v29-3-16]]

^<<v29-3-16,16>>^ O SENHOR brama de Sião e se fará ouvir de Jerusalém, e os céus e a terra tremerão; mas o SENHOR será o refúgio do seu povo e a fortaleza dos filhos de Israel.

[[v29-3-17]]

^<<v29-3-17,17>>^ Sabereis, assim, que eu sou o SENHOR, vosso Deus, que habito em Sião, meu santo monte; e Jerusalém será santa; estranhos não passarão mais por ela.

[[v29-3-18]]

^<<v29-3-18,18>>^ E há de ser que, naquele dia, os montes destilarão mosto, e os outeiros manarão leite, e todos os rios de Judá estarão cheios de águas; sairá uma fonte da Casa do SENHOR e regará o vale de Sitim.

[[v29-3-19]]

^<<v29-3-19,19>>^ O Egito se tornará uma desolação, e Edom se fará um deserto abandonado, por causa da violência que fizeram aos filhos de Judá, em cuja terra derramaram sangue inocente.

[[v29-3-20]]

^<<v29-3-20,20>>^ Judá, porém, será habitada para sempre, e Jerusalém, de geração em geração.

[[v29-3-21]]

^<<v29-3-21,21>>^ Eu expiarei o sangue dos que não foram expiados, porque o SENHOR habitará em Sião.

'''

xref:029-joel/029-joel-002.adoc#v29-2-0[&#60; Capítulo Anterior] | <<v29-3-0,Topo>> | xref:030-amos/030-amos-001.adoc#v30-1-0[Próximo Capítulo &#62;]