include::./index.adoc[]

[[v29-2-0]]
=== Joel, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v29-2-1]]

^<<v29-2-1,1>>^ Tocai a trombeta em Sião e dai voz de rebate no meu santo monte; perturbem-se todos os moradores da terra, porque o Dia do SENHOR vem, já está próximo;

[[v29-2-2]]

^<<v29-2-2,2>>^ dia de escuridade e densas trevas, dia de nuvens e negridão! Como a alva por sobre os montes, assim se difunde um povo grande e poderoso, qual desde o tempo antigo nunca houve, nem depois dele haverá pelos anos adiante, de geração em geração.

[[v29-2-3]]

^<<v29-2-3,3>>^ À frente dele vai fogo devorador, atrás, chama que abrasa; diante dele, a terra é como o jardim do Éden; mas, atrás dele, um deserto assolado. Nada lhe escapa.

[[v29-2-4]]

^<<v29-2-4,4>>^ A sua aparência é como a de cavalos; e, como cavaleiros, assim correm.

[[v29-2-5]]

^<<v29-2-5,5>>^ Estrondeando como carros, vêm, saltando pelos cimos dos montes, crepitando como chamas de fogo que devoram o restolho, como um povo poderoso posto em ordem de combate.

[[v29-2-6]]

^<<v29-2-6,6>>^ Diante deles, tremem os povos; todos os rostos empalidecem.

[[v29-2-7]]

^<<v29-2-7,7>>^ Correm como valentes; como homens de guerra, sobem muros; e cada um vai no seu caminho e não se desvia da sua fileira.

[[v29-2-8]]

^<<v29-2-8,8>>^ Não empurram uns aos outros; cada um segue o seu rumo; arremetem contra lanças e não se detêm no seu caminho.

[[v29-2-9]]

^<<v29-2-9,9>>^ Assaltam a cidade, correm pelos muros, sobem às casas; pelas janelas entram como ladrão.

[[v29-2-10]]

^<<v29-2-10,10>>^ Diante deles, treme a terra, e os céus se abalam; o sol e a lua se escurecem, e as estrelas retiram o seu resplendor.

[[v29-2-11]]

^<<v29-2-11,11>>^ O SENHOR levanta a voz diante do seu exército; porque muitíssimo grande é o seu arraial; porque é poderoso quem executa as suas ordens; sim, grande é o Dia do SENHOR e mui terrível! Quem o poderá suportar?

[[v29-2-12]]

^<<v29-2-12,12>>^ Ainda assim, agora mesmo, diz o SENHOR: Convertei-vos a mim de todo o vosso coração; e isso com jejuns, com choro e com pranto.

[[v29-2-13]]

^<<v29-2-13,13>>^ Rasgai o vosso coração, e não as vossas vestes, e convertei-vos ao SENHOR, vosso Deus, porque ele é misericordioso, e compassivo, e tardio em irar-se, e grande em benignidade, e se arrepende do mal.

[[v29-2-14]]

^<<v29-2-14,14>>^ Quem sabe se não se voltará, e se arrependerá, e deixará após si uma bênção, uma oferta de manjares e libação para o SENHOR, vosso Deus?

[[v29-2-15]]

^<<v29-2-15,15>>^ Tocai a trombeta em Sião, promulgai um santo jejum, proclamai uma assembleia solene.

[[v29-2-16]]

^<<v29-2-16,16>>^ Congregai o povo, santificai a congregação, ajuntai os anciãos, reuni os filhinhos e os que mamam; saia o noivo da sua recâmara, e a noiva, do seu aposento.

[[v29-2-17]]

^<<v29-2-17,17>>^ Chorem os sacerdotes, ministros do SENHOR, entre o pórtico e o altar, e orem: Poupa o teu povo, ó SENHOR, e não entregues a tua herança ao opróbrio, para que as nações façam escárnio dele. Por que hão de dizer entre os povos: Onde está o seu Deus?

[[v29-2-18]]

^<<v29-2-18,18>>^ Então, o SENHOR se mostrou zeloso da sua terra, compadeceu-se do seu povo

[[v29-2-19]]

^<<v29-2-19,19>>^ e, respondendo, lhe disse: Eis que vos envio o cereal, e o vinho, e o óleo, e deles sereis fartos, e vos não entregarei mais ao opróbrio entre as nações.

[[v29-2-20]]

^<<v29-2-20,20>>^ Mas o exército que vem do Norte, eu o removerei para longe de vós, lançá-lo-ei em uma terra seca e deserta; lançarei a sua vanguarda para o mar oriental, e a sua retaguarda, para o mar ocidental; subirá o seu mau cheiro, e subirá a sua podridão; porque agiu poderosamente.

[[v29-2-21]]

^<<v29-2-21,21>>^ Não temas, ó terra, regozija-te e alegra-te, porque o SENHOR faz grandes coisas.

[[v29-2-22]]

^<<v29-2-22,22>>^ Não temais, animais do campo, porque os pastos do deserto reverdecerão, porque o arvoredo dará o seu fruto, a figueira e a vide produzirão com vigor.

[[v29-2-23]]

^<<v29-2-23,23>>^ Alegrai-vos, pois, filhos de Sião, regozijai-vos no SENHOR, vosso Deus, porque ele vos dará em justa medida a chuva; fará descer, como outrora, a chuva temporã e a serôdia.

[[v29-2-24]]

^<<v29-2-24,24>>^ As eiras se encherão de trigo, e os lagares transbordarão de vinho e de óleo.

[[v29-2-25]]

^<<v29-2-25,25>>^ Restituir-vos-ei os anos que foram consumidos pelo gafanhoto migrador, pelo destruidor e pelo cortador, o meu grande exército que enviei contra vós outros.

[[v29-2-26]]

^<<v29-2-26,26>>^ Comereis abundantemente, e vos fartareis, e louvareis o nome do SENHOR, vosso Deus, que se houve maravilhosamente convosco; e o meu povo jamais será envergonhado.

[[v29-2-27]]

^<<v29-2-27,27>>^ Sabereis que estou no meio de Israel e que eu sou o SENHOR, vosso Deus, e não há outro; e o meu povo jamais será envergonhado.

[[v29-2-28]]

^<<v29-2-28,28>>^ E acontecerá, depois, que derramarei o meu Espírito sobre toda a carne; vossos filhos e vossas filhas profetizarão, vossos velhos sonharão, e vossos jovens terão visões;

[[v29-2-29]]

^<<v29-2-29,29>>^ até sobre os servos e sobre as servas derramarei o meu Espírito naqueles dias.

[[v29-2-30]]

^<<v29-2-30,30>>^ Mostrarei prodígios no céu e na terra: sangue, fogo e colunas de fumaça.

[[v29-2-31]]

^<<v29-2-31,31>>^ O sol se converterá em trevas, e a lua, em sangue, antes que venha o grande e terrível Dia do SENHOR.

[[v29-2-32]]

^<<v29-2-32,32>>^ E acontecerá que todo aquele que invocar o nome do SENHOR será salvo; porque, no monte Sião e em Jerusalém, estarão os que forem salvos, como o SENHOR prometeu; e, entre os sobreviventes, aqueles que o SENHOR chamar.

'''

xref:029-joel/029-joel-001.adoc#v29-1-0[&#60; Capítulo Anterior] | <<v29-2-0,Topo>> | xref:029-joel/029-joel-003.adoc#v29-3-0[Próximo Capítulo &#62;]