include::./index.adoc[]

[[v23-36-0]]
=== Isaías, 36
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-36-1]]

^<<v23-36-1,1>>^ No ano décimo quarto do rei Ezequias, subiu Senaqueribe, rei da Assíria, contra todas as cidades fortificadas de Judá e as tomou.

[[v23-36-2]]

^<<v23-36-2,2>>^ O rei da Assíria enviou Rabsaqué, de Laquis a Jerusalém, ao rei Ezequias, com grande exército; parou ele na extremidade do aqueduto do açude superior, junto ao caminho do campo do lavadeiro.

[[v23-36-3]]

^<<v23-36-3,3>>^ Então, saíram a encontrar-se com ele Eliaquim, filho de Hilquias, o mordomo, Sebna, o escrivão, e Joá, filho de Asafe, o cronista.

[[v23-36-4]]

^<<v23-36-4,4>>^ Rabsaqué lhes disse: Dizei a Ezequias: Assim diz o sumo rei, o rei da Assíria: Que confiança é essa em que te estribas?

[[v23-36-5]]

^<<v23-36-5,5>>^ Bem posso dizer-te que teu conselho e poder para a guerra não passam de vãs palavras; em quem, pois, agora confias, para que te rebeles contra mim?

[[v23-36-6]]

^<<v23-36-6,6>>^ Confias no Egito, esse bordão de cana esmagada, o qual, se alguém nele apoiar-se, lhe entrará pela mão e a traspassará; assim é Faraó, rei do Egito, para com todos os que nele confiam.

[[v23-36-7]]

^<<v23-36-7,7>>^ Mas, se me dizes: Confiamos no SENHOR, nosso Deus, não é esse aquele cujos altos e altares Ezequias removeu e disse a Judá e a Jerusalém: Perante este altar adorareis?

[[v23-36-8]]

^<<v23-36-8,8>>^ Ora, pois, empenha-te com meu senhor, rei da Assíria, e dar-te-ei dois mil cavalos, se de tua parte achares cavaleiros para os montar.

[[v23-36-9]]

^<<v23-36-9,9>>^ Como, pois, se não podes afugentar um só capitão dos menores dos servos do meu senhor, confias no Egito por causa dos carros e cavaleiros?

[[v23-36-10]]

^<<v23-36-10,10>>^ Acaso, subi eu agora sem o SENHOR contra esta terra, para a destruir? Pois o SENHOR mesmo me disse: Sobe contra a terra e destrói-a.

[[v23-36-11]]

^<<v23-36-11,11>>^ Então, disseram Eliaquim, Sebna e Joá a Rabsaqué: Pedimos-te que fales em aramaico aos teus servos, porque o entendemos, e não nos fales em judaico, aos ouvidos do povo que está sobre os muros.

[[v23-36-12]]

^<<v23-36-12,12>>^ Mas Rabsaqué lhes respondeu: Mandou-me, acaso, o meu senhor para dizer-te estas palavras a ti somente e a teu senhor? E não, antes, aos homens que estão assentados sobre os muros, para que comam convosco o seu próprio excremento e bebam a sua própria urina?

[[v23-36-13]]

^<<v23-36-13,13>>^ Então, Rabsaqué se pôs em pé, e clamou em alta voz em judaico, e disse: Ouvi as palavras do sumo rei, do rei da Assíria.

[[v23-36-14]]

^<<v23-36-14,14>>^ Assim diz o rei: Não vos engane Ezequias; porque não vos poderá livrar.

[[v23-36-15]]

^<<v23-36-15,15>>^ Nem tampouco Ezequias vos faça confiar no SENHOR, dizendo: O SENHOR certamente nos livrará, e esta cidade não será entregue nas mãos do rei da Assíria.

[[v23-36-16]]

^<<v23-36-16,16>>^ Não deis ouvidos a Ezequias; porque assim diz o rei da Assíria: Fazei as pazes comigo e vinde para mim; e comei, cada um da sua própria vide e da sua própria figueira, e bebei, cada um da água da sua própria cisterna;

[[v23-36-17]]

^<<v23-36-17,17>>^ até que eu venha e vos leve para uma terra como a vossa; terra de cereal e de vinho, terra de pão e de vinhas.

[[v23-36-18]]

^<<v23-36-18,18>>^ Não vos engane Ezequias, dizendo: O SENHOR nos livrará. Acaso, os deuses das nações livraram cada um a sua terra das mãos do rei da Assíria?

[[v23-36-19]]

^<<v23-36-19,19>>^ Onde estão os deuses de Hamate e de Arpade? Onde estão os deuses de Sefarvaim? Acaso, livraram eles a Samaria das minhas mãos?

[[v23-36-20]]

^<<v23-36-20,20>>^ Quais são, dentre todos os deuses destes países, os que livraram a sua terra das minhas mãos, para que o SENHOR livre a Jerusalém das minhas mãos?

[[v23-36-21]]

^<<v23-36-21,21>>^ Eles, porém, se calaram e não lhe responderam palavra; porque assim lhes havia ordenado o rei, dizendo: Não lhe respondereis.

[[v23-36-22]]

^<<v23-36-22,22>>^ Então, Eliaquim, filho de Hilquias, o mordomo, e Sebna, o escrivão, e Joá, filho de Asafe, o cronista, rasgaram suas vestes, vieram ter com Ezequias e lhe referiram as palavras de Rabsaqué.

'''

xref:023-isaias/023-isaias-035.adoc#v23-35-0[&#60; Capítulo Anterior] | <<v23-36-0,Topo>> | xref:023-isaias/023-isaias-037.adoc#v23-37-0[Próximo Capítulo &#62;]