include::./index.adoc[]

[[v23-2-0]]
=== Isaías, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-2-1]]

^<<v23-2-1,1>>^ Palavra que, em visão, veio a Isaías, filho de Amoz, a respeito de Judá e Jerusalém.

[[v23-2-2]]

^<<v23-2-2,2>>^ Nos últimos dias, acontecerá que o monte da Casa do SENHOR será estabelecido no cimo dos montes e se elevará sobre os outeiros, e para ele afluirão todos os povos.

[[v23-2-3]]

^<<v23-2-3,3>>^ Irão muitas nações e dirão: Vinde, e subamos ao monte do SENHOR e à casa do Deus de Jacó, para que nos ensine os seus caminhos, e andemos pelas suas veredas; porque de Sião sairá a lei, e a palavra do SENHOR, de Jerusalém.

[[v23-2-4]]

^<<v23-2-4,4>>^ Ele julgará entre os povos e corrigirá muitas nações; estas converterão as suas espadas em relhas de arados e suas lanças, em podadeiras; uma nação não levantará a espada contra outra nação, nem aprenderão mais a guerra.

[[v23-2-5]]

^<<v23-2-5,5>>^ Vinde, ó casa de Jacó, e andemos na luz do SENHOR.

[[v23-2-6]]

^<<v23-2-6,6>>^ Pois, tu, SENHOR, desamparaste o teu povo, a casa de Jacó, porque os seus se encheram da corrupção do Oriente e são agoureiros como os filisteus e se associam com os filhos dos estranhos.

[[v23-2-7]]

^<<v23-2-7,7>>^ A sua terra está cheia de prata e de ouro, e não têm conta os seus tesouros; também está cheia de cavalos, e os seus carros não têm fim.

[[v23-2-8]]

^<<v23-2-8,8>>^ Também está cheia a sua terra de ídolos; adoram a obra das suas mãos, aquilo que os seus próprios dedos fizeram.

[[v23-2-9]]

^<<v23-2-9,9>>^ Com isso, a gente se abate, e o homem se avilta; portanto, não lhes perdoarás.

[[v23-2-10]]

^<<v23-2-10,10>>^ Vai, entra nas rochas e esconde-te no pó, ante o terror do SENHOR e a glória da sua majestade.

[[v23-2-11]]

^<<v23-2-11,11>>^ Os olhos altivos dos homens serão abatidos, e a sua altivez será humilhada; só o SENHOR será exaltado naquele dia.

[[v23-2-12]]

^<<v23-2-12,12>>^ Porque o Dia do SENHOR dos Exércitos será contra todo soberbo e altivo e contra todo aquele que se exalta, para que seja abatido;

[[v23-2-13]]

^<<v23-2-13,13>>^ contra todos os cedros do Líbano, altos, mui elevados; e contra todos os carvalhos de Basã;

[[v23-2-14]]

^<<v23-2-14,14>>^ contra todos os montes altos e contra todos os outeiros elevados;

[[v23-2-15]]

^<<v23-2-15,15>>^ contra toda torre alta e contra toda muralha firme;

[[v23-2-16]]

^<<v23-2-16,16>>^ contra todos os navios de Társis e contra tudo o que é belo à vista.

[[v23-2-17]]

^<<v23-2-17,17>>^ A arrogância do homem será abatida, e a sua altivez será humilhada; só o SENHOR será exaltado naquele dia.

[[v23-2-18]]

^<<v23-2-18,18>>^ Os ídolos serão de todo destruídos.

[[v23-2-19]]

^<<v23-2-19,19>>^ Então, os homens se meterão nas cavernas das rochas e nos buracos da terra, ante o terror do SENHOR e a glória da sua majestade, quando ele se levantar para espantar a terra.

[[v23-2-20]]

^<<v23-2-20,20>>^ Naquele dia, os homens lançarão às toupeiras e aos morcegos os seus ídolos de prata e os seus ídolos de ouro, que fizeram para ante eles se prostrarem,

[[v23-2-21]]

^<<v23-2-21,21>>^ e meter-se-ão pelas fendas das rochas e pelas cavernas das penhas, ante o terror do SENHOR e a glória da sua majestade, quando ele se levantar para espantar a terra.

[[v23-2-22]]

^<<v23-2-22,22>>^ Afastai-vos, pois, do homem cujo fôlego está no seu nariz. Pois em que é ele estimado?

'''

xref:023-isaias/023-isaias-001.adoc#v23-1-0[&#60; Capítulo Anterior] | <<v23-2-0,Topo>> | xref:023-isaias/023-isaias-003.adoc#v23-3-0[Próximo Capítulo &#62;]