include::./index.adoc[]

[[v23-50-0]]
=== Isaías, 50
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-50-1]]

^<<v23-50-1,1>>^ Assim diz o SENHOR: Onde está a carta de divórcio de vossa mãe, pela qual eu a repudiei? Ou quem é o meu credor, a quem eu vos tenha vendido? Eis que por causa das vossas iniquidades é que fostes vendidos, e por causa das vossas transgressões vossa mãe foi repudiada.

[[v23-50-2]]

^<<v23-50-2,2>>^ Por que razão, quando eu vim, ninguém apareceu? Quando chamei, ninguém respondeu? Acaso, se encolheu tanto a minha mão, que já não pode remir ou já não há força em mim para livrar? Eis que pela minha repreensão faço secar o mar e torno os rios um deserto, até que cheirem mal os seus peixes; pois, não havendo água, morrem de sede.

[[v23-50-3]]

^<<v23-50-3,3>>^ Eu visto os céus de negridão e lhes ponho pano de saco por sua coberta.

[[v23-50-4]]

^<<v23-50-4,4>>^ O SENHOR Deus me deu língua de eruditos, para que eu saiba dizer boa palavra ao cansado. Ele me desperta todas as manhãs, desperta-me o ouvido para que eu ouça como os eruditos.

[[v23-50-5]]

^<<v23-50-5,5>>^ O SENHOR Deus me abriu os ouvidos, e eu não fui rebelde, não me retraí.

[[v23-50-6]]

^<<v23-50-6,6>>^ Ofereci as costas aos que me feriam e as faces, aos que me arrancavam os cabelos; não escondi o rosto aos que me afrontavam e me cuspiam.

[[v23-50-7]]

^<<v23-50-7,7>>^ Porque o SENHOR Deus me ajudou, pelo que não me senti envergonhado; por isso, fiz o meu rosto como um seixo e sei que não serei envergonhado.

[[v23-50-8]]

^<<v23-50-8,8>>^ Perto está o que me justifica; quem contenderá comigo? Apresentemo-nos juntamente; quem é o meu adversário? Chegue-se para mim.

[[v23-50-9]]

^<<v23-50-9,9>>^ Eis que o SENHOR Deus me ajuda; quem há que me condene? Eis que todos eles, como um vestido, serão consumidos; a traça os comerá.

[[v23-50-10]]

^<<v23-50-10,10>>^ Quem há entre vós que tema ao SENHOR e que ouça a voz do seu Servo? Aquele que andou em trevas, sem nenhuma luz, confie em o nome do SENHOR e se firme sobre o seu Deus.

[[v23-50-11]]

^<<v23-50-11,11>>^ Eia! Todos vós, que acendeis fogo e vos armais de setas incendiárias, andai entre as labaredas do vosso fogo e entre as setas que acendestes; de mim é que vos sobrevirá isto, e em tormentas vos deitareis.

'''

xref:023-isaias/023-isaias-049.adoc#v23-49-0[&#60; Capítulo Anterior] | <<v23-50-0,Topo>> | xref:023-isaias/023-isaias-051.adoc#v23-51-0[Próximo Capítulo &#62;]