include::./index.adoc[]

[[v23-49-0]]
=== Isaías, 49
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-49-1]]

^<<v23-49-1,1>>^ Ouvi-me, terras do mar, e vós, povos de longe, escutai! O SENHOR me chamou desde o meu nascimento, desde o ventre de minha mãe fez menção do meu nome;

[[v23-49-2]]

^<<v23-49-2,2>>^ fez a minha boca como uma espada aguda, na sombra da sua mão me escondeu; fez-me como uma flecha polida, e me guardou na sua aljava,

[[v23-49-3]]

^<<v23-49-3,3>>^ e me disse: Tu és o meu servo, és Israel, por quem hei de ser glorificado.

[[v23-49-4]]

^<<v23-49-4,4>>^ Eu mesmo disse: debalde tenho trabalhado, inútil e vãmente gastei as minhas forças; todavia, o meu direito está perante o SENHOR, a minha recompensa, perante o meu Deus.

[[v23-49-5]]

^<<v23-49-5,5>>^ Mas agora diz o SENHOR, que me formou desde o ventre para ser seu servo, para que torne a trazer Jacó e para reunir Israel a ele, porque eu sou glorificado perante o SENHOR, e o meu Deus é a minha força.

[[v23-49-6]]

^<<v23-49-6,6>>^ Sim, diz ele: Pouco é o seres meu servo, para restaurares as tribos de Jacó e tornares a trazer os remanescentes de Israel; também te dei como luz para os gentios, para seres a minha salvação até à extremidade da terra.

[[v23-49-7]]

^<<v23-49-7,7>>^ Assim diz o SENHOR, o Redentor e Santo de Israel, ao que é desprezado, ao aborrecido das nações, ao servo dos tiranos: Os reis o verão, e os príncipes se levantarão; e eles te adorarão por amor do SENHOR, que é fiel, e do Santo de Israel, que te escolheu.

[[v23-49-8]]

^<<v23-49-8,8>>^ Diz ainda o SENHOR: No tempo aceitável, eu te ouvi e te socorri no dia da salvação; guardar-te-ei e te farei mediador da aliança do povo, para restaurares a terra e lhe repartires as herdades assoladas;

[[v23-49-9]]

^<<v23-49-9,9>>^ para dizeres aos presos: Saí, e aos que estão em trevas: Aparecei. Eles pastarão nos caminhos e em todos os altos desnudos terão o seu pasto.

[[v23-49-10]]

^<<v23-49-10,10>>^ Não terão fome nem sede, a calma nem o sol os afligirá; porque o que deles se compadece os guiará e os conduzirá aos mananciais das águas.

[[v23-49-11]]

^<<v23-49-11,11>>^ Transformarei todos os meus montes em caminhos, e as minhas veredas serão alteadas.

[[v23-49-12]]

^<<v23-49-12,12>>^ Eis que estes virão de longe, e eis que aqueles, do Norte e do Ocidente, e aqueles outros, da terra de Sinim.

[[v23-49-13]]

^<<v23-49-13,13>>^ Cantai, ó céus, alegra-te, ó terra, e vós, montes, rompei em cânticos, porque o SENHOR consolou o seu povo e dos seus aflitos se compadece.

[[v23-49-14]]

^<<v23-49-14,14>>^ Mas Sião diz: O SENHOR me desamparou, o Senhor se esqueceu de mim.

[[v23-49-15]]

^<<v23-49-15,15>>^ Acaso, pode uma mulher esquecer-se do filho que ainda mama, de sorte que não se compadeça do filho do seu ventre? Mas ainda que esta viesse a se esquecer dele, eu, todavia, não me esquecerei de ti.

[[v23-49-16]]

^<<v23-49-16,16>>^ Eis que nas palmas das minhas mãos te gravei; os teus muros estão continuamente perante mim.

[[v23-49-17]]

^<<v23-49-17,17>>^ Os teus filhos virão apressadamente, ao passo que os teus destruidores e os teus assoladores se retiram do teu meio.

[[v23-49-18]]

^<<v23-49-18,18>>^ Levanta os olhos ao redor e olha: todos estes que se ajuntam vêm a ti. Tão certo como eu vivo, diz o SENHOR, de todos estes te vestirás como de um ornamento e deles te cingirás como noiva.

[[v23-49-19]]

^<<v23-49-19,19>>^ Pois, quanto aos teus lugares desertos e desolados e à tua terra destruída, agora tu, ó Sião, certamente, serás estreita demais para os moradores; e os que te devoravam estarão longe de ti.

[[v23-49-20]]

^<<v23-49-20,20>>^ Até mesmo os teus filhos, que de ti foram tirados, dirão aos teus ouvidos: Mui estreito é para mim este lugar; dá-me espaço em que eu habite.

[[v23-49-21]]

^<<v23-49-21,21>>^ E dirás contigo mesma: Quem me gerou estes, pois eu estava desfilhada e estéril, em exílio e repelida? Quem, pois, me criou estes? Fui deixada sozinha; estes, onde estavam?

[[v23-49-22]]

^<<v23-49-22,22>>^ Assim diz o SENHOR Deus: Eis que levantarei a mão para as nações e ante os povos arvorarei a minha bandeira; eles trarão os teus filhos nos braços, e as tuas filhas serão levadas sobre os ombros.

[[v23-49-23]]

^<<v23-49-23,23>>^ Reis serão os teus aios, e rainhas, as tuas amas; diante de ti se inclinarão com o rosto em terra e lamberão o pó dos teus pés; saberás que eu sou o SENHOR e que os que esperam em mim não serão envergonhados.

[[v23-49-24]]

^<<v23-49-24,24>>^ Tirar-se-ia a presa ao valente? Acaso, os presos poderiam fugir ao tirano?

[[v23-49-25]]

^<<v23-49-25,25>>^ Mas assim diz o SENHOR: Por certo que os presos se tirarão ao valente, e a presa do tirano fugirá, porque eu contenderei com os que contendem contigo e salvarei os teus filhos.

[[v23-49-26]]

^<<v23-49-26,26>>^ Sustentarei os teus opressores com a sua própria carne, e com o seu próprio sangue se embriagarão, como com vinho novo. Todo homem saberá que eu sou o SENHOR, o teu Salvador e o teu Redentor, o Poderoso de Jacó.

'''

xref:023-isaias/023-isaias-048.adoc#v23-48-0[&#60; Capítulo Anterior] | <<v23-49-0,Topo>> | xref:023-isaias/023-isaias-050.adoc#v23-50-0[Próximo Capítulo &#62;]