include::./index.adoc[]

[[v23-30-0]]
=== Isaías, 30
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-30-1]]

^<<v23-30-1,1>>^ Ai dos filhos rebeldes, diz o SENHOR, que executam planos que não procedem de mim e fazem aliança sem a minha aprovação, para acrescentarem pecado sobre pecado!

[[v23-30-2]]

^<<v23-30-2,2>>^ Que descem ao Egito sem me consultar, buscando refúgio em Faraó e abrigo, à sombra do Egito!

[[v23-30-3]]

^<<v23-30-3,3>>^ Mas o refúgio de Faraó se vos tornará em vergonha, e o abrigo na sombra do Egito, em confusão.

[[v23-30-4]]

^<<v23-30-4,4>>^ Porque os príncipes de Judá já estão em Zoã, e os seus embaixadores já chegaram a Hanes.

[[v23-30-5]]

^<<v23-30-5,5>>^ Todos se envergonharão de um povo que de nada lhes valerá, não servirá nem de ajuda nem de proveito, porém de vergonha e de opróbrio.

[[v23-30-6]]

^<<v23-30-6,6>>^ Sentença contra a Besta do Sul. Através da terra da aflição e angústia de onde vêm a leoa, o leão, a víbora e a serpente volante, levam a lombos de jumento as suas riquezas e sobre as corcovas de camelos, os seus tesouros, a um povo que de nada lhes aproveitará.

[[v23-30-7]]

^<<v23-30-7,7>>^ Pois, quanto ao Egito, vão e inútil é o seu auxílio; por isso, lhe chamei Gabarola que nada faz.

[[v23-30-8]]

^<<v23-30-8,8>>^ Vai, pois, escreve isso numa tabuinha perante eles, escreve-o num livro, para que fique registrado para os dias vindouros, para sempre, perpetuamente.

[[v23-30-9]]

^<<v23-30-9,9>>^ Porque povo rebelde é este, filhos mentirosos, filhos que não querem ouvir a lei do SENHOR.

[[v23-30-10]]

^<<v23-30-10,10>>^ Eles dizem aos videntes: Não tenhais visões; e aos profetas: Não profetizeis para nós o que é reto; dizei-nos coisas aprazíveis, profetizai-nos ilusões;

[[v23-30-11]]

^<<v23-30-11,11>>^ desviai-vos do caminho, apartai-vos da vereda; não nos faleis mais do Santo de Israel.

[[v23-30-12]]

^<<v23-30-12,12>>^ Pelo que assim diz o Santo de Israel: Visto que rejeitais esta palavra, confiais na opressão e na perversidade e sobre isso vos estribais,

[[v23-30-13]]

^<<v23-30-13,13>>^ portanto, esta maldade vos será como a brecha de um muro alto, que, formando uma barriga, está prestes a cair, e cuja queda vem de repente, num momento.

[[v23-30-14]]

^<<v23-30-14,14>>^ O SENHOR o quebrará como se quebra o vaso do oleiro, despedaçando-o sem nada lhe poupar; não se achará entre os seus cacos um que sirva para tomar fogo da lareira ou tirar água da poça.

[[v23-30-15]]

^<<v23-30-15,15>>^ Porque assim diz o SENHOR Deus, o Santo de Israel: Em vos converterdes e em sossegardes, está a vossa salvação; na tranquilidade e na confiança, a vossa força, mas não o quisestes.

[[v23-30-16]]

^<<v23-30-16,16>>^ Antes, dizeis: Não, sobre cavalos fugiremos; portanto, fugireis; e: Sobre cavalos ligeiros cavalgaremos; sim, ligeiros serão os vossos perseguidores.

[[v23-30-17]]

^<<v23-30-17,17>>^ Mil homens fugirão pela ameaça de apenas um; pela ameaça de cinco, todos vós fugireis, até que sejais deixados como o mastro no cimo do monte e como o estandarte no outeiro.

[[v23-30-18]]

^<<v23-30-18,18>>^ Por isso, o SENHOR espera, para ter misericórdia de vós, e se detém, para se compadecer de vós, porque o SENHOR é Deus de justiça; bem-aventurados todos os que nele esperam.

[[v23-30-19]]

^<<v23-30-19,19>>^ Porque o povo habitará em Sião, em Jerusalém; tu não chorarás mais; certamente, se compadecerá de ti, à voz do teu clamor, e, ouvindo-a, te responderá.

[[v23-30-20]]

^<<v23-30-20,20>>^ Embora o Senhor vos dê pão de angústia e água de aflição, contudo, não se esconderão mais os teus mestres; os teus olhos verão os teus mestres.

[[v23-30-21]]

^<<v23-30-21,21>>^ Quando te desviares para a direita e quando te desviares para a esquerda, os teus ouvidos ouvirão atrás de ti uma palavra, dizendo: Este é o caminho, andai por ele.

[[v23-30-22]]

^<<v23-30-22,22>>^ E terás por contaminados a prata que recobre as imagens esculpidas e o ouro que reveste as tuas imagens de fundição; lançá-las-ás fora como coisa imunda e a cada uma dirás: Fora daqui!

[[v23-30-23]]

^<<v23-30-23,23>>^ Então, o Senhor te dará chuva sobre a tua semente, com que semeares a terra, como também pão como produto da terra, o qual será farto e nutritivo; naquele dia, o teu gado pastará em lugares espaçosos.

[[v23-30-24]]

^<<v23-30-24,24>>^ Os bois e os jumentos que lavram a terra comerão forragem com sal, alimpada com pá e forquilha.

[[v23-30-25]]

^<<v23-30-25,25>>^ Em todo monte alto e em todo outeiro elevado haverá ribeiros e correntes de águas, no dia da grande matança quando caírem as torres.

[[v23-30-26]]

^<<v23-30-26,26>>^ A luz da lua será como a do sol, e a do sol, sete vezes maior, como a luz de sete dias, no dia em que o SENHOR atar a ferida do seu povo e curar a chaga do golpe que ele deu.

[[v23-30-27]]

^<<v23-30-27,27>>^ Eis o nome do SENHOR vem de longe, ardendo na sua ira, no meio de espessas nuvens; os seus lábios estão cheios de indignação, e a sua língua é como fogo devorador.

[[v23-30-28]]

^<<v23-30-28,28>>^ A sua respiração é como a torrente que transborda e chega até ao pescoço, para peneirar as nações com peneira de destruição; um freio de fazer errar estará nos queixos dos povos.

[[v23-30-29]]

^<<v23-30-29,29>>^ Um cântico haverá entre vós, como na noite em que se celebra festa santa; e alegria de coração, como a daquele que sai ao som da flauta para ir ao monte do SENHOR, à Rocha de Israel.

[[v23-30-30]]

^<<v23-30-30,30>>^ O SENHOR fará ouvir a sua voz majestosa e fará ver o golpe do seu braço, que desce com indignação de ira, no meio de chamas devoradoras, de chuvas torrenciais, de tempestades e de pedra de saraiva.

[[v23-30-31]]

^<<v23-30-31,31>>^ Porque com a voz do SENHOR será apavorada a Assíria, quando ele a fere com a vara.

[[v23-30-32]]

^<<v23-30-32,32>>^ Cada pancada castigadora, com a vara, que o SENHOR lhe der, será ao som de tamboris e harpas; e combaterá vibrando golpes contra eles.

[[v23-30-33]]

^<<v23-30-33,33>>^ Porque há muito está preparada a fogueira, preparada para o rei; a pira é profunda e larga, com fogo e lenha em abundância; o assopro do SENHOR, como torrente de enxofre, a acenderá.

'''

xref:023-isaias/023-isaias-029.adoc#v23-29-0[&#60; Capítulo Anterior] | <<v23-30-0,Topo>> | xref:023-isaias/023-isaias-031.adoc#v23-31-0[Próximo Capítulo &#62;]