include::./index.adoc[]

[[v23-52-0]]
=== Isaías, 52
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-52-1]]

^<<v23-52-1,1>>^ Desperta, desperta, reveste-te da tua fortaleza, ó Sião; veste-te das tuas roupagens formosas, ó Jerusalém, cidade santa; porque não mais entrará em ti nem incircunciso nem imundo.

[[v23-52-2]]

^<<v23-52-2,2>>^ Sacode-te do pó, levanta-te e toma assento, ó Jerusalém; solta-te das cadeias de teu pescoço, ó cativa filha de Sião.

[[v23-52-3]]

^<<v23-52-3,3>>^ Porque assim diz o SENHOR: Por nada fostes vendidos; e sem dinheiro sereis resgatados.

[[v23-52-4]]

^<<v23-52-4,4>>^ Porque assim diz o SENHOR Deus: O meu povo no princípio desceu ao Egito, para nele habitar, e a Assíria sem razão o oprimiu.

[[v23-52-5]]

^<<v23-52-5,5>>^ Agora, que farei eu aqui, diz o SENHOR, visto ter sido o meu povo levado sem preço? Os seus tiranos sobre ele dão uivos, diz o SENHOR; e o meu nome é blasfemado incessantemente todo o dia.

[[v23-52-6]]

^<<v23-52-6,6>>^ Por isso, o meu povo saberá o meu nome; portanto, naquele dia, saberá que sou eu quem fala: Eis-me aqui.

[[v23-52-7]]

^<<v23-52-7,7>>^ Que formosos são sobre os montes os pés do que anuncia as boas-novas, que faz ouvir a paz, que anuncia coisas boas, que faz ouvir a salvação, que diz a Sião: O teu Deus reina!

[[v23-52-8]]

^<<v23-52-8,8>>^ Eis o grito dos teus atalaias! Eles erguem a voz, juntamente exultam; porque com seus próprios olhos distintamente veem o retorno do SENHOR a Sião.

[[v23-52-9]]

^<<v23-52-9,9>>^ Rompei em júbilo, exultai à uma, ó ruínas de Jerusalém; porque o SENHOR consolou o seu povo, remiu a Jerusalém.

[[v23-52-10]]

^<<v23-52-10,10>>^ O SENHOR desnudou o seu santo braço à vista de todas as nações; e todos os confins da terra verão a salvação do nosso Deus.

[[v23-52-11]]

^<<v23-52-11,11>>^ Retirai-vos, retirai-vos, saí de lá, não toqueis coisa imunda; saí do meio dela, purificai-vos, vós que levais os utensílios do SENHOR.

[[v23-52-12]]

^<<v23-52-12,12>>^ Porquanto não saireis apressadamente, nem vos ireis fugindo; porque o SENHOR irá adiante de vós, e o Deus de Israel será a vossa retaguarda.

[[v23-52-13]]

^<<v23-52-13,13>>^ Eis que o meu Servo procederá com prudência; será exaltado e elevado e será mui sublime.

[[v23-52-14]]

^<<v23-52-14,14>>^ Como pasmaram muitos à vista dele (pois o seu aspecto estava mui desfigurado, mais do que o de outro qualquer, e a sua aparência, mais do que a dos outros filhos dos homens),

[[v23-52-15]]

^<<v23-52-15,15>>^ assim causará admiração às nações, e os reis fecharão a sua boca por causa dele; porque aquilo que não lhes foi anunciado verão, e aquilo que não ouviram entenderão.

'''

xref:023-isaias/023-isaias-051.adoc#v23-51-0[&#60; Capítulo Anterior] | <<v23-52-0,Topo>> | xref:023-isaias/023-isaias-053.adoc#v23-53-0[Próximo Capítulo &#62;]