include::./index.adoc[]

[[v23-21-0]]
=== Isaías, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-21-1]]

^<<v23-21-1,1>>^ Sentença contra o deserto do mar. Como os tufões vêm do Sul, ele virá do deserto, da horrível terra.

[[v23-21-2]]

^<<v23-21-2,2>>^ Dura visão me foi anunciada: o pérfido procede perfidamente, e o destruidor anda destruindo. Sobe, ó Elão, sitia, ó Média; já fiz cessar todo gemer.

[[v23-21-3]]

^<<v23-21-3,3>>^ Pelo que os meus lombos estão cheios de angústias; dores se apoderaram de mim como as de parturiente; contorço-me de dores e não posso ouvir, desfaleço-me e não posso ver.

[[v23-21-4]]

^<<v23-21-4,4>>^ O meu coração cambaleia, o horror me apavora; a noite que eu desejava se me tornou em tremores.

[[v23-21-5]]

^<<v23-21-5,5>>^ Põe-se a mesa, estendem-se tapetes, come-se e bebe-se. Levantai-vos, príncipes, untai o escudo.

[[v23-21-6]]

^<<v23-21-6,6>>^ Pois assim me disse o Senhor: Vai, põe o atalaia, e ele que diga o que vir.

[[v23-21-7]]

^<<v23-21-7,7>>^ Quando vir uma tropa de cavaleiros de dois a dois, uma tropa de jumentos e uma tropa de camelos, ele que escute diligentemente com grande atenção.

[[v23-21-8]]

^<<v23-21-8,8>>^ Então, o atalaia gritou como um leão: Senhor, sobre a torre de vigia estou em pé continuamente durante o dia e de guarda me ponho noites inteiras.

[[v23-21-9]]

^<<v23-21-9,9>>^ Eis agora vem uma tropa de homens, cavaleiros de dois a dois. Então, ergueu ele a voz e disse: Caiu, caiu Babilônia; e todas as imagens de escultura dos seus deuses jazem despedaçadas por terra.

[[v23-21-10]]

^<<v23-21-10,10>>^ Oh! Povo meu, debulhado e batido como o trigo da minha eira! O que ouvi do SENHOR dos Exércitos, Deus de Israel, isso vos anunciei.

[[v23-21-11]]

^<<v23-21-11,11>>^ Sentença contra Dumá. Gritam-me de Seir: Guarda, a que hora estamos da noite? Guarda, a que horas?

[[v23-21-12]]

^<<v23-21-12,12>>^ Respondeu o guarda: Vem a manhã, e também a noite; se quereis perguntar, perguntai; voltai, vinde.

[[v23-21-13]]

^<<v23-21-13,13>>^ Sentença contra a Arábia. Nos bosques da Arábia, passareis a noite, ó caravanas de dedanitas.

[[v23-21-14]]

^<<v23-21-14,14>>^ Traga-se água ao encontro dos sedentos; ó moradores da terra de Tema, levai pão aos fugitivos.

[[v23-21-15]]

^<<v23-21-15,15>>^ Porque fogem de diante das espadas, de diante da espada nua, de diante do arco armado e de diante do furor da guerra.

[[v23-21-16]]

^<<v23-21-16,16>>^ Porque assim me disse o Senhor: Dentro de um ano, tal como o de jornaleiro, toda a glória de Quedar desaparecerá.

[[v23-21-17]]

^<<v23-21-17,17>>^ E o restante do número dos flecheiros, os valentes dos filhos de Quedar, será diminuto, porque assim o disse o SENHOR, Deus de Israel.

'''

xref:023-isaias/023-isaias-020.adoc#v23-20-0[&#60; Capítulo Anterior] | <<v23-21-0,Topo>> | xref:023-isaias/023-isaias-022.adoc#v23-22-0[Próximo Capítulo &#62;]