include::./index.adoc[]

[[v23-61-0]]
=== Isaías, 61
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-61-1]]

^<<v23-61-1,1>>^ O Espírito do SENHOR Deus está sobre mim, porque o SENHOR me ungiu para pregar boas-novas aos quebrantados, enviou-me a curar os quebrantados de coração, a proclamar libertação aos cativos e a pôr em liberdade os algemados;

[[v23-61-2]]

^<<v23-61-2,2>>^ a apregoar o ano aceitável do SENHOR e o dia da vingança do nosso Deus; a consolar todos os que choram

[[v23-61-3]]

^<<v23-61-3,3>>^ e a pôr sobre os que em Sião estão de luto uma coroa em vez de cinzas, óleo de alegria, em vez de pranto, veste de louvor, em vez de espírito angustiado; a fim de que se chamem carvalhos de justiça, plantados pelo SENHOR para a sua glória.

[[v23-61-4]]

^<<v23-61-4,4>>^ Edificarão os lugares antigamente assolados, restaurarão os de antes destruídos e renovarão as cidades arruinadas, destruídas de geração em geração.

[[v23-61-5]]

^<<v23-61-5,5>>^ Estranhos se apresentarão e apascentarão os vossos rebanhos; estrangeiros serão os vossos lavradores e os vossos vinhateiros.

[[v23-61-6]]

^<<v23-61-6,6>>^ Mas vós sereis chamados sacerdotes do SENHOR, e vos chamarão ministros de nosso Deus; comereis as riquezas das nações e na sua glória vos gloriareis.

[[v23-61-7]]

^<<v23-61-7,7>>^ Em lugar da vossa vergonha, tereis dupla honra; em lugar da afronta, exultareis na vossa herança; por isso, na vossa terra possuireis o dobro e tereis perpétua alegria.

[[v23-61-8]]

^<<v23-61-8,8>>^ Porque eu, o SENHOR, amo o juízo e odeio a iniquidade do roubo; dar-lhes-ei fielmente a sua recompensa e com eles farei aliança eterna.

[[v23-61-9]]

^<<v23-61-9,9>>^ A sua posteridade será conhecida entre as nações, os seus descendentes, no meio dos povos; todos quantos os virem os reconhecerão como família bendita do SENHOR.

[[v23-61-10]]

^<<v23-61-10,10>>^ Regozijar-me-ei muito no SENHOR, a minha alma se alegra no meu Deus; porque me cobriu de vestes de salvação e me envolveu com o manto de justiça, como noivo que se adorna de turbante, como noiva que se enfeita com as suas joias.

[[v23-61-11]]

^<<v23-61-11,11>>^ Porque, como a terra produz os seus renovos, e como o jardim faz brotar o que nele se semeia, assim o SENHOR Deus fará brotar a justiça e o louvor perante todas as nações.

'''

xref:023-isaias/023-isaias-060.adoc#v23-60-0[&#60; Capítulo Anterior] | <<v23-61-0,Topo>> | xref:023-isaias/023-isaias-062.adoc#v23-62-0[Próximo Capítulo &#62;]