include::./index.adoc[]

[[v23-16-0]]
=== Isaías, 16
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-16-1]]

^<<v23-16-1,1>>^ Enviai cordeiros ao dominador da terra, desde Sela, pelo deserto, até ao monte da filha de Sião.

[[v23-16-2]]

^<<v23-16-2,2>>^ Como pássaro espantado, lançado fora do ninho, assim são as filhas de Moabe nos vaus do Arnom, que dizem:

[[v23-16-3]]

^<<v23-16-3,3>>^ Dá conselhos, executa o juízo e faze a tua sombra no pino do meio-dia como a noite; esconde os desterrados e não descubras os fugitivos.

[[v23-16-4]]

^<<v23-16-4,4>>^ Habitem entre ti os desterrados de Moabe, serve-lhes de esconderijo contra o destruidor. Quando o homem violento tiver fim, a destruição for desfeita e o opressor deixar a terra,

[[v23-16-5]]

^<<v23-16-5,5>>^ então, um trono se firmará em benignidade, e sobre ele no tabernáculo de Davi se assentará com fidelidade um que julgue, busque o juízo e não tarde em fazer justiça.

[[v23-16-6]]

^<<v23-16-6,6>>^ Temos ouvido da soberba de Moabe, soberbo em extremo; da sua arrogância, do seu orgulho e do seu furor; a sua jactância é vã.

[[v23-16-7]]

^<<v23-16-7,7>>^ Portanto, uivará Moabe, cada um por Moabe; gemereis profundamente abatidos pelas pastas de uvas de Quir-Haresete.

[[v23-16-8]]

^<<v23-16-8,8>>^ Porque os campos de Hesbom estão murchos; os senhores das nações talaram os melhores ramos da vinha de Sibma, que se estenderam até Jazer e se perderam no deserto, sarmentos que se estenderam e passaram além do mar.

[[v23-16-9]]

^<<v23-16-9,9>>^ Pelo que prantearei, com o pranto de Jazer, a vinha de Sibma; regar-te-ei com as minhas lágrimas, ó Hesbom, ó Eleale; pois, sobre os teus frutos de verão e sobre a tua vindima, caiu já dos inimigos o eia, como o de pisadores.

[[v23-16-10]]

^<<v23-16-10,10>>^ Fugiu a alegria e o regozijo do pomar; nas vinhas já não se canta, nem há júbilo algum; já não se pisarão as uvas nos lagares. Eu fiz cessar o eia dos pisadores.

[[v23-16-11]]

^<<v23-16-11,11>>^ Pelo que por Moabe vibra como harpa o meu íntimo, e o meu coração, por Quir-Heres.

[[v23-16-12]]

^<<v23-16-12,12>>^ Ver-se-á como Moabe se cansa nos altos, como entra no santuário a orar e nada alcança.

[[v23-16-13]]

^<<v23-16-13,13>>^ Esta é a palavra que o SENHOR há muito pronunciou contra Moabe.

[[v23-16-14]]

^<<v23-16-14,14>>^ Agora, porém, o SENHOR fala e diz: Dentro de três anos, tais como os de jornaleiros, será envilecida a glória de Moabe, com toda a sua grande multidão; e o restante será pouco, pequeno e débil.

'''

xref:023-isaias/023-isaias-015.adoc#v23-15-0[&#60; Capítulo Anterior] | <<v23-16-0,Topo>> | xref:023-isaias/023-isaias-017.adoc#v23-17-0[Próximo Capítulo &#62;]