include::./index.adoc[]

[[v23-64-0]]
=== Isaías, 64
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-64-1]]

^<<v23-64-1,1>>^ Oh! Se fendesses os céus e descesses! Se os montes tremessem na tua presença,

[[v23-64-2]]

^<<v23-64-2,2>>^ como quando o fogo inflama os gravetos, como quando faz ferver as águas, para fazeres notório o teu nome aos teus adversários, de sorte que as nações tremessem da tua presença!

[[v23-64-3]]

^<<v23-64-3,3>>^ Quando fizeste coisas terríveis, que não esperávamos, desceste, e os montes tremeram à tua presença.

[[v23-64-4]]

^<<v23-64-4,4>>^ Porque desde a antiguidade não se ouviu, nem com ouvidos se percebeu, nem com os olhos se viu Deus além de ti, que trabalha para aquele que nele espera.

[[v23-64-5]]

^<<v23-64-5,5>>^ Sais ao encontro daquele que com alegria pratica justiça, daqueles que se lembram de ti nos teus caminhos; eis que te iraste, porque pecamos; por muito tempo temos pecado e havemos de ser salvos?

[[v23-64-6]]

^<<v23-64-6,6>>^ Mas todos nós somos como o imundo, e todas as nossas justiças, como trapo da imundícia; todos nós murchamos como a folha, e as nossas iniquidades, como um vento, nos arrebatam.

[[v23-64-7]]

^<<v23-64-7,7>>^ Já ninguém há que invoque o teu nome, que se desperte e te detenha; porque escondes de nós o rosto e nos consomes por causa das nossas iniquidades.

[[v23-64-8]]

^<<v23-64-8,8>>^ Mas agora, ó SENHOR, tu és nosso Pai, nós somos o barro, e tu, o nosso oleiro; e todos nós, obra das tuas mãos.

[[v23-64-9]]

^<<v23-64-9,9>>^ Não te enfureças tanto, ó SENHOR, nem perpetuamente te lembres da nossa iniquidade; olha, pois, nós te pedimos: todos nós somos o teu povo.

[[v23-64-10]]

^<<v23-64-10,10>>^ As tuas santas cidades tornaram-se em deserto, Sião, em ermo; Jerusalém está assolada.

[[v23-64-11]]

^<<v23-64-11,11>>^ O nosso templo santo e glorioso, em que nossos pais te louvavam, foi queimado; todas as nossas coisas preciosas se tornaram em ruínas.

[[v23-64-12]]

^<<v23-64-12,12>>^ Conter-te-ias tu ainda, ó SENHOR, sobre estas calamidades? Ficarias calado e nos afligirias sobremaneira?

'''

xref:023-isaias/023-isaias-063.adoc#v23-63-0[&#60; Capítulo Anterior] | <<v23-64-0,Topo>> | xref:023-isaias/023-isaias-065.adoc#v23-65-0[Próximo Capítulo &#62;]