include::./index.adoc[]

[[v23-31-0]]
=== Isaías, 31
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-31-1]]

^<<v23-31-1,1>>^ Ai dos que descem ao Egito em busca de socorro e se estribam em cavalos; que confiam em carros, porque são muitos, e em cavaleiros, porque são mui fortes, mas não atentam para o Santo de Israel, nem buscam ao SENHOR!

[[v23-31-2]]

^<<v23-31-2,2>>^ Todavia, este é sábio, e faz vir o mal, e não retira as suas palavras; ele se levantará contra a casa dos malfeitores e contra a ajuda dos que praticam a iniquidade.

[[v23-31-3]]

^<<v23-31-3,3>>^ Pois os egípcios são homens e não deuses; os seus cavalos, carne e não espírito. Quando o SENHOR estender a mão, cairão por terra tanto o auxiliador como o ajudado, e ambos juntamente serão consumidos.

[[v23-31-4]]

^<<v23-31-4,4>>^ Porque assim me disse o SENHOR: Como o leão e o cachorro do leão rugem sobre a sua presa, ainda que se convoque contra eles grande número de pastores, e não se espantam das suas vozes, nem se abatem pela sua multidão, assim o SENHOR dos Exércitos descerá, para pelejar sobre o monte Sião e sobre o seu outeiro.

[[v23-31-5]]

^<<v23-31-5,5>>^ Como pairam as aves, assim o SENHOR dos Exércitos amparará a Jerusalém; protegê-la-á e salvá-la-á, poupá-la-á e livrá-la-á.

[[v23-31-6]]

^<<v23-31-6,6>>^ Convertei-vos, pois, ó filhos de Israel, àquele de quem tanto vos afastastes.

[[v23-31-7]]

^<<v23-31-7,7>>^ Pois, naquele dia, cada um lançará fora os seus ídolos de prata e os seus ídolos de ouro, que as vossas mãos fabricaram para pecardes.

[[v23-31-8]]

^<<v23-31-8,8>>^ Então, a Assíria cairá pela espada, não de homem; a espada, não de homem, a devorará; fugirá diante da espada, e os seus jovens serão sujeitos a trabalhos forçados.

[[v23-31-9]]

^<<v23-31-9,9>>^ De medo não atinará com a sua rocha de refúgio; os seus príncipes, espavoridos, desertarão a bandeira, diz o SENHOR, cujo fogo está em Sião e cuja fornalha, em Jerusalém.

'''

xref:023-isaias/023-isaias-030.adoc#v23-30-0[&#60; Capítulo Anterior] | <<v23-31-0,Topo>> | xref:023-isaias/023-isaias-032.adoc#v23-32-0[Próximo Capítulo &#62;]