include::./index.adoc[]

[[v23-18-0]]
=== Isaías, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-18-1]]

^<<v23-18-1,1>>^ Ai da terra onde há o roçar de muitas asas de insetos, que está além dos rios da Etiópia;

[[v23-18-2]]

^<<v23-18-2,2>>^ que envia embaixadores por mar em navios de papiro sobre as águas, dizendo: Ide, mensageiros velozes, a uma nação de homens altos e de pele brunida, a um povo terrível, de perto e de longe; a uma nação poderosa e esmagadora, cuja terra os rios dividem.

[[v23-18-3]]

^<<v23-18-3,3>>^ Vós, todos os habitantes do mundo, e vós, os moradores da terra, quando se arvorar a bandeira nos montes, olhai; e, quando se tocar a trombeta, escutai.

[[v23-18-4]]

^<<v23-18-4,4>>^ Porque assim me disse o SENHOR: Olhando da minha morada, estarei calmo como o ardor quieto do sol resplandecente, como a nuvem do orvalho no calor da sega.

[[v23-18-5]]

^<<v23-18-5,5>>^ Porque antes da vindima, caída já a flor, e quando as uvas amadurecem, então, podará os sarmentos com a foice e cortará os ramos que se estendem.

[[v23-18-6]]

^<<v23-18-6,6>>^ Serão deixados juntos às aves dos montes e aos animais da terra; sobre eles veranearão as aves de rapina, e todos os animais da terra passarão o inverno sobre eles.

[[v23-18-7]]

^<<v23-18-7,7>>^ Naquele tempo, será levado um presente ao SENHOR dos Exércitos por um povo de homens altos e de pele brunida, povo terrível, de perto e de longe; por uma nação poderosa e esmagadora, cuja terra os rios dividem, ao lugar do nome do SENHOR dos Exércitos, ao monte Sião.

'''

xref:023-isaias/023-isaias-017.adoc#v23-17-0[&#60; Capítulo Anterior] | <<v23-18-0,Topo>> | xref:023-isaias/023-isaias-019.adoc#v23-19-0[Próximo Capítulo &#62;]