include::./index.adoc[]

[[v23-12-0]]
=== Isaías, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-12-1]]

^<<v23-12-1,1>>^ Orarás naquele dia: Graças te dou, ó SENHOR, porque, ainda que te iraste contra mim, a tua ira se retirou, e tu me consolas.

[[v23-12-2]]

^<<v23-12-2,2>>^ Eis que Deus é a minha salvação; confiarei e não temerei, porque o SENHOR Deus é a minha força e o meu cântico; ele se tornou a minha salvação.

[[v23-12-3]]

^<<v23-12-3,3>>^ Vós, com alegria, tirareis água das fontes da salvação.

[[v23-12-4]]

^<<v23-12-4,4>>^ Direis naquele dia: Dai graças ao SENHOR, invocai o seu nome, tornai manifestos os seus feitos entre os povos, relembrai que é excelso o seu nome.

[[v23-12-5]]

^<<v23-12-5,5>>^ Cantai louvores ao SENHOR, porque fez coisas grandiosas; saiba-se isto em toda a terra.

[[v23-12-6]]

^<<v23-12-6,6>>^ Exulta e jubila, ó habitante de Sião, porque grande é o Santo de Israel no meio de ti.

'''

xref:023-isaias/023-isaias-011.adoc#v23-11-0[&#60; Capítulo Anterior] | <<v23-12-0,Topo>> | xref:023-isaias/023-isaias-013.adoc#v23-13-0[Próximo Capítulo &#62;]