include::./index.adoc[]

[[v23-24-0]]
=== Isaías, 24
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-24-1]]

^<<v23-24-1,1>>^ Eis que o SENHOR vai devastar e desolar a terra, vai transtornar a sua superfície e lhe dispersar os moradores.

[[v23-24-2]]

^<<v23-24-2,2>>^ O que suceder ao povo sucederá ao sacerdote; ao servo, como ao seu senhor; à serva, como à sua dona; ao comprador, como ao vendedor; ao que empresta, como ao que toma emprestado; ao credor, como ao devedor.

[[v23-24-3]]

^<<v23-24-3,3>>^ A terra será de todo devastada e totalmente saqueada, porque o SENHOR é quem proferiu esta palavra.

[[v23-24-4]]

^<<v23-24-4,4>>^ A terra pranteia e se murcha; o mundo enfraquece e se murcha; enlanguescem os mais altos do povo da terra.

[[v23-24-5]]

^<<v23-24-5,5>>^ Na verdade, a terra está contaminada por causa dos seus moradores, porquanto transgridem as leis, violam os estatutos e quebram a aliança eterna.

[[v23-24-6]]

^<<v23-24-6,6>>^ Por isso, a maldição consome a terra, e os que habitam nela se tornam culpados; por isso, serão queimados os moradores da terra, e poucos homens restarão.

[[v23-24-7]]

^<<v23-24-7,7>>^ Pranteia o vinho, enlanguesce a vide, e gemem todos os que estavam de coração alegre.

[[v23-24-8]]

^<<v23-24-8,8>>^ Cessou o folguedo dos tamboris, acabou o ruído dos que exultam, e descansou a alegria da harpa.

[[v23-24-9]]

^<<v23-24-9,9>>^ Já não se bebe vinho entre canções; a bebida forte é amarga para os que a bebem.

[[v23-24-10]]

^<<v23-24-10,10>>^ Demolida está a cidade caótica, todas as casas estão fechadas, ninguém já pode entrar.

[[v23-24-11]]

^<<v23-24-11,11>>^ Gritam por vinho nas ruas, fez-se noite para toda alegria, foi banido da terra o prazer.

[[v23-24-12]]

^<<v23-24-12,12>>^ Na cidade, reina a desolação, e a porta está reduzida a ruínas.

[[v23-24-13]]

^<<v23-24-13,13>>^ Porque será na terra, no meio destes povos, como o varejar da oliveira e como o rebuscar, quando está acabada a vindima.

[[v23-24-14]]

^<<v23-24-14,14>>^ Eles levantam a voz e cantam com alegria; por causa da glória do SENHOR, exultam desde o mar.

[[v23-24-15]]

^<<v23-24-15,15>>^ Por isso, glorificai ao SENHOR no Oriente e, nas terras do mar, ao nome do SENHOR, Deus de Israel.

[[v23-24-16]]

^<<v23-24-16,16>>^ Dos confins da terra ouvimos cantar: Glória ao Justo! Mas eu digo: definho, definho, ai de mim! Os pérfidos tratam perfidamente; sim, os pérfidos tratam mui perfidamente.

[[v23-24-17]]

^<<v23-24-17,17>>^ Terror, cova e laço vêm sobre ti, ó morador da terra.

[[v23-24-18]]

^<<v23-24-18,18>>^ E será que aquele que fugir da voz do terror cairá na cova, e, se sair da cova, o laço o prenderá; porque as represas do alto se abrem, e tremem os fundamentos da terra.

[[v23-24-19]]

^<<v23-24-19,19>>^ A terra será de todo quebrantada, ela totalmente se romperá, a terra violentamente se moverá.

[[v23-24-20]]

^<<v23-24-20,20>>^ A terra cambaleará como um bêbado e balanceará como rede de dormir; a sua transgressão pesa sobre ela, ela cairá e jamais se levantará.

[[v23-24-21]]

^<<v23-24-21,21>>^ Naquele dia, o SENHOR castigará, no céu, as hostes celestes, e os reis da terra, na terra.

[[v23-24-22]]

^<<v23-24-22,22>>^ Serão ajuntados como presos em masmorra, e encerrados num cárcere, e castigados depois de muitos dias.

[[v23-24-23]]

^<<v23-24-23,23>>^ A lua se envergonhará, e o sol se confundirá quando o SENHOR dos Exércitos reinar no monte Sião e em Jerusalém; perante os seus anciãos haverá glória.

'''

xref:023-isaias/023-isaias-023.adoc#v23-23-0[&#60; Capítulo Anterior] | <<v23-24-0,Topo>> | xref:023-isaias/023-isaias-025.adoc#v23-25-0[Próximo Capítulo &#62;]