include::./index.adoc[]

[[v23-28-0]]
=== Isaías, 28
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-28-1]]

^<<v23-28-1,1>>^ Ai da soberba coroa dos bêbados de Efraim e da flor caduca da sua gloriosa formosura que está sobre a parte alta do fertilíssimo vale dos vencidos do vinho!

[[v23-28-2]]

^<<v23-28-2,2>>^ Eis que o Senhor tem certo homem valente e poderoso; este, como uma queda de saraiva, como uma tormenta de destruição e como uma tempestade de impetuosas águas que transbordam, com poder as derribará por terra.

[[v23-28-3]]

^<<v23-28-3,3>>^ A soberba coroa dos bêbados de Efraim será pisada aos pés.

[[v23-28-4]]

^<<v23-28-4,4>>^ A flor caduca da sua gloriosa formosura, que está sobre a parte alta do fertilíssimo vale, será como o figo prematuro, que amadurece antes do verão, o qual, em pondo nele alguém os olhos, mal o apanha, já o devora.

[[v23-28-5]]

^<<v23-28-5,5>>^ Naquele dia, o SENHOR dos Exércitos será a coroa de glória e o formoso diadema para os restantes de seu povo;

[[v23-28-6]]

^<<v23-28-6,6>>^ será o espírito de justiça para o que se assenta a julgar e fortaleza para os que fazem recuar o assalto contra as portas.

[[v23-28-7]]

^<<v23-28-7,7>>^ Mas também estes cambaleiam por causa do vinho e não podem ter-se em pé por causa da bebida forte; o sacerdote e o profeta cambaleiam por causa da bebida forte, são vencidos pelo vinho, não podem ter-se em pé por causa da bebida forte; erram na visão, tropeçam no juízo.

[[v23-28-8]]

^<<v23-28-8,8>>^ Porque todas as mesas estão cheias de vômitos, e não há lugar sem imundícia.

[[v23-28-9]]

^<<v23-28-9,9>>^ A quem, pois, se ensinaria o conhecimento? E a quem se daria a entender o que se ouviu? Acaso, aos desmamados e aos que foram afastados dos seios maternos?

[[v23-28-10]]

^<<v23-28-10,10>>^ Porque é preceito sobre preceito, preceito e mais preceito; regra sobre regra, regra e mais regra; um pouco aqui, um pouco ali.

[[v23-28-11]]

^<<v23-28-11,11>>^ Pelo que por lábios gaguejantes e por língua estranha falará o SENHOR a este povo,

[[v23-28-12]]

^<<v23-28-12,12>>^ ao qual ele disse: Este é o descanso, dai descanso ao cansado; e este é o refrigério; mas não quiseram ouvir.

[[v23-28-13]]

^<<v23-28-13,13>>^ Assim, pois, a palavra do SENHOR lhes será preceito sobre preceito, preceito e mais preceito; regra sobre regra, regra e mais regra; um pouco aqui, um pouco ali; para que vão, e caiam para trás, e se quebrantem, se enlacem, e sejam presos.

[[v23-28-14]]

^<<v23-28-14,14>>^ Ouvi, pois, a palavra do SENHOR, homens escarnecedores, que dominais este povo que está em Jerusalém.

[[v23-28-15]]

^<<v23-28-15,15>>^ Porquanto dizeis: Fizemos aliança com a morte e com o além fizemos acordo; quando passar o dilúvio do açoite, não chegará a nós, porque, por nosso refúgio, temos a mentira e debaixo da falsidade nos temos escondido.

[[v23-28-16]]

^<<v23-28-16,16>>^ Portanto, assim diz o SENHOR Deus: Eis que eu assentei em Sião uma pedra, pedra já provada, pedra preciosa, angular, solidamente assentada; aquele que crer não foge.

[[v23-28-17]]

^<<v23-28-17,17>>^ Farei do juízo a régua e da justiça, o prumo; a saraiva varrerá o refúgio da mentira, e as águas arrastarão o esconderijo.

[[v23-28-18]]

^<<v23-28-18,18>>^ A vossa aliança com a morte será anulada, e o vosso acordo com o além não subsistirá; e, quando o dilúvio do açoite passar, sereis esmagados por ele.

[[v23-28-19]]

^<<v23-28-19,19>>^ Todas as vezes que passar, vos arrebatará, porque passará manhã após manhã, e todos os dias, e todas as noites; e será puro terror o só ouvir tal notícia.

[[v23-28-20]]

^<<v23-28-20,20>>^ Porque a cama será tão curta, que ninguém se poderá estender nela; e o cobertor, tão estreito, que ninguém se poderá cobrir com ele.

[[v23-28-21]]

^<<v23-28-21,21>>^ Porque o SENHOR se levantará, como no monte Perazim, e se irará, como no vale de Gibeão, para realizar a sua obra, a sua obra estranha, e para executar o seu ato, o seu ato inaudito.

[[v23-28-22]]

^<<v23-28-22,22>>^ Agora, pois, não mais escarneçais, para que os vossos grilhões não se façam mais fortes; porque já do Senhor, o SENHOR dos Exércitos, ouvi falar de uma destruição, e essa já está determinada sobre toda a terra.

[[v23-28-23]]

^<<v23-28-23,23>>^ Inclinai os ouvidos e ouvi a minha voz; atendei bem e ouvi o meu discurso.

[[v23-28-24]]

^<<v23-28-24,24>>^ Porventura, lavra todo dia o lavrador, para semear? Ou todo dia sulca a sua terra e a esterroa?

[[v23-28-25]]

^<<v23-28-25,25>>^ Porventura, quando já tem nivelado a superfície, não lhe espalha o endro, não semeia o cominho, não lança nela o trigo em leiras, ou cevada, no devido lugar, ou a espelta, na margem?

[[v23-28-26]]

^<<v23-28-26,26>>^ Pois o seu Deus assim o instrui devidamente e o ensina.

[[v23-28-27]]

^<<v23-28-27,27>>^ Porque o endro não se trilha com instrumento de trilhar, nem sobre o cominho se passa roda de carro; mas com vara se sacode o endro, e o cominho, com pau.

[[v23-28-28]]

^<<v23-28-28,28>>^ Acaso, é esmiuçado o cereal? Não; o lavrador nem sempre o está debulhando, nem sempre está fazendo passar por cima dele a roda do seu carro e os seus cavalos.

[[v23-28-29]]

^<<v23-28-29,29>>^ Também isso procede do SENHOR dos Exércitos; ele é maravilhoso em conselho e grande em sabedoria.

'''

xref:023-isaias/023-isaias-027.adoc#v23-27-0[&#60; Capítulo Anterior] | <<v23-28-0,Topo>> | xref:023-isaias/023-isaias-029.adoc#v23-29-0[Próximo Capítulo &#62;]