include::./index.adoc[]

[[v23-35-0]]
=== Isaías, 35
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-35-1]]

^<<v23-35-1,1>>^ O deserto e a terra se alegrarão; o ermo exultará e florescerá como o narciso.

[[v23-35-2]]

^<<v23-35-2,2>>^ Florescerá abundantemente, jubilará de alegria e exultará; deu-se-lhes a glória do Líbano, o esplendor do Carmelo e de Sarom; eles verão a glória do SENHOR, o esplendor do nosso Deus.

[[v23-35-3]]

^<<v23-35-3,3>>^ Fortalecei as mãos frouxas e firmai os joelhos vacilantes.

[[v23-35-4]]

^<<v23-35-4,4>>^ Dizei aos desalentados de coração: Sede fortes, não temais. Eis o vosso Deus. A vingança vem, a retribuição de Deus; ele vem e vos salvará.

[[v23-35-5]]

^<<v23-35-5,5>>^ Então, se abrirão os olhos dos cegos, e se desimpedirão os ouvidos dos surdos;

[[v23-35-6]]

^<<v23-35-6,6>>^ os coxos saltarão como cervos, e a língua dos mudos cantará; pois águas arrebentarão no deserto, e ribeiros, no ermo.

[[v23-35-7]]

^<<v23-35-7,7>>^ A areia esbraseada se transformará em lagos, e a terra sedenta, em mananciais de águas; onde outrora viviam os chacais, crescerá a erva com canas e juncos.

[[v23-35-8]]

^<<v23-35-8,8>>^ E ali haverá bom caminho, caminho que se chamará o Caminho Santo; o imundo não passará por ele, pois será somente para o seu povo; quem quer que por ele caminhe não errará, nem mesmo o louco.

[[v23-35-9]]

^<<v23-35-9,9>>^ Ali não haverá leão, animal feroz não passará por ele, nem se achará nele; mas os remidos andarão por ele.

[[v23-35-10]]

^<<v23-35-10,10>>^ Os resgatados do SENHOR voltarão e virão a Sião com cânticos de júbilo; alegria eterna coroará a sua cabeça; gozo e alegria alcançarão, e deles fugirá a tristeza e o gemido.

'''

xref:023-isaias/023-isaias-034.adoc#v23-34-0[&#60; Capítulo Anterior] | <<v23-35-0,Topo>> | xref:023-isaias/023-isaias-036.adoc#v23-36-0[Próximo Capítulo &#62;]