include::./index.adoc[]

[[v23-45-0]]
=== Isaías, 45
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-45-1]]

^<<v23-45-1,1>>^ Assim diz o SENHOR ao seu ungido, a Ciro, a quem tomo pela mão direita, para abater as nações ante a sua face, e para descingir os lombos dos reis, e para abrir diante dele as portas, que não se fecharão.

[[v23-45-2]]

^<<v23-45-2,2>>^ Eu irei adiante de ti, endireitarei os caminhos tortuosos, quebrarei as portas de bronze e despedaçarei as trancas de ferro;

[[v23-45-3]]

^<<v23-45-3,3>>^ dar-te-ei os tesouros escondidos e as riquezas encobertas, para que saibas que eu sou o SENHOR, o Deus de Israel, que te chama pelo teu nome.

[[v23-45-4]]

^<<v23-45-4,4>>^ Por amor do meu servo Jacó e de Israel, meu escolhido, eu te chamei pelo teu nome e te pus o sobrenome, ainda que não me conheces.

[[v23-45-5]]

^<<v23-45-5,5>>^ Eu sou o SENHOR, e não há outro; além de mim não há Deus; eu te cingirei, ainda que não me conheces.

[[v23-45-6]]

^<<v23-45-6,6>>^ Para que se saiba, até ao nascente do sol e até ao poente, que além de mim não há outro; eu sou o SENHOR, e não há outro.

[[v23-45-7]]

^<<v23-45-7,7>>^ Eu formo a luz e crio as trevas; faço a paz e crio o mal; eu, o SENHOR, faço todas estas coisas.

[[v23-45-8]]

^<<v23-45-8,8>>^ Destilai, ó céus, dessas alturas, e as nuvens chovam justiça; abra-se a terra e produza a salvação, e juntamente com ela brote a justiça; eu, o SENHOR, as criei.

[[v23-45-9]]

^<<v23-45-9,9>>^ Ai daquele que contende com o seu Criador! E não passa de um caco de barro entre outros cacos. Acaso, dirá o barro ao que lhe dá forma: Que fazes? Ou: A tua obra não tem alça.

[[v23-45-10]]

^<<v23-45-10,10>>^ Ai daquele que diz ao pai: Por que geras? E à mulher: Por que dás à luz?

[[v23-45-11]]

^<<v23-45-11,11>>^ Assim diz o SENHOR, o Santo de Israel, aquele que o formou: Quereis, acaso, saber as coisas futuras? Quereis dar ordens acerca de meus filhos e acerca das obras de minhas mãos?

[[v23-45-12]]

^<<v23-45-12,12>>^ Eu fiz a terra e criei nela o homem; as minhas mãos estenderam os céus, e a todos os seus exércitos dei as minhas ordens.

[[v23-45-13]]

^<<v23-45-13,13>>^ Eu, na minha justiça, suscitei a Ciro e todos os seus caminhos endireitarei; ele edificará a minha cidade e libertará os meus exilados, não por preço nem por presentes, diz o SENHOR dos Exércitos.

[[v23-45-14]]

^<<v23-45-14,14>>^ Assim diz o SENHOR: A riqueza do Egito, e as mercadorias da Etiópia, e os sabeus, homens de grande estatura, passarão ao teu poder e serão teus; seguir-te-ão, irão em grilhões, diante de ti se prostrarão e te farão as suas súplicas, dizendo: Só contigo está Deus, e não há outro que seja Deus.

[[v23-45-15]]

^<<v23-45-15,15>>^ Verdadeiramente, tu és Deus misterioso, ó Deus de Israel, ó Salvador.

[[v23-45-16]]

^<<v23-45-16,16>>^ Envergonhar-se-ão e serão confundidos todos eles; cairão, à uma, em ignomínia os que fabricam ídolos.

[[v23-45-17]]

^<<v23-45-17,17>>^ Israel, porém, será salvo pelo SENHOR com salvação eterna; não sereis envergonhados, nem confundidos em toda a eternidade.

[[v23-45-18]]

^<<v23-45-18,18>>^ Porque assim diz o SENHOR, que criou os céus, o Deus que formou a terra, que a fez e a estabeleceu; que não a criou para ser um caos, mas para ser habitada: Eu sou o SENHOR, e não há outro.

[[v23-45-19]]

^<<v23-45-19,19>>^ Não falei em segredo, nem em lugar algum de trevas da terra; não disse à descendência de Jacó: Buscai-me em vão; eu, o SENHOR, falo a verdade e proclamo o que é direito.

[[v23-45-20]]

^<<v23-45-20,20>>^ Congregai-vos e vinde; chegai-vos todos juntos, vós que escapastes das nações; nada sabem os que carregam o lenho das suas imagens de escultura e fazem súplicas a um deus que não pode salvar.

[[v23-45-21]]

^<<v23-45-21,21>>^ Declarai e apresentai as vossas razões. Que tomem conselho uns com os outros. Quem fez ouvir isto desde a antiguidade? Quem desde aquele tempo o anunciou? Porventura, não o fiz eu, o SENHOR? Pois não há outro Deus, senão eu, Deus justo e Salvador não há além de mim.

[[v23-45-22]]

^<<v23-45-22,22>>^ Olhai para mim e sede salvos, vós, todos os limites da terra; porque eu sou Deus, e não há outro.

[[v23-45-23]]

^<<v23-45-23,23>>^ Por mim mesmo tenho jurado; da minha boca saiu o que é justo, e a minha palavra não tornará atrás. Diante de mim se dobrará todo joelho, e jurará toda língua.

[[v23-45-24]]

^<<v23-45-24,24>>^ De mim se dirá: Tão somente no SENHOR há justiça e força; até ele virão e serão envergonhados todos os que se irritarem contra ele.

[[v23-45-25]]

^<<v23-45-25,25>>^ Mas no SENHOR será justificada toda a descendência de Israel e nele se gloriará.

'''

xref:023-isaias/023-isaias-044.adoc#v23-44-0[&#60; Capítulo Anterior] | <<v23-45-0,Topo>> | xref:023-isaias/023-isaias-046.adoc#v23-46-0[Próximo Capítulo &#62;]