include::./index.adoc[]

[[v23-53-0]]
=== Isaías, 53
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-53-1]]

^<<v23-53-1,1>>^ Quem creu em nossa pregação? E a quem foi revelado o braço do SENHOR?

[[v23-53-2]]

^<<v23-53-2,2>>^ Porque foi subindo como renovo perante ele e como raiz de uma terra seca; não tinha aparência nem formosura; olhamo-lo, mas nenhuma beleza havia que nos agradasse.

[[v23-53-3]]

^<<v23-53-3,3>>^ Era desprezado e o mais rejeitado entre os homens; homem de dores e que sabe o que é padecer; e, como um de quem os homens escondem o rosto, era desprezado, e dele não fizemos caso.

[[v23-53-4]]

^<<v23-53-4,4>>^ Certamente, ele tomou sobre si as nossas enfermidades e as nossas dores levou sobre si; e nós o reputávamos por aflito, ferido de Deus e oprimido.

[[v23-53-5]]

^<<v23-53-5,5>>^ Mas ele foi traspassado pelas nossas transgressões e moído pelas nossas iniquidades; o castigo que nos traz a paz estava sobre ele, e pelas suas pisaduras fomos sarados.

[[v23-53-6]]

^<<v23-53-6,6>>^ Todos nós andávamos desgarrados como ovelhas; cada um se desviava pelo caminho, mas o SENHOR fez cair sobre ele a iniquidade de nós todos.

[[v23-53-7]]

^<<v23-53-7,7>>^ Ele foi oprimido e humilhado, mas não abriu a boca; como cordeiro foi levado ao matadouro; e, como ovelha muda perante os seus tosquiadores, ele não abriu a boca.

[[v23-53-8]]

^<<v23-53-8,8>>^ Por juízo opressor foi arrebatado, e de sua linhagem, quem dela cogitou? Porquanto foi cortado da terra dos viventes; por causa da transgressão do meu povo, foi ele ferido.

[[v23-53-9]]

^<<v23-53-9,9>>^ Designaram-lhe a sepultura com os perversos, mas com o rico esteve na sua morte, posto que nunca fez injustiça, nem dolo algum se achou em sua boca.

[[v23-53-10]]

^<<v23-53-10,10>>^ Todavia, ao SENHOR agradou moê-lo, fazendo-o enfermar; quando der ele a sua alma como oferta pelo pecado, verá a sua posteridade e prolongará os seus dias; e a vontade do SENHOR prosperará nas suas mãos.

[[v23-53-11]]

^<<v23-53-11,11>>^ Ele verá o fruto do penoso trabalho de sua alma e ficará satisfeito; o meu Servo, o Justo, com o seu conhecimento, justificará a muitos, porque as iniquidades deles levará sobre si.

[[v23-53-12]]

^<<v23-53-12,12>>^ Por isso, eu lhe darei muitos como a sua parte, e com os poderosos repartirá ele o despojo, porquanto derramou a sua alma na morte; foi contado com os transgressores; contudo, levou sobre si o pecado de muitos e pelos transgressores intercedeu.

'''

xref:023-isaias/023-isaias-052.adoc#v23-52-0[&#60; Capítulo Anterior] | <<v23-53-0,Topo>> | xref:023-isaias/023-isaias-054.adoc#v23-54-0[Próximo Capítulo &#62;]