include::./index.adoc[]

[[v23-48-0]]
=== Isaías, 48
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-48-1]]

^<<v23-48-1,1>>^ Ouvi isto, casa de Jacó, que vos chamais pelo nome de Israel e saístes da linhagem de Judá, que jurais pelo nome do SENHOR e confessais o Deus de Israel, mas não em verdade nem em justiça.

[[v23-48-2]]

^<<v23-48-2,2>>^ (Da santa cidade tomam o nome e se firmam sobre o Deus de Israel, cujo nome é SENHOR dos Exércitos.)

[[v23-48-3]]

^<<v23-48-3,3>>^ As primeiras coisas, desde a antiguidade, as anunciei; sim, pronunciou-as a minha boca, e eu as fiz ouvir; de repente agi, e elas se cumpriram.

[[v23-48-4]]

^<<v23-48-4,4>>^ Porque eu sabia que eras obstinado, e a tua cerviz é um tendão de ferro, e tens a testa de bronze.

[[v23-48-5]]

^<<v23-48-5,5>>^ Por isso, to anunciei desde aquele tempo e to dei a conhecer antes que acontecesse, para que não dissesses: O meu ídolo fez estas coisas; ou: A minha imagem de escultura e a fundição as ordenaram.

[[v23-48-6]]

^<<v23-48-6,6>>^ Já o tens ouvido; olha para tudo isto; porventura, não o admites? Desde agora te faço ouvir coisas novas e ocultas, que não conhecias.

[[v23-48-7]]

^<<v23-48-7,7>>^ Apareceram agora e não há muito, e antes deste dia delas não ouviste, para que não digas: Eis que já o sabia.

[[v23-48-8]]

^<<v23-48-8,8>>^ Tu nem as ouviste, nem as conheceste, nem tampouco antecipadamente se te abriram os ouvidos, porque eu sabia que procederias mui perfidamente e eras chamado de transgressor desde o ventre materno.

[[v23-48-9]]

^<<v23-48-9,9>>^ Por amor do meu nome, retardarei a minha ira e por causa da minha honra me conterei para contigo, para que te não venha a exterminar.

[[v23-48-10]]

^<<v23-48-10,10>>^ Eis que te acrisolei, mas disso não resultou prata; provei-te na fornalha da aflição.

[[v23-48-11]]

^<<v23-48-11,11>>^ Por amor de mim, por amor de mim, é que faço isto; porque como seria profanado o meu nome? A minha glória, não a dou a outrem.

[[v23-48-12]]

^<<v23-48-12,12>>^ Dá-me ouvidos, ó Jacó, e tu, ó Israel, a quem chamei; eu sou o mesmo, sou o primeiro e também o último.

[[v23-48-13]]

^<<v23-48-13,13>>^ Também a minha mão fundou a terra, e a minha destra estendeu os céus; quando eu os chamar, eles se apresentarão juntos.

[[v23-48-14]]

^<<v23-48-14,14>>^ Ajuntai-vos, todos vós, e ouvi! Quem, dentre eles, tem anunciado estas coisas? O SENHOR amou a Ciro e executará a sua vontade contra a Babilônia, e o seu braço será contra os caldeus.

[[v23-48-15]]

^<<v23-48-15,15>>^ Eu, eu tenho falado; também já o chamei. Eu o trouxe e farei próspero o seu caminho.

[[v23-48-16]]

^<<v23-48-16,16>>^ Chegai-vos a mim e ouvi isto: não falei em segredo desde o princípio; desde o tempo em que isso vem acontecendo, tenho estado lá. Agora, o SENHOR Deus me enviou a mim e o seu Espírito.

[[v23-48-17]]

^<<v23-48-17,17>>^ Assim diz o SENHOR, o teu Redentor, o Santo de Israel: Eu sou o SENHOR, o teu Deus, que te ensina o que é útil e te guia pelo caminho em que deves andar.

[[v23-48-18]]

^<<v23-48-18,18>>^ Ah! Se tivesses dado ouvidos aos meus mandamentos! Então, seria a tua paz como um rio, e a tua justiça, como as ondas do mar.

[[v23-48-19]]

^<<v23-48-19,19>>^ Também a tua posteridade seria como a areia, e os teus descendentes, como os grãos da areia; o seu nome nunca seria eliminado nem destruído de diante de mim.

[[v23-48-20]]

^<<v23-48-20,20>>^ Saí da Babilônia, fugi de entre os caldeus e anunciai isto com voz de júbilo; proclamai-o e levai-o até ao fim da terra; dizei: O SENHOR remiu a seu servo Jacó.

[[v23-48-21]]

^<<v23-48-21,21>>^ Não padeceram sede, quando ele os levava pelos desertos; fez-lhes correr água da rocha; fendeu a pedra, e as águas correram.

[[v23-48-22]]

^<<v23-48-22,22>>^ Para os perversos, todavia, não há paz, diz o SENHOR.

'''

xref:023-isaias/023-isaias-047.adoc#v23-47-0[&#60; Capítulo Anterior] | <<v23-48-0,Topo>> | xref:023-isaias/023-isaias-049.adoc#v23-49-0[Próximo Capítulo &#62;]