include::./index.adoc[]

[[v23-32-0]]
=== Isaías, 32
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-32-1]]

^<<v23-32-1,1>>^ Eis aí está que reinará um rei com justiça, e em retidão governarão príncipes.

[[v23-32-2]]

^<<v23-32-2,2>>^ Cada um servirá de esconderijo contra o vento, de refúgio contra a tempestade, de torrentes de águas em lugares secos e de sombra de grande rocha em terra sedenta.

[[v23-32-3]]

^<<v23-32-3,3>>^ Os olhos dos que veem não se ofuscarão, e os ouvidos dos que ouvem estarão atentos.

[[v23-32-4]]

^<<v23-32-4,4>>^ O coração dos temerários saberá compreender, e a língua dos gagos falará pronta e distintamente.

[[v23-32-5]]

^<<v23-32-5,5>>^ Ao louco nunca mais se chamará nobre, e do fraudulento jamais se dirá que é magnânimo.

[[v23-32-6]]

^<<v23-32-6,6>>^ Porque o louco fala loucamente, e o seu coração obra o que é iníquo, para usar de impiedade e para proferir mentiras contra o SENHOR, para deixar o faminto na ânsia da sua fome e fazer que o sedento venha a ter falta de bebida.

[[v23-32-7]]

^<<v23-32-7,7>>^ Também as armas do fraudulento são más; ele maquina intrigas para arruinar os desvalidos, com palavras falsas, ainda quando a causa do pobre é justa.

[[v23-32-8]]

^<<v23-32-8,8>>^ Mas o nobre projeta coisas nobres e na sua nobreza perseverará.

[[v23-32-9]]

^<<v23-32-9,9>>^ Levantai-vos, mulheres que viveis despreocupadamente, e ouvi a minha voz; vós, filhas, que estais confiantes, inclinai os ouvidos às minhas palavras.

[[v23-32-10]]

^<<v23-32-10,10>>^ Porque daqui a um ano e dias vireis a tremer, ó mulheres que estais confiantes, porque a vindima se acabará, e não haverá colheita.

[[v23-32-11]]

^<<v23-32-11,11>>^ Tremei, mulheres que viveis despreocupadamente; turbai-vos, vós que estais confiantes. Despi-vos, e ponde-vos desnudas, e cingi com panos de saco os lombos.

[[v23-32-12]]

^<<v23-32-12,12>>^ Batei no peito por causa dos campos aprazíveis e por causa das vinhas frutíferas.

[[v23-32-13]]

^<<v23-32-13,13>>^ Sobre a terra do meu povo virão espinheiros e abrolhos, como também sobre todas as casas onde há alegria, na cidade que exulta.

[[v23-32-14]]

^<<v23-32-14,14>>^ O palácio será abandonado, a cidade populosa ficará deserta; Ofel e a torre da guarda servirão de cavernas para sempre, folga para os jumentos selvagens e pastos para os rebanhos;

[[v23-32-15]]

^<<v23-32-15,15>>^ até que se derrame sobre nós o Espírito lá do alto; então, o deserto se tornará em pomar, e o pomar será tido por bosque;

[[v23-32-16]]

^<<v23-32-16,16>>^ o juízo habitará no deserto, e a justiça morará no pomar.

[[v23-32-17]]

^<<v23-32-17,17>>^ O efeito da justiça será paz, e o fruto da justiça, repouso e segurança, para sempre.

[[v23-32-18]]

^<<v23-32-18,18>>^ O meu povo habitará em moradas de paz, em moradas bem seguras e em lugares quietos e tranquilos,

[[v23-32-19]]

^<<v23-32-19,19>>^ ainda que haja saraivada, caia o bosque e seja a cidade inteiramente abatida.

[[v23-32-20]]

^<<v23-32-20,20>>^ Bem-aventurados vós, os que semeais junto a todas as águas e dais liberdade ao pé do boi e do jumento.

'''

xref:023-isaias/023-isaias-031.adoc#v23-31-0[&#60; Capítulo Anterior] | <<v23-32-0,Topo>> | xref:023-isaias/023-isaias-033.adoc#v23-33-0[Próximo Capítulo &#62;]