include::./index.adoc[]

[[v23-42-0]]
=== Isaías, 42
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-42-1]]

^<<v23-42-1,1>>^ Eis aqui o meu servo, a quem sustenho; o meu escolhido, em quem a minha alma se compraz; pus sobre ele o meu Espírito, e ele promulgará o direito para os gentios.

[[v23-42-2]]

^<<v23-42-2,2>>^ Não clamará, nem gritará, nem fará ouvir a sua voz na praça.

[[v23-42-3]]

^<<v23-42-3,3>>^ Não esmagará a cana quebrada, nem apagará a torcida que fumega; em verdade, promulgará o direito.

[[v23-42-4]]

^<<v23-42-4,4>>^ Não desanimará, nem se quebrará até que ponha na terra o direito; e as terras do mar aguardarão a sua doutrina.

[[v23-42-5]]

^<<v23-42-5,5>>^ Assim diz Deus, o SENHOR, que criou os céus e os estendeu, formou a terra e a tudo quanto produz; que dá fôlego de vida ao povo que nela está e o espírito aos que andam nela.

[[v23-42-6]]

^<<v23-42-6,6>>^ Eu, o SENHOR, te chamei em justiça, tomar-te-ei pela mão, e te guardarei, e te farei mediador da aliança com o povo e luz para os gentios;

[[v23-42-7]]

^<<v23-42-7,7>>^ para abrires os olhos aos cegos, para tirares da prisão o cativo e do cárcere, os que jazem em trevas.

[[v23-42-8]]

^<<v23-42-8,8>>^ Eu sou o SENHOR, este é o meu nome; a minha glória, pois, não a darei a outrem, nem a minha honra, às imagens de escultura.

[[v23-42-9]]

^<<v23-42-9,9>>^ Eis que as primeiras predições já se cumpriram, e novas coisas eu vos anuncio; e, antes que sucedam, eu vo-las farei ouvir.

[[v23-42-10]]

^<<v23-42-10,10>>^ Cantai ao SENHOR um cântico novo e o seu louvor até às extremidades da terra, vós, os que navegais pelo mar e tudo quanto há nele, vós, terras do mar e seus moradores.

[[v23-42-11]]

^<<v23-42-11,11>>^ Alcem a voz o deserto, as suas cidades e as aldeias habitadas por Quedar; exultem os que habitam nas rochas e clamem do cimo dos montes;

[[v23-42-12]]

^<<v23-42-12,12>>^ deem honra ao SENHOR e anunciem a sua glória nas terras do mar.

[[v23-42-13]]

^<<v23-42-13,13>>^ O SENHOR sairá como valente, despertará o seu zelo como homem de guerra; clamará, lançará forte grito de guerra e mostrará sua força contra os seus inimigos.

[[v23-42-14]]

^<<v23-42-14,14>>^ Por muito tempo me calei, estive em silêncio e me contive; mas agora darei gritos como a parturiente, e ao mesmo tempo ofegarei, e estarei esbaforido.

[[v23-42-15]]

^<<v23-42-15,15>>^ Os montes e outeiros devastarei e toda a sua erva farei secar; tornarei os rios em terra firme e secarei os lagos.

[[v23-42-16]]

^<<v23-42-16,16>>^ Guiarei os cegos por um caminho que não conhecem, fá-los-ei andar por veredas desconhecidas; tornarei as trevas em luz perante eles e os caminhos escabrosos, planos. Estas coisas lhes farei e jamais os desampararei.

[[v23-42-17]]

^<<v23-42-17,17>>^ Tornarão atrás e confundir-se-ão de vergonha os que confiam em imagens de escultura e às imagens de fundição dizem: Vós sois nossos deuses.

[[v23-42-18]]

^<<v23-42-18,18>>^ Surdos, ouvi, e vós, cegos, olhai, para que possais ver.

[[v23-42-19]]

^<<v23-42-19,19>>^ Quem é cego, como o meu servo, ou surdo, como o meu mensageiro, a quem envio? Quem é cego, como o meu amigo, e cego, como o servo do SENHOR?

[[v23-42-20]]

^<<v23-42-20,20>>^ Tu vês muitas coisas, mas não as observas; ainda que tens os ouvidos abertos, nada ouves.

[[v23-42-21]]

^<<v23-42-21,21>>^ Foi do agrado do SENHOR, por amor da sua própria justiça, engrandecer a lei e fazê-la gloriosa.

[[v23-42-22]]

^<<v23-42-22,22>>^ Não obstante, é um povo roubado e saqueado; todos estão enlaçados em cavernas e escondidos em cárceres; são postos como presa, e ninguém há que os livre; por despojo, e ninguém diz: Restitui.

[[v23-42-23]]

^<<v23-42-23,23>>^ Quem há entre vós que ouça isto? Que atenda e ouça o que há de ser depois?

[[v23-42-24]]

^<<v23-42-24,24>>^ Quem entregou Jacó por despojo e Israel, aos roubadores? Acaso, não foi o SENHOR, aquele contra quem pecaram e nos caminhos do qual não queriam andar, não dando ouvidos à sua lei?

[[v23-42-25]]

^<<v23-42-25,25>>^ Pelo que derramou sobre eles o furor da sua ira e a violência da guerra; isto lhes ateou fogo ao redor, contudo, não o entenderam; e os queimou, mas não fizeram caso.

'''

xref:023-isaias/023-isaias-041.adoc#v23-41-0[&#60; Capítulo Anterior] | <<v23-42-0,Topo>> | xref:023-isaias/023-isaias-043.adoc#v23-43-0[Próximo Capítulo &#62;]