include::./index.adoc[]

[[v23-39-0]]
=== Isaías, 39
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-39-1]]

^<<v23-39-1,1>>^ Nesse tempo, Merodaque-Baladã, filho de Baladã, rei da Babilônia, enviou cartas e um presente a Ezequias, porque soube que estivera doente e já tinha convalescido.

[[v23-39-2]]

^<<v23-39-2,2>>^ Ezequias se agradou disso e mostrou aos mensageiros a casa do seu tesouro, a prata, o ouro, as especiarias, os óleos finos, todo o seu arsenal e tudo quanto se achava nos seus tesouros; nenhuma coisa houve, nem em sua casa, nem em todo o seu domínio, que Ezequias não lhes mostrasse.

[[v23-39-3]]

^<<v23-39-3,3>>^ Então, Isaías, o profeta, veio ao rei Ezequias e lhe disse: Que foi que aqueles homens disseram e donde vieram a ti? Respondeu Ezequias: De uma terra longínqua vieram a mim, da Babilônia.

[[v23-39-4]]

^<<v23-39-4,4>>^ Perguntou ele: Que viram em tua casa? Respondeu Ezequias: Viram tudo quanto há em minha casa; coisa nenhuma há nos meus tesouros que eu não lhes mostrasse.

[[v23-39-5]]

^<<v23-39-5,5>>^ Então, disse Isaías a Ezequias: Ouve a palavra do SENHOR dos Exércitos:

[[v23-39-6]]

^<<v23-39-6,6>>^ Eis que virão dias em que tudo quanto houver em tua casa, com o que entesouraram teus pais até ao dia de hoje, será levado para a Babilônia; não ficará coisa alguma, disse o SENHOR.

[[v23-39-7]]

^<<v23-39-7,7>>^ Dos teus próprios filhos, que tu gerares, tomarão, para que sejam eunucos no palácio do rei da Babilônia.

[[v23-39-8]]

^<<v23-39-8,8>>^ Então, disse Ezequias a Isaías: Boa é a palavra do SENHOR que disseste. Pois pensava: Haverá paz e segurança em meus dias.

'''

xref:023-isaias/023-isaias-038.adoc#v23-38-0[&#60; Capítulo Anterior] | <<v23-39-0,Topo>> | xref:023-isaias/023-isaias-040.adoc#v23-40-0[Próximo Capítulo &#62;]