include::./index.adoc[]

[[v23-59-0]]
=== Isaías, 59
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-59-1]]

^<<v23-59-1,1>>^ Eis que a mão do SENHOR não está encolhida, para que não possa salvar; nem surdo o seu ouvido, para não poder ouvir.

[[v23-59-2]]

^<<v23-59-2,2>>^ Mas as vossas iniquidades fazem separação entre vós e o vosso Deus; e os vossos pecados encobrem o seu rosto de vós, para que vos não ouça.

[[v23-59-3]]

^<<v23-59-3,3>>^ Porque as vossas mãos estão contaminadas de sangue, e os vossos dedos, de iniquidade; os vossos lábios falam mentiras, e a vossa língua profere maldade.

[[v23-59-4]]

^<<v23-59-4,4>>^ Ninguém há que clame pela justiça, ninguém que compareça em juízo pela verdade; confiam no que é nulo e andam falando mentiras; concebem o mal e dão à luz a iniquidade.

[[v23-59-5]]

^<<v23-59-5,5>>^ Chocam ovos de áspide e tecem teias de aranha; o que comer os ovos dela morrerá; se um dos ovos é pisado, sai-lhe uma víbora.

[[v23-59-6]]

^<<v23-59-6,6>>^ As suas teias não se prestam para vestes, os homens não poderão cobrir-se com o que eles fazem, as obras deles são obras de iniquidade, obra de violência há nas suas mãos.

[[v23-59-7]]

^<<v23-59-7,7>>^ Os seus pés correm para o mal, são velozes para derramar o sangue inocente; os seus pensamentos são pensamentos de iniquidade; nos seus caminhos há desolação e abatimento.

[[v23-59-8]]

^<<v23-59-8,8>>^ Desconhecem o caminho da paz, nem há justiça nos seus passos; fizeram para si veredas tortuosas; quem anda por elas não conhece a paz.

[[v23-59-9]]

^<<v23-59-9,9>>^ Por isso, está longe de nós o juízo, e a justiça não nos alcança; esperamos pela luz, e eis que há só trevas; pelo resplendor, mas andamos na escuridão.

[[v23-59-10]]

^<<v23-59-10,10>>^ Apalpamos as paredes como cegos, sim, como os que não têm olhos, andamos apalpando; tropeçamos ao meio-dia como nas trevas e entre os robustos somos como mortos.

[[v23-59-11]]

^<<v23-59-11,11>>^ Todos nós bramamos como ursos e gememos como pombas; esperamos o juízo, e não o há; a salvação, e ela está longe de nós.

[[v23-59-12]]

^<<v23-59-12,12>>^ Porque as nossas transgressões se multiplicam perante ti, e os nossos pecados testificam contra nós; porque as nossas transgressões estão conosco, e conhecemos as nossas iniquidades,

[[v23-59-13]]

^<<v23-59-13,13>>^ como o prevaricar, o mentir contra o SENHOR, o retirarmo-nos do nosso Deus, o pregar opressão e rebeldia, o conceber e proferir do coração palavras de falsidade.

[[v23-59-14]]

^<<v23-59-14,14>>^ Pelo que o direito se retirou, e a justiça se pôs de longe; porque a verdade anda tropeçando pelas praças, e a retidão não pode entrar.

[[v23-59-15]]

^<<v23-59-15,15>>^ Sim, a verdade sumiu, e quem se desvia do mal é tratado como presa. O SENHOR viu isso e desaprovou o não haver justiça.

[[v23-59-16]]

^<<v23-59-16,16>>^ Viu que não havia ajudador algum e maravilhou-se de que não houvesse um intercessor; pelo que o seu próprio braço lhe trouxe a salvação, e a sua própria justiça o susteve.

[[v23-59-17]]

^<<v23-59-17,17>>^ Vestiu-se de justiça, como de uma couraça, e pôs o capacete da salvação na cabeça; pôs sobre si a vestidura da vingança e se cobriu de zelo, como de um manto.

[[v23-59-18]]

^<<v23-59-18,18>>^ Segundo as obras deles, assim retribuirá; furor aos seus adversários e o devido aos seus inimigos; às terras do mar, dar-lhes-á a paga.

[[v23-59-19]]

^<<v23-59-19,19>>^ Temerão, pois, o nome do SENHOR desde o poente e a sua glória, desde o nascente do sol; pois virá como torrente impetuosa, impelida pelo Espírito do SENHOR.

[[v23-59-20]]

^<<v23-59-20,20>>^ Virá o Redentor a Sião e aos de Jacó que se converterem, diz o SENHOR.

[[v23-59-21]]

^<<v23-59-21,21>>^ Quanto a mim, esta é a minha aliança com eles, diz o SENHOR: o meu Espírito, que está sobre ti, e as minhas palavras, que pus na tua boca, não se apartarão dela, nem da de teus filhos, nem da dos filhos de teus filhos, não se apartarão desde agora e para todo o sempre, diz o SENHOR.

'''

xref:023-isaias/023-isaias-058.adoc#v23-58-0[&#60; Capítulo Anterior] | <<v23-59-0,Topo>> | xref:023-isaias/023-isaias-060.adoc#v23-60-0[Próximo Capítulo &#62;]