include::./index.adoc[]

[[v23-55-0]]
=== Isaías, 55
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-55-1]]

^<<v23-55-1,1>>^ Ah! Todos vós, os que tendes sede, vinde às águas; e vós, os que não tendes dinheiro, vinde, comprai e comei; sim, vinde e comprai, sem dinheiro e sem preço, vinho e leite.

[[v23-55-2]]

^<<v23-55-2,2>>^ Por que gastais o dinheiro naquilo que não é pão, e o vosso suor, naquilo que não satisfaz? Ouvi-me atentamente, comei o que é bom e vos deleitareis com finos manjares.

[[v23-55-3]]

^<<v23-55-3,3>>^ Inclinai os ouvidos e vinde a mim; ouvi, e a vossa alma viverá; porque convosco farei uma aliança perpétua, que consiste nas fiéis misericórdias prometidas a Davi.

[[v23-55-4]]

^<<v23-55-4,4>>^ Eis que eu o dei por testemunho aos povos, como príncipe e governador dos povos.

[[v23-55-5]]

^<<v23-55-5,5>>^ Eis que chamarás a uma nação que não conheces, e uma nação que nunca te conheceu correrá para junto de ti, por amor do SENHOR, teu Deus, e do Santo de Israel, porque este te glorificou.

[[v23-55-6]]

^<<v23-55-6,6>>^ Buscai o SENHOR enquanto se pode achar, invocai-o enquanto está perto.

[[v23-55-7]]

^<<v23-55-7,7>>^ Deixe o perverso o seu caminho, o iníquo, os seus pensamentos; converta-se ao SENHOR, que se compadecerá dele, e volte-se para o nosso Deus, porque é rico em perdoar.

[[v23-55-8]]

^<<v23-55-8,8>>^ Porque os meus pensamentos não são os vossos pensamentos, nem os vossos caminhos, os meus caminhos, diz o SENHOR,

[[v23-55-9]]

^<<v23-55-9,9>>^ porque, assim como os céus são mais altos do que a terra, assim são os meus caminhos mais altos do que os vossos caminhos, e os meus pensamentos, mais altos do que os vossos pensamentos.

[[v23-55-10]]

^<<v23-55-10,10>>^ Porque, assim como descem a chuva e a neve dos céus e para lá não tornam, sem que primeiro reguem a terra, e a fecundem, e a façam brotar, para dar semente ao semeador e pão ao que come,

[[v23-55-11]]

^<<v23-55-11,11>>^ assim será a palavra que sair da minha boca: não voltará para mim vazia, mas fará o que me apraz e prosperará naquilo para que a designei.

[[v23-55-12]]

^<<v23-55-12,12>>^ Saireis com alegria e em paz sereis guiados; os montes e os outeiros romperão em cânticos diante de vós, e todas as árvores do campo baterão palmas.

[[v23-55-13]]

^<<v23-55-13,13>>^ Em lugar do espinheiro, crescerá o cipreste, e em lugar da sarça crescerá a murta; e será isto glória para o SENHOR e memorial eterno, que jamais será extinto.

'''

xref:023-isaias/023-isaias-054.adoc#v23-54-0[&#60; Capítulo Anterior] | <<v23-55-0,Topo>> | xref:023-isaias/023-isaias-056.adoc#v23-56-0[Próximo Capítulo &#62;]