include::./index.adoc[]

[[v23-1-0]]
=== Isaías, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-1-1]]

^<<v23-1-1,1>>^ Visão de Isaías, filho de Amoz, que ele teve a respeito de Judá e Jerusalém, nos dias de Uzias, Jotão, Acaz e Ezequias, reis de Judá.

[[v23-1-2]]

^<<v23-1-2,2>>^ Ouvi, ó céus, e dá ouvidos, ó terra, porque o SENHOR é quem fala: Criei filhos e os engrandeci, mas eles estão revoltados contra mim.

[[v23-1-3]]

^<<v23-1-3,3>>^ O boi conhece o seu possuidor, e o jumento, o dono da sua manjedoura; mas Israel não tem conhecimento, o meu povo não entende.

[[v23-1-4]]

^<<v23-1-4,4>>^ Ai desta nação pecaminosa, povo carregado de iniquidade, raça de malignos, filhos corruptores; abandonaram o SENHOR, blasfemaram do Santo de Israel, voltaram para trás.

[[v23-1-5]]

^<<v23-1-5,5>>^ Por que haveis de ainda ser feridos, visto que continuais em rebeldia? Toda a cabeça está doente, e todo o coração, enfermo.

[[v23-1-6]]

^<<v23-1-6,6>>^ Desde a planta do pé até à cabeça não há nele coisa sã, senão feridas, contusões e chagas inflamadas, umas e outras não espremidas, nem atadas, nem amolecidas com óleo.

[[v23-1-7]]

^<<v23-1-7,7>>^ A vossa terra está assolada, as vossas cidades, consumidas pelo fogo; a vossa lavoura os estranhos devoram em vossa presença; e a terra se acha devastada como numa subversão de estranhos.

[[v23-1-8]]

^<<v23-1-8,8>>^ A filha de Sião é deixada como choça na vinha, como palhoça no pepinal, como cidade sitiada.

[[v23-1-9]]

^<<v23-1-9,9>>^ Se o SENHOR dos Exércitos não nos tivesse deixado alguns sobreviventes, já nos teríamos tornado como Sodoma e semelhantes a Gomorra.

[[v23-1-10]]

^<<v23-1-10,10>>^ Ouvi a palavra do SENHOR, vós, príncipes de Sodoma; prestai ouvidos à lei do nosso Deus, vós, povo de Gomorra.

[[v23-1-11]]

^<<v23-1-11,11>>^ De que me serve a mim a multidão de vossos sacrifícios? — diz o SENHOR. Estou farto dos holocaustos de carneiros e da gordura de animais cevados e não me agrado do sangue de novilhos, nem de cordeiros, nem de bodes.

[[v23-1-12]]

^<<v23-1-12,12>>^ Quando vindes para comparecer perante mim, quem vos requereu o só pisardes os meus átrios?

[[v23-1-13]]

^<<v23-1-13,13>>^ Não continueis a trazer ofertas vãs; o incenso é para mim abominação, e também as Festas da Lua Nova, os sábados, e a convocação das congregações; não posso suportar iniquidade associada ao ajuntamento solene.

[[v23-1-14]]

^<<v23-1-14,14>>^ As vossas Festas da Lua Nova e as vossas solenidades, a minha alma as aborrece; já me são pesadas; estou cansado de as sofrer.

[[v23-1-15]]

^<<v23-1-15,15>>^ Pelo que, quando estendeis as mãos, escondo de vós os olhos; sim, quando multiplicais as vossas orações, não as ouço, porque as vossas mãos estão cheias de sangue.

[[v23-1-16]]

^<<v23-1-16,16>>^ Lavai-vos, purificai-vos, tirai a maldade de vossos atos de diante dos meus olhos; cessai de fazer o mal.

[[v23-1-17]]

^<<v23-1-17,17>>^ Aprendei a fazer o bem; atendei à justiça, repreendei ao opressor; defendei o direito do órfão, pleiteai a causa das viúvas.

[[v23-1-18]]

^<<v23-1-18,18>>^ Vinde, pois, e arrazoemos, diz o SENHOR; ainda que os vossos pecados sejam como a escarlata, eles se tornarão brancos como a neve; ainda que sejam vermelhos como o carmesim, se tornarão como a lã.

[[v23-1-19]]

^<<v23-1-19,19>>^ Se quiserdes e me ouvirdes, comereis o melhor desta terra.

[[v23-1-20]]

^<<v23-1-20,20>>^ Mas, se recusardes e fordes rebeldes, sereis devorados à espada; porque a boca do SENHOR o disse.

[[v23-1-21]]

^<<v23-1-21,21>>^ Como se fez prostituta a cidade fiel! Ela, que estava cheia de justiça! Nela, habitava a retidão, mas, agora, homicidas.

[[v23-1-22]]

^<<v23-1-22,22>>^ A tua prata se tornou em escórias, o teu licor se misturou com água.

[[v23-1-23]]

^<<v23-1-23,23>>^ Os teus príncipes são rebeldes e companheiros de ladrões; cada um deles ama o suborno e corre atrás de recompensas. Não defendem o direito do órfão, e não chega perante eles a causa das viúvas.

[[v23-1-24]]

^<<v23-1-24,24>>^ Portanto, diz o Senhor, o SENHOR dos Exércitos, o Poderoso de Israel: Ah! Tomarei satisfações aos meus adversários e vingar-me-ei dos meus inimigos.

[[v23-1-25]]

^<<v23-1-25,25>>^ Voltarei contra ti a minha mão, purificar-te-ei como com potassa das tuas escórias e tirarei de ti todo metal impuro.

[[v23-1-26]]

^<<v23-1-26,26>>^ Restituir-te-ei os teus juízes, como eram antigamente, os teus conselheiros, como no princípio; depois, te chamarão cidade de justiça, cidade fiel.

[[v23-1-27]]

^<<v23-1-27,27>>^ Sião será redimida pelo direito, e os que se arrependem, pela justiça.

[[v23-1-28]]

^<<v23-1-28,28>>^ Mas os transgressores e os pecadores serão juntamente destruídos; e os que deixarem o SENHOR perecerão.

[[v23-1-29]]

^<<v23-1-29,29>>^ Porque vos envergonhareis dos carvalhos que cobiçastes e sereis confundidos por causa dos jardins que escolhestes.

[[v23-1-30]]

^<<v23-1-30,30>>^ Porque sereis como o carvalho, cujas folhas murcham, e como a floresta que não tem água.

[[v23-1-31]]

^<<v23-1-31,31>>^ O forte se tornará em estopa, e a sua obra, em faísca; ambos arderão juntamente, e não haverá quem os apague.

'''

xref:022-canticos/022-canticos-008.adoc#v22-8-0[&#60; Capítulo Anterior] | <<v23-1-0,Topo>> | xref:023-isaias/023-isaias-002.adoc#v23-2-0[Próximo Capítulo &#62;]