include::./index.adoc[]

[[v23-43-0]]
=== Isaías, 43
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-43-1]]

^<<v23-43-1,1>>^ Mas agora, assim diz o SENHOR, que te criou, ó Jacó, e que te formou, ó Israel: Não temas, porque eu te remi; chamei-te pelo teu nome, tu és meu.

[[v23-43-2]]

^<<v23-43-2,2>>^ Quando passares pelas águas, eu serei contigo; quando, pelos rios, eles não te submergirão; quando passares pelo fogo, não te queimarás, nem a chama arderá em ti.

[[v23-43-3]]

^<<v23-43-3,3>>^ Porque eu sou o SENHOR, teu Deus, o Santo de Israel, o teu Salvador; dei o Egito por teu resgate e a Etiópia e Sebá, por ti.

[[v23-43-4]]

^<<v23-43-4,4>>^ Visto que foste precioso aos meus olhos, digno de honra, e eu te amei, darei homens por ti e os povos, pela tua vida.

[[v23-43-5]]

^<<v23-43-5,5>>^ Não temas, pois, porque sou contigo; trarei a tua descendência desde o Oriente e a ajuntarei desde o Ocidente.

[[v23-43-6]]

^<<v23-43-6,6>>^ Direi ao Norte: entrega! E ao Sul: não retenhas! Trazei meus filhos de longe e minhas filhas, das extremidades da terra,

[[v23-43-7]]

^<<v23-43-7,7>>^ a todos os que são chamados pelo meu nome, e os que criei para minha glória, e que formei, e fiz.

[[v23-43-8]]

^<<v23-43-8,8>>^ Traze o povo que, ainda que tem olhos, é cego e surdo, ainda que tem ouvidos.

[[v23-43-9]]

^<<v23-43-9,9>>^ Todas as nações, congreguem-se; e, povos, reúnam-se; quem dentre eles pode anunciar isto e fazer-nos ouvir as predições antigas? Apresentem as suas testemunhas e por elas se justifiquem, para que se ouça e se diga: Verdade é!

[[v23-43-10]]

^<<v23-43-10,10>>^ Vós sois as minhas testemunhas, diz o SENHOR, o meu servo a quem escolhi; para que o saibais, e me creiais, e entendais que sou eu mesmo, e que antes de mim deus nenhum se formou, e depois de mim nenhum haverá.

[[v23-43-11]]

^<<v23-43-11,11>>^ Eu, eu sou o SENHOR, e fora de mim não há salvador.

[[v23-43-12]]

^<<v23-43-12,12>>^ Eu anunciei salvação, realizei-a e a fiz ouvir; deus estranho não houve entre vós, pois vós sois as minhas testemunhas, diz o SENHOR; eu sou Deus.

[[v23-43-13]]

^<<v23-43-13,13>>^ Ainda antes que houvesse dia, eu era; e nenhum há que possa livrar alguém das minhas mãos; agindo eu, quem o impedirá?

[[v23-43-14]]

^<<v23-43-14,14>>^ Assim diz o SENHOR, o que vos redime, o Santo de Israel: Por amor de vós, enviarei inimigos contra a Babilônia e a todos os de lá farei embarcar como fugitivos, isto é, os caldeus, nos navios com os quais se vangloriavam.

[[v23-43-15]]

^<<v23-43-15,15>>^ Eu sou o SENHOR, o vosso Santo, o Criador de Israel, o vosso Rei.

[[v23-43-16]]

^<<v23-43-16,16>>^ Assim diz o SENHOR, o que outrora preparou um caminho no mar e nas águas impetuosas, uma vereda;

[[v23-43-17]]

^<<v23-43-17,17>>^ o que fez sair o carro e o cavalo, o exército e a força — jazem juntamente lá e jamais se levantarão; estão extintos, apagados como uma torcida.

[[v23-43-18]]

^<<v23-43-18,18>>^ Não vos lembreis das coisas passadas, nem considereis as antigas.

[[v23-43-19]]

^<<v23-43-19,19>>^ Eis que faço coisa nova, que está saindo à luz; porventura, não o percebeis? Eis que porei um caminho no deserto e rios, no ermo.

[[v23-43-20]]

^<<v23-43-20,20>>^ Os animais do campo me glorificarão, os chacais e os filhotes de avestruzes; porque porei águas no deserto e rios, no ermo, para dar de beber ao meu povo, ao meu escolhido,

[[v23-43-21]]

^<<v23-43-21,21>>^ ao povo que formei para mim, para celebrar o meu louvor.

[[v23-43-22]]

^<<v23-43-22,22>>^ Contudo, não me tens invocado, ó Jacó, e de mim te cansaste, ó Israel.

[[v23-43-23]]

^<<v23-43-23,23>>^ Não me trouxeste o gado miúdo dos teus holocaustos, nem me honraste com os teus sacrifícios; não te dei trabalho com ofertas de manjares, nem te cansei com incenso.

[[v23-43-24]]

^<<v23-43-24,24>>^ Não me compraste por dinheiro cana aromática, nem com a gordura dos teus sacrifícios me satisfizeste, mas me deste trabalho com os teus pecados e me cansaste com as tuas iniquidades.

[[v23-43-25]]

^<<v23-43-25,25>>^ Eu, eu mesmo, sou o que apago as tuas transgressões por amor de mim e dos teus pecados não me lembro.

[[v23-43-26]]

^<<v23-43-26,26>>^ Desperta-me a memória; entremos juntos em juízo; apresenta as tuas razões, para que possas justificar-te.

[[v23-43-27]]

^<<v23-43-27,27>>^ Teu primeiro pai pecou, e os teus guias prevaricaram contra mim.

[[v23-43-28]]

^<<v23-43-28,28>>^ Pelo que profanarei os príncipes do santuário; e entregarei Jacó à destruição e Israel, ao opróbrio.

'''

xref:023-isaias/023-isaias-042.adoc#v23-42-0[&#60; Capítulo Anterior] | <<v23-43-0,Topo>> | xref:023-isaias/023-isaias-044.adoc#v23-44-0[Próximo Capítulo &#62;]