include::./index.adoc[]

[[v23-47-0]]
=== Isaías, 47
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-47-1]]

^<<v23-47-1,1>>^ Desce e assenta-te no pó, ó virgem filha de Babilônia; assenta-te no chão, pois já não há trono, ó filha dos caldeus, porque nunca mais te chamarás a mimosa e delicada.

[[v23-47-2]]

^<<v23-47-2,2>>^ Toma a mó e mói a farinha; tira o teu véu, ergue a cauda da tua vestidura, desnuda as pernas e atravessa os rios.

[[v23-47-3]]

^<<v23-47-3,3>>^ As tuas vergonhas serão descobertas, e se verá o teu opróbrio; tomarei vingança e não pouparei a homem algum.

[[v23-47-4]]

^<<v23-47-4,4>>^ Quanto ao nosso Redentor, o SENHOR dos Exércitos é seu nome, o Santo de Israel.

[[v23-47-5]]

^<<v23-47-5,5>>^ Assenta-te calada e entra nas trevas, ó filha dos caldeus, porque nunca mais serás chamada senhora de reinos.

[[v23-47-6]]

^<<v23-47-6,6>>^ Muito me agastei contra o meu povo, profanei a minha herança e a entreguei na tua mão, porém não usaste com ela de misericórdia e até sobre os velhos fizeste mui pesado o teu jugo.

[[v23-47-7]]

^<<v23-47-7,7>>^ E disseste: Eu serei senhora para sempre! Até agora não tomaste a sério estas coisas, nem te lembraste do seu fim.

[[v23-47-8]]

^<<v23-47-8,8>>^ Ouve isto, pois, tu que és dada a prazeres, que habitas segura, que dizes contigo mesma: Eu só, e além de mim não há outra; não ficarei viúva, nem conhecerei a perda de filhos.

[[v23-47-9]]

^<<v23-47-9,9>>^ Mas ambas estas coisas virão sobre ti num momento, no mesmo dia, perda de filhos e viuvez; virão em cheio sobre ti, apesar da multidão das tuas feitiçarias e da abundância dos teus muitos encantamentos.

[[v23-47-10]]

^<<v23-47-10,10>>^ Porque confiaste na tua maldade e disseste: Não há quem me veja. A tua sabedoria e a tua ciência, isso te fez desviar, e disseste contigo mesma: Eu só, e além de mim não há outra.

[[v23-47-11]]

^<<v23-47-11,11>>^ Pelo que sobre ti virá o mal que por encantamentos não saberás conjurar; tal calamidade cairá sobre ti, da qual por expiação não te poderás livrar; porque sobre ti, de repente, virá tamanha desolação, como não imaginavas.

[[v23-47-12]]

^<<v23-47-12,12>>^ Deixa-te estar com os teus encantamentos e com a multidão das tuas feitiçarias em que te fatigaste desde a tua mocidade; talvez possas tirar proveito, talvez, com isso, inspirar terror.

[[v23-47-13]]

^<<v23-47-13,13>>^ Já estás cansada com a multidão das tuas consultas! Levantem-se, pois, agora, os que dissecam os céus e fitam os astros, os que em cada lua nova te predizem o que há de vir sobre ti.

[[v23-47-14]]

^<<v23-47-14,14>>^ Eis que serão como restolho, o fogo os queimará; não poderão livrar-se do poder das chamas; nenhuma brasa restará para se aquentarem, nem fogo, para que diante dele se assentem.

[[v23-47-15]]

^<<v23-47-15,15>>^ Assim serão para contigo aqueles com quem te fatigaste; aqueles com quem negociaste desde a tua mocidade; dispersar-se-ão, cambaleantes, cada qual pelo seu caminho; ninguém te salvará.

'''

xref:023-isaias/023-isaias-046.adoc#v23-46-0[&#60; Capítulo Anterior] | <<v23-47-0,Topo>> | xref:023-isaias/023-isaias-048.adoc#v23-48-0[Próximo Capítulo &#62;]