include::./index.adoc[]

[[v23-62-0]]
=== Isaías, 62
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-62-1]]

^<<v23-62-1,1>>^ Por amor de Sião, me não calarei e, por amor de Jerusalém, não me aquietarei, até que saia a sua justiça como um resplendor, e a sua salvação, como uma tocha acesa.

[[v23-62-2]]

^<<v23-62-2,2>>^ As nações verão a tua justiça, e todos os reis, a tua glória; e serás chamada por um nome novo, que a boca do SENHOR designará.

[[v23-62-3]]

^<<v23-62-3,3>>^ Serás uma coroa de glória na mão do SENHOR, um diadema real na mão do teu Deus.

[[v23-62-4]]

^<<v23-62-4,4>>^ Nunca mais te chamarão Desamparada, nem a tua terra se denominará jamais Desolada; mas chamar-te-ão Minha-Delícia; e à tua terra, Desposada; porque o SENHOR se delicia em ti; e a tua terra se desposará.

[[v23-62-5]]

^<<v23-62-5,5>>^ Porque, como o jovem desposa a donzela, assim teus filhos te desposarão a ti; como o noivo se alegra da noiva, assim de ti se alegrará o teu Deus.

[[v23-62-6]]

^<<v23-62-6,6>>^ Sobre os teus muros, ó Jerusalém, pus guardas, que todo o dia e toda a noite jamais se calarão; vós, os que fareis lembrado o SENHOR, não descanseis,

[[v23-62-7]]

^<<v23-62-7,7>>^ nem deis a ele descanso até que restabeleça Jerusalém e a ponha por objeto de louvor na terra.

[[v23-62-8]]

^<<v23-62-8,8>>^ Jurou o SENHOR pela sua mão direita e pelo seu braço poderoso: Nunca mais darei o teu cereal por sustento aos teus inimigos, nem os estrangeiros beberão o teu vinho, fruto de tuas fadigas.

[[v23-62-9]]

^<<v23-62-9,9>>^ Mas os que o ajuntarem o comerão e louvarão ao SENHOR; e os que o recolherem beberão nos átrios do meu santuário.

[[v23-62-10]]

^<<v23-62-10,10>>^ Passai, passai pelas portas; preparai o caminho ao povo; aterrai, aterrai a estrada, limpai-a das pedras; arvorai bandeira aos povos.

[[v23-62-11]]

^<<v23-62-11,11>>^ Eis que o SENHOR fez ouvir até às extremidades da terra estas palavras: Dizei à filha de Sião: Eis que vem o teu Salvador; vem com ele a sua recompensa, e diante dele, o seu galardão.

[[v23-62-12]]

^<<v23-62-12,12>>^ Chamar-vos-ão Povo Santo, Remidos-Do- SENHOR; e tu, Sião, serás chamada Procurada, Cidade-Não-Deserta.

'''

xref:023-isaias/023-isaias-061.adoc#v23-61-0[&#60; Capítulo Anterior] | <<v23-62-0,Topo>> | xref:023-isaias/023-isaias-063.adoc#v23-63-0[Próximo Capítulo &#62;]