include::./index.adoc[]

[[v23-13-0]]
=== Isaías, 13
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-13-1]]

^<<v23-13-1,1>>^ Sentença que, numa visão, recebeu Isaías, filho de Amoz, contra a Babilônia.

[[v23-13-2]]

^<<v23-13-2,2>>^ Alçai um estandarte sobre o monte escalvado; levantai a voz para eles; acenai-lhes com a mão, para que entrem pelas portas dos tiranos.

[[v23-13-3]]

^<<v23-13-3,3>>^ Eu dei ordens aos meus consagrados, sim, chamei os meus valentes para executarem a minha ira, os que com exultação se orgulham.

[[v23-13-4]]

^<<v23-13-4,4>>^ Já se ouve sobre os montes o rumor como o de muito povo, o clamor de reinos e de nações já congregados. O SENHOR dos Exércitos passa revista às tropas de guerra.

[[v23-13-5]]

^<<v23-13-5,5>>^ Já vêm de um país remoto, desde a extremidade do céu, o SENHOR e os instrumentos da sua indignação, para destruir toda a terra.

[[v23-13-6]]

^<<v23-13-6,6>>^ Uivai, pois está perto o Dia do SENHOR; vem do Todo-Poderoso como assolação.

[[v23-13-7]]

^<<v23-13-7,7>>^ Pelo que todos os braços se tornarão frouxos, e o coração de todos os homens se derreterá.

[[v23-13-8]]

^<<v23-13-8,8>>^ Assombrar-se-ão, e apoderar-se-ão deles dores e ais, e terão contorções como a mulher parturiente; olharão atônitos uns para outros; o seu rosto se tornará rosto flamejante.

[[v23-13-9]]

^<<v23-13-9,9>>^ Eis que vem o Dia do SENHOR, dia cruel, com ira e ardente furor, para converter a terra em assolação e dela destruir os pecadores.

[[v23-13-10]]

^<<v23-13-10,10>>^ Porque as estrelas e constelações dos céus não darão a sua luz; o sol, logo ao nascer, se escurecerá, e a lua não fará resplandecer a sua luz.

[[v23-13-11]]

^<<v23-13-11,11>>^ Castigarei o mundo por causa da sua maldade e os perversos, por causa da sua iniquidade; farei cessar a arrogância dos atrevidos e abaterei a soberba dos violentos.

[[v23-13-12]]

^<<v23-13-12,12>>^ Farei que os homens sejam mais escassos do que o ouro puro, mais raros do que o ouro de Ofir.

[[v23-13-13]]

^<<v23-13-13,13>>^ Portanto, farei estremecer os céus; e a terra será sacudida do seu lugar, por causa da ira do SENHOR dos Exércitos e por causa do dia do seu ardente furor.

[[v23-13-14]]

^<<v23-13-14,14>>^ Cada um será como a gazela que foge e como o rebanho que ninguém recolhe; cada um voltará para o seu povo e cada um fugirá para a sua terra.

[[v23-13-15]]

^<<v23-13-15,15>>^ Quem for achado será traspassado; e aquele que for apanhado cairá à espada.

[[v23-13-16]]

^<<v23-13-16,16>>^ Suas crianças serão esmagadas perante eles; a sua casa será saqueada, e sua mulher, violada.

[[v23-13-17]]

^<<v23-13-17,17>>^ Eis que eu despertarei contra eles os medos, que não farão caso de prata, nem tampouco desejarão ouro.

[[v23-13-18]]

^<<v23-13-18,18>>^ Os seus arcos matarão os jovens; eles não se compadecerão do fruto do ventre; os seus olhos não pouparão as crianças.

[[v23-13-19]]

^<<v23-13-19,19>>^ Babilônia, a joia dos reinos, glória e orgulho dos caldeus, será como Sodoma e Gomorra, quando Deus as transtornou.

[[v23-13-20]]

^<<v23-13-20,20>>^ Nunca jamais será habitada, ninguém morará nela de geração em geração; o arábio não armará ali a sua tenda, nem tampouco os pastores farão ali deitar os seus rebanhos.

[[v23-13-21]]

^<<v23-13-21,21>>^ Porém, nela, as feras do deserto repousarão, e as suas casas se encherão de corujas; ali habitarão os avestruzes, e os sátiros pularão ali.

[[v23-13-22]]

^<<v23-13-22,22>>^ As hienas uivarão nos seus castelos; os chacais, nos seus palácios de prazer; está prestes a chegar o seu tempo, e os seus dias não se prolongarão.

'''

xref:023-isaias/023-isaias-012.adoc#v23-12-0[&#60; Capítulo Anterior] | <<v23-13-0,Topo>> | xref:023-isaias/023-isaias-014.adoc#v23-14-0[Próximo Capítulo &#62;]