include::./index.adoc[]

[[v23-8-0]]
=== Isaías, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-8-1]]

^<<v23-8-1,1>>^ Disse-me também o SENHOR: Toma uma ardósia grande e escreve nela de maneira inteligível: Rápido-Despojo-Presa-Segura.

[[v23-8-2]]

^<<v23-8-2,2>>^ Tomei para isto comigo testemunhas fidedignas, a Urias, sacerdote, e a Zacarias, filho de Jeberequias.

[[v23-8-3]]

^<<v23-8-3,3>>^ Fui ter com a profetisa; ela concebeu e deu à luz um filho. Então, me disse o SENHOR: Põe-lhe o nome de Rápido-Despojo-Presa-Segura.

[[v23-8-4]]

^<<v23-8-4,4>>^ Porque antes que o menino saiba dizer meu pai ou minha mãe, serão levadas as riquezas de Damasco e os despojos de Samaria, diante do rei da Assíria.

[[v23-8-5]]

^<<v23-8-5,5>>^ Falou-me ainda o SENHOR, dizendo:

[[v23-8-6]]

^<<v23-8-6,6>>^ Em vista de este povo ter desprezado as águas de Siloé, que correm brandamente, e se estar derretendo de medo diante de Rezim e do filho de Remalias,

[[v23-8-7]]

^<<v23-8-7,7>>^ eis que o Senhor fará vir sobre eles as águas do Eufrates, fortes e impetuosas, isto é, o rei da Assíria, com toda a sua glória; águas que encherão o leito dos rios e transbordarão por todas as suas ribanceiras.

[[v23-8-8]]

^<<v23-8-8,8>>^ Penetrarão em Judá, inundando-o, e, passando por ele, chegarão até ao pescoço; as alas estendidas do seu exército cobrirão a largura da tua terra, ó Emanuel.

[[v23-8-9]]

^<<v23-8-9,9>>^ Enfurecei-vos, ó povos, e sereis despedaçados; dai ouvidos, todos os que sois de países longínquos; cingi-vos e sereis despedaçados, cingi-vos e sereis despedaçados.

[[v23-8-10]]

^<<v23-8-10,10>>^ Forjai projetos, e eles serão frustrados; dai ordens, e elas não serão cumpridas, porque Deus é conosco.

[[v23-8-11]]

^<<v23-8-11,11>>^ Porque assim o SENHOR me disse, tendo forte a mão sobre mim, e me advertiu que não andasse pelo caminho deste povo, dizendo:

[[v23-8-12]]

^<<v23-8-12,12>>^ Não chameis conjuração a tudo quanto este povo chama conjuração; não temais o que ele teme, nem tomeis isso por temível.

[[v23-8-13]]

^<<v23-8-13,13>>^ Ao SENHOR dos Exércitos, a ele santificai; seja ele o vosso temor, seja ele o vosso espanto.

[[v23-8-14]]

^<<v23-8-14,14>>^ Ele vos será santuário; mas será pedra de tropeço e rocha de ofensa às duas casas de Israel, laço e armadilha aos moradores de Jerusalém.

[[v23-8-15]]

^<<v23-8-15,15>>^ Muitos dentre eles tropeçarão e cairão, serão quebrantados, enlaçados e presos.

[[v23-8-16]]

^<<v23-8-16,16>>^ Resguarda o testemunho, sela a lei no coração dos meus discípulos.

[[v23-8-17]]

^<<v23-8-17,17>>^ Esperarei no SENHOR, que esconde o seu rosto da casa de Jacó, e a ele aguardarei.

[[v23-8-18]]

^<<v23-8-18,18>>^ Eis-me aqui, e os filhos que o SENHOR me deu, para sinais e para maravilhas em Israel da parte do SENHOR dos Exércitos, que habita no monte Sião.

[[v23-8-19]]

^<<v23-8-19,19>>^ Quando vos disserem: Consultai os necromantes e os adivinhos, que chilreiam e murmuram, acaso, não consultará o povo ao seu Deus? A favor dos vivos se consultarão os mortos?

[[v23-8-20]]

^<<v23-8-20,20>>^ À lei e ao testemunho! Se eles não falarem desta maneira, jamais verão a alva.

[[v23-8-21]]

^<<v23-8-21,21>>^ Passarão pela terra duramente oprimidos e famintos; e será que, quando tiverem fome, enfurecendo-se, amaldiçoarão ao seu rei e ao seu Deus, olhando para cima.

[[v23-8-22]]

^<<v23-8-22,22>>^ Olharão para a terra, e eis aí angústia, escuridão e sombras de ansiedade, e serão lançados para densas trevas.

'''

xref:023-isaias/023-isaias-007.adoc#v23-7-0[&#60; Capítulo Anterior] | <<v23-8-0,Topo>> | xref:023-isaias/023-isaias-009.adoc#v23-9-0[Próximo Capítulo &#62;]