include::./index.adoc[]

[[v23-26-0]]
=== Isaías, 26
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-26-1]]

^<<v23-26-1,1>>^ Naquele dia, se entoará este cântico na terra de Judá: Temos uma cidade forte; Deus lhe põe a salvação por muros e baluartes.

[[v23-26-2]]

^<<v23-26-2,2>>^ Abri vós as portas, para que entre a nação justa, que guarda a fidelidade.

[[v23-26-3]]

^<<v23-26-3,3>>^ Tu, SENHOR, conservarás em perfeita paz aquele cujo propósito é firme; porque ele confia em ti.

[[v23-26-4]]

^<<v23-26-4,4>>^ Confiai no SENHOR perpetuamente, porque o SENHOR Deus é uma rocha eterna;

[[v23-26-5]]

^<<v23-26-5,5>>^ porque ele abate os que habitam no alto, na cidade elevada; abate-a, humilha-a até à terra e até ao pó.

[[v23-26-6]]

^<<v23-26-6,6>>^ O pé a pisará; os pés dos aflitos, e os passos dos pobres.

[[v23-26-7]]

^<<v23-26-7,7>>^ A vereda do justo é plana; tu, que és justo, aplanas a vereda do justo.

[[v23-26-8]]

^<<v23-26-8,8>>^ Também através dos teus juízos, SENHOR, te esperamos; no teu nome e na tua memória está o desejo da nossa alma.

[[v23-26-9]]

^<<v23-26-9,9>>^ Com minha alma suspiro de noite por ti e, com o meu espírito dentro de mim, eu te procuro diligentemente; porque, quando os teus juízos reinam na terra, os moradores do mundo aprendem justiça.

[[v23-26-10]]

^<<v23-26-10,10>>^ Ainda que se mostre favor ao perverso, nem por isso aprende a justiça; até na terra da retidão ele comete a iniquidade e não atenta para a majestade do SENHOR.

[[v23-26-11]]

^<<v23-26-11,11>>^ SENHOR, a tua mão está levantada, mas nem por isso a veem; porém verão o teu zelo pelo povo e se envergonharão; e o teu furor, por causa dos teus adversários, que os consuma.

[[v23-26-12]]

^<<v23-26-12,12>>^ SENHOR, concede-nos a paz, porque todas as nossas obras tu as fazes por nós.

[[v23-26-13]]

^<<v23-26-13,13>>^ Ó SENHOR, Deus nosso, outros senhores têm tido domínio sobre nós; mas graças a ti somente é que louvamos o teu nome.

[[v23-26-14]]

^<<v23-26-14,14>>^ Mortos não tornarão a viver, sombras não ressuscitam; por isso, os castigaste, e destruíste, e lhes fizeste perecer toda a memória.

[[v23-26-15]]

^<<v23-26-15,15>>^ Tu, SENHOR, aumentaste o povo, aumentaste o povo e tens sido glorificado; a todos os confins da terra dilataste.

[[v23-26-16]]

^<<v23-26-16,16>>^ SENHOR, na angústia te buscaram; vindo sobre eles a tua correção, derramaram as suas orações.

[[v23-26-17]]

^<<v23-26-17,17>>^ Como a mulher grávida, quando se lhe aproxima a hora de dar à luz, se contorce e dá gritos nas suas dores, assim fomos nós na tua presença, ó SENHOR!

[[v23-26-18]]

^<<v23-26-18,18>>^ Concebemos nós e nos contorcemos em dores de parto, mas o que demos à luz foi vento; não trouxemos à terra livramento algum, e não nasceram moradores do mundo.

[[v23-26-19]]

^<<v23-26-19,19>>^ Os vossos mortos e também o meu cadáver viverão e ressuscitarão; despertai e exultai, os que habitais no pó, porque o teu orvalho, ó Deus, será como o orvalho de vida, e a terra dará à luz os seus mortos.

[[v23-26-20]]

^<<v23-26-20,20>>^ Vai, pois, povo meu, entra nos teus quartos e fecha as tuas portas sobre ti; esconde-te só por um momento, até que passe a ira.

[[v23-26-21]]

^<<v23-26-21,21>>^ Pois eis que o SENHOR sai do seu lugar, para castigar a iniquidade dos moradores da terra; a terra descobrirá o sangue que embebeu e já não encobrirá aqueles que foram mortos.

'''

xref:023-isaias/023-isaias-025.adoc#v23-25-0[&#60; Capítulo Anterior] | <<v23-26-0,Topo>> | xref:023-isaias/023-isaias-027.adoc#v23-27-0[Próximo Capítulo &#62;]