include::./index.adoc[]

[[v23-7-0]]
=== Isaías, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-7-1]]

^<<v23-7-1,1>>^ Sucedeu nos dias de Acaz, filho de Jotão, filho de Uzias, rei de Judá, que Rezim, rei da Síria, e Peca, filho de Remalias, rei de Israel, subiram a Jerusalém, para pelejarem contra ela, porém não prevaleceram contra ela.

[[v23-7-2]]

^<<v23-7-2,2>>^ Deu-se aviso à casa de Davi: A Síria está aliada com Efraim. Então, ficou agitado o coração de Acaz e o coração do seu povo, como se agitam as árvores do bosque com o vento.

[[v23-7-3]]

^<<v23-7-3,3>>^ Disse o SENHOR a Isaías: Agora, sai tu com teu filho, que se chama Um-Resto-Volverá, ao encontro de Acaz, que está na outra extremidade do aqueduto do açude superior, junto ao caminho do campo do lavadeiro,

[[v23-7-4]]

^<<v23-7-4,4>>^ e dize-lhe: Acautela-te e aquieta-te; não temas, nem se desanime o teu coração por causa destes dois tocos de tições fumegantes; por causa do ardor da ira de Rezim, e da Síria, e do filho de Remalias.

[[v23-7-5]]

^<<v23-7-5,5>>^ Porquanto a Síria resolveu fazer-te mal, bem como Efraim e o filho de Remalias, dizendo:

[[v23-7-6]]

^<<v23-7-6,6>>^ Subamos contra Judá, e amedrontemo-lo, e o conquistemos para nós, e façamos reinar no meio dele o filho de Tabeal.

[[v23-7-7]]

^<<v23-7-7,7>>^ Assim diz o SENHOR Deus: Isto não subsistirá, nem tampouco acontecerá.

[[v23-7-8]]

^<<v23-7-8,8>>^ Mas a capital da Síria será Damasco, e o cabeça de Damasco, Rezim, e dentro de sessenta e cinco anos Efraim será destruído e deixará de ser povo.

[[v23-7-9]]

^<<v23-7-9,9>>^ Entretanto, a capital de Efraim será Samaria, e o cabeça de Samaria, o filho de Remalias; se o não crerdes, certamente, não permanecereis.

[[v23-7-10]]

^<<v23-7-10,10>>^ E continuou o SENHOR a falar com Acaz, dizendo:

[[v23-7-11]]

^<<v23-7-11,11>>^ Pede ao SENHOR, teu Deus, um sinal, quer seja embaixo, nas profundezas, ou em cima, nas alturas.

[[v23-7-12]]

^<<v23-7-12,12>>^ Acaz, porém, disse: Não o pedirei, nem tentarei ao SENHOR.

[[v23-7-13]]

^<<v23-7-13,13>>^ Então, disse o profeta: Ouvi, agora, ó casa de Davi: acaso, não vos basta fatigardes os homens, mas ainda fatigais também ao meu Deus?

[[v23-7-14]]

^<<v23-7-14,14>>^ Portanto, o Senhor mesmo vos dará um sinal: eis que a virgem conceberá e dará à luz um filho e lhe chamará Emanuel.

[[v23-7-15]]

^<<v23-7-15,15>>^ Ele comerá manteiga e mel quando souber desprezar o mal e escolher o bem.

[[v23-7-16]]

^<<v23-7-16,16>>^ Na verdade, antes que este menino saiba desprezar o mal e escolher o bem, será desamparada a terra ante cujos dois reis tu tremes de medo.

[[v23-7-17]]

^<<v23-7-17,17>>^ Mas o SENHOR fará vir sobre ti, sobre o teu povo e sobre a casa de teu pai, por intermédio do rei da Assíria, dias tais, quais nunca vieram, desde o dia em que Efraim se separou de Judá.

[[v23-7-18]]

^<<v23-7-18,18>>^ Porque há de acontecer que, naquele dia, assobiará o SENHOR às moscas que há no extremo dos rios do Egito e às abelhas que andam na terra da Assíria;

[[v23-7-19]]

^<<v23-7-19,19>>^ elas virão e pousarão todas nos vales profundos, nas fendas das rochas, em todos os espinhos e em todos os pastios.

[[v23-7-20]]

^<<v23-7-20,20>>^ Naquele dia, rapar-te-á o Senhor com uma navalha alugada doutro lado do rio, a saber, por meio do rei da Assíria, a cabeça e os cabelos das vergonhas e tirará também a barba.

[[v23-7-21]]

^<<v23-7-21,21>>^ Naquele dia, sucederá que um homem manterá apenas uma vaca nova e duas ovelhas,

[[v23-7-22]]

^<<v23-7-22,22>>^ e será tal a abundância de leite que elas lhe darão, que comerá manteiga; manteiga e mel comerá todo o restante no meio da terra.

[[v23-7-23]]

^<<v23-7-23,23>>^ Também, naquele dia, todo lugar em que houver mil vides, do valor de mil siclos de prata, será para espinheiros e abrolhos.

[[v23-7-24]]

^<<v23-7-24,24>>^ Com flechas e arco se entrará aí, porque os espinheiros e abrolhos cobrirão toda a terra.

[[v23-7-25]]

^<<v23-7-25,25>>^ Quanto a todos os montes, que os homens costumam sachar, para ali não irás por temeres os espinhos e abrolhos; serão para pasto de bois e para serem pisados de ovelhas.

'''

xref:023-isaias/023-isaias-006.adoc#v23-6-0[&#60; Capítulo Anterior] | <<v23-7-0,Topo>> | xref:023-isaias/023-isaias-008.adoc#v23-8-0[Próximo Capítulo &#62;]