include::./index.adoc[]

[[v23-11-0]]
=== Isaías, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-11-1]]

^<<v23-11-1,1>>^ Do tronco de Jessé sairá um rebento, e das suas raízes, um renovo.

[[v23-11-2]]

^<<v23-11-2,2>>^ Repousará sobre ele o Espírito do SENHOR, o Espírito de sabedoria e de entendimento, o Espírito de conselho e de fortaleza, o Espírito de conhecimento e de temor do SENHOR.

[[v23-11-3]]

^<<v23-11-3,3>>^ Deleitar-se-á no temor do SENHOR; não julgará segundo a vista dos seus olhos, nem repreenderá segundo o ouvir dos seus ouvidos;

[[v23-11-4]]

^<<v23-11-4,4>>^ mas julgará com justiça os pobres e decidirá com equidade a favor dos mansos da terra; ferirá a terra com a vara de sua boca e com o sopro dos seus lábios matará o perverso.

[[v23-11-5]]

^<<v23-11-5,5>>^ A justiça será o cinto dos seus lombos, e a fidelidade, o cinto dos seus rins.

[[v23-11-6]]

^<<v23-11-6,6>>^ O lobo habitará com o cordeiro, e o leopardo se deitará junto ao cabrito; o bezerro, o leão novo e o animal cevado andarão juntos, e um pequenino os guiará.

[[v23-11-7]]

^<<v23-11-7,7>>^ A vaca e a ursa pastarão juntas, e as suas crias juntas se deitarão; o leão comerá palha como o boi.

[[v23-11-8]]

^<<v23-11-8,8>>^ A criança de peito brincará sobre a toca da áspide, e o já desmamado meterá a mão na cova do basilisco.

[[v23-11-9]]

^<<v23-11-9,9>>^ Não se fará mal nem dano algum em todo o meu santo monte, porque a terra se encherá do conhecimento do SENHOR, como as águas cobrem o mar.

[[v23-11-10]]

^<<v23-11-10,10>>^ Naquele dia, recorrerão as nações à raiz de Jessé que está posta por estandarte dos povos; a glória lhe será a morada.

[[v23-11-11]]

^<<v23-11-11,11>>^ Naquele dia, o Senhor tornará a estender a mão para resgatar o restante do seu povo, que for deixado, da Assíria, do Egito, de Patros, da Etiópia, de Elão, de Sinar, de Hamate e das terras do mar.

[[v23-11-12]]

^<<v23-11-12,12>>^ Levantará um estandarte para as nações, ajuntará os desterrados de Israel e os dispersos de Judá recolherá desde os quatro confins da terra.

[[v23-11-13]]

^<<v23-11-13,13>>^ Afastar-se-á a inveja de Efraim, e os adversários de Judá serão eliminados; Efraim não invejará a Judá, e Judá não oprimirá a Efraim.

[[v23-11-14]]

^<<v23-11-14,14>>^ Antes, voarão para sobre os ombros dos filisteus ao Ocidente; juntos, despojarão os filhos do Oriente; contra Edom e Moabe lançarão as mãos, e os filhos de Amom lhes serão sujeitos.

[[v23-11-15]]

^<<v23-11-15,15>>^ O SENHOR destruirá totalmente o braço do mar do Egito, e com a força do seu vento moverá a mão contra o Eufrates, e, ferindo-o, dividi-lo-á em sete canais, de sorte que qualquer o atravessará de sandálias.

[[v23-11-16]]

^<<v23-11-16,16>>^ Haverá caminho plano para o restante do seu povo, que for deixado, da Assíria, como o houve para Israel no dia em que subiu da terra do Egito.

'''

xref:023-isaias/023-isaias-010.adoc#v23-10-0[&#60; Capítulo Anterior] | <<v23-11-0,Topo>> | xref:023-isaias/023-isaias-012.adoc#v23-12-0[Próximo Capítulo &#62;]