include::./index.adoc[]

[[v23-3-0]]
=== Isaías, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-3-1]]

^<<v23-3-1,1>>^ Porque eis que o Senhor, o SENHOR dos Exércitos, tira de Jerusalém e de Judá o sustento e o apoio, todo sustento de pão e todo sustento de água;

[[v23-3-2]]

^<<v23-3-2,2>>^ o valente, o guerreiro e o juiz; o profeta, o adivinho e o ancião;

[[v23-3-3]]

^<<v23-3-3,3>>^ o capitão de cinquenta, o respeitável, o conselheiro, o hábil entre os artífices e o encantador perito.

[[v23-3-4]]

^<<v23-3-4,4>>^ Dar-lhes-ei meninos por príncipes, e crianças governarão sobre eles.

[[v23-3-5]]

^<<v23-3-5,5>>^ Entre o povo, oprimem uns aos outros, cada um, ao seu próximo; o menino se atreverá contra o ancião, e o vil, contra o nobre.

[[v23-3-6]]

^<<v23-3-6,6>>^ Quando alguém se chegar a seu irmão e lhe disser, na casa de seu pai: Tu tens roupa, sê nosso príncipe e toma sob teu governo esta ruína;

[[v23-3-7]]

^<<v23-3-7,7>>^ naquele dia, levantará este a sua voz, dizendo: Não sou médico, não há pão em minha casa, nem veste alguma; não me ponhais por príncipe do povo.

[[v23-3-8]]

^<<v23-3-8,8>>^ Porque Jerusalém está arruinada, e Judá, caída; porquanto a sua língua e as suas obras são contra o SENHOR, para desafiarem a sua gloriosa presença.

[[v23-3-9]]

^<<v23-3-9,9>>^ O aspecto do seu rosto testifica contra eles; e, como Sodoma, publicam o seu pecado e não o encobrem. Ai da sua alma! Porque fazem mal a si mesmos.

[[v23-3-10]]

^<<v23-3-10,10>>^ Dizei aos justos que bem lhes irá; porque comerão do fruto das suas ações.

[[v23-3-11]]

^<<v23-3-11,11>>^ Ai do perverso! Mal lhe irá; porque a sua paga será o que as suas próprias mãos fizeram.

[[v23-3-12]]

^<<v23-3-12,12>>^ Os opressores do meu povo são crianças, e mulheres estão à testa do seu governo. Oh! Povo meu! Os que te guiam te enganam e destroem o caminho por onde deves seguir.

[[v23-3-13]]

^<<v23-3-13,13>>^ O SENHOR se dispõe para pleitear e se apresenta para julgar os povos.

[[v23-3-14]]

^<<v23-3-14,14>>^ O SENHOR entra em juízo contra os anciãos do seu povo e contra os seus príncipes. Vós sois os que consumistes esta vinha; o que roubastes do pobre está em vossa casa.

[[v23-3-15]]

^<<v23-3-15,15>>^ Que há convosco que esmagais o meu povo e moeis a face dos pobres? — diz o Senhor, o SENHOR dos Exércitos.

[[v23-3-16]]

^<<v23-3-16,16>>^ Diz ainda mais o SENHOR: Visto que são altivas as filhas de Sião e andam de pescoço emproado, de olhares impudentes, andam a passos curtos, fazendo tinir os ornamentos de seus pés,

[[v23-3-17]]

^<<v23-3-17,17>>^ o Senhor fará tinhosa a cabeça das filhas de Sião, o SENHOR porá a descoberto as suas vergonhas.

[[v23-3-18]]

^<<v23-3-18,18>>^ Naquele dia, tirará o Senhor o enfeite dos anéis dos tornozelos, e as toucas, e os ornamentos em forma de meia-lua;

[[v23-3-19]]

^<<v23-3-19,19>>^ os pendentes, e os braceletes, e os véus esvoaçantes;

[[v23-3-20]]

^<<v23-3-20,20>>^ os turbantes, as cadeiazinhas para os passos, as cintas, as caixinhas de perfumes e os amuletos;

[[v23-3-21]]

^<<v23-3-21,21>>^ os sinetes e as joias pendentes do nariz;

[[v23-3-22]]

^<<v23-3-22,22>>^ os vestidos de festa, os mantos, os xales e as bolsas;

[[v23-3-23]]

^<<v23-3-23,23>>^ os espelhos, as camisas finíssimas, os atavios de cabeça e os véus grandes.

[[v23-3-24]]

^<<v23-3-24,24>>^ Será que em lugar de perfume haverá podridão, e por cinta, corda; em lugar de encrespadura de cabelos, calvície; e em lugar de veste suntuosa, cilício; e marca de fogo, em lugar de formosura.

[[v23-3-25]]

^<<v23-3-25,25>>^ Os teus homens cairão à espada, e os teus valentes, na guerra.

[[v23-3-26]]

^<<v23-3-26,26>>^ As suas portas chorarão e estarão de luto; Sião, desolada, se assentará em terra.

'''

xref:023-isaias/023-isaias-002.adoc#v23-2-0[&#60; Capítulo Anterior] | <<v23-3-0,Topo>> | xref:023-isaias/023-isaias-004.adoc#v23-4-0[Próximo Capítulo &#62;]