include::./index.adoc[]

[[v23-23-0]]
=== Isaías, 23
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-23-1]]

^<<v23-23-1,1>>^ Sentença contra Tiro. Uivai, navios de Társis, porque está assolada, a ponto de não haver nela casa nenhuma, nem ancoradouro. Da terra de Chipre lhes foi isto revelado.

[[v23-23-2]]

^<<v23-23-2,2>>^ Calai-vos, moradores do litoral, vós a quem os mercadores de Sidom enriqueceram, navegando pelo mar.

[[v23-23-3]]

^<<v23-23-3,3>>^ Através das vastas águas, vinha o cereal dos canais do Egito e a ceifa do Nilo, como a tua renda, Tiro, que vieste a ser a feira das nações.

[[v23-23-4]]

^<<v23-23-4,4>>^ Envergonha-te, ó Sidom, porque o mar, a fortaleza do mar, fala, dizendo: Não tive dores de parto, não dei à luz, não criei rapazes, nem eduquei donzelas.

[[v23-23-5]]

^<<v23-23-5,5>>^ Quando a notícia a respeito de Tiro chegar ao Egito, com ela se angustiarão os homens.

[[v23-23-6]]

^<<v23-23-6,6>>^ Passai a Társis, uivai, moradores do litoral.

[[v23-23-7]]

^<<v23-23-7,7>>^ É esta, acaso, a vossa cidade que andava exultante, cuja origem data de remotos dias, cujos pés a levaram até longe para estabelecer-se?

[[v23-23-8]]

^<<v23-23-8,8>>^ Quem formou este desígnio contra Tiro, a cidade distribuidora de coroas, cujos mercadores são príncipes e cujos negociantes são os mais nobres da terra?

[[v23-23-9]]

^<<v23-23-9,9>>^ O SENHOR dos Exércitos formou este desígnio para denegrir a soberba de toda beleza e envilecer os mais nobres da terra.

[[v23-23-10]]

^<<v23-23-10,10>>^ Percorre livremente como o Nilo a tua terra, ó filha de Társis; já não há quem te restrinja.

[[v23-23-11]]

^<<v23-23-11,11>>^ O SENHOR estendeu a mão sobre o mar e turbou os reinos; deu ordens contra Canaã, para que se destruíssem as suas fortalezas.

[[v23-23-12]]

^<<v23-23-12,12>>^ E disse: Nunca mais exultarás, ó oprimida virgem filha de Sidom; levanta-te, passa a Chipre, mas ainda ali não terás descanso.

[[v23-23-13]]

^<<v23-23-13,13>>^ Eis a terra dos caldeus, povo que até há pouco não era povo e que a Assíria destinara para os sátiros do deserto; povo que levantou suas torres, e arrasou os palácios de Tiro, e os converteu em ruínas.

[[v23-23-14]]

^<<v23-23-14,14>>^ Uivai, navios de Társis, porque é destruída a que era a vossa fortaleza!

[[v23-23-15]]

^<<v23-23-15,15>>^ Naquele dia, Tiro será posta em esquecimento por setenta anos, segundo os dias de um rei; mas no fim dos setenta anos dar-se-á com Tiro o que consta na canção da meretriz:

[[v23-23-16]]

^<<v23-23-16,16>>^ Toma a harpa, rodeia a cidade, ó meretriz, entregue ao esquecimento; canta bem, toca, multiplica as tuas canções, para que se recordem de ti.

[[v23-23-17]]

^<<v23-23-17,17>>^ Findos os setenta anos, o SENHOR atentará para Tiro, e ela tornará ao salário da sua impureza e se prostituirá com todos os reinos da terra.

[[v23-23-18]]

^<<v23-23-18,18>>^ O ganho e o salário de sua impureza serão dedicados ao SENHOR; não serão entesourados, nem guardados, mas o seu ganho será para os que habitam perante o SENHOR, para que tenham comida em abundância e vestes finas.

'''

xref:023-isaias/023-isaias-022.adoc#v23-22-0[&#60; Capítulo Anterior] | <<v23-23-0,Topo>> | xref:023-isaias/023-isaias-024.adoc#v23-24-0[Próximo Capítulo &#62;]