include::./index.adoc[]

[[v23-54-0]]
=== Isaías, 54
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-54-1]]

^<<v23-54-1,1>>^ Canta alegremente, ó estéril, que não deste à luz; exulta com alegre canto e exclama, tu que não tiveste dores de parto; porque mais são os filhos da mulher solitária do que os filhos da casada, diz o SENHOR.

[[v23-54-2]]

^<<v23-54-2,2>>^ Alarga o espaço da tua tenda; estenda-se o toldo da tua habitação, e não o impeças; alonga as tuas cordas e firma bem as tuas estacas.

[[v23-54-3]]

^<<v23-54-3,3>>^ Porque transbordarás para a direita e para a esquerda; a tua posteridade possuirá as nações e fará que se povoem as cidades assoladas.

[[v23-54-4]]

^<<v23-54-4,4>>^ Não temas, porque não serás envergonhada; não te envergonhes, porque não sofrerás humilhação; pois te esquecerás da vergonha da tua mocidade e não mais te lembrarás do opróbrio da tua viuvez.

[[v23-54-5]]

^<<v23-54-5,5>>^ Porque o teu Criador é o teu marido; o SENHOR dos Exércitos é o seu nome; e o Santo de Israel é o teu Redentor; ele é chamado o Deus de toda a terra.

[[v23-54-6]]

^<<v23-54-6,6>>^ Porque o SENHOR te chamou como a mulher desamparada e de espírito abatido; como a mulher da mocidade, que fora repudiada, diz o teu Deus.

[[v23-54-7]]

^<<v23-54-7,7>>^ Por breve momento te deixei, mas com grandes misericórdias torno a acolher-te;

[[v23-54-8]]

^<<v23-54-8,8>>^ num ímpeto de indignação, escondi de ti a minha face por um momento; mas com misericórdia eterna me compadeço de ti, diz o SENHOR, o teu Redentor.

[[v23-54-9]]

^<<v23-54-9,9>>^ Porque isto é para mim como as águas de Noé; pois jurei que as águas de Noé não mais inundariam a terra, e assim jurei que não mais me iraria contra ti, nem te repreenderia.

[[v23-54-10]]

^<<v23-54-10,10>>^ Porque os montes se retirarão, e os outeiros serão removidos; mas a minha misericórdia não se apartará de ti, e a aliança da minha paz não será removida, diz o SENHOR, que se compadece de ti.

[[v23-54-11]]

^<<v23-54-11,11>>^ Ó tu, aflita, arrojada com a tormenta e desconsolada! Eis que eu assentarei as tuas pedras com argamassa colorida e te fundarei sobre safiras.

[[v23-54-12]]

^<<v23-54-12,12>>^ Farei os teus baluartes de rubis, as tuas portas, de carbúnculos e toda a tua muralha, de pedras preciosas.

[[v23-54-13]]

^<<v23-54-13,13>>^ Todos os teus filhos serão ensinados do SENHOR; e será grande a paz de teus filhos.

[[v23-54-14]]

^<<v23-54-14,14>>^ Serás estabelecida em justiça, longe da opressão, porque já não temerás, e também do espanto, porque não chegará a ti.

[[v23-54-15]]

^<<v23-54-15,15>>^ Eis que poderão suscitar contendas, mas não procederá de mim; quem conspira contra ti cairá diante de ti.

[[v23-54-16]]

^<<v23-54-16,16>>^ Eis que eu criei o ferreiro, que assopra as brasas no fogo e que produz a arma para o seu devido fim; também criei o assolador, para destruir.

[[v23-54-17]]

^<<v23-54-17,17>>^ Toda arma forjada contra ti não prosperará; toda língua que ousar contra ti em juízo, tu a condenarás; esta é a herança dos servos do SENHOR e o seu direito que de mim procede, diz o SENHOR.

'''

xref:023-isaias/023-isaias-053.adoc#v23-53-0[&#60; Capítulo Anterior] | <<v23-54-0,Topo>> | xref:023-isaias/023-isaias-055.adoc#v23-55-0[Próximo Capítulo &#62;]