include::./index.adoc[]

[[v23-41-0]]
=== Isaías, 41
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-41-1]]

^<<v23-41-1,1>>^ Calai-vos perante mim, ó ilhas, e os povos renovem as suas forças; cheguem-se e, então, falem; cheguemo-nos e pleiteemos juntos.

[[v23-41-2]]

^<<v23-41-2,2>>^ Quem suscitou do Oriente aquele a cujos passos segue a vitória? Quem faz que as nações se lhe submetam, e que ele calque aos pés os reis, e com a sua espada os transforme em pó, e com o seu arco, em palha que o vento arrebata?

[[v23-41-3]]

^<<v23-41-3,3>>^ Persegue-os e passa adiante em segurança, por uma vereda que seus pés jamais trilharam.

[[v23-41-4]]

^<<v23-41-4,4>>^ Quem fez e executou tudo isso? Aquele que desde o princípio tem chamado as gerações à existência, eu, o SENHOR, o primeiro, e com os últimos eu mesmo.

[[v23-41-5]]

^<<v23-41-5,5>>^ Os países do mar viram isto e temeram, os fins da terra tremeram, aproximaram-se e vieram.

[[v23-41-6]]

^<<v23-41-6,6>>^ Um ao outro ajudou e ao seu próximo disse: Sê forte.

[[v23-41-7]]

^<<v23-41-7,7>>^ Assim, o artífice anima ao ourives, e o que alisa com o martelo, ao que bate na bigorna, dizendo da soldadura: Está bem-feita. Então, com pregos fixa o ídolo para que não oscile.

[[v23-41-8]]

^<<v23-41-8,8>>^ Mas tu, ó Israel, servo meu, tu, Jacó, a quem elegi, descendente de Abraão, meu amigo,

[[v23-41-9]]

^<<v23-41-9,9>>^ tu, a quem tomei das extremidades da terra, e chamei dos seus cantos mais remotos, e a quem disse: Tu és o meu servo, eu te escolhi e não te rejeitei,

[[v23-41-10]]

^<<v23-41-10,10>>^ não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te fortaleço, e te ajudo, e te sustento com a minha destra fiel.

[[v23-41-11]]

^<<v23-41-11,11>>^ Eis que envergonhados e confundidos serão todos os que estão indignados contra ti; serão reduzidos a nada, e os que contendem contigo perecerão.

[[v23-41-12]]

^<<v23-41-12,12>>^ Aos que pelejam contra ti, buscá-los-ás, porém não os acharás; serão reduzidos a nada e a coisa de nenhum valor os que fazem guerra contra ti.

[[v23-41-13]]

^<<v23-41-13,13>>^ Porque eu, o SENHOR, teu Deus, te tomo pela tua mão direita e te digo: Não temas, que eu te ajudo.

[[v23-41-14]]

^<<v23-41-14,14>>^ Não temas, ó vermezinho de Jacó, povozinho de Israel; eu te ajudo, diz o SENHOR, e o teu Redentor é o Santo de Israel.

[[v23-41-15]]

^<<v23-41-15,15>>^ Eis que farei de ti um trilho cortante e novo, armado de lâminas duplas; os montes trilharás, e moerás, e os outeiros reduzirás a palha.

[[v23-41-16]]

^<<v23-41-16,16>>^ Tu os padejarás, e o vento os levará, e redemoinho os espalhará; tu te alegrarás no SENHOR e te gloriarás no Santo de Israel.

[[v23-41-17]]

^<<v23-41-17,17>>^ Os aflitos e necessitados buscam águas, e não as há, e a sua língua se seca de sede; mas eu, o SENHOR, os ouvirei, eu, o Deus de Israel, não os desampararei.

[[v23-41-18]]

^<<v23-41-18,18>>^ Abrirei rios nos altos desnudos e fontes no meio dos vales; tornarei o deserto em açudes de águas e a terra seca, em mananciais.

[[v23-41-19]]

^<<v23-41-19,19>>^ Plantarei no deserto o cedro, a acácia, a murta e a oliveira; conjuntamente, porei no ermo o cipreste, o olmeiro e o buxo,

[[v23-41-20]]

^<<v23-41-20,20>>^ para que todos vejam e saibam, considerem e juntamente entendam que a mão do SENHOR fez isso, e o Santo de Israel o criou.

[[v23-41-21]]

^<<v23-41-21,21>>^ Apresentai a vossa demanda, diz o SENHOR; alegai as vossas razões, diz o Rei de Jacó.

[[v23-41-22]]

^<<v23-41-22,22>>^ Trazei e anunciai-nos as coisas que hão de acontecer; relatai-nos as profecias anteriores, para que atentemos para elas e saibamos se se cumpriram; ou fazei-nos ouvir as coisas futuras.

[[v23-41-23]]

^<<v23-41-23,23>>^ Anunciai-nos as coisas que ainda hão de vir, para que saibamos que sois deuses; fazei bem ou fazei mal, para que nos assombremos, e juntamente o veremos.

[[v23-41-24]]

^<<v23-41-24,24>>^ Eis que sois menos do que nada, e menos do que nada é o que fazeis; abominação é quem vos escolhe.

[[v23-41-25]]

^<<v23-41-25,25>>^ Do Norte suscito a um, e ele vem, a um desde o nascimento do sol, e ele invocará o meu nome; pisará magistrados como lodo e como o oleiro pisa o barro.

[[v23-41-26]]

^<<v23-41-26,26>>^ Quem anunciou isto desde o princípio, a fim que o possamos saber, antecipadamente, para que digamos: É isso mesmo? Mas não há quem anuncie, nem tampouco quem manifeste, nem ainda quem ouça as vossas palavras.

[[v23-41-27]]

^<<v23-41-27,27>>^ Eu sou o que primeiro disse a Sião: Eis! Ei-los aí! E a Jerusalém dou um mensageiro de boas-novas.

[[v23-41-28]]

^<<v23-41-28,28>>^ Quando eu olho, não há ninguém; nem mesmo entre eles há conselheiro a quem eu pergunte, e me responda.

[[v23-41-29]]

^<<v23-41-29,29>>^ Eis que todos são nada; as suas obras são coisa nenhuma; as suas imagens de fundição, vento e vácuo.

'''

xref:023-isaias/023-isaias-040.adoc#v23-40-0[&#60; Capítulo Anterior] | <<v23-41-0,Topo>> | xref:023-isaias/023-isaias-042.adoc#v23-42-0[Próximo Capítulo &#62;]