include::./index.adoc[]

[[v23-20-0]]
=== Isaías, 20
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-20-1]]

^<<v23-20-1,1>>^ No ano em que Tartã, enviado por Sargão, rei da Assíria, veio a Asdode, e a guerreou, e a tomou,

[[v23-20-2]]

^<<v23-20-2,2>>^ nesse mesmo tempo, falou o SENHOR por intermédio de Isaías, filho de Amoz, dizendo: Vai, solta de teus lombos o pano grosseiro de profeta e tira dos pés o calçado. Assim ele o fez, indo despido e descalço.

[[v23-20-3]]

^<<v23-20-3,3>>^ Então, disse o SENHOR: Assim como Isaías, meu servo, andou três anos despido e descalço, por sinal e prodígio contra o Egito e contra a Etiópia,

[[v23-20-4]]

^<<v23-20-4,4>>^ assim o rei da Assíria levará os presos do Egito e os exilados da Etiópia, tanto moços como velhos, despidos e descalços e com as nádegas descobertas, para vergonha do Egito.

[[v23-20-5]]

^<<v23-20-5,5>>^ Então, se assombrarão os israelitas e se envergonharão por causa dos etíopes, sua esperança, e dos egípcios, sua glória.

[[v23-20-6]]

^<<v23-20-6,6>>^ Os moradores desta região dirão naquele dia: Vede, foi isto que aconteceu àqueles em quem esperávamos e a quem fugimos por socorro, para livrar-nos do rei da Assíria! Como, pois, escaparemos nós?

'''

xref:023-isaias/023-isaias-019.adoc#v23-19-0[&#60; Capítulo Anterior] | <<v23-20-0,Topo>> | xref:023-isaias/023-isaias-021.adoc#v23-21-0[Próximo Capítulo &#62;]