include::./index.adoc[]

[[v23-10-0]]
=== Isaías, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-10-1]]

^<<v23-10-1,1>>^ Ai dos que decretam leis injustas, dos que escrevem leis de opressão,

[[v23-10-2]]

^<<v23-10-2,2>>^ para negarem justiça aos pobres, para arrebatarem o direito aos aflitos do meu povo, a fim de despojarem as viúvas e roubarem os órfãos!

[[v23-10-3]]

^<<v23-10-3,3>>^ Mas que fareis vós outros no dia do castigo, na calamidade que vem de longe? A quem recorrereis para obter socorro e onde deixareis a vossa glória?

[[v23-10-4]]

^<<v23-10-4,4>>^ Nada mais vos resta a fazer, senão dobrar-vos entre os prisioneiros e cair entre os mortos. Com tudo isto, não se aparta a sua ira, e a mão dele continua ainda estendida.

[[v23-10-5]]

^<<v23-10-5,5>>^ Ai da Assíria, cetro da minha ira! A vara em sua mão é o instrumento do meu furor.

[[v23-10-6]]

^<<v23-10-6,6>>^ Envio-a contra uma nação ímpia e contra o povo da minha indignação lhe dou ordens, para que dele roube a presa, e lhe tome o despojo, e o ponha para ser pisado aos pés, como a lama das ruas.

[[v23-10-7]]

^<<v23-10-7,7>>^ Ela, porém, assim não pensa, o seu coração não entende assim; antes, intenta consigo mesma destruir e desarraigar não poucas nações.

[[v23-10-8]]

^<<v23-10-8,8>>^ Porque diz: Não são meus príncipes todos eles reis?

[[v23-10-9]]

^<<v23-10-9,9>>^ Não é Calno como Carquemis? Não é Hamate como Arpade? E Samaria, como Damasco?

[[v23-10-10]]

^<<v23-10-10,10>>^ O meu poder atingiu os reinos dos ídolos, ainda que as suas imagens de escultura eram melhores do que as de Jerusalém e do que as de Samaria.

[[v23-10-11]]

^<<v23-10-11,11>>^ Porventura, como fiz a Samaria e aos seus ídolos, não o faria igualmente a Jerusalém e aos seus ídolos?

[[v23-10-12]]

^<<v23-10-12,12>>^ Por isso, acontecerá que, havendo o Senhor acabado toda a sua obra no monte Sião e em Jerusalém, então, castigará a arrogância do coração do rei da Assíria e a desmedida altivez dos seus olhos;

[[v23-10-13]]

^<<v23-10-13,13>>^ porquanto o rei disse: Com o poder da minha mão, fiz isto, e com a minha sabedoria, porque sou inteligente; removi os limites dos povos, e roubei os seus tesouros, e como valente abati os que se assentavam em tronos.

[[v23-10-14]]

^<<v23-10-14,14>>^ Meti a mão nas riquezas dos povos como a um ninho e, como se ajuntam os ovos abandonados, assim eu ajuntei toda a terra, e não houve quem movesse a asa, ou abrisse a boca, ou piasse.

[[v23-10-15]]

^<<v23-10-15,15>>^ Porventura, gloriar-se-á o machado contra o que corta com ele? Ou presumirá a serra contra o que a maneja? Seria isso como se a vara brandisse os que a levantam ou o bastão levantasse a quem não é pau!

[[v23-10-16]]

^<<v23-10-16,16>>^ Pelo que o Senhor, o SENHOR dos Exércitos, enviará a tísica contra os seus homens, todos gordos, e debaixo da sua glória acenderá uma queima, como a queima de fogo.

[[v23-10-17]]

^<<v23-10-17,17>>^ Porque a Luz de Israel virá a ser como fogo, e o seu Santo, como labareda, que abrase e consuma os espinheiros e os abrolhos da Assíria, num só dia.

[[v23-10-18]]

^<<v23-10-18,18>>^ Também consumirá a glória da sua floresta e do seu campo fértil, desde a alma até ao corpo; e será como quando um doente se definha.

[[v23-10-19]]

^<<v23-10-19,19>>^ O resto das árvores da sua floresta será tão pouco, que um menino saberá escrever o número delas.

[[v23-10-20]]

^<<v23-10-20,20>>^ Acontecerá, naquele dia, que os restantes de Israel e os da casa de Jacó que se tiverem salvado nunca mais se estribarão naquele que os feriu, mas, com efeito, se estribarão no SENHOR, o Santo de Israel.

[[v23-10-21]]

^<<v23-10-21,21>>^ Os restantes se converterão ao Deus forte, sim, os restantes de Jacó.

[[v23-10-22]]

^<<v23-10-22,22>>^ Porque ainda que o teu povo, ó Israel, seja como a areia do mar, o restante se converterá; destruição será determinada, transbordante de justiça.

[[v23-10-23]]

^<<v23-10-23,23>>^ Porque uma destruição, e essa já determinada, o Senhor, o SENHOR dos Exércitos, a executará no meio de toda esta terra.

[[v23-10-24]]

^<<v23-10-24,24>>^ Pelo que assim diz o Senhor, o SENHOR dos Exércitos: Povo meu, que habitas em Sião, não temas a Assíria, quando te ferir com a vara e contra ti levantar o seu bastão à maneira dos egípcios;

[[v23-10-25]]

^<<v23-10-25,25>>^ porque daqui a bem pouco se cumprirá a minha indignação e a minha ira, para a consumir.

[[v23-10-26]]

^<<v23-10-26,26>>^ Porque o SENHOR dos Exércitos suscitará contra ela um flagelo, como a matança de Midiã junto à penha de Orebe; a sua vara estará sobre o mar, e ele a levantará como fez no Egito.

[[v23-10-27]]

^<<v23-10-27,27>>^ Acontecerá, naquele dia, que o peso será tirado do teu ombro, e o seu jugo, do teu pescoço, jugo que será despedaçado por causa da gordura.

[[v23-10-28]]

^<<v23-10-28,28>>^ A Assíria vem a Aiate, passa por Migrom e em Micmás larga a sua bagagem.

[[v23-10-29]]

^<<v23-10-29,29>>^ Passa o desfiladeiro, aloja-se em Geba, já Ramá treme, Gibeá de Saul foge.

[[v23-10-30]]

^<<v23-10-30,30>>^ Ergue com estrídulo a voz, ó filha de Galim! Ouve, ó Laís! Oh! Pobre Anatote!

[[v23-10-31]]

^<<v23-10-31,31>>^ Madmena se dispersa; os moradores de Gebim fogem para salvar-se.

[[v23-10-32]]

^<<v23-10-32,32>>^ Nesse mesmo dia, a Assíria parará em Nobe; agitará o punho ao monte da filha de Sião, o outeiro de Jerusalém.

[[v23-10-33]]

^<<v23-10-33,33>>^ Mas eis que o Senhor, o SENHOR dos Exércitos, cortará os ramos com violência, as árvores de alto porte serão derribadas, e as altivas serão abatidas.

[[v23-10-34]]

^<<v23-10-34,34>>^ Cortará com o ferro as brenhas da floresta, e o Líbano cairá pela mão de um poderoso.

'''

xref:023-isaias/023-isaias-009.adoc#v23-9-0[&#60; Capítulo Anterior] | <<v23-10-0,Topo>> | xref:023-isaias/023-isaias-011.adoc#v23-11-0[Próximo Capítulo &#62;]