include::./index.adoc[]

[[v23-5-0]]
=== Isaías, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-5-1]]

^<<v23-5-1,1>>^ Agora, cantarei ao meu amado o cântico do meu amado a respeito da sua vinha. O meu amado teve uma vinha num outeiro fertilíssimo.

[[v23-5-2]]

^<<v23-5-2,2>>^ Sachou-a, limpou-a das pedras e a plantou de vides escolhidas; edificou no meio dela uma torre e também abriu um lagar. Ele esperava que desse uvas boas, mas deu uvas bravas.

[[v23-5-3]]

^<<v23-5-3,3>>^ Agora, pois, ó moradores de Jerusalém e homens de Judá, julgai, vos peço, entre mim e a minha vinha.

[[v23-5-4]]

^<<v23-5-4,4>>^ Que mais se podia fazer ainda à minha vinha, que eu lhe não tenha feito? E como, esperando eu que desse uvas boas, veio a produzir uvas bravas?

[[v23-5-5]]

^<<v23-5-5,5>>^ Agora, pois, vos farei saber o que pretendo fazer à minha vinha: tirarei a sua sebe, para que a vinha sirva de pasto; derribarei o seu muro, para que seja pisada;

[[v23-5-6]]

^<<v23-5-6,6>>^ torná-la-ei em deserto. Não será podada, nem sachada, mas crescerão nela espinheiros e abrolhos; às nuvens darei ordem que não derramem chuva sobre ela.

[[v23-5-7]]

^<<v23-5-7,7>>^ Porque a vinha do SENHOR dos Exércitos é a casa de Israel, e os homens de Judá são a planta dileta do SENHOR; este desejou que exercessem juízo, e eis aí quebrantamento da lei; justiça, e eis aí clamor.

[[v23-5-8]]

^<<v23-5-8,8>>^ Ai dos que ajuntam casa a casa, reúnem campo a campo, até que não haja mais lugar, e ficam como únicos moradores no meio da terra!

[[v23-5-9]]

^<<v23-5-9,9>>^ A meus ouvidos disse o SENHOR dos Exércitos: Em verdade, muitas casas ficarão desertas, até as grandes e belas, sem moradores.

[[v23-5-10]]

^<<v23-5-10,10>>^ E dez jeiras de vinha não darão mais do que um bato, e um ômer cheio de semente não dará mais do que um efa.

[[v23-5-11]]

^<<v23-5-11,11>>^ Ai dos que se levantam pela manhã e seguem a bebedice e continuam até alta noite, até que o vinho os esquenta!

[[v23-5-12]]

^<<v23-5-12,12>>^ Liras e harpas, tamboris e flautas e vinho há nos seus banquetes; porém não consideram os feitos do SENHOR, nem olham para as obras das suas mãos.

[[v23-5-13]]

^<<v23-5-13,13>>^ Portanto, o meu povo será levado cativo, por falta de entendimento; os seus nobres terão fome, e a sua multidão se secará de sede.

[[v23-5-14]]

^<<v23-5-14,14>>^ Por isso, a cova aumentou o seu apetite, abriu a sua boca desmesuradamente; para lá desce a glória de Jerusalém, e o seu tumulto, e o seu ruído, e quem nesse meio folgava.

[[v23-5-15]]

^<<v23-5-15,15>>^ Então, a gente se abate, e o homem se avilta; e os olhos dos altivos são humilhados.

[[v23-5-16]]

^<<v23-5-16,16>>^ Mas o SENHOR dos Exércitos é exaltado em juízo; e Deus, o Santo, é santificado em justiça.

[[v23-5-17]]

^<<v23-5-17,17>>^ Então, os cordeiros pastarão lá como se no seu pasto; e os nômades se nutrirão dos campos dos ricos lá abandonados.

[[v23-5-18]]

^<<v23-5-18,18>>^ Ai dos que puxam para si a iniquidade com cordas de injustiça e o pecado, como com tirantes de carro!

[[v23-5-19]]

^<<v23-5-19,19>>^ E dizem: Apresse-se Deus, leve a cabo a sua obra, para que a vejamos; aproxime-se, manifeste-se o conselho do Santo de Israel, para que o conheçamos.

[[v23-5-20]]

^<<v23-5-20,20>>^ Ai dos que ao mal chamam bem e ao bem, mal; que fazem da escuridade luz e da luz, escuridade; põem o amargo por doce e o doce, por amargo!

[[v23-5-21]]

^<<v23-5-21,21>>^ Ai dos que são sábios a seus próprios olhos e prudentes em seu próprio conceito!

[[v23-5-22]]

^<<v23-5-22,22>>^ Ai dos que são heróis para beber vinho e valentes para misturar bebida forte,

[[v23-5-23]]

^<<v23-5-23,23>>^ os quais por suborno justificam o perverso e ao justo negam justiça!

[[v23-5-24]]

^<<v23-5-24,24>>^ Pelo que, como a língua de fogo consome o restolho, e a erva seca se desfaz pela chama, assim será a sua raiz como podridão, e a sua flor se esvaecerá como pó; porquanto rejeitaram a lei do SENHOR dos Exércitos e desprezaram a palavra do Santo de Israel.

[[v23-5-25]]

^<<v23-5-25,25>>^ Por isso, se acende a ira do SENHOR contra o seu povo, povo contra o qual estende a mão e o fere, de modo que tremem os montes e os seus cadáveres são como monturo no meio das ruas. Com tudo isto não se aplaca a sua ira, mas ainda está estendida a sua mão.

[[v23-5-26]]

^<<v23-5-26,26>>^ Ele arvorará o estandarte para as nações distantes e lhes assobiará para que venham das extremidades da terra; e vêm apressadamente.

[[v23-5-27]]

^<<v23-5-27,27>>^ Não há entre elas cansado, nem quem tropece; ninguém tosqueneja, nem dorme; não se lhe desata o cinto dos seus lombos, nem se lhe rompe das sandálias a correia.

[[v23-5-28]]

^<<v23-5-28,28>>^ As suas flechas são agudas, e todos os seus arcos, retesados; as unhas dos seus cavalos dizem-se de pederneira, e as rodas dos seus carros, um redemoinho.

[[v23-5-29]]

^<<v23-5-29,29>>^ O seu rugido é como o do leão; rugem como filhos de leão, e, rosnando, arrebatam a presa, e a levam, e não há quem a livre.

[[v23-5-30]]

^<<v23-5-30,30>>^ Bramam contra eles naquele dia, como o bramido do mar; se alguém olhar para a terra, eis que só há trevas e angústia, e a luz se escurece em densas nuvens.

'''

xref:023-isaias/023-isaias-004.adoc#v23-4-0[&#60; Capítulo Anterior] | <<v23-5-0,Topo>> | xref:023-isaias/023-isaias-006.adoc#v23-6-0[Próximo Capítulo &#62;]