include::./index.adoc[]

[[v23-44-0]]
=== Isaías, 44
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-44-1]]

^<<v23-44-1,1>>^ Agora, pois, ouve, ó Jacó, servo meu, ó Israel, a quem escolhi.

[[v23-44-2]]

^<<v23-44-2,2>>^ Assim diz o SENHOR, que te criou, e te formou desde o ventre, e que te ajuda: Não temas, ó Jacó, servo meu, ó amado, a quem escolhi.

[[v23-44-3]]

^<<v23-44-3,3>>^ Porque derramarei água sobre o sedento e torrentes, sobre a terra seca; derramarei o meu Espírito sobre a tua posteridade e a minha bênção, sobre os teus descendentes;

[[v23-44-4]]

^<<v23-44-4,4>>^ e brotarão como a erva, como salgueiros junto às correntes das águas.

[[v23-44-5]]

^<<v23-44-5,5>>^ Um dirá: Eu sou do SENHOR; outro se chamará do nome de Jacó; o outro ainda escreverá na própria mão: Eu sou do SENHOR, e por sobrenome tomará o nome de Israel.

[[v23-44-6]]

^<<v23-44-6,6>>^ Assim diz o SENHOR, Rei de Israel, seu Redentor, o SENHOR dos Exércitos: Eu sou o primeiro e eu sou o último, e além de mim não há Deus.

[[v23-44-7]]

^<<v23-44-7,7>>^ Quem há, como eu, feito predições desde que estabeleci o mais antigo povo? Que o declare e o exponha perante mim! Que esse anuncie as coisas futuras, as coisas que hão de vir!

[[v23-44-8]]

^<<v23-44-8,8>>^ Não vos assombreis, nem temais; acaso, desde aquele tempo não vo-lo fiz ouvir, não vo-lo anunciei? Vós sois as minhas testemunhas. Há outro Deus além de mim? Não, não há outra Rocha que eu conheça.

[[v23-44-9]]

^<<v23-44-9,9>>^ Todos os artífices de imagens de escultura são nada, e as suas coisas preferidas são de nenhum préstimo; eles mesmos são testemunhas de que elas nada veem, nem entendem, para que eles sejam confundidos.

[[v23-44-10]]

^<<v23-44-10,10>>^ Quem formaria um deus ou fundiria uma imagem de escultura, que é de nenhum préstimo?

[[v23-44-11]]

^<<v23-44-11,11>>^ Eis que todos os seus seguidores ficariam confundidos, pois os mesmos artífices não passam de homens; ajuntem-se todos e se apresentem, espantem-se e sejam, à uma, envergonhados.

[[v23-44-12]]

^<<v23-44-12,12>>^ O ferreiro faz o machado, trabalha nas brasas, forma um ídolo a martelo e forja-o com a força do seu braço; ele tem fome, e a sua força falta, não bebe água e desfalece.

[[v23-44-13]]

^<<v23-44-13,13>>^ O artífice em madeira estende o cordel e, com o lápis, esboça uma imagem; alisa-a com plaina, marca com o compasso e faz à semelhança e beleza de um homem, que possa morar em uma casa.

[[v23-44-14]]

^<<v23-44-14,14>>^ Um homem corta para si cedros, toma um cipreste ou um carvalho, fazendo escolha entre as árvores do bosque; planta um pinheiro, e a chuva o faz crescer.

[[v23-44-15]]

^<<v23-44-15,15>>^ Tais árvores servem ao homem para queimar; com parte de sua madeira se aquenta e coze o pão; e também faz um deus e se prostra diante dele, esculpe uma imagem e se ajoelha diante dela.

[[v23-44-16]]

^<<v23-44-16,16>>^ Metade queima no fogo e com ela coze a carne para comer; assa-a e farta-se; também se aquenta e diz: Ah! Já me aquento, contemplo a luz.

[[v23-44-17]]

^<<v23-44-17,17>>^ Então, do resto faz um deus, uma imagem de escultura; ajoelha-se diante dela, prostra-se e lhe dirige a sua oração, dizendo: Livra-me, porque tu és o meu deus.

[[v23-44-18]]

^<<v23-44-18,18>>^ Nada sabem, nem entendem; porque se lhes grudaram os olhos, para que não vejam, e o seu coração já não pode entender.

[[v23-44-19]]

^<<v23-44-19,19>>^ Nenhum deles cai em si, já não há conhecimento nem compreensão para dizer: Metade queimei e cozi pão sobre as suas brasas, assei sobre elas carne e a comi; e faria eu do resto uma abominação? Ajoelhar-me-ia eu diante de um pedaço de árvore?

[[v23-44-20]]

^<<v23-44-20,20>>^ Tal homem se apascenta de cinza; o seu coração enganado o iludiu, de maneira que não pode livrar a sua alma, nem dizer: Não é mentira aquilo em que confio?

[[v23-44-21]]

^<<v23-44-21,21>>^ Lembra-te destas coisas, ó Jacó, ó Israel, porquanto és meu servo! Eu te formei, tu és meu servo, ó Israel; não me esquecerei de ti.

[[v23-44-22]]

^<<v23-44-22,22>>^ Desfaço as tuas transgressões como a névoa e os teus pecados, como a nuvem; torna-te para mim, porque eu te remi.

[[v23-44-23]]

^<<v23-44-23,23>>^ Regozijai-vos, ó céus, porque o SENHOR fez isto; exultai, vós, ó profundezas da terra; retumbai com júbilo, vós, montes, vós, bosques e todas as suas árvores, porque o SENHOR remiu a Jacó e se glorificou em Israel.

[[v23-44-24]]

^<<v23-44-24,24>>^ Assim diz o SENHOR, que te redime, o mesmo que te formou desde o ventre materno: Eu sou o SENHOR, que faço todas as coisas, que sozinho estendi os céus e sozinho espraiei a terra;

[[v23-44-25]]

^<<v23-44-25,25>>^ que desfaço os sinais dos profetizadores de mentiras e enlouqueço os adivinhos; que faço tornar atrás os sábios, cujo saber converto em loucuras;

[[v23-44-26]]

^<<v23-44-26,26>>^ que confirmo a palavra do meu servo e cumpro o conselho dos meus mensageiros; que digo de Jerusalém: Ela será habitada; e das cidades de Judá: Elas serão edificadas; e quanto às suas ruínas: Eu as levantarei;

[[v23-44-27]]

^<<v23-44-27,27>>^ que digo à profundeza das águas: Seca-te, e eu secarei os teus rios;

[[v23-44-28]]

^<<v23-44-28,28>>^ que digo de Ciro: Ele é meu pastor e cumprirá tudo o que me apraz; que digo também de Jerusalém: Será edificada; e do templo: Será fundado.

'''

xref:023-isaias/023-isaias-043.adoc#v23-43-0[&#60; Capítulo Anterior] | <<v23-44-0,Topo>> | xref:023-isaias/023-isaias-045.adoc#v23-45-0[Próximo Capítulo &#62;]