include::./index.adoc[]

[[v23-66-0]]
=== Isaías, 66
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-66-1]]

^<<v23-66-1,1>>^ Assim diz o SENHOR: O céu é o meu trono, e a terra, o estrado dos meus pés; que casa me edificareis vós? E qual é o lugar do meu repouso?

[[v23-66-2]]

^<<v23-66-2,2>>^ Porque a minha mão fez todas estas coisas, e todas vieram a existir, diz o SENHOR, mas o homem para quem olharei é este: o aflito e abatido de espírito e que treme da minha palavra.

[[v23-66-3]]

^<<v23-66-3,3>>^ O que imola um boi é como o que comete homicídio; o que sacrifica um cordeiro, como o que quebra o pescoço a um cão; o que oferece uma oblação, como o que oferece sangue de porco; o que queima incenso, como o que bendiz a um ídolo. Como estes escolheram os seus próprios caminhos, e a sua alma se deleita nas suas abominações,

[[v23-66-4]]

^<<v23-66-4,4>>^ assim eu lhes escolherei o infortúnio e farei vir sobre eles o que eles temem; porque clamei, e ninguém respondeu, falei, e não escutaram; mas fizeram o que era mau perante mim e escolheram aquilo em que eu não tinha prazer.

[[v23-66-5]]

^<<v23-66-5,5>>^ Ouvi a palavra do SENHOR, vós, os que a temeis: Vossos irmãos, que vos aborrecem e que para longe vos lançam por causa do vosso amor ao meu nome e que dizem: Mostre o SENHOR a sua glória, para que vejamos a vossa alegria, esses serão confundidos.

[[v23-66-6]]

^<<v23-66-6,6>>^ Voz de grande tumulto virá da cidade, voz do templo, voz do SENHOR, que dá o pago aos seus inimigos.

[[v23-66-7]]

^<<v23-66-7,7>>^ Antes que estivesse de parto, deu à luz; antes que lhe viessem as dores, nasceu-lhe um menino.

[[v23-66-8]]

^<<v23-66-8,8>>^ Quem jamais ouviu tal coisa? Quem viu coisa semelhante? Pode, acaso, nascer uma terra num só dia? Ou nasce uma nação de uma só vez? Pois Sião, antes que lhe viessem as dores, deu à luz seus filhos.

[[v23-66-9]]

^<<v23-66-9,9>>^ Acaso, farei eu abrir a madre e não farei nascer? — diz o SENHOR; acaso, eu que faço nascer fecharei a madre? — diz o teu Deus.

[[v23-66-10]]

^<<v23-66-10,10>>^ Regozijai-vos juntamente com Jerusalém e alegrai-vos por ela, vós todos os que a amais; exultai com ela, todos os que por ela pranteastes,

[[v23-66-11]]

^<<v23-66-11,11>>^ para que mameis e vos farteis dos peitos das suas consolações; para que sugueis e vos deleiteis com a abundância da sua glória.

[[v23-66-12]]

^<<v23-66-12,12>>^ Porque assim diz o SENHOR: Eis que estenderei sobre ela a paz como um rio, e a glória das nações, como uma torrente que transborda; então, mamareis, nos braços vos trarão e sobre os joelhos vos acalentarão.

[[v23-66-13]]

^<<v23-66-13,13>>^ Como alguém a quem sua mãe consola, assim eu vos consolarei; e em Jerusalém vós sereis consolados.

[[v23-66-14]]

^<<v23-66-14,14>>^ Vós o vereis, e o vosso coração se regozijará, e os vossos ossos revigorarão como a erva tenra; então, o poder do SENHOR será notório aos seus servos, e ele se indignará contra os seus inimigos.

[[v23-66-15]]

^<<v23-66-15,15>>^ Porque eis que o SENHOR virá em fogo, e os seus carros, como um torvelinho, para tornar a sua ira em furor e a sua repreensão, em chamas de fogo,

[[v23-66-16]]

^<<v23-66-16,16>>^ porque com fogo e com a sua espada entrará o SENHOR em juízo com toda a carne; e serão muitos os mortos da parte do SENHOR.

[[v23-66-17]]

^<<v23-66-17,17>>^ Os que se santificam e se purificam para entrarem nos jardins após a deusa que está no meio, que comem carne de porco, coisas abomináveis e rato serão consumidos, diz o SENHOR.

[[v23-66-18]]

^<<v23-66-18,18>>^ Porque conheço as suas obras e os seus pensamentos e venho para ajuntar todas as nações e línguas; elas virão e contemplarão a minha glória.

[[v23-66-19]]

^<<v23-66-19,19>>^ Porei entre elas um sinal e alguns dos que foram salvos enviarei às nações, a Társis, Pul e Lude, que atiram com o arco, a Tubal e Javã, até às terras do mar mais remotas, que jamais ouviram falar de mim, nem viram a minha glória; eles anunciarão entre as nações a minha glória.

[[v23-66-20]]

^<<v23-66-20,20>>^ Trarão todos os vossos irmãos, dentre todas as nações, por oferta ao SENHOR, sobre cavalos, em liteiras e sobre mulas e dromedários, ao meu santo monte, a Jerusalém, diz o SENHOR, como quando os filhos de Israel trazem as suas ofertas de manjares, em vasos puros à Casa do SENHOR.

[[v23-66-21]]

^<<v23-66-21,21>>^ Também deles tomarei a alguns para sacerdotes e para levitas, diz o SENHOR.

[[v23-66-22]]

^<<v23-66-22,22>>^ Porque, como os novos céus e a nova terra, que hei de fazer, estarão diante de mim, diz o SENHOR, assim há de estar a vossa posteridade e o vosso nome.

[[v23-66-23]]

^<<v23-66-23,23>>^ E será que, de uma Festa da Lua Nova à outra e de um sábado a outro, virá toda a carne a adorar perante mim, diz o SENHOR.

[[v23-66-24]]

^<<v23-66-24,24>>^ Eles sairão e verão os cadáveres dos homens que prevaricaram contra mim; porque o seu verme nunca morrerá, nem o seu fogo se apagará; e eles serão um horror para toda a carne.

'''

xref:023-isaias/023-isaias-065.adoc#v23-65-0[&#60; Capítulo Anterior] | <<v23-66-0,Topo>> | xref:024-jeremias/024-jeremias-001.adoc#v24-1-0[Próximo Capítulo &#62;]