include::./index.adoc[]

[[v23-37-0]]
=== Isaías, 37
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-37-1]]

^<<v23-37-1,1>>^ Tendo o rei Ezequias ouvido isto, rasgou as suas vestes, cobriu-se de pano de saco e entrou na Casa do SENHOR.

[[v23-37-2]]

^<<v23-37-2,2>>^ Então, enviou a Eliaquim, o mordomo, a Sebna, o escrivão, e aos anciãos dos sacerdotes, com vestes de pano de saco, ao profeta Isaías, filho de Amoz,

[[v23-37-3]]

^<<v23-37-3,3>>^ os quais lhe dissessem: Assim diz Ezequias: Este dia é dia de angústia, de castigo e de opróbrio; porque filhos são chegados à hora de nascer, e não há força para dá-los à luz.

[[v23-37-4]]

^<<v23-37-4,4>>^ Porventura, o SENHOR, teu Deus, terá ouvido as palavras de Rabsaqué, a quem o rei da Assíria, seu senhor, enviou para afrontar o Deus vivo, e repreenderá as palavras que o SENHOR ouviu; faze, pois, tuas orações pelos que ainda subsistem.

[[v23-37-5]]

^<<v23-37-5,5>>^ Foram, pois, os servos do rei Ezequias ter com Isaías;

[[v23-37-6]]

^<<v23-37-6,6>>^ Isaías lhes disse: Dizei isto a vosso senhor: Assim diz o SENHOR: Não temas por causa das palavras que ouviste, com as quais os servos do rei da Assíria blasfemaram contra mim.

[[v23-37-7]]

^<<v23-37-7,7>>^ Eis que meterei nele um espírito, e ele, ao ouvir certo rumor, voltará para a sua terra; e nela eu o farei cair morto à espada.

[[v23-37-8]]

^<<v23-37-8,8>>^ Voltou, pois, Rabsaqué e encontrou o rei da Assíria pelejando contra Libna; porque ouvira que o rei já se havia retirado de Laquis.

[[v23-37-9]]

^<<v23-37-9,9>>^ O rei ouviu que, a respeito de Tiraca, rei da Etiópia, se dizia: Saiu para guerrear contra ti. Assim que ouviu isto, enviou mensageiros a Ezequias, dizendo:

[[v23-37-10]]

^<<v23-37-10,10>>^ Assim falareis a Ezequias, rei de Judá: Não te engane o teu Deus, em quem confias, dizendo: Jerusalém não será entregue nas mãos do rei da Assíria.

[[v23-37-11]]

^<<v23-37-11,11>>^ Já tens ouvido o que fizeram os reis da Assíria a todas as terras, como as destruíram totalmente; e crês tu que te livrarias?

[[v23-37-12]]

^<<v23-37-12,12>>^ Porventura, os deuses das nações livraram os povos que meus pais destruíram: Gozã, Harã, Rezefe e os filhos de Éden, que estavam em Telassar?

[[v23-37-13]]

^<<v23-37-13,13>>^ Onde está o rei de Hamate, e o rei de Arpade, e o rei da cidade de Sefarvaim, de Hena e de Iva?

[[v23-37-14]]

^<<v23-37-14,14>>^ Tendo Ezequias recebido a carta das mãos dos mensageiros, leu-a; então, subiu à Casa do SENHOR, estendeu-a perante o Senhor

[[v23-37-15]]

^<<v23-37-15,15>>^ e orou ao SENHOR, dizendo:

[[v23-37-16]]

^<<v23-37-16,16>>^ Ó SENHOR dos Exércitos, Deus de Israel, que estás entronizado acima dos querubins, tu somente és o Deus de todos os reinos da terra; tu fizeste os céus e a terra.

[[v23-37-17]]

^<<v23-37-17,17>>^ Inclina, ó SENHOR, os ouvidos e ouve; abre, SENHOR, os olhos e vê; ouve todas as palavras de Senaqueribe, as quais ele enviou para afrontar o Deus vivo.

[[v23-37-18]]

^<<v23-37-18,18>>^ Verdade é, SENHOR, que os reis da Assíria assolaram todos os países e suas terras

[[v23-37-19]]

^<<v23-37-19,19>>^ e lançaram no fogo os deuses deles, porque deuses não eram, senão obra de mãos de homens, madeira e pedra; por isso, os destruíram.

[[v23-37-20]]

^<<v23-37-20,20>>^ Agora, pois, ó SENHOR, nosso Deus, livra-nos das suas mãos, para que todos os reinos da terra saibam que só tu és o SENHOR.

[[v23-37-21]]

^<<v23-37-21,21>>^ Então, Isaías, filho de Amoz, mandou dizer a Ezequias: Assim diz o SENHOR, o Deus de Israel: Visto que me pediste acerca de Senaqueribe, rei da Assíria,

[[v23-37-22]]

^<<v23-37-22,22>>^ esta é a palavra que o SENHOR falou a respeito dele: A virgem, filha de Sião, te despreza e zomba de ti; a filha de Jerusalém meneia a cabeça por detrás de ti.

[[v23-37-23]]

^<<v23-37-23,23>>^ A quem afrontaste e de quem blasfemaste? E contra quem alçaste a voz e arrogantemente ergueste os olhos? Contra o Santo de Israel.

[[v23-37-24]]

^<<v23-37-24,24>>^ Por meio dos teus servos, afrontaste o Senhor e disseste: Com a multidão dos meus carros, subi ao cimo dos montes, ao mais interior do Líbano; deitarei abaixo os seus altos cedros e os ciprestes escolhidos, chegarei ao seu mais alto cimo, ao seu denso e fértil pomar.

[[v23-37-25]]

^<<v23-37-25,25>>^ Cavei e bebi as águas e com a planta de meus pés sequei todos os rios do Egito.

[[v23-37-26]]

^<<v23-37-26,26>>^ Acaso, não ouviste que já há muito dispus eu estas coisas, já desde os dias remotos o tinha planejado? Agora, porém, as faço executar e eu quis que tu reduzisses a montões de ruínas as cidades fortificadas.

[[v23-37-27]]

^<<v23-37-27,27>>^ Por isso, os seus moradores, debilitados, andaram cheios de temor e envergonhados; tornaram-se como a erva do campo, e a erva verde, e o capim dos telhados, e o cereal queimado antes de amadurecer.

[[v23-37-28]]

^<<v23-37-28,28>>^ Mas eu conheço o teu assentar, e o teu sair, e o teu entrar, e o teu furor contra mim.

[[v23-37-29]]

^<<v23-37-29,29>>^ Por causa do teu furor contra mim, e porque a tua arrogância subiu até aos meus ouvidos, eis que porei o meu anzol no teu nariz, e o meu freio, na tua boca, e te farei voltar pelo caminho por onde vieste.

[[v23-37-30]]

^<<v23-37-30,30>>^ Isto te será por sinal: este ano se comerá o que espontaneamente nascer e no segundo ano o que daí proceder; no terceiro ano, porém, semeai e colhei, plantai vinhas e comei os seus frutos.

[[v23-37-31]]

^<<v23-37-31,31>>^ O que escapou da casa de Judá e ficou de resto tornará a lançar raízes para baixo e dará fruto por cima;

[[v23-37-32]]

^<<v23-37-32,32>>^ porque de Jerusalém sairá o restante, e do monte Sião, o que escapou. O zelo do SENHOR dos Exércitos fará isto.

[[v23-37-33]]

^<<v23-37-33,33>>^ Pelo que assim diz o SENHOR acerca do rei da Assíria: Não entrará nesta cidade, nem lançará nela flecha alguma, não virá perante ela com escudo, nem há de levantar tranqueiras contra ela.

[[v23-37-34]]

^<<v23-37-34,34>>^ Pelo caminho por onde vier, por esse voltará; mas nesta cidade não entrará, diz o SENHOR.

[[v23-37-35]]

^<<v23-37-35,35>>^ Porque eu defenderei esta cidade, para a livrar, por amor de mim e por amor do meu servo Davi.

[[v23-37-36]]

^<<v23-37-36,36>>^ Então, saiu o Anjo do SENHOR e feriu no arraial dos assírios a cento e oitenta e cinco mil; e, quando se levantaram os restantes pela manhã, eis que todos estes eram cadáveres.

[[v23-37-37]]

^<<v23-37-37,37>>^ Retirou-se, pois, Senaqueribe, rei da Assíria, e se foi; voltou e ficou em Nínive.

[[v23-37-38]]

^<<v23-37-38,38>>^ Sucedeu que, estando ele a adorar na casa de Nisroque, seu deus, Adrameleque e Sarezer, seus filhos, o feriram à espada e fugiram para a terra de Ararate; e Esar-Hadom, seu filho, reinou em seu lugar.

'''

xref:023-isaias/023-isaias-036.adoc#v23-36-0[&#60; Capítulo Anterior] | <<v23-37-0,Topo>> | xref:023-isaias/023-isaias-038.adoc#v23-38-0[Próximo Capítulo &#62;]