include::./index.adoc[]

[[v23-33-0]]
=== Isaías, 33
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-33-1]]

^<<v23-33-1,1>>^ Ai de ti, destruidor que não foste destruído, que procedes perfidamente e não foste tratado com perfídia! Acabando tu de destruir, serás destruído, acabando de tratar perfidamente, serás tratado com perfídia.

[[v23-33-2]]

^<<v23-33-2,2>>^ SENHOR, tem misericórdia de nós; em ti temos esperado; sê tu o nosso braço manhã após manhã e a nossa salvação no tempo da angústia.

[[v23-33-3]]

^<<v23-33-3,3>>^ Ao ruído do tumulto, fogem os povos; quando tu te ergues, as nações são dispersas.

[[v23-33-4]]

^<<v23-33-4,4>>^ Então, ajuntar-se-á o vosso despojo como se ajuntam as lagartas; como os gafanhotos saltam, assim os homens saltarão sobre ele.

[[v23-33-5]]

^<<v23-33-5,5>>^ O SENHOR é sublime, pois habita nas alturas; encheu a Sião de direito e de justiça.

[[v23-33-6]]

^<<v23-33-6,6>>^ Haverá, ó Sião, estabilidade nos teus tempos, abundância de salvação, sabedoria e conhecimento; o temor do SENHOR será o teu tesouro.

[[v23-33-7]]

^<<v23-33-7,7>>^ Eis que os heróis pranteiam de fora, e os mensageiros de paz estão chorando amargamente.

[[v23-33-8]]

^<<v23-33-8,8>>^ As estradas estão desoladas, cessam os que passam por elas; rompem-se as alianças, as cidades são desprezadas, já não se faz caso do homem.

[[v23-33-9]]

^<<v23-33-9,9>>^ A terra geme e desfalece; o Líbano se envergonha e se murcha; Sarom se torna como um deserto, Basã e Carmelo são despidos de suas folhas.

[[v23-33-10]]

^<<v23-33-10,10>>^ Agora, me levantarei, diz o SENHOR; levantar-me-ei a mim mesmo; agora, serei exaltado.

[[v23-33-11]]

^<<v23-33-11,11>>^ Concebestes palha, dareis à luz restolho; o vosso bufo enfurecido é fogo que vos há de devorar.

[[v23-33-12]]

^<<v23-33-12,12>>^ Os povos serão queimados como se queima a cal; como espinhos cortados, arderão no fogo.

[[v23-33-13]]

^<<v23-33-13,13>>^ Ouvi vós, os que estais longe, o que tenho feito; e vós, os que estais perto, reconhecei o meu poder.

[[v23-33-14]]

^<<v23-33-14,14>>^ Os pecadores em Sião se assombram, o tremor se apodera dos ímpios; e eles perguntam: Quem dentre nós habitará com o fogo devorador? Quem dentre nós habitará com chamas eternas?

[[v23-33-15]]

^<<v23-33-15,15>>^ O que anda em justiça e fala o que é reto; o que despreza o ganho de opressão; o que, com um gesto de mãos, recusa aceitar suborno; o que tapa os ouvidos, para não ouvir falar de homicídios, e fecha os olhos, para não ver o mal,

[[v23-33-16]]

^<<v23-33-16,16>>^ este habitará nas alturas; as fortalezas das rochas serão o seu alto refúgio, o seu pão lhe será dado, as suas águas serão certas.

[[v23-33-17]]

^<<v23-33-17,17>>^ Os teus olhos verão o rei na sua formosura, verão a terra que se estende até longe.

[[v23-33-18]]

^<<v23-33-18,18>>^ O teu coração se recordará dos terrores, dizendo: Onde está aquele que registrou, onde, o que pesou o tributo, onde, o que contou as torres?

[[v23-33-19]]

^<<v23-33-19,19>>^ Já não verás aquele povo atrevido, povo de fala obscura, que não se pode entender, e de língua bárbara, ininteligível.

[[v23-33-20]]

^<<v23-33-20,20>>^ Olha para Sião, a cidade das nossas solenidades; os teus olhos verão a Jerusalém, habitação tranquila, tenda que não será removida, cujas estacas nunca serão arrancadas, nem rebentada nenhuma de suas cordas.

[[v23-33-21]]

^<<v23-33-21,21>>^ Mas o SENHOR ali nos será grandioso, fará as vezes de rios e correntes largas; barco nenhum de remo passará por eles, navio grande por eles não navegará.

[[v23-33-22]]

^<<v23-33-22,22>>^ Porque o SENHOR é o nosso juiz, o SENHOR é o nosso legislador, o SENHOR é o nosso Rei; ele nos salvará.

[[v23-33-23]]

^<<v23-33-23,23>>^ Agora, as tuas enxárcias estão frouxas; não podem ter firme o mastro, nem estender a vela. Então, se repartirá a presa de abundantes despojos; até os coxos participarão dela.

[[v23-33-24]]

^<<v23-33-24,24>>^ Nenhum morador de Jerusalém dirá: Estou doente; porque ao povo que habita nela, perdoar-se-lhe-á a sua iniquidade.

'''

xref:023-isaias/023-isaias-032.adoc#v23-32-0[&#60; Capítulo Anterior] | <<v23-33-0,Topo>> | xref:023-isaias/023-isaias-034.adoc#v23-34-0[Próximo Capítulo &#62;]