include::./index.adoc[]

[[v23-17-0]]
=== Isaías, 17
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-17-1]]

^<<v23-17-1,1>>^ Sentença contra Damasco. Eis que Damasco deixará de ser cidade e será um montão de ruínas.

[[v23-17-2]]

^<<v23-17-2,2>>^ As cidades de Aroer serão abandonadas; hão de ser para os rebanhos, que aí se deitarão sem haver quem os espante.

[[v23-17-3]]

^<<v23-17-3,3>>^ A fortaleza de Efraim desaparecerá, como também o reino de Damasco e o restante da Síria; serão como a glória dos filhos de Israel, diz o SENHOR dos Exércitos.

[[v23-17-4]]

^<<v23-17-4,4>>^ Naquele dia, a glória de Jacó será apoucada, e a gordura da sua carne desaparecerá.

[[v23-17-5]]

^<<v23-17-5,5>>^ Será, quando o segador ajunta a cana do trigo e com o braço sega as espigas, como quem colhe espigas, como quem colhe espigas no vale dos Refains.

[[v23-17-6]]

^<<v23-17-6,6>>^ Mas ainda ficarão alguns rabiscos, como no sacudir da oliveira; duas ou três azeitonas na ponta do ramo mais alto, e quatro ou cinco nos ramos mais exteriores de uma árvore frutífera, diz o SENHOR, Deus de Israel.

[[v23-17-7]]

^<<v23-17-7,7>>^ Naquele dia, olhará o homem para o seu Criador, e os seus olhos atentarão para o Santo de Israel.

[[v23-17-8]]

^<<v23-17-8,8>>^ E não olhará para os altares, obra das suas mãos, nem atentará para o que fizeram seus dedos, nem para os postes-ídolos, nem para os altares do incenso.

[[v23-17-9]]

^<<v23-17-9,9>>^ Naquele dia, serão as suas cidades fortes como os lugares abandonados no bosque ou sobre o cimo das montanhas, os quais outrora foram abandonados ante os filhos de Israel, e haverá assolação;

[[v23-17-10]]

^<<v23-17-10,10>>^ porquanto te esqueceste do Deus da tua salvação e não te lembraste da Rocha da tua fortaleza. Ainda que faças plantações formosas e plantes mudas de fora,

[[v23-17-11]]

^<<v23-17-11,11>>^ e, no dia em que as plantares, as fizeres crescer, e na manhã seguinte as fizeres florescer, ainda assim a colheita voará no dia da tribulação e das dores incuráveis.

[[v23-17-12]]

^<<v23-17-12,12>>^ Ai do bramido dos grandes povos que bramam como bramam os mares, e do rugido das nações que rugem como rugem as impetuosas águas!

[[v23-17-13]]

^<<v23-17-13,13>>^ Rugirão as nações, como rugem as muitas águas, mas Deus as repreenderá, e fugirão para longe; serão afugentadas como a palha dos montes diante do vento e como pó levado pelo tufão.

[[v23-17-14]]

^<<v23-17-14,14>>^ Ao anoitecer, eis que há pavor, e, antes que amanheça o dia, já não existem. Este é o quinhão daqueles que nos despojam e a sorte daqueles que nos saqueiam.

'''

xref:023-isaias/023-isaias-016.adoc#v23-16-0[&#60; Capítulo Anterior] | <<v23-17-0,Topo>> | xref:023-isaias/023-isaias-018.adoc#v23-18-0[Próximo Capítulo &#62;]