include::./index.adoc[]

[[v23-27-0]]
=== Isaías, 27
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-27-1]]

^<<v23-27-1,1>>^ Naquele dia, o SENHOR castigará com a sua dura espada, grande e forte, o dragão, serpente veloz, e o dragão, serpente sinuosa, e matará o monstro que está no mar.

[[v23-27-2]]

^<<v23-27-2,2>>^ Naquele dia, dirá o SENHOR: Cantai a vinha deliciosa!

[[v23-27-3]]

^<<v23-27-3,3>>^ Eu, o SENHOR, a vigio e a cada momento a regarei; para que ninguém lhe faça dano, de noite e de dia eu cuidarei dela.

[[v23-27-4]]

^<<v23-27-4,4>>^ Não há indignação em mim. Quem me dera espinheiros e abrolhos diante de mim! Em guerra, eu iria contra eles e juntamente os queimaria.

[[v23-27-5]]

^<<v23-27-5,5>>^ Ou que homens se apoderem da minha força e façam paz comigo; sim, que façam paz comigo.

[[v23-27-6]]

^<<v23-27-6,6>>^ Dias virão em que Jacó lançará raízes, florescerá e brotará Israel, e encherão de fruto o mundo.

[[v23-27-7]]

^<<v23-27-7,7>>^ Porventura, feriu o SENHOR a Israel como àqueles que o feriram? Ou o matou, assim como àqueles que o mataram?

[[v23-27-8]]

^<<v23-27-8,8>>^ Com xô!, xô! e exílio o trataste; com forte sopro o expulsaste no dia do vento oriental.

[[v23-27-9]]

^<<v23-27-9,9>>^ Portanto, com isto será expiada a culpa de Jacó, e este é todo o fruto do perdão do seu pecado: quando o SENHOR fizer a todas as pedras do altar como pedras de cal feitas em pedaços, não ficarão em pé os postes-ídolos e os altares do incenso.

[[v23-27-10]]

^<<v23-27-10,10>>^ Porque a cidade fortificada está solitária, habitação desamparada e abandonada como um deserto; ali pastam os bezerros, deitam-se e devoram os seus ramos.

[[v23-27-11]]

^<<v23-27-11,11>>^ Quando os seus ramos se secam, são quebrados. Então, vêm as mulheres e lhes deitam fogo, porque este povo não é povo de entendimento; por isso, aquele que o fez não se compadecerá dele, e aquele que o formou não lhe perdoará.

[[v23-27-12]]

^<<v23-27-12,12>>^ Naquele dia, em que o SENHOR debulhará o seu cereal desde o Eufrates até ao ribeiro do Egito; e vós, ó filhos de Israel, sereis colhidos um a um.

[[v23-27-13]]

^<<v23-27-13,13>>^ Naquele dia, se tocará uma grande trombeta, e os que andavam perdidos pela terra da Assíria e os que forem desterrados para a terra do Egito tornarão a vir e adorarão ao SENHOR no monte santo em Jerusalém.

'''

xref:023-isaias/023-isaias-026.adoc#v23-26-0[&#60; Capítulo Anterior] | <<v23-27-0,Topo>> | xref:023-isaias/023-isaias-028.adoc#v23-28-0[Próximo Capítulo &#62;]