include::./index.adoc[]

[[v23-65-0]]
=== Isaías, 65
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-65-1]]

^<<v23-65-1,1>>^ Fui buscado pelos que não perguntavam por mim; fui achado por aqueles que não me buscavam; a um povo que não se chamava do meu nome, eu disse: Eis-me aqui, eis-me aqui.

[[v23-65-2]]

^<<v23-65-2,2>>^ Estendi as mãos todo dia a um povo rebelde, que anda por caminho que não é bom, seguindo os seus próprios pensamentos;

[[v23-65-3]]

^<<v23-65-3,3>>^ povo que de contínuo me irrita abertamente, sacrificando em jardins e queimando incenso sobre altares de tijolos;

[[v23-65-4]]

^<<v23-65-4,4>>^ que mora entre as sepulturas e passa as noites em lugares misteriosos; come carne de porco e tem no seu prato ensopado de carne abominável;

[[v23-65-5]]

^<<v23-65-5,5>>^ povo que diz: Fica onde estás, não te chegues a mim, porque sou mais santo do que tu. És no meu nariz como fumaça de fogo que arde o dia todo.

[[v23-65-6]]

^<<v23-65-6,6>>^ Eis que está escrito diante de mim, e não me calarei; mas eu pagarei, vingar-me-ei, totalmente,

[[v23-65-7]]

^<<v23-65-7,7>>^ das vossas iniquidades e, juntamente, das iniquidades de vossos pais, diz o SENHOR, os quais queimaram incenso nos montes e me afrontaram nos outeiros; pelo que eu vos medirei totalmente a paga devida às suas obras antigas.

[[v23-65-8]]

^<<v23-65-8,8>>^ Assim diz o SENHOR: Como quando se acha vinho num cacho de uvas, dizem: Não o desperdices, pois há bênção nele, assim farei por amor de meus servos e não os destruirei a todos.

[[v23-65-9]]

^<<v23-65-9,9>>^ Farei sair de Jacó descendência e de Judá, um herdeiro que possua os meus montes; e os meus eleitos herdarão a terra e os meus servos habitarão nela.

[[v23-65-10]]

^<<v23-65-10,10>>^ Sarom servirá de campo de pasto de ovelhas, e o vale de Acor, de lugar de repouso de gado, para o meu povo que me buscar.

[[v23-65-11]]

^<<v23-65-11,11>>^ Mas a vós outros, os que vos apartais do SENHOR, os que vos esqueceis do meu santo monte, os que preparais mesa para a deusa Fortuna e misturais vinho para o deus Destino,

[[v23-65-12]]

^<<v23-65-12,12>>^ também vos destinarei à espada, e todos vos encurvareis à matança; porquanto chamei, e não respondestes, falei, e não atendestes; mas fizestes o que é mau perante mim e escolhestes aquilo em que eu não tinha prazer.

[[v23-65-13]]

^<<v23-65-13,13>>^ Pelo que assim diz o SENHOR Deus: Eis que os meus servos comerão, mas vós padecereis fome; os meus servos beberão, mas vós tereis sede; os meus servos se alegrarão, mas vós vos envergonhareis;

[[v23-65-14]]

^<<v23-65-14,14>>^ os meus servos cantarão por terem o coração alegre, mas vós gritareis pela tristeza do vosso coração e uivareis pela angústia de espírito.

[[v23-65-15]]

^<<v23-65-15,15>>^ Deixareis o vosso nome aos meus eleitos por maldição, o SENHOR Deus vos matará e a seus servos chamará por outro nome,

[[v23-65-16]]

^<<v23-65-16,16>>^ de sorte que aquele que se abençoar na terra, pelo Deus da verdade é que se abençoará; e aquele que jurar na terra, pelo Deus da verdade é que jurará; porque já estão esquecidas as angústias passadas e estão escondidas dos meus olhos.

[[v23-65-17]]

^<<v23-65-17,17>>^ Pois eis que eu crio novos céus e nova terra; e não haverá lembrança das coisas passadas, jamais haverá memória delas.

[[v23-65-18]]

^<<v23-65-18,18>>^ Mas vós folgareis e exultareis perpetuamente no que eu crio; porque eis que crio para Jerusalém alegria e para o seu povo, regozijo.

[[v23-65-19]]

^<<v23-65-19,19>>^ E exultarei por causa de Jerusalém e me alegrarei no meu povo, e nunca mais se ouvirá nela nem voz de choro nem de clamor.

[[v23-65-20]]

^<<v23-65-20,20>>^ Não haverá mais nela criança para viver poucos dias, nem velho que não cumpra os seus; porque morrer aos cem anos é morrer ainda jovem, e quem pecar só aos cem anos será amaldiçoado.

[[v23-65-21]]

^<<v23-65-21,21>>^ Eles edificarão casas e nelas habitarão; plantarão vinhas e comerão o seu fruto.

[[v23-65-22]]

^<<v23-65-22,22>>^ Não edificarão para que outros habitem; não plantarão para que outros comam; porque a longevidade do meu povo será como a da árvore, e os meus eleitos desfrutarão de todo as obras das suas próprias mãos.

[[v23-65-23]]

^<<v23-65-23,23>>^ Não trabalharão debalde, nem terão filhos para a calamidade, porque são a posteridade bendita do SENHOR, e os seus filhos estarão com eles.

[[v23-65-24]]

^<<v23-65-24,24>>^ E será que, antes que clamem, eu responderei; estando eles ainda falando, eu os ouvirei.

[[v23-65-25]]

^<<v23-65-25,25>>^ O lobo e o cordeiro pastarão juntos, e o leão comerá palha como o boi; pó será a comida da serpente. Não se fará mal nem dano algum em todo o meu santo monte, diz o SENHOR.

'''

xref:023-isaias/023-isaias-064.adoc#v23-64-0[&#60; Capítulo Anterior] | <<v23-65-0,Topo>> | xref:023-isaias/023-isaias-066.adoc#v23-66-0[Próximo Capítulo &#62;]