include::./index.adoc[]

[[v23-63-0]]
=== Isaías, 63
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-63-1]]

^<<v23-63-1,1>>^ Quem é este que vem de Edom, de Bozra, com vestes de vivas cores, que é glorioso em sua vestidura, que marcha na plenitude da sua força? Sou eu que falo em justiça, poderoso para salvar.

[[v23-63-2]]

^<<v23-63-2,2>>^ Por que está vermelho o traje, e as tuas vestes, como as daquele que pisa uvas no lagar?

[[v23-63-3]]

^<<v23-63-3,3>>^ O lagar, eu o pisei sozinho, e dos povos nenhum homem se achava comigo; pisei as uvas na minha ira; no meu furor, as esmaguei, e o seu sangue me salpicou as vestes e me manchou o traje todo.

[[v23-63-4]]

^<<v23-63-4,4>>^ Porque o dia da vingança me estava no coração, e o ano dos meus redimidos é chegado.

[[v23-63-5]]

^<<v23-63-5,5>>^ Olhei, e não havia quem me ajudasse, e admirei-me de não haver quem me sustivesse; pelo que o meu próprio braço me trouxe a salvação, e o meu furor me susteve.

[[v23-63-6]]

^<<v23-63-6,6>>^ Na minha ira, pisei os povos, no meu furor, embriaguei-os, derramando por terra o seu sangue.

[[v23-63-7]]

^<<v23-63-7,7>>^ Celebrarei as benignidades do SENHOR e os seus atos gloriosos, segundo tudo o que o SENHOR nos concedeu e segundo a grande bondade para com a casa de Israel, bondade que usou para com eles, segundo as suas misericórdias e segundo a multidão das suas benignidades.

[[v23-63-8]]

^<<v23-63-8,8>>^ Porque ele dizia: Certamente, eles são meu povo, filhos que não mentirão; e se lhes tornou o seu Salvador.

[[v23-63-9]]

^<<v23-63-9,9>>^ Em toda a angústia deles, foi ele angustiado, e o Anjo da sua presença os salvou; pelo seu amor e pela sua compaixão, ele os remiu, os tomou e os conduziu todos os dias da antiguidade.

[[v23-63-10]]

^<<v23-63-10,10>>^ Mas eles foram rebeldes e contristaram o seu Espírito Santo, pelo que se lhes tornou em inimigo e ele mesmo pelejou contra eles.

[[v23-63-11]]

^<<v23-63-11,11>>^ Então, o povo se lembrou dos dias antigos, de Moisés, e disse: Onde está aquele que fez subir do mar o pastor do seu rebanho? Onde está o que pôs nele o seu Espírito Santo?

[[v23-63-12]]

^<<v23-63-12,12>>^ Aquele cujo braço glorioso ele fez andar à mão direita de Moisés? Que fendeu as águas diante deles, criando para si um nome eterno?

[[v23-63-13]]

^<<v23-63-13,13>>^ Aquele que os guiou pelos abismos, como o cavalo no deserto, de modo que nunca tropeçaram?

[[v23-63-14]]

^<<v23-63-14,14>>^ Como o animal que desce aos vales, o Espírito do SENHOR lhes deu descanso. Assim, guiaste o teu povo, para te criares um nome glorioso.

[[v23-63-15]]

^<<v23-63-15,15>>^ Atenta do céu e olha da tua santa e gloriosa habitação. Onde estão o teu zelo e as tuas obras poderosas? A ternura do teu coração e as tuas misericórdias se detêm para comigo!

[[v23-63-16]]

^<<v23-63-16,16>>^ Mas tu és nosso Pai, ainda que Abraão não nos conhece, e Israel não nos reconhece; tu, ó SENHOR, és nosso Pai; nosso Redentor é o teu nome desde a antiguidade.

[[v23-63-17]]

^<<v23-63-17,17>>^ Ó SENHOR, por que nos fazes desviar dos teus caminhos? Por que endureces o nosso coração, para que te não temamos? Volta, por amor dos teus servos e das tribos da tua herança.

[[v23-63-18]]

^<<v23-63-18,18>>^ Só por breve tempo foi o país possuído pelo teu santo povo; nossos adversários pisaram o teu santuário.

[[v23-63-19]]

^<<v23-63-19,19>>^ Tornamo-nos como aqueles sobre quem tu nunca dominaste e como os que nunca se chamaram pelo teu nome.

'''

xref:023-isaias/023-isaias-062.adoc#v23-62-0[&#60; Capítulo Anterior] | <<v23-63-0,Topo>> | xref:023-isaias/023-isaias-064.adoc#v23-64-0[Próximo Capítulo &#62;]