include::./index.adoc[]

[[v23-46-0]]
=== Isaías, 46
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-46-1]]

^<<v23-46-1,1>>^ Bel se encurva, Nebo se abaixa; os ídolos são postos sobre os animais, sobre as bestas; as cargas que costumáveis levar são canseira para as bestas já cansadas.

[[v23-46-2]]

^<<v23-46-2,2>>^ Esses deuses juntamente se abaixam e se encurvam, não podem salvar a carga; eles mesmos entram em cativeiro.

[[v23-46-3]]

^<<v23-46-3,3>>^ Ouvi-me, ó casa de Jacó e todo o restante da casa de Israel; vós, a quem desde o nascimento carrego e levo nos braços desde o ventre materno.

[[v23-46-4]]

^<<v23-46-4,4>>^ Até à vossa velhice, eu serei o mesmo e, ainda até às cãs, eu vos carregarei; já o tenho feito; levar-vos-ei, pois, carregar-vos-ei e vos salvarei.

[[v23-46-5]]

^<<v23-46-5,5>>^ A quem me comparareis para que eu lhe seja igual? E que coisa semelhante confrontareis comigo?

[[v23-46-6]]

^<<v23-46-6,6>>^ Os que gastam o ouro da bolsa e pesam a prata nas balanças assalariam o ourives para que faça um deus e diante deste se prostram e se inclinam.

[[v23-46-7]]

^<<v23-46-7,7>>^ Sobre os ombros o tomam, levam-no e o põem no seu lugar, e aí ele fica; do seu lugar não se move; recorrem a ele, mas nenhuma resposta ele dá e a ninguém livra da sua tribulação.

[[v23-46-8]]

^<<v23-46-8,8>>^ Lembrai-vos disto e tende ânimo; tomai-o a sério, ó prevaricadores.

[[v23-46-9]]

^<<v23-46-9,9>>^ Lembrai-vos das coisas passadas da antiguidade: que eu sou Deus, e não há outro, eu sou Deus, e não há outro semelhante a mim;

[[v23-46-10]]

^<<v23-46-10,10>>^ que desde o princípio anuncio o que há de acontecer e desde a antiguidade, as coisas que ainda não sucederam; que digo: o meu conselho permanecerá de pé, farei toda a minha vontade;

[[v23-46-11]]

^<<v23-46-11,11>>^ que chamo a ave de rapina desde o Oriente e de uma terra longínqua, o homem do meu conselho. Eu o disse, eu também o cumprirei; tomei este propósito, também o executarei.

[[v23-46-12]]

^<<v23-46-12,12>>^ Ouvi-me vós, os que sois de obstinado coração, que estais longe da justiça.

[[v23-46-13]]

^<<v23-46-13,13>>^ Faço chegar a minha justiça, e não está longe; a minha salvação não tardará; mas estabelecerei em Sião o livramento e em Israel, a minha glória.

'''

xref:023-isaias/023-isaias-045.adoc#v23-45-0[&#60; Capítulo Anterior] | <<v23-46-0,Topo>> | xref:023-isaias/023-isaias-047.adoc#v23-47-0[Próximo Capítulo &#62;]