include::./index.adoc[]

[[v23-38-0]]
=== Isaías, 38
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-38-1]]

^<<v23-38-1,1>>^ Naqueles dias, Ezequias adoeceu de uma enfermidade mortal; veio ter com ele o profeta Isaías, filho de Amoz, e lhe disse: Assim diz o SENHOR: Põe em ordem a tua casa, porque morrerás e não viverás.

[[v23-38-2]]

^<<v23-38-2,2>>^ Então, virou Ezequias o rosto para a parede e orou ao SENHOR.

[[v23-38-3]]

^<<v23-38-3,3>>^ E disse: Lembra-te, SENHOR, peço-te, de que andei diante de ti com fidelidade, com inteireza de coração e fiz o que era reto aos teus olhos; e chorou muitíssimo.

[[v23-38-4]]

^<<v23-38-4,4>>^ Então, veio a palavra do SENHOR a Isaías, dizendo:

[[v23-38-5]]

^<<v23-38-5,5>>^ Vai e dize a Ezequias: Assim diz o SENHOR, o Deus de Davi, teu pai: Ouvi a tua oração e vi as tuas lágrimas; acrescentarei, pois, aos teus dias quinze anos.

[[v23-38-6]]

^<<v23-38-6,6>>^ Livrar-te-ei das mãos do rei da Assíria, a ti e a esta cidade, e defenderei esta cidade.

[[v23-38-7]]

^<<v23-38-7,7>>^ Ser-te-á isto da parte do SENHOR como sinal de que o SENHOR cumprirá esta palavra que falou:

[[v23-38-8]]

^<<v23-38-8,8>>^ eis que farei retroceder dez graus a sombra lançada pelo sol declinante no relógio de Acaz. Assim, retrocedeu o sol os dez graus que já havia declinado.

[[v23-38-9]]

^<<v23-38-9,9>>^ Cântico de Ezequias, rei de Judá, depois de ter estado doente e se ter restabelecido:

[[v23-38-10]]

^<<v23-38-10,10>>^ Eu disse: Em pleno vigor de meus dias, hei de entrar nas portas do além; roubado estou do resto dos meus anos.

[[v23-38-11]]

^<<v23-38-11,11>>^ Eu disse: já não verei o SENHOR na terra dos viventes; jamais verei homem algum entre os moradores do mundo.

[[v23-38-12]]

^<<v23-38-12,12>>^ A minha habitação foi arrancada e removida para longe de mim, como a tenda de um pastor; tu, como tecelão, me cortarás a vida da urdidura, do dia para a noite darás cabo de mim.

[[v23-38-13]]

^<<v23-38-13,13>>^ Espero com paciência até à madrugada, mas ele, como leão, me quebrou todos os ossos; do dia para a noite darás cabo de mim.

[[v23-38-14]]

^<<v23-38-14,14>>^ Como a andorinha ou o grou, assim eu chilreava e gemia como a pomba; os meus olhos se cansavam de olhar para cima. Ó Senhor, ando oprimido, responde tu por mim.

[[v23-38-15]]

^<<v23-38-15,15>>^ Que direi? Como prometeu, assim me fez; passarei tranquilamente por todos os meus anos, depois desta amargura da minha alma.

[[v23-38-16]]

^<<v23-38-16,16>>^ Senhor, por estas disposições tuas vivem os homens, e inteiramente delas depende o meu espírito; portanto, restaura-me a saúde e faze-me viver.

[[v23-38-17]]

^<<v23-38-17,17>>^ Eis que foi para minha paz que tive eu grande amargura; tu, porém, amaste a minha alma e a livraste da cova da corrupção, porque lançaste para trás de ti todos os meus pecados.

[[v23-38-18]]

^<<v23-38-18,18>>^ A sepultura não te pode louvar, nem a morte glorificar-te; não esperam em tua fidelidade os que descem à cova.

[[v23-38-19]]

^<<v23-38-19,19>>^ Os vivos, somente os vivos, esses te louvam como hoje eu o faço; o pai fará notória aos filhos a tua fidelidade.

[[v23-38-20]]

^<<v23-38-20,20>>^ O SENHOR veio salvar-me; pelo que, tangendo os instrumentos de cordas, nós o louvaremos todos os dias de nossa vida, na Casa do SENHOR.

[[v23-38-21]]

^<<v23-38-21,21>>^ Ora, Isaías dissera: Tome-se uma pasta de figos e ponha-se como emplasto sobre a úlcera; e ele recuperará a saúde.

[[v23-38-22]]

^<<v23-38-22,22>>^ Também dissera Ezequias: Qual será o sinal de que hei de subir à Casa do SENHOR?

'''

xref:023-isaias/023-isaias-037.adoc#v23-37-0[&#60; Capítulo Anterior] | <<v23-38-0,Topo>> | xref:023-isaias/023-isaias-039.adoc#v23-39-0[Próximo Capítulo &#62;]