include::./index.adoc[]

[[v23-22-0]]
=== Isaías, 22
// ara ?, ARA - Almeida Revista e Atualizada

[[v23-22-1]]

^<<v23-22-1,1>>^ Sentença contra o vale da Visão. Que tens agora, que todo o teu povo sobe aos telhados?

[[v23-22-2]]

^<<v23-22-2,2>>^ Tu, cidade que estavas cheia de aclamações, cidade estrepitosa, cidade alegre! Os teus mortos não foram mortos à espada, nem morreram na guerra.

[[v23-22-3]]

^<<v23-22-3,3>>^ Todos os teus príncipes fogem à uma e são presos sem que se use o arco; todos os teus que foram encontrados foram presos, sem embargo de já estarem longe na fuga.

[[v23-22-4]]

^<<v23-22-4,4>>^ Portanto, digo: desviai de mim a vista e chorarei amargamente; não insistais por causa da ruína da filha do meu povo.

[[v23-22-5]]

^<<v23-22-5,5>>^ Porque dia de alvoroço, de atropelamento e confusão é este da parte do Senhor, o SENHOR dos Exércitos, no vale da Visão: um derribar de muros e clamor que vai até aos montes.

[[v23-22-6]]

^<<v23-22-6,6>>^ Porque Elão tomou a aljava e vem com carros e cavaleiros; e Quir descobre os escudos.

[[v23-22-7]]

^<<v23-22-7,7>>^ Os teus mais formosos vales se enchem de carros, e os cavaleiros se põem em ordem às portas.

[[v23-22-8]]

^<<v23-22-8,8>>^ Tira-se a proteção de Judá. Naquele dia, olharás para as armas da Casa do Bosque.

[[v23-22-9]]

^<<v23-22-9,9>>^ Notareis as brechas da Cidade de Davi, por serem muitas, e ajuntareis as águas do açude inferior.

[[v23-22-10]]

^<<v23-22-10,10>>^ Também contareis as casas de Jerusalém e delas derribareis, para fortalecer os muros.

[[v23-22-11]]

^<<v23-22-11,11>>^ Fareis também um reservatório entre os dois muros para as águas do açude velho, mas não cogitais de olhar para cima, para aquele que suscitou essas calamidades, nem considerais naquele que há muito as formou.

[[v23-22-12]]

^<<v23-22-12,12>>^ O Senhor, o SENHOR dos Exércitos, vos convida naquele dia para chorar, prantear, rapar a cabeça e cingir o cilício.

[[v23-22-13]]

^<<v23-22-13,13>>^ Porém é só gozo e alegria que se veem; matam-se bois, degolam-se ovelhas, come-se carne, bebe-se vinho e se diz: Comamos e bebamos, que amanhã morreremos.

[[v23-22-14]]

^<<v23-22-14,14>>^ Mas o SENHOR dos Exércitos se declara aos meus ouvidos, dizendo: Certamente, esta maldade não será perdoada, até que morrais, diz o Senhor, o SENHOR dos Exércitos.

[[v23-22-15]]

^<<v23-22-15,15>>^ Assim diz o Senhor, o SENHOR dos Exércitos: Anda, vai ter com esse administrador, com Sebna, o mordomo, e pergunta-lhe:

[[v23-22-16]]

^<<v23-22-16,16>>^ Que é que tens aqui? Ou a quem tens tu aqui, para que abrisses aqui uma sepultura, lavrando em lugar alto a tua sepultura, cinzelando na rocha a tua própria morada?

[[v23-22-17]]

^<<v23-22-17,17>>^ Eis que como homem forte o SENHOR te arrojará violentamente; agarrar-te-á com firmeza,

[[v23-22-18]]

^<<v23-22-18,18>>^ enrolar-te-á num invólucro e te fará rolar como uma bola para terra espaçosa; ali morrerás, e ali acabarão os carros da tua glória, ó tu, vergonha da casa do teu senhor.

[[v23-22-19]]

^<<v23-22-19,19>>^ Eu te lançarei fora do teu posto, e serás derribado da tua posição.

[[v23-22-20]]

^<<v23-22-20,20>>^ Naquele dia, chamarei a meu servo Eliaquim, filho de Hilquias,

[[v23-22-21]]

^<<v23-22-21,21>>^ vesti-lo-ei da tua túnica, cingi-lo-ei com a tua faixa e lhe entregarei nas mãos o teu poder, e ele será como pai para os moradores de Jerusalém e para a casa de Judá.

[[v23-22-22]]

^<<v23-22-22,22>>^ Porei sobre o seu ombro a chave da casa de Davi; ele abrirá, e ninguém fechará, fechará, e ninguém abrirá.

[[v23-22-23]]

^<<v23-22-23,23>>^ Fincá-lo-ei como estaca em lugar firme, e ele será como um trono de honra para a casa de seu pai.

[[v23-22-24]]

^<<v23-22-24,24>>^ Nele, pendurarão toda a responsabilidade da casa de seu pai, a prole e os descendentes, todos os utensílios menores, desde as taças até as garrafas.

[[v23-22-25]]

^<<v23-22-25,25>>^ Naquele dia, diz o SENHOR dos Exércitos, a estaca que fora fincada em lugar firme será tirada, será arrancada e cairá, e a carga que nela estava se desprenderá, porque o SENHOR o disse.

'''

xref:023-isaias/023-isaias-021.adoc#v23-21-0[&#60; Capítulo Anterior] | <<v23-22-0,Topo>> | xref:023-isaias/023-isaias-023.adoc#v23-23-0[Próximo Capítulo &#62;]