include::./index.adoc[]

[[v24-43-0]]
=== Jeremias, 43
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-43-1]]

^<<v24-43-1,1>>^ Tendo Jeremias acabado de falar a todo o povo todas as palavras do SENHOR, seu Deus, palavras todas com as quais o SENHOR, seu Deus, o enviara,

[[v24-43-2]]

^<<v24-43-2,2>>^ então, falou Azarias, filho de Hosaías, e Joanã, filho de Careá, e todos os homens soberbos, dizendo a Jeremias: É mentira isso que dizes; o SENHOR, nosso Deus, não te enviou a dizer: Não entreis no Egito, para morar.

[[v24-43-3]]

^<<v24-43-3,3>>^ Baruque, filho de Nerias, é que te incita contra nós, para nos entregar nas mãos dos caldeus, a fim de nos matarem ou nos exilarem na Babilônia.

[[v24-43-4]]

^<<v24-43-4,4>>^ Não obedeceu, pois, Joanã, filho de Careá, e nenhum de todos os capitães dos exércitos, nem o povo todo à voz do SENHOR, para ficarem na terra de Judá.

[[v24-43-5]]

^<<v24-43-5,5>>^ Antes, tomaram Joanã, filho de Careá, e todos os capitães dos exércitos a todo o resto de Judá que havia voltado dentre todas as nações para as quais haviam sido lançados, para morar na terra de Judá;

[[v24-43-6]]

^<<v24-43-6,6>>^ tomaram aos homens, às mulheres e aos meninos, às filhas do rei e a todos que Nebuzaradã, o chefe da guarda, deixara com Gedalias, filho de Aicão, filho de Safã; como também a Jeremias, o profeta, e a Baruque, filho de Nerias;

[[v24-43-7]]

^<<v24-43-7,7>>^ e entraram na terra do Egito, porque não obedeceram à voz do SENHOR, e vieram até Tafnes.

[[v24-43-8]]

^<<v24-43-8,8>>^ Então, veio a palavra do SENHOR a Jeremias, em Tafnes, dizendo:

[[v24-43-9]]

^<<v24-43-9,9>>^ Toma contigo pedras grandes, encaixa-as na argamassa do pavimento que está à entrada da casa de Faraó, em Tafnes, à vista de homens judeus,

[[v24-43-10]]

^<<v24-43-10,10>>^ e dize-lhes: Assim diz o SENHOR dos Exércitos, o Deus de Israel: Eis que eu mandarei vir a Nabucodonosor, rei da Babilônia, meu servo, e porei o seu trono sobre estas pedras que encaixei; ele estenderá o seu baldaquino real sobre elas.

[[v24-43-11]]

^<<v24-43-11,11>>^ Virá e ferirá a terra do Egito; quem é para a morte, para a morte; quem é para o cativeiro, para o cativeiro; e quem é para a espada, para a espada.

[[v24-43-12]]

^<<v24-43-12,12>>^ Lançará fogo às casas dos deuses do Egito e as queimará; levará cativos os ídolos e despiolhará a terra do Egito, como o pastor despiolha a sua própria veste; e sairá dali em paz.

[[v24-43-13]]

^<<v24-43-13,13>>^ Quebrará as colunas de Bete-Semes na terra do Egito e queimará as casas dos deuses do Egito.

'''

xref:024-jeremias/024-jeremias-042.adoc#v24-42-0[&#60; Capítulo Anterior] | <<v24-43-0,Topo>> | xref:024-jeremias/024-jeremias-044.adoc#v24-44-0[Próximo Capítulo &#62;]