include::./index.adoc[]

[[v24-18-0]]
=== Jeremias, 18
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-18-1]]

^<<v24-18-1,1>>^ Palavra do SENHOR que veio a Jeremias, dizendo:

[[v24-18-2]]

^<<v24-18-2,2>>^ Dispõe-te, e desce à casa do oleiro, e lá ouvirás as minhas palavras.

[[v24-18-3]]

^<<v24-18-3,3>>^ Desci à casa do oleiro, e eis que ele estava entregue à sua obra sobre as rodas.

[[v24-18-4]]

^<<v24-18-4,4>>^ Como o vaso que o oleiro fazia de barro se lhe estragou na mão, tornou a fazer dele outro vaso, segundo bem lhe pareceu.

[[v24-18-5]]

^<<v24-18-5,5>>^ Então, veio a mim a palavra do SENHOR:

[[v24-18-6]]

^<<v24-18-6,6>>^ Não poderei eu fazer de vós como fez este oleiro, ó casa de Israel? — diz o SENHOR; eis que, como o barro na mão do oleiro, assim sois vós na minha mão, ó casa de Israel.

[[v24-18-7]]

^<<v24-18-7,7>>^ No momento em que eu falar acerca de uma nação ou de um reino para o arrancar, derribar e destruir,

[[v24-18-8]]

^<<v24-18-8,8>>^ se a tal nação se converter da maldade contra a qual eu falei, também eu me arrependerei do mal que pensava fazer-lhe.

[[v24-18-9]]

^<<v24-18-9,9>>^ E, no momento em que eu falar acerca de uma nação ou de um reino, para o edificar e plantar,

[[v24-18-10]]

^<<v24-18-10,10>>^ se ele fizer o que é mau perante mim e não der ouvidos à minha voz, então, me arrependerei do bem que houvera dito lhe faria.

[[v24-18-11]]

^<<v24-18-11,11>>^ Ora, pois, fala agora aos homens de Judá e aos moradores de Jerusalém, dizendo: Assim diz o SENHOR: Eis que estou forjando mal e formo um plano contra vós outros; convertei-vos, pois, agora, cada um do seu mau proceder e emendai os vossos caminhos e as vossas ações.

[[v24-18-12]]

^<<v24-18-12,12>>^ Mas eles dizem: Não há esperança, porque andaremos consoante os nossos projetos, e cada um fará segundo a dureza do seu coração maligno.

[[v24-18-13]]

^<<v24-18-13,13>>^ Portanto, assim diz o SENHOR: Perguntai agora entre os gentios sobre quem ouviu tal coisa. Coisa sobremaneira horrenda cometeu a virgem de Israel!

[[v24-18-14]]

^<<v24-18-14,14>>^ Acaso, a neve deixará o Líbano, a rocha que se ergue na planície? Ou faltarão as águas que vêm de longe, frias e correntes?

[[v24-18-15]]

^<<v24-18-15,15>>^ Contudo, todos os do meu povo se têm esquecido de mim, queimando incenso aos ídolos, que os fizeram tropeçar nos seus caminhos e nas veredas antigas, para que andassem por veredas não aterradas;

[[v24-18-16]]

^<<v24-18-16,16>>^ para fazerem da sua terra um espanto e objeto de perpétuo assobio; todo aquele que passar por ela se espantará e meneará a cabeça.

[[v24-18-17]]

^<<v24-18-17,17>>^ Com vento oriental os espalharei diante do inimigo; mostrar-lhes-ei as costas e não o rosto, no dia da sua calamidade.

[[v24-18-18]]

^<<v24-18-18,18>>^ Então, disseram: Vinde, e forjemos projetos contra Jeremias; porquanto não há de faltar a lei ao sacerdote, nem o conselho ao sábio, nem a palavra ao profeta; vinde, firamo-lo com a língua e não atendamos a nenhuma das suas palavras.

[[v24-18-19]]

^<<v24-18-19,19>>^ Olha para mim, SENHOR, e ouve a voz dos que contendem comigo.

[[v24-18-20]]

^<<v24-18-20,20>>^ Acaso, pagar-se-á mal por bem? Pois abriram uma cova para a minha alma. Lembra-te de que eu compareci à tua presença, para interceder pelo seu bem-estar, para desviar deles a tua indignação.

[[v24-18-21]]

^<<v24-18-21,21>>^ Portanto, entrega seus filhos à fome e ao poder da espada; sejam suas mulheres roubadas dos filhos e fiquem viúvas; seus maridos sejam mortos de peste, e os seus jovens, feridos à espada na peleja.

[[v24-18-22]]

^<<v24-18-22,22>>^ Ouça-se o clamor de suas casas, quando trouxeres bandos sobre eles de repente. Porquanto abriram cova para prender-me e puseram armadilha aos meus pés.

[[v24-18-23]]

^<<v24-18-23,23>>^ Mas tu, ó SENHOR, sabes todo o seu conselho contra mim para matar-me; não lhes perdoes a iniquidade, nem lhes apagues o pecado de diante da tua face; mas sejam derribados diante de ti; age contra eles no tempo da tua ira.

'''

xref:024-jeremias/024-jeremias-017.adoc#v24-17-0[&#60; Capítulo Anterior] | <<v24-18-0,Topo>> | xref:024-jeremias/024-jeremias-019.adoc#v24-19-0[Próximo Capítulo &#62;]