include::./index.adoc[]

[[v24-7-0]]
=== Jeremias, 7
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-7-1]]

^<<v24-7-1,1>>^ Palavra que da parte do SENHOR foi dita a Jeremias:

[[v24-7-2]]

^<<v24-7-2,2>>^ Põe-te à porta da Casa do SENHOR, e proclama ali esta palavra, e dize: Ouvi a palavra do SENHOR, todos de Judá, vós, os que entrais por estas portas, para adorardes ao SENHOR.

[[v24-7-3]]

^<<v24-7-3,3>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel: Emendai os vossos caminhos e as vossas obras, e eu vos farei habitar neste lugar.

[[v24-7-4]]

^<<v24-7-4,4>>^ Não confieis em palavras falsas, dizendo: Templo do SENHOR, templo do SENHOR, templo do SENHOR é este.

[[v24-7-5]]

^<<v24-7-5,5>>^ Mas, se deveras emendardes os vossos caminhos e as vossas obras, se deveras praticardes a justiça, cada um com o seu próximo;

[[v24-7-6]]

^<<v24-7-6,6>>^ se não oprimirdes o estrangeiro, e o órfão, e a viúva, nem derramardes sangue inocente neste lugar, nem andardes após outros deuses para vosso próprio mal,

[[v24-7-7]]

^<<v24-7-7,7>>^ eu vos farei habitar neste lugar, na terra que dei a vossos pais, desde os tempos antigos e para sempre.

[[v24-7-8]]

^<<v24-7-8,8>>^ Eis que vós confiais em palavras falsas, que para nada vos aproveitam.

[[v24-7-9]]

^<<v24-7-9,9>>^ Que é isso? Furtais e matais, cometeis adultério e jurais falsamente, queimais incenso a Baal e andais após outros deuses que não conheceis,

[[v24-7-10]]

^<<v24-7-10,10>>^ e depois vindes, e vos pondes diante de mim nesta casa que se chama pelo meu nome, e dizeis: Estamos salvos; sim, só para continuardes a praticar estas abominações!

[[v24-7-11]]

^<<v24-7-11,11>>^ Será esta casa que se chama pelo meu nome um covil de salteadores aos vossos olhos? Eis que eu, eu mesmo, vi isto, diz o SENHOR.

[[v24-7-12]]

^<<v24-7-12,12>>^ Mas ide agora ao meu lugar que estava em Siló, onde, no princípio, fiz habitar o meu nome, e vede o que lhe fiz, por causa da maldade do meu povo de Israel.

[[v24-7-13]]

^<<v24-7-13,13>>^ Agora, pois, visto que fazeis todas estas obras, diz o SENHOR, e eu vos falei, começando de madrugada, e não me ouvistes, chamei-vos, e não me respondestes,

[[v24-7-14]]

^<<v24-7-14,14>>^ farei também a esta casa que se chama pelo meu nome, na qual confiais, e a este lugar, que vos dei a vós outros e a vossos pais, como fiz a Siló.

[[v24-7-15]]

^<<v24-7-15,15>>^ Lançar-vos-ei da minha presença, como arrojei a todos os vossos irmãos, a toda a posteridade de Efraim.

[[v24-7-16]]

^<<v24-7-16,16>>^ Tu, pois, não intercedas por este povo, nem levantes por ele clamor ou oração, nem me importunes, porque eu não te ouvirei.

[[v24-7-17]]

^<<v24-7-17,17>>^ Acaso, não vês tu o que andam fazendo nas cidades de Judá e nas ruas de Jerusalém?

[[v24-7-18]]

^<<v24-7-18,18>>^ Os filhos apanham a lenha, os pais acendem o fogo, e as mulheres amassam a farinha, para se fazerem bolos à Rainha dos Céus; e oferecem libações a outros deuses, para me provocarem à ira.

[[v24-7-19]]

^<<v24-7-19,19>>^ Acaso, é a mim que eles provocam à ira, diz o SENHOR, e não, antes, a si mesmos, para a sua própria vergonha?

[[v24-7-20]]

^<<v24-7-20,20>>^ Portanto, assim diz o SENHOR Deus: Eis que a minha ira e o meu furor se derramarão sobre este lugar, sobre os homens e sobre os animais, sobre as árvores do campo e sobre os frutos da terra; arderá e não se apagará.

[[v24-7-21]]

^<<v24-7-21,21>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel: Ajuntai os vossos holocaustos aos vossos sacrifícios e comei carne.

[[v24-7-22]]

^<<v24-7-22,22>>^ Porque nada falei a vossos pais, no dia em que os tirei da terra do Egito, nem lhes ordenei coisa alguma acerca de holocaustos ou sacrifícios.

[[v24-7-23]]

^<<v24-7-23,23>>^ Mas isto lhes ordenei, dizendo: Dai ouvidos à minha voz, e eu serei o vosso Deus, e vós sereis o meu povo; andai em todo o caminho que eu vos ordeno, para que vos vá bem.

[[v24-7-24]]

^<<v24-7-24,24>>^ Mas não deram ouvidos, nem atenderam, porém andaram nos seus próprios conselhos e na dureza do seu coração maligno; andaram para trás e não para diante.

[[v24-7-25]]

^<<v24-7-25,25>>^ Desde o dia em que vossos pais saíram da terra do Egito até hoje, enviei-vos todos os meus servos, os profetas, todos os dias; começando de madrugada, eu os enviei.

[[v24-7-26]]

^<<v24-7-26,26>>^ Mas não me destes ouvidos, nem me atendestes; endurecestes a cerviz e fizestes pior do que vossos pais.

[[v24-7-27]]

^<<v24-7-27,27>>^ Dir-lhes-ás, pois, todas estas palavras, mas não te darão ouvidos; chamá-los-ás, mas não te responderão.

[[v24-7-28]]

^<<v24-7-28,28>>^ Dir-lhes-ás: Esta é a nação que não atende à voz do SENHOR, seu Deus, e não aceita a disciplina; já pereceu, a verdade foi eliminada da sua boca.

[[v24-7-29]]

^<<v24-7-29,29>>^ Corta os teus cabelos consagrados, ó Jerusalém, e põe-te a prantear sobre os altos desnudos; porque já o SENHOR rejeitou e desamparou a geração objeto do seu furor;

[[v24-7-30]]

^<<v24-7-30,30>>^ porque os filhos de Judá fizeram o que era mau perante mim, diz o SENHOR; puseram os seus ídolos abomináveis na casa que se chama pelo meu nome, para a contaminarem.

[[v24-7-31]]

^<<v24-7-31,31>>^ Edificaram os altos de Tofete, que está no vale do filho de Hinom, para queimarem a seus filhos e a suas filhas; o que nunca ordenei, nem me passou pela mente.

[[v24-7-32]]

^<<v24-7-32,32>>^ Portanto, eis que virão dias, diz o SENHOR, em que já não se chamará Tofete, nem vale do filho de Hinom, mas o vale da Matança; os mortos serão enterrados em Tofete por não haver outro lugar.

[[v24-7-33]]

^<<v24-7-33,33>>^ Os cadáveres deste povo servirão de pasto às aves dos céus e aos animais da terra; e ninguém haverá que os espante.

[[v24-7-34]]

^<<v24-7-34,34>>^ Farei cessar nas cidades de Judá e nas ruas de Jerusalém a voz de folguedo e a de alegria, a voz de noivo e a de noiva; porque a terra se tornará em desolação.

'''

xref:024-jeremias/024-jeremias-006.adoc#v24-6-0[&#60; Capítulo Anterior] | <<v24-7-0,Topo>> | xref:024-jeremias/024-jeremias-008.adoc#v24-8-0[Próximo Capítulo &#62;]