include::./index.adoc[]

[[v24-6-0]]
=== Jeremias, 6
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-6-1]]

^<<v24-6-1,1>>^ Fugi, filhos de Benjamim, do meio de Jerusalém; tocai a trombeta em Tecoa e levantai o facho sobre Bete-Haquerém, porque do lado do Norte surge um grande mal, uma grande calamidade.

[[v24-6-2]]

^<<v24-6-2,2>>^ A formosa e delicada, a filha de Sião, eu deixarei em ruínas.

[[v24-6-3]]

^<<v24-6-3,3>>^ Contra ela virão pastores com os seus rebanhos; levantarão suas tendas em redor, e cada um apascentará no seu devido lugar.

[[v24-6-4]]

^<<v24-6-4,4>>^ Preparai a guerra contra ela, disponde-vos, e subamos ao meio-dia. Ai de nós, que já declina o dia, já se vão estendendo as sombras da tarde!

[[v24-6-5]]

^<<v24-6-5,5>>^ Disponde-vos, e subamos de noite e destruamos os seus castelos.

[[v24-6-6]]

^<<v24-6-6,6>>^ Porque assim diz o SENHOR dos Exércitos: Cortai árvores e levantai tranqueiras contra Jerusalém. Esta é a cidade que há de ser punida; só opressão há no meio dela.

[[v24-6-7]]

^<<v24-6-7,7>>^ Como o poço conserva frescas as suas águas, assim ela, a sua malícia; violência e estrago se ouvem nela; enfermidade e feridas há diante de mim continuamente.

[[v24-6-8]]

^<<v24-6-8,8>>^ Aceita a disciplina, ó Jerusalém, para que eu não me aparte de ti; para que eu não te torne em assolação e terra não habitada.

[[v24-6-9]]

^<<v24-6-9,9>>^ Assim diz o SENHOR dos Exércitos: Diligentemente se rebuscarão os resíduos de Israel como uma vinha; vai metendo a mão, como o vindimador, por entre os sarmentos.

[[v24-6-10]]

^<<v24-6-10,10>>^ A quem falarei e testemunharei, para que ouçam? Eis que os seus ouvidos estão incircuncisos e não podem ouvir; eis que a palavra do SENHOR é para eles coisa vergonhosa; não gostam dela.

[[v24-6-11]]

^<<v24-6-11,11>>^ Pelo que estou cheio da ira do SENHOR; estou cansado de a conter. Derramá-la-ei sobre as crianças pelas ruas e nas reuniões de todos os jovens; porque até o marido com a mulher serão presos, e o velho, com o decrépito.

[[v24-6-12]]

^<<v24-6-12,12>>^ As suas casas passarão a outrem, os campos e também as mulheres, porque estenderei a mão contra os habitantes desta terra, diz o SENHOR,

[[v24-6-13]]

^<<v24-6-13,13>>^ porque desde o menor deles até ao maior, cada um se dá à ganância, e tanto o profeta como o sacerdote usam de falsidade.

[[v24-6-14]]

^<<v24-6-14,14>>^ Curam superficialmente a ferida do meu povo, dizendo: Paz, paz; quando não há paz.

[[v24-6-15]]

^<<v24-6-15,15>>^ Serão envergonhados, porque cometem abominação sem sentir por isso vergonha; nem sabem que coisa é envergonhar-se. Portanto, cairão com os que caem; quando eu os castigar, tropeçarão, diz o SENHOR.

[[v24-6-16]]

^<<v24-6-16,16>>^ Assim diz o SENHOR: Ponde-vos à margem no caminho e vede, perguntai pelas veredas antigas, qual é o bom caminho; andai por ele e achareis descanso para a vossa alma; mas eles dizem: Não andaremos.

[[v24-6-17]]

^<<v24-6-17,17>>^ Também pus atalaias sobre vós, dizendo: Estai atentos ao som da trombeta; mas eles dizem: Não escutaremos.

[[v24-6-18]]

^<<v24-6-18,18>>^ Portanto, ouvi, ó nações, e informa-te, ó congregação, do que se fará entre eles!

[[v24-6-19]]

^<<v24-6-19,19>>^ Ouve tu, ó terra! Eis que eu trarei mal sobre este povo, o próprio fruto dos seus pensamentos; porque não estão atentos às minhas palavras e rejeitam a minha lei.

[[v24-6-20]]

^<<v24-6-20,20>>^ Para que, pois, me vem o incenso de Sabá e a melhor cana aromática de terras longínquas? Os vossos holocaustos não me são aprazíveis, e os vossos sacrifícios não me agradam.

[[v24-6-21]]

^<<v24-6-21,21>>^ Portanto, assim diz o SENHOR: Eis que ponho tropeços a este povo; neles cairão pais e filhos juntamente; o vizinho e o seu companheiro perecerão.

[[v24-6-22]]

^<<v24-6-22,22>>^ Assim diz o SENHOR: Eis que um povo vem da terra do Norte, e uma grande nação se levanta dos confins da terra.

[[v24-6-23]]

^<<v24-6-23,23>>^ Trazem arco e dardo; eles são cruéis e não usam de misericórdia; a sua voz ruge como o mar, e em cavalos vêm montados, como guerreiros em ordem de batalha contra ti, ó filha de Sião.

[[v24-6-24]]

^<<v24-6-24,24>>^ Ao ouvirmos a sua fama, afrouxam-se as nossas mãos, angústia nos toma e dores como de parturiente.

[[v24-6-25]]

^<<v24-6-25,25>>^ Não saias ao campo, nem andes pelo caminho, porque o inimigo tem espada, e há terror por todos os lados.

[[v24-6-26]]

^<<v24-6-26,26>>^ Ó filha do meu povo, cinge-te de cilício e revolve-te na cinza; pranteia como por filho único, pranto de amarguras; porque, de súbito, virá o destruidor sobre nós.

[[v24-6-27]]

^<<v24-6-27,27>>^ Qual acrisolador te estabeleci entre o meu povo, qual fortaleza, para que venhas a conhecer o seu caminho e o examines.

[[v24-6-28]]

^<<v24-6-28,28>>^ Todos eles são os mais rebeldes e andam espalhando calúnias; são bronze e ferro, são todos corruptores.

[[v24-6-29]]

^<<v24-6-29,29>>^ O fole bufa, só chumbo resulta do seu fogo; em vão continua o depurador, porque os iníquos não são separados.

[[v24-6-30]]

^<<v24-6-30,30>>^ Prata de refugo lhes chamarão, porque o SENHOR os refugou.

'''

xref:024-jeremias/024-jeremias-005.adoc#v24-5-0[&#60; Capítulo Anterior] | <<v24-6-0,Topo>> | xref:024-jeremias/024-jeremias-007.adoc#v24-7-0[Próximo Capítulo &#62;]