include::./index.adoc[]

[[v24-52-0]]
=== Jeremias, 52
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-52-1]]

^<<v24-52-1,1>>^ Tinha Zedequias a idade de vinte e um anos, quando começou a reinar e reinou onze anos em Jerusalém. Sua mãe se chamava Hamutal e era filha de Jeremias, de Libna.

[[v24-52-2]]

^<<v24-52-2,2>>^ Fez ele o que era mau perante o SENHOR, conforme tudo quanto fizera Jeoaquim.

[[v24-52-3]]

^<<v24-52-3,3>>^ Assim sucedeu por causa da ira do SENHOR contra Jerusalém e contra Judá, a ponto de os rejeitar de sua presença; Zedequias rebelou-se contra o rei da Babilônia.

[[v24-52-4]]

^<<v24-52-4,4>>^ Sucedeu que, em o nono ano do reinado de Zedequias, aos dez dias do décimo mês, Nabucodonosor, rei da Babilônia, veio contra Jerusalém, ele e todo o seu exército, e se acamparam contra ela, e levantaram contra ela tranqueiras em redor.

[[v24-52-5]]

^<<v24-52-5,5>>^ A cidade ficou sitiada até ao undécimo ano do rei Zedequias.

[[v24-52-6]]

^<<v24-52-6,6>>^ Aos nove dias do quarto mês, quando a cidade se via apertada da fome, e não havia pão para o povo da terra,

[[v24-52-7]]

^<<v24-52-7,7>>^ então, a cidade foi arrombada, e todos os homens de guerra fugiram e saíram de noite pelo caminho da porta que está entre os dois muros perto do jardim do rei, a despeito de os caldeus se acharem contra a cidade em redor; e se foram pelo caminho da campina.

[[v24-52-8]]

^<<v24-52-8,8>>^ Porém o exército dos caldeus perseguiu o rei Zedequias e o alcançou nas campinas de Jericó; e todo o exército deste se dispersou e o abandonou.

[[v24-52-9]]

^<<v24-52-9,9>>^ Então, o tomaram preso e o fizeram subir ao rei da Babilônia, a Ribla, na terra de Hamate, e este lhe pronunciou a sentença.

[[v24-52-10]]

^<<v24-52-10,10>>^ Matou o rei da Babilônia os filhos de Zedequias à sua própria vista, bem assim todos os príncipes de Judá, em Ribla.

[[v24-52-11]]

^<<v24-52-11,11>>^ Vazou os olhos de Zedequias, atou-o com duas cadeias de bronze, levou-o à Babilônia e o conservou no cárcere até ao dia da sua morte.

[[v24-52-12]]

^<<v24-52-12,12>>^ No décimo dia do quinto mês, do ano décimo nono de Nabucodonosor, rei da Babilônia, Nebuzaradã, o chefe da guarda e servidor do rei da Babilônia, veio a Jerusalém.

[[v24-52-13]]

^<<v24-52-13,13>>^ E queimou a Casa do SENHOR e a casa do rei, como também todas as casas de Jerusalém; também entregou às chamas todos os edifícios importantes.

[[v24-52-14]]

^<<v24-52-14,14>>^ Todo o exército dos caldeus que estava com o chefe da guarda derribou todos os muros em redor de Jerusalém.

[[v24-52-15]]

^<<v24-52-15,15>>^ Dos mais pobres do povo, o mais do povo que havia ficado na cidade, os desertores que se entregaram ao rei da Babilônia e o mais da multidão Nebuzaradã, o chefe da guarda, levou cativos.

[[v24-52-16]]

^<<v24-52-16,16>>^ Porém dos mais pobres da terra deixou Nebuzaradã, o chefe da guarda, ficar alguns para vinheiros e para lavradores.

[[v24-52-17]]

^<<v24-52-17,17>>^ Os caldeus cortaram em pedaços as colunas de bronze que estavam na Casa do SENHOR, como também os suportes e o mar de bronze que estavam na Casa do SENHOR; e levaram todo o bronze para a Babilônia.

[[v24-52-18]]

^<<v24-52-18,18>>^ Levaram também as panelas, as pás, as espevitadeiras, as bacias, os recipientes de incenso e todos os utensílios de bronze, com que se ministrava.

[[v24-52-19]]

^<<v24-52-19,19>>^ Tomou também o chefe da guarda os copos, os braseiros, as bacias, as panelas, os candeeiros, os recipientes de incenso e as taças, tudo quanto fosse de ouro ou de prata.

[[v24-52-20]]

^<<v24-52-20,20>>^ Quanto às duas colunas, ao mar e aos suportes que Salomão fizera para a Casa do SENHOR, o peso do bronze de todos estes utensílios era incalculável.

[[v24-52-21]]

^<<v24-52-21,21>>^ Quanto às colunas, a altura de uma era de dezoito côvados, um cordão de doze côvados a cercava, e a grossura era de quatro dedos; era oca.

[[v24-52-22]]

^<<v24-52-22,22>>^ Sobre ela havia um capitel de bronze; a altura de cada um era de cinco côvados; a obra de rede e as romãs sobre o capitel ao redor eram de bronze.

[[v24-52-23]]

^<<v24-52-23,23>>^ Semelhante a esta era a outra coluna com as romãs. Havia noventa e seis romãs aos lados; as romãs todas sobre a obra de rede ao redor eram cem.

[[v24-52-24]]

^<<v24-52-24,24>>^ Levou também o chefe da guarda a Seraías, sumo sacerdote, e a Sofonias, segundo sacerdote, e aos três guardas da porta.

[[v24-52-25]]

^<<v24-52-25,25>>^ Da cidade tomou a um oficial, que era comandante das tropas de guerra, e a sete homens dos que eram conselheiros pessoais do rei e se achavam na cidade, como também ao escrivão-mor do exército, que alistava o povo da terra, e a sessenta homens do povo do lugar, que se achavam na cidade.

[[v24-52-26]]

^<<v24-52-26,26>>^ Tomando-os Nebuzaradã, o chefe da guarda, levou-os ao rei da Babilônia, a Ribla.

[[v24-52-27]]

^<<v24-52-27,27>>^ O rei da Babilônia os feriu e os matou em Ribla, na terra de Hamate.

[[v24-52-28]]

^<<v24-52-28,28>>^ Assim, Judá foi levado cativo para fora de sua terra. Este é o povo que Nabucodonosor levou para o exílio: no sétimo ano, três mil e vinte e três judeus;

[[v24-52-29]]

^<<v24-52-29,29>>^ no ano décimo oitavo de Nabucodonosor, levou ele cativas de Jerusalém oitocentas e trinta e duas pessoas;

[[v24-52-30]]

^<<v24-52-30,30>>^ no ano vigésimo terceiro de Nabucodonosor, Nebuzaradã, o chefe da guarda, levou cativas, dentre os judeus, setecentas e quarenta e cinco pessoas; todas as pessoas são quatro mil e seiscentas.

[[v24-52-31]]

^<<v24-52-31,31>>^ No trigésimo sétimo ano do cativeiro de Joaquim, rei de Judá, no dia vinte e cinco do duodécimo mês, Evil-Merodaque, rei da Babilônia, no ano em que começou a reinar, libertou a Joaquim, rei de Judá, e o fez sair do cárcere.

[[v24-52-32]]

^<<v24-52-32,32>>^ Falou com ele benignamente e lhe deu lugar de mais honra do que o dos reis que estavam consigo em Babilônia.

[[v24-52-33]]

^<<v24-52-33,33>>^ Mudou-lhe as vestes do cárcere, e Joaquim passou a comer pão na sua presença, todos os dias da sua vida.

[[v24-52-34]]

^<<v24-52-34,34>>^ E da parte do rei da Babilônia lhe foi dada subsistência vitalícia, uma pensão diária, até ao dia da sua morte, durante os dias da sua vida.

'''

xref:024-jeremias/024-jeremias-051.adoc#v24-51-0[&#60; Capítulo Anterior] | <<v24-52-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-001.adoc#v25-1-0[Próximo Capítulo &#62;]