include::./index.adoc[]

[[v24-2-0]]
=== Jeremias, 2
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-2-1]]

^<<v24-2-1,1>>^ A mim me veio a palavra do SENHOR, dizendo:

[[v24-2-2]]

^<<v24-2-2,2>>^ Vai e clama aos ouvidos de Jerusalém: Assim diz o SENHOR: Lembro-me de ti, da tua afeição quando eras jovem, e do teu amor quando noiva, e de como me seguias no deserto, numa terra em que se não semeia.

[[v24-2-3]]

^<<v24-2-3,3>>^ Então, Israel era consagrado ao SENHOR e era as primícias da sua colheita; todos os que o devoraram se faziam culpados; o mal vinha sobre eles, diz o SENHOR.

[[v24-2-4]]

^<<v24-2-4,4>>^ Ouvi a palavra do SENHOR, ó casa de Jacó e todas as famílias da casa de Israel.

[[v24-2-5]]

^<<v24-2-5,5>>^ Assim diz o SENHOR: Que injustiça acharam vossos pais em mim, para de mim se afastarem, indo após a nulidade dos ídolos e se tornando nulos eles mesmos,

[[v24-2-6]]

^<<v24-2-6,6>>^ e sem perguntarem: Onde está o SENHOR, que nos fez subir da terra do Egito? Que nos guiou através do deserto, por uma terra de ermos e de covas, por uma terra de sequidão e sombra de morte, por uma terra em que ninguém transitava e na qual não morava homem algum?

[[v24-2-7]]

^<<v24-2-7,7>>^ Eu vos introduzi numa terra fértil, para que comêsseis o seu fruto e o seu bem; mas, depois de terdes entrado nela, vós a contaminastes e da minha herança fizestes abominação.

[[v24-2-8]]

^<<v24-2-8,8>>^ Os sacerdotes não disseram: Onde está o SENHOR? E os que tratavam da lei não me conheceram, os pastores prevaricaram contra mim, os profetas profetizaram por Baal e andaram atrás de coisas de nenhum proveito.

[[v24-2-9]]

^<<v24-2-9,9>>^ Portanto, ainda pleitearei convosco, diz o SENHOR, e até com os filhos de vossos filhos pleitearei.

[[v24-2-10]]

^<<v24-2-10,10>>^ Passai às terras do mar de Chipre e vede; mandai mensageiros a Quedar, e atentai bem, e vede se jamais sucedeu coisa semelhante.

[[v24-2-11]]

^<<v24-2-11,11>>^ Houve alguma nação que trocasse os seus deuses, posto que não eram deuses? Todavia, o meu povo trocou a sua Glória por aquilo que é de nenhum proveito.

[[v24-2-12]]

^<<v24-2-12,12>>^ Espantai-vos disto, ó céus, e horrorizai-vos! Ficai estupefatos, diz o SENHOR.

[[v24-2-13]]

^<<v24-2-13,13>>^ Porque dois males cometeu o meu povo: a mim me deixaram, o manancial de águas vivas, e cavaram cisternas, cisternas rotas, que não retêm as águas.

[[v24-2-14]]

^<<v24-2-14,14>>^ Acaso, é Israel escravo ou servo nascido em casa? Por que, pois, veio a ser presa?

[[v24-2-15]]

^<<v24-2-15,15>>^ Os leões novos rugiram contra ele, levantaram a voz; da terra dele fizeram uma desolação; as suas cidades estão queimadas, e não há quem nelas habite.

[[v24-2-16]]

^<<v24-2-16,16>>^ Até os filhos de Mênfis e de Tafnes te pastaram o alto da cabeça.

[[v24-2-17]]

^<<v24-2-17,17>>^ Acaso, tudo isto não te sucedeu por haveres deixado o SENHOR, teu Deus, quando te guiava pelo caminho?

[[v24-2-18]]

^<<v24-2-18,18>>^ Agora, pois, que lucro terás indo ao Egito para beberes as águas do Nilo; ou indo à Assíria para beberes as águas do Eufrates?

[[v24-2-19]]

^<<v24-2-19,19>>^ A tua malícia te castigará, e as tuas infidelidades te repreenderão; sabe, pois, e vê que mau e quão amargo é deixares o SENHOR, teu Deus, e não teres temor de mim, diz o Senhor, o SENHOR dos Exércitos.

[[v24-2-20]]

^<<v24-2-20,20>>^ Ainda que há muito quebrava eu o teu jugo e rompia as tuas ataduras, dizias tu: Não quero servir-te. Pois, em todo outeiro alto e debaixo de toda árvore frondosa, te deitavas e te prostituías.

[[v24-2-21]]

^<<v24-2-21,21>>^ Eu mesmo te plantei como vide excelente, da semente mais pura; como, pois, te tornaste para mim uma planta degenerada, como de vide brava?

[[v24-2-22]]

^<<v24-2-22,22>>^ Pelo que ainda que te laves com salitre e amontoes potassa, continua a mácula da tua iniquidade perante mim, diz o SENHOR Deus.

[[v24-2-23]]

^<<v24-2-23,23>>^ Como podes dizer: Não estou maculada, não andei após os baalins? Vê o teu rasto no vale, reconhece o que fizeste, dromedária nova de ligeiros pés, que andas ziguezagueando pelo caminho;

[[v24-2-24]]

^<<v24-2-24,24>>^ jumenta selvagem, acostumada ao deserto e que, no ardor do cio, sorve o vento. Quem a impediria de satisfazer ao seu desejo? Os que a procuram não têm de fatigar-se; no mês dela a acharão.

[[v24-2-25]]

^<<v24-2-25,25>>^ Guarda-te de que os teus pés andem desnudos e a tua garganta tenha sede. Mas tu dizes: Não, é inútil; porque amo os estranhos e após eles irei.

[[v24-2-26]]

^<<v24-2-26,26>>^ Como se envergonha o ladrão quando o apanham, assim se envergonham os da casa de Israel; eles, os seus reis, os seus príncipes, os seus sacerdotes e os seus profetas,

[[v24-2-27]]

^<<v24-2-27,27>>^ que dizem a um pedaço de madeira: Tu és meu pai; e à pedra: Tu me geraste. Pois me viraram as costas e não o rosto; mas, em vindo a angústia, dizem: Levanta-te e livra-nos.

[[v24-2-28]]

^<<v24-2-28,28>>^ Onde, pois, estão os teus deuses, que para ti mesmo fizeste? Eles que se levantem se te podem livrar no tempo da tua angústia; porque os teus deuses, ó Judá, são tantos como as tuas cidades.

[[v24-2-29]]

^<<v24-2-29,29>>^ Por que contendeis comigo? Todos vós transgredistes contra mim, diz o SENHOR.

[[v24-2-30]]

^<<v24-2-30,30>>^ Em vão castiguei os vossos filhos; eles não aceitaram a minha disciplina; a vossa espada devorou os vossos profetas como leão destruidor.

[[v24-2-31]]

^<<v24-2-31,31>>^ Oh! Que geração! Considerai vós a palavra do SENHOR. Porventura, tenho eu sido para Israel um deserto? Ou uma terra da mais espessa escuridão? Por que, pois, diz o meu povo: Somos livres! Jamais tornaremos a ti?

[[v24-2-32]]

^<<v24-2-32,32>>^ Acaso, se esquece a virgem dos seus adornos ou a noiva do seu cinto? Todavia, o meu povo se esqueceu de mim por dias sem conta.

[[v24-2-33]]

^<<v24-2-33,33>>^ Como dispões bem os teus caminhos, para buscares o amor! Pois até às mulheres perdidas os ensinaste.

[[v24-2-34]]

^<<v24-2-34,34>>^ Nas orlas dos teus vestidos se achou também o sangue de pobres e inocentes, não surpreendidos no ato de roubar. Apesar de todas estas coisas,

[[v24-2-35]]

^<<v24-2-35,35>>^ ainda dizes: Estou inocente; certamente, a sua ira se desviou de mim. Eis que entrarei em juízo contigo, porquanto dizes: Não pequei.

[[v24-2-36]]

^<<v24-2-36,36>>^ Que mudar leviano é esse dos teus caminhos? Também do Egito serás envergonhada, como foste envergonhada da Assíria.

[[v24-2-37]]

^<<v24-2-37,37>>^ Também daquele sairás de mãos na cabeça; porque o SENHOR rejeitou aqueles em quem confiaste, e não terás sorte por meio deles.

'''

xref:024-jeremias/024-jeremias-001.adoc#v24-1-0[&#60; Capítulo Anterior] | <<v24-2-0,Topo>> | xref:024-jeremias/024-jeremias-003.adoc#v24-3-0[Próximo Capítulo &#62;]