include::./index.adoc[]

[[v24-39-0]]
=== Jeremias, 39
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-39-1]]

^<<v24-39-1,1>>^ Foi tomada Jerusalém. Era o ano nono de Zedequias, rei de Judá, no mês décimo, quando veio Nabucodonosor, rei da Babilônia, e todo o seu exército, contra Jerusalém, e a cercaram;

[[v24-39-2]]

^<<v24-39-2,2>>^ era o undécimo ano de Zedequias, no quarto mês, aos nove do mês, quando se fez uma brecha na cidade.

[[v24-39-3]]

^<<v24-39-3,3>>^ Então, entraram todos os príncipes do rei da Babilônia e se assentaram na Porta do Meio: Nergal-Sarezer, Sangar-Nebo, Sarsequim, Rabe-Saris, Nergal-Sarezer, Rabe-Mague e todos os outros príncipes do rei da Babilônia.

[[v24-39-4]]

^<<v24-39-4,4>>^ Tendo-os visto Zedequias, rei de Judá, e todos os homens de guerra, fugiram e, de noite, saíram da cidade, pelo caminho do jardim do rei, pela porta que está entre os dois muros; Zedequias saiu pelo caminho da campina.

[[v24-39-5]]

^<<v24-39-5,5>>^ Mas o exército dos caldeus os perseguiu e alcançou a Zedequias nas campinas de Jericó; eles o prenderam e o fizeram subir a Ribla, na terra de Hamate, a Nabucodonosor, rei da Babilônia, que lhe pronunciou a sentença.

[[v24-39-6]]

^<<v24-39-6,6>>^ O rei da Babilônia mandou matar, em Ribla, os filhos de Zedequias à vista deste; também matou a todos os príncipes de Judá.

[[v24-39-7]]

^<<v24-39-7,7>>^ Vazou os olhos a Zedequias e o atou com duas cadeias de bronze, para o levar à Babilônia.

[[v24-39-8]]

^<<v24-39-8,8>>^ Os caldeus queimaram a casa do rei e as casas do povo e derribaram os muros de Jerusalém.

[[v24-39-9]]

^<<v24-39-9,9>>^ O mais do povo que havia ficado na cidade, os desertores que se entregaram a ele e o sobrevivente do povo, Nebuzaradã, o chefe da guarda, levou-os cativos para a Babilônia.

[[v24-39-10]]

^<<v24-39-10,10>>^ Porém dos mais pobres da terra, que nada tinham, deixou Nebuzaradã, o chefe da guarda, na terra de Judá; e lhes deu vinhas e campos naquele dia.

[[v24-39-11]]

^<<v24-39-11,11>>^ Mas Nabucodonosor, rei da Babilônia, havia ordenado acerca de Jeremias, a Nebuzaradã, o chefe da guarda, dizendo:

[[v24-39-12]]

^<<v24-39-12,12>>^ Toma-o, cuida dele e não lhe faças nenhum mal; mas faze-lhe como ele te disser.

[[v24-39-13]]

^<<v24-39-13,13>>^ Deste modo, Nebuzaradã, o chefe da guarda, ordenou a Nebusazbã, Rabe-Saris, Nergal-Sarezer, Rabe-Mague, e todos os príncipes do rei da Babilônia

[[v24-39-14]]

^<<v24-39-14,14>>^ mandaram retirar Jeremias do átrio da guarda e o entregaram a Gedalias, filho de Aicão, filho de Safã, para que o levasse para o seu palácio; assim, habitou entre o povo.

[[v24-39-15]]

^<<v24-39-15,15>>^ Ora, tinha vindo a Jeremias a palavra do SENHOR, estando ele ainda detido no átrio da guarda, dizendo:

[[v24-39-16]]

^<<v24-39-16,16>>^ Vai e fala a Ebede-Meleque, o etíope, dizendo: Assim diz o SENHOR dos Exércitos, o Deus de Israel: Eis que eu trarei as minhas palavras sobre esta cidade para mal e não para bem; e se cumprirão diante de ti naquele dia.

[[v24-39-17]]

^<<v24-39-17,17>>^ A ti, porém, eu livrarei naquele dia, diz o SENHOR, e não serás entregue nas mãos dos homens a quem temes.

[[v24-39-18]]

^<<v24-39-18,18>>^ Pois certamente te salvarei, e não cairás à espada, porque a tua vida te será como despojo, porquanto confiaste em mim.

'''

xref:024-jeremias/024-jeremias-038.adoc#v24-38-0[&#60; Capítulo Anterior] | <<v24-39-0,Topo>> | xref:024-jeremias/024-jeremias-040.adoc#v24-40-0[Próximo Capítulo &#62;]