include::./index.adoc[]

[[v24-46-0]]
=== Jeremias, 46
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-46-1]]

^<<v24-46-1,1>>^ Palavra do SENHOR que veio a Jeremias, o profeta, contra as nações.

[[v24-46-2]]

^<<v24-46-2,2>>^ A respeito do Egito. Contra o exército de Faraó-Neco, rei do Egito, exército que estava junto ao rio Eufrates em Carquemis; ao qual feriu Nabucodonosor, rei da Babilônia, no ano quarto de Jeoaquim, filho de Josias, rei de Judá:

[[v24-46-3]]

^<<v24-46-3,3>>^ Preparai o escudo e o pavês e chegai-vos para a peleja.

[[v24-46-4]]

^<<v24-46-4,4>>^ Selai os cavalos, montai, cavaleiros, e apresentai-vos com elmos; poli as lanças, vesti-vos de couraças.

[[v24-46-5]]

^<<v24-46-5,5>>^ Por que razão vejo os medrosos voltando as costas? Estão derrotados os seus valentes e vão fugindo, sem olhar para trás; há terror ao redor, diz o SENHOR.

[[v24-46-6]]

^<<v24-46-6,6>>^ Não fuja o ligeiro, nem escape o valente; para o lado do Norte, junto à borda do rio Eufrates, tropeçaram e caíram.

[[v24-46-7]]

^<<v24-46-7,7>>^ Quem é este que vem subindo como o Nilo, como rios cujas águas se agitam?

[[v24-46-8]]

^<<v24-46-8,8>>^ O Egito vem subindo como o Nilo, como rios cujas águas se agitam; ele disse: Subirei, cobrirei a terra, destruirei a cidade e os que habitam nela.

[[v24-46-9]]

^<<v24-46-9,9>>^ Avançai, ó cavaleiros, estrondeai, ó carros, e saiam os valentes; os etíopes e os de Pute, que manejam o escudo, e os lídios, que manejam e entesam o arco.

[[v24-46-10]]

^<<v24-46-10,10>>^ Porque este dia é o Dia do Senhor, o SENHOR dos Exércitos, dia de vingança contra os seus adversários; a espada devorará, fartar-se-á e se embriagará com o sangue deles; porque o Senhor, o SENHOR dos Exércitos tem um sacrifício na terra do Norte, junto ao rio Eufrates.

[[v24-46-11]]

^<<v24-46-11,11>>^ Sobe a Gileade e toma bálsamo, ó virgem filha do Egito; debalde multiplicas remédios, pois não há remédio para curar-te.

[[v24-46-12]]

^<<v24-46-12,12>>^ As nações ouviram falar da tua vergonha, e a terra está cheia do teu clamor; porque, fugindo o valente, tropeçou no valente, e ambos caíram juntos.

[[v24-46-13]]

^<<v24-46-13,13>>^ Palavra que falou o SENHOR a Jeremias, o profeta, acerca da vinda de Nabucodonosor, rei da Babilônia, para ferir a terra do Egito:

[[v24-46-14]]

^<<v24-46-14,14>>^ Anunciai no Egito e fazei ouvir isto em Migdol; fazei também ouvi-lo em Mênfis e em Tafnes; dizei: Apresenta-te e prepara-te; porque a espada já devorou o que está ao redor de ti.

[[v24-46-15]]

^<<v24-46-15,15>>^ Por que foi derribado o teu Touro? Não se pôde ter de pé, porque o SENHOR o abateu.

[[v24-46-16]]

^<<v24-46-16,16>>^ O SENHOR multiplicou os que tropeçavam; também caíram uns sobre os outros e disseram: Levanta-te, e voltemos ao nosso povo e à terra do nosso nascimento, por causa da espada que oprime.

[[v24-46-17]]

^<<v24-46-17,17>>^ Ali, apelidarão a Faraó, rei do Egito, de Espalhafatoso, porque deixou passar o tempo adequado.

[[v24-46-18]]

^<<v24-46-18,18>>^ Tão certo como vivo eu, diz o Rei, cujo nome é SENHOR dos Exércitos, certamente, como o Tabor é entre os montes e o Carmelo junto ao mar, assim ele virá.

[[v24-46-19]]

^<<v24-46-19,19>>^ Prepara a tua bagagem para o exílio, ó moradora, filha do Egito; porque Mênfis se tornará em desolação e ficará arruinada e sem moradores.

[[v24-46-20]]

^<<v24-46-20,20>>^ Novilha mui formosa é o Egito; mas mutuca do Norte já lhe vem, sim, vem.

[[v24-46-21]]

^<<v24-46-21,21>>^ Até os seus soldados mercenários no meio dele, bezerros cevados, viraram as costas e fugiram juntos; não resistiram, porque veio sobre eles o dia da sua ruína e o tempo do seu castigo.

[[v24-46-22]]

^<<v24-46-22,22>>^ Faz o Egito um ruído como o da serpente que foge, porque os seus inimigos vêm contra ele, com machados, quais derribadores de árvores.

[[v24-46-23]]

^<<v24-46-23,23>>^ Cortarão o seu bosque, diz o SENHOR, ainda que impenetrável; porque se multiplicaram mais do que os gafanhotos; são inumeráveis.

[[v24-46-24]]

^<<v24-46-24,24>>^ A filha do Egito está envergonhada; foi entregue nas mãos do povo do Norte.

[[v24-46-25]]

^<<v24-46-25,25>>^ Diz o SENHOR dos Exércitos, o Deus de Israel: Eis que eu castigarei a Amom de Nô, a Faraó, ao Egito, aos deuses e aos seus reis, ao próprio Faraó e aos que confiam nele.

[[v24-46-26]]

^<<v24-46-26,26>>^ Entregá-los-ei nas mãos dos que lhes procuram a morte, nas mãos de Nabucodonosor, rei da Babilônia, e nas mãos dos seus servos; mas depois será habitada, como nos dias antigos, diz o Senhor.

[[v24-46-27]]

^<<v24-46-27,27>>^ Não temas, pois, tu, servo meu, Jacó, nem te espantes, ó Israel; porque eu te livrarei do país remoto e a tua descendência, da terra do seu cativeiro; Jacó voltará e ficará tranquilo e confiante; não haverá quem o atemorize.

[[v24-46-28]]

^<<v24-46-28,28>>^ Não temas, servo meu, Jacó, diz o SENHOR, porque estou contigo; darei cabo de todas as nações para as quais eu te arrojei; mas de ti não darei cabo; castigar-te-ei, mas em justa medida; não te inocentarei de todo.

'''

xref:024-jeremias/024-jeremias-045.adoc#v24-45-0[&#60; Capítulo Anterior] | <<v24-46-0,Topo>> | xref:024-jeremias/024-jeremias-047.adoc#v24-47-0[Próximo Capítulo &#62;]