include::./index.adoc[]

[[v24-19-0]]
=== Jeremias, 19
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-19-1]]

^<<v24-19-1,1>>^ Assim diz o SENHOR: Vai, compra uma botija de oleiro e leva contigo alguns dos anciãos do povo e dos anciãos dos sacerdotes;

[[v24-19-2]]

^<<v24-19-2,2>>^ sai ao vale do filho de Hinom, que está à entrada da Porta do Oleiro, e apregoa ali as palavras que eu te disser;

[[v24-19-3]]

^<<v24-19-3,3>>^ e dize: Ouvi a palavra do SENHOR, ó reis de Judá e moradores de Jerusalém. Assim diz o SENHOR dos Exércitos, o Deus de Israel: Eis que trarei mal sobre este lugar, e quem quer que dele ouvir retinir-lhe-ão os ouvidos.

[[v24-19-4]]

^<<v24-19-4,4>>^ Porquanto me deixaram e profanaram este lugar, queimando nele incenso a outros deuses, que nunca conheceram, nem eles, nem seus pais, nem os reis de Judá; e encheram este lugar de sangue de inocentes;

[[v24-19-5]]

^<<v24-19-5,5>>^ e edificaram os altos de Baal, para queimarem os seus filhos no fogo em holocaustos a Baal, o que nunca lhes ordenei, nem falei, nem me passou pela mente.

[[v24-19-6]]

^<<v24-19-6,6>>^ Por isso, eis que vêm dias, diz o SENHOR, em que este lugar já não se chamará Tofete, nem vale do filho de Hinom, mas o vale da Matança.

[[v24-19-7]]

^<<v24-19-7,7>>^ Porque dissiparei o conselho de Judá e de Jerusalém neste lugar e os farei cair à espada diante de seus inimigos e pela mão dos que procuram tirar-lhes a vida; e darei o seu cadáver por pasto às aves dos céus e aos animais da terra.

[[v24-19-8]]

^<<v24-19-8,8>>^ Porei esta cidade por espanto e objeto de assobios; todo aquele que passar por ela se espantará e assobiará, por causa de todas as suas pragas.

[[v24-19-9]]

^<<v24-19-9,9>>^ Fá-los-ei comer as carnes de seus filhos e as carnes de suas filhas, e cada um comerá a carne do seu próximo, no cerco e na angústia em que os apertarão os seus inimigos e os que buscam tirar-lhes a vida.

[[v24-19-10]]

^<<v24-19-10,10>>^ Então, quebrarás a botija à vista dos homens que foram contigo

[[v24-19-11]]

^<<v24-19-11,11>>^ e lhes dirás: Assim diz o SENHOR dos Exércitos: Deste modo quebrarei eu este povo e esta cidade, como se quebra o vaso do oleiro, que não pode mais refazer-se, e os enterrarão em Tofete, porque não haverá outro lugar para os enterrar.

[[v24-19-12]]

^<<v24-19-12,12>>^ Assim farei a este lugar, diz o SENHOR, e aos seus moradores; e farei desta cidade um Tofete.

[[v24-19-13]]

^<<v24-19-13,13>>^ As casas de Jerusalém e as casas dos reis de Judá serão imundas como o lugar de Tofete; também todas as casas sobre cujos terraços queimaram incenso a todo o exército dos céus e ofereceram libações a outros deuses.

[[v24-19-14]]

^<<v24-19-14,14>>^ Voltando, pois, Jeremias de Tofete, lugar para onde o enviara o SENHOR a profetizar, se pôs em pé no átrio da Casa do SENHOR e disse a todo o povo:

[[v24-19-15]]

^<<v24-19-15,15>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel: Eis que trarei sobre esta cidade e sobre todas as suas vilas todo o mal que pronunciei contra ela, porque endureceram a cerviz, para não ouvirem as minhas palavras.

'''

xref:024-jeremias/024-jeremias-018.adoc#v24-18-0[&#60; Capítulo Anterior] | <<v24-19-0,Topo>> | xref:024-jeremias/024-jeremias-020.adoc#v24-20-0[Próximo Capítulo &#62;]