include::./index.adoc[]

[[v24-22-0]]
=== Jeremias, 22
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-22-1]]

^<<v24-22-1,1>>^ Assim diz o SENHOR: Desce à casa do rei de Judá, e anuncia ali esta palavra,

[[v24-22-2]]

^<<v24-22-2,2>>^ e dize: Ouve a palavra do SENHOR, ó rei de Judá, que te assentas no trono de Davi, tu, os teus servos e o teu povo, que entrais por estas portas.

[[v24-22-3]]

^<<v24-22-3,3>>^ Assim diz o SENHOR: Executai o direito e a justiça e livrai o oprimido das mãos do opressor; não oprimais ao estrangeiro, nem ao órfão, nem à viúva; não façais violência, nem derrameis sangue inocente neste lugar.

[[v24-22-4]]

^<<v24-22-4,4>>^ Porque, se, deveras, cumprirdes esta palavra, entrarão pelas portas desta casa os reis que se assentarão no trono de Davi, em carros e montados em cavalos, eles, os seus servos e o seu povo.

[[v24-22-5]]

^<<v24-22-5,5>>^ Mas, se não derdes ouvidos a estas palavras, juro por mim mesmo, diz o SENHOR, que esta casa se tornará em desolação.

[[v24-22-6]]

^<<v24-22-6,6>>^ Porque assim diz o SENHOR acerca da casa do rei de Judá: Tu és para mim Gileade e a cabeça do Líbano; mas certamente farei de ti um deserto e cidades desabitadas.

[[v24-22-7]]

^<<v24-22-7,7>>^ Designarei contra ti destruidores, cada um com as suas armas; cortarão os teus cedros escolhidos e lançá-los-ão no fogo.

[[v24-22-8]]

^<<v24-22-8,8>>^ Muitas nações passarão por esta cidade, e dirá cada um ao seu companheiro: Por que procedeu o SENHOR assim com esta grande cidade?

[[v24-22-9]]

^<<v24-22-9,9>>^ Então, se lhes responderá: Porque deixaram a aliança do SENHOR, seu Deus, e adoraram a outros deuses, e os serviram.

[[v24-22-10]]

^<<v24-22-10,10>>^ Não choreis o morto, nem o lastimeis; chorai amargamente aquele que sai; porque nunca mais tornará, nem verá a terra onde nasceu.

[[v24-22-11]]

^<<v24-22-11,11>>^ Porque assim diz o SENHOR acerca de Salum, filho de Josias, rei de Judá, que reinou em lugar de Josias, seu pai, e que saiu deste lugar: Jamais tornará para ali.

[[v24-22-12]]

^<<v24-22-12,12>>^ Mas no lugar para onde o levaram cativo morrerá e nunca mais verá esta terra.

[[v24-22-13]]

^<<v24-22-13,13>>^ Ai daquele que edifica a sua casa com injustiça e os seus aposentos, sem direito! Que se vale do serviço do seu próximo, sem paga, e não lhe dá o salário;

[[v24-22-14]]

^<<v24-22-14,14>>^ que diz: Edificarei para mim casa espaçosa e largos aposentos, e lhe abre janelas, e forra-a de cedros, e a pinta de vermelhão.

[[v24-22-15]]

^<<v24-22-15,15>>^ Reinarás tu, só porque rivalizas com outro em cedro? Acaso, teu pai não comeu, e bebeu, e não exercitou o juízo e a justiça? Por isso, tudo lhe sucedeu bem.

[[v24-22-16]]

^<<v24-22-16,16>>^ Julgou a causa do aflito e do necessitado; por isso, tudo lhe ia bem. Porventura, não é isso conhecer-me? — diz o SENHOR.

[[v24-22-17]]

^<<v24-22-17,17>>^ Mas os teus olhos e o teu coração não atentam senão para a tua ganância, e para derramar o sangue inocente, e para levar a efeito a violência e a extorsão.

[[v24-22-18]]

^<<v24-22-18,18>>^ Portanto, assim diz o SENHOR acerca de Jeoaquim, filho de Josias, rei de Judá: Não o lamentarão, dizendo: Ai, meu irmão! Ou: Ai, minha irmã! Nem o lamentarão, dizendo: Ai, senhor! Ou: Ai, sua glória!

[[v24-22-19]]

^<<v24-22-19,19>>^ Como se sepulta um jumento, assim o sepultarão; arrastá-lo-ão e o lançarão para bem longe, para fora das portas de Jerusalém.

[[v24-22-20]]

^<<v24-22-20,20>>^ Sobe ao Líbano, ó Jerusalém, e clama; ergue a voz em Basã e clama desde Abarim, porque estão esmagados todos os teus amantes.

[[v24-22-21]]

^<<v24-22-21,21>>^ Falei contigo na tua prosperidade, mas tu disseste: Não ouvirei. Tem sido este o teu caminho, desde a tua mocidade, pois nunca deste ouvidos à minha voz.

[[v24-22-22]]

^<<v24-22-22,22>>^ O vento apascentará todos os teus pastores, e os teus amantes irão para o cativeiro; então, certamente ficarás envergonhada e confundida, por causa de toda a tua maldade.

[[v24-22-23]]

^<<v24-22-23,23>>^ Ó tu que habitas no Líbano e fazes o teu ninho nos cedros! Como gemerás quando te vierem as dores e as angústias como da que está de parto!

[[v24-22-24]]

^<<v24-22-24,24>>^ Tão certo como eu vivo, diz o SENHOR, ainda que Jeconias, filho de Jeoaquim, rei de Judá, fosse o anel do selo da minha mão direita, eu dali o arrancaria.

[[v24-22-25]]

^<<v24-22-25,25>>^ Entregar-te-ei, ó rei, nas mãos dos que procuram tirar-te a vida e nas mãos daqueles a quem temes, a saber, nas mãos de Nabucodonosor, rei da Babilônia, e nas mãos dos caldeus.

[[v24-22-26]]

^<<v24-22-26,26>>^ Lançar-te-ei a ti e a tua mãe, que te deu à luz, para outra terra, em que não nasceste; e ali morrereis.

[[v24-22-27]]

^<<v24-22-27,27>>^ Mas à terra da qual eles têm saudades, a ela não tornarão.

[[v24-22-28]]

^<<v24-22-28,28>>^ Acaso, é este Jeconias homem vil, coisa quebrada ou objeto de que ninguém se agrada? Por que foram lançados fora, ele e os seus filhos, e arrojados para a terra que não conhecem?

[[v24-22-29]]

^<<v24-22-29,29>>^ Ó terra, terra, terra! Ouve a palavra do SENHOR!

[[v24-22-30]]

^<<v24-22-30,30>>^ Assim diz o SENHOR: Registrai este como se não tivera filhos; homem que não prosperará nos seus dias, e nenhum dos seus filhos prosperará, para se assentar no trono de Davi e ainda reinar em Judá.

'''

xref:024-jeremias/024-jeremias-021.adoc#v24-21-0[&#60; Capítulo Anterior] | <<v24-22-0,Topo>> | xref:024-jeremias/024-jeremias-023.adoc#v24-23-0[Próximo Capítulo &#62;]