include::./index.adoc[]

[[v24-34-0]]
=== Jeremias, 34
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-34-1]]

^<<v24-34-1,1>>^ Palavra que do SENHOR veio a Jeremias, quando Nabucodonosor, rei da Babilônia, e todo o seu exército, e todos os reinos da terra que estavam debaixo do seu poder, e todos os povos pelejavam contra Jerusalém e contra todas as suas cidades, dizendo:

[[v24-34-2]]

^<<v24-34-2,2>>^ Assim diz o SENHOR, Deus de Israel: Vai, fala a Zedequias, rei de Judá, e dize-lhe: Assim diz o SENHOR: Eis que eu entrego esta cidade nas mãos do rei da Babilônia, o qual a queimará.

[[v24-34-3]]

^<<v24-34-3,3>>^ Tu não lhe escaparás das mãos; pelo contrário, serás preso e entregue nas suas mãos; tu verás o rei da Babilônia face a face, e ele te falará boca a boca, e entrarás na Babilônia.

[[v24-34-4]]

^<<v24-34-4,4>>^ Todavia, ouve a palavra do SENHOR, ó Zedequias, rei de Judá: Assim diz o SENHOR a teu respeito: Não morrerás à espada.

[[v24-34-5]]

^<<v24-34-5,5>>^ Em paz morrerás, e te queimarão perfumes a ti, como se queimaram a teus pais, que, como reis, te precederam, e te prantearão, dizendo: Ah! Senhor! Pois eu é que disse a palavra, diz o SENHOR.

[[v24-34-6]]

^<<v24-34-6,6>>^ Falou Jeremias, o profeta, a Zedequias, rei de Judá, todas estas palavras, em Jerusalém,

[[v24-34-7]]

^<<v24-34-7,7>>^ quando o exército do rei da Babilônia pelejava contra Jerusalém e contra todas as cidades que restavam de Judá, contra Laquis e contra Azeca; porque só estas ficaram das cidades fortificadas de Judá.

[[v24-34-8]]

^<<v24-34-8,8>>^ Palavra que do SENHOR veio a Jeremias, depois que o rei Zedequias fez aliança com todo o povo de Jerusalém, para lhes apregoar a liberdade:

[[v24-34-9]]

^<<v24-34-9,9>>^ que cada um despedisse forro o seu servo e cada um, a sua serva, hebreu ou hebreia, de maneira que ninguém retivesse como escravos hebreus, seus irmãos.

[[v24-34-10]]

^<<v24-34-10,10>>^ Todos os príncipes e todo o povo que haviam entrado na aliança obedeceram, despedindo forro cada um o seu servo e cada um a sua serva, de maneira que já não os retiveram como escravos; obedeceram e os despediram.

[[v24-34-11]]

^<<v24-34-11,11>>^ Mas depois se arrependeram, e fizeram voltar os servos e as servas que haviam despedido forros, e os sujeitaram por servos e por servas.

[[v24-34-12]]

^<<v24-34-12,12>>^ Veio, pois, a palavra do SENHOR a Jeremias, da parte do SENHOR, dizendo:

[[v24-34-13]]

^<<v24-34-13,13>>^ Assim diz o SENHOR, Deus de Israel: Eu fiz aliança com vossos pais, no dia em que os tirei da terra do Egito, da casa da servidão, dizendo:

[[v24-34-14]]

^<<v24-34-14,14>>^ Ao fim de sete anos, libertareis cada um a seu irmão hebreu, que te for vendido a ti e te houver servido seis anos, e despedi-lo-ás forro; mas vossos pais não me obedeceram, nem inclinaram os seus ouvidos a mim.

[[v24-34-15]]

^<<v24-34-15,15>>^ Não há muito, havíeis voltado a fazer o que é reto perante mim, apregoando liberdade cada um ao seu próximo; e tínheis feito perante mim aliança, na casa que se chama pelo meu nome;

[[v24-34-16]]

^<<v24-34-16,16>>^ mudastes, porém, e profanastes o meu nome, fazendo voltar cada um o seu servo e cada um, a sua serva, os quais, deixados à vontade, já tínheis despedido forros, e os sujeitastes, para que fossem vossos servos e servas.

[[v24-34-17]]

^<<v24-34-17,17>>^ Portanto, assim diz o SENHOR: Vós não me obedecestes, para apregoardes a liberdade, cada um a seu irmão e cada um ao seu próximo; pois eis que eu vos apregoo a liberdade, diz o SENHOR, para a espada, para a peste e para a fome; farei que sejais um espetáculo horrendo para todos os reinos da terra.

[[v24-34-18]]

^<<v24-34-18,18>>^ Farei aos homens que transgrediram a minha aliança e não cumpriram as palavras da aliança que fizeram perante mim como eles fizeram com o bezerro que dividiram em duas partes, passando eles pelo meio das duas porções;

[[v24-34-19]]

^<<v24-34-19,19>>^ os príncipes de Judá, os príncipes de Jerusalém, os oficiais, os sacerdotes e todo o povo da terra, os quais passaram por meio das porções do bezerro,

[[v24-34-20]]

^<<v24-34-20,20>>^ entregá-los-ei nas mãos de seus inimigos e nas mãos dos que procuram a sua morte, e os cadáveres deles servirão de pasto às aves dos céus e aos animais da terra.

[[v24-34-21]]

^<<v24-34-21,21>>^ A Zedequias, rei de Judá, e a seus príncipes, entregá-los-ei nas mãos de seus inimigos e nas mãos dos que procuram a sua morte, nas mãos do exército do rei da Babilônia, que já se retiraram de vós.

[[v24-34-22]]

^<<v24-34-22,22>>^ Eis que eu darei ordem, diz o SENHOR, e os farei tornar a esta cidade, e pelejarão contra ela, tomá-la-ão e a queimarão; e as cidades de Judá porei em assolação, de sorte que ninguém habite nelas.

'''

xref:024-jeremias/024-jeremias-033.adoc#v24-33-0[&#60; Capítulo Anterior] | <<v24-34-0,Topo>> | xref:024-jeremias/024-jeremias-035.adoc#v24-35-0[Próximo Capítulo &#62;]