include::./index.adoc[]

[[v24-8-0]]
=== Jeremias, 8
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-8-1]]

^<<v24-8-1,1>>^ Naquele tempo, diz o SENHOR, lançarão para fora das suas sepulturas os ossos dos reis e dos príncipes de Judá, os ossos dos sacerdotes e dos profetas e os ossos dos habitantes de Jerusalém;

[[v24-8-2]]

^<<v24-8-2,2>>^ espalhá-los-ão ao sol, e à lua, e a todo o exército do céu, a quem tinham amado, e a quem serviram, e após quem tinham ido, e a quem procuraram, e diante de quem se tinham prostrado; não serão recolhidos, nem sepultados; serão como esterco sobre a terra.

[[v24-8-3]]

^<<v24-8-3,3>>^ Escolherão antes a morte do que a vida todos os que restarem desta raça malvada que ficar nos lugares para onde os dispersei, diz o SENHOR dos Exércitos.

[[v24-8-4]]

^<<v24-8-4,4>>^ Dize-lhes mais: Assim diz o SENHOR: Quando caem os homens, não se tornam a levantar? Quando alguém se desvia do caminho, não torna a voltar?

[[v24-8-5]]

^<<v24-8-5,5>>^ Por que, pois, este povo de Jerusalém se desvia, apostatando continuamente? Persiste no engano e não quer voltar.

[[v24-8-6]]

^<<v24-8-6,6>>^ Eu escutei e ouvi; não falam o que é reto, ninguém há que se arrependa da sua maldade, dizendo: Que fiz eu? Cada um corre a sua carreira como um cavalo que arremete com ímpeto na batalha.

[[v24-8-7]]

^<<v24-8-7,7>>^ Até a cegonha no céu conhece as suas estações; a rola, a andorinha e o grou observam o tempo da sua arribação; mas o meu povo não conhece o juízo do SENHOR.

[[v24-8-8]]

^<<v24-8-8,8>>^ Como, pois, dizeis: Somos sábios, e a lei do SENHOR está conosco? Pois, com efeito, a falsa pena dos escribas a converteu em mentira.

[[v24-8-9]]

^<<v24-8-9,9>>^ Os sábios serão envergonhados, aterrorizados e presos; eis que rejeitaram a palavra do SENHOR; que sabedoria é essa que eles têm?

[[v24-8-10]]

^<<v24-8-10,10>>^ Portanto, darei suas mulheres a outros, e os seus campos, a novos possuidores; porque, desde o menor deles até ao maior, cada um se dá à ganância, e tanto o profeta como o sacerdote usam de falsidade.

[[v24-8-11]]

^<<v24-8-11,11>>^ Curam superficialmente a ferida do meu povo, dizendo: Paz, paz; quando não há paz.

[[v24-8-12]]

^<<v24-8-12,12>>^ Serão envergonhados, porque cometem abominação sem sentir por isso vergonha; nem sabem que coisa é envergonhar-se. Portanto, cairão com os que caem; quando eu os castigar, tropeçarão, diz o SENHOR.

[[v24-8-13]]

^<<v24-8-13,13>>^ Eu os consumirei de todo, diz o SENHOR; não haverá uvas na vide, nem figos na figueira, e a folha já está murcha; e já lhes designei os que passarão sobre eles.

[[v24-8-14]]

^<<v24-8-14,14>>^ Por que estamos ainda assentados aqui? Reuni-vos, e entremos nas cidades fortificadas e ali pereçamos; pois o SENHOR já nos decretou o perecimento e nos deu a beber água venenosa, porquanto pecamos contra o SENHOR.

[[v24-8-15]]

^<<v24-8-15,15>>^ Espera-se a paz, e nada há de bom; o tempo da cura, e eis o terror.

[[v24-8-16]]

^<<v24-8-16,16>>^ Desde Dã se ouve o resfolegar dos seus cavalos; toda a terra treme à voz dos rinchos dos seus garanhões; e vêm e devoram a terra e a sua abundância, a cidade e os que habitam nela.

[[v24-8-17]]

^<<v24-8-17,17>>^ Porque eis que envio para entre vós serpentes, áspides contra as quais não há encantamento, e vos morderão, diz o SENHOR.

[[v24-8-18]]

^<<v24-8-18,18>>^ Oh! Se eu pudesse consolar-me na minha tristeza! O meu coração desfalece dentro de mim.

[[v24-8-19]]

^<<v24-8-19,19>>^ Eis a voz do clamor da filha do meu povo de terra mui remota: Não está o SENHOR em Sião? Não está nela o seu Rei? Por que me provocaram à ira com as suas imagens de escultura, com os ídolos dos estrangeiros?

[[v24-8-20]]

^<<v24-8-20,20>>^ Passou a sega, findou o verão, e nós não estamos salvos.

[[v24-8-21]]

^<<v24-8-21,21>>^ Estou quebrantado pela ferida da filha do meu povo; estou de luto; o espanto se apoderou de mim.

[[v24-8-22]]

^<<v24-8-22,22>>^ Acaso, não há bálsamo em Gileade? Ou não há lá médico? Por que, pois, não se realizou a cura da filha do meu povo?

'''

xref:024-jeremias/024-jeremias-007.adoc#v24-7-0[&#60; Capítulo Anterior] | <<v24-8-0,Topo>> | xref:024-jeremias/024-jeremias-009.adoc#v24-9-0[Próximo Capítulo &#62;]