include::./index.adoc[]

[[v24-12-0]]
=== Jeremias, 12
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-12-1]]

^<<v24-12-1,1>>^ Justo és, ó SENHOR, quando entro contigo num pleito; contudo, falarei contigo dos teus juízos. Por que prospera o caminho dos perversos, e vivem em paz todos os que procedem perfidamente?

[[v24-12-2]]

^<<v24-12-2,2>>^ Plantaste-os, e eles deitaram raízes; crescem, dão fruto; têm-te nos lábios, mas longe do coração.

[[v24-12-3]]

^<<v24-12-3,3>>^ Mas tu, ó SENHOR, me conheces, tu me vês e provas o que sente o meu coração para contigo. Arranca-os como as ovelhas para o matadouro e destina-os para o dia da matança.

[[v24-12-4]]

^<<v24-12-4,4>>^ Até quando estará de luto a terra, e se secará a erva de todo o campo? Por causa da maldade dos que habitam nela, perecem os animais e as aves; porquanto dizem: Ele não verá o nosso fim.

[[v24-12-5]]

^<<v24-12-5,5>>^ Se te fatigas correndo com homens que vão a pé, como poderás competir com os que vão a cavalo? Se em terra de paz não te sentes seguro, que farás na floresta do Jordão?

[[v24-12-6]]

^<<v24-12-6,6>>^ Porque até os teus irmãos e a casa de teu pai, eles próprios procedem perfidamente contigo; eles mesmos te perseguem com fortes gritos. Não te fies deles ainda que te digam coisas boas.

[[v24-12-7]]

^<<v24-12-7,7>>^ Desamparei a minha casa, abandonei a minha herança; a que mais eu amava entreguei na mão de seus inimigos.

[[v24-12-8]]

^<<v24-12-8,8>>^ A minha herança tornou-se-me como leão numa floresta; levantou a voz contra mim; por isso, eu a aborreci.

[[v24-12-9]]

^<<v24-12-9,9>>^ Acaso, é para mim a minha herança ave de rapina de várias cores contra a qual se ajuntam outras aves de rapina? Ide, pois, ajuntai todos os animais do campo, trazei-os para a devorarem.

[[v24-12-10]]

^<<v24-12-10,10>>^ Muitos pastores destruíram a minha vinha e pisaram o meu quinhão; a porção que era o meu prazer, tornaram-na em deserto.

[[v24-12-11]]

^<<v24-12-11,11>>^ Em assolação a tornaram, e a mim clama no seu abandono; toda a terra está devastada, porque ninguém há que tome isso a peito.

[[v24-12-12]]

^<<v24-12-12,12>>^ Sobre todos os altos desnudos do deserto vieram destruidores; porque a espada do SENHOR devora de um a outro extremo da terra; não há paz para ninguém.

[[v24-12-13]]

^<<v24-12-13,13>>^ Semearam trigo e segaram espinhos; cansaram-se, mas sem proveito algum. Envergonhados sereis dos vossos frutos, por causa do brasume da ira do SENHOR.

[[v24-12-14]]

^<<v24-12-14,14>>^ Assim diz o SENHOR acerca de todos os meus maus vizinhos, que se apoderam da minha herança, que deixei ao meu povo de Israel: Eis que os arrancarei da sua terra e a casa de Judá arrancarei do meio deles.

[[v24-12-15]]

^<<v24-12-15,15>>^ E será que, depois de os haver arrancado, tornarei a compadecer-me deles e os farei voltar, cada um à sua herança, cada um à sua terra.

[[v24-12-16]]

^<<v24-12-16,16>>^ Se diligentemente aprenderem os caminhos do meu povo, jurando pelo meu nome: Tão certo como vive o SENHOR, como ensinaram o meu povo a jurar por Baal, então, serão edificados no meio do meu povo.

[[v24-12-17]]

^<<v24-12-17,17>>^ Mas, se não quiserem ouvir, arrancarei tal nação, arrancá-la-ei e a farei perecer, diz o SENHOR.

'''

xref:024-jeremias/024-jeremias-011.adoc#v24-11-0[&#60; Capítulo Anterior] | <<v24-12-0,Topo>> | xref:024-jeremias/024-jeremias-013.adoc#v24-13-0[Próximo Capítulo &#62;]