include::./index.adoc[]

[[v24-24-0]]
=== Jeremias, 24
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-24-1]]

^<<v24-24-1,1>>^ Fez-me ver o SENHOR, e vi dois cestos de figos postos diante do templo do SENHOR, depois que Nabucodonosor, rei da Babilônia, levou em cativeiro a Jeconias, filho de Jeoaquim, rei de Judá, e os príncipes de Judá, e os artífices, e os ferreiros de Jerusalém e os trouxe à Babilônia.

[[v24-24-2]]

^<<v24-24-2,2>>^ Tinha um cesto figos muito bons, como os figos temporãos; mas o outro, ruins, que, de ruins que eram, não se podiam comer.

[[v24-24-3]]

^<<v24-24-3,3>>^ Então, me perguntou o SENHOR: Que vês tu, Jeremias? Respondi: Figos; os figos muito bons e os muito ruins, que, de ruins que são, não se podem comer.

[[v24-24-4]]

^<<v24-24-4,4>>^ A mim me veio a palavra do SENHOR, dizendo:

[[v24-24-5]]

^<<v24-24-5,5>>^ Assim diz o SENHOR, o Deus de Israel: Do modo por que vejo estes bons figos, assim favorecerei os exilados de Judá, que eu enviei deste lugar para a terra dos caldeus.

[[v24-24-6]]

^<<v24-24-6,6>>^ Porei sobre eles favoravelmente os olhos e os farei voltar para esta terra; edificá-los-ei e não os destruirei, plantá-los-ei e não os arrancarei.

[[v24-24-7]]

^<<v24-24-7,7>>^ Dar-lhes-ei coração para que me conheçam que eu sou o SENHOR; eles serão o meu povo, e eu serei o seu Deus; porque se voltarão para mim de todo o seu coração.

[[v24-24-8]]

^<<v24-24-8,8>>^ Como se rejeitam os figos ruins, que, de ruins que são, não se podem comer, assim tratarei a Zedequias, rei de Judá, diz o SENHOR, e a seus príncipes, e ao restante de Jerusalém, tanto aos que ficaram nesta terra como aos que habitam na terra do Egito.

[[v24-24-9]]

^<<v24-24-9,9>>^ Eu os farei objeto de espanto, calamidade para todos os reinos da terra; opróbrio e provérbio, escárnio e maldição em todos os lugares para onde os arrojarei.

[[v24-24-10]]

^<<v24-24-10,10>>^ Enviarei contra eles a espada, a fome e a peste, até que se consumam de sobre a terra que lhes dei, a eles e a seus pais.

'''

xref:024-jeremias/024-jeremias-023.adoc#v24-23-0[&#60; Capítulo Anterior] | <<v24-24-0,Topo>> | xref:024-jeremias/024-jeremias-025.adoc#v24-25-0[Próximo Capítulo &#62;]