include::./index.adoc[]

[[v24-29-0]]
=== Jeremias, 29
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-29-1]]

^<<v24-29-1,1>>^ São estas as palavras da carta que Jeremias, o profeta, enviou de Jerusalém ao resto dos anciãos do cativeiro, como também aos sacerdotes, aos profetas e a todo o povo que Nabucodonosor havia deportado de Jerusalém para a Babilônia,

[[v24-29-2]]

^<<v24-29-2,2>>^ depois que saíram de Jerusalém o rei Jeconias, a rainha-mãe, os oficiais, os príncipes de Judá e Jerusalém e os carpinteiros e ferreiros.

[[v24-29-3]]

^<<v24-29-3,3>>^ A carta foi mandada por intermédio de Elasa, filho de Safã, e de Gemarias, filho de Hilquias, os quais Zedequias, rei de Judá, tinha enviado à Babilônia, a Nabucodonosor, rei da Babilônia, e dizia:

[[v24-29-4]]

^<<v24-29-4,4>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel, a todos os exilados que eu deportei de Jerusalém para a Babilônia:

[[v24-29-5]]

^<<v24-29-5,5>>^ Edificai casas e habitai nelas; plantai pomares e comei o seu fruto.

[[v24-29-6]]

^<<v24-29-6,6>>^ Tomai esposas e gerai filhos e filhas, tomai esposas para vossos filhos e dai vossas filhas a maridos, para que tenham filhos e filhas; multiplicai-vos aí e não vos diminuais.

[[v24-29-7]]

^<<v24-29-7,7>>^ Procurai a paz da cidade para onde vos desterrei e orai por ela ao SENHOR; porque na sua paz vós tereis paz.

[[v24-29-8]]

^<<v24-29-8,8>>^ Porque assim diz o SENHOR dos Exércitos, o Deus de Israel: Não vos enganem os vossos profetas que estão no meio de vós, nem os vossos adivinhos, nem deis ouvidos aos vossos sonhadores, que sempre sonham segundo o vosso desejo;

[[v24-29-9]]

^<<v24-29-9,9>>^ porque falsamente vos profetizam eles em meu nome; eu não os enviei, diz o SENHOR.

[[v24-29-10]]

^<<v24-29-10,10>>^ Assim diz o SENHOR: Logo que se cumprirem para a Babilônia setenta anos, atentarei para vós outros e cumprirei para convosco a minha boa palavra, tornando a trazer-vos para este lugar.

[[v24-29-11]]

^<<v24-29-11,11>>^ Eu é que sei que pensamentos tenho a vosso respeito, diz o SENHOR; pensamentos de paz e não de mal, para vos dar o fim que desejais.

[[v24-29-12]]

^<<v24-29-12,12>>^ Então, me invocareis, passareis a orar a mim, e eu vos ouvirei.

[[v24-29-13]]

^<<v24-29-13,13>>^ Buscar-me-eis e me achareis quando me buscardes de todo o vosso coração.

[[v24-29-14]]

^<<v24-29-14,14>>^ Serei achado de vós, diz o SENHOR, e farei mudar a vossa sorte; congregar-vos-ei de todas as nações e de todos os lugares para onde vos lancei, diz o SENHOR, e tornarei a trazer-vos ao lugar donde vos mandei para o exílio.

[[v24-29-15]]

^<<v24-29-15,15>>^ Vós dizeis: O SENHOR nos suscitou profetas na Babilônia.

[[v24-29-16]]

^<<v24-29-16,16>>^ Mas assim diz o SENHOR a respeito do rei que se assenta no trono de Davi e de todo o povo que habita nesta cidade, vossos irmãos, que não saíram convosco para o exílio;

[[v24-29-17]]

^<<v24-29-17,17>>^ assim diz o SENHOR dos Exércitos: Eis que enviarei contra eles a espada, a fome e a peste e fá-los-ei como a figos ruins, que, de ruins que são, não se podem comer.

[[v24-29-18]]

^<<v24-29-18,18>>^ Persegui-los-ei com a espada, a fome e a peste; fá-los-ei um espetáculo horrendo para todos os reinos da terra; e os porei por objeto de espanto, e de assobio, e de opróbrio entre todas as nações para onde os tiver arrojado;

[[v24-29-19]]

^<<v24-29-19,19>>^ porque não deram ouvidos às minhas palavras, diz o SENHOR, com as quais, começando de madrugada, lhes enviei os meus servos, os profetas; mas vós não os escutastes, diz o SENHOR.

[[v24-29-20]]

^<<v24-29-20,20>>^ Vós, pois, ouvi a palavra do SENHOR, todos os do exílio que enviei de Jerusalém para a Babilônia.

[[v24-29-21]]

^<<v24-29-21,21>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel, acerca de Acabe, filho de Colaías, e de Zedequias, filho de Maaseias, que vos profetizam falsamente em meu nome: Eis que os entregarei nas mãos de Nabucodonosor, rei da Babilônia, e ele os ferirá diante dos vossos olhos.

[[v24-29-22]]

^<<v24-29-22,22>>^ Daí surgirá nova espécie de maldição entre os exilados de Judá que estão na Babilônia: o SENHOR te faça como a Zedequias e como a Acabe, os quais o rei da Babilônia assou no fogo;

[[v24-29-23]]

^<<v24-29-23,23>>^ porquanto fizeram loucuras em Israel, cometeram adultérios com as mulheres de seus companheiros e anunciaram falsamente em meu nome palavras que não lhes mandei dizer; eu o sei e sou testemunha disso, diz o SENHOR.

[[v24-29-24]]

^<<v24-29-24,24>>^ A Semaías, o neelamita, falarás, dizendo:

[[v24-29-25]]

^<<v24-29-25,25>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel: Porquanto enviaste no teu nome cartas a todo o povo que está em Jerusalém, como também a Sofonias, filho de Maaseias, o sacerdote, e a todos os sacerdotes, dizendo:

[[v24-29-26]]

^<<v24-29-26,26>>^ O SENHOR te pôs por sacerdote em lugar do sacerdote Joiada, para que sejas encarregado da Casa do SENHOR sobre todo homem fanático que quer passar por profeta, para o lançares na prisão e no tronco.

[[v24-29-27]]

^<<v24-29-27,27>>^ Agora, pois, por que não repreendeste a Jeremias, o anatotita, que vos profetiza?

[[v24-29-28]]

^<<v24-29-28,28>>^ Pois nos enviou mensageiros à Babilônia para nos dizer: Há de durar muito o exílio; edificai casas e habitai nelas; plantai pomares e comei o seu fruto.

[[v24-29-29]]

^<<v24-29-29,29>>^ Sofonias, o sacerdote, leu esta carta aos ouvidos do profeta Jeremias.

[[v24-29-30]]

^<<v24-29-30,30>>^ Então, veio a palavra do SENHOR a Jeremias, dizendo:

[[v24-29-31]]

^<<v24-29-31,31>>^ Manda dizer a todos os exilados: Assim diz o SENHOR acerca de Semaías, o neelamita: Porquanto Semaías vos profetizou, não o havendo eu enviado, e vos fez confiar em mentiras,

[[v24-29-32]]

^<<v24-29-32,32>>^ assim diz o SENHOR: Eis que castigarei a Semaías, o neelamita, e à sua descendência; ele não terá ninguém que habite entre este povo e não verá o bem que hei de fazer ao meu povo, diz o SENHOR, porque pregou rebeldia contra o SENHOR.

'''

xref:024-jeremias/024-jeremias-028.adoc#v24-28-0[&#60; Capítulo Anterior] | <<v24-29-0,Topo>> | xref:024-jeremias/024-jeremias-030.adoc#v24-30-0[Próximo Capítulo &#62;]