include::./index.adoc[]

[[v24-32-0]]
=== Jeremias, 32
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-32-1]]

^<<v24-32-1,1>>^ Palavra que veio a Jeremias da parte do SENHOR, no ano décimo de Zedequias, rei de Judá, ou décimo oitavo de Nabucodonosor.

[[v24-32-2]]

^<<v24-32-2,2>>^ Ora, nesse tempo o exército do rei da Babilônia cercava Jerusalém; Jeremias, o profeta, estava encarcerado no pátio da guarda que estava na casa do rei de Judá.

[[v24-32-3]]

^<<v24-32-3,3>>^ Pois Zedequias, rei de Judá, o havia encerrado, dizendo: Por que profetizas tu que o SENHOR disse que entregaria esta cidade nas mãos do rei da Babilônia, e ele a tomaria;

[[v24-32-4]]

^<<v24-32-4,4>>^ que Zedequias, rei de Judá, não se livraria das mãos dos caldeus, mas infalivelmente seria entregue nas mãos do rei da Babilônia, e com ele falaria boca a boca, e o veria face a face;

[[v24-32-5]]

^<<v24-32-5,5>>^ e que ele levaria Zedequias para a Babilônia, onde estaria até que o SENHOR se lembrasse dele, como este disse; e, ainda que pelejásseis contra os caldeus, não seríeis bem-sucedidos?

[[v24-32-6]]

^<<v24-32-6,6>>^ Disse, pois, Jeremias: Veio a mim a palavra do SENHOR, dizendo:

[[v24-32-7]]

^<<v24-32-7,7>>^ Eis que Hananel, filho de teu tio Salum, virá a ti, dizendo: Compra o meu campo que está em Anatote, pois a ti, a quem pertence o direito de resgate, compete comprá-lo.

[[v24-32-8]]

^<<v24-32-8,8>>^ Veio, pois, a mim, segundo a palavra do SENHOR, Hananel, filho de meu tio, ao pátio da guarda e me disse: Compra agora o meu campo que está em Anatote, na terra de Benjamim; porque teu é o direito de posse e de resgate; compra-o. Então, entendi que isto era a palavra do SENHOR.

[[v24-32-9]]

^<<v24-32-9,9>>^ Comprei, pois, de Hananel, filho de meu tio, o campo que está em Anatote; e lhe pesei o dinheiro, dezessete siclos de prata.

[[v24-32-10]]

^<<v24-32-10,10>>^ Assinei a escritura, fechei-a com selo, chamei testemunhas e pesei-lhe o dinheiro numa balança.

[[v24-32-11]]

^<<v24-32-11,11>>^ Tomei a escritura da compra, tanto a selada, segundo mandam a lei e os estatutos, como a cópia aberta;

[[v24-32-12]]

^<<v24-32-12,12>>^ dei-a a Baruque, filho de Nerias, filho de Maaseias, na presença de Hananel, filho de meu tio, e perante as testemunhas, que assinaram a escritura da compra, e na presença de todos os judeus que se assentavam no pátio da guarda.

[[v24-32-13]]

^<<v24-32-13,13>>^ Perante eles dei ordem a Baruque, dizendo:

[[v24-32-14]]

^<<v24-32-14,14>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel: Toma esta escritura, esta escritura da compra, tanto a selada como a aberta, e mete-as num vaso de barro, para que se possam conservar por muitos dias;

[[v24-32-15]]

^<<v24-32-15,15>>^ porque assim diz o SENHOR dos Exércitos, o Deus de Israel: Ainda se comprarão casas, campos e vinhas nesta terra.

[[v24-32-16]]

^<<v24-32-16,16>>^ Depois que dei a escritura da compra a Baruque, filho de Nerias, orei ao SENHOR, dizendo:

[[v24-32-17]]

^<<v24-32-17,17>>^ Ah! SENHOR Deus, eis que fizeste os céus e a terra com o teu grande poder e com o teu braço estendido; coisa alguma te é demasiadamente maravilhosa.

[[v24-32-18]]

^<<v24-32-18,18>>^ Tu usas de misericórdia para com milhares e retribuis a iniquidade dos pais nos filhos; tu és o grande, o poderoso Deus, cujo nome é o SENHOR dos Exércitos,

[[v24-32-19]]

^<<v24-32-19,19>>^ grande em conselho e magnífico em obras; porque os teus olhos estão abertos sobre todos os caminhos dos filhos dos homens, para dar a cada um segundo o seu proceder, segundo o fruto das suas obras.

[[v24-32-20]]

^<<v24-32-20,20>>^ Tu puseste sinais e maravilhas na terra do Egito até ao dia de hoje, tanto em Israel como entre outros homens; e te fizeste um nome, qual o que tens neste dia.

[[v24-32-21]]

^<<v24-32-21,21>>^ Tiraste o teu povo de Israel da terra do Egito, com sinais e maravilhas, com mão poderosa e braço estendido e com grande espanto;

[[v24-32-22]]

^<<v24-32-22,22>>^ e lhe deste esta terra, que com juramento prometeste a seus pais, terra que mana leite e mel.

[[v24-32-23]]

^<<v24-32-23,23>>^ Entraram nela e dela tomaram posse, mas não obedeceram à tua voz, nem andaram na tua lei; de tudo o que lhes mandaste que fizessem, nada fizeram; pelo que trouxeste sobre eles todo este mal.

[[v24-32-24]]

^<<v24-32-24,24>>^ Eis aqui as trincheiras já atingem a cidade, para ser tomada; já está a cidade entregue nas mãos dos caldeus, que pelejam contra ela, pela espada, pela fome e pela peste. O que disseste aconteceu; e tu mesmo o vês.

[[v24-32-25]]

^<<v24-32-25,25>>^ Contudo, ó SENHOR Deus, tu me disseste: Compra o campo por dinheiro e chama testemunhas, embora já esteja a cidade entregue nas mãos dos caldeus.

[[v24-32-26]]

^<<v24-32-26,26>>^ Então, veio a palavra do SENHOR a Jeremias, dizendo:

[[v24-32-27]]

^<<v24-32-27,27>>^ Eis que eu sou o SENHOR, o Deus de todos os viventes; acaso, haveria coisa demasiadamente maravilhosa para mim?

[[v24-32-28]]

^<<v24-32-28,28>>^ Portanto, assim diz o SENHOR: Eis que entrego esta cidade nas mãos dos caldeus, nas mãos de Nabucodonosor, rei da Babilônia, e ele a tomará.

[[v24-32-29]]

^<<v24-32-29,29>>^ Os caldeus, que pelejam contra esta cidade, entrarão nela, porão fogo a esta cidade e queimarão as casas sobre cujos terraços queimaram incenso a Baal e ofereceram libações a outros deuses, para me provocarem à ira.

[[v24-32-30]]

^<<v24-32-30,30>>^ Porque os filhos de Israel e os filhos de Judá não fizeram senão mal perante mim, desde a sua mocidade; porque os filhos de Israel não fizeram senão provocar-me à ira com as obras das suas mãos, diz o SENHOR.

[[v24-32-31]]

^<<v24-32-31,31>>^ Porque para minha ira e para meu furor me tem sido esta cidade, desde o dia em que a edificaram e até ao dia de hoje, para que eu a removesse da minha presença,

[[v24-32-32]]

^<<v24-32-32,32>>^ por causa de toda a maldade que fizeram os filhos de Israel e os filhos de Judá, para me provocarem à ira, eles, os seus reis, os seus príncipes, os seus sacerdotes e os seus profetas, como também os homens de Judá e os moradores de Jerusalém.

[[v24-32-33]]

^<<v24-32-33,33>>^ Viraram-me as costas e não o rosto; ainda que eu, começando de madrugada, os ensinava, eles não deram ouvidos, para receberem a advertência.

[[v24-32-34]]

^<<v24-32-34,34>>^ Antes, puseram as suas abominações na casa que se chama pelo meu nome, para a profanarem.

[[v24-32-35]]

^<<v24-32-35,35>>^ Edificaram os altos de Baal, que estão no vale do filho de Hinom, para queimarem a seus filhos e a suas filhas a Moloque, o que nunca lhes ordenei, nem me passou pela mente fizessem tal abominação, para fazerem pecar a Judá.

[[v24-32-36]]

^<<v24-32-36,36>>^ Agora, pois, assim diz o SENHOR, o Deus de Israel, acerca desta cidade, da qual vós dizeis: Já está entregue nas mãos do rei da Babilônia, pela espada, pela fome e pela peste.

[[v24-32-37]]

^<<v24-32-37,37>>^ Eis que eu os congregarei de todas as terras, para onde os lancei na minha ira, no meu furor e na minha grande indignação; tornarei a trazê-los a este lugar e farei que nele habitem seguramente.

[[v24-32-38]]

^<<v24-32-38,38>>^ Eles serão o meu povo, e eu serei o seu Deus.

[[v24-32-39]]

^<<v24-32-39,39>>^ Dar-lhes-ei um só coração e um só caminho, para que me temam todos os dias, para seu bem e bem de seus filhos.

[[v24-32-40]]

^<<v24-32-40,40>>^ Farei com eles aliança eterna, segundo a qual não deixarei de lhes fazer o bem; e porei o meu temor no seu coração, para que nunca se apartem de mim.

[[v24-32-41]]

^<<v24-32-41,41>>^ Alegrar-me-ei por causa deles e lhes farei bem; plantá-los-ei firmemente nesta terra, de todo o meu coração e de toda a minha alma.

[[v24-32-42]]

^<<v24-32-42,42>>^ Porque assim diz o SENHOR: Assim como fiz vir sobre este povo todo este grande mal, assim lhes trarei todo o bem que lhes estou prometendo.

[[v24-32-43]]

^<<v24-32-43,43>>^ Comprar-se-ão campos nesta terra, da qual vós dizeis: Está deserta, sem homens nem animais; está entregue nas mãos dos caldeus.

[[v24-32-44]]

^<<v24-32-44,44>>^ Comprarão campos por dinheiro, e lavrarão as escrituras, e as fecharão com selos, e chamarão testemunhas na terra de Benjamim, nos contornos de Jerusalém, nas cidades de Judá, nas cidades da região montanhosa, nas cidades das planícies e nas cidades do Sul; porque lhes restaurarei a sorte, diz o SENHOR.

'''

xref:024-jeremias/024-jeremias-031.adoc#v24-31-0[&#60; Capítulo Anterior] | <<v24-32-0,Topo>> | xref:024-jeremias/024-jeremias-033.adoc#v24-33-0[Próximo Capítulo &#62;]