include::./index.adoc[]

[[v24-11-0]]
=== Jeremias, 11
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-11-1]]

^<<v24-11-1,1>>^ Palavra que veio a Jeremias, da parte do SENHOR, dizendo:

[[v24-11-2]]

^<<v24-11-2,2>>^ Ouve as palavras desta aliança e fala aos homens de Judá e aos habitantes de Jerusalém;

[[v24-11-3]]

^<<v24-11-3,3>>^ dize-lhes: Assim diz o SENHOR, o Deus de Israel: Maldito o homem que não atentar para as palavras desta aliança,

[[v24-11-4]]

^<<v24-11-4,4>>^ que ordenei a vossos pais, no dia em que os tirei da terra do Egito, da fornalha de ferro, dizendo: dai ouvidos à minha voz e fazei tudo segundo o que vos mando; assim, vós me sereis a mim por povo, e eu vos serei a vós outros por Deus;

[[v24-11-5]]

^<<v24-11-5,5>>^ para que confirme o juramento que fiz a vossos pais de lhes dar uma terra que manasse leite e mel, como se vê neste dia. Então, eu respondi e disse: amém, ó SENHOR!

[[v24-11-6]]

^<<v24-11-6,6>>^ Tornou-me o SENHOR: Apregoa todas estas palavras nas cidades de Judá e nas ruas de Jerusalém, dizendo: Ouvi as palavras desta aliança e cumpri-as.

[[v24-11-7]]

^<<v24-11-7,7>>^ Porque, deveras, adverti a vossos pais, no dia em que os tirei da terra do Egito, até ao dia de hoje, testemunhando desde cedo cada dia, dizendo: dai ouvidos à minha voz.

[[v24-11-8]]

^<<v24-11-8,8>>^ Mas não atenderam, nem inclinaram o seu ouvido; antes, andaram, cada um, segundo a dureza do seu coração maligno; pelo que fiz cair sobre eles todas as ameaças desta aliança, a qual lhes ordenei que cumprissem, mas não cumpriram.

[[v24-11-9]]

^<<v24-11-9,9>>^ Disse-me ainda o SENHOR: Uma conspiração se achou entre os homens de Judá, entre os habitantes de Jerusalém.

[[v24-11-10]]

^<<v24-11-10,10>>^ Tornaram às maldades de seus primeiros pais, que recusaram ouvir as minhas palavras; andaram eles após outros deuses para os servir; a casa de Israel e a casa de Judá violaram a minha aliança, que eu fizera com seus pais.

[[v24-11-11]]

^<<v24-11-11,11>>^ Portanto, assim diz o SENHOR: Eis que trarei mal sobre eles, de que não poderão escapar; clamarão a mim, porém não os ouvirei.

[[v24-11-12]]

^<<v24-11-12,12>>^ Então, as cidades de Judá e os habitantes de Jerusalém irão aos deuses a quem eles queimaram incenso e a eles clamarão; porém estes, de nenhuma sorte, os livrarão do tempo do seu mal.

[[v24-11-13]]

^<<v24-11-13,13>>^ Porque, ó Judá, segundo o número das tuas cidades, são os teus deuses; segundo o número das ruas de Jerusalém, levantaste altares para vergonhosa coisa, isto é, para queimares incenso a Baal.

[[v24-11-14]]

^<<v24-11-14,14>>^ Tu, pois, não ores por este povo, nem levantes por eles clamor nem oração; porque não os ouvirei quando eles clamarem a mim, por causa do seu mal.

[[v24-11-15]]

^<<v24-11-15,15>>^ Que direito tem na minha casa a minha amada, ela que cometeu vilezas? Acaso, ó amada, votos e carnes sacrificadas poderão afastar de ti o mal? Então, saltarias de prazer.

[[v24-11-16]]

^<<v24-11-16,16>>^ O SENHOR te chamou de oliveira verde, formosa por seus deliciosos frutos; mas agora, à voz de grande tumulto, acendeu fogo ao redor dela e consumiu os seus ramos.

[[v24-11-17]]

^<<v24-11-17,17>>^ Porque o SENHOR dos Exércitos, que te plantou, pronunciou contra ti o mal, pela maldade que a casa de Israel e a casa de Judá para si mesmas fizeram, pois me provocaram à ira, queimando incenso a Baal.

[[v24-11-18]]

^<<v24-11-18,18>>^ O SENHOR mo fez saber, e eu o soube; então, me fizeste ver as suas maquinações.

[[v24-11-19]]

^<<v24-11-19,19>>^ Eu era como manso cordeiro, que é levado ao matadouro; porque eu não sabia que tramavam projetos contra mim, dizendo: Destruamos a árvore com seu fruto; a ele cortemo-lo da terra dos viventes, e não haja mais memória do seu nome.

[[v24-11-20]]

^<<v24-11-20,20>>^ Mas, ó SENHOR dos Exércitos, justo Juiz, que provas o mais íntimo do coração, veja eu a tua vingança sobre eles; pois a ti revelei a minha causa.

[[v24-11-21]]

^<<v24-11-21,21>>^ Portanto, assim diz o SENHOR acerca dos homens de Anatote que procuram a tua morte e dizem: Não profetizes em o nome do SENHOR, para que não morras às nossas mãos.

[[v24-11-22]]

^<<v24-11-22,22>>^ Sim, assim diz o SENHOR dos Exércitos: Eis que eu os punirei; os jovens morrerão à espada, os seus filhos e as suas filhas morrerão de fome.

[[v24-11-23]]

^<<v24-11-23,23>>^ E não haverá deles resto nenhum, porque farei vir o mal sobre os homens de Anatote, no ano da sua punição.

'''

xref:024-jeremias/024-jeremias-010.adoc#v24-10-0[&#60; Capítulo Anterior] | <<v24-11-0,Topo>> | xref:024-jeremias/024-jeremias-012.adoc#v24-12-0[Próximo Capítulo &#62;]