include::./index.adoc[]

[[v24-21-0]]
=== Jeremias, 21
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-21-1]]

^<<v24-21-1,1>>^ Palavra que veio a Jeremias da parte do SENHOR, quando o rei Zedequias lhe enviou Pasur, filho de Malquias, e o sacerdote Sofonias, filho de Maaseias, dizendo:

[[v24-21-2]]

^<<v24-21-2,2>>^ Pergunta agora por nós ao SENHOR, por que Nabucodonosor, rei da Babilônia, guerreia contra nós; bem pode ser que o SENHOR nos trate segundo todas as suas maravilhas e o faça retirar-se de nós.

[[v24-21-3]]

^<<v24-21-3,3>>^ Então, Jeremias lhes disse: Assim direis a Zedequias:

[[v24-21-4]]

^<<v24-21-4,4>>^ Assim diz o SENHOR, o Deus de Israel: Eis que farei retroceder as armas de guerra que estão nas vossas mãos, com que vós pelejais fora dos muros contra o rei da Babilônia e contra os caldeus, que vos oprimem; tais armas, eu as ajuntarei no meio desta cidade.

[[v24-21-5]]

^<<v24-21-5,5>>^ Pelejarei eu mesmo contra vós outros com braço estendido e mão poderosa, com ira, com indignação e grande furor.

[[v24-21-6]]

^<<v24-21-6,6>>^ Ferirei os habitantes desta cidade, tanto os homens como os animais; de grande pestilência morrerão.

[[v24-21-7]]

^<<v24-21-7,7>>^ Depois disto, diz o SENHOR, entregarei Zedequias, rei de Judá, e seus servos, e o povo, e quantos desta cidade restarem da pestilência, da espada e da fome na mão de Nabucodonosor, rei da Babilônia, na de seus inimigos e na dos que procuram tirar-lhes a vida; feri-los-á a fio de espada; não os poupará, não se compadecerá, nem terá misericórdia.

[[v24-21-8]]

^<<v24-21-8,8>>^ A este povo dirás: Assim diz o SENHOR: Eis que ponho diante de vós o caminho da vida e o caminho da morte.

[[v24-21-9]]

^<<v24-21-9,9>>^ O que ficar nesta cidade há de morrer à espada, ou à fome, ou de peste; mas o que sair e render-se aos caldeus, que vos cercam, viverá, e a vida lhe será como despojo.

[[v24-21-10]]

^<<v24-21-10,10>>^ Pois voltei o rosto contra esta cidade, para mal e não para bem, diz o SENHOR; ela será entregue nas mãos do rei da Babilônia, e este a queimará.

[[v24-21-11]]

^<<v24-21-11,11>>^ À casa do rei de Judá dirás: Ouvi a palavra do SENHOR!

[[v24-21-12]]

^<<v24-21-12,12>>^ Ó casa de Davi, assim diz o SENHOR: Julgai pela manhã justamente e livrai o oprimido das mãos do opressor; para que não seja o meu furor como fogo e se acenda, sem que haja quem o apague, por causa da maldade das vossas ações.

[[v24-21-13]]

^<<v24-21-13,13>>^ Eis que eu sou contra ti, ó Moradora do vale, ó Rocha da campina, diz o SENHOR; contra vós outros que dizeis: Quem descerá contra nós? Ou: Quem entrará nas nossas moradas?

[[v24-21-14]]

^<<v24-21-14,14>>^ Castigar-vos-ei segundo o fruto das vossas ações, diz o SENHOR; acenderei fogo na cidade, qual bosque, o qual devorará todos os seus arredores.

'''

xref:024-jeremias/024-jeremias-020.adoc#v24-20-0[&#60; Capítulo Anterior] | <<v24-21-0,Topo>> | xref:024-jeremias/024-jeremias-022.adoc#v24-22-0[Próximo Capítulo &#62;]