include::./index.adoc[]

[[v24-9-0]]
=== Jeremias, 9
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-9-1]]

^<<v24-9-1,1>>^ Prouvera a Deus a minha cabeça se tornasse em águas, e os meus olhos, em fonte de lágrimas! Então, choraria de dia e de noite os mortos da filha do meu povo.

[[v24-9-2]]

^<<v24-9-2,2>>^ Prouvera a Deus eu tivesse no deserto uma estalagem de caminhantes! Então, deixaria o meu povo e me apartaria dele, porque todos eles são adúlteros, são um bando de traidores;

[[v24-9-3]]

^<<v24-9-3,3>>^ curvam a língua, como se fosse o seu arco, para a mentira; fortalecem-se na terra, mas não para a verdade, porque avançam de malícia em malícia e não me conhecem, diz o SENHOR.

[[v24-9-4]]

^<<v24-9-4,4>>^ Guardai-vos cada um do seu amigo e de irmão nenhum vos fieis; porque todo irmão não faz mais do que enganar, e todo amigo anda caluniando.

[[v24-9-5]]

^<<v24-9-5,5>>^ Cada um zomba do seu próximo, e não falam a verdade; ensinam a sua língua a proferir mentiras; cansam-se de praticar a iniquidade.

[[v24-9-6]]

^<<v24-9-6,6>>^ Vivem no meio da falsidade; pela falsidade recusam conhecer-me, diz o SENHOR.

[[v24-9-7]]

^<<v24-9-7,7>>^ Portanto, assim diz o SENHOR dos Exércitos: Eis que eu os acrisolarei e os provarei; porque de que outra maneira procederia eu com a filha do meu povo?

[[v24-9-8]]

^<<v24-9-8,8>>^ Flecha mortífera é a língua deles; falam engano; com a boca fala cada um de paz com o seu companheiro, mas no seu interior lhe arma ciladas.

[[v24-9-9]]

^<<v24-9-9,9>>^ Acaso, por estas coisas não os castigaria? — diz o SENHOR; ou não me vingaria eu de nação tal como esta?

[[v24-9-10]]

^<<v24-9-10,10>>^ Pelos montes levantarei choro e pranto e pelas pastagens do deserto, lamentação; porque já estão queimadas, e ninguém passa por elas; já não se ouve ali o mugido de gado; tanto as aves dos céus como os animais fugiram e se foram.

[[v24-9-11]]

^<<v24-9-11,11>>^ Farei de Jerusalém montões de ruínas, morada de chacais; e das cidades de Judá farei uma assolação, de sorte que fiquem desabitadas.

[[v24-9-12]]

^<<v24-9-12,12>>^ Quem é o homem sábio, que entenda isto, e a quem falou a boca do SENHOR, homem que possa explicar por que razão pereceu a terra e se queimou como deserto, de sorte que ninguém passa por ela?

[[v24-9-13]]

^<<v24-9-13,13>>^ Respondeu o SENHOR: Porque deixaram a minha lei, que pus perante eles, e não deram ouvidos ao que eu disse, nem andaram nela.

[[v24-9-14]]

^<<v24-9-14,14>>^ Antes, andaram na dureza do seu coração e seguiram os baalins, como lhes ensinaram os seus pais.

[[v24-9-15]]

^<<v24-9-15,15>>^ Portanto, assim diz o SENHOR dos Exércitos, Deus de Israel: Eis que alimentarei este povo com absinto e lhe darei a beber água venenosa.

[[v24-9-16]]

^<<v24-9-16,16>>^ Espalhá-los-ei entre nações que nem eles nem seus pais conheceram; e enviarei a espada após eles, até que eu venha a consumi-los.

[[v24-9-17]]

^<<v24-9-17,17>>^ Assim diz o SENHOR dos Exércitos: Considerai e chamai carpideiras, para que venham; mandai procurar mulheres hábeis, para que venham.

[[v24-9-18]]

^<<v24-9-18,18>>^ Apressem-se e levantem sobre nós o seu lamento, para que os nossos olhos se desfaçam em lágrimas, e as nossas pálpebras destilem água.

[[v24-9-19]]

^<<v24-9-19,19>>^ Porque uma voz de pranto se ouve de Sião: Como estamos arruinados! Estamos sobremodo envergonhados, porque deixamos a terra, e eles transtornaram as nossas moradas.

[[v24-9-20]]

^<<v24-9-20,20>>^ Ouvi, pois, vós, mulheres, a palavra do SENHOR, e os vossos ouvidos recebam a palavra da sua boca; ensinai o pranto a vossas filhas; e, cada uma à sua companheira, a lamentação.

[[v24-9-21]]

^<<v24-9-21,21>>^ Porque a morte subiu pelas nossas janelas e entrou em nossos palácios; exterminou das ruas as crianças e os jovens, das praças.

[[v24-9-22]]

^<<v24-9-22,22>>^ Fala: Assim diz o SENHOR: Os cadáveres dos homens jazerão como esterco sobre o campo e cairão como gavela atrás do segador, e não há quem a recolha.

[[v24-9-23]]

^<<v24-9-23,23>>^ Assim diz o SENHOR: Não se glorie o sábio na sua sabedoria, nem o forte, na sua força, nem o rico, nas suas riquezas;

[[v24-9-24]]

^<<v24-9-24,24>>^ mas o que se gloriar, glorie-se nisto: em me conhecer e saber que eu sou o SENHOR e faço misericórdia, juízo e justiça na terra; porque destas coisas me agrado, diz o SENHOR.

[[v24-9-25]]

^<<v24-9-25,25>>^ Eis que vêm dias, diz o SENHOR, em que castigarei a todos os circuncidados juntamente com os incircuncisos:

[[v24-9-26]]

^<<v24-9-26,26>>^ ao Egito, e a Judá, e a Edom, e aos filhos de Amom, e a Moabe, e a todos os que cortam os cabelos nas têmporas e habitam no deserto; porque todas as nações são incircuncisas, e toda a casa de Israel é incircuncisa de coração.

'''

xref:024-jeremias/024-jeremias-008.adoc#v24-8-0[&#60; Capítulo Anterior] | <<v24-9-0,Topo>> | xref:024-jeremias/024-jeremias-010.adoc#v24-10-0[Próximo Capítulo &#62;]