include::./index.adoc[]

[[v24-4-0]]
=== Jeremias, 4
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-4-1]]

^<<v24-4-1,1>>^ Se voltares, ó Israel, diz o SENHOR, volta para mim; se removeres as tuas abominações de diante de mim, não mais andarás vagueando;

[[v24-4-2]]

^<<v24-4-2,2>>^ se jurares pela vida do SENHOR, em verdade, em juízo e em justiça, então, nele serão benditas as nações e nele se glorificarão.

[[v24-4-3]]

^<<v24-4-3,3>>^ Porque assim diz o SENHOR aos homens de Judá e Jerusalém: Lavrai para vós outros campo novo e não semeeis entre espinhos.

[[v24-4-4]]

^<<v24-4-4,4>>^ Circuncidai-vos para o SENHOR, circuncidai o vosso coração, ó homens de Judá e moradores de Jerusalém, para que o meu furor não saia como fogo e arda, e não haja quem o apague, por causa da malícia das vossas obras.

[[v24-4-5]]

^<<v24-4-5,5>>^ Anunciai em Judá, fazei ouvir em Jerusalém e dizei: Tocai a trombeta na terra! Gritai em alta voz, dizendo: Ajuntai-vos, e entremos nas cidades fortificadas!

[[v24-4-6]]

^<<v24-4-6,6>>^ Arvorai a bandeira rumo a Sião, fugi e não vos detenhais; porque eu faço vir do Norte um mal, uma grande destruição.

[[v24-4-7]]

^<<v24-4-7,7>>^ Já um leão subiu da sua ramada, um destruidor das nações; ele já partiu, já deixou o seu lugar para fazer da tua terra uma desolação, a fim de que as tuas cidades sejam destruídas, e ninguém as habite.

[[v24-4-8]]

^<<v24-4-8,8>>^ Cingi-vos, pois, de cilício, lamentai e uivai; porque a ira ardente do SENHOR não se desviou de nós.

[[v24-4-9]]

^<<v24-4-9,9>>^ Sucederá naquele dia, diz o SENHOR, que o rei e os príncipes perderão a coragem, os sacerdotes ficarão pasmados, e os profetas, estupefatos.

[[v24-4-10]]

^<<v24-4-10,10>>^ Então, disse eu: Ah! SENHOR Deus! Verdadeiramente, enganaste a este povo e a Jerusalém, dizendo: Tereis paz; e eis que a espada lhe penetra até à alma.

[[v24-4-11]]

^<<v24-4-11,11>>^ Naquele tempo, se dirá a este povo e a Jerusalém: Vento abrasador dos altos desnudos do ermo assopra diretamente à filha do meu povo, não para padejar nem para alimpar.

[[v24-4-12]]

^<<v24-4-12,12>>^ Vento mais forte do que este virá ainda de minha parte, e, então, também eu pronunciarei a sentença contra eles.

[[v24-4-13]]

^<<v24-4-13,13>>^ Eis aí que sobe o destruidor como nuvens; os seus carros, como tempestade; os seus cavalos são mais ligeiros do que as águias. Ai de nós! Estamos arruinados!

[[v24-4-14]]

^<<v24-4-14,14>>^ Lava o teu coração da malícia, ó Jerusalém, para que sejas salva! Até quando hospedarás contigo os teus maus pensamentos?

[[v24-4-15]]

^<<v24-4-15,15>>^ Uma voz se faz ouvir desde Dã e anuncia a calamidade desde a região montanhosa de Efraim!

[[v24-4-16]]

^<<v24-4-16,16>>^ Proclamai isto às nações, fazei-o ouvir contra Jerusalém: De uma terra longínqua vêm sitiadores e levantam a voz contra as cidades de Judá.

[[v24-4-17]]

^<<v24-4-17,17>>^ Como os guardas de um campo, eles cercam Jerusalém, porque ela se rebelou contra mim, diz o SENHOR.

[[v24-4-18]]

^<<v24-4-18,18>>^ O teu proceder e as tuas obras fizeram vir sobre ti estas coisas; a tua calamidade, que é amarga, atinge até o próprio coração.

[[v24-4-19]]

^<<v24-4-19,19>>^ Ah! Meu coração! Meu coração! Eu me contorço em dores. Oh! As paredes do meu coração! Meu coração se agita! Não posso calar-me, porque ouves, ó minha alma, o som da trombeta, o alarido de guerra.

[[v24-4-20]]

^<<v24-4-20,20>>^ Golpe sobre golpe se anuncia, pois a terra toda já está destruída; de súbito, foram destruídas as minhas tendas; num momento, as suas lonas.

[[v24-4-21]]

^<<v24-4-21,21>>^ Até quando terei de ver a bandeira, terei de ouvir a voz da trombeta?

[[v24-4-22]]

^<<v24-4-22,22>>^ Deveras, o meu povo está louco, já não me conhece; são filhos néscios e não inteligentes; são sábios para o mal e não sabem fazer o bem.

[[v24-4-23]]

^<<v24-4-23,23>>^ Olhei para a terra, e ei-la sem forma e vazia; para os céus, e não tinham luz.

[[v24-4-24]]

^<<v24-4-24,24>>^ Olhei para os montes, e eis que tremiam, e todos os outeiros estremeciam.

[[v24-4-25]]

^<<v24-4-25,25>>^ Olhei, e eis que não havia homem nenhum, e todas as aves dos céus haviam fugido.

[[v24-4-26]]

^<<v24-4-26,26>>^ Olhei ainda, e eis que a terra fértil era um deserto, e todas as suas cidades estavam derribadas diante do SENHOR, diante do furor da sua ira.

[[v24-4-27]]

^<<v24-4-27,27>>^ Pois assim diz o SENHOR: Toda a terra será assolada; porém não a consumirei de todo.

[[v24-4-28]]

^<<v24-4-28,28>>^ Por isso, a terra pranteará, e os céus acima se enegrecerão; porque falei, resolvi e não me arrependo, nem me retrato.

[[v24-4-29]]

^<<v24-4-29,29>>^ Ao clamor dos cavaleiros e dos flecheiros, fogem todas as cidades, entram pelas selvas e sobem pelos penhascos; todas as cidades ficam desamparadas, e já ninguém habita nelas.

[[v24-4-30]]

^<<v24-4-30,30>>^ Agora, pois, ó assolada, por que fazes assim, e te vestes de escarlata, e te adornas com enfeites de ouro, e alargas os olhos com pinturas, se debalde te fazes bela? Os amantes te desprezam e procuram tirar-te a vida.

[[v24-4-31]]

^<<v24-4-31,31>>^ Pois ouço uma voz, como de parturiente, uma angústia como da primípara em suas dores; a voz da filha de Sião, ofegante, que estende as mãos, dizendo: Ai de mim agora! Porque a minha alma desfalece por causa dos assassinos.

'''

xref:024-jeremias/024-jeremias-003.adoc#v24-3-0[&#60; Capítulo Anterior] | <<v24-4-0,Topo>> | xref:024-jeremias/024-jeremias-005.adoc#v24-5-0[Próximo Capítulo &#62;]