include::./index.adoc[]

[[v24-35-0]]
=== Jeremias, 35
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-35-1]]

^<<v24-35-1,1>>^ Palavra que do SENHOR veio a Jeremias, nos dias de Jeoaquim, filho de Josias, rei de Judá, dizendo:

[[v24-35-2]]

^<<v24-35-2,2>>^ Vai à casa dos recabitas, fala com eles, leva-os à Casa do SENHOR, a uma das câmaras, e dá-lhes vinho a beber.

[[v24-35-3]]

^<<v24-35-3,3>>^ Então, tomei a Jazanias, filho de Jeremias, filho de Habazinias, aos irmãos, e a todos os filhos dele, e a toda a casa dos recabitas;

[[v24-35-4]]

^<<v24-35-4,4>>^ e os levei à Casa do SENHOR, à câmara dos filhos de Hanã, filho de Jigdalias, homem de Deus, que está junto à câmara dos príncipes e sobre a de Maaseias, filho de Salum, guarda do vestíbulo;

[[v24-35-5]]

^<<v24-35-5,5>>^ e pus diante dos filhos da casa dos recabitas taças cheias de vinho e copos e lhes disse: Bebei vinho.

[[v24-35-6]]

^<<v24-35-6,6>>^ Mas eles disseram: Não beberemos vinho, porque Jonadabe, filho de Recabe, nosso pai, nos ordenou: Nunca jamais bebereis vinho, nem vós nem vossos filhos;

[[v24-35-7]]

^<<v24-35-7,7>>^ não edificareis casa, não fareis sementeiras, não plantareis, nem possuireis vinha alguma; mas habitareis em tendas todos os vossos dias, para que vivais muitos dias sobre a terra em que viveis peregrinando.

[[v24-35-8]]

^<<v24-35-8,8>>^ Obedecemos, pois, à voz de Jonadabe, filho de Recabe, nosso pai, em tudo quanto nos ordenou; de maneira que não bebemos vinho em todos os nossos dias, nem nós, nem nossas mulheres, nem nossos filhos, nem nossas filhas;

[[v24-35-9]]

^<<v24-35-9,9>>^ nem edificamos casas para nossa habitação; não temos vinha, nem campo, nem semente.

[[v24-35-10]]

^<<v24-35-10,10>>^ Mas habitamos em tendas, e, assim, obedecemos, e tudo fizemos segundo nos ordenou Jonadabe, nosso pai.

[[v24-35-11]]

^<<v24-35-11,11>>^ Quando, porém, Nabucodonosor, rei da Babilônia, subia a esta terra, dissemos: Vinde, e refugiemo-nos em Jerusalém, por causa do exército dos caldeus e dos siros; e assim ficamos em Jerusalém.

[[v24-35-12]]

^<<v24-35-12,12>>^ Então, veio a palavra do SENHOR a Jeremias, dizendo:

[[v24-35-13]]

^<<v24-35-13,13>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel: Vai e dize aos homens de Judá e aos moradores de Jerusalém: Acaso, nunca aceitareis a minha advertência para obedecerdes às minhas palavras? — diz o SENHOR.

[[v24-35-14]]

^<<v24-35-14,14>>^ As palavras de Jonadabe, filho de Recabe, que ordenou a seus filhos não bebessem vinho, foram guardadas; pois, até ao dia de hoje, não beberam; antes, obedecem às ordens de seu pai; a mim, porém, que, começando de madrugada, vos tenho falado, não me obedecestes.

[[v24-35-15]]

^<<v24-35-15,15>>^ Começando de madrugada, vos tenho enviado todos os meus servos, dizendo: Convertei-vos agora, cada um do seu mau caminho, fazei boas as vossas ações e não sigais a outros deuses para servi-los; assim ficareis na terra que vos dei a vós outros e a vossos pais; mas não me inclinastes os ouvidos, nem me obedecestes a mim.

[[v24-35-16]]

^<<v24-35-16,16>>^ Visto que os filhos de Jonadabe, filho de Recabe, guardaram o mandamento de seu pai, que ele lhes ordenara, mas este povo não me obedeceu,

[[v24-35-17]]

^<<v24-35-17,17>>^ por isso, assim diz o SENHOR, o Deus dos Exércitos, o Deus de Israel: Eis que trarei sobre Judá e sobre todos os moradores de Jerusalém todo o mal que falei contra eles; pois lhes tenho falado, e não me obedeceram, clamei a eles, e não responderam.

[[v24-35-18]]

^<<v24-35-18,18>>^ À casa dos recabitas disse Jeremias: Assim diz o SENHOR dos Exércitos, o Deus de Israel: Pois que obedecestes ao mandamento de Jonadabe, vosso pai, e guardastes todos os seus preceitos, e tudo fizestes segundo vos ordenou,

[[v24-35-19]]

^<<v24-35-19,19>>^ por isso, assim diz o SENHOR dos Exércitos, o Deus de Israel: Nunca faltará homem a Jonadabe, filho de Recabe, que esteja na minha presença.

'''

xref:024-jeremias/024-jeremias-034.adoc#v24-34-0[&#60; Capítulo Anterior] | <<v24-35-0,Topo>> | xref:024-jeremias/024-jeremias-036.adoc#v24-36-0[Próximo Capítulo &#62;]