include::./index.adoc[]

[[v24-3-0]]
=== Jeremias, 3
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-3-1]]

^<<v24-3-1,1>>^ Se um homem repudiar sua mulher, e ela o deixar e tomar outro marido, porventura, aquele tornará a ela? Não se poluiria com isso de todo aquela terra? Ora, tu te prostituíste com muitos amantes; mas, ainda assim, torna para mim, diz o SENHOR.

[[v24-3-2]]

^<<v24-3-2,2>>^ Levanta os olhos aos altos desnudos e vê; onde não te prostituíste? Nos caminhos te assentavas à espera deles como o arábio no deserto; assim, poluíste a terra com as tuas devassidões e com a tua malícia.

[[v24-3-3]]

^<<v24-3-3,3>>^ Pelo que foram retiradas as chuvas, e não houve chuva serôdia; mas tu tens a fronte de prostituta e não queres ter vergonha.

[[v24-3-4]]

^<<v24-3-4,4>>^ Não é fato que agora mesmo tu me invocas, dizendo: Pai meu, tu és o amigo da minha mocidade?

[[v24-3-5]]

^<<v24-3-5,5>>^ Conservarás para sempre a tua ira? Ou a reterás até ao fim? Sim, assim me falas, mas cometes maldade a mais não poder.

[[v24-3-6]]

^<<v24-3-6,6>>^ Disse mais o SENHOR nos dias do rei Josias: Viste o que fez a pérfida Israel? Foi a todo monte alto e debaixo de toda árvore frondosa e se deu ali a toda prostituição.

[[v24-3-7]]

^<<v24-3-7,7>>^ E, depois de ela ter feito tudo isso, eu pensei que ela voltaria para mim, mas não voltou. A sua pérfida irmã Judá viu isto.

[[v24-3-8]]

^<<v24-3-8,8>>^ Quando, por causa de tudo isto, por ter cometido adultério, eu despedi a pérfida Israel e lhe dei carta de divórcio, vi que a falsa Judá, sua irmã, não temeu; mas ela mesma se foi e se deu à prostituição.

[[v24-3-9]]

^<<v24-3-9,9>>^ Sucedeu que, pelo ruidoso da sua prostituição, poluiu ela a terra; porque adulterou, adorando pedras e árvores.

[[v24-3-10]]

^<<v24-3-10,10>>^ Apesar de tudo isso, não voltou de todo o coração para mim a sua falsa irmã Judá, mas fingidamente, diz o SENHOR.

[[v24-3-11]]

^<<v24-3-11,11>>^ Disse-me o SENHOR: Já a pérfida Israel se mostrou mais justa do que a falsa Judá.

[[v24-3-12]]

^<<v24-3-12,12>>^ Vai, pois, e apregoa estas palavras para o lado do Norte e dize: Volta, ó pérfida Israel, diz o SENHOR, e não farei cair a minha ira sobre ti, porque eu sou compassivo, diz o SENHOR, e não manterei para sempre a minha ira.

[[v24-3-13]]

^<<v24-3-13,13>>^ Tão somente reconhece a tua iniquidade, reconhece que transgrediste contra o SENHOR, teu Deus, e te prostituíste com os estranhos debaixo de toda árvore frondosa e não deste ouvidos à minha voz, diz o SENHOR.

[[v24-3-14]]

^<<v24-3-14,14>>^ Convertei-vos, ó filhos rebeldes, diz o SENHOR; porque eu sou o vosso esposo e vos tomarei, um de cada cidade e dois de cada família, e vos levarei a Sião.

[[v24-3-15]]

^<<v24-3-15,15>>^ Dar-vos-ei pastores segundo o meu coração, que vos apascentem com conhecimento e com inteligência.

[[v24-3-16]]

^<<v24-3-16,16>>^ Sucederá que, quando vos multiplicardes e vos tornardes fecundos na terra, então, diz o SENHOR, nunca mais se exclamará: A arca da Aliança do SENHOR! Ela não lhes virá à mente, não se lembrarão dela nem dela sentirão falta; e não se fará outra.

[[v24-3-17]]

^<<v24-3-17,17>>^ Naquele tempo, chamarão a Jerusalém de Trono do SENHOR; nela se reunirão todas as nações em nome do SENHOR e já não andarão segundo a dureza do seu coração maligno.

[[v24-3-18]]

^<<v24-3-18,18>>^ Naqueles dias, andará a casa de Judá com a casa de Israel, e virão juntas da terra do Norte para a terra que dei em herança a vossos pais.

[[v24-3-19]]

^<<v24-3-19,19>>^ Mas eu a mim me perguntava: como te porei entre os filhos e te darei a terra desejável, a mais formosa herança das nações? E respondi: Pai me chamarás e de mim não te desviarás.

[[v24-3-20]]

^<<v24-3-20,20>>^ Deveras, como a mulher se aparta perfidamente do seu marido, assim com perfídia te houveste comigo, ó casa de Israel, diz o SENHOR.

[[v24-3-21]]

^<<v24-3-21,21>>^ Nos lugares altos, se ouviu uma voz, pranto e súplicas dos filhos de Israel; porquanto perverteram o seu caminho e se esqueceram do SENHOR, seu Deus.

[[v24-3-22]]

^<<v24-3-22,22>>^ Voltai, ó filhos rebeldes, eu curarei as vossas rebeliões. Eis-nos aqui, vimos ter contigo; porque tu és o SENHOR, nosso Deus.

[[v24-3-23]]

^<<v24-3-23,23>>^ Na verdade, os outeiros não passam de ilusão, nem as orgias das montanhas; com efeito, no SENHOR, nosso Deus, está a salvação de Israel.

[[v24-3-24]]

^<<v24-3-24,24>>^ Mas a coisa vergonhosa devorou o labor de nossos pais, desde a nossa mocidade: as suas ovelhas e o seu gado, os seus filhos e as suas filhas.

[[v24-3-25]]

^<<v24-3-25,25>>^ Deitemo-nos em nossa vergonha, e cubra-nos a nossa ignomínia, porque temos pecado contra o SENHOR, nosso Deus, nós e nossos pais, desde a nossa mocidade até ao dia de hoje; e não demos ouvidos à voz do SENHOR, nosso Deus.

'''

xref:024-jeremias/024-jeremias-002.adoc#v24-2-0[&#60; Capítulo Anterior] | <<v24-3-0,Topo>> | xref:024-jeremias/024-jeremias-004.adoc#v24-4-0[Próximo Capítulo &#62;]