include::./index.adoc[]

[[v24-20-0]]
=== Jeremias, 20
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-20-1]]

^<<v24-20-1,1>>^ Pasur, filho do sacerdote Imer, que era presidente na Casa do SENHOR, ouviu a Jeremias profetizando estas coisas.

[[v24-20-2]]

^<<v24-20-2,2>>^ Então, feriu Pasur ao profeta Jeremias e o meteu no tronco que estava na porta superior de Benjamim, na Casa do SENHOR. No dia seguinte, Pasur tirou a Jeremias do tronco.

[[v24-20-3]]

^<<v24-20-3,3>>^ Então, lhe disse Jeremias: O SENHOR já não te chama Pasur, e sim Terror-Por-Todos-Os-Lados.

[[v24-20-4]]

^<<v24-20-4,4>>^ Pois assim diz o SENHOR: Eis que te farei ser terror para ti mesmo e para todos os teus amigos; estes cairão à espada de seus inimigos, e teus olhos o verão; todo o Judá entregarei nas mãos do rei da Babilônia; este os levará presos à Babilônia e feri-los-á à espada.

[[v24-20-5]]

^<<v24-20-5,5>>^ Também entregarei toda a riqueza desta cidade, todo o fruto do seu trabalho e todas as suas coisas preciosas; sim, todos os tesouros dos reis de Judá entregarei nas mãos de seus inimigos, os quais hão de saqueá-los, tomá-los e levá-los à Babilônia.

[[v24-20-6]]

^<<v24-20-6,6>>^ E tu, Pasur, e todos os moradores da tua casa ireis para o cativeiro; irás à Babilônia, onde morrerás e serás sepultado, tu e todos os teus amigos, aos quais profetizaste falsamente.

[[v24-20-7]]

^<<v24-20-7,7>>^ Persuadiste-me, ó SENHOR, e persuadido fiquei; mais forte foste do que eu e prevaleceste; sirvo de escárnio todo o dia; cada um deles zomba de mim.

[[v24-20-8]]

^<<v24-20-8,8>>^ Porque, sempre que falo, tenho de gritar e clamar: Violência e destruição! Porque a palavra do SENHOR se me tornou um opróbrio e ludíbrio todo o dia.

[[v24-20-9]]

^<<v24-20-9,9>>^ Quando pensei: não me lembrarei dele e já não falarei no seu nome, então, isso me foi no coração como fogo ardente, encerrado nos meus ossos; já desfaleço de sofrer e não posso mais.

[[v24-20-10]]

^<<v24-20-10,10>>^ Porque ouvi a murmuração de muitos: Há terror por todos os lados! Denunciai, e o denunciaremos! Todos os meus íntimos amigos que aguardam de mim que eu tropece dizem: Bem pode ser que se deixe persuadir; então, prevaleceremos contra ele e dele nos vingaremos.

[[v24-20-11]]

^<<v24-20-11,11>>^ Mas o SENHOR está comigo como um poderoso guerreiro; por isso, tropeçarão os meus perseguidores e não prevalecerão; serão sobremodo envergonhados; e, porque não se houveram sabiamente, sofrerão afronta perpétua, que jamais se esquecerá.

[[v24-20-12]]

^<<v24-20-12,12>>^ Tu, pois, ó SENHOR dos Exércitos, que provas o justo e esquadrinhas os afetos e o coração, permite veja eu a tua vingança contra eles, pois te confiei a minha causa.

[[v24-20-13]]

^<<v24-20-13,13>>^ Cantai ao SENHOR, louvai ao SENHOR; pois livrou a alma do necessitado das mãos dos malfeitores.

[[v24-20-14]]

^<<v24-20-14,14>>^ Maldito o dia em que nasci! Não seja bendito o dia em que me deu à luz minha mãe!

[[v24-20-15]]

^<<v24-20-15,15>>^ Maldito o homem que deu as novas a meu pai, dizendo: Nasceu-te um filho!, alegrando-o com isso grandemente.

[[v24-20-16]]

^<<v24-20-16,16>>^ Seja esse homem como as cidades que o SENHOR, sem ter compaixão, destruiu; ouça ele clamor pela manhã e ao meio-dia, alarido.

[[v24-20-17]]

^<<v24-20-17,17>>^ Por que não me matou Deus no ventre materno? Por que minha mãe não foi minha sepultura? Ou não permaneceu grávida perpetuamente?

[[v24-20-18]]

^<<v24-20-18,18>>^ Por que saí do ventre materno tão somente para ver trabalho e tristeza e para que se consumam de vergonha os meus dias?

'''

xref:024-jeremias/024-jeremias-019.adoc#v24-19-0[&#60; Capítulo Anterior] | <<v24-20-0,Topo>> | xref:024-jeremias/024-jeremias-021.adoc#v24-21-0[Próximo Capítulo &#62;]