include::./index.adoc[]

[[v24-30-0]]
=== Jeremias, 30
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-30-1]]

^<<v24-30-1,1>>^ Palavra que do SENHOR veio a Jeremias, dizendo:

[[v24-30-2]]

^<<v24-30-2,2>>^ Assim fala o SENHOR, Deus de Israel: Escreve num livro todas as palavras que eu disse.

[[v24-30-3]]

^<<v24-30-3,3>>^ Porque eis que vêm dias, diz o SENHOR, em que mudarei a sorte do meu povo de Israel e de Judá, diz o SENHOR; fá-los-ei voltar para a terra que dei a seus pais, e a possuirão.

[[v24-30-4]]

^<<v24-30-4,4>>^ São estas as palavras que disse o SENHOR acerca de Israel e de Judá:

[[v24-30-5]]

^<<v24-30-5,5>>^ Assim diz o SENHOR: Ouvimos uma voz de tremor e de temor e não de paz.

[[v24-30-6]]

^<<v24-30-6,6>>^ Perguntai, pois, e vede se, acaso, um homem tem dores de parto. Por que vejo, pois, a cada homem com as mãos na cintura, como a que está dando à luz? E por que se tornaram pálidos todos os rostos?

[[v24-30-7]]

^<<v24-30-7,7>>^ Ah! Que grande é aquele dia, e não há outro semelhante! É tempo de angústia para Jacó; ele, porém, será livre dela.

[[v24-30-8]]

^<<v24-30-8,8>>^ Naquele dia, diz o SENHOR dos Exércitos, eu quebrarei o seu jugo de sobre o teu pescoço e quebrarei os teus canzis; e nunca mais estrangeiros farão escravo este povo,

[[v24-30-9]]

^<<v24-30-9,9>>^ que servirá ao SENHOR, seu Deus, como também a Davi, seu rei, que lhe levantarei.

[[v24-30-10]]

^<<v24-30-10,10>>^ Não temas, pois, servo meu, Jacó, diz o SENHOR, nem te espantes, ó Israel; pois eis que te livrarei das terras de longe e à tua descendência, da terra do exílio; Jacó voltará e ficará tranquilo e em sossego; e não haverá quem o atemorize.

[[v24-30-11]]

^<<v24-30-11,11>>^ Porque eu sou contigo, diz o SENHOR, para salvar-te; por isso, darei cabo de todas as nações entre as quais te espalhei; de ti, porém, não darei cabo, mas castigar-te-ei em justa medida e de todo não te inocentarei.

[[v24-30-12]]

^<<v24-30-12,12>>^ Porque assim diz o SENHOR: Teu mal é incurável, a tua chaga é dolorosa.

[[v24-30-13]]

^<<v24-30-13,13>>^ Não há quem defenda a tua causa; para a tua ferida não tens remédios nem emplasto.

[[v24-30-14]]

^<<v24-30-14,14>>^ Todos os teus amantes se esqueceram de ti, já não perguntam por ti; porque te feri com ferida de inimigo e com castigo de cruel, por causa da grandeza da tua maldade e da multidão de teus pecados.

[[v24-30-15]]

^<<v24-30-15,15>>^ Por que gritas por motivo da tua ferida? Tua dor é incurável. Por causa da grandeza de tua maldade e da multidão de teus pecados é que eu fiz estas coisas.

[[v24-30-16]]

^<<v24-30-16,16>>^ Por isso, todos os que te devoram serão devorados; e todos os teus adversários serão levados, cada um deles para o cativeiro; os que te despojam serão despojados, e entregarei ao saque todos os que te saqueiam.

[[v24-30-17]]

^<<v24-30-17,17>>^ Porque te restaurarei a saúde e curarei as tuas chagas, diz o SENHOR; pois te chamaram a repudiada, dizendo: É Sião, já ninguém pergunta por ela.

[[v24-30-18]]

^<<v24-30-18,18>>^ Assim diz o SENHOR: Eis que restaurarei a sorte das tendas de Jacó e me compadecerei das suas moradas; a cidade será reedificada sobre o seu montão de ruínas, e o palácio será habitado como outrora.

[[v24-30-19]]

^<<v24-30-19,19>>^ Sairão deles ações de graças e o júbilo dos que se alegram. Multiplicá-los-ei, e não serão diminuídos; glorificá-los-ei, e não serão apoucados.

[[v24-30-20]]

^<<v24-30-20,20>>^ Seus filhos serão como na antiguidade, e a sua congregação será firmada diante de mim, e castigarei todos os seus opressores.

[[v24-30-21]]

^<<v24-30-21,21>>^ O seu príncipe procederá deles, do meio deles sairá o que há de reinar; fá-lo-ei aproximar, e ele se chegará a mim; pois quem de si mesmo ousaria aproximar-se de mim? — diz o SENHOR.

[[v24-30-22]]

^<<v24-30-22,22>>^ Vós sereis o meu povo, eu serei o vosso Deus.

[[v24-30-23]]

^<<v24-30-23,23>>^ Eis a tempestade do SENHOR! O furor saiu, e um redemoinho tempestuou sobre a cabeça dos perversos.

[[v24-30-24]]

^<<v24-30-24,24>>^ Não voltará atrás o brasume da ira do SENHOR, até que tenha executado e cumprido os desígnios do seu coração. Nos últimos dias, entendereis isto.

'''

xref:024-jeremias/024-jeremias-029.adoc#v24-29-0[&#60; Capítulo Anterior] | <<v24-30-0,Topo>> | xref:024-jeremias/024-jeremias-031.adoc#v24-31-0[Próximo Capítulo &#62;]