include::./index.adoc[]

[[v24-31-0]]
=== Jeremias, 31
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-31-1]]

^<<v24-31-1,1>>^ Naquele tempo, diz o SENHOR, serei o Deus de todas as tribos de Israel, e elas serão o meu povo.

[[v24-31-2]]

^<<v24-31-2,2>>^ Assim diz o SENHOR: O povo que se livrou da espada logrou graça no deserto. Eu irei e darei descanso a Israel.

[[v24-31-3]]

^<<v24-31-3,3>>^ De longe se me deixou ver o SENHOR, dizendo: Com amor eterno eu te amei; por isso, com benignidade te atraí.

[[v24-31-4]]

^<<v24-31-4,4>>^ Ainda te edificarei, e serás edificada, ó virgem de Israel! Ainda serás adornada com os teus adufes e sairás com o coro dos que dançam.

[[v24-31-5]]

^<<v24-31-5,5>>^ Ainda plantarás vinhas nos montes de Samaria; plantarão os plantadores e gozarão dos frutos.

[[v24-31-6]]

^<<v24-31-6,6>>^ Porque haverá um dia em que gritarão os atalaias na região montanhosa de Efraim: Levantai-vos, e subamos a Sião, ao SENHOR, nosso Deus!

[[v24-31-7]]

^<<v24-31-7,7>>^ Porque assim diz o SENHOR: Cantai com alegria a Jacó, exultai por causa da cabeça das nações; proclamai, cantai louvores e dizei: Salva, SENHOR, o teu povo, o restante de Israel.

[[v24-31-8]]

^<<v24-31-8,8>>^ Eis que os trarei da terra do Norte e os congregarei das extremidades da terra; e, entre eles, também os cegos e aleijados, as mulheres grávidas e as de parto; em grande congregação, voltarão para aqui.

[[v24-31-9]]

^<<v24-31-9,9>>^ Virão com choro, e com súplicas os levarei; guiá-los-ei aos ribeiros de águas, por caminho reto em que não tropeçarão; porque sou pai para Israel, e Efraim é o meu primogênito.

[[v24-31-10]]

^<<v24-31-10,10>>^ Ouvi a palavra do SENHOR, ó nações, e anunciai nas terras longínquas do mar, e dizei: Aquele que espalhou a Israel o congregará e o guardará, como o pastor, ao seu rebanho.

[[v24-31-11]]

^<<v24-31-11,11>>^ Porque o SENHOR redimiu a Jacó e o livrou da mão do que era mais forte do que ele.

[[v24-31-12]]

^<<v24-31-12,12>>^ Hão de vir e exultar na altura de Sião, radiantes de alegria por causa dos bens do SENHOR, do cereal, do vinho, do azeite, dos cordeiros e dos bezerros; a sua alma será como um jardim regado, e nunca mais desfalecerão.

[[v24-31-13]]

^<<v24-31-13,13>>^ Então, a virgem se alegrará na dança, e também os jovens e os velhos; tornarei o seu pranto em júbilo e os consolarei; transformarei em regozijo a sua tristeza.

[[v24-31-14]]

^<<v24-31-14,14>>^ Saciarei de gordura a alma dos sacerdotes, e o meu povo se fartará com a minha bondade, diz o SENHOR.

[[v24-31-15]]

^<<v24-31-15,15>>^ Assim diz o SENHOR: Ouviu-se um clamor em Ramá, pranto e grande lamento; era Raquel chorando por seus filhos e inconsolável por causa deles, porque já não existem.

[[v24-31-16]]

^<<v24-31-16,16>>^ Assim diz o SENHOR: Reprime a tua voz de choro e as lágrimas de teus olhos; porque há recompensa para as tuas obras, diz o SENHOR, pois os teus filhos voltarão da terra do inimigo.

[[v24-31-17]]

^<<v24-31-17,17>>^ Há esperança para o teu futuro, diz o SENHOR, porque teus filhos voltarão para os seus territórios.

[[v24-31-18]]

^<<v24-31-18,18>>^ Bem ouvi que Efraim se queixava, dizendo: Castigaste-me, e fui castigado como novilho ainda não domado; converte-me, e serei convertido, porque tu és o SENHOR, meu Deus.

[[v24-31-19]]

^<<v24-31-19,19>>^ Na verdade, depois que me converti, arrependi-me; depois que fui instruído, bati no peito; fiquei envergonhado, confuso, porque levei o opróbrio da minha mocidade.

[[v24-31-20]]

^<<v24-31-20,20>>^ Não é Efraim meu precioso filho, filho das minhas delícias? Pois tantas vezes quantas falo contra ele, tantas vezes ternamente me lembro dele; comove-se por ele o meu coração, deveras me compadecerei dele, diz o SENHOR.

[[v24-31-21]]

^<<v24-31-21,21>>^ Põe-te marcos, finca postes que te guiem, presta atenção na vereda, no caminho por onde passaste; regressa, ó virgem de Israel, regressa às tuas cidades.

[[v24-31-22]]

^<<v24-31-22,22>>^ Até quando andarás errante, ó filha rebelde? Porque o SENHOR criou coisa nova na terra: a mulher infiel virá a requestar um homem.

[[v24-31-23]]

^<<v24-31-23,23>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel: Ainda dirão esta palavra na terra de Judá e nas suas cidades, quando eu lhe restaurar a sorte: O SENHOR te abençoe, ó morada de justiça, ó santo monte!

[[v24-31-24]]

^<<v24-31-24,24>>^ Nela, habitarão Judá e todas as suas cidades juntamente, como também os lavradores e os que pastoreiam os rebanhos.

[[v24-31-25]]

^<<v24-31-25,25>>^ Porque satisfiz à alma cansada, e saciei a toda alma desfalecida.

[[v24-31-26]]

^<<v24-31-26,26>>^ Nisto, despertei e olhei; e o meu sono fora doce para mim.

[[v24-31-27]]

^<<v24-31-27,27>>^ Eis que vêm dias, diz o SENHOR, em que semearei a casa de Israel e a casa de Judá com a semente de homens e de animais.

[[v24-31-28]]

^<<v24-31-28,28>>^ Como velei sobre eles, para arrancar, para derribar, para subverter, para destruir e para afligir, assim velarei sobre eles para edificar e para plantar, diz o SENHOR.

[[v24-31-29]]

^<<v24-31-29,29>>^ Naqueles dias, já não dirão: Os pais comeram uvas verdes, e os dentes dos filhos é que se embotaram.

[[v24-31-30]]

^<<v24-31-30,30>>^ Cada um, porém, será morto pela sua iniquidade; de todo homem que comer uvas verdes os dentes se embotarão.

[[v24-31-31]]

^<<v24-31-31,31>>^ Eis aí vêm dias, diz o SENHOR, em que firmarei nova aliança com a casa de Israel e com a casa de Judá.

[[v24-31-32]]

^<<v24-31-32,32>>^ Não conforme a aliança que fiz com seus pais, no dia em que os tomei pela mão, para os tirar da terra do Egito; porquanto eles anularam a minha aliança, não obstante eu os haver desposado, diz o SENHOR.

[[v24-31-33]]

^<<v24-31-33,33>>^ Porque esta é a aliança que firmarei com a casa de Israel, depois daqueles dias, diz o SENHOR: Na mente, lhes imprimirei as minhas leis, também no coração lhas inscreverei; eu serei o seu Deus, e eles serão o meu povo.

[[v24-31-34]]

^<<v24-31-34,34>>^ Não ensinará jamais cada um ao seu próximo, nem cada um ao seu irmão, dizendo: Conhece ao SENHOR, porque todos me conhecerão, desde o menor até ao maior deles, diz o SENHOR. Pois perdoarei as suas iniquidades e dos seus pecados jamais me lembrarei.

[[v24-31-35]]

^<<v24-31-35,35>>^ Assim diz o SENHOR, que dá o sol para a luz do dia e as leis fixas à lua e às estrelas para a luz da noite, que agita o mar e faz bramir as suas ondas; SENHOR dos Exércitos é o seu nome.

[[v24-31-36]]

^<<v24-31-36,36>>^ Se falharem estas leis fixas diante de mim, diz o SENHOR, deixará também a descendência de Israel de ser uma nação diante de mim para sempre.

[[v24-31-37]]

^<<v24-31-37,37>>^ Assim diz o SENHOR: Se puderem ser medidos os céus lá em cima e sondados os fundamentos da terra cá embaixo, também eu rejeitarei toda a descendência de Israel, por tudo quanto fizeram, diz o SENHOR.

[[v24-31-38]]

^<<v24-31-38,38>>^ Eis que vêm dias, diz o SENHOR, em que esta cidade será reedificada para o SENHOR, desde a Torre de Hananel até à Porta da Esquina.

[[v24-31-39]]

^<<v24-31-39,39>>^ O cordel de medir estender-se-á para diante, até ao outeiro de Garebe, e virar-se-á para Goa.

[[v24-31-40]]

^<<v24-31-40,40>>^ Todo o vale dos cadáveres e da cinza e todos os campos até ao ribeiro Cedrom, até à esquina da Porta dos Cavalos para o oriente, serão consagrados ao SENHOR. Esta Jerusalém jamais será desarraigada ou destruída.

'''

xref:024-jeremias/024-jeremias-030.adoc#v24-30-0[&#60; Capítulo Anterior] | <<v24-31-0,Topo>> | xref:024-jeremias/024-jeremias-032.adoc#v24-32-0[Próximo Capítulo &#62;]