include::./index.adoc[]

[[v24-33-0]]
=== Jeremias, 33
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-33-1]]

^<<v24-33-1,1>>^ Veio a palavra do SENHOR a Jeremias, segunda vez, estando ele ainda encarcerado no pátio da guarda, dizendo:

[[v24-33-2]]

^<<v24-33-2,2>>^ Assim diz o SENHOR que faz estas coisas, o SENHOR que as forma para as estabelecer ( SENHOR é o seu nome):

[[v24-33-3]]

^<<v24-33-3,3>>^ Invoca-me, e te responderei; anunciar-te-ei coisas grandes e ocultas, que não sabes.

[[v24-33-4]]

^<<v24-33-4,4>>^ Porque assim diz o SENHOR, o Deus de Israel, a respeito das casas desta cidade e das casas dos reis de Judá, que foram derribadas para a defesa contra as trincheiras e a espada:

[[v24-33-5]]

^<<v24-33-5,5>>^ Quando se der a peleja contra os caldeus, para que eu as encha de cadáveres de homens, feridos por minha ira e meu furor, porquanto desta cidade escondi o meu rosto, por causa de toda a sua maldade,

[[v24-33-6]]

^<<v24-33-6,6>>^ eis que lhe trarei a ela saúde e cura e os sararei; e lhes revelarei abundância de paz e segurança.

[[v24-33-7]]

^<<v24-33-7,7>>^ Restaurarei a sorte de Judá e de Israel e os edificarei como no princípio.

[[v24-33-8]]

^<<v24-33-8,8>>^ Purificá-los-ei de toda a sua iniquidade com que pecaram contra mim; e perdoarei todas as suas iniquidades com que pecaram e transgrediram contra mim.

[[v24-33-9]]

^<<v24-33-9,9>>^ Jerusalém me servirá por nome, por louvor e glória, entre todas as nações da terra que ouvirem todo o bem que eu lhe faço; espantar-se-ão e tremerão por causa de todo o bem e por causa de toda a paz que eu lhe dou.

[[v24-33-10]]

^<<v24-33-10,10>>^ Assim diz o SENHOR: Neste lugar, que vós dizeis que está deserto, sem homens nem animais, nas cidades de Judá e nas ruas de Jerusalém, que estão assoladas, sem homens, sem moradores e sem animais, ainda se ouvirá

[[v24-33-11]]

^<<v24-33-11,11>>^ a voz de júbilo e de alegria, e a voz de noivo, e a de noiva, e a voz dos que cantam: Rendei graças ao SENHOR dos Exércitos, porque ele é bom, porque a sua misericórdia dura para sempre; e dos que trazem ofertas de ações de graças à Casa do SENHOR; porque restaurarei a sorte da terra como no princípio, diz o SENHOR.

[[v24-33-12]]

^<<v24-33-12,12>>^ Assim diz o SENHOR dos Exércitos: Ainda neste lugar, que está deserto, sem homens e sem animais, e em todas as suas cidades, haverá morada de pastores que façam repousar aos seus rebanhos.

[[v24-33-13]]

^<<v24-33-13,13>>^ Nas cidades da região montanhosa, e nas cidades das planícies, e nas cidades do Sul, na terra de Benjamim, e nos contornos de Jerusalém, e nas cidades de Judá, ainda passarão os rebanhos pelas mãos de quem os conte, diz o SENHOR.

[[v24-33-14]]

^<<v24-33-14,14>>^ Eis que vêm dias, diz o SENHOR, em que cumprirei a boa palavra que proferi à casa de Israel e à casa de Judá.

[[v24-33-15]]

^<<v24-33-15,15>>^ Naqueles dias e naquele tempo, farei brotar a Davi um Renovo de justiça; ele executará juízo e justiça na terra.

[[v24-33-16]]

^<<v24-33-16,16>>^ Naqueles dias, Judá será salvo e Jerusalém habitará seguramente; ela será chamada SENHOR, Justiça Nossa.

[[v24-33-17]]

^<<v24-33-17,17>>^ Porque assim diz o SENHOR: Nunca faltará a Davi homem que se assente no trono da casa de Israel;

[[v24-33-18]]

^<<v24-33-18,18>>^ nem aos sacerdotes levitas faltará homem diante de mim, para que ofereça holocausto, queime oferta de manjares e faça sacrifício todos os dias.

[[v24-33-19]]

^<<v24-33-19,19>>^ Veio a palavra do SENHOR a Jeremias, dizendo:

[[v24-33-20]]

^<<v24-33-20,20>>^ Assim diz o SENHOR: Se puderdes invalidar a minha aliança com o dia e a minha aliança com a noite, de tal modo que não haja nem dia nem noite a seu tempo,

[[v24-33-21]]

^<<v24-33-21,21>>^ poder-se-á também invalidar a minha aliança com Davi, meu servo, para que não tenha filho que reine no seu trono; como também com os levitas sacerdotes, meus ministros.

[[v24-33-22]]

^<<v24-33-22,22>>^ Como não se pode contar o exército dos céus, nem medir-se a areia do mar, assim tornarei incontável a descendência de Davi, meu servo, e os levitas que ministram diante de mim.

[[v24-33-23]]

^<<v24-33-23,23>>^ Veio ainda a palavra do SENHOR a Jeremias, dizendo:

[[v24-33-24]]

^<<v24-33-24,24>>^ Não atentas para o que diz este povo: As duas famílias que o SENHOR elegeu, agora as rejeitou? Assim desprezam a meu povo, que a seus olhos já não é povo.

[[v24-33-25]]

^<<v24-33-25,25>>^ Assim diz o SENHOR: Se a minha aliança com o dia e com a noite não permanecer, e eu não mantiver as leis fixas dos céus e da terra,

[[v24-33-26]]

^<<v24-33-26,26>>^ também rejeitarei a descendência de Jacó e de Davi, meu servo, de modo que não tome da sua descendência quem domine sobre a descendência de Abraão, Isaque e Jacó; porque lhes restaurarei a sorte e deles me apiedarei.

'''

xref:024-jeremias/024-jeremias-032.adoc#v24-32-0[&#60; Capítulo Anterior] | <<v24-33-0,Topo>> | xref:024-jeremias/024-jeremias-034.adoc#v24-34-0[Próximo Capítulo &#62;]