include::./index.adoc[]

[[v24-40-0]]
=== Jeremias, 40
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-40-1]]

^<<v24-40-1,1>>^ Palavra que veio a Jeremias da parte do SENHOR, depois que Nebuzaradã, o chefe da guarda, o pôs em liberdade em Ramá, estando ele atado com cadeias no meio de todos os do cativeiro de Jerusalém e de Judá, que foram levados cativos para a Babilônia.

[[v24-40-2]]

^<<v24-40-2,2>>^ Tomou o chefe da guarda a Jeremias e lhe disse: O SENHOR, teu Deus, pronunciou este mal contra este lugar;

[[v24-40-3]]

^<<v24-40-3,3>>^ o SENHOR o trouxe e fez como tinha dito. Porque pecastes contra o SENHOR e não obedecestes à sua voz, tudo isto vos sucedeu.

[[v24-40-4]]

^<<v24-40-4,4>>^ Agora, pois, eis que te livrei hoje das cadeias que estavam sobre as tuas mãos. Se te apraz vir comigo para a Babilônia, vem, e eu cuidarei bem de ti; mas, se não te apraz vir comigo para a Babilônia, deixa de vir. Olha, toda a terra está diante de ti; para onde julgares bom e próprio ir, vai para aí.

[[v24-40-5]]

^<<v24-40-5,5>>^ Mas, visto que ele tardava em decidir-se, o capitão lhe disse: Volta a Gedalias, filho de Aicão, filho de Safã, a quem o rei da Babilônia nomeou governador das cidades de Judá, e habita com ele no meio do povo; ou, se para qualquer outra parte te aprouver ir, vai. Deu-lhe o chefe da guarda mantimento e um presente e o deixou ir.

[[v24-40-6]]

^<<v24-40-6,6>>^ Assim, foi Jeremias a Gedalias, filho de Aicão, a Mispa; e habitou com ele no meio do povo que havia ficado na terra.

[[v24-40-7]]

^<<v24-40-7,7>>^ Ouvindo, pois, os capitães dos exércitos que estavam no campo, eles e seus homens, que o rei da Babilônia nomeara governador da terra a Gedalias, filho de Aicão, e que lhe havia confiado os homens, as mulheres, os meninos e os mais pobres da terra que não foram levados ao exílio, para a Babilônia,

[[v24-40-8]]

^<<v24-40-8,8>>^ vieram ter com ele a Mispa, a saber: Ismael, filho de Netanias, Joanã e Jônatas, filhos de Careá, Seraías, filho de Tanumete, os filhos de Efai, o netofatita, Jezanias, filho do maacatita, eles e os seus homens.

[[v24-40-9]]

^<<v24-40-9,9>>^ Gedalias, filho de Aicão, filho de Safã, jurou a eles e aos seus homens e lhes disse: Nada temais da parte dos caldeus; ficai na terra, servi ao rei da Babilônia, e bem vos irá.

[[v24-40-10]]

^<<v24-40-10,10>>^ Quanto a mim, eis que habito em Mispa, para estar às ordens dos caldeus que vierem a nós; vós, porém, colhei o vinho, as frutas de verão e o azeite, metei-os nas vossas vasilhas e habitai nas vossas cidades que tomastes.

[[v24-40-11]]

^<<v24-40-11,11>>^ Da mesma sorte, todos os judeus que estavam em Moabe, entre os filhos de Amom e em Edom e os que havia em todas aquelas terras ouviram que o rei da Babilônia havia deixado um resto de Judá e que havia nomeado governador sobre eles a Gedalias, filho de Aicão, filho de Safã;

[[v24-40-12]]

^<<v24-40-12,12>>^ então, voltaram todos eles de todos os lugares para onde foram lançados e vieram à terra de Judá, a Gedalias, a Mispa; e colheram vinho e frutas de verão em muita abundância.

[[v24-40-13]]

^<<v24-40-13,13>>^ Joanã, filho de Careá, e todos os príncipes dos exércitos que estavam no campo vieram a Gedalias, a Mispa,

[[v24-40-14]]

^<<v24-40-14,14>>^ e lhe disseram: Sabes tu que Baalis, rei dos filhos de Amom, enviou a Ismael, filho de Netanias, para tirar-te a vida? Mas Gedalias, filho de Aicão, não lhes deu crédito.

[[v24-40-15]]

^<<v24-40-15,15>>^ Todavia, Joanã, filho de Careá, disse a Gedalias em segredo, em Mispa: Irei agora e matarei a Ismael, filho de Netanias, sem que ninguém o saiba; por que razão tiraria ele a tua vida, de maneira que todo o Judá que se tem congregado a ti fosse disperso, e viesse a perecer o resto de Judá?

[[v24-40-16]]

^<<v24-40-16,16>>^ Mas disse Gedalias, filho de Aicão, a Joanã, filho de Careá: Não faças tal coisa, porque isso que falas contra Ismael é falso.

'''

xref:024-jeremias/024-jeremias-039.adoc#v24-39-0[&#60; Capítulo Anterior] | <<v24-40-0,Topo>> | xref:024-jeremias/024-jeremias-041.adoc#v24-41-0[Próximo Capítulo &#62;]