include::./index.adoc[]

[[v24-14-0]]
=== Jeremias, 14
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-14-1]]

^<<v24-14-1,1>>^ Palavra do SENHOR que veio a Jeremias a respeito da grande seca.

[[v24-14-2]]

^<<v24-14-2,2>>^ Anda chorando Judá, as suas portas estão abandonadas e, de luto, se curvam até ao chão; e o clamor de Jerusalém vai subindo.

[[v24-14-3]]

^<<v24-14-3,3>>^ Os seus poderosos enviam os criados a buscar água; estes vão às cisternas e não acham água; voltam com seus cântaros vazios e, decepcionados e confusos, cobrem a cabeça.

[[v24-14-4]]

^<<v24-14-4,4>>^ Por não ter havido chuva sobre a terra, esta se acha deprimida; e, por isso, os lavradores, decepcionados, cobrem a cabeça.

[[v24-14-5]]

^<<v24-14-5,5>>^ Até as cervas no campo têm as suas crias e as abandonam, porquanto não há erva.

[[v24-14-6]]

^<<v24-14-6,6>>^ Os jumentos selvagens se põem nos desnudos altos e, ofegantes, sorvem o ar como chacais; os seus olhos desfalecem, porque não há erva.

[[v24-14-7]]

^<<v24-14-7,7>>^ Posto que as nossas maldades testificam contra nós, ó SENHOR, age por amor do teu nome; porque as nossas rebeldias se multiplicaram; contra ti pecamos.

[[v24-14-8]]

^<<v24-14-8,8>>^ Ó Esperança de Israel e Redentor seu no tempo da angústia, por que serias como estrangeiro na terra e como viandante que se desvia para passar a noite?

[[v24-14-9]]

^<<v24-14-9,9>>^ Por que serias como homem surpreendido, como valente que não pode salvar? Mas tu, ó SENHOR, estás em nosso meio, e somos chamados pelo teu nome; não nos desampares.

[[v24-14-10]]

^<<v24-14-10,10>>^ Assim diz o SENHOR sobre este povo: Gostam de andar errantes e não detêm os pés; por isso, o SENHOR não se agrada deles, mas se lembrará da maldade deles e lhes punirá o pecado.

[[v24-14-11]]

^<<v24-14-11,11>>^ Disse-me ainda o SENHOR: Não rogues por este povo para o bem dele.

[[v24-14-12]]

^<<v24-14-12,12>>^ Quando jejuarem, não ouvirei o seu clamor e, quando trouxerem holocaustos e ofertas de manjares, não me agradarei deles; antes, eu os consumirei pela espada, pela fome e pela peste.

[[v24-14-13]]

^<<v24-14-13,13>>^ Então, disse eu: Ah! SENHOR Deus, eis que os profetas lhes dizem: Não vereis espada, nem tereis fome; mas vos darei verdadeira paz neste lugar.

[[v24-14-14]]

^<<v24-14-14,14>>^ Disse-me o SENHOR: Os profetas profetizam mentiras em meu nome, nunca os enviei, nem lhes dei ordem, nem lhes falei; visão falsa, adivinhação, vaidade e o engano do seu íntimo são o que eles vos profetizam.

[[v24-14-15]]

^<<v24-14-15,15>>^ Portanto, assim diz o SENHOR acerca dos profetas que, profetizando em meu nome, sem que eu os tenha mandado, dizem que nem espada, nem fome haverá nesta terra: À espada e à fome serão consumidos esses profetas.

[[v24-14-16]]

^<<v24-14-16,16>>^ O povo a quem eles profetizam será lançado nas ruas de Jerusalém, por causa da fome e da espada; não haverá quem os sepulte, a ele, a suas mulheres, a seus filhos e a suas filhas; porque derramarei sobre eles a sua maldade.

[[v24-14-17]]

^<<v24-14-17,17>>^ Portanto, lhes dirás esta palavra: Os meus olhos derramem lágrimas, de noite e de dia, e não cessem; porque a virgem, filha do meu povo, está profundamente golpeada, de ferida mui dolorosa.

[[v24-14-18]]

^<<v24-14-18,18>>^ Se eu saio ao campo, eis aí os mortos à espada; se entro na cidade, estão ali os debilitados pela fome; até os profetas e os sacerdotes vagueiam pela terra e não sabem para onde vão.

[[v24-14-19]]

^<<v24-14-19,19>>^ Acaso, já de todo rejeitaste a Judá? Ou aborrece a tua alma a Sião? Por que nos feriste, e não há cura para nós? Aguardamos a paz, e nada há de bom; o tempo da cura, e eis o terror.

[[v24-14-20]]

^<<v24-14-20,20>>^ Conhecemos, ó SENHOR, a nossa maldade e a iniquidade de nossos pais; porque temos pecado contra ti.

[[v24-14-21]]

^<<v24-14-21,21>>^ Não nos rejeites, por amor do teu nome; não cubras de opróbrio o trono da tua glória; lembra-te e não anules a tua aliança conosco.

[[v24-14-22]]

^<<v24-14-22,22>>^ Acaso, haverá entre os ídolos dos gentios algum que faça chover? Ou podem os céus de si mesmos dar chuvas? Não és tu somente, ó SENHOR, nosso Deus, o que fazes isto? Portanto, em ti esperamos, pois tu fazes todas estas coisas.

'''

xref:024-jeremias/024-jeremias-013.adoc#v24-13-0[&#60; Capítulo Anterior] | <<v24-14-0,Topo>> | xref:024-jeremias/024-jeremias-015.adoc#v24-15-0[Próximo Capítulo &#62;]