include::./index.adoc[]

[[v24-37-0]]
=== Jeremias, 37
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-37-1]]

^<<v24-37-1,1>>^ Zedequias, filho de Josias e a quem Nabucodonosor, rei da Babilônia, constituíra rei na terra de Judá, reinou em lugar de Conias, filho de Jeoaquim.

[[v24-37-2]]

^<<v24-37-2,2>>^ Mas nem ele, nem os seus servos, nem o povo da terra deram ouvidos às palavras do SENHOR que falou por intermédio de Jeremias, o profeta.

[[v24-37-3]]

^<<v24-37-3,3>>^ Contudo, mandou o rei Zedequias a Jucal, filho de Selemias, e ao sacerdote Sofonias, filho de Maaseias, ao profeta Jeremias, para lhe dizerem: Roga por nós ao SENHOR, nosso Deus.

[[v24-37-4]]

^<<v24-37-4,4>>^ Jeremias andava livremente entre o povo, porque ainda o não haviam encarcerado.

[[v24-37-5]]

^<<v24-37-5,5>>^ O exército de Faraó saíra do Egito; e, quando os caldeus, que sitiavam Jerusalém, ouviram esta notícia, retiraram-se dela.

[[v24-37-6]]

^<<v24-37-6,6>>^ Então, veio a Jeremias, o profeta, a palavra do SENHOR:

[[v24-37-7]]

^<<v24-37-7,7>>^ Assim diz o SENHOR, Deus de Israel: Assim direis ao rei de Judá, que vos enviou a mim, para me consultar: Eis que o exército de Faraó, que saiu em vosso socorro, voltará para a sua terra, no Egito.

[[v24-37-8]]

^<<v24-37-8,8>>^ Retornarão os caldeus, pelejarão contra esta cidade, tomá-la-ão e a queimarão.

[[v24-37-9]]

^<<v24-37-9,9>>^ Assim diz o SENHOR: Não vos enganeis a vós mesmos, dizendo: Sem dúvida, se irão os caldeus de nós; pois, de fato, não se retirarão.

[[v24-37-10]]

^<<v24-37-10,10>>^ Porque, ainda que derrotásseis a todo o exército dos caldeus, que pelejam contra vós outros, e ficassem deles apenas homens mortalmente feridos, cada um se levantaria na sua tenda e queimaria esta cidade.

[[v24-37-11]]

^<<v24-37-11,11>>^ Tendo-se retirado o exército dos caldeus de Jerusalém, por causa do exército de Faraó,

[[v24-37-12]]

^<<v24-37-12,12>>^ saiu Jeremias de Jerusalém, a fim de ir à terra de Benjamim, para receber o quinhão de uma herança que tinha no meio do povo.

[[v24-37-13]]

^<<v24-37-13,13>>^ Estando ele à Porta de Benjamim, achava-se ali um capitão da guarda, cujo nome era Jerias, filho de Selemias, filho de Hananias, capitão que prendeu a Jeremias, o profeta, dizendo: Tu foges para os caldeus.

[[v24-37-14]]

^<<v24-37-14,14>>^ Disse Jeremias: É mentira, não fujo para os caldeus. Mas Jerias não lhe deu ouvidos; prendeu a Jeremias e o levou aos príncipes.

[[v24-37-15]]

^<<v24-37-15,15>>^ Os príncipes, irados contra Jeremias, açoitaram-no e o meteram no cárcere, na casa de Jônatas, o escrivão, porque a tinham transformado em cárcere.

[[v24-37-16]]

^<<v24-37-16,16>>^ Tendo Jeremias entrado nas celas do calabouço, ali ficou muitos dias.

[[v24-37-17]]

^<<v24-37-17,17>>^ Mandou o rei Zedequias trazê-lo para sua casa e, em secreto, lhe perguntou: Há alguma palavra do SENHOR? Respondeu Jeremias: Há. Disse ainda: Nas mãos do rei da Babilônia serás entregue.

[[v24-37-18]]

^<<v24-37-18,18>>^ Disse mais Jeremias ao rei Zedequias: Em que pequei contra ti, ou contra os teus servos, ou contra este povo, para que me pusesses na prisão?

[[v24-37-19]]

^<<v24-37-19,19>>^ Onde estão agora os vossos profetas, que vos profetizavam, dizendo: O rei da Babilônia não virá contra vós outros, nem contra esta terra?

[[v24-37-20]]

^<<v24-37-20,20>>^ Agora, pois, ouve, ó rei, meu senhor: Que a minha humilde súplica seja bem-acolhida por ti, e não me deixes tornar à casa de Jônatas, o escrivão, para que eu não venha a morrer ali.

[[v24-37-21]]

^<<v24-37-21,21>>^ Então, ordenou o rei Zedequias que pusessem a Jeremias no átrio da guarda; e, cada dia, deram-lhe um pão da Rua dos Padeiros, até acabar-se todo pão da cidade. Assim ficou Jeremias no átrio da guarda.

'''

xref:024-jeremias/024-jeremias-036.adoc#v24-36-0[&#60; Capítulo Anterior] | <<v24-37-0,Topo>> | xref:024-jeremias/024-jeremias-038.adoc#v24-38-0[Próximo Capítulo &#62;]