include::./index.adoc[]

[[v24-42-0]]
=== Jeremias, 42
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-42-1]]

^<<v24-42-1,1>>^ Então, chegaram todos os capitães dos exércitos, e Joanã, filho de Careá, e Jezanias, filho de Hosaías, e todo o povo, desde o menor até ao maior,

[[v24-42-2]]

^<<v24-42-2,2>>^ e disseram a Jeremias, o profeta: Apresentamos-te a nossa humilde súplica, a fim de que rogues ao SENHOR, teu Deus, por nós e por este resto; porque, de muitos que éramos, só restamos uns poucos, como vês com os teus próprios olhos;

[[v24-42-3]]

^<<v24-42-3,3>>^ a fim de que o SENHOR, teu Deus, nos mostre o caminho por onde havemos de andar e aquilo que havemos de fazer.

[[v24-42-4]]

^<<v24-42-4,4>>^ Respondeu-lhes Jeremias, o profeta: Já vos ouvi; eis que orarei ao SENHOR, vosso Deus, segundo o vosso pedido. Tudo o que o SENHOR vos responder, eu vo-lo declararei; não vos ocultarei nada.

[[v24-42-5]]

^<<v24-42-5,5>>^ Então, eles disseram a Jeremias: Seja o SENHOR testemunha verdadeira e fiel contra nós, se não fizermos segundo toda a palavra com que o SENHOR, teu Deus, te enviar a nós outros.

[[v24-42-6]]

^<<v24-42-6,6>>^ Seja ela boa ou seja má, obedeceremos à voz do SENHOR, nosso Deus, a quem te enviamos, para que nos suceda bem ao obedecermos à voz do SENHOR, nosso Deus.

[[v24-42-7]]

^<<v24-42-7,7>>^ Ao fim de dez dias, veio a palavra do SENHOR a Jeremias.

[[v24-42-8]]

^<<v24-42-8,8>>^ Então, chamou a Joanã, filho de Careá, e a todos os capitães dos exércitos que havia com ele, e a todo o povo, desde o menor até ao maior,

[[v24-42-9]]

^<<v24-42-9,9>>^ e lhes disse: Assim diz o SENHOR, Deus de Israel, a quem me enviastes para apresentar a vossa súplica diante dele:

[[v24-42-10]]

^<<v24-42-10,10>>^ Se permanecerdes nesta terra, então, vos edificarei e não vos derribarei; plantar-vos-ei e não vos arrancarei, porque estou arrependido do mal que vos tenho feito.

[[v24-42-11]]

^<<v24-42-11,11>>^ Não temais o rei da Babilônia, a quem vós temeis; não o temais, diz o SENHOR, porque eu sou convosco, para vos salvar e vos livrar das suas mãos.

[[v24-42-12]]

^<<v24-42-12,12>>^ Eu vos serei propício, para que ele tenha misericórdia de vós e vos faça morar em vossa terra.

[[v24-42-13]]

^<<v24-42-13,13>>^ Mas, se vós disserdes: Não ficaremos nesta terra, não obedecendo à voz do SENHOR, vosso Deus,

[[v24-42-14]]

^<<v24-42-14,14>>^ dizendo: Não; antes, iremos à terra do Egito, onde não veremos guerra, nem ouviremos som de trombeta, nem teremos fome de pão, e ali ficaremos,

[[v24-42-15]]

^<<v24-42-15,15>>^ nesse caso, ouvi a palavra do SENHOR, ó resto de Judá. Assim diz o SENHOR dos Exércitos, o Deus de Israel: Se tiverdes o firme propósito de entrar no Egito e fordes para morar,

[[v24-42-16]]

^<<v24-42-16,16>>^ acontecerá, então, que a espada que vós temeis vos alcançará na terra do Egito, e a fome que receais vos seguirá de perto os passos no Egito, onde morrereis.

[[v24-42-17]]

^<<v24-42-17,17>>^ Assim será com todos os homens que tiverem o propósito de entrar no Egito para morar: morrerão à espada, à fome e de peste; não restará deles nem um, nem escapará do mal que farei vir sobre eles.

[[v24-42-18]]

^<<v24-42-18,18>>^ Porque assim diz o SENHOR dos Exércitos, o Deus de Israel: Como se derramou a minha ira e o meu furor sobre os habitantes de Jerusalém, assim se derramará a minha indignação sobre vós, quando entrardes no Egito; sereis objeto de maldição, de espanto, de desprezo e opróbrio e não vereis mais este lugar.

[[v24-42-19]]

^<<v24-42-19,19>>^ Falou-vos o SENHOR, ó resto de Judá: Não entreis no Egito; tende por certo que vos adverti hoje.

[[v24-42-20]]

^<<v24-42-20,20>>^ Porque vós, à custa da vossa vida, a vós mesmos vos enganastes, pois me enviastes ao SENHOR, vosso Deus, dizendo: Ora por nós ao SENHOR, nosso Deus; e, segundo tudo o que disser o SENHOR, nosso Deus, declara-no-lo assim, e o faremos;

[[v24-42-21]]

^<<v24-42-21,21>>^ mas, tendo-vos declarado isso hoje, não destes ouvidos à voz do SENHOR, vosso Deus, em coisa alguma pela qual ele me enviou a vós outros.

[[v24-42-22]]

^<<v24-42-22,22>>^ Agora, pois, sabei por certo que morrereis à espada, à fome e de peste no mesmo lugar aonde desejastes ir para morar.

'''

xref:024-jeremias/024-jeremias-041.adoc#v24-41-0[&#60; Capítulo Anterior] | <<v24-42-0,Topo>> | xref:024-jeremias/024-jeremias-043.adoc#v24-43-0[Próximo Capítulo &#62;]