include::./index.adoc[]

[[v24-41-0]]
=== Jeremias, 41
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-41-1]]

^<<v24-41-1,1>>^ Sucedeu, porém, que, no sétimo mês, veio Ismael, filho de Netanias, filho de Elisama, de família real, e dez homens, capitães do rei, com ele, a Gedalias, filho de Aicão, a Mispa; e ali comeram pão juntos, em Mispa.

[[v24-41-2]]

^<<v24-41-2,2>>^ Dispuseram-se Ismael, filho de Netanias, e os dez homens que estavam com ele e feriram à espada a Gedalias, filho de Aicão, filho de Safã, matando, assim, aquele que o rei da Babilônia nomeara governador da terra.

[[v24-41-3]]

^<<v24-41-3,3>>^ Também matou Ismael a todos os judeus que estavam com Gedalias, em Mispa, como também aos caldeus, homens de guerra, que se achavam ali.

[[v24-41-4]]

^<<v24-41-4,4>>^ Sucedeu no dia seguinte ao em que ele matara a Gedalias, sem ninguém o saber,

[[v24-41-5]]

^<<v24-41-5,5>>^ que vieram homens de Siquém, de Siló e de Samaria; oitenta homens, com a barba rapada, as vestes rasgadas e o corpo retalhado, trazendo consigo ofertas de manjares e incenso, para levarem à Casa do SENHOR.

[[v24-41-6]]

^<<v24-41-6,6>>^ Saindo-lhes ao encontro Ismael, filho de Netanias, de Mispa, ia chorando; ao encontrá-los, lhes disse: Vinde a Gedalias, filho de Aicão.

[[v24-41-7]]

^<<v24-41-7,7>>^ Vindo eles, porém, até ao meio da cidade, matou-os Ismael, filho de Netanias, ele e os que estavam com ele, e os lançaram num poço.

[[v24-41-8]]

^<<v24-41-8,8>>^ Mas houve dentre eles dez homens que disseram a Ismael: Não nos mates a nós, porque temos depósitos de trigo, cevada, azeite e mel escondidos no campo. Por isso, ele desistiu e não os matou como aos outros.

[[v24-41-9]]

^<<v24-41-9,9>>^ O poço em que Ismael lançou todos os cadáveres dos homens que ferira além de Gedalias é o mesmo que fez o rei Asa, na sua defesa contra Baasa, rei de Israel; foi esse mesmo que encheu de mortos Ismael, filho de Netanias.

[[v24-41-10]]

^<<v24-41-10,10>>^ Ismael levou cativo a todo o resto do povo que estava em Mispa, isto é, as filhas do rei e todo o povo que ficara em Mispa, que Nebuzaradã, o chefe da guarda, havia confiado a Gedalias, filho de Aicão; levou-os cativos Ismael, filho de Netanias; e se foi para passar aos filhos de Amom.

[[v24-41-11]]

^<<v24-41-11,11>>^ Ouvindo, pois, Joanã, filho de Careá, e todos os príncipes dos exércitos que estavam com ele todo o mal que havia feito Ismael, filho de Netanias,

[[v24-41-12]]

^<<v24-41-12,12>>^ tomaram consigo a todos os seus homens e foram pelejar contra Ismael, filho de Netanias; acharam-no junto às grandes águas que há em Gibeão.

[[v24-41-13]]

^<<v24-41-13,13>>^ Ora, todo o povo que estava com Ismael se alegrou quando viu a Joanã, filho de Careá, e a todos os príncipes dos exércitos que vinham com ele.

[[v24-41-14]]

^<<v24-41-14,14>>^ Todo o povo que Ismael levara cativo de Mispa virou as costas, voltou e foi para Joanã, filho de Careá.

[[v24-41-15]]

^<<v24-41-15,15>>^ Mas Ismael, filho de Netanias, escapou de Joanã com oito homens e se foi para os filhos de Amom.

[[v24-41-16]]

^<<v24-41-16,16>>^ Tomou, então, Joanã, filho de Careá, e todos os príncipes dos exércitos que estavam com ele a todo o restante do povo que Ismael, filho de Netanias, levara cativo de Mispa, depois de ter ferido a Gedalias, filho de Aicão, isto é, os homens valentes de guerra, as mulheres, os meninos e os eunucos que havia recobrado de Gibeão;

[[v24-41-17]]

^<<v24-41-17,17>>^ partiram e pararam em Gerute-Quimã, que está perto de Belém, para dali entrarem no Egito,

[[v24-41-18]]

^<<v24-41-18,18>>^ por causa dos caldeus; porque os temiam, por ter Ismael, filho de Netanias, ferido a Gedalias, filho de Aicão, a quem o rei da Babilônia nomeara governador da terra.

'''

xref:024-jeremias/024-jeremias-040.adoc#v24-40-0[&#60; Capítulo Anterior] | <<v24-41-0,Topo>> | xref:024-jeremias/024-jeremias-042.adoc#v24-42-0[Próximo Capítulo &#62;]