include::./index.adoc[]

[[v24-28-0]]
=== Jeremias, 28
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-28-1]]

^<<v24-28-1,1>>^ No mesmo ano, no princípio do reinado de Zedequias, rei de Judá, isto é, no ano quarto, no quinto mês, Hananias, filho de Azur e profeta de Gibeão, me falou na Casa do SENHOR, na presença dos sacerdotes e de todo o povo, dizendo:

[[v24-28-2]]

^<<v24-28-2,2>>^ Assim fala o SENHOR dos Exércitos, o Deus de Israel, dizendo: Quebrei o jugo do rei da Babilônia.

[[v24-28-3]]

^<<v24-28-3,3>>^ Dentro de dois anos, eu tornarei a trazer a este lugar todos os utensílios da Casa do SENHOR, que daqui tomou Nabucodonosor, rei da Babilônia, levando-os para a Babilônia.

[[v24-28-4]]

^<<v24-28-4,4>>^ Também a Jeconias, filho de Jeoaquim, rei de Judá, e a todos os exilados de Judá, que entraram na Babilônia, eu tornarei a trazer a este lugar, diz o SENHOR; porque quebrei o jugo do rei da Babilônia.

[[v24-28-5]]

^<<v24-28-5,5>>^ Então, respondeu Jeremias, o profeta, ao profeta Hananias, na presença dos sacerdotes e perante todo o povo que estava na Casa do SENHOR.

[[v24-28-6]]

^<<v24-28-6,6>>^ Disse, pois, Jeremias, o profeta: Amém! Assim faça o SENHOR; confirme o SENHOR as tuas palavras, com que profetizaste, e torne ele a trazer da Babilônia a este lugar os utensílios da Casa do SENHOR e todos os exilados.

[[v24-28-7]]

^<<v24-28-7,7>>^ Mas ouve agora esta palavra, que eu falo a ti e a todo o povo para que ouçais:

[[v24-28-8]]

^<<v24-28-8,8>>^ Os profetas que houve antes de mim e antes de ti, desde a antiguidade, profetizaram guerra, mal e peste contra muitas terras e grandes reinos.

[[v24-28-9]]

^<<v24-28-9,9>>^ O profeta que profetizar paz, só ao cumprir-se a sua palavra, será conhecido como profeta, de fato, enviado do SENHOR.

[[v24-28-10]]

^<<v24-28-10,10>>^ Então, o profeta Hananias tomou os canzis do pescoço de Jeremias, o profeta, e os quebrou;

[[v24-28-11]]

^<<v24-28-11,11>>^ e falou na presença de todo o povo: Assim diz o SENHOR: Deste modo, dentro de dois anos, quebrarei o jugo de Nabucodonosor, rei da Babilônia, de sobre o pescoço de todas as nações. E Jeremias, o profeta, se foi, tomando o seu caminho.

[[v24-28-12]]

^<<v24-28-12,12>>^ Mas depois que Hananias, o profeta, quebrou os canzis de sobre o pescoço do profeta Jeremias, veio a este a palavra do SENHOR, dizendo:

[[v24-28-13]]

^<<v24-28-13,13>>^ Vai e fala a Hananias, dizendo: Assim diz o SENHOR: Canzis de madeira quebraste. Mas, em vez deles, farei canzis de ferro.

[[v24-28-14]]

^<<v24-28-14,14>>^ Porque assim diz o SENHOR dos Exércitos, o Deus de Israel: Jugo de ferro pus sobre o pescoço de todas estas nações, para servirem a Nabucodonosor, rei da Babilônia; e o servirão. Também lhe dei os animais do campo.

[[v24-28-15]]

^<<v24-28-15,15>>^ Disse Jeremias, o profeta, ao profeta Hananias: Ouve agora, Hananias: O SENHOR não te enviou, mas tu fizeste que este povo confiasse em mentiras.

[[v24-28-16]]

^<<v24-28-16,16>>^ Pelo que assim diz o SENHOR: Eis que te lançarei de sobre a face da terra; morrerás este ano, porque pregaste rebeldia contra o SENHOR.

[[v24-28-17]]

^<<v24-28-17,17>>^ Morreu, pois, o profeta Hananias, no mesmo ano, no sétimo mês.

'''

xref:024-jeremias/024-jeremias-027.adoc#v24-27-0[&#60; Capítulo Anterior] | <<v24-28-0,Topo>> | xref:024-jeremias/024-jeremias-029.adoc#v24-29-0[Próximo Capítulo &#62;]