include::./index.adoc[]

[[v24-27-0]]
=== Jeremias, 27
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-27-1]]

^<<v24-27-1,1>>^ No princípio do reinado de Zedequias, filho de Josias, rei de Judá, veio da parte do SENHOR esta palavra a Jeremias:

[[v24-27-2]]

^<<v24-27-2,2>>^ Assim me disse o SENHOR: Faze correias e canzis e põe-nos ao pescoço.

[[v24-27-3]]

^<<v24-27-3,3>>^ E envia outros ao rei de Edom, ao rei de Moabe, ao rei dos filhos de Amom, ao rei de Tiro e ao rei de Sidom, por intermédio dos mensageiros que vieram a Jerusalém ter com Zedequias, rei de Judá.

[[v24-27-4]]

^<<v24-27-4,4>>^ Ordena-lhes que digam aos seus senhores: Assim diz o SENHOR dos Exércitos, o Deus de Israel: Assim direis a vossos senhores:

[[v24-27-5]]

^<<v24-27-5,5>>^ Eu fiz a terra, o homem e os animais que estão sobre a face da terra, com o meu grande poder e com o meu braço estendido, e os dou àquele a quem for justo.

[[v24-27-6]]

^<<v24-27-6,6>>^ Agora, eu entregarei todas estas terras ao poder de Nabucodonosor, rei da Babilônia, meu servo; e também lhe dei os animais do campo para que o sirvam.

[[v24-27-7]]

^<<v24-27-7,7>>^ Todas as nações servirão a ele, a seu filho e ao filho de seu filho, até que também chegue a vez da sua própria terra, quando muitas nações e grandes reis o fizerem seu escravo.

[[v24-27-8]]

^<<v24-27-8,8>>^ Se alguma nação e reino não servirem o mesmo Nabucodonosor, rei da Babilônia, e não puserem o pescoço debaixo do jugo do rei da Babilônia, a essa nação castigarei com espada, e com fome, e com peste, diz o SENHOR, até que eu a consuma pela sua mão.

[[v24-27-9]]

^<<v24-27-9,9>>^ Não deis ouvidos aos vossos profetas e aos vossos adivinhos, aos vossos sonhadores, aos vossos agoureiros e aos vossos encantadores, que vos falam, dizendo: Não servireis o rei da Babilônia.

[[v24-27-10]]

^<<v24-27-10,10>>^ Porque eles vos profetizam mentiras para vos mandarem para longe da vossa terra, e para que eu vos expulse, e pereçais.

[[v24-27-11]]

^<<v24-27-11,11>>^ Mas a nação que meter o pescoço sob o jugo do rei da Babilônia e o servir, eu a deixarei na sua terra, diz o SENHOR, e lavrá-la-á e habitará nela.

[[v24-27-12]]

^<<v24-27-12,12>>^ Falei a Zedequias, rei de Judá, segundo todas estas palavras, dizendo: Metei o pescoço no jugo do rei da Babilônia, servi-o, a ele e ao seu povo, e vivereis.

[[v24-27-13]]

^<<v24-27-13,13>>^ Por que morrerias tu e o teu povo, à espada, à fome e de peste, como o SENHOR disse com respeito à nação que não servir ao rei da Babilônia?

[[v24-27-14]]

^<<v24-27-14,14>>^ Não deis ouvidos às palavras dos profetas, que vos dizem: Não servireis ao rei da Babilônia. É mentira o que eles vos profetizam.

[[v24-27-15]]

^<<v24-27-15,15>>^ Porque não os enviei, diz o SENHOR, e profetizam falsamente em meu nome, para que eu vos expulse e pereçais, vós e eles que vos profetizam.

[[v24-27-16]]

^<<v24-27-16,16>>^ Também falei aos sacerdotes e a todo este povo, dizendo: Assim diz o SENHOR: Não deis ouvidos às palavras dos vossos profetas que vos profetizam, dizendo: Eis que os utensílios da Casa do SENHOR voltarão em breve da Babilônia. É mentira o que eles vos profetizam.

[[v24-27-17]]

^<<v24-27-17,17>>^ Não lhes deis ouvidos, servi ao rei da Babilônia e vivereis; por que se tornaria esta cidade em desolação?

[[v24-27-18]]

^<<v24-27-18,18>>^ Porém, se são profetas, e se a palavra do SENHOR está com eles, que orem ao SENHOR dos Exércitos, para que os utensílios que ficaram na Casa do SENHOR, e na casa do rei de Judá, e em Jerusalém não sejam levados para a Babilônia.

[[v24-27-19]]

^<<v24-27-19,19>>^ Porque assim diz o SENHOR dos Exércitos acerca das colunas, do mar, dos suportes e dos restantes utensílios que ficaram na cidade,

[[v24-27-20]]

^<<v24-27-20,20>>^ os quais Nabucodonosor, rei da Babilônia, não levou, quando deportou, de Jerusalém para a Babilônia, a Jeconias, filho de Jeoaquim, rei de Judá, assim como a todos os nobres de Judá e de Jerusalém;

[[v24-27-21]]

^<<v24-27-21,21>>^ sim, isto diz o SENHOR dos Exércitos, o Deus de Israel, acerca dos utensílios que ficaram na Casa do SENHOR, e na casa do rei de Judá, e em Jerusalém:

[[v24-27-22]]

^<<v24-27-22,22>>^ à Babilônia serão levados, onde ficarão até ao dia em que eu atentar para eles, diz o SENHOR; então, os farei trazer e os devolverei a este lugar.

'''

xref:024-jeremias/024-jeremias-026.adoc#v24-26-0[&#60; Capítulo Anterior] | <<v24-27-0,Topo>> | xref:024-jeremias/024-jeremias-028.adoc#v24-28-0[Próximo Capítulo &#62;]