include::./index.adoc[]

[[v24-50-0]]
=== Jeremias, 50
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-50-1]]

^<<v24-50-1,1>>^ Palavra que falou o SENHOR contra a Babilônia e contra a terra dos caldeus, por intermédio de Jeremias, o profeta.

[[v24-50-2]]

^<<v24-50-2,2>>^ Anunciai entre as nações; fazei ouvir e arvorai estandarte; proclamai, não encubrais; dizei: Tomada é a Babilônia, Bel está confundido, e abatido, Merodaque; cobertas de vergonha estão as suas imagens, e seus ídolos tremem de terror.

[[v24-50-3]]

^<<v24-50-3,3>>^ Porque do Norte subiu contra ela uma nação que tornará deserta a sua terra, e não haverá quem nela habite; tanto os homens como os animais fugiram e se foram.

[[v24-50-4]]

^<<v24-50-4,4>>^ Naqueles dias, naquele tempo, diz o SENHOR, voltarão os filhos de Israel, eles e os filhos de Judá juntamente; andando e chorando, virão e buscarão ao SENHOR, seu Deus.

[[v24-50-5]]

^<<v24-50-5,5>>^ Perguntarão pelo caminho de Sião, de rostos voltados para lá, e dirão: Vinde, e unamo-nos ao SENHOR, em aliança eterna que jamais será esquecida.

[[v24-50-6]]

^<<v24-50-6,6>>^ O meu povo tem sido ovelhas perdidas; seus pastores as fizeram errar e as deixaram desviar para os montes; do monte passaram ao outeiro, esqueceram-se do seu redil.

[[v24-50-7]]

^<<v24-50-7,7>>^ Todos os que as acharam as devoraram; e os seus adversários diziam: Culpa nenhuma teremos; porque pecaram contra o SENHOR, a morada da justiça, e contra a esperança de seus pais, o SENHOR.

[[v24-50-8]]

^<<v24-50-8,8>>^ Fugi do meio da Babilônia e saí da terra dos caldeus; e sede como os bodes que vão adiante do rebanho.

[[v24-50-9]]

^<<v24-50-9,9>>^ Porque eis que eu suscitarei e farei subir contra a Babilônia um conjunto de grandes nações da terra do Norte, e se porão em ordem de batalha contra ela; assim será tomada. As suas flechas serão como de destro guerreiro, nenhuma tornará sem efeito.

[[v24-50-10]]

^<<v24-50-10,10>>^ A Caldeia servirá de presa; todos os que a saquearem se fartarão, diz o SENHOR;

[[v24-50-11]]

^<<v24-50-11,11>>^ ainda que vos alegrais e exultais, ó saqueadores da minha herança, saltais como bezerros na relva e rinchais como cavalos fogosos,

[[v24-50-12]]

^<<v24-50-12,12>>^ será mui envergonhada vossa mãe, será confundida a que vos deu à luz; eis que ela será a última das nações, um deserto, uma terra seca e uma solidão.

[[v24-50-13]]

^<<v24-50-13,13>>^ Por causa da indignação do SENHOR, não será habitada; antes, se tornará de todo deserta; qualquer que passar por Babilônia se espantará e assobiará por causa de todas as suas pragas.

[[v24-50-14]]

^<<v24-50-14,14>>^ Ponde-vos em ordem de batalha em redor contra Babilônia, todos vós que manejais o arco; atirai-lhe, não poupeis as flechas; porque ela pecou contra o SENHOR.

[[v24-50-15]]

^<<v24-50-15,15>>^ Gritai contra ela, rodeando-a; ela já se rendeu; caíram-lhe os baluartes, estão em terra os seus muros; pois esta é a vingança do SENHOR; vingai-vos dela; fazei-lhe a ela o que ela fez.

[[v24-50-16]]

^<<v24-50-16,16>>^ Eliminai da Babilônia o que semeia e o que maneja a foice no tempo da sega; por causa da espada do opressor, virar-se-á cada um para o seu povo e cada um fugirá para a sua terra.

[[v24-50-17]]

^<<v24-50-17,17>>^ Cordeiro desgarrado é Israel; os leões o afugentaram; primeiro, devorou-o o rei da Assíria, e, por fim, Nabucodonosor o desossou.

[[v24-50-18]]

^<<v24-50-18,18>>^ Portanto, assim diz o SENHOR dos Exércitos, o Deus de Israel: Eis que castigarei o rei da Babilônia e a sua terra, como castiguei o rei da Assíria.

[[v24-50-19]]

^<<v24-50-19,19>>^ Farei tornar Israel para a sua morada, e pastará no Carmelo e em Basã; fartar-se-á na região montanhosa de Efraim e em Gileade.

[[v24-50-20]]

^<<v24-50-20,20>>^ Naqueles dias e naquele tempo, diz o SENHOR, buscar-se-á a iniquidade de Israel, e já não haverá; os pecados de Judá, mas não se acharão; porque perdoarei aos remanescentes que eu deixar.

[[v24-50-21]]

^<<v24-50-21,21>>^ Sobe, ó espada, contra a terra duplamente rebelde, sobe contra ela e contra os moradores da terra de castigo; assola irremissivelmente, destrói tudo após eles, diz o SENHOR, e faze segundo tudo o que te mandei.

[[v24-50-22]]

^<<v24-50-22,22>>^ Há na terra estrondo de batalha e de grande destruição.

[[v24-50-23]]

^<<v24-50-23,23>>^ Como está quebrado, feito em pedaços o martelo de toda a terra! Como se tornou a Babilônia objeto de espanto entre as nações!

[[v24-50-24]]

^<<v24-50-24,24>>^ Lancei-te o laço, ó Babilônia, e foste presa, e não o soubeste; foste surpreendida e apanhada, porque contra o SENHOR te entremeteste.

[[v24-50-25]]

^<<v24-50-25,25>>^ O SENHOR abriu o seu arsenal e tirou dele as armas da sua indignação; porque o Senhor, o SENHOR dos Exércitos, tem obra a realizar na terra dos caldeus.

[[v24-50-26]]

^<<v24-50-26,26>>^ Vinde contra ela de todos os confins da terra, abri os seus celeiros, fazei dela montões de ruínas, destruí-a de todo; dela nada fique de resto.

[[v24-50-27]]

^<<v24-50-27,27>>^ Matai à espada a todos os seus touros, aos seus valentes; desçam eles para o matadouro; ai deles! Pois é chegado o seu dia, o tempo do seu castigo.

[[v24-50-28]]

^<<v24-50-28,28>>^ Ouve-se a voz dos que fugiram e escaparam da terra da Babilônia, para anunciarem em Sião a vingança do SENHOR, nosso Deus, a vingança do seu templo.

[[v24-50-29]]

^<<v24-50-29,29>>^ Convocai contra Babilônia a multidão dos que manejam o arco; acampai-vos contra ela em redor, e ninguém escape. Retribuí-lhe segundo a sua obra; conforme tudo o que fez, assim fazei a ela; porque se houve arrogantemente contra o SENHOR, contra o Santo de Israel.

[[v24-50-30]]

^<<v24-50-30,30>>^ Portanto, cairão os seus jovens nas suas praças, e todos os seus homens de guerra serão reduzidos a silêncio naquele dia, diz o SENHOR.

[[v24-50-31]]

^<<v24-50-31,31>>^ Eis que eu sou contra ti, ó orgulhosa, diz o Senhor, o SENHOR dos Exércitos; porque veio o teu dia, o tempo em que te hei de castigar.

[[v24-50-32]]

^<<v24-50-32,32>>^ Então, tropeçará o soberbo, e cairá, e ninguém haverá que o levante; porei fogo às suas cidades, o qual consumirá todos os seus arredores.

[[v24-50-33]]

^<<v24-50-33,33>>^ Assim diz o SENHOR dos Exércitos: Os filhos de Israel e os filhos de Judá sofrem opressão juntamente; todos os que os levaram cativos os retêm; recusam deixá-los ir;

[[v24-50-34]]

^<<v24-50-34,34>>^ mas o seu Redentor é forte, SENHOR dos Exércitos é o seu nome; certamente, pleiteará a causa deles, para aquietar a terra e inquietar os moradores da Babilônia.

[[v24-50-35]]

^<<v24-50-35,35>>^ A espada virá sobre os caldeus, diz o SENHOR, e sobre os moradores da Babilônia, sobre os seus príncipes, sobre os seus sábios.

[[v24-50-36]]

^<<v24-50-36,36>>^ A espada virá sobre os gabarolas, e ficarão insensatos; virá sobre os valentes dela, e ficarão aterrorizados.

[[v24-50-37]]

^<<v24-50-37,37>>^ A espada virá sobre os seus cavalos, e sobre os seus carros, e sobre todo o misto de gente que está no meio dela, e este será como mulheres; a espada virá sobre os tesouros dela, e serão saqueados.

[[v24-50-38]]

^<<v24-50-38,38>>^ A espada virá sobre as suas águas, e estas secarão; porque a terra é de imagens de escultura, e os seus moradores enlouquecem por estas coisas horríveis.

[[v24-50-39]]

^<<v24-50-39,39>>^ Por isso, as feras do deserto com os chacais habitarão em Babilônia; também os avestruzes habitarão nela, e nunca mais será povoada, nem habitada de geração em geração,

[[v24-50-40]]

^<<v24-50-40,40>>^ como quando Deus destruiu a Sodoma, e a Gomorra, e às suas cidades vizinhas, diz o SENHOR; assim, ninguém habitará ali, nem morará nela homem algum.

[[v24-50-41]]

^<<v24-50-41,41>>^ Eis que um povo vem do Norte; grande nação e muitos reis se levantarão dos confins da terra.

[[v24-50-42]]

^<<v24-50-42,42>>^ Armam-se de arco e de lança; eles são cruéis e não conhecem a compaixão; a voz deles é como o mar, que brama; montam cavalos, cada um posto em ordem de batalha contra ti, ó filha da Babilônia.

[[v24-50-43]]

^<<v24-50-43,43>>^ O rei da Babilônia ouviu a fama deles, e desfaleceram as suas mãos; a angústia se apoderou dele, e dores, como as da mulher que está de parto.

[[v24-50-44]]

^<<v24-50-44,44>>^ Eis que, como sobe o leãozinho da floresta jordânica contra o rebanho em pasto verde, assim, num momento, arrojá-la-ei dali e lá estabelecerei a quem eu escolher. Pois quem é semelhante a mim? Quem me pedirá contas? E quem é o pastor que me poderá resistir?

[[v24-50-45]]

^<<v24-50-45,45>>^ Portanto, ouvi o conselho do SENHOR, que ele decretou contra Babilônia, e os desígnios que ele formou contra a terra dos caldeus; certamente, até os menores do rebanho serão arrastados, e as suas moradas, espantadas por causa deles.

[[v24-50-46]]

^<<v24-50-46,46>>^ Ao estrondo da tomada de Babilônia, estremeceu a terra; e o grito se ouviu entre as nações.

'''

xref:024-jeremias/024-jeremias-049.adoc#v24-49-0[&#60; Capítulo Anterior] | <<v24-50-0,Topo>> | xref:024-jeremias/024-jeremias-051.adoc#v24-51-0[Próximo Capítulo &#62;]