include::./index.adoc[]

[[v24-5-0]]
=== Jeremias, 5
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-5-1]]

^<<v24-5-1,1>>^ Dai voltas às ruas de Jerusalém; vede agora, procurai saber, buscai pelas suas praças a ver se achais alguém, se há um homem que pratique a justiça ou busque a verdade; e eu lhe perdoarei a ela.

[[v24-5-2]]

^<<v24-5-2,2>>^ Embora digam: Tão certo como vive o SENHOR, certamente, juram falso.

[[v24-5-3]]

^<<v24-5-3,3>>^ Ah! SENHOR, não é para a fidelidade que atentam os teus olhos? Tu os feriste, e não lhes doeu; consumiste-os, e não quiseram receber a disciplina; endureceram o rosto mais do que uma rocha; não quiseram voltar.

[[v24-5-4]]

^<<v24-5-4,4>>^ Mas eu pensei: são apenas os pobres que são insensatos, pois não sabem o caminho do SENHOR, o direito do seu Deus.

[[v24-5-5]]

^<<v24-5-5,5>>^ Irei aos grandes e falarei com eles; porque eles sabem o caminho do SENHOR, o direito do seu Deus; mas estes, de comum acordo, quebraram o jugo e romperam as algemas.

[[v24-5-6]]

^<<v24-5-6,6>>^ Por isso, um leão do bosque os matará, um lobo dos desertos os assolará, um leopardo estará à espreita das suas cidades; qualquer que sair delas será despedaçado; porque as suas transgressões se multiplicaram, multiplicaram-se as suas perfídias.

[[v24-5-7]]

^<<v24-5-7,7>>^ Como, vendo isto, te perdoaria? Teus filhos me deixam a mim e juram pelos que não são deuses; depois de eu os ter fartado, adulteraram e em casa de meretrizes se ajuntaram em bandos;

[[v24-5-8]]

^<<v24-5-8,8>>^ como garanhões bem fartos, correm de um lado para outro, cada um rinchando à mulher do seu companheiro.

[[v24-5-9]]

^<<v24-5-9,9>>^ Deixaria eu de castigar estas coisas, diz o SENHOR, ou não me vingaria de nação como esta?

[[v24-5-10]]

^<<v24-5-10,10>>^ Subi vós aos terraços da vinha, destruí-a, porém não de todo; tirai-lhe as gavinhas, porque não são do SENHOR.

[[v24-5-11]]

^<<v24-5-11,11>>^ Porque perfidamente se houveram contra mim, a casa de Israel e a casa de Judá, diz o SENHOR.

[[v24-5-12]]

^<<v24-5-12,12>>^ Negaram ao SENHOR e disseram: Não é ele; e: Nenhum mal nos sobrevirá; não veremos espada nem fome.

[[v24-5-13]]

^<<v24-5-13,13>>^ Até os profetas não passam de vento, porque a palavra não está com eles, as suas ameaças se cumprirão contra eles mesmos.

[[v24-5-14]]

^<<v24-5-14,14>>^ Portanto, assim diz o SENHOR, o Deus dos Exércitos: Visto que proferiram eles tais palavras, eis que converterei em fogo as minhas palavras na tua boca e a este povo, em lenha, e eles serão consumidos.

[[v24-5-15]]

^<<v24-5-15,15>>^ Eis que trago sobre ti uma nação de longe, ó casa de Israel, diz o SENHOR; nação robusta, nação antiga, nação cuja língua ignoras; e não entendes o que ela fala.

[[v24-5-16]]

^<<v24-5-16,16>>^ A sua aljava é como uma sepultura aberta; todos os seus homens são valentes.

[[v24-5-17]]

^<<v24-5-17,17>>^ Comerão a tua sega e o teu pão, os teus filhos e as tuas filhas; comerão as tuas ovelhas e o teu gado; comerão a tua vide e a tua figueira; e com a espada derribarão as tuas cidades fortificadas, em que confias.

[[v24-5-18]]

^<<v24-5-18,18>>^ Contudo, ainda naqueles dias, diz o SENHOR, não vos destruirei de todo.

[[v24-5-19]]

^<<v24-5-19,19>>^ Quando disserem: Por que nos fez o SENHOR, nosso Deus, todas estas coisas? Então, lhes responderás: Como vós me deixastes e servistes a deuses estranhos na vossa terra, assim servireis a estrangeiros, em terra que não é vossa.

[[v24-5-20]]

^<<v24-5-20,20>>^ Anunciai isto na casa de Jacó e fazei-o ouvir em Judá, dizendo:

[[v24-5-21]]

^<<v24-5-21,21>>^ Ouvi agora isto, ó povo insensato e sem entendimento, que tendes olhos e não vedes, tendes ouvidos e não ouvis.

[[v24-5-22]]

^<<v24-5-22,22>>^ Não temereis a mim? — diz o SENHOR; não tremereis diante de mim, que pus a areia para limite do mar, limite perpétuo, que ele não traspassará? Ainda que se levantem as suas ondas, não prevalecerão; ainda que bramem, não o traspassarão.

[[v24-5-23]]

^<<v24-5-23,23>>^ Mas este povo é de coração rebelde e contumaz; rebelaram-se e foram-se.

[[v24-5-24]]

^<<v24-5-24,24>>^ Não dizem a eles mesmos: Temamos agora ao SENHOR, nosso Deus, que nos dá a seu tempo a chuva, a primeira e a última, que nos conserva as semanas determinadas da sega.

[[v24-5-25]]

^<<v24-5-25,25>>^ As vossas iniquidades desviam estas coisas, e os vossos pecados afastam de vós o bem.

[[v24-5-26]]

^<<v24-5-26,26>>^ Porque entre o meu povo se acham perversos; cada um anda espiando, como espreitam os passarinheiros; como eles, dispõem armadilhas e prendem os homens.

[[v24-5-27]]

^<<v24-5-27,27>>^ Como a gaiola cheia de pássaros, são as suas casas cheias de fraude; por isso, se tornaram poderosos e enriqueceram.

[[v24-5-28]]

^<<v24-5-28,28>>^ Engordam, tornam-se nédios e ultrapassam até os feitos dos malignos; não defendem a causa, a causa dos órfãos, para que prospere; nem julgam o direito dos necessitados.

[[v24-5-29]]

^<<v24-5-29,29>>^ Não castigaria eu estas coisas? — diz o SENHOR; não me vingaria eu de nação como esta?

[[v24-5-30]]

^<<v24-5-30,30>>^ Coisa espantosa e horrenda se anda fazendo na terra:

[[v24-5-31]]

^<<v24-5-31,31>>^ os profetas profetizam falsamente, e os sacerdotes dominam de mãos dadas com eles; e é o que deseja o meu povo. Porém que fareis quando estas coisas chegarem ao seu fim?

'''

xref:024-jeremias/024-jeremias-004.adoc#v24-4-0[&#60; Capítulo Anterior] | <<v24-5-0,Topo>> | xref:024-jeremias/024-jeremias-006.adoc#v24-6-0[Próximo Capítulo &#62;]