include::./index.adoc[]

[[v24-10-0]]
=== Jeremias, 10
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-10-1]]

^<<v24-10-1,1>>^ Ouvi a palavra que o SENHOR vos fala a vós outros, ó casa de Israel.

[[v24-10-2]]

^<<v24-10-2,2>>^ Assim diz o SENHOR: Não aprendais o caminho dos gentios, nem vos espanteis com os sinais dos céus, porque com eles os gentios se atemorizam.

[[v24-10-3]]

^<<v24-10-3,3>>^ Porque os costumes dos povos são vaidade; pois cortam do bosque um madeiro, obra das mãos do artífice, com machado;

[[v24-10-4]]

^<<v24-10-4,4>>^ com prata e ouro o enfeitam, com pregos e martelos o fixam, para que não oscile.

[[v24-10-5]]

^<<v24-10-5,5>>^ Os ídolos são como um espantalho em pepinal e não podem falar; necessitam de quem os leve, porquanto não podem andar. Não tenhais receio deles, pois não podem fazer mal, e não está neles o fazer o bem.

[[v24-10-6]]

^<<v24-10-6,6>>^ Ninguém há semelhante a ti, ó SENHOR; tu és grande, e grande é o poder do teu nome.

[[v24-10-7]]

^<<v24-10-7,7>>^ Quem te não temeria a ti, ó Rei das nações? Pois isto é a ti devido; porquanto, entre todos os sábios das nações e em todo o seu reino, ninguém há semelhante a ti.

[[v24-10-8]]

^<<v24-10-8,8>>^ Mas eles todos se tornaram estúpidos e loucos; seu ensino é vão e morto como um pedaço de madeira.

[[v24-10-9]]

^<<v24-10-9,9>>^ Traz-se prata batida de Társis e ouro de Ufaz; os ídolos são obra de artífice e de mãos de ourives; azuis e púrpuras são as suas vestes; todos eles são obra de homens hábeis.

[[v24-10-10]]

^<<v24-10-10,10>>^ Mas o SENHOR é verdadeiramente Deus; ele é o Deus vivo e o Rei eterno; do seu furor treme a terra, e as nações não podem suportar a sua indignação.

[[v24-10-11]]

^<<v24-10-11,11>>^ Assim lhes direis: Os deuses que não fizeram os céus e a terra desaparecerão da terra e de debaixo destes céus.

[[v24-10-12]]

^<<v24-10-12,12>>^ O SENHOR fez a terra pelo seu poder; estabeleceu o mundo por sua sabedoria e com a sua inteligência estendeu os céus.

[[v24-10-13]]

^<<v24-10-13,13>>^ Fazendo ele ribombar o trovão, logo há tumulto de águas no céu, e sobem os vapores das extremidades da terra; ele cria os relâmpagos para a chuva e dos seus depósitos faz sair o vento.

[[v24-10-14]]

^<<v24-10-14,14>>^ Todo homem se tornou estúpido e não tem saber; todo ourives é envergonhado pela imagem que ele mesmo esculpiu; pois as suas imagens são mentira, e nelas não há fôlego.

[[v24-10-15]]

^<<v24-10-15,15>>^ Vaidade são, obra ridícula; no tempo do seu castigo, virão a perecer.

[[v24-10-16]]

^<<v24-10-16,16>>^ Não é semelhante a estas Aquele que é a Porção de Jacó; porque ele é o Criador de todas as coisas, e Israel é a tribo da sua herança; SENHOR dos Exércitos é o seu nome.

[[v24-10-17]]

^<<v24-10-17,17>>^ Tira do chão a tua trouxa, ó filha de Sião, que moras em lugar sitiado.

[[v24-10-18]]

^<<v24-10-18,18>>^ Porque assim diz o SENHOR: Eis que desta vez arrojarei para fora os moradores da terra e os angustiarei, para que venham a senti-lo.

[[v24-10-19]]

^<<v24-10-19,19>>^ Ai de mim, por causa da minha ruína! É mui grave a minha ferida; então, eu disse: com efeito, é isto o meu sofrimento, e tenho de suportá-lo.

[[v24-10-20]]

^<<v24-10-20,20>>^ A minha tenda foi destruída, todas as cordas se romperam; os meus filhos se foram e já não existem; ninguém há que levante a minha tenda e lhe erga as lonas.

[[v24-10-21]]

^<<v24-10-21,21>>^ Porque os pastores se tornaram estúpidos e não buscaram ao SENHOR; por isso, não prosperaram, e todos os seus rebanhos se acham dispersos.

[[v24-10-22]]

^<<v24-10-22,22>>^ Eis aí um rumor! Eis que vem grande tumulto da terra do Norte, para fazer das cidades de Judá uma assolação, morada de chacais.

[[v24-10-23]]

^<<v24-10-23,23>>^ Eu sei, ó SENHOR, que não cabe ao homem determinar o seu caminho, nem ao que caminha o dirigir os seus passos.

[[v24-10-24]]

^<<v24-10-24,24>>^ Castiga-me, ó SENHOR, mas em justa medida, não na tua ira, para que não me reduzas a nada.

[[v24-10-25]]

^<<v24-10-25,25>>^ Derrama a tua indignação sobre as nações que não te conhecem e sobre os povos que não invocam o teu nome; porque devoraram a Jacó, devoraram-no, consumiram-no e assolaram a sua morada.

'''

xref:024-jeremias/024-jeremias-009.adoc#v24-9-0[&#60; Capítulo Anterior] | <<v24-10-0,Topo>> | xref:024-jeremias/024-jeremias-011.adoc#v24-11-0[Próximo Capítulo &#62;]