include::./index.adoc[]

[[v24-1-0]]
=== Jeremias, 1
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-1-1]]

^<<v24-1-1,1>>^ Palavras de Jeremias, filho de Hilquias, um dos sacerdotes que estavam em Anatote, na terra de Benjamim;

[[v24-1-2]]

^<<v24-1-2,2>>^ a ele veio a palavra do SENHOR, nos dias de Josias, filho de Amom e rei de Judá, no décimo terceiro ano do seu reinado;

[[v24-1-3]]

^<<v24-1-3,3>>^ e também nos dias de Jeoaquim, filho de Josias, rei de Judá, até ao fim do ano undécimo de Zedequias, filho de Josias, rei de Judá, e ainda até ao quinto mês do exílio de Jerusalém.

[[v24-1-4]]

^<<v24-1-4,4>>^ A mim me veio, pois, a palavra do SENHOR, dizendo:

[[v24-1-5]]

^<<v24-1-5,5>>^ Antes que eu te formasse no ventre materno, eu te conheci, e, antes que saísses da madre, te consagrei, e te constituí profeta às nações.

[[v24-1-6]]

^<<v24-1-6,6>>^ Então, lhe disse eu: ah! SENHOR Deus! Eis que não sei falar, porque não passo de uma criança.

[[v24-1-7]]

^<<v24-1-7,7>>^ Mas o SENHOR me disse: Não digas: Não passo de uma criança; porque a todos a quem eu te enviar irás; e tudo quanto eu te mandar falarás.

[[v24-1-8]]

^<<v24-1-8,8>>^ Não temas diante deles, porque eu sou contigo para te livrar, diz o SENHOR.

[[v24-1-9]]

^<<v24-1-9,9>>^ Depois, estendeu o SENHOR a mão, tocou-me na boca e o SENHOR me disse: Eis que ponho na tua boca as minhas palavras.

[[v24-1-10]]

^<<v24-1-10,10>>^ Olha que hoje te constituo sobre as nações e sobre os reinos, para arrancares e derribares, para destruíres e arruinares e também para edificares e para plantares.

[[v24-1-11]]

^<<v24-1-11,11>>^ Veio ainda a palavra do SENHOR, dizendo: Que vês tu, Jeremias? Respondi: vejo uma vara de amendoeira.

[[v24-1-12]]

^<<v24-1-12,12>>^ Disse-me o SENHOR: Viste bem, porque eu velo sobre a minha palavra para a cumprir.

[[v24-1-13]]

^<<v24-1-13,13>>^ Outra vez, me veio a palavra do SENHOR, dizendo: Que vês? Eu respondi: vejo uma panela ao fogo, cuja boca se inclina do Norte.

[[v24-1-14]]

^<<v24-1-14,14>>^ Disse-me o SENHOR: Do Norte se derramará o mal sobre todos os habitantes da terra.

[[v24-1-15]]

^<<v24-1-15,15>>^ Pois eis que convoco todas as tribos dos reinos do Norte, diz o SENHOR; e virão, e cada reino porá o seu trono à entrada das portas de Jerusalém e contra todos os seus muros em redor e contra todas as cidades de Judá.

[[v24-1-16]]

^<<v24-1-16,16>>^ Pronunciarei contra os moradores destas as minhas sentenças, por causa de toda a malícia deles; pois me deixaram a mim, e queimaram incenso a deuses estranhos, e adoraram as obras das suas próprias mãos.

[[v24-1-17]]

^<<v24-1-17,17>>^ Tu, pois, cinge os lombos, dispõe-te e dize-lhes tudo quanto eu te mandar; não te espantes diante deles, para que eu não te infunda espanto na sua presença.

[[v24-1-18]]

^<<v24-1-18,18>>^ Eis que hoje te ponho por cidade fortificada, por coluna de ferro e por muros de bronze, contra todo o país, contra os reis de Judá, contra os seus príncipes, contra os seus sacerdotes e contra o seu povo.

[[v24-1-19]]

^<<v24-1-19,19>>^ Pelejarão contra ti, mas não prevalecerão; porque eu sou contigo, diz o SENHOR, para te livrar.

'''

xref:023-isaias/023-isaias-066.adoc#v23-66-0[&#60; Capítulo Anterior] | <<v24-1-0,Topo>> | xref:024-jeremias/024-jeremias-002.adoc#v24-2-0[Próximo Capítulo &#62;]