include::./index.adoc[]

[[v24-23-0]]
=== Jeremias, 23
// ara ?, ARA - Almeida Revista e Atualizada

[[v24-23-1]]

^<<v24-23-1,1>>^ Ai dos pastores que destroem e dispersam as ovelhas do meu pasto! — diz o SENHOR.

[[v24-23-2]]

^<<v24-23-2,2>>^ Portanto, assim diz o SENHOR, o Deus de Israel, contra os pastores que apascentam o meu povo: Vós dispersastes as minhas ovelhas, e as afugentastes, e delas não cuidastes; mas eu cuidarei em vos castigar a maldade das vossas ações, diz o SENHOR.

[[v24-23-3]]

^<<v24-23-3,3>>^ Eu mesmo recolherei o restante das minhas ovelhas, de todas as terras para onde as tiver afugentado, e as farei voltar aos seus apriscos; serão fecundas e se multiplicarão.

[[v24-23-4]]

^<<v24-23-4,4>>^ Levantarei sobre elas pastores que as apascentem, e elas jamais temerão, nem se espantarão; nem uma delas faltará, diz o SENHOR.

[[v24-23-5]]

^<<v24-23-5,5>>^ Eis que vêm dias, diz o SENHOR, em que levantarei a Davi um Renovo justo; e, rei que é, reinará, e agirá sabiamente, e executará o juízo e a justiça na terra.

[[v24-23-6]]

^<<v24-23-6,6>>^ Nos seus dias, Judá será salvo, e Israel habitará seguro; será este o seu nome, com que será chamado: SENHOR, Justiça Nossa.

[[v24-23-7]]

^<<v24-23-7,7>>^ Portanto, eis que vêm dias, diz o SENHOR, em que nunca mais dirão: Tão certo como vive o SENHOR, que fez subir os filhos de Israel da terra do Egito;

[[v24-23-8]]

^<<v24-23-8,8>>^ mas: Tão certo como vive o SENHOR, que fez subir, que trouxe a descendência da casa de Israel da terra do Norte e de todas as terras para onde os tinha arrojado; e habitarão na sua terra.

[[v24-23-9]]

^<<v24-23-9,9>>^ Acerca dos profetas. O meu coração está quebrantado dentro de mim; todos os meus ossos estremecem; sou como homem embriagado e como homem vencido pelo vinho, por causa do SENHOR e por causa das suas santas palavras.

[[v24-23-10]]

^<<v24-23-10,10>>^ Porque a terra está cheia de adúlteros e chora por causa da maldição divina; os pastos do deserto se secam; pois a carreira dos adúlteros é má, e a sua força não é reta.

[[v24-23-11]]

^<<v24-23-11,11>>^ Pois estão contaminados, tanto o profeta como o sacerdote; até na minha casa achei a sua maldade, diz o SENHOR.

[[v24-23-12]]

^<<v24-23-12,12>>^ Portanto, o caminho deles será como lugares escorregadios na escuridão; serão empurrados e cairão nele; porque trarei sobre eles calamidade, o ano mesmo em que os castigarei, diz o SENHOR.

[[v24-23-13]]

^<<v24-23-13,13>>^ Nos profetas de Samaria bem vi eu loucura; profetizavam da parte de Baal e faziam errar o meu povo de Israel.

[[v24-23-14]]

^<<v24-23-14,14>>^ Mas nos profetas de Jerusalém vejo coisa horrenda; cometem adultérios, andam com falsidade e fortalecem as mãos dos malfeitores, para que não se convertam cada um da sua maldade; todos eles se tornaram para mim como Sodoma, e os moradores de Jerusalém, como Gomorra.

[[v24-23-15]]

^<<v24-23-15,15>>^ Portanto, assim diz o SENHOR dos Exércitos acerca dos profetas: Eis que os alimentarei com absinto e lhes darei a beber água venenosa; porque dos profetas de Jerusalém se derramou a impiedade sobre toda a terra.

[[v24-23-16]]

^<<v24-23-16,16>>^ Assim diz o SENHOR dos Exércitos: Não deis ouvidos às palavras dos profetas que entre vós profetizam e vos enchem de vãs esperanças; falam as visões do seu coração, não o que vem da boca do SENHOR.

[[v24-23-17]]

^<<v24-23-17,17>>^ Dizem continuamente aos que me desprezam: O SENHOR disse: Paz tereis; e a qualquer que anda segundo a dureza do seu coração dizem: Não virá mal sobre vós.

[[v24-23-18]]

^<<v24-23-18,18>>^ Porque quem esteve no conselho do SENHOR, e viu, e ouviu a sua palavra? Quem esteve atento à sua palavra e a ela atendeu?

[[v24-23-19]]

^<<v24-23-19,19>>^ Eis a tempestade do SENHOR! O furor saiu, e um redemoinho tempestuou sobre a cabeça dos perversos.

[[v24-23-20]]

^<<v24-23-20,20>>^ Não se desviará a ira do SENHOR, até que ele execute e cumpra os desígnios do seu coração; nos últimos dias, entendereis isso claramente.

[[v24-23-21]]

^<<v24-23-21,21>>^ Não mandei esses profetas; todavia, eles foram correndo; não lhes falei a eles; contudo, profetizaram.

[[v24-23-22]]

^<<v24-23-22,22>>^ Mas, se tivessem estado no meu conselho, então, teriam feito ouvir as minhas palavras ao meu povo e o teriam feito voltar do seu mau caminho e da maldade das suas ações.

[[v24-23-23]]

^<<v24-23-23,23>>^ Acaso, sou Deus apenas de perto, diz o SENHOR, e não também de longe?

[[v24-23-24]]

^<<v24-23-24,24>>^ Ocultar-se-ia alguém em esconderijos, de modo que eu não o veja? — diz o SENHOR; porventura, não encho eu os céus e a terra? — diz o SENHOR.

[[v24-23-25]]

^<<v24-23-25,25>>^ Tenho ouvido o que dizem aqueles profetas, proclamando mentiras em meu nome, dizendo: Sonhei, sonhei.

[[v24-23-26]]

^<<v24-23-26,26>>^ Até quando sucederá isso no coração dos profetas que proclamam mentiras, que proclamam só o engano do próprio coração?

[[v24-23-27]]

^<<v24-23-27,27>>^ Os quais cuidam em fazer que o meu povo se esqueça do meu nome pelos seus sonhos que cada um conta ao seu companheiro, assim como seus pais se esqueceram do meu nome, por causa de Baal.

[[v24-23-28]]

^<<v24-23-28,28>>^ O profeta que tem sonho conte-o como apenas sonho; mas aquele em quem está a minha palavra fale a minha palavra com verdade. Que tem a palha com o trigo? — diz o SENHOR.

[[v24-23-29]]

^<<v24-23-29,29>>^ Não é a minha palavra fogo, diz o SENHOR, e martelo que esmiúça a penha?

[[v24-23-30]]

^<<v24-23-30,30>>^ Portanto, eis que eu sou contra esses profetas, diz o SENHOR, que furtam as minhas palavras, cada um ao seu companheiro.

[[v24-23-31]]

^<<v24-23-31,31>>^ Eis que eu sou contra esses profetas, diz o SENHOR, que pregam a sua própria palavra e afirmam: Ele disse.

[[v24-23-32]]

^<<v24-23-32,32>>^ Eis que eu sou contra os que profetizam sonhos mentirosos, diz o SENHOR, e os contam, e com as suas mentiras e leviandades fazem errar o meu povo; pois eu não os enviei, nem lhes dei ordem; e também proveito nenhum trouxeram a este povo, diz o SENHOR.

[[v24-23-33]]

^<<v24-23-33,33>>^ Quando, pois, este povo te perguntar, ou qualquer profeta, ou sacerdote, dizendo: Qual é a sentença pesada do SENHOR? Então, lhe dirás: Vós sois o peso, e eu vos arrojarei, diz o SENHOR.

[[v24-23-34]]

^<<v24-23-34,34>>^ Quanto ao profeta, e ao sacerdote, e ao povo que disser: Sentença pesada do SENHOR, a esse homem eu castigarei e a sua casa.

[[v24-23-35]]

^<<v24-23-35,35>>^ Antes, direis, cada um ao seu companheiro e cada um ao seu irmão: Que respondeu o SENHOR? Que falou o SENHOR?

[[v24-23-36]]

^<<v24-23-36,36>>^ Mas nunca mais fareis menção da sentença pesada do SENHOR; porque a cada um lhe servirá de sentença pesada a sua própria palavra; pois torceis as palavras do Deus vivo, do SENHOR dos Exércitos, o nosso Deus.

[[v24-23-37]]

^<<v24-23-37,37>>^ Assim dirás ao profeta: Que te respondeu o SENHOR? Que falou o SENHOR?

[[v24-23-38]]

^<<v24-23-38,38>>^ Mas, porque dizeis: Sentença pesada do SENHOR, assim o diz o SENHOR: Porque dizeis esta palavra: Sentença pesada do SENHOR (havendo-vos eu proibido de dizerdes esta palavra: Sentença pesada do SENHOR),

[[v24-23-39]]

^<<v24-23-39,39>>^ por isso, levantar-vos-ei e vos arrojarei da minha presença, a vós outros e à cidade que vos dei e a vossos pais.

[[v24-23-40]]

^<<v24-23-40,40>>^ Porei sobre vós perpétuo opróbrio e eterna vergonha, que jamais será esquecida.

'''

xref:024-jeremias/024-jeremias-022.adoc#v24-22-0[&#60; Capítulo Anterior] | <<v24-23-0,Topo>> | xref:024-jeremias/024-jeremias-024.adoc#v24-24-0[Próximo Capítulo &#62;]